; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc --stop-after=finalize-isel %s -o - -mir-dbg-records -print-as-dbg-instrs \
; RUN: | FileCheck %s
; RUN: llc --stop-after=finalize-isel %s -o - | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @_ZN6EngineILi3Ed10MultiPatchI7GridTag6RemoteI5BrickEEE6notifyER10GridLayoutILi3EERK13ObserverEvent() !dbg !4 {
  ; CHECK-LABEL: name: _ZN6EngineILi3Ed10MultiPatchI7GridTag6RemoteI5BrickEEE6notifyER10GridLayoutILi3EERK13ObserverEvent
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV64rm:%[0-9]+]]:gr64 = MOV64rm $noreg, 1, $noreg, 0, $noreg, debug-instr-number 1 :: (load (s64) from `ptr null`)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.for.cond.preheader.i.i.i.i:
  ; CHECK-NEXT:   DBG_INSTR_REF !10, !DIExpression(DW_OP_LLVM_arg, 0), dbg-instr-ref(1, 0), debug-location !21
  ; CHECK-NEXT:   DBG_INSTR_REF !42, !DIExpression(DW_OP_LLVM_arg, 0, DW_OP_plus_uconst, 32, DW_OP_stack_value), dbg-instr-ref(1, 0), debug-location !48
  ; CHECK-NEXT:   [[MOV64rm1:%[0-9]+]]:gr64 = MOV64rm [[MOV64rm]], 1, $noreg, 32, $noreg, debug-location !61 :: (load (s64) from %ir.localEnginePtr_m.i.i.i.i.i.i)
  ; CHECK-NEXT:   MOV32mi killed [[MOV64rm1]], 1, $noreg, 0, $noreg, 0 :: (store (s32) into %ir.1)
  ; CHECK-NEXT:   RET 0
entry:
  %0 = load ptr, ptr null, align 8
  br label %for.cond.preheader.i.i.i.i

for.cond.preheader.i.i.i.i:                       ; preds = %entry
    #dbg_value(ptr %0, !10, !DIExpression(), !21)
  %localEnginePtr_m.i.i.i.i.i.i = getelementptr i8, ptr %0, i64 32
    #dbg_value(ptr %localEnginePtr_m.i.i.i.i.i.i, !42, !DIExpression(), !48)
  %1 = load ptr, ptr %localEnginePtr_m.i.i.i.i.i.i, align 8, !dbg !61
  store i32 0, ptr %1, align 4
  ret void
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 23.0.0git (https://github.com/OCHyams/llvm-project 7e489b3ebf9c337c8b6ea74bef9c4f45f2dc4fd9)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "x.cpp", directory: "/home/och/reduce", checksumkind: CSK_MD5, checksum: "a79402ede23ff238de3e4647c4f3a326")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DISubprogram(name: "notify", linkageName: "_ZN6EngineILi3Ed10MultiPatchI7GridTag6RemoteI5BrickEEE6notifyER10GridLayoutILi3EERK13ObserverEvent", scope: !5, file: !1, line: 30441, type: !7, scopeLine: 30442, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !9, retainedNodes: !2, keyInstructions: true)
!5 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Engine<3, double, MultiPatch<GridTag, Remote<Brick> > >", file: !1, line: 28278, size: 704, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, vtableHolder: !6, templateParams: !2, identifier: "_ZTS6EngineILi3Ed10MultiPatchI7GridTag6RemoteI5BrickEEE")
!6 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Observer<GridLayout<3> >", file: !1, line: 6229, size: 64, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, vtableHolder: !6, templateParams: !2, identifier: "_ZTS8ObserverI10GridLayoutILi3EEE")
!7 = distinct !DISubroutineType(types: !8)
!8 = !{null}
!9 = !DISubprogram(name: "notify", linkageName: "_ZN6EngineILi3Ed10MultiPatchI7GridTag6RemoteI5BrickEEE6notifyER10GridLayoutILi3EERK13ObserverEvent", scope: !5, file: !1, line: 30441, type: !7, scopeLine: 30441, containingType: !5, virtualIndex: 2, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!10 = !DILocalVariable(name: "pt", scope: !11, file: !1, line: 6829, type: !19)
!11 = distinct !DILexicalBlock(scope: !12, file: !1, line: 6829, column: 4)
!12 = distinct !DILexicalBlock(scope: !13, file: !1, line: 6828, column: 6)
!13 = distinct !DILexicalBlock(scope: !14, file: !1, line: 6827, column: 7)
!14 = distinct !DILexicalBlock(scope: !15, file: !1, line: 6826, column: 9)
!15 = distinct !DISubprogram(name: "deleteStorage", linkageName: "_ZN18RefBlockControllerI6EngineILi3Ed6RemoteI5BrickEEE13deleteStorageEv", scope: !16, file: !1, line: 6824, type: !17, scopeLine: 6825, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !18, retainedNodes: !2, keyInstructions: true)
!16 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "RefBlockController<Engine<3, double, Remote<Brick> > >", file: !1, line: 6680, size: 320, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS18RefBlockControllerI6EngineILi3Ed6RemoteI5BrickEEE")
!17 = distinct !DISubroutineType(types: !8)
!18 = !DISubprogram(name: "deleteStorage", linkageName: "_ZN18RefBlockControllerI6EngineILi3Ed6RemoteI5BrickEEE13deleteStorageEv", scope: !16, file: !1, line: 6824, type: !17, scopeLine: 6824, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!19 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !20, size: 64)
!20 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Engine<3, double, Remote<Brick> >", file: !1, line: 33776, size: 320, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS6EngineILi3Ed6RemoteI5BrickEE")
!21 = !DILocation(line: 0, scope: !11, inlinedAt: !22)
!22 = distinct !DILocation(line: 6731, column: 5, scope: !23, inlinedAt: !26)
!23 = distinct !DILexicalBlock(scope: !24, file: !1, line: 6730, column: 3)
!24 = distinct !DISubprogram(name: "~RefBlockController", linkageName: "_ZN18RefBlockControllerI6EngineILi3Ed6RemoteI5BrickEEED2Ev", scope: !16, file: !1, line: 6729, type: !17, scopeLine: 6730, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !25, retainedNodes: !2, keyInstructions: true)
!25 = !DISubprogram(name: "~RefBlockController", linkageName: "_ZN18RefBlockControllerI6EngineILi3Ed6RemoteI5BrickEEED4Ev", scope: !16, file: !1, line: 6729, type: !17, scopeLine: 6729, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!26 = distinct !DILocation(line: 6647, column: 2, scope: !27, inlinedAt: !34)
!27 = distinct !DILexicalBlock(scope: !28, file: !1, line: 6646, column: 12)
!28 = distinct !DILexicalBlock(scope: !29, file: !1, line: 6645, column: 5)
!29 = distinct !DILexicalBlock(scope: !30, file: !1, line: 6644, column: 7)
!30 = distinct !DISubprogram(name: "operator=", linkageName: "_ZN13RefCountedPtrI18RefBlockControllerI6EngineILi3Ed6RemoteI5BrickEEEEaSERKS7_", scope: !31, file: !1, line: 6642, type: !32, scopeLine: 6643, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !33, retainedNodes: !2, keyInstructions: true)
!31 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "RefCountedPtr<RefBlockController<Engine<3, double, Remote<Brick> > > >", file: !1, line: 6595, size: 64, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS13RefCountedPtrI18RefBlockControllerI6EngineILi3Ed6RemoteI5BrickEEEE")
!32 = distinct !DISubroutineType(types: !2)
!33 = !DISubprogram(name: "operator=", linkageName: "_ZN13RefCountedPtrI18RefBlockControllerI6EngineILi3Ed6RemoteI5BrickEEEEaSERKS7_", scope: !31, file: !1, line: 6642, type: !32, scopeLine: 6642, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!34 = distinct !DILocation(line: 6925, column: 26, scope: !35, inlinedAt: !39)
!35 = distinct !DISubprogram(name: "operator=", linkageName: "_ZN18RefCountedBlockPtrI6EngineILi3Ed6RemoteI5BrickEELb0E18RefBlockControllerIS4_EEaSERKS7_", scope: !36, file: !1, line: 6923, type: !37, scopeLine: 6924, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !38, retainedNodes: !2, keyInstructions: true)
!36 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "RefCountedBlockPtr<Engine<3, double, Remote<Brick> >, false, RefBlockController<Engine<3, double, Remote<Brick> > > >", file: !1, line: 6869, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS18RefCountedBlockPtrI6EngineILi3Ed6RemoteI5BrickEELb0E18RefBlockControllerIS4_EE")
!37 = distinct !DISubroutineType(types: !2)
!38 = !DISubprogram(name: "operator=", linkageName: "_ZN18RefCountedBlockPtrI6EngineILi3Ed6RemoteI5BrickEELb0E18RefBlockControllerIS4_EEaSERKS7_", scope: !36, file: !1, line: 6923, type: !37, scopeLine: 6923, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!39 = distinct !DILocation(line: 30461, column: 14, scope: !40)
!40 = distinct !DILexicalBlock(scope: !41, file: !1, line: 30445, column: 5)
!41 = distinct !DILexicalBlock(scope: !4, file: !1, line: 30444, column: 6)
!42 = !DILocalVariable(name: "this", arg: 1, scope: !43, type: !47, flags: DIFlagArtificial | DIFlagObjectPointer)
!43 = distinct !DISubprogram(name: "~RefCountedPtr", linkageName: "_ZN13RefCountedPtrI6SharedI6EngineILi3Ed5BrickEEED2Ev", scope: !44, file: !1, line: 6636, type: !45, scopeLine: 6637, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !46, retainedNodes: !2, keyInstructions: true)
!44 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "RefCountedPtr<Shared<Engine<3, double, Brick> > >", file: !1, line: 6595, size: 64, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS13RefCountedPtrI6SharedI6EngineILi3Ed5BrickEEE")
!45 = distinct !DISubroutineType(types: !8)
!46 = !DISubprogram(name: "~RefCountedPtr", linkageName: "_ZN13RefCountedPtrI6SharedI6EngineILi3Ed5BrickEEED4Ev", scope: !44, file: !1, line: 6636, type: !45, scopeLine: 6636, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!47 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !44, size: 64)
!48 = !DILocation(line: 0, scope: !43, inlinedAt: !49)
!49 = distinct !DILocation(line: 34225, column: 1, scope: !50, inlinedAt: !54)
!50 = distinct !DILexicalBlock(scope: !51, file: !1, line: 34224, column: 1)
!51 = distinct !DISubprogram(name: "~Engine", linkageName: "_ZN6EngineILi3Ed6RemoteI5BrickEED2Ev", scope: !20, file: !1, line: 34223, type: !52, scopeLine: 34224, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !53, retainedNodes: !2, keyInstructions: true)
!52 = distinct !DISubroutineType(types: !8)
!53 = !DISubprogram(name: "~Engine", linkageName: "_ZN6EngineILi3Ed6RemoteI5BrickEED4Ev", scope: !20, file: !1, line: 34223, type: !52, scopeLine: 34223, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!54 = distinct !DILocation(line: 6443, column: 12, scope: !55, inlinedAt: !59)
!55 = distinct !DISubprogram(name: "destruct", linkageName: "_ZN21MakeOwnCopyPropertiesI6EngineILi3Ed6RemoteI5BrickEEE8destructEPS4_", scope: !56, file: !1, line: 6441, type: !57, scopeLine: 6442, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !58, retainedNodes: !2, keyInstructions: true)
!56 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "MakeOwnCopyProperties<Engine<3, double, Remote<Brick> > >", file: !1, line: 6418, size: 8, flags: DIFlagTypePassByValue, elements: !2, templateParams: !2, identifier: "_ZTS21MakeOwnCopyPropertiesI6EngineILi3Ed6RemoteI5BrickEEE")
!57 = distinct !DISubroutineType(types: !8)
!58 = !DISubprogram(name: "destruct", linkageName: "_ZN21MakeOwnCopyPropertiesI6EngineILi3Ed6RemoteI5BrickEEE8destructEPS4_", scope: !56, file: !1, line: 6441, type: !57, scopeLine: 6441, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!59 = distinct !DILocation(line: 6830, column: 6, scope: !60, inlinedAt: !22)
!60 = distinct !DILexicalBlock(scope: !11, file: !1, line: 6829, column: 4)
!61 = !DILocation(line: 6617, column: 40, scope: !62, inlinedAt: !65)
!62 = distinct !DISubprogram(name: "isValid", linkageName: "_ZNK13RefCountedPtrI6SharedI6EngineILi3Ed5BrickEEE7isValidEv", scope: !44, file: !1, line: 6617, type: !63, scopeLine: 6617, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !64, retainedNodes: !2, keyInstructions: true)
!63 = distinct !DISubroutineType(types: !2)
!64 = !DISubprogram(name: "isValid", linkageName: "_ZNK13RefCountedPtrI6SharedI6EngineILi3Ed5BrickEEE7isValidEv", scope: !44, file: !1, line: 6617, type: !63, scopeLine: 6617, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!65 = distinct !DILocation(line: 6631, column: 8, scope: !66, inlinedAt: !69)
!66 = distinct !DILexicalBlock(scope: !67, file: !1, line: 6631, column: 8)
!67 = distinct !DISubprogram(name: "invalidate", linkageName: "_ZN13RefCountedPtrI6SharedI6EngineILi3Ed5BrickEEE10invalidateEv", scope: !44, file: !1, line: 6629, type: !45, scopeLine: 6630, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !68, retainedNodes: !2, keyInstructions: true)
!68 = !DISubprogram(name: "invalidate", linkageName: "_ZN13RefCountedPtrI6SharedI6EngineILi3Ed5BrickEEE10invalidateEv", scope: !44, file: !1, line: 6629, type: !45, scopeLine: 6629, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!69 = distinct !DILocation(line: 6638, column: 3, scope: !70, inlinedAt: !49)
!70 = distinct !DILexicalBlock(scope: !43, file: !1, line: 6637, column: 1)
