; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc --stop-after=finalize-isel %s -o - -mir-dbg-records -print-as-dbg-instrs \
; RUN: | FileCheck %s
; RUN: llc --stop-after=finalize-isel %s -o - | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @_ZN6InformC2EPKci(ptr %this) !dbg !4 {
  ; CHECK-LABEL: name: _ZN6InformC2EPKci
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $rdi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr64 = COPY $rdi
  ; CHECK-NEXT:   DBG_VALUE 0, $noreg, !9, !DIExpression(), debug-location !21
  ; CHECK-NEXT:   [[ADD64ri32_:%[0-9]+]]:gr64 = ADD64ri32 [[COPY]], 16, implicit-def dead $eflags, debug-location !23
  ; CHECK-NEXT:   MOV64mr $noreg, 1, $noreg, 0, $noreg, killed [[ADD64ri32_]] :: (store (s64) into `ptr null`)
  ; CHECK-NEXT:   RET 0
entry:
    #dbg_value(ptr null, !9, !DIExpression(), !21)
  %0 = getelementptr i8, ptr %this, i64 16, !dbg !23
  store ptr %0, ptr null, align 8
  ret void
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 23.0.0git (https://github.com/OCHyams/llvm-project 7e489b3ebf9c337c8b6ea74bef9c4f45f2dc4fd9)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "x.cpp", directory: "/home/och/reduce", checksumkind: CSK_MD5, checksum: "a79402ede23ff238de3e4647c4f3a326")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DISubprogram(name: "Inform", linkageName: "_ZN6InformC2EPKci", scope: !5, file: !1, line: 52482, type: !6, scopeLine: 52485, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !8, retainedNodes: !2, keyInstructions: true)
!5 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Inform", file: !1, line: 204, size: 896, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, identifier: "_ZTS6Inform")
!6 = distinct !DISubroutineType(types: !7)
!7 = !{null}
!8 = !DISubprogram(name: "Inform", linkageName: "_ZN6InformC4EPKci", scope: !5, file: !1, line: 213, type: !6, scopeLine: 213, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!9 = !DILocalVariable(name: "__s", arg: 2, scope: !10, file: !11, line: 533, type: !18)
!10 = distinct !DISubprogram(name: "basic_string<std::allocator<char> >", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2IS3_EEPKcRKS3_", scope: !12, file: !11, line: 533, type: !16, scopeLine: 535, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !2, declaration: !17, retainedNodes: !2, keyInstructions: true)
!11 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h", directory: "")
!12 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "basic_string<char, std::char_traits<char>, std::allocator<char> >", scope: !14, file: !13, line: 1627, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTSNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE")
!13 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.tcc", directory: "")
!14 = !DINamespace(name: "__cxx11", scope: !15, exportSymbols: true)
!15 = !DINamespace(name: "std", scope: null)
!16 = distinct !DISubroutineType(types: !7)
!17 = !DISubprogram(name: "basic_string<std::allocator<char> >", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC4IS3_EEPKcRKS3_", scope: !12, file: !11, line: 533, type: !16, scopeLine: 533, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized, templateParams: !2)
!18 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !19, size: 64)
!19 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !20)
!20 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
!21 = !DILocation(line: 0, scope: !10, inlinedAt: !22)
!22 = distinct !DILocation(line: 52483, column: 5, scope: !4)
!23 = !DILocation(line: 201, column: 51, scope: !24, inlinedAt: !27)
!24 = distinct !DISubprogram(name: "_M_local_data", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_M_local_dataEv", scope: !12, file: !11, line: 198, type: !25, scopeLine: 199, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !26, retainedNodes: !2, keyInstructions: true)
!25 = distinct !DISubroutineType(types: !2)
!26 = !DISubprogram(name: "_M_local_data", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_M_local_dataEv", scope: !12, file: !11, line: 198, type: !25, scopeLine: 198, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!27 = distinct !DILocation(line: 534, column: 21, scope: !10, inlinedAt: !22)
