; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc --stop-after=finalize-isel %s -o - -mir-dbg-records -print-as-dbg-instrs \
; RUN: | FileCheck %s
; RUN: llc --stop-after=finalize-isel %s -o - | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @_ZN5Pooma15PatchSizeSyncerC2EiR4GridILi1EE() !dbg !4 {
  ; CHECK-LABEL: name: _ZN5Pooma15PatchSizeSyncerC2EiR4GridILi1EE
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV32ri64_:%[0-9]+]]:gr64 = MOV32ri64 1, debug-instr-number 1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.if.end.i:
  ; CHECK-NEXT:   DBG_INSTR_REF !10, !DIExpression(DW_OP_LLVM_arg, 0), dbg-instr-ref(1, 0), debug-location !20
  ; CHECK-NEXT:   DBG_INSTR_REF !34, !DIExpression(DW_OP_LLVM_arg, 0), dbg-instr-ref(1, 0), debug-location !41
  ; CHECK-NEXT:   DBG_INSTR_REF !43, !DIExpression(DW_OP_LLVM_arg, 0), dbg-instr-ref(1, 0), debug-location !51
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr32 = COPY [[MOV32ri64_]].sub_32bit, debug-location !53
  ; CHECK-NEXT:   [[ADD32rr:%[0-9]+]]:gr32 = nuw nsw ADD32rr [[COPY]], [[COPY]], implicit-def dead $eflags, debug-location !53
  ; CHECK-NEXT:   [[SUBREG_TO_REG:%[0-9]+]]:gr64 = SUBREG_TO_REG killed [[ADD32rr]], %subreg.sub_32bit, debug-location !53
  ; CHECK-NEXT:   ADJCALLSTACKDOWN64 0, 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
  ; CHECK-NEXT:   [[MOV32r0_:%[0-9]+]]:gr32 = MOV32r0 implicit-def dead $eflags
  ; CHECK-NEXT:   [[SUBREG_TO_REG1:%[0-9]+]]:gr64 = SUBREG_TO_REG killed [[MOV32r0_]], %subreg.sub_32bit
  ; CHECK-NEXT:   $rdi = COPY [[SUBREG_TO_REG]]
  ; CHECK-NEXT:   CALL64r killed [[SUBREG_TO_REG1]], csr_64, implicit $rsp, implicit $ssp, implicit $rdi, implicit-def $rsp, implicit-def $ssp, implicit-def $rax
  ; CHECK-NEXT:   ADJCALLSTACKUP64 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr64 = COPY $rax
  ; CHECK-NEXT:   RET 0
entry:
  %conv = sext i32 1 to i64
  br label %if.end.i

if.end.i:                                         ; preds = %entry
    #dbg_value(i64 %conv, !10, !DIExpression(), !20)
    #dbg_value(i64 %conv, !34, !DIExpression(), !41)
    #dbg_value(i64 %conv, !43, !DIExpression(), !51)
  %mul.i.i.i.i = shl i64 %conv, 1, !dbg !53
  %call5.i.i.i.i7 = call ptr null(i64 %mul.i.i.i.i)
  ret void
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 23.0.0git (https://github.com/OCHyams/llvm-project 7e489b3ebf9c337c8b6ea74bef9c4f45f2dc4fd9)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "x.cpp", directory: "/home/och/reduce", checksumkind: CSK_MD5, checksum: "a79402ede23ff238de3e4647c4f3a326")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DISubprogram(name: "PatchSizeSyncer", linkageName: "_ZN5Pooma15PatchSizeSyncerC2EiR4GridILi1EE", scope: !5, file: !1, line: 52329, type: !7, scopeLine: 52334, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !9, retainedNodes: !2, keyInstructions: true)
!5 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PatchSizeSyncer", scope: !6, file: !1, line: 52286, size: 512, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, identifier: "_ZTSN5Pooma15PatchSizeSyncerE")
!6 = !DINamespace(name: "Pooma", scope: null)
!7 = distinct !DISubroutineType(types: !8)
!8 = !{null}
!9 = !DISubprogram(name: "PatchSizeSyncer", linkageName: "_ZN5Pooma15PatchSizeSyncerC4EiR4GridILi1EE", scope: !5, file: !1, line: 52290, type: !7, scopeLine: 52290, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!10 = !DILocalVariable(name: "__n", arg: 2, scope: !11, file: !12, line: 343, type: !17)
!11 = distinct !DISubprogram(name: "_M_allocate", linkageName: "_ZNSt12_Vector_baseISt4pairIiP4GridILi1EEESaIS4_EE11_M_allocateEm", scope: !13, file: !12, line: 343, type: !15, scopeLine: 344, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !16, retainedNodes: !2, keyInstructions: true)
!12 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h", directory: "", checksumkind: CSK_MD5, checksum: "abcaf00227294b9790605822a1c03477")
!13 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_base<std::pair<int, Grid<1> *>, std::allocator<std::pair<int, Grid<1> *> > >", scope: !14, file: !12, line: 84, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTSSt12_Vector_baseISt4pairIiP4GridILi1EEESaIS4_EE")
!14 = !DINamespace(name: "std", scope: null)
!15 = distinct !DISubroutineType(types: !2)
!16 = !DISubprogram(name: "_M_allocate", linkageName: "_ZNSt12_Vector_baseISt4pairIiP4GridILi1EEESaIS4_EE11_M_allocateEm", scope: !13, file: !12, line: 343, type: !15, scopeLine: 343, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!17 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", scope: !14, file: !18, line: 280, baseType: !19)
!18 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/x86_64-linux-gnu/c++/11/bits/c++config.h", directory: "", checksumkind: CSK_MD5, checksum: "b09addf8bea7ac9bf251a76b15f26064")
!19 = !DIBasicType(name: "unsigned long", size: 64, encoding: DW_ATE_unsigned)
!20 = !DILocation(line: 0, scope: !11, inlinedAt: !21)
!21 = distinct !DILocation(line: 78, column: 22, scope: !22, inlinedAt: !31)
!22 = distinct !DILexicalBlock(scope: !24, file: !23, line: 77, column: 6)
!23 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/vector.tcc", directory: "", checksumkind: CSK_MD5, checksum: "e9a66096952709a84b1e05178c12ec5a")
!24 = distinct !DILexicalBlock(scope: !25, file: !23, line: 76, column: 29)
!25 = distinct !DILexicalBlock(scope: !26, file: !23, line: 72, column: 2)
!26 = distinct !DILexicalBlock(scope: !27, file: !23, line: 71, column: 11)
!27 = distinct !DISubprogram(name: "reserve", linkageName: "_ZNSt6vectorISt4pairIiP4GridILi1EEESaIS4_EE7reserveEm", scope: !28, file: !23, line: 67, type: !29, scopeLine: 68, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !30, retainedNodes: !2, keyInstructions: true)
!28 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<std::pair<int, Grid<1> *>, std::allocator<std::pair<int, Grid<1> *> > >", scope: !14, file: !12, line: 389, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTSSt6vectorISt4pairIiP4GridILi1EEESaIS4_EE")
!29 = distinct !DISubroutineType(types: !8)
!30 = !DISubprogram(name: "reserve", linkageName: "_ZNSt6vectorISt4pairIiP4GridILi1EEESaIS4_EE7reserveEm", scope: !28, file: !23, line: 67, type: !29, scopeLine: 67, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!31 = distinct !DILocation(line: 52335, column: 36, scope: !32)
!32 = distinct !DILexicalBlock(scope: !33, file: !1, line: 52335, column: 7)
!33 = distinct !DILexicalBlock(scope: !4, file: !1, line: 52334, column: 1)
!34 = !DILocalVariable(name: "__n", arg: 2, scope: !35, file: !36, line: 463, type: !40)
!35 = distinct !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaISt4pairIiP4GridILi1EEEEE8allocateERS5_m", scope: !37, file: !36, line: 463, type: !38, scopeLine: 464, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !39, retainedNodes: !2, keyInstructions: true)
!36 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/alloc_traits.h", directory: "", checksumkind: CSK_MD5, checksum: "937e9d7f00d3ed7cff7ec8fafeb8a8bc")
!37 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "allocator_traits<std::allocator<std::pair<int, Grid<1> *> > >", scope: !14, file: !36, line: 411, size: 8, flags: DIFlagTypePassByValue, elements: !2, templateParams: !2, identifier: "_ZTSSt16allocator_traitsISaISt4pairIiP4GridILi1EEEEE")
!38 = distinct !DISubroutineType(types: !2)
!39 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaISt4pairIiP4GridILi1EEEEE8allocateERS5_m", scope: !37, file: !36, line: 463, type: !38, scopeLine: 463, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!40 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !36, line: 435, baseType: !17)
!41 = !DILocation(line: 0, scope: !35, inlinedAt: !42)
!42 = distinct !DILocation(line: 346, column: 20, scope: !11, inlinedAt: !21)
!43 = !DILocalVariable(name: "__n", arg: 2, scope: !44, file: !45, line: 103, type: !50)
!44 = distinct !DISubprogram(name: "allocate", linkageName: "_ZN9__gnu_cxx13new_allocatorISt4pairIiP4GridILi1EEEE8allocateEmPKv", scope: !46, file: !45, line: 103, type: !48, scopeLine: 104, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !49, retainedNodes: !2, keyInstructions: true)
!45 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/ext/new_allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "4493add5a3fa57e0ec30b90cd4e81c11")
!46 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "new_allocator<std::pair<int, Grid<1> *> >", scope: !47, file: !45, line: 55, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTSN9__gnu_cxx13new_allocatorISt4pairIiP4GridILi1EEEEE")
!47 = !DINamespace(name: "__gnu_cxx", scope: null)
!48 = distinct !DISubroutineType(types: !2)
!49 = !DISubprogram(name: "allocate", linkageName: "_ZN9__gnu_cxx13new_allocatorISt4pairIiP4GridILi1EEEE8allocateEmPKv", scope: !46, file: !45, line: 103, type: !48, scopeLine: 103, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!50 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !45, line: 59, baseType: !17, flags: DIFlagPublic)
!51 = !DILocation(line: 0, scope: !44, inlinedAt: !52)
!52 = distinct !DILocation(line: 464, column: 20, scope: !35, inlinedAt: !42)
!53 = !DILocation(line: 127, column: 46, scope: !44, inlinedAt: !52)
