; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc --stop-after=finalize-isel %s -o - -mir-dbg-records -print-as-dbg-instrs \
; RUN: | FileCheck %s
; RUN: llc --stop-after=finalize-isel %s -o - | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%class.FieldEngineBaseData.433 = type { %class.Engine.434, %class.RelationList }
%class.Engine.434 = type { %class.Engine.429, %class.ViewIndexer }
%class.Engine.429 = type { %"class.GenericURM<MeshTraits<3>>::PositionsFunctor", %class.Interval.108 }
%"class.GenericURM<MeshTraits<3>>::PositionsFunctor" = type { %class.Vector.99, %class.Vector.99 }
%class.Vector.99 = type { %class.VectorEngine.100 }
%class.VectorEngine.100 = type { [3 x double] }
%class.Interval.108 = type { %class.Domain.109 }
%class.Domain.109 = type { %class.DomainBase.110 }
%class.DomainBase.110 = type { [3 x %struct.WrapNoInit.111] }
%struct.WrapNoInit.111 = type { %class.Interval }
%class.Interval = type { %class.Domain.106 }
%class.Domain.106 = type { %class.DomainBase.107 }
%class.DomainBase.107 = type { [2 x i32] }
%class.ViewIndexer = type { %class.Interval.108, %class.Range.295, [3 x i32], [3 x i32], %class.Loc.96 }
%class.Range.295 = type { %class.Domain.296 }
%class.Domain.296 = type { %class.DomainBase.297 }
%class.DomainBase.297 = type { [3 x %struct.WrapNoInit.298] }
%struct.WrapNoInit.298 = type { %class.Range }
%class.Range = type { %class.Domain.219 }
%class.Domain.219 = type { %class.DomainBase.220 }
%class.DomainBase.220 = type { [3 x i32] }
%class.Loc.96 = type { %class.Domain.97 }
%class.Domain.97 = type { %class.DomainBase.98 }
%class.DomainBase.98 = type { [3 x %struct.WrapNoInit] }
%struct.WrapNoInit = type { %class.Loc }
%class.Loc = type { %class.Domain.89 }
%class.Domain.89 = type { %class.DomainBase.90 }
%class.DomainBase.90 = type { i32 }
%class.RelationList = type { %class.RefCountedPtr.269 }
%class.RefCountedPtr.269 = type { ptr }

define void @_ZN11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEC2IS4_SE_EERKS_IS1_T_T0_ERK8IntervalILi3EE(i64 %.pre, ptr %0) !dbg !4 {
  ; CHECK-LABEL: name: _ZN11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEC2IS4_SE_EERKS_IS1_T_T0_ERK8IntervalILi3EE
  ; CHECK: bb.0.invoke.cont5:
  ; CHECK-NEXT:   successors: %bb.2(0x30000000), %bb.1(0x50000000)
  ; CHECK-NEXT:   liveins: $rdi, $rsi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr64 = COPY $rsi
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr64 = COPY $rdi
  ; CHECK-NEXT:   [[IMUL64rri32_:%[0-9]+]]:gr64_nosp = IMUL64rri32 [[COPY1]], 176, implicit-def dead $eflags
  ; CHECK-NEXT:   [[ADD64rr:%[0-9]+]]:gr64 = ADD64rr [[COPY]], [[IMUL64rri32_]], implicit-def dead $eflags, debug-instr-number 1
  ; CHECK-NEXT:   DBG_INSTR_REF !9, !DIExpression(DW_OP_LLVM_arg, 0), dbg-instr-ref(1, 0), debug-location !15
  ; CHECK-NEXT:   DBG_VALUE %stack.0.ref.tmp47, $noreg, !35, !DIExpression(), debug-location !15
  ; CHECK-NEXT:   DBG_INSTR_REF !39, !DIExpression(DW_OP_LLVM_arg, 0, DW_OP_plus_uconst, 48, DW_OP_stack_value), dbg-instr-ref(1, 0), debug-location !45
  ; CHECK-NEXT:   MOV32mi [[COPY]], 1, [[IMUL64rri32_]], 48, $noreg, 0, debug-location !47 :: (store (s32) into %ir.domain_m.i.i)
  ; CHECK-NEXT:   TEST64rr [[ADD64rr]], [[ADD64rr]], implicit-def $eflags
  ; CHECK-NEXT:   JCC_1 %bb.2, 4, implicit $eflags
  ; CHECK-NEXT:   JMP_1 %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1._ZN12VectorEngineILi3Ed4FullEaSERKS1_.exit.i7.i.i.i:
  ; CHECK-NEXT:   RET 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.call.i.noexc:
  ; CHECK-NEXT:   RET 0
invoke.cont5:
  %ref.tmp47 = alloca %class.FieldEngineBaseData.433, align 8
  %add.ptr.i.i.i2052 = getelementptr [176 x i8], ptr %0, i64 %.pre
    #dbg_value(ptr %add.ptr.i.i.i2052, !9, !DIExpression(), !15)
    #dbg_value(ptr %ref.tmp47, !35, !DIExpression(), !15)
  %domain_m.i.i = getelementptr i8, ptr %add.ptr.i.i.i2052, i64 48
    #dbg_value(ptr %domain_m.i.i, !39, !DIExpression(), !45)
  store i32 0, ptr %domain_m.i.i, align 4, !dbg !47
  %cmp.not.i.i.i.i = icmp eq ptr %add.ptr.i.i.i2052, null
  br i1 %cmp.not.i.i.i.i, label %call.i.noexc, label %_ZN12VectorEngineILi3Ed4FullEaSERKS1_.exit.i7.i.i.i

_ZN12VectorEngineILi3Ed4FullEaSERKS1_.exit.i7.i.i.i: ; preds = %invoke.cont5
  ret void

call.i.noexc:                                     ; preds = %invoke.cont5
  ret void
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 23.0.0git (https://github.com/OCHyams/llvm-project 7e489b3ebf9c337c8b6ea74bef9c4f45f2dc4fd9)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "x.cpp", directory: "/home/och/reduce", checksumkind: CSK_MD5, checksum: "a79402ede23ff238de3e4647c4f3a326")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DISubprogram(name: "FieldEngine<Vector<3, double, Full>, IndexFunction<GenericURM<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >::PositionsFunctor> >", linkageName: "_ZN11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEC2IS4_SE_EERKS_IS1_T_T0_ERK8IntervalILi3EE", scope: !5, file: !1, line: 44979, type: !6, scopeLine: 44986, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !2, declaration: !8, retainedNodes: !2, keyInstructions: true)
!5 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FieldEngine<NoMesh<3>, Vector<3, double, Full>, ViewEngine<3, IndexFunction<GenericURM<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >::PositionsFunctor> > >", file: !1, line: 44890, size: 1152, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEE")
!6 = distinct !DISubroutineType(types: !7)
!7 = !{null}
!8 = !DISubprogram(name: "FieldEngine<Vector<3, double, Full>, IndexFunction<GenericURM<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >::PositionsFunctor> >", linkageName: "_ZN11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEC4IS4_SE_EERKS_IS1_T_T0_ERK8IntervalILi3EE", scope: !5, file: !1, line: 44979, type: !6, scopeLine: 44979, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized, templateParams: !2)
!9 = !DILocalVariable(name: "this", arg: 1, scope: !10, type: !14, flags: DIFlagArtificial | DIFlagObjectPointer)
!10 = distinct !DISubprogram(name: "operator=", linkageName: "_ZN6EngineILi3E6VectorILi3Ed4FullE13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEaSERKSC_", scope: !11, file: !1, line: 32727, type: !12, scopeLine: 32728, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !13, retainedNodes: !2, keyInstructions: true)
!11 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Engine<3, Vector<3, double, Full>, IndexFunction<GenericURM<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >::PositionsFunctor> >", file: !1, line: 32698, size: 576, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS6EngineILi3E6VectorILi3Ed4FullE13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEE")
!12 = distinct !DISubroutineType(types: !2)
!13 = !DISubprogram(name: "operator=", linkageName: "_ZN6EngineILi3E6VectorILi3Ed4FullE13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEaSERKSC_", scope: !11, file: !1, line: 32727, type: !12, scopeLine: 32727, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!14 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !11, size: 64)
!15 = !DILocation(line: 0, scope: !10, inlinedAt: !16)
!16 = distinct !DILocation(line: 32334, column: 11, scope: !17, inlinedAt: !21)
!17 = distinct !DISubprogram(name: "operator=", linkageName: "_ZN6EngineILi3E6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEaSERKSE_", scope: !18, file: !1, line: 32332, type: !19, scopeLine: 32333, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !20, retainedNodes: !2, keyInstructions: true)
!18 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Engine<3, Vector<3, double, Full>, ViewEngine<3, IndexFunction<GenericURM<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >::PositionsFunctor> > >", file: !1, line: 32259, size: 1344, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS6EngineILi3E6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEE")
!19 = distinct !DISubroutineType(types: !2)
!20 = !DISubprogram(name: "operator=", linkageName: "_ZN6EngineILi3E6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEaSERKSE_", scope: !18, file: !1, line: 32332, type: !19, scopeLine: 32332, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!21 = distinct !DILocation(line: 44856, column: 7, scope: !22, inlinedAt: !27)
!22 = distinct !DILexicalBlock(scope: !23, file: !1, line: 44856, column: 7)
!23 = distinct !DISubprogram(name: "operator=", linkageName: "_ZN19FieldEngineBaseDataILi3E6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEaSEOSE_", scope: !24, file: !1, line: 44856, type: !25, scopeLine: 44856, flags: DIFlagArtificial | DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !26, retainedNodes: !2, keyInstructions: true)
!24 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FieldEngineBaseData<3, Vector<3, double, Full>, ViewEngine<3, IndexFunction<GenericURM<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >::PositionsFunctor> > >", file: !1, line: 44856, size: 1408, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS19FieldEngineBaseDataILi3E6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEE")
!25 = distinct !DISubroutineType(types: !2)
!26 = !DISubprogram(name: "operator=", linkageName: "_ZN19FieldEngineBaseDataILi3E6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEaSEOSE_", scope: !24, type: !25, flags: DIFlagPublic | DIFlagArtificial | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!27 = distinct !DILocation(line: 44999, column: 20, scope: !28)
!28 = distinct !DILexicalBlock(scope: !29, file: !1, line: 44998, column: 7)
!29 = distinct !DILexicalBlock(scope: !30, file: !1, line: 44997, column: 7)
!30 = distinct !DILexicalBlock(scope: !31, file: !1, line: 44997, column: 7)
!31 = distinct !DILexicalBlock(scope: !32, file: !1, line: 44995, column: 5)
!32 = distinct !DILexicalBlock(scope: !33, file: !1, line: 44994, column: 5)
!33 = distinct !DILexicalBlock(scope: !34, file: !1, line: 44994, column: 5)
!34 = distinct !DILexicalBlock(scope: !4, file: !1, line: 44986, column: 3)
!35 = !DILocalVariable(name: "rhs", arg: 2, scope: !10, file: !1, line: 32727, type: !36)
!36 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !37, size: 64)
!37 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !38)
!38 = !DIDerivedType(tag: DW_TAG_typedef, name: "This_t", scope: !11, file: !1, line: 32702, baseType: !11, flags: DIFlagPublic)
!39 = !DILocalVariable(name: "this", arg: 1, scope: !40, type: !44, flags: DIFlagArtificial | DIFlagObjectPointer)
!40 = distinct !DISubprogram(name: "operator=", linkageName: "_ZN8IntervalILi3EEaSERKS0_", scope: !41, file: !1, line: 4399, type: !42, scopeLine: 4399, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !43, retainedNodes: !2, keyInstructions: true)
!41 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Interval<3>", file: !1, line: 4323, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS8IntervalILi3EE")
!42 = distinct !DISubroutineType(types: !2)
!43 = !DISubprogram(name: "operator=", linkageName: "_ZN8IntervalILi3EEaSERKS0_", scope: !41, file: !1, line: 4399, type: !42, scopeLine: 4399, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!44 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !41, size: 64)
!45 = !DILocation(line: 0, scope: !40, inlinedAt: !46)
!46 = distinct !DILocation(line: 32729, column: 14, scope: !10, inlinedAt: !16)
!47 = !DILocation(line: 3663, column: 12, scope: !48, inlinedAt: !52, atomGroup: 1, atomRank: 1)
!48 = distinct !DISubprogram(name: "setDomain<Interval<1> >", linkageName: "_ZN12DomainTraitsI8IntervalILi1EEE9setDomainIS1_EEvRA2_iRKT_", scope: !49, file: !1, line: 3660, type: !50, scopeLine: 3660, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !2, declaration: !51, retainedNodes: !2, keyInstructions: true)
!49 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "DomainTraits<Interval<1> >", file: !1, line: 3607, size: 8, flags: DIFlagTypePassByValue, elements: !2, templateParams: !2, identifier: "_ZTS12DomainTraitsI8IntervalILi1EEE")
!50 = distinct !DISubroutineType(types: !7)
!51 = !DISubprogram(name: "setDomain<Interval<1> >", linkageName: "_ZN12DomainTraitsI8IntervalILi1EEE9setDomainIS1_EEvRA2_iRKT_", scope: !49, file: !1, line: 3660, type: !50, scopeLine: 3660, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized, templateParams: !2)
!52 = distinct !DILocation(line: 3417, column: 5, scope: !53, inlinedAt: !57)
!53 = distinct !DISubprogram(name: "setDomain", linkageName: "_ZN16SetDomainFunctorI12DomainTraitsI8IntervalILi1EEEA2_iS2_S2_Lb0EE9setDomainERS4_RKS2_", scope: !54, file: !1, line: 3416, type: !55, scopeLine: 3416, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !56, retainedNodes: !2, keyInstructions: true)
!54 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SetDomainFunctor<DomainTraits<Interval<1> >, int[2], Interval<1>, Interval<1>, false>", file: !1, line: 3413, size: 8, flags: DIFlagTypePassByValue, elements: !2, templateParams: !2, identifier: "_ZTS16SetDomainFunctorI12DomainTraitsI8IntervalILi1EEEA2_iS2_S2_Lb0EE")
!55 = distinct !DISubroutineType(types: !7)
!56 = !DISubprogram(name: "setDomain", linkageName: "_ZN16SetDomainFunctorI12DomainTraitsI8IntervalILi1EEEA2_iS2_S2_Lb0EE9setDomainERS4_RKS2_", scope: !54, file: !1, line: 3416, type: !55, scopeLine: 3416, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!57 = distinct !DILocation(line: 3482, column: 5, scope: !58, inlinedAt: !62)
!58 = distinct !DISubprogram(name: "setDomain<Interval<1> >", linkageName: "_ZN6DomainILi1E12DomainTraitsI8IntervalILi1EEEE9setDomainIS2_EEvRKT_", scope: !59, file: !1, line: 3481, type: !60, scopeLine: 3481, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !2, declaration: !61, retainedNodes: !2, keyInstructions: true)
!59 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Domain<1, DomainTraits<Interval<1> > >", file: !1, line: 3435, size: 64, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS6DomainILi1E12DomainTraitsI8IntervalILi1EEEE")
!60 = distinct !DISubroutineType(types: !7)
!61 = !DISubprogram(name: "setDomain<Interval<1> >", linkageName: "_ZN6DomainILi1E12DomainTraitsI8IntervalILi1EEEE9setDomainIS2_EEvRKT_", scope: !59, file: !1, line: 3481, type: !60, scopeLine: 3481, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized, templateParams: !2)
!62 = distinct !DILocation(line: 3746, column: 47, scope: !63, inlinedAt: !69)
!63 = distinct !DILexicalBlock(scope: !64, file: !1, line: 3745, column: 5)
!64 = distinct !DILexicalBlock(scope: !65, file: !1, line: 3745, column: 5)
!65 = distinct !DISubprogram(name: "combine", linkageName: "_ZN13CombineDomainI8IntervalILi3EES1_Li0EE7combineERS1_RKS1_", scope: !66, file: !1, line: 3742, type: !67, scopeLine: 3742, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !68, retainedNodes: !2, keyInstructions: true)
!66 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "CombineDomain<Interval<3>, Interval<3>, 0>", file: !1, line: 3739, size: 8, flags: DIFlagTypePassByValue, elements: !2, templateParams: !2, identifier: "_ZTS13CombineDomainI8IntervalILi3EES1_Li0EE")
!67 = distinct !DISubroutineType(types: !7)
!68 = !DISubprogram(name: "combine", linkageName: "_ZN13CombineDomainI8IntervalILi3EES1_Li0EE7combineERS1_RKS1_", scope: !66, file: !1, line: 3742, type: !67, scopeLine: 3742, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!69 = distinct !DILocation(line: 3979, column: 7, scope: !70, inlinedAt: !74)
!70 = distinct !DISubprogram(name: "fill<Interval<3> >", linkageName: "_ZN10NewDomain1I8IntervalILi3EEE4fillIS1_EERT_S5_RKS1_", scope: !71, file: !1, line: 3977, type: !72, scopeLine: 3978, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !2, declaration: !73, retainedNodes: !2, keyInstructions: true)
!71 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "NewDomain1<Interval<3> >", file: !1, line: 3966, size: 8, flags: DIFlagTypePassByValue, elements: !2, templateParams: !2, identifier: "_ZTS10NewDomain1I8IntervalILi3EEE")
!72 = distinct !DISubroutineType(types: !2)
!73 = !DISubprogram(name: "fill<Interval<3> >", linkageName: "_ZN10NewDomain1I8IntervalILi3EEE4fillIS1_EERT_S5_RKS1_", scope: !71, file: !1, line: 3977, type: !72, scopeLine: 3977, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized, templateParams: !2)
!74 = distinct !DILocation(line: 4400, column: 12, scope: !40, inlinedAt: !46)
