; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc --stop-after=machine-sink %s -o - -mir-dbg-records -print-as-dbg-instrs \
; RUN: | FileCheck %s
; RUN: llc --stop-after=machine-sink %s -o - | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.memcpy.p0.p0.i64(ptr noalias writeonly captures(none), ptr noalias readonly captures(none), i64, i1 immarg) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: write)
declare void @llvm.memset.p0.i64(ptr writeonly captures(none), i8, i64, i1 immarg) #1

define void @_ZN4Adv51X6advectILi3E5FieldI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd10MultiPatchI7GridTag6RemoteI5BrickEEESF_SF_SF_SF_S2_IS8_6VectorILi3Ed4FullESE_ESF_S2_IS8_d16ConstantFunctionESF_EEvdRKT0_RKT1_RKT2_RKT3_RKT4_RKT5_RKT6_RKT7_RKT8_dbb(ptr %v) personality ptr null !dbg !4 {
  ; CHECK-LABEL: name: _ZN4Adv51X6advectILi3E5FieldI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd10MultiPatchI7GridTag6RemoteI5BrickEEESF_SF_SF_SF_S2_IS8_6VectorILi3Ed4FullESE_ESF_S2_IS8_d16ConstantFunctionESF_EEvdRKT0_RKT1_RKT2_RKT3_RKT4_RKT5_RKT6_RKT7_RKT8_dbb
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x7ffff800), %bb.1(0x00000800)
  ; CHECK-NEXT:   liveins: $rdi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr64 = COPY $rdi
  ; CHECK-NEXT:   EH_LABEL <mcsymbol >
  ; CHECK-NEXT:   ADJCALLSTACKDOWN64 0, 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
  ; CHECK-NEXT:   [[MOV32r0_:%[0-9]+]]:gr32 = MOV32r0 implicit-def dead $eflags, debug-location !9
  ; CHECK-NEXT:   [[SUBREG_TO_REG:%[0-9]+]]:gr64 = SUBREG_TO_REG killed [[MOV32r0_]], %subreg.sub_32bit, debug-location !9
  ; CHECK-NEXT:   $rdi = COPY [[SUBREG_TO_REG]]
  ; CHECK-NEXT:   CALL64r [[SUBREG_TO_REG]], csr_64, implicit $rsp, implicit $ssp, implicit $rdi, implicit-def $rsp, implicit-def $ssp, implicit-def $rax
  ; CHECK-NEXT:   ADJCALLSTACKUP64 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
  ; CHECK-NEXT:   EH_LABEL <mcsymbol >
  ; CHECK-NEXT:   JMP_1 %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.lpad9.i2772 (landing-pad):
  ; CHECK-NEXT:   liveins: $rax, $rdx
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   EH_LABEL <mcsymbol >
  ; CHECK-NEXT:   RET 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2..noexc727:
  ; CHECK-NEXT:   DBG_VALUE 0, $noreg, !58, !DIExpression(), debug-location !63
  ; CHECK-NEXT:   [[ADD64ri32_:%[0-9]+]]:gr64 = ADD64ri32 [[COPY]], 112, implicit-def dead $eflags
  ; CHECK-NEXT:   MOV64mi32 $noreg, 1, $noreg, 0, $noreg, 0, debug-location !64 :: (store (s64) into `ptr null`)
  ; CHECK-NEXT:   [[MOV8rm:%[0-9]+]]:gr8 = MOV8rm [[ADD64ri32_]], 1, $noreg, 0, $noreg :: (load (s8) from %ir.guards_m9.i.i.i.i568)
  ; CHECK-NEXT:   MOV8mr $noreg, 1, $noreg, 0, $noreg, killed [[MOV8rm]] :: (store (s8) into `ptr null`)
  ; CHECK-NEXT:   RET 0
entry:
  %guards_m9.i.i.i.i568 = getelementptr i8, ptr %v, i64 112
  call void @llvm.memset.p0.i64(ptr null, i8 0, i64 0, i1 false), !dbg !9
  %call5.i.i.i.i4.i.i30.i2771 = invoke ptr null(i64 0)
          to label %.noexc727 unwind label %lpad9.i2772

lpad9.i2772:                                      ; preds = %entry
  %0 = landingpad { ptr, i32 }
          cleanup
  ret void

.noexc727:                                        ; preds = %entry
    #dbg_value(ptr null, !58, !DIExpression(), !63)
  store ptr null, ptr null, align 8, !dbg !64
  call void @llvm.memcpy.p0.p0.i64(ptr null, ptr %guards_m9.i.i.i.i568, i64 1, i1 false)
  ret void
}

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(argmem: write) }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 23.0.0git (https://github.com/OCHyams/llvm-project 7e489b3ebf9c337c8b6ea74bef9c4f45f2dc4fd9)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "x.cpp", directory: "/home/och/reduce", checksumkind: CSK_MD5, checksum: "a79402ede23ff238de3e4647c4f3a326")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DISubprogram(name: "advect<3, Field<UniformRectilinearMesh<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >, double, MultiPatch<GridTag, Remote<Brick> > >, Field<UniformRectilinearMesh<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >, double, MultiPatch<GridTag, Remote<Brick> > >, Field<UniformRectilinearMesh<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >, double, MultiPatch<GridTag, Remote<Brick> > >, Field<UniformRectilinearMesh<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >, double, MultiPatch<GridTag, Remote<Brick> > >, Field<UniformRectilinearMesh<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >, double, MultiPatch<GridTag, Remote<Brick> > >, Field<UniformRectilinearMesh<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >, Vector<3, double, Full>, MultiPatch<GridTag, Remote<Brick> > >, Field<UniformRectilinearMesh<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >, double, MultiPatch<GridTag, Remote<Brick> > >, Field<UniformRectilinearMesh<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >, double, ConstantFunction>, Field<UniformRectilinearMesh<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >, double, MultiPatch<GridTag, Remote<Brick> > > >", linkageName: "_ZN4Adv51X6advectILi3E5FieldI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd10MultiPatchI7GridTag6RemoteI5BrickEEESF_SF_SF_SF_S2_IS8_6VectorILi3Ed4FullESE_ESF_S2_IS8_d16ConstantFunctionESF_EEvdRKT0_RKT1_RKT2_RKT3_RKT4_RKT5_RKT6_RKT7_RKT8_dbb", scope: !5, file: !1, line: 54027, type: !7, scopeLine: 54032, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !2, retainedNodes: !2, keyInstructions: true)
!5 = !DINamespace(name: "X", scope: !6)
!6 = !DINamespace(name: "Adv5", scope: null)
!7 = distinct !DISubroutineType(types: !8)
!8 = !{null}
!9 = !DILocation(line: 98, column: 16, scope: !10, inlinedAt: !17, atomGroup: 2, atomRank: 1)
!10 = distinct !DISubprogram(name: "_Vector_impl_data", linkageName: "_ZNSt12_Vector_baseI6VectorILi3Ed4FullESaIS2_EE17_Vector_impl_dataC2Ev", scope: !12, file: !11, line: 97, type: !15, scopeLine: 99, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !16, retainedNodes: !2, keyInstructions: true)
!11 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h", directory: "", checksumkind: CSK_MD5, checksum: "abcaf00227294b9790605822a1c03477")
!12 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_impl_data", scope: !13, file: !11, line: 91, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, identifier: "_ZTSNSt12_Vector_baseI6VectorILi3Ed4FullESaIS2_EE17_Vector_impl_dataE")
!13 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_base<Vector<3, double, Full>, std::allocator<Vector<3, double, Full> > >", scope: !14, file: !11, line: 84, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTSSt12_Vector_baseI6VectorILi3Ed4FullESaIS2_EE")
!14 = !DINamespace(name: "std", scope: null)
!15 = distinct !DISubroutineType(types: !8)
!16 = !DISubprogram(name: "_Vector_impl_data", linkageName: "_ZNSt12_Vector_baseI6VectorILi3Ed4FullESaIS2_EE17_Vector_impl_dataC4Ev", scope: !12, file: !11, line: 97, type: !15, scopeLine: 97, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!17 = distinct !DILocation(line: 136, column: 2, scope: !18, inlinedAt: !22)
!18 = distinct !DISubprogram(name: "_Vector_impl", linkageName: "_ZNSt12_Vector_baseI6VectorILi3Ed4FullESaIS2_EE12_Vector_implC2ERKS3_", scope: !19, file: !11, line: 136, type: !20, scopeLine: 138, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !21, retainedNodes: !2, keyInstructions: true)
!19 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_impl", scope: !13, file: !11, line: 128, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, identifier: "_ZTSNSt12_Vector_baseI6VectorILi3Ed4FullESaIS2_EE12_Vector_implE")
!20 = distinct !DISubroutineType(types: !8)
!21 = !DISubprogram(name: "_Vector_impl", linkageName: "_ZNSt12_Vector_baseI6VectorILi3Ed4FullESaIS2_EE12_Vector_implC4ERKS3_", scope: !19, file: !11, line: 136, type: !20, scopeLine: 136, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!22 = distinct !DILocation(line: 304, column: 9, scope: !23, inlinedAt: !26)
!23 = distinct !DISubprogram(name: "_Vector_base", linkageName: "_ZNSt12_Vector_baseI6VectorILi3Ed4FullESaIS2_EEC2EmRKS3_", scope: !13, file: !11, line: 303, type: !24, scopeLine: 305, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !25, retainedNodes: !2, keyInstructions: true)
!24 = distinct !DISubroutineType(types: !8)
!25 = !DISubprogram(name: "_Vector_base", linkageName: "_ZNSt12_Vector_baseI6VectorILi3Ed4FullESaIS2_EEC4EmRKS3_", scope: !13, file: !11, line: 303, type: !24, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!26 = distinct !DILocation(line: 524, column: 9, scope: !27, inlinedAt: !31)
!27 = distinct !DISubprogram(name: "vector", linkageName: "_ZNSt6vectorI6VectorILi3Ed4FullESaIS2_EEC2EmRKS2_RKS3_", scope: !28, file: !11, line: 522, type: !29, scopeLine: 525, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !30, retainedNodes: !2, keyInstructions: true)
!28 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<Vector<3, double, Full>, std::allocator<Vector<3, double, Full> > >", scope: !14, file: !11, line: 389, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTSSt6vectorI6VectorILi3Ed4FullESaIS2_EE")
!29 = distinct !DISubroutineType(types: !8)
!30 = !DISubprogram(name: "vector", linkageName: "_ZNSt6vectorI6VectorILi3Ed4FullESaIS2_EEC4EmRKS2_RKS3_", scope: !28, file: !11, line: 522, type: !29, scopeLine: 522, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!31 = distinct !DILocation(line: 43706, column: 7, scope: !32, inlinedAt: !36)
!32 = distinct !DISubprogram(name: "Centering", linkageName: "_ZN9CenteringILi3EEC2ERKS0_i", scope: !33, file: !1, line: 43702, type: !34, scopeLine: 43707, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !35, retainedNodes: !2, keyInstructions: true)
!33 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Centering<3>", file: !1, line: 43684, size: 448, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS9CenteringILi3EE")
!34 = distinct !DISubroutineType(types: !8)
!35 = !DISubprogram(name: "Centering", linkageName: "_ZN9CenteringILi3EEC4ERKS0_i", scope: !33, file: !1, line: 43702, type: !34, scopeLine: 43702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!36 = distinct !DILocation(line: 44960, column: 7, scope: !37, inlinedAt: !41)
!37 = distinct !DISubprogram(name: "FieldEngine", linkageName: "_ZN11FieldEngineI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd10MultiPatchI7GridTag6RemoteI5BrickEEEC2ERKSC_iRKN5Pooma16CenteringViewTagE", scope: !38, file: !1, line: 44958, type: !39, scopeLine: 44966, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !40, retainedNodes: !2, keyInstructions: true)
!38 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FieldEngine<UniformRectilinearMesh<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >, double, MultiPatch<GridTag, Remote<Brick> > >", file: !1, line: 44890, size: 1152, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS11FieldEngineI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd10MultiPatchI7GridTag6RemoteI5BrickEEE")
!39 = distinct !DISubroutineType(types: !8)
!40 = !DISubprogram(name: "FieldEngine", linkageName: "_ZN11FieldEngineI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd10MultiPatchI7GridTag6RemoteI5BrickEEEC4ERKSC_iRKN5Pooma16CenteringViewTagE", scope: !38, file: !1, line: 44958, type: !39, scopeLine: 44958, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!41 = distinct !DILocation(line: 45997, column: 7, scope: !42, inlinedAt: !46)
!42 = distinct !DISubprogram(name: "Field<MultiPatch<GridTag, Remote<Brick> > >", linkageName: "_ZN5FieldI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd10MultiPatchI7GridTag6RemoteI5BrickEEEC2ISB_EERKS_IS5_dT_EiRKN5Pooma16CenteringViewTagE", scope: !43, file: !1, line: 45996, type: !44, scopeLine: 45998, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !2, declaration: !45, retainedNodes: !2, keyInstructions: true)
!43 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Field<UniformRectilinearMesh<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >, double, MultiPatch<GridTag, Remote<Brick> > >", file: !1, line: 45917, size: 1152, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS5FieldI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd10MultiPatchI7GridTag6RemoteI5BrickEEE")
!44 = distinct !DISubroutineType(types: !8)
!45 = !DISubprogram(name: "Field<MultiPatch<GridTag, Remote<Brick> > >", linkageName: "_ZN5FieldI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd10MultiPatchI7GridTag6RemoteI5BrickEEEC4ISB_EERKS_IS5_dT_EiRKN5Pooma16CenteringViewTagE", scope: !43, file: !1, line: 45996, type: !44, scopeLine: 45996, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized, templateParams: !2)
!46 = distinct !DILocation(line: 45462, column: 12, scope: !47, inlinedAt: !51)
!47 = distinct !DISubprogram(name: "make", linkageName: "_ZN12SubFieldViewI5FieldI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd10MultiPatchI7GridTag6RemoteI5BrickEEEE4makeERKSD_iRKN5Pooma16CenteringViewTagE", scope: !48, file: !1, line: 45459, type: !49, scopeLine: 45460, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !50, retainedNodes: !2, keyInstructions: true)
!48 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SubFieldView<Field<UniformRectilinearMesh<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >, double, MultiPatch<GridTag, Remote<Brick> > > >", file: !1, line: 45446, size: 8, flags: DIFlagTypePassByValue, elements: !2, templateParams: !2, identifier: "_ZTS12SubFieldViewI5FieldI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd10MultiPatchI7GridTag6RemoteI5BrickEEEE")
!49 = distinct !DISubroutineType(types: !2)
!50 = !DISubprogram(name: "make", linkageName: "_ZN12SubFieldViewI5FieldI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd10MultiPatchI7GridTag6RemoteI5BrickEEEE4makeERKSD_iRKN5Pooma16CenteringViewTagE", scope: !48, file: !1, line: 45459, type: !49, scopeLine: 45459, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!51 = distinct !DILocation(line: 46097, column: 12, scope: !52, inlinedAt: !55)
!52 = distinct !DISubprogram(name: "center", linkageName: "_ZNK5FieldI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd10MultiPatchI7GridTag6RemoteI5BrickEEE6centerEi", scope: !43, file: !1, line: 46094, type: !53, scopeLine: 46095, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !54, retainedNodes: !2, keyInstructions: true)
!53 = distinct !DISubroutineType(types: !2)
!54 = !DISubprogram(name: "center", linkageName: "_ZNK5FieldI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd10MultiPatchI7GridTag6RemoteI5BrickEEE6centerEi", scope: !43, file: !1, line: 46094, type: !53, scopeLine: 46094, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!55 = distinct !DILocation(line: 54042, column: 14, scope: !56)
!56 = distinct !DILexicalBlock(scope: !57, file: !1, line: 54035, column: 16)
!57 = distinct !DILexicalBlock(scope: !4, file: !1, line: 54035, column: 11)
!58 = !DILocalVariable(name: "__value", arg: 3, scope: !27, file: !11, line: 522, type: !59)
!59 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !60, size: 64)
!60 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !61)
!61 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !28, file: !11, line: 414, baseType: !62, flags: DIFlagPublic)
!62 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Vector<3, double, Full>", file: !1, line: 29461, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS6VectorILi3Ed4FullE")
!63 = !DILocation(line: 0, scope: !27, inlinedAt: !31)
!64 = !DILocation(line: 361, column: 25, scope: !65, inlinedAt: !68, atomGroup: 1, atomRank: 1)
!65 = distinct !DISubprogram(name: "_M_create_storage", linkageName: "_ZNSt12_Vector_baseI6VectorILi3Ed4FullESaIS2_EE17_M_create_storageEm", scope: !13, file: !11, line: 359, type: !66, scopeLine: 360, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !67, retainedNodes: !2, keyInstructions: true)
!66 = distinct !DISubroutineType(types: !8)
!67 = !DISubprogram(name: "_M_create_storage", linkageName: "_ZNSt12_Vector_baseI6VectorILi3Ed4FullESaIS2_EE17_M_create_storageEm", scope: !13, file: !11, line: 359, type: !66, scopeLine: 359, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!68 = distinct !DILocation(line: 305, column: 9, scope: !69, inlinedAt: !26)
!69 = distinct !DILexicalBlock(scope: !23, file: !11, line: 305, column: 7)
