; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc --stop-after=machine-sink %s -o - -mir-dbg-records -print-as-dbg-instrs \
; RUN: | FileCheck %s
; RUN: llc --stop-after=machine-sink %s -o - | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @_ZN11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEC2IS4_SE_EERKS_IS1_T_T0_ERK8IntervalILi3EE(ptr %this, ptr %model, i1 %cmp.i.i.i, ptr %arrayidx2.i.i.i.2.i.i.i, i32 %.sink16.i, i32 %0) personality ptr null !dbg !4 {
  ; CHECK-LABEL: name: _ZN11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEC2IS4_SE_EERKS_IS1_T_T0_ERK8IntervalILi3EE
  ; CHECK: bb.0.invoke.cont5:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $rdi, $rsi, $edx, $rcx, $r8d, $r9d
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr32 = COPY $r9d
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr32 = COPY $r8d
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gr64 = COPY $rcx
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gr32 = COPY $edx
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gr64 = COPY $rsi
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gr64 = COPY $rdi
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:gr8 = COPY [[COPY3]].sub_8bit
  ; CHECK-NEXT:   TEST8ri [[COPY6]], 1, implicit-def $eflags
  ; CHECK-NEXT:   JCC_1 %bb.2, 4, implicit $eflags
  ; CHECK-NEXT:   JMP_1 %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.if.then.i.i:
  ; CHECK-NEXT:   successors: %bb.3(0x7ffff800), %bb.4(0x00000800)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   DBG_VALUE $noreg, $noreg, !9, !DIExpression(DW_OP_LLVM_fragment, 128, 32), debug-location !16
  ; CHECK-NEXT:   EH_LABEL <mcsymbol >
  ; CHECK-NEXT:   [[MOV64rm:%[0-9]+]]:gr64 = MOV64rm $noreg, 1, $noreg, 0, $noreg :: (load (s64) from `ptr null`)
  ; CHECK-NEXT:   ADJCALLSTACKDOWN64 0, 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
  ; CHECK-NEXT:   [[MOV32r0_:%[0-9]+]]:gr32 = MOV32r0 implicit-def dead $eflags
  ; CHECK-NEXT:   [[SUBREG_TO_REG:%[0-9]+]]:gr64 = SUBREG_TO_REG [[MOV32r0_]], %subreg.sub_32bit
  ; CHECK-NEXT:   $rdi = COPY [[SUBREG_TO_REG]]
  ; CHECK-NEXT:   CALL64r [[SUBREG_TO_REG]], csr_64, implicit $rsp, implicit $ssp, implicit $rdi, implicit-def $rsp, implicit-def $ssp, implicit-def $rax
  ; CHECK-NEXT:   ADJCALLSTACKUP64 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
  ; CHECK-NEXT:   EH_LABEL <mcsymbol >
  ; CHECK-NEXT:   JMP_1 %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.invoke.cont.i.i:
  ; CHECK-NEXT:   RET 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.invoke.cont13:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   MOV64mr $noreg, 1, $noreg, 0, $noreg, [[MOV64rm]] :: (store (s64) into `ptr null`)
  ; CHECK-NEXT:   JMP_1 %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.lpad12 (landing-pad):
  ; CHECK-NEXT:   liveins: $rax, $rdx
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   EH_LABEL <mcsymbol >
  ; CHECK-NEXT:   RET 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.invoke.cont53:
  ; CHECK-NEXT:   successors: %bb.7(0x7c000000), %bb.6(0x04000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gr32 = PHI [[MOV32r0_]], %bb.3, %2, %bb.7
  ; CHECK-NEXT:   MOV32mr $noreg, 1, $noreg, 0, $noreg, [[COPY1]] :: (store (s32) into `ptr null`, align 8)
  ; CHECK-NEXT:   MOV32mi [[COPY5]], 1, $noreg, 0, $noreg, 0 :: (store (s32) into %ir.this, align 8)
  ; CHECK-NEXT:   MOV32mr $noreg, 1, $noreg, 0, $noreg, [[COPY]] :: (store (s32) into `ptr null`)
  ; CHECK-NEXT:   [[SUB64rr:%[0-9]+]]:gr64 = SUB64rr [[COPY2]], [[COPY4]], implicit-def $eflags
  ; CHECK-NEXT:   [[SETCCr:%[0-9]+]]:gr8 = SETCCr 4, implicit $eflags
  ; CHECK-NEXT:   [[OR8rr:%[0-9]+]]:gr8 = OR8rr [[SETCCr]], [[COPY6]], implicit-def dead $eflags
  ; CHECK-NEXT:   TEST8ri killed [[OR8rr]], 1, implicit-def $eflags
  ; CHECK-NEXT:   JCC_1 %bb.7, 5, implicit $eflags
  ; CHECK-NEXT:   JMP_1 %bb.6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6.land.lhs.true.i.i.i:
  ; CHECK-NEXT:   RET 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7.invoke.cont61:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[OR32ri:%[0-9]+]]:gr32 = OR32ri [[PHI]], 1, implicit-def dead $eflags
  ; CHECK-NEXT:   JMP_1 %bb.5
invoke.cont5:
  %1 = load ptr, ptr null, align 8
  br i1 %cmp.i.i.i, label %if.then.i.i, label %invoke.cont.i.i

if.then.i.i:                                      ; preds = %invoke.cont5
    #dbg_value(i32 poison, !9, !DIExpression(DW_OP_LLVM_fragment, 128, 32), !16)
  %call.i118 = invoke ptr null(i64 0)
          to label %invoke.cont13 unwind label %lpad12

invoke.cont.i.i:                                  ; preds = %invoke.cont5
  ret void

invoke.cont13:                                    ; preds = %if.then.i.i
  %sub.ptr.rhs.cast.i.i.i.i = ptrtoint ptr %1 to i64
  store i64 %sub.ptr.rhs.cast.i.i.i.i, ptr null, align 8
  br label %invoke.cont53

lpad12:                                           ; preds = %if.then.i.i
  %2 = landingpad { ptr, i32 }
          cleanup
  ret void

invoke.cont53:                                    ; preds = %invoke.cont61, %invoke.cont13
  %m.0241 = phi i32 [ %inc, %invoke.cont61 ], [ 0, %invoke.cont13 ]
  store i32 %.sink16.i, ptr null, align 8
  store i32 0, ptr %this, align 8
  store i32 %0, ptr null, align 4
  %cmp.not.i.i.i208 = icmp eq ptr %arrayidx2.i.i.i.2.i.i.i, %model
  %brmerge = or i1 %cmp.not.i.i.i208, %cmp.i.i.i
  br i1 %brmerge, label %invoke.cont61, label %land.lhs.true.i.i.i

land.lhs.true.i.i.i:                              ; preds = %invoke.cont53
  ret void

invoke.cont61:                                    ; preds = %invoke.cont53
  %inc = or i32 %m.0241, 1
  %cmp44 = icmp slt i32 %m.0241, 0
  br label %invoke.cont53
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 23.0.0git (https://github.com/OCHyams/llvm-project 7e489b3ebf9c337c8b6ea74bef9c4f45f2dc4fd9)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "x.cpp", directory: "/home/och/reduce", checksumkind: CSK_MD5, checksum: "a79402ede23ff238de3e4647c4f3a326")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DISubprogram(name: "FieldEngine<Vector<3, double, Full>, IndexFunction<GenericURM<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >::PositionsFunctor> >", linkageName: "_ZN11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEC2IS4_SE_EERKS_IS1_T_T0_ERK8IntervalILi3EE", scope: !5, file: !1, line: 44979, type: !6, scopeLine: 44986, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !2, declaration: !8, retainedNodes: !2, keyInstructions: true)
!5 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FieldEngine<NoMesh<3>, Vector<3, double, Full>, ViewEngine<3, IndexFunction<GenericURM<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >::PositionsFunctor> > >", file: !1, line: 44890, size: 1152, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEE")
!6 = distinct !DISubroutineType(types: !7)
!7 = !{null}
!8 = !DISubprogram(name: "FieldEngine<Vector<3, double, Full>, IndexFunction<GenericURM<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >::PositionsFunctor> >", linkageName: "_ZN11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEC4IS4_SE_EERKS_IS1_T_T0_ERK8IntervalILi3EE", scope: !5, file: !1, line: 44979, type: !6, scopeLine: 44979, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized, templateParams: !2)
!9 = !DILocalVariable(name: "ret", scope: !10, file: !1, line: 30040, type: !15)
!10 = distinct !DISubprogram(name: "growRight<3>", linkageName: "_Z9growRightILi3EE8IntervalIXT_EERKS1_i", scope: !1, file: !1, line: 30038, type: !11, scopeLine: 30039, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !12, retainedNodes: !2, keyInstructions: true)
!11 = distinct !DISubroutineType(types: !2)
!12 = !{!13}
!13 = !DITemplateValueParameter(name: "Dim", type: !14, value: i32 3)
!14 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!15 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Interval<3>", file: !1, line: 4323, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !12, identifier: "_ZTS8IntervalILi3EE")
!16 = !DILocation(line: 0, scope: !10, inlinedAt: !17)
!17 = distinct !DILocation(line: 45280, column: 14, scope: !18, inlinedAt: !22)
!18 = distinct !DILexicalBlock(scope: !19, file: !1, line: 45279, column: 9)
!19 = distinct !DISubprogram(name: "inputDomainToVertexDomain", linkageName: "_ZNK11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEE25inputDomainToVertexDomainERK8IntervalILi3EE", scope: !5, file: !1, line: 45277, type: !20, scopeLine: 45278, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !21, retainedNodes: !2, keyInstructions: true)
!20 = distinct !DISubroutineType(types: !2)
!21 = !DISubprogram(name: "inputDomainToVertexDomain", linkageName: "_ZNK11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEE25inputDomainToVertexDomainERK8IntervalILi3EE", scope: !5, file: !1, line: 45277, type: !20, scopeLine: 45277, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!22 = distinct !DILocation(line: 44985, column: 28, scope: !4)
