; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc --stop-after=early-machinelicm %s -o - -mir-dbg-records -print-as-dbg-instrs \
; RUN: | FileCheck %s
; RUN: llc --stop-after=early-machinelicm %s -o - | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @_ZN11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEC2IS4_SE_EERKS_IS1_T_T0_ERK8IntervalILi3EE(ptr %this, i32 %0) !dbg !4 {
  ; CHECK-LABEL: name: _ZN11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEC2IS4_SE_EERKS_IS1_T_T0_ERK8IntervalILi3EE
  ; CHECK: bb.0.invoke.cont5:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $rdi, $esi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr32 = COPY $esi
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr64 = COPY $rdi
  ; CHECK-NEXT:   [[MOV32r0_:%[0-9]+]]:gr32 = MOV32r0 implicit-def dead $eflags
  ; CHECK-NEXT:   [[SUBREG_TO_REG:%[0-9]+]]:gr64 = SUBREG_TO_REG killed [[MOV32r0_]], %subreg.sub_32bit
  ; CHECK-NEXT:   [[MOV32rm:%[0-9]+]]:gr32 = MOV32rm [[COPY1]], 1, $noreg, 0, $noreg, debug-instr-number 1 :: (load (s32) from %ir.this, align 8)
  ; CHECK-NEXT:   [[MOV32rm1:%[0-9]+]]:gr32 = MOV32rm [[COPY1]], 1, $noreg, 92, $noreg :: (load (s32) from %ir.arrayidx2.i.i.i.i.i.i)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.for.body:
  ; CHECK-NEXT:   successors: %bb.2(0x04000000), %bb.3(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gr64 = PHI [[SUBREG_TO_REG]], %bb.0, %3, %bb.3
  ; CHECK-NEXT:   DBG_INSTR_REF !9, !DIExpression(DW_OP_LLVM_arg, 0, DW_OP_LLVM_fragment, 0, 32), dbg-instr-ref(1, 0), debug-location !21
  ; CHECK-NEXT:   TEST32rr [[COPY]], [[COPY]], implicit-def $eflags, debug-location !22
  ; CHECK-NEXT:   JCC_1 %bb.3, 14, implicit $eflags
  ; CHECK-NEXT:   JMP_1 %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.invoke.cont53.preheader:
  ; CHECK-NEXT:   MOV32mr $noreg, 1, $noreg, 0, $noreg, [[MOV32rm]] :: (store (s32) into `ptr null`, align 8)
  ; CHECK-NEXT:   MOV32mi [[COPY1]], 1, $noreg, 0, $noreg, 0 :: (store (s32) into %ir.this, align 8)
  ; CHECK-NEXT:   MOV32mr $noreg, 1, $noreg, 0, $noreg, [[MOV32rm1]] :: (store (s32) into `ptr null`)
  ; CHECK-NEXT:   RET 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.for.cond.cleanup45:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[OR64ri32_:%[0-9]+]]:gr64 = OR64ri32 [[PHI]], 1, implicit-def dead $eflags
  ; CHECK-NEXT:   JMP_1 %bb.1
invoke.cont5:
  br label %for.body

for.body:                                         ; preds = %for.cond.cleanup45, %invoke.cont5
  %indvars.iv = phi i64 [ 0, %invoke.cont5 ], [ %indvars.iv.next, %for.cond.cleanup45 ]
  %arrayidx2.i.i.i.i.i.i = getelementptr i8, ptr %this, i64 92
  %1 = load i32, ptr %arrayidx2.i.i.i.i.i.i, align 4
  %.sink16.i = load i32, ptr %this, align 8
    #dbg_value(i32 %.sink16.i, !9, !DIExpression(DW_OP_LLVM_fragment, 0, 32), !21)
  %cmp44240 = icmp sgt i32 %0, 0, !dbg !22
  br i1 %cmp44240, label %invoke.cont53.preheader, label %for.cond.cleanup45

invoke.cont53.preheader:                          ; preds = %for.body
  %2 = trunc i64 %indvars.iv to i32
  store i32 %.sink16.i, ptr null, align 8
  store i32 0, ptr %this, align 8
  store i32 %1, ptr null, align 4
  ret void

for.cond.cleanup45:                               ; preds = %for.body
  %indvars.iv.next = or i64 %indvars.iv, 1
  br label %for.body
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 23.0.0git (https://github.com/OCHyams/llvm-project 7e489b3ebf9c337c8b6ea74bef9c4f45f2dc4fd9)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "x.cpp", directory: "/home/och/reduce", checksumkind: CSK_MD5, checksum: "a79402ede23ff238de3e4647c4f3a326")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DISubprogram(name: "FieldEngine<Vector<3, double, Full>, IndexFunction<GenericURM<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >::PositionsFunctor> >", linkageName: "_ZN11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEC2IS4_SE_EERKS_IS1_T_T0_ERK8IntervalILi3EE", scope: !5, file: !1, line: 44979, type: !6, scopeLine: 44986, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !2, declaration: !8, retainedNodes: !2, keyInstructions: true)
!5 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FieldEngine<NoMesh<3>, Vector<3, double, Full>, ViewEngine<3, IndexFunction<GenericURM<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >::PositionsFunctor> > >", file: !1, line: 44890, size: 1152, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEE")
!6 = distinct !DISubroutineType(types: !7)
!7 = !{null}
!8 = !DISubprogram(name: "FieldEngine<Vector<3, double, Full>, IndexFunction<GenericURM<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >::PositionsFunctor> >", linkageName: "_ZN11FieldEngineI6NoMeshILi3EE6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEEC4IS4_SE_EERKS_IS1_T_T0_ERK8IntervalILi3EE", scope: !5, file: !1, line: 44979, type: !6, scopeLine: 44979, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized, templateParams: !2)
!9 = !DILocalVariable(name: "dc", scope: !10, file: !1, line: 44996, type: !14)
!10 = distinct !DILexicalBlock(scope: !11, file: !1, line: 44995, column: 5)
!11 = distinct !DILexicalBlock(scope: !12, file: !1, line: 44994, column: 5)
!12 = distinct !DILexicalBlock(scope: !13, file: !1, line: 44994, column: 5)
!13 = distinct !DILexicalBlock(scope: !4, file: !1, line: 44986, column: 3)
!14 = !DIDerivedType(tag: DW_TAG_typedef, name: "Domain_t", scope: !5, file: !1, line: 44898, baseType: !15, flags: DIFlagPublic)
!15 = !DIDerivedType(tag: DW_TAG_typedef, name: "Domain_t", scope: !16, file: !1, line: 32267, baseType: !17, flags: DIFlagPublic)
!16 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Engine<3, Vector<3, double, Full>, ViewEngine<3, IndexFunction<GenericURM<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >::PositionsFunctor> > >", file: !1, line: 32259, size: 1344, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS6EngineILi3E6VectorILi3Ed4FullE10ViewEngineILi3E13IndexFunctionIN10GenericURMI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEE16PositionsFunctorEEEE")
!17 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Interval<3>", file: !1, line: 4323, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !18, identifier: "_ZTS8IntervalILi3EE")
!18 = !{!19}
!19 = !DITemplateValueParameter(name: "Dim", type: !20, value: i32 3)
!20 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!21 = !DILocation(line: 0, scope: !10)
!22 = !DILocation(line: 44997, column: 25, scope: !23, atomGroup: 47154, atomRank: 1)
!23 = distinct !DILexicalBlock(scope: !24, file: !1, line: 44997, column: 7)
!24 = distinct !DILexicalBlock(scope: !10, file: !1, line: 44997, column: 7)
