; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc --stop-after=stack-coloring %s -o - -mir-dbg-records -print-as-dbg-instrs \
; RUN: | FileCheck %s
; RUN: llc --stop-after=stack-coloring %s -o - | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%class.DomainBlockIterator.262 = type { %class.Interval.108, [3 x %class.DomainIterator.263], %class.Loc.96, %class.Interval.108, i32 }
%class.DomainIterator.263 = type { %class.Interval, %class.Loc, [1 x i32], i32 }
%class.Interval = type { %class.Domain.106 }
%class.Domain.106 = type { %class.DomainBase.107 }
%class.DomainBase.107 = type { [2 x i32] }
%class.Loc = type { %class.Domain.89 }
%class.Domain.89 = type { %class.DomainBase.90 }
%class.DomainBase.90 = type { i32 }
%class.Loc.96 = type { %class.Domain.97 }
%class.Domain.97 = type { %class.DomainBase.98 }
%class.DomainBase.98 = type { [3 x %struct.WrapNoInit] }
%struct.WrapNoInit = type { %class.Loc }
%class.Interval.108 = type { %class.Domain.109 }
%class.Domain.109 = type { %class.DomainBase.110 }
%class.DomainBase.110 = type { [3 x %struct.WrapNoInit.111] }
%struct.WrapNoInit.111 = type { %class.Interval }

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(ptr captures(none)) #0

define void @_ZN14GridLayoutDataILi3EE14calcGCFillListEv(i1 %cmp15) !dbg !4 {
  ; CHECK-LABEL: name: _ZN14GridLayoutDataILi3EE14calcGCFillListEv
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr32 = COPY $edi
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr8 = COPY [[COPY]].sub_8bit
  ; CHECK-NEXT:   [[LEA64r:%[0-9]+]]:gr64 = LEA64r %stack.0.start, 1, $noreg, 0, $noreg
  ; CHECK-NEXT:   [[MOV32r0_:%[0-9]+]]:gr32 = MOV32r0 implicit-def dead $eflags
  ; CHECK-NEXT:   [[SUBREG_TO_REG:%[0-9]+]]:gr64 = SUBREG_TO_REG killed [[MOV32r0_]], %subreg.sub_32bit
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.for.body13:
  ; CHECK-NEXT:   successors: %bb.2(0x04000000), %bb.3(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gr64 = PHI [[LEA64r]], %bb.0, %3, %bb.5
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gr64 = PHI [[SUBREG_TO_REG]], %bb.0, %2, %bb.5, debug-instr-number 1
  ; CHECK-NEXT:   TEST8ri [[COPY1]], 1, implicit-def $eflags
  ; CHECK-NEXT:   JCC_1 %bb.3, 4, implicit $eflags
  ; CHECK-NEXT:   JMP_1 %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.if.then16:
  ; CHECK-NEXT:   MOV32mi %stack.0.start, 1, $noreg, 0, $noreg, 0 :: (store (s32) into %ir.start)
  ; CHECK-NEXT:   RET 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.if.end116:
  ; CHECK-NEXT:   successors: %bb.4(0x04000000), %bb.5(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   TEST8ri [[COPY1]], 1, implicit-def $eflags
  ; CHECK-NEXT:   JCC_1 %bb.5, 4, implicit $eflags
  ; CHECK-NEXT:   JMP_1 %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.if.then120:
  ; CHECK-NEXT:   DBG_INSTR_REF !9, !DIExpression(DW_OP_LLVM_arg, 0, DW_OP_LLVM_arg, 1, DW_OP_constu, 4, DW_OP_mul, DW_OP_plus, DW_OP_stack_value), %stack.0.start, dbg-instr-ref(1, 0), debug-location !18
  ; CHECK-NEXT:   MOV32mi [[PHI]], 1, $noreg, 0, $noreg, 0 :: (store (s32) into %ir.lsr.iv)
  ; CHECK-NEXT:   RET 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.for.inc235:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[INC64r:%[0-9]+]]:gr64 = INC64r [[PHI1]], implicit-def dead $eflags
  ; CHECK-NEXT:   [[ADD64ri32_:%[0-9]+]]:gr64 = ADD64ri32 [[PHI]], 4, implicit-def dead $eflags
  ; CHECK-NEXT:   JMP_1 %bb.1
entry:
  %start = alloca %class.DomainBlockIterator.262, align 4
  %tmp136 = alloca %class.Loc.96, align 8
  br label %for.body13

for.body13:                                       ; preds = %for.inc235, %entry
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.inc235 ]
  br i1 %cmp15, label %if.then16, label %if.end116

if.then16:                                        ; preds = %for.body13
  call void @llvm.lifetime.start.p0(ptr %start)
  store i32 0, ptr %start, align 4
  ret void

if.end116:                                        ; preds = %for.body13
  br i1 %cmp15, label %if.then120, label %for.inc235

if.then120:                                       ; preds = %if.end116
  %arrayidx.i454 = getelementptr [4 x i8], ptr null, i64 %indvars.iv
  call void @llvm.lifetime.start.p0(ptr %tmp136)
  %arrayidx.i449 = getelementptr [4 x i8], ptr %tmp136, i64 %indvars.iv
    #dbg_value(ptr %arrayidx.i449, !9, !DIExpression(), !18)
  store i32 0, ptr %arrayidx.i449, align 4
  ret void

for.inc235:                                       ; preds = %if.end116
  %indvars.iv.next = add i64 %indvars.iv, 1
  br label %for.body13
}

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 23.0.0git (https://github.com/OCHyams/llvm-project 7e489b3ebf9c337c8b6ea74bef9c4f45f2dc4fd9)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "x.cpp", directory: "/home/och/reduce", checksumkind: CSK_MD5, checksum: "a79402ede23ff238de3e4647c4f3a326")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DISubprogram(name: "calcGCFillList", linkageName: "_ZN14GridLayoutDataILi3EE14calcGCFillListEv", scope: !5, file: !1, line: 31275, type: !6, scopeLine: 31276, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !8, retainedNodes: !2, keyInstructions: true)
!5 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "GridLayoutData<3>", file: !1, line: 30662, size: 4032, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS14GridLayoutDataILi3EE")
!6 = distinct !DISubroutineType(types: !7)
!7 = !{null}
!8 = !DISubprogram(name: "calcGCFillList", linkageName: "_ZN14GridLayoutDataILi3EE14calcGCFillListEv", scope: !5, file: !1, line: 31275, type: !6, scopeLine: 31275, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!9 = !DILocalVariable(name: "this", arg: 1, scope: !10, type: !17, flags: DIFlagArtificial | DIFlagObjectPointer)
!10 = distinct !DISubprogram(name: "operator-=<int>", linkageName: "_ZN6DomainILi1E12DomainTraitsI3LocILi1EEEEmIIiEERS2_RKT_", scope: !11, file: !1, line: 3525, type: !12, scopeLine: 3525, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !14, declaration: !13, retainedNodes: !2, keyInstructions: true)
!11 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Domain<1, DomainTraits<Loc<1> > >", file: !1, line: 3435, size: 32, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS6DomainILi1E12DomainTraitsI3LocILi1EEEE")
!12 = distinct !DISubroutineType(types: !2)
!13 = !DISubprogram(name: "operator-=<int>", linkageName: "_ZN6DomainILi1E12DomainTraitsI3LocILi1EEEEmIIiEERS2_RKT_", scope: !11, file: !1, line: 3525, type: !12, scopeLine: 3525, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized, templateParams: !14)
!14 = !{!15}
!15 = !DITemplateTypeParameter(name: "T", type: !16)
!16 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!17 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !11, size: 64)
!18 = !DILocation(line: 0, scope: !10, inlinedAt: !19)
!19 = distinct !DILocation(line: 31322, column: 15, scope: !20)
!20 = distinct !DILexicalBlock(scope: !21, file: !1, line: 31319, column: 6)
!21 = distinct !DILexicalBlock(scope: !22, file: !1, line: 31318, column: 4)
!22 = distinct !DILexicalBlock(scope: !23, file: !1, line: 31318, column: 4)
!23 = distinct !DILexicalBlock(scope: !24, file: !1, line: 31315, column: 2)
!24 = distinct !DILexicalBlock(scope: !25, file: !1, line: 31314, column: 11)
!25 = distinct !DILexicalBlock(scope: !26, file: !1, line: 31288, column: 5)
!26 = distinct !DILexicalBlock(scope: !27, file: !1, line: 31287, column: 3)
!27 = distinct !DILexicalBlock(scope: !4, file: !1, line: 31287, column: 3)
