; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc --stop-after=twoaddressinstruction %s -o - -mir-dbg-records -print-as-dbg-instrs \
; RUN: | FileCheck %s
; RUN: llc --stop-after=twoaddressinstruction %s -o - | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @_ZN11FieldEngineI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd14MultiPatchViewI7GridTag6RemoteI5BrickELi3EEEC2Id10MultiPatchIS7_SA_EEERKS_IS5_T_T0_ERK8IntervalILi3EE(i32 %inc) !dbg !4 {
  ; CHECK-LABEL: name: _ZN11FieldEngineI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd14MultiPatchViewI7GridTag6RemoteI5BrickELi3EEEC2Id10MultiPatchIS7_SA_EEERKS_IS5_T_T0_ERK8IntervalILi3EE
  ; CHECK: bb.0.invoke.cont5:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr32 = COPY killed $edi
  ; CHECK-NEXT:   [[MOV32r0_:%[0-9]+]]:gr32 = MOV32r0 implicit-def dead $eflags
  ; CHECK-NEXT:   [[SUBREG_TO_REG:%[0-9]+]]:gr64 = SUBREG_TO_REG killed [[MOV32r0_]], %subreg.sub_32bit
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.invoke.cont53:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   DBG_VALUE 0, $noreg, !9, !DIExpression(), debug-location !14
  ; CHECK-NEXT:   [[MOV32rm:%[0-9]+]]:gr32 = MOV32rm $noreg, 1, $noreg, 0, $noreg :: (load (s32) from `ptr null`, align 8)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr32 = COPY killed [[MOV32rm]], debug-location !23
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr32 = IMUL32rr [[COPY1]], [[COPY]], implicit-def dead $eflags, debug-location !23
  ; CHECK-NEXT:   [[MOVSX64rr32_:%[0-9]+]]:gr64 = MOVSX64rr32 killed [[COPY1]]
  ; CHECK-NEXT:   [[IMUL64rri32_:%[0-9]+]]:gr64 = IMUL64rri32 killed [[MOVSX64rr32_]], 104, implicit-def dead $eflags
  ; CHECK-NEXT:   ADJCALLSTACKDOWN64 0, 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
  ; CHECK-NEXT:   $rdi = COPY killed [[IMUL64rri32_]]
  ; CHECK-NEXT:   $rsi = COPY [[SUBREG_TO_REG]]
  ; CHECK-NEXT:   CALL64r [[SUBREG_TO_REG]], csr_64, implicit $rsp, implicit $ssp, implicit killed $rdi, implicit killed $rsi, implicit-def $rsp, implicit-def $ssp, implicit-def dead $rax
  ; CHECK-NEXT:   ADJCALLSTACKUP64 0, 0, implicit-def dead $rsp, implicit-def dead $eflags, implicit-def dead $ssp, implicit $rsp, implicit $ssp
  ; CHECK-NEXT:   JMP_1 %bb.1
invoke.cont5:
  br label %invoke.cont53

invoke.cont53:                                    ; preds = %invoke.cont53, %invoke.cont5
    #dbg_value(ptr null, !9, !DIExpression(), !14)
  %0 = load i32, ptr null, align 8
  %mul.i193 = mul i32 %0, %inc, !dbg !23
  %conv.i195 = sext i32 %mul.i193 to i64
  %add.ptr.i.i199 = getelementptr [104 x i8], ptr null, i64 %conv.i195
  %call62 = call ptr null(ptr %add.ptr.i.i199, ptr null)
  br label %invoke.cont53
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 23.0.0git (https://github.com/OCHyams/llvm-project 7e489b3ebf9c337c8b6ea74bef9c4f45f2dc4fd9)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "x.cpp", directory: "/home/och/reduce", checksumkind: CSK_MD5, checksum: "a79402ede23ff238de3e4647c4f3a326")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DISubprogram(name: "FieldEngine<double, MultiPatch<GridTag, Remote<Brick> > >", linkageName: "_ZN11FieldEngineI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd14MultiPatchViewI7GridTag6RemoteI5BrickELi3EEEC2Id10MultiPatchIS7_SA_EEERKS_IS5_T_T0_ERK8IntervalILi3EE", scope: !5, file: !1, line: 44979, type: !6, scopeLine: 44986, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !2, declaration: !8, retainedNodes: !2, keyInstructions: true)
!5 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FieldEngine<UniformRectilinearMesh<MeshTraits<3, double, UniformRectilinearTag, CartesianTag, 3> >, double, MultiPatchView<GridTag, Remote<Brick>, 3> >", file: !1, line: 44890, size: 1152, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS11FieldEngineI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd14MultiPatchViewI7GridTag6RemoteI5BrickELi3EEE")
!6 = distinct !DISubroutineType(types: !7)
!7 = !{null}
!8 = !DISubprogram(name: "FieldEngine<double, MultiPatch<GridTag, Remote<Brick> > >", linkageName: "_ZN11FieldEngineI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd14MultiPatchViewI7GridTag6RemoteI5BrickELi3EEEC4Id10MultiPatchIS7_SA_EEERKS_IS5_T_T0_ERK8IntervalILi3EE", scope: !5, file: !1, line: 44979, type: !6, scopeLine: 44979, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized, templateParams: !2)
!9 = !DILocalVariable(name: "this", arg: 1, scope: !10, type: !13, flags: DIFlagArtificial | DIFlagObjectPointer)
!10 = distinct !DISubprogram(name: "data", linkageName: "_ZN11FieldEngineI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd14MultiPatchViewI7GridTag6RemoteI5BrickELi3EEE4dataEii", scope: !5, file: !1, line: 45285, type: !11, scopeLine: 45286, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !12, retainedNodes: !2, keyInstructions: true)
!11 = distinct !DISubroutineType(types: !2)
!12 = !DISubprogram(name: "data", linkageName: "_ZN11FieldEngineI22UniformRectilinearMeshI10MeshTraitsILi3Ed21UniformRectilinearTag12CartesianTagLi3EEEd14MultiPatchViewI7GridTag6RemoteI5BrickELi3EEE4dataEii", scope: !5, file: !1, line: 45285, type: !11, scopeLine: 45285, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!13 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5, size: 64)
!14 = !DILocation(line: 0, scope: !10, inlinedAt: !15)
!15 = distinct !DILocation(line: 44999, column: 9, scope: !16)
!16 = distinct !DILexicalBlock(scope: !17, file: !1, line: 44998, column: 7)
!17 = distinct !DILexicalBlock(scope: !18, file: !1, line: 44997, column: 7)
!18 = distinct !DILexicalBlock(scope: !19, file: !1, line: 44997, column: 7)
!19 = distinct !DILexicalBlock(scope: !20, file: !1, line: 44995, column: 5)
!20 = distinct !DILexicalBlock(scope: !21, file: !1, line: 44994, column: 5)
!21 = distinct !DILexicalBlock(scope: !22, file: !1, line: 44994, column: 5)
!22 = distinct !DILexicalBlock(scope: !4, file: !1, line: 44986, column: 3)
!23 = !DILocation(line: 45288, column: 28, scope: !10, inlinedAt: !15)
