; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc --stop-after=twoaddressinstruction %s -o - -mir-dbg-records -print-as-dbg-instrs \
; RUN: | FileCheck %s
; RUN: llc --stop-after=twoaddressinstruction %s -o - | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @_ZN13DomainMapNodeI8IntervalILi1EEiED2Ev(ptr %this) !dbg !4 {
  ; CHECK-LABEL: name: _ZN13DomainMapNodeI8IntervalILi1EEiED2Ev
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x30000000), %bb.2(0x50000000)
  ; CHECK-NEXT:   liveins: $rdi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr64 = COPY killed $rdi
  ; CHECK-NEXT:   [[MOV64rm:%[0-9]+]]:gr64 = MOV64rm [[COPY]], 1, $noreg, 0, $noreg, debug-instr-number 1, debug-location !9 :: (load (s64) from %ir.this)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr64 = COPY killed [[COPY]]
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr64 = ADD64ri32 [[COPY1]], 32, implicit-def dead $eflags
  ; CHECK-NEXT:   DBG_INSTR_REF !24, !DIExpression(DW_OP_LLVM_arg, 0), dbg-instr-ref(1, 0), debug-location !28
  ; CHECK-NEXT:   CMP64rr [[MOV64rm]], killed [[COPY1]], implicit-def $eflags
  ; CHECK-NEXT:   JCC_1 %bb.2, 5, implicit killed $eflags
  ; CHECK-NEXT:   JMP_1 %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.common.ret:
  ; CHECK-NEXT:   RET 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.while.body.i.i:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   MOV64mi32 killed [[MOV64rm]], 1, $noreg, 0, $noreg, 0 :: (store (s64) into %ir.0)
  ; CHECK-NEXT:   JMP_1 %bb.1
entry:
  %list_m = getelementptr i8, ptr %this, i64 32
  %0 = load ptr, ptr %this, align 8, !dbg !9
    #dbg_value(ptr %0, !24, !DIExpression(), !28)
  %cmp.not9.i.i = icmp eq ptr %0, %list_m
  br i1 %cmp.not9.i.i, label %common.ret, label %while.body.i.i

common.ret:                                       ; preds = %while.body.i.i, %entry
  ret void

while.body.i.i:                                   ; preds = %entry
  store i64 0, ptr %0, align 8
  br label %common.ret
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 23.0.0git (https://github.com/OCHyams/llvm-project 7e489b3ebf9c337c8b6ea74bef9c4f45f2dc4fd9)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "x.cpp", directory: "/home/och/reduce", checksumkind: CSK_MD5, checksum: "a79402ede23ff238de3e4647c4f3a326")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DISubprogram(name: "~DomainMapNode", linkageName: "_ZN13DomainMapNodeI8IntervalILi1EEiED2Ev", scope: !5, file: !1, line: 8905, type: !6, scopeLine: 8905, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !8, retainedNodes: !2, keyInstructions: true)
!5 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DomainMapNode<Interval<1>, int>", file: !1, line: 8893, size: 448, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS13DomainMapNodeI8IntervalILi1EEiE")
!6 = distinct !DISubroutineType(types: !7)
!7 = !{null}
!8 = !DISubprogram(name: "~DomainMapNode", linkageName: "_ZN13DomainMapNodeI8IntervalILi1EEiED4Ev", scope: !5, file: !1, line: 8905, type: !6, scopeLine: 8905, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!9 = !DILocation(line: 70, column: 58, scope: !10, inlinedAt: !18, atomGroup: 1, atomRank: 2)
!10 = distinct !DISubprogram(name: "_M_clear", linkageName: "_ZNSt7__cxx1110_List_baseISt4pairI8IntervalILi1EEiESaIS4_EE8_M_clearEv", scope: !12, file: !11, line: 67, type: !16, scopeLine: 68, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !17, retainedNodes: !2, keyInstructions: true)
!11 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/list.tcc", directory: "", checksumkind: CSK_MD5, checksum: "f9e14195e3b39126d58f67842330de06")
!12 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "_List_base<std::pair<Interval<1>, int>, std::allocator<std::pair<Interval<1>, int> > >", scope: !14, file: !13, line: 350, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTSNSt7__cxx1110_List_baseISt4pairI8IntervalILi1EEiESaIS4_EEE")
!13 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_list.h", directory: "", checksumkind: CSK_MD5, checksum: "10807eb51dc43c99a91c93e176ba24b1")
!14 = !DINamespace(name: "__cxx11", scope: !15, exportSymbols: true)
!15 = !DINamespace(name: "std", scope: null)
!16 = distinct !DISubroutineType(types: !7)
!17 = !DISubprogram(name: "_M_clear", linkageName: "_ZNSt7__cxx1110_List_baseISt4pairI8IntervalILi1EEiESaIS4_EE8_M_clearEv", scope: !12, file: !11, line: 67, type: !16, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!18 = distinct !DILocation(line: 500, column: 9, scope: !19, inlinedAt: !22)
!19 = distinct !DILexicalBlock(scope: !20, file: !13, line: 500, column: 7)
!20 = distinct !DISubprogram(name: "~_List_base", linkageName: "_ZNSt7__cxx1110_List_baseISt4pairI8IntervalILi1EEiESaIS4_EED2Ev", scope: !12, file: !13, line: 499, type: !16, scopeLine: 500, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !21, retainedNodes: !2, keyInstructions: true)
!21 = !DISubprogram(name: "~_List_base", linkageName: "_ZNSt7__cxx1110_List_baseISt4pairI8IntervalILi1EEiESaIS4_EED4Ev", scope: !12, file: !13, line: 499, type: !16, scopeLine: 499, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!22 = distinct !DILocation(line: 8910, column: 3, scope: !23)
!23 = distinct !DILexicalBlock(scope: !4, file: !1, line: 8905, column: 20)
!24 = !DILocalVariable(name: "__cur", scope: !10, file: !11, line: 70, type: !25)
!25 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !26, size: 64)
!26 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_List_node_base", scope: !27, file: !13, line: 81, size: 128, flags: DIFlagTypePassByValue, elements: !2, identifier: "_ZTSNSt8__detail15_List_node_baseE")
!27 = !DINamespace(name: "__detail", scope: !15)
!28 = !DILocation(line: 0, scope: !10, inlinedAt: !18)
