; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc --stop-after=twoaddressinstruction %s -o - -mir-dbg-records -print-as-dbg-instrs \
; RUN: | FileCheck %s
; RUN: llc --stop-after=twoaddressinstruction %s -o - | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @_ZN14GridLayoutDataILi3EE10initializeI13GridPartitionILi3EEEEvRK8IntervalILi3EERKT_RK13ContextMapperILi3EE(ptr %this, i32 %0, i32 %1) !dbg !4 {
  ; CHECK-LABEL: name: _ZN14GridLayoutDataILi3EE10initializeI13GridPartitionILi3EEEEvRK8IntervalILi3EERKT_RK13ContextMapperILi3EE
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $rdi, $esi, $edx
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr32 = COPY killed $edx
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr32 = COPY killed $esi
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gr64 = COPY killed $rdi
  ; CHECK-NEXT:   [[MOV32rm:%[0-9]+]]:gr32 = MOV32rm $noreg, 1, $noreg, 0, $noreg :: (load (s32) from `ptr null`)
  ; CHECK-NEXT:   MOV32mi [[COPY2]], 1, $noreg, 0, $noreg, 0 :: (store (s32) into %ir.this)
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gr32 = COPY killed [[COPY1]], debug-location !23
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gr32 = OR32rr [[COPY3]], [[MOV32rm]], implicit-def dead $eflags, debug-location !23
  ; CHECK-NEXT:   DBG_VALUE 0, $noreg, !9, !DIExpression(), debug-location !19
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gr32 = COPY killed [[MOV32rm]]
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gr32 = SUB32rr [[COPY4]], killed [[COPY]], implicit-def dead $eflags
  ; CHECK-NEXT:   MOV32mr $noreg, 1, $noreg, 0, $noreg, killed [[COPY4]] :: (store (s32) into `ptr null`, align 8)
  ; CHECK-NEXT:   MOV32mr killed [[COPY2]], 1, $noreg, 0, $noreg, killed [[COPY3]] :: (store (s32) into %ir.this)
  ; CHECK-NEXT:   RET 0
entry:
  %2 = load i32, ptr null, align 4
  store i32 0, ptr %this, align 4
    #dbg_value(ptr null, !9, !DIExpression(), !19)
  %sub.i = sub i32 %2, %1
  store i32 %sub.i, ptr null, align 8
  %add.i = or i32 %0, %2, !dbg !23
  store i32 %add.i, ptr %this, align 4
  ret void
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 23.0.0git (https://github.com/OCHyams/llvm-project 7e489b3ebf9c337c8b6ea74bef9c4f45f2dc4fd9)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "x.cpp", directory: "/home/och/reduce", checksumkind: CSK_MD5, checksum: "a79402ede23ff238de3e4647c4f3a326")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DISubprogram(name: "initialize<GridPartition<3> >", linkageName: "_ZN14GridLayoutDataILi3EE10initializeI13GridPartitionILi3EEEEvRK8IntervalILi3EERKT_RK13ContextMapperILi3EE", scope: !5, file: !1, line: 31159, type: !6, scopeLine: 31162, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !2, declaration: !8, retainedNodes: !2, keyInstructions: true)
!5 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "GridLayoutData<3>", file: !1, line: 30662, size: 4032, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS14GridLayoutDataILi3EE")
!6 = distinct !DISubroutineType(types: !7)
!7 = !{null}
!8 = !DISubprogram(name: "initialize<GridPartition<3> >", linkageName: "_ZN14GridLayoutDataILi3EE10initializeI13GridPartitionILi3EEEEvRK8IntervalILi3EERKT_RK13ContextMapperILi3EE", scope: !5, file: !1, line: 31159, type: !6, scopeLine: 31159, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized, templateParams: !2)
!9 = !DILocalVariable(name: "dom", arg: 1, scope: !10, file: !1, line: 5749, type: !14)
!10 = distinct !DISubprogram(name: "addGuardLayers", linkageName: "_ZN11GuardLayersILi3EE14addGuardLayersER8IntervalILi3EERKS0_", scope: !11, file: !1, line: 5749, type: !12, scopeLine: 5750, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !13, retainedNodes: !2, keyInstructions: true)
!11 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "GuardLayers<3>", file: !1, line: 5637, size: 192, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS11GuardLayersILi3EE")
!12 = distinct !DISubroutineType(types: !7)
!13 = !DISubprogram(name: "addGuardLayers", linkageName: "_ZN11GuardLayersILi3EE14addGuardLayersER8IntervalILi3EERKS0_", scope: !11, file: !1, line: 5749, type: !12, scopeLine: 5749, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!14 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !15, size: 64)
!15 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Interval<3>", file: !1, line: 4323, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !16, identifier: "_ZTS8IntervalILi3EE")
!16 = !{!17}
!17 = !DITemplateValueParameter(name: "Dim", type: !18, value: i32 3)
!18 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!19 = !DILocation(line: 0, scope: !10, inlinedAt: !20)
!20 = distinct !DILocation(line: 31185, column: 7, scope: !21)
!21 = distinct !DILexicalBlock(scope: !22, file: !1, line: 31183, column: 5)
!22 = distinct !DILexicalBlock(scope: !4, file: !1, line: 31182, column: 7)
!23 = !DILocation(line: 5754, column: 31, scope: !24, inlinedAt: !20, atomGroup: 5, atomRank: 2)
!24 = distinct !DILexicalBlock(scope: !25, file: !1, line: 5752, column: 7)
!25 = distinct !DILexicalBlock(scope: !26, file: !1, line: 5751, column: 5)
!26 = distinct !DILexicalBlock(scope: !10, file: !1, line: 5751, column: 5)
