; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt %s -o - -S | llvm-as - | llvm-dis - | FileCheck %s

; Key Instructions enabled.
define dso_local void @f() !dbg !5 {
; CHECK-LABEL: define dso_local void @f(
; CHECK-SAME: ) !dbg [[DBG5:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret void, !dbg [[DBG8:![0-9]+]]
;
entry:
  ret void, !dbg !8  ; atomGroup: 1, atomRank: 1
}

; Key Instructions enabled, atomGroup > 1 and forward-ref scope in DILocation.
define dso_local void @g() !dbg !10 {
; CHECK-LABEL: define dso_local void @g(
; CHECK-SAME: ) !dbg [[DBG9:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret void, !dbg [[DBG10:![0-9]+]]
;
entry:
  ret void, !dbg !9  ; atomGroup: 2, atomRank: 2
}

; Key Instructions not enabled.
define dso_local void @h() !dbg !11 {
; CHECK-LABEL: define dso_local void @h(
; CHECK-SAME: ) !dbg [[DBG11:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret void, !dbg [[DBG12:![0-9]+]]
;
entry:
  ret void, !dbg !12 ; atomGroup: 0, atomRank: 0
}

; Key Instructions, inlined instruction (from g).
define dso_local void @i() !dbg !13 {
; CHECK-LABEL: define dso_local void @i(
; CHECK-SAME: ) !dbg [[DBG13:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret void, !dbg [[DBG14:![0-9]+]]
;
entry:
  ret void, !dbg !14 ; scope g, inlinedAt i:4, atomGroup: 2, atomRank: 0
}

!llvm.dbg.cu = !{!0}
!llvm.debugify = !{!2, !3}
!llvm.module.flags = !{!4}

!0 = distinct !DICompileUnit(language: DW_LANG_C, file: !1, producer: "debugify", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
!1 = !DIFile(filename: "roundtrip.ll", directory: "/")
!2 = !{i32 2}
!3 = !{i32 0}
!4 = !{i32 2, !"Debug Info Version", i32 3}
!5 = distinct !DISubprogram(name: "f", linkageName: "f", scope: null, file: !1, line: 1, type: !6, scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, nextAtomGroup: 2)
!6 = !DISubroutineType(types: !7)
!7 = !{}
!8 = !DILocation(line: 1, scope: !5, atomGroup: 1, atomRank: 1)
!9 = !DILocation(line: 2, scope: !10, atomGroup: 2, atomRank: 2) ; fwd-ref scope.
!10 = distinct !DISubprogram(name: "g", linkageName: "g", scope: null, file: !1, line: 2, type: !6, scopeLine: 2, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, nextAtomGroup: 3)
!11 = distinct !DISubprogram(name: "h", linkageName: "h", scope: null, file: !1, line: 3, type: !6, scopeLine: 3, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0)
!12 = !DILocation(line: 3, scope: !11)
!13 = distinct !DISubprogram(name: "i", linkageName: "i", scope: null, file: !1, line: 4, type: !6, scopeLine: 4, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, nextAtomGroup: 3)
!14 = !DILocation(line: 2, scope: !10, inlinedAt: !15, atomGroup: 2, atomRank: 1) ; fwd-ref inlinedAt.
!15 = distinct !DILocation(line: 4, scope: !13)
;.
; CHECK: [[META0:![0-9]+]] = distinct !DICompileUnit(language: DW_LANG_C, file: [[META1:![0-9]+]], producer: "debugify", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
; CHECK: [[META1]] = !DIFile(filename: "{{.*}}roundtrip.ll", directory: {{.*}})
; CHECK: [[DBG5]] = distinct !DISubprogram(name: "f", linkageName: "f", scope: null, file: [[META1]], line: 1, type: [[META6:![0-9]+]], scopeLine: 1, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: [[META0]], nextAtomGroup: 2)
; CHECK: [[META6]] = !DISubroutineType(types: [[META7:![0-9]+]])
; CHECK: [[META7]] = !{}
; CHECK: [[DBG8]] = !DILocation(line: 1, scope: [[DBG5]], atomGroup: 1, atomRank: 1)
; CHECK: [[DBG9]] = distinct !DISubprogram(name: "g", linkageName: "g", scope: null, file: [[META1]], line: 2, type: [[META6]], scopeLine: 2, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: [[META0]], nextAtomGroup: 3)
; CHECK: [[DBG10]] = !DILocation(line: 2, scope: [[DBG9]], atomGroup: 2, atomRank: 2)
; CHECK: [[DBG11]] = distinct !DISubprogram(name: "h", linkageName: "h", scope: null, file: [[META1]], line: 3, type: [[META6]], scopeLine: 3, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: [[META0]])
; CHECK: [[DBG12]] = !DILocation(line: 3, scope: [[DBG11]])
; CHECK: [[DBG13]] = distinct !DISubprogram(name: "i", linkageName: "i", scope: null, file: [[META1]], line: 4, type: [[META6]], scopeLine: 4, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: [[META0]], nextAtomGroup: 3)
; CHECK: [[DBG14]] = !DILocation(line: 2, scope: [[DBG9]], inlinedAt: [[META15:![0-9]+]], atomGroup: 2, atomRank: 1)
; CHECK: [[META15]] = distinct !DILocation(line: 4, scope: [[DBG13]])
;.
