; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -o - -S --passes=simplifycfg | FileCheck %s
; Having multiple dbg.values sinking onto each other didn't always work.
; ModuleID = 'insert-dbg-values-in-chain.ll'
source_filename = "insert-dbg-values-in-chain.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define internal fastcc void @_ZL4getUIhET_PjPKN4llvm13DataExtractorEbPKc(ptr %offset_ptr) unnamed_addr {
; CHECK-LABEL: @_ZL4getUIhET_PjPKN4llvm13DataExtractorEbPKc(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    store ptr [[OFFSET_PTR:%.*]], ptr [[OFFSET_PTR]], align 8
; CHECK-NEXT:    [[CALL:%.*]] = call i1 @_ZNK4llvm13DataExtractor26isValidOffsetForDataOfSizeEjj()
; CHECK-NEXT:    br i1 [[CALL]], label [[IF_THEN1:%.*]], label [[IF_END5:%.*]]
; CHECK:       if.then1:
; CHECK-NEXT:    [[CALL2:%.*]] = call i8 @_ZN4llvm3sys13SwapByteOrderEh()
; CHECK-NEXT:    call void @llvm.dbg.value(metadata i8 [[CALL2]], metadata [[META1348:![0-9]+]], metadata !DIExpression()), !dbg [[DBG1365:![0-9]+]]
; CHECK-NEXT:    call void @llvm.dbg.value(metadata i8 [[CALL2]], metadata [[META1348]], metadata !DIExpression()), !dbg [[DBG1365]]
; CHECK-NEXT:    store i32 0, ptr [[OFFSET_PTR]], align 4
; CHECK-NEXT:    br label [[IF_END5]]
; CHECK:       if.end5:
; CHECK-NEXT:    call void @llvm.dbg.value(metadata i8 undef, metadata [[META1348]], metadata !DIExpression()), !dbg [[DBG1365]]
; CHECK-NEXT:    ret void
;
entry:
  store ptr %offset_ptr, ptr %offset_ptr, align 8
  %call = call i1 @_ZNK4llvm13DataExtractor26isValidOffsetForDataOfSizeEjj()
  br i1 %call, label %if.then, label %if.end5

if.then:                                          ; preds = %entry
  br label %if.then1

if.then1:                                         ; preds = %if.then
  %call2 = call i8 @_ZN4llvm3sys13SwapByteOrderEh()
  call void @llvm.dbg.value(metadata i8 %call2, metadata !1348, metadata !DIExpression()), !dbg !1365
  br label %if.end

if.end:                                           ; preds = %if.then1
  call void @llvm.dbg.value(metadata i8 %call2, metadata !1348, metadata !DIExpression()), !dbg !1365
  store i32 0, ptr %offset_ptr, align 4
  br label %if.end5

if.end5:                                          ; preds = %if.end, %entry
  call void @llvm.dbg.value(metadata i8 undef, metadata !1348, metadata !DIExpression()), !dbg !1365
  ret void
}

declare i1 @_ZNK4llvm13DataExtractor26isValidOffsetForDataOfSizeEjj() local_unnamed_addr

declare i8 @_ZN4llvm3sys13SwapByteOrderEh()

; Function Attrs: nocallback nofree nosync nounwind readnone speculatable willreturn
declare void @llvm.dbg.value(metadata, metadata, metadata) #0

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!1343, !1344, !1345, !1346, !1347}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, retainedTypes: !2, globals: !25, imports: !69, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "/fast/fs/llvm34/lib/Support/DataExtractor.cpp", directory: "/fast/fs/build34llvm5", checksumkind: CSK_MD5, checksum: "2452a439738dbbbedce15e8f60b67ac4")
!2 = !{!3, !8, !11, !14, !17, !21, !22}
!3 = !DIDerivedType(tag: DW_TAG_typedef, name: "int8_t", file: !4, line: 24, baseType: !5)
!4 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h", directory: "", checksumkind: CSK_MD5, checksum: "457547631e07cd24d9a14c8410e28e57")
!5 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int8_t", file: !6, line: 36, baseType: !7)
!6 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types.h", directory: "", checksumkind: CSK_MD5, checksum: "25679ba19d359e314e48661b21f5aa1f")
!7 = !DIBasicType(name: "signed char", size: 8, encoding: DW_ATE_signed_char)
!8 = !DIDerivedType(tag: DW_TAG_typedef, name: "int16_t", file: !4, line: 25, baseType: !9)
!9 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int16_t", file: !6, line: 38, baseType: !10)
!10 = !DIBasicType(name: "short", size: 16, encoding: DW_ATE_signed)
!11 = !DIDerivedType(tag: DW_TAG_typedef, name: "int32_t", file: !4, line: 26, baseType: !12)
!12 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int32_t", file: !6, line: 40, baseType: !13)
!13 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!14 = !DIDerivedType(tag: DW_TAG_typedef, name: "int64_t", file: !4, line: 27, baseType: !15)
!15 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int64_t", file: !6, line: 43, baseType: !16)
!16 = !DIBasicType(name: "long", size: 64, encoding: DW_ATE_signed)
!17 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint64_t", file: !18, line: 27, baseType: !19)
!18 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h", directory: "", checksumkind: CSK_MD5, checksum: "9754ebe022edbe8d7928fa709e442f0d")
!19 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint64_t", file: !6, line: 44, baseType: !20)
!20 = !DIBasicType(name: "unsigned long", size: 64, encoding: DW_ATE_unsigned)
!21 = !DIBasicType(name: "bool", size: 8, encoding: DW_ATE_boolean)
!22 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringRef", scope: !24, file: !23, line: 41, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm9StringRefE")
!23 = !DIFile(filename: "llvm34/include/llvm/ADT/StringRef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "5c2e300880041c873457392c89335431")
!24 = !DINamespace(name: "llvm", scope: null)
!25 = !{!26, !34, !39, !44, !49, !54, !59, !64}
!26 = !DIGlobalVariableExpression(var: !27, expr: !DIExpression())
!27 = distinct !DIGlobalVariable(scope: null, file: !28, line: 103, type: !29, isLocal: true, isDefinition: true)
!28 = !DIFile(filename: "llvm34/lib/Support/DataExtractor.cpp", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "2452a439738dbbbedce15e8f60b67ac4")
!29 = !DICompositeType(tag: DW_TAG_array_type, baseType: !30, size: 224, elements: !32)
!30 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !31)
!31 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
!32 = !{!33}
!33 = !DISubrange(count: 28)
!34 = !DIGlobalVariableExpression(var: !35, expr: !DIExpression())
!35 = distinct !DIGlobalVariable(scope: null, file: !28, line: 103, type: !36, isLocal: true, isDefinition: true)
!36 = !DICompositeType(tag: DW_TAG_array_type, baseType: !30, size: 368, elements: !37)
!37 = !{!38}
!38 = !DISubrange(count: 46)
!39 = !DIGlobalVariableExpression(var: !40, expr: !DIExpression())
!40 = distinct !DIGlobalVariable(scope: null, file: !28, line: 118, type: !41, isLocal: true, isDefinition: true)
!41 = !DICompositeType(tag: DW_TAG_array_type, baseType: !30, size: 208, elements: !42)
!42 = !{!43}
!43 = !DISubrange(count: 26)
!44 = !DIGlobalVariableExpression(var: !45, expr: !DIExpression())
!45 = distinct !DIGlobalVariable(scope: null, file: !23, line: 191, type: !46, isLocal: true, isDefinition: true)
!46 = !DICompositeType(tag: DW_TAG_array_type, baseType: !30, size: 120, elements: !47)
!47 = !{!48}
!48 = !DISubrange(count: 15)
!49 = !DIGlobalVariableExpression(var: !50, expr: !DIExpression())
!50 = distinct !DIGlobalVariable(scope: null, file: !23, line: 191, type: !51, isLocal: true, isDefinition: true)
!51 = !DICompositeType(tag: DW_TAG_array_type, baseType: !30, size: 280, elements: !52)
!52 = !{!53}
!53 = !DISubrange(count: 35)
!54 = !DIGlobalVariableExpression(var: !55, expr: !DIExpression())
!55 = distinct !DIGlobalVariable(scope: null, file: !23, line: 191, type: !56, isLocal: true, isDefinition: true)
!56 = !DICompositeType(tag: DW_TAG_array_type, baseType: !30, size: 360, elements: !57)
!57 = !{!58}
!58 = !DISubrange(count: 45)
!59 = !DIGlobalVariableExpression(var: !60, expr: !DIExpression())
!60 = distinct !DIGlobalVariable(scope: null, file: !23, line: 191, type: !61, isLocal: true, isDefinition: true)
!61 = !DICompositeType(tag: DW_TAG_array_type, baseType: !30, size: 376, elements: !62)
!62 = !{!63}
!63 = !DISubrange(count: 47)
!64 = !DIGlobalVariableExpression(var: !65, expr: !DIExpression(DW_OP_constu, 1, DW_OP_stack_value))
!65 = distinct !DIGlobalVariable(name: "IsLittleEndianHost", scope: !66, file: !67, line: 38, type: !68, isLocal: true, isDefinition: true)
!66 = !DINamespace(name: "sys", scope: !24)
!67 = !DIFile(filename: "llvm34/include/llvm/Support/Host.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "5166b69c575a98e5b18a6a5f5c749d89")
!68 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !21)
!69 = !{!70, !77, !84, !86, !88, !92, !94, !96, !98, !100, !102, !104, !106, !111, !115, !117, !119, !124, !126, !128, !130, !132, !134, !136, !139, !142, !144, !148, !153, !155, !157, !159, !161, !163, !165, !167, !169, !171, !173, !177, !181, !183, !185, !187, !189, !191, !193, !195, !197, !199, !201, !203, !205, !207, !209, !211, !215, !219, !223, !225, !227, !229, !231, !233, !235, !237, !239, !241, !245, !249, !253, !255, !257, !259, !264, !268, !272, !274, !276, !278, !280, !282, !284, !286, !288, !290, !292, !294, !296, !300, !304, !308, !310, !312, !314, !319, !323, !327, !329, !331, !333, !335, !337, !339, !343, !347, !349, !351, !353, !355, !359, !363, !367, !369, !371, !373, !375, !377, !379, !383, !387, !391, !393, !397, !401, !403, !405, !407, !409, !411, !413, !418, !429, !433, !439, !443, !447, !454, !458, !460, !462, !466, !470, !474, !478, !482, !484, !486, !488, !492, !496, !500, !502, !504, !508, !512, !518, !522, !527, !529, !532, !536, !540, !549, !553, !557, !561, !565, !569, !573, !577, !581, !585, !592, !596, !600, !602, !606, !610, !615, !621, !625, !629, !631, !638, !642, !649, !651, !655, !659, !663, !667, !672, !676, !680, !681, !682, !683, !685, !686, !687, !688, !689, !690, !691, !695, !699, !716, !719, !724, !777, !782, !786, !790, !794, !798, !800, !802, !806, !812, !816, !822, !828, !830, !834, !838, !842, !846, !858, !860, !864, !868, !872, !874, !878, !882, !886, !888, !890, !894, !902, !906, !910, !914, !916, !922, !924, !930, !934, !938, !942, !946, !950, !954, !956, !958, !962, !966, !970, !972, !976, !980, !982, !984, !988, !992, !996, !1000, !1001, !1002, !1003, !1004, !1005, !1006, !1007, !1008, !1009, !1010, !1012, !1013, !1014, !1015, !1018, !1020, !1022, !1024, !1026, !1028, !1030, !1032, !1035, !1037, !1041, !1044, !1047, !1048, !1050, !1052, !1054, !1056, !1058, !1060, !1062, !1064, !1067, !1069, !1073, !1077, !1082, !1086, !1088, !1090, !1092, !1094, !1096, !1098, !1100, !1102, !1104, !1106, !1108, !1110, !1112, !1116, !1118, !1122, !1128, !1133, !1137, !1139, !1141, !1143, !1145, !1152, !1156, !1160, !1164, !1168, !1172, !1176, !1180, !1182, !1186, !1192, !1196, !1200, !1202, !1205, !1209, !1213, !1215, !1217, !1219, !1221, !1223, !1225, !1227, !1231, !1235, !1239, !1243, !1247, !1251, !1253, !1257, !1261, !1265, !1269, !1271, !1273, !1277, !1281, !1282, !1283, !1284, !1285, !1286, !1292, !1295, !1296, !1298, !1300, !1302, !1304, !1308, !1310, !1312, !1314, !1316, !1318, !1320, !1322, !1324, !1328, !1332, !1334, !1338, !1342}
!70 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !72, file: !76, line: 52)
!71 = !DINamespace(name: "std", scope: null)
!72 = !DISubprogram(name: "abs", scope: !73, file: !73, line: 837, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!73 = !DIFile(filename: "/usr/include/stdlib.h", directory: "", checksumkind: CSK_MD5, checksum: "69d942f1572b8bd342d93c49f499f318")
!74 = !DISubroutineType(types: !75)
!75 = !{!13, !13}
!76 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h", directory: "")
!77 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !78, file: !83, line: 83)
!78 = !DISubprogram(name: "acos", scope: !79, file: !79, line: 53, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!79 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", directory: "", checksumkind: CSK_MD5, checksum: "540523e6856cf8d57a3ebef5fd79793e")
!80 = !DISubroutineType(types: !81)
!81 = !{!82, !82}
!82 = !DIBasicType(name: "double", size: 64, encoding: DW_ATE_float)
!83 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cmath", directory: "")
!84 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !85, file: !83, line: 102)
!85 = !DISubprogram(name: "asin", scope: !79, file: !79, line: 55, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!86 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !87, file: !83, line: 121)
!87 = !DISubprogram(name: "atan", scope: !79, file: !79, line: 57, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!88 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !89, file: !83, line: 140)
!89 = !DISubprogram(name: "atan2", scope: !79, file: !79, line: 59, type: !90, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!90 = !DISubroutineType(types: !91)
!91 = !{!82, !82, !82}
!92 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !93, file: !83, line: 161)
!93 = !DISubprogram(name: "ceil", scope: !79, file: !79, line: 159, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!94 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !95, file: !83, line: 180)
!95 = !DISubprogram(name: "cos", scope: !79, file: !79, line: 62, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!96 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !97, file: !83, line: 199)
!97 = !DISubprogram(name: "cosh", scope: !79, file: !79, line: 71, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!98 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !99, file: !83, line: 218)
!99 = !DISubprogram(name: "exp", scope: !79, file: !79, line: 95, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!100 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !101, file: !83, line: 237)
!101 = !DISubprogram(name: "fabs", scope: !79, file: !79, line: 162, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!102 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !103, file: !83, line: 256)
!103 = !DISubprogram(name: "floor", scope: !79, file: !79, line: 165, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!104 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !105, file: !83, line: 275)
!105 = !DISubprogram(name: "fmod", scope: !79, file: !79, line: 168, type: !90, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!106 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !107, file: !83, line: 296)
!107 = !DISubprogram(name: "frexp", scope: !79, file: !79, line: 98, type: !108, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!108 = !DISubroutineType(types: !109)
!109 = !{!82, !82, !110}
!110 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !13, size: 64)
!111 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !112, file: !83, line: 315)
!112 = !DISubprogram(name: "ldexp", scope: !79, file: !79, line: 101, type: !113, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!113 = !DISubroutineType(types: !114)
!114 = !{!82, !82, !13}
!115 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !116, file: !83, line: 334)
!116 = !DISubprogram(name: "log", scope: !79, file: !79, line: 104, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!117 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !118, file: !83, line: 353)
!118 = !DISubprogram(name: "log10", scope: !79, file: !79, line: 107, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!119 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !120, file: !83, line: 372)
!120 = !DISubprogram(name: "modf", scope: !79, file: !79, line: 110, type: !121, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!121 = !DISubroutineType(types: !122)
!122 = !{!82, !82, !123}
!123 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !82, size: 64)
!124 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !125, file: !83, line: 384)
!125 = !DISubprogram(name: "pow", scope: !79, file: !79, line: 140, type: !90, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!126 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !127, file: !83, line: 421)
!127 = !DISubprogram(name: "sin", scope: !79, file: !79, line: 64, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!128 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !129, file: !83, line: 440)
!129 = !DISubprogram(name: "sinh", scope: !79, file: !79, line: 73, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!130 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !131, file: !83, line: 459)
!131 = !DISubprogram(name: "sqrt", scope: !79, file: !79, line: 143, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!132 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !133, file: !83, line: 478)
!133 = !DISubprogram(name: "tan", scope: !79, file: !79, line: 66, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!134 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !135, file: !83, line: 497)
!135 = !DISubprogram(name: "tanh", scope: !79, file: !79, line: 75, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!136 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !137, file: !83, line: 1065)
!137 = !DIDerivedType(tag: DW_TAG_typedef, name: "double_t", file: !138, line: 150, baseType: !82)
!138 = !DIFile(filename: "/usr/include/math.h", directory: "", checksumkind: CSK_MD5, checksum: "ecf196918078d683ff91ad9a1c51599a")
!139 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !140, file: !83, line: 1066)
!140 = !DIDerivedType(tag: DW_TAG_typedef, name: "float_t", file: !138, line: 149, baseType: !141)
!141 = !DIBasicType(name: "float", size: 32, encoding: DW_ATE_float)
!142 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !143, file: !83, line: 1069)
!143 = !DISubprogram(name: "acosh", scope: !79, file: !79, line: 85, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!144 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !145, file: !83, line: 1070)
!145 = !DISubprogram(name: "acoshf", scope: !79, file: !79, line: 85, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!146 = !DISubroutineType(types: !147)
!147 = !{!141, !141}
!148 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !149, file: !83, line: 1071)
!149 = !DISubprogram(name: "acoshl", scope: !79, file: !79, line: 85, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!150 = !DISubroutineType(types: !151)
!151 = !{!152, !152}
!152 = !DIBasicType(name: "long double", size: 128, encoding: DW_ATE_float)
!153 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !154, file: !83, line: 1073)
!154 = !DISubprogram(name: "asinh", scope: !79, file: !79, line: 87, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!155 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !156, file: !83, line: 1074)
!156 = !DISubprogram(name: "asinhf", scope: !79, file: !79, line: 87, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!157 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !158, file: !83, line: 1075)
!158 = !DISubprogram(name: "asinhl", scope: !79, file: !79, line: 87, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!159 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !160, file: !83, line: 1077)
!160 = !DISubprogram(name: "atanh", scope: !79, file: !79, line: 89, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!161 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !162, file: !83, line: 1078)
!162 = !DISubprogram(name: "atanhf", scope: !79, file: !79, line: 89, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!163 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !164, file: !83, line: 1079)
!164 = !DISubprogram(name: "atanhl", scope: !79, file: !79, line: 89, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!165 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !166, file: !83, line: 1081)
!166 = !DISubprogram(name: "cbrt", scope: !79, file: !79, line: 152, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!167 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !168, file: !83, line: 1082)
!168 = !DISubprogram(name: "cbrtf", scope: !79, file: !79, line: 152, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!169 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !170, file: !83, line: 1083)
!170 = !DISubprogram(name: "cbrtl", scope: !79, file: !79, line: 152, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!171 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !172, file: !83, line: 1085)
!172 = !DISubprogram(name: "copysign", scope: !79, file: !79, line: 196, type: !90, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!173 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !174, file: !83, line: 1086)
!174 = !DISubprogram(name: "copysignf", scope: !79, file: !79, line: 196, type: !175, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!175 = !DISubroutineType(types: !176)
!176 = !{!141, !141, !141}
!177 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !178, file: !83, line: 1087)
!178 = !DISubprogram(name: "copysignl", scope: !79, file: !79, line: 196, type: !179, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!179 = !DISubroutineType(types: !180)
!180 = !{!152, !152, !152}
!181 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !182, file: !83, line: 1089)
!182 = !DISubprogram(name: "erf", scope: !79, file: !79, line: 228, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!183 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !184, file: !83, line: 1090)
!184 = !DISubprogram(name: "erff", scope: !79, file: !79, line: 228, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!185 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !186, file: !83, line: 1091)
!186 = !DISubprogram(name: "erfl", scope: !79, file: !79, line: 228, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!187 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !188, file: !83, line: 1093)
!188 = !DISubprogram(name: "erfc", scope: !79, file: !79, line: 229, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!189 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !190, file: !83, line: 1094)
!190 = !DISubprogram(name: "erfcf", scope: !79, file: !79, line: 229, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!191 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !192, file: !83, line: 1095)
!192 = !DISubprogram(name: "erfcl", scope: !79, file: !79, line: 229, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!193 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !194, file: !83, line: 1097)
!194 = !DISubprogram(name: "exp2", scope: !79, file: !79, line: 130, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!195 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !196, file: !83, line: 1098)
!196 = !DISubprogram(name: "exp2f", scope: !79, file: !79, line: 130, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!197 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !198, file: !83, line: 1099)
!198 = !DISubprogram(name: "exp2l", scope: !79, file: !79, line: 130, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!199 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !200, file: !83, line: 1101)
!200 = !DISubprogram(name: "expm1", scope: !79, file: !79, line: 119, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!201 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !202, file: !83, line: 1102)
!202 = !DISubprogram(name: "expm1f", scope: !79, file: !79, line: 119, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!203 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !204, file: !83, line: 1103)
!204 = !DISubprogram(name: "expm1l", scope: !79, file: !79, line: 119, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!205 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !206, file: !83, line: 1105)
!206 = !DISubprogram(name: "fdim", scope: !79, file: !79, line: 326, type: !90, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!207 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !208, file: !83, line: 1106)
!208 = !DISubprogram(name: "fdimf", scope: !79, file: !79, line: 326, type: !175, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!209 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !210, file: !83, line: 1107)
!210 = !DISubprogram(name: "fdiml", scope: !79, file: !79, line: 326, type: !179, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!211 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !212, file: !83, line: 1109)
!212 = !DISubprogram(name: "fma", scope: !79, file: !79, line: 335, type: !213, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!213 = !DISubroutineType(types: !214)
!214 = !{!82, !82, !82, !82}
!215 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !216, file: !83, line: 1110)
!216 = !DISubprogram(name: "fmaf", scope: !79, file: !79, line: 335, type: !217, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!217 = !DISubroutineType(types: !218)
!218 = !{!141, !141, !141, !141}
!219 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !220, file: !83, line: 1111)
!220 = !DISubprogram(name: "fmal", scope: !79, file: !79, line: 335, type: !221, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!221 = !DISubroutineType(types: !222)
!222 = !{!152, !152, !152, !152}
!223 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !224, file: !83, line: 1113)
!224 = !DISubprogram(name: "fmax", scope: !79, file: !79, line: 329, type: !90, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!225 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !226, file: !83, line: 1114)
!226 = !DISubprogram(name: "fmaxf", scope: !79, file: !79, line: 329, type: !175, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!227 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !228, file: !83, line: 1115)
!228 = !DISubprogram(name: "fmaxl", scope: !79, file: !79, line: 329, type: !179, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!229 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !230, file: !83, line: 1117)
!230 = !DISubprogram(name: "fmin", scope: !79, file: !79, line: 332, type: !90, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!231 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !232, file: !83, line: 1118)
!232 = !DISubprogram(name: "fminf", scope: !79, file: !79, line: 332, type: !175, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!233 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !234, file: !83, line: 1119)
!234 = !DISubprogram(name: "fminl", scope: !79, file: !79, line: 332, type: !179, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!235 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !236, file: !83, line: 1121)
!236 = !DISubprogram(name: "hypot", scope: !79, file: !79, line: 147, type: !90, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!237 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !238, file: !83, line: 1122)
!238 = !DISubprogram(name: "hypotf", scope: !79, file: !79, line: 147, type: !175, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!239 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !240, file: !83, line: 1123)
!240 = !DISubprogram(name: "hypotl", scope: !79, file: !79, line: 147, type: !179, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!241 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !242, file: !83, line: 1125)
!242 = !DISubprogram(name: "ilogb", scope: !79, file: !79, line: 280, type: !243, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!243 = !DISubroutineType(types: !244)
!244 = !{!13, !82}
!245 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !246, file: !83, line: 1126)
!246 = !DISubprogram(name: "ilogbf", scope: !79, file: !79, line: 280, type: !247, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!247 = !DISubroutineType(types: !248)
!248 = !{!13, !141}
!249 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !250, file: !83, line: 1127)
!250 = !DISubprogram(name: "ilogbl", scope: !79, file: !79, line: 280, type: !251, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!251 = !DISubroutineType(types: !252)
!252 = !{!13, !152}
!253 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !254, file: !83, line: 1129)
!254 = !DISubprogram(name: "lgamma", scope: !79, file: !79, line: 230, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!255 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !256, file: !83, line: 1130)
!256 = !DISubprogram(name: "lgammaf", scope: !79, file: !79, line: 230, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!257 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !258, file: !83, line: 1131)
!258 = !DISubprogram(name: "lgammal", scope: !79, file: !79, line: 230, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!259 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !260, file: !83, line: 1134)
!260 = !DISubprogram(name: "llrint", scope: !79, file: !79, line: 316, type: !261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!261 = !DISubroutineType(types: !262)
!262 = !{!263, !82}
!263 = !DIBasicType(name: "long long", size: 64, encoding: DW_ATE_signed)
!264 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !265, file: !83, line: 1135)
!265 = !DISubprogram(name: "llrintf", scope: !79, file: !79, line: 316, type: !266, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!266 = !DISubroutineType(types: !267)
!267 = !{!263, !141}
!268 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !269, file: !83, line: 1136)
!269 = !DISubprogram(name: "llrintl", scope: !79, file: !79, line: 316, type: !270, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!270 = !DISubroutineType(types: !271)
!271 = !{!263, !152}
!272 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !273, file: !83, line: 1138)
!273 = !DISubprogram(name: "llround", scope: !79, file: !79, line: 322, type: !261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!274 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !275, file: !83, line: 1139)
!275 = !DISubprogram(name: "llroundf", scope: !79, file: !79, line: 322, type: !266, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!276 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !277, file: !83, line: 1140)
!277 = !DISubprogram(name: "llroundl", scope: !79, file: !79, line: 322, type: !270, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!278 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !279, file: !83, line: 1143)
!279 = !DISubprogram(name: "log1p", scope: !79, file: !79, line: 122, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!280 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !281, file: !83, line: 1144)
!281 = !DISubprogram(name: "log1pf", scope: !79, file: !79, line: 122, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!282 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !283, file: !83, line: 1145)
!283 = !DISubprogram(name: "log1pl", scope: !79, file: !79, line: 122, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!284 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !285, file: !83, line: 1147)
!285 = !DISubprogram(name: "log2", scope: !79, file: !79, line: 133, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!286 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !287, file: !83, line: 1148)
!287 = !DISubprogram(name: "log2f", scope: !79, file: !79, line: 133, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!288 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !289, file: !83, line: 1149)
!289 = !DISubprogram(name: "log2l", scope: !79, file: !79, line: 133, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!290 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !291, file: !83, line: 1151)
!291 = !DISubprogram(name: "logb", scope: !79, file: !79, line: 125, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!292 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !293, file: !83, line: 1152)
!293 = !DISubprogram(name: "logbf", scope: !79, file: !79, line: 125, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!294 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !295, file: !83, line: 1153)
!295 = !DISubprogram(name: "logbl", scope: !79, file: !79, line: 125, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!296 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !297, file: !83, line: 1155)
!297 = !DISubprogram(name: "lrint", scope: !79, file: !79, line: 314, type: !298, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!298 = !DISubroutineType(types: !299)
!299 = !{!16, !82}
!300 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !301, file: !83, line: 1156)
!301 = !DISubprogram(name: "lrintf", scope: !79, file: !79, line: 314, type: !302, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!302 = !DISubroutineType(types: !303)
!303 = !{!16, !141}
!304 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !305, file: !83, line: 1157)
!305 = !DISubprogram(name: "lrintl", scope: !79, file: !79, line: 314, type: !306, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!306 = !DISubroutineType(types: !307)
!307 = !{!16, !152}
!308 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !309, file: !83, line: 1159)
!309 = !DISubprogram(name: "lround", scope: !79, file: !79, line: 320, type: !298, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!310 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !311, file: !83, line: 1160)
!311 = !DISubprogram(name: "lroundf", scope: !79, file: !79, line: 320, type: !302, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!312 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !313, file: !83, line: 1161)
!313 = !DISubprogram(name: "lroundl", scope: !79, file: !79, line: 320, type: !306, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!314 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !315, file: !83, line: 1163)
!315 = !DISubprogram(name: "nan", scope: !79, file: !79, line: 201, type: !316, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!316 = !DISubroutineType(types: !317)
!317 = !{!82, !318}
!318 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !30, size: 64)
!319 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !320, file: !83, line: 1164)
!320 = !DISubprogram(name: "nanf", scope: !79, file: !79, line: 201, type: !321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!321 = !DISubroutineType(types: !322)
!322 = !{!141, !318}
!323 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !324, file: !83, line: 1165)
!324 = !DISubprogram(name: "nanl", scope: !79, file: !79, line: 201, type: !325, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!325 = !DISubroutineType(types: !326)
!326 = !{!152, !318}
!327 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !328, file: !83, line: 1167)
!328 = !DISubprogram(name: "nearbyint", scope: !79, file: !79, line: 294, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!329 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !330, file: !83, line: 1168)
!330 = !DISubprogram(name: "nearbyintf", scope: !79, file: !79, line: 294, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!331 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !332, file: !83, line: 1169)
!332 = !DISubprogram(name: "nearbyintl", scope: !79, file: !79, line: 294, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!333 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !334, file: !83, line: 1171)
!334 = !DISubprogram(name: "nextafter", scope: !79, file: !79, line: 259, type: !90, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!335 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !336, file: !83, line: 1172)
!336 = !DISubprogram(name: "nextafterf", scope: !79, file: !79, line: 259, type: !175, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!337 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !338, file: !83, line: 1173)
!338 = !DISubprogram(name: "nextafterl", scope: !79, file: !79, line: 259, type: !179, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!339 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !340, file: !83, line: 1175)
!340 = !DISubprogram(name: "nexttoward", scope: !79, file: !79, line: 261, type: !341, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!341 = !DISubroutineType(types: !342)
!342 = !{!82, !82, !152}
!343 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !344, file: !83, line: 1176)
!344 = !DISubprogram(name: "nexttowardf", scope: !79, file: !79, line: 261, type: !345, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!345 = !DISubroutineType(types: !346)
!346 = !{!141, !141, !152}
!347 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !348, file: !83, line: 1177)
!348 = !DISubprogram(name: "nexttowardl", scope: !79, file: !79, line: 261, type: !179, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!349 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !350, file: !83, line: 1179)
!350 = !DISubprogram(name: "remainder", scope: !79, file: !79, line: 272, type: !90, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!351 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !352, file: !83, line: 1180)
!352 = !DISubprogram(name: "remainderf", scope: !79, file: !79, line: 272, type: !175, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!353 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !354, file: !83, line: 1181)
!354 = !DISubprogram(name: "remainderl", scope: !79, file: !79, line: 272, type: !179, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!355 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !356, file: !83, line: 1183)
!356 = !DISubprogram(name: "remquo", scope: !79, file: !79, line: 307, type: !357, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!357 = !DISubroutineType(types: !358)
!358 = !{!82, !82, !82, !110}
!359 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !360, file: !83, line: 1184)
!360 = !DISubprogram(name: "remquof", scope: !79, file: !79, line: 307, type: !361, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!361 = !DISubroutineType(types: !362)
!362 = !{!141, !141, !141, !110}
!363 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !364, file: !83, line: 1185)
!364 = !DISubprogram(name: "remquol", scope: !79, file: !79, line: 307, type: !365, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!365 = !DISubroutineType(types: !366)
!366 = !{!152, !152, !152, !110}
!367 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !368, file: !83, line: 1187)
!368 = !DISubprogram(name: "rint", scope: !79, file: !79, line: 256, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!369 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !370, file: !83, line: 1188)
!370 = !DISubprogram(name: "rintf", scope: !79, file: !79, line: 256, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!371 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !372, file: !83, line: 1189)
!372 = !DISubprogram(name: "rintl", scope: !79, file: !79, line: 256, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!373 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !374, file: !83, line: 1191)
!374 = !DISubprogram(name: "round", scope: !79, file: !79, line: 298, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!375 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !376, file: !83, line: 1192)
!376 = !DISubprogram(name: "roundf", scope: !79, file: !79, line: 298, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!377 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !378, file: !83, line: 1193)
!378 = !DISubprogram(name: "roundl", scope: !79, file: !79, line: 298, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!379 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !380, file: !83, line: 1195)
!380 = !DISubprogram(name: "scalbln", scope: !79, file: !79, line: 290, type: !381, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!381 = !DISubroutineType(types: !382)
!382 = !{!82, !82, !16}
!383 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !384, file: !83, line: 1196)
!384 = !DISubprogram(name: "scalblnf", scope: !79, file: !79, line: 290, type: !385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!385 = !DISubroutineType(types: !386)
!386 = !{!141, !141, !16}
!387 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !388, file: !83, line: 1197)
!388 = !DISubprogram(name: "scalblnl", scope: !79, file: !79, line: 290, type: !389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!389 = !DISubroutineType(types: !390)
!390 = !{!152, !152, !16}
!391 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !392, file: !83, line: 1199)
!392 = !DISubprogram(name: "scalbn", scope: !79, file: !79, line: 276, type: !113, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!393 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !394, file: !83, line: 1200)
!394 = !DISubprogram(name: "scalbnf", scope: !79, file: !79, line: 276, type: !395, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!395 = !DISubroutineType(types: !396)
!396 = !{!141, !141, !13}
!397 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !398, file: !83, line: 1201)
!398 = !DISubprogram(name: "scalbnl", scope: !79, file: !79, line: 276, type: !399, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!399 = !DISubroutineType(types: !400)
!400 = !{!152, !152, !13}
!401 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !402, file: !83, line: 1203)
!402 = !DISubprogram(name: "tgamma", scope: !79, file: !79, line: 235, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!403 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !404, file: !83, line: 1204)
!404 = !DISubprogram(name: "tgammaf", scope: !79, file: !79, line: 235, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!405 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !406, file: !83, line: 1205)
!406 = !DISubprogram(name: "tgammal", scope: !79, file: !79, line: 235, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!407 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !408, file: !83, line: 1207)
!408 = !DISubprogram(name: "trunc", scope: !79, file: !79, line: 302, type: !80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!409 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !410, file: !83, line: 1208)
!410 = !DISubprogram(name: "truncf", scope: !79, file: !79, line: 302, type: !146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!411 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !412, file: !83, line: 1209)
!412 = !DISubprogram(name: "truncl", scope: !79, file: !79, line: 302, type: !150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!413 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !414, file: !417, line: 56)
!414 = !DIDerivedType(tag: DW_TAG_typedef, name: "max_align_t", file: !415, line: 24, baseType: !416)
!415 = !DIFile(filename: "llvm5/build/lib/clang/15.0.0/include/__stddef_max_align_t.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "48e8e2456f77e6cda35d245130fa7259")
!416 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !415, line: 19, size: 256, flags: DIFlagFwdDecl, identifier: "_ZTS11max_align_t")
!417 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstddef", directory: "")
!418 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !419, file: !428, line: 75)
!419 = !DISubprogram(name: "memchr", scope: !420, file: !420, line: 90, type: !421, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!420 = !DIFile(filename: "/usr/include/string.h", directory: "", checksumkind: CSK_MD5, checksum: "1029a2d94b0e7b73f8dbf87ca20ab7bc")
!421 = !DISubroutineType(types: !422)
!422 = !{!423, !424, !13, !426}
!423 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 64)
!424 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !425, size: 64)
!425 = !DIDerivedType(tag: DW_TAG_const_type, baseType: null)
!426 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", file: !427, line: 46, baseType: !20)
!427 = !DIFile(filename: "llvm5/build/lib/clang/15.0.0/include/stddef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "b76978376d35d5cd171876ac58ac1256")
!428 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstring", directory: "")
!429 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !430, file: !428, line: 76)
!430 = !DISubprogram(name: "memcmp", scope: !420, file: !420, line: 63, type: !431, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!431 = !DISubroutineType(types: !432)
!432 = !{!13, !424, !424, !426}
!433 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !434, file: !428, line: 77)
!434 = !DISubprogram(name: "memcpy", scope: !420, file: !420, line: 42, type: !435, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!435 = !DISubroutineType(types: !436)
!436 = !{!423, !437, !438, !426}
!437 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !423)
!438 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !424)
!439 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !440, file: !428, line: 78)
!440 = !DISubprogram(name: "memmove", scope: !420, file: !420, line: 46, type: !441, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!441 = !DISubroutineType(types: !442)
!442 = !{!423, !423, !424, !426}
!443 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !444, file: !428, line: 79)
!444 = !DISubprogram(name: "memset", scope: !420, file: !420, line: 60, type: !445, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!445 = !DISubroutineType(types: !446)
!446 = !{!423, !423, !13, !426}
!447 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !448, file: !428, line: 80)
!448 = !DISubprogram(name: "strcat", scope: !420, file: !420, line: 129, type: !449, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!449 = !DISubroutineType(types: !450)
!450 = !{!451, !452, !453}
!451 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !31, size: 64)
!452 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !451)
!453 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !318)
!454 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !455, file: !428, line: 81)
!455 = !DISubprogram(name: "strcmp", scope: !420, file: !420, line: 136, type: !456, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!456 = !DISubroutineType(types: !457)
!457 = !{!13, !318, !318}
!458 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !459, file: !428, line: 82)
!459 = !DISubprogram(name: "strcoll", scope: !420, file: !420, line: 143, type: !456, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!460 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !461, file: !428, line: 83)
!461 = !DISubprogram(name: "strcpy", scope: !420, file: !420, line: 121, type: !449, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!462 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !463, file: !428, line: 84)
!463 = !DISubprogram(name: "strcspn", scope: !420, file: !420, line: 272, type: !464, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!464 = !DISubroutineType(types: !465)
!465 = !{!426, !318, !318}
!466 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !467, file: !428, line: 85)
!467 = !DISubprogram(name: "strerror", scope: !420, file: !420, line: 396, type: !468, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!468 = !DISubroutineType(types: !469)
!469 = !{!451, !13}
!470 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !471, file: !428, line: 86)
!471 = !DISubprogram(name: "strlen", scope: !420, file: !420, line: 384, type: !472, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!472 = !DISubroutineType(types: !473)
!473 = !{!426, !318}
!474 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !475, file: !428, line: 87)
!475 = !DISubprogram(name: "strncat", scope: !420, file: !420, line: 132, type: !476, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!476 = !DISubroutineType(types: !477)
!477 = !{!451, !452, !453, !426}
!478 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !479, file: !428, line: 88)
!479 = !DISubprogram(name: "strncmp", scope: !420, file: !420, line: 139, type: !480, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!480 = !DISubroutineType(types: !481)
!481 = !{!13, !318, !318, !426}
!482 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !483, file: !428, line: 89)
!483 = !DISubprogram(name: "strncpy", scope: !420, file: !420, line: 124, type: !476, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!484 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !485, file: !428, line: 90)
!485 = !DISubprogram(name: "strspn", scope: !420, file: !420, line: 276, type: !464, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!486 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !487, file: !428, line: 91)
!487 = !DISubprogram(name: "strtok", scope: !420, file: !420, line: 335, type: !449, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!488 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !489, file: !428, line: 92)
!489 = !DISubprogram(name: "strxfrm", scope: !420, file: !420, line: 146, type: !490, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!490 = !DISubroutineType(types: !491)
!491 = !{!426, !452, !453, !426}
!492 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !493, file: !428, line: 93)
!493 = !DISubprogram(name: "strchr", scope: !420, file: !420, line: 225, type: !494, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!494 = !DISubroutineType(types: !495)
!495 = !{!451, !318, !13}
!496 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !497, file: !428, line: 94)
!497 = !DISubprogram(name: "strpbrk", scope: !420, file: !420, line: 302, type: !498, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!498 = !DISubroutineType(types: !499)
!499 = !{!451, !318, !318}
!500 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !501, file: !428, line: 95)
!501 = !DISubprogram(name: "strrchr", scope: !420, file: !420, line: 252, type: !494, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!502 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !503, file: !428, line: 96)
!503 = !DISubprogram(name: "strstr", scope: !420, file: !420, line: 329, type: !498, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!504 = !DIImportedEntity(tag: DW_TAG_imported_module, scope: !505, entity: !506, file: !507, line: 58)
!505 = !DINamespace(name: "__gnu_debug", scope: null)
!506 = !DINamespace(name: "__debug", scope: !71)
!507 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/debug/debug.h", directory: "", checksumkind: CSK_MD5, checksum: "0d648599b52b1d377b1fee4a0a4b2b91")
!508 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !509, file: !511, line: 127)
!509 = !DIDerivedType(tag: DW_TAG_typedef, name: "div_t", file: !73, line: 62, baseType: !510)
!510 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !73, line: 58, size: 64, flags: DIFlagFwdDecl, identifier: "_ZTS5div_t")
!511 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdlib", directory: "")
!512 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !513, file: !511, line: 128)
!513 = !DIDerivedType(tag: DW_TAG_typedef, name: "ldiv_t", file: !73, line: 70, baseType: !514)
!514 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !73, line: 66, size: 128, flags: DIFlagTypePassByValue, elements: !515, identifier: "_ZTS6ldiv_t")
!515 = !{!516, !517}
!516 = !DIDerivedType(tag: DW_TAG_member, name: "quot", scope: !514, file: !73, line: 68, baseType: !16, size: 64)
!517 = !DIDerivedType(tag: DW_TAG_member, name: "rem", scope: !514, file: !73, line: 69, baseType: !16, size: 64, offset: 64)
!518 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !519, file: !511, line: 130)
!519 = !DISubprogram(name: "abort", scope: !73, file: !73, line: 588, type: !520, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!520 = !DISubroutineType(types: !521)
!521 = !{null}
!522 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !523, file: !511, line: 134)
!523 = !DISubprogram(name: "atexit", scope: !73, file: !73, line: 592, type: !524, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!524 = !DISubroutineType(types: !525)
!525 = !{!13, !526}
!526 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !520, size: 64)
!527 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !528, file: !511, line: 137)
!528 = !DISubprogram(name: "at_quick_exit", scope: !73, file: !73, line: 597, type: !524, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!529 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !530, file: !511, line: 140)
!530 = !DISubprogram(name: "atof", scope: !531, file: !531, line: 25, type: !316, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!531 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h", directory: "", checksumkind: CSK_MD5, checksum: "ce60958b260b171e83db3307f1d644f0")
!532 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !533, file: !511, line: 141)
!533 = !DISubprogram(name: "atoi", scope: !73, file: !73, line: 361, type: !534, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!534 = !DISubroutineType(types: !535)
!535 = !{!13, !318}
!536 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !537, file: !511, line: 142)
!537 = !DISubprogram(name: "atol", scope: !73, file: !73, line: 366, type: !538, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!538 = !DISubroutineType(types: !539)
!539 = !{!16, !318}
!540 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !541, file: !511, line: 143)
!541 = !DISubprogram(name: "bsearch", scope: !542, file: !542, line: 20, type: !543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!542 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h", directory: "", checksumkind: CSK_MD5, checksum: "1a798a38b25adee7bb680abce9ef568a")
!543 = !DISubroutineType(types: !544)
!544 = !{!423, !424, !424, !426, !426, !545}
!545 = !DIDerivedType(tag: DW_TAG_typedef, name: "__compar_fn_t", file: !73, line: 805, baseType: !546)
!546 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !547, size: 64)
!547 = !DISubroutineType(types: !548)
!548 = !{!13, !424, !424}
!549 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !550, file: !511, line: 144)
!550 = !DISubprogram(name: "calloc", scope: !73, file: !73, line: 541, type: !551, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!551 = !DISubroutineType(types: !552)
!552 = !{!423, !426, !426}
!553 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !554, file: !511, line: 145)
!554 = !DISubprogram(name: "div", scope: !73, file: !73, line: 849, type: !555, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!555 = !DISubroutineType(types: !556)
!556 = !{!509, !13, !13}
!557 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !558, file: !511, line: 146)
!558 = !DISubprogram(name: "exit", scope: !73, file: !73, line: 614, type: !559, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!559 = !DISubroutineType(types: !560)
!560 = !{null, !13}
!561 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !562, file: !511, line: 147)
!562 = !DISubprogram(name: "free", scope: !73, file: !73, line: 563, type: !563, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!563 = !DISubroutineType(types: !564)
!564 = !{null, !423}
!565 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !566, file: !511, line: 148)
!566 = !DISubprogram(name: "getenv", scope: !73, file: !73, line: 631, type: !567, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!567 = !DISubroutineType(types: !568)
!568 = !{!451, !318}
!569 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !570, file: !511, line: 149)
!570 = !DISubprogram(name: "labs", scope: !73, file: !73, line: 838, type: !571, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!571 = !DISubroutineType(types: !572)
!572 = !{!16, !16}
!573 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !574, file: !511, line: 150)
!574 = !DISubprogram(name: "ldiv", scope: !73, file: !73, line: 851, type: !575, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!575 = !DISubroutineType(types: !576)
!576 = !{!513, !16, !16}
!577 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !578, file: !511, line: 151)
!578 = !DISubprogram(name: "malloc", scope: !73, file: !73, line: 539, type: !579, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!579 = !DISubroutineType(types: !580)
!580 = !{!423, !426}
!581 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !582, file: !511, line: 153)
!582 = !DISubprogram(name: "mblen", scope: !73, file: !73, line: 919, type: !583, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!583 = !DISubroutineType(types: !584)
!584 = !{!13, !318, !426}
!585 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !586, file: !511, line: 154)
!586 = !DISubprogram(name: "mbstowcs", scope: !73, file: !73, line: 930, type: !587, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!587 = !DISubroutineType(types: !588)
!588 = !{!426, !589, !453, !426}
!589 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !590)
!590 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !591, size: 64)
!591 = !DIBasicType(name: "wchar_t", size: 32, encoding: DW_ATE_signed)
!592 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !593, file: !511, line: 155)
!593 = !DISubprogram(name: "mbtowc", scope: !73, file: !73, line: 922, type: !594, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!594 = !DISubroutineType(types: !595)
!595 = !{!13, !589, !453, !426}
!596 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !597, file: !511, line: 157)
!597 = !DISubprogram(name: "qsort", scope: !73, file: !73, line: 827, type: !598, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!598 = !DISubroutineType(types: !599)
!599 = !{null, !423, !426, !426, !545}
!600 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !601, file: !511, line: 160)
!601 = !DISubprogram(name: "quick_exit", scope: !73, file: !73, line: 620, type: !559, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!602 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !603, file: !511, line: 163)
!603 = !DISubprogram(name: "rand", scope: !73, file: !73, line: 453, type: !604, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!604 = !DISubroutineType(types: !605)
!605 = !{!13}
!606 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !607, file: !511, line: 164)
!607 = !DISubprogram(name: "realloc", scope: !73, file: !73, line: 549, type: !608, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!608 = !DISubroutineType(types: !609)
!609 = !{!423, !423, !426}
!610 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !611, file: !511, line: 165)
!611 = !DISubprogram(name: "srand", scope: !73, file: !73, line: 455, type: !612, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!612 = !DISubroutineType(types: !613)
!613 = !{null, !614}
!614 = !DIBasicType(name: "unsigned int", size: 32, encoding: DW_ATE_unsigned)
!615 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !616, file: !511, line: 166)
!616 = !DISubprogram(name: "strtod", scope: !73, file: !73, line: 117, type: !617, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!617 = !DISubroutineType(types: !618)
!618 = !{!82, !453, !619}
!619 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !620)
!620 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !451, size: 64)
!621 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !622, file: !511, line: 167)
!622 = !DISubprogram(name: "strtol", scope: !73, file: !73, line: 176, type: !623, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!623 = !DISubroutineType(types: !624)
!624 = !{!16, !453, !619, !13}
!625 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !626, file: !511, line: 168)
!626 = !DISubprogram(name: "strtoul", scope: !73, file: !73, line: 180, type: !627, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!627 = !DISubroutineType(types: !628)
!628 = !{!20, !453, !619, !13}
!629 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !630, file: !511, line: 169)
!630 = !DISubprogram(name: "system", scope: !73, file: !73, line: 781, type: !534, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!631 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !632, file: !511, line: 171)
!632 = !DISubprogram(name: "wcstombs", scope: !73, file: !73, line: 933, type: !633, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!633 = !DISubroutineType(types: !634)
!634 = !{!426, !452, !635, !426}
!635 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !636)
!636 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !637, size: 64)
!637 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !591)
!638 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !639, file: !511, line: 172)
!639 = !DISubprogram(name: "wctomb", scope: !73, file: !73, line: 926, type: !640, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!640 = !DISubroutineType(types: !641)
!641 = !{!13, !451, !591}
!642 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !644, file: !511, line: 200)
!643 = !DINamespace(name: "__gnu_cxx", scope: null)
!644 = !DIDerivedType(tag: DW_TAG_typedef, name: "lldiv_t", file: !73, line: 80, baseType: !645)
!645 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !73, line: 76, size: 128, flags: DIFlagTypePassByValue, elements: !646, identifier: "_ZTS7lldiv_t")
!646 = !{!647, !648}
!647 = !DIDerivedType(tag: DW_TAG_member, name: "quot", scope: !645, file: !73, line: 78, baseType: !263, size: 64)
!648 = !DIDerivedType(tag: DW_TAG_member, name: "rem", scope: !645, file: !73, line: 79, baseType: !263, size: 64, offset: 64)
!649 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !650, file: !511, line: 206)
!650 = !DISubprogram(name: "_Exit", scope: !73, file: !73, line: 626, type: !559, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!651 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !652, file: !511, line: 210)
!652 = !DISubprogram(name: "llabs", scope: !73, file: !73, line: 841, type: !653, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!653 = !DISubroutineType(types: !654)
!654 = !{!263, !263}
!655 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !656, file: !511, line: 216)
!656 = !DISubprogram(name: "lldiv", scope: !73, file: !73, line: 855, type: !657, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!657 = !DISubroutineType(types: !658)
!658 = !{!644, !263, !263}
!659 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !660, file: !511, line: 227)
!660 = !DISubprogram(name: "atoll", scope: !73, file: !73, line: 373, type: !661, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!661 = !DISubroutineType(types: !662)
!662 = !{!263, !318}
!663 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !664, file: !511, line: 228)
!664 = !DISubprogram(name: "strtoll", scope: !73, file: !73, line: 200, type: !665, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!665 = !DISubroutineType(types: !666)
!666 = !{!263, !453, !619, !13}
!667 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !668, file: !511, line: 229)
!668 = !DISubprogram(name: "strtoull", scope: !73, file: !73, line: 205, type: !669, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!669 = !DISubroutineType(types: !670)
!670 = !{!671, !453, !619, !13}
!671 = !DIBasicType(name: "unsigned long long", size: 64, encoding: DW_ATE_unsigned)
!672 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !673, file: !511, line: 231)
!673 = !DISubprogram(name: "strtof", scope: !73, file: !73, line: 123, type: !674, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!674 = !DISubroutineType(types: !675)
!675 = !{!141, !453, !619}
!676 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !677, file: !511, line: 232)
!677 = !DISubprogram(name: "strtold", scope: !73, file: !73, line: 126, type: !678, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!678 = !DISubroutineType(types: !679)
!679 = !{!152, !453, !619}
!680 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !644, file: !511, line: 240)
!681 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !650, file: !511, line: 242)
!682 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !652, file: !511, line: 244)
!683 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !684, file: !511, line: 245)
!684 = !DISubprogram(name: "div", linkageName: "_ZN9__gnu_cxx3divExx", scope: !643, file: !511, line: 213, type: !657, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!685 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !656, file: !511, line: 246)
!686 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !660, file: !511, line: 248)
!687 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !673, file: !511, line: 249)
!688 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !664, file: !511, line: 250)
!689 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !668, file: !511, line: 251)
!690 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !677, file: !511, line: 252)
!691 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !692, file: !693, line: 57)
!692 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "exception_ptr", scope: !694, file: !693, line: 79, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSNSt15__exception_ptr13exception_ptrE")
!693 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/exception_ptr.h", directory: "", checksumkind: CSK_MD5, checksum: "25d44782b686509a9fc5c8aaa8066643")
!694 = !DINamespace(name: "__exception_ptr", scope: !71)
!695 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !694, entity: !696, file: !693, line: 73)
!696 = !DISubprogram(name: "rethrow_exception", linkageName: "_ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE", scope: !71, file: !693, line: 69, type: !697, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!697 = !DISubroutineType(types: !698)
!698 = !{null, !692}
!699 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !700, file: !715, line: 64)
!700 = !DIDerivedType(tag: DW_TAG_typedef, name: "mbstate_t", file: !701, line: 6, baseType: !702)
!701 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/mbstate_t.h", directory: "", checksumkind: CSK_MD5, checksum: "ba8742313715e20e434cf6ccb2db98e3")
!702 = !DIDerivedType(tag: DW_TAG_typedef, name: "__mbstate_t", file: !703, line: 21, baseType: !704)
!703 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h", directory: "", checksumkind: CSK_MD5, checksum: "82911a3e689448e3691ded3e0b471a55")
!704 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !703, line: 13, size: 64, flags: DIFlagTypePassByValue, elements: !705, identifier: "_ZTS11__mbstate_t")
!705 = !{!706, !707}
!706 = !DIDerivedType(tag: DW_TAG_member, name: "__count", scope: !704, file: !703, line: 15, baseType: !13, size: 32)
!707 = !DIDerivedType(tag: DW_TAG_member, name: "__value", scope: !704, file: !703, line: 20, baseType: !708, size: 32, offset: 32)
!708 = distinct !DICompositeType(tag: DW_TAG_union_type, scope: !704, file: !703, line: 16, size: 32, flags: DIFlagTypePassByValue, elements: !709, identifier: "_ZTSN11__mbstate_tUt_E")
!709 = !{!710, !711}
!710 = !DIDerivedType(tag: DW_TAG_member, name: "__wch", scope: !708, file: !703, line: 18, baseType: !614, size: 32)
!711 = !DIDerivedType(tag: DW_TAG_member, name: "__wchb", scope: !708, file: !703, line: 19, baseType: !712, size: 32)
!712 = !DICompositeType(tag: DW_TAG_array_type, baseType: !31, size: 32, elements: !713)
!713 = !{!714}
!714 = !DISubrange(count: 4)
!715 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cwchar", directory: "")
!716 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !717, file: !715, line: 139)
!717 = !DIDerivedType(tag: DW_TAG_typedef, name: "wint_t", file: !718, line: 20, baseType: !614)
!718 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/wint_t.h", directory: "", checksumkind: CSK_MD5, checksum: "aa31b53ef28dc23152ceb41e2763ded3")
!719 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !720, file: !715, line: 141)
!720 = !DISubprogram(name: "btowc", scope: !721, file: !721, line: 318, type: !722, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!721 = !DIFile(filename: "/usr/include/wchar.h", directory: "", checksumkind: CSK_MD5, checksum: "5c0512b032e303d7adfb2a47454ecb1c")
!722 = !DISubroutineType(types: !723)
!723 = !{!717, !13}
!724 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !725, file: !715, line: 142)
!725 = !DISubprogram(name: "fgetwc", scope: !721, file: !721, line: 727, type: !726, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!726 = !DISubroutineType(types: !727)
!727 = !{!717, !728}
!728 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !729, size: 64)
!729 = !DIDerivedType(tag: DW_TAG_typedef, name: "__FILE", file: !730, line: 5, baseType: !731)
!730 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h", directory: "", checksumkind: CSK_MD5, checksum: "72a8fe90981f484acae7c6f3dfc5c2b7")
!731 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_IO_FILE", file: !732, line: 245, size: 1728, flags: DIFlagTypePassByValue, elements: !733, identifier: "_ZTS8_IO_FILE")
!732 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/libio.h", directory: "", checksumkind: CSK_MD5, checksum: "e2b53e448ab24b9cd2ba8684267b8131")
!733 = !{!734, !735, !736, !737, !738, !739, !740, !741, !742, !743, !744, !745, !746, !749, !751, !752, !753, !755, !757, !758, !762, !765, !767, !768, !769, !770, !771, !772, !773}
!734 = !DIDerivedType(tag: DW_TAG_member, name: "_flags", scope: !731, file: !732, line: 246, baseType: !13, size: 32)
!735 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_ptr", scope: !731, file: !732, line: 251, baseType: !451, size: 64, offset: 64)
!736 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_end", scope: !731, file: !732, line: 252, baseType: !451, size: 64, offset: 128)
!737 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_base", scope: !731, file: !732, line: 253, baseType: !451, size: 64, offset: 192)
!738 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_base", scope: !731, file: !732, line: 254, baseType: !451, size: 64, offset: 256)
!739 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_ptr", scope: !731, file: !732, line: 255, baseType: !451, size: 64, offset: 320)
!740 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_end", scope: !731, file: !732, line: 256, baseType: !451, size: 64, offset: 384)
!741 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_buf_base", scope: !731, file: !732, line: 257, baseType: !451, size: 64, offset: 448)
!742 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_buf_end", scope: !731, file: !732, line: 258, baseType: !451, size: 64, offset: 512)
!743 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_save_base", scope: !731, file: !732, line: 260, baseType: !451, size: 64, offset: 576)
!744 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_backup_base", scope: !731, file: !732, line: 261, baseType: !451, size: 64, offset: 640)
!745 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_save_end", scope: !731, file: !732, line: 262, baseType: !451, size: 64, offset: 704)
!746 = !DIDerivedType(tag: DW_TAG_member, name: "_markers", scope: !731, file: !732, line: 264, baseType: !747, size: 64, offset: 768)
!747 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !748, size: 64)
!748 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_IO_marker", file: !732, line: 160, size: 192, flags: DIFlagFwdDecl, identifier: "_ZTS10_IO_marker")
!749 = !DIDerivedType(tag: DW_TAG_member, name: "_chain", scope: !731, file: !732, line: 266, baseType: !750, size: 64, offset: 832)
!750 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !731, size: 64)
!751 = !DIDerivedType(tag: DW_TAG_member, name: "_fileno", scope: !731, file: !732, line: 268, baseType: !13, size: 32, offset: 896)
!752 = !DIDerivedType(tag: DW_TAG_member, name: "_flags2", scope: !731, file: !732, line: 272, baseType: !13, size: 32, offset: 928)
!753 = !DIDerivedType(tag: DW_TAG_member, name: "_old_offset", scope: !731, file: !732, line: 274, baseType: !754, size: 64, offset: 960)
!754 = !DIDerivedType(tag: DW_TAG_typedef, name: "__off_t", file: !6, line: 140, baseType: !16)
!755 = !DIDerivedType(tag: DW_TAG_member, name: "_cur_column", scope: !731, file: !732, line: 278, baseType: !756, size: 16, offset: 1024)
!756 = !DIBasicType(name: "unsigned short", size: 16, encoding: DW_ATE_unsigned)
!757 = !DIDerivedType(tag: DW_TAG_member, name: "_vtable_offset", scope: !731, file: !732, line: 279, baseType: !7, size: 8, offset: 1040)
!758 = !DIDerivedType(tag: DW_TAG_member, name: "_shortbuf", scope: !731, file: !732, line: 280, baseType: !759, size: 8, offset: 1048)
!759 = !DICompositeType(tag: DW_TAG_array_type, baseType: !31, size: 8, elements: !760)
!760 = !{!761}
!761 = !DISubrange(count: 1)
!762 = !DIDerivedType(tag: DW_TAG_member, name: "_lock", scope: !731, file: !732, line: 284, baseType: !763, size: 64, offset: 1088)
!763 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !764, size: 64)
!764 = !DIDerivedType(tag: DW_TAG_typedef, name: "_IO_lock_t", file: !732, line: 154, baseType: null)
!765 = !DIDerivedType(tag: DW_TAG_member, name: "_offset", scope: !731, file: !732, line: 293, baseType: !766, size: 64, offset: 1152)
!766 = !DIDerivedType(tag: DW_TAG_typedef, name: "__off64_t", file: !6, line: 141, baseType: !16)
!767 = !DIDerivedType(tag: DW_TAG_member, name: "__pad1", scope: !731, file: !732, line: 301, baseType: !423, size: 64, offset: 1216)
!768 = !DIDerivedType(tag: DW_TAG_member, name: "__pad2", scope: !731, file: !732, line: 302, baseType: !423, size: 64, offset: 1280)
!769 = !DIDerivedType(tag: DW_TAG_member, name: "__pad3", scope: !731, file: !732, line: 303, baseType: !423, size: 64, offset: 1344)
!770 = !DIDerivedType(tag: DW_TAG_member, name: "__pad4", scope: !731, file: !732, line: 304, baseType: !423, size: 64, offset: 1408)
!771 = !DIDerivedType(tag: DW_TAG_member, name: "__pad5", scope: !731, file: !732, line: 306, baseType: !426, size: 64, offset: 1472)
!772 = !DIDerivedType(tag: DW_TAG_member, name: "_mode", scope: !731, file: !732, line: 307, baseType: !13, size: 32, offset: 1536)
!773 = !DIDerivedType(tag: DW_TAG_member, name: "_unused2", scope: !731, file: !732, line: 309, baseType: !774, size: 160, offset: 1568)
!774 = !DICompositeType(tag: DW_TAG_array_type, baseType: !31, size: 160, elements: !775)
!775 = !{!776}
!776 = !DISubrange(count: 20)
!777 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !778, file: !715, line: 143)
!778 = !DISubprogram(name: "fgetws", scope: !721, file: !721, line: 756, type: !779, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!779 = !DISubroutineType(types: !780)
!780 = !{!590, !589, !13, !781}
!781 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !728)
!782 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !783, file: !715, line: 144)
!783 = !DISubprogram(name: "fputwc", scope: !721, file: !721, line: 741, type: !784, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!784 = !DISubroutineType(types: !785)
!785 = !{!717, !591, !728}
!786 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !787, file: !715, line: 145)
!787 = !DISubprogram(name: "fputws", scope: !721, file: !721, line: 763, type: !788, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!788 = !DISubroutineType(types: !789)
!789 = !{!13, !635, !781}
!790 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !791, file: !715, line: 146)
!791 = !DISubprogram(name: "fwide", scope: !721, file: !721, line: 573, type: !792, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!792 = !DISubroutineType(types: !793)
!793 = !{!13, !728, !13}
!794 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !795, file: !715, line: 147)
!795 = !DISubprogram(name: "fwprintf", scope: !721, file: !721, line: 580, type: !796, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!796 = !DISubroutineType(types: !797)
!797 = !{!13, !781, !635, null}
!798 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !799, file: !715, line: 148)
!799 = !DISubprogram(name: "fwscanf", scope: !721, file: !721, line: 621, type: !796, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!800 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !801, file: !715, line: 149)
!801 = !DISubprogram(name: "getwc", scope: !721, file: !721, line: 728, type: !726, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!802 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !803, file: !715, line: 150)
!803 = !DISubprogram(name: "getwchar", scope: !721, file: !721, line: 734, type: !804, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!804 = !DISubroutineType(types: !805)
!805 = !{!717}
!806 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !807, file: !715, line: 151)
!807 = !DISubprogram(name: "mbrlen", scope: !721, file: !721, line: 329, type: !808, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!808 = !DISubroutineType(types: !809)
!809 = !{!426, !453, !426, !810}
!810 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !811)
!811 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !700, size: 64)
!812 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !813, file: !715, line: 152)
!813 = !DISubprogram(name: "mbrtowc", scope: !721, file: !721, line: 296, type: !814, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!814 = !DISubroutineType(types: !815)
!815 = !{!426, !589, !453, !426, !810}
!816 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !817, file: !715, line: 153)
!817 = !DISubprogram(name: "mbsinit", scope: !721, file: !721, line: 292, type: !818, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!818 = !DISubroutineType(types: !819)
!819 = !{!13, !820}
!820 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !821, size: 64)
!821 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !700)
!822 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !823, file: !715, line: 154)
!823 = !DISubprogram(name: "mbsrtowcs", scope: !721, file: !721, line: 337, type: !824, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!824 = !DISubroutineType(types: !825)
!825 = !{!426, !589, !826, !426, !810}
!826 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !827)
!827 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !318, size: 64)
!828 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !829, file: !715, line: 155)
!829 = !DISubprogram(name: "putwc", scope: !721, file: !721, line: 742, type: !784, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!830 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !831, file: !715, line: 156)
!831 = !DISubprogram(name: "putwchar", scope: !721, file: !721, line: 748, type: !832, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!832 = !DISubroutineType(types: !833)
!833 = !{!717, !591}
!834 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !835, file: !715, line: 158)
!835 = !DISubprogram(name: "swprintf", scope: !721, file: !721, line: 590, type: !836, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!836 = !DISubroutineType(types: !837)
!837 = !{!13, !589, !426, !635, null}
!838 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !839, file: !715, line: 160)
!839 = !DISubprogram(name: "swscanf", scope: !721, file: !721, line: 631, type: !840, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!840 = !DISubroutineType(types: !841)
!841 = !{!13, !635, !635, null}
!842 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !843, file: !715, line: 161)
!843 = !DISubprogram(name: "ungetwc", scope: !721, file: !721, line: 771, type: !844, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!844 = !DISubroutineType(types: !845)
!845 = !{!717, !717, !728}
!846 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !847, file: !715, line: 162)
!847 = !DISubprogram(name: "vfwprintf", scope: !721, file: !721, line: 598, type: !848, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!848 = !DISubroutineType(types: !849)
!849 = !{!13, !781, !635, !850}
!850 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !851, size: 64)
!851 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__va_list_tag", size: 192, flags: DIFlagTypePassByValue, elements: !852, identifier: "_ZTS13__va_list_tag")
!852 = !{!853, !855, !856, !857}
!853 = !DIDerivedType(tag: DW_TAG_member, name: "gp_offset", scope: !851, file: !854, baseType: !614, size: 32)
!854 = !DIFile(filename: "llvm34/lib/Support/DataExtractor.cpp", directory: "/fast/fs")
!855 = !DIDerivedType(tag: DW_TAG_member, name: "fp_offset", scope: !851, file: !854, baseType: !614, size: 32, offset: 32)
!856 = !DIDerivedType(tag: DW_TAG_member, name: "overflow_arg_area", scope: !851, file: !854, baseType: !423, size: 64, offset: 64)
!857 = !DIDerivedType(tag: DW_TAG_member, name: "reg_save_area", scope: !851, file: !854, baseType: !423, size: 64, offset: 128)
!858 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !859, file: !715, line: 164)
!859 = !DISubprogram(name: "vfwscanf", scope: !721, file: !721, line: 673, type: !848, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!860 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !861, file: !715, line: 167)
!861 = !DISubprogram(name: "vswprintf", scope: !721, file: !721, line: 611, type: !862, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!862 = !DISubroutineType(types: !863)
!863 = !{!13, !589, !426, !635, !850}
!864 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !865, file: !715, line: 170)
!865 = !DISubprogram(name: "vswscanf", scope: !721, file: !721, line: 685, type: !866, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!866 = !DISubroutineType(types: !867)
!867 = !{!13, !635, !635, !850}
!868 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !869, file: !715, line: 172)
!869 = !DISubprogram(name: "vwprintf", scope: !721, file: !721, line: 606, type: !870, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!870 = !DISubroutineType(types: !871)
!871 = !{!13, !635, !850}
!872 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !873, file: !715, line: 174)
!873 = !DISubprogram(name: "vwscanf", scope: !721, file: !721, line: 681, type: !870, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!874 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !875, file: !715, line: 176)
!875 = !DISubprogram(name: "wcrtomb", scope: !721, file: !721, line: 301, type: !876, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!876 = !DISubroutineType(types: !877)
!877 = !{!426, !452, !591, !810}
!878 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !879, file: !715, line: 177)
!879 = !DISubprogram(name: "wcscat", scope: !721, file: !721, line: 97, type: !880, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!880 = !DISubroutineType(types: !881)
!881 = !{!590, !589, !635}
!882 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !883, file: !715, line: 178)
!883 = !DISubprogram(name: "wcscmp", scope: !721, file: !721, line: 106, type: !884, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!884 = !DISubroutineType(types: !885)
!885 = !{!13, !636, !636}
!886 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !887, file: !715, line: 179)
!887 = !DISubprogram(name: "wcscoll", scope: !721, file: !721, line: 131, type: !884, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!888 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !889, file: !715, line: 180)
!889 = !DISubprogram(name: "wcscpy", scope: !721, file: !721, line: 87, type: !880, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!890 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !891, file: !715, line: 181)
!891 = !DISubprogram(name: "wcscspn", scope: !721, file: !721, line: 187, type: !892, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!892 = !DISubroutineType(types: !893)
!893 = !{!426, !636, !636}
!894 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !895, file: !715, line: 182)
!895 = !DISubprogram(name: "wcsftime", scope: !721, file: !721, line: 835, type: !896, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!896 = !DISubroutineType(types: !897)
!897 = !{!426, !589, !426, !635, !898}
!898 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !899)
!899 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !900, size: 64)
!900 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !901)
!901 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "tm", file: !721, line: 83, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTS2tm")
!902 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !903, file: !715, line: 183)
!903 = !DISubprogram(name: "wcslen", scope: !721, file: !721, line: 222, type: !904, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!904 = !DISubroutineType(types: !905)
!905 = !{!426, !636}
!906 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !907, file: !715, line: 184)
!907 = !DISubprogram(name: "wcsncat", scope: !721, file: !721, line: 101, type: !908, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!908 = !DISubroutineType(types: !909)
!909 = !{!590, !589, !635, !426}
!910 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !911, file: !715, line: 185)
!911 = !DISubprogram(name: "wcsncmp", scope: !721, file: !721, line: 109, type: !912, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!912 = !DISubroutineType(types: !913)
!913 = !{!13, !636, !636, !426}
!914 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !915, file: !715, line: 186)
!915 = !DISubprogram(name: "wcsncpy", scope: !721, file: !721, line: 92, type: !908, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!916 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !917, file: !715, line: 187)
!917 = !DISubprogram(name: "wcsrtombs", scope: !721, file: !721, line: 343, type: !918, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!918 = !DISubroutineType(types: !919)
!919 = !{!426, !452, !920, !426, !810}
!920 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !921)
!921 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !636, size: 64)
!922 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !923, file: !715, line: 188)
!923 = !DISubprogram(name: "wcsspn", scope: !721, file: !721, line: 191, type: !892, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!924 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !925, file: !715, line: 189)
!925 = !DISubprogram(name: "wcstod", scope: !721, file: !721, line: 377, type: !926, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!926 = !DISubroutineType(types: !927)
!927 = !{!82, !635, !928}
!928 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !929)
!929 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !590, size: 64)
!930 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !931, file: !715, line: 191)
!931 = !DISubprogram(name: "wcstof", scope: !721, file: !721, line: 382, type: !932, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!932 = !DISubroutineType(types: !933)
!933 = !{!141, !635, !928}
!934 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !935, file: !715, line: 193)
!935 = !DISubprogram(name: "wcstok", scope: !721, file: !721, line: 217, type: !936, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!936 = !DISubroutineType(types: !937)
!937 = !{!590, !589, !635, !928}
!938 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !939, file: !715, line: 194)
!939 = !DISubprogram(name: "wcstol", scope: !721, file: !721, line: 428, type: !940, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!940 = !DISubroutineType(types: !941)
!941 = !{!16, !635, !928, !13}
!942 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !943, file: !715, line: 195)
!943 = !DISubprogram(name: "wcstoul", scope: !721, file: !721, line: 433, type: !944, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!944 = !DISubroutineType(types: !945)
!945 = !{!20, !635, !928, !13}
!946 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !947, file: !715, line: 196)
!947 = !DISubprogram(name: "wcsxfrm", scope: !721, file: !721, line: 135, type: !948, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!948 = !DISubroutineType(types: !949)
!949 = !{!426, !589, !635, !426}
!950 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !951, file: !715, line: 197)
!951 = !DISubprogram(name: "wctob", scope: !721, file: !721, line: 324, type: !952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!952 = !DISubroutineType(types: !953)
!953 = !{!13, !717}
!954 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !955, file: !715, line: 198)
!955 = !DISubprogram(name: "wmemcmp", scope: !721, file: !721, line: 258, type: !912, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!956 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !957, file: !715, line: 199)
!957 = !DISubprogram(name: "wmemcpy", scope: !721, file: !721, line: 262, type: !908, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!958 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !959, file: !715, line: 200)
!959 = !DISubprogram(name: "wmemmove", scope: !721, file: !721, line: 267, type: !960, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!960 = !DISubroutineType(types: !961)
!961 = !{!590, !590, !636, !426}
!962 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !963, file: !715, line: 201)
!963 = !DISubprogram(name: "wmemset", scope: !721, file: !721, line: 271, type: !964, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!964 = !DISubroutineType(types: !965)
!965 = !{!590, !590, !591, !426}
!966 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !967, file: !715, line: 202)
!967 = !DISubprogram(name: "wprintf", scope: !721, file: !721, line: 587, type: !968, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!968 = !DISubroutineType(types: !969)
!969 = !{!13, !635, null}
!970 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !971, file: !715, line: 203)
!971 = !DISubprogram(name: "wscanf", scope: !721, file: !721, line: 628, type: !968, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!972 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !973, file: !715, line: 204)
!973 = !DISubprogram(name: "wcschr", scope: !721, file: !721, line: 164, type: !974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!974 = !DISubroutineType(types: !975)
!975 = !{!590, !636, !591}
!976 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !977, file: !715, line: 205)
!977 = !DISubprogram(name: "wcspbrk", scope: !721, file: !721, line: 201, type: !978, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!978 = !DISubroutineType(types: !979)
!979 = !{!590, !636, !636}
!980 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !981, file: !715, line: 206)
!981 = !DISubprogram(name: "wcsrchr", scope: !721, file: !721, line: 174, type: !974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!982 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !983, file: !715, line: 207)
!983 = !DISubprogram(name: "wcsstr", scope: !721, file: !721, line: 212, type: !978, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!984 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !985, file: !715, line: 208)
!985 = !DISubprogram(name: "wmemchr", scope: !721, file: !721, line: 253, type: !986, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!986 = !DISubroutineType(types: !987)
!987 = !{!590, !636, !591, !426}
!988 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !989, file: !715, line: 248)
!989 = !DISubprogram(name: "wcstold", scope: !721, file: !721, line: 384, type: !990, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!990 = !DISubroutineType(types: !991)
!991 = !{!152, !635, !928}
!992 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !993, file: !715, line: 257)
!993 = !DISubprogram(name: "wcstoll", scope: !721, file: !721, line: 441, type: !994, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!994 = !DISubroutineType(types: !995)
!995 = !{!263, !635, !928, !13}
!996 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !997, file: !715, line: 258)
!997 = !DISubprogram(name: "wcstoull", scope: !721, file: !721, line: 448, type: !998, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!998 = !DISubroutineType(types: !999)
!999 = !{!671, !635, !928, !13}
!1000 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !989, file: !715, line: 264)
!1001 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !993, file: !715, line: 265)
!1002 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !997, file: !715, line: 266)
!1003 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !931, file: !715, line: 280)
!1004 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !859, file: !715, line: 283)
!1005 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !865, file: !715, line: 286)
!1006 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !873, file: !715, line: 289)
!1007 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !989, file: !715, line: 293)
!1008 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !993, file: !715, line: 294)
!1009 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !997, file: !715, line: 295)
!1010 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !3, file: !1011, line: 48)
!1011 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdint", directory: "")
!1012 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !8, file: !1011, line: 49)
!1013 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !11, file: !1011, line: 50)
!1014 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !14, file: !1011, line: 51)
!1015 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1016, file: !1011, line: 53)
!1016 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast8_t", file: !1017, line: 68, baseType: !7)
!1017 = !DIFile(filename: "/usr/include/stdint.h", directory: "", checksumkind: CSK_MD5, checksum: "c7469e3b87cb3d1a363efabd19f04208")
!1018 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1019, file: !1011, line: 54)
!1019 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast16_t", file: !1017, line: 70, baseType: !16)
!1020 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1021, file: !1011, line: 55)
!1021 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast32_t", file: !1017, line: 71, baseType: !16)
!1022 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1023, file: !1011, line: 56)
!1023 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast64_t", file: !1017, line: 72, baseType: !16)
!1024 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1025, file: !1011, line: 58)
!1025 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least8_t", file: !1017, line: 43, baseType: !7)
!1026 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1027, file: !1011, line: 59)
!1027 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least16_t", file: !1017, line: 44, baseType: !10)
!1028 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1029, file: !1011, line: 60)
!1029 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least32_t", file: !1017, line: 45, baseType: !13)
!1030 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1031, file: !1011, line: 61)
!1031 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least64_t", file: !1017, line: 47, baseType: !16)
!1032 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1033, file: !1011, line: 63)
!1033 = !DIDerivedType(tag: DW_TAG_typedef, name: "intmax_t", file: !1017, line: 111, baseType: !1034)
!1034 = !DIDerivedType(tag: DW_TAG_typedef, name: "__intmax_t", file: !6, line: 61, baseType: !16)
!1035 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1036, file: !1011, line: 64)
!1036 = !DIDerivedType(tag: DW_TAG_typedef, name: "intptr_t", file: !1017, line: 97, baseType: !16)
!1037 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1038, file: !1011, line: 66)
!1038 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint8_t", file: !18, line: 24, baseType: !1039)
!1039 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint8_t", file: !6, line: 37, baseType: !1040)
!1040 = !DIBasicType(name: "unsigned char", size: 8, encoding: DW_ATE_unsigned_char)
!1041 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1042, file: !1011, line: 67)
!1042 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint16_t", file: !18, line: 25, baseType: !1043)
!1043 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint16_t", file: !6, line: 39, baseType: !756)
!1044 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1045, file: !1011, line: 68)
!1045 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint32_t", file: !18, line: 26, baseType: !1046)
!1046 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint32_t", file: !6, line: 41, baseType: !614)
!1047 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !17, file: !1011, line: 69)
!1048 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1049, file: !1011, line: 71)
!1049 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast8_t", file: !1017, line: 81, baseType: !1040)
!1050 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1051, file: !1011, line: 72)
!1051 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast16_t", file: !1017, line: 83, baseType: !20)
!1052 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1053, file: !1011, line: 73)
!1053 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast32_t", file: !1017, line: 84, baseType: !20)
!1054 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1055, file: !1011, line: 74)
!1055 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast64_t", file: !1017, line: 85, baseType: !20)
!1056 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1057, file: !1011, line: 76)
!1057 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least8_t", file: !1017, line: 54, baseType: !1040)
!1058 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1059, file: !1011, line: 77)
!1059 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least16_t", file: !1017, line: 55, baseType: !756)
!1060 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1061, file: !1011, line: 78)
!1061 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least32_t", file: !1017, line: 56, baseType: !614)
!1062 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1063, file: !1011, line: 79)
!1063 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least64_t", file: !1017, line: 58, baseType: !20)
!1064 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1065, file: !1011, line: 81)
!1065 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintmax_t", file: !1017, line: 112, baseType: !1066)
!1066 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uintmax_t", file: !6, line: 62, baseType: !20)
!1067 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1068, file: !1011, line: 82)
!1068 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintptr_t", file: !1017, line: 100, baseType: !20)
!1069 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1070, file: !1072, line: 53)
!1070 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "lconv", file: !1071, line: 51, size: 768, flags: DIFlagFwdDecl, identifier: "_ZTS5lconv")
!1071 = !DIFile(filename: "/usr/include/locale.h", directory: "", checksumkind: CSK_MD5, checksum: "0595275e3f5b502d28f7cd61a0dff888")
!1072 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/clocale", directory: "")
!1073 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1074, file: !1072, line: 54)
!1074 = !DISubprogram(name: "setlocale", scope: !1071, file: !1071, line: 122, type: !1075, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1075 = !DISubroutineType(types: !1076)
!1076 = !{!451, !13, !318}
!1077 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1078, file: !1072, line: 55)
!1078 = !DISubprogram(name: "localeconv", scope: !1071, file: !1071, line: 125, type: !1079, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1079 = !DISubroutineType(types: !1080)
!1080 = !{!1081}
!1081 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1070, size: 64)
!1082 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1083, file: !1085, line: 64)
!1083 = !DISubprogram(name: "isalnum", scope: !1084, file: !1084, line: 108, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1084 = !DIFile(filename: "/usr/include/ctype.h", directory: "", checksumkind: CSK_MD5, checksum: "c67c809b09ef8ea9c273687bc20a7fd3")
!1085 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cctype", directory: "")
!1086 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1087, file: !1085, line: 65)
!1087 = !DISubprogram(name: "isalpha", scope: !1084, file: !1084, line: 109, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1088 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1089, file: !1085, line: 66)
!1089 = !DISubprogram(name: "iscntrl", scope: !1084, file: !1084, line: 110, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1090 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1091, file: !1085, line: 67)
!1091 = !DISubprogram(name: "isdigit", scope: !1084, file: !1084, line: 111, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1092 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1093, file: !1085, line: 68)
!1093 = !DISubprogram(name: "isgraph", scope: !1084, file: !1084, line: 113, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1094 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1095, file: !1085, line: 69)
!1095 = !DISubprogram(name: "islower", scope: !1084, file: !1084, line: 112, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1096 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1097, file: !1085, line: 70)
!1097 = !DISubprogram(name: "isprint", scope: !1084, file: !1084, line: 114, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1098 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1099, file: !1085, line: 71)
!1099 = !DISubprogram(name: "ispunct", scope: !1084, file: !1084, line: 115, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1100 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1101, file: !1085, line: 72)
!1101 = !DISubprogram(name: "isspace", scope: !1084, file: !1084, line: 116, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1102 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1103, file: !1085, line: 73)
!1103 = !DISubprogram(name: "isupper", scope: !1084, file: !1084, line: 117, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1104 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1105, file: !1085, line: 74)
!1105 = !DISubprogram(name: "isxdigit", scope: !1084, file: !1084, line: 118, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1106 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1107, file: !1085, line: 75)
!1107 = !DISubprogram(name: "tolower", scope: !1084, file: !1084, line: 122, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1108 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1109, file: !1085, line: 76)
!1109 = !DISubprogram(name: "toupper", scope: !1084, file: !1084, line: 125, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1110 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1111, file: !1085, line: 87)
!1111 = !DISubprogram(name: "isblank", scope: !1084, file: !1084, line: 130, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1112 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !1113, file: !1115, line: 44)
!1113 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", scope: !71, file: !1114, line: 238, baseType: !20)
!1114 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8/bits/c++config.h", directory: "", checksumkind: CSK_MD5, checksum: "5ab2830680f5a52514c973f039a03c0a")
!1115 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/new_allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "ece13daf300dfc0cac27dc2ea29129ca")
!1116 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !1117, file: !1115, line: 45)
!1117 = !DIDerivedType(tag: DW_TAG_typedef, name: "ptrdiff_t", scope: !71, file: !1114, line: 239, baseType: !16)
!1118 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1119, file: !1121, line: 98)
!1119 = !DIDerivedType(tag: DW_TAG_typedef, name: "FILE", file: !1120, line: 7, baseType: !731)
!1120 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/FILE.h", directory: "", checksumkind: CSK_MD5, checksum: "571f9fb6223c42439075fdde11a0de5d")
!1121 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdio", directory: "")
!1122 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1123, file: !1121, line: 99)
!1123 = !DIDerivedType(tag: DW_TAG_typedef, name: "fpos_t", file: !1124, line: 78, baseType: !1125)
!1124 = !DIFile(filename: "/usr/include/stdio.h", directory: "", checksumkind: CSK_MD5, checksum: "2ab51d960d7d0ed84798d1688a6988b0")
!1125 = !DIDerivedType(tag: DW_TAG_typedef, name: "_G_fpos_t", file: !1126, line: 30, baseType: !1127)
!1126 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/_G_config.h", directory: "", checksumkind: CSK_MD5, checksum: "f78480ecfcae11a7bda5a6b08034c1fb")
!1127 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !1126, line: 26, size: 128, flags: DIFlagFwdDecl, identifier: "_ZTS9_G_fpos_t")
!1128 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1129, file: !1121, line: 101)
!1129 = !DISubprogram(name: "clearerr", scope: !1124, file: !1124, line: 757, type: !1130, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1130 = !DISubroutineType(types: !1131)
!1131 = !{null, !1132}
!1132 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1119, size: 64)
!1133 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1134, file: !1121, line: 102)
!1134 = !DISubprogram(name: "fclose", scope: !1124, file: !1124, line: 199, type: !1135, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1135 = !DISubroutineType(types: !1136)
!1136 = !{!13, !1132}
!1137 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1138, file: !1121, line: 103)
!1138 = !DISubprogram(name: "feof", scope: !1124, file: !1124, line: 759, type: !1135, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1139 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1140, file: !1121, line: 104)
!1140 = !DISubprogram(name: "ferror", scope: !1124, file: !1124, line: 761, type: !1135, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1141 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1142, file: !1121, line: 105)
!1142 = !DISubprogram(name: "fflush", scope: !1124, file: !1124, line: 204, type: !1135, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1143 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1144, file: !1121, line: 106)
!1144 = !DISubprogram(name: "fgetc", scope: !1124, file: !1124, line: 477, type: !1135, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1145 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1146, file: !1121, line: 107)
!1146 = !DISubprogram(name: "fgetpos", scope: !1124, file: !1124, line: 731, type: !1147, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1147 = !DISubroutineType(types: !1148)
!1148 = !{!13, !1149, !1150}
!1149 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !1132)
!1150 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !1151)
!1151 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1123, size: 64)
!1152 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1153, file: !1121, line: 108)
!1153 = !DISubprogram(name: "fgets", scope: !1124, file: !1124, line: 564, type: !1154, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1154 = !DISubroutineType(types: !1155)
!1155 = !{!451, !452, !13, !1149}
!1156 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1157, file: !1121, line: 109)
!1157 = !DISubprogram(name: "fopen", scope: !1124, file: !1124, line: 232, type: !1158, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1158 = !DISubroutineType(types: !1159)
!1159 = !{!1132, !453, !453}
!1160 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1161, file: !1121, line: 110)
!1161 = !DISubprogram(name: "fprintf", scope: !1124, file: !1124, line: 312, type: !1162, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1162 = !DISubroutineType(types: !1163)
!1163 = !{!13, !1149, !453, null}
!1164 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1165, file: !1121, line: 111)
!1165 = !DISubprogram(name: "fputc", scope: !1124, file: !1124, line: 517, type: !1166, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1166 = !DISubroutineType(types: !1167)
!1167 = !{!13, !13, !1132}
!1168 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1169, file: !1121, line: 112)
!1169 = !DISubprogram(name: "fputs", scope: !1124, file: !1124, line: 626, type: !1170, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1170 = !DISubroutineType(types: !1171)
!1171 = !{!13, !453, !1149}
!1172 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1173, file: !1121, line: 113)
!1173 = !DISubprogram(name: "fread", scope: !1124, file: !1124, line: 646, type: !1174, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1174 = !DISubroutineType(types: !1175)
!1175 = !{!426, !437, !426, !426, !1149}
!1176 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1177, file: !1121, line: 114)
!1177 = !DISubprogram(name: "freopen", scope: !1124, file: !1124, line: 238, type: !1178, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1178 = !DISubroutineType(types: !1179)
!1179 = !{!1132, !453, !453, !1149}
!1180 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1181, file: !1121, line: 115)
!1181 = !DISubprogram(name: "fscanf", scope: !1124, file: !1124, line: 377, type: !1162, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1182 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1183, file: !1121, line: 116)
!1183 = !DISubprogram(name: "fseek", scope: !1124, file: !1124, line: 684, type: !1184, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1184 = !DISubroutineType(types: !1185)
!1185 = !{!13, !1132, !16, !13}
!1186 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1187, file: !1121, line: 117)
!1187 = !DISubprogram(name: "fsetpos", scope: !1124, file: !1124, line: 736, type: !1188, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1188 = !DISubroutineType(types: !1189)
!1189 = !{!13, !1132, !1190}
!1190 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1191, size: 64)
!1191 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1123)
!1192 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1193, file: !1121, line: 118)
!1193 = !DISubprogram(name: "ftell", scope: !1124, file: !1124, line: 689, type: !1194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1194 = !DISubroutineType(types: !1195)
!1195 = !{!16, !1132}
!1196 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1197, file: !1121, line: 119)
!1197 = !DISubprogram(name: "fwrite", scope: !1124, file: !1124, line: 652, type: !1198, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1198 = !DISubroutineType(types: !1199)
!1199 = !{!426, !438, !426, !426, !1149}
!1200 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1201, file: !1121, line: 120)
!1201 = !DISubprogram(name: "getc", scope: !1124, file: !1124, line: 478, type: !1135, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1202 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1203, file: !1121, line: 121)
!1203 = !DISubprogram(name: "getchar", scope: !1204, file: !1204, line: 44, type: !604, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1204 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdio.h", directory: "", checksumkind: CSK_MD5, checksum: "ae874477a6b090849220f12acdd69dc3")
!1205 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1206, file: !1121, line: 126)
!1206 = !DISubprogram(name: "perror", scope: !1124, file: !1124, line: 775, type: !1207, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1207 = !DISubroutineType(types: !1208)
!1208 = !{null, !318}
!1209 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1210, file: !1121, line: 127)
!1210 = !DISubprogram(name: "printf", scope: !1124, file: !1124, line: 318, type: !1211, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1211 = !DISubroutineType(types: !1212)
!1212 = !{!13, !453, null}
!1213 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1214, file: !1121, line: 128)
!1214 = !DISubprogram(name: "putc", scope: !1124, file: !1124, line: 518, type: !1166, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1215 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1216, file: !1121, line: 129)
!1216 = !DISubprogram(name: "putchar", scope: !1204, file: !1204, line: 79, type: !74, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1217 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1218, file: !1121, line: 130)
!1218 = !DISubprogram(name: "puts", scope: !1124, file: !1124, line: 632, type: !534, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1219 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1220, file: !1121, line: 131)
!1220 = !DISubprogram(name: "remove", scope: !1124, file: !1124, line: 144, type: !534, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1221 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1222, file: !1121, line: 132)
!1222 = !DISubprogram(name: "rename", scope: !1124, file: !1124, line: 146, type: !456, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1223 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1224, file: !1121, line: 133)
!1224 = !DISubprogram(name: "rewind", scope: !1124, file: !1124, line: 694, type: !1130, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1225 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1226, file: !1121, line: 134)
!1226 = !DISubprogram(name: "scanf", scope: !1124, file: !1124, line: 383, type: !1211, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1227 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1228, file: !1121, line: 135)
!1228 = !DISubprogram(name: "setbuf", scope: !1124, file: !1124, line: 290, type: !1229, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1229 = !DISubroutineType(types: !1230)
!1230 = !{null, !1149, !452}
!1231 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1232, file: !1121, line: 136)
!1232 = !DISubprogram(name: "setvbuf", scope: !1124, file: !1124, line: 294, type: !1233, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1233 = !DISubroutineType(types: !1234)
!1234 = !{!13, !1149, !452, !13, !426}
!1235 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1236, file: !1121, line: 137)
!1236 = !DISubprogram(name: "sprintf", scope: !1124, file: !1124, line: 320, type: !1237, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1237 = !DISubroutineType(types: !1238)
!1238 = !{!13, !452, !453, null}
!1239 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1240, file: !1121, line: 138)
!1240 = !DISubprogram(name: "sscanf", scope: !1124, file: !1124, line: 385, type: !1241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1241 = !DISubroutineType(types: !1242)
!1242 = !{!13, !453, !453, null}
!1243 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1244, file: !1121, line: 139)
!1244 = !DISubprogram(name: "tmpfile", scope: !1124, file: !1124, line: 159, type: !1245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1245 = !DISubroutineType(types: !1246)
!1246 = !{!1132}
!1247 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1248, file: !1121, line: 141)
!1248 = !DISubprogram(name: "tmpnam", scope: !1124, file: !1124, line: 173, type: !1249, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1249 = !DISubroutineType(types: !1250)
!1250 = !{!451, !451}
!1251 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1252, file: !1121, line: 143)
!1252 = !DISubprogram(name: "ungetc", scope: !1124, file: !1124, line: 639, type: !1166, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1253 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1254, file: !1121, line: 144)
!1254 = !DISubprogram(name: "vfprintf", scope: !1124, file: !1124, line: 327, type: !1255, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1255 = !DISubroutineType(types: !1256)
!1256 = !{!13, !1149, !453, !850}
!1257 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1258, file: !1121, line: 145)
!1258 = !DISubprogram(name: "vprintf", scope: !1204, file: !1204, line: 36, type: !1259, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1259 = !DISubroutineType(types: !1260)
!1260 = !{!13, !453, !850}
!1261 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1262, file: !1121, line: 146)
!1262 = !DISubprogram(name: "vsprintf", scope: !1124, file: !1124, line: 335, type: !1263, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1263 = !DISubroutineType(types: !1264)
!1264 = !{!13, !452, !453, !850}
!1265 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !1266, file: !1121, line: 175)
!1266 = !DISubprogram(name: "snprintf", scope: !1124, file: !1124, line: 340, type: !1267, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1267 = !DISubroutineType(types: !1268)
!1268 = !{!13, !452, !426, !453, null}
!1269 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !1270, file: !1121, line: 176)
!1270 = !DISubprogram(name: "vfscanf", scope: !1124, file: !1124, line: 420, type: !1255, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1271 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !1272, file: !1121, line: 177)
!1272 = !DISubprogram(name: "vscanf", scope: !1124, file: !1124, line: 428, type: !1259, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1273 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !1274, file: !1121, line: 178)
!1274 = !DISubprogram(name: "vsnprintf", scope: !1124, file: !1124, line: 344, type: !1275, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1275 = !DISubroutineType(types: !1276)
!1276 = !{!13, !452, !426, !453, !850}
!1277 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !643, entity: !1278, file: !1121, line: 179)
!1278 = !DISubprogram(name: "vsscanf", scope: !1124, file: !1124, line: 432, type: !1279, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1279 = !DISubroutineType(types: !1280)
!1280 = !{!13, !453, !453, !850}
!1281 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1266, file: !1121, line: 185)
!1282 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1270, file: !1121, line: 186)
!1283 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1272, file: !1121, line: 187)
!1284 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1274, file: !1121, line: 188)
!1285 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1278, file: !1121, line: 189)
!1286 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1287, file: !1291, line: 82)
!1287 = !DIDerivedType(tag: DW_TAG_typedef, name: "wctrans_t", file: !1288, line: 48, baseType: !1289)
!1288 = !DIFile(filename: "/usr/include/wctype.h", directory: "", checksumkind: CSK_MD5, checksum: "760693b7fbeea3d686e1f29058fc2257")
!1289 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1290, size: 64)
!1290 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !12)
!1291 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cwctype", directory: "")
!1292 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1293, file: !1291, line: 83)
!1293 = !DIDerivedType(tag: DW_TAG_typedef, name: "wctype_t", file: !1294, line: 38, baseType: !20)
!1294 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/wctype-wchar.h", directory: "", checksumkind: CSK_MD5, checksum: "45eef9c3aa1d99faffa3945ed9be039a")
!1295 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !717, file: !1291, line: 84)
!1296 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1297, file: !1291, line: 86)
!1297 = !DISubprogram(name: "iswalnum", scope: !1294, file: !1294, line: 95, type: !952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1298 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1299, file: !1291, line: 87)
!1299 = !DISubprogram(name: "iswalpha", scope: !1294, file: !1294, line: 101, type: !952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1300 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1301, file: !1291, line: 89)
!1301 = !DISubprogram(name: "iswblank", scope: !1294, file: !1294, line: 146, type: !952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1302 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1303, file: !1291, line: 91)
!1303 = !DISubprogram(name: "iswcntrl", scope: !1294, file: !1294, line: 104, type: !952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1304 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1305, file: !1291, line: 92)
!1305 = !DISubprogram(name: "iswctype", scope: !1294, file: !1294, line: 159, type: !1306, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1306 = !DISubroutineType(types: !1307)
!1307 = !{!13, !717, !1293}
!1308 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1309, file: !1291, line: 93)
!1309 = !DISubprogram(name: "iswdigit", scope: !1294, file: !1294, line: 108, type: !952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1310 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1311, file: !1291, line: 94)
!1311 = !DISubprogram(name: "iswgraph", scope: !1294, file: !1294, line: 112, type: !952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1312 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1313, file: !1291, line: 95)
!1313 = !DISubprogram(name: "iswlower", scope: !1294, file: !1294, line: 117, type: !952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1314 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1315, file: !1291, line: 96)
!1315 = !DISubprogram(name: "iswprint", scope: !1294, file: !1294, line: 120, type: !952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1316 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1317, file: !1291, line: 97)
!1317 = !DISubprogram(name: "iswpunct", scope: !1294, file: !1294, line: 125, type: !952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1318 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1319, file: !1291, line: 98)
!1319 = !DISubprogram(name: "iswspace", scope: !1294, file: !1294, line: 130, type: !952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1320 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1321, file: !1291, line: 99)
!1321 = !DISubprogram(name: "iswupper", scope: !1294, file: !1294, line: 135, type: !952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1322 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1323, file: !1291, line: 100)
!1323 = !DISubprogram(name: "iswxdigit", scope: !1294, file: !1294, line: 140, type: !952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1324 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1325, file: !1291, line: 101)
!1325 = !DISubprogram(name: "towctrans", scope: !1288, file: !1288, line: 55, type: !1326, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1326 = !DISubroutineType(types: !1327)
!1327 = !{!717, !717, !1287}
!1328 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1329, file: !1291, line: 102)
!1329 = !DISubprogram(name: "towlower", scope: !1294, file: !1294, line: 166, type: !1330, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1330 = !DISubroutineType(types: !1331)
!1331 = !{!717, !717}
!1332 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1333, file: !1291, line: 103)
!1333 = !DISubprogram(name: "towupper", scope: !1294, file: !1294, line: 169, type: !1330, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1334 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1335, file: !1291, line: 104)
!1335 = !DISubprogram(name: "wctrans", scope: !1288, file: !1288, line: 52, type: !1336, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1336 = !DISubroutineType(types: !1337)
!1337 = !{!1287, !318}
!1338 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !71, entity: !1339, file: !1291, line: 105)
!1339 = !DISubprogram(name: "wctype", scope: !1294, file: !1294, line: 155, type: !1340, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1340 = !DISubroutineType(types: !1341)
!1341 = !{!1293, !318}
!1342 = !DIImportedEntity(tag: DW_TAG_imported_module, scope: !0, entity: !24, file: !28, line: 14)
!1343 = !{i32 7, !"Dwarf Version", i32 5}
!1344 = !{i32 2, !"Debug Info Version", i32 3}
!1345 = !{i32 1, !"wchar_size", i32 4}
!1346 = !{i32 7, !"PIC Level", i32 2}
!1347 = !{i32 7, !"uwtable", i32 2}
!1348 = !DILocalVariable(name: "val", scope: !1349, file: !28, line: 19, type: !1040)
!1349 = distinct !DISubprogram(name: "getU<unsigned char>", linkageName: "_ZL4getUIhET_PjPKN4llvm13DataExtractorEbPKc", scope: !28, file: !28, line: 17, type: !1350, scopeLine: 18, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !1363, retainedNodes: !1357)
!1350 = !DISubroutineType(types: !1351)
!1351 = !{!1040, !1352, !1353, !21, !318}
!1352 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1045, size: 64)
!1353 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1354, size: 64)
!1354 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1355)
!1355 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DataExtractor", scope: !24, file: !1356, line: 18, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm13DataExtractorE")
!1356 = !DIFile(filename: "llvm34/include/llvm/Support/DataExtractor.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "ab8e04e2cdae0fee3a5b7c900855b879")
!1357 = !{!1358, !1359, !1360, !1361, !1348, !1362}
!1358 = !DILocalVariable(name: "offset_ptr", arg: 1, scope: !1349, file: !28, line: 17, type: !1352)
!1359 = !DILocalVariable(name: "de", arg: 2, scope: !1349, file: !28, line: 17, type: !1353)
!1360 = !DILocalVariable(name: "isLittleEndian", arg: 3, scope: !1349, file: !28, line: 18, type: !21)
!1361 = !DILocalVariable(name: "Data", arg: 4, scope: !1349, file: !28, line: 18, type: !318)
!1362 = !DILocalVariable(name: "offset", scope: !1349, file: !28, line: 20, type: !1045)
!1363 = !{!1364}
!1364 = !DITemplateTypeParameter(name: "T", type: !1040)
!1365 = !DILocation(line: 0, scope: !1349)
