; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s --passes=instcombine -o - -S | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define linkonce_odr { ptr, i32 } @_ZNSt11__copy_moveILb0ELb0ESt26random_access_iterator_tagE8__copy_mISt13_Bit_iteratorS3_EET0_T_S5_S4_(ptr %0, i1 %tobool.i.not.i) {
; CHECK-LABEL: @_ZNSt11__copy_moveILb0ELb0ESt26random_access_iterator_tagE8__copy_mISt13_Bit_iteratorS3_EET0_T_S5_S4_(
; CHECK-NEXT:  for.body:
; CHECK-NEXT:    br i1 [[TOBOOL_I_NOT_I:%.*]], label [[IF_ELSE_I_I:%.*]], label [[IF_THEN_I_I:%.*]]
; CHECK:       if.then.i.i:
; CHECK-NEXT:    br label [[_ZNST14_BIT_REFERENCEASERKS__EXIT:%.*]]
; CHECK:       if.else.i.i:
; CHECK-NEXT:    br label [[_ZNST14_BIT_REFERENCEASERKS__EXIT]]
; CHECK:       _ZNSt14_Bit_referenceaSERKS_.exit:
; CHECK-NEXT:    [[STOREMERGE:%.*]] = phi i64 [ 1, [[IF_THEN_I_I]] ], [ 0, [[IF_ELSE_I_I]] ]
; CHECK-NEXT:    store i64 [[STOREMERGE]], ptr [[TMP0:%.*]], align 8
; CHECK-NEXT:    call void @llvm.dbg.value(metadata ptr null, metadata [[META6619:![0-9]+]], metadata !DIExpression()), !dbg [[DBG6623:![0-9]+]]
; CHECK-NEXT:    ret { ptr, i32 } zeroinitializer
;
for.body:
  br i1 %tobool.i.not.i, label %if.else.i.i, label %if.then.i.i

if.then.i.i:                                      ; preds = %for.body
  store i64 1, ptr %0, align 8
  br label %_ZNSt14_Bit_referenceaSERKS_.exit

if.else.i.i:                                      ; preds = %for.body
  store i64 0, ptr %0, align 8
  br label %_ZNSt14_Bit_referenceaSERKS_.exit

_ZNSt14_Bit_referenceaSERKS_.exit:                ; preds = %if.else.i.i, %if.then.i.i
  call void @llvm.dbg.value(metadata ptr null, metadata !6619, metadata !DIExpression()), !dbg !6623
  ret { ptr, i32 } zeroinitializer
}

; Function Attrs: nocallback nofree nosync nounwind readnone speculatable willreturn
declare void @llvm.dbg.value(metadata, metadata, metadata) #0

attributes #0 = { nocallback nofree nosync nounwind readnone speculatable willreturn }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!6614, !6615, !6616, !6617, !6618}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !3293, globals: !4879, imports: !5311, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "/fast/fs/llvm34/lib/Support/YAMLTraits.cpp", directory: "/fast/fs/build34llvm5", checksumkind: CSK_MD5, checksum: "f31e6409b6fed9b737ded9800de56e42")
!2 = !{!3, !11, !107, !1074, !2173, !2326, !429, !2331, !2341, !3286, !3289}
!3 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "_Lock_policy", scope: !5, file: !4, line: 49, baseType: !6, size: 32, elements: !7, identifier: "_ZTSN9__gnu_cxx12_Lock_policyE")
!4 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/concurrence.h", directory: "")
!5 = !DINamespace(name: "__gnu_cxx", scope: null)
!6 = !DIBasicType(name: "unsigned int", size: 32, encoding: DW_ATE_unsigned)
!7 = !{!8, !9, !10}
!8 = !DIEnumerator(name: "_S_single", value: 0, isUnsigned: true)
!9 = !DIEnumerator(name: "_S_mutex", value: 1, isUnsigned: true)
!10 = !DIEnumerator(name: "_S_atomic", value: 2, isUnsigned: true)
!11 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "_", scope: !13, file: !12, line: 488, baseType: !6, size: 32, elements: !27, identifier: "_ZTSN4llvm4errc1_E")
!12 = !DIFile(filename: "llvm34/include/llvm/Support/system_error.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "072ae1f0c2ffd3e0f3980ca841a73a7d")
!13 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "errc", scope: !14, file: !12, line: 487, size: 32, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !15, identifier: "_ZTSN4llvm4errcE")
!14 = !DINamespace(name: "llvm", scope: null)
!15 = !{!16, !17, !21}
!16 = !DIDerivedType(tag: DW_TAG_member, name: "v_", scope: !13, file: !12, line: 610, baseType: !11, size: 32)
!17 = !DISubprogram(name: "errc", scope: !13, file: !12, line: 612, type: !18, scopeLine: 612, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!18 = !DISubroutineType(types: !19)
!19 = !{null, !20, !11}
!20 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !13, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!21 = !DISubprogram(name: "operator int", linkageName: "_ZNK4llvm4errccviEv", scope: !13, file: !12, line: 613, type: !22, scopeLine: 613, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!22 = !DISubroutineType(types: !23)
!23 = !{!24, !25}
!24 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!25 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !26, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!26 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !13)
!27 = !{!28, !29, !30, !31, !32, !33, !34, !35, !36, !37, !38, !39, !40, !41, !42, !43, !44, !45, !46, !47, !48, !49, !50, !51, !52, !53, !54, !55, !56, !57, !58, !59, !60, !61, !62, !63, !64, !65, !66, !67, !68, !69, !70, !71, !72, !73, !74, !75, !76, !77, !78, !79, !80, !81, !82, !83, !84, !85, !86, !87, !88, !89, !90, !91, !92, !93, !94, !95, !96, !97, !98, !99, !100, !101, !102, !103, !104, !105, !106}
!28 = !DIEnumerator(name: "success", value: 0, isUnsigned: true)
!29 = !DIEnumerator(name: "address_family_not_supported", value: 97, isUnsigned: true)
!30 = !DIEnumerator(name: "address_in_use", value: 98, isUnsigned: true)
!31 = !DIEnumerator(name: "address_not_available", value: 99, isUnsigned: true)
!32 = !DIEnumerator(name: "already_connected", value: 106, isUnsigned: true)
!33 = !DIEnumerator(name: "argument_list_too_long", value: 7, isUnsigned: true)
!34 = !DIEnumerator(name: "argument_out_of_domain", value: 33, isUnsigned: true)
!35 = !DIEnumerator(name: "bad_address", value: 14, isUnsigned: true)
!36 = !DIEnumerator(name: "bad_file_descriptor", value: 9, isUnsigned: true)
!37 = !DIEnumerator(name: "bad_message", value: 74, isUnsigned: true)
!38 = !DIEnumerator(name: "broken_pipe", value: 32, isUnsigned: true)
!39 = !DIEnumerator(name: "connection_aborted", value: 103, isUnsigned: true)
!40 = !DIEnumerator(name: "connection_already_in_progress", value: 114, isUnsigned: true)
!41 = !DIEnumerator(name: "connection_refused", value: 111, isUnsigned: true)
!42 = !DIEnumerator(name: "connection_reset", value: 104, isUnsigned: true)
!43 = !DIEnumerator(name: "cross_device_link", value: 18, isUnsigned: true)
!44 = !DIEnumerator(name: "destination_address_required", value: 89, isUnsigned: true)
!45 = !DIEnumerator(name: "device_or_resource_busy", value: 16, isUnsigned: true)
!46 = !DIEnumerator(name: "directory_not_empty", value: 39, isUnsigned: true)
!47 = !DIEnumerator(name: "executable_format_error", value: 8, isUnsigned: true)
!48 = !DIEnumerator(name: "file_exists", value: 17, isUnsigned: true)
!49 = !DIEnumerator(name: "file_too_large", value: 27, isUnsigned: true)
!50 = !DIEnumerator(name: "filename_too_long", value: 36, isUnsigned: true)
!51 = !DIEnumerator(name: "function_not_supported", value: 38, isUnsigned: true)
!52 = !DIEnumerator(name: "host_unreachable", value: 113, isUnsigned: true)
!53 = !DIEnumerator(name: "identifier_removed", value: 43, isUnsigned: true)
!54 = !DIEnumerator(name: "illegal_byte_sequence", value: 84, isUnsigned: true)
!55 = !DIEnumerator(name: "inappropriate_io_control_operation", value: 25, isUnsigned: true)
!56 = !DIEnumerator(name: "interrupted", value: 4, isUnsigned: true)
!57 = !DIEnumerator(name: "invalid_argument", value: 22, isUnsigned: true)
!58 = !DIEnumerator(name: "invalid_seek", value: 29, isUnsigned: true)
!59 = !DIEnumerator(name: "io_error", value: 5, isUnsigned: true)
!60 = !DIEnumerator(name: "is_a_directory", value: 21, isUnsigned: true)
!61 = !DIEnumerator(name: "message_size", value: 90, isUnsigned: true)
!62 = !DIEnumerator(name: "network_down", value: 100, isUnsigned: true)
!63 = !DIEnumerator(name: "network_reset", value: 102, isUnsigned: true)
!64 = !DIEnumerator(name: "network_unreachable", value: 101, isUnsigned: true)
!65 = !DIEnumerator(name: "no_buffer_space", value: 105, isUnsigned: true)
!66 = !DIEnumerator(name: "no_child_process", value: 10, isUnsigned: true)
!67 = !DIEnumerator(name: "no_link", value: 67, isUnsigned: true)
!68 = !DIEnumerator(name: "no_lock_available", value: 37, isUnsigned: true)
!69 = !DIEnumerator(name: "no_message_available", value: 61, isUnsigned: true)
!70 = !DIEnumerator(name: "no_message", value: 42, isUnsigned: true)
!71 = !DIEnumerator(name: "no_protocol_option", value: 92, isUnsigned: true)
!72 = !DIEnumerator(name: "no_space_on_device", value: 28, isUnsigned: true)
!73 = !DIEnumerator(name: "no_stream_resources", value: 63, isUnsigned: true)
!74 = !DIEnumerator(name: "no_such_device_or_address", value: 6, isUnsigned: true)
!75 = !DIEnumerator(name: "no_such_device", value: 19, isUnsigned: true)
!76 = !DIEnumerator(name: "no_such_file_or_directory", value: 2, isUnsigned: true)
!77 = !DIEnumerator(name: "no_such_process", value: 3, isUnsigned: true)
!78 = !DIEnumerator(name: "not_a_directory", value: 20, isUnsigned: true)
!79 = !DIEnumerator(name: "not_a_socket", value: 88, isUnsigned: true)
!80 = !DIEnumerator(name: "not_a_stream", value: 60, isUnsigned: true)
!81 = !DIEnumerator(name: "not_connected", value: 107, isUnsigned: true)
!82 = !DIEnumerator(name: "not_enough_memory", value: 12, isUnsigned: true)
!83 = !DIEnumerator(name: "not_supported", value: 95, isUnsigned: true)
!84 = !DIEnumerator(name: "operation_canceled", value: 125, isUnsigned: true)
!85 = !DIEnumerator(name: "operation_in_progress", value: 115, isUnsigned: true)
!86 = !DIEnumerator(name: "operation_not_permitted", value: 1, isUnsigned: true)
!87 = !DIEnumerator(name: "operation_not_supported", value: 95, isUnsigned: true)
!88 = !DIEnumerator(name: "operation_would_block", value: 11, isUnsigned: true)
!89 = !DIEnumerator(name: "owner_dead", value: 130, isUnsigned: true)
!90 = !DIEnumerator(name: "permission_denied", value: 13, isUnsigned: true)
!91 = !DIEnumerator(name: "protocol_error", value: 71, isUnsigned: true)
!92 = !DIEnumerator(name: "protocol_not_supported", value: 93, isUnsigned: true)
!93 = !DIEnumerator(name: "read_only_file_system", value: 30, isUnsigned: true)
!94 = !DIEnumerator(name: "resource_deadlock_would_occur", value: 35, isUnsigned: true)
!95 = !DIEnumerator(name: "resource_unavailable_try_again", value: 11, isUnsigned: true)
!96 = !DIEnumerator(name: "result_out_of_range", value: 34, isUnsigned: true)
!97 = !DIEnumerator(name: "state_not_recoverable", value: 131, isUnsigned: true)
!98 = !DIEnumerator(name: "stream_timeout", value: 62, isUnsigned: true)
!99 = !DIEnumerator(name: "text_file_busy", value: 26, isUnsigned: true)
!100 = !DIEnumerator(name: "timed_out", value: 110, isUnsigned: true)
!101 = !DIEnumerator(name: "too_many_files_open_in_system", value: 23, isUnsigned: true)
!102 = !DIEnumerator(name: "too_many_files_open", value: 24, isUnsigned: true)
!103 = !DIEnumerator(name: "too_many_links", value: 31, isUnsigned: true)
!104 = !DIEnumerator(name: "too_many_symbolic_link_levels", value: 40, isUnsigned: true)
!105 = !DIEnumerator(name: "value_too_large", value: 75, isUnsigned: true)
!106 = !DIEnumerator(name: "wrong_protocol_type", value: 91, isUnsigned: true)
!107 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "InState", scope: !109, file: !108, line: 868, baseType: !6, size: 32, elements: !1069, identifier: "_ZTSN4llvm4yaml6Output7InStateE")
!108 = !DIFile(filename: "llvm34/include/llvm/Support/YAMLTraits.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "1dab9feada443cc07b89eaff19fb3efa")
!109 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Output", scope: !110, file: !108, line: 823, size: 768, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !111, vtableHolder: !113)
!110 = !DINamespace(name: "yaml", scope: !14)
!111 = !{!112, !773, !774, !992, !993, !994, !995, !996, !997, !998, !1002, !1005, !1009, !1014, !1017, !1018, !1019, !1022, !1025, !1028, !1029, !1032, !1033, !1034, !1035, !1036, !1037, !1038, !1041, !1042, !1045, !1046, !1047, !1050, !1053, !1056, !1057, !1060, !1061, !1062, !1065, !1066, !1067, !1068}
!112 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !109, baseType: !113, flags: DIFlagPublic, extraData: i32 0)
!113 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "IO", scope: !110, file: !108, line: 315, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !114, vtableHolder: !113)
!114 = !{!115, !120, !122, !126, !129, !135, !138, !142, !143, !144, !147, !148, !149, !150, !151, !357, !358, !359, !363, !364, !365, !368, !369, !372, !373, !374, !378, !769, !772}
!115 = !DIDerivedType(tag: DW_TAG_member, name: "_vptr$IO", scope: !108, file: !108, baseType: !116, size: 64, flags: DIFlagArtificial)
!116 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !117, size: 64)
!117 = !DIDerivedType(tag: DW_TAG_pointer_type, name: "__vtbl_ptr_type", baseType: !118, size: 64)
!118 = !DISubroutineType(types: !119)
!119 = !{!24}
!120 = !DIDerivedType(tag: DW_TAG_member, name: "Ctxt", scope: !113, file: !108, line: 439, baseType: !121, size: 64, offset: 64)
!121 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 64)
!122 = !DISubprogram(name: "IO", scope: !113, file: !108, line: 318, type: !123, scopeLine: 318, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!123 = !DISubroutineType(types: !124)
!124 = !{null, !125, !121}
!125 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !113, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!126 = !DISubprogram(name: "~IO", scope: !113, file: !108, line: 319, type: !127, scopeLine: 319, containingType: !113, virtualIndex: 0, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!127 = !DISubroutineType(types: !128)
!128 = !{null, !125}
!129 = !DISubprogram(name: "outputting", linkageName: "_ZNK4llvm4yaml2IO10outputtingEv", scope: !113, file: !108, line: 321, type: !130, scopeLine: 321, containingType: !113, virtualIndex: 2, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!130 = !DISubroutineType(types: !131)
!131 = !{!132, !133}
!132 = !DIBasicType(name: "bool", size: 8, encoding: DW_ATE_boolean)
!133 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !134, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!134 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !113)
!135 = !DISubprogram(name: "beginSequence", linkageName: "_ZN4llvm4yaml2IO13beginSequenceEv", scope: !113, file: !108, line: 323, type: !136, scopeLine: 323, containingType: !113, virtualIndex: 3, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!136 = !DISubroutineType(types: !137)
!137 = !{!6, !125}
!138 = !DISubprogram(name: "preflightElement", linkageName: "_ZN4llvm4yaml2IO16preflightElementEjRPv", scope: !113, file: !108, line: 324, type: !139, scopeLine: 324, containingType: !113, virtualIndex: 4, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!139 = !DISubroutineType(types: !140)
!140 = !{!132, !125, !6, !141}
!141 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !121, size: 64)
!142 = !DISubprogram(name: "postflightElement", linkageName: "_ZN4llvm4yaml2IO17postflightElementEPv", scope: !113, file: !108, line: 325, type: !123, scopeLine: 325, containingType: !113, virtualIndex: 5, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!143 = !DISubprogram(name: "endSequence", linkageName: "_ZN4llvm4yaml2IO11endSequenceEv", scope: !113, file: !108, line: 326, type: !127, scopeLine: 326, containingType: !113, virtualIndex: 6, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!144 = !DISubprogram(name: "canElideEmptySequence", linkageName: "_ZN4llvm4yaml2IO21canElideEmptySequenceEv", scope: !113, file: !108, line: 327, type: !145, scopeLine: 327, containingType: !113, virtualIndex: 7, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!145 = !DISubroutineType(types: !146)
!146 = !{!132, !125}
!147 = !DISubprogram(name: "beginFlowSequence", linkageName: "_ZN4llvm4yaml2IO17beginFlowSequenceEv", scope: !113, file: !108, line: 329, type: !136, scopeLine: 329, containingType: !113, virtualIndex: 8, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!148 = !DISubprogram(name: "preflightFlowElement", linkageName: "_ZN4llvm4yaml2IO20preflightFlowElementEjRPv", scope: !113, file: !108, line: 330, type: !139, scopeLine: 330, containingType: !113, virtualIndex: 9, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!149 = !DISubprogram(name: "postflightFlowElement", linkageName: "_ZN4llvm4yaml2IO21postflightFlowElementEPv", scope: !113, file: !108, line: 331, type: !123, scopeLine: 331, containingType: !113, virtualIndex: 10, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!150 = !DISubprogram(name: "endFlowSequence", linkageName: "_ZN4llvm4yaml2IO15endFlowSequenceEv", scope: !113, file: !108, line: 332, type: !127, scopeLine: 332, containingType: !113, virtualIndex: 11, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!151 = !DISubprogram(name: "mapTag", linkageName: "_ZN4llvm4yaml2IO6mapTagENS_9StringRefEb", scope: !113, file: !108, line: 334, type: !152, scopeLine: 334, containingType: !113, virtualIndex: 12, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!152 = !DISubroutineType(types: !153)
!153 = !{!132, !125, !154, !132}
!154 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringRef", scope: !14, file: !155, line: 41, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !156, identifier: "_ZTSN4llvm9StringRefE")
!155 = !DIFile(filename: "llvm34/include/llvm/ADT/StringRef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "5c2e300880041c873457392c89335431")
!156 = !{!157, !162, !166, !167, !170, !171, !174, !178, !181, !184, !195, !201, !202, !205, !208, !211, !214, !215, !218, !219, !222, !223, !224, !227, !230, !233, !234, !235, !236, !237, !238, !241, !244, !245, !248, !249, !250, !251, !252, !253, !254, !255, !256, !259, !260, !265, !266, !267, !270, !273, !274, !275, !343, !346, !351, !352, !355, !356}
!157 = !DIDerivedType(tag: DW_TAG_member, name: "npos", scope: !154, file: !155, line: 45, baseType: !158, flags: DIFlagPublic | DIFlagStaticMember, extraData: i64 -1)
!158 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !159)
!159 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", file: !160, line: 46, baseType: !161)
!160 = !DIFile(filename: "llvm5/build/lib/clang/15.0.3/include/stddef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "b76978376d35d5cd171876ac58ac1256")
!161 = !DIBasicType(name: "unsigned long", size: 64, encoding: DW_ATE_unsigned)
!162 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !154, file: !155, line: 50, baseType: !163, size: 64)
!163 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !164, size: 64)
!164 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !165)
!165 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
!166 = !DIDerivedType(tag: DW_TAG_member, name: "Length", scope: !154, file: !155, line: 53, baseType: !159, size: 64, offset: 64)
!167 = !DISubprogram(name: "min", linkageName: "_ZN4llvm9StringRef3minEmm", scope: !154, file: !155, line: 58, type: !168, scopeLine: 58, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!168 = !DISubroutineType(types: !169)
!169 = !{!159, !159, !159}
!170 = !DISubprogram(name: "max", linkageName: "_ZN4llvm9StringRef3maxEmm", scope: !154, file: !155, line: 59, type: !168, scopeLine: 59, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!171 = !DISubprogram(name: "compareMemory", linkageName: "_ZN4llvm9StringRef13compareMemoryEPKcS2_m", scope: !154, file: !155, line: 63, type: !172, scopeLine: 63, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!172 = !DISubroutineType(types: !173)
!173 = !{!24, !163, !163, !159}
!174 = !DISubprogram(name: "StringRef", scope: !154, file: !155, line: 73, type: !175, scopeLine: 73, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!175 = !DISubroutineType(types: !176)
!176 = !{null, !177}
!177 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !154, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!178 = !DISubprogram(name: "StringRef", scope: !154, file: !155, line: 76, type: !179, scopeLine: 76, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!179 = !DISubroutineType(types: !180)
!180 = !{null, !177, !163}
!181 = !DISubprogram(name: "StringRef", scope: !154, file: !155, line: 83, type: !182, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!182 = !DISubroutineType(types: !183)
!183 = !{null, !177, !163, !159}
!184 = !DISubprogram(name: "StringRef", scope: !154, file: !155, line: 90, type: !185, scopeLine: 90, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!185 = !DISubroutineType(types: !186)
!186 = !{null, !177, !187}
!187 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !188, size: 64)
!188 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !189)
!189 = !DIDerivedType(tag: DW_TAG_typedef, name: "string", scope: !191, file: !190, line: 74, baseType: !193)
!190 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stringfwd.h", directory: "")
!191 = !DINamespace(name: "__cxx11", scope: !192, exportSymbols: true)
!192 = !DINamespace(name: "std", scope: null)
!193 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "basic_string<char, std::char_traits<char>, std::allocator<char> >", scope: !191, file: !194, line: 1607, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE")
!194 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.tcc", directory: "")
!195 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm9StringRef5beginEv", scope: !154, file: !155, line: 97, type: !196, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!196 = !DISubroutineType(types: !197)
!197 = !{!198, !199}
!198 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !154, file: !155, line: 43, baseType: !163)
!199 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !200, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!200 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !154)
!201 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm9StringRef3endEv", scope: !154, file: !155, line: 99, type: !196, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!202 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm9StringRef4dataEv", scope: !154, file: !155, line: 107, type: !203, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!203 = !DISubroutineType(types: !204)
!204 = !{!163, !199}
!205 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm9StringRef5emptyEv", scope: !154, file: !155, line: 110, type: !206, scopeLine: 110, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!206 = !DISubroutineType(types: !207)
!207 = !{!132, !199}
!208 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm9StringRef4sizeEv", scope: !154, file: !155, line: 113, type: !209, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!209 = !DISubroutineType(types: !210)
!210 = !{!159, !199}
!211 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm9StringRef5frontEv", scope: !154, file: !155, line: 116, type: !212, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!212 = !DISubroutineType(types: !213)
!213 = !{!165, !199}
!214 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm9StringRef4backEv", scope: !154, file: !155, line: 122, type: !212, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!215 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm9StringRef6equalsES0_", scope: !154, file: !155, line: 129, type: !216, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!216 = !DISubroutineType(types: !217)
!217 = !{!132, !199, !154}
!218 = !DISubprogram(name: "equals_lower", linkageName: "_ZNK4llvm9StringRef12equals_lowerES0_", scope: !154, file: !155, line: 135, type: !216, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!219 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm9StringRef7compareES0_", scope: !154, file: !155, line: 141, type: !220, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!220 = !DISubroutineType(types: !221)
!221 = !{!24, !199, !154}
!222 = !DISubprogram(name: "compare_lower", linkageName: "_ZNK4llvm9StringRef13compare_lowerES0_", scope: !154, file: !155, line: 153, type: !220, scopeLine: 153, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!223 = !DISubprogram(name: "compare_numeric", linkageName: "_ZNK4llvm9StringRef15compare_numericES0_", scope: !154, file: !155, line: 157, type: !220, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!224 = !DISubprogram(name: "edit_distance", linkageName: "_ZNK4llvm9StringRef13edit_distanceES0_bj", scope: !154, file: !155, line: 177, type: !225, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!225 = !DISubroutineType(types: !226)
!226 = !{!6, !199, !154, !132, !6}
!227 = !DISubprogram(name: "str", linkageName: "_ZNK4llvm9StringRef3strB5cxx11Ev", scope: !154, file: !155, line: 181, type: !228, scopeLine: 181, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!228 = !DISubroutineType(types: !229)
!229 = !{!189, !199}
!230 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm9StringRefixEm", scope: !154, file: !155, line: 190, type: !231, scopeLine: 190, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!231 = !DISubroutineType(types: !232)
!232 = !{!165, !199, !159}
!233 = !DISubprogram(name: "operator basic_string", linkageName: "_ZNK4llvm9StringRefcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv", scope: !154, file: !155, line: 199, type: !228, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!234 = !DISubprogram(name: "startswith", linkageName: "_ZNK4llvm9StringRef10startswithES0_", scope: !154, file: !155, line: 208, type: !216, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!235 = !DISubprogram(name: "startswith_lower", linkageName: "_ZNK4llvm9StringRef16startswith_lowerES0_", scope: !154, file: !155, line: 214, type: !216, scopeLine: 214, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!236 = !DISubprogram(name: "endswith", linkageName: "_ZNK4llvm9StringRef8endswithES0_", scope: !154, file: !155, line: 217, type: !216, scopeLine: 217, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!237 = !DISubprogram(name: "endswith_lower", linkageName: "_ZNK4llvm9StringRef14endswith_lowerES0_", scope: !154, file: !155, line: 223, type: !216, scopeLine: 223, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!238 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm9StringRef4findEcm", scope: !154, file: !155, line: 233, type: !239, scopeLine: 233, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!239 = !DISubroutineType(types: !240)
!240 = !{!159, !199, !165, !159}
!241 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm9StringRef4findES0_m", scope: !154, file: !155, line: 244, type: !242, scopeLine: 244, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!242 = !DISubroutineType(types: !243)
!243 = !{!159, !199, !154, !159}
!244 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm9StringRef5rfindEcm", scope: !154, file: !155, line: 250, type: !239, scopeLine: 250, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!245 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm9StringRef5rfindES0_", scope: !154, file: !155, line: 265, type: !246, scopeLine: 265, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!246 = !DISubroutineType(types: !247)
!247 = !{!159, !199, !154}
!248 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm9StringRef13find_first_ofEcm", scope: !154, file: !155, line: 269, type: !239, scopeLine: 269, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!249 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm9StringRef13find_first_ofES0_m", scope: !154, file: !155, line: 277, type: !242, scopeLine: 277, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!250 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm9StringRef17find_first_not_ofEcm", scope: !154, file: !155, line: 281, type: !239, scopeLine: 281, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!251 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm9StringRef17find_first_not_ofES0_m", scope: !154, file: !155, line: 287, type: !242, scopeLine: 287, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!252 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm9StringRef12find_last_ofEcm", scope: !154, file: !155, line: 291, type: !239, scopeLine: 291, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!253 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm9StringRef12find_last_ofES0_m", scope: !154, file: !155, line: 299, type: !242, scopeLine: 299, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!254 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNK4llvm9StringRef16find_last_not_ofEcm", scope: !154, file: !155, line: 303, type: !239, scopeLine: 303, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!255 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNK4llvm9StringRef16find_last_not_ofES0_m", scope: !154, file: !155, line: 309, type: !242, scopeLine: 309, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!256 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9StringRef5countEc", scope: !154, file: !155, line: 316, type: !257, scopeLine: 316, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!257 = !DISubroutineType(types: !258)
!258 = !{!159, !199, !165}
!259 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9StringRef5countES0_", scope: !154, file: !155, line: 326, type: !246, scopeLine: 326, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!260 = !DISubprogram(name: "getAsInteger", linkageName: "_ZNK4llvm9StringRef12getAsIntegerEjRNS_5APIntE", scope: !154, file: !155, line: 367, type: !261, scopeLine: 367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!261 = !DISubroutineType(types: !262)
!262 = !{!132, !199, !6, !263}
!263 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !264, size: 64)
!264 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "APInt", scope: !14, file: !155, line: 24, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm5APIntE")
!265 = !DISubprogram(name: "lower", linkageName: "_ZNK4llvm9StringRef5lowerB5cxx11Ev", scope: !154, file: !155, line: 374, type: !228, scopeLine: 374, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!266 = !DISubprogram(name: "upper", linkageName: "_ZNK4llvm9StringRef5upperB5cxx11Ev", scope: !154, file: !155, line: 377, type: !228, scopeLine: 377, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!267 = !DISubprogram(name: "substr", linkageName: "_ZNK4llvm9StringRef6substrEmm", scope: !154, file: !155, line: 392, type: !268, scopeLine: 392, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!268 = !DISubroutineType(types: !269)
!269 = !{!154, !199, !159, !159}
!270 = !DISubprogram(name: "drop_front", linkageName: "_ZNK4llvm9StringRef10drop_frontEm", scope: !154, file: !155, line: 399, type: !271, scopeLine: 399, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!271 = !DISubroutineType(types: !272)
!272 = !{!154, !199, !159}
!273 = !DISubprogram(name: "drop_back", linkageName: "_ZNK4llvm9StringRef9drop_backEm", scope: !154, file: !155, line: 406, type: !271, scopeLine: 406, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!274 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm9StringRef5sliceEmm", scope: !154, file: !155, line: 421, type: !268, scopeLine: 421, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!275 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitEc", scope: !154, file: !155, line: 437, type: !276, scopeLine: 437, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!276 = !DISubroutineType(types: !277)
!277 = !{!278, !199, !165}
!278 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::StringRef, llvm::StringRef>", scope: !192, file: !279, line: 208, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !280, templateParams: !340, identifier: "_ZTSSt4pairIN4llvm9StringRefES1_E")
!279 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_pair.h", directory: "", checksumkind: CSK_MD5, checksum: "9a7996187125e471e26ca57a6c9f4c5e")
!280 = !{!281, !301, !302, !303, !309, !313, !328, !337}
!281 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !278, baseType: !282, flags: DIFlagPrivate, extraData: i32 0)
!282 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::StringRef, llvm::StringRef>", scope: !192, file: !279, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !283, templateParams: !298, identifier: "_ZTSSt11__pair_baseIN4llvm9StringRefES1_E")
!283 = !{!284, !288, !289, !294}
!284 = !DISubprogram(name: "__pair_base", scope: !282, file: !279, line: 194, type: !285, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!285 = !DISubroutineType(types: !286)
!286 = !{null, !287}
!287 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !282, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!288 = !DISubprogram(name: "~__pair_base", scope: !282, file: !279, line: 195, type: !285, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!289 = !DISubprogram(name: "__pair_base", scope: !282, file: !279, line: 196, type: !290, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!290 = !DISubroutineType(types: !291)
!291 = !{null, !287, !292}
!292 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !293, size: 64)
!293 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !282)
!294 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN4llvm9StringRefES1_EaSERKS2_", scope: !282, file: !279, line: 197, type: !295, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!295 = !DISubroutineType(types: !296)
!296 = !{!297, !287, !292}
!297 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !282, size: 64)
!298 = !{!299, !300}
!299 = !DITemplateTypeParameter(name: "_U1", type: !154)
!300 = !DITemplateTypeParameter(name: "_U2", type: !154)
!301 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !278, file: !279, line: 214, baseType: !154, size: 128)
!302 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !278, file: !279, line: 215, baseType: !154, size: 128, offset: 128)
!303 = !DISubprogram(name: "pair", scope: !278, file: !279, line: 303, type: !304, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!304 = !DISubroutineType(types: !305)
!305 = !{null, !306, !307}
!306 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !278, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!307 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !308, size: 64)
!308 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !278)
!309 = !DISubprogram(name: "pair", scope: !278, file: !279, line: 304, type: !310, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!310 = !DISubroutineType(types: !311)
!311 = !{null, !306, !312}
!312 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !278, size: 64)
!313 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_EaSERKS2_", scope: !278, file: !279, line: 378, type: !314, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!314 = !DISubroutineType(types: !315)
!315 = !{!316, !306, !317}
!316 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !278, size: 64)
!317 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !319, file: !318, line: 1928, baseType: !307)
!318 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/type_traits", directory: "")
!319 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::StringRef, llvm::StringRef> &, const std::__nonesuch_no_braces &>", scope: !192, file: !318, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !321, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN4llvm9StringRefES2_ERKSt20__nonesuch_no_bracesE")
!320 = !{}
!321 = !{!322, !323, !324}
!322 = !DITemplateValueParameter(name: "_Cond", type: !132, value: i8 1)
!323 = !DITemplateTypeParameter(name: "_Iftrue", type: !307)
!324 = !DITemplateTypeParameter(name: "_Iffalse", type: !325)
!325 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !326, size: 64)
!326 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !327)
!327 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__nonesuch_no_braces", scope: !192, file: !279, line: 185, size: 8, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt20__nonesuch_no_braces")
!328 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_EaSEOS2_", scope: !278, file: !279, line: 389, type: !329, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!329 = !DISubroutineType(types: !330)
!330 = !{!316, !306, !331}
!331 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !332, file: !318, line: 1928, baseType: !312)
!332 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::StringRef, llvm::StringRef> &&, std::__nonesuch_no_braces &&>", scope: !192, file: !318, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !333, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN4llvm9StringRefES2_EOSt20__nonesuch_no_bracesE")
!333 = !{!322, !334, !335}
!334 = !DITemplateTypeParameter(name: "_Iftrue", type: !312)
!335 = !DITemplateTypeParameter(name: "_Iffalse", type: !336)
!336 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !327, size: 64)
!337 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_E4swapERS2_", scope: !278, file: !279, line: 424, type: !338, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!338 = !DISubroutineType(types: !339)
!339 = !{null, !306, !316}
!340 = !{!341, !342}
!341 = !DITemplateTypeParameter(name: "_T1", type: !154)
!342 = !DITemplateTypeParameter(name: "_T2", type: !154)
!343 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitES0_", scope: !154, file: !155, line: 454, type: !344, scopeLine: 454, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!344 = !DISubroutineType(types: !345)
!345 = !{!278, !199, !154}
!346 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitERNS_15SmallVectorImplIS0_EES0_ib", scope: !154, file: !155, line: 475, type: !347, scopeLine: 475, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!347 = !DISubroutineType(types: !348)
!348 = !{null, !199, !349, !154, !24, !132}
!349 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !350, size: 64)
!350 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<llvm::StringRef>", scope: !14, file: !155, line: 23, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm15SmallVectorImplINS_9StringRefEEE")
!351 = !DISubprogram(name: "rsplit", linkageName: "_ZNK4llvm9StringRef6rsplitEc", scope: !154, file: !155, line: 489, type: !276, scopeLine: 489, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!352 = !DISubprogram(name: "ltrim", linkageName: "_ZNK4llvm9StringRef5ltrimES0_", scope: !154, file: !155, line: 498, type: !353, scopeLine: 498, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!353 = !DISubroutineType(types: !354)
!354 = !{!154, !199, !154}
!355 = !DISubprogram(name: "rtrim", linkageName: "_ZNK4llvm9StringRef5rtrimES0_", scope: !154, file: !155, line: 504, type: !353, scopeLine: 504, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!356 = !DISubprogram(name: "trim", linkageName: "_ZNK4llvm9StringRef4trimES0_", scope: !154, file: !155, line: 510, type: !353, scopeLine: 510, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!357 = !DISubprogram(name: "beginMapping", linkageName: "_ZN4llvm4yaml2IO12beginMappingEv", scope: !113, file: !108, line: 335, type: !127, scopeLine: 335, containingType: !113, virtualIndex: 13, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!358 = !DISubprogram(name: "endMapping", linkageName: "_ZN4llvm4yaml2IO10endMappingEv", scope: !113, file: !108, line: 336, type: !127, scopeLine: 336, containingType: !113, virtualIndex: 14, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!359 = !DISubprogram(name: "preflightKey", linkageName: "_ZN4llvm4yaml2IO12preflightKeyEPKcbbRbRPv", scope: !113, file: !108, line: 337, type: !360, scopeLine: 337, containingType: !113, virtualIndex: 15, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!360 = !DISubroutineType(types: !361)
!361 = !{!132, !125, !163, !132, !132, !362, !141}
!362 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !132, size: 64)
!363 = !DISubprogram(name: "postflightKey", linkageName: "_ZN4llvm4yaml2IO13postflightKeyEPv", scope: !113, file: !108, line: 338, type: !123, scopeLine: 338, containingType: !113, virtualIndex: 16, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!364 = !DISubprogram(name: "beginEnumScalar", linkageName: "_ZN4llvm4yaml2IO15beginEnumScalarEv", scope: !113, file: !108, line: 340, type: !127, scopeLine: 340, containingType: !113, virtualIndex: 17, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!365 = !DISubprogram(name: "matchEnumScalar", linkageName: "_ZN4llvm4yaml2IO15matchEnumScalarEPKcb", scope: !113, file: !108, line: 341, type: !366, scopeLine: 341, containingType: !113, virtualIndex: 18, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!366 = !DISubroutineType(types: !367)
!367 = !{!132, !125, !163, !132}
!368 = !DISubprogram(name: "endEnumScalar", linkageName: "_ZN4llvm4yaml2IO13endEnumScalarEv", scope: !113, file: !108, line: 342, type: !127, scopeLine: 342, containingType: !113, virtualIndex: 19, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!369 = !DISubprogram(name: "beginBitSetScalar", linkageName: "_ZN4llvm4yaml2IO17beginBitSetScalarERb", scope: !113, file: !108, line: 344, type: !370, scopeLine: 344, containingType: !113, virtualIndex: 20, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!370 = !DISubroutineType(types: !371)
!371 = !{!132, !125, !362}
!372 = !DISubprogram(name: "bitSetMatch", linkageName: "_ZN4llvm4yaml2IO11bitSetMatchEPKcb", scope: !113, file: !108, line: 345, type: !366, scopeLine: 345, containingType: !113, virtualIndex: 21, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!373 = !DISubprogram(name: "endBitSetScalar", linkageName: "_ZN4llvm4yaml2IO15endBitSetScalarEv", scope: !113, file: !108, line: 346, type: !127, scopeLine: 346, containingType: !113, virtualIndex: 22, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!374 = !DISubprogram(name: "scalarString", linkageName: "_ZN4llvm4yaml2IO12scalarStringERNS_9StringRefE", scope: !113, file: !108, line: 348, type: !375, scopeLine: 348, containingType: !113, virtualIndex: 23, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!375 = !DISubroutineType(types: !376)
!376 = !{null, !125, !377}
!377 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !154, size: 64)
!378 = !DISubprogram(name: "setError", linkageName: "_ZN4llvm4yaml2IO8setErrorERKNS_5TwineE", scope: !113, file: !108, line: 350, type: !379, scopeLine: 350, containingType: !113, virtualIndex: 24, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!379 = !DISubroutineType(types: !380)
!380 = !{null, !125, !381}
!381 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !382, size: 64)
!382 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !383)
!383 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Twine", scope: !14, file: !384, line: 81, size: 192, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !385, identifier: "_ZTSN4llvm5TwineE")
!384 = !DIFile(filename: "llvm34/include/llvm/ADT/Twine.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "bc7908a6c9b9d5fa36f87d2503a3da7c")
!385 = !{!386, !421, !422, !424, !425, !445, !448, !451, !455, !456, !457, !458, !459, !460, !463, !464, !470, !471, !474, !477, !480, !484, !487, !491, !494, !497, !500, !504, !508, !512, !516, !519, !522, !525, !529, !530, !531, !534, !537, !754, !757, !760, !761, !764, !767, !768}
!386 = !DIDerivedType(tag: DW_TAG_member, name: "LHS", scope: !383, file: !384, line: 152, baseType: !387, size: 64)
!387 = distinct !DICompositeType(tag: DW_TAG_union_type, name: "Child", scope: !383, file: !384, line: 133, size: 64, flags: DIFlagTypePassByValue, elements: !388, identifier: "_ZTSN4llvm5Twine5ChildE")
!388 = !{!389, !391, !392, !394, !396, !397, !398, !399, !402, !406, !410, !414}
!389 = !DIDerivedType(tag: DW_TAG_member, name: "twine", scope: !387, file: !384, line: 135, baseType: !390, size: 64)
!390 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !382, size: 64)
!391 = !DIDerivedType(tag: DW_TAG_member, name: "cString", scope: !387, file: !384, line: 136, baseType: !163, size: 64)
!392 = !DIDerivedType(tag: DW_TAG_member, name: "stdString", scope: !387, file: !384, line: 137, baseType: !393, size: 64)
!393 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !188, size: 64)
!394 = !DIDerivedType(tag: DW_TAG_member, name: "stringRef", scope: !387, file: !384, line: 138, baseType: !395, size: 64)
!395 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !200, size: 64)
!396 = !DIDerivedType(tag: DW_TAG_member, name: "character", scope: !387, file: !384, line: 139, baseType: !165, size: 8)
!397 = !DIDerivedType(tag: DW_TAG_member, name: "decUI", scope: !387, file: !384, line: 140, baseType: !6, size: 32)
!398 = !DIDerivedType(tag: DW_TAG_member, name: "decI", scope: !387, file: !384, line: 141, baseType: !24, size: 32)
!399 = !DIDerivedType(tag: DW_TAG_member, name: "decUL", scope: !387, file: !384, line: 142, baseType: !400, size: 64)
!400 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !401, size: 64)
!401 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !161)
!402 = !DIDerivedType(tag: DW_TAG_member, name: "decL", scope: !387, file: !384, line: 143, baseType: !403, size: 64)
!403 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !404, size: 64)
!404 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !405)
!405 = !DIBasicType(name: "long", size: 64, encoding: DW_ATE_signed)
!406 = !DIDerivedType(tag: DW_TAG_member, name: "decULL", scope: !387, file: !384, line: 144, baseType: !407, size: 64)
!407 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !408, size: 64)
!408 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !409)
!409 = !DIBasicType(name: "unsigned long long", size: 64, encoding: DW_ATE_unsigned)
!410 = !DIDerivedType(tag: DW_TAG_member, name: "decLL", scope: !387, file: !384, line: 145, baseType: !411, size: 64)
!411 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !412, size: 64)
!412 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !413)
!413 = !DIBasicType(name: "long long", size: 64, encoding: DW_ATE_signed)
!414 = !DIDerivedType(tag: DW_TAG_member, name: "uHex", scope: !387, file: !384, line: 146, baseType: !415, size: 64)
!415 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !416, size: 64)
!416 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !417)
!417 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint64_t", file: !418, line: 27, baseType: !419)
!418 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h", directory: "", checksumkind: CSK_MD5, checksum: "9754ebe022edbe8d7928fa709e442f0d")
!419 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint64_t", file: !420, line: 44, baseType: !161)
!420 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types.h", directory: "", checksumkind: CSK_MD5, checksum: "25679ba19d359e314e48661b21f5aa1f")
!421 = !DIDerivedType(tag: DW_TAG_member, name: "RHS", scope: !383, file: !384, line: 155, baseType: !387, size: 64, offset: 64)
!422 = !DIDerivedType(tag: DW_TAG_member, name: "LHSKind", scope: !383, file: !384, line: 159, baseType: !423, size: 8, offset: 128)
!423 = !DIBasicType(name: "unsigned char", size: 8, encoding: DW_ATE_unsigned_char)
!424 = !DIDerivedType(tag: DW_TAG_member, name: "RHSKind", scope: !383, file: !384, line: 161, baseType: !423, size: 8, offset: 136)
!425 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 165, type: !426, scopeLine: 165, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!426 = !DISubroutineType(types: !427)
!427 = !{null, !428, !429}
!428 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !383, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!429 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "NodeKind", scope: !383, file: !384, line: 83, baseType: !6, size: 32, elements: !430, identifier: "_ZTSN4llvm5Twine8NodeKindE")
!430 = !{!431, !432, !433, !434, !435, !436, !437, !438, !439, !440, !441, !442, !443, !444}
!431 = !DIEnumerator(name: "NullKind", value: 0, isUnsigned: true)
!432 = !DIEnumerator(name: "EmptyKind", value: 1, isUnsigned: true)
!433 = !DIEnumerator(name: "TwineKind", value: 2, isUnsigned: true)
!434 = !DIEnumerator(name: "CStringKind", value: 3, isUnsigned: true)
!435 = !DIEnumerator(name: "StdStringKind", value: 4, isUnsigned: true)
!436 = !DIEnumerator(name: "StringRefKind", value: 5, isUnsigned: true)
!437 = !DIEnumerator(name: "CharKind", value: 6, isUnsigned: true)
!438 = !DIEnumerator(name: "DecUIKind", value: 7, isUnsigned: true)
!439 = !DIEnumerator(name: "DecIKind", value: 8, isUnsigned: true)
!440 = !DIEnumerator(name: "DecULKind", value: 9, isUnsigned: true)
!441 = !DIEnumerator(name: "DecLKind", value: 10, isUnsigned: true)
!442 = !DIEnumerator(name: "DecULLKind", value: 11, isUnsigned: true)
!443 = !DIEnumerator(name: "DecLLKind", value: 12, isUnsigned: true)
!444 = !DIEnumerator(name: "UHexKind", value: 13, isUnsigned: true)
!445 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 171, type: !446, scopeLine: 171, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!446 = !DISubroutineType(types: !447)
!447 = !{null, !428, !381, !381}
!448 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 179, type: !449, scopeLine: 179, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!449 = !DISubroutineType(types: !450)
!450 = !{null, !428, !387, !429, !387, !429}
!451 = !DISubprogram(name: "isNull", linkageName: "_ZNK4llvm5Twine6isNullEv", scope: !383, file: !384, line: 186, type: !452, scopeLine: 186, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!452 = !DISubroutineType(types: !453)
!453 = !{!132, !454}
!454 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !382, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!455 = !DISubprogram(name: "isEmpty", linkageName: "_ZNK4llvm5Twine7isEmptyEv", scope: !383, file: !384, line: 191, type: !452, scopeLine: 191, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!456 = !DISubprogram(name: "isNullary", linkageName: "_ZNK4llvm5Twine9isNullaryEv", scope: !383, file: !384, line: 196, type: !452, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!457 = !DISubprogram(name: "isUnary", linkageName: "_ZNK4llvm5Twine7isUnaryEv", scope: !383, file: !384, line: 201, type: !452, scopeLine: 201, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!458 = !DISubprogram(name: "isBinary", linkageName: "_ZNK4llvm5Twine8isBinaryEv", scope: !383, file: !384, line: 206, type: !452, scopeLine: 206, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!459 = !DISubprogram(name: "isValid", linkageName: "_ZNK4llvm5Twine7isValidEv", scope: !383, file: !384, line: 212, type: !452, scopeLine: 212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!460 = !DISubprogram(name: "getLHSKind", linkageName: "_ZNK4llvm5Twine10getLHSKindEv", scope: !383, file: !384, line: 237, type: !461, scopeLine: 237, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!461 = !DISubroutineType(types: !462)
!462 = !{!429, !454}
!463 = !DISubprogram(name: "getRHSKind", linkageName: "_ZNK4llvm5Twine10getRHSKindEv", scope: !383, file: !384, line: 240, type: !461, scopeLine: 240, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!464 = !DISubprogram(name: "printOneChild", linkageName: "_ZNK4llvm5Twine13printOneChildERNS_11raw_ostreamENS0_5ChildENS0_8NodeKindE", scope: !383, file: !384, line: 243, type: !465, scopeLine: 243, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!465 = !DISubroutineType(types: !466)
!466 = !{null, !454, !467, !387, !429}
!467 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !468, size: 64)
!468 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "raw_ostream", scope: !14, file: !469, line: 31, size: 320, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm11raw_ostreamE")
!469 = !DIFile(filename: "llvm34/include/llvm/Support/raw_ostream.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "2bb663449bd8797aa5193bb52a5154a0")
!470 = !DISubprogram(name: "printOneChildRepr", linkageName: "_ZNK4llvm5Twine17printOneChildReprERNS_11raw_ostreamENS0_5ChildENS0_8NodeKindE", scope: !383, file: !384, line: 246, type: !465, scopeLine: 246, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!471 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 254, type: !472, scopeLine: 254, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!472 = !DISubroutineType(types: !473)
!473 = !{null, !428}
!474 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 263, type: !475, scopeLine: 263, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!475 = !DISubroutineType(types: !476)
!476 = !{null, !428, !163}
!477 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 275, type: !478, scopeLine: 275, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!478 = !DISubroutineType(types: !479)
!479 = !{null, !428, !187}
!480 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 282, type: !481, scopeLine: 282, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!481 = !DISubroutineType(types: !482)
!482 = !{null, !428, !483}
!483 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !200, size: 64)
!484 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 289, type: !485, scopeLine: 289, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!485 = !DISubroutineType(types: !486)
!486 = !{null, !428, !165}
!487 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 295, type: !488, scopeLine: 295, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!488 = !DISubroutineType(types: !489)
!489 = !{null, !428, !490}
!490 = !DIBasicType(name: "signed char", size: 8, encoding: DW_ATE_signed_char)
!491 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 301, type: !492, scopeLine: 301, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!492 = !DISubroutineType(types: !493)
!493 = !{null, !428, !423}
!494 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 307, type: !495, scopeLine: 307, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!495 = !DISubroutineType(types: !496)
!496 = !{null, !428, !6}
!497 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 313, type: !498, scopeLine: 313, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!498 = !DISubroutineType(types: !499)
!499 = !{null, !428, !24}
!500 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 319, type: !501, scopeLine: 319, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!501 = !DISubroutineType(types: !502)
!502 = !{null, !428, !503}
!503 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !401, size: 64)
!504 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 325, type: !505, scopeLine: 325, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!505 = !DISubroutineType(types: !506)
!506 = !{null, !428, !507}
!507 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !404, size: 64)
!508 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 331, type: !509, scopeLine: 331, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!509 = !DISubroutineType(types: !510)
!510 = !{null, !428, !511}
!511 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !408, size: 64)
!512 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 337, type: !513, scopeLine: 337, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!513 = !DISubroutineType(types: !514)
!514 = !{null, !428, !515}
!515 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !412, size: 64)
!516 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 348, type: !517, scopeLine: 348, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!517 = !DISubroutineType(types: !518)
!518 = !{null, !428, !163, !483}
!519 = !DISubprogram(name: "Twine", scope: !383, file: !384, line: 356, type: !520, scopeLine: 356, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!520 = !DISubroutineType(types: !521)
!521 = !{null, !428, !483, !163}
!522 = !DISubprogram(name: "createNull", linkageName: "_ZN4llvm5Twine10createNullEv", scope: !383, file: !384, line: 365, type: !523, scopeLine: 365, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!523 = !DISubroutineType(types: !524)
!524 = !{!383}
!525 = !DISubprogram(name: "utohexstr", linkageName: "_ZN4llvm5Twine9utohexstrERKm", scope: !383, file: !384, line: 374, type: !526, scopeLine: 374, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!526 = !DISubroutineType(types: !527)
!527 = !{!383, !528}
!528 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !416, size: 64)
!529 = !DISubprogram(name: "isTriviallyEmpty", linkageName: "_ZNK4llvm5Twine16isTriviallyEmptyEv", scope: !383, file: !384, line: 387, type: !452, scopeLine: 387, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!530 = !DISubprogram(name: "isSingleStringRef", linkageName: "_ZNK4llvm5Twine17isSingleStringRefEv", scope: !383, file: !384, line: 393, type: !452, scopeLine: 393, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!531 = !DISubprogram(name: "concat", linkageName: "_ZNK4llvm5Twine6concatERKS0_", scope: !383, file: !384, line: 411, type: !532, scopeLine: 411, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!532 = !DISubroutineType(types: !533)
!533 = !{!383, !454, !381}
!534 = !DISubprogram(name: "str", linkageName: "_ZNK4llvm5Twine3strB5cxx11Ev", scope: !383, file: !384, line: 418, type: !535, scopeLine: 418, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!535 = !DISubroutineType(types: !536)
!536 = !{!189, !454}
!537 = !DISubprogram(name: "toVector", linkageName: "_ZNK4llvm5Twine8toVectorERNS_15SmallVectorImplIcEE", scope: !383, file: !384, line: 422, type: !538, scopeLine: 422, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!538 = !DISubroutineType(types: !539)
!539 = !{null, !454, !540}
!540 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !541, size: 64)
!541 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<char>", scope: !14, file: !542, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !543, templateParams: !753, identifier: "_ZTSN4llvm15SmallVectorImplIcEE")
!542 = !DIFile(filename: "llvm34/include/llvm/ADT/SmallVector.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "69b512a6e55455ea0ed3a25fbee45d45")
!543 = !{!544, !692, !698, !701, !704, !705, !706, !709, !710, !713, !716, !721, !722, !726, !729, !733, !736, !739, !742, !746, !750, !751, !752}
!544 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !541, baseType: !545, flags: DIFlagPublic, extraData: i32 0)
!545 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<char, true>", scope: !14, file: !542, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !546, templateParams: !690, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseIcLb1EEE")
!546 = !{!547, !676, !680, !683, !684, !687}
!547 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !545, baseType: !548, flags: DIFlagPublic, extraData: i32 0)
!548 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<char, void>", scope: !14, file: !542, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !549, templateParams: !673, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIcvEE")
!549 = !{!550, !572, !595, !599, !602, !607, !610, !614, !618, !622, !623, !624, !625, !626, !632, !637, !638, !639, !643, !644, !647, !651, !655, !660, !665, !668, !671, !672}
!550 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !548, baseType: !551, flags: DIFlagPublic, extraData: i32 0)
!551 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorBase", scope: !14, file: !542, line: 33, size: 192, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !552, identifier: "_ZTSN4llvm15SmallVectorBaseE")
!552 = !{!553, !554, !555, !556, !560, !563, !568, !569}
!553 = !DIDerivedType(tag: DW_TAG_member, name: "BeginX", scope: !551, file: !542, line: 35, baseType: !121, size: 64, flags: DIFlagProtected)
!554 = !DIDerivedType(tag: DW_TAG_member, name: "EndX", scope: !551, file: !542, line: 35, baseType: !121, size: 64, offset: 64, flags: DIFlagProtected)
!555 = !DIDerivedType(tag: DW_TAG_member, name: "CapacityX", scope: !551, file: !542, line: 35, baseType: !121, size: 64, offset: 128, flags: DIFlagProtected)
!556 = !DISubprogram(name: "SmallVectorBase", scope: !551, file: !542, line: 38, type: !557, scopeLine: 38, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!557 = !DISubroutineType(types: !558)
!558 = !{null, !559, !121, !159}
!559 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !551, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!560 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm15SmallVectorBase8grow_podEPvmm", scope: !551, file: !542, line: 43, type: !561, scopeLine: 43, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!561 = !DISubroutineType(types: !562)
!562 = !{null, !559, !121, !159, !159}
!563 = !DISubprogram(name: "size_in_bytes", linkageName: "_ZNK4llvm15SmallVectorBase13size_in_bytesEv", scope: !551, file: !542, line: 47, type: !564, scopeLine: 47, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!564 = !DISubroutineType(types: !565)
!565 = !{!159, !566}
!566 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !567, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!567 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !551)
!568 = !DISubprogram(name: "capacity_in_bytes", linkageName: "_ZNK4llvm15SmallVectorBase17capacity_in_bytesEv", scope: !551, file: !542, line: 52, type: !564, scopeLine: 52, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!569 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm15SmallVectorBase5emptyEv", scope: !551, file: !542, line: 56, type: !570, scopeLine: 56, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!570 = !DISubroutineType(types: !571)
!571 = !{!132, !566}
!572 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !548, file: !542, line: 74, baseType: !573, size: 8, offset: 192)
!573 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !548, file: !542, line: 73, baseType: !574)
!574 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<char, char, char, char, char, char, char>", scope: !14, file: !575, line: 199, size: 8, flags: DIFlagTypePassByValue, elements: !576, templateParams: !587, identifier: "_ZTSN4llvm21AlignedCharArrayUnionIcccccccEE")
!575 = !DIFile(filename: "llvm34/include/llvm/Support/AlignOf.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "55acc245b7ffca1b8660602cb703d9fb")
!576 = !{!577}
!577 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !574, baseType: !578, extraData: i32 0)
!578 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<1UL, 1UL>", scope: !14, file: !575, line: 75, size: 8, flags: DIFlagTypePassByValue, elements: !579, templateParams: !584, identifier: "_ZTSN4llvm16AlignedCharArrayILm1ELm1EEE")
!579 = !{!580}
!580 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !578, file: !575, line: 76, baseType: !581, size: 8, align: 8)
!581 = !DICompositeType(tag: DW_TAG_array_type, baseType: !165, size: 8, elements: !582)
!582 = !{!583}
!583 = !DISubrange(count: 1)
!584 = !{!585, !586}
!585 = !DITemplateValueParameter(name: "Alignment", type: !161, value: i64 1)
!586 = !DITemplateValueParameter(name: "Size", type: !161, value: i64 1)
!587 = !{!588, !589, !590, !591, !592, !593, !594}
!588 = !DITemplateTypeParameter(name: "T1", type: !165)
!589 = !DITemplateTypeParameter(name: "T2", type: !165, defaulted: true)
!590 = !DITemplateTypeParameter(name: "T3", type: !165, defaulted: true)
!591 = !DITemplateTypeParameter(name: "T4", type: !165, defaulted: true)
!592 = !DITemplateTypeParameter(name: "T5", type: !165, defaulted: true)
!593 = !DITemplateTypeParameter(name: "T6", type: !165, defaulted: true)
!594 = !DITemplateTypeParameter(name: "T7", type: !165, defaulted: true)
!595 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !548, file: !542, line: 78, type: !596, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!596 = !DISubroutineType(types: !597)
!597 = !{null, !598, !159}
!598 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !548, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!599 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE8grow_podEmm", scope: !548, file: !542, line: 80, type: !600, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!600 = !DISubroutineType(types: !601)
!601 = !{null, !598, !159, !159}
!602 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE7isSmallEv", scope: !548, file: !542, line: 86, type: !603, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!603 = !DISubroutineType(types: !604)
!604 = !{!132, !605}
!605 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !606, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!606 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !548)
!607 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE12resetToSmallEv", scope: !548, file: !542, line: 91, type: !608, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!608 = !DISubroutineType(types: !609)
!609 = !{null, !598}
!610 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE6setEndEPc", scope: !548, file: !542, line: 95, type: !611, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!611 = !DISubroutineType(types: !612)
!612 = !{null, !598, !613}
!613 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !165, size: 64)
!614 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE5beginEv", scope: !548, file: !542, line: 112, type: !615, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!615 = !DISubroutineType(types: !616)
!616 = !{!617, !598}
!617 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !548, file: !542, line: 100, baseType: !613)
!618 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE5beginEv", scope: !548, file: !542, line: 113, type: !619, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!619 = !DISubroutineType(types: !620)
!620 = !{!621, !605}
!621 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !548, file: !542, line: 101, baseType: !163)
!622 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE3endEv", scope: !548, file: !542, line: 114, type: !615, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!623 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE3endEv", scope: !548, file: !542, line: 115, type: !619, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!624 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE12capacity_ptrEv", scope: !548, file: !542, line: 117, type: !615, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!625 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE12capacity_ptrEv", scope: !548, file: !542, line: 118, type: !619, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!626 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE6rbeginEv", scope: !548, file: !542, line: 122, type: !627, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!627 = !DISubroutineType(types: !628)
!628 = !{!629, !598}
!629 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !548, file: !542, line: 104, baseType: !630)
!630 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<char *>", scope: !192, file: !631, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPcE")
!631 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_iterator.h", directory: "", checksumkind: CSK_MD5, checksum: "43ca426be47f2e0c5f7f184d7d27a436")
!632 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE6rbeginEv", scope: !548, file: !542, line: 123, type: !633, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!633 = !DISubroutineType(types: !634)
!634 = !{!635, !605}
!635 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !548, file: !542, line: 103, baseType: !636)
!636 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const char *>", scope: !192, file: !631, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKcE")
!637 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE4rendEv", scope: !548, file: !542, line: 124, type: !627, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!638 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE4rendEv", scope: !548, file: !542, line: 125, type: !633, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!639 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE4sizeEv", scope: !548, file: !542, line: 127, type: !640, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!640 = !DISubroutineType(types: !641)
!641 = !{!642, !605}
!642 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !542, line: 97, baseType: !159)
!643 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE8max_sizeEv", scope: !548, file: !542, line: 128, type: !640, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!644 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE8capacityEv", scope: !548, file: !542, line: 132, type: !645, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!645 = !DISubroutineType(types: !646)
!646 = !{!159, !605}
!647 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE4dataEv", scope: !548, file: !542, line: 135, type: !648, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!648 = !DISubroutineType(types: !649)
!649 = !{!650, !598}
!650 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !548, file: !542, line: 108, baseType: !613)
!651 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE4dataEv", scope: !548, file: !542, line: 137, type: !652, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!652 = !DISubroutineType(types: !653)
!653 = !{!654, !605}
!654 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !548, file: !542, line: 109, baseType: !163)
!655 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvEixEj", scope: !548, file: !542, line: 139, type: !656, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!656 = !DISubroutineType(types: !657)
!657 = !{!658, !598, !6}
!658 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !548, file: !542, line: 106, baseType: !659)
!659 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !165, size: 64)
!660 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvEixEj", scope: !548, file: !542, line: 143, type: !661, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!661 = !DISubroutineType(types: !662)
!662 = !{!663, !605, !6}
!663 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !548, file: !542, line: 107, baseType: !664)
!664 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !164, size: 64)
!665 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE5frontEv", scope: !548, file: !542, line: 148, type: !666, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!666 = !DISubroutineType(types: !667)
!667 = !{!658, !598}
!668 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE5frontEv", scope: !548, file: !542, line: 152, type: !669, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!669 = !DISubroutineType(types: !670)
!670 = !{!663, !605}
!671 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE4backEv", scope: !548, file: !542, line: 157, type: !666, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!672 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE4backEv", scope: !548, file: !542, line: 161, type: !669, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!673 = !{!674, !675}
!674 = !DITemplateTypeParameter(name: "T", type: !165)
!675 = !DITemplateTypeParameter(type: null, defaulted: true)
!676 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !545, file: !542, line: 298, type: !677, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!677 = !DISubroutineType(types: !678)
!678 = !{null, !679, !159}
!679 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !545, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!680 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIcLb1EE13destroy_rangeEPcS2_", scope: !545, file: !542, line: 301, type: !681, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!681 = !DISubroutineType(types: !682)
!682 = !{null, !613, !613}
!683 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIcLb1EE4growEm", scope: !545, file: !542, line: 346, type: !677, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!684 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIcLb1EE9push_backERKc", scope: !545, file: !542, line: 350, type: !685, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!685 = !DISubroutineType(types: !686)
!686 = !{null, !679, !664}
!687 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIcLb1EE8pop_backEv", scope: !545, file: !542, line: 361, type: !688, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!688 = !DISubroutineType(types: !689)
!689 = !{null, !679}
!690 = !{!674, !691}
!691 = !DITemplateValueParameter(name: "isPodLike", type: !132, value: i8 1)
!692 = !DISubprogram(name: "SmallVectorImpl", scope: !541, file: !542, line: 374, type: !693, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!693 = !DISubroutineType(types: !694)
!694 = !{null, !695, !696}
!695 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !541, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!696 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !697, size: 64)
!697 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !541)
!698 = !DISubprogram(name: "SmallVectorImpl", scope: !541, file: !542, line: 381, type: !699, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!699 = !DISubroutineType(types: !700)
!700 = !{null, !695, !6}
!701 = !DISubprogram(name: "~SmallVectorImpl", scope: !541, file: !542, line: 386, type: !702, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!702 = !DISubroutineType(types: !703)
!703 = !{null, !695}
!704 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplIcE5clearEv", scope: !541, file: !542, line: 396, type: !702, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!705 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIcE6resizeEj", scope: !541, file: !542, line: 401, type: !699, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!706 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIcE6resizeEjRKc", scope: !541, file: !542, line: 413, type: !707, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!707 = !DISubroutineType(types: !708)
!708 = !{null, !695, !6, !664}
!709 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplIcE7reserveEj", scope: !541, file: !542, line: 425, type: !699, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!710 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplIcE12pop_back_valEv", scope: !541, file: !542, line: 430, type: !711, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!711 = !DISubroutineType(types: !712)
!712 = !{!165, !695}
!713 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplIcE4swapERS1_", scope: !541, file: !542, line: 440, type: !714, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!714 = !DISubroutineType(types: !715)
!715 = !{null, !695, !540}
!716 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplIcE6appendEmRKc", scope: !541, file: !542, line: 460, type: !717, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!717 = !DISubroutineType(types: !718)
!718 = !{null, !695, !719, !664}
!719 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !541, file: !542, line: 377, baseType: !720)
!720 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !548, file: !542, line: 97, baseType: !159)
!721 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplIcE6assignEjRKc", scope: !541, file: !542, line: 470, type: !707, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!722 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIcE5eraseEPc", scope: !541, file: !542, line: 478, type: !723, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!723 = !DISubroutineType(types: !724)
!724 = !{!725, !695, !725}
!725 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !541, file: !542, line: 376, baseType: !617)
!726 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIcE5eraseEPcS2_", scope: !541, file: !542, line: 490, type: !727, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!727 = !DISubroutineType(types: !728)
!728 = !{!725, !695, !725, !725}
!729 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIcE6insertEPcOc", scope: !541, file: !542, line: 505, type: !730, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!730 = !DISubroutineType(types: !731)
!731 = !{!725, !695, !725, !732}
!732 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !165, size: 64)
!733 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIcE6insertEPcRKc", scope: !541, file: !542, line: 537, type: !734, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!734 = !DISubroutineType(types: !735)
!735 = !{!725, !695, !725, !664}
!736 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIcE6insertEPcmRKc", scope: !541, file: !542, line: 568, type: !737, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!737 = !DISubroutineType(types: !738)
!738 = !{!725, !695, !725, !719, !664}
!739 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIcEaSERKS1_", scope: !541, file: !542, line: 674, type: !740, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!740 = !DISubroutineType(types: !741)
!741 = !{!540, !695, !696}
!742 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIcEaSEOS1_", scope: !541, file: !542, line: 677, type: !743, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!743 = !DISubroutineType(types: !744)
!744 = !{!540, !695, !745}
!745 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !541, size: 64)
!746 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplIcEeqERKS1_", scope: !541, file: !542, line: 680, type: !747, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!747 = !DISubroutineType(types: !748)
!748 = !{!132, !749, !696}
!749 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !697, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!750 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplIcEneERKS1_", scope: !541, file: !542, line: 684, type: !747, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!751 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplIcEltERKS1_", scope: !541, file: !542, line: 688, type: !747, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!752 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplIcE8set_sizeEj", scope: !541, file: !542, line: 702, type: !699, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!753 = !{!674}
!754 = !DISubprogram(name: "getSingleStringRef", linkageName: "_ZNK4llvm5Twine18getSingleStringRefEv", scope: !383, file: !384, line: 426, type: !755, scopeLine: 426, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!755 = !DISubroutineType(types: !756)
!756 = !{!154, !454}
!757 = !DISubprogram(name: "toStringRef", linkageName: "_ZNK4llvm5Twine11toStringRefERNS_15SmallVectorImplIcEE", scope: !383, file: !384, line: 440, type: !758, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!758 = !DISubroutineType(types: !759)
!759 = !{!154, !454, !540}
!760 = !DISubprogram(name: "toNullTerminatedStringRef", linkageName: "_ZNK4llvm5Twine25toNullTerminatedStringRefERNS_15SmallVectorImplIcEE", scope: !383, file: !384, line: 448, type: !758, scopeLine: 448, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!761 = !DISubprogram(name: "print", linkageName: "_ZNK4llvm5Twine5printERNS_11raw_ostreamE", scope: !383, file: !384, line: 452, type: !762, scopeLine: 452, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!762 = !DISubroutineType(types: !763)
!763 = !{null, !454, !467}
!764 = !DISubprogram(name: "dump", linkageName: "_ZNK4llvm5Twine4dumpEv", scope: !383, file: !384, line: 455, type: !765, scopeLine: 455, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!765 = !DISubroutineType(types: !766)
!766 = !{null, !454}
!767 = !DISubprogram(name: "printRepr", linkageName: "_ZNK4llvm5Twine9printReprERNS_11raw_ostreamE", scope: !383, file: !384, line: 458, type: !762, scopeLine: 458, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!768 = !DISubprogram(name: "dumpRepr", linkageName: "_ZNK4llvm5Twine8dumpReprEv", scope: !383, file: !384, line: 461, type: !765, scopeLine: 461, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!769 = !DISubprogram(name: "getContext", linkageName: "_ZN4llvm4yaml2IO10getContextEv", scope: !113, file: !108, line: 382, type: !770, scopeLine: 382, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!770 = !DISubroutineType(types: !771)
!771 = !{!121, !125}
!772 = !DISubprogram(name: "setContext", linkageName: "_ZN4llvm4yaml2IO10setContextEPv", scope: !113, file: !108, line: 383, type: !123, scopeLine: 383, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!773 = !DIDerivedType(tag: DW_TAG_member, name: "Out", scope: !109, file: !108, line: 870, baseType: !467, size: 64, offset: 128)
!774 = !DIDerivedType(tag: DW_TAG_member, name: "StateStack", scope: !109, file: !108, line: 871, baseType: !775, size: 448, offset: 192)
!775 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<llvm::yaml::Output::InState, 8U>", scope: !14, file: !542, line: 880, size: 448, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !776, templateParams: !968, identifier: "_ZTSN4llvm11SmallVectorINS_4yaml6Output7InStateELj8EEE")
!776 = !{!777, !961, !970, !974, !977, !982, !985, !989}
!777 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !775, baseType: !778, flags: DIFlagPublic, extraData: i32 0)
!778 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<llvm::yaml::Output::InState>", scope: !14, file: !542, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !779, templateParams: !960, identifier: "_ZTSN4llvm15SmallVectorImplINS_4yaml6Output7InStateEEE")
!779 = !{!780, !898, !904, !907, !910, !911, !912, !915, !916, !919, !923, !928, !929, !933, !936, !940, !943, !946, !949, !953, !957, !958, !959}
!780 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !778, baseType: !781, flags: DIFlagPublic, extraData: i32 0)
!781 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<llvm::yaml::Output::InState, true>", scope: !14, file: !542, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !782, templateParams: !897, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseINS_4yaml6Output7InStateELb1EEE")
!782 = !{!783, !883, !887, !890, !891, !894}
!783 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !781, baseType: !784, flags: DIFlagPublic, extraData: i32 0)
!784 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<llvm::yaml::Output::InState, void>", scope: !14, file: !542, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !785, templateParams: !881, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvEE")
!785 = !{!786, !787, !803, !807, !810, !815, !818, !822, !826, !832, !833, !834, !835, !836, !841, !846, !847, !848, !851, !852, !855, !859, !863, !868, !873, !876, !879, !880}
!786 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !784, baseType: !551, flags: DIFlagPublic, extraData: i32 0)
!787 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !784, file: !542, line: 74, baseType: !788, size: 32, offset: 192)
!788 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !784, file: !542, line: 73, baseType: !789)
!789 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<llvm::yaml::Output::InState, char, char, char, char, char, char>", scope: !14, file: !575, line: 199, size: 32, flags: DIFlagTypePassByValue, elements: !790, templateParams: !801, identifier: "_ZTSN4llvm21AlignedCharArrayUnionINS_4yaml6Output7InStateEccccccEE")
!790 = !{!791}
!791 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !789, baseType: !792, extraData: i32 0)
!792 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<4UL, 4UL>", scope: !14, file: !575, line: 75, size: 32, flags: DIFlagTypePassByValue, elements: !793, templateParams: !798, identifier: "_ZTSN4llvm16AlignedCharArrayILm4ELm4EEE")
!793 = !{!794}
!794 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !792, file: !575, line: 76, baseType: !795, size: 32, align: 32)
!795 = !DICompositeType(tag: DW_TAG_array_type, baseType: !165, size: 32, elements: !796)
!796 = !{!797}
!797 = !DISubrange(count: 4)
!798 = !{!799, !800}
!799 = !DITemplateValueParameter(name: "Alignment", type: !161, value: i64 4)
!800 = !DITemplateValueParameter(name: "Size", type: !161, value: i64 4)
!801 = !{!802, !589, !590, !591, !592, !593, !594}
!802 = !DITemplateTypeParameter(name: "T1", type: !107)
!803 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !784, file: !542, line: 78, type: !804, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!804 = !DISubroutineType(types: !805)
!805 = !{null, !806, !159}
!806 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !784, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!807 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE8grow_podEmm", scope: !784, file: !542, line: 80, type: !808, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!808 = !DISubroutineType(types: !809)
!809 = !{null, !806, !159, !159}
!810 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE7isSmallEv", scope: !784, file: !542, line: 86, type: !811, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!811 = !DISubroutineType(types: !812)
!812 = !{!132, !813}
!813 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !814, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!814 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !784)
!815 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE12resetToSmallEv", scope: !784, file: !542, line: 91, type: !816, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!816 = !DISubroutineType(types: !817)
!817 = !{null, !806}
!818 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE6setEndEPS3_", scope: !784, file: !542, line: 95, type: !819, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!819 = !DISubroutineType(types: !820)
!820 = !{null, !806, !821}
!821 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !107, size: 64)
!822 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE5beginEv", scope: !784, file: !542, line: 112, type: !823, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!823 = !DISubroutineType(types: !824)
!824 = !{!825, !806}
!825 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !784, file: !542, line: 100, baseType: !821)
!826 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE5beginEv", scope: !784, file: !542, line: 113, type: !827, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!827 = !DISubroutineType(types: !828)
!828 = !{!829, !813}
!829 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !784, file: !542, line: 101, baseType: !830)
!830 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !831, size: 64)
!831 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !107)
!832 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE3endEv", scope: !784, file: !542, line: 114, type: !823, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!833 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE3endEv", scope: !784, file: !542, line: 115, type: !827, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!834 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE12capacity_ptrEv", scope: !784, file: !542, line: 117, type: !823, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!835 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE12capacity_ptrEv", scope: !784, file: !542, line: 118, type: !827, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!836 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE6rbeginEv", scope: !784, file: !542, line: 122, type: !837, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!837 = !DISubroutineType(types: !838)
!838 = !{!839, !806}
!839 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !784, file: !542, line: 104, baseType: !840)
!840 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<llvm::yaml::Output::InState *>", scope: !192, file: !631, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPN4llvm4yaml6Output7InStateEE")
!841 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE6rbeginEv", scope: !784, file: !542, line: 123, type: !842, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!842 = !DISubroutineType(types: !843)
!843 = !{!844, !813}
!844 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !784, file: !542, line: 103, baseType: !845)
!845 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const llvm::yaml::Output::InState *>", scope: !192, file: !631, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKN4llvm4yaml6Output7InStateEE")
!846 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE4rendEv", scope: !784, file: !542, line: 124, type: !837, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!847 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE4rendEv", scope: !784, file: !542, line: 125, type: !842, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!848 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE4sizeEv", scope: !784, file: !542, line: 127, type: !849, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!849 = !DISubroutineType(types: !850)
!850 = !{!642, !813}
!851 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE8max_sizeEv", scope: !784, file: !542, line: 128, type: !849, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!852 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE8capacityEv", scope: !784, file: !542, line: 132, type: !853, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!853 = !DISubroutineType(types: !854)
!854 = !{!159, !813}
!855 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE4dataEv", scope: !784, file: !542, line: 135, type: !856, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!856 = !DISubroutineType(types: !857)
!857 = !{!858, !806}
!858 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !784, file: !542, line: 108, baseType: !821)
!859 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE4dataEv", scope: !784, file: !542, line: 137, type: !860, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!860 = !DISubroutineType(types: !861)
!861 = !{!862, !813}
!862 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !784, file: !542, line: 109, baseType: !830)
!863 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvEixEj", scope: !784, file: !542, line: 139, type: !864, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!864 = !DISubroutineType(types: !865)
!865 = !{!866, !806, !6}
!866 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !784, file: !542, line: 106, baseType: !867)
!867 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !107, size: 64)
!868 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvEixEj", scope: !784, file: !542, line: 143, type: !869, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!869 = !DISubroutineType(types: !870)
!870 = !{!871, !813, !6}
!871 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !784, file: !542, line: 107, baseType: !872)
!872 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !831, size: 64)
!873 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE5frontEv", scope: !784, file: !542, line: 148, type: !874, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!874 = !DISubroutineType(types: !875)
!875 = !{!866, !806}
!876 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE5frontEv", scope: !784, file: !542, line: 152, type: !877, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!877 = !DISubroutineType(types: !878)
!878 = !{!871, !813}
!879 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE4backEv", scope: !784, file: !542, line: 157, type: !874, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!880 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_4yaml6Output7InStateEvE4backEv", scope: !784, file: !542, line: 161, type: !877, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!881 = !{!882, !675}
!882 = !DITemplateTypeParameter(name: "T", type: !107)
!883 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !781, file: !542, line: 298, type: !884, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!884 = !DISubroutineType(types: !885)
!885 = !{null, !886, !159}
!886 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !781, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!887 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseINS_4yaml6Output7InStateELb1EE13destroy_rangeEPS3_S5_", scope: !781, file: !542, line: 301, type: !888, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!888 = !DISubroutineType(types: !889)
!889 = !{null, !821, !821}
!890 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseINS_4yaml6Output7InStateELb1EE4growEm", scope: !781, file: !542, line: 346, type: !884, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!891 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseINS_4yaml6Output7InStateELb1EE9push_backERKS3_", scope: !781, file: !542, line: 350, type: !892, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!892 = !DISubroutineType(types: !893)
!893 = !{null, !886, !872}
!894 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseINS_4yaml6Output7InStateELb1EE8pop_backEv", scope: !781, file: !542, line: 361, type: !895, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!895 = !DISubroutineType(types: !896)
!896 = !{null, !886}
!897 = !{!882, !691}
!898 = !DISubprogram(name: "SmallVectorImpl", scope: !778, file: !542, line: 374, type: !899, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!899 = !DISubroutineType(types: !900)
!900 = !{null, !901, !902}
!901 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !778, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!902 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !903, size: 64)
!903 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !778)
!904 = !DISubprogram(name: "SmallVectorImpl", scope: !778, file: !542, line: 381, type: !905, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!905 = !DISubroutineType(types: !906)
!906 = !{null, !901, !6}
!907 = !DISubprogram(name: "~SmallVectorImpl", scope: !778, file: !542, line: 386, type: !908, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!908 = !DISubroutineType(types: !909)
!909 = !{null, !901}
!910 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEE5clearEv", scope: !778, file: !542, line: 396, type: !908, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!911 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEE6resizeEj", scope: !778, file: !542, line: 401, type: !905, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!912 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEE6resizeEjRKS3_", scope: !778, file: !542, line: 413, type: !913, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!913 = !DISubroutineType(types: !914)
!914 = !{null, !901, !6, !872}
!915 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEE7reserveEj", scope: !778, file: !542, line: 425, type: !905, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!916 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEE12pop_back_valEv", scope: !778, file: !542, line: 430, type: !917, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!917 = !DISubroutineType(types: !918)
!918 = !{!107, !901}
!919 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEE4swapERS4_", scope: !778, file: !542, line: 440, type: !920, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!920 = !DISubroutineType(types: !921)
!921 = !{null, !901, !922}
!922 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !778, size: 64)
!923 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEE6appendEmRKS3_", scope: !778, file: !542, line: 460, type: !924, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!924 = !DISubroutineType(types: !925)
!925 = !{null, !901, !926, !872}
!926 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !778, file: !542, line: 377, baseType: !927)
!927 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !784, file: !542, line: 97, baseType: !159)
!928 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEE6assignEjRKS3_", scope: !778, file: !542, line: 470, type: !913, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!929 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEE5eraseEPS3_", scope: !778, file: !542, line: 478, type: !930, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!930 = !DISubroutineType(types: !931)
!931 = !{!932, !901, !932}
!932 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !778, file: !542, line: 376, baseType: !825)
!933 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEE5eraseEPS3_S5_", scope: !778, file: !542, line: 490, type: !934, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!934 = !DISubroutineType(types: !935)
!935 = !{!932, !901, !932, !932}
!936 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEE6insertEPS3_OS3_", scope: !778, file: !542, line: 505, type: !937, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!937 = !DISubroutineType(types: !938)
!938 = !{!932, !901, !932, !939}
!939 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !107, size: 64)
!940 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEE6insertEPS3_RKS3_", scope: !778, file: !542, line: 537, type: !941, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!941 = !DISubroutineType(types: !942)
!942 = !{!932, !901, !932, !872}
!943 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEE6insertEPS3_mRKS3_", scope: !778, file: !542, line: 568, type: !944, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!944 = !DISubroutineType(types: !945)
!945 = !{!932, !901, !932, !926, !872}
!946 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEEaSERKS4_", scope: !778, file: !542, line: 674, type: !947, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!947 = !DISubroutineType(types: !948)
!948 = !{!922, !901, !902}
!949 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEEaSEOS4_", scope: !778, file: !542, line: 677, type: !950, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!950 = !DISubroutineType(types: !951)
!951 = !{!922, !901, !952}
!952 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !778, size: 64)
!953 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplINS_4yaml6Output7InStateEEeqERKS4_", scope: !778, file: !542, line: 680, type: !954, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!954 = !DISubroutineType(types: !955)
!955 = !{!132, !956, !902}
!956 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !903, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!957 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplINS_4yaml6Output7InStateEEneERKS4_", scope: !778, file: !542, line: 684, type: !954, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!958 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplINS_4yaml6Output7InStateEEltERKS4_", scope: !778, file: !542, line: 688, type: !954, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!959 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplINS_4yaml6Output7InStateEE8set_sizeEj", scope: !778, file: !542, line: 702, type: !905, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!960 = !{!882}
!961 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !775, file: !542, line: 882, baseType: !962, size: 224, offset: 224)
!962 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<llvm::yaml::Output::InState, 8U>", scope: !14, file: !542, line: 865, size: 224, flags: DIFlagTypePassByValue, elements: !963, templateParams: !968, identifier: "_ZTSN4llvm18SmallVectorStorageINS_4yaml6Output7InStateELj8EEE")
!963 = !{!964}
!964 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !962, file: !542, line: 866, baseType: !965, size: 224)
!965 = !DICompositeType(tag: DW_TAG_array_type, baseType: !788, size: 224, elements: !966)
!966 = !{!967}
!967 = !DISubrange(count: 7)
!968 = !{!882, !969}
!969 = !DITemplateValueParameter(name: "N", type: !6, value: i32 8)
!970 = !DISubprogram(name: "SmallVector", scope: !775, file: !542, line: 884, type: !971, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!971 = !DISubroutineType(types: !972)
!972 = !{null, !973}
!973 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !775, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!974 = !DISubprogram(name: "SmallVector", scope: !775, file: !542, line: 887, type: !975, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!975 = !DISubroutineType(types: !976)
!976 = !{null, !973, !6, !872}
!977 = !DISubprogram(name: "SmallVector", scope: !775, file: !542, line: 897, type: !978, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!978 = !DISubroutineType(types: !979)
!979 = !{null, !973, !980}
!980 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !981, size: 64)
!981 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !775)
!982 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorINS_4yaml6Output7InStateELj8EEaSERKS4_", scope: !775, file: !542, line: 902, type: !983, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!983 = !DISubroutineType(types: !984)
!984 = !{!980, !973, !980}
!985 = !DISubprogram(name: "SmallVector", scope: !775, file: !542, line: 908, type: !986, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!986 = !DISubroutineType(types: !987)
!987 = !{null, !973, !988}
!988 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !775, size: 64)
!989 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorINS_4yaml6Output7InStateELj8EEaSEOS4_", scope: !775, file: !542, line: 913, type: !990, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!990 = !DISubroutineType(types: !991)
!991 = !{!980, !973, !988}
!992 = !DIDerivedType(tag: DW_TAG_member, name: "Column", scope: !109, file: !108, line: 872, baseType: !24, size: 32, offset: 640)
!993 = !DIDerivedType(tag: DW_TAG_member, name: "ColumnAtFlowStart", scope: !109, file: !108, line: 873, baseType: !24, size: 32, offset: 672)
!994 = !DIDerivedType(tag: DW_TAG_member, name: "NeedBitValueComma", scope: !109, file: !108, line: 874, baseType: !132, size: 8, offset: 704)
!995 = !DIDerivedType(tag: DW_TAG_member, name: "NeedFlowSequenceComma", scope: !109, file: !108, line: 875, baseType: !132, size: 8, offset: 712)
!996 = !DIDerivedType(tag: DW_TAG_member, name: "EnumerationMatchFound", scope: !109, file: !108, line: 876, baseType: !132, size: 8, offset: 720)
!997 = !DIDerivedType(tag: DW_TAG_member, name: "NeedsNewLine", scope: !109, file: !108, line: 877, baseType: !132, size: 8, offset: 728)
!998 = !DISubprogram(name: "Output", scope: !109, file: !108, line: 825, type: !999, scopeLine: 825, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!999 = !DISubroutineType(types: !1000)
!1000 = !{null, !1001, !467, !121}
!1001 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !109, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1002 = !DISubprogram(name: "~Output", scope: !109, file: !108, line: 826, type: !1003, scopeLine: 826, containingType: !109, virtualIndex: 0, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1003 = !DISubroutineType(types: !1004)
!1004 = !{null, !1001}
!1005 = !DISubprogram(name: "classof", linkageName: "_ZN4llvm4yaml6Output7classofEPKNS0_2IOE", scope: !109, file: !108, line: 828, type: !1006, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1006 = !DISubroutineType(types: !1007)
!1007 = !{!132, !1008}
!1008 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !134, size: 64)
!1009 = !DISubprogram(name: "outputting", linkageName: "_ZNK4llvm4yaml6Output10outputtingEv", scope: !109, file: !108, line: 830, type: !1010, scopeLine: 830, containingType: !109, virtualIndex: 2, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1010 = !DISubroutineType(types: !1011)
!1011 = !{!132, !1012}
!1012 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1013, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1013 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !109)
!1014 = !DISubprogram(name: "mapTag", linkageName: "_ZN4llvm4yaml6Output6mapTagENS_9StringRefEb", scope: !109, file: !108, line: 831, type: !1015, scopeLine: 831, containingType: !109, virtualIndex: 12, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1015 = !DISubroutineType(types: !1016)
!1016 = !{!132, !1001, !154, !132}
!1017 = !DISubprogram(name: "beginMapping", linkageName: "_ZN4llvm4yaml6Output12beginMappingEv", scope: !109, file: !108, line: 832, type: !1003, scopeLine: 832, containingType: !109, virtualIndex: 13, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1018 = !DISubprogram(name: "endMapping", linkageName: "_ZN4llvm4yaml6Output10endMappingEv", scope: !109, file: !108, line: 833, type: !1003, scopeLine: 833, containingType: !109, virtualIndex: 14, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1019 = !DISubprogram(name: "preflightKey", linkageName: "_ZN4llvm4yaml6Output12preflightKeyEPKcbbRbRPv", scope: !109, file: !108, line: 834, type: !1020, scopeLine: 834, containingType: !109, virtualIndex: 15, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1020 = !DISubroutineType(types: !1021)
!1021 = !{!132, !1001, !163, !132, !132, !362, !141}
!1022 = !DISubprogram(name: "postflightKey", linkageName: "_ZN4llvm4yaml6Output13postflightKeyEPv", scope: !109, file: !108, line: 835, type: !1023, scopeLine: 835, containingType: !109, virtualIndex: 16, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1023 = !DISubroutineType(types: !1024)
!1024 = !{null, !1001, !121}
!1025 = !DISubprogram(name: "beginSequence", linkageName: "_ZN4llvm4yaml6Output13beginSequenceEv", scope: !109, file: !108, line: 836, type: !1026, scopeLine: 836, containingType: !109, virtualIndex: 3, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1026 = !DISubroutineType(types: !1027)
!1027 = !{!6, !1001}
!1028 = !DISubprogram(name: "endSequence", linkageName: "_ZN4llvm4yaml6Output11endSequenceEv", scope: !109, file: !108, line: 837, type: !1003, scopeLine: 837, containingType: !109, virtualIndex: 6, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1029 = !DISubprogram(name: "preflightElement", linkageName: "_ZN4llvm4yaml6Output16preflightElementEjRPv", scope: !109, file: !108, line: 838, type: !1030, scopeLine: 838, containingType: !109, virtualIndex: 4, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1030 = !DISubroutineType(types: !1031)
!1031 = !{!132, !1001, !6, !141}
!1032 = !DISubprogram(name: "postflightElement", linkageName: "_ZN4llvm4yaml6Output17postflightElementEPv", scope: !109, file: !108, line: 839, type: !1023, scopeLine: 839, containingType: !109, virtualIndex: 5, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1033 = !DISubprogram(name: "beginFlowSequence", linkageName: "_ZN4llvm4yaml6Output17beginFlowSequenceEv", scope: !109, file: !108, line: 840, type: !1026, scopeLine: 840, containingType: !109, virtualIndex: 8, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1034 = !DISubprogram(name: "preflightFlowElement", linkageName: "_ZN4llvm4yaml6Output20preflightFlowElementEjRPv", scope: !109, file: !108, line: 841, type: !1030, scopeLine: 841, containingType: !109, virtualIndex: 9, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1035 = !DISubprogram(name: "postflightFlowElement", linkageName: "_ZN4llvm4yaml6Output21postflightFlowElementEPv", scope: !109, file: !108, line: 842, type: !1023, scopeLine: 842, containingType: !109, virtualIndex: 10, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1036 = !DISubprogram(name: "endFlowSequence", linkageName: "_ZN4llvm4yaml6Output15endFlowSequenceEv", scope: !109, file: !108, line: 843, type: !1003, scopeLine: 843, containingType: !109, virtualIndex: 11, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1037 = !DISubprogram(name: "beginEnumScalar", linkageName: "_ZN4llvm4yaml6Output15beginEnumScalarEv", scope: !109, file: !108, line: 844, type: !1003, scopeLine: 844, containingType: !109, virtualIndex: 17, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1038 = !DISubprogram(name: "matchEnumScalar", linkageName: "_ZN4llvm4yaml6Output15matchEnumScalarEPKcb", scope: !109, file: !108, line: 845, type: !1039, scopeLine: 845, containingType: !109, virtualIndex: 18, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1039 = !DISubroutineType(types: !1040)
!1040 = !{!132, !1001, !163, !132}
!1041 = !DISubprogram(name: "endEnumScalar", linkageName: "_ZN4llvm4yaml6Output13endEnumScalarEv", scope: !109, file: !108, line: 846, type: !1003, scopeLine: 846, containingType: !109, virtualIndex: 19, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1042 = !DISubprogram(name: "beginBitSetScalar", linkageName: "_ZN4llvm4yaml6Output17beginBitSetScalarERb", scope: !109, file: !108, line: 847, type: !1043, scopeLine: 847, containingType: !109, virtualIndex: 20, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1043 = !DISubroutineType(types: !1044)
!1044 = !{!132, !1001, !362}
!1045 = !DISubprogram(name: "bitSetMatch", linkageName: "_ZN4llvm4yaml6Output11bitSetMatchEPKcb", scope: !109, file: !108, line: 848, type: !1039, scopeLine: 848, containingType: !109, virtualIndex: 21, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1046 = !DISubprogram(name: "endBitSetScalar", linkageName: "_ZN4llvm4yaml6Output15endBitSetScalarEv", scope: !109, file: !108, line: 849, type: !1003, scopeLine: 849, containingType: !109, virtualIndex: 22, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1047 = !DISubprogram(name: "scalarString", linkageName: "_ZN4llvm4yaml6Output12scalarStringERNS_9StringRefE", scope: !109, file: !108, line: 850, type: !1048, scopeLine: 850, containingType: !109, virtualIndex: 23, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1048 = !DISubroutineType(types: !1049)
!1049 = !{null, !1001, !377}
!1050 = !DISubprogram(name: "setError", linkageName: "_ZN4llvm4yaml6Output8setErrorERKNS_5TwineE", scope: !109, file: !108, line: 851, type: !1051, scopeLine: 851, containingType: !109, virtualIndex: 24, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1051 = !DISubroutineType(types: !1052)
!1052 = !{null, !1001, !381}
!1053 = !DISubprogram(name: "canElideEmptySequence", linkageName: "_ZN4llvm4yaml6Output21canElideEmptySequenceEv", scope: !109, file: !108, line: 852, type: !1054, scopeLine: 852, containingType: !109, virtualIndex: 7, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1054 = !DISubroutineType(types: !1055)
!1055 = !{!132, !1001}
!1056 = !DISubprogram(name: "beginDocuments", linkageName: "_ZN4llvm4yaml6Output14beginDocumentsEv", scope: !109, file: !108, line: 856, type: !1003, scopeLine: 856, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1057 = !DISubprogram(name: "preflightDocument", linkageName: "_ZN4llvm4yaml6Output17preflightDocumentEj", scope: !109, file: !108, line: 857, type: !1058, scopeLine: 857, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1058 = !DISubroutineType(types: !1059)
!1059 = !{!132, !1001, !6}
!1060 = !DISubprogram(name: "postflightDocument", linkageName: "_ZN4llvm4yaml6Output18postflightDocumentEv", scope: !109, file: !108, line: 858, type: !1003, scopeLine: 858, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1061 = !DISubprogram(name: "endDocuments", linkageName: "_ZN4llvm4yaml6Output12endDocumentsEv", scope: !109, file: !108, line: 859, type: !1003, scopeLine: 859, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1062 = !DISubprogram(name: "output", linkageName: "_ZN4llvm4yaml6Output6outputENS_9StringRefE", scope: !109, file: !108, line: 862, type: !1063, scopeLine: 862, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1063 = !DISubroutineType(types: !1064)
!1064 = !{null, !1001, !154}
!1065 = !DISubprogram(name: "outputUpToEndOfLine", linkageName: "_ZN4llvm4yaml6Output19outputUpToEndOfLineENS_9StringRefE", scope: !109, file: !108, line: 863, type: !1063, scopeLine: 863, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1066 = !DISubprogram(name: "newLineCheck", linkageName: "_ZN4llvm4yaml6Output12newLineCheckEv", scope: !109, file: !108, line: 864, type: !1003, scopeLine: 864, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1067 = !DISubprogram(name: "outputNewLine", linkageName: "_ZN4llvm4yaml6Output13outputNewLineEv", scope: !109, file: !108, line: 865, type: !1003, scopeLine: 865, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1068 = !DISubprogram(name: "paddedKey", linkageName: "_ZN4llvm4yaml6Output9paddedKeyENS_9StringRefE", scope: !109, file: !108, line: 866, type: !1063, scopeLine: 866, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1069 = !{!1070, !1071, !1072, !1073}
!1070 = !DIEnumerator(name: "inSeq", value: 0, isUnsigned: true)
!1071 = !DIEnumerator(name: "inFlowSeq", value: 1, isUnsigned: true)
!1072 = !DIEnumerator(name: "inMapFirstKey", value: 2, isUnsigned: true)
!1073 = !DIEnumerator(name: "inMapOtherKey", value: 3, isUnsigned: true)
!1074 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "DiagKind", scope: !1076, file: !1075, line: 37, baseType: !6, size: 32, elements: !2322, identifier: "_ZTSN4llvm9SourceMgr8DiagKindE")
!1075 = !DIFile(filename: "llvm34/include/llvm/Support/SourceMgr.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "7205ff9d743eab395e61aa4c578f38b5")
!1076 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SourceMgr", scope: !14, file: !1075, line: 35, size: 576, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1077, identifier: "_ZTSN4llvm9SourceMgrE")
!1077 = !{!1078, !1558, !2035, !2036, !2044, !2045, !2051, !2052, !2055, !2056, !2059, !2062, !2066, !2069, !2072, !2077, !2080, !2083, !2086, !2090, !2093, !2096, !2154, !2313, !2316, !2319}
!1078 = !DIDerivedType(tag: DW_TAG_member, name: "Buffers", scope: !1076, file: !1075, line: 58, baseType: !1079, size: 192)
!1079 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<llvm::SourceMgr::SrcBuffer, std::allocator<llvm::SourceMgr::SrcBuffer> >", scope: !192, file: !1080, line: 339, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1081, templateParams: !1278, identifier: "_ZTSSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE")
!1080 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h", directory: "", checksumkind: CSK_MD5, checksum: "ba305a1e10d49c66b3a70acbb63616a6")
!1081 = !{!1082, !1279, !1283, !1289, !1293, !1299, !1304, !1308, !1311, !1314, !1319, !1320, !1324, !1327, !1330, !1333, !1336, !1396, !1402, !1403, !1404, !1409, !1414, !1415, !1416, !1417, !1418, !1419, !1420, !1423, !1424, !1427, !1428, !1429, !1430, !1433, !1434, !1442, !1449, !1452, !1453, !1454, !1457, !1460, !1461, !1462, !1465, !1468, !1471, !1475, !1476, !1479, !1482, !1485, !1488, !1491, !1494, !1497, !1498, !1499, !1500, !1501, !1504, !1505, !1508, !1509, !1510, !1514, !1518, !1521, !1524, !1542}
!1082 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1079, baseType: !1083, flags: DIFlagProtected, extraData: i32 0)
!1083 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_base<llvm::SourceMgr::SrcBuffer, std::allocator<llvm::SourceMgr::SrcBuffer> >", scope: !192, file: !1080, line: 81, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1084, templateParams: !1278, identifier: "_ZTSSt12_Vector_baseIN4llvm9SourceMgr9SrcBufferESaIS2_EE")
!1084 = !{!1085, !1232, !1237, !1242, !1246, !1249, !1254, !1257, !1260, !1263, !1267, !1270, !1271, !1274, !1277}
!1085 = !DIDerivedType(tag: DW_TAG_member, name: "_M_impl", scope: !1083, file: !1080, line: 290, baseType: !1086, size: 192)
!1086 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_impl", scope: !1083, file: !1080, line: 88, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1087, identifier: "_ZTSNSt12_Vector_baseIN4llvm9SourceMgr9SrcBufferESaIS2_EE12_Vector_implE")
!1087 = !{!1088, !1210, !1213, !1214, !1215, !1219, !1224, !1228}
!1088 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1086, baseType: !1089, extraData: i32 0)
!1089 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Tp_alloc_type", scope: !1083, file: !1080, line: 84, baseType: !1090)
!1090 = !DIDerivedType(tag: DW_TAG_typedef, name: "other", scope: !1092, file: !1091, line: 117, baseType: !1209)
!1091 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/alloc_traits.h", directory: "")
!1092 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "rebind<llvm::SourceMgr::SrcBuffer>", scope: !1093, file: !1091, line: 116, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !1162, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIN4llvm9SourceMgr9SrcBufferEES3_E6rebindIS3_EE")
!1093 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__alloc_traits<std::allocator<llvm::SourceMgr::SrcBuffer>, llvm::SourceMgr::SrcBuffer>", scope: !5, file: !1091, line: 50, size: 8, flags: DIFlagTypePassByValue, elements: !1094, templateParams: !1207, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIN4llvm9SourceMgr9SrcBufferEES3_EE")
!1094 = !{!1095, !1193, !1196, !1200, !1203, !1204, !1205, !1206}
!1095 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1093, baseType: !1096, extraData: i32 0)
!1096 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "allocator_traits<std::allocator<llvm::SourceMgr::SrcBuffer> >", scope: !192, file: !1097, line: 384, size: 8, flags: DIFlagTypePassByValue, elements: !1098, templateParams: !1191, identifier: "_ZTSSt16allocator_traitsISaIN4llvm9SourceMgr9SrcBufferEEE")
!1097 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/alloc_traits.h", directory: "", checksumkind: CSK_MD5, checksum: "f7f651aab55acaadfc53aa53979a817c")
!1098 = !{!1099, !1175, !1179, !1182, !1188}
!1099 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIN4llvm9SourceMgr9SrcBufferEEE8allocateERS3_m", scope: !1096, file: !1097, line: 435, type: !1100, scopeLine: 435, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1100 = !DISubroutineType(types: !1101)
!1101 = !{!1102, !1112, !1174}
!1102 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1096, file: !1097, line: 392, baseType: !1103)
!1103 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1104, size: 64)
!1104 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SrcBuffer", scope: !1076, file: !1075, line: 48, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1105, identifier: "_ZTSN4llvm9SourceMgr9SrcBufferE")
!1105 = !{!1106, !1109}
!1106 = !DIDerivedType(tag: DW_TAG_member, name: "Buffer", scope: !1104, file: !1075, line: 50, baseType: !1107, size: 64)
!1107 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1108, size: 64)
!1108 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MemoryBuffer", scope: !14, file: !1075, line: 26, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12MemoryBufferE")
!1109 = !DIDerivedType(tag: DW_TAG_member, name: "IncludeLoc", scope: !1104, file: !1075, line: 54, baseType: !1110, size: 64, offset: 64)
!1110 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SMLoc", scope: !14, file: !1111, line: 23, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm5SMLocE")
!1111 = !DIFile(filename: "llvm34/include/llvm/Support/SMLoc.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "4c0f0aff440775fb973f85582fd92b78")
!1112 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1113, size: 64)
!1113 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !1096, file: !1097, line: 387, baseType: !1114)
!1114 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "allocator<llvm::SourceMgr::SrcBuffer>", scope: !192, file: !1115, line: 108, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1116, templateParams: !1162, identifier: "_ZTSSaIN4llvm9SourceMgr9SrcBufferEE")
!1115 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "9cafc7b584300736771313d46be845c3")
!1116 = !{!1117, !1164, !1168, !1173}
!1117 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1114, baseType: !1118, flags: DIFlagPublic, extraData: i32 0)
!1118 = !DIDerivedType(tag: DW_TAG_typedef, name: "__allocator_base<llvm::SourceMgr::SrcBuffer>", scope: !192, file: !1119, line: 48, baseType: !1120)
!1119 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8/bits/c++allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "9572fa47638d84b83d0311676a9766b8")
!1120 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "new_allocator<llvm::SourceMgr::SrcBuffer>", scope: !5, file: !1121, line: 58, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1122, templateParams: !1162, identifier: "_ZTSN9__gnu_cxx13new_allocatorIN4llvm9SourceMgr9SrcBufferEEE")
!1121 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/new_allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "ece13daf300dfc0cac27dc2ea29129ca")
!1122 = !{!1123, !1127, !1132, !1133, !1140, !1148, !1156, !1159}
!1123 = !DISubprogram(name: "new_allocator", scope: !1120, file: !1121, line: 79, type: !1124, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1124 = !DISubroutineType(types: !1125)
!1125 = !{null, !1126}
!1126 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1120, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1127 = !DISubprogram(name: "new_allocator", scope: !1120, file: !1121, line: 81, type: !1128, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1128 = !DISubroutineType(types: !1129)
!1129 = !{null, !1126, !1130}
!1130 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1131, size: 64)
!1131 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1120)
!1132 = !DISubprogram(name: "~new_allocator", scope: !1120, file: !1121, line: 86, type: !1124, scopeLine: 86, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1133 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorIN4llvm9SourceMgr9SrcBufferEE7addressERS3_", scope: !1120, file: !1121, line: 89, type: !1134, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1134 = !DISubroutineType(types: !1135)
!1135 = !{!1136, !1137, !1138}
!1136 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1120, file: !1121, line: 63, baseType: !1103)
!1137 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1131, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1138 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1120, file: !1121, line: 65, baseType: !1139)
!1139 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1104, size: 64)
!1140 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorIN4llvm9SourceMgr9SrcBufferEE7addressERKS3_", scope: !1120, file: !1121, line: 93, type: !1141, scopeLine: 93, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1141 = !DISubroutineType(types: !1142)
!1142 = !{!1143, !1137, !1146}
!1143 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !1120, file: !1121, line: 64, baseType: !1144)
!1144 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1145, size: 64)
!1145 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1104)
!1146 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1120, file: !1121, line: 66, baseType: !1147)
!1147 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1145, size: 64)
!1148 = !DISubprogram(name: "allocate", linkageName: "_ZN9__gnu_cxx13new_allocatorIN4llvm9SourceMgr9SrcBufferEE8allocateEmPKv", scope: !1120, file: !1121, line: 99, type: !1149, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1149 = !DISubroutineType(types: !1150)
!1150 = !{!1136, !1126, !1151, !1154}
!1151 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !1121, line: 61, baseType: !1152)
!1152 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", scope: !192, file: !1153, line: 238, baseType: !161)
!1153 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8/bits/c++config.h", directory: "", checksumkind: CSK_MD5, checksum: "5ab2830680f5a52514c973f039a03c0a")
!1154 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1155, size: 64)
!1155 = !DIDerivedType(tag: DW_TAG_const_type, baseType: null)
!1156 = !DISubprogram(name: "deallocate", linkageName: "_ZN9__gnu_cxx13new_allocatorIN4llvm9SourceMgr9SrcBufferEE10deallocateEPS3_m", scope: !1120, file: !1121, line: 116, type: !1157, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1157 = !DISubroutineType(types: !1158)
!1158 = !{null, !1126, !1136, !1151}
!1159 = !DISubprogram(name: "max_size", linkageName: "_ZNK9__gnu_cxx13new_allocatorIN4llvm9SourceMgr9SrcBufferEE8max_sizeEv", scope: !1120, file: !1121, line: 129, type: !1160, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1160 = !DISubroutineType(types: !1161)
!1161 = !{!1151, !1137}
!1162 = !{!1163}
!1163 = !DITemplateTypeParameter(name: "_Tp", type: !1104)
!1164 = !DISubprogram(name: "allocator", scope: !1114, file: !1115, line: 131, type: !1165, scopeLine: 131, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1165 = !DISubroutineType(types: !1166)
!1166 = !{null, !1167}
!1167 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1114, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1168 = !DISubprogram(name: "allocator", scope: !1114, file: !1115, line: 133, type: !1169, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1169 = !DISubroutineType(types: !1170)
!1170 = !{null, !1167, !1171}
!1171 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1172, size: 64)
!1172 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1114)
!1173 = !DISubprogram(name: "~allocator", scope: !1114, file: !1115, line: 139, type: !1165, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1174 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !1097, line: 407, baseType: !1152)
!1175 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIN4llvm9SourceMgr9SrcBufferEEE8allocateERS3_mPKv", scope: !1096, file: !1097, line: 449, type: !1176, scopeLine: 449, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1176 = !DISubroutineType(types: !1177)
!1177 = !{!1102, !1112, !1174, !1178}
!1178 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_void_pointer", file: !1097, line: 401, baseType: !1154)
!1179 = !DISubprogram(name: "deallocate", linkageName: "_ZNSt16allocator_traitsISaIN4llvm9SourceMgr9SrcBufferEEE10deallocateERS3_PS2_m", scope: !1096, file: !1097, line: 461, type: !1180, scopeLine: 461, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1180 = !DISubroutineType(types: !1181)
!1181 = !{null, !1112, !1102, !1174}
!1182 = !DISubprogram(name: "max_size", linkageName: "_ZNSt16allocator_traitsISaIN4llvm9SourceMgr9SrcBufferEEE8max_sizeERKS3_", scope: !1096, file: !1097, line: 495, type: !1183, scopeLine: 495, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1183 = !DISubroutineType(types: !1184)
!1184 = !{!1185, !1186}
!1185 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1096, file: !1097, line: 407, baseType: !1152)
!1186 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1187, size: 64)
!1187 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1113)
!1188 = !DISubprogram(name: "select_on_container_copy_construction", linkageName: "_ZNSt16allocator_traitsISaIN4llvm9SourceMgr9SrcBufferEEE37select_on_container_copy_constructionERKS3_", scope: !1096, file: !1097, line: 504, type: !1189, scopeLine: 504, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1189 = !DISubroutineType(types: !1190)
!1190 = !{!1113, !1186}
!1191 = !{!1192}
!1192 = !DITemplateTypeParameter(name: "_Alloc", type: !1114)
!1193 = !DISubprogram(name: "_S_select_on_copy", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIN4llvm9SourceMgr9SrcBufferEES3_E17_S_select_on_copyERKS4_", scope: !1093, file: !1091, line: 94, type: !1194, scopeLine: 94, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1194 = !DISubroutineType(types: !1195)
!1195 = !{!1114, !1171}
!1196 = !DISubprogram(name: "_S_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIN4llvm9SourceMgr9SrcBufferEES3_E10_S_on_swapERS4_S6_", scope: !1093, file: !1091, line: 97, type: !1197, scopeLine: 97, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1197 = !DISubroutineType(types: !1198)
!1198 = !{null, !1199, !1199}
!1199 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1114, size: 64)
!1200 = !DISubprogram(name: "_S_propagate_on_copy_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIN4llvm9SourceMgr9SrcBufferEES3_E27_S_propagate_on_copy_assignEv", scope: !1093, file: !1091, line: 100, type: !1201, scopeLine: 100, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1201 = !DISubroutineType(types: !1202)
!1202 = !{!132}
!1203 = !DISubprogram(name: "_S_propagate_on_move_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIN4llvm9SourceMgr9SrcBufferEES3_E27_S_propagate_on_move_assignEv", scope: !1093, file: !1091, line: 103, type: !1201, scopeLine: 103, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1204 = !DISubprogram(name: "_S_propagate_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIN4llvm9SourceMgr9SrcBufferEES3_E20_S_propagate_on_swapEv", scope: !1093, file: !1091, line: 106, type: !1201, scopeLine: 106, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1205 = !DISubprogram(name: "_S_always_equal", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIN4llvm9SourceMgr9SrcBufferEES3_E15_S_always_equalEv", scope: !1093, file: !1091, line: 109, type: !1201, scopeLine: 109, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1206 = !DISubprogram(name: "_S_nothrow_move", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIN4llvm9SourceMgr9SrcBufferEES3_E15_S_nothrow_moveEv", scope: !1093, file: !1091, line: 112, type: !1201, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1207 = !{!1192, !1208}
!1208 = !DITemplateTypeParameter(type: !1104)
!1209 = !DIDerivedType(tag: DW_TAG_typedef, name: "rebind_alloc<llvm::SourceMgr::SrcBuffer>", scope: !1096, file: !1097, line: 422, baseType: !1114)
!1210 = !DIDerivedType(tag: DW_TAG_member, name: "_M_start", scope: !1086, file: !1080, line: 91, baseType: !1211, size: 64)
!1211 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1083, file: !1080, line: 86, baseType: !1212)
!1212 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1093, file: !1091, line: 59, baseType: !1102)
!1213 = !DIDerivedType(tag: DW_TAG_member, name: "_M_finish", scope: !1086, file: !1080, line: 92, baseType: !1211, size: 64, offset: 64)
!1214 = !DIDerivedType(tag: DW_TAG_member, name: "_M_end_of_storage", scope: !1086, file: !1080, line: 93, baseType: !1211, size: 64, offset: 128)
!1215 = !DISubprogram(name: "_Vector_impl", scope: !1086, file: !1080, line: 95, type: !1216, scopeLine: 95, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1216 = !DISubroutineType(types: !1217)
!1217 = !{null, !1218}
!1218 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1086, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1219 = !DISubprogram(name: "_Vector_impl", scope: !1086, file: !1080, line: 99, type: !1220, scopeLine: 99, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1220 = !DISubroutineType(types: !1221)
!1221 = !{null, !1218, !1222}
!1222 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1223, size: 64)
!1223 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1089)
!1224 = !DISubprogram(name: "_Vector_impl", scope: !1086, file: !1080, line: 104, type: !1225, scopeLine: 104, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1225 = !DISubroutineType(types: !1226)
!1226 = !{null, !1218, !1227}
!1227 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1089, size: 64)
!1228 = !DISubprogram(name: "_M_swap_data", linkageName: "_ZNSt12_Vector_baseIN4llvm9SourceMgr9SrcBufferESaIS2_EE12_Vector_impl12_M_swap_dataERS5_", scope: !1086, file: !1080, line: 110, type: !1229, scopeLine: 110, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1229 = !DISubroutineType(types: !1230)
!1230 = !{null, !1218, !1231}
!1231 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1086, size: 64)
!1232 = !DISubprogram(name: "_M_get_Tp_allocator", linkageName: "_ZNSt12_Vector_baseIN4llvm9SourceMgr9SrcBufferESaIS2_EE19_M_get_Tp_allocatorEv", scope: !1083, file: !1080, line: 237, type: !1233, scopeLine: 237, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1233 = !DISubroutineType(types: !1234)
!1234 = !{!1235, !1236}
!1235 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1089, size: 64)
!1236 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1083, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1237 = !DISubprogram(name: "_M_get_Tp_allocator", linkageName: "_ZNKSt12_Vector_baseIN4llvm9SourceMgr9SrcBufferESaIS2_EE19_M_get_Tp_allocatorEv", scope: !1083, file: !1080, line: 241, type: !1238, scopeLine: 241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1238 = !DISubroutineType(types: !1239)
!1239 = !{!1222, !1240}
!1240 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1241, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1241 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1083)
!1242 = !DISubprogram(name: "get_allocator", linkageName: "_ZNKSt12_Vector_baseIN4llvm9SourceMgr9SrcBufferESaIS2_EE13get_allocatorEv", scope: !1083, file: !1080, line: 245, type: !1243, scopeLine: 245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1243 = !DISubroutineType(types: !1244)
!1244 = !{!1245, !1240}
!1245 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !1083, file: !1080, line: 234, baseType: !1114)
!1246 = !DISubprogram(name: "_Vector_base", scope: !1083, file: !1080, line: 248, type: !1247, scopeLine: 248, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1247 = !DISubroutineType(types: !1248)
!1248 = !{null, !1236}
!1249 = !DISubprogram(name: "_Vector_base", scope: !1083, file: !1080, line: 251, type: !1250, scopeLine: 251, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1250 = !DISubroutineType(types: !1251)
!1251 = !{null, !1236, !1252}
!1252 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1253, size: 64)
!1253 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1245)
!1254 = !DISubprogram(name: "_Vector_base", scope: !1083, file: !1080, line: 254, type: !1255, scopeLine: 254, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1255 = !DISubroutineType(types: !1256)
!1256 = !{null, !1236, !1152}
!1257 = !DISubprogram(name: "_Vector_base", scope: !1083, file: !1080, line: 258, type: !1258, scopeLine: 258, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1258 = !DISubroutineType(types: !1259)
!1259 = !{null, !1236, !1152, !1252}
!1260 = !DISubprogram(name: "_Vector_base", scope: !1083, file: !1080, line: 263, type: !1261, scopeLine: 263, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1261 = !DISubroutineType(types: !1262)
!1262 = !{null, !1236, !1227}
!1263 = !DISubprogram(name: "_Vector_base", scope: !1083, file: !1080, line: 266, type: !1264, scopeLine: 266, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1264 = !DISubroutineType(types: !1265)
!1265 = !{null, !1236, !1266}
!1266 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1083, size: 64)
!1267 = !DISubprogram(name: "_Vector_base", scope: !1083, file: !1080, line: 270, type: !1268, scopeLine: 270, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1268 = !DISubroutineType(types: !1269)
!1269 = !{null, !1236, !1266, !1252}
!1270 = !DISubprogram(name: "~_Vector_base", scope: !1083, file: !1080, line: 283, type: !1247, scopeLine: 283, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1271 = !DISubprogram(name: "_M_allocate", linkageName: "_ZNSt12_Vector_baseIN4llvm9SourceMgr9SrcBufferESaIS2_EE11_M_allocateEm", scope: !1083, file: !1080, line: 293, type: !1272, scopeLine: 293, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1272 = !DISubroutineType(types: !1273)
!1273 = !{!1211, !1236, !1152}
!1274 = !DISubprogram(name: "_M_deallocate", linkageName: "_ZNSt12_Vector_baseIN4llvm9SourceMgr9SrcBufferESaIS2_EE13_M_deallocateEPS2_m", scope: !1083, file: !1080, line: 300, type: !1275, scopeLine: 300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1275 = !DISubroutineType(types: !1276)
!1276 = !{null, !1236, !1211, !1152}
!1277 = !DISubprogram(name: "_M_create_storage", linkageName: "_ZNSt12_Vector_baseIN4llvm9SourceMgr9SrcBufferESaIS2_EE17_M_create_storageEm", scope: !1083, file: !1080, line: 309, type: !1255, scopeLine: 309, flags: DIFlagPrivate | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1278 = !{!1163, !1192}
!1279 = !DISubprogram(name: "vector", scope: !1079, file: !1080, line: 391, type: !1280, scopeLine: 391, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1280 = !DISubroutineType(types: !1281)
!1281 = !{null, !1282}
!1282 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1079, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1283 = !DISubprogram(name: "vector", scope: !1079, file: !1080, line: 402, type: !1284, scopeLine: 402, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1284 = !DISubroutineType(types: !1285)
!1285 = !{null, !1282, !1286}
!1286 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1287, size: 64)
!1287 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1288)
!1288 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !1079, file: !1080, line: 376, baseType: !1114)
!1289 = !DISubprogram(name: "vector", scope: !1079, file: !1080, line: 415, type: !1290, scopeLine: 415, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1290 = !DISubroutineType(types: !1291)
!1291 = !{null, !1282, !1292, !1286}
!1292 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !1080, line: 374, baseType: !1152)
!1293 = !DISubprogram(name: "vector", scope: !1079, file: !1080, line: 427, type: !1294, scopeLine: 427, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1294 = !DISubroutineType(types: !1295)
!1295 = !{null, !1282, !1292, !1296, !1286}
!1296 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1297, size: 64)
!1297 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1298)
!1298 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1079, file: !1080, line: 364, baseType: !1104)
!1299 = !DISubprogram(name: "vector", scope: !1079, file: !1080, line: 458, type: !1300, scopeLine: 458, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1300 = !DISubroutineType(types: !1301)
!1301 = !{null, !1282, !1302}
!1302 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1303, size: 64)
!1303 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1079)
!1304 = !DISubprogram(name: "vector", scope: !1079, file: !1080, line: 476, type: !1305, scopeLine: 476, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1305 = !DISubroutineType(types: !1306)
!1306 = !{null, !1282, !1307}
!1307 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1079, size: 64)
!1308 = !DISubprogram(name: "vector", scope: !1079, file: !1080, line: 480, type: !1309, scopeLine: 480, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1309 = !DISubroutineType(types: !1310)
!1310 = !{null, !1282, !1302, !1286}
!1311 = !DISubprogram(name: "vector", scope: !1079, file: !1080, line: 490, type: !1312, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1312 = !DISubroutineType(types: !1313)
!1313 = !{null, !1282, !1307, !1286}
!1314 = !DISubprogram(name: "vector", scope: !1079, file: !1080, line: 515, type: !1315, scopeLine: 515, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1315 = !DISubroutineType(types: !1316)
!1316 = !{null, !1282, !1317, !1286}
!1317 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<llvm::SourceMgr::SrcBuffer>", scope: !192, file: !1318, line: 47, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listIN4llvm9SourceMgr9SrcBufferEE")
!1318 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/initializer_list", directory: "")
!1319 = !DISubprogram(name: "~vector", scope: !1079, file: !1080, line: 565, type: !1280, scopeLine: 565, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1320 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EEaSERKS4_", scope: !1079, file: !1080, line: 582, type: !1321, scopeLine: 582, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1321 = !DISubroutineType(types: !1322)
!1322 = !{!1323, !1282, !1302}
!1323 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1079, size: 64)
!1324 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EEaSEOS4_", scope: !1079, file: !1080, line: 596, type: !1325, scopeLine: 596, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1325 = !DISubroutineType(types: !1326)
!1326 = !{!1323, !1282, !1307}
!1327 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EEaSESt16initializer_listIS2_E", scope: !1079, file: !1080, line: 617, type: !1328, scopeLine: 617, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1328 = !DISubroutineType(types: !1329)
!1329 = !{!1323, !1282, !1317}
!1330 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE6assignEmRKS2_", scope: !1079, file: !1080, line: 636, type: !1331, scopeLine: 636, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1331 = !DISubroutineType(types: !1332)
!1332 = !{null, !1282, !1292, !1296}
!1333 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE6assignESt16initializer_listIS2_E", scope: !1079, file: !1080, line: 681, type: !1334, scopeLine: 681, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1334 = !DISubroutineType(types: !1335)
!1335 = !{null, !1282, !1317}
!1336 = !DISubprogram(name: "begin", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE5beginEv", scope: !1079, file: !1080, line: 698, type: !1337, scopeLine: 698, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1337 = !DISubroutineType(types: !1338)
!1338 = !{!1339, !1282}
!1339 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1079, file: !1080, line: 369, baseType: !1340)
!1340 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<llvm::SourceMgr::SrcBuffer *, std::vector<llvm::SourceMgr::SrcBuffer, std::allocator<llvm::SourceMgr::SrcBuffer> > >", scope: !5, file: !631, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1341, templateParams: !1394, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPN4llvm9SourceMgr9SrcBufferESt6vectorIS3_SaIS3_EEEE")
!1341 = !{!1342, !1343, !1347, !1352, !1363, !1368, !1372, !1375, !1376, !1377, !1383, !1386, !1389, !1390, !1391}
!1342 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !1340, file: !631, line: 767, baseType: !1103, size: 64, flags: DIFlagProtected)
!1343 = !DISubprogram(name: "__normal_iterator", scope: !1340, file: !631, line: 779, type: !1344, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1344 = !DISubroutineType(types: !1345)
!1345 = !{null, !1346}
!1346 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1340, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1347 = !DISubprogram(name: "__normal_iterator", scope: !1340, file: !631, line: 783, type: !1348, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1348 = !DISubroutineType(types: !1349)
!1349 = !{null, !1346, !1350}
!1350 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1351, size: 64)
!1351 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1103)
!1352 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPN4llvm9SourceMgr9SrcBufferESt6vectorIS3_SaIS3_EEEdeEv", scope: !1340, file: !631, line: 796, type: !1353, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1353 = !DISubroutineType(types: !1354)
!1354 = !{!1355, !1361}
!1355 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1340, file: !631, line: 776, baseType: !1356)
!1356 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1358, file: !1357, line: 184, baseType: !1139)
!1357 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_iterator_base_types.h", directory: "")
!1358 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<llvm::SourceMgr::SrcBuffer *>", scope: !192, file: !1357, line: 178, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !1359, identifier: "_ZTSSt15iterator_traitsIPN4llvm9SourceMgr9SrcBufferEE")
!1359 = !{!1360}
!1360 = !DITemplateTypeParameter(name: "_Iterator", type: !1103)
!1361 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1362, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1362 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1340)
!1363 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPN4llvm9SourceMgr9SrcBufferESt6vectorIS3_SaIS3_EEEptEv", scope: !1340, file: !631, line: 800, type: !1364, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1364 = !DISubroutineType(types: !1365)
!1365 = !{!1366, !1361}
!1366 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1340, file: !631, line: 777, baseType: !1367)
!1367 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1358, file: !1357, line: 183, baseType: !1103)
!1368 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPN4llvm9SourceMgr9SrcBufferESt6vectorIS3_SaIS3_EEEppEv", scope: !1340, file: !631, line: 804, type: !1369, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1369 = !DISubroutineType(types: !1370)
!1370 = !{!1371, !1346}
!1371 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1340, size: 64)
!1372 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPN4llvm9SourceMgr9SrcBufferESt6vectorIS3_SaIS3_EEEppEi", scope: !1340, file: !631, line: 811, type: !1373, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1373 = !DISubroutineType(types: !1374)
!1374 = !{!1340, !1346, !24}
!1375 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPN4llvm9SourceMgr9SrcBufferESt6vectorIS3_SaIS3_EEEmmEv", scope: !1340, file: !631, line: 816, type: !1369, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1376 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPN4llvm9SourceMgr9SrcBufferESt6vectorIS3_SaIS3_EEEmmEi", scope: !1340, file: !631, line: 823, type: !1373, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1377 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPN4llvm9SourceMgr9SrcBufferESt6vectorIS3_SaIS3_EEEixEl", scope: !1340, file: !631, line: 828, type: !1378, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1378 = !DISubroutineType(types: !1379)
!1379 = !{!1355, !1361, !1380}
!1380 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1340, file: !631, line: 775, baseType: !1381)
!1381 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1358, file: !1357, line: 182, baseType: !1382)
!1382 = !DIDerivedType(tag: DW_TAG_typedef, name: "ptrdiff_t", scope: !192, file: !1153, line: 239, baseType: !405)
!1383 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPN4llvm9SourceMgr9SrcBufferESt6vectorIS3_SaIS3_EEEpLEl", scope: !1340, file: !631, line: 832, type: !1384, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1384 = !DISubroutineType(types: !1385)
!1385 = !{!1371, !1346, !1380}
!1386 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPN4llvm9SourceMgr9SrcBufferESt6vectorIS3_SaIS3_EEEplEl", scope: !1340, file: !631, line: 836, type: !1387, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1387 = !DISubroutineType(types: !1388)
!1388 = !{!1340, !1361, !1380}
!1389 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPN4llvm9SourceMgr9SrcBufferESt6vectorIS3_SaIS3_EEEmIEl", scope: !1340, file: !631, line: 840, type: !1384, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1390 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPN4llvm9SourceMgr9SrcBufferESt6vectorIS3_SaIS3_EEEmiEl", scope: !1340, file: !631, line: 844, type: !1387, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1391 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPN4llvm9SourceMgr9SrcBufferESt6vectorIS3_SaIS3_EEE4baseEv", scope: !1340, file: !631, line: 848, type: !1392, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1392 = !DISubroutineType(types: !1393)
!1393 = !{!1350, !1361}
!1394 = !{!1360, !1395}
!1395 = !DITemplateTypeParameter(name: "_Container", type: !1079)
!1396 = !DISubprogram(name: "begin", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE5beginEv", scope: !1079, file: !1080, line: 707, type: !1397, scopeLine: 707, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1397 = !DISubroutineType(types: !1398)
!1398 = !{!1399, !1401}
!1399 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !1079, file: !1080, line: 371, baseType: !1400)
!1400 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<const llvm::SourceMgr::SrcBuffer *, std::vector<llvm::SourceMgr::SrcBuffer, std::allocator<llvm::SourceMgr::SrcBuffer> > >", scope: !5, file: !631, line: 764, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPKN4llvm9SourceMgr9SrcBufferESt6vectorIS3_SaIS3_EEEE")
!1401 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1303, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1402 = !DISubprogram(name: "end", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE3endEv", scope: !1079, file: !1080, line: 716, type: !1337, scopeLine: 716, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1403 = !DISubprogram(name: "end", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE3endEv", scope: !1079, file: !1080, line: 725, type: !1397, scopeLine: 725, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1404 = !DISubprogram(name: "rbegin", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE6rbeginEv", scope: !1079, file: !1080, line: 734, type: !1405, scopeLine: 734, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1405 = !DISubroutineType(types: !1406)
!1406 = !{!1407, !1282}
!1407 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !1079, file: !1080, line: 373, baseType: !1408)
!1408 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<llvm::SourceMgr::SrcBuffer *, std::vector<llvm::SourceMgr::SrcBuffer, std::allocator<llvm::SourceMgr::SrcBuffer> > > >", scope: !192, file: !631, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPN4llvm9SourceMgr9SrcBufferESt6vectorIS4_SaIS4_EEEEE")
!1409 = !DISubprogram(name: "rbegin", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE6rbeginEv", scope: !1079, file: !1080, line: 743, type: !1410, scopeLine: 743, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1410 = !DISubroutineType(types: !1411)
!1411 = !{!1412, !1401}
!1412 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !1079, file: !1080, line: 372, baseType: !1413)
!1413 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<const llvm::SourceMgr::SrcBuffer *, std::vector<llvm::SourceMgr::SrcBuffer, std::allocator<llvm::SourceMgr::SrcBuffer> > > >", scope: !192, file: !631, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPKN4llvm9SourceMgr9SrcBufferESt6vectorIS4_SaIS4_EEEEE")
!1414 = !DISubprogram(name: "rend", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE4rendEv", scope: !1079, file: !1080, line: 752, type: !1405, scopeLine: 752, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1415 = !DISubprogram(name: "rend", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE4rendEv", scope: !1079, file: !1080, line: 761, type: !1410, scopeLine: 761, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1416 = !DISubprogram(name: "cbegin", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE6cbeginEv", scope: !1079, file: !1080, line: 771, type: !1397, scopeLine: 771, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1417 = !DISubprogram(name: "cend", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE4cendEv", scope: !1079, file: !1080, line: 780, type: !1397, scopeLine: 780, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1418 = !DISubprogram(name: "crbegin", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE7crbeginEv", scope: !1079, file: !1080, line: 789, type: !1410, scopeLine: 789, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1419 = !DISubprogram(name: "crend", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE5crendEv", scope: !1079, file: !1080, line: 798, type: !1410, scopeLine: 798, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1420 = !DISubprogram(name: "size", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE4sizeEv", scope: !1079, file: !1080, line: 805, type: !1421, scopeLine: 805, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1421 = !DISubroutineType(types: !1422)
!1422 = !{!1292, !1401}
!1423 = !DISubprogram(name: "max_size", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE8max_sizeEv", scope: !1079, file: !1080, line: 810, type: !1421, scopeLine: 810, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1424 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE6resizeEm", scope: !1079, file: !1080, line: 824, type: !1425, scopeLine: 824, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1425 = !DISubroutineType(types: !1426)
!1426 = !{null, !1282, !1292}
!1427 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE6resizeEmRKS2_", scope: !1079, file: !1080, line: 844, type: !1331, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1428 = !DISubprogram(name: "shrink_to_fit", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE13shrink_to_fitEv", scope: !1079, file: !1080, line: 876, type: !1280, scopeLine: 876, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1429 = !DISubprogram(name: "capacity", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE8capacityEv", scope: !1079, file: !1080, line: 885, type: !1421, scopeLine: 885, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1430 = !DISubprogram(name: "empty", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE5emptyEv", scope: !1079, file: !1080, line: 894, type: !1431, scopeLine: 894, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1431 = !DISubroutineType(types: !1432)
!1432 = !{!132, !1401}
!1433 = !DISubprogram(name: "reserve", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE7reserveEm", scope: !1079, file: !1080, line: 915, type: !1425, scopeLine: 915, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1434 = !DISubprogram(name: "operator[]", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EEixEm", scope: !1079, file: !1080, line: 930, type: !1435, scopeLine: 930, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1435 = !DISubroutineType(types: !1436)
!1436 = !{!1437, !1282, !1292}
!1437 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1079, file: !1080, line: 367, baseType: !1438)
!1438 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1093, file: !1091, line: 64, baseType: !1439)
!1439 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1440, size: 64)
!1440 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1093, file: !1091, line: 58, baseType: !1441)
!1441 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1096, file: !1097, line: 389, baseType: !1104)
!1442 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EEixEm", scope: !1079, file: !1080, line: 948, type: !1443, scopeLine: 948, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1443 = !DISubroutineType(types: !1444)
!1444 = !{!1445, !1401, !1292}
!1445 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1079, file: !1080, line: 368, baseType: !1446)
!1446 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1093, file: !1091, line: 65, baseType: !1447)
!1447 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1448, size: 64)
!1448 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1440)
!1449 = !DISubprogram(name: "_M_range_check", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE14_M_range_checkEm", scope: !1079, file: !1080, line: 957, type: !1450, scopeLine: 957, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1450 = !DISubroutineType(types: !1451)
!1451 = !{null, !1401, !1292}
!1452 = !DISubprogram(name: "at", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE2atEm", scope: !1079, file: !1080, line: 979, type: !1435, scopeLine: 979, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1453 = !DISubprogram(name: "at", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE2atEm", scope: !1079, file: !1080, line: 997, type: !1443, scopeLine: 997, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1454 = !DISubprogram(name: "front", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE5frontEv", scope: !1079, file: !1080, line: 1008, type: !1455, scopeLine: 1008, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1455 = !DISubroutineType(types: !1456)
!1456 = !{!1437, !1282}
!1457 = !DISubprogram(name: "front", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE5frontEv", scope: !1079, file: !1080, line: 1019, type: !1458, scopeLine: 1019, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1458 = !DISubroutineType(types: !1459)
!1459 = !{!1445, !1401}
!1460 = !DISubprogram(name: "back", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE4backEv", scope: !1079, file: !1080, line: 1030, type: !1455, scopeLine: 1030, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1461 = !DISubprogram(name: "back", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE4backEv", scope: !1079, file: !1080, line: 1041, type: !1458, scopeLine: 1041, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1462 = !DISubprogram(name: "data", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE4dataEv", scope: !1079, file: !1080, line: 1055, type: !1463, scopeLine: 1055, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1463 = !DISubroutineType(types: !1464)
!1464 = !{!1103, !1282}
!1465 = !DISubprogram(name: "data", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE4dataEv", scope: !1079, file: !1080, line: 1059, type: !1466, scopeLine: 1059, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1466 = !DISubroutineType(types: !1467)
!1467 = !{!1144, !1401}
!1468 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE9push_backERKS2_", scope: !1079, file: !1080, line: 1074, type: !1469, scopeLine: 1074, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1469 = !DISubroutineType(types: !1470)
!1470 = !{null, !1282, !1296}
!1471 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE9push_backEOS2_", scope: !1079, file: !1080, line: 1090, type: !1472, scopeLine: 1090, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1472 = !DISubroutineType(types: !1473)
!1473 = !{null, !1282, !1474}
!1474 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1298, size: 64)
!1475 = !DISubprogram(name: "pop_back", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE8pop_backEv", scope: !1079, file: !1080, line: 1112, type: !1280, scopeLine: 1112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1476 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EERS7_", scope: !1079, file: !1080, line: 1150, type: !1477, scopeLine: 1150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1477 = !DISubroutineType(types: !1478)
!1478 = !{!1339, !1282, !1399, !1296}
!1479 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EEOS2_", scope: !1079, file: !1080, line: 1180, type: !1480, scopeLine: 1180, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1480 = !DISubroutineType(types: !1481)
!1481 = !{!1339, !1282, !1399, !1474}
!1482 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EESt16initializer_listIS2_E", scope: !1079, file: !1080, line: 1197, type: !1483, scopeLine: 1197, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1483 = !DISubroutineType(types: !1484)
!1484 = !{!1339, !1282, !1399, !1317}
!1485 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EEmRS7_", scope: !1079, file: !1080, line: 1222, type: !1486, scopeLine: 1222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1486 = !DISubroutineType(types: !1487)
!1487 = !{!1339, !1282, !1399, !1292, !1296}
!1488 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE5eraseEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EE", scope: !1079, file: !1080, line: 1317, type: !1489, scopeLine: 1317, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1489 = !DISubroutineType(types: !1490)
!1490 = !{!1339, !1282, !1399}
!1491 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE5eraseEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EES9_", scope: !1079, file: !1080, line: 1344, type: !1492, scopeLine: 1344, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1492 = !DISubroutineType(types: !1493)
!1493 = !{!1339, !1282, !1399, !1399}
!1494 = !DISubprogram(name: "swap", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE4swapERS4_", scope: !1079, file: !1080, line: 1367, type: !1495, scopeLine: 1367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1495 = !DISubroutineType(types: !1496)
!1496 = !{null, !1282, !1323}
!1497 = !DISubprogram(name: "clear", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE5clearEv", scope: !1079, file: !1080, line: 1385, type: !1280, scopeLine: 1385, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1498 = !DISubprogram(name: "_M_fill_initialize", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE18_M_fill_initializeEmRKS2_", scope: !1079, file: !1080, line: 1477, type: !1331, scopeLine: 1477, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1499 = !DISubprogram(name: "_M_default_initialize", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE21_M_default_initializeEm", scope: !1079, file: !1080, line: 1487, type: !1425, scopeLine: 1487, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1500 = !DISubprogram(name: "_M_fill_assign", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE14_M_fill_assignEmRKS2_", scope: !1079, file: !1080, line: 1529, type: !1331, scopeLine: 1529, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1501 = !DISubprogram(name: "_M_fill_insert", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS2_S4_EEmRKS2_", scope: !1079, file: !1080, line: 1568, type: !1502, scopeLine: 1568, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1502 = !DISubroutineType(types: !1503)
!1503 = !{null, !1282, !1339, !1292, !1296}
!1504 = !DISubprogram(name: "_M_default_append", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE17_M_default_appendEm", scope: !1079, file: !1080, line: 1573, type: !1425, scopeLine: 1573, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1505 = !DISubprogram(name: "_M_shrink_to_fit", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE16_M_shrink_to_fitEv", scope: !1079, file: !1080, line: 1576, type: !1506, scopeLine: 1576, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1506 = !DISubroutineType(types: !1507)
!1507 = !{!132, !1282}
!1508 = !DISubprogram(name: "_M_insert_rval", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE14_M_insert_rvalEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EEOS2_", scope: !1079, file: !1080, line: 1625, type: !1480, scopeLine: 1625, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1509 = !DISubprogram(name: "_M_emplace_aux", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE14_M_emplace_auxEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EEOS2_", scope: !1079, file: !1080, line: 1634, type: !1480, scopeLine: 1634, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1510 = !DISubprogram(name: "_M_check_len", linkageName: "_ZNKSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE12_M_check_lenEmPKc", scope: !1079, file: !1080, line: 1640, type: !1511, scopeLine: 1640, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1511 = !DISubroutineType(types: !1512)
!1512 = !{!1513, !1401, !1292, !163}
!1513 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1079, file: !1080, line: 374, baseType: !1152)
!1514 = !DISubprogram(name: "_M_erase_at_end", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE15_M_erase_at_endEPS2_", scope: !1079, file: !1080, line: 1654, type: !1515, scopeLine: 1654, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1515 = !DISubroutineType(types: !1516)
!1516 = !{null, !1282, !1517}
!1517 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1079, file: !1080, line: 365, baseType: !1211)
!1518 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE8_M_eraseEN9__gnu_cxx17__normal_iteratorIPS2_S4_EE", scope: !1079, file: !1080, line: 1666, type: !1519, scopeLine: 1666, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1519 = !DISubroutineType(types: !1520)
!1520 = !{!1339, !1282, !1339}
!1521 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE8_M_eraseEN9__gnu_cxx17__normal_iteratorIPS2_S4_EES8_", scope: !1079, file: !1080, line: 1669, type: !1522, scopeLine: 1669, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1522 = !DISubroutineType(types: !1523)
!1523 = !{!1339, !1282, !1339, !1339}
!1524 = !DISubprogram(name: "_M_move_assign", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE14_M_move_assignEOS4_St17integral_constantIbLb1EE", scope: !1079, file: !1080, line: 1677, type: !1525, scopeLine: 1677, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1525 = !DISubroutineType(types: !1526)
!1526 = !{null, !1282, !1307, !1527}
!1527 = !DIDerivedType(tag: DW_TAG_typedef, name: "true_type", scope: !192, file: !318, line: 75, baseType: !1528)
!1528 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "integral_constant<bool, true>", scope: !192, file: !318, line: 57, size: 8, flags: DIFlagTypePassByValue, elements: !1529, templateParams: !1539, identifier: "_ZTSSt17integral_constantIbLb1EE")
!1529 = !{!1530, !1532, !1538}
!1530 = !DIDerivedType(tag: DW_TAG_member, name: "value", scope: !1528, file: !318, line: 59, baseType: !1531, flags: DIFlagStaticMember, extraData: i1 true)
!1531 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !132)
!1532 = !DISubprogram(name: "operator bool", linkageName: "_ZNKSt17integral_constantIbLb1EEcvbEv", scope: !1528, file: !318, line: 62, type: !1533, scopeLine: 62, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1533 = !DISubroutineType(types: !1534)
!1534 = !{!1535, !1536}
!1535 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1528, file: !318, line: 60, baseType: !132)
!1536 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1537, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1537 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1528)
!1538 = !DISubprogram(name: "operator()", linkageName: "_ZNKSt17integral_constantIbLb1EEclEv", scope: !1528, file: !318, line: 67, type: !1533, scopeLine: 67, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1539 = !{!1540, !1541}
!1540 = !DITemplateTypeParameter(name: "_Tp", type: !132)
!1541 = !DITemplateValueParameter(name: "__v", type: !132, value: i8 1)
!1542 = !DISubprogram(name: "_M_move_assign", linkageName: "_ZNSt6vectorIN4llvm9SourceMgr9SrcBufferESaIS2_EE14_M_move_assignEOS4_St17integral_constantIbLb0EE", scope: !1079, file: !1080, line: 1688, type: !1543, scopeLine: 1688, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1543 = !DISubroutineType(types: !1544)
!1544 = !{null, !1282, !1307, !1545}
!1545 = !DIDerivedType(tag: DW_TAG_typedef, name: "false_type", scope: !192, file: !318, line: 78, baseType: !1546)
!1546 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "integral_constant<bool, false>", scope: !192, file: !318, line: 57, size: 8, flags: DIFlagTypePassByValue, elements: !1547, templateParams: !1556, identifier: "_ZTSSt17integral_constantIbLb0EE")
!1547 = !{!1548, !1549, !1555}
!1548 = !DIDerivedType(tag: DW_TAG_member, name: "value", scope: !1546, file: !318, line: 59, baseType: !1531, flags: DIFlagStaticMember, extraData: i1 false)
!1549 = !DISubprogram(name: "operator bool", linkageName: "_ZNKSt17integral_constantIbLb0EEcvbEv", scope: !1546, file: !318, line: 62, type: !1550, scopeLine: 62, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1550 = !DISubroutineType(types: !1551)
!1551 = !{!1552, !1553}
!1552 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1546, file: !318, line: 60, baseType: !132)
!1553 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1554, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1554 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1546)
!1555 = !DISubprogram(name: "operator()", linkageName: "_ZNKSt17integral_constantIbLb0EEclEv", scope: !1546, file: !318, line: 67, type: !1550, scopeLine: 67, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1556 = !{!1540, !1557}
!1557 = !DITemplateValueParameter(name: "__v", type: !132, value: i8 0)
!1558 = !DIDerivedType(tag: DW_TAG_member, name: "IncludeDirectories", scope: !1076, file: !1075, line: 62, baseType: !1559, size: 192, offset: 192)
!1559 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >", scope: !192, file: !1080, line: 339, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1560, templateParams: !1735, identifier: "_ZTSSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE")
!1560 = !{!1561, !1736, !1740, !1746, !1749, !1755, !1760, !1764, !1767, !1770, !1774, !1775, !1779, !1782, !1785, !1788, !1791, !1849, !1907, !1908, !1909, !1914, !1919, !1920, !1921, !1922, !1923, !1924, !1925, !1928, !1929, !1932, !1933, !1934, !1935, !1938, !1939, !1947, !1954, !1957, !1958, !1959, !1962, !1965, !1966, !1967, !1970, !1973, !1976, !1980, !1981, !1984, !1987, !1990, !1993, !1996, !1999, !2002, !2003, !2004, !2005, !2006, !2009, !2010, !2013, !2014, !2015, !2019, !2023, !2026, !2029, !2032}
!1561 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1559, baseType: !1562, flags: DIFlagProtected, extraData: i32 0)
!1562 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >", scope: !192, file: !1080, line: 81, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1563, templateParams: !1735, identifier: "_ZTSSt12_Vector_baseINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE")
!1563 = !{!1564, !1689, !1694, !1699, !1703, !1706, !1711, !1714, !1717, !1720, !1724, !1727, !1728, !1731, !1734}
!1564 = !DIDerivedType(tag: DW_TAG_member, name: "_M_impl", scope: !1562, file: !1080, line: 290, baseType: !1565, size: 192)
!1565 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_impl", scope: !1562, file: !1080, line: 88, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1566, identifier: "_ZTSNSt12_Vector_baseINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE12_Vector_implE")
!1566 = !{!1567, !1667, !1670, !1671, !1672, !1676, !1681, !1685}
!1567 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1565, baseType: !1568, extraData: i32 0)
!1568 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Tp_alloc_type", scope: !1562, file: !1080, line: 84, baseType: !1569)
!1569 = !DIDerivedType(tag: DW_TAG_typedef, name: "other", scope: !1570, file: !1091, line: 117, baseType: !1666)
!1570 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "rebind<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >", scope: !1571, file: !1091, line: 116, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !1623, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEES6_E6rebindIS6_EE")
!1571 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__alloc_traits<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >", scope: !5, file: !1091, line: 50, size: 8, flags: DIFlagTypePassByValue, elements: !1572, templateParams: !1664, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEES6_EE")
!1572 = !{!1573, !1652, !1655, !1659, !1660, !1661, !1662, !1663}
!1573 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1571, baseType: !1574, extraData: i32 0)
!1574 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "allocator_traits<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >", scope: !192, file: !1097, line: 384, size: 8, flags: DIFlagTypePassByValue, elements: !1575, templateParams: !1650, identifier: "_ZTSSt16allocator_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE")
!1575 = !{!1576, !1635, !1638, !1641, !1647}
!1576 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE8allocateERS6_m", scope: !1574, file: !1097, line: 435, type: !1577, scopeLine: 435, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1577 = !DISubroutineType(types: !1578)
!1578 = !{!1579, !1581, !1174}
!1579 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1574, file: !1097, line: 392, baseType: !1580)
!1580 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !193, size: 64)
!1581 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1582, size: 64)
!1582 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !1574, file: !1097, line: 387, baseType: !1583)
!1583 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >", scope: !192, file: !1115, line: 108, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1584, templateParams: !1623, identifier: "_ZTSSaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE")
!1584 = !{!1585, !1625, !1629, !1634}
!1585 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1583, baseType: !1586, flags: DIFlagPublic, extraData: i32 0)
!1586 = !DIDerivedType(tag: DW_TAG_typedef, name: "__allocator_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >", scope: !192, file: !1119, line: 48, baseType: !1587)
!1587 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >", scope: !5, file: !1121, line: 58, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1588, templateParams: !1623, identifier: "_ZTSN9__gnu_cxx13new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE")
!1588 = !{!1589, !1593, !1598, !1599, !1606, !1614, !1617, !1620}
!1589 = !DISubprogram(name: "new_allocator", scope: !1587, file: !1121, line: 79, type: !1590, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1590 = !DISubroutineType(types: !1591)
!1591 = !{null, !1592}
!1592 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1587, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1593 = !DISubprogram(name: "new_allocator", scope: !1587, file: !1121, line: 81, type: !1594, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1594 = !DISubroutineType(types: !1595)
!1595 = !{null, !1592, !1596}
!1596 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1597, size: 64)
!1597 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1587)
!1598 = !DISubprogram(name: "~new_allocator", scope: !1587, file: !1121, line: 86, type: !1590, scopeLine: 86, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1599 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE7addressERS6_", scope: !1587, file: !1121, line: 89, type: !1600, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1600 = !DISubroutineType(types: !1601)
!1601 = !{!1602, !1603, !1604}
!1602 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1587, file: !1121, line: 63, baseType: !1580)
!1603 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1597, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1604 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1587, file: !1121, line: 65, baseType: !1605)
!1605 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !193, size: 64)
!1606 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE7addressERKS6_", scope: !1587, file: !1121, line: 93, type: !1607, scopeLine: 93, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1607 = !DISubroutineType(types: !1608)
!1608 = !{!1609, !1603, !1612}
!1609 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !1587, file: !1121, line: 64, baseType: !1610)
!1610 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1611, size: 64)
!1611 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !193)
!1612 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1587, file: !1121, line: 66, baseType: !1613)
!1613 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1611, size: 64)
!1614 = !DISubprogram(name: "allocate", linkageName: "_ZN9__gnu_cxx13new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE8allocateEmPKv", scope: !1587, file: !1121, line: 99, type: !1615, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1615 = !DISubroutineType(types: !1616)
!1616 = !{!1602, !1592, !1151, !1154}
!1617 = !DISubprogram(name: "deallocate", linkageName: "_ZN9__gnu_cxx13new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE10deallocateEPS6_m", scope: !1587, file: !1121, line: 116, type: !1618, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1618 = !DISubroutineType(types: !1619)
!1619 = !{null, !1592, !1602, !1151}
!1620 = !DISubprogram(name: "max_size", linkageName: "_ZNK9__gnu_cxx13new_allocatorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE8max_sizeEv", scope: !1587, file: !1121, line: 129, type: !1621, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1621 = !DISubroutineType(types: !1622)
!1622 = !{!1151, !1603}
!1623 = !{!1624}
!1624 = !DITemplateTypeParameter(name: "_Tp", type: !193)
!1625 = !DISubprogram(name: "allocator", scope: !1583, file: !1115, line: 131, type: !1626, scopeLine: 131, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1626 = !DISubroutineType(types: !1627)
!1627 = !{null, !1628}
!1628 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1583, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1629 = !DISubprogram(name: "allocator", scope: !1583, file: !1115, line: 133, type: !1630, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1630 = !DISubroutineType(types: !1631)
!1631 = !{null, !1628, !1632}
!1632 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1633, size: 64)
!1633 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1583)
!1634 = !DISubprogram(name: "~allocator", scope: !1583, file: !1115, line: 139, type: !1626, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1635 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE8allocateERS6_mPKv", scope: !1574, file: !1097, line: 449, type: !1636, scopeLine: 449, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1636 = !DISubroutineType(types: !1637)
!1637 = !{!1579, !1581, !1174, !1178}
!1638 = !DISubprogram(name: "deallocate", linkageName: "_ZNSt16allocator_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE10deallocateERS6_PS5_m", scope: !1574, file: !1097, line: 461, type: !1639, scopeLine: 461, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1639 = !DISubroutineType(types: !1640)
!1640 = !{null, !1581, !1579, !1174}
!1641 = !DISubprogram(name: "max_size", linkageName: "_ZNSt16allocator_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE8max_sizeERKS6_", scope: !1574, file: !1097, line: 495, type: !1642, scopeLine: 495, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1642 = !DISubroutineType(types: !1643)
!1643 = !{!1644, !1645}
!1644 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1574, file: !1097, line: 407, baseType: !1152)
!1645 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1646, size: 64)
!1646 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1582)
!1647 = !DISubprogram(name: "select_on_container_copy_construction", linkageName: "_ZNSt16allocator_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE37select_on_container_copy_constructionERKS6_", scope: !1574, file: !1097, line: 504, type: !1648, scopeLine: 504, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1648 = !DISubroutineType(types: !1649)
!1649 = !{!1582, !1645}
!1650 = !{!1651}
!1651 = !DITemplateTypeParameter(name: "_Alloc", type: !1583)
!1652 = !DISubprogram(name: "_S_select_on_copy", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEES6_E17_S_select_on_copyERKS7_", scope: !1571, file: !1091, line: 94, type: !1653, scopeLine: 94, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1653 = !DISubroutineType(types: !1654)
!1654 = !{!1583, !1632}
!1655 = !DISubprogram(name: "_S_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEES6_E10_S_on_swapERS7_S9_", scope: !1571, file: !1091, line: 97, type: !1656, scopeLine: 97, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1656 = !DISubroutineType(types: !1657)
!1657 = !{null, !1658, !1658}
!1658 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1583, size: 64)
!1659 = !DISubprogram(name: "_S_propagate_on_copy_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEES6_E27_S_propagate_on_copy_assignEv", scope: !1571, file: !1091, line: 100, type: !1201, scopeLine: 100, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1660 = !DISubprogram(name: "_S_propagate_on_move_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEES6_E27_S_propagate_on_move_assignEv", scope: !1571, file: !1091, line: 103, type: !1201, scopeLine: 103, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1661 = !DISubprogram(name: "_S_propagate_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEES6_E20_S_propagate_on_swapEv", scope: !1571, file: !1091, line: 106, type: !1201, scopeLine: 106, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1662 = !DISubprogram(name: "_S_always_equal", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEES6_E15_S_always_equalEv", scope: !1571, file: !1091, line: 109, type: !1201, scopeLine: 109, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1663 = !DISubprogram(name: "_S_nothrow_move", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEES6_E15_S_nothrow_moveEv", scope: !1571, file: !1091, line: 112, type: !1201, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1664 = !{!1651, !1665}
!1665 = !DITemplateTypeParameter(type: !193)
!1666 = !DIDerivedType(tag: DW_TAG_typedef, name: "rebind_alloc<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >", scope: !1574, file: !1097, line: 422, baseType: !1583)
!1667 = !DIDerivedType(tag: DW_TAG_member, name: "_M_start", scope: !1565, file: !1080, line: 91, baseType: !1668, size: 64)
!1668 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1562, file: !1080, line: 86, baseType: !1669)
!1669 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1571, file: !1091, line: 59, baseType: !1579)
!1670 = !DIDerivedType(tag: DW_TAG_member, name: "_M_finish", scope: !1565, file: !1080, line: 92, baseType: !1668, size: 64, offset: 64)
!1671 = !DIDerivedType(tag: DW_TAG_member, name: "_M_end_of_storage", scope: !1565, file: !1080, line: 93, baseType: !1668, size: 64, offset: 128)
!1672 = !DISubprogram(name: "_Vector_impl", scope: !1565, file: !1080, line: 95, type: !1673, scopeLine: 95, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1673 = !DISubroutineType(types: !1674)
!1674 = !{null, !1675}
!1675 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1565, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1676 = !DISubprogram(name: "_Vector_impl", scope: !1565, file: !1080, line: 99, type: !1677, scopeLine: 99, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1677 = !DISubroutineType(types: !1678)
!1678 = !{null, !1675, !1679}
!1679 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1680, size: 64)
!1680 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1568)
!1681 = !DISubprogram(name: "_Vector_impl", scope: !1565, file: !1080, line: 104, type: !1682, scopeLine: 104, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1682 = !DISubroutineType(types: !1683)
!1683 = !{null, !1675, !1684}
!1684 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1568, size: 64)
!1685 = !DISubprogram(name: "_M_swap_data", linkageName: "_ZNSt12_Vector_baseINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE12_Vector_impl12_M_swap_dataERS8_", scope: !1565, file: !1080, line: 110, type: !1686, scopeLine: 110, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1686 = !DISubroutineType(types: !1687)
!1687 = !{null, !1675, !1688}
!1688 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1565, size: 64)
!1689 = !DISubprogram(name: "_M_get_Tp_allocator", linkageName: "_ZNSt12_Vector_baseINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE19_M_get_Tp_allocatorEv", scope: !1562, file: !1080, line: 237, type: !1690, scopeLine: 237, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1690 = !DISubroutineType(types: !1691)
!1691 = !{!1692, !1693}
!1692 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1568, size: 64)
!1693 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1562, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1694 = !DISubprogram(name: "_M_get_Tp_allocator", linkageName: "_ZNKSt12_Vector_baseINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE19_M_get_Tp_allocatorEv", scope: !1562, file: !1080, line: 241, type: !1695, scopeLine: 241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1695 = !DISubroutineType(types: !1696)
!1696 = !{!1679, !1697}
!1697 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1698, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1698 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1562)
!1699 = !DISubprogram(name: "get_allocator", linkageName: "_ZNKSt12_Vector_baseINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE13get_allocatorEv", scope: !1562, file: !1080, line: 245, type: !1700, scopeLine: 245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1700 = !DISubroutineType(types: !1701)
!1701 = !{!1702, !1697}
!1702 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !1562, file: !1080, line: 234, baseType: !1583)
!1703 = !DISubprogram(name: "_Vector_base", scope: !1562, file: !1080, line: 248, type: !1704, scopeLine: 248, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1704 = !DISubroutineType(types: !1705)
!1705 = !{null, !1693}
!1706 = !DISubprogram(name: "_Vector_base", scope: !1562, file: !1080, line: 251, type: !1707, scopeLine: 251, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1707 = !DISubroutineType(types: !1708)
!1708 = !{null, !1693, !1709}
!1709 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1710, size: 64)
!1710 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1702)
!1711 = !DISubprogram(name: "_Vector_base", scope: !1562, file: !1080, line: 254, type: !1712, scopeLine: 254, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1712 = !DISubroutineType(types: !1713)
!1713 = !{null, !1693, !1152}
!1714 = !DISubprogram(name: "_Vector_base", scope: !1562, file: !1080, line: 258, type: !1715, scopeLine: 258, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1715 = !DISubroutineType(types: !1716)
!1716 = !{null, !1693, !1152, !1709}
!1717 = !DISubprogram(name: "_Vector_base", scope: !1562, file: !1080, line: 263, type: !1718, scopeLine: 263, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1718 = !DISubroutineType(types: !1719)
!1719 = !{null, !1693, !1684}
!1720 = !DISubprogram(name: "_Vector_base", scope: !1562, file: !1080, line: 266, type: !1721, scopeLine: 266, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1721 = !DISubroutineType(types: !1722)
!1722 = !{null, !1693, !1723}
!1723 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1562, size: 64)
!1724 = !DISubprogram(name: "_Vector_base", scope: !1562, file: !1080, line: 270, type: !1725, scopeLine: 270, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1725 = !DISubroutineType(types: !1726)
!1726 = !{null, !1693, !1723, !1709}
!1727 = !DISubprogram(name: "~_Vector_base", scope: !1562, file: !1080, line: 283, type: !1704, scopeLine: 283, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1728 = !DISubprogram(name: "_M_allocate", linkageName: "_ZNSt12_Vector_baseINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE11_M_allocateEm", scope: !1562, file: !1080, line: 293, type: !1729, scopeLine: 293, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1729 = !DISubroutineType(types: !1730)
!1730 = !{!1668, !1693, !1152}
!1731 = !DISubprogram(name: "_M_deallocate", linkageName: "_ZNSt12_Vector_baseINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE13_M_deallocateEPS5_m", scope: !1562, file: !1080, line: 300, type: !1732, scopeLine: 300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1732 = !DISubroutineType(types: !1733)
!1733 = !{null, !1693, !1668, !1152}
!1734 = !DISubprogram(name: "_M_create_storage", linkageName: "_ZNSt12_Vector_baseINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE17_M_create_storageEm", scope: !1562, file: !1080, line: 309, type: !1712, scopeLine: 309, flags: DIFlagPrivate | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1735 = !{!1624, !1651}
!1736 = !DISubprogram(name: "vector", scope: !1559, file: !1080, line: 391, type: !1737, scopeLine: 391, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1737 = !DISubroutineType(types: !1738)
!1738 = !{null, !1739}
!1739 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1559, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1740 = !DISubprogram(name: "vector", scope: !1559, file: !1080, line: 402, type: !1741, scopeLine: 402, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1741 = !DISubroutineType(types: !1742)
!1742 = !{null, !1739, !1743}
!1743 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1744, size: 64)
!1744 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1745)
!1745 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !1559, file: !1080, line: 376, baseType: !1583)
!1746 = !DISubprogram(name: "vector", scope: !1559, file: !1080, line: 415, type: !1747, scopeLine: 415, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1747 = !DISubroutineType(types: !1748)
!1748 = !{null, !1739, !1292, !1743}
!1749 = !DISubprogram(name: "vector", scope: !1559, file: !1080, line: 427, type: !1750, scopeLine: 427, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1750 = !DISubroutineType(types: !1751)
!1751 = !{null, !1739, !1292, !1752, !1743}
!1752 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1753, size: 64)
!1753 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1754)
!1754 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1559, file: !1080, line: 364, baseType: !193)
!1755 = !DISubprogram(name: "vector", scope: !1559, file: !1080, line: 458, type: !1756, scopeLine: 458, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1756 = !DISubroutineType(types: !1757)
!1757 = !{null, !1739, !1758}
!1758 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1759, size: 64)
!1759 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1559)
!1760 = !DISubprogram(name: "vector", scope: !1559, file: !1080, line: 476, type: !1761, scopeLine: 476, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1761 = !DISubroutineType(types: !1762)
!1762 = !{null, !1739, !1763}
!1763 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1559, size: 64)
!1764 = !DISubprogram(name: "vector", scope: !1559, file: !1080, line: 480, type: !1765, scopeLine: 480, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1765 = !DISubroutineType(types: !1766)
!1766 = !{null, !1739, !1758, !1743}
!1767 = !DISubprogram(name: "vector", scope: !1559, file: !1080, line: 490, type: !1768, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1768 = !DISubroutineType(types: !1769)
!1769 = !{null, !1739, !1763, !1743}
!1770 = !DISubprogram(name: "vector", scope: !1559, file: !1080, line: 515, type: !1771, scopeLine: 515, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1771 = !DISubroutineType(types: !1772)
!1772 = !{null, !1739, !1773, !1743}
!1773 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >", scope: !192, file: !1318, line: 47, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE")
!1774 = !DISubprogram(name: "~vector", scope: !1559, file: !1080, line: 565, type: !1737, scopeLine: 565, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1775 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EEaSERKS7_", scope: !1559, file: !1080, line: 582, type: !1776, scopeLine: 582, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1776 = !DISubroutineType(types: !1777)
!1777 = !{!1778, !1739, !1758}
!1778 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1559, size: 64)
!1779 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EEaSEOS7_", scope: !1559, file: !1080, line: 596, type: !1780, scopeLine: 596, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1780 = !DISubroutineType(types: !1781)
!1781 = !{!1778, !1739, !1763}
!1782 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EEaSESt16initializer_listIS5_E", scope: !1559, file: !1080, line: 617, type: !1783, scopeLine: 617, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1783 = !DISubroutineType(types: !1784)
!1784 = !{!1778, !1739, !1773}
!1785 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE6assignEmRKS5_", scope: !1559, file: !1080, line: 636, type: !1786, scopeLine: 636, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1786 = !DISubroutineType(types: !1787)
!1787 = !{null, !1739, !1292, !1752}
!1788 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE6assignESt16initializer_listIS5_E", scope: !1559, file: !1080, line: 681, type: !1789, scopeLine: 681, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1789 = !DISubroutineType(types: !1790)
!1790 = !{null, !1739, !1773}
!1791 = !DISubprogram(name: "begin", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE5beginEv", scope: !1559, file: !1080, line: 698, type: !1792, scopeLine: 698, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1792 = !DISubroutineType(types: !1793)
!1793 = !{!1794, !1739}
!1794 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1559, file: !1080, line: 369, baseType: !1795)
!1795 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > *, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >", scope: !5, file: !631, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1796, templateParams: !1847, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEE")
!1796 = !{!1797, !1798, !1802, !1807, !1817, !1822, !1826, !1829, !1830, !1831, !1836, !1839, !1842, !1843, !1844}
!1797 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !1795, file: !631, line: 767, baseType: !1580, size: 64, flags: DIFlagProtected)
!1798 = !DISubprogram(name: "__normal_iterator", scope: !1795, file: !631, line: 779, type: !1799, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1799 = !DISubroutineType(types: !1800)
!1800 = !{null, !1801}
!1801 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1795, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1802 = !DISubprogram(name: "__normal_iterator", scope: !1795, file: !631, line: 783, type: !1803, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1803 = !DISubroutineType(types: !1804)
!1804 = !{null, !1801, !1805}
!1805 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1806, size: 64)
!1806 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1580)
!1807 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEdeEv", scope: !1795, file: !631, line: 796, type: !1808, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1808 = !DISubroutineType(types: !1809)
!1809 = !{!1810, !1815}
!1810 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1795, file: !631, line: 776, baseType: !1811)
!1811 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1812, file: !1357, line: 184, baseType: !1605)
!1812 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > *>", scope: !192, file: !1357, line: 178, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !1813, identifier: "_ZTSSt15iterator_traitsIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE")
!1813 = !{!1814}
!1814 = !DITemplateTypeParameter(name: "_Iterator", type: !1580)
!1815 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1816, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1816 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1795)
!1817 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEptEv", scope: !1795, file: !631, line: 800, type: !1818, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1818 = !DISubroutineType(types: !1819)
!1819 = !{!1820, !1815}
!1820 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1795, file: !631, line: 777, baseType: !1821)
!1821 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1812, file: !1357, line: 183, baseType: !1580)
!1822 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEppEv", scope: !1795, file: !631, line: 804, type: !1823, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1823 = !DISubroutineType(types: !1824)
!1824 = !{!1825, !1801}
!1825 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1795, size: 64)
!1826 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEppEi", scope: !1795, file: !631, line: 811, type: !1827, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1827 = !DISubroutineType(types: !1828)
!1828 = !{!1795, !1801, !24}
!1829 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEmmEv", scope: !1795, file: !631, line: 816, type: !1823, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1830 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEmmEi", scope: !1795, file: !631, line: 823, type: !1827, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1831 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEixEl", scope: !1795, file: !631, line: 828, type: !1832, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1832 = !DISubroutineType(types: !1833)
!1833 = !{!1810, !1815, !1834}
!1834 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1795, file: !631, line: 775, baseType: !1835)
!1835 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1812, file: !1357, line: 182, baseType: !1382)
!1836 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEpLEl", scope: !1795, file: !631, line: 832, type: !1837, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1837 = !DISubroutineType(types: !1838)
!1838 = !{!1825, !1801, !1834}
!1839 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEplEl", scope: !1795, file: !631, line: 836, type: !1840, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1840 = !DISubroutineType(types: !1841)
!1841 = !{!1795, !1815, !1834}
!1842 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEmIEl", scope: !1795, file: !631, line: 840, type: !1837, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1843 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEmiEl", scope: !1795, file: !631, line: 844, type: !1840, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1844 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEE4baseEv", scope: !1795, file: !631, line: 848, type: !1845, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1845 = !DISubroutineType(types: !1846)
!1846 = !{!1805, !1815}
!1847 = !{!1814, !1848}
!1848 = !DITemplateTypeParameter(name: "_Container", type: !1559)
!1849 = !DISubprogram(name: "begin", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE5beginEv", scope: !1559, file: !1080, line: 707, type: !1850, scopeLine: 707, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1850 = !DISubroutineType(types: !1851)
!1851 = !{!1852, !1906}
!1852 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !1559, file: !1080, line: 371, baseType: !1853)
!1853 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > *, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >", scope: !5, file: !631, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1854, templateParams: !1905, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEE")
!1854 = !{!1855, !1856, !1860, !1865, !1875, !1880, !1884, !1887, !1888, !1889, !1894, !1897, !1900, !1901, !1902}
!1855 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !1853, file: !631, line: 767, baseType: !1610, size: 64, flags: DIFlagProtected)
!1856 = !DISubprogram(name: "__normal_iterator", scope: !1853, file: !631, line: 779, type: !1857, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1857 = !DISubroutineType(types: !1858)
!1858 = !{null, !1859}
!1859 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1853, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1860 = !DISubprogram(name: "__normal_iterator", scope: !1853, file: !631, line: 783, type: !1861, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1861 = !DISubroutineType(types: !1862)
!1862 = !{null, !1859, !1863}
!1863 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1864, size: 64)
!1864 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1610)
!1865 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEdeEv", scope: !1853, file: !631, line: 796, type: !1866, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1866 = !DISubroutineType(types: !1867)
!1867 = !{!1868, !1873}
!1868 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1853, file: !631, line: 776, baseType: !1869)
!1869 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1870, file: !1357, line: 195, baseType: !1613)
!1870 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > *>", scope: !192, file: !1357, line: 189, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !1871, identifier: "_ZTSSt15iterator_traitsIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE")
!1871 = !{!1872}
!1872 = !DITemplateTypeParameter(name: "_Iterator", type: !1610)
!1873 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1874, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1874 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1853)
!1875 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEptEv", scope: !1853, file: !631, line: 800, type: !1876, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1876 = !DISubroutineType(types: !1877)
!1877 = !{!1878, !1873}
!1878 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1853, file: !631, line: 777, baseType: !1879)
!1879 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1870, file: !1357, line: 194, baseType: !1610)
!1880 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEppEv", scope: !1853, file: !631, line: 804, type: !1881, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1881 = !DISubroutineType(types: !1882)
!1882 = !{!1883, !1859}
!1883 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1853, size: 64)
!1884 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEppEi", scope: !1853, file: !631, line: 811, type: !1885, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1885 = !DISubroutineType(types: !1886)
!1886 = !{!1853, !1859, !24}
!1887 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEmmEv", scope: !1853, file: !631, line: 816, type: !1881, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1888 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEmmEi", scope: !1853, file: !631, line: 823, type: !1885, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1889 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEixEl", scope: !1853, file: !631, line: 828, type: !1890, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1890 = !DISubroutineType(types: !1891)
!1891 = !{!1868, !1873, !1892}
!1892 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1853, file: !631, line: 775, baseType: !1893)
!1893 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1870, file: !1357, line: 193, baseType: !1382)
!1894 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEpLEl", scope: !1853, file: !631, line: 832, type: !1895, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1895 = !DISubroutineType(types: !1896)
!1896 = !{!1883, !1859, !1892}
!1897 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEplEl", scope: !1853, file: !631, line: 836, type: !1898, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1898 = !DISubroutineType(types: !1899)
!1899 = !{!1853, !1873, !1892}
!1900 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEmIEl", scope: !1853, file: !631, line: 840, type: !1895, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1901 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEEmiEl", scope: !1853, file: !631, line: 844, type: !1898, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1902 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS6_SaIS6_EEE4baseEv", scope: !1853, file: !631, line: 848, type: !1903, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1903 = !DISubroutineType(types: !1904)
!1904 = !{!1863, !1873}
!1905 = !{!1872, !1848}
!1906 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1759, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1907 = !DISubprogram(name: "end", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE3endEv", scope: !1559, file: !1080, line: 716, type: !1792, scopeLine: 716, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1908 = !DISubprogram(name: "end", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE3endEv", scope: !1559, file: !1080, line: 725, type: !1850, scopeLine: 725, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1909 = !DISubprogram(name: "rbegin", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE6rbeginEv", scope: !1559, file: !1080, line: 734, type: !1910, scopeLine: 734, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1910 = !DISubroutineType(types: !1911)
!1911 = !{!1912, !1739}
!1912 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !1559, file: !1080, line: 373, baseType: !1913)
!1913 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > *, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >", scope: !192, file: !631, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS7_SaIS7_EEEEE")
!1914 = !DISubprogram(name: "rbegin", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE6rbeginEv", scope: !1559, file: !1080, line: 743, type: !1915, scopeLine: 743, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1915 = !DISubroutineType(types: !1916)
!1916 = !{!1917, !1906}
!1917 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !1559, file: !1080, line: 372, baseType: !1918)
!1918 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > *, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >", scope: !192, file: !631, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIS7_SaIS7_EEEEE")
!1919 = !DISubprogram(name: "rend", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE4rendEv", scope: !1559, file: !1080, line: 752, type: !1910, scopeLine: 752, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1920 = !DISubprogram(name: "rend", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE4rendEv", scope: !1559, file: !1080, line: 761, type: !1915, scopeLine: 761, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1921 = !DISubprogram(name: "cbegin", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE6cbeginEv", scope: !1559, file: !1080, line: 771, type: !1850, scopeLine: 771, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1922 = !DISubprogram(name: "cend", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE4cendEv", scope: !1559, file: !1080, line: 780, type: !1850, scopeLine: 780, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1923 = !DISubprogram(name: "crbegin", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE7crbeginEv", scope: !1559, file: !1080, line: 789, type: !1915, scopeLine: 789, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1924 = !DISubprogram(name: "crend", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE5crendEv", scope: !1559, file: !1080, line: 798, type: !1915, scopeLine: 798, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1925 = !DISubprogram(name: "size", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE4sizeEv", scope: !1559, file: !1080, line: 805, type: !1926, scopeLine: 805, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1926 = !DISubroutineType(types: !1927)
!1927 = !{!1292, !1906}
!1928 = !DISubprogram(name: "max_size", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE8max_sizeEv", scope: !1559, file: !1080, line: 810, type: !1926, scopeLine: 810, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1929 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE6resizeEm", scope: !1559, file: !1080, line: 824, type: !1930, scopeLine: 824, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1930 = !DISubroutineType(types: !1931)
!1931 = !{null, !1739, !1292}
!1932 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE6resizeEmRKS5_", scope: !1559, file: !1080, line: 844, type: !1786, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1933 = !DISubprogram(name: "shrink_to_fit", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE13shrink_to_fitEv", scope: !1559, file: !1080, line: 876, type: !1737, scopeLine: 876, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1934 = !DISubprogram(name: "capacity", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE8capacityEv", scope: !1559, file: !1080, line: 885, type: !1926, scopeLine: 885, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1935 = !DISubprogram(name: "empty", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE5emptyEv", scope: !1559, file: !1080, line: 894, type: !1936, scopeLine: 894, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1936 = !DISubroutineType(types: !1937)
!1937 = !{!132, !1906}
!1938 = !DISubprogram(name: "reserve", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE7reserveEm", scope: !1559, file: !1080, line: 915, type: !1930, scopeLine: 915, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1939 = !DISubprogram(name: "operator[]", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EEixEm", scope: !1559, file: !1080, line: 930, type: !1940, scopeLine: 930, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1940 = !DISubroutineType(types: !1941)
!1941 = !{!1942, !1739, !1292}
!1942 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1559, file: !1080, line: 367, baseType: !1943)
!1943 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1571, file: !1091, line: 64, baseType: !1944)
!1944 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1945, size: 64)
!1945 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1571, file: !1091, line: 58, baseType: !1946)
!1946 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1574, file: !1097, line: 389, baseType: !193)
!1947 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EEixEm", scope: !1559, file: !1080, line: 948, type: !1948, scopeLine: 948, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1948 = !DISubroutineType(types: !1949)
!1949 = !{!1950, !1906, !1292}
!1950 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1559, file: !1080, line: 368, baseType: !1951)
!1951 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1571, file: !1091, line: 65, baseType: !1952)
!1952 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1953, size: 64)
!1953 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1945)
!1954 = !DISubprogram(name: "_M_range_check", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE14_M_range_checkEm", scope: !1559, file: !1080, line: 957, type: !1955, scopeLine: 957, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1955 = !DISubroutineType(types: !1956)
!1956 = !{null, !1906, !1292}
!1957 = !DISubprogram(name: "at", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE2atEm", scope: !1559, file: !1080, line: 979, type: !1940, scopeLine: 979, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1958 = !DISubprogram(name: "at", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE2atEm", scope: !1559, file: !1080, line: 997, type: !1948, scopeLine: 997, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1959 = !DISubprogram(name: "front", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE5frontEv", scope: !1559, file: !1080, line: 1008, type: !1960, scopeLine: 1008, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1960 = !DISubroutineType(types: !1961)
!1961 = !{!1942, !1739}
!1962 = !DISubprogram(name: "front", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE5frontEv", scope: !1559, file: !1080, line: 1019, type: !1963, scopeLine: 1019, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1963 = !DISubroutineType(types: !1964)
!1964 = !{!1950, !1906}
!1965 = !DISubprogram(name: "back", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE4backEv", scope: !1559, file: !1080, line: 1030, type: !1960, scopeLine: 1030, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1966 = !DISubprogram(name: "back", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE4backEv", scope: !1559, file: !1080, line: 1041, type: !1963, scopeLine: 1041, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1967 = !DISubprogram(name: "data", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE4dataEv", scope: !1559, file: !1080, line: 1055, type: !1968, scopeLine: 1055, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1968 = !DISubroutineType(types: !1969)
!1969 = !{!1580, !1739}
!1970 = !DISubprogram(name: "data", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE4dataEv", scope: !1559, file: !1080, line: 1059, type: !1971, scopeLine: 1059, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1971 = !DISubroutineType(types: !1972)
!1972 = !{!1610, !1906}
!1973 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE9push_backERKS5_", scope: !1559, file: !1080, line: 1074, type: !1974, scopeLine: 1074, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1974 = !DISubroutineType(types: !1975)
!1975 = !{null, !1739, !1752}
!1976 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE9push_backEOS5_", scope: !1559, file: !1080, line: 1090, type: !1977, scopeLine: 1090, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1977 = !DISubroutineType(types: !1978)
!1978 = !{null, !1739, !1979}
!1979 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1754, size: 64)
!1980 = !DISubprogram(name: "pop_back", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE8pop_backEv", scope: !1559, file: !1080, line: 1112, type: !1737, scopeLine: 1112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1981 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS5_S7_EERSA_", scope: !1559, file: !1080, line: 1150, type: !1982, scopeLine: 1150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1982 = !DISubroutineType(types: !1983)
!1983 = !{!1794, !1739, !1852, !1752}
!1984 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS5_S7_EEOS5_", scope: !1559, file: !1080, line: 1180, type: !1985, scopeLine: 1180, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1985 = !DISubroutineType(types: !1986)
!1986 = !{!1794, !1739, !1852, !1979}
!1987 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS5_S7_EESt16initializer_listIS5_E", scope: !1559, file: !1080, line: 1197, type: !1988, scopeLine: 1197, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1988 = !DISubroutineType(types: !1989)
!1989 = !{!1794, !1739, !1852, !1773}
!1990 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS5_S7_EEmRSA_", scope: !1559, file: !1080, line: 1222, type: !1991, scopeLine: 1222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1991 = !DISubroutineType(types: !1992)
!1992 = !{!1794, !1739, !1852, !1292, !1752}
!1993 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE5eraseEN9__gnu_cxx17__normal_iteratorIPKS5_S7_EE", scope: !1559, file: !1080, line: 1317, type: !1994, scopeLine: 1317, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1994 = !DISubroutineType(types: !1995)
!1995 = !{!1794, !1739, !1852}
!1996 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE5eraseEN9__gnu_cxx17__normal_iteratorIPKS5_S7_EESC_", scope: !1559, file: !1080, line: 1344, type: !1997, scopeLine: 1344, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1997 = !DISubroutineType(types: !1998)
!1998 = !{!1794, !1739, !1852, !1852}
!1999 = !DISubprogram(name: "swap", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE4swapERS7_", scope: !1559, file: !1080, line: 1367, type: !2000, scopeLine: 1367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2000 = !DISubroutineType(types: !2001)
!2001 = !{null, !1739, !1778}
!2002 = !DISubprogram(name: "clear", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE5clearEv", scope: !1559, file: !1080, line: 1385, type: !1737, scopeLine: 1385, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2003 = !DISubprogram(name: "_M_fill_initialize", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE18_M_fill_initializeEmRKS5_", scope: !1559, file: !1080, line: 1477, type: !1786, scopeLine: 1477, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2004 = !DISubprogram(name: "_M_default_initialize", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE21_M_default_initializeEm", scope: !1559, file: !1080, line: 1487, type: !1930, scopeLine: 1487, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2005 = !DISubprogram(name: "_M_fill_assign", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE14_M_fill_assignEmRKS5_", scope: !1559, file: !1080, line: 1529, type: !1786, scopeLine: 1529, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2006 = !DISubprogram(name: "_M_fill_insert", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS5_S7_EEmRKS5_", scope: !1559, file: !1080, line: 1568, type: !2007, scopeLine: 1568, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2007 = !DISubroutineType(types: !2008)
!2008 = !{null, !1739, !1794, !1292, !1752}
!2009 = !DISubprogram(name: "_M_default_append", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE17_M_default_appendEm", scope: !1559, file: !1080, line: 1573, type: !1930, scopeLine: 1573, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2010 = !DISubprogram(name: "_M_shrink_to_fit", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE16_M_shrink_to_fitEv", scope: !1559, file: !1080, line: 1576, type: !2011, scopeLine: 1576, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2011 = !DISubroutineType(types: !2012)
!2012 = !{!132, !1739}
!2013 = !DISubprogram(name: "_M_insert_rval", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE14_M_insert_rvalEN9__gnu_cxx17__normal_iteratorIPKS5_S7_EEOS5_", scope: !1559, file: !1080, line: 1625, type: !1985, scopeLine: 1625, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2014 = !DISubprogram(name: "_M_emplace_aux", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE14_M_emplace_auxEN9__gnu_cxx17__normal_iteratorIPKS5_S7_EEOS5_", scope: !1559, file: !1080, line: 1634, type: !1985, scopeLine: 1634, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2015 = !DISubprogram(name: "_M_check_len", linkageName: "_ZNKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE12_M_check_lenEmPKc", scope: !1559, file: !1080, line: 1640, type: !2016, scopeLine: 1640, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2016 = !DISubroutineType(types: !2017)
!2017 = !{!2018, !1906, !1292, !163}
!2018 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1559, file: !1080, line: 374, baseType: !1152)
!2019 = !DISubprogram(name: "_M_erase_at_end", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE15_M_erase_at_endEPS5_", scope: !1559, file: !1080, line: 1654, type: !2020, scopeLine: 1654, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2020 = !DISubroutineType(types: !2021)
!2021 = !{null, !1739, !2022}
!2022 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1559, file: !1080, line: 365, baseType: !1668)
!2023 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE8_M_eraseEN9__gnu_cxx17__normal_iteratorIPS5_S7_EE", scope: !1559, file: !1080, line: 1666, type: !2024, scopeLine: 1666, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2024 = !DISubroutineType(types: !2025)
!2025 = !{!1794, !1739, !1794}
!2026 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE8_M_eraseEN9__gnu_cxx17__normal_iteratorIPS5_S7_EESB_", scope: !1559, file: !1080, line: 1669, type: !2027, scopeLine: 1669, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2027 = !DISubroutineType(types: !2028)
!2028 = !{!1794, !1739, !1794, !1794}
!2029 = !DISubprogram(name: "_M_move_assign", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE14_M_move_assignEOS7_St17integral_constantIbLb1EE", scope: !1559, file: !1080, line: 1677, type: !2030, scopeLine: 1677, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2030 = !DISubroutineType(types: !2031)
!2031 = !{null, !1739, !1763, !1527}
!2032 = !DISubprogram(name: "_M_move_assign", linkageName: "_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EE14_M_move_assignEOS7_St17integral_constantIbLb0EE", scope: !1559, file: !1080, line: 1688, type: !2033, scopeLine: 1688, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2033 = !DISubroutineType(types: !2034)
!2034 = !{null, !1739, !1763, !1545}
!2035 = !DIDerivedType(tag: DW_TAG_member, name: "LineNoCache", scope: !1076, file: !1075, line: 66, baseType: !121, size: 64, offset: 384)
!2036 = !DIDerivedType(tag: DW_TAG_member, name: "DiagHandler", scope: !1076, file: !1075, line: 68, baseType: !2037, size: 64, offset: 448)
!2037 = !DIDerivedType(tag: DW_TAG_typedef, name: "DiagHandlerTy", scope: !1076, file: !1075, line: 46, baseType: !2038)
!2038 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2039, size: 64)
!2039 = !DISubroutineType(types: !2040)
!2040 = !{null, !2041, !121}
!2041 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2042, size: 64)
!2042 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2043)
!2043 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SMDiagnostic", scope: !14, file: !1075, line: 212, size: 2944, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12SMDiagnosticE")
!2044 = !DIDerivedType(tag: DW_TAG_member, name: "DiagContext", scope: !1076, file: !1075, line: 69, baseType: !121, size: 64, offset: 512)
!2045 = !DISubprogram(name: "SourceMgr", scope: !1076, file: !1075, line: 71, type: !2046, scopeLine: 71, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2046 = !DISubroutineType(types: !2047)
!2047 = !{null, !2048, !2049}
!2048 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1076, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2049 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2050, size: 64)
!2050 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1076)
!2051 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm9SourceMgraSERKS0_", scope: !1076, file: !1075, line: 72, type: !2046, scopeLine: 72, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2052 = !DISubprogram(name: "SourceMgr", scope: !1076, file: !1075, line: 74, type: !2053, scopeLine: 74, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2053 = !DISubroutineType(types: !2054)
!2054 = !{null, !2048}
!2055 = !DISubprogram(name: "~SourceMgr", scope: !1076, file: !1075, line: 75, type: !2053, scopeLine: 75, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2056 = !DISubprogram(name: "setIncludeDirs", linkageName: "_ZN4llvm9SourceMgr14setIncludeDirsERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE", scope: !1076, file: !1075, line: 77, type: !2057, scopeLine: 77, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2057 = !DISubroutineType(types: !2058)
!2058 = !{null, !2048, !1758}
!2059 = !DISubprogram(name: "setDiagHandler", linkageName: "_ZN4llvm9SourceMgr14setDiagHandlerEPFvRKNS_12SMDiagnosticEPvES4_", scope: !1076, file: !1075, line: 83, type: !2060, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2060 = !DISubroutineType(types: !2061)
!2061 = !{null, !2048, !2037, !121}
!2062 = !DISubprogram(name: "getDiagHandler", linkageName: "_ZNK4llvm9SourceMgr14getDiagHandlerEv", scope: !1076, file: !1075, line: 88, type: !2063, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2063 = !DISubroutineType(types: !2064)
!2064 = !{!2037, !2065}
!2065 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2050, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2066 = !DISubprogram(name: "getDiagContext", linkageName: "_ZNK4llvm9SourceMgr14getDiagContextEv", scope: !1076, file: !1075, line: 89, type: !2067, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2067 = !DISubroutineType(types: !2068)
!2068 = !{!121, !2065}
!2069 = !DISubprogram(name: "getBufferInfo", linkageName: "_ZNK4llvm9SourceMgr13getBufferInfoEj", scope: !1076, file: !1075, line: 91, type: !2070, scopeLine: 91, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2070 = !DISubroutineType(types: !2071)
!2071 = !{!1147, !2065, !6}
!2072 = !DISubprogram(name: "getMemoryBuffer", linkageName: "_ZNK4llvm9SourceMgr15getMemoryBufferEj", scope: !1076, file: !1075, line: 96, type: !2073, scopeLine: 96, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2073 = !DISubroutineType(types: !2074)
!2074 = !{!2075, !2065, !6}
!2075 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2076, size: 64)
!2076 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1108)
!2077 = !DISubprogram(name: "getNumBuffers", linkageName: "_ZNK4llvm9SourceMgr13getNumBuffersEv", scope: !1076, file: !1075, line: 101, type: !2078, scopeLine: 101, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2078 = !DISubroutineType(types: !2079)
!2079 = !{!159, !2065}
!2080 = !DISubprogram(name: "getParentIncludeLoc", linkageName: "_ZNK4llvm9SourceMgr19getParentIncludeLocEj", scope: !1076, file: !1075, line: 105, type: !2081, scopeLine: 105, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2081 = !DISubroutineType(types: !2082)
!2082 = !{!1110, !2065, !6}
!2083 = !DISubprogram(name: "AddNewSourceBuffer", linkageName: "_ZN4llvm9SourceMgr18AddNewSourceBufferEPNS_12MemoryBufferENS_5SMLocE", scope: !1076, file: !1075, line: 112, type: !2084, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2084 = !DISubroutineType(types: !2085)
!2085 = !{!159, !2048, !1107, !1110}
!2086 = !DISubprogram(name: "AddIncludeFile", linkageName: "_ZN4llvm9SourceMgr14AddIncludeFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_5SMLocERS6_", scope: !1076, file: !1075, line: 124, type: !2087, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2087 = !DISubroutineType(types: !2088)
!2088 = !{!159, !2048, !187, !1110, !2089}
!2089 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !189, size: 64)
!2090 = !DISubprogram(name: "FindBufferContainingLoc", linkageName: "_ZNK4llvm9SourceMgr23FindBufferContainingLocENS_5SMLocE", scope: !1076, file: !1075, line: 129, type: !2091, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2091 = !DISubroutineType(types: !2092)
!2092 = !{!24, !2065, !1110}
!2093 = !DISubprogram(name: "FindLineNumber", linkageName: "_ZNK4llvm9SourceMgr14FindLineNumberENS_5SMLocEi", scope: !1076, file: !1075, line: 133, type: !2094, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2094 = !DISubroutineType(types: !2095)
!2095 = !{!6, !2065, !1110, !24}
!2096 = !DISubprogram(name: "getLineAndColumn", linkageName: "_ZNK4llvm9SourceMgr16getLineAndColumnENS_5SMLocEi", scope: !1076, file: !1075, line: 140, type: !2097, scopeLine: 140, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2097 = !DISubroutineType(types: !2098)
!2098 = !{!2099, !2065, !1110, !24}
!2099 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<unsigned int, unsigned int>", scope: !192, file: !279, line: 208, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2100, templateParams: !2151, identifier: "_ZTSSt4pairIjjE")
!2100 = !{!2101, !2121, !2122, !2123, !2129, !2133, !2141, !2148}
!2101 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2099, baseType: !2102, flags: DIFlagPrivate, extraData: i32 0)
!2102 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<unsigned int, unsigned int>", scope: !192, file: !279, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !2103, templateParams: !2118, identifier: "_ZTSSt11__pair_baseIjjE")
!2103 = !{!2104, !2108, !2109, !2114}
!2104 = !DISubprogram(name: "__pair_base", scope: !2102, file: !279, line: 194, type: !2105, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2105 = !DISubroutineType(types: !2106)
!2106 = !{null, !2107}
!2107 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2102, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2108 = !DISubprogram(name: "~__pair_base", scope: !2102, file: !279, line: 195, type: !2105, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2109 = !DISubprogram(name: "__pair_base", scope: !2102, file: !279, line: 196, type: !2110, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2110 = !DISubroutineType(types: !2111)
!2111 = !{null, !2107, !2112}
!2112 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2113, size: 64)
!2113 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2102)
!2114 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIjjEaSERKS0_", scope: !2102, file: !279, line: 197, type: !2115, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2115 = !DISubroutineType(types: !2116)
!2116 = !{!2117, !2107, !2112}
!2117 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2102, size: 64)
!2118 = !{!2119, !2120}
!2119 = !DITemplateTypeParameter(name: "_U1", type: !6)
!2120 = !DITemplateTypeParameter(name: "_U2", type: !6)
!2121 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !2099, file: !279, line: 214, baseType: !6, size: 32)
!2122 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !2099, file: !279, line: 215, baseType: !6, size: 32, offset: 32)
!2123 = !DISubprogram(name: "pair", scope: !2099, file: !279, line: 303, type: !2124, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2124 = !DISubroutineType(types: !2125)
!2125 = !{null, !2126, !2127}
!2126 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2099, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2127 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2128, size: 64)
!2128 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2099)
!2129 = !DISubprogram(name: "pair", scope: !2099, file: !279, line: 304, type: !2130, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2130 = !DISubroutineType(types: !2131)
!2131 = !{null, !2126, !2132}
!2132 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2099, size: 64)
!2133 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIjjEaSERKS0_", scope: !2099, file: !279, line: 378, type: !2134, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2134 = !DISubroutineType(types: !2135)
!2135 = !{!2136, !2126, !2137}
!2136 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2099, size: 64)
!2137 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2138, file: !318, line: 1928, baseType: !2127)
!2138 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<unsigned int, unsigned int> &, const std::__nonesuch_no_braces &>", scope: !192, file: !318, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !2139, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIjjERKSt20__nonesuch_no_bracesE")
!2139 = !{!322, !2140, !324}
!2140 = !DITemplateTypeParameter(name: "_Iftrue", type: !2127)
!2141 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIjjEaSEOS0_", scope: !2099, file: !279, line: 389, type: !2142, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2142 = !DISubroutineType(types: !2143)
!2143 = !{!2136, !2126, !2144}
!2144 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2145, file: !318, line: 1928, baseType: !2132)
!2145 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<unsigned int, unsigned int> &&, std::__nonesuch_no_braces &&>", scope: !192, file: !318, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !2146, identifier: "_ZTSSt11conditionalILb1EOSt4pairIjjEOSt20__nonesuch_no_bracesE")
!2146 = !{!322, !2147, !335}
!2147 = !DITemplateTypeParameter(name: "_Iftrue", type: !2132)
!2148 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIjjE4swapERS0_", scope: !2099, file: !279, line: 424, type: !2149, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2149 = !DISubroutineType(types: !2150)
!2150 = !{null, !2126, !2136}
!2151 = !{!2152, !2153}
!2152 = !DITemplateTypeParameter(name: "_T1", type: !6)
!2153 = !DITemplateTypeParameter(name: "_T2", type: !6)
!2154 = !DISubprogram(name: "PrintMessage", linkageName: "_ZNK4llvm9SourceMgr12PrintMessageERNS_11raw_ostreamENS_5SMLocENS0_8DiagKindERKNS_5TwineENS_8ArrayRefINS_7SMRangeEEENS8_INS_7SMFixItEEEb", scope: !1076, file: !1075, line: 147, type: !2155, scopeLine: 147, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2155 = !DISubroutineType(types: !2156)
!2156 = !{null, !2065, !467, !1110, !1074, !381, !2157, !2238, !132}
!2157 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ArrayRef<llvm::SMRange>", scope: !14, file: !2158, line: 31, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2159, templateParams: !2236, identifier: "_ZTSN4llvm8ArrayRefINS_7SMRangeEEE")
!2158 = !DIFile(filename: "llvm34/include/llvm/ADT/ArrayRef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "6317ba9f99cd1980a6299fb308b36f31")
!2159 = !{!2160, !2164, !2166, !2170, !2177, !2181, !2184, !2187, !2193, !2199, !2200, !2205, !2206, !2209, !2212, !2215, !2218, !2219, !2222, !2225, !2228, !2231, !2235}
!2160 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !2157, file: !2158, line: 41, baseType: !2161, size: 64)
!2161 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2162, size: 64)
!2162 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2163)
!2163 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SMRange", scope: !14, file: !1111, line: 47, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm7SMRangeE")
!2164 = !DIDerivedType(tag: DW_TAG_member, name: "Length", scope: !2157, file: !2158, line: 44, baseType: !2165, size: 64, offset: 64)
!2165 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !2158, line: 35, baseType: !159)
!2166 = !DISubprogram(name: "ArrayRef", scope: !2157, file: !2158, line: 51, type: !2167, scopeLine: 51, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2167 = !DISubroutineType(types: !2168)
!2168 = !{null, !2169}
!2169 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2157, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2170 = !DISubprogram(name: "ArrayRef", scope: !2157, file: !2158, line: 54, type: !2171, scopeLine: 54, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2171 = !DISubroutineType(types: !2172)
!2172 = !{null, !2169, !2173}
!2173 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "NoneType", scope: !14, file: !2174, line: 22, baseType: !6, size: 32, elements: !2175, identifier: "_ZTSN4llvm8NoneTypeE")
!2174 = !DIFile(filename: "llvm34/include/llvm/ADT/None.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "a0342314f03a5b3ad15259d9915a8f1b")
!2175 = !{!2176}
!2176 = !DIEnumerator(name: "None", value: 0, isUnsigned: true)
!2177 = !DISubprogram(name: "ArrayRef", scope: !2157, file: !2158, line: 57, type: !2178, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2178 = !DISubroutineType(types: !2179)
!2179 = !{null, !2169, !2180}
!2180 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2162, size: 64)
!2181 = !DISubprogram(name: "ArrayRef", scope: !2157, file: !2158, line: 61, type: !2182, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2182 = !DISubroutineType(types: !2183)
!2183 = !{null, !2169, !2161, !159}
!2184 = !DISubprogram(name: "ArrayRef", scope: !2157, file: !2158, line: 65, type: !2185, scopeLine: 65, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2185 = !DISubroutineType(types: !2186)
!2186 = !{null, !2169, !2161, !2161}
!2187 = !DISubprogram(name: "ArrayRef", scope: !2157, file: !2158, line: 88, type: !2188, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2188 = !DISubroutineType(types: !2189)
!2189 = !{null, !2169, !2190}
!2190 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2191, size: 64)
!2191 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2192)
!2192 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<llvm::SMRange>", scope: !192, file: !1318, line: 47, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listIN4llvm7SMRangeEE")
!2193 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEE5beginEv", scope: !2157, file: !2158, line: 97, type: !2194, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2194 = !DISubroutineType(types: !2195)
!2195 = !{!2196, !2197}
!2196 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2157, file: !2158, line: 33, baseType: !2161)
!2197 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2198, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2198 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2157)
!2199 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEE3endEv", scope: !2157, file: !2158, line: 98, type: !2194, scopeLine: 98, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2200 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEE6rbeginEv", scope: !2157, file: !2158, line: 100, type: !2201, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2201 = !DISubroutineType(types: !2202)
!2202 = !{!2203, !2197}
!2203 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !2157, file: !2158, line: 37, baseType: !2204)
!2204 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const llvm::SMRange *>", scope: !192, file: !631, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKN4llvm7SMRangeEE")
!2205 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEE4rendEv", scope: !2157, file: !2158, line: 101, type: !2201, scopeLine: 101, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2206 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEE5emptyEv", scope: !2157, file: !2158, line: 104, type: !2207, scopeLine: 104, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2207 = !DISubroutineType(types: !2208)
!2208 = !{!132, !2197}
!2209 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEE4dataEv", scope: !2157, file: !2158, line: 106, type: !2210, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2210 = !DISubroutineType(types: !2211)
!2211 = !{!2161, !2197}
!2212 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEE4sizeEv", scope: !2157, file: !2158, line: 109, type: !2213, scopeLine: 109, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2213 = !DISubroutineType(types: !2214)
!2214 = !{!159, !2197}
!2215 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEE5frontEv", scope: !2157, file: !2158, line: 112, type: !2216, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2216 = !DISubroutineType(types: !2217)
!2217 = !{!2180, !2197}
!2218 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEE4backEv", scope: !2157, file: !2158, line: 118, type: !2216, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2219 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEE6equalsES2_", scope: !2157, file: !2158, line: 124, type: !2220, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2220 = !DISubroutineType(types: !2221)
!2221 = !{!132, !2197, !2157}
!2222 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEE5sliceEj", scope: !2157, file: !2158, line: 134, type: !2223, scopeLine: 134, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2223 = !DISubroutineType(types: !2224)
!2224 = !{!2157, !2197, !6}
!2225 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEE5sliceEjj", scope: !2157, file: !2158, line: 141, type: !2226, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2226 = !DISubroutineType(types: !2227)
!2227 = !{!2157, !2197, !6, !6}
!2228 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEEixEm", scope: !2157, file: !2158, line: 149, type: !2229, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2229 = !DISubroutineType(types: !2230)
!2230 = !{!2180, !2197, !159}
!2231 = !DISubprogram(name: "vec", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEE3vecEv", scope: !2157, file: !2158, line: 157, type: !2232, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2232 = !DISubroutineType(types: !2233)
!2233 = !{!2234, !2197}
!2234 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<llvm::SMRange, std::allocator<llvm::SMRange> >", scope: !192, file: !1080, line: 339, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt6vectorIN4llvm7SMRangeESaIS1_EE")
!2235 = !DISubprogram(name: "operator vector", linkageName: "_ZNK4llvm8ArrayRefINS_7SMRangeEEcvSt6vectorIS1_SaIS1_EEEv", scope: !2157, file: !2158, line: 164, type: !2232, scopeLine: 164, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2236 = !{!2237}
!2237 = !DITemplateTypeParameter(name: "T", type: !2163)
!2238 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ArrayRef<llvm::SMFixIt>", scope: !14, file: !2158, line: 31, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2239, templateParams: !2311, identifier: "_ZTSN4llvm8ArrayRefINS_7SMFixItEEE")
!2239 = !{!2240, !2244, !2245, !2249, !2252, !2256, !2259, !2262, !2268, !2274, !2275, !2280, !2281, !2284, !2287, !2290, !2293, !2294, !2297, !2300, !2303, !2306, !2310}
!2240 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !2238, file: !2158, line: 41, baseType: !2241, size: 64)
!2241 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2242, size: 64)
!2242 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2243)
!2243 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SMFixIt", scope: !14, file: !1075, line: 179, size: 384, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm7SMFixItE")
!2244 = !DIDerivedType(tag: DW_TAG_member, name: "Length", scope: !2238, file: !2158, line: 44, baseType: !2165, size: 64, offset: 64)
!2245 = !DISubprogram(name: "ArrayRef", scope: !2238, file: !2158, line: 51, type: !2246, scopeLine: 51, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2246 = !DISubroutineType(types: !2247)
!2247 = !{null, !2248}
!2248 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2238, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2249 = !DISubprogram(name: "ArrayRef", scope: !2238, file: !2158, line: 54, type: !2250, scopeLine: 54, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2250 = !DISubroutineType(types: !2251)
!2251 = !{null, !2248, !2173}
!2252 = !DISubprogram(name: "ArrayRef", scope: !2238, file: !2158, line: 57, type: !2253, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2253 = !DISubroutineType(types: !2254)
!2254 = !{null, !2248, !2255}
!2255 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2242, size: 64)
!2256 = !DISubprogram(name: "ArrayRef", scope: !2238, file: !2158, line: 61, type: !2257, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2257 = !DISubroutineType(types: !2258)
!2258 = !{null, !2248, !2241, !159}
!2259 = !DISubprogram(name: "ArrayRef", scope: !2238, file: !2158, line: 65, type: !2260, scopeLine: 65, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2260 = !DISubroutineType(types: !2261)
!2261 = !{null, !2248, !2241, !2241}
!2262 = !DISubprogram(name: "ArrayRef", scope: !2238, file: !2158, line: 88, type: !2263, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2263 = !DISubroutineType(types: !2264)
!2264 = !{null, !2248, !2265}
!2265 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2266, size: 64)
!2266 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2267)
!2267 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<llvm::SMFixIt>", scope: !192, file: !1318, line: 47, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listIN4llvm7SMFixItEE")
!2268 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEE5beginEv", scope: !2238, file: !2158, line: 97, type: !2269, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2269 = !DISubroutineType(types: !2270)
!2270 = !{!2271, !2272}
!2271 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2238, file: !2158, line: 33, baseType: !2241)
!2272 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2273, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2273 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2238)
!2274 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEE3endEv", scope: !2238, file: !2158, line: 98, type: !2269, scopeLine: 98, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2275 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEE6rbeginEv", scope: !2238, file: !2158, line: 100, type: !2276, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2276 = !DISubroutineType(types: !2277)
!2277 = !{!2278, !2272}
!2278 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !2238, file: !2158, line: 37, baseType: !2279)
!2279 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const llvm::SMFixIt *>", scope: !192, file: !631, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKN4llvm7SMFixItEE")
!2280 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEE4rendEv", scope: !2238, file: !2158, line: 101, type: !2276, scopeLine: 101, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2281 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEE5emptyEv", scope: !2238, file: !2158, line: 104, type: !2282, scopeLine: 104, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2282 = !DISubroutineType(types: !2283)
!2283 = !{!132, !2272}
!2284 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEE4dataEv", scope: !2238, file: !2158, line: 106, type: !2285, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2285 = !DISubroutineType(types: !2286)
!2286 = !{!2241, !2272}
!2287 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEE4sizeEv", scope: !2238, file: !2158, line: 109, type: !2288, scopeLine: 109, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2288 = !DISubroutineType(types: !2289)
!2289 = !{!159, !2272}
!2290 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEE5frontEv", scope: !2238, file: !2158, line: 112, type: !2291, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2291 = !DISubroutineType(types: !2292)
!2292 = !{!2255, !2272}
!2293 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEE4backEv", scope: !2238, file: !2158, line: 118, type: !2291, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2294 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEE6equalsES2_", scope: !2238, file: !2158, line: 124, type: !2295, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2295 = !DISubroutineType(types: !2296)
!2296 = !{!132, !2272, !2238}
!2297 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEE5sliceEj", scope: !2238, file: !2158, line: 134, type: !2298, scopeLine: 134, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2298 = !DISubroutineType(types: !2299)
!2299 = !{!2238, !2272, !6}
!2300 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEE5sliceEjj", scope: !2238, file: !2158, line: 141, type: !2301, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2301 = !DISubroutineType(types: !2302)
!2302 = !{!2238, !2272, !6, !6}
!2303 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEEixEm", scope: !2238, file: !2158, line: 149, type: !2304, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2304 = !DISubroutineType(types: !2305)
!2305 = !{!2255, !2272, !159}
!2306 = !DISubprogram(name: "vec", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEE3vecEv", scope: !2238, file: !2158, line: 157, type: !2307, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2307 = !DISubroutineType(types: !2308)
!2308 = !{!2309, !2272}
!2309 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<llvm::SMFixIt, std::allocator<llvm::SMFixIt> >", scope: !192, file: !1080, line: 339, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt6vectorIN4llvm7SMFixItESaIS1_EE")
!2310 = !DISubprogram(name: "operator vector", linkageName: "_ZNK4llvm8ArrayRefINS_7SMFixItEEcvSt6vectorIS1_SaIS1_EEEv", scope: !2238, file: !2158, line: 164, type: !2307, scopeLine: 164, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2311 = !{!2312}
!2312 = !DITemplateTypeParameter(name: "T", type: !2243)
!2313 = !DISubprogram(name: "PrintMessage", linkageName: "_ZNK4llvm9SourceMgr12PrintMessageENS_5SMLocENS0_8DiagKindERKNS_5TwineENS_8ArrayRefINS_7SMRangeEEENS6_INS_7SMFixItEEEb", scope: !1076, file: !1075, line: 154, type: !2314, scopeLine: 154, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2314 = !DISubroutineType(types: !2315)
!2315 = !{null, !2065, !1110, !1074, !381, !2157, !2238, !132}
!2316 = !DISubprogram(name: "GetMessage", linkageName: "_ZNK4llvm9SourceMgr10GetMessageENS_5SMLocENS0_8DiagKindERKNS_5TwineENS_8ArrayRefINS_7SMRangeEEENS6_INS_7SMFixItEEE", scope: !1076, file: !1075, line: 164, type: !2317, scopeLine: 164, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2317 = !DISubroutineType(types: !2318)
!2318 = !{!2043, !2065, !1110, !1074, !381, !2157, !2238}
!2319 = !DISubprogram(name: "PrintIncludeStack", linkageName: "_ZNK4llvm9SourceMgr17PrintIncludeStackENS_5SMLocERNS_11raw_ostreamE", scope: !1076, file: !1075, line: 174, type: !2320, scopeLine: 174, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2320 = !DISubroutineType(types: !2321)
!2321 = !{null, !2065, !1110, !467}
!2322 = !{!2323, !2324, !2325}
!2323 = !DIEnumerator(name: "DK_Error", value: 0, isUnsigned: true)
!2324 = !DIEnumerator(name: "DK_Warning", value: 1, isUnsigned: true)
!2325 = !DIEnumerator(name: "DK_Note", value: 2, isUnsigned: true)
!2326 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "_Rb_tree_color", scope: !192, file: !2327, line: 99, baseType: !6, size: 32, elements: !2328, identifier: "_ZTSSt14_Rb_tree_color")
!2327 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_tree.h", directory: "")
!2328 = !{!2329, !2330}
!2329 = !DIEnumerator(name: "_S_red", value: 0, isUnsigned: true)
!2330 = !DIEnumerator(name: "_S_black", value: 1, isUnsigned: true)
!2331 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "NodeKind", scope: !2333, file: !2332, line: 110, baseType: !6, size: 32, elements: !2334, identifier: "_ZTSN4llvm4yaml4Node8NodeKindE")
!2332 = !DIFile(filename: "llvm34/include/llvm/Support/YAMLParser.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "7140930bb3bb6b1b8dfb855dd6fc2125")
!2333 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Node", scope: !110, file: !2332, line: 107, size: 576, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm4yaml4NodeE")
!2334 = !{!2335, !2336, !2337, !2338, !2339, !2340}
!2335 = !DIEnumerator(name: "NK_Null", value: 0, isUnsigned: true)
!2336 = !DIEnumerator(name: "NK_Scalar", value: 1, isUnsigned: true)
!2337 = !DIEnumerator(name: "NK_KeyValue", value: 2, isUnsigned: true)
!2338 = !DIEnumerator(name: "NK_Mapping", value: 3, isUnsigned: true)
!2339 = !DIEnumerator(name: "NK_Sequence", value: 4, isUnsigned: true)
!2340 = !DIEnumerator(name: "NK_Alias", value: 5, isUnsigned: true)
!2341 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !2342, file: !575, line: 39, baseType: !6, size: 32, elements: !3284, identifier: "_ZTSN4llvm7AlignOfINS_14StringMapEntryIPNS_4yaml5Input5HNodeEEEEUt_E")
!2342 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignOf<llvm::StringMapEntry<llvm::yaml::Input::HNode *> >", scope: !14, file: !575, line: 38, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !2343, identifier: "_ZTSN4llvm7AlignOfINS_14StringMapEntryIPNS_4yaml5Input5HNodeEEEEE")
!2343 = !{!2344}
!2344 = !DITemplateTypeParameter(name: "T", type: !2345)
!2345 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringMapEntry<llvm::yaml::Input::HNode *>", scope: !14, file: !2346, line: 118, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2347, templateParams: !3282, identifier: "_ZTSN4llvm14StringMapEntryIPNS_4yaml5Input5HNodeEEE")
!2346 = !DIFile(filename: "llvm34/include/llvm/ADT/StringMap.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "25ead265da32dd3e6b5275b9c6f03393")
!2347 = !{!2348, !2361, !3233, !3238, !3241, !3246, !3251, !3254, !3258, !3261, !3264, !3265, !3269, !3272, !3276, !3279}
!2348 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2345, baseType: !2349, flags: DIFlagPublic, extraData: i32 0)
!2349 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringMapEntryBase", scope: !14, file: !2346, line: 43, size: 32, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2350, identifier: "_ZTSN4llvm18StringMapEntryBaseE")
!2350 = !{!2351, !2352, !2356}
!2351 = !DIDerivedType(tag: DW_TAG_member, name: "StrLen", scope: !2349, file: !2346, line: 44, baseType: !6, size: 32)
!2352 = !DISubprogram(name: "StringMapEntryBase", scope: !2349, file: !2346, line: 46, type: !2353, scopeLine: 46, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2353 = !DISubroutineType(types: !2354)
!2354 = !{null, !2355, !6}
!2355 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2349, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2356 = !DISubprogram(name: "getKeyLength", linkageName: "_ZNK4llvm18StringMapEntryBase12getKeyLengthEv", scope: !2349, file: !2346, line: 48, type: !2357, scopeLine: 48, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2357 = !DISubroutineType(types: !2358)
!2358 = !{!6, !2359}
!2359 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2360, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2360 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2349)
!2361 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !2345, file: !2346, line: 121, baseType: !2362, size: 64, offset: 64, flags: DIFlagPublic)
!2362 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2363, size: 64)
!2363 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "HNode", scope: !2364, file: !108, line: 727, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3217, vtableHolder: !2363)
!2364 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Input", scope: !110, file: !108, line: 686, size: 2048, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2365, vtableHolder: !113)
!2365 = !{!2366, !2367, !2368, !2421, !2471, !2515, !2518, !2553, !3145, !3146, !3147, !3151, !3154, !3157, !3158, !3163, !3166, !3167, !3168, !3171, !3174, !3177, !3178, !3181, !3182, !3183, !3184, !3185, !3186, !3187, !3190, !3191, !3194, !3195, !3196, !3199, !3202, !3205, !3209, !3212, !3215, !3216}
!2366 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2364, baseType: !113, flags: DIFlagPublic, extraData: i32 0)
!2367 = !DIDerivedType(tag: DW_TAG_member, name: "SrcMgr", scope: !2364, file: !108, line: 805, baseType: !1076, size: 576, offset: 128)
!2368 = !DIDerivedType(tag: DW_TAG_member, name: "Strm", scope: !2364, file: !108, line: 806, baseType: !2369, size: 64, offset: 704)
!2369 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "OwningPtr<llvm::yaml::Stream>", scope: !14, file: !2370, line: 28, size: 64, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2371, templateParams: !2419, identifier: "_ZTSN4llvm9OwningPtrINS_4yaml6StreamEEE")
!2370 = !DIFile(filename: "llvm34/include/llvm/ADT/OwningPtr.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "aca248455b073d207b4725e6c25cc91c")
!2371 = !{!2372, !2375, !2381, !2385, !2388, !2392, !2395, !2398, !2399, !2402, !2407, !2410, !2411, !2414, !2415, !2416}
!2372 = !DIDerivedType(tag: DW_TAG_member, name: "Ptr", scope: !2369, file: !2370, line: 31, baseType: !2373, size: 64)
!2373 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2374, size: 64)
!2374 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Stream", scope: !110, file: !2332, line: 79, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm4yaml6StreamE")
!2375 = !DISubprogram(name: "OwningPtr", scope: !2369, file: !2370, line: 29, type: !2376, scopeLine: 29, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2376 = !DISubroutineType(types: !2377)
!2377 = !{null, !2378, !2379}
!2378 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2369, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2379 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2380, size: 64)
!2380 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2369)
!2381 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm9OwningPtrINS_4yaml6StreamEEaSERKS3_", scope: !2369, file: !2370, line: 30, type: !2382, scopeLine: 30, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2382 = !DISubroutineType(types: !2383)
!2383 = !{!2384, !2378, !2379}
!2384 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2369, size: 64)
!2385 = !DISubprogram(name: "OwningPtr", scope: !2369, file: !2370, line: 33, type: !2386, scopeLine: 33, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2386 = !DISubroutineType(types: !2387)
!2387 = !{null, !2378, !2373}
!2388 = !DISubprogram(name: "OwningPtr", scope: !2369, file: !2370, line: 36, type: !2389, scopeLine: 36, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2389 = !DISubroutineType(types: !2390)
!2390 = !{null, !2378, !2391}
!2391 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2369, size: 64)
!2392 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm9OwningPtrINS_4yaml6StreamEEaSEOS3_", scope: !2369, file: !2370, line: 38, type: !2393, scopeLine: 38, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2393 = !DISubroutineType(types: !2394)
!2394 = !{!2384, !2378, !2391}
!2395 = !DISubprogram(name: "~OwningPtr", scope: !2369, file: !2370, line: 44, type: !2396, scopeLine: 44, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2396 = !DISubroutineType(types: !2397)
!2397 = !{null, !2378}
!2398 = !DISubprogram(name: "reset", linkageName: "_ZN4llvm9OwningPtrINS_4yaml6StreamEE5resetEPS2_", scope: !2369, file: !2370, line: 51, type: !2386, scopeLine: 51, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2399 = !DISubprogram(name: "take", linkageName: "_ZN4llvm9OwningPtrINS_4yaml6StreamEE4takeEv", scope: !2369, file: !2370, line: 60, type: !2400, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2400 = !DISubroutineType(types: !2401)
!2401 = !{!2373, !2378}
!2402 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm9OwningPtrINS_4yaml6StreamEEdeEv", scope: !2369, file: !2370, line: 66, type: !2403, scopeLine: 66, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2403 = !DISubroutineType(types: !2404)
!2404 = !{!2405, !2406}
!2405 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2374, size: 64)
!2406 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2380, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2407 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm9OwningPtrINS_4yaml6StreamEEptEv", scope: !2369, file: !2370, line: 71, type: !2408, scopeLine: 71, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2408 = !DISubroutineType(types: !2409)
!2409 = !{!2373, !2406}
!2410 = !DISubprogram(name: "get", linkageName: "_ZNK4llvm9OwningPtrINS_4yaml6StreamEE3getEv", scope: !2369, file: !2370, line: 72, type: !2408, scopeLine: 72, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2411 = !DISubprogram(name: "operator bool", linkageName: "_ZNK4llvm9OwningPtrINS_4yaml6StreamEEcvbEv", scope: !2369, file: !2370, line: 73, type: !2412, scopeLine: 73, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2412 = !DISubroutineType(types: !2413)
!2413 = !{!132, !2406}
!2414 = !DISubprogram(name: "operator!", linkageName: "_ZNK4llvm9OwningPtrINS_4yaml6StreamEEntEv", scope: !2369, file: !2370, line: 74, type: !2412, scopeLine: 74, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2415 = !DISubprogram(name: "isValid", linkageName: "_ZNK4llvm9OwningPtrINS_4yaml6StreamEE7isValidEv", scope: !2369, file: !2370, line: 75, type: !2412, scopeLine: 75, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2416 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm9OwningPtrINS_4yaml6StreamEE4swapERS3_", scope: !2369, file: !2370, line: 77, type: !2417, scopeLine: 77, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2417 = !DISubroutineType(types: !2418)
!2418 = !{null, !2378, !2384}
!2419 = !{!2420}
!2420 = !DITemplateTypeParameter(name: "T", type: !2374)
!2421 = !DIDerivedType(tag: DW_TAG_member, name: "TopNode", scope: !2364, file: !108, line: 807, baseType: !2422, size: 64, offset: 768)
!2422 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "OwningPtr<llvm::yaml::Input::HNode>", scope: !14, file: !2370, line: 28, size: 64, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2423, templateParams: !2469, identifier: "_ZTSN4llvm9OwningPtrINS_4yaml5Input5HNodeEEE")
!2423 = !{!2424, !2425, !2431, !2435, !2438, !2442, !2445, !2448, !2449, !2452, !2457, !2460, !2461, !2464, !2465, !2466}
!2424 = !DIDerivedType(tag: DW_TAG_member, name: "Ptr", scope: !2422, file: !2370, line: 31, baseType: !2362, size: 64)
!2425 = !DISubprogram(name: "OwningPtr", scope: !2422, file: !2370, line: 29, type: !2426, scopeLine: 29, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2426 = !DISubroutineType(types: !2427)
!2427 = !{null, !2428, !2429}
!2428 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2422, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2429 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2430, size: 64)
!2430 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2422)
!2431 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm9OwningPtrINS_4yaml5Input5HNodeEEaSERKS4_", scope: !2422, file: !2370, line: 30, type: !2432, scopeLine: 30, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2432 = !DISubroutineType(types: !2433)
!2433 = !{!2434, !2428, !2429}
!2434 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2422, size: 64)
!2435 = !DISubprogram(name: "OwningPtr", scope: !2422, file: !2370, line: 33, type: !2436, scopeLine: 33, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2436 = !DISubroutineType(types: !2437)
!2437 = !{null, !2428, !2362}
!2438 = !DISubprogram(name: "OwningPtr", scope: !2422, file: !2370, line: 36, type: !2439, scopeLine: 36, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2439 = !DISubroutineType(types: !2440)
!2440 = !{null, !2428, !2441}
!2441 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2422, size: 64)
!2442 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm9OwningPtrINS_4yaml5Input5HNodeEEaSEOS4_", scope: !2422, file: !2370, line: 38, type: !2443, scopeLine: 38, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2443 = !DISubroutineType(types: !2444)
!2444 = !{!2434, !2428, !2441}
!2445 = !DISubprogram(name: "~OwningPtr", scope: !2422, file: !2370, line: 44, type: !2446, scopeLine: 44, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2446 = !DISubroutineType(types: !2447)
!2447 = !{null, !2428}
!2448 = !DISubprogram(name: "reset", linkageName: "_ZN4llvm9OwningPtrINS_4yaml5Input5HNodeEE5resetEPS3_", scope: !2422, file: !2370, line: 51, type: !2436, scopeLine: 51, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2449 = !DISubprogram(name: "take", linkageName: "_ZN4llvm9OwningPtrINS_4yaml5Input5HNodeEE4takeEv", scope: !2422, file: !2370, line: 60, type: !2450, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2450 = !DISubroutineType(types: !2451)
!2451 = !{!2362, !2428}
!2452 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm9OwningPtrINS_4yaml5Input5HNodeEEdeEv", scope: !2422, file: !2370, line: 66, type: !2453, scopeLine: 66, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2453 = !DISubroutineType(types: !2454)
!2454 = !{!2455, !2456}
!2455 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2363, size: 64)
!2456 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2430, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2457 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm9OwningPtrINS_4yaml5Input5HNodeEEptEv", scope: !2422, file: !2370, line: 71, type: !2458, scopeLine: 71, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2458 = !DISubroutineType(types: !2459)
!2459 = !{!2362, !2456}
!2460 = !DISubprogram(name: "get", linkageName: "_ZNK4llvm9OwningPtrINS_4yaml5Input5HNodeEE3getEv", scope: !2422, file: !2370, line: 72, type: !2458, scopeLine: 72, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2461 = !DISubprogram(name: "operator bool", linkageName: "_ZNK4llvm9OwningPtrINS_4yaml5Input5HNodeEEcvbEv", scope: !2422, file: !2370, line: 73, type: !2462, scopeLine: 73, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2462 = !DISubroutineType(types: !2463)
!2463 = !{!132, !2456}
!2464 = !DISubprogram(name: "operator!", linkageName: "_ZNK4llvm9OwningPtrINS_4yaml5Input5HNodeEEntEv", scope: !2422, file: !2370, line: 74, type: !2462, scopeLine: 74, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2465 = !DISubprogram(name: "isValid", linkageName: "_ZNK4llvm9OwningPtrINS_4yaml5Input5HNodeEE7isValidEv", scope: !2422, file: !2370, line: 75, type: !2462, scopeLine: 75, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2466 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm9OwningPtrINS_4yaml5Input5HNodeEE4swapERS4_", scope: !2422, file: !2370, line: 77, type: !2467, scopeLine: 77, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2467 = !DISubroutineType(types: !2468)
!2468 = !{null, !2428, !2434}
!2469 = !{!2470}
!2470 = !DITemplateTypeParameter(name: "T", type: !2363)
!2471 = !DIDerivedType(tag: DW_TAG_member, name: "EC", scope: !2364, file: !108, line: 808, baseType: !2472, size: 128, offset: 832)
!2472 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "error_code", scope: !14, file: !12, line: 726, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2473, identifier: "_ZTSN4llvm10error_codeE")
!2473 = !{!2474, !2475, !2479, !2483, !2486, !2490, !2491, !2492, !2497, !2500, !2504, !2507, !2510}
!2474 = !DIDerivedType(tag: DW_TAG_member, name: "_val_", scope: !2472, file: !12, line: 727, baseType: !24, size: 32)
!2475 = !DIDerivedType(tag: DW_TAG_member, name: "_cat_", scope: !2472, file: !12, line: 728, baseType: !2476, size: 64, offset: 64)
!2476 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2477, size: 64)
!2477 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2478)
!2478 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "error_category", scope: !14, file: !12, line: 627, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm14error_categoryE")
!2479 = !DISubprogram(name: "error_code", scope: !2472, file: !12, line: 730, type: !2480, scopeLine: 730, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2480 = !DISubroutineType(types: !2481)
!2481 = !{null, !2482}
!2482 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2472, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2483 = !DISubprogram(name: "success", linkageName: "_ZN4llvm10error_code7successEv", scope: !2472, file: !12, line: 732, type: !2484, scopeLine: 732, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2484 = !DISubroutineType(types: !2485)
!2485 = !{!2472}
!2486 = !DISubprogram(name: "error_code", scope: !2472, file: !12, line: 736, type: !2487, scopeLine: 736, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2487 = !DISubroutineType(types: !2488)
!2488 = !{null, !2482, !24, !2489}
!2489 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2477, size: 64)
!2490 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm10error_code6assignEiRKNS_14error_categoryE", scope: !2472, file: !12, line: 746, type: !2487, scopeLine: 746, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2491 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm10error_code5clearEv", scope: !2472, file: !12, line: 760, type: !2480, scopeLine: 760, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2492 = !DISubprogram(name: "value", linkageName: "_ZNK4llvm10error_code5valueEv", scope: !2472, file: !12, line: 765, type: !2493, scopeLine: 765, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2493 = !DISubroutineType(types: !2494)
!2494 = !{!24, !2495}
!2495 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2496, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2496 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2472)
!2497 = !DISubprogram(name: "category", linkageName: "_ZNK4llvm10error_code8categoryEv", scope: !2472, file: !12, line: 767, type: !2498, scopeLine: 767, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2498 = !DISubroutineType(types: !2499)
!2499 = !{!2489, !2495}
!2500 = !DISubprogram(name: "default_error_condition", linkageName: "_ZNK4llvm10error_code23default_error_conditionEv", scope: !2472, file: !12, line: 769, type: !2501, scopeLine: 769, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2501 = !DISubroutineType(types: !2502)
!2502 = !{!2503, !2495}
!2503 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "error_condition", scope: !14, file: !12, line: 667, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm15error_conditionE")
!2504 = !DISubprogram(name: "message", linkageName: "_ZNK4llvm10error_code7messageB5cxx11Ev", scope: !2472, file: !12, line: 772, type: !2505, scopeLine: 772, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2505 = !DISubroutineType(types: !2506)
!2506 = !{!189, !2495}
!2507 = !DISubprogram(name: "unspecified_bool_true", linkageName: "_ZN4llvm10error_code21unspecified_bool_trueEv", scope: !2472, file: !12, line: 775, type: !2508, scopeLine: 775, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2508 = !DISubroutineType(types: !2509)
!2509 = !{null}
!2510 = !DISubprogram(name: "operator void (*)()", linkageName: "_ZNK4llvm10error_codecvPFvvEEv", scope: !2472, file: !12, line: 777, type: !2511, scopeLine: 777, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2511 = !DISubroutineType(types: !2512)
!2512 = !{!2513, !2495}
!2513 = !DIDerivedType(tag: DW_TAG_typedef, name: "unspecified_bool_type", scope: !2472, file: !12, line: 774, baseType: !2514)
!2514 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2508, size: 64)
!2515 = !DIDerivedType(tag: DW_TAG_member, name: "StringAllocator", scope: !2364, file: !108, line: 809, baseType: !2516, size: 576, offset: 960)
!2516 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "BumpPtrAllocator", scope: !14, file: !2517, line: 90, size: 576, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm16BumpPtrAllocatorE")
!2517 = !DIFile(filename: "llvm34/include/llvm/Support/Allocator.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e9d7c083de36bffba1b1ac9811c014c8")
!2518 = !DIDerivedType(tag: DW_TAG_member, name: "DocIterator", scope: !2364, file: !108, line: 810, baseType: !2519, size: 64, offset: 1536)
!2519 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "document_iterator", scope: !110, file: !2332, line: 532, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2520, identifier: "_ZTSN4llvm4yaml17document_iteratorE")
!2520 = !{!2521, !2524, !2528, !2532, !2537, !2538, !2541, !2546, !2549}
!2521 = !DIDerivedType(tag: DW_TAG_member, name: "Doc", scope: !2519, file: !2332, line: 571, baseType: !2522, size: 64)
!2522 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2523, size: 64)
!2523 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "OwningPtr<llvm::yaml::Document>", scope: !14, file: !2370, line: 28, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm9OwningPtrINS_4yaml8DocumentEEE")
!2524 = !DISubprogram(name: "document_iterator", scope: !2519, file: !2332, line: 534, type: !2525, scopeLine: 534, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2525 = !DISubroutineType(types: !2526)
!2526 = !{null, !2527}
!2527 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2519, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2528 = !DISubprogram(name: "document_iterator", scope: !2519, file: !2332, line: 535, type: !2529, scopeLine: 535, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2529 = !DISubroutineType(types: !2530)
!2530 = !{null, !2527, !2531}
!2531 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2523, size: 64)
!2532 = !DISubprogram(name: "operator==", linkageName: "_ZN4llvm4yaml17document_iteratoreqERKS1_", scope: !2519, file: !2332, line: 537, type: !2533, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2533 = !DISubroutineType(types: !2534)
!2534 = !{!132, !2527, !2535}
!2535 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2536, size: 64)
!2536 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2519)
!2537 = !DISubprogram(name: "operator!=", linkageName: "_ZN4llvm4yaml17document_iteratorneERKS1_", scope: !2519, file: !2332, line: 543, type: !2533, scopeLine: 543, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2538 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm4yaml17document_iteratorppEv", scope: !2519, file: !2332, line: 547, type: !2539, scopeLine: 547, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2539 = !DISubroutineType(types: !2540)
!2540 = !{!2519, !2527}
!2541 = !DISubprogram(name: "operator*", linkageName: "_ZN4llvm4yaml17document_iteratordeEv", scope: !2519, file: !2332, line: 558, type: !2542, scopeLine: 558, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2542 = !DISubroutineType(types: !2543)
!2543 = !{!2544, !2527}
!2544 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2545, size: 64)
!2545 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Document", scope: !110, file: !2332, line: 473, size: 1088, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm4yaml8DocumentE")
!2546 = !DISubprogram(name: "operator->", linkageName: "_ZN4llvm4yaml17document_iteratorptEv", scope: !2519, file: !2332, line: 562, type: !2547, scopeLine: 562, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2547 = !DISubroutineType(types: !2548)
!2548 = !{!2531, !2527}
!2549 = !DISubprogram(name: "isAtEnd", linkageName: "_ZNK4llvm4yaml17document_iterator7isAtEndEv", scope: !2519, file: !2332, line: 567, type: !2550, scopeLine: 567, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2550 = !DISubroutineType(types: !2551)
!2551 = !{!132, !2552}
!2552 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2536, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2553 = !DIDerivedType(tag: DW_TAG_member, name: "BitValuesUsed", scope: !2364, file: !108, line: 811, baseType: !2554, size: 320, offset: 1600)
!2554 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<bool, std::allocator<bool> >", scope: !192, file: !2555, line: 588, size: 320, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2556, templateParams: !3144, identifier: "_ZTSSt6vectorIbSaIbEE")
!2555 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_bvector.h", directory: "", checksumkind: CSK_MD5, checksum: "543595f245ff5dae7fc0594cdc71787c")
!2556 = !{!2557, !2893, !2899, !2903, !2908, !2912, !2916, !2920, !2924, !2927, !2930, !2959, !2960, !2964, !2967, !2970, !2973, !2976, !2980, !3028, !3029, !3030, !3035, !3040, !3041, !3042, !3043, !3044, !3045, !3046, !3049, !3050, !3051, !3054, !3058, !3062, !3065, !3066, !3067, !3070, !3074, !3078, !3079, !3080, !3081, !3084, !3087, !3090, !3094, !3097, !3100, !3101, !3104, !3107, !3110, !3111, !3112, !3113, !3116, !3117, !3118, !3119, !3122, !3125, !3128, !3131, !3135, !3138, !3141}
!2557 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2554, baseType: !2558, flags: DIFlagProtected, extraData: i32 0)
!2558 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bvector_base<std::allocator<bool> >", scope: !192, file: !2555, line: 426, size: 320, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2559, templateParams: !2595, identifier: "_ZTSSt13_Bvector_baseISaIbEE")
!2559 = !{!2560, !2858, !2863, !2868, !2872, !2875, !2880, !2884, !2885, !2888, !2889, !2890}
!2560 = !DIDerivedType(tag: DW_TAG_member, name: "_M_impl", scope: !2558, file: !2555, line: 526, baseType: !2561, size: 320, flags: DIFlagProtected)
!2561 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bvector_impl", scope: !2558, file: !2555, line: 468, size: 320, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2562, identifier: "_ZTSNSt13_Bvector_baseISaIbEE13_Bvector_implE")
!2562 = !{!2563, !2666, !2840, !2844, !2849, !2853}
!2563 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2561, baseType: !2564, extraData: i32 0)
!2564 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Bit_alloc_type", scope: !2558, file: !2555, line: 429, baseType: !2565)
!2565 = !DIDerivedType(tag: DW_TAG_typedef, name: "other", scope: !2566, file: !1091, line: 117, baseType: !2615)
!2566 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "rebind<unsigned long>", scope: !2567, file: !1091, line: 116, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !2613, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIbEbE6rebindImEE")
!2567 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__alloc_traits<std::allocator<bool>, bool>", scope: !5, file: !1091, line: 50, size: 8, flags: DIFlagTypePassByValue, elements: !2568, templateParams: !2611, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIbEbEE")
!2568 = !{!2569, !2597, !2602, !2606, !2607, !2608, !2609, !2610}
!2569 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2567, baseType: !2570, extraData: i32 0)
!2570 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "allocator_traits<std::allocator<bool> >", scope: !192, file: !1097, line: 384, size: 8, flags: DIFlagTypePassByValue, elements: !2571, templateParams: !2595, identifier: "_ZTSSt16allocator_traitsISaIbEE")
!2571 = !{!2572, !2580, !2583, !2586, !2592}
!2572 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIbEE8allocateERS0_m", scope: !2570, file: !1097, line: 435, type: !2573, scopeLine: 435, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2573 = !DISubroutineType(types: !2574)
!2574 = !{!2575, !2577, !1174}
!2575 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2570, file: !1097, line: 392, baseType: !2576)
!2576 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !132, size: 64)
!2577 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2578, size: 64)
!2578 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !2570, file: !1097, line: 387, baseType: !2579)
!2579 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "allocator<bool>", scope: !192, file: !1115, line: 108, size: 8, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSaIbE")
!2580 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIbEE8allocateERS0_mPKv", scope: !2570, file: !1097, line: 449, type: !2581, scopeLine: 449, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2581 = !DISubroutineType(types: !2582)
!2582 = !{!2575, !2577, !1174, !1178}
!2583 = !DISubprogram(name: "deallocate", linkageName: "_ZNSt16allocator_traitsISaIbEE10deallocateERS0_Pbm", scope: !2570, file: !1097, line: 461, type: !2584, scopeLine: 461, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2584 = !DISubroutineType(types: !2585)
!2585 = !{null, !2577, !2575, !1174}
!2586 = !DISubprogram(name: "max_size", linkageName: "_ZNSt16allocator_traitsISaIbEE8max_sizeERKS0_", scope: !2570, file: !1097, line: 495, type: !2587, scopeLine: 495, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2587 = !DISubroutineType(types: !2588)
!2588 = !{!2589, !2590}
!2589 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2570, file: !1097, line: 407, baseType: !1152)
!2590 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2591, size: 64)
!2591 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2578)
!2592 = !DISubprogram(name: "select_on_container_copy_construction", linkageName: "_ZNSt16allocator_traitsISaIbEE37select_on_container_copy_constructionERKS0_", scope: !2570, file: !1097, line: 504, type: !2593, scopeLine: 504, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2593 = !DISubroutineType(types: !2594)
!2594 = !{!2578, !2590}
!2595 = !{!2596}
!2596 = !DITemplateTypeParameter(name: "_Alloc", type: !2579)
!2597 = !DISubprogram(name: "_S_select_on_copy", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIbEbE17_S_select_on_copyERKS1_", scope: !2567, file: !1091, line: 94, type: !2598, scopeLine: 94, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2598 = !DISubroutineType(types: !2599)
!2599 = !{!2579, !2600}
!2600 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2601, size: 64)
!2601 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2579)
!2602 = !DISubprogram(name: "_S_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIbEbE10_S_on_swapERS1_S3_", scope: !2567, file: !1091, line: 97, type: !2603, scopeLine: 97, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2603 = !DISubroutineType(types: !2604)
!2604 = !{null, !2605, !2605}
!2605 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2579, size: 64)
!2606 = !DISubprogram(name: "_S_propagate_on_copy_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIbEbE27_S_propagate_on_copy_assignEv", scope: !2567, file: !1091, line: 100, type: !1201, scopeLine: 100, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2607 = !DISubprogram(name: "_S_propagate_on_move_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIbEbE27_S_propagate_on_move_assignEv", scope: !2567, file: !1091, line: 103, type: !1201, scopeLine: 103, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2608 = !DISubprogram(name: "_S_propagate_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIbEbE20_S_propagate_on_swapEv", scope: !2567, file: !1091, line: 106, type: !1201, scopeLine: 106, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2609 = !DISubprogram(name: "_S_always_equal", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIbEbE15_S_always_equalEv", scope: !2567, file: !1091, line: 109, type: !1201, scopeLine: 109, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2610 = !DISubprogram(name: "_S_nothrow_move", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIbEbE15_S_nothrow_moveEv", scope: !2567, file: !1091, line: 112, type: !1201, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2611 = !{!2596, !2612}
!2612 = !DITemplateTypeParameter(type: !132)
!2613 = !{!2614}
!2614 = !DITemplateTypeParameter(name: "_Tp", type: !161)
!2615 = !DIDerivedType(tag: DW_TAG_typedef, name: "rebind_alloc<unsigned long>", scope: !2570, file: !1097, line: 422, baseType: !2616)
!2616 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "allocator<unsigned long>", scope: !192, file: !1115, line: 108, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2617, templateParams: !2664, identifier: "_ZTSSaImE")
!2617 = !{!2618, !2654, !2658, !2663}
!2618 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2616, baseType: !2619, flags: DIFlagPublic, extraData: i32 0)
!2619 = !DIDerivedType(tag: DW_TAG_typedef, name: "__allocator_base<unsigned long>", scope: !192, file: !1119, line: 48, baseType: !2620)
!2620 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "new_allocator<unsigned long>", scope: !5, file: !1121, line: 58, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2621, templateParams: !2613, identifier: "_ZTSN9__gnu_cxx13new_allocatorImEE")
!2621 = !{!2622, !2626, !2631, !2632, !2640, !2645, !2648, !2651}
!2622 = !DISubprogram(name: "new_allocator", scope: !2620, file: !1121, line: 79, type: !2623, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2623 = !DISubroutineType(types: !2624)
!2624 = !{null, !2625}
!2625 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2620, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2626 = !DISubprogram(name: "new_allocator", scope: !2620, file: !1121, line: 81, type: !2627, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2627 = !DISubroutineType(types: !2628)
!2628 = !{null, !2625, !2629}
!2629 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2630, size: 64)
!2630 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2620)
!2631 = !DISubprogram(name: "~new_allocator", scope: !2620, file: !1121, line: 86, type: !2623, scopeLine: 86, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2632 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorImE7addressERm", scope: !2620, file: !1121, line: 89, type: !2633, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2633 = !DISubroutineType(types: !2634)
!2634 = !{!2635, !2637, !2638}
!2635 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2620, file: !1121, line: 63, baseType: !2636)
!2636 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !161, size: 64)
!2637 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2630, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2638 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2620, file: !1121, line: 65, baseType: !2639)
!2639 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !161, size: 64)
!2640 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorImE7addressERKm", scope: !2620, file: !1121, line: 93, type: !2641, scopeLine: 93, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2641 = !DISubroutineType(types: !2642)
!2642 = !{!2643, !2637, !2644}
!2643 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !2620, file: !1121, line: 64, baseType: !400)
!2644 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !2620, file: !1121, line: 66, baseType: !503)
!2645 = !DISubprogram(name: "allocate", linkageName: "_ZN9__gnu_cxx13new_allocatorImE8allocateEmPKv", scope: !2620, file: !1121, line: 99, type: !2646, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2646 = !DISubroutineType(types: !2647)
!2647 = !{!2635, !2625, !1151, !1154}
!2648 = !DISubprogram(name: "deallocate", linkageName: "_ZN9__gnu_cxx13new_allocatorImE10deallocateEPmm", scope: !2620, file: !1121, line: 116, type: !2649, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2649 = !DISubroutineType(types: !2650)
!2650 = !{null, !2625, !2635, !1151}
!2651 = !DISubprogram(name: "max_size", linkageName: "_ZNK9__gnu_cxx13new_allocatorImE8max_sizeEv", scope: !2620, file: !1121, line: 129, type: !2652, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2652 = !DISubroutineType(types: !2653)
!2653 = !{!1151, !2637}
!2654 = !DISubprogram(name: "allocator", scope: !2616, file: !1115, line: 131, type: !2655, scopeLine: 131, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2655 = !DISubroutineType(types: !2656)
!2656 = !{null, !2657}
!2657 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2616, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2658 = !DISubprogram(name: "allocator", scope: !2616, file: !1115, line: 133, type: !2659, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2659 = !DISubroutineType(types: !2660)
!2660 = !{null, !2657, !2661}
!2661 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2662, size: 64)
!2662 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2616)
!2663 = !DISubprogram(name: "~allocator", scope: !2616, file: !1115, line: 139, type: !2655, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2664 = !{!2665}
!2665 = !DITemplateTypeParameter(type: !161)
!2666 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2561, baseType: !2667, extraData: i32 0)
!2667 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bvector_impl_data", scope: !2558, file: !2555, line: 434, size: 320, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2668, identifier: "_ZTSNSt13_Bvector_baseISaIbEE18_Bvector_impl_dataE")
!2668 = !{!2669, !2785, !2786, !2830, !2834, !2838, !2839}
!2669 = !DIDerivedType(tag: DW_TAG_member, name: "_M_start", scope: !2667, file: !2555, line: 436, baseType: !2670, size: 128)
!2670 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bit_iterator", scope: !192, file: !2555, line: 216, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2671, identifier: "_ZTSSt13_Bit_iterator")
!2671 = !{!2672, !2718, !2722, !2725, !2731, !2764, !2768, !2771, !2772, !2773, !2777, !2778, !2781, !2782}
!2672 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2670, baseType: !2673, extraData: i32 0)
!2673 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bit_iterator_base", scope: !192, file: !2555, line: 138, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2674, identifier: "_ZTSSt18_Bit_iterator_base")
!2674 = !{!2675, !2692, !2695, !2696, !2700, !2703, !2704, !2707, !2713, !2714, !2715, !2716, !2717}
!2675 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2673, baseType: !2676, extraData: i32 0)
!2676 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::random_access_iterator_tag, bool, long, bool *, bool &>", scope: !192, file: !1357, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !2677, identifier: "_ZTSSt8iteratorISt26random_access_iterator_tagblPbRbE")
!2677 = !{!2678, !1540, !2689, !2690, !2691}
!2678 = !DITemplateTypeParameter(name: "_Category", type: !2679)
!2679 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "random_access_iterator_tag", scope: !192, file: !1357, line: 103, size: 8, flags: DIFlagTypePassByValue, elements: !2680, identifier: "_ZTSSt26random_access_iterator_tag")
!2680 = !{!2681}
!2681 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2679, baseType: !2682, extraData: i32 0)
!2682 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "bidirectional_iterator_tag", scope: !192, file: !1357, line: 99, size: 8, flags: DIFlagTypePassByValue, elements: !2683, identifier: "_ZTSSt26bidirectional_iterator_tag")
!2683 = !{!2684}
!2684 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2682, baseType: !2685, extraData: i32 0)
!2685 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "forward_iterator_tag", scope: !192, file: !1357, line: 95, size: 8, flags: DIFlagTypePassByValue, elements: !2686, identifier: "_ZTSSt20forward_iterator_tag")
!2686 = !{!2687}
!2687 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2685, baseType: !2688, extraData: i32 0)
!2688 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "input_iterator_tag", scope: !192, file: !1357, line: 89, size: 8, flags: DIFlagTypePassByValue, elements: !320, identifier: "_ZTSSt18input_iterator_tag")
!2689 = !DITemplateTypeParameter(name: "_Distance", type: !405)
!2690 = !DITemplateTypeParameter(name: "_Pointer", type: !2576)
!2691 = !DITemplateTypeParameter(name: "_Reference", type: !362)
!2692 = !DIDerivedType(tag: DW_TAG_member, name: "_M_p", scope: !2673, file: !2555, line: 141, baseType: !2693, size: 64)
!2693 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2694, size: 64)
!2694 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Bit_type", scope: !192, file: !2555, line: 69, baseType: !161)
!2695 = !DIDerivedType(tag: DW_TAG_member, name: "_M_offset", scope: !2673, file: !2555, line: 142, baseType: !6, size: 32, offset: 64)
!2696 = !DISubprogram(name: "_Bit_iterator_base", scope: !2673, file: !2555, line: 144, type: !2697, scopeLine: 144, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2697 = !DISubroutineType(types: !2698)
!2698 = !{null, !2699, !2693, !6}
!2699 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2673, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2700 = !DISubprogram(name: "_M_bump_up", linkageName: "_ZNSt18_Bit_iterator_base10_M_bump_upEv", scope: !2673, file: !2555, line: 148, type: !2701, scopeLine: 148, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2701 = !DISubroutineType(types: !2702)
!2702 = !{null, !2699}
!2703 = !DISubprogram(name: "_M_bump_down", linkageName: "_ZNSt18_Bit_iterator_base12_M_bump_downEv", scope: !2673, file: !2555, line: 158, type: !2701, scopeLine: 158, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2704 = !DISubprogram(name: "_M_incr", linkageName: "_ZNSt18_Bit_iterator_base7_M_incrEl", scope: !2673, file: !2555, line: 168, type: !2705, scopeLine: 168, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2705 = !DISubroutineType(types: !2706)
!2706 = !{null, !2699, !1382}
!2707 = !DISubprogram(name: "operator==", linkageName: "_ZNKSt18_Bit_iterator_baseeqERKS_", scope: !2673, file: !2555, line: 182, type: !2708, scopeLine: 182, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2708 = !DISubroutineType(types: !2709)
!2709 = !{!132, !2710, !2712}
!2710 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2711, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2711 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2673)
!2712 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2711, size: 64)
!2713 = !DISubprogram(name: "operator<", linkageName: "_ZNKSt18_Bit_iterator_baseltERKS_", scope: !2673, file: !2555, line: 186, type: !2708, scopeLine: 186, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2714 = !DISubprogram(name: "operator!=", linkageName: "_ZNKSt18_Bit_iterator_baseneERKS_", scope: !2673, file: !2555, line: 193, type: !2708, scopeLine: 193, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2715 = !DISubprogram(name: "operator>", linkageName: "_ZNKSt18_Bit_iterator_basegtERKS_", scope: !2673, file: !2555, line: 197, type: !2708, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2716 = !DISubprogram(name: "operator<=", linkageName: "_ZNKSt18_Bit_iterator_baseleERKS_", scope: !2673, file: !2555, line: 201, type: !2708, scopeLine: 201, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2717 = !DISubprogram(name: "operator>=", linkageName: "_ZNKSt18_Bit_iterator_basegeERKS_", scope: !2673, file: !2555, line: 205, type: !2708, scopeLine: 205, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2718 = !DISubprogram(name: "_Bit_iterator", scope: !2670, file: !2555, line: 222, type: !2719, scopeLine: 222, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2719 = !DISubroutineType(types: !2720)
!2720 = !{null, !2721}
!2721 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2670, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2722 = !DISubprogram(name: "_Bit_iterator", scope: !2670, file: !2555, line: 224, type: !2723, scopeLine: 224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2723 = !DISubroutineType(types: !2724)
!2724 = !{null, !2721, !2693, !6}
!2725 = !DISubprogram(name: "_M_const_cast", linkageName: "_ZNKSt13_Bit_iterator13_M_const_castEv", scope: !2670, file: !2555, line: 228, type: !2726, scopeLine: 228, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2726 = !DISubroutineType(types: !2727)
!2727 = !{!2728, !2729}
!2728 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2670, file: !2555, line: 220, baseType: !2670)
!2729 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2730, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2730 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2670)
!2731 = !DISubprogram(name: "operator*", linkageName: "_ZNKSt13_Bit_iteratordeEv", scope: !2670, file: !2555, line: 232, type: !2732, scopeLine: 232, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2732 = !DISubroutineType(types: !2733)
!2733 = !{!2734, !2729}
!2734 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2670, file: !2555, line: 218, baseType: !2735)
!2735 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bit_reference", scope: !192, file: !2555, line: 72, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2736, identifier: "_ZTSSt14_Bit_reference")
!2736 = !{!2737, !2738, !2739, !2743, !2746, !2751, !2755, !2759, !2762, !2763}
!2737 = !DIDerivedType(tag: DW_TAG_member, name: "_M_p", scope: !2735, file: !2555, line: 74, baseType: !2693, size: 64)
!2738 = !DIDerivedType(tag: DW_TAG_member, name: "_M_mask", scope: !2735, file: !2555, line: 75, baseType: !2694, size: 64, offset: 64)
!2739 = !DISubprogram(name: "_Bit_reference", scope: !2735, file: !2555, line: 77, type: !2740, scopeLine: 77, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2740 = !DISubroutineType(types: !2741)
!2741 = !{null, !2742, !2693, !2694}
!2742 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2735, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2743 = !DISubprogram(name: "_Bit_reference", scope: !2735, file: !2555, line: 80, type: !2744, scopeLine: 80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2744 = !DISubroutineType(types: !2745)
!2745 = !{null, !2742}
!2746 = !DISubprogram(name: "operator bool", linkageName: "_ZNKSt14_Bit_referencecvbEv", scope: !2735, file: !2555, line: 82, type: !2747, scopeLine: 82, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2747 = !DISubroutineType(types: !2748)
!2748 = !{!132, !2749}
!2749 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2750, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2750 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2735)
!2751 = !DISubprogram(name: "operator=", linkageName: "_ZNSt14_Bit_referenceaSEb", scope: !2735, file: !2555, line: 86, type: !2752, scopeLine: 86, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2752 = !DISubroutineType(types: !2753)
!2753 = !{!2754, !2742, !132}
!2754 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2735, size: 64)
!2755 = !DISubprogram(name: "operator=", linkageName: "_ZNSt14_Bit_referenceaSERKS_", scope: !2735, file: !2555, line: 96, type: !2756, scopeLine: 96, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2756 = !DISubroutineType(types: !2757)
!2757 = !{!2754, !2742, !2758}
!2758 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2750, size: 64)
!2759 = !DISubprogram(name: "operator==", linkageName: "_ZNKSt14_Bit_referenceeqERKS_", scope: !2735, file: !2555, line: 100, type: !2760, scopeLine: 100, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2760 = !DISubroutineType(types: !2761)
!2761 = !{!132, !2749, !2758}
!2762 = !DISubprogram(name: "operator<", linkageName: "_ZNKSt14_Bit_referenceltERKS_", scope: !2735, file: !2555, line: 104, type: !2760, scopeLine: 104, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2763 = !DISubprogram(name: "flip", linkageName: "_ZNSt14_Bit_reference4flipEv", scope: !2735, file: !2555, line: 108, type: !2744, scopeLine: 108, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2764 = !DISubprogram(name: "operator++", linkageName: "_ZNSt13_Bit_iteratorppEv", scope: !2670, file: !2555, line: 236, type: !2765, scopeLine: 236, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2765 = !DISubroutineType(types: !2766)
!2766 = !{!2767, !2721}
!2767 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2728, size: 64)
!2768 = !DISubprogram(name: "operator++", linkageName: "_ZNSt13_Bit_iteratorppEi", scope: !2670, file: !2555, line: 243, type: !2769, scopeLine: 243, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2769 = !DISubroutineType(types: !2770)
!2770 = !{!2728, !2721, !24}
!2771 = !DISubprogram(name: "operator--", linkageName: "_ZNSt13_Bit_iteratormmEv", scope: !2670, file: !2555, line: 251, type: !2765, scopeLine: 251, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2772 = !DISubprogram(name: "operator--", linkageName: "_ZNSt13_Bit_iteratormmEi", scope: !2670, file: !2555, line: 258, type: !2769, scopeLine: 258, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2773 = !DISubprogram(name: "operator+=", linkageName: "_ZNSt13_Bit_iteratorpLEl", scope: !2670, file: !2555, line: 266, type: !2774, scopeLine: 266, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2774 = !DISubroutineType(types: !2775)
!2775 = !{!2767, !2721, !2776}
!2776 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !2676, file: !1357, line: 125, baseType: !405)
!2777 = !DISubprogram(name: "operator-=", linkageName: "_ZNSt13_Bit_iteratormIEl", scope: !2670, file: !2555, line: 273, type: !2774, scopeLine: 273, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2778 = !DISubprogram(name: "operator+", linkageName: "_ZNKSt13_Bit_iteratorplEl", scope: !2670, file: !2555, line: 280, type: !2779, scopeLine: 280, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2779 = !DISubroutineType(types: !2780)
!2780 = !{!2728, !2729, !2776}
!2781 = !DISubprogram(name: "operator-", linkageName: "_ZNKSt13_Bit_iteratormiEl", scope: !2670, file: !2555, line: 287, type: !2779, scopeLine: 287, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2782 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt13_Bit_iteratorixEl", scope: !2670, file: !2555, line: 294, type: !2783, scopeLine: 294, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2783 = !DISubroutineType(types: !2784)
!2784 = !{!2734, !2729, !2776}
!2785 = !DIDerivedType(tag: DW_TAG_member, name: "_M_finish", scope: !2667, file: !2555, line: 437, baseType: !2670, size: 128, offset: 128)
!2786 = !DIDerivedType(tag: DW_TAG_member, name: "_M_end_of_storage", scope: !2667, file: !2555, line: 438, baseType: !2787, size: 64, offset: 256)
!2787 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Bit_pointer", scope: !2558, file: !2555, line: 432, baseType: !2788)
!2788 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2789, file: !1091, line: 59, baseType: !2797)
!2789 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__alloc_traits<std::allocator<unsigned long>, unsigned long>", scope: !5, file: !1091, line: 50, size: 8, flags: DIFlagTypePassByValue, elements: !2790, templateParams: !2829, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaImEmEE")
!2790 = !{!2791, !2817, !2820, !2824, !2825, !2826, !2827, !2828}
!2791 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2789, baseType: !2792, extraData: i32 0)
!2792 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "allocator_traits<std::allocator<unsigned long> >", scope: !192, file: !1097, line: 384, size: 8, flags: DIFlagTypePassByValue, elements: !2793, templateParams: !2815, identifier: "_ZTSSt16allocator_traitsISaImEE")
!2793 = !{!2794, !2800, !2803, !2806, !2812}
!2794 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaImEE8allocateERS0_m", scope: !2792, file: !1097, line: 435, type: !2795, scopeLine: 435, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2795 = !DISubroutineType(types: !2796)
!2796 = !{!2797, !2798, !1174}
!2797 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2792, file: !1097, line: 392, baseType: !2636)
!2798 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2799, size: 64)
!2799 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !2792, file: !1097, line: 387, baseType: !2616)
!2800 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaImEE8allocateERS0_mPKv", scope: !2792, file: !1097, line: 449, type: !2801, scopeLine: 449, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2801 = !DISubroutineType(types: !2802)
!2802 = !{!2797, !2798, !1174, !1178}
!2803 = !DISubprogram(name: "deallocate", linkageName: "_ZNSt16allocator_traitsISaImEE10deallocateERS0_Pmm", scope: !2792, file: !1097, line: 461, type: !2804, scopeLine: 461, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2804 = !DISubroutineType(types: !2805)
!2805 = !{null, !2798, !2797, !1174}
!2806 = !DISubprogram(name: "max_size", linkageName: "_ZNSt16allocator_traitsISaImEE8max_sizeERKS0_", scope: !2792, file: !1097, line: 495, type: !2807, scopeLine: 495, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2807 = !DISubroutineType(types: !2808)
!2808 = !{!2809, !2810}
!2809 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2792, file: !1097, line: 407, baseType: !1152)
!2810 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2811, size: 64)
!2811 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2799)
!2812 = !DISubprogram(name: "select_on_container_copy_construction", linkageName: "_ZNSt16allocator_traitsISaImEE37select_on_container_copy_constructionERKS0_", scope: !2792, file: !1097, line: 504, type: !2813, scopeLine: 504, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2813 = !DISubroutineType(types: !2814)
!2814 = !{!2799, !2810}
!2815 = !{!2816}
!2816 = !DITemplateTypeParameter(name: "_Alloc", type: !2616)
!2817 = !DISubprogram(name: "_S_select_on_copy", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaImEmE17_S_select_on_copyERKS1_", scope: !2789, file: !1091, line: 94, type: !2818, scopeLine: 94, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2818 = !DISubroutineType(types: !2819)
!2819 = !{!2616, !2661}
!2820 = !DISubprogram(name: "_S_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaImEmE10_S_on_swapERS1_S3_", scope: !2789, file: !1091, line: 97, type: !2821, scopeLine: 97, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2821 = !DISubroutineType(types: !2822)
!2822 = !{null, !2823, !2823}
!2823 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2616, size: 64)
!2824 = !DISubprogram(name: "_S_propagate_on_copy_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaImEmE27_S_propagate_on_copy_assignEv", scope: !2789, file: !1091, line: 100, type: !1201, scopeLine: 100, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2825 = !DISubprogram(name: "_S_propagate_on_move_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaImEmE27_S_propagate_on_move_assignEv", scope: !2789, file: !1091, line: 103, type: !1201, scopeLine: 103, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2826 = !DISubprogram(name: "_S_propagate_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaImEmE20_S_propagate_on_swapEv", scope: !2789, file: !1091, line: 106, type: !1201, scopeLine: 106, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2827 = !DISubprogram(name: "_S_always_equal", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaImEmE15_S_always_equalEv", scope: !2789, file: !1091, line: 109, type: !1201, scopeLine: 109, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2828 = !DISubprogram(name: "_S_nothrow_move", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaImEmE15_S_nothrow_moveEv", scope: !2789, file: !1091, line: 112, type: !1201, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2829 = !{!2816, !2665}
!2830 = !DISubprogram(name: "_Bvector_impl_data", scope: !2667, file: !2555, line: 440, type: !2831, scopeLine: 440, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2831 = !DISubroutineType(types: !2832)
!2832 = !{null, !2833}
!2833 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2667, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2834 = !DISubprogram(name: "_Bvector_impl_data", scope: !2667, file: !2555, line: 445, type: !2835, scopeLine: 445, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2835 = !DISubroutineType(types: !2836)
!2836 = !{null, !2833, !2837}
!2837 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2667, size: 64)
!2838 = !DISubprogram(name: "_M_move_data", linkageName: "_ZNSt13_Bvector_baseISaIbEE18_Bvector_impl_data12_M_move_dataEOS2_", scope: !2667, file: !2555, line: 451, type: !2835, scopeLine: 451, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2839 = !DISubprogram(name: "_M_reset", linkageName: "_ZNSt13_Bvector_baseISaIbEE18_Bvector_impl_data8_M_resetEv", scope: !2667, file: !2555, line: 461, type: !2831, scopeLine: 461, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2840 = !DISubprogram(name: "_Bvector_impl", scope: !2561, file: !2555, line: 472, type: !2841, scopeLine: 472, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2841 = !DISubroutineType(types: !2842)
!2842 = !{null, !2843}
!2843 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2561, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2844 = !DISubprogram(name: "_Bvector_impl", scope: !2561, file: !2555, line: 477, type: !2845, scopeLine: 477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2845 = !DISubroutineType(types: !2846)
!2846 = !{null, !2843, !2847}
!2847 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2848, size: 64)
!2848 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2564)
!2849 = !DISubprogram(name: "_Bvector_impl", scope: !2561, file: !2555, line: 482, type: !2850, scopeLine: 482, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2850 = !DISubroutineType(types: !2851)
!2851 = !{null, !2843, !2852}
!2852 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2561, size: 64)
!2853 = !DISubprogram(name: "_M_end_addr", linkageName: "_ZNKSt13_Bvector_baseISaIbEE13_Bvector_impl11_M_end_addrEv", scope: !2561, file: !2555, line: 486, type: !2854, scopeLine: 486, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2854 = !DISubroutineType(types: !2855)
!2855 = !{!2693, !2856}
!2856 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2857, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2857 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2561)
!2858 = !DISubprogram(name: "_M_get_Bit_allocator", linkageName: "_ZNSt13_Bvector_baseISaIbEE20_M_get_Bit_allocatorEv", scope: !2558, file: !2555, line: 498, type: !2859, scopeLine: 498, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2859 = !DISubroutineType(types: !2860)
!2860 = !{!2861, !2862}
!2861 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2564, size: 64)
!2862 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2558, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2863 = !DISubprogram(name: "_M_get_Bit_allocator", linkageName: "_ZNKSt13_Bvector_baseISaIbEE20_M_get_Bit_allocatorEv", scope: !2558, file: !2555, line: 502, type: !2864, scopeLine: 502, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2864 = !DISubroutineType(types: !2865)
!2865 = !{!2847, !2866}
!2866 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2867, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2867 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2558)
!2868 = !DISubprogram(name: "get_allocator", linkageName: "_ZNKSt13_Bvector_baseISaIbEE13get_allocatorEv", scope: !2558, file: !2555, line: 506, type: !2869, scopeLine: 506, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2869 = !DISubroutineType(types: !2870)
!2870 = !{!2871, !2866}
!2871 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !2558, file: !2555, line: 495, baseType: !2579)
!2872 = !DISubprogram(name: "_Bvector_base", scope: !2558, file: !2555, line: 510, type: !2873, scopeLine: 510, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2873 = !DISubroutineType(types: !2874)
!2874 = !{null, !2862}
!2875 = !DISubprogram(name: "_Bvector_base", scope: !2558, file: !2555, line: 515, type: !2876, scopeLine: 515, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2876 = !DISubroutineType(types: !2877)
!2877 = !{null, !2862, !2878}
!2878 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2879, size: 64)
!2879 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2871)
!2880 = !DISubprogram(name: "_Bvector_base", scope: !2558, file: !2555, line: 519, type: !2881, scopeLine: 519, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2881 = !DISubroutineType(types: !2882)
!2882 = !{null, !2862, !2883}
!2883 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2558, size: 64)
!2884 = !DISubprogram(name: "~_Bvector_base", scope: !2558, file: !2555, line: 522, type: !2873, scopeLine: 522, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2885 = !DISubprogram(name: "_M_allocate", linkageName: "_ZNSt13_Bvector_baseISaIbEE11_M_allocateEm", scope: !2558, file: !2555, line: 529, type: !2886, scopeLine: 529, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2886 = !DISubroutineType(types: !2887)
!2887 = !{!2787, !2862, !1152}
!2888 = !DISubprogram(name: "_M_deallocate", linkageName: "_ZNSt13_Bvector_baseISaIbEE13_M_deallocateEv", scope: !2558, file: !2555, line: 533, type: !2873, scopeLine: 533, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2889 = !DISubprogram(name: "_M_move_data", linkageName: "_ZNSt13_Bvector_baseISaIbEE12_M_move_dataEOS1_", scope: !2558, file: !2555, line: 547, type: !2881, scopeLine: 547, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2890 = !DISubprogram(name: "_S_nword", linkageName: "_ZNSt13_Bvector_baseISaIbEE8_S_nwordEm", scope: !2558, file: !2555, line: 552, type: !2891, scopeLine: 552, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2891 = !DISubroutineType(types: !2892)
!2892 = !{!1152, !1152}
!2893 = !DISubprogram(name: "get_allocator", linkageName: "_ZNKSt6vectorIbSaIbEE13get_allocatorEv", scope: !2554, file: !2555, line: 613, type: !2894, scopeLine: 613, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2894 = !DISubroutineType(types: !2895)
!2895 = !{!2896, !2897}
!2896 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !2554, file: !2555, line: 610, baseType: !2579)
!2897 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2898, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2898 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2554)
!2899 = !DISubprogram(name: "vector", scope: !2554, file: !2555, line: 624, type: !2900, scopeLine: 624, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2900 = !DISubroutineType(types: !2901)
!2901 = !{null, !2902}
!2902 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2554, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2903 = !DISubprogram(name: "vector", scope: !2554, file: !2555, line: 630, type: !2904, scopeLine: 630, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2904 = !DISubroutineType(types: !2905)
!2905 = !{null, !2902, !2906}
!2906 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2907, size: 64)
!2907 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2896)
!2908 = !DISubprogram(name: "vector", scope: !2554, file: !2555, line: 635, type: !2909, scopeLine: 635, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2909 = !DISubroutineType(types: !2910)
!2910 = !{null, !2902, !2911, !2906}
!2911 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !2555, line: 600, baseType: !1152)
!2912 = !DISubprogram(name: "vector", scope: !2554, file: !2555, line: 639, type: !2913, scopeLine: 639, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2913 = !DISubroutineType(types: !2914)
!2914 = !{null, !2902, !2911, !2915, !2906}
!2915 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1531, size: 64)
!2916 = !DISubprogram(name: "vector", scope: !2554, file: !2555, line: 652, type: !2917, scopeLine: 652, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2917 = !DISubroutineType(types: !2918)
!2918 = !{null, !2902, !2919}
!2919 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2898, size: 64)
!2920 = !DISubprogram(name: "vector", scope: !2554, file: !2555, line: 660, type: !2921, scopeLine: 660, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2921 = !DISubroutineType(types: !2922)
!2922 = !{null, !2902, !2923}
!2923 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2554, size: 64)
!2924 = !DISubprogram(name: "vector", scope: !2554, file: !2555, line: 662, type: !2925, scopeLine: 662, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2925 = !DISubroutineType(types: !2926)
!2926 = !{null, !2902, !2923, !2906}
!2927 = !DISubprogram(name: "vector", scope: !2554, file: !2555, line: 676, type: !2928, scopeLine: 676, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2928 = !DISubroutineType(types: !2929)
!2929 = !{null, !2902, !2919, !2906}
!2930 = !DISubprogram(name: "vector", scope: !2554, file: !2555, line: 683, type: !2931, scopeLine: 683, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2931 = !DISubroutineType(types: !2932)
!2932 = !{null, !2902, !2933, !2906}
!2933 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<bool>", scope: !192, file: !1318, line: 47, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2934, templateParams: !2957, identifier: "_ZTSSt16initializer_listIbE")
!2934 = !{!2935, !2938, !2940, !2945, !2948, !2953, !2956}
!2935 = !DIDerivedType(tag: DW_TAG_member, name: "_M_array", scope: !2933, file: !1318, line: 58, baseType: !2936, size: 64)
!2936 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2933, file: !1318, line: 54, baseType: !2937)
!2937 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1531, size: 64)
!2938 = !DIDerivedType(tag: DW_TAG_member, name: "_M_len", scope: !2933, file: !1318, line: 59, baseType: !2939, size: 64, offset: 64)
!2939 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !1318, line: 53, baseType: !1152)
!2940 = !DISubprogram(name: "initializer_list", scope: !2933, file: !1318, line: 62, type: !2941, scopeLine: 62, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2941 = !DISubroutineType(types: !2942)
!2942 = !{null, !2943, !2944, !2939}
!2943 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2933, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2944 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !2933, file: !1318, line: 55, baseType: !2937)
!2945 = !DISubprogram(name: "initializer_list", scope: !2933, file: !1318, line: 66, type: !2946, scopeLine: 66, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2946 = !DISubroutineType(types: !2947)
!2947 = !{null, !2943}
!2948 = !DISubprogram(name: "size", linkageName: "_ZNKSt16initializer_listIbE4sizeEv", scope: !2933, file: !1318, line: 71, type: !2949, scopeLine: 71, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2949 = !DISubroutineType(types: !2950)
!2950 = !{!2939, !2951}
!2951 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2952, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2952 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2933)
!2953 = !DISubprogram(name: "begin", linkageName: "_ZNKSt16initializer_listIbE5beginEv", scope: !2933, file: !1318, line: 75, type: !2954, scopeLine: 75, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2954 = !DISubroutineType(types: !2955)
!2955 = !{!2944, !2951}
!2956 = !DISubprogram(name: "end", linkageName: "_ZNKSt16initializer_listIbE3endEv", scope: !2933, file: !1318, line: 79, type: !2954, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2957 = !{!2958}
!2958 = !DITemplateTypeParameter(name: "_E", type: !132)
!2959 = !DISubprogram(name: "~vector", scope: !2554, file: !2555, line: 710, type: !2900, scopeLine: 710, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2960 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIbSaIbEEaSERKS1_", scope: !2554, file: !2555, line: 713, type: !2961, scopeLine: 713, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2961 = !DISubroutineType(types: !2962)
!2962 = !{!2963, !2902, !2919}
!2963 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2554, size: 64)
!2964 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIbSaIbEEaSEOS1_", scope: !2554, file: !2555, line: 744, type: !2965, scopeLine: 744, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2965 = !DISubroutineType(types: !2966)
!2966 = !{!2963, !2902, !2923}
!2967 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIbSaIbEEaSESt16initializer_listIbE", scope: !2554, file: !2555, line: 769, type: !2968, scopeLine: 769, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2968 = !DISubroutineType(types: !2969)
!2969 = !{!2963, !2902, !2933}
!2970 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorIbSaIbEE6assignEmRKb", scope: !2554, file: !2555, line: 781, type: !2971, scopeLine: 781, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2971 = !DISubroutineType(types: !2972)
!2972 = !{null, !2902, !2911, !2915}
!2973 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorIbSaIbEE6assignESt16initializer_listIbE", scope: !2554, file: !2555, line: 802, type: !2974, scopeLine: 802, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2974 = !DISubroutineType(types: !2975)
!2975 = !{null, !2902, !2933}
!2976 = !DISubprogram(name: "begin", linkageName: "_ZNSt6vectorIbSaIbEE5beginEv", scope: !2554, file: !2555, line: 807, type: !2977, scopeLine: 807, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2977 = !DISubroutineType(types: !2978)
!2978 = !{!2979, !2902}
!2979 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", file: !2555, line: 606, baseType: !2670)
!2980 = !DISubprogram(name: "begin", linkageName: "_ZNKSt6vectorIbSaIbEE5beginEv", scope: !2554, file: !2555, line: 811, type: !2981, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2981 = !DISubroutineType(types: !2982)
!2982 = !{!2983, !2897}
!2983 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", file: !2555, line: 607, baseType: !2984)
!2984 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bit_const_iterator", scope: !192, file: !2555, line: 302, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2985, identifier: "_ZTSSt19_Bit_const_iterator")
!2985 = !{!2986, !2987, !2991, !2994, !2998, !3003, !3007, !3012, !3015, !3016, !3017, !3020, !3021, !3024, !3025}
!2986 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2984, baseType: !2673, extraData: i32 0)
!2987 = !DISubprogram(name: "_Bit_const_iterator", scope: !2984, file: !2555, line: 309, type: !2988, scopeLine: 309, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2988 = !DISubroutineType(types: !2989)
!2989 = !{null, !2990}
!2990 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2984, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2991 = !DISubprogram(name: "_Bit_const_iterator", scope: !2984, file: !2555, line: 311, type: !2992, scopeLine: 311, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2992 = !DISubroutineType(types: !2993)
!2993 = !{null, !2990, !2693, !6}
!2994 = !DISubprogram(name: "_Bit_const_iterator", scope: !2984, file: !2555, line: 314, type: !2995, scopeLine: 314, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2995 = !DISubroutineType(types: !2996)
!2996 = !{null, !2990, !2997}
!2997 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2730, size: 64)
!2998 = !DISubprogram(name: "_M_const_cast", linkageName: "_ZNKSt19_Bit_const_iterator13_M_const_castEv", scope: !2984, file: !2555, line: 318, type: !2999, scopeLine: 318, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2999 = !DISubroutineType(types: !3000)
!3000 = !{!2670, !3001}
!3001 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3002, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3002 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2984)
!3003 = !DISubprogram(name: "operator*", linkageName: "_ZNKSt19_Bit_const_iteratordeEv", scope: !2984, file: !2555, line: 322, type: !3004, scopeLine: 322, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3004 = !DISubroutineType(types: !3005)
!3005 = !{!3006, !3001}
!3006 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !2984, file: !2555, line: 305, baseType: !132)
!3007 = !DISubprogram(name: "operator++", linkageName: "_ZNSt19_Bit_const_iteratorppEv", scope: !2984, file: !2555, line: 326, type: !3008, scopeLine: 326, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3008 = !DISubroutineType(types: !3009)
!3009 = !{!3010, !2990}
!3010 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3011, size: 64)
!3011 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !2984, file: !2555, line: 307, baseType: !2984)
!3012 = !DISubprogram(name: "operator++", linkageName: "_ZNSt19_Bit_const_iteratorppEi", scope: !2984, file: !2555, line: 333, type: !3013, scopeLine: 333, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3013 = !DISubroutineType(types: !3014)
!3014 = !{!3011, !2990, !24}
!3015 = !DISubprogram(name: "operator--", linkageName: "_ZNSt19_Bit_const_iteratormmEv", scope: !2984, file: !2555, line: 341, type: !3008, scopeLine: 341, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3016 = !DISubprogram(name: "operator--", linkageName: "_ZNSt19_Bit_const_iteratormmEi", scope: !2984, file: !2555, line: 348, type: !3013, scopeLine: 348, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3017 = !DISubprogram(name: "operator+=", linkageName: "_ZNSt19_Bit_const_iteratorpLEl", scope: !2984, file: !2555, line: 356, type: !3018, scopeLine: 356, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3018 = !DISubroutineType(types: !3019)
!3019 = !{!3010, !2990, !2776}
!3020 = !DISubprogram(name: "operator-=", linkageName: "_ZNSt19_Bit_const_iteratormIEl", scope: !2984, file: !2555, line: 363, type: !3018, scopeLine: 363, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3021 = !DISubprogram(name: "operator+", linkageName: "_ZNKSt19_Bit_const_iteratorplEl", scope: !2984, file: !2555, line: 370, type: !3022, scopeLine: 370, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3022 = !DISubroutineType(types: !3023)
!3023 = !{!3011, !3001, !2776}
!3024 = !DISubprogram(name: "operator-", linkageName: "_ZNKSt19_Bit_const_iteratormiEl", scope: !2984, file: !2555, line: 377, type: !3022, scopeLine: 377, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3025 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt19_Bit_const_iteratorixEl", scope: !2984, file: !2555, line: 384, type: !3026, scopeLine: 384, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3026 = !DISubroutineType(types: !3027)
!3027 = !{!3006, !3001, !2776}
!3028 = !DISubprogram(name: "end", linkageName: "_ZNSt6vectorIbSaIbEE3endEv", scope: !2554, file: !2555, line: 815, type: !2977, scopeLine: 815, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3029 = !DISubprogram(name: "end", linkageName: "_ZNKSt6vectorIbSaIbEE3endEv", scope: !2554, file: !2555, line: 819, type: !2981, scopeLine: 819, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3030 = !DISubprogram(name: "rbegin", linkageName: "_ZNSt6vectorIbSaIbEE6rbeginEv", scope: !2554, file: !2555, line: 823, type: !3031, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3031 = !DISubroutineType(types: !3032)
!3032 = !{!3033, !2902}
!3033 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", file: !2555, line: 609, baseType: !3034)
!3034 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<std::_Bit_iterator>", scope: !192, file: !631, line: 101, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorISt13_Bit_iteratorE")
!3035 = !DISubprogram(name: "rbegin", linkageName: "_ZNKSt6vectorIbSaIbEE6rbeginEv", scope: !2554, file: !2555, line: 827, type: !3036, scopeLine: 827, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3036 = !DISubroutineType(types: !3037)
!3037 = !{!3038, !2897}
!3038 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", file: !2555, line: 608, baseType: !3039)
!3039 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<std::_Bit_const_iterator>", scope: !192, file: !631, line: 101, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorISt19_Bit_const_iteratorE")
!3040 = !DISubprogram(name: "rend", linkageName: "_ZNSt6vectorIbSaIbEE4rendEv", scope: !2554, file: !2555, line: 831, type: !3031, scopeLine: 831, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3041 = !DISubprogram(name: "rend", linkageName: "_ZNKSt6vectorIbSaIbEE4rendEv", scope: !2554, file: !2555, line: 835, type: !3036, scopeLine: 835, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3042 = !DISubprogram(name: "cbegin", linkageName: "_ZNKSt6vectorIbSaIbEE6cbeginEv", scope: !2554, file: !2555, line: 840, type: !2981, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3043 = !DISubprogram(name: "cend", linkageName: "_ZNKSt6vectorIbSaIbEE4cendEv", scope: !2554, file: !2555, line: 844, type: !2981, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3044 = !DISubprogram(name: "crbegin", linkageName: "_ZNKSt6vectorIbSaIbEE7crbeginEv", scope: !2554, file: !2555, line: 848, type: !3036, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3045 = !DISubprogram(name: "crend", linkageName: "_ZNKSt6vectorIbSaIbEE5crendEv", scope: !2554, file: !2555, line: 852, type: !3036, scopeLine: 852, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3046 = !DISubprogram(name: "size", linkageName: "_ZNKSt6vectorIbSaIbEE4sizeEv", scope: !2554, file: !2555, line: 857, type: !3047, scopeLine: 857, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3047 = !DISubroutineType(types: !3048)
!3048 = !{!2911, !2897}
!3049 = !DISubprogram(name: "max_size", linkageName: "_ZNKSt6vectorIbSaIbEE8max_sizeEv", scope: !2554, file: !2555, line: 861, type: !3047, scopeLine: 861, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3050 = !DISubprogram(name: "capacity", linkageName: "_ZNKSt6vectorIbSaIbEE8capacityEv", scope: !2554, file: !2555, line: 873, type: !3047, scopeLine: 873, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3051 = !DISubprogram(name: "empty", linkageName: "_ZNKSt6vectorIbSaIbEE5emptyEv", scope: !2554, file: !2555, line: 878, type: !3052, scopeLine: 878, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3052 = !DISubroutineType(types: !3053)
!3053 = !{!132, !2897}
!3054 = !DISubprogram(name: "operator[]", linkageName: "_ZNSt6vectorIbSaIbEEixEm", scope: !2554, file: !2555, line: 882, type: !3055, scopeLine: 882, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3055 = !DISubroutineType(types: !3056)
!3056 = !{!3057, !2902, !2911}
!3057 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2554, file: !2555, line: 602, baseType: !2735)
!3058 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt6vectorIbSaIbEEixEm", scope: !2554, file: !2555, line: 889, type: !3059, scopeLine: 889, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3059 = !DISubroutineType(types: !3060)
!3060 = !{!3061, !2897, !2911}
!3061 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !2554, file: !2555, line: 603, baseType: !132)
!3062 = !DISubprogram(name: "_M_range_check", linkageName: "_ZNKSt6vectorIbSaIbEE14_M_range_checkEm", scope: !2554, file: !2555, line: 897, type: !3063, scopeLine: 897, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3063 = !DISubroutineType(types: !3064)
!3064 = !{null, !2897, !2911}
!3065 = !DISubprogram(name: "at", linkageName: "_ZNSt6vectorIbSaIbEE2atEm", scope: !2554, file: !2555, line: 908, type: !3055, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3066 = !DISubprogram(name: "at", linkageName: "_ZNKSt6vectorIbSaIbEE2atEm", scope: !2554, file: !2555, line: 912, type: !3059, scopeLine: 912, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3067 = !DISubprogram(name: "reserve", linkageName: "_ZNSt6vectorIbSaIbEE7reserveEm", scope: !2554, file: !2555, line: 916, type: !3068, scopeLine: 916, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3068 = !DISubroutineType(types: !3069)
!3069 = !{null, !2902, !2911}
!3070 = !DISubprogram(name: "front", linkageName: "_ZNSt6vectorIbSaIbEE5frontEv", scope: !2554, file: !2555, line: 925, type: !3071, scopeLine: 925, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3071 = !DISubroutineType(types: !3072)
!3072 = !{!3073, !2902}
!3073 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", file: !2555, line: 602, baseType: !2735)
!3074 = !DISubprogram(name: "front", linkageName: "_ZNKSt6vectorIbSaIbEE5frontEv", scope: !2554, file: !2555, line: 929, type: !3075, scopeLine: 929, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3075 = !DISubroutineType(types: !3076)
!3076 = !{!3077, !2897}
!3077 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", file: !2555, line: 603, baseType: !132)
!3078 = !DISubprogram(name: "back", linkageName: "_ZNSt6vectorIbSaIbEE4backEv", scope: !2554, file: !2555, line: 933, type: !3071, scopeLine: 933, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3079 = !DISubprogram(name: "back", linkageName: "_ZNKSt6vectorIbSaIbEE4backEv", scope: !2554, file: !2555, line: 937, type: !3075, scopeLine: 937, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3080 = !DISubprogram(name: "data", linkageName: "_ZNSt6vectorIbSaIbEE4dataEv", scope: !2554, file: !2555, line: 946, type: !2900, scopeLine: 946, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3081 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorIbSaIbEE9push_backEb", scope: !2554, file: !2555, line: 949, type: !3082, scopeLine: 949, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3082 = !DISubroutineType(types: !3083)
!3083 = !{null, !2902, !132}
!3084 = !DISubprogram(name: "swap", linkageName: "_ZNSt6vectorIbSaIbEE4swapERS1_", scope: !2554, file: !2555, line: 958, type: !3085, scopeLine: 958, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3085 = !DISubroutineType(types: !3086)
!3086 = !{null, !2902, !2963}
!3087 = !DISubprogram(name: "swap", linkageName: "_ZNSt6vectorIbSaIbEE4swapESt14_Bit_referenceS2_", scope: !2554, file: !2555, line: 970, type: !3088, scopeLine: 970, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3088 = !DISubroutineType(types: !3089)
!3089 = !{null, !3073, !3073}
!3090 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIbSaIbEE6insertESt19_Bit_const_iteratorRKb", scope: !2554, file: !2555, line: 979, type: !3091, scopeLine: 979, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3091 = !DISubroutineType(types: !3092)
!3092 = !{!3093, !2902, !2983, !2915}
!3093 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2554, file: !2555, line: 606, baseType: !2670)
!3094 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIbSaIbEE6insertESt19_Bit_const_iteratormRKb", scope: !2554, file: !2555, line: 1018, type: !3095, scopeLine: 1018, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3095 = !DISubroutineType(types: !3096)
!3096 = !{!3093, !2902, !2983, !2911, !2915}
!3097 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIbSaIbEE6insertESt19_Bit_const_iteratorSt16initializer_listIbE", scope: !2554, file: !2555, line: 1032, type: !3098, scopeLine: 1032, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3098 = !DISubroutineType(types: !3099)
!3099 = !{!3093, !2902, !2983, !2933}
!3100 = !DISubprogram(name: "pop_back", linkageName: "_ZNSt6vectorIbSaIbEE8pop_backEv", scope: !2554, file: !2555, line: 1037, type: !2900, scopeLine: 1037, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3101 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorIbSaIbEE5eraseESt19_Bit_const_iterator", scope: !2554, file: !2555, line: 1042, type: !3102, scopeLine: 1042, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3102 = !DISubroutineType(types: !3103)
!3103 = !{!3093, !2902, !2983}
!3104 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorIbSaIbEE5eraseESt19_Bit_const_iteratorS2_", scope: !2554, file: !2555, line: 1050, type: !3105, scopeLine: 1050, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3105 = !DISubroutineType(types: !3106)
!3106 = !{!3093, !2902, !2983, !2983}
!3107 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorIbSaIbEE6resizeEmb", scope: !2554, file: !2555, line: 1057, type: !3108, scopeLine: 1057, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3108 = !DISubroutineType(types: !3109)
!3109 = !{null, !2902, !2911, !132}
!3110 = !DISubprogram(name: "shrink_to_fit", linkageName: "_ZNSt6vectorIbSaIbEE13shrink_to_fitEv", scope: !2554, file: !2555, line: 1067, type: !2900, scopeLine: 1067, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3111 = !DISubprogram(name: "flip", linkageName: "_ZNSt6vectorIbSaIbEE4flipEv", scope: !2554, file: !2555, line: 1072, type: !2900, scopeLine: 1072, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3112 = !DISubprogram(name: "clear", linkageName: "_ZNSt6vectorIbSaIbEE5clearEv", scope: !2554, file: !2555, line: 1080, type: !2900, scopeLine: 1080, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3113 = !DISubprogram(name: "_M_copy_aligned", linkageName: "_ZNSt6vectorIbSaIbEE15_M_copy_alignedESt19_Bit_const_iteratorS2_St13_Bit_iterator", scope: !2554, file: !2555, line: 1107, type: !3114, scopeLine: 1107, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3114 = !DISubroutineType(types: !3115)
!3115 = !{!3093, !2902, !2983, !2983, !2979}
!3116 = !DISubprogram(name: "_M_initialize", linkageName: "_ZNSt6vectorIbSaIbEE13_M_initializeEm", scope: !2554, file: !2555, line: 1116, type: !3068, scopeLine: 1116, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3117 = !DISubprogram(name: "_M_initialize_value", linkageName: "_ZNSt6vectorIbSaIbEE19_M_initialize_valueEb", scope: !2554, file: !2555, line: 1134, type: !3082, scopeLine: 1134, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3118 = !DISubprogram(name: "_M_reallocate", linkageName: "_ZNSt6vectorIbSaIbEE13_M_reallocateEm", scope: !2554, file: !2555, line: 1143, type: !3068, scopeLine: 1143, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3119 = !DISubprogram(name: "_M_shrink_to_fit", linkageName: "_ZNSt6vectorIbSaIbEE16_M_shrink_to_fitEv", scope: !2554, file: !2555, line: 1147, type: !3120, scopeLine: 1147, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3120 = !DISubroutineType(types: !3121)
!3121 = !{!132, !2902}
!3122 = !DISubprogram(name: "_M_fill_assign", linkageName: "_ZNSt6vectorIbSaIbEE14_M_fill_assignEmb", scope: !2554, file: !2555, line: 1204, type: !3123, scopeLine: 1204, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3123 = !DISubroutineType(types: !3124)
!3124 = !{null, !2902, !1152, !132}
!3125 = !DISubprogram(name: "_M_fill_insert", linkageName: "_ZNSt6vectorIbSaIbEE14_M_fill_insertESt13_Bit_iteratormb", scope: !2554, file: !2555, line: 1268, type: !3126, scopeLine: 1268, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3126 = !DISubroutineType(types: !3127)
!3127 = !{null, !2902, !2979, !2911, !132}
!3128 = !DISubprogram(name: "_M_insert_aux", linkageName: "_ZNSt6vectorIbSaIbEE13_M_insert_auxESt13_Bit_iteratorb", scope: !2554, file: !2555, line: 1288, type: !3129, scopeLine: 1288, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3129 = !DISubroutineType(types: !3130)
!3130 = !{null, !2902, !2979, !132}
!3131 = !DISubprogram(name: "_M_check_len", linkageName: "_ZNKSt6vectorIbSaIbEE12_M_check_lenEmPKc", scope: !2554, file: !2555, line: 1291, type: !3132, scopeLine: 1291, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3132 = !DISubroutineType(types: !3133)
!3133 = !{!3134, !2897, !2911, !163}
!3134 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2554, file: !2555, line: 600, baseType: !1152)
!3135 = !DISubprogram(name: "_M_erase_at_end", linkageName: "_ZNSt6vectorIbSaIbEE15_M_erase_at_endESt13_Bit_iterator", scope: !2554, file: !2555, line: 1301, type: !3136, scopeLine: 1301, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3136 = !DISubroutineType(types: !3137)
!3137 = !{null, !2902, !2979}
!3138 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorIbSaIbEE8_M_eraseESt13_Bit_iterator", scope: !2554, file: !2555, line: 1305, type: !3139, scopeLine: 1305, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3139 = !DISubroutineType(types: !3140)
!3140 = !{!3093, !2902, !2979}
!3141 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorIbSaIbEE8_M_eraseESt13_Bit_iteratorS2_", scope: !2554, file: !2555, line: 1308, type: !3142, scopeLine: 1308, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3142 = !DISubroutineType(types: !3143)
!3143 = !{!3093, !2902, !2979, !2979}
!3144 = !{!1540, !2596}
!3145 = !DIDerivedType(tag: DW_TAG_member, name: "CurrentNode", scope: !2364, file: !108, line: 812, baseType: !2362, size: 64, offset: 1920)
!3146 = !DIDerivedType(tag: DW_TAG_member, name: "ScalarMatchFound", scope: !2364, file: !108, line: 813, baseType: !132, size: 8, offset: 1984)
!3147 = !DISubprogram(name: "Input", scope: !2364, file: !108, line: 691, type: !3148, scopeLine: 691, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3148 = !DISubroutineType(types: !3149)
!3149 = !{null, !3150, !154, !121, !2037, !121}
!3150 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2364, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3151 = !DISubprogram(name: "~Input", scope: !2364, file: !108, line: 695, type: !3152, scopeLine: 695, containingType: !2364, virtualIndex: 0, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3152 = !DISubroutineType(types: !3153)
!3153 = !{null, !3150}
!3154 = !DISubprogram(name: "error", linkageName: "_ZN4llvm4yaml5Input5errorEv", scope: !2364, file: !108, line: 698, type: !3155, scopeLine: 698, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3155 = !DISubroutineType(types: !3156)
!3156 = !{!2472, !3150}
!3157 = !DISubprogram(name: "classof", linkageName: "_ZN4llvm4yaml5Input7classofEPKNS0_2IOE", scope: !2364, file: !108, line: 700, type: !1006, scopeLine: 700, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3158 = !DISubprogram(name: "outputting", linkageName: "_ZNK4llvm4yaml5Input10outputtingEv", scope: !2364, file: !108, line: 703, type: !3159, scopeLine: 703, containingType: !2364, virtualIndex: 2, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3159 = !DISubroutineType(types: !3160)
!3160 = !{!132, !3161}
!3161 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3162, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3162 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2364)
!3163 = !DISubprogram(name: "mapTag", linkageName: "_ZN4llvm4yaml5Input6mapTagENS_9StringRefEb", scope: !2364, file: !108, line: 704, type: !3164, scopeLine: 704, containingType: !2364, virtualIndex: 12, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3164 = !DISubroutineType(types: !3165)
!3165 = !{!132, !3150, !154, !132}
!3166 = !DISubprogram(name: "beginMapping", linkageName: "_ZN4llvm4yaml5Input12beginMappingEv", scope: !2364, file: !108, line: 705, type: !3152, scopeLine: 705, containingType: !2364, virtualIndex: 13, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3167 = !DISubprogram(name: "endMapping", linkageName: "_ZN4llvm4yaml5Input10endMappingEv", scope: !2364, file: !108, line: 706, type: !3152, scopeLine: 706, containingType: !2364, virtualIndex: 14, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3168 = !DISubprogram(name: "preflightKey", linkageName: "_ZN4llvm4yaml5Input12preflightKeyEPKcbbRbRPv", scope: !2364, file: !108, line: 707, type: !3169, scopeLine: 707, containingType: !2364, virtualIndex: 15, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3169 = !DISubroutineType(types: !3170)
!3170 = !{!132, !3150, !163, !132, !132, !362, !141}
!3171 = !DISubprogram(name: "postflightKey", linkageName: "_ZN4llvm4yaml5Input13postflightKeyEPv", scope: !2364, file: !108, line: 708, type: !3172, scopeLine: 708, containingType: !2364, virtualIndex: 16, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3172 = !DISubroutineType(types: !3173)
!3173 = !{null, !3150, !121}
!3174 = !DISubprogram(name: "beginSequence", linkageName: "_ZN4llvm4yaml5Input13beginSequenceEv", scope: !2364, file: !108, line: 709, type: !3175, scopeLine: 709, containingType: !2364, virtualIndex: 3, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3175 = !DISubroutineType(types: !3176)
!3176 = !{!6, !3150}
!3177 = !DISubprogram(name: "endSequence", linkageName: "_ZN4llvm4yaml5Input11endSequenceEv", scope: !2364, file: !108, line: 710, type: !3152, scopeLine: 710, containingType: !2364, virtualIndex: 6, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3178 = !DISubprogram(name: "preflightElement", linkageName: "_ZN4llvm4yaml5Input16preflightElementEjRPv", scope: !2364, file: !108, line: 711, type: !3179, scopeLine: 711, containingType: !2364, virtualIndex: 4, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3179 = !DISubroutineType(types: !3180)
!3180 = !{!132, !3150, !6, !141}
!3181 = !DISubprogram(name: "postflightElement", linkageName: "_ZN4llvm4yaml5Input17postflightElementEPv", scope: !2364, file: !108, line: 712, type: !3172, scopeLine: 712, containingType: !2364, virtualIndex: 5, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3182 = !DISubprogram(name: "beginFlowSequence", linkageName: "_ZN4llvm4yaml5Input17beginFlowSequenceEv", scope: !2364, file: !108, line: 713, type: !3175, scopeLine: 713, containingType: !2364, virtualIndex: 8, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3183 = !DISubprogram(name: "preflightFlowElement", linkageName: "_ZN4llvm4yaml5Input20preflightFlowElementEjRPv", scope: !2364, file: !108, line: 714, type: !3179, scopeLine: 714, containingType: !2364, virtualIndex: 9, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3184 = !DISubprogram(name: "postflightFlowElement", linkageName: "_ZN4llvm4yaml5Input21postflightFlowElementEPv", scope: !2364, file: !108, line: 715, type: !3172, scopeLine: 715, containingType: !2364, virtualIndex: 10, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3185 = !DISubprogram(name: "endFlowSequence", linkageName: "_ZN4llvm4yaml5Input15endFlowSequenceEv", scope: !2364, file: !108, line: 716, type: !3152, scopeLine: 716, containingType: !2364, virtualIndex: 11, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3186 = !DISubprogram(name: "beginEnumScalar", linkageName: "_ZN4llvm4yaml5Input15beginEnumScalarEv", scope: !2364, file: !108, line: 717, type: !3152, scopeLine: 717, containingType: !2364, virtualIndex: 17, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3187 = !DISubprogram(name: "matchEnumScalar", linkageName: "_ZN4llvm4yaml5Input15matchEnumScalarEPKcb", scope: !2364, file: !108, line: 718, type: !3188, scopeLine: 718, containingType: !2364, virtualIndex: 18, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3188 = !DISubroutineType(types: !3189)
!3189 = !{!132, !3150, !163, !132}
!3190 = !DISubprogram(name: "endEnumScalar", linkageName: "_ZN4llvm4yaml5Input13endEnumScalarEv", scope: !2364, file: !108, line: 719, type: !3152, scopeLine: 719, containingType: !2364, virtualIndex: 19, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3191 = !DISubprogram(name: "beginBitSetScalar", linkageName: "_ZN4llvm4yaml5Input17beginBitSetScalarERb", scope: !2364, file: !108, line: 720, type: !3192, scopeLine: 720, containingType: !2364, virtualIndex: 20, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3192 = !DISubroutineType(types: !3193)
!3193 = !{!132, !3150, !362}
!3194 = !DISubprogram(name: "bitSetMatch", linkageName: "_ZN4llvm4yaml5Input11bitSetMatchEPKcb", scope: !2364, file: !108, line: 721, type: !3188, scopeLine: 721, containingType: !2364, virtualIndex: 21, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3195 = !DISubprogram(name: "endBitSetScalar", linkageName: "_ZN4llvm4yaml5Input15endBitSetScalarEv", scope: !2364, file: !108, line: 722, type: !3152, scopeLine: 722, containingType: !2364, virtualIndex: 22, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3196 = !DISubprogram(name: "scalarString", linkageName: "_ZN4llvm4yaml5Input12scalarStringERNS_9StringRefE", scope: !2364, file: !108, line: 723, type: !3197, scopeLine: 723, containingType: !2364, virtualIndex: 23, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3197 = !DISubroutineType(types: !3198)
!3198 = !{null, !3150, !377}
!3199 = !DISubprogram(name: "setError", linkageName: "_ZN4llvm4yaml5Input8setErrorERKNS_5TwineE", scope: !2364, file: !108, line: 724, type: !3200, scopeLine: 724, containingType: !2364, virtualIndex: 24, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3200 = !DISubroutineType(types: !3201)
!3201 = !{null, !3150, !381}
!3202 = !DISubprogram(name: "canElideEmptySequence", linkageName: "_ZN4llvm4yaml5Input21canElideEmptySequenceEv", scope: !2364, file: !108, line: 725, type: !3203, scopeLine: 725, containingType: !2364, virtualIndex: 7, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3203 = !DISubroutineType(types: !3204)
!3204 = !{!132, !3150}
!3205 = !DISubprogram(name: "createHNodes", linkageName: "_ZN4llvm4yaml5Input12createHNodesEPNS0_4NodeE", scope: !2364, file: !108, line: 793, type: !3206, scopeLine: 793, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3206 = !DISubroutineType(types: !3207)
!3207 = !{!2362, !3150, !3208}
!3208 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2333, size: 64)
!3209 = !DISubprogram(name: "setError", linkageName: "_ZN4llvm4yaml5Input8setErrorEPNS1_5HNodeERKNS_5TwineE", scope: !2364, file: !108, line: 794, type: !3210, scopeLine: 794, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3210 = !DISubroutineType(types: !3211)
!3211 = !{null, !3150, !2362, !381}
!3212 = !DISubprogram(name: "setError", linkageName: "_ZN4llvm4yaml5Input8setErrorEPNS0_4NodeERKNS_5TwineE", scope: !2364, file: !108, line: 795, type: !3213, scopeLine: 795, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3213 = !DISubroutineType(types: !3214)
!3214 = !{null, !3150, !3208, !381}
!3215 = !DISubprogram(name: "setCurrentDocument", linkageName: "_ZN4llvm4yaml5Input18setCurrentDocumentEv", scope: !2364, file: !108, line: 801, type: !3203, scopeLine: 801, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3216 = !DISubprogram(name: "nextDocument", linkageName: "_ZN4llvm4yaml5Input12nextDocumentEv", scope: !2364, file: !108, line: 802, type: !3152, scopeLine: 802, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3217 = !{!3218, !3219, !3220, !3224, !3227, !3228}
!3218 = !DIDerivedType(tag: DW_TAG_member, name: "_vptr$HNode", scope: !108, file: !108, baseType: !116, size: 64, flags: DIFlagArtificial)
!3219 = !DIDerivedType(tag: DW_TAG_member, name: "_node", scope: !2363, file: !108, line: 734, baseType: !3208, size: 64, offset: 64, flags: DIFlagPublic)
!3220 = !DISubprogram(name: "anchor", linkageName: "_ZN4llvm4yaml5Input5HNode6anchorEv", scope: !2363, file: !108, line: 728, type: !3221, scopeLine: 728, containingType: !2363, virtualIndex: 0, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3221 = !DISubroutineType(types: !3222)
!3222 = !{null, !3223}
!3223 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2363, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3224 = !DISubprogram(name: "HNode", scope: !2363, file: !108, line: 730, type: !3225, scopeLine: 730, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3225 = !DISubroutineType(types: !3226)
!3226 = !{null, !3223, !3208}
!3227 = !DISubprogram(name: "~HNode", scope: !2363, file: !108, line: 731, type: !3221, scopeLine: 731, containingType: !2363, virtualIndex: 0, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3228 = !DISubprogram(name: "classof", linkageName: "_ZN4llvm4yaml5Input5HNode7classofEPKS2_", scope: !2363, file: !108, line: 732, type: !3229, scopeLine: 732, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3229 = !DISubroutineType(types: !3230)
!3230 = !{!132, !3231}
!3231 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3232, size: 64)
!3232 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2363)
!3233 = !DISubprogram(name: "StringMapEntry", scope: !2345, file: !2346, line: 119, type: !3234, scopeLine: 119, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!3234 = !DISubroutineType(types: !3235)
!3235 = !{null, !3236, !3237}
!3236 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2345, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3237 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2345, size: 64)
!3238 = !DISubprogram(name: "StringMapEntry", scope: !2345, file: !2346, line: 123, type: !3239, scopeLine: 123, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3239 = !DISubroutineType(types: !3240)
!3240 = !{null, !3236, !6}
!3241 = !DISubprogram(name: "StringMapEntry", scope: !2345, file: !2346, line: 125, type: !3242, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3242 = !DISubroutineType(types: !3243)
!3243 = !{null, !3236, !6, !3244}
!3244 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3245, size: 64)
!3245 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2362)
!3246 = !DISubprogram(name: "getKey", linkageName: "_ZNK4llvm14StringMapEntryIPNS_4yaml5Input5HNodeEE6getKeyEv", scope: !2345, file: !2346, line: 128, type: !3247, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3247 = !DISubroutineType(types: !3248)
!3248 = !{!154, !3249}
!3249 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3250, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3250 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2345)
!3251 = !DISubprogram(name: "getValue", linkageName: "_ZNK4llvm14StringMapEntryIPNS_4yaml5Input5HNodeEE8getValueEv", scope: !2345, file: !2346, line: 132, type: !3252, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3252 = !DISubroutineType(types: !3253)
!3253 = !{!3244, !3249}
!3254 = !DISubprogram(name: "getValue", linkageName: "_ZN4llvm14StringMapEntryIPNS_4yaml5Input5HNodeEE8getValueEv", scope: !2345, file: !2346, line: 133, type: !3255, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3255 = !DISubroutineType(types: !3256)
!3256 = !{!3257, !3236}
!3257 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2362, size: 64)
!3258 = !DISubprogram(name: "setValue", linkageName: "_ZN4llvm14StringMapEntryIPNS_4yaml5Input5HNodeEE8setValueERKS4_", scope: !2345, file: !2346, line: 135, type: !3259, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3259 = !DISubroutineType(types: !3260)
!3260 = !{null, !3236, !3244}
!3261 = !DISubprogram(name: "getKeyData", linkageName: "_ZNK4llvm14StringMapEntryIPNS_4yaml5Input5HNodeEE10getKeyDataEv", scope: !2345, file: !2346, line: 140, type: !3262, scopeLine: 140, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3262 = !DISubroutineType(types: !3263)
!3263 = !{!163, !3249}
!3264 = !DISubprogram(name: "first", linkageName: "_ZNK4llvm14StringMapEntryIPNS_4yaml5Input5HNodeEE5firstEv", scope: !2345, file: !2346, line: 142, type: !3247, scopeLine: 142, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3265 = !DISubprogram(name: "Create", linkageName: "_ZN4llvm14StringMapEntryIPNS_4yaml5Input5HNodeEE6CreateEPKcS7_", scope: !2345, file: !2346, line: 190, type: !3266, scopeLine: 190, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3266 = !DISubroutineType(types: !3267)
!3267 = !{!3268, !163, !163}
!3268 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2345, size: 64)
!3269 = !DISubprogram(name: "GetStringMapEntryFromValue", linkageName: "_ZN4llvm14StringMapEntryIPNS_4yaml5Input5HNodeEE26GetStringMapEntryFromValueERS4_", scope: !2345, file: !2346, line: 196, type: !3270, scopeLine: 196, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3270 = !DISubroutineType(types: !3271)
!3271 = !{!3237, !3257}
!3272 = !DISubprogram(name: "GetStringMapEntryFromValue", linkageName: "_ZN4llvm14StringMapEntryIPNS_4yaml5Input5HNodeEE26GetStringMapEntryFromValueERKS4_", scope: !2345, file: !2346, line: 203, type: !3273, scopeLine: 203, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3273 = !DISubroutineType(types: !3274)
!3274 = !{!3275, !3244}
!3275 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3250, size: 64)
!3276 = !DISubprogram(name: "GetStringMapEntryFromKeyData", linkageName: "_ZN4llvm14StringMapEntryIPNS_4yaml5Input5HNodeEE28GetStringMapEntryFromKeyDataEPKc", scope: !2345, file: !2346, line: 209, type: !3277, scopeLine: 209, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3277 = !DISubroutineType(types: !3278)
!3278 = !{!3237, !163}
!3279 = !DISubprogram(name: "Destroy", linkageName: "_ZN4llvm14StringMapEntryIPNS_4yaml5Input5HNodeEE7DestroyEv", scope: !2345, file: !2346, line: 224, type: !3280, scopeLine: 224, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3280 = !DISubroutineType(types: !3281)
!3281 = !{null, !3236}
!3282 = !{!3283}
!3283 = !DITemplateTypeParameter(name: "ValueTy", type: !2362)
!3284 = !{!3285}
!3285 = !DIEnumerator(name: "Alignment", value: 8, isUnsigned: true)
!3286 = !DICompositeType(tag: DW_TAG_enumeration_type, scope: !192, file: !2555, line: 70, baseType: !6, size: 32, elements: !3287)
!3287 = !{!3288}
!3288 = !DIEnumerator(name: "_S_word_bit", value: 64, isUnsigned: true)
!3289 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !3290, file: !575, line: 39, baseType: !6, size: 32, elements: !3291, identifier: "_ZTSN4llvm7AlignOfIcEUt_E")
!3290 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignOf<char>", scope: !14, file: !575, line: 38, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !753, identifier: "_ZTSN4llvm7AlignOfIcEE")
!3291 = !{!3292}
!3292 = !DIEnumerator(name: "Alignment", value: 1, isUnsigned: true)
!3293 = !{!132, !383, !2362, !24, !3294, !3347, !121, !429, !6, !613, !617, !1154, !825, !154, !161, !405, !3419, !3428, !3632, !3804, !3268, !163, !4056, !1292, !4333, !4364, !2911, !2670, !1152, !2636, !4125, !4365, !3208, !621, !4378, !4389, !3652, !4390, !4441, !3865, !829, !719, !650, !113, !2364, !4126, !109, !2363, !4452, !4337, !3809, !4060, !1076, !2102, !2099, !2157, !2238, !1079, !1340, !1083, !1086, !1114, !1120, !1559, !1795, !1853, !1562, !1565, !1583, !1587, !2472, !2519, !2554, !2933, !2558, !2561, !2616, !2620, !2667, !2673, !13, !3351, !3348, !3320, !282, !278, !2984, !4064, !3634, !3637, !3655, !3659, !4468, !3421, !3424, !3474, !3815, !3818, !3821, !3824, !551, !4506, !4545, !4549, !541, !545, !548, !2369, !2422, !2345, !2349, !3535, !3538, !2735, !775, !778, !781, !784, !4660, !4664, !4680, !4683, !4794, !4812, !4829, !4847, !4864}
!3294 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Link_type", scope: !3295, file: !2327, line: 454, baseType: !3296)
!3295 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "_Rb_tree<llvm::StringRef, std::pair<const llvm::StringRef, llvm::StringRef>, std::_Select1st<std::pair<const llvm::StringRef, llvm::StringRef> >, std::less<llvm::StringRef>, std::allocator<std::pair<const llvm::StringRef, llvm::StringRef> > >", scope: !192, file: !2327, line: 444, size: 384, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt8_Rb_treeIN4llvm9StringRefESt4pairIKS1_S1_ESt10_Select1stIS4_ESt4lessIS1_ESaIS4_EE")
!3296 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3297, size: 64)
!3297 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Rb_tree_node<std::pair<const llvm::StringRef, llvm::StringRef> >", scope: !192, file: !2327, line: 216, size: 512, flags: DIFlagTypePassByValue, elements: !3298, templateParams: !3417, identifier: "_ZTSSt13_Rb_tree_nodeISt4pairIKN4llvm9StringRefES2_EE")
!3298 = !{!3299, !3319, !3408, !3412}
!3299 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3297, baseType: !3300, extraData: i32 0)
!3300 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Rb_tree_node_base", scope: !192, file: !2327, line: 101, size: 256, flags: DIFlagTypePassByValue, elements: !3301, identifier: "_ZTSSt18_Rb_tree_node_base")
!3301 = !{!3302, !3303, !3306, !3307, !3308, !3311, !3317, !3318}
!3302 = !DIDerivedType(tag: DW_TAG_member, name: "_M_color", scope: !3300, file: !2327, line: 106, baseType: !2326, size: 32)
!3303 = !DIDerivedType(tag: DW_TAG_member, name: "_M_parent", scope: !3300, file: !2327, line: 107, baseType: !3304, size: 64, offset: 64)
!3304 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Base_ptr", scope: !3300, file: !2327, line: 103, baseType: !3305)
!3305 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3300, size: 64)
!3306 = !DIDerivedType(tag: DW_TAG_member, name: "_M_left", scope: !3300, file: !2327, line: 108, baseType: !3304, size: 64, offset: 128)
!3307 = !DIDerivedType(tag: DW_TAG_member, name: "_M_right", scope: !3300, file: !2327, line: 109, baseType: !3304, size: 64, offset: 192)
!3308 = !DISubprogram(name: "_S_minimum", linkageName: "_ZNSt18_Rb_tree_node_base10_S_minimumEPS_", scope: !3300, file: !2327, line: 112, type: !3309, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3309 = !DISubroutineType(types: !3310)
!3310 = !{!3304, !3304}
!3311 = !DISubprogram(name: "_S_minimum", linkageName: "_ZNSt18_Rb_tree_node_base10_S_minimumEPKS_", scope: !3300, file: !2327, line: 119, type: !3312, scopeLine: 119, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3312 = !DISubroutineType(types: !3313)
!3313 = !{!3314, !3314}
!3314 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Const_Base_ptr", scope: !3300, file: !2327, line: 104, baseType: !3315)
!3315 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3316, size: 64)
!3316 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3300)
!3317 = !DISubprogram(name: "_S_maximum", linkageName: "_ZNSt18_Rb_tree_node_base10_S_maximumEPS_", scope: !3300, file: !2327, line: 126, type: !3309, scopeLine: 126, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3318 = !DISubprogram(name: "_S_maximum", linkageName: "_ZNSt18_Rb_tree_node_base10_S_maximumEPKS_", scope: !3300, file: !2327, line: 133, type: !3312, scopeLine: 133, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3319 = !DIDerivedType(tag: DW_TAG_member, name: "_M_storage", scope: !3297, file: !2327, line: 231, baseType: !3320, size: 256, offset: 256)
!3320 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__aligned_membuf<std::pair<const llvm::StringRef, llvm::StringRef> >", scope: !5, file: !3321, line: 47, size: 256, flags: DIFlagTypePassByValue, elements: !3322, templateParams: !3406, identifier: "_ZTSN9__gnu_cxx16__aligned_membufISt4pairIKN4llvm9StringRefES3_EEE")
!3321 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/aligned_buffer.h", directory: "")
!3322 = !{!3323, !3327, !3331, !3336, !3339, !3344, !3402}
!3323 = !DIDerivedType(tag: DW_TAG_member, name: "_M_storage", scope: !3320, file: !3321, line: 56, baseType: !3324, size: 256, align: 64)
!3324 = !DICompositeType(tag: DW_TAG_array_type, baseType: !423, size: 256, elements: !3325)
!3325 = !{!3326}
!3326 = !DISubrange(count: 32)
!3327 = !DISubprogram(name: "__aligned_membuf", scope: !3320, file: !3321, line: 58, type: !3328, scopeLine: 58, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3328 = !DISubroutineType(types: !3329)
!3329 = !{null, !3330}
!3330 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3320, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3331 = !DISubprogram(name: "__aligned_membuf", scope: !3320, file: !3321, line: 61, type: !3332, scopeLine: 61, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3332 = !DISubroutineType(types: !3333)
!3333 = !{null, !3330, !3334}
!3334 = !DIDerivedType(tag: DW_TAG_typedef, name: "nullptr_t", scope: !192, file: !1153, line: 242, baseType: !3335)
!3335 = !DIBasicType(tag: DW_TAG_unspecified_type, name: "decltype(nullptr)")
!3336 = !DISubprogram(name: "_M_addr", linkageName: "_ZN9__gnu_cxx16__aligned_membufISt4pairIKN4llvm9StringRefES3_EE7_M_addrEv", scope: !3320, file: !3321, line: 64, type: !3337, scopeLine: 64, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3337 = !DISubroutineType(types: !3338)
!3338 = !{!121, !3330}
!3339 = !DISubprogram(name: "_M_addr", linkageName: "_ZNK9__gnu_cxx16__aligned_membufISt4pairIKN4llvm9StringRefES3_EE7_M_addrEv", scope: !3320, file: !3321, line: 68, type: !3340, scopeLine: 68, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3340 = !DISubroutineType(types: !3341)
!3341 = !{!1154, !3342}
!3342 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3343, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3343 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3320)
!3344 = !DISubprogram(name: "_M_ptr", linkageName: "_ZN9__gnu_cxx16__aligned_membufISt4pairIKN4llvm9StringRefES3_EE6_M_ptrEv", scope: !3320, file: !3321, line: 72, type: !3345, scopeLine: 72, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3345 = !DISubroutineType(types: !3346)
!3346 = !{!3347, !3330}
!3347 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3348, size: 64)
!3348 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<const llvm::StringRef, llvm::StringRef>", scope: !192, file: !279, line: 208, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3349, templateParams: !3400, identifier: "_ZTSSt4pairIKN4llvm9StringRefES1_E")
!3349 = !{!3350, !3369, !3370, !3371, !3377, !3381, !3390, !3397}
!3350 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3348, baseType: !3351, flags: DIFlagPrivate, extraData: i32 0)
!3351 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<const llvm::StringRef, llvm::StringRef>", scope: !192, file: !279, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !3352, templateParams: !3367, identifier: "_ZTSSt11__pair_baseIKN4llvm9StringRefES1_E")
!3352 = !{!3353, !3357, !3358, !3363}
!3353 = !DISubprogram(name: "__pair_base", scope: !3351, file: !279, line: 194, type: !3354, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3354 = !DISubroutineType(types: !3355)
!3355 = !{null, !3356}
!3356 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3351, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3357 = !DISubprogram(name: "~__pair_base", scope: !3351, file: !279, line: 195, type: !3354, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3358 = !DISubprogram(name: "__pair_base", scope: !3351, file: !279, line: 196, type: !3359, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3359 = !DISubroutineType(types: !3360)
!3360 = !{null, !3356, !3361}
!3361 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3362, size: 64)
!3362 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3351)
!3363 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIKN4llvm9StringRefES1_EaSERKS3_", scope: !3351, file: !279, line: 197, type: !3364, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!3364 = !DISubroutineType(types: !3365)
!3365 = !{!3366, !3356, !3361}
!3366 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3351, size: 64)
!3367 = !{!3368, !300}
!3368 = !DITemplateTypeParameter(name: "_U1", type: !200)
!3369 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !3348, file: !279, line: 214, baseType: !200, size: 128)
!3370 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !3348, file: !279, line: 215, baseType: !154, size: 128, offset: 128)
!3371 = !DISubprogram(name: "pair", scope: !3348, file: !279, line: 303, type: !3372, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3372 = !DISubroutineType(types: !3373)
!3373 = !{null, !3374, !3375}
!3374 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3348, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3375 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3376, size: 64)
!3376 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3348)
!3377 = !DISubprogram(name: "pair", scope: !3348, file: !279, line: 304, type: !3378, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3378 = !DISubroutineType(types: !3379)
!3379 = !{null, !3374, !3380}
!3380 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3348, size: 64)
!3381 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIKN4llvm9StringRefES1_EaSERKSt20__nonesuch_no_braces", scope: !3348, file: !279, line: 378, type: !3382, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3382 = !DISubroutineType(types: !3383)
!3383 = !{!3384, !3374, !3385}
!3384 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3348, size: 64)
!3385 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !3386, file: !318, line: 1933, baseType: !325)
!3386 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<false, const std::pair<const llvm::StringRef, llvm::StringRef> &, const std::__nonesuch_no_braces &>", scope: !192, file: !318, line: 1932, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !3387, identifier: "_ZTSSt11conditionalILb0ERKSt4pairIKN4llvm9StringRefES2_ERKSt20__nonesuch_no_bracesE")
!3387 = !{!3388, !3389, !324}
!3388 = !DITemplateValueParameter(name: "_Cond", type: !132, value: i8 0)
!3389 = !DITemplateTypeParameter(name: "_Iftrue", type: !3375)
!3390 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIKN4llvm9StringRefES1_EaSEOSt20__nonesuch_no_braces", scope: !3348, file: !279, line: 389, type: !3391, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3391 = !DISubroutineType(types: !3392)
!3392 = !{!3384, !3374, !3393}
!3393 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !3394, file: !318, line: 1933, baseType: !336)
!3394 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<false, std::pair<const llvm::StringRef, llvm::StringRef> &&, std::__nonesuch_no_braces &&>", scope: !192, file: !318, line: 1932, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !3395, identifier: "_ZTSSt11conditionalILb0EOSt4pairIKN4llvm9StringRefES2_EOSt20__nonesuch_no_bracesE")
!3395 = !{!3388, !3396, !335}
!3396 = !DITemplateTypeParameter(name: "_Iftrue", type: !3380)
!3397 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIKN4llvm9StringRefES1_E4swapERS3_", scope: !3348, file: !279, line: 424, type: !3398, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3398 = !DISubroutineType(types: !3399)
!3399 = !{null, !3374, !3384}
!3400 = !{!3401, !342}
!3401 = !DITemplateTypeParameter(name: "_T1", type: !200)
!3402 = !DISubprogram(name: "_M_ptr", linkageName: "_ZNK9__gnu_cxx16__aligned_membufISt4pairIKN4llvm9StringRefES3_EE6_M_ptrEv", scope: !3320, file: !3321, line: 76, type: !3403, scopeLine: 76, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3403 = !DISubroutineType(types: !3404)
!3404 = !{!3405, !3342}
!3405 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3376, size: 64)
!3406 = !{!3407}
!3407 = !DITemplateTypeParameter(name: "_Tp", type: !3348)
!3408 = !DISubprogram(name: "_M_valptr", linkageName: "_ZNSt13_Rb_tree_nodeISt4pairIKN4llvm9StringRefES2_EE9_M_valptrEv", scope: !3297, file: !2327, line: 234, type: !3409, scopeLine: 234, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3409 = !DISubroutineType(types: !3410)
!3410 = !{!3347, !3411}
!3411 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3297, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3412 = !DISubprogram(name: "_M_valptr", linkageName: "_ZNKSt13_Rb_tree_nodeISt4pairIKN4llvm9StringRefES2_EE9_M_valptrEv", scope: !3297, file: !2327, line: 238, type: !3413, scopeLine: 238, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3413 = !DISubroutineType(types: !3414)
!3414 = !{!3405, !3415}
!3415 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3416, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3416 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3297)
!3417 = !{!3418}
!3418 = !DITemplateTypeParameter(name: "_Val", type: !3348)
!3419 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3420, size: 64)
!3420 = !DIDerivedType(tag: DW_TAG_typedef, name: "MapEntryTy", scope: !3421, file: !2346, line: 239, baseType: !2345)
!3421 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringMap<llvm::yaml::Input::HNode *, llvm::MallocAllocator>", scope: !14, file: !2346, line: 236, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3422, templateParams: !3630, identifier: "_ZTSN4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEEE")
!3422 = !{!3423, !3473, !3493, !3497, !3500, !3503, !3506, !3511, !3512, !3521, !3531, !3590, !3591, !3595, !3596, !3599, !3602, !3605, !3608, !3612, !3615, !3616, !3620, !3623, !3626, !3629}
!3423 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3421, baseType: !3424, flags: DIFlagPublic, extraData: i32 0)
!3424 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringMapImpl", scope: !14, file: !2346, line: 53, size: 192, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3425, identifier: "_ZTSN4llvm13StringMapImplE")
!3425 = !{!3426, !3429, !3430, !3431, !3432, !3433, !3437, !3440, !3443, !3446, !3451, !3454, !3457, !3458, !3461, !3464, !3465, !3468, !3469}
!3426 = !DIDerivedType(tag: DW_TAG_member, name: "TheTable", scope: !3424, file: !2346, line: 58, baseType: !3427, size: 64, flags: DIFlagProtected)
!3427 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3428, size: 64)
!3428 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2349, size: 64)
!3429 = !DIDerivedType(tag: DW_TAG_member, name: "NumBuckets", scope: !3424, file: !2346, line: 59, baseType: !6, size: 32, offset: 64, flags: DIFlagProtected)
!3430 = !DIDerivedType(tag: DW_TAG_member, name: "NumItems", scope: !3424, file: !2346, line: 60, baseType: !6, size: 32, offset: 96, flags: DIFlagProtected)
!3431 = !DIDerivedType(tag: DW_TAG_member, name: "NumTombstones", scope: !3424, file: !2346, line: 61, baseType: !6, size: 32, offset: 128, flags: DIFlagProtected)
!3432 = !DIDerivedType(tag: DW_TAG_member, name: "ItemSize", scope: !3424, file: !2346, line: 62, baseType: !6, size: 32, offset: 160, flags: DIFlagProtected)
!3433 = !DISubprogram(name: "StringMapImpl", scope: !3424, file: !2346, line: 64, type: !3434, scopeLine: 64, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3434 = !DISubroutineType(types: !3435)
!3435 = !{null, !3436, !6}
!3436 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3424, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3437 = !DISubprogram(name: "StringMapImpl", scope: !3424, file: !2346, line: 71, type: !3438, scopeLine: 71, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3438 = !DISubroutineType(types: !3439)
!3439 = !{null, !3436, !6, !6}
!3440 = !DISubprogram(name: "RehashTable", linkageName: "_ZN4llvm13StringMapImpl11RehashTableEv", scope: !3424, file: !2346, line: 72, type: !3441, scopeLine: 72, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3441 = !DISubroutineType(types: !3442)
!3442 = !{null, !3436}
!3443 = !DISubprogram(name: "LookupBucketFor", linkageName: "_ZN4llvm13StringMapImpl15LookupBucketForENS_9StringRefE", scope: !3424, file: !2346, line: 79, type: !3444, scopeLine: 79, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3444 = !DISubroutineType(types: !3445)
!3445 = !{!6, !3436, !154}
!3446 = !DISubprogram(name: "FindKey", linkageName: "_ZNK4llvm13StringMapImpl7FindKeyENS_9StringRefE", scope: !3424, file: !2346, line: 84, type: !3447, scopeLine: 84, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3447 = !DISubroutineType(types: !3448)
!3448 = !{!24, !3449, !154}
!3449 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3450, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3450 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3424)
!3451 = !DISubprogram(name: "RemoveKey", linkageName: "_ZN4llvm13StringMapImpl9RemoveKeyEPNS_18StringMapEntryBaseE", scope: !3424, file: !2346, line: 88, type: !3452, scopeLine: 88, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3452 = !DISubroutineType(types: !3453)
!3453 = !{null, !3436, !3428}
!3454 = !DISubprogram(name: "RemoveKey", linkageName: "_ZN4llvm13StringMapImpl9RemoveKeyENS_9StringRefE", scope: !3424, file: !2346, line: 92, type: !3455, scopeLine: 92, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3455 = !DISubroutineType(types: !3456)
!3456 = !{!3428, !3436, !154}
!3457 = !DISubprogram(name: "init", linkageName: "_ZN4llvm13StringMapImpl4initEj", scope: !3424, file: !2346, line: 94, type: !3434, scopeLine: 94, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3458 = !DISubprogram(name: "getTombstoneVal", linkageName: "_ZN4llvm13StringMapImpl15getTombstoneValEv", scope: !3424, file: !2346, line: 96, type: !3459, scopeLine: 96, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3459 = !DISubroutineType(types: !3460)
!3460 = !{!3428}
!3461 = !DISubprogram(name: "getNumBuckets", linkageName: "_ZNK4llvm13StringMapImpl13getNumBucketsEv", scope: !3424, file: !2346, line: 100, type: !3462, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3462 = !DISubroutineType(types: !3463)
!3463 = !{!6, !3449}
!3464 = !DISubprogram(name: "getNumItems", linkageName: "_ZNK4llvm13StringMapImpl11getNumItemsEv", scope: !3424, file: !2346, line: 101, type: !3462, scopeLine: 101, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3465 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm13StringMapImpl5emptyEv", scope: !3424, file: !2346, line: 103, type: !3466, scopeLine: 103, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3466 = !DISubroutineType(types: !3467)
!3467 = !{!132, !3449}
!3468 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm13StringMapImpl4sizeEv", scope: !3424, file: !2346, line: 104, type: !3462, scopeLine: 104, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3469 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm13StringMapImpl4swapERS0_", scope: !3424, file: !2346, line: 106, type: !3470, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3470 = !DISubroutineType(types: !3471)
!3471 = !{null, !3436, !3472}
!3472 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3424, size: 64)
!3473 = !DIDerivedType(tag: DW_TAG_member, name: "Allocator", scope: !3421, file: !2346, line: 237, baseType: !3474, size: 8, offset: 192)
!3474 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MallocAllocator", scope: !14, file: !2517, line: 29, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3475, identifier: "_ZTSN4llvm15MallocAllocatorE")
!3475 = !{!3476, !3480, !3481, !3482, !3485, !3488}
!3476 = !DISubprogram(name: "MallocAllocator", scope: !3474, file: !2517, line: 31, type: !3477, scopeLine: 31, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3477 = !DISubroutineType(types: !3478)
!3478 = !{null, !3479}
!3479 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3474, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3480 = !DISubprogram(name: "~MallocAllocator", scope: !3474, file: !2517, line: 32, type: !3477, scopeLine: 32, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3481 = !DISubprogram(name: "Reset", linkageName: "_ZN4llvm15MallocAllocator5ResetEv", scope: !3474, file: !2517, line: 34, type: !3477, scopeLine: 34, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3482 = !DISubprogram(name: "Allocate", linkageName: "_ZN4llvm15MallocAllocator8AllocateEmm", scope: !3474, file: !2517, line: 36, type: !3483, scopeLine: 36, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3483 = !DISubroutineType(types: !3484)
!3484 = !{!121, !3479, !159, !159}
!3485 = !DISubprogram(name: "Deallocate", linkageName: "_ZN4llvm15MallocAllocator10DeallocateEPKv", scope: !3474, file: !2517, line: 46, type: !3486, scopeLine: 46, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3486 = !DISubroutineType(types: !3487)
!3487 = !{null, !3479, !1154}
!3488 = !DISubprogram(name: "PrintStats", linkageName: "_ZNK4llvm15MallocAllocator10PrintStatsEv", scope: !3474, file: !2517, line: 48, type: !3489, scopeLine: 48, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3489 = !DISubroutineType(types: !3490)
!3490 = !{null, !3491}
!3491 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3492, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3492 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3474)
!3493 = !DISubprogram(name: "StringMap", scope: !3421, file: !2346, line: 241, type: !3494, scopeLine: 241, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3494 = !DISubroutineType(types: !3495)
!3495 = !{null, !3496}
!3496 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3421, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3497 = !DISubprogram(name: "StringMap", scope: !3421, file: !2346, line: 242, type: !3498, scopeLine: 242, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3498 = !DISubroutineType(types: !3499)
!3499 = !{null, !3496, !6}
!3500 = !DISubprogram(name: "StringMap", scope: !3421, file: !2346, line: 245, type: !3501, scopeLine: 245, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3501 = !DISubroutineType(types: !3502)
!3502 = !{null, !3496, !3474}
!3503 = !DISubprogram(name: "StringMap", scope: !3421, file: !2346, line: 248, type: !3504, scopeLine: 248, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3504 = !DISubroutineType(types: !3505)
!3505 = !{null, !3496, !6, !3474}
!3506 = !DISubprogram(name: "StringMap", scope: !3421, file: !2346, line: 252, type: !3507, scopeLine: 252, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3507 = !DISubroutineType(types: !3508)
!3508 = !{null, !3496, !3509}
!3509 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3510, size: 64)
!3510 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3421)
!3511 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEEaSERKS6_", scope: !3421, file: !2346, line: 258, type: !3507, scopeLine: 258, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3512 = !DISubprogram(name: "getAllocator", linkageName: "_ZN4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE12getAllocatorEv", scope: !3421, file: !2346, line: 267, type: !3513, scopeLine: 267, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3513 = !DISubroutineType(types: !3514)
!3514 = !{!3515, !3496}
!3515 = !DIDerivedType(tag: DW_TAG_typedef, name: "AllocatorRefTy", scope: !3421, file: !2346, line: 265, baseType: !3516)
!3516 = !DIDerivedType(tag: DW_TAG_typedef, name: "result", scope: !3517, file: !2517, line: 26, baseType: !3520)
!3517 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ReferenceAdder<llvm::MallocAllocator>", scope: !14, file: !2517, line: 26, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !3518, identifier: "_ZTSN4llvm14ReferenceAdderINS_15MallocAllocatorEEE")
!3518 = !{!3519}
!3519 = !DITemplateTypeParameter(name: "T", type: !3474)
!3520 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3474, size: 64)
!3521 = !DISubprogram(name: "getAllocator", linkageName: "_ZNK4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE12getAllocatorEv", scope: !3421, file: !2346, line: 268, type: !3522, scopeLine: 268, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3522 = !DISubroutineType(types: !3523)
!3523 = !{!3524, !3530}
!3524 = !DIDerivedType(tag: DW_TAG_typedef, name: "AllocatorCRefTy", scope: !3421, file: !2346, line: 266, baseType: !3525)
!3525 = !DIDerivedType(tag: DW_TAG_typedef, name: "result", scope: !3526, file: !2517, line: 26, baseType: !3529)
!3526 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ReferenceAdder<const llvm::MallocAllocator>", scope: !14, file: !2517, line: 26, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !3527, identifier: "_ZTSN4llvm14ReferenceAdderIKNS_15MallocAllocatorEEE")
!3527 = !{!3528}
!3528 = !DITemplateTypeParameter(name: "T", type: !3492)
!3529 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3492, size: 64)
!3530 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3510, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3531 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE5beginEv", scope: !3421, file: !2346, line: 278, type: !3532, scopeLine: 278, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3532 = !DISubroutineType(types: !3533)
!3533 = !{!3534, !3496}
!3534 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3421, file: !2346, line: 276, baseType: !3535)
!3535 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringMapIterator<llvm::yaml::Input::HNode *>", scope: !14, file: !2346, line: 459, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3536, templateParams: !3573, identifier: "_ZTSN4llvm17StringMapIteratorIPNS_4yaml5Input5HNodeEEE")
!3536 = !{!3537, !3575, !3579, !3582, !3587}
!3537 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3535, baseType: !3538, flags: DIFlagPublic, extraData: i32 0)
!3538 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringMapConstIterator<llvm::yaml::Input::HNode *>", scope: !14, file: !2346, line: 414, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3539, templateParams: !3573, identifier: "_ZTSN4llvm22StringMapConstIteratorIPNS_4yaml5Input5HNodeEEE")
!3539 = !{!3540, !3541, !3545, !3548, !3556, !3560, !3564, !3565, !3569, !3572}
!3540 = !DIDerivedType(tag: DW_TAG_member, name: "Ptr", scope: !3538, file: !2346, line: 416, baseType: !3427, size: 64, flags: DIFlagProtected)
!3541 = !DISubprogram(name: "StringMapConstIterator", scope: !3538, file: !2346, line: 420, type: !3542, scopeLine: 420, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3542 = !DISubroutineType(types: !3543)
!3543 = !{null, !3544}
!3544 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3538, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3545 = !DISubprogram(name: "StringMapConstIterator", scope: !3538, file: !2346, line: 422, type: !3546, scopeLine: 422, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3546 = !DISubroutineType(types: !3547)
!3547 = !{null, !3544, !3427, !132}
!3548 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm22StringMapConstIteratorIPNS_4yaml5Input5HNodeEEdeEv", scope: !3538, file: !2346, line: 428, type: !3549, scopeLine: 428, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3549 = !DISubroutineType(types: !3550)
!3550 = !{!3551, !3554}
!3551 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3552, size: 64)
!3552 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3553)
!3553 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !3538, file: !2346, line: 418, baseType: !2345)
!3554 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3555, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3555 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3538)
!3556 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm22StringMapConstIteratorIPNS_4yaml5Input5HNodeEEptEv", scope: !3538, file: !2346, line: 431, type: !3557, scopeLine: 431, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3557 = !DISubroutineType(types: !3558)
!3558 = !{!3559, !3554}
!3559 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3552, size: 64)
!3560 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm22StringMapConstIteratorIPNS_4yaml5Input5HNodeEEeqERKS5_", scope: !3538, file: !2346, line: 435, type: !3561, scopeLine: 435, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3561 = !DISubroutineType(types: !3562)
!3562 = !{!132, !3554, !3563}
!3563 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3555, size: 64)
!3564 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm22StringMapConstIteratorIPNS_4yaml5Input5HNodeEEneERKS5_", scope: !3538, file: !2346, line: 438, type: !3561, scopeLine: 438, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3565 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm22StringMapConstIteratorIPNS_4yaml5Input5HNodeEEppEv", scope: !3538, file: !2346, line: 442, type: !3566, scopeLine: 442, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3566 = !DISubroutineType(types: !3567)
!3567 = !{!3568, !3544}
!3568 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3538, size: 64)
!3569 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm22StringMapConstIteratorIPNS_4yaml5Input5HNodeEEppEi", scope: !3538, file: !2346, line: 447, type: !3570, scopeLine: 447, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3570 = !DISubroutineType(types: !3571)
!3571 = !{!3538, !3544, !24}
!3572 = !DISubprogram(name: "AdvancePastEmptyBuckets", linkageName: "_ZN4llvm22StringMapConstIteratorIPNS_4yaml5Input5HNodeEE23AdvancePastEmptyBucketsEv", scope: !3538, file: !2346, line: 452, type: !3542, scopeLine: 452, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3573 = !{!3574}
!3574 = !DITemplateTypeParameter(name: "ValueT", type: !2362)
!3575 = !DISubprogram(name: "StringMapIterator", scope: !3535, file: !2346, line: 461, type: !3576, scopeLine: 461, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3576 = !DISubroutineType(types: !3577)
!3577 = !{null, !3578}
!3578 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3535, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3579 = !DISubprogram(name: "StringMapIterator", scope: !3535, file: !2346, line: 462, type: !3580, scopeLine: 462, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3580 = !DISubroutineType(types: !3581)
!3581 = !{null, !3578, !3427, !132}
!3582 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm17StringMapIteratorIPNS_4yaml5Input5HNodeEEdeEv", scope: !3535, file: !2346, line: 466, type: !3583, scopeLine: 466, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3583 = !DISubroutineType(types: !3584)
!3584 = !{!3237, !3585}
!3585 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3586, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3586 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3535)
!3587 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm17StringMapIteratorIPNS_4yaml5Input5HNodeEEptEv", scope: !3535, file: !2346, line: 469, type: !3588, scopeLine: 469, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3588 = !DISubroutineType(types: !3589)
!3589 = !{!3268, !3585}
!3590 = !DISubprogram(name: "end", linkageName: "_ZN4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE3endEv", scope: !3421, file: !2346, line: 281, type: !3532, scopeLine: 281, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3591 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE5beginEv", scope: !3421, file: !2346, line: 284, type: !3592, scopeLine: 284, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3592 = !DISubroutineType(types: !3593)
!3593 = !{!3594, !3530}
!3594 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !3421, file: !2346, line: 275, baseType: !3538)
!3595 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE3endEv", scope: !3421, file: !2346, line: 287, type: !3592, scopeLine: 287, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3596 = !DISubprogram(name: "find", linkageName: "_ZN4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE4findENS_9StringRefE", scope: !3421, file: !2346, line: 291, type: !3597, scopeLine: 291, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3597 = !DISubroutineType(types: !3598)
!3598 = !{!3534, !3496, !154}
!3599 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE4findENS_9StringRefE", scope: !3421, file: !2346, line: 297, type: !3600, scopeLine: 297, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3600 = !DISubroutineType(types: !3601)
!3601 = !{!3594, !3530, !154}
!3602 = !DISubprogram(name: "lookup", linkageName: "_ZNK4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE6lookupENS_9StringRefE", scope: !3421, file: !2346, line: 305, type: !3603, scopeLine: 305, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3603 = !DISubroutineType(types: !3604)
!3604 = !{!2362, !3530, !154}
!3605 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEEixENS_9StringRefE", scope: !3421, file: !2346, line: 312, type: !3606, scopeLine: 312, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3606 = !DISubroutineType(types: !3607)
!3607 = !{!3257, !3496, !154}
!3608 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE5countENS_9StringRefE", scope: !3421, file: !2346, line: 316, type: !3609, scopeLine: 316, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3609 = !DISubroutineType(types: !3610)
!3610 = !{!3611, !3530, !154}
!3611 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !3421, file: !2346, line: 273, baseType: !159)
!3612 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE6insertEPNS_14StringMapEntryIS4_EE", scope: !3421, file: !2346, line: 323, type: !3613, scopeLine: 323, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3613 = !DISubroutineType(types: !3614)
!3614 = !{!132, !3496, !3419}
!3615 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE5clearEv", scope: !3421, file: !2346, line: 340, type: !3494, scopeLine: 340, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3616 = !DISubprogram(name: "GetOrCreateValue", linkageName: "_ZN4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE16GetOrCreateValueENS_9StringRefE", scope: !3421, file: !2346, line: 383, type: !3617, scopeLine: 383, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3617 = !DISubroutineType(types: !3618)
!3618 = !{!3619, !3496, !154}
!3619 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3420, size: 64)
!3620 = !DISubprogram(name: "remove", linkageName: "_ZN4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE6removeEPNS_14StringMapEntryIS4_EE", scope: !3421, file: !2346, line: 389, type: !3621, scopeLine: 389, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3621 = !DISubroutineType(types: !3622)
!3622 = !{null, !3496, !3419}
!3623 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE5eraseENS_17StringMapIteratorIS4_EE", scope: !3421, file: !2346, line: 393, type: !3624, scopeLine: 393, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3624 = !DISubroutineType(types: !3625)
!3625 = !{null, !3496, !3534}
!3626 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm9StringMapIPNS_4yaml5Input5HNodeENS_15MallocAllocatorEE5eraseENS_9StringRefE", scope: !3421, file: !2346, line: 399, type: !3627, scopeLine: 399, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3627 = !DISubroutineType(types: !3628)
!3628 = !{!132, !3496, !154}
!3629 = !DISubprogram(name: "~StringMap", scope: !3421, file: !2346, line: 406, type: !3494, scopeLine: 406, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3630 = !{!3283, !3631}
!3631 = !DITemplateTypeParameter(name: "AllocatorTy", type: !3474, defaulted: true)
!3632 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3633, size: 64)
!3633 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Tp_alloc_type", scope: !3634, file: !1080, line: 84, baseType: !3801)
!3634 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_base<llvm::yaml::Input::HNode *, std::allocator<llvm::yaml::Input::HNode *> >", scope: !192, file: !1080, line: 81, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3635, templateParams: !3800, identifier: "_ZTSSt12_Vector_baseIPN4llvm4yaml5Input5HNodeESaIS4_EE")
!3635 = !{!3636, !3754, !3759, !3764, !3768, !3771, !3776, !3779, !3782, !3785, !3789, !3792, !3793, !3796, !3799}
!3636 = !DIDerivedType(tag: DW_TAG_member, name: "_M_impl", scope: !3634, file: !1080, line: 290, baseType: !3637, size: 192)
!3637 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_impl", scope: !3634, file: !1080, line: 88, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3638, identifier: "_ZTSNSt12_Vector_baseIPN4llvm4yaml5Input5HNodeESaIS4_EE12_Vector_implE")
!3638 = !{!3639, !3640, !3735, !3736, !3737, !3741, !3746, !3750}
!3639 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3637, baseType: !3633, extraData: i32 0)
!3640 = !DIDerivedType(tag: DW_TAG_member, name: "_M_start", scope: !3637, file: !1080, line: 91, baseType: !3641, size: 64)
!3641 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3634, file: !1080, line: 86, baseType: !3642)
!3642 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3643, file: !1091, line: 59, baseType: !3651)
!3643 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__alloc_traits<std::allocator<llvm::yaml::Input::HNode *>, llvm::yaml::Input::HNode *>", scope: !5, file: !1091, line: 50, size: 8, flags: DIFlagTypePassByValue, elements: !3644, templateParams: !3733, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIPN4llvm4yaml5Input5HNodeEES5_EE")
!3644 = !{!3645, !3721, !3724, !3728, !3729, !3730, !3731, !3732}
!3645 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3643, baseType: !3646, extraData: i32 0)
!3646 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "allocator_traits<std::allocator<llvm::yaml::Input::HNode *> >", scope: !192, file: !1097, line: 384, size: 8, flags: DIFlagTypePassByValue, elements: !3647, templateParams: !3719, identifier: "_ZTSSt16allocator_traitsISaIPN4llvm4yaml5Input5HNodeEEE")
!3647 = !{!3648, !3704, !3707, !3710, !3716}
!3648 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIPN4llvm4yaml5Input5HNodeEEE8allocateERS5_m", scope: !3646, file: !1097, line: 435, type: !3649, scopeLine: 435, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3649 = !DISubroutineType(types: !3650)
!3650 = !{!3651, !3653, !1174}
!3651 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3646, file: !1097, line: 392, baseType: !3652)
!3652 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2362, size: 64)
!3653 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3654, size: 64)
!3654 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !3646, file: !1097, line: 387, baseType: !3655)
!3655 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "allocator<llvm::yaml::Input::HNode *>", scope: !192, file: !1115, line: 108, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3656, templateParams: !3692, identifier: "_ZTSSaIPN4llvm4yaml5Input5HNodeEE")
!3656 = !{!3657, !3694, !3698, !3703}
!3657 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3655, baseType: !3658, flags: DIFlagPublic, extraData: i32 0)
!3658 = !DIDerivedType(tag: DW_TAG_typedef, name: "__allocator_base<llvm::yaml::Input::HNode *>", scope: !192, file: !1119, line: 48, baseType: !3659)
!3659 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "new_allocator<llvm::yaml::Input::HNode *>", scope: !5, file: !1121, line: 58, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3660, templateParams: !3692, identifier: "_ZTSN9__gnu_cxx13new_allocatorIPN4llvm4yaml5Input5HNodeEEE")
!3660 = !{!3661, !3665, !3670, !3671, !3677, !3683, !3686, !3689}
!3661 = !DISubprogram(name: "new_allocator", scope: !3659, file: !1121, line: 79, type: !3662, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3662 = !DISubroutineType(types: !3663)
!3663 = !{null, !3664}
!3664 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3659, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3665 = !DISubprogram(name: "new_allocator", scope: !3659, file: !1121, line: 81, type: !3666, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3666 = !DISubroutineType(types: !3667)
!3667 = !{null, !3664, !3668}
!3668 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3669, size: 64)
!3669 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3659)
!3670 = !DISubprogram(name: "~new_allocator", scope: !3659, file: !1121, line: 86, type: !3662, scopeLine: 86, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3671 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorIPN4llvm4yaml5Input5HNodeEE7addressERS5_", scope: !3659, file: !1121, line: 89, type: !3672, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3672 = !DISubroutineType(types: !3673)
!3673 = !{!3674, !3675, !3676}
!3674 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3659, file: !1121, line: 63, baseType: !3652)
!3675 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3669, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3676 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3659, file: !1121, line: 65, baseType: !3257)
!3677 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorIPN4llvm4yaml5Input5HNodeEE7addressERKS5_", scope: !3659, file: !1121, line: 93, type: !3678, scopeLine: 93, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3678 = !DISubroutineType(types: !3679)
!3679 = !{!3680, !3675, !3682}
!3680 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !3659, file: !1121, line: 64, baseType: !3681)
!3681 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3245, size: 64)
!3682 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !3659, file: !1121, line: 66, baseType: !3244)
!3683 = !DISubprogram(name: "allocate", linkageName: "_ZN9__gnu_cxx13new_allocatorIPN4llvm4yaml5Input5HNodeEE8allocateEmPKv", scope: !3659, file: !1121, line: 99, type: !3684, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3684 = !DISubroutineType(types: !3685)
!3685 = !{!3674, !3664, !1151, !1154}
!3686 = !DISubprogram(name: "deallocate", linkageName: "_ZN9__gnu_cxx13new_allocatorIPN4llvm4yaml5Input5HNodeEE10deallocateEPS5_m", scope: !3659, file: !1121, line: 116, type: !3687, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3687 = !DISubroutineType(types: !3688)
!3688 = !{null, !3664, !3674, !1151}
!3689 = !DISubprogram(name: "max_size", linkageName: "_ZNK9__gnu_cxx13new_allocatorIPN4llvm4yaml5Input5HNodeEE8max_sizeEv", scope: !3659, file: !1121, line: 129, type: !3690, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3690 = !DISubroutineType(types: !3691)
!3691 = !{!1151, !3675}
!3692 = !{!3693}
!3693 = !DITemplateTypeParameter(name: "_Tp", type: !2362)
!3694 = !DISubprogram(name: "allocator", scope: !3655, file: !1115, line: 131, type: !3695, scopeLine: 131, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3695 = !DISubroutineType(types: !3696)
!3696 = !{null, !3697}
!3697 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3655, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3698 = !DISubprogram(name: "allocator", scope: !3655, file: !1115, line: 133, type: !3699, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3699 = !DISubroutineType(types: !3700)
!3700 = !{null, !3697, !3701}
!3701 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3702, size: 64)
!3702 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3655)
!3703 = !DISubprogram(name: "~allocator", scope: !3655, file: !1115, line: 139, type: !3695, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3704 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIPN4llvm4yaml5Input5HNodeEEE8allocateERS5_mPKv", scope: !3646, file: !1097, line: 449, type: !3705, scopeLine: 449, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3705 = !DISubroutineType(types: !3706)
!3706 = !{!3651, !3653, !1174, !1178}
!3707 = !DISubprogram(name: "deallocate", linkageName: "_ZNSt16allocator_traitsISaIPN4llvm4yaml5Input5HNodeEEE10deallocateERS5_PS4_m", scope: !3646, file: !1097, line: 461, type: !3708, scopeLine: 461, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3708 = !DISubroutineType(types: !3709)
!3709 = !{null, !3653, !3651, !1174}
!3710 = !DISubprogram(name: "max_size", linkageName: "_ZNSt16allocator_traitsISaIPN4llvm4yaml5Input5HNodeEEE8max_sizeERKS5_", scope: !3646, file: !1097, line: 495, type: !3711, scopeLine: 495, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3711 = !DISubroutineType(types: !3712)
!3712 = !{!3713, !3714}
!3713 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !3646, file: !1097, line: 407, baseType: !1152)
!3714 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3715, size: 64)
!3715 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3654)
!3716 = !DISubprogram(name: "select_on_container_copy_construction", linkageName: "_ZNSt16allocator_traitsISaIPN4llvm4yaml5Input5HNodeEEE37select_on_container_copy_constructionERKS5_", scope: !3646, file: !1097, line: 504, type: !3717, scopeLine: 504, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3717 = !DISubroutineType(types: !3718)
!3718 = !{!3654, !3714}
!3719 = !{!3720}
!3720 = !DITemplateTypeParameter(name: "_Alloc", type: !3655)
!3721 = !DISubprogram(name: "_S_select_on_copy", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPN4llvm4yaml5Input5HNodeEES5_E17_S_select_on_copyERKS6_", scope: !3643, file: !1091, line: 94, type: !3722, scopeLine: 94, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3722 = !DISubroutineType(types: !3723)
!3723 = !{!3655, !3701}
!3724 = !DISubprogram(name: "_S_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPN4llvm4yaml5Input5HNodeEES5_E10_S_on_swapERS6_S8_", scope: !3643, file: !1091, line: 97, type: !3725, scopeLine: 97, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3725 = !DISubroutineType(types: !3726)
!3726 = !{null, !3727, !3727}
!3727 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3655, size: 64)
!3728 = !DISubprogram(name: "_S_propagate_on_copy_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPN4llvm4yaml5Input5HNodeEES5_E27_S_propagate_on_copy_assignEv", scope: !3643, file: !1091, line: 100, type: !1201, scopeLine: 100, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3729 = !DISubprogram(name: "_S_propagate_on_move_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPN4llvm4yaml5Input5HNodeEES5_E27_S_propagate_on_move_assignEv", scope: !3643, file: !1091, line: 103, type: !1201, scopeLine: 103, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3730 = !DISubprogram(name: "_S_propagate_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPN4llvm4yaml5Input5HNodeEES5_E20_S_propagate_on_swapEv", scope: !3643, file: !1091, line: 106, type: !1201, scopeLine: 106, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3731 = !DISubprogram(name: "_S_always_equal", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPN4llvm4yaml5Input5HNodeEES5_E15_S_always_equalEv", scope: !3643, file: !1091, line: 109, type: !1201, scopeLine: 109, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3732 = !DISubprogram(name: "_S_nothrow_move", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPN4llvm4yaml5Input5HNodeEES5_E15_S_nothrow_moveEv", scope: !3643, file: !1091, line: 112, type: !1201, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3733 = !{!3720, !3734}
!3734 = !DITemplateTypeParameter(type: !2362)
!3735 = !DIDerivedType(tag: DW_TAG_member, name: "_M_finish", scope: !3637, file: !1080, line: 92, baseType: !3641, size: 64, offset: 64)
!3736 = !DIDerivedType(tag: DW_TAG_member, name: "_M_end_of_storage", scope: !3637, file: !1080, line: 93, baseType: !3641, size: 64, offset: 128)
!3737 = !DISubprogram(name: "_Vector_impl", scope: !3637, file: !1080, line: 95, type: !3738, scopeLine: 95, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3738 = !DISubroutineType(types: !3739)
!3739 = !{null, !3740}
!3740 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3637, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3741 = !DISubprogram(name: "_Vector_impl", scope: !3637, file: !1080, line: 99, type: !3742, scopeLine: 99, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3742 = !DISubroutineType(types: !3743)
!3743 = !{null, !3740, !3744}
!3744 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3745, size: 64)
!3745 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3633)
!3746 = !DISubprogram(name: "_Vector_impl", scope: !3637, file: !1080, line: 104, type: !3747, scopeLine: 104, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3747 = !DISubroutineType(types: !3748)
!3748 = !{null, !3740, !3749}
!3749 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3633, size: 64)
!3750 = !DISubprogram(name: "_M_swap_data", linkageName: "_ZNSt12_Vector_baseIPN4llvm4yaml5Input5HNodeESaIS4_EE12_Vector_impl12_M_swap_dataERS7_", scope: !3637, file: !1080, line: 110, type: !3751, scopeLine: 110, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3751 = !DISubroutineType(types: !3752)
!3752 = !{null, !3740, !3753}
!3753 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3637, size: 64)
!3754 = !DISubprogram(name: "_M_get_Tp_allocator", linkageName: "_ZNSt12_Vector_baseIPN4llvm4yaml5Input5HNodeESaIS4_EE19_M_get_Tp_allocatorEv", scope: !3634, file: !1080, line: 237, type: !3755, scopeLine: 237, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3755 = !DISubroutineType(types: !3756)
!3756 = !{!3757, !3758}
!3757 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3633, size: 64)
!3758 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3634, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3759 = !DISubprogram(name: "_M_get_Tp_allocator", linkageName: "_ZNKSt12_Vector_baseIPN4llvm4yaml5Input5HNodeESaIS4_EE19_M_get_Tp_allocatorEv", scope: !3634, file: !1080, line: 241, type: !3760, scopeLine: 241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3760 = !DISubroutineType(types: !3761)
!3761 = !{!3744, !3762}
!3762 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3763, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3763 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3634)
!3764 = !DISubprogram(name: "get_allocator", linkageName: "_ZNKSt12_Vector_baseIPN4llvm4yaml5Input5HNodeESaIS4_EE13get_allocatorEv", scope: !3634, file: !1080, line: 245, type: !3765, scopeLine: 245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3765 = !DISubroutineType(types: !3766)
!3766 = !{!3767, !3762}
!3767 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !3634, file: !1080, line: 234, baseType: !3655)
!3768 = !DISubprogram(name: "_Vector_base", scope: !3634, file: !1080, line: 248, type: !3769, scopeLine: 248, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3769 = !DISubroutineType(types: !3770)
!3770 = !{null, !3758}
!3771 = !DISubprogram(name: "_Vector_base", scope: !3634, file: !1080, line: 251, type: !3772, scopeLine: 251, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3772 = !DISubroutineType(types: !3773)
!3773 = !{null, !3758, !3774}
!3774 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3775, size: 64)
!3775 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3767)
!3776 = !DISubprogram(name: "_Vector_base", scope: !3634, file: !1080, line: 254, type: !3777, scopeLine: 254, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3777 = !DISubroutineType(types: !3778)
!3778 = !{null, !3758, !1152}
!3779 = !DISubprogram(name: "_Vector_base", scope: !3634, file: !1080, line: 258, type: !3780, scopeLine: 258, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3780 = !DISubroutineType(types: !3781)
!3781 = !{null, !3758, !1152, !3774}
!3782 = !DISubprogram(name: "_Vector_base", scope: !3634, file: !1080, line: 263, type: !3783, scopeLine: 263, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3783 = !DISubroutineType(types: !3784)
!3784 = !{null, !3758, !3749}
!3785 = !DISubprogram(name: "_Vector_base", scope: !3634, file: !1080, line: 266, type: !3786, scopeLine: 266, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3786 = !DISubroutineType(types: !3787)
!3787 = !{null, !3758, !3788}
!3788 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3634, size: 64)
!3789 = !DISubprogram(name: "_Vector_base", scope: !3634, file: !1080, line: 270, type: !3790, scopeLine: 270, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3790 = !DISubroutineType(types: !3791)
!3791 = !{null, !3758, !3788, !3774}
!3792 = !DISubprogram(name: "~_Vector_base", scope: !3634, file: !1080, line: 283, type: !3769, scopeLine: 283, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3793 = !DISubprogram(name: "_M_allocate", linkageName: "_ZNSt12_Vector_baseIPN4llvm4yaml5Input5HNodeESaIS4_EE11_M_allocateEm", scope: !3634, file: !1080, line: 293, type: !3794, scopeLine: 293, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3794 = !DISubroutineType(types: !3795)
!3795 = !{!3641, !3758, !1152}
!3796 = !DISubprogram(name: "_M_deallocate", linkageName: "_ZNSt12_Vector_baseIPN4llvm4yaml5Input5HNodeESaIS4_EE13_M_deallocateEPS4_m", scope: !3634, file: !1080, line: 300, type: !3797, scopeLine: 300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3797 = !DISubroutineType(types: !3798)
!3798 = !{null, !3758, !3641, !1152}
!3799 = !DISubprogram(name: "_M_create_storage", linkageName: "_ZNSt12_Vector_baseIPN4llvm4yaml5Input5HNodeESaIS4_EE17_M_create_storageEm", scope: !3634, file: !1080, line: 309, type: !3777, scopeLine: 309, flags: DIFlagPrivate | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3800 = !{!3693, !3720}
!3801 = !DIDerivedType(tag: DW_TAG_typedef, name: "other", scope: !3802, file: !1091, line: 117, baseType: !3803)
!3802 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "rebind<llvm::yaml::Input::HNode *>", scope: !3643, file: !1091, line: 116, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !3692, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIPN4llvm4yaml5Input5HNodeEES5_E6rebindIS5_EE")
!3803 = !DIDerivedType(tag: DW_TAG_typedef, name: "rebind_alloc<llvm::yaml::Input::HNode *>", scope: !3646, file: !1097, line: 422, baseType: !3655)
!3804 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !3806, file: !3805, line: 185, baseType: !4049)
!3805 = !DIFile(filename: "llvm34/include/llvm/Support/Casting.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "d66d299dea704124ccd357043ea0e9d5")
!3806 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty<llvm::yaml::Input::MapHNode, llvm::yaml::Input::HNode *>", scope: !14, file: !3805, line: 183, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !3807, identifier: "_ZTSN4llvm10cast_rettyINS_4yaml5Input8MapHNodeEPNS2_5HNodeEEE")
!3807 = !{!3808, !4048}
!3808 = !DITemplateTypeParameter(name: "To", type: !3809)
!3809 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MapHNode", scope: !2364, file: !108, line: 762, size: 960, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3810, vtableHolder: !2363)
!3810 = !{!3811, !3812, !3814, !4032, !4036, !4039, !4040, !4045}
!3811 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3809, baseType: !2363, flags: DIFlagPublic, extraData: i32 0)
!3812 = !DIDerivedType(tag: DW_TAG_member, name: "Mapping", scope: !3809, file: !108, line: 776, baseType: !3813, size: 256, offset: 128, flags: DIFlagPublic)
!3813 = !DIDerivedType(tag: DW_TAG_typedef, name: "NameToNode", scope: !3809, file: !108, line: 772, baseType: !3421)
!3814 = !DIDerivedType(tag: DW_TAG_member, name: "ValidKeys", scope: !3809, file: !108, line: 777, baseType: !3815, size: 576, offset: 384, flags: DIFlagPublic)
!3815 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<const char *, 6U>", scope: !14, file: !542, line: 880, size: 576, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3816, templateParams: !4008, identifier: "_ZTSN4llvm11SmallVectorIPKcLj6EEE")
!3816 = !{!3817, !4001, !4010, !4014, !4017, !4022, !4025, !4029}
!3817 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3815, baseType: !3818, flags: DIFlagPublic, extraData: i32 0)
!3818 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<const char *>", scope: !14, file: !542, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3819, templateParams: !4000, identifier: "_ZTSN4llvm15SmallVectorImplIPKcEE")
!3819 = !{!3820, !3938, !3944, !3947, !3950, !3951, !3952, !3955, !3956, !3959, !3963, !3968, !3969, !3973, !3976, !3980, !3983, !3986, !3989, !3993, !3997, !3998, !3999}
!3820 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3818, baseType: !3821, flags: DIFlagPublic, extraData: i32 0)
!3821 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<const char *, true>", scope: !14, file: !542, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3822, templateParams: !3937, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseIPKcLb1EEE")
!3822 = !{!3823, !3923, !3927, !3930, !3931, !3934}
!3823 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3821, baseType: !3824, flags: DIFlagPublic, extraData: i32 0)
!3824 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<const char *, void>", scope: !14, file: !542, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3825, templateParams: !3921, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIPKcvEE")
!3825 = !{!3826, !3827, !3843, !3847, !3850, !3855, !3858, !3862, !3866, !3872, !3873, !3874, !3875, !3876, !3881, !3886, !3887, !3888, !3891, !3892, !3895, !3899, !3903, !3908, !3913, !3916, !3919, !3920}
!3826 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3824, baseType: !551, flags: DIFlagPublic, extraData: i32 0)
!3827 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !3824, file: !542, line: 74, baseType: !3828, size: 64, offset: 192)
!3828 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !3824, file: !542, line: 73, baseType: !3829)
!3829 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<const char *, char, char, char, char, char, char>", scope: !14, file: !575, line: 199, size: 64, flags: DIFlagTypePassByValue, elements: !3830, templateParams: !3841, identifier: "_ZTSN4llvm21AlignedCharArrayUnionIPKcccccccEE")
!3830 = !{!3831}
!3831 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3829, baseType: !3832, extraData: i32 0)
!3832 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<8UL, 8UL>", scope: !14, file: !575, line: 75, size: 64, flags: DIFlagTypePassByValue, elements: !3833, templateParams: !3838, identifier: "_ZTSN4llvm16AlignedCharArrayILm8ELm8EEE")
!3833 = !{!3834}
!3834 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !3832, file: !575, line: 76, baseType: !3835, size: 64, align: 64)
!3835 = !DICompositeType(tag: DW_TAG_array_type, baseType: !165, size: 64, elements: !3836)
!3836 = !{!3837}
!3837 = !DISubrange(count: 8)
!3838 = !{!3839, !3840}
!3839 = !DITemplateValueParameter(name: "Alignment", type: !161, value: i64 8)
!3840 = !DITemplateValueParameter(name: "Size", type: !161, value: i64 8)
!3841 = !{!3842, !589, !590, !591, !592, !593, !594}
!3842 = !DITemplateTypeParameter(name: "T1", type: !163)
!3843 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !3824, file: !542, line: 78, type: !3844, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3844 = !DISubroutineType(types: !3845)
!3845 = !{null, !3846, !159}
!3846 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3824, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3847 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKcvE8grow_podEmm", scope: !3824, file: !542, line: 80, type: !3848, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3848 = !DISubroutineType(types: !3849)
!3849 = !{null, !3846, !159, !159}
!3850 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKcvE7isSmallEv", scope: !3824, file: !542, line: 86, type: !3851, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3851 = !DISubroutineType(types: !3852)
!3852 = !{!132, !3853}
!3853 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3854, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3854 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3824)
!3855 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKcvE12resetToSmallEv", scope: !3824, file: !542, line: 91, type: !3856, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3856 = !DISubroutineType(types: !3857)
!3857 = !{null, !3846}
!3858 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKcvE6setEndEPS2_", scope: !3824, file: !542, line: 95, type: !3859, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3859 = !DISubroutineType(types: !3860)
!3860 = !{null, !3846, !3861}
!3861 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !163, size: 64)
!3862 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKcvE5beginEv", scope: !3824, file: !542, line: 112, type: !3863, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3863 = !DISubroutineType(types: !3864)
!3864 = !{!3865, !3846}
!3865 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3824, file: !542, line: 100, baseType: !3861)
!3866 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKcvE5beginEv", scope: !3824, file: !542, line: 113, type: !3867, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3867 = !DISubroutineType(types: !3868)
!3868 = !{!3869, !3853}
!3869 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !3824, file: !542, line: 101, baseType: !3870)
!3870 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3871, size: 64)
!3871 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !163)
!3872 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKcvE3endEv", scope: !3824, file: !542, line: 114, type: !3863, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3873 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKcvE3endEv", scope: !3824, file: !542, line: 115, type: !3867, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3874 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKcvE12capacity_ptrEv", scope: !3824, file: !542, line: 117, type: !3863, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3875 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKcvE12capacity_ptrEv", scope: !3824, file: !542, line: 118, type: !3867, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3876 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKcvE6rbeginEv", scope: !3824, file: !542, line: 122, type: !3877, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3877 = !DISubroutineType(types: !3878)
!3878 = !{!3879, !3846}
!3879 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !3824, file: !542, line: 104, baseType: !3880)
!3880 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const char **>", scope: !192, file: !631, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPPKcE")
!3881 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKcvE6rbeginEv", scope: !3824, file: !542, line: 123, type: !3882, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3882 = !DISubroutineType(types: !3883)
!3883 = !{!3884, !3853}
!3884 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !3824, file: !542, line: 103, baseType: !3885)
!3885 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const char *const *>", scope: !192, file: !631, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKPKcE")
!3886 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKcvE4rendEv", scope: !3824, file: !542, line: 124, type: !3877, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3887 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKcvE4rendEv", scope: !3824, file: !542, line: 125, type: !3882, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3888 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKcvE4sizeEv", scope: !3824, file: !542, line: 127, type: !3889, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3889 = !DISubroutineType(types: !3890)
!3890 = !{!642, !3853}
!3891 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKcvE8max_sizeEv", scope: !3824, file: !542, line: 128, type: !3889, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3892 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKcvE8capacityEv", scope: !3824, file: !542, line: 132, type: !3893, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3893 = !DISubroutineType(types: !3894)
!3894 = !{!159, !3853}
!3895 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKcvE4dataEv", scope: !3824, file: !542, line: 135, type: !3896, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3896 = !DISubroutineType(types: !3897)
!3897 = !{!3898, !3846}
!3898 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3824, file: !542, line: 108, baseType: !3861)
!3899 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKcvE4dataEv", scope: !3824, file: !542, line: 137, type: !3900, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3900 = !DISubroutineType(types: !3901)
!3901 = !{!3902, !3853}
!3902 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !3824, file: !542, line: 109, baseType: !3870)
!3903 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKcvEixEj", scope: !3824, file: !542, line: 139, type: !3904, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3904 = !DISubroutineType(types: !3905)
!3905 = !{!3906, !3846, !6}
!3906 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3824, file: !542, line: 106, baseType: !3907)
!3907 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !163, size: 64)
!3908 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKcvEixEj", scope: !3824, file: !542, line: 143, type: !3909, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3909 = !DISubroutineType(types: !3910)
!3910 = !{!3911, !3853, !6}
!3911 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !3824, file: !542, line: 107, baseType: !3912)
!3912 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3871, size: 64)
!3913 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKcvE5frontEv", scope: !3824, file: !542, line: 148, type: !3914, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3914 = !DISubroutineType(types: !3915)
!3915 = !{!3906, !3846}
!3916 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKcvE5frontEv", scope: !3824, file: !542, line: 152, type: !3917, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3917 = !DISubroutineType(types: !3918)
!3918 = !{!3911, !3853}
!3919 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKcvE4backEv", scope: !3824, file: !542, line: 157, type: !3914, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3920 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKcvE4backEv", scope: !3824, file: !542, line: 161, type: !3917, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3921 = !{!3922, !675}
!3922 = !DITemplateTypeParameter(name: "T", type: !163)
!3923 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !3821, file: !542, line: 298, type: !3924, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3924 = !DISubroutineType(types: !3925)
!3925 = !{null, !3926, !159}
!3926 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3821, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3927 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPKcLb1EE13destroy_rangeEPS2_S4_", scope: !3821, file: !542, line: 301, type: !3928, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3928 = !DISubroutineType(types: !3929)
!3929 = !{null, !3861, !3861}
!3930 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPKcLb1EE4growEm", scope: !3821, file: !542, line: 346, type: !3924, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3931 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPKcLb1EE9push_backERKS2_", scope: !3821, file: !542, line: 350, type: !3932, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3932 = !DISubroutineType(types: !3933)
!3933 = !{null, !3926, !3912}
!3934 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPKcLb1EE8pop_backEv", scope: !3821, file: !542, line: 361, type: !3935, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3935 = !DISubroutineType(types: !3936)
!3936 = !{null, !3926}
!3937 = !{!3922, !691}
!3938 = !DISubprogram(name: "SmallVectorImpl", scope: !3818, file: !542, line: 374, type: !3939, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!3939 = !DISubroutineType(types: !3940)
!3940 = !{null, !3941, !3942}
!3941 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3818, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3942 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3943, size: 64)
!3943 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3818)
!3944 = !DISubprogram(name: "SmallVectorImpl", scope: !3818, file: !542, line: 381, type: !3945, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3945 = !DISubroutineType(types: !3946)
!3946 = !{null, !3941, !6}
!3947 = !DISubprogram(name: "~SmallVectorImpl", scope: !3818, file: !542, line: 386, type: !3948, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3948 = !DISubroutineType(types: !3949)
!3949 = !{null, !3941}
!3950 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplIPKcE5clearEv", scope: !3818, file: !542, line: 396, type: !3948, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3951 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIPKcE6resizeEj", scope: !3818, file: !542, line: 401, type: !3945, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3952 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIPKcE6resizeEjRKS2_", scope: !3818, file: !542, line: 413, type: !3953, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3953 = !DISubroutineType(types: !3954)
!3954 = !{null, !3941, !6, !3912}
!3955 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplIPKcE7reserveEj", scope: !3818, file: !542, line: 425, type: !3945, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3956 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplIPKcE12pop_back_valEv", scope: !3818, file: !542, line: 430, type: !3957, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3957 = !DISubroutineType(types: !3958)
!3958 = !{!163, !3941}
!3959 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplIPKcE4swapERS3_", scope: !3818, file: !542, line: 440, type: !3960, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3960 = !DISubroutineType(types: !3961)
!3961 = !{null, !3941, !3962}
!3962 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3818, size: 64)
!3963 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplIPKcE6appendEmRKS2_", scope: !3818, file: !542, line: 460, type: !3964, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3964 = !DISubroutineType(types: !3965)
!3965 = !{null, !3941, !3966, !3912}
!3966 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !3818, file: !542, line: 377, baseType: !3967)
!3967 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !3824, file: !542, line: 97, baseType: !159)
!3968 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplIPKcE6assignEjRKS2_", scope: !3818, file: !542, line: 470, type: !3953, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3969 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIPKcE5eraseEPS2_", scope: !3818, file: !542, line: 478, type: !3970, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3970 = !DISubroutineType(types: !3971)
!3971 = !{!3972, !3941, !3972}
!3972 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3818, file: !542, line: 376, baseType: !3865)
!3973 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIPKcE5eraseEPS2_S4_", scope: !3818, file: !542, line: 490, type: !3974, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3974 = !DISubroutineType(types: !3975)
!3975 = !{!3972, !3941, !3972, !3972}
!3976 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPKcE6insertEPS2_OS2_", scope: !3818, file: !542, line: 505, type: !3977, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3977 = !DISubroutineType(types: !3978)
!3978 = !{!3972, !3941, !3972, !3979}
!3979 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !163, size: 64)
!3980 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPKcE6insertEPS2_RKS2_", scope: !3818, file: !542, line: 537, type: !3981, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3981 = !DISubroutineType(types: !3982)
!3982 = !{!3972, !3941, !3972, !3912}
!3983 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPKcE6insertEPS2_mRKS2_", scope: !3818, file: !542, line: 568, type: !3984, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3984 = !DISubroutineType(types: !3985)
!3985 = !{!3972, !3941, !3972, !3966, !3912}
!3986 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIPKcEaSERKS3_", scope: !3818, file: !542, line: 674, type: !3987, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3987 = !DISubroutineType(types: !3988)
!3988 = !{!3962, !3941, !3942}
!3989 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIPKcEaSEOS3_", scope: !3818, file: !542, line: 677, type: !3990, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3990 = !DISubroutineType(types: !3991)
!3991 = !{!3962, !3941, !3992}
!3992 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3818, size: 64)
!3993 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplIPKcEeqERKS3_", scope: !3818, file: !542, line: 680, type: !3994, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3994 = !DISubroutineType(types: !3995)
!3995 = !{!132, !3996, !3942}
!3996 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3943, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3997 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplIPKcEneERKS3_", scope: !3818, file: !542, line: 684, type: !3994, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3998 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplIPKcEltERKS3_", scope: !3818, file: !542, line: 688, type: !3994, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3999 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplIPKcE8set_sizeEj", scope: !3818, file: !542, line: 702, type: !3945, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4000 = !{!3922}
!4001 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !3815, file: !542, line: 882, baseType: !4002, size: 320, offset: 256)
!4002 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<const char *, 6U>", scope: !14, file: !542, line: 865, size: 320, flags: DIFlagTypePassByValue, elements: !4003, templateParams: !4008, identifier: "_ZTSN4llvm18SmallVectorStorageIPKcLj6EEE")
!4003 = !{!4004}
!4004 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !4002, file: !542, line: 866, baseType: !4005, size: 320)
!4005 = !DICompositeType(tag: DW_TAG_array_type, baseType: !3828, size: 320, elements: !4006)
!4006 = !{!4007}
!4007 = !DISubrange(count: 5)
!4008 = !{!3922, !4009}
!4009 = !DITemplateValueParameter(name: "N", type: !6, value: i32 6)
!4010 = !DISubprogram(name: "SmallVector", scope: !3815, file: !542, line: 884, type: !4011, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4011 = !DISubroutineType(types: !4012)
!4012 = !{null, !4013}
!4013 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3815, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4014 = !DISubprogram(name: "SmallVector", scope: !3815, file: !542, line: 887, type: !4015, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4015 = !DISubroutineType(types: !4016)
!4016 = !{null, !4013, !6, !3912}
!4017 = !DISubprogram(name: "SmallVector", scope: !3815, file: !542, line: 897, type: !4018, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4018 = !DISubroutineType(types: !4019)
!4019 = !{null, !4013, !4020}
!4020 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4021, size: 64)
!4021 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3815)
!4022 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIPKcLj6EEaSERKS3_", scope: !3815, file: !542, line: 902, type: !4023, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4023 = !DISubroutineType(types: !4024)
!4024 = !{!4020, !4013, !4020}
!4025 = !DISubprogram(name: "SmallVector", scope: !3815, file: !542, line: 908, type: !4026, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4026 = !DISubroutineType(types: !4027)
!4027 = !{null, !4013, !4028}
!4028 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3815, size: 64)
!4029 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIPKcLj6EEaSEOS3_", scope: !3815, file: !542, line: 913, type: !4030, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4030 = !DISubroutineType(types: !4031)
!4031 = !{!4020, !4013, !4028}
!4032 = !DISubprogram(name: "MapHNode", scope: !3809, file: !108, line: 764, type: !4033, scopeLine: 764, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4033 = !DISubroutineType(types: !4034)
!4034 = !{null, !4035, !3208}
!4035 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3809, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4036 = !DISubprogram(name: "~MapHNode", scope: !3809, file: !108, line: 765, type: !4037, scopeLine: 765, containingType: !3809, virtualIndex: 0, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!4037 = !DISubroutineType(types: !4038)
!4038 = !{null, !4035}
!4039 = !DISubprogram(name: "classof", linkageName: "_ZN4llvm4yaml5Input8MapHNode7classofEPKNS1_5HNodeE", scope: !3809, file: !108, line: 767, type: !3229, scopeLine: 767, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4040 = !DISubprogram(name: "classof", linkageName: "_ZN4llvm4yaml5Input8MapHNode7classofEPKS2_", scope: !3809, file: !108, line: 770, type: !4041, scopeLine: 770, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4041 = !DISubroutineType(types: !4042)
!4042 = !{!132, !4043}
!4043 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4044, size: 64)
!4044 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3809)
!4045 = !DISubprogram(name: "isValidKey", linkageName: "_ZN4llvm4yaml5Input8MapHNode10isValidKeyENS_9StringRefE", scope: !3809, file: !108, line: 774, type: !4046, scopeLine: 774, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4046 = !DISubroutineType(types: !4047)
!4047 = !{!132, !4035, !154}
!4048 = !DITemplateTypeParameter(name: "From", type: !2362)
!4049 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4050, file: !3805, line: 179, baseType: !4053)
!4050 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_wrap<llvm::yaml::Input::MapHNode, llvm::yaml::Input::HNode *, llvm::yaml::Input::HNode *>", scope: !14, file: !3805, line: 177, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4051, identifier: "_ZTSN4llvm15cast_retty_wrapINS_4yaml5Input8MapHNodeEPNS2_5HNodeES5_EE")
!4051 = !{!3808, !4048, !4052}
!4052 = !DITemplateTypeParameter(name: "SimpleFrom", type: !2362)
!4053 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4054, file: !3805, line: 156, baseType: !4055)
!4054 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_impl<llvm::yaml::Input::MapHNode, llvm::yaml::Input::HNode *>", scope: !14, file: !3805, line: 155, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !3807, identifier: "_ZTSN4llvm15cast_retty_implINS_4yaml5Input8MapHNodeEPNS2_5HNodeEEE")
!4055 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3809, size: 64)
!4056 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4057, file: !3805, line: 185, baseType: !4327)
!4057 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty<llvm::yaml::Input::SequenceHNode, llvm::yaml::Input::HNode *>", scope: !14, file: !3805, line: 183, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4058, identifier: "_ZTSN4llvm10cast_rettyINS_4yaml5Input13SequenceHNodeEPNS2_5HNodeEEE")
!4058 = !{!4059, !4048}
!4059 = !DITemplateTypeParameter(name: "To", type: !4060)
!4060 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SequenceHNode", scope: !2364, file: !108, line: 780, size: 320, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4061, vtableHolder: !2363)
!4061 = !{!4062, !4063, !4314, !4318, !4321, !4322}
!4062 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4060, baseType: !2363, flags: DIFlagPublic, extraData: i32 0)
!4063 = !DIDerivedType(tag: DW_TAG_member, name: "Entries", scope: !4060, file: !108, line: 790, baseType: !4064, size: 192, offset: 128, flags: DIFlagPublic)
!4064 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<llvm::yaml::Input::HNode *, std::allocator<llvm::yaml::Input::HNode *> >", scope: !192, file: !1080, line: 339, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4065, templateParams: !3800, identifier: "_ZTSSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE")
!4065 = !{!4066, !4067, !4071, !4077, !4080, !4086, !4091, !4095, !4098, !4101, !4105, !4106, !4110, !4113, !4116, !4119, !4122, !4180, !4186, !4187, !4188, !4193, !4198, !4199, !4200, !4201, !4202, !4203, !4204, !4207, !4208, !4211, !4212, !4213, !4214, !4217, !4218, !4226, !4233, !4236, !4237, !4238, !4241, !4244, !4245, !4246, !4249, !4252, !4255, !4259, !4260, !4263, !4266, !4269, !4272, !4275, !4278, !4281, !4282, !4283, !4284, !4285, !4288, !4289, !4292, !4293, !4294, !4298, !4302, !4305, !4308, !4311}
!4066 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4064, baseType: !3634, flags: DIFlagProtected, extraData: i32 0)
!4067 = !DISubprogram(name: "vector", scope: !4064, file: !1080, line: 391, type: !4068, scopeLine: 391, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4068 = !DISubroutineType(types: !4069)
!4069 = !{null, !4070}
!4070 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4064, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4071 = !DISubprogram(name: "vector", scope: !4064, file: !1080, line: 402, type: !4072, scopeLine: 402, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4072 = !DISubroutineType(types: !4073)
!4073 = !{null, !4070, !4074}
!4074 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4075, size: 64)
!4075 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4076)
!4076 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !4064, file: !1080, line: 376, baseType: !3655)
!4077 = !DISubprogram(name: "vector", scope: !4064, file: !1080, line: 415, type: !4078, scopeLine: 415, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4078 = !DISubroutineType(types: !4079)
!4079 = !{null, !4070, !1292, !4074}
!4080 = !DISubprogram(name: "vector", scope: !4064, file: !1080, line: 427, type: !4081, scopeLine: 427, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4081 = !DISubroutineType(types: !4082)
!4082 = !{null, !4070, !1292, !4083, !4074}
!4083 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4084, size: 64)
!4084 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4085)
!4085 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !4064, file: !1080, line: 364, baseType: !2362)
!4086 = !DISubprogram(name: "vector", scope: !4064, file: !1080, line: 458, type: !4087, scopeLine: 458, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4087 = !DISubroutineType(types: !4088)
!4088 = !{null, !4070, !4089}
!4089 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4090, size: 64)
!4090 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4064)
!4091 = !DISubprogram(name: "vector", scope: !4064, file: !1080, line: 476, type: !4092, scopeLine: 476, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4092 = !DISubroutineType(types: !4093)
!4093 = !{null, !4070, !4094}
!4094 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !4064, size: 64)
!4095 = !DISubprogram(name: "vector", scope: !4064, file: !1080, line: 480, type: !4096, scopeLine: 480, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4096 = !DISubroutineType(types: !4097)
!4097 = !{null, !4070, !4089, !4074}
!4098 = !DISubprogram(name: "vector", scope: !4064, file: !1080, line: 490, type: !4099, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4099 = !DISubroutineType(types: !4100)
!4100 = !{null, !4070, !4094, !4074}
!4101 = !DISubprogram(name: "vector", scope: !4064, file: !1080, line: 515, type: !4102, scopeLine: 515, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4102 = !DISubroutineType(types: !4103)
!4103 = !{null, !4070, !4104, !4074}
!4104 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<llvm::yaml::Input::HNode *>", scope: !192, file: !1318, line: 47, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listIPN4llvm4yaml5Input5HNodeEE")
!4105 = !DISubprogram(name: "~vector", scope: !4064, file: !1080, line: 565, type: !4068, scopeLine: 565, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4106 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EEaSERKS6_", scope: !4064, file: !1080, line: 582, type: !4107, scopeLine: 582, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4107 = !DISubroutineType(types: !4108)
!4108 = !{!4109, !4070, !4089}
!4109 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4064, size: 64)
!4110 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EEaSEOS6_", scope: !4064, file: !1080, line: 596, type: !4111, scopeLine: 596, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4111 = !DISubroutineType(types: !4112)
!4112 = !{!4109, !4070, !4094}
!4113 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EEaSESt16initializer_listIS4_E", scope: !4064, file: !1080, line: 617, type: !4114, scopeLine: 617, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4114 = !DISubroutineType(types: !4115)
!4115 = !{!4109, !4070, !4104}
!4116 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE6assignEmRKS4_", scope: !4064, file: !1080, line: 636, type: !4117, scopeLine: 636, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4117 = !DISubroutineType(types: !4118)
!4118 = !{null, !4070, !1292, !4083}
!4119 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE6assignESt16initializer_listIS4_E", scope: !4064, file: !1080, line: 681, type: !4120, scopeLine: 681, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4120 = !DISubroutineType(types: !4121)
!4121 = !{null, !4070, !4104}
!4122 = !DISubprogram(name: "begin", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE5beginEv", scope: !4064, file: !1080, line: 698, type: !4123, scopeLine: 698, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4123 = !DISubroutineType(types: !4124)
!4124 = !{!4125, !4070}
!4125 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !4064, file: !1080, line: 369, baseType: !4126)
!4126 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<llvm::yaml::Input::HNode **, std::vector<llvm::yaml::Input::HNode *, std::allocator<llvm::yaml::Input::HNode *> > >", scope: !5, file: !631, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4127, templateParams: !4178, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPPN4llvm4yaml5Input5HNodeESt6vectorIS5_SaIS5_EEEE")
!4127 = !{!4128, !4129, !4133, !4138, !4148, !4153, !4157, !4160, !4161, !4162, !4167, !4170, !4173, !4174, !4175}
!4128 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !4126, file: !631, line: 767, baseType: !3652, size: 64, flags: DIFlagProtected)
!4129 = !DISubprogram(name: "__normal_iterator", scope: !4126, file: !631, line: 779, type: !4130, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4130 = !DISubroutineType(types: !4131)
!4131 = !{null, !4132}
!4132 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4126, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4133 = !DISubprogram(name: "__normal_iterator", scope: !4126, file: !631, line: 783, type: !4134, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4134 = !DISubroutineType(types: !4135)
!4135 = !{null, !4132, !4136}
!4136 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4137, size: 64)
!4137 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3652)
!4138 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN4llvm4yaml5Input5HNodeESt6vectorIS5_SaIS5_EEEdeEv", scope: !4126, file: !631, line: 796, type: !4139, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4139 = !DISubroutineType(types: !4140)
!4140 = !{!4141, !4146}
!4141 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !4126, file: !631, line: 776, baseType: !4142)
!4142 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !4143, file: !1357, line: 184, baseType: !3257)
!4143 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<llvm::yaml::Input::HNode **>", scope: !192, file: !1357, line: 178, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4144, identifier: "_ZTSSt15iterator_traitsIPPN4llvm4yaml5Input5HNodeEE")
!4144 = !{!4145}
!4145 = !DITemplateTypeParameter(name: "_Iterator", type: !3652)
!4146 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4147, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4147 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4126)
!4148 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN4llvm4yaml5Input5HNodeESt6vectorIS5_SaIS5_EEEptEv", scope: !4126, file: !631, line: 800, type: !4149, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4149 = !DISubroutineType(types: !4150)
!4150 = !{!4151, !4146}
!4151 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4126, file: !631, line: 777, baseType: !4152)
!4152 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4143, file: !1357, line: 183, baseType: !3652)
!4153 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN4llvm4yaml5Input5HNodeESt6vectorIS5_SaIS5_EEEppEv", scope: !4126, file: !631, line: 804, type: !4154, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4154 = !DISubroutineType(types: !4155)
!4155 = !{!4156, !4132}
!4156 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4126, size: 64)
!4157 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN4llvm4yaml5Input5HNodeESt6vectorIS5_SaIS5_EEEppEi", scope: !4126, file: !631, line: 811, type: !4158, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4158 = !DISubroutineType(types: !4159)
!4159 = !{!4126, !4132, !24}
!4160 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN4llvm4yaml5Input5HNodeESt6vectorIS5_SaIS5_EEEmmEv", scope: !4126, file: !631, line: 816, type: !4154, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4161 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN4llvm4yaml5Input5HNodeESt6vectorIS5_SaIS5_EEEmmEi", scope: !4126, file: !631, line: 823, type: !4158, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4162 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN4llvm4yaml5Input5HNodeESt6vectorIS5_SaIS5_EEEixEl", scope: !4126, file: !631, line: 828, type: !4163, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4163 = !DISubroutineType(types: !4164)
!4164 = !{!4141, !4146, !4165}
!4165 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !4126, file: !631, line: 775, baseType: !4166)
!4166 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !4143, file: !1357, line: 182, baseType: !1382)
!4167 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN4llvm4yaml5Input5HNodeESt6vectorIS5_SaIS5_EEEpLEl", scope: !4126, file: !631, line: 832, type: !4168, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4168 = !DISubroutineType(types: !4169)
!4169 = !{!4156, !4132, !4165}
!4170 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN4llvm4yaml5Input5HNodeESt6vectorIS5_SaIS5_EEEplEl", scope: !4126, file: !631, line: 836, type: !4171, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4171 = !DISubroutineType(types: !4172)
!4172 = !{!4126, !4146, !4165}
!4173 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN4llvm4yaml5Input5HNodeESt6vectorIS5_SaIS5_EEEmIEl", scope: !4126, file: !631, line: 840, type: !4168, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4174 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN4llvm4yaml5Input5HNodeESt6vectorIS5_SaIS5_EEEmiEl", scope: !4126, file: !631, line: 844, type: !4171, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4175 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN4llvm4yaml5Input5HNodeESt6vectorIS5_SaIS5_EEE4baseEv", scope: !4126, file: !631, line: 848, type: !4176, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4176 = !DISubroutineType(types: !4177)
!4177 = !{!4136, !4146}
!4178 = !{!4145, !4179}
!4179 = !DITemplateTypeParameter(name: "_Container", type: !4064)
!4180 = !DISubprogram(name: "begin", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE5beginEv", scope: !4064, file: !1080, line: 707, type: !4181, scopeLine: 707, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4181 = !DISubroutineType(types: !4182)
!4182 = !{!4183, !4185}
!4183 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !4064, file: !1080, line: 371, baseType: !4184)
!4184 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<llvm::yaml::Input::HNode *const *, std::vector<llvm::yaml::Input::HNode *, std::allocator<llvm::yaml::Input::HNode *> > >", scope: !5, file: !631, line: 764, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPKPN4llvm4yaml5Input5HNodeESt6vectorIS5_SaIS5_EEEE")
!4185 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4090, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4186 = !DISubprogram(name: "end", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE3endEv", scope: !4064, file: !1080, line: 716, type: !4123, scopeLine: 716, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4187 = !DISubprogram(name: "end", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE3endEv", scope: !4064, file: !1080, line: 725, type: !4181, scopeLine: 725, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4188 = !DISubprogram(name: "rbegin", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE6rbeginEv", scope: !4064, file: !1080, line: 734, type: !4189, scopeLine: 734, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4189 = !DISubroutineType(types: !4190)
!4190 = !{!4191, !4070}
!4191 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !4064, file: !1080, line: 373, baseType: !4192)
!4192 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<llvm::yaml::Input::HNode **, std::vector<llvm::yaml::Input::HNode *, std::allocator<llvm::yaml::Input::HNode *> > > >", scope: !192, file: !631, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPPN4llvm4yaml5Input5HNodeESt6vectorIS6_SaIS6_EEEEE")
!4193 = !DISubprogram(name: "rbegin", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE6rbeginEv", scope: !4064, file: !1080, line: 743, type: !4194, scopeLine: 743, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4194 = !DISubroutineType(types: !4195)
!4195 = !{!4196, !4185}
!4196 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !4064, file: !1080, line: 372, baseType: !4197)
!4197 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<llvm::yaml::Input::HNode *const *, std::vector<llvm::yaml::Input::HNode *, std::allocator<llvm::yaml::Input::HNode *> > > >", scope: !192, file: !631, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPKPN4llvm4yaml5Input5HNodeESt6vectorIS6_SaIS6_EEEEE")
!4198 = !DISubprogram(name: "rend", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE4rendEv", scope: !4064, file: !1080, line: 752, type: !4189, scopeLine: 752, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4199 = !DISubprogram(name: "rend", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE4rendEv", scope: !4064, file: !1080, line: 761, type: !4194, scopeLine: 761, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4200 = !DISubprogram(name: "cbegin", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE6cbeginEv", scope: !4064, file: !1080, line: 771, type: !4181, scopeLine: 771, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4201 = !DISubprogram(name: "cend", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE4cendEv", scope: !4064, file: !1080, line: 780, type: !4181, scopeLine: 780, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4202 = !DISubprogram(name: "crbegin", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE7crbeginEv", scope: !4064, file: !1080, line: 789, type: !4194, scopeLine: 789, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4203 = !DISubprogram(name: "crend", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE5crendEv", scope: !4064, file: !1080, line: 798, type: !4194, scopeLine: 798, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4204 = !DISubprogram(name: "size", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE4sizeEv", scope: !4064, file: !1080, line: 805, type: !4205, scopeLine: 805, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4205 = !DISubroutineType(types: !4206)
!4206 = !{!1292, !4185}
!4207 = !DISubprogram(name: "max_size", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE8max_sizeEv", scope: !4064, file: !1080, line: 810, type: !4205, scopeLine: 810, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4208 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE6resizeEm", scope: !4064, file: !1080, line: 824, type: !4209, scopeLine: 824, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4209 = !DISubroutineType(types: !4210)
!4210 = !{null, !4070, !1292}
!4211 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE6resizeEmRKS4_", scope: !4064, file: !1080, line: 844, type: !4117, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4212 = !DISubprogram(name: "shrink_to_fit", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE13shrink_to_fitEv", scope: !4064, file: !1080, line: 876, type: !4068, scopeLine: 876, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4213 = !DISubprogram(name: "capacity", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE8capacityEv", scope: !4064, file: !1080, line: 885, type: !4205, scopeLine: 885, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4214 = !DISubprogram(name: "empty", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE5emptyEv", scope: !4064, file: !1080, line: 894, type: !4215, scopeLine: 894, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4215 = !DISubroutineType(types: !4216)
!4216 = !{!132, !4185}
!4217 = !DISubprogram(name: "reserve", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE7reserveEm", scope: !4064, file: !1080, line: 915, type: !4209, scopeLine: 915, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4218 = !DISubprogram(name: "operator[]", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EEixEm", scope: !4064, file: !1080, line: 930, type: !4219, scopeLine: 930, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4219 = !DISubroutineType(types: !4220)
!4220 = !{!4221, !4070, !1292}
!4221 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !4064, file: !1080, line: 367, baseType: !4222)
!4222 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3643, file: !1091, line: 64, baseType: !4223)
!4223 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4224, size: 64)
!4224 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !3643, file: !1091, line: 58, baseType: !4225)
!4225 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !3646, file: !1097, line: 389, baseType: !2362)
!4226 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EEixEm", scope: !4064, file: !1080, line: 948, type: !4227, scopeLine: 948, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4227 = !DISubroutineType(types: !4228)
!4228 = !{!4229, !4185, !1292}
!4229 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !4064, file: !1080, line: 368, baseType: !4230)
!4230 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !3643, file: !1091, line: 65, baseType: !4231)
!4231 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4232, size: 64)
!4232 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4224)
!4233 = !DISubprogram(name: "_M_range_check", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE14_M_range_checkEm", scope: !4064, file: !1080, line: 957, type: !4234, scopeLine: 957, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4234 = !DISubroutineType(types: !4235)
!4235 = !{null, !4185, !1292}
!4236 = !DISubprogram(name: "at", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE2atEm", scope: !4064, file: !1080, line: 979, type: !4219, scopeLine: 979, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4237 = !DISubprogram(name: "at", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE2atEm", scope: !4064, file: !1080, line: 997, type: !4227, scopeLine: 997, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4238 = !DISubprogram(name: "front", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE5frontEv", scope: !4064, file: !1080, line: 1008, type: !4239, scopeLine: 1008, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4239 = !DISubroutineType(types: !4240)
!4240 = !{!4221, !4070}
!4241 = !DISubprogram(name: "front", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE5frontEv", scope: !4064, file: !1080, line: 1019, type: !4242, scopeLine: 1019, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4242 = !DISubroutineType(types: !4243)
!4243 = !{!4229, !4185}
!4244 = !DISubprogram(name: "back", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE4backEv", scope: !4064, file: !1080, line: 1030, type: !4239, scopeLine: 1030, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4245 = !DISubprogram(name: "back", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE4backEv", scope: !4064, file: !1080, line: 1041, type: !4242, scopeLine: 1041, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4246 = !DISubprogram(name: "data", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE4dataEv", scope: !4064, file: !1080, line: 1055, type: !4247, scopeLine: 1055, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4247 = !DISubroutineType(types: !4248)
!4248 = !{!3652, !4070}
!4249 = !DISubprogram(name: "data", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE4dataEv", scope: !4064, file: !1080, line: 1059, type: !4250, scopeLine: 1059, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4250 = !DISubroutineType(types: !4251)
!4251 = !{!3681, !4185}
!4252 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE9push_backERKS4_", scope: !4064, file: !1080, line: 1074, type: !4253, scopeLine: 1074, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4253 = !DISubroutineType(types: !4254)
!4254 = !{null, !4070, !4083}
!4255 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE9push_backEOS4_", scope: !4064, file: !1080, line: 1090, type: !4256, scopeLine: 1090, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4256 = !DISubroutineType(types: !4257)
!4257 = !{null, !4070, !4258}
!4258 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !4085, size: 64)
!4259 = !DISubprogram(name: "pop_back", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE8pop_backEv", scope: !4064, file: !1080, line: 1112, type: !4068, scopeLine: 1112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4260 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EERS9_", scope: !4064, file: !1080, line: 1150, type: !4261, scopeLine: 1150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4261 = !DISubroutineType(types: !4262)
!4262 = !{!4125, !4070, !4183, !4083}
!4263 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EEOS4_", scope: !4064, file: !1080, line: 1180, type: !4264, scopeLine: 1180, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4264 = !DISubroutineType(types: !4265)
!4265 = !{!4125, !4070, !4183, !4258}
!4266 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EESt16initializer_listIS4_E", scope: !4064, file: !1080, line: 1197, type: !4267, scopeLine: 1197, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4267 = !DISubroutineType(types: !4268)
!4268 = !{!4125, !4070, !4183, !4104}
!4269 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EEmRS9_", scope: !4064, file: !1080, line: 1222, type: !4270, scopeLine: 1222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4270 = !DISubroutineType(types: !4271)
!4271 = !{!4125, !4070, !4183, !1292, !4083}
!4272 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE5eraseEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EE", scope: !4064, file: !1080, line: 1317, type: !4273, scopeLine: 1317, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4273 = !DISubroutineType(types: !4274)
!4274 = !{!4125, !4070, !4183}
!4275 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE5eraseEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EESB_", scope: !4064, file: !1080, line: 1344, type: !4276, scopeLine: 1344, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4276 = !DISubroutineType(types: !4277)
!4277 = !{!4125, !4070, !4183, !4183}
!4278 = !DISubprogram(name: "swap", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE4swapERS6_", scope: !4064, file: !1080, line: 1367, type: !4279, scopeLine: 1367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4279 = !DISubroutineType(types: !4280)
!4280 = !{null, !4070, !4109}
!4281 = !DISubprogram(name: "clear", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE5clearEv", scope: !4064, file: !1080, line: 1385, type: !4068, scopeLine: 1385, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4282 = !DISubprogram(name: "_M_fill_initialize", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE18_M_fill_initializeEmRKS4_", scope: !4064, file: !1080, line: 1477, type: !4117, scopeLine: 1477, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4283 = !DISubprogram(name: "_M_default_initialize", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE21_M_default_initializeEm", scope: !4064, file: !1080, line: 1487, type: !4209, scopeLine: 1487, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4284 = !DISubprogram(name: "_M_fill_assign", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE14_M_fill_assignEmRKS4_", scope: !4064, file: !1080, line: 1529, type: !4117, scopeLine: 1529, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4285 = !DISubprogram(name: "_M_fill_insert", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS4_S6_EEmRKS4_", scope: !4064, file: !1080, line: 1568, type: !4286, scopeLine: 1568, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4286 = !DISubroutineType(types: !4287)
!4287 = !{null, !4070, !4125, !1292, !4083}
!4288 = !DISubprogram(name: "_M_default_append", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE17_M_default_appendEm", scope: !4064, file: !1080, line: 1573, type: !4209, scopeLine: 1573, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4289 = !DISubprogram(name: "_M_shrink_to_fit", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE16_M_shrink_to_fitEv", scope: !4064, file: !1080, line: 1576, type: !4290, scopeLine: 1576, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4290 = !DISubroutineType(types: !4291)
!4291 = !{!132, !4070}
!4292 = !DISubprogram(name: "_M_insert_rval", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE14_M_insert_rvalEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EEOS4_", scope: !4064, file: !1080, line: 1625, type: !4264, scopeLine: 1625, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4293 = !DISubprogram(name: "_M_emplace_aux", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE14_M_emplace_auxEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EEOS4_", scope: !4064, file: !1080, line: 1634, type: !4264, scopeLine: 1634, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4294 = !DISubprogram(name: "_M_check_len", linkageName: "_ZNKSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE12_M_check_lenEmPKc", scope: !4064, file: !1080, line: 1640, type: !4295, scopeLine: 1640, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4295 = !DISubroutineType(types: !4296)
!4296 = !{!4297, !4185, !1292, !163}
!4297 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !4064, file: !1080, line: 374, baseType: !1152)
!4298 = !DISubprogram(name: "_M_erase_at_end", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE15_M_erase_at_endEPS4_", scope: !4064, file: !1080, line: 1654, type: !4299, scopeLine: 1654, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4299 = !DISubroutineType(types: !4300)
!4300 = !{null, !4070, !4301}
!4301 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4064, file: !1080, line: 365, baseType: !3641)
!4302 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE8_M_eraseEN9__gnu_cxx17__normal_iteratorIPS4_S6_EE", scope: !4064, file: !1080, line: 1666, type: !4303, scopeLine: 1666, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4303 = !DISubroutineType(types: !4304)
!4304 = !{!4125, !4070, !4125}
!4305 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE8_M_eraseEN9__gnu_cxx17__normal_iteratorIPS4_S6_EESA_", scope: !4064, file: !1080, line: 1669, type: !4306, scopeLine: 1669, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4306 = !DISubroutineType(types: !4307)
!4307 = !{!4125, !4070, !4125, !4125}
!4308 = !DISubprogram(name: "_M_move_assign", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE14_M_move_assignEOS6_St17integral_constantIbLb1EE", scope: !4064, file: !1080, line: 1677, type: !4309, scopeLine: 1677, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4309 = !DISubroutineType(types: !4310)
!4310 = !{null, !4070, !4094, !1527}
!4311 = !DISubprogram(name: "_M_move_assign", linkageName: "_ZNSt6vectorIPN4llvm4yaml5Input5HNodeESaIS4_EE14_M_move_assignEOS6_St17integral_constantIbLb0EE", scope: !4064, file: !1080, line: 1688, type: !4312, scopeLine: 1688, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4312 = !DISubroutineType(types: !4313)
!4313 = !{null, !4070, !4094, !1545}
!4314 = !DISubprogram(name: "SequenceHNode", scope: !4060, file: !108, line: 782, type: !4315, scopeLine: 782, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4315 = !DISubroutineType(types: !4316)
!4316 = !{null, !4317, !3208}
!4317 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4060, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4318 = !DISubprogram(name: "~SequenceHNode", scope: !4060, file: !108, line: 783, type: !4319, scopeLine: 783, containingType: !4060, virtualIndex: 0, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!4319 = !DISubroutineType(types: !4320)
!4320 = !{null, !4317}
!4321 = !DISubprogram(name: "classof", linkageName: "_ZN4llvm4yaml5Input13SequenceHNode7classofEPKNS1_5HNodeE", scope: !4060, file: !108, line: 785, type: !3229, scopeLine: 785, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4322 = !DISubprogram(name: "classof", linkageName: "_ZN4llvm4yaml5Input13SequenceHNode7classofEPKS2_", scope: !4060, file: !108, line: 788, type: !4323, scopeLine: 788, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4323 = !DISubroutineType(types: !4324)
!4324 = !{!132, !4325}
!4325 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4326, size: 64)
!4326 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4060)
!4327 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4328, file: !3805, line: 179, baseType: !4330)
!4328 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_wrap<llvm::yaml::Input::SequenceHNode, llvm::yaml::Input::HNode *, llvm::yaml::Input::HNode *>", scope: !14, file: !3805, line: 177, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4329, identifier: "_ZTSN4llvm15cast_retty_wrapINS_4yaml5Input13SequenceHNodeEPNS2_5HNodeES5_EE")
!4329 = !{!4059, !4048, !4052}
!4330 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4331, file: !3805, line: 156, baseType: !4332)
!4331 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_impl<llvm::yaml::Input::SequenceHNode, llvm::yaml::Input::HNode *>", scope: !14, file: !3805, line: 155, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4058, identifier: "_ZTSN4llvm15cast_retty_implINS_4yaml5Input13SequenceHNodeEPNS2_5HNodeEEE")
!4332 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4060, size: 64)
!4333 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4334, file: !3805, line: 185, baseType: !4358)
!4334 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty<llvm::yaml::Input::ScalarHNode, llvm::yaml::Input::HNode *>", scope: !14, file: !3805, line: 183, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4335, identifier: "_ZTSN4llvm10cast_rettyINS_4yaml5Input11ScalarHNodeEPNS2_5HNodeEEE")
!4335 = !{!4336, !4048}
!4336 = !DITemplateTypeParameter(name: "To", type: !4337)
!4337 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ScalarHNode", scope: !2364, file: !108, line: 747, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4338, vtableHolder: !2363)
!4338 = !{!4339, !4340, !4341, !4345, !4348, !4353, !4354}
!4339 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4337, baseType: !2363, flags: DIFlagPublic, extraData: i32 0)
!4340 = !DIDerivedType(tag: DW_TAG_member, name: "_value", scope: !4337, file: !108, line: 759, baseType: !154, size: 128, offset: 128, flags: DIFlagProtected)
!4341 = !DISubprogram(name: "anchor", linkageName: "_ZN4llvm4yaml5Input11ScalarHNode6anchorEv", scope: !4337, file: !108, line: 748, type: !4342, scopeLine: 748, containingType: !4337, virtualIndex: 0, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!4342 = !DISubroutineType(types: !4343)
!4343 = !{null, !4344}
!4344 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4337, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4345 = !DISubprogram(name: "ScalarHNode", scope: !4337, file: !108, line: 750, type: !4346, scopeLine: 750, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4346 = !DISubroutineType(types: !4347)
!4347 = !{null, !4344, !3208, !154}
!4348 = !DISubprogram(name: "value", linkageName: "_ZNK4llvm4yaml5Input11ScalarHNode5valueEv", scope: !4337, file: !108, line: 752, type: !4349, scopeLine: 752, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4349 = !DISubroutineType(types: !4350)
!4350 = !{!154, !4351}
!4351 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4352, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4352 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4337)
!4353 = !DISubprogram(name: "classof", linkageName: "_ZN4llvm4yaml5Input11ScalarHNode7classofEPKNS1_5HNodeE", scope: !4337, file: !108, line: 754, type: !3229, scopeLine: 754, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4354 = !DISubprogram(name: "classof", linkageName: "_ZN4llvm4yaml5Input11ScalarHNode7classofEPKS2_", scope: !4337, file: !108, line: 757, type: !4355, scopeLine: 757, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4355 = !DISubroutineType(types: !4356)
!4356 = !{!132, !4357}
!4357 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4352, size: 64)
!4358 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4359, file: !3805, line: 179, baseType: !4361)
!4359 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_wrap<llvm::yaml::Input::ScalarHNode, llvm::yaml::Input::HNode *, llvm::yaml::Input::HNode *>", scope: !14, file: !3805, line: 177, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4360, identifier: "_ZTSN4llvm15cast_retty_wrapINS_4yaml5Input11ScalarHNodeEPNS2_5HNodeES5_EE")
!4360 = !{!4336, !4048, !4052}
!4361 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4362, file: !3805, line: 156, baseType: !4363)
!4362 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_impl<llvm::yaml::Input::ScalarHNode, llvm::yaml::Input::HNode *>", scope: !14, file: !3805, line: 155, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4335, identifier: "_ZTSN4llvm15cast_retty_implINS_4yaml5Input11ScalarHNodeEPNS2_5HNodeEEE")
!4363 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4337, size: 64)
!4364 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", file: !2555, line: 601, baseType: !1382)
!4365 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4366, file: !3805, line: 185, baseType: !4371)
!4366 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty<llvm::yaml::ScalarNode, llvm::yaml::Node *>", scope: !14, file: !3805, line: 183, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4367, identifier: "_ZTSN4llvm10cast_rettyINS_4yaml10ScalarNodeEPNS1_4NodeEEE")
!4367 = !{!4368, !4370}
!4368 = !DITemplateTypeParameter(name: "To", type: !4369)
!4369 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ScalarNode", scope: !110, file: !2332, line: 194, size: 704, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm4yaml10ScalarNodeE")
!4370 = !DITemplateTypeParameter(name: "From", type: !3208)
!4371 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4372, file: !3805, line: 179, baseType: !4375)
!4372 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_wrap<llvm::yaml::ScalarNode, llvm::yaml::Node *, llvm::yaml::Node *>", scope: !14, file: !3805, line: 177, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4373, identifier: "_ZTSN4llvm15cast_retty_wrapINS_4yaml10ScalarNodeEPNS1_4NodeES4_EE")
!4373 = !{!4368, !4370, !4374}
!4374 = !DITemplateTypeParameter(name: "SimpleFrom", type: !3208)
!4375 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4376, file: !3805, line: 156, baseType: !4377)
!4376 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_impl<llvm::yaml::ScalarNode, llvm::yaml::Node *>", scope: !14, file: !3805, line: 155, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4367, identifier: "_ZTSN4llvm15cast_retty_implINS_4yaml10ScalarNodeEPNS1_4NodeEEE")
!4377 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4369, size: 64)
!4378 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4379, file: !3805, line: 185, baseType: !4383)
!4379 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty<llvm::yaml::SequenceNode, llvm::yaml::Node *>", scope: !14, file: !3805, line: 183, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4380, identifier: "_ZTSN4llvm10cast_rettyINS_4yaml12SequenceNodeEPNS1_4NodeEEE")
!4380 = !{!4381, !4370}
!4381 = !DITemplateTypeParameter(name: "To", type: !4382)
!4382 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SequenceNode", scope: !110, file: !2332, line: 398, size: 704, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm4yaml12SequenceNodeE")
!4383 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4384, file: !3805, line: 179, baseType: !4386)
!4384 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_wrap<llvm::yaml::SequenceNode, llvm::yaml::Node *, llvm::yaml::Node *>", scope: !14, file: !3805, line: 177, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4385, identifier: "_ZTSN4llvm15cast_retty_wrapINS_4yaml12SequenceNodeEPNS1_4NodeES4_EE")
!4385 = !{!4381, !4370, !4374}
!4386 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4387, file: !3805, line: 156, baseType: !4388)
!4387 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_impl<llvm::yaml::SequenceNode, llvm::yaml::Node *>", scope: !14, file: !3805, line: 155, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4380, identifier: "_ZTSN4llvm15cast_retty_implINS_4yaml12SequenceNodeEPNS1_4NodeEEE")
!4388 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4382, size: 64)
!4389 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3745, size: 64)
!4390 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "move_iterator<llvm::yaml::Input::HNode **>", scope: !192, file: !631, line: 1007, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4391, templateParams: !4144, identifier: "_ZTSSt13move_iteratorIPPN4llvm4yaml5Input5HNodeEE")
!4391 = !{!4392, !4393, !4397, !4401, !4406, !4416, !4420, !4424, !4427, !4428, !4429, !4433, !4436, !4437, !4438}
!4392 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !4390, file: !631, line: 1010, baseType: !3652, size: 64, flags: DIFlagProtected)
!4393 = !DISubprogram(name: "move_iterator", scope: !4390, file: !631, line: 1029, type: !4394, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4394 = !DISubroutineType(types: !4395)
!4395 = !{null, !4396}
!4396 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4390, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4397 = !DISubprogram(name: "move_iterator", scope: !4390, file: !631, line: 1033, type: !4398, scopeLine: 1033, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4398 = !DISubroutineType(types: !4399)
!4399 = !{null, !4396, !4400}
!4400 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator_type", scope: !4390, file: !631, line: 1016, baseType: !3652)
!4401 = !DISubprogram(name: "base", linkageName: "_ZNKSt13move_iteratorIPPN4llvm4yaml5Input5HNodeEE4baseEv", scope: !4390, file: !631, line: 1042, type: !4402, scopeLine: 1042, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4402 = !DISubroutineType(types: !4403)
!4403 = !{!4400, !4404}
!4404 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4405, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4405 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4390)
!4406 = !DISubprogram(name: "operator*", linkageName: "_ZNKSt13move_iteratorIPPN4llvm4yaml5Input5HNodeEEdeEv", scope: !4390, file: !631, line: 1046, type: !4407, scopeLine: 1046, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4407 = !DISubroutineType(types: !4408)
!4408 = !{!4409, !4404}
!4409 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !4390, file: !631, line: 1026, baseType: !4410)
!4410 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !4411, file: !318, line: 1928, baseType: !4414)
!4411 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, llvm::yaml::Input::HNode *&&, llvm::yaml::Input::HNode *&>", scope: !192, file: !318, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4412, identifier: "_ZTSSt11conditionalILb1EOPN4llvm4yaml5Input5HNodeERS4_E")
!4412 = !{!322, !4413, !4415}
!4413 = !DITemplateTypeParameter(name: "_Iftrue", type: !4414)
!4414 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2362, size: 64)
!4415 = !DITemplateTypeParameter(name: "_Iffalse", type: !3257)
!4416 = !DISubprogram(name: "operator->", linkageName: "_ZNKSt13move_iteratorIPPN4llvm4yaml5Input5HNodeEEptEv", scope: !4390, file: !631, line: 1050, type: !4417, scopeLine: 1050, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4417 = !DISubroutineType(types: !4418)
!4418 = !{!4419, !4404}
!4419 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4390, file: !631, line: 1021, baseType: !3652)
!4420 = !DISubprogram(name: "operator++", linkageName: "_ZNSt13move_iteratorIPPN4llvm4yaml5Input5HNodeEEppEv", scope: !4390, file: !631, line: 1054, type: !4421, scopeLine: 1054, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4421 = !DISubroutineType(types: !4422)
!4422 = !{!4423, !4396}
!4423 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4390, size: 64)
!4424 = !DISubprogram(name: "operator++", linkageName: "_ZNSt13move_iteratorIPPN4llvm4yaml5Input5HNodeEEppEi", scope: !4390, file: !631, line: 1061, type: !4425, scopeLine: 1061, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4425 = !DISubroutineType(types: !4426)
!4426 = !{!4390, !4396, !24}
!4427 = !DISubprogram(name: "operator--", linkageName: "_ZNSt13move_iteratorIPPN4llvm4yaml5Input5HNodeEEmmEv", scope: !4390, file: !631, line: 1069, type: !4421, scopeLine: 1069, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4428 = !DISubprogram(name: "operator--", linkageName: "_ZNSt13move_iteratorIPPN4llvm4yaml5Input5HNodeEEmmEi", scope: !4390, file: !631, line: 1076, type: !4425, scopeLine: 1076, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4429 = !DISubprogram(name: "operator+", linkageName: "_ZNKSt13move_iteratorIPPN4llvm4yaml5Input5HNodeEEplEl", scope: !4390, file: !631, line: 1084, type: !4430, scopeLine: 1084, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4430 = !DISubroutineType(types: !4431)
!4431 = !{!4390, !4404, !4432}
!4432 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !4390, file: !631, line: 1019, baseType: !4166)
!4433 = !DISubprogram(name: "operator+=", linkageName: "_ZNSt13move_iteratorIPPN4llvm4yaml5Input5HNodeEEpLEl", scope: !4390, file: !631, line: 1088, type: !4434, scopeLine: 1088, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4434 = !DISubroutineType(types: !4435)
!4435 = !{!4423, !4396, !4432}
!4436 = !DISubprogram(name: "operator-", linkageName: "_ZNKSt13move_iteratorIPPN4llvm4yaml5Input5HNodeEEmiEl", scope: !4390, file: !631, line: 1095, type: !4430, scopeLine: 1095, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4437 = !DISubprogram(name: "operator-=", linkageName: "_ZNSt13move_iteratorIPPN4llvm4yaml5Input5HNodeEEmIEl", scope: !4390, file: !631, line: 1099, type: !4434, scopeLine: 1099, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4438 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt13move_iteratorIPPN4llvm4yaml5Input5HNodeEEixEl", scope: !4390, file: !631, line: 1106, type: !4439, scopeLine: 1106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4439 = !DISubroutineType(types: !4440)
!4440 = !{!4409, !4404, !4432}
!4441 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4442, file: !3805, line: 185, baseType: !4446)
!4442 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty<llvm::yaml::MappingNode, llvm::yaml::Node *>", scope: !14, file: !3805, line: 183, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4443, identifier: "_ZTSN4llvm10cast_rettyINS_4yaml11MappingNodeEPNS1_4NodeEEE")
!4443 = !{!4444, !4370}
!4444 = !DITemplateTypeParameter(name: "To", type: !4445)
!4445 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MappingNode", scope: !110, file: !2332, line: 348, size: 704, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm4yaml11MappingNodeE")
!4446 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4447, file: !3805, line: 179, baseType: !4449)
!4447 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_wrap<llvm::yaml::MappingNode, llvm::yaml::Node *, llvm::yaml::Node *>", scope: !14, file: !3805, line: 177, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4448, identifier: "_ZTSN4llvm15cast_retty_wrapINS_4yaml11MappingNodeEPNS1_4NodeES4_EE")
!4448 = !{!4444, !4370, !4374}
!4449 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !4450, file: !3805, line: 156, baseType: !4451)
!4450 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_impl<llvm::yaml::MappingNode, llvm::yaml::Node *>", scope: !14, file: !3805, line: 155, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4443, identifier: "_ZTSN4llvm15cast_retty_implINS_4yaml11MappingNodeEPNS1_4NodeEEE")
!4451 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4445, size: 64)
!4452 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "EmptyHNode", scope: !2364, file: !108, line: 737, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4453, vtableHolder: !2363)
!4453 = !{!4454, !4455, !4459, !4462, !4463}
!4454 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4452, baseType: !2363, flags: DIFlagPublic, extraData: i32 0)
!4455 = !DISubprogram(name: "anchor", linkageName: "_ZN4llvm4yaml5Input10EmptyHNode6anchorEv", scope: !4452, file: !108, line: 738, type: !4456, scopeLine: 738, containingType: !4452, virtualIndex: 0, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!4456 = !DISubroutineType(types: !4457)
!4457 = !{null, !4458}
!4458 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4452, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4459 = !DISubprogram(name: "EmptyHNode", scope: !4452, file: !108, line: 740, type: !4460, scopeLine: 740, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4460 = !DISubroutineType(types: !4461)
!4461 = !{null, !4458, !3208}
!4462 = !DISubprogram(name: "classof", linkageName: "_ZN4llvm4yaml5Input10EmptyHNode7classofEPKNS1_5HNodeE", scope: !4452, file: !108, line: 741, type: !3229, scopeLine: 741, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4463 = !DISubprogram(name: "classof", linkageName: "_ZN4llvm4yaml5Input10EmptyHNode7classofEPKS2_", scope: !4452, file: !108, line: 744, type: !4464, scopeLine: 744, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4464 = !DISubroutineType(types: !4465)
!4465 = !{!132, !4466}
!4466 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4467, size: 64)
!4467 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4452)
!4468 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "basic_collection_iterator<llvm::yaml::SequenceNode, llvm::yaml::Node>", scope: !110, file: !2332, line: 279, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4469, templateParams: !4503, identifier: "_ZTSN4llvm4yaml25basic_collection_iteratorINS0_12SequenceNodeENS0_4NodeEEE")
!4469 = !{!4470, !4478, !4479, !4483, !4486, !4491, !4494, !4495, !4499}
!4470 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4468, baseType: !4471, flags: DIFlagPublic, extraData: i32 0)
!4471 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::forward_iterator_tag, llvm::yaml::Node, long, llvm::yaml::Node *, llvm::yaml::Node &>", scope: !192, file: !1357, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4472, identifier: "_ZTSSt8iteratorISt20forward_iterator_tagN4llvm4yaml4NodeElPS3_RS3_E")
!4472 = !{!4473, !4474, !2689, !4475, !4476}
!4473 = !DITemplateTypeParameter(name: "_Category", type: !2685)
!4474 = !DITemplateTypeParameter(name: "_Tp", type: !2333)
!4475 = !DITemplateTypeParameter(name: "_Pointer", type: !3208)
!4476 = !DITemplateTypeParameter(name: "_Reference", type: !4477)
!4477 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2333, size: 64)
!4478 = !DIDerivedType(tag: DW_TAG_member, name: "Base", scope: !4468, file: !2332, line: 318, baseType: !4388, size: 64)
!4479 = !DISubprogram(name: "basic_collection_iterator", scope: !4468, file: !2332, line: 282, type: !4480, scopeLine: 282, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4480 = !DISubroutineType(types: !4481)
!4481 = !{null, !4482}
!4482 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4468, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4483 = !DISubprogram(name: "basic_collection_iterator", scope: !4468, file: !2332, line: 283, type: !4484, scopeLine: 283, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4484 = !DISubroutineType(types: !4485)
!4485 = !{null, !4482, !4388}
!4486 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm4yaml25basic_collection_iteratorINS0_12SequenceNodeENS0_4NodeEEptEv", scope: !4468, file: !2332, line: 285, type: !4487, scopeLine: 285, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4487 = !DISubroutineType(types: !4488)
!4488 = !{!3208, !4489}
!4489 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4490, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4490 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4468)
!4491 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm4yaml25basic_collection_iteratorINS0_12SequenceNodeENS0_4NodeEEdeEv", scope: !4468, file: !2332, line: 290, type: !4492, scopeLine: 290, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4492 = !DISubroutineType(types: !4493)
!4493 = !{!4477, !4489}
!4494 = !DISubprogram(name: "operator llvm::yaml::Node *", linkageName: "_ZNK4llvm4yaml25basic_collection_iteratorINS0_12SequenceNodeENS0_4NodeEEcvPS3_Ev", scope: !4468, file: !2332, line: 296, type: !4487, scopeLine: 296, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4495 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm4yaml25basic_collection_iteratorINS0_12SequenceNodeENS0_4NodeEEneERKS4_", scope: !4468, file: !2332, line: 301, type: !4496, scopeLine: 301, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4496 = !DISubroutineType(types: !4497)
!4497 = !{!132, !4489, !4498}
!4498 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4490, size: 64)
!4499 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm4yaml25basic_collection_iteratorINS0_12SequenceNodeENS0_4NodeEEppEv", scope: !4468, file: !2332, line: 308, type: !4500, scopeLine: 308, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4500 = !DISubroutineType(types: !4501)
!4501 = !{!4502, !4482}
!4502 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4468, size: 64)
!4503 = !{!4504, !4505}
!4504 = !DITemplateTypeParameter(name: "BaseT", type: !4382)
!4505 = !DITemplateTypeParameter(name: "ValueT", type: !2333)
!4506 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "basic_collection_iterator<llvm::yaml::MappingNode, llvm::yaml::KeyValueNode>", scope: !110, file: !2332, line: 279, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4507, templateParams: !4542, identifier: "_ZTSN4llvm4yaml25basic_collection_iteratorINS0_11MappingNodeENS0_12KeyValueNodeEEE")
!4507 = !{!4508, !4517, !4518, !4522, !4525, !4530, !4533, !4534, !4538}
!4508 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4506, baseType: !4509, flags: DIFlagPublic, extraData: i32 0)
!4509 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::forward_iterator_tag, llvm::yaml::KeyValueNode, long, llvm::yaml::KeyValueNode *, llvm::yaml::KeyValueNode &>", scope: !192, file: !1357, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !320, templateParams: !4510, identifier: "_ZTSSt8iteratorISt20forward_iterator_tagN4llvm4yaml12KeyValueNodeElPS3_RS3_E")
!4510 = !{!4473, !4511, !2689, !4513, !4515}
!4511 = !DITemplateTypeParameter(name: "_Tp", type: !4512)
!4512 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "KeyValueNode", scope: !110, file: !2332, line: 236, size: 704, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm4yaml12KeyValueNodeE")
!4513 = !DITemplateTypeParameter(name: "_Pointer", type: !4514)
!4514 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4512, size: 64)
!4515 = !DITemplateTypeParameter(name: "_Reference", type: !4516)
!4516 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4512, size: 64)
!4517 = !DIDerivedType(tag: DW_TAG_member, name: "Base", scope: !4506, file: !2332, line: 318, baseType: !4451, size: 64)
!4518 = !DISubprogram(name: "basic_collection_iterator", scope: !4506, file: !2332, line: 282, type: !4519, scopeLine: 282, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4519 = !DISubroutineType(types: !4520)
!4520 = !{null, !4521}
!4521 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4506, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4522 = !DISubprogram(name: "basic_collection_iterator", scope: !4506, file: !2332, line: 283, type: !4523, scopeLine: 283, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4523 = !DISubroutineType(types: !4524)
!4524 = !{null, !4521, !4451}
!4525 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm4yaml25basic_collection_iteratorINS0_11MappingNodeENS0_12KeyValueNodeEEptEv", scope: !4506, file: !2332, line: 285, type: !4526, scopeLine: 285, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4526 = !DISubroutineType(types: !4527)
!4527 = !{!4514, !4528}
!4528 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4529, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4529 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4506)
!4530 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm4yaml25basic_collection_iteratorINS0_11MappingNodeENS0_12KeyValueNodeEEdeEv", scope: !4506, file: !2332, line: 290, type: !4531, scopeLine: 290, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4531 = !DISubroutineType(types: !4532)
!4532 = !{!4516, !4528}
!4533 = !DISubprogram(name: "operator llvm::yaml::KeyValueNode *", linkageName: "_ZNK4llvm4yaml25basic_collection_iteratorINS0_11MappingNodeENS0_12KeyValueNodeEEcvPS3_Ev", scope: !4506, file: !2332, line: 296, type: !4526, scopeLine: 296, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4534 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm4yaml25basic_collection_iteratorINS0_11MappingNodeENS0_12KeyValueNodeEEneERKS4_", scope: !4506, file: !2332, line: 301, type: !4535, scopeLine: 301, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4535 = !DISubroutineType(types: !4536)
!4536 = !{!132, !4528, !4537}
!4537 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4529, size: 64)
!4538 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm4yaml25basic_collection_iteratorINS0_11MappingNodeENS0_12KeyValueNodeEEppEv", scope: !4506, file: !2332, line: 308, type: !4539, scopeLine: 308, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4539 = !DISubroutineType(types: !4540)
!4540 = !{!4541, !4521}
!4541 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4506, size: 64)
!4542 = !{!4543, !4544}
!4543 = !DITemplateTypeParameter(name: "BaseT", type: !4445)
!4544 = !DITemplateTypeParameter(name: "ValueT", type: !4512)
!4545 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallString<128U>", scope: !14, file: !4546, line: 25, size: 1216, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4547, templateParams: !4658, identifier: "_ZTSN4llvm11SmallStringILj128EEE")
!4546 = !DIFile(filename: "llvm34/include/llvm/ADT/SmallString.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "2c780b02f5ec1f15da12c71ace03c232")
!4547 = !{!4548, !4583, !4587, !4590, !4595, !4598, !4599, !4602, !4603, !4604, !4605, !4609, !4610, !4613, !4614, !4615, !4616, !4617, !4620, !4623, !4624, !4627, !4628, !4629, !4630, !4631, !4632, !4633, !4636, !4637, !4640, !4641, !4644, !4647, !4648, !4651, !4655}
!4548 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4545, baseType: !4549, flags: DIFlagPublic, extraData: i32 0)
!4549 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<char, 128U>", scope: !14, file: !542, line: 880, size: 1216, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4550, templateParams: !4559, identifier: "_ZTSN4llvm11SmallVectorIcLj128EEE")
!4550 = !{!4551, !4552, !4561, !4565, !4568, !4573, !4576, !4580}
!4551 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4549, baseType: !541, flags: DIFlagPublic, extraData: i32 0)
!4552 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !4549, file: !542, line: 882, baseType: !4553, size: 1016, offset: 200)
!4553 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<char, 128U>", scope: !14, file: !542, line: 865, size: 1016, flags: DIFlagTypePassByValue, elements: !4554, templateParams: !4559, identifier: "_ZTSN4llvm18SmallVectorStorageIcLj128EEE")
!4554 = !{!4555}
!4555 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !4553, file: !542, line: 866, baseType: !4556, size: 1016)
!4556 = !DICompositeType(tag: DW_TAG_array_type, baseType: !573, size: 1016, elements: !4557)
!4557 = !{!4558}
!4558 = !DISubrange(count: 127)
!4559 = !{!674, !4560}
!4560 = !DITemplateValueParameter(name: "N", type: !6, value: i32 128)
!4561 = !DISubprogram(name: "SmallVector", scope: !4549, file: !542, line: 884, type: !4562, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4562 = !DISubroutineType(types: !4563)
!4563 = !{null, !4564}
!4564 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4549, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4565 = !DISubprogram(name: "SmallVector", scope: !4549, file: !542, line: 887, type: !4566, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4566 = !DISubroutineType(types: !4567)
!4567 = !{null, !4564, !6, !664}
!4568 = !DISubprogram(name: "SmallVector", scope: !4549, file: !542, line: 897, type: !4569, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4569 = !DISubroutineType(types: !4570)
!4570 = !{null, !4564, !4571}
!4571 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4572, size: 64)
!4572 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4549)
!4573 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIcLj128EEaSERKS1_", scope: !4549, file: !542, line: 902, type: !4574, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4574 = !DISubroutineType(types: !4575)
!4575 = !{!4571, !4564, !4571}
!4576 = !DISubprogram(name: "SmallVector", scope: !4549, file: !542, line: 908, type: !4577, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4577 = !DISubroutineType(types: !4578)
!4578 = !{null, !4564, !4579}
!4579 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !4549, size: 64)
!4580 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIcLj128EEaSEOS1_", scope: !4549, file: !542, line: 913, type: !4581, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4581 = !DISubroutineType(types: !4582)
!4582 = !{!4571, !4564, !4579}
!4583 = !DISubprogram(name: "SmallString", scope: !4545, file: !4546, line: 28, type: !4584, scopeLine: 28, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4584 = !DISubroutineType(types: !4585)
!4585 = !{null, !4586}
!4586 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4545, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4587 = !DISubprogram(name: "SmallString", scope: !4545, file: !4546, line: 31, type: !4588, scopeLine: 31, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4588 = !DISubroutineType(types: !4589)
!4589 = !{null, !4586, !154}
!4590 = !DISubprogram(name: "SmallString", scope: !4545, file: !4546, line: 38, type: !4591, scopeLine: 38, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4591 = !DISubroutineType(types: !4592)
!4592 = !{null, !4586, !4593}
!4593 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4594, size: 64)
!4594 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4545)
!4595 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj128EE6assignEmc", scope: !4545, file: !4546, line: 48, type: !4596, scopeLine: 48, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4596 = !DISubroutineType(types: !4597)
!4597 = !{null, !4586, !159, !165}
!4598 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj128EE6assignENS_9StringRefE", scope: !4545, file: !4546, line: 60, type: !4588, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4599 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj128EE6assignERKNS_15SmallVectorImplIcEE", scope: !4545, file: !4546, line: 66, type: !4600, scopeLine: 66, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4600 = !DISubroutineType(types: !4601)
!4601 = !{null, !4586, !696}
!4602 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj128EE6appendEmc", scope: !4545, file: !4546, line: 81, type: !4596, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4603 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj128EE6appendENS_9StringRefE", scope: !4545, file: !4546, line: 87, type: !4588, scopeLine: 87, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4604 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj128EE6appendERKNS_15SmallVectorImplIcEE", scope: !4545, file: !4546, line: 92, type: !4600, scopeLine: 92, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4605 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm11SmallStringILj128EE6equalsENS_9StringRefE", scope: !4545, file: !4546, line: 102, type: !4606, scopeLine: 102, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4606 = !DISubroutineType(types: !4607)
!4607 = !{!132, !4608, !154}
!4608 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4594, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4609 = !DISubprogram(name: "equals_lower", linkageName: "_ZNK4llvm11SmallStringILj128EE12equals_lowerENS_9StringRefE", scope: !4545, file: !4546, line: 107, type: !4606, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4610 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm11SmallStringILj128EE7compareENS_9StringRefE", scope: !4545, file: !4546, line: 113, type: !4611, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4611 = !DISubroutineType(types: !4612)
!4612 = !{!24, !4608, !154}
!4613 = !DISubprogram(name: "compare_lower", linkageName: "_ZNK4llvm11SmallStringILj128EE13compare_lowerENS_9StringRefE", scope: !4545, file: !4546, line: 118, type: !4611, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4614 = !DISubprogram(name: "compare_numeric", linkageName: "_ZNK4llvm11SmallStringILj128EE15compare_numericENS_9StringRefE", scope: !4545, file: !4546, line: 124, type: !4611, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4615 = !DISubprogram(name: "startswith", linkageName: "_ZNK4llvm11SmallStringILj128EE10startswithENS_9StringRefE", scope: !4545, file: !4546, line: 133, type: !4606, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4616 = !DISubprogram(name: "endswith", linkageName: "_ZNK4llvm11SmallStringILj128EE8endswithENS_9StringRefE", scope: !4545, file: !4546, line: 138, type: !4606, scopeLine: 138, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4617 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm11SmallStringILj128EE4findEcm", scope: !4545, file: !4546, line: 150, type: !4618, scopeLine: 150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4618 = !DISubroutineType(types: !4619)
!4619 = !{!159, !4608, !165, !159}
!4620 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm11SmallStringILj128EE4findENS_9StringRefEm", scope: !4545, file: !4546, line: 158, type: !4621, scopeLine: 158, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4621 = !DISubroutineType(types: !4622)
!4622 = !{!159, !4608, !154, !159}
!4623 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm11SmallStringILj128EE5rfindEcm", scope: !4545, file: !4546, line: 166, type: !4618, scopeLine: 166, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4624 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm11SmallStringILj128EE5rfindENS_9StringRefE", scope: !4545, file: !4546, line: 174, type: !4625, scopeLine: 174, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4625 = !DISubroutineType(types: !4626)
!4626 = !{!159, !4608, !154}
!4627 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm11SmallStringILj128EE13find_first_ofEcm", scope: !4545, file: !4546, line: 180, type: !4618, scopeLine: 180, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4628 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm11SmallStringILj128EE13find_first_ofENS_9StringRefEm", scope: !4545, file: !4546, line: 188, type: !4621, scopeLine: 188, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4629 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm11SmallStringILj128EE17find_first_not_ofEcm", scope: !4545, file: !4546, line: 194, type: !4618, scopeLine: 194, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4630 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm11SmallStringILj128EE17find_first_not_ofENS_9StringRefEm", scope: !4545, file: !4546, line: 202, type: !4621, scopeLine: 202, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4631 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm11SmallStringILj128EE12find_last_ofEcm", scope: !4545, file: !4546, line: 208, type: !4618, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4632 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm11SmallStringILj128EE12find_last_ofENS_9StringRefEm", scope: !4545, file: !4546, line: 216, type: !4621, scopeLine: 216, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4633 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm11SmallStringILj128EE5countEc", scope: !4545, file: !4546, line: 226, type: !4634, scopeLine: 226, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4634 = !DISubroutineType(types: !4635)
!4635 = !{!159, !4608, !165}
!4636 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm11SmallStringILj128EE5countENS_9StringRefE", scope: !4545, file: !4546, line: 232, type: !4625, scopeLine: 232, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4637 = !DISubprogram(name: "substr", linkageName: "_ZNK4llvm11SmallStringILj128EE6substrEmm", scope: !4545, file: !4546, line: 249, type: !4638, scopeLine: 249, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4638 = !DISubroutineType(types: !4639)
!4639 = !{!154, !4608, !159, !159}
!4640 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm11SmallStringILj128EE5sliceEmm", scope: !4545, file: !4546, line: 263, type: !4638, scopeLine: 263, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4641 = !DISubprogram(name: "str", linkageName: "_ZNK4llvm11SmallStringILj128EE3strEv", scope: !4545, file: !4546, line: 270, type: !4642, scopeLine: 270, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4642 = !DISubroutineType(types: !4643)
!4643 = !{!154, !4608}
!4644 = !DISubprogram(name: "c_str", linkageName: "_ZN4llvm11SmallStringILj128EE5c_strEv", scope: !4545, file: !4546, line: 273, type: !4645, scopeLine: 273, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4645 = !DISubroutineType(types: !4646)
!4646 = !{!163, !4586}
!4647 = !DISubprogram(name: "operator StringRef", linkageName: "_ZNK4llvm11SmallStringILj128EEcvNS_9StringRefEEv", scope: !4545, file: !4546, line: 280, type: !4642, scopeLine: 280, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4648 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallStringILj128EEaSENS_9StringRefE", scope: !4545, file: !4546, line: 283, type: !4649, scopeLine: 283, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4649 = !DISubroutineType(types: !4650)
!4650 = !{!4593, !4586, !154}
!4651 = !DISubprogram(name: "operator+=", linkageName: "_ZN4llvm11SmallStringILj128EEpLENS_9StringRefE", scope: !4545, file: !4546, line: 288, type: !4652, scopeLine: 288, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4652 = !DISubroutineType(types: !4653)
!4653 = !{!4654, !4586, !154}
!4654 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4545, size: 64)
!4655 = !DISubprogram(name: "operator+=", linkageName: "_ZN4llvm11SmallStringILj128EEpLEc", scope: !4545, file: !4546, line: 292, type: !4656, scopeLine: 292, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4656 = !DISubroutineType(types: !4657)
!4657 = !{!4654, !4586, !165}
!4658 = !{!4659}
!4659 = !DITemplateValueParameter(name: "InternalLen", type: !6, value: i32 128)
!4660 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "format_object1<double>", scope: !14, file: !4661, line: 80, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4662, vtableHolder: !4664, templateParams: !4678, identifier: "_ZTSN4llvm14format_object1IdEE")
!4661 = !DIFile(filename: "llvm34/include/llvm/Support/Format.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "bf2e6ec12853d45d6f2c7a5ded7a65be")
!4662 = !{!4663, !4665, !4667, !4673}
!4663 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4660, baseType: !4664, flags: DIFlagPublic, extraData: i32 0)
!4664 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "format_object_base", scope: !14, file: !4661, line: 41, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm18format_object_baseE")
!4665 = !DIDerivedType(tag: DW_TAG_member, name: "Val", scope: !4660, file: !4661, line: 81, baseType: !4666, size: 64, offset: 128)
!4666 = !DIBasicType(name: "double", size: 64, encoding: DW_ATE_float)
!4667 = !DISubprogram(name: "format_object1", scope: !4660, file: !4661, line: 83, type: !4668, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4668 = !DISubroutineType(types: !4669)
!4669 = !{null, !4670, !163, !4671}
!4670 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4660, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4671 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4672, size: 64)
!4672 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4666)
!4673 = !DISubprogram(name: "snprint", linkageName: "_ZNK4llvm14format_object1IdE7snprintEPcj", scope: !4660, file: !4661, line: 87, type: !4674, scopeLine: 87, containingType: !4660, virtualIndex: 1, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!4674 = !DISubroutineType(types: !4675)
!4675 = !{!24, !4676, !613, !6}
!4676 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4677, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4677 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4660)
!4678 = !{!4679}
!4679 = !DITemplateTypeParameter(name: "T", type: !4666)
!4680 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallString<32U>", scope: !14, file: !4546, line: 25, size: 448, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4681, templateParams: !4792, identifier: "_ZTSN4llvm11SmallStringILj32EEE")
!4681 = !{!4682, !4717, !4721, !4724, !4729, !4732, !4733, !4736, !4737, !4738, !4739, !4743, !4744, !4747, !4748, !4749, !4750, !4751, !4754, !4757, !4758, !4761, !4762, !4763, !4764, !4765, !4766, !4767, !4770, !4771, !4774, !4775, !4778, !4781, !4782, !4785, !4789}
!4682 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4680, baseType: !4683, flags: DIFlagPublic, extraData: i32 0)
!4683 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<char, 32U>", scope: !14, file: !542, line: 880, size: 448, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4684, templateParams: !4693, identifier: "_ZTSN4llvm11SmallVectorIcLj32EEE")
!4684 = !{!4685, !4686, !4695, !4699, !4702, !4707, !4710, !4714}
!4685 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4683, baseType: !541, flags: DIFlagPublic, extraData: i32 0)
!4686 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !4683, file: !542, line: 882, baseType: !4687, size: 248, offset: 200)
!4687 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<char, 32U>", scope: !14, file: !542, line: 865, size: 248, flags: DIFlagTypePassByValue, elements: !4688, templateParams: !4693, identifier: "_ZTSN4llvm18SmallVectorStorageIcLj32EEE")
!4688 = !{!4689}
!4689 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !4687, file: !542, line: 866, baseType: !4690, size: 248)
!4690 = !DICompositeType(tag: DW_TAG_array_type, baseType: !573, size: 248, elements: !4691)
!4691 = !{!4692}
!4692 = !DISubrange(count: 31)
!4693 = !{!674, !4694}
!4694 = !DITemplateValueParameter(name: "N", type: !6, value: i32 32)
!4695 = !DISubprogram(name: "SmallVector", scope: !4683, file: !542, line: 884, type: !4696, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4696 = !DISubroutineType(types: !4697)
!4697 = !{null, !4698}
!4698 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4683, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4699 = !DISubprogram(name: "SmallVector", scope: !4683, file: !542, line: 887, type: !4700, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4700 = !DISubroutineType(types: !4701)
!4701 = !{null, !4698, !6, !664}
!4702 = !DISubprogram(name: "SmallVector", scope: !4683, file: !542, line: 897, type: !4703, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4703 = !DISubroutineType(types: !4704)
!4704 = !{null, !4698, !4705}
!4705 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4706, size: 64)
!4706 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4683)
!4707 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIcLj32EEaSERKS1_", scope: !4683, file: !542, line: 902, type: !4708, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4708 = !DISubroutineType(types: !4709)
!4709 = !{!4705, !4698, !4705}
!4710 = !DISubprogram(name: "SmallVector", scope: !4683, file: !542, line: 908, type: !4711, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4711 = !DISubroutineType(types: !4712)
!4712 = !{null, !4698, !4713}
!4713 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !4683, size: 64)
!4714 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIcLj32EEaSEOS1_", scope: !4683, file: !542, line: 913, type: !4715, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4715 = !DISubroutineType(types: !4716)
!4716 = !{!4705, !4698, !4713}
!4717 = !DISubprogram(name: "SmallString", scope: !4680, file: !4546, line: 28, type: !4718, scopeLine: 28, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4718 = !DISubroutineType(types: !4719)
!4719 = !{null, !4720}
!4720 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4680, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4721 = !DISubprogram(name: "SmallString", scope: !4680, file: !4546, line: 31, type: !4722, scopeLine: 31, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4722 = !DISubroutineType(types: !4723)
!4723 = !{null, !4720, !154}
!4724 = !DISubprogram(name: "SmallString", scope: !4680, file: !4546, line: 38, type: !4725, scopeLine: 38, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4725 = !DISubroutineType(types: !4726)
!4726 = !{null, !4720, !4727}
!4727 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4728, size: 64)
!4728 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4680)
!4729 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj32EE6assignEmc", scope: !4680, file: !4546, line: 48, type: !4730, scopeLine: 48, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4730 = !DISubroutineType(types: !4731)
!4731 = !{null, !4720, !159, !165}
!4732 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj32EE6assignENS_9StringRefE", scope: !4680, file: !4546, line: 60, type: !4722, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4733 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj32EE6assignERKNS_15SmallVectorImplIcEE", scope: !4680, file: !4546, line: 66, type: !4734, scopeLine: 66, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4734 = !DISubroutineType(types: !4735)
!4735 = !{null, !4720, !696}
!4736 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj32EE6appendEmc", scope: !4680, file: !4546, line: 81, type: !4730, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4737 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj32EE6appendENS_9StringRefE", scope: !4680, file: !4546, line: 87, type: !4722, scopeLine: 87, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4738 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj32EE6appendERKNS_15SmallVectorImplIcEE", scope: !4680, file: !4546, line: 92, type: !4734, scopeLine: 92, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4739 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm11SmallStringILj32EE6equalsENS_9StringRefE", scope: !4680, file: !4546, line: 102, type: !4740, scopeLine: 102, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4740 = !DISubroutineType(types: !4741)
!4741 = !{!132, !4742, !154}
!4742 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4728, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4743 = !DISubprogram(name: "equals_lower", linkageName: "_ZNK4llvm11SmallStringILj32EE12equals_lowerENS_9StringRefE", scope: !4680, file: !4546, line: 107, type: !4740, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4744 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm11SmallStringILj32EE7compareENS_9StringRefE", scope: !4680, file: !4546, line: 113, type: !4745, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4745 = !DISubroutineType(types: !4746)
!4746 = !{!24, !4742, !154}
!4747 = !DISubprogram(name: "compare_lower", linkageName: "_ZNK4llvm11SmallStringILj32EE13compare_lowerENS_9StringRefE", scope: !4680, file: !4546, line: 118, type: !4745, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4748 = !DISubprogram(name: "compare_numeric", linkageName: "_ZNK4llvm11SmallStringILj32EE15compare_numericENS_9StringRefE", scope: !4680, file: !4546, line: 124, type: !4745, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4749 = !DISubprogram(name: "startswith", linkageName: "_ZNK4llvm11SmallStringILj32EE10startswithENS_9StringRefE", scope: !4680, file: !4546, line: 133, type: !4740, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4750 = !DISubprogram(name: "endswith", linkageName: "_ZNK4llvm11SmallStringILj32EE8endswithENS_9StringRefE", scope: !4680, file: !4546, line: 138, type: !4740, scopeLine: 138, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4751 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm11SmallStringILj32EE4findEcm", scope: !4680, file: !4546, line: 150, type: !4752, scopeLine: 150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4752 = !DISubroutineType(types: !4753)
!4753 = !{!159, !4742, !165, !159}
!4754 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm11SmallStringILj32EE4findENS_9StringRefEm", scope: !4680, file: !4546, line: 158, type: !4755, scopeLine: 158, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4755 = !DISubroutineType(types: !4756)
!4756 = !{!159, !4742, !154, !159}
!4757 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm11SmallStringILj32EE5rfindEcm", scope: !4680, file: !4546, line: 166, type: !4752, scopeLine: 166, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4758 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm11SmallStringILj32EE5rfindENS_9StringRefE", scope: !4680, file: !4546, line: 174, type: !4759, scopeLine: 174, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4759 = !DISubroutineType(types: !4760)
!4760 = !{!159, !4742, !154}
!4761 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm11SmallStringILj32EE13find_first_ofEcm", scope: !4680, file: !4546, line: 180, type: !4752, scopeLine: 180, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4762 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm11SmallStringILj32EE13find_first_ofENS_9StringRefEm", scope: !4680, file: !4546, line: 188, type: !4755, scopeLine: 188, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4763 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm11SmallStringILj32EE17find_first_not_ofEcm", scope: !4680, file: !4546, line: 194, type: !4752, scopeLine: 194, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4764 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm11SmallStringILj32EE17find_first_not_ofENS_9StringRefEm", scope: !4680, file: !4546, line: 202, type: !4755, scopeLine: 202, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4765 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm11SmallStringILj32EE12find_last_ofEcm", scope: !4680, file: !4546, line: 208, type: !4752, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4766 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm11SmallStringILj32EE12find_last_ofENS_9StringRefEm", scope: !4680, file: !4546, line: 216, type: !4755, scopeLine: 216, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4767 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm11SmallStringILj32EE5countEc", scope: !4680, file: !4546, line: 226, type: !4768, scopeLine: 226, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4768 = !DISubroutineType(types: !4769)
!4769 = !{!159, !4742, !165}
!4770 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm11SmallStringILj32EE5countENS_9StringRefE", scope: !4680, file: !4546, line: 232, type: !4759, scopeLine: 232, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4771 = !DISubprogram(name: "substr", linkageName: "_ZNK4llvm11SmallStringILj32EE6substrEmm", scope: !4680, file: !4546, line: 249, type: !4772, scopeLine: 249, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4772 = !DISubroutineType(types: !4773)
!4773 = !{!154, !4742, !159, !159}
!4774 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm11SmallStringILj32EE5sliceEmm", scope: !4680, file: !4546, line: 263, type: !4772, scopeLine: 263, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4775 = !DISubprogram(name: "str", linkageName: "_ZNK4llvm11SmallStringILj32EE3strEv", scope: !4680, file: !4546, line: 270, type: !4776, scopeLine: 270, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4776 = !DISubroutineType(types: !4777)
!4777 = !{!154, !4742}
!4778 = !DISubprogram(name: "c_str", linkageName: "_ZN4llvm11SmallStringILj32EE5c_strEv", scope: !4680, file: !4546, line: 273, type: !4779, scopeLine: 273, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4779 = !DISubroutineType(types: !4780)
!4780 = !{!163, !4720}
!4781 = !DISubprogram(name: "operator StringRef", linkageName: "_ZNK4llvm11SmallStringILj32EEcvNS_9StringRefEEv", scope: !4680, file: !4546, line: 280, type: !4776, scopeLine: 280, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4782 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallStringILj32EEaSENS_9StringRefE", scope: !4680, file: !4546, line: 283, type: !4783, scopeLine: 283, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4783 = !DISubroutineType(types: !4784)
!4784 = !{!4727, !4720, !154}
!4785 = !DISubprogram(name: "operator+=", linkageName: "_ZN4llvm11SmallStringILj32EEpLENS_9StringRefE", scope: !4680, file: !4546, line: 288, type: !4786, scopeLine: 288, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4786 = !DISubroutineType(types: !4787)
!4787 = !{!4788, !4720, !154}
!4788 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4680, size: 64)
!4789 = !DISubprogram(name: "operator+=", linkageName: "_ZN4llvm11SmallStringILj32EEpLEc", scope: !4680, file: !4546, line: 292, type: !4790, scopeLine: 292, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4790 = !DISubroutineType(types: !4791)
!4791 = !{!4788, !4720, !165}
!4792 = !{!4793}
!4793 = !DITemplateValueParameter(name: "InternalLen", type: !6, value: i32 32)
!4794 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "format_object1<float>", scope: !14, file: !4661, line: 80, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4795, vtableHolder: !4664, templateParams: !4810, identifier: "_ZTSN4llvm14format_object1IfEE")
!4795 = !{!4796, !4797, !4799, !4805}
!4796 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4794, baseType: !4664, flags: DIFlagPublic, extraData: i32 0)
!4797 = !DIDerivedType(tag: DW_TAG_member, name: "Val", scope: !4794, file: !4661, line: 81, baseType: !4798, size: 32, offset: 128)
!4798 = !DIBasicType(name: "float", size: 32, encoding: DW_ATE_float)
!4799 = !DISubprogram(name: "format_object1", scope: !4794, file: !4661, line: 83, type: !4800, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4800 = !DISubroutineType(types: !4801)
!4801 = !{null, !4802, !163, !4803}
!4802 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4794, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4803 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4804, size: 64)
!4804 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4798)
!4805 = !DISubprogram(name: "snprint", linkageName: "_ZNK4llvm14format_object1IfE7snprintEPcj", scope: !4794, file: !4661, line: 87, type: !4806, scopeLine: 87, containingType: !4794, virtualIndex: 1, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!4806 = !DISubroutineType(types: !4807)
!4807 = !{!24, !4808, !613, !6}
!4808 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4809, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4809 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4794)
!4810 = !{!4811}
!4811 = !DITemplateTypeParameter(name: "T", type: !4798)
!4812 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "format_object1<unsigned char>", scope: !14, file: !4661, line: 80, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4813, vtableHolder: !4664, templateParams: !4827, identifier: "_ZTSN4llvm14format_object1IhEE")
!4813 = !{!4814, !4815, !4816, !4822}
!4814 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4812, baseType: !4664, flags: DIFlagPublic, extraData: i32 0)
!4815 = !DIDerivedType(tag: DW_TAG_member, name: "Val", scope: !4812, file: !4661, line: 81, baseType: !423, size: 8, offset: 128)
!4816 = !DISubprogram(name: "format_object1", scope: !4812, file: !4661, line: 83, type: !4817, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4817 = !DISubroutineType(types: !4818)
!4818 = !{null, !4819, !163, !4820}
!4819 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4812, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4820 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4821, size: 64)
!4821 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !423)
!4822 = !DISubprogram(name: "snprint", linkageName: "_ZNK4llvm14format_object1IhE7snprintEPcj", scope: !4812, file: !4661, line: 87, type: !4823, scopeLine: 87, containingType: !4812, virtualIndex: 1, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!4823 = !DISubroutineType(types: !4824)
!4824 = !{!24, !4825, !613, !6}
!4825 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4826, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4826 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4812)
!4827 = !{!4828}
!4828 = !DITemplateTypeParameter(name: "T", type: !423)
!4829 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "format_object1<unsigned short>", scope: !14, file: !4661, line: 80, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4830, vtableHolder: !4664, templateParams: !4845, identifier: "_ZTSN4llvm14format_object1ItEE")
!4830 = !{!4831, !4832, !4834, !4840}
!4831 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4829, baseType: !4664, flags: DIFlagPublic, extraData: i32 0)
!4832 = !DIDerivedType(tag: DW_TAG_member, name: "Val", scope: !4829, file: !4661, line: 81, baseType: !4833, size: 16, offset: 128)
!4833 = !DIBasicType(name: "unsigned short", size: 16, encoding: DW_ATE_unsigned)
!4834 = !DISubprogram(name: "format_object1", scope: !4829, file: !4661, line: 83, type: !4835, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4835 = !DISubroutineType(types: !4836)
!4836 = !{null, !4837, !163, !4838}
!4837 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4829, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4838 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4839, size: 64)
!4839 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4833)
!4840 = !DISubprogram(name: "snprint", linkageName: "_ZNK4llvm14format_object1ItE7snprintEPcj", scope: !4829, file: !4661, line: 87, type: !4841, scopeLine: 87, containingType: !4829, virtualIndex: 1, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!4841 = !DISubroutineType(types: !4842)
!4842 = !{!24, !4843, !613, !6}
!4843 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4844, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4844 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4829)
!4845 = !{!4846}
!4846 = !DITemplateTypeParameter(name: "T", type: !4833)
!4847 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "format_object1<unsigned int>", scope: !14, file: !4661, line: 80, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4848, vtableHolder: !4664, templateParams: !4862, identifier: "_ZTSN4llvm14format_object1IjEE")
!4848 = !{!4849, !4850, !4851, !4857}
!4849 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4847, baseType: !4664, flags: DIFlagPublic, extraData: i32 0)
!4850 = !DIDerivedType(tag: DW_TAG_member, name: "Val", scope: !4847, file: !4661, line: 81, baseType: !6, size: 32, offset: 128)
!4851 = !DISubprogram(name: "format_object1", scope: !4847, file: !4661, line: 83, type: !4852, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4852 = !DISubroutineType(types: !4853)
!4853 = !{null, !4854, !163, !4855}
!4854 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4847, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4855 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4856, size: 64)
!4856 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6)
!4857 = !DISubprogram(name: "snprint", linkageName: "_ZNK4llvm14format_object1IjE7snprintEPcj", scope: !4847, file: !4661, line: 87, type: !4858, scopeLine: 87, containingType: !4847, virtualIndex: 1, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!4858 = !DISubroutineType(types: !4859)
!4859 = !{!24, !4860, !613, !6}
!4860 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4861, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4861 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4847)
!4862 = !{!4863}
!4863 = !DITemplateTypeParameter(name: "T", type: !6)
!4864 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "format_object1<unsigned long>", scope: !14, file: !4661, line: 80, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4865, vtableHolder: !4664, templateParams: !4877, identifier: "_ZTSN4llvm14format_object1ImEE")
!4865 = !{!4866, !4867, !4868, !4872}
!4866 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4864, baseType: !4664, flags: DIFlagPublic, extraData: i32 0)
!4867 = !DIDerivedType(tag: DW_TAG_member, name: "Val", scope: !4864, file: !4661, line: 81, baseType: !161, size: 64, offset: 128)
!4868 = !DISubprogram(name: "format_object1", scope: !4864, file: !4661, line: 83, type: !4869, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4869 = !DISubroutineType(types: !4870)
!4870 = !{null, !4871, !163, !503}
!4871 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4864, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4872 = !DISubprogram(name: "snprint", linkageName: "_ZNK4llvm14format_object1ImE7snprintEPcj", scope: !4864, file: !4661, line: 87, type: !4873, scopeLine: 87, containingType: !4864, virtualIndex: 1, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!4873 = !DISubroutineType(types: !4874)
!4874 = !{!24, !4875, !613, !6}
!4875 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4876, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4876 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4864)
!4877 = !{!4878}
!4878 = !DITemplateTypeParameter(name: "T", type: !161)
!4879 = !{!4880, !4884, !4889, !4894, !4899, !4904, !4909, !4914, !4916, !4921, !4923, !4928, !4930, !4935, !4940, !4942, !4944, !4949, !4954, !4956, !4958, !4961, !4964, !4969, !4974, !4976, !4978, !4980, !4982, !4984, !4986, !4991, !4996, !4998, !5000, !5005, !5007, !5009, !5014, !5019, !5024, !5026, !5031, !5034, !5036, !5041, !5043, !5048, !5050, !5052, !5054, !5056, !5061, !5063, !5068, !5070, !5072, !5077, !5079, !5081, !5086, !5091, !5096, !5101, !5103, !5105, !5107, !5110, !5115, !5120, !5122, !5127, !5132, !5137, !5139, !5144, !5149, !5154, !5159, !5161, !5166, !5168, !5170, !5172, !5177, !5182, !5184, !5189, !5194, !5196, !5201, !5206, !5211, !5213, !5218, !5223, !5228, !5233, !5238, !5241, !5246, !5248, !5250, !5252, !5254, !5259, !5264, !5266, !5268, !5273, !5275, !5277, !5279, !5281, !5286, !5291, !5296, !5301, !5306}
!4880 = !DIGlobalVariableExpression(var: !4881, expr: !DIExpression())
!4881 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 76, type: !4883, isLocal: true, isDefinition: true)
!4882 = !DIFile(filename: "llvm34/lib/Support/YAMLTraits.cpp", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "f31e6409b6fed9b737ded9800de56e42")
!4883 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 256, elements: !3325)
!4884 = !DIGlobalVariableExpression(var: !4885, expr: !DIExpression())
!4885 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 76, type: !4886, isLocal: true, isDefinition: true)
!4886 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 416, elements: !4887)
!4887 = !{!4888}
!4888 = !DISubrange(count: 52)
!4889 = !DIGlobalVariableExpression(var: !4890, expr: !DIExpression())
!4890 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 76, type: !4891, isLocal: true, isDefinition: true)
!4891 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 344, elements: !4892)
!4892 = !{!4893}
!4893 = !DISubrange(count: 43)
!4894 = !DIGlobalVariableExpression(var: !4895, expr: !DIExpression())
!4895 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 76, type: !4896, isLocal: true, isDefinition: true)
!4896 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 360, elements: !4897)
!4897 = !{!4898}
!4898 = !DISubrange(count: 45)
!4899 = !DIGlobalVariableExpression(var: !4900, expr: !DIExpression())
!4900 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 133, type: !4901, isLocal: true, isDefinition: true)
!4901 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 112, elements: !4902)
!4902 = !{!4903}
!4903 = !DISubrange(count: 14)
!4904 = !DIGlobalVariableExpression(var: !4905, expr: !DIExpression())
!4905 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 140, type: !4906, isLocal: true, isDefinition: true)
!4906 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 184, elements: !4907)
!4907 = !{!4908}
!4908 = !DISubrange(count: 23)
!4909 = !DIGlobalVariableExpression(var: !4910, expr: !DIExpression())
!4910 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 140, type: !4911, isLocal: true, isDefinition: true)
!4911 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 16, elements: !4912)
!4912 = !{!4913}
!4913 = !DISubrange(count: 2)
!4914 = !DIGlobalVariableExpression(var: !4915, expr: !DIExpression())
!4915 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 164, type: !4901, isLocal: true, isDefinition: true)
!4916 = !DIGlobalVariableExpression(var: !4917, expr: !DIExpression())
!4917 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 238, type: !4918, isLocal: true, isDefinition: true)
!4918 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 208, elements: !4919)
!4919 = !{!4920}
!4920 = !DISubrange(count: 26)
!4921 = !DIGlobalVariableExpression(var: !4922, expr: !DIExpression())
!4922 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 247, type: !4883, isLocal: true, isDefinition: true)
!4923 = !DIGlobalVariableExpression(var: !4924, expr: !DIExpression())
!4924 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 266, type: !4925, isLocal: true, isDefinition: true)
!4925 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 352, elements: !4926)
!4926 = !{!4927}
!4927 = !DISubrange(count: 44)
!4928 = !DIGlobalVariableExpression(var: !4929, expr: !DIExpression())
!4929 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 280, type: !4891, isLocal: true, isDefinition: true)
!4930 = !DIGlobalVariableExpression(var: !4931, expr: !DIExpression())
!4931 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 280, type: !4932, isLocal: true, isDefinition: true)
!4932 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 400, elements: !4933)
!4933 = !{!4934}
!4934 = !DISubrange(count: 50)
!4935 = !DIGlobalVariableExpression(var: !4936, expr: !DIExpression())
!4936 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 283, type: !4937, isLocal: true, isDefinition: true)
!4937 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 144, elements: !4938)
!4938 = !{!4939}
!4939 = !DISubrange(count: 18)
!4940 = !DIGlobalVariableExpression(var: !4941, expr: !DIExpression())
!4941 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 294, type: !4937, isLocal: true, isDefinition: true)
!4942 = !DIGlobalVariableExpression(var: !4943, expr: !DIExpression())
!4943 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 299, type: !4906, isLocal: true, isDefinition: true)
!4944 = !DIGlobalVariableExpression(var: !4945, expr: !DIExpression())
!4945 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 299, type: !4946, isLocal: true, isDefinition: true)
!4946 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 272, elements: !4947)
!4947 = !{!4948}
!4948 = !DISubrange(count: 34)
!4949 = !DIGlobalVariableExpression(var: !4950, expr: !DIExpression())
!4950 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 299, type: !4951, isLocal: true, isDefinition: true)
!4951 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 656, elements: !4952)
!4952 = !{!4953}
!4953 = !DISubrange(count: 82)
!4954 = !DIGlobalVariableExpression(var: !4955, expr: !DIExpression())
!4955 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 353, type: !4937, isLocal: true, isDefinition: true)
!4956 = !DIGlobalVariableExpression(var: !4957, expr: !DIExpression())
!4957 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 420, type: !4911, isLocal: true, isDefinition: true)
!4958 = !DIGlobalVariableExpression(var: !4959, expr: !DIExpression())
!4959 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 449, type: !4960, isLocal: true, isDefinition: true)
!4960 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 32, elements: !796)
!4961 = !DIGlobalVariableExpression(var: !4962, expr: !DIExpression())
!4962 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 454, type: !4963, isLocal: true, isDefinition: true)
!4963 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 40, elements: !4006)
!4964 = !DIGlobalVariableExpression(var: !4965, expr: !DIExpression())
!4965 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 462, type: !4966, isLocal: true, isDefinition: true)
!4966 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 48, elements: !4967)
!4967 = !{!4968}
!4968 = !DISubrange(count: 6)
!4969 = !DIGlobalVariableExpression(var: !4970, expr: !DIExpression())
!4970 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 486, type: !4971, isLocal: true, isDefinition: true)
!4971 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 24, elements: !4972)
!4972 = !{!4973}
!4973 = !DISubrange(count: 3)
!4974 = !DIGlobalVariableExpression(var: !4975, expr: !DIExpression())
!4975 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 493, type: !4971, isLocal: true, isDefinition: true)
!4976 = !DIGlobalVariableExpression(var: !4977, expr: !DIExpression())
!4977 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 498, type: !4971, isLocal: true, isDefinition: true)
!4978 = !DIGlobalVariableExpression(var: !4979, expr: !DIExpression())
!4979 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 500, type: !4911, isLocal: true, isDefinition: true)
!4980 = !DIGlobalVariableExpression(var: !4981, expr: !DIExpression())
!4981 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 504, type: !4971, isLocal: true, isDefinition: true)
!4982 = !DIGlobalVariableExpression(var: !4983, expr: !DIExpression())
!4983 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 528, type: !4906, isLocal: true, isDefinition: true)
!4984 = !DIGlobalVariableExpression(var: !4985, expr: !DIExpression())
!4985 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 561, type: !4971, isLocal: true, isDefinition: true)
!4986 = !DIGlobalVariableExpression(var: !4987, expr: !DIExpression())
!4987 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 632, type: !4988, isLocal: true, isDefinition: true)
!4988 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 176, elements: !4989)
!4989 = !{!4990}
!4990 = !DISubrange(count: 22)
!4991 = !DIGlobalVariableExpression(var: !4992, expr: !DIExpression())
!4992 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 632, type: !4993, isLocal: true, isDefinition: true)
!4993 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 320, elements: !4994)
!4994 = !{!4995}
!4995 = !DISubrange(count: 40)
!4996 = !DIGlobalVariableExpression(var: !4997, expr: !DIExpression())
!4997 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 648, type: !4971, isLocal: true, isDefinition: true)
!4998 = !DIGlobalVariableExpression(var: !4999, expr: !DIExpression())
!4999 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 655, type: !4911, isLocal: true, isDefinition: true)
!5000 = !DIGlobalVariableExpression(var: !5001, expr: !DIExpression())
!5001 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 656, type: !5002, isLocal: true, isDefinition: true)
!5002 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 136, elements: !5003)
!5003 = !{!5004}
!5004 = !DISubrange(count: 17)
!5005 = !DIGlobalVariableExpression(var: !5006, expr: !DIExpression())
!5006 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 668, type: !4963, isLocal: true, isDefinition: true)
!5007 = !DIGlobalVariableExpression(var: !5008, expr: !DIExpression())
!5008 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 668, type: !4966, isLocal: true, isDefinition: true)
!5009 = !DIGlobalVariableExpression(var: !5010, expr: !DIExpression())
!5010 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 679, type: !5011, isLocal: true, isDefinition: true)
!5011 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 128, elements: !5012)
!5012 = !{!5013}
!5013 = !DISubrange(count: 16)
!5014 = !DIGlobalVariableExpression(var: !5015, expr: !DIExpression())
!5015 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 703, type: !5016, isLocal: true, isDefinition: true)
!5016 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 120, elements: !5017)
!5017 = !{!5018}
!5018 = !DISubrange(count: 15)
!5019 = !DIGlobalVariableExpression(var: !5020, expr: !DIExpression())
!5020 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 705, type: !5021, isLocal: true, isDefinition: true)
!5021 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 160, elements: !5022)
!5022 = !{!5023}
!5023 = !DISubrange(count: 20)
!5024 = !DIGlobalVariableExpression(var: !5025, expr: !DIExpression())
!5025 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 816, type: !4971, isLocal: true, isDefinition: true)
!5026 = !DIGlobalVariableExpression(var: !5027, expr: !DIExpression())
!5027 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 824, type: !5028, isLocal: true, isDefinition: true)
!5028 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 240, elements: !5029)
!5029 = !{!5030}
!5030 = !DISubrange(count: 30)
!5031 = !DIGlobalVariableExpression(var: !5032, expr: !DIExpression())
!5032 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 843, type: !5033, isLocal: true, isDefinition: true)
!5033 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 56, elements: !966)
!5034 = !DIGlobalVariableExpression(var: !5035, expr: !DIExpression())
!5035 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 849, type: !5021, isLocal: true, isDefinition: true)
!5036 = !DIGlobalVariableExpression(var: !5037, expr: !DIExpression())
!5037 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 851, type: !5038, isLocal: true, isDefinition: true)
!5038 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 200, elements: !5039)
!5039 = !{!5040}
!5040 = !DISubrange(count: 25)
!5041 = !DIGlobalVariableExpression(var: !5042, expr: !DIExpression())
!5042 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 858, type: !5033, isLocal: true, isDefinition: true)
!5043 = !DIGlobalVariableExpression(var: !5044, expr: !DIExpression())
!5044 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 864, type: !5045, isLocal: true, isDefinition: true)
!5045 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 168, elements: !5046)
!5046 = !{!5047}
!5047 = !DISubrange(count: 21)
!5048 = !DIGlobalVariableExpression(var: !5049, expr: !DIExpression())
!5049 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 866, type: !4918, isLocal: true, isDefinition: true)
!5050 = !DIGlobalVariableExpression(var: !5051, expr: !DIExpression())
!5051 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 873, type: !5033, isLocal: true, isDefinition: true)
!5052 = !DIGlobalVariableExpression(var: !5053, expr: !DIExpression())
!5053 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 879, type: !5045, isLocal: true, isDefinition: true)
!5054 = !DIGlobalVariableExpression(var: !5055, expr: !DIExpression())
!5055 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 881, type: !4918, isLocal: true, isDefinition: true)
!5056 = !DIGlobalVariableExpression(var: !5057, expr: !DIExpression())
!5057 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 888, type: !5058, isLocal: true, isDefinition: true)
!5058 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 80, elements: !5059)
!5059 = !{!5060}
!5060 = !DISubrange(count: 10)
!5061 = !DIGlobalVariableExpression(var: !5062, expr: !DIExpression())
!5062 = distinct !DIGlobalVariable(scope: null, file: !4882, line: 894, type: !5045, isLocal: true, isDefinition: true)
!5063 = !DIGlobalVariableExpression(var: !5064, expr: !DIExpression())
!5064 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 548, type: !5065, isLocal: true, isDefinition: true)
!5065 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 288, elements: !5066)
!5066 = !{!5067}
!5067 = !DISubrange(count: 36)
!5068 = !DIGlobalVariableExpression(var: !5069, expr: !DIExpression())
!5069 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 548, type: !4932, isLocal: true, isDefinition: true)
!5070 = !DIGlobalVariableExpression(var: !5071, expr: !DIExpression())
!5071 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 548, type: !4932, isLocal: true, isDefinition: true)
!5072 = !DIGlobalVariableExpression(var: !5073, expr: !DIExpression())
!5073 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 548, type: !5074, isLocal: true, isDefinition: true)
!5074 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 592, elements: !5075)
!5075 = !{!5076}
!5076 = !DISubrange(count: 74)
!5077 = !DIGlobalVariableExpression(var: !5078, expr: !DIExpression())
!5078 = distinct !DIGlobalVariable(scope: null, file: !384, line: 271, type: !5016, isLocal: true, isDefinition: true)
!5079 = !DIGlobalVariableExpression(var: !5080, expr: !DIExpression())
!5080 = distinct !DIGlobalVariable(scope: null, file: !384, line: 271, type: !5028, isLocal: true, isDefinition: true)
!5081 = !DIGlobalVariableExpression(var: !5082, expr: !DIExpression())
!5082 = distinct !DIGlobalVariable(scope: null, file: !384, line: 271, type: !5083, isLocal: true, isDefinition: true)
!5083 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 328, elements: !5084)
!5084 = !{!5085}
!5085 = !DISubrange(count: 41)
!5086 = !DIGlobalVariableExpression(var: !5087, expr: !DIExpression())
!5087 = distinct !DIGlobalVariable(scope: null, file: !384, line: 271, type: !5088, isLocal: true, isDefinition: true)
!5088 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 264, elements: !5089)
!5089 = !{!5090}
!5090 = !DISubrange(count: 33)
!5091 = !DIGlobalVariableExpression(var: !5092, expr: !DIExpression())
!5092 = distinct !DIGlobalVariable(scope: null, file: !155, line: 78, type: !5093, isLocal: true, isDefinition: true)
!5093 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 376, elements: !5094)
!5094 = !{!5095}
!5095 = !DISubrange(count: 47)
!5096 = !DIGlobalVariableExpression(var: !5097, expr: !DIExpression())
!5097 = distinct !DIGlobalVariable(scope: null, file: !155, line: 78, type: !5098, isLocal: true, isDefinition: true)
!5098 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 448, elements: !5099)
!5099 = !{!5100}
!5100 = !DISubrange(count: 56)
!5101 = !DIGlobalVariableExpression(var: !5102, expr: !DIExpression())
!5102 = distinct !DIGlobalVariable(scope: null, file: !155, line: 78, type: !4896, isLocal: true, isDefinition: true)
!5103 = !DIGlobalVariableExpression(var: !5104, expr: !DIExpression())
!5104 = distinct !DIGlobalVariable(scope: null, file: !155, line: 78, type: !5083, isLocal: true, isDefinition: true)
!5105 = !DIGlobalVariableExpression(var: !5106, expr: !DIExpression())
!5106 = distinct !DIGlobalVariable(scope: null, file: !384, line: 167, type: !4901, isLocal: true, isDefinition: true)
!5107 = !DIGlobalVariableExpression(var: !5108, expr: !DIExpression())
!5108 = distinct !DIGlobalVariable(scope: null, file: !384, line: 167, type: !5109, isLocal: true, isDefinition: true)
!5109 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 248, elements: !4691)
!5110 = !DIGlobalVariableExpression(var: !5111, expr: !DIExpression())
!5111 = distinct !DIGlobalVariable(scope: null, file: !384, line: 167, type: !5112, isLocal: true, isDefinition: true)
!5112 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 336, elements: !5113)
!5113 = !{!5114}
!5114 = !DISubrange(count: 42)
!5115 = !DIGlobalVariableExpression(var: !5116, expr: !DIExpression())
!5116 = distinct !DIGlobalVariable(scope: null, file: !384, line: 182, type: !5117, isLocal: true, isDefinition: true)
!5117 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 840, elements: !5118)
!5118 = !{!5119}
!5119 = !DISubrange(count: 105)
!5120 = !DIGlobalVariableExpression(var: !5121, expr: !DIExpression())
!5121 = distinct !DIGlobalVariable(scope: null, file: !384, line: 285, type: !4925, isLocal: true, isDefinition: true)
!5122 = !DIGlobalVariableExpression(var: !5123, expr: !DIExpression())
!5123 = distinct !DIGlobalVariable(scope: null, file: !155, line: 85, type: !5124, isLocal: true, isDefinition: true)
!5124 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 544, elements: !5125)
!5125 = !{!5126}
!5126 = !DISubrange(count: 68)
!5127 = !DIGlobalVariableExpression(var: !5128, expr: !DIExpression())
!5128 = distinct !DIGlobalVariable(scope: null, file: !155, line: 85, type: !5129, isLocal: true, isDefinition: true)
!5129 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 760, elements: !5130)
!5130 = !{!5131}
!5131 = !DISubrange(count: 95)
!5132 = !DIGlobalVariableExpression(var: !5133, expr: !DIExpression())
!5133 = distinct !DIGlobalVariable(scope: null, file: !155, line: 85, type: !5134, isLocal: true, isDefinition: true)
!5134 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 392, elements: !5135)
!5135 = !{!5136}
!5136 = !DISubrange(count: 49)
!5137 = !DIGlobalVariableExpression(var: !5138, expr: !DIExpression())
!5138 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 324, type: !4896, isLocal: true, isDefinition: true)
!5139 = !DIGlobalVariableExpression(var: !5140, expr: !DIExpression())
!5140 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 324, type: !5141, isLocal: true, isDefinition: true)
!5141 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 528, elements: !5142)
!5142 = !{!5143}
!5143 = !DISubrange(count: 66)
!5144 = !DIGlobalVariableExpression(var: !5145, expr: !DIExpression())
!5145 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 324, type: !5146, isLocal: true, isDefinition: true)
!5146 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 912, elements: !5147)
!5147 = !{!5148}
!5148 = !DISubrange(count: 114)
!5149 = !DIGlobalVariableExpression(var: !5150, expr: !DIExpression())
!5150 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 324, type: !5151, isLocal: true, isDefinition: true)
!5151 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 904, elements: !5152)
!5152 = !{!5153}
!5153 = !DISubrange(count: 113)
!5154 = !DIGlobalVariableExpression(var: !5155, expr: !DIExpression())
!5155 = distinct !DIGlobalVariable(scope: null, file: !155, line: 117, type: !5156, isLocal: true, isDefinition: true)
!5156 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 72, elements: !5157)
!5157 = !{!5158}
!5158 = !DISubrange(count: 9)
!5159 = !DIGlobalVariableExpression(var: !5160, expr: !DIExpression())
!5160 = distinct !DIGlobalVariable(scope: null, file: !155, line: 117, type: !5065, isLocal: true, isDefinition: true)
!5161 = !DIGlobalVariableExpression(var: !5162, expr: !DIExpression())
!5162 = distinct !DIGlobalVariable(scope: null, file: !155, line: 123, type: !5163, isLocal: true, isDefinition: true)
!5163 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 280, elements: !5164)
!5164 = !{!5165}
!5165 = !DISubrange(count: 35)
!5166 = !DIGlobalVariableExpression(var: !5167, expr: !DIExpression())
!5167 = distinct !DIGlobalVariable(scope: null, file: !155, line: 191, type: !5016, isLocal: true, isDefinition: true)
!5168 = !DIGlobalVariableExpression(var: !5169, expr: !DIExpression())
!5169 = distinct !DIGlobalVariable(scope: null, file: !155, line: 191, type: !5163, isLocal: true, isDefinition: true)
!5170 = !DIGlobalVariableExpression(var: !5171, expr: !DIExpression())
!5171 = distinct !DIGlobalVariable(scope: null, file: !155, line: 191, type: !5093, isLocal: true, isDefinition: true)
!5172 = !DIGlobalVariableExpression(var: !5173, expr: !DIExpression())
!5173 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 97, type: !5174, isLocal: true, isDefinition: true)
!5174 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 232, elements: !5175)
!5175 = !{!5176}
!5176 = !DISubrange(count: 29)
!5177 = !DIGlobalVariableExpression(var: !5178, expr: !DIExpression())
!5178 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 97, type: !5179, isLocal: true, isDefinition: true)
!5179 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 304, elements: !5180)
!5180 = !{!5181}
!5181 = !DISubrange(count: 38)
!5182 = !DIGlobalVariableExpression(var: !5183, expr: !DIExpression())
!5183 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 97, type: !5093, isLocal: true, isDefinition: true)
!5184 = !DIGlobalVariableExpression(var: !5185, expr: !DIExpression())
!5185 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 97, type: !5186, isLocal: true, isDefinition: true)
!5186 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 1272, elements: !5187)
!5187 = !{!5188}
!5188 = !DISubrange(count: 159)
!5189 = !DIGlobalVariableExpression(var: !5190, expr: !DIExpression())
!5190 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 97, type: !5191, isLocal: true, isDefinition: true)
!5191 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 1512, elements: !5192)
!5192 = !{!5193}
!5193 = !DISubrange(count: 189)
!5194 = !DIGlobalVariableExpression(var: !5195, expr: !DIExpression())
!5195 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 239, type: !5112, isLocal: true, isDefinition: true)
!5196 = !DIGlobalVariableExpression(var: !5197, expr: !DIExpression())
!5197 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 239, type: !5198, isLocal: true, isDefinition: true)
!5198 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 472, elements: !5199)
!5199 = !{!5200}
!5200 = !DISubrange(count: 59)
!5201 = !DIGlobalVariableExpression(var: !5202, expr: !DIExpression())
!5202 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 239, type: !5203, isLocal: true, isDefinition: true)
!5203 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 944, elements: !5204)
!5204 = !{!5205}
!5205 = !DISubrange(count: 118)
!5206 = !DIGlobalVariableExpression(var: !5207, expr: !DIExpression())
!5207 = distinct !DIGlobalVariable(scope: null, file: !2346, line: 373, type: !5208, isLocal: true, isDefinition: true)
!5208 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 312, elements: !5209)
!5209 = !{!5210}
!5210 = !DISubrange(count: 39)
!5211 = !DIGlobalVariableExpression(var: !5212, expr: !DIExpression())
!5212 = distinct !DIGlobalVariable(scope: null, file: !2346, line: 373, type: !4896, isLocal: true, isDefinition: true)
!5213 = !DIGlobalVariableExpression(var: !5214, expr: !DIExpression())
!5214 = distinct !DIGlobalVariable(scope: null, file: !2346, line: 373, type: !5215, isLocal: true, isDefinition: true)
!5215 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 1832, elements: !5216)
!5216 = !{!5217}
!5217 = !DISubrange(count: 229)
!5218 = !DIGlobalVariableExpression(var: !5219, expr: !DIExpression())
!5219 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 97, type: !5220, isLocal: true, isDefinition: true)
!5220 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 1592, elements: !5221)
!5221 = !{!5222}
!5222 = !DISubrange(count: 199)
!5223 = !DIGlobalVariableExpression(var: !5224, expr: !DIExpression())
!5224 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 239, type: !5225, isLocal: true, isDefinition: true)
!5225 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 984, elements: !5226)
!5226 = !{!5227}
!5227 = !DISubrange(count: 123)
!5228 = !DIGlobalVariableExpression(var: !5229, expr: !DIExpression())
!5229 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 97, type: !5230, isLocal: true, isDefinition: true)
!5230 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 1560, elements: !5231)
!5231 = !{!5232}
!5232 = !DISubrange(count: 195)
!5233 = !DIGlobalVariableExpression(var: !5234, expr: !DIExpression())
!5234 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 239, type: !5235, isLocal: true, isDefinition: true)
!5235 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 968, elements: !5236)
!5236 = !{!5237}
!5237 = !DISubrange(count: 121)
!5238 = !DIGlobalVariableExpression(var: !5239, expr: !DIExpression())
!5239 = distinct !DIGlobalVariable(scope: null, file: !5240, line: 790, type: !5174, isLocal: true, isDefinition: true)
!5240 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/vector.tcc", directory: "", checksumkind: CSK_MD5, checksum: "d0546ffb79f08cabb1d395ee56a00a29")
!5241 = !DIGlobalVariableExpression(var: !5242, expr: !DIExpression())
!5242 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 97, type: !5243, isLocal: true, isDefinition: true)
!5243 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 1304, elements: !5244)
!5244 = !{!5245}
!5245 = !DISubrange(count: 163)
!5246 = !DIGlobalVariableExpression(var: !5247, expr: !DIExpression())
!5247 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 239, type: !5117, isLocal: true, isDefinition: true)
!5248 = !DIGlobalVariableExpression(var: !5249, expr: !DIExpression())
!5249 = distinct !DIGlobalVariable(scope: null, file: !542, line: 140, type: !4988, isLocal: true, isDefinition: true)
!5250 = !DIGlobalVariableExpression(var: !5251, expr: !DIExpression())
!5251 = distinct !DIGlobalVariable(scope: null, file: !542, line: 140, type: !5093, isLocal: true, isDefinition: true)
!5252 = !DIGlobalVariableExpression(var: !5253, expr: !DIExpression())
!5253 = distinct !DIGlobalVariable(scope: null, file: !542, line: 140, type: !5203, isLocal: true, isDefinition: true)
!5254 = !DIGlobalVariableExpression(var: !5255, expr: !DIExpression())
!5255 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 97, type: !5256, isLocal: true, isDefinition: true)
!5256 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 1336, elements: !5257)
!5257 = !{!5258}
!5258 = !DISubrange(count: 167)
!5259 = !DIGlobalVariableExpression(var: !5260, expr: !DIExpression())
!5260 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 239, type: !5261, isLocal: true, isDefinition: true)
!5261 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 856, elements: !5262)
!5262 = !{!5263}
!5263 = !DISubrange(count: 107)
!5264 = !DIGlobalVariableExpression(var: !5265, expr: !DIExpression())
!5265 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 309, type: !4993, isLocal: true, isDefinition: true)
!5266 = !DIGlobalVariableExpression(var: !5267, expr: !DIExpression())
!5267 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 309, type: !4932, isLocal: true, isDefinition: true)
!5268 = !DIGlobalVariableExpression(var: !5269, expr: !DIExpression())
!5269 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 309, type: !5270, isLocal: true, isDefinition: true)
!5270 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 1600, elements: !5271)
!5271 = !{!5272}
!5272 = !DISubrange(count: 200)
!5273 = !DIGlobalVariableExpression(var: !5274, expr: !DIExpression())
!5274 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 297, type: !4946, isLocal: true, isDefinition: true)
!5275 = !DIGlobalVariableExpression(var: !5276, expr: !DIExpression())
!5276 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 297, type: !5141, isLocal: true, isDefinition: true)
!5277 = !DIGlobalVariableExpression(var: !5278, expr: !DIExpression())
!5278 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 297, type: !5191, isLocal: true, isDefinition: true)
!5279 = !DIGlobalVariableExpression(var: !5280, expr: !DIExpression())
!5280 = distinct !DIGlobalVariable(scope: null, file: !5240, line: 423, type: !4918, isLocal: true, isDefinition: true)
!5281 = !DIGlobalVariableExpression(var: !5282, expr: !DIExpression())
!5282 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 97, type: !5283, isLocal: true, isDefinition: true)
!5283 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 1320, elements: !5284)
!5284 = !{!5285}
!5285 = !DISubrange(count: 165)
!5286 = !DIGlobalVariableExpression(var: !5287, expr: !DIExpression())
!5287 = distinct !DIGlobalVariable(scope: null, file: !3805, line: 239, type: !5288, isLocal: true, isDefinition: true)
!5288 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 848, elements: !5289)
!5289 = !{!5290}
!5290 = !DISubrange(count: 106)
!5291 = !DIGlobalVariableExpression(var: !5292, expr: !DIExpression())
!5292 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 309, type: !5293, isLocal: true, isDefinition: true)
!5293 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 1712, elements: !5294)
!5294 = !{!5295}
!5295 = !DISubrange(count: 214)
!5296 = !DIGlobalVariableExpression(var: !5297, expr: !DIExpression())
!5297 = distinct !DIGlobalVariable(scope: null, file: !2332, line: 286, type: !5298, isLocal: true, isDefinition: true)
!5298 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 1488, elements: !5299)
!5299 = !{!5300}
!5300 = !DISubrange(count: 186)
!5301 = !DIGlobalVariableExpression(var: !5302, expr: !DIExpression())
!5302 = distinct !DIGlobalVariable(scope: null, file: !542, line: 158, type: !5303, isLocal: true, isDefinition: true)
!5303 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 1168, elements: !5304)
!5304 = !{!5305}
!5305 = !DISubrange(count: 146)
!5306 = !DIGlobalVariableExpression(var: !5307, expr: !DIExpression())
!5307 = distinct !DIGlobalVariable(scope: null, file: !542, line: 140, type: !5308, isLocal: true, isDefinition: true)
!5308 = !DICompositeType(tag: DW_TAG_array_type, baseType: !164, size: 1312, elements: !5309)
!5309 = !{!5310}
!5310 = !DISubrange(count: 164)
!5311 = !{!5312, !5318, !5324, !5326, !5328, !5332, !5334, !5336, !5338, !5340, !5342, !5344, !5346, !5351, !5355, !5357, !5359, !5364, !5366, !5368, !5370, !5372, !5374, !5376, !5379, !5381, !5383, !5387, !5392, !5394, !5396, !5398, !5400, !5402, !5404, !5406, !5408, !5410, !5412, !5416, !5420, !5422, !5424, !5426, !5428, !5430, !5432, !5434, !5436, !5438, !5440, !5442, !5444, !5446, !5448, !5450, !5454, !5458, !5462, !5464, !5466, !5468, !5470, !5472, !5474, !5476, !5478, !5480, !5484, !5488, !5492, !5494, !5496, !5498, !5502, !5506, !5510, !5512, !5514, !5516, !5518, !5520, !5522, !5524, !5526, !5528, !5530, !5532, !5534, !5538, !5542, !5546, !5548, !5550, !5552, !5556, !5560, !5564, !5566, !5568, !5570, !5572, !5574, !5576, !5580, !5584, !5586, !5588, !5590, !5592, !5596, !5600, !5604, !5606, !5608, !5610, !5612, !5614, !5616, !5620, !5624, !5628, !5630, !5634, !5638, !5640, !5642, !5644, !5646, !5648, !5650, !5655, !5661, !5665, !5671, !5675, !5679, !5685, !5689, !5691, !5693, !5697, !5701, !5705, !5709, !5711, !5713, !5715, !5717, !5721, !5725, !5729, !5731, !5733, !5737, !5741, !5747, !5749, !5753, !5755, !5758, !5762, !5766, !5775, !5779, !5783, !5787, !5791, !5795, !5799, !5803, !5807, !5811, !5818, !5822, !5826, !5828, !5830, !5834, !5838, !5844, !5848, !5852, !5854, !5861, !5865, !5871, !5873, !5877, !5881, !5885, !5889, !5893, !5897, !5901, !5902, !5903, !5904, !5906, !5907, !5908, !5909, !5910, !5911, !5912, !5916, !5920, !5934, !5937, !5942, !5989, !5994, !5998, !6002, !6006, !6010, !6012, !6014, !6018, !6024, !6028, !6034, !6039, !6041, !6045, !6049, !6053, !6057, !6069, !6071, !6075, !6079, !6083, !6085, !6089, !6093, !6097, !6099, !6101, !6105, !6113, !6117, !6121, !6125, !6127, !6133, !6135, !6141, !6145, !6149, !6153, !6157, !6161, !6165, !6167, !6169, !6173, !6177, !6181, !6183, !6187, !6191, !6193, !6195, !6199, !6203, !6207, !6211, !6212, !6213, !6214, !6215, !6216, !6217, !6218, !6219, !6220, !6221, !6226, !6230, !6233, !6236, !6239, !6241, !6243, !6245, !6247, !6249, !6251, !6253, !6256, !6258, !6261, !6264, !6267, !6268, !6270, !6272, !6274, !6276, !6278, !6280, !6282, !6284, !6287, !6289, !6293, !6297, !6302, !6306, !6308, !6310, !6312, !6314, !6316, !6318, !6320, !6322, !6324, !6326, !6328, !6330, !6332, !6333, !6334, !6338, !6344, !6349, !6353, !6355, !6357, !6359, !6361, !6368, !6372, !6376, !6380, !6384, !6388, !6392, !6396, !6398, !6402, !6408, !6412, !6416, !6418, !6421, !6425, !6429, !6431, !6433, !6435, !6437, !6439, !6441, !6443, !6447, !6451, !6455, !6459, !6463, !6467, !6469, !6473, !6477, !6481, !6485, !6487, !6489, !6493, !6497, !6498, !6499, !6500, !6501, !6502, !6508, !6511, !6512, !6514, !6516, !6518, !6520, !6524, !6526, !6528, !6530, !6532, !6534, !6536, !6538, !6540, !6544, !6548, !6550, !6554, !6558, !6560, !6563, !6568, !6572, !6573, !6578, !6582, !6587, !6592, !6596, !6602, !6606, !6608, !6612, !6613}
!5312 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5313, file: !5317, line: 52)
!5313 = !DISubprogram(name: "abs", scope: !5314, file: !5314, line: 837, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5314 = !DIFile(filename: "/usr/include/stdlib.h", directory: "", checksumkind: CSK_MD5, checksum: "69d942f1572b8bd342d93c49f499f318")
!5315 = !DISubroutineType(types: !5316)
!5316 = !{!24, !24}
!5317 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h", directory: "")
!5318 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5319, file: !5323, line: 83)
!5319 = !DISubprogram(name: "acos", scope: !5320, file: !5320, line: 53, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5320 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", directory: "", checksumkind: CSK_MD5, checksum: "540523e6856cf8d57a3ebef5fd79793e")
!5321 = !DISubroutineType(types: !5322)
!5322 = !{!4666, !4666}
!5323 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cmath", directory: "")
!5324 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5325, file: !5323, line: 102)
!5325 = !DISubprogram(name: "asin", scope: !5320, file: !5320, line: 55, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5326 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5327, file: !5323, line: 121)
!5327 = !DISubprogram(name: "atan", scope: !5320, file: !5320, line: 57, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5328 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5329, file: !5323, line: 140)
!5329 = !DISubprogram(name: "atan2", scope: !5320, file: !5320, line: 59, type: !5330, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5330 = !DISubroutineType(types: !5331)
!5331 = !{!4666, !4666, !4666}
!5332 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5333, file: !5323, line: 161)
!5333 = !DISubprogram(name: "ceil", scope: !5320, file: !5320, line: 159, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5334 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5335, file: !5323, line: 180)
!5335 = !DISubprogram(name: "cos", scope: !5320, file: !5320, line: 62, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5336 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5337, file: !5323, line: 199)
!5337 = !DISubprogram(name: "cosh", scope: !5320, file: !5320, line: 71, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5338 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5339, file: !5323, line: 218)
!5339 = !DISubprogram(name: "exp", scope: !5320, file: !5320, line: 95, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5340 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5341, file: !5323, line: 237)
!5341 = !DISubprogram(name: "fabs", scope: !5320, file: !5320, line: 162, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5342 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5343, file: !5323, line: 256)
!5343 = !DISubprogram(name: "floor", scope: !5320, file: !5320, line: 165, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5344 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5345, file: !5323, line: 275)
!5345 = !DISubprogram(name: "fmod", scope: !5320, file: !5320, line: 168, type: !5330, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5346 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5347, file: !5323, line: 296)
!5347 = !DISubprogram(name: "frexp", scope: !5320, file: !5320, line: 98, type: !5348, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5348 = !DISubroutineType(types: !5349)
!5349 = !{!4666, !4666, !5350}
!5350 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !24, size: 64)
!5351 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5352, file: !5323, line: 315)
!5352 = !DISubprogram(name: "ldexp", scope: !5320, file: !5320, line: 101, type: !5353, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5353 = !DISubroutineType(types: !5354)
!5354 = !{!4666, !4666, !24}
!5355 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5356, file: !5323, line: 334)
!5356 = !DISubprogram(name: "log", scope: !5320, file: !5320, line: 104, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5357 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5358, file: !5323, line: 353)
!5358 = !DISubprogram(name: "log10", scope: !5320, file: !5320, line: 107, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5359 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5360, file: !5323, line: 372)
!5360 = !DISubprogram(name: "modf", scope: !5320, file: !5320, line: 110, type: !5361, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5361 = !DISubroutineType(types: !5362)
!5362 = !{!4666, !4666, !5363}
!5363 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4666, size: 64)
!5364 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5365, file: !5323, line: 384)
!5365 = !DISubprogram(name: "pow", scope: !5320, file: !5320, line: 140, type: !5330, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5366 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5367, file: !5323, line: 421)
!5367 = !DISubprogram(name: "sin", scope: !5320, file: !5320, line: 64, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5368 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5369, file: !5323, line: 440)
!5369 = !DISubprogram(name: "sinh", scope: !5320, file: !5320, line: 73, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5370 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5371, file: !5323, line: 459)
!5371 = !DISubprogram(name: "sqrt", scope: !5320, file: !5320, line: 143, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5372 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5373, file: !5323, line: 478)
!5373 = !DISubprogram(name: "tan", scope: !5320, file: !5320, line: 66, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5374 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5375, file: !5323, line: 497)
!5375 = !DISubprogram(name: "tanh", scope: !5320, file: !5320, line: 75, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5376 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5377, file: !5323, line: 1065)
!5377 = !DIDerivedType(tag: DW_TAG_typedef, name: "double_t", file: !5378, line: 150, baseType: !4666)
!5378 = !DIFile(filename: "/usr/include/math.h", directory: "", checksumkind: CSK_MD5, checksum: "ecf196918078d683ff91ad9a1c51599a")
!5379 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5380, file: !5323, line: 1066)
!5380 = !DIDerivedType(tag: DW_TAG_typedef, name: "float_t", file: !5378, line: 149, baseType: !4798)
!5381 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5382, file: !5323, line: 1069)
!5382 = !DISubprogram(name: "acosh", scope: !5320, file: !5320, line: 85, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5383 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5384, file: !5323, line: 1070)
!5384 = !DISubprogram(name: "acoshf", scope: !5320, file: !5320, line: 85, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5385 = !DISubroutineType(types: !5386)
!5386 = !{!4798, !4798}
!5387 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5388, file: !5323, line: 1071)
!5388 = !DISubprogram(name: "acoshl", scope: !5320, file: !5320, line: 85, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5389 = !DISubroutineType(types: !5390)
!5390 = !{!5391, !5391}
!5391 = !DIBasicType(name: "long double", size: 128, encoding: DW_ATE_float)
!5392 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5393, file: !5323, line: 1073)
!5393 = !DISubprogram(name: "asinh", scope: !5320, file: !5320, line: 87, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5394 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5395, file: !5323, line: 1074)
!5395 = !DISubprogram(name: "asinhf", scope: !5320, file: !5320, line: 87, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5396 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5397, file: !5323, line: 1075)
!5397 = !DISubprogram(name: "asinhl", scope: !5320, file: !5320, line: 87, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5398 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5399, file: !5323, line: 1077)
!5399 = !DISubprogram(name: "atanh", scope: !5320, file: !5320, line: 89, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5400 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5401, file: !5323, line: 1078)
!5401 = !DISubprogram(name: "atanhf", scope: !5320, file: !5320, line: 89, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5402 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5403, file: !5323, line: 1079)
!5403 = !DISubprogram(name: "atanhl", scope: !5320, file: !5320, line: 89, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5404 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5405, file: !5323, line: 1081)
!5405 = !DISubprogram(name: "cbrt", scope: !5320, file: !5320, line: 152, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5406 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5407, file: !5323, line: 1082)
!5407 = !DISubprogram(name: "cbrtf", scope: !5320, file: !5320, line: 152, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5408 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5409, file: !5323, line: 1083)
!5409 = !DISubprogram(name: "cbrtl", scope: !5320, file: !5320, line: 152, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5410 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5411, file: !5323, line: 1085)
!5411 = !DISubprogram(name: "copysign", scope: !5320, file: !5320, line: 196, type: !5330, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5412 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5413, file: !5323, line: 1086)
!5413 = !DISubprogram(name: "copysignf", scope: !5320, file: !5320, line: 196, type: !5414, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5414 = !DISubroutineType(types: !5415)
!5415 = !{!4798, !4798, !4798}
!5416 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5417, file: !5323, line: 1087)
!5417 = !DISubprogram(name: "copysignl", scope: !5320, file: !5320, line: 196, type: !5418, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5418 = !DISubroutineType(types: !5419)
!5419 = !{!5391, !5391, !5391}
!5420 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5421, file: !5323, line: 1089)
!5421 = !DISubprogram(name: "erf", scope: !5320, file: !5320, line: 228, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5422 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5423, file: !5323, line: 1090)
!5423 = !DISubprogram(name: "erff", scope: !5320, file: !5320, line: 228, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5424 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5425, file: !5323, line: 1091)
!5425 = !DISubprogram(name: "erfl", scope: !5320, file: !5320, line: 228, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5426 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5427, file: !5323, line: 1093)
!5427 = !DISubprogram(name: "erfc", scope: !5320, file: !5320, line: 229, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5428 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5429, file: !5323, line: 1094)
!5429 = !DISubprogram(name: "erfcf", scope: !5320, file: !5320, line: 229, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5430 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5431, file: !5323, line: 1095)
!5431 = !DISubprogram(name: "erfcl", scope: !5320, file: !5320, line: 229, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5432 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5433, file: !5323, line: 1097)
!5433 = !DISubprogram(name: "exp2", scope: !5320, file: !5320, line: 130, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5434 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5435, file: !5323, line: 1098)
!5435 = !DISubprogram(name: "exp2f", scope: !5320, file: !5320, line: 130, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5436 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5437, file: !5323, line: 1099)
!5437 = !DISubprogram(name: "exp2l", scope: !5320, file: !5320, line: 130, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5438 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5439, file: !5323, line: 1101)
!5439 = !DISubprogram(name: "expm1", scope: !5320, file: !5320, line: 119, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5440 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5441, file: !5323, line: 1102)
!5441 = !DISubprogram(name: "expm1f", scope: !5320, file: !5320, line: 119, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5442 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5443, file: !5323, line: 1103)
!5443 = !DISubprogram(name: "expm1l", scope: !5320, file: !5320, line: 119, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5444 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5445, file: !5323, line: 1105)
!5445 = !DISubprogram(name: "fdim", scope: !5320, file: !5320, line: 326, type: !5330, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5446 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5447, file: !5323, line: 1106)
!5447 = !DISubprogram(name: "fdimf", scope: !5320, file: !5320, line: 326, type: !5414, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5448 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5449, file: !5323, line: 1107)
!5449 = !DISubprogram(name: "fdiml", scope: !5320, file: !5320, line: 326, type: !5418, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5450 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5451, file: !5323, line: 1109)
!5451 = !DISubprogram(name: "fma", scope: !5320, file: !5320, line: 335, type: !5452, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5452 = !DISubroutineType(types: !5453)
!5453 = !{!4666, !4666, !4666, !4666}
!5454 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5455, file: !5323, line: 1110)
!5455 = !DISubprogram(name: "fmaf", scope: !5320, file: !5320, line: 335, type: !5456, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5456 = !DISubroutineType(types: !5457)
!5457 = !{!4798, !4798, !4798, !4798}
!5458 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5459, file: !5323, line: 1111)
!5459 = !DISubprogram(name: "fmal", scope: !5320, file: !5320, line: 335, type: !5460, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5460 = !DISubroutineType(types: !5461)
!5461 = !{!5391, !5391, !5391, !5391}
!5462 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5463, file: !5323, line: 1113)
!5463 = !DISubprogram(name: "fmax", scope: !5320, file: !5320, line: 329, type: !5330, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5464 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5465, file: !5323, line: 1114)
!5465 = !DISubprogram(name: "fmaxf", scope: !5320, file: !5320, line: 329, type: !5414, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5466 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5467, file: !5323, line: 1115)
!5467 = !DISubprogram(name: "fmaxl", scope: !5320, file: !5320, line: 329, type: !5418, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5468 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5469, file: !5323, line: 1117)
!5469 = !DISubprogram(name: "fmin", scope: !5320, file: !5320, line: 332, type: !5330, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5470 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5471, file: !5323, line: 1118)
!5471 = !DISubprogram(name: "fminf", scope: !5320, file: !5320, line: 332, type: !5414, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5472 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5473, file: !5323, line: 1119)
!5473 = !DISubprogram(name: "fminl", scope: !5320, file: !5320, line: 332, type: !5418, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5474 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5475, file: !5323, line: 1121)
!5475 = !DISubprogram(name: "hypot", scope: !5320, file: !5320, line: 147, type: !5330, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5476 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5477, file: !5323, line: 1122)
!5477 = !DISubprogram(name: "hypotf", scope: !5320, file: !5320, line: 147, type: !5414, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5478 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5479, file: !5323, line: 1123)
!5479 = !DISubprogram(name: "hypotl", scope: !5320, file: !5320, line: 147, type: !5418, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5480 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5481, file: !5323, line: 1125)
!5481 = !DISubprogram(name: "ilogb", scope: !5320, file: !5320, line: 280, type: !5482, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5482 = !DISubroutineType(types: !5483)
!5483 = !{!24, !4666}
!5484 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5485, file: !5323, line: 1126)
!5485 = !DISubprogram(name: "ilogbf", scope: !5320, file: !5320, line: 280, type: !5486, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5486 = !DISubroutineType(types: !5487)
!5487 = !{!24, !4798}
!5488 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5489, file: !5323, line: 1127)
!5489 = !DISubprogram(name: "ilogbl", scope: !5320, file: !5320, line: 280, type: !5490, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5490 = !DISubroutineType(types: !5491)
!5491 = !{!24, !5391}
!5492 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5493, file: !5323, line: 1129)
!5493 = !DISubprogram(name: "lgamma", scope: !5320, file: !5320, line: 230, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5494 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5495, file: !5323, line: 1130)
!5495 = !DISubprogram(name: "lgammaf", scope: !5320, file: !5320, line: 230, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5496 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5497, file: !5323, line: 1131)
!5497 = !DISubprogram(name: "lgammal", scope: !5320, file: !5320, line: 230, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5498 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5499, file: !5323, line: 1134)
!5499 = !DISubprogram(name: "llrint", scope: !5320, file: !5320, line: 316, type: !5500, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5500 = !DISubroutineType(types: !5501)
!5501 = !{!413, !4666}
!5502 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5503, file: !5323, line: 1135)
!5503 = !DISubprogram(name: "llrintf", scope: !5320, file: !5320, line: 316, type: !5504, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5504 = !DISubroutineType(types: !5505)
!5505 = !{!413, !4798}
!5506 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5507, file: !5323, line: 1136)
!5507 = !DISubprogram(name: "llrintl", scope: !5320, file: !5320, line: 316, type: !5508, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5508 = !DISubroutineType(types: !5509)
!5509 = !{!413, !5391}
!5510 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5511, file: !5323, line: 1138)
!5511 = !DISubprogram(name: "llround", scope: !5320, file: !5320, line: 322, type: !5500, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5512 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5513, file: !5323, line: 1139)
!5513 = !DISubprogram(name: "llroundf", scope: !5320, file: !5320, line: 322, type: !5504, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5514 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5515, file: !5323, line: 1140)
!5515 = !DISubprogram(name: "llroundl", scope: !5320, file: !5320, line: 322, type: !5508, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5516 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5517, file: !5323, line: 1143)
!5517 = !DISubprogram(name: "log1p", scope: !5320, file: !5320, line: 122, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5518 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5519, file: !5323, line: 1144)
!5519 = !DISubprogram(name: "log1pf", scope: !5320, file: !5320, line: 122, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5520 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5521, file: !5323, line: 1145)
!5521 = !DISubprogram(name: "log1pl", scope: !5320, file: !5320, line: 122, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5522 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5523, file: !5323, line: 1147)
!5523 = !DISubprogram(name: "log2", scope: !5320, file: !5320, line: 133, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5524 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5525, file: !5323, line: 1148)
!5525 = !DISubprogram(name: "log2f", scope: !5320, file: !5320, line: 133, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5526 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5527, file: !5323, line: 1149)
!5527 = !DISubprogram(name: "log2l", scope: !5320, file: !5320, line: 133, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5528 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5529, file: !5323, line: 1151)
!5529 = !DISubprogram(name: "logb", scope: !5320, file: !5320, line: 125, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5530 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5531, file: !5323, line: 1152)
!5531 = !DISubprogram(name: "logbf", scope: !5320, file: !5320, line: 125, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5532 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5533, file: !5323, line: 1153)
!5533 = !DISubprogram(name: "logbl", scope: !5320, file: !5320, line: 125, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5534 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5535, file: !5323, line: 1155)
!5535 = !DISubprogram(name: "lrint", scope: !5320, file: !5320, line: 314, type: !5536, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5536 = !DISubroutineType(types: !5537)
!5537 = !{!405, !4666}
!5538 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5539, file: !5323, line: 1156)
!5539 = !DISubprogram(name: "lrintf", scope: !5320, file: !5320, line: 314, type: !5540, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5540 = !DISubroutineType(types: !5541)
!5541 = !{!405, !4798}
!5542 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5543, file: !5323, line: 1157)
!5543 = !DISubprogram(name: "lrintl", scope: !5320, file: !5320, line: 314, type: !5544, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5544 = !DISubroutineType(types: !5545)
!5545 = !{!405, !5391}
!5546 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5547, file: !5323, line: 1159)
!5547 = !DISubprogram(name: "lround", scope: !5320, file: !5320, line: 320, type: !5536, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5548 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5549, file: !5323, line: 1160)
!5549 = !DISubprogram(name: "lroundf", scope: !5320, file: !5320, line: 320, type: !5540, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5550 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5551, file: !5323, line: 1161)
!5551 = !DISubprogram(name: "lroundl", scope: !5320, file: !5320, line: 320, type: !5544, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5552 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5553, file: !5323, line: 1163)
!5553 = !DISubprogram(name: "nan", scope: !5320, file: !5320, line: 201, type: !5554, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5554 = !DISubroutineType(types: !5555)
!5555 = !{!4666, !163}
!5556 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5557, file: !5323, line: 1164)
!5557 = !DISubprogram(name: "nanf", scope: !5320, file: !5320, line: 201, type: !5558, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5558 = !DISubroutineType(types: !5559)
!5559 = !{!4798, !163}
!5560 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5561, file: !5323, line: 1165)
!5561 = !DISubprogram(name: "nanl", scope: !5320, file: !5320, line: 201, type: !5562, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5562 = !DISubroutineType(types: !5563)
!5563 = !{!5391, !163}
!5564 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5565, file: !5323, line: 1167)
!5565 = !DISubprogram(name: "nearbyint", scope: !5320, file: !5320, line: 294, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5566 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5567, file: !5323, line: 1168)
!5567 = !DISubprogram(name: "nearbyintf", scope: !5320, file: !5320, line: 294, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5568 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5569, file: !5323, line: 1169)
!5569 = !DISubprogram(name: "nearbyintl", scope: !5320, file: !5320, line: 294, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5570 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5571, file: !5323, line: 1171)
!5571 = !DISubprogram(name: "nextafter", scope: !5320, file: !5320, line: 259, type: !5330, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5572 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5573, file: !5323, line: 1172)
!5573 = !DISubprogram(name: "nextafterf", scope: !5320, file: !5320, line: 259, type: !5414, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5574 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5575, file: !5323, line: 1173)
!5575 = !DISubprogram(name: "nextafterl", scope: !5320, file: !5320, line: 259, type: !5418, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5576 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5577, file: !5323, line: 1175)
!5577 = !DISubprogram(name: "nexttoward", scope: !5320, file: !5320, line: 261, type: !5578, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5578 = !DISubroutineType(types: !5579)
!5579 = !{!4666, !4666, !5391}
!5580 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5581, file: !5323, line: 1176)
!5581 = !DISubprogram(name: "nexttowardf", scope: !5320, file: !5320, line: 261, type: !5582, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5582 = !DISubroutineType(types: !5583)
!5583 = !{!4798, !4798, !5391}
!5584 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5585, file: !5323, line: 1177)
!5585 = !DISubprogram(name: "nexttowardl", scope: !5320, file: !5320, line: 261, type: !5418, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5586 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5587, file: !5323, line: 1179)
!5587 = !DISubprogram(name: "remainder", scope: !5320, file: !5320, line: 272, type: !5330, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5588 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5589, file: !5323, line: 1180)
!5589 = !DISubprogram(name: "remainderf", scope: !5320, file: !5320, line: 272, type: !5414, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5590 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5591, file: !5323, line: 1181)
!5591 = !DISubprogram(name: "remainderl", scope: !5320, file: !5320, line: 272, type: !5418, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5592 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5593, file: !5323, line: 1183)
!5593 = !DISubprogram(name: "remquo", scope: !5320, file: !5320, line: 307, type: !5594, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5594 = !DISubroutineType(types: !5595)
!5595 = !{!4666, !4666, !4666, !5350}
!5596 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5597, file: !5323, line: 1184)
!5597 = !DISubprogram(name: "remquof", scope: !5320, file: !5320, line: 307, type: !5598, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5598 = !DISubroutineType(types: !5599)
!5599 = !{!4798, !4798, !4798, !5350}
!5600 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5601, file: !5323, line: 1185)
!5601 = !DISubprogram(name: "remquol", scope: !5320, file: !5320, line: 307, type: !5602, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5602 = !DISubroutineType(types: !5603)
!5603 = !{!5391, !5391, !5391, !5350}
!5604 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5605, file: !5323, line: 1187)
!5605 = !DISubprogram(name: "rint", scope: !5320, file: !5320, line: 256, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5606 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5607, file: !5323, line: 1188)
!5607 = !DISubprogram(name: "rintf", scope: !5320, file: !5320, line: 256, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5608 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5609, file: !5323, line: 1189)
!5609 = !DISubprogram(name: "rintl", scope: !5320, file: !5320, line: 256, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5610 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5611, file: !5323, line: 1191)
!5611 = !DISubprogram(name: "round", scope: !5320, file: !5320, line: 298, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5612 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5613, file: !5323, line: 1192)
!5613 = !DISubprogram(name: "roundf", scope: !5320, file: !5320, line: 298, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5614 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5615, file: !5323, line: 1193)
!5615 = !DISubprogram(name: "roundl", scope: !5320, file: !5320, line: 298, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5616 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5617, file: !5323, line: 1195)
!5617 = !DISubprogram(name: "scalbln", scope: !5320, file: !5320, line: 290, type: !5618, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5618 = !DISubroutineType(types: !5619)
!5619 = !{!4666, !4666, !405}
!5620 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5621, file: !5323, line: 1196)
!5621 = !DISubprogram(name: "scalblnf", scope: !5320, file: !5320, line: 290, type: !5622, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5622 = !DISubroutineType(types: !5623)
!5623 = !{!4798, !4798, !405}
!5624 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5625, file: !5323, line: 1197)
!5625 = !DISubprogram(name: "scalblnl", scope: !5320, file: !5320, line: 290, type: !5626, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5626 = !DISubroutineType(types: !5627)
!5627 = !{!5391, !5391, !405}
!5628 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5629, file: !5323, line: 1199)
!5629 = !DISubprogram(name: "scalbn", scope: !5320, file: !5320, line: 276, type: !5353, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5630 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5631, file: !5323, line: 1200)
!5631 = !DISubprogram(name: "scalbnf", scope: !5320, file: !5320, line: 276, type: !5632, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5632 = !DISubroutineType(types: !5633)
!5633 = !{!4798, !4798, !24}
!5634 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5635, file: !5323, line: 1201)
!5635 = !DISubprogram(name: "scalbnl", scope: !5320, file: !5320, line: 276, type: !5636, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5636 = !DISubroutineType(types: !5637)
!5637 = !{!5391, !5391, !24}
!5638 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5639, file: !5323, line: 1203)
!5639 = !DISubprogram(name: "tgamma", scope: !5320, file: !5320, line: 235, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5640 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5641, file: !5323, line: 1204)
!5641 = !DISubprogram(name: "tgammaf", scope: !5320, file: !5320, line: 235, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5642 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5643, file: !5323, line: 1205)
!5643 = !DISubprogram(name: "tgammal", scope: !5320, file: !5320, line: 235, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5644 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5645, file: !5323, line: 1207)
!5645 = !DISubprogram(name: "trunc", scope: !5320, file: !5320, line: 302, type: !5321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5646 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5647, file: !5323, line: 1208)
!5647 = !DISubprogram(name: "truncf", scope: !5320, file: !5320, line: 302, type: !5385, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5648 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5649, file: !5323, line: 1209)
!5649 = !DISubprogram(name: "truncl", scope: !5320, file: !5320, line: 302, type: !5389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5650 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5651, file: !5654, line: 56)
!5651 = !DIDerivedType(tag: DW_TAG_typedef, name: "max_align_t", file: !5652, line: 24, baseType: !5653)
!5652 = !DIFile(filename: "llvm5/build/lib/clang/15.0.3/include/__stddef_max_align_t.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "48e8e2456f77e6cda35d245130fa7259")
!5653 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !5652, line: 19, size: 256, flags: DIFlagFwdDecl, identifier: "_ZTS11max_align_t")
!5654 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstddef", directory: "")
!5655 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5656, file: !5660, line: 75)
!5656 = !DISubprogram(name: "memchr", scope: !5657, file: !5657, line: 90, type: !5658, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5657 = !DIFile(filename: "/usr/include/string.h", directory: "", checksumkind: CSK_MD5, checksum: "1029a2d94b0e7b73f8dbf87ca20ab7bc")
!5658 = !DISubroutineType(types: !5659)
!5659 = !{!121, !1154, !24, !159}
!5660 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstring", directory: "")
!5661 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5662, file: !5660, line: 76)
!5662 = !DISubprogram(name: "memcmp", scope: !5657, file: !5657, line: 63, type: !5663, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5663 = !DISubroutineType(types: !5664)
!5664 = !{!24, !1154, !1154, !159}
!5665 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5666, file: !5660, line: 77)
!5666 = !DISubprogram(name: "memcpy", scope: !5657, file: !5657, line: 42, type: !5667, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5667 = !DISubroutineType(types: !5668)
!5668 = !{!121, !5669, !5670, !159}
!5669 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !121)
!5670 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !1154)
!5671 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5672, file: !5660, line: 78)
!5672 = !DISubprogram(name: "memmove", scope: !5657, file: !5657, line: 46, type: !5673, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5673 = !DISubroutineType(types: !5674)
!5674 = !{!121, !121, !1154, !159}
!5675 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5676, file: !5660, line: 79)
!5676 = !DISubprogram(name: "memset", scope: !5657, file: !5657, line: 60, type: !5677, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5677 = !DISubroutineType(types: !5678)
!5678 = !{!121, !121, !24, !159}
!5679 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5680, file: !5660, line: 80)
!5680 = !DISubprogram(name: "strcat", scope: !5657, file: !5657, line: 129, type: !5681, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5681 = !DISubroutineType(types: !5682)
!5682 = !{!613, !5683, !5684}
!5683 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !613)
!5684 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !163)
!5685 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5686, file: !5660, line: 81)
!5686 = !DISubprogram(name: "strcmp", scope: !5657, file: !5657, line: 136, type: !5687, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5687 = !DISubroutineType(types: !5688)
!5688 = !{!24, !163, !163}
!5689 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5690, file: !5660, line: 82)
!5690 = !DISubprogram(name: "strcoll", scope: !5657, file: !5657, line: 143, type: !5687, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5691 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5692, file: !5660, line: 83)
!5692 = !DISubprogram(name: "strcpy", scope: !5657, file: !5657, line: 121, type: !5681, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5693 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5694, file: !5660, line: 84)
!5694 = !DISubprogram(name: "strcspn", scope: !5657, file: !5657, line: 272, type: !5695, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5695 = !DISubroutineType(types: !5696)
!5696 = !{!159, !163, !163}
!5697 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5698, file: !5660, line: 85)
!5698 = !DISubprogram(name: "strerror", scope: !5657, file: !5657, line: 396, type: !5699, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5699 = !DISubroutineType(types: !5700)
!5700 = !{!613, !24}
!5701 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5702, file: !5660, line: 86)
!5702 = !DISubprogram(name: "strlen", scope: !5657, file: !5657, line: 384, type: !5703, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5703 = !DISubroutineType(types: !5704)
!5704 = !{!159, !163}
!5705 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5706, file: !5660, line: 87)
!5706 = !DISubprogram(name: "strncat", scope: !5657, file: !5657, line: 132, type: !5707, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5707 = !DISubroutineType(types: !5708)
!5708 = !{!613, !5683, !5684, !159}
!5709 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5710, file: !5660, line: 88)
!5710 = !DISubprogram(name: "strncmp", scope: !5657, file: !5657, line: 139, type: !172, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5711 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5712, file: !5660, line: 89)
!5712 = !DISubprogram(name: "strncpy", scope: !5657, file: !5657, line: 124, type: !5707, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5713 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5714, file: !5660, line: 90)
!5714 = !DISubprogram(name: "strspn", scope: !5657, file: !5657, line: 276, type: !5695, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5715 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5716, file: !5660, line: 91)
!5716 = !DISubprogram(name: "strtok", scope: !5657, file: !5657, line: 335, type: !5681, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5717 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5718, file: !5660, line: 92)
!5718 = !DISubprogram(name: "strxfrm", scope: !5657, file: !5657, line: 146, type: !5719, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5719 = !DISubroutineType(types: !5720)
!5720 = !{!159, !5683, !5684, !159}
!5721 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5722, file: !5660, line: 93)
!5722 = !DISubprogram(name: "strchr", scope: !5657, file: !5657, line: 225, type: !5723, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5723 = !DISubroutineType(types: !5724)
!5724 = !{!613, !163, !24}
!5725 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5726, file: !5660, line: 94)
!5726 = !DISubprogram(name: "strpbrk", scope: !5657, file: !5657, line: 302, type: !5727, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5727 = !DISubroutineType(types: !5728)
!5728 = !{!613, !163, !163}
!5729 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5730, file: !5660, line: 95)
!5730 = !DISubprogram(name: "strrchr", scope: !5657, file: !5657, line: 252, type: !5723, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5731 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5732, file: !5660, line: 96)
!5732 = !DISubprogram(name: "strstr", scope: !5657, file: !5657, line: 329, type: !5727, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5733 = !DIImportedEntity(tag: DW_TAG_imported_module, scope: !5734, entity: !5735, file: !5736, line: 58)
!5734 = !DINamespace(name: "__gnu_debug", scope: null)
!5735 = !DINamespace(name: "__debug", scope: !192)
!5736 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/debug/debug.h", directory: "", checksumkind: CSK_MD5, checksum: "0d648599b52b1d377b1fee4a0a4b2b91")
!5737 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5738, file: !5740, line: 127)
!5738 = !DIDerivedType(tag: DW_TAG_typedef, name: "div_t", file: !5314, line: 62, baseType: !5739)
!5739 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !5314, line: 58, size: 64, flags: DIFlagFwdDecl, identifier: "_ZTS5div_t")
!5740 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdlib", directory: "")
!5741 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5742, file: !5740, line: 128)
!5742 = !DIDerivedType(tag: DW_TAG_typedef, name: "ldiv_t", file: !5314, line: 70, baseType: !5743)
!5743 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !5314, line: 66, size: 128, flags: DIFlagTypePassByValue, elements: !5744, identifier: "_ZTS6ldiv_t")
!5744 = !{!5745, !5746}
!5745 = !DIDerivedType(tag: DW_TAG_member, name: "quot", scope: !5743, file: !5314, line: 68, baseType: !405, size: 64)
!5746 = !DIDerivedType(tag: DW_TAG_member, name: "rem", scope: !5743, file: !5314, line: 69, baseType: !405, size: 64, offset: 64)
!5747 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5748, file: !5740, line: 130)
!5748 = !DISubprogram(name: "abort", scope: !5314, file: !5314, line: 588, type: !2508, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!5749 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5750, file: !5740, line: 134)
!5750 = !DISubprogram(name: "atexit", scope: !5314, file: !5314, line: 592, type: !5751, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5751 = !DISubroutineType(types: !5752)
!5752 = !{!24, !2514}
!5753 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5754, file: !5740, line: 137)
!5754 = !DISubprogram(name: "at_quick_exit", scope: !5314, file: !5314, line: 597, type: !5751, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5755 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5756, file: !5740, line: 140)
!5756 = !DISubprogram(name: "atof", scope: !5757, file: !5757, line: 25, type: !5554, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5757 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h", directory: "", checksumkind: CSK_MD5, checksum: "ce60958b260b171e83db3307f1d644f0")
!5758 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5759, file: !5740, line: 141)
!5759 = !DISubprogram(name: "atoi", scope: !5314, file: !5314, line: 361, type: !5760, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5760 = !DISubroutineType(types: !5761)
!5761 = !{!24, !163}
!5762 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5763, file: !5740, line: 142)
!5763 = !DISubprogram(name: "atol", scope: !5314, file: !5314, line: 366, type: !5764, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5764 = !DISubroutineType(types: !5765)
!5765 = !{!405, !163}
!5766 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5767, file: !5740, line: 143)
!5767 = !DISubprogram(name: "bsearch", scope: !5768, file: !5768, line: 20, type: !5769, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5768 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h", directory: "", checksumkind: CSK_MD5, checksum: "1a798a38b25adee7bb680abce9ef568a")
!5769 = !DISubroutineType(types: !5770)
!5770 = !{!121, !1154, !1154, !159, !159, !5771}
!5771 = !DIDerivedType(tag: DW_TAG_typedef, name: "__compar_fn_t", file: !5314, line: 805, baseType: !5772)
!5772 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5773, size: 64)
!5773 = !DISubroutineType(types: !5774)
!5774 = !{!24, !1154, !1154}
!5775 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5776, file: !5740, line: 144)
!5776 = !DISubprogram(name: "calloc", scope: !5314, file: !5314, line: 541, type: !5777, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5777 = !DISubroutineType(types: !5778)
!5778 = !{!121, !159, !159}
!5779 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5780, file: !5740, line: 145)
!5780 = !DISubprogram(name: "div", scope: !5314, file: !5314, line: 849, type: !5781, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5781 = !DISubroutineType(types: !5782)
!5782 = !{!5738, !24, !24}
!5783 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5784, file: !5740, line: 146)
!5784 = !DISubprogram(name: "exit", scope: !5314, file: !5314, line: 614, type: !5785, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!5785 = !DISubroutineType(types: !5786)
!5786 = !{null, !24}
!5787 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5788, file: !5740, line: 147)
!5788 = !DISubprogram(name: "free", scope: !5314, file: !5314, line: 563, type: !5789, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5789 = !DISubroutineType(types: !5790)
!5790 = !{null, !121}
!5791 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5792, file: !5740, line: 148)
!5792 = !DISubprogram(name: "getenv", scope: !5314, file: !5314, line: 631, type: !5793, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5793 = !DISubroutineType(types: !5794)
!5794 = !{!613, !163}
!5795 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5796, file: !5740, line: 149)
!5796 = !DISubprogram(name: "labs", scope: !5314, file: !5314, line: 838, type: !5797, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5797 = !DISubroutineType(types: !5798)
!5798 = !{!405, !405}
!5799 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5800, file: !5740, line: 150)
!5800 = !DISubprogram(name: "ldiv", scope: !5314, file: !5314, line: 851, type: !5801, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5801 = !DISubroutineType(types: !5802)
!5802 = !{!5742, !405, !405}
!5803 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5804, file: !5740, line: 151)
!5804 = !DISubprogram(name: "malloc", scope: !5314, file: !5314, line: 539, type: !5805, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5805 = !DISubroutineType(types: !5806)
!5806 = !{!121, !159}
!5807 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5808, file: !5740, line: 153)
!5808 = !DISubprogram(name: "mblen", scope: !5314, file: !5314, line: 919, type: !5809, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5809 = !DISubroutineType(types: !5810)
!5810 = !{!24, !163, !159}
!5811 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5812, file: !5740, line: 154)
!5812 = !DISubprogram(name: "mbstowcs", scope: !5314, file: !5314, line: 930, type: !5813, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5813 = !DISubroutineType(types: !5814)
!5814 = !{!159, !5815, !5684, !159}
!5815 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !5816)
!5816 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5817, size: 64)
!5817 = !DIBasicType(name: "wchar_t", size: 32, encoding: DW_ATE_signed)
!5818 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5819, file: !5740, line: 155)
!5819 = !DISubprogram(name: "mbtowc", scope: !5314, file: !5314, line: 922, type: !5820, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5820 = !DISubroutineType(types: !5821)
!5821 = !{!24, !5815, !5684, !159}
!5822 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5823, file: !5740, line: 157)
!5823 = !DISubprogram(name: "qsort", scope: !5314, file: !5314, line: 827, type: !5824, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5824 = !DISubroutineType(types: !5825)
!5825 = !{null, !121, !159, !159, !5771}
!5826 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5827, file: !5740, line: 160)
!5827 = !DISubprogram(name: "quick_exit", scope: !5314, file: !5314, line: 620, type: !5785, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!5828 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5829, file: !5740, line: 163)
!5829 = !DISubprogram(name: "rand", scope: !5314, file: !5314, line: 453, type: !118, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5830 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5831, file: !5740, line: 164)
!5831 = !DISubprogram(name: "realloc", scope: !5314, file: !5314, line: 549, type: !5832, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5832 = !DISubroutineType(types: !5833)
!5833 = !{!121, !121, !159}
!5834 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5835, file: !5740, line: 165)
!5835 = !DISubprogram(name: "srand", scope: !5314, file: !5314, line: 455, type: !5836, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5836 = !DISubroutineType(types: !5837)
!5837 = !{null, !6}
!5838 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5839, file: !5740, line: 166)
!5839 = !DISubprogram(name: "strtod", scope: !5314, file: !5314, line: 117, type: !5840, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5840 = !DISubroutineType(types: !5841)
!5841 = !{!4666, !5684, !5842}
!5842 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !5843)
!5843 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !613, size: 64)
!5844 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5845, file: !5740, line: 167)
!5845 = !DISubprogram(name: "strtol", scope: !5314, file: !5314, line: 176, type: !5846, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5846 = !DISubroutineType(types: !5847)
!5847 = !{!405, !5684, !5842, !24}
!5848 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5849, file: !5740, line: 168)
!5849 = !DISubprogram(name: "strtoul", scope: !5314, file: !5314, line: 180, type: !5850, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5850 = !DISubroutineType(types: !5851)
!5851 = !{!161, !5684, !5842, !24}
!5852 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5853, file: !5740, line: 169)
!5853 = !DISubprogram(name: "system", scope: !5314, file: !5314, line: 781, type: !5760, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5854 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5855, file: !5740, line: 171)
!5855 = !DISubprogram(name: "wcstombs", scope: !5314, file: !5314, line: 933, type: !5856, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5856 = !DISubroutineType(types: !5857)
!5857 = !{!159, !5683, !5858, !159}
!5858 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !5859)
!5859 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5860, size: 64)
!5860 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5817)
!5861 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5862, file: !5740, line: 172)
!5862 = !DISubprogram(name: "wctomb", scope: !5314, file: !5314, line: 926, type: !5863, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5863 = !DISubroutineType(types: !5864)
!5864 = !{!24, !613, !5817}
!5865 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !5866, file: !5740, line: 200)
!5866 = !DIDerivedType(tag: DW_TAG_typedef, name: "lldiv_t", file: !5314, line: 80, baseType: !5867)
!5867 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !5314, line: 76, size: 128, flags: DIFlagTypePassByValue, elements: !5868, identifier: "_ZTS7lldiv_t")
!5868 = !{!5869, !5870}
!5869 = !DIDerivedType(tag: DW_TAG_member, name: "quot", scope: !5867, file: !5314, line: 78, baseType: !413, size: 64)
!5870 = !DIDerivedType(tag: DW_TAG_member, name: "rem", scope: !5867, file: !5314, line: 79, baseType: !413, size: 64, offset: 64)
!5871 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !5872, file: !5740, line: 206)
!5872 = !DISubprogram(name: "_Exit", scope: !5314, file: !5314, line: 626, type: !5785, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!5873 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !5874, file: !5740, line: 210)
!5874 = !DISubprogram(name: "llabs", scope: !5314, file: !5314, line: 841, type: !5875, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5875 = !DISubroutineType(types: !5876)
!5876 = !{!413, !413}
!5877 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !5878, file: !5740, line: 216)
!5878 = !DISubprogram(name: "lldiv", scope: !5314, file: !5314, line: 855, type: !5879, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5879 = !DISubroutineType(types: !5880)
!5880 = !{!5866, !413, !413}
!5881 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !5882, file: !5740, line: 227)
!5882 = !DISubprogram(name: "atoll", scope: !5314, file: !5314, line: 373, type: !5883, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5883 = !DISubroutineType(types: !5884)
!5884 = !{!413, !163}
!5885 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !5886, file: !5740, line: 228)
!5886 = !DISubprogram(name: "strtoll", scope: !5314, file: !5314, line: 200, type: !5887, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5887 = !DISubroutineType(types: !5888)
!5888 = !{!413, !5684, !5842, !24}
!5889 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !5890, file: !5740, line: 229)
!5890 = !DISubprogram(name: "strtoull", scope: !5314, file: !5314, line: 205, type: !5891, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5891 = !DISubroutineType(types: !5892)
!5892 = !{!409, !5684, !5842, !24}
!5893 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !5894, file: !5740, line: 231)
!5894 = !DISubprogram(name: "strtof", scope: !5314, file: !5314, line: 123, type: !5895, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5895 = !DISubroutineType(types: !5896)
!5896 = !{!4798, !5684, !5842}
!5897 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !5898, file: !5740, line: 232)
!5898 = !DISubprogram(name: "strtold", scope: !5314, file: !5314, line: 126, type: !5899, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5899 = !DISubroutineType(types: !5900)
!5900 = !{!5391, !5684, !5842}
!5901 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5866, file: !5740, line: 240)
!5902 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5872, file: !5740, line: 242)
!5903 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5874, file: !5740, line: 244)
!5904 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5905, file: !5740, line: 245)
!5905 = !DISubprogram(name: "div", linkageName: "_ZN9__gnu_cxx3divExx", scope: !5, file: !5740, line: 213, type: !5879, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5906 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5878, file: !5740, line: 246)
!5907 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5882, file: !5740, line: 248)
!5908 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5894, file: !5740, line: 249)
!5909 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5886, file: !5740, line: 250)
!5910 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5890, file: !5740, line: 251)
!5911 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5898, file: !5740, line: 252)
!5912 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5913, file: !5914, line: 57)
!5913 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "exception_ptr", scope: !5915, file: !5914, line: 79, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSNSt15__exception_ptr13exception_ptrE")
!5914 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/exception_ptr.h", directory: "", checksumkind: CSK_MD5, checksum: "25d44782b686509a9fc5c8aaa8066643")
!5915 = !DINamespace(name: "__exception_ptr", scope: !192)
!5916 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5915, entity: !5917, file: !5914, line: 73)
!5917 = !DISubprogram(name: "rethrow_exception", linkageName: "_ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE", scope: !192, file: !5914, line: 69, type: !5918, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!5918 = !DISubroutineType(types: !5919)
!5919 = !{null, !5913}
!5920 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5921, file: !5933, line: 64)
!5921 = !DIDerivedType(tag: DW_TAG_typedef, name: "mbstate_t", file: !5922, line: 6, baseType: !5923)
!5922 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/mbstate_t.h", directory: "", checksumkind: CSK_MD5, checksum: "ba8742313715e20e434cf6ccb2db98e3")
!5923 = !DIDerivedType(tag: DW_TAG_typedef, name: "__mbstate_t", file: !5924, line: 21, baseType: !5925)
!5924 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h", directory: "", checksumkind: CSK_MD5, checksum: "82911a3e689448e3691ded3e0b471a55")
!5925 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !5924, line: 13, size: 64, flags: DIFlagTypePassByValue, elements: !5926, identifier: "_ZTS11__mbstate_t")
!5926 = !{!5927, !5928}
!5927 = !DIDerivedType(tag: DW_TAG_member, name: "__count", scope: !5925, file: !5924, line: 15, baseType: !24, size: 32)
!5928 = !DIDerivedType(tag: DW_TAG_member, name: "__value", scope: !5925, file: !5924, line: 20, baseType: !5929, size: 32, offset: 32)
!5929 = distinct !DICompositeType(tag: DW_TAG_union_type, scope: !5925, file: !5924, line: 16, size: 32, flags: DIFlagTypePassByValue, elements: !5930, identifier: "_ZTSN11__mbstate_tUt_E")
!5930 = !{!5931, !5932}
!5931 = !DIDerivedType(tag: DW_TAG_member, name: "__wch", scope: !5929, file: !5924, line: 18, baseType: !6, size: 32)
!5932 = !DIDerivedType(tag: DW_TAG_member, name: "__wchb", scope: !5929, file: !5924, line: 19, baseType: !795, size: 32)
!5933 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cwchar", directory: "")
!5934 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5935, file: !5933, line: 139)
!5935 = !DIDerivedType(tag: DW_TAG_typedef, name: "wint_t", file: !5936, line: 20, baseType: !6)
!5936 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/wint_t.h", directory: "", checksumkind: CSK_MD5, checksum: "aa31b53ef28dc23152ceb41e2763ded3")
!5937 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5938, file: !5933, line: 141)
!5938 = !DISubprogram(name: "btowc", scope: !5939, file: !5939, line: 318, type: !5940, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5939 = !DIFile(filename: "/usr/include/wchar.h", directory: "", checksumkind: CSK_MD5, checksum: "5c0512b032e303d7adfb2a47454ecb1c")
!5940 = !DISubroutineType(types: !5941)
!5941 = !{!5935, !24}
!5942 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5943, file: !5933, line: 142)
!5943 = !DISubprogram(name: "fgetwc", scope: !5939, file: !5939, line: 727, type: !5944, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5944 = !DISubroutineType(types: !5945)
!5945 = !{!5935, !5946}
!5946 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5947, size: 64)
!5947 = !DIDerivedType(tag: DW_TAG_typedef, name: "__FILE", file: !5948, line: 5, baseType: !5949)
!5948 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h", directory: "", checksumkind: CSK_MD5, checksum: "72a8fe90981f484acae7c6f3dfc5c2b7")
!5949 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_IO_FILE", file: !5950, line: 245, size: 1728, flags: DIFlagTypePassByValue, elements: !5951, identifier: "_ZTS8_IO_FILE")
!5950 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/libio.h", directory: "", checksumkind: CSK_MD5, checksum: "e2b53e448ab24b9cd2ba8684267b8131")
!5951 = !{!5952, !5953, !5954, !5955, !5956, !5957, !5958, !5959, !5960, !5961, !5962, !5963, !5964, !5967, !5969, !5970, !5971, !5973, !5974, !5975, !5976, !5979, !5981, !5982, !5983, !5984, !5985, !5986, !5987}
!5952 = !DIDerivedType(tag: DW_TAG_member, name: "_flags", scope: !5949, file: !5950, line: 246, baseType: !24, size: 32)
!5953 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_ptr", scope: !5949, file: !5950, line: 251, baseType: !613, size: 64, offset: 64)
!5954 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_end", scope: !5949, file: !5950, line: 252, baseType: !613, size: 64, offset: 128)
!5955 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_base", scope: !5949, file: !5950, line: 253, baseType: !613, size: 64, offset: 192)
!5956 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_base", scope: !5949, file: !5950, line: 254, baseType: !613, size: 64, offset: 256)
!5957 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_ptr", scope: !5949, file: !5950, line: 255, baseType: !613, size: 64, offset: 320)
!5958 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_end", scope: !5949, file: !5950, line: 256, baseType: !613, size: 64, offset: 384)
!5959 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_buf_base", scope: !5949, file: !5950, line: 257, baseType: !613, size: 64, offset: 448)
!5960 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_buf_end", scope: !5949, file: !5950, line: 258, baseType: !613, size: 64, offset: 512)
!5961 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_save_base", scope: !5949, file: !5950, line: 260, baseType: !613, size: 64, offset: 576)
!5962 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_backup_base", scope: !5949, file: !5950, line: 261, baseType: !613, size: 64, offset: 640)
!5963 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_save_end", scope: !5949, file: !5950, line: 262, baseType: !613, size: 64, offset: 704)
!5964 = !DIDerivedType(tag: DW_TAG_member, name: "_markers", scope: !5949, file: !5950, line: 264, baseType: !5965, size: 64, offset: 768)
!5965 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5966, size: 64)
!5966 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_IO_marker", file: !5950, line: 160, size: 192, flags: DIFlagFwdDecl, identifier: "_ZTS10_IO_marker")
!5967 = !DIDerivedType(tag: DW_TAG_member, name: "_chain", scope: !5949, file: !5950, line: 266, baseType: !5968, size: 64, offset: 832)
!5968 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5949, size: 64)
!5969 = !DIDerivedType(tag: DW_TAG_member, name: "_fileno", scope: !5949, file: !5950, line: 268, baseType: !24, size: 32, offset: 896)
!5970 = !DIDerivedType(tag: DW_TAG_member, name: "_flags2", scope: !5949, file: !5950, line: 272, baseType: !24, size: 32, offset: 928)
!5971 = !DIDerivedType(tag: DW_TAG_member, name: "_old_offset", scope: !5949, file: !5950, line: 274, baseType: !5972, size: 64, offset: 960)
!5972 = !DIDerivedType(tag: DW_TAG_typedef, name: "__off_t", file: !420, line: 140, baseType: !405)
!5973 = !DIDerivedType(tag: DW_TAG_member, name: "_cur_column", scope: !5949, file: !5950, line: 278, baseType: !4833, size: 16, offset: 1024)
!5974 = !DIDerivedType(tag: DW_TAG_member, name: "_vtable_offset", scope: !5949, file: !5950, line: 279, baseType: !490, size: 8, offset: 1040)
!5975 = !DIDerivedType(tag: DW_TAG_member, name: "_shortbuf", scope: !5949, file: !5950, line: 280, baseType: !581, size: 8, offset: 1048)
!5976 = !DIDerivedType(tag: DW_TAG_member, name: "_lock", scope: !5949, file: !5950, line: 284, baseType: !5977, size: 64, offset: 1088)
!5977 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5978, size: 64)
!5978 = !DIDerivedType(tag: DW_TAG_typedef, name: "_IO_lock_t", file: !5950, line: 154, baseType: null)
!5979 = !DIDerivedType(tag: DW_TAG_member, name: "_offset", scope: !5949, file: !5950, line: 293, baseType: !5980, size: 64, offset: 1152)
!5980 = !DIDerivedType(tag: DW_TAG_typedef, name: "__off64_t", file: !420, line: 141, baseType: !405)
!5981 = !DIDerivedType(tag: DW_TAG_member, name: "__pad1", scope: !5949, file: !5950, line: 301, baseType: !121, size: 64, offset: 1216)
!5982 = !DIDerivedType(tag: DW_TAG_member, name: "__pad2", scope: !5949, file: !5950, line: 302, baseType: !121, size: 64, offset: 1280)
!5983 = !DIDerivedType(tag: DW_TAG_member, name: "__pad3", scope: !5949, file: !5950, line: 303, baseType: !121, size: 64, offset: 1344)
!5984 = !DIDerivedType(tag: DW_TAG_member, name: "__pad4", scope: !5949, file: !5950, line: 304, baseType: !121, size: 64, offset: 1408)
!5985 = !DIDerivedType(tag: DW_TAG_member, name: "__pad5", scope: !5949, file: !5950, line: 306, baseType: !159, size: 64, offset: 1472)
!5986 = !DIDerivedType(tag: DW_TAG_member, name: "_mode", scope: !5949, file: !5950, line: 307, baseType: !24, size: 32, offset: 1536)
!5987 = !DIDerivedType(tag: DW_TAG_member, name: "_unused2", scope: !5949, file: !5950, line: 309, baseType: !5988, size: 160, offset: 1568)
!5988 = !DICompositeType(tag: DW_TAG_array_type, baseType: !165, size: 160, elements: !5022)
!5989 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5990, file: !5933, line: 143)
!5990 = !DISubprogram(name: "fgetws", scope: !5939, file: !5939, line: 756, type: !5991, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5991 = !DISubroutineType(types: !5992)
!5992 = !{!5816, !5815, !24, !5993}
!5993 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !5946)
!5994 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5995, file: !5933, line: 144)
!5995 = !DISubprogram(name: "fputwc", scope: !5939, file: !5939, line: 741, type: !5996, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5996 = !DISubroutineType(types: !5997)
!5997 = !{!5935, !5817, !5946}
!5998 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5999, file: !5933, line: 145)
!5999 = !DISubprogram(name: "fputws", scope: !5939, file: !5939, line: 763, type: !6000, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6000 = !DISubroutineType(types: !6001)
!6001 = !{!24, !5858, !5993}
!6002 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6003, file: !5933, line: 146)
!6003 = !DISubprogram(name: "fwide", scope: !5939, file: !5939, line: 573, type: !6004, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6004 = !DISubroutineType(types: !6005)
!6005 = !{!24, !5946, !24}
!6006 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6007, file: !5933, line: 147)
!6007 = !DISubprogram(name: "fwprintf", scope: !5939, file: !5939, line: 580, type: !6008, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6008 = !DISubroutineType(types: !6009)
!6009 = !{!24, !5993, !5858, null}
!6010 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6011, file: !5933, line: 148)
!6011 = !DISubprogram(name: "fwscanf", scope: !5939, file: !5939, line: 621, type: !6008, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6012 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6013, file: !5933, line: 149)
!6013 = !DISubprogram(name: "getwc", scope: !5939, file: !5939, line: 728, type: !5944, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6014 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6015, file: !5933, line: 150)
!6015 = !DISubprogram(name: "getwchar", scope: !5939, file: !5939, line: 734, type: !6016, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6016 = !DISubroutineType(types: !6017)
!6017 = !{!5935}
!6018 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6019, file: !5933, line: 151)
!6019 = !DISubprogram(name: "mbrlen", scope: !5939, file: !5939, line: 329, type: !6020, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6020 = !DISubroutineType(types: !6021)
!6021 = !{!159, !5684, !159, !6022}
!6022 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6023)
!6023 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5921, size: 64)
!6024 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6025, file: !5933, line: 152)
!6025 = !DISubprogram(name: "mbrtowc", scope: !5939, file: !5939, line: 296, type: !6026, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6026 = !DISubroutineType(types: !6027)
!6027 = !{!159, !5815, !5684, !159, !6022}
!6028 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6029, file: !5933, line: 153)
!6029 = !DISubprogram(name: "mbsinit", scope: !5939, file: !5939, line: 292, type: !6030, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6030 = !DISubroutineType(types: !6031)
!6031 = !{!24, !6032}
!6032 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6033, size: 64)
!6033 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5921)
!6034 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6035, file: !5933, line: 154)
!6035 = !DISubprogram(name: "mbsrtowcs", scope: !5939, file: !5939, line: 337, type: !6036, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6036 = !DISubroutineType(types: !6037)
!6037 = !{!159, !5815, !6038, !159, !6022}
!6038 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3861)
!6039 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6040, file: !5933, line: 155)
!6040 = !DISubprogram(name: "putwc", scope: !5939, file: !5939, line: 742, type: !5996, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6041 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6042, file: !5933, line: 156)
!6042 = !DISubprogram(name: "putwchar", scope: !5939, file: !5939, line: 748, type: !6043, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6043 = !DISubroutineType(types: !6044)
!6044 = !{!5935, !5817}
!6045 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6046, file: !5933, line: 158)
!6046 = !DISubprogram(name: "swprintf", scope: !5939, file: !5939, line: 590, type: !6047, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6047 = !DISubroutineType(types: !6048)
!6048 = !{!24, !5815, !159, !5858, null}
!6049 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6050, file: !5933, line: 160)
!6050 = !DISubprogram(name: "swscanf", scope: !5939, file: !5939, line: 631, type: !6051, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6051 = !DISubroutineType(types: !6052)
!6052 = !{!24, !5858, !5858, null}
!6053 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6054, file: !5933, line: 161)
!6054 = !DISubprogram(name: "ungetwc", scope: !5939, file: !5939, line: 771, type: !6055, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6055 = !DISubroutineType(types: !6056)
!6056 = !{!5935, !5935, !5946}
!6057 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6058, file: !5933, line: 162)
!6058 = !DISubprogram(name: "vfwprintf", scope: !5939, file: !5939, line: 598, type: !6059, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6059 = !DISubroutineType(types: !6060)
!6060 = !{!24, !5993, !5858, !6061}
!6061 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6062, size: 64)
!6062 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__va_list_tag", size: 192, flags: DIFlagTypePassByValue, elements: !6063, identifier: "_ZTS13__va_list_tag")
!6063 = !{!6064, !6066, !6067, !6068}
!6064 = !DIDerivedType(tag: DW_TAG_member, name: "gp_offset", scope: !6062, file: !6065, baseType: !6, size: 32)
!6065 = !DIFile(filename: "llvm34/lib/Support/YAMLTraits.cpp", directory: "/fast/fs")
!6066 = !DIDerivedType(tag: DW_TAG_member, name: "fp_offset", scope: !6062, file: !6065, baseType: !6, size: 32, offset: 32)
!6067 = !DIDerivedType(tag: DW_TAG_member, name: "overflow_arg_area", scope: !6062, file: !6065, baseType: !121, size: 64, offset: 64)
!6068 = !DIDerivedType(tag: DW_TAG_member, name: "reg_save_area", scope: !6062, file: !6065, baseType: !121, size: 64, offset: 128)
!6069 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6070, file: !5933, line: 164)
!6070 = !DISubprogram(name: "vfwscanf", scope: !5939, file: !5939, line: 673, type: !6059, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6071 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6072, file: !5933, line: 167)
!6072 = !DISubprogram(name: "vswprintf", scope: !5939, file: !5939, line: 611, type: !6073, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6073 = !DISubroutineType(types: !6074)
!6074 = !{!24, !5815, !159, !5858, !6061}
!6075 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6076, file: !5933, line: 170)
!6076 = !DISubprogram(name: "vswscanf", scope: !5939, file: !5939, line: 685, type: !6077, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6077 = !DISubroutineType(types: !6078)
!6078 = !{!24, !5858, !5858, !6061}
!6079 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6080, file: !5933, line: 172)
!6080 = !DISubprogram(name: "vwprintf", scope: !5939, file: !5939, line: 606, type: !6081, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6081 = !DISubroutineType(types: !6082)
!6082 = !{!24, !5858, !6061}
!6083 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6084, file: !5933, line: 174)
!6084 = !DISubprogram(name: "vwscanf", scope: !5939, file: !5939, line: 681, type: !6081, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6085 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6086, file: !5933, line: 176)
!6086 = !DISubprogram(name: "wcrtomb", scope: !5939, file: !5939, line: 301, type: !6087, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6087 = !DISubroutineType(types: !6088)
!6088 = !{!159, !5683, !5817, !6022}
!6089 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6090, file: !5933, line: 177)
!6090 = !DISubprogram(name: "wcscat", scope: !5939, file: !5939, line: 97, type: !6091, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6091 = !DISubroutineType(types: !6092)
!6092 = !{!5816, !5815, !5858}
!6093 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6094, file: !5933, line: 178)
!6094 = !DISubprogram(name: "wcscmp", scope: !5939, file: !5939, line: 106, type: !6095, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6095 = !DISubroutineType(types: !6096)
!6096 = !{!24, !5859, !5859}
!6097 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6098, file: !5933, line: 179)
!6098 = !DISubprogram(name: "wcscoll", scope: !5939, file: !5939, line: 131, type: !6095, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6099 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6100, file: !5933, line: 180)
!6100 = !DISubprogram(name: "wcscpy", scope: !5939, file: !5939, line: 87, type: !6091, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6101 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6102, file: !5933, line: 181)
!6102 = !DISubprogram(name: "wcscspn", scope: !5939, file: !5939, line: 187, type: !6103, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6103 = !DISubroutineType(types: !6104)
!6104 = !{!159, !5859, !5859}
!6105 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6106, file: !5933, line: 182)
!6106 = !DISubprogram(name: "wcsftime", scope: !5939, file: !5939, line: 835, type: !6107, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6107 = !DISubroutineType(types: !6108)
!6108 = !{!159, !5815, !159, !5858, !6109}
!6109 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6110)
!6110 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6111, size: 64)
!6111 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6112)
!6112 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "tm", file: !5939, line: 83, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTS2tm")
!6113 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6114, file: !5933, line: 183)
!6114 = !DISubprogram(name: "wcslen", scope: !5939, file: !5939, line: 222, type: !6115, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6115 = !DISubroutineType(types: !6116)
!6116 = !{!159, !5859}
!6117 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6118, file: !5933, line: 184)
!6118 = !DISubprogram(name: "wcsncat", scope: !5939, file: !5939, line: 101, type: !6119, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6119 = !DISubroutineType(types: !6120)
!6120 = !{!5816, !5815, !5858, !159}
!6121 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6122, file: !5933, line: 185)
!6122 = !DISubprogram(name: "wcsncmp", scope: !5939, file: !5939, line: 109, type: !6123, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6123 = !DISubroutineType(types: !6124)
!6124 = !{!24, !5859, !5859, !159}
!6125 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6126, file: !5933, line: 186)
!6126 = !DISubprogram(name: "wcsncpy", scope: !5939, file: !5939, line: 92, type: !6119, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6127 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6128, file: !5933, line: 187)
!6128 = !DISubprogram(name: "wcsrtombs", scope: !5939, file: !5939, line: 343, type: !6129, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6129 = !DISubroutineType(types: !6130)
!6130 = !{!159, !5683, !6131, !159, !6022}
!6131 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6132)
!6132 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5859, size: 64)
!6133 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6134, file: !5933, line: 188)
!6134 = !DISubprogram(name: "wcsspn", scope: !5939, file: !5939, line: 191, type: !6103, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6135 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6136, file: !5933, line: 189)
!6136 = !DISubprogram(name: "wcstod", scope: !5939, file: !5939, line: 377, type: !6137, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6137 = !DISubroutineType(types: !6138)
!6138 = !{!4666, !5858, !6139}
!6139 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6140)
!6140 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5816, size: 64)
!6141 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6142, file: !5933, line: 191)
!6142 = !DISubprogram(name: "wcstof", scope: !5939, file: !5939, line: 382, type: !6143, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6143 = !DISubroutineType(types: !6144)
!6144 = !{!4798, !5858, !6139}
!6145 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6146, file: !5933, line: 193)
!6146 = !DISubprogram(name: "wcstok", scope: !5939, file: !5939, line: 217, type: !6147, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6147 = !DISubroutineType(types: !6148)
!6148 = !{!5816, !5815, !5858, !6139}
!6149 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6150, file: !5933, line: 194)
!6150 = !DISubprogram(name: "wcstol", scope: !5939, file: !5939, line: 428, type: !6151, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6151 = !DISubroutineType(types: !6152)
!6152 = !{!405, !5858, !6139, !24}
!6153 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6154, file: !5933, line: 195)
!6154 = !DISubprogram(name: "wcstoul", scope: !5939, file: !5939, line: 433, type: !6155, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6155 = !DISubroutineType(types: !6156)
!6156 = !{!161, !5858, !6139, !24}
!6157 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6158, file: !5933, line: 196)
!6158 = !DISubprogram(name: "wcsxfrm", scope: !5939, file: !5939, line: 135, type: !6159, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6159 = !DISubroutineType(types: !6160)
!6160 = !{!159, !5815, !5858, !159}
!6161 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6162, file: !5933, line: 197)
!6162 = !DISubprogram(name: "wctob", scope: !5939, file: !5939, line: 324, type: !6163, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6163 = !DISubroutineType(types: !6164)
!6164 = !{!24, !5935}
!6165 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6166, file: !5933, line: 198)
!6166 = !DISubprogram(name: "wmemcmp", scope: !5939, file: !5939, line: 258, type: !6123, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6167 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6168, file: !5933, line: 199)
!6168 = !DISubprogram(name: "wmemcpy", scope: !5939, file: !5939, line: 262, type: !6119, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6169 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6170, file: !5933, line: 200)
!6170 = !DISubprogram(name: "wmemmove", scope: !5939, file: !5939, line: 267, type: !6171, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6171 = !DISubroutineType(types: !6172)
!6172 = !{!5816, !5816, !5859, !159}
!6173 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6174, file: !5933, line: 201)
!6174 = !DISubprogram(name: "wmemset", scope: !5939, file: !5939, line: 271, type: !6175, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6175 = !DISubroutineType(types: !6176)
!6176 = !{!5816, !5816, !5817, !159}
!6177 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6178, file: !5933, line: 202)
!6178 = !DISubprogram(name: "wprintf", scope: !5939, file: !5939, line: 587, type: !6179, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6179 = !DISubroutineType(types: !6180)
!6180 = !{!24, !5858, null}
!6181 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6182, file: !5933, line: 203)
!6182 = !DISubprogram(name: "wscanf", scope: !5939, file: !5939, line: 628, type: !6179, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6183 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6184, file: !5933, line: 204)
!6184 = !DISubprogram(name: "wcschr", scope: !5939, file: !5939, line: 164, type: !6185, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6185 = !DISubroutineType(types: !6186)
!6186 = !{!5816, !5859, !5817}
!6187 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6188, file: !5933, line: 205)
!6188 = !DISubprogram(name: "wcspbrk", scope: !5939, file: !5939, line: 201, type: !6189, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6189 = !DISubroutineType(types: !6190)
!6190 = !{!5816, !5859, !5859}
!6191 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6192, file: !5933, line: 206)
!6192 = !DISubprogram(name: "wcsrchr", scope: !5939, file: !5939, line: 174, type: !6185, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6193 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6194, file: !5933, line: 207)
!6194 = !DISubprogram(name: "wcsstr", scope: !5939, file: !5939, line: 212, type: !6189, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6195 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6196, file: !5933, line: 208)
!6196 = !DISubprogram(name: "wmemchr", scope: !5939, file: !5939, line: 253, type: !6197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6197 = !DISubroutineType(types: !6198)
!6198 = !{!5816, !5859, !5817, !159}
!6199 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6200, file: !5933, line: 248)
!6200 = !DISubprogram(name: "wcstold", scope: !5939, file: !5939, line: 384, type: !6201, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6201 = !DISubroutineType(types: !6202)
!6202 = !{!5391, !5858, !6139}
!6203 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6204, file: !5933, line: 257)
!6204 = !DISubprogram(name: "wcstoll", scope: !5939, file: !5939, line: 441, type: !6205, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6205 = !DISubroutineType(types: !6206)
!6206 = !{!413, !5858, !6139, !24}
!6207 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6208, file: !5933, line: 258)
!6208 = !DISubprogram(name: "wcstoull", scope: !5939, file: !5939, line: 448, type: !6209, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6209 = !DISubroutineType(types: !6210)
!6210 = !{!409, !5858, !6139, !24}
!6211 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6200, file: !5933, line: 264)
!6212 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6204, file: !5933, line: 265)
!6213 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6208, file: !5933, line: 266)
!6214 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6142, file: !5933, line: 280)
!6215 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6070, file: !5933, line: 283)
!6216 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6076, file: !5933, line: 286)
!6217 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6084, file: !5933, line: 289)
!6218 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6200, file: !5933, line: 293)
!6219 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6204, file: !5933, line: 294)
!6220 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6208, file: !5933, line: 295)
!6221 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6222, file: !6225, line: 48)
!6222 = !DIDerivedType(tag: DW_TAG_typedef, name: "int8_t", file: !6223, line: 24, baseType: !6224)
!6223 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h", directory: "", checksumkind: CSK_MD5, checksum: "457547631e07cd24d9a14c8410e28e57")
!6224 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int8_t", file: !420, line: 36, baseType: !490)
!6225 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdint", directory: "")
!6226 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6227, file: !6225, line: 49)
!6227 = !DIDerivedType(tag: DW_TAG_typedef, name: "int16_t", file: !6223, line: 25, baseType: !6228)
!6228 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int16_t", file: !420, line: 38, baseType: !6229)
!6229 = !DIBasicType(name: "short", size: 16, encoding: DW_ATE_signed)
!6230 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6231, file: !6225, line: 50)
!6231 = !DIDerivedType(tag: DW_TAG_typedef, name: "int32_t", file: !6223, line: 26, baseType: !6232)
!6232 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int32_t", file: !420, line: 40, baseType: !24)
!6233 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6234, file: !6225, line: 51)
!6234 = !DIDerivedType(tag: DW_TAG_typedef, name: "int64_t", file: !6223, line: 27, baseType: !6235)
!6235 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int64_t", file: !420, line: 43, baseType: !405)
!6236 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6237, file: !6225, line: 53)
!6237 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast8_t", file: !6238, line: 68, baseType: !490)
!6238 = !DIFile(filename: "/usr/include/stdint.h", directory: "", checksumkind: CSK_MD5, checksum: "c7469e3b87cb3d1a363efabd19f04208")
!6239 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6240, file: !6225, line: 54)
!6240 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast16_t", file: !6238, line: 70, baseType: !405)
!6241 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6242, file: !6225, line: 55)
!6242 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast32_t", file: !6238, line: 71, baseType: !405)
!6243 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6244, file: !6225, line: 56)
!6244 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast64_t", file: !6238, line: 72, baseType: !405)
!6245 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6246, file: !6225, line: 58)
!6246 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least8_t", file: !6238, line: 43, baseType: !490)
!6247 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6248, file: !6225, line: 59)
!6248 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least16_t", file: !6238, line: 44, baseType: !6229)
!6249 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6250, file: !6225, line: 60)
!6250 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least32_t", file: !6238, line: 45, baseType: !24)
!6251 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6252, file: !6225, line: 61)
!6252 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least64_t", file: !6238, line: 47, baseType: !405)
!6253 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6254, file: !6225, line: 63)
!6254 = !DIDerivedType(tag: DW_TAG_typedef, name: "intmax_t", file: !6238, line: 111, baseType: !6255)
!6255 = !DIDerivedType(tag: DW_TAG_typedef, name: "__intmax_t", file: !420, line: 61, baseType: !405)
!6256 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6257, file: !6225, line: 64)
!6257 = !DIDerivedType(tag: DW_TAG_typedef, name: "intptr_t", file: !6238, line: 97, baseType: !405)
!6258 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6259, file: !6225, line: 66)
!6259 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint8_t", file: !418, line: 24, baseType: !6260)
!6260 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint8_t", file: !420, line: 37, baseType: !423)
!6261 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6262, file: !6225, line: 67)
!6262 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint16_t", file: !418, line: 25, baseType: !6263)
!6263 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint16_t", file: !420, line: 39, baseType: !4833)
!6264 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6265, file: !6225, line: 68)
!6265 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint32_t", file: !418, line: 26, baseType: !6266)
!6266 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint32_t", file: !420, line: 41, baseType: !6)
!6267 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !417, file: !6225, line: 69)
!6268 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6269, file: !6225, line: 71)
!6269 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast8_t", file: !6238, line: 81, baseType: !423)
!6270 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6271, file: !6225, line: 72)
!6271 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast16_t", file: !6238, line: 83, baseType: !161)
!6272 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6273, file: !6225, line: 73)
!6273 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast32_t", file: !6238, line: 84, baseType: !161)
!6274 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6275, file: !6225, line: 74)
!6275 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast64_t", file: !6238, line: 85, baseType: !161)
!6276 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6277, file: !6225, line: 76)
!6277 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least8_t", file: !6238, line: 54, baseType: !423)
!6278 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6279, file: !6225, line: 77)
!6279 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least16_t", file: !6238, line: 55, baseType: !4833)
!6280 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6281, file: !6225, line: 78)
!6281 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least32_t", file: !6238, line: 56, baseType: !6)
!6282 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6283, file: !6225, line: 79)
!6283 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least64_t", file: !6238, line: 58, baseType: !161)
!6284 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6285, file: !6225, line: 81)
!6285 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintmax_t", file: !6238, line: 112, baseType: !6286)
!6286 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uintmax_t", file: !420, line: 62, baseType: !161)
!6287 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6288, file: !6225, line: 82)
!6288 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintptr_t", file: !6238, line: 100, baseType: !161)
!6289 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6290, file: !6292, line: 53)
!6290 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "lconv", file: !6291, line: 51, size: 768, flags: DIFlagFwdDecl, identifier: "_ZTS5lconv")
!6291 = !DIFile(filename: "/usr/include/locale.h", directory: "", checksumkind: CSK_MD5, checksum: "0595275e3f5b502d28f7cd61a0dff888")
!6292 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/clocale", directory: "")
!6293 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6294, file: !6292, line: 54)
!6294 = !DISubprogram(name: "setlocale", scope: !6291, file: !6291, line: 122, type: !6295, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6295 = !DISubroutineType(types: !6296)
!6296 = !{!613, !24, !163}
!6297 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6298, file: !6292, line: 55)
!6298 = !DISubprogram(name: "localeconv", scope: !6291, file: !6291, line: 125, type: !6299, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6299 = !DISubroutineType(types: !6300)
!6300 = !{!6301}
!6301 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6290, size: 64)
!6302 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6303, file: !6305, line: 64)
!6303 = !DISubprogram(name: "isalnum", scope: !6304, file: !6304, line: 108, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6304 = !DIFile(filename: "/usr/include/ctype.h", directory: "", checksumkind: CSK_MD5, checksum: "c67c809b09ef8ea9c273687bc20a7fd3")
!6305 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cctype", directory: "")
!6306 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6307, file: !6305, line: 65)
!6307 = !DISubprogram(name: "isalpha", scope: !6304, file: !6304, line: 109, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6308 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6309, file: !6305, line: 66)
!6309 = !DISubprogram(name: "iscntrl", scope: !6304, file: !6304, line: 110, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6310 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6311, file: !6305, line: 67)
!6311 = !DISubprogram(name: "isdigit", scope: !6304, file: !6304, line: 111, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6312 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6313, file: !6305, line: 68)
!6313 = !DISubprogram(name: "isgraph", scope: !6304, file: !6304, line: 113, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6314 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6315, file: !6305, line: 69)
!6315 = !DISubprogram(name: "islower", scope: !6304, file: !6304, line: 112, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6316 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6317, file: !6305, line: 70)
!6317 = !DISubprogram(name: "isprint", scope: !6304, file: !6304, line: 114, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6318 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6319, file: !6305, line: 71)
!6319 = !DISubprogram(name: "ispunct", scope: !6304, file: !6304, line: 115, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6320 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6321, file: !6305, line: 72)
!6321 = !DISubprogram(name: "isspace", scope: !6304, file: !6304, line: 116, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6322 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6323, file: !6305, line: 73)
!6323 = !DISubprogram(name: "isupper", scope: !6304, file: !6304, line: 117, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6324 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6325, file: !6305, line: 74)
!6325 = !DISubprogram(name: "isxdigit", scope: !6304, file: !6304, line: 118, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6326 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6327, file: !6305, line: 75)
!6327 = !DISubprogram(name: "tolower", scope: !6304, file: !6304, line: 122, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6328 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6329, file: !6305, line: 76)
!6329 = !DISubprogram(name: "toupper", scope: !6304, file: !6304, line: 125, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6330 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6331, file: !6305, line: 87)
!6331 = !DISubprogram(name: "isblank", scope: !6304, file: !6304, line: 130, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6332 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !1152, file: !1121, line: 44)
!6333 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !1382, file: !1121, line: 45)
!6334 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6335, file: !6337, line: 98)
!6335 = !DIDerivedType(tag: DW_TAG_typedef, name: "FILE", file: !6336, line: 7, baseType: !5949)
!6336 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/FILE.h", directory: "", checksumkind: CSK_MD5, checksum: "571f9fb6223c42439075fdde11a0de5d")
!6337 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdio", directory: "")
!6338 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6339, file: !6337, line: 99)
!6339 = !DIDerivedType(tag: DW_TAG_typedef, name: "fpos_t", file: !6340, line: 78, baseType: !6341)
!6340 = !DIFile(filename: "/usr/include/stdio.h", directory: "", checksumkind: CSK_MD5, checksum: "2ab51d960d7d0ed84798d1688a6988b0")
!6341 = !DIDerivedType(tag: DW_TAG_typedef, name: "_G_fpos_t", file: !6342, line: 30, baseType: !6343)
!6342 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/_G_config.h", directory: "", checksumkind: CSK_MD5, checksum: "f78480ecfcae11a7bda5a6b08034c1fb")
!6343 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !6342, line: 26, size: 128, flags: DIFlagFwdDecl, identifier: "_ZTS9_G_fpos_t")
!6344 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6345, file: !6337, line: 101)
!6345 = !DISubprogram(name: "clearerr", scope: !6340, file: !6340, line: 757, type: !6346, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6346 = !DISubroutineType(types: !6347)
!6347 = !{null, !6348}
!6348 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6335, size: 64)
!6349 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6350, file: !6337, line: 102)
!6350 = !DISubprogram(name: "fclose", scope: !6340, file: !6340, line: 199, type: !6351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6351 = !DISubroutineType(types: !6352)
!6352 = !{!24, !6348}
!6353 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6354, file: !6337, line: 103)
!6354 = !DISubprogram(name: "feof", scope: !6340, file: !6340, line: 759, type: !6351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6355 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6356, file: !6337, line: 104)
!6356 = !DISubprogram(name: "ferror", scope: !6340, file: !6340, line: 761, type: !6351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6357 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6358, file: !6337, line: 105)
!6358 = !DISubprogram(name: "fflush", scope: !6340, file: !6340, line: 204, type: !6351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6359 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6360, file: !6337, line: 106)
!6360 = !DISubprogram(name: "fgetc", scope: !6340, file: !6340, line: 477, type: !6351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6361 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6362, file: !6337, line: 107)
!6362 = !DISubprogram(name: "fgetpos", scope: !6340, file: !6340, line: 731, type: !6363, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6363 = !DISubroutineType(types: !6364)
!6364 = !{!24, !6365, !6366}
!6365 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6348)
!6366 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6367)
!6367 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6339, size: 64)
!6368 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6369, file: !6337, line: 108)
!6369 = !DISubprogram(name: "fgets", scope: !6340, file: !6340, line: 564, type: !6370, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6370 = !DISubroutineType(types: !6371)
!6371 = !{!613, !5683, !24, !6365}
!6372 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6373, file: !6337, line: 109)
!6373 = !DISubprogram(name: "fopen", scope: !6340, file: !6340, line: 232, type: !6374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6374 = !DISubroutineType(types: !6375)
!6375 = !{!6348, !5684, !5684}
!6376 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6377, file: !6337, line: 110)
!6377 = !DISubprogram(name: "fprintf", scope: !6340, file: !6340, line: 312, type: !6378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6378 = !DISubroutineType(types: !6379)
!6379 = !{!24, !6365, !5684, null}
!6380 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6381, file: !6337, line: 111)
!6381 = !DISubprogram(name: "fputc", scope: !6340, file: !6340, line: 517, type: !6382, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6382 = !DISubroutineType(types: !6383)
!6383 = !{!24, !24, !6348}
!6384 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6385, file: !6337, line: 112)
!6385 = !DISubprogram(name: "fputs", scope: !6340, file: !6340, line: 626, type: !6386, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6386 = !DISubroutineType(types: !6387)
!6387 = !{!24, !5684, !6365}
!6388 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6389, file: !6337, line: 113)
!6389 = !DISubprogram(name: "fread", scope: !6340, file: !6340, line: 646, type: !6390, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6390 = !DISubroutineType(types: !6391)
!6391 = !{!159, !5669, !159, !159, !6365}
!6392 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6393, file: !6337, line: 114)
!6393 = !DISubprogram(name: "freopen", scope: !6340, file: !6340, line: 238, type: !6394, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6394 = !DISubroutineType(types: !6395)
!6395 = !{!6348, !5684, !5684, !6365}
!6396 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6397, file: !6337, line: 115)
!6397 = !DISubprogram(name: "fscanf", scope: !6340, file: !6340, line: 377, type: !6378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6398 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6399, file: !6337, line: 116)
!6399 = !DISubprogram(name: "fseek", scope: !6340, file: !6340, line: 684, type: !6400, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6400 = !DISubroutineType(types: !6401)
!6401 = !{!24, !6348, !405, !24}
!6402 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6403, file: !6337, line: 117)
!6403 = !DISubprogram(name: "fsetpos", scope: !6340, file: !6340, line: 736, type: !6404, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6404 = !DISubroutineType(types: !6405)
!6405 = !{!24, !6348, !6406}
!6406 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6407, size: 64)
!6407 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6339)
!6408 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6409, file: !6337, line: 118)
!6409 = !DISubprogram(name: "ftell", scope: !6340, file: !6340, line: 689, type: !6410, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6410 = !DISubroutineType(types: !6411)
!6411 = !{!405, !6348}
!6412 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6413, file: !6337, line: 119)
!6413 = !DISubprogram(name: "fwrite", scope: !6340, file: !6340, line: 652, type: !6414, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6414 = !DISubroutineType(types: !6415)
!6415 = !{!159, !5670, !159, !159, !6365}
!6416 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6417, file: !6337, line: 120)
!6417 = !DISubprogram(name: "getc", scope: !6340, file: !6340, line: 478, type: !6351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6418 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6419, file: !6337, line: 121)
!6419 = !DISubprogram(name: "getchar", scope: !6420, file: !6420, line: 44, type: !118, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6420 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdio.h", directory: "", checksumkind: CSK_MD5, checksum: "ae874477a6b090849220f12acdd69dc3")
!6421 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6422, file: !6337, line: 126)
!6422 = !DISubprogram(name: "perror", scope: !6340, file: !6340, line: 775, type: !6423, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6423 = !DISubroutineType(types: !6424)
!6424 = !{null, !163}
!6425 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6426, file: !6337, line: 127)
!6426 = !DISubprogram(name: "printf", scope: !6340, file: !6340, line: 318, type: !6427, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6427 = !DISubroutineType(types: !6428)
!6428 = !{!24, !5684, null}
!6429 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6430, file: !6337, line: 128)
!6430 = !DISubprogram(name: "putc", scope: !6340, file: !6340, line: 518, type: !6382, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6431 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6432, file: !6337, line: 129)
!6432 = !DISubprogram(name: "putchar", scope: !6420, file: !6420, line: 79, type: !5315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6433 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6434, file: !6337, line: 130)
!6434 = !DISubprogram(name: "puts", scope: !6340, file: !6340, line: 632, type: !5760, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6435 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6436, file: !6337, line: 131)
!6436 = !DISubprogram(name: "remove", scope: !6340, file: !6340, line: 144, type: !5760, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6437 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6438, file: !6337, line: 132)
!6438 = !DISubprogram(name: "rename", scope: !6340, file: !6340, line: 146, type: !5687, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6439 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6440, file: !6337, line: 133)
!6440 = !DISubprogram(name: "rewind", scope: !6340, file: !6340, line: 694, type: !6346, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6441 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6442, file: !6337, line: 134)
!6442 = !DISubprogram(name: "scanf", scope: !6340, file: !6340, line: 383, type: !6427, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6443 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6444, file: !6337, line: 135)
!6444 = !DISubprogram(name: "setbuf", scope: !6340, file: !6340, line: 290, type: !6445, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6445 = !DISubroutineType(types: !6446)
!6446 = !{null, !6365, !5683}
!6447 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6448, file: !6337, line: 136)
!6448 = !DISubprogram(name: "setvbuf", scope: !6340, file: !6340, line: 294, type: !6449, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6449 = !DISubroutineType(types: !6450)
!6450 = !{!24, !6365, !5683, !24, !159}
!6451 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6452, file: !6337, line: 137)
!6452 = !DISubprogram(name: "sprintf", scope: !6340, file: !6340, line: 320, type: !6453, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6453 = !DISubroutineType(types: !6454)
!6454 = !{!24, !5683, !5684, null}
!6455 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6456, file: !6337, line: 138)
!6456 = !DISubprogram(name: "sscanf", scope: !6340, file: !6340, line: 385, type: !6457, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6457 = !DISubroutineType(types: !6458)
!6458 = !{!24, !5684, !5684, null}
!6459 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6460, file: !6337, line: 139)
!6460 = !DISubprogram(name: "tmpfile", scope: !6340, file: !6340, line: 159, type: !6461, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6461 = !DISubroutineType(types: !6462)
!6462 = !{!6348}
!6463 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6464, file: !6337, line: 141)
!6464 = !DISubprogram(name: "tmpnam", scope: !6340, file: !6340, line: 173, type: !6465, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6465 = !DISubroutineType(types: !6466)
!6466 = !{!613, !613}
!6467 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6468, file: !6337, line: 143)
!6468 = !DISubprogram(name: "ungetc", scope: !6340, file: !6340, line: 639, type: !6382, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6469 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6470, file: !6337, line: 144)
!6470 = !DISubprogram(name: "vfprintf", scope: !6340, file: !6340, line: 327, type: !6471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6471 = !DISubroutineType(types: !6472)
!6472 = !{!24, !6365, !5684, !6061}
!6473 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6474, file: !6337, line: 145)
!6474 = !DISubprogram(name: "vprintf", scope: !6420, file: !6420, line: 36, type: !6475, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6475 = !DISubroutineType(types: !6476)
!6476 = !{!24, !5684, !6061}
!6477 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6478, file: !6337, line: 146)
!6478 = !DISubprogram(name: "vsprintf", scope: !6340, file: !6340, line: 335, type: !6479, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6479 = !DISubroutineType(types: !6480)
!6480 = !{!24, !5683, !5684, !6061}
!6481 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6482, file: !6337, line: 175)
!6482 = !DISubprogram(name: "snprintf", scope: !6340, file: !6340, line: 340, type: !6483, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6483 = !DISubroutineType(types: !6484)
!6484 = !{!24, !5683, !159, !5684, null}
!6485 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6486, file: !6337, line: 176)
!6486 = !DISubprogram(name: "vfscanf", scope: !6340, file: !6340, line: 420, type: !6471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6487 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6488, file: !6337, line: 177)
!6488 = !DISubprogram(name: "vscanf", scope: !6340, file: !6340, line: 428, type: !6475, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6489 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6490, file: !6337, line: 178)
!6490 = !DISubprogram(name: "vsnprintf", scope: !6340, file: !6340, line: 344, type: !6491, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6491 = !DISubroutineType(types: !6492)
!6492 = !{!24, !5683, !159, !5684, !6061}
!6493 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6494, file: !6337, line: 179)
!6494 = !DISubprogram(name: "vsscanf", scope: !6340, file: !6340, line: 432, type: !6495, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6495 = !DISubroutineType(types: !6496)
!6496 = !{!24, !5684, !5684, !6061}
!6497 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6482, file: !6337, line: 185)
!6498 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6486, file: !6337, line: 186)
!6499 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6488, file: !6337, line: 187)
!6500 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6490, file: !6337, line: 188)
!6501 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6494, file: !6337, line: 189)
!6502 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6503, file: !6507, line: 82)
!6503 = !DIDerivedType(tag: DW_TAG_typedef, name: "wctrans_t", file: !6504, line: 48, baseType: !6505)
!6504 = !DIFile(filename: "/usr/include/wctype.h", directory: "", checksumkind: CSK_MD5, checksum: "760693b7fbeea3d686e1f29058fc2257")
!6505 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6506, size: 64)
!6506 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6232)
!6507 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cwctype", directory: "")
!6508 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6509, file: !6507, line: 83)
!6509 = !DIDerivedType(tag: DW_TAG_typedef, name: "wctype_t", file: !6510, line: 38, baseType: !161)
!6510 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/wctype-wchar.h", directory: "", checksumkind: CSK_MD5, checksum: "45eef9c3aa1d99faffa3945ed9be039a")
!6511 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !5935, file: !6507, line: 84)
!6512 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6513, file: !6507, line: 86)
!6513 = !DISubprogram(name: "iswalnum", scope: !6510, file: !6510, line: 95, type: !6163, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6514 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6515, file: !6507, line: 87)
!6515 = !DISubprogram(name: "iswalpha", scope: !6510, file: !6510, line: 101, type: !6163, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6516 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6517, file: !6507, line: 89)
!6517 = !DISubprogram(name: "iswblank", scope: !6510, file: !6510, line: 146, type: !6163, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6518 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6519, file: !6507, line: 91)
!6519 = !DISubprogram(name: "iswcntrl", scope: !6510, file: !6510, line: 104, type: !6163, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6520 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6521, file: !6507, line: 92)
!6521 = !DISubprogram(name: "iswctype", scope: !6510, file: !6510, line: 159, type: !6522, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6522 = !DISubroutineType(types: !6523)
!6523 = !{!24, !5935, !6509}
!6524 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6525, file: !6507, line: 93)
!6525 = !DISubprogram(name: "iswdigit", scope: !6510, file: !6510, line: 108, type: !6163, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6526 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6527, file: !6507, line: 94)
!6527 = !DISubprogram(name: "iswgraph", scope: !6510, file: !6510, line: 112, type: !6163, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6528 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6529, file: !6507, line: 95)
!6529 = !DISubprogram(name: "iswlower", scope: !6510, file: !6510, line: 117, type: !6163, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6530 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6531, file: !6507, line: 96)
!6531 = !DISubprogram(name: "iswprint", scope: !6510, file: !6510, line: 120, type: !6163, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6532 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6533, file: !6507, line: 97)
!6533 = !DISubprogram(name: "iswpunct", scope: !6510, file: !6510, line: 125, type: !6163, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6534 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6535, file: !6507, line: 98)
!6535 = !DISubprogram(name: "iswspace", scope: !6510, file: !6510, line: 130, type: !6163, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6536 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6537, file: !6507, line: 99)
!6537 = !DISubprogram(name: "iswupper", scope: !6510, file: !6510, line: 135, type: !6163, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6538 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6539, file: !6507, line: 100)
!6539 = !DISubprogram(name: "iswxdigit", scope: !6510, file: !6510, line: 140, type: !6163, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6540 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6541, file: !6507, line: 101)
!6541 = !DISubprogram(name: "towctrans", scope: !6504, file: !6504, line: 55, type: !6542, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6542 = !DISubroutineType(types: !6543)
!6543 = !{!5935, !5935, !6503}
!6544 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6545, file: !6507, line: 102)
!6545 = !DISubprogram(name: "towlower", scope: !6510, file: !6510, line: 166, type: !6546, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6546 = !DISubroutineType(types: !6547)
!6547 = !{!5935, !5935}
!6548 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6549, file: !6507, line: 103)
!6549 = !DISubprogram(name: "towupper", scope: !6510, file: !6510, line: 169, type: !6546, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6550 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6551, file: !6507, line: 104)
!6551 = !DISubprogram(name: "wctrans", scope: !6504, file: !6504, line: 52, type: !6552, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6552 = !DISubroutineType(types: !6553)
!6553 = !{!6503, !163}
!6554 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6555, file: !6507, line: 105)
!6555 = !DISubprogram(name: "wctype", scope: !6510, file: !6510, line: 155, type: !6556, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6556 = !DISubroutineType(types: !6557)
!6557 = !{!6509, !163}
!6558 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !3, file: !6559, line: 86)
!6559 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr_base.h", directory: "", checksumkind: CSK_MD5, checksum: "8405222f7806be9ab20595b5fcc527fd")
!6560 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6561, file: !6559, line: 87)
!6561 = !DIGlobalVariable(name: "__default_lock_policy", linkageName: "_ZN9__gnu_cxxL21__default_lock_policyE", scope: !5, file: !4, line: 53, type: !6562, isLocal: true, isDefinition: false)
!6562 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3)
!6563 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6564, file: !6567, line: 60)
!6564 = !DIDerivedType(tag: DW_TAG_typedef, name: "clock_t", file: !6565, line: 7, baseType: !6566)
!6565 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/clock_t.h", directory: "", checksumkind: CSK_MD5, checksum: "1aade99fd778d1551600c7ca1410b9f1")
!6566 = !DIDerivedType(tag: DW_TAG_typedef, name: "__clock_t", file: !420, line: 144, baseType: !405)
!6567 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ctime", directory: "")
!6568 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6569, file: !6567, line: 61)
!6569 = !DIDerivedType(tag: DW_TAG_typedef, name: "time_t", file: !6570, line: 7, baseType: !6571)
!6570 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/time_t.h", directory: "", checksumkind: CSK_MD5, checksum: "49b4e16ef1215de5afdbb283400ab90c")
!6571 = !DIDerivedType(tag: DW_TAG_typedef, name: "__time_t", file: !420, line: 148, baseType: !405)
!6572 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6112, file: !6567, line: 62)
!6573 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6574, file: !6567, line: 64)
!6574 = !DISubprogram(name: "clock", scope: !6575, file: !6575, line: 72, type: !6576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6575 = !DIFile(filename: "/usr/include/time.h", directory: "", checksumkind: CSK_MD5, checksum: "3b21b4c7d8bf3fafdb33a1c7ed8e024a")
!6576 = !DISubroutineType(types: !6577)
!6577 = !{!6564}
!6578 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6579, file: !6567, line: 65)
!6579 = !DISubprogram(name: "difftime", scope: !6575, file: !6575, line: 78, type: !6580, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6580 = !DISubroutineType(types: !6581)
!6581 = !{!4666, !6569, !6569}
!6582 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6583, file: !6567, line: 66)
!6583 = !DISubprogram(name: "mktime", scope: !6575, file: !6575, line: 82, type: !6584, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6584 = !DISubroutineType(types: !6585)
!6585 = !{!6569, !6586}
!6586 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6112, size: 64)
!6587 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6588, file: !6567, line: 67)
!6588 = !DISubprogram(name: "time", scope: !6575, file: !6575, line: 75, type: !6589, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6589 = !DISubroutineType(types: !6590)
!6590 = !{!6569, !6591}
!6591 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6569, size: 64)
!6592 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6593, file: !6567, line: 68)
!6593 = !DISubprogram(name: "asctime", scope: !6575, file: !6575, line: 139, type: !6594, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6594 = !DISubroutineType(types: !6595)
!6595 = !{!613, !6110}
!6596 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6597, file: !6567, line: 69)
!6597 = !DISubprogram(name: "ctime", scope: !6575, file: !6575, line: 142, type: !6598, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6598 = !DISubroutineType(types: !6599)
!6599 = !{!613, !6600}
!6600 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6601, size: 64)
!6601 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6569)
!6602 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6603, file: !6567, line: 70)
!6603 = !DISubprogram(name: "gmtime", scope: !6575, file: !6575, line: 119, type: !6604, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6604 = !DISubroutineType(types: !6605)
!6605 = !{!6586, !6600}
!6606 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6607, file: !6567, line: 71)
!6607 = !DISubprogram(name: "localtime", scope: !6575, file: !6575, line: 123, type: !6604, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6608 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !192, entity: !6609, file: !6567, line: 72)
!6609 = !DISubprogram(name: "strftime", scope: !6575, file: !6575, line: 88, type: !6610, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6610 = !DISubroutineType(types: !6611)
!6611 = !{!159, !5683, !159, !5684, !6109}
!6612 = !DIImportedEntity(tag: DW_TAG_imported_module, scope: !0, entity: !14, file: !4882, line: 19)
!6613 = !DIImportedEntity(tag: DW_TAG_imported_module, scope: !0, entity: !110, file: !4882, line: 20)
!6614 = !{i32 7, !"Dwarf Version", i32 5}
!6615 = !{i32 2, !"Debug Info Version", i32 3}
!6616 = !{i32 1, !"wchar_size", i32 4}
!6617 = !{i32 7, !"PIC Level", i32 2}
!6618 = !{i32 7, !"uwtable", i32 2}
!6619 = !DILocalVariable(name: "this", arg: 1, scope: !6620, type: !6622, flags: DIFlagArtificial | DIFlagObjectPointer)
!6620 = distinct !DISubprogram(name: "operator++", linkageName: "_ZNSt13_Bit_iteratorppEv", scope: !2670, file: !2555, line: 236, type: !2765, scopeLine: 237, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !2764, retainedNodes: !6621)
!6621 = !{!6619}
!6622 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2670, size: 64)
!6623 = !DILocation(line: 0, scope: !6620)
