; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s --passes=simplifycfg,reassociate -o - -S | FileCheck %s
; gnochange issue with the dbg.value after the call -- we used to insert before it, didn't with inhaled blocks
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @_ZNK5clang7CodeGen11VBTableInfo21EmitVBTableDefinitionERNS0_13CodeGenModuleEPKNS_13CXXRecordDeclEN4llvm11GlobalValue12LinkageTypesE(ptr %CGM) {
; CHECK-LABEL: @_ZNK5clang7CodeGen11VBTableInfo21EmitVBTableDefinitionERNS0_13CodeGenModuleEPKNS_13CXXRecordDeclEN4llvm11GlobalValue12LinkageTypesE(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL11:%.*]] = tail call i64 @_ZNK5clang15ASTRecordLayout14getVBPtrOffsetEv()
; CHECK-NEXT:    call void @llvm.dbg.value(metadata i64 [[CALL11]], metadata [[META4458:![0-9]+]], metadata !DIExpression()), !dbg [[DBG4485:![0-9]+]]
; CHECK-NEXT:    [[SUB:%.*]] = sub i64 0, [[CALL11]]
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr null, align 8
; CHECK-NEXT:    [[CALL13:%.*]] = tail call ptr @_ZN4llvm11ConstantInt3getEPNS_11IntegerTypeEmb(ptr [[TMP0]], i64 [[SUB]])
; CHECK-NEXT:    [[SUB_I:%.*]] = add i64 [[SUB]], 1
; CHECK-NEXT:    store i64 [[SUB_I]], ptr [[CGM:%.*]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %call11 = tail call i64 @_ZNK5clang15ASTRecordLayout14getVBPtrOffsetEv()
  call void @llvm.dbg.value(metadata i64 %call11, metadata !4458, metadata !DIExpression()), !dbg !4485
  %0 = load ptr, ptr null, align 8
  %sub = sub nsw i64 0, %call11
  %call13 = tail call ptr @_ZN4llvm11ConstantInt3getEPNS_11IntegerTypeEmb(ptr %0, i64 %sub)
  %add.i = add nsw i64 %call11, 0
  %sub.i = sub nsw i64 1, %add.i
  store i64 %sub.i, ptr %CGM, align 8
  ret void
}

declare i64 @_ZNK5clang15ASTRecordLayout14getVBPtrOffsetEv()

declare ptr @_ZN4llvm11ConstantInt3getEPNS_11IntegerTypeEmb(ptr, i64)

; Function Attrs: nocallback nofree nosync nounwind readnone speculatable willreturn
declare void @llvm.dbg.value(metadata, metadata, metadata) #0

attributes #0 = { nocallback nofree nosync nounwind readnone speculatable willreturn }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!4453, !4454, !4455, !4456, !4457}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !665, globals: !2680, imports: !3136, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "/fast/fs/llvm34/projects/clang/lib/CodeGen/MicrosoftVBTables.cpp", directory: "/fast/fs/build34llvm5", checksumkind: CSK_MD5, checksum: "a6973439eab46b43faf43bbd24913e65")
!2 = !{!3, !11, !16, !35, !46, !51, !255, !261, !267, !274, !505, !510, !513, !531, !554, !655, !659}
!3 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "_Lock_policy", scope: !5, file: !4, line: 49, baseType: !6, size: 32, elements: !7, identifier: "_ZTSN9__gnu_cxx12_Lock_policyE")
!4 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/concurrence.h", directory: "")
!5 = !DINamespace(name: "__gnu_cxx", scope: null)
!6 = !DIBasicType(name: "unsigned int", size: 32, encoding: DW_ATE_unsigned)
!7 = !{!8, !9, !10}
!8 = !DIEnumerator(name: "_S_single", value: 0, isUnsigned: true)
!9 = !DIEnumerator(name: "_S_mutex", value: 1, isUnsigned: true)
!10 = !DIEnumerator(name: "_S_atomic", value: 2, isUnsigned: true)
!11 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "NoneType", scope: !13, file: !12, line: 22, baseType: !6, size: 32, elements: !14, identifier: "_ZTSN4llvm8NoneTypeE")
!12 = !DIFile(filename: "llvm34/include/llvm/ADT/None.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "a0342314f03a5b3ad15259d9915a8f1b")
!13 = !DINamespace(name: "llvm", scope: null)
!14 = !{!15}
!15 = !DIEnumerator(name: "None", value: 0, isUnsigned: true)
!16 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "LinkageTypes", scope: !18, file: !17, line: 33, baseType: !6, size: 32, elements: !19, identifier: "_ZTSN4llvm11GlobalValue12LinkageTypesE")
!17 = !DIFile(filename: "llvm34/include/llvm/IR/GlobalValue.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "f4611cde2721012c3cd54bde1f5421d8")
!18 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "GlobalValue", scope: !13, file: !17, line: 29, size: 768, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm11GlobalValueE")
!19 = !{!20, !21, !22, !23, !24, !25, !26, !27, !28, !29, !30, !31, !32, !33, !34}
!20 = !DIEnumerator(name: "ExternalLinkage", value: 0, isUnsigned: true)
!21 = !DIEnumerator(name: "AvailableExternallyLinkage", value: 1, isUnsigned: true)
!22 = !DIEnumerator(name: "LinkOnceAnyLinkage", value: 2, isUnsigned: true)
!23 = !DIEnumerator(name: "LinkOnceODRLinkage", value: 3, isUnsigned: true)
!24 = !DIEnumerator(name: "WeakAnyLinkage", value: 4, isUnsigned: true)
!25 = !DIEnumerator(name: "WeakODRLinkage", value: 5, isUnsigned: true)
!26 = !DIEnumerator(name: "AppendingLinkage", value: 6, isUnsigned: true)
!27 = !DIEnumerator(name: "InternalLinkage", value: 7, isUnsigned: true)
!28 = !DIEnumerator(name: "PrivateLinkage", value: 8, isUnsigned: true)
!29 = !DIEnumerator(name: "LinkerPrivateLinkage", value: 9, isUnsigned: true)
!30 = !DIEnumerator(name: "LinkerPrivateWeakLinkage", value: 10, isUnsigned: true)
!31 = !DIEnumerator(name: "DLLImportLinkage", value: 11, isUnsigned: true)
!32 = !DIEnumerator(name: "DLLExportLinkage", value: 12, isUnsigned: true)
!33 = !DIEnumerator(name: "ExternalWeakLinkage", value: 13, isUnsigned: true)
!34 = !DIEnumerator(name: "CommonLinkage", value: 14, isUnsigned: true)
!35 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "TypeVisibilityKind", scope: !37, file: !36, line: 582, baseType: !6, size: 32, elements: !40, identifier: "_ZTSN5clang7CodeGen13CodeGenModule18TypeVisibilityKindE")
!36 = !DIFile(filename: "llvm34/projects/clang/lib/CodeGen/CodeGenModule.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "d5efe0039a053d4f13cad96bcb610311")
!37 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "CodeGenModule", scope: !38, file: !36, line: 226, size: 19072, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang7CodeGen13CodeGenModuleE")
!38 = !DINamespace(name: "CodeGen", scope: !39)
!39 = !DINamespace(name: "clang", scope: null)
!40 = !{!41, !42, !43, !44, !45}
!41 = !DIEnumerator(name: "TVK_ForVTT", value: 0, isUnsigned: true)
!42 = !DIEnumerator(name: "TVK_ForVTable", value: 1, isUnsigned: true)
!43 = !DIEnumerator(name: "TVK_ForConstructionVTable", value: 2, isUnsigned: true)
!44 = !DIEnumerator(name: "TVK_ForRTTI", value: 3, isUnsigned: true)
!45 = !DIEnumerator(name: "TVK_ForRTTIName", value: 4, isUnsigned: true)
!46 = !DICompositeType(tag: DW_TAG_enumeration_type, scope: !39, file: !47, line: 37, baseType: !6, size: 32, elements: !48)
!47 = !DIFile(filename: "llvm34/projects/clang/include/clang/AST/Type.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "8874f64b7354e7fe5e6133b6553c1ea8")
!48 = !{!49, !50}
!49 = !DIEnumerator(name: "TypeAlignmentInBits", value: 4, isUnsigned: true)
!50 = !DIEnumerator(name: "TypeAlignment", value: 16, isUnsigned: true)
!51 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !53, file: !52, line: 44, baseType: !248, size: 64, elements: !250, identifier: "_ZTSN4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEEUt_E")
!52 = !DIFile(filename: "llvm34/include/llvm/ADT/PointerIntPair.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "d23f9b419341ab3c3120cccf3bee7cc2")
!53 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerIntPair<llvm::PointerUnion<const clang::Type *, const clang::ExtQuals *>, 3U, unsigned int, llvm::PointerLikeTypeTraits<llvm::PointerUnion<const clang::Type *, const clang::ExtQuals *> > >", scope: !13, file: !52, line: 42, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !54, templateParams: !235, identifier: "_ZTSN4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEEE")
!54 = !{!55, !59, !63, !189, !192, !197, !200, !201, !204, !205, !206, !210, !214, !217, !220, !223, !226, !230, !231, !232, !233, !234}
!55 = !DIDerivedType(tag: DW_TAG_member, name: "Value", scope: !53, file: !52, line: 43, baseType: !56, size: 64)
!56 = !DIDerivedType(tag: DW_TAG_typedef, name: "intptr_t", file: !57, line: 97, baseType: !58)
!57 = !DIFile(filename: "/usr/include/stdint.h", directory: "", checksumkind: CSK_MD5, checksum: "c7469e3b87cb3d1a363efabd19f04208")
!58 = !DIBasicType(name: "long", size: 64, encoding: DW_ATE_signed)
!59 = !DISubprogram(name: "PointerIntPair", scope: !53, file: !52, line: 60, type: !60, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!60 = !DISubroutineType(types: !61)
!61 = !{null, !62}
!62 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !53, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!63 = !DISubprogram(name: "PointerIntPair", scope: !53, file: !52, line: 61, type: !64, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!64 = !DISubroutineType(types: !65)
!65 = !{null, !62, !66, !6}
!66 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerUnion<const clang::Type *, const clang::ExtQuals *>", scope: !13, file: !67, line: 80, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !68, templateParams: !139, identifier: "_ZTSN4llvm12PointerUnionIPKN5clang4TypeEPKNS1_8ExtQualsEEE")
!67 = !DIFile(filename: "llvm34/include/llvm/ADT/PointerUnion.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "fc2fa3fd44f400d393cc7a45e1be774f")
!68 = !{!69, !148, !152, !155, !158, !163, !164, !169, !173, !178, !183, !186}
!69 = !DIDerivedType(tag: DW_TAG_member, name: "Val", scope: !66, file: !67, line: 85, baseType: !70, size: 64)
!70 = !DIDerivedType(tag: DW_TAG_typedef, name: "ValTy", scope: !66, file: !67, line: 83, baseType: !71)
!71 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerIntPair<void *, 1U, bool, llvm::PointerUnionUIntTraits<const clang::Type *, const clang::ExtQuals *> >", scope: !13, file: !52, line: 42, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !72, templateParams: !128, identifier: "_ZTSN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEEE")
!72 = !{!73, !74, !78, !83, !86, !91, !94, !95, !98, !99, !100, !105, !109, !110, !111, !114, !119, !123, !124, !125, !126, !127}
!73 = !DIDerivedType(tag: DW_TAG_member, name: "Value", scope: !71, file: !52, line: 43, baseType: !56, size: 64)
!74 = !DISubprogram(name: "PointerIntPair", scope: !71, file: !52, line: 60, type: !75, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!75 = !DISubroutineType(types: !76)
!76 = !{null, !77}
!77 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !71, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!78 = !DISubprogram(name: "PointerIntPair", scope: !71, file: !52, line: 61, type: !79, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!79 = !DISubroutineType(types: !80)
!80 = !{null, !77, !81, !82}
!81 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 64)
!82 = !DIBasicType(name: "bool", size: 8, encoding: DW_ATE_boolean)
!83 = !DISubprogram(name: "PointerIntPair", scope: !71, file: !52, line: 66, type: !84, scopeLine: 66, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!84 = !DISubroutineType(types: !85)
!85 = !{null, !77, !81}
!86 = !DISubprogram(name: "getPointer", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEE10getPointerEv", scope: !71, file: !52, line: 70, type: !87, scopeLine: 70, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!87 = !DISubroutineType(types: !88)
!88 = !{!81, !89}
!89 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !90, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!90 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !71)
!91 = !DISubprogram(name: "getInt", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEE6getIntEv", scope: !71, file: !52, line: 75, type: !92, scopeLine: 75, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!92 = !DISubroutineType(types: !93)
!93 = !{!82, !89}
!94 = !DISubprogram(name: "setPointer", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEE10setPointerES1_", scope: !71, file: !52, line: 79, type: !84, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!95 = !DISubprogram(name: "setInt", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEE6setIntEb", scope: !71, file: !52, line: 88, type: !96, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!96 = !DISubroutineType(types: !97)
!97 = !{null, !77, !82}
!98 = !DISubprogram(name: "initWithPointer", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEE15initWithPointerES1_", scope: !71, file: !52, line: 97, type: !84, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!99 = !DISubprogram(name: "setPointerAndInt", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEE16setPointerAndIntES1_b", scope: !71, file: !52, line: 105, type: !79, scopeLine: 105, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!100 = !DISubprogram(name: "getAddrOfPointer", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEE16getAddrOfPointerEv", scope: !71, file: !52, line: 116, type: !101, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!101 = !DISubroutineType(types: !102)
!102 = !{!103, !89}
!103 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !104, size: 64)
!104 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !81)
!105 = !DISubprogram(name: "getAddrOfPointer", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEE16getAddrOfPointerEv", scope: !71, file: !52, line: 120, type: !106, scopeLine: 120, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!106 = !DISubroutineType(types: !107)
!107 = !{!108, !77}
!108 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !81, size: 64)
!109 = !DISubprogram(name: "getOpaqueValue", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEE14getOpaqueValueEv", scope: !71, file: !52, line: 127, type: !87, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!110 = !DISubprogram(name: "setFromOpaqueValue", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEE18setFromOpaqueValueES1_", scope: !71, file: !52, line: 128, type: !84, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!111 = !DISubprogram(name: "getFromOpaqueValue", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEE18getFromOpaqueValueES1_", scope: !71, file: !52, line: 130, type: !112, scopeLine: 130, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!112 = !DISubroutineType(types: !113)
!113 = !{!71, !81}
!114 = !DISubprogram(name: "getFromOpaqueValue", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEE18getFromOpaqueValueEPKv", scope: !71, file: !52, line: 136, type: !115, scopeLine: 136, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!115 = !DISubroutineType(types: !116)
!116 = !{!71, !117}
!117 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !118, size: 64)
!118 = !DIDerivedType(tag: DW_TAG_const_type, baseType: null)
!119 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEEeqERKSB_", scope: !71, file: !52, line: 141, type: !120, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!120 = !DISubroutineType(types: !121)
!121 = !{!82, !89, !122}
!122 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !90, size: 64)
!123 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEEneERKSB_", scope: !71, file: !52, line: 142, type: !120, scopeLine: 142, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!124 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEEltERKSB_", scope: !71, file: !52, line: 143, type: !120, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!125 = !DISubprogram(name: "operator>", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEEgtERKSB_", scope: !71, file: !52, line: 144, type: !120, scopeLine: 144, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!126 = !DISubprogram(name: "operator<=", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEEleERKSB_", scope: !71, file: !52, line: 145, type: !120, scopeLine: 145, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!127 = !DISubprogram(name: "operator>=", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEEgeERKSB_", scope: !71, file: !52, line: 146, type: !120, scopeLine: 146, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!128 = !{!129, !130, !131, !132}
!129 = !DITemplateTypeParameter(name: "PointerTy", type: !81)
!130 = !DITemplateValueParameter(name: "IntBits", type: !6, value: i32 1)
!131 = !DITemplateTypeParameter(name: "IntType", type: !82)
!132 = !DITemplateTypeParameter(name: "PtrTraits", type: !133)
!133 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerUnionUIntTraits<const clang::Type *, const clang::ExtQuals *>", scope: !13, file: !67, line: 53, size: 8, flags: DIFlagTypePassByValue, elements: !134, templateParams: !139, identifier: "_ZTSN4llvm22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS1_8ExtQualsEEE")
!134 = !{!135, !138}
!135 = !DISubprogram(name: "getAsVoidPointer", linkageName: "_ZN4llvm22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS1_8ExtQualsEE16getAsVoidPointerEPv", scope: !133, file: !67, line: 55, type: !136, scopeLine: 55, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!136 = !DISubroutineType(types: !137)
!137 = !{!81, !81}
!138 = !DISubprogram(name: "getFromVoidPointer", linkageName: "_ZN4llvm22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS1_8ExtQualsEE18getFromVoidPointerEPv", scope: !133, file: !67, line: 56, type: !136, scopeLine: 56, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!139 = !{!140, !144}
!140 = !DITemplateTypeParameter(name: "PT1", type: !141)
!141 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !142, size: 64)
!142 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !143)
!143 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Type", scope: !39, file: !47, line: 1156, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang4TypeE")
!144 = !DITemplateTypeParameter(name: "PT2", type: !145)
!145 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !146, size: 64)
!146 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !147)
!147 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ExtQuals", scope: !39, file: !47, line: 1059, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang8ExtQualsE")
!148 = !DISubprogram(name: "PointerUnion", scope: !66, file: !67, line: 97, type: !149, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!149 = !DISubroutineType(types: !150)
!150 = !{null, !151}
!151 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !66, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!152 = !DISubprogram(name: "PointerUnion", scope: !66, file: !67, line: 99, type: !153, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!153 = !DISubroutineType(types: !154)
!154 = !{null, !151, !141}
!155 = !DISubprogram(name: "PointerUnion", scope: !66, file: !67, line: 102, type: !156, scopeLine: 102, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!156 = !DISubroutineType(types: !157)
!157 = !{null, !151, !145}
!158 = !DISubprogram(name: "isNull", linkageName: "_ZNK4llvm12PointerUnionIPKN5clang4TypeEPKNS1_8ExtQualsEE6isNullEv", scope: !66, file: !67, line: 108, type: !159, scopeLine: 108, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!159 = !DISubroutineType(types: !160)
!160 = !{!82, !161}
!161 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !162, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!162 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !66)
!163 = !DISubprogram(name: "operator bool", linkageName: "_ZNK4llvm12PointerUnionIPKN5clang4TypeEPKNS1_8ExtQualsEEcvbEv", scope: !66, file: !67, line: 113, type: !159, scopeLine: 113, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!164 = !DISubprogram(name: "getAddrOfPtr1", linkageName: "_ZNK4llvm12PointerUnionIPKN5clang4TypeEPKNS1_8ExtQualsEE13getAddrOfPtr1Ev", scope: !66, file: !67, line: 144, type: !165, scopeLine: 144, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!165 = !DISubroutineType(types: !166)
!166 = !{!167, !161}
!167 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !168, size: 64)
!168 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !141)
!169 = !DISubprogram(name: "getAddrOfPtr1", linkageName: "_ZN4llvm12PointerUnionIPKN5clang4TypeEPKNS1_8ExtQualsEE13getAddrOfPtr1Ev", scope: !66, file: !67, line: 150, type: !170, scopeLine: 150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!170 = !DISubroutineType(types: !171)
!171 = !{!172, !151}
!172 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !141, size: 64)
!173 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm12PointerUnionIPKN5clang4TypeEPKNS1_8ExtQualsEEaSERKS4_", scope: !66, file: !67, line: 159, type: !174, scopeLine: 159, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!174 = !DISubroutineType(types: !175)
!175 = !{!176, !151, !177}
!176 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !162, size: 64)
!177 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !168, size: 64)
!178 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm12PointerUnionIPKN5clang4TypeEPKNS1_8ExtQualsEEaSERKS7_", scope: !66, file: !67, line: 164, type: !179, scopeLine: 164, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!179 = !DISubroutineType(types: !180)
!180 = !{!176, !151, !181}
!181 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !182, size: 64)
!182 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !145)
!183 = !DISubprogram(name: "getOpaqueValue", linkageName: "_ZNK4llvm12PointerUnionIPKN5clang4TypeEPKNS1_8ExtQualsEE14getOpaqueValueEv", scope: !66, file: !67, line: 171, type: !184, scopeLine: 171, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!184 = !DISubroutineType(types: !185)
!185 = !{!81, !161}
!186 = !DISubprogram(name: "getFromOpaqueValue", linkageName: "_ZN4llvm12PointerUnionIPKN5clang4TypeEPKNS1_8ExtQualsEE18getFromOpaqueValueEPv", scope: !66, file: !67, line: 172, type: !187, scopeLine: 172, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!187 = !DISubroutineType(types: !188)
!188 = !{!66, !81}
!189 = !DISubprogram(name: "PointerIntPair", scope: !53, file: !52, line: 66, type: !190, scopeLine: 66, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!190 = !DISubroutineType(types: !191)
!191 = !{null, !62, !66}
!192 = !DISubprogram(name: "getPointer", linkageName: "_ZNK4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEE10getPointerEv", scope: !53, file: !52, line: 70, type: !193, scopeLine: 70, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!193 = !DISubroutineType(types: !194)
!194 = !{!66, !195}
!195 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !196, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!196 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !53)
!197 = !DISubprogram(name: "getInt", linkageName: "_ZNK4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEE6getIntEv", scope: !53, file: !52, line: 75, type: !198, scopeLine: 75, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!198 = !DISubroutineType(types: !199)
!199 = !{!6, !195}
!200 = !DISubprogram(name: "setPointer", linkageName: "_ZN4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEE10setPointerES9_", scope: !53, file: !52, line: 79, type: !190, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!201 = !DISubprogram(name: "setInt", linkageName: "_ZN4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEE6setIntEj", scope: !53, file: !52, line: 88, type: !202, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!202 = !DISubroutineType(types: !203)
!203 = !{null, !62, !6}
!204 = !DISubprogram(name: "initWithPointer", linkageName: "_ZN4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEE15initWithPointerES9_", scope: !53, file: !52, line: 97, type: !190, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!205 = !DISubprogram(name: "setPointerAndInt", linkageName: "_ZN4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEE16setPointerAndIntES9_j", scope: !53, file: !52, line: 105, type: !64, scopeLine: 105, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!206 = !DISubprogram(name: "getAddrOfPointer", linkageName: "_ZNK4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEE16getAddrOfPointerEv", scope: !53, file: !52, line: 116, type: !207, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!207 = !DISubroutineType(types: !208)
!208 = !{!209, !195}
!209 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !162, size: 64)
!210 = !DISubprogram(name: "getAddrOfPointer", linkageName: "_ZN4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEE16getAddrOfPointerEv", scope: !53, file: !52, line: 120, type: !211, scopeLine: 120, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!211 = !DISubroutineType(types: !212)
!212 = !{!213, !62}
!213 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !66, size: 64)
!214 = !DISubprogram(name: "getOpaqueValue", linkageName: "_ZNK4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEE14getOpaqueValueEv", scope: !53, file: !52, line: 127, type: !215, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!215 = !DISubroutineType(types: !216)
!216 = !{!81, !195}
!217 = !DISubprogram(name: "setFromOpaqueValue", linkageName: "_ZN4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEE18setFromOpaqueValueEPv", scope: !53, file: !52, line: 128, type: !218, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!218 = !DISubroutineType(types: !219)
!219 = !{null, !62, !81}
!220 = !DISubprogram(name: "getFromOpaqueValue", linkageName: "_ZN4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEE18getFromOpaqueValueEPv", scope: !53, file: !52, line: 130, type: !221, scopeLine: 130, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!221 = !DISubroutineType(types: !222)
!222 = !{!53, !81}
!223 = !DISubprogram(name: "getFromOpaqueValue", linkageName: "_ZN4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEE18getFromOpaqueValueEPKv", scope: !53, file: !52, line: 136, type: !224, scopeLine: 136, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!224 = !DISubroutineType(types: !225)
!225 = !{!53, !117}
!226 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEEeqERKSC_", scope: !53, file: !52, line: 141, type: !227, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!227 = !DISubroutineType(types: !228)
!228 = !{!82, !195, !229}
!229 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !196, size: 64)
!230 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEEneERKSC_", scope: !53, file: !52, line: 142, type: !227, scopeLine: 142, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!231 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEEltERKSC_", scope: !53, file: !52, line: 143, type: !227, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!232 = !DISubprogram(name: "operator>", linkageName: "_ZNK4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEEgtERKSC_", scope: !53, file: !52, line: 144, type: !227, scopeLine: 144, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!233 = !DISubprogram(name: "operator<=", linkageName: "_ZNK4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEEleERKSC_", scope: !53, file: !52, line: 145, type: !227, scopeLine: 145, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!234 = !DISubprogram(name: "operator>=", linkageName: "_ZNK4llvm14PointerIntPairINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEELj3EjNS_21PointerLikeTypeTraitsIS9_EEEgeERKSC_", scope: !53, file: !52, line: 146, type: !227, scopeLine: 146, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!235 = !{!236, !237, !238, !239}
!236 = !DITemplateTypeParameter(name: "PointerTy", type: !66)
!237 = !DITemplateValueParameter(name: "IntBits", type: !6, value: i32 3)
!238 = !DITemplateTypeParameter(name: "IntType", type: !6, defaulted: true)
!239 = !DITemplateTypeParameter(name: "PtrTraits", type: !240)
!240 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerLikeTypeTraits<llvm::PointerUnion<const clang::Type *, const clang::ExtQuals *> >", scope: !13, file: !67, line: 194, size: 8, flags: DIFlagTypePassByValue, elements: !241, templateParams: !246, identifier: "_ZTSN4llvm21PointerLikeTypeTraitsINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEEEE")
!241 = !{!242, !245}
!242 = !DISubprogram(name: "getAsVoidPointer", linkageName: "_ZN4llvm21PointerLikeTypeTraitsINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEEE16getAsVoidPointerERKS9_", scope: !240, file: !67, line: 197, type: !243, scopeLine: 197, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!243 = !DISubroutineType(types: !244)
!244 = !{!81, !176}
!245 = !DISubprogram(name: "getFromVoidPointer", linkageName: "_ZN4llvm21PointerLikeTypeTraitsINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEEE18getFromVoidPointerEPv", scope: !240, file: !67, line: 201, type: !187, scopeLine: 201, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!246 = !{!247}
!247 = !DITemplateTypeParameter(name: "T", type: !66)
!248 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintptr_t", file: !57, line: 100, baseType: !249)
!249 = !DIBasicType(name: "unsigned long", size: 64, encoding: DW_ATE_unsigned)
!250 = !{!251, !252, !253, !254}
!251 = !DIEnumerator(name: "PointerBitMask", value: 18446744073709551608, isUnsigned: true)
!252 = !DIEnumerator(name: "IntShift", value: 0, isUnsigned: true)
!253 = !DIEnumerator(name: "IntMask", value: 7, isUnsigned: true)
!254 = !DIEnumerator(name: "ShiftedIntMask", value: 7, isUnsigned: true)
!255 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !71, file: !52, line: 44, baseType: !248, size: 64, elements: !256, identifier: "_ZTSN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS3_8ExtQualsEEEEUt_E")
!256 = !{!257, !258, !259, !260}
!257 = !DIEnumerator(name: "PointerBitMask", value: 18446744073709551600, isUnsigned: true)
!258 = !DIEnumerator(name: "IntShift", value: 3, isUnsigned: true)
!259 = !DIEnumerator(name: "IntMask", value: 1, isUnsigned: true)
!260 = !DIEnumerator(name: "ShiftedIntMask", value: 8, isUnsigned: true)
!261 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "GC", scope: !262, file: !47, line: 122, baseType: !6, size: 32, elements: !263, identifier: "_ZTSN5clang10Qualifiers2GCE")
!262 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Qualifiers", scope: !39, file: !47, line: 113, size: 32, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang10QualifiersE")
!263 = !{!264, !265, !266}
!264 = !DIEnumerator(name: "GCNone", value: 0, isUnsigned: true)
!265 = !DIEnumerator(name: "Weak", value: 1, isUnsigned: true)
!266 = !DIEnumerator(name: "Strong", value: 2, isUnsigned: true)
!267 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "ObjCLifetime", scope: !262, file: !47, line: 128, baseType: !6, size: 32, elements: !268, identifier: "_ZTSN5clang10Qualifiers12ObjCLifetimeE")
!268 = !{!269, !270, !271, !272, !273}
!269 = !DIEnumerator(name: "OCL_None", value: 0, isUnsigned: true)
!270 = !DIEnumerator(name: "OCL_ExplicitNone", value: 1, isUnsigned: true)
!271 = !DIEnumerator(name: "OCL_Strong", value: 2, isUnsigned: true)
!272 = !DIEnumerator(name: "OCL_Weak", value: 3, isUnsigned: true)
!273 = !DIEnumerator(name: "OCL_Autoreleasing", value: 4, isUnsigned: true)
!274 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "DestructionKind", scope: !275, file: !47, line: 955, baseType: !6, size: 32, elements: !500, identifier: "_ZTSN5clang8QualType15DestructionKindE")
!275 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "QualType", scope: !39, file: !47, line: 533, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !276, identifier: "_ZTSN5clang8QualTypeE")
!276 = !{!277, !278, !283, !286, !292, !296, !299, !302, !305, !308, !309, !310, !317, !321, !324, !327, !331, !332, !335, !336, !337, !338, !339, !340, !341, !342, !343, !344, !345, !346, !349, !350, !351, !352, !358, !359, !360, !361, !362, !363, !364, !367, !368, !369, !370, !371, !374, !375, !376, !377, !378, !379, !380, !381, !382, !383, !384, !385, !386, !387, !388, !391, !392, !393, !398, !399, !400, !401, !402, !411, !414, !417, !424, !433, !436, !439, !443, !446, !449, !453, !459, !462, !468, !469, !472, !473, !474, !477, !478, !479, !482, !483, !486, !489, !492, !493, !494, !497}
!277 = !DIDerivedType(tag: DW_TAG_member, name: "Value", scope: !275, file: !47, line: 536, baseType: !53, size: 64)
!278 = !DISubprogram(name: "getExtQualsUnsafe", linkageName: "_ZNK5clang8QualType17getExtQualsUnsafeEv", scope: !275, file: !47, line: 538, type: !279, scopeLine: 538, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!279 = !DISubroutineType(types: !280)
!280 = !{!145, !281}
!281 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !282, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!282 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !275)
!283 = !DISubprogram(name: "getTypePtrUnsafe", linkageName: "_ZNK5clang8QualType16getTypePtrUnsafeEv", scope: !275, file: !47, line: 542, type: !284, scopeLine: 542, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!284 = !DISubroutineType(types: !285)
!285 = !{!141, !281}
!286 = !DISubprogram(name: "getCommonPtr", linkageName: "_ZNK5clang8QualType12getCommonPtrEv", scope: !275, file: !47, line: 546, type: !287, scopeLine: 546, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!287 = !DISubroutineType(types: !288)
!288 = !{!289, !281}
!289 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !290, size: 64)
!290 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !291)
!291 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ExtQualsTypeCommonBase", scope: !39, file: !47, line: 1030, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang22ExtQualsTypeCommonBaseE")
!292 = !DISubprogram(name: "QualType", scope: !275, file: !47, line: 556, type: !293, scopeLine: 556, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!293 = !DISubroutineType(types: !294)
!294 = !{null, !295}
!295 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !275, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!296 = !DISubprogram(name: "QualType", scope: !275, file: !47, line: 558, type: !297, scopeLine: 558, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!297 = !DISubroutineType(types: !298)
!298 = !{null, !295, !141, !6}
!299 = !DISubprogram(name: "QualType", scope: !275, file: !47, line: 560, type: !300, scopeLine: 560, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!300 = !DISubroutineType(types: !301)
!301 = !{null, !295, !145, !6}
!302 = !DISubprogram(name: "getLocalFastQualifiers", linkageName: "_ZNK5clang8QualType22getLocalFastQualifiersEv", scope: !275, file: !47, line: 563, type: !303, scopeLine: 563, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!303 = !DISubroutineType(types: !304)
!304 = !{!6, !281}
!305 = !DISubprogram(name: "setLocalFastQualifiers", linkageName: "_ZN5clang8QualType22setLocalFastQualifiersEj", scope: !275, file: !47, line: 564, type: !306, scopeLine: 564, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!306 = !DISubroutineType(types: !307)
!307 = !{null, !295, !6}
!308 = !DISubprogram(name: "getTypePtr", linkageName: "_ZNK5clang8QualType10getTypePtrEv", scope: !275, file: !47, line: 570, type: !284, scopeLine: 570, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!309 = !DISubprogram(name: "getTypePtrOrNull", linkageName: "_ZNK5clang8QualType16getTypePtrOrNullEv", scope: !275, file: !47, line: 572, type: !284, scopeLine: 572, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!310 = !DISubprogram(name: "getBaseTypeIdentifier", linkageName: "_ZNK5clang8QualType21getBaseTypeIdentifierEv", scope: !275, file: !47, line: 575, type: !311, scopeLine: 575, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!311 = !DISubroutineType(types: !312)
!312 = !{!313, !281}
!313 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !314, size: 64)
!314 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !315)
!315 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "IdentifierInfo", scope: !39, file: !316, line: 50, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang14IdentifierInfoE")
!316 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/IdentifierTable.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "4680d46f8abc74960d0f86dc6eb6b801")
!317 = !DISubprogram(name: "split", linkageName: "_ZNK5clang8QualType5splitEv", scope: !275, file: !47, line: 579, type: !318, scopeLine: 579, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!318 = !DISubroutineType(types: !319)
!319 = !{!320, !281}
!320 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SplitQualType", scope: !39, file: !47, line: 496, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang13SplitQualTypeE")
!321 = !DISubprogram(name: "getAsOpaquePtr", linkageName: "_ZNK5clang8QualType14getAsOpaquePtrEv", scope: !275, file: !47, line: 581, type: !322, scopeLine: 581, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!322 = !DISubroutineType(types: !323)
!323 = !{!81, !281}
!324 = !DISubprogram(name: "getFromOpaquePtr", linkageName: "_ZN5clang8QualType16getFromOpaquePtrEPKv", scope: !275, file: !47, line: 582, type: !325, scopeLine: 582, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!325 = !DISubroutineType(types: !326)
!326 = !{!275, !117}
!327 = !DISubprogram(name: "operator*", linkageName: "_ZNK5clang8QualTypedeEv", scope: !275, file: !47, line: 588, type: !328, scopeLine: 588, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!328 = !DISubroutineType(types: !329)
!329 = !{!330, !281}
!330 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !142, size: 64)
!331 = !DISubprogram(name: "operator->", linkageName: "_ZNK5clang8QualTypeptEv", scope: !275, file: !47, line: 592, type: !284, scopeLine: 592, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!332 = !DISubprogram(name: "isCanonical", linkageName: "_ZNK5clang8QualType11isCanonicalEv", scope: !275, file: !47, line: 596, type: !333, scopeLine: 596, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!333 = !DISubroutineType(types: !334)
!334 = !{!82, !281}
!335 = !DISubprogram(name: "isCanonicalAsParam", linkageName: "_ZNK5clang8QualType18isCanonicalAsParamEv", scope: !275, file: !47, line: 597, type: !333, scopeLine: 597, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!336 = !DISubprogram(name: "isNull", linkageName: "_ZNK5clang8QualType6isNullEv", scope: !275, file: !47, line: 600, type: !333, scopeLine: 600, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!337 = !DISubprogram(name: "isLocalConstQualified", linkageName: "_ZNK5clang8QualType21isLocalConstQualifiedEv", scope: !275, file: !47, line: 607, type: !333, scopeLine: 607, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!338 = !DISubprogram(name: "isConstQualified", linkageName: "_ZNK5clang8QualType16isConstQualifiedEv", scope: !275, file: !47, line: 612, type: !333, scopeLine: 612, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!339 = !DISubprogram(name: "isLocalRestrictQualified", linkageName: "_ZNK5clang8QualType24isLocalRestrictQualifiedEv", scope: !275, file: !47, line: 617, type: !333, scopeLine: 617, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!340 = !DISubprogram(name: "isRestrictQualified", linkageName: "_ZNK5clang8QualType19isRestrictQualifiedEv", scope: !275, file: !47, line: 622, type: !333, scopeLine: 622, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!341 = !DISubprogram(name: "isLocalVolatileQualified", linkageName: "_ZNK5clang8QualType24isLocalVolatileQualifiedEv", scope: !275, file: !47, line: 627, type: !333, scopeLine: 627, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!342 = !DISubprogram(name: "isVolatileQualified", linkageName: "_ZNK5clang8QualType19isVolatileQualifiedEv", scope: !275, file: !47, line: 632, type: !333, scopeLine: 632, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!343 = !DISubprogram(name: "hasLocalQualifiers", linkageName: "_ZNK5clang8QualType18hasLocalQualifiersEv", scope: !275, file: !47, line: 637, type: !333, scopeLine: 637, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!344 = !DISubprogram(name: "hasQualifiers", linkageName: "_ZNK5clang8QualType13hasQualifiersEv", scope: !275, file: !47, line: 642, type: !333, scopeLine: 642, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!345 = !DISubprogram(name: "hasLocalNonFastQualifiers", linkageName: "_ZNK5clang8QualType25hasLocalNonFastQualifiersEv", scope: !275, file: !47, line: 647, type: !333, scopeLine: 647, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!346 = !DISubprogram(name: "getLocalQualifiers", linkageName: "_ZNK5clang8QualType18getLocalQualifiersEv", scope: !275, file: !47, line: 654, type: !347, scopeLine: 654, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!347 = !DISubroutineType(types: !348)
!348 = !{!262, !281}
!349 = !DISubprogram(name: "getQualifiers", linkageName: "_ZNK5clang8QualType13getQualifiersEv", scope: !275, file: !47, line: 657, type: !347, scopeLine: 657, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!350 = !DISubprogram(name: "getLocalCVRQualifiers", linkageName: "_ZNK5clang8QualType21getLocalCVRQualifiersEv", scope: !275, file: !47, line: 662, type: !303, scopeLine: 662, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!351 = !DISubprogram(name: "getCVRQualifiers", linkageName: "_ZNK5clang8QualType16getCVRQualifiersEv", scope: !275, file: !47, line: 668, type: !303, scopeLine: 668, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!352 = !DISubprogram(name: "isConstant", linkageName: "_ZNK5clang8QualType10isConstantERNS_10ASTContextE", scope: !275, file: !47, line: 670, type: !353, scopeLine: 670, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!353 = !DISubroutineType(types: !354)
!354 = !{!82, !281, !355}
!355 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !356, size: 64)
!356 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ASTContext", scope: !39, file: !357, line: 78, size: 148544, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang10ASTContextE")
!357 = !DIFile(filename: "llvm34/projects/clang/include/clang/AST/ASTContext.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "7c78439283a83535bf0b115a497f9453")
!358 = !DISubprogram(name: "isPODType", linkageName: "_ZNK5clang8QualType9isPODTypeERNS_10ASTContextE", scope: !275, file: !47, line: 675, type: !353, scopeLine: 675, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!359 = !DISubprogram(name: "isCXX98PODType", linkageName: "_ZNK5clang8QualType14isCXX98PODTypeERNS_10ASTContextE", scope: !275, file: !47, line: 680, type: !353, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!360 = !DISubprogram(name: "isCXX11PODType", linkageName: "_ZNK5clang8QualType14isCXX11PODTypeERNS_10ASTContextE", scope: !275, file: !47, line: 686, type: !353, scopeLine: 686, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!361 = !DISubprogram(name: "isTrivialType", linkageName: "_ZNK5clang8QualType13isTrivialTypeERNS_10ASTContextE", scope: !275, file: !47, line: 690, type: !353, scopeLine: 690, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!362 = !DISubprogram(name: "isTriviallyCopyableType", linkageName: "_ZNK5clang8QualType23isTriviallyCopyableTypeERNS_10ASTContextE", scope: !275, file: !47, line: 694, type: !353, scopeLine: 694, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!363 = !DISubprogram(name: "addConst", linkageName: "_ZN5clang8QualType8addConstEv", scope: !275, file: !47, line: 700, type: !293, scopeLine: 700, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!364 = !DISubprogram(name: "withConst", linkageName: "_ZNK5clang8QualType9withConstEv", scope: !275, file: !47, line: 703, type: !365, scopeLine: 703, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!365 = !DISubroutineType(types: !366)
!366 = !{!275, !281}
!367 = !DISubprogram(name: "addVolatile", linkageName: "_ZN5clang8QualType11addVolatileEv", scope: !275, file: !47, line: 708, type: !293, scopeLine: 708, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!368 = !DISubprogram(name: "withVolatile", linkageName: "_ZNK5clang8QualType12withVolatileEv", scope: !275, file: !47, line: 711, type: !365, scopeLine: 711, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!369 = !DISubprogram(name: "addRestrict", linkageName: "_ZN5clang8QualType11addRestrictEv", scope: !275, file: !47, line: 716, type: !293, scopeLine: 716, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!370 = !DISubprogram(name: "withRestrict", linkageName: "_ZNK5clang8QualType12withRestrictEv", scope: !275, file: !47, line: 719, type: !365, scopeLine: 719, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!371 = !DISubprogram(name: "withCVRQualifiers", linkageName: "_ZNK5clang8QualType17withCVRQualifiersEj", scope: !275, file: !47, line: 723, type: !372, scopeLine: 723, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!372 = !DISubroutineType(types: !373)
!373 = !{!275, !281, !6}
!374 = !DISubprogram(name: "addFastQualifiers", linkageName: "_ZN5clang8QualType17addFastQualifiersEj", scope: !275, file: !47, line: 727, type: !306, scopeLine: 727, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!375 = !DISubprogram(name: "removeLocalConst", linkageName: "_ZN5clang8QualType16removeLocalConstEv", scope: !275, file: !47, line: 733, type: !293, scopeLine: 733, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!376 = !DISubprogram(name: "removeLocalVolatile", linkageName: "_ZN5clang8QualType19removeLocalVolatileEv", scope: !275, file: !47, line: 734, type: !293, scopeLine: 734, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!377 = !DISubprogram(name: "removeLocalRestrict", linkageName: "_ZN5clang8QualType19removeLocalRestrictEv", scope: !275, file: !47, line: 735, type: !293, scopeLine: 735, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!378 = !DISubprogram(name: "removeLocalCVRQualifiers", linkageName: "_ZN5clang8QualType24removeLocalCVRQualifiersEj", scope: !275, file: !47, line: 736, type: !306, scopeLine: 736, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!379 = !DISubprogram(name: "removeLocalFastQualifiers", linkageName: "_ZN5clang8QualType25removeLocalFastQualifiersEv", scope: !275, file: !47, line: 738, type: !293, scopeLine: 738, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!380 = !DISubprogram(name: "removeLocalFastQualifiers", linkageName: "_ZN5clang8QualType25removeLocalFastQualifiersEj", scope: !275, file: !47, line: 739, type: !306, scopeLine: 739, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!381 = !DISubprogram(name: "withFastQualifiers", linkageName: "_ZNK5clang8QualType18withFastQualifiersEj", scope: !275, file: !47, line: 746, type: !372, scopeLine: 746, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!382 = !DISubprogram(name: "withExactLocalFastQualifiers", linkageName: "_ZNK5clang8QualType28withExactLocalFastQualifiersEj", scope: !275, file: !47, line: 754, type: !372, scopeLine: 754, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!383 = !DISubprogram(name: "withoutLocalFastQualifiers", linkageName: "_ZNK5clang8QualType26withoutLocalFastQualifiersEv", scope: !275, file: !47, line: 759, type: !365, scopeLine: 759, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!384 = !DISubprogram(name: "getCanonicalType", linkageName: "_ZNK5clang8QualType16getCanonicalTypeEv", scope: !275, file: !47, line: 765, type: !365, scopeLine: 765, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!385 = !DISubprogram(name: "getLocalUnqualifiedType", linkageName: "_ZNK5clang8QualType23getLocalUnqualifiedTypeEv", scope: !275, file: !47, line: 770, type: !365, scopeLine: 770, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!386 = !DISubprogram(name: "getUnqualifiedType", linkageName: "_ZNK5clang8QualType18getUnqualifiedTypeEv", scope: !275, file: !47, line: 790, type: !365, scopeLine: 790, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!387 = !DISubprogram(name: "getSplitUnqualifiedType", linkageName: "_ZNK5clang8QualType23getSplitUnqualifiedTypeEv", scope: !275, file: !47, line: 801, type: !318, scopeLine: 801, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!388 = !DISubprogram(name: "isMoreQualifiedThan", linkageName: "_ZNK5clang8QualType19isMoreQualifiedThanES0_", scope: !275, file: !47, line: 805, type: !389, scopeLine: 805, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!389 = !DISubroutineType(types: !390)
!390 = !{!82, !281, !275}
!391 = !DISubprogram(name: "isAtLeastAsQualifiedAs", linkageName: "_ZNK5clang8QualType22isAtLeastAsQualifiedAsES0_", scope: !275, file: !47, line: 809, type: !389, scopeLine: 809, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!392 = !DISubprogram(name: "getNonReferenceType", linkageName: "_ZNK5clang8QualType19getNonReferenceTypeEv", scope: !275, file: !47, line: 811, type: !365, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!393 = !DISubprogram(name: "getNonLValueExprType", linkageName: "_ZNK5clang8QualType20getNonLValueExprTypeERKNS_10ASTContextE", scope: !275, file: !47, line: 821, type: !394, scopeLine: 821, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!394 = !DISubroutineType(types: !395)
!395 = !{!275, !281, !396}
!396 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !397, size: 64)
!397 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !356)
!398 = !DISubprogram(name: "getDesugaredType", linkageName: "_ZNK5clang8QualType16getDesugaredTypeERKNS_10ASTContextE", scope: !275, file: !47, line: 831, type: !394, scopeLine: 831, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!399 = !DISubprogram(name: "getSplitDesugaredType", linkageName: "_ZNK5clang8QualType21getSplitDesugaredTypeEv", scope: !275, file: !47, line: 835, type: !318, scopeLine: 835, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!400 = !DISubprogram(name: "getSingleStepDesugaredType", linkageName: "_ZNK5clang8QualType26getSingleStepDesugaredTypeERKNS_10ASTContextE", scope: !275, file: !47, line: 844, type: !394, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!401 = !DISubprogram(name: "IgnoreParens", linkageName: "_ZNK5clang8QualType12IgnoreParensEv", scope: !275, file: !47, line: 850, type: !365, scopeLine: 850, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!402 = !DISubprogram(name: "getAsString", linkageName: "_ZNK5clang8QualType11getAsStringB5cxx11Ev", scope: !275, file: !47, line: 864, type: !403, scopeLine: 864, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!403 = !DISubroutineType(types: !404)
!404 = !{!405, !281}
!405 = !DIDerivedType(tag: DW_TAG_typedef, name: "string", scope: !407, file: !406, line: 74, baseType: !409)
!406 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stringfwd.h", directory: "")
!407 = !DINamespace(name: "__cxx11", scope: !408, exportSymbols: true)
!408 = !DINamespace(name: "std", scope: null)
!409 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "basic_string<char, std::char_traits<char>, std::allocator<char> >", scope: !407, file: !410, line: 1607, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE")
!410 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.tcc", directory: "")
!411 = !DISubprogram(name: "getAsString", linkageName: "_ZN5clang8QualType11getAsStringB5cxx11ENS_13SplitQualTypeE", scope: !275, file: !47, line: 867, type: !412, scopeLine: 867, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!412 = !DISubroutineType(types: !413)
!413 = !{!405, !320}
!414 = !DISubprogram(name: "getAsString", linkageName: "_ZN5clang8QualType11getAsStringB5cxx11EPKNS_4TypeENS_10QualifiersE", scope: !275, file: !47, line: 870, type: !415, scopeLine: 870, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!415 = !DISubroutineType(types: !416)
!416 = !{!405, !141, !262}
!417 = !DISubprogram(name: "getAsString", linkageName: "_ZNK5clang8QualType11getAsStringB5cxx11ERKNS_14PrintingPolicyE", scope: !275, file: !47, line: 872, type: !418, scopeLine: 872, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!418 = !DISubroutineType(types: !419)
!419 = !{!405, !281, !420}
!420 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !421, size: 64)
!421 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !422)
!422 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "PrintingPolicy", scope: !39, file: !423, line: 35, size: 1792, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang14PrintingPolicyE")
!423 = !DIFile(filename: "llvm34/projects/clang/include/clang/AST/PrettyPrinter.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "f288dfde20ed3a506de338038b68ad7d")
!424 = !DISubprogram(name: "print", linkageName: "_ZNK5clang8QualType5printERN4llvm11raw_ostreamERKNS_14PrintingPolicyERKNS1_5TwineE", scope: !275, file: !47, line: 874, type: !425, scopeLine: 874, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!425 = !DISubroutineType(types: !426)
!426 = !{null, !281, !427, !420, !430}
!427 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !428, size: 64)
!428 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "raw_ostream", scope: !13, file: !429, line: 47, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm11raw_ostreamE")
!429 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/LLVM.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "fe3bbe0ce03f58807015987f11a2006c")
!430 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !431, size: 64)
!431 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !432)
!432 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Twine", scope: !13, file: !429, line: 30, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm5TwineE")
!433 = !DISubprogram(name: "print", linkageName: "_ZN5clang8QualType5printENS_13SplitQualTypeERN4llvm11raw_ostreamERKNS_14PrintingPolicyERKNS2_5TwineE", scope: !275, file: !47, line: 878, type: !434, scopeLine: 878, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!434 = !DISubroutineType(types: !435)
!435 = !{null, !320, !427, !420, !430}
!436 = !DISubprogram(name: "print", linkageName: "_ZN5clang8QualType5printEPKNS_4TypeENS_10QualifiersERN4llvm11raw_ostreamERKNS_14PrintingPolicyERKNS5_5TwineE", scope: !275, file: !47, line: 882, type: !437, scopeLine: 882, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!437 = !DISubroutineType(types: !438)
!438 = !{null, !141, !262, !427, !420, !430}
!439 = !DISubprogram(name: "getAsStringInternal", linkageName: "_ZNK5clang8QualType19getAsStringInternalERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_14PrintingPolicyE", scope: !275, file: !47, line: 886, type: !440, scopeLine: 886, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!440 = !DISubroutineType(types: !441)
!441 = !{null, !281, !442, !420}
!442 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !405, size: 64)
!443 = !DISubprogram(name: "getAsStringInternal", linkageName: "_ZN5clang8QualType19getAsStringInternalENS_13SplitQualTypeERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_14PrintingPolicyE", scope: !275, file: !47, line: 890, type: !444, scopeLine: 890, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!444 = !DISubroutineType(types: !445)
!445 = !{null, !320, !442, !420}
!446 = !DISubprogram(name: "getAsStringInternal", linkageName: "_ZN5clang8QualType19getAsStringInternalEPKNS_4TypeENS_10QualifiersERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_14PrintingPolicyE", scope: !275, file: !47, line: 894, type: !447, scopeLine: 894, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!447 = !DISubroutineType(types: !448)
!448 = !{null, !141, !262, !442, !420}
!449 = !DISubprogram(name: "stream", linkageName: "_ZNK5clang8QualType6streamERKNS_14PrintingPolicyERKN4llvm5TwineE", scope: !275, file: !47, line: 914, type: !450, scopeLine: 914, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!450 = !DISubroutineType(types: !451)
!451 = !{!452, !281, !420, !430}
!452 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StreamedQualTypeHelper", scope: !275, file: !47, line: 898, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang8QualType22StreamedQualTypeHelperE")
!453 = !DISubprogram(name: "dump", linkageName: "_ZNK5clang8QualType4dumpEPKc", scope: !275, file: !47, line: 919, type: !454, scopeLine: 919, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!454 = !DISubroutineType(types: !455)
!455 = !{null, !281, !456}
!456 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !457, size: 64)
!457 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !458)
!458 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
!459 = !DISubprogram(name: "dump", linkageName: "_ZNK5clang8QualType4dumpEv", scope: !275, file: !47, line: 920, type: !460, scopeLine: 920, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!460 = !DISubroutineType(types: !461)
!461 = !{null, !281}
!462 = !DISubprogram(name: "Profile", linkageName: "_ZNK5clang8QualType7ProfileERN4llvm16FoldingSetNodeIDE", scope: !275, file: !47, line: 922, type: !463, scopeLine: 922, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!463 = !DISubroutineType(types: !464)
!464 = !{null, !281, !465}
!465 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !466, size: 64)
!466 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FoldingSetNodeID", scope: !13, file: !467, line: 294, size: 1216, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm16FoldingSetNodeIDE")
!467 = !DIFile(filename: "llvm34/include/llvm/ADT/FoldingSet.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "067c8c62e1324b93845c75f18ffd3a56")
!468 = !DISubprogram(name: "getAddressSpace", linkageName: "_ZNK5clang8QualType15getAddressSpaceEv", scope: !275, file: !47, line: 927, type: !303, scopeLine: 927, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!469 = !DISubprogram(name: "getObjCGCAttr", linkageName: "_ZNK5clang8QualType13getObjCGCAttrEv", scope: !275, file: !47, line: 930, type: !470, scopeLine: 930, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!470 = !DISubroutineType(types: !471)
!471 = !{!261, !281}
!472 = !DISubprogram(name: "isObjCGCWeak", linkageName: "_ZNK5clang8QualType12isObjCGCWeakEv", scope: !275, file: !47, line: 933, type: !333, scopeLine: 933, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!473 = !DISubprogram(name: "isObjCGCStrong", linkageName: "_ZNK5clang8QualType14isObjCGCStrongEv", scope: !275, file: !47, line: 938, type: !333, scopeLine: 938, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!474 = !DISubprogram(name: "getObjCLifetime", linkageName: "_ZNK5clang8QualType15getObjCLifetimeEv", scope: !275, file: !47, line: 943, type: !475, scopeLine: 943, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!475 = !DISubroutineType(types: !476)
!476 = !{!267, !281}
!477 = !DISubprogram(name: "hasNonTrivialObjCLifetime", linkageName: "_ZNK5clang8QualType25hasNonTrivialObjCLifetimeEv", scope: !275, file: !47, line: 947, type: !333, scopeLine: 947, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!478 = !DISubprogram(name: "hasStrongOrWeakObjCLifetime", linkageName: "_ZNK5clang8QualType27hasStrongOrWeakObjCLifetimeEv", scope: !275, file: !47, line: 951, type: !333, scopeLine: 951, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!479 = !DISubprogram(name: "isDestructedType", linkageName: "_ZNK5clang8QualType16isDestructedTypeEv", scope: !275, file: !47, line: 966, type: !480, scopeLine: 966, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!480 = !DISubroutineType(types: !481)
!481 = !{!274, !281}
!482 = !DISubprogram(name: "isCForbiddenLValueType", linkageName: "_ZNK5clang8QualType22isCForbiddenLValueTypeEv", scope: !275, file: !47, line: 980, type: !333, scopeLine: 980, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!483 = !DISubprogram(name: "isConstant", linkageName: "_ZN5clang8QualType10isConstantES0_RNS_10ASTContextE", scope: !275, file: !47, line: 986, type: !484, scopeLine: 986, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!484 = !DISubroutineType(types: !485)
!485 = !{!82, !275, !355}
!486 = !DISubprogram(name: "getDesugaredType", linkageName: "_ZN5clang8QualType16getDesugaredTypeES0_RKNS_10ASTContextE", scope: !275, file: !47, line: 987, type: !487, scopeLine: 987, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!487 = !DISubroutineType(types: !488)
!488 = !{!275, !275, !396}
!489 = !DISubprogram(name: "getSplitDesugaredType", linkageName: "_ZN5clang8QualType21getSplitDesugaredTypeES0_", scope: !275, file: !47, line: 988, type: !490, scopeLine: 988, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!490 = !DISubroutineType(types: !491)
!491 = !{!320, !275}
!492 = !DISubprogram(name: "getSplitUnqualifiedTypeImpl", linkageName: "_ZN5clang8QualType27getSplitUnqualifiedTypeImplES0_", scope: !275, file: !47, line: 989, type: !490, scopeLine: 989, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!493 = !DISubprogram(name: "getSingleStepDesugaredTypeImpl", linkageName: "_ZN5clang8QualType30getSingleStepDesugaredTypeImplES0_RKNS_10ASTContextE", scope: !275, file: !47, line: 990, type: !487, scopeLine: 990, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!494 = !DISubprogram(name: "IgnoreParens", linkageName: "_ZN5clang8QualType12IgnoreParensES0_", scope: !275, file: !47, line: 992, type: !495, scopeLine: 992, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!495 = !DISubroutineType(types: !496)
!496 = !{!275, !275}
!497 = !DISubprogram(name: "isDestructedTypeImpl", linkageName: "_ZN5clang8QualType20isDestructedTypeImplES0_", scope: !275, file: !47, line: 993, type: !498, scopeLine: 993, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!498 = !DISubroutineType(types: !499)
!499 = !{!274, !275}
!500 = !{!501, !502, !503, !504}
!501 = !DIEnumerator(name: "DK_none", value: 0, isUnsigned: true)
!502 = !DIEnumerator(name: "DK_cxx_destructor", value: 1, isUnsigned: true)
!503 = !DIEnumerator(name: "DK_objc_strong_lifetime", value: 2, isUnsigned: true)
!504 = !DIEnumerator(name: "DK_objc_weak_lifetime", value: 3, isUnsigned: true)
!505 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !133, file: !67, line: 57, baseType: !6, size: 32, elements: !506, identifier: "_ZTSN4llvm22PointerUnionUIntTraitsIPKN5clang4TypeEPKNS1_8ExtQualsEEUt_E")
!506 = !{!507, !508, !509}
!507 = !DIEnumerator(name: "PT1BitsAv", value: 4, isUnsigned: true)
!508 = !DIEnumerator(name: "PT2BitsAv", value: 4, isUnsigned: true)
!509 = !DIEnumerator(name: "NumLowBitsAvailable", value: 4, isUnsigned: true)
!510 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !240, file: !67, line: 206, baseType: !6, size: 32, elements: !511, identifier: "_ZTSN4llvm21PointerLikeTypeTraitsINS_12PointerUnionIPKN5clang4TypeEPKNS2_8ExtQualsEEEEUt_E")
!511 = !{!512}
!512 = !DIEnumerator(name: "NumLowBitsAvailable", value: 3, isUnsigned: true)
!513 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !515, file: !514, line: 62, baseType: !6, size: 32, elements: !529, identifier: "_ZTSN4llvm21PointerLikeTypeTraitsIPKN5clang13CXXRecordDeclEEUt_E")
!514 = !DIFile(filename: "llvm34/include/llvm/Support/PointerLikeTypeTraits.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "8333c3efd9cf0bb9b9cfe8a278228322")
!515 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerLikeTypeTraits<const clang::CXXRecordDecl *>", scope: !13, file: !514, line: 52, size: 8, flags: DIFlagTypePassByValue, elements: !516, templateParams: !527, identifier: "_ZTSN4llvm21PointerLikeTypeTraitsIPKN5clang13CXXRecordDeclEEE")
!516 = !{!517, !524}
!517 = !DISubprogram(name: "getAsVoidPointer", linkageName: "_ZN4llvm21PointerLikeTypeTraitsIPKN5clang13CXXRecordDeclEE16getAsVoidPointerES4_", scope: !515, file: !514, line: 56, type: !518, scopeLine: 56, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!518 = !DISubroutineType(types: !519)
!519 = !{!117, !520}
!520 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !521, size: 64)
!521 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !522)
!522 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "CXXRecordDecl", scope: !39, file: !523, line: 275, size: 1088, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang13CXXRecordDeclE")
!523 = !DIFile(filename: "llvm34/projects/clang/include/clang/AST/DeclCXX.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "d2690d597c97934b56344e8baf6e9e76")
!524 = !DISubprogram(name: "getFromVoidPointer", linkageName: "_ZN4llvm21PointerLikeTypeTraitsIPKN5clang13CXXRecordDeclEE18getFromVoidPointerEPKv", scope: !515, file: !514, line: 59, type: !525, scopeLine: 59, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!525 = !DISubroutineType(types: !526)
!526 = !{!520, !117}
!527 = !{!528}
!528 = !DITemplateTypeParameter(name: "T", type: !520)
!529 = !{!530}
!530 = !DIEnumerator(name: "NumLowBitsAvailable", value: 2, isUnsigned: true)
!531 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "TypeID", scope: !533, file: !532, line: 53, baseType: !6, size: 32, elements: !534, identifier: "_ZTSN4llvm4Type6TypeIDE")
!532 = !DIFile(filename: "llvm34/include/llvm/IR/Type.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "8f98b5b4d6937fd908ad7cd9ffc6bee0")
!533 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Type", scope: !13, file: !532, line: 44, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm4TypeE")
!534 = !{!535, !536, !537, !538, !539, !540, !541, !542, !543, !544, !545, !546, !547, !548, !549, !550, !551, !552, !553}
!535 = !DIEnumerator(name: "VoidTyID", value: 0, isUnsigned: true)
!536 = !DIEnumerator(name: "HalfTyID", value: 1, isUnsigned: true)
!537 = !DIEnumerator(name: "FloatTyID", value: 2, isUnsigned: true)
!538 = !DIEnumerator(name: "DoubleTyID", value: 3, isUnsigned: true)
!539 = !DIEnumerator(name: "X86_FP80TyID", value: 4, isUnsigned: true)
!540 = !DIEnumerator(name: "FP128TyID", value: 5, isUnsigned: true)
!541 = !DIEnumerator(name: "PPC_FP128TyID", value: 6, isUnsigned: true)
!542 = !DIEnumerator(name: "LabelTyID", value: 7, isUnsigned: true)
!543 = !DIEnumerator(name: "MetadataTyID", value: 8, isUnsigned: true)
!544 = !DIEnumerator(name: "X86_MMXTyID", value: 9, isUnsigned: true)
!545 = !DIEnumerator(name: "IntegerTyID", value: 10, isUnsigned: true)
!546 = !DIEnumerator(name: "FunctionTyID", value: 11, isUnsigned: true)
!547 = !DIEnumerator(name: "StructTyID", value: 12, isUnsigned: true)
!548 = !DIEnumerator(name: "ArrayTyID", value: 13, isUnsigned: true)
!549 = !DIEnumerator(name: "PointerTyID", value: 14, isUnsigned: true)
!550 = !DIEnumerator(name: "VectorTyID", value: 15, isUnsigned: true)
!551 = !DIEnumerator(name: "NumTypeIDs", value: 16, isUnsigned: true)
!552 = !DIEnumerator(name: "LastPrimitiveTyID", value: 9, isUnsigned: true)
!553 = !DIEnumerator(name: "FirstDerivedTyID", value: 10, isUnsigned: true)
!554 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !556, file: !555, line: 238, baseType: !6, size: 32, elements: !653, identifier: "_ZTSN4llvm11SmallPtrSetIPKN5clang13CXXRecordDeclELj4EEUt_E")
!555 = !DIFile(filename: "llvm34/include/llvm/ADT/SmallPtrSet.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "a8637a3720e7d16110f2e5a1c96cd729")
!556 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallPtrSet<const clang::CXXRecordDecl *, 4U>", scope: !13, file: !555, line: 236, size: 512, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !557, templateParams: !650, identifier: "_ZTSN4llvm11SmallPtrSetIPKN5clang13CXXRecordDeclELj4EEE")
!557 = !{!558, !616, !620, !624, !629, !632, !633, !637, !642, !643, !646}
!558 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !556, baseType: !559, flags: DIFlagPublic, extraData: i32 0)
!559 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallPtrSetImpl", scope: !13, file: !555, line: 48, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !560, identifier: "_ZTSN4llvm15SmallPtrSetImplE")
!560 = !{!561, !563, !564, !565, !566, !567, !573, !576, !579, !583, !586, !587, !590, !591, !594, !595, !598, !599, !604, !605, !608, !611, !615}
!561 = !DIDerivedType(tag: DW_TAG_member, name: "SmallArray", scope: !559, file: !555, line: 52, baseType: !562, size: 64, flags: DIFlagProtected)
!562 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !117, size: 64)
!563 = !DIDerivedType(tag: DW_TAG_member, name: "CurArray", scope: !559, file: !555, line: 55, baseType: !562, size: 64, offset: 64, flags: DIFlagProtected)
!564 = !DIDerivedType(tag: DW_TAG_member, name: "CurArraySize", scope: !559, file: !555, line: 57, baseType: !6, size: 32, offset: 128, flags: DIFlagProtected)
!565 = !DIDerivedType(tag: DW_TAG_member, name: "NumElements", scope: !559, file: !555, line: 60, baseType: !6, size: 32, offset: 160, flags: DIFlagProtected)
!566 = !DIDerivedType(tag: DW_TAG_member, name: "NumTombstones", scope: !559, file: !555, line: 61, baseType: !6, size: 32, offset: 192, flags: DIFlagProtected)
!567 = !DISubprogram(name: "SmallPtrSetImpl", scope: !559, file: !555, line: 64, type: !568, scopeLine: 64, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!568 = !DISubroutineType(types: !569)
!569 = !{null, !570, !562, !571}
!570 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !559, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!571 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !572, size: 64)
!572 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !559)
!573 = !DISubprogram(name: "SmallPtrSetImpl", scope: !559, file: !555, line: 65, type: !574, scopeLine: 65, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!574 = !DISubroutineType(types: !575)
!575 = !{null, !570, !562, !6}
!576 = !DISubprogram(name: "~SmallPtrSetImpl", scope: !559, file: !555, line: 71, type: !577, scopeLine: 71, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!577 = !DISubroutineType(types: !578)
!578 = !{null, !570}
!579 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm15SmallPtrSetImpl5emptyEv", scope: !559, file: !555, line: 74, type: !580, scopeLine: 74, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!580 = !DISubroutineType(types: !581)
!581 = !{!82, !582}
!582 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !572, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!583 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm15SmallPtrSetImpl4sizeEv", scope: !559, file: !555, line: 75, type: !584, scopeLine: 75, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!584 = !DISubroutineType(types: !585)
!585 = !{!6, !582}
!586 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallPtrSetImpl5clearEv", scope: !559, file: !555, line: 77, type: !577, scopeLine: 77, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!587 = !DISubprogram(name: "getTombstoneMarker", linkageName: "_ZN4llvm15SmallPtrSetImpl18getTombstoneMarkerEv", scope: !559, file: !555, line: 90, type: !588, scopeLine: 90, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!588 = !DISubroutineType(types: !589)
!589 = !{!81}
!590 = !DISubprogram(name: "getEmptyMarker", linkageName: "_ZN4llvm15SmallPtrSetImpl14getEmptyMarkerEv", scope: !559, file: !555, line: 91, type: !588, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!591 = !DISubprogram(name: "insert_imp", linkageName: "_ZN4llvm15SmallPtrSetImpl10insert_impEPKv", scope: !559, file: !555, line: 100, type: !592, scopeLine: 100, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!592 = !DISubroutineType(types: !593)
!593 = !{!82, !570, !117}
!594 = !DISubprogram(name: "erase_imp", linkageName: "_ZN4llvm15SmallPtrSetImpl9erase_impEPKv", scope: !559, file: !555, line: 106, type: !592, scopeLine: 106, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!595 = !DISubprogram(name: "count_imp", linkageName: "_ZNK4llvm15SmallPtrSetImpl9count_impEPKv", scope: !559, file: !555, line: 108, type: !596, scopeLine: 108, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!596 = !DISubroutineType(types: !597)
!597 = !{!82, !582, !117}
!598 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm15SmallPtrSetImpl7isSmallEv", scope: !559, file: !555, line: 123, type: !580, scopeLine: 123, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!599 = !DISubprogram(name: "FindBucketFor", linkageName: "_ZNK4llvm15SmallPtrSetImpl13FindBucketForEPKv", scope: !559, file: !555, line: 125, type: !600, scopeLine: 125, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!600 = !DISubroutineType(types: !601)
!601 = !{!602, !582, !117}
!602 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !603, size: 64)
!603 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !117)
!604 = !DISubprogram(name: "shrink_and_clear", linkageName: "_ZN4llvm15SmallPtrSetImpl16shrink_and_clearEv", scope: !559, file: !555, line: 126, type: !577, scopeLine: 126, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!605 = !DISubprogram(name: "Grow", linkageName: "_ZN4llvm15SmallPtrSetImpl4GrowEj", scope: !559, file: !555, line: 129, type: !606, scopeLine: 129, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!606 = !DISubroutineType(types: !607)
!607 = !{null, !570, !6}
!608 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallPtrSetImplaSERKS0_", scope: !559, file: !555, line: 131, type: !609, scopeLine: 131, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!609 = !DISubroutineType(types: !610)
!610 = !{null, !570, !571}
!611 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallPtrSetImpl4swapERS0_", scope: !559, file: !555, line: 135, type: !612, scopeLine: 135, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!612 = !DISubroutineType(types: !613)
!613 = !{null, !570, !614}
!614 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !559, size: 64)
!615 = !DISubprogram(name: "CopyFrom", linkageName: "_ZN4llvm15SmallPtrSetImpl8CopyFromERKS0_", scope: !559, file: !555, line: 137, type: !609, scopeLine: 137, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!616 = !DIDerivedType(tag: DW_TAG_member, name: "SmallStorage", scope: !556, file: !555, line: 240, baseType: !617, size: 256, offset: 256)
!617 = !DICompositeType(tag: DW_TAG_array_type, baseType: !117, size: 256, elements: !618)
!618 = !{!619}
!619 = !DISubrange(count: 4)
!620 = !DISubprogram(name: "SmallPtrSet", scope: !556, file: !555, line: 243, type: !621, scopeLine: 243, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!621 = !DISubroutineType(types: !622)
!622 = !{null, !623}
!623 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !556, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!624 = !DISubprogram(name: "SmallPtrSet", scope: !556, file: !555, line: 244, type: !625, scopeLine: 244, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!625 = !DISubroutineType(types: !626)
!626 = !{null, !623, !627}
!627 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !628, size: 64)
!628 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !556)
!629 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm11SmallPtrSetIPKN5clang13CXXRecordDeclELj4EE6insertES4_", scope: !556, file: !555, line: 253, type: !630, scopeLine: 253, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!630 = !DISubroutineType(types: !631)
!631 = !{!82, !623, !520}
!632 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm11SmallPtrSetIPKN5clang13CXXRecordDeclELj4EE5eraseES4_", scope: !556, file: !555, line: 259, type: !630, scopeLine: 259, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!633 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm11SmallPtrSetIPKN5clang13CXXRecordDeclELj4EE5countES4_", scope: !556, file: !555, line: 264, type: !634, scopeLine: 264, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!634 = !DISubroutineType(types: !635)
!635 = !{!82, !636, !520}
!636 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !628, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!637 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm11SmallPtrSetIPKN5clang13CXXRecordDeclELj4EE5beginEv", scope: !556, file: !555, line: 276, type: !638, scopeLine: 276, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!638 = !DISubroutineType(types: !639)
!639 = !{!640, !636}
!640 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !556, file: !555, line: 274, baseType: !641)
!641 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallPtrSetIterator<const clang::CXXRecordDecl *>", scope: !13, file: !555, line: 174, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm19SmallPtrSetIteratorIPKN5clang13CXXRecordDeclEEE")
!642 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm11SmallPtrSetIPKN5clang13CXXRecordDeclELj4EE3endEv", scope: !556, file: !555, line: 279, type: !638, scopeLine: 279, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!643 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallPtrSetIPKN5clang13CXXRecordDeclELj4EEaSERKS5_", scope: !556, file: !555, line: 286, type: !644, scopeLine: 286, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!644 = !DISubroutineType(types: !645)
!645 = !{!627, !623, !627}
!646 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm11SmallPtrSetIPKN5clang13CXXRecordDeclELj4EE4swapERS5_", scope: !556, file: !555, line: 292, type: !647, scopeLine: 292, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!647 = !DISubroutineType(types: !648)
!648 = !{null, !623, !649}
!649 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !556, size: 64)
!650 = !{!651, !652}
!651 = !DITemplateTypeParameter(name: "PtrType", type: !520)
!652 = !DITemplateValueParameter(name: "SmallSize", type: !6, value: i32 4)
!653 = !{!654}
!654 = !DIEnumerator(name: "SmallSizePowTwo", value: 4, isUnsigned: true)
!655 = !DICompositeType(tag: DW_TAG_enumeration_type, scope: !408, file: !656, line: 1875, baseType: !6, size: 32, elements: !657)
!656 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_algo.h", directory: "", checksumkind: CSK_MD5, checksum: "52ea3eafc6a0b82ae28b19432ed6df52")
!657 = !{!658}
!658 = !DIEnumerator(name: "_S_threshold", value: 16, isUnsigned: true)
!659 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "ManglerKind", scope: !661, file: !660, line: 69, baseType: !6, size: 32, elements: !662, identifier: "_ZTSN5clang13MangleContext11ManglerKindE")
!660 = !DIFile(filename: "llvm34/projects/clang/include/clang/AST/Mangle.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "1d162f10d5378735b2b66a0f78f76c5a")
!661 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MangleContext", scope: !39, file: !660, line: 67, size: 640, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang13MangleContextE")
!662 = !{!663, !664}
!663 = !DIEnumerator(name: "MK_Itanium", value: 0, isUnsigned: true)
!664 = !DIEnumerator(name: "MK_Microsoft", value: 1, isUnsigned: true)
!665 = !{!82, !666, !117, !746, !747, !750, !248, !752, !81, !56, !753, !6, !701, !754, !520, !758, !761, !846, !847, !849, !852, !855, !910, !911, !913, !1045, !1141, !1144, !1147, !1257, !1258, !531, !1260, !1268, !1276, !1089, !1369, !1380, !1022, !1634, !1636, !1638, !1700, !1655, !1759, !1810, !1580, !1811, !986, !1812, !1573, !1896, !1931, !1902, !1315, !1947, !1275, !1348, !1957, !1980, !1401, !1396, !1392, !1437, !1440, !1443, !915, !918, !66, !71, !2096, !275, !53, !767, !763, !786, !860, !857, !1173, !1170, !1152, !1149, !2100, !2216, !2213, !556, !559, !2056, !1813, !1816, !1381, !1702, !2282, !2295, !2299, !2302, !2305, !1046, !2494, !2497, !2500, !1277, !2612}
!666 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "CharUnits", scope: !39, file: !667, line: 38, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !668, identifier: "_ZTSN5clang9CharUnitsE")
!667 = !DIFile(filename: "llvm34/projects/clang/include/clang/AST/CharUnits.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "fd65449f38a583cd4e23337ccc808f59")
!668 = !{!669, !675, !679, !682, !685, !686, !689, !695, !698, !702, !703, !704, !705, !709, !710, !711, !712, !713, !714, !717, !718, !719, !720, !721, !724, !725, !728, !729, !730, !733, !734, !737, !740, !743}
!669 = !DIDerivedType(tag: DW_TAG_member, name: "Quantity", scope: !666, file: !667, line: 43, baseType: !670, size: 64)
!670 = !DIDerivedType(tag: DW_TAG_typedef, name: "QuantityType", scope: !666, file: !667, line: 40, baseType: !671)
!671 = !DIDerivedType(tag: DW_TAG_typedef, name: "int64_t", file: !672, line: 27, baseType: !673)
!672 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h", directory: "", checksumkind: CSK_MD5, checksum: "457547631e07cd24d9a14c8410e28e57")
!673 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int64_t", file: !674, line: 43, baseType: !58)
!674 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types.h", directory: "", checksumkind: CSK_MD5, checksum: "25679ba19d359e314e48661b21f5aa1f")
!675 = !DISubprogram(name: "CharUnits", scope: !666, file: !667, line: 45, type: !676, scopeLine: 45, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!676 = !DISubroutineType(types: !677)
!677 = !{null, !678, !670}
!678 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !666, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!679 = !DISubprogram(name: "CharUnits", scope: !666, file: !667, line: 50, type: !680, scopeLine: 50, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!680 = !DISubroutineType(types: !681)
!681 = !{null, !678}
!682 = !DISubprogram(name: "Zero", linkageName: "_ZN5clang9CharUnits4ZeroEv", scope: !666, file: !667, line: 53, type: !683, scopeLine: 53, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!683 = !DISubroutineType(types: !684)
!684 = !{!666}
!685 = !DISubprogram(name: "One", linkageName: "_ZN5clang9CharUnits3OneEv", scope: !666, file: !667, line: 58, type: !683, scopeLine: 58, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!686 = !DISubprogram(name: "fromQuantity", linkageName: "_ZN5clang9CharUnits12fromQuantityEl", scope: !666, file: !667, line: 63, type: !687, scopeLine: 63, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!687 = !DISubroutineType(types: !688)
!688 = !{!666, !670}
!689 = !DISubprogram(name: "operator+=", linkageName: "_ZN5clang9CharUnitspLERKS0_", scope: !666, file: !667, line: 68, type: !690, scopeLine: 68, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!690 = !DISubroutineType(types: !691)
!691 = !{!692, !678, !693}
!692 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !666, size: 64)
!693 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !694, size: 64)
!694 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !666)
!695 = !DISubprogram(name: "operator++", linkageName: "_ZN5clang9CharUnitsppEv", scope: !666, file: !667, line: 72, type: !696, scopeLine: 72, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!696 = !DISubroutineType(types: !697)
!697 = !{!692, !678}
!698 = !DISubprogram(name: "operator++", linkageName: "_ZN5clang9CharUnitsppEi", scope: !666, file: !667, line: 76, type: !699, scopeLine: 76, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!699 = !DISubroutineType(types: !700)
!700 = !{!666, !678, !701}
!701 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!702 = !DISubprogram(name: "operator-=", linkageName: "_ZN5clang9CharUnitsmIERKS0_", scope: !666, file: !667, line: 79, type: !690, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!703 = !DISubprogram(name: "operator--", linkageName: "_ZN5clang9CharUnitsmmEv", scope: !666, file: !667, line: 83, type: !696, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!704 = !DISubprogram(name: "operator--", linkageName: "_ZN5clang9CharUnitsmmEi", scope: !666, file: !667, line: 87, type: !699, scopeLine: 87, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!705 = !DISubprogram(name: "operator==", linkageName: "_ZNK5clang9CharUnitseqERKS0_", scope: !666, file: !667, line: 92, type: !706, scopeLine: 92, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!706 = !DISubroutineType(types: !707)
!707 = !{!82, !708, !693}
!708 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !694, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!709 = !DISubprogram(name: "operator!=", linkageName: "_ZNK5clang9CharUnitsneERKS0_", scope: !666, file: !667, line: 95, type: !706, scopeLine: 95, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!710 = !DISubprogram(name: "operator<", linkageName: "_ZNK5clang9CharUnitsltERKS0_", scope: !666, file: !667, line: 100, type: !706, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!711 = !DISubprogram(name: "operator<=", linkageName: "_ZNK5clang9CharUnitsleERKS0_", scope: !666, file: !667, line: 103, type: !706, scopeLine: 103, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!712 = !DISubprogram(name: "operator>", linkageName: "_ZNK5clang9CharUnitsgtERKS0_", scope: !666, file: !667, line: 106, type: !706, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!713 = !DISubprogram(name: "operator>=", linkageName: "_ZNK5clang9CharUnitsgeERKS0_", scope: !666, file: !667, line: 109, type: !706, scopeLine: 109, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!714 = !DISubprogram(name: "isZero", linkageName: "_ZNK5clang9CharUnits6isZeroEv", scope: !666, file: !667, line: 116, type: !715, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!715 = !DISubroutineType(types: !716)
!716 = !{!82, !708}
!717 = !DISubprogram(name: "isOne", linkageName: "_ZNK5clang9CharUnits5isOneEv", scope: !666, file: !667, line: 119, type: !715, scopeLine: 119, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!718 = !DISubprogram(name: "isPositive", linkageName: "_ZNK5clang9CharUnits10isPositiveEv", scope: !666, file: !667, line: 122, type: !715, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!719 = !DISubprogram(name: "isNegative", linkageName: "_ZNK5clang9CharUnits10isNegativeEv", scope: !666, file: !667, line: 125, type: !715, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!720 = !DISubprogram(name: "isPowerOfTwo", linkageName: "_ZNK5clang9CharUnits12isPowerOfTwoEv", scope: !666, file: !667, line: 129, type: !715, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!721 = !DISubprogram(name: "operator*", linkageName: "_ZNK5clang9CharUnitsmlEl", scope: !666, file: !667, line: 134, type: !722, scopeLine: 134, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!722 = !DISubroutineType(types: !723)
!723 = !{!666, !708, !670}
!724 = !DISubprogram(name: "operator/", linkageName: "_ZNK5clang9CharUnitsdvEl", scope: !666, file: !667, line: 137, type: !722, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!725 = !DISubprogram(name: "operator/", linkageName: "_ZNK5clang9CharUnitsdvERKS0_", scope: !666, file: !667, line: 140, type: !726, scopeLine: 140, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!726 = !DISubroutineType(types: !727)
!727 = !{!670, !708, !693}
!728 = !DISubprogram(name: "operator%", linkageName: "_ZNK5clang9CharUnitsrmEl", scope: !666, file: !667, line: 143, type: !722, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!729 = !DISubprogram(name: "operator%", linkageName: "_ZNK5clang9CharUnitsrmERKS0_", scope: !666, file: !667, line: 146, type: !726, scopeLine: 146, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!730 = !DISubprogram(name: "operator+", linkageName: "_ZNK5clang9CharUnitsplERKS0_", scope: !666, file: !667, line: 149, type: !731, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!731 = !DISubroutineType(types: !732)
!732 = !{!666, !708, !693}
!733 = !DISubprogram(name: "operator-", linkageName: "_ZNK5clang9CharUnitsmiERKS0_", scope: !666, file: !667, line: 152, type: !731, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!734 = !DISubprogram(name: "operator-", linkageName: "_ZNK5clang9CharUnitsngEv", scope: !666, file: !667, line: 155, type: !735, scopeLine: 155, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!735 = !DISubroutineType(types: !736)
!736 = !{!666, !708}
!737 = !DISubprogram(name: "getQuantity", linkageName: "_ZNK5clang9CharUnits11getQuantityEv", scope: !666, file: !667, line: 163, type: !738, scopeLine: 163, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!738 = !DISubroutineType(types: !739)
!739 = !{!670, !708}
!740 = !DISubprogram(name: "RoundUpToAlignment", linkageName: "_ZN5clang9CharUnits18RoundUpToAlignmentERKS0_", scope: !666, file: !667, line: 168, type: !741, scopeLine: 168, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!741 = !DISubroutineType(types: !742)
!742 = !{!666, !678, !693}
!743 = !DISubprogram(name: "alignmentAtOffset", linkageName: "_ZN5clang9CharUnits17alignmentAtOffsetES0_", scope: !666, file: !667, line: 175, type: !744, scopeLine: 175, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!744 = !DISubroutineType(types: !745)
!745 = !{!666, !678, !666}
!746 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !458, size: 64)
!747 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint64_t", file: !748, line: 27, baseType: !749)
!748 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h", directory: "", checksumkind: CSK_MD5, checksum: "9754ebe022edbe8d7928fa709e442f0d")
!749 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint64_t", file: !674, line: 44, baseType: !249)
!750 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !751, size: 64)
!751 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "CXXBaseSpecifier", scope: !39, file: !523, line: 158, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang16CXXBaseSpecifierE")
!752 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !291, size: 64)
!753 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !143, size: 64)
!754 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !755, size: 64)
!755 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !756)
!756 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMap<const clang::CXXRecordDecl *, clang::ASTRecordLayout::VBaseInfo, llvm::DenseMapInfo<const clang::CXXRecordDecl *> >", scope: !13, file: !757, line: 534, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm8DenseMapIPKN5clang13CXXRecordDeclENS1_15ASTRecordLayout9VBaseInfoENS_12DenseMapInfoIS4_EEEE")
!757 = !DIFile(filename: "llvm34/include/llvm/ADT/DenseMap.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e4a1c2d5b55fe605534e57bb36c4fe71")
!758 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !759, size: 64)
!759 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !760)
!760 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapBase<llvm::DenseMap<const clang::CXXRecordDecl *, clang::ASTRecordLayout::VBaseInfo, llvm::DenseMapInfo<const clang::CXXRecordDecl *> >, const clang::CXXRecordDecl *, clang::ASTRecordLayout::VBaseInfo, llvm::DenseMapInfo<const clang::CXXRecordDecl *> >", scope: !13, file: !757, line: 41, size: 8, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang13CXXRecordDeclENS2_15ASTRecordLayout9VBaseInfoENS_12DenseMapInfoIS5_EEEES5_S7_S9_EE")
!761 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !762, size: 64)
!762 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !760, file: !757, line: 43, baseType: !763)
!763 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<const clang::CXXRecordDecl *, clang::ASTRecordLayout::VBaseInfo>", scope: !408, file: !764, line: 208, size: 192, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !765, templateParams: !843, identifier: "_ZTSSt4pairIPKN5clang13CXXRecordDeclENS0_15ASTRecordLayout9VBaseInfoEE")
!764 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_pair.h", directory: "", checksumkind: CSK_MD5, checksum: "9a7996187125e471e26ca57a6c9f4c5e")
!765 = !{!766, !804, !805, !806, !812, !816, !831, !840}
!766 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !763, baseType: !767, flags: DIFlagPrivate, extraData: i32 0)
!767 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<const clang::CXXRecordDecl *, clang::ASTRecordLayout::VBaseInfo>", scope: !408, file: !764, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !768, templateParams: !783, identifier: "_ZTSSt11__pair_baseIPKN5clang13CXXRecordDeclENS0_15ASTRecordLayout9VBaseInfoEE")
!768 = !{!769, !773, !774, !779}
!769 = !DISubprogram(name: "__pair_base", scope: !767, file: !764, line: 194, type: !770, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!770 = !DISubroutineType(types: !771)
!771 = !{null, !772}
!772 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !767, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!773 = !DISubprogram(name: "~__pair_base", scope: !767, file: !764, line: 195, type: !770, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!774 = !DISubprogram(name: "__pair_base", scope: !767, file: !764, line: 196, type: !775, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!775 = !DISubroutineType(types: !776)
!776 = !{null, !772, !777}
!777 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !778, size: 64)
!778 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !767)
!779 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIPKN5clang13CXXRecordDeclENS0_15ASTRecordLayout9VBaseInfoEEaSERKS6_", scope: !767, file: !764, line: 197, type: !780, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!780 = !DISubroutineType(types: !781)
!781 = !{!782, !772, !777}
!782 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !767, size: 64)
!783 = !{!784, !785}
!784 = !DITemplateTypeParameter(name: "_U1", type: !520)
!785 = !DITemplateTypeParameter(name: "_U2", type: !786)
!786 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "VBaseInfo", scope: !788, file: !787, line: 36, size: 128, flags: DIFlagPublic | DIFlagTypePassByValue | DIFlagNonTrivial, elements: !789, identifier: "_ZTSN5clang15ASTRecordLayout9VBaseInfoE")
!787 = !DIFile(filename: "llvm34/projects/clang/include/clang/AST/RecordLayout.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "256382ffdbc4e8d3ed9e8485fee5c583")
!788 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ASTRecordLayout", scope: !39, file: !787, line: 34, size: 384, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang15ASTRecordLayoutE")
!789 = !{!790, !791, !792, !797, !801}
!790 = !DIDerivedType(tag: DW_TAG_member, name: "VBaseOffset", scope: !786, file: !787, line: 39, baseType: !666, size: 64)
!791 = !DIDerivedType(tag: DW_TAG_member, name: "HasVtorDisp", scope: !786, file: !787, line: 45, baseType: !82, size: 8, offset: 64, flags: DIFlagPrivate)
!792 = !DISubprogram(name: "hasVtorDisp", linkageName: "_ZNK5clang15ASTRecordLayout9VBaseInfo11hasVtorDispEv", scope: !786, file: !787, line: 48, type: !793, scopeLine: 48, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!793 = !DISubroutineType(types: !794)
!794 = !{!82, !795}
!795 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !796, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!796 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !786)
!797 = !DISubprogram(name: "VBaseInfo", scope: !786, file: !787, line: 50, type: !798, scopeLine: 50, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!798 = !DISubroutineType(types: !799)
!799 = !{null, !800}
!800 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !786, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!801 = !DISubprogram(name: "VBaseInfo", scope: !786, file: !787, line: 52, type: !802, scopeLine: 52, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!802 = !DISubroutineType(types: !803)
!803 = !{null, !800, !666, !82}
!804 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !763, file: !764, line: 214, baseType: !520, size: 64)
!805 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !763, file: !764, line: 215, baseType: !786, size: 128, offset: 64)
!806 = !DISubprogram(name: "pair", scope: !763, file: !764, line: 303, type: !807, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!807 = !DISubroutineType(types: !808)
!808 = !{null, !809, !810}
!809 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !763, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!810 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !811, size: 64)
!811 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !763)
!812 = !DISubprogram(name: "pair", scope: !763, file: !764, line: 304, type: !813, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!813 = !DISubroutineType(types: !814)
!814 = !{null, !809, !815}
!815 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !763, size: 64)
!816 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPKN5clang13CXXRecordDeclENS0_15ASTRecordLayout9VBaseInfoEEaSERKS6_", scope: !763, file: !764, line: 378, type: !817, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!817 = !DISubroutineType(types: !818)
!818 = !{!819, !809, !820}
!819 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !763, size: 64)
!820 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !822, file: !821, line: 1928, baseType: !810)
!821 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/type_traits", directory: "")
!822 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<const clang::CXXRecordDecl *, clang::ASTRecordLayout::VBaseInfo> &, const std::__nonesuch_no_braces &>", scope: !408, file: !821, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !824, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIPKN5clang13CXXRecordDeclENS1_15ASTRecordLayout9VBaseInfoEERKSt20__nonesuch_no_bracesE")
!823 = !{}
!824 = !{!825, !826, !827}
!825 = !DITemplateValueParameter(name: "_Cond", type: !82, value: i8 1)
!826 = !DITemplateTypeParameter(name: "_Iftrue", type: !810)
!827 = !DITemplateTypeParameter(name: "_Iffalse", type: !828)
!828 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !829, size: 64)
!829 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !830)
!830 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__nonesuch_no_braces", scope: !408, file: !764, line: 185, size: 8, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt20__nonesuch_no_braces")
!831 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPKN5clang13CXXRecordDeclENS0_15ASTRecordLayout9VBaseInfoEEaSEOS6_", scope: !763, file: !764, line: 389, type: !832, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!832 = !DISubroutineType(types: !833)
!833 = !{!819, !809, !834}
!834 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !835, file: !821, line: 1928, baseType: !815)
!835 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<const clang::CXXRecordDecl *, clang::ASTRecordLayout::VBaseInfo> &&, std::__nonesuch_no_braces &&>", scope: !408, file: !821, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !836, identifier: "_ZTSSt11conditionalILb1EOSt4pairIPKN5clang13CXXRecordDeclENS1_15ASTRecordLayout9VBaseInfoEEOSt20__nonesuch_no_bracesE")
!836 = !{!825, !837, !838}
!837 = !DITemplateTypeParameter(name: "_Iftrue", type: !815)
!838 = !DITemplateTypeParameter(name: "_Iffalse", type: !839)
!839 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !830, size: 64)
!840 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIPKN5clang13CXXRecordDeclENS0_15ASTRecordLayout9VBaseInfoEE4swapERS6_", scope: !763, file: !764, line: 424, type: !841, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!841 = !DISubroutineType(types: !842)
!842 = !{null, !809, !819}
!843 = !{!844, !845}
!844 = !DITemplateTypeParameter(name: "_T1", type: !520)
!845 = !DITemplateTypeParameter(name: "_T2", type: !786)
!846 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !756, size: 64)
!847 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !848, size: 64)
!848 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !756, file: !757, line: 540, baseType: !762)
!849 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !850, size: 64)
!850 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !851)
!851 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMap<const clang::CXXRecordDecl *, clang::CharUnits, llvm::DenseMapInfo<const clang::CXXRecordDecl *> >", scope: !13, file: !757, line: 534, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm8DenseMapIPKN5clang13CXXRecordDeclENS1_9CharUnitsENS_12DenseMapInfoIS4_EEEE")
!852 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !853, size: 64)
!853 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !854)
!854 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapBase<llvm::DenseMap<const clang::CXXRecordDecl *, clang::CharUnits, llvm::DenseMapInfo<const clang::CXXRecordDecl *> >, const clang::CXXRecordDecl *, clang::CharUnits, llvm::DenseMapInfo<const clang::CXXRecordDecl *> >", scope: !13, file: !757, line: 41, size: 8, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang13CXXRecordDeclENS2_9CharUnitsENS_12DenseMapInfoIS5_EEEES5_S6_S8_EE")
!855 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !856, size: 64)
!856 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !854, file: !757, line: 43, baseType: !857)
!857 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<const clang::CXXRecordDecl *, clang::CharUnits>", scope: !408, file: !764, line: 208, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !858, templateParams: !908, identifier: "_ZTSSt4pairIPKN5clang13CXXRecordDeclENS0_9CharUnitsEE")
!858 = !{!859, !878, !879, !880, !886, !890, !898, !905}
!859 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !857, baseType: !860, flags: DIFlagPrivate, extraData: i32 0)
!860 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<const clang::CXXRecordDecl *, clang::CharUnits>", scope: !408, file: !764, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !861, templateParams: !876, identifier: "_ZTSSt11__pair_baseIPKN5clang13CXXRecordDeclENS0_9CharUnitsEE")
!861 = !{!862, !866, !867, !872}
!862 = !DISubprogram(name: "__pair_base", scope: !860, file: !764, line: 194, type: !863, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!863 = !DISubroutineType(types: !864)
!864 = !{null, !865}
!865 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !860, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!866 = !DISubprogram(name: "~__pair_base", scope: !860, file: !764, line: 195, type: !863, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!867 = !DISubprogram(name: "__pair_base", scope: !860, file: !764, line: 196, type: !868, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!868 = !DISubroutineType(types: !869)
!869 = !{null, !865, !870}
!870 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !871, size: 64)
!871 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !860)
!872 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIPKN5clang13CXXRecordDeclENS0_9CharUnitsEEaSERKS5_", scope: !860, file: !764, line: 197, type: !873, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!873 = !DISubroutineType(types: !874)
!874 = !{!875, !865, !870}
!875 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !860, size: 64)
!876 = !{!784, !877}
!877 = !DITemplateTypeParameter(name: "_U2", type: !666)
!878 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !857, file: !764, line: 214, baseType: !520, size: 64)
!879 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !857, file: !764, line: 215, baseType: !666, size: 64, offset: 64)
!880 = !DISubprogram(name: "pair", scope: !857, file: !764, line: 303, type: !881, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!881 = !DISubroutineType(types: !882)
!882 = !{null, !883, !884}
!883 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !857, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!884 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !885, size: 64)
!885 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !857)
!886 = !DISubprogram(name: "pair", scope: !857, file: !764, line: 304, type: !887, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!887 = !DISubroutineType(types: !888)
!888 = !{null, !883, !889}
!889 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !857, size: 64)
!890 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPKN5clang13CXXRecordDeclENS0_9CharUnitsEEaSERKS5_", scope: !857, file: !764, line: 378, type: !891, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!891 = !DISubroutineType(types: !892)
!892 = !{!893, !883, !894}
!893 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !857, size: 64)
!894 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !895, file: !821, line: 1928, baseType: !884)
!895 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<const clang::CXXRecordDecl *, clang::CharUnits> &, const std::__nonesuch_no_braces &>", scope: !408, file: !821, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !896, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIPKN5clang13CXXRecordDeclENS1_9CharUnitsEERKSt20__nonesuch_no_bracesE")
!896 = !{!825, !897, !827}
!897 = !DITemplateTypeParameter(name: "_Iftrue", type: !884)
!898 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPKN5clang13CXXRecordDeclENS0_9CharUnitsEEaSEOS5_", scope: !857, file: !764, line: 389, type: !899, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!899 = !DISubroutineType(types: !900)
!900 = !{!893, !883, !901}
!901 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !902, file: !821, line: 1928, baseType: !889)
!902 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<const clang::CXXRecordDecl *, clang::CharUnits> &&, std::__nonesuch_no_braces &&>", scope: !408, file: !821, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !903, identifier: "_ZTSSt11conditionalILb1EOSt4pairIPKN5clang13CXXRecordDeclENS1_9CharUnitsEEOSt20__nonesuch_no_bracesE")
!903 = !{!825, !904, !838}
!904 = !DITemplateTypeParameter(name: "_Iftrue", type: !889)
!905 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIPKN5clang13CXXRecordDeclENS0_9CharUnitsEE4swapERS5_", scope: !857, file: !764, line: 424, type: !906, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!906 = !DISubroutineType(types: !907)
!907 = !{null, !883, !893}
!908 = !{!844, !909}
!909 = !DITemplateTypeParameter(name: "_T2", type: !666)
!910 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !851, size: 64)
!911 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !912, size: 64)
!912 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !851, file: !757, line: 540, baseType: !856)
!913 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !915, file: !914, line: 101, baseType: !1023)
!914 = !DIFile(filename: "llvm34/include/llvm/ADT/SmallVector.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "69b512a6e55455ea0ed3a25fbee45d45")
!915 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<const clang::CXXRecordDecl *, void>", scope: !13, file: !914, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !916, templateParams: !1043, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvEE")
!916 = !{!917, !941, !964, !968, !971, !976, !979, !983, !987, !990, !991, !992, !993, !994, !1000, !1005, !1006, !1007, !1011, !1012, !1015, !1019, !1025, !1030, !1035, !1038, !1041, !1042}
!917 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !915, baseType: !918, flags: DIFlagPublic, extraData: i32 0)
!918 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorBase", scope: !13, file: !914, line: 33, size: 192, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !919, identifier: "_ZTSN4llvm15SmallVectorBaseE")
!919 = !{!920, !921, !922, !923, !929, !932, !937, !938}
!920 = !DIDerivedType(tag: DW_TAG_member, name: "BeginX", scope: !918, file: !914, line: 35, baseType: !81, size: 64, flags: DIFlagProtected)
!921 = !DIDerivedType(tag: DW_TAG_member, name: "EndX", scope: !918, file: !914, line: 35, baseType: !81, size: 64, offset: 64, flags: DIFlagProtected)
!922 = !DIDerivedType(tag: DW_TAG_member, name: "CapacityX", scope: !918, file: !914, line: 35, baseType: !81, size: 64, offset: 128, flags: DIFlagProtected)
!923 = !DISubprogram(name: "SmallVectorBase", scope: !918, file: !914, line: 38, type: !924, scopeLine: 38, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!924 = !DISubroutineType(types: !925)
!925 = !{null, !926, !81, !927}
!926 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !918, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!927 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", file: !928, line: 46, baseType: !249)
!928 = !DIFile(filename: "llvm5/build/lib/clang/15.0.3/include/stddef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "b76978376d35d5cd171876ac58ac1256")
!929 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm15SmallVectorBase8grow_podEPvmm", scope: !918, file: !914, line: 43, type: !930, scopeLine: 43, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!930 = !DISubroutineType(types: !931)
!931 = !{null, !926, !81, !927, !927}
!932 = !DISubprogram(name: "size_in_bytes", linkageName: "_ZNK4llvm15SmallVectorBase13size_in_bytesEv", scope: !918, file: !914, line: 47, type: !933, scopeLine: 47, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!933 = !DISubroutineType(types: !934)
!934 = !{!927, !935}
!935 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !936, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!936 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !918)
!937 = !DISubprogram(name: "capacity_in_bytes", linkageName: "_ZNK4llvm15SmallVectorBase17capacity_in_bytesEv", scope: !918, file: !914, line: 52, type: !933, scopeLine: 52, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!938 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm15SmallVectorBase5emptyEv", scope: !918, file: !914, line: 56, type: !939, scopeLine: 56, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!939 = !DISubroutineType(types: !940)
!940 = !{!82, !935}
!941 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !915, file: !914, line: 74, baseType: !942, size: 64, offset: 192)
!942 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !915, file: !914, line: 73, baseType: !943)
!943 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<const clang::CXXRecordDecl *, char, char, char, char, char, char>", scope: !13, file: !944, line: 199, size: 64, flags: DIFlagTypePassByValue, elements: !945, templateParams: !956, identifier: "_ZTSN4llvm21AlignedCharArrayUnionIPKN5clang13CXXRecordDeclEccccccEE")
!944 = !DIFile(filename: "llvm34/include/llvm/Support/AlignOf.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "55acc245b7ffca1b8660602cb703d9fb")
!945 = !{!946}
!946 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !943, baseType: !947, extraData: i32 0)
!947 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<8UL, 8UL>", scope: !13, file: !944, line: 75, size: 64, flags: DIFlagTypePassByValue, elements: !948, templateParams: !953, identifier: "_ZTSN4llvm16AlignedCharArrayILm8ELm8EEE")
!948 = !{!949}
!949 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !947, file: !944, line: 76, baseType: !950, size: 64, align: 64)
!950 = !DICompositeType(tag: DW_TAG_array_type, baseType: !458, size: 64, elements: !951)
!951 = !{!952}
!952 = !DISubrange(count: 8)
!953 = !{!954, !955}
!954 = !DITemplateValueParameter(name: "Alignment", type: !249, value: i64 8)
!955 = !DITemplateValueParameter(name: "Size", type: !249, value: i64 8)
!956 = !{!957, !958, !959, !960, !961, !962, !963}
!957 = !DITemplateTypeParameter(name: "T1", type: !520)
!958 = !DITemplateTypeParameter(name: "T2", type: !458, defaulted: true)
!959 = !DITemplateTypeParameter(name: "T3", type: !458, defaulted: true)
!960 = !DITemplateTypeParameter(name: "T4", type: !458, defaulted: true)
!961 = !DITemplateTypeParameter(name: "T5", type: !458, defaulted: true)
!962 = !DITemplateTypeParameter(name: "T6", type: !458, defaulted: true)
!963 = !DITemplateTypeParameter(name: "T7", type: !458, defaulted: true)
!964 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !915, file: !914, line: 78, type: !965, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!965 = !DISubroutineType(types: !966)
!966 = !{null, !967, !927}
!967 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !915, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!968 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE8grow_podEmm", scope: !915, file: !914, line: 80, type: !969, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!969 = !DISubroutineType(types: !970)
!970 = !{null, !967, !927, !927}
!971 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE7isSmallEv", scope: !915, file: !914, line: 86, type: !972, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!972 = !DISubroutineType(types: !973)
!973 = !{!82, !974}
!974 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !975, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!975 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !915)
!976 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE12resetToSmallEv", scope: !915, file: !914, line: 91, type: !977, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!977 = !DISubroutineType(types: !978)
!978 = !{null, !967}
!979 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE6setEndEPS4_", scope: !915, file: !914, line: 95, type: !980, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!980 = !DISubroutineType(types: !981)
!981 = !{null, !967, !982}
!982 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !520, size: 64)
!983 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE5beginEv", scope: !915, file: !914, line: 112, type: !984, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!984 = !DISubroutineType(types: !985)
!985 = !{!986, !967}
!986 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !915, file: !914, line: 100, baseType: !982)
!987 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE5beginEv", scope: !915, file: !914, line: 113, type: !988, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!988 = !DISubroutineType(types: !989)
!989 = !{!913, !974}
!990 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE3endEv", scope: !915, file: !914, line: 114, type: !984, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!991 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE3endEv", scope: !915, file: !914, line: 115, type: !988, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!992 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE12capacity_ptrEv", scope: !915, file: !914, line: 117, type: !984, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!993 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE12capacity_ptrEv", scope: !915, file: !914, line: 118, type: !988, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!994 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE6rbeginEv", scope: !915, file: !914, line: 122, type: !995, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!995 = !DISubroutineType(types: !996)
!996 = !{!997, !967}
!997 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !915, file: !914, line: 104, baseType: !998)
!998 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const clang::CXXRecordDecl **>", scope: !408, file: !999, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPPKN5clang13CXXRecordDeclEE")
!999 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_iterator.h", directory: "", checksumkind: CSK_MD5, checksum: "43ca426be47f2e0c5f7f184d7d27a436")
!1000 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE6rbeginEv", scope: !915, file: !914, line: 123, type: !1001, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1001 = !DISubroutineType(types: !1002)
!1002 = !{!1003, !974}
!1003 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !915, file: !914, line: 103, baseType: !1004)
!1004 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const clang::CXXRecordDecl *const *>", scope: !408, file: !999, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKPKN5clang13CXXRecordDeclEE")
!1005 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE4rendEv", scope: !915, file: !914, line: 124, type: !995, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1006 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE4rendEv", scope: !915, file: !914, line: 125, type: !1001, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1007 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE4sizeEv", scope: !915, file: !914, line: 127, type: !1008, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1008 = !DISubroutineType(types: !1009)
!1009 = !{!1010, !974}
!1010 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !914, line: 97, baseType: !927)
!1011 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE8max_sizeEv", scope: !915, file: !914, line: 128, type: !1008, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1012 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE8capacityEv", scope: !915, file: !914, line: 132, type: !1013, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1013 = !DISubroutineType(types: !1014)
!1014 = !{!927, !974}
!1015 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE4dataEv", scope: !915, file: !914, line: 135, type: !1016, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1016 = !DISubroutineType(types: !1017)
!1017 = !{!1018, !967}
!1018 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !915, file: !914, line: 108, baseType: !982)
!1019 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE4dataEv", scope: !915, file: !914, line: 137, type: !1020, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1020 = !DISubroutineType(types: !1021)
!1021 = !{!1022, !974}
!1022 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !915, file: !914, line: 109, baseType: !1023)
!1023 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1024, size: 64)
!1024 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !520)
!1025 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvEixEj", scope: !915, file: !914, line: 139, type: !1026, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1026 = !DISubroutineType(types: !1027)
!1027 = !{!1028, !967, !6}
!1028 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !915, file: !914, line: 106, baseType: !1029)
!1029 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !520, size: 64)
!1030 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvEixEj", scope: !915, file: !914, line: 143, type: !1031, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1031 = !DISubroutineType(types: !1032)
!1032 = !{!1033, !974, !6}
!1033 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !915, file: !914, line: 107, baseType: !1034)
!1034 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1024, size: 64)
!1035 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE5frontEv", scope: !915, file: !914, line: 148, type: !1036, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1036 = !DISubroutineType(types: !1037)
!1037 = !{!1028, !967}
!1038 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE5frontEv", scope: !915, file: !914, line: 152, type: !1039, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1039 = !DISubroutineType(types: !1040)
!1040 = !{!1033, !974}
!1041 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE4backEv", scope: !915, file: !914, line: 157, type: !1036, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1042 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPKN5clang13CXXRecordDeclEvE4backEv", scope: !915, file: !914, line: 161, type: !1039, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1043 = !{!528, !1044}
!1044 = !DITemplateTypeParameter(type: null, defaulted: true)
!1045 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1046, file: !914, line: 100, baseType: !746)
!1046 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<char, void>", scope: !13, file: !914, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1047, templateParams: !1139, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIcvEE")
!1047 = !{!1048, !1049, !1065, !1069, !1072, !1077, !1080, !1083, !1086, !1090, !1091, !1092, !1093, !1094, !1099, !1104, !1105, !1106, !1109, !1110, !1113, !1117, !1121, !1126, !1131, !1134, !1137, !1138}
!1048 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1046, baseType: !918, flags: DIFlagPublic, extraData: i32 0)
!1049 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !1046, file: !914, line: 74, baseType: !1050, size: 8, offset: 192)
!1050 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !1046, file: !914, line: 73, baseType: !1051)
!1051 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<char, char, char, char, char, char, char>", scope: !13, file: !944, line: 199, size: 8, flags: DIFlagTypePassByValue, elements: !1052, templateParams: !1063, identifier: "_ZTSN4llvm21AlignedCharArrayUnionIcccccccEE")
!1052 = !{!1053}
!1053 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1051, baseType: !1054, extraData: i32 0)
!1054 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<1UL, 1UL>", scope: !13, file: !944, line: 75, size: 8, flags: DIFlagTypePassByValue, elements: !1055, templateParams: !1060, identifier: "_ZTSN4llvm16AlignedCharArrayILm1ELm1EEE")
!1055 = !{!1056}
!1056 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !1054, file: !944, line: 76, baseType: !1057, size: 8, align: 8)
!1057 = !DICompositeType(tag: DW_TAG_array_type, baseType: !458, size: 8, elements: !1058)
!1058 = !{!1059}
!1059 = !DISubrange(count: 1)
!1060 = !{!1061, !1062}
!1061 = !DITemplateValueParameter(name: "Alignment", type: !249, value: i64 1)
!1062 = !DITemplateValueParameter(name: "Size", type: !249, value: i64 1)
!1063 = !{!1064, !958, !959, !960, !961, !962, !963}
!1064 = !DITemplateTypeParameter(name: "T1", type: !458)
!1065 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !1046, file: !914, line: 78, type: !1066, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1066 = !DISubroutineType(types: !1067)
!1067 = !{null, !1068, !927}
!1068 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1046, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1069 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE8grow_podEmm", scope: !1046, file: !914, line: 80, type: !1070, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1070 = !DISubroutineType(types: !1071)
!1071 = !{null, !1068, !927, !927}
!1072 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE7isSmallEv", scope: !1046, file: !914, line: 86, type: !1073, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1073 = !DISubroutineType(types: !1074)
!1074 = !{!82, !1075}
!1075 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1076, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1076 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1046)
!1077 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE12resetToSmallEv", scope: !1046, file: !914, line: 91, type: !1078, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1078 = !DISubroutineType(types: !1079)
!1079 = !{null, !1068}
!1080 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE6setEndEPc", scope: !1046, file: !914, line: 95, type: !1081, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1081 = !DISubroutineType(types: !1082)
!1082 = !{null, !1068, !746}
!1083 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE5beginEv", scope: !1046, file: !914, line: 112, type: !1084, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1084 = !DISubroutineType(types: !1085)
!1085 = !{!1045, !1068}
!1086 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE5beginEv", scope: !1046, file: !914, line: 113, type: !1087, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1087 = !DISubroutineType(types: !1088)
!1088 = !{!1089, !1075}
!1089 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !1046, file: !914, line: 101, baseType: !456)
!1090 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE3endEv", scope: !1046, file: !914, line: 114, type: !1084, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1091 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE3endEv", scope: !1046, file: !914, line: 115, type: !1087, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1092 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE12capacity_ptrEv", scope: !1046, file: !914, line: 117, type: !1084, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1093 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE12capacity_ptrEv", scope: !1046, file: !914, line: 118, type: !1087, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1094 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE6rbeginEv", scope: !1046, file: !914, line: 122, type: !1095, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1095 = !DISubroutineType(types: !1096)
!1096 = !{!1097, !1068}
!1097 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !1046, file: !914, line: 104, baseType: !1098)
!1098 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<char *>", scope: !408, file: !999, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPcE")
!1099 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE6rbeginEv", scope: !1046, file: !914, line: 123, type: !1100, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1100 = !DISubroutineType(types: !1101)
!1101 = !{!1102, !1075}
!1102 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !1046, file: !914, line: 103, baseType: !1103)
!1103 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const char *>", scope: !408, file: !999, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKcE")
!1104 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE4rendEv", scope: !1046, file: !914, line: 124, type: !1095, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1105 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE4rendEv", scope: !1046, file: !914, line: 125, type: !1100, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1106 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE4sizeEv", scope: !1046, file: !914, line: 127, type: !1107, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1107 = !DISubroutineType(types: !1108)
!1108 = !{!1010, !1075}
!1109 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE8max_sizeEv", scope: !1046, file: !914, line: 128, type: !1107, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1110 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE8capacityEv", scope: !1046, file: !914, line: 132, type: !1111, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1111 = !DISubroutineType(types: !1112)
!1112 = !{!927, !1075}
!1113 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE4dataEv", scope: !1046, file: !914, line: 135, type: !1114, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1114 = !DISubroutineType(types: !1115)
!1115 = !{!1116, !1068}
!1116 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1046, file: !914, line: 108, baseType: !746)
!1117 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE4dataEv", scope: !1046, file: !914, line: 137, type: !1118, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1118 = !DISubroutineType(types: !1119)
!1119 = !{!1120, !1075}
!1120 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !1046, file: !914, line: 109, baseType: !456)
!1121 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvEixEj", scope: !1046, file: !914, line: 139, type: !1122, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1122 = !DISubroutineType(types: !1123)
!1123 = !{!1124, !1068, !6}
!1124 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1046, file: !914, line: 106, baseType: !1125)
!1125 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !458, size: 64)
!1126 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvEixEj", scope: !1046, file: !914, line: 143, type: !1127, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1127 = !DISubroutineType(types: !1128)
!1128 = !{!1129, !1075, !6}
!1129 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1046, file: !914, line: 107, baseType: !1130)
!1130 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !457, size: 64)
!1131 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE5frontEv", scope: !1046, file: !914, line: 148, type: !1132, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1132 = !DISubroutineType(types: !1133)
!1133 = !{!1124, !1068}
!1134 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE5frontEv", scope: !1046, file: !914, line: 152, type: !1135, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1135 = !DISubroutineType(types: !1136)
!1136 = !{!1129, !1075}
!1137 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE4backEv", scope: !1046, file: !914, line: 157, type: !1132, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1138 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE4backEv", scope: !1046, file: !914, line: 161, type: !1135, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1139 = !{!1140, !1044}
!1140 = !DITemplateTypeParameter(name: "T", type: !458)
!1141 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1142, size: 64)
!1142 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1143)
!1143 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMap<std::pair<const clang::CXXRecordDecl *, const clang::CXXRecordDecl *>, unsigned int, llvm::DenseMapInfo<std::pair<const clang::CXXRecordDecl *, const clang::CXXRecordDecl *> > >", scope: !13, file: !757, line: 534, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm8DenseMapISt4pairIPKN5clang13CXXRecordDeclES5_EjNS_12DenseMapInfoIS6_EEEE")
!1144 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1145, size: 64)
!1145 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1146)
!1146 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapBase<llvm::DenseMap<std::pair<const clang::CXXRecordDecl *, const clang::CXXRecordDecl *>, unsigned int, llvm::DenseMapInfo<std::pair<const clang::CXXRecordDecl *, const clang::CXXRecordDecl *> > >, std::pair<const clang::CXXRecordDecl *, const clang::CXXRecordDecl *>, unsigned int, llvm::DenseMapInfo<std::pair<const clang::CXXRecordDecl *, const clang::CXXRecordDecl *> > >", scope: !13, file: !757, line: 41, size: 8, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12DenseMapBaseINS_8DenseMapISt4pairIPKN5clang13CXXRecordDeclES6_EjNS_12DenseMapInfoIS7_EEEES7_jS9_EE")
!1147 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1148, size: 64)
!1148 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !1146, file: !757, line: 43, baseType: !1149)
!1149 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<std::pair<const clang::CXXRecordDecl *, const clang::CXXRecordDecl *>, unsigned int>", scope: !408, file: !764, line: 208, size: 192, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1150, templateParams: !1254, identifier: "_ZTSSt4pairIS_IPKN5clang13CXXRecordDeclES3_EjE")
!1150 = !{!1151, !1224, !1225, !1226, !1232, !1236, !1244, !1251}
!1151 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1149, baseType: !1152, flags: DIFlagPrivate, extraData: i32 0)
!1152 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<std::pair<const clang::CXXRecordDecl *, const clang::CXXRecordDecl *>, unsigned int>", scope: !408, file: !764, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !1153, templateParams: !1168, identifier: "_ZTSSt11__pair_baseISt4pairIPKN5clang13CXXRecordDeclES4_EjE")
!1153 = !{!1154, !1158, !1159, !1164}
!1154 = !DISubprogram(name: "__pair_base", scope: !1152, file: !764, line: 194, type: !1155, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1155 = !DISubroutineType(types: !1156)
!1156 = !{null, !1157}
!1157 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1152, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1158 = !DISubprogram(name: "~__pair_base", scope: !1152, file: !764, line: 195, type: !1155, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1159 = !DISubprogram(name: "__pair_base", scope: !1152, file: !764, line: 196, type: !1160, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1160 = !DISubroutineType(types: !1161)
!1161 = !{null, !1157, !1162}
!1162 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1163, size: 64)
!1163 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1152)
!1164 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseISt4pairIPKN5clang13CXXRecordDeclES4_EjEaSERKS6_", scope: !1152, file: !764, line: 197, type: !1165, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1165 = !DISubroutineType(types: !1166)
!1166 = !{!1167, !1157, !1162}
!1167 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1152, size: 64)
!1168 = !{!1169, !1223}
!1169 = !DITemplateTypeParameter(name: "_U1", type: !1170)
!1170 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<const clang::CXXRecordDecl *, const clang::CXXRecordDecl *>", scope: !408, file: !764, line: 208, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1171, templateParams: !1221, identifier: "_ZTSSt4pairIPKN5clang13CXXRecordDeclES3_E")
!1171 = !{!1172, !1191, !1192, !1193, !1199, !1203, !1211, !1218}
!1172 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1170, baseType: !1173, flags: DIFlagPrivate, extraData: i32 0)
!1173 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<const clang::CXXRecordDecl *, const clang::CXXRecordDecl *>", scope: !408, file: !764, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !1174, templateParams: !1189, identifier: "_ZTSSt11__pair_baseIPKN5clang13CXXRecordDeclES3_E")
!1174 = !{!1175, !1179, !1180, !1185}
!1175 = !DISubprogram(name: "__pair_base", scope: !1173, file: !764, line: 194, type: !1176, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1176 = !DISubroutineType(types: !1177)
!1177 = !{null, !1178}
!1178 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1173, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1179 = !DISubprogram(name: "~__pair_base", scope: !1173, file: !764, line: 195, type: !1176, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1180 = !DISubprogram(name: "__pair_base", scope: !1173, file: !764, line: 196, type: !1181, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1181 = !DISubroutineType(types: !1182)
!1182 = !{null, !1178, !1183}
!1183 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1184, size: 64)
!1184 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1173)
!1185 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIPKN5clang13CXXRecordDeclES3_EaSERKS4_", scope: !1173, file: !764, line: 197, type: !1186, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1186 = !DISubroutineType(types: !1187)
!1187 = !{!1188, !1178, !1183}
!1188 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1173, size: 64)
!1189 = !{!784, !1190}
!1190 = !DITemplateTypeParameter(name: "_U2", type: !520)
!1191 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !1170, file: !764, line: 214, baseType: !520, size: 64)
!1192 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !1170, file: !764, line: 215, baseType: !520, size: 64, offset: 64)
!1193 = !DISubprogram(name: "pair", scope: !1170, file: !764, line: 303, type: !1194, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1194 = !DISubroutineType(types: !1195)
!1195 = !{null, !1196, !1197}
!1196 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1170, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1197 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1198, size: 64)
!1198 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1170)
!1199 = !DISubprogram(name: "pair", scope: !1170, file: !764, line: 304, type: !1200, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1200 = !DISubroutineType(types: !1201)
!1201 = !{null, !1196, !1202}
!1202 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1170, size: 64)
!1203 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPKN5clang13CXXRecordDeclES3_EaSERKS4_", scope: !1170, file: !764, line: 378, type: !1204, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1204 = !DISubroutineType(types: !1205)
!1205 = !{!1206, !1196, !1207}
!1206 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1170, size: 64)
!1207 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1208, file: !821, line: 1928, baseType: !1197)
!1208 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<const clang::CXXRecordDecl *, const clang::CXXRecordDecl *> &, const std::__nonesuch_no_braces &>", scope: !408, file: !821, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1209, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIPKN5clang13CXXRecordDeclES4_ERKSt20__nonesuch_no_bracesE")
!1209 = !{!825, !1210, !827}
!1210 = !DITemplateTypeParameter(name: "_Iftrue", type: !1197)
!1211 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPKN5clang13CXXRecordDeclES3_EaSEOS4_", scope: !1170, file: !764, line: 389, type: !1212, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1212 = !DISubroutineType(types: !1213)
!1213 = !{!1206, !1196, !1214}
!1214 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1215, file: !821, line: 1928, baseType: !1202)
!1215 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<const clang::CXXRecordDecl *, const clang::CXXRecordDecl *> &&, std::__nonesuch_no_braces &&>", scope: !408, file: !821, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1216, identifier: "_ZTSSt11conditionalILb1EOSt4pairIPKN5clang13CXXRecordDeclES4_EOSt20__nonesuch_no_bracesE")
!1216 = !{!825, !1217, !838}
!1217 = !DITemplateTypeParameter(name: "_Iftrue", type: !1202)
!1218 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIPKN5clang13CXXRecordDeclES3_E4swapERS4_", scope: !1170, file: !764, line: 424, type: !1219, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1219 = !DISubroutineType(types: !1220)
!1220 = !{null, !1196, !1206}
!1221 = !{!844, !1222}
!1222 = !DITemplateTypeParameter(name: "_T2", type: !520)
!1223 = !DITemplateTypeParameter(name: "_U2", type: !6)
!1224 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !1149, file: !764, line: 214, baseType: !1170, size: 128)
!1225 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !1149, file: !764, line: 215, baseType: !6, size: 32, offset: 128)
!1226 = !DISubprogram(name: "pair", scope: !1149, file: !764, line: 303, type: !1227, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1227 = !DISubroutineType(types: !1228)
!1228 = !{null, !1229, !1230}
!1229 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1149, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1230 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1231, size: 64)
!1231 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1149)
!1232 = !DISubprogram(name: "pair", scope: !1149, file: !764, line: 304, type: !1233, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1233 = !DISubroutineType(types: !1234)
!1234 = !{null, !1229, !1235}
!1235 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1149, size: 64)
!1236 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIS_IPKN5clang13CXXRecordDeclES3_EjEaSERKS5_", scope: !1149, file: !764, line: 378, type: !1237, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1237 = !DISubroutineType(types: !1238)
!1238 = !{!1239, !1229, !1240}
!1239 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1149, size: 64)
!1240 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1241, file: !821, line: 1928, baseType: !1230)
!1241 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<std::pair<const clang::CXXRecordDecl *, const clang::CXXRecordDecl *>, unsigned int> &, const std::__nonesuch_no_braces &>", scope: !408, file: !821, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1242, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIS0_IPKN5clang13CXXRecordDeclES4_EjERKSt20__nonesuch_no_bracesE")
!1242 = !{!825, !1243, !827}
!1243 = !DITemplateTypeParameter(name: "_Iftrue", type: !1230)
!1244 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIS_IPKN5clang13CXXRecordDeclES3_EjEaSEOS5_", scope: !1149, file: !764, line: 389, type: !1245, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1245 = !DISubroutineType(types: !1246)
!1246 = !{!1239, !1229, !1247}
!1247 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1248, file: !821, line: 1928, baseType: !1235)
!1248 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<std::pair<const clang::CXXRecordDecl *, const clang::CXXRecordDecl *>, unsigned int> &&, std::__nonesuch_no_braces &&>", scope: !408, file: !821, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1249, identifier: "_ZTSSt11conditionalILb1EOSt4pairIS0_IPKN5clang13CXXRecordDeclES4_EjEOSt20__nonesuch_no_bracesE")
!1249 = !{!825, !1250, !838}
!1250 = !DITemplateTypeParameter(name: "_Iftrue", type: !1235)
!1251 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIS_IPKN5clang13CXXRecordDeclES3_EjE4swapERS5_", scope: !1149, file: !764, line: 424, type: !1252, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1252 = !DISubroutineType(types: !1253)
!1253 = !{null, !1229, !1239}
!1254 = !{!1255, !1256}
!1255 = !DITemplateTypeParameter(name: "_T1", type: !1170)
!1256 = !DITemplateTypeParameter(name: "_T2", type: !6)
!1257 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1143, size: 64)
!1258 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1259, size: 64)
!1259 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !1143, file: !757, line: 540, baseType: !1148)
!1260 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !1262, file: !1261, line: 185, baseType: !1269)
!1261 = !DIFile(filename: "llvm34/include/llvm/Support/Casting.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "d66d299dea704124ccd357043ea0e9d5")
!1262 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty<llvm::PointerType, llvm::Type *>", scope: !13, file: !1261, line: 183, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1263, identifier: "_ZTSN4llvm10cast_rettyINS_11PointerTypeEPNS_4TypeEEE")
!1263 = !{!1264, !1267}
!1264 = !DITemplateTypeParameter(name: "To", type: !1265)
!1265 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerType", scope: !13, file: !1266, line: 425, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm11PointerTypeE")
!1266 = !DIFile(filename: "llvm34/include/llvm/IR/DerivedTypes.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "dcedcb91dcebba5d791daad25c7c6444")
!1267 = !DITemplateTypeParameter(name: "From", type: !1268)
!1268 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !533, size: 64)
!1269 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !1270, file: !1261, line: 179, baseType: !1273)
!1270 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_wrap<llvm::PointerType, llvm::Type *, llvm::Type *>", scope: !13, file: !1261, line: 177, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1271, identifier: "_ZTSN4llvm15cast_retty_wrapINS_11PointerTypeEPNS_4TypeES3_EE")
!1271 = !{!1264, !1267, !1272}
!1272 = !DITemplateTypeParameter(name: "SimpleFrom", type: !1268)
!1273 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !1274, file: !1261, line: 156, baseType: !1275)
!1274 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_impl<llvm::PointerType, llvm::Type *>", scope: !13, file: !1261, line: 155, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1263, identifier: "_ZTSN4llvm15cast_retty_implINS_11PointerTypeEPNS_4TypeEEE")
!1275 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1265, size: 64)
!1276 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1277, file: !914, line: 100, baseType: !1308)
!1277 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<llvm::Constant *, void>", scope: !13, file: !914, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1278, templateParams: !1367, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvEE")
!1278 = !{!1279, !1280, !1290, !1294, !1297, !1302, !1305, !1309, !1312, !1318, !1319, !1320, !1321, !1322, !1327, !1332, !1333, !1334, !1337, !1338, !1341, !1345, !1349, !1354, !1359, !1362, !1365, !1366}
!1279 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1277, baseType: !918, flags: DIFlagPublic, extraData: i32 0)
!1280 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !1277, file: !914, line: 74, baseType: !1281, size: 64, offset: 192)
!1281 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !1277, file: !914, line: 73, baseType: !1282)
!1282 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<llvm::Constant *, char, char, char, char, char, char>", scope: !13, file: !944, line: 199, size: 64, flags: DIFlagTypePassByValue, elements: !1283, templateParams: !1285, identifier: "_ZTSN4llvm21AlignedCharArrayUnionIPNS_8ConstantEccccccEE")
!1283 = !{!1284}
!1284 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1282, baseType: !947, extraData: i32 0)
!1285 = !{!1286, !958, !959, !960, !961, !962, !963}
!1286 = !DITemplateTypeParameter(name: "T1", type: !1287)
!1287 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1288, size: 64)
!1288 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Constant", scope: !13, file: !1289, line: 41, size: 448, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm8ConstantE")
!1289 = !DIFile(filename: "llvm34/include/llvm/IR/Constant.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "4124d9ca22731a586674f17a48c4d198")
!1290 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !1277, file: !914, line: 78, type: !1291, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1291 = !DISubroutineType(types: !1292)
!1292 = !{null, !1293, !927}
!1293 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1277, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1294 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE8grow_podEmm", scope: !1277, file: !914, line: 80, type: !1295, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1295 = !DISubroutineType(types: !1296)
!1296 = !{null, !1293, !927, !927}
!1297 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE7isSmallEv", scope: !1277, file: !914, line: 86, type: !1298, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1298 = !DISubroutineType(types: !1299)
!1299 = !{!82, !1300}
!1300 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1301, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1301 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1277)
!1302 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE12resetToSmallEv", scope: !1277, file: !914, line: 91, type: !1303, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1303 = !DISubroutineType(types: !1304)
!1304 = !{null, !1293}
!1305 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE6setEndEPS2_", scope: !1277, file: !914, line: 95, type: !1306, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1306 = !DISubroutineType(types: !1307)
!1307 = !{null, !1293, !1308}
!1308 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1287, size: 64)
!1309 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE5beginEv", scope: !1277, file: !914, line: 112, type: !1310, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1310 = !DISubroutineType(types: !1311)
!1311 = !{!1276, !1293}
!1312 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE5beginEv", scope: !1277, file: !914, line: 113, type: !1313, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1313 = !DISubroutineType(types: !1314)
!1314 = !{!1315, !1300}
!1315 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !1277, file: !914, line: 101, baseType: !1316)
!1316 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1317, size: 64)
!1317 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1287)
!1318 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE3endEv", scope: !1277, file: !914, line: 114, type: !1310, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1319 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE3endEv", scope: !1277, file: !914, line: 115, type: !1313, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1320 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE12capacity_ptrEv", scope: !1277, file: !914, line: 117, type: !1310, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1321 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE12capacity_ptrEv", scope: !1277, file: !914, line: 118, type: !1313, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1322 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE6rbeginEv", scope: !1277, file: !914, line: 122, type: !1323, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1323 = !DISubroutineType(types: !1324)
!1324 = !{!1325, !1293}
!1325 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !1277, file: !914, line: 104, baseType: !1326)
!1326 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<llvm::Constant **>", scope: !408, file: !999, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPPN4llvm8ConstantEE")
!1327 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE6rbeginEv", scope: !1277, file: !914, line: 123, type: !1328, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1328 = !DISubroutineType(types: !1329)
!1329 = !{!1330, !1300}
!1330 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !1277, file: !914, line: 103, baseType: !1331)
!1331 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<llvm::Constant *const *>", scope: !408, file: !999, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKPN4llvm8ConstantEE")
!1332 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE4rendEv", scope: !1277, file: !914, line: 124, type: !1323, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1333 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE4rendEv", scope: !1277, file: !914, line: 125, type: !1328, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1334 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE4sizeEv", scope: !1277, file: !914, line: 127, type: !1335, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1335 = !DISubroutineType(types: !1336)
!1336 = !{!1010, !1300}
!1337 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE8max_sizeEv", scope: !1277, file: !914, line: 128, type: !1335, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1338 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE8capacityEv", scope: !1277, file: !914, line: 132, type: !1339, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1339 = !DISubroutineType(types: !1340)
!1340 = !{!927, !1300}
!1341 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE4dataEv", scope: !1277, file: !914, line: 135, type: !1342, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1342 = !DISubroutineType(types: !1343)
!1343 = !{!1344, !1293}
!1344 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1277, file: !914, line: 108, baseType: !1308)
!1345 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE4dataEv", scope: !1277, file: !914, line: 137, type: !1346, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1346 = !DISubroutineType(types: !1347)
!1347 = !{!1348, !1300}
!1348 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !1277, file: !914, line: 109, baseType: !1316)
!1349 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvEixEj", scope: !1277, file: !914, line: 139, type: !1350, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1350 = !DISubroutineType(types: !1351)
!1351 = !{!1352, !1293, !6}
!1352 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1277, file: !914, line: 106, baseType: !1353)
!1353 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1287, size: 64)
!1354 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvEixEj", scope: !1277, file: !914, line: 143, type: !1355, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1355 = !DISubroutineType(types: !1356)
!1356 = !{!1357, !1300, !6}
!1357 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1277, file: !914, line: 107, baseType: !1358)
!1358 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1317, size: 64)
!1359 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE5frontEv", scope: !1277, file: !914, line: 148, type: !1360, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1360 = !DISubroutineType(types: !1361)
!1361 = !{!1352, !1293}
!1362 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE5frontEv", scope: !1277, file: !914, line: 152, type: !1363, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1363 = !DISubroutineType(types: !1364)
!1364 = !{!1357, !1300}
!1365 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE4backEv", scope: !1277, file: !914, line: 157, type: !1360, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1366 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_8ConstantEvE4backEv", scope: !1277, file: !914, line: 161, type: !1363, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1367 = !{!1368, !1044}
!1368 = !DITemplateTypeParameter(name: "T", type: !1287)
!1369 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !1370, file: !1261, line: 185, baseType: !1374)
!1370 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty<llvm::ArrayType, llvm::Type *>", scope: !13, file: !1261, line: 183, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1371, identifier: "_ZTSN4llvm10cast_rettyINS_9ArrayTypeEPNS_4TypeEEE")
!1371 = !{!1372, !1267}
!1372 = !DITemplateTypeParameter(name: "To", type: !1373)
!1373 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ArrayType", scope: !13, file: !1266, line: 332, size: 320, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm9ArrayTypeE")
!1374 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !1375, file: !1261, line: 179, baseType: !1377)
!1375 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_wrap<llvm::ArrayType, llvm::Type *, llvm::Type *>", scope: !13, file: !1261, line: 177, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1376, identifier: "_ZTSN4llvm15cast_retty_wrapINS_9ArrayTypeEPNS_4TypeES3_EE")
!1376 = !{!1372, !1267, !1272}
!1377 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !1378, file: !1261, line: 156, baseType: !1379)
!1378 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_impl<llvm::ArrayType, llvm::Type *>", scope: !13, file: !1261, line: 155, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1371, identifier: "_ZTSN4llvm15cast_retty_implINS_9ArrayTypeEPNS_4TypeEEE")
!1379 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1373, size: 64)
!1380 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1381, file: !914, line: 100, baseType: !1573)
!1381 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<clang::CodeGen::VBTablePath *, void>", scope: !13, file: !914, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1382, templateParams: !1632, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvEE")
!1382 = !{!1383, !1384, !1555, !1559, !1562, !1567, !1570, !1574, !1577, !1583, !1584, !1585, !1586, !1587, !1592, !1597, !1598, !1599, !1602, !1603, !1606, !1610, !1614, !1619, !1624, !1627, !1630, !1631}
!1383 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1381, baseType: !918, flags: DIFlagPublic, extraData: i32 0)
!1384 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !1381, file: !914, line: 74, baseType: !1385, size: 64, offset: 192)
!1385 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !1381, file: !914, line: 73, baseType: !1386)
!1386 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<clang::CodeGen::VBTablePath *, char, char, char, char, char, char>", scope: !13, file: !944, line: 199, size: 64, flags: DIFlagTypePassByValue, elements: !1387, templateParams: !1389, identifier: "_ZTSN4llvm21AlignedCharArrayUnionIPN5clang7CodeGen11VBTablePathEccccccEE")
!1387 = !{!1388}
!1388 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1386, baseType: !947, extraData: i32 0)
!1389 = !{!1390, !958, !959, !960, !961, !962, !963}
!1390 = !DITemplateTypeParameter(name: "T1", type: !1391)
!1391 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1392, size: 64)
!1392 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "VBTablePath", scope: !38, file: !1393, line: 22, size: 640, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1394, identifier: "_ZTSN5clang7CodeGen11VBTablePathE")
!1393 = !DIFile(filename: "llvm34/projects/clang/lib/CodeGen/MicrosoftVBTables.cpp", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "a6973439eab46b43faf43bbd24913e65")
!1394 = !{!1395, !1435, !1436, !1550}
!1395 = !DIDerivedType(tag: DW_TAG_member, name: "VBInfo", scope: !1392, file: !1393, line: 28, baseType: !1396, size: 256)
!1396 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "VBTableInfo", scope: !38, file: !1397, line: 29, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1398, identifier: "_ZTSN5clang7CodeGen11VBTableInfoE")
!1397 = !DIFile(filename: "llvm34/projects/clang/lib/CodeGen/MicrosoftVBTables.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "02e7fec9dc833bc0c47640a8a0062d81")
!1398 = !{!1399, !1400, !1421, !1425, !1429}
!1399 = !DIDerivedType(tag: DW_TAG_member, name: "ReusingBase", scope: !1396, file: !1397, line: 37, baseType: !520, size: 64)
!1400 = !DIDerivedType(tag: DW_TAG_member, name: "VBPtrSubobject", scope: !1396, file: !1397, line: 40, baseType: !1401, size: 128, offset: 64)
!1401 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "BaseSubobject", scope: !39, file: !1402, line: 28, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1403, identifier: "_ZTSN5clang13BaseSubobjectE")
!1402 = !DIFile(filename: "llvm34/projects/clang/include/clang/AST/BaseSubobject.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "30047cb0d9372df8537593630c674c4f")
!1403 = !{!1404, !1405, !1406, !1410, !1413, !1418}
!1404 = !DIDerivedType(tag: DW_TAG_member, name: "Base", scope: !1401, file: !1402, line: 30, baseType: !520, size: 64)
!1405 = !DIDerivedType(tag: DW_TAG_member, name: "BaseOffset", scope: !1401, file: !1402, line: 33, baseType: !666, size: 64, offset: 64)
!1406 = !DISubprogram(name: "BaseSubobject", scope: !1401, file: !1402, line: 36, type: !1407, scopeLine: 36, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1407 = !DISubroutineType(types: !1408)
!1408 = !{null, !1409}
!1409 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1401, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1410 = !DISubprogram(name: "BaseSubobject", scope: !1401, file: !1402, line: 37, type: !1411, scopeLine: 37, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1411 = !DISubroutineType(types: !1412)
!1412 = !{null, !1409, !520, !666}
!1413 = !DISubprogram(name: "getBase", linkageName: "_ZNK5clang13BaseSubobject7getBaseEv", scope: !1401, file: !1402, line: 41, type: !1414, scopeLine: 41, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1414 = !DISubroutineType(types: !1415)
!1415 = !{!520, !1416}
!1416 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1417, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1417 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1401)
!1418 = !DISubprogram(name: "getBaseOffset", linkageName: "_ZNK5clang13BaseSubobject13getBaseOffsetEv", scope: !1401, file: !1402, line: 44, type: !1419, scopeLine: 44, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1419 = !DISubroutineType(types: !1420)
!1420 = !{!666, !1416}
!1421 = !DIDerivedType(tag: DW_TAG_member, name: "GV", scope: !1396, file: !1397, line: 43, baseType: !1422, size: 64, offset: 192)
!1422 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1423, size: 64)
!1423 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "GlobalVariable", scope: !13, file: !1424, line: 35, size: 960, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm14GlobalVariableE")
!1424 = !DIFile(filename: "llvm34/include/llvm/IR/GlobalVariable.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "89b15f8f6bcd59bb9ca5c207cdb93beb")
!1425 = !DISubprogram(name: "VBTableInfo", scope: !1396, file: !1397, line: 30, type: !1426, scopeLine: 30, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1426 = !DISubroutineType(types: !1427)
!1427 = !{null, !1428, !520, !1401, !1422}
!1428 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1396, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1429 = !DISubprogram(name: "EmitVBTableDefinition", linkageName: "_ZNK5clang7CodeGen11VBTableInfo21EmitVBTableDefinitionERNS0_13CodeGenModuleEPKNS_13CXXRecordDeclEN4llvm11GlobalValue12LinkageTypesE", scope: !1396, file: !1397, line: 46, type: !1430, scopeLine: 46, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1430 = !DISubroutineType(types: !1431)
!1431 = !{null, !1432, !1434, !520, !16}
!1432 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1433, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1433 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1396)
!1434 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !37, size: 64)
!1435 = !DIDerivedType(tag: DW_TAG_member, name: "NextBase", scope: !1392, file: !1393, line: 32, baseType: !520, size: 64, offset: 256)
!1436 = !DIDerivedType(tag: DW_TAG_member, name: "Path", scope: !1392, file: !1393, line: 37, baseType: !1437, size: 320, offset: 320)
!1437 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<const clang::CXXRecordDecl *, 1U>", scope: !13, file: !914, line: 880, size: 320, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1438, templateParams: !1526, identifier: "_ZTSN4llvm11SmallVectorIPKN5clang13CXXRecordDeclELj1EEE")
!1438 = !{!1439, !1524, !1528, !1532, !1535, !1540, !1543, !1547}
!1439 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1437, baseType: !1440, flags: DIFlagPublic, extraData: i32 0)
!1440 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<const clang::CXXRecordDecl *>", scope: !13, file: !914, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1441, templateParams: !527, identifier: "_ZTSN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEEE")
!1441 = !{!1442, !1462, !1468, !1471, !1474, !1475, !1476, !1479, !1480, !1483, !1487, !1492, !1493, !1497, !1500, !1504, !1507, !1510, !1513, !1517, !1521, !1522, !1523}
!1442 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1440, baseType: !1443, flags: DIFlagPublic, extraData: i32 0)
!1443 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<const clang::CXXRecordDecl *, true>", scope: !13, file: !914, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1444, templateParams: !1460, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseIPKN5clang13CXXRecordDeclELb1EEE")
!1444 = !{!1445, !1446, !1450, !1453, !1454, !1457}
!1445 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1443, baseType: !915, flags: DIFlagPublic, extraData: i32 0)
!1446 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !1443, file: !914, line: 298, type: !1447, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1447 = !DISubroutineType(types: !1448)
!1448 = !{null, !1449, !927}
!1449 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1443, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1450 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPKN5clang13CXXRecordDeclELb1EE13destroy_rangeEPS4_S6_", scope: !1443, file: !914, line: 301, type: !1451, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1451 = !DISubroutineType(types: !1452)
!1452 = !{null, !982, !982}
!1453 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPKN5clang13CXXRecordDeclELb1EE4growEm", scope: !1443, file: !914, line: 346, type: !1447, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1454 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPKN5clang13CXXRecordDeclELb1EE9push_backERKS4_", scope: !1443, file: !914, line: 350, type: !1455, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1455 = !DISubroutineType(types: !1456)
!1456 = !{null, !1449, !1034}
!1457 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPKN5clang13CXXRecordDeclELb1EE8pop_backEv", scope: !1443, file: !914, line: 361, type: !1458, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1458 = !DISubroutineType(types: !1459)
!1459 = !{null, !1449}
!1460 = !{!528, !1461}
!1461 = !DITemplateValueParameter(name: "isPodLike", type: !82, value: i8 1)
!1462 = !DISubprogram(name: "SmallVectorImpl", scope: !1440, file: !914, line: 374, type: !1463, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1463 = !DISubroutineType(types: !1464)
!1464 = !{null, !1465, !1466}
!1465 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1440, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1466 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1467, size: 64)
!1467 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1440)
!1468 = !DISubprogram(name: "SmallVectorImpl", scope: !1440, file: !914, line: 381, type: !1469, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1469 = !DISubroutineType(types: !1470)
!1470 = !{null, !1465, !6}
!1471 = !DISubprogram(name: "~SmallVectorImpl", scope: !1440, file: !914, line: 386, type: !1472, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1472 = !DISubroutineType(types: !1473)
!1473 = !{null, !1465}
!1474 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEE5clearEv", scope: !1440, file: !914, line: 396, type: !1472, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1475 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEE6resizeEj", scope: !1440, file: !914, line: 401, type: !1469, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1476 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEE6resizeEjRKS4_", scope: !1440, file: !914, line: 413, type: !1477, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1477 = !DISubroutineType(types: !1478)
!1478 = !{null, !1465, !6, !1034}
!1479 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEE7reserveEj", scope: !1440, file: !914, line: 425, type: !1469, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1480 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEE12pop_back_valEv", scope: !1440, file: !914, line: 430, type: !1481, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1481 = !DISubroutineType(types: !1482)
!1482 = !{!520, !1465}
!1483 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEE4swapERS5_", scope: !1440, file: !914, line: 440, type: !1484, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1484 = !DISubroutineType(types: !1485)
!1485 = !{null, !1465, !1486}
!1486 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1440, size: 64)
!1487 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEE6appendEmRKS4_", scope: !1440, file: !914, line: 460, type: !1488, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1488 = !DISubroutineType(types: !1489)
!1489 = !{null, !1465, !1490, !1034}
!1490 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1440, file: !914, line: 377, baseType: !1491)
!1491 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !915, file: !914, line: 97, baseType: !927)
!1492 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEE6assignEjRKS4_", scope: !1440, file: !914, line: 470, type: !1477, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1493 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEE5eraseEPS4_", scope: !1440, file: !914, line: 478, type: !1494, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1494 = !DISubroutineType(types: !1495)
!1495 = !{!1496, !1465, !1496}
!1496 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1440, file: !914, line: 376, baseType: !986)
!1497 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEE5eraseEPS4_S6_", scope: !1440, file: !914, line: 490, type: !1498, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1498 = !DISubroutineType(types: !1499)
!1499 = !{!1496, !1465, !1496, !1496}
!1500 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEE6insertEPS4_OS4_", scope: !1440, file: !914, line: 505, type: !1501, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1501 = !DISubroutineType(types: !1502)
!1502 = !{!1496, !1465, !1496, !1503}
!1503 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !520, size: 64)
!1504 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEE6insertEPS4_RKS4_", scope: !1440, file: !914, line: 537, type: !1505, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1505 = !DISubroutineType(types: !1506)
!1506 = !{!1496, !1465, !1496, !1034}
!1507 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEE6insertEPS4_mRKS4_", scope: !1440, file: !914, line: 568, type: !1508, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1508 = !DISubroutineType(types: !1509)
!1509 = !{!1496, !1465, !1496, !1490, !1034}
!1510 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEEaSERKS5_", scope: !1440, file: !914, line: 674, type: !1511, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1511 = !DISubroutineType(types: !1512)
!1512 = !{!1486, !1465, !1466}
!1513 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEEaSEOS5_", scope: !1440, file: !914, line: 677, type: !1514, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1514 = !DISubroutineType(types: !1515)
!1515 = !{!1486, !1465, !1516}
!1516 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1440, size: 64)
!1517 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEEeqERKS5_", scope: !1440, file: !914, line: 680, type: !1518, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1518 = !DISubroutineType(types: !1519)
!1519 = !{!82, !1520, !1466}
!1520 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1467, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1521 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEEneERKS5_", scope: !1440, file: !914, line: 684, type: !1518, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1522 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEEltERKS5_", scope: !1440, file: !914, line: 688, type: !1518, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1523 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplIPKN5clang13CXXRecordDeclEE8set_sizeEj", scope: !1440, file: !914, line: 702, type: !1469, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1524 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !1437, file: !914, line: 882, baseType: !1525, size: 8, offset: 256)
!1525 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<const clang::CXXRecordDecl *, 1U>", scope: !13, file: !914, line: 868, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1526, identifier: "_ZTSN4llvm18SmallVectorStorageIPKN5clang13CXXRecordDeclELj1EEE")
!1526 = !{!528, !1527}
!1527 = !DITemplateValueParameter(name: "N", type: !6, value: i32 1)
!1528 = !DISubprogram(name: "SmallVector", scope: !1437, file: !914, line: 884, type: !1529, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1529 = !DISubroutineType(types: !1530)
!1530 = !{null, !1531}
!1531 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1437, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1532 = !DISubprogram(name: "SmallVector", scope: !1437, file: !914, line: 887, type: !1533, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1533 = !DISubroutineType(types: !1534)
!1534 = !{null, !1531, !6, !1034}
!1535 = !DISubprogram(name: "SmallVector", scope: !1437, file: !914, line: 897, type: !1536, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1536 = !DISubroutineType(types: !1537)
!1537 = !{null, !1531, !1538}
!1538 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1539, size: 64)
!1539 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1437)
!1540 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIPKN5clang13CXXRecordDeclELj1EEaSERKS5_", scope: !1437, file: !914, line: 902, type: !1541, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1541 = !DISubroutineType(types: !1542)
!1542 = !{!1538, !1531, !1538}
!1543 = !DISubprogram(name: "SmallVector", scope: !1437, file: !914, line: 908, type: !1544, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1544 = !DISubroutineType(types: !1545)
!1545 = !{null, !1531, !1546}
!1546 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1437, size: 64)
!1547 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIPKN5clang13CXXRecordDeclELj1EEaSEOS5_", scope: !1437, file: !914, line: 913, type: !1548, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1548 = !DISubroutineType(types: !1549)
!1549 = !{!1538, !1531, !1546}
!1550 = !DISubprogram(name: "VBTablePath", scope: !1392, file: !1393, line: 23, type: !1551, scopeLine: 23, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1551 = !DISubroutineType(types: !1552)
!1552 = !{null, !1553, !1554}
!1553 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1392, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1554 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1433, size: 64)
!1555 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !1381, file: !914, line: 78, type: !1556, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1556 = !DISubroutineType(types: !1557)
!1557 = !{null, !1558, !927}
!1558 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1381, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1559 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE8grow_podEmm", scope: !1381, file: !914, line: 80, type: !1560, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1560 = !DISubroutineType(types: !1561)
!1561 = !{null, !1558, !927, !927}
!1562 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE7isSmallEv", scope: !1381, file: !914, line: 86, type: !1563, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1563 = !DISubroutineType(types: !1564)
!1564 = !{!82, !1565}
!1565 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1566, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1566 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1381)
!1567 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE12resetToSmallEv", scope: !1381, file: !914, line: 91, type: !1568, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1568 = !DISubroutineType(types: !1569)
!1569 = !{null, !1558}
!1570 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE6setEndEPS4_", scope: !1381, file: !914, line: 95, type: !1571, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1571 = !DISubroutineType(types: !1572)
!1572 = !{null, !1558, !1573}
!1573 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1391, size: 64)
!1574 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE5beginEv", scope: !1381, file: !914, line: 112, type: !1575, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1575 = !DISubroutineType(types: !1576)
!1576 = !{!1380, !1558}
!1577 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE5beginEv", scope: !1381, file: !914, line: 113, type: !1578, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1578 = !DISubroutineType(types: !1579)
!1579 = !{!1580, !1565}
!1580 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !1381, file: !914, line: 101, baseType: !1581)
!1581 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1582, size: 64)
!1582 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1391)
!1583 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE3endEv", scope: !1381, file: !914, line: 114, type: !1575, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1584 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE3endEv", scope: !1381, file: !914, line: 115, type: !1578, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1585 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE12capacity_ptrEv", scope: !1381, file: !914, line: 117, type: !1575, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1586 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE12capacity_ptrEv", scope: !1381, file: !914, line: 118, type: !1578, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1587 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE6rbeginEv", scope: !1381, file: !914, line: 122, type: !1588, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1588 = !DISubroutineType(types: !1589)
!1589 = !{!1590, !1558}
!1590 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !1381, file: !914, line: 104, baseType: !1591)
!1591 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<clang::CodeGen::VBTablePath **>", scope: !408, file: !999, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPPN5clang7CodeGen11VBTablePathEE")
!1592 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE6rbeginEv", scope: !1381, file: !914, line: 123, type: !1593, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1593 = !DISubroutineType(types: !1594)
!1594 = !{!1595, !1565}
!1595 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !1381, file: !914, line: 103, baseType: !1596)
!1596 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<clang::CodeGen::VBTablePath *const *>", scope: !408, file: !999, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKPN5clang7CodeGen11VBTablePathEE")
!1597 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE4rendEv", scope: !1381, file: !914, line: 124, type: !1588, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1598 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE4rendEv", scope: !1381, file: !914, line: 125, type: !1593, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1599 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE4sizeEv", scope: !1381, file: !914, line: 127, type: !1600, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1600 = !DISubroutineType(types: !1601)
!1601 = !{!1010, !1565}
!1602 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE8max_sizeEv", scope: !1381, file: !914, line: 128, type: !1600, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1603 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE8capacityEv", scope: !1381, file: !914, line: 132, type: !1604, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1604 = !DISubroutineType(types: !1605)
!1605 = !{!927, !1565}
!1606 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE4dataEv", scope: !1381, file: !914, line: 135, type: !1607, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1607 = !DISubroutineType(types: !1608)
!1608 = !{!1609, !1558}
!1609 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1381, file: !914, line: 108, baseType: !1573)
!1610 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE4dataEv", scope: !1381, file: !914, line: 137, type: !1611, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1611 = !DISubroutineType(types: !1612)
!1612 = !{!1613, !1565}
!1613 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !1381, file: !914, line: 109, baseType: !1581)
!1614 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvEixEj", scope: !1381, file: !914, line: 139, type: !1615, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1615 = !DISubroutineType(types: !1616)
!1616 = !{!1617, !1558, !6}
!1617 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1381, file: !914, line: 106, baseType: !1618)
!1618 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1391, size: 64)
!1619 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvEixEj", scope: !1381, file: !914, line: 143, type: !1620, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1620 = !DISubroutineType(types: !1621)
!1621 = !{!1622, !1565, !6}
!1622 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1381, file: !914, line: 107, baseType: !1623)
!1623 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1582, size: 64)
!1624 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE5frontEv", scope: !1381, file: !914, line: 148, type: !1625, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1625 = !DISubroutineType(types: !1626)
!1626 = !{!1617, !1558}
!1627 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE5frontEv", scope: !1381, file: !914, line: 152, type: !1628, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1628 = !DISubroutineType(types: !1629)
!1629 = !{!1622, !1565}
!1630 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE4backEv", scope: !1381, file: !914, line: 157, type: !1625, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1631 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPN5clang7CodeGen11VBTablePathEvE4backEv", scope: !1381, file: !914, line: 161, type: !1628, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1632 = !{!1633, !1044}
!1633 = !DITemplateTypeParameter(name: "T", type: !1391)
!1634 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !1635, line: 374, baseType: !1636)
!1635 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h", directory: "", checksumkind: CSK_MD5, checksum: "ba305a1e10d49c66b3a70acbb63616a6")
!1636 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", scope: !408, file: !1637, line: 238, baseType: !249)
!1637 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8/bits/c++config.h", directory: "", checksumkind: CSK_MD5, checksum: "5ab2830680f5a52514c973f039a03c0a")
!1638 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1639, size: 64)
!1639 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1640)
!1640 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Tp_alloc_type", scope: !1641, file: !1635, line: 84, baseType: !1642)
!1641 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_base<clang::CodeGen::VBTableInfo, std::allocator<clang::CodeGen::VBTableInfo> >", scope: !408, file: !1635, line: 81, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt12_Vector_baseIN5clang7CodeGen11VBTableInfoESaIS2_EE")
!1642 = !DIDerivedType(tag: DW_TAG_typedef, name: "other", scope: !1644, file: !1643, line: 117, baseType: !1699)
!1643 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/alloc_traits.h", directory: "")
!1644 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "rebind<clang::CodeGen::VBTableInfo>", scope: !1645, file: !1643, line: 116, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1697, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIN5clang7CodeGen11VBTableInfoEES3_E6rebindIS3_EE")
!1645 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__alloc_traits<std::allocator<clang::CodeGen::VBTableInfo>, clang::CodeGen::VBTableInfo>", scope: !5, file: !1643, line: 50, size: 8, flags: DIFlagTypePassByValue, elements: !1646, templateParams: !1695, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIN5clang7CodeGen11VBTableInfoEES3_EE")
!1646 = !{!1647, !1679, !1684, !1688, !1691, !1692, !1693, !1694}
!1647 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1645, baseType: !1648, extraData: i32 0)
!1648 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "allocator_traits<std::allocator<clang::CodeGen::VBTableInfo> >", scope: !408, file: !1649, line: 384, size: 8, flags: DIFlagTypePassByValue, elements: !1650, templateParams: !1677, identifier: "_ZTSSt16allocator_traitsISaIN5clang7CodeGen11VBTableInfoEEE")
!1649 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/alloc_traits.h", directory: "", checksumkind: CSK_MD5, checksum: "f7f651aab55acaadfc53aa53979a817c")
!1650 = !{!1651, !1661, !1665, !1668, !1674}
!1651 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIN5clang7CodeGen11VBTableInfoEEE8allocateERS3_m", scope: !1648, file: !1649, line: 435, type: !1652, scopeLine: 435, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1652 = !DISubroutineType(types: !1653)
!1653 = !{!1654, !1656, !1660}
!1654 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1648, file: !1649, line: 392, baseType: !1655)
!1655 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1396, size: 64)
!1656 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1657, size: 64)
!1657 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !1648, file: !1649, line: 387, baseType: !1658)
!1658 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "allocator<clang::CodeGen::VBTableInfo>", scope: !408, file: !1659, line: 108, size: 8, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSaIN5clang7CodeGen11VBTableInfoEE")
!1659 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "9cafc7b584300736771313d46be845c3")
!1660 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !1649, line: 407, baseType: !1636)
!1661 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIN5clang7CodeGen11VBTableInfoEEE8allocateERS3_mPKv", scope: !1648, file: !1649, line: 449, type: !1662, scopeLine: 449, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1662 = !DISubroutineType(types: !1663)
!1663 = !{!1654, !1656, !1660, !1664}
!1664 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_void_pointer", file: !1649, line: 401, baseType: !117)
!1665 = !DISubprogram(name: "deallocate", linkageName: "_ZNSt16allocator_traitsISaIN5clang7CodeGen11VBTableInfoEEE10deallocateERS3_PS2_m", scope: !1648, file: !1649, line: 461, type: !1666, scopeLine: 461, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1666 = !DISubroutineType(types: !1667)
!1667 = !{null, !1656, !1654, !1660}
!1668 = !DISubprogram(name: "max_size", linkageName: "_ZNSt16allocator_traitsISaIN5clang7CodeGen11VBTableInfoEEE8max_sizeERKS3_", scope: !1648, file: !1649, line: 495, type: !1669, scopeLine: 495, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1669 = !DISubroutineType(types: !1670)
!1670 = !{!1671, !1672}
!1671 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1648, file: !1649, line: 407, baseType: !1636)
!1672 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1673, size: 64)
!1673 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1657)
!1674 = !DISubprogram(name: "select_on_container_copy_construction", linkageName: "_ZNSt16allocator_traitsISaIN5clang7CodeGen11VBTableInfoEEE37select_on_container_copy_constructionERKS3_", scope: !1648, file: !1649, line: 504, type: !1675, scopeLine: 504, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1675 = !DISubroutineType(types: !1676)
!1676 = !{!1657, !1672}
!1677 = !{!1678}
!1678 = !DITemplateTypeParameter(name: "_Alloc", type: !1658)
!1679 = !DISubprogram(name: "_S_select_on_copy", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIN5clang7CodeGen11VBTableInfoEES3_E17_S_select_on_copyERKS4_", scope: !1645, file: !1643, line: 94, type: !1680, scopeLine: 94, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1680 = !DISubroutineType(types: !1681)
!1681 = !{!1658, !1682}
!1682 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1683, size: 64)
!1683 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1658)
!1684 = !DISubprogram(name: "_S_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIN5clang7CodeGen11VBTableInfoEES3_E10_S_on_swapERS4_S6_", scope: !1645, file: !1643, line: 97, type: !1685, scopeLine: 97, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1685 = !DISubroutineType(types: !1686)
!1686 = !{null, !1687, !1687}
!1687 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1658, size: 64)
!1688 = !DISubprogram(name: "_S_propagate_on_copy_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIN5clang7CodeGen11VBTableInfoEES3_E27_S_propagate_on_copy_assignEv", scope: !1645, file: !1643, line: 100, type: !1689, scopeLine: 100, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1689 = !DISubroutineType(types: !1690)
!1690 = !{!82}
!1691 = !DISubprogram(name: "_S_propagate_on_move_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIN5clang7CodeGen11VBTableInfoEES3_E27_S_propagate_on_move_assignEv", scope: !1645, file: !1643, line: 103, type: !1689, scopeLine: 103, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1692 = !DISubprogram(name: "_S_propagate_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIN5clang7CodeGen11VBTableInfoEES3_E20_S_propagate_on_swapEv", scope: !1645, file: !1643, line: 106, type: !1689, scopeLine: 106, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1693 = !DISubprogram(name: "_S_always_equal", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIN5clang7CodeGen11VBTableInfoEES3_E15_S_always_equalEv", scope: !1645, file: !1643, line: 109, type: !1689, scopeLine: 109, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1694 = !DISubprogram(name: "_S_nothrow_move", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIN5clang7CodeGen11VBTableInfoEES3_E15_S_nothrow_moveEv", scope: !1645, file: !1643, line: 112, type: !1689, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1695 = !{!1678, !1696}
!1696 = !DITemplateTypeParameter(type: !1396)
!1697 = !{!1698}
!1698 = !DITemplateTypeParameter(name: "_Tp", type: !1396)
!1699 = !DIDerivedType(tag: DW_TAG_typedef, name: "rebind_alloc<clang::CodeGen::VBTableInfo>", scope: !1648, file: !1649, line: 422, baseType: !1658)
!1700 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1701, file: !1635, line: 369, baseType: !1702)
!1701 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<clang::CodeGen::VBTableInfo, std::allocator<clang::CodeGen::VBTableInfo> >", scope: !408, file: !1635, line: 339, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt6vectorIN5clang7CodeGen11VBTableInfoESaIS2_EE")
!1702 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<clang::CodeGen::VBTableInfo *, std::vector<clang::CodeGen::VBTableInfo, std::allocator<clang::CodeGen::VBTableInfo> > >", scope: !5, file: !999, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1703, templateParams: !1757, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPN5clang7CodeGen11VBTableInfoESt6vectorIS3_SaIS3_EEEE")
!1703 = !{!1704, !1705, !1709, !1714, !1726, !1731, !1735, !1738, !1739, !1740, !1746, !1749, !1752, !1753, !1754}
!1704 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !1702, file: !999, line: 767, baseType: !1655, size: 64, flags: DIFlagProtected)
!1705 = !DISubprogram(name: "__normal_iterator", scope: !1702, file: !999, line: 779, type: !1706, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1706 = !DISubroutineType(types: !1707)
!1707 = !{null, !1708}
!1708 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1702, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1709 = !DISubprogram(name: "__normal_iterator", scope: !1702, file: !999, line: 783, type: !1710, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1710 = !DISubroutineType(types: !1711)
!1711 = !{null, !1708, !1712}
!1712 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1713, size: 64)
!1713 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1655)
!1714 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPN5clang7CodeGen11VBTableInfoESt6vectorIS3_SaIS3_EEEdeEv", scope: !1702, file: !999, line: 796, type: !1715, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1715 = !DISubroutineType(types: !1716)
!1716 = !{!1717, !1724}
!1717 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1702, file: !999, line: 776, baseType: !1718)
!1718 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1720, file: !1719, line: 184, baseType: !1723)
!1719 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_iterator_base_types.h", directory: "")
!1720 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<clang::CodeGen::VBTableInfo *>", scope: !408, file: !1719, line: 178, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1721, identifier: "_ZTSSt15iterator_traitsIPN5clang7CodeGen11VBTableInfoEE")
!1721 = !{!1722}
!1722 = !DITemplateTypeParameter(name: "_Iterator", type: !1655)
!1723 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1396, size: 64)
!1724 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1725, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1725 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1702)
!1726 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPN5clang7CodeGen11VBTableInfoESt6vectorIS3_SaIS3_EEEptEv", scope: !1702, file: !999, line: 800, type: !1727, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1727 = !DISubroutineType(types: !1728)
!1728 = !{!1729, !1724}
!1729 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1702, file: !999, line: 777, baseType: !1730)
!1730 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1720, file: !1719, line: 183, baseType: !1655)
!1731 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPN5clang7CodeGen11VBTableInfoESt6vectorIS3_SaIS3_EEEppEv", scope: !1702, file: !999, line: 804, type: !1732, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1732 = !DISubroutineType(types: !1733)
!1733 = !{!1734, !1708}
!1734 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1702, size: 64)
!1735 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPN5clang7CodeGen11VBTableInfoESt6vectorIS3_SaIS3_EEEppEi", scope: !1702, file: !999, line: 811, type: !1736, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1736 = !DISubroutineType(types: !1737)
!1737 = !{!1702, !1708, !701}
!1738 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPN5clang7CodeGen11VBTableInfoESt6vectorIS3_SaIS3_EEEmmEv", scope: !1702, file: !999, line: 816, type: !1732, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1739 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPN5clang7CodeGen11VBTableInfoESt6vectorIS3_SaIS3_EEEmmEi", scope: !1702, file: !999, line: 823, type: !1736, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1740 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPN5clang7CodeGen11VBTableInfoESt6vectorIS3_SaIS3_EEEixEl", scope: !1702, file: !999, line: 828, type: !1741, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1741 = !DISubroutineType(types: !1742)
!1742 = !{!1717, !1724, !1743}
!1743 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1702, file: !999, line: 775, baseType: !1744)
!1744 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1720, file: !1719, line: 182, baseType: !1745)
!1745 = !DIDerivedType(tag: DW_TAG_typedef, name: "ptrdiff_t", scope: !408, file: !1637, line: 239, baseType: !58)
!1746 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPN5clang7CodeGen11VBTableInfoESt6vectorIS3_SaIS3_EEEpLEl", scope: !1702, file: !999, line: 832, type: !1747, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1747 = !DISubroutineType(types: !1748)
!1748 = !{!1734, !1708, !1743}
!1749 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPN5clang7CodeGen11VBTableInfoESt6vectorIS3_SaIS3_EEEplEl", scope: !1702, file: !999, line: 836, type: !1750, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1750 = !DISubroutineType(types: !1751)
!1751 = !{!1702, !1724, !1743}
!1752 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPN5clang7CodeGen11VBTableInfoESt6vectorIS3_SaIS3_EEEmIEl", scope: !1702, file: !999, line: 840, type: !1747, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1753 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPN5clang7CodeGen11VBTableInfoESt6vectorIS3_SaIS3_EEEmiEl", scope: !1702, file: !999, line: 844, type: !1750, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1754 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPN5clang7CodeGen11VBTableInfoESt6vectorIS3_SaIS3_EEE4baseEv", scope: !1702, file: !999, line: 848, type: !1755, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1755 = !DISubroutineType(types: !1756)
!1756 = !{!1712, !1724}
!1757 = !{!1722, !1758}
!1758 = !DITemplateTypeParameter(name: "_Container", type: !1701)
!1759 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "move_iterator<clang::CodeGen::VBTableInfo *>", scope: !408, file: !999, line: 1007, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1760, templateParams: !1721, identifier: "_ZTSSt13move_iteratorIPN5clang7CodeGen11VBTableInfoEE")
!1760 = !{!1761, !1762, !1766, !1770, !1775, !1785, !1789, !1793, !1796, !1797, !1798, !1802, !1805, !1806, !1807}
!1761 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !1759, file: !999, line: 1010, baseType: !1655, size: 64, flags: DIFlagProtected)
!1762 = !DISubprogram(name: "move_iterator", scope: !1759, file: !999, line: 1029, type: !1763, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1763 = !DISubroutineType(types: !1764)
!1764 = !{null, !1765}
!1765 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1759, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1766 = !DISubprogram(name: "move_iterator", scope: !1759, file: !999, line: 1033, type: !1767, scopeLine: 1033, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1767 = !DISubroutineType(types: !1768)
!1768 = !{null, !1765, !1769}
!1769 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator_type", scope: !1759, file: !999, line: 1016, baseType: !1655)
!1770 = !DISubprogram(name: "base", linkageName: "_ZNKSt13move_iteratorIPN5clang7CodeGen11VBTableInfoEE4baseEv", scope: !1759, file: !999, line: 1042, type: !1771, scopeLine: 1042, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1771 = !DISubroutineType(types: !1772)
!1772 = !{!1769, !1773}
!1773 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1774, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1774 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1759)
!1775 = !DISubprogram(name: "operator*", linkageName: "_ZNKSt13move_iteratorIPN5clang7CodeGen11VBTableInfoEEdeEv", scope: !1759, file: !999, line: 1046, type: !1776, scopeLine: 1046, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1776 = !DISubroutineType(types: !1777)
!1777 = !{!1778, !1773}
!1778 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1759, file: !999, line: 1026, baseType: !1779)
!1779 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1780, file: !821, line: 1928, baseType: !1783)
!1780 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, clang::CodeGen::VBTableInfo &&, clang::CodeGen::VBTableInfo &>", scope: !408, file: !821, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1781, identifier: "_ZTSSt11conditionalILb1EON5clang7CodeGen11VBTableInfoERS2_E")
!1781 = !{!825, !1782, !1784}
!1782 = !DITemplateTypeParameter(name: "_Iftrue", type: !1783)
!1783 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1396, size: 64)
!1784 = !DITemplateTypeParameter(name: "_Iffalse", type: !1723)
!1785 = !DISubprogram(name: "operator->", linkageName: "_ZNKSt13move_iteratorIPN5clang7CodeGen11VBTableInfoEEptEv", scope: !1759, file: !999, line: 1050, type: !1786, scopeLine: 1050, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1786 = !DISubroutineType(types: !1787)
!1787 = !{!1788, !1773}
!1788 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1759, file: !999, line: 1021, baseType: !1655)
!1789 = !DISubprogram(name: "operator++", linkageName: "_ZNSt13move_iteratorIPN5clang7CodeGen11VBTableInfoEEppEv", scope: !1759, file: !999, line: 1054, type: !1790, scopeLine: 1054, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1790 = !DISubroutineType(types: !1791)
!1791 = !{!1792, !1765}
!1792 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1759, size: 64)
!1793 = !DISubprogram(name: "operator++", linkageName: "_ZNSt13move_iteratorIPN5clang7CodeGen11VBTableInfoEEppEi", scope: !1759, file: !999, line: 1061, type: !1794, scopeLine: 1061, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1794 = !DISubroutineType(types: !1795)
!1795 = !{!1759, !1765, !701}
!1796 = !DISubprogram(name: "operator--", linkageName: "_ZNSt13move_iteratorIPN5clang7CodeGen11VBTableInfoEEmmEv", scope: !1759, file: !999, line: 1069, type: !1790, scopeLine: 1069, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1797 = !DISubprogram(name: "operator--", linkageName: "_ZNSt13move_iteratorIPN5clang7CodeGen11VBTableInfoEEmmEi", scope: !1759, file: !999, line: 1076, type: !1794, scopeLine: 1076, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1798 = !DISubprogram(name: "operator+", linkageName: "_ZNKSt13move_iteratorIPN5clang7CodeGen11VBTableInfoEEplEl", scope: !1759, file: !999, line: 1084, type: !1799, scopeLine: 1084, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1799 = !DISubroutineType(types: !1800)
!1800 = !{!1759, !1773, !1801}
!1801 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1759, file: !999, line: 1019, baseType: !1744)
!1802 = !DISubprogram(name: "operator+=", linkageName: "_ZNSt13move_iteratorIPN5clang7CodeGen11VBTableInfoEEpLEl", scope: !1759, file: !999, line: 1088, type: !1803, scopeLine: 1088, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1803 = !DISubroutineType(types: !1804)
!1804 = !{!1792, !1765, !1801}
!1805 = !DISubprogram(name: "operator-", linkageName: "_ZNKSt13move_iteratorIPN5clang7CodeGen11VBTableInfoEEmiEl", scope: !1759, file: !999, line: 1095, type: !1799, scopeLine: 1095, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1806 = !DISubprogram(name: "operator-=", linkageName: "_ZNSt13move_iteratorIPN5clang7CodeGen11VBTableInfoEEmIEl", scope: !1759, file: !999, line: 1099, type: !1803, scopeLine: 1099, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1807 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt13move_iteratorIPN5clang7CodeGen11VBTableInfoEEixEl", scope: !1759, file: !999, line: 1106, type: !1808, scopeLine: 1106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1808 = !DISubroutineType(types: !1809)
!1809 = !{!1778, !1773, !1801}
!1810 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1640, size: 64)
!1811 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !522, size: 64)
!1812 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1813, file: !914, line: 377, baseType: !1895)
!1813 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<clang::CodeGen::VBTablePath *>", scope: !13, file: !914, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1814, templateParams: !1894, identifier: "_ZTSN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEEE")
!1814 = !{!1815, !1834, !1840, !1843, !1846, !1847, !1848, !1851, !1852, !1855, !1859, !1862, !1863, !1867, !1870, !1874, !1877, !1880, !1883, !1887, !1891, !1892, !1893}
!1815 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1813, baseType: !1816, flags: DIFlagPublic, extraData: i32 0)
!1816 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<clang::CodeGen::VBTablePath *, true>", scope: !13, file: !914, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1817, templateParams: !1833, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseIPN5clang7CodeGen11VBTablePathELb1EEE")
!1817 = !{!1818, !1819, !1823, !1826, !1827, !1830}
!1818 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1816, baseType: !1381, flags: DIFlagPublic, extraData: i32 0)
!1819 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !1816, file: !914, line: 298, type: !1820, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1820 = !DISubroutineType(types: !1821)
!1821 = !{null, !1822, !927}
!1822 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1816, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1823 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPN5clang7CodeGen11VBTablePathELb1EE13destroy_rangeEPS4_S6_", scope: !1816, file: !914, line: 301, type: !1824, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1824 = !DISubroutineType(types: !1825)
!1825 = !{null, !1573, !1573}
!1826 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPN5clang7CodeGen11VBTablePathELb1EE4growEm", scope: !1816, file: !914, line: 346, type: !1820, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1827 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPN5clang7CodeGen11VBTablePathELb1EE9push_backERKS4_", scope: !1816, file: !914, line: 350, type: !1828, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1828 = !DISubroutineType(types: !1829)
!1829 = !{null, !1822, !1623}
!1830 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPN5clang7CodeGen11VBTablePathELb1EE8pop_backEv", scope: !1816, file: !914, line: 361, type: !1831, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1831 = !DISubroutineType(types: !1832)
!1832 = !{null, !1822}
!1833 = !{!1633, !1461}
!1834 = !DISubprogram(name: "SmallVectorImpl", scope: !1813, file: !914, line: 374, type: !1835, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1835 = !DISubroutineType(types: !1836)
!1836 = !{null, !1837, !1838}
!1837 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1813, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1838 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1839, size: 64)
!1839 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1813)
!1840 = !DISubprogram(name: "SmallVectorImpl", scope: !1813, file: !914, line: 381, type: !1841, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1841 = !DISubroutineType(types: !1842)
!1842 = !{null, !1837, !6}
!1843 = !DISubprogram(name: "~SmallVectorImpl", scope: !1813, file: !914, line: 386, type: !1844, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1844 = !DISubroutineType(types: !1845)
!1845 = !{null, !1837}
!1846 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEE5clearEv", scope: !1813, file: !914, line: 396, type: !1844, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1847 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEE6resizeEj", scope: !1813, file: !914, line: 401, type: !1841, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1848 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEE6resizeEjRKS4_", scope: !1813, file: !914, line: 413, type: !1849, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1849 = !DISubroutineType(types: !1850)
!1850 = !{null, !1837, !6, !1623}
!1851 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEE7reserveEj", scope: !1813, file: !914, line: 425, type: !1841, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1852 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEE12pop_back_valEv", scope: !1813, file: !914, line: 430, type: !1853, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1853 = !DISubroutineType(types: !1854)
!1854 = !{!1391, !1837}
!1855 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEE4swapERS5_", scope: !1813, file: !914, line: 440, type: !1856, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1856 = !DISubroutineType(types: !1857)
!1857 = !{null, !1837, !1858}
!1858 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1813, size: 64)
!1859 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEE6appendEmRKS4_", scope: !1813, file: !914, line: 460, type: !1860, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1860 = !DISubroutineType(types: !1861)
!1861 = !{null, !1837, !1812, !1623}
!1862 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEE6assignEjRKS4_", scope: !1813, file: !914, line: 470, type: !1849, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1863 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEE5eraseEPS4_", scope: !1813, file: !914, line: 478, type: !1864, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1864 = !DISubroutineType(types: !1865)
!1865 = !{!1866, !1837, !1866}
!1866 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1813, file: !914, line: 376, baseType: !1380)
!1867 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEE5eraseEPS4_S6_", scope: !1813, file: !914, line: 490, type: !1868, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1868 = !DISubroutineType(types: !1869)
!1869 = !{!1866, !1837, !1866, !1866}
!1870 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEE6insertEPS4_OS4_", scope: !1813, file: !914, line: 505, type: !1871, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1871 = !DISubroutineType(types: !1872)
!1872 = !{!1866, !1837, !1866, !1873}
!1873 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1391, size: 64)
!1874 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEE6insertEPS4_RKS4_", scope: !1813, file: !914, line: 537, type: !1875, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1875 = !DISubroutineType(types: !1876)
!1876 = !{!1866, !1837, !1866, !1623}
!1877 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEE6insertEPS4_mRKS4_", scope: !1813, file: !914, line: 568, type: !1878, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1878 = !DISubroutineType(types: !1879)
!1879 = !{!1866, !1837, !1866, !1812, !1623}
!1880 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEEaSERKS5_", scope: !1813, file: !914, line: 674, type: !1881, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1881 = !DISubroutineType(types: !1882)
!1882 = !{!1858, !1837, !1838}
!1883 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEEaSEOS5_", scope: !1813, file: !914, line: 677, type: !1884, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1884 = !DISubroutineType(types: !1885)
!1885 = !{!1858, !1837, !1886}
!1886 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1813, size: 64)
!1887 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEEeqERKS5_", scope: !1813, file: !914, line: 680, type: !1888, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1888 = !DISubroutineType(types: !1889)
!1889 = !{!82, !1890, !1838}
!1890 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1839, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1891 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEEneERKS5_", scope: !1813, file: !914, line: 684, type: !1888, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1892 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEEltERKS5_", scope: !1813, file: !914, line: 688, type: !1888, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1893 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplIPN5clang7CodeGen11VBTablePathEE8set_sizeEj", scope: !1813, file: !914, line: 702, type: !1841, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1894 = !{!1633}
!1895 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1381, file: !914, line: 97, baseType: !927)
!1896 = !DIDerivedType(tag: DW_TAG_typedef, name: "_DistanceType", scope: !1898, file: !1897, line: 249, baseType: !1930)
!1897 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_heap.h", directory: "", checksumkind: CSK_MD5, checksum: "14882d5d8b49113d741f2e45566d69ea")
!1898 = distinct !DISubprogram(name: "__pop_heap<clang::CodeGen::VBTablePath **, __gnu_cxx::__ops::_Iter_comp_iter<bool (*)(clang::CodeGen::VBTablePath *, clang::CodeGen::VBTablePath *)> >", linkageName: "_ZSt10__pop_heapIPPN5clang7CodeGen11VBTablePathEN9__gnu_cxx5__ops15_Iter_comp_iterIPFbS3_S3_EEEEvT_SB_SB_RT0_", scope: !408, file: !1897, line: 243, type: !1899, scopeLine: 245, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !1927, retainedNodes: !1916)
!1899 = !DISubroutineType(types: !1900)
!1900 = !{null, !1573, !1573, !1573, !1901}
!1901 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1902, size: 64)
!1902 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Iter_comp_iter<bool (*)(clang::CodeGen::VBTablePath *, clang::CodeGen::VBTablePath *)>", scope: !1904, file: !1903, line: 130, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1905, templateParams: !1914, identifier: "_ZTSN9__gnu_cxx5__ops15_Iter_comp_iterIPFbPN5clang7CodeGen11VBTablePathES5_EEE")
!1903 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/predefined_ops.h", directory: "", checksumkind: CSK_MD5, checksum: "c4488885b044d9477796f6d04761c9e8")
!1904 = !DINamespace(name: "__ops", scope: !5)
!1905 = !{!1906, !1910}
!1906 = !DIDerivedType(tag: DW_TAG_member, name: "_M_comp", scope: !1902, file: !1903, line: 132, baseType: !1907, size: 64)
!1907 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1908, size: 64)
!1908 = !DISubroutineType(types: !1909)
!1909 = !{!82, !1391, !1391}
!1910 = !DISubprogram(name: "_Iter_comp_iter", scope: !1902, file: !1903, line: 135, type: !1911, scopeLine: 135, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1911 = !DISubroutineType(types: !1912)
!1912 = !{null, !1913, !1907}
!1913 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1902, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1914 = !{!1915}
!1915 = !DITemplateTypeParameter(name: "_Compare", type: !1907)
!1916 = !{!1917, !1918, !1919, !1920, !1921}
!1917 = !DILocalVariable(name: "__first", arg: 1, scope: !1898, file: !1897, line: 243, type: !1573)
!1918 = !DILocalVariable(name: "__last", arg: 2, scope: !1898, file: !1897, line: 243, type: !1573)
!1919 = !DILocalVariable(name: "__result", arg: 3, scope: !1898, file: !1897, line: 244, type: !1573)
!1920 = !DILocalVariable(name: "__comp", arg: 4, scope: !1898, file: !1897, line: 244, type: !1901)
!1921 = !DILocalVariable(name: "__value", scope: !1898, file: !1897, line: 251, type: !1922)
!1922 = !DIDerivedType(tag: DW_TAG_typedef, name: "_ValueType", scope: !1898, file: !1897, line: 247, baseType: !1923)
!1923 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1924, file: !1719, line: 181, baseType: !1391)
!1924 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<clang::CodeGen::VBTablePath **>", scope: !408, file: !1719, line: 178, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1925, identifier: "_ZTSSt15iterator_traitsIPPN5clang7CodeGen11VBTablePathEE")
!1925 = !{!1926}
!1926 = !DITemplateTypeParameter(name: "_Iterator", type: !1573)
!1927 = !{!1928, !1929}
!1928 = !DITemplateTypeParameter(name: "_RandomAccessIterator", type: !1573)
!1929 = !DITemplateTypeParameter(name: "_Compare", type: !1902)
!1930 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1924, file: !1719, line: 182, baseType: !1745)
!1931 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Val_comp_iter<bool (*)(clang::CodeGen::VBTablePath *, clang::CodeGen::VBTablePath *)>", scope: !1904, file: !1903, line: 191, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1932, templateParams: !1914, identifier: "_ZTSN9__gnu_cxx5__ops14_Val_comp_iterIPFbPN5clang7CodeGen11VBTablePathES5_EEE")
!1932 = !{!1933, !1934, !1938, !1943}
!1933 = !DIDerivedType(tag: DW_TAG_member, name: "_M_comp", scope: !1931, file: !1903, line: 193, baseType: !1907, size: 64)
!1934 = !DISubprogram(name: "_Val_comp_iter", scope: !1931, file: !1903, line: 196, type: !1935, scopeLine: 196, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1935 = !DISubroutineType(types: !1936)
!1936 = !{null, !1937, !1907}
!1937 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1931, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1938 = !DISubprogram(name: "_Val_comp_iter", scope: !1931, file: !1903, line: 201, type: !1939, scopeLine: 201, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1939 = !DISubroutineType(types: !1940)
!1940 = !{null, !1937, !1941}
!1941 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1942, size: 64)
!1942 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1902)
!1943 = !DISubprogram(name: "_Val_comp_iter", scope: !1931, file: !1903, line: 207, type: !1944, scopeLine: 207, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1944 = !DISubroutineType(types: !1945)
!1945 = !{null, !1937, !1946}
!1946 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1902, size: 64)
!1947 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !1948, file: !1261, line: 185, baseType: !1951)
!1948 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty<llvm::PointerType, llvm::PointerType *>", scope: !13, file: !1261, line: 183, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1949, identifier: "_ZTSN4llvm10cast_rettyINS_11PointerTypeEPS1_EE")
!1949 = !{!1264, !1950}
!1950 = !DITemplateTypeParameter(name: "From", type: !1275)
!1951 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !1952, file: !1261, line: 179, baseType: !1955)
!1952 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_wrap<llvm::PointerType, llvm::PointerType *, llvm::PointerType *>", scope: !13, file: !1261, line: 177, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1953, identifier: "_ZTSN4llvm15cast_retty_wrapINS_11PointerTypeEPS1_S2_EE")
!1953 = !{!1264, !1950, !1954}
!1954 = !DITemplateTypeParameter(name: "SimpleFrom", type: !1275)
!1955 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !1956, file: !1261, line: 156, baseType: !1275)
!1956 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_impl<llvm::PointerType, llvm::PointerType *>", scope: !13, file: !1261, line: 155, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !1949, identifier: "_ZTSN4llvm15cast_retty_implINS_11PointerTypeEPS1_EE")
!1957 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "VBTableBuilder", scope: !38, file: !1397, line: 93, size: 704, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1958, identifier: "_ZTSN5clang7CodeGen14VBTableBuilderE")
!1958 = !{!1959, !1960, !1961, !1964, !1965, !1969, !1974, !1977, !2051, !2090, !2093}
!1959 = !DIDerivedType(tag: DW_TAG_member, name: "CGM", scope: !1957, file: !1397, line: 116, baseType: !1434, size: 64)
!1960 = !DIDerivedType(tag: DW_TAG_member, name: "MostDerived", scope: !1957, file: !1397, line: 118, baseType: !520, size: 64, offset: 64)
!1961 = !DIDerivedType(tag: DW_TAG_member, name: "DerivedLayout", scope: !1957, file: !1397, line: 121, baseType: !1962, size: 64, offset: 128)
!1962 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1963, size: 64)
!1963 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !788)
!1964 = !DIDerivedType(tag: DW_TAG_member, name: "VBasesSeen", scope: !1957, file: !1397, line: 124, baseType: !556, size: 512, offset: 192)
!1965 = !DISubprogram(name: "VBTableBuilder", scope: !1957, file: !1397, line: 95, type: !1966, scopeLine: 95, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1966 = !DISubroutineType(types: !1967)
!1967 = !{null, !1968, !1434, !520}
!1968 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1957, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1969 = !DISubprogram(name: "enumerateVBTables", linkageName: "_ZN5clang7CodeGen14VBTableBuilder17enumerateVBTablesERSt6vectorINS0_11VBTableInfoESaIS3_EE", scope: !1957, file: !1397, line: 97, type: !1970, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1970 = !DISubroutineType(types: !1971)
!1971 = !{null, !1968, !1972}
!1972 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1973, size: 64)
!1973 = !DIDerivedType(tag: DW_TAG_typedef, name: "VBTableVector", scope: !38, file: !1397, line: 52, baseType: !1701)
!1974 = !DISubprogram(name: "hasVBPtr", linkageName: "_ZN5clang7CodeGen14VBTableBuilder8hasVBPtrEPKNS_13CXXRecordDeclE", scope: !1957, file: !1397, line: 100, type: !1975, scopeLine: 100, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1975 = !DISubroutineType(types: !1976)
!1976 = !{!82, !1968, !520}
!1977 = !DISubprogram(name: "getAddrOfVBTable", linkageName: "_ZN5clang7CodeGen14VBTableBuilder16getAddrOfVBTableEPKNS_13CXXRecordDeclEN4llvm8ArrayRefIS4_EE", scope: !1957, file: !1397, line: 102, type: !1978, scopeLine: 102, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1978 = !DISubroutineType(types: !1979)
!1979 = !{!1422, !1968, !520, !1980}
!1980 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ArrayRef<const clang::CXXRecordDecl *>", scope: !13, file: !1981, line: 31, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1982, templateParams: !527, identifier: "_ZTSN4llvm8ArrayRefIPKN5clang13CXXRecordDeclEEE")
!1981 = !DIFile(filename: "llvm34/include/llvm/ADT/ArrayRef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "6317ba9f99cd1980a6299fb308b36f31")
!1982 = !{!1983, !1984, !1986, !1990, !1993, !1996, !1999, !2002, !2009, !2015, !2016, !2020, !2021, !2024, !2027, !2030, !2033, !2034, !2037, !2040, !2043, !2046, !2050}
!1983 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !1980, file: !1981, line: 41, baseType: !1023, size: 64)
!1984 = !DIDerivedType(tag: DW_TAG_member, name: "Length", scope: !1980, file: !1981, line: 44, baseType: !1985, size: 64, offset: 64)
!1985 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !1981, line: 35, baseType: !927)
!1986 = !DISubprogram(name: "ArrayRef", scope: !1980, file: !1981, line: 51, type: !1987, scopeLine: 51, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1987 = !DISubroutineType(types: !1988)
!1988 = !{null, !1989}
!1989 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1980, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1990 = !DISubprogram(name: "ArrayRef", scope: !1980, file: !1981, line: 54, type: !1991, scopeLine: 54, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1991 = !DISubroutineType(types: !1992)
!1992 = !{null, !1989, !11}
!1993 = !DISubprogram(name: "ArrayRef", scope: !1980, file: !1981, line: 57, type: !1994, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1994 = !DISubroutineType(types: !1995)
!1995 = !{null, !1989, !1034}
!1996 = !DISubprogram(name: "ArrayRef", scope: !1980, file: !1981, line: 61, type: !1997, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1997 = !DISubroutineType(types: !1998)
!1998 = !{null, !1989, !1023, !927}
!1999 = !DISubprogram(name: "ArrayRef", scope: !1980, file: !1981, line: 65, type: !2000, scopeLine: 65, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2000 = !DISubroutineType(types: !2001)
!2001 = !{null, !1989, !1023, !1023}
!2002 = !DISubprogram(name: "ArrayRef", scope: !1980, file: !1981, line: 88, type: !2003, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2003 = !DISubroutineType(types: !2004)
!2004 = !{null, !1989, !2005}
!2005 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2006, size: 64)
!2006 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2007)
!2007 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<const clang::CXXRecordDecl *>", scope: !408, file: !2008, line: 47, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listIPKN5clang13CXXRecordDeclEE")
!2008 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/initializer_list", directory: "")
!2009 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEE5beginEv", scope: !1980, file: !1981, line: 97, type: !2010, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2010 = !DISubroutineType(types: !2011)
!2011 = !{!2012, !2013}
!2012 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1980, file: !1981, line: 33, baseType: !1023)
!2013 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2014, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2014 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1980)
!2015 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEE3endEv", scope: !1980, file: !1981, line: 98, type: !2010, scopeLine: 98, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2016 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEE6rbeginEv", scope: !1980, file: !1981, line: 100, type: !2017, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2017 = !DISubroutineType(types: !2018)
!2018 = !{!2019, !2013}
!2019 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !1980, file: !1981, line: 37, baseType: !1004)
!2020 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEE4rendEv", scope: !1980, file: !1981, line: 101, type: !2017, scopeLine: 101, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2021 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEE5emptyEv", scope: !1980, file: !1981, line: 104, type: !2022, scopeLine: 104, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2022 = !DISubroutineType(types: !2023)
!2023 = !{!82, !2013}
!2024 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEE4dataEv", scope: !1980, file: !1981, line: 106, type: !2025, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2025 = !DISubroutineType(types: !2026)
!2026 = !{!1023, !2013}
!2027 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEE4sizeEv", scope: !1980, file: !1981, line: 109, type: !2028, scopeLine: 109, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2028 = !DISubroutineType(types: !2029)
!2029 = !{!927, !2013}
!2030 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEE5frontEv", scope: !1980, file: !1981, line: 112, type: !2031, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2031 = !DISubroutineType(types: !2032)
!2032 = !{!1034, !2013}
!2033 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEE4backEv", scope: !1980, file: !1981, line: 118, type: !2031, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2034 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEE6equalsES5_", scope: !1980, file: !1981, line: 124, type: !2035, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2035 = !DISubroutineType(types: !2036)
!2036 = !{!82, !2013, !1980}
!2037 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEE5sliceEj", scope: !1980, file: !1981, line: 134, type: !2038, scopeLine: 134, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2038 = !DISubroutineType(types: !2039)
!2039 = !{!1980, !2013, !6}
!2040 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEE5sliceEjj", scope: !1980, file: !1981, line: 141, type: !2041, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2041 = !DISubroutineType(types: !2042)
!2042 = !{!1980, !2013, !6, !6}
!2043 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEEixEm", scope: !1980, file: !1981, line: 149, type: !2044, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2044 = !DISubroutineType(types: !2045)
!2045 = !{!1034, !2013, !927}
!2046 = !DISubprogram(name: "vec", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEE3vecEv", scope: !1980, file: !1981, line: 157, type: !2047, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2047 = !DISubroutineType(types: !2048)
!2048 = !{!2049, !2013}
!2049 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<const clang::CXXRecordDecl *, std::allocator<const clang::CXXRecordDecl *> >", scope: !408, file: !1635, line: 339, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt6vectorIPKN5clang13CXXRecordDeclESaIS3_EE")
!2050 = !DISubprogram(name: "operator vector", linkageName: "_ZNK4llvm8ArrayRefIPKN5clang13CXXRecordDeclEEcvSt6vectorIS4_SaIS4_EEEv", scope: !1980, file: !1981, line: 164, type: !2047, scopeLine: 164, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2051 = !DISubprogram(name: "findUnambiguousPaths", linkageName: "_ZN5clang7CodeGen14VBTableBuilder20findUnambiguousPathsEPKNS_13CXXRecordDeclENS_13BaseSubobjectERN4llvm11SmallVectorIPNS0_11VBTablePathELj6EEE", scope: !1957, file: !1397, line: 107, type: !2052, scopeLine: 107, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2052 = !DISubroutineType(types: !2053)
!2053 = !{null, !1968, !520, !1401, !2054}
!2054 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2055, size: 64)
!2055 = !DIDerivedType(tag: DW_TAG_typedef, name: "VBTablePathVector", scope: !38, file: !1397, line: 56, baseType: !2056)
!2056 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<clang::CodeGen::VBTablePath *, 6U>", scope: !13, file: !914, line: 880, size: 576, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2057, templateParams: !2066, identifier: "_ZTSN4llvm11SmallVectorIPN5clang7CodeGen11VBTablePathELj6EEE")
!2057 = !{!2058, !2059, !2068, !2072, !2075, !2080, !2083, !2087}
!2058 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2056, baseType: !1813, flags: DIFlagPublic, extraData: i32 0)
!2059 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !2056, file: !914, line: 882, baseType: !2060, size: 320, offset: 256)
!2060 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<clang::CodeGen::VBTablePath *, 6U>", scope: !13, file: !914, line: 865, size: 320, flags: DIFlagTypePassByValue, elements: !2061, templateParams: !2066, identifier: "_ZTSN4llvm18SmallVectorStorageIPN5clang7CodeGen11VBTablePathELj6EEE")
!2061 = !{!2062}
!2062 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !2060, file: !914, line: 866, baseType: !2063, size: 320)
!2063 = !DICompositeType(tag: DW_TAG_array_type, baseType: !1385, size: 320, elements: !2064)
!2064 = !{!2065}
!2065 = !DISubrange(count: 5)
!2066 = !{!1633, !2067}
!2067 = !DITemplateValueParameter(name: "N", type: !6, value: i32 6)
!2068 = !DISubprogram(name: "SmallVector", scope: !2056, file: !914, line: 884, type: !2069, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2069 = !DISubroutineType(types: !2070)
!2070 = !{null, !2071}
!2071 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2056, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2072 = !DISubprogram(name: "SmallVector", scope: !2056, file: !914, line: 887, type: !2073, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2073 = !DISubroutineType(types: !2074)
!2074 = !{null, !2071, !6, !1623}
!2075 = !DISubprogram(name: "SmallVector", scope: !2056, file: !914, line: 897, type: !2076, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2076 = !DISubroutineType(types: !2077)
!2077 = !{null, !2071, !2078}
!2078 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2079, size: 64)
!2079 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2056)
!2080 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIPN5clang7CodeGen11VBTablePathELj6EEaSERKS5_", scope: !2056, file: !914, line: 902, type: !2081, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2081 = !DISubroutineType(types: !2082)
!2082 = !{!2078, !2071, !2078}
!2083 = !DISubprogram(name: "SmallVector", scope: !2056, file: !914, line: 908, type: !2084, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2084 = !DISubroutineType(types: !2085)
!2085 = !{null, !2071, !2086}
!2086 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2056, size: 64)
!2087 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIPN5clang7CodeGen11VBTablePathELj6EEaSEOS5_", scope: !2056, file: !914, line: 913, type: !2088, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2088 = !DISubroutineType(types: !2089)
!2089 = !{!2078, !2071, !2086}
!2090 = !DISubprogram(name: "extendPath", linkageName: "_ZN5clang7CodeGen14VBTableBuilder10extendPathEPNS0_11VBTablePathEb", scope: !1957, file: !1397, line: 111, type: !2091, scopeLine: 111, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2091 = !DISubroutineType(types: !2092)
!2092 = !{null, !1968, !1391, !82}
!2093 = !DISubprogram(name: "rebucketPaths", linkageName: "_ZN5clang7CodeGen14VBTableBuilder13rebucketPathsERN4llvm11SmallVectorIPNS0_11VBTablePathELj6EEEmb", scope: !1957, file: !1397, line: 113, type: !2094, scopeLine: 113, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2094 = !DISubroutineType(types: !2095)
!2095 = !{!82, !1968, !2054, !927, !82}
!2096 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "IsPT2", scope: !66, file: !67, line: 90, size: 8, flags: DIFlagTypePassByValue, elements: !2097, identifier: "_ZTSN4llvm12PointerUnionIPKN5clang4TypeEPKNS1_8ExtQualsEE5IsPT2E")
!2097 = !{!2098}
!2098 = !DIDerivedType(tag: DW_TAG_member, name: "Num", scope: !2096, file: !67, line: 91, baseType: !2099, flags: DIFlagStaticMember, extraData: i32 1)
!2099 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !701)
!2100 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringRef", scope: !13, file: !2101, line: 41, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2102, identifier: "_ZTSN4llvm9StringRefE")
!2101 = !DIFile(filename: "llvm34/include/llvm/ADT/StringRef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "5c2e300880041c873457392c89335431")
!2102 = !{!2103, !2105, !2106, !2107, !2110, !2111, !2114, !2118, !2121, !2124, !2129, !2135, !2136, !2139, !2142, !2145, !2148, !2149, !2152, !2153, !2156, !2157, !2158, !2161, !2164, !2167, !2168, !2169, !2170, !2171, !2172, !2175, !2178, !2179, !2182, !2183, !2184, !2185, !2186, !2187, !2188, !2189, !2190, !2193, !2194, !2200, !2201, !2202, !2205, !2208, !2209, !2210, !2268, !2271, !2276, !2277, !2280, !2281}
!2103 = !DIDerivedType(tag: DW_TAG_member, name: "npos", scope: !2100, file: !2101, line: 45, baseType: !2104, flags: DIFlagPublic | DIFlagStaticMember, extraData: i64 -1)
!2104 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !927)
!2105 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !2100, file: !2101, line: 50, baseType: !456, size: 64)
!2106 = !DIDerivedType(tag: DW_TAG_member, name: "Length", scope: !2100, file: !2101, line: 53, baseType: !927, size: 64, offset: 64)
!2107 = !DISubprogram(name: "min", linkageName: "_ZN4llvm9StringRef3minEmm", scope: !2100, file: !2101, line: 58, type: !2108, scopeLine: 58, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2108 = !DISubroutineType(types: !2109)
!2109 = !{!927, !927, !927}
!2110 = !DISubprogram(name: "max", linkageName: "_ZN4llvm9StringRef3maxEmm", scope: !2100, file: !2101, line: 59, type: !2108, scopeLine: 59, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2111 = !DISubprogram(name: "compareMemory", linkageName: "_ZN4llvm9StringRef13compareMemoryEPKcS2_m", scope: !2100, file: !2101, line: 63, type: !2112, scopeLine: 63, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2112 = !DISubroutineType(types: !2113)
!2113 = !{!701, !456, !456, !927}
!2114 = !DISubprogram(name: "StringRef", scope: !2100, file: !2101, line: 73, type: !2115, scopeLine: 73, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2115 = !DISubroutineType(types: !2116)
!2116 = !{null, !2117}
!2117 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2100, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2118 = !DISubprogram(name: "StringRef", scope: !2100, file: !2101, line: 76, type: !2119, scopeLine: 76, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2119 = !DISubroutineType(types: !2120)
!2120 = !{null, !2117, !456}
!2121 = !DISubprogram(name: "StringRef", scope: !2100, file: !2101, line: 83, type: !2122, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2122 = !DISubroutineType(types: !2123)
!2123 = !{null, !2117, !456, !927}
!2124 = !DISubprogram(name: "StringRef", scope: !2100, file: !2101, line: 90, type: !2125, scopeLine: 90, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2125 = !DISubroutineType(types: !2126)
!2126 = !{null, !2117, !2127}
!2127 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2128, size: 64)
!2128 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !405)
!2129 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm9StringRef5beginEv", scope: !2100, file: !2101, line: 97, type: !2130, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2130 = !DISubroutineType(types: !2131)
!2131 = !{!2132, !2133}
!2132 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2100, file: !2101, line: 43, baseType: !456)
!2133 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2134, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2134 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2100)
!2135 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm9StringRef3endEv", scope: !2100, file: !2101, line: 99, type: !2130, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2136 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm9StringRef4dataEv", scope: !2100, file: !2101, line: 107, type: !2137, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2137 = !DISubroutineType(types: !2138)
!2138 = !{!456, !2133}
!2139 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm9StringRef5emptyEv", scope: !2100, file: !2101, line: 110, type: !2140, scopeLine: 110, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2140 = !DISubroutineType(types: !2141)
!2141 = !{!82, !2133}
!2142 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm9StringRef4sizeEv", scope: !2100, file: !2101, line: 113, type: !2143, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2143 = !DISubroutineType(types: !2144)
!2144 = !{!927, !2133}
!2145 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm9StringRef5frontEv", scope: !2100, file: !2101, line: 116, type: !2146, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2146 = !DISubroutineType(types: !2147)
!2147 = !{!458, !2133}
!2148 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm9StringRef4backEv", scope: !2100, file: !2101, line: 122, type: !2146, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2149 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm9StringRef6equalsES0_", scope: !2100, file: !2101, line: 129, type: !2150, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2150 = !DISubroutineType(types: !2151)
!2151 = !{!82, !2133, !2100}
!2152 = !DISubprogram(name: "equals_lower", linkageName: "_ZNK4llvm9StringRef12equals_lowerES0_", scope: !2100, file: !2101, line: 135, type: !2150, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2153 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm9StringRef7compareES0_", scope: !2100, file: !2101, line: 141, type: !2154, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2154 = !DISubroutineType(types: !2155)
!2155 = !{!701, !2133, !2100}
!2156 = !DISubprogram(name: "compare_lower", linkageName: "_ZNK4llvm9StringRef13compare_lowerES0_", scope: !2100, file: !2101, line: 153, type: !2154, scopeLine: 153, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2157 = !DISubprogram(name: "compare_numeric", linkageName: "_ZNK4llvm9StringRef15compare_numericES0_", scope: !2100, file: !2101, line: 157, type: !2154, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2158 = !DISubprogram(name: "edit_distance", linkageName: "_ZNK4llvm9StringRef13edit_distanceES0_bj", scope: !2100, file: !2101, line: 177, type: !2159, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2159 = !DISubroutineType(types: !2160)
!2160 = !{!6, !2133, !2100, !82, !6}
!2161 = !DISubprogram(name: "str", linkageName: "_ZNK4llvm9StringRef3strB5cxx11Ev", scope: !2100, file: !2101, line: 181, type: !2162, scopeLine: 181, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2162 = !DISubroutineType(types: !2163)
!2163 = !{!405, !2133}
!2164 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm9StringRefixEm", scope: !2100, file: !2101, line: 190, type: !2165, scopeLine: 190, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2165 = !DISubroutineType(types: !2166)
!2166 = !{!458, !2133, !927}
!2167 = !DISubprogram(name: "operator basic_string", linkageName: "_ZNK4llvm9StringRefcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv", scope: !2100, file: !2101, line: 199, type: !2162, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2168 = !DISubprogram(name: "startswith", linkageName: "_ZNK4llvm9StringRef10startswithES0_", scope: !2100, file: !2101, line: 208, type: !2150, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2169 = !DISubprogram(name: "startswith_lower", linkageName: "_ZNK4llvm9StringRef16startswith_lowerES0_", scope: !2100, file: !2101, line: 214, type: !2150, scopeLine: 214, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2170 = !DISubprogram(name: "endswith", linkageName: "_ZNK4llvm9StringRef8endswithES0_", scope: !2100, file: !2101, line: 217, type: !2150, scopeLine: 217, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2171 = !DISubprogram(name: "endswith_lower", linkageName: "_ZNK4llvm9StringRef14endswith_lowerES0_", scope: !2100, file: !2101, line: 223, type: !2150, scopeLine: 223, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2172 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm9StringRef4findEcm", scope: !2100, file: !2101, line: 233, type: !2173, scopeLine: 233, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2173 = !DISubroutineType(types: !2174)
!2174 = !{!927, !2133, !458, !927}
!2175 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm9StringRef4findES0_m", scope: !2100, file: !2101, line: 244, type: !2176, scopeLine: 244, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2176 = !DISubroutineType(types: !2177)
!2177 = !{!927, !2133, !2100, !927}
!2178 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm9StringRef5rfindEcm", scope: !2100, file: !2101, line: 250, type: !2173, scopeLine: 250, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2179 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm9StringRef5rfindES0_", scope: !2100, file: !2101, line: 265, type: !2180, scopeLine: 265, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2180 = !DISubroutineType(types: !2181)
!2181 = !{!927, !2133, !2100}
!2182 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm9StringRef13find_first_ofEcm", scope: !2100, file: !2101, line: 269, type: !2173, scopeLine: 269, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2183 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm9StringRef13find_first_ofES0_m", scope: !2100, file: !2101, line: 277, type: !2176, scopeLine: 277, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2184 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm9StringRef17find_first_not_ofEcm", scope: !2100, file: !2101, line: 281, type: !2173, scopeLine: 281, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2185 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm9StringRef17find_first_not_ofES0_m", scope: !2100, file: !2101, line: 287, type: !2176, scopeLine: 287, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2186 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm9StringRef12find_last_ofEcm", scope: !2100, file: !2101, line: 291, type: !2173, scopeLine: 291, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2187 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm9StringRef12find_last_ofES0_m", scope: !2100, file: !2101, line: 299, type: !2176, scopeLine: 299, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2188 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNK4llvm9StringRef16find_last_not_ofEcm", scope: !2100, file: !2101, line: 303, type: !2173, scopeLine: 303, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2189 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNK4llvm9StringRef16find_last_not_ofES0_m", scope: !2100, file: !2101, line: 309, type: !2176, scopeLine: 309, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2190 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9StringRef5countEc", scope: !2100, file: !2101, line: 316, type: !2191, scopeLine: 316, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2191 = !DISubroutineType(types: !2192)
!2192 = !{!927, !2133, !458}
!2193 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9StringRef5countES0_", scope: !2100, file: !2101, line: 326, type: !2180, scopeLine: 326, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2194 = !DISubprogram(name: "getAsInteger", linkageName: "_ZNK4llvm9StringRef12getAsIntegerEjRNS_5APIntE", scope: !2100, file: !2101, line: 367, type: !2195, scopeLine: 367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2195 = !DISubroutineType(types: !2196)
!2196 = !{!82, !2133, !6, !2197}
!2197 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2198, size: 64)
!2198 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "APInt", scope: !13, file: !2199, line: 75, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm5APIntE")
!2199 = !DIFile(filename: "llvm34/include/llvm/ADT/APInt.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "2db0cee52675cf90af287a88ac0514bc")
!2200 = !DISubprogram(name: "lower", linkageName: "_ZNK4llvm9StringRef5lowerB5cxx11Ev", scope: !2100, file: !2101, line: 374, type: !2162, scopeLine: 374, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2201 = !DISubprogram(name: "upper", linkageName: "_ZNK4llvm9StringRef5upperB5cxx11Ev", scope: !2100, file: !2101, line: 377, type: !2162, scopeLine: 377, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2202 = !DISubprogram(name: "substr", linkageName: "_ZNK4llvm9StringRef6substrEmm", scope: !2100, file: !2101, line: 392, type: !2203, scopeLine: 392, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2203 = !DISubroutineType(types: !2204)
!2204 = !{!2100, !2133, !927, !927}
!2205 = !DISubprogram(name: "drop_front", linkageName: "_ZNK4llvm9StringRef10drop_frontEm", scope: !2100, file: !2101, line: 399, type: !2206, scopeLine: 399, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2206 = !DISubroutineType(types: !2207)
!2207 = !{!2100, !2133, !927}
!2208 = !DISubprogram(name: "drop_back", linkageName: "_ZNK4llvm9StringRef9drop_backEm", scope: !2100, file: !2101, line: 406, type: !2206, scopeLine: 406, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2209 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm9StringRef5sliceEmm", scope: !2100, file: !2101, line: 421, type: !2203, scopeLine: 421, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2210 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitEc", scope: !2100, file: !2101, line: 437, type: !2211, scopeLine: 437, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2211 = !DISubroutineType(types: !2212)
!2212 = !{!2213, !2133, !458}
!2213 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::StringRef, llvm::StringRef>", scope: !408, file: !764, line: 208, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2214, templateParams: !2265, identifier: "_ZTSSt4pairIN4llvm9StringRefES1_E")
!2214 = !{!2215, !2235, !2236, !2237, !2243, !2247, !2255, !2262}
!2215 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2213, baseType: !2216, flags: DIFlagPrivate, extraData: i32 0)
!2216 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::StringRef, llvm::StringRef>", scope: !408, file: !764, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !2217, templateParams: !2232, identifier: "_ZTSSt11__pair_baseIN4llvm9StringRefES1_E")
!2217 = !{!2218, !2222, !2223, !2228}
!2218 = !DISubprogram(name: "__pair_base", scope: !2216, file: !764, line: 194, type: !2219, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2219 = !DISubroutineType(types: !2220)
!2220 = !{null, !2221}
!2221 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2216, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2222 = !DISubprogram(name: "~__pair_base", scope: !2216, file: !764, line: 195, type: !2219, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2223 = !DISubprogram(name: "__pair_base", scope: !2216, file: !764, line: 196, type: !2224, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2224 = !DISubroutineType(types: !2225)
!2225 = !{null, !2221, !2226}
!2226 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2227, size: 64)
!2227 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2216)
!2228 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN4llvm9StringRefES1_EaSERKS2_", scope: !2216, file: !764, line: 197, type: !2229, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2229 = !DISubroutineType(types: !2230)
!2230 = !{!2231, !2221, !2226}
!2231 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2216, size: 64)
!2232 = !{!2233, !2234}
!2233 = !DITemplateTypeParameter(name: "_U1", type: !2100)
!2234 = !DITemplateTypeParameter(name: "_U2", type: !2100)
!2235 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !2213, file: !764, line: 214, baseType: !2100, size: 128)
!2236 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !2213, file: !764, line: 215, baseType: !2100, size: 128, offset: 128)
!2237 = !DISubprogram(name: "pair", scope: !2213, file: !764, line: 303, type: !2238, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2238 = !DISubroutineType(types: !2239)
!2239 = !{null, !2240, !2241}
!2240 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2213, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2241 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2242, size: 64)
!2242 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2213)
!2243 = !DISubprogram(name: "pair", scope: !2213, file: !764, line: 304, type: !2244, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2244 = !DISubroutineType(types: !2245)
!2245 = !{null, !2240, !2246}
!2246 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2213, size: 64)
!2247 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_EaSERKS2_", scope: !2213, file: !764, line: 378, type: !2248, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2248 = !DISubroutineType(types: !2249)
!2249 = !{!2250, !2240, !2251}
!2250 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2213, size: 64)
!2251 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2252, file: !821, line: 1928, baseType: !2241)
!2252 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::StringRef, llvm::StringRef> &, const std::__nonesuch_no_braces &>", scope: !408, file: !821, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !2253, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN4llvm9StringRefES2_ERKSt20__nonesuch_no_bracesE")
!2253 = !{!825, !2254, !827}
!2254 = !DITemplateTypeParameter(name: "_Iftrue", type: !2241)
!2255 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_EaSEOS2_", scope: !2213, file: !764, line: 389, type: !2256, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2256 = !DISubroutineType(types: !2257)
!2257 = !{!2250, !2240, !2258}
!2258 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2259, file: !821, line: 1928, baseType: !2246)
!2259 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::StringRef, llvm::StringRef> &&, std::__nonesuch_no_braces &&>", scope: !408, file: !821, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !823, templateParams: !2260, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN4llvm9StringRefES2_EOSt20__nonesuch_no_bracesE")
!2260 = !{!825, !2261, !838}
!2261 = !DITemplateTypeParameter(name: "_Iftrue", type: !2246)
!2262 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_E4swapERS2_", scope: !2213, file: !764, line: 424, type: !2263, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2263 = !DISubroutineType(types: !2264)
!2264 = !{null, !2240, !2250}
!2265 = !{!2266, !2267}
!2266 = !DITemplateTypeParameter(name: "_T1", type: !2100)
!2267 = !DITemplateTypeParameter(name: "_T2", type: !2100)
!2268 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitES0_", scope: !2100, file: !2101, line: 454, type: !2269, scopeLine: 454, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2269 = !DISubroutineType(types: !2270)
!2270 = !{!2213, !2133, !2100}
!2271 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitERNS_15SmallVectorImplIS0_EES0_ib", scope: !2100, file: !2101, line: 475, type: !2272, scopeLine: 475, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2272 = !DISubroutineType(types: !2273)
!2273 = !{null, !2133, !2274, !2100, !701, !82}
!2274 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2275, size: 64)
!2275 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<llvm::StringRef>", scope: !13, file: !2101, line: 23, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm15SmallVectorImplINS_9StringRefEEE")
!2276 = !DISubprogram(name: "rsplit", linkageName: "_ZNK4llvm9StringRef6rsplitEc", scope: !2100, file: !2101, line: 489, type: !2211, scopeLine: 489, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2277 = !DISubprogram(name: "ltrim", linkageName: "_ZNK4llvm9StringRef5ltrimES0_", scope: !2100, file: !2101, line: 498, type: !2278, scopeLine: 498, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2278 = !DISubroutineType(types: !2279)
!2279 = !{!2100, !2133, !2100}
!2280 = !DISubprogram(name: "rtrim", linkageName: "_ZNK4llvm9StringRef5rtrimES0_", scope: !2100, file: !2101, line: 504, type: !2278, scopeLine: 504, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2281 = !DISubprogram(name: "trim", linkageName: "_ZNK4llvm9StringRef4trimES0_", scope: !2100, file: !2101, line: 510, type: !2278, scopeLine: 510, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2282 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Iter_comp_val<bool (*)(clang::CodeGen::VBTablePath *, clang::CodeGen::VBTablePath *)>", scope: !1904, file: !1903, line: 153, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2283, templateParams: !1914, identifier: "_ZTSN9__gnu_cxx5__ops14_Iter_comp_valIPFbPN5clang7CodeGen11VBTablePathES5_EEE")
!2283 = !{!2284, !2285, !2289, !2292}
!2284 = !DIDerivedType(tag: DW_TAG_member, name: "_M_comp", scope: !2282, file: !1903, line: 155, baseType: !1907, size: 64)
!2285 = !DISubprogram(name: "_Iter_comp_val", scope: !2282, file: !1903, line: 158, type: !2286, scopeLine: 158, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2286 = !DISubroutineType(types: !2287)
!2287 = !{null, !2288, !1907}
!2288 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2282, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2289 = !DISubprogram(name: "_Iter_comp_val", scope: !2282, file: !1903, line: 163, type: !2290, scopeLine: 163, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2290 = !DISubroutineType(types: !2291)
!2291 = !{null, !2288, !1941}
!2292 = !DISubprogram(name: "_Iter_comp_val", scope: !2282, file: !1903, line: 169, type: !2293, scopeLine: 169, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2293 = !DISubroutineType(types: !2294)
!2294 = !{null, !2288, !1946}
!2295 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallString<256U>", scope: !13, file: !2296, line: 25, size: 2240, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2297, templateParams: !2492, identifier: "_ZTSN4llvm11SmallStringILj256EEE")
!2296 = !DIFile(filename: "llvm34/include/llvm/ADT/SmallString.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "2c780b02f5ec1f15da12c71ace03c232")
!2297 = !{!2298, !2417, !2421, !2424, !2429, !2432, !2433, !2436, !2437, !2438, !2439, !2443, !2444, !2447, !2448, !2449, !2450, !2451, !2454, !2457, !2458, !2461, !2462, !2463, !2464, !2465, !2466, !2467, !2470, !2471, !2474, !2475, !2478, !2481, !2482, !2485, !2489}
!2298 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2295, baseType: !2299, flags: DIFlagPublic, extraData: i32 0)
!2299 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<char, 256U>", scope: !13, file: !914, line: 880, size: 2240, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2300, templateParams: !2393, identifier: "_ZTSN4llvm11SmallVectorIcLj256EEE")
!2300 = !{!2301, !2386, !2395, !2399, !2402, !2407, !2410, !2414}
!2301 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2299, baseType: !2302, flags: DIFlagPublic, extraData: i32 0)
!2302 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<char>", scope: !13, file: !914, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2303, templateParams: !2385, identifier: "_ZTSN4llvm15SmallVectorImplIcEE")
!2303 = !{!2304, !2323, !2329, !2332, !2335, !2336, !2337, !2340, !2341, !2344, !2348, !2353, !2354, !2358, !2361, !2365, !2368, !2371, !2374, !2378, !2382, !2383, !2384}
!2304 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2302, baseType: !2305, flags: DIFlagPublic, extraData: i32 0)
!2305 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<char, true>", scope: !13, file: !914, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2306, templateParams: !2322, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseIcLb1EEE")
!2306 = !{!2307, !2308, !2312, !2315, !2316, !2319}
!2307 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2305, baseType: !1046, flags: DIFlagPublic, extraData: i32 0)
!2308 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !2305, file: !914, line: 298, type: !2309, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2309 = !DISubroutineType(types: !2310)
!2310 = !{null, !2311, !927}
!2311 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2305, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2312 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIcLb1EE13destroy_rangeEPcS2_", scope: !2305, file: !914, line: 301, type: !2313, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2313 = !DISubroutineType(types: !2314)
!2314 = !{null, !746, !746}
!2315 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIcLb1EE4growEm", scope: !2305, file: !914, line: 346, type: !2309, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2316 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIcLb1EE9push_backERKc", scope: !2305, file: !914, line: 350, type: !2317, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2317 = !DISubroutineType(types: !2318)
!2318 = !{null, !2311, !1130}
!2319 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIcLb1EE8pop_backEv", scope: !2305, file: !914, line: 361, type: !2320, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2320 = !DISubroutineType(types: !2321)
!2321 = !{null, !2311}
!2322 = !{!1140, !1461}
!2323 = !DISubprogram(name: "SmallVectorImpl", scope: !2302, file: !914, line: 374, type: !2324, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2324 = !DISubroutineType(types: !2325)
!2325 = !{null, !2326, !2327}
!2326 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2302, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2327 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2328, size: 64)
!2328 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2302)
!2329 = !DISubprogram(name: "SmallVectorImpl", scope: !2302, file: !914, line: 381, type: !2330, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2330 = !DISubroutineType(types: !2331)
!2331 = !{null, !2326, !6}
!2332 = !DISubprogram(name: "~SmallVectorImpl", scope: !2302, file: !914, line: 386, type: !2333, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2333 = !DISubroutineType(types: !2334)
!2334 = !{null, !2326}
!2335 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplIcE5clearEv", scope: !2302, file: !914, line: 396, type: !2333, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2336 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIcE6resizeEj", scope: !2302, file: !914, line: 401, type: !2330, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2337 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIcE6resizeEjRKc", scope: !2302, file: !914, line: 413, type: !2338, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2338 = !DISubroutineType(types: !2339)
!2339 = !{null, !2326, !6, !1130}
!2340 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplIcE7reserveEj", scope: !2302, file: !914, line: 425, type: !2330, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2341 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplIcE12pop_back_valEv", scope: !2302, file: !914, line: 430, type: !2342, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2342 = !DISubroutineType(types: !2343)
!2343 = !{!458, !2326}
!2344 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplIcE4swapERS1_", scope: !2302, file: !914, line: 440, type: !2345, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2345 = !DISubroutineType(types: !2346)
!2346 = !{null, !2326, !2347}
!2347 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2302, size: 64)
!2348 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplIcE6appendEmRKc", scope: !2302, file: !914, line: 460, type: !2349, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2349 = !DISubroutineType(types: !2350)
!2350 = !{null, !2326, !2351, !1130}
!2351 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2302, file: !914, line: 377, baseType: !2352)
!2352 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1046, file: !914, line: 97, baseType: !927)
!2353 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplIcE6assignEjRKc", scope: !2302, file: !914, line: 470, type: !2338, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2354 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIcE5eraseEPc", scope: !2302, file: !914, line: 478, type: !2355, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2355 = !DISubroutineType(types: !2356)
!2356 = !{!2357, !2326, !2357}
!2357 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2302, file: !914, line: 376, baseType: !1045)
!2358 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIcE5eraseEPcS2_", scope: !2302, file: !914, line: 490, type: !2359, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2359 = !DISubroutineType(types: !2360)
!2360 = !{!2357, !2326, !2357, !2357}
!2361 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIcE6insertEPcOc", scope: !2302, file: !914, line: 505, type: !2362, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2362 = !DISubroutineType(types: !2363)
!2363 = !{!2357, !2326, !2357, !2364}
!2364 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !458, size: 64)
!2365 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIcE6insertEPcRKc", scope: !2302, file: !914, line: 537, type: !2366, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2366 = !DISubroutineType(types: !2367)
!2367 = !{!2357, !2326, !2357, !1130}
!2368 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIcE6insertEPcmRKc", scope: !2302, file: !914, line: 568, type: !2369, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2369 = !DISubroutineType(types: !2370)
!2370 = !{!2357, !2326, !2357, !2351, !1130}
!2371 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIcEaSERKS1_", scope: !2302, file: !914, line: 674, type: !2372, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2372 = !DISubroutineType(types: !2373)
!2373 = !{!2347, !2326, !2327}
!2374 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIcEaSEOS1_", scope: !2302, file: !914, line: 677, type: !2375, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2375 = !DISubroutineType(types: !2376)
!2376 = !{!2347, !2326, !2377}
!2377 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2302, size: 64)
!2378 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplIcEeqERKS1_", scope: !2302, file: !914, line: 680, type: !2379, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2379 = !DISubroutineType(types: !2380)
!2380 = !{!82, !2381, !2327}
!2381 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2328, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2382 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplIcEneERKS1_", scope: !2302, file: !914, line: 684, type: !2379, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2383 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplIcEltERKS1_", scope: !2302, file: !914, line: 688, type: !2379, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2384 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplIcE8set_sizeEj", scope: !2302, file: !914, line: 702, type: !2330, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2385 = !{!1140}
!2386 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !2299, file: !914, line: 882, baseType: !2387, size: 2040, offset: 200)
!2387 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<char, 256U>", scope: !13, file: !914, line: 865, size: 2040, flags: DIFlagTypePassByValue, elements: !2388, templateParams: !2393, identifier: "_ZTSN4llvm18SmallVectorStorageIcLj256EEE")
!2388 = !{!2389}
!2389 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !2387, file: !914, line: 866, baseType: !2390, size: 2040)
!2390 = !DICompositeType(tag: DW_TAG_array_type, baseType: !1050, size: 2040, elements: !2391)
!2391 = !{!2392}
!2392 = !DISubrange(count: 255)
!2393 = !{!1140, !2394}
!2394 = !DITemplateValueParameter(name: "N", type: !6, value: i32 256)
!2395 = !DISubprogram(name: "SmallVector", scope: !2299, file: !914, line: 884, type: !2396, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2396 = !DISubroutineType(types: !2397)
!2397 = !{null, !2398}
!2398 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2299, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2399 = !DISubprogram(name: "SmallVector", scope: !2299, file: !914, line: 887, type: !2400, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2400 = !DISubroutineType(types: !2401)
!2401 = !{null, !2398, !6, !1130}
!2402 = !DISubprogram(name: "SmallVector", scope: !2299, file: !914, line: 897, type: !2403, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2403 = !DISubroutineType(types: !2404)
!2404 = !{null, !2398, !2405}
!2405 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2406, size: 64)
!2406 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2299)
!2407 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIcLj256EEaSERKS1_", scope: !2299, file: !914, line: 902, type: !2408, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2408 = !DISubroutineType(types: !2409)
!2409 = !{!2405, !2398, !2405}
!2410 = !DISubprogram(name: "SmallVector", scope: !2299, file: !914, line: 908, type: !2411, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2411 = !DISubroutineType(types: !2412)
!2412 = !{null, !2398, !2413}
!2413 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2299, size: 64)
!2414 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIcLj256EEaSEOS1_", scope: !2299, file: !914, line: 913, type: !2415, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2415 = !DISubroutineType(types: !2416)
!2416 = !{!2405, !2398, !2413}
!2417 = !DISubprogram(name: "SmallString", scope: !2295, file: !2296, line: 28, type: !2418, scopeLine: 28, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2418 = !DISubroutineType(types: !2419)
!2419 = !{null, !2420}
!2420 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2295, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2421 = !DISubprogram(name: "SmallString", scope: !2295, file: !2296, line: 31, type: !2422, scopeLine: 31, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2422 = !DISubroutineType(types: !2423)
!2423 = !{null, !2420, !2100}
!2424 = !DISubprogram(name: "SmallString", scope: !2295, file: !2296, line: 38, type: !2425, scopeLine: 38, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2425 = !DISubroutineType(types: !2426)
!2426 = !{null, !2420, !2427}
!2427 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2428, size: 64)
!2428 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2295)
!2429 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj256EE6assignEmc", scope: !2295, file: !2296, line: 48, type: !2430, scopeLine: 48, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2430 = !DISubroutineType(types: !2431)
!2431 = !{null, !2420, !927, !458}
!2432 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj256EE6assignENS_9StringRefE", scope: !2295, file: !2296, line: 60, type: !2422, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2433 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj256EE6assignERKNS_15SmallVectorImplIcEE", scope: !2295, file: !2296, line: 66, type: !2434, scopeLine: 66, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2434 = !DISubroutineType(types: !2435)
!2435 = !{null, !2420, !2327}
!2436 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj256EE6appendEmc", scope: !2295, file: !2296, line: 81, type: !2430, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2437 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj256EE6appendENS_9StringRefE", scope: !2295, file: !2296, line: 87, type: !2422, scopeLine: 87, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2438 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj256EE6appendERKNS_15SmallVectorImplIcEE", scope: !2295, file: !2296, line: 92, type: !2434, scopeLine: 92, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2439 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm11SmallStringILj256EE6equalsENS_9StringRefE", scope: !2295, file: !2296, line: 102, type: !2440, scopeLine: 102, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2440 = !DISubroutineType(types: !2441)
!2441 = !{!82, !2442, !2100}
!2442 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2428, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2443 = !DISubprogram(name: "equals_lower", linkageName: "_ZNK4llvm11SmallStringILj256EE12equals_lowerENS_9StringRefE", scope: !2295, file: !2296, line: 107, type: !2440, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2444 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm11SmallStringILj256EE7compareENS_9StringRefE", scope: !2295, file: !2296, line: 113, type: !2445, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2445 = !DISubroutineType(types: !2446)
!2446 = !{!701, !2442, !2100}
!2447 = !DISubprogram(name: "compare_lower", linkageName: "_ZNK4llvm11SmallStringILj256EE13compare_lowerENS_9StringRefE", scope: !2295, file: !2296, line: 118, type: !2445, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2448 = !DISubprogram(name: "compare_numeric", linkageName: "_ZNK4llvm11SmallStringILj256EE15compare_numericENS_9StringRefE", scope: !2295, file: !2296, line: 124, type: !2445, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2449 = !DISubprogram(name: "startswith", linkageName: "_ZNK4llvm11SmallStringILj256EE10startswithENS_9StringRefE", scope: !2295, file: !2296, line: 133, type: !2440, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2450 = !DISubprogram(name: "endswith", linkageName: "_ZNK4llvm11SmallStringILj256EE8endswithENS_9StringRefE", scope: !2295, file: !2296, line: 138, type: !2440, scopeLine: 138, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2451 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm11SmallStringILj256EE4findEcm", scope: !2295, file: !2296, line: 150, type: !2452, scopeLine: 150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2452 = !DISubroutineType(types: !2453)
!2453 = !{!927, !2442, !458, !927}
!2454 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm11SmallStringILj256EE4findENS_9StringRefEm", scope: !2295, file: !2296, line: 158, type: !2455, scopeLine: 158, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2455 = !DISubroutineType(types: !2456)
!2456 = !{!927, !2442, !2100, !927}
!2457 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm11SmallStringILj256EE5rfindEcm", scope: !2295, file: !2296, line: 166, type: !2452, scopeLine: 166, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2458 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm11SmallStringILj256EE5rfindENS_9StringRefE", scope: !2295, file: !2296, line: 174, type: !2459, scopeLine: 174, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2459 = !DISubroutineType(types: !2460)
!2460 = !{!927, !2442, !2100}
!2461 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm11SmallStringILj256EE13find_first_ofEcm", scope: !2295, file: !2296, line: 180, type: !2452, scopeLine: 180, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2462 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm11SmallStringILj256EE13find_first_ofENS_9StringRefEm", scope: !2295, file: !2296, line: 188, type: !2455, scopeLine: 188, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2463 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm11SmallStringILj256EE17find_first_not_ofEcm", scope: !2295, file: !2296, line: 194, type: !2452, scopeLine: 194, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2464 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm11SmallStringILj256EE17find_first_not_ofENS_9StringRefEm", scope: !2295, file: !2296, line: 202, type: !2455, scopeLine: 202, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2465 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm11SmallStringILj256EE12find_last_ofEcm", scope: !2295, file: !2296, line: 208, type: !2452, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2466 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm11SmallStringILj256EE12find_last_ofENS_9StringRefEm", scope: !2295, file: !2296, line: 216, type: !2455, scopeLine: 216, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2467 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm11SmallStringILj256EE5countEc", scope: !2295, file: !2296, line: 226, type: !2468, scopeLine: 226, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2468 = !DISubroutineType(types: !2469)
!2469 = !{!927, !2442, !458}
!2470 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm11SmallStringILj256EE5countENS_9StringRefE", scope: !2295, file: !2296, line: 232, type: !2459, scopeLine: 232, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2471 = !DISubprogram(name: "substr", linkageName: "_ZNK4llvm11SmallStringILj256EE6substrEmm", scope: !2295, file: !2296, line: 249, type: !2472, scopeLine: 249, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2472 = !DISubroutineType(types: !2473)
!2473 = !{!2100, !2442, !927, !927}
!2474 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm11SmallStringILj256EE5sliceEmm", scope: !2295, file: !2296, line: 263, type: !2472, scopeLine: 263, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2475 = !DISubprogram(name: "str", linkageName: "_ZNK4llvm11SmallStringILj256EE3strEv", scope: !2295, file: !2296, line: 270, type: !2476, scopeLine: 270, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2476 = !DISubroutineType(types: !2477)
!2477 = !{!2100, !2442}
!2478 = !DISubprogram(name: "c_str", linkageName: "_ZN4llvm11SmallStringILj256EE5c_strEv", scope: !2295, file: !2296, line: 273, type: !2479, scopeLine: 273, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2479 = !DISubroutineType(types: !2480)
!2480 = !{!456, !2420}
!2481 = !DISubprogram(name: "operator StringRef", linkageName: "_ZNK4llvm11SmallStringILj256EEcvNS_9StringRefEEv", scope: !2295, file: !2296, line: 280, type: !2476, scopeLine: 280, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2482 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallStringILj256EEaSENS_9StringRefE", scope: !2295, file: !2296, line: 283, type: !2483, scopeLine: 283, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2483 = !DISubroutineType(types: !2484)
!2484 = !{!2427, !2420, !2100}
!2485 = !DISubprogram(name: "operator+=", linkageName: "_ZN4llvm11SmallStringILj256EEpLENS_9StringRefE", scope: !2295, file: !2296, line: 288, type: !2486, scopeLine: 288, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2486 = !DISubroutineType(types: !2487)
!2487 = !{!2488, !2420, !2100}
!2488 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2295, size: 64)
!2489 = !DISubprogram(name: "operator+=", linkageName: "_ZN4llvm11SmallStringILj256EEpLEc", scope: !2295, file: !2296, line: 292, type: !2490, scopeLine: 292, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2490 = !DISubroutineType(types: !2491)
!2491 = !{!2488, !2420, !458}
!2492 = !{!2493}
!2493 = !DITemplateValueParameter(name: "InternalLen", type: !6, value: i32 256)
!2494 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<llvm::Constant *, 4U>", scope: !13, file: !914, line: 880, size: 448, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2495, templateParams: !2588, identifier: "_ZTSN4llvm11SmallVectorIPNS_8ConstantELj4EEE")
!2495 = !{!2496, !2581, !2590, !2594, !2597, !2602, !2605, !2609}
!2496 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2494, baseType: !2497, flags: DIFlagPublic, extraData: i32 0)
!2497 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<llvm::Constant *>", scope: !13, file: !914, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2498, templateParams: !2580, identifier: "_ZTSN4llvm15SmallVectorImplIPNS_8ConstantEEE")
!2498 = !{!2499, !2518, !2524, !2527, !2530, !2531, !2532, !2535, !2536, !2539, !2543, !2548, !2549, !2553, !2556, !2560, !2563, !2566, !2569, !2573, !2577, !2578, !2579}
!2499 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2497, baseType: !2500, flags: DIFlagPublic, extraData: i32 0)
!2500 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<llvm::Constant *, true>", scope: !13, file: !914, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2501, templateParams: !2517, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseIPNS_8ConstantELb1EEE")
!2501 = !{!2502, !2503, !2507, !2510, !2511, !2514}
!2502 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2500, baseType: !1277, flags: DIFlagPublic, extraData: i32 0)
!2503 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !2500, file: !914, line: 298, type: !2504, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2504 = !DISubroutineType(types: !2505)
!2505 = !{null, !2506, !927}
!2506 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2500, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2507 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPNS_8ConstantELb1EE13destroy_rangeEPS2_S4_", scope: !2500, file: !914, line: 301, type: !2508, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2508 = !DISubroutineType(types: !2509)
!2509 = !{null, !1308, !1308}
!2510 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPNS_8ConstantELb1EE4growEm", scope: !2500, file: !914, line: 346, type: !2504, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2511 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPNS_8ConstantELb1EE9push_backERKS2_", scope: !2500, file: !914, line: 350, type: !2512, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2512 = !DISubroutineType(types: !2513)
!2513 = !{null, !2506, !1358}
!2514 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPNS_8ConstantELb1EE8pop_backEv", scope: !2500, file: !914, line: 361, type: !2515, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2515 = !DISubroutineType(types: !2516)
!2516 = !{null, !2506}
!2517 = !{!1368, !1461}
!2518 = !DISubprogram(name: "SmallVectorImpl", scope: !2497, file: !914, line: 374, type: !2519, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2519 = !DISubroutineType(types: !2520)
!2520 = !{null, !2521, !2522}
!2521 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2497, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2522 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2523, size: 64)
!2523 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2497)
!2524 = !DISubprogram(name: "SmallVectorImpl", scope: !2497, file: !914, line: 381, type: !2525, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2525 = !DISubroutineType(types: !2526)
!2526 = !{null, !2521, !6}
!2527 = !DISubprogram(name: "~SmallVectorImpl", scope: !2497, file: !914, line: 386, type: !2528, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2528 = !DISubroutineType(types: !2529)
!2529 = !{null, !2521}
!2530 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEE5clearEv", scope: !2497, file: !914, line: 396, type: !2528, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2531 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEE6resizeEj", scope: !2497, file: !914, line: 401, type: !2525, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2532 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEE6resizeEjRKS2_", scope: !2497, file: !914, line: 413, type: !2533, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2533 = !DISubroutineType(types: !2534)
!2534 = !{null, !2521, !6, !1358}
!2535 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEE7reserveEj", scope: !2497, file: !914, line: 425, type: !2525, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2536 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEE12pop_back_valEv", scope: !2497, file: !914, line: 430, type: !2537, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2537 = !DISubroutineType(types: !2538)
!2538 = !{!1287, !2521}
!2539 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEE4swapERS3_", scope: !2497, file: !914, line: 440, type: !2540, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2540 = !DISubroutineType(types: !2541)
!2541 = !{null, !2521, !2542}
!2542 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2497, size: 64)
!2543 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEE6appendEmRKS2_", scope: !2497, file: !914, line: 460, type: !2544, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2544 = !DISubroutineType(types: !2545)
!2545 = !{null, !2521, !2546, !1358}
!2546 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2497, file: !914, line: 377, baseType: !2547)
!2547 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1277, file: !914, line: 97, baseType: !927)
!2548 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEE6assignEjRKS2_", scope: !2497, file: !914, line: 470, type: !2533, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2549 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEE5eraseEPS2_", scope: !2497, file: !914, line: 478, type: !2550, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2550 = !DISubroutineType(types: !2551)
!2551 = !{!2552, !2521, !2552}
!2552 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2497, file: !914, line: 376, baseType: !1276)
!2553 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEE5eraseEPS2_S4_", scope: !2497, file: !914, line: 490, type: !2554, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2554 = !DISubroutineType(types: !2555)
!2555 = !{!2552, !2521, !2552, !2552}
!2556 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEE6insertEPS2_OS2_", scope: !2497, file: !914, line: 505, type: !2557, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2557 = !DISubroutineType(types: !2558)
!2558 = !{!2552, !2521, !2552, !2559}
!2559 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1287, size: 64)
!2560 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEE6insertEPS2_RKS2_", scope: !2497, file: !914, line: 537, type: !2561, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2561 = !DISubroutineType(types: !2562)
!2562 = !{!2552, !2521, !2552, !1358}
!2563 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEE6insertEPS2_mRKS2_", scope: !2497, file: !914, line: 568, type: !2564, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2564 = !DISubroutineType(types: !2565)
!2565 = !{!2552, !2521, !2552, !2546, !1358}
!2566 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEEaSERKS3_", scope: !2497, file: !914, line: 674, type: !2567, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2567 = !DISubroutineType(types: !2568)
!2568 = !{!2542, !2521, !2522}
!2569 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEEaSEOS3_", scope: !2497, file: !914, line: 677, type: !2570, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2570 = !DISubroutineType(types: !2571)
!2571 = !{!2542, !2521, !2572}
!2572 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2497, size: 64)
!2573 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplIPNS_8ConstantEEeqERKS3_", scope: !2497, file: !914, line: 680, type: !2574, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2574 = !DISubroutineType(types: !2575)
!2575 = !{!82, !2576, !2522}
!2576 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2523, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2577 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplIPNS_8ConstantEEneERKS3_", scope: !2497, file: !914, line: 684, type: !2574, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2578 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplIPNS_8ConstantEEltERKS3_", scope: !2497, file: !914, line: 688, type: !2574, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2579 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplIPNS_8ConstantEE8set_sizeEj", scope: !2497, file: !914, line: 702, type: !2525, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2580 = !{!1368}
!2581 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !2494, file: !914, line: 882, baseType: !2582, size: 192, offset: 256)
!2582 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<llvm::Constant *, 4U>", scope: !13, file: !914, line: 865, size: 192, flags: DIFlagTypePassByValue, elements: !2583, templateParams: !2588, identifier: "_ZTSN4llvm18SmallVectorStorageIPNS_8ConstantELj4EEE")
!2583 = !{!2584}
!2584 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !2582, file: !914, line: 866, baseType: !2585, size: 192)
!2585 = !DICompositeType(tag: DW_TAG_array_type, baseType: !1281, size: 192, elements: !2586)
!2586 = !{!2587}
!2587 = !DISubrange(count: 3)
!2588 = !{!1368, !2589}
!2589 = !DITemplateValueParameter(name: "N", type: !6, value: i32 4)
!2590 = !DISubprogram(name: "SmallVector", scope: !2494, file: !914, line: 884, type: !2591, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2591 = !DISubroutineType(types: !2592)
!2592 = !{null, !2593}
!2593 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2494, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2594 = !DISubprogram(name: "SmallVector", scope: !2494, file: !914, line: 887, type: !2595, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2595 = !DISubroutineType(types: !2596)
!2596 = !{null, !2593, !6, !1358}
!2597 = !DISubprogram(name: "SmallVector", scope: !2494, file: !914, line: 897, type: !2598, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2598 = !DISubroutineType(types: !2599)
!2599 = !{null, !2593, !2600}
!2600 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2601, size: 64)
!2601 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2494)
!2602 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIPNS_8ConstantELj4EEaSERKS3_", scope: !2494, file: !914, line: 902, type: !2603, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2603 = !DISubroutineType(types: !2604)
!2604 = !{!2600, !2593, !2600}
!2605 = !DISubprogram(name: "SmallVector", scope: !2494, file: !914, line: 908, type: !2606, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2606 = !DISubroutineType(types: !2607)
!2607 = !{null, !2593, !2608}
!2608 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2494, size: 64)
!2609 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIPNS_8ConstantELj4EEaSEOS3_", scope: !2494, file: !914, line: 913, type: !2610, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2610 = !DISubroutineType(types: !2611)
!2611 = !{!2600, !2593, !2608}
!2612 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ArrayRef<llvm::Constant *>", scope: !13, file: !1981, line: 31, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2613, templateParams: !2580, identifier: "_ZTSN4llvm8ArrayRefIPNS_8ConstantEEE")
!2613 = !{!2614, !2615, !2616, !2620, !2623, !2626, !2629, !2632, !2638, !2644, !2645, !2649, !2650, !2653, !2656, !2659, !2662, !2663, !2666, !2669, !2672, !2675, !2679}
!2614 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !2612, file: !1981, line: 41, baseType: !1316, size: 64)
!2615 = !DIDerivedType(tag: DW_TAG_member, name: "Length", scope: !2612, file: !1981, line: 44, baseType: !1985, size: 64, offset: 64)
!2616 = !DISubprogram(name: "ArrayRef", scope: !2612, file: !1981, line: 51, type: !2617, scopeLine: 51, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2617 = !DISubroutineType(types: !2618)
!2618 = !{null, !2619}
!2619 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2612, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2620 = !DISubprogram(name: "ArrayRef", scope: !2612, file: !1981, line: 54, type: !2621, scopeLine: 54, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2621 = !DISubroutineType(types: !2622)
!2622 = !{null, !2619, !11}
!2623 = !DISubprogram(name: "ArrayRef", scope: !2612, file: !1981, line: 57, type: !2624, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2624 = !DISubroutineType(types: !2625)
!2625 = !{null, !2619, !1358}
!2626 = !DISubprogram(name: "ArrayRef", scope: !2612, file: !1981, line: 61, type: !2627, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2627 = !DISubroutineType(types: !2628)
!2628 = !{null, !2619, !1316, !927}
!2629 = !DISubprogram(name: "ArrayRef", scope: !2612, file: !1981, line: 65, type: !2630, scopeLine: 65, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2630 = !DISubroutineType(types: !2631)
!2631 = !{null, !2619, !1316, !1316}
!2632 = !DISubprogram(name: "ArrayRef", scope: !2612, file: !1981, line: 88, type: !2633, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2633 = !DISubroutineType(types: !2634)
!2634 = !{null, !2619, !2635}
!2635 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2636, size: 64)
!2636 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2637)
!2637 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<llvm::Constant *>", scope: !408, file: !2008, line: 47, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listIPN4llvm8ConstantEE")
!2638 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEE5beginEv", scope: !2612, file: !1981, line: 97, type: !2639, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2639 = !DISubroutineType(types: !2640)
!2640 = !{!2641, !2642}
!2641 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2612, file: !1981, line: 33, baseType: !1316)
!2642 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2643, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2643 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2612)
!2644 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEE3endEv", scope: !2612, file: !1981, line: 98, type: !2639, scopeLine: 98, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2645 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEE6rbeginEv", scope: !2612, file: !1981, line: 100, type: !2646, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2646 = !DISubroutineType(types: !2647)
!2647 = !{!2648, !2642}
!2648 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !2612, file: !1981, line: 37, baseType: !1331)
!2649 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEE4rendEv", scope: !2612, file: !1981, line: 101, type: !2646, scopeLine: 101, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2650 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEE5emptyEv", scope: !2612, file: !1981, line: 104, type: !2651, scopeLine: 104, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2651 = !DISubroutineType(types: !2652)
!2652 = !{!82, !2642}
!2653 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEE4dataEv", scope: !2612, file: !1981, line: 106, type: !2654, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2654 = !DISubroutineType(types: !2655)
!2655 = !{!1316, !2642}
!2656 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEE4sizeEv", scope: !2612, file: !1981, line: 109, type: !2657, scopeLine: 109, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2657 = !DISubroutineType(types: !2658)
!2658 = !{!927, !2642}
!2659 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEE5frontEv", scope: !2612, file: !1981, line: 112, type: !2660, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2660 = !DISubroutineType(types: !2661)
!2661 = !{!1358, !2642}
!2662 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEE4backEv", scope: !2612, file: !1981, line: 118, type: !2660, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2663 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEE6equalsES3_", scope: !2612, file: !1981, line: 124, type: !2664, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2664 = !DISubroutineType(types: !2665)
!2665 = !{!82, !2642, !2612}
!2666 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEE5sliceEj", scope: !2612, file: !1981, line: 134, type: !2667, scopeLine: 134, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2667 = !DISubroutineType(types: !2668)
!2668 = !{!2612, !2642, !6}
!2669 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEE5sliceEjj", scope: !2612, file: !1981, line: 141, type: !2670, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2670 = !DISubroutineType(types: !2671)
!2671 = !{!2612, !2642, !6, !6}
!2672 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEEixEm", scope: !2612, file: !1981, line: 149, type: !2673, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2673 = !DISubroutineType(types: !2674)
!2674 = !{!1358, !2642, !927}
!2675 = !DISubprogram(name: "vec", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEE3vecEv", scope: !2612, file: !1981, line: 157, type: !2676, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2676 = !DISubroutineType(types: !2677)
!2677 = !{!2678, !2642}
!2678 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<llvm::Constant *, std::allocator<llvm::Constant *> >", scope: !408, file: !1635, line: 339, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt6vectorIPN4llvm8ConstantESaIS2_EE")
!2679 = !DISubprogram(name: "operator vector", linkageName: "_ZNK4llvm8ArrayRefIPNS_8ConstantEEcvSt6vectorIS2_SaIS2_EEEv", scope: !2612, file: !1981, line: 164, type: !2676, scopeLine: 164, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2680 = !{!2681, !2686, !2691, !2696, !2701, !2706, !2711, !2716, !2721, !2726, !2731, !2736, !2741, !2746, !2748, !2753, !2758, !2763, !2768, !2773, !2778, !2783, !2788, !2790, !2795, !2797, !2800, !2805, !2810, !2815, !2820, !2825, !2827, !2832, !2834, !2839, !2844, !2849, !2854, !2859, !2864, !2869, !2874, !2876, !2881, !2886, !2891, !2896, !2901, !2906, !2909, !2914, !2919, !2924, !2929, !2934, !2939, !2944, !2946, !2951, !2956, !2961, !2966, !2971, !2976, !2982, !2987, !2989, !2994, !2996, !3002, !3007, !3009, !3014, !3019, !3024, !3029, !3034, !3039, !3041, !3043, !3045, !3050, !3052, !3057, !3059, !3061, !3066, !3068, !3070, !3072, !3077, !3082, !3087, !3089, !3091, !3094, !3099, !3101, !3106, !3111, !3116, !3121, !3126, !3131}
!2681 = !DIGlobalVariableExpression(var: !2682, expr: !DIExpression())
!2682 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 116, type: !2683, isLocal: true, isDefinition: true)
!2683 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 232, elements: !2684)
!2684 = !{!2685}
!2685 = !DISubrange(count: 29)
!2686 = !DIGlobalVariableExpression(var: !2687, expr: !DIExpression())
!2687 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 116, type: !2688, isLocal: true, isDefinition: true)
!2688 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 568, elements: !2689)
!2689 = !{!2690}
!2690 = !DISubrange(count: 71)
!2691 = !DIGlobalVariableExpression(var: !2692, expr: !DIExpression())
!2692 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 116, type: !2693, isLocal: true, isDefinition: true)
!2693 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 520, elements: !2694)
!2694 = !{!2695}
!2695 = !DISubrange(count: 65)
!2696 = !DIGlobalVariableExpression(var: !2697, expr: !DIExpression())
!2697 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 116, type: !2698, isLocal: true, isDefinition: true)
!2698 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 1176, elements: !2699)
!2699 = !{!2700}
!2700 = !DISubrange(count: 147)
!2701 = !DIGlobalVariableExpression(var: !2702, expr: !DIExpression())
!2702 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 126, type: !2703, isLocal: true, isDefinition: true)
!2703 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 208, elements: !2704)
!2704 = !{!2705}
!2705 = !DISubrange(count: 26)
!2706 = !DIGlobalVariableExpression(var: !2707, expr: !DIExpression())
!2707 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 126, type: !2708, isLocal: true, isDefinition: true)
!2708 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 680, elements: !2709)
!2709 = !{!2710}
!2710 = !DISubrange(count: 85)
!2711 = !DIGlobalVariableExpression(var: !2712, expr: !DIExpression())
!2712 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 178, type: !2713, isLocal: true, isDefinition: true)
!2713 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 424, elements: !2714)
!2714 = !{!2715}
!2715 = !DISubrange(count: 53)
!2716 = !DIGlobalVariableExpression(var: !2717, expr: !DIExpression())
!2717 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 178, type: !2718, isLocal: true, isDefinition: true)
!2718 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 768, elements: !2719)
!2719 = !{!2720}
!2720 = !DISubrange(count: 96)
!2721 = !DIGlobalVariableExpression(var: !2722, expr: !DIExpression())
!2722 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 178, type: !2723, isLocal: true, isDefinition: true)
!2723 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 1128, elements: !2724)
!2724 = !{!2725}
!2725 = !DISubrange(count: 141)
!2726 = !DIGlobalVariableExpression(var: !2727, expr: !DIExpression())
!2727 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 190, type: !2728, isLocal: true, isDefinition: true)
!2728 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 416, elements: !2729)
!2729 = !{!2730}
!2730 = !DISubrange(count: 52)
!2731 = !DIGlobalVariableExpression(var: !2732, expr: !DIExpression())
!2732 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 190, type: !2733, isLocal: true, isDefinition: true)
!2733 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 856, elements: !2734)
!2734 = !{!2735}
!2735 = !DISubrange(count: 107)
!2736 = !DIGlobalVariableExpression(var: !2737, expr: !DIExpression())
!2737 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 190, type: !2738, isLocal: true, isDefinition: true)
!2738 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 1288, elements: !2739)
!2739 = !{!2740}
!2740 = !DISubrange(count: 161)
!2741 = !DIGlobalVariableExpression(var: !2742, expr: !DIExpression())
!2742 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 209, type: !2743, isLocal: true, isDefinition: true)
!2743 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 168, elements: !2744)
!2744 = !{!2745}
!2745 = !DISubrange(count: 21)
!2746 = !DIGlobalVariableExpression(var: !2747, expr: !DIExpression())
!2747 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 213, type: !2683, isLocal: true, isDefinition: true)
!2748 = !DIGlobalVariableExpression(var: !2749, expr: !DIExpression())
!2749 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 213, type: !2750, isLocal: true, isDefinition: true)
!2750 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 448, elements: !2751)
!2751 = !{!2752}
!2752 = !DISubrange(count: 56)
!2753 = !DIGlobalVariableExpression(var: !2754, expr: !DIExpression())
!2754 = distinct !DIGlobalVariable(scope: null, file: !1393, line: 217, type: !2755, isLocal: true, isDefinition: true)
!2755 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 936, elements: !2756)
!2756 = !{!2757}
!2757 = !DISubrange(count: 117)
!2758 = !DIGlobalVariableExpression(var: !2759, expr: !DIExpression())
!2759 = distinct !DIGlobalVariable(scope: null, file: !787, line: 260, type: !2760, isLocal: true, isDefinition: true)
!2760 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 376, elements: !2761)
!2761 = !{!2762}
!2762 = !DISubrange(count: 47)
!2763 = !DIGlobalVariableExpression(var: !2764, expr: !DIExpression())
!2764 = distinct !DIGlobalVariable(scope: null, file: !787, line: 260, type: !2765, isLocal: true, isDefinition: true)
!2765 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 480, elements: !2766)
!2766 = !{!2767}
!2767 = !DISubrange(count: 60)
!2768 = !DIGlobalVariableExpression(var: !2769, expr: !DIExpression())
!2769 = distinct !DIGlobalVariable(scope: null, file: !787, line: 260, type: !2770, isLocal: true, isDefinition: true)
!2770 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 512, elements: !2771)
!2771 = !{!2772}
!2772 = !DISubrange(count: 64)
!2773 = !DIGlobalVariableExpression(var: !2774, expr: !DIExpression())
!2774 = distinct !DIGlobalVariable(scope: null, file: !787, line: 260, type: !2775, isLocal: true, isDefinition: true)
!2775 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 392, elements: !2776)
!2776 = !{!2777}
!2777 = !DISubrange(count: 49)
!2778 = !DIGlobalVariableExpression(var: !2779, expr: !DIExpression())
!2779 = distinct !DIGlobalVariable(scope: null, file: !787, line: 266, type: !2780, isLocal: true, isDefinition: true)
!2780 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 368, elements: !2781)
!2781 = !{!2782}
!2782 = !DISubrange(count: 46)
!2783 = !DIGlobalVariableExpression(var: !2784, expr: !DIExpression())
!2784 = distinct !DIGlobalVariable(scope: null, file: !523, line: 566, type: !2785, isLocal: true, isDefinition: true)
!2785 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 360, elements: !2786)
!2786 = !{!2787}
!2787 = !DISubrange(count: 45)
!2788 = !DIGlobalVariableExpression(var: !2789, expr: !DIExpression())
!2789 = distinct !DIGlobalVariable(scope: null, file: !523, line: 566, type: !2693, isLocal: true, isDefinition: true)
!2790 = !DIGlobalVariableExpression(var: !2791, expr: !DIExpression())
!2791 = distinct !DIGlobalVariable(scope: null, file: !523, line: 566, type: !2792, isLocal: true, isDefinition: true)
!2792 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 472, elements: !2793)
!2793 = !{!2794}
!2794 = !DISubrange(count: 59)
!2795 = !DIGlobalVariableExpression(var: !2796, expr: !DIExpression())
!2796 = distinct !DIGlobalVariable(scope: null, file: !523, line: 566, type: !2770, isLocal: true, isDefinition: true)
!2797 = !DIGlobalVariableExpression(var: !2798, expr: !DIExpression())
!2798 = distinct !DIGlobalVariable(scope: null, file: !2799, line: 349, type: !2750, isLocal: true, isDefinition: true)
!2799 = !DIFile(filename: "llvm34/projects/clang/include/clang/AST/ExternalASTSource.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "182ed67eb4c02b0139e64f02d7c0c9d0")
!2800 = !DIGlobalVariableExpression(var: !2801, expr: !DIExpression())
!2801 = distinct !DIGlobalVariable(scope: null, file: !2799, line: 349, type: !2802, isLocal: true, isDefinition: true)
!2802 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 544, elements: !2803)
!2803 = !{!2804}
!2804 = !DISubrange(count: 68)
!2805 = !DIGlobalVariableExpression(var: !2806, expr: !DIExpression())
!2806 = distinct !DIGlobalVariable(scope: null, file: !2799, line: 349, type: !2807, isLocal: true, isDefinition: true)
!2807 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 552, elements: !2808)
!2808 = !{!2809}
!2809 = !DISubrange(count: 69)
!2810 = !DIGlobalVariableExpression(var: !2811, expr: !DIExpression())
!2811 = distinct !DIGlobalVariable(scope: null, file: !2799, line: 349, type: !2812, isLocal: true, isDefinition: true)
!2812 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 2208, elements: !2813)
!2813 = !{!2814}
!2814 = !DISubrange(count: 276)
!2815 = !DIGlobalVariableExpression(var: !2816, expr: !DIExpression())
!2816 = distinct !DIGlobalVariable(scope: null, file: !47, line: 547, type: !2817, isLocal: true, isDefinition: true)
!2817 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 288, elements: !2818)
!2818 = !{!2819}
!2819 = !DISubrange(count: 36)
!2820 = !DIGlobalVariableExpression(var: !2821, expr: !DIExpression())
!2821 = distinct !DIGlobalVariable(scope: null, file: !47, line: 547, type: !2822, isLocal: true, isDefinition: true)
!2822 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 408, elements: !2823)
!2823 = !{!2824}
!2824 = !DISubrange(count: 51)
!2825 = !DIGlobalVariableExpression(var: !2826, expr: !DIExpression())
!2826 = distinct !DIGlobalVariable(scope: null, file: !47, line: 547, type: !2750, isLocal: true, isDefinition: true)
!2827 = !DIGlobalVariableExpression(var: !2828, expr: !DIExpression())
!2828 = distinct !DIGlobalVariable(scope: null, file: !47, line: 547, type: !2829, isLocal: true, isDefinition: true)
!2829 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 600, elements: !2830)
!2830 = !{!2831}
!2831 = !DISubrange(count: 75)
!2832 = !DIGlobalVariableExpression(var: !2833, expr: !DIExpression())
!2833 = distinct !DIGlobalVariable(scope: null, file: !52, line: 100, type: !2817, isLocal: true, isDefinition: true)
!2834 = !DIGlobalVariableExpression(var: !2835, expr: !DIExpression())
!2835 = distinct !DIGlobalVariable(scope: null, file: !52, line: 100, type: !2836, isLocal: true, isDefinition: true)
!2836 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 800, elements: !2837)
!2837 = !{!2838}
!2838 = !DISubrange(count: 100)
!2839 = !DIGlobalVariableExpression(var: !2840, expr: !DIExpression())
!2840 = distinct !DIGlobalVariable(scope: null, file: !52, line: 100, type: !2841, isLocal: true, isDefinition: true)
!2841 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 400, elements: !2842)
!2842 = !{!2843}
!2843 = !DISubrange(count: 50)
!2844 = !DIGlobalVariableExpression(var: !2845, expr: !DIExpression())
!2845 = distinct !DIGlobalVariable(scope: null, file: !52, line: 100, type: !2846, isLocal: true, isDefinition: true)
!2846 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 2280, elements: !2847)
!2847 = !{!2848}
!2848 = !DISubrange(count: 285)
!2849 = !DIGlobalVariableExpression(var: !2850, expr: !DIExpression())
!2850 = distinct !DIGlobalVariable(scope: null, file: !52, line: 108, type: !2851, isLocal: true, isDefinition: true)
!2851 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 2848, elements: !2852)
!2852 = !{!2853}
!2853 = !DISubrange(count: 356)
!2854 = !DIGlobalVariableExpression(var: !2855, expr: !DIExpression())
!2855 = distinct !DIGlobalVariable(scope: null, file: !52, line: 111, type: !2856, isLocal: true, isDefinition: true)
!2856 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 224, elements: !2857)
!2857 = !{!2858}
!2858 = !DISubrange(count: 28)
!2859 = !DIGlobalVariableExpression(var: !2860, expr: !DIExpression())
!2860 = distinct !DIGlobalVariable(scope: null, file: !52, line: 111, type: !2861, isLocal: true, isDefinition: true)
!2861 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 464, elements: !2862)
!2862 = !{!2863}
!2863 = !DISubrange(count: 58)
!2864 = !DIGlobalVariableExpression(var: !2865, expr: !DIExpression())
!2865 = distinct !DIGlobalVariable(scope: null, file: !787, line: 221, type: !2866, isLocal: true, isDefinition: true)
!2866 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 776, elements: !2867)
!2867 = !{!2868}
!2868 = !DISubrange(count: 97)
!2869 = !DIGlobalVariableExpression(var: !2870, expr: !DIExpression())
!2870 = distinct !DIGlobalVariable(scope: null, file: !787, line: 222, type: !2871, isLocal: true, isDefinition: true)
!2871 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 152, elements: !2872)
!2872 = !{!2873}
!2873 = !DISubrange(count: 19)
!2874 = !DIGlobalVariableExpression(var: !2875, expr: !DIExpression())
!2875 = distinct !DIGlobalVariable(scope: null, file: !787, line: 222, type: !2792, isLocal: true, isDefinition: true)
!2876 = !DIGlobalVariableExpression(var: !2877, expr: !DIExpression())
!2877 = distinct !DIGlobalVariable(scope: null, file: !757, line: 478, type: !2878, isLocal: true, isDefinition: true)
!2878 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 432, elements: !2879)
!2879 = !{!2880}
!2880 = !DISubrange(count: 54)
!2881 = !DIGlobalVariableExpression(var: !2882, expr: !DIExpression())
!2882 = distinct !DIGlobalVariable(scope: null, file: !757, line: 478, type: !2883, isLocal: true, isDefinition: true)
!2883 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 1072, elements: !2884)
!2884 = !{!2885}
!2885 = !DISubrange(count: 134)
!2886 = !DIGlobalVariableExpression(var: !2887, expr: !DIExpression())
!2887 = distinct !DIGlobalVariable(scope: null, file: !757, line: 478, type: !2888, isLocal: true, isDefinition: true)
!2888 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 352, elements: !2889)
!2889 = !{!2890}
!2890 = !DISubrange(count: 44)
!2891 = !DIGlobalVariableExpression(var: !2892, expr: !DIExpression())
!2892 = distinct !DIGlobalVariable(scope: null, file: !757, line: 478, type: !2893, isLocal: true, isDefinition: true)
!2893 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 4632, elements: !2894)
!2894 = !{!2895}
!2895 = !DISubrange(count: 579)
!2896 = !DIGlobalVariableExpression(var: !2897, expr: !DIExpression())
!2897 = distinct !DIGlobalVariable(scope: null, file: !757, line: 445, type: !2898, isLocal: true, isDefinition: true)
!2898 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 80, elements: !2899)
!2899 = !{!2900}
!2900 = !DISubrange(count: 10)
!2901 = !DIGlobalVariableExpression(var: !2902, expr: !DIExpression())
!2902 = distinct !DIGlobalVariable(scope: null, file: !757, line: 445, type: !2903, isLocal: true, isDefinition: true)
!2903 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 4368, elements: !2904)
!2904 = !{!2905}
!2905 = !DISubrange(count: 546)
!2906 = !DIGlobalVariableExpression(var: !2907, expr: !DIExpression())
!2907 = distinct !DIGlobalVariable(scope: null, file: !757, line: 623, type: !2908, isLocal: true, isDefinition: true)
!2908 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 64, elements: !951)
!2909 = !DIGlobalVariableExpression(var: !2910, expr: !DIExpression())
!2910 = distinct !DIGlobalVariable(scope: null, file: !757, line: 623, type: !2911, isLocal: true, isDefinition: true)
!2911 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 1984, elements: !2912)
!2912 = !{!2913}
!2913 = !DISubrange(count: 248)
!2914 = !DIGlobalVariableExpression(var: !2915, expr: !DIExpression())
!2915 = distinct !DIGlobalVariable(scope: null, file: !757, line: 271, type: !2916, isLocal: true, isDefinition: true)
!2916 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 336, elements: !2917)
!2917 = !{!2918}
!2918 = !DISubrange(count: 42)
!2919 = !DIGlobalVariableExpression(var: !2920, expr: !DIExpression())
!2920 = distinct !DIGlobalVariable(scope: null, file: !757, line: 271, type: !2921, isLocal: true, isDefinition: true)
!2921 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 736, elements: !2922)
!2922 = !{!2923}
!2923 = !DISubrange(count: 92)
!2924 = !DIGlobalVariableExpression(var: !2925, expr: !DIExpression())
!2925 = distinct !DIGlobalVariable(scope: null, file: !757, line: 271, type: !2926, isLocal: true, isDefinition: true)
!2926 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 3744, elements: !2927)
!2927 = !{!2928}
!2928 = !DISubrange(count: 468)
!2929 = !DIGlobalVariableExpression(var: !2930, expr: !DIExpression())
!2930 = distinct !DIGlobalVariable(scope: null, file: !757, line: 291, type: !2931, isLocal: true, isDefinition: true)
!2931 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 192, elements: !2932)
!2932 = !{!2933}
!2933 = !DISubrange(count: 24)
!2934 = !DIGlobalVariableExpression(var: !2935, expr: !DIExpression())
!2935 = distinct !DIGlobalVariable(scope: null, file: !757, line: 291, type: !2936, isLocal: true, isDefinition: true)
!2936 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 312, elements: !2937)
!2937 = !{!2938}
!2938 = !DISubrange(count: 39)
!2939 = !DIGlobalVariableExpression(var: !2940, expr: !DIExpression())
!2940 = distinct !DIGlobalVariable(scope: null, file: !757, line: 291, type: !2941, isLocal: true, isDefinition: true)
!2941 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 4296, elements: !2942)
!2942 = !{!2943}
!2943 = !DISubrange(count: 537)
!2944 = !DIGlobalVariableExpression(var: !2945, expr: !DIExpression())
!2945 = distinct !DIGlobalVariable(scope: null, file: !787, line: 213, type: !2718, isLocal: true, isDefinition: true)
!2946 = !DIGlobalVariableExpression(var: !2947, expr: !DIExpression())
!2947 = distinct !DIGlobalVariable(scope: null, file: !787, line: 214, type: !2948, isLocal: true, isDefinition: true)
!2948 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 456, elements: !2949)
!2949 = !{!2950}
!2950 = !DISubrange(count: 57)
!2951 = !DIGlobalVariableExpression(var: !2952, expr: !DIExpression())
!2952 = distinct !DIGlobalVariable(scope: null, file: !757, line: 478, type: !2953, isLocal: true, isDefinition: true)
!2953 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 4088, elements: !2954)
!2954 = !{!2955}
!2955 = !DISubrange(count: 511)
!2956 = !DIGlobalVariableExpression(var: !2957, expr: !DIExpression())
!2957 = distinct !DIGlobalVariable(scope: null, file: !757, line: 445, type: !2958, isLocal: true, isDefinition: true)
!2958 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 3824, elements: !2959)
!2959 = !{!2960}
!2960 = !DISubrange(count: 478)
!2961 = !DIGlobalVariableExpression(var: !2962, expr: !DIExpression())
!2962 = distinct !DIGlobalVariable(scope: null, file: !757, line: 623, type: !2963, isLocal: true, isDefinition: true)
!2963 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 1712, elements: !2964)
!2964 = !{!2965}
!2965 = !DISubrange(count: 214)
!2966 = !DIGlobalVariableExpression(var: !2967, expr: !DIExpression())
!2967 = distinct !DIGlobalVariable(scope: null, file: !757, line: 271, type: !2968, isLocal: true, isDefinition: true)
!2968 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 3200, elements: !2969)
!2969 = !{!2970}
!2970 = !DISubrange(count: 400)
!2971 = !DIGlobalVariableExpression(var: !2972, expr: !DIExpression())
!2972 = distinct !DIGlobalVariable(scope: null, file: !757, line: 291, type: !2973, isLocal: true, isDefinition: true)
!2973 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 3752, elements: !2974)
!2974 = !{!2975}
!2975 = !DISubrange(count: 469)
!2976 = !DIGlobalVariableExpression(var: !2977, expr: !DIExpression())
!2977 = distinct !DIGlobalVariable(scope: null, file: !2978, line: 67, type: !2979, isLocal: true, isDefinition: true)
!2978 = !DIFile(filename: "llvm34/include/llvm/ADT/OwningPtr.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "aca248455b073d207b4725e6c25cc91c")
!2979 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 256, elements: !2980)
!2980 = !{!2981}
!2981 = !DISubrange(count: 32)
!2982 = !DIGlobalVariableExpression(var: !2983, expr: !DIExpression())
!2983 = distinct !DIGlobalVariable(scope: null, file: !2978, line: 67, type: !2984, isLocal: true, isDefinition: true)
!2984 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 328, elements: !2985)
!2985 = !{!2986}
!2986 = !DISubrange(count: 41)
!2987 = !DIGlobalVariableExpression(var: !2988, expr: !DIExpression())
!2988 = distinct !DIGlobalVariable(scope: null, file: !2978, line: 67, type: !2785, isLocal: true, isDefinition: true)
!2989 = !DIGlobalVariableExpression(var: !2990, expr: !DIExpression())
!2990 = distinct !DIGlobalVariable(scope: null, file: !2978, line: 67, type: !2991, isLocal: true, isDefinition: true)
!2991 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 696, elements: !2992)
!2992 = !{!2993}
!2993 = !DISubrange(count: 87)
!2994 = !DIGlobalVariableExpression(var: !2995, expr: !DIExpression())
!2995 = distinct !DIGlobalVariable(scope: null, file: !787, line: 278, type: !2770, isLocal: true, isDefinition: true)
!2996 = !DIGlobalVariableExpression(var: !2997, expr: !DIExpression())
!2997 = distinct !DIGlobalVariable(scope: null, file: !2998, line: 511, type: !2999, isLocal: true, isDefinition: true)
!2998 = !DIFile(filename: "llvm34/projects/clang/include/clang/AST/VTableBuilder.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "1965b04bb922003dac5bddde46ca8973")
!2999 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 264, elements: !3000)
!3000 = !{!3001}
!3001 = !DISubrange(count: 33)
!3002 = !DIGlobalVariableExpression(var: !3003, expr: !DIExpression())
!3003 = distinct !DIGlobalVariable(scope: null, file: !2998, line: 511, type: !3004, isLocal: true, isDefinition: true)
!3004 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 560, elements: !3005)
!3005 = !{!3006}
!3006 = !DISubrange(count: 70)
!3007 = !DIGlobalVariableExpression(var: !3008, expr: !DIExpression())
!3008 = distinct !DIGlobalVariable(scope: null, file: !2998, line: 511, type: !2693, isLocal: true, isDefinition: true)
!3009 = !DIGlobalVariableExpression(var: !3010, expr: !DIExpression())
!3010 = distinct !DIGlobalVariable(scope: null, file: !2998, line: 511, type: !3011, isLocal: true, isDefinition: true)
!3011 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 960, elements: !3012)
!3012 = !{!3013}
!3013 = !DISubrange(count: 120)
!3014 = !DIGlobalVariableExpression(var: !3015, expr: !DIExpression())
!3015 = distinct !DIGlobalVariable(scope: null, file: !757, line: 478, type: !3016, isLocal: true, isDefinition: true)
!3016 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 6256, elements: !3017)
!3017 = !{!3018}
!3018 = !DISubrange(count: 782)
!3019 = !DIGlobalVariableExpression(var: !3020, expr: !DIExpression())
!3020 = distinct !DIGlobalVariable(scope: null, file: !757, line: 445, type: !3021, isLocal: true, isDefinition: true)
!3021 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 5664, elements: !3022)
!3022 = !{!3023}
!3023 = !DISubrange(count: 708)
!3024 = !DIGlobalVariableExpression(var: !3025, expr: !DIExpression())
!3025 = distinct !DIGlobalVariable(scope: null, file: !757, line: 623, type: !3026, isLocal: true, isDefinition: true)
!3026 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 2632, elements: !3027)
!3027 = !{!3028}
!3028 = !DISubrange(count: 329)
!3029 = !DIGlobalVariableExpression(var: !3030, expr: !DIExpression())
!3030 = distinct !DIGlobalVariable(scope: null, file: !757, line: 271, type: !3031, isLocal: true, isDefinition: true)
!3031 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 5040, elements: !3032)
!3032 = !{!3033}
!3033 = !DISubrange(count: 630)
!3034 = !DIGlobalVariableExpression(var: !3035, expr: !DIExpression())
!3035 = distinct !DIGlobalVariable(scope: null, file: !757, line: 291, type: !3036, isLocal: true, isDefinition: true)
!3036 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 5592, elements: !3037)
!3037 = !{!3038}
!3038 = !DISubrange(count: 699)
!3039 = !DIGlobalVariableExpression(var: !3040, expr: !DIExpression())
!3040 = distinct !DIGlobalVariable(scope: null, file: !1261, line: 239, type: !2916, isLocal: true, isDefinition: true)
!3041 = !DIGlobalVariableExpression(var: !3042, expr: !DIExpression())
!3042 = distinct !DIGlobalVariable(scope: null, file: !1261, line: 239, type: !2792, isLocal: true, isDefinition: true)
!3043 = !DIGlobalVariableExpression(var: !3044, expr: !DIExpression())
!3044 = distinct !DIGlobalVariable(scope: null, file: !1261, line: 239, type: !2760, isLocal: true, isDefinition: true)
!3045 = !DIGlobalVariableExpression(var: !3046, expr: !DIExpression())
!3046 = distinct !DIGlobalVariable(scope: null, file: !1261, line: 239, type: !3047, isLocal: true, isDefinition: true)
!3047 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 752, elements: !3048)
!3048 = !{!3049}
!3049 = !DISubrange(count: 94)
!3050 = !DIGlobalVariableExpression(var: !3051, expr: !DIExpression())
!3051 = distinct !DIGlobalVariable(scope: null, file: !1261, line: 97, type: !2683, isLocal: true, isDefinition: true)
!3052 = !DIGlobalVariableExpression(var: !3053, expr: !DIExpression())
!3053 = distinct !DIGlobalVariable(scope: null, file: !1261, line: 97, type: !3054, isLocal: true, isDefinition: true)
!3054 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 304, elements: !3055)
!3055 = !{!3056}
!3056 = !DISubrange(count: 38)
!3057 = !DIGlobalVariableExpression(var: !3058, expr: !DIExpression())
!3058 = distinct !DIGlobalVariable(scope: null, file: !1261, line: 97, type: !2723, isLocal: true, isDefinition: true)
!3059 = !DIGlobalVariableExpression(var: !3060, expr: !DIExpression())
!3060 = distinct !DIGlobalVariable(scope: null, file: !2101, line: 85, type: !2802, isLocal: true, isDefinition: true)
!3061 = !DIGlobalVariableExpression(var: !3062, expr: !DIExpression())
!3062 = distinct !DIGlobalVariable(scope: null, file: !2101, line: 85, type: !3063, isLocal: true, isDefinition: true)
!3063 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 760, elements: !3064)
!3064 = !{!3065}
!3065 = !DISubrange(count: 95)
!3066 = !DIGlobalVariableExpression(var: !3067, expr: !DIExpression())
!3067 = distinct !DIGlobalVariable(scope: null, file: !2101, line: 85, type: !2785, isLocal: true, isDefinition: true)
!3068 = !DIGlobalVariableExpression(var: !3069, expr: !DIExpression())
!3069 = distinct !DIGlobalVariable(scope: null, file: !2101, line: 85, type: !2775, isLocal: true, isDefinition: true)
!3070 = !DIGlobalVariableExpression(var: !3071, expr: !DIExpression())
!3071 = distinct !DIGlobalVariable(scope: null, file: !1261, line: 239, type: !2921, isLocal: true, isDefinition: true)
!3072 = !DIGlobalVariableExpression(var: !3073, expr: !DIExpression())
!3073 = distinct !DIGlobalVariable(scope: null, file: !1261, line: 97, type: !3074, isLocal: true, isDefinition: true)
!3074 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 1096, elements: !3075)
!3075 = !{!3076}
!3076 = !DISubrange(count: 137)
!3077 = !DIGlobalVariableExpression(var: !3078, expr: !DIExpression())
!3078 = distinct !DIGlobalVariable(scope: null, file: !555, line: 67, type: !3079, isLocal: true, isDefinition: true)
!3079 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 296, elements: !3080)
!3080 = !{!3081}
!3081 = !DISubrange(count: 37)
!3082 = !DIGlobalVariableExpression(var: !3083, expr: !DIExpression())
!3083 = distinct !DIGlobalVariable(scope: null, file: !555, line: 67, type: !3084, isLocal: true, isDefinition: true)
!3084 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 704, elements: !3085)
!3085 = !{!3086}
!3086 = !DISubrange(count: 88)
!3087 = !DIGlobalVariableExpression(var: !3088, expr: !DIExpression())
!3088 = distinct !DIGlobalVariable(scope: null, file: !555, line: 67, type: !2760, isLocal: true, isDefinition: true)
!3089 = !DIGlobalVariableExpression(var: !3090, expr: !DIExpression())
!3090 = distinct !DIGlobalVariable(scope: null, file: !555, line: 67, type: !2802, isLocal: true, isDefinition: true)
!3091 = !DIGlobalVariableExpression(var: !3092, expr: !DIExpression())
!3092 = distinct !DIGlobalVariable(scope: null, file: !3093, line: 423, type: !2703, isLocal: true, isDefinition: true)
!3093 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/vector.tcc", directory: "", checksumkind: CSK_MD5, checksum: "d0546ffb79f08cabb1d395ee56a00a29")
!3094 = !DIGlobalVariableExpression(var: !3095, expr: !DIExpression())
!3095 = distinct !DIGlobalVariable(scope: null, file: !914, line: 140, type: !3096, isLocal: true, isDefinition: true)
!3096 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 176, elements: !3097)
!3097 = !{!3098}
!3098 = !DISubrange(count: 22)
!3099 = !DIGlobalVariableExpression(var: !3100, expr: !DIExpression())
!3100 = distinct !DIGlobalVariable(scope: null, file: !914, line: 140, type: !2760, isLocal: true, isDefinition: true)
!3101 = !DIGlobalVariableExpression(var: !3102, expr: !DIExpression())
!3102 = distinct !DIGlobalVariable(scope: null, file: !914, line: 140, type: !3103, isLocal: true, isDefinition: true)
!3103 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 1344, elements: !3104)
!3104 = !{!3105}
!3105 = !DISubrange(count: 168)
!3106 = !DIGlobalVariableExpression(var: !3107, expr: !DIExpression())
!3107 = distinct !DIGlobalVariable(scope: null, file: !914, line: 158, type: !3108, isLocal: true, isDefinition: true)
!3108 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 72, elements: !3109)
!3109 = !{!3110}
!3110 = !DISubrange(count: 9)
!3111 = !DIGlobalVariableExpression(var: !3112, expr: !DIExpression())
!3112 = distinct !DIGlobalVariable(scope: null, file: !914, line: 158, type: !3113, isLocal: true, isDefinition: true)
!3113 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 1200, elements: !3114)
!3114 = !{!3115}
!3115 = !DISubrange(count: 150)
!3116 = !DIGlobalVariableExpression(var: !3117, expr: !DIExpression())
!3117 = distinct !DIGlobalVariable(scope: null, file: !1261, line: 232, type: !3118, isLocal: true, isDefinition: true)
!3118 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 912, elements: !3119)
!3119 = !{!3120}
!3120 = !DISubrange(count: 114)
!3121 = !DIGlobalVariableExpression(var: !3122, expr: !DIExpression())
!3122 = distinct !DIGlobalVariable(scope: null, file: !914, line: 140, type: !3123, isLocal: true, isDefinition: true)
!3123 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 1136, elements: !3124)
!3124 = !{!3125}
!3125 = !DISubrange(count: 142)
!3126 = !DIGlobalVariableExpression(var: !3127, expr: !DIExpression())
!3127 = distinct !DIGlobalVariable(scope: null, file: !1261, line: 239, type: !3128, isLocal: true, isDefinition: true)
!3128 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 808, elements: !3129)
!3129 = !{!3130}
!3130 = !DISubrange(count: 101)
!3131 = !DIGlobalVariableExpression(var: !3132, expr: !DIExpression())
!3132 = distinct !DIGlobalVariable(scope: null, file: !1261, line: 97, type: !3133, isLocal: true, isDefinition: true)
!3133 = !DICompositeType(tag: DW_TAG_array_type, baseType: !457, size: 1240, elements: !3134)
!3134 = !{!3135}
!3135 = !DISubrange(count: 155)
!3136 = !{!3137, !3143, !3150, !3152, !3154, !3158, !3160, !3162, !3164, !3166, !3168, !3170, !3172, !3177, !3181, !3183, !3185, !3190, !3192, !3194, !3196, !3198, !3200, !3202, !3205, !3208, !3210, !3214, !3219, !3221, !3223, !3225, !3227, !3229, !3231, !3233, !3235, !3237, !3239, !3243, !3247, !3249, !3251, !3253, !3255, !3257, !3259, !3261, !3263, !3265, !3267, !3269, !3271, !3273, !3275, !3277, !3281, !3285, !3289, !3291, !3293, !3295, !3297, !3299, !3301, !3303, !3305, !3307, !3311, !3315, !3319, !3321, !3323, !3325, !3330, !3334, !3338, !3340, !3342, !3344, !3346, !3348, !3350, !3352, !3354, !3356, !3358, !3360, !3362, !3366, !3370, !3374, !3376, !3378, !3380, !3384, !3388, !3392, !3394, !3396, !3398, !3400, !3402, !3404, !3408, !3412, !3414, !3416, !3418, !3420, !3424, !3428, !3432, !3434, !3436, !3438, !3440, !3442, !3444, !3448, !3452, !3456, !3458, !3462, !3466, !3468, !3470, !3472, !3474, !3476, !3478, !3483, !3489, !3493, !3499, !3503, !3507, !3513, !3517, !3519, !3521, !3525, !3529, !3533, !3537, !3539, !3541, !3543, !3545, !3549, !3553, !3557, !3559, !3561, !3565, !3569, !3575, !3579, !3584, !3586, !3589, !3593, !3597, !3606, !3610, !3614, !3618, !3622, !3626, !3630, !3634, !3638, !3642, !3649, !3653, !3657, !3659, !3663, !3667, !3671, !3677, !3681, !3685, !3687, !3694, !3698, !3704, !3706, !3710, !3714, !3718, !3722, !3727, !3731, !3735, !3736, !3737, !3738, !3740, !3741, !3742, !3743, !3744, !3745, !3746, !3750, !3754, !3769, !3772, !3777, !3828, !3833, !3837, !3841, !3845, !3849, !3851, !3853, !3857, !3863, !3867, !3873, !3879, !3881, !3885, !3889, !3893, !3897, !3909, !3911, !3915, !3919, !3923, !3925, !3929, !3933, !3937, !3939, !3941, !3945, !3953, !3957, !3961, !3965, !3967, !3973, !3975, !3981, !3985, !3989, !3993, !3997, !4001, !4005, !4007, !4009, !4013, !4017, !4021, !4023, !4027, !4031, !4033, !4035, !4039, !4043, !4047, !4051, !4052, !4053, !4054, !4055, !4056, !4057, !4058, !4059, !4060, !4061, !4065, !4069, !4072, !4073, !4075, !4077, !4079, !4081, !4083, !4085, !4087, !4089, !4092, !4093, !4097, !4100, !4103, !4104, !4106, !4108, !4110, !4112, !4114, !4116, !4118, !4120, !4123, !4124, !4128, !4132, !4137, !4141, !4143, !4145, !4147, !4149, !4151, !4153, !4155, !4157, !4159, !4161, !4163, !4165, !4167, !4169, !4170, !4174, !4180, !4185, !4189, !4191, !4193, !4195, !4197, !4204, !4208, !4212, !4216, !4220, !4224, !4228, !4232, !4234, !4238, !4244, !4248, !4252, !4254, !4257, !4261, !4265, !4267, !4269, !4271, !4273, !4275, !4277, !4279, !4283, !4287, !4291, !4295, !4299, !4303, !4305, !4309, !4313, !4317, !4321, !4323, !4325, !4329, !4333, !4334, !4335, !4336, !4337, !4338, !4344, !4347, !4348, !4350, !4352, !4354, !4356, !4360, !4362, !4364, !4366, !4368, !4370, !4372, !4374, !4376, !4380, !4384, !4386, !4390, !4394, !4395, !4396, !4398, !4399, !4401, !4404, !4409, !4413, !4414, !4419, !4423, !4428, !4433, !4437, !4443, !4447, !4449}
!3137 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3138, file: !3142, line: 52)
!3138 = !DISubprogram(name: "abs", scope: !3139, file: !3139, line: 837, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3139 = !DIFile(filename: "/usr/include/stdlib.h", directory: "", checksumkind: CSK_MD5, checksum: "69d942f1572b8bd342d93c49f499f318")
!3140 = !DISubroutineType(types: !3141)
!3141 = !{!701, !701}
!3142 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h", directory: "")
!3143 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3144, file: !3149, line: 83)
!3144 = !DISubprogram(name: "acos", scope: !3145, file: !3145, line: 53, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3145 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", directory: "", checksumkind: CSK_MD5, checksum: "540523e6856cf8d57a3ebef5fd79793e")
!3146 = !DISubroutineType(types: !3147)
!3147 = !{!3148, !3148}
!3148 = !DIBasicType(name: "double", size: 64, encoding: DW_ATE_float)
!3149 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cmath", directory: "")
!3150 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3151, file: !3149, line: 102)
!3151 = !DISubprogram(name: "asin", scope: !3145, file: !3145, line: 55, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3152 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3153, file: !3149, line: 121)
!3153 = !DISubprogram(name: "atan", scope: !3145, file: !3145, line: 57, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3154 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3155, file: !3149, line: 140)
!3155 = !DISubprogram(name: "atan2", scope: !3145, file: !3145, line: 59, type: !3156, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3156 = !DISubroutineType(types: !3157)
!3157 = !{!3148, !3148, !3148}
!3158 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3159, file: !3149, line: 161)
!3159 = !DISubprogram(name: "ceil", scope: !3145, file: !3145, line: 159, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3160 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3161, file: !3149, line: 180)
!3161 = !DISubprogram(name: "cos", scope: !3145, file: !3145, line: 62, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3162 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3163, file: !3149, line: 199)
!3163 = !DISubprogram(name: "cosh", scope: !3145, file: !3145, line: 71, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3164 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3165, file: !3149, line: 218)
!3165 = !DISubprogram(name: "exp", scope: !3145, file: !3145, line: 95, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3166 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3167, file: !3149, line: 237)
!3167 = !DISubprogram(name: "fabs", scope: !3145, file: !3145, line: 162, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3168 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3169, file: !3149, line: 256)
!3169 = !DISubprogram(name: "floor", scope: !3145, file: !3145, line: 165, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3170 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3171, file: !3149, line: 275)
!3171 = !DISubprogram(name: "fmod", scope: !3145, file: !3145, line: 168, type: !3156, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3172 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3173, file: !3149, line: 296)
!3173 = !DISubprogram(name: "frexp", scope: !3145, file: !3145, line: 98, type: !3174, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3174 = !DISubroutineType(types: !3175)
!3175 = !{!3148, !3148, !3176}
!3176 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !701, size: 64)
!3177 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3178, file: !3149, line: 315)
!3178 = !DISubprogram(name: "ldexp", scope: !3145, file: !3145, line: 101, type: !3179, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3179 = !DISubroutineType(types: !3180)
!3180 = !{!3148, !3148, !701}
!3181 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3182, file: !3149, line: 334)
!3182 = !DISubprogram(name: "log", scope: !3145, file: !3145, line: 104, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3183 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3184, file: !3149, line: 353)
!3184 = !DISubprogram(name: "log10", scope: !3145, file: !3145, line: 107, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3185 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3186, file: !3149, line: 372)
!3186 = !DISubprogram(name: "modf", scope: !3145, file: !3145, line: 110, type: !3187, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3187 = !DISubroutineType(types: !3188)
!3188 = !{!3148, !3148, !3189}
!3189 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3148, size: 64)
!3190 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3191, file: !3149, line: 384)
!3191 = !DISubprogram(name: "pow", scope: !3145, file: !3145, line: 140, type: !3156, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3192 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3193, file: !3149, line: 421)
!3193 = !DISubprogram(name: "sin", scope: !3145, file: !3145, line: 64, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3194 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3195, file: !3149, line: 440)
!3195 = !DISubprogram(name: "sinh", scope: !3145, file: !3145, line: 73, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3196 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3197, file: !3149, line: 459)
!3197 = !DISubprogram(name: "sqrt", scope: !3145, file: !3145, line: 143, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3198 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3199, file: !3149, line: 478)
!3199 = !DISubprogram(name: "tan", scope: !3145, file: !3145, line: 66, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3200 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3201, file: !3149, line: 497)
!3201 = !DISubprogram(name: "tanh", scope: !3145, file: !3145, line: 75, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3202 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3203, file: !3149, line: 1065)
!3203 = !DIDerivedType(tag: DW_TAG_typedef, name: "double_t", file: !3204, line: 150, baseType: !3148)
!3204 = !DIFile(filename: "/usr/include/math.h", directory: "", checksumkind: CSK_MD5, checksum: "ecf196918078d683ff91ad9a1c51599a")
!3205 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3206, file: !3149, line: 1066)
!3206 = !DIDerivedType(tag: DW_TAG_typedef, name: "float_t", file: !3204, line: 149, baseType: !3207)
!3207 = !DIBasicType(name: "float", size: 32, encoding: DW_ATE_float)
!3208 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3209, file: !3149, line: 1069)
!3209 = !DISubprogram(name: "acosh", scope: !3145, file: !3145, line: 85, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3210 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3211, file: !3149, line: 1070)
!3211 = !DISubprogram(name: "acoshf", scope: !3145, file: !3145, line: 85, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3212 = !DISubroutineType(types: !3213)
!3213 = !{!3207, !3207}
!3214 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3215, file: !3149, line: 1071)
!3215 = !DISubprogram(name: "acoshl", scope: !3145, file: !3145, line: 85, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3216 = !DISubroutineType(types: !3217)
!3217 = !{!3218, !3218}
!3218 = !DIBasicType(name: "long double", size: 128, encoding: DW_ATE_float)
!3219 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3220, file: !3149, line: 1073)
!3220 = !DISubprogram(name: "asinh", scope: !3145, file: !3145, line: 87, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3221 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3222, file: !3149, line: 1074)
!3222 = !DISubprogram(name: "asinhf", scope: !3145, file: !3145, line: 87, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3223 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3224, file: !3149, line: 1075)
!3224 = !DISubprogram(name: "asinhl", scope: !3145, file: !3145, line: 87, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3225 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3226, file: !3149, line: 1077)
!3226 = !DISubprogram(name: "atanh", scope: !3145, file: !3145, line: 89, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3227 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3228, file: !3149, line: 1078)
!3228 = !DISubprogram(name: "atanhf", scope: !3145, file: !3145, line: 89, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3229 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3230, file: !3149, line: 1079)
!3230 = !DISubprogram(name: "atanhl", scope: !3145, file: !3145, line: 89, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3231 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3232, file: !3149, line: 1081)
!3232 = !DISubprogram(name: "cbrt", scope: !3145, file: !3145, line: 152, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3233 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3234, file: !3149, line: 1082)
!3234 = !DISubprogram(name: "cbrtf", scope: !3145, file: !3145, line: 152, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3235 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3236, file: !3149, line: 1083)
!3236 = !DISubprogram(name: "cbrtl", scope: !3145, file: !3145, line: 152, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3237 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3238, file: !3149, line: 1085)
!3238 = !DISubprogram(name: "copysign", scope: !3145, file: !3145, line: 196, type: !3156, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3239 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3240, file: !3149, line: 1086)
!3240 = !DISubprogram(name: "copysignf", scope: !3145, file: !3145, line: 196, type: !3241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3241 = !DISubroutineType(types: !3242)
!3242 = !{!3207, !3207, !3207}
!3243 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3244, file: !3149, line: 1087)
!3244 = !DISubprogram(name: "copysignl", scope: !3145, file: !3145, line: 196, type: !3245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3245 = !DISubroutineType(types: !3246)
!3246 = !{!3218, !3218, !3218}
!3247 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3248, file: !3149, line: 1089)
!3248 = !DISubprogram(name: "erf", scope: !3145, file: !3145, line: 228, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3249 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3250, file: !3149, line: 1090)
!3250 = !DISubprogram(name: "erff", scope: !3145, file: !3145, line: 228, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3251 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3252, file: !3149, line: 1091)
!3252 = !DISubprogram(name: "erfl", scope: !3145, file: !3145, line: 228, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3253 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3254, file: !3149, line: 1093)
!3254 = !DISubprogram(name: "erfc", scope: !3145, file: !3145, line: 229, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3255 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3256, file: !3149, line: 1094)
!3256 = !DISubprogram(name: "erfcf", scope: !3145, file: !3145, line: 229, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3257 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3258, file: !3149, line: 1095)
!3258 = !DISubprogram(name: "erfcl", scope: !3145, file: !3145, line: 229, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3259 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3260, file: !3149, line: 1097)
!3260 = !DISubprogram(name: "exp2", scope: !3145, file: !3145, line: 130, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3261 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3262, file: !3149, line: 1098)
!3262 = !DISubprogram(name: "exp2f", scope: !3145, file: !3145, line: 130, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3263 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3264, file: !3149, line: 1099)
!3264 = !DISubprogram(name: "exp2l", scope: !3145, file: !3145, line: 130, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3265 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3266, file: !3149, line: 1101)
!3266 = !DISubprogram(name: "expm1", scope: !3145, file: !3145, line: 119, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3267 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3268, file: !3149, line: 1102)
!3268 = !DISubprogram(name: "expm1f", scope: !3145, file: !3145, line: 119, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3269 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3270, file: !3149, line: 1103)
!3270 = !DISubprogram(name: "expm1l", scope: !3145, file: !3145, line: 119, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3271 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3272, file: !3149, line: 1105)
!3272 = !DISubprogram(name: "fdim", scope: !3145, file: !3145, line: 326, type: !3156, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3273 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3274, file: !3149, line: 1106)
!3274 = !DISubprogram(name: "fdimf", scope: !3145, file: !3145, line: 326, type: !3241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3275 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3276, file: !3149, line: 1107)
!3276 = !DISubprogram(name: "fdiml", scope: !3145, file: !3145, line: 326, type: !3245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3277 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3278, file: !3149, line: 1109)
!3278 = !DISubprogram(name: "fma", scope: !3145, file: !3145, line: 335, type: !3279, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3279 = !DISubroutineType(types: !3280)
!3280 = !{!3148, !3148, !3148, !3148}
!3281 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3282, file: !3149, line: 1110)
!3282 = !DISubprogram(name: "fmaf", scope: !3145, file: !3145, line: 335, type: !3283, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3283 = !DISubroutineType(types: !3284)
!3284 = !{!3207, !3207, !3207, !3207}
!3285 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3286, file: !3149, line: 1111)
!3286 = !DISubprogram(name: "fmal", scope: !3145, file: !3145, line: 335, type: !3287, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3287 = !DISubroutineType(types: !3288)
!3288 = !{!3218, !3218, !3218, !3218}
!3289 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3290, file: !3149, line: 1113)
!3290 = !DISubprogram(name: "fmax", scope: !3145, file: !3145, line: 329, type: !3156, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3291 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3292, file: !3149, line: 1114)
!3292 = !DISubprogram(name: "fmaxf", scope: !3145, file: !3145, line: 329, type: !3241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3293 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3294, file: !3149, line: 1115)
!3294 = !DISubprogram(name: "fmaxl", scope: !3145, file: !3145, line: 329, type: !3245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3295 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3296, file: !3149, line: 1117)
!3296 = !DISubprogram(name: "fmin", scope: !3145, file: !3145, line: 332, type: !3156, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3297 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3298, file: !3149, line: 1118)
!3298 = !DISubprogram(name: "fminf", scope: !3145, file: !3145, line: 332, type: !3241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3299 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3300, file: !3149, line: 1119)
!3300 = !DISubprogram(name: "fminl", scope: !3145, file: !3145, line: 332, type: !3245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3301 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3302, file: !3149, line: 1121)
!3302 = !DISubprogram(name: "hypot", scope: !3145, file: !3145, line: 147, type: !3156, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3303 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3304, file: !3149, line: 1122)
!3304 = !DISubprogram(name: "hypotf", scope: !3145, file: !3145, line: 147, type: !3241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3305 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3306, file: !3149, line: 1123)
!3306 = !DISubprogram(name: "hypotl", scope: !3145, file: !3145, line: 147, type: !3245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3307 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3308, file: !3149, line: 1125)
!3308 = !DISubprogram(name: "ilogb", scope: !3145, file: !3145, line: 280, type: !3309, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3309 = !DISubroutineType(types: !3310)
!3310 = !{!701, !3148}
!3311 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3312, file: !3149, line: 1126)
!3312 = !DISubprogram(name: "ilogbf", scope: !3145, file: !3145, line: 280, type: !3313, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3313 = !DISubroutineType(types: !3314)
!3314 = !{!701, !3207}
!3315 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3316, file: !3149, line: 1127)
!3316 = !DISubprogram(name: "ilogbl", scope: !3145, file: !3145, line: 280, type: !3317, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3317 = !DISubroutineType(types: !3318)
!3318 = !{!701, !3218}
!3319 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3320, file: !3149, line: 1129)
!3320 = !DISubprogram(name: "lgamma", scope: !3145, file: !3145, line: 230, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3321 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3322, file: !3149, line: 1130)
!3322 = !DISubprogram(name: "lgammaf", scope: !3145, file: !3145, line: 230, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3323 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3324, file: !3149, line: 1131)
!3324 = !DISubprogram(name: "lgammal", scope: !3145, file: !3145, line: 230, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3325 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3326, file: !3149, line: 1134)
!3326 = !DISubprogram(name: "llrint", scope: !3145, file: !3145, line: 316, type: !3327, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3327 = !DISubroutineType(types: !3328)
!3328 = !{!3329, !3148}
!3329 = !DIBasicType(name: "long long", size: 64, encoding: DW_ATE_signed)
!3330 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3331, file: !3149, line: 1135)
!3331 = !DISubprogram(name: "llrintf", scope: !3145, file: !3145, line: 316, type: !3332, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3332 = !DISubroutineType(types: !3333)
!3333 = !{!3329, !3207}
!3334 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3335, file: !3149, line: 1136)
!3335 = !DISubprogram(name: "llrintl", scope: !3145, file: !3145, line: 316, type: !3336, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3336 = !DISubroutineType(types: !3337)
!3337 = !{!3329, !3218}
!3338 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3339, file: !3149, line: 1138)
!3339 = !DISubprogram(name: "llround", scope: !3145, file: !3145, line: 322, type: !3327, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3340 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3341, file: !3149, line: 1139)
!3341 = !DISubprogram(name: "llroundf", scope: !3145, file: !3145, line: 322, type: !3332, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3342 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3343, file: !3149, line: 1140)
!3343 = !DISubprogram(name: "llroundl", scope: !3145, file: !3145, line: 322, type: !3336, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3344 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3345, file: !3149, line: 1143)
!3345 = !DISubprogram(name: "log1p", scope: !3145, file: !3145, line: 122, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3346 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3347, file: !3149, line: 1144)
!3347 = !DISubprogram(name: "log1pf", scope: !3145, file: !3145, line: 122, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3348 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3349, file: !3149, line: 1145)
!3349 = !DISubprogram(name: "log1pl", scope: !3145, file: !3145, line: 122, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3350 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3351, file: !3149, line: 1147)
!3351 = !DISubprogram(name: "log2", scope: !3145, file: !3145, line: 133, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3352 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3353, file: !3149, line: 1148)
!3353 = !DISubprogram(name: "log2f", scope: !3145, file: !3145, line: 133, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3354 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3355, file: !3149, line: 1149)
!3355 = !DISubprogram(name: "log2l", scope: !3145, file: !3145, line: 133, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3356 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3357, file: !3149, line: 1151)
!3357 = !DISubprogram(name: "logb", scope: !3145, file: !3145, line: 125, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3358 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3359, file: !3149, line: 1152)
!3359 = !DISubprogram(name: "logbf", scope: !3145, file: !3145, line: 125, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3360 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3361, file: !3149, line: 1153)
!3361 = !DISubprogram(name: "logbl", scope: !3145, file: !3145, line: 125, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3362 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3363, file: !3149, line: 1155)
!3363 = !DISubprogram(name: "lrint", scope: !3145, file: !3145, line: 314, type: !3364, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3364 = !DISubroutineType(types: !3365)
!3365 = !{!58, !3148}
!3366 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3367, file: !3149, line: 1156)
!3367 = !DISubprogram(name: "lrintf", scope: !3145, file: !3145, line: 314, type: !3368, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3368 = !DISubroutineType(types: !3369)
!3369 = !{!58, !3207}
!3370 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3371, file: !3149, line: 1157)
!3371 = !DISubprogram(name: "lrintl", scope: !3145, file: !3145, line: 314, type: !3372, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3372 = !DISubroutineType(types: !3373)
!3373 = !{!58, !3218}
!3374 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3375, file: !3149, line: 1159)
!3375 = !DISubprogram(name: "lround", scope: !3145, file: !3145, line: 320, type: !3364, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3376 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3377, file: !3149, line: 1160)
!3377 = !DISubprogram(name: "lroundf", scope: !3145, file: !3145, line: 320, type: !3368, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3378 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3379, file: !3149, line: 1161)
!3379 = !DISubprogram(name: "lroundl", scope: !3145, file: !3145, line: 320, type: !3372, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3380 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3381, file: !3149, line: 1163)
!3381 = !DISubprogram(name: "nan", scope: !3145, file: !3145, line: 201, type: !3382, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3382 = !DISubroutineType(types: !3383)
!3383 = !{!3148, !456}
!3384 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3385, file: !3149, line: 1164)
!3385 = !DISubprogram(name: "nanf", scope: !3145, file: !3145, line: 201, type: !3386, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3386 = !DISubroutineType(types: !3387)
!3387 = !{!3207, !456}
!3388 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3389, file: !3149, line: 1165)
!3389 = !DISubprogram(name: "nanl", scope: !3145, file: !3145, line: 201, type: !3390, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3390 = !DISubroutineType(types: !3391)
!3391 = !{!3218, !456}
!3392 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3393, file: !3149, line: 1167)
!3393 = !DISubprogram(name: "nearbyint", scope: !3145, file: !3145, line: 294, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3394 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3395, file: !3149, line: 1168)
!3395 = !DISubprogram(name: "nearbyintf", scope: !3145, file: !3145, line: 294, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3396 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3397, file: !3149, line: 1169)
!3397 = !DISubprogram(name: "nearbyintl", scope: !3145, file: !3145, line: 294, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3398 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3399, file: !3149, line: 1171)
!3399 = !DISubprogram(name: "nextafter", scope: !3145, file: !3145, line: 259, type: !3156, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3400 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3401, file: !3149, line: 1172)
!3401 = !DISubprogram(name: "nextafterf", scope: !3145, file: !3145, line: 259, type: !3241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3402 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3403, file: !3149, line: 1173)
!3403 = !DISubprogram(name: "nextafterl", scope: !3145, file: !3145, line: 259, type: !3245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3404 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3405, file: !3149, line: 1175)
!3405 = !DISubprogram(name: "nexttoward", scope: !3145, file: !3145, line: 261, type: !3406, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3406 = !DISubroutineType(types: !3407)
!3407 = !{!3148, !3148, !3218}
!3408 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3409, file: !3149, line: 1176)
!3409 = !DISubprogram(name: "nexttowardf", scope: !3145, file: !3145, line: 261, type: !3410, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3410 = !DISubroutineType(types: !3411)
!3411 = !{!3207, !3207, !3218}
!3412 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3413, file: !3149, line: 1177)
!3413 = !DISubprogram(name: "nexttowardl", scope: !3145, file: !3145, line: 261, type: !3245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3414 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3415, file: !3149, line: 1179)
!3415 = !DISubprogram(name: "remainder", scope: !3145, file: !3145, line: 272, type: !3156, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3416 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3417, file: !3149, line: 1180)
!3417 = !DISubprogram(name: "remainderf", scope: !3145, file: !3145, line: 272, type: !3241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3418 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3419, file: !3149, line: 1181)
!3419 = !DISubprogram(name: "remainderl", scope: !3145, file: !3145, line: 272, type: !3245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3420 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3421, file: !3149, line: 1183)
!3421 = !DISubprogram(name: "remquo", scope: !3145, file: !3145, line: 307, type: !3422, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3422 = !DISubroutineType(types: !3423)
!3423 = !{!3148, !3148, !3148, !3176}
!3424 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3425, file: !3149, line: 1184)
!3425 = !DISubprogram(name: "remquof", scope: !3145, file: !3145, line: 307, type: !3426, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3426 = !DISubroutineType(types: !3427)
!3427 = !{!3207, !3207, !3207, !3176}
!3428 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3429, file: !3149, line: 1185)
!3429 = !DISubprogram(name: "remquol", scope: !3145, file: !3145, line: 307, type: !3430, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3430 = !DISubroutineType(types: !3431)
!3431 = !{!3218, !3218, !3218, !3176}
!3432 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3433, file: !3149, line: 1187)
!3433 = !DISubprogram(name: "rint", scope: !3145, file: !3145, line: 256, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3434 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3435, file: !3149, line: 1188)
!3435 = !DISubprogram(name: "rintf", scope: !3145, file: !3145, line: 256, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3436 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3437, file: !3149, line: 1189)
!3437 = !DISubprogram(name: "rintl", scope: !3145, file: !3145, line: 256, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3438 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3439, file: !3149, line: 1191)
!3439 = !DISubprogram(name: "round", scope: !3145, file: !3145, line: 298, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3440 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3441, file: !3149, line: 1192)
!3441 = !DISubprogram(name: "roundf", scope: !3145, file: !3145, line: 298, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3442 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3443, file: !3149, line: 1193)
!3443 = !DISubprogram(name: "roundl", scope: !3145, file: !3145, line: 298, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3444 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3445, file: !3149, line: 1195)
!3445 = !DISubprogram(name: "scalbln", scope: !3145, file: !3145, line: 290, type: !3446, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3446 = !DISubroutineType(types: !3447)
!3447 = !{!3148, !3148, !58}
!3448 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3449, file: !3149, line: 1196)
!3449 = !DISubprogram(name: "scalblnf", scope: !3145, file: !3145, line: 290, type: !3450, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3450 = !DISubroutineType(types: !3451)
!3451 = !{!3207, !3207, !58}
!3452 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3453, file: !3149, line: 1197)
!3453 = !DISubprogram(name: "scalblnl", scope: !3145, file: !3145, line: 290, type: !3454, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3454 = !DISubroutineType(types: !3455)
!3455 = !{!3218, !3218, !58}
!3456 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3457, file: !3149, line: 1199)
!3457 = !DISubprogram(name: "scalbn", scope: !3145, file: !3145, line: 276, type: !3179, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3458 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3459, file: !3149, line: 1200)
!3459 = !DISubprogram(name: "scalbnf", scope: !3145, file: !3145, line: 276, type: !3460, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3460 = !DISubroutineType(types: !3461)
!3461 = !{!3207, !3207, !701}
!3462 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3463, file: !3149, line: 1201)
!3463 = !DISubprogram(name: "scalbnl", scope: !3145, file: !3145, line: 276, type: !3464, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3464 = !DISubroutineType(types: !3465)
!3465 = !{!3218, !3218, !701}
!3466 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3467, file: !3149, line: 1203)
!3467 = !DISubprogram(name: "tgamma", scope: !3145, file: !3145, line: 235, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3468 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3469, file: !3149, line: 1204)
!3469 = !DISubprogram(name: "tgammaf", scope: !3145, file: !3145, line: 235, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3470 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3471, file: !3149, line: 1205)
!3471 = !DISubprogram(name: "tgammal", scope: !3145, file: !3145, line: 235, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3472 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3473, file: !3149, line: 1207)
!3473 = !DISubprogram(name: "trunc", scope: !3145, file: !3145, line: 302, type: !3146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3474 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3475, file: !3149, line: 1208)
!3475 = !DISubprogram(name: "truncf", scope: !3145, file: !3145, line: 302, type: !3212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3476 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3477, file: !3149, line: 1209)
!3477 = !DISubprogram(name: "truncl", scope: !3145, file: !3145, line: 302, type: !3216, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3478 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3479, file: !3482, line: 56)
!3479 = !DIDerivedType(tag: DW_TAG_typedef, name: "max_align_t", file: !3480, line: 24, baseType: !3481)
!3480 = !DIFile(filename: "llvm5/build/lib/clang/15.0.3/include/__stddef_max_align_t.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "48e8e2456f77e6cda35d245130fa7259")
!3481 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !3480, line: 19, size: 256, flags: DIFlagFwdDecl, identifier: "_ZTS11max_align_t")
!3482 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstddef", directory: "")
!3483 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3484, file: !3488, line: 75)
!3484 = !DISubprogram(name: "memchr", scope: !3485, file: !3485, line: 90, type: !3486, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3485 = !DIFile(filename: "/usr/include/string.h", directory: "", checksumkind: CSK_MD5, checksum: "1029a2d94b0e7b73f8dbf87ca20ab7bc")
!3486 = !DISubroutineType(types: !3487)
!3487 = !{!81, !117, !701, !927}
!3488 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstring", directory: "")
!3489 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3490, file: !3488, line: 76)
!3490 = !DISubprogram(name: "memcmp", scope: !3485, file: !3485, line: 63, type: !3491, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3491 = !DISubroutineType(types: !3492)
!3492 = !{!701, !117, !117, !927}
!3493 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3494, file: !3488, line: 77)
!3494 = !DISubprogram(name: "memcpy", scope: !3485, file: !3485, line: 42, type: !3495, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3495 = !DISubroutineType(types: !3496)
!3496 = !{!81, !3497, !3498, !927}
!3497 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !81)
!3498 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !117)
!3499 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3500, file: !3488, line: 78)
!3500 = !DISubprogram(name: "memmove", scope: !3485, file: !3485, line: 46, type: !3501, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3501 = !DISubroutineType(types: !3502)
!3502 = !{!81, !81, !117, !927}
!3503 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3504, file: !3488, line: 79)
!3504 = !DISubprogram(name: "memset", scope: !3485, file: !3485, line: 60, type: !3505, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3505 = !DISubroutineType(types: !3506)
!3506 = !{!81, !81, !701, !927}
!3507 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3508, file: !3488, line: 80)
!3508 = !DISubprogram(name: "strcat", scope: !3485, file: !3485, line: 129, type: !3509, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3509 = !DISubroutineType(types: !3510)
!3510 = !{!746, !3511, !3512}
!3511 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !746)
!3512 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !456)
!3513 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3514, file: !3488, line: 81)
!3514 = !DISubprogram(name: "strcmp", scope: !3485, file: !3485, line: 136, type: !3515, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3515 = !DISubroutineType(types: !3516)
!3516 = !{!701, !456, !456}
!3517 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3518, file: !3488, line: 82)
!3518 = !DISubprogram(name: "strcoll", scope: !3485, file: !3485, line: 143, type: !3515, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3519 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3520, file: !3488, line: 83)
!3520 = !DISubprogram(name: "strcpy", scope: !3485, file: !3485, line: 121, type: !3509, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3521 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3522, file: !3488, line: 84)
!3522 = !DISubprogram(name: "strcspn", scope: !3485, file: !3485, line: 272, type: !3523, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3523 = !DISubroutineType(types: !3524)
!3524 = !{!927, !456, !456}
!3525 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3526, file: !3488, line: 85)
!3526 = !DISubprogram(name: "strerror", scope: !3485, file: !3485, line: 396, type: !3527, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3527 = !DISubroutineType(types: !3528)
!3528 = !{!746, !701}
!3529 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3530, file: !3488, line: 86)
!3530 = !DISubprogram(name: "strlen", scope: !3485, file: !3485, line: 384, type: !3531, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3531 = !DISubroutineType(types: !3532)
!3532 = !{!927, !456}
!3533 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3534, file: !3488, line: 87)
!3534 = !DISubprogram(name: "strncat", scope: !3485, file: !3485, line: 132, type: !3535, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3535 = !DISubroutineType(types: !3536)
!3536 = !{!746, !3511, !3512, !927}
!3537 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3538, file: !3488, line: 88)
!3538 = !DISubprogram(name: "strncmp", scope: !3485, file: !3485, line: 139, type: !2112, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3539 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3540, file: !3488, line: 89)
!3540 = !DISubprogram(name: "strncpy", scope: !3485, file: !3485, line: 124, type: !3535, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3541 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3542, file: !3488, line: 90)
!3542 = !DISubprogram(name: "strspn", scope: !3485, file: !3485, line: 276, type: !3523, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3543 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3544, file: !3488, line: 91)
!3544 = !DISubprogram(name: "strtok", scope: !3485, file: !3485, line: 335, type: !3509, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3545 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3546, file: !3488, line: 92)
!3546 = !DISubprogram(name: "strxfrm", scope: !3485, file: !3485, line: 146, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3547 = !DISubroutineType(types: !3548)
!3548 = !{!927, !3511, !3512, !927}
!3549 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3550, file: !3488, line: 93)
!3550 = !DISubprogram(name: "strchr", scope: !3485, file: !3485, line: 225, type: !3551, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3551 = !DISubroutineType(types: !3552)
!3552 = !{!746, !456, !701}
!3553 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3554, file: !3488, line: 94)
!3554 = !DISubprogram(name: "strpbrk", scope: !3485, file: !3485, line: 302, type: !3555, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3555 = !DISubroutineType(types: !3556)
!3556 = !{!746, !456, !456}
!3557 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3558, file: !3488, line: 95)
!3558 = !DISubprogram(name: "strrchr", scope: !3485, file: !3485, line: 252, type: !3551, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3559 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3560, file: !3488, line: 96)
!3560 = !DISubprogram(name: "strstr", scope: !3485, file: !3485, line: 329, type: !3555, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3561 = !DIImportedEntity(tag: DW_TAG_imported_module, scope: !3562, entity: !3563, file: !3564, line: 58)
!3562 = !DINamespace(name: "__gnu_debug", scope: null)
!3563 = !DINamespace(name: "__debug", scope: !408)
!3564 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/debug/debug.h", directory: "", checksumkind: CSK_MD5, checksum: "0d648599b52b1d377b1fee4a0a4b2b91")
!3565 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3566, file: !3568, line: 127)
!3566 = !DIDerivedType(tag: DW_TAG_typedef, name: "div_t", file: !3139, line: 62, baseType: !3567)
!3567 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !3139, line: 58, size: 64, flags: DIFlagFwdDecl, identifier: "_ZTS5div_t")
!3568 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdlib", directory: "")
!3569 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3570, file: !3568, line: 128)
!3570 = !DIDerivedType(tag: DW_TAG_typedef, name: "ldiv_t", file: !3139, line: 70, baseType: !3571)
!3571 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !3139, line: 66, size: 128, flags: DIFlagTypePassByValue, elements: !3572, identifier: "_ZTS6ldiv_t")
!3572 = !{!3573, !3574}
!3573 = !DIDerivedType(tag: DW_TAG_member, name: "quot", scope: !3571, file: !3139, line: 68, baseType: !58, size: 64)
!3574 = !DIDerivedType(tag: DW_TAG_member, name: "rem", scope: !3571, file: !3139, line: 69, baseType: !58, size: 64, offset: 64)
!3575 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3576, file: !3568, line: 130)
!3576 = !DISubprogram(name: "abort", scope: !3139, file: !3139, line: 588, type: !3577, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!3577 = !DISubroutineType(types: !3578)
!3578 = !{null}
!3579 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3580, file: !3568, line: 134)
!3580 = !DISubprogram(name: "atexit", scope: !3139, file: !3139, line: 592, type: !3581, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3581 = !DISubroutineType(types: !3582)
!3582 = !{!701, !3583}
!3583 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3577, size: 64)
!3584 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3585, file: !3568, line: 137)
!3585 = !DISubprogram(name: "at_quick_exit", scope: !3139, file: !3139, line: 597, type: !3581, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3586 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3587, file: !3568, line: 140)
!3587 = !DISubprogram(name: "atof", scope: !3588, file: !3588, line: 25, type: !3382, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3588 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h", directory: "", checksumkind: CSK_MD5, checksum: "ce60958b260b171e83db3307f1d644f0")
!3589 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3590, file: !3568, line: 141)
!3590 = !DISubprogram(name: "atoi", scope: !3139, file: !3139, line: 361, type: !3591, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3591 = !DISubroutineType(types: !3592)
!3592 = !{!701, !456}
!3593 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3594, file: !3568, line: 142)
!3594 = !DISubprogram(name: "atol", scope: !3139, file: !3139, line: 366, type: !3595, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3595 = !DISubroutineType(types: !3596)
!3596 = !{!58, !456}
!3597 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3598, file: !3568, line: 143)
!3598 = !DISubprogram(name: "bsearch", scope: !3599, file: !3599, line: 20, type: !3600, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3599 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h", directory: "", checksumkind: CSK_MD5, checksum: "1a798a38b25adee7bb680abce9ef568a")
!3600 = !DISubroutineType(types: !3601)
!3601 = !{!81, !117, !117, !927, !927, !3602}
!3602 = !DIDerivedType(tag: DW_TAG_typedef, name: "__compar_fn_t", file: !3139, line: 805, baseType: !3603)
!3603 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3604, size: 64)
!3604 = !DISubroutineType(types: !3605)
!3605 = !{!701, !117, !117}
!3606 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3607, file: !3568, line: 144)
!3607 = !DISubprogram(name: "calloc", scope: !3139, file: !3139, line: 541, type: !3608, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3608 = !DISubroutineType(types: !3609)
!3609 = !{!81, !927, !927}
!3610 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3611, file: !3568, line: 145)
!3611 = !DISubprogram(name: "div", scope: !3139, file: !3139, line: 849, type: !3612, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3612 = !DISubroutineType(types: !3613)
!3613 = !{!3566, !701, !701}
!3614 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3615, file: !3568, line: 146)
!3615 = !DISubprogram(name: "exit", scope: !3139, file: !3139, line: 614, type: !3616, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!3616 = !DISubroutineType(types: !3617)
!3617 = !{null, !701}
!3618 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3619, file: !3568, line: 147)
!3619 = !DISubprogram(name: "free", scope: !3139, file: !3139, line: 563, type: !3620, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3620 = !DISubroutineType(types: !3621)
!3621 = !{null, !81}
!3622 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3623, file: !3568, line: 148)
!3623 = !DISubprogram(name: "getenv", scope: !3139, file: !3139, line: 631, type: !3624, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3624 = !DISubroutineType(types: !3625)
!3625 = !{!746, !456}
!3626 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3627, file: !3568, line: 149)
!3627 = !DISubprogram(name: "labs", scope: !3139, file: !3139, line: 838, type: !3628, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3628 = !DISubroutineType(types: !3629)
!3629 = !{!58, !58}
!3630 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3631, file: !3568, line: 150)
!3631 = !DISubprogram(name: "ldiv", scope: !3139, file: !3139, line: 851, type: !3632, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3632 = !DISubroutineType(types: !3633)
!3633 = !{!3570, !58, !58}
!3634 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3635, file: !3568, line: 151)
!3635 = !DISubprogram(name: "malloc", scope: !3139, file: !3139, line: 539, type: !3636, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3636 = !DISubroutineType(types: !3637)
!3637 = !{!81, !927}
!3638 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3639, file: !3568, line: 153)
!3639 = !DISubprogram(name: "mblen", scope: !3139, file: !3139, line: 919, type: !3640, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3640 = !DISubroutineType(types: !3641)
!3641 = !{!701, !456, !927}
!3642 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3643, file: !3568, line: 154)
!3643 = !DISubprogram(name: "mbstowcs", scope: !3139, file: !3139, line: 930, type: !3644, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3644 = !DISubroutineType(types: !3645)
!3645 = !{!927, !3646, !3512, !927}
!3646 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3647)
!3647 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3648, size: 64)
!3648 = !DIBasicType(name: "wchar_t", size: 32, encoding: DW_ATE_signed)
!3649 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3650, file: !3568, line: 155)
!3650 = !DISubprogram(name: "mbtowc", scope: !3139, file: !3139, line: 922, type: !3651, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3651 = !DISubroutineType(types: !3652)
!3652 = !{!701, !3646, !3512, !927}
!3653 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3654, file: !3568, line: 157)
!3654 = !DISubprogram(name: "qsort", scope: !3139, file: !3139, line: 827, type: !3655, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3655 = !DISubroutineType(types: !3656)
!3656 = !{null, !81, !927, !927, !3602}
!3657 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3658, file: !3568, line: 160)
!3658 = !DISubprogram(name: "quick_exit", scope: !3139, file: !3139, line: 620, type: !3616, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!3659 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3660, file: !3568, line: 163)
!3660 = !DISubprogram(name: "rand", scope: !3139, file: !3139, line: 453, type: !3661, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3661 = !DISubroutineType(types: !3662)
!3662 = !{!701}
!3663 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3664, file: !3568, line: 164)
!3664 = !DISubprogram(name: "realloc", scope: !3139, file: !3139, line: 549, type: !3665, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3665 = !DISubroutineType(types: !3666)
!3666 = !{!81, !81, !927}
!3667 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3668, file: !3568, line: 165)
!3668 = !DISubprogram(name: "srand", scope: !3139, file: !3139, line: 455, type: !3669, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3669 = !DISubroutineType(types: !3670)
!3670 = !{null, !6}
!3671 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3672, file: !3568, line: 166)
!3672 = !DISubprogram(name: "strtod", scope: !3139, file: !3139, line: 117, type: !3673, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3673 = !DISubroutineType(types: !3674)
!3674 = !{!3148, !3512, !3675}
!3675 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3676)
!3676 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !746, size: 64)
!3677 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3678, file: !3568, line: 167)
!3678 = !DISubprogram(name: "strtol", scope: !3139, file: !3139, line: 176, type: !3679, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3679 = !DISubroutineType(types: !3680)
!3680 = !{!58, !3512, !3675, !701}
!3681 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3682, file: !3568, line: 168)
!3682 = !DISubprogram(name: "strtoul", scope: !3139, file: !3139, line: 180, type: !3683, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3683 = !DISubroutineType(types: !3684)
!3684 = !{!249, !3512, !3675, !701}
!3685 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3686, file: !3568, line: 169)
!3686 = !DISubprogram(name: "system", scope: !3139, file: !3139, line: 781, type: !3591, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3687 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3688, file: !3568, line: 171)
!3688 = !DISubprogram(name: "wcstombs", scope: !3139, file: !3139, line: 933, type: !3689, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3689 = !DISubroutineType(types: !3690)
!3690 = !{!927, !3511, !3691, !927}
!3691 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3692)
!3692 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3693, size: 64)
!3693 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3648)
!3694 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3695, file: !3568, line: 172)
!3695 = !DISubprogram(name: "wctomb", scope: !3139, file: !3139, line: 926, type: !3696, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3696 = !DISubroutineType(types: !3697)
!3697 = !{!701, !746, !3648}
!3698 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3699, file: !3568, line: 200)
!3699 = !DIDerivedType(tag: DW_TAG_typedef, name: "lldiv_t", file: !3139, line: 80, baseType: !3700)
!3700 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !3139, line: 76, size: 128, flags: DIFlagTypePassByValue, elements: !3701, identifier: "_ZTS7lldiv_t")
!3701 = !{!3702, !3703}
!3702 = !DIDerivedType(tag: DW_TAG_member, name: "quot", scope: !3700, file: !3139, line: 78, baseType: !3329, size: 64)
!3703 = !DIDerivedType(tag: DW_TAG_member, name: "rem", scope: !3700, file: !3139, line: 79, baseType: !3329, size: 64, offset: 64)
!3704 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3705, file: !3568, line: 206)
!3705 = !DISubprogram(name: "_Exit", scope: !3139, file: !3139, line: 626, type: !3616, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!3706 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3707, file: !3568, line: 210)
!3707 = !DISubprogram(name: "llabs", scope: !3139, file: !3139, line: 841, type: !3708, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3708 = !DISubroutineType(types: !3709)
!3709 = !{!3329, !3329}
!3710 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3711, file: !3568, line: 216)
!3711 = !DISubprogram(name: "lldiv", scope: !3139, file: !3139, line: 855, type: !3712, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3712 = !DISubroutineType(types: !3713)
!3713 = !{!3699, !3329, !3329}
!3714 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3715, file: !3568, line: 227)
!3715 = !DISubprogram(name: "atoll", scope: !3139, file: !3139, line: 373, type: !3716, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3716 = !DISubroutineType(types: !3717)
!3717 = !{!3329, !456}
!3718 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3719, file: !3568, line: 228)
!3719 = !DISubprogram(name: "strtoll", scope: !3139, file: !3139, line: 200, type: !3720, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3720 = !DISubroutineType(types: !3721)
!3721 = !{!3329, !3512, !3675, !701}
!3722 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3723, file: !3568, line: 229)
!3723 = !DISubprogram(name: "strtoull", scope: !3139, file: !3139, line: 205, type: !3724, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3724 = !DISubroutineType(types: !3725)
!3725 = !{!3726, !3512, !3675, !701}
!3726 = !DIBasicType(name: "unsigned long long", size: 64, encoding: DW_ATE_unsigned)
!3727 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3728, file: !3568, line: 231)
!3728 = !DISubprogram(name: "strtof", scope: !3139, file: !3139, line: 123, type: !3729, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3729 = !DISubroutineType(types: !3730)
!3730 = !{!3207, !3512, !3675}
!3731 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3732, file: !3568, line: 232)
!3732 = !DISubprogram(name: "strtold", scope: !3139, file: !3139, line: 126, type: !3733, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3733 = !DISubroutineType(types: !3734)
!3734 = !{!3218, !3512, !3675}
!3735 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3699, file: !3568, line: 240)
!3736 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3705, file: !3568, line: 242)
!3737 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3707, file: !3568, line: 244)
!3738 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3739, file: !3568, line: 245)
!3739 = !DISubprogram(name: "div", linkageName: "_ZN9__gnu_cxx3divExx", scope: !5, file: !3568, line: 213, type: !3712, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3740 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3711, file: !3568, line: 246)
!3741 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3715, file: !3568, line: 248)
!3742 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3728, file: !3568, line: 249)
!3743 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3719, file: !3568, line: 250)
!3744 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3723, file: !3568, line: 251)
!3745 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3732, file: !3568, line: 252)
!3746 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3747, file: !3748, line: 57)
!3747 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "exception_ptr", scope: !3749, file: !3748, line: 79, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSNSt15__exception_ptr13exception_ptrE")
!3748 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/exception_ptr.h", directory: "", checksumkind: CSK_MD5, checksum: "25d44782b686509a9fc5c8aaa8066643")
!3749 = !DINamespace(name: "__exception_ptr", scope: !408)
!3750 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !3749, entity: !3751, file: !3748, line: 73)
!3751 = !DISubprogram(name: "rethrow_exception", linkageName: "_ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE", scope: !408, file: !3748, line: 69, type: !3752, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!3752 = !DISubroutineType(types: !3753)
!3753 = !{null, !3747}
!3754 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3755, file: !3768, line: 64)
!3755 = !DIDerivedType(tag: DW_TAG_typedef, name: "mbstate_t", file: !3756, line: 6, baseType: !3757)
!3756 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/mbstate_t.h", directory: "", checksumkind: CSK_MD5, checksum: "ba8742313715e20e434cf6ccb2db98e3")
!3757 = !DIDerivedType(tag: DW_TAG_typedef, name: "__mbstate_t", file: !3758, line: 21, baseType: !3759)
!3758 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h", directory: "", checksumkind: CSK_MD5, checksum: "82911a3e689448e3691ded3e0b471a55")
!3759 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !3758, line: 13, size: 64, flags: DIFlagTypePassByValue, elements: !3760, identifier: "_ZTS11__mbstate_t")
!3760 = !{!3761, !3762}
!3761 = !DIDerivedType(tag: DW_TAG_member, name: "__count", scope: !3759, file: !3758, line: 15, baseType: !701, size: 32)
!3762 = !DIDerivedType(tag: DW_TAG_member, name: "__value", scope: !3759, file: !3758, line: 20, baseType: !3763, size: 32, offset: 32)
!3763 = distinct !DICompositeType(tag: DW_TAG_union_type, scope: !3759, file: !3758, line: 16, size: 32, flags: DIFlagTypePassByValue, elements: !3764, identifier: "_ZTSN11__mbstate_tUt_E")
!3764 = !{!3765, !3766}
!3765 = !DIDerivedType(tag: DW_TAG_member, name: "__wch", scope: !3763, file: !3758, line: 18, baseType: !6, size: 32)
!3766 = !DIDerivedType(tag: DW_TAG_member, name: "__wchb", scope: !3763, file: !3758, line: 19, baseType: !3767, size: 32)
!3767 = !DICompositeType(tag: DW_TAG_array_type, baseType: !458, size: 32, elements: !618)
!3768 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cwchar", directory: "")
!3769 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3770, file: !3768, line: 139)
!3770 = !DIDerivedType(tag: DW_TAG_typedef, name: "wint_t", file: !3771, line: 20, baseType: !6)
!3771 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/wint_t.h", directory: "", checksumkind: CSK_MD5, checksum: "aa31b53ef28dc23152ceb41e2763ded3")
!3772 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3773, file: !3768, line: 141)
!3773 = !DISubprogram(name: "btowc", scope: !3774, file: !3774, line: 318, type: !3775, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3774 = !DIFile(filename: "/usr/include/wchar.h", directory: "", checksumkind: CSK_MD5, checksum: "5c0512b032e303d7adfb2a47454ecb1c")
!3775 = !DISubroutineType(types: !3776)
!3776 = !{!3770, !701}
!3777 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3778, file: !3768, line: 142)
!3778 = !DISubprogram(name: "fgetwc", scope: !3774, file: !3774, line: 727, type: !3779, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3779 = !DISubroutineType(types: !3780)
!3780 = !{!3770, !3781}
!3781 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3782, size: 64)
!3782 = !DIDerivedType(tag: DW_TAG_typedef, name: "__FILE", file: !3783, line: 5, baseType: !3784)
!3783 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h", directory: "", checksumkind: CSK_MD5, checksum: "72a8fe90981f484acae7c6f3dfc5c2b7")
!3784 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_IO_FILE", file: !3785, line: 245, size: 1728, flags: DIFlagTypePassByValue, elements: !3786, identifier: "_ZTS8_IO_FILE")
!3785 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/libio.h", directory: "", checksumkind: CSK_MD5, checksum: "e2b53e448ab24b9cd2ba8684267b8131")
!3786 = !{!3787, !3788, !3789, !3790, !3791, !3792, !3793, !3794, !3795, !3796, !3797, !3798, !3799, !3802, !3804, !3805, !3806, !3808, !3810, !3812, !3813, !3816, !3818, !3819, !3820, !3821, !3822, !3823, !3824}
!3787 = !DIDerivedType(tag: DW_TAG_member, name: "_flags", scope: !3784, file: !3785, line: 246, baseType: !701, size: 32)
!3788 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_ptr", scope: !3784, file: !3785, line: 251, baseType: !746, size: 64, offset: 64)
!3789 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_end", scope: !3784, file: !3785, line: 252, baseType: !746, size: 64, offset: 128)
!3790 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_base", scope: !3784, file: !3785, line: 253, baseType: !746, size: 64, offset: 192)
!3791 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_base", scope: !3784, file: !3785, line: 254, baseType: !746, size: 64, offset: 256)
!3792 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_ptr", scope: !3784, file: !3785, line: 255, baseType: !746, size: 64, offset: 320)
!3793 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_end", scope: !3784, file: !3785, line: 256, baseType: !746, size: 64, offset: 384)
!3794 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_buf_base", scope: !3784, file: !3785, line: 257, baseType: !746, size: 64, offset: 448)
!3795 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_buf_end", scope: !3784, file: !3785, line: 258, baseType: !746, size: 64, offset: 512)
!3796 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_save_base", scope: !3784, file: !3785, line: 260, baseType: !746, size: 64, offset: 576)
!3797 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_backup_base", scope: !3784, file: !3785, line: 261, baseType: !746, size: 64, offset: 640)
!3798 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_save_end", scope: !3784, file: !3785, line: 262, baseType: !746, size: 64, offset: 704)
!3799 = !DIDerivedType(tag: DW_TAG_member, name: "_markers", scope: !3784, file: !3785, line: 264, baseType: !3800, size: 64, offset: 768)
!3800 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3801, size: 64)
!3801 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_IO_marker", file: !3785, line: 160, size: 192, flags: DIFlagFwdDecl, identifier: "_ZTS10_IO_marker")
!3802 = !DIDerivedType(tag: DW_TAG_member, name: "_chain", scope: !3784, file: !3785, line: 266, baseType: !3803, size: 64, offset: 832)
!3803 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3784, size: 64)
!3804 = !DIDerivedType(tag: DW_TAG_member, name: "_fileno", scope: !3784, file: !3785, line: 268, baseType: !701, size: 32, offset: 896)
!3805 = !DIDerivedType(tag: DW_TAG_member, name: "_flags2", scope: !3784, file: !3785, line: 272, baseType: !701, size: 32, offset: 928)
!3806 = !DIDerivedType(tag: DW_TAG_member, name: "_old_offset", scope: !3784, file: !3785, line: 274, baseType: !3807, size: 64, offset: 960)
!3807 = !DIDerivedType(tag: DW_TAG_typedef, name: "__off_t", file: !674, line: 140, baseType: !58)
!3808 = !DIDerivedType(tag: DW_TAG_member, name: "_cur_column", scope: !3784, file: !3785, line: 278, baseType: !3809, size: 16, offset: 1024)
!3809 = !DIBasicType(name: "unsigned short", size: 16, encoding: DW_ATE_unsigned)
!3810 = !DIDerivedType(tag: DW_TAG_member, name: "_vtable_offset", scope: !3784, file: !3785, line: 279, baseType: !3811, size: 8, offset: 1040)
!3811 = !DIBasicType(name: "signed char", size: 8, encoding: DW_ATE_signed_char)
!3812 = !DIDerivedType(tag: DW_TAG_member, name: "_shortbuf", scope: !3784, file: !3785, line: 280, baseType: !1057, size: 8, offset: 1048)
!3813 = !DIDerivedType(tag: DW_TAG_member, name: "_lock", scope: !3784, file: !3785, line: 284, baseType: !3814, size: 64, offset: 1088)
!3814 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3815, size: 64)
!3815 = !DIDerivedType(tag: DW_TAG_typedef, name: "_IO_lock_t", file: !3785, line: 154, baseType: null)
!3816 = !DIDerivedType(tag: DW_TAG_member, name: "_offset", scope: !3784, file: !3785, line: 293, baseType: !3817, size: 64, offset: 1152)
!3817 = !DIDerivedType(tag: DW_TAG_typedef, name: "__off64_t", file: !674, line: 141, baseType: !58)
!3818 = !DIDerivedType(tag: DW_TAG_member, name: "__pad1", scope: !3784, file: !3785, line: 301, baseType: !81, size: 64, offset: 1216)
!3819 = !DIDerivedType(tag: DW_TAG_member, name: "__pad2", scope: !3784, file: !3785, line: 302, baseType: !81, size: 64, offset: 1280)
!3820 = !DIDerivedType(tag: DW_TAG_member, name: "__pad3", scope: !3784, file: !3785, line: 303, baseType: !81, size: 64, offset: 1344)
!3821 = !DIDerivedType(tag: DW_TAG_member, name: "__pad4", scope: !3784, file: !3785, line: 304, baseType: !81, size: 64, offset: 1408)
!3822 = !DIDerivedType(tag: DW_TAG_member, name: "__pad5", scope: !3784, file: !3785, line: 306, baseType: !927, size: 64, offset: 1472)
!3823 = !DIDerivedType(tag: DW_TAG_member, name: "_mode", scope: !3784, file: !3785, line: 307, baseType: !701, size: 32, offset: 1536)
!3824 = !DIDerivedType(tag: DW_TAG_member, name: "_unused2", scope: !3784, file: !3785, line: 309, baseType: !3825, size: 160, offset: 1568)
!3825 = !DICompositeType(tag: DW_TAG_array_type, baseType: !458, size: 160, elements: !3826)
!3826 = !{!3827}
!3827 = !DISubrange(count: 20)
!3828 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3829, file: !3768, line: 143)
!3829 = !DISubprogram(name: "fgetws", scope: !3774, file: !3774, line: 756, type: !3830, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3830 = !DISubroutineType(types: !3831)
!3831 = !{!3647, !3646, !701, !3832}
!3832 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3781)
!3833 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3834, file: !3768, line: 144)
!3834 = !DISubprogram(name: "fputwc", scope: !3774, file: !3774, line: 741, type: !3835, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3835 = !DISubroutineType(types: !3836)
!3836 = !{!3770, !3648, !3781}
!3837 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3838, file: !3768, line: 145)
!3838 = !DISubprogram(name: "fputws", scope: !3774, file: !3774, line: 763, type: !3839, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3839 = !DISubroutineType(types: !3840)
!3840 = !{!701, !3691, !3832}
!3841 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3842, file: !3768, line: 146)
!3842 = !DISubprogram(name: "fwide", scope: !3774, file: !3774, line: 573, type: !3843, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3843 = !DISubroutineType(types: !3844)
!3844 = !{!701, !3781, !701}
!3845 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3846, file: !3768, line: 147)
!3846 = !DISubprogram(name: "fwprintf", scope: !3774, file: !3774, line: 580, type: !3847, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3847 = !DISubroutineType(types: !3848)
!3848 = !{!701, !3832, !3691, null}
!3849 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3850, file: !3768, line: 148)
!3850 = !DISubprogram(name: "fwscanf", scope: !3774, file: !3774, line: 621, type: !3847, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3851 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3852, file: !3768, line: 149)
!3852 = !DISubprogram(name: "getwc", scope: !3774, file: !3774, line: 728, type: !3779, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3853 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3854, file: !3768, line: 150)
!3854 = !DISubprogram(name: "getwchar", scope: !3774, file: !3774, line: 734, type: !3855, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3855 = !DISubroutineType(types: !3856)
!3856 = !{!3770}
!3857 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3858, file: !3768, line: 151)
!3858 = !DISubprogram(name: "mbrlen", scope: !3774, file: !3774, line: 329, type: !3859, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3859 = !DISubroutineType(types: !3860)
!3860 = !{!927, !3512, !927, !3861}
!3861 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3862)
!3862 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3755, size: 64)
!3863 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3864, file: !3768, line: 152)
!3864 = !DISubprogram(name: "mbrtowc", scope: !3774, file: !3774, line: 296, type: !3865, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3865 = !DISubroutineType(types: !3866)
!3866 = !{!927, !3646, !3512, !927, !3861}
!3867 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3868, file: !3768, line: 153)
!3868 = !DISubprogram(name: "mbsinit", scope: !3774, file: !3774, line: 292, type: !3869, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3869 = !DISubroutineType(types: !3870)
!3870 = !{!701, !3871}
!3871 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3872, size: 64)
!3872 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3755)
!3873 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3874, file: !3768, line: 154)
!3874 = !DISubprogram(name: "mbsrtowcs", scope: !3774, file: !3774, line: 337, type: !3875, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3875 = !DISubroutineType(types: !3876)
!3876 = !{!927, !3646, !3877, !927, !3861}
!3877 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3878)
!3878 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !456, size: 64)
!3879 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3880, file: !3768, line: 155)
!3880 = !DISubprogram(name: "putwc", scope: !3774, file: !3774, line: 742, type: !3835, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3881 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3882, file: !3768, line: 156)
!3882 = !DISubprogram(name: "putwchar", scope: !3774, file: !3774, line: 748, type: !3883, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3883 = !DISubroutineType(types: !3884)
!3884 = !{!3770, !3648}
!3885 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3886, file: !3768, line: 158)
!3886 = !DISubprogram(name: "swprintf", scope: !3774, file: !3774, line: 590, type: !3887, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3887 = !DISubroutineType(types: !3888)
!3888 = !{!701, !3646, !927, !3691, null}
!3889 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3890, file: !3768, line: 160)
!3890 = !DISubprogram(name: "swscanf", scope: !3774, file: !3774, line: 631, type: !3891, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3891 = !DISubroutineType(types: !3892)
!3892 = !{!701, !3691, !3691, null}
!3893 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3894, file: !3768, line: 161)
!3894 = !DISubprogram(name: "ungetwc", scope: !3774, file: !3774, line: 771, type: !3895, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3895 = !DISubroutineType(types: !3896)
!3896 = !{!3770, !3770, !3781}
!3897 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3898, file: !3768, line: 162)
!3898 = !DISubprogram(name: "vfwprintf", scope: !3774, file: !3774, line: 598, type: !3899, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3899 = !DISubroutineType(types: !3900)
!3900 = !{!701, !3832, !3691, !3901}
!3901 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3902, size: 64)
!3902 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__va_list_tag", size: 192, flags: DIFlagTypePassByValue, elements: !3903, identifier: "_ZTS13__va_list_tag")
!3903 = !{!3904, !3906, !3907, !3908}
!3904 = !DIDerivedType(tag: DW_TAG_member, name: "gp_offset", scope: !3902, file: !3905, baseType: !6, size: 32)
!3905 = !DIFile(filename: "llvm34/projects/clang/lib/CodeGen/MicrosoftVBTables.cpp", directory: "/fast/fs")
!3906 = !DIDerivedType(tag: DW_TAG_member, name: "fp_offset", scope: !3902, file: !3905, baseType: !6, size: 32, offset: 32)
!3907 = !DIDerivedType(tag: DW_TAG_member, name: "overflow_arg_area", scope: !3902, file: !3905, baseType: !81, size: 64, offset: 64)
!3908 = !DIDerivedType(tag: DW_TAG_member, name: "reg_save_area", scope: !3902, file: !3905, baseType: !81, size: 64, offset: 128)
!3909 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3910, file: !3768, line: 164)
!3910 = !DISubprogram(name: "vfwscanf", scope: !3774, file: !3774, line: 673, type: !3899, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3911 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3912, file: !3768, line: 167)
!3912 = !DISubprogram(name: "vswprintf", scope: !3774, file: !3774, line: 611, type: !3913, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3913 = !DISubroutineType(types: !3914)
!3914 = !{!701, !3646, !927, !3691, !3901}
!3915 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3916, file: !3768, line: 170)
!3916 = !DISubprogram(name: "vswscanf", scope: !3774, file: !3774, line: 685, type: !3917, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3917 = !DISubroutineType(types: !3918)
!3918 = !{!701, !3691, !3691, !3901}
!3919 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3920, file: !3768, line: 172)
!3920 = !DISubprogram(name: "vwprintf", scope: !3774, file: !3774, line: 606, type: !3921, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3921 = !DISubroutineType(types: !3922)
!3922 = !{!701, !3691, !3901}
!3923 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3924, file: !3768, line: 174)
!3924 = !DISubprogram(name: "vwscanf", scope: !3774, file: !3774, line: 681, type: !3921, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3925 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3926, file: !3768, line: 176)
!3926 = !DISubprogram(name: "wcrtomb", scope: !3774, file: !3774, line: 301, type: !3927, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3927 = !DISubroutineType(types: !3928)
!3928 = !{!927, !3511, !3648, !3861}
!3929 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3930, file: !3768, line: 177)
!3930 = !DISubprogram(name: "wcscat", scope: !3774, file: !3774, line: 97, type: !3931, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3931 = !DISubroutineType(types: !3932)
!3932 = !{!3647, !3646, !3691}
!3933 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3934, file: !3768, line: 178)
!3934 = !DISubprogram(name: "wcscmp", scope: !3774, file: !3774, line: 106, type: !3935, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3935 = !DISubroutineType(types: !3936)
!3936 = !{!701, !3692, !3692}
!3937 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3938, file: !3768, line: 179)
!3938 = !DISubprogram(name: "wcscoll", scope: !3774, file: !3774, line: 131, type: !3935, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3939 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3940, file: !3768, line: 180)
!3940 = !DISubprogram(name: "wcscpy", scope: !3774, file: !3774, line: 87, type: !3931, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3941 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3942, file: !3768, line: 181)
!3942 = !DISubprogram(name: "wcscspn", scope: !3774, file: !3774, line: 187, type: !3943, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3943 = !DISubroutineType(types: !3944)
!3944 = !{!927, !3692, !3692}
!3945 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3946, file: !3768, line: 182)
!3946 = !DISubprogram(name: "wcsftime", scope: !3774, file: !3774, line: 835, type: !3947, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3947 = !DISubroutineType(types: !3948)
!3948 = !{!927, !3646, !927, !3691, !3949}
!3949 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3950)
!3950 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3951, size: 64)
!3951 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3952)
!3952 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "tm", file: !3774, line: 83, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTS2tm")
!3953 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3954, file: !3768, line: 183)
!3954 = !DISubprogram(name: "wcslen", scope: !3774, file: !3774, line: 222, type: !3955, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3955 = !DISubroutineType(types: !3956)
!3956 = !{!927, !3692}
!3957 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3958, file: !3768, line: 184)
!3958 = !DISubprogram(name: "wcsncat", scope: !3774, file: !3774, line: 101, type: !3959, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3959 = !DISubroutineType(types: !3960)
!3960 = !{!3647, !3646, !3691, !927}
!3961 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3962, file: !3768, line: 185)
!3962 = !DISubprogram(name: "wcsncmp", scope: !3774, file: !3774, line: 109, type: !3963, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3963 = !DISubroutineType(types: !3964)
!3964 = !{!701, !3692, !3692, !927}
!3965 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3966, file: !3768, line: 186)
!3966 = !DISubprogram(name: "wcsncpy", scope: !3774, file: !3774, line: 92, type: !3959, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3967 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3968, file: !3768, line: 187)
!3968 = !DISubprogram(name: "wcsrtombs", scope: !3774, file: !3774, line: 343, type: !3969, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3969 = !DISubroutineType(types: !3970)
!3970 = !{!927, !3511, !3971, !927, !3861}
!3971 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3972)
!3972 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3692, size: 64)
!3973 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3974, file: !3768, line: 188)
!3974 = !DISubprogram(name: "wcsspn", scope: !3774, file: !3774, line: 191, type: !3943, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3975 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3976, file: !3768, line: 189)
!3976 = !DISubprogram(name: "wcstod", scope: !3774, file: !3774, line: 377, type: !3977, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3977 = !DISubroutineType(types: !3978)
!3978 = !{!3148, !3691, !3979}
!3979 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3980)
!3980 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3647, size: 64)
!3981 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3982, file: !3768, line: 191)
!3982 = !DISubprogram(name: "wcstof", scope: !3774, file: !3774, line: 382, type: !3983, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3983 = !DISubroutineType(types: !3984)
!3984 = !{!3207, !3691, !3979}
!3985 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3986, file: !3768, line: 193)
!3986 = !DISubprogram(name: "wcstok", scope: !3774, file: !3774, line: 217, type: !3987, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3987 = !DISubroutineType(types: !3988)
!3988 = !{!3647, !3646, !3691, !3979}
!3989 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3990, file: !3768, line: 194)
!3990 = !DISubprogram(name: "wcstol", scope: !3774, file: !3774, line: 428, type: !3991, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3991 = !DISubroutineType(types: !3992)
!3992 = !{!58, !3691, !3979, !701}
!3993 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3994, file: !3768, line: 195)
!3994 = !DISubprogram(name: "wcstoul", scope: !3774, file: !3774, line: 433, type: !3995, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3995 = !DISubroutineType(types: !3996)
!3996 = !{!249, !3691, !3979, !701}
!3997 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3998, file: !3768, line: 196)
!3998 = !DISubprogram(name: "wcsxfrm", scope: !3774, file: !3774, line: 135, type: !3999, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3999 = !DISubroutineType(types: !4000)
!4000 = !{!927, !3646, !3691, !927}
!4001 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4002, file: !3768, line: 197)
!4002 = !DISubprogram(name: "wctob", scope: !3774, file: !3774, line: 324, type: !4003, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4003 = !DISubroutineType(types: !4004)
!4004 = !{!701, !3770}
!4005 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4006, file: !3768, line: 198)
!4006 = !DISubprogram(name: "wmemcmp", scope: !3774, file: !3774, line: 258, type: !3963, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4007 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4008, file: !3768, line: 199)
!4008 = !DISubprogram(name: "wmemcpy", scope: !3774, file: !3774, line: 262, type: !3959, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4009 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4010, file: !3768, line: 200)
!4010 = !DISubprogram(name: "wmemmove", scope: !3774, file: !3774, line: 267, type: !4011, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4011 = !DISubroutineType(types: !4012)
!4012 = !{!3647, !3647, !3692, !927}
!4013 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4014, file: !3768, line: 201)
!4014 = !DISubprogram(name: "wmemset", scope: !3774, file: !3774, line: 271, type: !4015, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4015 = !DISubroutineType(types: !4016)
!4016 = !{!3647, !3647, !3648, !927}
!4017 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4018, file: !3768, line: 202)
!4018 = !DISubprogram(name: "wprintf", scope: !3774, file: !3774, line: 587, type: !4019, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4019 = !DISubroutineType(types: !4020)
!4020 = !{!701, !3691, null}
!4021 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4022, file: !3768, line: 203)
!4022 = !DISubprogram(name: "wscanf", scope: !3774, file: !3774, line: 628, type: !4019, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4023 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4024, file: !3768, line: 204)
!4024 = !DISubprogram(name: "wcschr", scope: !3774, file: !3774, line: 164, type: !4025, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4025 = !DISubroutineType(types: !4026)
!4026 = !{!3647, !3692, !3648}
!4027 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4028, file: !3768, line: 205)
!4028 = !DISubprogram(name: "wcspbrk", scope: !3774, file: !3774, line: 201, type: !4029, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4029 = !DISubroutineType(types: !4030)
!4030 = !{!3647, !3692, !3692}
!4031 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4032, file: !3768, line: 206)
!4032 = !DISubprogram(name: "wcsrchr", scope: !3774, file: !3774, line: 174, type: !4025, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4033 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4034, file: !3768, line: 207)
!4034 = !DISubprogram(name: "wcsstr", scope: !3774, file: !3774, line: 212, type: !4029, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4035 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4036, file: !3768, line: 208)
!4036 = !DISubprogram(name: "wmemchr", scope: !3774, file: !3774, line: 253, type: !4037, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4037 = !DISubroutineType(types: !4038)
!4038 = !{!3647, !3692, !3648, !927}
!4039 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4040, file: !3768, line: 248)
!4040 = !DISubprogram(name: "wcstold", scope: !3774, file: !3774, line: 384, type: !4041, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4041 = !DISubroutineType(types: !4042)
!4042 = !{!3218, !3691, !3979}
!4043 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4044, file: !3768, line: 257)
!4044 = !DISubprogram(name: "wcstoll", scope: !3774, file: !3774, line: 441, type: !4045, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4045 = !DISubroutineType(types: !4046)
!4046 = !{!3329, !3691, !3979, !701}
!4047 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4048, file: !3768, line: 258)
!4048 = !DISubprogram(name: "wcstoull", scope: !3774, file: !3774, line: 448, type: !4049, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4049 = !DISubroutineType(types: !4050)
!4050 = !{!3726, !3691, !3979, !701}
!4051 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4040, file: !3768, line: 264)
!4052 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4044, file: !3768, line: 265)
!4053 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4048, file: !3768, line: 266)
!4054 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3982, file: !3768, line: 280)
!4055 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3910, file: !3768, line: 283)
!4056 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3916, file: !3768, line: 286)
!4057 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3924, file: !3768, line: 289)
!4058 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4040, file: !3768, line: 293)
!4059 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4044, file: !3768, line: 294)
!4060 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4048, file: !3768, line: 295)
!4061 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4062, file: !4064, line: 48)
!4062 = !DIDerivedType(tag: DW_TAG_typedef, name: "int8_t", file: !672, line: 24, baseType: !4063)
!4063 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int8_t", file: !674, line: 36, baseType: !3811)
!4064 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdint", directory: "")
!4065 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4066, file: !4064, line: 49)
!4066 = !DIDerivedType(tag: DW_TAG_typedef, name: "int16_t", file: !672, line: 25, baseType: !4067)
!4067 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int16_t", file: !674, line: 38, baseType: !4068)
!4068 = !DIBasicType(name: "short", size: 16, encoding: DW_ATE_signed)
!4069 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4070, file: !4064, line: 50)
!4070 = !DIDerivedType(tag: DW_TAG_typedef, name: "int32_t", file: !672, line: 26, baseType: !4071)
!4071 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int32_t", file: !674, line: 40, baseType: !701)
!4072 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !671, file: !4064, line: 51)
!4073 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4074, file: !4064, line: 53)
!4074 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast8_t", file: !57, line: 68, baseType: !3811)
!4075 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4076, file: !4064, line: 54)
!4076 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast16_t", file: !57, line: 70, baseType: !58)
!4077 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4078, file: !4064, line: 55)
!4078 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast32_t", file: !57, line: 71, baseType: !58)
!4079 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4080, file: !4064, line: 56)
!4080 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast64_t", file: !57, line: 72, baseType: !58)
!4081 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4082, file: !4064, line: 58)
!4082 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least8_t", file: !57, line: 43, baseType: !3811)
!4083 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4084, file: !4064, line: 59)
!4084 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least16_t", file: !57, line: 44, baseType: !4068)
!4085 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4086, file: !4064, line: 60)
!4086 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least32_t", file: !57, line: 45, baseType: !701)
!4087 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4088, file: !4064, line: 61)
!4088 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least64_t", file: !57, line: 47, baseType: !58)
!4089 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4090, file: !4064, line: 63)
!4090 = !DIDerivedType(tag: DW_TAG_typedef, name: "intmax_t", file: !57, line: 111, baseType: !4091)
!4091 = !DIDerivedType(tag: DW_TAG_typedef, name: "__intmax_t", file: !674, line: 61, baseType: !58)
!4092 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !56, file: !4064, line: 64)
!4093 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4094, file: !4064, line: 66)
!4094 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint8_t", file: !748, line: 24, baseType: !4095)
!4095 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint8_t", file: !674, line: 37, baseType: !4096)
!4096 = !DIBasicType(name: "unsigned char", size: 8, encoding: DW_ATE_unsigned_char)
!4097 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4098, file: !4064, line: 67)
!4098 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint16_t", file: !748, line: 25, baseType: !4099)
!4099 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint16_t", file: !674, line: 39, baseType: !3809)
!4100 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4101, file: !4064, line: 68)
!4101 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint32_t", file: !748, line: 26, baseType: !4102)
!4102 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint32_t", file: !674, line: 41, baseType: !6)
!4103 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !747, file: !4064, line: 69)
!4104 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4105, file: !4064, line: 71)
!4105 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast8_t", file: !57, line: 81, baseType: !4096)
!4106 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4107, file: !4064, line: 72)
!4107 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast16_t", file: !57, line: 83, baseType: !249)
!4108 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4109, file: !4064, line: 73)
!4109 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast32_t", file: !57, line: 84, baseType: !249)
!4110 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4111, file: !4064, line: 74)
!4111 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast64_t", file: !57, line: 85, baseType: !249)
!4112 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4113, file: !4064, line: 76)
!4113 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least8_t", file: !57, line: 54, baseType: !4096)
!4114 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4115, file: !4064, line: 77)
!4115 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least16_t", file: !57, line: 55, baseType: !3809)
!4116 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4117, file: !4064, line: 78)
!4117 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least32_t", file: !57, line: 56, baseType: !6)
!4118 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4119, file: !4064, line: 79)
!4119 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least64_t", file: !57, line: 58, baseType: !249)
!4120 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4121, file: !4064, line: 81)
!4121 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintmax_t", file: !57, line: 112, baseType: !4122)
!4122 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uintmax_t", file: !674, line: 62, baseType: !249)
!4123 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !248, file: !4064, line: 82)
!4124 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4125, file: !4127, line: 53)
!4125 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "lconv", file: !4126, line: 51, size: 768, flags: DIFlagFwdDecl, identifier: "_ZTS5lconv")
!4126 = !DIFile(filename: "/usr/include/locale.h", directory: "", checksumkind: CSK_MD5, checksum: "0595275e3f5b502d28f7cd61a0dff888")
!4127 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/clocale", directory: "")
!4128 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4129, file: !4127, line: 54)
!4129 = !DISubprogram(name: "setlocale", scope: !4126, file: !4126, line: 122, type: !4130, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4130 = !DISubroutineType(types: !4131)
!4131 = !{!746, !701, !456}
!4132 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4133, file: !4127, line: 55)
!4133 = !DISubprogram(name: "localeconv", scope: !4126, file: !4126, line: 125, type: !4134, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4134 = !DISubroutineType(types: !4135)
!4135 = !{!4136}
!4136 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4125, size: 64)
!4137 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4138, file: !4140, line: 64)
!4138 = !DISubprogram(name: "isalnum", scope: !4139, file: !4139, line: 108, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4139 = !DIFile(filename: "/usr/include/ctype.h", directory: "", checksumkind: CSK_MD5, checksum: "c67c809b09ef8ea9c273687bc20a7fd3")
!4140 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cctype", directory: "")
!4141 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4142, file: !4140, line: 65)
!4142 = !DISubprogram(name: "isalpha", scope: !4139, file: !4139, line: 109, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4143 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4144, file: !4140, line: 66)
!4144 = !DISubprogram(name: "iscntrl", scope: !4139, file: !4139, line: 110, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4145 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4146, file: !4140, line: 67)
!4146 = !DISubprogram(name: "isdigit", scope: !4139, file: !4139, line: 111, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4147 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4148, file: !4140, line: 68)
!4148 = !DISubprogram(name: "isgraph", scope: !4139, file: !4139, line: 113, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4149 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4150, file: !4140, line: 69)
!4150 = !DISubprogram(name: "islower", scope: !4139, file: !4139, line: 112, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4151 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4152, file: !4140, line: 70)
!4152 = !DISubprogram(name: "isprint", scope: !4139, file: !4139, line: 114, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4153 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4154, file: !4140, line: 71)
!4154 = !DISubprogram(name: "ispunct", scope: !4139, file: !4139, line: 115, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4155 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4156, file: !4140, line: 72)
!4156 = !DISubprogram(name: "isspace", scope: !4139, file: !4139, line: 116, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4157 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4158, file: !4140, line: 73)
!4158 = !DISubprogram(name: "isupper", scope: !4139, file: !4139, line: 117, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4159 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4160, file: !4140, line: 74)
!4160 = !DISubprogram(name: "isxdigit", scope: !4139, file: !4139, line: 118, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4161 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4162, file: !4140, line: 75)
!4162 = !DISubprogram(name: "tolower", scope: !4139, file: !4139, line: 122, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4163 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4164, file: !4140, line: 76)
!4164 = !DISubprogram(name: "toupper", scope: !4139, file: !4139, line: 125, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4165 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4166, file: !4140, line: 87)
!4166 = !DISubprogram(name: "isblank", scope: !4139, file: !4139, line: 130, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4167 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !1636, file: !4168, line: 44)
!4168 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/new_allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "ece13daf300dfc0cac27dc2ea29129ca")
!4169 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !1745, file: !4168, line: 45)
!4170 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4171, file: !4173, line: 98)
!4171 = !DIDerivedType(tag: DW_TAG_typedef, name: "FILE", file: !4172, line: 7, baseType: !3784)
!4172 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/FILE.h", directory: "", checksumkind: CSK_MD5, checksum: "571f9fb6223c42439075fdde11a0de5d")
!4173 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdio", directory: "")
!4174 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4175, file: !4173, line: 99)
!4175 = !DIDerivedType(tag: DW_TAG_typedef, name: "fpos_t", file: !4176, line: 78, baseType: !4177)
!4176 = !DIFile(filename: "/usr/include/stdio.h", directory: "", checksumkind: CSK_MD5, checksum: "2ab51d960d7d0ed84798d1688a6988b0")
!4177 = !DIDerivedType(tag: DW_TAG_typedef, name: "_G_fpos_t", file: !4178, line: 30, baseType: !4179)
!4178 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/_G_config.h", directory: "", checksumkind: CSK_MD5, checksum: "f78480ecfcae11a7bda5a6b08034c1fb")
!4179 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !4178, line: 26, size: 128, flags: DIFlagFwdDecl, identifier: "_ZTS9_G_fpos_t")
!4180 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4181, file: !4173, line: 101)
!4181 = !DISubprogram(name: "clearerr", scope: !4176, file: !4176, line: 757, type: !4182, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4182 = !DISubroutineType(types: !4183)
!4183 = !{null, !4184}
!4184 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4171, size: 64)
!4185 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4186, file: !4173, line: 102)
!4186 = !DISubprogram(name: "fclose", scope: !4176, file: !4176, line: 199, type: !4187, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4187 = !DISubroutineType(types: !4188)
!4188 = !{!701, !4184}
!4189 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4190, file: !4173, line: 103)
!4190 = !DISubprogram(name: "feof", scope: !4176, file: !4176, line: 759, type: !4187, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4191 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4192, file: !4173, line: 104)
!4192 = !DISubprogram(name: "ferror", scope: !4176, file: !4176, line: 761, type: !4187, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4193 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4194, file: !4173, line: 105)
!4194 = !DISubprogram(name: "fflush", scope: !4176, file: !4176, line: 204, type: !4187, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4195 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4196, file: !4173, line: 106)
!4196 = !DISubprogram(name: "fgetc", scope: !4176, file: !4176, line: 477, type: !4187, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4197 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4198, file: !4173, line: 107)
!4198 = !DISubprogram(name: "fgetpos", scope: !4176, file: !4176, line: 731, type: !4199, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4199 = !DISubroutineType(types: !4200)
!4200 = !{!701, !4201, !4202}
!4201 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4184)
!4202 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4203)
!4203 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4175, size: 64)
!4204 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4205, file: !4173, line: 108)
!4205 = !DISubprogram(name: "fgets", scope: !4176, file: !4176, line: 564, type: !4206, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4206 = !DISubroutineType(types: !4207)
!4207 = !{!746, !3511, !701, !4201}
!4208 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4209, file: !4173, line: 109)
!4209 = !DISubprogram(name: "fopen", scope: !4176, file: !4176, line: 232, type: !4210, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4210 = !DISubroutineType(types: !4211)
!4211 = !{!4184, !3512, !3512}
!4212 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4213, file: !4173, line: 110)
!4213 = !DISubprogram(name: "fprintf", scope: !4176, file: !4176, line: 312, type: !4214, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4214 = !DISubroutineType(types: !4215)
!4215 = !{!701, !4201, !3512, null}
!4216 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4217, file: !4173, line: 111)
!4217 = !DISubprogram(name: "fputc", scope: !4176, file: !4176, line: 517, type: !4218, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4218 = !DISubroutineType(types: !4219)
!4219 = !{!701, !701, !4184}
!4220 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4221, file: !4173, line: 112)
!4221 = !DISubprogram(name: "fputs", scope: !4176, file: !4176, line: 626, type: !4222, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4222 = !DISubroutineType(types: !4223)
!4223 = !{!701, !3512, !4201}
!4224 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4225, file: !4173, line: 113)
!4225 = !DISubprogram(name: "fread", scope: !4176, file: !4176, line: 646, type: !4226, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4226 = !DISubroutineType(types: !4227)
!4227 = !{!927, !3497, !927, !927, !4201}
!4228 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4229, file: !4173, line: 114)
!4229 = !DISubprogram(name: "freopen", scope: !4176, file: !4176, line: 238, type: !4230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4230 = !DISubroutineType(types: !4231)
!4231 = !{!4184, !3512, !3512, !4201}
!4232 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4233, file: !4173, line: 115)
!4233 = !DISubprogram(name: "fscanf", scope: !4176, file: !4176, line: 377, type: !4214, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4234 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4235, file: !4173, line: 116)
!4235 = !DISubprogram(name: "fseek", scope: !4176, file: !4176, line: 684, type: !4236, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4236 = !DISubroutineType(types: !4237)
!4237 = !{!701, !4184, !58, !701}
!4238 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4239, file: !4173, line: 117)
!4239 = !DISubprogram(name: "fsetpos", scope: !4176, file: !4176, line: 736, type: !4240, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4240 = !DISubroutineType(types: !4241)
!4241 = !{!701, !4184, !4242}
!4242 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4243, size: 64)
!4243 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4175)
!4244 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4245, file: !4173, line: 118)
!4245 = !DISubprogram(name: "ftell", scope: !4176, file: !4176, line: 689, type: !4246, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4246 = !DISubroutineType(types: !4247)
!4247 = !{!58, !4184}
!4248 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4249, file: !4173, line: 119)
!4249 = !DISubprogram(name: "fwrite", scope: !4176, file: !4176, line: 652, type: !4250, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4250 = !DISubroutineType(types: !4251)
!4251 = !{!927, !3498, !927, !927, !4201}
!4252 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4253, file: !4173, line: 120)
!4253 = !DISubprogram(name: "getc", scope: !4176, file: !4176, line: 478, type: !4187, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4254 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4255, file: !4173, line: 121)
!4255 = !DISubprogram(name: "getchar", scope: !4256, file: !4256, line: 44, type: !3661, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4256 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdio.h", directory: "", checksumkind: CSK_MD5, checksum: "ae874477a6b090849220f12acdd69dc3")
!4257 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4258, file: !4173, line: 126)
!4258 = !DISubprogram(name: "perror", scope: !4176, file: !4176, line: 775, type: !4259, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4259 = !DISubroutineType(types: !4260)
!4260 = !{null, !456}
!4261 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4262, file: !4173, line: 127)
!4262 = !DISubprogram(name: "printf", scope: !4176, file: !4176, line: 318, type: !4263, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4263 = !DISubroutineType(types: !4264)
!4264 = !{!701, !3512, null}
!4265 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4266, file: !4173, line: 128)
!4266 = !DISubprogram(name: "putc", scope: !4176, file: !4176, line: 518, type: !4218, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4267 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4268, file: !4173, line: 129)
!4268 = !DISubprogram(name: "putchar", scope: !4256, file: !4256, line: 79, type: !3140, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4269 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4270, file: !4173, line: 130)
!4270 = !DISubprogram(name: "puts", scope: !4176, file: !4176, line: 632, type: !3591, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4271 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4272, file: !4173, line: 131)
!4272 = !DISubprogram(name: "remove", scope: !4176, file: !4176, line: 144, type: !3591, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4273 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4274, file: !4173, line: 132)
!4274 = !DISubprogram(name: "rename", scope: !4176, file: !4176, line: 146, type: !3515, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4275 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4276, file: !4173, line: 133)
!4276 = !DISubprogram(name: "rewind", scope: !4176, file: !4176, line: 694, type: !4182, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4277 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4278, file: !4173, line: 134)
!4278 = !DISubprogram(name: "scanf", scope: !4176, file: !4176, line: 383, type: !4263, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4279 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4280, file: !4173, line: 135)
!4280 = !DISubprogram(name: "setbuf", scope: !4176, file: !4176, line: 290, type: !4281, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4281 = !DISubroutineType(types: !4282)
!4282 = !{null, !4201, !3511}
!4283 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4284, file: !4173, line: 136)
!4284 = !DISubprogram(name: "setvbuf", scope: !4176, file: !4176, line: 294, type: !4285, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4285 = !DISubroutineType(types: !4286)
!4286 = !{!701, !4201, !3511, !701, !927}
!4287 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4288, file: !4173, line: 137)
!4288 = !DISubprogram(name: "sprintf", scope: !4176, file: !4176, line: 320, type: !4289, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4289 = !DISubroutineType(types: !4290)
!4290 = !{!701, !3511, !3512, null}
!4291 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4292, file: !4173, line: 138)
!4292 = !DISubprogram(name: "sscanf", scope: !4176, file: !4176, line: 385, type: !4293, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4293 = !DISubroutineType(types: !4294)
!4294 = !{!701, !3512, !3512, null}
!4295 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4296, file: !4173, line: 139)
!4296 = !DISubprogram(name: "tmpfile", scope: !4176, file: !4176, line: 159, type: !4297, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4297 = !DISubroutineType(types: !4298)
!4298 = !{!4184}
!4299 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4300, file: !4173, line: 141)
!4300 = !DISubprogram(name: "tmpnam", scope: !4176, file: !4176, line: 173, type: !4301, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4301 = !DISubroutineType(types: !4302)
!4302 = !{!746, !746}
!4303 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4304, file: !4173, line: 143)
!4304 = !DISubprogram(name: "ungetc", scope: !4176, file: !4176, line: 639, type: !4218, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4305 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4306, file: !4173, line: 144)
!4306 = !DISubprogram(name: "vfprintf", scope: !4176, file: !4176, line: 327, type: !4307, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4307 = !DISubroutineType(types: !4308)
!4308 = !{!701, !4201, !3512, !3901}
!4309 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4310, file: !4173, line: 145)
!4310 = !DISubprogram(name: "vprintf", scope: !4256, file: !4256, line: 36, type: !4311, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4311 = !DISubroutineType(types: !4312)
!4312 = !{!701, !3512, !3901}
!4313 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4314, file: !4173, line: 146)
!4314 = !DISubprogram(name: "vsprintf", scope: !4176, file: !4176, line: 335, type: !4315, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4315 = !DISubroutineType(types: !4316)
!4316 = !{!701, !3511, !3512, !3901}
!4317 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4318, file: !4173, line: 175)
!4318 = !DISubprogram(name: "snprintf", scope: !4176, file: !4176, line: 340, type: !4319, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4319 = !DISubroutineType(types: !4320)
!4320 = !{!701, !3511, !927, !3512, null}
!4321 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4322, file: !4173, line: 176)
!4322 = !DISubprogram(name: "vfscanf", scope: !4176, file: !4176, line: 420, type: !4307, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4323 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4324, file: !4173, line: 177)
!4324 = !DISubprogram(name: "vscanf", scope: !4176, file: !4176, line: 428, type: !4311, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4325 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4326, file: !4173, line: 178)
!4326 = !DISubprogram(name: "vsnprintf", scope: !4176, file: !4176, line: 344, type: !4327, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4327 = !DISubroutineType(types: !4328)
!4328 = !{!701, !3511, !927, !3512, !3901}
!4329 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4330, file: !4173, line: 179)
!4330 = !DISubprogram(name: "vsscanf", scope: !4176, file: !4176, line: 432, type: !4331, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4331 = !DISubroutineType(types: !4332)
!4332 = !{!701, !3512, !3512, !3901}
!4333 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4318, file: !4173, line: 185)
!4334 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4322, file: !4173, line: 186)
!4335 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4324, file: !4173, line: 187)
!4336 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4326, file: !4173, line: 188)
!4337 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4330, file: !4173, line: 189)
!4338 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4339, file: !4343, line: 82)
!4339 = !DIDerivedType(tag: DW_TAG_typedef, name: "wctrans_t", file: !4340, line: 48, baseType: !4341)
!4340 = !DIFile(filename: "/usr/include/wctype.h", directory: "", checksumkind: CSK_MD5, checksum: "760693b7fbeea3d686e1f29058fc2257")
!4341 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4342, size: 64)
!4342 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4071)
!4343 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cwctype", directory: "")
!4344 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4345, file: !4343, line: 83)
!4345 = !DIDerivedType(tag: DW_TAG_typedef, name: "wctype_t", file: !4346, line: 38, baseType: !249)
!4346 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/wctype-wchar.h", directory: "", checksumkind: CSK_MD5, checksum: "45eef9c3aa1d99faffa3945ed9be039a")
!4347 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3770, file: !4343, line: 84)
!4348 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4349, file: !4343, line: 86)
!4349 = !DISubprogram(name: "iswalnum", scope: !4346, file: !4346, line: 95, type: !4003, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4350 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4351, file: !4343, line: 87)
!4351 = !DISubprogram(name: "iswalpha", scope: !4346, file: !4346, line: 101, type: !4003, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4352 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4353, file: !4343, line: 89)
!4353 = !DISubprogram(name: "iswblank", scope: !4346, file: !4346, line: 146, type: !4003, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4354 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4355, file: !4343, line: 91)
!4355 = !DISubprogram(name: "iswcntrl", scope: !4346, file: !4346, line: 104, type: !4003, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4356 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4357, file: !4343, line: 92)
!4357 = !DISubprogram(name: "iswctype", scope: !4346, file: !4346, line: 159, type: !4358, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4358 = !DISubroutineType(types: !4359)
!4359 = !{!701, !3770, !4345}
!4360 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4361, file: !4343, line: 93)
!4361 = !DISubprogram(name: "iswdigit", scope: !4346, file: !4346, line: 108, type: !4003, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4362 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4363, file: !4343, line: 94)
!4363 = !DISubprogram(name: "iswgraph", scope: !4346, file: !4346, line: 112, type: !4003, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4364 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4365, file: !4343, line: 95)
!4365 = !DISubprogram(name: "iswlower", scope: !4346, file: !4346, line: 117, type: !4003, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4366 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4367, file: !4343, line: 96)
!4367 = !DISubprogram(name: "iswprint", scope: !4346, file: !4346, line: 120, type: !4003, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4368 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4369, file: !4343, line: 97)
!4369 = !DISubprogram(name: "iswpunct", scope: !4346, file: !4346, line: 125, type: !4003, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4370 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4371, file: !4343, line: 98)
!4371 = !DISubprogram(name: "iswspace", scope: !4346, file: !4346, line: 130, type: !4003, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4372 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4373, file: !4343, line: 99)
!4373 = !DISubprogram(name: "iswupper", scope: !4346, file: !4346, line: 135, type: !4003, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4374 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4375, file: !4343, line: 100)
!4375 = !DISubprogram(name: "iswxdigit", scope: !4346, file: !4346, line: 140, type: !4003, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4376 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4377, file: !4343, line: 101)
!4377 = !DISubprogram(name: "towctrans", scope: !4340, file: !4340, line: 55, type: !4378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4378 = !DISubroutineType(types: !4379)
!4379 = !{!3770, !3770, !4339}
!4380 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4381, file: !4343, line: 102)
!4381 = !DISubprogram(name: "towlower", scope: !4346, file: !4346, line: 166, type: !4382, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4382 = !DISubroutineType(types: !4383)
!4383 = !{!3770, !3770}
!4384 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4385, file: !4343, line: 103)
!4385 = !DISubprogram(name: "towupper", scope: !4346, file: !4346, line: 169, type: !4382, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4386 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4387, file: !4343, line: 104)
!4387 = !DISubprogram(name: "wctrans", scope: !4340, file: !4340, line: 52, type: !4388, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4388 = !DISubroutineType(types: !4389)
!4389 = !{!4339, !456}
!4390 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4391, file: !4343, line: 105)
!4391 = !DISubprogram(name: "wctype", scope: !4346, file: !4346, line: 155, type: !4392, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4392 = !DISubroutineType(types: !4393)
!4393 = !{!4345, !456}
!4394 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !39, entity: !2100, file: !429, line: 63)
!4395 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !39, entity: !432, file: !429, line: 64)
!4396 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !39, entity: !4397, file: !429, line: 76)
!4397 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "RefCountedBaseVPTR", scope: !13, file: !429, line: 45, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm18RefCountedBaseVPTRE")
!4398 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !39, entity: !428, file: !429, line: 78)
!4399 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3, file: !4400, line: 86)
!4400 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr_base.h", directory: "", checksumkind: CSK_MD5, checksum: "8405222f7806be9ab20595b5fcc527fd")
!4401 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4402, file: !4400, line: 87)
!4402 = !DIGlobalVariable(name: "__default_lock_policy", linkageName: "_ZN9__gnu_cxxL21__default_lock_policyE", scope: !5, file: !4, line: 53, type: !4403, isLocal: true, isDefinition: false)
!4403 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3)
!4404 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4405, file: !4408, line: 60)
!4405 = !DIDerivedType(tag: DW_TAG_typedef, name: "clock_t", file: !4406, line: 7, baseType: !4407)
!4406 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/clock_t.h", directory: "", checksumkind: CSK_MD5, checksum: "1aade99fd778d1551600c7ca1410b9f1")
!4407 = !DIDerivedType(tag: DW_TAG_typedef, name: "__clock_t", file: !674, line: 144, baseType: !58)
!4408 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ctime", directory: "")
!4409 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4410, file: !4408, line: 61)
!4410 = !DIDerivedType(tag: DW_TAG_typedef, name: "time_t", file: !4411, line: 7, baseType: !4412)
!4411 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/time_t.h", directory: "", checksumkind: CSK_MD5, checksum: "49b4e16ef1215de5afdbb283400ab90c")
!4412 = !DIDerivedType(tag: DW_TAG_typedef, name: "__time_t", file: !674, line: 148, baseType: !58)
!4413 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !3952, file: !4408, line: 62)
!4414 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4415, file: !4408, line: 64)
!4415 = !DISubprogram(name: "clock", scope: !4416, file: !4416, line: 72, type: !4417, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4416 = !DIFile(filename: "/usr/include/time.h", directory: "", checksumkind: CSK_MD5, checksum: "3b21b4c7d8bf3fafdb33a1c7ed8e024a")
!4417 = !DISubroutineType(types: !4418)
!4418 = !{!4405}
!4419 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4420, file: !4408, line: 65)
!4420 = !DISubprogram(name: "difftime", scope: !4416, file: !4416, line: 78, type: !4421, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4421 = !DISubroutineType(types: !4422)
!4422 = !{!3148, !4410, !4410}
!4423 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4424, file: !4408, line: 66)
!4424 = !DISubprogram(name: "mktime", scope: !4416, file: !4416, line: 82, type: !4425, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4425 = !DISubroutineType(types: !4426)
!4426 = !{!4410, !4427}
!4427 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3952, size: 64)
!4428 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4429, file: !4408, line: 67)
!4429 = !DISubprogram(name: "time", scope: !4416, file: !4416, line: 75, type: !4430, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4430 = !DISubroutineType(types: !4431)
!4431 = !{!4410, !4432}
!4432 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4410, size: 64)
!4433 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4434, file: !4408, line: 68)
!4434 = !DISubprogram(name: "asctime", scope: !4416, file: !4416, line: 139, type: !4435, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4435 = !DISubroutineType(types: !4436)
!4436 = !{!746, !3950}
!4437 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4438, file: !4408, line: 69)
!4438 = !DISubprogram(name: "ctime", scope: !4416, file: !4416, line: 142, type: !4439, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4439 = !DISubroutineType(types: !4440)
!4440 = !{!746, !4441}
!4441 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4442, size: 64)
!4442 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4410)
!4443 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4444, file: !4408, line: 70)
!4444 = !DISubprogram(name: "gmtime", scope: !4416, file: !4416, line: 119, type: !4445, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4445 = !DISubroutineType(types: !4446)
!4446 = !{!4427, !4441}
!4447 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4448, file: !4408, line: 71)
!4448 = !DISubprogram(name: "localtime", scope: !4416, file: !4416, line: 123, type: !4445, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4449 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !408, entity: !4450, file: !4408, line: 72)
!4450 = !DISubprogram(name: "strftime", scope: !4416, file: !4416, line: 88, type: !4451, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4451 = !DISubroutineType(types: !4452)
!4452 = !{!927, !3511, !927, !3512, !3949}
!4453 = !{i32 7, !"Dwarf Version", i32 5}
!4454 = !{i32 2, !"Debug Info Version", i32 3}
!4455 = !{i32 1, !"wchar_size", i32 4}
!4456 = !{i32 7, !"PIC Level", i32 2}
!4457 = !{i32 7, !"uwtable", i32 2}
!4458 = !DILocalVariable(name: "VBPtrOffset", scope: !4459, file: !1393, line: 201, type: !666)
!4459 = distinct !DISubprogram(name: "EmitVBTableDefinition", linkageName: "_ZNK5clang7CodeGen11VBTableInfo21EmitVBTableDefinitionERNS0_13CodeGenModuleEPKNS_13CXXRecordDeclEN4llvm11GlobalValue12LinkageTypesE", scope: !1396, file: !1393, line: 187, type: !1430, scopeLine: 189, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !1429, retainedNodes: !4460)
!4460 = !{!4461, !4463, !4464, !4465, !4466, !4467, !4468, !4458, !4469, !4472, !4477, !4478, !4481, !4482, !4483, !4484}
!4461 = !DILocalVariable(name: "this", arg: 1, scope: !4459, type: !4462, flags: DIFlagArtificial | DIFlagObjectPointer)
!4462 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1433, size: 64)
!4463 = !DILocalVariable(name: "CGM", arg: 2, scope: !4459, file: !1393, line: 188, type: !1434)
!4464 = !DILocalVariable(name: "RD", arg: 3, scope: !4459, file: !1393, line: 188, type: !520)
!4465 = !DILocalVariable(name: "Linkage", arg: 4, scope: !4459, file: !1393, line: 189, type: !16)
!4466 = !DILocalVariable(name: "BaseLayout", scope: !4459, file: !1393, line: 193, type: !1962)
!4467 = !DILocalVariable(name: "DerivedLayout", scope: !4459, file: !1393, line: 195, type: !1962)
!4468 = !DILocalVariable(name: "Offsets", scope: !4459, file: !1393, line: 198, type: !2494)
!4469 = !DILocalVariable(name: "Context", scope: !4459, file: !1393, line: 204, type: !4470)
!4470 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4471, size: 64)
!4471 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MicrosoftVTableContext", scope: !39, file: !2998, line: 403, size: 1280, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang22MicrosoftVTableContextE")
!4472 = !DILocalVariable(name: "I", scope: !4473, file: !1393, line: 205, type: !4474)
!4473 = distinct !DILexicalBlock(scope: !4459, file: !1393, line: 205, column: 3)
!4474 = !DIDerivedType(tag: DW_TAG_typedef, name: "base_class_const_iterator", scope: !522, file: !523, line: 622, baseType: !4475)
!4475 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4476, size: 64)
!4476 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !751)
!4477 = !DILocalVariable(name: "E", scope: !4473, file: !1393, line: 206, type: !4474)
!4478 = !DILocalVariable(name: "VBase", scope: !4479, file: !1393, line: 207, type: !520)
!4479 = distinct !DILexicalBlock(scope: !4480, file: !1393, line: 206, column: 52)
!4480 = distinct !DILexicalBlock(scope: !4473, file: !1393, line: 205, column: 3)
!4481 = !DILocalVariable(name: "Offset", scope: !4479, file: !1393, line: 208, type: !666)
!4482 = !DILocalVariable(name: "VBIndex", scope: !4479, file: !1393, line: 212, type: !6)
!4483 = !DILocalVariable(name: "VBTableType", scope: !4459, file: !1393, line: 220, type: !1379)
!4484 = !DILocalVariable(name: "Init", scope: !4459, file: !1393, line: 222, type: !1287)
!4485 = !DILocation(line: 0, scope: !4459)
