; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -o - -S --passes=simplifycfg | FileCheck %s
; Huuurrr. In the below, the function *checks notes* ... SplitBlockAndInsertIfThen...
; needs to know that we're splitting at a "get the head" position.
; This is very dumb. But it exists. Ho hum.
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define internal fastcc void @_ZN12_GLOBAL__N_117TailDuplicatePass17duplicateSimpleBBEPN4llvm17MachineBasicBlockERNS1_15SmallVectorImplIS3_EERKNS1_8DenseSetIjNS1_12DenseMapInfoIjEEEERNS4_IPNS1_12MachineInstrEEE(i1 %tobool49.not, ptr %PredFBB1) {
; CHECK-LABEL: @_ZN12_GLOBAL__N_117TailDuplicatePass17duplicateSimpleBBEPN4llvm17MachineBasicBlockERNS1_15SmallVectorImplIS3_EERKNS1_8DenseSetIjNS1_12DenseMapInfoIjEEEERNS4_IPNS1_12MachineInstrEEE(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = xor i1 [[TOBOOL49_NOT:%.*]], true
; CHECK-NEXT:    [[TMP1:%.*]] = xor i1 [[TMP0]], true
; CHECK-NEXT:    [[TMP2:%.*]] = or i1 [[TMP1]], undef
; CHECK-NEXT:    br i1 [[TMP2]], label [[TMP3:%.*]], label [[TMP4:%.*]]
; CHECK:       3:
; CHECK-NEXT:    store ptr null, ptr [[PREDFBB1:%.*]], align 8
; CHECK-NEXT:    br label [[TMP4]]
; CHECK:       4:
; CHECK-NEXT:    call void @llvm.dbg.value(metadata ptr undef, metadata [[META8505:![0-9]+]], metadata !DIExpression()), !dbg [[DBG8528:![0-9]+]]
; CHECK-NEXT:    ret void
;
entry:
  br i1 %tobool49.not, label %if.then50, label %if.end51

if.then50:                                        ; preds = %entry
  store ptr null, ptr %PredFBB1, align 8
  br label %if.end51

if.end51:                                         ; preds = %if.then50, %entry
  br i1 undef, label %if.then53, label %if.end54

if.then53:                                        ; preds = %if.end51
  store ptr null, ptr %PredFBB1, align 8
  br label %if.end54

if.end54:                                         ; preds = %if.then53, %if.end51
  call void @llvm.dbg.value(metadata ptr undef, metadata !8505, metadata !DIExpression()), !dbg !8528
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind readnone speculatable willreturn
declare void @llvm.dbg.value(metadata, metadata, metadata) #0

attributes #0 = { nocallback nofree nosync nounwind readnone speculatable willreturn }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!8500, !8501, !8502, !8503, !8504}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !809, globals: !6444, imports: !7184, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "/fast/fs/llvm34/lib/CodeGen/TailDuplication.cpp", directory: "/fast/fs/build34llvm5", checksumkind: CSK_MD5, checksum: "f5cdce11cfd44d2c944f0e413097b426")
!2 = !{!3, !11, !19, !29, !111, !115, !223, !246, !540, !546, !551, !583, !588, !594, !635, !770, !785, !791, !796, !803}
!3 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "_Lock_policy", scope: !5, file: !4, line: 49, baseType: !6, size: 32, elements: !7, identifier: "_ZTSN9__gnu_cxx12_Lock_policyE")
!4 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/concurrence.h", directory: "")
!5 = !DINamespace(name: "__gnu_cxx", scope: null)
!6 = !DIBasicType(name: "unsigned int", size: 32, encoding: DW_ATE_unsigned)
!7 = !{!8, !9, !10}
!8 = !DIEnumerator(name: "_S_single", value: 0, isUnsigned: true)
!9 = !DIEnumerator(name: "_S_mutex", value: 1, isUnsigned: true)
!10 = !DIEnumerator(name: "_S_atomic", value: 2, isUnsigned: true)
!11 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "OptionHidden", scope: !13, file: !12, line: 107, baseType: !6, size: 32, elements: !15, identifier: "_ZTSN4llvm2cl12OptionHiddenE")
!12 = !DIFile(filename: "llvm34/include/llvm/Support/CommandLine.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "7355fa45f9b7e74d70b631b79925f02b")
!13 = !DINamespace(name: "cl", scope: !14)
!14 = !DINamespace(name: "llvm", scope: null)
!15 = !{!16, !17, !18}
!16 = !DIEnumerator(name: "NotHidden", value: 0, isUnsigned: true)
!17 = !DIEnumerator(name: "Hidden", value: 1, isUnsigned: true)
!18 = !DIEnumerator(name: "ReallyHidden", value: 2, isUnsigned: true)
!19 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "PassKind", scope: !14, file: !20, line: 67, baseType: !6, size: 32, elements: !21, identifier: "_ZTSN4llvm8PassKindE")
!20 = !DIFile(filename: "llvm34/include/llvm/Pass.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "46c927a21d41c0100f7ff76e01726dcc")
!21 = !{!22, !23, !24, !25, !26, !27, !28}
!22 = !DIEnumerator(name: "PT_BasicBlock", value: 0, isUnsigned: true)
!23 = !DIEnumerator(name: "PT_Region", value: 1, isUnsigned: true)
!24 = !DIEnumerator(name: "PT_Loop", value: 2, isUnsigned: true)
!25 = !DIEnumerator(name: "PT_Function", value: 3, isUnsigned: true)
!26 = !DIEnumerator(name: "PT_CallGraphSCC", value: 4, isUnsigned: true)
!27 = !DIEnumerator(name: "PT_Module", value: 5, isUnsigned: true)
!28 = !DIEnumerator(name: "PT_PassManager", value: 6, isUnsigned: true)
!29 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "SimpleValueType", scope: !31, file: !30, line: 35, baseType: !32, size: 32, elements: !33, identifier: "_ZTSN4llvm3MVT15SimpleValueTypeE")
!30 = !DIFile(filename: "llvm34/include/llvm/CodeGen/ValueTypes.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e707d46c4dc350b14263b32a00d2cd7f")
!31 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MVT", scope: !14, file: !30, line: 33, size: 32, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm3MVTE")
!32 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!33 = !{!34, !35, !36, !37, !38, !39, !40, !41, !42, !43, !44, !45, !46, !47, !48, !49, !50, !51, !52, !53, !54, !55, !56, !57, !58, !59, !60, !61, !62, !63, !64, !65, !66, !67, !68, !69, !70, !71, !72, !73, !74, !75, !76, !77, !78, !79, !80, !81, !82, !83, !84, !85, !86, !87, !88, !89, !90, !91, !92, !93, !94, !95, !96, !97, !98, !99, !100, !101, !102, !103, !104, !105, !106, !107, !108, !109, !110}
!34 = !DIEnumerator(name: "INVALID_SIMPLE_VALUE_TYPE", value: -1)
!35 = !DIEnumerator(name: "Other", value: 0)
!36 = !DIEnumerator(name: "i1", value: 1)
!37 = !DIEnumerator(name: "i8", value: 2)
!38 = !DIEnumerator(name: "i16", value: 3)
!39 = !DIEnumerator(name: "i32", value: 4)
!40 = !DIEnumerator(name: "i64", value: 5)
!41 = !DIEnumerator(name: "i128", value: 6)
!42 = !DIEnumerator(name: "FIRST_INTEGER_VALUETYPE", value: 1)
!43 = !DIEnumerator(name: "LAST_INTEGER_VALUETYPE", value: 6)
!44 = !DIEnumerator(name: "f16", value: 7)
!45 = !DIEnumerator(name: "f32", value: 8)
!46 = !DIEnumerator(name: "f64", value: 9)
!47 = !DIEnumerator(name: "f80", value: 10)
!48 = !DIEnumerator(name: "f128", value: 11)
!49 = !DIEnumerator(name: "ppcf128", value: 12)
!50 = !DIEnumerator(name: "FIRST_FP_VALUETYPE", value: 7)
!51 = !DIEnumerator(name: "LAST_FP_VALUETYPE", value: 12)
!52 = !DIEnumerator(name: "v2i1", value: 13)
!53 = !DIEnumerator(name: "v4i1", value: 14)
!54 = !DIEnumerator(name: "v8i1", value: 15)
!55 = !DIEnumerator(name: "v16i1", value: 16)
!56 = !DIEnumerator(name: "v32i1", value: 17)
!57 = !DIEnumerator(name: "v64i1", value: 18)
!58 = !DIEnumerator(name: "v1i8", value: 19)
!59 = !DIEnumerator(name: "v2i8", value: 20)
!60 = !DIEnumerator(name: "v4i8", value: 21)
!61 = !DIEnumerator(name: "v8i8", value: 22)
!62 = !DIEnumerator(name: "v16i8", value: 23)
!63 = !DIEnumerator(name: "v32i8", value: 24)
!64 = !DIEnumerator(name: "v64i8", value: 25)
!65 = !DIEnumerator(name: "v1i16", value: 26)
!66 = !DIEnumerator(name: "v2i16", value: 27)
!67 = !DIEnumerator(name: "v4i16", value: 28)
!68 = !DIEnumerator(name: "v8i16", value: 29)
!69 = !DIEnumerator(name: "v16i16", value: 30)
!70 = !DIEnumerator(name: "v32i16", value: 31)
!71 = !DIEnumerator(name: "v1i32", value: 32)
!72 = !DIEnumerator(name: "v2i32", value: 33)
!73 = !DIEnumerator(name: "v4i32", value: 34)
!74 = !DIEnumerator(name: "v8i32", value: 35)
!75 = !DIEnumerator(name: "v16i32", value: 36)
!76 = !DIEnumerator(name: "v1i64", value: 37)
!77 = !DIEnumerator(name: "v2i64", value: 38)
!78 = !DIEnumerator(name: "v4i64", value: 39)
!79 = !DIEnumerator(name: "v8i64", value: 40)
!80 = !DIEnumerator(name: "v16i64", value: 41)
!81 = !DIEnumerator(name: "FIRST_INTEGER_VECTOR_VALUETYPE", value: 13)
!82 = !DIEnumerator(name: "LAST_INTEGER_VECTOR_VALUETYPE", value: 41)
!83 = !DIEnumerator(name: "v2f16", value: 42)
!84 = !DIEnumerator(name: "v4f16", value: 43)
!85 = !DIEnumerator(name: "v8f16", value: 44)
!86 = !DIEnumerator(name: "v1f32", value: 45)
!87 = !DIEnumerator(name: "v2f32", value: 46)
!88 = !DIEnumerator(name: "v4f32", value: 47)
!89 = !DIEnumerator(name: "v8f32", value: 48)
!90 = !DIEnumerator(name: "v16f32", value: 49)
!91 = !DIEnumerator(name: "v1f64", value: 50)
!92 = !DIEnumerator(name: "v2f64", value: 51)
!93 = !DIEnumerator(name: "v4f64", value: 52)
!94 = !DIEnumerator(name: "v8f64", value: 53)
!95 = !DIEnumerator(name: "FIRST_FP_VECTOR_VALUETYPE", value: 42)
!96 = !DIEnumerator(name: "LAST_FP_VECTOR_VALUETYPE", value: 53)
!97 = !DIEnumerator(name: "FIRST_VECTOR_VALUETYPE", value: 13)
!98 = !DIEnumerator(name: "LAST_VECTOR_VALUETYPE", value: 53)
!99 = !DIEnumerator(name: "x86mmx", value: 54)
!100 = !DIEnumerator(name: "Glue", value: 55)
!101 = !DIEnumerator(name: "isVoid", value: 56)
!102 = !DIEnumerator(name: "Untyped", value: 57)
!103 = !DIEnumerator(name: "LAST_VALUETYPE", value: 58)
!104 = !DIEnumerator(name: "MAX_ALLOWED_VALUETYPE", value: 64)
!105 = !DIEnumerator(name: "Metadata", value: 250)
!106 = !DIEnumerator(name: "iPTRAny", value: 251)
!107 = !DIEnumerator(name: "vAny", value: 252)
!108 = !DIEnumerator(name: "fAny", value: 253)
!109 = !DIEnumerator(name: "iAny", value: 254)
!110 = !DIEnumerator(name: "iPTR", value: 255)
!111 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "NoneType", scope: !14, file: !112, line: 22, baseType: !6, size: 32, elements: !113, identifier: "_ZTSN4llvm8NoneTypeE")
!112 = !DIFile(filename: "llvm34/include/llvm/ADT/None.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "a0342314f03a5b3ad15259d9915a8f1b")
!113 = !{!114}
!114 = !DIEnumerator(name: "None", value: 0, isUnsigned: true)
!115 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !117, file: !116, line: 238, baseType: !6, size: 32, elements: !221, identifier: "_ZTSN4llvm11SmallPtrSetIPNS_17MachineBasicBlockELj8EEUt_E")
!116 = !DIFile(filename: "llvm34/include/llvm/ADT/SmallPtrSet.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "a8637a3720e7d16110f2e5a1c96cd729")
!117 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallPtrSet<llvm::MachineBasicBlock *, 8U>", scope: !14, file: !116, line: 236, size: 768, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !118, templateParams: !218, identifier: "_ZTSN4llvm11SmallPtrSetIPNS_17MachineBasicBlockELj8EEE")
!118 = !{!119, !181, !185, !189, !194, !200, !201, !205, !210, !211, !214}
!119 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !117, baseType: !120, flags: DIFlagPublic, extraData: i32 0)
!120 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallPtrSetImpl", scope: !14, file: !116, line: 48, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !121, identifier: "_ZTSN4llvm15SmallPtrSetImplE")
!121 = !{!122, !126, !127, !128, !129, !130, !136, !139, !142, !147, !150, !151, !155, !156, !159, !160, !163, !164, !169, !170, !173, !176, !180}
!122 = !DIDerivedType(tag: DW_TAG_member, name: "SmallArray", scope: !120, file: !116, line: 52, baseType: !123, size: 64, flags: DIFlagProtected)
!123 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !124, size: 64)
!124 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !125, size: 64)
!125 = !DIDerivedType(tag: DW_TAG_const_type, baseType: null)
!126 = !DIDerivedType(tag: DW_TAG_member, name: "CurArray", scope: !120, file: !116, line: 55, baseType: !123, size: 64, offset: 64, flags: DIFlagProtected)
!127 = !DIDerivedType(tag: DW_TAG_member, name: "CurArraySize", scope: !120, file: !116, line: 57, baseType: !6, size: 32, offset: 128, flags: DIFlagProtected)
!128 = !DIDerivedType(tag: DW_TAG_member, name: "NumElements", scope: !120, file: !116, line: 60, baseType: !6, size: 32, offset: 160, flags: DIFlagProtected)
!129 = !DIDerivedType(tag: DW_TAG_member, name: "NumTombstones", scope: !120, file: !116, line: 61, baseType: !6, size: 32, offset: 192, flags: DIFlagProtected)
!130 = !DISubprogram(name: "SmallPtrSetImpl", scope: !120, file: !116, line: 64, type: !131, scopeLine: 64, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!131 = !DISubroutineType(types: !132)
!132 = !{null, !133, !123, !134}
!133 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !120, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!134 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !135, size: 64)
!135 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !120)
!136 = !DISubprogram(name: "SmallPtrSetImpl", scope: !120, file: !116, line: 65, type: !137, scopeLine: 65, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!137 = !DISubroutineType(types: !138)
!138 = !{null, !133, !123, !6}
!139 = !DISubprogram(name: "~SmallPtrSetImpl", scope: !120, file: !116, line: 71, type: !140, scopeLine: 71, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!140 = !DISubroutineType(types: !141)
!141 = !{null, !133}
!142 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm15SmallPtrSetImpl5emptyEv", scope: !120, file: !116, line: 74, type: !143, scopeLine: 74, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!143 = !DISubroutineType(types: !144)
!144 = !{!145, !146}
!145 = !DIBasicType(name: "bool", size: 8, encoding: DW_ATE_boolean)
!146 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !135, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!147 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm15SmallPtrSetImpl4sizeEv", scope: !120, file: !116, line: 75, type: !148, scopeLine: 75, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!148 = !DISubroutineType(types: !149)
!149 = !{!6, !146}
!150 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallPtrSetImpl5clearEv", scope: !120, file: !116, line: 77, type: !140, scopeLine: 77, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!151 = !DISubprogram(name: "getTombstoneMarker", linkageName: "_ZN4llvm15SmallPtrSetImpl18getTombstoneMarkerEv", scope: !120, file: !116, line: 90, type: !152, scopeLine: 90, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!152 = !DISubroutineType(types: !153)
!153 = !{!154}
!154 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 64)
!155 = !DISubprogram(name: "getEmptyMarker", linkageName: "_ZN4llvm15SmallPtrSetImpl14getEmptyMarkerEv", scope: !120, file: !116, line: 91, type: !152, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!156 = !DISubprogram(name: "insert_imp", linkageName: "_ZN4llvm15SmallPtrSetImpl10insert_impEPKv", scope: !120, file: !116, line: 100, type: !157, scopeLine: 100, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!157 = !DISubroutineType(types: !158)
!158 = !{!145, !133, !124}
!159 = !DISubprogram(name: "erase_imp", linkageName: "_ZN4llvm15SmallPtrSetImpl9erase_impEPKv", scope: !120, file: !116, line: 106, type: !157, scopeLine: 106, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!160 = !DISubprogram(name: "count_imp", linkageName: "_ZNK4llvm15SmallPtrSetImpl9count_impEPKv", scope: !120, file: !116, line: 108, type: !161, scopeLine: 108, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!161 = !DISubroutineType(types: !162)
!162 = !{!145, !146, !124}
!163 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm15SmallPtrSetImpl7isSmallEv", scope: !120, file: !116, line: 123, type: !143, scopeLine: 123, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!164 = !DISubprogram(name: "FindBucketFor", linkageName: "_ZNK4llvm15SmallPtrSetImpl13FindBucketForEPKv", scope: !120, file: !116, line: 125, type: !165, scopeLine: 125, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!165 = !DISubroutineType(types: !166)
!166 = !{!167, !146, !124}
!167 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !168, size: 64)
!168 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !124)
!169 = !DISubprogram(name: "shrink_and_clear", linkageName: "_ZN4llvm15SmallPtrSetImpl16shrink_and_clearEv", scope: !120, file: !116, line: 126, type: !140, scopeLine: 126, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!170 = !DISubprogram(name: "Grow", linkageName: "_ZN4llvm15SmallPtrSetImpl4GrowEj", scope: !120, file: !116, line: 129, type: !171, scopeLine: 129, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!171 = !DISubroutineType(types: !172)
!172 = !{null, !133, !6}
!173 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallPtrSetImplaSERKS0_", scope: !120, file: !116, line: 131, type: !174, scopeLine: 131, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!174 = !DISubroutineType(types: !175)
!175 = !{null, !133, !134}
!176 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallPtrSetImpl4swapERS0_", scope: !120, file: !116, line: 135, type: !177, scopeLine: 135, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!177 = !DISubroutineType(types: !178)
!178 = !{null, !133, !179}
!179 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !120, size: 64)
!180 = !DISubprogram(name: "CopyFrom", linkageName: "_ZN4llvm15SmallPtrSetImpl8CopyFromERKS0_", scope: !120, file: !116, line: 137, type: !174, scopeLine: 137, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!181 = !DIDerivedType(tag: DW_TAG_member, name: "SmallStorage", scope: !117, file: !116, line: 240, baseType: !182, size: 512, offset: 256)
!182 = !DICompositeType(tag: DW_TAG_array_type, baseType: !124, size: 512, elements: !183)
!183 = !{!184}
!184 = !DISubrange(count: 8)
!185 = !DISubprogram(name: "SmallPtrSet", scope: !117, file: !116, line: 243, type: !186, scopeLine: 243, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!186 = !DISubroutineType(types: !187)
!187 = !{null, !188}
!188 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !117, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!189 = !DISubprogram(name: "SmallPtrSet", scope: !117, file: !116, line: 244, type: !190, scopeLine: 244, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!190 = !DISubroutineType(types: !191)
!191 = !{null, !188, !192}
!192 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !193, size: 64)
!193 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !117)
!194 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm11SmallPtrSetIPNS_17MachineBasicBlockELj8EE6insertES2_", scope: !117, file: !116, line: 253, type: !195, scopeLine: 253, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!195 = !DISubroutineType(types: !196)
!196 = !{!145, !188, !197}
!197 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !198, size: 64)
!198 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MachineBasicBlock", scope: !14, file: !199, line: 62, size: 1408, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm17MachineBasicBlockE")
!199 = !DIFile(filename: "llvm34/include/llvm/CodeGen/MachineBasicBlock.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "a28a380f2952405e2da5b2c96750300d")
!200 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm11SmallPtrSetIPNS_17MachineBasicBlockELj8EE5eraseES2_", scope: !117, file: !116, line: 259, type: !195, scopeLine: 259, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!201 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm11SmallPtrSetIPNS_17MachineBasicBlockELj8EE5countES2_", scope: !117, file: !116, line: 264, type: !202, scopeLine: 264, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!202 = !DISubroutineType(types: !203)
!203 = !{!145, !204, !197}
!204 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !193, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!205 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm11SmallPtrSetIPNS_17MachineBasicBlockELj8EE5beginEv", scope: !117, file: !116, line: 276, type: !206, scopeLine: 276, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!206 = !DISubroutineType(types: !207)
!207 = !{!208, !204}
!208 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !117, file: !116, line: 274, baseType: !209)
!209 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallPtrSetIterator<llvm::MachineBasicBlock *>", scope: !14, file: !116, line: 174, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm19SmallPtrSetIteratorIPNS_17MachineBasicBlockEEE")
!210 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm11SmallPtrSetIPNS_17MachineBasicBlockELj8EE3endEv", scope: !117, file: !116, line: 279, type: !206, scopeLine: 279, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!211 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallPtrSetIPNS_17MachineBasicBlockELj8EEaSERKS3_", scope: !117, file: !116, line: 286, type: !212, scopeLine: 286, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!212 = !DISubroutineType(types: !213)
!213 = !{!192, !188, !192}
!214 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm11SmallPtrSetIPNS_17MachineBasicBlockELj8EE4swapERS3_", scope: !117, file: !116, line: 292, type: !215, scopeLine: 292, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!215 = !DISubroutineType(types: !216)
!216 = !{null, !188, !217}
!217 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !117, size: 64)
!218 = !{!219, !220}
!219 = !DITemplateTypeParameter(name: "PtrType", type: !197)
!220 = !DITemplateValueParameter(name: "SmallSize", type: !6, value: i32 8)
!221 = !{!222}
!222 = !DIEnumerator(name: "SmallSizePowTwo", value: 8, isUnsigned: true)
!223 = !DICompositeType(tag: DW_TAG_enumeration_type, scope: !225, file: !224, line: 25, baseType: !6, size: 32, elements: !226)
!224 = !DIFile(filename: "llvm34/include/llvm/Target/TargetOpcodes.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "602cb86be2d0eacef1fa25536094b1a7")
!225 = !DINamespace(name: "TargetOpcode", scope: !14)
!226 = !{!227, !228, !229, !230, !231, !232, !233, !234, !235, !236, !237, !238, !239, !240, !241, !242, !243, !244, !245}
!227 = !DIEnumerator(name: "PHI", value: 0, isUnsigned: true)
!228 = !DIEnumerator(name: "INLINEASM", value: 1, isUnsigned: true)
!229 = !DIEnumerator(name: "PROLOG_LABEL", value: 2, isUnsigned: true)
!230 = !DIEnumerator(name: "EH_LABEL", value: 3, isUnsigned: true)
!231 = !DIEnumerator(name: "GC_LABEL", value: 4, isUnsigned: true)
!232 = !DIEnumerator(name: "KILL", value: 5, isUnsigned: true)
!233 = !DIEnumerator(name: "EXTRACT_SUBREG", value: 6, isUnsigned: true)
!234 = !DIEnumerator(name: "INSERT_SUBREG", value: 7, isUnsigned: true)
!235 = !DIEnumerator(name: "IMPLICIT_DEF", value: 8, isUnsigned: true)
!236 = !DIEnumerator(name: "SUBREG_TO_REG", value: 9, isUnsigned: true)
!237 = !DIEnumerator(name: "COPY_TO_REGCLASS", value: 10, isUnsigned: true)
!238 = !DIEnumerator(name: "DBG_VALUE", value: 11, isUnsigned: true)
!239 = !DIEnumerator(name: "REG_SEQUENCE", value: 12, isUnsigned: true)
!240 = !DIEnumerator(name: "COPY", value: 13, isUnsigned: true)
!241 = !DIEnumerator(name: "BUNDLE", value: 14, isUnsigned: true)
!242 = !DIEnumerator(name: "LIFETIME_START", value: 15, isUnsigned: true)
!243 = !DIEnumerator(name: "LIFETIME_END", value: 16, isUnsigned: true)
!244 = !DIEnumerator(name: "STACKMAP", value: 17, isUnsigned: true)
!245 = !DIEnumerator(name: "PATCHPOINT", value: 18, isUnsigned: true)
!246 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "MachineOperandType", scope: !248, file: !247, line: 45, baseType: !6, size: 32, elements: !524, identifier: "_ZTSN4llvm14MachineOperand18MachineOperandTypeE")
!247 = !DIFile(filename: "llvm34/include/llvm/CodeGen/MachineOperand.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "a78ec1c608034687bf08714ad11b2657")
!248 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MachineOperand", scope: !14, file: !247, line: 43, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !249, identifier: "_ZTSN4llvm14MachineOperandE")
!249 = !{!250, !252, !253, !254, !255, !256, !257, !258, !259, !260, !261, !262, !267, !271, !330, !334, !339, !342, !345, !346, !349, !354, !357, !367, !370, !371, !372, !373, !374, !375, !376, !377, !378, !379, !380, !381, !382, !383, !384, !385, !386, !387, !388, !389, !390, !391, !392, !393, !394, !395, !396, !397, !398, !399, !406, !409, !412, !413, !414, !415, !416, !417, !418, !419, !420, !423, !426, !429, !432, !435, !438, !441, !444, !445, !448, !451, !454, !457, !460, !463, !464, !467, !470, !474, !475, !478, !481, !484, !487, !490, !493, !496, !499, !502, !505, !508, !511, !514, !517, !520, !523}
!250 = !DIDerivedType(tag: DW_TAG_member, name: "OpKind", scope: !248, file: !247, line: 66, baseType: !251, size: 8)
!251 = !DIBasicType(name: "unsigned char", size: 8, encoding: DW_ATE_unsigned_char)
!252 = !DIDerivedType(tag: DW_TAG_member, name: "SubReg_TargetFlags", scope: !248, file: !247, line: 72, baseType: !6, size: 12, offset: 8, flags: DIFlagBitField, extraData: i64 8)
!253 = !DIDerivedType(tag: DW_TAG_member, name: "TiedTo", scope: !248, file: !247, line: 77, baseType: !251, size: 4, offset: 20, flags: DIFlagBitField, extraData: i64 8)
!254 = !DIDerivedType(tag: DW_TAG_member, name: "IsDef", scope: !248, file: !247, line: 84, baseType: !145, size: 1, offset: 24, flags: DIFlagBitField, extraData: i64 8)
!255 = !DIDerivedType(tag: DW_TAG_member, name: "IsImp", scope: !248, file: !247, line: 88, baseType: !145, size: 1, offset: 25, flags: DIFlagBitField, extraData: i64 8)
!256 = !DIDerivedType(tag: DW_TAG_member, name: "IsKill", scope: !248, file: !247, line: 92, baseType: !145, size: 1, offset: 26, flags: DIFlagBitField, extraData: i64 8)
!257 = !DIDerivedType(tag: DW_TAG_member, name: "IsDead", scope: !248, file: !247, line: 96, baseType: !145, size: 1, offset: 27, flags: DIFlagBitField, extraData: i64 8)
!258 = !DIDerivedType(tag: DW_TAG_member, name: "IsUndef", scope: !248, file: !247, line: 115, baseType: !145, size: 1, offset: 28, flags: DIFlagBitField, extraData: i64 8)
!259 = !DIDerivedType(tag: DW_TAG_member, name: "IsInternalRead", scope: !248, file: !247, line: 126, baseType: !145, size: 1, offset: 29, flags: DIFlagBitField, extraData: i64 8)
!260 = !DIDerivedType(tag: DW_TAG_member, name: "IsEarlyClobber", scope: !248, file: !247, line: 131, baseType: !145, size: 1, offset: 30, flags: DIFlagBitField, extraData: i64 8)
!261 = !DIDerivedType(tag: DW_TAG_member, name: "IsDebug", scope: !248, file: !247, line: 135, baseType: !145, size: 1, offset: 31, flags: DIFlagBitField, extraData: i64 8)
!262 = !DIDerivedType(tag: DW_TAG_member, name: "SmallContents", scope: !248, file: !247, line: 144, baseType: !263, size: 32, offset: 32)
!263 = distinct !DICompositeType(tag: DW_TAG_union_type, scope: !248, file: !247, line: 141, size: 32, flags: DIFlagTypePassByValue, elements: !264, identifier: "_ZTSN4llvm14MachineOperandUt_E")
!264 = !{!265, !266}
!265 = !DIDerivedType(tag: DW_TAG_member, name: "RegNo", scope: !263, file: !247, line: 142, baseType: !6, size: 32)
!266 = !DIDerivedType(tag: DW_TAG_member, name: "OffsetLo", scope: !263, file: !247, line: 143, baseType: !6, size: 32)
!267 = !DIDerivedType(tag: DW_TAG_member, name: "ParentMI", scope: !248, file: !247, line: 148, baseType: !268, size: 64, offset: 64)
!268 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !269, size: 64)
!269 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MachineInstr", scope: !14, file: !270, line: 50, size: 512, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12MachineInstrE")
!270 = !DIFile(filename: "llvm34/include/llvm/CodeGen/MachineInstr.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "aa69bcafce289978b7ceed072d605684")
!271 = !DIDerivedType(tag: DW_TAG_member, name: "Contents", scope: !248, file: !247, line: 178, baseType: !272, size: 128, offset: 128)
!272 = distinct !DICompositeType(tag: DW_TAG_union_type, scope: !248, file: !247, line: 151, size: 128, flags: DIFlagTypePassByValue, elements: !273, identifier: "_ZTSN4llvm14MachineOperandUt0_E")
!273 = !{!274, !275, !279, !283, !289, !295, !300, !303, !309}
!274 = !DIDerivedType(tag: DW_TAG_member, name: "MBB", scope: !272, file: !247, line: 152, baseType: !197, size: 64)
!275 = !DIDerivedType(tag: DW_TAG_member, name: "CFP", scope: !272, file: !247, line: 153, baseType: !276, size: 64)
!276 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !277, size: 64)
!277 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !278)
!278 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ConstantFP", scope: !14, file: !247, line: 23, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm10ConstantFPE")
!279 = !DIDerivedType(tag: DW_TAG_member, name: "CI", scope: !272, file: !247, line: 154, baseType: !280, size: 64)
!280 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !281, size: 64)
!281 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !282)
!282 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ConstantInt", scope: !14, file: !247, line: 24, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm11ConstantIntE")
!283 = !DIDerivedType(tag: DW_TAG_member, name: "ImmVal", scope: !272, file: !247, line: 155, baseType: !284, size: 64)
!284 = !DIDerivedType(tag: DW_TAG_typedef, name: "int64_t", file: !285, line: 27, baseType: !286)
!285 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h", directory: "", checksumkind: CSK_MD5, checksum: "457547631e07cd24d9a14c8410e28e57")
!286 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int64_t", file: !287, line: 43, baseType: !288)
!287 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types.h", directory: "", checksumkind: CSK_MD5, checksum: "25679ba19d359e314e48661b21f5aa1f")
!288 = !DIBasicType(name: "long", size: 64, encoding: DW_ATE_signed)
!289 = !DIDerivedType(tag: DW_TAG_member, name: "RegMask", scope: !272, file: !247, line: 156, baseType: !290, size: 64)
!290 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !291, size: 64)
!291 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !292)
!292 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint32_t", file: !293, line: 26, baseType: !294)
!293 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h", directory: "", checksumkind: CSK_MD5, checksum: "9754ebe022edbe8d7928fa709e442f0d")
!294 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint32_t", file: !287, line: 41, baseType: !6)
!295 = !DIDerivedType(tag: DW_TAG_member, name: "MD", scope: !272, file: !247, line: 157, baseType: !296, size: 64)
!296 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !297, size: 64)
!297 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !298)
!298 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MDNode", scope: !14, file: !299, line: 73, size: 448, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm6MDNodeE")
!299 = !DIFile(filename: "llvm34/include/llvm/IR/Metadata.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "1be96067847fad606fafd23e7d94e7e8")
!300 = !DIDerivedType(tag: DW_TAG_member, name: "Sym", scope: !272, file: !247, line: 158, baseType: !301, size: 64)
!301 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !302, size: 64)
!302 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MCSymbol", scope: !14, file: !247, line: 34, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm8MCSymbolE")
!303 = !DIDerivedType(tag: DW_TAG_member, name: "Reg", scope: !272, file: !247, line: 164, baseType: !304, size: 128)
!304 = distinct !DICompositeType(tag: DW_TAG_structure_type, scope: !272, file: !247, line: 160, size: 128, flags: DIFlagTypePassByValue, elements: !305, identifier: "_ZTSN4llvm14MachineOperandUt0_Ut_E")
!305 = !{!306, !308}
!306 = !DIDerivedType(tag: DW_TAG_member, name: "Prev", scope: !304, file: !247, line: 162, baseType: !307, size: 64)
!307 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !248, size: 64)
!308 = !DIDerivedType(tag: DW_TAG_member, name: "Next", scope: !304, file: !247, line: 163, baseType: !307, size: 64, offset: 64)
!309 = !DIDerivedType(tag: DW_TAG_member, name: "OffsetedInfo", scope: !272, file: !247, line: 177, baseType: !310, size: 128)
!310 = distinct !DICompositeType(tag: DW_TAG_structure_type, scope: !272, file: !247, line: 168, size: 128, flags: DIFlagTypePassByValue, elements: !311, identifier: "_ZTSN4llvm14MachineOperandUt0_Ut0_E")
!311 = !{!312, !329}
!312 = !DIDerivedType(tag: DW_TAG_member, name: "Val", scope: !310, file: !247, line: 174, baseType: !313, size: 64)
!313 = distinct !DICompositeType(tag: DW_TAG_union_type, scope: !310, file: !247, line: 169, size: 64, flags: DIFlagTypePassByValue, elements: !314, identifier: "_ZTSN4llvm14MachineOperandUt0_Ut0_Ut_E")
!314 = !{!315, !316, !320, !325}
!315 = !DIDerivedType(tag: DW_TAG_member, name: "Index", scope: !313, file: !247, line: 170, baseType: !32, size: 32)
!316 = !DIDerivedType(tag: DW_TAG_member, name: "SymbolName", scope: !313, file: !247, line: 171, baseType: !317, size: 64)
!317 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !318, size: 64)
!318 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !319)
!319 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
!320 = !DIDerivedType(tag: DW_TAG_member, name: "GV", scope: !313, file: !247, line: 172, baseType: !321, size: 64)
!321 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !322, size: 64)
!322 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !323)
!323 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "GlobalValue", scope: !14, file: !324, line: 29, size: 768, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm11GlobalValueE")
!324 = !DIFile(filename: "llvm34/include/llvm/IR/GlobalValue.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "f4611cde2721012c3cd54bde1f5421d8")
!325 = !DIDerivedType(tag: DW_TAG_member, name: "BA", scope: !313, file: !247, line: 173, baseType: !326, size: 64)
!326 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !327, size: 64)
!327 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !328)
!328 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "BlockAddress", scope: !14, file: !247, line: 22, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12BlockAddressE")
!329 = !DIDerivedType(tag: DW_TAG_member, name: "OffsetHi", scope: !310, file: !247, line: 176, baseType: !32, size: 32, offset: 64)
!330 = !DISubprogram(name: "MachineOperand", scope: !248, file: !247, line: 180, type: !331, scopeLine: 180, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!331 = !DISubroutineType(types: !332)
!332 = !{null, !333, !246}
!333 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !248, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!334 = !DISubprogram(name: "getType", linkageName: "_ZNK4llvm14MachineOperand7getTypeEv", scope: !248, file: !247, line: 185, type: !335, scopeLine: 185, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!335 = !DISubroutineType(types: !336)
!336 = !{!246, !337}
!337 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !338, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!338 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !248)
!339 = !DISubprogram(name: "getTargetFlags", linkageName: "_ZNK4llvm14MachineOperand14getTargetFlagsEv", scope: !248, file: !247, line: 187, type: !340, scopeLine: 187, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!340 = !DISubroutineType(types: !341)
!341 = !{!6, !337}
!342 = !DISubprogram(name: "setTargetFlags", linkageName: "_ZN4llvm14MachineOperand14setTargetFlagsEj", scope: !248, file: !247, line: 190, type: !343, scopeLine: 190, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!343 = !DISubroutineType(types: !344)
!344 = !{null, !333, !6}
!345 = !DISubprogram(name: "addTargetFlag", linkageName: "_ZN4llvm14MachineOperand13addTargetFlagEj", scope: !248, file: !247, line: 195, type: !343, scopeLine: 195, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!346 = !DISubprogram(name: "getParent", linkageName: "_ZN4llvm14MachineOperand9getParentEv", scope: !248, file: !247, line: 204, type: !347, scopeLine: 204, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!347 = !DISubroutineType(types: !348)
!348 = !{!268, !333}
!349 = !DISubprogram(name: "getParent", linkageName: "_ZNK4llvm14MachineOperand9getParentEv", scope: !248, file: !247, line: 205, type: !350, scopeLine: 205, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!350 = !DISubroutineType(types: !351)
!351 = !{!352, !337}
!352 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !353, size: 64)
!353 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !269)
!354 = !DISubprogram(name: "clearParent", linkageName: "_ZN4llvm14MachineOperand11clearParentEv", scope: !248, file: !247, line: 215, type: !355, scopeLine: 215, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!355 = !DISubroutineType(types: !356)
!356 = !{null, !333}
!357 = !DISubprogram(name: "print", linkageName: "_ZNK4llvm14MachineOperand5printERNS_11raw_ostreamEPKNS_13TargetMachineE", scope: !248, file: !247, line: 217, type: !358, scopeLine: 217, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!358 = !DISubroutineType(types: !359)
!359 = !{null, !337, !360, !363}
!360 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !361, size: 64)
!361 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "raw_ostream", scope: !14, file: !362, line: 31, size: 320, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm11raw_ostreamE")
!362 = !DIFile(filename: "llvm34/include/llvm/Support/raw_ostream.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "2bb663449bd8797aa5193bb52a5154a0")
!363 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !364, size: 64)
!364 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !365)
!365 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "TargetMachine", scope: !14, file: !366, line: 61, size: 1536, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm13TargetMachineE")
!366 = !DIFile(filename: "llvm34/include/llvm/Target/TargetMachine.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "cd69e77639551236fdae0aee19eb7096")
!367 = !DISubprogram(name: "isReg", linkageName: "_ZNK4llvm14MachineOperand5isRegEv", scope: !248, file: !247, line: 224, type: !368, scopeLine: 224, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!368 = !DISubroutineType(types: !369)
!369 = !{!145, !337}
!370 = !DISubprogram(name: "isImm", linkageName: "_ZNK4llvm14MachineOperand5isImmEv", scope: !248, file: !247, line: 226, type: !368, scopeLine: 226, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!371 = !DISubprogram(name: "isCImm", linkageName: "_ZNK4llvm14MachineOperand6isCImmEv", scope: !248, file: !247, line: 228, type: !368, scopeLine: 228, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!372 = !DISubprogram(name: "isFPImm", linkageName: "_ZNK4llvm14MachineOperand7isFPImmEv", scope: !248, file: !247, line: 230, type: !368, scopeLine: 230, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!373 = !DISubprogram(name: "isMBB", linkageName: "_ZNK4llvm14MachineOperand5isMBBEv", scope: !248, file: !247, line: 232, type: !368, scopeLine: 232, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!374 = !DISubprogram(name: "isFI", linkageName: "_ZNK4llvm14MachineOperand4isFIEv", scope: !248, file: !247, line: 234, type: !368, scopeLine: 234, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!375 = !DISubprogram(name: "isCPI", linkageName: "_ZNK4llvm14MachineOperand5isCPIEv", scope: !248, file: !247, line: 236, type: !368, scopeLine: 236, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!376 = !DISubprogram(name: "isTargetIndex", linkageName: "_ZNK4llvm14MachineOperand13isTargetIndexEv", scope: !248, file: !247, line: 238, type: !368, scopeLine: 238, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!377 = !DISubprogram(name: "isJTI", linkageName: "_ZNK4llvm14MachineOperand5isJTIEv", scope: !248, file: !247, line: 240, type: !368, scopeLine: 240, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!378 = !DISubprogram(name: "isGlobal", linkageName: "_ZNK4llvm14MachineOperand8isGlobalEv", scope: !248, file: !247, line: 242, type: !368, scopeLine: 242, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!379 = !DISubprogram(name: "isSymbol", linkageName: "_ZNK4llvm14MachineOperand8isSymbolEv", scope: !248, file: !247, line: 244, type: !368, scopeLine: 244, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!380 = !DISubprogram(name: "isBlockAddress", linkageName: "_ZNK4llvm14MachineOperand14isBlockAddressEv", scope: !248, file: !247, line: 246, type: !368, scopeLine: 246, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!381 = !DISubprogram(name: "isRegMask", linkageName: "_ZNK4llvm14MachineOperand9isRegMaskEv", scope: !248, file: !247, line: 248, type: !368, scopeLine: 248, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!382 = !DISubprogram(name: "isMetadata", linkageName: "_ZNK4llvm14MachineOperand10isMetadataEv", scope: !248, file: !247, line: 250, type: !368, scopeLine: 250, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!383 = !DISubprogram(name: "isMCSymbol", linkageName: "_ZNK4llvm14MachineOperand10isMCSymbolEv", scope: !248, file: !247, line: 251, type: !368, scopeLine: 251, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!384 = !DISubprogram(name: "getReg", linkageName: "_ZNK4llvm14MachineOperand6getRegEv", scope: !248, file: !247, line: 259, type: !340, scopeLine: 259, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!385 = !DISubprogram(name: "getSubReg", linkageName: "_ZNK4llvm14MachineOperand9getSubRegEv", scope: !248, file: !247, line: 264, type: !340, scopeLine: 264, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!386 = !DISubprogram(name: "isUse", linkageName: "_ZNK4llvm14MachineOperand5isUseEv", scope: !248, file: !247, line: 269, type: !368, scopeLine: 269, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!387 = !DISubprogram(name: "isDef", linkageName: "_ZNK4llvm14MachineOperand5isDefEv", scope: !248, file: !247, line: 274, type: !368, scopeLine: 274, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!388 = !DISubprogram(name: "isImplicit", linkageName: "_ZNK4llvm14MachineOperand10isImplicitEv", scope: !248, file: !247, line: 279, type: !368, scopeLine: 279, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!389 = !DISubprogram(name: "isDead", linkageName: "_ZNK4llvm14MachineOperand6isDeadEv", scope: !248, file: !247, line: 284, type: !368, scopeLine: 284, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!390 = !DISubprogram(name: "isKill", linkageName: "_ZNK4llvm14MachineOperand6isKillEv", scope: !248, file: !247, line: 289, type: !368, scopeLine: 289, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!391 = !DISubprogram(name: "isUndef", linkageName: "_ZNK4llvm14MachineOperand7isUndefEv", scope: !248, file: !247, line: 294, type: !368, scopeLine: 294, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!392 = !DISubprogram(name: "isInternalRead", linkageName: "_ZNK4llvm14MachineOperand14isInternalReadEv", scope: !248, file: !247, line: 299, type: !368, scopeLine: 299, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!393 = !DISubprogram(name: "isEarlyClobber", linkageName: "_ZNK4llvm14MachineOperand14isEarlyClobberEv", scope: !248, file: !247, line: 304, type: !368, scopeLine: 304, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!394 = !DISubprogram(name: "isTied", linkageName: "_ZNK4llvm14MachineOperand6isTiedEv", scope: !248, file: !247, line: 309, type: !368, scopeLine: 309, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!395 = !DISubprogram(name: "isDebug", linkageName: "_ZNK4llvm14MachineOperand7isDebugEv", scope: !248, file: !247, line: 314, type: !368, scopeLine: 314, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!396 = !DISubprogram(name: "readsReg", linkageName: "_ZNK4llvm14MachineOperand8readsRegEv", scope: !248, file: !247, line: 326, type: !368, scopeLine: 326, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!397 = !DISubprogram(name: "setReg", linkageName: "_ZN4llvm14MachineOperand6setRegEj", scope: !248, file: !247, line: 337, type: !343, scopeLine: 337, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!398 = !DISubprogram(name: "setSubReg", linkageName: "_ZN4llvm14MachineOperand9setSubRegEj", scope: !248, file: !247, line: 339, type: !343, scopeLine: 339, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!399 = !DISubprogram(name: "substVirtReg", linkageName: "_ZN4llvm14MachineOperand12substVirtRegEjjRKNS_18TargetRegisterInfoE", scope: !248, file: !247, line: 350, type: !400, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!400 = !DISubroutineType(types: !401)
!401 = !{null, !333, !6, !6, !402}
!402 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !403, size: 64)
!403 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !404)
!404 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "TargetRegisterInfo", scope: !14, file: !405, line: 219, size: 1792, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm18TargetRegisterInfoE")
!405 = !DIFile(filename: "llvm34/include/llvm/Target/TargetRegisterInfo.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "de4919bc3ce91a6443d0364ab49e1947")
!406 = !DISubprogram(name: "substPhysReg", linkageName: "_ZN4llvm14MachineOperand12substPhysRegEjRKNS_18TargetRegisterInfoE", scope: !248, file: !247, line: 356, type: !407, scopeLine: 356, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!407 = !DISubroutineType(types: !408)
!408 = !{null, !333, !6, !402}
!409 = !DISubprogram(name: "setIsUse", linkageName: "_ZN4llvm14MachineOperand8setIsUseEb", scope: !248, file: !247, line: 358, type: !410, scopeLine: 358, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!410 = !DISubroutineType(types: !411)
!411 = !{null, !333, !145}
!412 = !DISubprogram(name: "setIsDef", linkageName: "_ZN4llvm14MachineOperand8setIsDefEb", scope: !248, file: !247, line: 360, type: !410, scopeLine: 360, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!413 = !DISubprogram(name: "setImplicit", linkageName: "_ZN4llvm14MachineOperand11setImplicitEb", scope: !248, file: !247, line: 362, type: !410, scopeLine: 362, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!414 = !DISubprogram(name: "setIsKill", linkageName: "_ZN4llvm14MachineOperand9setIsKillEb", scope: !248, file: !247, line: 367, type: !410, scopeLine: 367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!415 = !DISubprogram(name: "setIsDead", linkageName: "_ZN4llvm14MachineOperand9setIsDeadEb", scope: !248, file: !247, line: 373, type: !410, scopeLine: 373, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!416 = !DISubprogram(name: "setIsUndef", linkageName: "_ZN4llvm14MachineOperand10setIsUndefEb", scope: !248, file: !247, line: 378, type: !410, scopeLine: 378, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!417 = !DISubprogram(name: "setIsInternalRead", linkageName: "_ZN4llvm14MachineOperand17setIsInternalReadEb", scope: !248, file: !247, line: 383, type: !410, scopeLine: 383, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!418 = !DISubprogram(name: "setIsEarlyClobber", linkageName: "_ZN4llvm14MachineOperand17setIsEarlyClobberEb", scope: !248, file: !247, line: 388, type: !410, scopeLine: 388, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!419 = !DISubprogram(name: "setIsDebug", linkageName: "_ZN4llvm14MachineOperand10setIsDebugEb", scope: !248, file: !247, line: 393, type: !410, scopeLine: 393, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!420 = !DISubprogram(name: "getImm", linkageName: "_ZNK4llvm14MachineOperand6getImmEv", scope: !248, file: !247, line: 402, type: !421, scopeLine: 402, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!421 = !DISubroutineType(types: !422)
!422 = !{!284, !337}
!423 = !DISubprogram(name: "getCImm", linkageName: "_ZNK4llvm14MachineOperand7getCImmEv", scope: !248, file: !247, line: 407, type: !424, scopeLine: 407, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!424 = !DISubroutineType(types: !425)
!425 = !{!280, !337}
!426 = !DISubprogram(name: "getFPImm", linkageName: "_ZNK4llvm14MachineOperand8getFPImmEv", scope: !248, file: !247, line: 412, type: !427, scopeLine: 412, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!427 = !DISubroutineType(types: !428)
!428 = !{!276, !337}
!429 = !DISubprogram(name: "getMBB", linkageName: "_ZNK4llvm14MachineOperand6getMBBEv", scope: !248, file: !247, line: 417, type: !430, scopeLine: 417, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!430 = !DISubroutineType(types: !431)
!431 = !{!197, !337}
!432 = !DISubprogram(name: "getIndex", linkageName: "_ZNK4llvm14MachineOperand8getIndexEv", scope: !248, file: !247, line: 422, type: !433, scopeLine: 422, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!433 = !DISubroutineType(types: !434)
!434 = !{!32, !337}
!435 = !DISubprogram(name: "getGlobal", linkageName: "_ZNK4llvm14MachineOperand9getGlobalEv", scope: !248, file: !247, line: 428, type: !436, scopeLine: 428, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!436 = !DISubroutineType(types: !437)
!437 = !{!321, !337}
!438 = !DISubprogram(name: "getBlockAddress", linkageName: "_ZNK4llvm14MachineOperand15getBlockAddressEv", scope: !248, file: !247, line: 433, type: !439, scopeLine: 433, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!439 = !DISubroutineType(types: !440)
!440 = !{!326, !337}
!441 = !DISubprogram(name: "getMCSymbol", linkageName: "_ZNK4llvm14MachineOperand11getMCSymbolEv", scope: !248, file: !247, line: 438, type: !442, scopeLine: 438, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!442 = !DISubroutineType(types: !443)
!443 = !{!301, !337}
!444 = !DISubprogram(name: "getOffset", linkageName: "_ZNK4llvm14MachineOperand9getOffsetEv", scope: !248, file: !247, line: 445, type: !421, scopeLine: 445, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!445 = !DISubprogram(name: "getSymbolName", linkageName: "_ZNK4llvm14MachineOperand13getSymbolNameEv", scope: !248, file: !247, line: 452, type: !446, scopeLine: 452, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!446 = !DISubroutineType(types: !447)
!447 = !{!317, !337}
!448 = !DISubprogram(name: "clobbersPhysReg", linkageName: "_ZN4llvm14MachineOperand15clobbersPhysRegEPKjj", scope: !248, file: !247, line: 461, type: !449, scopeLine: 461, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!449 = !DISubroutineType(types: !450)
!450 = !{!145, !290, !6}
!451 = !DISubprogram(name: "clobbersPhysReg", linkageName: "_ZNK4llvm14MachineOperand15clobbersPhysRegEj", scope: !248, file: !247, line: 468, type: !452, scopeLine: 468, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!452 = !DISubroutineType(types: !453)
!453 = !{!145, !337, !6}
!454 = !DISubprogram(name: "getRegMask", linkageName: "_ZNK4llvm14MachineOperand10getRegMaskEv", scope: !248, file: !247, line: 474, type: !455, scopeLine: 474, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!455 = !DISubroutineType(types: !456)
!456 = !{!290, !337}
!457 = !DISubprogram(name: "getMetadata", linkageName: "_ZNK4llvm14MachineOperand11getMetadataEv", scope: !248, file: !247, line: 479, type: !458, scopeLine: 479, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!458 = !DISubroutineType(types: !459)
!459 = !{!296, !337}
!460 = !DISubprogram(name: "setImm", linkageName: "_ZN4llvm14MachineOperand6setImmEl", scope: !248, file: !247, line: 488, type: !461, scopeLine: 488, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!461 = !DISubroutineType(types: !462)
!462 = !{null, !333, !284}
!463 = !DISubprogram(name: "setOffset", linkageName: "_ZN4llvm14MachineOperand9setOffsetEl", scope: !248, file: !247, line: 493, type: !461, scopeLine: 493, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!464 = !DISubprogram(name: "setIndex", linkageName: "_ZN4llvm14MachineOperand8setIndexEi", scope: !248, file: !247, line: 500, type: !465, scopeLine: 500, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!465 = !DISubroutineType(types: !466)
!466 = !{null, !333, !32}
!467 = !DISubprogram(name: "setMBB", linkageName: "_ZN4llvm14MachineOperand6setMBBEPNS_17MachineBasicBlockE", scope: !248, file: !247, line: 506, type: !468, scopeLine: 506, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!468 = !DISubroutineType(types: !469)
!469 = !{null, !333, !197}
!470 = !DISubprogram(name: "isIdenticalTo", linkageName: "_ZNK4llvm14MachineOperand13isIdenticalToERKS0_", scope: !248, file: !247, line: 517, type: !471, scopeLine: 517, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!471 = !DISubroutineType(types: !472)
!472 = !{!145, !337, !473}
!473 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !338, size: 64)
!474 = !DISubprogram(name: "ChangeToImmediate", linkageName: "_ZN4llvm14MachineOperand17ChangeToImmediateEl", scope: !248, file: !247, line: 529, type: !461, scopeLine: 529, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!475 = !DISubprogram(name: "ChangeToRegister", linkageName: "_ZN4llvm14MachineOperand16ChangeToRegisterEjbbbbbb", scope: !248, file: !247, line: 534, type: !476, scopeLine: 534, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!476 = !DISubroutineType(types: !477)
!477 = !{null, !333, !6, !145, !145, !145, !145, !145, !145}
!478 = !DISubprogram(name: "CreateImm", linkageName: "_ZN4llvm14MachineOperand9CreateImmEl", scope: !248, file: !247, line: 542, type: !479, scopeLine: 542, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!479 = !DISubroutineType(types: !480)
!480 = !{!248, !284}
!481 = !DISubprogram(name: "CreateCImm", linkageName: "_ZN4llvm14MachineOperand10CreateCImmEPKNS_11ConstantIntE", scope: !248, file: !247, line: 548, type: !482, scopeLine: 548, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!482 = !DISubroutineType(types: !483)
!483 = !{!248, !280}
!484 = !DISubprogram(name: "CreateFPImm", linkageName: "_ZN4llvm14MachineOperand11CreateFPImmEPKNS_10ConstantFPE", scope: !248, file: !247, line: 554, type: !485, scopeLine: 554, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!485 = !DISubroutineType(types: !486)
!486 = !{!248, !276}
!487 = !DISubprogram(name: "CreateReg", linkageName: "_ZN4llvm14MachineOperand9CreateRegEjbbbbbbjbb", scope: !248, file: !247, line: 560, type: !488, scopeLine: 560, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!488 = !DISubroutineType(types: !489)
!489 = !{!248, !6, !145, !145, !145, !145, !145, !145, !6, !145, !145}
!490 = !DISubprogram(name: "CreateMBB", linkageName: "_ZN4llvm14MachineOperand9CreateMBBEPNS_17MachineBasicBlockEh", scope: !248, file: !247, line: 585, type: !491, scopeLine: 585, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!491 = !DISubroutineType(types: !492)
!492 = !{!248, !197, !251}
!493 = !DISubprogram(name: "CreateFI", linkageName: "_ZN4llvm14MachineOperand8CreateFIEi", scope: !248, file: !247, line: 592, type: !494, scopeLine: 592, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!494 = !DISubroutineType(types: !495)
!495 = !{!248, !32}
!496 = !DISubprogram(name: "CreateCPI", linkageName: "_ZN4llvm14MachineOperand9CreateCPIEjih", scope: !248, file: !247, line: 597, type: !497, scopeLine: 597, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!497 = !DISubroutineType(types: !498)
!498 = !{!248, !6, !32, !251}
!499 = !DISubprogram(name: "CreateTargetIndex", linkageName: "_ZN4llvm14MachineOperand17CreateTargetIndexEjlh", scope: !248, file: !247, line: 605, type: !500, scopeLine: 605, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!500 = !DISubroutineType(types: !501)
!501 = !{!248, !6, !284, !251}
!502 = !DISubprogram(name: "CreateJTI", linkageName: "_ZN4llvm14MachineOperand9CreateJTIEjh", scope: !248, file: !247, line: 613, type: !503, scopeLine: 613, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!503 = !DISubroutineType(types: !504)
!504 = !{!248, !6, !251}
!505 = !DISubprogram(name: "CreateGA", linkageName: "_ZN4llvm14MachineOperand8CreateGAEPKNS_11GlobalValueElh", scope: !248, file: !247, line: 620, type: !506, scopeLine: 620, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!506 = !DISubroutineType(types: !507)
!507 = !{!248, !321, !284, !251}
!508 = !DISubprogram(name: "CreateES", linkageName: "_ZN4llvm14MachineOperand8CreateESEPKch", scope: !248, file: !247, line: 628, type: !509, scopeLine: 628, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!509 = !DISubroutineType(types: !510)
!510 = !{!248, !317, !251}
!511 = !DISubprogram(name: "CreateBA", linkageName: "_ZN4llvm14MachineOperand8CreateBAEPKNS_12BlockAddressElh", scope: !248, file: !247, line: 636, type: !512, scopeLine: 636, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!512 = !DISubroutineType(types: !513)
!513 = !{!248, !326, !284, !251}
!514 = !DISubprogram(name: "CreateRegMask", linkageName: "_ZN4llvm14MachineOperand13CreateRegMaskEPKj", scope: !248, file: !247, line: 656, type: !515, scopeLine: 656, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!515 = !DISubroutineType(types: !516)
!516 = !{!248, !290}
!517 = !DISubprogram(name: "CreateMetadata", linkageName: "_ZN4llvm14MachineOperand14CreateMetadataEPKNS_6MDNodeE", scope: !248, file: !247, line: 662, type: !518, scopeLine: 662, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!518 = !DISubroutineType(types: !519)
!519 = !{!248, !296}
!520 = !DISubprogram(name: "CreateMCSymbol", linkageName: "_ZN4llvm14MachineOperand14CreateMCSymbolEPNS_8MCSymbolE", scope: !248, file: !247, line: 668, type: !521, scopeLine: 668, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!521 = !DISubroutineType(types: !522)
!522 = !{!248, !301}
!523 = !DISubprogram(name: "isOnRegUseList", linkageName: "_ZNK4llvm14MachineOperand14isOnRegUseListEv", scope: !248, file: !247, line: 684, type: !368, scopeLine: 684, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!524 = !{!525, !526, !527, !528, !529, !530, !531, !532, !533, !534, !535, !536, !537, !538, !539}
!525 = !DIEnumerator(name: "MO_Register", value: 0, isUnsigned: true)
!526 = !DIEnumerator(name: "MO_Immediate", value: 1, isUnsigned: true)
!527 = !DIEnumerator(name: "MO_CImmediate", value: 2, isUnsigned: true)
!528 = !DIEnumerator(name: "MO_FPImmediate", value: 3, isUnsigned: true)
!529 = !DIEnumerator(name: "MO_MachineBasicBlock", value: 4, isUnsigned: true)
!530 = !DIEnumerator(name: "MO_FrameIndex", value: 5, isUnsigned: true)
!531 = !DIEnumerator(name: "MO_ConstantPoolIndex", value: 6, isUnsigned: true)
!532 = !DIEnumerator(name: "MO_TargetIndex", value: 7, isUnsigned: true)
!533 = !DIEnumerator(name: "MO_JumpTableIndex", value: 8, isUnsigned: true)
!534 = !DIEnumerator(name: "MO_ExternalSymbol", value: 9, isUnsigned: true)
!535 = !DIEnumerator(name: "MO_GlobalAddress", value: 10, isUnsigned: true)
!536 = !DIEnumerator(name: "MO_BlockAddress", value: 11, isUnsigned: true)
!537 = !DIEnumerator(name: "MO_RegisterMask", value: 12, isUnsigned: true)
!538 = !DIEnumerator(name: "MO_Metadata", value: 13, isUnsigned: true)
!539 = !DIEnumerator(name: "MO_MCSymbol", value: 14, isUnsigned: true)
!540 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "MIFlag", scope: !269, file: !270, line: 62, baseType: !6, size: 32, elements: !541, identifier: "_ZTSN4llvm12MachineInstr6MIFlagE")
!541 = !{!542, !543, !544, !545}
!542 = !DIEnumerator(name: "NoFlags", value: 0, isUnsigned: true)
!543 = !DIEnumerator(name: "FrameSetup", value: 1, isUnsigned: true)
!544 = !DIEnumerator(name: "BundledPred", value: 2, isUnsigned: true)
!545 = !DIEnumerator(name: "BundledSucc", value: 4, isUnsigned: true)
!546 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "QueryType", scope: !269, file: !270, line: 304, baseType: !6, size: 32, elements: !547, identifier: "_ZTSN4llvm12MachineInstr9QueryTypeE")
!547 = !{!548, !549, !550}
!548 = !DIEnumerator(name: "IgnoreBundle", value: 0, isUnsigned: true)
!549 = !DIEnumerator(name: "AnyInBundle", value: 1, isUnsigned: true)
!550 = !DIEnumerator(name: "AllInBundle", value: 2, isUnsigned: true)
!551 = !DICompositeType(tag: DW_TAG_enumeration_type, scope: !553, file: !552, line: 100, baseType: !6, size: 32, elements: !554)
!552 = !DIFile(filename: "llvm34/include/llvm/MC/MCInstrDesc.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "817305767b5005bf7c982edca011af7c")
!553 = !DINamespace(name: "MCID", scope: !14)
!554 = !{!555, !556, !557, !558, !559, !560, !561, !562, !563, !564, !565, !566, !567, !568, !569, !570, !571, !572, !573, !574, !575, !576, !577, !578, !579, !580, !581, !582}
!555 = !DIEnumerator(name: "Variadic", value: 0, isUnsigned: true)
!556 = !DIEnumerator(name: "HasOptionalDef", value: 1, isUnsigned: true)
!557 = !DIEnumerator(name: "Pseudo", value: 2, isUnsigned: true)
!558 = !DIEnumerator(name: "Return", value: 3, isUnsigned: true)
!559 = !DIEnumerator(name: "Call", value: 4, isUnsigned: true)
!560 = !DIEnumerator(name: "Barrier", value: 5, isUnsigned: true)
!561 = !DIEnumerator(name: "Terminator", value: 6, isUnsigned: true)
!562 = !DIEnumerator(name: "Branch", value: 7, isUnsigned: true)
!563 = !DIEnumerator(name: "IndirectBranch", value: 8, isUnsigned: true)
!564 = !DIEnumerator(name: "Compare", value: 9, isUnsigned: true)
!565 = !DIEnumerator(name: "MoveImm", value: 10, isUnsigned: true)
!566 = !DIEnumerator(name: "Bitcast", value: 11, isUnsigned: true)
!567 = !DIEnumerator(name: "Select", value: 12, isUnsigned: true)
!568 = !DIEnumerator(name: "DelaySlot", value: 13, isUnsigned: true)
!569 = !DIEnumerator(name: "FoldableAsLoad", value: 14, isUnsigned: true)
!570 = !DIEnumerator(name: "MayLoad", value: 15, isUnsigned: true)
!571 = !DIEnumerator(name: "MayStore", value: 16, isUnsigned: true)
!572 = !DIEnumerator(name: "Predicable", value: 17, isUnsigned: true)
!573 = !DIEnumerator(name: "NotDuplicable", value: 18, isUnsigned: true)
!574 = !DIEnumerator(name: "UnmodeledSideEffects", value: 19, isUnsigned: true)
!575 = !DIEnumerator(name: "Commutable", value: 20, isUnsigned: true)
!576 = !DIEnumerator(name: "ConvertibleTo3Addr", value: 21, isUnsigned: true)
!577 = !DIEnumerator(name: "UsesCustomInserter", value: 22, isUnsigned: true)
!578 = !DIEnumerator(name: "HasPostISelHook", value: 23, isUnsigned: true)
!579 = !DIEnumerator(name: "Rematerializable", value: 24, isUnsigned: true)
!580 = !DIEnumerator(name: "CheapAsAMove", value: 25, isUnsigned: true)
!581 = !DIEnumerator(name: "ExtraSrcRegAllocReq", value: 26, isUnsigned: true)
!582 = !DIEnumerator(name: "ExtraDefRegAllocReq", value: 27, isUnsigned: true)
!583 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "OperandConstraint", scope: !584, file: !552, line: 31, baseType: !6, size: 32, elements: !585, identifier: "_ZTSN4llvm4MCOI17OperandConstraintE")
!584 = !DINamespace(name: "MCOI", scope: !14)
!585 = !{!586, !587}
!586 = !DIEnumerator(name: "TIED_TO", value: 0, isUnsigned: true)
!587 = !DIEnumerator(name: "EARLY_CLOBBER", value: 1, isUnsigned: true)
!588 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "AttrIndex", scope: !590, file: !589, line: 204, baseType: !6, size: 32, elements: !591, identifier: "_ZTSN4llvm12AttributeSet9AttrIndexE")
!589 = !DIFile(filename: "llvm34/include/llvm/IR/Attributes.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "c9039b55a51f72c16020342550e3bea1")
!590 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "AttributeSet", scope: !14, file: !589, line: 202, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12AttributeSetE")
!591 = !{!592, !593}
!592 = !DIEnumerator(name: "ReturnIndex", value: 0, isUnsigned: true)
!593 = !DIEnumerator(name: "FunctionIndex", value: 4294967295, isUnsigned: true)
!594 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "AttrKind", scope: !595, file: !589, line: 64, baseType: !6, size: 32, elements: !596, identifier: "_ZTSN4llvm9Attribute8AttrKindE")
!595 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Attribute", scope: !14, file: !589, line: 45, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm9AttributeE")
!596 = !{!114, !597, !598, !599, !600, !601, !602, !603, !604, !605, !606, !607, !608, !609, !610, !611, !612, !613, !614, !615, !616, !617, !618, !619, !620, !621, !622, !623, !624, !625, !626, !627, !628, !629, !630, !631, !632, !633, !634}
!597 = !DIEnumerator(name: "Alignment", value: 1, isUnsigned: true)
!598 = !DIEnumerator(name: "AlwaysInline", value: 2, isUnsigned: true)
!599 = !DIEnumerator(name: "Builtin", value: 3, isUnsigned: true)
!600 = !DIEnumerator(name: "ByVal", value: 4, isUnsigned: true)
!601 = !DIEnumerator(name: "Cold", value: 5, isUnsigned: true)
!602 = !DIEnumerator(name: "InlineHint", value: 6, isUnsigned: true)
!603 = !DIEnumerator(name: "InReg", value: 7, isUnsigned: true)
!604 = !DIEnumerator(name: "MinSize", value: 8, isUnsigned: true)
!605 = !DIEnumerator(name: "Naked", value: 9, isUnsigned: true)
!606 = !DIEnumerator(name: "Nest", value: 10, isUnsigned: true)
!607 = !DIEnumerator(name: "NoAlias", value: 11, isUnsigned: true)
!608 = !DIEnumerator(name: "NoBuiltin", value: 12, isUnsigned: true)
!609 = !DIEnumerator(name: "NoCapture", value: 13, isUnsigned: true)
!610 = !DIEnumerator(name: "NoDuplicate", value: 14, isUnsigned: true)
!611 = !DIEnumerator(name: "NoImplicitFloat", value: 15, isUnsigned: true)
!612 = !DIEnumerator(name: "NoInline", value: 16, isUnsigned: true)
!613 = !DIEnumerator(name: "NonLazyBind", value: 17, isUnsigned: true)
!614 = !DIEnumerator(name: "NoRedZone", value: 18, isUnsigned: true)
!615 = !DIEnumerator(name: "NoReturn", value: 19, isUnsigned: true)
!616 = !DIEnumerator(name: "NoUnwind", value: 20, isUnsigned: true)
!617 = !DIEnumerator(name: "OptimizeForSize", value: 21, isUnsigned: true)
!618 = !DIEnumerator(name: "OptimizeNone", value: 22, isUnsigned: true)
!619 = !DIEnumerator(name: "ReadNone", value: 23, isUnsigned: true)
!620 = !DIEnumerator(name: "ReadOnly", value: 24, isUnsigned: true)
!621 = !DIEnumerator(name: "Returned", value: 25, isUnsigned: true)
!622 = !DIEnumerator(name: "ReturnsTwice", value: 26, isUnsigned: true)
!623 = !DIEnumerator(name: "SExt", value: 27, isUnsigned: true)
!624 = !DIEnumerator(name: "StackAlignment", value: 28, isUnsigned: true)
!625 = !DIEnumerator(name: "StackProtect", value: 29, isUnsigned: true)
!626 = !DIEnumerator(name: "StackProtectReq", value: 30, isUnsigned: true)
!627 = !DIEnumerator(name: "StackProtectStrong", value: 31, isUnsigned: true)
!628 = !DIEnumerator(name: "StructRet", value: 32, isUnsigned: true)
!629 = !DIEnumerator(name: "SanitizeAddress", value: 33, isUnsigned: true)
!630 = !DIEnumerator(name: "SanitizeThread", value: 34, isUnsigned: true)
!631 = !DIEnumerator(name: "SanitizeMemory", value: 35, isUnsigned: true)
!632 = !DIEnumerator(name: "UWTable", value: 36, isUnsigned: true)
!633 = !DIEnumerator(name: "ZExt", value: 37, isUnsigned: true)
!634 = !DIEnumerator(name: "EndAttrKinds", value: 38, isUnsigned: true)
!635 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !637, file: !636, line: 30, baseType: !6, size: 32, elements: !768, identifier: "_ZTSN4llvm9BitVectorUt_E")
!636 = !DIFile(filename: "llvm34/include/llvm/ADT/BitVector.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "5471169af44daed63e23f7fd85983c51")
!637 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "BitVector", scope: !14, file: !636, line: 27, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !638, identifier: "_ZTSN4llvm9BitVectorE")
!638 = !{!639, !643, !644, !645, !649, !652, !657, !661, !662, !666, !669, !670, !671, !672, !673, !676, !679, !680, !681, !684, !688, !691, !694, !695, !696, !697, !698, !699, !726, !729, !730, !733, !734, !735, !738, !739, !740, !741, !742, !745, !748, !751, !754, !755, !756, !757, !760, !763, !764, !765}
!639 = !DIDerivedType(tag: DW_TAG_member, name: "Bits", scope: !637, file: !636, line: 32, baseType: !640, size: 64)
!640 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !641, size: 64)
!641 = !DIDerivedType(tag: DW_TAG_typedef, name: "BitWord", scope: !637, file: !636, line: 28, baseType: !642)
!642 = !DIBasicType(name: "unsigned long", size: 64, encoding: DW_ATE_unsigned)
!643 = !DIDerivedType(tag: DW_TAG_member, name: "Size", scope: !637, file: !636, line: 33, baseType: !6, size: 32, offset: 64)
!644 = !DIDerivedType(tag: DW_TAG_member, name: "Capacity", scope: !637, file: !636, line: 34, baseType: !6, size: 32, offset: 96)
!645 = !DISubprogram(name: "BitVector", scope: !637, file: !636, line: 74, type: !646, scopeLine: 74, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!646 = !DISubroutineType(types: !647)
!647 = !{null, !648}
!648 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !637, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!649 = !DISubprogram(name: "BitVector", scope: !637, file: !636, line: 80, type: !650, scopeLine: 80, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!650 = !DISubroutineType(types: !651)
!651 = !{null, !648, !6, !145}
!652 = !DISubprogram(name: "BitVector", scope: !637, file: !636, line: 89, type: !653, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!653 = !DISubroutineType(types: !654)
!654 = !{null, !648, !655}
!655 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !656, size: 64)
!656 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !637)
!657 = !DISubprogram(name: "BitVector", scope: !637, file: !636, line: 102, type: !658, scopeLine: 102, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!658 = !DISubroutineType(types: !659)
!659 = !{null, !648, !660}
!660 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !637, size: 64)
!661 = !DISubprogram(name: "~BitVector", scope: !637, file: !636, line: 108, type: !646, scopeLine: 108, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!662 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm9BitVector5emptyEv", scope: !637, file: !636, line: 113, type: !663, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!663 = !DISubroutineType(types: !664)
!664 = !{!145, !665}
!665 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !656, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!666 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm9BitVector4sizeEv", scope: !637, file: !636, line: 116, type: !667, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!667 = !DISubroutineType(types: !668)
!668 = !{!6, !665}
!669 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9BitVector5countEv", scope: !637, file: !636, line: 119, type: !667, scopeLine: 119, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!670 = !DISubprogram(name: "any", linkageName: "_ZNK4llvm9BitVector3anyEv", scope: !637, file: !636, line: 132, type: !663, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!671 = !DISubprogram(name: "all", linkageName: "_ZNK4llvm9BitVector3allEv", scope: !637, file: !636, line: 140, type: !663, scopeLine: 140, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!672 = !DISubprogram(name: "none", linkageName: "_ZNK4llvm9BitVector4noneEv", scope: !637, file: !636, line: 153, type: !663, scopeLine: 153, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!673 = !DISubprogram(name: "find_first", linkageName: "_ZNK4llvm9BitVector10find_firstEv", scope: !637, file: !636, line: 159, type: !674, scopeLine: 159, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!674 = !DISubroutineType(types: !675)
!675 = !{!32, !665}
!676 = !DISubprogram(name: "find_next", linkageName: "_ZNK4llvm9BitVector9find_nextEj", scope: !637, file: !636, line: 173, type: !677, scopeLine: 173, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!677 = !DISubroutineType(types: !678)
!678 = !{!32, !665, !6}
!679 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm9BitVector5clearEv", scope: !637, file: !636, line: 205, type: !646, scopeLine: 205, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!680 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm9BitVector6resizeEjb", scope: !637, file: !636, line: 210, type: !650, scopeLine: 210, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!681 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm9BitVector7reserveEj", scope: !637, file: !636, line: 230, type: !682, scopeLine: 230, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!682 = !DISubroutineType(types: !683)
!683 = !{null, !648, !6}
!684 = !DISubprogram(name: "set", linkageName: "_ZN4llvm9BitVector3setEv", scope: !637, file: !636, line: 236, type: !685, scopeLine: 236, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!685 = !DISubroutineType(types: !686)
!686 = !{!687, !648}
!687 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !637, size: 64)
!688 = !DISubprogram(name: "set", linkageName: "_ZN4llvm9BitVector3setEj", scope: !637, file: !636, line: 242, type: !689, scopeLine: 242, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!689 = !DISubroutineType(types: !690)
!690 = !{!687, !648, !6}
!691 = !DISubprogram(name: "set", linkageName: "_ZN4llvm9BitVector3setEjj", scope: !637, file: !636, line: 248, type: !692, scopeLine: 248, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!692 = !DISubroutineType(types: !693)
!693 = !{!687, !648, !6, !6}
!694 = !DISubprogram(name: "reset", linkageName: "_ZN4llvm9BitVector5resetEv", scope: !637, file: !636, line: 275, type: !685, scopeLine: 275, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!695 = !DISubprogram(name: "reset", linkageName: "_ZN4llvm9BitVector5resetEj", scope: !637, file: !636, line: 280, type: !689, scopeLine: 280, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!696 = !DISubprogram(name: "reset", linkageName: "_ZN4llvm9BitVector5resetEjj", scope: !637, file: !636, line: 286, type: !692, scopeLine: 286, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!697 = !DISubprogram(name: "flip", linkageName: "_ZN4llvm9BitVector4flipEv", scope: !637, file: !636, line: 313, type: !685, scopeLine: 313, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!698 = !DISubprogram(name: "flip", linkageName: "_ZN4llvm9BitVector4flipEj", scope: !637, file: !636, line: 320, type: !689, scopeLine: 320, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!699 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm9BitVectorixEj", scope: !637, file: !636, line: 326, type: !700, scopeLine: 326, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!700 = !DISubroutineType(types: !701)
!701 = !{!702, !648, !6}
!702 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reference", scope: !637, file: !636, line: 38, size: 128, flags: DIFlagPublic | DIFlagTypePassByReference | DIFlagNonTrivial, elements: !703, identifier: "_ZTSN4llvm9BitVector9referenceE")
!703 = !{!704, !705, !706, !710, !713, !714, !718, !721}
!704 = !DIDerivedType(tag: DW_TAG_member, name: "WordRef", scope: !702, file: !636, line: 41, baseType: !640, size: 64)
!705 = !DIDerivedType(tag: DW_TAG_member, name: "BitPos", scope: !702, file: !636, line: 42, baseType: !6, size: 32, offset: 64)
!706 = !DISubprogram(name: "reference", scope: !702, file: !636, line: 44, type: !707, scopeLine: 44, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!707 = !DISubroutineType(types: !708)
!708 = !{null, !709}
!709 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !702, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!710 = !DISubprogram(name: "reference", scope: !702, file: !636, line: 47, type: !711, scopeLine: 47, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!711 = !DISubroutineType(types: !712)
!712 = !{null, !709, !687, !6}
!713 = !DISubprogram(name: "~reference", scope: !702, file: !636, line: 52, type: !707, scopeLine: 52, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!714 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm9BitVector9referenceaSES1_", scope: !702, file: !636, line: 54, type: !715, scopeLine: 54, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!715 = !DISubroutineType(types: !716)
!716 = !{!717, !709, !702}
!717 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !702, size: 64)
!718 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm9BitVector9referenceaSEb", scope: !702, file: !636, line: 59, type: !719, scopeLine: 59, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!719 = !DISubroutineType(types: !720)
!720 = !{!717, !709, !145}
!721 = !DISubprogram(name: "operator bool", linkageName: "_ZNK4llvm9BitVector9referencecvbEv", scope: !702, file: !636, line: 67, type: !722, scopeLine: 67, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!722 = !DISubroutineType(types: !723)
!723 = !{!145, !724}
!724 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !725, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!725 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !702)
!726 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm9BitVectorixEj", scope: !637, file: !636, line: 331, type: !727, scopeLine: 331, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!727 = !DISubroutineType(types: !728)
!728 = !{!145, !665, !6}
!729 = !DISubprogram(name: "test", linkageName: "_ZNK4llvm9BitVector4testEj", scope: !637, file: !636, line: 337, type: !727, scopeLine: 337, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!730 = !DISubprogram(name: "anyCommon", linkageName: "_ZNK4llvm9BitVector9anyCommonERKS0_", scope: !637, file: !636, line: 342, type: !731, scopeLine: 342, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!731 = !DISubroutineType(types: !732)
!732 = !{!145, !665, !655}
!733 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm9BitVectoreqERKS0_", scope: !637, file: !636, line: 352, type: !731, scopeLine: 352, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!734 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm9BitVectorneERKS0_", scope: !637, file: !636, line: 373, type: !731, scopeLine: 373, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!735 = !DISubprogram(name: "operator&=", linkageName: "_ZN4llvm9BitVectoraNERKS0_", scope: !637, file: !636, line: 378, type: !736, scopeLine: 378, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!736 = !DISubroutineType(types: !737)
!737 = !{!687, !648, !655}
!738 = !DISubprogram(name: "reset", linkageName: "_ZN4llvm9BitVector5resetERKS0_", scope: !637, file: !636, line: 395, type: !736, scopeLine: 395, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!739 = !DISubprogram(name: "test", linkageName: "_ZNK4llvm9BitVector4testERKS0_", scope: !637, file: !636, line: 406, type: !731, scopeLine: 406, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!740 = !DISubprogram(name: "operator|=", linkageName: "_ZN4llvm9BitVectoroRERKS0_", scope: !637, file: !636, line: 421, type: !736, scopeLine: 421, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!741 = !DISubprogram(name: "operator^=", linkageName: "_ZN4llvm9BitVectoreOERKS0_", scope: !637, file: !636, line: 429, type: !736, scopeLine: 429, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!742 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm9BitVectoraSERKS0_", scope: !637, file: !636, line: 438, type: !743, scopeLine: 438, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!743 = !DISubroutineType(types: !744)
!744 = !{!655, !648, !655}
!745 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm9BitVectoraSEOS0_", scope: !637, file: !636, line: 463, type: !746, scopeLine: 463, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!746 = !DISubroutineType(types: !747)
!747 = !{!655, !648, !660}
!748 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm9BitVector4swapERS0_", scope: !637, file: !636, line: 477, type: !749, scopeLine: 477, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!749 = !DISubroutineType(types: !750)
!750 = !{null, !648, !687}
!751 = !DISubprogram(name: "setBitsInMask", linkageName: "_ZN4llvm9BitVector13setBitsInMaskEPKjj", scope: !637, file: !636, line: 497, type: !752, scopeLine: 497, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!752 = !DISubroutineType(types: !753)
!753 = !{null, !648, !290, !6}
!754 = !DISubprogram(name: "clearBitsInMask", linkageName: "_ZN4llvm9BitVector15clearBitsInMaskEPKjj", scope: !637, file: !636, line: 503, type: !752, scopeLine: 503, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!755 = !DISubprogram(name: "setBitsNotInMask", linkageName: "_ZN4llvm9BitVector16setBitsNotInMaskEPKjj", scope: !637, file: !636, line: 509, type: !752, scopeLine: 509, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!756 = !DISubprogram(name: "clearBitsNotInMask", linkageName: "_ZN4llvm9BitVector18clearBitsNotInMaskEPKjj", scope: !637, file: !636, line: 515, type: !752, scopeLine: 515, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!757 = !DISubprogram(name: "NumBitWords", linkageName: "_ZNK4llvm9BitVector11NumBitWordsEj", scope: !637, file: !636, line: 520, type: !758, scopeLine: 520, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!758 = !DISubroutineType(types: !759)
!759 = !{!6, !665, !6}
!760 = !DISubprogram(name: "set_unused_bits", linkageName: "_ZN4llvm9BitVector15set_unused_bitsEb", scope: !637, file: !636, line: 525, type: !761, scopeLine: 525, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!761 = !DISubroutineType(types: !762)
!762 = !{null, !648, !145}
!763 = !DISubprogram(name: "clear_unused_bits", linkageName: "_ZN4llvm9BitVector17clear_unused_bitsEv", scope: !637, file: !636, line: 543, type: !646, scopeLine: 543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!764 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm9BitVector4growEj", scope: !637, file: !636, line: 547, type: !682, scopeLine: 547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!765 = !DISubprogram(name: "init_words", linkageName: "_ZN4llvm9BitVector10init_wordsEPmjb", scope: !637, file: !636, line: 554, type: !766, scopeLine: 554, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!766 = !DISubroutineType(types: !767)
!767 = !{null, !648, !640, !6, !145}
!768 = !{!769}
!769 = !DIEnumerator(name: "BITWORD_SIZE", value: 64, isUnsigned: true)
!770 = !DICompositeType(tag: DW_TAG_enumeration_type, scope: !772, file: !771, line: 30, baseType: !6, size: 32, elements: !773)
!771 = !DIFile(filename: "llvm34/include/llvm/CodeGen/MachineInstrBuilder.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e96d37a37ff7b5bff2251569b5f9ba94")
!772 = !DINamespace(name: "RegState", scope: !14)
!773 = !{!774, !775, !776, !777, !778, !779, !780, !781, !782, !783, !784}
!774 = !DIEnumerator(name: "Define", value: 2, isUnsigned: true)
!775 = !DIEnumerator(name: "Implicit", value: 4, isUnsigned: true)
!776 = !DIEnumerator(name: "Kill", value: 8, isUnsigned: true)
!777 = !DIEnumerator(name: "Dead", value: 16, isUnsigned: true)
!778 = !DIEnumerator(name: "Undef", value: 32, isUnsigned: true)
!779 = !DIEnumerator(name: "EarlyClobber", value: 64, isUnsigned: true)
!780 = !DIEnumerator(name: "Debug", value: 128, isUnsigned: true)
!781 = !DIEnumerator(name: "InternalRead", value: 256, isUnsigned: true)
!782 = !DIEnumerator(name: "DefineNoRead", value: 34, isUnsigned: true)
!783 = !DIEnumerator(name: "ImplicitDefine", value: 6, isUnsigned: true)
!784 = !DIEnumerator(name: "ImplicitKill", value: 12, isUnsigned: true)
!785 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "ZeroBehavior", scope: !14, file: !786, line: 30, baseType: !6, size: 32, elements: !787, identifier: "_ZTSN4llvm12ZeroBehaviorE")
!786 = !DIFile(filename: "llvm34/include/llvm/Support/MathExtras.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "dc2c2488e5b34ad60e03a667451851b1")
!787 = !{!788, !789, !790}
!788 = !DIEnumerator(name: "ZB_Undefined", value: 0, isUnsigned: true)
!789 = !DIEnumerator(name: "ZB_Max", value: 1, isUnsigned: true)
!790 = !DIEnumerator(name: "ZB_Width", value: 2, isUnsigned: true)
!791 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "ValueExpected", scope: !13, file: !12, line: 100, baseType: !6, size: 32, elements: !792, identifier: "_ZTSN4llvm2cl13ValueExpectedE")
!792 = !{!793, !794, !795}
!793 = !DIEnumerator(name: "ValueOptional", value: 1, isUnsigned: true)
!794 = !DIEnumerator(name: "ValueRequired", value: 2, isUnsigned: true)
!795 = !DIEnumerator(name: "ValueDisallowed", value: 3, isUnsigned: true)
!796 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "NumOccurrencesFlag", scope: !13, file: !12, line: 84, baseType: !6, size: 32, elements: !797, identifier: "_ZTSN4llvm2cl18NumOccurrencesFlagE")
!797 = !{!798, !799, !800, !801, !802}
!798 = !DIEnumerator(name: "Optional", value: 0, isUnsigned: true)
!799 = !DIEnumerator(name: "ZeroOrMore", value: 1, isUnsigned: true)
!800 = !DIEnumerator(name: "Required", value: 2, isUnsigned: true)
!801 = !DIEnumerator(name: "OneOrMore", value: 3, isUnsigned: true)
!802 = !DIEnumerator(name: "ConsumeAfter", value: 4, isUnsigned: true)
!803 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "FormattingFlags", scope: !13, file: !12, line: 128, baseType: !6, size: 32, elements: !804, identifier: "_ZTSN4llvm2cl15FormattingFlagsE")
!804 = !{!805, !806, !807, !808}
!805 = !DIEnumerator(name: "NormalFormatting", value: 0, isUnsigned: true)
!806 = !DIEnumerator(name: "Positional", value: 1, isUnsigned: true)
!807 = !DIEnumerator(name: "Prefix", value: 2, isUnsigned: true)
!808 = !DIEnumerator(name: "Grouping", value: 3, isUnsigned: true)
!809 = !{!810, !824, !1360, !1361, !145, !2313, !2314, !154, !2315, !2316, !124, !2443, !3090, !3093, !3280, !3338, !3432, !268, !288, !3434, !197, !6, !1044, !3495, !3549, !3644, !3647, !3987, !3988, !3989, !4049, !3888, !4050, !3379, !3285, !4134, !640, !32, !905, !4190, !4244, !2383, !4298, !4348, !4349, !4729, !4730, !4731, !4632, !4732, !4823, !1703, !1430, !4824, !4873, !2214, !1761, !4772, !4874, !4964, !3282, !2390, !4975, !4910, !5027, !5038, !5048, !5057, !5062, !5709, !1345, !5069, !5122, !5125, !5128, !2318, !2321, !1390, !1386, !1364, !2125, !2122, !1367, !1434, !1431, !2465, !2836, !2481, !2500, !2599, !2602, !2605, !2444, !637, !3214, !3211, !5491, !5495, !5499, !117, !120, !5510, !4051, !4054, !3339, !3436, !3496, !5710, !5713, !5716, !3550, !5828, !5617, !5620, !4875, !4136, !5339, !5432, !5429, !3672, !3669, !3649, !3801, !3798, !3652, !3990, !5859, !3658, !5905, !5923, !5384, !702, !4245, !4374, !4371, !4351, !4546, !4543, !4354, !5958, !5255, !5258, !4733, !4360, !1373, !2005, !1704, !1409, !1762, !1412, !1415, !1495, !1499, !4450, !5989, !6081, !248, !6132, !6163, !6182, !4976, !826, !837, !1092, !842, !845, !867, !873, !6218, !823, !6222, !6226, !6229, !6232, !6235, !6294, !6331, !6334, !6335, !6339, !6343, !6346, !6349, !6407, !6441}
!810 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "desc", scope: !13, file: !12, line: 286, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !811, identifier: "_ZTSN4llvm2cl4descE")
!811 = !{!812, !813, !817}
!812 = !DIDerivedType(tag: DW_TAG_member, name: "Desc", scope: !810, file: !12, line: 287, baseType: !317, size: 64)
!813 = !DISubprogram(name: "desc", scope: !810, file: !12, line: 288, type: !814, scopeLine: 288, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!814 = !DISubroutineType(types: !815)
!815 = !{null, !816, !317}
!816 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !810, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!817 = !DISubprogram(name: "apply", linkageName: "_ZNK4llvm2cl4desc5applyERNS0_6OptionE", scope: !810, file: !12, line: 289, type: !818, scopeLine: 289, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!818 = !DISubroutineType(types: !819)
!819 = !{null, !820, !822}
!820 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !821, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!821 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !810)
!822 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !823, size: 64)
!823 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Option", scope: !13, file: !12, line: 163, size: 512, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm2cl6OptionE")
!824 = !DIDerivedType(tag: DW_TAG_typedef, name: "NormalCtor_t", scope: !826, file: !825, line: 41, baseType: !1357)
!825 = !DIFile(filename: "llvm34/include/llvm/PassSupport.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "3b8dc647f268ebac7a0cd4e4e69b5005")
!826 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PassInfo", scope: !14, file: !825, line: 39, size: 512, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !827, identifier: "_ZTSN4llvm8PassInfoE")
!827 = !{!828, !830, !831, !832, !834, !835, !836, !1311, !1312, !1316, !1319, !1323, !1324, !1327, !1330, !1333, !1334, !1335, !1338, !1341, !1346, !1349, !1352, !1356}
!828 = !DIDerivedType(tag: DW_TAG_member, name: "PassName", scope: !826, file: !825, line: 44, baseType: !829, size: 64)
!829 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !317)
!830 = !DIDerivedType(tag: DW_TAG_member, name: "PassArgument", scope: !826, file: !825, line: 45, baseType: !829, size: 64, offset: 64)
!831 = !DIDerivedType(tag: DW_TAG_member, name: "PassID", scope: !826, file: !825, line: 46, baseType: !124, size: 64, offset: 128)
!832 = !DIDerivedType(tag: DW_TAG_member, name: "IsCFGOnlyPass", scope: !826, file: !825, line: 47, baseType: !833, size: 8, offset: 192)
!833 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !145)
!834 = !DIDerivedType(tag: DW_TAG_member, name: "IsAnalysis", scope: !826, file: !825, line: 48, baseType: !833, size: 8, offset: 200)
!835 = !DIDerivedType(tag: DW_TAG_member, name: "IsAnalysisGroup", scope: !826, file: !825, line: 49, baseType: !833, size: 8, offset: 208)
!836 = !DIDerivedType(tag: DW_TAG_member, name: "ItfImpl", scope: !826, file: !825, line: 50, baseType: !837, size: 192, offset: 256)
!837 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<const llvm::PassInfo *, std::allocator<const llvm::PassInfo *> >", scope: !839, file: !838, line: 339, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !840, templateParams: !1030, identifier: "_ZTSSt6vectorIPKN4llvm8PassInfoESaIS3_EE")
!838 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h", directory: "", checksumkind: CSK_MD5, checksum: "ba305a1e10d49c66b3a70acbb63616a6")
!839 = !DINamespace(name: "std", scope: null)
!840 = !{!841, !1031, !1035, !1041, !1045, !1051, !1056, !1060, !1063, !1066, !1071, !1072, !1076, !1079, !1082, !1085, !1088, !1149, !1155, !1156, !1157, !1162, !1167, !1168, !1169, !1170, !1171, !1172, !1173, !1176, !1177, !1180, !1181, !1182, !1183, !1186, !1187, !1195, !1202, !1205, !1206, !1207, !1210, !1213, !1214, !1215, !1218, !1221, !1224, !1228, !1229, !1232, !1235, !1238, !1241, !1244, !1247, !1250, !1251, !1252, !1253, !1254, !1257, !1258, !1261, !1262, !1263, !1267, !1271, !1274, !1277, !1295}
!841 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !837, baseType: !842, flags: DIFlagProtected, extraData: i32 0)
!842 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_base<const llvm::PassInfo *, std::allocator<const llvm::PassInfo *> >", scope: !839, file: !838, line: 81, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !843, templateParams: !1030, identifier: "_ZTSSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE")
!843 = !{!844, !984, !989, !994, !998, !1001, !1006, !1009, !1012, !1015, !1019, !1022, !1023, !1026, !1029}
!844 = !DIDerivedType(tag: DW_TAG_member, name: "_M_impl", scope: !842, file: !838, line: 290, baseType: !845, size: 192)
!845 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_impl", scope: !842, file: !838, line: 88, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !846, identifier: "_ZTSNSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE12_Vector_implE")
!846 = !{!847, !962, !965, !966, !967, !971, !976, !980}
!847 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !845, baseType: !848, extraData: i32 0)
!848 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Tp_alloc_type", scope: !842, file: !838, line: 84, baseType: !849)
!849 = !DIDerivedType(tag: DW_TAG_typedef, name: "other", scope: !851, file: !850, line: 117, baseType: !961)
!850 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/alloc_traits.h", directory: "")
!851 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "rebind<const llvm::PassInfo *>", scope: !852, file: !850, line: 116, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !913, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E6rebindIS4_EE")
!852 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__alloc_traits<std::allocator<const llvm::PassInfo *>, const llvm::PassInfo *>", scope: !5, file: !850, line: 50, size: 8, flags: DIFlagTypePassByValue, elements: !853, templateParams: !958, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_EE")
!853 = !{!854, !944, !947, !951, !954, !955, !956, !957}
!854 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !852, baseType: !855, extraData: i32 0)
!855 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "allocator_traits<std::allocator<const llvm::PassInfo *> >", scope: !839, file: !856, line: 384, size: 8, flags: DIFlagTypePassByValue, elements: !857, templateParams: !942, identifier: "_ZTSSt16allocator_traitsISaIPKN4llvm8PassInfoEEE")
!856 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/alloc_traits.h", directory: "", checksumkind: CSK_MD5, checksum: "f7f651aab55acaadfc53aa53979a817c")
!857 = !{!858, !926, !930, !933, !939}
!858 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIPKN4llvm8PassInfoEEE8allocateERS4_m", scope: !855, file: !856, line: 435, type: !859, scopeLine: 435, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!859 = !DISubroutineType(types: !860)
!860 = !{!861, !865, !925}
!861 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !855, file: !856, line: 392, baseType: !862)
!862 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !863, size: 64)
!863 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !864, size: 64)
!864 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !826)
!865 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !866, size: 64)
!866 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !855, file: !856, line: 387, baseType: !867)
!867 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "allocator<const llvm::PassInfo *>", scope: !839, file: !868, line: 108, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !869, templateParams: !913, identifier: "_ZTSSaIPKN4llvm8PassInfoEE")
!868 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "9cafc7b584300736771313d46be845c3")
!869 = !{!870, !915, !919, !924}
!870 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !867, baseType: !871, flags: DIFlagPublic, extraData: i32 0)
!871 = !DIDerivedType(tag: DW_TAG_typedef, name: "__allocator_base<const llvm::PassInfo *>", scope: !839, file: !872, line: 48, baseType: !873)
!872 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8/bits/c++allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "9572fa47638d84b83d0311676a9766b8")
!873 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "new_allocator<const llvm::PassInfo *>", scope: !5, file: !874, line: 58, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !875, templateParams: !913, identifier: "_ZTSN9__gnu_cxx13new_allocatorIPKN4llvm8PassInfoEEE")
!874 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/new_allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "ece13daf300dfc0cac27dc2ea29129ca")
!875 = !{!876, !880, !885, !886, !893, !901, !907, !910}
!876 = !DISubprogram(name: "new_allocator", scope: !873, file: !874, line: 79, type: !877, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!877 = !DISubroutineType(types: !878)
!878 = !{null, !879}
!879 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !873, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!880 = !DISubprogram(name: "new_allocator", scope: !873, file: !874, line: 81, type: !881, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!881 = !DISubroutineType(types: !882)
!882 = !{null, !879, !883}
!883 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !884, size: 64)
!884 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !873)
!885 = !DISubprogram(name: "~new_allocator", scope: !873, file: !874, line: 86, type: !877, scopeLine: 86, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!886 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorIPKN4llvm8PassInfoEE7addressERS4_", scope: !873, file: !874, line: 89, type: !887, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!887 = !DISubroutineType(types: !888)
!888 = !{!889, !890, !891}
!889 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !873, file: !874, line: 63, baseType: !862)
!890 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !884, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!891 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !873, file: !874, line: 65, baseType: !892)
!892 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !863, size: 64)
!893 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorIPKN4llvm8PassInfoEE7addressERKS4_", scope: !873, file: !874, line: 93, type: !894, scopeLine: 93, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!894 = !DISubroutineType(types: !895)
!895 = !{!896, !890, !899}
!896 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !873, file: !874, line: 64, baseType: !897)
!897 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !898, size: 64)
!898 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !863)
!899 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !873, file: !874, line: 66, baseType: !900)
!900 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !898, size: 64)
!901 = !DISubprogram(name: "allocate", linkageName: "_ZN9__gnu_cxx13new_allocatorIPKN4llvm8PassInfoEE8allocateEmPKv", scope: !873, file: !874, line: 99, type: !902, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!902 = !DISubroutineType(types: !903)
!903 = !{!889, !879, !904, !124}
!904 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !874, line: 61, baseType: !905)
!905 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", scope: !839, file: !906, line: 238, baseType: !642)
!906 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8/bits/c++config.h", directory: "", checksumkind: CSK_MD5, checksum: "5ab2830680f5a52514c973f039a03c0a")
!907 = !DISubprogram(name: "deallocate", linkageName: "_ZN9__gnu_cxx13new_allocatorIPKN4llvm8PassInfoEE10deallocateEPS4_m", scope: !873, file: !874, line: 116, type: !908, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!908 = !DISubroutineType(types: !909)
!909 = !{null, !879, !889, !904}
!910 = !DISubprogram(name: "max_size", linkageName: "_ZNK9__gnu_cxx13new_allocatorIPKN4llvm8PassInfoEE8max_sizeEv", scope: !873, file: !874, line: 129, type: !911, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!911 = !DISubroutineType(types: !912)
!912 = !{!904, !890}
!913 = !{!914}
!914 = !DITemplateTypeParameter(name: "_Tp", type: !863)
!915 = !DISubprogram(name: "allocator", scope: !867, file: !868, line: 131, type: !916, scopeLine: 131, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!916 = !DISubroutineType(types: !917)
!917 = !{null, !918}
!918 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !867, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!919 = !DISubprogram(name: "allocator", scope: !867, file: !868, line: 133, type: !920, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!920 = !DISubroutineType(types: !921)
!921 = !{null, !918, !922}
!922 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !923, size: 64)
!923 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !867)
!924 = !DISubprogram(name: "~allocator", scope: !867, file: !868, line: 139, type: !916, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!925 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !856, line: 407, baseType: !905)
!926 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIPKN4llvm8PassInfoEEE8allocateERS4_mPKv", scope: !855, file: !856, line: 449, type: !927, scopeLine: 449, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!927 = !DISubroutineType(types: !928)
!928 = !{!861, !865, !925, !929}
!929 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_void_pointer", file: !856, line: 401, baseType: !124)
!930 = !DISubprogram(name: "deallocate", linkageName: "_ZNSt16allocator_traitsISaIPKN4llvm8PassInfoEEE10deallocateERS4_PS3_m", scope: !855, file: !856, line: 461, type: !931, scopeLine: 461, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!931 = !DISubroutineType(types: !932)
!932 = !{null, !865, !861, !925}
!933 = !DISubprogram(name: "max_size", linkageName: "_ZNSt16allocator_traitsISaIPKN4llvm8PassInfoEEE8max_sizeERKS4_", scope: !855, file: !856, line: 495, type: !934, scopeLine: 495, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!934 = !DISubroutineType(types: !935)
!935 = !{!936, !937}
!936 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !855, file: !856, line: 407, baseType: !905)
!937 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !938, size: 64)
!938 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !866)
!939 = !DISubprogram(name: "select_on_container_copy_construction", linkageName: "_ZNSt16allocator_traitsISaIPKN4llvm8PassInfoEEE37select_on_container_copy_constructionERKS4_", scope: !855, file: !856, line: 504, type: !940, scopeLine: 504, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!940 = !DISubroutineType(types: !941)
!941 = !{!866, !937}
!942 = !{!943}
!943 = !DITemplateTypeParameter(name: "_Alloc", type: !867)
!944 = !DISubprogram(name: "_S_select_on_copy", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E17_S_select_on_copyERKS5_", scope: !852, file: !850, line: 94, type: !945, scopeLine: 94, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!945 = !DISubroutineType(types: !946)
!946 = !{!867, !922}
!947 = !DISubprogram(name: "_S_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E10_S_on_swapERS5_S7_", scope: !852, file: !850, line: 97, type: !948, scopeLine: 97, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!948 = !DISubroutineType(types: !949)
!949 = !{null, !950, !950}
!950 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !867, size: 64)
!951 = !DISubprogram(name: "_S_propagate_on_copy_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E27_S_propagate_on_copy_assignEv", scope: !852, file: !850, line: 100, type: !952, scopeLine: 100, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!952 = !DISubroutineType(types: !953)
!953 = !{!145}
!954 = !DISubprogram(name: "_S_propagate_on_move_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E27_S_propagate_on_move_assignEv", scope: !852, file: !850, line: 103, type: !952, scopeLine: 103, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!955 = !DISubprogram(name: "_S_propagate_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E20_S_propagate_on_swapEv", scope: !852, file: !850, line: 106, type: !952, scopeLine: 106, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!956 = !DISubprogram(name: "_S_always_equal", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E15_S_always_equalEv", scope: !852, file: !850, line: 109, type: !952, scopeLine: 109, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!957 = !DISubprogram(name: "_S_nothrow_move", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E15_S_nothrow_moveEv", scope: !852, file: !850, line: 112, type: !952, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!958 = !{!943, !959}
!959 = !DITemplateTypeParameter(type: !863)
!960 = !{}
!961 = !DIDerivedType(tag: DW_TAG_typedef, name: "rebind_alloc<const llvm::PassInfo *>", scope: !855, file: !856, line: 422, baseType: !867)
!962 = !DIDerivedType(tag: DW_TAG_member, name: "_M_start", scope: !845, file: !838, line: 91, baseType: !963, size: 64)
!963 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !842, file: !838, line: 86, baseType: !964)
!964 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !852, file: !850, line: 59, baseType: !861)
!965 = !DIDerivedType(tag: DW_TAG_member, name: "_M_finish", scope: !845, file: !838, line: 92, baseType: !963, size: 64, offset: 64)
!966 = !DIDerivedType(tag: DW_TAG_member, name: "_M_end_of_storage", scope: !845, file: !838, line: 93, baseType: !963, size: 64, offset: 128)
!967 = !DISubprogram(name: "_Vector_impl", scope: !845, file: !838, line: 95, type: !968, scopeLine: 95, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!968 = !DISubroutineType(types: !969)
!969 = !{null, !970}
!970 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !845, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!971 = !DISubprogram(name: "_Vector_impl", scope: !845, file: !838, line: 99, type: !972, scopeLine: 99, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!972 = !DISubroutineType(types: !973)
!973 = !{null, !970, !974}
!974 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !975, size: 64)
!975 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !848)
!976 = !DISubprogram(name: "_Vector_impl", scope: !845, file: !838, line: 104, type: !977, scopeLine: 104, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!977 = !DISubroutineType(types: !978)
!978 = !{null, !970, !979}
!979 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !848, size: 64)
!980 = !DISubprogram(name: "_M_swap_data", linkageName: "_ZNSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE12_Vector_impl12_M_swap_dataERS6_", scope: !845, file: !838, line: 110, type: !981, scopeLine: 110, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!981 = !DISubroutineType(types: !982)
!982 = !{null, !970, !983}
!983 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !845, size: 64)
!984 = !DISubprogram(name: "_M_get_Tp_allocator", linkageName: "_ZNSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE19_M_get_Tp_allocatorEv", scope: !842, file: !838, line: 237, type: !985, scopeLine: 237, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!985 = !DISubroutineType(types: !986)
!986 = !{!987, !988}
!987 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !848, size: 64)
!988 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !842, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!989 = !DISubprogram(name: "_M_get_Tp_allocator", linkageName: "_ZNKSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE19_M_get_Tp_allocatorEv", scope: !842, file: !838, line: 241, type: !990, scopeLine: 241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!990 = !DISubroutineType(types: !991)
!991 = !{!974, !992}
!992 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !993, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!993 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !842)
!994 = !DISubprogram(name: "get_allocator", linkageName: "_ZNKSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE13get_allocatorEv", scope: !842, file: !838, line: 245, type: !995, scopeLine: 245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!995 = !DISubroutineType(types: !996)
!996 = !{!997, !992}
!997 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !842, file: !838, line: 234, baseType: !867)
!998 = !DISubprogram(name: "_Vector_base", scope: !842, file: !838, line: 248, type: !999, scopeLine: 248, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!999 = !DISubroutineType(types: !1000)
!1000 = !{null, !988}
!1001 = !DISubprogram(name: "_Vector_base", scope: !842, file: !838, line: 251, type: !1002, scopeLine: 251, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1002 = !DISubroutineType(types: !1003)
!1003 = !{null, !988, !1004}
!1004 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1005, size: 64)
!1005 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !997)
!1006 = !DISubprogram(name: "_Vector_base", scope: !842, file: !838, line: 254, type: !1007, scopeLine: 254, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1007 = !DISubroutineType(types: !1008)
!1008 = !{null, !988, !905}
!1009 = !DISubprogram(name: "_Vector_base", scope: !842, file: !838, line: 258, type: !1010, scopeLine: 258, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1010 = !DISubroutineType(types: !1011)
!1011 = !{null, !988, !905, !1004}
!1012 = !DISubprogram(name: "_Vector_base", scope: !842, file: !838, line: 263, type: !1013, scopeLine: 263, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1013 = !DISubroutineType(types: !1014)
!1014 = !{null, !988, !979}
!1015 = !DISubprogram(name: "_Vector_base", scope: !842, file: !838, line: 266, type: !1016, scopeLine: 266, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1016 = !DISubroutineType(types: !1017)
!1017 = !{null, !988, !1018}
!1018 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !842, size: 64)
!1019 = !DISubprogram(name: "_Vector_base", scope: !842, file: !838, line: 270, type: !1020, scopeLine: 270, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1020 = !DISubroutineType(types: !1021)
!1021 = !{null, !988, !1018, !1004}
!1022 = !DISubprogram(name: "~_Vector_base", scope: !842, file: !838, line: 283, type: !999, scopeLine: 283, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1023 = !DISubprogram(name: "_M_allocate", linkageName: "_ZNSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE11_M_allocateEm", scope: !842, file: !838, line: 293, type: !1024, scopeLine: 293, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1024 = !DISubroutineType(types: !1025)
!1025 = !{!963, !988, !905}
!1026 = !DISubprogram(name: "_M_deallocate", linkageName: "_ZNSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE13_M_deallocateEPS3_m", scope: !842, file: !838, line: 300, type: !1027, scopeLine: 300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1027 = !DISubroutineType(types: !1028)
!1028 = !{null, !988, !963, !905}
!1029 = !DISubprogram(name: "_M_create_storage", linkageName: "_ZNSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE17_M_create_storageEm", scope: !842, file: !838, line: 309, type: !1007, scopeLine: 309, flags: DIFlagPrivate | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1030 = !{!914, !943}
!1031 = !DISubprogram(name: "vector", scope: !837, file: !838, line: 391, type: !1032, scopeLine: 391, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1032 = !DISubroutineType(types: !1033)
!1033 = !{null, !1034}
!1034 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !837, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1035 = !DISubprogram(name: "vector", scope: !837, file: !838, line: 402, type: !1036, scopeLine: 402, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1036 = !DISubroutineType(types: !1037)
!1037 = !{null, !1034, !1038}
!1038 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1039, size: 64)
!1039 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1040)
!1040 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !837, file: !838, line: 376, baseType: !867)
!1041 = !DISubprogram(name: "vector", scope: !837, file: !838, line: 415, type: !1042, scopeLine: 415, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1042 = !DISubroutineType(types: !1043)
!1043 = !{null, !1034, !1044, !1038}
!1044 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !838, line: 374, baseType: !905)
!1045 = !DISubprogram(name: "vector", scope: !837, file: !838, line: 427, type: !1046, scopeLine: 427, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1046 = !DISubroutineType(types: !1047)
!1047 = !{null, !1034, !1044, !1048, !1038}
!1048 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1049, size: 64)
!1049 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1050)
!1050 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !837, file: !838, line: 364, baseType: !863)
!1051 = !DISubprogram(name: "vector", scope: !837, file: !838, line: 458, type: !1052, scopeLine: 458, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1052 = !DISubroutineType(types: !1053)
!1053 = !{null, !1034, !1054}
!1054 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1055, size: 64)
!1055 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !837)
!1056 = !DISubprogram(name: "vector", scope: !837, file: !838, line: 476, type: !1057, scopeLine: 476, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1057 = !DISubroutineType(types: !1058)
!1058 = !{null, !1034, !1059}
!1059 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !837, size: 64)
!1060 = !DISubprogram(name: "vector", scope: !837, file: !838, line: 480, type: !1061, scopeLine: 480, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1061 = !DISubroutineType(types: !1062)
!1062 = !{null, !1034, !1054, !1038}
!1063 = !DISubprogram(name: "vector", scope: !837, file: !838, line: 490, type: !1064, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1064 = !DISubroutineType(types: !1065)
!1065 = !{null, !1034, !1059, !1038}
!1066 = !DISubprogram(name: "vector", scope: !837, file: !838, line: 515, type: !1067, scopeLine: 515, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1067 = !DISubroutineType(types: !1068)
!1068 = !{null, !1034, !1069, !1038}
!1069 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<const llvm::PassInfo *>", scope: !839, file: !1070, line: 47, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listIPKN4llvm8PassInfoEE")
!1070 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/initializer_list", directory: "")
!1071 = !DISubprogram(name: "~vector", scope: !837, file: !838, line: 565, type: !1032, scopeLine: 565, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1072 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EEaSERKS5_", scope: !837, file: !838, line: 582, type: !1073, scopeLine: 582, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1073 = !DISubroutineType(types: !1074)
!1074 = !{!1075, !1034, !1054}
!1075 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !837, size: 64)
!1076 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EEaSEOS5_", scope: !837, file: !838, line: 596, type: !1077, scopeLine: 596, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1077 = !DISubroutineType(types: !1078)
!1078 = !{!1075, !1034, !1059}
!1079 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EEaSESt16initializer_listIS3_E", scope: !837, file: !838, line: 617, type: !1080, scopeLine: 617, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1080 = !DISubroutineType(types: !1081)
!1081 = !{!1075, !1034, !1069}
!1082 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6assignEmRKS3_", scope: !837, file: !838, line: 636, type: !1083, scopeLine: 636, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1083 = !DISubroutineType(types: !1084)
!1084 = !{null, !1034, !1044, !1048}
!1085 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6assignESt16initializer_listIS3_E", scope: !837, file: !838, line: 681, type: !1086, scopeLine: 681, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1086 = !DISubroutineType(types: !1087)
!1087 = !{null, !1034, !1069}
!1088 = !DISubprogram(name: "begin", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE5beginEv", scope: !837, file: !838, line: 698, type: !1089, scopeLine: 698, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1089 = !DISubroutineType(types: !1090)
!1090 = !{!1091, !1034}
!1091 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !837, file: !838, line: 369, baseType: !1092)
!1092 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<const llvm::PassInfo **, std::vector<const llvm::PassInfo *, std::allocator<const llvm::PassInfo *> > >", scope: !5, file: !1093, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1094, templateParams: !1147, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEE")
!1093 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_iterator.h", directory: "", checksumkind: CSK_MD5, checksum: "43ca426be47f2e0c5f7f184d7d27a436")
!1094 = !{!1095, !1096, !1100, !1105, !1116, !1121, !1125, !1128, !1129, !1130, !1136, !1139, !1142, !1143, !1144}
!1095 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !1092, file: !1093, line: 767, baseType: !862, size: 64, flags: DIFlagProtected)
!1096 = !DISubprogram(name: "__normal_iterator", scope: !1092, file: !1093, line: 779, type: !1097, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1097 = !DISubroutineType(types: !1098)
!1098 = !{null, !1099}
!1099 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1092, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1100 = !DISubprogram(name: "__normal_iterator", scope: !1092, file: !1093, line: 783, type: !1101, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1101 = !DISubroutineType(types: !1102)
!1102 = !{null, !1099, !1103}
!1103 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1104, size: 64)
!1104 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !862)
!1105 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEdeEv", scope: !1092, file: !1093, line: 796, type: !1106, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1106 = !DISubroutineType(types: !1107)
!1107 = !{!1108, !1114}
!1108 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1092, file: !1093, line: 776, baseType: !1109)
!1109 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1111, file: !1110, line: 184, baseType: !892)
!1110 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_iterator_base_types.h", directory: "")
!1111 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<const llvm::PassInfo **>", scope: !839, file: !1110, line: 178, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !1112, identifier: "_ZTSSt15iterator_traitsIPPKN4llvm8PassInfoEE")
!1112 = !{!1113}
!1113 = !DITemplateTypeParameter(name: "_Iterator", type: !862)
!1114 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1115, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1115 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1092)
!1116 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEptEv", scope: !1092, file: !1093, line: 800, type: !1117, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1117 = !DISubroutineType(types: !1118)
!1118 = !{!1119, !1114}
!1119 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1092, file: !1093, line: 777, baseType: !1120)
!1120 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1111, file: !1110, line: 183, baseType: !862)
!1121 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEppEv", scope: !1092, file: !1093, line: 804, type: !1122, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1122 = !DISubroutineType(types: !1123)
!1123 = !{!1124, !1099}
!1124 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1092, size: 64)
!1125 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEppEi", scope: !1092, file: !1093, line: 811, type: !1126, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1126 = !DISubroutineType(types: !1127)
!1127 = !{!1092, !1099, !32}
!1128 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEmmEv", scope: !1092, file: !1093, line: 816, type: !1122, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1129 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEmmEi", scope: !1092, file: !1093, line: 823, type: !1126, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1130 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEixEl", scope: !1092, file: !1093, line: 828, type: !1131, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1131 = !DISubroutineType(types: !1132)
!1132 = !{!1108, !1114, !1133}
!1133 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1092, file: !1093, line: 775, baseType: !1134)
!1134 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1111, file: !1110, line: 182, baseType: !1135)
!1135 = !DIDerivedType(tag: DW_TAG_typedef, name: "ptrdiff_t", scope: !839, file: !906, line: 239, baseType: !288)
!1136 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEpLEl", scope: !1092, file: !1093, line: 832, type: !1137, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1137 = !DISubroutineType(types: !1138)
!1138 = !{!1124, !1099, !1133}
!1139 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEplEl", scope: !1092, file: !1093, line: 836, type: !1140, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1140 = !DISubroutineType(types: !1141)
!1141 = !{!1092, !1114, !1133}
!1142 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEmIEl", scope: !1092, file: !1093, line: 840, type: !1137, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1143 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEmiEl", scope: !1092, file: !1093, line: 844, type: !1140, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1144 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEE4baseEv", scope: !1092, file: !1093, line: 848, type: !1145, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1145 = !DISubroutineType(types: !1146)
!1146 = !{!1103, !1114}
!1147 = !{!1113, !1148}
!1148 = !DITemplateTypeParameter(name: "_Container", type: !837)
!1149 = !DISubprogram(name: "begin", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE5beginEv", scope: !837, file: !838, line: 707, type: !1150, scopeLine: 707, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1150 = !DISubroutineType(types: !1151)
!1151 = !{!1152, !1154}
!1152 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !837, file: !838, line: 371, baseType: !1153)
!1153 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<const llvm::PassInfo *const *, std::vector<const llvm::PassInfo *, std::allocator<const llvm::PassInfo *> > >", scope: !5, file: !1093, line: 764, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPKPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEE")
!1154 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1055, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1155 = !DISubprogram(name: "end", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE3endEv", scope: !837, file: !838, line: 716, type: !1089, scopeLine: 716, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1156 = !DISubprogram(name: "end", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE3endEv", scope: !837, file: !838, line: 725, type: !1150, scopeLine: 725, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1157 = !DISubprogram(name: "rbegin", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6rbeginEv", scope: !837, file: !838, line: 734, type: !1158, scopeLine: 734, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1158 = !DISubroutineType(types: !1159)
!1159 = !{!1160, !1034}
!1160 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !837, file: !838, line: 373, baseType: !1161)
!1161 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<const llvm::PassInfo **, std::vector<const llvm::PassInfo *, std::allocator<const llvm::PassInfo *> > > >", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS5_SaIS5_EEEEE")
!1162 = !DISubprogram(name: "rbegin", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE6rbeginEv", scope: !837, file: !838, line: 743, type: !1163, scopeLine: 743, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1163 = !DISubroutineType(types: !1164)
!1164 = !{!1165, !1154}
!1165 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !837, file: !838, line: 372, baseType: !1166)
!1166 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<const llvm::PassInfo *const *, std::vector<const llvm::PassInfo *, std::allocator<const llvm::PassInfo *> > > >", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPKPKN4llvm8PassInfoESt6vectorIS5_SaIS5_EEEEE")
!1167 = !DISubprogram(name: "rend", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE4rendEv", scope: !837, file: !838, line: 752, type: !1158, scopeLine: 752, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1168 = !DISubprogram(name: "rend", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE4rendEv", scope: !837, file: !838, line: 761, type: !1163, scopeLine: 761, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1169 = !DISubprogram(name: "cbegin", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE6cbeginEv", scope: !837, file: !838, line: 771, type: !1150, scopeLine: 771, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1170 = !DISubprogram(name: "cend", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE4cendEv", scope: !837, file: !838, line: 780, type: !1150, scopeLine: 780, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1171 = !DISubprogram(name: "crbegin", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE7crbeginEv", scope: !837, file: !838, line: 789, type: !1163, scopeLine: 789, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1172 = !DISubprogram(name: "crend", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE5crendEv", scope: !837, file: !838, line: 798, type: !1163, scopeLine: 798, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1173 = !DISubprogram(name: "size", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE4sizeEv", scope: !837, file: !838, line: 805, type: !1174, scopeLine: 805, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1174 = !DISubroutineType(types: !1175)
!1175 = !{!1044, !1154}
!1176 = !DISubprogram(name: "max_size", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE8max_sizeEv", scope: !837, file: !838, line: 810, type: !1174, scopeLine: 810, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1177 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6resizeEm", scope: !837, file: !838, line: 824, type: !1178, scopeLine: 824, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1178 = !DISubroutineType(types: !1179)
!1179 = !{null, !1034, !1044}
!1180 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6resizeEmRKS3_", scope: !837, file: !838, line: 844, type: !1083, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1181 = !DISubprogram(name: "shrink_to_fit", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE13shrink_to_fitEv", scope: !837, file: !838, line: 876, type: !1032, scopeLine: 876, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1182 = !DISubprogram(name: "capacity", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE8capacityEv", scope: !837, file: !838, line: 885, type: !1174, scopeLine: 885, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1183 = !DISubprogram(name: "empty", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE5emptyEv", scope: !837, file: !838, line: 894, type: !1184, scopeLine: 894, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1184 = !DISubroutineType(types: !1185)
!1185 = !{!145, !1154}
!1186 = !DISubprogram(name: "reserve", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE7reserveEm", scope: !837, file: !838, line: 915, type: !1178, scopeLine: 915, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1187 = !DISubprogram(name: "operator[]", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EEixEm", scope: !837, file: !838, line: 930, type: !1188, scopeLine: 930, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1188 = !DISubroutineType(types: !1189)
!1189 = !{!1190, !1034, !1044}
!1190 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !837, file: !838, line: 367, baseType: !1191)
!1191 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !852, file: !850, line: 64, baseType: !1192)
!1192 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1193, size: 64)
!1193 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !852, file: !850, line: 58, baseType: !1194)
!1194 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !855, file: !856, line: 389, baseType: !863)
!1195 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EEixEm", scope: !837, file: !838, line: 948, type: !1196, scopeLine: 948, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1196 = !DISubroutineType(types: !1197)
!1197 = !{!1198, !1154, !1044}
!1198 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !837, file: !838, line: 368, baseType: !1199)
!1199 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !852, file: !850, line: 65, baseType: !1200)
!1200 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1201, size: 64)
!1201 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1193)
!1202 = !DISubprogram(name: "_M_range_check", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE14_M_range_checkEm", scope: !837, file: !838, line: 957, type: !1203, scopeLine: 957, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1203 = !DISubroutineType(types: !1204)
!1204 = !{null, !1154, !1044}
!1205 = !DISubprogram(name: "at", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE2atEm", scope: !837, file: !838, line: 979, type: !1188, scopeLine: 979, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1206 = !DISubprogram(name: "at", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE2atEm", scope: !837, file: !838, line: 997, type: !1196, scopeLine: 997, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1207 = !DISubprogram(name: "front", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE5frontEv", scope: !837, file: !838, line: 1008, type: !1208, scopeLine: 1008, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1208 = !DISubroutineType(types: !1209)
!1209 = !{!1190, !1034}
!1210 = !DISubprogram(name: "front", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE5frontEv", scope: !837, file: !838, line: 1019, type: !1211, scopeLine: 1019, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1211 = !DISubroutineType(types: !1212)
!1212 = !{!1198, !1154}
!1213 = !DISubprogram(name: "back", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE4backEv", scope: !837, file: !838, line: 1030, type: !1208, scopeLine: 1030, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1214 = !DISubprogram(name: "back", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE4backEv", scope: !837, file: !838, line: 1041, type: !1211, scopeLine: 1041, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1215 = !DISubprogram(name: "data", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE4dataEv", scope: !837, file: !838, line: 1055, type: !1216, scopeLine: 1055, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1216 = !DISubroutineType(types: !1217)
!1217 = !{!862, !1034}
!1218 = !DISubprogram(name: "data", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE4dataEv", scope: !837, file: !838, line: 1059, type: !1219, scopeLine: 1059, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1219 = !DISubroutineType(types: !1220)
!1220 = !{!897, !1154}
!1221 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE9push_backERKS3_", scope: !837, file: !838, line: 1074, type: !1222, scopeLine: 1074, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1222 = !DISubroutineType(types: !1223)
!1223 = !{null, !1034, !1048}
!1224 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE9push_backEOS3_", scope: !837, file: !838, line: 1090, type: !1225, scopeLine: 1090, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1225 = !DISubroutineType(types: !1226)
!1226 = !{null, !1034, !1227}
!1227 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1050, size: 64)
!1228 = !DISubprogram(name: "pop_back", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE8pop_backEv", scope: !837, file: !838, line: 1112, type: !1032, scopeLine: 1112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1229 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EERS8_", scope: !837, file: !838, line: 1150, type: !1230, scopeLine: 1150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1230 = !DISubroutineType(types: !1231)
!1231 = !{!1091, !1034, !1152, !1048}
!1232 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EEOS3_", scope: !837, file: !838, line: 1180, type: !1233, scopeLine: 1180, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1233 = !DISubroutineType(types: !1234)
!1234 = !{!1091, !1034, !1152, !1227}
!1235 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EESt16initializer_listIS3_E", scope: !837, file: !838, line: 1197, type: !1236, scopeLine: 1197, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1236 = !DISubroutineType(types: !1237)
!1237 = !{!1091, !1034, !1152, !1069}
!1238 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EEmRS8_", scope: !837, file: !838, line: 1222, type: !1239, scopeLine: 1222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1239 = !DISubroutineType(types: !1240)
!1240 = !{!1091, !1034, !1152, !1044, !1048}
!1241 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE5eraseEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EE", scope: !837, file: !838, line: 1317, type: !1242, scopeLine: 1317, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1242 = !DISubroutineType(types: !1243)
!1243 = !{!1091, !1034, !1152}
!1244 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE5eraseEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EESA_", scope: !837, file: !838, line: 1344, type: !1245, scopeLine: 1344, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1245 = !DISubroutineType(types: !1246)
!1246 = !{!1091, !1034, !1152, !1152}
!1247 = !DISubprogram(name: "swap", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE4swapERS5_", scope: !837, file: !838, line: 1367, type: !1248, scopeLine: 1367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1248 = !DISubroutineType(types: !1249)
!1249 = !{null, !1034, !1075}
!1250 = !DISubprogram(name: "clear", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE5clearEv", scope: !837, file: !838, line: 1385, type: !1032, scopeLine: 1385, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1251 = !DISubprogram(name: "_M_fill_initialize", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE18_M_fill_initializeEmRKS3_", scope: !837, file: !838, line: 1477, type: !1083, scopeLine: 1477, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1252 = !DISubprogram(name: "_M_default_initialize", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE21_M_default_initializeEm", scope: !837, file: !838, line: 1487, type: !1178, scopeLine: 1487, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1253 = !DISubprogram(name: "_M_fill_assign", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE14_M_fill_assignEmRKS3_", scope: !837, file: !838, line: 1529, type: !1083, scopeLine: 1529, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1254 = !DISubprogram(name: "_M_fill_insert", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS3_S5_EEmRKS3_", scope: !837, file: !838, line: 1568, type: !1255, scopeLine: 1568, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1255 = !DISubroutineType(types: !1256)
!1256 = !{null, !1034, !1091, !1044, !1048}
!1257 = !DISubprogram(name: "_M_default_append", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE17_M_default_appendEm", scope: !837, file: !838, line: 1573, type: !1178, scopeLine: 1573, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1258 = !DISubprogram(name: "_M_shrink_to_fit", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE16_M_shrink_to_fitEv", scope: !837, file: !838, line: 1576, type: !1259, scopeLine: 1576, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1259 = !DISubroutineType(types: !1260)
!1260 = !{!145, !1034}
!1261 = !DISubprogram(name: "_M_insert_rval", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE14_M_insert_rvalEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EEOS3_", scope: !837, file: !838, line: 1625, type: !1233, scopeLine: 1625, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1262 = !DISubprogram(name: "_M_emplace_aux", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE14_M_emplace_auxEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EEOS3_", scope: !837, file: !838, line: 1634, type: !1233, scopeLine: 1634, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1263 = !DISubprogram(name: "_M_check_len", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE12_M_check_lenEmPKc", scope: !837, file: !838, line: 1640, type: !1264, scopeLine: 1640, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1264 = !DISubroutineType(types: !1265)
!1265 = !{!1266, !1154, !1044, !317}
!1266 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !837, file: !838, line: 374, baseType: !905)
!1267 = !DISubprogram(name: "_M_erase_at_end", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE15_M_erase_at_endEPS3_", scope: !837, file: !838, line: 1654, type: !1268, scopeLine: 1654, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1268 = !DISubroutineType(types: !1269)
!1269 = !{null, !1034, !1270}
!1270 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !837, file: !838, line: 365, baseType: !963)
!1271 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE8_M_eraseEN9__gnu_cxx17__normal_iteratorIPS3_S5_EE", scope: !837, file: !838, line: 1666, type: !1272, scopeLine: 1666, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1272 = !DISubroutineType(types: !1273)
!1273 = !{!1091, !1034, !1091}
!1274 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE8_M_eraseEN9__gnu_cxx17__normal_iteratorIPS3_S5_EES9_", scope: !837, file: !838, line: 1669, type: !1275, scopeLine: 1669, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1275 = !DISubroutineType(types: !1276)
!1276 = !{!1091, !1034, !1091, !1091}
!1277 = !DISubprogram(name: "_M_move_assign", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE14_M_move_assignEOS5_St17integral_constantIbLb1EE", scope: !837, file: !838, line: 1677, type: !1278, scopeLine: 1677, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1278 = !DISubroutineType(types: !1279)
!1279 = !{null, !1034, !1059, !1280}
!1280 = !DIDerivedType(tag: DW_TAG_typedef, name: "true_type", scope: !839, file: !1281, line: 75, baseType: !1282)
!1281 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/type_traits", directory: "")
!1282 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "integral_constant<bool, true>", scope: !839, file: !1281, line: 57, size: 8, flags: DIFlagTypePassByValue, elements: !1283, templateParams: !1292, identifier: "_ZTSSt17integral_constantIbLb1EE")
!1283 = !{!1284, !1285, !1291}
!1284 = !DIDerivedType(tag: DW_TAG_member, name: "value", scope: !1282, file: !1281, line: 59, baseType: !833, flags: DIFlagStaticMember, extraData: i1 true)
!1285 = !DISubprogram(name: "operator bool", linkageName: "_ZNKSt17integral_constantIbLb1EEcvbEv", scope: !1282, file: !1281, line: 62, type: !1286, scopeLine: 62, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1286 = !DISubroutineType(types: !1287)
!1287 = !{!1288, !1289}
!1288 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1282, file: !1281, line: 60, baseType: !145)
!1289 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1290, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1290 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1282)
!1291 = !DISubprogram(name: "operator()", linkageName: "_ZNKSt17integral_constantIbLb1EEclEv", scope: !1282, file: !1281, line: 67, type: !1286, scopeLine: 67, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1292 = !{!1293, !1294}
!1293 = !DITemplateTypeParameter(name: "_Tp", type: !145)
!1294 = !DITemplateValueParameter(name: "__v", type: !145, value: i8 1)
!1295 = !DISubprogram(name: "_M_move_assign", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE14_M_move_assignEOS5_St17integral_constantIbLb0EE", scope: !837, file: !838, line: 1688, type: !1296, scopeLine: 1688, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1296 = !DISubroutineType(types: !1297)
!1297 = !{null, !1034, !1059, !1298}
!1298 = !DIDerivedType(tag: DW_TAG_typedef, name: "false_type", scope: !839, file: !1281, line: 78, baseType: !1299)
!1299 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "integral_constant<bool, false>", scope: !839, file: !1281, line: 57, size: 8, flags: DIFlagTypePassByValue, elements: !1300, templateParams: !1309, identifier: "_ZTSSt17integral_constantIbLb0EE")
!1300 = !{!1301, !1302, !1308}
!1301 = !DIDerivedType(tag: DW_TAG_member, name: "value", scope: !1299, file: !1281, line: 59, baseType: !833, flags: DIFlagStaticMember, extraData: i1 false)
!1302 = !DISubprogram(name: "operator bool", linkageName: "_ZNKSt17integral_constantIbLb0EEcvbEv", scope: !1299, file: !1281, line: 62, type: !1303, scopeLine: 62, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1303 = !DISubroutineType(types: !1304)
!1304 = !{!1305, !1306}
!1305 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1299, file: !1281, line: 60, baseType: !145)
!1306 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1307, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1307 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1299)
!1308 = !DISubprogram(name: "operator()", linkageName: "_ZNKSt17integral_constantIbLb0EEclEv", scope: !1299, file: !1281, line: 67, type: !1303, scopeLine: 67, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1309 = !{!1293, !1310}
!1310 = !DITemplateValueParameter(name: "__v", type: !145, value: i8 0)
!1311 = !DIDerivedType(tag: DW_TAG_member, name: "NormalCtor", scope: !826, file: !825, line: 52, baseType: !824, size: 64, offset: 448)
!1312 = !DISubprogram(name: "PassInfo", scope: !826, file: !825, line: 57, type: !1313, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1313 = !DISubroutineType(types: !1314)
!1314 = !{null, !1315, !317, !317, !124, !824, !145, !145}
!1315 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !826, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1316 = !DISubprogram(name: "PassInfo", scope: !826, file: !825, line: 65, type: !1317, scopeLine: 65, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1317 = !DISubroutineType(types: !1318)
!1318 = !{null, !1315, !317, !124}
!1319 = !DISubprogram(name: "getPassName", linkageName: "_ZNK4llvm8PassInfo11getPassNameEv", scope: !826, file: !825, line: 72, type: !1320, scopeLine: 72, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1320 = !DISubroutineType(types: !1321)
!1321 = !{!317, !1322}
!1322 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !864, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1323 = !DISubprogram(name: "getPassArgument", linkageName: "_ZNK4llvm8PassInfo15getPassArgumentEv", scope: !826, file: !825, line: 78, type: !1320, scopeLine: 78, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1324 = !DISubprogram(name: "getTypeInfo", linkageName: "_ZNK4llvm8PassInfo11getTypeInfoEv", scope: !826, file: !825, line: 82, type: !1325, scopeLine: 82, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1325 = !DISubroutineType(types: !1326)
!1326 = !{!124, !1322}
!1327 = !DISubprogram(name: "isPassID", linkageName: "_ZNK4llvm8PassInfo8isPassIDEPKv", scope: !826, file: !825, line: 85, type: !1328, scopeLine: 85, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1328 = !DISubroutineType(types: !1329)
!1329 = !{!145, !1322, !124}
!1330 = !DISubprogram(name: "isAnalysisGroup", linkageName: "_ZNK4llvm8PassInfo15isAnalysisGroupEv", scope: !826, file: !825, line: 92, type: !1331, scopeLine: 92, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1331 = !DISubroutineType(types: !1332)
!1332 = !{!145, !1322}
!1333 = !DISubprogram(name: "isAnalysis", linkageName: "_ZNK4llvm8PassInfo10isAnalysisEv", scope: !826, file: !825, line: 93, type: !1331, scopeLine: 93, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1334 = !DISubprogram(name: "isCFGOnlyPass", linkageName: "_ZNK4llvm8PassInfo13isCFGOnlyPassEv", scope: !826, file: !825, line: 97, type: !1331, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1335 = !DISubprogram(name: "getNormalCtor", linkageName: "_ZNK4llvm8PassInfo13getNormalCtorEv", scope: !826, file: !825, line: 103, type: !1336, scopeLine: 103, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1336 = !DISubroutineType(types: !1337)
!1337 = !{!824, !1322}
!1338 = !DISubprogram(name: "setNormalCtor", linkageName: "_ZN4llvm8PassInfo13setNormalCtorEPFPNS_4PassEvE", scope: !826, file: !825, line: 106, type: !1339, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1339 = !DISubroutineType(types: !1340)
!1340 = !{null, !1315, !824}
!1341 = !DISubprogram(name: "createPass", linkageName: "_ZNK4llvm8PassInfo10createPassEv", scope: !826, file: !825, line: 111, type: !1342, scopeLine: 111, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1342 = !DISubroutineType(types: !1343)
!1343 = !{!1344, !1322}
!1344 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1345, size: 64)
!1345 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Pass", scope: !14, file: !20, line: 82, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm4PassE")
!1346 = !DISubprogram(name: "addInterfaceImplemented", linkageName: "_ZN4llvm8PassInfo23addInterfaceImplementedEPKS0_", scope: !826, file: !825, line: 117, type: !1347, scopeLine: 117, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1347 = !DISubroutineType(types: !1348)
!1348 = !{null, !1315, !863}
!1349 = !DISubprogram(name: "getInterfacesImplemented", linkageName: "_ZNK4llvm8PassInfo24getInterfacesImplementedEv", scope: !826, file: !825, line: 124, type: !1350, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1350 = !DISubroutineType(types: !1351)
!1351 = !{!1054, !1322}
!1352 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8PassInfoaSERKS0_", scope: !826, file: !825, line: 129, type: !1353, scopeLine: 129, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1353 = !DISubroutineType(types: !1354)
!1354 = !{null, !1315, !1355}
!1355 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !864, size: 64)
!1356 = !DISubprogram(name: "PassInfo", scope: !826, file: !825, line: 130, type: !1353, scopeLine: 130, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1357 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1358, size: 64)
!1358 = !DISubroutineType(types: !1359)
!1359 = !{!1344}
!1360 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !319, size: 64)
!1361 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1362, size: 64)
!1362 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !1364, file: !1363, line: 540, baseType: !2191)
!1363 = !DIFile(filename: "llvm34/include/llvm/ADT/DenseMap.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e4a1c2d5b55fe605534e57bb36c4fe71")
!1364 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMap<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > >, llvm::DenseMapInfo<unsigned int> >", scope: !14, file: !1363, line: 534, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1365, templateParams: !2312, identifier: "_ZTSN4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEEE")
!1365 = !{!1366, !2264, !2265, !2266, !2267, !2268, !2272, !2277, !2281, !2284, !2288, !2291, !2294, !2295, !2296, !2297, !2298, !2302, !2303, !2304, !2305, !2308, !2309}
!1366 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1364, baseType: !1367, flags: DIFlagPublic, extraData: i32 0)
!1367 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapBase<llvm::DenseMap<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > >, llvm::DenseMapInfo<unsigned int> >, unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > >, llvm::DenseMapInfo<unsigned int> >", scope: !14, file: !1363, line: 41, size: 8, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1368, templateParams: !2262, identifier: "_ZTSN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_EE")
!1368 = !{!1369, !2085, !2086, !2092, !2093, !2096, !2099, !2104, !2107, !2110, !2113, !2116, !2119, !2177, !2180, !2183, !2186, !2192, !2195, !2199, !2202, !2205, !2208, !2209, !2210, !2211, !2215, !2219, !2220, !2223, !2224, !2225, !2228, !2229, !2230, !2231, !2232, !2233, !2234, !2239, !2242, !2243, !2244, !2245, !2246, !2247, !2250, !2253, !2256, !2259}
!1369 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E5beginEv", scope: !1367, file: !1363, line: 53, type: !1370, scopeLine: 53, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1370 = !DISubroutineType(types: !1371)
!1371 = !{!1372, !2084}
!1372 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1367, file: !1363, line: 50, baseType: !1373)
!1373 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapIterator<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > >, llvm::DenseMapInfo<unsigned int>, false>", scope: !14, file: !1363, line: 987, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1374, templateParams: !2082, identifier: "_ZTSN4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb0EEE")
!1374 = !{!1375, !1977, !1978, !1982, !1985, !1990, !1996, !1999, !2073, !2074, !2078, !2081}
!1375 = !DIDerivedType(tag: DW_TAG_member, name: "Ptr", scope: !1373, file: !1363, line: 999, baseType: !1376, size: 64)
!1376 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1373, file: !1363, line: 995, baseType: !1377)
!1377 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1378, size: 64)
!1378 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1373, file: !1363, line: 994, baseType: !1379)
!1379 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1381, file: !1380, line: 236, baseType: !1386)
!1380 = !DIFile(filename: "llvm34/include/llvm/Support/type_traits.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "3b111e0adbb374a4c7fc591de906379a")
!1381 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<false, const std::pair<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > > >, std::pair<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > > > >", scope: !14, file: !1380, line: 236, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !1382, identifier: "_ZTSN4llvm11conditionalILb0EKSt4pairIjSt6vectorIS1_IPNS_17MachineBasicBlockEjESaIS5_EEES8_EE")
!1382 = !{!1383, !1384, !1976}
!1383 = !DITemplateValueParameter(type: !145, value: i8 0)
!1384 = !DITemplateTypeParameter(name: "T", type: !1385)
!1385 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1386)
!1386 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > > >", scope: !839, file: !1387, line: 208, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1388, templateParams: !1973, identifier: "_ZTSSt4pairIjSt6vectorIS_IPN4llvm17MachineBasicBlockEjESaIS4_EEE")
!1387 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_pair.h", directory: "", checksumkind: CSK_MD5, checksum: "9a7996187125e471e26ca57a6c9f4c5e")
!1388 = !{!1389, !1944, !1945, !1946, !1951, !1955, !1963, !1970}
!1389 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1386, baseType: !1390, flags: DIFlagPrivate, extraData: i32 0)
!1390 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > > >", scope: !839, file: !1387, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !1391, templateParams: !1406, identifier: "_ZTSSt11__pair_baseIjSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS5_EEE")
!1391 = !{!1392, !1396, !1397, !1402}
!1392 = !DISubprogram(name: "__pair_base", scope: !1390, file: !1387, line: 194, type: !1393, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1393 = !DISubroutineType(types: !1394)
!1394 = !{null, !1395}
!1395 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1390, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1396 = !DISubprogram(name: "~__pair_base", scope: !1390, file: !1387, line: 195, type: !1393, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1397 = !DISubprogram(name: "__pair_base", scope: !1390, file: !1387, line: 196, type: !1398, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1398 = !DISubroutineType(types: !1399)
!1399 = !{null, !1395, !1400}
!1400 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1401, size: 64)
!1401 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1390)
!1402 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIjSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS5_EEEaSERKS8_", scope: !1390, file: !1387, line: 197, type: !1403, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1403 = !DISubroutineType(types: !1404)
!1404 = !{!1405, !1395, !1400}
!1405 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1390, size: 64)
!1406 = !{!1407, !1408}
!1407 = !DITemplateTypeParameter(name: "_U1", type: !6)
!1408 = !DITemplateTypeParameter(name: "_U2", type: !1409)
!1409 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > >", scope: !839, file: !838, line: 339, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1410, templateParams: !1644, identifier: "_ZTSSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE")
!1410 = !{!1411, !1645, !1649, !1655, !1658, !1664, !1669, !1673, !1676, !1679, !1683, !1684, !1688, !1691, !1694, !1697, !1700, !1758, !1816, !1817, !1818, !1823, !1828, !1829, !1830, !1831, !1832, !1833, !1834, !1837, !1838, !1841, !1842, !1843, !1844, !1847, !1848, !1856, !1863, !1866, !1867, !1868, !1871, !1874, !1875, !1876, !1879, !1882, !1885, !1889, !1890, !1893, !1896, !1899, !1902, !1905, !1908, !1911, !1912, !1913, !1914, !1915, !1918, !1919, !1922, !1923, !1924, !1928, !1932, !1935, !1938, !1941}
!1411 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1409, baseType: !1412, flags: DIFlagProtected, extraData: i32 0)
!1412 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_base<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > >", scope: !839, file: !838, line: 81, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1413, templateParams: !1644, identifier: "_ZTSSt12_Vector_baseISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE")
!1413 = !{!1414, !1598, !1603, !1608, !1612, !1615, !1620, !1623, !1626, !1629, !1633, !1636, !1637, !1640, !1643}
!1414 = !DIDerivedType(tag: DW_TAG_member, name: "_M_impl", scope: !1412, file: !838, line: 290, baseType: !1415, size: 192)
!1415 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_impl", scope: !1412, file: !838, line: 88, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1416, identifier: "_ZTSNSt12_Vector_baseISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE12_Vector_implE")
!1416 = !{!1417, !1576, !1579, !1580, !1581, !1585, !1590, !1594}
!1417 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1415, baseType: !1418, extraData: i32 0)
!1418 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Tp_alloc_type", scope: !1412, file: !838, line: 84, baseType: !1419)
!1419 = !DIDerivedType(tag: DW_TAG_typedef, name: "other", scope: !1420, file: !850, line: 117, baseType: !1575)
!1420 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "rebind<std::pair<llvm::MachineBasicBlock *, unsigned int> >", scope: !1421, file: !850, line: 116, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !1532, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEES5_E6rebindIS5_EE")
!1421 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__alloc_traits<std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> >, std::pair<llvm::MachineBasicBlock *, unsigned int> >", scope: !5, file: !850, line: 50, size: 8, flags: DIFlagTypePassByValue, elements: !1422, templateParams: !1573, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEES5_EE")
!1422 = !{!1423, !1561, !1564, !1568, !1569, !1570, !1571, !1572}
!1423 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1421, baseType: !1424, extraData: i32 0)
!1424 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "allocator_traits<std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > >", scope: !839, file: !856, line: 384, size: 8, flags: DIFlagTypePassByValue, elements: !1425, templateParams: !1559, identifier: "_ZTSSt16allocator_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEEE")
!1425 = !{!1426, !1544, !1547, !1550, !1556}
!1426 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEEE8allocateERS5_m", scope: !1424, file: !856, line: 435, type: !1427, scopeLine: 435, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1427 = !DISubroutineType(types: !1428)
!1428 = !{!1429, !1493, !925}
!1429 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1424, file: !856, line: 392, baseType: !1430)
!1430 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1431, size: 64)
!1431 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::MachineBasicBlock *, unsigned int>", scope: !839, file: !1387, line: 208, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1432, templateParams: !1490, identifier: "_ZTSSt4pairIPN4llvm17MachineBasicBlockEjE")
!1432 = !{!1433, !1453, !1454, !1455, !1461, !1465, !1478, !1487}
!1433 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1431, baseType: !1434, flags: DIFlagPrivate, extraData: i32 0)
!1434 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::MachineBasicBlock *, unsigned int>", scope: !839, file: !1387, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !1435, templateParams: !1450, identifier: "_ZTSSt11__pair_baseIPN4llvm17MachineBasicBlockEjE")
!1435 = !{!1436, !1440, !1441, !1446}
!1436 = !DISubprogram(name: "__pair_base", scope: !1434, file: !1387, line: 194, type: !1437, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1437 = !DISubroutineType(types: !1438)
!1438 = !{null, !1439}
!1439 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1434, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1440 = !DISubprogram(name: "~__pair_base", scope: !1434, file: !1387, line: 195, type: !1437, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1441 = !DISubprogram(name: "__pair_base", scope: !1434, file: !1387, line: 196, type: !1442, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1442 = !DISubroutineType(types: !1443)
!1443 = !{null, !1439, !1444}
!1444 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1445, size: 64)
!1445 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1434)
!1446 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIPN4llvm17MachineBasicBlockEjEaSERKS3_", scope: !1434, file: !1387, line: 197, type: !1447, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1447 = !DISubroutineType(types: !1448)
!1448 = !{!1449, !1439, !1444}
!1449 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1434, size: 64)
!1450 = !{!1451, !1452}
!1451 = !DITemplateTypeParameter(name: "_U1", type: !197)
!1452 = !DITemplateTypeParameter(name: "_U2", type: !6)
!1453 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !1431, file: !1387, line: 214, baseType: !197, size: 64)
!1454 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !1431, file: !1387, line: 215, baseType: !6, size: 32, offset: 64)
!1455 = !DISubprogram(name: "pair", scope: !1431, file: !1387, line: 303, type: !1456, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1456 = !DISubroutineType(types: !1457)
!1457 = !{null, !1458, !1459}
!1458 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1431, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1459 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1460, size: 64)
!1460 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1431)
!1461 = !DISubprogram(name: "pair", scope: !1431, file: !1387, line: 304, type: !1462, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1462 = !DISubroutineType(types: !1463)
!1463 = !{null, !1458, !1464}
!1464 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1431, size: 64)
!1465 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPN4llvm17MachineBasicBlockEjEaSERKS3_", scope: !1431, file: !1387, line: 378, type: !1466, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1466 = !DISubroutineType(types: !1467)
!1467 = !{!1468, !1458, !1469}
!1468 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1431, size: 64)
!1469 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1470, file: !1281, line: 1928, baseType: !1459)
!1470 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::MachineBasicBlock *, unsigned int> &, const std::__nonesuch_no_braces &>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !1471, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIPN4llvm17MachineBasicBlockEjERKSt20__nonesuch_no_bracesE")
!1471 = !{!1472, !1473, !1474}
!1472 = !DITemplateValueParameter(name: "_Cond", type: !145, value: i8 1)
!1473 = !DITemplateTypeParameter(name: "_Iftrue", type: !1459)
!1474 = !DITemplateTypeParameter(name: "_Iffalse", type: !1475)
!1475 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1476, size: 64)
!1476 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1477)
!1477 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__nonesuch_no_braces", scope: !839, file: !1387, line: 185, size: 8, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt20__nonesuch_no_braces")
!1478 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPN4llvm17MachineBasicBlockEjEaSEOS3_", scope: !1431, file: !1387, line: 389, type: !1479, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1479 = !DISubroutineType(types: !1480)
!1480 = !{!1468, !1458, !1481}
!1481 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1482, file: !1281, line: 1928, baseType: !1464)
!1482 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::MachineBasicBlock *, unsigned int> &&, std::__nonesuch_no_braces &&>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !1483, identifier: "_ZTSSt11conditionalILb1EOSt4pairIPN4llvm17MachineBasicBlockEjEOSt20__nonesuch_no_bracesE")
!1483 = !{!1472, !1484, !1485}
!1484 = !DITemplateTypeParameter(name: "_Iftrue", type: !1464)
!1485 = !DITemplateTypeParameter(name: "_Iffalse", type: !1486)
!1486 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1477, size: 64)
!1487 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIPN4llvm17MachineBasicBlockEjE4swapERS3_", scope: !1431, file: !1387, line: 424, type: !1488, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1488 = !DISubroutineType(types: !1489)
!1489 = !{null, !1458, !1468}
!1490 = !{!1491, !1492}
!1491 = !DITemplateTypeParameter(name: "_T1", type: !197)
!1492 = !DITemplateTypeParameter(name: "_T2", type: !6)
!1493 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1494, size: 64)
!1494 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !1424, file: !856, line: 387, baseType: !1495)
!1495 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> >", scope: !839, file: !868, line: 108, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1496, templateParams: !1532, identifier: "_ZTSSaISt4pairIPN4llvm17MachineBasicBlockEjEE")
!1496 = !{!1497, !1534, !1538, !1543}
!1497 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1495, baseType: !1498, flags: DIFlagPublic, extraData: i32 0)
!1498 = !DIDerivedType(tag: DW_TAG_typedef, name: "__allocator_base<std::pair<llvm::MachineBasicBlock *, unsigned int> >", scope: !839, file: !872, line: 48, baseType: !1499)
!1499 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "new_allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> >", scope: !5, file: !874, line: 58, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1500, templateParams: !1532, identifier: "_ZTSN9__gnu_cxx13new_allocatorISt4pairIPN4llvm17MachineBasicBlockEjEEE")
!1500 = !{!1501, !1505, !1510, !1511, !1517, !1523, !1526, !1529}
!1501 = !DISubprogram(name: "new_allocator", scope: !1499, file: !874, line: 79, type: !1502, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1502 = !DISubroutineType(types: !1503)
!1503 = !{null, !1504}
!1504 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1499, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1505 = !DISubprogram(name: "new_allocator", scope: !1499, file: !874, line: 81, type: !1506, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1506 = !DISubroutineType(types: !1507)
!1507 = !{null, !1504, !1508}
!1508 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1509, size: 64)
!1509 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1499)
!1510 = !DISubprogram(name: "~new_allocator", scope: !1499, file: !874, line: 86, type: !1502, scopeLine: 86, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1511 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorISt4pairIPN4llvm17MachineBasicBlockEjEE7addressERS5_", scope: !1499, file: !874, line: 89, type: !1512, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1512 = !DISubroutineType(types: !1513)
!1513 = !{!1514, !1515, !1516}
!1514 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1499, file: !874, line: 63, baseType: !1430)
!1515 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1509, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1516 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1499, file: !874, line: 65, baseType: !1468)
!1517 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorISt4pairIPN4llvm17MachineBasicBlockEjEE7addressERKS5_", scope: !1499, file: !874, line: 93, type: !1518, scopeLine: 93, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1518 = !DISubroutineType(types: !1519)
!1519 = !{!1520, !1515, !1522}
!1520 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !1499, file: !874, line: 64, baseType: !1521)
!1521 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1460, size: 64)
!1522 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1499, file: !874, line: 66, baseType: !1459)
!1523 = !DISubprogram(name: "allocate", linkageName: "_ZN9__gnu_cxx13new_allocatorISt4pairIPN4llvm17MachineBasicBlockEjEE8allocateEmPKv", scope: !1499, file: !874, line: 99, type: !1524, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1524 = !DISubroutineType(types: !1525)
!1525 = !{!1514, !1504, !904, !124}
!1526 = !DISubprogram(name: "deallocate", linkageName: "_ZN9__gnu_cxx13new_allocatorISt4pairIPN4llvm17MachineBasicBlockEjEE10deallocateEPS5_m", scope: !1499, file: !874, line: 116, type: !1527, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1527 = !DISubroutineType(types: !1528)
!1528 = !{null, !1504, !1514, !904}
!1529 = !DISubprogram(name: "max_size", linkageName: "_ZNK9__gnu_cxx13new_allocatorISt4pairIPN4llvm17MachineBasicBlockEjEE8max_sizeEv", scope: !1499, file: !874, line: 129, type: !1530, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1530 = !DISubroutineType(types: !1531)
!1531 = !{!904, !1515}
!1532 = !{!1533}
!1533 = !DITemplateTypeParameter(name: "_Tp", type: !1431)
!1534 = !DISubprogram(name: "allocator", scope: !1495, file: !868, line: 131, type: !1535, scopeLine: 131, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1535 = !DISubroutineType(types: !1536)
!1536 = !{null, !1537}
!1537 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1495, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1538 = !DISubprogram(name: "allocator", scope: !1495, file: !868, line: 133, type: !1539, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1539 = !DISubroutineType(types: !1540)
!1540 = !{null, !1537, !1541}
!1541 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1542, size: 64)
!1542 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1495)
!1543 = !DISubprogram(name: "~allocator", scope: !1495, file: !868, line: 139, type: !1535, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1544 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEEE8allocateERS5_mPKv", scope: !1424, file: !856, line: 449, type: !1545, scopeLine: 449, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1545 = !DISubroutineType(types: !1546)
!1546 = !{!1429, !1493, !925, !929}
!1547 = !DISubprogram(name: "deallocate", linkageName: "_ZNSt16allocator_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEEE10deallocateERS5_PS4_m", scope: !1424, file: !856, line: 461, type: !1548, scopeLine: 461, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1548 = !DISubroutineType(types: !1549)
!1549 = !{null, !1493, !1429, !925}
!1550 = !DISubprogram(name: "max_size", linkageName: "_ZNSt16allocator_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEEE8max_sizeERKS5_", scope: !1424, file: !856, line: 495, type: !1551, scopeLine: 495, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1551 = !DISubroutineType(types: !1552)
!1552 = !{!1553, !1554}
!1553 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1424, file: !856, line: 407, baseType: !905)
!1554 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1555, size: 64)
!1555 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1494)
!1556 = !DISubprogram(name: "select_on_container_copy_construction", linkageName: "_ZNSt16allocator_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEEE37select_on_container_copy_constructionERKS5_", scope: !1424, file: !856, line: 504, type: !1557, scopeLine: 504, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1557 = !DISubroutineType(types: !1558)
!1558 = !{!1494, !1554}
!1559 = !{!1560}
!1560 = !DITemplateTypeParameter(name: "_Alloc", type: !1495)
!1561 = !DISubprogram(name: "_S_select_on_copy", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEES5_E17_S_select_on_copyERKS6_", scope: !1421, file: !850, line: 94, type: !1562, scopeLine: 94, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1562 = !DISubroutineType(types: !1563)
!1563 = !{!1495, !1541}
!1564 = !DISubprogram(name: "_S_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEES5_E10_S_on_swapERS6_S8_", scope: !1421, file: !850, line: 97, type: !1565, scopeLine: 97, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1565 = !DISubroutineType(types: !1566)
!1566 = !{null, !1567, !1567}
!1567 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1495, size: 64)
!1568 = !DISubprogram(name: "_S_propagate_on_copy_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEES5_E27_S_propagate_on_copy_assignEv", scope: !1421, file: !850, line: 100, type: !952, scopeLine: 100, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1569 = !DISubprogram(name: "_S_propagate_on_move_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEES5_E27_S_propagate_on_move_assignEv", scope: !1421, file: !850, line: 103, type: !952, scopeLine: 103, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1570 = !DISubprogram(name: "_S_propagate_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEES5_E20_S_propagate_on_swapEv", scope: !1421, file: !850, line: 106, type: !952, scopeLine: 106, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1571 = !DISubprogram(name: "_S_always_equal", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEES5_E15_S_always_equalEv", scope: !1421, file: !850, line: 109, type: !952, scopeLine: 109, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1572 = !DISubprogram(name: "_S_nothrow_move", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaISt4pairIPN4llvm17MachineBasicBlockEjEES5_E15_S_nothrow_moveEv", scope: !1421, file: !850, line: 112, type: !952, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1573 = !{!1560, !1574}
!1574 = !DITemplateTypeParameter(type: !1431)
!1575 = !DIDerivedType(tag: DW_TAG_typedef, name: "rebind_alloc<std::pair<llvm::MachineBasicBlock *, unsigned int> >", scope: !1424, file: !856, line: 422, baseType: !1495)
!1576 = !DIDerivedType(tag: DW_TAG_member, name: "_M_start", scope: !1415, file: !838, line: 91, baseType: !1577, size: 64)
!1577 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1412, file: !838, line: 86, baseType: !1578)
!1578 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1421, file: !850, line: 59, baseType: !1429)
!1579 = !DIDerivedType(tag: DW_TAG_member, name: "_M_finish", scope: !1415, file: !838, line: 92, baseType: !1577, size: 64, offset: 64)
!1580 = !DIDerivedType(tag: DW_TAG_member, name: "_M_end_of_storage", scope: !1415, file: !838, line: 93, baseType: !1577, size: 64, offset: 128)
!1581 = !DISubprogram(name: "_Vector_impl", scope: !1415, file: !838, line: 95, type: !1582, scopeLine: 95, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1582 = !DISubroutineType(types: !1583)
!1583 = !{null, !1584}
!1584 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1415, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1585 = !DISubprogram(name: "_Vector_impl", scope: !1415, file: !838, line: 99, type: !1586, scopeLine: 99, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1586 = !DISubroutineType(types: !1587)
!1587 = !{null, !1584, !1588}
!1588 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1589, size: 64)
!1589 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1418)
!1590 = !DISubprogram(name: "_Vector_impl", scope: !1415, file: !838, line: 104, type: !1591, scopeLine: 104, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1591 = !DISubroutineType(types: !1592)
!1592 = !{null, !1584, !1593}
!1593 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1418, size: 64)
!1594 = !DISubprogram(name: "_M_swap_data", linkageName: "_ZNSt12_Vector_baseISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE12_Vector_impl12_M_swap_dataERS7_", scope: !1415, file: !838, line: 110, type: !1595, scopeLine: 110, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1595 = !DISubroutineType(types: !1596)
!1596 = !{null, !1584, !1597}
!1597 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1415, size: 64)
!1598 = !DISubprogram(name: "_M_get_Tp_allocator", linkageName: "_ZNSt12_Vector_baseISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE19_M_get_Tp_allocatorEv", scope: !1412, file: !838, line: 237, type: !1599, scopeLine: 237, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1599 = !DISubroutineType(types: !1600)
!1600 = !{!1601, !1602}
!1601 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1418, size: 64)
!1602 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1412, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1603 = !DISubprogram(name: "_M_get_Tp_allocator", linkageName: "_ZNKSt12_Vector_baseISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE19_M_get_Tp_allocatorEv", scope: !1412, file: !838, line: 241, type: !1604, scopeLine: 241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1604 = !DISubroutineType(types: !1605)
!1605 = !{!1588, !1606}
!1606 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1607, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1607 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1412)
!1608 = !DISubprogram(name: "get_allocator", linkageName: "_ZNKSt12_Vector_baseISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE13get_allocatorEv", scope: !1412, file: !838, line: 245, type: !1609, scopeLine: 245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1609 = !DISubroutineType(types: !1610)
!1610 = !{!1611, !1606}
!1611 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !1412, file: !838, line: 234, baseType: !1495)
!1612 = !DISubprogram(name: "_Vector_base", scope: !1412, file: !838, line: 248, type: !1613, scopeLine: 248, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1613 = !DISubroutineType(types: !1614)
!1614 = !{null, !1602}
!1615 = !DISubprogram(name: "_Vector_base", scope: !1412, file: !838, line: 251, type: !1616, scopeLine: 251, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1616 = !DISubroutineType(types: !1617)
!1617 = !{null, !1602, !1618}
!1618 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1619, size: 64)
!1619 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1611)
!1620 = !DISubprogram(name: "_Vector_base", scope: !1412, file: !838, line: 254, type: !1621, scopeLine: 254, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1621 = !DISubroutineType(types: !1622)
!1622 = !{null, !1602, !905}
!1623 = !DISubprogram(name: "_Vector_base", scope: !1412, file: !838, line: 258, type: !1624, scopeLine: 258, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1624 = !DISubroutineType(types: !1625)
!1625 = !{null, !1602, !905, !1618}
!1626 = !DISubprogram(name: "_Vector_base", scope: !1412, file: !838, line: 263, type: !1627, scopeLine: 263, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1627 = !DISubroutineType(types: !1628)
!1628 = !{null, !1602, !1593}
!1629 = !DISubprogram(name: "_Vector_base", scope: !1412, file: !838, line: 266, type: !1630, scopeLine: 266, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1630 = !DISubroutineType(types: !1631)
!1631 = !{null, !1602, !1632}
!1632 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1412, size: 64)
!1633 = !DISubprogram(name: "_Vector_base", scope: !1412, file: !838, line: 270, type: !1634, scopeLine: 270, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1634 = !DISubroutineType(types: !1635)
!1635 = !{null, !1602, !1632, !1618}
!1636 = !DISubprogram(name: "~_Vector_base", scope: !1412, file: !838, line: 283, type: !1613, scopeLine: 283, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1637 = !DISubprogram(name: "_M_allocate", linkageName: "_ZNSt12_Vector_baseISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE11_M_allocateEm", scope: !1412, file: !838, line: 293, type: !1638, scopeLine: 293, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1638 = !DISubroutineType(types: !1639)
!1639 = !{!1577, !1602, !905}
!1640 = !DISubprogram(name: "_M_deallocate", linkageName: "_ZNSt12_Vector_baseISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE13_M_deallocateEPS4_m", scope: !1412, file: !838, line: 300, type: !1641, scopeLine: 300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1641 = !DISubroutineType(types: !1642)
!1642 = !{null, !1602, !1577, !905}
!1643 = !DISubprogram(name: "_M_create_storage", linkageName: "_ZNSt12_Vector_baseISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE17_M_create_storageEm", scope: !1412, file: !838, line: 309, type: !1621, scopeLine: 309, flags: DIFlagPrivate | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1644 = !{!1533, !1560}
!1645 = !DISubprogram(name: "vector", scope: !1409, file: !838, line: 391, type: !1646, scopeLine: 391, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1646 = !DISubroutineType(types: !1647)
!1647 = !{null, !1648}
!1648 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1409, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1649 = !DISubprogram(name: "vector", scope: !1409, file: !838, line: 402, type: !1650, scopeLine: 402, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1650 = !DISubroutineType(types: !1651)
!1651 = !{null, !1648, !1652}
!1652 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1653, size: 64)
!1653 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1654)
!1654 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !1409, file: !838, line: 376, baseType: !1495)
!1655 = !DISubprogram(name: "vector", scope: !1409, file: !838, line: 415, type: !1656, scopeLine: 415, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1656 = !DISubroutineType(types: !1657)
!1657 = !{null, !1648, !1044, !1652}
!1658 = !DISubprogram(name: "vector", scope: !1409, file: !838, line: 427, type: !1659, scopeLine: 427, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1659 = !DISubroutineType(types: !1660)
!1660 = !{null, !1648, !1044, !1661, !1652}
!1661 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1662, size: 64)
!1662 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1663)
!1663 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1409, file: !838, line: 364, baseType: !1431)
!1664 = !DISubprogram(name: "vector", scope: !1409, file: !838, line: 458, type: !1665, scopeLine: 458, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1665 = !DISubroutineType(types: !1666)
!1666 = !{null, !1648, !1667}
!1667 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1668, size: 64)
!1668 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1409)
!1669 = !DISubprogram(name: "vector", scope: !1409, file: !838, line: 476, type: !1670, scopeLine: 476, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1670 = !DISubroutineType(types: !1671)
!1671 = !{null, !1648, !1672}
!1672 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1409, size: 64)
!1673 = !DISubprogram(name: "vector", scope: !1409, file: !838, line: 480, type: !1674, scopeLine: 480, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1674 = !DISubroutineType(types: !1675)
!1675 = !{null, !1648, !1667, !1652}
!1676 = !DISubprogram(name: "vector", scope: !1409, file: !838, line: 490, type: !1677, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1677 = !DISubroutineType(types: !1678)
!1678 = !{null, !1648, !1672, !1652}
!1679 = !DISubprogram(name: "vector", scope: !1409, file: !838, line: 515, type: !1680, scopeLine: 515, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1680 = !DISubroutineType(types: !1681)
!1681 = !{null, !1648, !1682, !1652}
!1682 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<std::pair<llvm::MachineBasicBlock *, unsigned int> >", scope: !839, file: !1070, line: 47, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listISt4pairIPN4llvm17MachineBasicBlockEjEE")
!1683 = !DISubprogram(name: "~vector", scope: !1409, file: !838, line: 565, type: !1646, scopeLine: 565, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1684 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EEaSERKS6_", scope: !1409, file: !838, line: 582, type: !1685, scopeLine: 582, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1685 = !DISubroutineType(types: !1686)
!1686 = !{!1687, !1648, !1667}
!1687 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1409, size: 64)
!1688 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EEaSEOS6_", scope: !1409, file: !838, line: 596, type: !1689, scopeLine: 596, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1689 = !DISubroutineType(types: !1690)
!1690 = !{!1687, !1648, !1672}
!1691 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EEaSESt16initializer_listIS4_E", scope: !1409, file: !838, line: 617, type: !1692, scopeLine: 617, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1692 = !DISubroutineType(types: !1693)
!1693 = !{!1687, !1648, !1682}
!1694 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE6assignEmRKS4_", scope: !1409, file: !838, line: 636, type: !1695, scopeLine: 636, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1695 = !DISubroutineType(types: !1696)
!1696 = !{null, !1648, !1044, !1661}
!1697 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE6assignESt16initializer_listIS4_E", scope: !1409, file: !838, line: 681, type: !1698, scopeLine: 681, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1698 = !DISubroutineType(types: !1699)
!1699 = !{null, !1648, !1682}
!1700 = !DISubprogram(name: "begin", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE5beginEv", scope: !1409, file: !838, line: 698, type: !1701, scopeLine: 698, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1701 = !DISubroutineType(types: !1702)
!1702 = !{!1703, !1648}
!1703 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1409, file: !838, line: 369, baseType: !1704)
!1704 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<std::pair<llvm::MachineBasicBlock *, unsigned int> *, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > > >", scope: !5, file: !1093, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1705, templateParams: !1756, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEE")
!1705 = !{!1706, !1707, !1711, !1716, !1726, !1731, !1735, !1738, !1739, !1740, !1745, !1748, !1751, !1752, !1753}
!1706 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !1704, file: !1093, line: 767, baseType: !1430, size: 64, flags: DIFlagProtected)
!1707 = !DISubprogram(name: "__normal_iterator", scope: !1704, file: !1093, line: 779, type: !1708, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1708 = !DISubroutineType(types: !1709)
!1709 = !{null, !1710}
!1710 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1704, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1711 = !DISubprogram(name: "__normal_iterator", scope: !1704, file: !1093, line: 783, type: !1712, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1712 = !DISubroutineType(types: !1713)
!1713 = !{null, !1710, !1714}
!1714 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1715, size: 64)
!1715 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1430)
!1716 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEdeEv", scope: !1704, file: !1093, line: 796, type: !1717, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1717 = !DISubroutineType(types: !1718)
!1718 = !{!1719, !1724}
!1719 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1704, file: !1093, line: 776, baseType: !1720)
!1720 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1721, file: !1110, line: 184, baseType: !1468)
!1721 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<std::pair<llvm::MachineBasicBlock *, unsigned int> *>", scope: !839, file: !1110, line: 178, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !1722, identifier: "_ZTSSt15iterator_traitsIPSt4pairIPN4llvm17MachineBasicBlockEjEE")
!1722 = !{!1723}
!1723 = !DITemplateTypeParameter(name: "_Iterator", type: !1430)
!1724 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1725, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1725 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1704)
!1726 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEptEv", scope: !1704, file: !1093, line: 800, type: !1727, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1727 = !DISubroutineType(types: !1728)
!1728 = !{!1729, !1724}
!1729 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1704, file: !1093, line: 777, baseType: !1730)
!1730 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1721, file: !1110, line: 183, baseType: !1430)
!1731 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEppEv", scope: !1704, file: !1093, line: 804, type: !1732, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1732 = !DISubroutineType(types: !1733)
!1733 = !{!1734, !1710}
!1734 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1704, size: 64)
!1735 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEppEi", scope: !1704, file: !1093, line: 811, type: !1736, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1736 = !DISubroutineType(types: !1737)
!1737 = !{!1704, !1710, !32}
!1738 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEmmEv", scope: !1704, file: !1093, line: 816, type: !1732, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1739 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEmmEi", scope: !1704, file: !1093, line: 823, type: !1736, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1740 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEixEl", scope: !1704, file: !1093, line: 828, type: !1741, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1741 = !DISubroutineType(types: !1742)
!1742 = !{!1719, !1724, !1743}
!1743 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1704, file: !1093, line: 775, baseType: !1744)
!1744 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1721, file: !1110, line: 182, baseType: !1135)
!1745 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEpLEl", scope: !1704, file: !1093, line: 832, type: !1746, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1746 = !DISubroutineType(types: !1747)
!1747 = !{!1734, !1710, !1743}
!1748 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEplEl", scope: !1704, file: !1093, line: 836, type: !1749, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1749 = !DISubroutineType(types: !1750)
!1750 = !{!1704, !1724, !1743}
!1751 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEmIEl", scope: !1704, file: !1093, line: 840, type: !1746, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1752 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEmiEl", scope: !1704, file: !1093, line: 844, type: !1749, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1753 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEE4baseEv", scope: !1704, file: !1093, line: 848, type: !1754, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1754 = !DISubroutineType(types: !1755)
!1755 = !{!1714, !1724}
!1756 = !{!1723, !1757}
!1757 = !DITemplateTypeParameter(name: "_Container", type: !1409)
!1758 = !DISubprogram(name: "begin", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE5beginEv", scope: !1409, file: !838, line: 707, type: !1759, scopeLine: 707, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1759 = !DISubroutineType(types: !1760)
!1760 = !{!1761, !1815}
!1761 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !1409, file: !838, line: 371, baseType: !1762)
!1762 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<const std::pair<llvm::MachineBasicBlock *, unsigned int> *, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > > >", scope: !5, file: !1093, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1763, templateParams: !1814, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEE")
!1763 = !{!1764, !1765, !1769, !1774, !1784, !1789, !1793, !1796, !1797, !1798, !1803, !1806, !1809, !1810, !1811}
!1764 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !1762, file: !1093, line: 767, baseType: !1521, size: 64, flags: DIFlagProtected)
!1765 = !DISubprogram(name: "__normal_iterator", scope: !1762, file: !1093, line: 779, type: !1766, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1766 = !DISubroutineType(types: !1767)
!1767 = !{null, !1768}
!1768 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1762, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1769 = !DISubprogram(name: "__normal_iterator", scope: !1762, file: !1093, line: 783, type: !1770, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1770 = !DISubroutineType(types: !1771)
!1771 = !{null, !1768, !1772}
!1772 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1773, size: 64)
!1773 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1521)
!1774 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEdeEv", scope: !1762, file: !1093, line: 796, type: !1775, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1775 = !DISubroutineType(types: !1776)
!1776 = !{!1777, !1782}
!1777 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1762, file: !1093, line: 776, baseType: !1778)
!1778 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1779, file: !1110, line: 195, baseType: !1459)
!1779 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<const std::pair<llvm::MachineBasicBlock *, unsigned int> *>", scope: !839, file: !1110, line: 189, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !1780, identifier: "_ZTSSt15iterator_traitsIPKSt4pairIPN4llvm17MachineBasicBlockEjEE")
!1780 = !{!1781}
!1781 = !DITemplateTypeParameter(name: "_Iterator", type: !1521)
!1782 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1783, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1783 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1762)
!1784 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEptEv", scope: !1762, file: !1093, line: 800, type: !1785, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1785 = !DISubroutineType(types: !1786)
!1786 = !{!1787, !1782}
!1787 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1762, file: !1093, line: 777, baseType: !1788)
!1788 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1779, file: !1110, line: 194, baseType: !1521)
!1789 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEppEv", scope: !1762, file: !1093, line: 804, type: !1790, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1790 = !DISubroutineType(types: !1791)
!1791 = !{!1792, !1768}
!1792 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1762, size: 64)
!1793 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEppEi", scope: !1762, file: !1093, line: 811, type: !1794, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1794 = !DISubroutineType(types: !1795)
!1795 = !{!1762, !1768, !32}
!1796 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEmmEv", scope: !1762, file: !1093, line: 816, type: !1790, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1797 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEmmEi", scope: !1762, file: !1093, line: 823, type: !1794, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1798 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEixEl", scope: !1762, file: !1093, line: 828, type: !1799, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1799 = !DISubroutineType(types: !1800)
!1800 = !{!1777, !1782, !1801}
!1801 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1762, file: !1093, line: 775, baseType: !1802)
!1802 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1779, file: !1110, line: 193, baseType: !1135)
!1803 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEpLEl", scope: !1762, file: !1093, line: 832, type: !1804, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1804 = !DISubroutineType(types: !1805)
!1805 = !{!1792, !1768, !1801}
!1806 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEplEl", scope: !1762, file: !1093, line: 836, type: !1807, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1807 = !DISubroutineType(types: !1808)
!1808 = !{!1762, !1782, !1801}
!1809 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEmIEl", scope: !1762, file: !1093, line: 840, type: !1804, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1810 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEEmiEl", scope: !1762, file: !1093, line: 844, type: !1807, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1811 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS5_SaIS5_EEE4baseEv", scope: !1762, file: !1093, line: 848, type: !1812, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1812 = !DISubroutineType(types: !1813)
!1813 = !{!1772, !1782}
!1814 = !{!1781, !1757}
!1815 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1668, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1816 = !DISubprogram(name: "end", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE3endEv", scope: !1409, file: !838, line: 716, type: !1701, scopeLine: 716, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1817 = !DISubprogram(name: "end", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE3endEv", scope: !1409, file: !838, line: 725, type: !1759, scopeLine: 725, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1818 = !DISubprogram(name: "rbegin", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE6rbeginEv", scope: !1409, file: !838, line: 734, type: !1819, scopeLine: 734, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1819 = !DISubroutineType(types: !1820)
!1820 = !{!1821, !1648}
!1821 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !1409, file: !838, line: 373, baseType: !1822)
!1822 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<std::pair<llvm::MachineBasicBlock *, unsigned int> *, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > > > >", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS6_SaIS6_EEEEE")
!1823 = !DISubprogram(name: "rbegin", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE6rbeginEv", scope: !1409, file: !838, line: 743, type: !1824, scopeLine: 743, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1824 = !DISubroutineType(types: !1825)
!1825 = !{!1826, !1815}
!1826 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !1409, file: !838, line: 372, baseType: !1827)
!1827 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<const std::pair<llvm::MachineBasicBlock *, unsigned int> *, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > > > >", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN4llvm17MachineBasicBlockEjESt6vectorIS6_SaIS6_EEEEE")
!1828 = !DISubprogram(name: "rend", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE4rendEv", scope: !1409, file: !838, line: 752, type: !1819, scopeLine: 752, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1829 = !DISubprogram(name: "rend", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE4rendEv", scope: !1409, file: !838, line: 761, type: !1824, scopeLine: 761, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1830 = !DISubprogram(name: "cbegin", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE6cbeginEv", scope: !1409, file: !838, line: 771, type: !1759, scopeLine: 771, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1831 = !DISubprogram(name: "cend", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE4cendEv", scope: !1409, file: !838, line: 780, type: !1759, scopeLine: 780, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1832 = !DISubprogram(name: "crbegin", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE7crbeginEv", scope: !1409, file: !838, line: 789, type: !1824, scopeLine: 789, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1833 = !DISubprogram(name: "crend", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE5crendEv", scope: !1409, file: !838, line: 798, type: !1824, scopeLine: 798, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1834 = !DISubprogram(name: "size", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE4sizeEv", scope: !1409, file: !838, line: 805, type: !1835, scopeLine: 805, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1835 = !DISubroutineType(types: !1836)
!1836 = !{!1044, !1815}
!1837 = !DISubprogram(name: "max_size", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE8max_sizeEv", scope: !1409, file: !838, line: 810, type: !1835, scopeLine: 810, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1838 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE6resizeEm", scope: !1409, file: !838, line: 824, type: !1839, scopeLine: 824, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1839 = !DISubroutineType(types: !1840)
!1840 = !{null, !1648, !1044}
!1841 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE6resizeEmRKS4_", scope: !1409, file: !838, line: 844, type: !1695, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1842 = !DISubprogram(name: "shrink_to_fit", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE13shrink_to_fitEv", scope: !1409, file: !838, line: 876, type: !1646, scopeLine: 876, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1843 = !DISubprogram(name: "capacity", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE8capacityEv", scope: !1409, file: !838, line: 885, type: !1835, scopeLine: 885, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1844 = !DISubprogram(name: "empty", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE5emptyEv", scope: !1409, file: !838, line: 894, type: !1845, scopeLine: 894, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1845 = !DISubroutineType(types: !1846)
!1846 = !{!145, !1815}
!1847 = !DISubprogram(name: "reserve", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE7reserveEm", scope: !1409, file: !838, line: 915, type: !1839, scopeLine: 915, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1848 = !DISubprogram(name: "operator[]", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EEixEm", scope: !1409, file: !838, line: 930, type: !1849, scopeLine: 930, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1849 = !DISubroutineType(types: !1850)
!1850 = !{!1851, !1648, !1044}
!1851 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1409, file: !838, line: 367, baseType: !1852)
!1852 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1421, file: !850, line: 64, baseType: !1853)
!1853 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1854, size: 64)
!1854 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1421, file: !850, line: 58, baseType: !1855)
!1855 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1424, file: !856, line: 389, baseType: !1431)
!1856 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EEixEm", scope: !1409, file: !838, line: 948, type: !1857, scopeLine: 948, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1857 = !DISubroutineType(types: !1858)
!1858 = !{!1859, !1815, !1044}
!1859 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1409, file: !838, line: 368, baseType: !1860)
!1860 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1421, file: !850, line: 65, baseType: !1861)
!1861 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1862, size: 64)
!1862 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1854)
!1863 = !DISubprogram(name: "_M_range_check", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE14_M_range_checkEm", scope: !1409, file: !838, line: 957, type: !1864, scopeLine: 957, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1864 = !DISubroutineType(types: !1865)
!1865 = !{null, !1815, !1044}
!1866 = !DISubprogram(name: "at", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE2atEm", scope: !1409, file: !838, line: 979, type: !1849, scopeLine: 979, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1867 = !DISubprogram(name: "at", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE2atEm", scope: !1409, file: !838, line: 997, type: !1857, scopeLine: 997, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1868 = !DISubprogram(name: "front", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE5frontEv", scope: !1409, file: !838, line: 1008, type: !1869, scopeLine: 1008, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1869 = !DISubroutineType(types: !1870)
!1870 = !{!1851, !1648}
!1871 = !DISubprogram(name: "front", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE5frontEv", scope: !1409, file: !838, line: 1019, type: !1872, scopeLine: 1019, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1872 = !DISubroutineType(types: !1873)
!1873 = !{!1859, !1815}
!1874 = !DISubprogram(name: "back", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE4backEv", scope: !1409, file: !838, line: 1030, type: !1869, scopeLine: 1030, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1875 = !DISubprogram(name: "back", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE4backEv", scope: !1409, file: !838, line: 1041, type: !1872, scopeLine: 1041, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1876 = !DISubprogram(name: "data", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE4dataEv", scope: !1409, file: !838, line: 1055, type: !1877, scopeLine: 1055, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1877 = !DISubroutineType(types: !1878)
!1878 = !{!1430, !1648}
!1879 = !DISubprogram(name: "data", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE4dataEv", scope: !1409, file: !838, line: 1059, type: !1880, scopeLine: 1059, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1880 = !DISubroutineType(types: !1881)
!1881 = !{!1521, !1815}
!1882 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE9push_backERKS4_", scope: !1409, file: !838, line: 1074, type: !1883, scopeLine: 1074, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1883 = !DISubroutineType(types: !1884)
!1884 = !{null, !1648, !1661}
!1885 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE9push_backEOS4_", scope: !1409, file: !838, line: 1090, type: !1886, scopeLine: 1090, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1886 = !DISubroutineType(types: !1887)
!1887 = !{null, !1648, !1888}
!1888 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1663, size: 64)
!1889 = !DISubprogram(name: "pop_back", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE8pop_backEv", scope: !1409, file: !838, line: 1112, type: !1646, scopeLine: 1112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1890 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EERS9_", scope: !1409, file: !838, line: 1150, type: !1891, scopeLine: 1150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1891 = !DISubroutineType(types: !1892)
!1892 = !{!1703, !1648, !1761, !1661}
!1893 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EEOS4_", scope: !1409, file: !838, line: 1180, type: !1894, scopeLine: 1180, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1894 = !DISubroutineType(types: !1895)
!1895 = !{!1703, !1648, !1761, !1888}
!1896 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EESt16initializer_listIS4_E", scope: !1409, file: !838, line: 1197, type: !1897, scopeLine: 1197, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1897 = !DISubroutineType(types: !1898)
!1898 = !{!1703, !1648, !1761, !1682}
!1899 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EEmRS9_", scope: !1409, file: !838, line: 1222, type: !1900, scopeLine: 1222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1900 = !DISubroutineType(types: !1901)
!1901 = !{!1703, !1648, !1761, !1044, !1661}
!1902 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE5eraseEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EE", scope: !1409, file: !838, line: 1317, type: !1903, scopeLine: 1317, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1903 = !DISubroutineType(types: !1904)
!1904 = !{!1703, !1648, !1761}
!1905 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE5eraseEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EESB_", scope: !1409, file: !838, line: 1344, type: !1906, scopeLine: 1344, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1906 = !DISubroutineType(types: !1907)
!1907 = !{!1703, !1648, !1761, !1761}
!1908 = !DISubprogram(name: "swap", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE4swapERS6_", scope: !1409, file: !838, line: 1367, type: !1909, scopeLine: 1367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1909 = !DISubroutineType(types: !1910)
!1910 = !{null, !1648, !1687}
!1911 = !DISubprogram(name: "clear", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE5clearEv", scope: !1409, file: !838, line: 1385, type: !1646, scopeLine: 1385, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1912 = !DISubprogram(name: "_M_fill_initialize", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE18_M_fill_initializeEmRKS4_", scope: !1409, file: !838, line: 1477, type: !1695, scopeLine: 1477, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1913 = !DISubprogram(name: "_M_default_initialize", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE21_M_default_initializeEm", scope: !1409, file: !838, line: 1487, type: !1839, scopeLine: 1487, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1914 = !DISubprogram(name: "_M_fill_assign", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE14_M_fill_assignEmRKS4_", scope: !1409, file: !838, line: 1529, type: !1695, scopeLine: 1529, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1915 = !DISubprogram(name: "_M_fill_insert", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS4_S6_EEmRKS4_", scope: !1409, file: !838, line: 1568, type: !1916, scopeLine: 1568, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1916 = !DISubroutineType(types: !1917)
!1917 = !{null, !1648, !1703, !1044, !1661}
!1918 = !DISubprogram(name: "_M_default_append", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE17_M_default_appendEm", scope: !1409, file: !838, line: 1573, type: !1839, scopeLine: 1573, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1919 = !DISubprogram(name: "_M_shrink_to_fit", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE16_M_shrink_to_fitEv", scope: !1409, file: !838, line: 1576, type: !1920, scopeLine: 1576, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1920 = !DISubroutineType(types: !1921)
!1921 = !{!145, !1648}
!1922 = !DISubprogram(name: "_M_insert_rval", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE14_M_insert_rvalEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EEOS4_", scope: !1409, file: !838, line: 1625, type: !1894, scopeLine: 1625, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1923 = !DISubprogram(name: "_M_emplace_aux", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE14_M_emplace_auxEN9__gnu_cxx17__normal_iteratorIPKS4_S6_EEOS4_", scope: !1409, file: !838, line: 1634, type: !1894, scopeLine: 1634, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1924 = !DISubprogram(name: "_M_check_len", linkageName: "_ZNKSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE12_M_check_lenEmPKc", scope: !1409, file: !838, line: 1640, type: !1925, scopeLine: 1640, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1925 = !DISubroutineType(types: !1926)
!1926 = !{!1927, !1815, !1044, !317}
!1927 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1409, file: !838, line: 374, baseType: !905)
!1928 = !DISubprogram(name: "_M_erase_at_end", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE15_M_erase_at_endEPS4_", scope: !1409, file: !838, line: 1654, type: !1929, scopeLine: 1654, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1929 = !DISubroutineType(types: !1930)
!1930 = !{null, !1648, !1931}
!1931 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1409, file: !838, line: 365, baseType: !1577)
!1932 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE8_M_eraseEN9__gnu_cxx17__normal_iteratorIPS4_S6_EE", scope: !1409, file: !838, line: 1666, type: !1933, scopeLine: 1666, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1933 = !DISubroutineType(types: !1934)
!1934 = !{!1703, !1648, !1703}
!1935 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE8_M_eraseEN9__gnu_cxx17__normal_iteratorIPS4_S6_EESA_", scope: !1409, file: !838, line: 1669, type: !1936, scopeLine: 1669, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1936 = !DISubroutineType(types: !1937)
!1937 = !{!1703, !1648, !1703, !1703}
!1938 = !DISubprogram(name: "_M_move_assign", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE14_M_move_assignEOS6_St17integral_constantIbLb1EE", scope: !1409, file: !838, line: 1677, type: !1939, scopeLine: 1677, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1939 = !DISubroutineType(types: !1940)
!1940 = !{null, !1648, !1672, !1280}
!1941 = !DISubprogram(name: "_M_move_assign", linkageName: "_ZNSt6vectorISt4pairIPN4llvm17MachineBasicBlockEjESaIS4_EE14_M_move_assignEOS6_St17integral_constantIbLb0EE", scope: !1409, file: !838, line: 1688, type: !1942, scopeLine: 1688, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1942 = !DISubroutineType(types: !1943)
!1943 = !{null, !1648, !1672, !1298}
!1944 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !1386, file: !1387, line: 214, baseType: !6, size: 32)
!1945 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !1386, file: !1387, line: 215, baseType: !1409, size: 192, offset: 64)
!1946 = !DISubprogram(name: "pair", scope: !1386, file: !1387, line: 303, type: !1947, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1947 = !DISubroutineType(types: !1948)
!1948 = !{null, !1949, !1950}
!1949 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1386, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1950 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1385, size: 64)
!1951 = !DISubprogram(name: "pair", scope: !1386, file: !1387, line: 304, type: !1952, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1952 = !DISubroutineType(types: !1953)
!1953 = !{null, !1949, !1954}
!1954 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1386, size: 64)
!1955 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIjSt6vectorIS_IPN4llvm17MachineBasicBlockEjESaIS4_EEEaSERKS7_", scope: !1386, file: !1387, line: 378, type: !1956, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1956 = !DISubroutineType(types: !1957)
!1957 = !{!1958, !1949, !1959}
!1958 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1386, size: 64)
!1959 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1960, file: !1281, line: 1928, baseType: !1950)
!1960 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > > > &, const std::__nonesuch_no_braces &>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !1961, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIjSt6vectorIS0_IPN4llvm17MachineBasicBlockEjESaIS5_EEERKSt20__nonesuch_no_bracesE")
!1961 = !{!1472, !1962, !1474}
!1962 = !DITemplateTypeParameter(name: "_Iftrue", type: !1950)
!1963 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIjSt6vectorIS_IPN4llvm17MachineBasicBlockEjESaIS4_EEEaSEOS7_", scope: !1386, file: !1387, line: 389, type: !1964, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1964 = !DISubroutineType(types: !1965)
!1965 = !{!1958, !1949, !1966}
!1966 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1967, file: !1281, line: 1928, baseType: !1954)
!1967 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > > > &&, std::__nonesuch_no_braces &&>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !1968, identifier: "_ZTSSt11conditionalILb1EOSt4pairIjSt6vectorIS0_IPN4llvm17MachineBasicBlockEjESaIS5_EEEOSt20__nonesuch_no_bracesE")
!1968 = !{!1472, !1969, !1485}
!1969 = !DITemplateTypeParameter(name: "_Iftrue", type: !1954)
!1970 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIjSt6vectorIS_IPN4llvm17MachineBasicBlockEjESaIS4_EEE4swapERS7_", scope: !1386, file: !1387, line: 424, type: !1971, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1971 = !DISubroutineType(types: !1972)
!1972 = !{null, !1949, !1958}
!1973 = !{!1974, !1975}
!1974 = !DITemplateTypeParameter(name: "_T1", type: !6)
!1975 = !DITemplateTypeParameter(name: "_T2", type: !1409)
!1976 = !DITemplateTypeParameter(name: "F", type: !1386)
!1977 = !DIDerivedType(tag: DW_TAG_member, name: "End", scope: !1373, file: !1363, line: 999, baseType: !1376, size: 64, offset: 64)
!1978 = !DISubprogram(name: "DenseMapIterator", scope: !1373, file: !1363, line: 1001, type: !1979, scopeLine: 1001, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1979 = !DISubroutineType(types: !1980)
!1980 = !{null, !1981}
!1981 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1373, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1982 = !DISubprogram(name: "DenseMapIterator", scope: !1373, file: !1363, line: 1003, type: !1983, scopeLine: 1003, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1983 = !DISubroutineType(types: !1984)
!1984 = !{null, !1981, !1376, !1376, !145}
!1985 = !DISubprogram(name: "DenseMapIterator", scope: !1373, file: !1363, line: 1011, type: !1986, scopeLine: 1011, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1986 = !DISubroutineType(types: !1987)
!1987 = !{null, !1981, !1988}
!1988 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1989, size: 64)
!1989 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1373)
!1990 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb0EEdeEv", scope: !1373, file: !1363, line: 1015, type: !1991, scopeLine: 1015, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1991 = !DISubroutineType(types: !1992)
!1992 = !{!1993, !1995}
!1993 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1373, file: !1363, line: 996, baseType: !1994)
!1994 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1378, size: 64)
!1995 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1989, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1996 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb0EEptEv", scope: !1373, file: !1363, line: 1018, type: !1997, scopeLine: 1018, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1997 = !DISubroutineType(types: !1998)
!1998 = !{!1376, !1995}
!1999 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb0EEeqERKNS0_IjS7_S9_Lb1EEE", scope: !1373, file: !1363, line: 1022, type: !2000, scopeLine: 1022, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2000 = !DISubroutineType(types: !2001)
!2001 = !{!145, !1995, !2002}
!2002 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2003, size: 64)
!2003 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2004)
!2004 = !DIDerivedType(tag: DW_TAG_typedef, name: "ConstIterator", scope: !1373, file: !1363, line: 990, baseType: !2005)
!2005 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapIterator<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > >, llvm::DenseMapInfo<unsigned int>, true>", scope: !14, file: !1363, line: 987, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2006, templateParams: !2051, identifier: "_ZTSN4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb1EEE")
!2006 = !{!2007, !2015, !2016, !2020, !2023, !2026, !2033, !2036, !2042, !2043, !2047, !2050}
!2007 = !DIDerivedType(tag: DW_TAG_member, name: "Ptr", scope: !2005, file: !1363, line: 999, baseType: !2008, size: 64)
!2008 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2005, file: !1363, line: 995, baseType: !2009)
!2009 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2010, size: 64)
!2010 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !2005, file: !1363, line: 994, baseType: !2011)
!2011 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2012, file: !1380, line: 233, baseType: !1385)
!2012 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > > >, std::pair<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > > > >", scope: !14, file: !1380, line: 233, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !2013, identifier: "_ZTSN4llvm11conditionalILb1EKSt4pairIjSt6vectorIS1_IPNS_17MachineBasicBlockEjESaIS5_EEES8_EE")
!2013 = !{!2014, !1384, !1976}
!2014 = !DITemplateValueParameter(type: !145, value: i8 1)
!2015 = !DIDerivedType(tag: DW_TAG_member, name: "End", scope: !2005, file: !1363, line: 999, baseType: !2008, size: 64, offset: 64)
!2016 = !DISubprogram(name: "DenseMapIterator", scope: !2005, file: !1363, line: 1001, type: !2017, scopeLine: 1001, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2017 = !DISubroutineType(types: !2018)
!2018 = !{null, !2019}
!2019 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2005, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2020 = !DISubprogram(name: "DenseMapIterator", scope: !2005, file: !1363, line: 1003, type: !2021, scopeLine: 1003, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2021 = !DISubroutineType(types: !2022)
!2022 = !{null, !2019, !2008, !2008, !145}
!2023 = !DISubprogram(name: "DenseMapIterator", scope: !2005, file: !1363, line: 1011, type: !2024, scopeLine: 1011, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2024 = !DISubroutineType(types: !2025)
!2025 = !{null, !2019, !1988}
!2026 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb1EEdeEv", scope: !2005, file: !1363, line: 1015, type: !2027, scopeLine: 1015, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2027 = !DISubroutineType(types: !2028)
!2028 = !{!2029, !2031}
!2029 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2005, file: !1363, line: 996, baseType: !2030)
!2030 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2010, size: 64)
!2031 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2032, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2032 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2005)
!2033 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb1EEptEv", scope: !2005, file: !1363, line: 1018, type: !2034, scopeLine: 1018, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2034 = !DISubroutineType(types: !2035)
!2035 = !{!2008, !2031}
!2036 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb1EEeqERKSA_", scope: !2005, file: !1363, line: 1022, type: !2037, scopeLine: 1022, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2037 = !DISubroutineType(types: !2038)
!2038 = !{!145, !2031, !2039}
!2039 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2040, size: 64)
!2040 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2041)
!2041 = !DIDerivedType(tag: DW_TAG_typedef, name: "ConstIterator", scope: !2005, file: !1363, line: 990, baseType: !2005)
!2042 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb1EEneERKSA_", scope: !2005, file: !1363, line: 1025, type: !2037, scopeLine: 1025, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2043 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb1EEppEv", scope: !2005, file: !1363, line: 1029, type: !2044, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2044 = !DISubroutineType(types: !2045)
!2045 = !{!2046, !2019}
!2046 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2005, size: 64)
!2047 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb1EEppEi", scope: !2005, file: !1363, line: 1034, type: !2048, scopeLine: 1034, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2048 = !DISubroutineType(types: !2049)
!2049 = !{!2005, !2019, !32}
!2050 = !DISubprogram(name: "AdvancePastEmptyBuckets", linkageName: "_ZN4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb1EE23AdvancePastEmptyBucketsEv", scope: !2005, file: !1363, line: 1039, type: !2017, scopeLine: 1039, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2051 = !{!2052, !2053, !2054, !2072}
!2052 = !DITemplateTypeParameter(name: "KeyT", type: !6)
!2053 = !DITemplateTypeParameter(name: "ValueT", type: !1409)
!2054 = !DITemplateTypeParameter(name: "KeyInfoT", type: !2055)
!2055 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "DenseMapInfo<unsigned int>", scope: !14, file: !2056, line: 61, size: 8, flags: DIFlagTypePassByValue, elements: !2057, templateParams: !2070, identifier: "_ZTSN4llvm12DenseMapInfoIjEE")
!2056 = !DIFile(filename: "llvm34/include/llvm/ADT/DenseMapInfo.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "1e7505cc8cacf4830514e4c206b176d8")
!2057 = !{!2058, !2061, !2062, !2067}
!2058 = !DISubprogram(name: "getEmptyKey", linkageName: "_ZN4llvm12DenseMapInfoIjE11getEmptyKeyEv", scope: !2055, file: !2056, line: 62, type: !2059, scopeLine: 62, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2059 = !DISubroutineType(types: !2060)
!2060 = !{!6}
!2061 = !DISubprogram(name: "getTombstoneKey", linkageName: "_ZN4llvm12DenseMapInfoIjE15getTombstoneKeyEv", scope: !2055, file: !2056, line: 63, type: !2059, scopeLine: 63, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2062 = !DISubprogram(name: "getHashValue", linkageName: "_ZN4llvm12DenseMapInfoIjE12getHashValueERKj", scope: !2055, file: !2056, line: 64, type: !2063, scopeLine: 64, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2063 = !DISubroutineType(types: !2064)
!2064 = !{!6, !2065}
!2065 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2066, size: 64)
!2066 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6)
!2067 = !DISubprogram(name: "isEqual", linkageName: "_ZN4llvm12DenseMapInfoIjE7isEqualERKjS3_", scope: !2055, file: !2056, line: 65, type: !2068, scopeLine: 65, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2068 = !DISubroutineType(types: !2069)
!2069 = !{!145, !2065, !2065}
!2070 = !{!2071}
!2071 = !DITemplateTypeParameter(name: "T", type: !6)
!2072 = !DITemplateValueParameter(name: "IsConst", type: !145, value: i8 1)
!2073 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb0EEneERKNS0_IjS7_S9_Lb1EEE", scope: !1373, file: !1363, line: 1025, type: !2000, scopeLine: 1025, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2074 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb0EEppEv", scope: !1373, file: !1363, line: 1029, type: !2075, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2075 = !DISubroutineType(types: !2076)
!2076 = !{!2077, !1981}
!2077 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1373, size: 64)
!2078 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb0EEppEi", scope: !1373, file: !1363, line: 1034, type: !2079, scopeLine: 1034, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2079 = !DISubroutineType(types: !2080)
!2080 = !{!1373, !1981, !32}
!2081 = !DISubprogram(name: "AdvancePastEmptyBuckets", linkageName: "_ZN4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEELb0EE23AdvancePastEmptyBucketsEv", scope: !1373, file: !1363, line: 1039, type: !1979, scopeLine: 1039, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2082 = !{!2052, !2053, !2054, !2083}
!2083 = !DITemplateValueParameter(name: "IsConst", type: !145, defaulted: true, value: i8 0)
!2084 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1367, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2085 = !DISubprogram(name: "end", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E3endEv", scope: !1367, file: !1363, line: 57, type: !1370, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2086 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E5beginEv", scope: !1367, file: !1363, line: 60, type: !2087, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2087 = !DISubroutineType(types: !2088)
!2088 = !{!2089, !2090}
!2089 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !1367, file: !1363, line: 52, baseType: !2005)
!2090 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2091, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2091 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1367)
!2092 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E3endEv", scope: !1367, file: !1363, line: 63, type: !2087, scopeLine: 63, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2093 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E5emptyEv", scope: !1367, file: !1363, line: 67, type: !2094, scopeLine: 67, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2094 = !DISubroutineType(types: !2095)
!2095 = !{!145, !2090}
!2096 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E4sizeEv", scope: !1367, file: !1363, line: 70, type: !2097, scopeLine: 70, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2097 = !DISubroutineType(types: !2098)
!2098 = !{!6, !2090}
!2099 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E6resizeEm", scope: !1367, file: !1363, line: 73, type: !2100, scopeLine: 73, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2100 = !DISubroutineType(types: !2101)
!2101 = !{null, !2084, !2102}
!2102 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", file: !2103, line: 46, baseType: !642)
!2103 = !DIFile(filename: "llvm5/build/lib/clang/15.0.3/include/stddef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "b76978376d35d5cd171876ac58ac1256")
!2104 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E5clearEv", scope: !1367, file: !1363, line: 78, type: !2105, scopeLine: 78, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2105 = !DISubroutineType(types: !2106)
!2106 = !{null, !2084}
!2107 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E5countERKj", scope: !1367, file: !1363, line: 103, type: !2108, scopeLine: 103, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2108 = !DISubroutineType(types: !2109)
!2109 = !{!145, !2090, !2065}
!2110 = !DISubprogram(name: "find", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E4findERKj", scope: !1367, file: !1363, line: 108, type: !2111, scopeLine: 108, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2111 = !DISubroutineType(types: !2112)
!2112 = !{!1372, !2084, !2065}
!2113 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E4findERKj", scope: !1367, file: !1363, line: 114, type: !2114, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2114 = !DISubroutineType(types: !2115)
!2115 = !{!2089, !2090, !2065}
!2116 = !DISubprogram(name: "lookup", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E6lookupERKj", scope: !1367, file: !1363, line: 143, type: !2117, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2117 = !DISubroutineType(types: !2118)
!2118 = !{!1409, !2090, !2065}
!2119 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E6insertERKS3_IjS8_E", scope: !1367, file: !1363, line: 153, type: !2120, scopeLine: 153, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2120 = !DISubroutineType(types: !2121)
!2121 = !{!2122, !2084, !1950}
!2122 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::DenseMapIterator<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > >, llvm::DenseMapInfo<unsigned int>, false>, bool>", scope: !839, file: !1387, line: 208, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2123, templateParams: !2174, identifier: "_ZTSSt4pairIN4llvm16DenseMapIteratorIjSt6vectorIS_IPNS0_17MachineBasicBlockEjESaIS5_EENS0_12DenseMapInfoIjEELb0EEEbE")
!2123 = !{!2124, !2144, !2145, !2146, !2152, !2156, !2164, !2171}
!2124 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2122, baseType: !2125, flags: DIFlagPrivate, extraData: i32 0)
!2125 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::DenseMapIterator<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > >, llvm::DenseMapInfo<unsigned int>, false>, bool>", scope: !839, file: !1387, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !2126, templateParams: !2141, identifier: "_ZTSSt11__pair_baseIN4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS0_17MachineBasicBlockEjESaIS6_EENS0_12DenseMapInfoIjEELb0EEEbE")
!2126 = !{!2127, !2131, !2132, !2137}
!2127 = !DISubprogram(name: "__pair_base", scope: !2125, file: !1387, line: 194, type: !2128, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2128 = !DISubroutineType(types: !2129)
!2129 = !{null, !2130}
!2130 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2125, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2131 = !DISubprogram(name: "~__pair_base", scope: !2125, file: !1387, line: 195, type: !2128, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2132 = !DISubprogram(name: "__pair_base", scope: !2125, file: !1387, line: 196, type: !2133, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2133 = !DISubroutineType(types: !2134)
!2134 = !{null, !2130, !2135}
!2135 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2136, size: 64)
!2136 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2125)
!2137 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN4llvm16DenseMapIteratorIjSt6vectorISt4pairIPNS0_17MachineBasicBlockEjESaIS6_EENS0_12DenseMapInfoIjEELb0EEEbEaSERKSC_", scope: !2125, file: !1387, line: 197, type: !2138, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2138 = !DISubroutineType(types: !2139)
!2139 = !{!2140, !2130, !2135}
!2140 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2125, size: 64)
!2141 = !{!2142, !2143}
!2142 = !DITemplateTypeParameter(name: "_U1", type: !1373)
!2143 = !DITemplateTypeParameter(name: "_U2", type: !145)
!2144 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !2122, file: !1387, line: 214, baseType: !1373, size: 128)
!2145 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !2122, file: !1387, line: 215, baseType: !145, size: 8, offset: 128)
!2146 = !DISubprogram(name: "pair", scope: !2122, file: !1387, line: 303, type: !2147, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2147 = !DISubroutineType(types: !2148)
!2148 = !{null, !2149, !2150}
!2149 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2122, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2150 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2151, size: 64)
!2151 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2122)
!2152 = !DISubprogram(name: "pair", scope: !2122, file: !1387, line: 304, type: !2153, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2153 = !DISubroutineType(types: !2154)
!2154 = !{null, !2149, !2155}
!2155 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2122, size: 64)
!2156 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm16DenseMapIteratorIjSt6vectorIS_IPNS0_17MachineBasicBlockEjESaIS5_EENS0_12DenseMapInfoIjEELb0EEEbEaSERKSB_", scope: !2122, file: !1387, line: 378, type: !2157, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2157 = !DISubroutineType(types: !2158)
!2158 = !{!2159, !2149, !2160}
!2159 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2122, size: 64)
!2160 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2161, file: !1281, line: 1928, baseType: !2150)
!2161 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::DenseMapIterator<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > >, llvm::DenseMapInfo<unsigned int>, false>, bool> &, const std::__nonesuch_no_braces &>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !2162, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN4llvm16DenseMapIteratorIjSt6vectorIS0_IPNS1_17MachineBasicBlockEjESaIS6_EENS1_12DenseMapInfoIjEELb0EEEbERKSt20__nonesuch_no_bracesE")
!2162 = !{!1472, !2163, !1474}
!2163 = !DITemplateTypeParameter(name: "_Iftrue", type: !2150)
!2164 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm16DenseMapIteratorIjSt6vectorIS_IPNS0_17MachineBasicBlockEjESaIS5_EENS0_12DenseMapInfoIjEELb0EEEbEaSEOSB_", scope: !2122, file: !1387, line: 389, type: !2165, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2165 = !DISubroutineType(types: !2166)
!2166 = !{!2159, !2149, !2167}
!2167 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2168, file: !1281, line: 1928, baseType: !2155)
!2168 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::DenseMapIterator<unsigned int, std::vector<std::pair<llvm::MachineBasicBlock *, unsigned int>, std::allocator<std::pair<llvm::MachineBasicBlock *, unsigned int> > >, llvm::DenseMapInfo<unsigned int>, false>, bool> &&, std::__nonesuch_no_braces &&>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !2169, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN4llvm16DenseMapIteratorIjSt6vectorIS0_IPNS1_17MachineBasicBlockEjESaIS6_EENS1_12DenseMapInfoIjEELb0EEEbEOSt20__nonesuch_no_bracesE")
!2169 = !{!1472, !2170, !1485}
!2170 = !DITemplateTypeParameter(name: "_Iftrue", type: !2155)
!2171 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN4llvm16DenseMapIteratorIjSt6vectorIS_IPNS0_17MachineBasicBlockEjESaIS5_EENS0_12DenseMapInfoIjEELb0EEEbE4swapERSB_", scope: !2122, file: !1387, line: 424, type: !2172, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2172 = !DISubroutineType(types: !2173)
!2173 = !{null, !2149, !2159}
!2174 = !{!2175, !2176}
!2175 = !DITemplateTypeParameter(name: "_T1", type: !1373)
!2176 = !DITemplateTypeParameter(name: "_T2", type: !145)
!2177 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E6insertEOS3_IjS8_E", scope: !1367, file: !1363, line: 168, type: !2178, scopeLine: 168, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2178 = !DISubroutineType(types: !2179)
!2179 = !{!2122, !2084, !1954}
!2180 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E5eraseERKj", scope: !1367, file: !1363, line: 190, type: !2181, scopeLine: 190, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2181 = !DISubroutineType(types: !2182)
!2182 = !{!145, !2084, !2065}
!2183 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E5eraseENS_16DenseMapIteratorIjS8_SA_Lb0EEE", scope: !1367, file: !1363, line: 201, type: !2184, scopeLine: 201, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2184 = !DISubroutineType(types: !2185)
!2185 = !{null, !2084, !1372}
!2186 = !DISubprogram(name: "FindAndConstruct", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E16FindAndConstructERKj", scope: !1367, file: !1363, line: 209, type: !2187, scopeLine: 209, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2187 = !DISubroutineType(types: !2188)
!2188 = !{!2189, !2084, !2065}
!2189 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2190, size: 64)
!2190 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1367, file: !1363, line: 48, baseType: !2191)
!2191 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !1367, file: !1363, line: 43, baseType: !1386)
!2192 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_EixERKj", scope: !1367, file: !1363, line: 217, type: !2193, scopeLine: 217, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2193 = !DISubroutineType(types: !2194)
!2194 = !{!1687, !2084, !2065}
!2195 = !DISubprogram(name: "FindAndConstruct", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E16FindAndConstructEOj", scope: !1367, file: !1363, line: 222, type: !2196, scopeLine: 222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2196 = !DISubroutineType(types: !2197)
!2197 = !{!2189, !2084, !2198}
!2198 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !6, size: 64)
!2199 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_EixEOj", scope: !1367, file: !1363, line: 230, type: !2200, scopeLine: 230, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2200 = !DISubroutineType(types: !2201)
!2201 = !{!1687, !2084, !2198}
!2202 = !DISubprogram(name: "isPointerIntoBucketsArray", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E25isPointerIntoBucketsArrayEPKv", scope: !1367, file: !1363, line: 238, type: !2203, scopeLine: 238, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2203 = !DISubroutineType(types: !2204)
!2204 = !{!145, !2090, !124}
!2205 = !DISubprogram(name: "getPointerIntoBucketsArray", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E26getPointerIntoBucketsArrayEv", scope: !1367, file: !1363, line: 245, type: !2206, scopeLine: 245, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2206 = !DISubroutineType(types: !2207)
!2207 = !{!124, !2090}
!2208 = !DISubprogram(name: "DenseMapBase", scope: !1367, file: !1363, line: 248, type: !2105, scopeLine: 248, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2209 = !DISubprogram(name: "destroyAll", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E10destroyAllEv", scope: !1367, file: !1363, line: 250, type: !2105, scopeLine: 250, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2210 = !DISubprogram(name: "initEmpty", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E9initEmptyEv", scope: !1367, file: !1363, line: 267, type: !2105, scopeLine: 267, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2211 = !DISubprogram(name: "moveFromOldBuckets", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E18moveFromOldBucketsEPS3_IjS8_ESE_", scope: !1367, file: !1363, line: 278, type: !2212, scopeLine: 278, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2212 = !DISubroutineType(types: !2213)
!2213 = !{null, !2084, !2214, !2214}
!2214 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2191, size: 64)
!2215 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E4swapERSC_", scope: !1367, file: !1363, line: 328, type: !2216, scopeLine: 328, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2216 = !DISubroutineType(types: !2217)
!2217 = !{null, !2084, !2218}
!2218 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1367, size: 64)
!2219 = !DISubprogram(name: "getHashValue", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E12getHashValueERKj", scope: !1367, file: !1363, line: 333, type: !2063, scopeLine: 333, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2220 = !DISubprogram(name: "getEmptyKey", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E11getEmptyKeyEv", scope: !1367, file: !1363, line: 340, type: !2221, scopeLine: 340, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2221 = !DISubroutineType(types: !2222)
!2222 = !{!2066}
!2223 = !DISubprogram(name: "getTombstoneKey", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E15getTombstoneKeyEv", scope: !1367, file: !1363, line: 343, type: !2221, scopeLine: 343, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2224 = !DISubprogram(name: "getNumEntries", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E13getNumEntriesEv", scope: !1367, file: !1363, line: 348, type: !2097, scopeLine: 348, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2225 = !DISubprogram(name: "setNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E13setNumEntriesEj", scope: !1367, file: !1363, line: 351, type: !2226, scopeLine: 351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2226 = !DISubroutineType(types: !2227)
!2227 = !{null, !2084, !6}
!2228 = !DISubprogram(name: "incrementNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E19incrementNumEntriesEv", scope: !1367, file: !1363, line: 354, type: !2105, scopeLine: 354, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2229 = !DISubprogram(name: "decrementNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E19decrementNumEntriesEv", scope: !1367, file: !1363, line: 357, type: !2105, scopeLine: 357, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2230 = !DISubprogram(name: "getNumTombstones", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E16getNumTombstonesEv", scope: !1367, file: !1363, line: 360, type: !2097, scopeLine: 360, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2231 = !DISubprogram(name: "setNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E16setNumTombstonesEj", scope: !1367, file: !1363, line: 363, type: !2226, scopeLine: 363, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2232 = !DISubprogram(name: "incrementNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E22incrementNumTombstonesEv", scope: !1367, file: !1363, line: 366, type: !2105, scopeLine: 366, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2233 = !DISubprogram(name: "decrementNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E22decrementNumTombstonesEv", scope: !1367, file: !1363, line: 369, type: !2105, scopeLine: 369, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2234 = !DISubprogram(name: "getBuckets", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E10getBucketsEv", scope: !1367, file: !1363, line: 372, type: !2235, scopeLine: 372, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2235 = !DISubroutineType(types: !2236)
!2236 = !{!2237, !2090}
!2237 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2238, size: 64)
!2238 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2191)
!2239 = !DISubprogram(name: "getBuckets", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E10getBucketsEv", scope: !1367, file: !1363, line: 375, type: !2240, scopeLine: 375, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2240 = !DISubroutineType(types: !2241)
!2241 = !{!2214, !2084}
!2242 = !DISubprogram(name: "getNumBuckets", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E13getNumBucketsEv", scope: !1367, file: !1363, line: 378, type: !2097, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2243 = !DISubprogram(name: "getBucketsEnd", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E13getBucketsEndEv", scope: !1367, file: !1363, line: 381, type: !2240, scopeLine: 381, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2244 = !DISubprogram(name: "getBucketsEnd", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E13getBucketsEndEv", scope: !1367, file: !1363, line: 384, type: !2235, scopeLine: 384, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2245 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E4growEj", scope: !1367, file: !1363, line: 388, type: !2226, scopeLine: 388, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2246 = !DISubprogram(name: "shrink_and_clear", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E16shrink_and_clearEv", scope: !1367, file: !1363, line: 392, type: !2105, scopeLine: 392, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2247 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E16InsertIntoBucketERKjRKS8_PS3_IjS8_E", scope: !1367, file: !1363, line: 397, type: !2248, scopeLine: 397, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2248 = !DISubroutineType(types: !2249)
!2249 = !{!2214, !2084, !2065, !1667, !2214}
!2250 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E16InsertIntoBucketERKjOS8_PS3_IjS8_E", scope: !1367, file: !1363, line: 407, type: !2251, scopeLine: 407, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2251 = !DISubroutineType(types: !2252)
!2252 = !{!2214, !2084, !2065, !1672, !2214}
!2253 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E16InsertIntoBucketEOjOS8_PS3_IjS8_E", scope: !1367, file: !1363, line: 416, type: !2254, scopeLine: 416, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2254 = !DISubroutineType(types: !2255)
!2255 = !{!2214, !2084, !2198, !1672, !2214}
!2256 = !DISubprogram(name: "InsertIntoBucketImpl", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E20InsertIntoBucketImplERKjPS3_IjS8_E", scope: !1367, file: !1363, line: 425, type: !2257, scopeLine: 425, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2257 = !DISubroutineType(types: !2258)
!2258 = !{!2214, !2084, !2065, !2214}
!2259 = !DISubprogram(name: "getMemorySize", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS6_EENS_12DenseMapInfoIjEEEEjS8_SA_E13getMemorySizeEv", scope: !1367, file: !1363, line: 527, type: !2260, scopeLine: 527, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2260 = !DISubroutineType(types: !2261)
!2261 = !{!2102, !2090}
!2262 = !{!2263, !2052, !2053, !2054}
!2263 = !DITemplateTypeParameter(name: "DerivedT", type: !1364)
!2264 = !DIDerivedType(tag: DW_TAG_member, name: "Buckets", scope: !1364, file: !1363, line: 543, baseType: !1361, size: 64)
!2265 = !DIDerivedType(tag: DW_TAG_member, name: "NumEntries", scope: !1364, file: !1363, line: 544, baseType: !6, size: 32, offset: 64)
!2266 = !DIDerivedType(tag: DW_TAG_member, name: "NumTombstones", scope: !1364, file: !1363, line: 545, baseType: !6, size: 32, offset: 96)
!2267 = !DIDerivedType(tag: DW_TAG_member, name: "NumBuckets", scope: !1364, file: !1363, line: 546, baseType: !6, size: 32, offset: 128)
!2268 = !DISubprogram(name: "DenseMap", scope: !1364, file: !1363, line: 549, type: !2269, scopeLine: 549, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2269 = !DISubroutineType(types: !2270)
!2270 = !{null, !2271, !6}
!2271 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1364, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2272 = !DISubprogram(name: "DenseMap", scope: !1364, file: !1363, line: 553, type: !2273, scopeLine: 553, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2273 = !DISubroutineType(types: !2274)
!2274 = !{null, !2271, !2275}
!2275 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2276, size: 64)
!2276 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1364)
!2277 = !DISubprogram(name: "DenseMap", scope: !1364, file: !1363, line: 559, type: !2278, scopeLine: 559, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2278 = !DISubroutineType(types: !2279)
!2279 = !{null, !2271, !2280}
!2280 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1364, size: 64)
!2281 = !DISubprogram(name: "~DenseMap", scope: !1364, file: !1363, line: 571, type: !2282, scopeLine: 571, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2282 = !DISubroutineType(types: !2283)
!2283 = !{null, !2271}
!2284 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEE4swapERSA_", scope: !1364, file: !1363, line: 576, type: !2285, scopeLine: 576, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2285 = !DISubroutineType(types: !2286)
!2286 = !{null, !2271, !2287}
!2287 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1364, size: 64)
!2288 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEEaSERKSA_", scope: !1364, file: !1363, line: 583, type: !2289, scopeLine: 583, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2289 = !DISubroutineType(types: !2290)
!2290 = !{!2287, !2271, !2275}
!2291 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEEaSEOSA_", scope: !1364, file: !1363, line: 589, type: !2292, scopeLine: 589, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2292 = !DISubroutineType(types: !2293)
!2293 = !{!2287, !2271, !2280}
!2294 = !DISubprogram(name: "copyFrom", linkageName: "_ZN4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEE8copyFromERKSA_", scope: !1364, file: !1363, line: 598, type: !2273, scopeLine: 598, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2295 = !DISubprogram(name: "init", linkageName: "_ZN4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEE4initEj", scope: !1364, file: !1363, line: 609, type: !2269, scopeLine: 609, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2296 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEE4growEj", scope: !1364, file: !1363, line: 618, type: !2269, scopeLine: 618, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2297 = !DISubprogram(name: "shrink_and_clear", linkageName: "_ZN4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEE16shrink_and_clearEv", scope: !1364, file: !1363, line: 635, type: !2282, scopeLine: 635, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2298 = !DISubprogram(name: "getNumEntries", linkageName: "_ZNK4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEE13getNumEntriesEv", scope: !1364, file: !1363, line: 653, type: !2299, scopeLine: 653, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2299 = !DISubroutineType(types: !2300)
!2300 = !{!6, !2301}
!2301 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2276, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2302 = !DISubprogram(name: "setNumEntries", linkageName: "_ZN4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEE13setNumEntriesEj", scope: !1364, file: !1363, line: 656, type: !2269, scopeLine: 656, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2303 = !DISubprogram(name: "getNumTombstones", linkageName: "_ZNK4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEE16getNumTombstonesEv", scope: !1364, file: !1363, line: 660, type: !2299, scopeLine: 660, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2304 = !DISubprogram(name: "setNumTombstones", linkageName: "_ZN4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEE16setNumTombstonesEj", scope: !1364, file: !1363, line: 663, type: !2269, scopeLine: 663, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2305 = !DISubprogram(name: "getBuckets", linkageName: "_ZNK4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEE10getBucketsEv", scope: !1364, file: !1363, line: 667, type: !2306, scopeLine: 667, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2306 = !DISubroutineType(types: !2307)
!2307 = !{!1361, !2301}
!2308 = !DISubprogram(name: "getNumBuckets", linkageName: "_ZNK4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEE13getNumBucketsEv", scope: !1364, file: !1363, line: 671, type: !2299, scopeLine: 671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2309 = !DISubprogram(name: "allocateBuckets", linkageName: "_ZN4llvm8DenseMapIjSt6vectorISt4pairIPNS_17MachineBasicBlockEjESaIS5_EENS_12DenseMapInfoIjEEE15allocateBucketsEj", scope: !1364, file: !1363, line: 675, type: !2310, scopeLine: 675, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2310 = !DISubroutineType(types: !2311)
!2311 = !{!145, !2271, !6}
!2312 = !{!2052, !2053, !2054}
!2313 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1364, size: 64)
!2314 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2276, size: 64)
!2315 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1418, size: 64)
!2316 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2318, file: !2317, line: 100, baseType: !2383)
!2317 = !DIFile(filename: "llvm34/include/llvm/ADT/SmallVector.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "69b512a6e55455ea0ed3a25fbee45d45")
!2318 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<unsigned int, void>", scope: !14, file: !2317, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2319, templateParams: !2441, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIjvEE")
!2319 = !{!2320, !2342, !2365, !2369, !2372, !2377, !2380, !2384, !2387, !2392, !2393, !2394, !2395, !2396, !2401, !2406, !2407, !2408, !2412, !2413, !2416, !2420, !2424, !2429, !2433, !2436, !2439, !2440}
!2320 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2318, baseType: !2321, flags: DIFlagPublic, extraData: i32 0)
!2321 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorBase", scope: !14, file: !2317, line: 33, size: 192, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2322, identifier: "_ZTSN4llvm15SmallVectorBaseE")
!2322 = !{!2323, !2324, !2325, !2326, !2330, !2333, !2338, !2339}
!2323 = !DIDerivedType(tag: DW_TAG_member, name: "BeginX", scope: !2321, file: !2317, line: 35, baseType: !154, size: 64, flags: DIFlagProtected)
!2324 = !DIDerivedType(tag: DW_TAG_member, name: "EndX", scope: !2321, file: !2317, line: 35, baseType: !154, size: 64, offset: 64, flags: DIFlagProtected)
!2325 = !DIDerivedType(tag: DW_TAG_member, name: "CapacityX", scope: !2321, file: !2317, line: 35, baseType: !154, size: 64, offset: 128, flags: DIFlagProtected)
!2326 = !DISubprogram(name: "SmallVectorBase", scope: !2321, file: !2317, line: 38, type: !2327, scopeLine: 38, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2327 = !DISubroutineType(types: !2328)
!2328 = !{null, !2329, !154, !2102}
!2329 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2321, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2330 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm15SmallVectorBase8grow_podEPvmm", scope: !2321, file: !2317, line: 43, type: !2331, scopeLine: 43, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2331 = !DISubroutineType(types: !2332)
!2332 = !{null, !2329, !154, !2102, !2102}
!2333 = !DISubprogram(name: "size_in_bytes", linkageName: "_ZNK4llvm15SmallVectorBase13size_in_bytesEv", scope: !2321, file: !2317, line: 47, type: !2334, scopeLine: 47, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2334 = !DISubroutineType(types: !2335)
!2335 = !{!2102, !2336}
!2336 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2337, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2337 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2321)
!2338 = !DISubprogram(name: "capacity_in_bytes", linkageName: "_ZNK4llvm15SmallVectorBase17capacity_in_bytesEv", scope: !2321, file: !2317, line: 52, type: !2334, scopeLine: 52, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2339 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm15SmallVectorBase5emptyEv", scope: !2321, file: !2317, line: 56, type: !2340, scopeLine: 56, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2340 = !DISubroutineType(types: !2341)
!2341 = !{!145, !2336}
!2342 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !2318, file: !2317, line: 74, baseType: !2343, size: 32, offset: 192)
!2343 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !2318, file: !2317, line: 73, baseType: !2344)
!2344 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<unsigned int, char, char, char, char, char, char>", scope: !14, file: !2345, line: 199, size: 32, flags: DIFlagTypePassByValue, elements: !2346, templateParams: !2357, identifier: "_ZTSN4llvm21AlignedCharArrayUnionIjccccccEE")
!2345 = !DIFile(filename: "llvm34/include/llvm/Support/AlignOf.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "55acc245b7ffca1b8660602cb703d9fb")
!2346 = !{!2347}
!2347 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2344, baseType: !2348, extraData: i32 0)
!2348 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<4UL, 4UL>", scope: !14, file: !2345, line: 75, size: 32, flags: DIFlagTypePassByValue, elements: !2349, templateParams: !2354, identifier: "_ZTSN4llvm16AlignedCharArrayILm4ELm4EEE")
!2349 = !{!2350}
!2350 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !2348, file: !2345, line: 76, baseType: !2351, size: 32, align: 32)
!2351 = !DICompositeType(tag: DW_TAG_array_type, baseType: !319, size: 32, elements: !2352)
!2352 = !{!2353}
!2353 = !DISubrange(count: 4)
!2354 = !{!2355, !2356}
!2355 = !DITemplateValueParameter(name: "Alignment", type: !642, value: i64 4)
!2356 = !DITemplateValueParameter(name: "Size", type: !642, value: i64 4)
!2357 = !{!2358, !2359, !2360, !2361, !2362, !2363, !2364}
!2358 = !DITemplateTypeParameter(name: "T1", type: !6)
!2359 = !DITemplateTypeParameter(name: "T2", type: !319, defaulted: true)
!2360 = !DITemplateTypeParameter(name: "T3", type: !319, defaulted: true)
!2361 = !DITemplateTypeParameter(name: "T4", type: !319, defaulted: true)
!2362 = !DITemplateTypeParameter(name: "T5", type: !319, defaulted: true)
!2363 = !DITemplateTypeParameter(name: "T6", type: !319, defaulted: true)
!2364 = !DITemplateTypeParameter(name: "T7", type: !319, defaulted: true)
!2365 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !2318, file: !2317, line: 78, type: !2366, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2366 = !DISubroutineType(types: !2367)
!2367 = !{null, !2368, !2102}
!2368 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2318, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2369 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE8grow_podEmm", scope: !2318, file: !2317, line: 80, type: !2370, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2370 = !DISubroutineType(types: !2371)
!2371 = !{null, !2368, !2102, !2102}
!2372 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE7isSmallEv", scope: !2318, file: !2317, line: 86, type: !2373, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2373 = !DISubroutineType(types: !2374)
!2374 = !{!145, !2375}
!2375 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2376, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2376 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2318)
!2377 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE12resetToSmallEv", scope: !2318, file: !2317, line: 91, type: !2378, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2378 = !DISubroutineType(types: !2379)
!2379 = !{null, !2368}
!2380 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE6setEndEPj", scope: !2318, file: !2317, line: 95, type: !2381, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2381 = !DISubroutineType(types: !2382)
!2382 = !{null, !2368, !2383}
!2383 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6, size: 64)
!2384 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE5beginEv", scope: !2318, file: !2317, line: 112, type: !2385, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2385 = !DISubroutineType(types: !2386)
!2386 = !{!2316, !2368}
!2387 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE5beginEv", scope: !2318, file: !2317, line: 113, type: !2388, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2388 = !DISubroutineType(types: !2389)
!2389 = !{!2390, !2375}
!2390 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !2318, file: !2317, line: 101, baseType: !2391)
!2391 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2066, size: 64)
!2392 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE3endEv", scope: !2318, file: !2317, line: 114, type: !2385, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2393 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE3endEv", scope: !2318, file: !2317, line: 115, type: !2388, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2394 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE12capacity_ptrEv", scope: !2318, file: !2317, line: 117, type: !2385, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2395 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE12capacity_ptrEv", scope: !2318, file: !2317, line: 118, type: !2388, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2396 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE6rbeginEv", scope: !2318, file: !2317, line: 122, type: !2397, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2397 = !DISubroutineType(types: !2398)
!2398 = !{!2399, !2368}
!2399 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !2318, file: !2317, line: 104, baseType: !2400)
!2400 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<unsigned int *>", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPjE")
!2401 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE6rbeginEv", scope: !2318, file: !2317, line: 123, type: !2402, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2402 = !DISubroutineType(types: !2403)
!2403 = !{!2404, !2375}
!2404 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !2318, file: !2317, line: 103, baseType: !2405)
!2405 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const unsigned int *>", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKjE")
!2406 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE4rendEv", scope: !2318, file: !2317, line: 124, type: !2397, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2407 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE4rendEv", scope: !2318, file: !2317, line: 125, type: !2402, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2408 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE4sizeEv", scope: !2318, file: !2317, line: 127, type: !2409, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2409 = !DISubroutineType(types: !2410)
!2410 = !{!2411, !2375}
!2411 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !2317, line: 97, baseType: !2102)
!2412 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE8max_sizeEv", scope: !2318, file: !2317, line: 128, type: !2409, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2413 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE8capacityEv", scope: !2318, file: !2317, line: 132, type: !2414, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2414 = !DISubroutineType(types: !2415)
!2415 = !{!2102, !2375}
!2416 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE4dataEv", scope: !2318, file: !2317, line: 135, type: !2417, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2417 = !DISubroutineType(types: !2418)
!2418 = !{!2419, !2368}
!2419 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2318, file: !2317, line: 108, baseType: !2383)
!2420 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE4dataEv", scope: !2318, file: !2317, line: 137, type: !2421, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2421 = !DISubroutineType(types: !2422)
!2422 = !{!2423, !2375}
!2423 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !2318, file: !2317, line: 109, baseType: !2391)
!2424 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvEixEj", scope: !2318, file: !2317, line: 139, type: !2425, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2425 = !DISubroutineType(types: !2426)
!2426 = !{!2427, !2368, !6}
!2427 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2318, file: !2317, line: 106, baseType: !2428)
!2428 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6, size: 64)
!2429 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvEixEj", scope: !2318, file: !2317, line: 143, type: !2430, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2430 = !DISubroutineType(types: !2431)
!2431 = !{!2432, !2375, !6}
!2432 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !2318, file: !2317, line: 107, baseType: !2065)
!2433 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE5frontEv", scope: !2318, file: !2317, line: 148, type: !2434, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2434 = !DISubroutineType(types: !2435)
!2435 = !{!2427, !2368}
!2436 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE5frontEv", scope: !2318, file: !2317, line: 152, type: !2437, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2437 = !DISubroutineType(types: !2438)
!2438 = !{!2432, !2375}
!2439 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE4backEv", scope: !2318, file: !2317, line: 157, type: !2434, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2440 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE4backEv", scope: !2318, file: !2317, line: 161, type: !2437, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2441 = !{!2071, !2442}
!2442 = !DITemplateTypeParameter(type: null, defaulted: true)
!2443 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2444, file: !2317, line: 100, baseType: !2615)
!2444 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<llvm::RegScavenger::ScavengedInfo, void>", scope: !14, file: !2317, line: 66, size: 320, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2445, templateParams: !3089, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvEE")
!2445 = !{!2446, !2447, !3015, !3019, !3022, !3027, !3030, !3033, !3036, !3041, !3042, !3043, !3044, !3045, !3050, !3055, !3056, !3057, !3060, !3061, !3064, !3068, !3072, !3077, !3081, !3084, !3087, !3088}
!2446 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2444, baseType: !2321, flags: DIFlagPublic, extraData: i32 0)
!2447 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !2444, file: !2317, line: 74, baseType: !2448, size: 128, offset: 192)
!2448 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !2444, file: !2317, line: 73, baseType: !2449)
!2449 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<llvm::RegScavenger::ScavengedInfo, char, char, char, char, char, char>", scope: !14, file: !2345, line: 199, size: 128, flags: DIFlagTypePassByValue, elements: !2450, templateParams: !2461, identifier: "_ZTSN4llvm21AlignedCharArrayUnionINS_12RegScavenger13ScavengedInfoEccccccEE")
!2450 = !{!2451}
!2451 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2449, baseType: !2452, extraData: i32 0)
!2452 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<8UL, 16UL>", scope: !14, file: !2345, line: 75, size: 128, flags: DIFlagTypePassByValue, elements: !2453, templateParams: !2458, identifier: "_ZTSN4llvm16AlignedCharArrayILm8ELm16EEE")
!2453 = !{!2454}
!2454 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !2452, file: !2345, line: 76, baseType: !2455, size: 128, align: 64)
!2455 = !DICompositeType(tag: DW_TAG_array_type, baseType: !319, size: 128, elements: !2456)
!2456 = !{!2457}
!2457 = !DISubrange(count: 16)
!2458 = !{!2459, !2460}
!2459 = !DITemplateValueParameter(name: "Alignment", type: !642, value: i64 8)
!2460 = !DITemplateValueParameter(name: "Size", type: !642, value: i64 16)
!2461 = !{!2462, !2359, !2360, !2361, !2362, !2363, !2364}
!2462 = !DITemplateTypeParameter(name: "T1", type: !2463)
!2463 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ScavengedInfo", scope: !2465, file: !2464, line: 44, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12RegScavenger13ScavengedInfoE")
!2464 = !DIFile(filename: "llvm34/include/llvm/CodeGen/RegisterScavenging.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "48689f48a548da20a4ec640a8ae0d5d0")
!2465 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "RegScavenger", scope: !14, file: !2464, line: 31, size: 1408, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2466, identifier: "_ZTSN4llvm12RegScavengerE")
!2466 = !{!2467, !2469, !2474, !2478, !2479, !2596, !2597, !2598, !2722, !2723, !2724, !2725, !2726, !2730, !2733, !2734, !2735, !2738, !2739, !2740, !2741, !2746, !2749, !2973, !2976, !2979, !2982, !2987, !2990, !2993, !2996, !2999, !3002, !3003, !3006, !3007, !3008, !3011}
!2467 = !DIDerivedType(tag: DW_TAG_member, name: "TRI", scope: !2465, file: !2464, line: 32, baseType: !2468, size: 64)
!2468 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !403, size: 64)
!2469 = !DIDerivedType(tag: DW_TAG_member, name: "TII", scope: !2465, file: !2464, line: 33, baseType: !2470, size: 64, offset: 64)
!2470 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2471, size: 64)
!2471 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2472)
!2472 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "TargetInstrInfo", scope: !14, file: !2473, line: 47, size: 384, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm15TargetInstrInfoE")
!2473 = !DIFile(filename: "llvm34/include/llvm/Target/TargetInstrInfo.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "5e341fd0e3613fa2c1d1b96514cc9dd1")
!2474 = !DIDerivedType(tag: DW_TAG_member, name: "MRI", scope: !2465, file: !2464, line: 34, baseType: !2475, size: 64, offset: 128)
!2475 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2476, size: 64)
!2476 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MachineRegisterInfo", scope: !14, file: !2477, line: 30, size: 1536, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm19MachineRegisterInfoE")
!2477 = !DIFile(filename: "llvm34/include/llvm/CodeGen/MachineRegisterInfo.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "1e95340fd6fc0ef1135608387cc79766")
!2478 = !DIDerivedType(tag: DW_TAG_member, name: "MBB", scope: !2465, file: !2464, line: 35, baseType: !197, size: 64, offset: 192)
!2479 = !DIDerivedType(tag: DW_TAG_member, name: "MBBI", scope: !2465, file: !2464, line: 36, baseType: !2480, size: 128, offset: 256)
!2480 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !198, file: !199, line: 212, baseType: !2481)
!2481 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "bundle_iterator<llvm::MachineInstr, llvm::ilist_iterator<llvm::MachineInstr> >", scope: !198, file: !199, line: 144, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2482, templateParams: !2593, identifier: "_ZTSN4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEE")
!2482 = !{!2483, !2499, !2554, !2558, !2561, !2564, !2567, !2572, !2575, !2576, !2580, !2581, !2585, !2586, !2589, !2590}
!2483 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2481, baseType: !2484, flags: DIFlagPublic, extraData: i32 0)
!2484 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::bidirectional_iterator_tag, llvm::MachineInstr, long, llvm::MachineInstr *, llvm::MachineInstr &>", scope: !839, file: !1110, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !2485, identifier: "_ZTSSt8iteratorISt26bidirectional_iterator_tagN4llvm12MachineInstrElPS2_RS2_E")
!2485 = !{!2486, !2494, !2495, !2496, !2497}
!2486 = !DITemplateTypeParameter(name: "_Category", type: !2487)
!2487 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "bidirectional_iterator_tag", scope: !839, file: !1110, line: 99, size: 8, flags: DIFlagTypePassByValue, elements: !2488, identifier: "_ZTSSt26bidirectional_iterator_tag")
!2488 = !{!2489}
!2489 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2487, baseType: !2490, extraData: i32 0)
!2490 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "forward_iterator_tag", scope: !839, file: !1110, line: 95, size: 8, flags: DIFlagTypePassByValue, elements: !2491, identifier: "_ZTSSt20forward_iterator_tag")
!2491 = !{!2492}
!2492 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2490, baseType: !2493, extraData: i32 0)
!2493 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "input_iterator_tag", scope: !839, file: !1110, line: 89, size: 8, flags: DIFlagTypePassByValue, elements: !960, identifier: "_ZTSSt18input_iterator_tag")
!2494 = !DITemplateTypeParameter(name: "_Tp", type: !269)
!2495 = !DITemplateTypeParameter(name: "_Distance", type: !288)
!2496 = !DITemplateTypeParameter(name: "_Pointer", type: !268)
!2497 = !DITemplateTypeParameter(name: "_Reference", type: !2498)
!2498 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !269, size: 64)
!2499 = !DIDerivedType(tag: DW_TAG_member, name: "MII", scope: !2481, file: !199, line: 146, baseType: !2500, size: 64, offset: 64)
!2500 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ilist_iterator<llvm::MachineInstr>", scope: !14, file: !2501, line: 145, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2502, templateParams: !2552, identifier: "_ZTSN4llvm14ilist_iteratorINS_12MachineInstrEEE")
!2501 = !DIFile(filename: "llvm34/include/llvm/ADT/ilist.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "da692daf2fc683e7a6021157e4a297cf")
!2502 = !{!2503, !2504, !2507, !2514, !2515, !2516, !2517, !2518, !2522, !2527, !2530, !2533, !2536, !2537, !2541, !2542, !2546, !2547, !2550, !2551}
!2503 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2500, baseType: !2484, flags: DIFlagPublic, extraData: i32 0)
!2504 = !DIDerivedType(tag: DW_TAG_member, name: "NodePtr", scope: !2500, file: !2501, line: 158, baseType: !2505, size: 64)
!2505 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2500, file: !2501, line: 155, baseType: !2506)
!2506 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2484, file: !1110, line: 127, baseType: !268)
!2507 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEixEl", scope: !2500, file: !2501, line: 164, type: !2508, scopeLine: 164, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2508 = !DISubroutineType(types: !2509)
!2509 = !{null, !2510, !2512}
!2510 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2511, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2511 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2500)
!2512 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !2500, file: !2501, line: 154, baseType: !2513)
!2513 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !2484, file: !1110, line: 125, baseType: !288)
!2514 = !DISubprogram(name: "operator+", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEplEl", scope: !2500, file: !2501, line: 165, type: !2508, scopeLine: 165, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2515 = !DISubprogram(name: "operator-", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEmiEl", scope: !2500, file: !2501, line: 166, type: !2508, scopeLine: 166, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2516 = !DISubprogram(name: "operator+=", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEpLEl", scope: !2500, file: !2501, line: 167, type: !2508, scopeLine: 167, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2517 = !DISubprogram(name: "operator-=", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEmIEl", scope: !2500, file: !2501, line: 168, type: !2508, scopeLine: 168, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2518 = !DISubprogram(name: "ilist_iterator", scope: !2500, file: !2501, line: 176, type: !2519, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2519 = !DISubroutineType(types: !2520)
!2520 = !{null, !2521, !2505}
!2521 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2500, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2522 = !DISubprogram(name: "ilist_iterator", scope: !2500, file: !2501, line: 177, type: !2523, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2523 = !DISubroutineType(types: !2524)
!2524 = !{null, !2521, !2525}
!2525 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2500, file: !2501, line: 156, baseType: !2526)
!2526 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2484, file: !1110, line: 129, baseType: !2498)
!2527 = !DISubprogram(name: "ilist_iterator", scope: !2500, file: !2501, line: 178, type: !2528, scopeLine: 178, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2528 = !DISubroutineType(types: !2529)
!2529 = !{null, !2521}
!2530 = !DISubprogram(name: "operator llvm::MachineInstr *", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEcvPS1_Ev", scope: !2500, file: !2501, line: 195, type: !2531, scopeLine: 195, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2531 = !DISubroutineType(types: !2532)
!2532 = !{!2505, !2510}
!2533 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEdeEv", scope: !2500, file: !2501, line: 199, type: !2534, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2534 = !DISubroutineType(types: !2535)
!2535 = !{!2525, !2510}
!2536 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEptEv", scope: !2500, file: !2501, line: 202, type: !2531, scopeLine: 202, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2537 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEeqERKS2_", scope: !2500, file: !2501, line: 205, type: !2538, scopeLine: 205, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2538 = !DISubroutineType(types: !2539)
!2539 = !{!145, !2510, !2540}
!2540 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2511, size: 64)
!2541 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEneERKS2_", scope: !2500, file: !2501, line: 208, type: !2538, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2542 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorINS_12MachineInstrEEmmEv", scope: !2500, file: !2501, line: 213, type: !2543, scopeLine: 213, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2543 = !DISubroutineType(types: !2544)
!2544 = !{!2545, !2521}
!2545 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2500, size: 64)
!2546 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorINS_12MachineInstrEEppEv", scope: !2500, file: !2501, line: 218, type: !2543, scopeLine: 218, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2547 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorINS_12MachineInstrEEmmEi", scope: !2500, file: !2501, line: 222, type: !2548, scopeLine: 222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2548 = !DISubroutineType(types: !2549)
!2549 = !{!2500, !2521, !32}
!2550 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorINS_12MachineInstrEEppEi", scope: !2500, file: !2501, line: 227, type: !2548, scopeLine: 227, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2551 = !DISubprogram(name: "getNodePtrUnchecked", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEE19getNodePtrUncheckedEv", scope: !2500, file: !2501, line: 234, type: !2531, scopeLine: 234, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2552 = !{!2553}
!2553 = !DITemplateTypeParameter(name: "NodeTy", type: !269)
!2554 = !DISubprogram(name: "bundle_iterator", scope: !2481, file: !199, line: 149, type: !2555, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2555 = !DISubroutineType(types: !2556)
!2556 = !{null, !2557, !2500}
!2557 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2481, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2558 = !DISubprogram(name: "bundle_iterator", scope: !2481, file: !199, line: 151, type: !2559, scopeLine: 151, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2559 = !DISubroutineType(types: !2560)
!2560 = !{null, !2557, !2498}
!2561 = !DISubprogram(name: "bundle_iterator", scope: !2481, file: !199, line: 155, type: !2562, scopeLine: 155, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2562 = !DISubroutineType(types: !2563)
!2563 = !{null, !2557, !268}
!2564 = !DISubprogram(name: "bundle_iterator", scope: !2481, file: !199, line: 163, type: !2565, scopeLine: 163, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2565 = !DISubroutineType(types: !2566)
!2566 = !{null, !2557}
!2567 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEdeEv", scope: !2481, file: !199, line: 165, type: !2568, scopeLine: 165, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2568 = !DISubroutineType(types: !2569)
!2569 = !{!2498, !2570}
!2570 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2571, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2571 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2481)
!2572 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEptEv", scope: !2481, file: !199, line: 166, type: !2573, scopeLine: 166, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2573 = !DISubroutineType(types: !2574)
!2574 = !{!268, !2570}
!2575 = !DISubprogram(name: "operator llvm::MachineInstr *", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEcvPS2_Ev", scope: !2481, file: !199, line: 168, type: !2573, scopeLine: 168, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2576 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEeqERKS5_", scope: !2481, file: !199, line: 170, type: !2577, scopeLine: 170, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2577 = !DISubroutineType(types: !2578)
!2578 = !{!145, !2570, !2579}
!2579 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2571, size: 64)
!2580 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEneERKS5_", scope: !2481, file: !199, line: 173, type: !2577, scopeLine: 173, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2581 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEmmEv", scope: !2481, file: !199, line: 178, type: !2582, scopeLine: 178, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2582 = !DISubroutineType(types: !2583)
!2583 = !{!2584, !2557}
!2584 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2481, size: 64)
!2585 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEppEv", scope: !2481, file: !199, line: 183, type: !2582, scopeLine: 183, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2586 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEmmEi", scope: !2481, file: !199, line: 189, type: !2587, scopeLine: 189, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2587 = !DISubroutineType(types: !2588)
!2588 = !{!2481, !2557, !32}
!2589 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEppEi", scope: !2481, file: !199, line: 194, type: !2587, scopeLine: 194, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2590 = !DISubprogram(name: "getInstrIterator", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEE16getInstrIteratorEv", scope: !2481, file: !199, line: 200, type: !2591, scopeLine: 200, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2591 = !DISubroutineType(types: !2592)
!2592 = !{!2500, !2570}
!2593 = !{!2594, !2595}
!2594 = !DITemplateTypeParameter(name: "Ty", type: !269)
!2595 = !DITemplateTypeParameter(name: "IterTy", type: !2500)
!2596 = !DIDerivedType(tag: DW_TAG_member, name: "NumPhysRegs", scope: !2465, file: !2464, line: 37, baseType: !6, size: 32, offset: 384)
!2597 = !DIDerivedType(tag: DW_TAG_member, name: "Tracking", scope: !2465, file: !2464, line: 41, baseType: !145, size: 8, offset: 416)
!2598 = !DIDerivedType(tag: DW_TAG_member, name: "Scavenged", scope: !2465, file: !2464, line: 59, baseType: !2599, size: 448, offset: 448)
!2599 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<llvm::RegScavenger::ScavengedInfo, 2U>", scope: !14, file: !2317, line: 880, size: 448, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2600, templateParams: !2698, identifier: "_ZTSN4llvm11SmallVectorINS_12RegScavenger13ScavengedInfoELj2EEE")
!2600 = !{!2601, !2691, !2700, !2704, !2707, !2712, !2715, !2719}
!2601 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2599, baseType: !2602, flags: DIFlagPublic, extraData: i32 0)
!2602 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<llvm::RegScavenger::ScavengedInfo>", scope: !14, file: !2317, line: 371, size: 320, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2603, templateParams: !2690, identifier: "_ZTSN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEEE")
!2603 = !{!2604, !2628, !2634, !2637, !2640, !2641, !2642, !2645, !2646, !2649, !2653, !2658, !2659, !2663, !2666, !2670, !2673, !2676, !2679, !2683, !2687, !2688, !2689}
!2604 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2602, baseType: !2605, flags: DIFlagPublic, extraData: i32 0)
!2605 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<llvm::RegScavenger::ScavengedInfo, true>", scope: !14, file: !2317, line: 296, size: 320, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2606, templateParams: !2625, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseINS_12RegScavenger13ScavengedInfoELb1EEE")
!2606 = !{!2607, !2608, !2612, !2616, !2617, !2622}
!2607 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2605, baseType: !2444, flags: DIFlagPublic, extraData: i32 0)
!2608 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !2605, file: !2317, line: 298, type: !2609, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2609 = !DISubroutineType(types: !2610)
!2610 = !{null, !2611, !2102}
!2611 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2605, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2612 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseINS_12RegScavenger13ScavengedInfoELb1EE13destroy_rangeEPS2_S4_", scope: !2605, file: !2317, line: 301, type: !2613, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2613 = !DISubroutineType(types: !2614)
!2614 = !{null, !2615, !2615}
!2615 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2463, size: 64)
!2616 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseINS_12RegScavenger13ScavengedInfoELb1EE4growEm", scope: !2605, file: !2317, line: 346, type: !2609, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2617 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseINS_12RegScavenger13ScavengedInfoELb1EE9push_backERKS2_", scope: !2605, file: !2317, line: 350, type: !2618, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2618 = !DISubroutineType(types: !2619)
!2619 = !{null, !2611, !2620}
!2620 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2621, size: 64)
!2621 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2463)
!2622 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseINS_12RegScavenger13ScavengedInfoELb1EE8pop_backEv", scope: !2605, file: !2317, line: 361, type: !2623, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2623 = !DISubroutineType(types: !2624)
!2624 = !{null, !2611}
!2625 = !{!2626, !2627}
!2626 = !DITemplateTypeParameter(name: "T", type: !2463)
!2627 = !DITemplateValueParameter(name: "isPodLike", type: !145, value: i8 1)
!2628 = !DISubprogram(name: "SmallVectorImpl", scope: !2602, file: !2317, line: 374, type: !2629, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2629 = !DISubroutineType(types: !2630)
!2630 = !{null, !2631, !2632}
!2631 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2602, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2632 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2633, size: 64)
!2633 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2602)
!2634 = !DISubprogram(name: "SmallVectorImpl", scope: !2602, file: !2317, line: 381, type: !2635, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2635 = !DISubroutineType(types: !2636)
!2636 = !{null, !2631, !6}
!2637 = !DISubprogram(name: "~SmallVectorImpl", scope: !2602, file: !2317, line: 386, type: !2638, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2638 = !DISubroutineType(types: !2639)
!2639 = !{null, !2631}
!2640 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEE5clearEv", scope: !2602, file: !2317, line: 396, type: !2638, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2641 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEE6resizeEj", scope: !2602, file: !2317, line: 401, type: !2635, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2642 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEE6resizeEjRKS2_", scope: !2602, file: !2317, line: 413, type: !2643, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2643 = !DISubroutineType(types: !2644)
!2644 = !{null, !2631, !6, !2620}
!2645 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEE7reserveEj", scope: !2602, file: !2317, line: 425, type: !2635, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2646 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEE12pop_back_valEv", scope: !2602, file: !2317, line: 430, type: !2647, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2647 = !DISubroutineType(types: !2648)
!2648 = !{!2463, !2631}
!2649 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEE4swapERS3_", scope: !2602, file: !2317, line: 440, type: !2650, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2650 = !DISubroutineType(types: !2651)
!2651 = !{null, !2631, !2652}
!2652 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2602, size: 64)
!2653 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEE6appendEmRKS2_", scope: !2602, file: !2317, line: 460, type: !2654, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2654 = !DISubroutineType(types: !2655)
!2655 = !{null, !2631, !2656, !2620}
!2656 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2602, file: !2317, line: 377, baseType: !2657)
!2657 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2444, file: !2317, line: 97, baseType: !2102)
!2658 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEE6assignEjRKS2_", scope: !2602, file: !2317, line: 470, type: !2643, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2659 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEE5eraseEPS2_", scope: !2602, file: !2317, line: 478, type: !2660, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2660 = !DISubroutineType(types: !2661)
!2661 = !{!2662, !2631, !2662}
!2662 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2602, file: !2317, line: 376, baseType: !2443)
!2663 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEE5eraseEPS2_S4_", scope: !2602, file: !2317, line: 490, type: !2664, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2664 = !DISubroutineType(types: !2665)
!2665 = !{!2662, !2631, !2662, !2662}
!2666 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEE6insertEPS2_OS2_", scope: !2602, file: !2317, line: 505, type: !2667, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2667 = !DISubroutineType(types: !2668)
!2668 = !{!2662, !2631, !2662, !2669}
!2669 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2463, size: 64)
!2670 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEE6insertEPS2_RKS2_", scope: !2602, file: !2317, line: 537, type: !2671, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2671 = !DISubroutineType(types: !2672)
!2672 = !{!2662, !2631, !2662, !2620}
!2673 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEE6insertEPS2_mRKS2_", scope: !2602, file: !2317, line: 568, type: !2674, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2674 = !DISubroutineType(types: !2675)
!2675 = !{!2662, !2631, !2662, !2656, !2620}
!2676 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEEaSERKS3_", scope: !2602, file: !2317, line: 674, type: !2677, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2677 = !DISubroutineType(types: !2678)
!2678 = !{!2652, !2631, !2632}
!2679 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEEaSEOS3_", scope: !2602, file: !2317, line: 677, type: !2680, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2680 = !DISubroutineType(types: !2681)
!2681 = !{!2652, !2631, !2682}
!2682 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2602, size: 64)
!2683 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEEeqERKS3_", scope: !2602, file: !2317, line: 680, type: !2684, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2684 = !DISubroutineType(types: !2685)
!2685 = !{!145, !2686, !2632}
!2686 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2633, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2687 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEEneERKS3_", scope: !2602, file: !2317, line: 684, type: !2684, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2688 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEEltERKS3_", scope: !2602, file: !2317, line: 688, type: !2684, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2689 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplINS_12RegScavenger13ScavengedInfoEE8set_sizeEj", scope: !2602, file: !2317, line: 702, type: !2635, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2690 = !{!2626}
!2691 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !2599, file: !2317, line: 882, baseType: !2692, size: 128, offset: 320)
!2692 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<llvm::RegScavenger::ScavengedInfo, 2U>", scope: !14, file: !2317, line: 865, size: 128, flags: DIFlagTypePassByValue, elements: !2693, templateParams: !2698, identifier: "_ZTSN4llvm18SmallVectorStorageINS_12RegScavenger13ScavengedInfoELj2EEE")
!2693 = !{!2694}
!2694 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !2692, file: !2317, line: 866, baseType: !2695, size: 128)
!2695 = !DICompositeType(tag: DW_TAG_array_type, baseType: !2448, size: 128, elements: !2696)
!2696 = !{!2697}
!2697 = !DISubrange(count: 1)
!2698 = !{!2626, !2699}
!2699 = !DITemplateValueParameter(name: "N", type: !6, value: i32 2)
!2700 = !DISubprogram(name: "SmallVector", scope: !2599, file: !2317, line: 884, type: !2701, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2701 = !DISubroutineType(types: !2702)
!2702 = !{null, !2703}
!2703 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2599, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2704 = !DISubprogram(name: "SmallVector", scope: !2599, file: !2317, line: 887, type: !2705, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2705 = !DISubroutineType(types: !2706)
!2706 = !{null, !2703, !6, !2620}
!2707 = !DISubprogram(name: "SmallVector", scope: !2599, file: !2317, line: 897, type: !2708, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2708 = !DISubroutineType(types: !2709)
!2709 = !{null, !2703, !2710}
!2710 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2711, size: 64)
!2711 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2599)
!2712 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorINS_12RegScavenger13ScavengedInfoELj2EEaSERKS3_", scope: !2599, file: !2317, line: 902, type: !2713, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2713 = !DISubroutineType(types: !2714)
!2714 = !{!2710, !2703, !2710}
!2715 = !DISubprogram(name: "SmallVector", scope: !2599, file: !2317, line: 908, type: !2716, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2716 = !DISubroutineType(types: !2717)
!2717 = !{null, !2703, !2718}
!2718 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2599, size: 64)
!2719 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorINS_12RegScavenger13ScavengedInfoELj2EEaSEOS3_", scope: !2599, file: !2317, line: 913, type: !2720, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2720 = !DISubroutineType(types: !2721)
!2721 = !{!2710, !2703, !2718}
!2722 = !DIDerivedType(tag: DW_TAG_member, name: "CalleeSavedRegs", scope: !2465, file: !2464, line: 63, baseType: !637, size: 128, offset: 896)
!2723 = !DIDerivedType(tag: DW_TAG_member, name: "RegsAvailable", scope: !2465, file: !2464, line: 68, baseType: !637, size: 128, offset: 1024)
!2724 = !DIDerivedType(tag: DW_TAG_member, name: "KillRegs", scope: !2465, file: !2464, line: 72, baseType: !637, size: 128, offset: 1152)
!2725 = !DIDerivedType(tag: DW_TAG_member, name: "DefRegs", scope: !2465, file: !2464, line: 72, baseType: !637, size: 128, offset: 1280)
!2726 = !DISubprogram(name: "RegScavenger", scope: !2465, file: !2464, line: 75, type: !2727, scopeLine: 75, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2727 = !DISubroutineType(types: !2728)
!2728 = !{null, !2729}
!2729 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2465, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2730 = !DISubprogram(name: "enterBasicBlock", linkageName: "_ZN4llvm12RegScavenger15enterBasicBlockEPNS_17MachineBasicBlockE", scope: !2465, file: !2464, line: 80, type: !2731, scopeLine: 80, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2731 = !DISubroutineType(types: !2732)
!2732 = !{null, !2729, !197}
!2733 = !DISubprogram(name: "initRegState", linkageName: "_ZN4llvm12RegScavenger12initRegStateEv", scope: !2465, file: !2464, line: 84, type: !2727, scopeLine: 84, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2734 = !DISubprogram(name: "forward", linkageName: "_ZN4llvm12RegScavenger7forwardEv", scope: !2465, file: !2464, line: 87, type: !2727, scopeLine: 87, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2735 = !DISubprogram(name: "forward", linkageName: "_ZN4llvm12RegScavenger7forwardENS_17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS3_EEEE", scope: !2465, file: !2464, line: 91, type: !2736, scopeLine: 91, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2736 = !DISubroutineType(types: !2737)
!2737 = !{null, !2729, !2480}
!2738 = !DISubprogram(name: "unprocess", linkageName: "_ZN4llvm12RegScavenger9unprocessEv", scope: !2465, file: !2464, line: 98, type: !2727, scopeLine: 98, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2739 = !DISubprogram(name: "unprocess", linkageName: "_ZN4llvm12RegScavenger9unprocessENS_17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS3_EEEE", scope: !2465, file: !2464, line: 101, type: !2736, scopeLine: 101, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2740 = !DISubprogram(name: "skipTo", linkageName: "_ZN4llvm12RegScavenger6skipToENS_17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS3_EEEE", scope: !2465, file: !2464, line: 106, type: !2736, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2741 = !DISubprogram(name: "getCurrentPosition", linkageName: "_ZNK4llvm12RegScavenger18getCurrentPositionEv", scope: !2465, file: !2464, line: 112, type: !2742, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2742 = !DISubroutineType(types: !2743)
!2743 = !{!2480, !2744}
!2744 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2745, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2745 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2465)
!2746 = !DISubprogram(name: "getRegsUsed", linkageName: "_ZN4llvm12RegScavenger11getRegsUsedERNS_9BitVectorEb", scope: !2465, file: !2464, line: 117, type: !2747, scopeLine: 117, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2747 = !DISubroutineType(types: !2748)
!2748 = !{null, !2729, !687, !145}
!2749 = !DISubprogram(name: "getRegsAvailable", linkageName: "_ZN4llvm12RegScavenger16getRegsAvailableEPKNS_19TargetRegisterClassE", scope: !2465, file: !2464, line: 121, type: !2750, scopeLine: 121, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2750 = !DISubroutineType(types: !2751)
!2751 = !{!637, !2729, !2752}
!2752 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2753, size: 64)
!2753 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2754)
!2754 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "TargetRegisterClass", scope: !14, file: !405, line: 36, size: 384, flags: DIFlagTypePassByValue, elements: !2755, identifier: "_ZTSN4llvm19TargetRegisterClassE")
!2755 = !{!2756, !2819, !2824, !2825, !2827, !2832, !2916, !2920, !2923, !2927, !2928, !2929, !2932, !2935, !2938, !2939, !2940, !2943, !2946, !2950, !2953, !2954, !2957, !2958, !2959, !2960, !2963, !2966, !2969, !2970}
!2756 = !DIDerivedType(tag: DW_TAG_member, name: "MC", scope: !2754, file: !405, line: 44, baseType: !2757, size: 64, flags: DIFlagPublic)
!2757 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2758, size: 64)
!2758 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2759)
!2759 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MCRegisterClass", scope: !14, file: !2760, line: 30, size: 320, flags: DIFlagTypePassByValue, elements: !2761, identifier: "_ZTSN4llvm15MCRegisterClassE")
!2760 = !DIFile(filename: "llvm34/include/llvm/MC/MCRegisterInfo.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "52288842b54a0a7ed9b58f30b2e121db")
!2761 = !{!2762, !2763, !2772, !2778, !2780, !2781, !2782, !2783, !2784, !2789, !2790, !2794, !2797, !2800, !2801, !2802, !2805, !2808, !2811, !2812, !2813, !2816}
!2762 = !DIDerivedType(tag: DW_TAG_member, name: "Name", scope: !2759, file: !2760, line: 35, baseType: !317, size: 64, flags: DIFlagPublic)
!2763 = !DIDerivedType(tag: DW_TAG_member, name: "RegsBegin", scope: !2759, file: !2760, line: 36, baseType: !2764, size: 64, offset: 64, flags: DIFlagPublic)
!2764 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2765)
!2765 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2759, file: !2760, line: 32, baseType: !2766)
!2766 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2767, size: 64)
!2767 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2768)
!2768 = !DIDerivedType(tag: DW_TAG_typedef, name: "MCPhysReg", scope: !14, file: !2760, line: 27, baseType: !2769)
!2769 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint16_t", file: !293, line: 25, baseType: !2770)
!2770 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint16_t", file: !287, line: 39, baseType: !2771)
!2771 = !DIBasicType(name: "unsigned short", size: 16, encoding: DW_ATE_unsigned)
!2772 = !DIDerivedType(tag: DW_TAG_member, name: "RegSet", scope: !2759, file: !2760, line: 37, baseType: !2773, size: 64, offset: 128, flags: DIFlagPublic)
!2773 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2774)
!2774 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2775, size: 64)
!2775 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2776)
!2776 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint8_t", file: !293, line: 24, baseType: !2777)
!2777 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint8_t", file: !287, line: 37, baseType: !251)
!2778 = !DIDerivedType(tag: DW_TAG_member, name: "RegsSize", scope: !2759, file: !2760, line: 38, baseType: !2779, size: 16, offset: 192, flags: DIFlagPublic)
!2779 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2769)
!2780 = !DIDerivedType(tag: DW_TAG_member, name: "RegSetSize", scope: !2759, file: !2760, line: 39, baseType: !2779, size: 16, offset: 208, flags: DIFlagPublic)
!2781 = !DIDerivedType(tag: DW_TAG_member, name: "ID", scope: !2759, file: !2760, line: 40, baseType: !2779, size: 16, offset: 224, flags: DIFlagPublic)
!2782 = !DIDerivedType(tag: DW_TAG_member, name: "RegSize", scope: !2759, file: !2760, line: 41, baseType: !2779, size: 16, offset: 240, flags: DIFlagPublic)
!2783 = !DIDerivedType(tag: DW_TAG_member, name: "Alignment", scope: !2759, file: !2760, line: 41, baseType: !2779, size: 16, offset: 256, flags: DIFlagPublic)
!2784 = !DIDerivedType(tag: DW_TAG_member, name: "CopyCost", scope: !2759, file: !2760, line: 42, baseType: !2785, size: 8, offset: 272, flags: DIFlagPublic)
!2785 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2786)
!2786 = !DIDerivedType(tag: DW_TAG_typedef, name: "int8_t", file: !285, line: 24, baseType: !2787)
!2787 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int8_t", file: !287, line: 36, baseType: !2788)
!2788 = !DIBasicType(name: "signed char", size: 8, encoding: DW_ATE_signed_char)
!2789 = !DIDerivedType(tag: DW_TAG_member, name: "Allocatable", scope: !2759, file: !2760, line: 43, baseType: !833, size: 8, offset: 280, flags: DIFlagPublic)
!2790 = !DISubprogram(name: "getID", linkageName: "_ZNK4llvm15MCRegisterClass5getIDEv", scope: !2759, file: !2760, line: 47, type: !2791, scopeLine: 47, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2791 = !DISubroutineType(types: !2792)
!2792 = !{!6, !2793}
!2793 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2758, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2794 = !DISubprogram(name: "getName", linkageName: "_ZNK4llvm15MCRegisterClass7getNameEv", scope: !2759, file: !2760, line: 51, type: !2795, scopeLine: 51, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2795 = !DISubroutineType(types: !2796)
!2796 = !{!317, !2793}
!2797 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm15MCRegisterClass5beginEv", scope: !2759, file: !2760, line: 55, type: !2798, scopeLine: 55, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2798 = !DISubroutineType(types: !2799)
!2799 = !{!2765, !2793}
!2800 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm15MCRegisterClass3endEv", scope: !2759, file: !2760, line: 56, type: !2798, scopeLine: 56, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2801 = !DISubprogram(name: "getNumRegs", linkageName: "_ZNK4llvm15MCRegisterClass10getNumRegsEv", scope: !2759, file: !2760, line: 60, type: !2791, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2802 = !DISubprogram(name: "getRegister", linkageName: "_ZNK4llvm15MCRegisterClass11getRegisterEj", scope: !2759, file: !2760, line: 64, type: !2803, scopeLine: 64, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2803 = !DISubroutineType(types: !2804)
!2804 = !{!6, !2793, !6}
!2805 = !DISubprogram(name: "contains", linkageName: "_ZNK4llvm15MCRegisterClass8containsEj", scope: !2759, file: !2760, line: 71, type: !2806, scopeLine: 71, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2806 = !DISubroutineType(types: !2807)
!2807 = !{!145, !2793, !6}
!2808 = !DISubprogram(name: "contains", linkageName: "_ZNK4llvm15MCRegisterClass8containsEjj", scope: !2759, file: !2760, line: 80, type: !2809, scopeLine: 80, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2809 = !DISubroutineType(types: !2810)
!2810 = !{!145, !2793, !6, !6}
!2811 = !DISubprogram(name: "getSize", linkageName: "_ZNK4llvm15MCRegisterClass7getSizeEv", scope: !2759, file: !2760, line: 86, type: !2791, scopeLine: 86, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2812 = !DISubprogram(name: "getAlignment", linkageName: "_ZNK4llvm15MCRegisterClass12getAlignmentEv", scope: !2759, file: !2760, line: 90, type: !2791, scopeLine: 90, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2813 = !DISubprogram(name: "getCopyCost", linkageName: "_ZNK4llvm15MCRegisterClass11getCopyCostEv", scope: !2759, file: !2760, line: 95, type: !2814, scopeLine: 95, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2814 = !DISubroutineType(types: !2815)
!2815 = !{!32, !2793}
!2816 = !DISubprogram(name: "isAllocatable", linkageName: "_ZNK4llvm15MCRegisterClass13isAllocatableEv", scope: !2759, file: !2760, line: 99, type: !2817, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2817 = !DISubroutineType(types: !2818)
!2818 = !{!145, !2793}
!2819 = !DIDerivedType(tag: DW_TAG_member, name: "VTs", scope: !2754, file: !405, line: 45, baseType: !2820, size: 64, offset: 64, flags: DIFlagPublic)
!2820 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2821)
!2821 = !DIDerivedType(tag: DW_TAG_typedef, name: "vt_iterator", scope: !2754, file: !405, line: 40, baseType: !2822)
!2822 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2823, size: 64)
!2823 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !29)
!2824 = !DIDerivedType(tag: DW_TAG_member, name: "SubClassMask", scope: !2754, file: !405, line: 46, baseType: !290, size: 64, offset: 128, flags: DIFlagPublic)
!2825 = !DIDerivedType(tag: DW_TAG_member, name: "SuperRegIndices", scope: !2754, file: !405, line: 47, baseType: !2826, size: 64, offset: 192, flags: DIFlagPublic)
!2826 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2779, size: 64)
!2827 = !DIDerivedType(tag: DW_TAG_member, name: "SuperClasses", scope: !2754, file: !405, line: 48, baseType: !2828, size: 64, offset: 256, flags: DIFlagPublic)
!2828 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2829)
!2829 = !DIDerivedType(tag: DW_TAG_typedef, name: "sc_iterator", scope: !2754, file: !405, line: 41, baseType: !2830)
!2830 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2831, size: 64)
!2831 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2752)
!2832 = !DIDerivedType(tag: DW_TAG_member, name: "OrderFunc", scope: !2754, file: !405, line: 49, baseType: !2833, size: 64, offset: 320, flags: DIFlagPublic)
!2833 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2834, size: 64)
!2834 = !DISubroutineType(types: !2835)
!2835 = !{!2836, !2912}
!2836 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ArrayRef<unsigned short>", scope: !14, file: !2837, line: 31, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2838, templateParams: !2910, identifier: "_ZTSN4llvm8ArrayRefItEE")
!2837 = !DIFile(filename: "llvm34/include/llvm/ADT/ArrayRef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "6317ba9f99cd1980a6299fb308b36f31")
!2838 = !{!2839, !2842, !2844, !2848, !2851, !2855, !2858, !2861, !2867, !2873, !2874, !2879, !2880, !2883, !2886, !2889, !2892, !2893, !2896, !2899, !2902, !2905, !2909}
!2839 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !2836, file: !2837, line: 41, baseType: !2840, size: 64)
!2840 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2841, size: 64)
!2841 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2771)
!2842 = !DIDerivedType(tag: DW_TAG_member, name: "Length", scope: !2836, file: !2837, line: 44, baseType: !2843, size: 64, offset: 64)
!2843 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !2837, line: 35, baseType: !2102)
!2844 = !DISubprogram(name: "ArrayRef", scope: !2836, file: !2837, line: 51, type: !2845, scopeLine: 51, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2845 = !DISubroutineType(types: !2846)
!2846 = !{null, !2847}
!2847 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2836, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2848 = !DISubprogram(name: "ArrayRef", scope: !2836, file: !2837, line: 54, type: !2849, scopeLine: 54, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2849 = !DISubroutineType(types: !2850)
!2850 = !{null, !2847, !111}
!2851 = !DISubprogram(name: "ArrayRef", scope: !2836, file: !2837, line: 57, type: !2852, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2852 = !DISubroutineType(types: !2853)
!2853 = !{null, !2847, !2854}
!2854 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2841, size: 64)
!2855 = !DISubprogram(name: "ArrayRef", scope: !2836, file: !2837, line: 61, type: !2856, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2856 = !DISubroutineType(types: !2857)
!2857 = !{null, !2847, !2840, !2102}
!2858 = !DISubprogram(name: "ArrayRef", scope: !2836, file: !2837, line: 65, type: !2859, scopeLine: 65, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2859 = !DISubroutineType(types: !2860)
!2860 = !{null, !2847, !2840, !2840}
!2861 = !DISubprogram(name: "ArrayRef", scope: !2836, file: !2837, line: 88, type: !2862, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2862 = !DISubroutineType(types: !2863)
!2863 = !{null, !2847, !2864}
!2864 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2865, size: 64)
!2865 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2866)
!2866 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<unsigned short>", scope: !839, file: !1070, line: 47, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listItE")
!2867 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm8ArrayRefItE5beginEv", scope: !2836, file: !2837, line: 97, type: !2868, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2868 = !DISubroutineType(types: !2869)
!2869 = !{!2870, !2871}
!2870 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2836, file: !2837, line: 33, baseType: !2840)
!2871 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2872, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2872 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2836)
!2873 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm8ArrayRefItE3endEv", scope: !2836, file: !2837, line: 98, type: !2868, scopeLine: 98, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2874 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm8ArrayRefItE6rbeginEv", scope: !2836, file: !2837, line: 100, type: !2875, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2875 = !DISubroutineType(types: !2876)
!2876 = !{!2877, !2871}
!2877 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !2836, file: !2837, line: 37, baseType: !2878)
!2878 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const unsigned short *>", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKtE")
!2879 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm8ArrayRefItE4rendEv", scope: !2836, file: !2837, line: 101, type: !2875, scopeLine: 101, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2880 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm8ArrayRefItE5emptyEv", scope: !2836, file: !2837, line: 104, type: !2881, scopeLine: 104, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2881 = !DISubroutineType(types: !2882)
!2882 = !{!145, !2871}
!2883 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm8ArrayRefItE4dataEv", scope: !2836, file: !2837, line: 106, type: !2884, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2884 = !DISubroutineType(types: !2885)
!2885 = !{!2840, !2871}
!2886 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm8ArrayRefItE4sizeEv", scope: !2836, file: !2837, line: 109, type: !2887, scopeLine: 109, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2887 = !DISubroutineType(types: !2888)
!2888 = !{!2102, !2871}
!2889 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm8ArrayRefItE5frontEv", scope: !2836, file: !2837, line: 112, type: !2890, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2890 = !DISubroutineType(types: !2891)
!2891 = !{!2854, !2871}
!2892 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm8ArrayRefItE4backEv", scope: !2836, file: !2837, line: 118, type: !2890, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2893 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm8ArrayRefItE6equalsES1_", scope: !2836, file: !2837, line: 124, type: !2894, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2894 = !DISubroutineType(types: !2895)
!2895 = !{!145, !2871, !2836}
!2896 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefItE5sliceEj", scope: !2836, file: !2837, line: 134, type: !2897, scopeLine: 134, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2897 = !DISubroutineType(types: !2898)
!2898 = !{!2836, !2871, !6}
!2899 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefItE5sliceEjj", scope: !2836, file: !2837, line: 141, type: !2900, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2900 = !DISubroutineType(types: !2901)
!2901 = !{!2836, !2871, !6, !6}
!2902 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm8ArrayRefItEixEm", scope: !2836, file: !2837, line: 149, type: !2903, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2903 = !DISubroutineType(types: !2904)
!2904 = !{!2854, !2871, !2102}
!2905 = !DISubprogram(name: "vec", linkageName: "_ZNK4llvm8ArrayRefItE3vecEv", scope: !2836, file: !2837, line: 157, type: !2906, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2906 = !DISubroutineType(types: !2907)
!2907 = !{!2908, !2871}
!2908 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<unsigned short, std::allocator<unsigned short> >", scope: !839, file: !838, line: 339, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt6vectorItSaItEE")
!2909 = !DISubprogram(name: "operator vector", linkageName: "_ZNK4llvm8ArrayRefItEcvSt6vectorItSaItEEEv", scope: !2836, file: !2837, line: 164, type: !2906, scopeLine: 164, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2910 = !{!2911}
!2911 = !DITemplateTypeParameter(name: "T", type: !2771)
!2912 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2913, size: 64)
!2913 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2914)
!2914 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MachineFunction", scope: !14, file: !2915, line: 75, size: 2752, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm15MachineFunctionE")
!2915 = !DIFile(filename: "llvm34/include/llvm/CodeGen/MachineFunction.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "6679f105617a991eecf4f4903ade0d6f")
!2916 = !DISubprogram(name: "getID", linkageName: "_ZNK4llvm19TargetRegisterClass5getIDEv", scope: !2754, file: !405, line: 53, type: !2917, scopeLine: 53, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2917 = !DISubroutineType(types: !2918)
!2918 = !{!6, !2919}
!2919 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2753, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2920 = !DISubprogram(name: "getName", linkageName: "_ZNK4llvm19TargetRegisterClass7getNameEv", scope: !2754, file: !405, line: 57, type: !2921, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2921 = !DISubroutineType(types: !2922)
!2922 = !{!317, !2919}
!2923 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm19TargetRegisterClass5beginEv", scope: !2754, file: !405, line: 61, type: !2924, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2924 = !DISubroutineType(types: !2925)
!2925 = !{!2926, !2919}
!2926 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2754, file: !405, line: 38, baseType: !2766)
!2927 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm19TargetRegisterClass3endEv", scope: !2754, file: !405, line: 62, type: !2924, scopeLine: 62, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2928 = !DISubprogram(name: "getNumRegs", linkageName: "_ZNK4llvm19TargetRegisterClass10getNumRegsEv", scope: !2754, file: !405, line: 66, type: !2917, scopeLine: 66, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2929 = !DISubprogram(name: "getRegister", linkageName: "_ZNK4llvm19TargetRegisterClass11getRegisterEj", scope: !2754, file: !405, line: 70, type: !2930, scopeLine: 70, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2930 = !DISubroutineType(types: !2931)
!2931 = !{!6, !2919, !6}
!2932 = !DISubprogram(name: "contains", linkageName: "_ZNK4llvm19TargetRegisterClass8containsEj", scope: !2754, file: !405, line: 76, type: !2933, scopeLine: 76, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2933 = !DISubroutineType(types: !2934)
!2934 = !{!145, !2919, !6}
!2935 = !DISubprogram(name: "contains", linkageName: "_ZNK4llvm19TargetRegisterClass8containsEjj", scope: !2754, file: !405, line: 81, type: !2936, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2936 = !DISubroutineType(types: !2937)
!2937 = !{!145, !2919, !6, !6}
!2938 = !DISubprogram(name: "getSize", linkageName: "_ZNK4llvm19TargetRegisterClass7getSizeEv", scope: !2754, file: !405, line: 87, type: !2917, scopeLine: 87, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2939 = !DISubprogram(name: "getAlignment", linkageName: "_ZNK4llvm19TargetRegisterClass12getAlignmentEv", scope: !2754, file: !405, line: 91, type: !2917, scopeLine: 91, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2940 = !DISubprogram(name: "getCopyCost", linkageName: "_ZNK4llvm19TargetRegisterClass11getCopyCostEv", scope: !2754, file: !405, line: 96, type: !2941, scopeLine: 96, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2941 = !DISubroutineType(types: !2942)
!2942 = !{!32, !2919}
!2943 = !DISubprogram(name: "isAllocatable", linkageName: "_ZNK4llvm19TargetRegisterClass13isAllocatableEv", scope: !2754, file: !405, line: 100, type: !2944, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2944 = !DISubroutineType(types: !2945)
!2945 = !{!145, !2919}
!2946 = !DISubprogram(name: "hasType", linkageName: "_ZNK4llvm19TargetRegisterClass7hasTypeENS_3EVTE", scope: !2754, file: !405, line: 104, type: !2947, scopeLine: 104, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2947 = !DISubroutineType(types: !2948)
!2948 = !{!145, !2919, !2949}
!2949 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "EVT", scope: !14, file: !30, line: 576, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm3EVTE")
!2950 = !DISubprogram(name: "vt_begin", linkageName: "_ZNK4llvm19TargetRegisterClass8vt_beginEv", scope: !2754, file: !405, line: 113, type: !2951, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2951 = !DISubroutineType(types: !2952)
!2952 = !{!2821, !2919}
!2953 = !DISubprogram(name: "vt_end", linkageName: "_ZNK4llvm19TargetRegisterClass6vt_endEv", scope: !2754, file: !405, line: 117, type: !2951, scopeLine: 117, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2954 = !DISubprogram(name: "hasSubClass", linkageName: "_ZNK4llvm19TargetRegisterClass11hasSubClassEPKS0_", scope: !2754, file: !405, line: 125, type: !2955, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2955 = !DISubroutineType(types: !2956)
!2956 = !{!145, !2919, !2752}
!2957 = !DISubprogram(name: "hasSubClassEq", linkageName: "_ZNK4llvm19TargetRegisterClass13hasSubClassEqEPKS0_", scope: !2754, file: !405, line: 131, type: !2955, scopeLine: 131, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2958 = !DISubprogram(name: "hasSuperClass", linkageName: "_ZNK4llvm19TargetRegisterClass13hasSuperClassEPKS0_", scope: !2754, file: !405, line: 138, type: !2955, scopeLine: 138, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2959 = !DISubprogram(name: "hasSuperClassEq", linkageName: "_ZNK4llvm19TargetRegisterClass15hasSuperClassEqEPKS0_", scope: !2754, file: !405, line: 144, type: !2955, scopeLine: 144, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2960 = !DISubprogram(name: "getSubClassMask", linkageName: "_ZNK4llvm19TargetRegisterClass15getSubClassMaskEv", scope: !2754, file: !405, line: 151, type: !2961, scopeLine: 151, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2961 = !DISubroutineType(types: !2962)
!2962 = !{!290, !2919}
!2963 = !DISubprogram(name: "getSuperRegIndices", linkageName: "_ZNK4llvm19TargetRegisterClass18getSuperRegIndicesEv", scope: !2754, file: !405, line: 163, type: !2964, scopeLine: 163, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2964 = !DISubroutineType(types: !2965)
!2965 = !{!2826, !2919}
!2966 = !DISubprogram(name: "getSuperClasses", linkageName: "_ZNK4llvm19TargetRegisterClass15getSuperClassesEv", scope: !2754, file: !405, line: 170, type: !2967, scopeLine: 170, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2967 = !DISubroutineType(types: !2968)
!2968 = !{!2829, !2919}
!2969 = !DISubprogram(name: "isASubClass", linkageName: "_ZNK4llvm19TargetRegisterClass11isASubClassEv", scope: !2754, file: !405, line: 176, type: !2944, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2970 = !DISubprogram(name: "getRawAllocationOrder", linkageName: "_ZNK4llvm19TargetRegisterClass21getRawAllocationOrderERKNS_15MachineFunctionE", scope: !2754, file: !405, line: 194, type: !2971, scopeLine: 194, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2971 = !DISubroutineType(types: !2972)
!2972 = !{!2836, !2919, !2912}
!2973 = !DISubprogram(name: "FindUnusedReg", linkageName: "_ZNK4llvm12RegScavenger13FindUnusedRegEPKNS_19TargetRegisterClassE", scope: !2465, file: !2464, line: 125, type: !2974, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2974 = !DISubroutineType(types: !2975)
!2975 = !{!6, !2744, !2752}
!2976 = !DISubprogram(name: "addScavengingFrameIndex", linkageName: "_ZN4llvm12RegScavenger23addScavengingFrameIndexEi", scope: !2465, file: !2464, line: 128, type: !2977, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2977 = !DISubroutineType(types: !2978)
!2978 = !{null, !2729, !32}
!2979 = !DISubprogram(name: "isScavengingFrameIndex", linkageName: "_ZNK4llvm12RegScavenger22isScavengingFrameIndexEi", scope: !2465, file: !2464, line: 133, type: !2980, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2980 = !DISubroutineType(types: !2981)
!2981 = !{!145, !2744, !32}
!2982 = !DISubprogram(name: "getScavengingFrameIndices", linkageName: "_ZNK4llvm12RegScavenger25getScavengingFrameIndicesERNS_15SmallVectorImplIiEE", scope: !2465, file: !2464, line: 143, type: !2983, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2983 = !DISubroutineType(types: !2984)
!2984 = !{null, !2744, !2985}
!2985 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2986, size: 64)
!2986 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<int>", scope: !14, file: !2317, line: 371, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm15SmallVectorImplIiEE")
!2987 = !DISubprogram(name: "scavengeRegister", linkageName: "_ZN4llvm12RegScavenger16scavengeRegisterEPKNS_19TargetRegisterClassENS_17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS6_EEEEi", scope: !2465, file: !2464, line: 154, type: !2988, scopeLine: 154, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2988 = !DISubroutineType(types: !2989)
!2989 = !{!6, !2729, !2752, !2480, !32}
!2990 = !DISubprogram(name: "scavengeRegister", linkageName: "_ZN4llvm12RegScavenger16scavengeRegisterEPKNS_19TargetRegisterClassEi", scope: !2465, file: !2464, line: 156, type: !2991, scopeLine: 156, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2991 = !DISubroutineType(types: !2992)
!2992 = !{!6, !2729, !2752, !32}
!2993 = !DISubprogram(name: "setUsed", linkageName: "_ZN4llvm12RegScavenger7setUsedEj", scope: !2465, file: !2464, line: 162, type: !2994, scopeLine: 162, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2994 = !DISubroutineType(types: !2995)
!2995 = !{null, !2729, !6}
!2996 = !DISubprogram(name: "isReserved", linkageName: "_ZNK4llvm12RegScavenger10isReservedEj", scope: !2465, file: !2464, line: 165, type: !2997, scopeLine: 165, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2997 = !DISubroutineType(types: !2998)
!2998 = !{!145, !2744, !6}
!2999 = !DISubprogram(name: "isUsed", linkageName: "_ZNK4llvm12RegScavenger6isUsedEjb", scope: !2465, file: !2464, line: 171, type: !3000, scopeLine: 171, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3000 = !DISubroutineType(types: !3001)
!3001 = !{!145, !2744, !6, !145}
!3002 = !DISubprogram(name: "isAliasUsed", linkageName: "_ZNK4llvm12RegScavenger11isAliasUsedEj", scope: !2465, file: !2464, line: 176, type: !2997, scopeLine: 176, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3003 = !DISubprogram(name: "setUsed", linkageName: "_ZN4llvm12RegScavenger7setUsedERNS_9BitVectorE", scope: !2465, file: !2464, line: 180, type: !3004, scopeLine: 180, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3004 = !DISubroutineType(types: !3005)
!3005 = !{null, !2729, !687}
!3006 = !DISubprogram(name: "setUnused", linkageName: "_ZN4llvm12RegScavenger9setUnusedERNS_9BitVectorE", scope: !2465, file: !2464, line: 183, type: !3004, scopeLine: 183, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3007 = !DISubprogram(name: "determineKillsAndDefs", linkageName: "_ZN4llvm12RegScavenger21determineKillsAndDefsEv", scope: !2465, file: !2464, line: 189, type: !2727, scopeLine: 189, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3008 = !DISubprogram(name: "addRegWithSubRegs", linkageName: "_ZN4llvm12RegScavenger17addRegWithSubRegsERNS_9BitVectorEj", scope: !2465, file: !2464, line: 192, type: !3009, scopeLine: 192, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3009 = !DISubroutineType(types: !3010)
!3010 = !{null, !2729, !687, !6}
!3011 = !DISubprogram(name: "findSurvivorReg", linkageName: "_ZN4llvm12RegScavenger15findSurvivorRegENS_17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS3_EEEERNS_9BitVectorEjRS6_", scope: !2465, file: !2464, line: 199, type: !3012, scopeLine: 199, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3012 = !DISubroutineType(types: !3013)
!3013 = !{!6, !2729, !2480, !687, !6, !3014}
!3014 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2480, size: 64)
!3015 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !2444, file: !2317, line: 78, type: !3016, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3016 = !DISubroutineType(types: !3017)
!3017 = !{null, !3018, !2102}
!3018 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2444, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3019 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE8grow_podEmm", scope: !2444, file: !2317, line: 80, type: !3020, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3020 = !DISubroutineType(types: !3021)
!3021 = !{null, !3018, !2102, !2102}
!3022 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE7isSmallEv", scope: !2444, file: !2317, line: 86, type: !3023, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3023 = !DISubroutineType(types: !3024)
!3024 = !{!145, !3025}
!3025 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3026, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3026 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2444)
!3027 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE12resetToSmallEv", scope: !2444, file: !2317, line: 91, type: !3028, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3028 = !DISubroutineType(types: !3029)
!3029 = !{null, !3018}
!3030 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE6setEndEPS2_", scope: !2444, file: !2317, line: 95, type: !3031, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3031 = !DISubroutineType(types: !3032)
!3032 = !{null, !3018, !2615}
!3033 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE5beginEv", scope: !2444, file: !2317, line: 112, type: !3034, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3034 = !DISubroutineType(types: !3035)
!3035 = !{!2443, !3018}
!3036 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE5beginEv", scope: !2444, file: !2317, line: 113, type: !3037, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3037 = !DISubroutineType(types: !3038)
!3038 = !{!3039, !3025}
!3039 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !2444, file: !2317, line: 101, baseType: !3040)
!3040 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2621, size: 64)
!3041 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE3endEv", scope: !2444, file: !2317, line: 114, type: !3034, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3042 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE3endEv", scope: !2444, file: !2317, line: 115, type: !3037, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3043 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE12capacity_ptrEv", scope: !2444, file: !2317, line: 117, type: !3034, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3044 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE12capacity_ptrEv", scope: !2444, file: !2317, line: 118, type: !3037, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3045 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE6rbeginEv", scope: !2444, file: !2317, line: 122, type: !3046, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3046 = !DISubroutineType(types: !3047)
!3047 = !{!3048, !3018}
!3048 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !2444, file: !2317, line: 104, baseType: !3049)
!3049 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<llvm::RegScavenger::ScavengedInfo *>", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPN4llvm12RegScavenger13ScavengedInfoEE")
!3050 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE6rbeginEv", scope: !2444, file: !2317, line: 123, type: !3051, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3051 = !DISubroutineType(types: !3052)
!3052 = !{!3053, !3025}
!3053 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !2444, file: !2317, line: 103, baseType: !3054)
!3054 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const llvm::RegScavenger::ScavengedInfo *>", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKN4llvm12RegScavenger13ScavengedInfoEE")
!3055 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE4rendEv", scope: !2444, file: !2317, line: 124, type: !3046, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3056 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE4rendEv", scope: !2444, file: !2317, line: 125, type: !3051, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3057 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE4sizeEv", scope: !2444, file: !2317, line: 127, type: !3058, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3058 = !DISubroutineType(types: !3059)
!3059 = !{!2411, !3025}
!3060 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE8max_sizeEv", scope: !2444, file: !2317, line: 128, type: !3058, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3061 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE8capacityEv", scope: !2444, file: !2317, line: 132, type: !3062, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3062 = !DISubroutineType(types: !3063)
!3063 = !{!2102, !3025}
!3064 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE4dataEv", scope: !2444, file: !2317, line: 135, type: !3065, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3065 = !DISubroutineType(types: !3066)
!3066 = !{!3067, !3018}
!3067 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2444, file: !2317, line: 108, baseType: !2615)
!3068 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE4dataEv", scope: !2444, file: !2317, line: 137, type: !3069, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3069 = !DISubroutineType(types: !3070)
!3070 = !{!3071, !3025}
!3071 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !2444, file: !2317, line: 109, baseType: !3040)
!3072 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvEixEj", scope: !2444, file: !2317, line: 139, type: !3073, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3073 = !DISubroutineType(types: !3074)
!3074 = !{!3075, !3018, !6}
!3075 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2444, file: !2317, line: 106, baseType: !3076)
!3076 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2463, size: 64)
!3077 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvEixEj", scope: !2444, file: !2317, line: 143, type: !3078, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3078 = !DISubroutineType(types: !3079)
!3079 = !{!3080, !3025, !6}
!3080 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !2444, file: !2317, line: 107, baseType: !2620)
!3081 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE5frontEv", scope: !2444, file: !2317, line: 148, type: !3082, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3082 = !DISubroutineType(types: !3083)
!3083 = !{!3075, !3018}
!3084 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE5frontEv", scope: !2444, file: !2317, line: 152, type: !3085, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3085 = !DISubroutineType(types: !3086)
!3086 = !{!3080, !3025}
!3087 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE4backEv", scope: !2444, file: !2317, line: 157, type: !3082, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3088 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_12RegScavenger13ScavengedInfoEvE4backEv", scope: !2444, file: !2317, line: 161, type: !3085, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3089 = !{!2626, !2442}
!3090 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3091, size: 64)
!3091 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MachineModuleInfo", scope: !14, file: !3092, line: 97, size: 11840, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm17MachineModuleInfoE")
!3092 = !DIFile(filename: "llvm34/include/llvm/CodeGen/MachineModuleInfo.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "00593de51232b0f1b2d9b1e78a6d420a")
!3093 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringRef", scope: !14, file: !3094, line: 41, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3095, identifier: "_ZTSN4llvm9StringRefE")
!3094 = !DIFile(filename: "llvm34/include/llvm/ADT/StringRef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "5c2e300880041c873457392c89335431")
!3095 = !{!3096, !3098, !3099, !3100, !3103, !3104, !3107, !3111, !3114, !3117, !3127, !3133, !3134, !3137, !3140, !3143, !3146, !3147, !3150, !3151, !3154, !3155, !3156, !3159, !3162, !3165, !3166, !3167, !3168, !3169, !3170, !3173, !3176, !3177, !3180, !3181, !3182, !3183, !3184, !3185, !3186, !3187, !3188, !3191, !3192, !3198, !3199, !3200, !3203, !3206, !3207, !3208, !3266, !3269, !3274, !3275, !3278, !3279}
!3096 = !DIDerivedType(tag: DW_TAG_member, name: "npos", scope: !3093, file: !3094, line: 45, baseType: !3097, flags: DIFlagPublic | DIFlagStaticMember, extraData: i64 -1)
!3097 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2102)
!3098 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !3093, file: !3094, line: 50, baseType: !317, size: 64)
!3099 = !DIDerivedType(tag: DW_TAG_member, name: "Length", scope: !3093, file: !3094, line: 53, baseType: !2102, size: 64, offset: 64)
!3100 = !DISubprogram(name: "min", linkageName: "_ZN4llvm9StringRef3minEmm", scope: !3093, file: !3094, line: 58, type: !3101, scopeLine: 58, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3101 = !DISubroutineType(types: !3102)
!3102 = !{!2102, !2102, !2102}
!3103 = !DISubprogram(name: "max", linkageName: "_ZN4llvm9StringRef3maxEmm", scope: !3093, file: !3094, line: 59, type: !3101, scopeLine: 59, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3104 = !DISubprogram(name: "compareMemory", linkageName: "_ZN4llvm9StringRef13compareMemoryEPKcS2_m", scope: !3093, file: !3094, line: 63, type: !3105, scopeLine: 63, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3105 = !DISubroutineType(types: !3106)
!3106 = !{!32, !317, !317, !2102}
!3107 = !DISubprogram(name: "StringRef", scope: !3093, file: !3094, line: 73, type: !3108, scopeLine: 73, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3108 = !DISubroutineType(types: !3109)
!3109 = !{null, !3110}
!3110 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3093, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3111 = !DISubprogram(name: "StringRef", scope: !3093, file: !3094, line: 76, type: !3112, scopeLine: 76, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3112 = !DISubroutineType(types: !3113)
!3113 = !{null, !3110, !317}
!3114 = !DISubprogram(name: "StringRef", scope: !3093, file: !3094, line: 83, type: !3115, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3115 = !DISubroutineType(types: !3116)
!3116 = !{null, !3110, !317, !2102}
!3117 = !DISubprogram(name: "StringRef", scope: !3093, file: !3094, line: 90, type: !3118, scopeLine: 90, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3118 = !DISubroutineType(types: !3119)
!3119 = !{null, !3110, !3120}
!3120 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3121, size: 64)
!3121 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3122)
!3122 = !DIDerivedType(tag: DW_TAG_typedef, name: "string", scope: !3124, file: !3123, line: 74, baseType: !3125)
!3123 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stringfwd.h", directory: "")
!3124 = !DINamespace(name: "__cxx11", scope: !839, exportSymbols: true)
!3125 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "basic_string<char, std::char_traits<char>, std::allocator<char> >", scope: !3124, file: !3126, line: 1607, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE")
!3126 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.tcc", directory: "")
!3127 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm9StringRef5beginEv", scope: !3093, file: !3094, line: 97, type: !3128, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3128 = !DISubroutineType(types: !3129)
!3129 = !{!3130, !3131}
!3130 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3093, file: !3094, line: 43, baseType: !317)
!3131 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3132, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3132 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3093)
!3133 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm9StringRef3endEv", scope: !3093, file: !3094, line: 99, type: !3128, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3134 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm9StringRef4dataEv", scope: !3093, file: !3094, line: 107, type: !3135, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3135 = !DISubroutineType(types: !3136)
!3136 = !{!317, !3131}
!3137 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm9StringRef5emptyEv", scope: !3093, file: !3094, line: 110, type: !3138, scopeLine: 110, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3138 = !DISubroutineType(types: !3139)
!3139 = !{!145, !3131}
!3140 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm9StringRef4sizeEv", scope: !3093, file: !3094, line: 113, type: !3141, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3141 = !DISubroutineType(types: !3142)
!3142 = !{!2102, !3131}
!3143 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm9StringRef5frontEv", scope: !3093, file: !3094, line: 116, type: !3144, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3144 = !DISubroutineType(types: !3145)
!3145 = !{!319, !3131}
!3146 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm9StringRef4backEv", scope: !3093, file: !3094, line: 122, type: !3144, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3147 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm9StringRef6equalsES0_", scope: !3093, file: !3094, line: 129, type: !3148, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3148 = !DISubroutineType(types: !3149)
!3149 = !{!145, !3131, !3093}
!3150 = !DISubprogram(name: "equals_lower", linkageName: "_ZNK4llvm9StringRef12equals_lowerES0_", scope: !3093, file: !3094, line: 135, type: !3148, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3151 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm9StringRef7compareES0_", scope: !3093, file: !3094, line: 141, type: !3152, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3152 = !DISubroutineType(types: !3153)
!3153 = !{!32, !3131, !3093}
!3154 = !DISubprogram(name: "compare_lower", linkageName: "_ZNK4llvm9StringRef13compare_lowerES0_", scope: !3093, file: !3094, line: 153, type: !3152, scopeLine: 153, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3155 = !DISubprogram(name: "compare_numeric", linkageName: "_ZNK4llvm9StringRef15compare_numericES0_", scope: !3093, file: !3094, line: 157, type: !3152, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3156 = !DISubprogram(name: "edit_distance", linkageName: "_ZNK4llvm9StringRef13edit_distanceES0_bj", scope: !3093, file: !3094, line: 177, type: !3157, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3157 = !DISubroutineType(types: !3158)
!3158 = !{!6, !3131, !3093, !145, !6}
!3159 = !DISubprogram(name: "str", linkageName: "_ZNK4llvm9StringRef3strB5cxx11Ev", scope: !3093, file: !3094, line: 181, type: !3160, scopeLine: 181, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3160 = !DISubroutineType(types: !3161)
!3161 = !{!3122, !3131}
!3162 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm9StringRefixEm", scope: !3093, file: !3094, line: 190, type: !3163, scopeLine: 190, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3163 = !DISubroutineType(types: !3164)
!3164 = !{!319, !3131, !2102}
!3165 = !DISubprogram(name: "operator basic_string", linkageName: "_ZNK4llvm9StringRefcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv", scope: !3093, file: !3094, line: 199, type: !3160, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3166 = !DISubprogram(name: "startswith", linkageName: "_ZNK4llvm9StringRef10startswithES0_", scope: !3093, file: !3094, line: 208, type: !3148, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3167 = !DISubprogram(name: "startswith_lower", linkageName: "_ZNK4llvm9StringRef16startswith_lowerES0_", scope: !3093, file: !3094, line: 214, type: !3148, scopeLine: 214, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3168 = !DISubprogram(name: "endswith", linkageName: "_ZNK4llvm9StringRef8endswithES0_", scope: !3093, file: !3094, line: 217, type: !3148, scopeLine: 217, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3169 = !DISubprogram(name: "endswith_lower", linkageName: "_ZNK4llvm9StringRef14endswith_lowerES0_", scope: !3093, file: !3094, line: 223, type: !3148, scopeLine: 223, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3170 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm9StringRef4findEcm", scope: !3093, file: !3094, line: 233, type: !3171, scopeLine: 233, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3171 = !DISubroutineType(types: !3172)
!3172 = !{!2102, !3131, !319, !2102}
!3173 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm9StringRef4findES0_m", scope: !3093, file: !3094, line: 244, type: !3174, scopeLine: 244, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3174 = !DISubroutineType(types: !3175)
!3175 = !{!2102, !3131, !3093, !2102}
!3176 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm9StringRef5rfindEcm", scope: !3093, file: !3094, line: 250, type: !3171, scopeLine: 250, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3177 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm9StringRef5rfindES0_", scope: !3093, file: !3094, line: 265, type: !3178, scopeLine: 265, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3178 = !DISubroutineType(types: !3179)
!3179 = !{!2102, !3131, !3093}
!3180 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm9StringRef13find_first_ofEcm", scope: !3093, file: !3094, line: 269, type: !3171, scopeLine: 269, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3181 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm9StringRef13find_first_ofES0_m", scope: !3093, file: !3094, line: 277, type: !3174, scopeLine: 277, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3182 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm9StringRef17find_first_not_ofEcm", scope: !3093, file: !3094, line: 281, type: !3171, scopeLine: 281, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3183 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm9StringRef17find_first_not_ofES0_m", scope: !3093, file: !3094, line: 287, type: !3174, scopeLine: 287, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3184 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm9StringRef12find_last_ofEcm", scope: !3093, file: !3094, line: 291, type: !3171, scopeLine: 291, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3185 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm9StringRef12find_last_ofES0_m", scope: !3093, file: !3094, line: 299, type: !3174, scopeLine: 299, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3186 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNK4llvm9StringRef16find_last_not_ofEcm", scope: !3093, file: !3094, line: 303, type: !3171, scopeLine: 303, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3187 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNK4llvm9StringRef16find_last_not_ofES0_m", scope: !3093, file: !3094, line: 309, type: !3174, scopeLine: 309, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3188 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9StringRef5countEc", scope: !3093, file: !3094, line: 316, type: !3189, scopeLine: 316, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3189 = !DISubroutineType(types: !3190)
!3190 = !{!2102, !3131, !319}
!3191 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9StringRef5countES0_", scope: !3093, file: !3094, line: 326, type: !3178, scopeLine: 326, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3192 = !DISubprogram(name: "getAsInteger", linkageName: "_ZNK4llvm9StringRef12getAsIntegerEjRNS_5APIntE", scope: !3093, file: !3094, line: 367, type: !3193, scopeLine: 367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3193 = !DISubroutineType(types: !3194)
!3194 = !{!145, !3131, !6, !3195}
!3195 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3196, size: 64)
!3196 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "APInt", scope: !14, file: !3197, line: 75, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm5APIntE")
!3197 = !DIFile(filename: "llvm34/include/llvm/ADT/APInt.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "2db0cee52675cf90af287a88ac0514bc")
!3198 = !DISubprogram(name: "lower", linkageName: "_ZNK4llvm9StringRef5lowerB5cxx11Ev", scope: !3093, file: !3094, line: 374, type: !3160, scopeLine: 374, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3199 = !DISubprogram(name: "upper", linkageName: "_ZNK4llvm9StringRef5upperB5cxx11Ev", scope: !3093, file: !3094, line: 377, type: !3160, scopeLine: 377, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3200 = !DISubprogram(name: "substr", linkageName: "_ZNK4llvm9StringRef6substrEmm", scope: !3093, file: !3094, line: 392, type: !3201, scopeLine: 392, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3201 = !DISubroutineType(types: !3202)
!3202 = !{!3093, !3131, !2102, !2102}
!3203 = !DISubprogram(name: "drop_front", linkageName: "_ZNK4llvm9StringRef10drop_frontEm", scope: !3093, file: !3094, line: 399, type: !3204, scopeLine: 399, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3204 = !DISubroutineType(types: !3205)
!3205 = !{!3093, !3131, !2102}
!3206 = !DISubprogram(name: "drop_back", linkageName: "_ZNK4llvm9StringRef9drop_backEm", scope: !3093, file: !3094, line: 406, type: !3204, scopeLine: 406, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3207 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm9StringRef5sliceEmm", scope: !3093, file: !3094, line: 421, type: !3201, scopeLine: 421, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3208 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitEc", scope: !3093, file: !3094, line: 437, type: !3209, scopeLine: 437, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3209 = !DISubroutineType(types: !3210)
!3210 = !{!3211, !3131, !319}
!3211 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::StringRef, llvm::StringRef>", scope: !839, file: !1387, line: 208, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3212, templateParams: !3263, identifier: "_ZTSSt4pairIN4llvm9StringRefES1_E")
!3212 = !{!3213, !3233, !3234, !3235, !3241, !3245, !3253, !3260}
!3213 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3211, baseType: !3214, flags: DIFlagPrivate, extraData: i32 0)
!3214 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::StringRef, llvm::StringRef>", scope: !839, file: !1387, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !3215, templateParams: !3230, identifier: "_ZTSSt11__pair_baseIN4llvm9StringRefES1_E")
!3215 = !{!3216, !3220, !3221, !3226}
!3216 = !DISubprogram(name: "__pair_base", scope: !3214, file: !1387, line: 194, type: !3217, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3217 = !DISubroutineType(types: !3218)
!3218 = !{null, !3219}
!3219 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3214, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3220 = !DISubprogram(name: "~__pair_base", scope: !3214, file: !1387, line: 195, type: !3217, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3221 = !DISubprogram(name: "__pair_base", scope: !3214, file: !1387, line: 196, type: !3222, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3222 = !DISubroutineType(types: !3223)
!3223 = !{null, !3219, !3224}
!3224 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3225, size: 64)
!3225 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3214)
!3226 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN4llvm9StringRefES1_EaSERKS2_", scope: !3214, file: !1387, line: 197, type: !3227, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!3227 = !DISubroutineType(types: !3228)
!3228 = !{!3229, !3219, !3224}
!3229 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3214, size: 64)
!3230 = !{!3231, !3232}
!3231 = !DITemplateTypeParameter(name: "_U1", type: !3093)
!3232 = !DITemplateTypeParameter(name: "_U2", type: !3093)
!3233 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !3211, file: !1387, line: 214, baseType: !3093, size: 128)
!3234 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !3211, file: !1387, line: 215, baseType: !3093, size: 128, offset: 128)
!3235 = !DISubprogram(name: "pair", scope: !3211, file: !1387, line: 303, type: !3236, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3236 = !DISubroutineType(types: !3237)
!3237 = !{null, !3238, !3239}
!3238 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3211, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3239 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3240, size: 64)
!3240 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3211)
!3241 = !DISubprogram(name: "pair", scope: !3211, file: !1387, line: 304, type: !3242, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3242 = !DISubroutineType(types: !3243)
!3243 = !{null, !3238, !3244}
!3244 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3211, size: 64)
!3245 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_EaSERKS2_", scope: !3211, file: !1387, line: 378, type: !3246, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3246 = !DISubroutineType(types: !3247)
!3247 = !{!3248, !3238, !3249}
!3248 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3211, size: 64)
!3249 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !3250, file: !1281, line: 1928, baseType: !3239)
!3250 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::StringRef, llvm::StringRef> &, const std::__nonesuch_no_braces &>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !3251, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN4llvm9StringRefES2_ERKSt20__nonesuch_no_bracesE")
!3251 = !{!1472, !3252, !1474}
!3252 = !DITemplateTypeParameter(name: "_Iftrue", type: !3239)
!3253 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_EaSEOS2_", scope: !3211, file: !1387, line: 389, type: !3254, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3254 = !DISubroutineType(types: !3255)
!3255 = !{!3248, !3238, !3256}
!3256 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !3257, file: !1281, line: 1928, baseType: !3244)
!3257 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::StringRef, llvm::StringRef> &&, std::__nonesuch_no_braces &&>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !3258, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN4llvm9StringRefES2_EOSt20__nonesuch_no_bracesE")
!3258 = !{!1472, !3259, !1485}
!3259 = !DITemplateTypeParameter(name: "_Iftrue", type: !3244)
!3260 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_E4swapERS2_", scope: !3211, file: !1387, line: 424, type: !3261, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3261 = !DISubroutineType(types: !3262)
!3262 = !{null, !3238, !3248}
!3263 = !{!3264, !3265}
!3264 = !DITemplateTypeParameter(name: "_T1", type: !3093)
!3265 = !DITemplateTypeParameter(name: "_T2", type: !3093)
!3266 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitES0_", scope: !3093, file: !3094, line: 454, type: !3267, scopeLine: 454, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3267 = !DISubroutineType(types: !3268)
!3268 = !{!3211, !3131, !3093}
!3269 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitERNS_15SmallVectorImplIS0_EES0_ib", scope: !3093, file: !3094, line: 475, type: !3270, scopeLine: 475, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3270 = !DISubroutineType(types: !3271)
!3271 = !{null, !3131, !3272, !3093, !32, !145}
!3272 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3273, size: 64)
!3273 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<llvm::StringRef>", scope: !14, file: !2317, line: 371, size: 320, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm15SmallVectorImplINS_9StringRefEEE")
!3274 = !DISubprogram(name: "rsplit", linkageName: "_ZNK4llvm9StringRef6rsplitEc", scope: !3093, file: !3094, line: 489, type: !3209, scopeLine: 489, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3275 = !DISubprogram(name: "ltrim", linkageName: "_ZNK4llvm9StringRef5ltrimES0_", scope: !3093, file: !3094, line: 498, type: !3276, scopeLine: 498, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3276 = !DISubroutineType(types: !3277)
!3277 = !{!3093, !3131, !3093}
!3278 = !DISubprogram(name: "rtrim", linkageName: "_ZNK4llvm9StringRef5rtrimES0_", scope: !3093, file: !3094, line: 504, type: !3276, scopeLine: 504, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3279 = !DISubprogram(name: "trim", linkageName: "_ZNK4llvm9StringRef4trimES0_", scope: !3093, file: !3094, line: 510, type: !3276, scopeLine: 510, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3280 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3281, file: !838, line: 369, baseType: !3282)
!3281 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<llvm::MachineBasicBlock *, std::allocator<llvm::MachineBasicBlock *> >", scope: !839, file: !838, line: 339, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt6vectorIPN4llvm17MachineBasicBlockESaIS2_EE")
!3282 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<llvm::MachineBasicBlock **, std::vector<llvm::MachineBasicBlock *, std::allocator<llvm::MachineBasicBlock *> > >", scope: !5, file: !1093, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3283, templateParams: !3336, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEE")
!3283 = !{!3284, !3286, !3290, !3295, !3306, !3311, !3315, !3318, !3319, !3320, !3325, !3328, !3331, !3332, !3333}
!3284 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !3282, file: !1093, line: 767, baseType: !3285, size: 64, flags: DIFlagProtected)
!3285 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !197, size: 64)
!3286 = !DISubprogram(name: "__normal_iterator", scope: !3282, file: !1093, line: 779, type: !3287, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3287 = !DISubroutineType(types: !3288)
!3288 = !{null, !3289}
!3289 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3282, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3290 = !DISubprogram(name: "__normal_iterator", scope: !3282, file: !1093, line: 783, type: !3291, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3291 = !DISubroutineType(types: !3292)
!3292 = !{null, !3289, !3293}
!3293 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3294, size: 64)
!3294 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3285)
!3295 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEdeEv", scope: !3282, file: !1093, line: 796, type: !3296, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3296 = !DISubroutineType(types: !3297)
!3297 = !{!3298, !3304}
!3298 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3282, file: !1093, line: 776, baseType: !3299)
!3299 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3300, file: !1110, line: 184, baseType: !3303)
!3300 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<llvm::MachineBasicBlock **>", scope: !839, file: !1110, line: 178, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !3301, identifier: "_ZTSSt15iterator_traitsIPPN4llvm17MachineBasicBlockEE")
!3301 = !{!3302}
!3302 = !DITemplateTypeParameter(name: "_Iterator", type: !3285)
!3303 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !197, size: 64)
!3304 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3305, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3305 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3282)
!3306 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEptEv", scope: !3282, file: !1093, line: 800, type: !3307, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3307 = !DISubroutineType(types: !3308)
!3308 = !{!3309, !3304}
!3309 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3282, file: !1093, line: 777, baseType: !3310)
!3310 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3300, file: !1110, line: 183, baseType: !3285)
!3311 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEppEv", scope: !3282, file: !1093, line: 804, type: !3312, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3312 = !DISubroutineType(types: !3313)
!3313 = !{!3314, !3289}
!3314 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3282, size: 64)
!3315 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEppEi", scope: !3282, file: !1093, line: 811, type: !3316, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3316 = !DISubroutineType(types: !3317)
!3317 = !{!3282, !3289, !32}
!3318 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEmmEv", scope: !3282, file: !1093, line: 816, type: !3312, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3319 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEmmEi", scope: !3282, file: !1093, line: 823, type: !3316, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3320 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEixEl", scope: !3282, file: !1093, line: 828, type: !3321, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3321 = !DISubroutineType(types: !3322)
!3322 = !{!3298, !3304, !3323}
!3323 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !3282, file: !1093, line: 775, baseType: !3324)
!3324 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !3300, file: !1110, line: 182, baseType: !1135)
!3325 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEpLEl", scope: !3282, file: !1093, line: 832, type: !3326, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3326 = !DISubroutineType(types: !3327)
!3327 = !{!3314, !3289, !3323}
!3328 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEplEl", scope: !3282, file: !1093, line: 836, type: !3329, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3329 = !DISubroutineType(types: !3330)
!3330 = !{!3282, !3304, !3323}
!3331 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEmIEl", scope: !3282, file: !1093, line: 840, type: !3326, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3332 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEmiEl", scope: !3282, file: !1093, line: 844, type: !3329, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3333 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEE4baseEv", scope: !3282, file: !1093, line: 848, type: !3334, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3334 = !DISubroutineType(types: !3335)
!3335 = !{!3293, !3304}
!3336 = !{!3302, !3337}
!3337 = !DITemplateTypeParameter(name: "_Container", type: !3281)
!3338 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3339, file: !2317, line: 100, baseType: !3285)
!3339 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<llvm::MachineBasicBlock *, void>", scope: !14, file: !2317, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3340, templateParams: !3430, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvEE")
!3340 = !{!3341, !3342, !3355, !3359, !3362, !3367, !3370, !3373, !3376, !3382, !3383, !3384, !3385, !3386, !3391, !3396, !3397, !3398, !3401, !3402, !3405, !3409, !3413, !3417, !3422, !3425, !3428, !3429}
!3341 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3339, baseType: !2321, flags: DIFlagPublic, extraData: i32 0)
!3342 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !3339, file: !2317, line: 74, baseType: !3343, size: 64, offset: 192)
!3343 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !3339, file: !2317, line: 73, baseType: !3344)
!3344 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<llvm::MachineBasicBlock *, char, char, char, char, char, char>", scope: !14, file: !2345, line: 199, size: 64, flags: DIFlagTypePassByValue, elements: !3345, templateParams: !3353, identifier: "_ZTSN4llvm21AlignedCharArrayUnionIPNS_17MachineBasicBlockEccccccEE")
!3345 = !{!3346}
!3346 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3344, baseType: !3347, extraData: i32 0)
!3347 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<8UL, 8UL>", scope: !14, file: !2345, line: 75, size: 64, flags: DIFlagTypePassByValue, elements: !3348, templateParams: !3351, identifier: "_ZTSN4llvm16AlignedCharArrayILm8ELm8EEE")
!3348 = !{!3349}
!3349 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !3347, file: !2345, line: 76, baseType: !3350, size: 64, align: 64)
!3350 = !DICompositeType(tag: DW_TAG_array_type, baseType: !319, size: 64, elements: !183)
!3351 = !{!2459, !3352}
!3352 = !DITemplateValueParameter(name: "Size", type: !642, value: i64 8)
!3353 = !{!3354, !2359, !2360, !2361, !2362, !2363, !2364}
!3354 = !DITemplateTypeParameter(name: "T1", type: !197)
!3355 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !3339, file: !2317, line: 78, type: !3356, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3356 = !DISubroutineType(types: !3357)
!3357 = !{null, !3358, !2102}
!3358 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3339, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3359 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE8grow_podEmm", scope: !3339, file: !2317, line: 80, type: !3360, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3360 = !DISubroutineType(types: !3361)
!3361 = !{null, !3358, !2102, !2102}
!3362 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE7isSmallEv", scope: !3339, file: !2317, line: 86, type: !3363, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3363 = !DISubroutineType(types: !3364)
!3364 = !{!145, !3365}
!3365 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3366, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3366 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3339)
!3367 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE12resetToSmallEv", scope: !3339, file: !2317, line: 91, type: !3368, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3368 = !DISubroutineType(types: !3369)
!3369 = !{null, !3358}
!3370 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE6setEndEPS2_", scope: !3339, file: !2317, line: 95, type: !3371, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3371 = !DISubroutineType(types: !3372)
!3372 = !{null, !3358, !3285}
!3373 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE5beginEv", scope: !3339, file: !2317, line: 112, type: !3374, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3374 = !DISubroutineType(types: !3375)
!3375 = !{!3338, !3358}
!3376 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE5beginEv", scope: !3339, file: !2317, line: 113, type: !3377, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3377 = !DISubroutineType(types: !3378)
!3378 = !{!3379, !3365}
!3379 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !3339, file: !2317, line: 101, baseType: !3380)
!3380 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3381, size: 64)
!3381 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !197)
!3382 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE3endEv", scope: !3339, file: !2317, line: 114, type: !3374, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3383 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE3endEv", scope: !3339, file: !2317, line: 115, type: !3377, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3384 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE12capacity_ptrEv", scope: !3339, file: !2317, line: 117, type: !3374, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3385 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE12capacity_ptrEv", scope: !3339, file: !2317, line: 118, type: !3377, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3386 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE6rbeginEv", scope: !3339, file: !2317, line: 122, type: !3387, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3387 = !DISubroutineType(types: !3388)
!3388 = !{!3389, !3358}
!3389 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !3339, file: !2317, line: 104, baseType: !3390)
!3390 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<llvm::MachineBasicBlock **>", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPPN4llvm17MachineBasicBlockEE")
!3391 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE6rbeginEv", scope: !3339, file: !2317, line: 123, type: !3392, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3392 = !DISubroutineType(types: !3393)
!3393 = !{!3394, !3365}
!3394 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !3339, file: !2317, line: 103, baseType: !3395)
!3395 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<llvm::MachineBasicBlock *const *>", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKPN4llvm17MachineBasicBlockEE")
!3396 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE4rendEv", scope: !3339, file: !2317, line: 124, type: !3387, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3397 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE4rendEv", scope: !3339, file: !2317, line: 125, type: !3392, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3398 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE4sizeEv", scope: !3339, file: !2317, line: 127, type: !3399, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3399 = !DISubroutineType(types: !3400)
!3400 = !{!2411, !3365}
!3401 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE8max_sizeEv", scope: !3339, file: !2317, line: 128, type: !3399, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3402 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE8capacityEv", scope: !3339, file: !2317, line: 132, type: !3403, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3403 = !DISubroutineType(types: !3404)
!3404 = !{!2102, !3365}
!3405 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE4dataEv", scope: !3339, file: !2317, line: 135, type: !3406, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3406 = !DISubroutineType(types: !3407)
!3407 = !{!3408, !3358}
!3408 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3339, file: !2317, line: 108, baseType: !3285)
!3409 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE4dataEv", scope: !3339, file: !2317, line: 137, type: !3410, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3410 = !DISubroutineType(types: !3411)
!3411 = !{!3412, !3365}
!3412 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !3339, file: !2317, line: 109, baseType: !3380)
!3413 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvEixEj", scope: !3339, file: !2317, line: 139, type: !3414, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3414 = !DISubroutineType(types: !3415)
!3415 = !{!3416, !3358, !6}
!3416 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3339, file: !2317, line: 106, baseType: !3303)
!3417 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvEixEj", scope: !3339, file: !2317, line: 143, type: !3418, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3418 = !DISubroutineType(types: !3419)
!3419 = !{!3420, !3365, !6}
!3420 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !3339, file: !2317, line: 107, baseType: !3421)
!3421 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3381, size: 64)
!3422 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE5frontEv", scope: !3339, file: !2317, line: 148, type: !3423, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3423 = !DISubroutineType(types: !3424)
!3424 = !{!3416, !3358}
!3425 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE5frontEv", scope: !3339, file: !2317, line: 152, type: !3426, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3426 = !DISubroutineType(types: !3427)
!3427 = !{!3420, !3365}
!3428 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE4backEv", scope: !3339, file: !2317, line: 157, type: !3423, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3429 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_17MachineBasicBlockEvE4backEv", scope: !3339, file: !2317, line: 161, type: !3426, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3430 = !{!3431, !2442}
!3431 = !DITemplateTypeParameter(name: "T", type: !197)
!3432 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3433, file: !2501, line: 344, baseType: !2500)
!3433 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "iplist<llvm::MachineInstr, llvm::ilist_traits<llvm::MachineInstr> >", scope: !14, file: !2501, line: 313, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm6iplistINS_12MachineInstrENS_12ilist_traitsIS1_EEEE")
!3434 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3435, file: !2501, line: 344, baseType: !3436)
!3435 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "iplist<llvm::MachineBasicBlock, llvm::ilist_traits<llvm::MachineBasicBlock> >", scope: !14, file: !2501, line: 313, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm6iplistINS_17MachineBasicBlockENS_12ilist_traitsIS1_EEEE")
!3436 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ilist_iterator<llvm::MachineBasicBlock>", scope: !14, file: !2501, line: 145, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3437, templateParams: !3493, identifier: "_ZTSN4llvm14ilist_iteratorINS_17MachineBasicBlockEEE")
!3437 = !{!3438, !3445, !3448, !3455, !3456, !3457, !3458, !3459, !3463, !3468, !3471, !3474, !3477, !3478, !3482, !3483, !3487, !3488, !3491, !3492}
!3438 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3436, baseType: !3439, flags: DIFlagPublic, extraData: i32 0)
!3439 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::bidirectional_iterator_tag, llvm::MachineBasicBlock, long, llvm::MachineBasicBlock *, llvm::MachineBasicBlock &>", scope: !839, file: !1110, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !3440, identifier: "_ZTSSt8iteratorISt26bidirectional_iterator_tagN4llvm17MachineBasicBlockElPS2_RS2_E")
!3440 = !{!2486, !3441, !2495, !3442, !3443}
!3441 = !DITemplateTypeParameter(name: "_Tp", type: !198)
!3442 = !DITemplateTypeParameter(name: "_Pointer", type: !197)
!3443 = !DITemplateTypeParameter(name: "_Reference", type: !3444)
!3444 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !198, size: 64)
!3445 = !DIDerivedType(tag: DW_TAG_member, name: "NodePtr", scope: !3436, file: !2501, line: 158, baseType: !3446, size: 64)
!3446 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3436, file: !2501, line: 155, baseType: !3447)
!3447 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3439, file: !1110, line: 127, baseType: !197)
!3448 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEixEl", scope: !3436, file: !2501, line: 164, type: !3449, scopeLine: 164, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3449 = !DISubroutineType(types: !3450)
!3450 = !{null, !3451, !3453}
!3451 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3452, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3452 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3436)
!3453 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !3436, file: !2501, line: 154, baseType: !3454)
!3454 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !3439, file: !1110, line: 125, baseType: !288)
!3455 = !DISubprogram(name: "operator+", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEplEl", scope: !3436, file: !2501, line: 165, type: !3449, scopeLine: 165, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3456 = !DISubprogram(name: "operator-", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEmiEl", scope: !3436, file: !2501, line: 166, type: !3449, scopeLine: 166, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3457 = !DISubprogram(name: "operator+=", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEpLEl", scope: !3436, file: !2501, line: 167, type: !3449, scopeLine: 167, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3458 = !DISubprogram(name: "operator-=", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEmIEl", scope: !3436, file: !2501, line: 168, type: !3449, scopeLine: 168, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3459 = !DISubprogram(name: "ilist_iterator", scope: !3436, file: !2501, line: 176, type: !3460, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3460 = !DISubroutineType(types: !3461)
!3461 = !{null, !3462, !3446}
!3462 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3436, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3463 = !DISubprogram(name: "ilist_iterator", scope: !3436, file: !2501, line: 177, type: !3464, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3464 = !DISubroutineType(types: !3465)
!3465 = !{null, !3462, !3466}
!3466 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3436, file: !2501, line: 156, baseType: !3467)
!3467 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3439, file: !1110, line: 129, baseType: !3444)
!3468 = !DISubprogram(name: "ilist_iterator", scope: !3436, file: !2501, line: 178, type: !3469, scopeLine: 178, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3469 = !DISubroutineType(types: !3470)
!3470 = !{null, !3462}
!3471 = !DISubprogram(name: "operator llvm::MachineBasicBlock *", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEcvPS1_Ev", scope: !3436, file: !2501, line: 195, type: !3472, scopeLine: 195, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3472 = !DISubroutineType(types: !3473)
!3473 = !{!3446, !3451}
!3474 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEdeEv", scope: !3436, file: !2501, line: 199, type: !3475, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3475 = !DISubroutineType(types: !3476)
!3476 = !{!3466, !3451}
!3477 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEptEv", scope: !3436, file: !2501, line: 202, type: !3472, scopeLine: 202, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3478 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEeqERKS2_", scope: !3436, file: !2501, line: 205, type: !3479, scopeLine: 205, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3479 = !DISubroutineType(types: !3480)
!3480 = !{!145, !3451, !3481}
!3481 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3452, size: 64)
!3482 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEneERKS2_", scope: !3436, file: !2501, line: 208, type: !3479, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3483 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorINS_17MachineBasicBlockEEmmEv", scope: !3436, file: !2501, line: 213, type: !3484, scopeLine: 213, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3484 = !DISubroutineType(types: !3485)
!3485 = !{!3486, !3462}
!3486 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3436, size: 64)
!3487 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorINS_17MachineBasicBlockEEppEv", scope: !3436, file: !2501, line: 218, type: !3484, scopeLine: 218, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3488 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorINS_17MachineBasicBlockEEmmEi", scope: !3436, file: !2501, line: 222, type: !3489, scopeLine: 222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3489 = !DISubroutineType(types: !3490)
!3490 = !{!3436, !3462, !32}
!3491 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorINS_17MachineBasicBlockEEppEi", scope: !3436, file: !2501, line: 227, type: !3489, scopeLine: 227, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3492 = !DISubprogram(name: "getNodePtrUnchecked", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEE19getNodePtrUncheckedEv", scope: !3436, file: !2501, line: 234, type: !3472, scopeLine: 234, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3493 = !{!3494}
!3494 = !DITemplateTypeParameter(name: "NodeTy", type: !198)
!3495 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !3281, file: !838, line: 371, baseType: !3496)
!3496 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<llvm::MachineBasicBlock *const *, std::vector<llvm::MachineBasicBlock *, std::allocator<llvm::MachineBasicBlock *> > >", scope: !5, file: !1093, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3497, templateParams: !3548, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPKPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEE")
!3497 = !{!3498, !3499, !3503, !3508, !3518, !3523, !3527, !3530, !3531, !3532, !3537, !3540, !3543, !3544, !3545}
!3498 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !3496, file: !1093, line: 767, baseType: !3380, size: 64, flags: DIFlagProtected)
!3499 = !DISubprogram(name: "__normal_iterator", scope: !3496, file: !1093, line: 779, type: !3500, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3500 = !DISubroutineType(types: !3501)
!3501 = !{null, !3502}
!3502 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3496, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3503 = !DISubprogram(name: "__normal_iterator", scope: !3496, file: !1093, line: 783, type: !3504, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3504 = !DISubroutineType(types: !3505)
!3505 = !{null, !3502, !3506}
!3506 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3507, size: 64)
!3507 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3380)
!3508 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEdeEv", scope: !3496, file: !1093, line: 796, type: !3509, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3509 = !DISubroutineType(types: !3510)
!3510 = !{!3511, !3516}
!3511 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3496, file: !1093, line: 776, baseType: !3512)
!3512 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3513, file: !1110, line: 195, baseType: !3421)
!3513 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<llvm::MachineBasicBlock *const *>", scope: !839, file: !1110, line: 189, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !3514, identifier: "_ZTSSt15iterator_traitsIPKPN4llvm17MachineBasicBlockEE")
!3514 = !{!3515}
!3515 = !DITemplateTypeParameter(name: "_Iterator", type: !3380)
!3516 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3517, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3517 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3496)
!3518 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEptEv", scope: !3496, file: !1093, line: 800, type: !3519, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3519 = !DISubroutineType(types: !3520)
!3520 = !{!3521, !3516}
!3521 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3496, file: !1093, line: 777, baseType: !3522)
!3522 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3513, file: !1110, line: 194, baseType: !3380)
!3523 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEppEv", scope: !3496, file: !1093, line: 804, type: !3524, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3524 = !DISubroutineType(types: !3525)
!3525 = !{!3526, !3502}
!3526 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3496, size: 64)
!3527 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEppEi", scope: !3496, file: !1093, line: 811, type: !3528, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3528 = !DISubroutineType(types: !3529)
!3529 = !{!3496, !3502, !32}
!3530 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEmmEv", scope: !3496, file: !1093, line: 816, type: !3524, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3531 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEmmEi", scope: !3496, file: !1093, line: 823, type: !3528, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3532 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEixEl", scope: !3496, file: !1093, line: 828, type: !3533, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3533 = !DISubroutineType(types: !3534)
!3534 = !{!3511, !3516, !3535}
!3535 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !3496, file: !1093, line: 775, baseType: !3536)
!3536 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !3513, file: !1110, line: 193, baseType: !1135)
!3537 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEpLEl", scope: !3496, file: !1093, line: 832, type: !3538, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3538 = !DISubroutineType(types: !3539)
!3539 = !{!3526, !3502, !3535}
!3540 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEplEl", scope: !3496, file: !1093, line: 836, type: !3541, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3541 = !DISubroutineType(types: !3542)
!3542 = !{!3496, !3516, !3535}
!3543 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEmIEl", scope: !3496, file: !1093, line: 840, type: !3538, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3544 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEEmiEl", scope: !3496, file: !1093, line: 844, type: !3541, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3545 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKPN4llvm17MachineBasicBlockESt6vectorIS3_SaIS3_EEE4baseEv", scope: !3496, file: !1093, line: 848, type: !3546, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3546 = !DISubroutineType(types: !3547)
!3547 = !{!3506, !3516}
!3548 = !{!3515, !3337}
!3549 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3550, file: !2317, line: 100, baseType: !307)
!3550 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<llvm::MachineOperand, void>", scope: !14, file: !2317, line: 66, size: 448, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3551, templateParams: !3642, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvEE")
!3551 = !{!3552, !3553, !3568, !3572, !3575, !3580, !3583, !3586, !3589, !3594, !3595, !3596, !3597, !3598, !3603, !3608, !3609, !3610, !3613, !3614, !3617, !3621, !3625, !3630, !3634, !3637, !3640, !3641}
!3552 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3550, baseType: !2321, flags: DIFlagPublic, extraData: i32 0)
!3553 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !3550, file: !2317, line: 74, baseType: !3554, size: 256, offset: 192)
!3554 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !3550, file: !2317, line: 73, baseType: !3555)
!3555 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<llvm::MachineOperand, char, char, char, char, char, char>", scope: !14, file: !2345, line: 199, size: 256, flags: DIFlagTypePassByValue, elements: !3556, templateParams: !3566, identifier: "_ZTSN4llvm21AlignedCharArrayUnionINS_14MachineOperandEccccccEE")
!3556 = !{!3557}
!3557 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3555, baseType: !3558, extraData: i32 0)
!3558 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<8UL, 32UL>", scope: !14, file: !2345, line: 75, size: 256, flags: DIFlagTypePassByValue, elements: !3559, templateParams: !3564, identifier: "_ZTSN4llvm16AlignedCharArrayILm8ELm32EEE")
!3559 = !{!3560}
!3560 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !3558, file: !2345, line: 76, baseType: !3561, size: 256, align: 64)
!3561 = !DICompositeType(tag: DW_TAG_array_type, baseType: !319, size: 256, elements: !3562)
!3562 = !{!3563}
!3563 = !DISubrange(count: 32)
!3564 = !{!2459, !3565}
!3565 = !DITemplateValueParameter(name: "Size", type: !642, value: i64 32)
!3566 = !{!3567, !2359, !2360, !2361, !2362, !2363, !2364}
!3567 = !DITemplateTypeParameter(name: "T1", type: !248)
!3568 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !3550, file: !2317, line: 78, type: !3569, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3569 = !DISubroutineType(types: !3570)
!3570 = !{null, !3571, !2102}
!3571 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3550, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3572 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE8grow_podEmm", scope: !3550, file: !2317, line: 80, type: !3573, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3573 = !DISubroutineType(types: !3574)
!3574 = !{null, !3571, !2102, !2102}
!3575 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE7isSmallEv", scope: !3550, file: !2317, line: 86, type: !3576, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3576 = !DISubroutineType(types: !3577)
!3577 = !{!145, !3578}
!3578 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3579, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3579 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3550)
!3580 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE12resetToSmallEv", scope: !3550, file: !2317, line: 91, type: !3581, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3581 = !DISubroutineType(types: !3582)
!3582 = !{null, !3571}
!3583 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE6setEndEPS1_", scope: !3550, file: !2317, line: 95, type: !3584, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3584 = !DISubroutineType(types: !3585)
!3585 = !{null, !3571, !307}
!3586 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE5beginEv", scope: !3550, file: !2317, line: 112, type: !3587, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3587 = !DISubroutineType(types: !3588)
!3588 = !{!3549, !3571}
!3589 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE5beginEv", scope: !3550, file: !2317, line: 113, type: !3590, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3590 = !DISubroutineType(types: !3591)
!3591 = !{!3592, !3578}
!3592 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !3550, file: !2317, line: 101, baseType: !3593)
!3593 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !338, size: 64)
!3594 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE3endEv", scope: !3550, file: !2317, line: 114, type: !3587, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3595 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE3endEv", scope: !3550, file: !2317, line: 115, type: !3590, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3596 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE12capacity_ptrEv", scope: !3550, file: !2317, line: 117, type: !3587, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3597 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE12capacity_ptrEv", scope: !3550, file: !2317, line: 118, type: !3590, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3598 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE6rbeginEv", scope: !3550, file: !2317, line: 122, type: !3599, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3599 = !DISubroutineType(types: !3600)
!3600 = !{!3601, !3571}
!3601 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !3550, file: !2317, line: 104, baseType: !3602)
!3602 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<llvm::MachineOperand *>", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPN4llvm14MachineOperandEE")
!3603 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE6rbeginEv", scope: !3550, file: !2317, line: 123, type: !3604, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3604 = !DISubroutineType(types: !3605)
!3605 = !{!3606, !3578}
!3606 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !3550, file: !2317, line: 103, baseType: !3607)
!3607 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const llvm::MachineOperand *>", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKN4llvm14MachineOperandEE")
!3608 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE4rendEv", scope: !3550, file: !2317, line: 124, type: !3599, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3609 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE4rendEv", scope: !3550, file: !2317, line: 125, type: !3604, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3610 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE4sizeEv", scope: !3550, file: !2317, line: 127, type: !3611, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3611 = !DISubroutineType(types: !3612)
!3612 = !{!2411, !3578}
!3613 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE8max_sizeEv", scope: !3550, file: !2317, line: 128, type: !3611, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3614 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE8capacityEv", scope: !3550, file: !2317, line: 132, type: !3615, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3615 = !DISubroutineType(types: !3616)
!3616 = !{!2102, !3578}
!3617 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE4dataEv", scope: !3550, file: !2317, line: 135, type: !3618, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3618 = !DISubroutineType(types: !3619)
!3619 = !{!3620, !3571}
!3620 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3550, file: !2317, line: 108, baseType: !307)
!3621 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE4dataEv", scope: !3550, file: !2317, line: 137, type: !3622, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3622 = !DISubroutineType(types: !3623)
!3623 = !{!3624, !3578}
!3624 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !3550, file: !2317, line: 109, baseType: !3593)
!3625 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvEixEj", scope: !3550, file: !2317, line: 139, type: !3626, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3626 = !DISubroutineType(types: !3627)
!3627 = !{!3628, !3571, !6}
!3628 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3550, file: !2317, line: 106, baseType: !3629)
!3629 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !248, size: 64)
!3630 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvEixEj", scope: !3550, file: !2317, line: 143, type: !3631, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3631 = !DISubroutineType(types: !3632)
!3632 = !{!3633, !3578, !6}
!3633 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !3550, file: !2317, line: 107, baseType: !473)
!3634 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE5frontEv", scope: !3550, file: !2317, line: 148, type: !3635, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3635 = !DISubroutineType(types: !3636)
!3636 = !{!3628, !3571}
!3637 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE5frontEv", scope: !3550, file: !2317, line: 152, type: !3638, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3638 = !DISubroutineType(types: !3639)
!3639 = !{!3633, !3578}
!3640 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE4backEv", scope: !3550, file: !2317, line: 157, type: !3635, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3641 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonINS_14MachineOperandEvE4backEv", scope: !3550, file: !2317, line: 161, type: !3638, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3642 = !{!3643, !2442}
!3643 = !DITemplateTypeParameter(name: "T", type: !248)
!3644 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2914, file: !2915, line: 303, baseType: !3645)
!3645 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3646, file: !2501, line: 642, baseType: !3434)
!3646 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ilist<llvm::MachineBasicBlock>", scope: !14, file: !2501, line: 640, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm5ilistINS_17MachineBasicBlockEEE")
!3647 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3648, size: 64)
!3648 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !3649, file: !1363, line: 540, baseType: !3865)
!3649 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMap<unsigned int, char, llvm::DenseMapInfo<unsigned int> >", scope: !14, file: !1363, line: 534, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3650, templateParams: !3986, identifier: "_ZTSN4llvm8DenseMapIjcNS_12DenseMapInfoIjEEEE")
!3650 = !{!3651, !3938, !3939, !3940, !3941, !3942, !3946, !3951, !3955, !3958, !3962, !3965, !3968, !3969, !3970, !3971, !3972, !3976, !3977, !3978, !3979, !3982, !3983}
!3651 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3649, baseType: !3652, flags: DIFlagPublic, extraData: i32 0)
!3652 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapBase<llvm::DenseMap<unsigned int, char, llvm::DenseMapInfo<unsigned int> >, unsigned int, char, llvm::DenseMapInfo<unsigned int> >", scope: !14, file: !1363, line: 41, size: 8, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3653, templateParams: !3936, identifier: "_ZTSN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_EE")
!3653 = !{!3654, !3763, !3764, !3770, !3771, !3774, !3777, !3780, !3783, !3786, !3789, !3792, !3795, !3851, !3854, !3857, !3860, !3866, !3870, !3873, !3876, !3879, !3882, !3883, !3884, !3885, !3889, !3893, !3894, !3895, !3896, !3897, !3900, !3901, !3902, !3903, !3904, !3905, !3906, !3911, !3914, !3915, !3916, !3917, !3918, !3919, !3923, !3927, !3930, !3933}
!3654 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E5beginEv", scope: !3652, file: !1363, line: 53, type: !3655, scopeLine: 53, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3655 = !DISubroutineType(types: !3656)
!3656 = !{!3657, !3762}
!3657 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3652, file: !1363, line: 50, baseType: !3658)
!3658 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapIterator<unsigned int, char, llvm::DenseMapInfo<unsigned int>, false>", scope: !14, file: !1363, line: 987, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3659, templateParams: !3760, identifier: "_ZTSN4llvm16DenseMapIteratorIjcNS_12DenseMapInfoIjEELb0EEE")
!3659 = !{!3660, !3722, !3723, !3727, !3730, !3735, !3741, !3744, !3751, !3752, !3756, !3759}
!3660 = !DIDerivedType(tag: DW_TAG_member, name: "Ptr", scope: !3658, file: !1363, line: 999, baseType: !3661, size: 64)
!3661 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3658, file: !1363, line: 995, baseType: !3662)
!3662 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3663, size: 64)
!3663 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !3658, file: !1363, line: 994, baseType: !3664)
!3664 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !3665, file: !1380, line: 236, baseType: !3669)
!3665 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<false, const std::pair<unsigned int, char>, std::pair<unsigned int, char> >", scope: !14, file: !1380, line: 236, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !3666, identifier: "_ZTSN4llvm11conditionalILb0EKSt4pairIjcES2_EE")
!3666 = !{!1383, !3667, !3721}
!3667 = !DITemplateTypeParameter(name: "T", type: !3668)
!3668 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3669)
!3669 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<unsigned int, char>", scope: !839, file: !1387, line: 208, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3670, templateParams: !3719, identifier: "_ZTSSt4pairIjcE")
!3670 = !{!3671, !3690, !3691, !3692, !3697, !3701, !3709, !3716}
!3671 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3669, baseType: !3672, flags: DIFlagPrivate, extraData: i32 0)
!3672 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<unsigned int, char>", scope: !839, file: !1387, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !3673, templateParams: !3688, identifier: "_ZTSSt11__pair_baseIjcE")
!3673 = !{!3674, !3678, !3679, !3684}
!3674 = !DISubprogram(name: "__pair_base", scope: !3672, file: !1387, line: 194, type: !3675, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3675 = !DISubroutineType(types: !3676)
!3676 = !{null, !3677}
!3677 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3672, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3678 = !DISubprogram(name: "~__pair_base", scope: !3672, file: !1387, line: 195, type: !3675, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3679 = !DISubprogram(name: "__pair_base", scope: !3672, file: !1387, line: 196, type: !3680, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3680 = !DISubroutineType(types: !3681)
!3681 = !{null, !3677, !3682}
!3682 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3683, size: 64)
!3683 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3672)
!3684 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIjcEaSERKS0_", scope: !3672, file: !1387, line: 197, type: !3685, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!3685 = !DISubroutineType(types: !3686)
!3686 = !{!3687, !3677, !3682}
!3687 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3672, size: 64)
!3688 = !{!1407, !3689}
!3689 = !DITemplateTypeParameter(name: "_U2", type: !319)
!3690 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !3669, file: !1387, line: 214, baseType: !6, size: 32)
!3691 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !3669, file: !1387, line: 215, baseType: !319, size: 8, offset: 32)
!3692 = !DISubprogram(name: "pair", scope: !3669, file: !1387, line: 303, type: !3693, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3693 = !DISubroutineType(types: !3694)
!3694 = !{null, !3695, !3696}
!3695 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3669, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3696 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3668, size: 64)
!3697 = !DISubprogram(name: "pair", scope: !3669, file: !1387, line: 304, type: !3698, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3698 = !DISubroutineType(types: !3699)
!3699 = !{null, !3695, !3700}
!3700 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3669, size: 64)
!3701 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIjcEaSERKS0_", scope: !3669, file: !1387, line: 378, type: !3702, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3702 = !DISubroutineType(types: !3703)
!3703 = !{!3704, !3695, !3705}
!3704 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3669, size: 64)
!3705 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !3706, file: !1281, line: 1928, baseType: !3696)
!3706 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<unsigned int, char> &, const std::__nonesuch_no_braces &>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !3707, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIjcERKSt20__nonesuch_no_bracesE")
!3707 = !{!1472, !3708, !1474}
!3708 = !DITemplateTypeParameter(name: "_Iftrue", type: !3696)
!3709 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIjcEaSEOS0_", scope: !3669, file: !1387, line: 389, type: !3710, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3710 = !DISubroutineType(types: !3711)
!3711 = !{!3704, !3695, !3712}
!3712 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !3713, file: !1281, line: 1928, baseType: !3700)
!3713 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<unsigned int, char> &&, std::__nonesuch_no_braces &&>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !3714, identifier: "_ZTSSt11conditionalILb1EOSt4pairIjcEOSt20__nonesuch_no_bracesE")
!3714 = !{!1472, !3715, !1485}
!3715 = !DITemplateTypeParameter(name: "_Iftrue", type: !3700)
!3716 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIjcE4swapERS0_", scope: !3669, file: !1387, line: 424, type: !3717, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3717 = !DISubroutineType(types: !3718)
!3718 = !{null, !3695, !3704}
!3719 = !{!1974, !3720}
!3720 = !DITemplateTypeParameter(name: "_T2", type: !319)
!3721 = !DITemplateTypeParameter(name: "F", type: !3669)
!3722 = !DIDerivedType(tag: DW_TAG_member, name: "End", scope: !3658, file: !1363, line: 999, baseType: !3661, size: 64, offset: 64)
!3723 = !DISubprogram(name: "DenseMapIterator", scope: !3658, file: !1363, line: 1001, type: !3724, scopeLine: 1001, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3724 = !DISubroutineType(types: !3725)
!3725 = !{null, !3726}
!3726 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3658, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3727 = !DISubprogram(name: "DenseMapIterator", scope: !3658, file: !1363, line: 1003, type: !3728, scopeLine: 1003, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3728 = !DISubroutineType(types: !3729)
!3729 = !{null, !3726, !3661, !3661, !145}
!3730 = !DISubprogram(name: "DenseMapIterator", scope: !3658, file: !1363, line: 1011, type: !3731, scopeLine: 1011, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3731 = !DISubroutineType(types: !3732)
!3732 = !{null, !3726, !3733}
!3733 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3734, size: 64)
!3734 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3658)
!3735 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm16DenseMapIteratorIjcNS_12DenseMapInfoIjEELb0EEdeEv", scope: !3658, file: !1363, line: 1015, type: !3736, scopeLine: 1015, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3736 = !DISubroutineType(types: !3737)
!3737 = !{!3738, !3740}
!3738 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3658, file: !1363, line: 996, baseType: !3739)
!3739 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3663, size: 64)
!3740 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3734, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3741 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm16DenseMapIteratorIjcNS_12DenseMapInfoIjEELb0EEptEv", scope: !3658, file: !1363, line: 1018, type: !3742, scopeLine: 1018, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3742 = !DISubroutineType(types: !3743)
!3743 = !{!3661, !3740}
!3744 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm16DenseMapIteratorIjcNS_12DenseMapInfoIjEELb0EEeqERKNS0_IjcS2_Lb1EEE", scope: !3658, file: !1363, line: 1022, type: !3745, scopeLine: 1022, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3745 = !DISubroutineType(types: !3746)
!3746 = !{!145, !3740, !3747}
!3747 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3748, size: 64)
!3748 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3749)
!3749 = !DIDerivedType(tag: DW_TAG_typedef, name: "ConstIterator", scope: !3658, file: !1363, line: 990, baseType: !3750)
!3750 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapIterator<unsigned int, char, llvm::DenseMapInfo<unsigned int>, true>", scope: !14, file: !1363, line: 37, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm16DenseMapIteratorIjcNS_12DenseMapInfoIjEELb1EEE")
!3751 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm16DenseMapIteratorIjcNS_12DenseMapInfoIjEELb0EEneERKNS0_IjcS2_Lb1EEE", scope: !3658, file: !1363, line: 1025, type: !3745, scopeLine: 1025, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3752 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIjcNS_12DenseMapInfoIjEELb0EEppEv", scope: !3658, file: !1363, line: 1029, type: !3753, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3753 = !DISubroutineType(types: !3754)
!3754 = !{!3755, !3726}
!3755 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3658, size: 64)
!3756 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIjcNS_12DenseMapInfoIjEELb0EEppEi", scope: !3658, file: !1363, line: 1034, type: !3757, scopeLine: 1034, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3757 = !DISubroutineType(types: !3758)
!3758 = !{!3658, !3726, !32}
!3759 = !DISubprogram(name: "AdvancePastEmptyBuckets", linkageName: "_ZN4llvm16DenseMapIteratorIjcNS_12DenseMapInfoIjEELb0EE23AdvancePastEmptyBucketsEv", scope: !3658, file: !1363, line: 1039, type: !3724, scopeLine: 1039, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3760 = !{!2052, !3761, !2054, !2083}
!3761 = !DITemplateTypeParameter(name: "ValueT", type: !319)
!3762 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3652, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3763 = !DISubprogram(name: "end", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E3endEv", scope: !3652, file: !1363, line: 57, type: !3655, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3764 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E5beginEv", scope: !3652, file: !1363, line: 60, type: !3765, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3765 = !DISubroutineType(types: !3766)
!3766 = !{!3767, !3768}
!3767 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !3652, file: !1363, line: 52, baseType: !3750)
!3768 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3769, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3769 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3652)
!3770 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E3endEv", scope: !3652, file: !1363, line: 63, type: !3765, scopeLine: 63, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3771 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E5emptyEv", scope: !3652, file: !1363, line: 67, type: !3772, scopeLine: 67, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3772 = !DISubroutineType(types: !3773)
!3773 = !{!145, !3768}
!3774 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E4sizeEv", scope: !3652, file: !1363, line: 70, type: !3775, scopeLine: 70, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3775 = !DISubroutineType(types: !3776)
!3776 = !{!6, !3768}
!3777 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E6resizeEm", scope: !3652, file: !1363, line: 73, type: !3778, scopeLine: 73, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3778 = !DISubroutineType(types: !3779)
!3779 = !{null, !3762, !2102}
!3780 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E5clearEv", scope: !3652, file: !1363, line: 78, type: !3781, scopeLine: 78, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3781 = !DISubroutineType(types: !3782)
!3782 = !{null, !3762}
!3783 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E5countERKj", scope: !3652, file: !1363, line: 103, type: !3784, scopeLine: 103, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3784 = !DISubroutineType(types: !3785)
!3785 = !{!145, !3768, !2065}
!3786 = !DISubprogram(name: "find", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E4findERKj", scope: !3652, file: !1363, line: 108, type: !3787, scopeLine: 108, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3787 = !DISubroutineType(types: !3788)
!3788 = !{!3657, !3762, !2065}
!3789 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E4findERKj", scope: !3652, file: !1363, line: 114, type: !3790, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3790 = !DISubroutineType(types: !3791)
!3791 = !{!3767, !3768, !2065}
!3792 = !DISubprogram(name: "lookup", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E6lookupERKj", scope: !3652, file: !1363, line: 143, type: !3793, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3793 = !DISubroutineType(types: !3794)
!3794 = !{!319, !3768, !2065}
!3795 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E6insertERKSt4pairIjcE", scope: !3652, file: !1363, line: 153, type: !3796, scopeLine: 153, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3796 = !DISubroutineType(types: !3797)
!3797 = !{!3798, !3762, !3696}
!3798 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::DenseMapIterator<unsigned int, char, llvm::DenseMapInfo<unsigned int>, false>, bool>", scope: !839, file: !1387, line: 208, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3799, templateParams: !3849, identifier: "_ZTSSt4pairIN4llvm16DenseMapIteratorIjcNS0_12DenseMapInfoIjEELb0EEEbE")
!3799 = !{!3800, !3819, !3820, !3821, !3827, !3831, !3839, !3846}
!3800 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3798, baseType: !3801, flags: DIFlagPrivate, extraData: i32 0)
!3801 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::DenseMapIterator<unsigned int, char, llvm::DenseMapInfo<unsigned int>, false>, bool>", scope: !839, file: !1387, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !3802, templateParams: !3817, identifier: "_ZTSSt11__pair_baseIN4llvm16DenseMapIteratorIjcNS0_12DenseMapInfoIjEELb0EEEbE")
!3802 = !{!3803, !3807, !3808, !3813}
!3803 = !DISubprogram(name: "__pair_base", scope: !3801, file: !1387, line: 194, type: !3804, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3804 = !DISubroutineType(types: !3805)
!3805 = !{null, !3806}
!3806 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3801, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3807 = !DISubprogram(name: "~__pair_base", scope: !3801, file: !1387, line: 195, type: !3804, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3808 = !DISubprogram(name: "__pair_base", scope: !3801, file: !1387, line: 196, type: !3809, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3809 = !DISubroutineType(types: !3810)
!3810 = !{null, !3806, !3811}
!3811 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3812, size: 64)
!3812 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3801)
!3813 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN4llvm16DenseMapIteratorIjcNS0_12DenseMapInfoIjEELb0EEEbEaSERKS5_", scope: !3801, file: !1387, line: 197, type: !3814, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!3814 = !DISubroutineType(types: !3815)
!3815 = !{!3816, !3806, !3811}
!3816 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3801, size: 64)
!3817 = !{!3818, !2143}
!3818 = !DITemplateTypeParameter(name: "_U1", type: !3658)
!3819 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !3798, file: !1387, line: 214, baseType: !3658, size: 128)
!3820 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !3798, file: !1387, line: 215, baseType: !145, size: 8, offset: 128)
!3821 = !DISubprogram(name: "pair", scope: !3798, file: !1387, line: 303, type: !3822, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3822 = !DISubroutineType(types: !3823)
!3823 = !{null, !3824, !3825}
!3824 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3798, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3825 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3826, size: 64)
!3826 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3798)
!3827 = !DISubprogram(name: "pair", scope: !3798, file: !1387, line: 304, type: !3828, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3828 = !DISubroutineType(types: !3829)
!3829 = !{null, !3824, !3830}
!3830 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3798, size: 64)
!3831 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm16DenseMapIteratorIjcNS0_12DenseMapInfoIjEELb0EEEbEaSERKS5_", scope: !3798, file: !1387, line: 378, type: !3832, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3832 = !DISubroutineType(types: !3833)
!3833 = !{!3834, !3824, !3835}
!3834 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3798, size: 64)
!3835 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !3836, file: !1281, line: 1928, baseType: !3825)
!3836 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::DenseMapIterator<unsigned int, char, llvm::DenseMapInfo<unsigned int>, false>, bool> &, const std::__nonesuch_no_braces &>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !3837, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN4llvm16DenseMapIteratorIjcNS1_12DenseMapInfoIjEELb0EEEbERKSt20__nonesuch_no_bracesE")
!3837 = !{!1472, !3838, !1474}
!3838 = !DITemplateTypeParameter(name: "_Iftrue", type: !3825)
!3839 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm16DenseMapIteratorIjcNS0_12DenseMapInfoIjEELb0EEEbEaSEOS5_", scope: !3798, file: !1387, line: 389, type: !3840, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3840 = !DISubroutineType(types: !3841)
!3841 = !{!3834, !3824, !3842}
!3842 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !3843, file: !1281, line: 1928, baseType: !3830)
!3843 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::DenseMapIterator<unsigned int, char, llvm::DenseMapInfo<unsigned int>, false>, bool> &&, std::__nonesuch_no_braces &&>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !3844, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN4llvm16DenseMapIteratorIjcNS1_12DenseMapInfoIjEELb0EEEbEOSt20__nonesuch_no_bracesE")
!3844 = !{!1472, !3845, !1485}
!3845 = !DITemplateTypeParameter(name: "_Iftrue", type: !3830)
!3846 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN4llvm16DenseMapIteratorIjcNS0_12DenseMapInfoIjEELb0EEEbE4swapERS5_", scope: !3798, file: !1387, line: 424, type: !3847, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3847 = !DISubroutineType(types: !3848)
!3848 = !{null, !3824, !3834}
!3849 = !{!3850, !2176}
!3850 = !DITemplateTypeParameter(name: "_T1", type: !3658)
!3851 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E6insertEOSt4pairIjcE", scope: !3652, file: !1363, line: 168, type: !3852, scopeLine: 168, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3852 = !DISubroutineType(types: !3853)
!3853 = !{!3798, !3762, !3700}
!3854 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E5eraseERKj", scope: !3652, file: !1363, line: 190, type: !3855, scopeLine: 190, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3855 = !DISubroutineType(types: !3856)
!3856 = !{!145, !3762, !2065}
!3857 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E5eraseENS_16DenseMapIteratorIjcS3_Lb0EEE", scope: !3652, file: !1363, line: 201, type: !3858, scopeLine: 201, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3858 = !DISubroutineType(types: !3859)
!3859 = !{null, !3762, !3657}
!3860 = !DISubprogram(name: "FindAndConstruct", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E16FindAndConstructERKj", scope: !3652, file: !1363, line: 209, type: !3861, scopeLine: 209, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3861 = !DISubroutineType(types: !3862)
!3862 = !{!3863, !3762, !2065}
!3863 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3864, size: 64)
!3864 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !3652, file: !1363, line: 48, baseType: !3865)
!3865 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !3652, file: !1363, line: 43, baseType: !3669)
!3866 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_EixERKj", scope: !3652, file: !1363, line: 217, type: !3867, scopeLine: 217, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3867 = !DISubroutineType(types: !3868)
!3868 = !{!3869, !3762, !2065}
!3869 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !319, size: 64)
!3870 = !DISubprogram(name: "FindAndConstruct", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E16FindAndConstructEOj", scope: !3652, file: !1363, line: 222, type: !3871, scopeLine: 222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3871 = !DISubroutineType(types: !3872)
!3872 = !{!3863, !3762, !2198}
!3873 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_EixEOj", scope: !3652, file: !1363, line: 230, type: !3874, scopeLine: 230, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3874 = !DISubroutineType(types: !3875)
!3875 = !{!3869, !3762, !2198}
!3876 = !DISubprogram(name: "isPointerIntoBucketsArray", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E25isPointerIntoBucketsArrayEPKv", scope: !3652, file: !1363, line: 238, type: !3877, scopeLine: 238, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3877 = !DISubroutineType(types: !3878)
!3878 = !{!145, !3768, !124}
!3879 = !DISubprogram(name: "getPointerIntoBucketsArray", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E26getPointerIntoBucketsArrayEv", scope: !3652, file: !1363, line: 245, type: !3880, scopeLine: 245, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3880 = !DISubroutineType(types: !3881)
!3881 = !{!124, !3768}
!3882 = !DISubprogram(name: "DenseMapBase", scope: !3652, file: !1363, line: 248, type: !3781, scopeLine: 248, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3883 = !DISubprogram(name: "destroyAll", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E10destroyAllEv", scope: !3652, file: !1363, line: 250, type: !3781, scopeLine: 250, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3884 = !DISubprogram(name: "initEmpty", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E9initEmptyEv", scope: !3652, file: !1363, line: 267, type: !3781, scopeLine: 267, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3885 = !DISubprogram(name: "moveFromOldBuckets", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E18moveFromOldBucketsEPSt4pairIjcES8_", scope: !3652, file: !1363, line: 278, type: !3886, scopeLine: 278, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3886 = !DISubroutineType(types: !3887)
!3887 = !{null, !3762, !3888, !3888}
!3888 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3865, size: 64)
!3889 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E4swapERS5_", scope: !3652, file: !1363, line: 328, type: !3890, scopeLine: 328, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3890 = !DISubroutineType(types: !3891)
!3891 = !{null, !3762, !3892}
!3892 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3652, size: 64)
!3893 = !DISubprogram(name: "getHashValue", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E12getHashValueERKj", scope: !3652, file: !1363, line: 333, type: !2063, scopeLine: 333, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3894 = !DISubprogram(name: "getEmptyKey", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E11getEmptyKeyEv", scope: !3652, file: !1363, line: 340, type: !2221, scopeLine: 340, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3895 = !DISubprogram(name: "getTombstoneKey", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E15getTombstoneKeyEv", scope: !3652, file: !1363, line: 343, type: !2221, scopeLine: 343, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3896 = !DISubprogram(name: "getNumEntries", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E13getNumEntriesEv", scope: !3652, file: !1363, line: 348, type: !3775, scopeLine: 348, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3897 = !DISubprogram(name: "setNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E13setNumEntriesEj", scope: !3652, file: !1363, line: 351, type: !3898, scopeLine: 351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3898 = !DISubroutineType(types: !3899)
!3899 = !{null, !3762, !6}
!3900 = !DISubprogram(name: "incrementNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E19incrementNumEntriesEv", scope: !3652, file: !1363, line: 354, type: !3781, scopeLine: 354, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3901 = !DISubprogram(name: "decrementNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E19decrementNumEntriesEv", scope: !3652, file: !1363, line: 357, type: !3781, scopeLine: 357, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3902 = !DISubprogram(name: "getNumTombstones", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E16getNumTombstonesEv", scope: !3652, file: !1363, line: 360, type: !3775, scopeLine: 360, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3903 = !DISubprogram(name: "setNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E16setNumTombstonesEj", scope: !3652, file: !1363, line: 363, type: !3898, scopeLine: 363, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3904 = !DISubprogram(name: "incrementNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E22incrementNumTombstonesEv", scope: !3652, file: !1363, line: 366, type: !3781, scopeLine: 366, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3905 = !DISubprogram(name: "decrementNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E22decrementNumTombstonesEv", scope: !3652, file: !1363, line: 369, type: !3781, scopeLine: 369, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3906 = !DISubprogram(name: "getBuckets", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E10getBucketsEv", scope: !3652, file: !1363, line: 372, type: !3907, scopeLine: 372, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3907 = !DISubroutineType(types: !3908)
!3908 = !{!3909, !3768}
!3909 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3910, size: 64)
!3910 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3865)
!3911 = !DISubprogram(name: "getBuckets", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E10getBucketsEv", scope: !3652, file: !1363, line: 375, type: !3912, scopeLine: 375, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3912 = !DISubroutineType(types: !3913)
!3913 = !{!3888, !3762}
!3914 = !DISubprogram(name: "getNumBuckets", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E13getNumBucketsEv", scope: !3652, file: !1363, line: 378, type: !3775, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3915 = !DISubprogram(name: "getBucketsEnd", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E13getBucketsEndEv", scope: !3652, file: !1363, line: 381, type: !3912, scopeLine: 381, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3916 = !DISubprogram(name: "getBucketsEnd", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E13getBucketsEndEv", scope: !3652, file: !1363, line: 384, type: !3907, scopeLine: 384, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3917 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E4growEj", scope: !3652, file: !1363, line: 388, type: !3898, scopeLine: 388, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3918 = !DISubprogram(name: "shrink_and_clear", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E16shrink_and_clearEv", scope: !3652, file: !1363, line: 392, type: !3781, scopeLine: 392, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3919 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E16InsertIntoBucketERKjRKcPSt4pairIjcE", scope: !3652, file: !1363, line: 397, type: !3920, scopeLine: 397, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3920 = !DISubroutineType(types: !3921)
!3921 = !{!3888, !3762, !2065, !3922, !3888}
!3922 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !318, size: 64)
!3923 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E16InsertIntoBucketERKjOcPSt4pairIjcE", scope: !3652, file: !1363, line: 407, type: !3924, scopeLine: 407, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3924 = !DISubroutineType(types: !3925)
!3925 = !{!3888, !3762, !2065, !3926, !3888}
!3926 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !319, size: 64)
!3927 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E16InsertIntoBucketEOjOcPSt4pairIjcE", scope: !3652, file: !1363, line: 416, type: !3928, scopeLine: 416, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3928 = !DISubroutineType(types: !3929)
!3929 = !{!3888, !3762, !2198, !3926, !3888}
!3930 = !DISubprogram(name: "InsertIntoBucketImpl", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E20InsertIntoBucketImplERKjPSt4pairIjcE", scope: !3652, file: !1363, line: 425, type: !3931, scopeLine: 425, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3931 = !DISubroutineType(types: !3932)
!3932 = !{!3888, !3762, !2065, !3888}
!3933 = !DISubprogram(name: "getMemorySize", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjcNS_12DenseMapInfoIjEEEEjcS3_E13getMemorySizeEv", scope: !3652, file: !1363, line: 527, type: !3934, scopeLine: 527, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3934 = !DISubroutineType(types: !3935)
!3935 = !{!2102, !3768}
!3936 = !{!3937, !2052, !3761, !2054}
!3937 = !DITemplateTypeParameter(name: "DerivedT", type: !3649)
!3938 = !DIDerivedType(tag: DW_TAG_member, name: "Buckets", scope: !3649, file: !1363, line: 543, baseType: !3647, size: 64)
!3939 = !DIDerivedType(tag: DW_TAG_member, name: "NumEntries", scope: !3649, file: !1363, line: 544, baseType: !6, size: 32, offset: 64)
!3940 = !DIDerivedType(tag: DW_TAG_member, name: "NumTombstones", scope: !3649, file: !1363, line: 545, baseType: !6, size: 32, offset: 96)
!3941 = !DIDerivedType(tag: DW_TAG_member, name: "NumBuckets", scope: !3649, file: !1363, line: 546, baseType: !6, size: 32, offset: 128)
!3942 = !DISubprogram(name: "DenseMap", scope: !3649, file: !1363, line: 549, type: !3943, scopeLine: 549, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3943 = !DISubroutineType(types: !3944)
!3944 = !{null, !3945, !6}
!3945 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3649, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3946 = !DISubprogram(name: "DenseMap", scope: !3649, file: !1363, line: 553, type: !3947, scopeLine: 553, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3947 = !DISubroutineType(types: !3948)
!3948 = !{null, !3945, !3949}
!3949 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3950, size: 64)
!3950 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3649)
!3951 = !DISubprogram(name: "DenseMap", scope: !3649, file: !1363, line: 559, type: !3952, scopeLine: 559, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3952 = !DISubroutineType(types: !3953)
!3953 = !{null, !3945, !3954}
!3954 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3649, size: 64)
!3955 = !DISubprogram(name: "~DenseMap", scope: !3649, file: !1363, line: 571, type: !3956, scopeLine: 571, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3956 = !DISubroutineType(types: !3957)
!3957 = !{null, !3945}
!3958 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm8DenseMapIjcNS_12DenseMapInfoIjEEE4swapERS3_", scope: !3649, file: !1363, line: 576, type: !3959, scopeLine: 576, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3959 = !DISubroutineType(types: !3960)
!3960 = !{null, !3945, !3961}
!3961 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3649, size: 64)
!3962 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8DenseMapIjcNS_12DenseMapInfoIjEEEaSERKS3_", scope: !3649, file: !1363, line: 583, type: !3963, scopeLine: 583, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3963 = !DISubroutineType(types: !3964)
!3964 = !{!3961, !3945, !3949}
!3965 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8DenseMapIjcNS_12DenseMapInfoIjEEEaSEOS3_", scope: !3649, file: !1363, line: 589, type: !3966, scopeLine: 589, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3966 = !DISubroutineType(types: !3967)
!3967 = !{!3961, !3945, !3954}
!3968 = !DISubprogram(name: "copyFrom", linkageName: "_ZN4llvm8DenseMapIjcNS_12DenseMapInfoIjEEE8copyFromERKS3_", scope: !3649, file: !1363, line: 598, type: !3947, scopeLine: 598, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3969 = !DISubprogram(name: "init", linkageName: "_ZN4llvm8DenseMapIjcNS_12DenseMapInfoIjEEE4initEj", scope: !3649, file: !1363, line: 609, type: !3943, scopeLine: 609, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3970 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm8DenseMapIjcNS_12DenseMapInfoIjEEE4growEj", scope: !3649, file: !1363, line: 618, type: !3943, scopeLine: 618, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3971 = !DISubprogram(name: "shrink_and_clear", linkageName: "_ZN4llvm8DenseMapIjcNS_12DenseMapInfoIjEEE16shrink_and_clearEv", scope: !3649, file: !1363, line: 635, type: !3956, scopeLine: 635, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3972 = !DISubprogram(name: "getNumEntries", linkageName: "_ZNK4llvm8DenseMapIjcNS_12DenseMapInfoIjEEE13getNumEntriesEv", scope: !3649, file: !1363, line: 653, type: !3973, scopeLine: 653, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3973 = !DISubroutineType(types: !3974)
!3974 = !{!6, !3975}
!3975 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3950, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3976 = !DISubprogram(name: "setNumEntries", linkageName: "_ZN4llvm8DenseMapIjcNS_12DenseMapInfoIjEEE13setNumEntriesEj", scope: !3649, file: !1363, line: 656, type: !3943, scopeLine: 656, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3977 = !DISubprogram(name: "getNumTombstones", linkageName: "_ZNK4llvm8DenseMapIjcNS_12DenseMapInfoIjEEE16getNumTombstonesEv", scope: !3649, file: !1363, line: 660, type: !3973, scopeLine: 660, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3978 = !DISubprogram(name: "setNumTombstones", linkageName: "_ZN4llvm8DenseMapIjcNS_12DenseMapInfoIjEEE16setNumTombstonesEj", scope: !3649, file: !1363, line: 663, type: !3943, scopeLine: 663, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3979 = !DISubprogram(name: "getBuckets", linkageName: "_ZNK4llvm8DenseMapIjcNS_12DenseMapInfoIjEEE10getBucketsEv", scope: !3649, file: !1363, line: 667, type: !3980, scopeLine: 667, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3980 = !DISubroutineType(types: !3981)
!3981 = !{!3647, !3975}
!3982 = !DISubprogram(name: "getNumBuckets", linkageName: "_ZNK4llvm8DenseMapIjcNS_12DenseMapInfoIjEEE13getNumBucketsEv", scope: !3649, file: !1363, line: 671, type: !3973, scopeLine: 671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3983 = !DISubprogram(name: "allocateBuckets", linkageName: "_ZN4llvm8DenseMapIjcNS_12DenseMapInfoIjEEE15allocateBucketsEj", scope: !3649, file: !1363, line: 675, type: !3984, scopeLine: 675, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3984 = !DISubroutineType(types: !3985)
!3985 = !{!145, !3945, !6}
!3986 = !{!2052, !3761, !2054}
!3987 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3649, size: 64)
!3988 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3950, size: 64)
!3989 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !3433, file: !2501, line: 345, baseType: !3990)
!3990 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ilist_iterator<const llvm::MachineInstr>", scope: !14, file: !2501, line: 145, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3991, templateParams: !4047, identifier: "_ZTSN4llvm14ilist_iteratorIKNS_12MachineInstrEEE")
!3991 = !{!3992, !3999, !4002, !4009, !4010, !4011, !4012, !4013, !4017, !4022, !4025, !4028, !4031, !4032, !4036, !4037, !4041, !4042, !4045, !4046}
!3992 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3990, baseType: !3993, flags: DIFlagPublic, extraData: i32 0)
!3993 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::bidirectional_iterator_tag, const llvm::MachineInstr, long, const llvm::MachineInstr *, const llvm::MachineInstr &>", scope: !839, file: !1110, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !3994, identifier: "_ZTSSt8iteratorISt26bidirectional_iterator_tagKN4llvm12MachineInstrElPS3_RS3_E")
!3994 = !{!2486, !3995, !2495, !3996, !3997}
!3995 = !DITemplateTypeParameter(name: "_Tp", type: !353)
!3996 = !DITemplateTypeParameter(name: "_Pointer", type: !352)
!3997 = !DITemplateTypeParameter(name: "_Reference", type: !3998)
!3998 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !353, size: 64)
!3999 = !DIDerivedType(tag: DW_TAG_member, name: "NodePtr", scope: !3990, file: !2501, line: 158, baseType: !4000, size: 64)
!4000 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3990, file: !2501, line: 155, baseType: !4001)
!4001 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3993, file: !1110, line: 127, baseType: !352)
!4002 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEixEl", scope: !3990, file: !2501, line: 164, type: !4003, scopeLine: 164, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4003 = !DISubroutineType(types: !4004)
!4004 = !{null, !4005, !4007}
!4005 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4006, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4006 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3990)
!4007 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !3990, file: !2501, line: 154, baseType: !4008)
!4008 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !3993, file: !1110, line: 125, baseType: !288)
!4009 = !DISubprogram(name: "operator+", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEplEl", scope: !3990, file: !2501, line: 165, type: !4003, scopeLine: 165, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4010 = !DISubprogram(name: "operator-", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEmiEl", scope: !3990, file: !2501, line: 166, type: !4003, scopeLine: 166, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4011 = !DISubprogram(name: "operator+=", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEpLEl", scope: !3990, file: !2501, line: 167, type: !4003, scopeLine: 167, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4012 = !DISubprogram(name: "operator-=", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEmIEl", scope: !3990, file: !2501, line: 168, type: !4003, scopeLine: 168, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4013 = !DISubprogram(name: "ilist_iterator", scope: !3990, file: !2501, line: 176, type: !4014, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4014 = !DISubroutineType(types: !4015)
!4015 = !{null, !4016, !4000}
!4016 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3990, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4017 = !DISubprogram(name: "ilist_iterator", scope: !3990, file: !2501, line: 177, type: !4018, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4018 = !DISubroutineType(types: !4019)
!4019 = !{null, !4016, !4020}
!4020 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3990, file: !2501, line: 156, baseType: !4021)
!4021 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3993, file: !1110, line: 129, baseType: !3998)
!4022 = !DISubprogram(name: "ilist_iterator", scope: !3990, file: !2501, line: 178, type: !4023, scopeLine: 178, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4023 = !DISubroutineType(types: !4024)
!4024 = !{null, !4016}
!4025 = !DISubprogram(name: "operator const llvm::MachineInstr *", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEcvPS2_Ev", scope: !3990, file: !2501, line: 195, type: !4026, scopeLine: 195, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4026 = !DISubroutineType(types: !4027)
!4027 = !{!4000, !4005}
!4028 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEdeEv", scope: !3990, file: !2501, line: 199, type: !4029, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4029 = !DISubroutineType(types: !4030)
!4030 = !{!4020, !4005}
!4031 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEptEv", scope: !3990, file: !2501, line: 202, type: !4026, scopeLine: 202, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4032 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEeqERKS3_", scope: !3990, file: !2501, line: 205, type: !4033, scopeLine: 205, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4033 = !DISubroutineType(types: !4034)
!4034 = !{!145, !4005, !4035}
!4035 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4006, size: 64)
!4036 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEneERKS3_", scope: !3990, file: !2501, line: 208, type: !4033, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4037 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorIKNS_12MachineInstrEEmmEv", scope: !3990, file: !2501, line: 213, type: !4038, scopeLine: 213, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4038 = !DISubroutineType(types: !4039)
!4039 = !{!4040, !4016}
!4040 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3990, size: 64)
!4041 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorIKNS_12MachineInstrEEppEv", scope: !3990, file: !2501, line: 218, type: !4038, scopeLine: 218, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4042 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorIKNS_12MachineInstrEEmmEi", scope: !3990, file: !2501, line: 222, type: !4043, scopeLine: 222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4043 = !DISubroutineType(types: !4044)
!4044 = !{!3990, !4016, !32}
!4045 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorIKNS_12MachineInstrEEppEi", scope: !3990, file: !2501, line: 227, type: !4043, scopeLine: 227, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4046 = !DISubprogram(name: "getNodePtrUnchecked", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEE19getNodePtrUncheckedEv", scope: !3990, file: !2501, line: 234, type: !4026, scopeLine: 234, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4047 = !{!4048}
!4048 = !DITemplateTypeParameter(name: "NodeTy", type: !353)
!4049 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3769, size: 64)
!4050 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !4051, file: !2317, line: 377, baseType: !4133)
!4051 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<llvm::MachineBasicBlock *>", scope: !14, file: !2317, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4052, templateParams: !4132, identifier: "_ZTSN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEEE")
!4052 = !{!4053, !4072, !4078, !4081, !4084, !4085, !4086, !4089, !4090, !4093, !4097, !4100, !4101, !4105, !4108, !4112, !4115, !4118, !4121, !4125, !4129, !4130, !4131}
!4053 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4051, baseType: !4054, flags: DIFlagPublic, extraData: i32 0)
!4054 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<llvm::MachineBasicBlock *, true>", scope: !14, file: !2317, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4055, templateParams: !4071, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseIPNS_17MachineBasicBlockELb1EEE")
!4055 = !{!4056, !4057, !4061, !4064, !4065, !4068}
!4056 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4054, baseType: !3339, flags: DIFlagPublic, extraData: i32 0)
!4057 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !4054, file: !2317, line: 298, type: !4058, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4058 = !DISubroutineType(types: !4059)
!4059 = !{null, !4060, !2102}
!4060 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4054, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4061 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPNS_17MachineBasicBlockELb1EE13destroy_rangeEPS2_S4_", scope: !4054, file: !2317, line: 301, type: !4062, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4062 = !DISubroutineType(types: !4063)
!4063 = !{null, !3285, !3285}
!4064 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPNS_17MachineBasicBlockELb1EE4growEm", scope: !4054, file: !2317, line: 346, type: !4058, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4065 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPNS_17MachineBasicBlockELb1EE9push_backERKS2_", scope: !4054, file: !2317, line: 350, type: !4066, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4066 = !DISubroutineType(types: !4067)
!4067 = !{null, !4060, !3421}
!4068 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPNS_17MachineBasicBlockELb1EE8pop_backEv", scope: !4054, file: !2317, line: 361, type: !4069, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4069 = !DISubroutineType(types: !4070)
!4070 = !{null, !4060}
!4071 = !{!3431, !2627}
!4072 = !DISubprogram(name: "SmallVectorImpl", scope: !4051, file: !2317, line: 374, type: !4073, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!4073 = !DISubroutineType(types: !4074)
!4074 = !{null, !4075, !4076}
!4075 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4051, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4076 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4077, size: 64)
!4077 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4051)
!4078 = !DISubprogram(name: "SmallVectorImpl", scope: !4051, file: !2317, line: 381, type: !4079, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4079 = !DISubroutineType(types: !4080)
!4080 = !{null, !4075, !6}
!4081 = !DISubprogram(name: "~SmallVectorImpl", scope: !4051, file: !2317, line: 386, type: !4082, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4082 = !DISubroutineType(types: !4083)
!4083 = !{null, !4075}
!4084 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEE5clearEv", scope: !4051, file: !2317, line: 396, type: !4082, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4085 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEE6resizeEj", scope: !4051, file: !2317, line: 401, type: !4079, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4086 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEE6resizeEjRKS2_", scope: !4051, file: !2317, line: 413, type: !4087, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4087 = !DISubroutineType(types: !4088)
!4088 = !{null, !4075, !6, !3421}
!4089 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEE7reserveEj", scope: !4051, file: !2317, line: 425, type: !4079, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4090 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEE12pop_back_valEv", scope: !4051, file: !2317, line: 430, type: !4091, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4091 = !DISubroutineType(types: !4092)
!4092 = !{!197, !4075}
!4093 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEE4swapERS3_", scope: !4051, file: !2317, line: 440, type: !4094, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4094 = !DISubroutineType(types: !4095)
!4095 = !{null, !4075, !4096}
!4096 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4051, size: 64)
!4097 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEE6appendEmRKS2_", scope: !4051, file: !2317, line: 460, type: !4098, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4098 = !DISubroutineType(types: !4099)
!4099 = !{null, !4075, !4050, !3421}
!4100 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEE6assignEjRKS2_", scope: !4051, file: !2317, line: 470, type: !4087, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4101 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEE5eraseEPS2_", scope: !4051, file: !2317, line: 478, type: !4102, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4102 = !DISubroutineType(types: !4103)
!4103 = !{!4104, !4075, !4104}
!4104 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !4051, file: !2317, line: 376, baseType: !3338)
!4105 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEE5eraseEPS2_S4_", scope: !4051, file: !2317, line: 490, type: !4106, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4106 = !DISubroutineType(types: !4107)
!4107 = !{!4104, !4075, !4104, !4104}
!4108 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEE6insertEPS2_OS2_", scope: !4051, file: !2317, line: 505, type: !4109, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4109 = !DISubroutineType(types: !4110)
!4110 = !{!4104, !4075, !4104, !4111}
!4111 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !197, size: 64)
!4112 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEE6insertEPS2_RKS2_", scope: !4051, file: !2317, line: 537, type: !4113, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4113 = !DISubroutineType(types: !4114)
!4114 = !{!4104, !4075, !4104, !3421}
!4115 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEE6insertEPS2_mRKS2_", scope: !4051, file: !2317, line: 568, type: !4116, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4116 = !DISubroutineType(types: !4117)
!4117 = !{!4104, !4075, !4104, !4050, !3421}
!4118 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEEaSERKS3_", scope: !4051, file: !2317, line: 674, type: !4119, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4119 = !DISubroutineType(types: !4120)
!4120 = !{!4096, !4075, !4076}
!4121 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEEaSEOS3_", scope: !4051, file: !2317, line: 677, type: !4122, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4122 = !DISubroutineType(types: !4123)
!4123 = !{!4096, !4075, !4124}
!4124 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !4051, size: 64)
!4125 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplIPNS_17MachineBasicBlockEEeqERKS3_", scope: !4051, file: !2317, line: 680, type: !4126, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4126 = !DISubroutineType(types: !4127)
!4127 = !{!145, !4128, !4076}
!4128 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4077, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4129 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplIPNS_17MachineBasicBlockEEneERKS3_", scope: !4051, file: !2317, line: 684, type: !4126, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4130 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplIPNS_17MachineBasicBlockEEltERKS3_", scope: !4051, file: !2317, line: 688, type: !4126, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4131 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEE8set_sizeEj", scope: !4051, file: !2317, line: 702, type: !4079, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4132 = !{!3431}
!4133 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !3339, file: !2317, line: 97, baseType: !2102)
!4134 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !4135, file: !838, line: 371, baseType: !4136)
!4135 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<unsigned int, std::allocator<unsigned int> >", scope: !839, file: !838, line: 339, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt6vectorIjSaIjEE")
!4136 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<const unsigned int *, std::vector<unsigned int, std::allocator<unsigned int> > >", scope: !5, file: !1093, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4137, templateParams: !4188, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPKjSt6vectorIjSaIjEEEE")
!4137 = !{!4138, !4139, !4143, !4148, !4158, !4163, !4167, !4170, !4171, !4172, !4177, !4180, !4183, !4184, !4185}
!4138 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !4136, file: !1093, line: 767, baseType: !2391, size: 64, flags: DIFlagProtected)
!4139 = !DISubprogram(name: "__normal_iterator", scope: !4136, file: !1093, line: 779, type: !4140, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4140 = !DISubroutineType(types: !4141)
!4141 = !{null, !4142}
!4142 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4136, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4143 = !DISubprogram(name: "__normal_iterator", scope: !4136, file: !1093, line: 783, type: !4144, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4144 = !DISubroutineType(types: !4145)
!4145 = !{null, !4142, !4146}
!4146 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4147, size: 64)
!4147 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2391)
!4148 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKjSt6vectorIjSaIjEEEdeEv", scope: !4136, file: !1093, line: 796, type: !4149, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4149 = !DISubroutineType(types: !4150)
!4150 = !{!4151, !4156}
!4151 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !4136, file: !1093, line: 776, baseType: !4152)
!4152 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !4153, file: !1110, line: 195, baseType: !2065)
!4153 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<const unsigned int *>", scope: !839, file: !1110, line: 189, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !4154, identifier: "_ZTSSt15iterator_traitsIPKjE")
!4154 = !{!4155}
!4155 = !DITemplateTypeParameter(name: "_Iterator", type: !2391)
!4156 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4157, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4157 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4136)
!4158 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKjSt6vectorIjSaIjEEEptEv", scope: !4136, file: !1093, line: 800, type: !4159, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4159 = !DISubroutineType(types: !4160)
!4160 = !{!4161, !4156}
!4161 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4136, file: !1093, line: 777, baseType: !4162)
!4162 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4153, file: !1110, line: 194, baseType: !2391)
!4163 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKjSt6vectorIjSaIjEEEppEv", scope: !4136, file: !1093, line: 804, type: !4164, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4164 = !DISubroutineType(types: !4165)
!4165 = !{!4166, !4142}
!4166 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4136, size: 64)
!4167 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKjSt6vectorIjSaIjEEEppEi", scope: !4136, file: !1093, line: 811, type: !4168, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4168 = !DISubroutineType(types: !4169)
!4169 = !{!4136, !4142, !32}
!4170 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKjSt6vectorIjSaIjEEEmmEv", scope: !4136, file: !1093, line: 816, type: !4164, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4171 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKjSt6vectorIjSaIjEEEmmEi", scope: !4136, file: !1093, line: 823, type: !4168, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4172 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKjSt6vectorIjSaIjEEEixEl", scope: !4136, file: !1093, line: 828, type: !4173, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4173 = !DISubroutineType(types: !4174)
!4174 = !{!4151, !4156, !4175}
!4175 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !4136, file: !1093, line: 775, baseType: !4176)
!4176 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !4153, file: !1110, line: 193, baseType: !1135)
!4177 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKjSt6vectorIjSaIjEEEpLEl", scope: !4136, file: !1093, line: 832, type: !4178, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4178 = !DISubroutineType(types: !4179)
!4179 = !{!4166, !4142, !4175}
!4180 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKjSt6vectorIjSaIjEEEplEl", scope: !4136, file: !1093, line: 836, type: !4181, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4181 = !DISubroutineType(types: !4182)
!4182 = !{!4136, !4156, !4175}
!4183 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKjSt6vectorIjSaIjEEEmIEl", scope: !4136, file: !1093, line: 840, type: !4178, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4184 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKjSt6vectorIjSaIjEEEmiEl", scope: !4136, file: !1093, line: 844, type: !4181, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4185 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKjSt6vectorIjSaIjEEE4baseEv", scope: !4136, file: !1093, line: 848, type: !4186, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4186 = !DISubroutineType(types: !4187)
!4187 = !{!4146, !4156}
!4188 = !{!4155, !4189}
!4189 = !DITemplateTypeParameter(name: "_Container", type: !4135)
!4190 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4191, size: 64)
!4191 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4192)
!4192 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Tp_alloc_type", scope: !4193, file: !838, line: 84, baseType: !4194)
!4193 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_base<unsigned int, std::allocator<unsigned int> >", scope: !839, file: !838, line: 81, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt12_Vector_baseIjSaIjEE")
!4194 = !DIDerivedType(tag: DW_TAG_typedef, name: "other", scope: !4195, file: !850, line: 117, baseType: !4243)
!4195 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "rebind<unsigned int>", scope: !4196, file: !850, line: 116, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !4241, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIjEjE6rebindIjEE")
!4196 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__alloc_traits<std::allocator<unsigned int>, unsigned int>", scope: !5, file: !850, line: 50, size: 8, flags: DIFlagTypePassByValue, elements: !4197, templateParams: !4239, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIjEjEE")
!4197 = !{!4198, !4225, !4230, !4234, !4235, !4236, !4237, !4238}
!4198 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4196, baseType: !4199, extraData: i32 0)
!4199 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "allocator_traits<std::allocator<unsigned int> >", scope: !839, file: !856, line: 384, size: 8, flags: DIFlagTypePassByValue, elements: !4200, templateParams: !4223, identifier: "_ZTSSt16allocator_traitsISaIjEE")
!4200 = !{!4201, !4208, !4211, !4214, !4220}
!4201 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIjEE8allocateERS0_m", scope: !4199, file: !856, line: 435, type: !4202, scopeLine: 435, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4202 = !DISubroutineType(types: !4203)
!4203 = !{!4204, !4205, !925}
!4204 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4199, file: !856, line: 392, baseType: !2383)
!4205 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4206, size: 64)
!4206 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !4199, file: !856, line: 387, baseType: !4207)
!4207 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "allocator<unsigned int>", scope: !839, file: !868, line: 108, size: 8, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSaIjE")
!4208 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIjEE8allocateERS0_mPKv", scope: !4199, file: !856, line: 449, type: !4209, scopeLine: 449, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4209 = !DISubroutineType(types: !4210)
!4210 = !{!4204, !4205, !925, !929}
!4211 = !DISubprogram(name: "deallocate", linkageName: "_ZNSt16allocator_traitsISaIjEE10deallocateERS0_Pjm", scope: !4199, file: !856, line: 461, type: !4212, scopeLine: 461, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4212 = !DISubroutineType(types: !4213)
!4213 = !{null, !4205, !4204, !925}
!4214 = !DISubprogram(name: "max_size", linkageName: "_ZNSt16allocator_traitsISaIjEE8max_sizeERKS0_", scope: !4199, file: !856, line: 495, type: !4215, scopeLine: 495, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4215 = !DISubroutineType(types: !4216)
!4216 = !{!4217, !4218}
!4217 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !4199, file: !856, line: 407, baseType: !905)
!4218 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4219, size: 64)
!4219 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4206)
!4220 = !DISubprogram(name: "select_on_container_copy_construction", linkageName: "_ZNSt16allocator_traitsISaIjEE37select_on_container_copy_constructionERKS0_", scope: !4199, file: !856, line: 504, type: !4221, scopeLine: 504, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4221 = !DISubroutineType(types: !4222)
!4222 = !{!4206, !4218}
!4223 = !{!4224}
!4224 = !DITemplateTypeParameter(name: "_Alloc", type: !4207)
!4225 = !DISubprogram(name: "_S_select_on_copy", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIjEjE17_S_select_on_copyERKS1_", scope: !4196, file: !850, line: 94, type: !4226, scopeLine: 94, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4226 = !DISubroutineType(types: !4227)
!4227 = !{!4207, !4228}
!4228 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4229, size: 64)
!4229 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4207)
!4230 = !DISubprogram(name: "_S_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIjEjE10_S_on_swapERS1_S3_", scope: !4196, file: !850, line: 97, type: !4231, scopeLine: 97, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4231 = !DISubroutineType(types: !4232)
!4232 = !{null, !4233, !4233}
!4233 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4207, size: 64)
!4234 = !DISubprogram(name: "_S_propagate_on_copy_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIjEjE27_S_propagate_on_copy_assignEv", scope: !4196, file: !850, line: 100, type: !952, scopeLine: 100, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4235 = !DISubprogram(name: "_S_propagate_on_move_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIjEjE27_S_propagate_on_move_assignEv", scope: !4196, file: !850, line: 103, type: !952, scopeLine: 103, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4236 = !DISubprogram(name: "_S_propagate_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIjEjE20_S_propagate_on_swapEv", scope: !4196, file: !850, line: 106, type: !952, scopeLine: 106, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4237 = !DISubprogram(name: "_S_always_equal", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIjEjE15_S_always_equalEv", scope: !4196, file: !850, line: 109, type: !952, scopeLine: 109, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4238 = !DISubprogram(name: "_S_nothrow_move", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIjEjE15_S_nothrow_moveEv", scope: !4196, file: !850, line: 112, type: !952, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4239 = !{!4224, !4240}
!4240 = !DITemplateTypeParameter(type: !6)
!4241 = !{!4242}
!4242 = !DITemplateTypeParameter(name: "_Tp", type: !6)
!4243 = !DIDerivedType(tag: DW_TAG_typedef, name: "rebind_alloc<unsigned int>", scope: !4199, file: !856, line: 422, baseType: !4207)
!4244 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !4135, file: !838, line: 369, baseType: !4245)
!4245 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<unsigned int *, std::vector<unsigned int, std::allocator<unsigned int> > >", scope: !5, file: !1093, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4246, templateParams: !4297, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPjSt6vectorIjSaIjEEEE")
!4246 = !{!4247, !4248, !4252, !4257, !4267, !4272, !4276, !4279, !4280, !4281, !4286, !4289, !4292, !4293, !4294}
!4247 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !4245, file: !1093, line: 767, baseType: !2383, size: 64, flags: DIFlagProtected)
!4248 = !DISubprogram(name: "__normal_iterator", scope: !4245, file: !1093, line: 779, type: !4249, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4249 = !DISubroutineType(types: !4250)
!4250 = !{null, !4251}
!4251 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4245, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4252 = !DISubprogram(name: "__normal_iterator", scope: !4245, file: !1093, line: 783, type: !4253, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4253 = !DISubroutineType(types: !4254)
!4254 = !{null, !4251, !4255}
!4255 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4256, size: 64)
!4256 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2383)
!4257 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPjSt6vectorIjSaIjEEEdeEv", scope: !4245, file: !1093, line: 796, type: !4258, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4258 = !DISubroutineType(types: !4259)
!4259 = !{!4260, !4265}
!4260 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !4245, file: !1093, line: 776, baseType: !4261)
!4261 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !4262, file: !1110, line: 184, baseType: !2428)
!4262 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<unsigned int *>", scope: !839, file: !1110, line: 178, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !4263, identifier: "_ZTSSt15iterator_traitsIPjE")
!4263 = !{!4264}
!4264 = !DITemplateTypeParameter(name: "_Iterator", type: !2383)
!4265 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4266, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4266 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4245)
!4267 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPjSt6vectorIjSaIjEEEptEv", scope: !4245, file: !1093, line: 800, type: !4268, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4268 = !DISubroutineType(types: !4269)
!4269 = !{!4270, !4265}
!4270 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4245, file: !1093, line: 777, baseType: !4271)
!4271 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4262, file: !1110, line: 183, baseType: !2383)
!4272 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPjSt6vectorIjSaIjEEEppEv", scope: !4245, file: !1093, line: 804, type: !4273, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4273 = !DISubroutineType(types: !4274)
!4274 = !{!4275, !4251}
!4275 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4245, size: 64)
!4276 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPjSt6vectorIjSaIjEEEppEi", scope: !4245, file: !1093, line: 811, type: !4277, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4277 = !DISubroutineType(types: !4278)
!4278 = !{!4245, !4251, !32}
!4279 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPjSt6vectorIjSaIjEEEmmEv", scope: !4245, file: !1093, line: 816, type: !4273, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4280 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPjSt6vectorIjSaIjEEEmmEi", scope: !4245, file: !1093, line: 823, type: !4277, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4281 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPjSt6vectorIjSaIjEEEixEl", scope: !4245, file: !1093, line: 828, type: !4282, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4282 = !DISubroutineType(types: !4283)
!4283 = !{!4260, !4265, !4284}
!4284 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !4245, file: !1093, line: 775, baseType: !4285)
!4285 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !4262, file: !1110, line: 182, baseType: !1135)
!4286 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPjSt6vectorIjSaIjEEEpLEl", scope: !4245, file: !1093, line: 832, type: !4287, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4287 = !DISubroutineType(types: !4288)
!4288 = !{!4275, !4251, !4284}
!4289 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPjSt6vectorIjSaIjEEEplEl", scope: !4245, file: !1093, line: 836, type: !4290, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4290 = !DISubroutineType(types: !4291)
!4291 = !{!4245, !4265, !4284}
!4292 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPjSt6vectorIjSaIjEEEmIEl", scope: !4245, file: !1093, line: 840, type: !4287, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4293 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPjSt6vectorIjSaIjEEEmiEl", scope: !4245, file: !1093, line: 844, type: !4290, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4294 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPjSt6vectorIjSaIjEEE4baseEv", scope: !4245, file: !1093, line: 848, type: !4295, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4295 = !DISubroutineType(types: !4296)
!4296 = !{!4255, !4265}
!4297 = !{!4264, !4189}
!4298 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "move_iterator<unsigned int *>", scope: !839, file: !1093, line: 1007, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4299, templateParams: !4263, identifier: "_ZTSSt13move_iteratorIPjE")
!4299 = !{!4300, !4301, !4305, !4309, !4314, !4323, !4327, !4331, !4334, !4335, !4336, !4340, !4343, !4344, !4345}
!4300 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !4298, file: !1093, line: 1010, baseType: !2383, size: 64, flags: DIFlagProtected)
!4301 = !DISubprogram(name: "move_iterator", scope: !4298, file: !1093, line: 1029, type: !4302, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4302 = !DISubroutineType(types: !4303)
!4303 = !{null, !4304}
!4304 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4298, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4305 = !DISubprogram(name: "move_iterator", scope: !4298, file: !1093, line: 1033, type: !4306, scopeLine: 1033, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4306 = !DISubroutineType(types: !4307)
!4307 = !{null, !4304, !4308}
!4308 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator_type", scope: !4298, file: !1093, line: 1016, baseType: !2383)
!4309 = !DISubprogram(name: "base", linkageName: "_ZNKSt13move_iteratorIPjE4baseEv", scope: !4298, file: !1093, line: 1042, type: !4310, scopeLine: 1042, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4310 = !DISubroutineType(types: !4311)
!4311 = !{!4308, !4312}
!4312 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4313, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4313 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4298)
!4314 = !DISubprogram(name: "operator*", linkageName: "_ZNKSt13move_iteratorIPjEdeEv", scope: !4298, file: !1093, line: 1046, type: !4315, scopeLine: 1046, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4315 = !DISubroutineType(types: !4316)
!4316 = !{!4317, !4312}
!4317 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !4298, file: !1093, line: 1026, baseType: !4318)
!4318 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !4319, file: !1281, line: 1928, baseType: !2198)
!4319 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, unsigned int &&, unsigned int &>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !4320, identifier: "_ZTSSt11conditionalILb1EOjRjE")
!4320 = !{!1472, !4321, !4322}
!4321 = !DITemplateTypeParameter(name: "_Iftrue", type: !2198)
!4322 = !DITemplateTypeParameter(name: "_Iffalse", type: !2428)
!4323 = !DISubprogram(name: "operator->", linkageName: "_ZNKSt13move_iteratorIPjEptEv", scope: !4298, file: !1093, line: 1050, type: !4324, scopeLine: 1050, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4324 = !DISubroutineType(types: !4325)
!4325 = !{!4326, !4312}
!4326 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4298, file: !1093, line: 1021, baseType: !2383)
!4327 = !DISubprogram(name: "operator++", linkageName: "_ZNSt13move_iteratorIPjEppEv", scope: !4298, file: !1093, line: 1054, type: !4328, scopeLine: 1054, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4328 = !DISubroutineType(types: !4329)
!4329 = !{!4330, !4304}
!4330 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4298, size: 64)
!4331 = !DISubprogram(name: "operator++", linkageName: "_ZNSt13move_iteratorIPjEppEi", scope: !4298, file: !1093, line: 1061, type: !4332, scopeLine: 1061, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4332 = !DISubroutineType(types: !4333)
!4333 = !{!4298, !4304, !32}
!4334 = !DISubprogram(name: "operator--", linkageName: "_ZNSt13move_iteratorIPjEmmEv", scope: !4298, file: !1093, line: 1069, type: !4328, scopeLine: 1069, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4335 = !DISubprogram(name: "operator--", linkageName: "_ZNSt13move_iteratorIPjEmmEi", scope: !4298, file: !1093, line: 1076, type: !4332, scopeLine: 1076, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4336 = !DISubprogram(name: "operator+", linkageName: "_ZNKSt13move_iteratorIPjEplEl", scope: !4298, file: !1093, line: 1084, type: !4337, scopeLine: 1084, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4337 = !DISubroutineType(types: !4338)
!4338 = !{!4298, !4312, !4339}
!4339 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !4298, file: !1093, line: 1019, baseType: !4285)
!4340 = !DISubprogram(name: "operator+=", linkageName: "_ZNSt13move_iteratorIPjEpLEl", scope: !4298, file: !1093, line: 1088, type: !4341, scopeLine: 1088, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4341 = !DISubroutineType(types: !4342)
!4342 = !{!4330, !4304, !4339}
!4343 = !DISubprogram(name: "operator-", linkageName: "_ZNKSt13move_iteratorIPjEmiEl", scope: !4298, file: !1093, line: 1095, type: !4337, scopeLine: 1095, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4344 = !DISubprogram(name: "operator-=", linkageName: "_ZNSt13move_iteratorIPjEmIEl", scope: !4298, file: !1093, line: 1099, type: !4341, scopeLine: 1099, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4345 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt13move_iteratorIPjEixEl", scope: !4298, file: !1093, line: 1106, type: !4346, scopeLine: 1106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4346 = !DISubroutineType(types: !4347)
!4347 = !{!4317, !4312, !4339}
!4348 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4192, size: 64)
!4349 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4350, size: 64)
!4350 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !4351, file: !1363, line: 540, baseType: !4610)
!4351 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMap<unsigned int, unsigned int, llvm::DenseMapInfo<unsigned int> >", scope: !14, file: !1363, line: 534, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4352, templateParams: !4728, identifier: "_ZTSN4llvm8DenseMapIjjNS_12DenseMapInfoIjEEEE")
!4352 = !{!4353, !4680, !4681, !4682, !4683, !4684, !4688, !4693, !4697, !4700, !4704, !4707, !4710, !4711, !4712, !4713, !4714, !4718, !4719, !4720, !4721, !4724, !4725}
!4353 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4351, baseType: !4354, flags: DIFlagPublic, extraData: i32 0)
!4354 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapBase<llvm::DenseMap<unsigned int, unsigned int, llvm::DenseMapInfo<unsigned int> >, unsigned int, unsigned int, llvm::DenseMapInfo<unsigned int> >", scope: !14, file: !1363, line: 41, size: 8, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4355, templateParams: !4678, identifier: "_ZTSN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_EE")
!4355 = !{!4356, !4508, !4509, !4515, !4516, !4519, !4522, !4525, !4528, !4531, !4534, !4537, !4540, !4596, !4599, !4602, !4605, !4611, !4614, !4617, !4620, !4623, !4626, !4627, !4628, !4629, !4633, !4637, !4638, !4639, !4640, !4641, !4644, !4645, !4646, !4647, !4648, !4649, !4650, !4655, !4658, !4659, !4660, !4661, !4662, !4663, !4666, !4669, !4672, !4675}
!4356 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E5beginEv", scope: !4354, file: !1363, line: 53, type: !4357, scopeLine: 53, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4357 = !DISubroutineType(types: !4358)
!4358 = !{!4359, !4507}
!4359 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !4354, file: !1363, line: 50, baseType: !4360)
!4360 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapIterator<unsigned int, unsigned int, llvm::DenseMapInfo<unsigned int>, false>", scope: !14, file: !1363, line: 987, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4361, templateParams: !4506, identifier: "_ZTSN4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb0EEE")
!4361 = !{!4362, !4422, !4423, !4427, !4430, !4435, !4441, !4444, !4497, !4498, !4502, !4505}
!4362 = !DIDerivedType(tag: DW_TAG_member, name: "Ptr", scope: !4360, file: !1363, line: 999, baseType: !4363, size: 64)
!4363 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4360, file: !1363, line: 995, baseType: !4364)
!4364 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4365, size: 64)
!4365 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !4360, file: !1363, line: 994, baseType: !4366)
!4366 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !4367, file: !1380, line: 236, baseType: !4371)
!4367 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<false, const std::pair<unsigned int, unsigned int>, std::pair<unsigned int, unsigned int> >", scope: !14, file: !1380, line: 236, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !4368, identifier: "_ZTSN4llvm11conditionalILb0EKSt4pairIjjES2_EE")
!4368 = !{!1383, !4369, !4421}
!4369 = !DITemplateTypeParameter(name: "T", type: !4370)
!4370 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4371)
!4371 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<unsigned int, unsigned int>", scope: !839, file: !1387, line: 208, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4372, templateParams: !4420, identifier: "_ZTSSt4pairIjjE")
!4372 = !{!4373, !4391, !4392, !4393, !4398, !4402, !4410, !4417}
!4373 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4371, baseType: !4374, flags: DIFlagPrivate, extraData: i32 0)
!4374 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<unsigned int, unsigned int>", scope: !839, file: !1387, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !4375, templateParams: !4390, identifier: "_ZTSSt11__pair_baseIjjE")
!4375 = !{!4376, !4380, !4381, !4386}
!4376 = !DISubprogram(name: "__pair_base", scope: !4374, file: !1387, line: 194, type: !4377, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4377 = !DISubroutineType(types: !4378)
!4378 = !{null, !4379}
!4379 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4374, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4380 = !DISubprogram(name: "~__pair_base", scope: !4374, file: !1387, line: 195, type: !4377, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4381 = !DISubprogram(name: "__pair_base", scope: !4374, file: !1387, line: 196, type: !4382, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4382 = !DISubroutineType(types: !4383)
!4383 = !{null, !4379, !4384}
!4384 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4385, size: 64)
!4385 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4374)
!4386 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIjjEaSERKS0_", scope: !4374, file: !1387, line: 197, type: !4387, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!4387 = !DISubroutineType(types: !4388)
!4388 = !{!4389, !4379, !4384}
!4389 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4374, size: 64)
!4390 = !{!1407, !1452}
!4391 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !4371, file: !1387, line: 214, baseType: !6, size: 32)
!4392 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !4371, file: !1387, line: 215, baseType: !6, size: 32, offset: 32)
!4393 = !DISubprogram(name: "pair", scope: !4371, file: !1387, line: 303, type: !4394, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4394 = !DISubroutineType(types: !4395)
!4395 = !{null, !4396, !4397}
!4396 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4371, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4397 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4370, size: 64)
!4398 = !DISubprogram(name: "pair", scope: !4371, file: !1387, line: 304, type: !4399, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4399 = !DISubroutineType(types: !4400)
!4400 = !{null, !4396, !4401}
!4401 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !4371, size: 64)
!4402 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIjjEaSERKS0_", scope: !4371, file: !1387, line: 378, type: !4403, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4403 = !DISubroutineType(types: !4404)
!4404 = !{!4405, !4396, !4406}
!4405 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4371, size: 64)
!4406 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !4407, file: !1281, line: 1928, baseType: !4397)
!4407 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<unsigned int, unsigned int> &, const std::__nonesuch_no_braces &>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !4408, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIjjERKSt20__nonesuch_no_bracesE")
!4408 = !{!1472, !4409, !1474}
!4409 = !DITemplateTypeParameter(name: "_Iftrue", type: !4397)
!4410 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIjjEaSEOS0_", scope: !4371, file: !1387, line: 389, type: !4411, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4411 = !DISubroutineType(types: !4412)
!4412 = !{!4405, !4396, !4413}
!4413 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !4414, file: !1281, line: 1928, baseType: !4401)
!4414 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<unsigned int, unsigned int> &&, std::__nonesuch_no_braces &&>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !4415, identifier: "_ZTSSt11conditionalILb1EOSt4pairIjjEOSt20__nonesuch_no_bracesE")
!4415 = !{!1472, !4416, !1485}
!4416 = !DITemplateTypeParameter(name: "_Iftrue", type: !4401)
!4417 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIjjE4swapERS0_", scope: !4371, file: !1387, line: 424, type: !4418, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4418 = !DISubroutineType(types: !4419)
!4419 = !{null, !4396, !4405}
!4420 = !{!1974, !1492}
!4421 = !DITemplateTypeParameter(name: "F", type: !4371)
!4422 = !DIDerivedType(tag: DW_TAG_member, name: "End", scope: !4360, file: !1363, line: 999, baseType: !4363, size: 64, offset: 64)
!4423 = !DISubprogram(name: "DenseMapIterator", scope: !4360, file: !1363, line: 1001, type: !4424, scopeLine: 1001, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4424 = !DISubroutineType(types: !4425)
!4425 = !{null, !4426}
!4426 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4360, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4427 = !DISubprogram(name: "DenseMapIterator", scope: !4360, file: !1363, line: 1003, type: !4428, scopeLine: 1003, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4428 = !DISubroutineType(types: !4429)
!4429 = !{null, !4426, !4363, !4363, !145}
!4430 = !DISubprogram(name: "DenseMapIterator", scope: !4360, file: !1363, line: 1011, type: !4431, scopeLine: 1011, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4431 = !DISubroutineType(types: !4432)
!4432 = !{null, !4426, !4433}
!4433 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4434, size: 64)
!4434 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4360)
!4435 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb0EEdeEv", scope: !4360, file: !1363, line: 1015, type: !4436, scopeLine: 1015, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4436 = !DISubroutineType(types: !4437)
!4437 = !{!4438, !4440}
!4438 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !4360, file: !1363, line: 996, baseType: !4439)
!4439 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4365, size: 64)
!4440 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4434, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4441 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb0EEptEv", scope: !4360, file: !1363, line: 1018, type: !4442, scopeLine: 1018, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4442 = !DISubroutineType(types: !4443)
!4443 = !{!4363, !4440}
!4444 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb0EEeqERKNS0_IjjS2_Lb1EEE", scope: !4360, file: !1363, line: 1022, type: !4445, scopeLine: 1022, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4445 = !DISubroutineType(types: !4446)
!4446 = !{!145, !4440, !4447}
!4447 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4448, size: 64)
!4448 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4449)
!4449 = !DIDerivedType(tag: DW_TAG_typedef, name: "ConstIterator", scope: !4360, file: !1363, line: 990, baseType: !4450)
!4450 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapIterator<unsigned int, unsigned int, llvm::DenseMapInfo<unsigned int>, true>", scope: !14, file: !1363, line: 987, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4451, templateParams: !4495, identifier: "_ZTSN4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb1EEE")
!4451 = !{!4452, !4459, !4460, !4464, !4467, !4470, !4477, !4480, !4486, !4487, !4491, !4494}
!4452 = !DIDerivedType(tag: DW_TAG_member, name: "Ptr", scope: !4450, file: !1363, line: 999, baseType: !4453, size: 64)
!4453 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4450, file: !1363, line: 995, baseType: !4454)
!4454 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4455, size: 64)
!4455 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !4450, file: !1363, line: 994, baseType: !4456)
!4456 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !4457, file: !1380, line: 233, baseType: !4370)
!4457 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<unsigned int, unsigned int>, std::pair<unsigned int, unsigned int> >", scope: !14, file: !1380, line: 233, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !4458, identifier: "_ZTSN4llvm11conditionalILb1EKSt4pairIjjES2_EE")
!4458 = !{!2014, !4369, !4421}
!4459 = !DIDerivedType(tag: DW_TAG_member, name: "End", scope: !4450, file: !1363, line: 999, baseType: !4453, size: 64, offset: 64)
!4460 = !DISubprogram(name: "DenseMapIterator", scope: !4450, file: !1363, line: 1001, type: !4461, scopeLine: 1001, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4461 = !DISubroutineType(types: !4462)
!4462 = !{null, !4463}
!4463 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4450, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4464 = !DISubprogram(name: "DenseMapIterator", scope: !4450, file: !1363, line: 1003, type: !4465, scopeLine: 1003, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4465 = !DISubroutineType(types: !4466)
!4466 = !{null, !4463, !4453, !4453, !145}
!4467 = !DISubprogram(name: "DenseMapIterator", scope: !4450, file: !1363, line: 1011, type: !4468, scopeLine: 1011, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4468 = !DISubroutineType(types: !4469)
!4469 = !{null, !4463, !4433}
!4470 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb1EEdeEv", scope: !4450, file: !1363, line: 1015, type: !4471, scopeLine: 1015, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4471 = !DISubroutineType(types: !4472)
!4472 = !{!4473, !4475}
!4473 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !4450, file: !1363, line: 996, baseType: !4474)
!4474 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4455, size: 64)
!4475 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4476, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4476 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4450)
!4477 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb1EEptEv", scope: !4450, file: !1363, line: 1018, type: !4478, scopeLine: 1018, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4478 = !DISubroutineType(types: !4479)
!4479 = !{!4453, !4475}
!4480 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb1EEeqERKS3_", scope: !4450, file: !1363, line: 1022, type: !4481, scopeLine: 1022, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4481 = !DISubroutineType(types: !4482)
!4482 = !{!145, !4475, !4483}
!4483 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4484, size: 64)
!4484 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4485)
!4485 = !DIDerivedType(tag: DW_TAG_typedef, name: "ConstIterator", scope: !4450, file: !1363, line: 990, baseType: !4450)
!4486 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb1EEneERKS3_", scope: !4450, file: !1363, line: 1025, type: !4481, scopeLine: 1025, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4487 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb1EEppEv", scope: !4450, file: !1363, line: 1029, type: !4488, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4488 = !DISubroutineType(types: !4489)
!4489 = !{!4490, !4463}
!4490 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4450, size: 64)
!4491 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb1EEppEi", scope: !4450, file: !1363, line: 1034, type: !4492, scopeLine: 1034, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4492 = !DISubroutineType(types: !4493)
!4493 = !{!4450, !4463, !32}
!4494 = !DISubprogram(name: "AdvancePastEmptyBuckets", linkageName: "_ZN4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb1EE23AdvancePastEmptyBucketsEv", scope: !4450, file: !1363, line: 1039, type: !4461, scopeLine: 1039, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4495 = !{!2052, !4496, !2054, !2072}
!4496 = !DITemplateTypeParameter(name: "ValueT", type: !6)
!4497 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb0EEneERKNS0_IjjS2_Lb1EEE", scope: !4360, file: !1363, line: 1025, type: !4445, scopeLine: 1025, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4498 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb0EEppEv", scope: !4360, file: !1363, line: 1029, type: !4499, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4499 = !DISubroutineType(types: !4500)
!4500 = !{!4501, !4426}
!4501 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4360, size: 64)
!4502 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb0EEppEi", scope: !4360, file: !1363, line: 1034, type: !4503, scopeLine: 1034, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4503 = !DISubroutineType(types: !4504)
!4504 = !{!4360, !4426, !32}
!4505 = !DISubprogram(name: "AdvancePastEmptyBuckets", linkageName: "_ZN4llvm16DenseMapIteratorIjjNS_12DenseMapInfoIjEELb0EE23AdvancePastEmptyBucketsEv", scope: !4360, file: !1363, line: 1039, type: !4424, scopeLine: 1039, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4506 = !{!2052, !4496, !2054, !2083}
!4507 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4354, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4508 = !DISubprogram(name: "end", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E3endEv", scope: !4354, file: !1363, line: 57, type: !4357, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4509 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E5beginEv", scope: !4354, file: !1363, line: 60, type: !4510, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4510 = !DISubroutineType(types: !4511)
!4511 = !{!4512, !4513}
!4512 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !4354, file: !1363, line: 52, baseType: !4450)
!4513 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4514, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4514 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4354)
!4515 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E3endEv", scope: !4354, file: !1363, line: 63, type: !4510, scopeLine: 63, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4516 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E5emptyEv", scope: !4354, file: !1363, line: 67, type: !4517, scopeLine: 67, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4517 = !DISubroutineType(types: !4518)
!4518 = !{!145, !4513}
!4519 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E4sizeEv", scope: !4354, file: !1363, line: 70, type: !4520, scopeLine: 70, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4520 = !DISubroutineType(types: !4521)
!4521 = !{!6, !4513}
!4522 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E6resizeEm", scope: !4354, file: !1363, line: 73, type: !4523, scopeLine: 73, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4523 = !DISubroutineType(types: !4524)
!4524 = !{null, !4507, !2102}
!4525 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E5clearEv", scope: !4354, file: !1363, line: 78, type: !4526, scopeLine: 78, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4526 = !DISubroutineType(types: !4527)
!4527 = !{null, !4507}
!4528 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E5countERKj", scope: !4354, file: !1363, line: 103, type: !4529, scopeLine: 103, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4529 = !DISubroutineType(types: !4530)
!4530 = !{!145, !4513, !2065}
!4531 = !DISubprogram(name: "find", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E4findERKj", scope: !4354, file: !1363, line: 108, type: !4532, scopeLine: 108, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4532 = !DISubroutineType(types: !4533)
!4533 = !{!4359, !4507, !2065}
!4534 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E4findERKj", scope: !4354, file: !1363, line: 114, type: !4535, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4535 = !DISubroutineType(types: !4536)
!4536 = !{!4512, !4513, !2065}
!4537 = !DISubprogram(name: "lookup", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E6lookupERKj", scope: !4354, file: !1363, line: 143, type: !4538, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4538 = !DISubroutineType(types: !4539)
!4539 = !{!6, !4513, !2065}
!4540 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E6insertERKSt4pairIjjE", scope: !4354, file: !1363, line: 153, type: !4541, scopeLine: 153, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4541 = !DISubroutineType(types: !4542)
!4542 = !{!4543, !4507, !4397}
!4543 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::DenseMapIterator<unsigned int, unsigned int, llvm::DenseMapInfo<unsigned int>, false>, bool>", scope: !839, file: !1387, line: 208, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4544, templateParams: !4594, identifier: "_ZTSSt4pairIN4llvm16DenseMapIteratorIjjNS0_12DenseMapInfoIjEELb0EEEbE")
!4544 = !{!4545, !4564, !4565, !4566, !4572, !4576, !4584, !4591}
!4545 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4543, baseType: !4546, flags: DIFlagPrivate, extraData: i32 0)
!4546 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::DenseMapIterator<unsigned int, unsigned int, llvm::DenseMapInfo<unsigned int>, false>, bool>", scope: !839, file: !1387, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !4547, templateParams: !4562, identifier: "_ZTSSt11__pair_baseIN4llvm16DenseMapIteratorIjjNS0_12DenseMapInfoIjEELb0EEEbE")
!4547 = !{!4548, !4552, !4553, !4558}
!4548 = !DISubprogram(name: "__pair_base", scope: !4546, file: !1387, line: 194, type: !4549, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4549 = !DISubroutineType(types: !4550)
!4550 = !{null, !4551}
!4551 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4546, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4552 = !DISubprogram(name: "~__pair_base", scope: !4546, file: !1387, line: 195, type: !4549, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4553 = !DISubprogram(name: "__pair_base", scope: !4546, file: !1387, line: 196, type: !4554, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4554 = !DISubroutineType(types: !4555)
!4555 = !{null, !4551, !4556}
!4556 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4557, size: 64)
!4557 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4546)
!4558 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN4llvm16DenseMapIteratorIjjNS0_12DenseMapInfoIjEELb0EEEbEaSERKS5_", scope: !4546, file: !1387, line: 197, type: !4559, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!4559 = !DISubroutineType(types: !4560)
!4560 = !{!4561, !4551, !4556}
!4561 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4546, size: 64)
!4562 = !{!4563, !2143}
!4563 = !DITemplateTypeParameter(name: "_U1", type: !4360)
!4564 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !4543, file: !1387, line: 214, baseType: !4360, size: 128)
!4565 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !4543, file: !1387, line: 215, baseType: !145, size: 8, offset: 128)
!4566 = !DISubprogram(name: "pair", scope: !4543, file: !1387, line: 303, type: !4567, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4567 = !DISubroutineType(types: !4568)
!4568 = !{null, !4569, !4570}
!4569 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4543, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4570 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4571, size: 64)
!4571 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4543)
!4572 = !DISubprogram(name: "pair", scope: !4543, file: !1387, line: 304, type: !4573, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4573 = !DISubroutineType(types: !4574)
!4574 = !{null, !4569, !4575}
!4575 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !4543, size: 64)
!4576 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm16DenseMapIteratorIjjNS0_12DenseMapInfoIjEELb0EEEbEaSERKS5_", scope: !4543, file: !1387, line: 378, type: !4577, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4577 = !DISubroutineType(types: !4578)
!4578 = !{!4579, !4569, !4580}
!4579 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4543, size: 64)
!4580 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !4581, file: !1281, line: 1928, baseType: !4570)
!4581 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::DenseMapIterator<unsigned int, unsigned int, llvm::DenseMapInfo<unsigned int>, false>, bool> &, const std::__nonesuch_no_braces &>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !4582, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN4llvm16DenseMapIteratorIjjNS1_12DenseMapInfoIjEELb0EEEbERKSt20__nonesuch_no_bracesE")
!4582 = !{!1472, !4583, !1474}
!4583 = !DITemplateTypeParameter(name: "_Iftrue", type: !4570)
!4584 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm16DenseMapIteratorIjjNS0_12DenseMapInfoIjEELb0EEEbEaSEOS5_", scope: !4543, file: !1387, line: 389, type: !4585, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4585 = !DISubroutineType(types: !4586)
!4586 = !{!4579, !4569, !4587}
!4587 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !4588, file: !1281, line: 1928, baseType: !4575)
!4588 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::DenseMapIterator<unsigned int, unsigned int, llvm::DenseMapInfo<unsigned int>, false>, bool> &&, std::__nonesuch_no_braces &&>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !4589, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN4llvm16DenseMapIteratorIjjNS1_12DenseMapInfoIjEELb0EEEbEOSt20__nonesuch_no_bracesE")
!4589 = !{!1472, !4590, !1485}
!4590 = !DITemplateTypeParameter(name: "_Iftrue", type: !4575)
!4591 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN4llvm16DenseMapIteratorIjjNS0_12DenseMapInfoIjEELb0EEEbE4swapERS5_", scope: !4543, file: !1387, line: 424, type: !4592, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4592 = !DISubroutineType(types: !4593)
!4593 = !{null, !4569, !4579}
!4594 = !{!4595, !2176}
!4595 = !DITemplateTypeParameter(name: "_T1", type: !4360)
!4596 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E6insertEOSt4pairIjjE", scope: !4354, file: !1363, line: 168, type: !4597, scopeLine: 168, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4597 = !DISubroutineType(types: !4598)
!4598 = !{!4543, !4507, !4401}
!4599 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E5eraseERKj", scope: !4354, file: !1363, line: 190, type: !4600, scopeLine: 190, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4600 = !DISubroutineType(types: !4601)
!4601 = !{!145, !4507, !2065}
!4602 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E5eraseENS_16DenseMapIteratorIjjS3_Lb0EEE", scope: !4354, file: !1363, line: 201, type: !4603, scopeLine: 201, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4603 = !DISubroutineType(types: !4604)
!4604 = !{null, !4507, !4359}
!4605 = !DISubprogram(name: "FindAndConstruct", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E16FindAndConstructERKj", scope: !4354, file: !1363, line: 209, type: !4606, scopeLine: 209, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4606 = !DISubroutineType(types: !4607)
!4607 = !{!4608, !4507, !2065}
!4608 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4609, size: 64)
!4609 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !4354, file: !1363, line: 48, baseType: !4610)
!4610 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !4354, file: !1363, line: 43, baseType: !4371)
!4611 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_EixERKj", scope: !4354, file: !1363, line: 217, type: !4612, scopeLine: 217, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4612 = !DISubroutineType(types: !4613)
!4613 = !{!2428, !4507, !2065}
!4614 = !DISubprogram(name: "FindAndConstruct", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E16FindAndConstructEOj", scope: !4354, file: !1363, line: 222, type: !4615, scopeLine: 222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4615 = !DISubroutineType(types: !4616)
!4616 = !{!4608, !4507, !2198}
!4617 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_EixEOj", scope: !4354, file: !1363, line: 230, type: !4618, scopeLine: 230, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4618 = !DISubroutineType(types: !4619)
!4619 = !{!2428, !4507, !2198}
!4620 = !DISubprogram(name: "isPointerIntoBucketsArray", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E25isPointerIntoBucketsArrayEPKv", scope: !4354, file: !1363, line: 238, type: !4621, scopeLine: 238, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4621 = !DISubroutineType(types: !4622)
!4622 = !{!145, !4513, !124}
!4623 = !DISubprogram(name: "getPointerIntoBucketsArray", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E26getPointerIntoBucketsArrayEv", scope: !4354, file: !1363, line: 245, type: !4624, scopeLine: 245, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4624 = !DISubroutineType(types: !4625)
!4625 = !{!124, !4513}
!4626 = !DISubprogram(name: "DenseMapBase", scope: !4354, file: !1363, line: 248, type: !4526, scopeLine: 248, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4627 = !DISubprogram(name: "destroyAll", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E10destroyAllEv", scope: !4354, file: !1363, line: 250, type: !4526, scopeLine: 250, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4628 = !DISubprogram(name: "initEmpty", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E9initEmptyEv", scope: !4354, file: !1363, line: 267, type: !4526, scopeLine: 267, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4629 = !DISubprogram(name: "moveFromOldBuckets", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E18moveFromOldBucketsEPSt4pairIjjES8_", scope: !4354, file: !1363, line: 278, type: !4630, scopeLine: 278, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4630 = !DISubroutineType(types: !4631)
!4631 = !{null, !4507, !4632, !4632}
!4632 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4610, size: 64)
!4633 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E4swapERS5_", scope: !4354, file: !1363, line: 328, type: !4634, scopeLine: 328, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4634 = !DISubroutineType(types: !4635)
!4635 = !{null, !4507, !4636}
!4636 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4354, size: 64)
!4637 = !DISubprogram(name: "getHashValue", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E12getHashValueERKj", scope: !4354, file: !1363, line: 333, type: !2063, scopeLine: 333, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4638 = !DISubprogram(name: "getEmptyKey", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E11getEmptyKeyEv", scope: !4354, file: !1363, line: 340, type: !2221, scopeLine: 340, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4639 = !DISubprogram(name: "getTombstoneKey", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E15getTombstoneKeyEv", scope: !4354, file: !1363, line: 343, type: !2221, scopeLine: 343, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4640 = !DISubprogram(name: "getNumEntries", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E13getNumEntriesEv", scope: !4354, file: !1363, line: 348, type: !4520, scopeLine: 348, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4641 = !DISubprogram(name: "setNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E13setNumEntriesEj", scope: !4354, file: !1363, line: 351, type: !4642, scopeLine: 351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4642 = !DISubroutineType(types: !4643)
!4643 = !{null, !4507, !6}
!4644 = !DISubprogram(name: "incrementNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E19incrementNumEntriesEv", scope: !4354, file: !1363, line: 354, type: !4526, scopeLine: 354, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4645 = !DISubprogram(name: "decrementNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E19decrementNumEntriesEv", scope: !4354, file: !1363, line: 357, type: !4526, scopeLine: 357, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4646 = !DISubprogram(name: "getNumTombstones", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E16getNumTombstonesEv", scope: !4354, file: !1363, line: 360, type: !4520, scopeLine: 360, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4647 = !DISubprogram(name: "setNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E16setNumTombstonesEj", scope: !4354, file: !1363, line: 363, type: !4642, scopeLine: 363, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4648 = !DISubprogram(name: "incrementNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E22incrementNumTombstonesEv", scope: !4354, file: !1363, line: 366, type: !4526, scopeLine: 366, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4649 = !DISubprogram(name: "decrementNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E22decrementNumTombstonesEv", scope: !4354, file: !1363, line: 369, type: !4526, scopeLine: 369, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4650 = !DISubprogram(name: "getBuckets", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E10getBucketsEv", scope: !4354, file: !1363, line: 372, type: !4651, scopeLine: 372, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4651 = !DISubroutineType(types: !4652)
!4652 = !{!4653, !4513}
!4653 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4654, size: 64)
!4654 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4610)
!4655 = !DISubprogram(name: "getBuckets", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E10getBucketsEv", scope: !4354, file: !1363, line: 375, type: !4656, scopeLine: 375, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4656 = !DISubroutineType(types: !4657)
!4657 = !{!4632, !4507}
!4658 = !DISubprogram(name: "getNumBuckets", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E13getNumBucketsEv", scope: !4354, file: !1363, line: 378, type: !4520, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4659 = !DISubprogram(name: "getBucketsEnd", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E13getBucketsEndEv", scope: !4354, file: !1363, line: 381, type: !4656, scopeLine: 381, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4660 = !DISubprogram(name: "getBucketsEnd", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E13getBucketsEndEv", scope: !4354, file: !1363, line: 384, type: !4651, scopeLine: 384, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4661 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E4growEj", scope: !4354, file: !1363, line: 388, type: !4642, scopeLine: 388, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4662 = !DISubprogram(name: "shrink_and_clear", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E16shrink_and_clearEv", scope: !4354, file: !1363, line: 392, type: !4526, scopeLine: 392, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4663 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E16InsertIntoBucketERKjS7_PSt4pairIjjE", scope: !4354, file: !1363, line: 397, type: !4664, scopeLine: 397, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4664 = !DISubroutineType(types: !4665)
!4665 = !{!4632, !4507, !2065, !2065, !4632}
!4666 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E16InsertIntoBucketERKjOjPSt4pairIjjE", scope: !4354, file: !1363, line: 407, type: !4667, scopeLine: 407, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4667 = !DISubroutineType(types: !4668)
!4668 = !{!4632, !4507, !2065, !2198, !4632}
!4669 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E16InsertIntoBucketEOjS6_PSt4pairIjjE", scope: !4354, file: !1363, line: 416, type: !4670, scopeLine: 416, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4670 = !DISubroutineType(types: !4671)
!4671 = !{!4632, !4507, !2198, !2198, !4632}
!4672 = !DISubprogram(name: "InsertIntoBucketImpl", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E20InsertIntoBucketImplERKjPSt4pairIjjE", scope: !4354, file: !1363, line: 425, type: !4673, scopeLine: 425, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4673 = !DISubroutineType(types: !4674)
!4674 = !{!4632, !4507, !2065, !4632}
!4675 = !DISubprogram(name: "getMemorySize", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIjjNS_12DenseMapInfoIjEEEEjjS3_E13getMemorySizeEv", scope: !4354, file: !1363, line: 527, type: !4676, scopeLine: 527, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4676 = !DISubroutineType(types: !4677)
!4677 = !{!2102, !4513}
!4678 = !{!4679, !2052, !4496, !2054}
!4679 = !DITemplateTypeParameter(name: "DerivedT", type: !4351)
!4680 = !DIDerivedType(tag: DW_TAG_member, name: "Buckets", scope: !4351, file: !1363, line: 543, baseType: !4349, size: 64)
!4681 = !DIDerivedType(tag: DW_TAG_member, name: "NumEntries", scope: !4351, file: !1363, line: 544, baseType: !6, size: 32, offset: 64)
!4682 = !DIDerivedType(tag: DW_TAG_member, name: "NumTombstones", scope: !4351, file: !1363, line: 545, baseType: !6, size: 32, offset: 96)
!4683 = !DIDerivedType(tag: DW_TAG_member, name: "NumBuckets", scope: !4351, file: !1363, line: 546, baseType: !6, size: 32, offset: 128)
!4684 = !DISubprogram(name: "DenseMap", scope: !4351, file: !1363, line: 549, type: !4685, scopeLine: 549, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4685 = !DISubroutineType(types: !4686)
!4686 = !{null, !4687, !6}
!4687 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4351, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4688 = !DISubprogram(name: "DenseMap", scope: !4351, file: !1363, line: 553, type: !4689, scopeLine: 553, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4689 = !DISubroutineType(types: !4690)
!4690 = !{null, !4687, !4691}
!4691 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4692, size: 64)
!4692 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4351)
!4693 = !DISubprogram(name: "DenseMap", scope: !4351, file: !1363, line: 559, type: !4694, scopeLine: 559, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4694 = !DISubroutineType(types: !4695)
!4695 = !{null, !4687, !4696}
!4696 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !4351, size: 64)
!4697 = !DISubprogram(name: "~DenseMap", scope: !4351, file: !1363, line: 571, type: !4698, scopeLine: 571, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4698 = !DISubroutineType(types: !4699)
!4699 = !{null, !4687}
!4700 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm8DenseMapIjjNS_12DenseMapInfoIjEEE4swapERS3_", scope: !4351, file: !1363, line: 576, type: !4701, scopeLine: 576, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4701 = !DISubroutineType(types: !4702)
!4702 = !{null, !4687, !4703}
!4703 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4351, size: 64)
!4704 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8DenseMapIjjNS_12DenseMapInfoIjEEEaSERKS3_", scope: !4351, file: !1363, line: 583, type: !4705, scopeLine: 583, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4705 = !DISubroutineType(types: !4706)
!4706 = !{!4703, !4687, !4691}
!4707 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8DenseMapIjjNS_12DenseMapInfoIjEEEaSEOS3_", scope: !4351, file: !1363, line: 589, type: !4708, scopeLine: 589, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4708 = !DISubroutineType(types: !4709)
!4709 = !{!4703, !4687, !4696}
!4710 = !DISubprogram(name: "copyFrom", linkageName: "_ZN4llvm8DenseMapIjjNS_12DenseMapInfoIjEEE8copyFromERKS3_", scope: !4351, file: !1363, line: 598, type: !4689, scopeLine: 598, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4711 = !DISubprogram(name: "init", linkageName: "_ZN4llvm8DenseMapIjjNS_12DenseMapInfoIjEEE4initEj", scope: !4351, file: !1363, line: 609, type: !4685, scopeLine: 609, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4712 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm8DenseMapIjjNS_12DenseMapInfoIjEEE4growEj", scope: !4351, file: !1363, line: 618, type: !4685, scopeLine: 618, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4713 = !DISubprogram(name: "shrink_and_clear", linkageName: "_ZN4llvm8DenseMapIjjNS_12DenseMapInfoIjEEE16shrink_and_clearEv", scope: !4351, file: !1363, line: 635, type: !4698, scopeLine: 635, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4714 = !DISubprogram(name: "getNumEntries", linkageName: "_ZNK4llvm8DenseMapIjjNS_12DenseMapInfoIjEEE13getNumEntriesEv", scope: !4351, file: !1363, line: 653, type: !4715, scopeLine: 653, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4715 = !DISubroutineType(types: !4716)
!4716 = !{!6, !4717}
!4717 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4692, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4718 = !DISubprogram(name: "setNumEntries", linkageName: "_ZN4llvm8DenseMapIjjNS_12DenseMapInfoIjEEE13setNumEntriesEj", scope: !4351, file: !1363, line: 656, type: !4685, scopeLine: 656, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4719 = !DISubprogram(name: "getNumTombstones", linkageName: "_ZNK4llvm8DenseMapIjjNS_12DenseMapInfoIjEEE16getNumTombstonesEv", scope: !4351, file: !1363, line: 660, type: !4715, scopeLine: 660, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4720 = !DISubprogram(name: "setNumTombstones", linkageName: "_ZN4llvm8DenseMapIjjNS_12DenseMapInfoIjEEE16setNumTombstonesEj", scope: !4351, file: !1363, line: 663, type: !4685, scopeLine: 663, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4721 = !DISubprogram(name: "getBuckets", linkageName: "_ZNK4llvm8DenseMapIjjNS_12DenseMapInfoIjEEE10getBucketsEv", scope: !4351, file: !1363, line: 667, type: !4722, scopeLine: 667, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4722 = !DISubroutineType(types: !4723)
!4723 = !{!4349, !4717}
!4724 = !DISubprogram(name: "getNumBuckets", linkageName: "_ZNK4llvm8DenseMapIjjNS_12DenseMapInfoIjEEE13getNumBucketsEv", scope: !4351, file: !1363, line: 671, type: !4715, scopeLine: 671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4725 = !DISubprogram(name: "allocateBuckets", linkageName: "_ZN4llvm8DenseMapIjjNS_12DenseMapInfoIjEEE15allocateBucketsEj", scope: !4351, file: !1363, line: 675, type: !4726, scopeLine: 675, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4726 = !DISubroutineType(types: !4727)
!4727 = !{!145, !4687, !6}
!4728 = !{!2052, !4496, !2054}
!4729 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4351, size: 64)
!4730 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4692, size: 64)
!4731 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4514, size: 64)
!4732 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !4733, file: !2317, line: 100, baseType: !4765)
!4733 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<std::pair<unsigned int, unsigned int>, void>", scope: !14, file: !2317, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4734, templateParams: !4821, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonISt4pairIjjEvEE")
!4734 = !{!4735, !4736, !4747, !4751, !4754, !4759, !4762, !4766, !4769, !4774, !4775, !4776, !4777, !4778, !4783, !4788, !4789, !4790, !4793, !4794, !4797, !4801, !4805, !4809, !4813, !4816, !4819, !4820}
!4735 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4733, baseType: !2321, flags: DIFlagPublic, extraData: i32 0)
!4736 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !4733, file: !2317, line: 74, baseType: !4737, size: 64, offset: 192)
!4737 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !4733, file: !2317, line: 73, baseType: !4738)
!4738 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<std::pair<unsigned int, unsigned int>, char, char, char, char, char, char>", scope: !14, file: !2345, line: 199, size: 64, flags: DIFlagTypePassByValue, elements: !4739, templateParams: !4745, identifier: "_ZTSN4llvm21AlignedCharArrayUnionISt4pairIjjEccccccEE")
!4739 = !{!4740}
!4740 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4738, baseType: !4741, extraData: i32 0)
!4741 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<4UL, 8UL>", scope: !14, file: !2345, line: 75, size: 64, flags: DIFlagTypePassByValue, elements: !4742, templateParams: !4744, identifier: "_ZTSN4llvm16AlignedCharArrayILm4ELm8EEE")
!4742 = !{!4743}
!4743 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !4741, file: !2345, line: 76, baseType: !3350, size: 64, align: 32)
!4744 = !{!2355, !3352}
!4745 = !{!4746, !2359, !2360, !2361, !2362, !2363, !2364}
!4746 = !DITemplateTypeParameter(name: "T1", type: !4371)
!4747 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !4733, file: !2317, line: 78, type: !4748, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4748 = !DISubroutineType(types: !4749)
!4749 = !{null, !4750, !2102}
!4750 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4733, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4751 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairIjjEvE8grow_podEmm", scope: !4733, file: !2317, line: 80, type: !4752, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4752 = !DISubroutineType(types: !4753)
!4753 = !{null, !4750, !2102, !2102}
!4754 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairIjjEvE7isSmallEv", scope: !4733, file: !2317, line: 86, type: !4755, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4755 = !DISubroutineType(types: !4756)
!4756 = !{!145, !4757}
!4757 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4758, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4758 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4733)
!4759 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairIjjEvE12resetToSmallEv", scope: !4733, file: !2317, line: 91, type: !4760, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4760 = !DISubroutineType(types: !4761)
!4761 = !{null, !4750}
!4762 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairIjjEvE6setEndEPS2_", scope: !4733, file: !2317, line: 95, type: !4763, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4763 = !DISubroutineType(types: !4764)
!4764 = !{null, !4750, !4765}
!4765 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4371, size: 64)
!4766 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairIjjEvE5beginEv", scope: !4733, file: !2317, line: 112, type: !4767, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4767 = !DISubroutineType(types: !4768)
!4768 = !{!4732, !4750}
!4769 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairIjjEvE5beginEv", scope: !4733, file: !2317, line: 113, type: !4770, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4770 = !DISubroutineType(types: !4771)
!4771 = !{!4772, !4757}
!4772 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !4733, file: !2317, line: 101, baseType: !4773)
!4773 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4370, size: 64)
!4774 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairIjjEvE3endEv", scope: !4733, file: !2317, line: 114, type: !4767, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4775 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairIjjEvE3endEv", scope: !4733, file: !2317, line: 115, type: !4770, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4776 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairIjjEvE12capacity_ptrEv", scope: !4733, file: !2317, line: 117, type: !4767, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4777 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairIjjEvE12capacity_ptrEv", scope: !4733, file: !2317, line: 118, type: !4770, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4778 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairIjjEvE6rbeginEv", scope: !4733, file: !2317, line: 122, type: !4779, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4779 = !DISubroutineType(types: !4780)
!4780 = !{!4781, !4750}
!4781 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !4733, file: !2317, line: 104, baseType: !4782)
!4782 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<std::pair<unsigned int, unsigned int> *>", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPSt4pairIjjEE")
!4783 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairIjjEvE6rbeginEv", scope: !4733, file: !2317, line: 123, type: !4784, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4784 = !DISubroutineType(types: !4785)
!4785 = !{!4786, !4757}
!4786 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !4733, file: !2317, line: 103, baseType: !4787)
!4787 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const std::pair<unsigned int, unsigned int> *>", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKSt4pairIjjEE")
!4788 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairIjjEvE4rendEv", scope: !4733, file: !2317, line: 124, type: !4779, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4789 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairIjjEvE4rendEv", scope: !4733, file: !2317, line: 125, type: !4784, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4790 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairIjjEvE4sizeEv", scope: !4733, file: !2317, line: 127, type: !4791, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4791 = !DISubroutineType(types: !4792)
!4792 = !{!2411, !4757}
!4793 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairIjjEvE8max_sizeEv", scope: !4733, file: !2317, line: 128, type: !4791, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4794 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairIjjEvE8capacityEv", scope: !4733, file: !2317, line: 132, type: !4795, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4795 = !DISubroutineType(types: !4796)
!4796 = !{!2102, !4757}
!4797 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairIjjEvE4dataEv", scope: !4733, file: !2317, line: 135, type: !4798, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4798 = !DISubroutineType(types: !4799)
!4799 = !{!4800, !4750}
!4800 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4733, file: !2317, line: 108, baseType: !4765)
!4801 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairIjjEvE4dataEv", scope: !4733, file: !2317, line: 137, type: !4802, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4802 = !DISubroutineType(types: !4803)
!4803 = !{!4804, !4757}
!4804 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !4733, file: !2317, line: 109, baseType: !4773)
!4805 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairIjjEvEixEj", scope: !4733, file: !2317, line: 139, type: !4806, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4806 = !DISubroutineType(types: !4807)
!4807 = !{!4808, !4750, !6}
!4808 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !4733, file: !2317, line: 106, baseType: !4405)
!4809 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairIjjEvEixEj", scope: !4733, file: !2317, line: 143, type: !4810, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4810 = !DISubroutineType(types: !4811)
!4811 = !{!4812, !4757, !6}
!4812 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !4733, file: !2317, line: 107, baseType: !4397)
!4813 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairIjjEvE5frontEv", scope: !4733, file: !2317, line: 148, type: !4814, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4814 = !DISubroutineType(types: !4815)
!4815 = !{!4808, !4750}
!4816 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairIjjEvE5frontEv", scope: !4733, file: !2317, line: 152, type: !4817, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4817 = !DISubroutineType(types: !4818)
!4818 = !{!4812, !4757}
!4819 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairIjjEvE4backEv", scope: !4733, file: !2317, line: 157, type: !4814, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4820 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairIjjEvE4backEv", scope: !4733, file: !2317, line: 161, type: !4817, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4821 = !{!4822, !2442}
!4822 = !DITemplateTypeParameter(name: "T", type: !4371)
!4823 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1589, size: 64)
!4824 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "move_iterator<std::pair<llvm::MachineBasicBlock *, unsigned int> *>", scope: !839, file: !1093, line: 1007, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4825, templateParams: !1722, identifier: "_ZTSSt13move_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjEE")
!4825 = !{!4826, !4827, !4831, !4835, !4840, !4848, !4852, !4856, !4859, !4860, !4861, !4865, !4868, !4869, !4870}
!4826 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !4824, file: !1093, line: 1010, baseType: !1430, size: 64, flags: DIFlagProtected)
!4827 = !DISubprogram(name: "move_iterator", scope: !4824, file: !1093, line: 1029, type: !4828, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4828 = !DISubroutineType(types: !4829)
!4829 = !{null, !4830}
!4830 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4824, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4831 = !DISubprogram(name: "move_iterator", scope: !4824, file: !1093, line: 1033, type: !4832, scopeLine: 1033, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4832 = !DISubroutineType(types: !4833)
!4833 = !{null, !4830, !4834}
!4834 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator_type", scope: !4824, file: !1093, line: 1016, baseType: !1430)
!4835 = !DISubprogram(name: "base", linkageName: "_ZNKSt13move_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjEE4baseEv", scope: !4824, file: !1093, line: 1042, type: !4836, scopeLine: 1042, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4836 = !DISubroutineType(types: !4837)
!4837 = !{!4834, !4838}
!4838 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4839, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4839 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4824)
!4840 = !DISubprogram(name: "operator*", linkageName: "_ZNKSt13move_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjEEdeEv", scope: !4824, file: !1093, line: 1046, type: !4841, scopeLine: 1046, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4841 = !DISubroutineType(types: !4842)
!4842 = !{!4843, !4838}
!4843 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !4824, file: !1093, line: 1026, baseType: !4844)
!4844 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !4845, file: !1281, line: 1928, baseType: !1464)
!4845 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::MachineBasicBlock *, unsigned int> &&, std::pair<llvm::MachineBasicBlock *, unsigned int> &>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !4846, identifier: "_ZTSSt11conditionalILb1EOSt4pairIPN4llvm17MachineBasicBlockEjERS4_E")
!4846 = !{!1472, !1484, !4847}
!4847 = !DITemplateTypeParameter(name: "_Iffalse", type: !1468)
!4848 = !DISubprogram(name: "operator->", linkageName: "_ZNKSt13move_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjEEptEv", scope: !4824, file: !1093, line: 1050, type: !4849, scopeLine: 1050, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4849 = !DISubroutineType(types: !4850)
!4850 = !{!4851, !4838}
!4851 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4824, file: !1093, line: 1021, baseType: !1430)
!4852 = !DISubprogram(name: "operator++", linkageName: "_ZNSt13move_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjEEppEv", scope: !4824, file: !1093, line: 1054, type: !4853, scopeLine: 1054, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4853 = !DISubroutineType(types: !4854)
!4854 = !{!4855, !4830}
!4855 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4824, size: 64)
!4856 = !DISubprogram(name: "operator++", linkageName: "_ZNSt13move_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjEEppEi", scope: !4824, file: !1093, line: 1061, type: !4857, scopeLine: 1061, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4857 = !DISubroutineType(types: !4858)
!4858 = !{!4824, !4830, !32}
!4859 = !DISubprogram(name: "operator--", linkageName: "_ZNSt13move_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjEEmmEv", scope: !4824, file: !1093, line: 1069, type: !4853, scopeLine: 1069, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4860 = !DISubprogram(name: "operator--", linkageName: "_ZNSt13move_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjEEmmEi", scope: !4824, file: !1093, line: 1076, type: !4857, scopeLine: 1076, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4861 = !DISubprogram(name: "operator+", linkageName: "_ZNKSt13move_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjEEplEl", scope: !4824, file: !1093, line: 1084, type: !4862, scopeLine: 1084, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4862 = !DISubroutineType(types: !4863)
!4863 = !{!4824, !4838, !4864}
!4864 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !4824, file: !1093, line: 1019, baseType: !1744)
!4865 = !DISubprogram(name: "operator+=", linkageName: "_ZNSt13move_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjEEpLEl", scope: !4824, file: !1093, line: 1088, type: !4866, scopeLine: 1088, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4866 = !DISubroutineType(types: !4867)
!4867 = !{!4855, !4830, !4864}
!4868 = !DISubprogram(name: "operator-", linkageName: "_ZNKSt13move_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjEEmiEl", scope: !4824, file: !1093, line: 1095, type: !4862, scopeLine: 1095, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4869 = !DISubprogram(name: "operator-=", linkageName: "_ZNSt13move_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjEEmIEl", scope: !4824, file: !1093, line: 1099, type: !4866, scopeLine: 1099, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4870 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt13move_iteratorIPSt4pairIPN4llvm17MachineBasicBlockEjEEixEl", scope: !4824, file: !1093, line: 1106, type: !4871, scopeLine: 1106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4871 = !DISubroutineType(types: !4872)
!4872 = !{!4843, !4838, !4864}
!4873 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2091, size: 64)
!4874 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !4875, file: !2317, line: 100, baseType: !4903)
!4875 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<llvm::MachineInstr *, void>", scope: !14, file: !2317, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4876, templateParams: !4962, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvEE")
!4876 = !{!4877, !4878, !4885, !4889, !4892, !4897, !4900, !4904, !4907, !4913, !4914, !4915, !4916, !4917, !4922, !4927, !4928, !4929, !4932, !4933, !4936, !4940, !4944, !4949, !4954, !4957, !4960, !4961}
!4877 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4875, baseType: !2321, flags: DIFlagPublic, extraData: i32 0)
!4878 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !4875, file: !2317, line: 74, baseType: !4879, size: 64, offset: 192)
!4879 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !4875, file: !2317, line: 73, baseType: !4880)
!4880 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<llvm::MachineInstr *, char, char, char, char, char, char>", scope: !14, file: !2345, line: 199, size: 64, flags: DIFlagTypePassByValue, elements: !4881, templateParams: !4883, identifier: "_ZTSN4llvm21AlignedCharArrayUnionIPNS_12MachineInstrEccccccEE")
!4881 = !{!4882}
!4882 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4880, baseType: !3347, extraData: i32 0)
!4883 = !{!4884, !2359, !2360, !2361, !2362, !2363, !2364}
!4884 = !DITemplateTypeParameter(name: "T1", type: !268)
!4885 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !4875, file: !2317, line: 78, type: !4886, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4886 = !DISubroutineType(types: !4887)
!4887 = !{null, !4888, !2102}
!4888 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4875, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4889 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE8grow_podEmm", scope: !4875, file: !2317, line: 80, type: !4890, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4890 = !DISubroutineType(types: !4891)
!4891 = !{null, !4888, !2102, !2102}
!4892 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE7isSmallEv", scope: !4875, file: !2317, line: 86, type: !4893, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4893 = !DISubroutineType(types: !4894)
!4894 = !{!145, !4895}
!4895 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4896, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4896 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4875)
!4897 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE12resetToSmallEv", scope: !4875, file: !2317, line: 91, type: !4898, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4898 = !DISubroutineType(types: !4899)
!4899 = !{null, !4888}
!4900 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE6setEndEPS2_", scope: !4875, file: !2317, line: 95, type: !4901, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4901 = !DISubroutineType(types: !4902)
!4902 = !{null, !4888, !4903}
!4903 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !268, size: 64)
!4904 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE5beginEv", scope: !4875, file: !2317, line: 112, type: !4905, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4905 = !DISubroutineType(types: !4906)
!4906 = !{!4874, !4888}
!4907 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE5beginEv", scope: !4875, file: !2317, line: 113, type: !4908, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4908 = !DISubroutineType(types: !4909)
!4909 = !{!4910, !4895}
!4910 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !4875, file: !2317, line: 101, baseType: !4911)
!4911 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4912, size: 64)
!4912 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !268)
!4913 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE3endEv", scope: !4875, file: !2317, line: 114, type: !4905, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4914 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE3endEv", scope: !4875, file: !2317, line: 115, type: !4908, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4915 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE12capacity_ptrEv", scope: !4875, file: !2317, line: 117, type: !4905, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4916 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE12capacity_ptrEv", scope: !4875, file: !2317, line: 118, type: !4908, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4917 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE6rbeginEv", scope: !4875, file: !2317, line: 122, type: !4918, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4918 = !DISubroutineType(types: !4919)
!4919 = !{!4920, !4888}
!4920 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !4875, file: !2317, line: 104, baseType: !4921)
!4921 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<llvm::MachineInstr **>", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPPN4llvm12MachineInstrEE")
!4922 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE6rbeginEv", scope: !4875, file: !2317, line: 123, type: !4923, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4923 = !DISubroutineType(types: !4924)
!4924 = !{!4925, !4895}
!4925 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !4875, file: !2317, line: 103, baseType: !4926)
!4926 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<llvm::MachineInstr *const *>", scope: !839, file: !1093, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKPN4llvm12MachineInstrEE")
!4927 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE4rendEv", scope: !4875, file: !2317, line: 124, type: !4918, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4928 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE4rendEv", scope: !4875, file: !2317, line: 125, type: !4923, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4929 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE4sizeEv", scope: !4875, file: !2317, line: 127, type: !4930, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4930 = !DISubroutineType(types: !4931)
!4931 = !{!2411, !4895}
!4932 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE8max_sizeEv", scope: !4875, file: !2317, line: 128, type: !4930, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4933 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE8capacityEv", scope: !4875, file: !2317, line: 132, type: !4934, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4934 = !DISubroutineType(types: !4935)
!4935 = !{!2102, !4895}
!4936 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE4dataEv", scope: !4875, file: !2317, line: 135, type: !4937, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4937 = !DISubroutineType(types: !4938)
!4938 = !{!4939, !4888}
!4939 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !4875, file: !2317, line: 108, baseType: !4903)
!4940 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE4dataEv", scope: !4875, file: !2317, line: 137, type: !4941, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4941 = !DISubroutineType(types: !4942)
!4942 = !{!4943, !4895}
!4943 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !4875, file: !2317, line: 109, baseType: !4911)
!4944 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvEixEj", scope: !4875, file: !2317, line: 139, type: !4945, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4945 = !DISubroutineType(types: !4946)
!4946 = !{!4947, !4888, !6}
!4947 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !4875, file: !2317, line: 106, baseType: !4948)
!4948 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !268, size: 64)
!4949 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvEixEj", scope: !4875, file: !2317, line: 143, type: !4950, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4950 = !DISubroutineType(types: !4951)
!4951 = !{!4952, !4895, !6}
!4952 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !4875, file: !2317, line: 107, baseType: !4953)
!4953 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4912, size: 64)
!4954 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE5frontEv", scope: !4875, file: !2317, line: 148, type: !4955, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4955 = !DISubroutineType(types: !4956)
!4956 = !{!4947, !4888}
!4957 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE5frontEv", scope: !4875, file: !2317, line: 152, type: !4958, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4958 = !DISubroutineType(types: !4959)
!4959 = !{!4952, !4895}
!4960 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE4backEv", scope: !4875, file: !2317, line: 157, type: !4955, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4961 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIPNS_12MachineInstrEvE4backEv", scope: !4875, file: !2317, line: 161, type: !4958, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4962 = !{!4963, !2442}
!4963 = !DITemplateTypeParameter(name: "T", type: !268)
!4964 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Iter_equals_val<llvm::MachineBasicBlock *const>", scope: !4966, file: !4965, line: 229, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4967, templateParams: !4973, identifier: "_ZTSN9__gnu_cxx5__ops16_Iter_equals_valIKPN4llvm17MachineBasicBlockEEE")
!4965 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/predefined_ops.h", directory: "", checksumkind: CSK_MD5, checksum: "c4488885b044d9477796f6d04761c9e8")
!4966 = !DINamespace(name: "__ops", scope: !5)
!4967 = !{!4968, !4969}
!4968 = !DIDerivedType(tag: DW_TAG_member, name: "_M_value", scope: !4964, file: !4965, line: 231, baseType: !3421, size: 64)
!4969 = !DISubprogram(name: "_Iter_equals_val", scope: !4964, file: !4965, line: 234, type: !4970, scopeLine: 234, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4970 = !DISubroutineType(types: !4971)
!4971 = !{null, !4972, !3421}
!4972 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4964, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4973 = !{!4974}
!4974 = !DITemplateTypeParameter(name: "_Value", type: !3381)
!4975 = !DIDerivedType(tag: DW_TAG_typedef, name: "use_iterator", scope: !2476, file: !2477, line: 256, baseType: !4976)
!4976 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "defusechain_iterator<true, false, false>", scope: !2476, file: !2477, line: 556, size: 64, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4977, templateParams: !5026, identifier: "_ZTSN4llvm19MachineRegisterInfo20defusechain_iteratorILb1ELb0ELb0EEE")
!4977 = !{!4978, !4982, !4983, !4987, !4992, !4995, !4999, !5000, !5003, !5007, !5010, !5013, !5014, !5017, !5020, !5023}
!4978 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4976, baseType: !4979, flags: DIFlagPublic, extraData: i32 0)
!4979 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::forward_iterator_tag, llvm::MachineInstr, long, llvm::MachineInstr *, llvm::MachineInstr &>", scope: !839, file: !1110, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !4980, identifier: "_ZTSSt8iteratorISt20forward_iterator_tagN4llvm12MachineInstrElPS2_RS2_E")
!4980 = !{!4981, !2494, !2495, !2496, !2497}
!4981 = !DITemplateTypeParameter(name: "_Category", type: !2490)
!4982 = !DIDerivedType(tag: DW_TAG_member, name: "Op", scope: !4976, file: !2477, line: 558, baseType: !307, size: 64)
!4983 = !DISubprogram(name: "defusechain_iterator", scope: !4976, file: !2477, line: 559, type: !4984, scopeLine: 559, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4984 = !DISubroutineType(types: !4985)
!4985 = !{null, !4986, !307}
!4986 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4976, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4987 = !DISubprogram(name: "defusechain_iterator", scope: !4976, file: !2477, line: 576, type: !4988, scopeLine: 576, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4988 = !DISubroutineType(types: !4989)
!4989 = !{null, !4986, !4990}
!4990 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4991, size: 64)
!4991 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4976)
!4992 = !DISubprogram(name: "defusechain_iterator", scope: !4976, file: !2477, line: 577, type: !4993, scopeLine: 577, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4993 = !DISubroutineType(types: !4994)
!4994 = !{null, !4986}
!4995 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm19MachineRegisterInfo20defusechain_iteratorILb1ELb0ELb0EEeqERKS2_", scope: !4976, file: !2477, line: 579, type: !4996, scopeLine: 579, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4996 = !DISubroutineType(types: !4997)
!4997 = !{!145, !4998, !4990}
!4998 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4991, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4999 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm19MachineRegisterInfo20defusechain_iteratorILb1ELb0ELb0EEneERKS2_", scope: !4976, file: !2477, line: 582, type: !4996, scopeLine: 582, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5000 = !DISubprogram(name: "atEnd", linkageName: "_ZNK4llvm19MachineRegisterInfo20defusechain_iteratorILb1ELb0ELb0EE5atEndEv", scope: !4976, file: !2477, line: 587, type: !5001, scopeLine: 587, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5001 = !DISubroutineType(types: !5002)
!5002 = !{!145, !4998}
!5003 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm19MachineRegisterInfo20defusechain_iteratorILb1ELb0ELb0EEppEv", scope: !4976, file: !2477, line: 590, type: !5004, scopeLine: 590, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5004 = !DISubroutineType(types: !5005)
!5005 = !{!5006, !4986}
!5006 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4976, size: 64)
!5007 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm19MachineRegisterInfo20defusechain_iteratorILb1ELb0ELb0EEppEi", scope: !4976, file: !2477, line: 611, type: !5008, scopeLine: 611, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5008 = !DISubroutineType(types: !5009)
!5009 = !{!4976, !4986, !32}
!5010 = !DISubprogram(name: "skipInstruction", linkageName: "_ZN4llvm19MachineRegisterInfo20defusechain_iteratorILb1ELb0ELb0EE15skipInstructionEv", scope: !4976, file: !2477, line: 618, type: !5011, scopeLine: 618, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5011 = !DISubroutineType(types: !5012)
!5012 = !{!268, !4986}
!5013 = !DISubprogram(name: "skipBundle", linkageName: "_ZN4llvm19MachineRegisterInfo20defusechain_iteratorILb1ELb0ELb0EE10skipBundleEv", scope: !4976, file: !2477, line: 626, type: !5011, scopeLine: 626, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5014 = !DISubprogram(name: "getOperand", linkageName: "_ZNK4llvm19MachineRegisterInfo20defusechain_iteratorILb1ELb0ELb0EE10getOperandEv", scope: !4976, file: !2477, line: 634, type: !5015, scopeLine: 634, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5015 = !DISubroutineType(types: !5016)
!5016 = !{!3629, !4998}
!5017 = !DISubprogram(name: "getOperandNo", linkageName: "_ZNK4llvm19MachineRegisterInfo20defusechain_iteratorILb1ELb0ELb0EE12getOperandNoEv", scope: !4976, file: !2477, line: 641, type: !5018, scopeLine: 641, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5018 = !DISubroutineType(types: !5019)
!5019 = !{!6, !4998}
!5020 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm19MachineRegisterInfo20defusechain_iteratorILb1ELb0ELb0EEdeEv", scope: !4976, file: !2477, line: 647, type: !5021, scopeLine: 647, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5021 = !DISubroutineType(types: !5022)
!5022 = !{!2498, !4998}
!5023 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm19MachineRegisterInfo20defusechain_iteratorILb1ELb0ELb0EEptEv", scope: !4976, file: !2477, line: 652, type: !5024, scopeLine: 652, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5024 = !DISubroutineType(types: !5025)
!5025 = !{!268, !4998}
!5026 = !{!2014, !1383, !1383}
!5027 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "initializer<int>", scope: !13, file: !12, line: 305, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !5028, templateParams: !5036, identifier: "_ZTSN4llvm2cl11initializerIiEE")
!5028 = !{!5029, !5032}
!5029 = !DIDerivedType(tag: DW_TAG_member, name: "Init", scope: !5027, file: !12, line: 306, baseType: !5030, size: 64)
!5030 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5031, size: 64)
!5031 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !32)
!5032 = !DISubprogram(name: "initializer", scope: !5027, file: !12, line: 307, type: !5033, scopeLine: 307, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5033 = !DISubroutineType(types: !5034)
!5034 = !{null, !5035, !5030}
!5035 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5027, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5036 = !{!5037}
!5037 = !DITemplateTypeParameter(name: "Ty", type: !32)
!5038 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "initializer<bool>", scope: !13, file: !12, line: 305, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !5039, templateParams: !5046, identifier: "_ZTSN4llvm2cl11initializerIbEE")
!5039 = !{!5040, !5042}
!5040 = !DIDerivedType(tag: DW_TAG_member, name: "Init", scope: !5038, file: !12, line: 306, baseType: !5041, size: 64)
!5041 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !833, size: 64)
!5042 = !DISubprogram(name: "initializer", scope: !5038, file: !12, line: 307, type: !5043, scopeLine: 307, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5043 = !DISubroutineType(types: !5044)
!5044 = !{null, !5045, !5041}
!5045 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5038, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5046 = !{!5047}
!5047 = !DITemplateTypeParameter(name: "Ty", type: !145)
!5048 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "initializer<unsigned int>", scope: !13, file: !12, line: 305, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !5049, templateParams: !5055, identifier: "_ZTSN4llvm2cl11initializerIjEE")
!5049 = !{!5050, !5051}
!5050 = !DIDerivedType(tag: DW_TAG_member, name: "Init", scope: !5048, file: !12, line: 306, baseType: !2065, size: 64)
!5051 = !DISubprogram(name: "initializer", scope: !5048, file: !12, line: 307, type: !5052, scopeLine: 307, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5052 = !DISubroutineType(types: !5053)
!5053 = !{null, !5054, !2065}
!5054 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5048, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5055 = !{!5056}
!5056 = !DITemplateTypeParameter(name: "Ty", type: !6)
!5057 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "TailDuplicatePass", scope: !5059, file: !5058, line: 61, size: 1536, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5060, vtableHolder: !1345)
!5058 = !DIFile(filename: "llvm34/lib/CodeGen/TailDuplication.cpp", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "f5cdce11cfd44d2c944f0e413097b426")
!5059 = !DINamespace(scope: null)
!5060 = !{!5061, !5064, !5065, !5066, !5067, !5068, !5120, !5121, !5238, !5239, !5240, !5244, !5248, !5251, !5484, !5487, !5603, !5604, !5607, !5610, !5613, !5700, !5703, !5706}
!5061 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5057, baseType: !5062, flags: DIFlagPublic, extraData: i32 0)
!5062 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MachineFunctionPass", scope: !14, file: !5063, line: 32, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm19MachineFunctionPassE")
!5063 = !DIFile(filename: "llvm34/include/llvm/CodeGen/MachineFunctionPass.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "74cc7fb7c82e767959d97cc024180cc7")
!5064 = !DIDerivedType(tag: DW_TAG_member, name: "TII", scope: !5057, file: !5058, line: 62, baseType: !2470, size: 64, offset: 256)
!5065 = !DIDerivedType(tag: DW_TAG_member, name: "TRI", scope: !5057, file: !5058, line: 63, baseType: !2468, size: 64, offset: 320)
!5066 = !DIDerivedType(tag: DW_TAG_member, name: "MMI", scope: !5057, file: !5058, line: 64, baseType: !3090, size: 64, offset: 384)
!5067 = !DIDerivedType(tag: DW_TAG_member, name: "MRI", scope: !5057, file: !5058, line: 65, baseType: !2475, size: 64, offset: 448)
!5068 = !DIDerivedType(tag: DW_TAG_member, name: "RS", scope: !5057, file: !5058, line: 66, baseType: !5069, size: 64, offset: 512)
!5069 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "OwningPtr<llvm::RegScavenger>", scope: !14, file: !5070, line: 28, size: 64, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5071, templateParams: !5118, identifier: "_ZTSN4llvm9OwningPtrINS_12RegScavengerEEE")
!5070 = !DIFile(filename: "llvm34/include/llvm/ADT/OwningPtr.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "aca248455b073d207b4725e6c25cc91c")
!5071 = !{!5072, !5074, !5080, !5084, !5087, !5091, !5094, !5097, !5098, !5101, !5106, !5109, !5110, !5113, !5114, !5115}
!5072 = !DIDerivedType(tag: DW_TAG_member, name: "Ptr", scope: !5069, file: !5070, line: 31, baseType: !5073, size: 64)
!5073 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2465, size: 64)
!5074 = !DISubprogram(name: "OwningPtr", scope: !5069, file: !5070, line: 29, type: !5075, scopeLine: 29, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!5075 = !DISubroutineType(types: !5076)
!5076 = !{null, !5077, !5078}
!5077 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5069, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5078 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5079, size: 64)
!5079 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5069)
!5080 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm9OwningPtrINS_12RegScavengerEEaSERKS2_", scope: !5069, file: !5070, line: 30, type: !5081, scopeLine: 30, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!5081 = !DISubroutineType(types: !5082)
!5082 = !{!5083, !5077, !5078}
!5083 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5069, size: 64)
!5084 = !DISubprogram(name: "OwningPtr", scope: !5069, file: !5070, line: 33, type: !5085, scopeLine: 33, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5085 = !DISubroutineType(types: !5086)
!5086 = !{null, !5077, !5073}
!5087 = !DISubprogram(name: "OwningPtr", scope: !5069, file: !5070, line: 36, type: !5088, scopeLine: 36, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5088 = !DISubroutineType(types: !5089)
!5089 = !{null, !5077, !5090}
!5090 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !5069, size: 64)
!5091 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm9OwningPtrINS_12RegScavengerEEaSEOS2_", scope: !5069, file: !5070, line: 38, type: !5092, scopeLine: 38, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5092 = !DISubroutineType(types: !5093)
!5093 = !{!5083, !5077, !5090}
!5094 = !DISubprogram(name: "~OwningPtr", scope: !5069, file: !5070, line: 44, type: !5095, scopeLine: 44, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5095 = !DISubroutineType(types: !5096)
!5096 = !{null, !5077}
!5097 = !DISubprogram(name: "reset", linkageName: "_ZN4llvm9OwningPtrINS_12RegScavengerEE5resetEPS1_", scope: !5069, file: !5070, line: 51, type: !5085, scopeLine: 51, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5098 = !DISubprogram(name: "take", linkageName: "_ZN4llvm9OwningPtrINS_12RegScavengerEE4takeEv", scope: !5069, file: !5070, line: 60, type: !5099, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5099 = !DISubroutineType(types: !5100)
!5100 = !{!5073, !5077}
!5101 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm9OwningPtrINS_12RegScavengerEEdeEv", scope: !5069, file: !5070, line: 66, type: !5102, scopeLine: 66, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5102 = !DISubroutineType(types: !5103)
!5103 = !{!5104, !5105}
!5104 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2465, size: 64)
!5105 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5079, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5106 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm9OwningPtrINS_12RegScavengerEEptEv", scope: !5069, file: !5070, line: 71, type: !5107, scopeLine: 71, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5107 = !DISubroutineType(types: !5108)
!5108 = !{!5073, !5105}
!5109 = !DISubprogram(name: "get", linkageName: "_ZNK4llvm9OwningPtrINS_12RegScavengerEE3getEv", scope: !5069, file: !5070, line: 72, type: !5107, scopeLine: 72, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5110 = !DISubprogram(name: "operator bool", linkageName: "_ZNK4llvm9OwningPtrINS_12RegScavengerEEcvbEv", scope: !5069, file: !5070, line: 73, type: !5111, scopeLine: 73, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5111 = !DISubroutineType(types: !5112)
!5112 = !{!145, !5105}
!5113 = !DISubprogram(name: "operator!", linkageName: "_ZNK4llvm9OwningPtrINS_12RegScavengerEEntEv", scope: !5069, file: !5070, line: 74, type: !5111, scopeLine: 74, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5114 = !DISubprogram(name: "isValid", linkageName: "_ZNK4llvm9OwningPtrINS_12RegScavengerEE7isValidEv", scope: !5069, file: !5070, line: 75, type: !5111, scopeLine: 75, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5115 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm9OwningPtrINS_12RegScavengerEE4swapERS2_", scope: !5069, file: !5070, line: 77, type: !5116, scopeLine: 77, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5116 = !DISubroutineType(types: !5117)
!5117 = !{null, !5077, !5083}
!5118 = !{!5119}
!5119 = !DITemplateTypeParameter(name: "T", type: !2465)
!5120 = !DIDerivedType(tag: DW_TAG_member, name: "PreRegAlloc", scope: !5057, file: !5058, line: 67, baseType: !145, size: 8, offset: 576)
!5121 = !DIDerivedType(tag: DW_TAG_member, name: "SSAUpdateVRs", scope: !5057, file: !5058, line: 70, baseType: !5122, size: 704, offset: 640)
!5122 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<unsigned int, 16U>", scope: !14, file: !2317, line: 880, size: 704, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5123, templateParams: !5214, identifier: "_ZTSN4llvm11SmallVectorIjLj16EEE")
!5123 = !{!5124, !5207, !5216, !5220, !5223, !5228, !5231, !5235}
!5124 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5122, baseType: !5125, flags: DIFlagPublic, extraData: i32 0)
!5125 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<unsigned int>", scope: !14, file: !2317, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5126, templateParams: !2070, identifier: "_ZTSN4llvm15SmallVectorImplIjEE")
!5126 = !{!5127, !5146, !5152, !5155, !5158, !5159, !5160, !5163, !5164, !5167, !5171, !5176, !5177, !5181, !5184, !5187, !5190, !5193, !5196, !5200, !5204, !5205, !5206}
!5127 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5125, baseType: !5128, flags: DIFlagPublic, extraData: i32 0)
!5128 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<unsigned int, true>", scope: !14, file: !2317, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !5129, templateParams: !5145, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseIjLb1EEE")
!5129 = !{!5130, !5131, !5135, !5138, !5139, !5142}
!5130 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5128, baseType: !2318, flags: DIFlagPublic, extraData: i32 0)
!5131 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !5128, file: !2317, line: 298, type: !5132, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5132 = !DISubroutineType(types: !5133)
!5133 = !{null, !5134, !2102}
!5134 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5128, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5135 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIjLb1EE13destroy_rangeEPjS2_", scope: !5128, file: !2317, line: 301, type: !5136, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!5136 = !DISubroutineType(types: !5137)
!5137 = !{null, !2383, !2383}
!5138 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIjLb1EE4growEm", scope: !5128, file: !2317, line: 346, type: !5132, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5139 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIjLb1EE9push_backERKj", scope: !5128, file: !2317, line: 350, type: !5140, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5140 = !DISubroutineType(types: !5141)
!5141 = !{null, !5134, !2065}
!5142 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIjLb1EE8pop_backEv", scope: !5128, file: !2317, line: 361, type: !5143, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5143 = !DISubroutineType(types: !5144)
!5144 = !{null, !5134}
!5145 = !{!2071, !2627}
!5146 = !DISubprogram(name: "SmallVectorImpl", scope: !5125, file: !2317, line: 374, type: !5147, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!5147 = !DISubroutineType(types: !5148)
!5148 = !{null, !5149, !5150}
!5149 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5125, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5150 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5151, size: 64)
!5151 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5125)
!5152 = !DISubprogram(name: "SmallVectorImpl", scope: !5125, file: !2317, line: 381, type: !5153, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5153 = !DISubroutineType(types: !5154)
!5154 = !{null, !5149, !6}
!5155 = !DISubprogram(name: "~SmallVectorImpl", scope: !5125, file: !2317, line: 386, type: !5156, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5156 = !DISubroutineType(types: !5157)
!5157 = !{null, !5149}
!5158 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplIjE5clearEv", scope: !5125, file: !2317, line: 396, type: !5156, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5159 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIjE6resizeEj", scope: !5125, file: !2317, line: 401, type: !5153, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5160 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIjE6resizeEjRKj", scope: !5125, file: !2317, line: 413, type: !5161, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5161 = !DISubroutineType(types: !5162)
!5162 = !{null, !5149, !6, !2065}
!5163 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplIjE7reserveEj", scope: !5125, file: !2317, line: 425, type: !5153, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5164 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplIjE12pop_back_valEv", scope: !5125, file: !2317, line: 430, type: !5165, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5165 = !DISubroutineType(types: !5166)
!5166 = !{!6, !5149}
!5167 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplIjE4swapERS1_", scope: !5125, file: !2317, line: 440, type: !5168, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5168 = !DISubroutineType(types: !5169)
!5169 = !{null, !5149, !5170}
!5170 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5125, size: 64)
!5171 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplIjE6appendEmRKj", scope: !5125, file: !2317, line: 460, type: !5172, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5172 = !DISubroutineType(types: !5173)
!5173 = !{null, !5149, !5174, !2065}
!5174 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !5125, file: !2317, line: 377, baseType: !5175)
!5175 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2318, file: !2317, line: 97, baseType: !2102)
!5176 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplIjE6assignEjRKj", scope: !5125, file: !2317, line: 470, type: !5161, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5177 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIjE5eraseEPj", scope: !5125, file: !2317, line: 478, type: !5178, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5178 = !DISubroutineType(types: !5179)
!5179 = !{!5180, !5149, !5180}
!5180 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !5125, file: !2317, line: 376, baseType: !2316)
!5181 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIjE5eraseEPjS2_", scope: !5125, file: !2317, line: 490, type: !5182, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5182 = !DISubroutineType(types: !5183)
!5183 = !{!5180, !5149, !5180, !5180}
!5184 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIjE6insertEPjOj", scope: !5125, file: !2317, line: 505, type: !5185, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5185 = !DISubroutineType(types: !5186)
!5186 = !{!5180, !5149, !5180, !2198}
!5187 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIjE6insertEPjRKj", scope: !5125, file: !2317, line: 537, type: !5188, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5188 = !DISubroutineType(types: !5189)
!5189 = !{!5180, !5149, !5180, !2065}
!5190 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIjE6insertEPjmRKj", scope: !5125, file: !2317, line: 568, type: !5191, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5191 = !DISubroutineType(types: !5192)
!5192 = !{!5180, !5149, !5180, !5174, !2065}
!5193 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIjEaSERKS1_", scope: !5125, file: !2317, line: 674, type: !5194, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5194 = !DISubroutineType(types: !5195)
!5195 = !{!5170, !5149, !5150}
!5196 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIjEaSEOS1_", scope: !5125, file: !2317, line: 677, type: !5197, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5197 = !DISubroutineType(types: !5198)
!5198 = !{!5170, !5149, !5199}
!5199 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !5125, size: 64)
!5200 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplIjEeqERKS1_", scope: !5125, file: !2317, line: 680, type: !5201, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5201 = !DISubroutineType(types: !5202)
!5202 = !{!145, !5203, !5150}
!5203 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5151, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5204 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplIjEneERKS1_", scope: !5125, file: !2317, line: 684, type: !5201, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5205 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplIjEltERKS1_", scope: !5125, file: !2317, line: 688, type: !5201, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5206 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplIjE8set_sizeEj", scope: !5125, file: !2317, line: 702, type: !5153, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5207 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !5122, file: !2317, line: 882, baseType: !5208, size: 480, offset: 224)
!5208 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<unsigned int, 16U>", scope: !14, file: !2317, line: 865, size: 480, flags: DIFlagTypePassByValue, elements: !5209, templateParams: !5214, identifier: "_ZTSN4llvm18SmallVectorStorageIjLj16EEE")
!5209 = !{!5210}
!5210 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !5208, file: !2317, line: 866, baseType: !5211, size: 480)
!5211 = !DICompositeType(tag: DW_TAG_array_type, baseType: !2343, size: 480, elements: !5212)
!5212 = !{!5213}
!5213 = !DISubrange(count: 15)
!5214 = !{!2071, !5215}
!5215 = !DITemplateValueParameter(name: "N", type: !6, value: i32 16)
!5216 = !DISubprogram(name: "SmallVector", scope: !5122, file: !2317, line: 884, type: !5217, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5217 = !DISubroutineType(types: !5218)
!5218 = !{null, !5219}
!5219 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5122, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5220 = !DISubprogram(name: "SmallVector", scope: !5122, file: !2317, line: 887, type: !5221, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5221 = !DISubroutineType(types: !5222)
!5222 = !{null, !5219, !6, !2065}
!5223 = !DISubprogram(name: "SmallVector", scope: !5122, file: !2317, line: 897, type: !5224, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5224 = !DISubroutineType(types: !5225)
!5225 = !{null, !5219, !5226}
!5226 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5227, size: 64)
!5227 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5122)
!5228 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIjLj16EEaSERKS1_", scope: !5122, file: !2317, line: 902, type: !5229, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5229 = !DISubroutineType(types: !5230)
!5230 = !{!5226, !5219, !5226}
!5231 = !DISubprogram(name: "SmallVector", scope: !5122, file: !2317, line: 908, type: !5232, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5232 = !DISubroutineType(types: !5233)
!5233 = !{null, !5219, !5234}
!5234 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !5122, size: 64)
!5235 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIjLj16EEaSEOS1_", scope: !5122, file: !2317, line: 913, type: !5236, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5236 = !DISubroutineType(types: !5237)
!5237 = !{!5226, !5219, !5234}
!5238 = !DIDerivedType(tag: DW_TAG_member, name: "SSAUpdateVals", scope: !5057, file: !5058, line: 74, baseType: !1364, size: 192, offset: 1344)
!5239 = !DIDerivedType(tag: DW_TAG_member, name: "ID", scope: !5057, file: !5058, line: 77, baseType: !319, flags: DIFlagPublic | DIFlagStaticMember)
!5240 = !DISubprogram(name: "TailDuplicatePass", scope: !5057, file: !5058, line: 78, type: !5241, scopeLine: 78, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!5241 = !DISubroutineType(types: !5242)
!5242 = !{null, !5243}
!5243 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5057, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5244 = !DISubprogram(name: "runOnMachineFunction", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass20runOnMachineFunctionERN4llvm15MachineFunctionE", scope: !5057, file: !5058, line: 81, type: !5245, scopeLine: 81, containingType: !5057, virtualIndex: 18, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagLocalToUnit | DISPFlagOptimized)
!5245 = !DISubroutineType(types: !5246)
!5246 = !{!145, !5243, !5247}
!5247 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2914, size: 64)
!5248 = !DISubprogram(name: "AddSSAUpdateEntry", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass17AddSSAUpdateEntryEjjPN4llvm17MachineBasicBlockE", scope: !5057, file: !5058, line: 84, type: !5249, scopeLine: 84, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!5249 = !DISubroutineType(types: !5250)
!5250 = !{null, !5243, !6, !6, !197}
!5251 = !DISubprogram(name: "ProcessPHI", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass10ProcessPHIEPN4llvm12MachineInstrEPNS1_17MachineBasicBlockES5_RNS1_8DenseMapIjjNS1_12DenseMapInfoIjEEEERNS1_15SmallVectorImplISt4pairIjjEEERKNS1_8DenseSetIjS8_EEb", scope: !5057, file: !5058, line: 86, type: !5252, scopeLine: 86, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!5252 = !DISubroutineType(types: !5253)
!5253 = !{null, !5243, !268, !197, !197, !4703, !5254, !5337, !145}
!5254 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5255, size: 64)
!5255 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<std::pair<unsigned int, unsigned int> >", scope: !14, file: !2317, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5256, templateParams: !5336, identifier: "_ZTSN4llvm15SmallVectorImplISt4pairIjjEEE")
!5256 = !{!5257, !5276, !5282, !5285, !5288, !5289, !5290, !5293, !5294, !5297, !5300, !5305, !5306, !5310, !5313, !5316, !5319, !5322, !5325, !5329, !5333, !5334, !5335}
!5257 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5255, baseType: !5258, flags: DIFlagPublic, extraData: i32 0)
!5258 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<std::pair<unsigned int, unsigned int>, true>", scope: !14, file: !2317, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !5259, templateParams: !5275, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseISt4pairIjjELb1EEE")
!5259 = !{!5260, !5261, !5265, !5268, !5269, !5272}
!5260 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5258, baseType: !4733, flags: DIFlagPublic, extraData: i32 0)
!5261 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !5258, file: !2317, line: 298, type: !5262, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5262 = !DISubroutineType(types: !5263)
!5263 = !{null, !5264, !2102}
!5264 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5258, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5265 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseISt4pairIjjELb1EE13destroy_rangeEPS2_S4_", scope: !5258, file: !2317, line: 301, type: !5266, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!5266 = !DISubroutineType(types: !5267)
!5267 = !{null, !4765, !4765}
!5268 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseISt4pairIjjELb1EE4growEm", scope: !5258, file: !2317, line: 346, type: !5262, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5269 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseISt4pairIjjELb1EE9push_backERKS2_", scope: !5258, file: !2317, line: 350, type: !5270, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5270 = !DISubroutineType(types: !5271)
!5271 = !{null, !5264, !4397}
!5272 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseISt4pairIjjELb1EE8pop_backEv", scope: !5258, file: !2317, line: 361, type: !5273, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5273 = !DISubroutineType(types: !5274)
!5274 = !{null, !5264}
!5275 = !{!4822, !2627}
!5276 = !DISubprogram(name: "SmallVectorImpl", scope: !5255, file: !2317, line: 374, type: !5277, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!5277 = !DISubroutineType(types: !5278)
!5278 = !{null, !5279, !5280}
!5279 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5255, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5280 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5281, size: 64)
!5281 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5255)
!5282 = !DISubprogram(name: "SmallVectorImpl", scope: !5255, file: !2317, line: 381, type: !5283, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5283 = !DISubroutineType(types: !5284)
!5284 = !{null, !5279, !6}
!5285 = !DISubprogram(name: "~SmallVectorImpl", scope: !5255, file: !2317, line: 386, type: !5286, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5286 = !DISubroutineType(types: !5287)
!5287 = !{null, !5279}
!5288 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEE5clearEv", scope: !5255, file: !2317, line: 396, type: !5286, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5289 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEE6resizeEj", scope: !5255, file: !2317, line: 401, type: !5283, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5290 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEE6resizeEjRKS2_", scope: !5255, file: !2317, line: 413, type: !5291, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5291 = !DISubroutineType(types: !5292)
!5292 = !{null, !5279, !6, !4397}
!5293 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEE7reserveEj", scope: !5255, file: !2317, line: 425, type: !5283, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5294 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEE12pop_back_valEv", scope: !5255, file: !2317, line: 430, type: !5295, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5295 = !DISubroutineType(types: !5296)
!5296 = !{!4371, !5279}
!5297 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEE4swapERS3_", scope: !5255, file: !2317, line: 440, type: !5298, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5298 = !DISubroutineType(types: !5299)
!5299 = !{null, !5279, !5254}
!5300 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEE6appendEmRKS2_", scope: !5255, file: !2317, line: 460, type: !5301, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5301 = !DISubroutineType(types: !5302)
!5302 = !{null, !5279, !5303, !4397}
!5303 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !5255, file: !2317, line: 377, baseType: !5304)
!5304 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !4733, file: !2317, line: 97, baseType: !2102)
!5305 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEE6assignEjRKS2_", scope: !5255, file: !2317, line: 470, type: !5291, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5306 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEE5eraseEPS2_", scope: !5255, file: !2317, line: 478, type: !5307, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5307 = !DISubroutineType(types: !5308)
!5308 = !{!5309, !5279, !5309}
!5309 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !5255, file: !2317, line: 376, baseType: !4732)
!5310 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEE5eraseEPS2_S4_", scope: !5255, file: !2317, line: 490, type: !5311, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5311 = !DISubroutineType(types: !5312)
!5312 = !{!5309, !5279, !5309, !5309}
!5313 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEE6insertEPS2_OS2_", scope: !5255, file: !2317, line: 505, type: !5314, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5314 = !DISubroutineType(types: !5315)
!5315 = !{!5309, !5279, !5309, !4401}
!5316 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEE6insertEPS2_RKS2_", scope: !5255, file: !2317, line: 537, type: !5317, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5317 = !DISubroutineType(types: !5318)
!5318 = !{!5309, !5279, !5309, !4397}
!5319 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEE6insertEPS2_mRKS2_", scope: !5255, file: !2317, line: 568, type: !5320, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5320 = !DISubroutineType(types: !5321)
!5321 = !{!5309, !5279, !5309, !5303, !4397}
!5322 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEEaSERKS3_", scope: !5255, file: !2317, line: 674, type: !5323, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5323 = !DISubroutineType(types: !5324)
!5324 = !{!5254, !5279, !5280}
!5325 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEEaSEOS3_", scope: !5255, file: !2317, line: 677, type: !5326, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5326 = !DISubroutineType(types: !5327)
!5327 = !{!5254, !5279, !5328}
!5328 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !5255, size: 64)
!5329 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplISt4pairIjjEEeqERKS3_", scope: !5255, file: !2317, line: 680, type: !5330, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5330 = !DISubroutineType(types: !5331)
!5331 = !{!145, !5332, !5280}
!5332 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5281, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5333 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplISt4pairIjjEEneERKS3_", scope: !5255, file: !2317, line: 684, type: !5330, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5334 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplISt4pairIjjEEltERKS3_", scope: !5255, file: !2317, line: 688, type: !5330, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5335 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplISt4pairIjjEE8set_sizeEj", scope: !5255, file: !2317, line: 702, type: !5283, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5336 = !{!4822}
!5337 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5338, size: 64)
!5338 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5339)
!5339 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseSet<unsigned int, llvm::DenseMapInfo<unsigned int> >", scope: !14, file: !5340, line: 26, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5341, templateParams: !5482, identifier: "_ZTSN4llvm8DenseSetIjNS_12DenseMapInfoIjEEEE")
!5340 = !DIFile(filename: "llvm34/include/llvm/ADT/DenseSet.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "aae1a6c0416fd9b2ee5efcee94ade352")
!5341 = !{!5342, !5344, !5348, !5351, !5355, !5358, !5361, !5364, !5367, !5370, !5373, !5377, !5380, !5410, !5411, !5416, !5417, !5420, !5423, !5426}
!5342 = !DIDerivedType(tag: DW_TAG_member, name: "TheMap", scope: !5339, file: !5340, line: 28, baseType: !5343, size: 192)
!5343 = !DIDerivedType(tag: DW_TAG_typedef, name: "MapTy", scope: !5339, file: !5340, line: 27, baseType: !3649)
!5344 = !DISubprogram(name: "DenseSet", scope: !5339, file: !5340, line: 30, type: !5345, scopeLine: 30, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5345 = !DISubroutineType(types: !5346)
!5346 = !{null, !5347, !5337}
!5347 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5339, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5348 = !DISubprogram(name: "DenseSet", scope: !5339, file: !5340, line: 31, type: !5349, scopeLine: 31, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5349 = !DISubroutineType(types: !5350)
!5350 = !{null, !5347, !6}
!5351 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm8DenseSetIjNS_12DenseMapInfoIjEEE5emptyEv", scope: !5339, file: !5340, line: 33, type: !5352, scopeLine: 33, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5352 = !DISubroutineType(types: !5353)
!5353 = !{!145, !5354}
!5354 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5338, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5355 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm8DenseSetIjNS_12DenseMapInfoIjEEE4sizeEv", scope: !5339, file: !5340, line: 34, type: !5356, scopeLine: 34, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5356 = !DISubroutineType(types: !5357)
!5357 = !{!6, !5354}
!5358 = !DISubprogram(name: "getMemorySize", linkageName: "_ZNK4llvm8DenseSetIjNS_12DenseMapInfoIjEEE13getMemorySizeEv", scope: !5339, file: !5340, line: 35, type: !5359, scopeLine: 35, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5359 = !DISubroutineType(types: !5360)
!5360 = !{!2102, !5354}
!5361 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE6resizeEm", scope: !5339, file: !5340, line: 39, type: !5362, scopeLine: 39, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5362 = !DISubroutineType(types: !5363)
!5363 = !{null, !5347, !2102}
!5364 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE5clearEv", scope: !5339, file: !5340, line: 41, type: !5365, scopeLine: 41, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5365 = !DISubroutineType(types: !5366)
!5366 = !{null, !5347}
!5367 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm8DenseSetIjNS_12DenseMapInfoIjEEE5countERKj", scope: !5339, file: !5340, line: 45, type: !5368, scopeLine: 45, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5368 = !DISubroutineType(types: !5369)
!5369 = !{!145, !5354, !2065}
!5370 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE5eraseERKj", scope: !5339, file: !5340, line: 49, type: !5371, scopeLine: 49, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5371 = !DISubroutineType(types: !5372)
!5372 = !{!145, !5347, !2065}
!5373 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE4swapERS3_", scope: !5339, file: !5340, line: 53, type: !5374, scopeLine: 53, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5374 = !DISubroutineType(types: !5375)
!5375 = !{null, !5347, !5376}
!5376 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5339, size: 64)
!5377 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8DenseSetIjNS_12DenseMapInfoIjEEEaSERKS3_", scope: !5339, file: !5340, line: 57, type: !5378, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5378 = !DISubroutineType(types: !5379)
!5379 = !{!5376, !5347, !5337}
!5380 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE5beginEv", scope: !5339, file: !5340, line: 107, type: !5381, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5381 = !DISubroutineType(types: !5382)
!5382 = !{!5383, !5347}
!5383 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !5339, file: !5340, line: 104, baseType: !5384)
!5384 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Iterator", scope: !5339, file: !5340, line: 64, size: 128, flags: DIFlagPublic | DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5385, identifier: "_ZTSN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE8IteratorE")
!5385 = !{!5386, !5387, !5393, !5396, !5399, !5403, !5409}
!5386 = !DIDerivedType(tag: DW_TAG_member, name: "I", scope: !5384, file: !5340, line: 65, baseType: !3657, size: 128)
!5387 = !DISubprogram(name: "Iterator", scope: !5384, file: !5340, line: 74, type: !5388, scopeLine: 74, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5388 = !DISubroutineType(types: !5389)
!5389 = !{null, !5390, !5391}
!5390 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5384, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5391 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5392, size: 64)
!5392 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3657)
!5393 = !DISubprogram(name: "operator*", linkageName: "_ZN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE8IteratordeEv", scope: !5384, file: !5340, line: 76, type: !5394, scopeLine: 76, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5394 = !DISubroutineType(types: !5395)
!5395 = !{!2428, !5390}
!5396 = !DISubprogram(name: "operator->", linkageName: "_ZN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE8IteratorptEv", scope: !5384, file: !5340, line: 77, type: !5397, scopeLine: 77, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5397 = !DISubroutineType(types: !5398)
!5398 = !{!2383, !5390}
!5399 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE8IteratorppEv", scope: !5384, file: !5340, line: 79, type: !5400, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5400 = !DISubroutineType(types: !5401)
!5401 = !{!5402, !5390}
!5402 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5384, size: 64)
!5403 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm8DenseSetIjNS_12DenseMapInfoIjEEE8IteratoreqERKS4_", scope: !5384, file: !5340, line: 80, type: !5404, scopeLine: 80, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5404 = !DISubroutineType(types: !5405)
!5405 = !{!145, !5406, !5408}
!5406 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5407, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5407 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5384)
!5408 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5407, size: 64)
!5409 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm8DenseSetIjNS_12DenseMapInfoIjEEE8IteratorneERKS4_", scope: !5384, file: !5340, line: 81, type: !5404, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5410 = !DISubprogram(name: "end", linkageName: "_ZN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE3endEv", scope: !5339, file: !5340, line: 108, type: !5381, scopeLine: 108, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5411 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm8DenseSetIjNS_12DenseMapInfoIjEEE5beginEv", scope: !5339, file: !5340, line: 110, type: !5412, scopeLine: 110, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5412 = !DISubroutineType(types: !5413)
!5413 = !{!5414, !5354}
!5414 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !5339, file: !5340, line: 105, baseType: !5415)
!5415 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ConstIterator", scope: !5339, file: !5340, line: 84, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE13ConstIteratorE")
!5416 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm8DenseSetIjNS_12DenseMapInfoIjEEE3endEv", scope: !5339, file: !5340, line: 111, type: !5412, scopeLine: 111, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5417 = !DISubprogram(name: "find", linkageName: "_ZN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE4findERKj", scope: !5339, file: !5340, line: 113, type: !5418, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5418 = !DISubroutineType(types: !5419)
!5419 = !{!5383, !5347, !2065}
!5420 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE5eraseENS3_8IteratorE", scope: !5339, file: !5340, line: 114, type: !5421, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5421 = !DISubroutineType(types: !5422)
!5422 = !{null, !5347, !5384}
!5423 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE5eraseENS3_13ConstIteratorE", scope: !5339, file: !5340, line: 115, type: !5424, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5424 = !DISubroutineType(types: !5425)
!5425 = !{null, !5347, !5415}
!5426 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm8DenseSetIjNS_12DenseMapInfoIjEEE6insertERKj", scope: !5339, file: !5340, line: 117, type: !5427, scopeLine: 117, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5427 = !DISubroutineType(types: !5428)
!5428 = !{!5429, !5347, !2065}
!5429 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::DenseSet<unsigned int, llvm::DenseMapInfo<unsigned int> >::Iterator, bool>", scope: !839, file: !1387, line: 208, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5430, templateParams: !5480, identifier: "_ZTSSt4pairIN4llvm8DenseSetIjNS0_12DenseMapInfoIjEEE8IteratorEbE")
!5430 = !{!5431, !5450, !5451, !5452, !5458, !5462, !5470, !5477}
!5431 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5429, baseType: !5432, flags: DIFlagPrivate, extraData: i32 0)
!5432 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::DenseSet<unsigned int, llvm::DenseMapInfo<unsigned int> >::Iterator, bool>", scope: !839, file: !1387, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !5433, templateParams: !5448, identifier: "_ZTSSt11__pair_baseIN4llvm8DenseSetIjNS0_12DenseMapInfoIjEEE8IteratorEbE")
!5433 = !{!5434, !5438, !5439, !5444}
!5434 = !DISubprogram(name: "__pair_base", scope: !5432, file: !1387, line: 194, type: !5435, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5435 = !DISubroutineType(types: !5436)
!5436 = !{null, !5437}
!5437 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5432, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5438 = !DISubprogram(name: "~__pair_base", scope: !5432, file: !1387, line: 195, type: !5435, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5439 = !DISubprogram(name: "__pair_base", scope: !5432, file: !1387, line: 196, type: !5440, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5440 = !DISubroutineType(types: !5441)
!5441 = !{null, !5437, !5442}
!5442 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5443, size: 64)
!5443 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5432)
!5444 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN4llvm8DenseSetIjNS0_12DenseMapInfoIjEEE8IteratorEbEaSERKS6_", scope: !5432, file: !1387, line: 197, type: !5445, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!5445 = !DISubroutineType(types: !5446)
!5446 = !{!5447, !5437, !5442}
!5447 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5432, size: 64)
!5448 = !{!5449, !2143}
!5449 = !DITemplateTypeParameter(name: "_U1", type: !5384)
!5450 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !5429, file: !1387, line: 214, baseType: !5384, size: 128)
!5451 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !5429, file: !1387, line: 215, baseType: !145, size: 8, offset: 128)
!5452 = !DISubprogram(name: "pair", scope: !5429, file: !1387, line: 303, type: !5453, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5453 = !DISubroutineType(types: !5454)
!5454 = !{null, !5455, !5456}
!5455 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5429, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5456 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5457, size: 64)
!5457 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5429)
!5458 = !DISubprogram(name: "pair", scope: !5429, file: !1387, line: 304, type: !5459, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5459 = !DISubroutineType(types: !5460)
!5460 = !{null, !5455, !5461}
!5461 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !5429, size: 64)
!5462 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm8DenseSetIjNS0_12DenseMapInfoIjEEE8IteratorEbEaSERKS6_", scope: !5429, file: !1387, line: 378, type: !5463, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5463 = !DISubroutineType(types: !5464)
!5464 = !{!5465, !5455, !5466}
!5465 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5429, size: 64)
!5466 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !5467, file: !1281, line: 1928, baseType: !5456)
!5467 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::DenseSet<unsigned int, llvm::DenseMapInfo<unsigned int> >::Iterator, bool> &, const std::__nonesuch_no_braces &>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !5468, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN4llvm8DenseSetIjNS1_12DenseMapInfoIjEEE8IteratorEbERKSt20__nonesuch_no_bracesE")
!5468 = !{!1472, !5469, !1474}
!5469 = !DITemplateTypeParameter(name: "_Iftrue", type: !5456)
!5470 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm8DenseSetIjNS0_12DenseMapInfoIjEEE8IteratorEbEaSEOS6_", scope: !5429, file: !1387, line: 389, type: !5471, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5471 = !DISubroutineType(types: !5472)
!5472 = !{!5465, !5455, !5473}
!5473 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !5474, file: !1281, line: 1928, baseType: !5461)
!5474 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::DenseSet<unsigned int, llvm::DenseMapInfo<unsigned int> >::Iterator, bool> &&, std::__nonesuch_no_braces &&>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !5475, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN4llvm8DenseSetIjNS1_12DenseMapInfoIjEEE8IteratorEbEOSt20__nonesuch_no_bracesE")
!5475 = !{!1472, !5476, !1485}
!5476 = !DITemplateTypeParameter(name: "_Iftrue", type: !5461)
!5477 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN4llvm8DenseSetIjNS0_12DenseMapInfoIjEEE8IteratorEbE4swapERS6_", scope: !5429, file: !1387, line: 424, type: !5478, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5478 = !DISubroutineType(types: !5479)
!5479 = !{null, !5455, !5465}
!5480 = !{!5481, !2176}
!5481 = !DITemplateTypeParameter(name: "_T1", type: !5384)
!5482 = !{!4496, !5483}
!5483 = !DITemplateTypeParameter(name: "ValueInfoT", type: !2055)
!5484 = !DISubprogram(name: "DuplicateInstruction", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass20DuplicateInstructionEPN4llvm12MachineInstrEPNS1_17MachineBasicBlockES5_RNS1_15MachineFunctionERNS1_8DenseMapIjjNS1_12DenseMapInfoIjEEEERKNS1_8DenseSetIjSA_EE", scope: !5057, file: !5058, line: 92, type: !5485, scopeLine: 92, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!5485 = !DISubroutineType(types: !5486)
!5486 = !{null, !5243, !268, !197, !197, !5247, !4703, !5337}
!5487 = !DISubprogram(name: "UpdateSuccessorsPHIs", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass20UpdateSuccessorsPHIsEPN4llvm17MachineBasicBlockEbRNS1_15SmallVectorImplIS3_EERNS1_14SmallSetVectorIS3_Lj8EEE", scope: !5057, file: !5058, line: 98, type: !5488, scopeLine: 98, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!5488 = !DISubroutineType(types: !5489)
!5489 = !{null, !5243, !197, !145, !4096, !5490}
!5490 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5491, size: 64)
!5491 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallSetVector<llvm::MachineBasicBlock *, 8U>", scope: !14, file: !5492, line: 218, size: 1472, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5493, templateParams: !5520, identifier: "_ZTSN4llvm14SmallSetVectorIPNS_17MachineBasicBlockELj8EEE")
!5492 = !DIFile(filename: "llvm34/include/llvm/ADT/SetVector.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "a5aac229c25339a509a9387d1d107ece")
!5493 = !{!5494, !5599}
!5494 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5491, baseType: !5495, flags: DIFlagPublic, extraData: i32 0)
!5495 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SetVector<llvm::MachineBasicBlock *, llvm::SmallVector<llvm::MachineBasicBlock *, 8U>, llvm::SmallSet<llvm::MachineBasicBlock *, 8U, std::less<llvm::MachineBasicBlock *> > >", scope: !14, file: !5492, line: 37, size: 1472, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5496, templateParams: !5596, identifier: "_ZTSN4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEEE")
!5496 = !{!5497, !5508, !5543, !5547, !5552, !5556, !5560, !5564, !5565, !5566, !5569, !5573, !5579, !5580, !5586, !5587, !5588, !5591, !5595}
!5497 = !DIDerivedType(tag: DW_TAG_member, name: "set_", scope: !5495, file: !5492, line: 211, baseType: !5498, size: 768)
!5498 = !DIDerivedType(tag: DW_TAG_typedef, name: "set_type", scope: !5495, file: !5492, line: 43, baseType: !5499)
!5499 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallSet<llvm::MachineBasicBlock *, 8U, std::less<llvm::MachineBasicBlock *> >", scope: !14, file: !5500, line: 115, size: 768, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5501, templateParams: !5503, identifier: "_ZTSN4llvm8SmallSetIPNS_17MachineBasicBlockELj8ESt4lessIS2_EEE")
!5500 = !DIFile(filename: "llvm34/include/llvm/ADT/SmallSet.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e25947feb7951446d0deac6c780241f4")
!5501 = !{!5502}
!5502 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5499, baseType: !117, flags: DIFlagPublic, extraData: i32 0)
!5503 = !{!3431, !5504, !5505}
!5504 = !DITemplateValueParameter(name: "N", type: !6, value: i32 8)
!5505 = !DITemplateTypeParameter(name: "C", type: !5506)
!5506 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "less<llvm::MachineBasicBlock *>", scope: !839, file: !5507, line: 381, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt4lessIPN4llvm17MachineBasicBlockEE")
!5507 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_function.h", directory: "", checksumkind: CSK_MD5, checksum: "803be361e8ffed08708fdd84c0d32d86")
!5508 = !DIDerivedType(tag: DW_TAG_member, name: "vector_", scope: !5495, file: !5492, line: 212, baseType: !5509, size: 704, offset: 768)
!5509 = !DIDerivedType(tag: DW_TAG_typedef, name: "vector_type", scope: !5495, file: !5492, line: 44, baseType: !5510)
!5510 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<llvm::MachineBasicBlock *, 8U>", scope: !14, file: !2317, line: 880, size: 704, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5511, templateParams: !5520, identifier: "_ZTSN4llvm11SmallVectorIPNS_17MachineBasicBlockELj8EEE")
!5511 = !{!5512, !5513, !5521, !5525, !5528, !5533, !5536, !5540}
!5512 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5510, baseType: !4051, flags: DIFlagPublic, extraData: i32 0)
!5513 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !5510, file: !2317, line: 882, baseType: !5514, size: 448, offset: 256)
!5514 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<llvm::MachineBasicBlock *, 8U>", scope: !14, file: !2317, line: 865, size: 448, flags: DIFlagTypePassByValue, elements: !5515, templateParams: !5520, identifier: "_ZTSN4llvm18SmallVectorStorageIPNS_17MachineBasicBlockELj8EEE")
!5515 = !{!5516}
!5516 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !5514, file: !2317, line: 866, baseType: !5517, size: 448)
!5517 = !DICompositeType(tag: DW_TAG_array_type, baseType: !3343, size: 448, elements: !5518)
!5518 = !{!5519}
!5519 = !DISubrange(count: 7)
!5520 = !{!3431, !5504}
!5521 = !DISubprogram(name: "SmallVector", scope: !5510, file: !2317, line: 884, type: !5522, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5522 = !DISubroutineType(types: !5523)
!5523 = !{null, !5524}
!5524 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5510, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5525 = !DISubprogram(name: "SmallVector", scope: !5510, file: !2317, line: 887, type: !5526, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5526 = !DISubroutineType(types: !5527)
!5527 = !{null, !5524, !6, !3421}
!5528 = !DISubprogram(name: "SmallVector", scope: !5510, file: !2317, line: 897, type: !5529, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5529 = !DISubroutineType(types: !5530)
!5530 = !{null, !5524, !5531}
!5531 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5532, size: 64)
!5532 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5510)
!5533 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIPNS_17MachineBasicBlockELj8EEaSERKS3_", scope: !5510, file: !2317, line: 902, type: !5534, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5534 = !DISubroutineType(types: !5535)
!5535 = !{!5531, !5524, !5531}
!5536 = !DISubprogram(name: "SmallVector", scope: !5510, file: !2317, line: 908, type: !5537, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5537 = !DISubroutineType(types: !5538)
!5538 = !{null, !5524, !5539}
!5539 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !5510, size: 64)
!5540 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIPNS_17MachineBasicBlockELj8EEaSEOS3_", scope: !5510, file: !2317, line: 913, type: !5541, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5541 = !DISubroutineType(types: !5542)
!5542 = !{!5531, !5524, !5539}
!5543 = !DISubprogram(name: "SetVector", scope: !5495, file: !5492, line: 50, type: !5544, scopeLine: 50, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5544 = !DISubroutineType(types: !5545)
!5545 = !{null, !5546}
!5546 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5495, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5547 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEE5emptyEv", scope: !5495, file: !5492, line: 59, type: !5548, scopeLine: 59, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5548 = !DISubroutineType(types: !5549)
!5549 = !{!145, !5550}
!5550 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5551, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5551 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5495)
!5552 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEE4sizeEv", scope: !5495, file: !5492, line: 64, type: !5553, scopeLine: 64, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5553 = !DISubroutineType(types: !5554)
!5554 = !{!5555, !5550}
!5555 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !5495, file: !5492, line: 47, baseType: !4050)
!5556 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEE5beginEv", scope: !5495, file: !5492, line: 69, type: !5557, scopeLine: 69, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5557 = !DISubroutineType(types: !5558)
!5558 = !{!5559, !5546}
!5559 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !5495, file: !5492, line: 45, baseType: !3379)
!5560 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEE5beginEv", scope: !5495, file: !5492, line: 74, type: !5561, scopeLine: 74, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5561 = !DISubroutineType(types: !5562)
!5562 = !{!5563, !5550}
!5563 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !5495, file: !5492, line: 46, baseType: !3379)
!5564 = !DISubprogram(name: "end", linkageName: "_ZN4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEE3endEv", scope: !5495, file: !5492, line: 79, type: !5557, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5565 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEE3endEv", scope: !5495, file: !5492, line: 84, type: !5561, scopeLine: 84, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5566 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEE4backEv", scope: !5495, file: !5492, line: 89, type: !5567, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5567 = !DISubroutineType(types: !5568)
!5568 = !{!3421, !5550}
!5569 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEEixEm", scope: !5495, file: !5492, line: 95, type: !5570, scopeLine: 95, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5570 = !DISubroutineType(types: !5571)
!5571 = !{!5572, !5550, !5555}
!5572 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !5495, file: !5492, line: 42, baseType: !3421)
!5573 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEE6insertERKS2_", scope: !5495, file: !5492, line: 102, type: !5574, scopeLine: 102, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5574 = !DISubroutineType(types: !5575)
!5575 = !{!145, !5546, !5576}
!5576 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5577, size: 64)
!5577 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5578)
!5578 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !5495, file: !5492, line: 39, baseType: !197)
!5579 = !DISubprogram(name: "remove", linkageName: "_ZN4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEE6removeERKS2_", scope: !5495, file: !5492, line: 118, type: !5574, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5580 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEE5countERKS2_", scope: !5495, file: !5492, line: 156, type: !5581, scopeLine: 156, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5581 = !DISubroutineType(types: !5582)
!5582 = !{!5555, !5550, !5583}
!5583 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5584, size: 64)
!5584 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5585)
!5585 = !DIDerivedType(tag: DW_TAG_typedef, name: "key_type", scope: !5495, file: !5492, line: 40, baseType: !197)
!5586 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEE5clearEv", scope: !5495, file: !5492, line: 161, type: !5544, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5587 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEE8pop_backEv", scope: !5495, file: !5492, line: 167, type: !5544, scopeLine: 167, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5588 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEE12pop_back_valEv", scope: !5495, file: !5492, line: 173, type: !5589, scopeLine: 173, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5589 = !DISubroutineType(types: !5590)
!5590 = !{!197, !5546}
!5591 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEEeqERKS9_", scope: !5495, file: !5492, line: 179, type: !5592, scopeLine: 179, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5592 = !DISubroutineType(types: !5593)
!5593 = !{!145, !5550, !5594}
!5594 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5551, size: 64)
!5595 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm9SetVectorIPNS_17MachineBasicBlockENS_11SmallVectorIS2_Lj8EEENS_8SmallSetIS2_Lj8ESt4lessIS2_EEEEneERKS9_", scope: !5495, file: !5492, line: 183, type: !5592, scopeLine: 183, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5596 = !{!3431, !5597, !5598}
!5597 = !DITemplateTypeParameter(name: "Vector", type: !5510)
!5598 = !DITemplateTypeParameter(name: "Set", type: !5499)
!5599 = !DISubprogram(name: "SmallSetVector", scope: !5491, file: !5492, line: 220, type: !5600, scopeLine: 220, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5600 = !DISubroutineType(types: !5601)
!5601 = !{null, !5602}
!5602 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5491, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5603 = !DISubprogram(name: "TailDuplicateBlocks", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass19TailDuplicateBlocksERN4llvm15MachineFunctionE", scope: !5057, file: !5058, line: 101, type: !5245, scopeLine: 101, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!5604 = !DISubprogram(name: "shouldTailDuplicate", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass19shouldTailDuplicateERKN4llvm15MachineFunctionEbRNS1_17MachineBasicBlockE", scope: !5057, file: !5058, line: 102, type: !5605, scopeLine: 102, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!5605 = !DISubroutineType(types: !5606)
!5606 = !{!145, !5243, !2912, !145, !3444}
!5607 = !DISubprogram(name: "isSimpleBB", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass10isSimpleBBEPN4llvm17MachineBasicBlockE", scope: !5057, file: !5058, line: 104, type: !5608, scopeLine: 104, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!5608 = !DISubroutineType(types: !5609)
!5609 = !{!145, !5243, !197}
!5610 = !DISubprogram(name: "canCompletelyDuplicateBB", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass24canCompletelyDuplicateBBERN4llvm17MachineBasicBlockE", scope: !5057, file: !5058, line: 105, type: !5611, scopeLine: 105, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!5611 = !DISubroutineType(types: !5612)
!5612 = !{!145, !5243, !3444}
!5613 = !DISubprogram(name: "duplicateSimpleBB", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass17duplicateSimpleBBEPN4llvm17MachineBasicBlockERNS1_15SmallVectorImplIS3_EERKNS1_8DenseSetIjNS1_12DenseMapInfoIjEEEERNS4_IPNS1_12MachineInstrEEE", scope: !5057, file: !5058, line: 106, type: !5614, scopeLine: 106, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!5614 = !DISubroutineType(types: !5615)
!5615 = !{!145, !5243, !197, !4096, !5337, !5616}
!5616 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5617, size: 64)
!5617 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<llvm::MachineInstr *>", scope: !14, file: !2317, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5618, templateParams: !5699, identifier: "_ZTSN4llvm15SmallVectorImplIPNS_12MachineInstrEEE")
!5618 = !{!5619, !5638, !5644, !5647, !5650, !5651, !5652, !5655, !5656, !5659, !5662, !5667, !5668, !5672, !5675, !5679, !5682, !5685, !5688, !5692, !5696, !5697, !5698}
!5619 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5617, baseType: !5620, flags: DIFlagPublic, extraData: i32 0)
!5620 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<llvm::MachineInstr *, true>", scope: !14, file: !2317, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !5621, templateParams: !5637, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseIPNS_12MachineInstrELb1EEE")
!5621 = !{!5622, !5623, !5627, !5630, !5631, !5634}
!5622 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5620, baseType: !4875, flags: DIFlagPublic, extraData: i32 0)
!5623 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !5620, file: !2317, line: 298, type: !5624, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5624 = !DISubroutineType(types: !5625)
!5625 = !{null, !5626, !2102}
!5626 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5620, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5627 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPNS_12MachineInstrELb1EE13destroy_rangeEPS2_S4_", scope: !5620, file: !2317, line: 301, type: !5628, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!5628 = !DISubroutineType(types: !5629)
!5629 = !{null, !4903, !4903}
!5630 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPNS_12MachineInstrELb1EE4growEm", scope: !5620, file: !2317, line: 346, type: !5624, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5631 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPNS_12MachineInstrELb1EE9push_backERKS2_", scope: !5620, file: !2317, line: 350, type: !5632, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5632 = !DISubroutineType(types: !5633)
!5633 = !{null, !5626, !4953}
!5634 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIPNS_12MachineInstrELb1EE8pop_backEv", scope: !5620, file: !2317, line: 361, type: !5635, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5635 = !DISubroutineType(types: !5636)
!5636 = !{null, !5626}
!5637 = !{!4963, !2627}
!5638 = !DISubprogram(name: "SmallVectorImpl", scope: !5617, file: !2317, line: 374, type: !5639, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!5639 = !DISubroutineType(types: !5640)
!5640 = !{null, !5641, !5642}
!5641 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5617, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5642 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5643, size: 64)
!5643 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5617)
!5644 = !DISubprogram(name: "SmallVectorImpl", scope: !5617, file: !2317, line: 381, type: !5645, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5645 = !DISubroutineType(types: !5646)
!5646 = !{null, !5641, !6}
!5647 = !DISubprogram(name: "~SmallVectorImpl", scope: !5617, file: !2317, line: 386, type: !5648, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5648 = !DISubroutineType(types: !5649)
!5649 = !{null, !5641}
!5650 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEE5clearEv", scope: !5617, file: !2317, line: 396, type: !5648, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5651 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEE6resizeEj", scope: !5617, file: !2317, line: 401, type: !5645, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5652 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEE6resizeEjRKS2_", scope: !5617, file: !2317, line: 413, type: !5653, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5653 = !DISubroutineType(types: !5654)
!5654 = !{null, !5641, !6, !4953}
!5655 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEE7reserveEj", scope: !5617, file: !2317, line: 425, type: !5645, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5656 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEE12pop_back_valEv", scope: !5617, file: !2317, line: 430, type: !5657, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5657 = !DISubroutineType(types: !5658)
!5658 = !{!268, !5641}
!5659 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEE4swapERS3_", scope: !5617, file: !2317, line: 440, type: !5660, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5660 = !DISubroutineType(types: !5661)
!5661 = !{null, !5641, !5616}
!5662 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEE6appendEmRKS2_", scope: !5617, file: !2317, line: 460, type: !5663, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5663 = !DISubroutineType(types: !5664)
!5664 = !{null, !5641, !5665, !4953}
!5665 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !5617, file: !2317, line: 377, baseType: !5666)
!5666 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !4875, file: !2317, line: 97, baseType: !2102)
!5667 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEE6assignEjRKS2_", scope: !5617, file: !2317, line: 470, type: !5653, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5668 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEE5eraseEPS2_", scope: !5617, file: !2317, line: 478, type: !5669, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5669 = !DISubroutineType(types: !5670)
!5670 = !{!5671, !5641, !5671}
!5671 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !5617, file: !2317, line: 376, baseType: !4874)
!5672 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEE5eraseEPS2_S4_", scope: !5617, file: !2317, line: 490, type: !5673, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5673 = !DISubroutineType(types: !5674)
!5674 = !{!5671, !5641, !5671, !5671}
!5675 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEE6insertEPS2_OS2_", scope: !5617, file: !2317, line: 505, type: !5676, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5676 = !DISubroutineType(types: !5677)
!5677 = !{!5671, !5641, !5671, !5678}
!5678 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !268, size: 64)
!5679 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEE6insertEPS2_RKS2_", scope: !5617, file: !2317, line: 537, type: !5680, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5680 = !DISubroutineType(types: !5681)
!5681 = !{!5671, !5641, !5671, !4953}
!5682 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEE6insertEPS2_mRKS2_", scope: !5617, file: !2317, line: 568, type: !5683, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5683 = !DISubroutineType(types: !5684)
!5684 = !{!5671, !5641, !5671, !5665, !4953}
!5685 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEEaSERKS3_", scope: !5617, file: !2317, line: 674, type: !5686, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5686 = !DISubroutineType(types: !5687)
!5687 = !{!5616, !5641, !5642}
!5688 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEEaSEOS3_", scope: !5617, file: !2317, line: 677, type: !5689, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5689 = !DISubroutineType(types: !5690)
!5690 = !{!5616, !5641, !5691}
!5691 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !5617, size: 64)
!5692 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplIPNS_12MachineInstrEEeqERKS3_", scope: !5617, file: !2317, line: 680, type: !5693, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5693 = !DISubroutineType(types: !5694)
!5694 = !{!145, !5695, !5642}
!5695 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5643, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5696 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplIPNS_12MachineInstrEEneERKS3_", scope: !5617, file: !2317, line: 684, type: !5693, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5697 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplIPNS_12MachineInstrEEltERKS3_", scope: !5617, file: !2317, line: 688, type: !5693, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5698 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplIPNS_12MachineInstrEE8set_sizeEj", scope: !5617, file: !2317, line: 702, type: !5645, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5699 = !{!4963}
!5700 = !DISubprogram(name: "TailDuplicate", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass13TailDuplicateEPN4llvm17MachineBasicBlockEbRNS1_15MachineFunctionERNS1_15SmallVectorImplIS3_EERNS6_IPNS1_12MachineInstrEEE", scope: !5057, file: !5058, line: 110, type: !5701, scopeLine: 110, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!5701 = !DISubroutineType(types: !5702)
!5702 = !{!145, !5243, !197, !145, !5247, !4096, !5616}
!5703 = !DISubprogram(name: "TailDuplicateAndUpdate", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass22TailDuplicateAndUpdateEPN4llvm17MachineBasicBlockEbRNS1_15MachineFunctionE", scope: !5057, file: !5058, line: 115, type: !5704, scopeLine: 115, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!5704 = !DISubroutineType(types: !5705)
!5705 = !{!145, !5243, !197, !145, !5247}
!5706 = !DISubprogram(name: "RemoveDeadBlock", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass15RemoveDeadBlockEPN4llvm17MachineBasicBlockE", scope: !5057, file: !5058, line: 119, type: !5707, scopeLine: 119, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!5707 = !DISubroutineType(types: !5708)
!5708 = !{null, !5243, !197}
!5709 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FunctionPass", scope: !14, file: !20, line: 293, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12FunctionPassE")
!5710 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<llvm::MachineOperand, 4U>", scope: !14, file: !2317, line: 880, size: 1216, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5711, templateParams: !5804, identifier: "_ZTSN4llvm11SmallVectorINS_14MachineOperandELj4EEE")
!5711 = !{!5712, !5797, !5806, !5810, !5813, !5818, !5821, !5825}
!5712 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5710, baseType: !5713, flags: DIFlagPublic, extraData: i32 0)
!5713 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<llvm::MachineOperand>", scope: !14, file: !2317, line: 371, size: 448, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5714, templateParams: !5796, identifier: "_ZTSN4llvm15SmallVectorImplINS_14MachineOperandEEE")
!5714 = !{!5715, !5734, !5740, !5743, !5746, !5747, !5748, !5751, !5752, !5755, !5759, !5764, !5765, !5769, !5772, !5776, !5779, !5782, !5785, !5789, !5793, !5794, !5795}
!5715 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5713, baseType: !5716, flags: DIFlagPublic, extraData: i32 0)
!5716 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<llvm::MachineOperand, true>", scope: !14, file: !2317, line: 296, size: 448, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !5717, templateParams: !5733, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseINS_14MachineOperandELb1EEE")
!5717 = !{!5718, !5719, !5723, !5726, !5727, !5730}
!5718 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5716, baseType: !3550, flags: DIFlagPublic, extraData: i32 0)
!5719 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !5716, file: !2317, line: 298, type: !5720, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5720 = !DISubroutineType(types: !5721)
!5721 = !{null, !5722, !2102}
!5722 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5716, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5723 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseINS_14MachineOperandELb1EE13destroy_rangeEPS1_S3_", scope: !5716, file: !2317, line: 301, type: !5724, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!5724 = !DISubroutineType(types: !5725)
!5725 = !{null, !307, !307}
!5726 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseINS_14MachineOperandELb1EE4growEm", scope: !5716, file: !2317, line: 346, type: !5720, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5727 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseINS_14MachineOperandELb1EE9push_backERKS1_", scope: !5716, file: !2317, line: 350, type: !5728, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5728 = !DISubroutineType(types: !5729)
!5729 = !{null, !5722, !473}
!5730 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseINS_14MachineOperandELb1EE8pop_backEv", scope: !5716, file: !2317, line: 361, type: !5731, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5731 = !DISubroutineType(types: !5732)
!5732 = !{null, !5722}
!5733 = !{!3643, !2627}
!5734 = !DISubprogram(name: "SmallVectorImpl", scope: !5713, file: !2317, line: 374, type: !5735, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!5735 = !DISubroutineType(types: !5736)
!5736 = !{null, !5737, !5738}
!5737 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5713, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5738 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5739, size: 64)
!5739 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5713)
!5740 = !DISubprogram(name: "SmallVectorImpl", scope: !5713, file: !2317, line: 381, type: !5741, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5741 = !DISubroutineType(types: !5742)
!5742 = !{null, !5737, !6}
!5743 = !DISubprogram(name: "~SmallVectorImpl", scope: !5713, file: !2317, line: 386, type: !5744, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5744 = !DISubroutineType(types: !5745)
!5745 = !{null, !5737}
!5746 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEE5clearEv", scope: !5713, file: !2317, line: 396, type: !5744, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5747 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEE6resizeEj", scope: !5713, file: !2317, line: 401, type: !5741, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5748 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEE6resizeEjRKS1_", scope: !5713, file: !2317, line: 413, type: !5749, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5749 = !DISubroutineType(types: !5750)
!5750 = !{null, !5737, !6, !473}
!5751 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEE7reserveEj", scope: !5713, file: !2317, line: 425, type: !5741, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5752 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEE12pop_back_valEv", scope: !5713, file: !2317, line: 430, type: !5753, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5753 = !DISubroutineType(types: !5754)
!5754 = !{!248, !5737}
!5755 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEE4swapERS2_", scope: !5713, file: !2317, line: 440, type: !5756, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5756 = !DISubroutineType(types: !5757)
!5757 = !{null, !5737, !5758}
!5758 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5713, size: 64)
!5759 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEE6appendEmRKS1_", scope: !5713, file: !2317, line: 460, type: !5760, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5760 = !DISubroutineType(types: !5761)
!5761 = !{null, !5737, !5762, !473}
!5762 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !5713, file: !2317, line: 377, baseType: !5763)
!5763 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !3550, file: !2317, line: 97, baseType: !2102)
!5764 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEE6assignEjRKS1_", scope: !5713, file: !2317, line: 470, type: !5749, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5765 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEE5eraseEPS1_", scope: !5713, file: !2317, line: 478, type: !5766, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5766 = !DISubroutineType(types: !5767)
!5767 = !{!5768, !5737, !5768}
!5768 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !5713, file: !2317, line: 376, baseType: !3549)
!5769 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEE5eraseEPS1_S3_", scope: !5713, file: !2317, line: 490, type: !5770, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5770 = !DISubroutineType(types: !5771)
!5771 = !{!5768, !5737, !5768, !5768}
!5772 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEE6insertEPS1_OS1_", scope: !5713, file: !2317, line: 505, type: !5773, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5773 = !DISubroutineType(types: !5774)
!5774 = !{!5768, !5737, !5768, !5775}
!5775 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !248, size: 64)
!5776 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEE6insertEPS1_RKS1_", scope: !5713, file: !2317, line: 537, type: !5777, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5777 = !DISubroutineType(types: !5778)
!5778 = !{!5768, !5737, !5768, !473}
!5779 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEE6insertEPS1_mRKS1_", scope: !5713, file: !2317, line: 568, type: !5780, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5780 = !DISubroutineType(types: !5781)
!5781 = !{!5768, !5737, !5768, !5762, !473}
!5782 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEEaSERKS2_", scope: !5713, file: !2317, line: 674, type: !5783, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5783 = !DISubroutineType(types: !5784)
!5784 = !{!5758, !5737, !5738}
!5785 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEEaSEOS2_", scope: !5713, file: !2317, line: 677, type: !5786, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5786 = !DISubroutineType(types: !5787)
!5787 = !{!5758, !5737, !5788}
!5788 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !5713, size: 64)
!5789 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplINS_14MachineOperandEEeqERKS2_", scope: !5713, file: !2317, line: 680, type: !5790, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5790 = !DISubroutineType(types: !5791)
!5791 = !{!145, !5792, !5738}
!5792 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5739, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5793 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplINS_14MachineOperandEEneERKS2_", scope: !5713, file: !2317, line: 684, type: !5790, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5794 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplINS_14MachineOperandEEltERKS2_", scope: !5713, file: !2317, line: 688, type: !5790, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5795 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplINS_14MachineOperandEE8set_sizeEj", scope: !5713, file: !2317, line: 702, type: !5741, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5796 = !{!3643}
!5797 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !5710, file: !2317, line: 882, baseType: !5798, size: 768, offset: 448)
!5798 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<llvm::MachineOperand, 4U>", scope: !14, file: !2317, line: 865, size: 768, flags: DIFlagTypePassByValue, elements: !5799, templateParams: !5804, identifier: "_ZTSN4llvm18SmallVectorStorageINS_14MachineOperandELj4EEE")
!5799 = !{!5800}
!5800 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !5798, file: !2317, line: 866, baseType: !5801, size: 768)
!5801 = !DICompositeType(tag: DW_TAG_array_type, baseType: !3554, size: 768, elements: !5802)
!5802 = !{!5803}
!5803 = !DISubrange(count: 3)
!5804 = !{!3643, !5805}
!5805 = !DITemplateValueParameter(name: "N", type: !6, value: i32 4)
!5806 = !DISubprogram(name: "SmallVector", scope: !5710, file: !2317, line: 884, type: !5807, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5807 = !DISubroutineType(types: !5808)
!5808 = !{null, !5809}
!5809 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5710, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5810 = !DISubprogram(name: "SmallVector", scope: !5710, file: !2317, line: 887, type: !5811, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5811 = !DISubroutineType(types: !5812)
!5812 = !{null, !5809, !6, !473}
!5813 = !DISubprogram(name: "SmallVector", scope: !5710, file: !2317, line: 897, type: !5814, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5814 = !DISubroutineType(types: !5815)
!5815 = !{null, !5809, !5816}
!5816 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5817, size: 64)
!5817 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5710)
!5818 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorINS_14MachineOperandELj4EEaSERKS2_", scope: !5710, file: !2317, line: 902, type: !5819, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5819 = !DISubroutineType(types: !5820)
!5820 = !{!5816, !5809, !5816}
!5821 = !DISubprogram(name: "SmallVector", scope: !5710, file: !2317, line: 908, type: !5822, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5822 = !DISubroutineType(types: !5823)
!5823 = !{null, !5809, !5824}
!5824 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !5710, size: 64)
!5825 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorINS_14MachineOperandELj4EEaSEOS2_", scope: !5710, file: !2317, line: 913, type: !5826, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5826 = !DISubroutineType(types: !5827)
!5827 = !{!5816, !5809, !5824}
!5828 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<llvm::MachineInstr *, 16U>", scope: !14, file: !2317, line: 880, size: 1216, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5829, templateParams: !5836, identifier: "_ZTSN4llvm11SmallVectorIPNS_12MachineInstrELj16EEE")
!5829 = !{!5830, !5831, !5837, !5841, !5844, !5849, !5852, !5856}
!5830 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5828, baseType: !5617, flags: DIFlagPublic, extraData: i32 0)
!5831 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !5828, file: !2317, line: 882, baseType: !5832, size: 960, offset: 256)
!5832 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<llvm::MachineInstr *, 16U>", scope: !14, file: !2317, line: 865, size: 960, flags: DIFlagTypePassByValue, elements: !5833, templateParams: !5836, identifier: "_ZTSN4llvm18SmallVectorStorageIPNS_12MachineInstrELj16EEE")
!5833 = !{!5834}
!5834 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !5832, file: !2317, line: 866, baseType: !5835, size: 960)
!5835 = !DICompositeType(tag: DW_TAG_array_type, baseType: !4879, size: 960, elements: !5212)
!5836 = !{!4963, !5215}
!5837 = !DISubprogram(name: "SmallVector", scope: !5828, file: !2317, line: 884, type: !5838, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5838 = !DISubroutineType(types: !5839)
!5839 = !{null, !5840}
!5840 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5828, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5841 = !DISubprogram(name: "SmallVector", scope: !5828, file: !2317, line: 887, type: !5842, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5842 = !DISubroutineType(types: !5843)
!5843 = !{null, !5840, !6, !4953}
!5844 = !DISubprogram(name: "SmallVector", scope: !5828, file: !2317, line: 897, type: !5845, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5845 = !DISubroutineType(types: !5846)
!5846 = !{null, !5840, !5847}
!5847 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5848, size: 64)
!5848 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5828)
!5849 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIPNS_12MachineInstrELj16EEaSERKS3_", scope: !5828, file: !2317, line: 902, type: !5850, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5850 = !DISubroutineType(types: !5851)
!5851 = !{!5847, !5840, !5847}
!5852 = !DISubprogram(name: "SmallVector", scope: !5828, file: !2317, line: 908, type: !5853, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5853 = !DISubroutineType(types: !5854)
!5854 = !{null, !5840, !5855}
!5855 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !5828, size: 64)
!5856 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIPNS_12MachineInstrELj16EEaSEOS3_", scope: !5828, file: !2317, line: 913, type: !5857, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5857 = !DISubroutineType(types: !5858)
!5858 = !{!5847, !5840, !5855}
!5859 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "bundle_iterator<const llvm::MachineInstr, llvm::ilist_iterator<const llvm::MachineInstr> >", scope: !198, file: !199, line: 144, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !5860, templateParams: !5902, identifier: "_ZTSN4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEE")
!5860 = !{!5861, !5862, !5863, !5867, !5870, !5873, !5876, !5881, !5884, !5885, !5889, !5890, !5894, !5895, !5898, !5899}
!5861 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5859, baseType: !3993, flags: DIFlagPublic, extraData: i32 0)
!5862 = !DIDerivedType(tag: DW_TAG_member, name: "MII", scope: !5859, file: !199, line: 146, baseType: !3990, size: 64, offset: 64)
!5863 = !DISubprogram(name: "bundle_iterator", scope: !5859, file: !199, line: 149, type: !5864, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5864 = !DISubroutineType(types: !5865)
!5865 = !{null, !5866, !3990}
!5866 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5859, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5867 = !DISubprogram(name: "bundle_iterator", scope: !5859, file: !199, line: 151, type: !5868, scopeLine: 151, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5868 = !DISubroutineType(types: !5869)
!5869 = !{null, !5866, !3998}
!5870 = !DISubprogram(name: "bundle_iterator", scope: !5859, file: !199, line: 155, type: !5871, scopeLine: 155, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5871 = !DISubroutineType(types: !5872)
!5872 = !{null, !5866, !352}
!5873 = !DISubprogram(name: "bundle_iterator", scope: !5859, file: !199, line: 163, type: !5874, scopeLine: 163, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5874 = !DISubroutineType(types: !5875)
!5875 = !{null, !5866}
!5876 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEdeEv", scope: !5859, file: !199, line: 165, type: !5877, scopeLine: 165, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5877 = !DISubroutineType(types: !5878)
!5878 = !{!3998, !5879}
!5879 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5880, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5880 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5859)
!5881 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEptEv", scope: !5859, file: !199, line: 166, type: !5882, scopeLine: 166, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5882 = !DISubroutineType(types: !5883)
!5883 = !{!352, !5879}
!5884 = !DISubprogram(name: "operator const llvm::MachineInstr *", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEcvPS3_Ev", scope: !5859, file: !199, line: 168, type: !5882, scopeLine: 168, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5885 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEeqERKS6_", scope: !5859, file: !199, line: 170, type: !5886, scopeLine: 170, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5886 = !DISubroutineType(types: !5887)
!5887 = !{!145, !5879, !5888}
!5888 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5880, size: 64)
!5889 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEneERKS6_", scope: !5859, file: !199, line: 173, type: !5886, scopeLine: 173, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5890 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEmmEv", scope: !5859, file: !199, line: 178, type: !5891, scopeLine: 178, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5891 = !DISubroutineType(types: !5892)
!5892 = !{!5893, !5866}
!5893 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5859, size: 64)
!5894 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEppEv", scope: !5859, file: !199, line: 183, type: !5891, scopeLine: 183, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5895 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEmmEi", scope: !5859, file: !199, line: 189, type: !5896, scopeLine: 189, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5896 = !DISubroutineType(types: !5897)
!5897 = !{!5859, !5866, !32}
!5898 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEppEi", scope: !5859, file: !199, line: 194, type: !5896, scopeLine: 194, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5899 = !DISubprogram(name: "getInstrIterator", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEE16getInstrIteratorEv", scope: !5859, file: !199, line: 200, type: !5900, scopeLine: 200, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5900 = !DISubroutineType(types: !5901)
!5901 = !{!3990, !5879}
!5902 = !{!5903, !5904}
!5903 = !DITemplateTypeParameter(name: "Ty", type: !353)
!5904 = !DITemplateTypeParameter(name: "IterTy", type: !3990)
!5905 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<unsigned int, int>", scope: !839, file: !1387, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !5906, templateParams: !5921, identifier: "_ZTSSt11__pair_baseIjiE")
!5906 = !{!5907, !5911, !5912, !5917}
!5907 = !DISubprogram(name: "__pair_base", scope: !5905, file: !1387, line: 194, type: !5908, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5908 = !DISubroutineType(types: !5909)
!5909 = !{null, !5910}
!5910 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5905, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5911 = !DISubprogram(name: "~__pair_base", scope: !5905, file: !1387, line: 195, type: !5908, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5912 = !DISubprogram(name: "__pair_base", scope: !5905, file: !1387, line: 196, type: !5913, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5913 = !DISubroutineType(types: !5914)
!5914 = !{null, !5910, !5915}
!5915 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5916, size: 64)
!5916 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5905)
!5917 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIjiEaSERKS0_", scope: !5905, file: !1387, line: 197, type: !5918, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!5918 = !DISubroutineType(types: !5919)
!5919 = !{!5920, !5910, !5915}
!5920 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5905, size: 64)
!5921 = !{!1407, !5922}
!5922 = !DITemplateTypeParameter(name: "_U2", type: !32)
!5923 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<unsigned int, int>", scope: !839, file: !1387, line: 208, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !5924, templateParams: !5956, identifier: "_ZTSSt4pairIjiE")
!5924 = !{!5925, !5926, !5927, !5928, !5934, !5938, !5946, !5953}
!5925 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5923, baseType: !5905, flags: DIFlagPrivate, extraData: i32 0)
!5926 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !5923, file: !1387, line: 214, baseType: !6, size: 32)
!5927 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !5923, file: !1387, line: 215, baseType: !32, size: 32, offset: 32)
!5928 = !DISubprogram(name: "pair", scope: !5923, file: !1387, line: 303, type: !5929, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5929 = !DISubroutineType(types: !5930)
!5930 = !{null, !5931, !5932}
!5931 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5923, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5932 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5933, size: 64)
!5933 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5923)
!5934 = !DISubprogram(name: "pair", scope: !5923, file: !1387, line: 304, type: !5935, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5935 = !DISubroutineType(types: !5936)
!5936 = !{null, !5931, !5937}
!5937 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !5923, size: 64)
!5938 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIjiEaSERKS0_", scope: !5923, file: !1387, line: 378, type: !5939, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5939 = !DISubroutineType(types: !5940)
!5940 = !{!5941, !5931, !5942}
!5941 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5923, size: 64)
!5942 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !5943, file: !1281, line: 1928, baseType: !5932)
!5943 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<unsigned int, int> &, const std::__nonesuch_no_braces &>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !5944, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIjiERKSt20__nonesuch_no_bracesE")
!5944 = !{!1472, !5945, !1474}
!5945 = !DITemplateTypeParameter(name: "_Iftrue", type: !5932)
!5946 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIjiEaSEOS0_", scope: !5923, file: !1387, line: 389, type: !5947, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5947 = !DISubroutineType(types: !5948)
!5948 = !{!5941, !5931, !5949}
!5949 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !5950, file: !1281, line: 1928, baseType: !5937)
!5950 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<unsigned int, int> &&, std::__nonesuch_no_braces &&>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !5951, identifier: "_ZTSSt11conditionalILb1EOSt4pairIjiEOSt20__nonesuch_no_bracesE")
!5951 = !{!1472, !5952, !1485}
!5952 = !DITemplateTypeParameter(name: "_Iftrue", type: !5937)
!5953 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIjiE4swapERS0_", scope: !5923, file: !1387, line: 424, type: !5954, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5954 = !DISubroutineType(types: !5955)
!5955 = !{null, !5931, !5941}
!5956 = !{!1974, !5957}
!5957 = !DITemplateTypeParameter(name: "_T2", type: !32)
!5958 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<std::pair<unsigned int, unsigned int>, 4U>", scope: !14, file: !2317, line: 880, size: 448, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !5959, templateParams: !5966, identifier: "_ZTSN4llvm11SmallVectorISt4pairIjjELj4EEE")
!5959 = !{!5960, !5961, !5967, !5971, !5974, !5979, !5982, !5986}
!5960 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !5958, baseType: !5255, flags: DIFlagPublic, extraData: i32 0)
!5961 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !5958, file: !2317, line: 882, baseType: !5962, size: 192, offset: 256)
!5962 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<std::pair<unsigned int, unsigned int>, 4U>", scope: !14, file: !2317, line: 865, size: 192, flags: DIFlagTypePassByValue, elements: !5963, templateParams: !5966, identifier: "_ZTSN4llvm18SmallVectorStorageISt4pairIjjELj4EEE")
!5963 = !{!5964}
!5964 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !5962, file: !2317, line: 866, baseType: !5965, size: 192)
!5965 = !DICompositeType(tag: DW_TAG_array_type, baseType: !4737, size: 192, elements: !5802)
!5966 = !{!4822, !5805}
!5967 = !DISubprogram(name: "SmallVector", scope: !5958, file: !2317, line: 884, type: !5968, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5968 = !DISubroutineType(types: !5969)
!5969 = !{null, !5970}
!5970 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5958, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5971 = !DISubprogram(name: "SmallVector", scope: !5958, file: !2317, line: 887, type: !5972, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5972 = !DISubroutineType(types: !5973)
!5973 = !{null, !5970, !6, !4397}
!5974 = !DISubprogram(name: "SmallVector", scope: !5958, file: !2317, line: 897, type: !5975, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5975 = !DISubroutineType(types: !5976)
!5976 = !{null, !5970, !5977}
!5977 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !5978, size: 64)
!5978 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5958)
!5979 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorISt4pairIjjELj4EEaSERKS3_", scope: !5958, file: !2317, line: 902, type: !5980, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5980 = !DISubroutineType(types: !5981)
!5981 = !{!5977, !5970, !5977}
!5982 = !DISubprogram(name: "SmallVector", scope: !5958, file: !2317, line: 908, type: !5983, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5983 = !DISubroutineType(types: !5984)
!5984 = !{null, !5970, !5985}
!5985 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !5958, size: 64)
!5986 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorISt4pairIjjELj4EEaSEOS3_", scope: !5958, file: !2317, line: 913, type: !5987, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5987 = !DISubroutineType(types: !5988)
!5988 = !{!5977, !5970, !5985}
!5989 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MachineInstrBuilder", scope: !14, file: !771, line: 45, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !5990, identifier: "_ZTSN4llvm19MachineInstrBuilderE")
!5990 = !{!5991, !5993, !5994, !5998, !6001, !6006, !6007, !6010, !6014, !6017, !6020, !6023, !6026, !6029, !6032, !6035, !6038, !6041, !6044, !6047, !6050, !6055, !6060, !6063, !6066, !6069, !6072, !6075, !6078}
!5991 = !DIDerivedType(tag: DW_TAG_member, name: "MF", scope: !5989, file: !771, line: 46, baseType: !5992, size: 64)
!5992 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2914, size: 64)
!5993 = !DIDerivedType(tag: DW_TAG_member, name: "MI", scope: !5989, file: !771, line: 47, baseType: !268, size: 64, offset: 64)
!5994 = !DISubprogram(name: "MachineInstrBuilder", scope: !5989, file: !771, line: 49, type: !5995, scopeLine: 49, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5995 = !DISubroutineType(types: !5996)
!5996 = !{null, !5997}
!5997 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5989, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!5998 = !DISubprogram(name: "MachineInstrBuilder", scope: !5989, file: !771, line: 53, type: !5999, scopeLine: 53, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5999 = !DISubroutineType(types: !6000)
!6000 = !{null, !5997, !5247, !268}
!6001 = !DISubprogram(name: "operator llvm::MachineInstr *", linkageName: "_ZNK4llvm19MachineInstrBuildercvPNS_12MachineInstrEEv", scope: !5989, file: !771, line: 57, type: !6002, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6002 = !DISubroutineType(types: !6003)
!6003 = !{!268, !6004}
!6004 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6005, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6005 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !5989)
!6006 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm19MachineInstrBuilderptEv", scope: !5989, file: !771, line: 58, type: !6002, scopeLine: 58, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6007 = !DISubprogram(name: "operator bundle_iterator", linkageName: "_ZNK4llvm19MachineInstrBuildercvNS_17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS3_EEEEEv", scope: !5989, file: !771, line: 59, type: !6008, scopeLine: 59, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6008 = !DISubroutineType(types: !6009)
!6009 = !{!2480, !6004}
!6010 = !DISubprogram(name: "addReg", linkageName: "_ZNK4llvm19MachineInstrBuilder6addRegEjjj", scope: !5989, file: !771, line: 64, type: !6011, scopeLine: 64, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6011 = !DISubroutineType(types: !6012)
!6012 = !{!6013, !6004, !6, !6, !6}
!6013 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6005, size: 64)
!6014 = !DISubprogram(name: "addImm", linkageName: "_ZNK4llvm19MachineInstrBuilder6addImmEl", scope: !5989, file: !771, line: 83, type: !6015, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6015 = !DISubroutineType(types: !6016)
!6016 = !{!6013, !6004, !284}
!6017 = !DISubprogram(name: "addCImm", linkageName: "_ZNK4llvm19MachineInstrBuilder7addCImmEPKNS_11ConstantIntE", scope: !5989, file: !771, line: 88, type: !6018, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6018 = !DISubroutineType(types: !6019)
!6019 = !{!6013, !6004, !280}
!6020 = !DISubprogram(name: "addFPImm", linkageName: "_ZNK4llvm19MachineInstrBuilder8addFPImmEPKNS_10ConstantFPE", scope: !5989, file: !771, line: 93, type: !6021, scopeLine: 93, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6021 = !DISubroutineType(types: !6022)
!6022 = !{!6013, !6004, !276}
!6023 = !DISubprogram(name: "addMBB", linkageName: "_ZNK4llvm19MachineInstrBuilder6addMBBEPNS_17MachineBasicBlockEh", scope: !5989, file: !771, line: 98, type: !6024, scopeLine: 98, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6024 = !DISubroutineType(types: !6025)
!6025 = !{!6013, !6004, !197, !251}
!6026 = !DISubprogram(name: "addFrameIndex", linkageName: "_ZNK4llvm19MachineInstrBuilder13addFrameIndexEi", scope: !5989, file: !771, line: 104, type: !6027, scopeLine: 104, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6027 = !DISubroutineType(types: !6028)
!6028 = !{!6013, !6004, !32}
!6029 = !DISubprogram(name: "addConstantPoolIndex", linkageName: "_ZNK4llvm19MachineInstrBuilder20addConstantPoolIndexEjih", scope: !5989, file: !771, line: 109, type: !6030, scopeLine: 109, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6030 = !DISubroutineType(types: !6031)
!6031 = !{!6013, !6004, !6, !32, !251}
!6032 = !DISubprogram(name: "addTargetIndex", linkageName: "_ZNK4llvm19MachineInstrBuilder14addTargetIndexEjlh", scope: !5989, file: !771, line: 116, type: !6033, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6033 = !DISubroutineType(types: !6034)
!6034 = !{!6013, !6004, !6, !284, !251}
!6035 = !DISubprogram(name: "addJumpTableIndex", linkageName: "_ZNK4llvm19MachineInstrBuilder17addJumpTableIndexEjh", scope: !5989, file: !771, line: 123, type: !6036, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6036 = !DISubroutineType(types: !6037)
!6037 = !{!6013, !6004, !6, !251}
!6038 = !DISubprogram(name: "addGlobalAddress", linkageName: "_ZNK4llvm19MachineInstrBuilder16addGlobalAddressEPKNS_11GlobalValueElh", scope: !5989, file: !771, line: 129, type: !6039, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6039 = !DISubroutineType(types: !6040)
!6040 = !{!6013, !6004, !321, !284, !251}
!6041 = !DISubprogram(name: "addExternalSymbol", linkageName: "_ZNK4llvm19MachineInstrBuilder17addExternalSymbolEPKch", scope: !5989, file: !771, line: 136, type: !6042, scopeLine: 136, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6042 = !DISubroutineType(types: !6043)
!6043 = !{!6013, !6004, !317, !251}
!6044 = !DISubprogram(name: "addBlockAddress", linkageName: "_ZNK4llvm19MachineInstrBuilder15addBlockAddressEPKNS_12BlockAddressElh", scope: !5989, file: !771, line: 142, type: !6045, scopeLine: 142, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6045 = !DISubroutineType(types: !6046)
!6046 = !{!6013, !6004, !326, !284, !251}
!6047 = !DISubprogram(name: "addRegMask", linkageName: "_ZNK4llvm19MachineInstrBuilder10addRegMaskEPKj", scope: !5989, file: !771, line: 149, type: !6048, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6048 = !DISubroutineType(types: !6049)
!6049 = !{!6013, !6004, !290}
!6050 = !DISubprogram(name: "addMemOperand", linkageName: "_ZNK4llvm19MachineInstrBuilder13addMemOperandEPNS_17MachineMemOperandE", scope: !5989, file: !771, line: 154, type: !6051, scopeLine: 154, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6051 = !DISubroutineType(types: !6052)
!6052 = !{!6013, !6004, !6053}
!6053 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6054, size: 64)
!6054 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MachineMemOperand", scope: !14, file: !270, line: 41, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm17MachineMemOperandE")
!6055 = !DISubprogram(name: "setMemRefs", linkageName: "_ZNK4llvm19MachineInstrBuilder10setMemRefsEPPNS_17MachineMemOperandES3_", scope: !5989, file: !771, line: 159, type: !6056, scopeLine: 159, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6056 = !DISubroutineType(types: !6057)
!6057 = !{!6013, !6004, !6058, !6058}
!6058 = !DIDerivedType(tag: DW_TAG_typedef, name: "mmo_iterator", scope: !269, file: !270, line: 52, baseType: !6059)
!6059 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6053, size: 64)
!6060 = !DISubprogram(name: "addOperand", linkageName: "_ZNK4llvm19MachineInstrBuilder10addOperandERKNS_14MachineOperandE", scope: !5989, file: !771, line: 166, type: !6061, scopeLine: 166, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6061 = !DISubroutineType(types: !6062)
!6062 = !{!6013, !6004, !473}
!6063 = !DISubprogram(name: "addMetadata", linkageName: "_ZNK4llvm19MachineInstrBuilder11addMetadataEPKNS_6MDNodeE", scope: !5989, file: !771, line: 171, type: !6064, scopeLine: 171, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6064 = !DISubroutineType(types: !6065)
!6065 = !{!6013, !6004, !296}
!6066 = !DISubprogram(name: "addSym", linkageName: "_ZNK4llvm19MachineInstrBuilder6addSymEPNS_8MCSymbolE", scope: !5989, file: !771, line: 176, type: !6067, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6067 = !DISubroutineType(types: !6068)
!6068 = !{!6013, !6004, !301}
!6069 = !DISubprogram(name: "setMIFlags", linkageName: "_ZNK4llvm19MachineInstrBuilder10setMIFlagsEj", scope: !5989, file: !771, line: 181, type: !6070, scopeLine: 181, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6070 = !DISubroutineType(types: !6071)
!6071 = !{!6013, !6004, !6}
!6072 = !DISubprogram(name: "setMIFlag", linkageName: "_ZNK4llvm19MachineInstrBuilder9setMIFlagENS_12MachineInstr6MIFlagE", scope: !5989, file: !771, line: 186, type: !6073, scopeLine: 186, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6073 = !DISubroutineType(types: !6074)
!6074 = !{!6013, !6004, !540}
!6075 = !DISubprogram(name: "addDisp", linkageName: "_ZNK4llvm19MachineInstrBuilder7addDispERKNS_14MachineOperandElh", scope: !5989, file: !771, line: 192, type: !6076, scopeLine: 192, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6076 = !DISubroutineType(types: !6077)
!6077 = !{!6013, !6004, !473, !284, !251}
!6078 = !DISubprogram(name: "copyImplicitOps", linkageName: "_ZN4llvm19MachineInstrBuilder15copyImplicitOpsEPKNS_12MachineInstrE", scope: !5989, file: !771, line: 214, type: !6079, scopeLine: 214, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6079 = !DISubroutineType(types: !6080)
!6080 = !{!6013, !5997, !352}
!6081 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DebugLoc", scope: !14, file: !6082, line: 28, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !6083, identifier: "_ZTSN4llvm8DebugLocE")
!6082 = !DIFile(filename: "llvm34/include/llvm/Support/DebugLoc.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e188d7c48d20030c1f9a1f125b024b4f")
!6083 = !{!6084, !6085, !6086, !6089, !6090, !6094, !6098, !6101, !6102, !6107, !6110, !6111, !6118, !6119, !6123, !6124, !6128, !6129}
!6084 = !DIDerivedType(tag: DW_TAG_member, name: "LineCol", scope: !6081, file: !6082, line: 50, baseType: !292, size: 32)
!6085 = !DIDerivedType(tag: DW_TAG_member, name: "ScopeIdx", scope: !6081, file: !6082, line: 54, baseType: !32, size: 32, offset: 32)
!6086 = !DISubprogram(name: "getEmptyKey", linkageName: "_ZN4llvm8DebugLoc11getEmptyKeyEv", scope: !6081, file: !6082, line: 33, type: !6087, scopeLine: 33, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!6087 = !DISubroutineType(types: !6088)
!6088 = !{!6081}
!6089 = !DISubprogram(name: "getTombstoneKey", linkageName: "_ZN4llvm8DebugLoc15getTombstoneKeyEv", scope: !6081, file: !6082, line: 41, type: !6087, scopeLine: 41, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!6090 = !DISubprogram(name: "DebugLoc", scope: !6081, file: !6082, line: 56, type: !6091, scopeLine: 56, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6091 = !DISubroutineType(types: !6092)
!6092 = !{null, !6093}
!6093 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6081, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6094 = !DISubprogram(name: "get", linkageName: "_ZN4llvm8DebugLoc3getEjjPNS_6MDNodeES2_", scope: !6081, file: !6082, line: 60, type: !6095, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!6095 = !DISubroutineType(types: !6096)
!6096 = !{!6081, !6, !6, !6097, !6097}
!6097 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !298, size: 64)
!6098 = !DISubprogram(name: "getFromDILocation", linkageName: "_ZN4llvm8DebugLoc17getFromDILocationEPNS_6MDNodeE", scope: !6081, file: !6082, line: 64, type: !6099, scopeLine: 64, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!6099 = !DISubroutineType(types: !6100)
!6100 = !{!6081, !6097}
!6101 = !DISubprogram(name: "getFromDILexicalBlock", linkageName: "_ZN4llvm8DebugLoc21getFromDILexicalBlockEPNS_6MDNodeE", scope: !6081, file: !6082, line: 67, type: !6099, scopeLine: 67, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!6102 = !DISubprogram(name: "isUnknown", linkageName: "_ZNK4llvm8DebugLoc9isUnknownEv", scope: !6081, file: !6082, line: 70, type: !6103, scopeLine: 70, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6103 = !DISubroutineType(types: !6104)
!6104 = !{!145, !6105}
!6105 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6106, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6106 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6081)
!6107 = !DISubprogram(name: "getLine", linkageName: "_ZNK4llvm8DebugLoc7getLineEv", scope: !6081, file: !6082, line: 72, type: !6108, scopeLine: 72, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6108 = !DISubroutineType(types: !6109)
!6109 = !{!6, !6105}
!6110 = !DISubprogram(name: "getCol", linkageName: "_ZNK4llvm8DebugLoc6getColEv", scope: !6081, file: !6082, line: 76, type: !6108, scopeLine: 76, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6111 = !DISubprogram(name: "getScope", linkageName: "_ZNK4llvm8DebugLoc8getScopeERKNS_11LLVMContextE", scope: !6081, file: !6082, line: 82, type: !6112, scopeLine: 82, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6112 = !DISubroutineType(types: !6113)
!6113 = !{!6097, !6105, !6114}
!6114 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6115, size: 64)
!6115 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6116)
!6116 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "LLVMContext", scope: !14, file: !6117, line: 37, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm11LLVMContextE")
!6117 = !DIFile(filename: "llvm34/include/llvm/IR/Value.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "fb369523392cb020a231366bb46d728b")
!6118 = !DISubprogram(name: "getInlinedAt", linkageName: "_ZNK4llvm8DebugLoc12getInlinedAtERKNS_11LLVMContextE", scope: !6081, file: !6082, line: 86, type: !6112, scopeLine: 86, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6119 = !DISubprogram(name: "getScopeAndInlinedAt", linkageName: "_ZNK4llvm8DebugLoc20getScopeAndInlinedAtERPNS_6MDNodeES3_RKNS_11LLVMContextE", scope: !6081, file: !6082, line: 89, type: !6120, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6120 = !DISubroutineType(types: !6121)
!6121 = !{null, !6105, !6122, !6122, !6114}
!6122 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6097, size: 64)
!6123 = !DISubprogram(name: "getAsMDNode", linkageName: "_ZNK4llvm8DebugLoc11getAsMDNodeERKNS_11LLVMContextE", scope: !6081, file: !6082, line: 95, type: !6112, scopeLine: 95, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6124 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm8DebugLoceqERKS0_", scope: !6081, file: !6082, line: 97, type: !6125, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6125 = !DISubroutineType(types: !6126)
!6126 = !{!145, !6105, !6127}
!6127 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6106, size: 64)
!6128 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm8DebugLocneERKS0_", scope: !6081, file: !6082, line: 100, type: !6125, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6129 = !DISubprogram(name: "dump", linkageName: "_ZNK4llvm8DebugLoc4dumpERKNS_11LLVMContextE", scope: !6081, file: !6082, line: 102, type: !6130, scopeLine: 102, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6130 = !DISubroutineType(types: !6131)
!6131 = !{null, !6105, !6114}
!6132 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<llvm::MachineInstr *, 8U>", scope: !14, file: !2317, line: 880, size: 704, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !6133, templateParams: !6140, identifier: "_ZTSN4llvm11SmallVectorIPNS_12MachineInstrELj8EEE")
!6133 = !{!6134, !6135, !6141, !6145, !6148, !6153, !6156, !6160}
!6134 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !6132, baseType: !5617, flags: DIFlagPublic, extraData: i32 0)
!6135 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !6132, file: !2317, line: 882, baseType: !6136, size: 448, offset: 256)
!6136 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<llvm::MachineInstr *, 8U>", scope: !14, file: !2317, line: 865, size: 448, flags: DIFlagTypePassByValue, elements: !6137, templateParams: !6140, identifier: "_ZTSN4llvm18SmallVectorStorageIPNS_12MachineInstrELj8EEE")
!6137 = !{!6138}
!6138 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !6136, file: !2317, line: 866, baseType: !6139, size: 448)
!6139 = !DICompositeType(tag: DW_TAG_array_type, baseType: !4879, size: 448, elements: !5518)
!6140 = !{!4963, !5504}
!6141 = !DISubprogram(name: "SmallVector", scope: !6132, file: !2317, line: 884, type: !6142, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6142 = !DISubroutineType(types: !6143)
!6143 = !{null, !6144}
!6144 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6132, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6145 = !DISubprogram(name: "SmallVector", scope: !6132, file: !2317, line: 887, type: !6146, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6146 = !DISubroutineType(types: !6147)
!6147 = !{null, !6144, !6, !4953}
!6148 = !DISubprogram(name: "SmallVector", scope: !6132, file: !2317, line: 897, type: !6149, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6149 = !DISubroutineType(types: !6150)
!6150 = !{null, !6144, !6151}
!6151 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6152, size: 64)
!6152 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6132)
!6153 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIPNS_12MachineInstrELj8EEaSERKS3_", scope: !6132, file: !2317, line: 902, type: !6154, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6154 = !DISubroutineType(types: !6155)
!6155 = !{!6151, !6144, !6151}
!6156 = !DISubprogram(name: "SmallVector", scope: !6132, file: !2317, line: 908, type: !6157, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6157 = !DISubroutineType(types: !6158)
!6158 = !{null, !6144, !6159}
!6159 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !6132, size: 64)
!6160 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIPNS_12MachineInstrELj8EEaSEOS3_", scope: !6132, file: !2317, line: 913, type: !6161, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6161 = !DISubroutineType(types: !6162)
!6162 = !{!6151, !6144, !6159}
!6163 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<const llvm::TargetRegisterClass *, llvm::MachineOperand *>", scope: !839, file: !1387, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !6164, templateParams: !6179, identifier: "_ZTSSt11__pair_baseIPKN4llvm19TargetRegisterClassEPNS0_14MachineOperandEE")
!6164 = !{!6165, !6169, !6170, !6175}
!6165 = !DISubprogram(name: "__pair_base", scope: !6163, file: !1387, line: 194, type: !6166, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6166 = !DISubroutineType(types: !6167)
!6167 = !{null, !6168}
!6168 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6163, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6169 = !DISubprogram(name: "~__pair_base", scope: !6163, file: !1387, line: 195, type: !6166, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6170 = !DISubprogram(name: "__pair_base", scope: !6163, file: !1387, line: 196, type: !6171, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6171 = !DISubroutineType(types: !6172)
!6172 = !{null, !6168, !6173}
!6173 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6174, size: 64)
!6174 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6163)
!6175 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIPKN4llvm19TargetRegisterClassEPNS0_14MachineOperandEEaSERKS6_", scope: !6163, file: !1387, line: 197, type: !6176, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!6176 = !DISubroutineType(types: !6177)
!6177 = !{!6178, !6168, !6173}
!6178 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6163, size: 64)
!6179 = !{!6180, !6181}
!6180 = !DITemplateTypeParameter(name: "_U1", type: !2752)
!6181 = !DITemplateTypeParameter(name: "_U2", type: !307)
!6182 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<const llvm::TargetRegisterClass *, llvm::MachineOperand *>", scope: !839, file: !1387, line: 208, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !6183, templateParams: !6215, identifier: "_ZTSSt4pairIPKN4llvm19TargetRegisterClassEPNS0_14MachineOperandEE")
!6183 = !{!6184, !6185, !6186, !6187, !6193, !6197, !6205, !6212}
!6184 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !6182, baseType: !6163, flags: DIFlagPrivate, extraData: i32 0)
!6185 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !6182, file: !1387, line: 214, baseType: !2752, size: 64)
!6186 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !6182, file: !1387, line: 215, baseType: !307, size: 64, offset: 64)
!6187 = !DISubprogram(name: "pair", scope: !6182, file: !1387, line: 303, type: !6188, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6188 = !DISubroutineType(types: !6189)
!6189 = !{null, !6190, !6191}
!6190 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6182, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6191 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6192, size: 64)
!6192 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6182)
!6193 = !DISubprogram(name: "pair", scope: !6182, file: !1387, line: 304, type: !6194, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6194 = !DISubroutineType(types: !6195)
!6195 = !{null, !6190, !6196}
!6196 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !6182, size: 64)
!6197 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPKN4llvm19TargetRegisterClassEPNS0_14MachineOperandEEaSERKS6_", scope: !6182, file: !1387, line: 378, type: !6198, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6198 = !DISubroutineType(types: !6199)
!6199 = !{!6200, !6190, !6201}
!6200 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6182, size: 64)
!6201 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !6202, file: !1281, line: 1928, baseType: !6191)
!6202 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<const llvm::TargetRegisterClass *, llvm::MachineOperand *> &, const std::__nonesuch_no_braces &>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !6203, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIPKN4llvm19TargetRegisterClassEPNS1_14MachineOperandEERKSt20__nonesuch_no_bracesE")
!6203 = !{!1472, !6204, !1474}
!6204 = !DITemplateTypeParameter(name: "_Iftrue", type: !6191)
!6205 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPKN4llvm19TargetRegisterClassEPNS0_14MachineOperandEEaSEOS6_", scope: !6182, file: !1387, line: 389, type: !6206, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6206 = !DISubroutineType(types: !6207)
!6207 = !{!6200, !6190, !6208}
!6208 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !6209, file: !1281, line: 1928, baseType: !6196)
!6209 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<const llvm::TargetRegisterClass *, llvm::MachineOperand *> &&, std::__nonesuch_no_braces &&>", scope: !839, file: !1281, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !960, templateParams: !6210, identifier: "_ZTSSt11conditionalILb1EOSt4pairIPKN4llvm19TargetRegisterClassEPNS1_14MachineOperandEEOSt20__nonesuch_no_bracesE")
!6210 = !{!1472, !6211, !1485}
!6211 = !DITemplateTypeParameter(name: "_Iftrue", type: !6196)
!6212 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIPKN4llvm19TargetRegisterClassEPNS0_14MachineOperandEE4swapERS6_", scope: !6182, file: !1387, line: 424, type: !6213, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6213 = !DISubroutineType(types: !6214)
!6214 = !{null, !6190, !6200}
!6215 = !{!6216, !6217}
!6216 = !DITemplateTypeParameter(name: "_T1", type: !2752)
!6217 = !DITemplateTypeParameter(name: "_T2", type: !307)
!6218 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "opt<unsigned int, false, llvm::cl::parser<unsigned int> >", scope: !13, file: !12, line: 1268, size: 768, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !6219, vtableHolder: !823, templateParams: !6328)
!6219 = !{!6220, !6221, !6293, !6295, !6299, !6304, !6309, !6312, !6315, !6318, !6321, !6324}
!6220 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !6218, baseType: !823, flags: DIFlagPublic, extraData: i32 0)
!6221 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !6218, baseType: !6222, offset: 512, flags: DIFlagPublic, extraData: i32 0)
!6222 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "opt_storage<unsigned int, false, false>", scope: !13, file: !12, line: 1117, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !6223, templateParams: !6291, identifier: "_ZTSN4llvm2cl11opt_storageIjLb0ELb0EEE")
!6223 = !{!6224, !6225, !6272, !6276, !6279, !6284, !6289, !6290}
!6224 = !DIDerivedType(tag: DW_TAG_member, name: "Value", scope: !6222, file: !12, line: 1119, baseType: !6, size: 32, flags: DIFlagPublic)
!6225 = !DIDerivedType(tag: DW_TAG_member, name: "Default", scope: !6222, file: !12, line: 1120, baseType: !6226, size: 128, offset: 64, flags: DIFlagPublic)
!6226 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "OptionValue<unsigned int>", scope: !13, file: !12, line: 417, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !6227, vtableHolder: !6235, templateParams: !6261, identifier: "_ZTSN4llvm2cl11OptionValueIjEE")
!6227 = !{!6228, !6265, !6269}
!6228 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !6226, baseType: !6229, extraData: i32 0)
!6229 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "OptionValueBase<unsigned int, false>", scope: !13, file: !12, line: 411, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !6230, vtableHolder: !6235, templateParams: !6263, identifier: "_ZTSN4llvm2cl15OptionValueBaseIjLb0EEE")
!6230 = !{!6231}
!6231 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !6229, baseType: !6232, extraData: i32 0)
!6232 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "OptionValueCopy<unsigned int>", scope: !13, file: !12, line: 382, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !6233, vtableHolder: !6235, templateParams: !6261, identifier: "_ZTSN4llvm2cl15OptionValueCopyIjEE")
!6233 = !{!6234, !6236, !6237, !6238, !6242, !6247, !6250, !6253, !6256}
!6234 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !6232, baseType: !6235, flags: DIFlagPublic, extraData: i32 0)
!6235 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "GenericOptionValue", scope: !13, file: !12, line: 350, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm2cl18GenericOptionValueE")
!6236 = !DIDerivedType(tag: DW_TAG_member, name: "Value", scope: !6232, file: !12, line: 383, baseType: !6, size: 32, offset: 64)
!6237 = !DIDerivedType(tag: DW_TAG_member, name: "Valid", scope: !6232, file: !12, line: 384, baseType: !145, size: 8, offset: 96)
!6238 = !DISubprogram(name: "OptionValueCopy", scope: !6232, file: !12, line: 386, type: !6239, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6239 = !DISubroutineType(types: !6240)
!6240 = !{null, !6241}
!6241 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6232, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6242 = !DISubprogram(name: "hasValue", linkageName: "_ZNK4llvm2cl15OptionValueCopyIjE8hasValueEv", scope: !6232, file: !12, line: 388, type: !6243, scopeLine: 388, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6243 = !DISubroutineType(types: !6244)
!6244 = !{!145, !6245}
!6245 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6246, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6246 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6232)
!6247 = !DISubprogram(name: "getValue", linkageName: "_ZNK4llvm2cl15OptionValueCopyIjE8getValueEv", scope: !6232, file: !12, line: 390, type: !6248, scopeLine: 390, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6248 = !DISubroutineType(types: !6249)
!6249 = !{!2065, !6245}
!6250 = !DISubprogram(name: "setValue", linkageName: "_ZN4llvm2cl15OptionValueCopyIjE8setValueERKj", scope: !6232, file: !12, line: 395, type: !6251, scopeLine: 395, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6251 = !DISubroutineType(types: !6252)
!6252 = !{null, !6241, !2065}
!6253 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm2cl15OptionValueCopyIjE7compareERKj", scope: !6232, file: !12, line: 397, type: !6254, scopeLine: 397, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6254 = !DISubroutineType(types: !6255)
!6255 = !{!145, !6245, !2065}
!6256 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm2cl15OptionValueCopyIjE7compareERKNS0_18GenericOptionValueE", scope: !6232, file: !12, line: 401, type: !6257, scopeLine: 401, containingType: !6232, virtualIndex: 2, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!6257 = !DISubroutineType(types: !6258)
!6258 = !{!145, !6245, !6259}
!6259 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6260, size: 64)
!6260 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6235)
!6261 = !{!6262}
!6262 = !DITemplateTypeParameter(name: "DataType", type: !6)
!6263 = !{!6262, !6264}
!6264 = !DITemplateValueParameter(name: "isClass", type: !145, value: i8 0)
!6265 = !DISubprogram(name: "OptionValue", scope: !6226, file: !12, line: 418, type: !6266, scopeLine: 418, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6266 = !DISubroutineType(types: !6267)
!6267 = !{null, !6268}
!6268 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6226, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6269 = !DISubprogram(name: "OptionValue", scope: !6226, file: !12, line: 420, type: !6270, scopeLine: 420, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6270 = !DISubroutineType(types: !6271)
!6271 = !{null, !6268, !2065}
!6272 = !DISubprogram(name: "opt_storage", scope: !6222, file: !12, line: 1124, type: !6273, scopeLine: 1124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6273 = !DISubroutineType(types: !6274)
!6274 = !{null, !6275}
!6275 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6222, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6276 = !DISubprogram(name: "getValue", linkageName: "_ZN4llvm2cl11opt_storageIjLb0ELb0EE8getValueEv", scope: !6222, file: !12, line: 1132, type: !6277, scopeLine: 1132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6277 = !DISubroutineType(types: !6278)
!6278 = !{!2428, !6275}
!6279 = !DISubprogram(name: "getValue", linkageName: "_ZNK4llvm2cl11opt_storageIjLb0ELb0EE8getValueEv", scope: !6222, file: !12, line: 1133, type: !6280, scopeLine: 1133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6280 = !DISubroutineType(types: !6281)
!6281 = !{!6, !6282}
!6282 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6283, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6283 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6222)
!6284 = !DISubprogram(name: "getDefault", linkageName: "_ZNK4llvm2cl11opt_storageIjLb0ELb0EE10getDefaultEv", scope: !6222, file: !12, line: 1135, type: !6285, scopeLine: 1135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6285 = !DISubroutineType(types: !6286)
!6286 = !{!6287, !6282}
!6287 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6288, size: 64)
!6288 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6226)
!6289 = !DISubprogram(name: "operator unsigned int", linkageName: "_ZNK4llvm2cl11opt_storageIjLb0ELb0EEcvjEv", scope: !6222, file: !12, line: 1137, type: !6280, scopeLine: 1137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6290 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm2cl11opt_storageIjLb0ELb0EEptEv", scope: !6222, file: !12, line: 1140, type: !6280, scopeLine: 1140, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6291 = !{!6262, !6292, !6264}
!6292 = !DITemplateValueParameter(name: "ExternalStorage", type: !145, value: i8 0)
!6293 = !DIDerivedType(tag: DW_TAG_member, name: "Parser", scope: !6218, file: !12, line: 1152, baseType: !6294, size: 64, offset: 704)
!6294 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "parser<unsigned int>", scope: !13, file: !12, line: 820, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm2cl6parserIjEE")
!6295 = !DISubprogram(name: "handleOccurrence", linkageName: "_ZN4llvm2cl3optIjLb0ENS0_6parserIjEEE16handleOccurrenceEjNS_9StringRefES5_", scope: !6218, file: !12, line: 1154, type: !6296, scopeLine: 1154, containingType: !6218, virtualIndex: 0, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!6296 = !DISubroutineType(types: !6297)
!6297 = !{!145, !6298, !6, !3093, !3093}
!6298 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6218, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6299 = !DISubprogram(name: "getValueExpectedFlagDefault", linkageName: "_ZNK4llvm2cl3optIjLb0ENS0_6parserIjEEE27getValueExpectedFlagDefaultEv", scope: !6218, file: !12, line: 1165, type: !6300, scopeLine: 1165, containingType: !6218, virtualIndex: 1, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!6300 = !DISubroutineType(types: !6301)
!6301 = !{!791, !6302}
!6302 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6303, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6303 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6218)
!6304 = !DISubprogram(name: "getExtraOptionNames", linkageName: "_ZN4llvm2cl3optIjLb0ENS0_6parserIjEEE19getExtraOptionNamesERNS_15SmallVectorImplIPKcEE", scope: !6218, file: !12, line: 1168, type: !6305, scopeLine: 1168, containingType: !6218, virtualIndex: 6, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!6305 = !DISubroutineType(types: !6306)
!6306 = !{null, !6298, !6307}
!6307 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6308, size: 64)
!6308 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<const char *>", scope: !14, file: !2317, line: 371, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm15SmallVectorImplIPKcEE")
!6309 = !DISubprogram(name: "getOptionWidth", linkageName: "_ZNK4llvm2cl3optIjLb0ENS0_6parserIjEEE14getOptionWidthEv", scope: !6218, file: !12, line: 1173, type: !6310, scopeLine: 1173, containingType: !6218, virtualIndex: 3, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!6310 = !DISubroutineType(types: !6311)
!6311 = !{!2102, !6302}
!6312 = !DISubprogram(name: "printOptionInfo", linkageName: "_ZNK4llvm2cl3optIjLb0ENS0_6parserIjEEE15printOptionInfoEm", scope: !6218, file: !12, line: 1174, type: !6313, scopeLine: 1174, containingType: !6218, virtualIndex: 4, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!6313 = !DISubroutineType(types: !6314)
!6314 = !{null, !6302, !2102}
!6315 = !DISubprogram(name: "printOptionValue", linkageName: "_ZNK4llvm2cl3optIjLb0ENS0_6parserIjEEE16printOptionValueEmb", scope: !6218, file: !12, line: 1178, type: !6316, scopeLine: 1178, containingType: !6218, virtualIndex: 5, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!6316 = !DISubroutineType(types: !6317)
!6317 = !{null, !6302, !2102, !145}
!6318 = !DISubprogram(name: "done", linkageName: "_ZN4llvm2cl3optIjLb0ENS0_6parserIjEEE4doneEv", scope: !6218, file: !12, line: 1185, type: !6319, scopeLine: 1185, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6319 = !DISubroutineType(types: !6320)
!6320 = !{null, !6298}
!6321 = !DISubprogram(name: "setInitialValue", linkageName: "_ZN4llvm2cl3optIjLb0ENS0_6parserIjEEE15setInitialValueERKj", scope: !6218, file: !12, line: 1191, type: !6322, scopeLine: 1191, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6322 = !DISubroutineType(types: !6323)
!6323 = !{null, !6298, !2065}
!6324 = !DISubprogram(name: "getParser", linkageName: "_ZN4llvm2cl3optIjLb0ENS0_6parserIjEEE9getParserEv", scope: !6218, file: !12, line: 1193, type: !6325, scopeLine: 1193, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6325 = !DISubroutineType(types: !6326)
!6326 = !{!6327, !6298}
!6327 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6294, size: 64)
!6328 = !{!6262, !6329, !6330}
!6329 = !DITemplateValueParameter(name: "ExternalStorage", type: !145, defaulted: true, value: i8 0)
!6330 = !DITemplateTypeParameter(name: "ParserClass", type: !6294)
!6331 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "basic_parser<unsigned int>", scope: !13, file: !12, line: 835, size: 64, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !6332, vtableHolder: !6334, templateParams: !6261)
!6332 = !{!6333}
!6333 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !6331, baseType: !6334, flags: DIFlagPublic, extraData: i32 0)
!6334 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "basic_parser_impl", scope: !13, file: !12, line: 693, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm2cl17basic_parser_implE")
!6335 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "opt<bool, false, llvm::cl::parser<bool> >", scope: !13, file: !12, line: 1272, size: 832, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !6336, vtableHolder: !823, templateParams: !6439)
!6336 = !{!6337, !6338, !6406, !6408, !6412, !6417, !6420, !6423, !6426, !6429, !6432, !6435}
!6337 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !6335, baseType: !823, flags: DIFlagPublic, extraData: i32 0)
!6338 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !6335, baseType: !6339, offset: 512, flags: DIFlagPublic, extraData: i32 0)
!6339 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "opt_storage<bool, false, false>", scope: !13, file: !12, line: 1117, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !6340, templateParams: !6405, identifier: "_ZTSN4llvm2cl11opt_storageIbLb0ELb0EEE")
!6340 = !{!6341, !6342, !6385, !6389, !6393, !6398, !6403, !6404}
!6341 = !DIDerivedType(tag: DW_TAG_member, name: "Value", scope: !6339, file: !12, line: 1119, baseType: !145, size: 8, flags: DIFlagPublic)
!6342 = !DIDerivedType(tag: DW_TAG_member, name: "Default", scope: !6339, file: !12, line: 1120, baseType: !6343, size: 128, offset: 64, flags: DIFlagPublic)
!6343 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "OptionValue<bool>", scope: !13, file: !12, line: 417, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !6344, vtableHolder: !6235, templateParams: !6375, identifier: "_ZTSN4llvm2cl11OptionValueIbEE")
!6344 = !{!6345, !6378, !6382}
!6345 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !6343, baseType: !6346, extraData: i32 0)
!6346 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "OptionValueBase<bool, false>", scope: !13, file: !12, line: 411, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !6347, vtableHolder: !6235, templateParams: !6377, identifier: "_ZTSN4llvm2cl15OptionValueBaseIbLb0EEE")
!6347 = !{!6348}
!6348 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !6346, baseType: !6349, extraData: i32 0)
!6349 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "OptionValueCopy<bool>", scope: !13, file: !12, line: 382, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !6350, vtableHolder: !6235, templateParams: !6375, identifier: "_ZTSN4llvm2cl15OptionValueCopyIbEE")
!6350 = !{!6351, !6352, !6353, !6354, !6358, !6363, !6366, !6369, !6372}
!6351 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !6349, baseType: !6235, flags: DIFlagPublic, extraData: i32 0)
!6352 = !DIDerivedType(tag: DW_TAG_member, name: "Value", scope: !6349, file: !12, line: 383, baseType: !145, size: 8, offset: 64)
!6353 = !DIDerivedType(tag: DW_TAG_member, name: "Valid", scope: !6349, file: !12, line: 384, baseType: !145, size: 8, offset: 72)
!6354 = !DISubprogram(name: "OptionValueCopy", scope: !6349, file: !12, line: 386, type: !6355, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6355 = !DISubroutineType(types: !6356)
!6356 = !{null, !6357}
!6357 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6349, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6358 = !DISubprogram(name: "hasValue", linkageName: "_ZNK4llvm2cl15OptionValueCopyIbE8hasValueEv", scope: !6349, file: !12, line: 388, type: !6359, scopeLine: 388, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6359 = !DISubroutineType(types: !6360)
!6360 = !{!145, !6361}
!6361 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6362, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6362 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6349)
!6363 = !DISubprogram(name: "getValue", linkageName: "_ZNK4llvm2cl15OptionValueCopyIbE8getValueEv", scope: !6349, file: !12, line: 390, type: !6364, scopeLine: 390, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6364 = !DISubroutineType(types: !6365)
!6365 = !{!5041, !6361}
!6366 = !DISubprogram(name: "setValue", linkageName: "_ZN4llvm2cl15OptionValueCopyIbE8setValueERKb", scope: !6349, file: !12, line: 395, type: !6367, scopeLine: 395, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6367 = !DISubroutineType(types: !6368)
!6368 = !{null, !6357, !5041}
!6369 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm2cl15OptionValueCopyIbE7compareERKb", scope: !6349, file: !12, line: 397, type: !6370, scopeLine: 397, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6370 = !DISubroutineType(types: !6371)
!6371 = !{!145, !6361, !5041}
!6372 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm2cl15OptionValueCopyIbE7compareERKNS0_18GenericOptionValueE", scope: !6349, file: !12, line: 401, type: !6373, scopeLine: 401, containingType: !6349, virtualIndex: 2, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!6373 = !DISubroutineType(types: !6374)
!6374 = !{!145, !6361, !6259}
!6375 = !{!6376}
!6376 = !DITemplateTypeParameter(name: "DataType", type: !145)
!6377 = !{!6376, !6264}
!6378 = !DISubprogram(name: "OptionValue", scope: !6343, file: !12, line: 418, type: !6379, scopeLine: 418, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6379 = !DISubroutineType(types: !6380)
!6380 = !{null, !6381}
!6381 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6343, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6382 = !DISubprogram(name: "OptionValue", scope: !6343, file: !12, line: 420, type: !6383, scopeLine: 420, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6383 = !DISubroutineType(types: !6384)
!6384 = !{null, !6381, !5041}
!6385 = !DISubprogram(name: "opt_storage", scope: !6339, file: !12, line: 1124, type: !6386, scopeLine: 1124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6386 = !DISubroutineType(types: !6387)
!6387 = !{null, !6388}
!6388 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6339, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6389 = !DISubprogram(name: "getValue", linkageName: "_ZN4llvm2cl11opt_storageIbLb0ELb0EE8getValueEv", scope: !6339, file: !12, line: 1132, type: !6390, scopeLine: 1132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6390 = !DISubroutineType(types: !6391)
!6391 = !{!6392, !6388}
!6392 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !145, size: 64)
!6393 = !DISubprogram(name: "getValue", linkageName: "_ZNK4llvm2cl11opt_storageIbLb0ELb0EE8getValueEv", scope: !6339, file: !12, line: 1133, type: !6394, scopeLine: 1133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6394 = !DISubroutineType(types: !6395)
!6395 = !{!145, !6396}
!6396 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6397, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6397 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6339)
!6398 = !DISubprogram(name: "getDefault", linkageName: "_ZNK4llvm2cl11opt_storageIbLb0ELb0EE10getDefaultEv", scope: !6339, file: !12, line: 1135, type: !6399, scopeLine: 1135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6399 = !DISubroutineType(types: !6400)
!6400 = !{!6401, !6396}
!6401 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6402, size: 64)
!6402 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6343)
!6403 = !DISubprogram(name: "operator bool", linkageName: "_ZNK4llvm2cl11opt_storageIbLb0ELb0EEcvbEv", scope: !6339, file: !12, line: 1137, type: !6394, scopeLine: 1137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6404 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm2cl11opt_storageIbLb0ELb0EEptEv", scope: !6339, file: !12, line: 1140, type: !6394, scopeLine: 1140, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6405 = !{!6376, !6292, !6264}
!6406 = !DIDerivedType(tag: DW_TAG_member, name: "Parser", scope: !6335, file: !12, line: 1152, baseType: !6407, size: 128, offset: 704)
!6407 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "parser<bool>", scope: !13, file: !12, line: 742, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm2cl6parserIbEE")
!6408 = !DISubprogram(name: "handleOccurrence", linkageName: "_ZN4llvm2cl3optIbLb0ENS0_6parserIbEEE16handleOccurrenceEjNS_9StringRefES5_", scope: !6335, file: !12, line: 1154, type: !6409, scopeLine: 1154, containingType: !6335, virtualIndex: 0, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!6409 = !DISubroutineType(types: !6410)
!6410 = !{!145, !6411, !6, !3093, !3093}
!6411 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6335, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6412 = !DISubprogram(name: "getValueExpectedFlagDefault", linkageName: "_ZNK4llvm2cl3optIbLb0ENS0_6parserIbEEE27getValueExpectedFlagDefaultEv", scope: !6335, file: !12, line: 1165, type: !6413, scopeLine: 1165, containingType: !6335, virtualIndex: 1, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!6413 = !DISubroutineType(types: !6414)
!6414 = !{!791, !6415}
!6415 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6416, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6416 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6335)
!6417 = !DISubprogram(name: "getExtraOptionNames", linkageName: "_ZN4llvm2cl3optIbLb0ENS0_6parserIbEEE19getExtraOptionNamesERNS_15SmallVectorImplIPKcEE", scope: !6335, file: !12, line: 1168, type: !6418, scopeLine: 1168, containingType: !6335, virtualIndex: 6, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!6418 = !DISubroutineType(types: !6419)
!6419 = !{null, !6411, !6307}
!6420 = !DISubprogram(name: "getOptionWidth", linkageName: "_ZNK4llvm2cl3optIbLb0ENS0_6parserIbEEE14getOptionWidthEv", scope: !6335, file: !12, line: 1173, type: !6421, scopeLine: 1173, containingType: !6335, virtualIndex: 3, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!6421 = !DISubroutineType(types: !6422)
!6422 = !{!2102, !6415}
!6423 = !DISubprogram(name: "printOptionInfo", linkageName: "_ZNK4llvm2cl3optIbLb0ENS0_6parserIbEEE15printOptionInfoEm", scope: !6335, file: !12, line: 1174, type: !6424, scopeLine: 1174, containingType: !6335, virtualIndex: 4, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!6424 = !DISubroutineType(types: !6425)
!6425 = !{null, !6415, !2102}
!6426 = !DISubprogram(name: "printOptionValue", linkageName: "_ZNK4llvm2cl3optIbLb0ENS0_6parserIbEEE16printOptionValueEmb", scope: !6335, file: !12, line: 1178, type: !6427, scopeLine: 1178, containingType: !6335, virtualIndex: 5, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!6427 = !DISubroutineType(types: !6428)
!6428 = !{null, !6415, !2102, !145}
!6429 = !DISubprogram(name: "done", linkageName: "_ZN4llvm2cl3optIbLb0ENS0_6parserIbEEE4doneEv", scope: !6335, file: !12, line: 1185, type: !6430, scopeLine: 1185, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6430 = !DISubroutineType(types: !6431)
!6431 = !{null, !6411}
!6432 = !DISubprogram(name: "setInitialValue", linkageName: "_ZN4llvm2cl3optIbLb0ENS0_6parserIbEEE15setInitialValueERKb", scope: !6335, file: !12, line: 1191, type: !6433, scopeLine: 1191, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6433 = !DISubroutineType(types: !6434)
!6434 = !{null, !6411, !5041}
!6435 = !DISubprogram(name: "getParser", linkageName: "_ZN4llvm2cl3optIbLb0ENS0_6parserIbEEE9getParserEv", scope: !6335, file: !12, line: 1193, type: !6436, scopeLine: 1193, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6436 = !DISubroutineType(types: !6437)
!6437 = !{!6438, !6411}
!6438 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6407, size: 64)
!6439 = !{!6376, !6329, !6440}
!6440 = !DITemplateTypeParameter(name: "ParserClass", type: !6407)
!6441 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "basic_parser<bool>", scope: !13, file: !12, line: 768, size: 64, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !6442, vtableHolder: !6334, templateParams: !6375)
!6442 = !{!6443}
!6443 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !6441, baseType: !6334, flags: DIFlagPublic, extraData: i32 0)
!6444 = !{!6445, !6450, !6455, !6457, !6460, !6465, !6467, !6470, !6472, !6474, !6492, !6497, !6499, !6504, !6506, !6511, !6516, !6521, !6526, !6532, !6537, !6542, !6547, !6552, !6557, !6562, !6567, !6572, !6577, !6580, !6585, !6587, !6592, !6597, !6599, !6604, !6606, !6611, !6616, !6621, !6626, !6631, !6633, !6635, !6640, !6645, !6647, !6697, !6702, !6704, !6706, !6711, !6716, !6718, !6723, !6728, !6731, !6736, !6738, !6743, !6748, !6753, !6758, !6763, !6765, !6770, !6775, !6777, !6782, !6787, !6792, !6797, !6800, !6805, !6810, !6812, !6817, !6819, !6821, !6826, !6831, !6833, !6838, !6840, !6842, !6844, !6849, !6852, !6857, !6859, !6861, !6866, !6871, !6876, !6881, !6886, !6891, !6896, !6901, !6906, !6908, !6913, !6915, !6920, !6922, !6924, !6926, !6931, !6933, !6938, !6941, !6943, !6948, !6950, !6952, !6954, !6959, !6964, !6969, !6974, !6979, !6981, !6983, !6988, !6990, !6992, !6994, !6999, !7001, !7006, !7008, !7013, !7015, !7017, !7022, !7024, !7029, !7031, !7036, !7041, !7043, !7045, !7047, !7049, !7051, !7056, !7061, !7063, !7065, !7070, !7072, !7077, !7079, !7081, !7083, !7085, !7088, !7090, !7092, !7097, !7102, !7104, !7109, !7111, !7113, !7115, !7120, !7125, !7130, !7132, !7137, !7139, !7141, !7143, !7145, !7147, !7152, !7157, !7159, !7161, !7163, !7165, !7168, !7170, !7172, !7174, !7179}
!6445 = !DIGlobalVariableExpression(var: !6446, expr: !DIExpression())
!6446 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 45, type: !6447, isLocal: true, isDefinition: true)
!6447 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 112, elements: !6448)
!6448 = !{!6449}
!6449 = !DISubrange(count: 14)
!6450 = !DIGlobalVariableExpression(var: !6451, expr: !DIExpression())
!6451 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 46, type: !6452, isLocal: true, isDefinition: true)
!6452 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 400, elements: !6453)
!6453 = !{!6454}
!6454 = !DISubrange(count: 50)
!6455 = !DIGlobalVariableExpression(var: !6456, expr: !DIExpression())
!6456 = distinct !DIGlobalVariable(name: "TailDuplicateSize", linkageName: "_ZL17TailDuplicateSize", scope: !0, file: !5058, line: 45, type: !6218, isLocal: true, isDefinition: true)
!6457 = !DIGlobalVariableExpression(var: !6458, expr: !DIExpression())
!6458 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 50, type: !6459, isLocal: true, isDefinition: true)
!6459 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 128, elements: !2456)
!6460 = !DIGlobalVariableExpression(var: !6461, expr: !DIExpression())
!6461 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 51, type: !6462, isLocal: true, isDefinition: true)
!6462 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 392, elements: !6463)
!6463 = !{!6464}
!6464 = !DISubrange(count: 49)
!6465 = !DIGlobalVariableExpression(var: !6466, expr: !DIExpression())
!6466 = distinct !DIGlobalVariable(name: "TailDupVerify", linkageName: "_ZL13TailDupVerify", scope: !0, file: !5058, line: 50, type: !6335, isLocal: true, isDefinition: true)
!6467 = !DIGlobalVariableExpression(var: !6468, expr: !DIExpression())
!6468 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 55, type: !6469, isLocal: true, isDefinition: true)
!6469 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 120, elements: !5212)
!6470 = !DIGlobalVariableExpression(var: !6471, expr: !DIExpression())
!6471 = distinct !DIGlobalVariable(name: "TailDupLimit", linkageName: "_ZL12TailDupLimit", scope: !0, file: !5058, line: 55, type: !6218, isLocal: true, isDefinition: true)
!6472 = !DIGlobalVariableExpression(var: !6473, expr: !DIExpression())
!6473 = distinct !DIGlobalVariable(name: "TailDuplicateID", linkageName: "_ZN4llvm15TailDuplicateIDE", scope: !14, file: !5058, line: 125, type: !3869, isLocal: false, isDefinition: true)
!6474 = !DIGlobalVariableExpression(var: !6475, expr: !DIExpression())
!6475 = distinct !DIGlobalVariable(name: "initialized", scope: !6476, file: !5058, line: 127, type: !6491, isLocal: true, isDefinition: true)
!6476 = distinct !DISubprogram(name: "initializeTailDuplicatePassPass", linkageName: "_ZN4llvm31initializeTailDuplicatePassPassERNS_12PassRegistryE", scope: !14, file: !5058, line: 127, type: !6477, scopeLine: 127, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !6482)
!6477 = !DISubroutineType(types: !6478)
!6478 = !{null, !6479}
!6479 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6480, size: 64)
!6480 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PassRegistry", scope: !14, file: !6481, line: 35, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12PassRegistryE")
!6481 = !DIFile(filename: "llvm34/include/llvm/PassRegistry.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "ea055db655addf2322a009df18bef61e")
!6482 = !{!6483, !6484, !6488}
!6483 = !DILocalVariable(name: "Registry", arg: 1, scope: !6476, file: !5058, line: 127, type: !6479)
!6484 = !DILocalVariable(name: "old_val", scope: !6476, file: !5058, line: 127, type: !6485)
!6485 = !DIDerivedType(tag: DW_TAG_typedef, name: "cas_flag", scope: !6487, file: !6486, line: 26, baseType: !292)
!6486 = !DIFile(filename: "llvm34/include/llvm/Support/Atomic.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "bb80c3b7b95076871079a09befb3cafb")
!6487 = !DINamespace(name: "sys", scope: !14)
!6488 = !DILocalVariable(name: "tmp", scope: !6489, file: !5058, line: 127, type: !6485)
!6489 = distinct !DILexicalBlock(scope: !6490, file: !5058, line: 127, column: 1)
!6490 = distinct !DILexicalBlock(scope: !6476, file: !5058, line: 127, column: 1)
!6491 = !DIDerivedType(tag: DW_TAG_volatile_type, baseType: !6485)
!6492 = !DIGlobalVariableExpression(var: !6493, expr: !DIExpression())
!6493 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 127, type: !6494, isLocal: true, isDefinition: true)
!6494 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 384, elements: !6495)
!6495 = !{!6496}
!6496 = !DISubrange(count: 48)
!6497 = !DIGlobalVariableExpression(var: !6498, expr: !DIExpression())
!6498 = distinct !DIGlobalVariable(name: "ID", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass2IDE", scope: !5059, file: !5058, line: 122, type: !319, isLocal: true, isDefinition: true, declaration: !5239)
!6499 = !DIGlobalVariableExpression(var: !6500, expr: !DIExpression())
!6500 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 127, type: !6501, isLocal: true, isDefinition: true)
!6501 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 136, elements: !6502)
!6502 = !{!6503}
!6503 = !DISubrange(count: 17)
!6504 = !DIGlobalVariableExpression(var: !6505, expr: !DIExpression())
!6505 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 127, type: !6459, isLocal: true, isDefinition: true)
!6506 = !DIGlobalVariableExpression(var: !6507, expr: !DIExpression())
!6507 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 271, type: !6508, isLocal: true, isDefinition: true)
!6508 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 336, elements: !6509)
!6509 = !{!6510}
!6510 = !DISubrange(count: 42)
!6511 = !DIGlobalVariableExpression(var: !6512, expr: !DIExpression())
!6512 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 271, type: !6513, isLocal: true, isDefinition: true)
!6513 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 736, elements: !6514)
!6514 = !{!6515}
!6515 = !DISubrange(count: 92)
!6516 = !DIGlobalVariableExpression(var: !6517, expr: !DIExpression())
!6517 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 271, type: !6518, isLocal: true, isDefinition: true)
!6518 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 352, elements: !6519)
!6519 = !{!6520}
!6520 = !DISubrange(count: 44)
!6521 = !DIGlobalVariableExpression(var: !6522, expr: !DIExpression())
!6522 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 271, type: !6523, isLocal: true, isDefinition: true)
!6523 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 3936, elements: !6524)
!6524 = !{!6525}
!6525 = !DISubrange(count: 492)
!6526 = !DIGlobalVariableExpression(var: !6527, expr: !DIExpression())
!6527 = distinct !DIGlobalVariable(scope: null, file: !6528, line: 180, type: !6529, isLocal: true, isDefinition: true)
!6528 = !DIFile(filename: "llvm34/include/llvm/PassAnalysisSupport.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e41256537e53ea4c00bf424a000ee518")
!6529 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 344, elements: !6530)
!6530 = !{!6531}
!6531 = !DISubrange(count: 43)
!6532 = !DIGlobalVariableExpression(var: !6533, expr: !DIExpression())
!6533 = distinct !DIGlobalVariable(scope: null, file: !6528, line: 180, type: !6534, isLocal: true, isDefinition: true)
!6534 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 456, elements: !6535)
!6535 = !{!6536}
!6536 = !DISubrange(count: 57)
!6537 = !DIGlobalVariableExpression(var: !6538, expr: !DIExpression())
!6538 = distinct !DIGlobalVariable(scope: null, file: !6528, line: 180, type: !6539, isLocal: true, isDefinition: true)
!6539 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 408, elements: !6540)
!6540 = !{!6541}
!6541 = !DISubrange(count: 51)
!6542 = !DIGlobalVariableExpression(var: !6543, expr: !DIExpression())
!6543 = distinct !DIGlobalVariable(scope: null, file: !6528, line: 180, type: !6544, isLocal: true, isDefinition: true)
!6544 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 784, elements: !6545)
!6545 = !{!6546}
!6546 = !DISubrange(count: 98)
!6547 = !DIGlobalVariableExpression(var: !6548, expr: !DIExpression())
!6548 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 305, type: !6549, isLocal: true, isDefinition: true)
!6549 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 240, elements: !6550)
!6550 = !{!6551}
!6551 = !DISubrange(count: 30)
!6552 = !DIGlobalVariableExpression(var: !6553, expr: !DIExpression())
!6553 = distinct !DIGlobalVariable(scope: null, file: !3094, line: 78, type: !6554, isLocal: true, isDefinition: true)
!6554 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 376, elements: !6555)
!6555 = !{!6556}
!6556 = !DISubrange(count: 47)
!6557 = !DIGlobalVariableExpression(var: !6558, expr: !DIExpression())
!6558 = distinct !DIGlobalVariable(scope: null, file: !3094, line: 78, type: !6559, isLocal: true, isDefinition: true)
!6559 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 448, elements: !6560)
!6560 = !{!6561}
!6561 = !DISubrange(count: 56)
!6562 = !DIGlobalVariableExpression(var: !6563, expr: !DIExpression())
!6563 = distinct !DIGlobalVariable(scope: null, file: !3094, line: 78, type: !6564, isLocal: true, isDefinition: true)
!6564 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 360, elements: !6565)
!6565 = !{!6566}
!6566 = !DISubrange(count: 45)
!6567 = !DIGlobalVariableExpression(var: !6568, expr: !DIExpression())
!6568 = distinct !DIGlobalVariable(scope: null, file: !3094, line: 78, type: !6569, isLocal: true, isDefinition: true)
!6569 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 328, elements: !6570)
!6570 = !{!6571}
!6571 = !DISubrange(count: 41)
!6572 = !DIGlobalVariableExpression(var: !6573, expr: !DIExpression())
!6573 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 168, type: !6574, isLocal: true, isDefinition: true)
!6574 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 168, elements: !6575)
!6575 = !{!6576}
!6576 = !DISubrange(count: 21)
!6577 = !DIGlobalVariableExpression(var: !6578, expr: !DIExpression())
!6578 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 168, type: !6579, isLocal: true, isDefinition: true)
!6579 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 24, elements: !5802)
!6580 = !DIGlobalVariableExpression(var: !6581, expr: !DIExpression())
!6581 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 169, type: !6582, isLocal: true, isDefinition: true)
!6582 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 296, elements: !6583)
!6583 = !{!6584}
!6584 = !DISubrange(count: 37)
!6585 = !DIGlobalVariableExpression(var: !6586, expr: !DIExpression())
!6586 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 178, type: !6549, isLocal: true, isDefinition: true)
!6587 = !DIGlobalVariableExpression(var: !6588, expr: !DIExpression())
!6588 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 180, type: !6589, isLocal: true, isDefinition: true)
!6589 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 280, elements: !6590)
!6590 = !{!6591}
!6591 = !DISubrange(count: 35)
!6592 = !DIGlobalVariableExpression(var: !6593, expr: !DIExpression())
!6593 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 186, type: !6594, isLocal: true, isDefinition: true)
!6594 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 152, elements: !6595)
!6595 = !{!6596}
!6596 = !DISubrange(count: 19)
!6597 = !DIGlobalVariableExpression(var: !6598, expr: !DIExpression())
!6598 = distinct !DIGlobalVariable(scope: null, file: !116, line: 67, type: !6582, isLocal: true, isDefinition: true)
!6599 = !DIGlobalVariableExpression(var: !6600, expr: !DIExpression())
!6600 = distinct !DIGlobalVariable(scope: null, file: !116, line: 67, type: !6601, isLocal: true, isDefinition: true)
!6601 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 704, elements: !6602)
!6602 = !{!6603}
!6603 = !DISubrange(count: 88)
!6604 = !DIGlobalVariableExpression(var: !6605, expr: !DIExpression())
!6605 = distinct !DIGlobalVariable(scope: null, file: !116, line: 67, type: !6554, isLocal: true, isDefinition: true)
!6606 = !DIGlobalVariableExpression(var: !6607, expr: !DIExpression())
!6607 = distinct !DIGlobalVariable(scope: null, file: !116, line: 67, type: !6608, isLocal: true, isDefinition: true)
!6608 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 544, elements: !6609)
!6609 = !{!6610}
!6610 = !DISubrange(count: 68)
!6611 = !DIGlobalVariableExpression(var: !6612, expr: !DIExpression())
!6612 = distinct !DIGlobalVariable(scope: null, file: !270, line: 272, type: !6613, isLocal: true, isDefinition: true)
!6613 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 216, elements: !6614)
!6614 = !{!6615}
!6615 = !DISubrange(count: 27)
!6616 = !DIGlobalVariableExpression(var: !6617, expr: !DIExpression())
!6617 = distinct !DIGlobalVariable(scope: null, file: !270, line: 272, type: !6618, isLocal: true, isDefinition: true)
!6618 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 424, elements: !6619)
!6619 = !{!6620}
!6620 = !DISubrange(count: 53)
!6621 = !DIGlobalVariableExpression(var: !6622, expr: !DIExpression())
!6622 = distinct !DIGlobalVariable(scope: null, file: !270, line: 272, type: !6623, isLocal: true, isDefinition: true)
!6623 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 416, elements: !6624)
!6624 = !{!6625}
!6625 = !DISubrange(count: 52)
!6626 = !DIGlobalVariableExpression(var: !6627, expr: !DIExpression())
!6627 = distinct !DIGlobalVariable(scope: null, file: !270, line: 272, type: !6628, isLocal: true, isDefinition: true)
!6628 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 536, elements: !6629)
!6629 = !{!6630}
!6630 = !DISubrange(count: 67)
!6631 = !DIGlobalVariableExpression(var: !6632, expr: !DIExpression())
!6632 = distinct !DIGlobalVariable(scope: null, file: !247, line: 418, type: !6549, isLocal: true, isDefinition: true)
!6633 = !DIGlobalVariableExpression(var: !6634, expr: !DIExpression())
!6634 = distinct !DIGlobalVariable(scope: null, file: !247, line: 418, type: !6529, isLocal: true, isDefinition: true)
!6635 = !DIGlobalVariableExpression(var: !6636, expr: !DIExpression())
!6636 = distinct !DIGlobalVariable(scope: null, file: !247, line: 418, type: !6637, isLocal: true, isDefinition: true)
!6637 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 432, elements: !6638)
!6638 = !{!6639}
!6639 = !DISubrange(count: 54)
!6640 = !DIGlobalVariableExpression(var: !6641, expr: !DIExpression())
!6641 = distinct !DIGlobalVariable(scope: null, file: !247, line: 418, type: !6642, isLocal: true, isDefinition: true)
!6642 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 496, elements: !6643)
!6643 = !{!6644}
!6644 = !DISubrange(count: 62)
!6645 = !DIGlobalVariableExpression(var: !6646, expr: !DIExpression())
!6646 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 37, type: !6613, isLocal: true, isDefinition: true)
!6647 = !DIGlobalVariableExpression(var: !6648, expr: !DIExpression())
!6648 = distinct !DIGlobalVariable(name: "NumTails", linkageName: "_ZL8NumTails", scope: !0, file: !5058, line: 37, type: !6649, isLocal: true, isDefinition: true)
!6649 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Statistic", scope: !14, file: !6650, line: 35, size: 192, flags: DIFlagTypePassByValue, elements: !6651, identifier: "_ZTSN4llvm9StatisticE")
!6650 = !DIFile(filename: "llvm34/include/llvm/ADT/Statistic.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "53ce2a0037e7af9cca48ac8c0c187505")
!6651 = !{!6652, !6653, !6654, !6655, !6656, !6661, !6664, !6665, !6669, !6672, !6676, !6679, !6682, !6683, !6684, !6687, !6688, !6689, !6690, !6694}
!6652 = !DIDerivedType(tag: DW_TAG_member, name: "Name", scope: !6649, file: !6650, line: 37, baseType: !317, size: 64, flags: DIFlagPublic)
!6653 = !DIDerivedType(tag: DW_TAG_member, name: "Desc", scope: !6649, file: !6650, line: 38, baseType: !317, size: 64, offset: 64, flags: DIFlagPublic)
!6654 = !DIDerivedType(tag: DW_TAG_member, name: "Value", scope: !6649, file: !6650, line: 39, baseType: !6491, size: 32, offset: 128, flags: DIFlagPublic)
!6655 = !DIDerivedType(tag: DW_TAG_member, name: "Initialized", scope: !6649, file: !6650, line: 40, baseType: !145, size: 8, offset: 160, flags: DIFlagPublic)
!6656 = !DISubprogram(name: "getValue", linkageName: "_ZNK4llvm9Statistic8getValueEv", scope: !6649, file: !6650, line: 42, type: !6657, scopeLine: 42, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6657 = !DISubroutineType(types: !6658)
!6658 = !{!6485, !6659}
!6659 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6660, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6660 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6649)
!6661 = !DISubprogram(name: "getName", linkageName: "_ZNK4llvm9Statistic7getNameEv", scope: !6649, file: !6650, line: 43, type: !6662, scopeLine: 43, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6662 = !DISubroutineType(types: !6663)
!6663 = !{!317, !6659}
!6664 = !DISubprogram(name: "getDesc", linkageName: "_ZNK4llvm9Statistic7getDescEv", scope: !6649, file: !6650, line: 44, type: !6662, scopeLine: 44, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6665 = !DISubprogram(name: "construct", linkageName: "_ZN4llvm9Statistic9constructEPKcS2_", scope: !6649, file: !6650, line: 47, type: !6666, scopeLine: 47, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6666 = !DISubroutineType(types: !6667)
!6667 = !{null, !6668, !317, !317}
!6668 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6649, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6669 = !DISubprogram(name: "operator unsigned int", linkageName: "_ZNK4llvm9StatisticcvjEv", scope: !6649, file: !6650, line: 53, type: !6670, scopeLine: 53, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6670 = !DISubroutineType(types: !6671)
!6671 = !{!6, !6659}
!6672 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm9StatisticaSEj", scope: !6649, file: !6650, line: 56, type: !6673, scopeLine: 56, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6673 = !DISubroutineType(types: !6674)
!6674 = !{!6675, !6668, !6}
!6675 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6660, size: 64)
!6676 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm9StatisticppEv", scope: !6649, file: !6650, line: 61, type: !6677, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6677 = !DISubroutineType(types: !6678)
!6678 = !{!6675, !6668}
!6679 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm9StatisticppEi", scope: !6649, file: !6650, line: 70, type: !6680, scopeLine: 70, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6680 = !DISubroutineType(types: !6681)
!6681 = !{!6, !6668, !32}
!6682 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm9StatisticmmEv", scope: !6649, file: !6650, line: 77, type: !6677, scopeLine: 77, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6683 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm9StatisticmmEi", scope: !6649, file: !6650, line: 82, type: !6680, scopeLine: 82, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6684 = !DISubprogram(name: "operator+=", linkageName: "_ZN4llvm9StatisticpLERKj", scope: !6649, file: !6650, line: 89, type: !6685, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6685 = !DISubroutineType(types: !6686)
!6686 = !{!6675, !6668, !2065}
!6687 = !DISubprogram(name: "operator-=", linkageName: "_ZN4llvm9StatisticmIERKj", scope: !6649, file: !6650, line: 95, type: !6685, scopeLine: 95, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6688 = !DISubprogram(name: "operator*=", linkageName: "_ZN4llvm9StatisticmLERKj", scope: !6649, file: !6650, line: 101, type: !6685, scopeLine: 101, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6689 = !DISubprogram(name: "operator/=", linkageName: "_ZN4llvm9StatisticdVERKj", scope: !6649, file: !6650, line: 106, type: !6685, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6690 = !DISubprogram(name: "init", linkageName: "_ZN4llvm9Statistic4initEv", scope: !6649, file: !6650, line: 152, type: !6691, scopeLine: 152, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6691 = !DISubroutineType(types: !6692)
!6692 = !{!6693, !6668}
!6693 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6649, size: 64)
!6694 = !DISubprogram(name: "RegisterStatistic", linkageName: "_ZN4llvm9Statistic17RegisterStatisticEv", scope: !6649, file: !6650, line: 159, type: !6695, scopeLine: 159, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6695 = !DISubroutineType(types: !6696)
!6696 = !{null, !6668}
!6697 = !DIGlobalVariableExpression(var: !6698, expr: !DIExpression())
!6698 = distinct !DIGlobalVariable(scope: null, file: !2501, line: 399, type: !6699, isLocal: true, isDefinition: true)
!6699 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 232, elements: !6700)
!6700 = !{!6701}
!6701 = !DISubrange(count: 29)
!6702 = !DIGlobalVariableExpression(var: !6703, expr: !DIExpression())
!6703 = distinct !DIGlobalVariable(scope: null, file: !2501, line: 399, type: !6529, isLocal: true, isDefinition: true)
!6704 = !DIGlobalVariableExpression(var: !6705, expr: !DIExpression())
!6705 = distinct !DIGlobalVariable(scope: null, file: !2501, line: 399, type: !6569, isLocal: true, isDefinition: true)
!6706 = !DIGlobalVariableExpression(var: !6707, expr: !DIExpression())
!6707 = distinct !DIGlobalVariable(scope: null, file: !2501, line: 399, type: !6708, isLocal: true, isDefinition: true)
!6708 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 1152, elements: !6709)
!6709 = !{!6710}
!6710 = !DISubrange(count: 144)
!6711 = !DIGlobalVariableExpression(var: !6712, expr: !DIExpression())
!6712 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 743, type: !6713, isLocal: true, isDefinition: true)
!6713 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 208, elements: !6714)
!6714 = !{!6715}
!6715 = !DISubrange(count: 26)
!6716 = !DIGlobalVariableExpression(var: !6717, expr: !DIExpression())
!6717 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 761, type: !6618, isLocal: true, isDefinition: true)
!6718 = !DIGlobalVariableExpression(var: !6719, expr: !DIExpression())
!6719 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 761, type: !6720, isLocal: true, isDefinition: true)
!6720 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 600, elements: !6721)
!6721 = !{!6722}
!6722 = !DISubrange(count: 75)
!6723 = !DIGlobalVariableExpression(var: !6724, expr: !DIExpression())
!6724 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 761, type: !6725, isLocal: true, isDefinition: true)
!6725 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 1648, elements: !6726)
!6726 = !{!6727}
!6727 = !DISubrange(count: 206)
!6728 = !DIGlobalVariableExpression(var: !6729, expr: !DIExpression())
!6729 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 777, type: !6730, isLocal: true, isDefinition: true)
!6730 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 256, elements: !3562)
!6731 = !DIGlobalVariableExpression(var: !6732, expr: !DIExpression())
!6732 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 777, type: !6733, isLocal: true, isDefinition: true)
!6733 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 96, elements: !6734)
!6734 = !{!6735}
!6735 = !DISubrange(count: 12)
!6736 = !DIGlobalVariableExpression(var: !6737, expr: !DIExpression())
!6737 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 835, type: !6559, isLocal: true, isDefinition: true)
!6738 = !DIGlobalVariableExpression(var: !6739, expr: !DIExpression())
!6739 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 835, type: !6740, isLocal: true, isDefinition: true)
!6740 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 656, elements: !6741)
!6741 = !{!6742}
!6742 = !DISubrange(count: 82)
!6743 = !DIGlobalVariableExpression(var: !6744, expr: !DIExpression())
!6744 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 857, type: !6745, isLocal: true, isDefinition: true)
!6745 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 176, elements: !6746)
!6746 = !{!6747}
!6747 = !DISubrange(count: 22)
!6748 = !DIGlobalVariableExpression(var: !6749, expr: !DIExpression())
!6749 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 857, type: !6750, isLocal: true, isDefinition: true)
!6750 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 88, elements: !6751)
!6751 = !{!6752}
!6752 = !DISubrange(count: 11)
!6753 = !DIGlobalVariableExpression(var: !6754, expr: !DIExpression())
!6754 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 878, type: !6755, isLocal: true, isDefinition: true)
!6755 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 312, elements: !6756)
!6756 = !{!6757}
!6757 = !DISubrange(count: 39)
!6758 = !DIGlobalVariableExpression(var: !6759, expr: !DIExpression())
!6759 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 878, type: !6760, isLocal: true, isDefinition: true)
!6760 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 480, elements: !6761)
!6761 = !{!6762}
!6762 = !DISubrange(count: 60)
!6763 = !DIGlobalVariableExpression(var: !6764, expr: !DIExpression())
!6764 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 894, type: !6574, isLocal: true, isDefinition: true)
!6765 = !DIGlobalVariableExpression(var: !6766, expr: !DIExpression())
!6766 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 271, type: !6767, isLocal: true, isDefinition: true)
!6767 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 2048, elements: !6768)
!6768 = !{!6769}
!6769 = !DISubrange(count: 256)
!6770 = !DIGlobalVariableExpression(var: !6771, expr: !DIExpression())
!6771 = distinct !DIGlobalVariable(scope: null, file: !270, line: 268, type: !6772, isLocal: true, isDefinition: true)
!6772 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 632, elements: !6773)
!6773 = !{!6774}
!6774 = !DISubrange(count: 79)
!6775 = !DIGlobalVariableExpression(var: !6776, expr: !DIExpression())
!6776 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 478, type: !6637, isLocal: true, isDefinition: true)
!6777 = !DIGlobalVariableExpression(var: !6778, expr: !DIExpression())
!6778 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 478, type: !6779, isLocal: true, isDefinition: true)
!6779 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 1072, elements: !6780)
!6780 = !{!6781}
!6781 = !DISubrange(count: 134)
!6782 = !DIGlobalVariableExpression(var: !6783, expr: !DIExpression())
!6783 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 478, type: !6784, isLocal: true, isDefinition: true)
!6784 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 2808, elements: !6785)
!6785 = !{!6786}
!6786 = !DISubrange(count: 351)
!6787 = !DIGlobalVariableExpression(var: !6788, expr: !DIExpression())
!6788 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 445, type: !6789, isLocal: true, isDefinition: true)
!6789 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 80, elements: !6790)
!6790 = !{!6791}
!6791 = !DISubrange(count: 10)
!6792 = !DIGlobalVariableExpression(var: !6793, expr: !DIExpression())
!6793 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 445, type: !6794, isLocal: true, isDefinition: true)
!6794 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 2672, elements: !6795)
!6795 = !{!6796}
!6796 = !DISubrange(count: 334)
!6797 = !DIGlobalVariableExpression(var: !6798, expr: !DIExpression())
!6798 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 623, type: !6799, isLocal: true, isDefinition: true)
!6799 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 64, elements: !183)
!6800 = !DIGlobalVariableExpression(var: !6801, expr: !DIExpression())
!6801 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 623, type: !6802, isLocal: true, isDefinition: true)
!6802 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 1136, elements: !6803)
!6803 = !{!6804}
!6804 = !DISubrange(count: 142)
!6805 = !DIGlobalVariableExpression(var: !6806, expr: !DIExpression())
!6806 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 291, type: !6807, isLocal: true, isDefinition: true)
!6807 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 192, elements: !6808)
!6808 = !{!6809}
!6809 = !DISubrange(count: 24)
!6810 = !DIGlobalVariableExpression(var: !6811, expr: !DIExpression())
!6811 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 291, type: !6755, isLocal: true, isDefinition: true)
!6812 = !DIGlobalVariableExpression(var: !6813, expr: !DIExpression())
!6813 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 291, type: !6814, isLocal: true, isDefinition: true)
!6814 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 2600, elements: !6815)
!6815 = !{!6816}
!6816 = !DISubrange(count: 325)
!6817 = !DIGlobalVariableExpression(var: !6818, expr: !DIExpression())
!6818 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 685, type: !6594, isLocal: true, isDefinition: true)
!6819 = !DIGlobalVariableExpression(var: !6820, expr: !DIExpression())
!6820 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 726, type: !6594, isLocal: true, isDefinition: true)
!6821 = !DIGlobalVariableExpression(var: !6822, expr: !DIExpression())
!6822 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 726, type: !6823, isLocal: true, isDefinition: true)
!6823 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 1688, elements: !6824)
!6824 = !{!6825}
!6825 = !DISubrange(count: 211)
!6826 = !DIGlobalVariableExpression(var: !6827, expr: !DIExpression())
!6827 = distinct !DIGlobalVariable(scope: null, file: !2501, line: 215, type: !6828, isLocal: true, isDefinition: true)
!6828 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 288, elements: !6829)
!6829 = !{!6830}
!6830 = !DISubrange(count: 36)
!6831 = !DIGlobalVariableExpression(var: !6832, expr: !DIExpression())
!6832 = distinct !DIGlobalVariable(scope: null, file: !2501, line: 215, type: !6462, isLocal: true, isDefinition: true)
!6833 = !DIGlobalVariableExpression(var: !6834, expr: !DIExpression())
!6834 = distinct !DIGlobalVariable(scope: null, file: !2501, line: 215, type: !6835, isLocal: true, isDefinition: true)
!6835 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 872, elements: !6836)
!6836 = !{!6837}
!6837 = !DISubrange(count: 109)
!6838 = !DIGlobalVariableExpression(var: !6839, expr: !DIExpression())
!6839 = distinct !DIGlobalVariable(scope: null, file: !636, line: 327, type: !6713, isLocal: true, isDefinition: true)
!6840 = !DIGlobalVariableExpression(var: !6841, expr: !DIExpression())
!6841 = distinct !DIGlobalVariable(scope: null, file: !636, line: 327, type: !6508, isLocal: true, isDefinition: true)
!6842 = !DIGlobalVariableExpression(var: !6843, expr: !DIExpression())
!6843 = distinct !DIGlobalVariable(scope: null, file: !636, line: 327, type: !6564, isLocal: true, isDefinition: true)
!6844 = !DIGlobalVariableExpression(var: !6845, expr: !DIExpression())
!6845 = distinct !DIGlobalVariable(scope: null, file: !636, line: 327, type: !6846, isLocal: true, isDefinition: true)
!6846 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 552, elements: !6847)
!6847 = !{!6848}
!6848 = !DISubrange(count: 69)
!6849 = !DIGlobalVariableExpression(var: !6850, expr: !DIExpression())
!6850 = distinct !DIGlobalVariable(scope: null, file: !6851, line: 423, type: !6713, isLocal: true, isDefinition: true)
!6851 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/vector.tcc", directory: "", checksumkind: CSK_MD5, checksum: "d0546ffb79f08cabb1d395ee56a00a29")
!6852 = !DIGlobalVariableExpression(var: !6853, expr: !DIExpression())
!6853 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 271, type: !6854, isLocal: true, isDefinition: true)
!6854 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 2304, elements: !6855)
!6855 = !{!6856}
!6856 = !DISubrange(count: 288)
!6857 = !DIGlobalVariableExpression(var: !6858, expr: !DIExpression())
!6858 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 392, type: !6828, isLocal: true, isDefinition: true)
!6859 = !DIGlobalVariableExpression(var: !6860, expr: !DIExpression())
!6860 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 392, type: !6452, isLocal: true, isDefinition: true)
!6861 = !DIGlobalVariableExpression(var: !6862, expr: !DIExpression())
!6862 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 392, type: !6863, isLocal: true, isDefinition: true)
!6863 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 2160, elements: !6864)
!6864 = !{!6865}
!6865 = !DISubrange(count: 270)
!6866 = !DIGlobalVariableExpression(var: !6867, expr: !DIExpression())
!6867 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 478, type: !6868, isLocal: true, isDefinition: true)
!6868 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 3064, elements: !6869)
!6869 = !{!6870}
!6870 = !DISubrange(count: 383)
!6871 = !DIGlobalVariableExpression(var: !6872, expr: !DIExpression())
!6872 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 445, type: !6873, isLocal: true, isDefinition: true)
!6873 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 2928, elements: !6874)
!6874 = !{!6875}
!6875 = !DISubrange(count: 366)
!6876 = !DIGlobalVariableExpression(var: !6877, expr: !DIExpression())
!6877 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 623, type: !6878, isLocal: true, isDefinition: true)
!6878 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 1264, elements: !6879)
!6879 = !{!6880}
!6880 = !DISubrange(count: 158)
!6881 = !DIGlobalVariableExpression(var: !6882, expr: !DIExpression())
!6882 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 291, type: !6883, isLocal: true, isDefinition: true)
!6883 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 2856, elements: !6884)
!6884 = !{!6885}
!6885 = !DISubrange(count: 357)
!6886 = !DIGlobalVariableExpression(var: !6887, expr: !DIExpression())
!6887 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 478, type: !6888, isLocal: true, isDefinition: true)
!6888 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 4696, elements: !6889)
!6889 = !{!6890}
!6890 = !DISubrange(count: 587)
!6891 = !DIGlobalVariableExpression(var: !6892, expr: !DIExpression())
!6892 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 445, type: !6893, isLocal: true, isDefinition: true)
!6893 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 4560, elements: !6894)
!6894 = !{!6895}
!6895 = !DISubrange(count: 570)
!6896 = !DIGlobalVariableExpression(var: !6897, expr: !DIExpression())
!6897 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 623, type: !6898, isLocal: true, isDefinition: true)
!6898 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 2080, elements: !6899)
!6899 = !{!6900}
!6900 = !DISubrange(count: 260)
!6901 = !DIGlobalVariableExpression(var: !6902, expr: !DIExpression())
!6902 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 291, type: !6903, isLocal: true, isDefinition: true)
!6903 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 4488, elements: !6904)
!6904 = !{!6905}
!6905 = !DISubrange(count: 561)
!6906 = !DIGlobalVariableExpression(var: !6907, expr: !DIExpression())
!6907 = distinct !DIGlobalVariable(scope: null, file: !405, line: 288, type: !6529, isLocal: true, isDefinition: true)
!6908 = !DIGlobalVariableExpression(var: !6909, expr: !DIExpression())
!6909 = distinct !DIGlobalVariable(scope: null, file: !405, line: 288, type: !6910, isLocal: true, isDefinition: true)
!6910 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 528, elements: !6911)
!6911 = !{!6912}
!6912 = !DISubrange(count: 66)
!6913 = !DIGlobalVariableExpression(var: !6914, expr: !DIExpression())
!6914 = distinct !DIGlobalVariable(scope: null, file: !405, line: 288, type: !6534, isLocal: true, isDefinition: true)
!6915 = !DIGlobalVariableExpression(var: !6916, expr: !DIExpression())
!6916 = distinct !DIGlobalVariable(scope: null, file: !405, line: 288, type: !6917, isLocal: true, isDefinition: true)
!6917 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 560, elements: !6918)
!6918 = !{!6919}
!6919 = !DISubrange(count: 70)
!6920 = !DIGlobalVariableExpression(var: !6921, expr: !DIExpression())
!6921 = distinct !DIGlobalVariable(scope: null, file: !247, line: 275, type: !6529, isLocal: true, isDefinition: true)
!6922 = !DIGlobalVariableExpression(var: !6923, expr: !DIExpression())
!6923 = distinct !DIGlobalVariable(scope: null, file: !247, line: 275, type: !6569, isLocal: true, isDefinition: true)
!6924 = !DIGlobalVariableExpression(var: !6925, expr: !DIExpression())
!6925 = distinct !DIGlobalVariable(scope: null, file: !199, line: 468, type: !6518, isLocal: true, isDefinition: true)
!6926 = !DIGlobalVariableExpression(var: !6927, expr: !DIExpression())
!6927 = distinct !DIGlobalVariable(scope: null, file: !199, line: 468, type: !6928, isLocal: true, isDefinition: true)
!6928 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 816, elements: !6929)
!6929 = !{!6930}
!6930 = !DISubrange(count: 102)
!6931 = !DIGlobalVariableExpression(var: !6932, expr: !DIExpression())
!6932 = distinct !DIGlobalVariable(scope: null, file: !199, line: 468, type: !6534, isLocal: true, isDefinition: true)
!6933 = !DIGlobalVariableExpression(var: !6934, expr: !DIExpression())
!6934 = distinct !DIGlobalVariable(scope: null, file: !199, line: 468, type: !6935, isLocal: true, isDefinition: true)
!6935 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 984, elements: !6936)
!6936 = !{!6937}
!6937 = !DISubrange(count: 123)
!6938 = !DIGlobalVariableExpression(var: !6939, expr: !DIExpression())
!6939 = distinct !DIGlobalVariable(scope: null, file: !6940, line: 49, type: !6459, isLocal: true, isDefinition: true)
!6940 = !DIFile(filename: "llvm34/include/llvm/MC/MCInstrInfo.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "9bd9d1052f8abc66aa37b97fa81ac10f")
!6941 = !DIGlobalVariableExpression(var: !6942, expr: !DIExpression())
!6942 = distinct !DIGlobalVariable(scope: null, file: !6940, line: 49, type: !6569, isLocal: true, isDefinition: true)
!6943 = !DIGlobalVariableExpression(var: !6944, expr: !DIExpression())
!6944 = distinct !DIGlobalVariable(scope: null, file: !6940, line: 49, type: !6945, isLocal: true, isDefinition: true)
!6945 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 368, elements: !6946)
!6946 = !{!6947}
!6947 = !DISubrange(count: 46)
!6948 = !DIGlobalVariableExpression(var: !6949, expr: !DIExpression())
!6949 = distinct !DIGlobalVariable(scope: null, file: !6940, line: 49, type: !6608, isLocal: true, isDefinition: true)
!6950 = !DIGlobalVariableExpression(var: !6951, expr: !DIExpression())
!6951 = distinct !DIGlobalVariable(scope: null, file: !2317, line: 140, type: !6745, isLocal: true, isDefinition: true)
!6952 = !DIGlobalVariableExpression(var: !6953, expr: !DIExpression())
!6953 = distinct !DIGlobalVariable(scope: null, file: !2317, line: 140, type: !6554, isLocal: true, isDefinition: true)
!6954 = !DIGlobalVariableExpression(var: !6955, expr: !DIExpression())
!6955 = distinct !DIGlobalVariable(scope: null, file: !2317, line: 140, type: !6956, isLocal: true, isDefinition: true)
!6956 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 1472, elements: !6957)
!6957 = !{!6958}
!6958 = !DISubrange(count: 184)
!6959 = !DIGlobalVariableExpression(var: !6960, expr: !DIExpression())
!6960 = distinct !DIGlobalVariable(scope: null, file: !771, line: 66, type: !6961, isLocal: true, isDefinition: true)
!6961 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 488, elements: !6962)
!6962 = !{!6963}
!6963 = !DISubrange(count: 61)
!6964 = !DIGlobalVariableExpression(var: !6965, expr: !DIExpression())
!6965 = distinct !DIGlobalVariable(scope: null, file: !771, line: 66, type: !6966, isLocal: true, isDefinition: true)
!6966 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 680, elements: !6967)
!6967 = !{!6968}
!6968 = !DISubrange(count: 85)
!6969 = !DIGlobalVariableExpression(var: !6970, expr: !DIExpression())
!6970 = distinct !DIGlobalVariable(scope: null, file: !771, line: 66, type: !6971, isLocal: true, isDefinition: true)
!6971 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 472, elements: !6972)
!6972 = !{!6973}
!6973 = !DISubrange(count: 59)
!6974 = !DIGlobalVariableExpression(var: !6975, expr: !DIExpression())
!6975 = distinct !DIGlobalVariable(scope: null, file: !771, line: 66, type: !6976, isLocal: true, isDefinition: true)
!6976 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 920, elements: !6977)
!6977 = !{!6978}
!6978 = !DISubrange(count: 115)
!6979 = !DIGlobalVariableExpression(var: !6980, expr: !DIExpression())
!6980 = distinct !DIGlobalVariable(scope: null, file: !247, line: 567, type: !6574, isLocal: true, isDefinition: true)
!6981 = !DIGlobalVariableExpression(var: !6982, expr: !DIExpression())
!6982 = distinct !DIGlobalVariable(scope: null, file: !247, line: 567, type: !6945, isLocal: true, isDefinition: true)
!6983 = !DIGlobalVariableExpression(var: !6984, expr: !DIExpression())
!6984 = distinct !DIGlobalVariable(scope: null, file: !247, line: 567, type: !6985, isLocal: true, isDefinition: true)
!6985 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 1088, elements: !6986)
!6986 = !{!6987}
!6987 = !DISubrange(count: 136)
!6988 = !DIGlobalVariableExpression(var: !6989, expr: !DIExpression())
!6989 = distinct !DIGlobalVariable(scope: null, file: !247, line: 568, type: !6501, isLocal: true, isDefinition: true)
!6990 = !DIGlobalVariableExpression(var: !6991, expr: !DIExpression())
!6991 = distinct !DIGlobalVariable(scope: null, file: !247, line: 568, type: !6569, isLocal: true, isDefinition: true)
!6992 = !DIGlobalVariableExpression(var: !6993, expr: !DIExpression())
!6993 = distinct !DIGlobalVariable(scope: null, file: !247, line: 340, type: !6539, isLocal: true, isDefinition: true)
!6994 = !DIGlobalVariableExpression(var: !6995, expr: !DIExpression())
!6995 = distinct !DIGlobalVariable(scope: null, file: !247, line: 342, type: !6996, isLocal: true, isDefinition: true)
!6996 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 160, elements: !6997)
!6997 = !{!6998}
!6998 = !DISubrange(count: 20)
!6999 = !DIGlobalVariableExpression(var: !7000, expr: !DIExpression())
!7000 = distinct !DIGlobalVariable(scope: null, file: !247, line: 342, type: !6637, isLocal: true, isDefinition: true)
!7001 = !DIGlobalVariableExpression(var: !7002, expr: !DIExpression())
!7002 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 38, type: !7003, isLocal: true, isDefinition: true)
!7003 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 264, elements: !7004)
!7004 = !{!7005}
!7005 = !DISubrange(count: 33)
!7006 = !DIGlobalVariableExpression(var: !7007, expr: !DIExpression())
!7007 = distinct !DIGlobalVariable(name: "NumTailDups", linkageName: "_ZL11NumTailDups", scope: !0, file: !5058, line: 38, type: !6649, isLocal: true, isDefinition: true)
!7008 = !DIGlobalVariableExpression(var: !7009, expr: !DIExpression())
!7009 = distinct !DIGlobalVariable(scope: null, file: !2501, line: 215, type: !7010, isLocal: true, isDefinition: true)
!7010 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 952, elements: !7011)
!7011 = !{!7012}
!7012 = !DISubrange(count: 119)
!7013 = !DIGlobalVariableExpression(var: !7014, expr: !DIExpression())
!7014 = distinct !DIGlobalVariable(scope: null, file: !2501, line: 487, type: !6699, isLocal: true, isDefinition: true)
!7015 = !DIGlobalVariableExpression(var: !7016, expr: !DIExpression())
!7016 = distinct !DIGlobalVariable(scope: null, file: !2501, line: 487, type: !6494, isLocal: true, isDefinition: true)
!7017 = !DIGlobalVariableExpression(var: !7018, expr: !DIExpression())
!7018 = distinct !DIGlobalVariable(scope: null, file: !2501, line: 487, type: !7019, isLocal: true, isDefinition: true)
!7019 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 1800, elements: !7020)
!7020 = !{!7021}
!7021 = !DISubrange(count: 225)
!7022 = !DIGlobalVariableExpression(var: !7023, expr: !DIExpression())
!7023 = distinct !DIGlobalVariable(scope: null, file: !2501, line: 490, type: !6637, isLocal: true, isDefinition: true)
!7024 = !DIGlobalVariableExpression(var: !7025, expr: !DIExpression())
!7025 = distinct !DIGlobalVariable(scope: null, file: !2501, line: 490, type: !7026, isLocal: true, isDefinition: true)
!7026 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 616, elements: !7027)
!7027 = !{!7028}
!7028 = !DISubrange(count: 77)
!7029 = !DIGlobalVariableExpression(var: !7030, expr: !DIExpression())
!7030 = distinct !DIGlobalVariable(scope: null, file: !6650, line: 156, type: !6564, isLocal: true, isDefinition: true)
!7031 = !DIGlobalVariableExpression(var: !7032, expr: !DIExpression())
!7032 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 472, type: !7033, isLocal: true, isDefinition: true)
!7033 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 72, elements: !7034)
!7034 = !{!7035}
!7035 = !DISubrange(count: 9)
!7036 = !DIGlobalVariableExpression(var: !7037, expr: !DIExpression())
!7037 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 472, type: !7038, isLocal: true, isDefinition: true)
!7038 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 1560, elements: !7039)
!7039 = !{!7040}
!7040 = !DISubrange(count: 195)
!7041 = !DIGlobalVariableExpression(var: !7042, expr: !DIExpression())
!7042 = distinct !DIGlobalVariable(scope: null, file: !247, line: 507, type: !6961, isLocal: true, isDefinition: true)
!7043 = !DIGlobalVariableExpression(var: !7044, expr: !DIExpression())
!7044 = distinct !DIGlobalVariable(scope: null, file: !247, line: 191, type: !6508, isLocal: true, isDefinition: true)
!7045 = !DIGlobalVariableExpression(var: !7046, expr: !DIExpression())
!7046 = distinct !DIGlobalVariable(scope: null, file: !247, line: 191, type: !6559, isLocal: true, isDefinition: true)
!7047 = !DIGlobalVariableExpression(var: !7048, expr: !DIExpression())
!7048 = distinct !DIGlobalVariable(scope: null, file: !247, line: 191, type: !6559, isLocal: true, isDefinition: true)
!7049 = !DIGlobalVariableExpression(var: !7050, expr: !DIExpression())
!7050 = distinct !DIGlobalVariable(scope: null, file: !247, line: 193, type: !6713, isLocal: true, isDefinition: true)
!7051 = !DIGlobalVariableExpression(var: !7052, expr: !DIExpression())
!7052 = distinct !DIGlobalVariable(scope: null, file: !247, line: 193, type: !7053, isLocal: true, isDefinition: true)
!7053 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 440, elements: !7054)
!7054 = !{!7055}
!7055 = !DISubrange(count: 55)
!7056 = !DIGlobalVariableExpression(var: !7057, expr: !DIExpression())
!7057 = distinct !DIGlobalVariable(scope: null, file: !2317, line: 140, type: !7058, isLocal: true, isDefinition: true)
!7058 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 1280, elements: !7059)
!7059 = !{!7060}
!7060 = !DISubrange(count: 160)
!7061 = !DIGlobalVariableExpression(var: !7062, expr: !DIExpression())
!7062 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 39, type: !6494, isLocal: true, isDefinition: true)
!7063 = !DIGlobalVariableExpression(var: !7064, expr: !DIExpression())
!7064 = distinct !DIGlobalVariable(name: "NumInstrDups", linkageName: "_ZL12NumInstrDups", scope: !0, file: !5058, line: 39, type: !6649, isLocal: true, isDefinition: true)
!7065 = !DIGlobalVariableExpression(var: !7066, expr: !DIExpression())
!7066 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 957, type: !7067, isLocal: true, isDefinition: true)
!7067 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 144, elements: !7068)
!7068 = !{!7069}
!7069 = !DISubrange(count: 18)
!7070 = !DIGlobalVariableExpression(var: !7071, expr: !DIExpression())
!7071 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 957, type: !6569, isLocal: true, isDefinition: true)
!7072 = !DIGlobalVariableExpression(var: !7073, expr: !DIExpression())
!7073 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 957, type: !7074, isLocal: true, isDefinition: true)
!7074 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 720, elements: !7075)
!7075 = !{!7076}
!7076 = !DISubrange(count: 90)
!7077 = !DIGlobalVariableExpression(var: !7078, expr: !DIExpression())
!7078 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 958, type: !6459, isLocal: true, isDefinition: true)
!7079 = !DIGlobalVariableExpression(var: !7080, expr: !DIExpression())
!7080 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 40, type: !6549, isLocal: true, isDefinition: true)
!7081 = !DIGlobalVariableExpression(var: !7082, expr: !DIExpression())
!7082 = distinct !DIGlobalVariable(name: "NumDeadBlocks", linkageName: "_ZL13NumDeadBlocks", scope: !0, file: !5058, line: 40, type: !6649, isLocal: true, isDefinition: true)
!7083 = !DIGlobalVariableExpression(var: !7084, expr: !DIExpression())
!7084 = distinct !DIGlobalVariable(scope: null, file: !2317, line: 140, type: !6779, isLocal: true, isDefinition: true)
!7085 = !DIGlobalVariableExpression(var: !7086, expr: !DIExpression())
!7086 = distinct !DIGlobalVariable(scope: null, file: !7087, line: 49, type: !6574, isLocal: true, isDefinition: true)
!7087 = !DIFile(filename: "llvm34/include/llvm/ADT/IndexedMap.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "694ed884e913842cf962e2491fed713e")
!7088 = !DIGlobalVariableExpression(var: !7089, expr: !DIExpression())
!7089 = distinct !DIGlobalVariable(scope: null, file: !7087, line: 49, type: !6559, isLocal: true, isDefinition: true)
!7090 = !DIGlobalVariableExpression(var: !7091, expr: !DIExpression())
!7091 = distinct !DIGlobalVariable(scope: null, file: !7087, line: 49, type: !6945, isLocal: true, isDefinition: true)
!7092 = !DIGlobalVariableExpression(var: !7093, expr: !DIExpression())
!7093 = distinct !DIGlobalVariable(scope: null, file: !7087, line: 49, type: !7094, isLocal: true, isDefinition: true)
!7094 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 2464, elements: !7095)
!7095 = !{!7096}
!7096 = !DISubrange(count: 308)
!7097 = !DIGlobalVariableExpression(var: !7098, expr: !DIExpression())
!7098 = distinct !DIGlobalVariable(scope: null, file: !405, line: 295, type: !7099, isLocal: true, isDefinition: true)
!7099 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 184, elements: !7100)
!7100 = !{!7101}
!7101 = !DISubrange(count: 23)
!7102 = !DIGlobalVariableExpression(var: !7103, expr: !DIExpression())
!7103 = distinct !DIGlobalVariable(scope: null, file: !405, line: 295, type: !6539, isLocal: true, isDefinition: true)
!7104 = !DIGlobalVariableExpression(var: !7105, expr: !DIExpression())
!7105 = distinct !DIGlobalVariable(scope: null, file: !405, line: 295, type: !7106, isLocal: true, isDefinition: true)
!7106 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 592, elements: !7107)
!7107 = !{!7108}
!7108 = !DISubrange(count: 74)
!7109 = !DIGlobalVariableExpression(var: !7110, expr: !DIExpression())
!7110 = distinct !DIGlobalVariable(scope: null, file: !2477, line: 635, type: !7003, isLocal: true, isDefinition: true)
!7111 = !DIGlobalVariableExpression(var: !7112, expr: !DIExpression())
!7112 = distinct !DIGlobalVariable(scope: null, file: !2477, line: 635, type: !6569, isLocal: true, isDefinition: true)
!7113 = !DIGlobalVariableExpression(var: !7114, expr: !DIExpression())
!7114 = distinct !DIGlobalVariable(scope: null, file: !2477, line: 635, type: !6971, isLocal: true, isDefinition: true)
!7115 = !DIGlobalVariableExpression(var: !7116, expr: !DIExpression())
!7116 = distinct !DIGlobalVariable(scope: null, file: !2477, line: 635, type: !7117, isLocal: true, isDefinition: true)
!7117 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 880, elements: !7118)
!7118 = !{!7119}
!7119 = !DISubrange(count: 110)
!7120 = !DIGlobalVariableExpression(var: !7121, expr: !DIExpression())
!7121 = distinct !DIGlobalVariable(scope: null, file: !2477, line: 648, type: !7122, isLocal: true, isDefinition: true)
!7122 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 856, elements: !7123)
!7123 = !{!7124}
!7124 = !DISubrange(count: 107)
!7125 = !DIGlobalVariableExpression(var: !7126, expr: !DIExpression())
!7126 = distinct !DIGlobalVariable(scope: null, file: !2477, line: 591, type: !7127, isLocal: true, isDefinition: true)
!7127 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 248, elements: !7128)
!7128 = !{!7129}
!7129 = !DISubrange(count: 31)
!7130 = !DIGlobalVariableExpression(var: !7131, expr: !DIExpression())
!7131 = distinct !DIGlobalVariable(scope: null, file: !2477, line: 591, type: !6755, isLocal: true, isDefinition: true)
!7132 = !DIGlobalVariableExpression(var: !7133, expr: !DIExpression())
!7133 = distinct !DIGlobalVariable(scope: null, file: !2477, line: 591, type: !7134, isLocal: true, isDefinition: true)
!7134 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 1016, elements: !7135)
!7135 = !{!7136}
!7136 = !DISubrange(count: 127)
!7137 = !DIGlobalVariableExpression(var: !7138, expr: !DIExpression())
!7138 = distinct !DIGlobalVariable(scope: null, file: !2477, line: 89, type: !6730, isLocal: true, isDefinition: true)
!7139 = !DIGlobalVariableExpression(var: !7140, expr: !DIExpression())
!7140 = distinct !DIGlobalVariable(scope: null, file: !2477, line: 89, type: !7053, isLocal: true, isDefinition: true)
!7141 = !DIGlobalVariableExpression(var: !7142, expr: !DIExpression())
!7142 = distinct !DIGlobalVariable(scope: null, file: !2477, line: 89, type: !7122, isLocal: true, isDefinition: true)
!7143 = !DIGlobalVariableExpression(var: !7144, expr: !DIExpression())
!7144 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 98, type: !6745, isLocal: true, isDefinition: true)
!7145 = !DIGlobalVariableExpression(var: !7146, expr: !DIExpression())
!7146 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 98, type: !6494, isLocal: true, isDefinition: true)
!7147 = !DIGlobalVariableExpression(var: !7148, expr: !DIExpression())
!7148 = distinct !DIGlobalVariable(scope: null, file: !1363, line: 98, type: !7149, isLocal: true, isDefinition: true)
!7149 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 3904, elements: !7150)
!7150 = !{!7151}
!7151 = !DISubrange(count: 488)
!7152 = !DIGlobalVariableExpression(var: !7153, expr: !DIExpression())
!7153 = distinct !DIGlobalVariable(scope: null, file: !2317, line: 140, type: !7154, isLocal: true, isDefinition: true)
!7154 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 1200, elements: !7155)
!7155 = !{!7156}
!7156 = !DISubrange(count: 150)
!7157 = !DIGlobalVariableExpression(var: !7158, expr: !DIExpression())
!7158 = distinct !DIGlobalVariable(scope: null, file: !247, line: 260, type: !6564, isLocal: true, isDefinition: true)
!7159 = !DIGlobalVariableExpression(var: !7160, expr: !DIExpression())
!7160 = distinct !DIGlobalVariable(scope: null, file: !247, line: 260, type: !6452, isLocal: true, isDefinition: true)
!7161 = !DIGlobalVariableExpression(var: !7162, expr: !DIExpression())
!7162 = distinct !DIGlobalVariable(scope: null, file: !5058, line: 41, type: !6574, isLocal: true, isDefinition: true)
!7163 = !DIGlobalVariableExpression(var: !7164, expr: !DIExpression())
!7164 = distinct !DIGlobalVariable(name: "NumAddedPHIs", linkageName: "_ZL12NumAddedPHIs", scope: !0, file: !5058, line: 41, type: !6649, isLocal: true, isDefinition: true)
!7165 = !DIGlobalVariableExpression(var: !7166, expr: !DIExpression())
!7166 = distinct !DIGlobalVariable(scope: null, file: !12, line: 243, type: !7167, isLocal: true, isDefinition: true)
!7167 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 8, elements: !2696)
!7168 = !DIGlobalVariableExpression(var: !7169, expr: !DIExpression())
!7169 = distinct !DIGlobalVariable(scope: null, file: !12, line: 391, type: !6574, isLocal: true, isDefinition: true)
!7170 = !DIGlobalVariableExpression(var: !7171, expr: !DIExpression())
!7171 = distinct !DIGlobalVariable(scope: null, file: !12, line: 391, type: !6730, isLocal: true, isDefinition: true)
!7172 = !DIGlobalVariableExpression(var: !7173, expr: !DIExpression())
!7173 = distinct !DIGlobalVariable(scope: null, file: !12, line: 391, type: !6539, isLocal: true, isDefinition: true)
!7174 = !DIGlobalVariableExpression(var: !7175, expr: !DIExpression())
!7175 = distinct !DIGlobalVariable(scope: null, file: !12, line: 391, type: !7176, isLocal: true, isDefinition: true)
!7176 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 800, elements: !7177)
!7177 = !{!7178}
!7178 = !DISubrange(count: 100)
!7179 = !DIGlobalVariableExpression(var: !7180, expr: !DIExpression())
!7180 = distinct !DIGlobalVariable(scope: null, file: !12, line: 391, type: !7181, isLocal: true, isDefinition: true)
!7181 = !DICompositeType(tag: DW_TAG_array_type, baseType: !318, size: 672, elements: !7182)
!7182 = !{!7183}
!7183 = !DISubrange(count: 84)
!7184 = !{!7185, !7189, !7203, !7206, !7211, !7259, !7267, !7271, !7278, !7282, !7286, !7288, !7290, !7294, !7301, !7305, !7311, !7317, !7319, !7323, !7327, !7331, !7335, !7347, !7349, !7353, !7357, !7361, !7363, !7368, !7372, !7376, !7378, !7380, !7384, !7392, !7396, !7400, !7404, !7406, !7412, !7414, !7421, !7426, !7430, !7434, !7438, !7442, !7446, !7448, !7450, !7454, !7458, !7462, !7464, !7468, !7472, !7474, !7476, !7480, !7485, !7490, !7495, !7496, !7497, !7498, !7499, !7500, !7501, !7502, !7503, !7504, !7505, !7507, !7511, !7514, !7515, !7518, !7520, !7522, !7524, !7526, !7528, !7530, !7532, !7535, !7537, !7538, !7539, !7540, !7543, !7545, !7547, !7549, !7551, !7553, !7555, !7557, !7559, !7562, !7564, !7568, !7572, !7573, !7574, !7578, !7582, !7587, !7593, !7595, !7597, !7599, !7601, !7603, !7605, !7607, !7609, !7611, !7613, !7615, !7617, !7619, !7623, !7627, !7633, !7637, !7642, !7644, !7649, !7653, !7657, !7666, !7670, !7674, !7678, !7682, !7686, !7690, !7694, !7698, !7702, !7706, !7710, !7714, !7716, !7720, !7724, !7728, !7734, !7738, !7742, !7744, !7748, !7752, !7758, !7760, !7764, !7768, !7772, !7776, !7780, !7784, !7788, !7789, !7790, !7791, !7793, !7794, !7795, !7796, !7797, !7798, !7799, !7803, !7809, !7814, !7818, !7820, !7822, !7824, !7826, !7833, !7837, !7841, !7845, !7849, !7853, !7858, !7862, !7864, !7868, !7874, !7878, !7883, !7885, !7888, !7892, !7896, !7898, !7900, !7902, !7904, !7908, !7910, !7912, !7916, !7920, !7924, !7928, !7932, !7936, !7938, !7942, !7946, !7950, !7954, !7956, !7958, !7962, !7966, !7967, !7968, !7969, !7970, !7971, !7977, !7979, !7981, !7985, !7987, !7989, !7991, !7993, !7995, !7997, !7999, !8004, !8008, !8010, !8012, !8017, !8019, !8021, !8023, !8025, !8027, !8029, !8032, !8034, !8036, !8040, !8044, !8046, !8048, !8050, !8052, !8054, !8056, !8058, !8060, !8062, !8064, !8068, !8072, !8074, !8076, !8078, !8080, !8082, !8084, !8086, !8088, !8090, !8092, !8094, !8096, !8098, !8100, !8102, !8106, !8110, !8114, !8116, !8118, !8120, !8122, !8124, !8126, !8128, !8130, !8132, !8136, !8140, !8144, !8146, !8148, !8150, !8154, !8158, !8162, !8164, !8166, !8168, !8170, !8172, !8174, !8176, !8178, !8180, !8182, !8184, !8186, !8190, !8194, !8198, !8200, !8202, !8204, !8206, !8210, !8214, !8216, !8218, !8220, !8222, !8224, !8226, !8230, !8234, !8236, !8238, !8240, !8242, !8246, !8250, !8254, !8256, !8258, !8260, !8262, !8264, !8266, !8270, !8274, !8278, !8280, !8284, !8288, !8290, !8292, !8294, !8296, !8298, !8300, !8305, !8311, !8315, !8319, !8323, !8327, !8331, !8333, !8335, !8337, !8341, !8345, !8349, !8353, !8355, !8357, !8359, !8361, !8365, !8369, !8373, !8375, !8377, !8383, !8386, !8387, !8389, !8391, !8393, !8395, !8399, !8401, !8403, !8405, !8407, !8409, !8411, !8413, !8415, !8419, !8423, !8425, !8429, !8433, !8435, !8438, !8441, !8443, !8448, !8452, !8453, !8458, !8462, !8467, !8472, !8476, !8482, !8486, !8488, !8492, !8499}
!7185 = !DIImportedEntity(tag: DW_TAG_imported_module, scope: !7186, entity: !7187, file: !7188, line: 58)
!7186 = !DINamespace(name: "__gnu_debug", scope: null)
!7187 = !DINamespace(name: "__debug", scope: !839)
!7188 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/debug/debug.h", directory: "", checksumkind: CSK_MD5, checksum: "0d648599b52b1d377b1fee4a0a4b2b91")
!7189 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7190, file: !7202, line: 64)
!7190 = !DIDerivedType(tag: DW_TAG_typedef, name: "mbstate_t", file: !7191, line: 6, baseType: !7192)
!7191 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/mbstate_t.h", directory: "", checksumkind: CSK_MD5, checksum: "ba8742313715e20e434cf6ccb2db98e3")
!7192 = !DIDerivedType(tag: DW_TAG_typedef, name: "__mbstate_t", file: !7193, line: 21, baseType: !7194)
!7193 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h", directory: "", checksumkind: CSK_MD5, checksum: "82911a3e689448e3691ded3e0b471a55")
!7194 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !7193, line: 13, size: 64, flags: DIFlagTypePassByValue, elements: !7195, identifier: "_ZTS11__mbstate_t")
!7195 = !{!7196, !7197}
!7196 = !DIDerivedType(tag: DW_TAG_member, name: "__count", scope: !7194, file: !7193, line: 15, baseType: !32, size: 32)
!7197 = !DIDerivedType(tag: DW_TAG_member, name: "__value", scope: !7194, file: !7193, line: 20, baseType: !7198, size: 32, offset: 32)
!7198 = distinct !DICompositeType(tag: DW_TAG_union_type, scope: !7194, file: !7193, line: 16, size: 32, flags: DIFlagTypePassByValue, elements: !7199, identifier: "_ZTSN11__mbstate_tUt_E")
!7199 = !{!7200, !7201}
!7200 = !DIDerivedType(tag: DW_TAG_member, name: "__wch", scope: !7198, file: !7193, line: 18, baseType: !6, size: 32)
!7201 = !DIDerivedType(tag: DW_TAG_member, name: "__wchb", scope: !7198, file: !7193, line: 19, baseType: !2351, size: 32)
!7202 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cwchar", directory: "")
!7203 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7204, file: !7202, line: 139)
!7204 = !DIDerivedType(tag: DW_TAG_typedef, name: "wint_t", file: !7205, line: 20, baseType: !6)
!7205 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/wint_t.h", directory: "", checksumkind: CSK_MD5, checksum: "aa31b53ef28dc23152ceb41e2763ded3")
!7206 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7207, file: !7202, line: 141)
!7207 = !DISubprogram(name: "btowc", scope: !7208, file: !7208, line: 318, type: !7209, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7208 = !DIFile(filename: "/usr/include/wchar.h", directory: "", checksumkind: CSK_MD5, checksum: "5c0512b032e303d7adfb2a47454ecb1c")
!7209 = !DISubroutineType(types: !7210)
!7210 = !{!7204, !32}
!7211 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7212, file: !7202, line: 142)
!7212 = !DISubprogram(name: "fgetwc", scope: !7208, file: !7208, line: 727, type: !7213, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7213 = !DISubroutineType(types: !7214)
!7214 = !{!7204, !7215}
!7215 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7216, size: 64)
!7216 = !DIDerivedType(tag: DW_TAG_typedef, name: "__FILE", file: !7217, line: 5, baseType: !7218)
!7217 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h", directory: "", checksumkind: CSK_MD5, checksum: "72a8fe90981f484acae7c6f3dfc5c2b7")
!7218 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_IO_FILE", file: !7219, line: 245, size: 1728, flags: DIFlagTypePassByValue, elements: !7220, identifier: "_ZTS8_IO_FILE")
!7219 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/libio.h", directory: "", checksumkind: CSK_MD5, checksum: "e2b53e448ab24b9cd2ba8684267b8131")
!7220 = !{!7221, !7222, !7223, !7224, !7225, !7226, !7227, !7228, !7229, !7230, !7231, !7232, !7233, !7236, !7238, !7239, !7240, !7242, !7243, !7244, !7246, !7249, !7251, !7252, !7253, !7254, !7255, !7256, !7257}
!7221 = !DIDerivedType(tag: DW_TAG_member, name: "_flags", scope: !7218, file: !7219, line: 246, baseType: !32, size: 32)
!7222 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_ptr", scope: !7218, file: !7219, line: 251, baseType: !1360, size: 64, offset: 64)
!7223 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_end", scope: !7218, file: !7219, line: 252, baseType: !1360, size: 64, offset: 128)
!7224 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_base", scope: !7218, file: !7219, line: 253, baseType: !1360, size: 64, offset: 192)
!7225 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_base", scope: !7218, file: !7219, line: 254, baseType: !1360, size: 64, offset: 256)
!7226 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_ptr", scope: !7218, file: !7219, line: 255, baseType: !1360, size: 64, offset: 320)
!7227 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_end", scope: !7218, file: !7219, line: 256, baseType: !1360, size: 64, offset: 384)
!7228 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_buf_base", scope: !7218, file: !7219, line: 257, baseType: !1360, size: 64, offset: 448)
!7229 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_buf_end", scope: !7218, file: !7219, line: 258, baseType: !1360, size: 64, offset: 512)
!7230 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_save_base", scope: !7218, file: !7219, line: 260, baseType: !1360, size: 64, offset: 576)
!7231 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_backup_base", scope: !7218, file: !7219, line: 261, baseType: !1360, size: 64, offset: 640)
!7232 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_save_end", scope: !7218, file: !7219, line: 262, baseType: !1360, size: 64, offset: 704)
!7233 = !DIDerivedType(tag: DW_TAG_member, name: "_markers", scope: !7218, file: !7219, line: 264, baseType: !7234, size: 64, offset: 768)
!7234 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7235, size: 64)
!7235 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_IO_marker", file: !7219, line: 160, size: 192, flags: DIFlagFwdDecl, identifier: "_ZTS10_IO_marker")
!7236 = !DIDerivedType(tag: DW_TAG_member, name: "_chain", scope: !7218, file: !7219, line: 266, baseType: !7237, size: 64, offset: 832)
!7237 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7218, size: 64)
!7238 = !DIDerivedType(tag: DW_TAG_member, name: "_fileno", scope: !7218, file: !7219, line: 268, baseType: !32, size: 32, offset: 896)
!7239 = !DIDerivedType(tag: DW_TAG_member, name: "_flags2", scope: !7218, file: !7219, line: 272, baseType: !32, size: 32, offset: 928)
!7240 = !DIDerivedType(tag: DW_TAG_member, name: "_old_offset", scope: !7218, file: !7219, line: 274, baseType: !7241, size: 64, offset: 960)
!7241 = !DIDerivedType(tag: DW_TAG_typedef, name: "__off_t", file: !287, line: 140, baseType: !288)
!7242 = !DIDerivedType(tag: DW_TAG_member, name: "_cur_column", scope: !7218, file: !7219, line: 278, baseType: !2771, size: 16, offset: 1024)
!7243 = !DIDerivedType(tag: DW_TAG_member, name: "_vtable_offset", scope: !7218, file: !7219, line: 279, baseType: !2788, size: 8, offset: 1040)
!7244 = !DIDerivedType(tag: DW_TAG_member, name: "_shortbuf", scope: !7218, file: !7219, line: 280, baseType: !7245, size: 8, offset: 1048)
!7245 = !DICompositeType(tag: DW_TAG_array_type, baseType: !319, size: 8, elements: !2696)
!7246 = !DIDerivedType(tag: DW_TAG_member, name: "_lock", scope: !7218, file: !7219, line: 284, baseType: !7247, size: 64, offset: 1088)
!7247 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7248, size: 64)
!7248 = !DIDerivedType(tag: DW_TAG_typedef, name: "_IO_lock_t", file: !7219, line: 154, baseType: null)
!7249 = !DIDerivedType(tag: DW_TAG_member, name: "_offset", scope: !7218, file: !7219, line: 293, baseType: !7250, size: 64, offset: 1152)
!7250 = !DIDerivedType(tag: DW_TAG_typedef, name: "__off64_t", file: !287, line: 141, baseType: !288)
!7251 = !DIDerivedType(tag: DW_TAG_member, name: "__pad1", scope: !7218, file: !7219, line: 301, baseType: !154, size: 64, offset: 1216)
!7252 = !DIDerivedType(tag: DW_TAG_member, name: "__pad2", scope: !7218, file: !7219, line: 302, baseType: !154, size: 64, offset: 1280)
!7253 = !DIDerivedType(tag: DW_TAG_member, name: "__pad3", scope: !7218, file: !7219, line: 303, baseType: !154, size: 64, offset: 1344)
!7254 = !DIDerivedType(tag: DW_TAG_member, name: "__pad4", scope: !7218, file: !7219, line: 304, baseType: !154, size: 64, offset: 1408)
!7255 = !DIDerivedType(tag: DW_TAG_member, name: "__pad5", scope: !7218, file: !7219, line: 306, baseType: !2102, size: 64, offset: 1472)
!7256 = !DIDerivedType(tag: DW_TAG_member, name: "_mode", scope: !7218, file: !7219, line: 307, baseType: !32, size: 32, offset: 1536)
!7257 = !DIDerivedType(tag: DW_TAG_member, name: "_unused2", scope: !7218, file: !7219, line: 309, baseType: !7258, size: 160, offset: 1568)
!7258 = !DICompositeType(tag: DW_TAG_array_type, baseType: !319, size: 160, elements: !6997)
!7259 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7260, file: !7202, line: 143)
!7260 = !DISubprogram(name: "fgetws", scope: !7208, file: !7208, line: 756, type: !7261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7261 = !DISubroutineType(types: !7262)
!7262 = !{!7263, !7265, !32, !7266}
!7263 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7264, size: 64)
!7264 = !DIBasicType(name: "wchar_t", size: 32, encoding: DW_ATE_signed)
!7265 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !7263)
!7266 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !7215)
!7267 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7268, file: !7202, line: 144)
!7268 = !DISubprogram(name: "fputwc", scope: !7208, file: !7208, line: 741, type: !7269, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7269 = !DISubroutineType(types: !7270)
!7270 = !{!7204, !7264, !7215}
!7271 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7272, file: !7202, line: 145)
!7272 = !DISubprogram(name: "fputws", scope: !7208, file: !7208, line: 763, type: !7273, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7273 = !DISubroutineType(types: !7274)
!7274 = !{!32, !7275, !7266}
!7275 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !7276)
!7276 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7277, size: 64)
!7277 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !7264)
!7278 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7279, file: !7202, line: 146)
!7279 = !DISubprogram(name: "fwide", scope: !7208, file: !7208, line: 573, type: !7280, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7280 = !DISubroutineType(types: !7281)
!7281 = !{!32, !7215, !32}
!7282 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7283, file: !7202, line: 147)
!7283 = !DISubprogram(name: "fwprintf", scope: !7208, file: !7208, line: 580, type: !7284, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7284 = !DISubroutineType(types: !7285)
!7285 = !{!32, !7266, !7275, null}
!7286 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7287, file: !7202, line: 148)
!7287 = !DISubprogram(name: "fwscanf", scope: !7208, file: !7208, line: 621, type: !7284, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7288 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7289, file: !7202, line: 149)
!7289 = !DISubprogram(name: "getwc", scope: !7208, file: !7208, line: 728, type: !7213, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7290 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7291, file: !7202, line: 150)
!7291 = !DISubprogram(name: "getwchar", scope: !7208, file: !7208, line: 734, type: !7292, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7292 = !DISubroutineType(types: !7293)
!7293 = !{!7204}
!7294 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7295, file: !7202, line: 151)
!7295 = !DISubprogram(name: "mbrlen", scope: !7208, file: !7208, line: 329, type: !7296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7296 = !DISubroutineType(types: !7297)
!7297 = !{!2102, !7298, !2102, !7299}
!7298 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !317)
!7299 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !7300)
!7300 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7190, size: 64)
!7301 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7302, file: !7202, line: 152)
!7302 = !DISubprogram(name: "mbrtowc", scope: !7208, file: !7208, line: 296, type: !7303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7303 = !DISubroutineType(types: !7304)
!7304 = !{!2102, !7265, !7298, !2102, !7299}
!7305 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7306, file: !7202, line: 153)
!7306 = !DISubprogram(name: "mbsinit", scope: !7208, file: !7208, line: 292, type: !7307, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7307 = !DISubroutineType(types: !7308)
!7308 = !{!32, !7309}
!7309 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7310, size: 64)
!7310 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !7190)
!7311 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7312, file: !7202, line: 154)
!7312 = !DISubprogram(name: "mbsrtowcs", scope: !7208, file: !7208, line: 337, type: !7313, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7313 = !DISubroutineType(types: !7314)
!7314 = !{!2102, !7265, !7315, !2102, !7299}
!7315 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !7316)
!7316 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !317, size: 64)
!7317 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7318, file: !7202, line: 155)
!7318 = !DISubprogram(name: "putwc", scope: !7208, file: !7208, line: 742, type: !7269, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7319 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7320, file: !7202, line: 156)
!7320 = !DISubprogram(name: "putwchar", scope: !7208, file: !7208, line: 748, type: !7321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7321 = !DISubroutineType(types: !7322)
!7322 = !{!7204, !7264}
!7323 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7324, file: !7202, line: 158)
!7324 = !DISubprogram(name: "swprintf", scope: !7208, file: !7208, line: 590, type: !7325, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7325 = !DISubroutineType(types: !7326)
!7326 = !{!32, !7265, !2102, !7275, null}
!7327 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7328, file: !7202, line: 160)
!7328 = !DISubprogram(name: "swscanf", scope: !7208, file: !7208, line: 631, type: !7329, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7329 = !DISubroutineType(types: !7330)
!7330 = !{!32, !7275, !7275, null}
!7331 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7332, file: !7202, line: 161)
!7332 = !DISubprogram(name: "ungetwc", scope: !7208, file: !7208, line: 771, type: !7333, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7333 = !DISubroutineType(types: !7334)
!7334 = !{!7204, !7204, !7215}
!7335 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7336, file: !7202, line: 162)
!7336 = !DISubprogram(name: "vfwprintf", scope: !7208, file: !7208, line: 598, type: !7337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7337 = !DISubroutineType(types: !7338)
!7338 = !{!32, !7266, !7275, !7339}
!7339 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7340, size: 64)
!7340 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__va_list_tag", size: 192, flags: DIFlagTypePassByValue, elements: !7341, identifier: "_ZTS13__va_list_tag")
!7341 = !{!7342, !7344, !7345, !7346}
!7342 = !DIDerivedType(tag: DW_TAG_member, name: "gp_offset", scope: !7340, file: !7343, baseType: !6, size: 32)
!7343 = !DIFile(filename: "llvm34/lib/CodeGen/TailDuplication.cpp", directory: "/fast/fs")
!7344 = !DIDerivedType(tag: DW_TAG_member, name: "fp_offset", scope: !7340, file: !7343, baseType: !6, size: 32, offset: 32)
!7345 = !DIDerivedType(tag: DW_TAG_member, name: "overflow_arg_area", scope: !7340, file: !7343, baseType: !154, size: 64, offset: 64)
!7346 = !DIDerivedType(tag: DW_TAG_member, name: "reg_save_area", scope: !7340, file: !7343, baseType: !154, size: 64, offset: 128)
!7347 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7348, file: !7202, line: 164)
!7348 = !DISubprogram(name: "vfwscanf", scope: !7208, file: !7208, line: 673, type: !7337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7349 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7350, file: !7202, line: 167)
!7350 = !DISubprogram(name: "vswprintf", scope: !7208, file: !7208, line: 611, type: !7351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7351 = !DISubroutineType(types: !7352)
!7352 = !{!32, !7265, !2102, !7275, !7339}
!7353 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7354, file: !7202, line: 170)
!7354 = !DISubprogram(name: "vswscanf", scope: !7208, file: !7208, line: 685, type: !7355, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7355 = !DISubroutineType(types: !7356)
!7356 = !{!32, !7275, !7275, !7339}
!7357 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7358, file: !7202, line: 172)
!7358 = !DISubprogram(name: "vwprintf", scope: !7208, file: !7208, line: 606, type: !7359, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7359 = !DISubroutineType(types: !7360)
!7360 = !{!32, !7275, !7339}
!7361 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7362, file: !7202, line: 174)
!7362 = !DISubprogram(name: "vwscanf", scope: !7208, file: !7208, line: 681, type: !7359, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7363 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7364, file: !7202, line: 176)
!7364 = !DISubprogram(name: "wcrtomb", scope: !7208, file: !7208, line: 301, type: !7365, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7365 = !DISubroutineType(types: !7366)
!7366 = !{!2102, !7367, !7264, !7299}
!7367 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !1360)
!7368 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7369, file: !7202, line: 177)
!7369 = !DISubprogram(name: "wcscat", scope: !7208, file: !7208, line: 97, type: !7370, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7370 = !DISubroutineType(types: !7371)
!7371 = !{!7263, !7265, !7275}
!7372 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7373, file: !7202, line: 178)
!7373 = !DISubprogram(name: "wcscmp", scope: !7208, file: !7208, line: 106, type: !7374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7374 = !DISubroutineType(types: !7375)
!7375 = !{!32, !7276, !7276}
!7376 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7377, file: !7202, line: 179)
!7377 = !DISubprogram(name: "wcscoll", scope: !7208, file: !7208, line: 131, type: !7374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7378 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7379, file: !7202, line: 180)
!7379 = !DISubprogram(name: "wcscpy", scope: !7208, file: !7208, line: 87, type: !7370, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7380 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7381, file: !7202, line: 181)
!7381 = !DISubprogram(name: "wcscspn", scope: !7208, file: !7208, line: 187, type: !7382, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7382 = !DISubroutineType(types: !7383)
!7383 = !{!2102, !7276, !7276}
!7384 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7385, file: !7202, line: 182)
!7385 = !DISubprogram(name: "wcsftime", scope: !7208, file: !7208, line: 835, type: !7386, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7386 = !DISubroutineType(types: !7387)
!7387 = !{!2102, !7265, !2102, !7275, !7388}
!7388 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !7389)
!7389 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7390, size: 64)
!7390 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !7391)
!7391 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "tm", file: !7208, line: 83, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTS2tm")
!7392 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7393, file: !7202, line: 183)
!7393 = !DISubprogram(name: "wcslen", scope: !7208, file: !7208, line: 222, type: !7394, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7394 = !DISubroutineType(types: !7395)
!7395 = !{!2102, !7276}
!7396 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7397, file: !7202, line: 184)
!7397 = !DISubprogram(name: "wcsncat", scope: !7208, file: !7208, line: 101, type: !7398, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7398 = !DISubroutineType(types: !7399)
!7399 = !{!7263, !7265, !7275, !2102}
!7400 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7401, file: !7202, line: 185)
!7401 = !DISubprogram(name: "wcsncmp", scope: !7208, file: !7208, line: 109, type: !7402, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7402 = !DISubroutineType(types: !7403)
!7403 = !{!32, !7276, !7276, !2102}
!7404 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7405, file: !7202, line: 186)
!7405 = !DISubprogram(name: "wcsncpy", scope: !7208, file: !7208, line: 92, type: !7398, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7406 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7407, file: !7202, line: 187)
!7407 = !DISubprogram(name: "wcsrtombs", scope: !7208, file: !7208, line: 343, type: !7408, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7408 = !DISubroutineType(types: !7409)
!7409 = !{!2102, !7367, !7410, !2102, !7299}
!7410 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !7411)
!7411 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7276, size: 64)
!7412 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7413, file: !7202, line: 188)
!7413 = !DISubprogram(name: "wcsspn", scope: !7208, file: !7208, line: 191, type: !7382, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7414 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7415, file: !7202, line: 189)
!7415 = !DISubprogram(name: "wcstod", scope: !7208, file: !7208, line: 377, type: !7416, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7416 = !DISubroutineType(types: !7417)
!7417 = !{!7418, !7275, !7419}
!7418 = !DIBasicType(name: "double", size: 64, encoding: DW_ATE_float)
!7419 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !7420)
!7420 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7263, size: 64)
!7421 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7422, file: !7202, line: 191)
!7422 = !DISubprogram(name: "wcstof", scope: !7208, file: !7208, line: 382, type: !7423, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7423 = !DISubroutineType(types: !7424)
!7424 = !{!7425, !7275, !7419}
!7425 = !DIBasicType(name: "float", size: 32, encoding: DW_ATE_float)
!7426 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7427, file: !7202, line: 193)
!7427 = !DISubprogram(name: "wcstok", scope: !7208, file: !7208, line: 217, type: !7428, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7428 = !DISubroutineType(types: !7429)
!7429 = !{!7263, !7265, !7275, !7419}
!7430 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7431, file: !7202, line: 194)
!7431 = !DISubprogram(name: "wcstol", scope: !7208, file: !7208, line: 428, type: !7432, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7432 = !DISubroutineType(types: !7433)
!7433 = !{!288, !7275, !7419, !32}
!7434 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7435, file: !7202, line: 195)
!7435 = !DISubprogram(name: "wcstoul", scope: !7208, file: !7208, line: 433, type: !7436, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7436 = !DISubroutineType(types: !7437)
!7437 = !{!642, !7275, !7419, !32}
!7438 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7439, file: !7202, line: 196)
!7439 = !DISubprogram(name: "wcsxfrm", scope: !7208, file: !7208, line: 135, type: !7440, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7440 = !DISubroutineType(types: !7441)
!7441 = !{!2102, !7265, !7275, !2102}
!7442 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7443, file: !7202, line: 197)
!7443 = !DISubprogram(name: "wctob", scope: !7208, file: !7208, line: 324, type: !7444, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7444 = !DISubroutineType(types: !7445)
!7445 = !{!32, !7204}
!7446 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7447, file: !7202, line: 198)
!7447 = !DISubprogram(name: "wmemcmp", scope: !7208, file: !7208, line: 258, type: !7402, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7448 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7449, file: !7202, line: 199)
!7449 = !DISubprogram(name: "wmemcpy", scope: !7208, file: !7208, line: 262, type: !7398, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7450 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7451, file: !7202, line: 200)
!7451 = !DISubprogram(name: "wmemmove", scope: !7208, file: !7208, line: 267, type: !7452, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7452 = !DISubroutineType(types: !7453)
!7453 = !{!7263, !7263, !7276, !2102}
!7454 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7455, file: !7202, line: 201)
!7455 = !DISubprogram(name: "wmemset", scope: !7208, file: !7208, line: 271, type: !7456, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7456 = !DISubroutineType(types: !7457)
!7457 = !{!7263, !7263, !7264, !2102}
!7458 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7459, file: !7202, line: 202)
!7459 = !DISubprogram(name: "wprintf", scope: !7208, file: !7208, line: 587, type: !7460, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7460 = !DISubroutineType(types: !7461)
!7461 = !{!32, !7275, null}
!7462 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7463, file: !7202, line: 203)
!7463 = !DISubprogram(name: "wscanf", scope: !7208, file: !7208, line: 628, type: !7460, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7464 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7465, file: !7202, line: 204)
!7465 = !DISubprogram(name: "wcschr", scope: !7208, file: !7208, line: 164, type: !7466, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7466 = !DISubroutineType(types: !7467)
!7467 = !{!7263, !7276, !7264}
!7468 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7469, file: !7202, line: 205)
!7469 = !DISubprogram(name: "wcspbrk", scope: !7208, file: !7208, line: 201, type: !7470, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7470 = !DISubroutineType(types: !7471)
!7471 = !{!7263, !7276, !7276}
!7472 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7473, file: !7202, line: 206)
!7473 = !DISubprogram(name: "wcsrchr", scope: !7208, file: !7208, line: 174, type: !7466, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7474 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7475, file: !7202, line: 207)
!7475 = !DISubprogram(name: "wcsstr", scope: !7208, file: !7208, line: 212, type: !7470, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7476 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7477, file: !7202, line: 208)
!7477 = !DISubprogram(name: "wmemchr", scope: !7208, file: !7208, line: 253, type: !7478, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7478 = !DISubroutineType(types: !7479)
!7479 = !{!7263, !7276, !7264, !2102}
!7480 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7481, file: !7202, line: 248)
!7481 = !DISubprogram(name: "wcstold", scope: !7208, file: !7208, line: 384, type: !7482, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7482 = !DISubroutineType(types: !7483)
!7483 = !{!7484, !7275, !7419}
!7484 = !DIBasicType(name: "long double", size: 128, encoding: DW_ATE_float)
!7485 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7486, file: !7202, line: 257)
!7486 = !DISubprogram(name: "wcstoll", scope: !7208, file: !7208, line: 441, type: !7487, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7487 = !DISubroutineType(types: !7488)
!7488 = !{!7489, !7275, !7419, !32}
!7489 = !DIBasicType(name: "long long", size: 64, encoding: DW_ATE_signed)
!7490 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7491, file: !7202, line: 258)
!7491 = !DISubprogram(name: "wcstoull", scope: !7208, file: !7208, line: 448, type: !7492, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7492 = !DISubroutineType(types: !7493)
!7493 = !{!7494, !7275, !7419, !32}
!7494 = !DIBasicType(name: "unsigned long long", size: 64, encoding: DW_ATE_unsigned)
!7495 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7481, file: !7202, line: 264)
!7496 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7486, file: !7202, line: 265)
!7497 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7491, file: !7202, line: 266)
!7498 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7422, file: !7202, line: 280)
!7499 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7348, file: !7202, line: 283)
!7500 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7354, file: !7202, line: 286)
!7501 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7362, file: !7202, line: 289)
!7502 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7481, file: !7202, line: 293)
!7503 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7486, file: !7202, line: 294)
!7504 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7491, file: !7202, line: 295)
!7505 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !2786, file: !7506, line: 48)
!7506 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdint", directory: "")
!7507 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7508, file: !7506, line: 49)
!7508 = !DIDerivedType(tag: DW_TAG_typedef, name: "int16_t", file: !285, line: 25, baseType: !7509)
!7509 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int16_t", file: !287, line: 38, baseType: !7510)
!7510 = !DIBasicType(name: "short", size: 16, encoding: DW_ATE_signed)
!7511 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7512, file: !7506, line: 50)
!7512 = !DIDerivedType(tag: DW_TAG_typedef, name: "int32_t", file: !285, line: 26, baseType: !7513)
!7513 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int32_t", file: !287, line: 40, baseType: !32)
!7514 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !284, file: !7506, line: 51)
!7515 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7516, file: !7506, line: 53)
!7516 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast8_t", file: !7517, line: 68, baseType: !2788)
!7517 = !DIFile(filename: "/usr/include/stdint.h", directory: "", checksumkind: CSK_MD5, checksum: "c7469e3b87cb3d1a363efabd19f04208")
!7518 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7519, file: !7506, line: 54)
!7519 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast16_t", file: !7517, line: 70, baseType: !288)
!7520 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7521, file: !7506, line: 55)
!7521 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast32_t", file: !7517, line: 71, baseType: !288)
!7522 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7523, file: !7506, line: 56)
!7523 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast64_t", file: !7517, line: 72, baseType: !288)
!7524 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7525, file: !7506, line: 58)
!7525 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least8_t", file: !7517, line: 43, baseType: !2788)
!7526 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7527, file: !7506, line: 59)
!7527 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least16_t", file: !7517, line: 44, baseType: !7510)
!7528 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7529, file: !7506, line: 60)
!7529 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least32_t", file: !7517, line: 45, baseType: !32)
!7530 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7531, file: !7506, line: 61)
!7531 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least64_t", file: !7517, line: 47, baseType: !288)
!7532 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7533, file: !7506, line: 63)
!7533 = !DIDerivedType(tag: DW_TAG_typedef, name: "intmax_t", file: !7517, line: 111, baseType: !7534)
!7534 = !DIDerivedType(tag: DW_TAG_typedef, name: "__intmax_t", file: !287, line: 61, baseType: !288)
!7535 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7536, file: !7506, line: 64)
!7536 = !DIDerivedType(tag: DW_TAG_typedef, name: "intptr_t", file: !7517, line: 97, baseType: !288)
!7537 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !2776, file: !7506, line: 66)
!7538 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !2769, file: !7506, line: 67)
!7539 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !292, file: !7506, line: 68)
!7540 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7541, file: !7506, line: 69)
!7541 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint64_t", file: !293, line: 27, baseType: !7542)
!7542 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint64_t", file: !287, line: 44, baseType: !642)
!7543 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7544, file: !7506, line: 71)
!7544 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast8_t", file: !7517, line: 81, baseType: !251)
!7545 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7546, file: !7506, line: 72)
!7546 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast16_t", file: !7517, line: 83, baseType: !642)
!7547 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7548, file: !7506, line: 73)
!7548 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast32_t", file: !7517, line: 84, baseType: !642)
!7549 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7550, file: !7506, line: 74)
!7550 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast64_t", file: !7517, line: 85, baseType: !642)
!7551 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7552, file: !7506, line: 76)
!7552 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least8_t", file: !7517, line: 54, baseType: !251)
!7553 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7554, file: !7506, line: 77)
!7554 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least16_t", file: !7517, line: 55, baseType: !2771)
!7555 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7556, file: !7506, line: 78)
!7556 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least32_t", file: !7517, line: 56, baseType: !6)
!7557 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7558, file: !7506, line: 79)
!7558 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least64_t", file: !7517, line: 58, baseType: !642)
!7559 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7560, file: !7506, line: 81)
!7560 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintmax_t", file: !7517, line: 112, baseType: !7561)
!7561 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uintmax_t", file: !287, line: 62, baseType: !642)
!7562 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7563, file: !7506, line: 82)
!7563 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintptr_t", file: !7517, line: 100, baseType: !642)
!7564 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7565, file: !7566, line: 57)
!7565 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "exception_ptr", scope: !7567, file: !7566, line: 79, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSNSt15__exception_ptr13exception_ptrE")
!7566 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/exception_ptr.h", directory: "", checksumkind: CSK_MD5, checksum: "25d44782b686509a9fc5c8aaa8066643")
!7567 = !DINamespace(name: "__exception_ptr", scope: !839)
!7568 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !7567, entity: !7569, file: !7566, line: 73)
!7569 = !DISubprogram(name: "rethrow_exception", linkageName: "_ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE", scope: !839, file: !7566, line: 69, type: !7570, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!7570 = !DISubroutineType(types: !7571)
!7571 = !{null, !7565}
!7572 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !905, file: !874, line: 44)
!7573 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !1135, file: !874, line: 45)
!7574 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7575, file: !7577, line: 53)
!7575 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "lconv", file: !7576, line: 51, size: 768, flags: DIFlagFwdDecl, identifier: "_ZTS5lconv")
!7576 = !DIFile(filename: "/usr/include/locale.h", directory: "", checksumkind: CSK_MD5, checksum: "0595275e3f5b502d28f7cd61a0dff888")
!7577 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/clocale", directory: "")
!7578 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7579, file: !7577, line: 54)
!7579 = !DISubprogram(name: "setlocale", scope: !7576, file: !7576, line: 122, type: !7580, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7580 = !DISubroutineType(types: !7581)
!7581 = !{!1360, !32, !317}
!7582 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7583, file: !7577, line: 55)
!7583 = !DISubprogram(name: "localeconv", scope: !7576, file: !7576, line: 125, type: !7584, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7584 = !DISubroutineType(types: !7585)
!7585 = !{!7586}
!7586 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7575, size: 64)
!7587 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7588, file: !7592, line: 64)
!7588 = !DISubprogram(name: "isalnum", scope: !7589, file: !7589, line: 108, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7589 = !DIFile(filename: "/usr/include/ctype.h", directory: "", checksumkind: CSK_MD5, checksum: "c67c809b09ef8ea9c273687bc20a7fd3")
!7590 = !DISubroutineType(types: !7591)
!7591 = !{!32, !32}
!7592 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cctype", directory: "")
!7593 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7594, file: !7592, line: 65)
!7594 = !DISubprogram(name: "isalpha", scope: !7589, file: !7589, line: 109, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7595 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7596, file: !7592, line: 66)
!7596 = !DISubprogram(name: "iscntrl", scope: !7589, file: !7589, line: 110, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7597 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7598, file: !7592, line: 67)
!7598 = !DISubprogram(name: "isdigit", scope: !7589, file: !7589, line: 111, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7599 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7600, file: !7592, line: 68)
!7600 = !DISubprogram(name: "isgraph", scope: !7589, file: !7589, line: 113, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7601 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7602, file: !7592, line: 69)
!7602 = !DISubprogram(name: "islower", scope: !7589, file: !7589, line: 112, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7603 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7604, file: !7592, line: 70)
!7604 = !DISubprogram(name: "isprint", scope: !7589, file: !7589, line: 114, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7605 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7606, file: !7592, line: 71)
!7606 = !DISubprogram(name: "ispunct", scope: !7589, file: !7589, line: 115, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7607 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7608, file: !7592, line: 72)
!7608 = !DISubprogram(name: "isspace", scope: !7589, file: !7589, line: 116, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7609 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7610, file: !7592, line: 73)
!7610 = !DISubprogram(name: "isupper", scope: !7589, file: !7589, line: 117, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7611 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7612, file: !7592, line: 74)
!7612 = !DISubprogram(name: "isxdigit", scope: !7589, file: !7589, line: 118, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7613 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7614, file: !7592, line: 75)
!7614 = !DISubprogram(name: "tolower", scope: !7589, file: !7589, line: 122, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7615 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7616, file: !7592, line: 76)
!7616 = !DISubprogram(name: "toupper", scope: !7589, file: !7589, line: 125, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7617 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7618, file: !7592, line: 87)
!7618 = !DISubprogram(name: "isblank", scope: !7589, file: !7589, line: 130, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7619 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7620, file: !7622, line: 52)
!7620 = !DISubprogram(name: "abs", scope: !7621, file: !7621, line: 837, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7621 = !DIFile(filename: "/usr/include/stdlib.h", directory: "", checksumkind: CSK_MD5, checksum: "69d942f1572b8bd342d93c49f499f318")
!7622 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h", directory: "")
!7623 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7624, file: !7626, line: 127)
!7624 = !DIDerivedType(tag: DW_TAG_typedef, name: "div_t", file: !7621, line: 62, baseType: !7625)
!7625 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !7621, line: 58, size: 64, flags: DIFlagFwdDecl, identifier: "_ZTS5div_t")
!7626 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdlib", directory: "")
!7627 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7628, file: !7626, line: 128)
!7628 = !DIDerivedType(tag: DW_TAG_typedef, name: "ldiv_t", file: !7621, line: 70, baseType: !7629)
!7629 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !7621, line: 66, size: 128, flags: DIFlagTypePassByValue, elements: !7630, identifier: "_ZTS6ldiv_t")
!7630 = !{!7631, !7632}
!7631 = !DIDerivedType(tag: DW_TAG_member, name: "quot", scope: !7629, file: !7621, line: 68, baseType: !288, size: 64)
!7632 = !DIDerivedType(tag: DW_TAG_member, name: "rem", scope: !7629, file: !7621, line: 69, baseType: !288, size: 64, offset: 64)
!7633 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7634, file: !7626, line: 130)
!7634 = !DISubprogram(name: "abort", scope: !7621, file: !7621, line: 588, type: !7635, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!7635 = !DISubroutineType(types: !7636)
!7636 = !{null}
!7637 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7638, file: !7626, line: 134)
!7638 = !DISubprogram(name: "atexit", scope: !7621, file: !7621, line: 592, type: !7639, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7639 = !DISubroutineType(types: !7640)
!7640 = !{!32, !7641}
!7641 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7635, size: 64)
!7642 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7643, file: !7626, line: 137)
!7643 = !DISubprogram(name: "at_quick_exit", scope: !7621, file: !7621, line: 597, type: !7639, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7644 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7645, file: !7626, line: 140)
!7645 = !DISubprogram(name: "atof", scope: !7646, file: !7646, line: 25, type: !7647, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7646 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h", directory: "", checksumkind: CSK_MD5, checksum: "ce60958b260b171e83db3307f1d644f0")
!7647 = !DISubroutineType(types: !7648)
!7648 = !{!7418, !317}
!7649 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7650, file: !7626, line: 141)
!7650 = !DISubprogram(name: "atoi", scope: !7621, file: !7621, line: 361, type: !7651, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7651 = !DISubroutineType(types: !7652)
!7652 = !{!32, !317}
!7653 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7654, file: !7626, line: 142)
!7654 = !DISubprogram(name: "atol", scope: !7621, file: !7621, line: 366, type: !7655, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7655 = !DISubroutineType(types: !7656)
!7656 = !{!288, !317}
!7657 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7658, file: !7626, line: 143)
!7658 = !DISubprogram(name: "bsearch", scope: !7659, file: !7659, line: 20, type: !7660, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7659 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h", directory: "", checksumkind: CSK_MD5, checksum: "1a798a38b25adee7bb680abce9ef568a")
!7660 = !DISubroutineType(types: !7661)
!7661 = !{!154, !124, !124, !2102, !2102, !7662}
!7662 = !DIDerivedType(tag: DW_TAG_typedef, name: "__compar_fn_t", file: !7621, line: 805, baseType: !7663)
!7663 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7664, size: 64)
!7664 = !DISubroutineType(types: !7665)
!7665 = !{!32, !124, !124}
!7666 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7667, file: !7626, line: 144)
!7667 = !DISubprogram(name: "calloc", scope: !7621, file: !7621, line: 541, type: !7668, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7668 = !DISubroutineType(types: !7669)
!7669 = !{!154, !2102, !2102}
!7670 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7671, file: !7626, line: 145)
!7671 = !DISubprogram(name: "div", scope: !7621, file: !7621, line: 849, type: !7672, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7672 = !DISubroutineType(types: !7673)
!7673 = !{!7624, !32, !32}
!7674 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7675, file: !7626, line: 146)
!7675 = !DISubprogram(name: "exit", scope: !7621, file: !7621, line: 614, type: !7676, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!7676 = !DISubroutineType(types: !7677)
!7677 = !{null, !32}
!7678 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7679, file: !7626, line: 147)
!7679 = !DISubprogram(name: "free", scope: !7621, file: !7621, line: 563, type: !7680, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7680 = !DISubroutineType(types: !7681)
!7681 = !{null, !154}
!7682 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7683, file: !7626, line: 148)
!7683 = !DISubprogram(name: "getenv", scope: !7621, file: !7621, line: 631, type: !7684, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7684 = !DISubroutineType(types: !7685)
!7685 = !{!1360, !317}
!7686 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7687, file: !7626, line: 149)
!7687 = !DISubprogram(name: "labs", scope: !7621, file: !7621, line: 838, type: !7688, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7688 = !DISubroutineType(types: !7689)
!7689 = !{!288, !288}
!7690 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7691, file: !7626, line: 150)
!7691 = !DISubprogram(name: "ldiv", scope: !7621, file: !7621, line: 851, type: !7692, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7692 = !DISubroutineType(types: !7693)
!7693 = !{!7628, !288, !288}
!7694 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7695, file: !7626, line: 151)
!7695 = !DISubprogram(name: "malloc", scope: !7621, file: !7621, line: 539, type: !7696, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7696 = !DISubroutineType(types: !7697)
!7697 = !{!154, !2102}
!7698 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7699, file: !7626, line: 153)
!7699 = !DISubprogram(name: "mblen", scope: !7621, file: !7621, line: 919, type: !7700, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7700 = !DISubroutineType(types: !7701)
!7701 = !{!32, !317, !2102}
!7702 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7703, file: !7626, line: 154)
!7703 = !DISubprogram(name: "mbstowcs", scope: !7621, file: !7621, line: 930, type: !7704, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7704 = !DISubroutineType(types: !7705)
!7705 = !{!2102, !7265, !7298, !2102}
!7706 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7707, file: !7626, line: 155)
!7707 = !DISubprogram(name: "mbtowc", scope: !7621, file: !7621, line: 922, type: !7708, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7708 = !DISubroutineType(types: !7709)
!7709 = !{!32, !7265, !7298, !2102}
!7710 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7711, file: !7626, line: 157)
!7711 = !DISubprogram(name: "qsort", scope: !7621, file: !7621, line: 827, type: !7712, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7712 = !DISubroutineType(types: !7713)
!7713 = !{null, !154, !2102, !2102, !7662}
!7714 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7715, file: !7626, line: 160)
!7715 = !DISubprogram(name: "quick_exit", scope: !7621, file: !7621, line: 620, type: !7676, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!7716 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7717, file: !7626, line: 163)
!7717 = !DISubprogram(name: "rand", scope: !7621, file: !7621, line: 453, type: !7718, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7718 = !DISubroutineType(types: !7719)
!7719 = !{!32}
!7720 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7721, file: !7626, line: 164)
!7721 = !DISubprogram(name: "realloc", scope: !7621, file: !7621, line: 549, type: !7722, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7722 = !DISubroutineType(types: !7723)
!7723 = !{!154, !154, !2102}
!7724 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7725, file: !7626, line: 165)
!7725 = !DISubprogram(name: "srand", scope: !7621, file: !7621, line: 455, type: !7726, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7726 = !DISubroutineType(types: !7727)
!7727 = !{null, !6}
!7728 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7729, file: !7626, line: 166)
!7729 = !DISubprogram(name: "strtod", scope: !7621, file: !7621, line: 117, type: !7730, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7730 = !DISubroutineType(types: !7731)
!7731 = !{!7418, !7298, !7732}
!7732 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !7733)
!7733 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1360, size: 64)
!7734 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7735, file: !7626, line: 167)
!7735 = !DISubprogram(name: "strtol", scope: !7621, file: !7621, line: 176, type: !7736, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7736 = !DISubroutineType(types: !7737)
!7737 = !{!288, !7298, !7732, !32}
!7738 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7739, file: !7626, line: 168)
!7739 = !DISubprogram(name: "strtoul", scope: !7621, file: !7621, line: 180, type: !7740, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7740 = !DISubroutineType(types: !7741)
!7741 = !{!642, !7298, !7732, !32}
!7742 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7743, file: !7626, line: 169)
!7743 = !DISubprogram(name: "system", scope: !7621, file: !7621, line: 781, type: !7651, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7744 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7745, file: !7626, line: 171)
!7745 = !DISubprogram(name: "wcstombs", scope: !7621, file: !7621, line: 933, type: !7746, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7746 = !DISubroutineType(types: !7747)
!7747 = !{!2102, !7367, !7275, !2102}
!7748 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7749, file: !7626, line: 172)
!7749 = !DISubprogram(name: "wctomb", scope: !7621, file: !7621, line: 926, type: !7750, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7750 = !DISubroutineType(types: !7751)
!7751 = !{!32, !1360, !7264}
!7752 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7753, file: !7626, line: 200)
!7753 = !DIDerivedType(tag: DW_TAG_typedef, name: "lldiv_t", file: !7621, line: 80, baseType: !7754)
!7754 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !7621, line: 76, size: 128, flags: DIFlagTypePassByValue, elements: !7755, identifier: "_ZTS7lldiv_t")
!7755 = !{!7756, !7757}
!7756 = !DIDerivedType(tag: DW_TAG_member, name: "quot", scope: !7754, file: !7621, line: 78, baseType: !7489, size: 64)
!7757 = !DIDerivedType(tag: DW_TAG_member, name: "rem", scope: !7754, file: !7621, line: 79, baseType: !7489, size: 64, offset: 64)
!7758 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7759, file: !7626, line: 206)
!7759 = !DISubprogram(name: "_Exit", scope: !7621, file: !7621, line: 626, type: !7676, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!7760 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7761, file: !7626, line: 210)
!7761 = !DISubprogram(name: "llabs", scope: !7621, file: !7621, line: 841, type: !7762, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7762 = !DISubroutineType(types: !7763)
!7763 = !{!7489, !7489}
!7764 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7765, file: !7626, line: 216)
!7765 = !DISubprogram(name: "lldiv", scope: !7621, file: !7621, line: 855, type: !7766, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7766 = !DISubroutineType(types: !7767)
!7767 = !{!7753, !7489, !7489}
!7768 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7769, file: !7626, line: 227)
!7769 = !DISubprogram(name: "atoll", scope: !7621, file: !7621, line: 373, type: !7770, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7770 = !DISubroutineType(types: !7771)
!7771 = !{!7489, !317}
!7772 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7773, file: !7626, line: 228)
!7773 = !DISubprogram(name: "strtoll", scope: !7621, file: !7621, line: 200, type: !7774, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7774 = !DISubroutineType(types: !7775)
!7775 = !{!7489, !7298, !7732, !32}
!7776 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7777, file: !7626, line: 229)
!7777 = !DISubprogram(name: "strtoull", scope: !7621, file: !7621, line: 205, type: !7778, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7778 = !DISubroutineType(types: !7779)
!7779 = !{!7494, !7298, !7732, !32}
!7780 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7781, file: !7626, line: 231)
!7781 = !DISubprogram(name: "strtof", scope: !7621, file: !7621, line: 123, type: !7782, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7782 = !DISubroutineType(types: !7783)
!7783 = !{!7425, !7298, !7732}
!7784 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7785, file: !7626, line: 232)
!7785 = !DISubprogram(name: "strtold", scope: !7621, file: !7621, line: 126, type: !7786, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7786 = !DISubroutineType(types: !7787)
!7787 = !{!7484, !7298, !7732}
!7788 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7753, file: !7626, line: 240)
!7789 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7759, file: !7626, line: 242)
!7790 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7761, file: !7626, line: 244)
!7791 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7792, file: !7626, line: 245)
!7792 = !DISubprogram(name: "div", linkageName: "_ZN9__gnu_cxx3divExx", scope: !5, file: !7626, line: 213, type: !7766, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7793 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7765, file: !7626, line: 246)
!7794 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7769, file: !7626, line: 248)
!7795 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7781, file: !7626, line: 249)
!7796 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7773, file: !7626, line: 250)
!7797 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7777, file: !7626, line: 251)
!7798 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7785, file: !7626, line: 252)
!7799 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7800, file: !7802, line: 98)
!7800 = !DIDerivedType(tag: DW_TAG_typedef, name: "FILE", file: !7801, line: 7, baseType: !7218)
!7801 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/FILE.h", directory: "", checksumkind: CSK_MD5, checksum: "571f9fb6223c42439075fdde11a0de5d")
!7802 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdio", directory: "")
!7803 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7804, file: !7802, line: 99)
!7804 = !DIDerivedType(tag: DW_TAG_typedef, name: "fpos_t", file: !7805, line: 78, baseType: !7806)
!7805 = !DIFile(filename: "/usr/include/stdio.h", directory: "", checksumkind: CSK_MD5, checksum: "2ab51d960d7d0ed84798d1688a6988b0")
!7806 = !DIDerivedType(tag: DW_TAG_typedef, name: "_G_fpos_t", file: !7807, line: 30, baseType: !7808)
!7807 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/_G_config.h", directory: "", checksumkind: CSK_MD5, checksum: "f78480ecfcae11a7bda5a6b08034c1fb")
!7808 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !7807, line: 26, size: 128, flags: DIFlagFwdDecl, identifier: "_ZTS9_G_fpos_t")
!7809 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7810, file: !7802, line: 101)
!7810 = !DISubprogram(name: "clearerr", scope: !7805, file: !7805, line: 757, type: !7811, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7811 = !DISubroutineType(types: !7812)
!7812 = !{null, !7813}
!7813 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7800, size: 64)
!7814 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7815, file: !7802, line: 102)
!7815 = !DISubprogram(name: "fclose", scope: !7805, file: !7805, line: 199, type: !7816, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7816 = !DISubroutineType(types: !7817)
!7817 = !{!32, !7813}
!7818 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7819, file: !7802, line: 103)
!7819 = !DISubprogram(name: "feof", scope: !7805, file: !7805, line: 759, type: !7816, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7820 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7821, file: !7802, line: 104)
!7821 = !DISubprogram(name: "ferror", scope: !7805, file: !7805, line: 761, type: !7816, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7822 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7823, file: !7802, line: 105)
!7823 = !DISubprogram(name: "fflush", scope: !7805, file: !7805, line: 204, type: !7816, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7824 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7825, file: !7802, line: 106)
!7825 = !DISubprogram(name: "fgetc", scope: !7805, file: !7805, line: 477, type: !7816, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7826 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7827, file: !7802, line: 107)
!7827 = !DISubprogram(name: "fgetpos", scope: !7805, file: !7805, line: 731, type: !7828, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7828 = !DISubroutineType(types: !7829)
!7829 = !{!32, !7830, !7831}
!7830 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !7813)
!7831 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !7832)
!7832 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7804, size: 64)
!7833 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7834, file: !7802, line: 108)
!7834 = !DISubprogram(name: "fgets", scope: !7805, file: !7805, line: 564, type: !7835, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7835 = !DISubroutineType(types: !7836)
!7836 = !{!1360, !7367, !32, !7830}
!7837 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7838, file: !7802, line: 109)
!7838 = !DISubprogram(name: "fopen", scope: !7805, file: !7805, line: 232, type: !7839, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7839 = !DISubroutineType(types: !7840)
!7840 = !{!7813, !7298, !7298}
!7841 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7842, file: !7802, line: 110)
!7842 = !DISubprogram(name: "fprintf", scope: !7805, file: !7805, line: 312, type: !7843, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7843 = !DISubroutineType(types: !7844)
!7844 = !{!32, !7830, !7298, null}
!7845 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7846, file: !7802, line: 111)
!7846 = !DISubprogram(name: "fputc", scope: !7805, file: !7805, line: 517, type: !7847, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7847 = !DISubroutineType(types: !7848)
!7848 = !{!32, !32, !7813}
!7849 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7850, file: !7802, line: 112)
!7850 = !DISubprogram(name: "fputs", scope: !7805, file: !7805, line: 626, type: !7851, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7851 = !DISubroutineType(types: !7852)
!7852 = !{!32, !7298, !7830}
!7853 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7854, file: !7802, line: 113)
!7854 = !DISubprogram(name: "fread", scope: !7805, file: !7805, line: 646, type: !7855, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7855 = !DISubroutineType(types: !7856)
!7856 = !{!2102, !7857, !2102, !2102, !7830}
!7857 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !154)
!7858 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7859, file: !7802, line: 114)
!7859 = !DISubprogram(name: "freopen", scope: !7805, file: !7805, line: 238, type: !7860, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7860 = !DISubroutineType(types: !7861)
!7861 = !{!7813, !7298, !7298, !7830}
!7862 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7863, file: !7802, line: 115)
!7863 = !DISubprogram(name: "fscanf", scope: !7805, file: !7805, line: 377, type: !7843, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7864 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7865, file: !7802, line: 116)
!7865 = !DISubprogram(name: "fseek", scope: !7805, file: !7805, line: 684, type: !7866, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7866 = !DISubroutineType(types: !7867)
!7867 = !{!32, !7813, !288, !32}
!7868 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7869, file: !7802, line: 117)
!7869 = !DISubprogram(name: "fsetpos", scope: !7805, file: !7805, line: 736, type: !7870, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7870 = !DISubroutineType(types: !7871)
!7871 = !{!32, !7813, !7872}
!7872 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7873, size: 64)
!7873 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !7804)
!7874 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7875, file: !7802, line: 118)
!7875 = !DISubprogram(name: "ftell", scope: !7805, file: !7805, line: 689, type: !7876, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7876 = !DISubroutineType(types: !7877)
!7877 = !{!288, !7813}
!7878 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7879, file: !7802, line: 119)
!7879 = !DISubprogram(name: "fwrite", scope: !7805, file: !7805, line: 652, type: !7880, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7880 = !DISubroutineType(types: !7881)
!7881 = !{!2102, !7882, !2102, !2102, !7830}
!7882 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !124)
!7883 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7884, file: !7802, line: 120)
!7884 = !DISubprogram(name: "getc", scope: !7805, file: !7805, line: 478, type: !7816, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7885 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7886, file: !7802, line: 121)
!7886 = !DISubprogram(name: "getchar", scope: !7887, file: !7887, line: 44, type: !7718, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7887 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdio.h", directory: "", checksumkind: CSK_MD5, checksum: "ae874477a6b090849220f12acdd69dc3")
!7888 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7889, file: !7802, line: 126)
!7889 = !DISubprogram(name: "perror", scope: !7805, file: !7805, line: 775, type: !7890, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7890 = !DISubroutineType(types: !7891)
!7891 = !{null, !317}
!7892 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7893, file: !7802, line: 127)
!7893 = !DISubprogram(name: "printf", scope: !7805, file: !7805, line: 318, type: !7894, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7894 = !DISubroutineType(types: !7895)
!7895 = !{!32, !7298, null}
!7896 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7897, file: !7802, line: 128)
!7897 = !DISubprogram(name: "putc", scope: !7805, file: !7805, line: 518, type: !7847, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7898 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7899, file: !7802, line: 129)
!7899 = !DISubprogram(name: "putchar", scope: !7887, file: !7887, line: 79, type: !7590, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7900 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7901, file: !7802, line: 130)
!7901 = !DISubprogram(name: "puts", scope: !7805, file: !7805, line: 632, type: !7651, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7902 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7903, file: !7802, line: 131)
!7903 = !DISubprogram(name: "remove", scope: !7805, file: !7805, line: 144, type: !7651, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7904 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7905, file: !7802, line: 132)
!7905 = !DISubprogram(name: "rename", scope: !7805, file: !7805, line: 146, type: !7906, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7906 = !DISubroutineType(types: !7907)
!7907 = !{!32, !317, !317}
!7908 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7909, file: !7802, line: 133)
!7909 = !DISubprogram(name: "rewind", scope: !7805, file: !7805, line: 694, type: !7811, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7910 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7911, file: !7802, line: 134)
!7911 = !DISubprogram(name: "scanf", scope: !7805, file: !7805, line: 383, type: !7894, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7912 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7913, file: !7802, line: 135)
!7913 = !DISubprogram(name: "setbuf", scope: !7805, file: !7805, line: 290, type: !7914, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7914 = !DISubroutineType(types: !7915)
!7915 = !{null, !7830, !7367}
!7916 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7917, file: !7802, line: 136)
!7917 = !DISubprogram(name: "setvbuf", scope: !7805, file: !7805, line: 294, type: !7918, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7918 = !DISubroutineType(types: !7919)
!7919 = !{!32, !7830, !7367, !32, !2102}
!7920 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7921, file: !7802, line: 137)
!7921 = !DISubprogram(name: "sprintf", scope: !7805, file: !7805, line: 320, type: !7922, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7922 = !DISubroutineType(types: !7923)
!7923 = !{!32, !7367, !7298, null}
!7924 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7925, file: !7802, line: 138)
!7925 = !DISubprogram(name: "sscanf", scope: !7805, file: !7805, line: 385, type: !7926, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7926 = !DISubroutineType(types: !7927)
!7927 = !{!32, !7298, !7298, null}
!7928 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7929, file: !7802, line: 139)
!7929 = !DISubprogram(name: "tmpfile", scope: !7805, file: !7805, line: 159, type: !7930, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7930 = !DISubroutineType(types: !7931)
!7931 = !{!7813}
!7932 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7933, file: !7802, line: 141)
!7933 = !DISubprogram(name: "tmpnam", scope: !7805, file: !7805, line: 173, type: !7934, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7934 = !DISubroutineType(types: !7935)
!7935 = !{!1360, !1360}
!7936 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7937, file: !7802, line: 143)
!7937 = !DISubprogram(name: "ungetc", scope: !7805, file: !7805, line: 639, type: !7847, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7938 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7939, file: !7802, line: 144)
!7939 = !DISubprogram(name: "vfprintf", scope: !7805, file: !7805, line: 327, type: !7940, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7940 = !DISubroutineType(types: !7941)
!7941 = !{!32, !7830, !7298, !7339}
!7942 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7943, file: !7802, line: 145)
!7943 = !DISubprogram(name: "vprintf", scope: !7887, file: !7887, line: 36, type: !7944, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7944 = !DISubroutineType(types: !7945)
!7945 = !{!32, !7298, !7339}
!7946 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7947, file: !7802, line: 146)
!7947 = !DISubprogram(name: "vsprintf", scope: !7805, file: !7805, line: 335, type: !7948, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7948 = !DISubroutineType(types: !7949)
!7949 = !{!32, !7367, !7298, !7339}
!7950 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7951, file: !7802, line: 175)
!7951 = !DISubprogram(name: "snprintf", scope: !7805, file: !7805, line: 340, type: !7952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7952 = !DISubroutineType(types: !7953)
!7953 = !{!32, !7367, !2102, !7298, null}
!7954 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7955, file: !7802, line: 176)
!7955 = !DISubprogram(name: "vfscanf", scope: !7805, file: !7805, line: 420, type: !7940, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7956 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7957, file: !7802, line: 177)
!7957 = !DISubprogram(name: "vscanf", scope: !7805, file: !7805, line: 428, type: !7944, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7958 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7959, file: !7802, line: 178)
!7959 = !DISubprogram(name: "vsnprintf", scope: !7805, file: !7805, line: 344, type: !7960, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7960 = !DISubroutineType(types: !7961)
!7961 = !{!32, !7367, !2102, !7298, !7339}
!7962 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !7963, file: !7802, line: 179)
!7963 = !DISubprogram(name: "vsscanf", scope: !7805, file: !7805, line: 432, type: !7964, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7964 = !DISubroutineType(types: !7965)
!7965 = !{!32, !7298, !7298, !7339}
!7966 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7951, file: !7802, line: 185)
!7967 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7955, file: !7802, line: 186)
!7968 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7957, file: !7802, line: 187)
!7969 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7959, file: !7802, line: 188)
!7970 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7963, file: !7802, line: 189)
!7971 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7972, file: !7976, line: 83)
!7972 = !DISubprogram(name: "acos", scope: !7973, file: !7973, line: 53, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7973 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", directory: "", checksumkind: CSK_MD5, checksum: "540523e6856cf8d57a3ebef5fd79793e")
!7974 = !DISubroutineType(types: !7975)
!7975 = !{!7418, !7418}
!7976 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cmath", directory: "")
!7977 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7978, file: !7976, line: 102)
!7978 = !DISubprogram(name: "asin", scope: !7973, file: !7973, line: 55, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7979 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7980, file: !7976, line: 121)
!7980 = !DISubprogram(name: "atan", scope: !7973, file: !7973, line: 57, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7981 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7982, file: !7976, line: 140)
!7982 = !DISubprogram(name: "atan2", scope: !7973, file: !7973, line: 59, type: !7983, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7983 = !DISubroutineType(types: !7984)
!7984 = !{!7418, !7418, !7418}
!7985 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7986, file: !7976, line: 161)
!7986 = !DISubprogram(name: "ceil", scope: !7973, file: !7973, line: 159, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7987 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7988, file: !7976, line: 180)
!7988 = !DISubprogram(name: "cos", scope: !7973, file: !7973, line: 62, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7989 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7990, file: !7976, line: 199)
!7990 = !DISubprogram(name: "cosh", scope: !7973, file: !7973, line: 71, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7991 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7992, file: !7976, line: 218)
!7992 = !DISubprogram(name: "exp", scope: !7973, file: !7973, line: 95, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7993 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7994, file: !7976, line: 237)
!7994 = !DISubprogram(name: "fabs", scope: !7973, file: !7973, line: 162, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7995 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7996, file: !7976, line: 256)
!7996 = !DISubprogram(name: "floor", scope: !7973, file: !7973, line: 165, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7997 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7998, file: !7976, line: 275)
!7998 = !DISubprogram(name: "fmod", scope: !7973, file: !7973, line: 168, type: !7983, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7999 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8000, file: !7976, line: 296)
!8000 = !DISubprogram(name: "frexp", scope: !7973, file: !7973, line: 98, type: !8001, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8001 = !DISubroutineType(types: !8002)
!8002 = !{!7418, !7418, !8003}
!8003 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !32, size: 64)
!8004 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8005, file: !7976, line: 315)
!8005 = !DISubprogram(name: "ldexp", scope: !7973, file: !7973, line: 101, type: !8006, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8006 = !DISubroutineType(types: !8007)
!8007 = !{!7418, !7418, !32}
!8008 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8009, file: !7976, line: 334)
!8009 = !DISubprogram(name: "log", scope: !7973, file: !7973, line: 104, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8010 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8011, file: !7976, line: 353)
!8011 = !DISubprogram(name: "log10", scope: !7973, file: !7973, line: 107, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8012 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8013, file: !7976, line: 372)
!8013 = !DISubprogram(name: "modf", scope: !7973, file: !7973, line: 110, type: !8014, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8014 = !DISubroutineType(types: !8015)
!8015 = !{!7418, !7418, !8016}
!8016 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7418, size: 64)
!8017 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8018, file: !7976, line: 384)
!8018 = !DISubprogram(name: "pow", scope: !7973, file: !7973, line: 140, type: !7983, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8019 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8020, file: !7976, line: 421)
!8020 = !DISubprogram(name: "sin", scope: !7973, file: !7973, line: 64, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8021 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8022, file: !7976, line: 440)
!8022 = !DISubprogram(name: "sinh", scope: !7973, file: !7973, line: 73, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8023 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8024, file: !7976, line: 459)
!8024 = !DISubprogram(name: "sqrt", scope: !7973, file: !7973, line: 143, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8025 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8026, file: !7976, line: 478)
!8026 = !DISubprogram(name: "tan", scope: !7973, file: !7973, line: 66, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8027 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8028, file: !7976, line: 497)
!8028 = !DISubprogram(name: "tanh", scope: !7973, file: !7973, line: 75, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8029 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8030, file: !7976, line: 1065)
!8030 = !DIDerivedType(tag: DW_TAG_typedef, name: "double_t", file: !8031, line: 150, baseType: !7418)
!8031 = !DIFile(filename: "/usr/include/math.h", directory: "", checksumkind: CSK_MD5, checksum: "ecf196918078d683ff91ad9a1c51599a")
!8032 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8033, file: !7976, line: 1066)
!8033 = !DIDerivedType(tag: DW_TAG_typedef, name: "float_t", file: !8031, line: 149, baseType: !7425)
!8034 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8035, file: !7976, line: 1069)
!8035 = !DISubprogram(name: "acosh", scope: !7973, file: !7973, line: 85, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8036 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8037, file: !7976, line: 1070)
!8037 = !DISubprogram(name: "acoshf", scope: !7973, file: !7973, line: 85, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8038 = !DISubroutineType(types: !8039)
!8039 = !{!7425, !7425}
!8040 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8041, file: !7976, line: 1071)
!8041 = !DISubprogram(name: "acoshl", scope: !7973, file: !7973, line: 85, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8042 = !DISubroutineType(types: !8043)
!8043 = !{!7484, !7484}
!8044 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8045, file: !7976, line: 1073)
!8045 = !DISubprogram(name: "asinh", scope: !7973, file: !7973, line: 87, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8046 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8047, file: !7976, line: 1074)
!8047 = !DISubprogram(name: "asinhf", scope: !7973, file: !7973, line: 87, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8048 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8049, file: !7976, line: 1075)
!8049 = !DISubprogram(name: "asinhl", scope: !7973, file: !7973, line: 87, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8050 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8051, file: !7976, line: 1077)
!8051 = !DISubprogram(name: "atanh", scope: !7973, file: !7973, line: 89, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8052 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8053, file: !7976, line: 1078)
!8053 = !DISubprogram(name: "atanhf", scope: !7973, file: !7973, line: 89, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8054 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8055, file: !7976, line: 1079)
!8055 = !DISubprogram(name: "atanhl", scope: !7973, file: !7973, line: 89, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8056 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8057, file: !7976, line: 1081)
!8057 = !DISubprogram(name: "cbrt", scope: !7973, file: !7973, line: 152, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8058 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8059, file: !7976, line: 1082)
!8059 = !DISubprogram(name: "cbrtf", scope: !7973, file: !7973, line: 152, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8060 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8061, file: !7976, line: 1083)
!8061 = !DISubprogram(name: "cbrtl", scope: !7973, file: !7973, line: 152, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8062 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8063, file: !7976, line: 1085)
!8063 = !DISubprogram(name: "copysign", scope: !7973, file: !7973, line: 196, type: !7983, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8064 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8065, file: !7976, line: 1086)
!8065 = !DISubprogram(name: "copysignf", scope: !7973, file: !7973, line: 196, type: !8066, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8066 = !DISubroutineType(types: !8067)
!8067 = !{!7425, !7425, !7425}
!8068 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8069, file: !7976, line: 1087)
!8069 = !DISubprogram(name: "copysignl", scope: !7973, file: !7973, line: 196, type: !8070, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8070 = !DISubroutineType(types: !8071)
!8071 = !{!7484, !7484, !7484}
!8072 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8073, file: !7976, line: 1089)
!8073 = !DISubprogram(name: "erf", scope: !7973, file: !7973, line: 228, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8074 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8075, file: !7976, line: 1090)
!8075 = !DISubprogram(name: "erff", scope: !7973, file: !7973, line: 228, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8076 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8077, file: !7976, line: 1091)
!8077 = !DISubprogram(name: "erfl", scope: !7973, file: !7973, line: 228, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8078 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8079, file: !7976, line: 1093)
!8079 = !DISubprogram(name: "erfc", scope: !7973, file: !7973, line: 229, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8080 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8081, file: !7976, line: 1094)
!8081 = !DISubprogram(name: "erfcf", scope: !7973, file: !7973, line: 229, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8082 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8083, file: !7976, line: 1095)
!8083 = !DISubprogram(name: "erfcl", scope: !7973, file: !7973, line: 229, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8084 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8085, file: !7976, line: 1097)
!8085 = !DISubprogram(name: "exp2", scope: !7973, file: !7973, line: 130, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8086 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8087, file: !7976, line: 1098)
!8087 = !DISubprogram(name: "exp2f", scope: !7973, file: !7973, line: 130, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8088 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8089, file: !7976, line: 1099)
!8089 = !DISubprogram(name: "exp2l", scope: !7973, file: !7973, line: 130, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8090 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8091, file: !7976, line: 1101)
!8091 = !DISubprogram(name: "expm1", scope: !7973, file: !7973, line: 119, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8092 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8093, file: !7976, line: 1102)
!8093 = !DISubprogram(name: "expm1f", scope: !7973, file: !7973, line: 119, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8094 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8095, file: !7976, line: 1103)
!8095 = !DISubprogram(name: "expm1l", scope: !7973, file: !7973, line: 119, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8096 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8097, file: !7976, line: 1105)
!8097 = !DISubprogram(name: "fdim", scope: !7973, file: !7973, line: 326, type: !7983, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8098 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8099, file: !7976, line: 1106)
!8099 = !DISubprogram(name: "fdimf", scope: !7973, file: !7973, line: 326, type: !8066, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8100 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8101, file: !7976, line: 1107)
!8101 = !DISubprogram(name: "fdiml", scope: !7973, file: !7973, line: 326, type: !8070, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8102 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8103, file: !7976, line: 1109)
!8103 = !DISubprogram(name: "fma", scope: !7973, file: !7973, line: 335, type: !8104, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8104 = !DISubroutineType(types: !8105)
!8105 = !{!7418, !7418, !7418, !7418}
!8106 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8107, file: !7976, line: 1110)
!8107 = !DISubprogram(name: "fmaf", scope: !7973, file: !7973, line: 335, type: !8108, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8108 = !DISubroutineType(types: !8109)
!8109 = !{!7425, !7425, !7425, !7425}
!8110 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8111, file: !7976, line: 1111)
!8111 = !DISubprogram(name: "fmal", scope: !7973, file: !7973, line: 335, type: !8112, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8112 = !DISubroutineType(types: !8113)
!8113 = !{!7484, !7484, !7484, !7484}
!8114 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8115, file: !7976, line: 1113)
!8115 = !DISubprogram(name: "fmax", scope: !7973, file: !7973, line: 329, type: !7983, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8116 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8117, file: !7976, line: 1114)
!8117 = !DISubprogram(name: "fmaxf", scope: !7973, file: !7973, line: 329, type: !8066, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8118 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8119, file: !7976, line: 1115)
!8119 = !DISubprogram(name: "fmaxl", scope: !7973, file: !7973, line: 329, type: !8070, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8120 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8121, file: !7976, line: 1117)
!8121 = !DISubprogram(name: "fmin", scope: !7973, file: !7973, line: 332, type: !7983, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8122 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8123, file: !7976, line: 1118)
!8123 = !DISubprogram(name: "fminf", scope: !7973, file: !7973, line: 332, type: !8066, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8124 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8125, file: !7976, line: 1119)
!8125 = !DISubprogram(name: "fminl", scope: !7973, file: !7973, line: 332, type: !8070, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8126 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8127, file: !7976, line: 1121)
!8127 = !DISubprogram(name: "hypot", scope: !7973, file: !7973, line: 147, type: !7983, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8128 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8129, file: !7976, line: 1122)
!8129 = !DISubprogram(name: "hypotf", scope: !7973, file: !7973, line: 147, type: !8066, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8130 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8131, file: !7976, line: 1123)
!8131 = !DISubprogram(name: "hypotl", scope: !7973, file: !7973, line: 147, type: !8070, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8132 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8133, file: !7976, line: 1125)
!8133 = !DISubprogram(name: "ilogb", scope: !7973, file: !7973, line: 280, type: !8134, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8134 = !DISubroutineType(types: !8135)
!8135 = !{!32, !7418}
!8136 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8137, file: !7976, line: 1126)
!8137 = !DISubprogram(name: "ilogbf", scope: !7973, file: !7973, line: 280, type: !8138, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8138 = !DISubroutineType(types: !8139)
!8139 = !{!32, !7425}
!8140 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8141, file: !7976, line: 1127)
!8141 = !DISubprogram(name: "ilogbl", scope: !7973, file: !7973, line: 280, type: !8142, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8142 = !DISubroutineType(types: !8143)
!8143 = !{!32, !7484}
!8144 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8145, file: !7976, line: 1129)
!8145 = !DISubprogram(name: "lgamma", scope: !7973, file: !7973, line: 230, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8146 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8147, file: !7976, line: 1130)
!8147 = !DISubprogram(name: "lgammaf", scope: !7973, file: !7973, line: 230, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8148 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8149, file: !7976, line: 1131)
!8149 = !DISubprogram(name: "lgammal", scope: !7973, file: !7973, line: 230, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8150 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8151, file: !7976, line: 1134)
!8151 = !DISubprogram(name: "llrint", scope: !7973, file: !7973, line: 316, type: !8152, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8152 = !DISubroutineType(types: !8153)
!8153 = !{!7489, !7418}
!8154 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8155, file: !7976, line: 1135)
!8155 = !DISubprogram(name: "llrintf", scope: !7973, file: !7973, line: 316, type: !8156, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8156 = !DISubroutineType(types: !8157)
!8157 = !{!7489, !7425}
!8158 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8159, file: !7976, line: 1136)
!8159 = !DISubprogram(name: "llrintl", scope: !7973, file: !7973, line: 316, type: !8160, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8160 = !DISubroutineType(types: !8161)
!8161 = !{!7489, !7484}
!8162 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8163, file: !7976, line: 1138)
!8163 = !DISubprogram(name: "llround", scope: !7973, file: !7973, line: 322, type: !8152, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8164 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8165, file: !7976, line: 1139)
!8165 = !DISubprogram(name: "llroundf", scope: !7973, file: !7973, line: 322, type: !8156, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8166 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8167, file: !7976, line: 1140)
!8167 = !DISubprogram(name: "llroundl", scope: !7973, file: !7973, line: 322, type: !8160, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8168 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8169, file: !7976, line: 1143)
!8169 = !DISubprogram(name: "log1p", scope: !7973, file: !7973, line: 122, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8170 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8171, file: !7976, line: 1144)
!8171 = !DISubprogram(name: "log1pf", scope: !7973, file: !7973, line: 122, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8172 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8173, file: !7976, line: 1145)
!8173 = !DISubprogram(name: "log1pl", scope: !7973, file: !7973, line: 122, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8174 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8175, file: !7976, line: 1147)
!8175 = !DISubprogram(name: "log2", scope: !7973, file: !7973, line: 133, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8176 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8177, file: !7976, line: 1148)
!8177 = !DISubprogram(name: "log2f", scope: !7973, file: !7973, line: 133, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8178 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8179, file: !7976, line: 1149)
!8179 = !DISubprogram(name: "log2l", scope: !7973, file: !7973, line: 133, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8180 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8181, file: !7976, line: 1151)
!8181 = !DISubprogram(name: "logb", scope: !7973, file: !7973, line: 125, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8182 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8183, file: !7976, line: 1152)
!8183 = !DISubprogram(name: "logbf", scope: !7973, file: !7973, line: 125, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8184 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8185, file: !7976, line: 1153)
!8185 = !DISubprogram(name: "logbl", scope: !7973, file: !7973, line: 125, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8186 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8187, file: !7976, line: 1155)
!8187 = !DISubprogram(name: "lrint", scope: !7973, file: !7973, line: 314, type: !8188, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8188 = !DISubroutineType(types: !8189)
!8189 = !{!288, !7418}
!8190 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8191, file: !7976, line: 1156)
!8191 = !DISubprogram(name: "lrintf", scope: !7973, file: !7973, line: 314, type: !8192, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8192 = !DISubroutineType(types: !8193)
!8193 = !{!288, !7425}
!8194 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8195, file: !7976, line: 1157)
!8195 = !DISubprogram(name: "lrintl", scope: !7973, file: !7973, line: 314, type: !8196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8196 = !DISubroutineType(types: !8197)
!8197 = !{!288, !7484}
!8198 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8199, file: !7976, line: 1159)
!8199 = !DISubprogram(name: "lround", scope: !7973, file: !7973, line: 320, type: !8188, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8200 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8201, file: !7976, line: 1160)
!8201 = !DISubprogram(name: "lroundf", scope: !7973, file: !7973, line: 320, type: !8192, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8202 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8203, file: !7976, line: 1161)
!8203 = !DISubprogram(name: "lroundl", scope: !7973, file: !7973, line: 320, type: !8196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8204 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8205, file: !7976, line: 1163)
!8205 = !DISubprogram(name: "nan", scope: !7973, file: !7973, line: 201, type: !7647, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8206 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8207, file: !7976, line: 1164)
!8207 = !DISubprogram(name: "nanf", scope: !7973, file: !7973, line: 201, type: !8208, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8208 = !DISubroutineType(types: !8209)
!8209 = !{!7425, !317}
!8210 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8211, file: !7976, line: 1165)
!8211 = !DISubprogram(name: "nanl", scope: !7973, file: !7973, line: 201, type: !8212, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8212 = !DISubroutineType(types: !8213)
!8213 = !{!7484, !317}
!8214 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8215, file: !7976, line: 1167)
!8215 = !DISubprogram(name: "nearbyint", scope: !7973, file: !7973, line: 294, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8216 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8217, file: !7976, line: 1168)
!8217 = !DISubprogram(name: "nearbyintf", scope: !7973, file: !7973, line: 294, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8218 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8219, file: !7976, line: 1169)
!8219 = !DISubprogram(name: "nearbyintl", scope: !7973, file: !7973, line: 294, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8220 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8221, file: !7976, line: 1171)
!8221 = !DISubprogram(name: "nextafter", scope: !7973, file: !7973, line: 259, type: !7983, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8222 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8223, file: !7976, line: 1172)
!8223 = !DISubprogram(name: "nextafterf", scope: !7973, file: !7973, line: 259, type: !8066, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8224 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8225, file: !7976, line: 1173)
!8225 = !DISubprogram(name: "nextafterl", scope: !7973, file: !7973, line: 259, type: !8070, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8226 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8227, file: !7976, line: 1175)
!8227 = !DISubprogram(name: "nexttoward", scope: !7973, file: !7973, line: 261, type: !8228, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8228 = !DISubroutineType(types: !8229)
!8229 = !{!7418, !7418, !7484}
!8230 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8231, file: !7976, line: 1176)
!8231 = !DISubprogram(name: "nexttowardf", scope: !7973, file: !7973, line: 261, type: !8232, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8232 = !DISubroutineType(types: !8233)
!8233 = !{!7425, !7425, !7484}
!8234 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8235, file: !7976, line: 1177)
!8235 = !DISubprogram(name: "nexttowardl", scope: !7973, file: !7973, line: 261, type: !8070, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8236 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8237, file: !7976, line: 1179)
!8237 = !DISubprogram(name: "remainder", scope: !7973, file: !7973, line: 272, type: !7983, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8238 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8239, file: !7976, line: 1180)
!8239 = !DISubprogram(name: "remainderf", scope: !7973, file: !7973, line: 272, type: !8066, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8240 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8241, file: !7976, line: 1181)
!8241 = !DISubprogram(name: "remainderl", scope: !7973, file: !7973, line: 272, type: !8070, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8242 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8243, file: !7976, line: 1183)
!8243 = !DISubprogram(name: "remquo", scope: !7973, file: !7973, line: 307, type: !8244, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8244 = !DISubroutineType(types: !8245)
!8245 = !{!7418, !7418, !7418, !8003}
!8246 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8247, file: !7976, line: 1184)
!8247 = !DISubprogram(name: "remquof", scope: !7973, file: !7973, line: 307, type: !8248, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8248 = !DISubroutineType(types: !8249)
!8249 = !{!7425, !7425, !7425, !8003}
!8250 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8251, file: !7976, line: 1185)
!8251 = !DISubprogram(name: "remquol", scope: !7973, file: !7973, line: 307, type: !8252, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8252 = !DISubroutineType(types: !8253)
!8253 = !{!7484, !7484, !7484, !8003}
!8254 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8255, file: !7976, line: 1187)
!8255 = !DISubprogram(name: "rint", scope: !7973, file: !7973, line: 256, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8256 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8257, file: !7976, line: 1188)
!8257 = !DISubprogram(name: "rintf", scope: !7973, file: !7973, line: 256, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8258 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8259, file: !7976, line: 1189)
!8259 = !DISubprogram(name: "rintl", scope: !7973, file: !7973, line: 256, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8260 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8261, file: !7976, line: 1191)
!8261 = !DISubprogram(name: "round", scope: !7973, file: !7973, line: 298, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8262 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8263, file: !7976, line: 1192)
!8263 = !DISubprogram(name: "roundf", scope: !7973, file: !7973, line: 298, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8264 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8265, file: !7976, line: 1193)
!8265 = !DISubprogram(name: "roundl", scope: !7973, file: !7973, line: 298, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8266 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8267, file: !7976, line: 1195)
!8267 = !DISubprogram(name: "scalbln", scope: !7973, file: !7973, line: 290, type: !8268, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8268 = !DISubroutineType(types: !8269)
!8269 = !{!7418, !7418, !288}
!8270 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8271, file: !7976, line: 1196)
!8271 = !DISubprogram(name: "scalblnf", scope: !7973, file: !7973, line: 290, type: !8272, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8272 = !DISubroutineType(types: !8273)
!8273 = !{!7425, !7425, !288}
!8274 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8275, file: !7976, line: 1197)
!8275 = !DISubprogram(name: "scalblnl", scope: !7973, file: !7973, line: 290, type: !8276, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8276 = !DISubroutineType(types: !8277)
!8277 = !{!7484, !7484, !288}
!8278 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8279, file: !7976, line: 1199)
!8279 = !DISubprogram(name: "scalbn", scope: !7973, file: !7973, line: 276, type: !8006, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8280 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8281, file: !7976, line: 1200)
!8281 = !DISubprogram(name: "scalbnf", scope: !7973, file: !7973, line: 276, type: !8282, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8282 = !DISubroutineType(types: !8283)
!8283 = !{!7425, !7425, !32}
!8284 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8285, file: !7976, line: 1201)
!8285 = !DISubprogram(name: "scalbnl", scope: !7973, file: !7973, line: 276, type: !8286, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8286 = !DISubroutineType(types: !8287)
!8287 = !{!7484, !7484, !32}
!8288 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8289, file: !7976, line: 1203)
!8289 = !DISubprogram(name: "tgamma", scope: !7973, file: !7973, line: 235, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8290 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8291, file: !7976, line: 1204)
!8291 = !DISubprogram(name: "tgammaf", scope: !7973, file: !7973, line: 235, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8292 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8293, file: !7976, line: 1205)
!8293 = !DISubprogram(name: "tgammal", scope: !7973, file: !7973, line: 235, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8294 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8295, file: !7976, line: 1207)
!8295 = !DISubprogram(name: "trunc", scope: !7973, file: !7973, line: 302, type: !7974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8296 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8297, file: !7976, line: 1208)
!8297 = !DISubprogram(name: "truncf", scope: !7973, file: !7973, line: 302, type: !8038, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8298 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8299, file: !7976, line: 1209)
!8299 = !DISubprogram(name: "truncl", scope: !7973, file: !7973, line: 302, type: !8042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8300 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8301, file: !8304, line: 56)
!8301 = !DIDerivedType(tag: DW_TAG_typedef, name: "max_align_t", file: !8302, line: 24, baseType: !8303)
!8302 = !DIFile(filename: "llvm5/build/lib/clang/15.0.3/include/__stddef_max_align_t.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "48e8e2456f77e6cda35d245130fa7259")
!8303 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !8302, line: 19, size: 256, flags: DIFlagFwdDecl, identifier: "_ZTS11max_align_t")
!8304 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstddef", directory: "")
!8305 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8306, file: !8310, line: 75)
!8306 = !DISubprogram(name: "memchr", scope: !8307, file: !8307, line: 90, type: !8308, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8307 = !DIFile(filename: "/usr/include/string.h", directory: "", checksumkind: CSK_MD5, checksum: "1029a2d94b0e7b73f8dbf87ca20ab7bc")
!8308 = !DISubroutineType(types: !8309)
!8309 = !{!154, !124, !32, !2102}
!8310 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstring", directory: "")
!8311 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8312, file: !8310, line: 76)
!8312 = !DISubprogram(name: "memcmp", scope: !8307, file: !8307, line: 63, type: !8313, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8313 = !DISubroutineType(types: !8314)
!8314 = !{!32, !124, !124, !2102}
!8315 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8316, file: !8310, line: 77)
!8316 = !DISubprogram(name: "memcpy", scope: !8307, file: !8307, line: 42, type: !8317, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8317 = !DISubroutineType(types: !8318)
!8318 = !{!154, !7857, !7882, !2102}
!8319 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8320, file: !8310, line: 78)
!8320 = !DISubprogram(name: "memmove", scope: !8307, file: !8307, line: 46, type: !8321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8321 = !DISubroutineType(types: !8322)
!8322 = !{!154, !154, !124, !2102}
!8323 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8324, file: !8310, line: 79)
!8324 = !DISubprogram(name: "memset", scope: !8307, file: !8307, line: 60, type: !8325, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8325 = !DISubroutineType(types: !8326)
!8326 = !{!154, !154, !32, !2102}
!8327 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8328, file: !8310, line: 80)
!8328 = !DISubprogram(name: "strcat", scope: !8307, file: !8307, line: 129, type: !8329, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8329 = !DISubroutineType(types: !8330)
!8330 = !{!1360, !7367, !7298}
!8331 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8332, file: !8310, line: 81)
!8332 = !DISubprogram(name: "strcmp", scope: !8307, file: !8307, line: 136, type: !7906, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8333 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8334, file: !8310, line: 82)
!8334 = !DISubprogram(name: "strcoll", scope: !8307, file: !8307, line: 143, type: !7906, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8335 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8336, file: !8310, line: 83)
!8336 = !DISubprogram(name: "strcpy", scope: !8307, file: !8307, line: 121, type: !8329, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8337 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8338, file: !8310, line: 84)
!8338 = !DISubprogram(name: "strcspn", scope: !8307, file: !8307, line: 272, type: !8339, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8339 = !DISubroutineType(types: !8340)
!8340 = !{!2102, !317, !317}
!8341 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8342, file: !8310, line: 85)
!8342 = !DISubprogram(name: "strerror", scope: !8307, file: !8307, line: 396, type: !8343, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8343 = !DISubroutineType(types: !8344)
!8344 = !{!1360, !32}
!8345 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8346, file: !8310, line: 86)
!8346 = !DISubprogram(name: "strlen", scope: !8307, file: !8307, line: 384, type: !8347, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8347 = !DISubroutineType(types: !8348)
!8348 = !{!2102, !317}
!8349 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8350, file: !8310, line: 87)
!8350 = !DISubprogram(name: "strncat", scope: !8307, file: !8307, line: 132, type: !8351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8351 = !DISubroutineType(types: !8352)
!8352 = !{!1360, !7367, !7298, !2102}
!8353 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8354, file: !8310, line: 88)
!8354 = !DISubprogram(name: "strncmp", scope: !8307, file: !8307, line: 139, type: !3105, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8355 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8356, file: !8310, line: 89)
!8356 = !DISubprogram(name: "strncpy", scope: !8307, file: !8307, line: 124, type: !8351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8357 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8358, file: !8310, line: 90)
!8358 = !DISubprogram(name: "strspn", scope: !8307, file: !8307, line: 276, type: !8339, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8359 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8360, file: !8310, line: 91)
!8360 = !DISubprogram(name: "strtok", scope: !8307, file: !8307, line: 335, type: !8329, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8361 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8362, file: !8310, line: 92)
!8362 = !DISubprogram(name: "strxfrm", scope: !8307, file: !8307, line: 146, type: !8363, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8363 = !DISubroutineType(types: !8364)
!8364 = !{!2102, !7367, !7298, !2102}
!8365 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8366, file: !8310, line: 93)
!8366 = !DISubprogram(name: "strchr", scope: !8307, file: !8307, line: 225, type: !8367, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8367 = !DISubroutineType(types: !8368)
!8368 = !{!1360, !317, !32}
!8369 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8370, file: !8310, line: 94)
!8370 = !DISubprogram(name: "strpbrk", scope: !8307, file: !8307, line: 302, type: !8371, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8371 = !DISubroutineType(types: !8372)
!8372 = !{!1360, !317, !317}
!8373 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8374, file: !8310, line: 95)
!8374 = !DISubprogram(name: "strrchr", scope: !8307, file: !8307, line: 252, type: !8367, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8375 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8376, file: !8310, line: 96)
!8376 = !DISubprogram(name: "strstr", scope: !8307, file: !8307, line: 329, type: !8371, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8377 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8378, file: !8382, line: 82)
!8378 = !DIDerivedType(tag: DW_TAG_typedef, name: "wctrans_t", file: !8379, line: 48, baseType: !8380)
!8379 = !DIFile(filename: "/usr/include/wctype.h", directory: "", checksumkind: CSK_MD5, checksum: "760693b7fbeea3d686e1f29058fc2257")
!8380 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !8381, size: 64)
!8381 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !7513)
!8382 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cwctype", directory: "")
!8383 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8384, file: !8382, line: 83)
!8384 = !DIDerivedType(tag: DW_TAG_typedef, name: "wctype_t", file: !8385, line: 38, baseType: !642)
!8385 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/wctype-wchar.h", directory: "", checksumkind: CSK_MD5, checksum: "45eef9c3aa1d99faffa3945ed9be039a")
!8386 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7204, file: !8382, line: 84)
!8387 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8388, file: !8382, line: 86)
!8388 = !DISubprogram(name: "iswalnum", scope: !8385, file: !8385, line: 95, type: !7444, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8389 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8390, file: !8382, line: 87)
!8390 = !DISubprogram(name: "iswalpha", scope: !8385, file: !8385, line: 101, type: !7444, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8391 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8392, file: !8382, line: 89)
!8392 = !DISubprogram(name: "iswblank", scope: !8385, file: !8385, line: 146, type: !7444, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8393 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8394, file: !8382, line: 91)
!8394 = !DISubprogram(name: "iswcntrl", scope: !8385, file: !8385, line: 104, type: !7444, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8395 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8396, file: !8382, line: 92)
!8396 = !DISubprogram(name: "iswctype", scope: !8385, file: !8385, line: 159, type: !8397, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8397 = !DISubroutineType(types: !8398)
!8398 = !{!32, !7204, !8384}
!8399 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8400, file: !8382, line: 93)
!8400 = !DISubprogram(name: "iswdigit", scope: !8385, file: !8385, line: 108, type: !7444, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8401 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8402, file: !8382, line: 94)
!8402 = !DISubprogram(name: "iswgraph", scope: !8385, file: !8385, line: 112, type: !7444, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8403 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8404, file: !8382, line: 95)
!8404 = !DISubprogram(name: "iswlower", scope: !8385, file: !8385, line: 117, type: !7444, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8405 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8406, file: !8382, line: 96)
!8406 = !DISubprogram(name: "iswprint", scope: !8385, file: !8385, line: 120, type: !7444, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8407 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8408, file: !8382, line: 97)
!8408 = !DISubprogram(name: "iswpunct", scope: !8385, file: !8385, line: 125, type: !7444, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8409 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8410, file: !8382, line: 98)
!8410 = !DISubprogram(name: "iswspace", scope: !8385, file: !8385, line: 130, type: !7444, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8411 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8412, file: !8382, line: 99)
!8412 = !DISubprogram(name: "iswupper", scope: !8385, file: !8385, line: 135, type: !7444, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8413 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8414, file: !8382, line: 100)
!8414 = !DISubprogram(name: "iswxdigit", scope: !8385, file: !8385, line: 140, type: !7444, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8415 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8416, file: !8382, line: 101)
!8416 = !DISubprogram(name: "towctrans", scope: !8379, file: !8379, line: 55, type: !8417, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8417 = !DISubroutineType(types: !8418)
!8418 = !{!7204, !7204, !8378}
!8419 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8420, file: !8382, line: 102)
!8420 = !DISubprogram(name: "towlower", scope: !8385, file: !8385, line: 166, type: !8421, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8421 = !DISubroutineType(types: !8422)
!8422 = !{!7204, !7204}
!8423 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8424, file: !8382, line: 103)
!8424 = !DISubprogram(name: "towupper", scope: !8385, file: !8385, line: 169, type: !8421, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8425 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8426, file: !8382, line: 104)
!8426 = !DISubprogram(name: "wctrans", scope: !8379, file: !8379, line: 52, type: !8427, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8427 = !DISubroutineType(types: !8428)
!8428 = !{!8378, !317}
!8429 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8430, file: !8382, line: 105)
!8430 = !DISubprogram(name: "wctype", scope: !8385, file: !8385, line: 155, type: !8431, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8431 = !DISubroutineType(types: !8432)
!8432 = !{!8384, !317}
!8433 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !3, file: !8434, line: 86)
!8434 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr_base.h", directory: "", checksumkind: CSK_MD5, checksum: "8405222f7806be9ab20595b5fcc527fd")
!8435 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8436, file: !8434, line: 87)
!8436 = !DIGlobalVariable(name: "__default_lock_policy", linkageName: "_ZN9__gnu_cxxL21__default_lock_policyE", scope: !5, file: !4, line: 53, type: !8437, isLocal: true, isDefinition: false)
!8437 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3)
!8438 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !14, entity: !8439, file: !366, line: 53)
!8439 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PassManagerBase", scope: !8440, file: !366, line: 51, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm6legacy15PassManagerBaseE")
!8440 = !DINamespace(name: "legacy", scope: !14)
!8441 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !14, entity: !8439, file: !8442, line: 39)
!8442 = !DIFile(filename: "llvm34/include/llvm/CodeGen/Passes.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "6ebcafaf100c7f53917c6d2820bd62e8")
!8443 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8444, file: !8447, line: 60)
!8444 = !DIDerivedType(tag: DW_TAG_typedef, name: "clock_t", file: !8445, line: 7, baseType: !8446)
!8445 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/clock_t.h", directory: "", checksumkind: CSK_MD5, checksum: "1aade99fd778d1551600c7ca1410b9f1")
!8446 = !DIDerivedType(tag: DW_TAG_typedef, name: "__clock_t", file: !287, line: 144, baseType: !288)
!8447 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ctime", directory: "")
!8448 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8449, file: !8447, line: 61)
!8449 = !DIDerivedType(tag: DW_TAG_typedef, name: "time_t", file: !8450, line: 7, baseType: !8451)
!8450 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/time_t.h", directory: "", checksumkind: CSK_MD5, checksum: "49b4e16ef1215de5afdbb283400ab90c")
!8451 = !DIDerivedType(tag: DW_TAG_typedef, name: "__time_t", file: !287, line: 148, baseType: !288)
!8452 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !7391, file: !8447, line: 62)
!8453 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8454, file: !8447, line: 64)
!8454 = !DISubprogram(name: "clock", scope: !8455, file: !8455, line: 72, type: !8456, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8455 = !DIFile(filename: "/usr/include/time.h", directory: "", checksumkind: CSK_MD5, checksum: "3b21b4c7d8bf3fafdb33a1c7ed8e024a")
!8456 = !DISubroutineType(types: !8457)
!8457 = !{!8444}
!8458 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8459, file: !8447, line: 65)
!8459 = !DISubprogram(name: "difftime", scope: !8455, file: !8455, line: 78, type: !8460, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8460 = !DISubroutineType(types: !8461)
!8461 = !{!7418, !8449, !8449}
!8462 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8463, file: !8447, line: 66)
!8463 = !DISubprogram(name: "mktime", scope: !8455, file: !8455, line: 82, type: !8464, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8464 = !DISubroutineType(types: !8465)
!8465 = !{!8449, !8466}
!8466 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7391, size: 64)
!8467 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8468, file: !8447, line: 67)
!8468 = !DISubprogram(name: "time", scope: !8455, file: !8455, line: 75, type: !8469, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8469 = !DISubroutineType(types: !8470)
!8470 = !{!8449, !8471}
!8471 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !8449, size: 64)
!8472 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8473, file: !8447, line: 68)
!8473 = !DISubprogram(name: "asctime", scope: !8455, file: !8455, line: 139, type: !8474, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8474 = !DISubroutineType(types: !8475)
!8475 = !{!1360, !7389}
!8476 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8477, file: !8447, line: 69)
!8477 = !DISubprogram(name: "ctime", scope: !8455, file: !8455, line: 142, type: !8478, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8478 = !DISubroutineType(types: !8479)
!8479 = !{!1360, !8480}
!8480 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !8481, size: 64)
!8481 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !8449)
!8482 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8483, file: !8447, line: 70)
!8483 = !DISubprogram(name: "gmtime", scope: !8455, file: !8455, line: 119, type: !8484, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8484 = !DISubroutineType(types: !8485)
!8485 = !{!8466, !8480}
!8486 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8487, file: !8447, line: 71)
!8487 = !DISubprogram(name: "localtime", scope: !8455, file: !8455, line: 123, type: !8484, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8488 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8489, file: !8447, line: 72)
!8489 = !DISubprogram(name: "strftime", scope: !8455, file: !8455, line: 88, type: !8490, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!8490 = !DISubroutineType(types: !8491)
!8491 = !{!2102, !7367, !2102, !7298, !7388}
!8492 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !839, entity: !8493, file: !8498, line: 55)
!8493 = !DIDerivedType(tag: DW_TAG_typedef, name: "va_list", file: !7805, line: 46, baseType: !8494)
!8494 = !DIDerivedType(tag: DW_TAG_typedef, name: "__gnuc_va_list", file: !8495, line: 32, baseType: !8496)
!8495 = !DIFile(filename: "llvm5/build/lib/clang/15.0.3/include/stdarg.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "4de3cbd931b589d291e5c39387aecf82")
!8496 = !DIDerivedType(tag: DW_TAG_typedef, name: "__builtin_va_list", file: !7343, baseType: !8497)
!8497 = !DICompositeType(tag: DW_TAG_array_type, baseType: !7340, size: 192, elements: !2696)
!8498 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdarg", directory: "")
!8499 = !DIImportedEntity(tag: DW_TAG_imported_module, scope: !0, entity: !14, file: !5058, line: 35)
!8500 = !{i32 7, !"Dwarf Version", i32 5}
!8501 = !{i32 2, !"Debug Info Version", i32 3}
!8502 = !{i32 1, !"wchar_size", i32 4}
!8503 = !{i32 7, !"PIC Level", i32 2}
!8504 = !{i32 7, !"uwtable", i32 2}
!8505 = !DILocalVariable(name: "PredTBB", scope: !8506, file: !5058, line: 679, type: !197)
!8506 = distinct !DILexicalBlock(scope: !8507, file: !5058, line: 670, column: 42)
!8507 = distinct !DILexicalBlock(scope: !8508, file: !5058, line: 669, column: 3)
!8508 = distinct !DILexicalBlock(scope: !8509, file: !5058, line: 669, column: 3)
!8509 = distinct !DISubprogram(name: "duplicateSimpleBB", linkageName: "_ZN12_GLOBAL__N_117TailDuplicatePass17duplicateSimpleBBEPN4llvm17MachineBasicBlockERNS1_15SmallVectorImplIS3_EERKNS1_8DenseSetIjNS1_12DenseMapInfoIjEEEERNS4_IPNS1_12MachineInstrEEE", scope: !5057, file: !5058, line: 660, type: !5614, scopeLine: 663, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !5613, retainedNodes: !8510)
!8510 = !{!8511, !8513, !8514, !8515, !8516, !8517, !8518, !8519, !8520, !8521, !8522, !8505, !8523, !8524, !8525, !8526, !8527}
!8511 = !DILocalVariable(name: "this", arg: 1, scope: !8509, type: !8512, flags: DIFlagArtificial | DIFlagObjectPointer)
!8512 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5057, size: 64)
!8513 = !DILocalVariable(name: "TailBB", arg: 2, scope: !8509, file: !5058, line: 660, type: !197)
!8514 = !DILocalVariable(name: "TDBBs", arg: 3, scope: !8509, file: !5058, line: 661, type: !4096)
!8515 = !DILocalVariable(name: "UsedByPhi", arg: 4, scope: !8509, file: !5058, line: 662, type: !5337)
!8516 = !DILocalVariable(name: "Copies", arg: 5, scope: !8509, file: !5058, line: 663, type: !5616)
!8517 = !DILocalVariable(name: "Succs", scope: !8509, file: !5058, line: 664, type: !117)
!8518 = !DILocalVariable(name: "Preds", scope: !8509, file: !5058, line: 666, type: !5510)
!8519 = !DILocalVariable(name: "Changed", scope: !8509, file: !5058, line: 668, type: !145)
!8520 = !DILocalVariable(name: "PI", scope: !8508, file: !5058, line: 669, type: !5559)
!8521 = !DILocalVariable(name: "PE", scope: !8508, file: !5058, line: 670, type: !5559)
!8522 = !DILocalVariable(name: "PredBB", scope: !8506, file: !5058, line: 671, type: !197)
!8523 = !DILocalVariable(name: "PredFBB", scope: !8506, file: !5058, line: 679, type: !197)
!8524 = !DILocalVariable(name: "PredCond", scope: !8506, file: !5058, line: 680, type: !5710)
!8525 = !DILocalVariable(name: "NewTarget", scope: !8506, file: !5058, line: 688, type: !197)
!8526 = !DILocalVariable(name: "NextBB", scope: !8506, file: !5058, line: 689, type: !197)
!8527 = !DILocalVariable(name: "NumSuccessors", scope: !8506, file: !5058, line: 725, type: !6)
!8528 = !DILocation(line: 0, scope: !8506)
