; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -o - -S --passes=simplifycfg | FileCheck %s
+; If we move a dbg.declare in performBranchToCommonDestFolding, it might have
+; dbg.values attached to it. Needs remapping too.
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: nocallback nofree nosync nounwind readnone speculatable willreturn
declare void @llvm.dbg.declare(metadata, metadata, metadata) #0

define linkonce_odr i64 @_ZNK4llvm6iplistINS_17MachineBasicBlockENS_12ilist_traitsIS1_EEE4sizeEv(ptr align 8 dereferenceable(16) %this, i1 %cmp) {
; CHECK-LABEL: @_ZNK4llvm6iplistINS_17MachineBasicBlockENS_12ilist_traitsIS1_EEE4sizeEv(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[THIS:%.*]], align 8
; CHECK-NEXT:    [[CMP_I_NOT2_I_I:%.*]] = icmp eq ptr null, null
; CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP:%.*]], [[CMP_I_NOT2_I_I]]
; CHECK-NEXT:    call void @llvm.dbg.value(metadata ptr [[TMP0]], metadata [[META4790:![0-9]+]], metadata !DIExpression()), !dbg [[DBG4806:![0-9]+]]
; CHECK-NEXT:    call void @llvm.dbg.declare(metadata ptr undef, metadata [[META4790]], metadata !DIExpression()), !dbg [[DBG4807:![0-9]+]]
; CHECK-NEXT:    br i1 [[OR_COND]], label [[RETURN:%.*]], label [[WHILE_BODY_I_I:%.*]]
; CHECK:       while.body.i.i:
; CHECK-NEXT:    br label [[WHILE_BODY_I_I]]
; CHECK:       return:
; CHECK-NEXT:    ret i64 0
;
entry:
  br i1 %cmp, label %return, label %if.end

if.end:                                           ; preds = %entry
  %0 = load ptr, ptr %this, align 8
  call void @llvm.dbg.value(metadata ptr %0, metadata !4790, metadata !DIExpression()), !dbg !4806
  call void @llvm.dbg.declare(metadata ptr undef, metadata !4790, metadata !DIExpression()), !dbg !4807
  %cmp.i.not2.i.i = icmp eq ptr null, null
  br i1 %cmp.i.not2.i.i, label %return, label %while.body.i.i

while.body.i.i:                                   ; preds = %while.body.i.i, %if.end
  br i1 false, label %return, label %while.body.i.i

return:                                           ; preds = %while.body.i.i, %if.end, %entry
  ret i64 0
}

; Function Attrs: nocallback nofree nosync nounwind readnone speculatable willreturn
declare void @llvm.dbg.value(metadata, metadata, metadata) #0

attributes #0 = { nocallback nofree nosync nounwind readnone speculatable willreturn }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!4785, !4786, !4787, !4788, !4789}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !329, globals: !2961, imports: !3467, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "/fast/fs/llvm34/lib/CodeGen/SlotIndexes.cpp", directory: "/fast/fs/build34llvm5", checksumkind: CSK_MD5, checksum: "f424b3c485923976c215b7f43a177ea6")
!2 = !{!3, !11, !244, !247, !257, !272, !280, !281, !289, !312, !318, !323}
!3 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "_Lock_policy", scope: !5, file: !4, line: 49, baseType: !6, size: 32, elements: !7, identifier: "_ZTSN9__gnu_cxx12_Lock_policyE")
!4 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/concurrence.h", directory: "")
!5 = !DINamespace(name: "__gnu_cxx", scope: null)
!6 = !DIBasicType(name: "unsigned int", size: 32, encoding: DW_ATE_unsigned)
!7 = !{!8, !9, !10}
!8 = !DIEnumerator(name: "_S_single", value: 0, isUnsigned: true)
!9 = !DIEnumerator(name: "_S_mutex", value: 1, isUnsigned: true)
!10 = !DIEnumerator(name: "_S_atomic", value: 2, isUnsigned: true)
!11 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "Slot", scope: !13, file: !12, line: 95, baseType: !6, size: 32, elements: !238, identifier: "_ZTSN4llvm9SlotIndex4SlotE")
!12 = !DIFile(filename: "llvm34/include/llvm/CodeGen/SlotIndexes.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "665b994cdfc886ca43d38fc00944e432")
!13 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SlotIndex", scope: !14, file: !12, line: 92, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !15, identifier: "_ZTSN4llvm9SlotIndexE")
!14 = !DINamespace(name: "llvm", scope: null)
!15 = !{!16, !170, !174, !179, !182, !185, !188, !192, !195, !196, !202, !205, !208, !209, !210, !211, !212, !213, !216, !217, !221, !222, !223, !224, !225, !226, !229, !230, !233, !234, !235, !236, !237}
!16 = !DIDerivedType(tag: DW_TAG_member, name: "lie", scope: !13, file: !12, line: 119, baseType: !17, size: 64)
!17 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerIntPair<llvm::IndexListEntry *, 2U, unsigned int, llvm::PointerLikeTypeTraits<llvm::IndexListEntry *> >", scope: !14, file: !18, line: 42, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !19, templateParams: !154, identifier: "_ZTSN4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEEE")
!18 = !DIFile(filename: "llvm34/include/llvm/ADT/PointerIntPair.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "d23f9b419341ab3c3120cccf3bee7cc2")
!19 = !{!20, !24, !28, !103, !106, !111, !114, !115, !118, !119, !120, !125, !129, !133, !136, !139, !144, !149, !150, !151, !152, !153}
!20 = !DIDerivedType(tag: DW_TAG_member, name: "Value", scope: !17, file: !18, line: 43, baseType: !21, size: 64)
!21 = !DIDerivedType(tag: DW_TAG_typedef, name: "intptr_t", file: !22, line: 97, baseType: !23)
!22 = !DIFile(filename: "/usr/include/stdint.h", directory: "", checksumkind: CSK_MD5, checksum: "c7469e3b87cb3d1a363efabd19f04208")
!23 = !DIBasicType(name: "long", size: 64, encoding: DW_ATE_signed)
!24 = !DISubprogram(name: "PointerIntPair", scope: !17, file: !18, line: 60, type: !25, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!25 = !DISubroutineType(types: !26)
!26 = !{null, !27}
!27 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !17, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!28 = !DISubprogram(name: "PointerIntPair", scope: !17, file: !18, line: 61, type: !29, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!29 = !DISubroutineType(types: !30)
!30 = !{null, !27, !31, !6}
!31 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !32, size: 64)
!32 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "IndexListEntry", scope: !14, file: !12, line: 38, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !33, identifier: "_ZTSN4llvm14IndexListEntryE")
!33 = !{!34, !81, !85, !86, !90, !94, !97, !100}
!34 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !32, baseType: !35, flags: DIFlagPublic, extraData: i32 0)
!35 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ilist_node<llvm::IndexListEntry>", scope: !14, file: !36, line: 43, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !37, templateParams: !59, identifier: "_ZTSN4llvm10ilist_nodeINS_14IndexListEntryEEE")
!36 = !DIFile(filename: "llvm34/include/llvm/ADT/ilist_node.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "938ee4ec9b54a94136a2a91548afee83")
!37 = !{!38, !61, !62, !66, !71, !74, !77, !78, !79, !80}
!38 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !35, baseType: !39, extraData: i32 0)
!39 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ilist_half_node<llvm::IndexListEntry>", scope: !14, file: !36, line: 26, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !40, templateParams: !59, identifier: "_ZTSN4llvm15ilist_half_nodeINS_14IndexListEntryEEE")
!40 = !{!41, !42, !46, !53, !56}
!41 = !DIDerivedType(tag: DW_TAG_member, name: "Prev", scope: !39, file: !36, line: 28, baseType: !31, size: 64)
!42 = !DISubprogram(name: "getPrev", linkageName: "_ZN4llvm15ilist_half_nodeINS_14IndexListEntryEE7getPrevEv", scope: !39, file: !36, line: 30, type: !43, scopeLine: 30, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!43 = !DISubroutineType(types: !44)
!44 = !{!31, !45}
!45 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !39, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!46 = !DISubprogram(name: "getPrev", linkageName: "_ZNK4llvm15ilist_half_nodeINS_14IndexListEntryEE7getPrevEv", scope: !39, file: !36, line: 31, type: !47, scopeLine: 31, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!47 = !DISubroutineType(types: !48)
!48 = !{!49, !51}
!49 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !50, size: 64)
!50 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !32)
!51 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !52, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!52 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !39)
!53 = !DISubprogram(name: "setPrev", linkageName: "_ZN4llvm15ilist_half_nodeINS_14IndexListEntryEE7setPrevEPS1_", scope: !39, file: !36, line: 32, type: !54, scopeLine: 32, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!54 = !DISubroutineType(types: !55)
!55 = !{null, !45, !31}
!56 = !DISubprogram(name: "ilist_half_node", scope: !39, file: !36, line: 33, type: !57, scopeLine: 33, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!57 = !DISubroutineType(types: !58)
!58 = !{null, !45}
!59 = !{!60}
!60 = !DITemplateTypeParameter(name: "NodeTy", type: !32)
!61 = !DIDerivedType(tag: DW_TAG_member, name: "Next", scope: !35, file: !36, line: 46, baseType: !31, size: 64, offset: 64)
!62 = !DISubprogram(name: "getNext", linkageName: "_ZN4llvm10ilist_nodeINS_14IndexListEntryEE7getNextEv", scope: !35, file: !36, line: 47, type: !63, scopeLine: 47, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!63 = !DISubroutineType(types: !64)
!64 = !{!31, !65}
!65 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !35, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!66 = !DISubprogram(name: "getNext", linkageName: "_ZNK4llvm10ilist_nodeINS_14IndexListEntryEE7getNextEv", scope: !35, file: !36, line: 48, type: !67, scopeLine: 48, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!67 = !DISubroutineType(types: !68)
!68 = !{!49, !69}
!69 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !70, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!70 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !35)
!71 = !DISubprogram(name: "setNext", linkageName: "_ZN4llvm10ilist_nodeINS_14IndexListEntryEE7setNextEPS1_", scope: !35, file: !36, line: 49, type: !72, scopeLine: 49, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!72 = !DISubroutineType(types: !73)
!73 = !{null, !65, !31}
!74 = !DISubprogram(name: "ilist_node", scope: !35, file: !36, line: 51, type: !75, scopeLine: 51, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!75 = !DISubroutineType(types: !76)
!76 = !{null, !65}
!77 = !DISubprogram(name: "getPrevNode", linkageName: "_ZN4llvm10ilist_nodeINS_14IndexListEntryEE11getPrevNodeEv", scope: !35, file: !36, line: 58, type: !63, scopeLine: 58, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!78 = !DISubprogram(name: "getPrevNode", linkageName: "_ZNK4llvm10ilist_nodeINS_14IndexListEntryEE11getPrevNodeEv", scope: !35, file: !36, line: 69, type: !67, scopeLine: 69, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!79 = !DISubprogram(name: "getNextNode", linkageName: "_ZN4llvm10ilist_nodeINS_14IndexListEntryEE11getNextNodeEv", scope: !35, file: !36, line: 80, type: !63, scopeLine: 80, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!80 = !DISubprogram(name: "getNextNode", linkageName: "_ZNK4llvm10ilist_nodeINS_14IndexListEntryEE11getNextNodeEv", scope: !35, file: !36, line: 91, type: !67, scopeLine: 91, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!81 = !DIDerivedType(tag: DW_TAG_member, name: "mi", scope: !32, file: !12, line: 39, baseType: !82, size: 64, offset: 128)
!82 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !83, size: 64)
!83 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MachineInstr", scope: !14, file: !84, line: 50, size: 512, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12MachineInstrE")
!84 = !DIFile(filename: "llvm34/include/llvm/CodeGen/MachineInstr.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "aa69bcafce289978b7ceed072d605684")
!85 = !DIDerivedType(tag: DW_TAG_member, name: "index", scope: !32, file: !12, line: 40, baseType: !6, size: 32, offset: 192)
!86 = !DISubprogram(name: "IndexListEntry", scope: !32, file: !12, line: 44, type: !87, scopeLine: 44, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!87 = !DISubroutineType(types: !88)
!88 = !{null, !89, !82, !6}
!89 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !32, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!90 = !DISubprogram(name: "getInstr", linkageName: "_ZNK4llvm14IndexListEntry8getInstrEv", scope: !32, file: !12, line: 46, type: !91, scopeLine: 46, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!91 = !DISubroutineType(types: !92)
!92 = !{!82, !93}
!93 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !50, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!94 = !DISubprogram(name: "setInstr", linkageName: "_ZN4llvm14IndexListEntry8setInstrEPNS_12MachineInstrE", scope: !32, file: !12, line: 47, type: !95, scopeLine: 47, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!95 = !DISubroutineType(types: !96)
!96 = !{null, !89, !82}
!97 = !DISubprogram(name: "getIndex", linkageName: "_ZNK4llvm14IndexListEntry8getIndexEv", scope: !32, file: !12, line: 51, type: !98, scopeLine: 51, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!98 = !DISubroutineType(types: !99)
!99 = !{!6, !93}
!100 = !DISubprogram(name: "setIndex", linkageName: "_ZN4llvm14IndexListEntry8setIndexEj", scope: !32, file: !12, line: 52, type: !101, scopeLine: 52, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!101 = !DISubroutineType(types: !102)
!102 = !{null, !89, !6}
!103 = !DISubprogram(name: "PointerIntPair", scope: !17, file: !18, line: 66, type: !104, scopeLine: 66, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!104 = !DISubroutineType(types: !105)
!105 = !{null, !27, !31}
!106 = !DISubprogram(name: "getPointer", linkageName: "_ZNK4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEE10getPointerEv", scope: !17, file: !18, line: 70, type: !107, scopeLine: 70, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!107 = !DISubroutineType(types: !108)
!108 = !{!31, !109}
!109 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !110, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!110 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !17)
!111 = !DISubprogram(name: "getInt", linkageName: "_ZNK4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEE6getIntEv", scope: !17, file: !18, line: 75, type: !112, scopeLine: 75, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!112 = !DISubroutineType(types: !113)
!113 = !{!6, !109}
!114 = !DISubprogram(name: "setPointer", linkageName: "_ZN4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEE10setPointerES2_", scope: !17, file: !18, line: 79, type: !104, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!115 = !DISubprogram(name: "setInt", linkageName: "_ZN4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEE6setIntEj", scope: !17, file: !18, line: 88, type: !116, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!116 = !DISubroutineType(types: !117)
!117 = !{null, !27, !6}
!118 = !DISubprogram(name: "initWithPointer", linkageName: "_ZN4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEE15initWithPointerES2_", scope: !17, file: !18, line: 97, type: !104, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!119 = !DISubprogram(name: "setPointerAndInt", linkageName: "_ZN4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEE16setPointerAndIntES2_j", scope: !17, file: !18, line: 105, type: !29, scopeLine: 105, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!120 = !DISubprogram(name: "getAddrOfPointer", linkageName: "_ZNK4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEE16getAddrOfPointerEv", scope: !17, file: !18, line: 116, type: !121, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!121 = !DISubroutineType(types: !122)
!122 = !{!123, !109}
!123 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !124, size: 64)
!124 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !31)
!125 = !DISubprogram(name: "getAddrOfPointer", linkageName: "_ZN4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEE16getAddrOfPointerEv", scope: !17, file: !18, line: 120, type: !126, scopeLine: 120, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!126 = !DISubroutineType(types: !127)
!127 = !{!128, !27}
!128 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !31, size: 64)
!129 = !DISubprogram(name: "getOpaqueValue", linkageName: "_ZNK4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEE14getOpaqueValueEv", scope: !17, file: !18, line: 127, type: !130, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!130 = !DISubroutineType(types: !131)
!131 = !{!132, !109}
!132 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 64)
!133 = !DISubprogram(name: "setFromOpaqueValue", linkageName: "_ZN4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEE18setFromOpaqueValueEPv", scope: !17, file: !18, line: 128, type: !134, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!134 = !DISubroutineType(types: !135)
!135 = !{null, !27, !132}
!136 = !DISubprogram(name: "getFromOpaqueValue", linkageName: "_ZN4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEE18getFromOpaqueValueEPv", scope: !17, file: !18, line: 130, type: !137, scopeLine: 130, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!137 = !DISubroutineType(types: !138)
!138 = !{!17, !132}
!139 = !DISubprogram(name: "getFromOpaqueValue", linkageName: "_ZN4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEE18getFromOpaqueValueEPKv", scope: !17, file: !18, line: 136, type: !140, scopeLine: 136, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!140 = !DISubroutineType(types: !141)
!141 = !{!17, !142}
!142 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !143, size: 64)
!143 = !DIDerivedType(tag: DW_TAG_const_type, baseType: null)
!144 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEEeqERKS5_", scope: !17, file: !18, line: 141, type: !145, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!145 = !DISubroutineType(types: !146)
!146 = !{!147, !109, !148}
!147 = !DIBasicType(name: "bool", size: 8, encoding: DW_ATE_boolean)
!148 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !110, size: 64)
!149 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEEneERKS5_", scope: !17, file: !18, line: 142, type: !145, scopeLine: 142, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!150 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEEltERKS5_", scope: !17, file: !18, line: 143, type: !145, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!151 = !DISubprogram(name: "operator>", linkageName: "_ZNK4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEEgtERKS5_", scope: !17, file: !18, line: 144, type: !145, scopeLine: 144, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!152 = !DISubprogram(name: "operator<=", linkageName: "_ZNK4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEEleERKS5_", scope: !17, file: !18, line: 145, type: !145, scopeLine: 145, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!153 = !DISubprogram(name: "operator>=", linkageName: "_ZNK4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEEgeERKS5_", scope: !17, file: !18, line: 146, type: !145, scopeLine: 146, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!154 = !{!155, !156, !157, !158}
!155 = !DITemplateTypeParameter(name: "PointerTy", type: !31)
!156 = !DITemplateValueParameter(name: "IntBits", type: !6, value: i32 2)
!157 = !DITemplateTypeParameter(name: "IntType", type: !6, defaulted: true)
!158 = !DITemplateTypeParameter(name: "PtrTraits", type: !159)
!159 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerLikeTypeTraits<llvm::IndexListEntry *>", scope: !14, file: !160, line: 34, size: 8, flags: DIFlagTypePassByValue, elements: !161, templateParams: !168, identifier: "_ZTSN4llvm21PointerLikeTypeTraitsIPNS_14IndexListEntryEEE")
!160 = !DIFile(filename: "llvm34/include/llvm/Support/PointerLikeTypeTraits.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "8333c3efd9cf0bb9b9cfe8a278228322")
!161 = !{!162, !165}
!162 = !DISubprogram(name: "getAsVoidPointer", linkageName: "_ZN4llvm21PointerLikeTypeTraitsIPNS_14IndexListEntryEE16getAsVoidPointerES2_", scope: !159, file: !160, line: 36, type: !163, scopeLine: 36, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!163 = !DISubroutineType(types: !164)
!164 = !{!132, !31}
!165 = !DISubprogram(name: "getFromVoidPointer", linkageName: "_ZN4llvm21PointerLikeTypeTraitsIPNS_14IndexListEntryEE18getFromVoidPointerEPv", scope: !159, file: !160, line: 37, type: !166, scopeLine: 37, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!166 = !DISubroutineType(types: !167)
!167 = !{!31, !132}
!168 = !{!169}
!169 = !DITemplateTypeParameter(name: "T", type: !31)
!170 = !DISubprogram(name: "SlotIndex", scope: !13, file: !12, line: 121, type: !171, scopeLine: 121, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!171 = !DISubroutineType(types: !172)
!172 = !{null, !173, !31, !6}
!173 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !13, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!174 = !DISubprogram(name: "listEntry", linkageName: "_ZNK4llvm9SlotIndex9listEntryEv", scope: !13, file: !12, line: 124, type: !175, scopeLine: 124, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!175 = !DISubroutineType(types: !176)
!176 = !{!31, !177}
!177 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !178, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!178 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !13)
!179 = !DISubprogram(name: "getIndex", linkageName: "_ZNK4llvm9SlotIndex8getIndexEv", scope: !13, file: !12, line: 133, type: !180, scopeLine: 133, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!180 = !DISubroutineType(types: !181)
!181 = !{!6, !177}
!182 = !DISubprogram(name: "getSlot", linkageName: "_ZNK4llvm9SlotIndex7getSlotEv", scope: !13, file: !12, line: 138, type: !183, scopeLine: 138, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!183 = !DISubroutineType(types: !184)
!184 = !{!11, !177}
!185 = !DISubprogram(name: "SlotIndex", scope: !13, file: !12, line: 150, type: !186, scopeLine: 150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!186 = !DISubroutineType(types: !187)
!187 = !{null, !173}
!188 = !DISubprogram(name: "SlotIndex", scope: !13, file: !12, line: 153, type: !189, scopeLine: 153, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!189 = !DISubroutineType(types: !190)
!190 = !{null, !173, !191, !11}
!191 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !178, size: 64)
!192 = !DISubprogram(name: "isValid", linkageName: "_ZNK4llvm9SlotIndex7isValidEv", scope: !13, file: !12, line: 160, type: !193, scopeLine: 160, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!193 = !DISubroutineType(types: !194)
!194 = !{!147, !177}
!195 = !DISubprogram(name: "operator bool", linkageName: "_ZNK4llvm9SlotIndexcvbEv", scope: !13, file: !12, line: 165, type: !193, scopeLine: 165, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!196 = !DISubprogram(name: "print", linkageName: "_ZNK4llvm9SlotIndex5printERNS_11raw_ostreamE", scope: !13, file: !12, line: 168, type: !197, scopeLine: 168, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!197 = !DISubroutineType(types: !198)
!198 = !{null, !177, !199}
!199 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !200, size: 64)
!200 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "raw_ostream", scope: !14, file: !201, line: 31, size: 320, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm11raw_ostreamE")
!201 = !DIFile(filename: "llvm34/include/llvm/Support/raw_ostream.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "2bb663449bd8797aa5193bb52a5154a0")
!202 = !DISubprogram(name: "dump", linkageName: "_ZNK4llvm9SlotIndex4dumpEv", scope: !13, file: !12, line: 171, type: !203, scopeLine: 171, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!203 = !DISubroutineType(types: !204)
!204 = !{null, !177}
!205 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm9SlotIndexeqES0_", scope: !13, file: !12, line: 174, type: !206, scopeLine: 174, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!206 = !DISubroutineType(types: !207)
!207 = !{!147, !177, !13}
!208 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm9SlotIndexneES0_", scope: !13, file: !12, line: 178, type: !206, scopeLine: 178, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!209 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm9SlotIndexltES0_", scope: !13, file: !12, line: 184, type: !206, scopeLine: 184, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!210 = !DISubprogram(name: "operator<=", linkageName: "_ZNK4llvm9SlotIndexleES0_", scope: !13, file: !12, line: 189, type: !206, scopeLine: 189, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!211 = !DISubprogram(name: "operator>", linkageName: "_ZNK4llvm9SlotIndexgtES0_", scope: !13, file: !12, line: 195, type: !206, scopeLine: 195, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!212 = !DISubprogram(name: "operator>=", linkageName: "_ZNK4llvm9SlotIndexgeES0_", scope: !13, file: !12, line: 201, type: !206, scopeLine: 201, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!213 = !DISubprogram(name: "isSameInstr", linkageName: "_ZN4llvm9SlotIndex11isSameInstrES0_S0_", scope: !13, file: !12, line: 206, type: !214, scopeLine: 206, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!214 = !DISubroutineType(types: !215)
!215 = !{!147, !13, !13}
!216 = !DISubprogram(name: "isEarlierInstr", linkageName: "_ZN4llvm9SlotIndex14isEarlierInstrES0_S0_", scope: !13, file: !12, line: 212, type: !214, scopeLine: 212, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!217 = !DISubprogram(name: "distance", linkageName: "_ZNK4llvm9SlotIndex8distanceES0_", scope: !13, file: !12, line: 217, type: !218, scopeLine: 217, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!218 = !DISubroutineType(types: !219)
!219 = !{!220, !177, !13}
!220 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!221 = !DISubprogram(name: "getInstrDistance", linkageName: "_ZNK4llvm9SlotIndex16getInstrDistanceES0_", scope: !13, file: !12, line: 223, type: !218, scopeLine: 223, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!222 = !DISubprogram(name: "isBlock", linkageName: "_ZNK4llvm9SlotIndex7isBlockEv", scope: !13, file: !12, line: 229, type: !193, scopeLine: 229, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!223 = !DISubprogram(name: "isEarlyClobber", linkageName: "_ZNK4llvm9SlotIndex14isEarlyClobberEv", scope: !13, file: !12, line: 232, type: !193, scopeLine: 232, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!224 = !DISubprogram(name: "isRegister", linkageName: "_ZNK4llvm9SlotIndex10isRegisterEv", scope: !13, file: !12, line: 236, type: !193, scopeLine: 236, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!225 = !DISubprogram(name: "isDead", linkageName: "_ZNK4llvm9SlotIndex6isDeadEv", scope: !13, file: !12, line: 239, type: !193, scopeLine: 239, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!226 = !DISubprogram(name: "getBaseIndex", linkageName: "_ZNK4llvm9SlotIndex12getBaseIndexEv", scope: !13, file: !12, line: 244, type: !227, scopeLine: 244, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!227 = !DISubroutineType(types: !228)
!228 = !{!13, !177}
!229 = !DISubprogram(name: "getBoundaryIndex", linkageName: "_ZNK4llvm9SlotIndex16getBoundaryIndexEv", scope: !13, file: !12, line: 251, type: !227, scopeLine: 251, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!230 = !DISubprogram(name: "getRegSlot", linkageName: "_ZNK4llvm9SlotIndex10getRegSlotEb", scope: !13, file: !12, line: 257, type: !231, scopeLine: 257, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!231 = !DISubroutineType(types: !232)
!232 = !{!13, !177, !147}
!233 = !DISubprogram(name: "getDeadSlot", linkageName: "_ZNK4llvm9SlotIndex11getDeadSlotEv", scope: !13, file: !12, line: 262, type: !227, scopeLine: 262, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!234 = !DISubprogram(name: "getNextSlot", linkageName: "_ZNK4llvm9SlotIndex11getNextSlotEv", scope: !13, file: !12, line: 272, type: !227, scopeLine: 272, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!235 = !DISubprogram(name: "getNextIndex", linkageName: "_ZNK4llvm9SlotIndex12getNextIndexEv", scope: !13, file: !12, line: 282, type: !227, scopeLine: 282, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!236 = !DISubprogram(name: "getPrevSlot", linkageName: "_ZNK4llvm9SlotIndex11getPrevSlotEv", scope: !13, file: !12, line: 292, type: !227, scopeLine: 292, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!237 = !DISubprogram(name: "getPrevIndex", linkageName: "_ZNK4llvm9SlotIndex12getPrevIndexEv", scope: !13, file: !12, line: 302, type: !227, scopeLine: 302, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!238 = !{!239, !240, !241, !242, !243}
!239 = !DIEnumerator(name: "Slot_Block", value: 0, isUnsigned: true)
!240 = !DIEnumerator(name: "Slot_EarlyClobber", value: 1, isUnsigned: true)
!241 = !DIEnumerator(name: "Slot_Register", value: 2, isUnsigned: true)
!242 = !DIEnumerator(name: "Slot_Dead", value: 3, isUnsigned: true)
!243 = !DIEnumerator(name: "Slot_Count", value: 4, isUnsigned: true)
!244 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !13, file: !12, line: 143, baseType: !6, size: 32, elements: !245, identifier: "_ZTSN4llvm9SlotIndexUt_E")
!245 = !{!246}
!246 = !DIEnumerator(name: "InstrDist", value: 16, isUnsigned: true)
!247 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "PassKind", scope: !14, file: !248, line: 67, baseType: !6, size: 32, elements: !249, identifier: "_ZTSN4llvm8PassKindE")
!248 = !DIFile(filename: "llvm34/include/llvm/Pass.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "46c927a21d41c0100f7ff76e01726dcc")
!249 = !{!250, !251, !252, !253, !254, !255, !256}
!250 = !DIEnumerator(name: "PT_BasicBlock", value: 0, isUnsigned: true)
!251 = !DIEnumerator(name: "PT_Region", value: 1, isUnsigned: true)
!252 = !DIEnumerator(name: "PT_Loop", value: 2, isUnsigned: true)
!253 = !DIEnumerator(name: "PT_Function", value: 3, isUnsigned: true)
!254 = !DIEnumerator(name: "PT_CallGraphSCC", value: 4, isUnsigned: true)
!255 = !DIEnumerator(name: "PT_Module", value: 5, isUnsigned: true)
!256 = !DIEnumerator(name: "PT_PassManager", value: 6, isUnsigned: true)
!257 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !258, file: !160, line: 62, baseType: !6, size: 32, elements: !270, identifier: "_ZTSN4llvm21PointerLikeTypeTraitsIPKNS_12MachineInstrEEUt_E")
!258 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerLikeTypeTraits<const llvm::MachineInstr *>", scope: !14, file: !160, line: 52, size: 8, flags: DIFlagTypePassByValue, elements: !259, templateParams: !268, identifier: "_ZTSN4llvm21PointerLikeTypeTraitsIPKNS_12MachineInstrEEE")
!259 = !{!260, !265}
!260 = !DISubprogram(name: "getAsVoidPointer", linkageName: "_ZN4llvm21PointerLikeTypeTraitsIPKNS_12MachineInstrEE16getAsVoidPointerES3_", scope: !258, file: !160, line: 56, type: !261, scopeLine: 56, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!261 = !DISubroutineType(types: !262)
!262 = !{!142, !263}
!263 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !264, size: 64)
!264 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !83)
!265 = !DISubprogram(name: "getFromVoidPointer", linkageName: "_ZN4llvm21PointerLikeTypeTraitsIPKNS_12MachineInstrEE18getFromVoidPointerEPKv", scope: !258, file: !160, line: 59, type: !266, scopeLine: 59, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!266 = !DISubroutineType(types: !267)
!267 = !{!263, !142}
!268 = !{!269}
!269 = !DITemplateTypeParameter(name: "T", type: !263)
!270 = !{!271}
!271 = !DIEnumerator(name: "NumLowBitsAvailable", value: 2, isUnsigned: true)
!272 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !274, file: !273, line: 39, baseType: !6, size: 32, elements: !278, identifier: "_ZTSN4llvm7AlignOfINS_14IndexListEntryEEUt_E")
!273 = !DIFile(filename: "llvm34/include/llvm/Support/AlignOf.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "55acc245b7ffca1b8660602cb703d9fb")
!274 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignOf<llvm::IndexListEntry>", scope: !14, file: !273, line: 38, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !276, identifier: "_ZTSN4llvm7AlignOfINS_14IndexListEntryEEE")
!275 = !{}
!276 = !{!277}
!277 = !DITemplateTypeParameter(name: "T", type: !32)
!278 = !{!279}
!279 = !DIEnumerator(name: "Alignment", value: 8, isUnsigned: true)
!280 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !159, file: !160, line: 47, baseType: !6, size: 32, elements: !270, identifier: "_ZTSN4llvm21PointerLikeTypeTraitsIPNS_14IndexListEntryEEUt_E")
!281 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !17, file: !18, line: 44, baseType: !282, size: 64, elements: !284, identifier: "_ZTSN4llvm14PointerIntPairIPNS_14IndexListEntryELj2EjNS_21PointerLikeTypeTraitsIS2_EEEUt_E")
!282 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintptr_t", file: !22, line: 100, baseType: !283)
!283 = !DIBasicType(name: "unsigned long", size: 64, encoding: DW_ATE_unsigned)
!284 = !{!285, !286, !287, !288}
!285 = !DIEnumerator(name: "PointerBitMask", value: 18446744073709551612, isUnsigned: true)
!286 = !DIEnumerator(name: "IntShift", value: 0, isUnsigned: true)
!287 = !DIEnumerator(name: "IntMask", value: 3, isUnsigned: true)
!288 = !DIEnumerator(name: "ShiftedIntMask", value: 3, isUnsigned: true)
!289 = !DICompositeType(tag: DW_TAG_enumeration_type, scope: !291, file: !290, line: 25, baseType: !6, size: 32, elements: !292)
!290 = !DIFile(filename: "llvm34/include/llvm/Target/TargetOpcodes.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "602cb86be2d0eacef1fa25536094b1a7")
!291 = !DINamespace(name: "TargetOpcode", scope: !14)
!292 = !{!293, !294, !295, !296, !297, !298, !299, !300, !301, !302, !303, !304, !305, !306, !307, !308, !309, !310, !311}
!293 = !DIEnumerator(name: "PHI", value: 0, isUnsigned: true)
!294 = !DIEnumerator(name: "INLINEASM", value: 1, isUnsigned: true)
!295 = !DIEnumerator(name: "PROLOG_LABEL", value: 2, isUnsigned: true)
!296 = !DIEnumerator(name: "EH_LABEL", value: 3, isUnsigned: true)
!297 = !DIEnumerator(name: "GC_LABEL", value: 4, isUnsigned: true)
!298 = !DIEnumerator(name: "KILL", value: 5, isUnsigned: true)
!299 = !DIEnumerator(name: "EXTRACT_SUBREG", value: 6, isUnsigned: true)
!300 = !DIEnumerator(name: "INSERT_SUBREG", value: 7, isUnsigned: true)
!301 = !DIEnumerator(name: "IMPLICIT_DEF", value: 8, isUnsigned: true)
!302 = !DIEnumerator(name: "SUBREG_TO_REG", value: 9, isUnsigned: true)
!303 = !DIEnumerator(name: "COPY_TO_REGCLASS", value: 10, isUnsigned: true)
!304 = !DIEnumerator(name: "DBG_VALUE", value: 11, isUnsigned: true)
!305 = !DIEnumerator(name: "REG_SEQUENCE", value: 12, isUnsigned: true)
!306 = !DIEnumerator(name: "COPY", value: 13, isUnsigned: true)
!307 = !DIEnumerator(name: "BUNDLE", value: 14, isUnsigned: true)
!308 = !DIEnumerator(name: "LIFETIME_START", value: 15, isUnsigned: true)
!309 = !DIEnumerator(name: "LIFETIME_END", value: 16, isUnsigned: true)
!310 = !DIEnumerator(name: "STACKMAP", value: 17, isUnsigned: true)
!311 = !DIEnumerator(name: "PATCHPOINT", value: 18, isUnsigned: true)
!312 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "MIFlag", scope: !83, file: !84, line: 62, baseType: !6, size: 32, elements: !313, identifier: "_ZTSN4llvm12MachineInstr6MIFlagE")
!313 = !{!314, !315, !316, !317}
!314 = !DIEnumerator(name: "NoFlags", value: 0, isUnsigned: true)
!315 = !DIEnumerator(name: "FrameSetup", value: 1, isUnsigned: true)
!316 = !DIEnumerator(name: "BundledPred", value: 2, isUnsigned: true)
!317 = !DIEnumerator(name: "BundledSucc", value: 4, isUnsigned: true)
!318 = !DICompositeType(tag: DW_TAG_enumeration_type, scope: !320, file: !319, line: 1875, baseType: !6, size: 32, elements: !321)
!319 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_algo.h", directory: "", checksumkind: CSK_MD5, checksum: "52ea3eafc6a0b82ae28b19432ed6df52")
!320 = !DINamespace(name: "std", scope: null)
!321 = !{!322}
!322 = !DIEnumerator(name: "_S_threshold", value: 16, isUnsigned: true)
!323 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "ZeroBehavior", scope: !14, file: !324, line: 30, baseType: !6, size: 32, elements: !325, identifier: "_ZTSN4llvm12ZeroBehaviorE")
!324 = !DIFile(filename: "llvm34/include/llvm/Support/MathExtras.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "dc2c2488e5b34ad60e03a667451851b1")
!325 = !{!326, !327, !328}
!326 = !DIEnumerator(name: "ZB_Undefined", value: 0, isUnsigned: true)
!327 = !DIEnumerator(name: "ZB_Max", value: 1, isUnsigned: true)
!328 = !DIEnumerator(name: "ZB_Width", value: 2, isUnsigned: true)
!329 = !{!147, !330, !31, !867, !1293, !1294, !282, !263, !1295, !6, !551, !1296, !1371, !1372, !21, !1432, !82, !1493, !283, !132, !1679, !11, !142, !1739, !1918, !1865, !2227, !1191, !2228, !220, !2368, !2310, !2410, !2374, !2317, !2087, !2426, !1784, !1781, !2429, !2848, !852, !2433, !1919, !1922, !39, !896, !892, !870, !1101, !1098, !873, !2476, !2479, !2482, !1741, !1744, !2242, !2239, !2595, !2598, !2601, !2229, !332, !346, !599, !350, !353, !375, !381, !1299, !32, !35, !1373, !13, !17, !1434, !2744, !2849, !2867, !1613, !1610, !983, !1680, !879, !1974, !2902, !2948, !2088}
!330 = !DIDerivedType(tag: DW_TAG_typedef, name: "NormalCtor_t", scope: !332, file: !331, line: 41, baseType: !864)
!331 = !DIFile(filename: "llvm34/include/llvm/PassSupport.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "3b8dc647f268ebac7a0cd4e4e69b5005")
!332 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PassInfo", scope: !14, file: !331, line: 39, size: 512, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !333, identifier: "_ZTSN4llvm8PassInfoE")
!333 = !{!334, !339, !340, !341, !343, !344, !345, !818, !819, !823, !826, !830, !831, !834, !837, !840, !841, !842, !845, !848, !853, !856, !859, !863}
!334 = !DIDerivedType(tag: DW_TAG_member, name: "PassName", scope: !332, file: !331, line: 44, baseType: !335, size: 64)
!335 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !336)
!336 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !337, size: 64)
!337 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !338)
!338 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
!339 = !DIDerivedType(tag: DW_TAG_member, name: "PassArgument", scope: !332, file: !331, line: 45, baseType: !335, size: 64, offset: 64)
!340 = !DIDerivedType(tag: DW_TAG_member, name: "PassID", scope: !332, file: !331, line: 46, baseType: !142, size: 64, offset: 128)
!341 = !DIDerivedType(tag: DW_TAG_member, name: "IsCFGOnlyPass", scope: !332, file: !331, line: 47, baseType: !342, size: 8, offset: 192)
!342 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !147)
!343 = !DIDerivedType(tag: DW_TAG_member, name: "IsAnalysis", scope: !332, file: !331, line: 48, baseType: !342, size: 8, offset: 200)
!344 = !DIDerivedType(tag: DW_TAG_member, name: "IsAnalysisGroup", scope: !332, file: !331, line: 49, baseType: !342, size: 8, offset: 208)
!345 = !DIDerivedType(tag: DW_TAG_member, name: "ItfImpl", scope: !332, file: !331, line: 50, baseType: !346, size: 192, offset: 256)
!346 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<const llvm::PassInfo *, std::allocator<const llvm::PassInfo *> >", scope: !320, file: !347, line: 339, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !348, templateParams: !537, identifier: "_ZTSSt6vectorIPKN4llvm8PassInfoESaIS3_EE")
!347 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h", directory: "", checksumkind: CSK_MD5, checksum: "ba305a1e10d49c66b3a70acbb63616a6")
!348 = !{!349, !538, !542, !548, !552, !558, !563, !567, !570, !573, !578, !579, !583, !586, !589, !592, !595, !656, !662, !663, !664, !669, !674, !675, !676, !677, !678, !679, !680, !683, !684, !687, !688, !689, !690, !693, !694, !702, !709, !712, !713, !714, !717, !720, !721, !722, !725, !728, !731, !735, !736, !739, !742, !745, !748, !751, !754, !757, !758, !759, !760, !761, !764, !765, !768, !769, !770, !774, !778, !781, !784, !802}
!349 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !346, baseType: !350, flags: DIFlagProtected, extraData: i32 0)
!350 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_base<const llvm::PassInfo *, std::allocator<const llvm::PassInfo *> >", scope: !320, file: !347, line: 81, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !351, templateParams: !537, identifier: "_ZTSSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE")
!351 = !{!352, !491, !496, !501, !505, !508, !513, !516, !519, !522, !526, !529, !530, !533, !536}
!352 = !DIDerivedType(tag: DW_TAG_member, name: "_M_impl", scope: !350, file: !347, line: 290, baseType: !353, size: 192)
!353 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_impl", scope: !350, file: !347, line: 88, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !354, identifier: "_ZTSNSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE12_Vector_implE")
!354 = !{!355, !469, !472, !473, !474, !478, !483, !487}
!355 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !353, baseType: !356, extraData: i32 0)
!356 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Tp_alloc_type", scope: !350, file: !347, line: 84, baseType: !357)
!357 = !DIDerivedType(tag: DW_TAG_typedef, name: "other", scope: !359, file: !358, line: 117, baseType: !468)
!358 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/alloc_traits.h", directory: "")
!359 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "rebind<const llvm::PassInfo *>", scope: !360, file: !358, line: 116, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !421, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E6rebindIS4_EE")
!360 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__alloc_traits<std::allocator<const llvm::PassInfo *>, const llvm::PassInfo *>", scope: !5, file: !358, line: 50, size: 8, flags: DIFlagTypePassByValue, elements: !361, templateParams: !466, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_EE")
!361 = !{!362, !452, !455, !459, !462, !463, !464, !465}
!362 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !360, baseType: !363, extraData: i32 0)
!363 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "allocator_traits<std::allocator<const llvm::PassInfo *> >", scope: !320, file: !364, line: 384, size: 8, flags: DIFlagTypePassByValue, elements: !365, templateParams: !450, identifier: "_ZTSSt16allocator_traitsISaIPKN4llvm8PassInfoEEE")
!364 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/alloc_traits.h", directory: "", checksumkind: CSK_MD5, checksum: "f7f651aab55acaadfc53aa53979a817c")
!365 = !{!366, !434, !438, !441, !447}
!366 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIPKN4llvm8PassInfoEEE8allocateERS4_m", scope: !363, file: !364, line: 435, type: !367, scopeLine: 435, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!367 = !DISubroutineType(types: !368)
!368 = !{!369, !373, !433}
!369 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !363, file: !364, line: 392, baseType: !370)
!370 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !371, size: 64)
!371 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !372, size: 64)
!372 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !332)
!373 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !374, size: 64)
!374 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !363, file: !364, line: 387, baseType: !375)
!375 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "allocator<const llvm::PassInfo *>", scope: !320, file: !376, line: 108, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !377, templateParams: !421, identifier: "_ZTSSaIPKN4llvm8PassInfoEE")
!376 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "9cafc7b584300736771313d46be845c3")
!377 = !{!378, !423, !427, !432}
!378 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !375, baseType: !379, flags: DIFlagPublic, extraData: i32 0)
!379 = !DIDerivedType(tag: DW_TAG_typedef, name: "__allocator_base<const llvm::PassInfo *>", scope: !320, file: !380, line: 48, baseType: !381)
!380 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8/bits/c++allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "9572fa47638d84b83d0311676a9766b8")
!381 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "new_allocator<const llvm::PassInfo *>", scope: !5, file: !382, line: 58, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !383, templateParams: !421, identifier: "_ZTSN9__gnu_cxx13new_allocatorIPKN4llvm8PassInfoEEE")
!382 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/new_allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "ece13daf300dfc0cac27dc2ea29129ca")
!383 = !{!384, !388, !393, !394, !401, !409, !415, !418}
!384 = !DISubprogram(name: "new_allocator", scope: !381, file: !382, line: 79, type: !385, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!385 = !DISubroutineType(types: !386)
!386 = !{null, !387}
!387 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !381, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!388 = !DISubprogram(name: "new_allocator", scope: !381, file: !382, line: 81, type: !389, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!389 = !DISubroutineType(types: !390)
!390 = !{null, !387, !391}
!391 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !392, size: 64)
!392 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !381)
!393 = !DISubprogram(name: "~new_allocator", scope: !381, file: !382, line: 86, type: !385, scopeLine: 86, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!394 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorIPKN4llvm8PassInfoEE7addressERS4_", scope: !381, file: !382, line: 89, type: !395, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!395 = !DISubroutineType(types: !396)
!396 = !{!397, !398, !399}
!397 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !381, file: !382, line: 63, baseType: !370)
!398 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !392, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!399 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !381, file: !382, line: 65, baseType: !400)
!400 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !371, size: 64)
!401 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorIPKN4llvm8PassInfoEE7addressERKS4_", scope: !381, file: !382, line: 93, type: !402, scopeLine: 93, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!402 = !DISubroutineType(types: !403)
!403 = !{!404, !398, !407}
!404 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !381, file: !382, line: 64, baseType: !405)
!405 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !406, size: 64)
!406 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !371)
!407 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !381, file: !382, line: 66, baseType: !408)
!408 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !406, size: 64)
!409 = !DISubprogram(name: "allocate", linkageName: "_ZN9__gnu_cxx13new_allocatorIPKN4llvm8PassInfoEE8allocateEmPKv", scope: !381, file: !382, line: 99, type: !410, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!410 = !DISubroutineType(types: !411)
!411 = !{!397, !387, !412, !142}
!412 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !382, line: 61, baseType: !413)
!413 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", scope: !320, file: !414, line: 238, baseType: !283)
!414 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8/bits/c++config.h", directory: "", checksumkind: CSK_MD5, checksum: "5ab2830680f5a52514c973f039a03c0a")
!415 = !DISubprogram(name: "deallocate", linkageName: "_ZN9__gnu_cxx13new_allocatorIPKN4llvm8PassInfoEE10deallocateEPS4_m", scope: !381, file: !382, line: 116, type: !416, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!416 = !DISubroutineType(types: !417)
!417 = !{null, !387, !397, !412}
!418 = !DISubprogram(name: "max_size", linkageName: "_ZNK9__gnu_cxx13new_allocatorIPKN4llvm8PassInfoEE8max_sizeEv", scope: !381, file: !382, line: 129, type: !419, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!419 = !DISubroutineType(types: !420)
!420 = !{!412, !398}
!421 = !{!422}
!422 = !DITemplateTypeParameter(name: "_Tp", type: !371)
!423 = !DISubprogram(name: "allocator", scope: !375, file: !376, line: 131, type: !424, scopeLine: 131, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!424 = !DISubroutineType(types: !425)
!425 = !{null, !426}
!426 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !375, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!427 = !DISubprogram(name: "allocator", scope: !375, file: !376, line: 133, type: !428, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!428 = !DISubroutineType(types: !429)
!429 = !{null, !426, !430}
!430 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !431, size: 64)
!431 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !375)
!432 = !DISubprogram(name: "~allocator", scope: !375, file: !376, line: 139, type: !424, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!433 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !364, line: 407, baseType: !413)
!434 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIPKN4llvm8PassInfoEEE8allocateERS4_mPKv", scope: !363, file: !364, line: 449, type: !435, scopeLine: 449, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!435 = !DISubroutineType(types: !436)
!436 = !{!369, !373, !433, !437}
!437 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_void_pointer", file: !364, line: 401, baseType: !142)
!438 = !DISubprogram(name: "deallocate", linkageName: "_ZNSt16allocator_traitsISaIPKN4llvm8PassInfoEEE10deallocateERS4_PS3_m", scope: !363, file: !364, line: 461, type: !439, scopeLine: 461, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!439 = !DISubroutineType(types: !440)
!440 = !{null, !373, !369, !433}
!441 = !DISubprogram(name: "max_size", linkageName: "_ZNSt16allocator_traitsISaIPKN4llvm8PassInfoEEE8max_sizeERKS4_", scope: !363, file: !364, line: 495, type: !442, scopeLine: 495, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!442 = !DISubroutineType(types: !443)
!443 = !{!444, !445}
!444 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !363, file: !364, line: 407, baseType: !413)
!445 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !446, size: 64)
!446 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !374)
!447 = !DISubprogram(name: "select_on_container_copy_construction", linkageName: "_ZNSt16allocator_traitsISaIPKN4llvm8PassInfoEEE37select_on_container_copy_constructionERKS4_", scope: !363, file: !364, line: 504, type: !448, scopeLine: 504, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!448 = !DISubroutineType(types: !449)
!449 = !{!374, !445}
!450 = !{!451}
!451 = !DITemplateTypeParameter(name: "_Alloc", type: !375)
!452 = !DISubprogram(name: "_S_select_on_copy", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E17_S_select_on_copyERKS5_", scope: !360, file: !358, line: 94, type: !453, scopeLine: 94, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!453 = !DISubroutineType(types: !454)
!454 = !{!375, !430}
!455 = !DISubprogram(name: "_S_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E10_S_on_swapERS5_S7_", scope: !360, file: !358, line: 97, type: !456, scopeLine: 97, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!456 = !DISubroutineType(types: !457)
!457 = !{null, !458, !458}
!458 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !375, size: 64)
!459 = !DISubprogram(name: "_S_propagate_on_copy_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E27_S_propagate_on_copy_assignEv", scope: !360, file: !358, line: 100, type: !460, scopeLine: 100, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!460 = !DISubroutineType(types: !461)
!461 = !{!147}
!462 = !DISubprogram(name: "_S_propagate_on_move_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E27_S_propagate_on_move_assignEv", scope: !360, file: !358, line: 103, type: !460, scopeLine: 103, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!463 = !DISubprogram(name: "_S_propagate_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E20_S_propagate_on_swapEv", scope: !360, file: !358, line: 106, type: !460, scopeLine: 106, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!464 = !DISubprogram(name: "_S_always_equal", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E15_S_always_equalEv", scope: !360, file: !358, line: 109, type: !460, scopeLine: 109, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!465 = !DISubprogram(name: "_S_nothrow_move", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPKN4llvm8PassInfoEES4_E15_S_nothrow_moveEv", scope: !360, file: !358, line: 112, type: !460, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!466 = !{!451, !467}
!467 = !DITemplateTypeParameter(type: !371)
!468 = !DIDerivedType(tag: DW_TAG_typedef, name: "rebind_alloc<const llvm::PassInfo *>", scope: !363, file: !364, line: 422, baseType: !375)
!469 = !DIDerivedType(tag: DW_TAG_member, name: "_M_start", scope: !353, file: !347, line: 91, baseType: !470, size: 64)
!470 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !350, file: !347, line: 86, baseType: !471)
!471 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !360, file: !358, line: 59, baseType: !369)
!472 = !DIDerivedType(tag: DW_TAG_member, name: "_M_finish", scope: !353, file: !347, line: 92, baseType: !470, size: 64, offset: 64)
!473 = !DIDerivedType(tag: DW_TAG_member, name: "_M_end_of_storage", scope: !353, file: !347, line: 93, baseType: !470, size: 64, offset: 128)
!474 = !DISubprogram(name: "_Vector_impl", scope: !353, file: !347, line: 95, type: !475, scopeLine: 95, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!475 = !DISubroutineType(types: !476)
!476 = !{null, !477}
!477 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !353, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!478 = !DISubprogram(name: "_Vector_impl", scope: !353, file: !347, line: 99, type: !479, scopeLine: 99, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!479 = !DISubroutineType(types: !480)
!480 = !{null, !477, !481}
!481 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !482, size: 64)
!482 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !356)
!483 = !DISubprogram(name: "_Vector_impl", scope: !353, file: !347, line: 104, type: !484, scopeLine: 104, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!484 = !DISubroutineType(types: !485)
!485 = !{null, !477, !486}
!486 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !356, size: 64)
!487 = !DISubprogram(name: "_M_swap_data", linkageName: "_ZNSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE12_Vector_impl12_M_swap_dataERS6_", scope: !353, file: !347, line: 110, type: !488, scopeLine: 110, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!488 = !DISubroutineType(types: !489)
!489 = !{null, !477, !490}
!490 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !353, size: 64)
!491 = !DISubprogram(name: "_M_get_Tp_allocator", linkageName: "_ZNSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE19_M_get_Tp_allocatorEv", scope: !350, file: !347, line: 237, type: !492, scopeLine: 237, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!492 = !DISubroutineType(types: !493)
!493 = !{!494, !495}
!494 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !356, size: 64)
!495 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !350, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!496 = !DISubprogram(name: "_M_get_Tp_allocator", linkageName: "_ZNKSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE19_M_get_Tp_allocatorEv", scope: !350, file: !347, line: 241, type: !497, scopeLine: 241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!497 = !DISubroutineType(types: !498)
!498 = !{!481, !499}
!499 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !500, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!500 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !350)
!501 = !DISubprogram(name: "get_allocator", linkageName: "_ZNKSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE13get_allocatorEv", scope: !350, file: !347, line: 245, type: !502, scopeLine: 245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!502 = !DISubroutineType(types: !503)
!503 = !{!504, !499}
!504 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !350, file: !347, line: 234, baseType: !375)
!505 = !DISubprogram(name: "_Vector_base", scope: !350, file: !347, line: 248, type: !506, scopeLine: 248, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!506 = !DISubroutineType(types: !507)
!507 = !{null, !495}
!508 = !DISubprogram(name: "_Vector_base", scope: !350, file: !347, line: 251, type: !509, scopeLine: 251, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!509 = !DISubroutineType(types: !510)
!510 = !{null, !495, !511}
!511 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !512, size: 64)
!512 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !504)
!513 = !DISubprogram(name: "_Vector_base", scope: !350, file: !347, line: 254, type: !514, scopeLine: 254, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!514 = !DISubroutineType(types: !515)
!515 = !{null, !495, !413}
!516 = !DISubprogram(name: "_Vector_base", scope: !350, file: !347, line: 258, type: !517, scopeLine: 258, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!517 = !DISubroutineType(types: !518)
!518 = !{null, !495, !413, !511}
!519 = !DISubprogram(name: "_Vector_base", scope: !350, file: !347, line: 263, type: !520, scopeLine: 263, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!520 = !DISubroutineType(types: !521)
!521 = !{null, !495, !486}
!522 = !DISubprogram(name: "_Vector_base", scope: !350, file: !347, line: 266, type: !523, scopeLine: 266, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!523 = !DISubroutineType(types: !524)
!524 = !{null, !495, !525}
!525 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !350, size: 64)
!526 = !DISubprogram(name: "_Vector_base", scope: !350, file: !347, line: 270, type: !527, scopeLine: 270, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!527 = !DISubroutineType(types: !528)
!528 = !{null, !495, !525, !511}
!529 = !DISubprogram(name: "~_Vector_base", scope: !350, file: !347, line: 283, type: !506, scopeLine: 283, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!530 = !DISubprogram(name: "_M_allocate", linkageName: "_ZNSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE11_M_allocateEm", scope: !350, file: !347, line: 293, type: !531, scopeLine: 293, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!531 = !DISubroutineType(types: !532)
!532 = !{!470, !495, !413}
!533 = !DISubprogram(name: "_M_deallocate", linkageName: "_ZNSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE13_M_deallocateEPS3_m", scope: !350, file: !347, line: 300, type: !534, scopeLine: 300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!534 = !DISubroutineType(types: !535)
!535 = !{null, !495, !470, !413}
!536 = !DISubprogram(name: "_M_create_storage", linkageName: "_ZNSt12_Vector_baseIPKN4llvm8PassInfoESaIS3_EE17_M_create_storageEm", scope: !350, file: !347, line: 309, type: !514, scopeLine: 309, flags: DIFlagPrivate | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!537 = !{!422, !451}
!538 = !DISubprogram(name: "vector", scope: !346, file: !347, line: 391, type: !539, scopeLine: 391, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!539 = !DISubroutineType(types: !540)
!540 = !{null, !541}
!541 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !346, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!542 = !DISubprogram(name: "vector", scope: !346, file: !347, line: 402, type: !543, scopeLine: 402, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!543 = !DISubroutineType(types: !544)
!544 = !{null, !541, !545}
!545 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !546, size: 64)
!546 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !547)
!547 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !346, file: !347, line: 376, baseType: !375)
!548 = !DISubprogram(name: "vector", scope: !346, file: !347, line: 415, type: !549, scopeLine: 415, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!549 = !DISubroutineType(types: !550)
!550 = !{null, !541, !551, !545}
!551 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !347, line: 374, baseType: !413)
!552 = !DISubprogram(name: "vector", scope: !346, file: !347, line: 427, type: !553, scopeLine: 427, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!553 = !DISubroutineType(types: !554)
!554 = !{null, !541, !551, !555, !545}
!555 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !556, size: 64)
!556 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !557)
!557 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !346, file: !347, line: 364, baseType: !371)
!558 = !DISubprogram(name: "vector", scope: !346, file: !347, line: 458, type: !559, scopeLine: 458, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!559 = !DISubroutineType(types: !560)
!560 = !{null, !541, !561}
!561 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !562, size: 64)
!562 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !346)
!563 = !DISubprogram(name: "vector", scope: !346, file: !347, line: 476, type: !564, scopeLine: 476, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!564 = !DISubroutineType(types: !565)
!565 = !{null, !541, !566}
!566 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !346, size: 64)
!567 = !DISubprogram(name: "vector", scope: !346, file: !347, line: 480, type: !568, scopeLine: 480, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!568 = !DISubroutineType(types: !569)
!569 = !{null, !541, !561, !545}
!570 = !DISubprogram(name: "vector", scope: !346, file: !347, line: 490, type: !571, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!571 = !DISubroutineType(types: !572)
!572 = !{null, !541, !566, !545}
!573 = !DISubprogram(name: "vector", scope: !346, file: !347, line: 515, type: !574, scopeLine: 515, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!574 = !DISubroutineType(types: !575)
!575 = !{null, !541, !576, !545}
!576 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<const llvm::PassInfo *>", scope: !320, file: !577, line: 47, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listIPKN4llvm8PassInfoEE")
!577 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/initializer_list", directory: "")
!578 = !DISubprogram(name: "~vector", scope: !346, file: !347, line: 565, type: !539, scopeLine: 565, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!579 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EEaSERKS5_", scope: !346, file: !347, line: 582, type: !580, scopeLine: 582, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!580 = !DISubroutineType(types: !581)
!581 = !{!582, !541, !561}
!582 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !346, size: 64)
!583 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EEaSEOS5_", scope: !346, file: !347, line: 596, type: !584, scopeLine: 596, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!584 = !DISubroutineType(types: !585)
!585 = !{!582, !541, !566}
!586 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EEaSESt16initializer_listIS3_E", scope: !346, file: !347, line: 617, type: !587, scopeLine: 617, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!587 = !DISubroutineType(types: !588)
!588 = !{!582, !541, !576}
!589 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6assignEmRKS3_", scope: !346, file: !347, line: 636, type: !590, scopeLine: 636, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!590 = !DISubroutineType(types: !591)
!591 = !{null, !541, !551, !555}
!592 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6assignESt16initializer_listIS3_E", scope: !346, file: !347, line: 681, type: !593, scopeLine: 681, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!593 = !DISubroutineType(types: !594)
!594 = !{null, !541, !576}
!595 = !DISubprogram(name: "begin", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE5beginEv", scope: !346, file: !347, line: 698, type: !596, scopeLine: 698, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!596 = !DISubroutineType(types: !597)
!597 = !{!598, !541}
!598 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !346, file: !347, line: 369, baseType: !599)
!599 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<const llvm::PassInfo **, std::vector<const llvm::PassInfo *, std::allocator<const llvm::PassInfo *> > >", scope: !5, file: !600, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !601, templateParams: !654, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEE")
!600 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_iterator.h", directory: "", checksumkind: CSK_MD5, checksum: "43ca426be47f2e0c5f7f184d7d27a436")
!601 = !{!602, !603, !607, !612, !623, !628, !632, !635, !636, !637, !643, !646, !649, !650, !651}
!602 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !599, file: !600, line: 767, baseType: !370, size: 64, flags: DIFlagProtected)
!603 = !DISubprogram(name: "__normal_iterator", scope: !599, file: !600, line: 779, type: !604, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!604 = !DISubroutineType(types: !605)
!605 = !{null, !606}
!606 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !599, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!607 = !DISubprogram(name: "__normal_iterator", scope: !599, file: !600, line: 783, type: !608, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!608 = !DISubroutineType(types: !609)
!609 = !{null, !606, !610}
!610 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !611, size: 64)
!611 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !370)
!612 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEdeEv", scope: !599, file: !600, line: 796, type: !613, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!613 = !DISubroutineType(types: !614)
!614 = !{!615, !621}
!615 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !599, file: !600, line: 776, baseType: !616)
!616 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !618, file: !617, line: 184, baseType: !400)
!617 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_iterator_base_types.h", directory: "")
!618 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<const llvm::PassInfo **>", scope: !320, file: !617, line: 178, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !619, identifier: "_ZTSSt15iterator_traitsIPPKN4llvm8PassInfoEE")
!619 = !{!620}
!620 = !DITemplateTypeParameter(name: "_Iterator", type: !370)
!621 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !622, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!622 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !599)
!623 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEptEv", scope: !599, file: !600, line: 800, type: !624, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!624 = !DISubroutineType(types: !625)
!625 = !{!626, !621}
!626 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !599, file: !600, line: 777, baseType: !627)
!627 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !618, file: !617, line: 183, baseType: !370)
!628 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEppEv", scope: !599, file: !600, line: 804, type: !629, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!629 = !DISubroutineType(types: !630)
!630 = !{!631, !606}
!631 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !599, size: 64)
!632 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEppEi", scope: !599, file: !600, line: 811, type: !633, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!633 = !DISubroutineType(types: !634)
!634 = !{!599, !606, !220}
!635 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEmmEv", scope: !599, file: !600, line: 816, type: !629, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!636 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEmmEi", scope: !599, file: !600, line: 823, type: !633, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!637 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEixEl", scope: !599, file: !600, line: 828, type: !638, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!638 = !DISubroutineType(types: !639)
!639 = !{!615, !621, !640}
!640 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !599, file: !600, line: 775, baseType: !641)
!641 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !618, file: !617, line: 182, baseType: !642)
!642 = !DIDerivedType(tag: DW_TAG_typedef, name: "ptrdiff_t", scope: !320, file: !414, line: 239, baseType: !23)
!643 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEpLEl", scope: !599, file: !600, line: 832, type: !644, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!644 = !DISubroutineType(types: !645)
!645 = !{!631, !606, !640}
!646 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEplEl", scope: !599, file: !600, line: 836, type: !647, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!647 = !DISubroutineType(types: !648)
!648 = !{!599, !621, !640}
!649 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEmIEl", scope: !599, file: !600, line: 840, type: !644, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!650 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEmiEl", scope: !599, file: !600, line: 844, type: !647, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!651 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEE4baseEv", scope: !599, file: !600, line: 848, type: !652, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!652 = !DISubroutineType(types: !653)
!653 = !{!610, !621}
!654 = !{!620, !655}
!655 = !DITemplateTypeParameter(name: "_Container", type: !346)
!656 = !DISubprogram(name: "begin", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE5beginEv", scope: !346, file: !347, line: 707, type: !657, scopeLine: 707, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!657 = !DISubroutineType(types: !658)
!658 = !{!659, !661}
!659 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !346, file: !347, line: 371, baseType: !660)
!660 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<const llvm::PassInfo *const *, std::vector<const llvm::PassInfo *, std::allocator<const llvm::PassInfo *> > >", scope: !5, file: !600, line: 764, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPKPKN4llvm8PassInfoESt6vectorIS4_SaIS4_EEEE")
!661 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !562, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!662 = !DISubprogram(name: "end", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE3endEv", scope: !346, file: !347, line: 716, type: !596, scopeLine: 716, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!663 = !DISubprogram(name: "end", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE3endEv", scope: !346, file: !347, line: 725, type: !657, scopeLine: 725, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!664 = !DISubprogram(name: "rbegin", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6rbeginEv", scope: !346, file: !347, line: 734, type: !665, scopeLine: 734, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!665 = !DISubroutineType(types: !666)
!666 = !{!667, !541}
!667 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !346, file: !347, line: 373, baseType: !668)
!668 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<const llvm::PassInfo **, std::vector<const llvm::PassInfo *, std::allocator<const llvm::PassInfo *> > > >", scope: !320, file: !600, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPPKN4llvm8PassInfoESt6vectorIS5_SaIS5_EEEEE")
!669 = !DISubprogram(name: "rbegin", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE6rbeginEv", scope: !346, file: !347, line: 743, type: !670, scopeLine: 743, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!670 = !DISubroutineType(types: !671)
!671 = !{!672, !661}
!672 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !346, file: !347, line: 372, baseType: !673)
!673 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<const llvm::PassInfo *const *, std::vector<const llvm::PassInfo *, std::allocator<const llvm::PassInfo *> > > >", scope: !320, file: !600, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPKPKN4llvm8PassInfoESt6vectorIS5_SaIS5_EEEEE")
!674 = !DISubprogram(name: "rend", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE4rendEv", scope: !346, file: !347, line: 752, type: !665, scopeLine: 752, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!675 = !DISubprogram(name: "rend", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE4rendEv", scope: !346, file: !347, line: 761, type: !670, scopeLine: 761, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!676 = !DISubprogram(name: "cbegin", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE6cbeginEv", scope: !346, file: !347, line: 771, type: !657, scopeLine: 771, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!677 = !DISubprogram(name: "cend", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE4cendEv", scope: !346, file: !347, line: 780, type: !657, scopeLine: 780, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!678 = !DISubprogram(name: "crbegin", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE7crbeginEv", scope: !346, file: !347, line: 789, type: !670, scopeLine: 789, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!679 = !DISubprogram(name: "crend", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE5crendEv", scope: !346, file: !347, line: 798, type: !670, scopeLine: 798, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!680 = !DISubprogram(name: "size", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE4sizeEv", scope: !346, file: !347, line: 805, type: !681, scopeLine: 805, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!681 = !DISubroutineType(types: !682)
!682 = !{!551, !661}
!683 = !DISubprogram(name: "max_size", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE8max_sizeEv", scope: !346, file: !347, line: 810, type: !681, scopeLine: 810, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!684 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6resizeEm", scope: !346, file: !347, line: 824, type: !685, scopeLine: 824, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!685 = !DISubroutineType(types: !686)
!686 = !{null, !541, !551}
!687 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6resizeEmRKS3_", scope: !346, file: !347, line: 844, type: !590, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!688 = !DISubprogram(name: "shrink_to_fit", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE13shrink_to_fitEv", scope: !346, file: !347, line: 876, type: !539, scopeLine: 876, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!689 = !DISubprogram(name: "capacity", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE8capacityEv", scope: !346, file: !347, line: 885, type: !681, scopeLine: 885, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!690 = !DISubprogram(name: "empty", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE5emptyEv", scope: !346, file: !347, line: 894, type: !691, scopeLine: 894, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!691 = !DISubroutineType(types: !692)
!692 = !{!147, !661}
!693 = !DISubprogram(name: "reserve", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE7reserveEm", scope: !346, file: !347, line: 915, type: !685, scopeLine: 915, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!694 = !DISubprogram(name: "operator[]", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EEixEm", scope: !346, file: !347, line: 930, type: !695, scopeLine: 930, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!695 = !DISubroutineType(types: !696)
!696 = !{!697, !541, !551}
!697 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !346, file: !347, line: 367, baseType: !698)
!698 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !360, file: !358, line: 64, baseType: !699)
!699 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !700, size: 64)
!700 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !360, file: !358, line: 58, baseType: !701)
!701 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !363, file: !364, line: 389, baseType: !371)
!702 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EEixEm", scope: !346, file: !347, line: 948, type: !703, scopeLine: 948, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!703 = !DISubroutineType(types: !704)
!704 = !{!705, !661, !551}
!705 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !346, file: !347, line: 368, baseType: !706)
!706 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !360, file: !358, line: 65, baseType: !707)
!707 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !708, size: 64)
!708 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !700)
!709 = !DISubprogram(name: "_M_range_check", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE14_M_range_checkEm", scope: !346, file: !347, line: 957, type: !710, scopeLine: 957, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!710 = !DISubroutineType(types: !711)
!711 = !{null, !661, !551}
!712 = !DISubprogram(name: "at", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE2atEm", scope: !346, file: !347, line: 979, type: !695, scopeLine: 979, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!713 = !DISubprogram(name: "at", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE2atEm", scope: !346, file: !347, line: 997, type: !703, scopeLine: 997, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!714 = !DISubprogram(name: "front", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE5frontEv", scope: !346, file: !347, line: 1008, type: !715, scopeLine: 1008, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!715 = !DISubroutineType(types: !716)
!716 = !{!697, !541}
!717 = !DISubprogram(name: "front", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE5frontEv", scope: !346, file: !347, line: 1019, type: !718, scopeLine: 1019, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!718 = !DISubroutineType(types: !719)
!719 = !{!705, !661}
!720 = !DISubprogram(name: "back", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE4backEv", scope: !346, file: !347, line: 1030, type: !715, scopeLine: 1030, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!721 = !DISubprogram(name: "back", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE4backEv", scope: !346, file: !347, line: 1041, type: !718, scopeLine: 1041, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!722 = !DISubprogram(name: "data", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE4dataEv", scope: !346, file: !347, line: 1055, type: !723, scopeLine: 1055, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!723 = !DISubroutineType(types: !724)
!724 = !{!370, !541}
!725 = !DISubprogram(name: "data", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE4dataEv", scope: !346, file: !347, line: 1059, type: !726, scopeLine: 1059, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!726 = !DISubroutineType(types: !727)
!727 = !{!405, !661}
!728 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE9push_backERKS3_", scope: !346, file: !347, line: 1074, type: !729, scopeLine: 1074, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!729 = !DISubroutineType(types: !730)
!730 = !{null, !541, !555}
!731 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE9push_backEOS3_", scope: !346, file: !347, line: 1090, type: !732, scopeLine: 1090, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!732 = !DISubroutineType(types: !733)
!733 = !{null, !541, !734}
!734 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !557, size: 64)
!735 = !DISubprogram(name: "pop_back", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE8pop_backEv", scope: !346, file: !347, line: 1112, type: !539, scopeLine: 1112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!736 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EERS8_", scope: !346, file: !347, line: 1150, type: !737, scopeLine: 1150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!737 = !DISubroutineType(types: !738)
!738 = !{!598, !541, !659, !555}
!739 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EEOS3_", scope: !346, file: !347, line: 1180, type: !740, scopeLine: 1180, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!740 = !DISubroutineType(types: !741)
!741 = !{!598, !541, !659, !734}
!742 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EESt16initializer_listIS3_E", scope: !346, file: !347, line: 1197, type: !743, scopeLine: 1197, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!743 = !DISubroutineType(types: !744)
!744 = !{!598, !541, !659, !576}
!745 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EEmRS8_", scope: !346, file: !347, line: 1222, type: !746, scopeLine: 1222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!746 = !DISubroutineType(types: !747)
!747 = !{!598, !541, !659, !551, !555}
!748 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE5eraseEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EE", scope: !346, file: !347, line: 1317, type: !749, scopeLine: 1317, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!749 = !DISubroutineType(types: !750)
!750 = !{!598, !541, !659}
!751 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE5eraseEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EESA_", scope: !346, file: !347, line: 1344, type: !752, scopeLine: 1344, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!752 = !DISubroutineType(types: !753)
!753 = !{!598, !541, !659, !659}
!754 = !DISubprogram(name: "swap", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE4swapERS5_", scope: !346, file: !347, line: 1367, type: !755, scopeLine: 1367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!755 = !DISubroutineType(types: !756)
!756 = !{null, !541, !582}
!757 = !DISubprogram(name: "clear", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE5clearEv", scope: !346, file: !347, line: 1385, type: !539, scopeLine: 1385, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!758 = !DISubprogram(name: "_M_fill_initialize", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE18_M_fill_initializeEmRKS3_", scope: !346, file: !347, line: 1477, type: !590, scopeLine: 1477, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!759 = !DISubprogram(name: "_M_default_initialize", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE21_M_default_initializeEm", scope: !346, file: !347, line: 1487, type: !685, scopeLine: 1487, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!760 = !DISubprogram(name: "_M_fill_assign", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE14_M_fill_assignEmRKS3_", scope: !346, file: !347, line: 1529, type: !590, scopeLine: 1529, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!761 = !DISubprogram(name: "_M_fill_insert", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS3_S5_EEmRKS3_", scope: !346, file: !347, line: 1568, type: !762, scopeLine: 1568, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!762 = !DISubroutineType(types: !763)
!763 = !{null, !541, !598, !551, !555}
!764 = !DISubprogram(name: "_M_default_append", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE17_M_default_appendEm", scope: !346, file: !347, line: 1573, type: !685, scopeLine: 1573, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!765 = !DISubprogram(name: "_M_shrink_to_fit", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE16_M_shrink_to_fitEv", scope: !346, file: !347, line: 1576, type: !766, scopeLine: 1576, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!766 = !DISubroutineType(types: !767)
!767 = !{!147, !541}
!768 = !DISubprogram(name: "_M_insert_rval", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE14_M_insert_rvalEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EEOS3_", scope: !346, file: !347, line: 1625, type: !740, scopeLine: 1625, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!769 = !DISubprogram(name: "_M_emplace_aux", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE14_M_emplace_auxEN9__gnu_cxx17__normal_iteratorIPKS3_S5_EEOS3_", scope: !346, file: !347, line: 1634, type: !740, scopeLine: 1634, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!770 = !DISubprogram(name: "_M_check_len", linkageName: "_ZNKSt6vectorIPKN4llvm8PassInfoESaIS3_EE12_M_check_lenEmPKc", scope: !346, file: !347, line: 1640, type: !771, scopeLine: 1640, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!771 = !DISubroutineType(types: !772)
!772 = !{!773, !661, !551, !336}
!773 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !346, file: !347, line: 374, baseType: !413)
!774 = !DISubprogram(name: "_M_erase_at_end", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE15_M_erase_at_endEPS3_", scope: !346, file: !347, line: 1654, type: !775, scopeLine: 1654, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!775 = !DISubroutineType(types: !776)
!776 = !{null, !541, !777}
!777 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !346, file: !347, line: 365, baseType: !470)
!778 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE8_M_eraseEN9__gnu_cxx17__normal_iteratorIPS3_S5_EE", scope: !346, file: !347, line: 1666, type: !779, scopeLine: 1666, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!779 = !DISubroutineType(types: !780)
!780 = !{!598, !541, !598}
!781 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE8_M_eraseEN9__gnu_cxx17__normal_iteratorIPS3_S5_EES9_", scope: !346, file: !347, line: 1669, type: !782, scopeLine: 1669, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!782 = !DISubroutineType(types: !783)
!783 = !{!598, !541, !598, !598}
!784 = !DISubprogram(name: "_M_move_assign", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE14_M_move_assignEOS5_St17integral_constantIbLb1EE", scope: !346, file: !347, line: 1677, type: !785, scopeLine: 1677, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!785 = !DISubroutineType(types: !786)
!786 = !{null, !541, !566, !787}
!787 = !DIDerivedType(tag: DW_TAG_typedef, name: "true_type", scope: !320, file: !788, line: 75, baseType: !789)
!788 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/type_traits", directory: "")
!789 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "integral_constant<bool, true>", scope: !320, file: !788, line: 57, size: 8, flags: DIFlagTypePassByValue, elements: !790, templateParams: !799, identifier: "_ZTSSt17integral_constantIbLb1EE")
!790 = !{!791, !792, !798}
!791 = !DIDerivedType(tag: DW_TAG_member, name: "value", scope: !789, file: !788, line: 59, baseType: !342, flags: DIFlagStaticMember, extraData: i1 true)
!792 = !DISubprogram(name: "operator bool", linkageName: "_ZNKSt17integral_constantIbLb1EEcvbEv", scope: !789, file: !788, line: 62, type: !793, scopeLine: 62, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!793 = !DISubroutineType(types: !794)
!794 = !{!795, !796}
!795 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !789, file: !788, line: 60, baseType: !147)
!796 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !797, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!797 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !789)
!798 = !DISubprogram(name: "operator()", linkageName: "_ZNKSt17integral_constantIbLb1EEclEv", scope: !789, file: !788, line: 67, type: !793, scopeLine: 67, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!799 = !{!800, !801}
!800 = !DITemplateTypeParameter(name: "_Tp", type: !147)
!801 = !DITemplateValueParameter(name: "__v", type: !147, value: i8 1)
!802 = !DISubprogram(name: "_M_move_assign", linkageName: "_ZNSt6vectorIPKN4llvm8PassInfoESaIS3_EE14_M_move_assignEOS5_St17integral_constantIbLb0EE", scope: !346, file: !347, line: 1688, type: !803, scopeLine: 1688, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!803 = !DISubroutineType(types: !804)
!804 = !{null, !541, !566, !805}
!805 = !DIDerivedType(tag: DW_TAG_typedef, name: "false_type", scope: !320, file: !788, line: 78, baseType: !806)
!806 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "integral_constant<bool, false>", scope: !320, file: !788, line: 57, size: 8, flags: DIFlagTypePassByValue, elements: !807, templateParams: !816, identifier: "_ZTSSt17integral_constantIbLb0EE")
!807 = !{!808, !809, !815}
!808 = !DIDerivedType(tag: DW_TAG_member, name: "value", scope: !806, file: !788, line: 59, baseType: !342, flags: DIFlagStaticMember, extraData: i1 false)
!809 = !DISubprogram(name: "operator bool", linkageName: "_ZNKSt17integral_constantIbLb0EEcvbEv", scope: !806, file: !788, line: 62, type: !810, scopeLine: 62, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!810 = !DISubroutineType(types: !811)
!811 = !{!812, !813}
!812 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !806, file: !788, line: 60, baseType: !147)
!813 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !814, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!814 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !806)
!815 = !DISubprogram(name: "operator()", linkageName: "_ZNKSt17integral_constantIbLb0EEclEv", scope: !806, file: !788, line: 67, type: !810, scopeLine: 67, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!816 = !{!800, !817}
!817 = !DITemplateValueParameter(name: "__v", type: !147, value: i8 0)
!818 = !DIDerivedType(tag: DW_TAG_member, name: "NormalCtor", scope: !332, file: !331, line: 52, baseType: !330, size: 64, offset: 448)
!819 = !DISubprogram(name: "PassInfo", scope: !332, file: !331, line: 57, type: !820, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!820 = !DISubroutineType(types: !821)
!821 = !{null, !822, !336, !336, !142, !330, !147, !147}
!822 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !332, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!823 = !DISubprogram(name: "PassInfo", scope: !332, file: !331, line: 65, type: !824, scopeLine: 65, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!824 = !DISubroutineType(types: !825)
!825 = !{null, !822, !336, !142}
!826 = !DISubprogram(name: "getPassName", linkageName: "_ZNK4llvm8PassInfo11getPassNameEv", scope: !332, file: !331, line: 72, type: !827, scopeLine: 72, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!827 = !DISubroutineType(types: !828)
!828 = !{!336, !829}
!829 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !372, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!830 = !DISubprogram(name: "getPassArgument", linkageName: "_ZNK4llvm8PassInfo15getPassArgumentEv", scope: !332, file: !331, line: 78, type: !827, scopeLine: 78, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!831 = !DISubprogram(name: "getTypeInfo", linkageName: "_ZNK4llvm8PassInfo11getTypeInfoEv", scope: !332, file: !331, line: 82, type: !832, scopeLine: 82, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!832 = !DISubroutineType(types: !833)
!833 = !{!142, !829}
!834 = !DISubprogram(name: "isPassID", linkageName: "_ZNK4llvm8PassInfo8isPassIDEPKv", scope: !332, file: !331, line: 85, type: !835, scopeLine: 85, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!835 = !DISubroutineType(types: !836)
!836 = !{!147, !829, !142}
!837 = !DISubprogram(name: "isAnalysisGroup", linkageName: "_ZNK4llvm8PassInfo15isAnalysisGroupEv", scope: !332, file: !331, line: 92, type: !838, scopeLine: 92, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!838 = !DISubroutineType(types: !839)
!839 = !{!147, !829}
!840 = !DISubprogram(name: "isAnalysis", linkageName: "_ZNK4llvm8PassInfo10isAnalysisEv", scope: !332, file: !331, line: 93, type: !838, scopeLine: 93, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!841 = !DISubprogram(name: "isCFGOnlyPass", linkageName: "_ZNK4llvm8PassInfo13isCFGOnlyPassEv", scope: !332, file: !331, line: 97, type: !838, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!842 = !DISubprogram(name: "getNormalCtor", linkageName: "_ZNK4llvm8PassInfo13getNormalCtorEv", scope: !332, file: !331, line: 103, type: !843, scopeLine: 103, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!843 = !DISubroutineType(types: !844)
!844 = !{!330, !829}
!845 = !DISubprogram(name: "setNormalCtor", linkageName: "_ZN4llvm8PassInfo13setNormalCtorEPFPNS_4PassEvE", scope: !332, file: !331, line: 106, type: !846, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!846 = !DISubroutineType(types: !847)
!847 = !{null, !822, !330}
!848 = !DISubprogram(name: "createPass", linkageName: "_ZNK4llvm8PassInfo10createPassEv", scope: !332, file: !331, line: 111, type: !849, scopeLine: 111, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!849 = !DISubroutineType(types: !850)
!850 = !{!851, !829}
!851 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !852, size: 64)
!852 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Pass", scope: !14, file: !248, line: 82, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm4PassE")
!853 = !DISubprogram(name: "addInterfaceImplemented", linkageName: "_ZN4llvm8PassInfo23addInterfaceImplementedEPKS0_", scope: !332, file: !331, line: 117, type: !854, scopeLine: 117, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!854 = !DISubroutineType(types: !855)
!855 = !{null, !822, !371}
!856 = !DISubprogram(name: "getInterfacesImplemented", linkageName: "_ZNK4llvm8PassInfo24getInterfacesImplementedEv", scope: !332, file: !331, line: 124, type: !857, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!857 = !DISubroutineType(types: !858)
!858 = !{!561, !829}
!859 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8PassInfoaSERKS0_", scope: !332, file: !331, line: 129, type: !860, scopeLine: 129, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!860 = !DISubroutineType(types: !861)
!861 = !{null, !822, !862}
!862 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !372, size: 64)
!863 = !DISubprogram(name: "PassInfo", scope: !332, file: !331, line: 130, type: !860, scopeLine: 130, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!864 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !865, size: 64)
!865 = !DISubroutineType(types: !866)
!866 = !{!851}
!867 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !868, size: 64)
!868 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !870, file: !869, line: 540, baseType: !1167)
!869 = !DIFile(filename: "llvm34/include/llvm/ADT/DenseMap.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e4a1c2d5b55fe605534e57bb36c4fe71")
!870 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMap<const llvm::MachineInstr *, llvm::SlotIndex, llvm::DenseMapInfo<const llvm::MachineInstr *> >", scope: !14, file: !869, line: 534, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !871, templateParams: !1292, identifier: "_ZTSN4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEEE")
!871 = !{!872, !1244, !1245, !1246, !1247, !1248, !1252, !1257, !1261, !1264, !1268, !1271, !1274, !1275, !1276, !1277, !1278, !1282, !1283, !1284, !1285, !1288, !1289}
!872 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !870, baseType: !873, flags: DIFlagPublic, extraData: i32 0)
!873 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapBase<llvm::DenseMap<const llvm::MachineInstr *, llvm::SlotIndex, llvm::DenseMapInfo<const llvm::MachineInstr *> >, const llvm::MachineInstr *, llvm::SlotIndex, llvm::DenseMapInfo<const llvm::MachineInstr *> >", scope: !14, file: !869, line: 41, size: 8, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !874, templateParams: !1242, identifier: "_ZTSN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_EE")
!874 = !{!875, !1059, !1060, !1066, !1067, !1070, !1073, !1078, !1081, !1086, !1089, !1092, !1095, !1153, !1156, !1159, !1162, !1168, !1172, !1176, !1179, !1182, !1185, !1186, !1187, !1188, !1192, !1196, !1199, !1202, !1203, !1204, !1207, !1208, !1209, !1210, !1211, !1212, !1213, !1218, !1221, !1222, !1223, !1224, !1225, !1226, !1229, !1233, !1236, !1239}
!875 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E5beginEv", scope: !873, file: !869, line: 53, type: !876, scopeLine: 53, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!876 = !DISubroutineType(types: !877)
!877 = !{!878, !1058}
!878 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !873, file: !869, line: 50, baseType: !879)
!879 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapIterator<const llvm::MachineInstr *, llvm::SlotIndex, llvm::DenseMapInfo<const llvm::MachineInstr *>, false>", scope: !14, file: !869, line: 987, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !880, templateParams: !1056, identifier: "_ZTSN4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb0EEE")
!880 = !{!881, !955, !956, !960, !963, !968, !974, !977, !1047, !1048, !1052, !1055}
!881 = !DIDerivedType(tag: DW_TAG_member, name: "Ptr", scope: !879, file: !869, line: 999, baseType: !882, size: 64)
!882 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !879, file: !869, line: 995, baseType: !883)
!883 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !884, size: 64)
!884 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !879, file: !869, line: 994, baseType: !885)
!885 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !887, file: !886, line: 236, baseType: !892)
!886 = !DIFile(filename: "llvm34/include/llvm/Support/type_traits.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "3b111e0adbb374a4c7fc591de906379a")
!887 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<false, const std::pair<const llvm::MachineInstr *, llvm::SlotIndex>, std::pair<const llvm::MachineInstr *, llvm::SlotIndex> >", scope: !14, file: !886, line: 236, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !888, identifier: "_ZTSN4llvm11conditionalILb0EKSt4pairIPKNS_12MachineInstrENS_9SlotIndexEES6_EE")
!888 = !{!889, !890, !954}
!889 = !DITemplateValueParameter(type: !147, value: i8 0)
!890 = !DITemplateTypeParameter(name: "T", type: !891)
!891 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !892)
!892 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<const llvm::MachineInstr *, llvm::SlotIndex>", scope: !320, file: !893, line: 208, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !894, templateParams: !951, identifier: "_ZTSSt4pairIPKN4llvm12MachineInstrENS0_9SlotIndexEE")
!893 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_pair.h", directory: "", checksumkind: CSK_MD5, checksum: "9a7996187125e471e26ca57a6c9f4c5e")
!894 = !{!895, !915, !916, !917, !922, !926, !939, !948}
!895 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !892, baseType: !896, flags: DIFlagPrivate, extraData: i32 0)
!896 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<const llvm::MachineInstr *, llvm::SlotIndex>", scope: !320, file: !893, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !897, templateParams: !912, identifier: "_ZTSSt11__pair_baseIPKN4llvm12MachineInstrENS0_9SlotIndexEE")
!897 = !{!898, !902, !903, !908}
!898 = !DISubprogram(name: "__pair_base", scope: !896, file: !893, line: 194, type: !899, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!899 = !DISubroutineType(types: !900)
!900 = !{null, !901}
!901 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !896, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!902 = !DISubprogram(name: "~__pair_base", scope: !896, file: !893, line: 195, type: !899, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!903 = !DISubprogram(name: "__pair_base", scope: !896, file: !893, line: 196, type: !904, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!904 = !DISubroutineType(types: !905)
!905 = !{null, !901, !906}
!906 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !907, size: 64)
!907 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !896)
!908 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIPKN4llvm12MachineInstrENS0_9SlotIndexEEaSERKS5_", scope: !896, file: !893, line: 197, type: !909, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!909 = !DISubroutineType(types: !910)
!910 = !{!911, !901, !906}
!911 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !896, size: 64)
!912 = !{!913, !914}
!913 = !DITemplateTypeParameter(name: "_U1", type: !263)
!914 = !DITemplateTypeParameter(name: "_U2", type: !13)
!915 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !892, file: !893, line: 214, baseType: !263, size: 64)
!916 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !892, file: !893, line: 215, baseType: !13, size: 64, offset: 64)
!917 = !DISubprogram(name: "pair", scope: !892, file: !893, line: 303, type: !918, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!918 = !DISubroutineType(types: !919)
!919 = !{null, !920, !921}
!920 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !892, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!921 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !891, size: 64)
!922 = !DISubprogram(name: "pair", scope: !892, file: !893, line: 304, type: !923, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!923 = !DISubroutineType(types: !924)
!924 = !{null, !920, !925}
!925 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !892, size: 64)
!926 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPKN4llvm12MachineInstrENS0_9SlotIndexEEaSERKS5_", scope: !892, file: !893, line: 378, type: !927, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!927 = !DISubroutineType(types: !928)
!928 = !{!929, !920, !930}
!929 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !892, size: 64)
!930 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !931, file: !788, line: 1928, baseType: !921)
!931 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<const llvm::MachineInstr *, llvm::SlotIndex> &, const std::__nonesuch_no_braces &>", scope: !320, file: !788, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !932, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIPKN4llvm12MachineInstrENS1_9SlotIndexEERKSt20__nonesuch_no_bracesE")
!932 = !{!933, !934, !935}
!933 = !DITemplateValueParameter(name: "_Cond", type: !147, value: i8 1)
!934 = !DITemplateTypeParameter(name: "_Iftrue", type: !921)
!935 = !DITemplateTypeParameter(name: "_Iffalse", type: !936)
!936 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !937, size: 64)
!937 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !938)
!938 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__nonesuch_no_braces", scope: !320, file: !893, line: 185, size: 8, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt20__nonesuch_no_braces")
!939 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPKN4llvm12MachineInstrENS0_9SlotIndexEEaSEOS5_", scope: !892, file: !893, line: 389, type: !940, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!940 = !DISubroutineType(types: !941)
!941 = !{!929, !920, !942}
!942 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !943, file: !788, line: 1928, baseType: !925)
!943 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<const llvm::MachineInstr *, llvm::SlotIndex> &&, std::__nonesuch_no_braces &&>", scope: !320, file: !788, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !944, identifier: "_ZTSSt11conditionalILb1EOSt4pairIPKN4llvm12MachineInstrENS1_9SlotIndexEEOSt20__nonesuch_no_bracesE")
!944 = !{!933, !945, !946}
!945 = !DITemplateTypeParameter(name: "_Iftrue", type: !925)
!946 = !DITemplateTypeParameter(name: "_Iffalse", type: !947)
!947 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !938, size: 64)
!948 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIPKN4llvm12MachineInstrENS0_9SlotIndexEE4swapERS5_", scope: !892, file: !893, line: 424, type: !949, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!949 = !DISubroutineType(types: !950)
!950 = !{null, !920, !929}
!951 = !{!952, !953}
!952 = !DITemplateTypeParameter(name: "_T1", type: !263)
!953 = !DITemplateTypeParameter(name: "_T2", type: !13)
!954 = !DITemplateTypeParameter(name: "F", type: !892)
!955 = !DIDerivedType(tag: DW_TAG_member, name: "End", scope: !879, file: !869, line: 999, baseType: !882, size: 64, offset: 64)
!956 = !DISubprogram(name: "DenseMapIterator", scope: !879, file: !869, line: 1001, type: !957, scopeLine: 1001, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!957 = !DISubroutineType(types: !958)
!958 = !{null, !959}
!959 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !879, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!960 = !DISubprogram(name: "DenseMapIterator", scope: !879, file: !869, line: 1003, type: !961, scopeLine: 1003, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!961 = !DISubroutineType(types: !962)
!962 = !{null, !959, !882, !882, !147}
!963 = !DISubprogram(name: "DenseMapIterator", scope: !879, file: !869, line: 1011, type: !964, scopeLine: 1011, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!964 = !DISubroutineType(types: !965)
!965 = !{null, !959, !966}
!966 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !967, size: 64)
!967 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !879)
!968 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb0EEdeEv", scope: !879, file: !869, line: 1015, type: !969, scopeLine: 1015, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!969 = !DISubroutineType(types: !970)
!970 = !{!971, !973}
!971 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !879, file: !869, line: 996, baseType: !972)
!972 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !884, size: 64)
!973 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !967, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!974 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb0EEptEv", scope: !879, file: !869, line: 1018, type: !975, scopeLine: 1018, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!975 = !DISubroutineType(types: !976)
!976 = !{!882, !973}
!977 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb0EEeqERKNS0_IS3_S4_S6_Lb1EEE", scope: !879, file: !869, line: 1022, type: !978, scopeLine: 1022, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!978 = !DISubroutineType(types: !979)
!979 = !{!147, !973, !980}
!980 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !981, size: 64)
!981 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !982)
!982 = !DIDerivedType(tag: DW_TAG_typedef, name: "ConstIterator", scope: !879, file: !869, line: 990, baseType: !983)
!983 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapIterator<const llvm::MachineInstr *, llvm::SlotIndex, llvm::DenseMapInfo<const llvm::MachineInstr *>, true>", scope: !14, file: !869, line: 987, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !984, templateParams: !1029, identifier: "_ZTSN4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb1EEE")
!984 = !{!985, !993, !994, !998, !1001, !1004, !1011, !1014, !1020, !1021, !1025, !1028}
!985 = !DIDerivedType(tag: DW_TAG_member, name: "Ptr", scope: !983, file: !869, line: 999, baseType: !986, size: 64)
!986 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !983, file: !869, line: 995, baseType: !987)
!987 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !988, size: 64)
!988 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !983, file: !869, line: 994, baseType: !989)
!989 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !990, file: !886, line: 233, baseType: !891)
!990 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<const llvm::MachineInstr *, llvm::SlotIndex>, std::pair<const llvm::MachineInstr *, llvm::SlotIndex> >", scope: !14, file: !886, line: 233, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !991, identifier: "_ZTSN4llvm11conditionalILb1EKSt4pairIPKNS_12MachineInstrENS_9SlotIndexEES6_EE")
!991 = !{!992, !890, !954}
!992 = !DITemplateValueParameter(type: !147, value: i8 1)
!993 = !DIDerivedType(tag: DW_TAG_member, name: "End", scope: !983, file: !869, line: 999, baseType: !986, size: 64, offset: 64)
!994 = !DISubprogram(name: "DenseMapIterator", scope: !983, file: !869, line: 1001, type: !995, scopeLine: 1001, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!995 = !DISubroutineType(types: !996)
!996 = !{null, !997}
!997 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !983, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!998 = !DISubprogram(name: "DenseMapIterator", scope: !983, file: !869, line: 1003, type: !999, scopeLine: 1003, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!999 = !DISubroutineType(types: !1000)
!1000 = !{null, !997, !986, !986, !147}
!1001 = !DISubprogram(name: "DenseMapIterator", scope: !983, file: !869, line: 1011, type: !1002, scopeLine: 1011, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1002 = !DISubroutineType(types: !1003)
!1003 = !{null, !997, !966}
!1004 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb1EEdeEv", scope: !983, file: !869, line: 1015, type: !1005, scopeLine: 1015, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1005 = !DISubroutineType(types: !1006)
!1006 = !{!1007, !1009}
!1007 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !983, file: !869, line: 996, baseType: !1008)
!1008 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !988, size: 64)
!1009 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1010, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1010 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !983)
!1011 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb1EEptEv", scope: !983, file: !869, line: 1018, type: !1012, scopeLine: 1018, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1012 = !DISubroutineType(types: !1013)
!1013 = !{!986, !1009}
!1014 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb1EEeqERKS7_", scope: !983, file: !869, line: 1022, type: !1015, scopeLine: 1022, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1015 = !DISubroutineType(types: !1016)
!1016 = !{!147, !1009, !1017}
!1017 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1018, size: 64)
!1018 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1019)
!1019 = !DIDerivedType(tag: DW_TAG_typedef, name: "ConstIterator", scope: !983, file: !869, line: 990, baseType: !983)
!1020 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb1EEneERKS7_", scope: !983, file: !869, line: 1025, type: !1015, scopeLine: 1025, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1021 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb1EEppEv", scope: !983, file: !869, line: 1029, type: !1022, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1022 = !DISubroutineType(types: !1023)
!1023 = !{!1024, !997}
!1024 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !983, size: 64)
!1025 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb1EEppEi", scope: !983, file: !869, line: 1034, type: !1026, scopeLine: 1034, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1026 = !DISubroutineType(types: !1027)
!1027 = !{!983, !997, !220}
!1028 = !DISubprogram(name: "AdvancePastEmptyBuckets", linkageName: "_ZN4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb1EE23AdvancePastEmptyBucketsEv", scope: !983, file: !869, line: 1039, type: !995, scopeLine: 1039, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1029 = !{!1030, !1031, !1032, !1046}
!1030 = !DITemplateTypeParameter(name: "KeyT", type: !263)
!1031 = !DITemplateTypeParameter(name: "ValueT", type: !13)
!1032 = !DITemplateTypeParameter(name: "KeyInfoT", type: !1033)
!1033 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "DenseMapInfo<const llvm::MachineInstr *>", scope: !14, file: !1034, line: 32, size: 8, flags: DIFlagTypePassByValue, elements: !1035, templateParams: !268, identifier: "_ZTSN4llvm12DenseMapInfoIPKNS_12MachineInstrEEE")
!1034 = !DIFile(filename: "llvm34/include/llvm/ADT/DenseMapInfo.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "1e7505cc8cacf4830514e4c206b176d8")
!1035 = !{!1036, !1039, !1040, !1043}
!1036 = !DISubprogram(name: "getEmptyKey", linkageName: "_ZN4llvm12DenseMapInfoIPKNS_12MachineInstrEE11getEmptyKeyEv", scope: !1033, file: !1034, line: 33, type: !1037, scopeLine: 33, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1037 = !DISubroutineType(types: !1038)
!1038 = !{!263}
!1039 = !DISubprogram(name: "getTombstoneKey", linkageName: "_ZN4llvm12DenseMapInfoIPKNS_12MachineInstrEE15getTombstoneKeyEv", scope: !1033, file: !1034, line: 38, type: !1037, scopeLine: 38, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1040 = !DISubprogram(name: "getHashValue", linkageName: "_ZN4llvm12DenseMapInfoIPKNS_12MachineInstrEE12getHashValueES3_", scope: !1033, file: !1034, line: 43, type: !1041, scopeLine: 43, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1041 = !DISubroutineType(types: !1042)
!1042 = !{!6, !263}
!1043 = !DISubprogram(name: "isEqual", linkageName: "_ZN4llvm12DenseMapInfoIPKNS_12MachineInstrEE7isEqualES3_S3_", scope: !1033, file: !1034, line: 47, type: !1044, scopeLine: 47, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1044 = !DISubroutineType(types: !1045)
!1045 = !{!147, !263, !263}
!1046 = !DITemplateValueParameter(name: "IsConst", type: !147, value: i8 1)
!1047 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb0EEneERKNS0_IS3_S4_S6_Lb1EEE", scope: !879, file: !869, line: 1025, type: !978, scopeLine: 1025, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1048 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb0EEppEv", scope: !879, file: !869, line: 1029, type: !1049, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1049 = !DISubroutineType(types: !1050)
!1050 = !{!1051, !959}
!1051 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !879, size: 64)
!1052 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb0EEppEi", scope: !879, file: !869, line: 1034, type: !1053, scopeLine: 1034, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1053 = !DISubroutineType(types: !1054)
!1054 = !{!879, !959, !220}
!1055 = !DISubprogram(name: "AdvancePastEmptyBuckets", linkageName: "_ZN4llvm16DenseMapIteratorIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EELb0EE23AdvancePastEmptyBucketsEv", scope: !879, file: !869, line: 1039, type: !957, scopeLine: 1039, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1056 = !{!1030, !1031, !1032, !1057}
!1057 = !DITemplateValueParameter(name: "IsConst", type: !147, defaulted: true, value: i8 0)
!1058 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !873, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1059 = !DISubprogram(name: "end", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E3endEv", scope: !873, file: !869, line: 57, type: !876, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1060 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E5beginEv", scope: !873, file: !869, line: 60, type: !1061, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1061 = !DISubroutineType(types: !1062)
!1062 = !{!1063, !1064}
!1063 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !873, file: !869, line: 52, baseType: !983)
!1064 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1065, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1065 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !873)
!1066 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E3endEv", scope: !873, file: !869, line: 63, type: !1061, scopeLine: 63, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1067 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E5emptyEv", scope: !873, file: !869, line: 67, type: !1068, scopeLine: 67, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1068 = !DISubroutineType(types: !1069)
!1069 = !{!147, !1064}
!1070 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E4sizeEv", scope: !873, file: !869, line: 70, type: !1071, scopeLine: 70, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1071 = !DISubroutineType(types: !1072)
!1072 = !{!6, !1064}
!1073 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E6resizeEm", scope: !873, file: !869, line: 73, type: !1074, scopeLine: 73, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1074 = !DISubroutineType(types: !1075)
!1075 = !{null, !1058, !1076}
!1076 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", file: !1077, line: 46, baseType: !283)
!1077 = !DIFile(filename: "llvm5/build/lib/clang/15.0.3/include/stddef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "b76978376d35d5cd171876ac58ac1256")
!1078 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E5clearEv", scope: !873, file: !869, line: 78, type: !1079, scopeLine: 78, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1079 = !DISubroutineType(types: !1080)
!1080 = !{null, !1058}
!1081 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E5countERKS4_", scope: !873, file: !869, line: 103, type: !1082, scopeLine: 103, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1082 = !DISubroutineType(types: !1083)
!1083 = !{!147, !1064, !1084}
!1084 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1085, size: 64)
!1085 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !263)
!1086 = !DISubprogram(name: "find", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E4findERKS4_", scope: !873, file: !869, line: 108, type: !1087, scopeLine: 108, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1087 = !DISubroutineType(types: !1088)
!1088 = !{!878, !1058, !1084}
!1089 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E4findERKS4_", scope: !873, file: !869, line: 114, type: !1090, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1090 = !DISubroutineType(types: !1091)
!1091 = !{!1063, !1064, !1084}
!1092 = !DISubprogram(name: "lookup", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E6lookupERKS4_", scope: !873, file: !869, line: 143, type: !1093, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1093 = !DISubroutineType(types: !1094)
!1094 = !{!13, !1064, !1084}
!1095 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E6insertERKSt4pairIS4_S5_E", scope: !873, file: !869, line: 153, type: !1096, scopeLine: 153, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1096 = !DISubroutineType(types: !1097)
!1097 = !{!1098, !1058, !921}
!1098 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::DenseMapIterator<const llvm::MachineInstr *, llvm::SlotIndex, llvm::DenseMapInfo<const llvm::MachineInstr *>, false>, bool>", scope: !320, file: !893, line: 208, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1099, templateParams: !1150, identifier: "_ZTSSt4pairIN4llvm16DenseMapIteratorIPKNS0_12MachineInstrENS0_9SlotIndexENS0_12DenseMapInfoIS4_EELb0EEEbE")
!1099 = !{!1100, !1120, !1121, !1122, !1128, !1132, !1140, !1147}
!1100 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1098, baseType: !1101, flags: DIFlagPrivate, extraData: i32 0)
!1101 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::DenseMapIterator<const llvm::MachineInstr *, llvm::SlotIndex, llvm::DenseMapInfo<const llvm::MachineInstr *>, false>, bool>", scope: !320, file: !893, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !1102, templateParams: !1117, identifier: "_ZTSSt11__pair_baseIN4llvm16DenseMapIteratorIPKNS0_12MachineInstrENS0_9SlotIndexENS0_12DenseMapInfoIS4_EELb0EEEbE")
!1102 = !{!1103, !1107, !1108, !1113}
!1103 = !DISubprogram(name: "__pair_base", scope: !1101, file: !893, line: 194, type: !1104, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1104 = !DISubroutineType(types: !1105)
!1105 = !{null, !1106}
!1106 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1101, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1107 = !DISubprogram(name: "~__pair_base", scope: !1101, file: !893, line: 195, type: !1104, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1108 = !DISubprogram(name: "__pair_base", scope: !1101, file: !893, line: 196, type: !1109, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1109 = !DISubroutineType(types: !1110)
!1110 = !{null, !1106, !1111}
!1111 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1112, size: 64)
!1112 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1101)
!1113 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN4llvm16DenseMapIteratorIPKNS0_12MachineInstrENS0_9SlotIndexENS0_12DenseMapInfoIS4_EELb0EEEbEaSERKS9_", scope: !1101, file: !893, line: 197, type: !1114, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1114 = !DISubroutineType(types: !1115)
!1115 = !{!1116, !1106, !1111}
!1116 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1101, size: 64)
!1117 = !{!1118, !1119}
!1118 = !DITemplateTypeParameter(name: "_U1", type: !879)
!1119 = !DITemplateTypeParameter(name: "_U2", type: !147)
!1120 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !1098, file: !893, line: 214, baseType: !879, size: 128)
!1121 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !1098, file: !893, line: 215, baseType: !147, size: 8, offset: 128)
!1122 = !DISubprogram(name: "pair", scope: !1098, file: !893, line: 303, type: !1123, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1123 = !DISubroutineType(types: !1124)
!1124 = !{null, !1125, !1126}
!1125 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1098, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1126 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1127, size: 64)
!1127 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1098)
!1128 = !DISubprogram(name: "pair", scope: !1098, file: !893, line: 304, type: !1129, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1129 = !DISubroutineType(types: !1130)
!1130 = !{null, !1125, !1131}
!1131 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1098, size: 64)
!1132 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm16DenseMapIteratorIPKNS0_12MachineInstrENS0_9SlotIndexENS0_12DenseMapInfoIS4_EELb0EEEbEaSERKS9_", scope: !1098, file: !893, line: 378, type: !1133, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1133 = !DISubroutineType(types: !1134)
!1134 = !{!1135, !1125, !1136}
!1135 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1098, size: 64)
!1136 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1137, file: !788, line: 1928, baseType: !1126)
!1137 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::DenseMapIterator<const llvm::MachineInstr *, llvm::SlotIndex, llvm::DenseMapInfo<const llvm::MachineInstr *>, false>, bool> &, const std::__nonesuch_no_braces &>", scope: !320, file: !788, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !1138, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN4llvm16DenseMapIteratorIPKNS1_12MachineInstrENS1_9SlotIndexENS1_12DenseMapInfoIS5_EELb0EEEbERKSt20__nonesuch_no_bracesE")
!1138 = !{!933, !1139, !935}
!1139 = !DITemplateTypeParameter(name: "_Iftrue", type: !1126)
!1140 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm16DenseMapIteratorIPKNS0_12MachineInstrENS0_9SlotIndexENS0_12DenseMapInfoIS4_EELb0EEEbEaSEOS9_", scope: !1098, file: !893, line: 389, type: !1141, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1141 = !DISubroutineType(types: !1142)
!1142 = !{!1135, !1125, !1143}
!1143 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1144, file: !788, line: 1928, baseType: !1131)
!1144 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::DenseMapIterator<const llvm::MachineInstr *, llvm::SlotIndex, llvm::DenseMapInfo<const llvm::MachineInstr *>, false>, bool> &&, std::__nonesuch_no_braces &&>", scope: !320, file: !788, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !1145, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN4llvm16DenseMapIteratorIPKNS1_12MachineInstrENS1_9SlotIndexENS1_12DenseMapInfoIS5_EELb0EEEbEOSt20__nonesuch_no_bracesE")
!1145 = !{!933, !1146, !946}
!1146 = !DITemplateTypeParameter(name: "_Iftrue", type: !1131)
!1147 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN4llvm16DenseMapIteratorIPKNS0_12MachineInstrENS0_9SlotIndexENS0_12DenseMapInfoIS4_EELb0EEEbE4swapERS9_", scope: !1098, file: !893, line: 424, type: !1148, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1148 = !DISubroutineType(types: !1149)
!1149 = !{null, !1125, !1135}
!1150 = !{!1151, !1152}
!1151 = !DITemplateTypeParameter(name: "_T1", type: !879)
!1152 = !DITemplateTypeParameter(name: "_T2", type: !147)
!1153 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E6insertEOSt4pairIS4_S5_E", scope: !873, file: !869, line: 168, type: !1154, scopeLine: 168, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1154 = !DISubroutineType(types: !1155)
!1155 = !{!1098, !1058, !925}
!1156 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E5eraseERKS4_", scope: !873, file: !869, line: 190, type: !1157, scopeLine: 190, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1157 = !DISubroutineType(types: !1158)
!1158 = !{!147, !1058, !1084}
!1159 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E5eraseENS_16DenseMapIteratorIS4_S5_S7_Lb0EEE", scope: !873, file: !869, line: 201, type: !1160, scopeLine: 201, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1160 = !DISubroutineType(types: !1161)
!1161 = !{null, !1058, !878}
!1162 = !DISubprogram(name: "FindAndConstruct", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E16FindAndConstructERKS4_", scope: !873, file: !869, line: 209, type: !1163, scopeLine: 209, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1163 = !DISubroutineType(types: !1164)
!1164 = !{!1165, !1058, !1084}
!1165 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1166, size: 64)
!1166 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !873, file: !869, line: 48, baseType: !1167)
!1167 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !873, file: !869, line: 43, baseType: !892)
!1168 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_EixERKS4_", scope: !873, file: !869, line: 217, type: !1169, scopeLine: 217, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1169 = !DISubroutineType(types: !1170)
!1170 = !{!1171, !1058, !1084}
!1171 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !13, size: 64)
!1172 = !DISubprogram(name: "FindAndConstruct", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E16FindAndConstructEOS4_", scope: !873, file: !869, line: 222, type: !1173, scopeLine: 222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1173 = !DISubroutineType(types: !1174)
!1174 = !{!1165, !1058, !1175}
!1175 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !263, size: 64)
!1176 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_EixEOS4_", scope: !873, file: !869, line: 230, type: !1177, scopeLine: 230, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1177 = !DISubroutineType(types: !1178)
!1178 = !{!1171, !1058, !1175}
!1179 = !DISubprogram(name: "isPointerIntoBucketsArray", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E25isPointerIntoBucketsArrayEPKv", scope: !873, file: !869, line: 238, type: !1180, scopeLine: 238, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1180 = !DISubroutineType(types: !1181)
!1181 = !{!147, !1064, !142}
!1182 = !DISubprogram(name: "getPointerIntoBucketsArray", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E26getPointerIntoBucketsArrayEv", scope: !873, file: !869, line: 245, type: !1183, scopeLine: 245, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1183 = !DISubroutineType(types: !1184)
!1184 = !{!142, !1064}
!1185 = !DISubprogram(name: "DenseMapBase", scope: !873, file: !869, line: 248, type: !1079, scopeLine: 248, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1186 = !DISubprogram(name: "destroyAll", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E10destroyAllEv", scope: !873, file: !869, line: 250, type: !1079, scopeLine: 250, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1187 = !DISubprogram(name: "initEmpty", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E9initEmptyEv", scope: !873, file: !869, line: 267, type: !1079, scopeLine: 267, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1188 = !DISubprogram(name: "moveFromOldBuckets", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E18moveFromOldBucketsEPSt4pairIS4_S5_ESC_", scope: !873, file: !869, line: 278, type: !1189, scopeLine: 278, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1189 = !DISubroutineType(types: !1190)
!1190 = !{null, !1058, !1191, !1191}
!1191 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1167, size: 64)
!1192 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E4swapERS9_", scope: !873, file: !869, line: 328, type: !1193, scopeLine: 328, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1193 = !DISubroutineType(types: !1194)
!1194 = !{null, !1058, !1195}
!1195 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !873, size: 64)
!1196 = !DISubprogram(name: "getHashValue", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E12getHashValueERKS4_", scope: !873, file: !869, line: 333, type: !1197, scopeLine: 333, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1197 = !DISubroutineType(types: !1198)
!1198 = !{!6, !1084}
!1199 = !DISubprogram(name: "getEmptyKey", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E11getEmptyKeyEv", scope: !873, file: !869, line: 340, type: !1200, scopeLine: 340, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1200 = !DISubroutineType(types: !1201)
!1201 = !{!1085}
!1202 = !DISubprogram(name: "getTombstoneKey", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E15getTombstoneKeyEv", scope: !873, file: !869, line: 343, type: !1200, scopeLine: 343, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1203 = !DISubprogram(name: "getNumEntries", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E13getNumEntriesEv", scope: !873, file: !869, line: 348, type: !1071, scopeLine: 348, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1204 = !DISubprogram(name: "setNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E13setNumEntriesEj", scope: !873, file: !869, line: 351, type: !1205, scopeLine: 351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1205 = !DISubroutineType(types: !1206)
!1206 = !{null, !1058, !6}
!1207 = !DISubprogram(name: "incrementNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E19incrementNumEntriesEv", scope: !873, file: !869, line: 354, type: !1079, scopeLine: 354, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1208 = !DISubprogram(name: "decrementNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E19decrementNumEntriesEv", scope: !873, file: !869, line: 357, type: !1079, scopeLine: 357, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1209 = !DISubprogram(name: "getNumTombstones", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E16getNumTombstonesEv", scope: !873, file: !869, line: 360, type: !1071, scopeLine: 360, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1210 = !DISubprogram(name: "setNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E16setNumTombstonesEj", scope: !873, file: !869, line: 363, type: !1205, scopeLine: 363, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1211 = !DISubprogram(name: "incrementNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E22incrementNumTombstonesEv", scope: !873, file: !869, line: 366, type: !1079, scopeLine: 366, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1212 = !DISubprogram(name: "decrementNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E22decrementNumTombstonesEv", scope: !873, file: !869, line: 369, type: !1079, scopeLine: 369, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1213 = !DISubprogram(name: "getBuckets", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E10getBucketsEv", scope: !873, file: !869, line: 372, type: !1214, scopeLine: 372, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1214 = !DISubroutineType(types: !1215)
!1215 = !{!1216, !1064}
!1216 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1217, size: 64)
!1217 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1167)
!1218 = !DISubprogram(name: "getBuckets", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E10getBucketsEv", scope: !873, file: !869, line: 375, type: !1219, scopeLine: 375, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1219 = !DISubroutineType(types: !1220)
!1220 = !{!1191, !1058}
!1221 = !DISubprogram(name: "getNumBuckets", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E13getNumBucketsEv", scope: !873, file: !869, line: 378, type: !1071, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1222 = !DISubprogram(name: "getBucketsEnd", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E13getBucketsEndEv", scope: !873, file: !869, line: 381, type: !1219, scopeLine: 381, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1223 = !DISubprogram(name: "getBucketsEnd", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E13getBucketsEndEv", scope: !873, file: !869, line: 384, type: !1214, scopeLine: 384, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1224 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E4growEj", scope: !873, file: !869, line: 388, type: !1205, scopeLine: 388, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1225 = !DISubprogram(name: "shrink_and_clear", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E16shrink_and_clearEv", scope: !873, file: !869, line: 392, type: !1079, scopeLine: 392, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1226 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E16InsertIntoBucketERKS4_RKS5_PSt4pairIS4_S5_E", scope: !873, file: !869, line: 397, type: !1227, scopeLine: 397, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1227 = !DISubroutineType(types: !1228)
!1228 = !{!1191, !1058, !1084, !191, !1191}
!1229 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E16InsertIntoBucketERKS4_OS5_PSt4pairIS4_S5_E", scope: !873, file: !869, line: 407, type: !1230, scopeLine: 407, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1230 = !DISubroutineType(types: !1231)
!1231 = !{!1191, !1058, !1084, !1232, !1191}
!1232 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !13, size: 64)
!1233 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E16InsertIntoBucketEOS4_OS5_PSt4pairIS4_S5_E", scope: !873, file: !869, line: 416, type: !1234, scopeLine: 416, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1234 = !DISubroutineType(types: !1235)
!1235 = !{!1191, !1058, !1175, !1232, !1191}
!1236 = !DISubprogram(name: "InsertIntoBucketImpl", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E20InsertIntoBucketImplERKS4_PSt4pairIS4_S5_E", scope: !873, file: !869, line: 425, type: !1237, scopeLine: 425, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1237 = !DISubroutineType(types: !1238)
!1238 = !{!1191, !1058, !1084, !1191}
!1239 = !DISubprogram(name: "getMemorySize", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS4_EEEES4_S5_S7_E13getMemorySizeEv", scope: !873, file: !869, line: 527, type: !1240, scopeLine: 527, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1240 = !DISubroutineType(types: !1241)
!1241 = !{!1076, !1064}
!1242 = !{!1243, !1030, !1031, !1032}
!1243 = !DITemplateTypeParameter(name: "DerivedT", type: !870)
!1244 = !DIDerivedType(tag: DW_TAG_member, name: "Buckets", scope: !870, file: !869, line: 543, baseType: !867, size: 64)
!1245 = !DIDerivedType(tag: DW_TAG_member, name: "NumEntries", scope: !870, file: !869, line: 544, baseType: !6, size: 32, offset: 64)
!1246 = !DIDerivedType(tag: DW_TAG_member, name: "NumTombstones", scope: !870, file: !869, line: 545, baseType: !6, size: 32, offset: 96)
!1247 = !DIDerivedType(tag: DW_TAG_member, name: "NumBuckets", scope: !870, file: !869, line: 546, baseType: !6, size: 32, offset: 128)
!1248 = !DISubprogram(name: "DenseMap", scope: !870, file: !869, line: 549, type: !1249, scopeLine: 549, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1249 = !DISubroutineType(types: !1250)
!1250 = !{null, !1251, !6}
!1251 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !870, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1252 = !DISubprogram(name: "DenseMap", scope: !870, file: !869, line: 553, type: !1253, scopeLine: 553, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1253 = !DISubroutineType(types: !1254)
!1254 = !{null, !1251, !1255}
!1255 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1256, size: 64)
!1256 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !870)
!1257 = !DISubprogram(name: "DenseMap", scope: !870, file: !869, line: 559, type: !1258, scopeLine: 559, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1258 = !DISubroutineType(types: !1259)
!1259 = !{null, !1251, !1260}
!1260 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !870, size: 64)
!1261 = !DISubprogram(name: "~DenseMap", scope: !870, file: !869, line: 571, type: !1262, scopeLine: 571, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1262 = !DISubroutineType(types: !1263)
!1263 = !{null, !1251}
!1264 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEE4swapERS7_", scope: !870, file: !869, line: 576, type: !1265, scopeLine: 576, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1265 = !DISubroutineType(types: !1266)
!1266 = !{null, !1251, !1267}
!1267 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !870, size: 64)
!1268 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEEaSERKS7_", scope: !870, file: !869, line: 583, type: !1269, scopeLine: 583, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1269 = !DISubroutineType(types: !1270)
!1270 = !{!1267, !1251, !1255}
!1271 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEEaSEOS7_", scope: !870, file: !869, line: 589, type: !1272, scopeLine: 589, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1272 = !DISubroutineType(types: !1273)
!1273 = !{!1267, !1251, !1260}
!1274 = !DISubprogram(name: "copyFrom", linkageName: "_ZN4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEE8copyFromERKS7_", scope: !870, file: !869, line: 598, type: !1253, scopeLine: 598, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1275 = !DISubprogram(name: "init", linkageName: "_ZN4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEE4initEj", scope: !870, file: !869, line: 609, type: !1249, scopeLine: 609, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1276 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEE4growEj", scope: !870, file: !869, line: 618, type: !1249, scopeLine: 618, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1277 = !DISubprogram(name: "shrink_and_clear", linkageName: "_ZN4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEE16shrink_and_clearEv", scope: !870, file: !869, line: 635, type: !1262, scopeLine: 635, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1278 = !DISubprogram(name: "getNumEntries", linkageName: "_ZNK4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEE13getNumEntriesEv", scope: !870, file: !869, line: 653, type: !1279, scopeLine: 653, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1279 = !DISubroutineType(types: !1280)
!1280 = !{!6, !1281}
!1281 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1256, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1282 = !DISubprogram(name: "setNumEntries", linkageName: "_ZN4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEE13setNumEntriesEj", scope: !870, file: !869, line: 656, type: !1249, scopeLine: 656, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1283 = !DISubprogram(name: "getNumTombstones", linkageName: "_ZNK4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEE16getNumTombstonesEv", scope: !870, file: !869, line: 660, type: !1279, scopeLine: 660, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1284 = !DISubprogram(name: "setNumTombstones", linkageName: "_ZN4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEE16setNumTombstonesEj", scope: !870, file: !869, line: 663, type: !1249, scopeLine: 663, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1285 = !DISubprogram(name: "getBuckets", linkageName: "_ZNK4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEE10getBucketsEv", scope: !870, file: !869, line: 667, type: !1286, scopeLine: 667, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1286 = !DISubroutineType(types: !1287)
!1287 = !{!867, !1281}
!1288 = !DISubprogram(name: "getNumBuckets", linkageName: "_ZNK4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEE13getNumBucketsEv", scope: !870, file: !869, line: 671, type: !1279, scopeLine: 671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1289 = !DISubprogram(name: "allocateBuckets", linkageName: "_ZN4llvm8DenseMapIPKNS_12MachineInstrENS_9SlotIndexENS_12DenseMapInfoIS3_EEE15allocateBucketsEj", scope: !870, file: !869, line: 675, type: !1290, scopeLine: 675, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1290 = !DISubroutineType(types: !1291)
!1291 = !{!147, !1251, !6}
!1292 = !{!1030, !1031, !1032}
!1293 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !870, size: 64)
!1294 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1256, size: 64)
!1295 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !338, size: 64)
!1296 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !1298, file: !1297, line: 345, baseType: !1299)
!1297 = !DIFile(filename: "llvm34/include/llvm/ADT/ilist.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "da692daf2fc683e7a6021157e4a297cf")
!1298 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "iplist<llvm::MachineBasicBlock, llvm::ilist_traits<llvm::MachineBasicBlock> >", scope: !14, file: !1297, line: 313, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm6iplistINS_17MachineBasicBlockENS_12ilist_traitsIS1_EEEE")
!1299 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ilist_iterator<const llvm::MachineBasicBlock>", scope: !14, file: !1297, line: 145, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1300, templateParams: !1369, identifier: "_ZTSN4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEE")
!1300 = !{!1301, !1321, !1324, !1331, !1332, !1333, !1334, !1335, !1339, !1344, !1347, !1350, !1353, !1354, !1358, !1359, !1363, !1364, !1367, !1368}
!1301 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1299, baseType: !1302, flags: DIFlagPublic, extraData: i32 0)
!1302 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::bidirectional_iterator_tag, const llvm::MachineBasicBlock, long, const llvm::MachineBasicBlock *, const llvm::MachineBasicBlock &>", scope: !320, file: !617, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !1303, identifier: "_ZTSSt8iteratorISt26bidirectional_iterator_tagKN4llvm17MachineBasicBlockElPS3_RS3_E")
!1303 = !{!1304, !1312, !1316, !1317, !1319}
!1304 = !DITemplateTypeParameter(name: "_Category", type: !1305)
!1305 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "bidirectional_iterator_tag", scope: !320, file: !617, line: 99, size: 8, flags: DIFlagTypePassByValue, elements: !1306, identifier: "_ZTSSt26bidirectional_iterator_tag")
!1306 = !{!1307}
!1307 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1305, baseType: !1308, extraData: i32 0)
!1308 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "forward_iterator_tag", scope: !320, file: !617, line: 95, size: 8, flags: DIFlagTypePassByValue, elements: !1309, identifier: "_ZTSSt20forward_iterator_tag")
!1309 = !{!1310}
!1310 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1308, baseType: !1311, extraData: i32 0)
!1311 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "input_iterator_tag", scope: !320, file: !617, line: 89, size: 8, flags: DIFlagTypePassByValue, elements: !275, identifier: "_ZTSSt18input_iterator_tag")
!1312 = !DITemplateTypeParameter(name: "_Tp", type: !1313)
!1313 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1314)
!1314 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MachineBasicBlock", scope: !14, file: !1315, line: 62, size: 1408, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm17MachineBasicBlockE")
!1315 = !DIFile(filename: "llvm34/include/llvm/CodeGen/MachineBasicBlock.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "a28a380f2952405e2da5b2c96750300d")
!1316 = !DITemplateTypeParameter(name: "_Distance", type: !23)
!1317 = !DITemplateTypeParameter(name: "_Pointer", type: !1318)
!1318 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1313, size: 64)
!1319 = !DITemplateTypeParameter(name: "_Reference", type: !1320)
!1320 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1313, size: 64)
!1321 = !DIDerivedType(tag: DW_TAG_member, name: "NodePtr", scope: !1299, file: !1297, line: 158, baseType: !1322, size: 64)
!1322 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1299, file: !1297, line: 155, baseType: !1323)
!1323 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1302, file: !617, line: 127, baseType: !1318)
!1324 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEixEl", scope: !1299, file: !1297, line: 164, type: !1325, scopeLine: 164, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1325 = !DISubroutineType(types: !1326)
!1326 = !{null, !1327, !1329}
!1327 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1328, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1328 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1299)
!1329 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1299, file: !1297, line: 154, baseType: !1330)
!1330 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1302, file: !617, line: 125, baseType: !23)
!1331 = !DISubprogram(name: "operator+", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEplEl", scope: !1299, file: !1297, line: 165, type: !1325, scopeLine: 165, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1332 = !DISubprogram(name: "operator-", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEmiEl", scope: !1299, file: !1297, line: 166, type: !1325, scopeLine: 166, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1333 = !DISubprogram(name: "operator+=", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEpLEl", scope: !1299, file: !1297, line: 167, type: !1325, scopeLine: 167, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1334 = !DISubprogram(name: "operator-=", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEmIEl", scope: !1299, file: !1297, line: 168, type: !1325, scopeLine: 168, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1335 = !DISubprogram(name: "ilist_iterator", scope: !1299, file: !1297, line: 176, type: !1336, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1336 = !DISubroutineType(types: !1337)
!1337 = !{null, !1338, !1322}
!1338 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1299, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1339 = !DISubprogram(name: "ilist_iterator", scope: !1299, file: !1297, line: 177, type: !1340, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1340 = !DISubroutineType(types: !1341)
!1341 = !{null, !1338, !1342}
!1342 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1299, file: !1297, line: 156, baseType: !1343)
!1343 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1302, file: !617, line: 129, baseType: !1320)
!1344 = !DISubprogram(name: "ilist_iterator", scope: !1299, file: !1297, line: 178, type: !1345, scopeLine: 178, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1345 = !DISubroutineType(types: !1346)
!1346 = !{null, !1338}
!1347 = !DISubprogram(name: "operator const llvm::MachineBasicBlock *", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEcvPS2_Ev", scope: !1299, file: !1297, line: 195, type: !1348, scopeLine: 195, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1348 = !DISubroutineType(types: !1349)
!1349 = !{!1322, !1327}
!1350 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEdeEv", scope: !1299, file: !1297, line: 199, type: !1351, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1351 = !DISubroutineType(types: !1352)
!1352 = !{!1342, !1327}
!1353 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEptEv", scope: !1299, file: !1297, line: 202, type: !1348, scopeLine: 202, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1354 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEeqERKS3_", scope: !1299, file: !1297, line: 205, type: !1355, scopeLine: 205, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1355 = !DISubroutineType(types: !1356)
!1356 = !{!147, !1327, !1357}
!1357 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1328, size: 64)
!1358 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEneERKS3_", scope: !1299, file: !1297, line: 208, type: !1355, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1359 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEmmEv", scope: !1299, file: !1297, line: 213, type: !1360, scopeLine: 213, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1360 = !DISubroutineType(types: !1361)
!1361 = !{!1362, !1338}
!1362 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1299, size: 64)
!1363 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEppEv", scope: !1299, file: !1297, line: 218, type: !1360, scopeLine: 218, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1364 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEmmEi", scope: !1299, file: !1297, line: 222, type: !1365, scopeLine: 222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1365 = !DISubroutineType(types: !1366)
!1366 = !{!1299, !1338, !220}
!1367 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorIKNS_17MachineBasicBlockEEppEi", scope: !1299, file: !1297, line: 227, type: !1365, scopeLine: 227, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1368 = !DISubprogram(name: "getNodePtrUnchecked", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_17MachineBasicBlockEE19getNodePtrUncheckedEv", scope: !1299, file: !1297, line: 234, type: !1348, scopeLine: 234, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1369 = !{!1370}
!1370 = !DITemplateTypeParameter(name: "NodeTy", type: !1313)
!1371 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1314, size: 64)
!1372 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1298, file: !1297, line: 344, baseType: !1373)
!1373 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ilist_iterator<llvm::MachineBasicBlock>", scope: !14, file: !1297, line: 145, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1374, templateParams: !1430, identifier: "_ZTSN4llvm14ilist_iteratorINS_17MachineBasicBlockEEE")
!1374 = !{!1375, !1382, !1385, !1392, !1393, !1394, !1395, !1396, !1400, !1405, !1408, !1411, !1414, !1415, !1419, !1420, !1424, !1425, !1428, !1429}
!1375 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1373, baseType: !1376, flags: DIFlagPublic, extraData: i32 0)
!1376 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::bidirectional_iterator_tag, llvm::MachineBasicBlock, long, llvm::MachineBasicBlock *, llvm::MachineBasicBlock &>", scope: !320, file: !617, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !1377, identifier: "_ZTSSt8iteratorISt26bidirectional_iterator_tagN4llvm17MachineBasicBlockElPS2_RS2_E")
!1377 = !{!1304, !1378, !1316, !1379, !1380}
!1378 = !DITemplateTypeParameter(name: "_Tp", type: !1314)
!1379 = !DITemplateTypeParameter(name: "_Pointer", type: !1371)
!1380 = !DITemplateTypeParameter(name: "_Reference", type: !1381)
!1381 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1314, size: 64)
!1382 = !DIDerivedType(tag: DW_TAG_member, name: "NodePtr", scope: !1373, file: !1297, line: 158, baseType: !1383, size: 64)
!1383 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1373, file: !1297, line: 155, baseType: !1384)
!1384 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1376, file: !617, line: 127, baseType: !1371)
!1385 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEixEl", scope: !1373, file: !1297, line: 164, type: !1386, scopeLine: 164, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1386 = !DISubroutineType(types: !1387)
!1387 = !{null, !1388, !1390}
!1388 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1389, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1389 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1373)
!1390 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1373, file: !1297, line: 154, baseType: !1391)
!1391 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1376, file: !617, line: 125, baseType: !23)
!1392 = !DISubprogram(name: "operator+", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEplEl", scope: !1373, file: !1297, line: 165, type: !1386, scopeLine: 165, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1393 = !DISubprogram(name: "operator-", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEmiEl", scope: !1373, file: !1297, line: 166, type: !1386, scopeLine: 166, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1394 = !DISubprogram(name: "operator+=", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEpLEl", scope: !1373, file: !1297, line: 167, type: !1386, scopeLine: 167, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1395 = !DISubprogram(name: "operator-=", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEmIEl", scope: !1373, file: !1297, line: 168, type: !1386, scopeLine: 168, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1396 = !DISubprogram(name: "ilist_iterator", scope: !1373, file: !1297, line: 176, type: !1397, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1397 = !DISubroutineType(types: !1398)
!1398 = !{null, !1399, !1383}
!1399 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1373, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1400 = !DISubprogram(name: "ilist_iterator", scope: !1373, file: !1297, line: 177, type: !1401, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1401 = !DISubroutineType(types: !1402)
!1402 = !{null, !1399, !1403}
!1403 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1373, file: !1297, line: 156, baseType: !1404)
!1404 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1376, file: !617, line: 129, baseType: !1381)
!1405 = !DISubprogram(name: "ilist_iterator", scope: !1373, file: !1297, line: 178, type: !1406, scopeLine: 178, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1406 = !DISubroutineType(types: !1407)
!1407 = !{null, !1399}
!1408 = !DISubprogram(name: "operator llvm::MachineBasicBlock *", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEcvPS1_Ev", scope: !1373, file: !1297, line: 195, type: !1409, scopeLine: 195, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1409 = !DISubroutineType(types: !1410)
!1410 = !{!1383, !1388}
!1411 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEdeEv", scope: !1373, file: !1297, line: 199, type: !1412, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1412 = !DISubroutineType(types: !1413)
!1413 = !{!1403, !1388}
!1414 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEptEv", scope: !1373, file: !1297, line: 202, type: !1409, scopeLine: 202, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1415 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEeqERKS2_", scope: !1373, file: !1297, line: 205, type: !1416, scopeLine: 205, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1416 = !DISubroutineType(types: !1417)
!1417 = !{!147, !1388, !1418}
!1418 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1389, size: 64)
!1419 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEEneERKS2_", scope: !1373, file: !1297, line: 208, type: !1416, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1420 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorINS_17MachineBasicBlockEEmmEv", scope: !1373, file: !1297, line: 213, type: !1421, scopeLine: 213, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1421 = !DISubroutineType(types: !1422)
!1422 = !{!1423, !1399}
!1423 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1373, size: 64)
!1424 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorINS_17MachineBasicBlockEEppEv", scope: !1373, file: !1297, line: 218, type: !1421, scopeLine: 218, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1425 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorINS_17MachineBasicBlockEEmmEi", scope: !1373, file: !1297, line: 222, type: !1426, scopeLine: 222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1426 = !DISubroutineType(types: !1427)
!1427 = !{!1373, !1399, !220}
!1428 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorINS_17MachineBasicBlockEEppEi", scope: !1373, file: !1297, line: 227, type: !1426, scopeLine: 227, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1429 = !DISubprogram(name: "getNodePtrUnchecked", linkageName: "_ZNK4llvm14ilist_iteratorINS_17MachineBasicBlockEE19getNodePtrUncheckedEv", scope: !1373, file: !1297, line: 234, type: !1409, scopeLine: 234, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1430 = !{!1431}
!1431 = !DITemplateTypeParameter(name: "NodeTy", type: !1314)
!1432 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1433, file: !1297, line: 344, baseType: !1434)
!1433 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "iplist<llvm::MachineInstr, llvm::ilist_traits<llvm::MachineInstr> >", scope: !14, file: !1297, line: 313, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm6iplistINS_12MachineInstrENS_12ilist_traitsIS1_EEEE")
!1434 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ilist_iterator<llvm::MachineInstr>", scope: !14, file: !1297, line: 145, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1435, templateParams: !1491, identifier: "_ZTSN4llvm14ilist_iteratorINS_12MachineInstrEEE")
!1435 = !{!1436, !1443, !1446, !1453, !1454, !1455, !1456, !1457, !1461, !1466, !1469, !1472, !1475, !1476, !1480, !1481, !1485, !1486, !1489, !1490}
!1436 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1434, baseType: !1437, flags: DIFlagPublic, extraData: i32 0)
!1437 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::bidirectional_iterator_tag, llvm::MachineInstr, long, llvm::MachineInstr *, llvm::MachineInstr &>", scope: !320, file: !617, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !1438, identifier: "_ZTSSt8iteratorISt26bidirectional_iterator_tagN4llvm12MachineInstrElPS2_RS2_E")
!1438 = !{!1304, !1439, !1316, !1440, !1441}
!1439 = !DITemplateTypeParameter(name: "_Tp", type: !83)
!1440 = !DITemplateTypeParameter(name: "_Pointer", type: !82)
!1441 = !DITemplateTypeParameter(name: "_Reference", type: !1442)
!1442 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !83, size: 64)
!1443 = !DIDerivedType(tag: DW_TAG_member, name: "NodePtr", scope: !1434, file: !1297, line: 158, baseType: !1444, size: 64)
!1444 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1434, file: !1297, line: 155, baseType: !1445)
!1445 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1437, file: !617, line: 127, baseType: !82)
!1446 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEixEl", scope: !1434, file: !1297, line: 164, type: !1447, scopeLine: 164, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1447 = !DISubroutineType(types: !1448)
!1448 = !{null, !1449, !1451}
!1449 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1450, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1450 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1434)
!1451 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1434, file: !1297, line: 154, baseType: !1452)
!1452 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1437, file: !617, line: 125, baseType: !23)
!1453 = !DISubprogram(name: "operator+", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEplEl", scope: !1434, file: !1297, line: 165, type: !1447, scopeLine: 165, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1454 = !DISubprogram(name: "operator-", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEmiEl", scope: !1434, file: !1297, line: 166, type: !1447, scopeLine: 166, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1455 = !DISubprogram(name: "operator+=", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEpLEl", scope: !1434, file: !1297, line: 167, type: !1447, scopeLine: 167, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1456 = !DISubprogram(name: "operator-=", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEmIEl", scope: !1434, file: !1297, line: 168, type: !1447, scopeLine: 168, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1457 = !DISubprogram(name: "ilist_iterator", scope: !1434, file: !1297, line: 176, type: !1458, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1458 = !DISubroutineType(types: !1459)
!1459 = !{null, !1460, !1444}
!1460 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1434, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1461 = !DISubprogram(name: "ilist_iterator", scope: !1434, file: !1297, line: 177, type: !1462, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1462 = !DISubroutineType(types: !1463)
!1463 = !{null, !1460, !1464}
!1464 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1434, file: !1297, line: 156, baseType: !1465)
!1465 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1437, file: !617, line: 129, baseType: !1442)
!1466 = !DISubprogram(name: "ilist_iterator", scope: !1434, file: !1297, line: 178, type: !1467, scopeLine: 178, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1467 = !DISubroutineType(types: !1468)
!1468 = !{null, !1460}
!1469 = !DISubprogram(name: "operator llvm::MachineInstr *", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEcvPS1_Ev", scope: !1434, file: !1297, line: 195, type: !1470, scopeLine: 195, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1470 = !DISubroutineType(types: !1471)
!1471 = !{!1444, !1449}
!1472 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEdeEv", scope: !1434, file: !1297, line: 199, type: !1473, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1473 = !DISubroutineType(types: !1474)
!1474 = !{!1464, !1449}
!1475 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEptEv", scope: !1434, file: !1297, line: 202, type: !1470, scopeLine: 202, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1476 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEeqERKS2_", scope: !1434, file: !1297, line: 205, type: !1477, scopeLine: 205, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1477 = !DISubroutineType(types: !1478)
!1478 = !{!147, !1449, !1479}
!1479 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1450, size: 64)
!1480 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEEneERKS2_", scope: !1434, file: !1297, line: 208, type: !1477, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1481 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorINS_12MachineInstrEEmmEv", scope: !1434, file: !1297, line: 213, type: !1482, scopeLine: 213, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1482 = !DISubroutineType(types: !1483)
!1483 = !{!1484, !1460}
!1484 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1434, size: 64)
!1485 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorINS_12MachineInstrEEppEv", scope: !1434, file: !1297, line: 218, type: !1482, scopeLine: 218, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1486 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorINS_12MachineInstrEEmmEi", scope: !1434, file: !1297, line: 222, type: !1487, scopeLine: 222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1487 = !DISubroutineType(types: !1488)
!1488 = !{!1434, !1460, !220}
!1489 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorINS_12MachineInstrEEppEi", scope: !1434, file: !1297, line: 227, type: !1487, scopeLine: 227, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1490 = !DISubprogram(name: "getNodePtrUnchecked", linkageName: "_ZNK4llvm14ilist_iteratorINS_12MachineInstrEE19getNodePtrUncheckedEv", scope: !1434, file: !1297, line: 234, type: !1470, scopeLine: 234, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1491 = !{!1492}
!1492 = !DITemplateTypeParameter(name: "NodeTy", type: !83)
!1493 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringRef", scope: !14, file: !1494, line: 41, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1495, identifier: "_ZTSN4llvm9StringRefE")
!1494 = !DIFile(filename: "llvm34/include/llvm/ADT/StringRef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "5c2e300880041c873457392c89335431")
!1495 = !{!1496, !1498, !1499, !1500, !1503, !1504, !1507, !1511, !1514, !1517, !1527, !1533, !1534, !1537, !1540, !1543, !1546, !1547, !1550, !1551, !1554, !1555, !1556, !1559, !1562, !1565, !1566, !1567, !1568, !1569, !1570, !1573, !1576, !1577, !1580, !1581, !1582, !1583, !1584, !1585, !1586, !1587, !1588, !1591, !1592, !1597, !1598, !1599, !1602, !1605, !1606, !1607, !1665, !1668, !1673, !1674, !1677, !1678}
!1496 = !DIDerivedType(tag: DW_TAG_member, name: "npos", scope: !1493, file: !1494, line: 45, baseType: !1497, flags: DIFlagPublic | DIFlagStaticMember, extraData: i64 -1)
!1497 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1076)
!1498 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !1493, file: !1494, line: 50, baseType: !336, size: 64)
!1499 = !DIDerivedType(tag: DW_TAG_member, name: "Length", scope: !1493, file: !1494, line: 53, baseType: !1076, size: 64, offset: 64)
!1500 = !DISubprogram(name: "min", linkageName: "_ZN4llvm9StringRef3minEmm", scope: !1493, file: !1494, line: 58, type: !1501, scopeLine: 58, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1501 = !DISubroutineType(types: !1502)
!1502 = !{!1076, !1076, !1076}
!1503 = !DISubprogram(name: "max", linkageName: "_ZN4llvm9StringRef3maxEmm", scope: !1493, file: !1494, line: 59, type: !1501, scopeLine: 59, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1504 = !DISubprogram(name: "compareMemory", linkageName: "_ZN4llvm9StringRef13compareMemoryEPKcS2_m", scope: !1493, file: !1494, line: 63, type: !1505, scopeLine: 63, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1505 = !DISubroutineType(types: !1506)
!1506 = !{!220, !336, !336, !1076}
!1507 = !DISubprogram(name: "StringRef", scope: !1493, file: !1494, line: 73, type: !1508, scopeLine: 73, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1508 = !DISubroutineType(types: !1509)
!1509 = !{null, !1510}
!1510 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1493, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1511 = !DISubprogram(name: "StringRef", scope: !1493, file: !1494, line: 76, type: !1512, scopeLine: 76, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1512 = !DISubroutineType(types: !1513)
!1513 = !{null, !1510, !336}
!1514 = !DISubprogram(name: "StringRef", scope: !1493, file: !1494, line: 83, type: !1515, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1515 = !DISubroutineType(types: !1516)
!1516 = !{null, !1510, !336, !1076}
!1517 = !DISubprogram(name: "StringRef", scope: !1493, file: !1494, line: 90, type: !1518, scopeLine: 90, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1518 = !DISubroutineType(types: !1519)
!1519 = !{null, !1510, !1520}
!1520 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1521, size: 64)
!1521 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1522)
!1522 = !DIDerivedType(tag: DW_TAG_typedef, name: "string", scope: !1524, file: !1523, line: 74, baseType: !1525)
!1523 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stringfwd.h", directory: "")
!1524 = !DINamespace(name: "__cxx11", scope: !320, exportSymbols: true)
!1525 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "basic_string<char, std::char_traits<char>, std::allocator<char> >", scope: !1524, file: !1526, line: 1607, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE")
!1526 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.tcc", directory: "")
!1527 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm9StringRef5beginEv", scope: !1493, file: !1494, line: 97, type: !1528, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1528 = !DISubroutineType(types: !1529)
!1529 = !{!1530, !1531}
!1530 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1493, file: !1494, line: 43, baseType: !336)
!1531 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1532, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1532 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1493)
!1533 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm9StringRef3endEv", scope: !1493, file: !1494, line: 99, type: !1528, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1534 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm9StringRef4dataEv", scope: !1493, file: !1494, line: 107, type: !1535, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1535 = !DISubroutineType(types: !1536)
!1536 = !{!336, !1531}
!1537 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm9StringRef5emptyEv", scope: !1493, file: !1494, line: 110, type: !1538, scopeLine: 110, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1538 = !DISubroutineType(types: !1539)
!1539 = !{!147, !1531}
!1540 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm9StringRef4sizeEv", scope: !1493, file: !1494, line: 113, type: !1541, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1541 = !DISubroutineType(types: !1542)
!1542 = !{!1076, !1531}
!1543 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm9StringRef5frontEv", scope: !1493, file: !1494, line: 116, type: !1544, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1544 = !DISubroutineType(types: !1545)
!1545 = !{!338, !1531}
!1546 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm9StringRef4backEv", scope: !1493, file: !1494, line: 122, type: !1544, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1547 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm9StringRef6equalsES0_", scope: !1493, file: !1494, line: 129, type: !1548, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1548 = !DISubroutineType(types: !1549)
!1549 = !{!147, !1531, !1493}
!1550 = !DISubprogram(name: "equals_lower", linkageName: "_ZNK4llvm9StringRef12equals_lowerES0_", scope: !1493, file: !1494, line: 135, type: !1548, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1551 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm9StringRef7compareES0_", scope: !1493, file: !1494, line: 141, type: !1552, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1552 = !DISubroutineType(types: !1553)
!1553 = !{!220, !1531, !1493}
!1554 = !DISubprogram(name: "compare_lower", linkageName: "_ZNK4llvm9StringRef13compare_lowerES0_", scope: !1493, file: !1494, line: 153, type: !1552, scopeLine: 153, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1555 = !DISubprogram(name: "compare_numeric", linkageName: "_ZNK4llvm9StringRef15compare_numericES0_", scope: !1493, file: !1494, line: 157, type: !1552, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1556 = !DISubprogram(name: "edit_distance", linkageName: "_ZNK4llvm9StringRef13edit_distanceES0_bj", scope: !1493, file: !1494, line: 177, type: !1557, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1557 = !DISubroutineType(types: !1558)
!1558 = !{!6, !1531, !1493, !147, !6}
!1559 = !DISubprogram(name: "str", linkageName: "_ZNK4llvm9StringRef3strB5cxx11Ev", scope: !1493, file: !1494, line: 181, type: !1560, scopeLine: 181, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1560 = !DISubroutineType(types: !1561)
!1561 = !{!1522, !1531}
!1562 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm9StringRefixEm", scope: !1493, file: !1494, line: 190, type: !1563, scopeLine: 190, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1563 = !DISubroutineType(types: !1564)
!1564 = !{!338, !1531, !1076}
!1565 = !DISubprogram(name: "operator basic_string", linkageName: "_ZNK4llvm9StringRefcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv", scope: !1493, file: !1494, line: 199, type: !1560, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1566 = !DISubprogram(name: "startswith", linkageName: "_ZNK4llvm9StringRef10startswithES0_", scope: !1493, file: !1494, line: 208, type: !1548, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1567 = !DISubprogram(name: "startswith_lower", linkageName: "_ZNK4llvm9StringRef16startswith_lowerES0_", scope: !1493, file: !1494, line: 214, type: !1548, scopeLine: 214, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1568 = !DISubprogram(name: "endswith", linkageName: "_ZNK4llvm9StringRef8endswithES0_", scope: !1493, file: !1494, line: 217, type: !1548, scopeLine: 217, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1569 = !DISubprogram(name: "endswith_lower", linkageName: "_ZNK4llvm9StringRef14endswith_lowerES0_", scope: !1493, file: !1494, line: 223, type: !1548, scopeLine: 223, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1570 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm9StringRef4findEcm", scope: !1493, file: !1494, line: 233, type: !1571, scopeLine: 233, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1571 = !DISubroutineType(types: !1572)
!1572 = !{!1076, !1531, !338, !1076}
!1573 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm9StringRef4findES0_m", scope: !1493, file: !1494, line: 244, type: !1574, scopeLine: 244, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1574 = !DISubroutineType(types: !1575)
!1575 = !{!1076, !1531, !1493, !1076}
!1576 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm9StringRef5rfindEcm", scope: !1493, file: !1494, line: 250, type: !1571, scopeLine: 250, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1577 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm9StringRef5rfindES0_", scope: !1493, file: !1494, line: 265, type: !1578, scopeLine: 265, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1578 = !DISubroutineType(types: !1579)
!1579 = !{!1076, !1531, !1493}
!1580 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm9StringRef13find_first_ofEcm", scope: !1493, file: !1494, line: 269, type: !1571, scopeLine: 269, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1581 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm9StringRef13find_first_ofES0_m", scope: !1493, file: !1494, line: 277, type: !1574, scopeLine: 277, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1582 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm9StringRef17find_first_not_ofEcm", scope: !1493, file: !1494, line: 281, type: !1571, scopeLine: 281, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1583 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm9StringRef17find_first_not_ofES0_m", scope: !1493, file: !1494, line: 287, type: !1574, scopeLine: 287, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1584 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm9StringRef12find_last_ofEcm", scope: !1493, file: !1494, line: 291, type: !1571, scopeLine: 291, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1585 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm9StringRef12find_last_ofES0_m", scope: !1493, file: !1494, line: 299, type: !1574, scopeLine: 299, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1586 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNK4llvm9StringRef16find_last_not_ofEcm", scope: !1493, file: !1494, line: 303, type: !1571, scopeLine: 303, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1587 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNK4llvm9StringRef16find_last_not_ofES0_m", scope: !1493, file: !1494, line: 309, type: !1574, scopeLine: 309, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1588 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9StringRef5countEc", scope: !1493, file: !1494, line: 316, type: !1589, scopeLine: 316, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1589 = !DISubroutineType(types: !1590)
!1590 = !{!1076, !1531, !338}
!1591 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9StringRef5countES0_", scope: !1493, file: !1494, line: 326, type: !1578, scopeLine: 326, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1592 = !DISubprogram(name: "getAsInteger", linkageName: "_ZNK4llvm9StringRef12getAsIntegerEjRNS_5APIntE", scope: !1493, file: !1494, line: 367, type: !1593, scopeLine: 367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1593 = !DISubroutineType(types: !1594)
!1594 = !{!147, !1531, !6, !1595}
!1595 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1596, size: 64)
!1596 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "APInt", scope: !14, file: !1494, line: 24, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm5APIntE")
!1597 = !DISubprogram(name: "lower", linkageName: "_ZNK4llvm9StringRef5lowerB5cxx11Ev", scope: !1493, file: !1494, line: 374, type: !1560, scopeLine: 374, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1598 = !DISubprogram(name: "upper", linkageName: "_ZNK4llvm9StringRef5upperB5cxx11Ev", scope: !1493, file: !1494, line: 377, type: !1560, scopeLine: 377, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1599 = !DISubprogram(name: "substr", linkageName: "_ZNK4llvm9StringRef6substrEmm", scope: !1493, file: !1494, line: 392, type: !1600, scopeLine: 392, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1600 = !DISubroutineType(types: !1601)
!1601 = !{!1493, !1531, !1076, !1076}
!1602 = !DISubprogram(name: "drop_front", linkageName: "_ZNK4llvm9StringRef10drop_frontEm", scope: !1493, file: !1494, line: 399, type: !1603, scopeLine: 399, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1603 = !DISubroutineType(types: !1604)
!1604 = !{!1493, !1531, !1076}
!1605 = !DISubprogram(name: "drop_back", linkageName: "_ZNK4llvm9StringRef9drop_backEm", scope: !1493, file: !1494, line: 406, type: !1603, scopeLine: 406, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1606 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm9StringRef5sliceEmm", scope: !1493, file: !1494, line: 421, type: !1600, scopeLine: 421, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1607 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitEc", scope: !1493, file: !1494, line: 437, type: !1608, scopeLine: 437, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1608 = !DISubroutineType(types: !1609)
!1609 = !{!1610, !1531, !338}
!1610 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::StringRef, llvm::StringRef>", scope: !320, file: !893, line: 208, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1611, templateParams: !1662, identifier: "_ZTSSt4pairIN4llvm9StringRefES1_E")
!1611 = !{!1612, !1632, !1633, !1634, !1640, !1644, !1652, !1659}
!1612 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1610, baseType: !1613, flags: DIFlagPrivate, extraData: i32 0)
!1613 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::StringRef, llvm::StringRef>", scope: !320, file: !893, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !1614, templateParams: !1629, identifier: "_ZTSSt11__pair_baseIN4llvm9StringRefES1_E")
!1614 = !{!1615, !1619, !1620, !1625}
!1615 = !DISubprogram(name: "__pair_base", scope: !1613, file: !893, line: 194, type: !1616, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1616 = !DISubroutineType(types: !1617)
!1617 = !{null, !1618}
!1618 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1613, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1619 = !DISubprogram(name: "~__pair_base", scope: !1613, file: !893, line: 195, type: !1616, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1620 = !DISubprogram(name: "__pair_base", scope: !1613, file: !893, line: 196, type: !1621, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1621 = !DISubroutineType(types: !1622)
!1622 = !{null, !1618, !1623}
!1623 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1624, size: 64)
!1624 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1613)
!1625 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN4llvm9StringRefES1_EaSERKS2_", scope: !1613, file: !893, line: 197, type: !1626, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1626 = !DISubroutineType(types: !1627)
!1627 = !{!1628, !1618, !1623}
!1628 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1613, size: 64)
!1629 = !{!1630, !1631}
!1630 = !DITemplateTypeParameter(name: "_U1", type: !1493)
!1631 = !DITemplateTypeParameter(name: "_U2", type: !1493)
!1632 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !1610, file: !893, line: 214, baseType: !1493, size: 128)
!1633 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !1610, file: !893, line: 215, baseType: !1493, size: 128, offset: 128)
!1634 = !DISubprogram(name: "pair", scope: !1610, file: !893, line: 303, type: !1635, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1635 = !DISubroutineType(types: !1636)
!1636 = !{null, !1637, !1638}
!1637 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1610, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1638 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1639, size: 64)
!1639 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1610)
!1640 = !DISubprogram(name: "pair", scope: !1610, file: !893, line: 304, type: !1641, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1641 = !DISubroutineType(types: !1642)
!1642 = !{null, !1637, !1643}
!1643 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1610, size: 64)
!1644 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_EaSERKS2_", scope: !1610, file: !893, line: 378, type: !1645, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1645 = !DISubroutineType(types: !1646)
!1646 = !{!1647, !1637, !1648}
!1647 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1610, size: 64)
!1648 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1649, file: !788, line: 1928, baseType: !1638)
!1649 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::StringRef, llvm::StringRef> &, const std::__nonesuch_no_braces &>", scope: !320, file: !788, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !1650, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN4llvm9StringRefES2_ERKSt20__nonesuch_no_bracesE")
!1650 = !{!933, !1651, !935}
!1651 = !DITemplateTypeParameter(name: "_Iftrue", type: !1638)
!1652 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_EaSEOS2_", scope: !1610, file: !893, line: 389, type: !1653, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1653 = !DISubroutineType(types: !1654)
!1654 = !{!1647, !1637, !1655}
!1655 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1656, file: !788, line: 1928, baseType: !1643)
!1656 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::StringRef, llvm::StringRef> &&, std::__nonesuch_no_braces &&>", scope: !320, file: !788, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !1657, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN4llvm9StringRefES2_EOSt20__nonesuch_no_bracesE")
!1657 = !{!933, !1658, !946}
!1658 = !DITemplateTypeParameter(name: "_Iftrue", type: !1643)
!1659 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_E4swapERS2_", scope: !1610, file: !893, line: 424, type: !1660, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1660 = !DISubroutineType(types: !1661)
!1661 = !{null, !1637, !1647}
!1662 = !{!1663, !1664}
!1663 = !DITemplateTypeParameter(name: "_T1", type: !1493)
!1664 = !DITemplateTypeParameter(name: "_T2", type: !1493)
!1665 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitES0_", scope: !1493, file: !1494, line: 454, type: !1666, scopeLine: 454, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1666 = !DISubroutineType(types: !1667)
!1667 = !{!1610, !1531, !1493}
!1668 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitERNS_15SmallVectorImplIS0_EES0_ib", scope: !1493, file: !1494, line: 475, type: !1669, scopeLine: 475, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1669 = !DISubroutineType(types: !1670)
!1670 = !{null, !1531, !1671, !1493, !220, !147}
!1671 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1672, size: 64)
!1672 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<llvm::StringRef>", scope: !14, file: !1494, line: 23, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm15SmallVectorImplINS_9StringRefEEE")
!1673 = !DISubprogram(name: "rsplit", linkageName: "_ZNK4llvm9StringRef6rsplitEc", scope: !1493, file: !1494, line: 489, type: !1608, scopeLine: 489, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1674 = !DISubprogram(name: "ltrim", linkageName: "_ZNK4llvm9StringRef5ltrimES0_", scope: !1493, file: !1494, line: 498, type: !1675, scopeLine: 498, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1675 = !DISubroutineType(types: !1676)
!1676 = !{!1493, !1531, !1493}
!1677 = !DISubprogram(name: "rtrim", linkageName: "_ZNK4llvm9StringRef5rtrimES0_", scope: !1493, file: !1494, line: 504, type: !1675, scopeLine: 504, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1678 = !DISubprogram(name: "trim", linkageName: "_ZNK4llvm9StringRef4trimES0_", scope: !1493, file: !1494, line: 510, type: !1675, scopeLine: 510, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1679 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !1433, file: !1297, line: 345, baseType: !1680)
!1680 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ilist_iterator<const llvm::MachineInstr>", scope: !14, file: !1297, line: 145, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1681, templateParams: !1737, identifier: "_ZTSN4llvm14ilist_iteratorIKNS_12MachineInstrEEE")
!1681 = !{!1682, !1689, !1692, !1699, !1700, !1701, !1702, !1703, !1707, !1712, !1715, !1718, !1721, !1722, !1726, !1727, !1731, !1732, !1735, !1736}
!1682 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1680, baseType: !1683, flags: DIFlagPublic, extraData: i32 0)
!1683 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::bidirectional_iterator_tag, const llvm::MachineInstr, long, const llvm::MachineInstr *, const llvm::MachineInstr &>", scope: !320, file: !617, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !1684, identifier: "_ZTSSt8iteratorISt26bidirectional_iterator_tagKN4llvm12MachineInstrElPS3_RS3_E")
!1684 = !{!1304, !1685, !1316, !1686, !1687}
!1685 = !DITemplateTypeParameter(name: "_Tp", type: !264)
!1686 = !DITemplateTypeParameter(name: "_Pointer", type: !263)
!1687 = !DITemplateTypeParameter(name: "_Reference", type: !1688)
!1688 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !264, size: 64)
!1689 = !DIDerivedType(tag: DW_TAG_member, name: "NodePtr", scope: !1680, file: !1297, line: 158, baseType: !1690, size: 64)
!1690 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1680, file: !1297, line: 155, baseType: !1691)
!1691 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1683, file: !617, line: 127, baseType: !263)
!1692 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEixEl", scope: !1680, file: !1297, line: 164, type: !1693, scopeLine: 164, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1693 = !DISubroutineType(types: !1694)
!1694 = !{null, !1695, !1697}
!1695 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1696, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1696 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1680)
!1697 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1680, file: !1297, line: 154, baseType: !1698)
!1698 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1683, file: !617, line: 125, baseType: !23)
!1699 = !DISubprogram(name: "operator+", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEplEl", scope: !1680, file: !1297, line: 165, type: !1693, scopeLine: 165, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1700 = !DISubprogram(name: "operator-", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEmiEl", scope: !1680, file: !1297, line: 166, type: !1693, scopeLine: 166, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1701 = !DISubprogram(name: "operator+=", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEpLEl", scope: !1680, file: !1297, line: 167, type: !1693, scopeLine: 167, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1702 = !DISubprogram(name: "operator-=", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEmIEl", scope: !1680, file: !1297, line: 168, type: !1693, scopeLine: 168, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1703 = !DISubprogram(name: "ilist_iterator", scope: !1680, file: !1297, line: 176, type: !1704, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1704 = !DISubroutineType(types: !1705)
!1705 = !{null, !1706, !1690}
!1706 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1680, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1707 = !DISubprogram(name: "ilist_iterator", scope: !1680, file: !1297, line: 177, type: !1708, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1708 = !DISubroutineType(types: !1709)
!1709 = !{null, !1706, !1710}
!1710 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1680, file: !1297, line: 156, baseType: !1711)
!1711 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1683, file: !617, line: 129, baseType: !1688)
!1712 = !DISubprogram(name: "ilist_iterator", scope: !1680, file: !1297, line: 178, type: !1713, scopeLine: 178, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1713 = !DISubroutineType(types: !1714)
!1714 = !{null, !1706}
!1715 = !DISubprogram(name: "operator const llvm::MachineInstr *", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEcvPS2_Ev", scope: !1680, file: !1297, line: 195, type: !1716, scopeLine: 195, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1716 = !DISubroutineType(types: !1717)
!1717 = !{!1690, !1695}
!1718 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEdeEv", scope: !1680, file: !1297, line: 199, type: !1719, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1719 = !DISubroutineType(types: !1720)
!1720 = !{!1710, !1695}
!1721 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEptEv", scope: !1680, file: !1297, line: 202, type: !1716, scopeLine: 202, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1722 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEeqERKS3_", scope: !1680, file: !1297, line: 205, type: !1723, scopeLine: 205, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1723 = !DISubroutineType(types: !1724)
!1724 = !{!147, !1695, !1725}
!1725 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1696, size: 64)
!1726 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEEneERKS3_", scope: !1680, file: !1297, line: 208, type: !1723, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1727 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorIKNS_12MachineInstrEEmmEv", scope: !1680, file: !1297, line: 213, type: !1728, scopeLine: 213, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1728 = !DISubroutineType(types: !1729)
!1729 = !{!1730, !1706}
!1730 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1680, size: 64)
!1731 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorIKNS_12MachineInstrEEppEv", scope: !1680, file: !1297, line: 218, type: !1728, scopeLine: 218, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1732 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorIKNS_12MachineInstrEEmmEi", scope: !1680, file: !1297, line: 222, type: !1733, scopeLine: 222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1733 = !DISubroutineType(types: !1734)
!1734 = !{!1680, !1706, !220}
!1735 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorIKNS_12MachineInstrEEppEi", scope: !1680, file: !1297, line: 227, type: !1733, scopeLine: 227, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1736 = !DISubprogram(name: "getNodePtrUnchecked", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_12MachineInstrEE19getNodePtrUncheckedEv", scope: !1680, file: !1297, line: 234, type: !1716, scopeLine: 234, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1737 = !{!1738}
!1738 = !DITemplateTypeParameter(name: "NodeTy", type: !264)
!1739 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1741, file: !1740, line: 100, baseType: !1858)
!1740 = !DIFile(filename: "llvm34/include/llvm/ADT/SmallVector.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "69b512a6e55455ea0ed3a25fbee45d45")
!1741 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<std::pair<llvm::SlotIndex, llvm::SlotIndex>, void>", scope: !14, file: !1740, line: 66, size: 320, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1742, templateParams: !1915, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvEE")
!1742 = !{!1743, !1765, !1840, !1844, !1847, !1852, !1855, !1859, !1862, !1867, !1868, !1869, !1870, !1871, !1876, !1881, !1882, !1883, !1887, !1888, !1891, !1895, !1899, !1903, !1907, !1910, !1913, !1914}
!1743 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1741, baseType: !1744, flags: DIFlagPublic, extraData: i32 0)
!1744 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorBase", scope: !14, file: !1740, line: 33, size: 192, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1745, identifier: "_ZTSN4llvm15SmallVectorBaseE")
!1745 = !{!1746, !1747, !1748, !1749, !1753, !1756, !1761, !1762}
!1746 = !DIDerivedType(tag: DW_TAG_member, name: "BeginX", scope: !1744, file: !1740, line: 35, baseType: !132, size: 64, flags: DIFlagProtected)
!1747 = !DIDerivedType(tag: DW_TAG_member, name: "EndX", scope: !1744, file: !1740, line: 35, baseType: !132, size: 64, offset: 64, flags: DIFlagProtected)
!1748 = !DIDerivedType(tag: DW_TAG_member, name: "CapacityX", scope: !1744, file: !1740, line: 35, baseType: !132, size: 64, offset: 128, flags: DIFlagProtected)
!1749 = !DISubprogram(name: "SmallVectorBase", scope: !1744, file: !1740, line: 38, type: !1750, scopeLine: 38, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1750 = !DISubroutineType(types: !1751)
!1751 = !{null, !1752, !132, !1076}
!1752 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1744, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1753 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm15SmallVectorBase8grow_podEPvmm", scope: !1744, file: !1740, line: 43, type: !1754, scopeLine: 43, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1754 = !DISubroutineType(types: !1755)
!1755 = !{null, !1752, !132, !1076, !1076}
!1756 = !DISubprogram(name: "size_in_bytes", linkageName: "_ZNK4llvm15SmallVectorBase13size_in_bytesEv", scope: !1744, file: !1740, line: 47, type: !1757, scopeLine: 47, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1757 = !DISubroutineType(types: !1758)
!1758 = !{!1076, !1759}
!1759 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1760, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1760 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1744)
!1761 = !DISubprogram(name: "capacity_in_bytes", linkageName: "_ZNK4llvm15SmallVectorBase17capacity_in_bytesEv", scope: !1744, file: !1740, line: 52, type: !1757, scopeLine: 52, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1762 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm15SmallVectorBase5emptyEv", scope: !1744, file: !1740, line: 56, type: !1763, scopeLine: 56, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1763 = !DISubroutineType(types: !1764)
!1764 = !{!147, !1759}
!1765 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !1741, file: !1740, line: 74, baseType: !1766, size: 128, offset: 192)
!1766 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !1741, file: !1740, line: 73, baseType: !1767)
!1767 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<std::pair<llvm::SlotIndex, llvm::SlotIndex>, char, char, char, char, char, char>", scope: !14, file: !273, line: 199, size: 128, flags: DIFlagTypePassByValue, elements: !1768, templateParams: !1779, identifier: "_ZTSN4llvm21AlignedCharArrayUnionISt4pairINS_9SlotIndexES2_EccccccEE")
!1768 = !{!1769}
!1769 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1767, baseType: !1770, extraData: i32 0)
!1770 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<8UL, 16UL>", scope: !14, file: !273, line: 75, size: 128, flags: DIFlagTypePassByValue, elements: !1771, templateParams: !1776, identifier: "_ZTSN4llvm16AlignedCharArrayILm8ELm16EEE")
!1771 = !{!1772}
!1772 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !1770, file: !273, line: 76, baseType: !1773, size: 128, align: 64)
!1773 = !DICompositeType(tag: DW_TAG_array_type, baseType: !338, size: 128, elements: !1774)
!1774 = !{!1775}
!1775 = !DISubrange(count: 16)
!1776 = !{!1777, !1778}
!1777 = !DITemplateValueParameter(name: "Alignment", type: !283, value: i64 8)
!1778 = !DITemplateValueParameter(name: "Size", type: !283, value: i64 16)
!1779 = !{!1780, !1834, !1835, !1836, !1837, !1838, !1839}
!1780 = !DITemplateTypeParameter(name: "T1", type: !1781)
!1781 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::SlotIndex, llvm::SlotIndex>", scope: !320, file: !893, line: 208, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1782, templateParams: !1832, identifier: "_ZTSSt4pairIN4llvm9SlotIndexES1_E")
!1782 = !{!1783, !1802, !1803, !1804, !1810, !1814, !1822, !1829}
!1783 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1781, baseType: !1784, flags: DIFlagPrivate, extraData: i32 0)
!1784 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::SlotIndex, llvm::SlotIndex>", scope: !320, file: !893, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !1785, templateParams: !1800, identifier: "_ZTSSt11__pair_baseIN4llvm9SlotIndexES1_E")
!1785 = !{!1786, !1790, !1791, !1796}
!1786 = !DISubprogram(name: "__pair_base", scope: !1784, file: !893, line: 194, type: !1787, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1787 = !DISubroutineType(types: !1788)
!1788 = !{null, !1789}
!1789 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1784, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1790 = !DISubprogram(name: "~__pair_base", scope: !1784, file: !893, line: 195, type: !1787, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1791 = !DISubprogram(name: "__pair_base", scope: !1784, file: !893, line: 196, type: !1792, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1792 = !DISubroutineType(types: !1793)
!1793 = !{null, !1789, !1794}
!1794 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1795, size: 64)
!1795 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1784)
!1796 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN4llvm9SlotIndexES1_EaSERKS2_", scope: !1784, file: !893, line: 197, type: !1797, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1797 = !DISubroutineType(types: !1798)
!1798 = !{!1799, !1789, !1794}
!1799 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1784, size: 64)
!1800 = !{!1801, !914}
!1801 = !DITemplateTypeParameter(name: "_U1", type: !13)
!1802 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !1781, file: !893, line: 214, baseType: !13, size: 64)
!1803 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !1781, file: !893, line: 215, baseType: !13, size: 64, offset: 64)
!1804 = !DISubprogram(name: "pair", scope: !1781, file: !893, line: 303, type: !1805, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1805 = !DISubroutineType(types: !1806)
!1806 = !{null, !1807, !1808}
!1807 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1781, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1808 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1809, size: 64)
!1809 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1781)
!1810 = !DISubprogram(name: "pair", scope: !1781, file: !893, line: 304, type: !1811, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1811 = !DISubroutineType(types: !1812)
!1812 = !{null, !1807, !1813}
!1813 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1781, size: 64)
!1814 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9SlotIndexES1_EaSERKS2_", scope: !1781, file: !893, line: 378, type: !1815, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1815 = !DISubroutineType(types: !1816)
!1816 = !{!1817, !1807, !1818}
!1817 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1781, size: 64)
!1818 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1819, file: !788, line: 1928, baseType: !1808)
!1819 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::SlotIndex, llvm::SlotIndex> &, const std::__nonesuch_no_braces &>", scope: !320, file: !788, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !1820, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN4llvm9SlotIndexES2_ERKSt20__nonesuch_no_bracesE")
!1820 = !{!933, !1821, !935}
!1821 = !DITemplateTypeParameter(name: "_Iftrue", type: !1808)
!1822 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9SlotIndexES1_EaSEOS2_", scope: !1781, file: !893, line: 389, type: !1823, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1823 = !DISubroutineType(types: !1824)
!1824 = !{!1817, !1807, !1825}
!1825 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1826, file: !788, line: 1928, baseType: !1813)
!1826 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::SlotIndex, llvm::SlotIndex> &&, std::__nonesuch_no_braces &&>", scope: !320, file: !788, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !1827, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN4llvm9SlotIndexES2_EOSt20__nonesuch_no_bracesE")
!1827 = !{!933, !1828, !946}
!1828 = !DITemplateTypeParameter(name: "_Iftrue", type: !1813)
!1829 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN4llvm9SlotIndexES1_E4swapERS2_", scope: !1781, file: !893, line: 424, type: !1830, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1830 = !DISubroutineType(types: !1831)
!1831 = !{null, !1807, !1817}
!1832 = !{!1833, !953}
!1833 = !DITemplateTypeParameter(name: "_T1", type: !13)
!1834 = !DITemplateTypeParameter(name: "T2", type: !338, defaulted: true)
!1835 = !DITemplateTypeParameter(name: "T3", type: !338, defaulted: true)
!1836 = !DITemplateTypeParameter(name: "T4", type: !338, defaulted: true)
!1837 = !DITemplateTypeParameter(name: "T5", type: !338, defaulted: true)
!1838 = !DITemplateTypeParameter(name: "T6", type: !338, defaulted: true)
!1839 = !DITemplateTypeParameter(name: "T7", type: !338, defaulted: true)
!1840 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !1741, file: !1740, line: 78, type: !1841, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1841 = !DISubroutineType(types: !1842)
!1842 = !{null, !1843, !1076}
!1843 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1741, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1844 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE8grow_podEmm", scope: !1741, file: !1740, line: 80, type: !1845, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1845 = !DISubroutineType(types: !1846)
!1846 = !{null, !1843, !1076, !1076}
!1847 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE7isSmallEv", scope: !1741, file: !1740, line: 86, type: !1848, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1848 = !DISubroutineType(types: !1849)
!1849 = !{!147, !1850}
!1850 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1851, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1851 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1741)
!1852 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE12resetToSmallEv", scope: !1741, file: !1740, line: 91, type: !1853, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1853 = !DISubroutineType(types: !1854)
!1854 = !{null, !1843}
!1855 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE6setEndEPS3_", scope: !1741, file: !1740, line: 95, type: !1856, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1856 = !DISubroutineType(types: !1857)
!1857 = !{null, !1843, !1858}
!1858 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1781, size: 64)
!1859 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE5beginEv", scope: !1741, file: !1740, line: 112, type: !1860, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1860 = !DISubroutineType(types: !1861)
!1861 = !{!1739, !1843}
!1862 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE5beginEv", scope: !1741, file: !1740, line: 113, type: !1863, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1863 = !DISubroutineType(types: !1864)
!1864 = !{!1865, !1850}
!1865 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !1741, file: !1740, line: 101, baseType: !1866)
!1866 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1809, size: 64)
!1867 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE3endEv", scope: !1741, file: !1740, line: 114, type: !1860, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1868 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE3endEv", scope: !1741, file: !1740, line: 115, type: !1863, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1869 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE12capacity_ptrEv", scope: !1741, file: !1740, line: 117, type: !1860, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1870 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE12capacity_ptrEv", scope: !1741, file: !1740, line: 118, type: !1863, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1871 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE6rbeginEv", scope: !1741, file: !1740, line: 122, type: !1872, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1872 = !DISubroutineType(types: !1873)
!1873 = !{!1874, !1843}
!1874 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !1741, file: !1740, line: 104, baseType: !1875)
!1875 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<std::pair<llvm::SlotIndex, llvm::SlotIndex> *>", scope: !320, file: !600, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPSt4pairIN4llvm9SlotIndexES2_EE")
!1876 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE6rbeginEv", scope: !1741, file: !1740, line: 123, type: !1877, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1877 = !DISubroutineType(types: !1878)
!1878 = !{!1879, !1850}
!1879 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !1741, file: !1740, line: 103, baseType: !1880)
!1880 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const std::pair<llvm::SlotIndex, llvm::SlotIndex> *>", scope: !320, file: !600, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKSt4pairIN4llvm9SlotIndexES2_EE")
!1881 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE4rendEv", scope: !1741, file: !1740, line: 124, type: !1872, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1882 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE4rendEv", scope: !1741, file: !1740, line: 125, type: !1877, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1883 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE4sizeEv", scope: !1741, file: !1740, line: 127, type: !1884, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1884 = !DISubroutineType(types: !1885)
!1885 = !{!1886, !1850}
!1886 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !1740, line: 97, baseType: !1076)
!1887 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE8max_sizeEv", scope: !1741, file: !1740, line: 128, type: !1884, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1888 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE8capacityEv", scope: !1741, file: !1740, line: 132, type: !1889, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1889 = !DISubroutineType(types: !1890)
!1890 = !{!1076, !1850}
!1891 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE4dataEv", scope: !1741, file: !1740, line: 135, type: !1892, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1892 = !DISubroutineType(types: !1893)
!1893 = !{!1894, !1843}
!1894 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1741, file: !1740, line: 108, baseType: !1858)
!1895 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE4dataEv", scope: !1741, file: !1740, line: 137, type: !1896, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1896 = !DISubroutineType(types: !1897)
!1897 = !{!1898, !1850}
!1898 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !1741, file: !1740, line: 109, baseType: !1866)
!1899 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvEixEj", scope: !1741, file: !1740, line: 139, type: !1900, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1900 = !DISubroutineType(types: !1901)
!1901 = !{!1902, !1843, !6}
!1902 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1741, file: !1740, line: 106, baseType: !1817)
!1903 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvEixEj", scope: !1741, file: !1740, line: 143, type: !1904, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1904 = !DISubroutineType(types: !1905)
!1905 = !{!1906, !1850, !6}
!1906 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1741, file: !1740, line: 107, baseType: !1808)
!1907 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE5frontEv", scope: !1741, file: !1740, line: 148, type: !1908, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1908 = !DISubroutineType(types: !1909)
!1909 = !{!1902, !1843}
!1910 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE5frontEv", scope: !1741, file: !1740, line: 152, type: !1911, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1911 = !DISubroutineType(types: !1912)
!1912 = !{!1906, !1850}
!1913 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE4backEv", scope: !1741, file: !1740, line: 157, type: !1908, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1914 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexES2_EvE4backEv", scope: !1741, file: !1740, line: 161, type: !1911, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1915 = !{!1916, !1917}
!1916 = !DITemplateTypeParameter(name: "T", type: !1781)
!1917 = !DITemplateTypeParameter(type: null, defaulted: true)
!1918 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1919, file: !1297, line: 344, baseType: !1974)
!1919 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "iplist<llvm::IndexListEntry, llvm::ilist_traits<llvm::IndexListEntry> >", scope: !14, file: !1297, line: 313, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1920, templateParams: !2225, identifier: "_ZTSN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEEE")
!1920 = !{!1921, !2052, !2053, !2057, !2062, !2065, !2068, !2071, !2072, !2076, !2077, !2080, !2081, !2084, !2146, !2147, !2148, !2153, !2158, !2159, !2160, !2164, !2167, !2171, !2175, !2176, !2177, !2181, !2184, !2185, !2189, !2194, !2197, !2198, !2201, !2202, !2205, !2206, !2209, !2210, !2211, !2212, !2215, !2218, !2219, !2222, !2223, !2224}
!1921 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1919, baseType: !1922, flags: DIFlagPublic, extraData: i32 0)
!1922 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ilist_traits<llvm::IndexListEntry>", scope: !14, file: !12, line: 73, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1923, templateParams: !59, identifier: "_ZTSN4llvm12ilist_traitsINS_14IndexListEntryEEE")
!1923 = !{!1924, !2031, !2032, !2037, !2040, !2041, !2044, !2045, !2049}
!1924 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1922, baseType: !1925, extraData: i32 0)
!1925 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ilist_default_traits<llvm::IndexListEntry>", scope: !14, file: !1297, line: 127, size: 8, flags: DIFlagTypePassByValue, elements: !1926, templateParams: !59, identifier: "_ZTSN4llvm20ilist_default_traitsINS_14IndexListEntryEEE")
!1926 = !{!1927, !1942, !1957}
!1927 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1925, baseType: !1928, extraData: i32 0)
!1928 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ilist_nextprev_traits<llvm::IndexListEntry>", scope: !14, file: !1297, line: 56, size: 8, flags: DIFlagTypePassByValue, elements: !1929, templateParams: !59, identifier: "_ZTSN4llvm21ilist_nextprev_traitsINS_14IndexListEntryEEE")
!1929 = !{!1930, !1933, !1934, !1937, !1938, !1941}
!1930 = !DISubprogram(name: "getPrev", linkageName: "_ZN4llvm21ilist_nextprev_traitsINS_14IndexListEntryEE7getPrevEPS1_", scope: !1928, file: !1297, line: 57, type: !1931, scopeLine: 57, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1931 = !DISubroutineType(types: !1932)
!1932 = !{!31, !31}
!1933 = !DISubprogram(name: "getNext", linkageName: "_ZN4llvm21ilist_nextprev_traitsINS_14IndexListEntryEE7getNextEPS1_", scope: !1928, file: !1297, line: 58, type: !1931, scopeLine: 58, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1934 = !DISubprogram(name: "getPrev", linkageName: "_ZN4llvm21ilist_nextprev_traitsINS_14IndexListEntryEE7getPrevEPKS1_", scope: !1928, file: !1297, line: 59, type: !1935, scopeLine: 59, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1935 = !DISubroutineType(types: !1936)
!1936 = !{!49, !49}
!1937 = !DISubprogram(name: "getNext", linkageName: "_ZN4llvm21ilist_nextprev_traitsINS_14IndexListEntryEE7getNextEPKS1_", scope: !1928, file: !1297, line: 60, type: !1935, scopeLine: 60, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1938 = !DISubprogram(name: "setPrev", linkageName: "_ZN4llvm21ilist_nextprev_traitsINS_14IndexListEntryEE7setPrevEPS1_S3_", scope: !1928, file: !1297, line: 62, type: !1939, scopeLine: 62, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1939 = !DISubroutineType(types: !1940)
!1940 = !{null, !31, !31}
!1941 = !DISubprogram(name: "setNext", linkageName: "_ZN4llvm21ilist_nextprev_traitsINS_14IndexListEntryEE7setNextEPS1_S3_", scope: !1928, file: !1297, line: 63, type: !1939, scopeLine: 63, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1942 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1925, baseType: !1943, extraData: i32 0)
!1943 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ilist_sentinel_traits<llvm::IndexListEntry>", scope: !14, file: !1297, line: 76, size: 8, flags: DIFlagTypePassByValue, elements: !1944, templateParams: !59, identifier: "_ZTSN4llvm21ilist_sentinel_traitsINS_14IndexListEntryEEE")
!1944 = !{!1945, !1948, !1951, !1952, !1956}
!1945 = !DISubprogram(name: "createSentinel", linkageName: "_ZN4llvm21ilist_sentinel_traitsINS_14IndexListEntryEE14createSentinelEv", scope: !1943, file: !1297, line: 78, type: !1946, scopeLine: 78, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1946 = !DISubroutineType(types: !1947)
!1947 = !{!31}
!1948 = !DISubprogram(name: "destroySentinel", linkageName: "_ZN4llvm21ilist_sentinel_traitsINS_14IndexListEntryEE15destroySentinelEPS1_", scope: !1943, file: !1297, line: 81, type: !1949, scopeLine: 81, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1949 = !DISubroutineType(types: !1950)
!1950 = !{null, !31}
!1951 = !DISubprogram(name: "provideInitialHead", linkageName: "_ZN4llvm21ilist_sentinel_traitsINS_14IndexListEntryEE18provideInitialHeadEv", scope: !1943, file: !1297, line: 86, type: !1946, scopeLine: 86, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1952 = !DISubprogram(name: "ensureHead", linkageName: "_ZN4llvm21ilist_sentinel_traitsINS_14IndexListEntryEE10ensureHeadERPS1_", scope: !1943, file: !1297, line: 91, type: !1953, scopeLine: 91, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1953 = !DISubroutineType(types: !1954)
!1954 = !{!31, !1955}
!1955 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !31, size: 64)
!1956 = !DISubprogram(name: "noteHead", linkageName: "_ZN4llvm21ilist_sentinel_traitsINS_14IndexListEntryEE8noteHeadEPS1_S3_", scope: !1943, file: !1297, line: 102, type: !1939, scopeLine: 102, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1957 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1925, baseType: !1958, extraData: i32 0)
!1958 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ilist_node_traits<llvm::IndexListEntry>", scope: !14, file: !1297, line: 111, size: 8, flags: DIFlagTypePassByValue, elements: !1959, templateParams: !59, identifier: "_ZTSN4llvm17ilist_node_traitsINS_14IndexListEntryEEE")
!1959 = !{!1960, !1964, !1965, !1969, !1970}
!1960 = !DISubprogram(name: "createNode", linkageName: "_ZN4llvm17ilist_node_traitsINS_14IndexListEntryEE10createNodeERKS1_", scope: !1958, file: !1297, line: 112, type: !1961, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1961 = !DISubroutineType(types: !1962)
!1962 = !{!31, !1963}
!1963 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !50, size: 64)
!1964 = !DISubprogram(name: "deleteNode", linkageName: "_ZN4llvm17ilist_node_traitsINS_14IndexListEntryEE10deleteNodeEPS1_", scope: !1958, file: !1297, line: 113, type: !1949, scopeLine: 113, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1965 = !DISubprogram(name: "addNodeToList", linkageName: "_ZN4llvm17ilist_node_traitsINS_14IndexListEntryEE13addNodeToListEPS1_", scope: !1958, file: !1297, line: 115, type: !1966, scopeLine: 115, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1966 = !DISubroutineType(types: !1967)
!1967 = !{null, !1968, !31}
!1968 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1958, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1969 = !DISubprogram(name: "removeNodeFromList", linkageName: "_ZN4llvm17ilist_node_traitsINS_14IndexListEntryEE18removeNodeFromListEPS1_", scope: !1958, file: !1297, line: 116, type: !1966, scopeLine: 116, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1970 = !DISubprogram(name: "transferNodesFromList", linkageName: "_ZN4llvm17ilist_node_traitsINS_14IndexListEntryEE21transferNodesFromListERS2_NS_14ilist_iteratorIS1_EES5_", scope: !1958, file: !1297, line: 117, type: !1971, scopeLine: 117, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1971 = !DISubroutineType(types: !1972)
!1972 = !{null, !1968, !1973, !1974, !1974}
!1973 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1958, size: 64)
!1974 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ilist_iterator<llvm::IndexListEntry>", scope: !14, file: !1297, line: 145, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1975, templateParams: !59, identifier: "_ZTSN4llvm14ilist_iteratorINS_14IndexListEntryEEE")
!1975 = !{!1976, !1983, !1986, !1993, !1994, !1995, !1996, !1997, !2001, !2006, !2009, !2012, !2015, !2016, !2020, !2021, !2025, !2026, !2029, !2030}
!1976 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1974, baseType: !1977, flags: DIFlagPublic, extraData: i32 0)
!1977 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::bidirectional_iterator_tag, llvm::IndexListEntry, long, llvm::IndexListEntry *, llvm::IndexListEntry &>", scope: !320, file: !617, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !1978, identifier: "_ZTSSt8iteratorISt26bidirectional_iterator_tagN4llvm14IndexListEntryElPS2_RS2_E")
!1978 = !{!1304, !1979, !1316, !1980, !1981}
!1979 = !DITemplateTypeParameter(name: "_Tp", type: !32)
!1980 = !DITemplateTypeParameter(name: "_Pointer", type: !31)
!1981 = !DITemplateTypeParameter(name: "_Reference", type: !1982)
!1982 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !32, size: 64)
!1983 = !DIDerivedType(tag: DW_TAG_member, name: "NodePtr", scope: !1974, file: !1297, line: 158, baseType: !1984, size: 64)
!1984 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1974, file: !1297, line: 155, baseType: !1985)
!1985 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1977, file: !617, line: 127, baseType: !31)
!1986 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm14ilist_iteratorINS_14IndexListEntryEEixEl", scope: !1974, file: !1297, line: 164, type: !1987, scopeLine: 164, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1987 = !DISubroutineType(types: !1988)
!1988 = !{null, !1989, !1991}
!1989 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1990, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1990 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1974)
!1991 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1974, file: !1297, line: 154, baseType: !1992)
!1992 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1977, file: !617, line: 125, baseType: !23)
!1993 = !DISubprogram(name: "operator+", linkageName: "_ZNK4llvm14ilist_iteratorINS_14IndexListEntryEEplEl", scope: !1974, file: !1297, line: 165, type: !1987, scopeLine: 165, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1994 = !DISubprogram(name: "operator-", linkageName: "_ZNK4llvm14ilist_iteratorINS_14IndexListEntryEEmiEl", scope: !1974, file: !1297, line: 166, type: !1987, scopeLine: 166, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1995 = !DISubprogram(name: "operator+=", linkageName: "_ZNK4llvm14ilist_iteratorINS_14IndexListEntryEEpLEl", scope: !1974, file: !1297, line: 167, type: !1987, scopeLine: 167, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1996 = !DISubprogram(name: "operator-=", linkageName: "_ZNK4llvm14ilist_iteratorINS_14IndexListEntryEEmIEl", scope: !1974, file: !1297, line: 168, type: !1987, scopeLine: 168, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1997 = !DISubprogram(name: "ilist_iterator", scope: !1974, file: !1297, line: 176, type: !1998, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1998 = !DISubroutineType(types: !1999)
!1999 = !{null, !2000, !1984}
!2000 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1974, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2001 = !DISubprogram(name: "ilist_iterator", scope: !1974, file: !1297, line: 177, type: !2002, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2002 = !DISubroutineType(types: !2003)
!2003 = !{null, !2000, !2004}
!2004 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1974, file: !1297, line: 156, baseType: !2005)
!2005 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1977, file: !617, line: 129, baseType: !1982)
!2006 = !DISubprogram(name: "ilist_iterator", scope: !1974, file: !1297, line: 178, type: !2007, scopeLine: 178, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2007 = !DISubroutineType(types: !2008)
!2008 = !{null, !2000}
!2009 = !DISubprogram(name: "operator llvm::IndexListEntry *", linkageName: "_ZNK4llvm14ilist_iteratorINS_14IndexListEntryEEcvPS1_Ev", scope: !1974, file: !1297, line: 195, type: !2010, scopeLine: 195, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2010 = !DISubroutineType(types: !2011)
!2011 = !{!1984, !1989}
!2012 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm14ilist_iteratorINS_14IndexListEntryEEdeEv", scope: !1974, file: !1297, line: 199, type: !2013, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2013 = !DISubroutineType(types: !2014)
!2014 = !{!2004, !1989}
!2015 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm14ilist_iteratorINS_14IndexListEntryEEptEv", scope: !1974, file: !1297, line: 202, type: !2010, scopeLine: 202, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2016 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm14ilist_iteratorINS_14IndexListEntryEEeqERKS2_", scope: !1974, file: !1297, line: 205, type: !2017, scopeLine: 205, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2017 = !DISubroutineType(types: !2018)
!2018 = !{!147, !1989, !2019}
!2019 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1990, size: 64)
!2020 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm14ilist_iteratorINS_14IndexListEntryEEneERKS2_", scope: !1974, file: !1297, line: 208, type: !2017, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2021 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorINS_14IndexListEntryEEmmEv", scope: !1974, file: !1297, line: 213, type: !2022, scopeLine: 213, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2022 = !DISubroutineType(types: !2023)
!2023 = !{!2024, !2000}
!2024 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1974, size: 64)
!2025 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorINS_14IndexListEntryEEppEv", scope: !1974, file: !1297, line: 218, type: !2022, scopeLine: 218, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2026 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorINS_14IndexListEntryEEmmEi", scope: !1974, file: !1297, line: 222, type: !2027, scopeLine: 222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2027 = !DISubroutineType(types: !2028)
!2028 = !{!1974, !2000, !220}
!2029 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorINS_14IndexListEntryEEppEi", scope: !1974, file: !1297, line: 227, type: !2027, scopeLine: 227, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2030 = !DISubprogram(name: "getNodePtrUnchecked", linkageName: "_ZNK4llvm14ilist_iteratorINS_14IndexListEntryEE19getNodePtrUncheckedEv", scope: !1974, file: !1297, line: 234, type: !2010, scopeLine: 234, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2031 = !DIDerivedType(tag: DW_TAG_member, name: "Sentinel", scope: !1922, file: !12, line: 75, baseType: !39, size: 64, flags: DIFlagPrivate)
!2032 = !DISubprogram(name: "createSentinel", linkageName: "_ZNK4llvm12ilist_traitsINS_14IndexListEntryEE14createSentinelEv", scope: !1922, file: !12, line: 77, type: !2033, scopeLine: 77, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2033 = !DISubroutineType(types: !2034)
!2034 = !{!31, !2035}
!2035 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2036, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2036 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1922)
!2037 = !DISubprogram(name: "destroySentinel", linkageName: "_ZNK4llvm12ilist_traitsINS_14IndexListEntryEE15destroySentinelEPS1_", scope: !1922, file: !12, line: 80, type: !2038, scopeLine: 80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2038 = !DISubroutineType(types: !2039)
!2039 = !{null, !2035, !31}
!2040 = !DISubprogram(name: "provideInitialHead", linkageName: "_ZNK4llvm12ilist_traitsINS_14IndexListEntryEE18provideInitialHeadEv", scope: !1922, file: !12, line: 82, type: !2033, scopeLine: 82, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2041 = !DISubprogram(name: "ensureHead", linkageName: "_ZNK4llvm12ilist_traitsINS_14IndexListEntryEE10ensureHeadEPS1_", scope: !1922, file: !12, line: 83, type: !2042, scopeLine: 83, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2042 = !DISubroutineType(types: !2043)
!2043 = !{!31, !2035, !31}
!2044 = !DISubprogram(name: "noteHead", linkageName: "_ZN4llvm12ilist_traitsINS_14IndexListEntryEE8noteHeadEPS1_S3_", scope: !1922, file: !12, line: 84, type: !1939, scopeLine: 84, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2045 = !DISubprogram(name: "deleteNode", linkageName: "_ZN4llvm12ilist_traitsINS_14IndexListEntryEE10deleteNodeEPS1_", scope: !1922, file: !12, line: 85, type: !2046, scopeLine: 85, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2046 = !DISubroutineType(types: !2047)
!2047 = !{null, !2048, !31}
!2048 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1922, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2049 = !DISubprogram(name: "createNode", linkageName: "_ZN4llvm12ilist_traitsINS_14IndexListEntryEE10createNodeERKS1_", scope: !1922, file: !12, line: 88, type: !2050, scopeLine: 88, flags: DIFlagPrivate | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2050 = !DISubroutineType(types: !2051)
!2051 = !{null, !2048, !1963}
!2052 = !DIDerivedType(tag: DW_TAG_member, name: "Head", scope: !1919, file: !1297, line: 314, baseType: !31, size: 64, offset: 64)
!2053 = !DISubprogram(name: "getTail", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE7getTailEv", scope: !1919, file: !1297, line: 320, type: !2054, scopeLine: 320, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2054 = !DISubroutineType(types: !2055)
!2055 = !{!31, !2056}
!2056 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1919, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2057 = !DISubprogram(name: "getTail", linkageName: "_ZNK4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE7getTailEv", scope: !1919, file: !1297, line: 321, type: !2058, scopeLine: 321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2058 = !DISubroutineType(types: !2059)
!2059 = !{!49, !2060}
!2060 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2061, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2061 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1919)
!2062 = !DISubprogram(name: "setTail", linkageName: "_ZNK4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE7setTailEPS1_", scope: !1919, file: !1297, line: 322, type: !2063, scopeLine: 322, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2063 = !DISubroutineType(types: !2064)
!2064 = !{null, !2060, !31}
!2065 = !DISubprogram(name: "CreateLazySentinel", linkageName: "_ZNK4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE18CreateLazySentinelEv", scope: !1919, file: !1297, line: 326, type: !2066, scopeLine: 326, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2066 = !DISubroutineType(types: !2067)
!2067 = !{null, !2060}
!2068 = !DISubprogram(name: "op_less", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE7op_lessERS1_S5_", scope: !1919, file: !1297, line: 330, type: !2069, scopeLine: 330, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2069 = !DISubroutineType(types: !2070)
!2070 = !{!147, !1982, !1982}
!2071 = !DISubprogram(name: "op_equal", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE8op_equalERS1_S5_", scope: !1919, file: !1297, line: 331, type: !2069, scopeLine: 331, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2072 = !DISubprogram(name: "iplist", scope: !1919, file: !1297, line: 335, type: !2073, scopeLine: 335, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2073 = !DISubroutineType(types: !2074)
!2074 = !{null, !2056, !2075}
!2075 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2061, size: 64)
!2076 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEEaSERKS4_", scope: !1919, file: !1297, line: 336, type: !2073, scopeLine: 336, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2077 = !DISubprogram(name: "iplist", scope: !1919, file: !1297, line: 351, type: !2078, scopeLine: 351, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2078 = !DISubroutineType(types: !2079)
!2079 = !{null, !2056}
!2080 = !DISubprogram(name: "~iplist", scope: !1919, file: !1297, line: 352, type: !2078, scopeLine: 352, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2081 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE5beginEv", scope: !1919, file: !1297, line: 359, type: !2082, scopeLine: 359, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2082 = !DISubroutineType(types: !2083)
!2083 = !{!1918, !2056}
!2084 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE5beginEv", scope: !1919, file: !1297, line: 363, type: !2085, scopeLine: 363, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2085 = !DISubroutineType(types: !2086)
!2086 = !{!2087, !2060}
!2087 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !1919, file: !1297, line: 345, baseType: !2088)
!2088 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ilist_iterator<const llvm::IndexListEntry>", scope: !14, file: !1297, line: 145, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2089, templateParams: !2144, identifier: "_ZTSN4llvm14ilist_iteratorIKNS_14IndexListEntryEEE")
!2089 = !{!2090, !2096, !2099, !2106, !2107, !2108, !2109, !2110, !2114, !2119, !2122, !2125, !2128, !2129, !2133, !2134, !2138, !2139, !2142, !2143}
!2090 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2088, baseType: !2091, flags: DIFlagPublic, extraData: i32 0)
!2091 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::bidirectional_iterator_tag, const llvm::IndexListEntry, long, const llvm::IndexListEntry *, const llvm::IndexListEntry &>", scope: !320, file: !617, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !2092, identifier: "_ZTSSt8iteratorISt26bidirectional_iterator_tagKN4llvm14IndexListEntryElPS3_RS3_E")
!2092 = !{!1304, !2093, !1316, !2094, !2095}
!2093 = !DITemplateTypeParameter(name: "_Tp", type: !50)
!2094 = !DITemplateTypeParameter(name: "_Pointer", type: !49)
!2095 = !DITemplateTypeParameter(name: "_Reference", type: !1963)
!2096 = !DIDerivedType(tag: DW_TAG_member, name: "NodePtr", scope: !2088, file: !1297, line: 158, baseType: !2097, size: 64)
!2097 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2088, file: !1297, line: 155, baseType: !2098)
!2098 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2091, file: !617, line: 127, baseType: !49)
!2099 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_14IndexListEntryEEixEl", scope: !2088, file: !1297, line: 164, type: !2100, scopeLine: 164, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2100 = !DISubroutineType(types: !2101)
!2101 = !{null, !2102, !2104}
!2102 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2103, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2103 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2088)
!2104 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !2088, file: !1297, line: 154, baseType: !2105)
!2105 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !2091, file: !617, line: 125, baseType: !23)
!2106 = !DISubprogram(name: "operator+", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_14IndexListEntryEEplEl", scope: !2088, file: !1297, line: 165, type: !2100, scopeLine: 165, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2107 = !DISubprogram(name: "operator-", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_14IndexListEntryEEmiEl", scope: !2088, file: !1297, line: 166, type: !2100, scopeLine: 166, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2108 = !DISubprogram(name: "operator+=", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_14IndexListEntryEEpLEl", scope: !2088, file: !1297, line: 167, type: !2100, scopeLine: 167, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2109 = !DISubprogram(name: "operator-=", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_14IndexListEntryEEmIEl", scope: !2088, file: !1297, line: 168, type: !2100, scopeLine: 168, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2110 = !DISubprogram(name: "ilist_iterator", scope: !2088, file: !1297, line: 176, type: !2111, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2111 = !DISubroutineType(types: !2112)
!2112 = !{null, !2113, !2097}
!2113 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2088, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2114 = !DISubprogram(name: "ilist_iterator", scope: !2088, file: !1297, line: 177, type: !2115, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2115 = !DISubroutineType(types: !2116)
!2116 = !{null, !2113, !2117}
!2117 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2088, file: !1297, line: 156, baseType: !2118)
!2118 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2091, file: !617, line: 129, baseType: !1963)
!2119 = !DISubprogram(name: "ilist_iterator", scope: !2088, file: !1297, line: 178, type: !2120, scopeLine: 178, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2120 = !DISubroutineType(types: !2121)
!2121 = !{null, !2113}
!2122 = !DISubprogram(name: "operator const llvm::IndexListEntry *", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_14IndexListEntryEEcvPS2_Ev", scope: !2088, file: !1297, line: 195, type: !2123, scopeLine: 195, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2123 = !DISubroutineType(types: !2124)
!2124 = !{!2097, !2102}
!2125 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_14IndexListEntryEEdeEv", scope: !2088, file: !1297, line: 199, type: !2126, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2126 = !DISubroutineType(types: !2127)
!2127 = !{!2117, !2102}
!2128 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_14IndexListEntryEEptEv", scope: !2088, file: !1297, line: 202, type: !2123, scopeLine: 202, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2129 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_14IndexListEntryEEeqERKS3_", scope: !2088, file: !1297, line: 205, type: !2130, scopeLine: 205, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2130 = !DISubroutineType(types: !2131)
!2131 = !{!147, !2102, !2132}
!2132 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2103, size: 64)
!2133 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_14IndexListEntryEEneERKS3_", scope: !2088, file: !1297, line: 208, type: !2130, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2134 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorIKNS_14IndexListEntryEEmmEv", scope: !2088, file: !1297, line: 213, type: !2135, scopeLine: 213, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2135 = !DISubroutineType(types: !2136)
!2136 = !{!2137, !2113}
!2137 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2088, size: 64)
!2138 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorIKNS_14IndexListEntryEEppEv", scope: !2088, file: !1297, line: 218, type: !2135, scopeLine: 218, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2139 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm14ilist_iteratorIKNS_14IndexListEntryEEmmEi", scope: !2088, file: !1297, line: 222, type: !2140, scopeLine: 222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2140 = !DISubroutineType(types: !2141)
!2141 = !{!2088, !2113, !220}
!2142 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm14ilist_iteratorIKNS_14IndexListEntryEEppEi", scope: !2088, file: !1297, line: 227, type: !2140, scopeLine: 227, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2143 = !DISubprogram(name: "getNodePtrUnchecked", linkageName: "_ZNK4llvm14ilist_iteratorIKNS_14IndexListEntryEE19getNodePtrUncheckedEv", scope: !2088, file: !1297, line: 234, type: !2123, scopeLine: 234, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2144 = !{!2145}
!2145 = !DITemplateTypeParameter(name: "NodeTy", type: !50)
!2146 = !DISubprogram(name: "end", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE3endEv", scope: !1919, file: !1297, line: 367, type: !2082, scopeLine: 367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2147 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE3endEv", scope: !1919, file: !1297, line: 371, type: !2085, scopeLine: 371, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2148 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE6rbeginEv", scope: !1919, file: !1297, line: 377, type: !2149, scopeLine: 377, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2149 = !DISubroutineType(types: !2150)
!2150 = !{!2151, !2056}
!2151 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !1919, file: !1297, line: 349, baseType: !2152)
!2152 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<llvm::ilist_iterator<llvm::IndexListEntry> >", scope: !320, file: !600, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN4llvm14ilist_iteratorINS0_14IndexListEntryEEEE")
!2153 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE6rbeginEv", scope: !1919, file: !1297, line: 378, type: !2154, scopeLine: 378, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2154 = !DISubroutineType(types: !2155)
!2155 = !{!2156, !2060}
!2156 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !1919, file: !1297, line: 348, baseType: !2157)
!2157 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<llvm::ilist_iterator<const llvm::IndexListEntry> >", scope: !320, file: !600, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN4llvm14ilist_iteratorIKNS0_14IndexListEntryEEEE")
!2158 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE4rendEv", scope: !1919, file: !1297, line: 379, type: !2149, scopeLine: 379, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2159 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE4rendEv", scope: !1919, file: !1297, line: 380, type: !2154, scopeLine: 380, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2160 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE8max_sizeEv", scope: !1919, file: !1297, line: 384, type: !2161, scopeLine: 384, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2161 = !DISubroutineType(types: !2162)
!2162 = !{!2163, !2060}
!2163 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !1297, line: 346, baseType: !1076)
!2164 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE5emptyEv", scope: !1919, file: !1297, line: 385, type: !2165, scopeLine: 385, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2165 = !DISubroutineType(types: !2166)
!2166 = !{!147, !2060}
!2167 = !DISubprogram(name: "front", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE5frontEv", scope: !1919, file: !1297, line: 390, type: !2168, scopeLine: 390, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2168 = !DISubroutineType(types: !2169)
!2169 = !{!2170, !2056}
!2170 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1919, file: !1297, line: 341, baseType: !1982)
!2171 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE5frontEv", scope: !1919, file: !1297, line: 394, type: !2172, scopeLine: 394, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2172 = !DISubroutineType(types: !2173)
!2173 = !{!2174, !2060}
!2174 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1919, file: !1297, line: 342, baseType: !1963)
!2175 = !DISubprogram(name: "back", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE4backEv", scope: !1919, file: !1297, line: 398, type: !2168, scopeLine: 398, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2176 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE4backEv", scope: !1919, file: !1297, line: 402, type: !2172, scopeLine: 402, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2177 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE4swapERS4_", scope: !1919, file: !1297, line: 407, type: !2178, scopeLine: 407, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2178 = !DISubroutineType(types: !2179)
!2179 = !{null, !2056, !2180}
!2180 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1919, size: 64)
!2181 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE6insertENS_14ilist_iteratorIS1_EEPS1_", scope: !1919, file: !1297, line: 412, type: !2182, scopeLine: 412, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2182 = !DISubroutineType(types: !2183)
!2183 = !{!1918, !2056, !1918, !31}
!2184 = !DISubprogram(name: "insertAfter", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE11insertAfterENS_14ilist_iteratorIS1_EEPS1_", scope: !1919, file: !1297, line: 428, type: !2182, scopeLine: 428, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2185 = !DISubprogram(name: "remove", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE6removeERNS_14ilist_iteratorIS1_EE", scope: !1919, file: !1297, line: 435, type: !2186, scopeLine: 435, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2186 = !DISubroutineType(types: !2187)
!2187 = !{!31, !2056, !2188}
!2188 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1918, size: 64)
!2189 = !DISubprogram(name: "remove", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE6removeERKNS_14ilist_iteratorIS1_EE", scope: !1919, file: !1297, line: 459, type: !2190, scopeLine: 459, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2190 = !DISubroutineType(types: !2191)
!2191 = !{!31, !2056, !2192}
!2192 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2193, size: 64)
!2193 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1918)
!2194 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE5eraseENS_14ilist_iteratorIS1_EE", scope: !1919, file: !1297, line: 465, type: !2195, scopeLine: 465, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2195 = !DISubroutineType(types: !2196)
!2196 = !{!1918, !2056, !1918}
!2197 = !DISubprogram(name: "clearAndLeakNodesUnsafely", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE25clearAndLeakNodesUnsafelyEv", scope: !1919, file: !1297, line: 475, type: !2078, scopeLine: 475, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2198 = !DISubprogram(name: "transfer", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE8transferENS_14ilist_iteratorIS1_EERS4_S6_S6_", scope: !1919, file: !1297, line: 486, type: !2199, scopeLine: 486, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2199 = !DISubroutineType(types: !2200)
!2200 = !{null, !2056, !1918, !2180, !1918, !1918}
!2201 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE4sizeEv", scope: !1919, file: !1297, line: 539, type: !2161, scopeLine: 539, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2202 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE5eraseENS_14ilist_iteratorIS1_EES6_", scope: !1919, file: !1297, line: 544, type: !2203, scopeLine: 544, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2203 = !DISubroutineType(types: !2204)
!2204 = !{!1918, !2056, !1918, !1918}
!2205 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE5clearEv", scope: !1919, file: !1297, line: 550, type: !2078, scopeLine: 550, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2206 = !DISubprogram(name: "push_front", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE10push_frontEPS1_", scope: !1919, file: !1297, line: 553, type: !2207, scopeLine: 553, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2207 = !DISubroutineType(types: !2208)
!2208 = !{null, !2056, !31}
!2209 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE9push_backEPS1_", scope: !1919, file: !1297, line: 554, type: !2207, scopeLine: 554, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2210 = !DISubprogram(name: "pop_front", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE9pop_frontEv", scope: !1919, file: !1297, line: 555, type: !2078, scopeLine: 555, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2211 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE8pop_backEv", scope: !1919, file: !1297, line: 559, type: !2078, scopeLine: 559, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2212 = !DISubprogram(name: "splice", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE6spliceENS_14ilist_iteratorIS1_EERS4_", scope: !1919, file: !1297, line: 570, type: !2213, scopeLine: 570, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2213 = !DISubroutineType(types: !2214)
!2214 = !{null, !2056, !1918, !2180}
!2215 = !DISubprogram(name: "splice", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE6spliceENS_14ilist_iteratorIS1_EERS4_S6_", scope: !1919, file: !1297, line: 574, type: !2216, scopeLine: 574, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2216 = !DISubroutineType(types: !2217)
!2217 = !{null, !2056, !1918, !2180, !1918}
!2218 = !DISubprogram(name: "splice", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE6spliceENS_14ilist_iteratorIS1_EERS4_S6_S6_", scope: !1919, file: !1297, line: 579, type: !2199, scopeLine: 579, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2219 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE5eraseERKS1_", scope: !1919, file: !1297, line: 592, type: !2220, scopeLine: 592, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2220 = !DISubroutineType(types: !2221)
!2221 = !{null, !2056, !1963}
!2222 = !DISubprogram(name: "unique", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE6uniqueEv", scope: !1919, file: !1297, line: 617, type: !2078, scopeLine: 617, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2223 = !DISubprogram(name: "merge", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE5mergeERS4_", scope: !1919, file: !1297, line: 632, type: !2178, scopeLine: 632, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2224 = !DISubprogram(name: "sort", linkageName: "_ZN4llvm6iplistINS_14IndexListEntryENS_12ilist_traitsIS1_EEE4sortEv", scope: !1919, file: !1297, line: 635, type: !2078, scopeLine: 635, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2225 = !{!60, !2226}
!2226 = !DITemplateTypeParameter(name: "Traits", type: !1922)
!2227 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1065, size: 64)
!2228 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2229, file: !1740, line: 100, baseType: !2310)
!2229 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<std::pair<llvm::SlotIndex, llvm::MachineBasicBlock *>, void>", scope: !14, file: !1740, line: 66, size: 320, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2230, templateParams: !2366, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvEE")
!2230 = !{!2231, !2232, !2292, !2296, !2299, !2304, !2307, !2311, !2314, !2319, !2320, !2321, !2322, !2323, !2328, !2333, !2334, !2335, !2338, !2339, !2342, !2346, !2350, !2354, !2358, !2361, !2364, !2365}
!2231 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2229, baseType: !1744, flags: DIFlagPublic, extraData: i32 0)
!2232 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !2229, file: !1740, line: 74, baseType: !2233, size: 128, offset: 192)
!2233 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !2229, file: !1740, line: 73, baseType: !2234)
!2234 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<std::pair<llvm::SlotIndex, llvm::MachineBasicBlock *>, char, char, char, char, char, char>", scope: !14, file: !273, line: 199, size: 128, flags: DIFlagTypePassByValue, elements: !2235, templateParams: !2237, identifier: "_ZTSN4llvm21AlignedCharArrayUnionISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEccccccEE")
!2235 = !{!2236}
!2236 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2234, baseType: !1770, extraData: i32 0)
!2237 = !{!2238, !1834, !1835, !1836, !1837, !1838, !1839}
!2238 = !DITemplateTypeParameter(name: "T1", type: !2239)
!2239 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::SlotIndex, llvm::MachineBasicBlock *>", scope: !320, file: !893, line: 208, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2240, templateParams: !2290, identifier: "_ZTSSt4pairIN4llvm9SlotIndexEPNS0_17MachineBasicBlockEE")
!2240 = !{!2241, !2260, !2261, !2262, !2268, !2272, !2280, !2287}
!2241 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2239, baseType: !2242, flags: DIFlagPrivate, extraData: i32 0)
!2242 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::SlotIndex, llvm::MachineBasicBlock *>", scope: !320, file: !893, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !2243, templateParams: !2258, identifier: "_ZTSSt11__pair_baseIN4llvm9SlotIndexEPNS0_17MachineBasicBlockEE")
!2243 = !{!2244, !2248, !2249, !2254}
!2244 = !DISubprogram(name: "__pair_base", scope: !2242, file: !893, line: 194, type: !2245, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2245 = !DISubroutineType(types: !2246)
!2246 = !{null, !2247}
!2247 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2242, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2248 = !DISubprogram(name: "~__pair_base", scope: !2242, file: !893, line: 195, type: !2245, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2249 = !DISubprogram(name: "__pair_base", scope: !2242, file: !893, line: 196, type: !2250, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2250 = !DISubroutineType(types: !2251)
!2251 = !{null, !2247, !2252}
!2252 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2253, size: 64)
!2253 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2242)
!2254 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN4llvm9SlotIndexEPNS0_17MachineBasicBlockEEaSERKS4_", scope: !2242, file: !893, line: 197, type: !2255, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2255 = !DISubroutineType(types: !2256)
!2256 = !{!2257, !2247, !2252}
!2257 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2242, size: 64)
!2258 = !{!1801, !2259}
!2259 = !DITemplateTypeParameter(name: "_U2", type: !1371)
!2260 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !2239, file: !893, line: 214, baseType: !13, size: 64)
!2261 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !2239, file: !893, line: 215, baseType: !1371, size: 64, offset: 64)
!2262 = !DISubprogram(name: "pair", scope: !2239, file: !893, line: 303, type: !2263, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2263 = !DISubroutineType(types: !2264)
!2264 = !{null, !2265, !2266}
!2265 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2239, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2266 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2267, size: 64)
!2267 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2239)
!2268 = !DISubprogram(name: "pair", scope: !2239, file: !893, line: 304, type: !2269, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2269 = !DISubroutineType(types: !2270)
!2270 = !{null, !2265, !2271}
!2271 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2239, size: 64)
!2272 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9SlotIndexEPNS0_17MachineBasicBlockEEaSERKS4_", scope: !2239, file: !893, line: 378, type: !2273, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2273 = !DISubroutineType(types: !2274)
!2274 = !{!2275, !2265, !2276}
!2275 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2239, size: 64)
!2276 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2277, file: !788, line: 1928, baseType: !2266)
!2277 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::SlotIndex, llvm::MachineBasicBlock *> &, const std::__nonesuch_no_braces &>", scope: !320, file: !788, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !2278, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN4llvm9SlotIndexEPNS1_17MachineBasicBlockEERKSt20__nonesuch_no_bracesE")
!2278 = !{!933, !2279, !935}
!2279 = !DITemplateTypeParameter(name: "_Iftrue", type: !2266)
!2280 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9SlotIndexEPNS0_17MachineBasicBlockEEaSEOS4_", scope: !2239, file: !893, line: 389, type: !2281, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2281 = !DISubroutineType(types: !2282)
!2282 = !{!2275, !2265, !2283}
!2283 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2284, file: !788, line: 1928, baseType: !2271)
!2284 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::SlotIndex, llvm::MachineBasicBlock *> &&, std::__nonesuch_no_braces &&>", scope: !320, file: !788, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !2285, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN4llvm9SlotIndexEPNS1_17MachineBasicBlockEEOSt20__nonesuch_no_bracesE")
!2285 = !{!933, !2286, !946}
!2286 = !DITemplateTypeParameter(name: "_Iftrue", type: !2271)
!2287 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN4llvm9SlotIndexEPNS0_17MachineBasicBlockEE4swapERS4_", scope: !2239, file: !893, line: 424, type: !2288, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2288 = !DISubroutineType(types: !2289)
!2289 = !{null, !2265, !2275}
!2290 = !{!1833, !2291}
!2291 = !DITemplateTypeParameter(name: "_T2", type: !1371)
!2292 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !2229, file: !1740, line: 78, type: !2293, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2293 = !DISubroutineType(types: !2294)
!2294 = !{null, !2295, !1076}
!2295 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2229, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2296 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE8grow_podEmm", scope: !2229, file: !1740, line: 80, type: !2297, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2297 = !DISubroutineType(types: !2298)
!2298 = !{null, !2295, !1076, !1076}
!2299 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE7isSmallEv", scope: !2229, file: !1740, line: 86, type: !2300, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2300 = !DISubroutineType(types: !2301)
!2301 = !{!147, !2302}
!2302 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2303, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2303 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2229)
!2304 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE12resetToSmallEv", scope: !2229, file: !1740, line: 91, type: !2305, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2305 = !DISubroutineType(types: !2306)
!2306 = !{null, !2295}
!2307 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE6setEndEPS5_", scope: !2229, file: !1740, line: 95, type: !2308, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2308 = !DISubroutineType(types: !2309)
!2309 = !{null, !2295, !2310}
!2310 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2239, size: 64)
!2311 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE5beginEv", scope: !2229, file: !1740, line: 112, type: !2312, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2312 = !DISubroutineType(types: !2313)
!2313 = !{!2228, !2295}
!2314 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE5beginEv", scope: !2229, file: !1740, line: 113, type: !2315, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2315 = !DISubroutineType(types: !2316)
!2316 = !{!2317, !2302}
!2317 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !2229, file: !1740, line: 101, baseType: !2318)
!2318 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2267, size: 64)
!2319 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE3endEv", scope: !2229, file: !1740, line: 114, type: !2312, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2320 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE3endEv", scope: !2229, file: !1740, line: 115, type: !2315, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2321 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE12capacity_ptrEv", scope: !2229, file: !1740, line: 117, type: !2312, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2322 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE12capacity_ptrEv", scope: !2229, file: !1740, line: 118, type: !2315, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2323 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE6rbeginEv", scope: !2229, file: !1740, line: 122, type: !2324, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2324 = !DISubroutineType(types: !2325)
!2325 = !{!2326, !2295}
!2326 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !2229, file: !1740, line: 104, baseType: !2327)
!2327 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<std::pair<llvm::SlotIndex, llvm::MachineBasicBlock *> *>", scope: !320, file: !600, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPSt4pairIN4llvm9SlotIndexEPNS1_17MachineBasicBlockEEE")
!2328 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE6rbeginEv", scope: !2229, file: !1740, line: 123, type: !2329, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2329 = !DISubroutineType(types: !2330)
!2330 = !{!2331, !2302}
!2331 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !2229, file: !1740, line: 103, baseType: !2332)
!2332 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const std::pair<llvm::SlotIndex, llvm::MachineBasicBlock *> *>", scope: !320, file: !600, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKSt4pairIN4llvm9SlotIndexEPNS1_17MachineBasicBlockEEE")
!2333 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE4rendEv", scope: !2229, file: !1740, line: 124, type: !2324, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2334 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE4rendEv", scope: !2229, file: !1740, line: 125, type: !2329, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2335 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE4sizeEv", scope: !2229, file: !1740, line: 127, type: !2336, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2336 = !DISubroutineType(types: !2337)
!2337 = !{!1886, !2302}
!2338 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE8max_sizeEv", scope: !2229, file: !1740, line: 128, type: !2336, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2339 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE8capacityEv", scope: !2229, file: !1740, line: 132, type: !2340, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2340 = !DISubroutineType(types: !2341)
!2341 = !{!1076, !2302}
!2342 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE4dataEv", scope: !2229, file: !1740, line: 135, type: !2343, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2343 = !DISubroutineType(types: !2344)
!2344 = !{!2345, !2295}
!2345 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2229, file: !1740, line: 108, baseType: !2310)
!2346 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE4dataEv", scope: !2229, file: !1740, line: 137, type: !2347, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2347 = !DISubroutineType(types: !2348)
!2348 = !{!2349, !2302}
!2349 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !2229, file: !1740, line: 109, baseType: !2318)
!2350 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvEixEj", scope: !2229, file: !1740, line: 139, type: !2351, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2351 = !DISubroutineType(types: !2352)
!2352 = !{!2353, !2295, !6}
!2353 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2229, file: !1740, line: 106, baseType: !2275)
!2354 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvEixEj", scope: !2229, file: !1740, line: 143, type: !2355, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2355 = !DISubroutineType(types: !2356)
!2356 = !{!2357, !2302, !6}
!2357 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !2229, file: !1740, line: 107, baseType: !2266)
!2358 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE5frontEv", scope: !2229, file: !1740, line: 148, type: !2359, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2359 = !DISubroutineType(types: !2360)
!2360 = !{!2353, !2295}
!2361 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE5frontEv", scope: !2229, file: !1740, line: 152, type: !2362, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2362 = !DISubroutineType(types: !2363)
!2363 = !{!2357, !2302}
!2364 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE4backEv", scope: !2229, file: !1740, line: 157, type: !2359, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2365 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEvE4backEv", scope: !2229, file: !1740, line: 161, type: !2362, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2366 = !{!2367, !1917}
!2367 = !DITemplateTypeParameter(name: "T", type: !2239)
!2368 = !DIDerivedType(tag: DW_TAG_typedef, name: "_DistanceType", scope: !2370, file: !2369, line: 249, baseType: !2409)
!2369 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_heap.h", directory: "", checksumkind: CSK_MD5, checksum: "14882d5d8b49113d741f2e45566d69ea")
!2370 = distinct !DISubprogram(name: "__pop_heap<std::pair<llvm::SlotIndex, llvm::MachineBasicBlock *> *, __gnu_cxx::__ops::_Iter_comp_iter<llvm::Idx2MBBCompare> >", linkageName: "_ZSt10__pop_heapIPSt4pairIN4llvm9SlotIndexEPNS1_17MachineBasicBlockEEN9__gnu_cxx5__ops15_Iter_comp_iterINS1_14Idx2MBBCompareEEEEvT_SC_SC_RT0_", scope: !320, file: !2369, line: 243, type: !2371, scopeLine: 245, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !2406, retainedNodes: !2395)
!2371 = !DISubroutineType(types: !2372)
!2372 = !{null, !2310, !2310, !2310, !2373}
!2373 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2374, size: 64)
!2374 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Iter_comp_iter<llvm::Idx2MBBCompare>", scope: !2376, file: !2375, line: 130, size: 8, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2377, templateParams: !2393, identifier: "_ZTSN9__gnu_cxx5__ops15_Iter_comp_iterIN4llvm14Idx2MBBCompareEEE")
!2375 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/predefined_ops.h", directory: "", checksumkind: CSK_MD5, checksum: "c4488885b044d9477796f6d04761c9e8")
!2376 = !DINamespace(name: "__ops", scope: !5)
!2377 = !{!2378, !2389}
!2378 = !DIDerivedType(tag: DW_TAG_member, name: "_M_comp", scope: !2374, file: !2375, line: 132, baseType: !2379, size: 8)
!2379 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "Idx2MBBCompare", scope: !14, file: !12, line: 325, size: 8, flags: DIFlagTypePassByValue, elements: !2380, identifier: "_ZTSN4llvm14Idx2MBBCompareE")
!2380 = !{!2381}
!2381 = !DISubprogram(name: "operator()", linkageName: "_ZNK4llvm14Idx2MBBCompareclERKSt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEES7_", scope: !2379, file: !12, line: 326, type: !2382, scopeLine: 326, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2382 = !DISubroutineType(types: !2383)
!2383 = !{!147, !2384, !2386, !2386}
!2384 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2385, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2385 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2379)
!2386 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2387, size: 64)
!2387 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2388)
!2388 = !DIDerivedType(tag: DW_TAG_typedef, name: "IdxMBBPair", scope: !14, file: !12, line: 315, baseType: !2239)
!2389 = !DISubprogram(name: "_Iter_comp_iter", scope: !2374, file: !2375, line: 135, type: !2390, scopeLine: 135, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2390 = !DISubroutineType(types: !2391)
!2391 = !{null, !2392, !2379}
!2392 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2374, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2393 = !{!2394}
!2394 = !DITemplateTypeParameter(name: "_Compare", type: !2379)
!2395 = !{!2396, !2397, !2398, !2399, !2400}
!2396 = !DILocalVariable(name: "__first", arg: 1, scope: !2370, file: !2369, line: 243, type: !2310)
!2397 = !DILocalVariable(name: "__last", arg: 2, scope: !2370, file: !2369, line: 243, type: !2310)
!2398 = !DILocalVariable(name: "__result", arg: 3, scope: !2370, file: !2369, line: 244, type: !2310)
!2399 = !DILocalVariable(name: "__comp", arg: 4, scope: !2370, file: !2369, line: 244, type: !2373)
!2400 = !DILocalVariable(name: "__value", scope: !2370, file: !2369, line: 251, type: !2401)
!2401 = !DIDerivedType(tag: DW_TAG_typedef, name: "_ValueType", scope: !2370, file: !2369, line: 247, baseType: !2402)
!2402 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !2403, file: !617, line: 181, baseType: !2239)
!2403 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<std::pair<llvm::SlotIndex, llvm::MachineBasicBlock *> *>", scope: !320, file: !617, line: 178, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !2404, identifier: "_ZTSSt15iterator_traitsIPSt4pairIN4llvm9SlotIndexEPNS1_17MachineBasicBlockEEE")
!2404 = !{!2405}
!2405 = !DITemplateTypeParameter(name: "_Iterator", type: !2310)
!2406 = !{!2407, !2408}
!2407 = !DITemplateTypeParameter(name: "_RandomAccessIterator", type: !2310)
!2408 = !DITemplateTypeParameter(name: "_Compare", type: !2374)
!2409 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !2403, file: !617, line: 182, baseType: !642)
!2410 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Val_comp_iter<llvm::Idx2MBBCompare>", scope: !2376, file: !2375, line: 191, size: 8, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2411, templateParams: !2393, identifier: "_ZTSN9__gnu_cxx5__ops14_Val_comp_iterIN4llvm14Idx2MBBCompareEEE")
!2411 = !{!2412, !2413, !2417, !2422}
!2412 = !DIDerivedType(tag: DW_TAG_member, name: "_M_comp", scope: !2410, file: !2375, line: 193, baseType: !2379, size: 8)
!2413 = !DISubprogram(name: "_Val_comp_iter", scope: !2410, file: !2375, line: 196, type: !2414, scopeLine: 196, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2414 = !DISubroutineType(types: !2415)
!2415 = !{null, !2416, !2379}
!2416 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2410, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2417 = !DISubprogram(name: "_Val_comp_iter", scope: !2410, file: !2375, line: 201, type: !2418, scopeLine: 201, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2418 = !DISubroutineType(types: !2419)
!2419 = !{null, !2416, !2420}
!2420 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2421, size: 64)
!2421 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2374)
!2422 = !DISubprogram(name: "_Val_comp_iter", scope: !2410, file: !2375, line: 207, type: !2423, scopeLine: 207, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2423 = !DISubroutineType(types: !2424)
!2424 = !{null, !2416, !2425}
!2425 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2374, size: 64)
!2426 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SlotIndexes", scope: !14, file: !12, line: 334, size: 3648, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2427, vtableHolder: !852)
!2427 = !{!2428, !2431, !2469, !2473, !2475, !2594, !2709, !2712, !2713, !2717, !2720, !2723, !2731, !2732, !2736, !2739, !2740, !2790, !2793, !2794, !2797, !2800, !2803, !2806, !2807, !2808, !2811, !2814, !2817, !2820, !2821, !2822, !2825, !2830, !2833, !2836, !2839, !2842, !2845}
!2428 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2426, baseType: !2429, flags: DIFlagPublic, extraData: i32 0)
!2429 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MachineFunctionPass", scope: !14, file: !2430, line: 32, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm19MachineFunctionPassE")
!2430 = !DIFile(filename: "llvm34/include/llvm/CodeGen/MachineFunctionPass.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "74cc7fb7c82e767959d97cc024180cc7")
!2431 = !DIDerivedType(tag: DW_TAG_member, name: "indexList", scope: !2426, file: !12, line: 338, baseType: !2432, size: 128, offset: 256)
!2432 = !DIDerivedType(tag: DW_TAG_typedef, name: "IndexList", scope: !2426, file: !12, line: 337, baseType: !2433)
!2433 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "ilist<llvm::IndexListEntry>", scope: !14, file: !1297, line: 640, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2434, templateParams: !59, identifier: "_ZTSN4llvm5ilistINS_14IndexListEntryEEE")
!2434 = !{!2435, !2436, !2440, !2445, !2450, !2453, !2457, !2460, !2461, !2464, !2465, !2468}
!2435 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2433, baseType: !1919, extraData: i32 0)
!2436 = !DISubprogram(name: "ilist", scope: !2433, file: !1297, line: 644, type: !2437, scopeLine: 644, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2437 = !DISubroutineType(types: !2438)
!2438 = !{null, !2439}
!2439 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2433, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2440 = !DISubprogram(name: "ilist", scope: !2433, file: !1297, line: 645, type: !2441, scopeLine: 645, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2441 = !DISubroutineType(types: !2442)
!2442 = !{null, !2439, !2443}
!2443 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2444, size: 64)
!2444 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2433)
!2445 = !DISubprogram(name: "ilist", scope: !2433, file: !1297, line: 648, type: !2446, scopeLine: 648, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2446 = !DISubroutineType(types: !2447)
!2447 = !{null, !2439, !2448}
!2448 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2433, file: !1297, line: 641, baseType: !2449)
!2449 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1919, file: !1297, line: 346, baseType: !1076)
!2450 = !DISubprogram(name: "ilist", scope: !2433, file: !1297, line: 651, type: !2451, scopeLine: 651, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2451 = !DISubroutineType(types: !2452)
!2452 = !{null, !2439, !2448, !1963}
!2453 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm5ilistINS_14IndexListEntryEE6insertENS_14ilist_iteratorIS1_EERKS1_", scope: !2433, file: !1297, line: 664, type: !2454, scopeLine: 664, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2454 = !DISubroutineType(types: !2455)
!2455 = !{!2456, !2439, !2456, !1963}
!2456 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2433, file: !1297, line: 642, baseType: !1918)
!2457 = !DISubprogram(name: "push_front", linkageName: "_ZN4llvm5ilistINS_14IndexListEntryEE10push_frontERKS1_", scope: !2433, file: !1297, line: 670, type: !2458, scopeLine: 670, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2458 = !DISubroutineType(types: !2459)
!2459 = !{null, !2439, !1963}
!2460 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm5ilistINS_14IndexListEntryEE9push_backERKS1_", scope: !2433, file: !1297, line: 671, type: !2458, scopeLine: 671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2461 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm5ilistINS_14IndexListEntryEE6insertENS_14ilist_iteratorIS1_EEmRKS1_", scope: !2433, file: !1297, line: 673, type: !2462, scopeLine: 673, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2462 = !DISubroutineType(types: !2463)
!2463 = !{null, !2439, !2456, !2448, !1963}
!2464 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm5ilistINS_14IndexListEntryEE6assignEmRKS1_", scope: !2433, file: !1297, line: 678, type: !2451, scopeLine: 678, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2465 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm5ilistINS_14IndexListEntryEE6resizeEmS1_", scope: !2433, file: !1297, line: 699, type: !2466, scopeLine: 699, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2466 = !DISubroutineType(types: !2467)
!2467 = !{null, !2439, !2448, !32}
!2468 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm5ilistINS_14IndexListEntryEE6resizeEm", scope: !2433, file: !1297, line: 709, type: !2446, scopeLine: 709, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2469 = !DIDerivedType(tag: DW_TAG_member, name: "mf", scope: !2426, file: !12, line: 344, baseType: !2470, size: 64, offset: 384)
!2470 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2471, size: 64)
!2471 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MachineFunction", scope: !14, file: !2472, line: 75, size: 2752, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm15MachineFunctionE")
!2472 = !DIFile(filename: "llvm34/include/llvm/CodeGen/MachineFunction.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "6679f105617a991eecf4f4903ade0d6f")
!2473 = !DIDerivedType(tag: DW_TAG_member, name: "mi2iMap", scope: !2426, file: !12, line: 347, baseType: !2474, size: 192, offset: 448)
!2474 = !DIDerivedType(tag: DW_TAG_typedef, name: "Mi2IndexMap", scope: !2426, file: !12, line: 346, baseType: !870)
!2475 = !DIDerivedType(tag: DW_TAG_member, name: "MBBRanges", scope: !2426, file: !12, line: 350, baseType: !2476, size: 1216, offset: 640)
!2476 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<std::pair<llvm::SlotIndex, llvm::SlotIndex>, 8U>", scope: !14, file: !1740, line: 880, size: 1216, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2477, templateParams: !2570, identifier: "_ZTSN4llvm11SmallVectorISt4pairINS_9SlotIndexES2_ELj8EEE")
!2477 = !{!2478, !2563, !2572, !2576, !2579, !2584, !2587, !2591}
!2478 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2476, baseType: !2479, flags: DIFlagPublic, extraData: i32 0)
!2479 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<std::pair<llvm::SlotIndex, llvm::SlotIndex> >", scope: !14, file: !1740, line: 371, size: 320, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2480, templateParams: !2562, identifier: "_ZTSN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EEE")
!2480 = !{!2481, !2501, !2507, !2510, !2513, !2514, !2515, !2518, !2519, !2522, !2526, !2531, !2532, !2536, !2539, !2542, !2545, !2548, !2551, !2555, !2559, !2560, !2561}
!2481 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2479, baseType: !2482, flags: DIFlagPublic, extraData: i32 0)
!2482 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<std::pair<llvm::SlotIndex, llvm::SlotIndex>, true>", scope: !14, file: !1740, line: 296, size: 320, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2483, templateParams: !2499, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseISt4pairINS_9SlotIndexES2_ELb1EEE")
!2483 = !{!2484, !2485, !2489, !2492, !2493, !2496}
!2484 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2482, baseType: !1741, flags: DIFlagPublic, extraData: i32 0)
!2485 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !2482, file: !1740, line: 298, type: !2486, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2486 = !DISubroutineType(types: !2487)
!2487 = !{null, !2488, !1076}
!2488 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2482, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2489 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseISt4pairINS_9SlotIndexES2_ELb1EE13destroy_rangeEPS3_S5_", scope: !2482, file: !1740, line: 301, type: !2490, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2490 = !DISubroutineType(types: !2491)
!2491 = !{null, !1858, !1858}
!2492 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseISt4pairINS_9SlotIndexES2_ELb1EE4growEm", scope: !2482, file: !1740, line: 346, type: !2486, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2493 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseISt4pairINS_9SlotIndexES2_ELb1EE9push_backERKS3_", scope: !2482, file: !1740, line: 350, type: !2494, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2494 = !DISubroutineType(types: !2495)
!2495 = !{null, !2488, !1808}
!2496 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseISt4pairINS_9SlotIndexES2_ELb1EE8pop_backEv", scope: !2482, file: !1740, line: 361, type: !2497, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2497 = !DISubroutineType(types: !2498)
!2498 = !{null, !2488}
!2499 = !{!1916, !2500}
!2500 = !DITemplateValueParameter(name: "isPodLike", type: !147, value: i8 1)
!2501 = !DISubprogram(name: "SmallVectorImpl", scope: !2479, file: !1740, line: 374, type: !2502, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2502 = !DISubroutineType(types: !2503)
!2503 = !{null, !2504, !2505}
!2504 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2479, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2505 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2506, size: 64)
!2506 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2479)
!2507 = !DISubprogram(name: "SmallVectorImpl", scope: !2479, file: !1740, line: 381, type: !2508, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2508 = !DISubroutineType(types: !2509)
!2509 = !{null, !2504, !6}
!2510 = !DISubprogram(name: "~SmallVectorImpl", scope: !2479, file: !1740, line: 386, type: !2511, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2511 = !DISubroutineType(types: !2512)
!2512 = !{null, !2504}
!2513 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EE5clearEv", scope: !2479, file: !1740, line: 396, type: !2511, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2514 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EE6resizeEj", scope: !2479, file: !1740, line: 401, type: !2508, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2515 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EE6resizeEjRKS3_", scope: !2479, file: !1740, line: 413, type: !2516, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2516 = !DISubroutineType(types: !2517)
!2517 = !{null, !2504, !6, !1808}
!2518 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EE7reserveEj", scope: !2479, file: !1740, line: 425, type: !2508, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2519 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EE12pop_back_valEv", scope: !2479, file: !1740, line: 430, type: !2520, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2520 = !DISubroutineType(types: !2521)
!2521 = !{!1781, !2504}
!2522 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EE4swapERS4_", scope: !2479, file: !1740, line: 440, type: !2523, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2523 = !DISubroutineType(types: !2524)
!2524 = !{null, !2504, !2525}
!2525 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2479, size: 64)
!2526 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EE6appendEmRKS3_", scope: !2479, file: !1740, line: 460, type: !2527, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2527 = !DISubroutineType(types: !2528)
!2528 = !{null, !2504, !2529, !1808}
!2529 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2479, file: !1740, line: 377, baseType: !2530)
!2530 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1741, file: !1740, line: 97, baseType: !1076)
!2531 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EE6assignEjRKS3_", scope: !2479, file: !1740, line: 470, type: !2516, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2532 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EE5eraseEPS3_", scope: !2479, file: !1740, line: 478, type: !2533, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2533 = !DISubroutineType(types: !2534)
!2534 = !{!2535, !2504, !2535}
!2535 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2479, file: !1740, line: 376, baseType: !1739)
!2536 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EE5eraseEPS3_S5_", scope: !2479, file: !1740, line: 490, type: !2537, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2537 = !DISubroutineType(types: !2538)
!2538 = !{!2535, !2504, !2535, !2535}
!2539 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EE6insertEPS3_OS3_", scope: !2479, file: !1740, line: 505, type: !2540, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2540 = !DISubroutineType(types: !2541)
!2541 = !{!2535, !2504, !2535, !1813}
!2542 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EE6insertEPS3_RKS3_", scope: !2479, file: !1740, line: 537, type: !2543, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2543 = !DISubroutineType(types: !2544)
!2544 = !{!2535, !2504, !2535, !1808}
!2545 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EE6insertEPS3_mRKS3_", scope: !2479, file: !1740, line: 568, type: !2546, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2546 = !DISubroutineType(types: !2547)
!2547 = !{!2535, !2504, !2535, !2529, !1808}
!2548 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EEaSERKS4_", scope: !2479, file: !1740, line: 674, type: !2549, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2549 = !DISubroutineType(types: !2550)
!2550 = !{!2525, !2504, !2505}
!2551 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EEaSEOS4_", scope: !2479, file: !1740, line: 677, type: !2552, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2552 = !DISubroutineType(types: !2553)
!2553 = !{!2525, !2504, !2554}
!2554 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2479, size: 64)
!2555 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EEeqERKS4_", scope: !2479, file: !1740, line: 680, type: !2556, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2556 = !DISubroutineType(types: !2557)
!2557 = !{!147, !2558, !2505}
!2558 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2506, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2559 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EEneERKS4_", scope: !2479, file: !1740, line: 684, type: !2556, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2560 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EEltERKS4_", scope: !2479, file: !1740, line: 688, type: !2556, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2561 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexES2_EE8set_sizeEj", scope: !2479, file: !1740, line: 702, type: !2508, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2562 = !{!1916}
!2563 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !2476, file: !1740, line: 882, baseType: !2564, size: 896, offset: 320)
!2564 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<std::pair<llvm::SlotIndex, llvm::SlotIndex>, 8U>", scope: !14, file: !1740, line: 865, size: 896, flags: DIFlagTypePassByValue, elements: !2565, templateParams: !2570, identifier: "_ZTSN4llvm18SmallVectorStorageISt4pairINS_9SlotIndexES2_ELj8EEE")
!2565 = !{!2566}
!2566 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !2564, file: !1740, line: 866, baseType: !2567, size: 896)
!2567 = !DICompositeType(tag: DW_TAG_array_type, baseType: !1766, size: 896, elements: !2568)
!2568 = !{!2569}
!2569 = !DISubrange(count: 7)
!2570 = !{!1916, !2571}
!2571 = !DITemplateValueParameter(name: "N", type: !6, value: i32 8)
!2572 = !DISubprogram(name: "SmallVector", scope: !2476, file: !1740, line: 884, type: !2573, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2573 = !DISubroutineType(types: !2574)
!2574 = !{null, !2575}
!2575 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2476, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2576 = !DISubprogram(name: "SmallVector", scope: !2476, file: !1740, line: 887, type: !2577, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2577 = !DISubroutineType(types: !2578)
!2578 = !{null, !2575, !6, !1808}
!2579 = !DISubprogram(name: "SmallVector", scope: !2476, file: !1740, line: 897, type: !2580, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2580 = !DISubroutineType(types: !2581)
!2581 = !{null, !2575, !2582}
!2582 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2583, size: 64)
!2583 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2476)
!2584 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorISt4pairINS_9SlotIndexES2_ELj8EEaSERKS4_", scope: !2476, file: !1740, line: 902, type: !2585, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2585 = !DISubroutineType(types: !2586)
!2586 = !{!2582, !2575, !2582}
!2587 = !DISubprogram(name: "SmallVector", scope: !2476, file: !1740, line: 908, type: !2588, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2588 = !DISubroutineType(types: !2589)
!2589 = !{null, !2575, !2590}
!2590 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2476, size: 64)
!2591 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorISt4pairINS_9SlotIndexES2_ELj8EEaSEOS4_", scope: !2476, file: !1740, line: 913, type: !2592, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2592 = !DISubroutineType(types: !2593)
!2593 = !{!2582, !2575, !2590}
!2594 = !DIDerivedType(tag: DW_TAG_member, name: "idx2MBBMap", scope: !2426, file: !12, line: 354, baseType: !2595, size: 1216, offset: 1856)
!2595 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<std::pair<llvm::SlotIndex, llvm::MachineBasicBlock *>, 8U>", scope: !14, file: !1740, line: 880, size: 1216, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2596, templateParams: !2686, identifier: "_ZTSN4llvm11SmallVectorISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEELj8EEE")
!2596 = !{!2597, !2681, !2687, !2691, !2694, !2699, !2702, !2706}
!2597 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2595, baseType: !2598, flags: DIFlagPublic, extraData: i32 0)
!2598 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<std::pair<llvm::SlotIndex, llvm::MachineBasicBlock *> >", scope: !14, file: !1740, line: 371, size: 320, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2599, templateParams: !2680, identifier: "_ZTSN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEEE")
!2599 = !{!2600, !2619, !2625, !2628, !2631, !2632, !2633, !2636, !2637, !2640, !2644, !2649, !2650, !2654, !2657, !2660, !2663, !2666, !2669, !2673, !2677, !2678, !2679}
!2600 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2598, baseType: !2601, flags: DIFlagPublic, extraData: i32 0)
!2601 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<std::pair<llvm::SlotIndex, llvm::MachineBasicBlock *>, true>", scope: !14, file: !1740, line: 296, size: 320, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2602, templateParams: !2618, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEELb1EEE")
!2602 = !{!2603, !2604, !2608, !2611, !2612, !2615}
!2603 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2601, baseType: !2229, flags: DIFlagPublic, extraData: i32 0)
!2604 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !2601, file: !1740, line: 298, type: !2605, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2605 = !DISubroutineType(types: !2606)
!2606 = !{null, !2607, !1076}
!2607 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2601, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2608 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEELb1EE13destroy_rangeEPS5_S7_", scope: !2601, file: !1740, line: 301, type: !2609, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2609 = !DISubroutineType(types: !2610)
!2610 = !{null, !2310, !2310}
!2611 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEELb1EE4growEm", scope: !2601, file: !1740, line: 346, type: !2605, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2612 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEELb1EE9push_backERKS5_", scope: !2601, file: !1740, line: 350, type: !2613, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2613 = !DISubroutineType(types: !2614)
!2614 = !{null, !2607, !2266}
!2615 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEELb1EE8pop_backEv", scope: !2601, file: !1740, line: 361, type: !2616, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2616 = !DISubroutineType(types: !2617)
!2617 = !{null, !2607}
!2618 = !{!2367, !2500}
!2619 = !DISubprogram(name: "SmallVectorImpl", scope: !2598, file: !1740, line: 374, type: !2620, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2620 = !DISubroutineType(types: !2621)
!2621 = !{null, !2622, !2623}
!2622 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2598, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2623 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2624, size: 64)
!2624 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2598)
!2625 = !DISubprogram(name: "SmallVectorImpl", scope: !2598, file: !1740, line: 381, type: !2626, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2626 = !DISubroutineType(types: !2627)
!2627 = !{null, !2622, !6}
!2628 = !DISubprogram(name: "~SmallVectorImpl", scope: !2598, file: !1740, line: 386, type: !2629, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2629 = !DISubroutineType(types: !2630)
!2630 = !{null, !2622}
!2631 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEE5clearEv", scope: !2598, file: !1740, line: 396, type: !2629, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2632 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEE6resizeEj", scope: !2598, file: !1740, line: 401, type: !2626, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2633 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEE6resizeEjRKS5_", scope: !2598, file: !1740, line: 413, type: !2634, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2634 = !DISubroutineType(types: !2635)
!2635 = !{null, !2622, !6, !2266}
!2636 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEE7reserveEj", scope: !2598, file: !1740, line: 425, type: !2626, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2637 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEE12pop_back_valEv", scope: !2598, file: !1740, line: 430, type: !2638, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2638 = !DISubroutineType(types: !2639)
!2639 = !{!2239, !2622}
!2640 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEE4swapERS6_", scope: !2598, file: !1740, line: 440, type: !2641, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2641 = !DISubroutineType(types: !2642)
!2642 = !{null, !2622, !2643}
!2643 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2598, size: 64)
!2644 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEE6appendEmRKS5_", scope: !2598, file: !1740, line: 460, type: !2645, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2645 = !DISubroutineType(types: !2646)
!2646 = !{null, !2622, !2647, !2266}
!2647 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2598, file: !1740, line: 377, baseType: !2648)
!2648 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2229, file: !1740, line: 97, baseType: !1076)
!2649 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEE6assignEjRKS5_", scope: !2598, file: !1740, line: 470, type: !2634, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2650 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEE5eraseEPS5_", scope: !2598, file: !1740, line: 478, type: !2651, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2651 = !DISubroutineType(types: !2652)
!2652 = !{!2653, !2622, !2653}
!2653 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2598, file: !1740, line: 376, baseType: !2228)
!2654 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEE5eraseEPS5_S7_", scope: !2598, file: !1740, line: 490, type: !2655, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2655 = !DISubroutineType(types: !2656)
!2656 = !{!2653, !2622, !2653, !2653}
!2657 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEE6insertEPS5_OS5_", scope: !2598, file: !1740, line: 505, type: !2658, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2658 = !DISubroutineType(types: !2659)
!2659 = !{!2653, !2622, !2653, !2271}
!2660 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEE6insertEPS5_RKS5_", scope: !2598, file: !1740, line: 537, type: !2661, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2661 = !DISubroutineType(types: !2662)
!2662 = !{!2653, !2622, !2653, !2266}
!2663 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEE6insertEPS5_mRKS5_", scope: !2598, file: !1740, line: 568, type: !2664, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2664 = !DISubroutineType(types: !2665)
!2665 = !{!2653, !2622, !2653, !2647, !2266}
!2666 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEEaSERKS6_", scope: !2598, file: !1740, line: 674, type: !2667, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2667 = !DISubroutineType(types: !2668)
!2668 = !{!2643, !2622, !2623}
!2669 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEEaSEOS6_", scope: !2598, file: !1740, line: 677, type: !2670, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2670 = !DISubroutineType(types: !2671)
!2671 = !{!2643, !2622, !2672}
!2672 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2598, size: 64)
!2673 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEEeqERKS6_", scope: !2598, file: !1740, line: 680, type: !2674, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2674 = !DISubroutineType(types: !2675)
!2675 = !{!147, !2676, !2623}
!2676 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2624, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2677 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEEneERKS6_", scope: !2598, file: !1740, line: 684, type: !2674, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2678 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEEltERKS6_", scope: !2598, file: !1740, line: 688, type: !2674, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2679 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEEE8set_sizeEj", scope: !2598, file: !1740, line: 702, type: !2626, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2680 = !{!2367}
!2681 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !2595, file: !1740, line: 882, baseType: !2682, size: 896, offset: 320)
!2682 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<std::pair<llvm::SlotIndex, llvm::MachineBasicBlock *>, 8U>", scope: !14, file: !1740, line: 865, size: 896, flags: DIFlagTypePassByValue, elements: !2683, templateParams: !2686, identifier: "_ZTSN4llvm18SmallVectorStorageISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEELj8EEE")
!2683 = !{!2684}
!2684 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !2682, file: !1740, line: 866, baseType: !2685, size: 896)
!2685 = !DICompositeType(tag: DW_TAG_array_type, baseType: !2233, size: 896, elements: !2568)
!2686 = !{!2367, !2571}
!2687 = !DISubprogram(name: "SmallVector", scope: !2595, file: !1740, line: 884, type: !2688, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2688 = !DISubroutineType(types: !2689)
!2689 = !{null, !2690}
!2690 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2595, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2691 = !DISubprogram(name: "SmallVector", scope: !2595, file: !1740, line: 887, type: !2692, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2692 = !DISubroutineType(types: !2693)
!2693 = !{null, !2690, !6, !2266}
!2694 = !DISubprogram(name: "SmallVector", scope: !2595, file: !1740, line: 897, type: !2695, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2695 = !DISubroutineType(types: !2696)
!2696 = !{null, !2690, !2697}
!2697 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2698, size: 64)
!2698 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2595)
!2699 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEELj8EEaSERKS6_", scope: !2595, file: !1740, line: 902, type: !2700, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2700 = !DISubroutineType(types: !2701)
!2701 = !{!2697, !2690, !2697}
!2702 = !DISubprogram(name: "SmallVector", scope: !2595, file: !1740, line: 908, type: !2703, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2703 = !DISubroutineType(types: !2704)
!2704 = !{null, !2690, !2705}
!2705 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2595, size: 64)
!2706 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorISt4pairINS_9SlotIndexEPNS_17MachineBasicBlockEELj8EEaSEOS6_", scope: !2595, file: !1740, line: 913, type: !2707, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2707 = !DISubroutineType(types: !2708)
!2708 = !{!2697, !2690, !2705}
!2709 = !DIDerivedType(tag: DW_TAG_member, name: "ileAllocator", scope: !2426, file: !12, line: 357, baseType: !2710, size: 576, offset: 3072)
!2710 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "BumpPtrAllocator", scope: !14, file: !2711, line: 90, size: 576, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm16BumpPtrAllocatorE")
!2711 = !DIFile(filename: "llvm34/include/llvm/Support/Allocator.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e9d7c083de36bffba1b1ac9811c014c8")
!2712 = !DIDerivedType(tag: DW_TAG_member, name: "ID", scope: !2426, file: !12, line: 374, baseType: !338, flags: DIFlagPublic | DIFlagStaticMember)
!2713 = !DISubprogram(name: "createEntry", linkageName: "_ZN4llvm11SlotIndexes11createEntryEPNS_12MachineInstrEj", scope: !2426, file: !12, line: 359, type: !2714, scopeLine: 359, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2714 = !DISubroutineType(types: !2715)
!2715 = !{!31, !2716, !82, !6}
!2716 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2426, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2717 = !DISubprogram(name: "renumberIndexes", linkageName: "_ZN4llvm11SlotIndexes15renumberIndexesENS_14ilist_iteratorINS_14IndexListEntryEEE", scope: !2426, file: !12, line: 371, type: !2718, scopeLine: 371, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2718 = !DISubroutineType(types: !2719)
!2719 = !{null, !2716, !2456}
!2720 = !DISubprogram(name: "SlotIndexes", scope: !2426, file: !12, line: 376, type: !2721, scopeLine: 376, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2721 = !DISubroutineType(types: !2722)
!2722 = !{null, !2716}
!2723 = !DISubprogram(name: "getAnalysisUsage", linkageName: "_ZNK4llvm11SlotIndexes16getAnalysisUsageERNS_13AnalysisUsageE", scope: !2426, file: !12, line: 380, type: !2724, scopeLine: 380, containingType: !2426, virtualIndex: 10, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!2724 = !DISubroutineType(types: !2725)
!2725 = !{null, !2726, !2728}
!2726 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2727, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2727 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2426)
!2728 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2729, size: 64)
!2729 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "AnalysisUsage", scope: !14, file: !2730, line: 37, size: 6784, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm13AnalysisUsageE")
!2730 = !DIFile(filename: "llvm34/include/llvm/PassAnalysisSupport.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e41256537e53ea4c00bf424a000ee518")
!2731 = !DISubprogram(name: "releaseMemory", linkageName: "_ZN4llvm11SlotIndexes13releaseMemoryEv", scope: !2426, file: !12, line: 381, type: !2721, scopeLine: 381, containingType: !2426, virtualIndex: 11, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!2732 = !DISubprogram(name: "runOnMachineFunction", linkageName: "_ZN4llvm11SlotIndexes20runOnMachineFunctionERNS_15MachineFunctionE", scope: !2426, file: !12, line: 383, type: !2733, scopeLine: 383, containingType: !2426, virtualIndex: 18, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!2733 = !DISubroutineType(types: !2734)
!2734 = !{!147, !2716, !2735}
!2735 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2471, size: 64)
!2736 = !DISubprogram(name: "dump", linkageName: "_ZNK4llvm11SlotIndexes4dumpEv", scope: !2426, file: !12, line: 386, type: !2737, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2737 = !DISubroutineType(types: !2738)
!2738 = !{null, !2726}
!2739 = !DISubprogram(name: "renumberIndexes", linkageName: "_ZN4llvm11SlotIndexes15renumberIndexesEv", scope: !2426, file: !12, line: 389, type: !2721, scopeLine: 389, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2740 = !DISubprogram(name: "repairIndexesInRange", linkageName: "_ZN4llvm11SlotIndexes20repairIndexesInRangeEPNS_17MachineBasicBlockENS1_15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS4_EEEES7_", scope: !2426, file: !12, line: 392, type: !2741, scopeLine: 392, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2741 = !DISubroutineType(types: !2742)
!2742 = !{null, !2716, !1371, !2743, !2743}
!2743 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1314, file: !1315, line: 212, baseType: !2744)
!2744 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "bundle_iterator<llvm::MachineInstr, llvm::ilist_iterator<llvm::MachineInstr> >", scope: !1314, file: !1315, line: 144, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2745, templateParams: !2787, identifier: "_ZTSN4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEE")
!2745 = !{!2746, !2747, !2748, !2752, !2755, !2758, !2761, !2766, !2769, !2770, !2774, !2775, !2779, !2780, !2783, !2784}
!2746 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2744, baseType: !1437, flags: DIFlagPublic, extraData: i32 0)
!2747 = !DIDerivedType(tag: DW_TAG_member, name: "MII", scope: !2744, file: !1315, line: 146, baseType: !1434, size: 64, offset: 64)
!2748 = !DISubprogram(name: "bundle_iterator", scope: !2744, file: !1315, line: 149, type: !2749, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2749 = !DISubroutineType(types: !2750)
!2750 = !{null, !2751, !1434}
!2751 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2744, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2752 = !DISubprogram(name: "bundle_iterator", scope: !2744, file: !1315, line: 151, type: !2753, scopeLine: 151, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2753 = !DISubroutineType(types: !2754)
!2754 = !{null, !2751, !1442}
!2755 = !DISubprogram(name: "bundle_iterator", scope: !2744, file: !1315, line: 155, type: !2756, scopeLine: 155, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2756 = !DISubroutineType(types: !2757)
!2757 = !{null, !2751, !82}
!2758 = !DISubprogram(name: "bundle_iterator", scope: !2744, file: !1315, line: 163, type: !2759, scopeLine: 163, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2759 = !DISubroutineType(types: !2760)
!2760 = !{null, !2751}
!2761 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEdeEv", scope: !2744, file: !1315, line: 165, type: !2762, scopeLine: 165, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2762 = !DISubroutineType(types: !2763)
!2763 = !{!1442, !2764}
!2764 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2765, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2765 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2744)
!2766 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEptEv", scope: !2744, file: !1315, line: 166, type: !2767, scopeLine: 166, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2767 = !DISubroutineType(types: !2768)
!2768 = !{!82, !2764}
!2769 = !DISubprogram(name: "operator llvm::MachineInstr *", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEcvPS2_Ev", scope: !2744, file: !1315, line: 168, type: !2767, scopeLine: 168, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2770 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEeqERKS5_", scope: !2744, file: !1315, line: 170, type: !2771, scopeLine: 170, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2771 = !DISubroutineType(types: !2772)
!2772 = !{!147, !2764, !2773}
!2773 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2765, size: 64)
!2774 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEneERKS5_", scope: !2744, file: !1315, line: 173, type: !2771, scopeLine: 173, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2775 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEmmEv", scope: !2744, file: !1315, line: 178, type: !2776, scopeLine: 178, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2776 = !DISubroutineType(types: !2777)
!2777 = !{!2778, !2751}
!2778 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2744, size: 64)
!2779 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEppEv", scope: !2744, file: !1315, line: 183, type: !2776, scopeLine: 183, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2780 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEmmEi", scope: !2744, file: !1315, line: 189, type: !2781, scopeLine: 189, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2781 = !DISubroutineType(types: !2782)
!2782 = !{!2744, !2751, !220}
!2783 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEEppEi", scope: !2744, file: !1315, line: 194, type: !2781, scopeLine: 194, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2784 = !DISubprogram(name: "getInstrIterator", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorINS_12MachineInstrENS_14ilist_iteratorIS2_EEE16getInstrIteratorEv", scope: !2744, file: !1315, line: 200, type: !2785, scopeLine: 200, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2785 = !DISubroutineType(types: !2786)
!2786 = !{!1434, !2764}
!2787 = !{!2788, !2789}
!2788 = !DITemplateTypeParameter(name: "Ty", type: !83)
!2789 = !DITemplateTypeParameter(name: "IterTy", type: !1434)
!2790 = !DISubprogram(name: "getZeroIndex", linkageName: "_ZN4llvm11SlotIndexes12getZeroIndexEv", scope: !2426, file: !12, line: 397, type: !2791, scopeLine: 397, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2791 = !DISubroutineType(types: !2792)
!2792 = !{!13, !2716}
!2793 = !DISubprogram(name: "getLastIndex", linkageName: "_ZN4llvm11SlotIndexes12getLastIndexEv", scope: !2426, file: !12, line: 403, type: !2791, scopeLine: 403, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2794 = !DISubprogram(name: "hasIndex", linkageName: "_ZNK4llvm11SlotIndexes8hasIndexEPKNS_12MachineInstrE", scope: !2426, file: !12, line: 409, type: !2795, scopeLine: 409, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2795 = !DISubroutineType(types: !2796)
!2796 = !{!147, !2726, !263}
!2797 = !DISubprogram(name: "getInstructionIndex", linkageName: "_ZNK4llvm11SlotIndexes19getInstructionIndexEPKNS_12MachineInstrE", scope: !2426, file: !12, line: 414, type: !2798, scopeLine: 414, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2798 = !DISubroutineType(types: !2799)
!2799 = !{!13, !2726, !263}
!2800 = !DISubprogram(name: "getInstructionFromIndex", linkageName: "_ZNK4llvm11SlotIndexes23getInstructionFromIndexENS_9SlotIndexE", scope: !2426, file: !12, line: 423, type: !2801, scopeLine: 423, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2801 = !DISubroutineType(types: !2802)
!2802 = !{!82, !2726, !13}
!2803 = !DISubprogram(name: "getNextNonNullIndex", linkageName: "_ZN4llvm11SlotIndexes19getNextNonNullIndexENS_9SlotIndexE", scope: !2426, file: !12, line: 429, type: !2804, scopeLine: 429, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2804 = !DISubroutineType(types: !2805)
!2805 = !{!13, !2716, !13}
!2806 = !DISubprogram(name: "getIndexBefore", linkageName: "_ZNK4llvm11SlotIndexes14getIndexBeforeEPKNS_12MachineInstrE", scope: !2426, file: !12, line: 442, type: !2798, scopeLine: 442, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2807 = !DISubprogram(name: "getIndexAfter", linkageName: "_ZNK4llvm11SlotIndexes13getIndexAfterEPKNS_12MachineInstrE", scope: !2426, file: !12, line: 459, type: !2798, scopeLine: 459, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2808 = !DISubprogram(name: "getMBBRange", linkageName: "_ZNK4llvm11SlotIndexes11getMBBRangeEj", scope: !2426, file: !12, line: 475, type: !2809, scopeLine: 475, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2809 = !DISubroutineType(types: !2810)
!2810 = !{!1808, !2726, !6}
!2811 = !DISubprogram(name: "getMBBRange", linkageName: "_ZNK4llvm11SlotIndexes11getMBBRangeEPKNS_17MachineBasicBlockE", scope: !2426, file: !12, line: 481, type: !2812, scopeLine: 481, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2812 = !DISubroutineType(types: !2813)
!2813 = !{!1808, !2726, !1318}
!2814 = !DISubprogram(name: "getMBBStartIdx", linkageName: "_ZNK4llvm11SlotIndexes14getMBBStartIdxEj", scope: !2426, file: !12, line: 486, type: !2815, scopeLine: 486, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2815 = !DISubroutineType(types: !2816)
!2816 = !{!13, !2726, !6}
!2817 = !DISubprogram(name: "getMBBStartIdx", linkageName: "_ZNK4llvm11SlotIndexes14getMBBStartIdxEPKNS_17MachineBasicBlockE", scope: !2426, file: !12, line: 491, type: !2818, scopeLine: 491, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2818 = !DISubroutineType(types: !2819)
!2819 = !{!13, !2726, !1318}
!2820 = !DISubprogram(name: "getMBBEndIdx", linkageName: "_ZNK4llvm11SlotIndexes12getMBBEndIdxEj", scope: !2426, file: !12, line: 496, type: !2815, scopeLine: 496, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2821 = !DISubprogram(name: "getMBBEndIdx", linkageName: "_ZNK4llvm11SlotIndexes12getMBBEndIdxEPKNS_17MachineBasicBlockE", scope: !2426, file: !12, line: 501, type: !2818, scopeLine: 501, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2822 = !DISubprogram(name: "getMBBFromIndex", linkageName: "_ZNK4llvm11SlotIndexes15getMBBFromIndexENS_9SlotIndexE", scope: !2426, file: !12, line: 506, type: !2823, scopeLine: 506, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2823 = !DISubroutineType(types: !2824)
!2824 = !{!1371, !2726, !13}
!2825 = !DISubprogram(name: "findLiveInMBBs", linkageName: "_ZNK4llvm11SlotIndexes14findLiveInMBBsENS_9SlotIndexES1_RNS_15SmallVectorImplIPNS_17MachineBasicBlockEEE", scope: !2426, file: !12, line: 522, type: !2826, scopeLine: 522, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2826 = !DISubroutineType(types: !2827)
!2827 = !{!147, !2726, !13, !13, !2828}
!2828 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2829, size: 64)
!2829 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<llvm::MachineBasicBlock *>", scope: !14, file: !1740, line: 371, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm15SmallVectorImplIPNS_17MachineBasicBlockEEE")
!2830 = !DISubprogram(name: "getMBBCoveringRange", linkageName: "_ZNK4llvm11SlotIndexes19getMBBCoveringRangeENS_9SlotIndexES1_", scope: !2426, file: !12, line: 540, type: !2831, scopeLine: 540, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2831 = !DISubroutineType(types: !2832)
!2832 = !{!1371, !2726, !13, !13}
!2833 = !DISubprogram(name: "insertMachineInstrInMaps", linkageName: "_ZN4llvm11SlotIndexes24insertMachineInstrInMapsEPNS_12MachineInstrEb", scope: !2426, file: !12, line: 569, type: !2834, scopeLine: 569, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2834 = !DISubroutineType(types: !2835)
!2835 = !{!13, !2716, !82, !147}
!2836 = !DISubprogram(name: "removeMachineInstrFromMaps", linkageName: "_ZN4llvm11SlotIndexes26removeMachineInstrFromMapsEPNS_12MachineInstrE", scope: !2426, file: !12, line: 610, type: !2837, scopeLine: 610, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2837 = !DISubroutineType(types: !2838)
!2838 = !{null, !2716, !82}
!2839 = !DISubprogram(name: "replaceMachineInstrInMaps", linkageName: "_ZN4llvm11SlotIndexes25replaceMachineInstrInMapsEPNS_12MachineInstrES2_", scope: !2426, file: !12, line: 625, type: !2840, scopeLine: 625, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2840 = !DISubroutineType(types: !2841)
!2841 = !{null, !2716, !82, !82}
!2842 = !DISubprogram(name: "insertMBBInMaps", linkageName: "_ZN4llvm11SlotIndexes15insertMBBInMapsEPNS_17MachineBasicBlockE", scope: !2426, file: !12, line: 639, type: !2843, scopeLine: 639, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2843 = !DISubroutineType(types: !2844)
!2844 = !{null, !2716, !1371}
!2845 = !DISubprogram(name: "eraseIndex", linkageName: "_ZN4llvm11SlotIndexes10eraseIndexENS_9SlotIndexE", scope: !2426, file: !12, line: 689, type: !2846, scopeLine: 689, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2846 = !DISubroutineType(types: !2847)
!2847 = !{null, !2716, !13}
!2848 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FunctionPass", scope: !14, file: !248, line: 293, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12FunctionPassE")
!2849 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::MachineInstr *, llvm::SlotIndex>", scope: !320, file: !893, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !2850, templateParams: !2865, identifier: "_ZTSSt11__pair_baseIPN4llvm12MachineInstrENS0_9SlotIndexEE")
!2850 = !{!2851, !2855, !2856, !2861}
!2851 = !DISubprogram(name: "__pair_base", scope: !2849, file: !893, line: 194, type: !2852, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2852 = !DISubroutineType(types: !2853)
!2853 = !{null, !2854}
!2854 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2849, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2855 = !DISubprogram(name: "~__pair_base", scope: !2849, file: !893, line: 195, type: !2852, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2856 = !DISubprogram(name: "__pair_base", scope: !2849, file: !893, line: 196, type: !2857, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2857 = !DISubroutineType(types: !2858)
!2858 = !{null, !2854, !2859}
!2859 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2860, size: 64)
!2860 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2849)
!2861 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIPN4llvm12MachineInstrENS0_9SlotIndexEEaSERKS4_", scope: !2849, file: !893, line: 197, type: !2862, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2862 = !DISubroutineType(types: !2863)
!2863 = !{!2864, !2854, !2859}
!2864 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2849, size: 64)
!2865 = !{!2866, !914}
!2866 = !DITemplateTypeParameter(name: "_U1", type: !82)
!2867 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::MachineInstr *, llvm::SlotIndex>", scope: !320, file: !893, line: 208, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2868, templateParams: !2900, identifier: "_ZTSSt4pairIPN4llvm12MachineInstrENS0_9SlotIndexEE")
!2868 = !{!2869, !2870, !2871, !2872, !2878, !2882, !2890, !2897}
!2869 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2867, baseType: !2849, flags: DIFlagPrivate, extraData: i32 0)
!2870 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !2867, file: !893, line: 214, baseType: !82, size: 64)
!2871 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !2867, file: !893, line: 215, baseType: !13, size: 64, offset: 64)
!2872 = !DISubprogram(name: "pair", scope: !2867, file: !893, line: 303, type: !2873, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2873 = !DISubroutineType(types: !2874)
!2874 = !{null, !2875, !2876}
!2875 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2867, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2876 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2877, size: 64)
!2877 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2867)
!2878 = !DISubprogram(name: "pair", scope: !2867, file: !893, line: 304, type: !2879, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2879 = !DISubroutineType(types: !2880)
!2880 = !{null, !2875, !2881}
!2881 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2867, size: 64)
!2882 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPN4llvm12MachineInstrENS0_9SlotIndexEEaSERKS4_", scope: !2867, file: !893, line: 378, type: !2883, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2883 = !DISubroutineType(types: !2884)
!2884 = !{!2885, !2875, !2886}
!2885 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2867, size: 64)
!2886 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2887, file: !788, line: 1928, baseType: !2876)
!2887 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::MachineInstr *, llvm::SlotIndex> &, const std::__nonesuch_no_braces &>", scope: !320, file: !788, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !2888, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIPN4llvm12MachineInstrENS1_9SlotIndexEERKSt20__nonesuch_no_bracesE")
!2888 = !{!933, !2889, !935}
!2889 = !DITemplateTypeParameter(name: "_Iftrue", type: !2876)
!2890 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPN4llvm12MachineInstrENS0_9SlotIndexEEaSEOS4_", scope: !2867, file: !893, line: 389, type: !2891, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2891 = !DISubroutineType(types: !2892)
!2892 = !{!2885, !2875, !2893}
!2893 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2894, file: !788, line: 1928, baseType: !2881)
!2894 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::MachineInstr *, llvm::SlotIndex> &&, std::__nonesuch_no_braces &&>", scope: !320, file: !788, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !2895, identifier: "_ZTSSt11conditionalILb1EOSt4pairIPN4llvm12MachineInstrENS1_9SlotIndexEEOSt20__nonesuch_no_bracesE")
!2895 = !{!933, !2896, !946}
!2896 = !DITemplateTypeParameter(name: "_Iftrue", type: !2881)
!2897 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIPN4llvm12MachineInstrENS0_9SlotIndexEE4swapERS4_", scope: !2867, file: !893, line: 424, type: !2898, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2898 = !DISubroutineType(types: !2899)
!2899 = !{null, !2875, !2885}
!2900 = !{!2901, !953}
!2901 = !DITemplateTypeParameter(name: "_T1", type: !82)
!2902 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "bundle_iterator<const llvm::MachineInstr, llvm::ilist_iterator<const llvm::MachineInstr> >", scope: !1314, file: !1315, line: 144, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2903, templateParams: !2945, identifier: "_ZTSN4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEE")
!2903 = !{!2904, !2905, !2906, !2910, !2913, !2916, !2919, !2924, !2927, !2928, !2932, !2933, !2937, !2938, !2941, !2942}
!2904 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2902, baseType: !1683, flags: DIFlagPublic, extraData: i32 0)
!2905 = !DIDerivedType(tag: DW_TAG_member, name: "MII", scope: !2902, file: !1315, line: 146, baseType: !1680, size: 64, offset: 64)
!2906 = !DISubprogram(name: "bundle_iterator", scope: !2902, file: !1315, line: 149, type: !2907, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2907 = !DISubroutineType(types: !2908)
!2908 = !{null, !2909, !1680}
!2909 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2902, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2910 = !DISubprogram(name: "bundle_iterator", scope: !2902, file: !1315, line: 151, type: !2911, scopeLine: 151, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2911 = !DISubroutineType(types: !2912)
!2912 = !{null, !2909, !1688}
!2913 = !DISubprogram(name: "bundle_iterator", scope: !2902, file: !1315, line: 155, type: !2914, scopeLine: 155, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2914 = !DISubroutineType(types: !2915)
!2915 = !{null, !2909, !263}
!2916 = !DISubprogram(name: "bundle_iterator", scope: !2902, file: !1315, line: 163, type: !2917, scopeLine: 163, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2917 = !DISubroutineType(types: !2918)
!2918 = !{null, !2909}
!2919 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEdeEv", scope: !2902, file: !1315, line: 165, type: !2920, scopeLine: 165, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2920 = !DISubroutineType(types: !2921)
!2921 = !{!1688, !2922}
!2922 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2923, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2923 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2902)
!2924 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEptEv", scope: !2902, file: !1315, line: 166, type: !2925, scopeLine: 166, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2925 = !DISubroutineType(types: !2926)
!2926 = !{!263, !2922}
!2927 = !DISubprogram(name: "operator const llvm::MachineInstr *", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEcvPS3_Ev", scope: !2902, file: !1315, line: 168, type: !2925, scopeLine: 168, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2928 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEeqERKS6_", scope: !2902, file: !1315, line: 170, type: !2929, scopeLine: 170, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2929 = !DISubroutineType(types: !2930)
!2930 = !{!147, !2922, !2931}
!2931 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2923, size: 64)
!2932 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEneERKS6_", scope: !2902, file: !1315, line: 173, type: !2929, scopeLine: 173, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2933 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEmmEv", scope: !2902, file: !1315, line: 178, type: !2934, scopeLine: 178, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2934 = !DISubroutineType(types: !2935)
!2935 = !{!2936, !2909}
!2936 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2902, size: 64)
!2937 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEppEv", scope: !2902, file: !1315, line: 183, type: !2934, scopeLine: 183, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2938 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEmmEi", scope: !2902, file: !1315, line: 189, type: !2939, scopeLine: 189, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2939 = !DISubroutineType(types: !2940)
!2940 = !{!2902, !2909, !220}
!2941 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEEppEi", scope: !2902, file: !1315, line: 194, type: !2939, scopeLine: 194, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2942 = !DISubprogram(name: "getInstrIterator", linkageName: "_ZNK4llvm17MachineBasicBlock15bundle_iteratorIKNS_12MachineInstrENS_14ilist_iteratorIS3_EEE16getInstrIteratorEv", scope: !2902, file: !1315, line: 200, type: !2943, scopeLine: 200, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2943 = !DISubroutineType(types: !2944)
!2944 = !{!1680, !2922}
!2945 = !{!2946, !2947}
!2946 = !DITemplateTypeParameter(name: "Ty", type: !264)
!2947 = !DITemplateTypeParameter(name: "IterTy", type: !1680)
!2948 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Iter_comp_val<llvm::Idx2MBBCompare>", scope: !2376, file: !2375, line: 153, size: 8, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2949, templateParams: !2393, identifier: "_ZTSN9__gnu_cxx5__ops14_Iter_comp_valIN4llvm14Idx2MBBCompareEEE")
!2949 = !{!2950, !2951, !2955, !2958}
!2950 = !DIDerivedType(tag: DW_TAG_member, name: "_M_comp", scope: !2948, file: !2375, line: 155, baseType: !2379, size: 8)
!2951 = !DISubprogram(name: "_Iter_comp_val", scope: !2948, file: !2375, line: 158, type: !2952, scopeLine: 158, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2952 = !DISubroutineType(types: !2953)
!2953 = !{null, !2954, !2379}
!2954 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2948, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2955 = !DISubprogram(name: "_Iter_comp_val", scope: !2948, file: !2375, line: 163, type: !2956, scopeLine: 163, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2956 = !DISubroutineType(types: !2957)
!2957 = !{null, !2954, !2420}
!2958 = !DISubprogram(name: "_Iter_comp_val", scope: !2948, file: !2375, line: 169, type: !2959, scopeLine: 169, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2959 = !DISubroutineType(types: !2960)
!2960 = !{null, !2954, !2425}
!2961 = !{!2962, !2965, !2987, !2992, !2997, !3002, !3007, !3012, !3017, !3019, !3024, !3029, !3034, !3039, !3044, !3049, !3054, !3059, !3064, !3066, !3071, !3073, !3078, !3083, !3085, !3090, !3095, !3100, !3105, !3110, !3112, !3117, !3122, !3127, !3132, !3137, !3142, !3147, !3152, !3157, !3162, !3167, !3172, !3224, !3226, !3228, !3230, !3235, !3240, !3245, !3250, !3255, !3260, !3265, !3267, !3272, !3274, !3279, !3284, !3286, !3288, !3290, !3295, !3300, !3305, !3310, !3315, !3320, !3322, !3327, !3332, !3337, !3339, !3344, !3349, !3351, !3353, !3358, !3360, !3365, !3370, !3375, !3377, !3379, !3384, !3389, !3391, !3396, !3401, !3406, !3408, !3413, !3418, !3423, !3428, !3433, !3435, !3440, !3445, !3450, !3452, !3457, !3462}
!2962 = !DIGlobalVariableExpression(var: !2963, expr: !DIExpression())
!2963 = distinct !DIGlobalVariable(name: "ID", linkageName: "_ZN4llvm11SlotIndexes2IDE", scope: !0, file: !2964, line: 21, type: !338, isLocal: false, isDefinition: true, declaration: !2712)
!2964 = !DIFile(filename: "llvm34/lib/CodeGen/SlotIndexes.cpp", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "f424b3c485923976c215b7f43a177ea6")
!2965 = !DIGlobalVariableExpression(var: !2966, expr: !DIExpression())
!2966 = distinct !DIGlobalVariable(name: "initialized", scope: !2967, file: !2964, line: 22, type: !2986, isLocal: true, isDefinition: true)
!2967 = distinct !DISubprogram(name: "initializeSlotIndexesPass", linkageName: "_ZN4llvm25initializeSlotIndexesPassERNS_12PassRegistryE", scope: !14, file: !2964, line: 22, type: !2968, scopeLine: 22, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !2973)
!2968 = !DISubroutineType(types: !2969)
!2969 = !{null, !2970}
!2970 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2971, size: 64)
!2971 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PassRegistry", scope: !14, file: !2972, line: 35, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12PassRegistryE")
!2972 = !DIFile(filename: "llvm34/include/llvm/PassRegistry.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "ea055db655addf2322a009df18bef61e")
!2973 = !{!2974, !2975, !2983}
!2974 = !DILocalVariable(name: "Registry", arg: 1, scope: !2967, file: !2964, line: 22, type: !2970)
!2975 = !DILocalVariable(name: "old_val", scope: !2967, file: !2964, line: 22, type: !2976)
!2976 = !DIDerivedType(tag: DW_TAG_typedef, name: "cas_flag", scope: !2978, file: !2977, line: 26, baseType: !2979)
!2977 = !DIFile(filename: "llvm34/include/llvm/Support/Atomic.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "bb80c3b7b95076871079a09befb3cafb")
!2978 = !DINamespace(name: "sys", scope: !14)
!2979 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint32_t", file: !2980, line: 26, baseType: !2981)
!2980 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h", directory: "", checksumkind: CSK_MD5, checksum: "9754ebe022edbe8d7928fa709e442f0d")
!2981 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint32_t", file: !2982, line: 41, baseType: !6)
!2982 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types.h", directory: "", checksumkind: CSK_MD5, checksum: "25679ba19d359e314e48661b21f5aa1f")
!2983 = !DILocalVariable(name: "tmp", scope: !2984, file: !2964, line: 22, type: !2976)
!2984 = distinct !DILexicalBlock(scope: !2985, file: !2964, line: 22, column: 1)
!2985 = distinct !DILexicalBlock(scope: !2967, file: !2964, line: 22, column: 1)
!2986 = !DIDerivedType(tag: DW_TAG_volatile_type, baseType: !2976)
!2987 = !DIGlobalVariableExpression(var: !2988, expr: !DIExpression())
!2988 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 22, type: !2989, isLocal: true, isDefinition: true)
!2989 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 352, elements: !2990)
!2990 = !{!2991}
!2991 = !DISubrange(count: 44)
!2992 = !DIGlobalVariableExpression(var: !2993, expr: !DIExpression())
!2993 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 57, type: !2994, isLocal: true, isDefinition: true)
!2994 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 344, elements: !2995)
!2995 = !{!2996}
!2996 = !DISubrange(count: 43)
!2997 = !DIGlobalVariableExpression(var: !2998, expr: !DIExpression())
!2998 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 57, type: !2999, isLocal: true, isDefinition: true)
!2999 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 528, elements: !3000)
!3000 = !{!3001}
!3001 = !DISubrange(count: 66)
!3002 = !DIGlobalVariableExpression(var: !3003, expr: !DIExpression())
!3003 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 57, type: !3004, isLocal: true, isDefinition: true)
!3004 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 624, elements: !3005)
!3005 = !{!3006}
!3006 = !DISubrange(count: 78)
!3007 = !DIGlobalVariableExpression(var: !3008, expr: !DIExpression())
!3008 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 58, type: !3009, isLocal: true, isDefinition: true)
!3009 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 424, elements: !3010)
!3010 = !{!3011}
!3011 = !DISubrange(count: 53)
!3012 = !DIGlobalVariableExpression(var: !3013, expr: !DIExpression())
!3013 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 58, type: !3014, isLocal: true, isDefinition: true)
!3014 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 616, elements: !3015)
!3015 = !{!3016}
!3016 = !DISubrange(count: 77)
!3017 = !DIGlobalVariableExpression(var: !3018, expr: !DIExpression())
!3018 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 60, type: !3009, isLocal: true, isDefinition: true)
!3019 = !DIGlobalVariableExpression(var: !3020, expr: !DIExpression())
!3020 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 60, type: !3021, isLocal: true, isDefinition: true)
!3021 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 608, elements: !3022)
!3022 = !{!3023}
!3023 = !DISubrange(count: 76)
!3024 = !DIGlobalVariableExpression(var: !3025, expr: !DIExpression())
!3025 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 62, type: !3026, isLocal: true, isDefinition: true)
!3026 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 496, elements: !3027)
!3027 = !{!3028}
!3028 = !DISubrange(count: 62)
!3029 = !DIGlobalVariableExpression(var: !3030, expr: !DIExpression())
!3030 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 62, type: !3031, isLocal: true, isDefinition: true)
!3031 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 664, elements: !3032)
!3032 = !{!3033}
!3033 = !DISubrange(count: 83)
!3034 = !DIGlobalVariableExpression(var: !3035, expr: !DIExpression())
!3035 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 105, type: !3036, isLocal: true, isDefinition: true)
!3036 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 96, elements: !3037)
!3037 = !{!3038}
!3038 = !DISubrange(count: 12)
!3039 = !DIGlobalVariableExpression(var: !3040, expr: !DIExpression())
!3040 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 113, type: !3041, isLocal: true, isDefinition: true)
!3041 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 272, elements: !3042)
!3042 = !{!3043}
!3043 = !DISubrange(count: 34)
!3044 = !DIGlobalVariableExpression(var: !3045, expr: !DIExpression())
!3045 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 140, type: !3046, isLocal: true, isDefinition: true)
!3046 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 232, elements: !3047)
!3047 = !{!3048}
!3048 = !DISubrange(count: 29)
!3049 = !DIGlobalVariableExpression(var: !3050, expr: !DIExpression())
!3050 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 140, type: !3051, isLocal: true, isDefinition: true)
!3051 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 48, elements: !3052)
!3052 = !{!3053}
!3053 = !DISubrange(count: 6)
!3054 = !DIGlobalVariableExpression(var: !3055, expr: !DIExpression())
!3055 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 180, type: !3056, isLocal: true, isDefinition: true)
!3056 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 416, elements: !3057)
!3057 = !{!3058}
!3058 = !DISubrange(count: 52)
!3059 = !DIGlobalVariableExpression(var: !3060, expr: !DIExpression())
!3060 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 180, type: !3061, isLocal: true, isDefinition: true)
!3061 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 1040, elements: !3062)
!3062 = !{!3063}
!3063 = !DISubrange(count: 130)
!3064 = !DIGlobalVariableExpression(var: !3065, expr: !DIExpression())
!3065 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 180, type: !3061, isLocal: true, isDefinition: true)
!3066 = !DIGlobalVariableExpression(var: !3067, expr: !DIExpression())
!3067 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 220, type: !3068, isLocal: true, isDefinition: true)
!3068 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 16, elements: !3069)
!3069 = !{!3070}
!3070 = !DISubrange(count: 2)
!3071 = !DIGlobalVariableExpression(var: !3072, expr: !DIExpression())
!3072 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 225, type: !3068, isLocal: true, isDefinition: true)
!3073 = !DIGlobalVariableExpression(var: !3074, expr: !DIExpression())
!3074 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 230, type: !3075, isLocal: true, isDefinition: true)
!3075 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 32, elements: !3076)
!3076 = !{!3077}
!3077 = !DISubrange(count: 4)
!3078 = !DIGlobalVariableExpression(var: !3079, expr: !DIExpression())
!3079 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 230, type: !3080, isLocal: true, isDefinition: true)
!3080 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 24, elements: !3081)
!3081 = !{!3082}
!3082 = !DISubrange(count: 3)
!3083 = !DIGlobalVariableExpression(var: !3084, expr: !DIExpression())
!3084 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 231, type: !3080, isLocal: true, isDefinition: true)
!3085 = !DIGlobalVariableExpression(var: !3086, expr: !DIExpression())
!3086 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 238, type: !3087, isLocal: true, isDefinition: true)
!3087 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 40, elements: !3088)
!3088 = !{!3089}
!3089 = !DISubrange(count: 5)
!3090 = !DIGlobalVariableExpression(var: !3091, expr: !DIExpression())
!3091 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 240, type: !3092, isLocal: true, isDefinition: true)
!3092 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 64, elements: !3093)
!3093 = !{!3094}
!3094 = !DISubrange(count: 8)
!3095 = !DIGlobalVariableExpression(var: !3096, expr: !DIExpression())
!3096 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 22, type: !3097, isLocal: true, isDefinition: true)
!3097 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 168, elements: !3098)
!3098 = !{!3099}
!3099 = !DISubrange(count: 21)
!3100 = !DIGlobalVariableExpression(var: !3101, expr: !DIExpression())
!3101 = distinct !DIGlobalVariable(scope: null, file: !869, line: 271, type: !3102, isLocal: true, isDefinition: true)
!3102 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 336, elements: !3103)
!3103 = !{!3104}
!3104 = !DISubrange(count: 42)
!3105 = !DIGlobalVariableExpression(var: !3106, expr: !DIExpression())
!3106 = distinct !DIGlobalVariable(scope: null, file: !869, line: 271, type: !3107, isLocal: true, isDefinition: true)
!3107 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 736, elements: !3108)
!3108 = !{!3109}
!3109 = !DISubrange(count: 92)
!3110 = !DIGlobalVariableExpression(var: !3111, expr: !DIExpression())
!3111 = distinct !DIGlobalVariable(scope: null, file: !869, line: 271, type: !2989, isLocal: true, isDefinition: true)
!3112 = !DIGlobalVariableExpression(var: !3113, expr: !DIExpression())
!3113 = distinct !DIGlobalVariable(scope: null, file: !869, line: 271, type: !3114, isLocal: true, isDefinition: true)
!3114 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 3072, elements: !3115)
!3115 = !{!3116}
!3116 = !DISubrange(count: 384)
!3117 = !DIGlobalVariableExpression(var: !3118, expr: !DIExpression())
!3118 = distinct !DIGlobalVariable(scope: null, file: !18, line: 108, type: !3119, isLocal: true, isDefinition: true)
!3119 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 288, elements: !3120)
!3120 = !{!3121}
!3121 = !DISubrange(count: 36)
!3122 = !DIGlobalVariableExpression(var: !3123, expr: !DIExpression())
!3123 = distinct !DIGlobalVariable(scope: null, file: !18, line: 108, type: !3124, isLocal: true, isDefinition: true)
!3124 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 800, elements: !3125)
!3125 = !{!3126}
!3126 = !DISubrange(count: 100)
!3127 = !DIGlobalVariableExpression(var: !3128, expr: !DIExpression())
!3128 = distinct !DIGlobalVariable(scope: null, file: !18, line: 108, type: !3129, isLocal: true, isDefinition: true)
!3129 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 400, elements: !3130)
!3130 = !{!3131}
!3131 = !DISubrange(count: 50)
!3132 = !DIGlobalVariableExpression(var: !3133, expr: !DIExpression())
!3133 = distinct !DIGlobalVariable(scope: null, file: !18, line: 108, type: !3134, isLocal: true, isDefinition: true)
!3134 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 1840, elements: !3135)
!3135 = !{!3136}
!3136 = !DISubrange(count: 230)
!3137 = !DIGlobalVariableExpression(var: !3138, expr: !DIExpression())
!3138 = distinct !DIGlobalVariable(scope: null, file: !18, line: 111, type: !3139, isLocal: true, isDefinition: true)
!3139 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 224, elements: !3140)
!3140 = !{!3141}
!3141 = !DISubrange(count: 28)
!3142 = !DIGlobalVariableExpression(var: !3143, expr: !DIExpression())
!3143 = distinct !DIGlobalVariable(scope: null, file: !18, line: 111, type: !3144, isLocal: true, isDefinition: true)
!3144 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 464, elements: !3145)
!3145 = !{!3146}
!3146 = !DISubrange(count: 58)
!3147 = !DIGlobalVariableExpression(var: !3148, expr: !DIExpression())
!3148 = distinct !DIGlobalVariable(scope: null, file: !1494, line: 78, type: !3149, isLocal: true, isDefinition: true)
!3149 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 376, elements: !3150)
!3150 = !{!3151}
!3151 = !DISubrange(count: 47)
!3152 = !DIGlobalVariableExpression(var: !3153, expr: !DIExpression())
!3153 = distinct !DIGlobalVariable(scope: null, file: !1494, line: 78, type: !3154, isLocal: true, isDefinition: true)
!3154 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 448, elements: !3155)
!3155 = !{!3156}
!3156 = !DISubrange(count: 56)
!3157 = !DIGlobalVariableExpression(var: !3158, expr: !DIExpression())
!3158 = distinct !DIGlobalVariable(scope: null, file: !1494, line: 78, type: !3159, isLocal: true, isDefinition: true)
!3159 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 360, elements: !3160)
!3160 = !{!3161}
!3161 = !DISubrange(count: 45)
!3162 = !DIGlobalVariableExpression(var: !3163, expr: !DIExpression())
!3163 = distinct !DIGlobalVariable(scope: null, file: !1494, line: 78, type: !3164, isLocal: true, isDefinition: true)
!3164 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 328, elements: !3165)
!3165 = !{!3166}
!3166 = !DISubrange(count: 41)
!3167 = !DIGlobalVariableExpression(var: !3168, expr: !DIExpression())
!3168 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 26, type: !3169, isLocal: true, isDefinition: true)
!3169 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 240, elements: !3170)
!3170 = !{!3171}
!3171 = !DISubrange(count: 30)
!3172 = !DIGlobalVariableExpression(var: !3173, expr: !DIExpression())
!3173 = distinct !DIGlobalVariable(name: "NumGlobalRenum", linkageName: "_ZL14NumGlobalRenum", scope: !0, file: !2964, line: 26, type: !3174, isLocal: true, isDefinition: true)
!3174 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Statistic", scope: !14, file: !3175, line: 35, size: 192, flags: DIFlagTypePassByValue, elements: !3176, identifier: "_ZTSN4llvm9StatisticE")
!3175 = !DIFile(filename: "llvm34/include/llvm/ADT/Statistic.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "53ce2a0037e7af9cca48ac8c0c187505")
!3176 = !{!3177, !3178, !3179, !3180, !3181, !3186, !3189, !3190, !3194, !3197, !3201, !3204, !3207, !3208, !3209, !3214, !3215, !3216, !3217, !3221}
!3177 = !DIDerivedType(tag: DW_TAG_member, name: "Name", scope: !3174, file: !3175, line: 37, baseType: !336, size: 64, flags: DIFlagPublic)
!3178 = !DIDerivedType(tag: DW_TAG_member, name: "Desc", scope: !3174, file: !3175, line: 38, baseType: !336, size: 64, offset: 64, flags: DIFlagPublic)
!3179 = !DIDerivedType(tag: DW_TAG_member, name: "Value", scope: !3174, file: !3175, line: 39, baseType: !2986, size: 32, offset: 128, flags: DIFlagPublic)
!3180 = !DIDerivedType(tag: DW_TAG_member, name: "Initialized", scope: !3174, file: !3175, line: 40, baseType: !147, size: 8, offset: 160, flags: DIFlagPublic)
!3181 = !DISubprogram(name: "getValue", linkageName: "_ZNK4llvm9Statistic8getValueEv", scope: !3174, file: !3175, line: 42, type: !3182, scopeLine: 42, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3182 = !DISubroutineType(types: !3183)
!3183 = !{!2976, !3184}
!3184 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3185, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3185 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3174)
!3186 = !DISubprogram(name: "getName", linkageName: "_ZNK4llvm9Statistic7getNameEv", scope: !3174, file: !3175, line: 43, type: !3187, scopeLine: 43, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3187 = !DISubroutineType(types: !3188)
!3188 = !{!336, !3184}
!3189 = !DISubprogram(name: "getDesc", linkageName: "_ZNK4llvm9Statistic7getDescEv", scope: !3174, file: !3175, line: 44, type: !3187, scopeLine: 44, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3190 = !DISubprogram(name: "construct", linkageName: "_ZN4llvm9Statistic9constructEPKcS2_", scope: !3174, file: !3175, line: 47, type: !3191, scopeLine: 47, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3191 = !DISubroutineType(types: !3192)
!3192 = !{null, !3193, !336, !336}
!3193 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3174, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3194 = !DISubprogram(name: "operator unsigned int", linkageName: "_ZNK4llvm9StatisticcvjEv", scope: !3174, file: !3175, line: 53, type: !3195, scopeLine: 53, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3195 = !DISubroutineType(types: !3196)
!3196 = !{!6, !3184}
!3197 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm9StatisticaSEj", scope: !3174, file: !3175, line: 56, type: !3198, scopeLine: 56, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3198 = !DISubroutineType(types: !3199)
!3199 = !{!3200, !3193, !6}
!3200 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3185, size: 64)
!3201 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm9StatisticppEv", scope: !3174, file: !3175, line: 61, type: !3202, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3202 = !DISubroutineType(types: !3203)
!3203 = !{!3200, !3193}
!3204 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm9StatisticppEi", scope: !3174, file: !3175, line: 70, type: !3205, scopeLine: 70, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3205 = !DISubroutineType(types: !3206)
!3206 = !{!6, !3193, !220}
!3207 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm9StatisticmmEv", scope: !3174, file: !3175, line: 77, type: !3202, scopeLine: 77, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3208 = !DISubprogram(name: "operator--", linkageName: "_ZN4llvm9StatisticmmEi", scope: !3174, file: !3175, line: 82, type: !3205, scopeLine: 82, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3209 = !DISubprogram(name: "operator+=", linkageName: "_ZN4llvm9StatisticpLERKj", scope: !3174, file: !3175, line: 89, type: !3210, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3210 = !DISubroutineType(types: !3211)
!3211 = !{!3200, !3193, !3212}
!3212 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3213, size: 64)
!3213 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6)
!3214 = !DISubprogram(name: "operator-=", linkageName: "_ZN4llvm9StatisticmIERKj", scope: !3174, file: !3175, line: 95, type: !3210, scopeLine: 95, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3215 = !DISubprogram(name: "operator*=", linkageName: "_ZN4llvm9StatisticmLERKj", scope: !3174, file: !3175, line: 101, type: !3210, scopeLine: 101, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3216 = !DISubprogram(name: "operator/=", linkageName: "_ZN4llvm9StatisticdVERKj", scope: !3174, file: !3175, line: 106, type: !3210, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3217 = !DISubprogram(name: "init", linkageName: "_ZN4llvm9Statistic4initEv", scope: !3174, file: !3175, line: 152, type: !3218, scopeLine: 152, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3218 = !DISubroutineType(types: !3219)
!3219 = !{!3220, !3193}
!3220 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3174, size: 64)
!3221 = !DISubprogram(name: "RegisterStatistic", linkageName: "_ZN4llvm9Statistic17RegisterStatisticEv", scope: !3174, file: !3175, line: 159, type: !3222, scopeLine: 159, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3222 = !DISubroutineType(types: !3223)
!3223 = !{null, !3193}
!3224 = !DIGlobalVariableExpression(var: !3225, expr: !DIExpression())
!3225 = distinct !DIGlobalVariable(scope: null, file: !3175, line: 156, type: !3159, isLocal: true, isDefinition: true)
!3226 = !DIGlobalVariableExpression(var: !3227, expr: !DIExpression())
!3227 = distinct !DIGlobalVariable(scope: null, file: !2964, line: 25, type: !3046, isLocal: true, isDefinition: true)
!3228 = !DIGlobalVariableExpression(var: !3229, expr: !DIExpression())
!3229 = distinct !DIGlobalVariable(name: "NumLocalRenum", linkageName: "_ZL13NumLocalRenum", scope: !0, file: !2964, line: 25, type: !3174, isLocal: true, isDefinition: true)
!3230 = !DIGlobalVariableExpression(var: !3231, expr: !DIExpression())
!3231 = distinct !DIGlobalVariable(scope: null, file: !869, line: 478, type: !3232, isLocal: true, isDefinition: true)
!3232 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 432, elements: !3233)
!3233 = !{!3234}
!3234 = !DISubrange(count: 54)
!3235 = !DIGlobalVariableExpression(var: !3236, expr: !DIExpression())
!3236 = distinct !DIGlobalVariable(scope: null, file: !869, line: 478, type: !3237, isLocal: true, isDefinition: true)
!3237 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 1072, elements: !3238)
!3238 = !{!3239}
!3239 = !DISubrange(count: 134)
!3240 = !DIGlobalVariableExpression(var: !3241, expr: !DIExpression())
!3241 = distinct !DIGlobalVariable(scope: null, file: !869, line: 478, type: !3242, isLocal: true, isDefinition: true)
!3242 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 3944, elements: !3243)
!3243 = !{!3244}
!3244 = !DISubrange(count: 493)
!3245 = !DIGlobalVariableExpression(var: !3246, expr: !DIExpression())
!3246 = distinct !DIGlobalVariable(scope: null, file: !12, line: 417, type: !3247, isLocal: true, isDefinition: true)
!3247 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 248, elements: !3248)
!3248 = !{!3249}
!3249 = !DISubrange(count: 31)
!3250 = !DIGlobalVariableExpression(var: !3251, expr: !DIExpression())
!3251 = distinct !DIGlobalVariable(scope: null, file: !12, line: 417, type: !3252, isLocal: true, isDefinition: true)
!3252 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 456, elements: !3253)
!3253 = !{!3254}
!3254 = !DISubrange(count: 57)
!3255 = !DIGlobalVariableExpression(var: !3256, expr: !DIExpression())
!3256 = distinct !DIGlobalVariable(scope: null, file: !12, line: 417, type: !3257, isLocal: true, isDefinition: true)
!3257 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 408, elements: !3258)
!3258 = !{!3259}
!3259 = !DISubrange(count: 51)
!3260 = !DIGlobalVariableExpression(var: !3261, expr: !DIExpression())
!3261 = distinct !DIGlobalVariable(scope: null, file: !12, line: 417, type: !3262, isLocal: true, isDefinition: true)
!3262 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 712, elements: !3263)
!3263 = !{!3264}
!3264 = !DISubrange(count: 89)
!3265 = !DIGlobalVariableExpression(var: !3266, expr: !DIExpression())
!3266 = distinct !DIGlobalVariable(scope: null, file: !1297, line: 215, type: !3119, isLocal: true, isDefinition: true)
!3267 = !DIGlobalVariableExpression(var: !3268, expr: !DIExpression())
!3268 = distinct !DIGlobalVariable(scope: null, file: !1297, line: 215, type: !3269, isLocal: true, isDefinition: true)
!3269 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 392, elements: !3270)
!3270 = !{!3271}
!3271 = !DISubrange(count: 49)
!3272 = !DIGlobalVariableExpression(var: !3273, expr: !DIExpression())
!3273 = distinct !DIGlobalVariable(scope: null, file: !1297, line: 215, type: !3164, isLocal: true, isDefinition: true)
!3274 = !DIGlobalVariableExpression(var: !3275, expr: !DIExpression())
!3275 = distinct !DIGlobalVariable(scope: null, file: !1297, line: 215, type: !3276, isLocal: true, isDefinition: true)
!3276 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 968, elements: !3277)
!3277 = !{!3278}
!3278 = !DISubrange(count: 121)
!3279 = !DIGlobalVariableExpression(var: !3280, expr: !DIExpression())
!3280 = distinct !DIGlobalVariable(scope: null, file: !12, line: 125, type: !3281, isLocal: true, isDefinition: true)
!3281 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 280, elements: !3282)
!3282 = !{!3283}
!3283 = !DISubrange(count: 35)
!3284 = !DIGlobalVariableExpression(var: !3285, expr: !DIExpression())
!3285 = distinct !DIGlobalVariable(scope: null, file: !12, line: 125, type: !3129, isLocal: true, isDefinition: true)
!3286 = !DIGlobalVariableExpression(var: !3287, expr: !DIExpression())
!3287 = distinct !DIGlobalVariable(scope: null, file: !12, line: 125, type: !3252, isLocal: true, isDefinition: true)
!3288 = !DIGlobalVariableExpression(var: !3289, expr: !DIExpression())
!3289 = distinct !DIGlobalVariable(scope: null, file: !12, line: 616, type: !3139, isLocal: true, isDefinition: true)
!3290 = !DIGlobalVariableExpression(var: !3291, expr: !DIExpression())
!3291 = distinct !DIGlobalVariable(scope: null, file: !12, line: 616, type: !3292, isLocal: true, isDefinition: true)
!3292 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 472, elements: !3293)
!3293 = !{!3294}
!3294 = !DISubrange(count: 59)
!3295 = !DIGlobalVariableExpression(var: !3296, expr: !DIExpression())
!3296 = distinct !DIGlobalVariable(scope: null, file: !12, line: 616, type: !3297, isLocal: true, isDefinition: true)
!3297 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 584, elements: !3298)
!3298 = !{!3299}
!3299 = !DISubrange(count: 73)
!3300 = !DIGlobalVariableExpression(var: !3301, expr: !DIExpression())
!3301 = distinct !DIGlobalVariable(scope: null, file: !12, line: 570, type: !3302, isLocal: true, isDefinition: true)
!3302 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 480, elements: !3303)
!3303 = !{!3304}
!3304 = !DISubrange(count: 60)
!3305 = !DIGlobalVariableExpression(var: !3306, expr: !DIExpression())
!3306 = distinct !DIGlobalVariable(scope: null, file: !12, line: 570, type: !3307, isLocal: true, isDefinition: true)
!3307 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 696, elements: !3308)
!3308 = !{!3309}
!3309 = !DISubrange(count: 87)
!3310 = !DIGlobalVariableExpression(var: !3311, expr: !DIExpression())
!3311 = distinct !DIGlobalVariable(scope: null, file: !12, line: 570, type: !3312, isLocal: true, isDefinition: true)
!3312 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 704, elements: !3313)
!3313 = !{!3314}
!3314 = !DISubrange(count: 88)
!3315 = !DIGlobalVariableExpression(var: !3316, expr: !DIExpression())
!3316 = distinct !DIGlobalVariable(scope: null, file: !12, line: 572, type: !3317, isLocal: true, isDefinition: true)
!3317 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 184, elements: !3318)
!3318 = !{!3319}
!3319 = !DISubrange(count: 23)
!3320 = !DIGlobalVariableExpression(var: !3321, expr: !DIExpression())
!3321 = distinct !DIGlobalVariable(scope: null, file: !12, line: 572, type: !3026, isLocal: true, isDefinition: true)
!3322 = !DIGlobalVariableExpression(var: !3323, expr: !DIExpression())
!3323 = distinct !DIGlobalVariable(scope: null, file: !12, line: 575, type: !3324, isLocal: true, isDefinition: true)
!3324 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 304, elements: !3325)
!3325 = !{!3326}
!3326 = !DISubrange(count: 38)
!3327 = !DIGlobalVariableExpression(var: !3328, expr: !DIExpression())
!3328 = distinct !DIGlobalVariable(scope: null, file: !12, line: 575, type: !3329, isLocal: true, isDefinition: true)
!3329 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 504, elements: !3330)
!3330 = !{!3331}
!3331 = !DISubrange(count: 63)
!3332 = !DIGlobalVariableExpression(var: !3333, expr: !DIExpression())
!3333 = distinct !DIGlobalVariable(scope: null, file: !12, line: 577, type: !3334, isLocal: true, isDefinition: true)
!3334 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 264, elements: !3335)
!3335 = !{!3336}
!3336 = !DISubrange(count: 33)
!3337 = !DIGlobalVariableExpression(var: !3338, expr: !DIExpression())
!3338 = distinct !DIGlobalVariable(scope: null, file: !12, line: 577, type: !3292, isLocal: true, isDefinition: true)
!3339 = !DIGlobalVariableExpression(var: !3340, expr: !DIExpression())
!3340 = distinct !DIGlobalVariable(scope: null, file: !12, line: 461, type: !3341, isLocal: true, isDefinition: true)
!3341 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 296, elements: !3342)
!3342 = !{!3343}
!3343 = !DISubrange(count: 37)
!3344 = !DIGlobalVariableExpression(var: !3345, expr: !DIExpression())
!3345 = distinct !DIGlobalVariable(scope: null, file: !12, line: 461, type: !3346, isLocal: true, isDefinition: true)
!3346 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 368, elements: !3347)
!3347 = !{!3348}
!3348 = !DISubrange(count: 46)
!3349 = !DIGlobalVariableExpression(var: !3350, expr: !DIExpression())
!3350 = distinct !DIGlobalVariable(scope: null, file: !12, line: 461, type: !3031, isLocal: true, isDefinition: true)
!3351 = !DIGlobalVariableExpression(var: !3352, expr: !DIExpression())
!3352 = distinct !DIGlobalVariable(scope: null, file: !1315, line: 156, type: !3329, isLocal: true, isDefinition: true)
!3353 = !DIGlobalVariableExpression(var: !3354, expr: !DIExpression())
!3354 = distinct !DIGlobalVariable(scope: null, file: !1315, line: 156, type: !3355, isLocal: true, isDefinition: true)
!3355 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 816, elements: !3356)
!3356 = !{!3357}
!3357 = !DISubrange(count: 102)
!3358 = !DIGlobalVariableExpression(var: !3359, expr: !DIExpression())
!3359 = distinct !DIGlobalVariable(scope: null, file: !1315, line: 156, type: !3252, isLocal: true, isDefinition: true)
!3360 = !DIGlobalVariableExpression(var: !3361, expr: !DIExpression())
!3361 = distinct !DIGlobalVariable(scope: null, file: !1315, line: 156, type: !3362, isLocal: true, isDefinition: true)
!3362 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 1816, elements: !3363)
!3363 = !{!3364}
!3364 = !DISubrange(count: 227)
!3365 = !DIGlobalVariableExpression(var: !3366, expr: !DIExpression())
!3366 = distinct !DIGlobalVariable(scope: null, file: !12, line: 444, type: !3367, isLocal: true, isDefinition: true)
!3367 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 672, elements: !3368)
!3368 = !{!3369}
!3369 = !DISubrange(count: 84)
!3370 = !DIGlobalVariableExpression(var: !3371, expr: !DIExpression())
!3371 = distinct !DIGlobalVariable(scope: null, file: !1315, line: 156, type: !3372, isLocal: true, isDefinition: true)
!3372 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 1624, elements: !3373)
!3373 = !{!3374}
!3374 = !DISubrange(count: 203)
!3375 = !DIGlobalVariableExpression(var: !3376, expr: !DIExpression())
!3376 = distinct !DIGlobalVariable(scope: null, file: !1297, line: 399, type: !3046, isLocal: true, isDefinition: true)
!3377 = !DIGlobalVariableExpression(var: !3378, expr: !DIExpression())
!3378 = distinct !DIGlobalVariable(scope: null, file: !1297, line: 399, type: !2994, isLocal: true, isDefinition: true)
!3379 = !DIGlobalVariableExpression(var: !3380, expr: !DIExpression())
!3380 = distinct !DIGlobalVariable(scope: null, file: !1297, line: 399, type: !3381, isLocal: true, isDefinition: true)
!3381 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 1200, elements: !3382)
!3382 = !{!3383}
!3383 = !DISubrange(count: 150)
!3384 = !DIGlobalVariableExpression(var: !3385, expr: !DIExpression())
!3385 = distinct !DIGlobalVariable(scope: null, file: !1740, line: 144, type: !3386, isLocal: true, isDefinition: true)
!3386 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 176, elements: !3387)
!3387 = !{!3388}
!3388 = !DISubrange(count: 22)
!3389 = !DIGlobalVariableExpression(var: !3390, expr: !DIExpression())
!3390 = distinct !DIGlobalVariable(scope: null, file: !1740, line: 144, type: !3149, isLocal: true, isDefinition: true)
!3391 = !DIGlobalVariableExpression(var: !3392, expr: !DIExpression())
!3392 = distinct !DIGlobalVariable(scope: null, file: !1740, line: 144, type: !3393, isLocal: true, isDefinition: true)
!3393 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 1664, elements: !3394)
!3394 = !{!3395}
!3395 = !DISubrange(count: 208)
!3396 = !DIGlobalVariableExpression(var: !3397, expr: !DIExpression())
!3397 = distinct !DIGlobalVariable(scope: null, file: !869, line: 445, type: !3398, isLocal: true, isDefinition: true)
!3398 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 80, elements: !3399)
!3399 = !{!3400}
!3400 = !DISubrange(count: 10)
!3401 = !DIGlobalVariableExpression(var: !3402, expr: !DIExpression())
!3402 = distinct !DIGlobalVariable(scope: null, file: !869, line: 445, type: !3403, isLocal: true, isDefinition: true)
!3403 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 3696, elements: !3404)
!3404 = !{!3405}
!3405 = !DISubrange(count: 462)
!3406 = !DIGlobalVariableExpression(var: !3407, expr: !DIExpression())
!3407 = distinct !DIGlobalVariable(scope: null, file: !869, line: 623, type: !3092, isLocal: true, isDefinition: true)
!3408 = !DIGlobalVariableExpression(var: !3409, expr: !DIExpression())
!3409 = distinct !DIGlobalVariable(scope: null, file: !869, line: 623, type: !3410, isLocal: true, isDefinition: true)
!3410 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 1648, elements: !3411)
!3411 = !{!3412}
!3412 = !DISubrange(count: 206)
!3413 = !DIGlobalVariableExpression(var: !3414, expr: !DIExpression())
!3414 = distinct !DIGlobalVariable(scope: null, file: !869, line: 291, type: !3415, isLocal: true, isDefinition: true)
!3415 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 192, elements: !3416)
!3416 = !{!3417}
!3417 = !DISubrange(count: 24)
!3418 = !DIGlobalVariableExpression(var: !3419, expr: !DIExpression())
!3419 = distinct !DIGlobalVariable(scope: null, file: !869, line: 291, type: !3420, isLocal: true, isDefinition: true)
!3420 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 312, elements: !3421)
!3421 = !{!3422}
!3422 = !DISubrange(count: 39)
!3423 = !DIGlobalVariableExpression(var: !3424, expr: !DIExpression())
!3424 = distinct !DIGlobalVariable(scope: null, file: !869, line: 291, type: !3425, isLocal: true, isDefinition: true)
!3425 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 3624, elements: !3426)
!3426 = !{!3427}
!3427 = !DISubrange(count: 453)
!3428 = !DIGlobalVariableExpression(var: !3429, expr: !DIExpression())
!3429 = distinct !DIGlobalVariable(scope: null, file: !1740, line: 140, type: !3430, isLocal: true, isDefinition: true)
!3430 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 1568, elements: !3431)
!3431 = !{!3432}
!3432 = !DISubrange(count: 196)
!3433 = !DIGlobalVariableExpression(var: !3434, expr: !DIExpression())
!3434 = distinct !DIGlobalVariable(scope: null, file: !869, line: 98, type: !3386, isLocal: true, isDefinition: true)
!3435 = !DIGlobalVariableExpression(var: !3436, expr: !DIExpression())
!3436 = distinct !DIGlobalVariable(scope: null, file: !869, line: 98, type: !3437, isLocal: true, isDefinition: true)
!3437 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 384, elements: !3438)
!3438 = !{!3439}
!3439 = !DISubrange(count: 48)
!3440 = !DIGlobalVariableExpression(var: !3441, expr: !DIExpression())
!3441 = distinct !DIGlobalVariable(scope: null, file: !869, line: 98, type: !3442, isLocal: true, isDefinition: true)
!3442 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 3040, elements: !3443)
!3443 = !{!3444}
!3444 = !DISubrange(count: 380)
!3445 = !DIGlobalVariableExpression(var: !3446, expr: !DIExpression())
!3446 = distinct !DIGlobalVariable(scope: null, file: !1297, line: 436, type: !3447, isLocal: true, isDefinition: true)
!3447 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 216, elements: !3448)
!3448 = !{!3449}
!3449 = !DISubrange(count: 27)
!3450 = !DIGlobalVariableExpression(var: !3451, expr: !DIExpression())
!3451 = distinct !DIGlobalVariable(scope: null, file: !1297, line: 436, type: !2989, isLocal: true, isDefinition: true)
!3452 = !DIGlobalVariableExpression(var: !3453, expr: !DIExpression())
!3453 = distinct !DIGlobalVariable(scope: null, file: !1297, line: 436, type: !3454, isLocal: true, isDefinition: true)
!3454 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 1280, elements: !3455)
!3455 = !{!3456}
!3456 = !DISubrange(count: 160)
!3457 = !DIGlobalVariableExpression(var: !3458, expr: !DIExpression())
!3458 = distinct !DIGlobalVariable(scope: null, file: !1297, line: 215, type: !3459, isLocal: true, isDefinition: true)
!3459 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 872, elements: !3460)
!3460 = !{!3461}
!3461 = !DISubrange(count: 109)
!3462 = !DIGlobalVariableExpression(var: !3463, expr: !DIExpression())
!3463 = distinct !DIGlobalVariable(scope: null, file: !1297, line: 215, type: !3464, isLocal: true, isDefinition: true)
!3464 = !DICompositeType(tag: DW_TAG_array_type, baseType: !337, size: 904, elements: !3465)
!3465 = !{!3466}
!3466 = !DISubrange(count: 113)
!3467 = !{!3468, !3474, !3481, !3483, !3485, !3489, !3491, !3493, !3495, !3497, !3499, !3501, !3503, !3508, !3512, !3514, !3516, !3521, !3523, !3525, !3527, !3529, !3531, !3533, !3536, !3539, !3541, !3545, !3550, !3552, !3554, !3556, !3558, !3560, !3562, !3564, !3566, !3568, !3570, !3574, !3578, !3580, !3582, !3584, !3586, !3588, !3590, !3592, !3594, !3596, !3598, !3600, !3602, !3604, !3606, !3608, !3612, !3616, !3620, !3622, !3624, !3626, !3628, !3630, !3632, !3634, !3636, !3638, !3642, !3646, !3650, !3652, !3654, !3656, !3661, !3665, !3669, !3671, !3673, !3675, !3677, !3679, !3681, !3683, !3685, !3687, !3689, !3691, !3693, !3697, !3701, !3705, !3707, !3709, !3711, !3715, !3719, !3723, !3725, !3727, !3729, !3731, !3733, !3735, !3739, !3743, !3745, !3747, !3749, !3751, !3755, !3759, !3763, !3765, !3767, !3769, !3771, !3773, !3775, !3779, !3783, !3787, !3789, !3793, !3797, !3799, !3801, !3803, !3805, !3807, !3809, !3814, !3820, !3824, !3830, !3834, !3838, !3844, !3848, !3850, !3852, !3856, !3860, !3864, !3868, !3870, !3872, !3874, !3876, !3880, !3884, !3888, !3890, !3892, !3896, !3900, !3906, !3910, !3915, !3917, !3920, !3924, !3928, !3937, !3941, !3945, !3949, !3953, !3957, !3961, !3965, !3969, !3973, !3980, !3984, !3988, !3990, !3994, !3998, !4002, !4008, !4012, !4016, !4018, !4025, !4029, !4035, !4037, !4041, !4045, !4049, !4053, !4058, !4062, !4066, !4067, !4068, !4069, !4071, !4072, !4073, !4074, !4075, !4076, !4077, !4081, !4085, !4100, !4103, !4108, !4162, !4167, !4171, !4175, !4179, !4183, !4185, !4187, !4191, !4197, !4201, !4207, !4213, !4215, !4219, !4223, !4227, !4231, !4243, !4245, !4249, !4253, !4257, !4259, !4263, !4267, !4271, !4273, !4275, !4279, !4287, !4291, !4295, !4299, !4301, !4307, !4309, !4315, !4319, !4323, !4327, !4331, !4335, !4339, !4341, !4343, !4347, !4351, !4355, !4357, !4361, !4365, !4367, !4369, !4373, !4377, !4381, !4385, !4386, !4387, !4388, !4389, !4390, !4391, !4392, !4393, !4394, !4395, !4400, !4404, !4407, !4410, !4412, !4414, !4416, !4418, !4420, !4422, !4424, !4426, !4429, !4430, !4434, !4437, !4438, !4441, !4443, !4445, !4447, !4449, !4451, !4453, !4455, !4457, !4460, !4461, !4465, !4469, !4474, !4478, !4480, !4482, !4484, !4486, !4488, !4490, !4492, !4494, !4496, !4498, !4500, !4502, !4504, !4505, !4506, !4510, !4516, !4521, !4525, !4527, !4529, !4531, !4533, !4540, !4544, !4548, !4552, !4556, !4560, !4564, !4568, !4570, !4574, !4580, !4584, !4588, !4590, !4593, !4597, !4601, !4603, !4605, !4607, !4609, !4611, !4613, !4615, !4619, !4623, !4627, !4631, !4635, !4639, !4641, !4645, !4649, !4653, !4657, !4659, !4661, !4665, !4669, !4670, !4671, !4672, !4673, !4674, !4680, !4683, !4684, !4686, !4688, !4690, !4692, !4696, !4698, !4700, !4702, !4704, !4706, !4708, !4710, !4712, !4716, !4720, !4722, !4726, !4730, !4732, !4735, !4740, !4744, !4745, !4750, !4754, !4759, !4764, !4768, !4774, !4778, !4780, !4784}
!3468 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3469, file: !3473, line: 52)
!3469 = !DISubprogram(name: "abs", scope: !3470, file: !3470, line: 837, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3470 = !DIFile(filename: "/usr/include/stdlib.h", directory: "", checksumkind: CSK_MD5, checksum: "69d942f1572b8bd342d93c49f499f318")
!3471 = !DISubroutineType(types: !3472)
!3472 = !{!220, !220}
!3473 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h", directory: "")
!3474 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3475, file: !3480, line: 83)
!3475 = !DISubprogram(name: "acos", scope: !3476, file: !3476, line: 53, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3476 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", directory: "", checksumkind: CSK_MD5, checksum: "540523e6856cf8d57a3ebef5fd79793e")
!3477 = !DISubroutineType(types: !3478)
!3478 = !{!3479, !3479}
!3479 = !DIBasicType(name: "double", size: 64, encoding: DW_ATE_float)
!3480 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cmath", directory: "")
!3481 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3482, file: !3480, line: 102)
!3482 = !DISubprogram(name: "asin", scope: !3476, file: !3476, line: 55, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3483 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3484, file: !3480, line: 121)
!3484 = !DISubprogram(name: "atan", scope: !3476, file: !3476, line: 57, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3485 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3486, file: !3480, line: 140)
!3486 = !DISubprogram(name: "atan2", scope: !3476, file: !3476, line: 59, type: !3487, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3487 = !DISubroutineType(types: !3488)
!3488 = !{!3479, !3479, !3479}
!3489 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3490, file: !3480, line: 161)
!3490 = !DISubprogram(name: "ceil", scope: !3476, file: !3476, line: 159, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3491 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3492, file: !3480, line: 180)
!3492 = !DISubprogram(name: "cos", scope: !3476, file: !3476, line: 62, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3493 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3494, file: !3480, line: 199)
!3494 = !DISubprogram(name: "cosh", scope: !3476, file: !3476, line: 71, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3495 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3496, file: !3480, line: 218)
!3496 = !DISubprogram(name: "exp", scope: !3476, file: !3476, line: 95, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3497 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3498, file: !3480, line: 237)
!3498 = !DISubprogram(name: "fabs", scope: !3476, file: !3476, line: 162, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3499 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3500, file: !3480, line: 256)
!3500 = !DISubprogram(name: "floor", scope: !3476, file: !3476, line: 165, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3501 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3502, file: !3480, line: 275)
!3502 = !DISubprogram(name: "fmod", scope: !3476, file: !3476, line: 168, type: !3487, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3503 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3504, file: !3480, line: 296)
!3504 = !DISubprogram(name: "frexp", scope: !3476, file: !3476, line: 98, type: !3505, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3505 = !DISubroutineType(types: !3506)
!3506 = !{!3479, !3479, !3507}
!3507 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !220, size: 64)
!3508 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3509, file: !3480, line: 315)
!3509 = !DISubprogram(name: "ldexp", scope: !3476, file: !3476, line: 101, type: !3510, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3510 = !DISubroutineType(types: !3511)
!3511 = !{!3479, !3479, !220}
!3512 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3513, file: !3480, line: 334)
!3513 = !DISubprogram(name: "log", scope: !3476, file: !3476, line: 104, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3514 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3515, file: !3480, line: 353)
!3515 = !DISubprogram(name: "log10", scope: !3476, file: !3476, line: 107, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3516 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3517, file: !3480, line: 372)
!3517 = !DISubprogram(name: "modf", scope: !3476, file: !3476, line: 110, type: !3518, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3518 = !DISubroutineType(types: !3519)
!3519 = !{!3479, !3479, !3520}
!3520 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3479, size: 64)
!3521 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3522, file: !3480, line: 384)
!3522 = !DISubprogram(name: "pow", scope: !3476, file: !3476, line: 140, type: !3487, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3523 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3524, file: !3480, line: 421)
!3524 = !DISubprogram(name: "sin", scope: !3476, file: !3476, line: 64, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3525 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3526, file: !3480, line: 440)
!3526 = !DISubprogram(name: "sinh", scope: !3476, file: !3476, line: 73, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3527 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3528, file: !3480, line: 459)
!3528 = !DISubprogram(name: "sqrt", scope: !3476, file: !3476, line: 143, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3529 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3530, file: !3480, line: 478)
!3530 = !DISubprogram(name: "tan", scope: !3476, file: !3476, line: 66, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3531 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3532, file: !3480, line: 497)
!3532 = !DISubprogram(name: "tanh", scope: !3476, file: !3476, line: 75, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3533 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3534, file: !3480, line: 1065)
!3534 = !DIDerivedType(tag: DW_TAG_typedef, name: "double_t", file: !3535, line: 150, baseType: !3479)
!3535 = !DIFile(filename: "/usr/include/math.h", directory: "", checksumkind: CSK_MD5, checksum: "ecf196918078d683ff91ad9a1c51599a")
!3536 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3537, file: !3480, line: 1066)
!3537 = !DIDerivedType(tag: DW_TAG_typedef, name: "float_t", file: !3535, line: 149, baseType: !3538)
!3538 = !DIBasicType(name: "float", size: 32, encoding: DW_ATE_float)
!3539 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3540, file: !3480, line: 1069)
!3540 = !DISubprogram(name: "acosh", scope: !3476, file: !3476, line: 85, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3541 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3542, file: !3480, line: 1070)
!3542 = !DISubprogram(name: "acoshf", scope: !3476, file: !3476, line: 85, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3543 = !DISubroutineType(types: !3544)
!3544 = !{!3538, !3538}
!3545 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3546, file: !3480, line: 1071)
!3546 = !DISubprogram(name: "acoshl", scope: !3476, file: !3476, line: 85, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3547 = !DISubroutineType(types: !3548)
!3548 = !{!3549, !3549}
!3549 = !DIBasicType(name: "long double", size: 128, encoding: DW_ATE_float)
!3550 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3551, file: !3480, line: 1073)
!3551 = !DISubprogram(name: "asinh", scope: !3476, file: !3476, line: 87, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3552 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3553, file: !3480, line: 1074)
!3553 = !DISubprogram(name: "asinhf", scope: !3476, file: !3476, line: 87, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3554 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3555, file: !3480, line: 1075)
!3555 = !DISubprogram(name: "asinhl", scope: !3476, file: !3476, line: 87, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3556 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3557, file: !3480, line: 1077)
!3557 = !DISubprogram(name: "atanh", scope: !3476, file: !3476, line: 89, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3558 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3559, file: !3480, line: 1078)
!3559 = !DISubprogram(name: "atanhf", scope: !3476, file: !3476, line: 89, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3560 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3561, file: !3480, line: 1079)
!3561 = !DISubprogram(name: "atanhl", scope: !3476, file: !3476, line: 89, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3562 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3563, file: !3480, line: 1081)
!3563 = !DISubprogram(name: "cbrt", scope: !3476, file: !3476, line: 152, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3564 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3565, file: !3480, line: 1082)
!3565 = !DISubprogram(name: "cbrtf", scope: !3476, file: !3476, line: 152, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3566 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3567, file: !3480, line: 1083)
!3567 = !DISubprogram(name: "cbrtl", scope: !3476, file: !3476, line: 152, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3568 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3569, file: !3480, line: 1085)
!3569 = !DISubprogram(name: "copysign", scope: !3476, file: !3476, line: 196, type: !3487, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3570 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3571, file: !3480, line: 1086)
!3571 = !DISubprogram(name: "copysignf", scope: !3476, file: !3476, line: 196, type: !3572, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3572 = !DISubroutineType(types: !3573)
!3573 = !{!3538, !3538, !3538}
!3574 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3575, file: !3480, line: 1087)
!3575 = !DISubprogram(name: "copysignl", scope: !3476, file: !3476, line: 196, type: !3576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3576 = !DISubroutineType(types: !3577)
!3577 = !{!3549, !3549, !3549}
!3578 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3579, file: !3480, line: 1089)
!3579 = !DISubprogram(name: "erf", scope: !3476, file: !3476, line: 228, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3580 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3581, file: !3480, line: 1090)
!3581 = !DISubprogram(name: "erff", scope: !3476, file: !3476, line: 228, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3582 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3583, file: !3480, line: 1091)
!3583 = !DISubprogram(name: "erfl", scope: !3476, file: !3476, line: 228, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3584 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3585, file: !3480, line: 1093)
!3585 = !DISubprogram(name: "erfc", scope: !3476, file: !3476, line: 229, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3586 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3587, file: !3480, line: 1094)
!3587 = !DISubprogram(name: "erfcf", scope: !3476, file: !3476, line: 229, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3588 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3589, file: !3480, line: 1095)
!3589 = !DISubprogram(name: "erfcl", scope: !3476, file: !3476, line: 229, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3590 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3591, file: !3480, line: 1097)
!3591 = !DISubprogram(name: "exp2", scope: !3476, file: !3476, line: 130, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3592 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3593, file: !3480, line: 1098)
!3593 = !DISubprogram(name: "exp2f", scope: !3476, file: !3476, line: 130, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3594 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3595, file: !3480, line: 1099)
!3595 = !DISubprogram(name: "exp2l", scope: !3476, file: !3476, line: 130, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3596 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3597, file: !3480, line: 1101)
!3597 = !DISubprogram(name: "expm1", scope: !3476, file: !3476, line: 119, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3598 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3599, file: !3480, line: 1102)
!3599 = !DISubprogram(name: "expm1f", scope: !3476, file: !3476, line: 119, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3600 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3601, file: !3480, line: 1103)
!3601 = !DISubprogram(name: "expm1l", scope: !3476, file: !3476, line: 119, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3602 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3603, file: !3480, line: 1105)
!3603 = !DISubprogram(name: "fdim", scope: !3476, file: !3476, line: 326, type: !3487, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3604 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3605, file: !3480, line: 1106)
!3605 = !DISubprogram(name: "fdimf", scope: !3476, file: !3476, line: 326, type: !3572, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3606 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3607, file: !3480, line: 1107)
!3607 = !DISubprogram(name: "fdiml", scope: !3476, file: !3476, line: 326, type: !3576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3608 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3609, file: !3480, line: 1109)
!3609 = !DISubprogram(name: "fma", scope: !3476, file: !3476, line: 335, type: !3610, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3610 = !DISubroutineType(types: !3611)
!3611 = !{!3479, !3479, !3479, !3479}
!3612 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3613, file: !3480, line: 1110)
!3613 = !DISubprogram(name: "fmaf", scope: !3476, file: !3476, line: 335, type: !3614, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3614 = !DISubroutineType(types: !3615)
!3615 = !{!3538, !3538, !3538, !3538}
!3616 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3617, file: !3480, line: 1111)
!3617 = !DISubprogram(name: "fmal", scope: !3476, file: !3476, line: 335, type: !3618, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3618 = !DISubroutineType(types: !3619)
!3619 = !{!3549, !3549, !3549, !3549}
!3620 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3621, file: !3480, line: 1113)
!3621 = !DISubprogram(name: "fmax", scope: !3476, file: !3476, line: 329, type: !3487, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3622 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3623, file: !3480, line: 1114)
!3623 = !DISubprogram(name: "fmaxf", scope: !3476, file: !3476, line: 329, type: !3572, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3624 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3625, file: !3480, line: 1115)
!3625 = !DISubprogram(name: "fmaxl", scope: !3476, file: !3476, line: 329, type: !3576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3626 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3627, file: !3480, line: 1117)
!3627 = !DISubprogram(name: "fmin", scope: !3476, file: !3476, line: 332, type: !3487, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3628 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3629, file: !3480, line: 1118)
!3629 = !DISubprogram(name: "fminf", scope: !3476, file: !3476, line: 332, type: !3572, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3630 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3631, file: !3480, line: 1119)
!3631 = !DISubprogram(name: "fminl", scope: !3476, file: !3476, line: 332, type: !3576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3632 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3633, file: !3480, line: 1121)
!3633 = !DISubprogram(name: "hypot", scope: !3476, file: !3476, line: 147, type: !3487, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3634 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3635, file: !3480, line: 1122)
!3635 = !DISubprogram(name: "hypotf", scope: !3476, file: !3476, line: 147, type: !3572, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3636 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3637, file: !3480, line: 1123)
!3637 = !DISubprogram(name: "hypotl", scope: !3476, file: !3476, line: 147, type: !3576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3638 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3639, file: !3480, line: 1125)
!3639 = !DISubprogram(name: "ilogb", scope: !3476, file: !3476, line: 280, type: !3640, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3640 = !DISubroutineType(types: !3641)
!3641 = !{!220, !3479}
!3642 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3643, file: !3480, line: 1126)
!3643 = !DISubprogram(name: "ilogbf", scope: !3476, file: !3476, line: 280, type: !3644, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3644 = !DISubroutineType(types: !3645)
!3645 = !{!220, !3538}
!3646 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3647, file: !3480, line: 1127)
!3647 = !DISubprogram(name: "ilogbl", scope: !3476, file: !3476, line: 280, type: !3648, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3648 = !DISubroutineType(types: !3649)
!3649 = !{!220, !3549}
!3650 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3651, file: !3480, line: 1129)
!3651 = !DISubprogram(name: "lgamma", scope: !3476, file: !3476, line: 230, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3652 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3653, file: !3480, line: 1130)
!3653 = !DISubprogram(name: "lgammaf", scope: !3476, file: !3476, line: 230, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3654 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3655, file: !3480, line: 1131)
!3655 = !DISubprogram(name: "lgammal", scope: !3476, file: !3476, line: 230, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3656 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3657, file: !3480, line: 1134)
!3657 = !DISubprogram(name: "llrint", scope: !3476, file: !3476, line: 316, type: !3658, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3658 = !DISubroutineType(types: !3659)
!3659 = !{!3660, !3479}
!3660 = !DIBasicType(name: "long long", size: 64, encoding: DW_ATE_signed)
!3661 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3662, file: !3480, line: 1135)
!3662 = !DISubprogram(name: "llrintf", scope: !3476, file: !3476, line: 316, type: !3663, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3663 = !DISubroutineType(types: !3664)
!3664 = !{!3660, !3538}
!3665 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3666, file: !3480, line: 1136)
!3666 = !DISubprogram(name: "llrintl", scope: !3476, file: !3476, line: 316, type: !3667, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3667 = !DISubroutineType(types: !3668)
!3668 = !{!3660, !3549}
!3669 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3670, file: !3480, line: 1138)
!3670 = !DISubprogram(name: "llround", scope: !3476, file: !3476, line: 322, type: !3658, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3671 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3672, file: !3480, line: 1139)
!3672 = !DISubprogram(name: "llroundf", scope: !3476, file: !3476, line: 322, type: !3663, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3673 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3674, file: !3480, line: 1140)
!3674 = !DISubprogram(name: "llroundl", scope: !3476, file: !3476, line: 322, type: !3667, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3675 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3676, file: !3480, line: 1143)
!3676 = !DISubprogram(name: "log1p", scope: !3476, file: !3476, line: 122, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3677 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3678, file: !3480, line: 1144)
!3678 = !DISubprogram(name: "log1pf", scope: !3476, file: !3476, line: 122, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3679 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3680, file: !3480, line: 1145)
!3680 = !DISubprogram(name: "log1pl", scope: !3476, file: !3476, line: 122, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3681 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3682, file: !3480, line: 1147)
!3682 = !DISubprogram(name: "log2", scope: !3476, file: !3476, line: 133, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3683 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3684, file: !3480, line: 1148)
!3684 = !DISubprogram(name: "log2f", scope: !3476, file: !3476, line: 133, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3685 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3686, file: !3480, line: 1149)
!3686 = !DISubprogram(name: "log2l", scope: !3476, file: !3476, line: 133, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3687 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3688, file: !3480, line: 1151)
!3688 = !DISubprogram(name: "logb", scope: !3476, file: !3476, line: 125, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3689 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3690, file: !3480, line: 1152)
!3690 = !DISubprogram(name: "logbf", scope: !3476, file: !3476, line: 125, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3691 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3692, file: !3480, line: 1153)
!3692 = !DISubprogram(name: "logbl", scope: !3476, file: !3476, line: 125, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3693 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3694, file: !3480, line: 1155)
!3694 = !DISubprogram(name: "lrint", scope: !3476, file: !3476, line: 314, type: !3695, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3695 = !DISubroutineType(types: !3696)
!3696 = !{!23, !3479}
!3697 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3698, file: !3480, line: 1156)
!3698 = !DISubprogram(name: "lrintf", scope: !3476, file: !3476, line: 314, type: !3699, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3699 = !DISubroutineType(types: !3700)
!3700 = !{!23, !3538}
!3701 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3702, file: !3480, line: 1157)
!3702 = !DISubprogram(name: "lrintl", scope: !3476, file: !3476, line: 314, type: !3703, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3703 = !DISubroutineType(types: !3704)
!3704 = !{!23, !3549}
!3705 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3706, file: !3480, line: 1159)
!3706 = !DISubprogram(name: "lround", scope: !3476, file: !3476, line: 320, type: !3695, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3707 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3708, file: !3480, line: 1160)
!3708 = !DISubprogram(name: "lroundf", scope: !3476, file: !3476, line: 320, type: !3699, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3709 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3710, file: !3480, line: 1161)
!3710 = !DISubprogram(name: "lroundl", scope: !3476, file: !3476, line: 320, type: !3703, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3711 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3712, file: !3480, line: 1163)
!3712 = !DISubprogram(name: "nan", scope: !3476, file: !3476, line: 201, type: !3713, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3713 = !DISubroutineType(types: !3714)
!3714 = !{!3479, !336}
!3715 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3716, file: !3480, line: 1164)
!3716 = !DISubprogram(name: "nanf", scope: !3476, file: !3476, line: 201, type: !3717, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3717 = !DISubroutineType(types: !3718)
!3718 = !{!3538, !336}
!3719 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3720, file: !3480, line: 1165)
!3720 = !DISubprogram(name: "nanl", scope: !3476, file: !3476, line: 201, type: !3721, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3721 = !DISubroutineType(types: !3722)
!3722 = !{!3549, !336}
!3723 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3724, file: !3480, line: 1167)
!3724 = !DISubprogram(name: "nearbyint", scope: !3476, file: !3476, line: 294, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3725 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3726, file: !3480, line: 1168)
!3726 = !DISubprogram(name: "nearbyintf", scope: !3476, file: !3476, line: 294, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3727 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3728, file: !3480, line: 1169)
!3728 = !DISubprogram(name: "nearbyintl", scope: !3476, file: !3476, line: 294, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3729 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3730, file: !3480, line: 1171)
!3730 = !DISubprogram(name: "nextafter", scope: !3476, file: !3476, line: 259, type: !3487, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3731 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3732, file: !3480, line: 1172)
!3732 = !DISubprogram(name: "nextafterf", scope: !3476, file: !3476, line: 259, type: !3572, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3733 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3734, file: !3480, line: 1173)
!3734 = !DISubprogram(name: "nextafterl", scope: !3476, file: !3476, line: 259, type: !3576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3735 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3736, file: !3480, line: 1175)
!3736 = !DISubprogram(name: "nexttoward", scope: !3476, file: !3476, line: 261, type: !3737, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3737 = !DISubroutineType(types: !3738)
!3738 = !{!3479, !3479, !3549}
!3739 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3740, file: !3480, line: 1176)
!3740 = !DISubprogram(name: "nexttowardf", scope: !3476, file: !3476, line: 261, type: !3741, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3741 = !DISubroutineType(types: !3742)
!3742 = !{!3538, !3538, !3549}
!3743 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3744, file: !3480, line: 1177)
!3744 = !DISubprogram(name: "nexttowardl", scope: !3476, file: !3476, line: 261, type: !3576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3745 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3746, file: !3480, line: 1179)
!3746 = !DISubprogram(name: "remainder", scope: !3476, file: !3476, line: 272, type: !3487, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3747 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3748, file: !3480, line: 1180)
!3748 = !DISubprogram(name: "remainderf", scope: !3476, file: !3476, line: 272, type: !3572, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3749 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3750, file: !3480, line: 1181)
!3750 = !DISubprogram(name: "remainderl", scope: !3476, file: !3476, line: 272, type: !3576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3751 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3752, file: !3480, line: 1183)
!3752 = !DISubprogram(name: "remquo", scope: !3476, file: !3476, line: 307, type: !3753, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3753 = !DISubroutineType(types: !3754)
!3754 = !{!3479, !3479, !3479, !3507}
!3755 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3756, file: !3480, line: 1184)
!3756 = !DISubprogram(name: "remquof", scope: !3476, file: !3476, line: 307, type: !3757, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3757 = !DISubroutineType(types: !3758)
!3758 = !{!3538, !3538, !3538, !3507}
!3759 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3760, file: !3480, line: 1185)
!3760 = !DISubprogram(name: "remquol", scope: !3476, file: !3476, line: 307, type: !3761, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3761 = !DISubroutineType(types: !3762)
!3762 = !{!3549, !3549, !3549, !3507}
!3763 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3764, file: !3480, line: 1187)
!3764 = !DISubprogram(name: "rint", scope: !3476, file: !3476, line: 256, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3765 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3766, file: !3480, line: 1188)
!3766 = !DISubprogram(name: "rintf", scope: !3476, file: !3476, line: 256, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3767 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3768, file: !3480, line: 1189)
!3768 = !DISubprogram(name: "rintl", scope: !3476, file: !3476, line: 256, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3769 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3770, file: !3480, line: 1191)
!3770 = !DISubprogram(name: "round", scope: !3476, file: !3476, line: 298, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3771 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3772, file: !3480, line: 1192)
!3772 = !DISubprogram(name: "roundf", scope: !3476, file: !3476, line: 298, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3773 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3774, file: !3480, line: 1193)
!3774 = !DISubprogram(name: "roundl", scope: !3476, file: !3476, line: 298, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3775 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3776, file: !3480, line: 1195)
!3776 = !DISubprogram(name: "scalbln", scope: !3476, file: !3476, line: 290, type: !3777, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3777 = !DISubroutineType(types: !3778)
!3778 = !{!3479, !3479, !23}
!3779 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3780, file: !3480, line: 1196)
!3780 = !DISubprogram(name: "scalblnf", scope: !3476, file: !3476, line: 290, type: !3781, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3781 = !DISubroutineType(types: !3782)
!3782 = !{!3538, !3538, !23}
!3783 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3784, file: !3480, line: 1197)
!3784 = !DISubprogram(name: "scalblnl", scope: !3476, file: !3476, line: 290, type: !3785, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3785 = !DISubroutineType(types: !3786)
!3786 = !{!3549, !3549, !23}
!3787 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3788, file: !3480, line: 1199)
!3788 = !DISubprogram(name: "scalbn", scope: !3476, file: !3476, line: 276, type: !3510, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3789 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3790, file: !3480, line: 1200)
!3790 = !DISubprogram(name: "scalbnf", scope: !3476, file: !3476, line: 276, type: !3791, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3791 = !DISubroutineType(types: !3792)
!3792 = !{!3538, !3538, !220}
!3793 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3794, file: !3480, line: 1201)
!3794 = !DISubprogram(name: "scalbnl", scope: !3476, file: !3476, line: 276, type: !3795, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3795 = !DISubroutineType(types: !3796)
!3796 = !{!3549, !3549, !220}
!3797 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3798, file: !3480, line: 1203)
!3798 = !DISubprogram(name: "tgamma", scope: !3476, file: !3476, line: 235, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3799 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3800, file: !3480, line: 1204)
!3800 = !DISubprogram(name: "tgammaf", scope: !3476, file: !3476, line: 235, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3801 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3802, file: !3480, line: 1205)
!3802 = !DISubprogram(name: "tgammal", scope: !3476, file: !3476, line: 235, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3803 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3804, file: !3480, line: 1207)
!3804 = !DISubprogram(name: "trunc", scope: !3476, file: !3476, line: 302, type: !3477, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3805 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3806, file: !3480, line: 1208)
!3806 = !DISubprogram(name: "truncf", scope: !3476, file: !3476, line: 302, type: !3543, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3807 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3808, file: !3480, line: 1209)
!3808 = !DISubprogram(name: "truncl", scope: !3476, file: !3476, line: 302, type: !3547, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3809 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3810, file: !3813, line: 56)
!3810 = !DIDerivedType(tag: DW_TAG_typedef, name: "max_align_t", file: !3811, line: 24, baseType: !3812)
!3811 = !DIFile(filename: "llvm5/build/lib/clang/15.0.3/include/__stddef_max_align_t.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "48e8e2456f77e6cda35d245130fa7259")
!3812 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !3811, line: 19, size: 256, flags: DIFlagFwdDecl, identifier: "_ZTS11max_align_t")
!3813 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstddef", directory: "")
!3814 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3815, file: !3819, line: 75)
!3815 = !DISubprogram(name: "memchr", scope: !3816, file: !3816, line: 90, type: !3817, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3816 = !DIFile(filename: "/usr/include/string.h", directory: "", checksumkind: CSK_MD5, checksum: "1029a2d94b0e7b73f8dbf87ca20ab7bc")
!3817 = !DISubroutineType(types: !3818)
!3818 = !{!132, !142, !220, !1076}
!3819 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstring", directory: "")
!3820 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3821, file: !3819, line: 76)
!3821 = !DISubprogram(name: "memcmp", scope: !3816, file: !3816, line: 63, type: !3822, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3822 = !DISubroutineType(types: !3823)
!3823 = !{!220, !142, !142, !1076}
!3824 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3825, file: !3819, line: 77)
!3825 = !DISubprogram(name: "memcpy", scope: !3816, file: !3816, line: 42, type: !3826, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3826 = !DISubroutineType(types: !3827)
!3827 = !{!132, !3828, !3829, !1076}
!3828 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !132)
!3829 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !142)
!3830 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3831, file: !3819, line: 78)
!3831 = !DISubprogram(name: "memmove", scope: !3816, file: !3816, line: 46, type: !3832, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3832 = !DISubroutineType(types: !3833)
!3833 = !{!132, !132, !142, !1076}
!3834 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3835, file: !3819, line: 79)
!3835 = !DISubprogram(name: "memset", scope: !3816, file: !3816, line: 60, type: !3836, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3836 = !DISubroutineType(types: !3837)
!3837 = !{!132, !132, !220, !1076}
!3838 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3839, file: !3819, line: 80)
!3839 = !DISubprogram(name: "strcat", scope: !3816, file: !3816, line: 129, type: !3840, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3840 = !DISubroutineType(types: !3841)
!3841 = !{!1295, !3842, !3843}
!3842 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !1295)
!3843 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !336)
!3844 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3845, file: !3819, line: 81)
!3845 = !DISubprogram(name: "strcmp", scope: !3816, file: !3816, line: 136, type: !3846, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3846 = !DISubroutineType(types: !3847)
!3847 = !{!220, !336, !336}
!3848 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3849, file: !3819, line: 82)
!3849 = !DISubprogram(name: "strcoll", scope: !3816, file: !3816, line: 143, type: !3846, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3850 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3851, file: !3819, line: 83)
!3851 = !DISubprogram(name: "strcpy", scope: !3816, file: !3816, line: 121, type: !3840, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3852 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3853, file: !3819, line: 84)
!3853 = !DISubprogram(name: "strcspn", scope: !3816, file: !3816, line: 272, type: !3854, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3854 = !DISubroutineType(types: !3855)
!3855 = !{!1076, !336, !336}
!3856 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3857, file: !3819, line: 85)
!3857 = !DISubprogram(name: "strerror", scope: !3816, file: !3816, line: 396, type: !3858, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3858 = !DISubroutineType(types: !3859)
!3859 = !{!1295, !220}
!3860 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3861, file: !3819, line: 86)
!3861 = !DISubprogram(name: "strlen", scope: !3816, file: !3816, line: 384, type: !3862, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3862 = !DISubroutineType(types: !3863)
!3863 = !{!1076, !336}
!3864 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3865, file: !3819, line: 87)
!3865 = !DISubprogram(name: "strncat", scope: !3816, file: !3816, line: 132, type: !3866, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3866 = !DISubroutineType(types: !3867)
!3867 = !{!1295, !3842, !3843, !1076}
!3868 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3869, file: !3819, line: 88)
!3869 = !DISubprogram(name: "strncmp", scope: !3816, file: !3816, line: 139, type: !1505, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3870 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3871, file: !3819, line: 89)
!3871 = !DISubprogram(name: "strncpy", scope: !3816, file: !3816, line: 124, type: !3866, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3872 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3873, file: !3819, line: 90)
!3873 = !DISubprogram(name: "strspn", scope: !3816, file: !3816, line: 276, type: !3854, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3874 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3875, file: !3819, line: 91)
!3875 = !DISubprogram(name: "strtok", scope: !3816, file: !3816, line: 335, type: !3840, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3876 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3877, file: !3819, line: 92)
!3877 = !DISubprogram(name: "strxfrm", scope: !3816, file: !3816, line: 146, type: !3878, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3878 = !DISubroutineType(types: !3879)
!3879 = !{!1076, !3842, !3843, !1076}
!3880 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3881, file: !3819, line: 93)
!3881 = !DISubprogram(name: "strchr", scope: !3816, file: !3816, line: 225, type: !3882, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3882 = !DISubroutineType(types: !3883)
!3883 = !{!1295, !336, !220}
!3884 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3885, file: !3819, line: 94)
!3885 = !DISubprogram(name: "strpbrk", scope: !3816, file: !3816, line: 302, type: !3886, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3886 = !DISubroutineType(types: !3887)
!3887 = !{!1295, !336, !336}
!3888 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3889, file: !3819, line: 95)
!3889 = !DISubprogram(name: "strrchr", scope: !3816, file: !3816, line: 252, type: !3882, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3890 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3891, file: !3819, line: 96)
!3891 = !DISubprogram(name: "strstr", scope: !3816, file: !3816, line: 329, type: !3886, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3892 = !DIImportedEntity(tag: DW_TAG_imported_module, scope: !3893, entity: !3894, file: !3895, line: 58)
!3893 = !DINamespace(name: "__gnu_debug", scope: null)
!3894 = !DINamespace(name: "__debug", scope: !320)
!3895 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/debug/debug.h", directory: "", checksumkind: CSK_MD5, checksum: "0d648599b52b1d377b1fee4a0a4b2b91")
!3896 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3897, file: !3899, line: 127)
!3897 = !DIDerivedType(tag: DW_TAG_typedef, name: "div_t", file: !3470, line: 62, baseType: !3898)
!3898 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !3470, line: 58, size: 64, flags: DIFlagFwdDecl, identifier: "_ZTS5div_t")
!3899 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdlib", directory: "")
!3900 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3901, file: !3899, line: 128)
!3901 = !DIDerivedType(tag: DW_TAG_typedef, name: "ldiv_t", file: !3470, line: 70, baseType: !3902)
!3902 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !3470, line: 66, size: 128, flags: DIFlagTypePassByValue, elements: !3903, identifier: "_ZTS6ldiv_t")
!3903 = !{!3904, !3905}
!3904 = !DIDerivedType(tag: DW_TAG_member, name: "quot", scope: !3902, file: !3470, line: 68, baseType: !23, size: 64)
!3905 = !DIDerivedType(tag: DW_TAG_member, name: "rem", scope: !3902, file: !3470, line: 69, baseType: !23, size: 64, offset: 64)
!3906 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3907, file: !3899, line: 130)
!3907 = !DISubprogram(name: "abort", scope: !3470, file: !3470, line: 588, type: !3908, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!3908 = !DISubroutineType(types: !3909)
!3909 = !{null}
!3910 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3911, file: !3899, line: 134)
!3911 = !DISubprogram(name: "atexit", scope: !3470, file: !3470, line: 592, type: !3912, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3912 = !DISubroutineType(types: !3913)
!3913 = !{!220, !3914}
!3914 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3908, size: 64)
!3915 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3916, file: !3899, line: 137)
!3916 = !DISubprogram(name: "at_quick_exit", scope: !3470, file: !3470, line: 597, type: !3912, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3917 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3918, file: !3899, line: 140)
!3918 = !DISubprogram(name: "atof", scope: !3919, file: !3919, line: 25, type: !3713, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3919 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h", directory: "", checksumkind: CSK_MD5, checksum: "ce60958b260b171e83db3307f1d644f0")
!3920 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3921, file: !3899, line: 141)
!3921 = !DISubprogram(name: "atoi", scope: !3470, file: !3470, line: 361, type: !3922, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3922 = !DISubroutineType(types: !3923)
!3923 = !{!220, !336}
!3924 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3925, file: !3899, line: 142)
!3925 = !DISubprogram(name: "atol", scope: !3470, file: !3470, line: 366, type: !3926, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3926 = !DISubroutineType(types: !3927)
!3927 = !{!23, !336}
!3928 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3929, file: !3899, line: 143)
!3929 = !DISubprogram(name: "bsearch", scope: !3930, file: !3930, line: 20, type: !3931, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3930 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h", directory: "", checksumkind: CSK_MD5, checksum: "1a798a38b25adee7bb680abce9ef568a")
!3931 = !DISubroutineType(types: !3932)
!3932 = !{!132, !142, !142, !1076, !1076, !3933}
!3933 = !DIDerivedType(tag: DW_TAG_typedef, name: "__compar_fn_t", file: !3470, line: 805, baseType: !3934)
!3934 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3935, size: 64)
!3935 = !DISubroutineType(types: !3936)
!3936 = !{!220, !142, !142}
!3937 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3938, file: !3899, line: 144)
!3938 = !DISubprogram(name: "calloc", scope: !3470, file: !3470, line: 541, type: !3939, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3939 = !DISubroutineType(types: !3940)
!3940 = !{!132, !1076, !1076}
!3941 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3942, file: !3899, line: 145)
!3942 = !DISubprogram(name: "div", scope: !3470, file: !3470, line: 849, type: !3943, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3943 = !DISubroutineType(types: !3944)
!3944 = !{!3897, !220, !220}
!3945 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3946, file: !3899, line: 146)
!3946 = !DISubprogram(name: "exit", scope: !3470, file: !3470, line: 614, type: !3947, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!3947 = !DISubroutineType(types: !3948)
!3948 = !{null, !220}
!3949 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3950, file: !3899, line: 147)
!3950 = !DISubprogram(name: "free", scope: !3470, file: !3470, line: 563, type: !3951, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3951 = !DISubroutineType(types: !3952)
!3952 = !{null, !132}
!3953 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3954, file: !3899, line: 148)
!3954 = !DISubprogram(name: "getenv", scope: !3470, file: !3470, line: 631, type: !3955, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3955 = !DISubroutineType(types: !3956)
!3956 = !{!1295, !336}
!3957 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3958, file: !3899, line: 149)
!3958 = !DISubprogram(name: "labs", scope: !3470, file: !3470, line: 838, type: !3959, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3959 = !DISubroutineType(types: !3960)
!3960 = !{!23, !23}
!3961 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3962, file: !3899, line: 150)
!3962 = !DISubprogram(name: "ldiv", scope: !3470, file: !3470, line: 851, type: !3963, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3963 = !DISubroutineType(types: !3964)
!3964 = !{!3901, !23, !23}
!3965 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3966, file: !3899, line: 151)
!3966 = !DISubprogram(name: "malloc", scope: !3470, file: !3470, line: 539, type: !3967, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3967 = !DISubroutineType(types: !3968)
!3968 = !{!132, !1076}
!3969 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3970, file: !3899, line: 153)
!3970 = !DISubprogram(name: "mblen", scope: !3470, file: !3470, line: 919, type: !3971, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3971 = !DISubroutineType(types: !3972)
!3972 = !{!220, !336, !1076}
!3973 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3974, file: !3899, line: 154)
!3974 = !DISubprogram(name: "mbstowcs", scope: !3470, file: !3470, line: 930, type: !3975, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3975 = !DISubroutineType(types: !3976)
!3976 = !{!1076, !3977, !3843, !1076}
!3977 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3978)
!3978 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3979, size: 64)
!3979 = !DIBasicType(name: "wchar_t", size: 32, encoding: DW_ATE_signed)
!3980 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3981, file: !3899, line: 155)
!3981 = !DISubprogram(name: "mbtowc", scope: !3470, file: !3470, line: 922, type: !3982, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3982 = !DISubroutineType(types: !3983)
!3983 = !{!220, !3977, !3843, !1076}
!3984 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3985, file: !3899, line: 157)
!3985 = !DISubprogram(name: "qsort", scope: !3470, file: !3470, line: 827, type: !3986, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3986 = !DISubroutineType(types: !3987)
!3987 = !{null, !132, !1076, !1076, !3933}
!3988 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3989, file: !3899, line: 160)
!3989 = !DISubprogram(name: "quick_exit", scope: !3470, file: !3470, line: 620, type: !3947, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!3990 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3991, file: !3899, line: 163)
!3991 = !DISubprogram(name: "rand", scope: !3470, file: !3470, line: 453, type: !3992, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3992 = !DISubroutineType(types: !3993)
!3993 = !{!220}
!3994 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3995, file: !3899, line: 164)
!3995 = !DISubprogram(name: "realloc", scope: !3470, file: !3470, line: 549, type: !3996, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3996 = !DISubroutineType(types: !3997)
!3997 = !{!132, !132, !1076}
!3998 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3999, file: !3899, line: 165)
!3999 = !DISubprogram(name: "srand", scope: !3470, file: !3470, line: 455, type: !4000, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4000 = !DISubroutineType(types: !4001)
!4001 = !{null, !6}
!4002 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4003, file: !3899, line: 166)
!4003 = !DISubprogram(name: "strtod", scope: !3470, file: !3470, line: 117, type: !4004, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4004 = !DISubroutineType(types: !4005)
!4005 = !{!3479, !3843, !4006}
!4006 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4007)
!4007 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1295, size: 64)
!4008 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4009, file: !3899, line: 167)
!4009 = !DISubprogram(name: "strtol", scope: !3470, file: !3470, line: 176, type: !4010, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4010 = !DISubroutineType(types: !4011)
!4011 = !{!23, !3843, !4006, !220}
!4012 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4013, file: !3899, line: 168)
!4013 = !DISubprogram(name: "strtoul", scope: !3470, file: !3470, line: 180, type: !4014, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4014 = !DISubroutineType(types: !4015)
!4015 = !{!283, !3843, !4006, !220}
!4016 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4017, file: !3899, line: 169)
!4017 = !DISubprogram(name: "system", scope: !3470, file: !3470, line: 781, type: !3922, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4018 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4019, file: !3899, line: 171)
!4019 = !DISubprogram(name: "wcstombs", scope: !3470, file: !3470, line: 933, type: !4020, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4020 = !DISubroutineType(types: !4021)
!4021 = !{!1076, !3842, !4022, !1076}
!4022 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4023)
!4023 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4024, size: 64)
!4024 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3979)
!4025 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4026, file: !3899, line: 172)
!4026 = !DISubprogram(name: "wctomb", scope: !3470, file: !3470, line: 926, type: !4027, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4027 = !DISubroutineType(types: !4028)
!4028 = !{!220, !1295, !3979}
!4029 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4030, file: !3899, line: 200)
!4030 = !DIDerivedType(tag: DW_TAG_typedef, name: "lldiv_t", file: !3470, line: 80, baseType: !4031)
!4031 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !3470, line: 76, size: 128, flags: DIFlagTypePassByValue, elements: !4032, identifier: "_ZTS7lldiv_t")
!4032 = !{!4033, !4034}
!4033 = !DIDerivedType(tag: DW_TAG_member, name: "quot", scope: !4031, file: !3470, line: 78, baseType: !3660, size: 64)
!4034 = !DIDerivedType(tag: DW_TAG_member, name: "rem", scope: !4031, file: !3470, line: 79, baseType: !3660, size: 64, offset: 64)
!4035 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4036, file: !3899, line: 206)
!4036 = !DISubprogram(name: "_Exit", scope: !3470, file: !3470, line: 626, type: !3947, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!4037 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4038, file: !3899, line: 210)
!4038 = !DISubprogram(name: "llabs", scope: !3470, file: !3470, line: 841, type: !4039, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4039 = !DISubroutineType(types: !4040)
!4040 = !{!3660, !3660}
!4041 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4042, file: !3899, line: 216)
!4042 = !DISubprogram(name: "lldiv", scope: !3470, file: !3470, line: 855, type: !4043, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4043 = !DISubroutineType(types: !4044)
!4044 = !{!4030, !3660, !3660}
!4045 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4046, file: !3899, line: 227)
!4046 = !DISubprogram(name: "atoll", scope: !3470, file: !3470, line: 373, type: !4047, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4047 = !DISubroutineType(types: !4048)
!4048 = !{!3660, !336}
!4049 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4050, file: !3899, line: 228)
!4050 = !DISubprogram(name: "strtoll", scope: !3470, file: !3470, line: 200, type: !4051, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4051 = !DISubroutineType(types: !4052)
!4052 = !{!3660, !3843, !4006, !220}
!4053 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4054, file: !3899, line: 229)
!4054 = !DISubprogram(name: "strtoull", scope: !3470, file: !3470, line: 205, type: !4055, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4055 = !DISubroutineType(types: !4056)
!4056 = !{!4057, !3843, !4006, !220}
!4057 = !DIBasicType(name: "unsigned long long", size: 64, encoding: DW_ATE_unsigned)
!4058 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4059, file: !3899, line: 231)
!4059 = !DISubprogram(name: "strtof", scope: !3470, file: !3470, line: 123, type: !4060, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4060 = !DISubroutineType(types: !4061)
!4061 = !{!3538, !3843, !4006}
!4062 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4063, file: !3899, line: 232)
!4063 = !DISubprogram(name: "strtold", scope: !3470, file: !3470, line: 126, type: !4064, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4064 = !DISubroutineType(types: !4065)
!4065 = !{!3549, !3843, !4006}
!4066 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4030, file: !3899, line: 240)
!4067 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4036, file: !3899, line: 242)
!4068 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4038, file: !3899, line: 244)
!4069 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4070, file: !3899, line: 245)
!4070 = !DISubprogram(name: "div", linkageName: "_ZN9__gnu_cxx3divExx", scope: !5, file: !3899, line: 213, type: !4043, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4071 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4042, file: !3899, line: 246)
!4072 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4046, file: !3899, line: 248)
!4073 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4059, file: !3899, line: 249)
!4074 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4050, file: !3899, line: 250)
!4075 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4054, file: !3899, line: 251)
!4076 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4063, file: !3899, line: 252)
!4077 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4078, file: !4079, line: 57)
!4078 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "exception_ptr", scope: !4080, file: !4079, line: 79, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSNSt15__exception_ptr13exception_ptrE")
!4079 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/exception_ptr.h", directory: "", checksumkind: CSK_MD5, checksum: "25d44782b686509a9fc5c8aaa8066643")
!4080 = !DINamespace(name: "__exception_ptr", scope: !320)
!4081 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !4080, entity: !4082, file: !4079, line: 73)
!4082 = !DISubprogram(name: "rethrow_exception", linkageName: "_ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE", scope: !320, file: !4079, line: 69, type: !4083, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!4083 = !DISubroutineType(types: !4084)
!4084 = !{null, !4078}
!4085 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4086, file: !4099, line: 64)
!4086 = !DIDerivedType(tag: DW_TAG_typedef, name: "mbstate_t", file: !4087, line: 6, baseType: !4088)
!4087 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/mbstate_t.h", directory: "", checksumkind: CSK_MD5, checksum: "ba8742313715e20e434cf6ccb2db98e3")
!4088 = !DIDerivedType(tag: DW_TAG_typedef, name: "__mbstate_t", file: !4089, line: 21, baseType: !4090)
!4089 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h", directory: "", checksumkind: CSK_MD5, checksum: "82911a3e689448e3691ded3e0b471a55")
!4090 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !4089, line: 13, size: 64, flags: DIFlagTypePassByValue, elements: !4091, identifier: "_ZTS11__mbstate_t")
!4091 = !{!4092, !4093}
!4092 = !DIDerivedType(tag: DW_TAG_member, name: "__count", scope: !4090, file: !4089, line: 15, baseType: !220, size: 32)
!4093 = !DIDerivedType(tag: DW_TAG_member, name: "__value", scope: !4090, file: !4089, line: 20, baseType: !4094, size: 32, offset: 32)
!4094 = distinct !DICompositeType(tag: DW_TAG_union_type, scope: !4090, file: !4089, line: 16, size: 32, flags: DIFlagTypePassByValue, elements: !4095, identifier: "_ZTSN11__mbstate_tUt_E")
!4095 = !{!4096, !4097}
!4096 = !DIDerivedType(tag: DW_TAG_member, name: "__wch", scope: !4094, file: !4089, line: 18, baseType: !6, size: 32)
!4097 = !DIDerivedType(tag: DW_TAG_member, name: "__wchb", scope: !4094, file: !4089, line: 19, baseType: !4098, size: 32)
!4098 = !DICompositeType(tag: DW_TAG_array_type, baseType: !338, size: 32, elements: !3076)
!4099 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cwchar", directory: "")
!4100 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4101, file: !4099, line: 139)
!4101 = !DIDerivedType(tag: DW_TAG_typedef, name: "wint_t", file: !4102, line: 20, baseType: !6)
!4102 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/wint_t.h", directory: "", checksumkind: CSK_MD5, checksum: "aa31b53ef28dc23152ceb41e2763ded3")
!4103 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4104, file: !4099, line: 141)
!4104 = !DISubprogram(name: "btowc", scope: !4105, file: !4105, line: 318, type: !4106, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4105 = !DIFile(filename: "/usr/include/wchar.h", directory: "", checksumkind: CSK_MD5, checksum: "5c0512b032e303d7adfb2a47454ecb1c")
!4106 = !DISubroutineType(types: !4107)
!4107 = !{!4101, !220}
!4108 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4109, file: !4099, line: 142)
!4109 = !DISubprogram(name: "fgetwc", scope: !4105, file: !4105, line: 727, type: !4110, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4110 = !DISubroutineType(types: !4111)
!4111 = !{!4101, !4112}
!4112 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4113, size: 64)
!4113 = !DIDerivedType(tag: DW_TAG_typedef, name: "__FILE", file: !4114, line: 5, baseType: !4115)
!4114 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h", directory: "", checksumkind: CSK_MD5, checksum: "72a8fe90981f484acae7c6f3dfc5c2b7")
!4115 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_IO_FILE", file: !4116, line: 245, size: 1728, flags: DIFlagTypePassByValue, elements: !4117, identifier: "_ZTS8_IO_FILE")
!4116 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/libio.h", directory: "", checksumkind: CSK_MD5, checksum: "e2b53e448ab24b9cd2ba8684267b8131")
!4117 = !{!4118, !4119, !4120, !4121, !4122, !4123, !4124, !4125, !4126, !4127, !4128, !4129, !4130, !4133, !4135, !4136, !4137, !4139, !4141, !4143, !4147, !4150, !4152, !4153, !4154, !4155, !4156, !4157, !4158}
!4118 = !DIDerivedType(tag: DW_TAG_member, name: "_flags", scope: !4115, file: !4116, line: 246, baseType: !220, size: 32)
!4119 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_ptr", scope: !4115, file: !4116, line: 251, baseType: !1295, size: 64, offset: 64)
!4120 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_end", scope: !4115, file: !4116, line: 252, baseType: !1295, size: 64, offset: 128)
!4121 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_base", scope: !4115, file: !4116, line: 253, baseType: !1295, size: 64, offset: 192)
!4122 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_base", scope: !4115, file: !4116, line: 254, baseType: !1295, size: 64, offset: 256)
!4123 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_ptr", scope: !4115, file: !4116, line: 255, baseType: !1295, size: 64, offset: 320)
!4124 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_end", scope: !4115, file: !4116, line: 256, baseType: !1295, size: 64, offset: 384)
!4125 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_buf_base", scope: !4115, file: !4116, line: 257, baseType: !1295, size: 64, offset: 448)
!4126 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_buf_end", scope: !4115, file: !4116, line: 258, baseType: !1295, size: 64, offset: 512)
!4127 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_save_base", scope: !4115, file: !4116, line: 260, baseType: !1295, size: 64, offset: 576)
!4128 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_backup_base", scope: !4115, file: !4116, line: 261, baseType: !1295, size: 64, offset: 640)
!4129 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_save_end", scope: !4115, file: !4116, line: 262, baseType: !1295, size: 64, offset: 704)
!4130 = !DIDerivedType(tag: DW_TAG_member, name: "_markers", scope: !4115, file: !4116, line: 264, baseType: !4131, size: 64, offset: 768)
!4131 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4132, size: 64)
!4132 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_IO_marker", file: !4116, line: 160, size: 192, flags: DIFlagFwdDecl, identifier: "_ZTS10_IO_marker")
!4133 = !DIDerivedType(tag: DW_TAG_member, name: "_chain", scope: !4115, file: !4116, line: 266, baseType: !4134, size: 64, offset: 832)
!4134 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4115, size: 64)
!4135 = !DIDerivedType(tag: DW_TAG_member, name: "_fileno", scope: !4115, file: !4116, line: 268, baseType: !220, size: 32, offset: 896)
!4136 = !DIDerivedType(tag: DW_TAG_member, name: "_flags2", scope: !4115, file: !4116, line: 272, baseType: !220, size: 32, offset: 928)
!4137 = !DIDerivedType(tag: DW_TAG_member, name: "_old_offset", scope: !4115, file: !4116, line: 274, baseType: !4138, size: 64, offset: 960)
!4138 = !DIDerivedType(tag: DW_TAG_typedef, name: "__off_t", file: !2982, line: 140, baseType: !23)
!4139 = !DIDerivedType(tag: DW_TAG_member, name: "_cur_column", scope: !4115, file: !4116, line: 278, baseType: !4140, size: 16, offset: 1024)
!4140 = !DIBasicType(name: "unsigned short", size: 16, encoding: DW_ATE_unsigned)
!4141 = !DIDerivedType(tag: DW_TAG_member, name: "_vtable_offset", scope: !4115, file: !4116, line: 279, baseType: !4142, size: 8, offset: 1040)
!4142 = !DIBasicType(name: "signed char", size: 8, encoding: DW_ATE_signed_char)
!4143 = !DIDerivedType(tag: DW_TAG_member, name: "_shortbuf", scope: !4115, file: !4116, line: 280, baseType: !4144, size: 8, offset: 1048)
!4144 = !DICompositeType(tag: DW_TAG_array_type, baseType: !338, size: 8, elements: !4145)
!4145 = !{!4146}
!4146 = !DISubrange(count: 1)
!4147 = !DIDerivedType(tag: DW_TAG_member, name: "_lock", scope: !4115, file: !4116, line: 284, baseType: !4148, size: 64, offset: 1088)
!4148 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4149, size: 64)
!4149 = !DIDerivedType(tag: DW_TAG_typedef, name: "_IO_lock_t", file: !4116, line: 154, baseType: null)
!4150 = !DIDerivedType(tag: DW_TAG_member, name: "_offset", scope: !4115, file: !4116, line: 293, baseType: !4151, size: 64, offset: 1152)
!4151 = !DIDerivedType(tag: DW_TAG_typedef, name: "__off64_t", file: !2982, line: 141, baseType: !23)
!4152 = !DIDerivedType(tag: DW_TAG_member, name: "__pad1", scope: !4115, file: !4116, line: 301, baseType: !132, size: 64, offset: 1216)
!4153 = !DIDerivedType(tag: DW_TAG_member, name: "__pad2", scope: !4115, file: !4116, line: 302, baseType: !132, size: 64, offset: 1280)
!4154 = !DIDerivedType(tag: DW_TAG_member, name: "__pad3", scope: !4115, file: !4116, line: 303, baseType: !132, size: 64, offset: 1344)
!4155 = !DIDerivedType(tag: DW_TAG_member, name: "__pad4", scope: !4115, file: !4116, line: 304, baseType: !132, size: 64, offset: 1408)
!4156 = !DIDerivedType(tag: DW_TAG_member, name: "__pad5", scope: !4115, file: !4116, line: 306, baseType: !1076, size: 64, offset: 1472)
!4157 = !DIDerivedType(tag: DW_TAG_member, name: "_mode", scope: !4115, file: !4116, line: 307, baseType: !220, size: 32, offset: 1536)
!4158 = !DIDerivedType(tag: DW_TAG_member, name: "_unused2", scope: !4115, file: !4116, line: 309, baseType: !4159, size: 160, offset: 1568)
!4159 = !DICompositeType(tag: DW_TAG_array_type, baseType: !338, size: 160, elements: !4160)
!4160 = !{!4161}
!4161 = !DISubrange(count: 20)
!4162 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4163, file: !4099, line: 143)
!4163 = !DISubprogram(name: "fgetws", scope: !4105, file: !4105, line: 756, type: !4164, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4164 = !DISubroutineType(types: !4165)
!4165 = !{!3978, !3977, !220, !4166}
!4166 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4112)
!4167 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4168, file: !4099, line: 144)
!4168 = !DISubprogram(name: "fputwc", scope: !4105, file: !4105, line: 741, type: !4169, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4169 = !DISubroutineType(types: !4170)
!4170 = !{!4101, !3979, !4112}
!4171 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4172, file: !4099, line: 145)
!4172 = !DISubprogram(name: "fputws", scope: !4105, file: !4105, line: 763, type: !4173, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4173 = !DISubroutineType(types: !4174)
!4174 = !{!220, !4022, !4166}
!4175 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4176, file: !4099, line: 146)
!4176 = !DISubprogram(name: "fwide", scope: !4105, file: !4105, line: 573, type: !4177, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4177 = !DISubroutineType(types: !4178)
!4178 = !{!220, !4112, !220}
!4179 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4180, file: !4099, line: 147)
!4180 = !DISubprogram(name: "fwprintf", scope: !4105, file: !4105, line: 580, type: !4181, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4181 = !DISubroutineType(types: !4182)
!4182 = !{!220, !4166, !4022, null}
!4183 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4184, file: !4099, line: 148)
!4184 = !DISubprogram(name: "fwscanf", scope: !4105, file: !4105, line: 621, type: !4181, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4185 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4186, file: !4099, line: 149)
!4186 = !DISubprogram(name: "getwc", scope: !4105, file: !4105, line: 728, type: !4110, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4187 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4188, file: !4099, line: 150)
!4188 = !DISubprogram(name: "getwchar", scope: !4105, file: !4105, line: 734, type: !4189, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4189 = !DISubroutineType(types: !4190)
!4190 = !{!4101}
!4191 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4192, file: !4099, line: 151)
!4192 = !DISubprogram(name: "mbrlen", scope: !4105, file: !4105, line: 329, type: !4193, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4193 = !DISubroutineType(types: !4194)
!4194 = !{!1076, !3843, !1076, !4195}
!4195 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4196)
!4196 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4086, size: 64)
!4197 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4198, file: !4099, line: 152)
!4198 = !DISubprogram(name: "mbrtowc", scope: !4105, file: !4105, line: 296, type: !4199, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4199 = !DISubroutineType(types: !4200)
!4200 = !{!1076, !3977, !3843, !1076, !4195}
!4201 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4202, file: !4099, line: 153)
!4202 = !DISubprogram(name: "mbsinit", scope: !4105, file: !4105, line: 292, type: !4203, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4203 = !DISubroutineType(types: !4204)
!4204 = !{!220, !4205}
!4205 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4206, size: 64)
!4206 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4086)
!4207 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4208, file: !4099, line: 154)
!4208 = !DISubprogram(name: "mbsrtowcs", scope: !4105, file: !4105, line: 337, type: !4209, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4209 = !DISubroutineType(types: !4210)
!4210 = !{!1076, !3977, !4211, !1076, !4195}
!4211 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4212)
!4212 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !336, size: 64)
!4213 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4214, file: !4099, line: 155)
!4214 = !DISubprogram(name: "putwc", scope: !4105, file: !4105, line: 742, type: !4169, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4215 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4216, file: !4099, line: 156)
!4216 = !DISubprogram(name: "putwchar", scope: !4105, file: !4105, line: 748, type: !4217, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4217 = !DISubroutineType(types: !4218)
!4218 = !{!4101, !3979}
!4219 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4220, file: !4099, line: 158)
!4220 = !DISubprogram(name: "swprintf", scope: !4105, file: !4105, line: 590, type: !4221, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4221 = !DISubroutineType(types: !4222)
!4222 = !{!220, !3977, !1076, !4022, null}
!4223 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4224, file: !4099, line: 160)
!4224 = !DISubprogram(name: "swscanf", scope: !4105, file: !4105, line: 631, type: !4225, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4225 = !DISubroutineType(types: !4226)
!4226 = !{!220, !4022, !4022, null}
!4227 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4228, file: !4099, line: 161)
!4228 = !DISubprogram(name: "ungetwc", scope: !4105, file: !4105, line: 771, type: !4229, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4229 = !DISubroutineType(types: !4230)
!4230 = !{!4101, !4101, !4112}
!4231 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4232, file: !4099, line: 162)
!4232 = !DISubprogram(name: "vfwprintf", scope: !4105, file: !4105, line: 598, type: !4233, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4233 = !DISubroutineType(types: !4234)
!4234 = !{!220, !4166, !4022, !4235}
!4235 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4236, size: 64)
!4236 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__va_list_tag", size: 192, flags: DIFlagTypePassByValue, elements: !4237, identifier: "_ZTS13__va_list_tag")
!4237 = !{!4238, !4240, !4241, !4242}
!4238 = !DIDerivedType(tag: DW_TAG_member, name: "gp_offset", scope: !4236, file: !4239, baseType: !6, size: 32)
!4239 = !DIFile(filename: "llvm34/lib/CodeGen/SlotIndexes.cpp", directory: "/fast/fs")
!4240 = !DIDerivedType(tag: DW_TAG_member, name: "fp_offset", scope: !4236, file: !4239, baseType: !6, size: 32, offset: 32)
!4241 = !DIDerivedType(tag: DW_TAG_member, name: "overflow_arg_area", scope: !4236, file: !4239, baseType: !132, size: 64, offset: 64)
!4242 = !DIDerivedType(tag: DW_TAG_member, name: "reg_save_area", scope: !4236, file: !4239, baseType: !132, size: 64, offset: 128)
!4243 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4244, file: !4099, line: 164)
!4244 = !DISubprogram(name: "vfwscanf", scope: !4105, file: !4105, line: 673, type: !4233, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4245 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4246, file: !4099, line: 167)
!4246 = !DISubprogram(name: "vswprintf", scope: !4105, file: !4105, line: 611, type: !4247, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4247 = !DISubroutineType(types: !4248)
!4248 = !{!220, !3977, !1076, !4022, !4235}
!4249 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4250, file: !4099, line: 170)
!4250 = !DISubprogram(name: "vswscanf", scope: !4105, file: !4105, line: 685, type: !4251, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4251 = !DISubroutineType(types: !4252)
!4252 = !{!220, !4022, !4022, !4235}
!4253 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4254, file: !4099, line: 172)
!4254 = !DISubprogram(name: "vwprintf", scope: !4105, file: !4105, line: 606, type: !4255, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4255 = !DISubroutineType(types: !4256)
!4256 = !{!220, !4022, !4235}
!4257 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4258, file: !4099, line: 174)
!4258 = !DISubprogram(name: "vwscanf", scope: !4105, file: !4105, line: 681, type: !4255, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4259 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4260, file: !4099, line: 176)
!4260 = !DISubprogram(name: "wcrtomb", scope: !4105, file: !4105, line: 301, type: !4261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4261 = !DISubroutineType(types: !4262)
!4262 = !{!1076, !3842, !3979, !4195}
!4263 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4264, file: !4099, line: 177)
!4264 = !DISubprogram(name: "wcscat", scope: !4105, file: !4105, line: 97, type: !4265, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4265 = !DISubroutineType(types: !4266)
!4266 = !{!3978, !3977, !4022}
!4267 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4268, file: !4099, line: 178)
!4268 = !DISubprogram(name: "wcscmp", scope: !4105, file: !4105, line: 106, type: !4269, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4269 = !DISubroutineType(types: !4270)
!4270 = !{!220, !4023, !4023}
!4271 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4272, file: !4099, line: 179)
!4272 = !DISubprogram(name: "wcscoll", scope: !4105, file: !4105, line: 131, type: !4269, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4273 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4274, file: !4099, line: 180)
!4274 = !DISubprogram(name: "wcscpy", scope: !4105, file: !4105, line: 87, type: !4265, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4275 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4276, file: !4099, line: 181)
!4276 = !DISubprogram(name: "wcscspn", scope: !4105, file: !4105, line: 187, type: !4277, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4277 = !DISubroutineType(types: !4278)
!4278 = !{!1076, !4023, !4023}
!4279 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4280, file: !4099, line: 182)
!4280 = !DISubprogram(name: "wcsftime", scope: !4105, file: !4105, line: 835, type: !4281, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4281 = !DISubroutineType(types: !4282)
!4282 = !{!1076, !3977, !1076, !4022, !4283}
!4283 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4284)
!4284 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4285, size: 64)
!4285 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4286)
!4286 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "tm", file: !4105, line: 83, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTS2tm")
!4287 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4288, file: !4099, line: 183)
!4288 = !DISubprogram(name: "wcslen", scope: !4105, file: !4105, line: 222, type: !4289, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4289 = !DISubroutineType(types: !4290)
!4290 = !{!1076, !4023}
!4291 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4292, file: !4099, line: 184)
!4292 = !DISubprogram(name: "wcsncat", scope: !4105, file: !4105, line: 101, type: !4293, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4293 = !DISubroutineType(types: !4294)
!4294 = !{!3978, !3977, !4022, !1076}
!4295 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4296, file: !4099, line: 185)
!4296 = !DISubprogram(name: "wcsncmp", scope: !4105, file: !4105, line: 109, type: !4297, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4297 = !DISubroutineType(types: !4298)
!4298 = !{!220, !4023, !4023, !1076}
!4299 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4300, file: !4099, line: 186)
!4300 = !DISubprogram(name: "wcsncpy", scope: !4105, file: !4105, line: 92, type: !4293, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4301 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4302, file: !4099, line: 187)
!4302 = !DISubprogram(name: "wcsrtombs", scope: !4105, file: !4105, line: 343, type: !4303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4303 = !DISubroutineType(types: !4304)
!4304 = !{!1076, !3842, !4305, !1076, !4195}
!4305 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4306)
!4306 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4023, size: 64)
!4307 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4308, file: !4099, line: 188)
!4308 = !DISubprogram(name: "wcsspn", scope: !4105, file: !4105, line: 191, type: !4277, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4309 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4310, file: !4099, line: 189)
!4310 = !DISubprogram(name: "wcstod", scope: !4105, file: !4105, line: 377, type: !4311, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4311 = !DISubroutineType(types: !4312)
!4312 = !{!3479, !4022, !4313}
!4313 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4314)
!4314 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3978, size: 64)
!4315 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4316, file: !4099, line: 191)
!4316 = !DISubprogram(name: "wcstof", scope: !4105, file: !4105, line: 382, type: !4317, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4317 = !DISubroutineType(types: !4318)
!4318 = !{!3538, !4022, !4313}
!4319 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4320, file: !4099, line: 193)
!4320 = !DISubprogram(name: "wcstok", scope: !4105, file: !4105, line: 217, type: !4321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4321 = !DISubroutineType(types: !4322)
!4322 = !{!3978, !3977, !4022, !4313}
!4323 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4324, file: !4099, line: 194)
!4324 = !DISubprogram(name: "wcstol", scope: !4105, file: !4105, line: 428, type: !4325, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4325 = !DISubroutineType(types: !4326)
!4326 = !{!23, !4022, !4313, !220}
!4327 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4328, file: !4099, line: 195)
!4328 = !DISubprogram(name: "wcstoul", scope: !4105, file: !4105, line: 433, type: !4329, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4329 = !DISubroutineType(types: !4330)
!4330 = !{!283, !4022, !4313, !220}
!4331 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4332, file: !4099, line: 196)
!4332 = !DISubprogram(name: "wcsxfrm", scope: !4105, file: !4105, line: 135, type: !4333, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4333 = !DISubroutineType(types: !4334)
!4334 = !{!1076, !3977, !4022, !1076}
!4335 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4336, file: !4099, line: 197)
!4336 = !DISubprogram(name: "wctob", scope: !4105, file: !4105, line: 324, type: !4337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4337 = !DISubroutineType(types: !4338)
!4338 = !{!220, !4101}
!4339 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4340, file: !4099, line: 198)
!4340 = !DISubprogram(name: "wmemcmp", scope: !4105, file: !4105, line: 258, type: !4297, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4341 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4342, file: !4099, line: 199)
!4342 = !DISubprogram(name: "wmemcpy", scope: !4105, file: !4105, line: 262, type: !4293, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4343 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4344, file: !4099, line: 200)
!4344 = !DISubprogram(name: "wmemmove", scope: !4105, file: !4105, line: 267, type: !4345, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4345 = !DISubroutineType(types: !4346)
!4346 = !{!3978, !3978, !4023, !1076}
!4347 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4348, file: !4099, line: 201)
!4348 = !DISubprogram(name: "wmemset", scope: !4105, file: !4105, line: 271, type: !4349, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4349 = !DISubroutineType(types: !4350)
!4350 = !{!3978, !3978, !3979, !1076}
!4351 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4352, file: !4099, line: 202)
!4352 = !DISubprogram(name: "wprintf", scope: !4105, file: !4105, line: 587, type: !4353, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4353 = !DISubroutineType(types: !4354)
!4354 = !{!220, !4022, null}
!4355 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4356, file: !4099, line: 203)
!4356 = !DISubprogram(name: "wscanf", scope: !4105, file: !4105, line: 628, type: !4353, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4357 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4358, file: !4099, line: 204)
!4358 = !DISubprogram(name: "wcschr", scope: !4105, file: !4105, line: 164, type: !4359, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4359 = !DISubroutineType(types: !4360)
!4360 = !{!3978, !4023, !3979}
!4361 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4362, file: !4099, line: 205)
!4362 = !DISubprogram(name: "wcspbrk", scope: !4105, file: !4105, line: 201, type: !4363, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4363 = !DISubroutineType(types: !4364)
!4364 = !{!3978, !4023, !4023}
!4365 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4366, file: !4099, line: 206)
!4366 = !DISubprogram(name: "wcsrchr", scope: !4105, file: !4105, line: 174, type: !4359, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4367 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4368, file: !4099, line: 207)
!4368 = !DISubprogram(name: "wcsstr", scope: !4105, file: !4105, line: 212, type: !4363, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4369 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4370, file: !4099, line: 208)
!4370 = !DISubprogram(name: "wmemchr", scope: !4105, file: !4105, line: 253, type: !4371, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4371 = !DISubroutineType(types: !4372)
!4372 = !{!3978, !4023, !3979, !1076}
!4373 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4374, file: !4099, line: 248)
!4374 = !DISubprogram(name: "wcstold", scope: !4105, file: !4105, line: 384, type: !4375, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4375 = !DISubroutineType(types: !4376)
!4376 = !{!3549, !4022, !4313}
!4377 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4378, file: !4099, line: 257)
!4378 = !DISubprogram(name: "wcstoll", scope: !4105, file: !4105, line: 441, type: !4379, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4379 = !DISubroutineType(types: !4380)
!4380 = !{!3660, !4022, !4313, !220}
!4381 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4382, file: !4099, line: 258)
!4382 = !DISubprogram(name: "wcstoull", scope: !4105, file: !4105, line: 448, type: !4383, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4383 = !DISubroutineType(types: !4384)
!4384 = !{!4057, !4022, !4313, !220}
!4385 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4374, file: !4099, line: 264)
!4386 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4378, file: !4099, line: 265)
!4387 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4382, file: !4099, line: 266)
!4388 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4316, file: !4099, line: 280)
!4389 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4244, file: !4099, line: 283)
!4390 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4250, file: !4099, line: 286)
!4391 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4258, file: !4099, line: 289)
!4392 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4374, file: !4099, line: 293)
!4393 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4378, file: !4099, line: 294)
!4394 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4382, file: !4099, line: 295)
!4395 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4396, file: !4399, line: 48)
!4396 = !DIDerivedType(tag: DW_TAG_typedef, name: "int8_t", file: !4397, line: 24, baseType: !4398)
!4397 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h", directory: "", checksumkind: CSK_MD5, checksum: "457547631e07cd24d9a14c8410e28e57")
!4398 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int8_t", file: !2982, line: 36, baseType: !4142)
!4399 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdint", directory: "")
!4400 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4401, file: !4399, line: 49)
!4401 = !DIDerivedType(tag: DW_TAG_typedef, name: "int16_t", file: !4397, line: 25, baseType: !4402)
!4402 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int16_t", file: !2982, line: 38, baseType: !4403)
!4403 = !DIBasicType(name: "short", size: 16, encoding: DW_ATE_signed)
!4404 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4405, file: !4399, line: 50)
!4405 = !DIDerivedType(tag: DW_TAG_typedef, name: "int32_t", file: !4397, line: 26, baseType: !4406)
!4406 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int32_t", file: !2982, line: 40, baseType: !220)
!4407 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4408, file: !4399, line: 51)
!4408 = !DIDerivedType(tag: DW_TAG_typedef, name: "int64_t", file: !4397, line: 27, baseType: !4409)
!4409 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int64_t", file: !2982, line: 43, baseType: !23)
!4410 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4411, file: !4399, line: 53)
!4411 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast8_t", file: !22, line: 68, baseType: !4142)
!4412 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4413, file: !4399, line: 54)
!4413 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast16_t", file: !22, line: 70, baseType: !23)
!4414 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4415, file: !4399, line: 55)
!4415 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast32_t", file: !22, line: 71, baseType: !23)
!4416 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4417, file: !4399, line: 56)
!4417 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast64_t", file: !22, line: 72, baseType: !23)
!4418 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4419, file: !4399, line: 58)
!4419 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least8_t", file: !22, line: 43, baseType: !4142)
!4420 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4421, file: !4399, line: 59)
!4421 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least16_t", file: !22, line: 44, baseType: !4403)
!4422 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4423, file: !4399, line: 60)
!4423 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least32_t", file: !22, line: 45, baseType: !220)
!4424 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4425, file: !4399, line: 61)
!4425 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least64_t", file: !22, line: 47, baseType: !23)
!4426 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4427, file: !4399, line: 63)
!4427 = !DIDerivedType(tag: DW_TAG_typedef, name: "intmax_t", file: !22, line: 111, baseType: !4428)
!4428 = !DIDerivedType(tag: DW_TAG_typedef, name: "__intmax_t", file: !2982, line: 61, baseType: !23)
!4429 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !21, file: !4399, line: 64)
!4430 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4431, file: !4399, line: 66)
!4431 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint8_t", file: !2980, line: 24, baseType: !4432)
!4432 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint8_t", file: !2982, line: 37, baseType: !4433)
!4433 = !DIBasicType(name: "unsigned char", size: 8, encoding: DW_ATE_unsigned_char)
!4434 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4435, file: !4399, line: 67)
!4435 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint16_t", file: !2980, line: 25, baseType: !4436)
!4436 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint16_t", file: !2982, line: 39, baseType: !4140)
!4437 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !2979, file: !4399, line: 68)
!4438 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4439, file: !4399, line: 69)
!4439 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint64_t", file: !2980, line: 27, baseType: !4440)
!4440 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint64_t", file: !2982, line: 44, baseType: !283)
!4441 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4442, file: !4399, line: 71)
!4442 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast8_t", file: !22, line: 81, baseType: !4433)
!4443 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4444, file: !4399, line: 72)
!4444 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast16_t", file: !22, line: 83, baseType: !283)
!4445 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4446, file: !4399, line: 73)
!4446 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast32_t", file: !22, line: 84, baseType: !283)
!4447 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4448, file: !4399, line: 74)
!4448 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast64_t", file: !22, line: 85, baseType: !283)
!4449 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4450, file: !4399, line: 76)
!4450 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least8_t", file: !22, line: 54, baseType: !4433)
!4451 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4452, file: !4399, line: 77)
!4452 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least16_t", file: !22, line: 55, baseType: !4140)
!4453 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4454, file: !4399, line: 78)
!4454 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least32_t", file: !22, line: 56, baseType: !6)
!4455 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4456, file: !4399, line: 79)
!4456 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least64_t", file: !22, line: 58, baseType: !283)
!4457 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4458, file: !4399, line: 81)
!4458 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintmax_t", file: !22, line: 112, baseType: !4459)
!4459 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uintmax_t", file: !2982, line: 62, baseType: !283)
!4460 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !282, file: !4399, line: 82)
!4461 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4462, file: !4464, line: 53)
!4462 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "lconv", file: !4463, line: 51, size: 768, flags: DIFlagFwdDecl, identifier: "_ZTS5lconv")
!4463 = !DIFile(filename: "/usr/include/locale.h", directory: "", checksumkind: CSK_MD5, checksum: "0595275e3f5b502d28f7cd61a0dff888")
!4464 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/clocale", directory: "")
!4465 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4466, file: !4464, line: 54)
!4466 = !DISubprogram(name: "setlocale", scope: !4463, file: !4463, line: 122, type: !4467, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4467 = !DISubroutineType(types: !4468)
!4468 = !{!1295, !220, !336}
!4469 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4470, file: !4464, line: 55)
!4470 = !DISubprogram(name: "localeconv", scope: !4463, file: !4463, line: 125, type: !4471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4471 = !DISubroutineType(types: !4472)
!4472 = !{!4473}
!4473 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4462, size: 64)
!4474 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4475, file: !4477, line: 64)
!4475 = !DISubprogram(name: "isalnum", scope: !4476, file: !4476, line: 108, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4476 = !DIFile(filename: "/usr/include/ctype.h", directory: "", checksumkind: CSK_MD5, checksum: "c67c809b09ef8ea9c273687bc20a7fd3")
!4477 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cctype", directory: "")
!4478 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4479, file: !4477, line: 65)
!4479 = !DISubprogram(name: "isalpha", scope: !4476, file: !4476, line: 109, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4480 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4481, file: !4477, line: 66)
!4481 = !DISubprogram(name: "iscntrl", scope: !4476, file: !4476, line: 110, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4482 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4483, file: !4477, line: 67)
!4483 = !DISubprogram(name: "isdigit", scope: !4476, file: !4476, line: 111, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4484 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4485, file: !4477, line: 68)
!4485 = !DISubprogram(name: "isgraph", scope: !4476, file: !4476, line: 113, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4486 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4487, file: !4477, line: 69)
!4487 = !DISubprogram(name: "islower", scope: !4476, file: !4476, line: 112, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4488 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4489, file: !4477, line: 70)
!4489 = !DISubprogram(name: "isprint", scope: !4476, file: !4476, line: 114, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4490 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4491, file: !4477, line: 71)
!4491 = !DISubprogram(name: "ispunct", scope: !4476, file: !4476, line: 115, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4492 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4493, file: !4477, line: 72)
!4493 = !DISubprogram(name: "isspace", scope: !4476, file: !4476, line: 116, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4494 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4495, file: !4477, line: 73)
!4495 = !DISubprogram(name: "isupper", scope: !4476, file: !4476, line: 117, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4496 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4497, file: !4477, line: 74)
!4497 = !DISubprogram(name: "isxdigit", scope: !4476, file: !4476, line: 118, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4498 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4499, file: !4477, line: 75)
!4499 = !DISubprogram(name: "tolower", scope: !4476, file: !4476, line: 122, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4500 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4501, file: !4477, line: 76)
!4501 = !DISubprogram(name: "toupper", scope: !4476, file: !4476, line: 125, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4502 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4503, file: !4477, line: 87)
!4503 = !DISubprogram(name: "isblank", scope: !4476, file: !4476, line: 130, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4504 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !413, file: !382, line: 44)
!4505 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !642, file: !382, line: 45)
!4506 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4507, file: !4509, line: 98)
!4507 = !DIDerivedType(tag: DW_TAG_typedef, name: "FILE", file: !4508, line: 7, baseType: !4115)
!4508 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/FILE.h", directory: "", checksumkind: CSK_MD5, checksum: "571f9fb6223c42439075fdde11a0de5d")
!4509 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdio", directory: "")
!4510 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4511, file: !4509, line: 99)
!4511 = !DIDerivedType(tag: DW_TAG_typedef, name: "fpos_t", file: !4512, line: 78, baseType: !4513)
!4512 = !DIFile(filename: "/usr/include/stdio.h", directory: "", checksumkind: CSK_MD5, checksum: "2ab51d960d7d0ed84798d1688a6988b0")
!4513 = !DIDerivedType(tag: DW_TAG_typedef, name: "_G_fpos_t", file: !4514, line: 30, baseType: !4515)
!4514 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/_G_config.h", directory: "", checksumkind: CSK_MD5, checksum: "f78480ecfcae11a7bda5a6b08034c1fb")
!4515 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !4514, line: 26, size: 128, flags: DIFlagFwdDecl, identifier: "_ZTS9_G_fpos_t")
!4516 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4517, file: !4509, line: 101)
!4517 = !DISubprogram(name: "clearerr", scope: !4512, file: !4512, line: 757, type: !4518, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4518 = !DISubroutineType(types: !4519)
!4519 = !{null, !4520}
!4520 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4507, size: 64)
!4521 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4522, file: !4509, line: 102)
!4522 = !DISubprogram(name: "fclose", scope: !4512, file: !4512, line: 199, type: !4523, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4523 = !DISubroutineType(types: !4524)
!4524 = !{!220, !4520}
!4525 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4526, file: !4509, line: 103)
!4526 = !DISubprogram(name: "feof", scope: !4512, file: !4512, line: 759, type: !4523, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4527 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4528, file: !4509, line: 104)
!4528 = !DISubprogram(name: "ferror", scope: !4512, file: !4512, line: 761, type: !4523, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4529 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4530, file: !4509, line: 105)
!4530 = !DISubprogram(name: "fflush", scope: !4512, file: !4512, line: 204, type: !4523, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4531 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4532, file: !4509, line: 106)
!4532 = !DISubprogram(name: "fgetc", scope: !4512, file: !4512, line: 477, type: !4523, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4533 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4534, file: !4509, line: 107)
!4534 = !DISubprogram(name: "fgetpos", scope: !4512, file: !4512, line: 731, type: !4535, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4535 = !DISubroutineType(types: !4536)
!4536 = !{!220, !4537, !4538}
!4537 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4520)
!4538 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4539)
!4539 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4511, size: 64)
!4540 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4541, file: !4509, line: 108)
!4541 = !DISubprogram(name: "fgets", scope: !4512, file: !4512, line: 564, type: !4542, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4542 = !DISubroutineType(types: !4543)
!4543 = !{!1295, !3842, !220, !4537}
!4544 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4545, file: !4509, line: 109)
!4545 = !DISubprogram(name: "fopen", scope: !4512, file: !4512, line: 232, type: !4546, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4546 = !DISubroutineType(types: !4547)
!4547 = !{!4520, !3843, !3843}
!4548 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4549, file: !4509, line: 110)
!4549 = !DISubprogram(name: "fprintf", scope: !4512, file: !4512, line: 312, type: !4550, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4550 = !DISubroutineType(types: !4551)
!4551 = !{!220, !4537, !3843, null}
!4552 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4553, file: !4509, line: 111)
!4553 = !DISubprogram(name: "fputc", scope: !4512, file: !4512, line: 517, type: !4554, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4554 = !DISubroutineType(types: !4555)
!4555 = !{!220, !220, !4520}
!4556 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4557, file: !4509, line: 112)
!4557 = !DISubprogram(name: "fputs", scope: !4512, file: !4512, line: 626, type: !4558, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4558 = !DISubroutineType(types: !4559)
!4559 = !{!220, !3843, !4537}
!4560 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4561, file: !4509, line: 113)
!4561 = !DISubprogram(name: "fread", scope: !4512, file: !4512, line: 646, type: !4562, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4562 = !DISubroutineType(types: !4563)
!4563 = !{!1076, !3828, !1076, !1076, !4537}
!4564 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4565, file: !4509, line: 114)
!4565 = !DISubprogram(name: "freopen", scope: !4512, file: !4512, line: 238, type: !4566, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4566 = !DISubroutineType(types: !4567)
!4567 = !{!4520, !3843, !3843, !4537}
!4568 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4569, file: !4509, line: 115)
!4569 = !DISubprogram(name: "fscanf", scope: !4512, file: !4512, line: 377, type: !4550, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4570 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4571, file: !4509, line: 116)
!4571 = !DISubprogram(name: "fseek", scope: !4512, file: !4512, line: 684, type: !4572, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4572 = !DISubroutineType(types: !4573)
!4573 = !{!220, !4520, !23, !220}
!4574 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4575, file: !4509, line: 117)
!4575 = !DISubprogram(name: "fsetpos", scope: !4512, file: !4512, line: 736, type: !4576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4576 = !DISubroutineType(types: !4577)
!4577 = !{!220, !4520, !4578}
!4578 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4579, size: 64)
!4579 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4511)
!4580 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4581, file: !4509, line: 118)
!4581 = !DISubprogram(name: "ftell", scope: !4512, file: !4512, line: 689, type: !4582, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4582 = !DISubroutineType(types: !4583)
!4583 = !{!23, !4520}
!4584 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4585, file: !4509, line: 119)
!4585 = !DISubprogram(name: "fwrite", scope: !4512, file: !4512, line: 652, type: !4586, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4586 = !DISubroutineType(types: !4587)
!4587 = !{!1076, !3829, !1076, !1076, !4537}
!4588 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4589, file: !4509, line: 120)
!4589 = !DISubprogram(name: "getc", scope: !4512, file: !4512, line: 478, type: !4523, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4590 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4591, file: !4509, line: 121)
!4591 = !DISubprogram(name: "getchar", scope: !4592, file: !4592, line: 44, type: !3992, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4592 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdio.h", directory: "", checksumkind: CSK_MD5, checksum: "ae874477a6b090849220f12acdd69dc3")
!4593 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4594, file: !4509, line: 126)
!4594 = !DISubprogram(name: "perror", scope: !4512, file: !4512, line: 775, type: !4595, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4595 = !DISubroutineType(types: !4596)
!4596 = !{null, !336}
!4597 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4598, file: !4509, line: 127)
!4598 = !DISubprogram(name: "printf", scope: !4512, file: !4512, line: 318, type: !4599, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4599 = !DISubroutineType(types: !4600)
!4600 = !{!220, !3843, null}
!4601 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4602, file: !4509, line: 128)
!4602 = !DISubprogram(name: "putc", scope: !4512, file: !4512, line: 518, type: !4554, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4603 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4604, file: !4509, line: 129)
!4604 = !DISubprogram(name: "putchar", scope: !4592, file: !4592, line: 79, type: !3471, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4605 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4606, file: !4509, line: 130)
!4606 = !DISubprogram(name: "puts", scope: !4512, file: !4512, line: 632, type: !3922, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4607 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4608, file: !4509, line: 131)
!4608 = !DISubprogram(name: "remove", scope: !4512, file: !4512, line: 144, type: !3922, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4609 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4610, file: !4509, line: 132)
!4610 = !DISubprogram(name: "rename", scope: !4512, file: !4512, line: 146, type: !3846, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4611 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4612, file: !4509, line: 133)
!4612 = !DISubprogram(name: "rewind", scope: !4512, file: !4512, line: 694, type: !4518, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4613 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4614, file: !4509, line: 134)
!4614 = !DISubprogram(name: "scanf", scope: !4512, file: !4512, line: 383, type: !4599, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4615 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4616, file: !4509, line: 135)
!4616 = !DISubprogram(name: "setbuf", scope: !4512, file: !4512, line: 290, type: !4617, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4617 = !DISubroutineType(types: !4618)
!4618 = !{null, !4537, !3842}
!4619 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4620, file: !4509, line: 136)
!4620 = !DISubprogram(name: "setvbuf", scope: !4512, file: !4512, line: 294, type: !4621, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4621 = !DISubroutineType(types: !4622)
!4622 = !{!220, !4537, !3842, !220, !1076}
!4623 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4624, file: !4509, line: 137)
!4624 = !DISubprogram(name: "sprintf", scope: !4512, file: !4512, line: 320, type: !4625, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4625 = !DISubroutineType(types: !4626)
!4626 = !{!220, !3842, !3843, null}
!4627 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4628, file: !4509, line: 138)
!4628 = !DISubprogram(name: "sscanf", scope: !4512, file: !4512, line: 385, type: !4629, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4629 = !DISubroutineType(types: !4630)
!4630 = !{!220, !3843, !3843, null}
!4631 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4632, file: !4509, line: 139)
!4632 = !DISubprogram(name: "tmpfile", scope: !4512, file: !4512, line: 159, type: !4633, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4633 = !DISubroutineType(types: !4634)
!4634 = !{!4520}
!4635 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4636, file: !4509, line: 141)
!4636 = !DISubprogram(name: "tmpnam", scope: !4512, file: !4512, line: 173, type: !4637, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4637 = !DISubroutineType(types: !4638)
!4638 = !{!1295, !1295}
!4639 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4640, file: !4509, line: 143)
!4640 = !DISubprogram(name: "ungetc", scope: !4512, file: !4512, line: 639, type: !4554, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4641 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4642, file: !4509, line: 144)
!4642 = !DISubprogram(name: "vfprintf", scope: !4512, file: !4512, line: 327, type: !4643, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4643 = !DISubroutineType(types: !4644)
!4644 = !{!220, !4537, !3843, !4235}
!4645 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4646, file: !4509, line: 145)
!4646 = !DISubprogram(name: "vprintf", scope: !4592, file: !4592, line: 36, type: !4647, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4647 = !DISubroutineType(types: !4648)
!4648 = !{!220, !3843, !4235}
!4649 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4650, file: !4509, line: 146)
!4650 = !DISubprogram(name: "vsprintf", scope: !4512, file: !4512, line: 335, type: !4651, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4651 = !DISubroutineType(types: !4652)
!4652 = !{!220, !3842, !3843, !4235}
!4653 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4654, file: !4509, line: 175)
!4654 = !DISubprogram(name: "snprintf", scope: !4512, file: !4512, line: 340, type: !4655, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4655 = !DISubroutineType(types: !4656)
!4656 = !{!220, !3842, !1076, !3843, null}
!4657 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4658, file: !4509, line: 176)
!4658 = !DISubprogram(name: "vfscanf", scope: !4512, file: !4512, line: 420, type: !4643, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4659 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4660, file: !4509, line: 177)
!4660 = !DISubprogram(name: "vscanf", scope: !4512, file: !4512, line: 428, type: !4647, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4661 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4662, file: !4509, line: 178)
!4662 = !DISubprogram(name: "vsnprintf", scope: !4512, file: !4512, line: 344, type: !4663, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4663 = !DISubroutineType(types: !4664)
!4664 = !{!220, !3842, !1076, !3843, !4235}
!4665 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4666, file: !4509, line: 179)
!4666 = !DISubprogram(name: "vsscanf", scope: !4512, file: !4512, line: 432, type: !4667, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4667 = !DISubroutineType(types: !4668)
!4668 = !{!220, !3843, !3843, !4235}
!4669 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4654, file: !4509, line: 185)
!4670 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4658, file: !4509, line: 186)
!4671 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4660, file: !4509, line: 187)
!4672 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4662, file: !4509, line: 188)
!4673 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4666, file: !4509, line: 189)
!4674 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4675, file: !4679, line: 82)
!4675 = !DIDerivedType(tag: DW_TAG_typedef, name: "wctrans_t", file: !4676, line: 48, baseType: !4677)
!4676 = !DIFile(filename: "/usr/include/wctype.h", directory: "", checksumkind: CSK_MD5, checksum: "760693b7fbeea3d686e1f29058fc2257")
!4677 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4678, size: 64)
!4678 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4406)
!4679 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cwctype", directory: "")
!4680 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4681, file: !4679, line: 83)
!4681 = !DIDerivedType(tag: DW_TAG_typedef, name: "wctype_t", file: !4682, line: 38, baseType: !283)
!4682 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/wctype-wchar.h", directory: "", checksumkind: CSK_MD5, checksum: "45eef9c3aa1d99faffa3945ed9be039a")
!4683 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4101, file: !4679, line: 84)
!4684 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4685, file: !4679, line: 86)
!4685 = !DISubprogram(name: "iswalnum", scope: !4682, file: !4682, line: 95, type: !4337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4686 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4687, file: !4679, line: 87)
!4687 = !DISubprogram(name: "iswalpha", scope: !4682, file: !4682, line: 101, type: !4337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4688 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4689, file: !4679, line: 89)
!4689 = !DISubprogram(name: "iswblank", scope: !4682, file: !4682, line: 146, type: !4337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4690 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4691, file: !4679, line: 91)
!4691 = !DISubprogram(name: "iswcntrl", scope: !4682, file: !4682, line: 104, type: !4337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4692 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4693, file: !4679, line: 92)
!4693 = !DISubprogram(name: "iswctype", scope: !4682, file: !4682, line: 159, type: !4694, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4694 = !DISubroutineType(types: !4695)
!4695 = !{!220, !4101, !4681}
!4696 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4697, file: !4679, line: 93)
!4697 = !DISubprogram(name: "iswdigit", scope: !4682, file: !4682, line: 108, type: !4337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4698 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4699, file: !4679, line: 94)
!4699 = !DISubprogram(name: "iswgraph", scope: !4682, file: !4682, line: 112, type: !4337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4700 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4701, file: !4679, line: 95)
!4701 = !DISubprogram(name: "iswlower", scope: !4682, file: !4682, line: 117, type: !4337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4702 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4703, file: !4679, line: 96)
!4703 = !DISubprogram(name: "iswprint", scope: !4682, file: !4682, line: 120, type: !4337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4704 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4705, file: !4679, line: 97)
!4705 = !DISubprogram(name: "iswpunct", scope: !4682, file: !4682, line: 125, type: !4337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4706 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4707, file: !4679, line: 98)
!4707 = !DISubprogram(name: "iswspace", scope: !4682, file: !4682, line: 130, type: !4337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4708 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4709, file: !4679, line: 99)
!4709 = !DISubprogram(name: "iswupper", scope: !4682, file: !4682, line: 135, type: !4337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4710 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4711, file: !4679, line: 100)
!4711 = !DISubprogram(name: "iswxdigit", scope: !4682, file: !4682, line: 140, type: !4337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4712 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4713, file: !4679, line: 101)
!4713 = !DISubprogram(name: "towctrans", scope: !4676, file: !4676, line: 55, type: !4714, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4714 = !DISubroutineType(types: !4715)
!4715 = !{!4101, !4101, !4675}
!4716 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4717, file: !4679, line: 102)
!4717 = !DISubprogram(name: "towlower", scope: !4682, file: !4682, line: 166, type: !4718, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4718 = !DISubroutineType(types: !4719)
!4719 = !{!4101, !4101}
!4720 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4721, file: !4679, line: 103)
!4721 = !DISubprogram(name: "towupper", scope: !4682, file: !4682, line: 169, type: !4718, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4722 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4723, file: !4679, line: 104)
!4723 = !DISubprogram(name: "wctrans", scope: !4676, file: !4676, line: 52, type: !4724, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4724 = !DISubroutineType(types: !4725)
!4725 = !{!4675, !336}
!4726 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4727, file: !4679, line: 105)
!4727 = !DISubprogram(name: "wctype", scope: !4682, file: !4682, line: 155, type: !4728, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4728 = !DISubroutineType(types: !4729)
!4729 = !{!4681, !336}
!4730 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !3, file: !4731, line: 86)
!4731 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr_base.h", directory: "", checksumkind: CSK_MD5, checksum: "8405222f7806be9ab20595b5fcc527fd")
!4732 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4733, file: !4731, line: 87)
!4733 = !DIGlobalVariable(name: "__default_lock_policy", linkageName: "_ZN9__gnu_cxxL21__default_lock_policyE", scope: !5, file: !4, line: 53, type: !4734, isLocal: true, isDefinition: false)
!4734 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3)
!4735 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4736, file: !4739, line: 60)
!4736 = !DIDerivedType(tag: DW_TAG_typedef, name: "clock_t", file: !4737, line: 7, baseType: !4738)
!4737 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/clock_t.h", directory: "", checksumkind: CSK_MD5, checksum: "1aade99fd778d1551600c7ca1410b9f1")
!4738 = !DIDerivedType(tag: DW_TAG_typedef, name: "__clock_t", file: !2982, line: 144, baseType: !23)
!4739 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ctime", directory: "")
!4740 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4741, file: !4739, line: 61)
!4741 = !DIDerivedType(tag: DW_TAG_typedef, name: "time_t", file: !4742, line: 7, baseType: !4743)
!4742 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/time_t.h", directory: "", checksumkind: CSK_MD5, checksum: "49b4e16ef1215de5afdbb283400ab90c")
!4743 = !DIDerivedType(tag: DW_TAG_typedef, name: "__time_t", file: !2982, line: 148, baseType: !23)
!4744 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4286, file: !4739, line: 62)
!4745 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4746, file: !4739, line: 64)
!4746 = !DISubprogram(name: "clock", scope: !4747, file: !4747, line: 72, type: !4748, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4747 = !DIFile(filename: "/usr/include/time.h", directory: "", checksumkind: CSK_MD5, checksum: "3b21b4c7d8bf3fafdb33a1c7ed8e024a")
!4748 = !DISubroutineType(types: !4749)
!4749 = !{!4736}
!4750 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4751, file: !4739, line: 65)
!4751 = !DISubprogram(name: "difftime", scope: !4747, file: !4747, line: 78, type: !4752, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4752 = !DISubroutineType(types: !4753)
!4753 = !{!3479, !4741, !4741}
!4754 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4755, file: !4739, line: 66)
!4755 = !DISubprogram(name: "mktime", scope: !4747, file: !4747, line: 82, type: !4756, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4756 = !DISubroutineType(types: !4757)
!4757 = !{!4741, !4758}
!4758 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4286, size: 64)
!4759 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4760, file: !4739, line: 67)
!4760 = !DISubprogram(name: "time", scope: !4747, file: !4747, line: 75, type: !4761, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4761 = !DISubroutineType(types: !4762)
!4762 = !{!4741, !4763}
!4763 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4741, size: 64)
!4764 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4765, file: !4739, line: 68)
!4765 = !DISubprogram(name: "asctime", scope: !4747, file: !4747, line: 139, type: !4766, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4766 = !DISubroutineType(types: !4767)
!4767 = !{!1295, !4284}
!4768 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4769, file: !4739, line: 69)
!4769 = !DISubprogram(name: "ctime", scope: !4747, file: !4747, line: 142, type: !4770, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4770 = !DISubroutineType(types: !4771)
!4771 = !{!1295, !4772}
!4772 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4773, size: 64)
!4773 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4741)
!4774 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4775, file: !4739, line: 70)
!4775 = !DISubprogram(name: "gmtime", scope: !4747, file: !4747, line: 119, type: !4776, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4776 = !DISubroutineType(types: !4777)
!4777 = !{!4758, !4772}
!4778 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4779, file: !4739, line: 71)
!4779 = !DISubprogram(name: "localtime", scope: !4747, file: !4747, line: 123, type: !4776, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4780 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !320, entity: !4781, file: !4739, line: 72)
!4781 = !DISubprogram(name: "strftime", scope: !4747, file: !4747, line: 88, type: !4782, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4782 = !DISubroutineType(types: !4783)
!4783 = !{!1076, !3842, !1076, !3843, !4283}
!4784 = !DIImportedEntity(tag: DW_TAG_imported_module, scope: !0, entity: !14, file: !2964, line: 19)
!4785 = !{i32 7, !"Dwarf Version", i32 5}
!4786 = !{i32 2, !"Debug Info Version", i32 3}
!4787 = !{i32 1, !"wchar_size", i32 4}
!4788 = !{i32 7, !"PIC Level", i32 2}
!4789 = !{i32 7, !"uwtable", i32 2}
!4790 = !DILocalVariable(name: "__first", arg: 1, scope: !4791, file: !4792, line: 80, type: !1299)
!4791 = distinct !DISubprogram(name: "__distance<llvm::ilist_iterator<const llvm::MachineBasicBlock> >", linkageName: "_ZSt10__distanceIN4llvm14ilist_iteratorIKNS0_17MachineBasicBlockEEEENSt15iterator_traitsIT_E15difference_typeES6_S6_St18input_iterator_tag", scope: !320, file: !4792, line: 80, type: !4793, scopeLine: 82, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, templateParams: !4804, retainedNodes: !4800)
!4792 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_iterator_base_funcs.h", directory: "")
!4793 = !DISubroutineType(types: !4794)
!4794 = !{!4795, !1299, !1299, !1311}
!4795 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !4796, file: !617, line: 156, baseType: !1329)
!4796 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__iterator_traits<llvm::ilist_iterator<const llvm::MachineBasicBlock>, void>", scope: !320, file: !617, line: 147, size: 8, flags: DIFlagTypePassByValue, elements: !275, templateParams: !4797, identifier: "_ZTSSt17__iterator_traitsIN4llvm14ilist_iteratorIKNS0_17MachineBasicBlockEEEvE")
!4797 = !{!4798, !4799}
!4798 = !DITemplateTypeParameter(name: "_Iterator", type: !1299)
!4799 = !DITemplateTypeParameter(type: null)
!4800 = !{!4790, !4801, !4802, !4803}
!4801 = !DILocalVariable(name: "__last", arg: 2, scope: !4791, file: !4792, line: 80, type: !1299)
!4802 = !DILocalVariable(arg: 3, scope: !4791, file: !4792, line: 81, type: !1311)
!4803 = !DILocalVariable(name: "__n", scope: !4791, file: !4792, line: 86, type: !4795)
!4804 = !{!4805}
!4805 = !DITemplateTypeParameter(name: "_InputIterator", type: !1299)
!4806 = !DILocation(line: 0, scope: !4791)
!4807 = !DILocation(line: 80, column: 31, scope: !4791)
