; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -o - -S --passes=simplifycfg | FileCheck %s
; If we have a dbg.value ahead of an optimised-out inst passing through
; FoldCondBranchOnValueKnownInPredecessorImpl, preserve it.
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @_ZN5clang12Preprocessor18ExpandBuiltinMacroERNS_5TokenE(i1 %call181) {
; CHECK-LABEL: @_ZN5clang12Preprocessor18ExpandBuiltinMacroERNS_5TokenE(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 [[CALL181:%.*]], label [[IF_THEN182:%.*]], label [[IF_END231_CRITEDGE:%.*]]
; CHECK:       if.then182:
; CHECK-NEXT:    call void @_ZN5clang12Preprocessor18LexUnexpandedTokenERNS_5TokenE()
; CHECK-NEXT:    call void @llvm.dbg.value(metadata i8 undef, metadata [[META6885:![0-9]+]], metadata !DIExpression()), !dbg [[DBG6953:![0-9]+]]
; CHECK-NEXT:    [[TMP0:%.*]] = xor i1 false, false
; CHECK-NEXT:    call void @llvm.assume(i1 true)
; CHECK-NEXT:    br label [[IF_END231:%.*]]
; CHECK:       if.end231.critedge:
; CHECK-NEXT:    call void @llvm.dbg.value(metadata i8 undef, metadata [[META6885]], metadata !DIExpression()), !dbg [[DBG6953]]
; CHECK-NEXT:    call void @llvm.assume(i1 true)
; CHECK-NEXT:    br label [[IF_END231]]
; CHECK:       if.end231:
; CHECK-NEXT:    ret void
;
entry:
  br i1 %call181, label %if.then182, label %if.end190

if.then182:                                       ; preds = %entry
  call void @_ZN5clang12Preprocessor18LexUnexpandedTokenERNS_5TokenE()
  br label %if.end190

if.end190:                                        ; preds = %if.then182, %entry
  call void @llvm.dbg.value(metadata i8 undef, metadata !6885, metadata !DIExpression()), !dbg !6953
  %0 = xor i1 false, false
  call void @llvm.assume(i1 true)
  br i1 %call181, label %if.then230, label %if.end231

if.then230:                                       ; preds = %if.end190
  br label %if.end231

if.end231:                                        ; preds = %if.then230, %if.end190
  ret void
}

declare void @_ZN5clang12Preprocessor18LexUnexpandedTokenERNS_5TokenE()

; Function Attrs: inaccessiblememonly nocallback nofree nosync nounwind willreturn
declare void @llvm.assume(i1 noundef) #0

; Function Attrs: nocallback nofree nosync nounwind readnone speculatable willreturn
declare void @llvm.dbg.value(metadata, metadata, metadata) #1

attributes #0 = { inaccessiblememonly nocallback nofree nosync nounwind willreturn }
attributes #1 = { nocallback nofree nosync nounwind readnone speculatable willreturn }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!6880, !6881, !6882, !6883, !6884}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !1833, globals: !4303, imports: !5566, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "/fast/fs/llvm34/projects/clang/lib/Lex/PPMacroExpansion.cpp", directory: "/fast/fs/build34llvm5", checksumkind: CSK_MD5, checksum: "84b26e26fade7b8d905a5831be1ffc69")
!2 = !{!3, !11, !292, !953, !1425, !1429, !1444, !1380, !1449, !1454, !1457, !1463, !1467, !1472, !1482, !1540, !1807, !1811, !1826}
!3 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "_Lock_policy", scope: !5, file: !4, line: 49, baseType: !6, size: 32, elements: !7, identifier: "_ZTSN9__gnu_cxx12_Lock_policyE")
!4 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/concurrence.h", directory: "")
!5 = !DINamespace(name: "__gnu_cxx", scope: null)
!6 = !DIBasicType(name: "unsigned int", size: 32, encoding: DW_ATE_unsigned)
!7 = !{!8, !9, !10}
!8 = !DIEnumerator(name: "_S_single", value: 0, isUnsigned: true)
!9 = !DIEnumerator(name: "_S_mutex", value: 1, isUnsigned: true)
!10 = !DIEnumerator(name: "_S_atomic", value: 2, isUnsigned: true)
!11 = !DICompositeType(tag: DW_TAG_enumeration_type, scope: !13, file: !12, line: 17, baseType: !6, size: 32, elements: !15)
!12 = !DIFile(filename: "llvm34/projects/clang/include/clang/Lex/LexDiagnostic.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "c004ed46e8750184209ceb6bf6bd4a00")
!13 = !DINamespace(name: "diag", scope: !14)
!14 = !DINamespace(name: "clang", scope: null)
!15 = !{!16, !17, !18, !19, !20, !21, !22, !23, !24, !25, !26, !27, !28, !29, !30, !31, !32, !33, !34, !35, !36, !37, !38, !39, !40, !41, !42, !43, !44, !45, !46, !47, !48, !49, !50, !51, !52, !53, !54, !55, !56, !57, !58, !59, !60, !61, !62, !63, !64, !65, !66, !67, !68, !69, !70, !71, !72, !73, !74, !75, !76, !77, !78, !79, !80, !81, !82, !83, !84, !85, !86, !87, !88, !89, !90, !91, !92, !93, !94, !95, !96, !97, !98, !99, !100, !101, !102, !103, !104, !105, !106, !107, !108, !109, !110, !111, !112, !113, !114, !115, !116, !117, !118, !119, !120, !121, !122, !123, !124, !125, !126, !127, !128, !129, !130, !131, !132, !133, !134, !135, !136, !137, !138, !139, !140, !141, !142, !143, !144, !145, !146, !147, !148, !149, !150, !151, !152, !153, !154, !155, !156, !157, !158, !159, !160, !161, !162, !163, !164, !165, !166, !167, !168, !169, !170, !171, !172, !173, !174, !175, !176, !177, !178, !179, !180, !181, !182, !183, !184, !185, !186, !187, !188, !189, !190, !191, !192, !193, !194, !195, !196, !197, !198, !199, !200, !201, !202, !203, !204, !205, !206, !207, !208, !209, !210, !211, !212, !213, !214, !215, !216, !217, !218, !219, !220, !221, !222, !223, !224, !225, !226, !227, !228, !229, !230, !231, !232, !233, !234, !235, !236, !237, !238, !239, !240, !241, !242, !243, !244, !245, !246, !247, !248, !249, !250, !251, !252, !253, !254, !255, !256, !257, !258, !259, !260, !261, !262, !263, !264, !265, !266, !267, !268, !269, !270, !271, !272, !273, !274, !275, !276, !277, !278, !279, !280, !281, !282, !283, !284, !285, !286, !287, !288, !289, !290, !291}
!16 = !DIEnumerator(name: "__LEXSTART", value: 620, isUnsigned: true)
!17 = !DIEnumerator(name: "backslash_newline_space", value: 621, isUnsigned: true)
!18 = !DIEnumerator(name: "err__Pragma_malformed", value: 622, isUnsigned: true)
!19 = !DIEnumerator(name: "err_bad_character_encoding", value: 623, isUnsigned: true)
!20 = !DIEnumerator(name: "err_bad_string_encoding", value: 624, isUnsigned: true)
!21 = !DIEnumerator(name: "err_character_too_large", value: 625, isUnsigned: true)
!22 = !DIEnumerator(name: "err_conflict_marker", value: 626, isUnsigned: true)
!23 = !DIEnumerator(name: "err_defined_macro_name", value: 627, isUnsigned: true)
!24 = !DIEnumerator(name: "err_digit_separator_not_between_digits", value: 628, isUnsigned: true)
!25 = !DIEnumerator(name: "err_embedded_include", value: 629, isUnsigned: true)
!26 = !DIEnumerator(name: "err_expected_id_building_module", value: 630, isUnsigned: true)
!27 = !DIEnumerator(name: "err_exponent_has_no_digits", value: 631, isUnsigned: true)
!28 = !DIEnumerator(name: "err_feature_check_malformed", value: 632, isUnsigned: true)
!29 = !DIEnumerator(name: "err_hex_escape_no_digits", value: 633, isUnsigned: true)
!30 = !DIEnumerator(name: "err_hex_escape_too_large", value: 634, isUnsigned: true)
!31 = !DIEnumerator(name: "err_hexconstant_requires_digits", value: 635, isUnsigned: true)
!32 = !DIEnumerator(name: "err_hexconstant_requires_exponent", value: 636, isUnsigned: true)
!33 = !DIEnumerator(name: "err_invalid_binary_digit", value: 637, isUnsigned: true)
!34 = !DIEnumerator(name: "err_invalid_char_raw_delim", value: 638, isUnsigned: true)
!35 = !DIEnumerator(name: "err_invalid_character_to_charify", value: 639, isUnsigned: true)
!36 = !DIEnumerator(name: "err_invalid_decimal_digit", value: 640, isUnsigned: true)
!37 = !DIEnumerator(name: "err_invalid_octal_digit", value: 641, isUnsigned: true)
!38 = !DIEnumerator(name: "err_invalid_pth_file", value: 642, isUnsigned: true)
!39 = !DIEnumerator(name: "err_invalid_suffix_float_constant", value: 643, isUnsigned: true)
!40 = !DIEnumerator(name: "err_invalid_suffix_integer_constant", value: 644, isUnsigned: true)
!41 = !DIEnumerator(name: "err_invalid_utf8", value: 645, isUnsigned: true)
!42 = !DIEnumerator(name: "err_lexing_string", value: 646, isUnsigned: true)
!43 = !DIEnumerator(name: "err_mmap_config_macro_submodule", value: 647, isUnsigned: true)
!44 = !DIEnumerator(name: "err_mmap_expected_attribute", value: 648, isUnsigned: true)
!45 = !DIEnumerator(name: "err_mmap_expected_config_macro", value: 649, isUnsigned: true)
!46 = !DIEnumerator(name: "err_mmap_expected_conflicts_comma", value: 650, isUnsigned: true)
!47 = !DIEnumerator(name: "err_mmap_expected_conflicts_message", value: 651, isUnsigned: true)
!48 = !DIEnumerator(name: "err_mmap_expected_export_wildcard", value: 652, isUnsigned: true)
!49 = !DIEnumerator(name: "err_mmap_expected_feature", value: 653, isUnsigned: true)
!50 = !DIEnumerator(name: "err_mmap_expected_header", value: 654, isUnsigned: true)
!51 = !DIEnumerator(name: "err_mmap_expected_inferred_member", value: 655, isUnsigned: true)
!52 = !DIEnumerator(name: "err_mmap_expected_lbrace", value: 656, isUnsigned: true)
!53 = !DIEnumerator(name: "err_mmap_expected_lbrace_wildcard", value: 657, isUnsigned: true)
!54 = !DIEnumerator(name: "err_mmap_expected_library_name", value: 658, isUnsigned: true)
!55 = !DIEnumerator(name: "err_mmap_expected_member", value: 659, isUnsigned: true)
!56 = !DIEnumerator(name: "err_mmap_expected_mmap_file", value: 660, isUnsigned: true)
!57 = !DIEnumerator(name: "err_mmap_expected_module", value: 661, isUnsigned: true)
!58 = !DIEnumerator(name: "err_mmap_expected_module_name", value: 662, isUnsigned: true)
!59 = !DIEnumerator(name: "err_mmap_expected_rbrace", value: 663, isUnsigned: true)
!60 = !DIEnumerator(name: "err_mmap_expected_rsquare", value: 664, isUnsigned: true)
!61 = !DIEnumerator(name: "err_mmap_explicit_inferred_framework", value: 665, isUnsigned: true)
!62 = !DIEnumerator(name: "err_mmap_explicit_top_level", value: 666, isUnsigned: true)
!63 = !DIEnumerator(name: "err_mmap_header_not_found", value: 667, isUnsigned: true)
!64 = !DIEnumerator(name: "err_mmap_inferred_framework_submodule", value: 668, isUnsigned: true)
!65 = !DIEnumerator(name: "err_mmap_inferred_no_umbrella", value: 669, isUnsigned: true)
!66 = !DIEnumerator(name: "err_mmap_inferred_redef", value: 670, isUnsigned: true)
!67 = !DIEnumerator(name: "err_mmap_missing_exclude_name", value: 671, isUnsigned: true)
!68 = !DIEnumerator(name: "err_mmap_missing_module_qualified", value: 672, isUnsigned: true)
!69 = !DIEnumerator(name: "err_mmap_missing_module_unqualified", value: 673, isUnsigned: true)
!70 = !DIEnumerator(name: "err_mmap_module_id", value: 674, isUnsigned: true)
!71 = !DIEnumerator(name: "err_mmap_module_redefinition", value: 675, isUnsigned: true)
!72 = !DIEnumerator(name: "err_mmap_nested_submodule_id", value: 676, isUnsigned: true)
!73 = !DIEnumerator(name: "err_mmap_top_level_inferred_submodule", value: 677, isUnsigned: true)
!74 = !DIEnumerator(name: "err_mmap_umbrella_clash", value: 678, isUnsigned: true)
!75 = !DIEnumerator(name: "err_mmap_umbrella_dir_not_found", value: 679, isUnsigned: true)
!76 = !DIEnumerator(name: "err_mmap_unknown_token", value: 680, isUnsigned: true)
!77 = !DIEnumerator(name: "err_multichar_utf_character_literal", value: 681, isUnsigned: true)
!78 = !DIEnumerator(name: "err_non_ascii", value: 682, isUnsigned: true)
!79 = !DIEnumerator(name: "err_octal_escape_too_large", value: 683, isUnsigned: true)
!80 = !DIEnumerator(name: "err_pascal_string_too_long", value: 684, isUnsigned: true)
!81 = !DIEnumerator(name: "err_paste_at_end", value: 685, isUnsigned: true)
!82 = !DIEnumerator(name: "err_paste_at_start", value: 686, isUnsigned: true)
!83 = !DIEnumerator(name: "err_pp_arc_cf_code_audited_syntax", value: 687, isUnsigned: true)
!84 = !DIEnumerator(name: "err_pp_bad_paste", value: 688, isUnsigned: true)
!85 = !DIEnumerator(name: "err_pp_bad_paste_ms", value: 689, isUnsigned: true)
!86 = !DIEnumerator(name: "err_pp_colon_without_question", value: 690, isUnsigned: true)
!87 = !DIEnumerator(name: "err_pp_defined_requires_identifier", value: 691, isUnsigned: true)
!88 = !DIEnumerator(name: "err_pp_directive_required", value: 692, isUnsigned: true)
!89 = !DIEnumerator(name: "err_pp_division_by_zero", value: 693, isUnsigned: true)
!90 = !DIEnumerator(name: "err_pp_double_begin_of_arc_cf_code_audited", value: 694, isUnsigned: true)
!91 = !DIEnumerator(name: "err_pp_duplicate_name_in_arg_list", value: 695, isUnsigned: true)
!92 = !DIEnumerator(name: "err_pp_empty_filename", value: 696, isUnsigned: true)
!93 = !DIEnumerator(name: "err_pp_endif_without_if", value: 697, isUnsigned: true)
!94 = !DIEnumerator(name: "err_pp_eof_in_arc_cf_code_audited", value: 698, isUnsigned: true)
!95 = !DIEnumerator(name: "err_pp_error_opening_file", value: 699, isUnsigned: true)
!96 = !DIEnumerator(name: "err_pp_expected_comma_in_arg_list", value: 700, isUnsigned: true)
!97 = !DIEnumerator(name: "err_pp_expected_eol", value: 701, isUnsigned: true)
!98 = !DIEnumerator(name: "err_pp_expected_ident_in_arg_list", value: 702, isUnsigned: true)
!99 = !DIEnumerator(name: "err_pp_expected_rparen", value: 703, isUnsigned: true)
!100 = !DIEnumerator(name: "err_pp_expected_value_in_expr", value: 704, isUnsigned: true)
!101 = !DIEnumerator(name: "err_pp_expects_filename", value: 705, isUnsigned: true)
!102 = !DIEnumerator(name: "err_pp_expr_bad_token_binop", value: 706, isUnsigned: true)
!103 = !DIEnumerator(name: "err_pp_expr_bad_token_start_expr", value: 707, isUnsigned: true)
!104 = !DIEnumerator(name: "err_pp_file_not_found", value: 708, isUnsigned: true)
!105 = !DIEnumerator(name: "err_pp_file_not_found_not_fatal", value: 709, isUnsigned: true)
!106 = !DIEnumerator(name: "err_pp_hash_error", value: 710, isUnsigned: true)
!107 = !DIEnumerator(name: "err_pp_illegal_floating_literal", value: 711, isUnsigned: true)
!108 = !DIEnumerator(name: "err_pp_import_directive_ms", value: 712, isUnsigned: true)
!109 = !DIEnumerator(name: "err_pp_include_in_arc_cf_code_audited", value: 713, isUnsigned: true)
!110 = !DIEnumerator(name: "err_pp_include_too_deep", value: 714, isUnsigned: true)
!111 = !DIEnumerator(name: "err_pp_invalid_directive", value: 715, isUnsigned: true)
!112 = !DIEnumerator(name: "err_pp_invalid_poison", value: 716, isUnsigned: true)
!113 = !DIEnumerator(name: "err_pp_invalid_tok_in_arg_list", value: 717, isUnsigned: true)
!114 = !DIEnumerator(name: "err_pp_invalid_udl", value: 718, isUnsigned: true)
!115 = !DIEnumerator(name: "err_pp_line_digit_sequence", value: 719, isUnsigned: true)
!116 = !DIEnumerator(name: "err_pp_line_invalid_filename", value: 720, isUnsigned: true)
!117 = !DIEnumerator(name: "err_pp_line_requires_integer", value: 721, isUnsigned: true)
!118 = !DIEnumerator(name: "err_pp_linemarker_invalid_filename", value: 722, isUnsigned: true)
!119 = !DIEnumerator(name: "err_pp_linemarker_invalid_flag", value: 723, isUnsigned: true)
!120 = !DIEnumerator(name: "err_pp_linemarker_invalid_pop", value: 724, isUnsigned: true)
!121 = !DIEnumerator(name: "err_pp_linemarker_requires_integer", value: 725, isUnsigned: true)
!122 = !DIEnumerator(name: "err_pp_macro_not_identifier", value: 726, isUnsigned: true)
!123 = !DIEnumerator(name: "err_pp_malformed_ident", value: 727, isUnsigned: true)
!124 = !DIEnumerator(name: "err_pp_missing_lparen", value: 728, isUnsigned: true)
!125 = !DIEnumerator(name: "err_pp_missing_macro_name", value: 729, isUnsigned: true)
!126 = !DIEnumerator(name: "err_pp_missing_rparen", value: 730, isUnsigned: true)
!127 = !DIEnumerator(name: "err_pp_missing_rparen_in_macro_def", value: 731, isUnsigned: true)
!128 = !DIEnumerator(name: "err_pp_opencl_variadic_macros", value: 732, isUnsigned: true)
!129 = !DIEnumerator(name: "err_pp_operator_used_as_macro_name", value: 733, isUnsigned: true)
!130 = !DIEnumerator(name: "err_pp_remainder_by_zero", value: 734, isUnsigned: true)
!131 = !DIEnumerator(name: "err_pp_stringize_not_parameter", value: 735, isUnsigned: true)
!132 = !DIEnumerator(name: "err_pp_unmatched_end_of_arc_cf_code_audited", value: 736, isUnsigned: true)
!133 = !DIEnumerator(name: "err_pp_unterminated_conditional", value: 737, isUnsigned: true)
!134 = !DIEnumerator(name: "err_pp_used_poisoned_id", value: 738, isUnsigned: true)
!135 = !DIEnumerator(name: "err_pp_visibility_non_macro", value: 739, isUnsigned: true)
!136 = !DIEnumerator(name: "err_pragma_message", value: 740, isUnsigned: true)
!137 = !DIEnumerator(name: "err_pragma_message_malformed", value: 741, isUnsigned: true)
!138 = !DIEnumerator(name: "err_pragma_push_pop_macro_malformed", value: 742, isUnsigned: true)
!139 = !DIEnumerator(name: "err_raw_delim_too_long", value: 743, isUnsigned: true)
!140 = !DIEnumerator(name: "err_string_concat_mixed_suffix", value: 744, isUnsigned: true)
!141 = !DIEnumerator(name: "err_too_few_args_in_macro_invoc", value: 745, isUnsigned: true)
!142 = !DIEnumerator(name: "err_too_many_args_in_macro_invoc", value: 746, isUnsigned: true)
!143 = !DIEnumerator(name: "err_ucn_control_character", value: 747, isUnsigned: true)
!144 = !DIEnumerator(name: "err_ucn_escape_basic_scs", value: 748, isUnsigned: true)
!145 = !DIEnumerator(name: "err_ucn_escape_incomplete", value: 749, isUnsigned: true)
!146 = !DIEnumerator(name: "err_ucn_escape_invalid", value: 750, isUnsigned: true)
!147 = !DIEnumerator(name: "err_unsupported_string_concat", value: 751, isUnsigned: true)
!148 = !DIEnumerator(name: "err_unterm_macro_invoc", value: 752, isUnsigned: true)
!149 = !DIEnumerator(name: "err_unterminated___pragma", value: 753, isUnsigned: true)
!150 = !DIEnumerator(name: "err_unterminated_block_comment", value: 754, isUnsigned: true)
!151 = !DIEnumerator(name: "err_unterminated_raw_string", value: 755, isUnsigned: true)
!152 = !DIEnumerator(name: "err_warning_check_malformed", value: 756, isUnsigned: true)
!153 = !DIEnumerator(name: "error_undeclared_use_of_module", value: 757, isUnsigned: true)
!154 = !DIEnumerator(name: "error_use_of_private_header_outside_module", value: 758, isUnsigned: true)
!155 = !DIEnumerator(name: "escaped_newline_block_comment_end", value: 759, isUnsigned: true)
!156 = !DIEnumerator(name: "ext_binary_literal", value: 760, isUnsigned: true)
!157 = !DIEnumerator(name: "ext_binary_literal_cxx1y", value: 761, isUnsigned: true)
!158 = !DIEnumerator(name: "ext_c99_whitespace_required_after_macro_name", value: 762, isUnsigned: true)
!159 = !DIEnumerator(name: "ext_charize_microsoft", value: 763, isUnsigned: true)
!160 = !DIEnumerator(name: "ext_dollar_in_identifier", value: 764, isUnsigned: true)
!161 = !DIEnumerator(name: "ext_embedded_directive", value: 765, isUnsigned: true)
!162 = !DIEnumerator(name: "ext_empty_character", value: 766, isUnsigned: true)
!163 = !DIEnumerator(name: "ext_empty_fnmacro_arg", value: 767, isUnsigned: true)
!164 = !DIEnumerator(name: "ext_four_char_character_literal", value: 768, isUnsigned: true)
!165 = !DIEnumerator(name: "ext_hexconstant_invalid", value: 769, isUnsigned: true)
!166 = !DIEnumerator(name: "ext_imaginary_constant", value: 770, isUnsigned: true)
!167 = !DIEnumerator(name: "ext_line_comment", value: 771, isUnsigned: true)
!168 = !DIEnumerator(name: "ext_missing_varargs_arg", value: 772, isUnsigned: true)
!169 = !DIEnumerator(name: "ext_missing_whitespace_after_macro_name", value: 773, isUnsigned: true)
!170 = !DIEnumerator(name: "ext_ms_reserved_user_defined_literal", value: 774, isUnsigned: true)
!171 = !DIEnumerator(name: "ext_multi_line_line_comment", value: 775, isUnsigned: true)
!172 = !DIEnumerator(name: "ext_multichar_character_literal", value: 776, isUnsigned: true)
!173 = !DIEnumerator(name: "ext_named_variadic_macro", value: 777, isUnsigned: true)
!174 = !DIEnumerator(name: "ext_no_newline_eof", value: 778, isUnsigned: true)
!175 = !DIEnumerator(name: "ext_nonstandard_escape", value: 779, isUnsigned: true)
!176 = !DIEnumerator(name: "ext_on_off_switch_syntax", value: 780, isUnsigned: true)
!177 = !DIEnumerator(name: "ext_paste_comma", value: 781, isUnsigned: true)
!178 = !DIEnumerator(name: "ext_pp_bad_vaargs_use", value: 782, isUnsigned: true)
!179 = !DIEnumerator(name: "ext_pp_comma_expr", value: 783, isUnsigned: true)
!180 = !DIEnumerator(name: "ext_pp_extra_tokens_at_eol", value: 784, isUnsigned: true)
!181 = !DIEnumerator(name: "ext_pp_ident_directive", value: 785, isUnsigned: true)
!182 = !DIEnumerator(name: "ext_pp_import_directive", value: 786, isUnsigned: true)
!183 = !DIEnumerator(name: "ext_pp_include_next_directive", value: 787, isUnsigned: true)
!184 = !DIEnumerator(name: "ext_pp_line_too_big", value: 788, isUnsigned: true)
!185 = !DIEnumerator(name: "ext_pp_line_zero", value: 789, isUnsigned: true)
!186 = !DIEnumerator(name: "ext_pp_macro_redef", value: 790, isUnsigned: true)
!187 = !DIEnumerator(name: "ext_pp_redef_builtin_macro", value: 791, isUnsigned: true)
!188 = !DIEnumerator(name: "ext_pp_undef_builtin_macro", value: 792, isUnsigned: true)
!189 = !DIEnumerator(name: "ext_pp_warning_directive", value: 793, isUnsigned: true)
!190 = !DIEnumerator(name: "ext_pragma_syntax_eod", value: 794, isUnsigned: true)
!191 = !DIEnumerator(name: "ext_reserved_user_defined_literal", value: 795, isUnsigned: true)
!192 = !DIEnumerator(name: "ext_stdc_pragma_ignored", value: 796, isUnsigned: true)
!193 = !DIEnumerator(name: "ext_string_too_long", value: 797, isUnsigned: true)
!194 = !DIEnumerator(name: "ext_token_used", value: 798, isUnsigned: true)
!195 = !DIEnumerator(name: "ext_unicode_whitespace", value: 799, isUnsigned: true)
!196 = !DIEnumerator(name: "ext_unknown_escape", value: 800, isUnsigned: true)
!197 = !DIEnumerator(name: "ext_unterminated_char", value: 801, isUnsigned: true)
!198 = !DIEnumerator(name: "ext_unterminated_string", value: 802, isUnsigned: true)
!199 = !DIEnumerator(name: "ext_variadic_macro", value: 803, isUnsigned: true)
!200 = !DIEnumerator(name: "note_header_guard", value: 804, isUnsigned: true)
!201 = !DIEnumerator(name: "note_init_list_at_beginning_of_macro_argument", value: 805, isUnsigned: true)
!202 = !DIEnumerator(name: "note_macro_here", value: 806, isUnsigned: true)
!203 = !DIEnumerator(name: "note_mmap_lbrace_match", value: 807, isUnsigned: true)
!204 = !DIEnumerator(name: "note_mmap_lsquare_match", value: 808, isUnsigned: true)
!205 = !DIEnumerator(name: "note_mmap_prev_definition", value: 809, isUnsigned: true)
!206 = !DIEnumerator(name: "note_pp_ambiguous_macro_chosen", value: 810, isUnsigned: true)
!207 = !DIEnumerator(name: "note_pp_ambiguous_macro_other", value: 811, isUnsigned: true)
!208 = !DIEnumerator(name: "note_suggest_parens_for_macro", value: 812, isUnsigned: true)
!209 = !DIEnumerator(name: "note_ucn_four_not_eight", value: 813, isUnsigned: true)
!210 = !DIEnumerator(name: "null_in_char", value: 814, isUnsigned: true)
!211 = !DIEnumerator(name: "null_in_file", value: 815, isUnsigned: true)
!212 = !DIEnumerator(name: "null_in_string", value: 816, isUnsigned: true)
!213 = !DIEnumerator(name: "pp_disabled_macro_expansion", value: 817, isUnsigned: true)
!214 = !DIEnumerator(name: "pp_err_elif_after_else", value: 818, isUnsigned: true)
!215 = !DIEnumerator(name: "pp_err_elif_without_if", value: 819, isUnsigned: true)
!216 = !DIEnumerator(name: "pp_err_else_after_else", value: 820, isUnsigned: true)
!217 = !DIEnumerator(name: "pp_err_else_without_if", value: 821, isUnsigned: true)
!218 = !DIEnumerator(name: "pp_hash_warning", value: 822, isUnsigned: true)
!219 = !DIEnumerator(name: "pp_include_macros_out_of_predefines", value: 823, isUnsigned: true)
!220 = !DIEnumerator(name: "pp_include_next_absolute_path", value: 824, isUnsigned: true)
!221 = !DIEnumerator(name: "pp_include_next_in_primary", value: 825, isUnsigned: true)
!222 = !DIEnumerator(name: "pp_invalid_string_literal", value: 826, isUnsigned: true)
!223 = !DIEnumerator(name: "pp_macro_not_used", value: 827, isUnsigned: true)
!224 = !DIEnumerator(name: "pp_out_of_date_dependency", value: 828, isUnsigned: true)
!225 = !DIEnumerator(name: "pp_poisoning_existing_macro", value: 829, isUnsigned: true)
!226 = !DIEnumerator(name: "pp_pragma_once_in_main_file", value: 830, isUnsigned: true)
!227 = !DIEnumerator(name: "pp_pragma_sysheader_in_main_file", value: 831, isUnsigned: true)
!228 = !DIEnumerator(name: "trigraph_converted", value: 832, isUnsigned: true)
!229 = !DIEnumerator(name: "trigraph_ends_block_comment", value: 833, isUnsigned: true)
!230 = !DIEnumerator(name: "trigraph_ignored", value: 834, isUnsigned: true)
!231 = !DIEnumerator(name: "trigraph_ignored_block_comment", value: 835, isUnsigned: true)
!232 = !DIEnumerator(name: "warn_auto_module_import", value: 836, isUnsigned: true)
!233 = !DIEnumerator(name: "warn_bad_character_encoding", value: 837, isUnsigned: true)
!234 = !DIEnumerator(name: "warn_bad_string_encoding", value: 838, isUnsigned: true)
!235 = !DIEnumerator(name: "warn_c99_compat_unicode_id", value: 839, isUnsigned: true)
!236 = !DIEnumerator(name: "warn_c99_compat_unicode_literal", value: 840, isUnsigned: true)
!237 = !DIEnumerator(name: "warn_char_constant_too_large", value: 841, isUnsigned: true)
!238 = !DIEnumerator(name: "warn_cxx11_compat_binary_literal", value: 842, isUnsigned: true)
!239 = !DIEnumerator(name: "warn_cxx11_compat_digit_separator", value: 843, isUnsigned: true)
!240 = !DIEnumerator(name: "warn_cxx11_compat_reserved_user_defined_literal", value: 844, isUnsigned: true)
!241 = !DIEnumerator(name: "warn_cxx11_compat_user_defined_literal", value: 845, isUnsigned: true)
!242 = !DIEnumerator(name: "warn_cxx11_keyword", value: 846, isUnsigned: true)
!243 = !DIEnumerator(name: "warn_cxx98_compat_empty_fnmacro_arg", value: 847, isUnsigned: true)
!244 = !DIEnumerator(name: "warn_cxx98_compat_less_colon_colon", value: 848, isUnsigned: true)
!245 = !DIEnumerator(name: "warn_cxx98_compat_literal_ucn_control_character", value: 849, isUnsigned: true)
!246 = !DIEnumerator(name: "warn_cxx98_compat_literal_ucn_escape_basic_scs", value: 850, isUnsigned: true)
!247 = !DIEnumerator(name: "warn_cxx98_compat_no_newline_eof", value: 851, isUnsigned: true)
!248 = !DIEnumerator(name: "warn_cxx98_compat_pp_line_too_big", value: 852, isUnsigned: true)
!249 = !DIEnumerator(name: "warn_cxx98_compat_raw_string_literal", value: 853, isUnsigned: true)
!250 = !DIEnumerator(name: "warn_cxx98_compat_unicode_id", value: 854, isUnsigned: true)
!251 = !DIEnumerator(name: "warn_cxx98_compat_unicode_literal", value: 855, isUnsigned: true)
!252 = !DIEnumerator(name: "warn_cxx98_compat_variadic_macro", value: 856, isUnsigned: true)
!253 = !DIEnumerator(name: "warn_extraneous_char_constant", value: 857, isUnsigned: true)
!254 = !DIEnumerator(name: "warn_forgotten_module_header", value: 858, isUnsigned: true)
!255 = !DIEnumerator(name: "warn_has_warning_invalid_option", value: 859, isUnsigned: true)
!256 = !DIEnumerator(name: "warn_header_guard", value: 860, isUnsigned: true)
!257 = !DIEnumerator(name: "warn_missing_whitespace_after_macro_name", value: 861, isUnsigned: true)
!258 = !DIEnumerator(name: "warn_mmap_unknown_attribute", value: 862, isUnsigned: true)
!259 = !DIEnumerator(name: "warn_nested_block_comment", value: 863, isUnsigned: true)
!260 = !DIEnumerator(name: "warn_no_newline_eof", value: 864, isUnsigned: true)
!261 = !DIEnumerator(name: "warn_pp_ambiguous_macro", value: 865, isUnsigned: true)
!262 = !DIEnumerator(name: "warn_pp_convert_lhs_to_positive", value: 866, isUnsigned: true)
!263 = !DIEnumerator(name: "warn_pp_convert_rhs_to_positive", value: 867, isUnsigned: true)
!264 = !DIEnumerator(name: "warn_pp_expr_overflow", value: 868, isUnsigned: true)
!265 = !DIEnumerator(name: "warn_pp_line_decimal", value: 869, isUnsigned: true)
!266 = !DIEnumerator(name: "warn_pp_undef_identifier", value: 870, isUnsigned: true)
!267 = !DIEnumerator(name: "warn_pragma_debug_unexpected_command", value: 871, isUnsigned: true)
!268 = !DIEnumerator(name: "warn_pragma_diagnostic_cannot_pop", value: 872, isUnsigned: true)
!269 = !DIEnumerator(name: "warn_pragma_diagnostic_invalid", value: 873, isUnsigned: true)
!270 = !DIEnumerator(name: "warn_pragma_diagnostic_invalid_option", value: 874, isUnsigned: true)
!271 = !DIEnumerator(name: "warn_pragma_diagnostic_invalid_token", value: 875, isUnsigned: true)
!272 = !DIEnumerator(name: "warn_pragma_diagnostic_unknown_warning", value: 876, isUnsigned: true)
!273 = !DIEnumerator(name: "warn_pragma_ignored", value: 877, isUnsigned: true)
!274 = !DIEnumerator(name: "warn_pragma_include_alias_expected", value: 878, isUnsigned: true)
!275 = !DIEnumerator(name: "warn_pragma_include_alias_expected_filename", value: 879, isUnsigned: true)
!276 = !DIEnumerator(name: "warn_pragma_include_alias_mismatch_angle", value: 880, isUnsigned: true)
!277 = !DIEnumerator(name: "warn_pragma_include_alias_mismatch_quote", value: 881, isUnsigned: true)
!278 = !DIEnumerator(name: "warn_pragma_message", value: 882, isUnsigned: true)
!279 = !DIEnumerator(name: "warn_pragma_pop_macro_no_push", value: 883, isUnsigned: true)
!280 = !DIEnumerator(name: "warn_pragma_warning_expected", value: 884, isUnsigned: true)
!281 = !DIEnumerator(name: "warn_pragma_warning_expected_number", value: 885, isUnsigned: true)
!282 = !DIEnumerator(name: "warn_pragma_warning_push_level", value: 886, isUnsigned: true)
!283 = !DIEnumerator(name: "warn_pragma_warning_spec_invalid", value: 887, isUnsigned: true)
!284 = !DIEnumerator(name: "warn_stdc_fenv_access_not_supported", value: 888, isUnsigned: true)
!285 = !DIEnumerator(name: "warn_ucn_escape_incomplete", value: 889, isUnsigned: true)
!286 = !DIEnumerator(name: "warn_ucn_escape_no_digits", value: 890, isUnsigned: true)
!287 = !DIEnumerator(name: "warn_ucn_escape_surrogate", value: 891, isUnsigned: true)
!288 = !DIEnumerator(name: "warn_ucn_not_valid_in_c89", value: 892, isUnsigned: true)
!289 = !DIEnumerator(name: "warn_ucn_not_valid_in_c89_literal", value: 893, isUnsigned: true)
!290 = !DIEnumerator(name: "warn_uncovered_module_header", value: 894, isUnsigned: true)
!291 = !DIEnumerator(name: "NUM_BUILTIN_LEX_DIAGNOSTICS", value: 895, isUnsigned: true)
!292 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "TokenFlags", scope: !294, file: !293, line: 73, baseType: !6, size: 32, elements: !1416, identifier: "_ZTSN5clang5Token10TokenFlagsE")
!293 = !DIFile(filename: "llvm34/projects/clang/include/clang/Lex/Token.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "68b6c37e8c920a18be3730d77a6d50a1")
!294 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Token", scope: !14, file: !293, line: 36, size: 192, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !295, identifier: "_ZTSN5clang5TokenE")
!295 = !{!296, !944, !945, !946, !948, !950, !1274, !1278, !1281, !1282, !1285, !1286, !1287, !1290, !1293, !1296, !1299, !1300, !1301, !1302, !1336, !1339, !1342, !1345, !1351, !1354, !1355, !1358, !1359, !1360, !1363, !1366, !1369, !1370, !1371, !1374, !1375, !1376, !1377, !1409, !1412, !1413, !1414, !1415}
!296 = !DIDerivedType(tag: DW_TAG_member, name: "Loc", scope: !294, file: !293, line: 38, baseType: !297, size: 32)
!297 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SourceLocation", scope: !14, file: !298, line: 87, size: 32, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !299, identifier: "_ZTSN5clang14SourceLocationE")
!298 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/SourceLocation.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "6fa740d6b2148f6e30f14b68326fa300")
!299 = !{!300, !301, !305, !311, !312, !313, !314, !317, !320, !321, !325, !326, !327, !331, !336, !347, !941}
!300 = !DIDerivedType(tag: DW_TAG_member, name: "ID", scope: !297, file: !298, line: 88, baseType: !6, size: 32)
!301 = !DISubprogram(name: "SourceLocation", scope: !297, file: !298, line: 97, type: !302, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!302 = !DISubroutineType(types: !303)
!303 = !{null, !304}
!304 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !297, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!305 = !DISubprogram(name: "isFileID", linkageName: "_ZNK5clang14SourceLocation8isFileIDEv", scope: !297, file: !298, line: 99, type: !306, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!306 = !DISubroutineType(types: !307)
!307 = !{!308, !309}
!308 = !DIBasicType(name: "bool", size: 8, encoding: DW_ATE_boolean)
!309 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !310, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!310 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !297)
!311 = !DISubprogram(name: "isMacroID", linkageName: "_ZNK5clang14SourceLocation9isMacroIDEv", scope: !297, file: !298, line: 100, type: !306, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!312 = !DISubprogram(name: "isValid", linkageName: "_ZNK5clang14SourceLocation7isValidEv", scope: !297, file: !298, line: 107, type: !306, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!313 = !DISubprogram(name: "isInvalid", linkageName: "_ZNK5clang14SourceLocation9isInvalidEv", scope: !297, file: !298, line: 108, type: !306, scopeLine: 108, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!314 = !DISubprogram(name: "getOffset", linkageName: "_ZNK5clang14SourceLocation9getOffsetEv", scope: !297, file: !298, line: 112, type: !315, scopeLine: 112, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!315 = !DISubroutineType(types: !316)
!316 = !{!6, !309}
!317 = !DISubprogram(name: "getFileLoc", linkageName: "_ZN5clang14SourceLocation10getFileLocEj", scope: !297, file: !298, line: 116, type: !318, scopeLine: 116, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!318 = !DISubroutineType(types: !319)
!319 = !{!297, !6}
!320 = !DISubprogram(name: "getMacroLoc", linkageName: "_ZN5clang14SourceLocation11getMacroLocEj", scope: !297, file: !298, line: 123, type: !318, scopeLine: 123, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!321 = !DISubprogram(name: "getLocWithOffset", linkageName: "_ZNK5clang14SourceLocation16getLocWithOffsetEi", scope: !297, file: !298, line: 133, type: !322, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!322 = !DISubroutineType(types: !323)
!323 = !{!297, !309, !324}
!324 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!325 = !DISubprogram(name: "getRawEncoding", linkageName: "_ZNK5clang14SourceLocation14getRawEncodingEv", scope: !297, file: !298, line: 145, type: !315, scopeLine: 145, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!326 = !DISubprogram(name: "getFromRawEncoding", linkageName: "_ZN5clang14SourceLocation18getFromRawEncodingEj", scope: !297, file: !298, line: 151, type: !318, scopeLine: 151, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!327 = !DISubprogram(name: "getPtrEncoding", linkageName: "_ZNK5clang14SourceLocation14getPtrEncodingEv", scope: !297, file: !298, line: 162, type: !328, scopeLine: 162, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!328 = !DISubroutineType(types: !329)
!329 = !{!330, !309}
!330 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 64)
!331 = !DISubprogram(name: "getFromPtrEncoding", linkageName: "_ZN5clang14SourceLocation18getFromPtrEncodingEPKv", scope: !297, file: !298, line: 170, type: !332, scopeLine: 170, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!332 = !DISubroutineType(types: !333)
!333 = !{!297, !334}
!334 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !335, size: 64)
!335 = !DIDerivedType(tag: DW_TAG_const_type, baseType: null)
!336 = !DISubprogram(name: "print", linkageName: "_ZNK5clang14SourceLocation5printERN4llvm11raw_ostreamERKNS_13SourceManagerE", scope: !297, file: !298, line: 174, type: !337, scopeLine: 174, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!337 = !DISubroutineType(types: !338)
!338 = !{null, !309, !339, !343}
!339 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !340, size: 64)
!340 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "raw_ostream", scope: !342, file: !341, line: 47, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm11raw_ostreamE")
!341 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/LLVM.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "fe3bbe0ce03f58807015987f11a2006c")
!342 = !DINamespace(name: "llvm", scope: null)
!343 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !344, size: 64)
!344 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !345)
!345 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SourceManager", scope: !14, file: !346, line: 538, size: 4928, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang13SourceManagerE")
!346 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/SourceManager.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e6d975d790c3941a74fcadca377a23e0")
!347 = !DISubprogram(name: "printToString", linkageName: "_ZNK5clang14SourceLocation13printToStringB5cxx11ERKNS_13SourceManagerE", scope: !297, file: !298, line: 175, type: !348, scopeLine: 175, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!348 = !DISubroutineType(types: !349)
!349 = !{!350, !309, !343}
!350 = !DIDerivedType(tag: DW_TAG_typedef, name: "string", scope: !352, file: !351, line: 74, baseType: !354)
!351 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stringfwd.h", directory: "")
!352 = !DINamespace(name: "__cxx11", scope: !353, exportSymbols: true)
!353 = !DINamespace(name: "std", scope: null)
!354 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "basic_string<char, std::char_traits<char>, std::allocator<char> >", scope: !352, file: !355, line: 1607, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !356, templateParams: !887, identifier: "_ZTSNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE")
!355 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.tcc", directory: "")
!356 = !{!357, !471, !492, !493, !501, !505, !508, !513, !516, !522, !523, !524, !527, !531, !534, !535, !538, !539, !543, !548, !551, !554, !557, !560, !563, !564, !567, !573, !578, !581, !584, !587, !591, !594, !597, !598, !601, !602, !605, !608, !611, !614, !617, !620, !624, !629, !632, !635, !636, !640, !643, !646, !649, !652, !655, !658, !659, !660, !665, !670, !671, !672, !673, !674, !675, !676, !679, !680, !681, !682, !683, !684, !685, !686, !687, !688, !697, !703, !704, !705, !708, !711, !712, !713, !714, !715, !716, !717, !718, !721, !724, !725, !728, !729, !732, !733, !734, !735, !736, !737, !738, !739, !742, !745, !748, !751, !754, !757, !760, !764, !767, !770, !773, !774, !777, !780, !783, !786, !789, !792, !795, !798, !801, !804, !807, !810, !813, !816, !817, !820, !821, !824, !827, !830, !831, !834, !837, !840, !843, !846, !847, !848, !849, !850, !851, !852, !853, !854, !855, !856, !857, !858, !859, !860, !861, !862, !863, !864, !865, !866, !869, !872, !875, !878, !881, !884}
!357 = !DIDerivedType(tag: DW_TAG_member, name: "npos", scope: !354, file: !358, line: 101, baseType: !359, flags: DIFlagPublic | DIFlagStaticMember, extraData: i64 -1)
!358 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h", directory: "")
!359 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !360)
!360 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !354, file: !358, line: 88, baseType: !361)
!361 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !363, file: !362, line: 61, baseType: !447)
!362 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/alloc_traits.h", directory: "")
!363 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__alloc_traits<std::allocator<char>, char>", scope: !5, file: !362, line: 50, size: 8, flags: DIFlagTypePassByValue, elements: !364, templateParams: !469, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIcEcEE")
!364 = !{!365, !455, !458, !462, !465, !466, !467, !468}
!365 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !363, baseType: !366, extraData: i32 0)
!366 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "allocator_traits<std::allocator<char> >", scope: !353, file: !367, line: 384, size: 8, flags: DIFlagTypePassByValue, elements: !368, templateParams: !453, identifier: "_ZTSSt16allocator_traitsISaIcEE")
!367 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/alloc_traits.h", directory: "", checksumkind: CSK_MD5, checksum: "f7f651aab55acaadfc53aa53979a817c")
!368 = !{!369, !437, !441, !444, !450}
!369 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIcEE8allocateERS0_m", scope: !366, file: !367, line: 435, type: !370, scopeLine: 435, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!370 = !DISubroutineType(types: !371)
!371 = !{!372, !375, !436}
!372 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !366, file: !367, line: 392, baseType: !373)
!373 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !374, size: 64)
!374 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
!375 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !376, size: 64)
!376 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !366, file: !367, line: 387, baseType: !377)
!377 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "allocator<char>", scope: !353, file: !378, line: 199, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !379, templateParams: !424, identifier: "_ZTSSaIcE")
!378 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "9cafc7b584300736771313d46be845c3")
!379 = !{!380, !426, !430, !435}
!380 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !377, baseType: !381, flags: DIFlagPublic, extraData: i32 0)
!381 = !DIDerivedType(tag: DW_TAG_typedef, name: "__allocator_base<char>", scope: !353, file: !382, line: 48, baseType: !383)
!382 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8/bits/c++allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "9572fa47638d84b83d0311676a9766b8")
!383 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "new_allocator<char>", scope: !5, file: !384, line: 58, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !385, templateParams: !424, identifier: "_ZTSN9__gnu_cxx13new_allocatorIcEE")
!384 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/new_allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "ece13daf300dfc0cac27dc2ea29129ca")
!385 = !{!386, !390, !395, !396, !403, !411, !418, !421}
!386 = !DISubprogram(name: "new_allocator", scope: !383, file: !384, line: 79, type: !387, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!387 = !DISubroutineType(types: !388)
!388 = !{null, !389}
!389 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !383, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!390 = !DISubprogram(name: "new_allocator", scope: !383, file: !384, line: 81, type: !391, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!391 = !DISubroutineType(types: !392)
!392 = !{null, !389, !393}
!393 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !394, size: 64)
!394 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !383)
!395 = !DISubprogram(name: "~new_allocator", scope: !383, file: !384, line: 86, type: !387, scopeLine: 86, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!396 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorIcE7addressERc", scope: !383, file: !384, line: 89, type: !397, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!397 = !DISubroutineType(types: !398)
!398 = !{!399, !400, !401}
!399 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !383, file: !384, line: 63, baseType: !373)
!400 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !394, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!401 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !383, file: !384, line: 65, baseType: !402)
!402 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !374, size: 64)
!403 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorIcE7addressERKc", scope: !383, file: !384, line: 93, type: !404, scopeLine: 93, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!404 = !DISubroutineType(types: !405)
!405 = !{!406, !400, !409}
!406 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !383, file: !384, line: 64, baseType: !407)
!407 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !408, size: 64)
!408 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !374)
!409 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !383, file: !384, line: 66, baseType: !410)
!410 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !408, size: 64)
!411 = !DISubprogram(name: "allocate", linkageName: "_ZN9__gnu_cxx13new_allocatorIcE8allocateEmPKv", scope: !383, file: !384, line: 99, type: !412, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!412 = !DISubroutineType(types: !413)
!413 = !{!399, !389, !414, !334}
!414 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !384, line: 61, baseType: !415)
!415 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", scope: !353, file: !416, line: 238, baseType: !417)
!416 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8/bits/c++config.h", directory: "", checksumkind: CSK_MD5, checksum: "5ab2830680f5a52514c973f039a03c0a")
!417 = !DIBasicType(name: "unsigned long", size: 64, encoding: DW_ATE_unsigned)
!418 = !DISubprogram(name: "deallocate", linkageName: "_ZN9__gnu_cxx13new_allocatorIcE10deallocateEPcm", scope: !383, file: !384, line: 116, type: !419, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!419 = !DISubroutineType(types: !420)
!420 = !{null, !389, !399, !414}
!421 = !DISubprogram(name: "max_size", linkageName: "_ZNK9__gnu_cxx13new_allocatorIcE8max_sizeEv", scope: !383, file: !384, line: 129, type: !422, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!422 = !DISubroutineType(types: !423)
!423 = !{!414, !400}
!424 = !{!425}
!425 = !DITemplateTypeParameter(name: "_Tp", type: !374)
!426 = !DISubprogram(name: "allocator", scope: !377, file: !378, line: 131, type: !427, scopeLine: 131, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!427 = !DISubroutineType(types: !428)
!428 = !{null, !429}
!429 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !377, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!430 = !DISubprogram(name: "allocator", scope: !377, file: !378, line: 133, type: !431, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!431 = !DISubroutineType(types: !432)
!432 = !{null, !429, !433}
!433 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !434, size: 64)
!434 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !377)
!435 = !DISubprogram(name: "~allocator", scope: !377, file: !378, line: 139, type: !427, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!436 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !367, line: 407, baseType: !415)
!437 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIcEE8allocateERS0_mPKv", scope: !366, file: !367, line: 449, type: !438, scopeLine: 449, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!438 = !DISubroutineType(types: !439)
!439 = !{!372, !375, !436, !440}
!440 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_void_pointer", file: !367, line: 401, baseType: !334)
!441 = !DISubprogram(name: "deallocate", linkageName: "_ZNSt16allocator_traitsISaIcEE10deallocateERS0_Pcm", scope: !366, file: !367, line: 461, type: !442, scopeLine: 461, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!442 = !DISubroutineType(types: !443)
!443 = !{null, !375, !372, !436}
!444 = !DISubprogram(name: "max_size", linkageName: "_ZNSt16allocator_traitsISaIcEE8max_sizeERKS0_", scope: !366, file: !367, line: 495, type: !445, scopeLine: 495, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!445 = !DISubroutineType(types: !446)
!446 = !{!447, !448}
!447 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !366, file: !367, line: 407, baseType: !415)
!448 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !449, size: 64)
!449 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !376)
!450 = !DISubprogram(name: "select_on_container_copy_construction", linkageName: "_ZNSt16allocator_traitsISaIcEE37select_on_container_copy_constructionERKS0_", scope: !366, file: !367, line: 504, type: !451, scopeLine: 504, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!451 = !DISubroutineType(types: !452)
!452 = !{!376, !448}
!453 = !{!454}
!454 = !DITemplateTypeParameter(name: "_Alloc", type: !377)
!455 = !DISubprogram(name: "_S_select_on_copy", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIcEcE17_S_select_on_copyERKS1_", scope: !363, file: !362, line: 94, type: !456, scopeLine: 94, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!456 = !DISubroutineType(types: !457)
!457 = !{!377, !433}
!458 = !DISubprogram(name: "_S_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIcEcE10_S_on_swapERS1_S3_", scope: !363, file: !362, line: 97, type: !459, scopeLine: 97, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!459 = !DISubroutineType(types: !460)
!460 = !{null, !461, !461}
!461 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !377, size: 64)
!462 = !DISubprogram(name: "_S_propagate_on_copy_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIcEcE27_S_propagate_on_copy_assignEv", scope: !363, file: !362, line: 100, type: !463, scopeLine: 100, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!463 = !DISubroutineType(types: !464)
!464 = !{!308}
!465 = !DISubprogram(name: "_S_propagate_on_move_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIcEcE27_S_propagate_on_move_assignEv", scope: !363, file: !362, line: 103, type: !463, scopeLine: 103, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!466 = !DISubprogram(name: "_S_propagate_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIcEcE20_S_propagate_on_swapEv", scope: !363, file: !362, line: 106, type: !463, scopeLine: 106, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!467 = !DISubprogram(name: "_S_always_equal", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIcEcE15_S_always_equalEv", scope: !363, file: !362, line: 109, type: !463, scopeLine: 109, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!468 = !DISubprogram(name: "_S_nothrow_move", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIcEcE15_S_nothrow_moveEv", scope: !363, file: !362, line: 112, type: !463, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!469 = !{!454, !470}
!470 = !DITemplateTypeParameter(type: !374)
!471 = !DIDerivedType(tag: DW_TAG_member, name: "_M_dataplus", scope: !354, file: !358, line: 155, baseType: !472, size: 64)
!472 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Alloc_hider", scope: !354, file: !358, line: 139, size: 64, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !473, identifier: "_ZTSNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_Alloc_hiderE")
!473 = !{!474, !481, !484, !488}
!474 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !472, baseType: !475, extraData: i32 0)
!475 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !354, file: !358, line: 87, baseType: !476)
!476 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Char_alloc_type", scope: !354, file: !358, line: 80, baseType: !477)
!477 = !DIDerivedType(tag: DW_TAG_typedef, name: "other", scope: !478, file: !362, line: 117, baseType: !480)
!478 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "rebind<char>", scope: !363, file: !362, line: 116, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !424, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIcEcE6rebindIcEE")
!479 = !{}
!480 = !DIDerivedType(tag: DW_TAG_typedef, name: "rebind_alloc<char>", scope: !366, file: !367, line: 422, baseType: !377)
!481 = !DIDerivedType(tag: DW_TAG_member, name: "_M_p", scope: !472, file: !358, line: 152, baseType: !482, size: 64)
!482 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !354, file: !358, line: 92, baseType: !483)
!483 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !363, file: !362, line: 59, baseType: !372)
!484 = !DISubprogram(name: "_Alloc_hider", scope: !472, file: !358, line: 145, type: !485, scopeLine: 145, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!485 = !DISubroutineType(types: !486)
!486 = !{null, !487, !482, !433}
!487 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !472, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!488 = !DISubprogram(name: "_Alloc_hider", scope: !472, file: !358, line: 148, type: !489, scopeLine: 148, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!489 = !DISubroutineType(types: !490)
!490 = !{null, !487, !482, !491}
!491 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !377, size: 64)
!492 = !DIDerivedType(tag: DW_TAG_member, name: "_M_string_length", scope: !354, file: !358, line: 156, baseType: !360, size: 64, offset: 64)
!493 = !DIDerivedType(tag: DW_TAG_member, scope: !354, file: !358, line: 160, baseType: !494, size: 128, offset: 128)
!494 = distinct !DICompositeType(tag: DW_TAG_union_type, scope: !354, file: !358, line: 160, size: 128, flags: DIFlagExportSymbols | DIFlagTypePassByValue, elements: !495, identifier: "_ZTSNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEUt0_E")
!495 = !{!496, !500}
!496 = !DIDerivedType(tag: DW_TAG_member, name: "_M_local_buf", scope: !494, file: !358, line: 162, baseType: !497, size: 128)
!497 = !DICompositeType(tag: DW_TAG_array_type, baseType: !374, size: 128, elements: !498)
!498 = !{!499}
!499 = !DISubrange(count: 16)
!500 = !DIDerivedType(tag: DW_TAG_member, name: "_M_allocated_capacity", scope: !494, file: !358, line: 163, baseType: !360, size: 64)
!501 = !DISubprogram(name: "_M_data", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7_M_dataEPc", scope: !354, file: !358, line: 167, type: !502, scopeLine: 167, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!502 = !DISubroutineType(types: !503)
!503 = !{null, !504, !482}
!504 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !354, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!505 = !DISubprogram(name: "_M_length", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_lengthEm", scope: !354, file: !358, line: 171, type: !506, scopeLine: 171, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!506 = !DISubroutineType(types: !507)
!507 = !{null, !504, !360}
!508 = !DISubprogram(name: "_M_data", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7_M_dataEv", scope: !354, file: !358, line: 175, type: !509, scopeLine: 175, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!509 = !DISubroutineType(types: !510)
!510 = !{!482, !511}
!511 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !512, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!512 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !354)
!513 = !DISubprogram(name: "_M_local_data", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_M_local_dataEv", scope: !354, file: !358, line: 179, type: !514, scopeLine: 179, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!514 = !DISubroutineType(types: !515)
!515 = !{!482, !504}
!516 = !DISubprogram(name: "_M_local_data", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_M_local_dataEv", scope: !354, file: !358, line: 189, type: !517, scopeLine: 189, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!517 = !DISubroutineType(types: !518)
!518 = !{!519, !511}
!519 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !354, file: !358, line: 93, baseType: !520)
!520 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !363, file: !362, line: 60, baseType: !521)
!521 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !366, file: !367, line: 395, baseType: !407)
!522 = !DISubprogram(name: "_M_capacity", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE11_M_capacityEm", scope: !354, file: !358, line: 199, type: !506, scopeLine: 199, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!523 = !DISubprogram(name: "_M_set_length", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_M_set_lengthEm", scope: !354, file: !358, line: 203, type: !506, scopeLine: 203, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!524 = !DISubprogram(name: "_M_is_local", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE11_M_is_localEv", scope: !354, file: !358, line: 210, type: !525, scopeLine: 210, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!525 = !DISubroutineType(types: !526)
!526 = !{!308, !511}
!527 = !DISubprogram(name: "_M_create", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm", scope: !354, file: !358, line: 215, type: !528, scopeLine: 215, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!528 = !DISubroutineType(types: !529)
!529 = !{!482, !504, !530, !360}
!530 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !360, size: 64)
!531 = !DISubprogram(name: "_M_dispose", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv", scope: !354, file: !358, line: 218, type: !532, scopeLine: 218, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!532 = !DISubroutineType(types: !533)
!533 = !{null, !504}
!534 = !DISubprogram(name: "_M_destroy", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_destroyEm", scope: !354, file: !358, line: 225, type: !506, scopeLine: 225, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!535 = !DISubprogram(name: "_M_construct_aux_2", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE18_M_construct_aux_2Emc", scope: !354, file: !358, line: 247, type: !536, scopeLine: 247, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!536 = !DISubroutineType(types: !537)
!537 = !{null, !504, !360, !374}
!538 = !DISubprogram(name: "_M_construct", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructEmc", scope: !354, file: !358, line: 272, type: !536, scopeLine: 272, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!539 = !DISubprogram(name: "_M_get_allocator", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE16_M_get_allocatorEv", scope: !354, file: !358, line: 275, type: !540, scopeLine: 275, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!540 = !DISubroutineType(types: !541)
!541 = !{!542, !504}
!542 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !475, size: 64)
!543 = !DISubprogram(name: "_M_get_allocator", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE16_M_get_allocatorEv", scope: !354, file: !358, line: 279, type: !544, scopeLine: 279, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!544 = !DISubroutineType(types: !545)
!545 = !{!546, !511}
!546 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !547, size: 64)
!547 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !475)
!548 = !DISubprogram(name: "_M_check", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE8_M_checkEmPKc", scope: !354, file: !358, line: 299, type: !549, scopeLine: 299, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!549 = !DISubroutineType(types: !550)
!550 = !{!360, !511, !360, !407}
!551 = !DISubprogram(name: "_M_check_length", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE15_M_check_lengthEmmPKc", scope: !354, file: !358, line: 309, type: !552, scopeLine: 309, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!552 = !DISubroutineType(types: !553)
!553 = !{null, !511, !360, !360, !407}
!554 = !DISubprogram(name: "_M_limit", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE8_M_limitEmm", scope: !354, file: !358, line: 318, type: !555, scopeLine: 318, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!555 = !DISubroutineType(types: !556)
!556 = !{!360, !511, !360, !360}
!557 = !DISubprogram(name: "_M_disjunct", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE11_M_disjunctEPKc", scope: !354, file: !358, line: 326, type: !558, scopeLine: 326, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!558 = !DISubroutineType(types: !559)
!559 = !{!308, !511, !407}
!560 = !DISubprogram(name: "_S_copy", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7_S_copyEPcPKcm", scope: !354, file: !358, line: 335, type: !561, scopeLine: 335, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!561 = !DISubroutineType(types: !562)
!562 = !{null, !373, !407, !360}
!563 = !DISubprogram(name: "_S_move", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7_S_moveEPcPKcm", scope: !354, file: !358, line: 344, type: !561, scopeLine: 344, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!564 = !DISubprogram(name: "_S_assign", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_S_assignEPcmc", scope: !354, file: !358, line: 353, type: !565, scopeLine: 353, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!565 = !DISubroutineType(types: !566)
!566 = !{null, !373, !360, !374}
!567 = !DISubprogram(name: "_S_copy_chars", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcN9__gnu_cxx17__normal_iteratorIS5_S4_EES8_", scope: !354, file: !358, line: 372, type: !568, scopeLine: 372, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!568 = !DISubroutineType(types: !569)
!569 = !{null, !373, !570, !570}
!570 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !354, file: !358, line: 94, baseType: !571)
!571 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<char *, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >", scope: !5, file: !572, line: 764, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE")
!572 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_iterator.h", directory: "", checksumkind: CSK_MD5, checksum: "43ca426be47f2e0c5f7f184d7d27a436")
!573 = !DISubprogram(name: "_S_copy_chars", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcN9__gnu_cxx17__normal_iteratorIPKcS4_EESA_", scope: !354, file: !358, line: 376, type: !574, scopeLine: 376, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!574 = !DISubroutineType(types: !575)
!575 = !{null, !373, !576, !576}
!576 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !354, file: !358, line: 96, baseType: !577)
!577 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<const char *, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >", scope: !5, file: !572, line: 764, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE")
!578 = !DISubprogram(name: "_S_copy_chars", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcS5_S5_", scope: !354, file: !358, line: 381, type: !579, scopeLine: 381, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!579 = !DISubroutineType(types: !580)
!580 = !{null, !373, !373, !373}
!581 = !DISubprogram(name: "_S_copy_chars", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcPKcS7_", scope: !354, file: !358, line: 385, type: !582, scopeLine: 385, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!582 = !DISubroutineType(types: !583)
!583 = !{null, !373, !407, !407}
!584 = !DISubprogram(name: "_S_compare", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_S_compareEmm", scope: !354, file: !358, line: 390, type: !585, scopeLine: 390, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!585 = !DISubroutineType(types: !586)
!586 = !{!324, !360, !360}
!587 = !DISubprogram(name: "_M_assign", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_", scope: !354, file: !358, line: 403, type: !588, scopeLine: 403, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!588 = !DISubroutineType(types: !589)
!589 = !{null, !504, !590}
!590 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !512, size: 64)
!591 = !DISubprogram(name: "_M_mutate", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_mutateEmmPKcm", scope: !354, file: !358, line: 406, type: !592, scopeLine: 406, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!592 = !DISubroutineType(types: !593)
!593 = !{null, !504, !360, !360, !407, !360}
!594 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE8_M_eraseEmm", scope: !354, file: !358, line: 410, type: !595, scopeLine: 410, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!595 = !DISubroutineType(types: !596)
!596 = !{null, !504, !360, !360}
!597 = !DISubprogram(name: "basic_string", scope: !354, file: !358, line: 420, type: !532, scopeLine: 420, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!598 = !DISubprogram(name: "basic_string", scope: !354, file: !358, line: 429, type: !599, scopeLine: 429, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!599 = !DISubroutineType(types: !600)
!600 = !{null, !504, !433}
!601 = !DISubprogram(name: "basic_string", scope: !354, file: !358, line: 437, type: !588, scopeLine: 437, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!602 = !DISubprogram(name: "basic_string", scope: !354, file: !358, line: 450, type: !603, scopeLine: 450, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!603 = !DISubroutineType(types: !604)
!604 = !{null, !504, !590, !360, !433}
!605 = !DISubprogram(name: "basic_string", scope: !354, file: !358, line: 465, type: !606, scopeLine: 465, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!606 = !DISubroutineType(types: !607)
!607 = !{null, !504, !590, !360, !360}
!608 = !DISubprogram(name: "basic_string", scope: !354, file: !358, line: 481, type: !609, scopeLine: 481, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!609 = !DISubroutineType(types: !610)
!610 = !{null, !504, !590, !360, !360, !433}
!611 = !DISubprogram(name: "basic_string", scope: !354, file: !358, line: 499, type: !612, scopeLine: 499, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!612 = !DISubroutineType(types: !613)
!613 = !{null, !504, !407, !360, !433}
!614 = !DISubprogram(name: "basic_string", scope: !354, file: !358, line: 514, type: !615, scopeLine: 514, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!615 = !DISubroutineType(types: !616)
!616 = !{null, !504, !407, !433}
!617 = !DISubprogram(name: "basic_string", scope: !354, file: !358, line: 529, type: !618, scopeLine: 529, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!618 = !DISubroutineType(types: !619)
!619 = !{null, !504, !360, !374, !433}
!620 = !DISubprogram(name: "basic_string", scope: !354, file: !358, line: 541, type: !621, scopeLine: 541, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!621 = !DISubroutineType(types: !622)
!622 = !{null, !504, !623}
!623 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !354, size: 64)
!624 = !DISubprogram(name: "basic_string", scope: !354, file: !358, line: 568, type: !625, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!625 = !DISubroutineType(types: !626)
!626 = !{null, !504, !627, !433}
!627 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<char>", scope: !353, file: !628, line: 47, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listIcE")
!628 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/initializer_list", directory: "")
!629 = !DISubprogram(name: "basic_string", scope: !354, file: !358, line: 572, type: !630, scopeLine: 572, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!630 = !DISubroutineType(types: !631)
!631 = !{null, !504, !590, !433}
!632 = !DISubprogram(name: "basic_string", scope: !354, file: !358, line: 576, type: !633, scopeLine: 576, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!633 = !DISubroutineType(types: !634)
!634 = !{null, !504, !623, !433}
!635 = !DISubprogram(name: "~basic_string", scope: !354, file: !358, line: 656, type: !532, scopeLine: 656, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!636 = !DISubprogram(name: "operator=", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSERKS4_", scope: !354, file: !358, line: 664, type: !637, scopeLine: 664, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!637 = !DISubroutineType(types: !638)
!638 = !{!639, !504, !590}
!639 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !354, size: 64)
!640 = !DISubprogram(name: "operator=", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSEPKc", scope: !354, file: !358, line: 703, type: !641, scopeLine: 703, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!641 = !DISubroutineType(types: !642)
!642 = !{!639, !504, !407}
!643 = !DISubprogram(name: "operator=", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSEc", scope: !354, file: !358, line: 714, type: !644, scopeLine: 714, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!644 = !DISubroutineType(types: !645)
!645 = !{!639, !504, !374}
!646 = !DISubprogram(name: "operator=", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSEOS4_", scope: !354, file: !358, line: 732, type: !647, scopeLine: 732, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!647 = !DISubroutineType(types: !648)
!648 = !{!639, !504, !623}
!649 = !DISubprogram(name: "operator=", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSESt16initializer_listIcE", scope: !354, file: !358, line: 795, type: !650, scopeLine: 795, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!650 = !DISubroutineType(types: !651)
!651 = !{!639, !504, !627}
!652 = !DISubprogram(name: "begin", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5beginEv", scope: !354, file: !358, line: 826, type: !653, scopeLine: 826, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!653 = !DISubroutineType(types: !654)
!654 = !{!570, !504}
!655 = !DISubprogram(name: "begin", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5beginEv", scope: !354, file: !358, line: 834, type: !656, scopeLine: 834, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!656 = !DISubroutineType(types: !657)
!657 = !{!576, !511}
!658 = !DISubprogram(name: "end", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE3endEv", scope: !354, file: !358, line: 842, type: !653, scopeLine: 842, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!659 = !DISubprogram(name: "end", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE3endEv", scope: !354, file: !358, line: 850, type: !656, scopeLine: 850, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!660 = !DISubprogram(name: "rbegin", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6rbeginEv", scope: !354, file: !358, line: 859, type: !661, scopeLine: 859, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!661 = !DISubroutineType(types: !662)
!662 = !{!663, !504}
!663 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !354, file: !358, line: 98, baseType: !664)
!664 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<char *, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >", scope: !353, file: !572, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEE")
!665 = !DISubprogram(name: "rbegin", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6rbeginEv", scope: !354, file: !358, line: 868, type: !666, scopeLine: 868, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!666 = !DISubroutineType(types: !667)
!667 = !{!668, !511}
!668 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !354, file: !358, line: 97, baseType: !669)
!669 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<const char *, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >", scope: !353, file: !572, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEE")
!670 = !DISubprogram(name: "rend", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4rendEv", scope: !354, file: !358, line: 877, type: !661, scopeLine: 877, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!671 = !DISubprogram(name: "rend", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4rendEv", scope: !354, file: !358, line: 886, type: !666, scopeLine: 886, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!672 = !DISubprogram(name: "cbegin", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6cbeginEv", scope: !354, file: !358, line: 895, type: !656, scopeLine: 895, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!673 = !DISubprogram(name: "cend", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4cendEv", scope: !354, file: !358, line: 903, type: !656, scopeLine: 903, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!674 = !DISubprogram(name: "crbegin", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7crbeginEv", scope: !354, file: !358, line: 912, type: !666, scopeLine: 912, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!675 = !DISubprogram(name: "crend", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5crendEv", scope: !354, file: !358, line: 921, type: !666, scopeLine: 921, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!676 = !DISubprogram(name: "size", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4sizeEv", scope: !354, file: !358, line: 930, type: !677, scopeLine: 930, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!677 = !DISubroutineType(types: !678)
!678 = !{!360, !511}
!679 = !DISubprogram(name: "length", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6lengthEv", scope: !354, file: !358, line: 936, type: !677, scopeLine: 936, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!680 = !DISubprogram(name: "max_size", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE8max_sizeEv", scope: !354, file: !358, line: 941, type: !677, scopeLine: 941, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!681 = !DISubprogram(name: "resize", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6resizeEmc", scope: !354, file: !358, line: 955, type: !536, scopeLine: 955, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!682 = !DISubprogram(name: "resize", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6resizeEm", scope: !354, file: !358, line: 968, type: !506, scopeLine: 968, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!683 = !DISubprogram(name: "shrink_to_fit", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13shrink_to_fitEv", scope: !354, file: !358, line: 974, type: !532, scopeLine: 974, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!684 = !DISubprogram(name: "capacity", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE8capacityEv", scope: !354, file: !358, line: 993, type: !677, scopeLine: 993, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!685 = !DISubprogram(name: "reserve", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEm", scope: !354, file: !358, line: 1017, type: !506, scopeLine: 1017, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!686 = !DISubprogram(name: "clear", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5clearEv", scope: !354, file: !358, line: 1023, type: !532, scopeLine: 1023, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!687 = !DISubprogram(name: "empty", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5emptyEv", scope: !354, file: !358, line: 1031, type: !525, scopeLine: 1031, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!688 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEixEm", scope: !354, file: !358, line: 1046, type: !689, scopeLine: 1046, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!689 = !DISubroutineType(types: !690)
!690 = !{!691, !511, !360}
!691 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !354, file: !358, line: 91, baseType: !692)
!692 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !363, file: !362, line: 65, baseType: !693)
!693 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !694, size: 64)
!694 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !695)
!695 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !363, file: !362, line: 58, baseType: !696)
!696 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !366, file: !367, line: 389, baseType: !374)
!697 = !DISubprogram(name: "operator[]", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEixEm", scope: !354, file: !358, line: 1063, type: !698, scopeLine: 1063, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!698 = !DISubroutineType(types: !699)
!699 = !{!700, !504, !360}
!700 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !354, file: !358, line: 90, baseType: !701)
!701 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !363, file: !362, line: 64, baseType: !702)
!702 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !695, size: 64)
!703 = !DISubprogram(name: "at", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE2atEm", scope: !354, file: !358, line: 1084, type: !689, scopeLine: 1084, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!704 = !DISubprogram(name: "at", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE2atEm", scope: !354, file: !358, line: 1105, type: !698, scopeLine: 1105, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!705 = !DISubprogram(name: "front", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5frontEv", scope: !354, file: !358, line: 1121, type: !706, scopeLine: 1121, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!706 = !DISubroutineType(types: !707)
!707 = !{!700, !504}
!708 = !DISubprogram(name: "front", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5frontEv", scope: !354, file: !358, line: 1132, type: !709, scopeLine: 1132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!709 = !DISubroutineType(types: !710)
!710 = !{!691, !511}
!711 = !DISubprogram(name: "back", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4backEv", scope: !354, file: !358, line: 1143, type: !706, scopeLine: 1143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!712 = !DISubprogram(name: "back", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4backEv", scope: !354, file: !358, line: 1154, type: !709, scopeLine: 1154, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!713 = !DISubprogram(name: "operator+=", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEpLERKS4_", scope: !354, file: !358, line: 1168, type: !637, scopeLine: 1168, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!714 = !DISubprogram(name: "operator+=", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEpLEPKc", scope: !354, file: !358, line: 1177, type: !641, scopeLine: 1177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!715 = !DISubprogram(name: "operator+=", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEpLEc", scope: !354, file: !358, line: 1186, type: !644, scopeLine: 1186, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!716 = !DISubprogram(name: "operator+=", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEpLESt16initializer_listIcE", scope: !354, file: !358, line: 1199, type: !650, scopeLine: 1199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!717 = !DISubprogram(name: "append", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendERKS4_", scope: !354, file: !358, line: 1221, type: !637, scopeLine: 1221, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!718 = !DISubprogram(name: "append", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendERKS4_mm", scope: !354, file: !358, line: 1238, type: !719, scopeLine: 1238, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!719 = !DISubroutineType(types: !720)
!720 = !{!639, !504, !590, !360, !360}
!721 = !DISubprogram(name: "append", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEPKcm", scope: !354, file: !358, line: 1250, type: !722, scopeLine: 1250, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!722 = !DISubroutineType(types: !723)
!723 = !{!639, !504, !407, !360}
!724 = !DISubprogram(name: "append", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEPKc", scope: !354, file: !358, line: 1263, type: !641, scopeLine: 1263, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!725 = !DISubprogram(name: "append", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEmc", scope: !354, file: !358, line: 1280, type: !726, scopeLine: 1280, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!726 = !DISubroutineType(types: !727)
!727 = !{!639, !504, !360, !374}
!728 = !DISubprogram(name: "append", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendESt16initializer_listIcE", scope: !354, file: !358, line: 1290, type: !650, scopeLine: 1290, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!729 = !DISubprogram(name: "push_back", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9push_backEc", scope: !354, file: !358, line: 1349, type: !730, scopeLine: 1349, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!730 = !DISubroutineType(types: !731)
!731 = !{null, !504, !374}
!732 = !DISubprogram(name: "assign", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6assignERKS4_", scope: !354, file: !358, line: 1364, type: !637, scopeLine: 1364, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!733 = !DISubprogram(name: "assign", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6assignEOS4_", scope: !354, file: !358, line: 1380, type: !647, scopeLine: 1380, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!734 = !DISubprogram(name: "assign", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6assignERKS4_mm", scope: !354, file: !358, line: 1403, type: !719, scopeLine: 1403, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!735 = !DISubprogram(name: "assign", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6assignEPKcm", scope: !354, file: !358, line: 1419, type: !722, scopeLine: 1419, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!736 = !DISubprogram(name: "assign", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6assignEPKc", scope: !354, file: !358, line: 1435, type: !641, scopeLine: 1435, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!737 = !DISubprogram(name: "assign", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6assignEmc", scope: !354, file: !358, line: 1452, type: !726, scopeLine: 1452, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!738 = !DISubprogram(name: "assign", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6assignESt16initializer_listIcE", scope: !354, file: !358, line: 1480, type: !650, scopeLine: 1480, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!739 = !DISubprogram(name: "insert", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6insertEN9__gnu_cxx17__normal_iteratorIPKcS4_EEmc", scope: !354, file: !358, line: 1533, type: !740, scopeLine: 1533, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!740 = !DISubroutineType(types: !741)
!741 = !{!570, !504, !576, !360, !374}
!742 = !DISubprogram(name: "insert", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6insertEN9__gnu_cxx17__normal_iteratorIPcS4_EESt16initializer_listIcE", scope: !354, file: !358, line: 1611, type: !743, scopeLine: 1611, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!743 = !DISubroutineType(types: !744)
!744 = !{null, !504, !570, !627}
!745 = !DISubprogram(name: "insert", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6insertEmRKS4_", scope: !354, file: !358, line: 1631, type: !746, scopeLine: 1631, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!746 = !DISubroutineType(types: !747)
!747 = !{!639, !504, !360, !590}
!748 = !DISubprogram(name: "insert", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6insertEmRKS4_mm", scope: !354, file: !358, line: 1654, type: !749, scopeLine: 1654, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!749 = !DISubroutineType(types: !750)
!750 = !{!639, !504, !360, !590, !360, !360}
!751 = !DISubprogram(name: "insert", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6insertEmPKcm", scope: !354, file: !358, line: 1677, type: !752, scopeLine: 1677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!752 = !DISubroutineType(types: !753)
!753 = !{!639, !504, !360, !407, !360}
!754 = !DISubprogram(name: "insert", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6insertEmPKc", scope: !354, file: !358, line: 1696, type: !755, scopeLine: 1696, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!755 = !DISubroutineType(types: !756)
!756 = !{!639, !504, !360, !407}
!757 = !DISubprogram(name: "insert", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6insertEmmc", scope: !354, file: !358, line: 1720, type: !758, scopeLine: 1720, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!758 = !DISubroutineType(types: !759)
!759 = !{!639, !504, !360, !360, !374}
!760 = !DISubprogram(name: "insert", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6insertEN9__gnu_cxx17__normal_iteratorIPKcS4_EEc", scope: !354, file: !358, line: 1738, type: !761, scopeLine: 1738, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!761 = !DISubroutineType(types: !762)
!762 = !{!570, !504, !763, !374}
!763 = !DIDerivedType(tag: DW_TAG_typedef, name: "__const_iterator", scope: !354, file: !358, line: 108, baseType: !576)
!764 = !DISubprogram(name: "erase", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5eraseEmm", scope: !354, file: !358, line: 1798, type: !765, scopeLine: 1798, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!765 = !DISubroutineType(types: !766)
!766 = !{!639, !504, !360, !360}
!767 = !DISubprogram(name: "erase", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5eraseEN9__gnu_cxx17__normal_iteratorIPKcS4_EE", scope: !354, file: !358, line: 1817, type: !768, scopeLine: 1817, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!768 = !DISubroutineType(types: !769)
!769 = !{!570, !504, !763}
!770 = !DISubprogram(name: "erase", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5eraseEN9__gnu_cxx17__normal_iteratorIPKcS4_EES9_", scope: !354, file: !358, line: 1836, type: !771, scopeLine: 1836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!771 = !DISubroutineType(types: !772)
!772 = !{!570, !504, !763, !763}
!773 = !DISubprogram(name: "pop_back", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE8pop_backEv", scope: !354, file: !358, line: 1855, type: !532, scopeLine: 1855, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!774 = !DISubprogram(name: "replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEmmRKS4_", scope: !354, file: !358, line: 1880, type: !775, scopeLine: 1880, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!775 = !DISubroutineType(types: !776)
!776 = !{!639, !504, !360, !360, !590}
!777 = !DISubprogram(name: "replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEmmRKS4_mm", scope: !354, file: !358, line: 1902, type: !778, scopeLine: 1902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!778 = !DISubroutineType(types: !779)
!779 = !{!639, !504, !360, !360, !590, !360, !360}
!780 = !DISubprogram(name: "replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEmmPKcm", scope: !354, file: !358, line: 1927, type: !781, scopeLine: 1927, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!781 = !DISubroutineType(types: !782)
!782 = !{!639, !504, !360, !360, !407, !360}
!783 = !DISubprogram(name: "replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEmmPKc", scope: !354, file: !358, line: 1952, type: !784, scopeLine: 1952, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!784 = !DISubroutineType(types: !785)
!785 = !{!639, !504, !360, !360, !407}
!786 = !DISubprogram(name: "replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEmmmc", scope: !354, file: !358, line: 1976, type: !787, scopeLine: 1976, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!787 = !DISubroutineType(types: !788)
!788 = !{!639, !504, !360, !360, !360, !374}
!789 = !DISubprogram(name: "replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEN9__gnu_cxx17__normal_iteratorIPKcS4_EES9_RKS4_", scope: !354, file: !358, line: 1994, type: !790, scopeLine: 1994, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!790 = !DISubroutineType(types: !791)
!791 = !{!639, !504, !763, !763, !590}
!792 = !DISubprogram(name: "replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEN9__gnu_cxx17__normal_iteratorIPKcS4_EES9_S8_m", scope: !354, file: !358, line: 2014, type: !793, scopeLine: 2014, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!793 = !DISubroutineType(types: !794)
!794 = !{!639, !504, !763, !763, !407, !360}
!795 = !DISubprogram(name: "replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEN9__gnu_cxx17__normal_iteratorIPKcS4_EES9_S8_", scope: !354, file: !358, line: 2036, type: !796, scopeLine: 2036, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!796 = !DISubroutineType(types: !797)
!797 = !{!639, !504, !763, !763, !407}
!798 = !DISubprogram(name: "replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEN9__gnu_cxx17__normal_iteratorIPKcS4_EES9_mc", scope: !354, file: !358, line: 2057, type: !799, scopeLine: 2057, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!799 = !DISubroutineType(types: !800)
!800 = !{!639, !504, !763, !763, !360, !374}
!801 = !DISubprogram(name: "replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEN9__gnu_cxx17__normal_iteratorIPKcS4_EES9_PcSA_", scope: !354, file: !358, line: 2114, type: !802, scopeLine: 2114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!802 = !DISubroutineType(types: !803)
!803 = !{!639, !504, !763, !763, !373, !373}
!804 = !DISubprogram(name: "replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEN9__gnu_cxx17__normal_iteratorIPKcS4_EES9_S8_S8_", scope: !354, file: !358, line: 2125, type: !805, scopeLine: 2125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!805 = !DISubroutineType(types: !806)
!806 = !{!639, !504, !763, !763, !407, !407}
!807 = !DISubprogram(name: "replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEN9__gnu_cxx17__normal_iteratorIPKcS4_EES9_NS6_IPcS4_EESB_", scope: !354, file: !358, line: 2136, type: !808, scopeLine: 2136, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!808 = !DISubroutineType(types: !809)
!809 = !{!639, !504, !763, !763, !570, !570}
!810 = !DISubprogram(name: "replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEN9__gnu_cxx17__normal_iteratorIPKcS4_EES9_S9_S9_", scope: !354, file: !358, line: 2147, type: !811, scopeLine: 2147, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!811 = !DISubroutineType(types: !812)
!812 = !{!639, !504, !763, !763, !576, !576}
!813 = !DISubprogram(name: "replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEN9__gnu_cxx17__normal_iteratorIPKcS4_EES9_St16initializer_listIcE", scope: !354, file: !358, line: 2172, type: !814, scopeLine: 2172, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!814 = !DISubroutineType(types: !815)
!815 = !{!639, !504, !576, !576, !627}
!816 = !DISubprogram(name: "_M_replace_aux", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE14_M_replace_auxEmmmc", scope: !354, file: !358, line: 2245, type: !787, scopeLine: 2245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!817 = !DISubprogram(name: "_M_replace", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEmmPKcm", scope: !354, file: !358, line: 2249, type: !818, scopeLine: 2249, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!818 = !DISubroutineType(types: !819)
!819 = !{!639, !504, !360, !360, !407, !359}
!820 = !DISubprogram(name: "_M_append", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm", scope: !354, file: !358, line: 2253, type: !722, scopeLine: 2253, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!821 = !DISubprogram(name: "copy", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4copyEPcmm", scope: !354, file: !358, line: 2270, type: !822, scopeLine: 2270, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!822 = !DISubroutineType(types: !823)
!823 = !{!360, !511, !373, !360, !360}
!824 = !DISubprogram(name: "swap", linkageName: "_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4swapERS4_", scope: !354, file: !358, line: 2280, type: !825, scopeLine: 2280, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!825 = !DISubroutineType(types: !826)
!826 = !{null, !504, !639}
!827 = !DISubprogram(name: "c_str", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5c_strEv", scope: !354, file: !358, line: 2290, type: !828, scopeLine: 2290, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!828 = !DISubroutineType(types: !829)
!829 = !{!407, !511}
!830 = !DISubprogram(name: "data", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4dataEv", scope: !354, file: !358, line: 2302, type: !828, scopeLine: 2302, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!831 = !DISubprogram(name: "get_allocator", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13get_allocatorEv", scope: !354, file: !358, line: 2321, type: !832, scopeLine: 2321, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!832 = !DISubroutineType(types: !833)
!833 = !{!475, !511}
!834 = !DISubprogram(name: "find", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcmm", scope: !354, file: !358, line: 2337, type: !835, scopeLine: 2337, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!835 = !DISubroutineType(types: !836)
!836 = !{!360, !511, !407, !360, !360}
!837 = !DISubprogram(name: "find", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findERKS4_m", scope: !354, file: !358, line: 2351, type: !838, scopeLine: 2351, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!838 = !DISubroutineType(types: !839)
!839 = !{!360, !511, !590, !360}
!840 = !DISubprogram(name: "find", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcm", scope: !354, file: !358, line: 2383, type: !841, scopeLine: 2383, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!841 = !DISubroutineType(types: !842)
!842 = !{!360, !511, !407, !360}
!843 = !DISubprogram(name: "find", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEcm", scope: !354, file: !358, line: 2400, type: !844, scopeLine: 2400, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!844 = !DISubroutineType(types: !845)
!845 = !{!360, !511, !374, !360}
!846 = !DISubprogram(name: "rfind", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5rfindERKS4_m", scope: !354, file: !358, line: 2413, type: !838, scopeLine: 2413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!847 = !DISubprogram(name: "rfind", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5rfindEPKcmm", scope: !354, file: !358, line: 2447, type: !835, scopeLine: 2447, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!848 = !DISubprogram(name: "rfind", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5rfindEPKcm", scope: !354, file: !358, line: 2461, type: !841, scopeLine: 2461, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!849 = !DISubprogram(name: "rfind", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5rfindEcm", scope: !354, file: !358, line: 2478, type: !844, scopeLine: 2478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!850 = !DISubprogram(name: "find_first_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13find_first_ofERKS4_m", scope: !354, file: !358, line: 2492, type: !838, scopeLine: 2492, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!851 = !DISubprogram(name: "find_first_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13find_first_ofEPKcmm", scope: !354, file: !358, line: 2527, type: !835, scopeLine: 2527, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!852 = !DISubprogram(name: "find_first_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13find_first_ofEPKcm", scope: !354, file: !358, line: 2541, type: !841, scopeLine: 2541, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!853 = !DISubprogram(name: "find_first_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13find_first_ofEcm", scope: !354, file: !358, line: 2561, type: !844, scopeLine: 2561, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!854 = !DISubprogram(name: "find_last_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12find_last_ofERKS4_m", scope: !354, file: !358, line: 2576, type: !838, scopeLine: 2576, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!855 = !DISubprogram(name: "find_last_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12find_last_ofEPKcmm", scope: !354, file: !358, line: 2611, type: !835, scopeLine: 2611, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!856 = !DISubprogram(name: "find_last_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12find_last_ofEPKcm", scope: !354, file: !358, line: 2625, type: !841, scopeLine: 2625, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!857 = !DISubprogram(name: "find_last_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12find_last_ofEcm", scope: !354, file: !358, line: 2645, type: !844, scopeLine: 2645, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!858 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE17find_first_not_ofERKS4_m", scope: !354, file: !358, line: 2659, type: !838, scopeLine: 2659, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!859 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE17find_first_not_ofEPKcmm", scope: !354, file: !358, line: 2694, type: !835, scopeLine: 2694, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!860 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE17find_first_not_ofEPKcm", scope: !354, file: !358, line: 2708, type: !841, scopeLine: 2708, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!861 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE17find_first_not_ofEcm", scope: !354, file: !358, line: 2726, type: !844, scopeLine: 2726, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!862 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE16find_last_not_ofERKS4_m", scope: !354, file: !358, line: 2741, type: !838, scopeLine: 2741, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!863 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE16find_last_not_ofEPKcmm", scope: !354, file: !358, line: 2776, type: !835, scopeLine: 2776, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!864 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE16find_last_not_ofEPKcm", scope: !354, file: !358, line: 2790, type: !841, scopeLine: 2790, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!865 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE16find_last_not_ofEcm", scope: !354, file: !358, line: 2808, type: !844, scopeLine: 2808, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!866 = !DISubprogram(name: "substr", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6substrEmm", scope: !354, file: !358, line: 2824, type: !867, scopeLine: 2824, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!867 = !DISubroutineType(types: !868)
!868 = !{!354, !511, !360, !360}
!869 = !DISubprogram(name: "compare", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_", scope: !354, file: !358, line: 2843, type: !870, scopeLine: 2843, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!870 = !DISubroutineType(types: !871)
!871 = !{!324, !511, !590}
!872 = !DISubprogram(name: "compare", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEmmRKS4_", scope: !354, file: !358, line: 2936, type: !873, scopeLine: 2936, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!873 = !DISubroutineType(types: !874)
!874 = !{!324, !511, !360, !360, !590}
!875 = !DISubprogram(name: "compare", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEmmRKS4_mm", scope: !354, file: !358, line: 2962, type: !876, scopeLine: 2962, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!876 = !DISubroutineType(types: !877)
!877 = !{!324, !511, !360, !360, !590, !360, !360}
!878 = !DISubprogram(name: "compare", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc", scope: !354, file: !358, line: 2980, type: !879, scopeLine: 2980, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!879 = !DISubroutineType(types: !880)
!880 = !{!324, !511, !407}
!881 = !DISubprogram(name: "compare", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEmmPKc", scope: !354, file: !358, line: 3004, type: !882, scopeLine: 3004, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!882 = !DISubroutineType(types: !883)
!883 = !{!324, !511, !360, !360, !407}
!884 = !DISubprogram(name: "compare", linkageName: "_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEmmPKcm", scope: !354, file: !358, line: 3031, type: !885, scopeLine: 3031, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!885 = !DISubroutineType(types: !886)
!886 = !{!324, !511, !360, !360, !407, !360}
!887 = !{!888, !889, !454}
!888 = !DITemplateTypeParameter(name: "_CharT", type: !374)
!889 = !DITemplateTypeParameter(name: "_Traits", type: !890)
!890 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "char_traits<char>", scope: !353, file: !891, line: 277, size: 8, flags: DIFlagTypePassByValue, elements: !892, templateParams: !940, identifier: "_ZTSSt11char_traitsIcE")
!891 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/char_traits.h", directory: "")
!892 = !{!893, !900, !903, !904, !908, !911, !914, !918, !919, !922, !928, !931, !934, !937}
!893 = !DISubprogram(name: "assign", linkageName: "_ZNSt11char_traitsIcE6assignERcRKc", scope: !890, file: !891, line: 286, type: !894, scopeLine: 286, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!894 = !DISubroutineType(types: !895)
!895 = !{null, !896, !898}
!896 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !897, size: 64)
!897 = !DIDerivedType(tag: DW_TAG_typedef, name: "char_type", scope: !890, file: !891, line: 279, baseType: !374)
!898 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !899, size: 64)
!899 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !897)
!900 = !DISubprogram(name: "eq", linkageName: "_ZNSt11char_traitsIcE2eqERKcS2_", scope: !890, file: !891, line: 290, type: !901, scopeLine: 290, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!901 = !DISubroutineType(types: !902)
!902 = !{!308, !898, !898}
!903 = !DISubprogram(name: "lt", linkageName: "_ZNSt11char_traitsIcE2ltERKcS2_", scope: !890, file: !891, line: 294, type: !901, scopeLine: 294, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!904 = !DISubprogram(name: "compare", linkageName: "_ZNSt11char_traitsIcE7compareEPKcS2_m", scope: !890, file: !891, line: 302, type: !905, scopeLine: 302, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!905 = !DISubroutineType(types: !906)
!906 = !{!324, !907, !907, !415}
!907 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !899, size: 64)
!908 = !DISubprogram(name: "length", linkageName: "_ZNSt11char_traitsIcE6lengthEPKc", scope: !890, file: !891, line: 316, type: !909, scopeLine: 316, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!909 = !DISubroutineType(types: !910)
!910 = !{!415, !907}
!911 = !DISubprogram(name: "find", linkageName: "_ZNSt11char_traitsIcE4findEPKcmRS1_", scope: !890, file: !891, line: 326, type: !912, scopeLine: 326, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!912 = !DISubroutineType(types: !913)
!913 = !{!907, !907, !415, !898}
!914 = !DISubprogram(name: "move", linkageName: "_ZNSt11char_traitsIcE4moveEPcPKcm", scope: !890, file: !891, line: 340, type: !915, scopeLine: 340, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!915 = !DISubroutineType(types: !916)
!916 = !{!917, !917, !907, !415}
!917 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !897, size: 64)
!918 = !DISubprogram(name: "copy", linkageName: "_ZNSt11char_traitsIcE4copyEPcPKcm", scope: !890, file: !891, line: 348, type: !915, scopeLine: 348, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!919 = !DISubprogram(name: "assign", linkageName: "_ZNSt11char_traitsIcE6assignEPcmc", scope: !890, file: !891, line: 356, type: !920, scopeLine: 356, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!920 = !DISubroutineType(types: !921)
!921 = !{!917, !917, !415, !897}
!922 = !DISubprogram(name: "to_char_type", linkageName: "_ZNSt11char_traitsIcE12to_char_typeERKi", scope: !890, file: !891, line: 364, type: !923, scopeLine: 364, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!923 = !DISubroutineType(types: !924)
!924 = !{!897, !925}
!925 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !926, size: 64)
!926 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !927)
!927 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_type", scope: !890, file: !891, line: 280, baseType: !324)
!928 = !DISubprogram(name: "to_int_type", linkageName: "_ZNSt11char_traitsIcE11to_int_typeERKc", scope: !890, file: !891, line: 370, type: !929, scopeLine: 370, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!929 = !DISubroutineType(types: !930)
!930 = !{!927, !898}
!931 = !DISubprogram(name: "eq_int_type", linkageName: "_ZNSt11char_traitsIcE11eq_int_typeERKiS2_", scope: !890, file: !891, line: 374, type: !932, scopeLine: 374, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!932 = !DISubroutineType(types: !933)
!933 = !{!308, !925, !925}
!934 = !DISubprogram(name: "eof", linkageName: "_ZNSt11char_traitsIcE3eofEv", scope: !890, file: !891, line: 378, type: !935, scopeLine: 378, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!935 = !DISubroutineType(types: !936)
!936 = !{!927}
!937 = !DISubprogram(name: "not_eof", linkageName: "_ZNSt11char_traitsIcE7not_eofERKi", scope: !890, file: !891, line: 382, type: !938, scopeLine: 382, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!938 = !DISubroutineType(types: !939)
!939 = !{!927, !925}
!940 = !{!888}
!941 = !DISubprogram(name: "dump", linkageName: "_ZNK5clang14SourceLocation4dumpERKNS_13SourceManagerE", scope: !297, file: !298, line: 176, type: !942, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!942 = !DISubroutineType(types: !943)
!943 = !{null, !309, !343}
!944 = !DIDerivedType(tag: DW_TAG_member, name: "UintData", scope: !294, file: !293, line: 48, baseType: !6, size: 32, offset: 32)
!945 = !DIDerivedType(tag: DW_TAG_member, name: "PtrData", scope: !294, file: !293, line: 62, baseType: !330, size: 64, offset: 64)
!946 = !DIDerivedType(tag: DW_TAG_member, name: "Kind", scope: !294, file: !293, line: 66, baseType: !947, size: 16, offset: 128)
!947 = !DIBasicType(name: "unsigned short", size: 16, encoding: DW_ATE_unsigned)
!948 = !DIDerivedType(tag: DW_TAG_member, name: "Flags", scope: !294, file: !293, line: 69, baseType: !949, size: 8, offset: 144)
!949 = !DIBasicType(name: "unsigned char", size: 8, encoding: DW_ATE_unsigned_char)
!950 = !DISubprogram(name: "getKind", linkageName: "_ZNK5clang5Token7getKindEv", scope: !294, file: !293, line: 86, type: !951, scopeLine: 86, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!951 = !DISubroutineType(types: !952)
!952 = !{!953, !1272}
!953 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "TokenKind", scope: !955, file: !954, line: 23, baseType: !6, size: 32, elements: !956, identifier: "_ZTSN5clang3tok9TokenKindE")
!954 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/TokenKinds.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "7eb12cb2b6682ea1941c3102d162293e")
!955 = !DINamespace(name: "tok", scope: !14)
!956 = !{!957, !958, !959, !960, !961, !962, !963, !964, !965, !966, !967, !968, !969, !970, !971, !972, !973, !974, !975, !976, !977, !978, !979, !980, !981, !982, !983, !984, !985, !986, !987, !988, !989, !990, !991, !992, !993, !994, !995, !996, !997, !998, !999, !1000, !1001, !1002, !1003, !1004, !1005, !1006, !1007, !1008, !1009, !1010, !1011, !1012, !1013, !1014, !1015, !1016, !1017, !1018, !1019, !1020, !1021, !1022, !1023, !1024, !1025, !1026, !1027, !1028, !1029, !1030, !1031, !1032, !1033, !1034, !1035, !1036, !1037, !1038, !1039, !1040, !1041, !1042, !1043, !1044, !1045, !1046, !1047, !1048, !1049, !1050, !1051, !1052, !1053, !1054, !1055, !1056, !1057, !1058, !1059, !1060, !1061, !1062, !1063, !1064, !1065, !1066, !1067, !1068, !1069, !1070, !1071, !1072, !1073, !1074, !1075, !1076, !1077, !1078, !1079, !1080, !1081, !1082, !1083, !1084, !1085, !1086, !1087, !1088, !1089, !1090, !1091, !1092, !1093, !1094, !1095, !1096, !1097, !1098, !1099, !1100, !1101, !1102, !1103, !1104, !1105, !1106, !1107, !1108, !1109, !1110, !1111, !1112, !1113, !1114, !1115, !1116, !1117, !1118, !1119, !1120, !1121, !1122, !1123, !1124, !1125, !1126, !1127, !1128, !1129, !1130, !1131, !1132, !1133, !1134, !1135, !1136, !1137, !1138, !1139, !1140, !1141, !1142, !1143, !1144, !1145, !1146, !1147, !1148, !1149, !1150, !1151, !1152, !1153, !1154, !1155, !1156, !1157, !1158, !1159, !1160, !1161, !1162, !1163, !1164, !1165, !1166, !1167, !1168, !1169, !1170, !1171, !1172, !1173, !1174, !1175, !1176, !1177, !1178, !1179, !1180, !1181, !1182, !1183, !1184, !1185, !1186, !1187, !1188, !1189, !1190, !1191, !1192, !1193, !1194, !1195, !1196, !1197, !1198, !1199, !1200, !1201, !1202, !1203, !1204, !1205, !1206, !1207, !1208, !1209, !1210, !1211, !1212, !1213, !1214, !1215, !1216, !1217, !1218, !1219, !1220, !1221, !1222, !1223, !1224, !1225, !1226, !1227, !1228, !1229, !1230, !1231, !1232, !1233, !1234, !1235, !1236, !1237, !1238, !1239, !1240, !1241, !1242, !1243, !1244, !1245, !1246, !1247, !1248, !1249, !1250, !1251, !1252, !1253, !1254, !1255, !1256, !1257, !1258, !1259, !1260, !1261, !1262, !1263, !1264, !1265, !1266, !1267, !1268, !1269, !1270, !1271}
!957 = !DIEnumerator(name: "unknown", value: 0, isUnsigned: true)
!958 = !DIEnumerator(name: "eof", value: 1, isUnsigned: true)
!959 = !DIEnumerator(name: "eod", value: 2, isUnsigned: true)
!960 = !DIEnumerator(name: "code_completion", value: 3, isUnsigned: true)
!961 = !DIEnumerator(name: "cxx_defaultarg_end", value: 4, isUnsigned: true)
!962 = !DIEnumerator(name: "comment", value: 5, isUnsigned: true)
!963 = !DIEnumerator(name: "identifier", value: 6, isUnsigned: true)
!964 = !DIEnumerator(name: "raw_identifier", value: 7, isUnsigned: true)
!965 = !DIEnumerator(name: "numeric_constant", value: 8, isUnsigned: true)
!966 = !DIEnumerator(name: "char_constant", value: 9, isUnsigned: true)
!967 = !DIEnumerator(name: "wide_char_constant", value: 10, isUnsigned: true)
!968 = !DIEnumerator(name: "utf16_char_constant", value: 11, isUnsigned: true)
!969 = !DIEnumerator(name: "utf32_char_constant", value: 12, isUnsigned: true)
!970 = !DIEnumerator(name: "string_literal", value: 13, isUnsigned: true)
!971 = !DIEnumerator(name: "wide_string_literal", value: 14, isUnsigned: true)
!972 = !DIEnumerator(name: "angle_string_literal", value: 15, isUnsigned: true)
!973 = !DIEnumerator(name: "utf8_string_literal", value: 16, isUnsigned: true)
!974 = !DIEnumerator(name: "utf16_string_literal", value: 17, isUnsigned: true)
!975 = !DIEnumerator(name: "utf32_string_literal", value: 18, isUnsigned: true)
!976 = !DIEnumerator(name: "l_square", value: 19, isUnsigned: true)
!977 = !DIEnumerator(name: "r_square", value: 20, isUnsigned: true)
!978 = !DIEnumerator(name: "l_paren", value: 21, isUnsigned: true)
!979 = !DIEnumerator(name: "r_paren", value: 22, isUnsigned: true)
!980 = !DIEnumerator(name: "l_brace", value: 23, isUnsigned: true)
!981 = !DIEnumerator(name: "r_brace", value: 24, isUnsigned: true)
!982 = !DIEnumerator(name: "period", value: 25, isUnsigned: true)
!983 = !DIEnumerator(name: "ellipsis", value: 26, isUnsigned: true)
!984 = !DIEnumerator(name: "amp", value: 27, isUnsigned: true)
!985 = !DIEnumerator(name: "ampamp", value: 28, isUnsigned: true)
!986 = !DIEnumerator(name: "ampequal", value: 29, isUnsigned: true)
!987 = !DIEnumerator(name: "star", value: 30, isUnsigned: true)
!988 = !DIEnumerator(name: "starequal", value: 31, isUnsigned: true)
!989 = !DIEnumerator(name: "plus", value: 32, isUnsigned: true)
!990 = !DIEnumerator(name: "plusplus", value: 33, isUnsigned: true)
!991 = !DIEnumerator(name: "plusequal", value: 34, isUnsigned: true)
!992 = !DIEnumerator(name: "minus", value: 35, isUnsigned: true)
!993 = !DIEnumerator(name: "arrow", value: 36, isUnsigned: true)
!994 = !DIEnumerator(name: "minusminus", value: 37, isUnsigned: true)
!995 = !DIEnumerator(name: "minusequal", value: 38, isUnsigned: true)
!996 = !DIEnumerator(name: "tilde", value: 39, isUnsigned: true)
!997 = !DIEnumerator(name: "exclaim", value: 40, isUnsigned: true)
!998 = !DIEnumerator(name: "exclaimequal", value: 41, isUnsigned: true)
!999 = !DIEnumerator(name: "slash", value: 42, isUnsigned: true)
!1000 = !DIEnumerator(name: "slashequal", value: 43, isUnsigned: true)
!1001 = !DIEnumerator(name: "percent", value: 44, isUnsigned: true)
!1002 = !DIEnumerator(name: "percentequal", value: 45, isUnsigned: true)
!1003 = !DIEnumerator(name: "less", value: 46, isUnsigned: true)
!1004 = !DIEnumerator(name: "lessless", value: 47, isUnsigned: true)
!1005 = !DIEnumerator(name: "lessequal", value: 48, isUnsigned: true)
!1006 = !DIEnumerator(name: "lesslessequal", value: 49, isUnsigned: true)
!1007 = !DIEnumerator(name: "greater", value: 50, isUnsigned: true)
!1008 = !DIEnumerator(name: "greatergreater", value: 51, isUnsigned: true)
!1009 = !DIEnumerator(name: "greaterequal", value: 52, isUnsigned: true)
!1010 = !DIEnumerator(name: "greatergreaterequal", value: 53, isUnsigned: true)
!1011 = !DIEnumerator(name: "caret", value: 54, isUnsigned: true)
!1012 = !DIEnumerator(name: "caretequal", value: 55, isUnsigned: true)
!1013 = !DIEnumerator(name: "pipe", value: 56, isUnsigned: true)
!1014 = !DIEnumerator(name: "pipepipe", value: 57, isUnsigned: true)
!1015 = !DIEnumerator(name: "pipeequal", value: 58, isUnsigned: true)
!1016 = !DIEnumerator(name: "question", value: 59, isUnsigned: true)
!1017 = !DIEnumerator(name: "colon", value: 60, isUnsigned: true)
!1018 = !DIEnumerator(name: "semi", value: 61, isUnsigned: true)
!1019 = !DIEnumerator(name: "equal", value: 62, isUnsigned: true)
!1020 = !DIEnumerator(name: "equalequal", value: 63, isUnsigned: true)
!1021 = !DIEnumerator(name: "comma", value: 64, isUnsigned: true)
!1022 = !DIEnumerator(name: "hash", value: 65, isUnsigned: true)
!1023 = !DIEnumerator(name: "hashhash", value: 66, isUnsigned: true)
!1024 = !DIEnumerator(name: "hashat", value: 67, isUnsigned: true)
!1025 = !DIEnumerator(name: "periodstar", value: 68, isUnsigned: true)
!1026 = !DIEnumerator(name: "arrowstar", value: 69, isUnsigned: true)
!1027 = !DIEnumerator(name: "coloncolon", value: 70, isUnsigned: true)
!1028 = !DIEnumerator(name: "at", value: 71, isUnsigned: true)
!1029 = !DIEnumerator(name: "lesslessless", value: 72, isUnsigned: true)
!1030 = !DIEnumerator(name: "greatergreatergreater", value: 73, isUnsigned: true)
!1031 = !DIEnumerator(name: "kw_auto", value: 74, isUnsigned: true)
!1032 = !DIEnumerator(name: "kw_break", value: 75, isUnsigned: true)
!1033 = !DIEnumerator(name: "kw_case", value: 76, isUnsigned: true)
!1034 = !DIEnumerator(name: "kw_char", value: 77, isUnsigned: true)
!1035 = !DIEnumerator(name: "kw_const", value: 78, isUnsigned: true)
!1036 = !DIEnumerator(name: "kw_continue", value: 79, isUnsigned: true)
!1037 = !DIEnumerator(name: "kw_default", value: 80, isUnsigned: true)
!1038 = !DIEnumerator(name: "kw_do", value: 81, isUnsigned: true)
!1039 = !DIEnumerator(name: "kw_double", value: 82, isUnsigned: true)
!1040 = !DIEnumerator(name: "kw_else", value: 83, isUnsigned: true)
!1041 = !DIEnumerator(name: "kw_enum", value: 84, isUnsigned: true)
!1042 = !DIEnumerator(name: "kw_extern", value: 85, isUnsigned: true)
!1043 = !DIEnumerator(name: "kw_float", value: 86, isUnsigned: true)
!1044 = !DIEnumerator(name: "kw_for", value: 87, isUnsigned: true)
!1045 = !DIEnumerator(name: "kw_goto", value: 88, isUnsigned: true)
!1046 = !DIEnumerator(name: "kw_if", value: 89, isUnsigned: true)
!1047 = !DIEnumerator(name: "kw_inline", value: 90, isUnsigned: true)
!1048 = !DIEnumerator(name: "kw_int", value: 91, isUnsigned: true)
!1049 = !DIEnumerator(name: "kw_long", value: 92, isUnsigned: true)
!1050 = !DIEnumerator(name: "kw_register", value: 93, isUnsigned: true)
!1051 = !DIEnumerator(name: "kw_restrict", value: 94, isUnsigned: true)
!1052 = !DIEnumerator(name: "kw_return", value: 95, isUnsigned: true)
!1053 = !DIEnumerator(name: "kw_short", value: 96, isUnsigned: true)
!1054 = !DIEnumerator(name: "kw_signed", value: 97, isUnsigned: true)
!1055 = !DIEnumerator(name: "kw_sizeof", value: 98, isUnsigned: true)
!1056 = !DIEnumerator(name: "kw_static", value: 99, isUnsigned: true)
!1057 = !DIEnumerator(name: "kw_struct", value: 100, isUnsigned: true)
!1058 = !DIEnumerator(name: "kw_switch", value: 101, isUnsigned: true)
!1059 = !DIEnumerator(name: "kw_typedef", value: 102, isUnsigned: true)
!1060 = !DIEnumerator(name: "kw_union", value: 103, isUnsigned: true)
!1061 = !DIEnumerator(name: "kw_unsigned", value: 104, isUnsigned: true)
!1062 = !DIEnumerator(name: "kw_void", value: 105, isUnsigned: true)
!1063 = !DIEnumerator(name: "kw_volatile", value: 106, isUnsigned: true)
!1064 = !DIEnumerator(name: "kw_while", value: 107, isUnsigned: true)
!1065 = !DIEnumerator(name: "kw__Alignas", value: 108, isUnsigned: true)
!1066 = !DIEnumerator(name: "kw__Alignof", value: 109, isUnsigned: true)
!1067 = !DIEnumerator(name: "kw__Atomic", value: 110, isUnsigned: true)
!1068 = !DIEnumerator(name: "kw__Bool", value: 111, isUnsigned: true)
!1069 = !DIEnumerator(name: "kw__Complex", value: 112, isUnsigned: true)
!1070 = !DIEnumerator(name: "kw__Generic", value: 113, isUnsigned: true)
!1071 = !DIEnumerator(name: "kw__Imaginary", value: 114, isUnsigned: true)
!1072 = !DIEnumerator(name: "kw__Noreturn", value: 115, isUnsigned: true)
!1073 = !DIEnumerator(name: "kw__Static_assert", value: 116, isUnsigned: true)
!1074 = !DIEnumerator(name: "kw__Thread_local", value: 117, isUnsigned: true)
!1075 = !DIEnumerator(name: "kw___func__", value: 118, isUnsigned: true)
!1076 = !DIEnumerator(name: "kw___objc_yes", value: 119, isUnsigned: true)
!1077 = !DIEnumerator(name: "kw___objc_no", value: 120, isUnsigned: true)
!1078 = !DIEnumerator(name: "kw_asm", value: 121, isUnsigned: true)
!1079 = !DIEnumerator(name: "kw_bool", value: 122, isUnsigned: true)
!1080 = !DIEnumerator(name: "kw_catch", value: 123, isUnsigned: true)
!1081 = !DIEnumerator(name: "kw_class", value: 124, isUnsigned: true)
!1082 = !DIEnumerator(name: "kw_const_cast", value: 125, isUnsigned: true)
!1083 = !DIEnumerator(name: "kw_delete", value: 126, isUnsigned: true)
!1084 = !DIEnumerator(name: "kw_dynamic_cast", value: 127, isUnsigned: true)
!1085 = !DIEnumerator(name: "kw_explicit", value: 128, isUnsigned: true)
!1086 = !DIEnumerator(name: "kw_export", value: 129, isUnsigned: true)
!1087 = !DIEnumerator(name: "kw_false", value: 130, isUnsigned: true)
!1088 = !DIEnumerator(name: "kw_friend", value: 131, isUnsigned: true)
!1089 = !DIEnumerator(name: "kw_mutable", value: 132, isUnsigned: true)
!1090 = !DIEnumerator(name: "kw_namespace", value: 133, isUnsigned: true)
!1091 = !DIEnumerator(name: "kw_new", value: 134, isUnsigned: true)
!1092 = !DIEnumerator(name: "kw_operator", value: 135, isUnsigned: true)
!1093 = !DIEnumerator(name: "kw_private", value: 136, isUnsigned: true)
!1094 = !DIEnumerator(name: "kw_protected", value: 137, isUnsigned: true)
!1095 = !DIEnumerator(name: "kw_public", value: 138, isUnsigned: true)
!1096 = !DIEnumerator(name: "kw_reinterpret_cast", value: 139, isUnsigned: true)
!1097 = !DIEnumerator(name: "kw_static_cast", value: 140, isUnsigned: true)
!1098 = !DIEnumerator(name: "kw_template", value: 141, isUnsigned: true)
!1099 = !DIEnumerator(name: "kw_this", value: 142, isUnsigned: true)
!1100 = !DIEnumerator(name: "kw_throw", value: 143, isUnsigned: true)
!1101 = !DIEnumerator(name: "kw_true", value: 144, isUnsigned: true)
!1102 = !DIEnumerator(name: "kw_try", value: 145, isUnsigned: true)
!1103 = !DIEnumerator(name: "kw_typename", value: 146, isUnsigned: true)
!1104 = !DIEnumerator(name: "kw_typeid", value: 147, isUnsigned: true)
!1105 = !DIEnumerator(name: "kw_using", value: 148, isUnsigned: true)
!1106 = !DIEnumerator(name: "kw_virtual", value: 149, isUnsigned: true)
!1107 = !DIEnumerator(name: "kw_wchar_t", value: 150, isUnsigned: true)
!1108 = !DIEnumerator(name: "kw_alignas", value: 151, isUnsigned: true)
!1109 = !DIEnumerator(name: "kw_alignof", value: 152, isUnsigned: true)
!1110 = !DIEnumerator(name: "kw_char16_t", value: 153, isUnsigned: true)
!1111 = !DIEnumerator(name: "kw_char32_t", value: 154, isUnsigned: true)
!1112 = !DIEnumerator(name: "kw_constexpr", value: 155, isUnsigned: true)
!1113 = !DIEnumerator(name: "kw_decltype", value: 156, isUnsigned: true)
!1114 = !DIEnumerator(name: "kw_noexcept", value: 157, isUnsigned: true)
!1115 = !DIEnumerator(name: "kw_nullptr", value: 158, isUnsigned: true)
!1116 = !DIEnumerator(name: "kw_static_assert", value: 159, isUnsigned: true)
!1117 = !DIEnumerator(name: "kw_thread_local", value: 160, isUnsigned: true)
!1118 = !DIEnumerator(name: "kw__Decimal32", value: 161, isUnsigned: true)
!1119 = !DIEnumerator(name: "kw__Decimal64", value: 162, isUnsigned: true)
!1120 = !DIEnumerator(name: "kw__Decimal128", value: 163, isUnsigned: true)
!1121 = !DIEnumerator(name: "kw___null", value: 164, isUnsigned: true)
!1122 = !DIEnumerator(name: "kw___alignof", value: 165, isUnsigned: true)
!1123 = !DIEnumerator(name: "kw___attribute", value: 166, isUnsigned: true)
!1124 = !DIEnumerator(name: "kw___builtin_choose_expr", value: 167, isUnsigned: true)
!1125 = !DIEnumerator(name: "kw___builtin_offsetof", value: 168, isUnsigned: true)
!1126 = !DIEnumerator(name: "kw___builtin_types_compatible_p", value: 169, isUnsigned: true)
!1127 = !DIEnumerator(name: "kw___builtin_va_arg", value: 170, isUnsigned: true)
!1128 = !DIEnumerator(name: "kw___extension__", value: 171, isUnsigned: true)
!1129 = !DIEnumerator(name: "kw___imag", value: 172, isUnsigned: true)
!1130 = !DIEnumerator(name: "kw___int128", value: 173, isUnsigned: true)
!1131 = !DIEnumerator(name: "kw___label__", value: 174, isUnsigned: true)
!1132 = !DIEnumerator(name: "kw___real", value: 175, isUnsigned: true)
!1133 = !DIEnumerator(name: "kw___thread", value: 176, isUnsigned: true)
!1134 = !DIEnumerator(name: "kw___FUNCTION__", value: 177, isUnsigned: true)
!1135 = !DIEnumerator(name: "kw___PRETTY_FUNCTION__", value: 178, isUnsigned: true)
!1136 = !DIEnumerator(name: "kw_typeof", value: 179, isUnsigned: true)
!1137 = !DIEnumerator(name: "kw___FUNCDNAME__", value: 180, isUnsigned: true)
!1138 = !DIEnumerator(name: "kw_L__FUNCTION__", value: 181, isUnsigned: true)
!1139 = !DIEnumerator(name: "kw___is_interface_class", value: 182, isUnsigned: true)
!1140 = !DIEnumerator(name: "kw___is_sealed", value: 183, isUnsigned: true)
!1141 = !DIEnumerator(name: "kw___has_nothrow_assign", value: 184, isUnsigned: true)
!1142 = !DIEnumerator(name: "kw___has_nothrow_move_assign", value: 185, isUnsigned: true)
!1143 = !DIEnumerator(name: "kw___has_nothrow_copy", value: 186, isUnsigned: true)
!1144 = !DIEnumerator(name: "kw___has_nothrow_constructor", value: 187, isUnsigned: true)
!1145 = !DIEnumerator(name: "kw___has_trivial_assign", value: 188, isUnsigned: true)
!1146 = !DIEnumerator(name: "kw___has_trivial_move_assign", value: 189, isUnsigned: true)
!1147 = !DIEnumerator(name: "kw___has_trivial_copy", value: 190, isUnsigned: true)
!1148 = !DIEnumerator(name: "kw___has_trivial_constructor", value: 191, isUnsigned: true)
!1149 = !DIEnumerator(name: "kw___has_trivial_move_constructor", value: 192, isUnsigned: true)
!1150 = !DIEnumerator(name: "kw___has_trivial_destructor", value: 193, isUnsigned: true)
!1151 = !DIEnumerator(name: "kw___has_virtual_destructor", value: 194, isUnsigned: true)
!1152 = !DIEnumerator(name: "kw___is_abstract", value: 195, isUnsigned: true)
!1153 = !DIEnumerator(name: "kw___is_base_of", value: 196, isUnsigned: true)
!1154 = !DIEnumerator(name: "kw___is_class", value: 197, isUnsigned: true)
!1155 = !DIEnumerator(name: "kw___is_convertible_to", value: 198, isUnsigned: true)
!1156 = !DIEnumerator(name: "kw___is_empty", value: 199, isUnsigned: true)
!1157 = !DIEnumerator(name: "kw___is_enum", value: 200, isUnsigned: true)
!1158 = !DIEnumerator(name: "kw___is_final", value: 201, isUnsigned: true)
!1159 = !DIEnumerator(name: "kw___is_literal", value: 202, isUnsigned: true)
!1160 = !DIEnumerator(name: "kw___is_literal_type", value: 203, isUnsigned: true)
!1161 = !DIEnumerator(name: "kw___is_pod", value: 204, isUnsigned: true)
!1162 = !DIEnumerator(name: "kw___is_polymorphic", value: 205, isUnsigned: true)
!1163 = !DIEnumerator(name: "kw___is_trivial", value: 206, isUnsigned: true)
!1164 = !DIEnumerator(name: "kw___is_union", value: 207, isUnsigned: true)
!1165 = !DIEnumerator(name: "kw___is_trivially_constructible", value: 208, isUnsigned: true)
!1166 = !DIEnumerator(name: "kw___is_trivially_copyable", value: 209, isUnsigned: true)
!1167 = !DIEnumerator(name: "kw___is_trivially_assignable", value: 210, isUnsigned: true)
!1168 = !DIEnumerator(name: "kw___underlying_type", value: 211, isUnsigned: true)
!1169 = !DIEnumerator(name: "kw___is_lvalue_expr", value: 212, isUnsigned: true)
!1170 = !DIEnumerator(name: "kw___is_rvalue_expr", value: 213, isUnsigned: true)
!1171 = !DIEnumerator(name: "kw___is_arithmetic", value: 214, isUnsigned: true)
!1172 = !DIEnumerator(name: "kw___is_floating_point", value: 215, isUnsigned: true)
!1173 = !DIEnumerator(name: "kw___is_integral", value: 216, isUnsigned: true)
!1174 = !DIEnumerator(name: "kw___is_complete_type", value: 217, isUnsigned: true)
!1175 = !DIEnumerator(name: "kw___is_void", value: 218, isUnsigned: true)
!1176 = !DIEnumerator(name: "kw___is_array", value: 219, isUnsigned: true)
!1177 = !DIEnumerator(name: "kw___is_function", value: 220, isUnsigned: true)
!1178 = !DIEnumerator(name: "kw___is_reference", value: 221, isUnsigned: true)
!1179 = !DIEnumerator(name: "kw___is_lvalue_reference", value: 222, isUnsigned: true)
!1180 = !DIEnumerator(name: "kw___is_rvalue_reference", value: 223, isUnsigned: true)
!1181 = !DIEnumerator(name: "kw___is_fundamental", value: 224, isUnsigned: true)
!1182 = !DIEnumerator(name: "kw___is_object", value: 225, isUnsigned: true)
!1183 = !DIEnumerator(name: "kw___is_scalar", value: 226, isUnsigned: true)
!1184 = !DIEnumerator(name: "kw___is_compound", value: 227, isUnsigned: true)
!1185 = !DIEnumerator(name: "kw___is_pointer", value: 228, isUnsigned: true)
!1186 = !DIEnumerator(name: "kw___is_member_object_pointer", value: 229, isUnsigned: true)
!1187 = !DIEnumerator(name: "kw___is_member_function_pointer", value: 230, isUnsigned: true)
!1188 = !DIEnumerator(name: "kw___is_member_pointer", value: 231, isUnsigned: true)
!1189 = !DIEnumerator(name: "kw___is_const", value: 232, isUnsigned: true)
!1190 = !DIEnumerator(name: "kw___is_volatile", value: 233, isUnsigned: true)
!1191 = !DIEnumerator(name: "kw___is_standard_layout", value: 234, isUnsigned: true)
!1192 = !DIEnumerator(name: "kw___is_signed", value: 235, isUnsigned: true)
!1193 = !DIEnumerator(name: "kw___is_unsigned", value: 236, isUnsigned: true)
!1194 = !DIEnumerator(name: "kw___is_same", value: 237, isUnsigned: true)
!1195 = !DIEnumerator(name: "kw___is_convertible", value: 238, isUnsigned: true)
!1196 = !DIEnumerator(name: "kw___array_rank", value: 239, isUnsigned: true)
!1197 = !DIEnumerator(name: "kw___array_extent", value: 240, isUnsigned: true)
!1198 = !DIEnumerator(name: "kw___private_extern__", value: 241, isUnsigned: true)
!1199 = !DIEnumerator(name: "kw___module_private__", value: 242, isUnsigned: true)
!1200 = !DIEnumerator(name: "kw___declspec", value: 243, isUnsigned: true)
!1201 = !DIEnumerator(name: "kw___cdecl", value: 244, isUnsigned: true)
!1202 = !DIEnumerator(name: "kw___stdcall", value: 245, isUnsigned: true)
!1203 = !DIEnumerator(name: "kw___fastcall", value: 246, isUnsigned: true)
!1204 = !DIEnumerator(name: "kw___thiscall", value: 247, isUnsigned: true)
!1205 = !DIEnumerator(name: "kw___forceinline", value: 248, isUnsigned: true)
!1206 = !DIEnumerator(name: "kw___unaligned", value: 249, isUnsigned: true)
!1207 = !DIEnumerator(name: "kw___kernel", value: 250, isUnsigned: true)
!1208 = !DIEnumerator(name: "kw_vec_step", value: 251, isUnsigned: true)
!1209 = !DIEnumerator(name: "kw___private", value: 252, isUnsigned: true)
!1210 = !DIEnumerator(name: "kw___global", value: 253, isUnsigned: true)
!1211 = !DIEnumerator(name: "kw___local", value: 254, isUnsigned: true)
!1212 = !DIEnumerator(name: "kw___constant", value: 255, isUnsigned: true)
!1213 = !DIEnumerator(name: "kw___read_only", value: 256, isUnsigned: true)
!1214 = !DIEnumerator(name: "kw___write_only", value: 257, isUnsigned: true)
!1215 = !DIEnumerator(name: "kw___read_write", value: 258, isUnsigned: true)
!1216 = !DIEnumerator(name: "kw___builtin_astype", value: 259, isUnsigned: true)
!1217 = !DIEnumerator(name: "kw_image1d_t", value: 260, isUnsigned: true)
!1218 = !DIEnumerator(name: "kw_image1d_array_t", value: 261, isUnsigned: true)
!1219 = !DIEnumerator(name: "kw_image1d_buffer_t", value: 262, isUnsigned: true)
!1220 = !DIEnumerator(name: "kw_image2d_t", value: 263, isUnsigned: true)
!1221 = !DIEnumerator(name: "kw_image2d_array_t", value: 264, isUnsigned: true)
!1222 = !DIEnumerator(name: "kw_image3d_t", value: 265, isUnsigned: true)
!1223 = !DIEnumerator(name: "kw_sampler_t", value: 266, isUnsigned: true)
!1224 = !DIEnumerator(name: "kw_event_t", value: 267, isUnsigned: true)
!1225 = !DIEnumerator(name: "kw___pascal", value: 268, isUnsigned: true)
!1226 = !DIEnumerator(name: "kw___vector", value: 269, isUnsigned: true)
!1227 = !DIEnumerator(name: "kw___pixel", value: 270, isUnsigned: true)
!1228 = !DIEnumerator(name: "kw_half", value: 271, isUnsigned: true)
!1229 = !DIEnumerator(name: "kw___bridge", value: 272, isUnsigned: true)
!1230 = !DIEnumerator(name: "kw___bridge_transfer", value: 273, isUnsigned: true)
!1231 = !DIEnumerator(name: "kw___bridge_retained", value: 274, isUnsigned: true)
!1232 = !DIEnumerator(name: "kw___bridge_retain", value: 275, isUnsigned: true)
!1233 = !DIEnumerator(name: "kw___ptr64", value: 276, isUnsigned: true)
!1234 = !DIEnumerator(name: "kw___ptr32", value: 277, isUnsigned: true)
!1235 = !DIEnumerator(name: "kw___sptr", value: 278, isUnsigned: true)
!1236 = !DIEnumerator(name: "kw___uptr", value: 279, isUnsigned: true)
!1237 = !DIEnumerator(name: "kw___w64", value: 280, isUnsigned: true)
!1238 = !DIEnumerator(name: "kw___uuidof", value: 281, isUnsigned: true)
!1239 = !DIEnumerator(name: "kw___try", value: 282, isUnsigned: true)
!1240 = !DIEnumerator(name: "kw___finally", value: 283, isUnsigned: true)
!1241 = !DIEnumerator(name: "kw___leave", value: 284, isUnsigned: true)
!1242 = !DIEnumerator(name: "kw___int64", value: 285, isUnsigned: true)
!1243 = !DIEnumerator(name: "kw___if_exists", value: 286, isUnsigned: true)
!1244 = !DIEnumerator(name: "kw___if_not_exists", value: 287, isUnsigned: true)
!1245 = !DIEnumerator(name: "kw___single_inheritance", value: 288, isUnsigned: true)
!1246 = !DIEnumerator(name: "kw___multiple_inheritance", value: 289, isUnsigned: true)
!1247 = !DIEnumerator(name: "kw___virtual_inheritance", value: 290, isUnsigned: true)
!1248 = !DIEnumerator(name: "kw___interface", value: 291, isUnsigned: true)
!1249 = !DIEnumerator(name: "kw___builtin_convertvector", value: 292, isUnsigned: true)
!1250 = !DIEnumerator(name: "kw___unknown_anytype", value: 293, isUnsigned: true)
!1251 = !DIEnumerator(name: "annot_cxxscope", value: 294, isUnsigned: true)
!1252 = !DIEnumerator(name: "annot_typename", value: 295, isUnsigned: true)
!1253 = !DIEnumerator(name: "annot_template_id", value: 296, isUnsigned: true)
!1254 = !DIEnumerator(name: "annot_primary_expr", value: 297, isUnsigned: true)
!1255 = !DIEnumerator(name: "annot_decltype", value: 298, isUnsigned: true)
!1256 = !DIEnumerator(name: "annot_pragma_unused", value: 299, isUnsigned: true)
!1257 = !DIEnumerator(name: "annot_pragma_vis", value: 300, isUnsigned: true)
!1258 = !DIEnumerator(name: "annot_pragma_pack", value: 301, isUnsigned: true)
!1259 = !DIEnumerator(name: "annot_pragma_parser_crash", value: 302, isUnsigned: true)
!1260 = !DIEnumerator(name: "annot_pragma_captured", value: 303, isUnsigned: true)
!1261 = !DIEnumerator(name: "annot_pragma_msstruct", value: 304, isUnsigned: true)
!1262 = !DIEnumerator(name: "annot_pragma_align", value: 305, isUnsigned: true)
!1263 = !DIEnumerator(name: "annot_pragma_weak", value: 306, isUnsigned: true)
!1264 = !DIEnumerator(name: "annot_pragma_weakalias", value: 307, isUnsigned: true)
!1265 = !DIEnumerator(name: "annot_pragma_redefine_extname", value: 308, isUnsigned: true)
!1266 = !DIEnumerator(name: "annot_pragma_fp_contract", value: 309, isUnsigned: true)
!1267 = !DIEnumerator(name: "annot_pragma_opencl_extension", value: 310, isUnsigned: true)
!1268 = !DIEnumerator(name: "annot_pragma_openmp", value: 311, isUnsigned: true)
!1269 = !DIEnumerator(name: "annot_pragma_openmp_end", value: 312, isUnsigned: true)
!1270 = !DIEnumerator(name: "annot_module_include", value: 313, isUnsigned: true)
!1271 = !DIEnumerator(name: "NUM_TOKENS", value: 314, isUnsigned: true)
!1272 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1273, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1273 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !294)
!1274 = !DISubprogram(name: "setKind", linkageName: "_ZN5clang5Token7setKindENS_3tok9TokenKindE", scope: !294, file: !293, line: 87, type: !1275, scopeLine: 87, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1275 = !DISubroutineType(types: !1276)
!1276 = !{null, !1277, !953}
!1277 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !294, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1278 = !DISubprogram(name: "is", linkageName: "_ZNK5clang5Token2isENS_3tok9TokenKindE", scope: !294, file: !293, line: 91, type: !1279, scopeLine: 91, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1279 = !DISubroutineType(types: !1280)
!1280 = !{!308, !1272, !953}
!1281 = !DISubprogram(name: "isNot", linkageName: "_ZNK5clang5Token5isNotENS_3tok9TokenKindE", scope: !294, file: !293, line: 92, type: !1279, scopeLine: 92, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1282 = !DISubprogram(name: "isAnyIdentifier", linkageName: "_ZNK5clang5Token15isAnyIdentifierEv", scope: !294, file: !293, line: 96, type: !1283, scopeLine: 96, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1283 = !DISubroutineType(types: !1284)
!1284 = !{!308, !1272}
!1285 = !DISubprogram(name: "isLiteral", linkageName: "_ZNK5clang5Token9isLiteralEv", scope: !294, file: !293, line: 102, type: !1283, scopeLine: 102, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1286 = !DISubprogram(name: "isAnnotation", linkageName: "_ZNK5clang5Token12isAnnotationEv", scope: !294, file: !293, line: 107, type: !1283, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1287 = !DISubprogram(name: "getLocation", linkageName: "_ZNK5clang5Token11getLocationEv", scope: !294, file: !293, line: 113, type: !1288, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1288 = !DISubroutineType(types: !1289)
!1289 = !{!297, !1272}
!1290 = !DISubprogram(name: "getLength", linkageName: "_ZNK5clang5Token9getLengthEv", scope: !294, file: !293, line: 114, type: !1291, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1291 = !DISubroutineType(types: !1292)
!1292 = !{!6, !1272}
!1293 = !DISubprogram(name: "setLocation", linkageName: "_ZN5clang5Token11setLocationENS_14SourceLocationE", scope: !294, file: !293, line: 119, type: !1294, scopeLine: 119, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1294 = !DISubroutineType(types: !1295)
!1295 = !{null, !1277, !297}
!1296 = !DISubprogram(name: "setLength", linkageName: "_ZN5clang5Token9setLengthEj", scope: !294, file: !293, line: 120, type: !1297, scopeLine: 120, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1297 = !DISubroutineType(types: !1298)
!1298 = !{null, !1277, !6}
!1299 = !DISubprogram(name: "getAnnotationEndLoc", linkageName: "_ZNK5clang5Token19getAnnotationEndLocEv", scope: !294, file: !293, line: 125, type: !1288, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1300 = !DISubprogram(name: "setAnnotationEndLoc", linkageName: "_ZN5clang5Token19setAnnotationEndLocENS_14SourceLocationE", scope: !294, file: !293, line: 129, type: !1294, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1301 = !DISubprogram(name: "getLastLoc", linkageName: "_ZNK5clang5Token10getLastLocEv", scope: !294, file: !293, line: 134, type: !1288, scopeLine: 134, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1302 = !DISubprogram(name: "getAnnotationRange", linkageName: "_ZNK5clang5Token18getAnnotationRangeEv", scope: !294, file: !293, line: 140, type: !1303, scopeLine: 140, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1303 = !DISubroutineType(types: !1304)
!1304 = !{!1305, !1272}
!1305 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SourceRange", scope: !14, file: !298, line: 192, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1306, identifier: "_ZTSN5clang11SourceRangeE")
!1306 = !{!1307, !1308, !1309, !1313, !1316, !1319, !1324, !1325, !1326, !1327, !1330, !1331, !1335}
!1307 = !DIDerivedType(tag: DW_TAG_member, name: "B", scope: !1305, file: !298, line: 193, baseType: !297, size: 32)
!1308 = !DIDerivedType(tag: DW_TAG_member, name: "E", scope: !1305, file: !298, line: 194, baseType: !297, size: 32, offset: 32)
!1309 = !DISubprogram(name: "SourceRange", scope: !1305, file: !298, line: 196, type: !1310, scopeLine: 196, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1310 = !DISubroutineType(types: !1311)
!1311 = !{null, !1312}
!1312 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1305, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1313 = !DISubprogram(name: "SourceRange", scope: !1305, file: !298, line: 197, type: !1314, scopeLine: 197, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1314 = !DISubroutineType(types: !1315)
!1315 = !{null, !1312, !297}
!1316 = !DISubprogram(name: "SourceRange", scope: !1305, file: !298, line: 198, type: !1317, scopeLine: 198, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1317 = !DISubroutineType(types: !1318)
!1318 = !{null, !1312, !297, !297}
!1319 = !DISubprogram(name: "getBegin", linkageName: "_ZNK5clang11SourceRange8getBeginEv", scope: !1305, file: !298, line: 200, type: !1320, scopeLine: 200, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1320 = !DISubroutineType(types: !1321)
!1321 = !{!297, !1322}
!1322 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1323, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1323 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1305)
!1324 = !DISubprogram(name: "getEnd", linkageName: "_ZNK5clang11SourceRange6getEndEv", scope: !1305, file: !298, line: 201, type: !1320, scopeLine: 201, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1325 = !DISubprogram(name: "setBegin", linkageName: "_ZN5clang11SourceRange8setBeginENS_14SourceLocationE", scope: !1305, file: !298, line: 203, type: !1314, scopeLine: 203, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1326 = !DISubprogram(name: "setEnd", linkageName: "_ZN5clang11SourceRange6setEndENS_14SourceLocationE", scope: !1305, file: !298, line: 204, type: !1314, scopeLine: 204, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1327 = !DISubprogram(name: "isValid", linkageName: "_ZNK5clang11SourceRange7isValidEv", scope: !1305, file: !298, line: 206, type: !1328, scopeLine: 206, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1328 = !DISubroutineType(types: !1329)
!1329 = !{!308, !1322}
!1330 = !DISubprogram(name: "isInvalid", linkageName: "_ZNK5clang11SourceRange9isInvalidEv", scope: !1305, file: !298, line: 207, type: !1328, scopeLine: 207, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1331 = !DISubprogram(name: "operator==", linkageName: "_ZNK5clang11SourceRangeeqERKS0_", scope: !1305, file: !298, line: 209, type: !1332, scopeLine: 209, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1332 = !DISubroutineType(types: !1333)
!1333 = !{!308, !1322, !1334}
!1334 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1323, size: 64)
!1335 = !DISubprogram(name: "operator!=", linkageName: "_ZNK5clang11SourceRangeneERKS0_", scope: !1305, file: !298, line: 213, type: !1332, scopeLine: 213, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1336 = !DISubprogram(name: "setAnnotationRange", linkageName: "_ZN5clang5Token18setAnnotationRangeENS_11SourceRangeE", scope: !294, file: !293, line: 143, type: !1337, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1337 = !DISubroutineType(types: !1338)
!1338 = !{null, !1277, !1305}
!1339 = !DISubprogram(name: "getName", linkageName: "_ZNK5clang5Token7getNameEv", scope: !294, file: !293, line: 148, type: !1340, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1340 = !DISubroutineType(types: !1341)
!1341 = !{!407, !1272}
!1342 = !DISubprogram(name: "startToken", linkageName: "_ZN5clang5Token10startTokenEv", scope: !294, file: !293, line: 153, type: !1343, scopeLine: 153, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1343 = !DISubroutineType(types: !1344)
!1344 = !{null, !1277}
!1345 = !DISubprogram(name: "getIdentifierInfo", linkageName: "_ZNK5clang5Token17getIdentifierInfoEv", scope: !294, file: !293, line: 161, type: !1346, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1346 = !DISubroutineType(types: !1347)
!1347 = !{!1348, !1272}
!1348 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1349, size: 64)
!1349 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "IdentifierInfo", scope: !14, file: !1350, line: 50, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang14IdentifierInfoE")
!1350 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/IdentifierTable.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "4680d46f8abc74960d0f86dc6eb6b801")
!1351 = !DISubprogram(name: "setIdentifierInfo", linkageName: "_ZN5clang5Token17setIdentifierInfoEPNS_14IdentifierInfoE", scope: !294, file: !293, line: 169, type: !1352, scopeLine: 169, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1352 = !DISubroutineType(types: !1353)
!1353 = !{null, !1277, !1348}
!1354 = !DISubprogram(name: "getRawIdentifierData", linkageName: "_ZNK5clang5Token20getRawIdentifierDataEv", scope: !294, file: !293, line: 176, type: !1340, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1355 = !DISubprogram(name: "setRawIdentifierData", linkageName: "_ZN5clang5Token20setRawIdentifierDataEPKc", scope: !294, file: !293, line: 180, type: !1356, scopeLine: 180, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1356 = !DISubroutineType(types: !1357)
!1357 = !{null, !1277, !407}
!1358 = !DISubprogram(name: "getLiteralData", linkageName: "_ZNK5clang5Token14getLiteralDataEv", scope: !294, file: !293, line: 188, type: !1340, scopeLine: 188, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1359 = !DISubprogram(name: "setLiteralData", linkageName: "_ZN5clang5Token14setLiteralDataEPKc", scope: !294, file: !293, line: 192, type: !1356, scopeLine: 192, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1360 = !DISubprogram(name: "getAnnotationValue", linkageName: "_ZNK5clang5Token18getAnnotationValueEv", scope: !294, file: !293, line: 197, type: !1361, scopeLine: 197, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1361 = !DISubroutineType(types: !1362)
!1362 = !{!330, !1272}
!1363 = !DISubprogram(name: "setAnnotationValue", linkageName: "_ZN5clang5Token18setAnnotationValueEPv", scope: !294, file: !293, line: 201, type: !1364, scopeLine: 201, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1364 = !DISubroutineType(types: !1365)
!1365 = !{null, !1277, !330}
!1366 = !DISubprogram(name: "setFlag", linkageName: "_ZN5clang5Token7setFlagENS0_10TokenFlagsE", scope: !294, file: !293, line: 207, type: !1367, scopeLine: 207, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1367 = !DISubroutineType(types: !1368)
!1368 = !{null, !1277, !292}
!1369 = !DISubprogram(name: "clearFlag", linkageName: "_ZN5clang5Token9clearFlagENS0_10TokenFlagsE", scope: !294, file: !293, line: 212, type: !1367, scopeLine: 212, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1370 = !DISubprogram(name: "getFlags", linkageName: "_ZNK5clang5Token8getFlagsEv", scope: !294, file: !293, line: 220, type: !1291, scopeLine: 220, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1371 = !DISubprogram(name: "setFlagValue", linkageName: "_ZN5clang5Token12setFlagValueENS0_10TokenFlagsEb", scope: !294, file: !293, line: 225, type: !1372, scopeLine: 225, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1372 = !DISubroutineType(types: !1373)
!1373 = !{null, !1277, !292, !308}
!1374 = !DISubprogram(name: "isAtStartOfLine", linkageName: "_ZNK5clang5Token15isAtStartOfLineEv", scope: !294, file: !293, line: 234, type: !1283, scopeLine: 234, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1375 = !DISubprogram(name: "hasLeadingSpace", linkageName: "_ZNK5clang5Token15hasLeadingSpaceEv", scope: !294, file: !293, line: 238, type: !1283, scopeLine: 238, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1376 = !DISubprogram(name: "isExpandDisabled", linkageName: "_ZNK5clang5Token16isExpandDisabledEv", scope: !294, file: !293, line: 242, type: !1283, scopeLine: 242, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1377 = !DISubprogram(name: "isObjCAtKeyword", linkageName: "_ZNK5clang5Token15isObjCAtKeywordENS_3tok15ObjCKeywordKindE", scope: !294, file: !293, line: 247, type: !1378, scopeLine: 247, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1378 = !DISubroutineType(types: !1379)
!1379 = !{!308, !1272, !1380}
!1380 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "ObjCKeywordKind", scope: !955, file: !954, line: 39, baseType: !6, size: 32, elements: !1381, identifier: "_ZTSN5clang3tok15ObjCKeywordKindE")
!1381 = !{!1382, !1383, !1384, !1385, !1386, !1387, !1388, !1389, !1390, !1391, !1392, !1393, !1394, !1395, !1396, !1397, !1398, !1399, !1400, !1401, !1402, !1403, !1404, !1405, !1406, !1407, !1408}
!1382 = !DIEnumerator(name: "objc_not_keyword", value: 0, isUnsigned: true)
!1383 = !DIEnumerator(name: "objc_class", value: 1, isUnsigned: true)
!1384 = !DIEnumerator(name: "objc_compatibility_alias", value: 2, isUnsigned: true)
!1385 = !DIEnumerator(name: "objc_defs", value: 3, isUnsigned: true)
!1386 = !DIEnumerator(name: "objc_encode", value: 4, isUnsigned: true)
!1387 = !DIEnumerator(name: "objc_end", value: 5, isUnsigned: true)
!1388 = !DIEnumerator(name: "objc_implementation", value: 6, isUnsigned: true)
!1389 = !DIEnumerator(name: "objc_interface", value: 7, isUnsigned: true)
!1390 = !DIEnumerator(name: "objc_private", value: 8, isUnsigned: true)
!1391 = !DIEnumerator(name: "objc_protected", value: 9, isUnsigned: true)
!1392 = !DIEnumerator(name: "objc_protocol", value: 10, isUnsigned: true)
!1393 = !DIEnumerator(name: "objc_public", value: 11, isUnsigned: true)
!1394 = !DIEnumerator(name: "objc_selector", value: 12, isUnsigned: true)
!1395 = !DIEnumerator(name: "objc_throw", value: 13, isUnsigned: true)
!1396 = !DIEnumerator(name: "objc_try", value: 14, isUnsigned: true)
!1397 = !DIEnumerator(name: "objc_catch", value: 15, isUnsigned: true)
!1398 = !DIEnumerator(name: "objc_finally", value: 16, isUnsigned: true)
!1399 = !DIEnumerator(name: "objc_synchronized", value: 17, isUnsigned: true)
!1400 = !DIEnumerator(name: "objc_autoreleasepool", value: 18, isUnsigned: true)
!1401 = !DIEnumerator(name: "objc_property", value: 19, isUnsigned: true)
!1402 = !DIEnumerator(name: "objc_package", value: 20, isUnsigned: true)
!1403 = !DIEnumerator(name: "objc_required", value: 21, isUnsigned: true)
!1404 = !DIEnumerator(name: "objc_optional", value: 22, isUnsigned: true)
!1405 = !DIEnumerator(name: "objc_synthesize", value: 23, isUnsigned: true)
!1406 = !DIEnumerator(name: "objc_dynamic", value: 24, isUnsigned: true)
!1407 = !DIEnumerator(name: "objc_import", value: 25, isUnsigned: true)
!1408 = !DIEnumerator(name: "NUM_OBJC_KEYWORDS", value: 26, isUnsigned: true)
!1409 = !DISubprogram(name: "getObjCKeywordID", linkageName: "_ZNK5clang5Token16getObjCKeywordIDEv", scope: !294, file: !293, line: 250, type: !1410, scopeLine: 250, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1410 = !DISubroutineType(types: !1411)
!1411 = !{!1380, !1272}
!1412 = !DISubprogram(name: "needsCleaning", linkageName: "_ZNK5clang5Token13needsCleaningEv", scope: !294, file: !293, line: 253, type: !1283, scopeLine: 253, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1413 = !DISubprogram(name: "hasLeadingEmptyMacro", linkageName: "_ZNK5clang5Token20hasLeadingEmptyMacroEv", scope: !294, file: !293, line: 257, type: !1283, scopeLine: 257, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1414 = !DISubprogram(name: "hasUDSuffix", linkageName: "_ZNK5clang5Token11hasUDSuffixEv", scope: !294, file: !293, line: 263, type: !1283, scopeLine: 263, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1415 = !DISubprogram(name: "hasUCN", linkageName: "_ZNK5clang5Token6hasUCNEv", scope: !294, file: !293, line: 266, type: !1283, scopeLine: 266, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1416 = !{!1417, !1418, !1419, !1420, !1421, !1422, !1423, !1424}
!1417 = !DIEnumerator(name: "StartOfLine", value: 1, isUnsigned: true)
!1418 = !DIEnumerator(name: "LeadingSpace", value: 2, isUnsigned: true)
!1419 = !DIEnumerator(name: "DisableExpand", value: 4, isUnsigned: true)
!1420 = !DIEnumerator(name: "NeedsCleaning", value: 8, isUnsigned: true)
!1421 = !DIEnumerator(name: "LeadingEmptyMacro", value: 16, isUnsigned: true)
!1422 = !DIEnumerator(name: "HasUDSuffix", value: 32, isUnsigned: true)
!1423 = !DIEnumerator(name: "HasUCN", value: 64, isUnsigned: true)
!1424 = !DIEnumerator(name: "IgnoredComma", value: 128, isUnsigned: true)
!1425 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "NoneType", scope: !342, file: !1426, line: 22, baseType: !6, size: 32, elements: !1427, identifier: "_ZTSN4llvm8NoneTypeE")
!1426 = !DIFile(filename: "llvm34/include/llvm/ADT/None.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "a0342314f03a5b3ad15259d9915a8f1b")
!1427 = !{!1428}
!1428 = !DIEnumerator(name: "None", value: 0, isUnsigned: true)
!1429 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "ArgumentKind", scope: !1431, file: !1430, line: 149, baseType: !6, size: 32, elements: !1432, identifier: "_ZTSN5clang17DiagnosticsEngine12ArgumentKindE")
!1430 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/Diagnostic.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "2e9ac3be6db0319027dde5c1d8125a04")
!1431 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DiagnosticsEngine", scope: !14, file: !1430, line: 131, size: 11648, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang17DiagnosticsEngineE")
!1432 = !{!1433, !1434, !1435, !1436, !1437, !1438, !1439, !1440, !1441, !1442, !1443}
!1433 = !DIEnumerator(name: "ak_std_string", value: 0, isUnsigned: true)
!1434 = !DIEnumerator(name: "ak_c_string", value: 1, isUnsigned: true)
!1435 = !DIEnumerator(name: "ak_sint", value: 2, isUnsigned: true)
!1436 = !DIEnumerator(name: "ak_uint", value: 3, isUnsigned: true)
!1437 = !DIEnumerator(name: "ak_identifierinfo", value: 4, isUnsigned: true)
!1438 = !DIEnumerator(name: "ak_qualtype", value: 5, isUnsigned: true)
!1439 = !DIEnumerator(name: "ak_declarationname", value: 6, isUnsigned: true)
!1440 = !DIEnumerator(name: "ak_nameddecl", value: 7, isUnsigned: true)
!1441 = !DIEnumerator(name: "ak_nestednamespec", value: 8, isUnsigned: true)
!1442 = !DIEnumerator(name: "ak_declcontext", value: 9, isUnsigned: true)
!1443 = !DIEnumerator(name: "ak_qualtype_pair", value: 10, isUnsigned: true)
!1444 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !1431, file: !1430, line: 707, baseType: !6, size: 32, elements: !1445, identifier: "_ZTSN5clang17DiagnosticsEngineUt_E")
!1445 = !{!1446, !1447, !1448}
!1446 = !DIEnumerator(name: "MaxArguments", value: 10, isUnsigned: true)
!1447 = !DIEnumerator(name: "MaxRanges", value: 10, isUnsigned: true)
!1448 = !DIEnumerator(name: "MaxFixItHints", value: 10, isUnsigned: true)
!1449 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "Bracket", file: !1450, line: 371, baseType: !6, size: 32, elements: !1451, identifier: "_ZTS7Bracket")
!1450 = !DIFile(filename: "llvm34/projects/clang/lib/Lex/PPMacroExpansion.cpp", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "84b26e26fade7b8d905a5831be1ffc69")
!1451 = !{!1452, !1453}
!1452 = !DIEnumerator(name: "Brace", value: 0, isUnsigned: true)
!1453 = !DIEnumerator(name: "Paren", value: 1, isUnsigned: true)
!1454 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !354, file: !358, line: 158, baseType: !6, size: 32, elements: !1455, identifier: "_ZTSNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEUt_E")
!1455 = !{!1456}
!1456 = !DIEnumerator(name: "_S_local_capacity", value: 15, isUnsigned: true)
!1457 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "CharacteristicKind", scope: !1458, file: !346, line: 77, baseType: !6, size: 32, elements: !1459, identifier: "_ZTSN5clang6SrcMgr18CharacteristicKindE")
!1458 = !DINamespace(name: "SrcMgr", scope: !14)
!1459 = !{!1460, !1461, !1462}
!1460 = !DIEnumerator(name: "C_User", value: 0, isUnsigned: true)
!1461 = !DIEnumerator(name: "C_System", value: 1, isUnsigned: true)
!1462 = !DIEnumerator(name: "C_ExternCSystem", value: 2, isUnsigned: true)
!1463 = !DICompositeType(tag: DW_TAG_enumeration_type, scope: !353, file: !1464, line: 70, baseType: !6, size: 32, elements: !1465)
!1464 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_bvector.h", directory: "", checksumkind: CSK_MD5, checksum: "543595f245ff5dae7fc0594cdc71787c")
!1465 = !{!1466}
!1466 = !DIEnumerator(name: "_S_word_bit", value: 64, isUnsigned: true)
!1467 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "ExtensionHandling", scope: !1431, file: !1430, line: 145, baseType: !6, size: 32, elements: !1468, identifier: "_ZTSN5clang17DiagnosticsEngine17ExtensionHandlingE")
!1468 = !{!1469, !1470, !1471}
!1469 = !DIEnumerator(name: "Ext_Ignore", value: 0, isUnsigned: true)
!1470 = !DIEnumerator(name: "Ext_Warn", value: 1, isUnsigned: true)
!1471 = !DIEnumerator(name: "Ext_Error", value: 2, isUnsigned: true)
!1472 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "Kind", scope: !1474, file: !1473, line: 28, baseType: !6, size: 32, elements: !1475, identifier: "_ZTSN5clang11ObjCRuntime4KindE")
!1473 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/ObjCRuntime.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "8316d08ad95388a83ee016fda0d3156e")
!1474 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ObjCRuntime", scope: !14, file: !1473, line: 25, size: 160, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang11ObjCRuntimeE")
!1475 = !{!1476, !1477, !1478, !1479, !1480, !1481}
!1476 = !DIEnumerator(name: "MacOSX", value: 0, isUnsigned: true)
!1477 = !DIEnumerator(name: "FragileMacOSX", value: 1, isUnsigned: true)
!1478 = !DIEnumerator(name: "iOS", value: 2, isUnsigned: true)
!1479 = !DIEnumerator(name: "GCC", value: 3, isUnsigned: true)
!1480 = !DIEnumerator(name: "GNUstep", value: 4, isUnsigned: true)
!1481 = !DIEnumerator(name: "ObjFW", value: 5, isUnsigned: true)
!1482 = !DICompositeType(tag: DW_TAG_enumeration_type, scope: !13, file: !1483, line: 49, baseType: !6, size: 32, elements: !1484)
!1483 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/DiagnosticIDs.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "d3dd8be052b98ac08581c112be7e2a4d")
!1484 = !{!1485, !1486, !1487, !1488, !1489, !1490, !1491, !1492, !1493, !1494, !1495, !1496, !1497, !1498, !1499, !1500, !1501, !1502, !1503, !1504, !1505, !1506, !1507, !1508, !1509, !1510, !1511, !1512, !1513, !1514, !1515, !1516, !1517, !1518, !1519, !1520, !1521, !1522, !1523, !1524, !1525, !1526, !1527, !1528, !1529, !1530, !1531, !1532, !1533, !1534, !1535, !1536, !1537, !1538, !1539}
!1485 = !DIEnumerator(name: "__COMMONSTART", value: 0, isUnsigned: true)
!1486 = !DIEnumerator(name: "err_attribute_not_type_attr", value: 1, isUnsigned: true)
!1487 = !DIEnumerator(name: "err_cannot_open_file", value: 2, isUnsigned: true)
!1488 = !DIEnumerator(name: "err_default_special_members", value: 3, isUnsigned: true)
!1489 = !DIEnumerator(name: "err_deleted_non_function", value: 4, isUnsigned: true)
!1490 = !DIEnumerator(name: "err_enum_template", value: 5, isUnsigned: true)
!1491 = !DIEnumerator(name: "err_expected_colon", value: 6, isUnsigned: true)
!1492 = !DIEnumerator(name: "err_expected_colon_after_setter_name", value: 7, isUnsigned: true)
!1493 = !DIEnumerator(name: "err_expected_namespace_name", value: 8, isUnsigned: true)
!1494 = !DIEnumerator(name: "err_expected_string_literal", value: 9, isUnsigned: true)
!1495 = !DIEnumerator(name: "err_file_modified", value: 10, isUnsigned: true)
!1496 = !DIEnumerator(name: "err_integer_too_large", value: 11, isUnsigned: true)
!1497 = !DIEnumerator(name: "err_invalid_character_udl", value: 12, isUnsigned: true)
!1498 = !DIEnumerator(name: "err_invalid_numeric_udl", value: 13, isUnsigned: true)
!1499 = !DIEnumerator(name: "err_invalid_storage_class_in_func_decl", value: 14, isUnsigned: true)
!1500 = !DIEnumerator(name: "err_invalid_string_udl", value: 15, isUnsigned: true)
!1501 = !DIEnumerator(name: "err_module_cycle", value: 16, isUnsigned: true)
!1502 = !DIEnumerator(name: "err_module_file_conflict", value: 17, isUnsigned: true)
!1503 = !DIEnumerator(name: "err_module_not_built", value: 18, isUnsigned: true)
!1504 = !DIEnumerator(name: "err_module_not_found", value: 19, isUnsigned: true)
!1505 = !DIEnumerator(name: "err_param_redefinition", value: 20, isUnsigned: true)
!1506 = !DIEnumerator(name: "err_target_unknown_abi", value: 21, isUnsigned: true)
!1507 = !DIEnumerator(name: "err_target_unknown_cpu", value: 22, isUnsigned: true)
!1508 = !DIEnumerator(name: "err_target_unknown_cxxabi", value: 23, isUnsigned: true)
!1509 = !DIEnumerator(name: "err_target_unknown_fpmath", value: 24, isUnsigned: true)
!1510 = !DIEnumerator(name: "err_target_unknown_triple", value: 25, isUnsigned: true)
!1511 = !DIEnumerator(name: "err_target_unsupported_fpmath", value: 26, isUnsigned: true)
!1512 = !DIEnumerator(name: "err_unable_to_make_temp", value: 27, isUnsigned: true)
!1513 = !DIEnumerator(name: "err_unable_to_rename_temp", value: 28, isUnsigned: true)
!1514 = !DIEnumerator(name: "err_unsupported_bom", value: 29, isUnsigned: true)
!1515 = !DIEnumerator(name: "ext_c99_longlong", value: 30, isUnsigned: true)
!1516 = !DIEnumerator(name: "ext_cxx11_longlong", value: 31, isUnsigned: true)
!1517 = !DIEnumerator(name: "ext_variadic_templates", value: 32, isUnsigned: true)
!1518 = !DIEnumerator(name: "fatal_too_many_errors", value: 33, isUnsigned: true)
!1519 = !DIEnumerator(name: "note_also_found", value: 34, isUnsigned: true)
!1520 = !DIEnumerator(name: "note_decl_hiding_tag_type", value: 35, isUnsigned: true)
!1521 = !DIEnumerator(name: "note_declared_at", value: 36, isUnsigned: true)
!1522 = !DIEnumerator(name: "note_duplicate_case_prev", value: 37, isUnsigned: true)
!1523 = !DIEnumerator(name: "note_forward_declaration", value: 38, isUnsigned: true)
!1524 = !DIEnumerator(name: "note_invalid_subexpr_in_const_expr", value: 39, isUnsigned: true)
!1525 = !DIEnumerator(name: "note_matching", value: 40, isUnsigned: true)
!1526 = !DIEnumerator(name: "note_possibility", value: 41, isUnsigned: true)
!1527 = !DIEnumerator(name: "note_pragma_entered_here", value: 42, isUnsigned: true)
!1528 = !DIEnumerator(name: "note_previous_declaration", value: 43, isUnsigned: true)
!1529 = !DIEnumerator(name: "note_previous_definition", value: 44, isUnsigned: true)
!1530 = !DIEnumerator(name: "note_previous_implicit_declaration", value: 45, isUnsigned: true)
!1531 = !DIEnumerator(name: "note_previous_use", value: 46, isUnsigned: true)
!1532 = !DIEnumerator(name: "note_type_being_defined", value: 47, isUnsigned: true)
!1533 = !DIEnumerator(name: "note_using", value: 48, isUnsigned: true)
!1534 = !DIEnumerator(name: "warn_cxx98_compat_longlong", value: 49, isUnsigned: true)
!1535 = !DIEnumerator(name: "warn_cxx98_compat_variadic_templates", value: 50, isUnsigned: true)
!1536 = !DIEnumerator(name: "warn_integer_too_large_for_signed", value: 51, isUnsigned: true)
!1537 = !DIEnumerator(name: "warn_method_param_declaration", value: 52, isUnsigned: true)
!1538 = !DIEnumerator(name: "warn_method_param_redefinition", value: 53, isUnsigned: true)
!1539 = !DIEnumerator(name: "NUM_BUILTIN_COMMON_DIAGNOSTICS", value: 54, isUnsigned: true)
!1540 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !1542, file: !1541, line: 39, baseType: !6, size: 32, elements: !1805, identifier: "_ZTSN4llvm7AlignOfINS_14StringMapEntryIPN5clang14IdentifierInfoEEEEUt_E")
!1541 = !DIFile(filename: "llvm34/include/llvm/Support/AlignOf.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "55acc245b7ffca1b8660602cb703d9fb")
!1542 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignOf<llvm::StringMapEntry<clang::IdentifierInfo *> >", scope: !342, file: !1541, line: 38, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !1543, identifier: "_ZTSN4llvm7AlignOfINS_14StringMapEntryIPN5clang14IdentifierInfoEEEEE")
!1543 = !{!1544}
!1544 = !DITemplateTypeParameter(name: "T", type: !1545)
!1545 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringMapEntry<clang::IdentifierInfo *>", scope: !342, file: !1546, line: 118, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1547, templateParams: !1803, identifier: "_ZTSN4llvm14StringMapEntryIPN5clang14IdentifierInfoEEE")
!1546 = !DIFile(filename: "llvm34/include/llvm/ADT/StringMap.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "25ead265da32dd3e6b5275b9c6f03393")
!1547 = !{!1548, !1561, !1562, !1567, !1570, !1575, !1772, !1775, !1779, !1782, !1785, !1786, !1790, !1793, !1797, !1800}
!1548 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1545, baseType: !1549, flags: DIFlagPublic, extraData: i32 0)
!1549 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringMapEntryBase", scope: !342, file: !1546, line: 43, size: 32, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1550, identifier: "_ZTSN4llvm18StringMapEntryBaseE")
!1550 = !{!1551, !1552, !1556}
!1551 = !DIDerivedType(tag: DW_TAG_member, name: "StrLen", scope: !1549, file: !1546, line: 44, baseType: !6, size: 32)
!1552 = !DISubprogram(name: "StringMapEntryBase", scope: !1549, file: !1546, line: 46, type: !1553, scopeLine: 46, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1553 = !DISubroutineType(types: !1554)
!1554 = !{null, !1555, !6}
!1555 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1549, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1556 = !DISubprogram(name: "getKeyLength", linkageName: "_ZNK4llvm18StringMapEntryBase12getKeyLengthEv", scope: !1549, file: !1546, line: 48, type: !1557, scopeLine: 48, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1557 = !DISubroutineType(types: !1558)
!1558 = !{!6, !1559}
!1559 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1560, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1560 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1549)
!1561 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !1545, file: !1546, line: 121, baseType: !1348, size: 64, offset: 64, flags: DIFlagPublic)
!1562 = !DISubprogram(name: "StringMapEntry", scope: !1545, file: !1546, line: 119, type: !1563, scopeLine: 119, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1563 = !DISubroutineType(types: !1564)
!1564 = !{null, !1565, !1566}
!1565 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1545, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1566 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1545, size: 64)
!1567 = !DISubprogram(name: "StringMapEntry", scope: !1545, file: !1546, line: 123, type: !1568, scopeLine: 123, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1568 = !DISubroutineType(types: !1569)
!1569 = !{null, !1565, !6}
!1570 = !DISubprogram(name: "StringMapEntry", scope: !1545, file: !1546, line: 125, type: !1571, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1571 = !DISubroutineType(types: !1572)
!1572 = !{null, !1565, !6, !1573}
!1573 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1574, size: 64)
!1574 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1348)
!1575 = !DISubprogram(name: "getKey", linkageName: "_ZNK4llvm14StringMapEntryIPN5clang14IdentifierInfoEE6getKeyEv", scope: !1545, file: !1546, line: 128, type: !1576, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1576 = !DISubroutineType(types: !1577)
!1577 = !{!1578, !1770}
!1578 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringRef", scope: !342, file: !1579, line: 41, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1580, identifier: "_ZTSN4llvm9StringRefE")
!1579 = !DIFile(filename: "llvm34/include/llvm/ADT/StringRef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "5c2e300880041c873457392c89335431")
!1580 = !{!1581, !1585, !1586, !1587, !1590, !1591, !1594, !1598, !1601, !1604, !1609, !1615, !1616, !1619, !1622, !1625, !1628, !1629, !1632, !1633, !1636, !1637, !1638, !1641, !1644, !1647, !1648, !1649, !1650, !1651, !1652, !1655, !1658, !1659, !1662, !1663, !1664, !1665, !1666, !1667, !1668, !1669, !1670, !1673, !1674, !1679, !1680, !1681, !1684, !1687, !1688, !1689, !1756, !1759, !1764, !1765, !1768, !1769}
!1581 = !DIDerivedType(tag: DW_TAG_member, name: "npos", scope: !1578, file: !1579, line: 45, baseType: !1582, flags: DIFlagPublic | DIFlagStaticMember, extraData: i64 -1)
!1582 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1583)
!1583 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", file: !1584, line: 46, baseType: !417)
!1584 = !DIFile(filename: "llvm5/build/lib/clang/15.0.3/include/stddef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "b76978376d35d5cd171876ac58ac1256")
!1585 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !1578, file: !1579, line: 50, baseType: !407, size: 64)
!1586 = !DIDerivedType(tag: DW_TAG_member, name: "Length", scope: !1578, file: !1579, line: 53, baseType: !1583, size: 64, offset: 64)
!1587 = !DISubprogram(name: "min", linkageName: "_ZN4llvm9StringRef3minEmm", scope: !1578, file: !1579, line: 58, type: !1588, scopeLine: 58, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1588 = !DISubroutineType(types: !1589)
!1589 = !{!1583, !1583, !1583}
!1590 = !DISubprogram(name: "max", linkageName: "_ZN4llvm9StringRef3maxEmm", scope: !1578, file: !1579, line: 59, type: !1588, scopeLine: 59, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1591 = !DISubprogram(name: "compareMemory", linkageName: "_ZN4llvm9StringRef13compareMemoryEPKcS2_m", scope: !1578, file: !1579, line: 63, type: !1592, scopeLine: 63, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1592 = !DISubroutineType(types: !1593)
!1593 = !{!324, !407, !407, !1583}
!1594 = !DISubprogram(name: "StringRef", scope: !1578, file: !1579, line: 73, type: !1595, scopeLine: 73, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1595 = !DISubroutineType(types: !1596)
!1596 = !{null, !1597}
!1597 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1578, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1598 = !DISubprogram(name: "StringRef", scope: !1578, file: !1579, line: 76, type: !1599, scopeLine: 76, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1599 = !DISubroutineType(types: !1600)
!1600 = !{null, !1597, !407}
!1601 = !DISubprogram(name: "StringRef", scope: !1578, file: !1579, line: 83, type: !1602, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1602 = !DISubroutineType(types: !1603)
!1603 = !{null, !1597, !407, !1583}
!1604 = !DISubprogram(name: "StringRef", scope: !1578, file: !1579, line: 90, type: !1605, scopeLine: 90, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1605 = !DISubroutineType(types: !1606)
!1606 = !{null, !1597, !1607}
!1607 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1608, size: 64)
!1608 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !350)
!1609 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm9StringRef5beginEv", scope: !1578, file: !1579, line: 97, type: !1610, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1610 = !DISubroutineType(types: !1611)
!1611 = !{!1612, !1613}
!1612 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1578, file: !1579, line: 43, baseType: !407)
!1613 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1614, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1614 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1578)
!1615 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm9StringRef3endEv", scope: !1578, file: !1579, line: 99, type: !1610, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1616 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm9StringRef4dataEv", scope: !1578, file: !1579, line: 107, type: !1617, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1617 = !DISubroutineType(types: !1618)
!1618 = !{!407, !1613}
!1619 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm9StringRef5emptyEv", scope: !1578, file: !1579, line: 110, type: !1620, scopeLine: 110, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1620 = !DISubroutineType(types: !1621)
!1621 = !{!308, !1613}
!1622 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm9StringRef4sizeEv", scope: !1578, file: !1579, line: 113, type: !1623, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1623 = !DISubroutineType(types: !1624)
!1624 = !{!1583, !1613}
!1625 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm9StringRef5frontEv", scope: !1578, file: !1579, line: 116, type: !1626, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1626 = !DISubroutineType(types: !1627)
!1627 = !{!374, !1613}
!1628 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm9StringRef4backEv", scope: !1578, file: !1579, line: 122, type: !1626, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1629 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm9StringRef6equalsES0_", scope: !1578, file: !1579, line: 129, type: !1630, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1630 = !DISubroutineType(types: !1631)
!1631 = !{!308, !1613, !1578}
!1632 = !DISubprogram(name: "equals_lower", linkageName: "_ZNK4llvm9StringRef12equals_lowerES0_", scope: !1578, file: !1579, line: 135, type: !1630, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1633 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm9StringRef7compareES0_", scope: !1578, file: !1579, line: 141, type: !1634, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1634 = !DISubroutineType(types: !1635)
!1635 = !{!324, !1613, !1578}
!1636 = !DISubprogram(name: "compare_lower", linkageName: "_ZNK4llvm9StringRef13compare_lowerES0_", scope: !1578, file: !1579, line: 153, type: !1634, scopeLine: 153, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1637 = !DISubprogram(name: "compare_numeric", linkageName: "_ZNK4llvm9StringRef15compare_numericES0_", scope: !1578, file: !1579, line: 157, type: !1634, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1638 = !DISubprogram(name: "edit_distance", linkageName: "_ZNK4llvm9StringRef13edit_distanceES0_bj", scope: !1578, file: !1579, line: 177, type: !1639, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1639 = !DISubroutineType(types: !1640)
!1640 = !{!6, !1613, !1578, !308, !6}
!1641 = !DISubprogram(name: "str", linkageName: "_ZNK4llvm9StringRef3strB5cxx11Ev", scope: !1578, file: !1579, line: 181, type: !1642, scopeLine: 181, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1642 = !DISubroutineType(types: !1643)
!1643 = !{!350, !1613}
!1644 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm9StringRefixEm", scope: !1578, file: !1579, line: 190, type: !1645, scopeLine: 190, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1645 = !DISubroutineType(types: !1646)
!1646 = !{!374, !1613, !1583}
!1647 = !DISubprogram(name: "operator basic_string", linkageName: "_ZNK4llvm9StringRefcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv", scope: !1578, file: !1579, line: 199, type: !1642, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1648 = !DISubprogram(name: "startswith", linkageName: "_ZNK4llvm9StringRef10startswithES0_", scope: !1578, file: !1579, line: 208, type: !1630, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1649 = !DISubprogram(name: "startswith_lower", linkageName: "_ZNK4llvm9StringRef16startswith_lowerES0_", scope: !1578, file: !1579, line: 214, type: !1630, scopeLine: 214, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1650 = !DISubprogram(name: "endswith", linkageName: "_ZNK4llvm9StringRef8endswithES0_", scope: !1578, file: !1579, line: 217, type: !1630, scopeLine: 217, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1651 = !DISubprogram(name: "endswith_lower", linkageName: "_ZNK4llvm9StringRef14endswith_lowerES0_", scope: !1578, file: !1579, line: 223, type: !1630, scopeLine: 223, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1652 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm9StringRef4findEcm", scope: !1578, file: !1579, line: 233, type: !1653, scopeLine: 233, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1653 = !DISubroutineType(types: !1654)
!1654 = !{!1583, !1613, !374, !1583}
!1655 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm9StringRef4findES0_m", scope: !1578, file: !1579, line: 244, type: !1656, scopeLine: 244, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1656 = !DISubroutineType(types: !1657)
!1657 = !{!1583, !1613, !1578, !1583}
!1658 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm9StringRef5rfindEcm", scope: !1578, file: !1579, line: 250, type: !1653, scopeLine: 250, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1659 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm9StringRef5rfindES0_", scope: !1578, file: !1579, line: 265, type: !1660, scopeLine: 265, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1660 = !DISubroutineType(types: !1661)
!1661 = !{!1583, !1613, !1578}
!1662 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm9StringRef13find_first_ofEcm", scope: !1578, file: !1579, line: 269, type: !1653, scopeLine: 269, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1663 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm9StringRef13find_first_ofES0_m", scope: !1578, file: !1579, line: 277, type: !1656, scopeLine: 277, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1664 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm9StringRef17find_first_not_ofEcm", scope: !1578, file: !1579, line: 281, type: !1653, scopeLine: 281, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1665 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm9StringRef17find_first_not_ofES0_m", scope: !1578, file: !1579, line: 287, type: !1656, scopeLine: 287, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1666 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm9StringRef12find_last_ofEcm", scope: !1578, file: !1579, line: 291, type: !1653, scopeLine: 291, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1667 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm9StringRef12find_last_ofES0_m", scope: !1578, file: !1579, line: 299, type: !1656, scopeLine: 299, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1668 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNK4llvm9StringRef16find_last_not_ofEcm", scope: !1578, file: !1579, line: 303, type: !1653, scopeLine: 303, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1669 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNK4llvm9StringRef16find_last_not_ofES0_m", scope: !1578, file: !1579, line: 309, type: !1656, scopeLine: 309, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1670 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9StringRef5countEc", scope: !1578, file: !1579, line: 316, type: !1671, scopeLine: 316, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1671 = !DISubroutineType(types: !1672)
!1672 = !{!1583, !1613, !374}
!1673 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9StringRef5countES0_", scope: !1578, file: !1579, line: 326, type: !1660, scopeLine: 326, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1674 = !DISubprogram(name: "getAsInteger", linkageName: "_ZNK4llvm9StringRef12getAsIntegerEjRNS_5APIntE", scope: !1578, file: !1579, line: 367, type: !1675, scopeLine: 367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1675 = !DISubroutineType(types: !1676)
!1676 = !{!308, !1613, !6, !1677}
!1677 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1678, size: 64)
!1678 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "APInt", scope: !342, file: !1579, line: 24, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm5APIntE")
!1679 = !DISubprogram(name: "lower", linkageName: "_ZNK4llvm9StringRef5lowerB5cxx11Ev", scope: !1578, file: !1579, line: 374, type: !1642, scopeLine: 374, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1680 = !DISubprogram(name: "upper", linkageName: "_ZNK4llvm9StringRef5upperB5cxx11Ev", scope: !1578, file: !1579, line: 377, type: !1642, scopeLine: 377, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1681 = !DISubprogram(name: "substr", linkageName: "_ZNK4llvm9StringRef6substrEmm", scope: !1578, file: !1579, line: 392, type: !1682, scopeLine: 392, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1682 = !DISubroutineType(types: !1683)
!1683 = !{!1578, !1613, !1583, !1583}
!1684 = !DISubprogram(name: "drop_front", linkageName: "_ZNK4llvm9StringRef10drop_frontEm", scope: !1578, file: !1579, line: 399, type: !1685, scopeLine: 399, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1685 = !DISubroutineType(types: !1686)
!1686 = !{!1578, !1613, !1583}
!1687 = !DISubprogram(name: "drop_back", linkageName: "_ZNK4llvm9StringRef9drop_backEm", scope: !1578, file: !1579, line: 406, type: !1685, scopeLine: 406, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1688 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm9StringRef5sliceEmm", scope: !1578, file: !1579, line: 421, type: !1682, scopeLine: 421, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1689 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitEc", scope: !1578, file: !1579, line: 437, type: !1690, scopeLine: 437, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1690 = !DISubroutineType(types: !1691)
!1691 = !{!1692, !1613, !374}
!1692 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::StringRef, llvm::StringRef>", scope: !353, file: !1693, line: 208, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1694, templateParams: !1753, identifier: "_ZTSSt4pairIN4llvm9StringRefES1_E")
!1693 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_pair.h", directory: "", checksumkind: CSK_MD5, checksum: "9a7996187125e471e26ca57a6c9f4c5e")
!1694 = !{!1695, !1715, !1716, !1717, !1723, !1727, !1741, !1750}
!1695 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1692, baseType: !1696, flags: DIFlagPrivate, extraData: i32 0)
!1696 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::StringRef, llvm::StringRef>", scope: !353, file: !1693, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !1697, templateParams: !1712, identifier: "_ZTSSt11__pair_baseIN4llvm9StringRefES1_E")
!1697 = !{!1698, !1702, !1703, !1708}
!1698 = !DISubprogram(name: "__pair_base", scope: !1696, file: !1693, line: 194, type: !1699, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1699 = !DISubroutineType(types: !1700)
!1700 = !{null, !1701}
!1701 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1696, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1702 = !DISubprogram(name: "~__pair_base", scope: !1696, file: !1693, line: 195, type: !1699, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1703 = !DISubprogram(name: "__pair_base", scope: !1696, file: !1693, line: 196, type: !1704, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1704 = !DISubroutineType(types: !1705)
!1705 = !{null, !1701, !1706}
!1706 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1707, size: 64)
!1707 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1696)
!1708 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN4llvm9StringRefES1_EaSERKS2_", scope: !1696, file: !1693, line: 197, type: !1709, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1709 = !DISubroutineType(types: !1710)
!1710 = !{!1711, !1701, !1706}
!1711 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1696, size: 64)
!1712 = !{!1713, !1714}
!1713 = !DITemplateTypeParameter(name: "_U1", type: !1578)
!1714 = !DITemplateTypeParameter(name: "_U2", type: !1578)
!1715 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !1692, file: !1693, line: 214, baseType: !1578, size: 128)
!1716 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !1692, file: !1693, line: 215, baseType: !1578, size: 128, offset: 128)
!1717 = !DISubprogram(name: "pair", scope: !1692, file: !1693, line: 303, type: !1718, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1718 = !DISubroutineType(types: !1719)
!1719 = !{null, !1720, !1721}
!1720 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1692, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1721 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1722, size: 64)
!1722 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1692)
!1723 = !DISubprogram(name: "pair", scope: !1692, file: !1693, line: 304, type: !1724, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1724 = !DISubroutineType(types: !1725)
!1725 = !{null, !1720, !1726}
!1726 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1692, size: 64)
!1727 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_EaSERKS2_", scope: !1692, file: !1693, line: 378, type: !1728, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1728 = !DISubroutineType(types: !1729)
!1729 = !{!1730, !1720, !1731}
!1730 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1692, size: 64)
!1731 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1733, file: !1732, line: 1928, baseType: !1721)
!1732 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/type_traits", directory: "")
!1733 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::StringRef, llvm::StringRef> &, const std::__nonesuch_no_braces &>", scope: !353, file: !1732, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !1734, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN4llvm9StringRefES2_ERKSt20__nonesuch_no_bracesE")
!1734 = !{!1735, !1736, !1737}
!1735 = !DITemplateValueParameter(name: "_Cond", type: !308, value: i8 1)
!1736 = !DITemplateTypeParameter(name: "_Iftrue", type: !1721)
!1737 = !DITemplateTypeParameter(name: "_Iffalse", type: !1738)
!1738 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1739, size: 64)
!1739 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1740)
!1740 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__nonesuch_no_braces", scope: !353, file: !1693, line: 185, size: 8, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt20__nonesuch_no_braces")
!1741 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_EaSEOS2_", scope: !1692, file: !1693, line: 389, type: !1742, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1742 = !DISubroutineType(types: !1743)
!1743 = !{!1730, !1720, !1744}
!1744 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1745, file: !1732, line: 1928, baseType: !1726)
!1745 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::StringRef, llvm::StringRef> &&, std::__nonesuch_no_braces &&>", scope: !353, file: !1732, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !1746, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN4llvm9StringRefES2_EOSt20__nonesuch_no_bracesE")
!1746 = !{!1735, !1747, !1748}
!1747 = !DITemplateTypeParameter(name: "_Iftrue", type: !1726)
!1748 = !DITemplateTypeParameter(name: "_Iffalse", type: !1749)
!1749 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1740, size: 64)
!1750 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_E4swapERS2_", scope: !1692, file: !1693, line: 424, type: !1751, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1751 = !DISubroutineType(types: !1752)
!1752 = !{null, !1720, !1730}
!1753 = !{!1754, !1755}
!1754 = !DITemplateTypeParameter(name: "_T1", type: !1578)
!1755 = !DITemplateTypeParameter(name: "_T2", type: !1578)
!1756 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitES0_", scope: !1578, file: !1579, line: 454, type: !1757, scopeLine: 454, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1757 = !DISubroutineType(types: !1758)
!1758 = !{!1692, !1613, !1578}
!1759 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitERNS_15SmallVectorImplIS0_EES0_ib", scope: !1578, file: !1579, line: 475, type: !1760, scopeLine: 475, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1760 = !DISubroutineType(types: !1761)
!1761 = !{null, !1613, !1762, !1578, !324, !308}
!1762 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1763, size: 64)
!1763 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<llvm::StringRef>", scope: !342, file: !1579, line: 23, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm15SmallVectorImplINS_9StringRefEEE")
!1764 = !DISubprogram(name: "rsplit", linkageName: "_ZNK4llvm9StringRef6rsplitEc", scope: !1578, file: !1579, line: 489, type: !1690, scopeLine: 489, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1765 = !DISubprogram(name: "ltrim", linkageName: "_ZNK4llvm9StringRef5ltrimES0_", scope: !1578, file: !1579, line: 498, type: !1766, scopeLine: 498, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1766 = !DISubroutineType(types: !1767)
!1767 = !{!1578, !1613, !1578}
!1768 = !DISubprogram(name: "rtrim", linkageName: "_ZNK4llvm9StringRef5rtrimES0_", scope: !1578, file: !1579, line: 504, type: !1766, scopeLine: 504, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1769 = !DISubprogram(name: "trim", linkageName: "_ZNK4llvm9StringRef4trimES0_", scope: !1578, file: !1579, line: 510, type: !1766, scopeLine: 510, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1770 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1771, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1771 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1545)
!1772 = !DISubprogram(name: "getValue", linkageName: "_ZNK4llvm14StringMapEntryIPN5clang14IdentifierInfoEE8getValueEv", scope: !1545, file: !1546, line: 132, type: !1773, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1773 = !DISubroutineType(types: !1774)
!1774 = !{!1573, !1770}
!1775 = !DISubprogram(name: "getValue", linkageName: "_ZN4llvm14StringMapEntryIPN5clang14IdentifierInfoEE8getValueEv", scope: !1545, file: !1546, line: 133, type: !1776, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1776 = !DISubroutineType(types: !1777)
!1777 = !{!1778, !1565}
!1778 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1348, size: 64)
!1779 = !DISubprogram(name: "setValue", linkageName: "_ZN4llvm14StringMapEntryIPN5clang14IdentifierInfoEE8setValueERKS3_", scope: !1545, file: !1546, line: 135, type: !1780, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1780 = !DISubroutineType(types: !1781)
!1781 = !{null, !1565, !1573}
!1782 = !DISubprogram(name: "getKeyData", linkageName: "_ZNK4llvm14StringMapEntryIPN5clang14IdentifierInfoEE10getKeyDataEv", scope: !1545, file: !1546, line: 140, type: !1783, scopeLine: 140, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1783 = !DISubroutineType(types: !1784)
!1784 = !{!407, !1770}
!1785 = !DISubprogram(name: "first", linkageName: "_ZNK4llvm14StringMapEntryIPN5clang14IdentifierInfoEE5firstEv", scope: !1545, file: !1546, line: 142, type: !1576, scopeLine: 142, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1786 = !DISubprogram(name: "Create", linkageName: "_ZN4llvm14StringMapEntryIPN5clang14IdentifierInfoEE6CreateEPKcS6_", scope: !1545, file: !1546, line: 190, type: !1787, scopeLine: 190, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1787 = !DISubroutineType(types: !1788)
!1788 = !{!1789, !407, !407}
!1789 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1545, size: 64)
!1790 = !DISubprogram(name: "GetStringMapEntryFromValue", linkageName: "_ZN4llvm14StringMapEntryIPN5clang14IdentifierInfoEE26GetStringMapEntryFromValueERS3_", scope: !1545, file: !1546, line: 196, type: !1791, scopeLine: 196, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1791 = !DISubroutineType(types: !1792)
!1792 = !{!1566, !1778}
!1793 = !DISubprogram(name: "GetStringMapEntryFromValue", linkageName: "_ZN4llvm14StringMapEntryIPN5clang14IdentifierInfoEE26GetStringMapEntryFromValueERKS3_", scope: !1545, file: !1546, line: 203, type: !1794, scopeLine: 203, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1794 = !DISubroutineType(types: !1795)
!1795 = !{!1796, !1573}
!1796 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1771, size: 64)
!1797 = !DISubprogram(name: "GetStringMapEntryFromKeyData", linkageName: "_ZN4llvm14StringMapEntryIPN5clang14IdentifierInfoEE28GetStringMapEntryFromKeyDataEPKc", scope: !1545, file: !1546, line: 209, type: !1798, scopeLine: 209, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1798 = !DISubroutineType(types: !1799)
!1799 = !{!1566, !407}
!1800 = !DISubprogram(name: "Destroy", linkageName: "_ZN4llvm14StringMapEntryIPN5clang14IdentifierInfoEE7DestroyEv", scope: !1545, file: !1546, line: 224, type: !1801, scopeLine: 224, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1801 = !DISubroutineType(types: !1802)
!1802 = !{null, !1565}
!1803 = !{!1804}
!1804 = !DITemplateTypeParameter(name: "ValueTy", type: !1348)
!1805 = !{!1806}
!1806 = !DIEnumerator(name: "Alignment", value: 8, isUnsigned: true)
!1807 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !1808, file: !1541, line: 39, baseType: !6, size: 32, elements: !1805, identifier: "_ZTSN4llvm7AlignOfIN5clang14IdentifierInfoEEUt_E")
!1808 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignOf<clang::IdentifierInfo>", scope: !342, file: !1541, line: 38, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !1809, identifier: "_ZTSN4llvm7AlignOfIN5clang14IdentifierInfoEEE")
!1809 = !{!1810}
!1810 = !DITemplateTypeParameter(name: "T", type: !1349)
!1811 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !1812, file: !1350, line: 850, baseType: !6, size: 32, elements: !1824, identifier: "_ZTSN4llvm21PointerLikeTypeTraitsIPKN5clang14IdentifierInfoEEUt_E")
!1812 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerLikeTypeTraits<const clang::IdentifierInfo *>", scope: !342, file: !1350, line: 842, size: 8, flags: DIFlagTypePassByValue, elements: !1813, templateParams: !1822, identifier: "_ZTSN4llvm21PointerLikeTypeTraitsIPKN5clang14IdentifierInfoEEE")
!1813 = !{!1814, !1819}
!1814 = !DISubprogram(name: "getAsVoidPointer", linkageName: "_ZN4llvm21PointerLikeTypeTraitsIPKN5clang14IdentifierInfoEE16getAsVoidPointerES4_", scope: !1812, file: !1350, line: 844, type: !1815, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1815 = !DISubroutineType(types: !1816)
!1816 = !{!334, !1817}
!1817 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1818, size: 64)
!1818 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1349)
!1819 = !DISubprogram(name: "getFromVoidPointer", linkageName: "_ZN4llvm21PointerLikeTypeTraitsIPKN5clang14IdentifierInfoEE18getFromVoidPointerEPKv", scope: !1812, file: !1350, line: 847, type: !1820, scopeLine: 847, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1820 = !DISubroutineType(types: !1821)
!1821 = !{!1817, !334}
!1822 = !{!1823}
!1823 = !DITemplateTypeParameter(name: "T", type: !1817)
!1824 = !{!1825}
!1825 = !DIEnumerator(name: "NumLowBitsAvailable", value: 1, isUnsigned: true)
!1826 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "Kind", scope: !1828, file: !1827, line: 323, baseType: !6, size: 32, elements: !1829, identifier: "_ZTSN5clang14MacroDirective4KindE")
!1827 = !DIFile(filename: "llvm34/projects/clang/include/clang/Lex/MacroInfo.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "8e70dc8f9390b02811179410a0c5da5c")
!1828 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MacroDirective", scope: !14, file: !1827, line: 321, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang14MacroDirectiveE")
!1829 = !{!1830, !1831, !1832}
!1830 = !DIEnumerator(name: "MD_Define", value: 0, isUnsigned: true)
!1831 = !DIEnumerator(name: "MD_Undefine", value: 1, isUnsigned: true)
!1832 = !DIEnumerator(name: "MD_Visibility", value: 2, isUnsigned: true)
!1833 = !{!308, !324, !1834, !953, !1835, !1838, !1348, !1966, !6, !373, !2094, !334, !2036, !1583, !2193, !330, !2032, !360, !917, !417, !2278, !2372, !2517, !2392, !2388, !2519, !2542, !407, !2608, !1837, !2618, !2708, !2711, !1789, !2712, !1817, !2716, !2719, !2776, !2777, !1826, !2779, !2793, !2795, !2809, !2812, !2071, !2067, !415, !2908, !3021, !2923, !3079, !3128, !3129, !3023, !2322, !3184, !3268, !1305, !2798, !3338, !294, !297, !3387, !3390, !3393, !2095, !1971, !1890, !1932, !377, !383, !354, !472, !3505, !1578, !1696, !1692, !2927, !2924, !3518, !3522, !3185, !3188, !2279, !3633, !3637, !3658, !2432, !2429, !3675, !3678, !3769, !2555, !2552, !1545, !1549, !3798, !3801, !2724, !2721, !3912, !3982, !2194, !2197, !1968, !4016, !4050, !4053, !4056, !2813, !4165, !3130, !4185, !4188, !4191, !2619}
!1834 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1828, size: 64)
!1835 = !DIDerivedType(tag: DW_TAG_typedef, name: "intptr_t", file: !1836, line: 97, baseType: !1837)
!1836 = !DIFile(filename: "/usr/include/stdint.h", directory: "", checksumkind: CSK_MD5, checksum: "c7469e3b87cb3d1a363efabd19f04208")
!1837 = !DIBasicType(name: "long", size: 64, encoding: DW_ATE_signed)
!1838 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DiagnosticBuilder", scope: !14, file: !1430, line: 849, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1839, identifier: "_ZTSN5clang17DiagnosticBuilderE")
!1839 = !{!1840, !1842, !1843, !1844, !1845, !1846, !1847, !1853, !1856, !1859, !1860, !1864, !1867, !1870, !1871, !1874, !1875, !1878, !1879, !1882, !1885, !1927, !1964, !1965}
!1840 = !DIDerivedType(tag: DW_TAG_member, name: "DiagObj", scope: !1838, file: !1430, line: 850, baseType: !1841, size: 64)
!1841 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1431, size: 64)
!1842 = !DIDerivedType(tag: DW_TAG_member, name: "NumArgs", scope: !1838, file: !1430, line: 851, baseType: !6, size: 32, offset: 64)
!1843 = !DIDerivedType(tag: DW_TAG_member, name: "NumRanges", scope: !1838, file: !1430, line: 851, baseType: !6, size: 32, offset: 96)
!1844 = !DIDerivedType(tag: DW_TAG_member, name: "NumFixits", scope: !1838, file: !1430, line: 851, baseType: !6, size: 32, offset: 128)
!1845 = !DIDerivedType(tag: DW_TAG_member, name: "IsActive", scope: !1838, file: !1430, line: 858, baseType: !308, size: 8, offset: 160)
!1846 = !DIDerivedType(tag: DW_TAG_member, name: "IsForceEmit", scope: !1838, file: !1430, line: 862, baseType: !308, size: 8, offset: 168)
!1847 = !DISubprogram(name: "operator=", linkageName: "_ZN5clang17DiagnosticBuilderaSERKS0_", scope: !1838, file: !1430, line: 864, type: !1848, scopeLine: 864, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1848 = !DISubroutineType(types: !1849)
!1849 = !{null, !1850, !1851}
!1850 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1838, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1851 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1852, size: 64)
!1852 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1838)
!1853 = !DISubprogram(name: "DiagnosticBuilder", scope: !1838, file: !1430, line: 867, type: !1854, scopeLine: 867, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1854 = !DISubroutineType(types: !1855)
!1855 = !{null, !1850}
!1856 = !DISubprogram(name: "DiagnosticBuilder", scope: !1838, file: !1430, line: 871, type: !1857, scopeLine: 871, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1857 = !DISubroutineType(types: !1858)
!1858 = !{null, !1850, !1841}
!1859 = !DISubprogram(name: "FlushCounts", linkageName: "_ZN5clang17DiagnosticBuilder11FlushCountsEv", scope: !1838, file: !1430, line: 880, type: !1854, scopeLine: 880, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1860 = !DISubprogram(name: "Clear", linkageName: "_ZNK5clang17DiagnosticBuilder5ClearEv", scope: !1838, file: !1430, line: 887, type: !1861, scopeLine: 887, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1861 = !DISubroutineType(types: !1862)
!1862 = !{null, !1863}
!1863 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1852, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1864 = !DISubprogram(name: "isActive", linkageName: "_ZNK5clang17DiagnosticBuilder8isActiveEv", scope: !1838, file: !1430, line: 894, type: !1865, scopeLine: 894, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1865 = !DISubroutineType(types: !1866)
!1866 = !{!308, !1863}
!1867 = !DISubprogram(name: "Emit", linkageName: "_ZN5clang17DiagnosticBuilder4EmitEv", scope: !1838, file: !1430, line: 903, type: !1868, scopeLine: 903, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1868 = !DISubroutineType(types: !1869)
!1869 = !{!308, !1850}
!1870 = !DISubprogram(name: "DiagnosticBuilder", scope: !1838, file: !1430, line: 924, type: !1848, scopeLine: 924, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1871 = !DISubprogram(name: "getEmpty", linkageName: "_ZN5clang17DiagnosticBuilder8getEmptyEv", scope: !1838, file: !1430, line: 935, type: !1872, scopeLine: 935, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1872 = !DISubroutineType(types: !1873)
!1873 = !{!1838}
!1874 = !DISubprogram(name: "~DiagnosticBuilder", scope: !1838, file: !1430, line: 940, type: !1854, scopeLine: 940, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1875 = !DISubprogram(name: "setForceEmit", linkageName: "_ZNK5clang17DiagnosticBuilder12setForceEmitEv", scope: !1838, file: !1430, line: 945, type: !1876, scopeLine: 945, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1876 = !DISubroutineType(types: !1877)
!1877 = !{!1851, !1863}
!1878 = !DISubprogram(name: "operator bool", linkageName: "_ZNK5clang17DiagnosticBuildercvbEv", scope: !1838, file: !1430, line: 957, type: !1865, scopeLine: 957, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1879 = !DISubprogram(name: "AddString", linkageName: "_ZNK5clang17DiagnosticBuilder9AddStringEN4llvm9StringRefE", scope: !1838, file: !1430, line: 959, type: !1880, scopeLine: 959, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1880 = !DISubroutineType(types: !1881)
!1881 = !{null, !1863, !1578}
!1882 = !DISubprogram(name: "AddTaggedVal", linkageName: "_ZNK5clang17DiagnosticBuilder12AddTaggedValElNS_17DiagnosticsEngine12ArgumentKindE", scope: !1838, file: !1430, line: 967, type: !1883, scopeLine: 967, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1883 = !DISubroutineType(types: !1884)
!1884 = !{null, !1863, !1835, !1429}
!1885 = !DISubprogram(name: "AddSourceRange", linkageName: "_ZNK5clang17DiagnosticBuilder14AddSourceRangeERKNS_15CharSourceRangeE", scope: !1838, file: !1430, line: 975, type: !1886, scopeLine: 975, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1886 = !DISubroutineType(types: !1887)
!1887 = !{null, !1863, !1888}
!1888 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1889, size: 64)
!1889 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1890)
!1890 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "CharSourceRange", scope: !14, file: !298, line: 225, size: 96, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1891, identifier: "_ZTSN5clang15CharSourceRangeE")
!1891 = !{!1892, !1893, !1894, !1898, !1901, !1904, !1905, !1908, !1909, !1913, !1914, !1917, !1918, !1921, !1924, !1925, !1926}
!1892 = !DIDerivedType(tag: DW_TAG_member, name: "Range", scope: !1890, file: !298, line: 226, baseType: !1305, size: 64)
!1893 = !DIDerivedType(tag: DW_TAG_member, name: "IsTokenRange", scope: !1890, file: !298, line: 227, baseType: !308, size: 8, offset: 64)
!1894 = !DISubprogram(name: "CharSourceRange", scope: !1890, file: !298, line: 229, type: !1895, scopeLine: 229, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1895 = !DISubroutineType(types: !1896)
!1896 = !{null, !1897}
!1897 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1890, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1898 = !DISubprogram(name: "CharSourceRange", scope: !1890, file: !298, line: 230, type: !1899, scopeLine: 230, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1899 = !DISubroutineType(types: !1900)
!1900 = !{null, !1897, !1305, !308}
!1901 = !DISubprogram(name: "getTokenRange", linkageName: "_ZN5clang15CharSourceRange13getTokenRangeENS_11SourceRangeE", scope: !1890, file: !298, line: 232, type: !1902, scopeLine: 232, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1902 = !DISubroutineType(types: !1903)
!1903 = !{!1890, !1305}
!1904 = !DISubprogram(name: "getCharRange", linkageName: "_ZN5clang15CharSourceRange12getCharRangeENS_11SourceRangeE", scope: !1890, file: !298, line: 236, type: !1902, scopeLine: 236, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1905 = !DISubprogram(name: "getTokenRange", linkageName: "_ZN5clang15CharSourceRange13getTokenRangeENS_14SourceLocationES1_", scope: !1890, file: !298, line: 240, type: !1906, scopeLine: 240, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1906 = !DISubroutineType(types: !1907)
!1907 = !{!1890, !297, !297}
!1908 = !DISubprogram(name: "getCharRange", linkageName: "_ZN5clang15CharSourceRange12getCharRangeENS_14SourceLocationES1_", scope: !1890, file: !298, line: 243, type: !1906, scopeLine: 243, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1909 = !DISubprogram(name: "isTokenRange", linkageName: "_ZNK5clang15CharSourceRange12isTokenRangeEv", scope: !1890, file: !298, line: 250, type: !1910, scopeLine: 250, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1910 = !DISubroutineType(types: !1911)
!1911 = !{!308, !1912}
!1912 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1889, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1913 = !DISubprogram(name: "isCharRange", linkageName: "_ZNK5clang15CharSourceRange11isCharRangeEv", scope: !1890, file: !298, line: 251, type: !1910, scopeLine: 251, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1914 = !DISubprogram(name: "getBegin", linkageName: "_ZNK5clang15CharSourceRange8getBeginEv", scope: !1890, file: !298, line: 253, type: !1915, scopeLine: 253, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1915 = !DISubroutineType(types: !1916)
!1916 = !{!297, !1912}
!1917 = !DISubprogram(name: "getEnd", linkageName: "_ZNK5clang15CharSourceRange6getEndEv", scope: !1890, file: !298, line: 254, type: !1915, scopeLine: 254, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1918 = !DISubprogram(name: "getAsRange", linkageName: "_ZNK5clang15CharSourceRange10getAsRangeEv", scope: !1890, file: !298, line: 255, type: !1919, scopeLine: 255, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1919 = !DISubroutineType(types: !1920)
!1920 = !{!1334, !1912}
!1921 = !DISubprogram(name: "setBegin", linkageName: "_ZN5clang15CharSourceRange8setBeginENS_14SourceLocationE", scope: !1890, file: !298, line: 257, type: !1922, scopeLine: 257, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1922 = !DISubroutineType(types: !1923)
!1923 = !{null, !1897, !297}
!1924 = !DISubprogram(name: "setEnd", linkageName: "_ZN5clang15CharSourceRange6setEndENS_14SourceLocationE", scope: !1890, file: !298, line: 258, type: !1922, scopeLine: 258, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1925 = !DISubprogram(name: "isValid", linkageName: "_ZNK5clang15CharSourceRange7isValidEv", scope: !1890, file: !298, line: 260, type: !1910, scopeLine: 260, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1926 = !DISubprogram(name: "isInvalid", linkageName: "_ZNK5clang15CharSourceRange9isInvalidEv", scope: !1890, file: !298, line: 261, type: !1910, scopeLine: 261, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1927 = !DISubprogram(name: "AddFixItHint", linkageName: "_ZNK5clang17DiagnosticBuilder12AddFixItHintERKNS_9FixItHintE", scope: !1838, file: !1430, line: 982, type: !1928, scopeLine: 982, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1928 = !DISubroutineType(types: !1929)
!1929 = !{null, !1863, !1930}
!1930 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1931, size: 64)
!1931 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1932)
!1932 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FixItHint", scope: !14, file: !1430, line: 48, size: 512, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1933, identifier: "_ZTSN5clang9FixItHintE")
!1933 = !{!1934, !1935, !1936, !1937, !1938, !1942, !1946, !1949, !1952, !1955, !1958, !1961}
!1934 = !DIDerivedType(tag: DW_TAG_member, name: "RemoveRange", scope: !1932, file: !1430, line: 52, baseType: !1890, size: 96, flags: DIFlagPublic)
!1935 = !DIDerivedType(tag: DW_TAG_member, name: "InsertFromRange", scope: !1932, file: !1430, line: 56, baseType: !1890, size: 96, offset: 96, flags: DIFlagPublic)
!1936 = !DIDerivedType(tag: DW_TAG_member, name: "CodeToInsert", scope: !1932, file: !1430, line: 60, baseType: !350, size: 256, offset: 192, flags: DIFlagPublic)
!1937 = !DIDerivedType(tag: DW_TAG_member, name: "BeforePreviousInsertions", scope: !1932, file: !1430, line: 62, baseType: !308, size: 8, offset: 448, flags: DIFlagPublic)
!1938 = !DISubprogram(name: "FixItHint", scope: !1932, file: !1430, line: 66, type: !1939, scopeLine: 66, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1939 = !DISubroutineType(types: !1940)
!1940 = !{null, !1941}
!1941 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1932, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1942 = !DISubprogram(name: "isNull", linkageName: "_ZNK5clang9FixItHint6isNullEv", scope: !1932, file: !1430, line: 68, type: !1943, scopeLine: 68, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1943 = !DISubroutineType(types: !1944)
!1944 = !{!308, !1945}
!1945 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1931, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1946 = !DISubprogram(name: "CreateInsertion", linkageName: "_ZN5clang9FixItHint15CreateInsertionENS_14SourceLocationEN4llvm9StringRefEb", scope: !1932, file: !1430, line: 74, type: !1947, scopeLine: 74, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1947 = !DISubroutineType(types: !1948)
!1948 = !{!1932, !297, !1578, !308}
!1949 = !DISubprogram(name: "CreateInsertionFromRange", linkageName: "_ZN5clang9FixItHint24CreateInsertionFromRangeENS_14SourceLocationENS_15CharSourceRangeEb", scope: !1932, file: !1430, line: 87, type: !1950, scopeLine: 87, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1950 = !DISubroutineType(types: !1951)
!1951 = !{!1932, !297, !1890, !308}
!1952 = !DISubprogram(name: "CreateRemoval", linkageName: "_ZN5clang9FixItHint13CreateRemovalENS_15CharSourceRangeE", scope: !1932, file: !1430, line: 100, type: !1953, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1953 = !DISubroutineType(types: !1954)
!1954 = !{!1932, !1890}
!1955 = !DISubprogram(name: "CreateRemoval", linkageName: "_ZN5clang9FixItHint13CreateRemovalENS_11SourceRangeE", scope: !1932, file: !1430, line: 105, type: !1956, scopeLine: 105, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1956 = !DISubroutineType(types: !1957)
!1957 = !{!1932, !1305}
!1958 = !DISubprogram(name: "CreateReplacement", linkageName: "_ZN5clang9FixItHint17CreateReplacementENS_15CharSourceRangeEN4llvm9StringRefE", scope: !1932, file: !1430, line: 111, type: !1959, scopeLine: 111, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1959 = !DISubroutineType(types: !1960)
!1960 = !{!1932, !1890, !1578}
!1961 = !DISubprogram(name: "CreateReplacement", linkageName: "_ZN5clang9FixItHint17CreateReplacementENS_11SourceRangeEN4llvm9StringRefE", scope: !1932, file: !1430, line: 119, type: !1962, scopeLine: 119, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1962 = !DISubroutineType(types: !1963)
!1963 = !{!1932, !1305, !1578}
!1964 = !DISubprogram(name: "hasMaxRanges", linkageName: "_ZNK5clang17DiagnosticBuilder12hasMaxRangesEv", scope: !1838, file: !1430, line: 989, type: !1865, scopeLine: 989, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1965 = !DISubprogram(name: "hasMaxFixItHints", linkageName: "_ZNK5clang17DiagnosticBuilder16hasMaxFixItHintsEv", scope: !1838, file: !1430, line: 993, type: !1865, scopeLine: 993, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1966 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !1968, file: !1967, line: 101, baseType: !2072)
!1967 = !DIFile(filename: "llvm34/include/llvm/ADT/SmallVector.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "69b512a6e55455ea0ed3a25fbee45d45")
!1968 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<clang::Token, void>", scope: !342, file: !1967, line: 66, size: 384, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1969, templateParams: !2091, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIN5clang5TokenEvEE")
!1969 = !{!1970, !1992, !2014, !2018, !2021, !2026, !2029, !2033, !2037, !2040, !2041, !2042, !2043, !2044, !2049, !2054, !2055, !2056, !2060, !2061, !2064, !2068, !2073, !2078, !2083, !2086, !2089, !2090}
!1970 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1968, baseType: !1971, flags: DIFlagPublic, extraData: i32 0)
!1971 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorBase", scope: !342, file: !1967, line: 33, size: 192, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1972, identifier: "_ZTSN4llvm15SmallVectorBaseE")
!1972 = !{!1973, !1974, !1975, !1976, !1980, !1983, !1988, !1989}
!1973 = !DIDerivedType(tag: DW_TAG_member, name: "BeginX", scope: !1971, file: !1967, line: 35, baseType: !330, size: 64, flags: DIFlagProtected)
!1974 = !DIDerivedType(tag: DW_TAG_member, name: "EndX", scope: !1971, file: !1967, line: 35, baseType: !330, size: 64, offset: 64, flags: DIFlagProtected)
!1975 = !DIDerivedType(tag: DW_TAG_member, name: "CapacityX", scope: !1971, file: !1967, line: 35, baseType: !330, size: 64, offset: 128, flags: DIFlagProtected)
!1976 = !DISubprogram(name: "SmallVectorBase", scope: !1971, file: !1967, line: 38, type: !1977, scopeLine: 38, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1977 = !DISubroutineType(types: !1978)
!1978 = !{null, !1979, !330, !1583}
!1979 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1971, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1980 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm15SmallVectorBase8grow_podEPvmm", scope: !1971, file: !1967, line: 43, type: !1981, scopeLine: 43, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1981 = !DISubroutineType(types: !1982)
!1982 = !{null, !1979, !330, !1583, !1583}
!1983 = !DISubprogram(name: "size_in_bytes", linkageName: "_ZNK4llvm15SmallVectorBase13size_in_bytesEv", scope: !1971, file: !1967, line: 47, type: !1984, scopeLine: 47, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1984 = !DISubroutineType(types: !1985)
!1985 = !{!1583, !1986}
!1986 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1987, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1987 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1971)
!1988 = !DISubprogram(name: "capacity_in_bytes", linkageName: "_ZNK4llvm15SmallVectorBase17capacity_in_bytesEv", scope: !1971, file: !1967, line: 52, type: !1984, scopeLine: 52, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1989 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm15SmallVectorBase5emptyEv", scope: !1971, file: !1967, line: 56, type: !1990, scopeLine: 56, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1990 = !DISubroutineType(types: !1991)
!1991 = !{!308, !1986}
!1992 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !1968, file: !1967, line: 74, baseType: !1993, size: 192, offset: 192)
!1993 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !1968, file: !1967, line: 73, baseType: !1994)
!1994 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<clang::Token, char, char, char, char, char, char>", scope: !342, file: !1541, line: 199, size: 192, flags: DIFlagTypePassByValue, elements: !1995, templateParams: !2006, identifier: "_ZTSN4llvm21AlignedCharArrayUnionIN5clang5TokenEccccccEE")
!1995 = !{!1996}
!1996 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1994, baseType: !1997, extraData: i32 0)
!1997 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<8UL, 24UL>", scope: !342, file: !1541, line: 75, size: 192, flags: DIFlagTypePassByValue, elements: !1998, templateParams: !2003, identifier: "_ZTSN4llvm16AlignedCharArrayILm8ELm24EEE")
!1998 = !{!1999}
!1999 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !1997, file: !1541, line: 76, baseType: !2000, size: 192, align: 64)
!2000 = !DICompositeType(tag: DW_TAG_array_type, baseType: !374, size: 192, elements: !2001)
!2001 = !{!2002}
!2002 = !DISubrange(count: 24)
!2003 = !{!2004, !2005}
!2004 = !DITemplateValueParameter(name: "Alignment", type: !417, value: i64 8)
!2005 = !DITemplateValueParameter(name: "Size", type: !417, value: i64 24)
!2006 = !{!2007, !2008, !2009, !2010, !2011, !2012, !2013}
!2007 = !DITemplateTypeParameter(name: "T1", type: !294)
!2008 = !DITemplateTypeParameter(name: "T2", type: !374, defaulted: true)
!2009 = !DITemplateTypeParameter(name: "T3", type: !374, defaulted: true)
!2010 = !DITemplateTypeParameter(name: "T4", type: !374, defaulted: true)
!2011 = !DITemplateTypeParameter(name: "T5", type: !374, defaulted: true)
!2012 = !DITemplateTypeParameter(name: "T6", type: !374, defaulted: true)
!2013 = !DITemplateTypeParameter(name: "T7", type: !374, defaulted: true)
!2014 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !1968, file: !1967, line: 78, type: !2015, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2015 = !DISubroutineType(types: !2016)
!2016 = !{null, !2017, !1583}
!2017 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1968, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2018 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE8grow_podEmm", scope: !1968, file: !1967, line: 80, type: !2019, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2019 = !DISubroutineType(types: !2020)
!2020 = !{null, !2017, !1583, !1583}
!2021 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE7isSmallEv", scope: !1968, file: !1967, line: 86, type: !2022, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2022 = !DISubroutineType(types: !2023)
!2023 = !{!308, !2024}
!2024 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2025, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2025 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1968)
!2026 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE12resetToSmallEv", scope: !1968, file: !1967, line: 91, type: !2027, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2027 = !DISubroutineType(types: !2028)
!2028 = !{null, !2017}
!2029 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE6setEndEPS2_", scope: !1968, file: !1967, line: 95, type: !2030, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2030 = !DISubroutineType(types: !2031)
!2031 = !{null, !2017, !2032}
!2032 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !294, size: 64)
!2033 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE5beginEv", scope: !1968, file: !1967, line: 112, type: !2034, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2034 = !DISubroutineType(types: !2035)
!2035 = !{!2036, !2017}
!2036 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1968, file: !1967, line: 100, baseType: !2032)
!2037 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE5beginEv", scope: !1968, file: !1967, line: 113, type: !2038, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2038 = !DISubroutineType(types: !2039)
!2039 = !{!1966, !2024}
!2040 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE3endEv", scope: !1968, file: !1967, line: 114, type: !2034, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2041 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE3endEv", scope: !1968, file: !1967, line: 115, type: !2038, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2042 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE12capacity_ptrEv", scope: !1968, file: !1967, line: 117, type: !2034, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2043 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE12capacity_ptrEv", scope: !1968, file: !1967, line: 118, type: !2038, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2044 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE6rbeginEv", scope: !1968, file: !1967, line: 122, type: !2045, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2045 = !DISubroutineType(types: !2046)
!2046 = !{!2047, !2017}
!2047 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !1968, file: !1967, line: 104, baseType: !2048)
!2048 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<clang::Token *>", scope: !353, file: !572, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPN5clang5TokenEE")
!2049 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE6rbeginEv", scope: !1968, file: !1967, line: 123, type: !2050, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2050 = !DISubroutineType(types: !2051)
!2051 = !{!2052, !2024}
!2052 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !1968, file: !1967, line: 103, baseType: !2053)
!2053 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const clang::Token *>", scope: !353, file: !572, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKN5clang5TokenEE")
!2054 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE4rendEv", scope: !1968, file: !1967, line: 124, type: !2045, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2055 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE4rendEv", scope: !1968, file: !1967, line: 125, type: !2050, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2056 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE4sizeEv", scope: !1968, file: !1967, line: 127, type: !2057, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2057 = !DISubroutineType(types: !2058)
!2058 = !{!2059, !2024}
!2059 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !1967, line: 97, baseType: !1583)
!2060 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE8max_sizeEv", scope: !1968, file: !1967, line: 128, type: !2057, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2061 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE8capacityEv", scope: !1968, file: !1967, line: 132, type: !2062, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2062 = !DISubroutineType(types: !2063)
!2063 = !{!1583, !2024}
!2064 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE4dataEv", scope: !1968, file: !1967, line: 135, type: !2065, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2065 = !DISubroutineType(types: !2066)
!2066 = !{!2067, !2017}
!2067 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !1968, file: !1967, line: 108, baseType: !2032)
!2068 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE4dataEv", scope: !1968, file: !1967, line: 137, type: !2069, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2069 = !DISubroutineType(types: !2070)
!2070 = !{!2071, !2024}
!2071 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !1968, file: !1967, line: 109, baseType: !2072)
!2072 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1273, size: 64)
!2073 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang5TokenEvEixEj", scope: !1968, file: !1967, line: 139, type: !2074, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2074 = !DISubroutineType(types: !2075)
!2075 = !{!2076, !2017, !6}
!2076 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !1968, file: !1967, line: 106, baseType: !2077)
!2077 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !294, size: 64)
!2078 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang5TokenEvEixEj", scope: !1968, file: !1967, line: 143, type: !2079, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2079 = !DISubroutineType(types: !2080)
!2080 = !{!2081, !2024, !6}
!2081 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !1968, file: !1967, line: 107, baseType: !2082)
!2082 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1273, size: 64)
!2083 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE5frontEv", scope: !1968, file: !1967, line: 148, type: !2084, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2084 = !DISubroutineType(types: !2085)
!2085 = !{!2076, !2017}
!2086 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE5frontEv", scope: !1968, file: !1967, line: 152, type: !2087, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2087 = !DISubroutineType(types: !2088)
!2088 = !{!2081, !2024}
!2089 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE4backEv", scope: !1968, file: !1967, line: 157, type: !2084, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2090 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang5TokenEvE4backEv", scope: !1968, file: !1967, line: 161, type: !2087, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2091 = !{!2092, !2093}
!2092 = !DITemplateTypeParameter(name: "T", type: !294)
!2093 = !DITemplateTypeParameter(type: null, defaulted: true)
!2094 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2095, file: !1967, line: 100, baseType: !2132)
!2095 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<Bracket, void>", scope: !342, file: !1967, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2096, templateParams: !2191, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonI7BracketvEE")
!2096 = !{!2097, !2098, !2114, !2118, !2121, !2126, !2129, !2133, !2136, !2142, !2143, !2144, !2145, !2146, !2151, !2156, !2157, !2158, !2161, !2162, !2165, !2169, !2173, !2178, !2183, !2186, !2189, !2190}
!2097 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2095, baseType: !1971, flags: DIFlagPublic, extraData: i32 0)
!2098 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !2095, file: !1967, line: 74, baseType: !2099, size: 32, offset: 192)
!2099 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !2095, file: !1967, line: 73, baseType: !2100)
!2100 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<Bracket, char, char, char, char, char, char>", scope: !342, file: !1541, line: 199, size: 32, flags: DIFlagTypePassByValue, elements: !2101, templateParams: !2112, identifier: "_ZTSN4llvm21AlignedCharArrayUnionI7BracketccccccEE")
!2101 = !{!2102}
!2102 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2100, baseType: !2103, extraData: i32 0)
!2103 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<4UL, 4UL>", scope: !342, file: !1541, line: 75, size: 32, flags: DIFlagTypePassByValue, elements: !2104, templateParams: !2109, identifier: "_ZTSN4llvm16AlignedCharArrayILm4ELm4EEE")
!2104 = !{!2105}
!2105 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !2103, file: !1541, line: 76, baseType: !2106, size: 32, align: 32)
!2106 = !DICompositeType(tag: DW_TAG_array_type, baseType: !374, size: 32, elements: !2107)
!2107 = !{!2108}
!2108 = !DISubrange(count: 4)
!2109 = !{!2110, !2111}
!2110 = !DITemplateValueParameter(name: "Alignment", type: !417, value: i64 4)
!2111 = !DITemplateValueParameter(name: "Size", type: !417, value: i64 4)
!2112 = !{!2113, !2008, !2009, !2010, !2011, !2012, !2013}
!2113 = !DITemplateTypeParameter(name: "T1", type: !1449)
!2114 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !2095, file: !1967, line: 78, type: !2115, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2115 = !DISubroutineType(types: !2116)
!2116 = !{null, !2117, !1583}
!2117 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2095, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2118 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonI7BracketvE8grow_podEmm", scope: !2095, file: !1967, line: 80, type: !2119, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2119 = !DISubroutineType(types: !2120)
!2120 = !{null, !2117, !1583, !1583}
!2121 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonI7BracketvE7isSmallEv", scope: !2095, file: !1967, line: 86, type: !2122, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2122 = !DISubroutineType(types: !2123)
!2123 = !{!308, !2124}
!2124 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2125, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2125 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2095)
!2126 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonI7BracketvE12resetToSmallEv", scope: !2095, file: !1967, line: 91, type: !2127, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2127 = !DISubroutineType(types: !2128)
!2128 = !{null, !2117}
!2129 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonI7BracketvE6setEndEPS1_", scope: !2095, file: !1967, line: 95, type: !2130, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2130 = !DISubroutineType(types: !2131)
!2131 = !{null, !2117, !2132}
!2132 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1449, size: 64)
!2133 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonI7BracketvE5beginEv", scope: !2095, file: !1967, line: 112, type: !2134, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2134 = !DISubroutineType(types: !2135)
!2135 = !{!2094, !2117}
!2136 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonI7BracketvE5beginEv", scope: !2095, file: !1967, line: 113, type: !2137, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2137 = !DISubroutineType(types: !2138)
!2138 = !{!2139, !2124}
!2139 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !2095, file: !1967, line: 101, baseType: !2140)
!2140 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2141, size: 64)
!2141 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1449)
!2142 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonI7BracketvE3endEv", scope: !2095, file: !1967, line: 114, type: !2134, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2143 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonI7BracketvE3endEv", scope: !2095, file: !1967, line: 115, type: !2137, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2144 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonI7BracketvE12capacity_ptrEv", scope: !2095, file: !1967, line: 117, type: !2134, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2145 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonI7BracketvE12capacity_ptrEv", scope: !2095, file: !1967, line: 118, type: !2137, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2146 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonI7BracketvE6rbeginEv", scope: !2095, file: !1967, line: 122, type: !2147, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2147 = !DISubroutineType(types: !2148)
!2148 = !{!2149, !2117}
!2149 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !2095, file: !1967, line: 104, baseType: !2150)
!2150 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<Bracket *>", scope: !353, file: !572, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIP7BracketE")
!2151 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonI7BracketvE6rbeginEv", scope: !2095, file: !1967, line: 123, type: !2152, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2152 = !DISubroutineType(types: !2153)
!2153 = !{!2154, !2124}
!2154 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !2095, file: !1967, line: 103, baseType: !2155)
!2155 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const Bracket *>", scope: !353, file: !572, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPK7BracketE")
!2156 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonI7BracketvE4rendEv", scope: !2095, file: !1967, line: 124, type: !2147, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2157 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonI7BracketvE4rendEv", scope: !2095, file: !1967, line: 125, type: !2152, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2158 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonI7BracketvE4sizeEv", scope: !2095, file: !1967, line: 127, type: !2159, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2159 = !DISubroutineType(types: !2160)
!2160 = !{!2059, !2124}
!2161 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonI7BracketvE8max_sizeEv", scope: !2095, file: !1967, line: 128, type: !2159, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2162 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonI7BracketvE8capacityEv", scope: !2095, file: !1967, line: 132, type: !2163, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2163 = !DISubroutineType(types: !2164)
!2164 = !{!1583, !2124}
!2165 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonI7BracketvE4dataEv", scope: !2095, file: !1967, line: 135, type: !2166, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2166 = !DISubroutineType(types: !2167)
!2167 = !{!2168, !2117}
!2168 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2095, file: !1967, line: 108, baseType: !2132)
!2169 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonI7BracketvE4dataEv", scope: !2095, file: !1967, line: 137, type: !2170, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2170 = !DISubroutineType(types: !2171)
!2171 = !{!2172, !2124}
!2172 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !2095, file: !1967, line: 109, baseType: !2140)
!2173 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonI7BracketvEixEj", scope: !2095, file: !1967, line: 139, type: !2174, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2174 = !DISubroutineType(types: !2175)
!2175 = !{!2176, !2117, !6}
!2176 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2095, file: !1967, line: 106, baseType: !2177)
!2177 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1449, size: 64)
!2178 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonI7BracketvEixEj", scope: !2095, file: !1967, line: 143, type: !2179, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2179 = !DISubroutineType(types: !2180)
!2180 = !{!2181, !2124, !6}
!2181 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !2095, file: !1967, line: 107, baseType: !2182)
!2182 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2141, size: 64)
!2183 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonI7BracketvE5frontEv", scope: !2095, file: !1967, line: 148, type: !2184, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2184 = !DISubroutineType(types: !2185)
!2185 = !{!2176, !2117}
!2186 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonI7BracketvE5frontEv", scope: !2095, file: !1967, line: 152, type: !2187, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2187 = !DISubroutineType(types: !2188)
!2188 = !{!2181, !2124}
!2189 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonI7BracketvE4backEv", scope: !2095, file: !1967, line: 157, type: !2184, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2190 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonI7BracketvE4backEv", scope: !2095, file: !1967, line: 161, type: !2187, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2191 = !{!2192, !2093}
!2192 = !DITemplateTypeParameter(name: "T", type: !1449)
!2193 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2194, file: !1967, line: 377, baseType: !2277)
!2194 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<clang::Token>", scope: !342, file: !1967, line: 371, size: 384, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2195, templateParams: !2276, identifier: "_ZTSN4llvm15SmallVectorImplIN5clang5TokenEEE")
!2195 = !{!2196, !2216, !2222, !2225, !2228, !2229, !2230, !2233, !2234, !2237, !2241, !2244, !2245, !2249, !2252, !2256, !2259, !2262, !2265, !2269, !2273, !2274, !2275}
!2196 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2194, baseType: !2197, flags: DIFlagPublic, extraData: i32 0)
!2197 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<clang::Token, true>", scope: !342, file: !1967, line: 296, size: 384, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2198, templateParams: !2214, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseIN5clang5TokenELb1EEE")
!2198 = !{!2199, !2200, !2204, !2207, !2208, !2211}
!2199 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2197, baseType: !1968, flags: DIFlagPublic, extraData: i32 0)
!2200 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !2197, file: !1967, line: 298, type: !2201, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2201 = !DISubroutineType(types: !2202)
!2202 = !{null, !2203, !1583}
!2203 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2197, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2204 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIN5clang5TokenELb1EE13destroy_rangeEPS2_S4_", scope: !2197, file: !1967, line: 301, type: !2205, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2205 = !DISubroutineType(types: !2206)
!2206 = !{null, !2032, !2032}
!2207 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIN5clang5TokenELb1EE4growEm", scope: !2197, file: !1967, line: 346, type: !2201, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2208 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIN5clang5TokenELb1EE9push_backERKS2_", scope: !2197, file: !1967, line: 350, type: !2209, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2209 = !DISubroutineType(types: !2210)
!2210 = !{null, !2203, !2082}
!2211 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIN5clang5TokenELb1EE8pop_backEv", scope: !2197, file: !1967, line: 361, type: !2212, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2212 = !DISubroutineType(types: !2213)
!2213 = !{null, !2203}
!2214 = !{!2092, !2215}
!2215 = !DITemplateValueParameter(name: "isPodLike", type: !308, value: i8 1)
!2216 = !DISubprogram(name: "SmallVectorImpl", scope: !2194, file: !1967, line: 374, type: !2217, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2217 = !DISubroutineType(types: !2218)
!2218 = !{null, !2219, !2220}
!2219 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2194, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2220 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2221, size: 64)
!2221 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2194)
!2222 = !DISubprogram(name: "SmallVectorImpl", scope: !2194, file: !1967, line: 381, type: !2223, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2223 = !DISubroutineType(types: !2224)
!2224 = !{null, !2219, !6}
!2225 = !DISubprogram(name: "~SmallVectorImpl", scope: !2194, file: !1967, line: 386, type: !2226, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2226 = !DISubroutineType(types: !2227)
!2227 = !{null, !2219}
!2228 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEE5clearEv", scope: !2194, file: !1967, line: 396, type: !2226, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2229 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEE6resizeEj", scope: !2194, file: !1967, line: 401, type: !2223, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2230 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEE6resizeEjRKS2_", scope: !2194, file: !1967, line: 413, type: !2231, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2231 = !DISubroutineType(types: !2232)
!2232 = !{null, !2219, !6, !2082}
!2233 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEE7reserveEj", scope: !2194, file: !1967, line: 425, type: !2223, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2234 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEE12pop_back_valEv", scope: !2194, file: !1967, line: 430, type: !2235, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2235 = !DISubroutineType(types: !2236)
!2236 = !{!294, !2219}
!2237 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEE4swapERS3_", scope: !2194, file: !1967, line: 440, type: !2238, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2238 = !DISubroutineType(types: !2239)
!2239 = !{null, !2219, !2240}
!2240 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2194, size: 64)
!2241 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEE6appendEmRKS2_", scope: !2194, file: !1967, line: 460, type: !2242, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2242 = !DISubroutineType(types: !2243)
!2243 = !{null, !2219, !2193, !2082}
!2244 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEE6assignEjRKS2_", scope: !2194, file: !1967, line: 470, type: !2231, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2245 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEE5eraseEPS2_", scope: !2194, file: !1967, line: 478, type: !2246, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2246 = !DISubroutineType(types: !2247)
!2247 = !{!2248, !2219, !2248}
!2248 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2194, file: !1967, line: 376, baseType: !2036)
!2249 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEE5eraseEPS2_S4_", scope: !2194, file: !1967, line: 490, type: !2250, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2250 = !DISubroutineType(types: !2251)
!2251 = !{!2248, !2219, !2248, !2248}
!2252 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEE6insertEPS2_OS2_", scope: !2194, file: !1967, line: 505, type: !2253, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2253 = !DISubroutineType(types: !2254)
!2254 = !{!2248, !2219, !2248, !2255}
!2255 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !294, size: 64)
!2256 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEE6insertEPS2_RKS2_", scope: !2194, file: !1967, line: 537, type: !2257, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2257 = !DISubroutineType(types: !2258)
!2258 = !{!2248, !2219, !2248, !2082}
!2259 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEE6insertEPS2_mRKS2_", scope: !2194, file: !1967, line: 568, type: !2260, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2260 = !DISubroutineType(types: !2261)
!2261 = !{!2248, !2219, !2248, !2193, !2082}
!2262 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEEaSERKS3_", scope: !2194, file: !1967, line: 674, type: !2263, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2263 = !DISubroutineType(types: !2264)
!2264 = !{!2240, !2219, !2220}
!2265 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEEaSEOS3_", scope: !2194, file: !1967, line: 677, type: !2266, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2266 = !DISubroutineType(types: !2267)
!2267 = !{!2240, !2219, !2268}
!2268 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2194, size: 64)
!2269 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplIN5clang5TokenEEeqERKS3_", scope: !2194, file: !1967, line: 680, type: !2270, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2270 = !DISubroutineType(types: !2271)
!2271 = !{!308, !2272, !2220}
!2272 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2221, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2273 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplIN5clang5TokenEEneERKS3_", scope: !2194, file: !1967, line: 684, type: !2270, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2274 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplIN5clang5TokenEEltERKS3_", scope: !2194, file: !1967, line: 688, type: !2270, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2275 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplIN5clang5TokenEE8set_sizeEj", scope: !2194, file: !1967, line: 702, type: !2223, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2276 = !{!2092}
!2277 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !1968, file: !1967, line: 97, baseType: !1583)
!2278 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2279, file: !1967, line: 100, baseType: !373)
!2279 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<char, void>", scope: !342, file: !1967, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2280, templateParams: !2370, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIcvEE")
!2280 = !{!2281, !2282, !2298, !2302, !2305, !2310, !2313, !2316, !2319, !2323, !2324, !2325, !2326, !2327, !2332, !2337, !2338, !2339, !2342, !2343, !2346, !2350, !2354, !2358, !2362, !2365, !2368, !2369}
!2281 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2279, baseType: !1971, flags: DIFlagPublic, extraData: i32 0)
!2282 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !2279, file: !1967, line: 74, baseType: !2283, size: 8, offset: 192)
!2283 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !2279, file: !1967, line: 73, baseType: !2284)
!2284 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<char, char, char, char, char, char, char>", scope: !342, file: !1541, line: 199, size: 8, flags: DIFlagTypePassByValue, elements: !2285, templateParams: !2296, identifier: "_ZTSN4llvm21AlignedCharArrayUnionIcccccccEE")
!2285 = !{!2286}
!2286 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2284, baseType: !2287, extraData: i32 0)
!2287 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<1UL, 1UL>", scope: !342, file: !1541, line: 75, size: 8, flags: DIFlagTypePassByValue, elements: !2288, templateParams: !2293, identifier: "_ZTSN4llvm16AlignedCharArrayILm1ELm1EEE")
!2288 = !{!2289}
!2289 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !2287, file: !1541, line: 76, baseType: !2290, size: 8, align: 8)
!2290 = !DICompositeType(tag: DW_TAG_array_type, baseType: !374, size: 8, elements: !2291)
!2291 = !{!2292}
!2292 = !DISubrange(count: 1)
!2293 = !{!2294, !2295}
!2294 = !DITemplateValueParameter(name: "Alignment", type: !417, value: i64 1)
!2295 = !DITemplateValueParameter(name: "Size", type: !417, value: i64 1)
!2296 = !{!2297, !2008, !2009, !2010, !2011, !2012, !2013}
!2297 = !DITemplateTypeParameter(name: "T1", type: !374)
!2298 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !2279, file: !1967, line: 78, type: !2299, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2299 = !DISubroutineType(types: !2300)
!2300 = !{null, !2301, !1583}
!2301 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2279, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2302 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE8grow_podEmm", scope: !2279, file: !1967, line: 80, type: !2303, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2303 = !DISubroutineType(types: !2304)
!2304 = !{null, !2301, !1583, !1583}
!2305 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE7isSmallEv", scope: !2279, file: !1967, line: 86, type: !2306, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2306 = !DISubroutineType(types: !2307)
!2307 = !{!308, !2308}
!2308 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2309, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2309 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2279)
!2310 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE12resetToSmallEv", scope: !2279, file: !1967, line: 91, type: !2311, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2311 = !DISubroutineType(types: !2312)
!2312 = !{null, !2301}
!2313 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE6setEndEPc", scope: !2279, file: !1967, line: 95, type: !2314, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2314 = !DISubroutineType(types: !2315)
!2315 = !{null, !2301, !373}
!2316 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE5beginEv", scope: !2279, file: !1967, line: 112, type: !2317, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2317 = !DISubroutineType(types: !2318)
!2318 = !{!2278, !2301}
!2319 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE5beginEv", scope: !2279, file: !1967, line: 113, type: !2320, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2320 = !DISubroutineType(types: !2321)
!2321 = !{!2322, !2308}
!2322 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !2279, file: !1967, line: 101, baseType: !407)
!2323 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE3endEv", scope: !2279, file: !1967, line: 114, type: !2317, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2324 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE3endEv", scope: !2279, file: !1967, line: 115, type: !2320, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2325 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE12capacity_ptrEv", scope: !2279, file: !1967, line: 117, type: !2317, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2326 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE12capacity_ptrEv", scope: !2279, file: !1967, line: 118, type: !2320, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2327 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE6rbeginEv", scope: !2279, file: !1967, line: 122, type: !2328, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2328 = !DISubroutineType(types: !2329)
!2329 = !{!2330, !2301}
!2330 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !2279, file: !1967, line: 104, baseType: !2331)
!2331 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<char *>", scope: !353, file: !572, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPcE")
!2332 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE6rbeginEv", scope: !2279, file: !1967, line: 123, type: !2333, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2333 = !DISubroutineType(types: !2334)
!2334 = !{!2335, !2308}
!2335 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !2279, file: !1967, line: 103, baseType: !2336)
!2336 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const char *>", scope: !353, file: !572, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKcE")
!2337 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE4rendEv", scope: !2279, file: !1967, line: 124, type: !2328, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2338 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE4rendEv", scope: !2279, file: !1967, line: 125, type: !2333, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2339 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE4sizeEv", scope: !2279, file: !1967, line: 127, type: !2340, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2340 = !DISubroutineType(types: !2341)
!2341 = !{!2059, !2308}
!2342 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE8max_sizeEv", scope: !2279, file: !1967, line: 128, type: !2340, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2343 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE8capacityEv", scope: !2279, file: !1967, line: 132, type: !2344, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2344 = !DISubroutineType(types: !2345)
!2345 = !{!1583, !2308}
!2346 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE4dataEv", scope: !2279, file: !1967, line: 135, type: !2347, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2347 = !DISubroutineType(types: !2348)
!2348 = !{!2349, !2301}
!2349 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2279, file: !1967, line: 108, baseType: !373)
!2350 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE4dataEv", scope: !2279, file: !1967, line: 137, type: !2351, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2351 = !DISubroutineType(types: !2352)
!2352 = !{!2353, !2308}
!2353 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !2279, file: !1967, line: 109, baseType: !407)
!2354 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvEixEj", scope: !2279, file: !1967, line: 139, type: !2355, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2355 = !DISubroutineType(types: !2356)
!2356 = !{!2357, !2301, !6}
!2357 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2279, file: !1967, line: 106, baseType: !402)
!2358 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvEixEj", scope: !2279, file: !1967, line: 143, type: !2359, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2359 = !DISubroutineType(types: !2360)
!2360 = !{!2361, !2308, !6}
!2361 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !2279, file: !1967, line: 107, baseType: !410)
!2362 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE5frontEv", scope: !2279, file: !1967, line: 148, type: !2363, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2363 = !DISubroutineType(types: !2364)
!2364 = !{!2357, !2301}
!2365 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE5frontEv", scope: !2279, file: !1967, line: 152, type: !2366, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2366 = !DISubroutineType(types: !2367)
!2367 = !{!2361, !2308}
!2368 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIcvE4backEv", scope: !2279, file: !1967, line: 157, type: !2363, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2369 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIcvE4backEv", scope: !2279, file: !1967, line: 161, type: !2366, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2370 = !{!2371, !2093}
!2371 = !DITemplateTypeParameter(name: "T", type: !374)
!2372 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !2373, file: !1967, line: 101, baseType: !2374)
!2373 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<clang::SrcMgr::SLocEntry, void>", scope: !342, file: !1967, line: 66, size: 384, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIN5clang6SrcMgr9SLocEntryEvEE")
!2374 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2375, size: 64)
!2375 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2376)
!2376 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SLocEntry", scope: !1458, file: !346, line: 389, size: 192, flags: DIFlagTypePassByValue, elements: !2377, identifier: "_ZTSN5clang6SrcMgr9SLocEntryE")
!2377 = !{!2378, !2379, !2495, !2499, !2502, !2503, !2507, !2511, !2514}
!2378 = !DIDerivedType(tag: DW_TAG_member, name: "Offset", scope: !2376, file: !346, line: 390, baseType: !6, size: 32)
!2379 = !DIDerivedType(tag: DW_TAG_member, scope: !2376, file: !346, line: 391, baseType: !2380, size: 128, offset: 64)
!2380 = distinct !DICompositeType(tag: DW_TAG_union_type, scope: !2376, file: !346, line: 391, size: 128, flags: DIFlagExportSymbols | DIFlagTypePassByValue, elements: !2381, identifier: "_ZTSN5clang6SrcMgr9SLocEntryUt_E")
!2381 = !{!2382, !2413}
!2382 = !DIDerivedType(tag: DW_TAG_member, name: "File", scope: !2380, file: !346, line: 392, baseType: !2383, size: 128)
!2383 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FileInfo", scope: !1458, file: !346, line: 236, size: 128, flags: DIFlagTypePassByValue, elements: !2384, identifier: "_ZTSN5clang6SrcMgr8FileInfoE")
!2384 = !{!2385, !2386, !2387, !2389, !2395, !2400, !2403, !2406, !2409}
!2385 = !DIDerivedType(tag: DW_TAG_member, name: "IncludeLoc", scope: !2383, file: !346, line: 240, baseType: !6, size: 32)
!2386 = !DIDerivedType(tag: DW_TAG_member, name: "NumCreatedFIDs", scope: !2383, file: !346, line: 246, baseType: !6, size: 32, offset: 32)
!2387 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !2383, file: !346, line: 251, baseType: !2388, size: 64, offset: 64)
!2388 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintptr_t", file: !1836, line: 100, baseType: !417)
!2389 = !DISubprogram(name: "get", linkageName: "_ZN5clang6SrcMgr8FileInfo3getENS_14SourceLocationEPKNS0_12ContentCacheENS0_18CharacteristicKindE", scope: !2383, file: !346, line: 258, type: !2390, scopeLine: 258, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2390 = !DISubroutineType(types: !2391)
!2391 = !{!2383, !297, !2392, !1457}
!2392 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2393, size: 64)
!2393 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2394)
!2394 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ContentCache", scope: !1458, file: !346, line: 84, size: 320, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang6SrcMgr12ContentCacheE")
!2395 = !DISubprogram(name: "getIncludeLoc", linkageName: "_ZNK5clang6SrcMgr8FileInfo13getIncludeLocEv", scope: !2383, file: !346, line: 270, type: !2396, scopeLine: 270, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2396 = !DISubroutineType(types: !2397)
!2397 = !{!297, !2398}
!2398 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2399, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2399 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2383)
!2400 = !DISubprogram(name: "getContentCache", linkageName: "_ZNK5clang6SrcMgr8FileInfo15getContentCacheEv", scope: !2383, file: !346, line: 273, type: !2401, scopeLine: 273, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2401 = !DISubroutineType(types: !2402)
!2402 = !{!2392, !2398}
!2403 = !DISubprogram(name: "getFileCharacteristic", linkageName: "_ZNK5clang6SrcMgr8FileInfo21getFileCharacteristicEv", scope: !2383, file: !346, line: 278, type: !2404, scopeLine: 278, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2404 = !DISubroutineType(types: !2405)
!2405 = !{!1457, !2398}
!2406 = !DISubprogram(name: "hasLineDirectives", linkageName: "_ZNK5clang6SrcMgr8FileInfo17hasLineDirectivesEv", scope: !2383, file: !346, line: 283, type: !2407, scopeLine: 283, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2407 = !DISubroutineType(types: !2408)
!2408 = !{!308, !2398}
!2409 = !DISubprogram(name: "setHasLineDirectives", linkageName: "_ZN5clang6SrcMgr8FileInfo20setHasLineDirectivesEv", scope: !2383, file: !346, line: 287, type: !2410, scopeLine: 287, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2410 = !DISubroutineType(types: !2411)
!2411 = !{null, !2412}
!2412 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2383, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2413 = !DIDerivedType(tag: DW_TAG_member, name: "Expansion", scope: !2380, file: !346, line: 393, baseType: !2414, size: 96)
!2414 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ExpansionInfo", scope: !1458, file: !346, line: 295, size: 96, flags: DIFlagTypePassByValue, elements: !2415, identifier: "_ZTSN5clang6SrcMgr13ExpansionInfoE")
!2415 = !{!2416, !2417, !2418, !2419, !2424, !2425, !2426, !2484, !2487, !2488, !2489, !2492}
!2416 = !DIDerivedType(tag: DW_TAG_member, name: "SpellingLoc", scope: !2414, file: !346, line: 299, baseType: !6, size: 32)
!2417 = !DIDerivedType(tag: DW_TAG_member, name: "ExpansionLocStart", scope: !2414, file: !346, line: 307, baseType: !6, size: 32, offset: 32)
!2418 = !DIDerivedType(tag: DW_TAG_member, name: "ExpansionLocEnd", scope: !2414, file: !346, line: 307, baseType: !6, size: 32, offset: 64)
!2419 = !DISubprogram(name: "getSpellingLoc", linkageName: "_ZNK5clang6SrcMgr13ExpansionInfo14getSpellingLocEv", scope: !2414, file: !346, line: 310, type: !2420, scopeLine: 310, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2420 = !DISubroutineType(types: !2421)
!2421 = !{!297, !2422}
!2422 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2423, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2423 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2414)
!2424 = !DISubprogram(name: "getExpansionLocStart", linkageName: "_ZNK5clang6SrcMgr13ExpansionInfo20getExpansionLocStartEv", scope: !2414, file: !346, line: 313, type: !2420, scopeLine: 313, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2425 = !DISubprogram(name: "getExpansionLocEnd", linkageName: "_ZNK5clang6SrcMgr13ExpansionInfo18getExpansionLocEndEv", scope: !2414, file: !346, line: 316, type: !2420, scopeLine: 316, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2426 = !DISubprogram(name: "getExpansionLocRange", linkageName: "_ZNK5clang6SrcMgr13ExpansionInfo20getExpansionLocRangeEv", scope: !2414, file: !346, line: 322, type: !2427, scopeLine: 322, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2427 = !DISubroutineType(types: !2428)
!2428 = !{!2429, !2422}
!2429 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<clang::SourceLocation, clang::SourceLocation>", scope: !353, file: !1693, line: 208, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2430, templateParams: !2481, identifier: "_ZTSSt4pairIN5clang14SourceLocationES1_E")
!2430 = !{!2431, !2451, !2452, !2453, !2459, !2463, !2471, !2478}
!2431 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2429, baseType: !2432, flags: DIFlagPrivate, extraData: i32 0)
!2432 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<clang::SourceLocation, clang::SourceLocation>", scope: !353, file: !1693, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !2433, templateParams: !2448, identifier: "_ZTSSt11__pair_baseIN5clang14SourceLocationES1_E")
!2433 = !{!2434, !2438, !2439, !2444}
!2434 = !DISubprogram(name: "__pair_base", scope: !2432, file: !1693, line: 194, type: !2435, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2435 = !DISubroutineType(types: !2436)
!2436 = !{null, !2437}
!2437 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2432, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2438 = !DISubprogram(name: "~__pair_base", scope: !2432, file: !1693, line: 195, type: !2435, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2439 = !DISubprogram(name: "__pair_base", scope: !2432, file: !1693, line: 196, type: !2440, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2440 = !DISubroutineType(types: !2441)
!2441 = !{null, !2437, !2442}
!2442 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2443, size: 64)
!2443 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2432)
!2444 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN5clang14SourceLocationES1_EaSERKS2_", scope: !2432, file: !1693, line: 197, type: !2445, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2445 = !DISubroutineType(types: !2446)
!2446 = !{!2447, !2437, !2442}
!2447 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2432, size: 64)
!2448 = !{!2449, !2450}
!2449 = !DITemplateTypeParameter(name: "_U1", type: !297)
!2450 = !DITemplateTypeParameter(name: "_U2", type: !297)
!2451 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !2429, file: !1693, line: 214, baseType: !297, size: 32)
!2452 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !2429, file: !1693, line: 215, baseType: !297, size: 32, offset: 32)
!2453 = !DISubprogram(name: "pair", scope: !2429, file: !1693, line: 303, type: !2454, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2454 = !DISubroutineType(types: !2455)
!2455 = !{null, !2456, !2457}
!2456 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2429, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2457 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2458, size: 64)
!2458 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2429)
!2459 = !DISubprogram(name: "pair", scope: !2429, file: !1693, line: 304, type: !2460, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2460 = !DISubroutineType(types: !2461)
!2461 = !{null, !2456, !2462}
!2462 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2429, size: 64)
!2463 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN5clang14SourceLocationES1_EaSERKS2_", scope: !2429, file: !1693, line: 378, type: !2464, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2464 = !DISubroutineType(types: !2465)
!2465 = !{!2466, !2456, !2467}
!2466 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2429, size: 64)
!2467 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2468, file: !1732, line: 1928, baseType: !2457)
!2468 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<clang::SourceLocation, clang::SourceLocation> &, const std::__nonesuch_no_braces &>", scope: !353, file: !1732, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !2469, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN5clang14SourceLocationES2_ERKSt20__nonesuch_no_bracesE")
!2469 = !{!1735, !2470, !1737}
!2470 = !DITemplateTypeParameter(name: "_Iftrue", type: !2457)
!2471 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN5clang14SourceLocationES1_EaSEOS2_", scope: !2429, file: !1693, line: 389, type: !2472, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2472 = !DISubroutineType(types: !2473)
!2473 = !{!2466, !2456, !2474}
!2474 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2475, file: !1732, line: 1928, baseType: !2462)
!2475 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<clang::SourceLocation, clang::SourceLocation> &&, std::__nonesuch_no_braces &&>", scope: !353, file: !1732, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !2476, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN5clang14SourceLocationES2_EOSt20__nonesuch_no_bracesE")
!2476 = !{!1735, !2477, !1748}
!2477 = !DITemplateTypeParameter(name: "_Iftrue", type: !2462)
!2478 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN5clang14SourceLocationES1_E4swapERS2_", scope: !2429, file: !1693, line: 424, type: !2479, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2479 = !DISubroutineType(types: !2480)
!2480 = !{null, !2456, !2466}
!2481 = !{!2482, !2483}
!2482 = !DITemplateTypeParameter(name: "_T1", type: !297)
!2483 = !DITemplateTypeParameter(name: "_T2", type: !297)
!2484 = !DISubprogram(name: "isMacroArgExpansion", linkageName: "_ZNK5clang6SrcMgr13ExpansionInfo19isMacroArgExpansionEv", scope: !2414, file: !346, line: 326, type: !2485, scopeLine: 326, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2485 = !DISubroutineType(types: !2486)
!2486 = !{!308, !2422}
!2487 = !DISubprogram(name: "isMacroBodyExpansion", linkageName: "_ZNK5clang6SrcMgr13ExpansionInfo20isMacroBodyExpansionEv", scope: !2414, file: !346, line: 332, type: !2485, scopeLine: 332, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2488 = !DISubprogram(name: "isFunctionMacroExpansion", linkageName: "_ZNK5clang6SrcMgr13ExpansionInfo24isFunctionMacroExpansionEv", scope: !2414, file: !346, line: 337, type: !2485, scopeLine: 337, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2489 = !DISubprogram(name: "create", linkageName: "_ZN5clang6SrcMgr13ExpansionInfo6createENS_14SourceLocationES2_S2_", scope: !2414, file: !346, line: 348, type: !2490, scopeLine: 348, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2490 = !DISubroutineType(types: !2491)
!2491 = !{!2414, !297, !297, !297}
!2492 = !DISubprogram(name: "createForMacroArg", linkageName: "_ZN5clang6SrcMgr13ExpansionInfo17createForMacroArgENS_14SourceLocationES2_", scope: !2414, file: !346, line: 376, type: !2493, scopeLine: 376, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2493 = !DISubroutineType(types: !2494)
!2494 = !{!2414, !297, !297}
!2495 = !DISubprogram(name: "getOffset", linkageName: "_ZNK5clang6SrcMgr9SLocEntry9getOffsetEv", scope: !2376, file: !346, line: 396, type: !2496, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2496 = !DISubroutineType(types: !2497)
!2497 = !{!6, !2498}
!2498 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2375, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2499 = !DISubprogram(name: "isExpansion", linkageName: "_ZNK5clang6SrcMgr9SLocEntry11isExpansionEv", scope: !2376, file: !346, line: 398, type: !2500, scopeLine: 398, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2500 = !DISubroutineType(types: !2501)
!2501 = !{!308, !2498}
!2502 = !DISubprogram(name: "isFile", linkageName: "_ZNK5clang6SrcMgr9SLocEntry6isFileEv", scope: !2376, file: !346, line: 399, type: !2500, scopeLine: 399, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2503 = !DISubprogram(name: "getFile", linkageName: "_ZNK5clang6SrcMgr9SLocEntry7getFileEv", scope: !2376, file: !346, line: 401, type: !2504, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2504 = !DISubroutineType(types: !2505)
!2505 = !{!2506, !2498}
!2506 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2399, size: 64)
!2507 = !DISubprogram(name: "getExpansion", linkageName: "_ZNK5clang6SrcMgr9SLocEntry12getExpansionEv", scope: !2376, file: !346, line: 406, type: !2508, scopeLine: 406, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2508 = !DISubroutineType(types: !2509)
!2509 = !{!2510, !2498}
!2510 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2423, size: 64)
!2511 = !DISubprogram(name: "get", linkageName: "_ZN5clang6SrcMgr9SLocEntry3getEjRKNS0_8FileInfoE", scope: !2376, file: !346, line: 411, type: !2512, scopeLine: 411, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2512 = !DISubroutineType(types: !2513)
!2513 = !{!2376, !6, !2506}
!2514 = !DISubprogram(name: "get", linkageName: "_ZN5clang6SrcMgr9SLocEntry3getEjRKNS0_13ExpansionInfoE", scope: !2376, file: !346, line: 418, type: !2515, scopeLine: 418, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2515 = !DISubroutineType(types: !2516)
!2516 = !{!2376, !6, !2510}
!2517 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2373, file: !1967, line: 100, baseType: !2518)
!2518 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2376, size: 64)
!2519 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringSwitch<bool, bool>", scope: !342, file: !2520, line: 42, size: 192, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2521, templateParams: !2539, identifier: "_ZTSN4llvm12StringSwitchIbbEE")
!2520 = !DIFile(filename: "llvm34/include/llvm/ADT/StringSwitch.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "2b7706e5e11d0ed7a98ce7ff70ef5a8b")
!2521 = !{!2522, !2523, !2526, !2530, !2536}
!2522 = !DIDerivedType(tag: DW_TAG_member, name: "Str", scope: !2519, file: !2520, line: 44, baseType: !1578, size: 128)
!2523 = !DIDerivedType(tag: DW_TAG_member, name: "Result", scope: !2519, file: !2520, line: 48, baseType: !2524, size: 64, offset: 128)
!2524 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2525, size: 64)
!2525 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !308)
!2526 = !DISubprogram(name: "StringSwitch", scope: !2519, file: !2520, line: 51, type: !2527, scopeLine: 51, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2527 = !DISubroutineType(types: !2528)
!2528 = !{null, !2529, !1578}
!2529 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2519, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2530 = !DISubprogram(name: "Default", linkageName: "_ZNK4llvm12StringSwitchIbbE7DefaultERKb", scope: !2519, file: !2520, line: 111, type: !2531, scopeLine: 111, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2531 = !DISubroutineType(types: !2532)
!2532 = !{!308, !2533, !2535}
!2533 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2534, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2534 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2519)
!2535 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2525, size: 64)
!2536 = !DISubprogram(name: "operator bool", linkageName: "_ZNK4llvm12StringSwitchIbbEcvbEv", scope: !2519, file: !2520, line: 118, type: !2537, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2537 = !DISubroutineType(types: !2538)
!2538 = !{!308, !2533}
!2539 = !{!2540, !2541}
!2540 = !DITemplateTypeParameter(name: "T", type: !308)
!2541 = !DITemplateTypeParameter(name: "R", type: !308)
!2542 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2543, size: 64)
!2543 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2544)
!2544 = !DIDerivedType(tag: DW_TAG_typedef, name: "actualtype", scope: !2545, file: !1350, line: 106, baseType: !2552)
!2545 = distinct !DISubprogram(name: "getNameStart", linkageName: "_ZNK5clang14IdentifierInfo12getNameStartEv", scope: !1349, file: !1350, line: 99, type: !2546, scopeLine: 99, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !2549, retainedNodes: !2550)
!2546 = !DISubroutineType(types: !2547)
!2547 = !{!407, !2548}
!2548 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1818, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2549 = !DISubprogram(name: "getNameStart", linkageName: "_ZNK5clang14IdentifierInfo12getNameStartEv", scope: !1349, file: !1350, line: 99, type: !2546, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2550 = !{!2551}
!2551 = !DILocalVariable(name: "this", arg: 1, scope: !2545, type: !1817, flags: DIFlagArtificial | DIFlagObjectPointer)
!2552 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<clang::IdentifierInfo, const char *>", scope: !353, file: !1693, line: 208, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2553, templateParams: !2605, identifier: "_ZTSSt4pairIN5clang14IdentifierInfoEPKcE")
!2553 = !{!2554, !2574, !2575, !2576, !2582, !2586, !2595, !2602}
!2554 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2552, baseType: !2555, flags: DIFlagPrivate, extraData: i32 0)
!2555 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<clang::IdentifierInfo, const char *>", scope: !353, file: !1693, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !2556, templateParams: !2571, identifier: "_ZTSSt11__pair_baseIN5clang14IdentifierInfoEPKcE")
!2556 = !{!2557, !2561, !2562, !2567}
!2557 = !DISubprogram(name: "__pair_base", scope: !2555, file: !1693, line: 194, type: !2558, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2558 = !DISubroutineType(types: !2559)
!2559 = !{null, !2560}
!2560 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2555, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2561 = !DISubprogram(name: "~__pair_base", scope: !2555, file: !1693, line: 195, type: !2558, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2562 = !DISubprogram(name: "__pair_base", scope: !2555, file: !1693, line: 196, type: !2563, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2563 = !DISubroutineType(types: !2564)
!2564 = !{null, !2560, !2565}
!2565 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2566, size: 64)
!2566 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2555)
!2567 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN5clang14IdentifierInfoEPKcEaSERKS4_", scope: !2555, file: !1693, line: 197, type: !2568, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2568 = !DISubroutineType(types: !2569)
!2569 = !{!2570, !2560, !2565}
!2570 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2555, size: 64)
!2571 = !{!2572, !2573}
!2572 = !DITemplateTypeParameter(name: "_U1", type: !1349)
!2573 = !DITemplateTypeParameter(name: "_U2", type: !407)
!2574 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !2552, file: !1693, line: 214, baseType: !1349, size: 192)
!2575 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !2552, file: !1693, line: 215, baseType: !407, size: 64, offset: 192)
!2576 = !DISubprogram(name: "pair", scope: !2552, file: !1693, line: 303, type: !2577, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2577 = !DISubroutineType(types: !2578)
!2578 = !{null, !2579, !2580}
!2579 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2552, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2580 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2581, size: 64)
!2581 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2552)
!2582 = !DISubprogram(name: "pair", scope: !2552, file: !1693, line: 304, type: !2583, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2583 = !DISubroutineType(types: !2584)
!2584 = !{null, !2579, !2585}
!2585 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2552, size: 64)
!2586 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN5clang14IdentifierInfoEPKcEaSERKSt20__nonesuch_no_braces", scope: !2552, file: !1693, line: 378, type: !2587, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2587 = !DISubroutineType(types: !2588)
!2588 = !{!2589, !2579, !2590}
!2589 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2552, size: 64)
!2590 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2591, file: !1732, line: 1933, baseType: !1738)
!2591 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<false, const std::pair<clang::IdentifierInfo, const char *> &, const std::__nonesuch_no_braces &>", scope: !353, file: !1732, line: 1932, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !2592, identifier: "_ZTSSt11conditionalILb0ERKSt4pairIN5clang14IdentifierInfoEPKcERKSt20__nonesuch_no_bracesE")
!2592 = !{!2593, !2594, !1737}
!2593 = !DITemplateValueParameter(name: "_Cond", type: !308, value: i8 0)
!2594 = !DITemplateTypeParameter(name: "_Iftrue", type: !2580)
!2595 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN5clang14IdentifierInfoEPKcEaSEOSt20__nonesuch_no_braces", scope: !2552, file: !1693, line: 389, type: !2596, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2596 = !DISubroutineType(types: !2597)
!2597 = !{!2589, !2579, !2598}
!2598 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2599, file: !1732, line: 1933, baseType: !1749)
!2599 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<false, std::pair<clang::IdentifierInfo, const char *> &&, std::__nonesuch_no_braces &&>", scope: !353, file: !1732, line: 1932, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !2600, identifier: "_ZTSSt11conditionalILb0EOSt4pairIN5clang14IdentifierInfoEPKcEOSt20__nonesuch_no_bracesE")
!2600 = !{!2593, !2601, !1748}
!2601 = !DITemplateTypeParameter(name: "_Iftrue", type: !2585)
!2602 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN5clang14IdentifierInfoEPKcE4swapERS4_", scope: !2552, file: !1693, line: 424, type: !2603, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2603 = !DISubroutineType(types: !2604)
!2604 = !{null, !2579, !2589}
!2605 = !{!2606, !2607}
!2606 = !DITemplateTypeParameter(name: "_T1", type: !1349)
!2607 = !DITemplateTypeParameter(name: "_T2", type: !407)
!2608 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2609, size: 64)
!2609 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2610)
!2610 = !DIDerivedType(tag: DW_TAG_typedef, name: "actualtype", scope: !2611, file: !1350, line: 119, baseType: !2552)
!2611 = distinct !DISubprogram(name: "getLength", linkageName: "_ZNK5clang14IdentifierInfo9getLengthEv", scope: !1349, file: !1350, line: 112, type: !2612, scopeLine: 112, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !2614, retainedNodes: !2615)
!2612 = !DISubroutineType(types: !2613)
!2613 = !{!6, !2548}
!2614 = !DISubprogram(name: "getLength", linkageName: "_ZNK5clang14IdentifierInfo9getLengthEv", scope: !1349, file: !1350, line: 112, type: !2612, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2615 = !{!2616, !2617}
!2616 = !DILocalVariable(name: "this", arg: 1, scope: !2611, type: !1817, flags: DIFlagArtificial | DIFlagObjectPointer)
!2617 = !DILocalVariable(name: "p", scope: !2611, file: !1350, line: 120, type: !407)
!2618 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2619, file: !1967, line: 100, baseType: !2647)
!2619 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<unsigned int, void>", scope: !342, file: !1967, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2620, templateParams: !2706, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIjvEE")
!2620 = !{!2621, !2622, !2629, !2633, !2636, !2641, !2644, !2648, !2651, !2657, !2658, !2659, !2660, !2661, !2666, !2671, !2672, !2673, !2676, !2677, !2680, !2684, !2688, !2693, !2698, !2701, !2704, !2705}
!2621 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2619, baseType: !1971, flags: DIFlagPublic, extraData: i32 0)
!2622 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !2619, file: !1967, line: 74, baseType: !2623, size: 32, offset: 192)
!2623 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !2619, file: !1967, line: 73, baseType: !2624)
!2624 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<unsigned int, char, char, char, char, char, char>", scope: !342, file: !1541, line: 199, size: 32, flags: DIFlagTypePassByValue, elements: !2625, templateParams: !2627, identifier: "_ZTSN4llvm21AlignedCharArrayUnionIjccccccEE")
!2625 = !{!2626}
!2626 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2624, baseType: !2103, extraData: i32 0)
!2627 = !{!2628, !2008, !2009, !2010, !2011, !2012, !2013}
!2628 = !DITemplateTypeParameter(name: "T1", type: !6)
!2629 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !2619, file: !1967, line: 78, type: !2630, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2630 = !DISubroutineType(types: !2631)
!2631 = !{null, !2632, !1583}
!2632 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2619, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2633 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE8grow_podEmm", scope: !2619, file: !1967, line: 80, type: !2634, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2634 = !DISubroutineType(types: !2635)
!2635 = !{null, !2632, !1583, !1583}
!2636 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE7isSmallEv", scope: !2619, file: !1967, line: 86, type: !2637, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2637 = !DISubroutineType(types: !2638)
!2638 = !{!308, !2639}
!2639 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2640, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2640 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2619)
!2641 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE12resetToSmallEv", scope: !2619, file: !1967, line: 91, type: !2642, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2642 = !DISubroutineType(types: !2643)
!2643 = !{null, !2632}
!2644 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE6setEndEPj", scope: !2619, file: !1967, line: 95, type: !2645, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2645 = !DISubroutineType(types: !2646)
!2646 = !{null, !2632, !2647}
!2647 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6, size: 64)
!2648 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE5beginEv", scope: !2619, file: !1967, line: 112, type: !2649, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2649 = !DISubroutineType(types: !2650)
!2650 = !{!2618, !2632}
!2651 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE5beginEv", scope: !2619, file: !1967, line: 113, type: !2652, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2652 = !DISubroutineType(types: !2653)
!2653 = !{!2654, !2639}
!2654 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !2619, file: !1967, line: 101, baseType: !2655)
!2655 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2656, size: 64)
!2656 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6)
!2657 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE3endEv", scope: !2619, file: !1967, line: 114, type: !2649, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2658 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE3endEv", scope: !2619, file: !1967, line: 115, type: !2652, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2659 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE12capacity_ptrEv", scope: !2619, file: !1967, line: 117, type: !2649, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2660 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE12capacity_ptrEv", scope: !2619, file: !1967, line: 118, type: !2652, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2661 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE6rbeginEv", scope: !2619, file: !1967, line: 122, type: !2662, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2662 = !DISubroutineType(types: !2663)
!2663 = !{!2664, !2632}
!2664 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !2619, file: !1967, line: 104, baseType: !2665)
!2665 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<unsigned int *>", scope: !353, file: !572, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPjE")
!2666 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE6rbeginEv", scope: !2619, file: !1967, line: 123, type: !2667, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2667 = !DISubroutineType(types: !2668)
!2668 = !{!2669, !2639}
!2669 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !2619, file: !1967, line: 103, baseType: !2670)
!2670 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const unsigned int *>", scope: !353, file: !572, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKjE")
!2671 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE4rendEv", scope: !2619, file: !1967, line: 124, type: !2662, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2672 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE4rendEv", scope: !2619, file: !1967, line: 125, type: !2667, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2673 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE4sizeEv", scope: !2619, file: !1967, line: 127, type: !2674, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2674 = !DISubroutineType(types: !2675)
!2675 = !{!2059, !2639}
!2676 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE8max_sizeEv", scope: !2619, file: !1967, line: 128, type: !2674, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2677 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE8capacityEv", scope: !2619, file: !1967, line: 132, type: !2678, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2678 = !DISubroutineType(types: !2679)
!2679 = !{!1583, !2639}
!2680 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE4dataEv", scope: !2619, file: !1967, line: 135, type: !2681, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2681 = !DISubroutineType(types: !2682)
!2682 = !{!2683, !2632}
!2683 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2619, file: !1967, line: 108, baseType: !2647)
!2684 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE4dataEv", scope: !2619, file: !1967, line: 137, type: !2685, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2685 = !DISubroutineType(types: !2686)
!2686 = !{!2687, !2639}
!2687 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !2619, file: !1967, line: 109, baseType: !2655)
!2688 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvEixEj", scope: !2619, file: !1967, line: 139, type: !2689, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2689 = !DISubroutineType(types: !2690)
!2690 = !{!2691, !2632, !6}
!2691 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2619, file: !1967, line: 106, baseType: !2692)
!2692 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !6, size: 64)
!2693 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvEixEj", scope: !2619, file: !1967, line: 143, type: !2694, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2694 = !DISubroutineType(types: !2695)
!2695 = !{!2696, !2639, !6}
!2696 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !2619, file: !1967, line: 107, baseType: !2697)
!2697 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2656, size: 64)
!2698 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE5frontEv", scope: !2619, file: !1967, line: 148, type: !2699, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2699 = !DISubroutineType(types: !2700)
!2700 = !{!2691, !2632}
!2701 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE5frontEv", scope: !2619, file: !1967, line: 152, type: !2702, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2702 = !DISubroutineType(types: !2703)
!2703 = !{!2696, !2639}
!2704 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIjvE4backEv", scope: !2619, file: !1967, line: 157, type: !2699, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2705 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIjvE4backEv", scope: !2619, file: !1967, line: 161, type: !2702, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2706 = !{!2707, !2093}
!2707 = !DITemplateTypeParameter(name: "T", type: !6)
!2708 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2709, size: 64)
!2709 = !DIDerivedType(tag: DW_TAG_typedef, name: "MapEntryTy", scope: !2710, file: !1546, line: 239, baseType: !1545)
!2710 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringMap<clang::IdentifierInfo *, llvm::BumpPtrAllocator>", scope: !342, file: !1546, line: 236, size: 768, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm9StringMapIPN5clang14IdentifierInfoENS_16BumpPtrAllocatorEEE")
!2711 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1549, size: 64)
!2712 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2713, size: 64)
!2713 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2714)
!2714 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMap<const clang::IdentifierInfo *, clang::MacroDirective *, llvm::DenseMapInfo<const clang::IdentifierInfo *> >", scope: !342, file: !2715, line: 534, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm8DenseMapIPKN5clang14IdentifierInfoEPNS1_14MacroDirectiveENS_12DenseMapInfoIS4_EEEE")
!2715 = !DIFile(filename: "llvm34/include/llvm/ADT/DenseMap.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e4a1c2d5b55fe605534e57bb36c4fe71")
!2716 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2717, size: 64)
!2717 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2718)
!2718 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapBase<llvm::DenseMap<const clang::IdentifierInfo *, clang::MacroDirective *, llvm::DenseMapInfo<const clang::IdentifierInfo *> >, const clang::IdentifierInfo *, clang::MacroDirective *, llvm::DenseMapInfo<const clang::IdentifierInfo *> >", scope: !342, file: !2715, line: 41, size: 8, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang14IdentifierInfoEPNS2_14MacroDirectiveENS_12DenseMapInfoIS5_EEEES5_S7_S9_EE")
!2719 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2720, size: 64)
!2720 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !2718, file: !2715, line: 43, baseType: !2721)
!2721 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<const clang::IdentifierInfo *, clang::MacroDirective *>", scope: !353, file: !1693, line: 208, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2722, templateParams: !2773, identifier: "_ZTSSt4pairIPKN5clang14IdentifierInfoEPNS0_14MacroDirectiveEE")
!2722 = !{!2723, !2743, !2744, !2745, !2751, !2755, !2763, !2770}
!2723 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2721, baseType: !2724, flags: DIFlagPrivate, extraData: i32 0)
!2724 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<const clang::IdentifierInfo *, clang::MacroDirective *>", scope: !353, file: !1693, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !2725, templateParams: !2740, identifier: "_ZTSSt11__pair_baseIPKN5clang14IdentifierInfoEPNS0_14MacroDirectiveEE")
!2725 = !{!2726, !2730, !2731, !2736}
!2726 = !DISubprogram(name: "__pair_base", scope: !2724, file: !1693, line: 194, type: !2727, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2727 = !DISubroutineType(types: !2728)
!2728 = !{null, !2729}
!2729 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2724, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2730 = !DISubprogram(name: "~__pair_base", scope: !2724, file: !1693, line: 195, type: !2727, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2731 = !DISubprogram(name: "__pair_base", scope: !2724, file: !1693, line: 196, type: !2732, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2732 = !DISubroutineType(types: !2733)
!2733 = !{null, !2729, !2734}
!2734 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2735, size: 64)
!2735 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2724)
!2736 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIPKN5clang14IdentifierInfoEPNS0_14MacroDirectiveEEaSERKS6_", scope: !2724, file: !1693, line: 197, type: !2737, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2737 = !DISubroutineType(types: !2738)
!2738 = !{!2739, !2729, !2734}
!2739 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2724, size: 64)
!2740 = !{!2741, !2742}
!2741 = !DITemplateTypeParameter(name: "_U1", type: !1817)
!2742 = !DITemplateTypeParameter(name: "_U2", type: !1834)
!2743 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !2721, file: !1693, line: 214, baseType: !1817, size: 64)
!2744 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !2721, file: !1693, line: 215, baseType: !1834, size: 64, offset: 64)
!2745 = !DISubprogram(name: "pair", scope: !2721, file: !1693, line: 303, type: !2746, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2746 = !DISubroutineType(types: !2747)
!2747 = !{null, !2748, !2749}
!2748 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2721, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2749 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2750, size: 64)
!2750 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2721)
!2751 = !DISubprogram(name: "pair", scope: !2721, file: !1693, line: 304, type: !2752, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2752 = !DISubroutineType(types: !2753)
!2753 = !{null, !2748, !2754}
!2754 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2721, size: 64)
!2755 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPKN5clang14IdentifierInfoEPNS0_14MacroDirectiveEEaSERKS6_", scope: !2721, file: !1693, line: 378, type: !2756, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2756 = !DISubroutineType(types: !2757)
!2757 = !{!2758, !2748, !2759}
!2758 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2721, size: 64)
!2759 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2760, file: !1732, line: 1928, baseType: !2749)
!2760 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<const clang::IdentifierInfo *, clang::MacroDirective *> &, const std::__nonesuch_no_braces &>", scope: !353, file: !1732, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !2761, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIPKN5clang14IdentifierInfoEPNS1_14MacroDirectiveEERKSt20__nonesuch_no_bracesE")
!2761 = !{!1735, !2762, !1737}
!2762 = !DITemplateTypeParameter(name: "_Iftrue", type: !2749)
!2763 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPKN5clang14IdentifierInfoEPNS0_14MacroDirectiveEEaSEOS6_", scope: !2721, file: !1693, line: 389, type: !2764, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2764 = !DISubroutineType(types: !2765)
!2765 = !{!2758, !2748, !2766}
!2766 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2767, file: !1732, line: 1928, baseType: !2754)
!2767 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<const clang::IdentifierInfo *, clang::MacroDirective *> &&, std::__nonesuch_no_braces &&>", scope: !353, file: !1732, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !2768, identifier: "_ZTSSt11conditionalILb1EOSt4pairIPKN5clang14IdentifierInfoEPNS1_14MacroDirectiveEEOSt20__nonesuch_no_bracesE")
!2768 = !{!1735, !2769, !1748}
!2769 = !DITemplateTypeParameter(name: "_Iftrue", type: !2754)
!2770 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIPKN5clang14IdentifierInfoEPNS0_14MacroDirectiveEE4swapERS6_", scope: !2721, file: !1693, line: 424, type: !2771, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2771 = !DISubroutineType(types: !2772)
!2772 = !{null, !2748, !2758}
!2773 = !{!2774, !2775}
!2774 = !DITemplateTypeParameter(name: "_T1", type: !1817)
!2775 = !DITemplateTypeParameter(name: "_T2", type: !1834)
!2776 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2714, size: 64)
!2777 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2778, size: 64)
!2778 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !2714, file: !2715, line: 540, baseType: !2720)
!2779 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !2781, file: !2780, line: 185, baseType: !2786)
!2780 = !DIFile(filename: "llvm34/include/llvm/Support/Casting.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "d66d299dea704124ccd357043ea0e9d5")
!2781 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty<clang::DefMacroDirective, clang::MacroDirective *>", scope: !342, file: !2780, line: 183, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !2782, identifier: "_ZTSN4llvm10cast_rettyIN5clang17DefMacroDirectiveEPNS1_14MacroDirectiveEEE")
!2782 = !{!2783, !2785}
!2783 = !DITemplateTypeParameter(name: "To", type: !2784)
!2784 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DefMacroDirective", scope: !14, file: !1827, line: 461, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang17DefMacroDirectiveE")
!2785 = !DITemplateTypeParameter(name: "From", type: !1834)
!2786 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !2787, file: !2780, line: 179, baseType: !2790)
!2787 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_wrap<clang::DefMacroDirective, clang::MacroDirective *, clang::MacroDirective *>", scope: !342, file: !2780, line: 177, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !2788, identifier: "_ZTSN4llvm15cast_retty_wrapIN5clang17DefMacroDirectiveEPNS1_14MacroDirectiveES4_EE")
!2788 = !{!2783, !2785, !2789}
!2789 = !DITemplateTypeParameter(name: "SimpleFrom", type: !1834)
!2790 = !DIDerivedType(tag: DW_TAG_typedef, name: "ret_type", scope: !2791, file: !2780, line: 156, baseType: !2792)
!2791 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "cast_retty_impl<clang::DefMacroDirective, clang::MacroDirective *>", scope: !342, file: !2780, line: 155, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !2782, identifier: "_ZTSN4llvm15cast_retty_implIN5clang17DefMacroDirectiveEPNS1_14MacroDirectiveEEE")
!2792 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2784, size: 64)
!2793 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !2794, line: 374, baseType: !415)
!2794 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h", directory: "", checksumkind: CSK_MD5, checksum: "ba305a1e10d49c66b3a70acbb63616a6")
!2795 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2796, file: !1967, line: 100, baseType: !2797)
!2796 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<clang::Preprocessor::MacroExpandsInfo, void>", scope: !342, file: !1967, line: 66, size: 512, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIN5clang12Preprocessor16MacroExpandsInfoEvEE")
!2797 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2798, size: 64)
!2798 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "MacroExpandsInfo", scope: !2800, file: !2799, line: 302, size: 320, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2801, identifier: "_ZTSN5clang12Preprocessor16MacroExpandsInfoE")
!2799 = !DIFile(filename: "llvm34/projects/clang/include/clang/Lex/Preprocessor.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "256d80ca1ad37c23bef05d6cab9ffdd6")
!2800 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Preprocessor", scope: !14, file: !2799, line: 86, size: 15808, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang12PreprocessorE")
!2801 = !{!2802, !2803, !2804, !2805}
!2802 = !DIDerivedType(tag: DW_TAG_member, name: "Tok", scope: !2798, file: !2799, line: 303, baseType: !294, size: 192)
!2803 = !DIDerivedType(tag: DW_TAG_member, name: "MD", scope: !2798, file: !2799, line: 304, baseType: !1834, size: 64, offset: 192)
!2804 = !DIDerivedType(tag: DW_TAG_member, name: "Range", scope: !2798, file: !2799, line: 305, baseType: !1305, size: 64, offset: 256)
!2805 = !DISubprogram(name: "MacroExpandsInfo", scope: !2798, file: !2799, line: 306, type: !2806, scopeLine: 306, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2806 = !DISubroutineType(types: !2807)
!2807 = !{null, !2808, !294, !1834, !1305}
!2808 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2798, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2809 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !2796, file: !1967, line: 101, baseType: !2810)
!2810 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2811, size: 64)
!2811 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2798)
!2812 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2813, file: !1967, line: 100, baseType: !2849)
!2813 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<clang::SourceRange, void>", scope: !342, file: !1967, line: 66, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2814, templateParams: !2906, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvEE")
!2814 = !{!2815, !2816, !2831, !2835, !2838, !2843, !2846, !2850, !2853, !2858, !2859, !2860, !2861, !2862, !2867, !2872, !2873, !2874, !2877, !2878, !2881, !2885, !2889, !2894, !2898, !2901, !2904, !2905}
!2815 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2813, baseType: !1971, flags: DIFlagPublic, extraData: i32 0)
!2816 = !DIDerivedType(tag: DW_TAG_member, name: "FirstEl", scope: !2813, file: !1967, line: 74, baseType: !2817, size: 64, offset: 192)
!2817 = !DIDerivedType(tag: DW_TAG_typedef, name: "U", scope: !2813, file: !1967, line: 73, baseType: !2818)
!2818 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<clang::SourceRange, char, char, char, char, char, char>", scope: !342, file: !1541, line: 199, size: 64, flags: DIFlagTypePassByValue, elements: !2819, templateParams: !2829, identifier: "_ZTSN4llvm21AlignedCharArrayUnionIN5clang11SourceRangeEccccccEE")
!2819 = !{!2820}
!2820 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2818, baseType: !2821, extraData: i32 0)
!2821 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<4UL, 8UL>", scope: !342, file: !1541, line: 75, size: 64, flags: DIFlagTypePassByValue, elements: !2822, templateParams: !2827, identifier: "_ZTSN4llvm16AlignedCharArrayILm4ELm8EEE")
!2822 = !{!2823}
!2823 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !2821, file: !1541, line: 76, baseType: !2824, size: 64, align: 32)
!2824 = !DICompositeType(tag: DW_TAG_array_type, baseType: !374, size: 64, elements: !2825)
!2825 = !{!2826}
!2826 = !DISubrange(count: 8)
!2827 = !{!2110, !2828}
!2828 = !DITemplateValueParameter(name: "Size", type: !417, value: i64 8)
!2829 = !{!2830, !2008, !2009, !2010, !2011, !2012, !2013}
!2830 = !DITemplateTypeParameter(name: "T1", type: !1305)
!2831 = !DISubprogram(name: "SmallVectorTemplateCommon", scope: !2813, file: !1967, line: 78, type: !2832, scopeLine: 78, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2832 = !DISubroutineType(types: !2833)
!2833 = !{null, !2834, !1583}
!2834 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2813, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2835 = !DISubprogram(name: "grow_pod", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE8grow_podEmm", scope: !2813, file: !1967, line: 80, type: !2836, scopeLine: 80, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2836 = !DISubroutineType(types: !2837)
!2837 = !{null, !2834, !1583, !1583}
!2838 = !DISubprogram(name: "isSmall", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE7isSmallEv", scope: !2813, file: !1967, line: 86, type: !2839, scopeLine: 86, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2839 = !DISubroutineType(types: !2840)
!2840 = !{!308, !2841}
!2841 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2842, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2842 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2813)
!2843 = !DISubprogram(name: "resetToSmall", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE12resetToSmallEv", scope: !2813, file: !1967, line: 91, type: !2844, scopeLine: 91, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2844 = !DISubroutineType(types: !2845)
!2845 = !{null, !2834}
!2846 = !DISubprogram(name: "setEnd", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE6setEndEPS2_", scope: !2813, file: !1967, line: 95, type: !2847, scopeLine: 95, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2847 = !DISubroutineType(types: !2848)
!2848 = !{null, !2834, !2849}
!2849 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1305, size: 64)
!2850 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE5beginEv", scope: !2813, file: !1967, line: 112, type: !2851, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2851 = !DISubroutineType(types: !2852)
!2852 = !{!2812, !2834}
!2853 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE5beginEv", scope: !2813, file: !1967, line: 113, type: !2854, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2854 = !DISubroutineType(types: !2855)
!2855 = !{!2856, !2841}
!2856 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !2813, file: !1967, line: 101, baseType: !2857)
!2857 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1323, size: 64)
!2858 = !DISubprogram(name: "end", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE3endEv", scope: !2813, file: !1967, line: 114, type: !2851, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2859 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE3endEv", scope: !2813, file: !1967, line: 115, type: !2854, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2860 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE12capacity_ptrEv", scope: !2813, file: !1967, line: 117, type: !2851, scopeLine: 117, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2861 = !DISubprogram(name: "capacity_ptr", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE12capacity_ptrEv", scope: !2813, file: !1967, line: 118, type: !2854, scopeLine: 118, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2862 = !DISubprogram(name: "rbegin", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE6rbeginEv", scope: !2813, file: !1967, line: 122, type: !2863, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2863 = !DISubroutineType(types: !2864)
!2864 = !{!2865, !2834}
!2865 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !2813, file: !1967, line: 104, baseType: !2866)
!2866 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<clang::SourceRange *>", scope: !353, file: !572, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPN5clang11SourceRangeEE")
!2867 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE6rbeginEv", scope: !2813, file: !1967, line: 123, type: !2868, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2868 = !DISubroutineType(types: !2869)
!2869 = !{!2870, !2841}
!2870 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !2813, file: !1967, line: 103, baseType: !2871)
!2871 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const clang::SourceRange *>", scope: !353, file: !572, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKN5clang11SourceRangeEE")
!2872 = !DISubprogram(name: "rend", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE4rendEv", scope: !2813, file: !1967, line: 124, type: !2863, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2873 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE4rendEv", scope: !2813, file: !1967, line: 125, type: !2868, scopeLine: 125, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2874 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE4sizeEv", scope: !2813, file: !1967, line: 127, type: !2875, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2875 = !DISubroutineType(types: !2876)
!2876 = !{!2059, !2841}
!2877 = !DISubprogram(name: "max_size", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE8max_sizeEv", scope: !2813, file: !1967, line: 128, type: !2875, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2878 = !DISubprogram(name: "capacity", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE8capacityEv", scope: !2813, file: !1967, line: 132, type: !2879, scopeLine: 132, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2879 = !DISubroutineType(types: !2880)
!2880 = !{!1583, !2841}
!2881 = !DISubprogram(name: "data", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE4dataEv", scope: !2813, file: !1967, line: 135, type: !2882, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2882 = !DISubroutineType(types: !2883)
!2883 = !{!2884, !2834}
!2884 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2813, file: !1967, line: 108, baseType: !2849)
!2885 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE4dataEv", scope: !2813, file: !1967, line: 137, type: !2886, scopeLine: 137, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2886 = !DISubroutineType(types: !2887)
!2887 = !{!2888, !2841}
!2888 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !2813, file: !1967, line: 109, baseType: !2857)
!2889 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvEixEj", scope: !2813, file: !1967, line: 139, type: !2890, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2890 = !DISubroutineType(types: !2891)
!2891 = !{!2892, !2834, !6}
!2892 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2813, file: !1967, line: 106, baseType: !2893)
!2893 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1305, size: 64)
!2894 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvEixEj", scope: !2813, file: !1967, line: 143, type: !2895, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2895 = !DISubroutineType(types: !2896)
!2896 = !{!2897, !2841, !6}
!2897 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !2813, file: !1967, line: 107, baseType: !1334)
!2898 = !DISubprogram(name: "front", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE5frontEv", scope: !2813, file: !1967, line: 148, type: !2899, scopeLine: 148, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2899 = !DISubroutineType(types: !2900)
!2900 = !{!2892, !2834}
!2901 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE5frontEv", scope: !2813, file: !1967, line: 152, type: !2902, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2902 = !DISubroutineType(types: !2903)
!2903 = !{!2897, !2841}
!2904 = !DISubprogram(name: "back", linkageName: "_ZN4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE4backEv", scope: !2813, file: !1967, line: 157, type: !2899, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2905 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm25SmallVectorTemplateCommonIN5clang11SourceRangeEvE4backEv", scope: !2813, file: !1967, line: 161, type: !2902, scopeLine: 161, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2906 = !{!2907, !2093}
!2907 = !DITemplateTypeParameter(name: "T", type: !1305)
!2908 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2909, size: 64)
!2909 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2910)
!2910 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Tp_alloc_type", scope: !2911, file: !2794, line: 84, baseType: !2912)
!2911 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_base<std::pair<clang::TokenLexer *, unsigned long>, std::allocator<std::pair<clang::TokenLexer *, unsigned long> > >", scope: !353, file: !2794, line: 81, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt12_Vector_baseISt4pairIPN5clang10TokenLexerEmESaIS4_EE")
!2912 = !DIDerivedType(tag: DW_TAG_typedef, name: "other", scope: !2913, file: !362, line: 117, baseType: !3020)
!2913 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "rebind<std::pair<clang::TokenLexer *, unsigned long> >", scope: !2914, file: !362, line: 116, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !3018, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaISt4pairIPN5clang10TokenLexerEmEES5_E6rebindIS5_EE")
!2914 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__alloc_traits<std::allocator<std::pair<clang::TokenLexer *, unsigned long> >, std::pair<clang::TokenLexer *, unsigned long> >", scope: !5, file: !362, line: 50, size: 8, flags: DIFlagTypePassByValue, elements: !2915, templateParams: !3016, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaISt4pairIPN5clang10TokenLexerEmEES5_EE")
!2915 = !{!2916, !3002, !3007, !3011, !3012, !3013, !3014, !3015}
!2916 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2914, baseType: !2917, extraData: i32 0)
!2917 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "allocator_traits<std::allocator<std::pair<clang::TokenLexer *, unsigned long> > >", scope: !353, file: !367, line: 384, size: 8, flags: DIFlagTypePassByValue, elements: !2918, templateParams: !3000, identifier: "_ZTSSt16allocator_traitsISaISt4pairIPN5clang10TokenLexerEmEEE")
!2918 = !{!2919, !2985, !2988, !2991, !2997}
!2919 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaISt4pairIPN5clang10TokenLexerEmEEE8allocateERS5_m", scope: !2917, file: !367, line: 435, type: !2920, scopeLine: 435, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2920 = !DISubroutineType(types: !2921)
!2921 = !{!2922, !2982, !436}
!2922 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2917, file: !367, line: 392, baseType: !2923)
!2923 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2924, size: 64)
!2924 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<clang::TokenLexer *, unsigned long>", scope: !353, file: !1693, line: 208, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2925, templateParams: !2979, identifier: "_ZTSSt4pairIPN5clang10TokenLexerEmE")
!2925 = !{!2926, !2949, !2950, !2951, !2957, !2961, !2969, !2976}
!2926 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2924, baseType: !2927, flags: DIFlagPrivate, extraData: i32 0)
!2927 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<clang::TokenLexer *, unsigned long>", scope: !353, file: !1693, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !2928, templateParams: !2943, identifier: "_ZTSSt11__pair_baseIPN5clang10TokenLexerEmE")
!2928 = !{!2929, !2933, !2934, !2939}
!2929 = !DISubprogram(name: "__pair_base", scope: !2927, file: !1693, line: 194, type: !2930, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2930 = !DISubroutineType(types: !2931)
!2931 = !{null, !2932}
!2932 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2927, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2933 = !DISubprogram(name: "~__pair_base", scope: !2927, file: !1693, line: 195, type: !2930, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2934 = !DISubprogram(name: "__pair_base", scope: !2927, file: !1693, line: 196, type: !2935, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2935 = !DISubroutineType(types: !2936)
!2936 = !{null, !2932, !2937}
!2937 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2938, size: 64)
!2938 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2927)
!2939 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIPN5clang10TokenLexerEmEaSERKS3_", scope: !2927, file: !1693, line: 197, type: !2940, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2940 = !DISubroutineType(types: !2941)
!2941 = !{!2942, !2932, !2937}
!2942 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2927, size: 64)
!2943 = !{!2944, !2948}
!2944 = !DITemplateTypeParameter(name: "_U1", type: !2945)
!2945 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2946, size: 64)
!2946 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "TokenLexer", scope: !14, file: !2947, line: 29, size: 576, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang10TokenLexerE")
!2947 = !DIFile(filename: "llvm34/projects/clang/include/clang/Lex/TokenLexer.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "5fa77ae7c2aab4c0366011507eccee8c")
!2948 = !DITemplateTypeParameter(name: "_U2", type: !417)
!2949 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !2924, file: !1693, line: 214, baseType: !2945, size: 64)
!2950 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !2924, file: !1693, line: 215, baseType: !417, size: 64, offset: 64)
!2951 = !DISubprogram(name: "pair", scope: !2924, file: !1693, line: 303, type: !2952, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2952 = !DISubroutineType(types: !2953)
!2953 = !{null, !2954, !2955}
!2954 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2924, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2955 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2956, size: 64)
!2956 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2924)
!2957 = !DISubprogram(name: "pair", scope: !2924, file: !1693, line: 304, type: !2958, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2958 = !DISubroutineType(types: !2959)
!2959 = !{null, !2954, !2960}
!2960 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2924, size: 64)
!2961 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPN5clang10TokenLexerEmEaSERKS3_", scope: !2924, file: !1693, line: 378, type: !2962, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2962 = !DISubroutineType(types: !2963)
!2963 = !{!2964, !2954, !2965}
!2964 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2924, size: 64)
!2965 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2966, file: !1732, line: 1928, baseType: !2955)
!2966 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<clang::TokenLexer *, unsigned long> &, const std::__nonesuch_no_braces &>", scope: !353, file: !1732, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !2967, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIPN5clang10TokenLexerEmERKSt20__nonesuch_no_bracesE")
!2967 = !{!1735, !2968, !1737}
!2968 = !DITemplateTypeParameter(name: "_Iftrue", type: !2955)
!2969 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPN5clang10TokenLexerEmEaSEOS3_", scope: !2924, file: !1693, line: 389, type: !2970, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2970 = !DISubroutineType(types: !2971)
!2971 = !{!2964, !2954, !2972}
!2972 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2973, file: !1732, line: 1928, baseType: !2960)
!2973 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<clang::TokenLexer *, unsigned long> &&, std::__nonesuch_no_braces &&>", scope: !353, file: !1732, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !2974, identifier: "_ZTSSt11conditionalILb1EOSt4pairIPN5clang10TokenLexerEmEOSt20__nonesuch_no_bracesE")
!2974 = !{!1735, !2975, !1748}
!2975 = !DITemplateTypeParameter(name: "_Iftrue", type: !2960)
!2976 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIPN5clang10TokenLexerEmE4swapERS3_", scope: !2924, file: !1693, line: 424, type: !2977, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2977 = !DISubroutineType(types: !2978)
!2978 = !{null, !2954, !2964}
!2979 = !{!2980, !2981}
!2980 = !DITemplateTypeParameter(name: "_T1", type: !2945)
!2981 = !DITemplateTypeParameter(name: "_T2", type: !417)
!2982 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2983, size: 64)
!2983 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !2917, file: !367, line: 387, baseType: !2984)
!2984 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "allocator<std::pair<clang::TokenLexer *, unsigned long> >", scope: !353, file: !378, line: 108, size: 8, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSaISt4pairIPN5clang10TokenLexerEmEE")
!2985 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaISt4pairIPN5clang10TokenLexerEmEEE8allocateERS5_mPKv", scope: !2917, file: !367, line: 449, type: !2986, scopeLine: 449, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2986 = !DISubroutineType(types: !2987)
!2987 = !{!2922, !2982, !436, !440}
!2988 = !DISubprogram(name: "deallocate", linkageName: "_ZNSt16allocator_traitsISaISt4pairIPN5clang10TokenLexerEmEEE10deallocateERS5_PS4_m", scope: !2917, file: !367, line: 461, type: !2989, scopeLine: 461, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2989 = !DISubroutineType(types: !2990)
!2990 = !{null, !2982, !2922, !436}
!2991 = !DISubprogram(name: "max_size", linkageName: "_ZNSt16allocator_traitsISaISt4pairIPN5clang10TokenLexerEmEEE8max_sizeERKS5_", scope: !2917, file: !367, line: 495, type: !2992, scopeLine: 495, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2992 = !DISubroutineType(types: !2993)
!2993 = !{!2994, !2995}
!2994 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2917, file: !367, line: 407, baseType: !415)
!2995 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2996, size: 64)
!2996 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2983)
!2997 = !DISubprogram(name: "select_on_container_copy_construction", linkageName: "_ZNSt16allocator_traitsISaISt4pairIPN5clang10TokenLexerEmEEE37select_on_container_copy_constructionERKS5_", scope: !2917, file: !367, line: 504, type: !2998, scopeLine: 504, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2998 = !DISubroutineType(types: !2999)
!2999 = !{!2983, !2995}
!3000 = !{!3001}
!3001 = !DITemplateTypeParameter(name: "_Alloc", type: !2984)
!3002 = !DISubprogram(name: "_S_select_on_copy", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaISt4pairIPN5clang10TokenLexerEmEES5_E17_S_select_on_copyERKS6_", scope: !2914, file: !362, line: 94, type: !3003, scopeLine: 94, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3003 = !DISubroutineType(types: !3004)
!3004 = !{!2984, !3005}
!3005 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3006, size: 64)
!3006 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2984)
!3007 = !DISubprogram(name: "_S_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaISt4pairIPN5clang10TokenLexerEmEES5_E10_S_on_swapERS6_S8_", scope: !2914, file: !362, line: 97, type: !3008, scopeLine: 97, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3008 = !DISubroutineType(types: !3009)
!3009 = !{null, !3010, !3010}
!3010 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2984, size: 64)
!3011 = !DISubprogram(name: "_S_propagate_on_copy_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaISt4pairIPN5clang10TokenLexerEmEES5_E27_S_propagate_on_copy_assignEv", scope: !2914, file: !362, line: 100, type: !463, scopeLine: 100, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3012 = !DISubprogram(name: "_S_propagate_on_move_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaISt4pairIPN5clang10TokenLexerEmEES5_E27_S_propagate_on_move_assignEv", scope: !2914, file: !362, line: 103, type: !463, scopeLine: 103, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3013 = !DISubprogram(name: "_S_propagate_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaISt4pairIPN5clang10TokenLexerEmEES5_E20_S_propagate_on_swapEv", scope: !2914, file: !362, line: 106, type: !463, scopeLine: 106, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3014 = !DISubprogram(name: "_S_always_equal", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaISt4pairIPN5clang10TokenLexerEmEES5_E15_S_always_equalEv", scope: !2914, file: !362, line: 109, type: !463, scopeLine: 109, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3015 = !DISubprogram(name: "_S_nothrow_move", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaISt4pairIPN5clang10TokenLexerEmEES5_E15_S_nothrow_moveEv", scope: !2914, file: !362, line: 112, type: !463, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3016 = !{!3001, !3017}
!3017 = !DITemplateTypeParameter(type: !2924)
!3018 = !{!3019}
!3019 = !DITemplateTypeParameter(name: "_Tp", type: !2924)
!3020 = !DIDerivedType(tag: DW_TAG_typedef, name: "rebind_alloc<std::pair<clang::TokenLexer *, unsigned long> >", scope: !2917, file: !367, line: 422, baseType: !2984)
!3021 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3022, file: !2794, line: 369, baseType: !3023)
!3022 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<std::pair<clang::TokenLexer *, unsigned long>, std::allocator<std::pair<clang::TokenLexer *, unsigned long> > >", scope: !353, file: !2794, line: 339, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt6vectorISt4pairIPN5clang10TokenLexerEmESaIS4_EE")
!3023 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<std::pair<clang::TokenLexer *, unsigned long> *, std::vector<std::pair<clang::TokenLexer *, unsigned long>, std::allocator<std::pair<clang::TokenLexer *, unsigned long> > > >", scope: !5, file: !572, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3024, templateParams: !3077, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEE")
!3024 = !{!3025, !3026, !3030, !3035, !3046, !3051, !3055, !3058, !3059, !3060, !3066, !3069, !3072, !3073, !3074}
!3025 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !3023, file: !572, line: 767, baseType: !2923, size: 64, flags: DIFlagProtected)
!3026 = !DISubprogram(name: "__normal_iterator", scope: !3023, file: !572, line: 779, type: !3027, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3027 = !DISubroutineType(types: !3028)
!3028 = !{null, !3029}
!3029 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3023, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3030 = !DISubprogram(name: "__normal_iterator", scope: !3023, file: !572, line: 783, type: !3031, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3031 = !DISubroutineType(types: !3032)
!3032 = !{null, !3029, !3033}
!3033 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3034, size: 64)
!3034 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2923)
!3035 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEdeEv", scope: !3023, file: !572, line: 796, type: !3036, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3036 = !DISubroutineType(types: !3037)
!3037 = !{!3038, !3044}
!3038 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3023, file: !572, line: 776, baseType: !3039)
!3039 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3041, file: !3040, line: 184, baseType: !2964)
!3040 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_iterator_base_types.h", directory: "")
!3041 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<std::pair<clang::TokenLexer *, unsigned long> *>", scope: !353, file: !3040, line: 178, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !3042, identifier: "_ZTSSt15iterator_traitsIPSt4pairIPN5clang10TokenLexerEmEE")
!3042 = !{!3043}
!3043 = !DITemplateTypeParameter(name: "_Iterator", type: !2923)
!3044 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3045, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3045 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3023)
!3046 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEptEv", scope: !3023, file: !572, line: 800, type: !3047, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3047 = !DISubroutineType(types: !3048)
!3048 = !{!3049, !3044}
!3049 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3023, file: !572, line: 777, baseType: !3050)
!3050 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3041, file: !3040, line: 183, baseType: !2923)
!3051 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEppEv", scope: !3023, file: !572, line: 804, type: !3052, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3052 = !DISubroutineType(types: !3053)
!3053 = !{!3054, !3029}
!3054 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3023, size: 64)
!3055 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEppEi", scope: !3023, file: !572, line: 811, type: !3056, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3056 = !DISubroutineType(types: !3057)
!3057 = !{!3023, !3029, !324}
!3058 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEmmEv", scope: !3023, file: !572, line: 816, type: !3052, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3059 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEmmEi", scope: !3023, file: !572, line: 823, type: !3056, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3060 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEixEl", scope: !3023, file: !572, line: 828, type: !3061, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3061 = !DISubroutineType(types: !3062)
!3062 = !{!3038, !3044, !3063}
!3063 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !3023, file: !572, line: 775, baseType: !3064)
!3064 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !3041, file: !3040, line: 182, baseType: !3065)
!3065 = !DIDerivedType(tag: DW_TAG_typedef, name: "ptrdiff_t", scope: !353, file: !416, line: 239, baseType: !1837)
!3066 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEpLEl", scope: !3023, file: !572, line: 832, type: !3067, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3067 = !DISubroutineType(types: !3068)
!3068 = !{!3054, !3029, !3063}
!3069 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEplEl", scope: !3023, file: !572, line: 836, type: !3070, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3070 = !DISubroutineType(types: !3071)
!3071 = !{!3023, !3044, !3063}
!3072 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEmIEl", scope: !3023, file: !572, line: 840, type: !3067, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3073 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEmiEl", scope: !3023, file: !572, line: 844, type: !3070, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3074 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEE4baseEv", scope: !3023, file: !572, line: 848, type: !3075, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3075 = !DISubroutineType(types: !3076)
!3076 = !{!3033, !3044}
!3077 = !{!3043, !3078}
!3078 = !DITemplateTypeParameter(name: "_Container", type: !3022)
!3079 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "move_iterator<std::pair<clang::TokenLexer *, unsigned long> *>", scope: !353, file: !572, line: 1007, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3080, templateParams: !3042, identifier: "_ZTSSt13move_iteratorIPSt4pairIPN5clang10TokenLexerEmEE")
!3080 = !{!3081, !3082, !3086, !3090, !3095, !3103, !3107, !3111, !3114, !3115, !3116, !3120, !3123, !3124, !3125}
!3081 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !3079, file: !572, line: 1010, baseType: !2923, size: 64, flags: DIFlagProtected)
!3082 = !DISubprogram(name: "move_iterator", scope: !3079, file: !572, line: 1029, type: !3083, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3083 = !DISubroutineType(types: !3084)
!3084 = !{null, !3085}
!3085 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3079, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3086 = !DISubprogram(name: "move_iterator", scope: !3079, file: !572, line: 1033, type: !3087, scopeLine: 1033, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3087 = !DISubroutineType(types: !3088)
!3088 = !{null, !3085, !3089}
!3089 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator_type", scope: !3079, file: !572, line: 1016, baseType: !2923)
!3090 = !DISubprogram(name: "base", linkageName: "_ZNKSt13move_iteratorIPSt4pairIPN5clang10TokenLexerEmEE4baseEv", scope: !3079, file: !572, line: 1042, type: !3091, scopeLine: 1042, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3091 = !DISubroutineType(types: !3092)
!3092 = !{!3089, !3093}
!3093 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3094, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3094 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3079)
!3095 = !DISubprogram(name: "operator*", linkageName: "_ZNKSt13move_iteratorIPSt4pairIPN5clang10TokenLexerEmEEdeEv", scope: !3079, file: !572, line: 1046, type: !3096, scopeLine: 1046, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3096 = !DISubroutineType(types: !3097)
!3097 = !{!3098, !3093}
!3098 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3079, file: !572, line: 1026, baseType: !3099)
!3099 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !3100, file: !1732, line: 1928, baseType: !2960)
!3100 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<clang::TokenLexer *, unsigned long> &&, std::pair<clang::TokenLexer *, unsigned long> &>", scope: !353, file: !1732, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !3101, identifier: "_ZTSSt11conditionalILb1EOSt4pairIPN5clang10TokenLexerEmERS4_E")
!3101 = !{!1735, !2975, !3102}
!3102 = !DITemplateTypeParameter(name: "_Iffalse", type: !2964)
!3103 = !DISubprogram(name: "operator->", linkageName: "_ZNKSt13move_iteratorIPSt4pairIPN5clang10TokenLexerEmEEptEv", scope: !3079, file: !572, line: 1050, type: !3104, scopeLine: 1050, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3104 = !DISubroutineType(types: !3105)
!3105 = !{!3106, !3093}
!3106 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3079, file: !572, line: 1021, baseType: !2923)
!3107 = !DISubprogram(name: "operator++", linkageName: "_ZNSt13move_iteratorIPSt4pairIPN5clang10TokenLexerEmEEppEv", scope: !3079, file: !572, line: 1054, type: !3108, scopeLine: 1054, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3108 = !DISubroutineType(types: !3109)
!3109 = !{!3110, !3085}
!3110 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3079, size: 64)
!3111 = !DISubprogram(name: "operator++", linkageName: "_ZNSt13move_iteratorIPSt4pairIPN5clang10TokenLexerEmEEppEi", scope: !3079, file: !572, line: 1061, type: !3112, scopeLine: 1061, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3112 = !DISubroutineType(types: !3113)
!3113 = !{!3079, !3085, !324}
!3114 = !DISubprogram(name: "operator--", linkageName: "_ZNSt13move_iteratorIPSt4pairIPN5clang10TokenLexerEmEEmmEv", scope: !3079, file: !572, line: 1069, type: !3108, scopeLine: 1069, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3115 = !DISubprogram(name: "operator--", linkageName: "_ZNSt13move_iteratorIPSt4pairIPN5clang10TokenLexerEmEEmmEi", scope: !3079, file: !572, line: 1076, type: !3112, scopeLine: 1076, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3116 = !DISubprogram(name: "operator+", linkageName: "_ZNKSt13move_iteratorIPSt4pairIPN5clang10TokenLexerEmEEplEl", scope: !3079, file: !572, line: 1084, type: !3117, scopeLine: 1084, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3117 = !DISubroutineType(types: !3118)
!3118 = !{!3079, !3093, !3119}
!3119 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !3079, file: !572, line: 1019, baseType: !3064)
!3120 = !DISubprogram(name: "operator+=", linkageName: "_ZNSt13move_iteratorIPSt4pairIPN5clang10TokenLexerEmEEpLEl", scope: !3079, file: !572, line: 1088, type: !3121, scopeLine: 1088, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3121 = !DISubroutineType(types: !3122)
!3122 = !{!3110, !3085, !3119}
!3123 = !DISubprogram(name: "operator-", linkageName: "_ZNKSt13move_iteratorIPSt4pairIPN5clang10TokenLexerEmEEmiEl", scope: !3079, file: !572, line: 1095, type: !3117, scopeLine: 1095, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3124 = !DISubprogram(name: "operator-=", linkageName: "_ZNSt13move_iteratorIPSt4pairIPN5clang10TokenLexerEmEEmIEl", scope: !3079, file: !572, line: 1099, type: !3121, scopeLine: 1099, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3125 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt13move_iteratorIPSt4pairIPN5clang10TokenLexerEmEEixEl", scope: !3079, file: !572, line: 1106, type: !3126, scopeLine: 1106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3126 = !DISubroutineType(types: !3127)
!3127 = !{!3098, !3093, !3119}
!3128 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2910, size: 64)
!3129 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !3022, file: !2794, line: 371, baseType: !3130)
!3130 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<const std::pair<clang::TokenLexer *, unsigned long> *, std::vector<std::pair<clang::TokenLexer *, unsigned long>, std::allocator<std::pair<clang::TokenLexer *, unsigned long> > > >", scope: !5, file: !572, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3131, templateParams: !3183, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEE")
!3131 = !{!3132, !3134, !3138, !3143, !3153, !3158, !3162, !3165, !3166, !3167, !3172, !3175, !3178, !3179, !3180}
!3132 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !3130, file: !572, line: 767, baseType: !3133, size: 64, flags: DIFlagProtected)
!3133 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2956, size: 64)
!3134 = !DISubprogram(name: "__normal_iterator", scope: !3130, file: !572, line: 779, type: !3135, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3135 = !DISubroutineType(types: !3136)
!3136 = !{null, !3137}
!3137 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3130, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3138 = !DISubprogram(name: "__normal_iterator", scope: !3130, file: !572, line: 783, type: !3139, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3139 = !DISubroutineType(types: !3140)
!3140 = !{null, !3137, !3141}
!3141 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3142, size: 64)
!3142 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3133)
!3143 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEdeEv", scope: !3130, file: !572, line: 796, type: !3144, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3144 = !DISubroutineType(types: !3145)
!3145 = !{!3146, !3151}
!3146 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3130, file: !572, line: 776, baseType: !3147)
!3147 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3148, file: !3040, line: 195, baseType: !2955)
!3148 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<const std::pair<clang::TokenLexer *, unsigned long> *>", scope: !353, file: !3040, line: 189, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !3149, identifier: "_ZTSSt15iterator_traitsIPKSt4pairIPN5clang10TokenLexerEmEE")
!3149 = !{!3150}
!3150 = !DITemplateTypeParameter(name: "_Iterator", type: !3133)
!3151 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3152, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3152 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3130)
!3153 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEptEv", scope: !3130, file: !572, line: 800, type: !3154, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3154 = !DISubroutineType(types: !3155)
!3155 = !{!3156, !3151}
!3156 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3130, file: !572, line: 777, baseType: !3157)
!3157 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3148, file: !3040, line: 194, baseType: !3133)
!3158 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEppEv", scope: !3130, file: !572, line: 804, type: !3159, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3159 = !DISubroutineType(types: !3160)
!3160 = !{!3161, !3137}
!3161 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3130, size: 64)
!3162 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEppEi", scope: !3130, file: !572, line: 811, type: !3163, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3163 = !DISubroutineType(types: !3164)
!3164 = !{!3130, !3137, !324}
!3165 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEmmEv", scope: !3130, file: !572, line: 816, type: !3159, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3166 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEmmEi", scope: !3130, file: !572, line: 823, type: !3163, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3167 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEixEl", scope: !3130, file: !572, line: 828, type: !3168, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3168 = !DISubroutineType(types: !3169)
!3169 = !{!3146, !3151, !3170}
!3170 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !3130, file: !572, line: 775, baseType: !3171)
!3171 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !3148, file: !3040, line: 193, baseType: !3065)
!3172 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEpLEl", scope: !3130, file: !572, line: 832, type: !3173, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3173 = !DISubroutineType(types: !3174)
!3174 = !{!3161, !3137, !3170}
!3175 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEplEl", scope: !3130, file: !572, line: 836, type: !3176, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3176 = !DISubroutineType(types: !3177)
!3177 = !{!3130, !3151, !3170}
!3178 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEmIEl", scope: !3130, file: !572, line: 840, type: !3173, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3179 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEEmiEl", scope: !3130, file: !572, line: 844, type: !3176, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3180 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKSt4pairIPN5clang10TokenLexerEmESt6vectorIS5_SaIS5_EEE4baseEv", scope: !3130, file: !572, line: 848, type: !3181, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3181 = !DISubroutineType(types: !3182)
!3182 = !{!3141, !3151}
!3183 = !{!3150, !3078}
!3184 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !3185, file: !1967, line: 377, baseType: !3267)
!3185 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<char>", scope: !342, file: !1967, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3186, templateParams: !3266, identifier: "_ZTSN4llvm15SmallVectorImplIcEE")
!3186 = !{!3187, !3206, !3212, !3215, !3218, !3219, !3220, !3223, !3224, !3227, !3231, !3234, !3235, !3239, !3242, !3246, !3249, !3252, !3255, !3259, !3263, !3264, !3265}
!3187 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3185, baseType: !3188, flags: DIFlagPublic, extraData: i32 0)
!3188 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<char, true>", scope: !342, file: !1967, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3189, templateParams: !3205, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseIcLb1EEE")
!3189 = !{!3190, !3191, !3195, !3198, !3199, !3202}
!3190 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3188, baseType: !2279, flags: DIFlagPublic, extraData: i32 0)
!3191 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !3188, file: !1967, line: 298, type: !3192, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3192 = !DISubroutineType(types: !3193)
!3193 = !{null, !3194, !1583}
!3194 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3188, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3195 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIcLb1EE13destroy_rangeEPcS2_", scope: !3188, file: !1967, line: 301, type: !3196, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3196 = !DISubroutineType(types: !3197)
!3197 = !{null, !373, !373}
!3198 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIcLb1EE4growEm", scope: !3188, file: !1967, line: 346, type: !3192, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3199 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIcLb1EE9push_backERKc", scope: !3188, file: !1967, line: 350, type: !3200, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3200 = !DISubroutineType(types: !3201)
!3201 = !{null, !3194, !410}
!3202 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIcLb1EE8pop_backEv", scope: !3188, file: !1967, line: 361, type: !3203, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3203 = !DISubroutineType(types: !3204)
!3204 = !{null, !3194}
!3205 = !{!2371, !2215}
!3206 = !DISubprogram(name: "SmallVectorImpl", scope: !3185, file: !1967, line: 374, type: !3207, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!3207 = !DISubroutineType(types: !3208)
!3208 = !{null, !3209, !3210}
!3209 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3185, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3210 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3211, size: 64)
!3211 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3185)
!3212 = !DISubprogram(name: "SmallVectorImpl", scope: !3185, file: !1967, line: 381, type: !3213, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3213 = !DISubroutineType(types: !3214)
!3214 = !{null, !3209, !6}
!3215 = !DISubprogram(name: "~SmallVectorImpl", scope: !3185, file: !1967, line: 386, type: !3216, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3216 = !DISubroutineType(types: !3217)
!3217 = !{null, !3209}
!3218 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplIcE5clearEv", scope: !3185, file: !1967, line: 396, type: !3216, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3219 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIcE6resizeEj", scope: !3185, file: !1967, line: 401, type: !3213, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3220 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIcE6resizeEjRKc", scope: !3185, file: !1967, line: 413, type: !3221, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3221 = !DISubroutineType(types: !3222)
!3222 = !{null, !3209, !6, !410}
!3223 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplIcE7reserveEj", scope: !3185, file: !1967, line: 425, type: !3213, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3224 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplIcE12pop_back_valEv", scope: !3185, file: !1967, line: 430, type: !3225, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3225 = !DISubroutineType(types: !3226)
!3226 = !{!374, !3209}
!3227 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplIcE4swapERS1_", scope: !3185, file: !1967, line: 440, type: !3228, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3228 = !DISubroutineType(types: !3229)
!3229 = !{null, !3209, !3230}
!3230 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3185, size: 64)
!3231 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplIcE6appendEmRKc", scope: !3185, file: !1967, line: 460, type: !3232, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3232 = !DISubroutineType(types: !3233)
!3233 = !{null, !3209, !3184, !410}
!3234 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplIcE6assignEjRKc", scope: !3185, file: !1967, line: 470, type: !3221, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3235 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIcE5eraseEPc", scope: !3185, file: !1967, line: 478, type: !3236, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3236 = !DISubroutineType(types: !3237)
!3237 = !{!3238, !3209, !3238}
!3238 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3185, file: !1967, line: 376, baseType: !2278)
!3239 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIcE5eraseEPcS2_", scope: !3185, file: !1967, line: 490, type: !3240, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3240 = !DISubroutineType(types: !3241)
!3241 = !{!3238, !3209, !3238, !3238}
!3242 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIcE6insertEPcOc", scope: !3185, file: !1967, line: 505, type: !3243, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3243 = !DISubroutineType(types: !3244)
!3244 = !{!3238, !3209, !3238, !3245}
!3245 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !374, size: 64)
!3246 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIcE6insertEPcRKc", scope: !3185, file: !1967, line: 537, type: !3247, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3247 = !DISubroutineType(types: !3248)
!3248 = !{!3238, !3209, !3238, !410}
!3249 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIcE6insertEPcmRKc", scope: !3185, file: !1967, line: 568, type: !3250, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3250 = !DISubroutineType(types: !3251)
!3251 = !{!3238, !3209, !3238, !3184, !410}
!3252 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIcEaSERKS1_", scope: !3185, file: !1967, line: 674, type: !3253, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3253 = !DISubroutineType(types: !3254)
!3254 = !{!3230, !3209, !3210}
!3255 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIcEaSEOS1_", scope: !3185, file: !1967, line: 677, type: !3256, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3256 = !DISubroutineType(types: !3257)
!3257 = !{!3230, !3209, !3258}
!3258 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3185, size: 64)
!3259 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplIcEeqERKS1_", scope: !3185, file: !1967, line: 680, type: !3260, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3260 = !DISubroutineType(types: !3261)
!3261 = !{!308, !3262, !3210}
!3262 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3211, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3263 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplIcEneERKS1_", scope: !3185, file: !1967, line: 684, type: !3260, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3264 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplIcEltERKS1_", scope: !3185, file: !1967, line: 688, type: !3260, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3265 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplIcE8set_sizeEj", scope: !3185, file: !1967, line: 702, type: !3213, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3266 = !{!2371}
!3267 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2279, file: !1967, line: 97, baseType: !1583)
!3268 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ArrayRef<clang::Token>", scope: !342, file: !3269, line: 31, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3270, templateParams: !2276, identifier: "_ZTSN4llvm8ArrayRefIN5clang5TokenEEE")
!3269 = !DIFile(filename: "llvm34/include/llvm/ADT/ArrayRef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "6317ba9f99cd1980a6299fb308b36f31")
!3270 = !{!3271, !3272, !3274, !3278, !3281, !3284, !3287, !3290, !3296, !3302, !3303, !3307, !3308, !3311, !3314, !3317, !3320, !3321, !3324, !3327, !3330, !3333, !3337}
!3271 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !3268, file: !3269, line: 41, baseType: !2072, size: 64)
!3272 = !DIDerivedType(tag: DW_TAG_member, name: "Length", scope: !3268, file: !3269, line: 44, baseType: !3273, size: 64, offset: 64)
!3273 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !3269, line: 35, baseType: !1583)
!3274 = !DISubprogram(name: "ArrayRef", scope: !3268, file: !3269, line: 51, type: !3275, scopeLine: 51, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3275 = !DISubroutineType(types: !3276)
!3276 = !{null, !3277}
!3277 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3268, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3278 = !DISubprogram(name: "ArrayRef", scope: !3268, file: !3269, line: 54, type: !3279, scopeLine: 54, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3279 = !DISubroutineType(types: !3280)
!3280 = !{null, !3277, !1425}
!3281 = !DISubprogram(name: "ArrayRef", scope: !3268, file: !3269, line: 57, type: !3282, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3282 = !DISubroutineType(types: !3283)
!3283 = !{null, !3277, !2082}
!3284 = !DISubprogram(name: "ArrayRef", scope: !3268, file: !3269, line: 61, type: !3285, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3285 = !DISubroutineType(types: !3286)
!3286 = !{null, !3277, !2072, !1583}
!3287 = !DISubprogram(name: "ArrayRef", scope: !3268, file: !3269, line: 65, type: !3288, scopeLine: 65, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3288 = !DISubroutineType(types: !3289)
!3289 = !{null, !3277, !2072, !2072}
!3290 = !DISubprogram(name: "ArrayRef", scope: !3268, file: !3269, line: 88, type: !3291, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3291 = !DISubroutineType(types: !3292)
!3292 = !{null, !3277, !3293}
!3293 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3294, size: 64)
!3294 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3295)
!3295 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<clang::Token>", scope: !353, file: !628, line: 47, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listIN5clang5TokenEE")
!3296 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEE5beginEv", scope: !3268, file: !3269, line: 97, type: !3297, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3297 = !DISubroutineType(types: !3298)
!3298 = !{!3299, !3300}
!3299 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3268, file: !3269, line: 33, baseType: !2072)
!3300 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3301, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3301 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3268)
!3302 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEE3endEv", scope: !3268, file: !3269, line: 98, type: !3297, scopeLine: 98, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3303 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEE6rbeginEv", scope: !3268, file: !3269, line: 100, type: !3304, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3304 = !DISubroutineType(types: !3305)
!3305 = !{!3306, !3300}
!3306 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !3268, file: !3269, line: 37, baseType: !2053)
!3307 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEE4rendEv", scope: !3268, file: !3269, line: 101, type: !3304, scopeLine: 101, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3308 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEE5emptyEv", scope: !3268, file: !3269, line: 104, type: !3309, scopeLine: 104, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3309 = !DISubroutineType(types: !3310)
!3310 = !{!308, !3300}
!3311 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEE4dataEv", scope: !3268, file: !3269, line: 106, type: !3312, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3312 = !DISubroutineType(types: !3313)
!3313 = !{!2072, !3300}
!3314 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEE4sizeEv", scope: !3268, file: !3269, line: 109, type: !3315, scopeLine: 109, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3315 = !DISubroutineType(types: !3316)
!3316 = !{!1583, !3300}
!3317 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEE5frontEv", scope: !3268, file: !3269, line: 112, type: !3318, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3318 = !DISubroutineType(types: !3319)
!3319 = !{!2082, !3300}
!3320 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEE4backEv", scope: !3268, file: !3269, line: 118, type: !3318, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3321 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEE6equalsES3_", scope: !3268, file: !3269, line: 124, type: !3322, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3322 = !DISubroutineType(types: !3323)
!3323 = !{!308, !3300, !3268}
!3324 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEE5sliceEj", scope: !3268, file: !3269, line: 134, type: !3325, scopeLine: 134, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3325 = !DISubroutineType(types: !3326)
!3326 = !{!3268, !3300, !6}
!3327 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEE5sliceEjj", scope: !3268, file: !3269, line: 141, type: !3328, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3328 = !DISubroutineType(types: !3329)
!3329 = !{!3268, !3300, !6, !6}
!3330 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEEixEm", scope: !3268, file: !3269, line: 149, type: !3331, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3331 = !DISubroutineType(types: !3332)
!3332 = !{!2082, !3300, !1583}
!3333 = !DISubprogram(name: "vec", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEE3vecEv", scope: !3268, file: !3269, line: 157, type: !3334, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3334 = !DISubroutineType(types: !3335)
!3335 = !{!3336, !3300}
!3336 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<clang::Token, std::allocator<clang::Token> >", scope: !353, file: !2794, line: 339, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt6vectorIN5clang5TokenESaIS1_EE")
!3337 = !DISubprogram(name: "operator vector", linkageName: "_ZNK4llvm8ArrayRefIN5clang5TokenEEcvSt6vectorIS2_SaIS2_EEEv", scope: !3268, file: !3269, line: 164, type: !3334, scopeLine: 164, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3338 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DefInfo", scope: !1828, file: !1827, line: 395, size: 128, flags: DIFlagPublic | DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3339, identifier: "_ZTSN5clang14MacroDirective7DefInfoE")
!3339 = !{!3340, !3341, !3342, !3343, !3347, !3350, !3357, !3360, !3363, !3368, !3373, !3374, !3377, !3378, !3379, !3380, !3381, !3384}
!3340 = !DIDerivedType(tag: DW_TAG_member, name: "DefDirective", scope: !3338, file: !1827, line: 396, baseType: !2792, size: 64)
!3341 = !DIDerivedType(tag: DW_TAG_member, name: "UndefLoc", scope: !3338, file: !1827, line: 397, baseType: !297, size: 32, offset: 64)
!3342 = !DIDerivedType(tag: DW_TAG_member, name: "IsPublic", scope: !3338, file: !1827, line: 398, baseType: !308, size: 8, offset: 96)
!3343 = !DISubprogram(name: "DefInfo", scope: !3338, file: !1827, line: 401, type: !3344, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3344 = !DISubroutineType(types: !3345)
!3345 = !{null, !3346}
!3346 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3338, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3347 = !DISubprogram(name: "DefInfo", scope: !3338, file: !1827, line: 403, type: !3348, scopeLine: 403, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3348 = !DISubroutineType(types: !3349)
!3349 = !{null, !3346, !2792, !297, !308}
!3350 = !DISubprogram(name: "getDirective", linkageName: "_ZNK5clang14MacroDirective7DefInfo12getDirectiveEv", scope: !3338, file: !1827, line: 407, type: !3351, scopeLine: 407, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3351 = !DISubroutineType(types: !3352)
!3352 = !{!3353, !3355}
!3353 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3354, size: 64)
!3354 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2784)
!3355 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3356, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3356 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3338)
!3357 = !DISubprogram(name: "getDirective", linkageName: "_ZN5clang14MacroDirective7DefInfo12getDirectiveEv", scope: !3338, file: !1827, line: 408, type: !3358, scopeLine: 408, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3358 = !DISubroutineType(types: !3359)
!3359 = !{!2792, !3346}
!3360 = !DISubprogram(name: "getLocation", linkageName: "_ZNK5clang14MacroDirective7DefInfo11getLocationEv", scope: !3338, file: !1827, line: 410, type: !3361, scopeLine: 410, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3361 = !DISubroutineType(types: !3362)
!3362 = !{!297, !3355}
!3363 = !DISubprogram(name: "getMacroInfo", linkageName: "_ZN5clang14MacroDirective7DefInfo12getMacroInfoEv", scope: !3338, file: !1827, line: 411, type: !3364, scopeLine: 411, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3364 = !DISubroutineType(types: !3365)
!3365 = !{!3366, !3346}
!3366 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3367, size: 64)
!3367 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MacroInfo", scope: !14, file: !1827, line: 29, size: 1984, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang9MacroInfoE")
!3368 = !DISubprogram(name: "getMacroInfo", linkageName: "_ZNK5clang14MacroDirective7DefInfo12getMacroInfoEv", scope: !3338, file: !1827, line: 412, type: !3369, scopeLine: 412, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3369 = !DISubroutineType(types: !3370)
!3370 = !{!3371, !3355}
!3371 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3372, size: 64)
!3372 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3367)
!3373 = !DISubprogram(name: "getUndefLocation", linkageName: "_ZNK5clang14MacroDirective7DefInfo16getUndefLocationEv", scope: !3338, file: !1827, line: 416, type: !3361, scopeLine: 416, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3374 = !DISubprogram(name: "isUndefined", linkageName: "_ZNK5clang14MacroDirective7DefInfo11isUndefinedEv", scope: !3338, file: !1827, line: 417, type: !3375, scopeLine: 417, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3375 = !DISubroutineType(types: !3376)
!3376 = !{!308, !3355}
!3377 = !DISubprogram(name: "isPublic", linkageName: "_ZNK5clang14MacroDirective7DefInfo8isPublicEv", scope: !3338, file: !1827, line: 419, type: !3375, scopeLine: 419, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3378 = !DISubprogram(name: "isValid", linkageName: "_ZNK5clang14MacroDirective7DefInfo7isValidEv", scope: !3338, file: !1827, line: 421, type: !3375, scopeLine: 421, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3379 = !DISubprogram(name: "isInvalid", linkageName: "_ZNK5clang14MacroDirective7DefInfo9isInvalidEv", scope: !3338, file: !1827, line: 422, type: !3375, scopeLine: 422, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3380 = !DISubprogram(name: "operator bool", linkageName: "_ZNK5clang14MacroDirective7DefInfocvbEv", scope: !3338, file: !1827, line: 424, type: !3375, scopeLine: 424, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3381 = !DISubprogram(name: "getPreviousDefinition", linkageName: "_ZN5clang14MacroDirective7DefInfo21getPreviousDefinitionEb", scope: !3338, file: !1827, line: 426, type: !3382, scopeLine: 426, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3382 = !DISubroutineType(types: !3383)
!3383 = !{!3338, !3346, !308}
!3384 = !DISubprogram(name: "getPreviousDefinition", linkageName: "_ZNK5clang14MacroDirective7DefInfo21getPreviousDefinitionEb", scope: !3338, file: !1827, line: 427, type: !3385, scopeLine: 427, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3385 = !DISubroutineType(types: !3386)
!3386 = !{!3356, !3355, !308}
!3387 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<Bracket, 8U>", scope: !342, file: !1967, line: 880, size: 448, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3388, templateParams: !3481, identifier: "_ZTSN4llvm11SmallVectorI7BracketLj8EEE")
!3388 = !{!3389, !3474, !3483, !3487, !3490, !3495, !3498, !3502}
!3389 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3387, baseType: !3390, flags: DIFlagPublic, extraData: i32 0)
!3390 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<Bracket>", scope: !342, file: !1967, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3391, templateParams: !3473, identifier: "_ZTSN4llvm15SmallVectorImplI7BracketEE")
!3391 = !{!3392, !3411, !3417, !3420, !3423, !3424, !3425, !3428, !3429, !3432, !3436, !3441, !3442, !3446, !3449, !3453, !3456, !3459, !3462, !3466, !3470, !3471, !3472}
!3392 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3390, baseType: !3393, flags: DIFlagPublic, extraData: i32 0)
!3393 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<Bracket, true>", scope: !342, file: !1967, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3394, templateParams: !3410, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseI7BracketLb1EEE")
!3394 = !{!3395, !3396, !3400, !3403, !3404, !3407}
!3395 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3393, baseType: !2095, flags: DIFlagPublic, extraData: i32 0)
!3396 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !3393, file: !1967, line: 298, type: !3397, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3397 = !DISubroutineType(types: !3398)
!3398 = !{null, !3399, !1583}
!3399 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3393, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3400 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseI7BracketLb1EE13destroy_rangeEPS1_S3_", scope: !3393, file: !1967, line: 301, type: !3401, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3401 = !DISubroutineType(types: !3402)
!3402 = !{null, !2132, !2132}
!3403 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseI7BracketLb1EE4growEm", scope: !3393, file: !1967, line: 346, type: !3397, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3404 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseI7BracketLb1EE9push_backERKS1_", scope: !3393, file: !1967, line: 350, type: !3405, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3405 = !DISubroutineType(types: !3406)
!3406 = !{null, !3399, !2182}
!3407 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseI7BracketLb1EE8pop_backEv", scope: !3393, file: !1967, line: 361, type: !3408, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3408 = !DISubroutineType(types: !3409)
!3409 = !{null, !3399}
!3410 = !{!2192, !2215}
!3411 = !DISubprogram(name: "SmallVectorImpl", scope: !3390, file: !1967, line: 374, type: !3412, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!3412 = !DISubroutineType(types: !3413)
!3413 = !{null, !3414, !3415}
!3414 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3390, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3415 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3416, size: 64)
!3416 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3390)
!3417 = !DISubprogram(name: "SmallVectorImpl", scope: !3390, file: !1967, line: 381, type: !3418, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3418 = !DISubroutineType(types: !3419)
!3419 = !{null, !3414, !6}
!3420 = !DISubprogram(name: "~SmallVectorImpl", scope: !3390, file: !1967, line: 386, type: !3421, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3421 = !DISubroutineType(types: !3422)
!3422 = !{null, !3414}
!3423 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplI7BracketE5clearEv", scope: !3390, file: !1967, line: 396, type: !3421, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3424 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplI7BracketE6resizeEj", scope: !3390, file: !1967, line: 401, type: !3418, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3425 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplI7BracketE6resizeEjRKS1_", scope: !3390, file: !1967, line: 413, type: !3426, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3426 = !DISubroutineType(types: !3427)
!3427 = !{null, !3414, !6, !2182}
!3428 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplI7BracketE7reserveEj", scope: !3390, file: !1967, line: 425, type: !3418, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3429 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplI7BracketE12pop_back_valEv", scope: !3390, file: !1967, line: 430, type: !3430, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3430 = !DISubroutineType(types: !3431)
!3431 = !{!1449, !3414}
!3432 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplI7BracketE4swapERS2_", scope: !3390, file: !1967, line: 440, type: !3433, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3433 = !DISubroutineType(types: !3434)
!3434 = !{null, !3414, !3435}
!3435 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3390, size: 64)
!3436 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplI7BracketE6appendEmRKS1_", scope: !3390, file: !1967, line: 460, type: !3437, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3437 = !DISubroutineType(types: !3438)
!3438 = !{null, !3414, !3439, !2182}
!3439 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !3390, file: !1967, line: 377, baseType: !3440)
!3440 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2095, file: !1967, line: 97, baseType: !1583)
!3441 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplI7BracketE6assignEjRKS1_", scope: !3390, file: !1967, line: 470, type: !3426, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3442 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplI7BracketE5eraseEPS1_", scope: !3390, file: !1967, line: 478, type: !3443, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3443 = !DISubroutineType(types: !3444)
!3444 = !{!3445, !3414, !3445}
!3445 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !3390, file: !1967, line: 376, baseType: !2094)
!3446 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplI7BracketE5eraseEPS1_S3_", scope: !3390, file: !1967, line: 490, type: !3447, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3447 = !DISubroutineType(types: !3448)
!3448 = !{!3445, !3414, !3445, !3445}
!3449 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplI7BracketE6insertEPS1_OS1_", scope: !3390, file: !1967, line: 505, type: !3450, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3450 = !DISubroutineType(types: !3451)
!3451 = !{!3445, !3414, !3445, !3452}
!3452 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1449, size: 64)
!3453 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplI7BracketE6insertEPS1_RKS1_", scope: !3390, file: !1967, line: 537, type: !3454, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3454 = !DISubroutineType(types: !3455)
!3455 = !{!3445, !3414, !3445, !2182}
!3456 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplI7BracketE6insertEPS1_mRKS1_", scope: !3390, file: !1967, line: 568, type: !3457, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3457 = !DISubroutineType(types: !3458)
!3458 = !{!3445, !3414, !3445, !3439, !2182}
!3459 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplI7BracketEaSERKS2_", scope: !3390, file: !1967, line: 674, type: !3460, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3460 = !DISubroutineType(types: !3461)
!3461 = !{!3435, !3414, !3415}
!3462 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplI7BracketEaSEOS2_", scope: !3390, file: !1967, line: 677, type: !3463, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3463 = !DISubroutineType(types: !3464)
!3464 = !{!3435, !3414, !3465}
!3465 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3390, size: 64)
!3466 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplI7BracketEeqERKS2_", scope: !3390, file: !1967, line: 680, type: !3467, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3467 = !DISubroutineType(types: !3468)
!3468 = !{!308, !3469, !3415}
!3469 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3416, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3470 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplI7BracketEneERKS2_", scope: !3390, file: !1967, line: 684, type: !3467, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3471 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplI7BracketEltERKS2_", scope: !3390, file: !1967, line: 688, type: !3467, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3472 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplI7BracketE8set_sizeEj", scope: !3390, file: !1967, line: 702, type: !3418, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3473 = !{!2192}
!3474 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !3387, file: !1967, line: 882, baseType: !3475, size: 224, offset: 224)
!3475 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<Bracket, 8U>", scope: !342, file: !1967, line: 865, size: 224, flags: DIFlagTypePassByValue, elements: !3476, templateParams: !3481, identifier: "_ZTSN4llvm18SmallVectorStorageI7BracketLj8EEE")
!3476 = !{!3477}
!3477 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !3475, file: !1967, line: 866, baseType: !3478, size: 224)
!3478 = !DICompositeType(tag: DW_TAG_array_type, baseType: !2099, size: 224, elements: !3479)
!3479 = !{!3480}
!3480 = !DISubrange(count: 7)
!3481 = !{!2192, !3482}
!3482 = !DITemplateValueParameter(name: "N", type: !6, value: i32 8)
!3483 = !DISubprogram(name: "SmallVector", scope: !3387, file: !1967, line: 884, type: !3484, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3484 = !DISubroutineType(types: !3485)
!3485 = !{null, !3486}
!3486 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3387, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3487 = !DISubprogram(name: "SmallVector", scope: !3387, file: !1967, line: 887, type: !3488, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3488 = !DISubroutineType(types: !3489)
!3489 = !{null, !3486, !6, !2182}
!3490 = !DISubprogram(name: "SmallVector", scope: !3387, file: !1967, line: 897, type: !3491, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3491 = !DISubroutineType(types: !3492)
!3492 = !{null, !3486, !3493}
!3493 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3494, size: 64)
!3494 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3387)
!3495 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorI7BracketLj8EEaSERKS2_", scope: !3387, file: !1967, line: 902, type: !3496, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3496 = !DISubroutineType(types: !3497)
!3497 = !{!3493, !3486, !3493}
!3498 = !DISubprogram(name: "SmallVector", scope: !3387, file: !1967, line: 908, type: !3499, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3499 = !DISubroutineType(types: !3500)
!3500 = !{null, !3486, !3501}
!3501 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3387, size: 64)
!3502 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorI7BracketLj8EEaSEOS2_", scope: !3387, file: !1967, line: 913, type: !3503, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3503 = !DISubroutineType(types: !3504)
!3504 = !{!3493, !3486, !3501}
!3505 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "integral_constant<bool, true>", scope: !353, file: !1732, line: 57, size: 8, flags: DIFlagTypePassByValue, elements: !3506, templateParams: !3515, identifier: "_ZTSSt17integral_constantIbLb1EE")
!3506 = !{!3507, !3508, !3514}
!3507 = !DIDerivedType(tag: DW_TAG_member, name: "value", scope: !3505, file: !1732, line: 59, baseType: !2525, flags: DIFlagStaticMember, extraData: i1 true)
!3508 = !DISubprogram(name: "operator bool", linkageName: "_ZNKSt17integral_constantIbLb1EEcvbEv", scope: !3505, file: !1732, line: 62, type: !3509, scopeLine: 62, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3509 = !DISubroutineType(types: !3510)
!3510 = !{!3511, !3512}
!3511 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !3505, file: !1732, line: 60, baseType: !308)
!3512 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3513, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3513 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3505)
!3514 = !DISubprogram(name: "operator()", linkageName: "_ZNKSt17integral_constantIbLb1EEclEv", scope: !3505, file: !1732, line: 67, type: !3509, scopeLine: 67, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3515 = !{!3516, !3517}
!3516 = !DITemplateTypeParameter(name: "_Tp", type: !308)
!3517 = !DITemplateValueParameter(name: "__v", type: !308, value: i8 1)
!3518 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallString<32U>", scope: !342, file: !3519, line: 25, size: 448, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3520, templateParams: !3631, identifier: "_ZTSN4llvm11SmallStringILj32EEE")
!3519 = !DIFile(filename: "llvm34/include/llvm/ADT/SmallString.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "2c780b02f5ec1f15da12c71ace03c232")
!3520 = !{!3521, !3556, !3560, !3563, !3568, !3571, !3572, !3575, !3576, !3577, !3578, !3582, !3583, !3586, !3587, !3588, !3589, !3590, !3593, !3596, !3597, !3600, !3601, !3602, !3603, !3604, !3605, !3606, !3609, !3610, !3613, !3614, !3617, !3620, !3621, !3624, !3628}
!3521 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3518, baseType: !3522, flags: DIFlagPublic, extraData: i32 0)
!3522 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<char, 32U>", scope: !342, file: !1967, line: 880, size: 448, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3523, templateParams: !3532, identifier: "_ZTSN4llvm11SmallVectorIcLj32EEE")
!3523 = !{!3524, !3525, !3534, !3538, !3541, !3546, !3549, !3553}
!3524 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3522, baseType: !3185, flags: DIFlagPublic, extraData: i32 0)
!3525 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !3522, file: !1967, line: 882, baseType: !3526, size: 248, offset: 200)
!3526 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<char, 32U>", scope: !342, file: !1967, line: 865, size: 248, flags: DIFlagTypePassByValue, elements: !3527, templateParams: !3532, identifier: "_ZTSN4llvm18SmallVectorStorageIcLj32EEE")
!3527 = !{!3528}
!3528 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !3526, file: !1967, line: 866, baseType: !3529, size: 248)
!3529 = !DICompositeType(tag: DW_TAG_array_type, baseType: !2283, size: 248, elements: !3530)
!3530 = !{!3531}
!3531 = !DISubrange(count: 31)
!3532 = !{!2371, !3533}
!3533 = !DITemplateValueParameter(name: "N", type: !6, value: i32 32)
!3534 = !DISubprogram(name: "SmallVector", scope: !3522, file: !1967, line: 884, type: !3535, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3535 = !DISubroutineType(types: !3536)
!3536 = !{null, !3537}
!3537 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3522, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3538 = !DISubprogram(name: "SmallVector", scope: !3522, file: !1967, line: 887, type: !3539, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3539 = !DISubroutineType(types: !3540)
!3540 = !{null, !3537, !6, !410}
!3541 = !DISubprogram(name: "SmallVector", scope: !3522, file: !1967, line: 897, type: !3542, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3542 = !DISubroutineType(types: !3543)
!3543 = !{null, !3537, !3544}
!3544 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3545, size: 64)
!3545 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3522)
!3546 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIcLj32EEaSERKS1_", scope: !3522, file: !1967, line: 902, type: !3547, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3547 = !DISubroutineType(types: !3548)
!3548 = !{!3544, !3537, !3544}
!3549 = !DISubprogram(name: "SmallVector", scope: !3522, file: !1967, line: 908, type: !3550, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3550 = !DISubroutineType(types: !3551)
!3551 = !{null, !3537, !3552}
!3552 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3522, size: 64)
!3553 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIcLj32EEaSEOS1_", scope: !3522, file: !1967, line: 913, type: !3554, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3554 = !DISubroutineType(types: !3555)
!3555 = !{!3544, !3537, !3552}
!3556 = !DISubprogram(name: "SmallString", scope: !3518, file: !3519, line: 28, type: !3557, scopeLine: 28, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3557 = !DISubroutineType(types: !3558)
!3558 = !{null, !3559}
!3559 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3518, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3560 = !DISubprogram(name: "SmallString", scope: !3518, file: !3519, line: 31, type: !3561, scopeLine: 31, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3561 = !DISubroutineType(types: !3562)
!3562 = !{null, !3559, !1578}
!3563 = !DISubprogram(name: "SmallString", scope: !3518, file: !3519, line: 38, type: !3564, scopeLine: 38, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3564 = !DISubroutineType(types: !3565)
!3565 = !{null, !3559, !3566}
!3566 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3567, size: 64)
!3567 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3518)
!3568 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj32EE6assignEmc", scope: !3518, file: !3519, line: 48, type: !3569, scopeLine: 48, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3569 = !DISubroutineType(types: !3570)
!3570 = !{null, !3559, !1583, !374}
!3571 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj32EE6assignENS_9StringRefE", scope: !3518, file: !3519, line: 60, type: !3561, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3572 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj32EE6assignERKNS_15SmallVectorImplIcEE", scope: !3518, file: !3519, line: 66, type: !3573, scopeLine: 66, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3573 = !DISubroutineType(types: !3574)
!3574 = !{null, !3559, !3210}
!3575 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj32EE6appendEmc", scope: !3518, file: !3519, line: 81, type: !3569, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3576 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj32EE6appendENS_9StringRefE", scope: !3518, file: !3519, line: 87, type: !3561, scopeLine: 87, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3577 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj32EE6appendERKNS_15SmallVectorImplIcEE", scope: !3518, file: !3519, line: 92, type: !3573, scopeLine: 92, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3578 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm11SmallStringILj32EE6equalsENS_9StringRefE", scope: !3518, file: !3519, line: 102, type: !3579, scopeLine: 102, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3579 = !DISubroutineType(types: !3580)
!3580 = !{!308, !3581, !1578}
!3581 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3567, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3582 = !DISubprogram(name: "equals_lower", linkageName: "_ZNK4llvm11SmallStringILj32EE12equals_lowerENS_9StringRefE", scope: !3518, file: !3519, line: 107, type: !3579, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3583 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm11SmallStringILj32EE7compareENS_9StringRefE", scope: !3518, file: !3519, line: 113, type: !3584, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3584 = !DISubroutineType(types: !3585)
!3585 = !{!324, !3581, !1578}
!3586 = !DISubprogram(name: "compare_lower", linkageName: "_ZNK4llvm11SmallStringILj32EE13compare_lowerENS_9StringRefE", scope: !3518, file: !3519, line: 118, type: !3584, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3587 = !DISubprogram(name: "compare_numeric", linkageName: "_ZNK4llvm11SmallStringILj32EE15compare_numericENS_9StringRefE", scope: !3518, file: !3519, line: 124, type: !3584, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3588 = !DISubprogram(name: "startswith", linkageName: "_ZNK4llvm11SmallStringILj32EE10startswithENS_9StringRefE", scope: !3518, file: !3519, line: 133, type: !3579, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3589 = !DISubprogram(name: "endswith", linkageName: "_ZNK4llvm11SmallStringILj32EE8endswithENS_9StringRefE", scope: !3518, file: !3519, line: 138, type: !3579, scopeLine: 138, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3590 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm11SmallStringILj32EE4findEcm", scope: !3518, file: !3519, line: 150, type: !3591, scopeLine: 150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3591 = !DISubroutineType(types: !3592)
!3592 = !{!1583, !3581, !374, !1583}
!3593 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm11SmallStringILj32EE4findENS_9StringRefEm", scope: !3518, file: !3519, line: 158, type: !3594, scopeLine: 158, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3594 = !DISubroutineType(types: !3595)
!3595 = !{!1583, !3581, !1578, !1583}
!3596 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm11SmallStringILj32EE5rfindEcm", scope: !3518, file: !3519, line: 166, type: !3591, scopeLine: 166, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3597 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm11SmallStringILj32EE5rfindENS_9StringRefE", scope: !3518, file: !3519, line: 174, type: !3598, scopeLine: 174, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3598 = !DISubroutineType(types: !3599)
!3599 = !{!1583, !3581, !1578}
!3600 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm11SmallStringILj32EE13find_first_ofEcm", scope: !3518, file: !3519, line: 180, type: !3591, scopeLine: 180, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3601 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm11SmallStringILj32EE13find_first_ofENS_9StringRefEm", scope: !3518, file: !3519, line: 188, type: !3594, scopeLine: 188, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3602 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm11SmallStringILj32EE17find_first_not_ofEcm", scope: !3518, file: !3519, line: 194, type: !3591, scopeLine: 194, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3603 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm11SmallStringILj32EE17find_first_not_ofENS_9StringRefEm", scope: !3518, file: !3519, line: 202, type: !3594, scopeLine: 202, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3604 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm11SmallStringILj32EE12find_last_ofEcm", scope: !3518, file: !3519, line: 208, type: !3591, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3605 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm11SmallStringILj32EE12find_last_ofENS_9StringRefEm", scope: !3518, file: !3519, line: 216, type: !3594, scopeLine: 216, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3606 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm11SmallStringILj32EE5countEc", scope: !3518, file: !3519, line: 226, type: !3607, scopeLine: 226, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3607 = !DISubroutineType(types: !3608)
!3608 = !{!1583, !3581, !374}
!3609 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm11SmallStringILj32EE5countENS_9StringRefE", scope: !3518, file: !3519, line: 232, type: !3598, scopeLine: 232, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3610 = !DISubprogram(name: "substr", linkageName: "_ZNK4llvm11SmallStringILj32EE6substrEmm", scope: !3518, file: !3519, line: 249, type: !3611, scopeLine: 249, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3611 = !DISubroutineType(types: !3612)
!3612 = !{!1578, !3581, !1583, !1583}
!3613 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm11SmallStringILj32EE5sliceEmm", scope: !3518, file: !3519, line: 263, type: !3611, scopeLine: 263, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3614 = !DISubprogram(name: "str", linkageName: "_ZNK4llvm11SmallStringILj32EE3strEv", scope: !3518, file: !3519, line: 270, type: !3615, scopeLine: 270, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3615 = !DISubroutineType(types: !3616)
!3616 = !{!1578, !3581}
!3617 = !DISubprogram(name: "c_str", linkageName: "_ZN4llvm11SmallStringILj32EE5c_strEv", scope: !3518, file: !3519, line: 273, type: !3618, scopeLine: 273, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3618 = !DISubroutineType(types: !3619)
!3619 = !{!407, !3559}
!3620 = !DISubprogram(name: "operator StringRef", linkageName: "_ZNK4llvm11SmallStringILj32EEcvNS_9StringRefEEv", scope: !3518, file: !3519, line: 280, type: !3615, scopeLine: 280, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3621 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallStringILj32EEaSENS_9StringRefE", scope: !3518, file: !3519, line: 283, type: !3622, scopeLine: 283, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3622 = !DISubroutineType(types: !3623)
!3623 = !{!3566, !3559, !1578}
!3624 = !DISubprogram(name: "operator+=", linkageName: "_ZN4llvm11SmallStringILj32EEpLENS_9StringRefE", scope: !3518, file: !3519, line: 288, type: !3625, scopeLine: 288, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3625 = !DISubroutineType(types: !3626)
!3626 = !{!3627, !3559, !1578}
!3627 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3518, size: 64)
!3628 = !DISubprogram(name: "operator+=", linkageName: "_ZN4llvm11SmallStringILj32EEpLEc", scope: !3518, file: !3519, line: 292, type: !3629, scopeLine: 292, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3629 = !DISubroutineType(types: !3630)
!3630 = !{!3627, !3559, !374}
!3631 = !{!3632}
!3632 = !DITemplateValueParameter(name: "InternalLen", type: !6, value: i32 32)
!3633 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "format_object3<const char *, int, int>", scope: !342, file: !3634, line: 115, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3635, vtableHolder: !3637, templateParams: !3654, identifier: "_ZTSN4llvm14format_object3IPKciiEE")
!3634 = !DIFile(filename: "llvm34/include/llvm/Support/Format.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "bf2e6ec12853d45d6f2c7a5ded7a65be")
!3635 = !{!3636, !3638, !3639, !3640, !3641, !3649}
!3636 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3633, baseType: !3637, flags: DIFlagPublic, extraData: i32 0)
!3637 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "format_object_base", scope: !342, file: !3634, line: 41, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm18format_object_baseE")
!3638 = !DIDerivedType(tag: DW_TAG_member, name: "Val1", scope: !3633, file: !3634, line: 116, baseType: !407, size: 64, offset: 128)
!3639 = !DIDerivedType(tag: DW_TAG_member, name: "Val2", scope: !3633, file: !3634, line: 117, baseType: !324, size: 32, offset: 192)
!3640 = !DIDerivedType(tag: DW_TAG_member, name: "Val3", scope: !3633, file: !3634, line: 118, baseType: !324, size: 32, offset: 224)
!3641 = !DISubprogram(name: "format_object3", scope: !3633, file: !3634, line: 120, type: !3642, scopeLine: 120, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3642 = !DISubroutineType(types: !3643)
!3643 = !{null, !3644, !407, !3645, !3647, !3647}
!3644 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3633, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3645 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3646, size: 64)
!3646 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !407)
!3647 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3648, size: 64)
!3648 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !324)
!3649 = !DISubprogram(name: "snprint", linkageName: "_ZNK4llvm14format_object3IPKciiE7snprintEPcj", scope: !3633, file: !3634, line: 124, type: !3650, scopeLine: 124, containingType: !3633, virtualIndex: 1, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3650 = !DISubroutineType(types: !3651)
!3651 = !{!324, !3652, !373, !6}
!3652 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3653, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3653 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3633)
!3654 = !{!3655, !3656, !3657}
!3655 = !DITemplateTypeParameter(name: "T1", type: !407)
!3656 = !DITemplateTypeParameter(name: "T2", type: !324)
!3657 = !DITemplateTypeParameter(name: "T3", type: !324)
!3658 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "format_object3<int, int, int>", scope: !342, file: !3634, line: 115, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3659, vtableHolder: !3637, templateParams: !3673, identifier: "_ZTSN4llvm14format_object3IiiiEE")
!3659 = !{!3660, !3661, !3662, !3663, !3664, !3668}
!3660 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3658, baseType: !3637, flags: DIFlagPublic, extraData: i32 0)
!3661 = !DIDerivedType(tag: DW_TAG_member, name: "Val1", scope: !3658, file: !3634, line: 116, baseType: !324, size: 32, offset: 128)
!3662 = !DIDerivedType(tag: DW_TAG_member, name: "Val2", scope: !3658, file: !3634, line: 117, baseType: !324, size: 32, offset: 160)
!3663 = !DIDerivedType(tag: DW_TAG_member, name: "Val3", scope: !3658, file: !3634, line: 118, baseType: !324, size: 32, offset: 192)
!3664 = !DISubprogram(name: "format_object3", scope: !3658, file: !3634, line: 120, type: !3665, scopeLine: 120, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3665 = !DISubroutineType(types: !3666)
!3666 = !{null, !3667, !407, !3647, !3647, !3647}
!3667 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3658, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3668 = !DISubprogram(name: "snprint", linkageName: "_ZNK4llvm14format_object3IiiiE7snprintEPcj", scope: !3658, file: !3634, line: 124, type: !3669, scopeLine: 124, containingType: !3658, virtualIndex: 1, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!3669 = !DISubroutineType(types: !3670)
!3670 = !{!324, !3671, !373, !6}
!3671 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3672, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3672 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3658)
!3673 = !{!3674, !3656, !3657}
!3674 = !DITemplateTypeParameter(name: "T1", type: !324)
!3675 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bit_const_iterator", scope: !353, file: !1464, line: 302, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3676, identifier: "_ZTSSt19_Bit_const_iterator")
!3676 = !{!3677, !3725, !3729, !3732, !3738, !3743, !3747, !3752, !3755, !3756, !3757, !3761, !3762, !3765, !3766}
!3677 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3675, baseType: !3678, extraData: i32 0)
!3678 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bit_iterator_base", scope: !353, file: !1464, line: 138, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3679, identifier: "_ZTSSt18_Bit_iterator_base")
!3679 = !{!3680, !3699, !3702, !3703, !3707, !3710, !3711, !3714, !3720, !3721, !3722, !3723, !3724}
!3680 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3678, baseType: !3681, extraData: i32 0)
!3681 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::random_access_iterator_tag, bool, long, bool *, bool &>", scope: !353, file: !3040, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !3682, identifier: "_ZTSSt8iteratorISt26random_access_iterator_tagblPbRbE")
!3682 = !{!3683, !3516, !3694, !3695, !3697}
!3683 = !DITemplateTypeParameter(name: "_Category", type: !3684)
!3684 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "random_access_iterator_tag", scope: !353, file: !3040, line: 103, size: 8, flags: DIFlagTypePassByValue, elements: !3685, identifier: "_ZTSSt26random_access_iterator_tag")
!3685 = !{!3686}
!3686 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3684, baseType: !3687, extraData: i32 0)
!3687 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "bidirectional_iterator_tag", scope: !353, file: !3040, line: 99, size: 8, flags: DIFlagTypePassByValue, elements: !3688, identifier: "_ZTSSt26bidirectional_iterator_tag")
!3688 = !{!3689}
!3689 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3687, baseType: !3690, extraData: i32 0)
!3690 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "forward_iterator_tag", scope: !353, file: !3040, line: 95, size: 8, flags: DIFlagTypePassByValue, elements: !3691, identifier: "_ZTSSt20forward_iterator_tag")
!3691 = !{!3692}
!3692 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3690, baseType: !3693, extraData: i32 0)
!3693 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "input_iterator_tag", scope: !353, file: !3040, line: 89, size: 8, flags: DIFlagTypePassByValue, elements: !479, identifier: "_ZTSSt18input_iterator_tag")
!3694 = !DITemplateTypeParameter(name: "_Distance", type: !1837)
!3695 = !DITemplateTypeParameter(name: "_Pointer", type: !3696)
!3696 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !308, size: 64)
!3697 = !DITemplateTypeParameter(name: "_Reference", type: !3698)
!3698 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !308, size: 64)
!3699 = !DIDerivedType(tag: DW_TAG_member, name: "_M_p", scope: !3678, file: !1464, line: 141, baseType: !3700, size: 64)
!3700 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3701, size: 64)
!3701 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Bit_type", scope: !353, file: !1464, line: 69, baseType: !417)
!3702 = !DIDerivedType(tag: DW_TAG_member, name: "_M_offset", scope: !3678, file: !1464, line: 142, baseType: !6, size: 32, offset: 64)
!3703 = !DISubprogram(name: "_Bit_iterator_base", scope: !3678, file: !1464, line: 144, type: !3704, scopeLine: 144, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3704 = !DISubroutineType(types: !3705)
!3705 = !{null, !3706, !3700, !6}
!3706 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3678, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3707 = !DISubprogram(name: "_M_bump_up", linkageName: "_ZNSt18_Bit_iterator_base10_M_bump_upEv", scope: !3678, file: !1464, line: 148, type: !3708, scopeLine: 148, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3708 = !DISubroutineType(types: !3709)
!3709 = !{null, !3706}
!3710 = !DISubprogram(name: "_M_bump_down", linkageName: "_ZNSt18_Bit_iterator_base12_M_bump_downEv", scope: !3678, file: !1464, line: 158, type: !3708, scopeLine: 158, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3711 = !DISubprogram(name: "_M_incr", linkageName: "_ZNSt18_Bit_iterator_base7_M_incrEl", scope: !3678, file: !1464, line: 168, type: !3712, scopeLine: 168, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3712 = !DISubroutineType(types: !3713)
!3713 = !{null, !3706, !3065}
!3714 = !DISubprogram(name: "operator==", linkageName: "_ZNKSt18_Bit_iterator_baseeqERKS_", scope: !3678, file: !1464, line: 182, type: !3715, scopeLine: 182, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3715 = !DISubroutineType(types: !3716)
!3716 = !{!308, !3717, !3719}
!3717 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3718, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3718 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3678)
!3719 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3718, size: 64)
!3720 = !DISubprogram(name: "operator<", linkageName: "_ZNKSt18_Bit_iterator_baseltERKS_", scope: !3678, file: !1464, line: 186, type: !3715, scopeLine: 186, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3721 = !DISubprogram(name: "operator!=", linkageName: "_ZNKSt18_Bit_iterator_baseneERKS_", scope: !3678, file: !1464, line: 193, type: !3715, scopeLine: 193, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3722 = !DISubprogram(name: "operator>", linkageName: "_ZNKSt18_Bit_iterator_basegtERKS_", scope: !3678, file: !1464, line: 197, type: !3715, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3723 = !DISubprogram(name: "operator<=", linkageName: "_ZNKSt18_Bit_iterator_baseleERKS_", scope: !3678, file: !1464, line: 201, type: !3715, scopeLine: 201, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3724 = !DISubprogram(name: "operator>=", linkageName: "_ZNKSt18_Bit_iterator_basegeERKS_", scope: !3678, file: !1464, line: 205, type: !3715, scopeLine: 205, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3725 = !DISubprogram(name: "_Bit_const_iterator", scope: !3675, file: !1464, line: 309, type: !3726, scopeLine: 309, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3726 = !DISubroutineType(types: !3727)
!3727 = !{null, !3728}
!3728 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3675, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3729 = !DISubprogram(name: "_Bit_const_iterator", scope: !3675, file: !1464, line: 311, type: !3730, scopeLine: 311, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3730 = !DISubroutineType(types: !3731)
!3731 = !{null, !3728, !3700, !6}
!3732 = !DISubprogram(name: "_Bit_const_iterator", scope: !3675, file: !1464, line: 314, type: !3733, scopeLine: 314, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3733 = !DISubroutineType(types: !3734)
!3734 = !{null, !3728, !3735}
!3735 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3736, size: 64)
!3736 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3737)
!3737 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bit_iterator", scope: !353, file: !1464, line: 216, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt13_Bit_iterator")
!3738 = !DISubprogram(name: "_M_const_cast", linkageName: "_ZNKSt19_Bit_const_iterator13_M_const_castEv", scope: !3675, file: !1464, line: 318, type: !3739, scopeLine: 318, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3739 = !DISubroutineType(types: !3740)
!3740 = !{!3737, !3741}
!3741 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3742, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3742 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3675)
!3743 = !DISubprogram(name: "operator*", linkageName: "_ZNKSt19_Bit_const_iteratordeEv", scope: !3675, file: !1464, line: 322, type: !3744, scopeLine: 322, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3744 = !DISubroutineType(types: !3745)
!3745 = !{!3746, !3741}
!3746 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !3675, file: !1464, line: 305, baseType: !308)
!3747 = !DISubprogram(name: "operator++", linkageName: "_ZNSt19_Bit_const_iteratorppEv", scope: !3675, file: !1464, line: 326, type: !3748, scopeLine: 326, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3748 = !DISubroutineType(types: !3749)
!3749 = !{!3750, !3728}
!3750 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3751, size: 64)
!3751 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !3675, file: !1464, line: 307, baseType: !3675)
!3752 = !DISubprogram(name: "operator++", linkageName: "_ZNSt19_Bit_const_iteratorppEi", scope: !3675, file: !1464, line: 333, type: !3753, scopeLine: 333, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3753 = !DISubroutineType(types: !3754)
!3754 = !{!3751, !3728, !324}
!3755 = !DISubprogram(name: "operator--", linkageName: "_ZNSt19_Bit_const_iteratormmEv", scope: !3675, file: !1464, line: 341, type: !3748, scopeLine: 341, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3756 = !DISubprogram(name: "operator--", linkageName: "_ZNSt19_Bit_const_iteratormmEi", scope: !3675, file: !1464, line: 348, type: !3753, scopeLine: 348, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3757 = !DISubprogram(name: "operator+=", linkageName: "_ZNSt19_Bit_const_iteratorpLEl", scope: !3675, file: !1464, line: 356, type: !3758, scopeLine: 356, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3758 = !DISubroutineType(types: !3759)
!3759 = !{!3750, !3728, !3760}
!3760 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !3681, file: !3040, line: 125, baseType: !1837)
!3761 = !DISubprogram(name: "operator-=", linkageName: "_ZNSt19_Bit_const_iteratormIEl", scope: !3675, file: !1464, line: 363, type: !3758, scopeLine: 363, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3762 = !DISubprogram(name: "operator+", linkageName: "_ZNKSt19_Bit_const_iteratorplEl", scope: !3675, file: !1464, line: 370, type: !3763, scopeLine: 370, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3763 = !DISubroutineType(types: !3764)
!3764 = !{!3751, !3741, !3760}
!3765 = !DISubprogram(name: "operator-", linkageName: "_ZNKSt19_Bit_const_iteratormiEl", scope: !3675, file: !1464, line: 377, type: !3763, scopeLine: 377, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3766 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt19_Bit_const_iteratorixEl", scope: !3675, file: !1464, line: 384, type: !3767, scopeLine: 384, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3767 = !DISubroutineType(types: !3768)
!3768 = !{!3746, !3741, !3760}
!3769 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bit_reference", scope: !353, file: !1464, line: 72, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3770, identifier: "_ZTSSt14_Bit_reference")
!3770 = !{!3771, !3772, !3773, !3777, !3780, !3785, !3789, !3793, !3796, !3797}
!3771 = !DIDerivedType(tag: DW_TAG_member, name: "_M_p", scope: !3769, file: !1464, line: 74, baseType: !3700, size: 64)
!3772 = !DIDerivedType(tag: DW_TAG_member, name: "_M_mask", scope: !3769, file: !1464, line: 75, baseType: !3701, size: 64, offset: 64)
!3773 = !DISubprogram(name: "_Bit_reference", scope: !3769, file: !1464, line: 77, type: !3774, scopeLine: 77, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3774 = !DISubroutineType(types: !3775)
!3775 = !{null, !3776, !3700, !3701}
!3776 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3769, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3777 = !DISubprogram(name: "_Bit_reference", scope: !3769, file: !1464, line: 80, type: !3778, scopeLine: 80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3778 = !DISubroutineType(types: !3779)
!3779 = !{null, !3776}
!3780 = !DISubprogram(name: "operator bool", linkageName: "_ZNKSt14_Bit_referencecvbEv", scope: !3769, file: !1464, line: 82, type: !3781, scopeLine: 82, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3781 = !DISubroutineType(types: !3782)
!3782 = !{!308, !3783}
!3783 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3784, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3784 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3769)
!3785 = !DISubprogram(name: "operator=", linkageName: "_ZNSt14_Bit_referenceaSEb", scope: !3769, file: !1464, line: 86, type: !3786, scopeLine: 86, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3786 = !DISubroutineType(types: !3787)
!3787 = !{!3788, !3776, !308}
!3788 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3769, size: 64)
!3789 = !DISubprogram(name: "operator=", linkageName: "_ZNSt14_Bit_referenceaSERKS_", scope: !3769, file: !1464, line: 96, type: !3790, scopeLine: 96, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3790 = !DISubroutineType(types: !3791)
!3791 = !{!3788, !3776, !3792}
!3792 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3784, size: 64)
!3793 = !DISubprogram(name: "operator==", linkageName: "_ZNKSt14_Bit_referenceeqERKS_", scope: !3769, file: !1464, line: 100, type: !3794, scopeLine: 100, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3794 = !DISubroutineType(types: !3795)
!3795 = !{!308, !3783, !3792}
!3796 = !DISubprogram(name: "operator<", linkageName: "_ZNKSt14_Bit_referenceltERKS_", scope: !3769, file: !1464, line: 104, type: !3794, scopeLine: 104, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3797 = !DISubprogram(name: "flip", linkageName: "_ZNSt14_Bit_reference4flipEv", scope: !3769, file: !1464, line: 108, type: !3778, scopeLine: 108, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3798 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallString<128U>", scope: !342, file: !3519, line: 25, size: 1216, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3799, templateParams: !3910, identifier: "_ZTSN4llvm11SmallStringILj128EEE")
!3799 = !{!3800, !3835, !3839, !3842, !3847, !3850, !3851, !3854, !3855, !3856, !3857, !3861, !3862, !3865, !3866, !3867, !3868, !3869, !3872, !3875, !3876, !3879, !3880, !3881, !3882, !3883, !3884, !3885, !3888, !3889, !3892, !3893, !3896, !3899, !3900, !3903, !3907}
!3800 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3798, baseType: !3801, flags: DIFlagPublic, extraData: i32 0)
!3801 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<char, 128U>", scope: !342, file: !1967, line: 880, size: 1216, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3802, templateParams: !3811, identifier: "_ZTSN4llvm11SmallVectorIcLj128EEE")
!3802 = !{!3803, !3804, !3813, !3817, !3820, !3825, !3828, !3832}
!3803 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3801, baseType: !3185, flags: DIFlagPublic, extraData: i32 0)
!3804 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !3801, file: !1967, line: 882, baseType: !3805, size: 1016, offset: 200)
!3805 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<char, 128U>", scope: !342, file: !1967, line: 865, size: 1016, flags: DIFlagTypePassByValue, elements: !3806, templateParams: !3811, identifier: "_ZTSN4llvm18SmallVectorStorageIcLj128EEE")
!3806 = !{!3807}
!3807 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !3805, file: !1967, line: 866, baseType: !3808, size: 1016)
!3808 = !DICompositeType(tag: DW_TAG_array_type, baseType: !2283, size: 1016, elements: !3809)
!3809 = !{!3810}
!3810 = !DISubrange(count: 127)
!3811 = !{!2371, !3812}
!3812 = !DITemplateValueParameter(name: "N", type: !6, value: i32 128)
!3813 = !DISubprogram(name: "SmallVector", scope: !3801, file: !1967, line: 884, type: !3814, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3814 = !DISubroutineType(types: !3815)
!3815 = !{null, !3816}
!3816 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3801, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3817 = !DISubprogram(name: "SmallVector", scope: !3801, file: !1967, line: 887, type: !3818, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3818 = !DISubroutineType(types: !3819)
!3819 = !{null, !3816, !6, !410}
!3820 = !DISubprogram(name: "SmallVector", scope: !3801, file: !1967, line: 897, type: !3821, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3821 = !DISubroutineType(types: !3822)
!3822 = !{null, !3816, !3823}
!3823 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3824, size: 64)
!3824 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3801)
!3825 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIcLj128EEaSERKS1_", scope: !3801, file: !1967, line: 902, type: !3826, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3826 = !DISubroutineType(types: !3827)
!3827 = !{!3823, !3816, !3823}
!3828 = !DISubprogram(name: "SmallVector", scope: !3801, file: !1967, line: 908, type: !3829, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3829 = !DISubroutineType(types: !3830)
!3830 = !{null, !3816, !3831}
!3831 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3801, size: 64)
!3832 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIcLj128EEaSEOS1_", scope: !3801, file: !1967, line: 913, type: !3833, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3833 = !DISubroutineType(types: !3834)
!3834 = !{!3823, !3816, !3831}
!3835 = !DISubprogram(name: "SmallString", scope: !3798, file: !3519, line: 28, type: !3836, scopeLine: 28, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3836 = !DISubroutineType(types: !3837)
!3837 = !{null, !3838}
!3838 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3798, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3839 = !DISubprogram(name: "SmallString", scope: !3798, file: !3519, line: 31, type: !3840, scopeLine: 31, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3840 = !DISubroutineType(types: !3841)
!3841 = !{null, !3838, !1578}
!3842 = !DISubprogram(name: "SmallString", scope: !3798, file: !3519, line: 38, type: !3843, scopeLine: 38, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3843 = !DISubroutineType(types: !3844)
!3844 = !{null, !3838, !3845}
!3845 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3846, size: 64)
!3846 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3798)
!3847 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj128EE6assignEmc", scope: !3798, file: !3519, line: 48, type: !3848, scopeLine: 48, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3848 = !DISubroutineType(types: !3849)
!3849 = !{null, !3838, !1583, !374}
!3850 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj128EE6assignENS_9StringRefE", scope: !3798, file: !3519, line: 60, type: !3840, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3851 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm11SmallStringILj128EE6assignERKNS_15SmallVectorImplIcEE", scope: !3798, file: !3519, line: 66, type: !3852, scopeLine: 66, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3852 = !DISubroutineType(types: !3853)
!3853 = !{null, !3838, !3210}
!3854 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj128EE6appendEmc", scope: !3798, file: !3519, line: 81, type: !3848, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3855 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj128EE6appendENS_9StringRefE", scope: !3798, file: !3519, line: 87, type: !3840, scopeLine: 87, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3856 = !DISubprogram(name: "append", linkageName: "_ZN4llvm11SmallStringILj128EE6appendERKNS_15SmallVectorImplIcEE", scope: !3798, file: !3519, line: 92, type: !3852, scopeLine: 92, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3857 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm11SmallStringILj128EE6equalsENS_9StringRefE", scope: !3798, file: !3519, line: 102, type: !3858, scopeLine: 102, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3858 = !DISubroutineType(types: !3859)
!3859 = !{!308, !3860, !1578}
!3860 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3846, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3861 = !DISubprogram(name: "equals_lower", linkageName: "_ZNK4llvm11SmallStringILj128EE12equals_lowerENS_9StringRefE", scope: !3798, file: !3519, line: 107, type: !3858, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3862 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm11SmallStringILj128EE7compareENS_9StringRefE", scope: !3798, file: !3519, line: 113, type: !3863, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3863 = !DISubroutineType(types: !3864)
!3864 = !{!324, !3860, !1578}
!3865 = !DISubprogram(name: "compare_lower", linkageName: "_ZNK4llvm11SmallStringILj128EE13compare_lowerENS_9StringRefE", scope: !3798, file: !3519, line: 118, type: !3863, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3866 = !DISubprogram(name: "compare_numeric", linkageName: "_ZNK4llvm11SmallStringILj128EE15compare_numericENS_9StringRefE", scope: !3798, file: !3519, line: 124, type: !3863, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3867 = !DISubprogram(name: "startswith", linkageName: "_ZNK4llvm11SmallStringILj128EE10startswithENS_9StringRefE", scope: !3798, file: !3519, line: 133, type: !3858, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3868 = !DISubprogram(name: "endswith", linkageName: "_ZNK4llvm11SmallStringILj128EE8endswithENS_9StringRefE", scope: !3798, file: !3519, line: 138, type: !3858, scopeLine: 138, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3869 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm11SmallStringILj128EE4findEcm", scope: !3798, file: !3519, line: 150, type: !3870, scopeLine: 150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3870 = !DISubroutineType(types: !3871)
!3871 = !{!1583, !3860, !374, !1583}
!3872 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm11SmallStringILj128EE4findENS_9StringRefEm", scope: !3798, file: !3519, line: 158, type: !3873, scopeLine: 158, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3873 = !DISubroutineType(types: !3874)
!3874 = !{!1583, !3860, !1578, !1583}
!3875 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm11SmallStringILj128EE5rfindEcm", scope: !3798, file: !3519, line: 166, type: !3870, scopeLine: 166, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3876 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm11SmallStringILj128EE5rfindENS_9StringRefE", scope: !3798, file: !3519, line: 174, type: !3877, scopeLine: 174, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3877 = !DISubroutineType(types: !3878)
!3878 = !{!1583, !3860, !1578}
!3879 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm11SmallStringILj128EE13find_first_ofEcm", scope: !3798, file: !3519, line: 180, type: !3870, scopeLine: 180, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3880 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm11SmallStringILj128EE13find_first_ofENS_9StringRefEm", scope: !3798, file: !3519, line: 188, type: !3873, scopeLine: 188, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3881 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm11SmallStringILj128EE17find_first_not_ofEcm", scope: !3798, file: !3519, line: 194, type: !3870, scopeLine: 194, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3882 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm11SmallStringILj128EE17find_first_not_ofENS_9StringRefEm", scope: !3798, file: !3519, line: 202, type: !3873, scopeLine: 202, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3883 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm11SmallStringILj128EE12find_last_ofEcm", scope: !3798, file: !3519, line: 208, type: !3870, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3884 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm11SmallStringILj128EE12find_last_ofENS_9StringRefEm", scope: !3798, file: !3519, line: 216, type: !3873, scopeLine: 216, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3885 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm11SmallStringILj128EE5countEc", scope: !3798, file: !3519, line: 226, type: !3886, scopeLine: 226, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3886 = !DISubroutineType(types: !3887)
!3887 = !{!1583, !3860, !374}
!3888 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm11SmallStringILj128EE5countENS_9StringRefE", scope: !3798, file: !3519, line: 232, type: !3877, scopeLine: 232, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3889 = !DISubprogram(name: "substr", linkageName: "_ZNK4llvm11SmallStringILj128EE6substrEmm", scope: !3798, file: !3519, line: 249, type: !3890, scopeLine: 249, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3890 = !DISubroutineType(types: !3891)
!3891 = !{!1578, !3860, !1583, !1583}
!3892 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm11SmallStringILj128EE5sliceEmm", scope: !3798, file: !3519, line: 263, type: !3890, scopeLine: 263, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3893 = !DISubprogram(name: "str", linkageName: "_ZNK4llvm11SmallStringILj128EE3strEv", scope: !3798, file: !3519, line: 270, type: !3894, scopeLine: 270, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3894 = !DISubroutineType(types: !3895)
!3895 = !{!1578, !3860}
!3896 = !DISubprogram(name: "c_str", linkageName: "_ZN4llvm11SmallStringILj128EE5c_strEv", scope: !3798, file: !3519, line: 273, type: !3897, scopeLine: 273, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3897 = !DISubroutineType(types: !3898)
!3898 = !{!407, !3838}
!3899 = !DISubprogram(name: "operator StringRef", linkageName: "_ZNK4llvm11SmallStringILj128EEcvNS_9StringRefEEv", scope: !3798, file: !3519, line: 280, type: !3894, scopeLine: 280, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3900 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallStringILj128EEaSENS_9StringRefE", scope: !3798, file: !3519, line: 283, type: !3901, scopeLine: 283, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3901 = !DISubroutineType(types: !3902)
!3902 = !{!3845, !3838, !1578}
!3903 = !DISubprogram(name: "operator+=", linkageName: "_ZN4llvm11SmallStringILj128EEpLENS_9StringRefE", scope: !3798, file: !3519, line: 288, type: !3904, scopeLine: 288, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3904 = !DISubroutineType(types: !3905)
!3905 = !{!3906, !3838, !1578}
!3906 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3798, size: 64)
!3907 = !DISubprogram(name: "operator+=", linkageName: "_ZN4llvm11SmallStringILj128EEpLEc", scope: !3798, file: !3519, line: 292, type: !3908, scopeLine: 292, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3908 = !DISubroutineType(types: !3909)
!3909 = !{!3906, !3838, !374}
!3910 = !{!3911}
!3911 = !DITemplateValueParameter(name: "InternalLen", type: !6, value: i32 128)
!3912 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapIterator<const clang::IdentifierInfo *, clang::MacroDirective *, llvm::DenseMapInfo<const clang::IdentifierInfo *>, true>", scope: !342, file: !2715, line: 987, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !3913, templateParams: !3964, identifier: "_ZTSN4llvm16DenseMapIteratorIPKN5clang14IdentifierInfoEPNS1_14MacroDirectiveENS_12DenseMapInfoIS4_EELb1EEE")
!3913 = !{!3914, !3925, !3926, !3930, !3933, !3939, !3946, !3949, !3955, !3956, !3960, !3963}
!3914 = !DIDerivedType(tag: DW_TAG_member, name: "Ptr", scope: !3912, file: !2715, line: 999, baseType: !3915, size: 64)
!3915 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !3912, file: !2715, line: 995, baseType: !3916)
!3916 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3917, size: 64)
!3917 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !3912, file: !2715, line: 994, baseType: !3918)
!3918 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !3920, file: !3919, line: 233, baseType: !2750)
!3919 = !DIFile(filename: "llvm34/include/llvm/Support/type_traits.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "3b111e0adbb374a4c7fc591de906379a")
!3920 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<const clang::IdentifierInfo *, clang::MacroDirective *>, std::pair<const clang::IdentifierInfo *, clang::MacroDirective *> >", scope: !342, file: !3919, line: 233, size: 8, flags: DIFlagTypePassByValue, elements: !479, templateParams: !3921, identifier: "_ZTSN4llvm11conditionalILb1EKSt4pairIPKN5clang14IdentifierInfoEPNS2_14MacroDirectiveEES8_EE")
!3921 = !{!3922, !3923, !3924}
!3922 = !DITemplateValueParameter(type: !308, value: i8 1)
!3923 = !DITemplateTypeParameter(name: "T", type: !2750)
!3924 = !DITemplateTypeParameter(name: "F", type: !2721)
!3925 = !DIDerivedType(tag: DW_TAG_member, name: "End", scope: !3912, file: !2715, line: 999, baseType: !3915, size: 64, offset: 64)
!3926 = !DISubprogram(name: "DenseMapIterator", scope: !3912, file: !2715, line: 1001, type: !3927, scopeLine: 1001, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3927 = !DISubroutineType(types: !3928)
!3928 = !{null, !3929}
!3929 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3912, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3930 = !DISubprogram(name: "DenseMapIterator", scope: !3912, file: !2715, line: 1003, type: !3931, scopeLine: 1003, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3931 = !DISubroutineType(types: !3932)
!3932 = !{null, !3929, !3915, !3915, !308}
!3933 = !DISubprogram(name: "DenseMapIterator", scope: !3912, file: !2715, line: 1011, type: !3934, scopeLine: 1011, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3934 = !DISubroutineType(types: !3935)
!3935 = !{null, !3929, !3936}
!3936 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3937, size: 64)
!3937 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3938)
!3938 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapIterator<const clang::IdentifierInfo *, clang::MacroDirective *, llvm::DenseMapInfo<const clang::IdentifierInfo *>, false>", scope: !342, file: !2715, line: 987, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm16DenseMapIteratorIPKN5clang14IdentifierInfoEPNS1_14MacroDirectiveENS_12DenseMapInfoIS4_EELb0EEE")
!3939 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm16DenseMapIteratorIPKN5clang14IdentifierInfoEPNS1_14MacroDirectiveENS_12DenseMapInfoIS4_EELb1EEdeEv", scope: !3912, file: !2715, line: 1015, type: !3940, scopeLine: 1015, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3940 = !DISubroutineType(types: !3941)
!3941 = !{!3942, !3944}
!3942 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !3912, file: !2715, line: 996, baseType: !3943)
!3943 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3917, size: 64)
!3944 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3945, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3945 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3912)
!3946 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm16DenseMapIteratorIPKN5clang14IdentifierInfoEPNS1_14MacroDirectiveENS_12DenseMapInfoIS4_EELb1EEptEv", scope: !3912, file: !2715, line: 1018, type: !3947, scopeLine: 1018, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3947 = !DISubroutineType(types: !3948)
!3948 = !{!3915, !3944}
!3949 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm16DenseMapIteratorIPKN5clang14IdentifierInfoEPNS1_14MacroDirectiveENS_12DenseMapInfoIS4_EELb1EEeqERKS9_", scope: !3912, file: !2715, line: 1022, type: !3950, scopeLine: 1022, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3950 = !DISubroutineType(types: !3951)
!3951 = !{!308, !3944, !3952}
!3952 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3953, size: 64)
!3953 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3954)
!3954 = !DIDerivedType(tag: DW_TAG_typedef, name: "ConstIterator", scope: !3912, file: !2715, line: 990, baseType: !3912)
!3955 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm16DenseMapIteratorIPKN5clang14IdentifierInfoEPNS1_14MacroDirectiveENS_12DenseMapInfoIS4_EELb1EEneERKS9_", scope: !3912, file: !2715, line: 1025, type: !3950, scopeLine: 1025, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3956 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIPKN5clang14IdentifierInfoEPNS1_14MacroDirectiveENS_12DenseMapInfoIS4_EELb1EEppEv", scope: !3912, file: !2715, line: 1029, type: !3957, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3957 = !DISubroutineType(types: !3958)
!3958 = !{!3959, !3929}
!3959 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !3912, size: 64)
!3960 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIPKN5clang14IdentifierInfoEPNS1_14MacroDirectiveENS_12DenseMapInfoIS4_EELb1EEppEi", scope: !3912, file: !2715, line: 1034, type: !3961, scopeLine: 1034, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3961 = !DISubroutineType(types: !3962)
!3962 = !{!3912, !3929, !324}
!3963 = !DISubprogram(name: "AdvancePastEmptyBuckets", linkageName: "_ZN4llvm16DenseMapIteratorIPKN5clang14IdentifierInfoEPNS1_14MacroDirectiveENS_12DenseMapInfoIS4_EELb1EE23AdvancePastEmptyBucketsEv", scope: !3912, file: !2715, line: 1039, type: !3927, scopeLine: 1039, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3964 = !{!3965, !3966, !3967, !3981}
!3965 = !DITemplateTypeParameter(name: "KeyT", type: !1817)
!3966 = !DITemplateTypeParameter(name: "ValueT", type: !1834)
!3967 = !DITemplateTypeParameter(name: "KeyInfoT", type: !3968)
!3968 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "DenseMapInfo<const clang::IdentifierInfo *>", scope: !342, file: !3969, line: 32, size: 8, flags: DIFlagTypePassByValue, elements: !3970, templateParams: !1822, identifier: "_ZTSN4llvm12DenseMapInfoIPKN5clang14IdentifierInfoEEE")
!3969 = !DIFile(filename: "llvm34/include/llvm/ADT/DenseMapInfo.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "1e7505cc8cacf4830514e4c206b176d8")
!3970 = !{!3971, !3974, !3975, !3978}
!3971 = !DISubprogram(name: "getEmptyKey", linkageName: "_ZN4llvm12DenseMapInfoIPKN5clang14IdentifierInfoEE11getEmptyKeyEv", scope: !3968, file: !3969, line: 33, type: !3972, scopeLine: 33, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3972 = !DISubroutineType(types: !3973)
!3973 = !{!1817}
!3974 = !DISubprogram(name: "getTombstoneKey", linkageName: "_ZN4llvm12DenseMapInfoIPKN5clang14IdentifierInfoEE15getTombstoneKeyEv", scope: !3968, file: !3969, line: 38, type: !3972, scopeLine: 38, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3975 = !DISubprogram(name: "getHashValue", linkageName: "_ZN4llvm12DenseMapInfoIPKN5clang14IdentifierInfoEE12getHashValueES4_", scope: !3968, file: !3969, line: 43, type: !3976, scopeLine: 43, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3976 = !DISubroutineType(types: !3977)
!3977 = !{!6, !1817}
!3978 = !DISubprogram(name: "isEqual", linkageName: "_ZN4llvm12DenseMapInfoIPKN5clang14IdentifierInfoEE7isEqualES4_S4_", scope: !3968, file: !3969, line: 47, type: !3979, scopeLine: 47, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!3979 = !DISubroutineType(types: !3980)
!3980 = !{!308, !1817, !1817}
!3981 = !DITemplateValueParameter(name: "IsConst", type: !308, value: i8 1)
!3982 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<clang::Token, 64U>", scope: !342, file: !1967, line: 880, size: 12480, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !3983, templateParams: !3992, identifier: "_ZTSN4llvm11SmallVectorIN5clang5TokenELj64EEE")
!3983 = !{!3984, !3985, !3994, !3998, !4001, !4006, !4009, !4013}
!3984 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !3982, baseType: !2194, flags: DIFlagPublic, extraData: i32 0)
!3985 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !3982, file: !1967, line: 882, baseType: !3986, size: 12096, offset: 384)
!3986 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<clang::Token, 64U>", scope: !342, file: !1967, line: 865, size: 12096, flags: DIFlagTypePassByValue, elements: !3987, templateParams: !3992, identifier: "_ZTSN4llvm18SmallVectorStorageIN5clang5TokenELj64EEE")
!3987 = !{!3988}
!3988 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !3986, file: !1967, line: 866, baseType: !3989, size: 12096)
!3989 = !DICompositeType(tag: DW_TAG_array_type, baseType: !1993, size: 12096, elements: !3990)
!3990 = !{!3991}
!3991 = !DISubrange(count: 63)
!3992 = !{!2092, !3993}
!3993 = !DITemplateValueParameter(name: "N", type: !6, value: i32 64)
!3994 = !DISubprogram(name: "SmallVector", scope: !3982, file: !1967, line: 884, type: !3995, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3995 = !DISubroutineType(types: !3996)
!3996 = !{null, !3997}
!3997 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3982, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!3998 = !DISubprogram(name: "SmallVector", scope: !3982, file: !1967, line: 887, type: !3999, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3999 = !DISubroutineType(types: !4000)
!4000 = !{null, !3997, !6, !2082}
!4001 = !DISubprogram(name: "SmallVector", scope: !3982, file: !1967, line: 897, type: !4002, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4002 = !DISubroutineType(types: !4003)
!4003 = !{null, !3997, !4004}
!4004 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4005, size: 64)
!4005 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3982)
!4006 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIN5clang5TokenELj64EEaSERKS3_", scope: !3982, file: !1967, line: 902, type: !4007, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4007 = !DISubroutineType(types: !4008)
!4008 = !{!4004, !3997, !4004}
!4009 = !DISubprogram(name: "SmallVector", scope: !3982, file: !1967, line: 908, type: !4010, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4010 = !DISubroutineType(types: !4011)
!4011 = !{null, !3997, !4012}
!4012 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !3982, size: 64)
!4013 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIN5clang5TokenELj64EEaSEOS3_", scope: !3982, file: !1967, line: 913, type: !4014, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4014 = !DISubroutineType(types: !4015)
!4015 = !{!4004, !3997, !4012}
!4016 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<clang::Token, 4U>", scope: !342, file: !1967, line: 880, size: 960, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4017, templateParams: !4026, identifier: "_ZTSN4llvm11SmallVectorIN5clang5TokenELj4EEE")
!4017 = !{!4018, !4019, !4028, !4032, !4035, !4040, !4043, !4047}
!4018 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4016, baseType: !2194, flags: DIFlagPublic, extraData: i32 0)
!4019 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !4016, file: !1967, line: 882, baseType: !4020, size: 576, offset: 384)
!4020 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<clang::Token, 4U>", scope: !342, file: !1967, line: 865, size: 576, flags: DIFlagTypePassByValue, elements: !4021, templateParams: !4026, identifier: "_ZTSN4llvm18SmallVectorStorageIN5clang5TokenELj4EEE")
!4021 = !{!4022}
!4022 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !4020, file: !1967, line: 866, baseType: !4023, size: 576)
!4023 = !DICompositeType(tag: DW_TAG_array_type, baseType: !1993, size: 576, elements: !4024)
!4024 = !{!4025}
!4025 = !DISubrange(count: 3)
!4026 = !{!2092, !4027}
!4027 = !DITemplateValueParameter(name: "N", type: !6, value: i32 4)
!4028 = !DISubprogram(name: "SmallVector", scope: !4016, file: !1967, line: 884, type: !4029, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4029 = !DISubroutineType(types: !4030)
!4030 = !{null, !4031}
!4031 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4016, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4032 = !DISubprogram(name: "SmallVector", scope: !4016, file: !1967, line: 887, type: !4033, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4033 = !DISubroutineType(types: !4034)
!4034 = !{null, !4031, !6, !2082}
!4035 = !DISubprogram(name: "SmallVector", scope: !4016, file: !1967, line: 897, type: !4036, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4036 = !DISubroutineType(types: !4037)
!4037 = !{null, !4031, !4038}
!4038 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4039, size: 64)
!4039 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4016)
!4040 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIN5clang5TokenELj4EEaSERKS3_", scope: !4016, file: !1967, line: 902, type: !4041, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4041 = !DISubroutineType(types: !4042)
!4042 = !{!4038, !4031, !4038}
!4043 = !DISubprogram(name: "SmallVector", scope: !4016, file: !1967, line: 908, type: !4044, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4044 = !DISubroutineType(types: !4045)
!4045 = !{null, !4031, !4046}
!4046 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !4016, size: 64)
!4047 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIN5clang5TokenELj4EEaSEOS3_", scope: !4016, file: !1967, line: 913, type: !4048, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4048 = !DISubroutineType(types: !4049)
!4049 = !{!4038, !4031, !4046}
!4050 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<clang::SourceRange, 4U>", scope: !342, file: !1967, line: 880, size: 448, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4051, templateParams: !4142, identifier: "_ZTSN4llvm11SmallVectorIN5clang11SourceRangeELj4EEE")
!4051 = !{!4052, !4137, !4143, !4147, !4150, !4155, !4158, !4162}
!4052 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4050, baseType: !4053, flags: DIFlagPublic, extraData: i32 0)
!4053 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<clang::SourceRange>", scope: !342, file: !1967, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4054, templateParams: !4136, identifier: "_ZTSN4llvm15SmallVectorImplIN5clang11SourceRangeEEE")
!4054 = !{!4055, !4074, !4080, !4083, !4086, !4087, !4088, !4091, !4092, !4095, !4099, !4104, !4105, !4109, !4112, !4116, !4119, !4122, !4125, !4129, !4133, !4134, !4135}
!4055 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4053, baseType: !4056, flags: DIFlagPublic, extraData: i32 0)
!4056 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<clang::SourceRange, true>", scope: !342, file: !1967, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4057, templateParams: !4073, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseIN5clang11SourceRangeELb1EEE")
!4057 = !{!4058, !4059, !4063, !4066, !4067, !4070}
!4058 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4056, baseType: !2813, flags: DIFlagPublic, extraData: i32 0)
!4059 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !4056, file: !1967, line: 298, type: !4060, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4060 = !DISubroutineType(types: !4061)
!4061 = !{null, !4062, !1583}
!4062 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4056, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4063 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIN5clang11SourceRangeELb1EE13destroy_rangeEPS2_S4_", scope: !4056, file: !1967, line: 301, type: !4064, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4064 = !DISubroutineType(types: !4065)
!4065 = !{null, !2849, !2849}
!4066 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIN5clang11SourceRangeELb1EE4growEm", scope: !4056, file: !1967, line: 346, type: !4060, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4067 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIN5clang11SourceRangeELb1EE9push_backERKS2_", scope: !4056, file: !1967, line: 350, type: !4068, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4068 = !DISubroutineType(types: !4069)
!4069 = !{null, !4062, !1334}
!4070 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIN5clang11SourceRangeELb1EE8pop_backEv", scope: !4056, file: !1967, line: 361, type: !4071, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4071 = !DISubroutineType(types: !4072)
!4072 = !{null, !4062}
!4073 = !{!2907, !2215}
!4074 = !DISubprogram(name: "SmallVectorImpl", scope: !4053, file: !1967, line: 374, type: !4075, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!4075 = !DISubroutineType(types: !4076)
!4076 = !{null, !4077, !4078}
!4077 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4053, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4078 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4079, size: 64)
!4079 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4053)
!4080 = !DISubprogram(name: "SmallVectorImpl", scope: !4053, file: !1967, line: 381, type: !4081, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4081 = !DISubroutineType(types: !4082)
!4082 = !{null, !4077, !6}
!4083 = !DISubprogram(name: "~SmallVectorImpl", scope: !4053, file: !1967, line: 386, type: !4084, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4084 = !DISubroutineType(types: !4085)
!4085 = !{null, !4077}
!4086 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEE5clearEv", scope: !4053, file: !1967, line: 396, type: !4084, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4087 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEE6resizeEj", scope: !4053, file: !1967, line: 401, type: !4081, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4088 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEE6resizeEjRKS2_", scope: !4053, file: !1967, line: 413, type: !4089, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4089 = !DISubroutineType(types: !4090)
!4090 = !{null, !4077, !6, !1334}
!4091 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEE7reserveEj", scope: !4053, file: !1967, line: 425, type: !4081, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4092 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEE12pop_back_valEv", scope: !4053, file: !1967, line: 430, type: !4093, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4093 = !DISubroutineType(types: !4094)
!4094 = !{!1305, !4077}
!4095 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEE4swapERS3_", scope: !4053, file: !1967, line: 440, type: !4096, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4096 = !DISubroutineType(types: !4097)
!4097 = !{null, !4077, !4098}
!4098 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4053, size: 64)
!4099 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEE6appendEmRKS2_", scope: !4053, file: !1967, line: 460, type: !4100, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4100 = !DISubroutineType(types: !4101)
!4101 = !{null, !4077, !4102, !1334}
!4102 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !4053, file: !1967, line: 377, baseType: !4103)
!4103 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2813, file: !1967, line: 97, baseType: !1583)
!4104 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEE6assignEjRKS2_", scope: !4053, file: !1967, line: 470, type: !4089, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4105 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEE5eraseEPS2_", scope: !4053, file: !1967, line: 478, type: !4106, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4106 = !DISubroutineType(types: !4107)
!4107 = !{!4108, !4077, !4108}
!4108 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !4053, file: !1967, line: 376, baseType: !2812)
!4109 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEE5eraseEPS2_S4_", scope: !4053, file: !1967, line: 490, type: !4110, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4110 = !DISubroutineType(types: !4111)
!4111 = !{!4108, !4077, !4108, !4108}
!4112 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEE6insertEPS2_OS2_", scope: !4053, file: !1967, line: 505, type: !4113, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4113 = !DISubroutineType(types: !4114)
!4114 = !{!4108, !4077, !4108, !4115}
!4115 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1305, size: 64)
!4116 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEE6insertEPS2_RKS2_", scope: !4053, file: !1967, line: 537, type: !4117, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4117 = !DISubroutineType(types: !4118)
!4118 = !{!4108, !4077, !4108, !1334}
!4119 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEE6insertEPS2_mRKS2_", scope: !4053, file: !1967, line: 568, type: !4120, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4120 = !DISubroutineType(types: !4121)
!4121 = !{!4108, !4077, !4108, !4102, !1334}
!4122 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEEaSERKS3_", scope: !4053, file: !1967, line: 674, type: !4123, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4123 = !DISubroutineType(types: !4124)
!4124 = !{!4098, !4077, !4078}
!4125 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEEaSEOS3_", scope: !4053, file: !1967, line: 677, type: !4126, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4126 = !DISubroutineType(types: !4127)
!4127 = !{!4098, !4077, !4128}
!4128 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !4053, size: 64)
!4129 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplIN5clang11SourceRangeEEeqERKS3_", scope: !4053, file: !1967, line: 680, type: !4130, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4130 = !DISubroutineType(types: !4131)
!4131 = !{!308, !4132, !4078}
!4132 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4079, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4133 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplIN5clang11SourceRangeEEneERKS3_", scope: !4053, file: !1967, line: 684, type: !4130, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4134 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplIN5clang11SourceRangeEEltERKS3_", scope: !4053, file: !1967, line: 688, type: !4130, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4135 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplIN5clang11SourceRangeEE8set_sizeEj", scope: !4053, file: !1967, line: 702, type: !4081, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4136 = !{!2907}
!4137 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !4050, file: !1967, line: 882, baseType: !4138, size: 192, offset: 256)
!4138 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<clang::SourceRange, 4U>", scope: !342, file: !1967, line: 865, size: 192, flags: DIFlagTypePassByValue, elements: !4139, templateParams: !4142, identifier: "_ZTSN4llvm18SmallVectorStorageIN5clang11SourceRangeELj4EEE")
!4139 = !{!4140}
!4140 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !4138, file: !1967, line: 866, baseType: !4141, size: 192)
!4141 = !DICompositeType(tag: DW_TAG_array_type, baseType: !2817, size: 192, elements: !4024)
!4142 = !{!2907, !4027}
!4143 = !DISubprogram(name: "SmallVector", scope: !4050, file: !1967, line: 884, type: !4144, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4144 = !DISubroutineType(types: !4145)
!4145 = !{null, !4146}
!4146 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4050, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4147 = !DISubprogram(name: "SmallVector", scope: !4050, file: !1967, line: 887, type: !4148, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4148 = !DISubroutineType(types: !4149)
!4149 = !{null, !4146, !6, !1334}
!4150 = !DISubprogram(name: "SmallVector", scope: !4050, file: !1967, line: 897, type: !4151, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4151 = !DISubroutineType(types: !4152)
!4152 = !{null, !4146, !4153}
!4153 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4154, size: 64)
!4154 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4050)
!4155 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIN5clang11SourceRangeELj4EEaSERKS3_", scope: !4050, file: !1967, line: 902, type: !4156, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4156 = !DISubroutineType(types: !4157)
!4157 = !{!4153, !4146, !4153}
!4158 = !DISubprogram(name: "SmallVector", scope: !4050, file: !1967, line: 908, type: !4159, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4159 = !DISubroutineType(types: !4160)
!4160 = !{null, !4146, !4161}
!4161 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !4050, size: 64)
!4162 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIN5clang11SourceRangeELj4EEaSEOS3_", scope: !4050, file: !1967, line: 913, type: !4163, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4163 = !DISubroutineType(types: !4164)
!4164 = !{!4153, !4146, !4161}
!4165 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "tier<clang::TokenLexer *, unsigned long>", scope: !342, file: !4166, line: 200, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4167, templateParams: !4182, identifier: "_ZTSN4llvm4tierIPN5clang10TokenLexerEmEE")
!4166 = !DIFile(filename: "llvm34/include/llvm/ADT/STLExtras.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "5c8fce0bbf85d98f65c147b890304660")
!4167 = !{!4168, !4171, !4174, !4178}
!4168 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !4165, file: !4166, line: 204, baseType: !4169, size: 64)
!4169 = !DIDerivedType(tag: DW_TAG_typedef, name: "first_type", scope: !4165, file: !4166, line: 201, baseType: !4170)
!4170 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2945, size: 64)
!4171 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !4165, file: !4166, line: 205, baseType: !4172, size: 64, offset: 64)
!4172 = !DIDerivedType(tag: DW_TAG_typedef, name: "second_type", scope: !4165, file: !4166, line: 202, baseType: !4173)
!4173 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !417, size: 64)
!4174 = !DISubprogram(name: "tier", scope: !4165, file: !4166, line: 207, type: !4175, scopeLine: 207, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4175 = !DISubroutineType(types: !4176)
!4176 = !{null, !4177, !4169, !4172}
!4177 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4165, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4178 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm4tierIPN5clang10TokenLexerEmEaSERKSt4pairIS3_mE", scope: !4165, file: !4166, line: 208, type: !4179, scopeLine: 208, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4179 = !DISubroutineType(types: !4180)
!4180 = !{!4181, !4177, !2955}
!4181 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4165, size: 64)
!4182 = !{!4183, !4184}
!4183 = !DITemplateTypeParameter(name: "T1", type: !2945)
!4184 = !DITemplateTypeParameter(name: "T2", type: !417)
!4185 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVector<unsigned int, 10U>", scope: !342, file: !1967, line: 880, size: 512, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4186, templateParams: !4279, identifier: "_ZTSN4llvm11SmallVectorIjLj10EEE")
!4186 = !{!4187, !4272, !4281, !4285, !4288, !4293, !4296, !4300}
!4187 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4185, baseType: !4188, flags: DIFlagPublic, extraData: i32 0)
!4188 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<unsigned int>", scope: !342, file: !1967, line: 371, size: 256, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !4189, templateParams: !4271, identifier: "_ZTSN4llvm15SmallVectorImplIjEE")
!4189 = !{!4190, !4209, !4215, !4218, !4221, !4222, !4223, !4226, !4227, !4230, !4234, !4239, !4240, !4244, !4247, !4251, !4254, !4257, !4260, !4264, !4268, !4269, !4270}
!4190 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4188, baseType: !4191, flags: DIFlagPublic, extraData: i32 0)
!4191 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateBase<unsigned int, true>", scope: !342, file: !1967, line: 296, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !4192, templateParams: !4208, identifier: "_ZTSN4llvm23SmallVectorTemplateBaseIjLb1EEE")
!4192 = !{!4193, !4194, !4198, !4201, !4202, !4205}
!4193 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !4191, baseType: !2619, flags: DIFlagPublic, extraData: i32 0)
!4194 = !DISubprogram(name: "SmallVectorTemplateBase", scope: !4191, file: !1967, line: 298, type: !4195, scopeLine: 298, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4195 = !DISubroutineType(types: !4196)
!4196 = !{null, !4197, !1583}
!4197 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4191, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4198 = !DISubprogram(name: "destroy_range", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIjLb1EE13destroy_rangeEPjS2_", scope: !4191, file: !1967, line: 301, type: !4199, scopeLine: 301, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!4199 = !DISubroutineType(types: !4200)
!4200 = !{null, !2647, !2647}
!4201 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIjLb1EE4growEm", scope: !4191, file: !1967, line: 346, type: !4195, scopeLine: 346, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4202 = !DISubprogram(name: "push_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIjLb1EE9push_backERKj", scope: !4191, file: !1967, line: 350, type: !4203, scopeLine: 350, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4203 = !DISubroutineType(types: !4204)
!4204 = !{null, !4197, !2697}
!4205 = !DISubprogram(name: "pop_back", linkageName: "_ZN4llvm23SmallVectorTemplateBaseIjLb1EE8pop_backEv", scope: !4191, file: !1967, line: 361, type: !4206, scopeLine: 361, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4206 = !DISubroutineType(types: !4207)
!4207 = !{null, !4197}
!4208 = !{!2707, !2215}
!4209 = !DISubprogram(name: "SmallVectorImpl", scope: !4188, file: !1967, line: 374, type: !4210, scopeLine: 374, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!4210 = !DISubroutineType(types: !4211)
!4211 = !{null, !4212, !4213}
!4212 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4188, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4213 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4214, size: 64)
!4214 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4188)
!4215 = !DISubprogram(name: "SmallVectorImpl", scope: !4188, file: !1967, line: 381, type: !4216, scopeLine: 381, flags: DIFlagProtected | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4216 = !DISubroutineType(types: !4217)
!4217 = !{null, !4212, !6}
!4218 = !DISubprogram(name: "~SmallVectorImpl", scope: !4188, file: !1967, line: 386, type: !4219, scopeLine: 386, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4219 = !DISubroutineType(types: !4220)
!4220 = !{null, !4212}
!4221 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm15SmallVectorImplIjE5clearEv", scope: !4188, file: !1967, line: 396, type: !4219, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4222 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIjE6resizeEj", scope: !4188, file: !1967, line: 401, type: !4216, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4223 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm15SmallVectorImplIjE6resizeEjRKj", scope: !4188, file: !1967, line: 413, type: !4224, scopeLine: 413, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4224 = !DISubroutineType(types: !4225)
!4225 = !{null, !4212, !6, !2697}
!4226 = !DISubprogram(name: "reserve", linkageName: "_ZN4llvm15SmallVectorImplIjE7reserveEj", scope: !4188, file: !1967, line: 425, type: !4216, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4227 = !DISubprogram(name: "pop_back_val", linkageName: "_ZN4llvm15SmallVectorImplIjE12pop_back_valEv", scope: !4188, file: !1967, line: 430, type: !4228, scopeLine: 430, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4228 = !DISubroutineType(types: !4229)
!4229 = !{!6, !4212}
!4230 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm15SmallVectorImplIjE4swapERS1_", scope: !4188, file: !1967, line: 440, type: !4231, scopeLine: 440, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4231 = !DISubroutineType(types: !4232)
!4232 = !{null, !4212, !4233}
!4233 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4188, size: 64)
!4234 = !DISubprogram(name: "append", linkageName: "_ZN4llvm15SmallVectorImplIjE6appendEmRKj", scope: !4188, file: !1967, line: 460, type: !4235, scopeLine: 460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4235 = !DISubroutineType(types: !4236)
!4236 = !{null, !4212, !4237, !2697}
!4237 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !4188, file: !1967, line: 377, baseType: !4238)
!4238 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !2619, file: !1967, line: 97, baseType: !1583)
!4239 = !DISubprogram(name: "assign", linkageName: "_ZN4llvm15SmallVectorImplIjE6assignEjRKj", scope: !4188, file: !1967, line: 470, type: !4224, scopeLine: 470, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4240 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIjE5eraseEPj", scope: !4188, file: !1967, line: 478, type: !4241, scopeLine: 478, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4241 = !DISubroutineType(types: !4242)
!4242 = !{!4243, !4212, !4243}
!4243 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !4188, file: !1967, line: 376, baseType: !2618)
!4244 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm15SmallVectorImplIjE5eraseEPjS2_", scope: !4188, file: !1967, line: 490, type: !4245, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4245 = !DISubroutineType(types: !4246)
!4246 = !{!4243, !4212, !4243, !4243}
!4247 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIjE6insertEPjOj", scope: !4188, file: !1967, line: 505, type: !4248, scopeLine: 505, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4248 = !DISubroutineType(types: !4249)
!4249 = !{!4243, !4212, !4243, !4250}
!4250 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !6, size: 64)
!4251 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIjE6insertEPjRKj", scope: !4188, file: !1967, line: 537, type: !4252, scopeLine: 537, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4252 = !DISubroutineType(types: !4253)
!4253 = !{!4243, !4212, !4243, !2697}
!4254 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm15SmallVectorImplIjE6insertEPjmRKj", scope: !4188, file: !1967, line: 568, type: !4255, scopeLine: 568, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4255 = !DISubroutineType(types: !4256)
!4256 = !{!4243, !4212, !4243, !4237, !2697}
!4257 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIjEaSERKS1_", scope: !4188, file: !1967, line: 674, type: !4258, scopeLine: 674, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4258 = !DISubroutineType(types: !4259)
!4259 = !{!4233, !4212, !4213}
!4260 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm15SmallVectorImplIjEaSEOS1_", scope: !4188, file: !1967, line: 677, type: !4261, scopeLine: 677, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4261 = !DISubroutineType(types: !4262)
!4262 = !{!4233, !4212, !4263}
!4263 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !4188, size: 64)
!4264 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm15SmallVectorImplIjEeqERKS1_", scope: !4188, file: !1967, line: 680, type: !4265, scopeLine: 680, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4265 = !DISubroutineType(types: !4266)
!4266 = !{!308, !4267, !4213}
!4267 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4214, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4268 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm15SmallVectorImplIjEneERKS1_", scope: !4188, file: !1967, line: 684, type: !4265, scopeLine: 684, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4269 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm15SmallVectorImplIjEltERKS1_", scope: !4188, file: !1967, line: 688, type: !4265, scopeLine: 688, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4270 = !DISubprogram(name: "set_size", linkageName: "_ZN4llvm15SmallVectorImplIjE8set_sizeEj", scope: !4188, file: !1967, line: 702, type: !4216, scopeLine: 702, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4271 = !{!2707}
!4272 = !DIDerivedType(tag: DW_TAG_member, name: "Storage", scope: !4185, file: !1967, line: 882, baseType: !4273, size: 288, offset: 224)
!4273 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "SmallVectorStorage<unsigned int, 10U>", scope: !342, file: !1967, line: 865, size: 288, flags: DIFlagTypePassByValue, elements: !4274, templateParams: !4279, identifier: "_ZTSN4llvm18SmallVectorStorageIjLj10EEE")
!4274 = !{!4275}
!4275 = !DIDerivedType(tag: DW_TAG_member, name: "InlineElts", scope: !4273, file: !1967, line: 866, baseType: !4276, size: 288)
!4276 = !DICompositeType(tag: DW_TAG_array_type, baseType: !2623, size: 288, elements: !4277)
!4277 = !{!4278}
!4278 = !DISubrange(count: 9)
!4279 = !{!2707, !4280}
!4280 = !DITemplateValueParameter(name: "N", type: !6, value: i32 10)
!4281 = !DISubprogram(name: "SmallVector", scope: !4185, file: !1967, line: 884, type: !4282, scopeLine: 884, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4282 = !DISubroutineType(types: !4283)
!4283 = !{null, !4284}
!4284 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4185, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!4285 = !DISubprogram(name: "SmallVector", scope: !4185, file: !1967, line: 887, type: !4286, scopeLine: 887, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4286 = !DISubroutineType(types: !4287)
!4287 = !{null, !4284, !6, !2697}
!4288 = !DISubprogram(name: "SmallVector", scope: !4185, file: !1967, line: 897, type: !4289, scopeLine: 897, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4289 = !DISubroutineType(types: !4290)
!4290 = !{null, !4284, !4291}
!4291 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !4292, size: 64)
!4292 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4185)
!4293 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIjLj10EEaSERKS1_", scope: !4185, file: !1967, line: 902, type: !4294, scopeLine: 902, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4294 = !DISubroutineType(types: !4295)
!4295 = !{!4291, !4284, !4291}
!4296 = !DISubprogram(name: "SmallVector", scope: !4185, file: !1967, line: 908, type: !4297, scopeLine: 908, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4297 = !DISubroutineType(types: !4298)
!4298 = !{null, !4284, !4299}
!4299 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !4185, size: 64)
!4300 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm11SmallVectorIjLj10EEaSEOS1_", scope: !4185, file: !1967, line: 913, type: !4301, scopeLine: 913, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4301 = !DISubroutineType(types: !4302)
!4302 = !{!4291, !4284, !4299}
!4303 = !{!4304, !4309, !4314, !4319, !4324, !4329, !4334, !4339, !4344, !4349, !4354, !4359, !4362, !4367, !4372, !4377, !4379, !4381, !4383, !4385, !4390, !4393, !4398, !4403, !4405, !4407, !4410, !4412, !4414, !4416, !4421, !4423, !4425, !4430, !4432, !4434, !4436, !4441, !4446, !4451, !4453, !4458, !4463, !4465, !4467, !4472, !4474, !4479, !4484, !4486, !4491, !4496, !4501, !4506, !4511, !4513, !4518, !4523, !4525, !4530, !4535, !4537, !4542, !4547, !4552, !4557, !4562, !4564, !4569, !4571, !4576, !4581, !4584, !4586, !4588, !4590, !4592, !4594, !4599, !4601, !4606, !4611, !4616, !4618, !4623, !4625, !4630, !4632, !4634, !4636, !4638, !4640, !4642, !4644, !4649, !4651, !4653, !4655, !4657, !4662, !4664, !4666, !4668, !4670, !4672, !4674, !4677, !4679, !4681, !4683, !4685, !4687, !4689, !4691, !4693, !4695, !4697, !4699, !4742, !4747, !4752, !4757, !4762, !4764, !4766, !4771, !4773, !4778, !4783, !4788, !4790, !4792, !4794, !4799, !4804, !4807, !4812, !4817, !4822, !4827, !4829, !4834, !4837, !4843, !4848, !4850, !4852, !4857, !4859, !4861, !4863, !4865, !4867, !4869, !4871, !4873, !4875, !4880, !4882, !4884, !4886, !4888, !4891, !4893, !4895, !4897, !4899, !4901, !4903, !4905, !4908, !4910, !4912, !4914, !4916, !4918, !4923, !4925, !4927, !4929, !4931, !4933, !4935, !4937, !4939, !4941, !4943, !4945, !4947, !4949, !4951, !4953, !4955, !4957, !4962, !4967, !4969, !4971, !4973, !4975, !4977, !4979, !4981, !4983, !4985, !4987, !4989, !4991, !4993, !4995, !4997, !4999, !5001, !5003, !5005, !5007, !5009, !5011, !5013, !5015, !5017, !5019, !5021, !5023, !5025, !5027, !5029, !5031, !5033, !5035, !5037, !5039, !5041, !5043, !5048, !5050, !5052, !5054, !5056, !5058, !5060, !5062, !5064, !5066, !5068, !5070, !5072, !5074, !5076, !5078, !5080, !5082, !5084, !5086, !5088, !5090, !5092, !5094, !5096, !5098, !5100, !5102, !5104, !5106, !5108, !5110, !5112, !5114, !5116, !5118, !5120, !5122, !5124, !5126, !5128, !5130, !5132, !5134, !5136, !5138, !5140, !5142, !5144, !5146, !5148, !5150, !5152, !5154, !5156, !5158, !5160, !5162, !5164, !5166, !5168, !5170, !5172, !5174, !5176, !5178, !5180, !5182, !5184, !5186, !5188, !5190, !5192, !5194, !5196, !5198, !5200, !5202, !5204, !5206, !5208, !5210, !5212, !5214, !5216, !5218, !5220, !5222, !5224, !5226, !5228, !5230, !5232, !5234, !5236, !5238, !5240, !5242, !5247, !5249, !5251, !5253, !5255, !5257, !5259, !5261, !5263, !5265, !5267, !5269, !5271, !5273, !5275, !5277, !5279, !5281, !5283, !5285, !5287, !5289, !5291, !5293, !5295, !5297, !5299, !5301, !5303, !5305, !5307, !5309, !5311, !5313, !5315, !5317, !5319, !5321, !5323, !5325, !5327, !5329, !5331, !5336, !5338, !5340, !5342, !5344, !5346, !5348, !5350, !5352, !5354, !5356, !5358, !5360, !5362, !5364, !5366, !5368, !5370, !5372, !5374, !5376, !5378, !5380, !5382, !5384, !5386, !5388, !5390, !5392, !5394, !5396, !5398, !5400, !5402, !5404, !5406, !5408, !5410, !5412, !5414, !5416, !5418, !5420, !5422, !5424, !5426, !5428, !5430, !5432, !5434, !5436, !5438, !5440, !5442, !5444, !5446, !5448, !5450, !5452, !5454, !5456, !5458, !5460, !5462, !5464, !5466, !5468, !5470, !5472, !5474, !5476, !5481, !5486, !5488, !5490, !5492, !5497, !5499, !5504, !5506, !5511, !5513, !5518, !5523, !5525, !5527, !5532, !5534, !5536, !5538, !5543, !5545, !5547, !5552, !5557, !5560, !5562, !5564}
!4304 = !DIGlobalVariableExpression(var: !4305, expr: !DIExpression())
!4305 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 37, type: !4306, isLocal: true, isDefinition: true)
!4306 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 296, elements: !4307)
!4307 = !{!4308}
!4308 = !DISubrange(count: 37)
!4309 = !DIGlobalVariableExpression(var: !4310, expr: !DIExpression())
!4310 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 37, type: !4311, isLocal: true, isDefinition: true)
!4311 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 536, elements: !4312)
!4312 = !{!4313}
!4313 = !DISubrange(count: 67)
!4314 = !DIGlobalVariableExpression(var: !4315, expr: !DIExpression())
!4315 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 37, type: !4316, isLocal: true, isDefinition: true)
!4316 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 480, elements: !4317)
!4317 = !{!4318}
!4318 = !DISubrange(count: 60)
!4319 = !DIGlobalVariableExpression(var: !4320, expr: !DIExpression())
!4320 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 37, type: !4321, isLocal: true, isDefinition: true)
!4321 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 848, elements: !4322)
!4322 = !{!4323}
!4323 = !DISubrange(count: 106)
!4324 = !DIGlobalVariableExpression(var: !4325, expr: !DIExpression())
!4325 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 40, type: !4326, isLocal: true, isDefinition: true)
!4326 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 272, elements: !4327)
!4327 = !{!4328}
!4328 = !DISubrange(count: 34)
!4329 = !DIGlobalVariableExpression(var: !4330, expr: !DIExpression())
!4330 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 40, type: !4331, isLocal: true, isDefinition: true)
!4331 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 472, elements: !4332)
!4332 = !{!4333}
!4333 = !DISubrange(count: 59)
!4334 = !DIGlobalVariableExpression(var: !4335, expr: !DIExpression())
!4335 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 45, type: !4336, isLocal: true, isDefinition: true)
!4336 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 280, elements: !4337)
!4337 = !{!4338}
!4338 = !DISubrange(count: 35)
!4339 = !DIGlobalVariableExpression(var: !4340, expr: !DIExpression())
!4340 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 45, type: !4341, isLocal: true, isDefinition: true)
!4341 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 344, elements: !4342)
!4342 = !{!4343}
!4343 = !DISubrange(count: 43)
!4344 = !DIGlobalVariableExpression(var: !4345, expr: !DIExpression())
!4345 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 45, type: !4346, isLocal: true, isDefinition: true)
!4346 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 776, elements: !4347)
!4347 = !{!4348}
!4348 = !DISubrange(count: 97)
!4349 = !DIGlobalVariableExpression(var: !4350, expr: !DIExpression())
!4350 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 46, type: !4351, isLocal: true, isDefinition: true)
!4351 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 368, elements: !4352)
!4352 = !{!4353}
!4353 = !DISubrange(count: 46)
!4354 = !DIGlobalVariableExpression(var: !4355, expr: !DIExpression())
!4355 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 46, type: !4356, isLocal: true, isDefinition: true)
!4356 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 560, elements: !4357)
!4357 = !{!4358}
!4358 = !DISubrange(count: 70)
!4359 = !DIGlobalVariableExpression(var: !4360, expr: !DIExpression())
!4360 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 60, type: !4361, isLocal: true, isDefinition: true)
!4361 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 72, elements: !4277)
!4362 = !DIGlobalVariableExpression(var: !4363, expr: !DIExpression())
!4363 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 60, type: !4364, isLocal: true, isDefinition: true)
!4364 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 800, elements: !4365)
!4365 = !{!4366}
!4366 = !DISubrange(count: 100)
!4367 = !DIGlobalVariableExpression(var: !4368, expr: !DIExpression())
!4368 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 62, type: !4369, isLocal: true, isDefinition: true)
!4369 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 520, elements: !4370)
!4370 = !{!4371}
!4371 = !DISubrange(count: 65)
!4372 = !DIGlobalVariableExpression(var: !4373, expr: !DIExpression())
!4373 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 62, type: !4374, isLocal: true, isDefinition: true)
!4374 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 640, elements: !4375)
!4375 = !{!4376}
!4376 = !DISubrange(count: 80)
!4377 = !DIGlobalVariableExpression(var: !4378, expr: !DIExpression())
!4378 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 88, type: !4361, isLocal: true, isDefinition: true)
!4379 = !DIGlobalVariableExpression(var: !4380, expr: !DIExpression())
!4380 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 89, type: !4361, isLocal: true, isDefinition: true)
!4381 = !DIGlobalVariableExpression(var: !4382, expr: !DIExpression())
!4382 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 90, type: !4361, isLocal: true, isDefinition: true)
!4383 = !DIGlobalVariableExpression(var: !4384, expr: !DIExpression())
!4384 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 91, type: !4361, isLocal: true, isDefinition: true)
!4385 = !DIGlobalVariableExpression(var: !4386, expr: !DIExpression())
!4386 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 92, type: !4387, isLocal: true, isDefinition: true)
!4387 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 96, elements: !4388)
!4388 = !{!4389}
!4389 = !DISubrange(count: 12)
!4390 = !DIGlobalVariableExpression(var: !4391, expr: !DIExpression())
!4391 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 93, type: !4392, isLocal: true, isDefinition: true)
!4392 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 64, elements: !2825)
!4393 = !DIGlobalVariableExpression(var: !4394, expr: !DIExpression())
!4394 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 96, type: !4395, isLocal: true, isDefinition: true)
!4395 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 112, elements: !4396)
!4396 = !{!4397}
!4397 = !DISubrange(count: 14)
!4398 = !DIGlobalVariableExpression(var: !4399, expr: !DIExpression())
!4399 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 97, type: !4400, isLocal: true, isDefinition: true)
!4400 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 144, elements: !4401)
!4401 = !{!4402}
!4402 = !DISubrange(count: 18)
!4403 = !DIGlobalVariableExpression(var: !4404, expr: !DIExpression())
!4404 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 98, type: !4395, isLocal: true, isDefinition: true)
!4405 = !DIGlobalVariableExpression(var: !4406, expr: !DIExpression())
!4406 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 101, type: !4395, isLocal: true, isDefinition: true)
!4407 = !DIGlobalVariableExpression(var: !4408, expr: !DIExpression())
!4408 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 102, type: !4409, isLocal: true, isDefinition: true)
!4409 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 128, elements: !498)
!4410 = !DIGlobalVariableExpression(var: !4411, expr: !DIExpression())
!4411 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 103, type: !4395, isLocal: true, isDefinition: true)
!4412 = !DIGlobalVariableExpression(var: !4413, expr: !DIExpression())
!4413 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 104, type: !4409, isLocal: true, isDefinition: true)
!4414 = !DIGlobalVariableExpression(var: !4415, expr: !DIExpression())
!4415 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 105, type: !4395, isLocal: true, isDefinition: true)
!4416 = !DIGlobalVariableExpression(var: !4417, expr: !DIExpression())
!4417 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 106, type: !4418, isLocal: true, isDefinition: true)
!4418 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 152, elements: !4419)
!4419 = !{!4420}
!4420 = !DISubrange(count: 19)
!4421 = !DIGlobalVariableExpression(var: !4422, expr: !DIExpression())
!4422 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 107, type: !4395, isLocal: true, isDefinition: true)
!4423 = !DIGlobalVariableExpression(var: !4424, expr: !DIExpression())
!4424 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 111, type: !4400, isLocal: true, isDefinition: true)
!4425 = !DIGlobalVariableExpression(var: !4426, expr: !DIExpression())
!4426 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 115, type: !4427, isLocal: true, isDefinition: true)
!4427 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 88, elements: !4428)
!4428 = !{!4429}
!4429 = !DISubrange(count: 11)
!4430 = !DIGlobalVariableExpression(var: !4431, expr: !DIExpression())
!4431 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 125, type: !4361, isLocal: true, isDefinition: true)
!4432 = !DIGlobalVariableExpression(var: !4433, expr: !DIExpression())
!4433 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 215, type: !4395, isLocal: true, isDefinition: true)
!4434 = !DIGlobalVariableExpression(var: !4435, expr: !DIExpression())
!4435 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 215, type: !4346, isLocal: true, isDefinition: true)
!4436 = !DIGlobalVariableExpression(var: !4437, expr: !DIExpression())
!4437 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 518, type: !4438, isLocal: true, isDefinition: true)
!4438 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 240, elements: !4439)
!4439 = !{!4440}
!4440 = !DISubrange(count: 30)
!4441 = !DIGlobalVariableExpression(var: !4442, expr: !DIExpression())
!4442 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 518, type: !4443, isLocal: true, isDefinition: true)
!4443 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 448, elements: !4444)
!4444 = !{!4445}
!4445 = !DISubrange(count: 56)
!4446 = !DIGlobalVariableExpression(var: !4447, expr: !DIExpression())
!4447 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 518, type: !4448, isLocal: true, isDefinition: true)
!4448 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 1008, elements: !4449)
!4449 = !{!4450}
!4450 = !DISubrange(count: 126)
!4451 = !DIGlobalVariableExpression(var: !4452, expr: !DIExpression())
!4452 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 533, type: !4306, isLocal: true, isDefinition: true)
!4453 = !DIGlobalVariableExpression(var: !4454, expr: !DIExpression())
!4454 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 533, type: !4455, isLocal: true, isDefinition: true)
!4455 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 696, elements: !4456)
!4456 = !{!4457}
!4457 = !DISubrange(count: 87)
!4458 = !DIGlobalVariableExpression(var: !4459, expr: !DIExpression())
!4459 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 690, type: !4460, isLocal: true, isDefinition: true)
!4460 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 16, elements: !4461)
!4461 = !{!4462}
!4462 = !DISubrange(count: 2)
!4463 = !DIGlobalVariableExpression(var: !4464, expr: !DIExpression())
!4464 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 693, type: !4460, isLocal: true, isDefinition: true)
!4465 = !DIGlobalVariableExpression(var: !4466, expr: !DIExpression())
!4466 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 784, type: !4361, isLocal: true, isDefinition: true)
!4467 = !DIGlobalVariableExpression(var: !4468, expr: !DIExpression())
!4468 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 784, type: !4469, isLocal: true, isDefinition: true)
!4469 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 840, elements: !4470)
!4470 = !{!4471}
!4471 = !DISubrange(count: 105)
!4472 = !DIGlobalVariableExpression(var: !4473, expr: !DIExpression())
!4473 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 809, type: !4336, isLocal: true, isDefinition: true)
!4474 = !DIGlobalVariableExpression(var: !4475, expr: !DIExpression())
!4475 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 809, type: !4476, isLocal: true, isDefinition: true)
!4476 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 568, elements: !4477)
!4477 = !{!4478}
!4478 = !DISubrange(count: 71)
!4479 = !DIGlobalVariableExpression(var: !4480, expr: !DIExpression())
!4480 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 811, type: !4481, isLocal: true, isDefinition: true)
!4481 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 304, elements: !4482)
!4482 = !{!4483}
!4483 = !DISubrange(count: 38)
!4484 = !DIGlobalVariableExpression(var: !4485, expr: !DIExpression())
!4485 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1241, type: !4326, isLocal: true, isDefinition: true)
!4486 = !DIGlobalVariableExpression(var: !4487, expr: !DIExpression())
!4487 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1241, type: !4488, isLocal: true, isDefinition: true)
!4488 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 336, elements: !4489)
!4489 = !{!4490}
!4490 = !DISubrange(count: 42)
!4491 = !DIGlobalVariableExpression(var: !4492, expr: !DIExpression())
!4492 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1241, type: !4493, isLocal: true, isDefinition: true)
!4493 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 488, elements: !4494)
!4494 = !{!4495}
!4495 = !DISubrange(count: 61)
!4496 = !DIGlobalVariableExpression(var: !4497, expr: !DIExpression())
!4497 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1357, type: !4498, isLocal: true, isDefinition: true)
!4498 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 208, elements: !4499)
!4499 = !{!4500}
!4500 = !DISubrange(count: 26)
!4501 = !DIGlobalVariableExpression(var: !4502, expr: !DIExpression())
!4502 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1400, type: !4503, isLocal: true, isDefinition: true)
!4503 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 176, elements: !4504)
!4504 = !{!4505}
!4505 = !DISubrange(count: 22)
!4506 = !DIGlobalVariableExpression(var: !4507, expr: !DIExpression())
!4507 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1400, type: !4508, isLocal: true, isDefinition: true)
!4508 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 416, elements: !4509)
!4509 = !{!4510}
!4510 = !DISubrange(count: 52)
!4511 = !DIGlobalVariableExpression(var: !4512, expr: !DIExpression())
!4512 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1437, type: !4409, isLocal: true, isDefinition: true)
!4513 = !DIGlobalVariableExpression(var: !4514, expr: !DIExpression())
!4514 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1483, type: !4515, isLocal: true, isDefinition: true)
!4515 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 160, elements: !4516)
!4516 = !{!4517}
!4517 = !DISubrange(count: 20)
!4518 = !DIGlobalVariableExpression(var: !4519, expr: !DIExpression())
!4519 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 968, type: !4520, isLocal: true, isDefinition: true)
!4520 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 352, elements: !4521)
!4521 = !{!4522}
!4522 = !DISubrange(count: 44)
!4523 = !DIGlobalVariableExpression(var: !4524, expr: !DIExpression())
!4524 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 968, type: !4316, isLocal: true, isDefinition: true)
!4525 = !DIGlobalVariableExpression(var: !4526, expr: !DIExpression())
!4526 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 968, type: !4527, isLocal: true, isDefinition: true)
!4527 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 512, elements: !4528)
!4528 = !{!4529}
!4529 = !DISubrange(count: 64)
!4530 = !DIGlobalVariableExpression(var: !4531, expr: !DIExpression())
!4531 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 968, type: !4532, isLocal: true, isDefinition: true)
!4532 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 744, elements: !4533)
!4533 = !{!4534}
!4534 = !DISubrange(count: 93)
!4535 = !DIGlobalVariableExpression(var: !4536, expr: !DIExpression())
!4536 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 969, type: !4326, isLocal: true, isDefinition: true)
!4537 = !DIGlobalVariableExpression(var: !4538, expr: !DIExpression())
!4538 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 969, type: !4539, isLocal: true, isDefinition: true)
!4539 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 648, elements: !4540)
!4540 = !{!4541}
!4541 = !DISubrange(count: 81)
!4542 = !DIGlobalVariableExpression(var: !4543, expr: !DIExpression())
!4543 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 1069, type: !4544, isLocal: true, isDefinition: true)
!4544 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 320, elements: !4545)
!4545 = !{!4546}
!4546 = !DISubrange(count: 40)
!4547 = !DIGlobalVariableExpression(var: !4548, expr: !DIExpression())
!4548 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 1069, type: !4549, isLocal: true, isDefinition: true)
!4549 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 496, elements: !4550)
!4550 = !{!4551}
!4551 = !DISubrange(count: 62)
!4552 = !DIGlobalVariableExpression(var: !4553, expr: !DIExpression())
!4553 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 1069, type: !4554, isLocal: true, isDefinition: true)
!4554 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 760, elements: !4555)
!4555 = !{!4556}
!4556 = !DISubrange(count: 95)
!4557 = !DIGlobalVariableExpression(var: !4558, expr: !DIExpression())
!4558 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 874, type: !4559, isLocal: true, isDefinition: true)
!4559 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 432, elements: !4560)
!4560 = !{!4561}
!4561 = !DISubrange(count: 54)
!4562 = !DIGlobalVariableExpression(var: !4563, expr: !DIExpression())
!4563 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 874, type: !4311, isLocal: true, isDefinition: true)
!4564 = !DIGlobalVariableExpression(var: !4565, expr: !DIExpression())
!4565 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 874, type: !4566, isLocal: true, isDefinition: true)
!4566 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 576, elements: !4567)
!4567 = !{!4568}
!4568 = !DISubrange(count: 72)
!4569 = !DIGlobalVariableExpression(var: !4570, expr: !DIExpression())
!4570 = distinct !DIGlobalVariable(scope: null, file: !293, line: 162, type: !4508, isLocal: true, isDefinition: true)
!4571 = !DIGlobalVariableExpression(var: !4572, expr: !DIExpression())
!4572 = distinct !DIGlobalVariable(scope: null, file: !293, line: 162, type: !4573, isLocal: true, isDefinition: true)
!4573 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 672, elements: !4574)
!4574 = !{!4575}
!4575 = !DISubrange(count: 84)
!4576 = !DIGlobalVariableExpression(var: !4577, expr: !DIExpression())
!4577 = distinct !DIGlobalVariable(scope: null, file: !293, line: 162, type: !4578, isLocal: true, isDefinition: true)
!4578 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 456, elements: !4579)
!4579 = !{!4580}
!4580 = !DISubrange(count: 57)
!4581 = !DIGlobalVariableExpression(var: !4582, expr: !DIExpression())
!4582 = distinct !DIGlobalVariable(scope: null, file: !293, line: 162, type: !4583, isLocal: true, isDefinition: true)
!4583 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 504, elements: !3990)
!4584 = !DIGlobalVariableExpression(var: !4585, expr: !DIExpression())
!4585 = distinct !DIGlobalVariable(scope: null, file: !293, line: 164, type: !4520, isLocal: true, isDefinition: true)
!4586 = !DIGlobalVariableExpression(var: !4587, expr: !DIExpression())
!4587 = distinct !DIGlobalVariable(scope: null, file: !293, line: 164, type: !4369, isLocal: true, isDefinition: true)
!4588 = !DIGlobalVariableExpression(var: !4589, expr: !DIExpression())
!4589 = distinct !DIGlobalVariable(scope: null, file: !1827, line: 250, type: !4409, isLocal: true, isDefinition: true)
!4590 = !DIGlobalVariableExpression(var: !4591, expr: !DIExpression())
!4591 = distinct !DIGlobalVariable(scope: null, file: !1827, line: 250, type: !4508, isLocal: true, isDefinition: true)
!4592 = !DIGlobalVariableExpression(var: !4593, expr: !DIExpression())
!4593 = distinct !DIGlobalVariable(scope: null, file: !1827, line: 250, type: !4493, isLocal: true, isDefinition: true)
!4594 = !DIGlobalVariableExpression(var: !4595, expr: !DIExpression())
!4595 = distinct !DIGlobalVariable(scope: null, file: !1827, line: 250, type: !4596, isLocal: true, isDefinition: true)
!4596 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 624, elements: !4597)
!4597 = !{!4598}
!4598 = !DISubrange(count: 78)
!4599 = !DIGlobalVariableExpression(var: !4600, expr: !DIExpression())
!4600 = distinct !DIGlobalVariable(scope: null, file: !1967, line: 144, type: !4503, isLocal: true, isDefinition: true)
!4601 = !DIGlobalVariableExpression(var: !4602, expr: !DIExpression())
!4602 = distinct !DIGlobalVariable(scope: null, file: !1967, line: 144, type: !4603, isLocal: true, isDefinition: true)
!4603 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 376, elements: !4604)
!4604 = !{!4605}
!4605 = !DISubrange(count: 47)
!4606 = !DIGlobalVariableExpression(var: !4607, expr: !DIExpression())
!4607 = distinct !DIGlobalVariable(scope: null, file: !1967, line: 144, type: !4608, isLocal: true, isDefinition: true)
!4608 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 1168, elements: !4609)
!4609 = !{!4610}
!4610 = !DISubrange(count: 146)
!4611 = !DIGlobalVariableExpression(var: !4612, expr: !DIExpression())
!4612 = distinct !DIGlobalVariable(scope: null, file: !293, line: 115, type: !4613, isLocal: true, isDefinition: true)
!4613 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 312, elements: !4614)
!4614 = !{!4615}
!4615 = !DISubrange(count: 39)
!4616 = !DIGlobalVariableExpression(var: !4617, expr: !DIExpression())
!4617 = distinct !DIGlobalVariable(scope: null, file: !293, line: 115, type: !4316, isLocal: true, isDefinition: true)
!4618 = !DIGlobalVariableExpression(var: !4619, expr: !DIExpression())
!4619 = distinct !DIGlobalVariable(scope: null, file: !293, line: 115, type: !4620, isLocal: true, isDefinition: true)
!4620 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 360, elements: !4621)
!4621 = !{!4622}
!4622 = !DISubrange(count: 45)
!4623 = !DIGlobalVariableExpression(var: !4624, expr: !DIExpression())
!4624 = distinct !DIGlobalVariable(scope: null, file: !2799, line: 539, type: !4515, isLocal: true, isDefinition: true)
!4625 = !DIGlobalVariableExpression(var: !4626, expr: !DIExpression())
!4626 = distinct !DIGlobalVariable(scope: null, file: !2799, line: 539, type: !4627, isLocal: true, isDefinition: true)
!4627 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 328, elements: !4628)
!4628 = !{!4629}
!4629 = !DISubrange(count: 41)
!4630 = !DIGlobalVariableExpression(var: !4631, expr: !DIExpression())
!4631 = distinct !DIGlobalVariable(scope: null, file: !2799, line: 539, type: !4527, isLocal: true, isDefinition: true)
!4632 = !DIGlobalVariableExpression(var: !4633, expr: !DIExpression())
!4633 = distinct !DIGlobalVariable(scope: null, file: !2799, line: 539, type: !4532, isLocal: true, isDefinition: true)
!4634 = !DIGlobalVariableExpression(var: !4635, expr: !DIExpression())
!4635 = distinct !DIGlobalVariable(scope: null, file: !293, line: 121, type: !4341, isLocal: true, isDefinition: true)
!4636 = !DIGlobalVariableExpression(var: !4637, expr: !DIExpression())
!4637 = distinct !DIGlobalVariable(scope: null, file: !1967, line: 158, type: !4361, isLocal: true, isDefinition: true)
!4638 = !DIGlobalVariableExpression(var: !4639, expr: !DIExpression())
!4639 = distinct !DIGlobalVariable(scope: null, file: !1967, line: 158, type: !4321, isLocal: true, isDefinition: true)
!4640 = !DIGlobalVariableExpression(var: !4641, expr: !DIExpression())
!4641 = distinct !DIGlobalVariable(scope: null, file: !1967, line: 628, type: !4306, isLocal: true, isDefinition: true)
!4642 = !DIGlobalVariableExpression(var: !4643, expr: !DIExpression())
!4643 = distinct !DIGlobalVariable(scope: null, file: !1967, line: 628, type: !4493, isLocal: true, isDefinition: true)
!4644 = !DIGlobalVariableExpression(var: !4645, expr: !DIExpression())
!4645 = distinct !DIGlobalVariable(scope: null, file: !1967, line: 628, type: !4646, isLocal: true, isDefinition: true)
!4646 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 1304, elements: !4647)
!4647 = !{!4648}
!4648 = !DISubrange(count: 163)
!4649 = !DIGlobalVariableExpression(var: !4650, expr: !DIExpression())
!4650 = distinct !DIGlobalVariable(scope: null, file: !1967, line: 629, type: !4481, isLocal: true, isDefinition: true)
!4651 = !DIGlobalVariableExpression(var: !4652, expr: !DIExpression())
!4652 = distinct !DIGlobalVariable(scope: null, file: !1967, line: 629, type: !4316, isLocal: true, isDefinition: true)
!4653 = !DIGlobalVariableExpression(var: !4654, expr: !DIExpression())
!4654 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 976, type: !4573, isLocal: true, isDefinition: true)
!4655 = !DIGlobalVariableExpression(var: !4656, expr: !DIExpression())
!4656 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 977, type: !4374, isLocal: true, isDefinition: true)
!4657 = !DIGlobalVariableExpression(var: !4658, expr: !DIExpression())
!4658 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 983, type: !4659, isLocal: true, isDefinition: true)
!4659 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 608, elements: !4660)
!4660 = !{!4661}
!4661 = !DISubrange(count: 76)
!4662 = !DIGlobalVariableExpression(var: !4663, expr: !DIExpression())
!4663 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 984, type: !4573, isLocal: true, isDefinition: true)
!4664 = !DIGlobalVariableExpression(var: !4665, expr: !DIExpression())
!4665 = distinct !DIGlobalVariable(scope: null, file: !355, line: 212, type: !4488, isLocal: true, isDefinition: true)
!4666 = !DIGlobalVariableExpression(var: !4667, expr: !DIExpression())
!4667 = distinct !DIGlobalVariable(scope: null, file: !1579, line: 78, type: !4603, isLocal: true, isDefinition: true)
!4668 = !DIGlobalVariableExpression(var: !4669, expr: !DIExpression())
!4669 = distinct !DIGlobalVariable(scope: null, file: !1579, line: 78, type: !4443, isLocal: true, isDefinition: true)
!4670 = !DIGlobalVariableExpression(var: !4671, expr: !DIExpression())
!4671 = distinct !DIGlobalVariable(scope: null, file: !1579, line: 78, type: !4620, isLocal: true, isDefinition: true)
!4672 = !DIGlobalVariableExpression(var: !4673, expr: !DIExpression())
!4673 = distinct !DIGlobalVariable(scope: null, file: !1579, line: 78, type: !4627, isLocal: true, isDefinition: true)
!4674 = !DIGlobalVariableExpression(var: !4675, expr: !DIExpression())
!4675 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 826, type: !4676, isLocal: true, isDefinition: true)
!4676 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 32, elements: !2107)
!4677 = !DIGlobalVariableExpression(var: !4678, expr: !DIExpression())
!4678 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 826, type: !4676, isLocal: true, isDefinition: true)
!4679 = !DIGlobalVariableExpression(var: !4680, expr: !DIExpression())
!4680 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 826, type: !4676, isLocal: true, isDefinition: true)
!4681 = !DIGlobalVariableExpression(var: !4682, expr: !DIExpression())
!4682 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 826, type: !4676, isLocal: true, isDefinition: true)
!4683 = !DIGlobalVariableExpression(var: !4684, expr: !DIExpression())
!4684 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 826, type: !4676, isLocal: true, isDefinition: true)
!4685 = !DIGlobalVariableExpression(var: !4686, expr: !DIExpression())
!4686 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 826, type: !4676, isLocal: true, isDefinition: true)
!4687 = !DIGlobalVariableExpression(var: !4688, expr: !DIExpression())
!4688 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 826, type: !4676, isLocal: true, isDefinition: true)
!4689 = !DIGlobalVariableExpression(var: !4690, expr: !DIExpression())
!4690 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 826, type: !4676, isLocal: true, isDefinition: true)
!4691 = !DIGlobalVariableExpression(var: !4692, expr: !DIExpression())
!4692 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 826, type: !4676, isLocal: true, isDefinition: true)
!4693 = !DIGlobalVariableExpression(var: !4694, expr: !DIExpression())
!4694 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 826, type: !4676, isLocal: true, isDefinition: true)
!4695 = !DIGlobalVariableExpression(var: !4696, expr: !DIExpression())
!4696 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 826, type: !4676, isLocal: true, isDefinition: true)
!4697 = !DIGlobalVariableExpression(var: !4698, expr: !DIExpression())
!4698 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 826, type: !4676, isLocal: true, isDefinition: true)
!4699 = !DIGlobalVariableExpression(var: !4700, expr: !DIExpression())
!4700 = distinct !DIGlobalVariable(name: "Months", scope: !4701, file: !1450, line: 825, type: !4741, isLocal: true, isDefinition: true)
!4701 = distinct !DISubprogram(name: "ComputeDATE_TIME", linkageName: "_ZL16ComputeDATE_TIMERN5clang14SourceLocationES1_RNS_12PreprocessorE", scope: !1450, file: !1450, line: 820, type: !4702, scopeLine: 821, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !4706)
!4702 = !DISubroutineType(types: !4703)
!4703 = !{null, !4704, !4704, !4705}
!4704 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !297, size: 64)
!4705 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2800, size: 64)
!4706 = !{!4707, !4708, !4709, !4710, !4715, !4731, !4733, !4736, !4737, !4739, !4740}
!4707 = !DILocalVariable(name: "DATELoc", arg: 1, scope: !4701, file: !1450, line: 820, type: !4704)
!4708 = !DILocalVariable(name: "TIMELoc", arg: 2, scope: !4701, file: !1450, line: 820, type: !4704)
!4709 = !DILocalVariable(name: "PP", arg: 3, scope: !4701, file: !1450, line: 821, type: !4705)
!4710 = !DILocalVariable(name: "TT", scope: !4701, file: !1450, line: 822, type: !4711)
!4711 = !DIDerivedType(tag: DW_TAG_typedef, name: "time_t", file: !4712, line: 7, baseType: !4713)
!4712 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/time_t.h", directory: "", checksumkind: CSK_MD5, checksum: "49b4e16ef1215de5afdbb283400ab90c")
!4713 = !DIDerivedType(tag: DW_TAG_typedef, name: "__time_t", file: !4714, line: 148, baseType: !1837)
!4714 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types.h", directory: "", checksumkind: CSK_MD5, checksum: "25679ba19d359e314e48661b21f5aa1f")
!4715 = !DILocalVariable(name: "TM", scope: !4701, file: !1450, line: 823, type: !4716)
!4716 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4717, size: 64)
!4717 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "tm", file: !4718, line: 7, size: 448, flags: DIFlagTypePassByValue, elements: !4719, identifier: "_ZTS2tm")
!4718 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/struct_tm.h", directory: "", checksumkind: CSK_MD5, checksum: "9e5545b565ef031c4cd0faf90b69386f")
!4719 = !{!4720, !4721, !4722, !4723, !4724, !4725, !4726, !4727, !4728, !4729, !4730}
!4720 = !DIDerivedType(tag: DW_TAG_member, name: "tm_sec", scope: !4717, file: !4718, line: 9, baseType: !324, size: 32)
!4721 = !DIDerivedType(tag: DW_TAG_member, name: "tm_min", scope: !4717, file: !4718, line: 10, baseType: !324, size: 32, offset: 32)
!4722 = !DIDerivedType(tag: DW_TAG_member, name: "tm_hour", scope: !4717, file: !4718, line: 11, baseType: !324, size: 32, offset: 64)
!4723 = !DIDerivedType(tag: DW_TAG_member, name: "tm_mday", scope: !4717, file: !4718, line: 12, baseType: !324, size: 32, offset: 96)
!4724 = !DIDerivedType(tag: DW_TAG_member, name: "tm_mon", scope: !4717, file: !4718, line: 13, baseType: !324, size: 32, offset: 128)
!4725 = !DIDerivedType(tag: DW_TAG_member, name: "tm_year", scope: !4717, file: !4718, line: 14, baseType: !324, size: 32, offset: 160)
!4726 = !DIDerivedType(tag: DW_TAG_member, name: "tm_wday", scope: !4717, file: !4718, line: 15, baseType: !324, size: 32, offset: 192)
!4727 = !DIDerivedType(tag: DW_TAG_member, name: "tm_yday", scope: !4717, file: !4718, line: 16, baseType: !324, size: 32, offset: 224)
!4728 = !DIDerivedType(tag: DW_TAG_member, name: "tm_isdst", scope: !4717, file: !4718, line: 17, baseType: !324, size: 32, offset: 256)
!4729 = !DIDerivedType(tag: DW_TAG_member, name: "tm_gmtoff", scope: !4717, file: !4718, line: 20, baseType: !1837, size: 64, offset: 320)
!4730 = !DIDerivedType(tag: DW_TAG_member, name: "tm_zone", scope: !4717, file: !4718, line: 21, baseType: !407, size: 64, offset: 384)
!4731 = !DILocalVariable(name: "TmpBuffer", scope: !4732, file: !1450, line: 830, type: !3518)
!4732 = distinct !DILexicalBlock(scope: !4701, file: !1450, line: 829, column: 3)
!4733 = !DILocalVariable(name: "TmpStream", scope: !4732, file: !1450, line: 831, type: !4734)
!4734 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "raw_svector_ostream", scope: !342, file: !4735, line: 450, size: 384, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm19raw_svector_ostreamE")
!4735 = !DIFile(filename: "llvm34/include/llvm/Support/raw_ostream.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "2bb663449bd8797aa5193bb52a5154a0")
!4736 = !DILocalVariable(name: "TmpTok", scope: !4732, file: !1450, line: 834, type: !294)
!4737 = !DILocalVariable(name: "TmpBuffer", scope: !4738, file: !1450, line: 841, type: !3518)
!4738 = distinct !DILexicalBlock(scope: !4701, file: !1450, line: 840, column: 3)
!4739 = !DILocalVariable(name: "TmpStream", scope: !4738, file: !1450, line: 842, type: !4734)
!4740 = !DILocalVariable(name: "TmpTok", scope: !4738, file: !1450, line: 845, type: !294)
!4741 = !DICompositeType(tag: DW_TAG_array_type, baseType: !3646, size: 768, elements: !4388)
!4742 = !DIGlobalVariableExpression(var: !4743, expr: !DIExpression())
!4743 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 832, type: !4744, isLocal: true, isDefinition: true)
!4744 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 104, elements: !4745)
!4745 = !{!4746}
!4746 = !DISubrange(count: 13)
!4747 = !DIGlobalVariableExpression(var: !4748, expr: !DIExpression())
!4748 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 843, type: !4749, isLocal: true, isDefinition: true)
!4749 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 136, elements: !4750)
!4750 = !{!4751}
!4751 = !DISubrange(count: 17)
!4752 = !DIGlobalVariableExpression(var: !4753, expr: !DIExpression())
!4753 = distinct !DIGlobalVariable(scope: null, file: !1967, line: 144, type: !4754, isLocal: true, isDefinition: true)
!4754 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 1360, elements: !4755)
!4755 = !{!4756}
!4756 = !DISubrange(count: 170)
!4757 = !DIGlobalVariableExpression(var: !4758, expr: !DIExpression())
!4758 = distinct !DIGlobalVariable(scope: null, file: !346, line: 1565, type: !4759, isLocal: true, isDefinition: true)
!4759 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 224, elements: !4760)
!4760 = !{!4761}
!4761 = !DISubrange(count: 28)
!4762 = !DIGlobalVariableExpression(var: !4763, expr: !DIExpression())
!4763 = distinct !DIGlobalVariable(scope: null, file: !346, line: 1565, type: !4488, isLocal: true, isDefinition: true)
!4764 = !DIGlobalVariableExpression(var: !4765, expr: !DIExpression())
!4765 = distinct !DIGlobalVariable(scope: null, file: !346, line: 1565, type: !4311, isLocal: true, isDefinition: true)
!4766 = !DIGlobalVariableExpression(var: !4767, expr: !DIExpression())
!4767 = distinct !DIGlobalVariable(scope: null, file: !346, line: 1565, type: !4768, isLocal: true, isDefinition: true)
!4768 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 664, elements: !4769)
!4769 = !{!4770}
!4770 = !DISubrange(count: 83)
!4771 = !DIGlobalVariableExpression(var: !4772, expr: !DIExpression())
!4772 = distinct !DIGlobalVariable(scope: null, file: !346, line: 1489, type: !4395, isLocal: true, isDefinition: true)
!4773 = !DIGlobalVariableExpression(var: !4774, expr: !DIExpression())
!4774 = distinct !DIGlobalVariable(scope: null, file: !346, line: 1489, type: !4775, isLocal: true, isDefinition: true)
!4775 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 440, elements: !4776)
!4776 = !{!4777}
!4777 = !DISubrange(count: 55)
!4778 = !DIGlobalVariableExpression(var: !4779, expr: !DIExpression())
!4779 = distinct !DIGlobalVariable(scope: null, file: !346, line: 1489, type: !4780, isLocal: true, isDefinition: true)
!4780 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 752, elements: !4781)
!4781 = !{!4782}
!4782 = !DISubrange(count: 94)
!4783 = !DIGlobalVariableExpression(var: !4784, expr: !DIExpression())
!4784 = distinct !DIGlobalVariable(scope: null, file: !1967, line: 140, type: !4785, isLocal: true, isDefinition: true)
!4785 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 1264, elements: !4786)
!4786 = !{!4787}
!4787 = !DISubrange(count: 158)
!4788 = !DIGlobalVariableExpression(var: !4789, expr: !DIExpression())
!4789 = distinct !DIGlobalVariable(scope: null, file: !346, line: 1479, type: !4559, isLocal: true, isDefinition: true)
!4790 = !DIGlobalVariableExpression(var: !4791, expr: !DIExpression())
!4791 = distinct !DIGlobalVariable(scope: null, file: !346, line: 1479, type: !4532, isLocal: true, isDefinition: true)
!4792 = !DIGlobalVariableExpression(var: !4793, expr: !DIExpression())
!4793 = distinct !DIGlobalVariable(scope: null, file: !346, line: 402, type: !4503, isLocal: true, isDefinition: true)
!4794 = !DIGlobalVariableExpression(var: !4795, expr: !DIExpression())
!4795 = distinct !DIGlobalVariable(scope: null, file: !346, line: 402, type: !4796, isLocal: true, isDefinition: true)
!4796 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 288, elements: !4797)
!4797 = !{!4798}
!4798 = !DISubrange(count: 36)
!4799 = !DIGlobalVariableExpression(var: !4800, expr: !DIExpression())
!4800 = distinct !DIGlobalVariable(scope: null, file: !346, line: 402, type: !4801, isLocal: true, isDefinition: true)
!4801 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 584, elements: !4802)
!4802 = !{!4803}
!4803 = !DISubrange(count: 73)
!4804 = !DIGlobalVariableExpression(var: !4805, expr: !DIExpression())
!4805 = distinct !DIGlobalVariable(scope: null, file: !4806, line: 154, type: !4476, isLocal: true, isDefinition: true)
!4806 = !DIFile(filename: "llvm34/projects/clang/include/clang/Lex/PreprocessorLexer.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "21e94b7bdd21445a227572b946433d91")
!4807 = !DIGlobalVariableExpression(var: !4808, expr: !DIExpression())
!4808 = distinct !DIGlobalVariable(scope: null, file: !4806, line: 154, type: !4809, isLocal: true, isDefinition: true)
!4809 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 632, elements: !4810)
!4810 = !{!4811}
!4811 = !DISubrange(count: 79)
!4812 = !DIGlobalVariableExpression(var: !4813, expr: !DIExpression())
!4813 = distinct !DIGlobalVariable(scope: null, file: !4806, line: 154, type: !4814, isLocal: true, isDefinition: true)
!4814 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 552, elements: !4815)
!4815 = !{!4816}
!4816 = !DISubrange(count: 69)
!4817 = !DIGlobalVariableExpression(var: !4818, expr: !DIExpression())
!4818 = distinct !DIGlobalVariable(scope: null, file: !4806, line: 154, type: !4819, isLocal: true, isDefinition: true)
!4819 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 464, elements: !4820)
!4820 = !{!4821}
!4821 = !DISubrange(count: 58)
!4822 = !DIGlobalVariableExpression(var: !4823, expr: !DIExpression())
!4823 = distinct !DIGlobalVariable(scope: null, file: !1579, line: 85, type: !4824, isLocal: true, isDefinition: true)
!4824 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 544, elements: !4825)
!4825 = !{!4826}
!4826 = !DISubrange(count: 68)
!4827 = !DIGlobalVariableExpression(var: !4828, expr: !DIExpression())
!4828 = distinct !DIGlobalVariable(scope: null, file: !1579, line: 85, type: !4554, isLocal: true, isDefinition: true)
!4829 = !DIGlobalVariableExpression(var: !4830, expr: !DIExpression())
!4830 = distinct !DIGlobalVariable(scope: null, file: !1579, line: 85, type: !4831, isLocal: true, isDefinition: true)
!4831 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 392, elements: !4832)
!4832 = !{!4833}
!4833 = !DISubrange(count: 49)
!4834 = !DIGlobalVariableExpression(var: !4835, expr: !DIExpression())
!4835 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1051, type: !4836, isLocal: true, isDefinition: true)
!4836 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 24, elements: !4024)
!4837 = !DIGlobalVariableExpression(var: !4838, expr: !DIExpression())
!4838 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 9, type: !4840, isLocal: true, isDefinition: true)
!4839 = !DIFile(filename: "projects/clang/include/clang/Lex/AttrSpellings.inc", directory: "/fast/fs/build34llvm5", checksumkind: CSK_MD5, checksum: "15be89b255834adff7a75ed0f3845cc3")
!4840 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 80, elements: !4841)
!4841 = !{!4842}
!4842 = !DISubrange(count: 10)
!4843 = !DIGlobalVariableExpression(var: !4844, expr: !DIExpression())
!4844 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 10, type: !4845, isLocal: true, isDefinition: true)
!4845 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 120, elements: !4846)
!4846 = !{!4847}
!4847 = !DISubrange(count: 15)
!4848 = !DIGlobalVariableExpression(var: !4849, expr: !DIExpression())
!4849 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 11, type: !4409, isLocal: true, isDefinition: true)
!4850 = !DIGlobalVariableExpression(var: !4851, expr: !DIExpression())
!4851 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 12, type: !4395, isLocal: true, isDefinition: true)
!4852 = !DIGlobalVariableExpression(var: !4853, expr: !DIExpression())
!4853 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 13, type: !4854, isLocal: true, isDefinition: true)
!4854 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 48, elements: !4855)
!4855 = !{!4856}
!4856 = !DISubrange(count: 6)
!4857 = !DIGlobalVariableExpression(var: !4858, expr: !DIExpression())
!4858 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 15, type: !4392, isLocal: true, isDefinition: true)
!4859 = !DIGlobalVariableExpression(var: !4860, expr: !DIExpression())
!4860 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 16, type: !4854, isLocal: true, isDefinition: true)
!4861 = !DIGlobalVariableExpression(var: !4862, expr: !DIExpression())
!4862 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 18, type: !4392, isLocal: true, isDefinition: true)
!4863 = !DIGlobalVariableExpression(var: !4864, expr: !DIExpression())
!4864 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 19, type: !4361, isLocal: true, isDefinition: true)
!4865 = !DIGlobalVariableExpression(var: !4866, expr: !DIExpression())
!4866 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 20, type: !4427, isLocal: true, isDefinition: true)
!4867 = !DIGlobalVariableExpression(var: !4868, expr: !DIExpression())
!4868 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 22, type: !4395, isLocal: true, isDefinition: true)
!4869 = !DIGlobalVariableExpression(var: !4870, expr: !DIExpression())
!4870 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 24, type: !4400, isLocal: true, isDefinition: true)
!4871 = !DIGlobalVariableExpression(var: !4872, expr: !DIExpression())
!4872 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 25, type: !4361, isLocal: true, isDefinition: true)
!4873 = !DIGlobalVariableExpression(var: !4874, expr: !DIExpression())
!4874 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 26, type: !4796, isLocal: true, isDefinition: true)
!4875 = !DIGlobalVariableExpression(var: !4876, expr: !DIExpression())
!4876 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 27, type: !4877, isLocal: true, isDefinition: true)
!4877 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 184, elements: !4878)
!4878 = !{!4879}
!4879 = !DISubrange(count: 23)
!4880 = !DIGlobalVariableExpression(var: !4881, expr: !DIExpression())
!4881 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 28, type: !4503, isLocal: true, isDefinition: true)
!4882 = !DIGlobalVariableExpression(var: !4883, expr: !DIExpression())
!4883 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 29, type: !4503, isLocal: true, isDefinition: true)
!4884 = !DIGlobalVariableExpression(var: !4885, expr: !DIExpression())
!4885 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 30, type: !4418, isLocal: true, isDefinition: true)
!4886 = !DIGlobalVariableExpression(var: !4887, expr: !DIExpression())
!4887 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 31, type: !4744, isLocal: true, isDefinition: true)
!4888 = !DIGlobalVariableExpression(var: !4889, expr: !DIExpression())
!4889 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 32, type: !4890, isLocal: true, isDefinition: true)
!4890 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 56, elements: !3479)
!4891 = !DIGlobalVariableExpression(var: !4892, expr: !DIExpression())
!4892 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 33, type: !4392, isLocal: true, isDefinition: true)
!4893 = !DIGlobalVariableExpression(var: !4894, expr: !DIExpression())
!4894 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 34, type: !4840, isLocal: true, isDefinition: true)
!4895 = !DIGlobalVariableExpression(var: !4896, expr: !DIExpression())
!4896 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 35, type: !4854, isLocal: true, isDefinition: true)
!4897 = !DIGlobalVariableExpression(var: !4898, expr: !DIExpression())
!4898 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 37, type: !4392, isLocal: true, isDefinition: true)
!4899 = !DIGlobalVariableExpression(var: !4900, expr: !DIExpression())
!4900 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 38, type: !4890, isLocal: true, isDefinition: true)
!4901 = !DIGlobalVariableExpression(var: !4902, expr: !DIExpression())
!4902 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 39, type: !4515, isLocal: true, isDefinition: true)
!4903 = !DIGlobalVariableExpression(var: !4904, expr: !DIExpression())
!4904 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 40, type: !4387, isLocal: true, isDefinition: true)
!4905 = !DIGlobalVariableExpression(var: !4906, expr: !DIExpression())
!4906 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 41, type: !4907, isLocal: true, isDefinition: true)
!4907 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 192, elements: !2001)
!4908 = !DIGlobalVariableExpression(var: !4909, expr: !DIExpression())
!4909 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 42, type: !4515, isLocal: true, isDefinition: true)
!4910 = !DIGlobalVariableExpression(var: !4911, expr: !DIExpression())
!4911 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 43, type: !4515, isLocal: true, isDefinition: true)
!4912 = !DIGlobalVariableExpression(var: !4913, expr: !DIExpression())
!4913 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 44, type: !4361, isLocal: true, isDefinition: true)
!4914 = !DIGlobalVariableExpression(var: !4915, expr: !DIExpression())
!4915 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 45, type: !4890, isLocal: true, isDefinition: true)
!4916 = !DIGlobalVariableExpression(var: !4917, expr: !DIExpression())
!4917 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 46, type: !4890, isLocal: true, isDefinition: true)
!4918 = !DIGlobalVariableExpression(var: !4919, expr: !DIExpression())
!4919 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 47, type: !4920, isLocal: true, isDefinition: true)
!4920 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 40, elements: !4921)
!4921 = !{!4922}
!4922 = !DISubrange(count: 5)
!4923 = !DIGlobalVariableExpression(var: !4924, expr: !DIExpression())
!4924 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 48, type: !4395, isLocal: true, isDefinition: true)
!4925 = !DIGlobalVariableExpression(var: !4926, expr: !DIExpression())
!4926 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 49, type: !4890, isLocal: true, isDefinition: true)
!4927 = !DIGlobalVariableExpression(var: !4928, expr: !DIExpression())
!4928 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 50, type: !4361, isLocal: true, isDefinition: true)
!4929 = !DIGlobalVariableExpression(var: !4930, expr: !DIExpression())
!4930 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 52, type: !4395, isLocal: true, isDefinition: true)
!4931 = !DIGlobalVariableExpression(var: !4932, expr: !DIExpression())
!4932 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 53, type: !4418, isLocal: true, isDefinition: true)
!4933 = !DIGlobalVariableExpression(var: !4934, expr: !DIExpression())
!4934 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 56, type: !4392, isLocal: true, isDefinition: true)
!4935 = !DIGlobalVariableExpression(var: !4936, expr: !DIExpression())
!4936 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 58, type: !4920, isLocal: true, isDefinition: true)
!4937 = !DIGlobalVariableExpression(var: !4938, expr: !DIExpression())
!4938 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 60, type: !4890, isLocal: true, isDefinition: true)
!4939 = !DIGlobalVariableExpression(var: !4940, expr: !DIExpression())
!4940 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 62, type: !4854, isLocal: true, isDefinition: true)
!4941 = !DIGlobalVariableExpression(var: !4942, expr: !DIExpression())
!4942 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 63, type: !4392, isLocal: true, isDefinition: true)
!4943 = !DIGlobalVariableExpression(var: !4944, expr: !DIExpression())
!4944 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 66, type: !4387, isLocal: true, isDefinition: true)
!4945 = !DIGlobalVariableExpression(var: !4946, expr: !DIExpression())
!4946 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 68, type: !4427, isLocal: true, isDefinition: true)
!4947 = !DIGlobalVariableExpression(var: !4948, expr: !DIExpression())
!4948 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 69, type: !4840, isLocal: true, isDefinition: true)
!4949 = !DIGlobalVariableExpression(var: !4950, expr: !DIExpression())
!4950 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 70, type: !4840, isLocal: true, isDefinition: true)
!4951 = !DIGlobalVariableExpression(var: !4952, expr: !DIExpression())
!4952 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 71, type: !4427, isLocal: true, isDefinition: true)
!4953 = !DIGlobalVariableExpression(var: !4954, expr: !DIExpression())
!4954 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 74, type: !4427, isLocal: true, isDefinition: true)
!4955 = !DIGlobalVariableExpression(var: !4956, expr: !DIExpression())
!4956 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 76, type: !4907, isLocal: true, isDefinition: true)
!4957 = !DIGlobalVariableExpression(var: !4958, expr: !DIExpression())
!4958 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 77, type: !4959, isLocal: true, isDefinition: true)
!4959 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 200, elements: !4960)
!4960 = !{!4961}
!4961 = !DISubrange(count: 25)
!4962 = !DIGlobalVariableExpression(var: !4963, expr: !DIExpression())
!4963 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 78, type: !4964, isLocal: true, isDefinition: true)
!4964 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 216, elements: !4965)
!4965 = !{!4966}
!4966 = !DISubrange(count: 27)
!4967 = !DIGlobalVariableExpression(var: !4968, expr: !DIExpression())
!4968 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 79, type: !4409, isLocal: true, isDefinition: true)
!4969 = !DIGlobalVariableExpression(var: !4970, expr: !DIExpression())
!4970 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 80, type: !4387, isLocal: true, isDefinition: true)
!4971 = !DIGlobalVariableExpression(var: !4972, expr: !DIExpression())
!4972 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 81, type: !4361, isLocal: true, isDefinition: true)
!4973 = !DIGlobalVariableExpression(var: !4974, expr: !DIExpression())
!4974 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 83, type: !4427, isLocal: true, isDefinition: true)
!4975 = !DIGlobalVariableExpression(var: !4976, expr: !DIExpression())
!4976 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 84, type: !4840, isLocal: true, isDefinition: true)
!4977 = !DIGlobalVariableExpression(var: !4978, expr: !DIExpression())
!4978 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 85, type: !4854, isLocal: true, isDefinition: true)
!4979 = !DIGlobalVariableExpression(var: !4980, expr: !DIExpression())
!4980 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 86, type: !4890, isLocal: true, isDefinition: true)
!4981 = !DIGlobalVariableExpression(var: !4982, expr: !DIExpression())
!4982 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 87, type: !4395, isLocal: true, isDefinition: true)
!4983 = !DIGlobalVariableExpression(var: !4984, expr: !DIExpression())
!4984 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 88, type: !4890, isLocal: true, isDefinition: true)
!4985 = !DIGlobalVariableExpression(var: !4986, expr: !DIExpression())
!4986 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 90, type: !4427, isLocal: true, isDefinition: true)
!4987 = !DIGlobalVariableExpression(var: !4988, expr: !DIExpression())
!4988 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 92, type: !4427, isLocal: true, isDefinition: true)
!4989 = !DIGlobalVariableExpression(var: !4990, expr: !DIExpression())
!4990 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 94, type: !4427, isLocal: true, isDefinition: true)
!4991 = !DIGlobalVariableExpression(var: !4992, expr: !DIExpression())
!4992 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 95, type: !4387, isLocal: true, isDefinition: true)
!4993 = !DIGlobalVariableExpression(var: !4994, expr: !DIExpression())
!4994 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 96, type: !4676, isLocal: true, isDefinition: true)
!4995 = !DIGlobalVariableExpression(var: !4996, expr: !DIExpression())
!4996 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 98, type: !4361, isLocal: true, isDefinition: true)
!4997 = !DIGlobalVariableExpression(var: !4998, expr: !DIExpression())
!4998 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 99, type: !4361, isLocal: true, isDefinition: true)
!4999 = !DIGlobalVariableExpression(var: !5000, expr: !DIExpression())
!5000 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 100, type: !4418, isLocal: true, isDefinition: true)
!5001 = !DIGlobalVariableExpression(var: !5002, expr: !DIExpression())
!5002 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 101, type: !4395, isLocal: true, isDefinition: true)
!5003 = !DIGlobalVariableExpression(var: !5004, expr: !DIExpression())
!5004 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 102, type: !4845, isLocal: true, isDefinition: true)
!5005 = !DIGlobalVariableExpression(var: !5006, expr: !DIExpression())
!5006 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 103, type: !4395, isLocal: true, isDefinition: true)
!5007 = !DIGlobalVariableExpression(var: !5008, expr: !DIExpression())
!5008 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 104, type: !4361, isLocal: true, isDefinition: true)
!5009 = !DIGlobalVariableExpression(var: !5010, expr: !DIExpression())
!5010 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 105, type: !4845, isLocal: true, isDefinition: true)
!5011 = !DIGlobalVariableExpression(var: !5012, expr: !DIExpression())
!5012 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 106, type: !4890, isLocal: true, isDefinition: true)
!5013 = !DIGlobalVariableExpression(var: !5014, expr: !DIExpression())
!5014 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 108, type: !4890, isLocal: true, isDefinition: true)
!5015 = !DIGlobalVariableExpression(var: !5016, expr: !DIExpression())
!5016 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 110, type: !4840, isLocal: true, isDefinition: true)
!5017 = !DIGlobalVariableExpression(var: !5018, expr: !DIExpression())
!5018 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 112, type: !4392, isLocal: true, isDefinition: true)
!5019 = !DIGlobalVariableExpression(var: !5020, expr: !DIExpression())
!5020 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 113, type: !4890, isLocal: true, isDefinition: true)
!5021 = !DIGlobalVariableExpression(var: !5022, expr: !DIExpression())
!5022 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 115, type: !4920, isLocal: true, isDefinition: true)
!5023 = !DIGlobalVariableExpression(var: !5024, expr: !DIExpression())
!5024 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 117, type: !4361, isLocal: true, isDefinition: true)
!5025 = !DIGlobalVariableExpression(var: !5026, expr: !DIExpression())
!5026 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 118, type: !4840, isLocal: true, isDefinition: true)
!5027 = !DIGlobalVariableExpression(var: !5028, expr: !DIExpression())
!5028 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 119, type: !4877, isLocal: true, isDefinition: true)
!5029 = !DIGlobalVariableExpression(var: !5030, expr: !DIExpression())
!5030 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 120, type: !4427, isLocal: true, isDefinition: true)
!5031 = !DIGlobalVariableExpression(var: !5032, expr: !DIExpression())
!5032 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 121, type: !4387, isLocal: true, isDefinition: true)
!5033 = !DIGlobalVariableExpression(var: !5034, expr: !DIExpression())
!5034 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 122, type: !4749, isLocal: true, isDefinition: true)
!5035 = !DIGlobalVariableExpression(var: !5036, expr: !DIExpression())
!5036 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 123, type: !4907, isLocal: true, isDefinition: true)
!5037 = !DIGlobalVariableExpression(var: !5038, expr: !DIExpression())
!5038 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 124, type: !4907, isLocal: true, isDefinition: true)
!5039 = !DIGlobalVariableExpression(var: !5040, expr: !DIExpression())
!5040 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 125, type: !4515, isLocal: true, isDefinition: true)
!5041 = !DIGlobalVariableExpression(var: !5042, expr: !DIExpression())
!5042 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 126, type: !4854, isLocal: true, isDefinition: true)
!5043 = !DIGlobalVariableExpression(var: !5044, expr: !DIExpression())
!5044 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 128, type: !5045, isLocal: true, isDefinition: true)
!5045 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 168, elements: !5046)
!5046 = !{!5047}
!5047 = !DISubrange(count: 21)
!5048 = !DIGlobalVariableExpression(var: !5049, expr: !DIExpression())
!5049 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 129, type: !4749, isLocal: true, isDefinition: true)
!5050 = !DIGlobalVariableExpression(var: !5051, expr: !DIExpression())
!5051 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 130, type: !4361, isLocal: true, isDefinition: true)
!5052 = !DIGlobalVariableExpression(var: !5053, expr: !DIExpression())
!5053 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 132, type: !4392, isLocal: true, isDefinition: true)
!5054 = !DIGlobalVariableExpression(var: !5055, expr: !DIExpression())
!5055 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 133, type: !4361, isLocal: true, isDefinition: true)
!5056 = !DIGlobalVariableExpression(var: !5057, expr: !DIExpression())
!5057 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 135, type: !4877, isLocal: true, isDefinition: true)
!5058 = !DIGlobalVariableExpression(var: !5059, expr: !DIExpression())
!5059 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 137, type: !4361, isLocal: true, isDefinition: true)
!5060 = !DIGlobalVariableExpression(var: !5061, expr: !DIExpression())
!5061 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 141, type: !4964, isLocal: true, isDefinition: true)
!5062 = !DIGlobalVariableExpression(var: !5063, expr: !DIExpression())
!5063 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 142, type: !4515, isLocal: true, isDefinition: true)
!5064 = !DIGlobalVariableExpression(var: !5065, expr: !DIExpression())
!5065 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 145, type: !4418, isLocal: true, isDefinition: true)
!5066 = !DIGlobalVariableExpression(var: !5067, expr: !DIExpression())
!5067 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 146, type: !4418, isLocal: true, isDefinition: true)
!5068 = !DIGlobalVariableExpression(var: !5069, expr: !DIExpression())
!5069 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 147, type: !4498, isLocal: true, isDefinition: true)
!5070 = !DIGlobalVariableExpression(var: !5071, expr: !DIExpression())
!5071 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 148, type: !4392, isLocal: true, isDefinition: true)
!5072 = !DIGlobalVariableExpression(var: !5073, expr: !DIExpression())
!5073 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 150, type: !4392, isLocal: true, isDefinition: true)
!5074 = !DIGlobalVariableExpression(var: !5075, expr: !DIExpression())
!5075 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 152, type: !4387, isLocal: true, isDefinition: true)
!5076 = !DIGlobalVariableExpression(var: !5077, expr: !DIExpression())
!5077 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 153, type: !4845, isLocal: true, isDefinition: true)
!5078 = !DIGlobalVariableExpression(var: !5079, expr: !DIExpression())
!5079 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 154, type: !4392, isLocal: true, isDefinition: true)
!5080 = !DIGlobalVariableExpression(var: !5081, expr: !DIExpression())
!5081 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 155, type: !4418, isLocal: true, isDefinition: true)
!5082 = !DIGlobalVariableExpression(var: !5083, expr: !DIExpression())
!5083 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 156, type: !4361, isLocal: true, isDefinition: true)
!5084 = !DIGlobalVariableExpression(var: !5085, expr: !DIExpression())
!5085 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 157, type: !4845, isLocal: true, isDefinition: true)
!5086 = !DIGlobalVariableExpression(var: !5087, expr: !DIExpression())
!5087 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 158, type: !4503, isLocal: true, isDefinition: true)
!5088 = !DIGlobalVariableExpression(var: !5089, expr: !DIExpression())
!5089 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 159, type: !4336, isLocal: true, isDefinition: true)
!5090 = !DIGlobalVariableExpression(var: !5091, expr: !DIExpression())
!5091 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 160, type: !4515, isLocal: true, isDefinition: true)
!5092 = !DIGlobalVariableExpression(var: !5093, expr: !DIExpression())
!5093 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 161, type: !4964, isLocal: true, isDefinition: true)
!5094 = !DIGlobalVariableExpression(var: !5095, expr: !DIExpression())
!5095 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 162, type: !4409, isLocal: true, isDefinition: true)
!5096 = !DIGlobalVariableExpression(var: !5097, expr: !DIExpression())
!5097 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 163, type: !4515, isLocal: true, isDefinition: true)
!5098 = !DIGlobalVariableExpression(var: !5099, expr: !DIExpression())
!5099 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 164, type: !4361, isLocal: true, isDefinition: true)
!5100 = !DIGlobalVariableExpression(var: !5101, expr: !DIExpression())
!5101 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 165, type: !4890, isLocal: true, isDefinition: true)
!5102 = !DIGlobalVariableExpression(var: !5103, expr: !DIExpression())
!5103 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 166, type: !4744, isLocal: true, isDefinition: true)
!5104 = !DIGlobalVariableExpression(var: !5105, expr: !DIExpression())
!5105 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 167, type: !4409, isLocal: true, isDefinition: true)
!5106 = !DIGlobalVariableExpression(var: !5107, expr: !DIExpression())
!5107 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 168, type: !4400, isLocal: true, isDefinition: true)
!5108 = !DIGlobalVariableExpression(var: !5109, expr: !DIExpression())
!5109 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 169, type: !4409, isLocal: true, isDefinition: true)
!5110 = !DIGlobalVariableExpression(var: !5111, expr: !DIExpression())
!5111 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 170, type: !4890, isLocal: true, isDefinition: true)
!5112 = !DIGlobalVariableExpression(var: !5113, expr: !DIExpression())
!5113 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 172, type: !4409, isLocal: true, isDefinition: true)
!5114 = !DIGlobalVariableExpression(var: !5115, expr: !DIExpression())
!5115 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 173, type: !4890, isLocal: true, isDefinition: true)
!5116 = !DIGlobalVariableExpression(var: !5117, expr: !DIExpression())
!5117 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 174, type: !4361, isLocal: true, isDefinition: true)
!5118 = !DIGlobalVariableExpression(var: !5119, expr: !DIExpression())
!5119 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 175, type: !4392, isLocal: true, isDefinition: true)
!5120 = !DIGlobalVariableExpression(var: !5121, expr: !DIExpression())
!5121 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 176, type: !4676, isLocal: true, isDefinition: true)
!5122 = !DIGlobalVariableExpression(var: !5123, expr: !DIExpression())
!5123 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 178, type: !4840, isLocal: true, isDefinition: true)
!5124 = !DIGlobalVariableExpression(var: !5125, expr: !DIExpression())
!5125 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 179, type: !4395, isLocal: true, isDefinition: true)
!5126 = !DIGlobalVariableExpression(var: !5127, expr: !DIExpression())
!5127 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 180, type: !4845, isLocal: true, isDefinition: true)
!5128 = !DIGlobalVariableExpression(var: !5129, expr: !DIExpression())
!5129 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 181, type: !4392, isLocal: true, isDefinition: true)
!5130 = !DIGlobalVariableExpression(var: !5131, expr: !DIExpression())
!5131 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 182, type: !4392, isLocal: true, isDefinition: true)
!5132 = !DIGlobalVariableExpression(var: !5133, expr: !DIExpression())
!5133 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 183, type: !4920, isLocal: true, isDefinition: true)
!5134 = !DIGlobalVariableExpression(var: !5135, expr: !DIExpression())
!5135 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 185, type: !4392, isLocal: true, isDefinition: true)
!5136 = !DIGlobalVariableExpression(var: !5137, expr: !DIExpression())
!5137 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 187, type: !5045, isLocal: true, isDefinition: true)
!5138 = !DIGlobalVariableExpression(var: !5139, expr: !DIExpression())
!5139 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 188, type: !4749, isLocal: true, isDefinition: true)
!5140 = !DIGlobalVariableExpression(var: !5141, expr: !DIExpression())
!5141 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 189, type: !4395, isLocal: true, isDefinition: true)
!5142 = !DIGlobalVariableExpression(var: !5143, expr: !DIExpression())
!5143 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 191, type: !4890, isLocal: true, isDefinition: true)
!5144 = !DIGlobalVariableExpression(var: !5145, expr: !DIExpression())
!5145 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 192, type: !4409, isLocal: true, isDefinition: true)
!5146 = !DIGlobalVariableExpression(var: !5147, expr: !DIExpression())
!5147 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 193, type: !4392, isLocal: true, isDefinition: true)
!5148 = !DIGlobalVariableExpression(var: !5149, expr: !DIExpression())
!5149 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 195, type: !4840, isLocal: true, isDefinition: true)
!5150 = !DIGlobalVariableExpression(var: !5151, expr: !DIExpression())
!5151 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 196, type: !4361, isLocal: true, isDefinition: true)
!5152 = !DIGlobalVariableExpression(var: !5153, expr: !DIExpression())
!5153 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 198, type: !4395, isLocal: true, isDefinition: true)
!5154 = !DIGlobalVariableExpression(var: !5155, expr: !DIExpression())
!5155 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 199, type: !5045, isLocal: true, isDefinition: true)
!5156 = !DIGlobalVariableExpression(var: !5157, expr: !DIExpression())
!5157 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 200, type: !4503, isLocal: true, isDefinition: true)
!5158 = !DIGlobalVariableExpression(var: !5159, expr: !DIExpression())
!5159 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 201, type: !4907, isLocal: true, isDefinition: true)
!5160 = !DIGlobalVariableExpression(var: !5161, expr: !DIExpression())
!5161 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 202, type: !5045, isLocal: true, isDefinition: true)
!5162 = !DIGlobalVariableExpression(var: !5163, expr: !DIExpression())
!5163 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 203, type: !4392, isLocal: true, isDefinition: true)
!5164 = !DIGlobalVariableExpression(var: !5165, expr: !DIExpression())
!5165 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 205, type: !4840, isLocal: true, isDefinition: true)
!5166 = !DIGlobalVariableExpression(var: !5167, expr: !DIExpression())
!5167 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 206, type: !4361, isLocal: true, isDefinition: true)
!5168 = !DIGlobalVariableExpression(var: !5169, expr: !DIExpression())
!5169 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 207, type: !4361, isLocal: true, isDefinition: true)
!5170 = !DIGlobalVariableExpression(var: !5171, expr: !DIExpression())
!5171 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 209, type: !4840, isLocal: true, isDefinition: true)
!5172 = !DIGlobalVariableExpression(var: !5173, expr: !DIExpression())
!5173 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 211, type: !4845, isLocal: true, isDefinition: true)
!5174 = !DIGlobalVariableExpression(var: !5175, expr: !DIExpression())
!5175 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 212, type: !4361, isLocal: true, isDefinition: true)
!5176 = !DIGlobalVariableExpression(var: !5177, expr: !DIExpression())
!5177 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 214, type: !4427, isLocal: true, isDefinition: true)
!5178 = !DIGlobalVariableExpression(var: !5179, expr: !DIExpression())
!5179 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 215, type: !4840, isLocal: true, isDefinition: true)
!5180 = !DIGlobalVariableExpression(var: !5181, expr: !DIExpression())
!5181 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 216, type: !4400, isLocal: true, isDefinition: true)
!5182 = !DIGlobalVariableExpression(var: !5183, expr: !DIExpression())
!5183 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 218, type: !4503, isLocal: true, isDefinition: true)
!5184 = !DIGlobalVariableExpression(var: !5185, expr: !DIExpression())
!5185 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 219, type: !4409, isLocal: true, isDefinition: true)
!5186 = !DIGlobalVariableExpression(var: !5187, expr: !DIExpression())
!5187 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 221, type: !4890, isLocal: true, isDefinition: true)
!5188 = !DIGlobalVariableExpression(var: !5189, expr: !DIExpression())
!5189 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 222, type: !4387, isLocal: true, isDefinition: true)
!5190 = !DIGlobalVariableExpression(var: !5191, expr: !DIExpression())
!5191 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 223, type: !4387, isLocal: true, isDefinition: true)
!5192 = !DIGlobalVariableExpression(var: !5193, expr: !DIExpression())
!5193 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 224, type: !4409, isLocal: true, isDefinition: true)
!5194 = !DIGlobalVariableExpression(var: !5195, expr: !DIExpression())
!5195 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 225, type: !4890, isLocal: true, isDefinition: true)
!5196 = !DIGlobalVariableExpression(var: !5197, expr: !DIExpression())
!5197 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 227, type: !4920, isLocal: true, isDefinition: true)
!5198 = !DIGlobalVariableExpression(var: !5199, expr: !DIExpression())
!5199 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 229, type: !4920, isLocal: true, isDefinition: true)
!5200 = !DIGlobalVariableExpression(var: !5201, expr: !DIExpression())
!5201 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 230, type: !4840, isLocal: true, isDefinition: true)
!5202 = !DIGlobalVariableExpression(var: !5203, expr: !DIExpression())
!5203 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 231, type: !4395, isLocal: true, isDefinition: true)
!5204 = !DIGlobalVariableExpression(var: !5205, expr: !DIExpression())
!5205 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 232, type: !4387, isLocal: true, isDefinition: true)
!5206 = !DIGlobalVariableExpression(var: !5207, expr: !DIExpression())
!5207 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 234, type: !4503, isLocal: true, isDefinition: true)
!5208 = !DIGlobalVariableExpression(var: !5209, expr: !DIExpression())
!5209 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 235, type: !4427, isLocal: true, isDefinition: true)
!5210 = !DIGlobalVariableExpression(var: !5211, expr: !DIExpression())
!5211 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 237, type: !4387, isLocal: true, isDefinition: true)
!5212 = !DIGlobalVariableExpression(var: !5213, expr: !DIExpression())
!5213 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 238, type: !4418, isLocal: true, isDefinition: true)
!5214 = !DIGlobalVariableExpression(var: !5215, expr: !DIExpression())
!5215 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 241, type: !4920, isLocal: true, isDefinition: true)
!5216 = !DIGlobalVariableExpression(var: !5217, expr: !DIExpression())
!5217 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 243, type: !4387, isLocal: true, isDefinition: true)
!5218 = !DIGlobalVariableExpression(var: !5219, expr: !DIExpression())
!5219 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 244, type: !4392, isLocal: true, isDefinition: true)
!5220 = !DIGlobalVariableExpression(var: !5221, expr: !DIExpression())
!5221 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 246, type: !4854, isLocal: true, isDefinition: true)
!5222 = !DIGlobalVariableExpression(var: !5223, expr: !DIExpression())
!5223 = distinct !DIGlobalVariable(scope: null, file: !4839, line: 247, type: !5045, isLocal: true, isDefinition: true)
!5224 = !DIGlobalVariableExpression(var: !5225, expr: !DIExpression())
!5225 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1023, type: !4840, isLocal: true, isDefinition: true)
!5226 = !DIGlobalVariableExpression(var: !5227, expr: !DIExpression())
!5227 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1024, type: !4361, isLocal: true, isDefinition: true)
!5228 = !DIGlobalVariableExpression(var: !5229, expr: !DIExpression())
!5229 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1025, type: !5045, isLocal: true, isDefinition: true)
!5230 = !DIGlobalVariableExpression(var: !5231, expr: !DIExpression())
!5231 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1026, type: !4409, isLocal: true, isDefinition: true)
!5232 = !DIGlobalVariableExpression(var: !5233, expr: !DIExpression())
!5233 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1027, type: !4845, isLocal: true, isDefinition: true)
!5234 = !DIGlobalVariableExpression(var: !5235, expr: !DIExpression())
!5235 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1029, type: !4427, isLocal: true, isDefinition: true)
!5236 = !DIGlobalVariableExpression(var: !5237, expr: !DIExpression())
!5237 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1030, type: !4503, isLocal: true, isDefinition: true)
!5238 = !DIGlobalVariableExpression(var: !5239, expr: !DIExpression())
!5239 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1031, type: !4959, isLocal: true, isDefinition: true)
!5240 = !DIGlobalVariableExpression(var: !5241, expr: !DIExpression())
!5241 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1032, type: !4503, isLocal: true, isDefinition: true)
!5242 = !DIGlobalVariableExpression(var: !5243, expr: !DIExpression())
!5243 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1033, type: !5244, isLocal: true, isDefinition: true)
!5244 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 232, elements: !5245)
!5245 = !{!5246}
!5246 = !DISubrange(count: 29)
!5247 = !DIGlobalVariableExpression(var: !5248, expr: !DIExpression())
!5248 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1034, type: !4498, isLocal: true, isDefinition: true)
!5249 = !DIGlobalVariableExpression(var: !5250, expr: !DIExpression())
!5250 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1035, type: !5045, isLocal: true, isDefinition: true)
!5251 = !DIGlobalVariableExpression(var: !5252, expr: !DIExpression())
!5252 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1036, type: !4395, isLocal: true, isDefinition: true)
!5253 = !DIGlobalVariableExpression(var: !5254, expr: !DIExpression())
!5254 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1037, type: !4326, isLocal: true, isDefinition: true)
!5255 = !DIGlobalVariableExpression(var: !5256, expr: !DIExpression())
!5256 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1038, type: !4503, isLocal: true, isDefinition: true)
!5257 = !DIGlobalVariableExpression(var: !5258, expr: !DIExpression())
!5258 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1040, type: !4515, isLocal: true, isDefinition: true)
!5259 = !DIGlobalVariableExpression(var: !5260, expr: !DIExpression())
!5260 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1041, type: !4400, isLocal: true, isDefinition: true)
!5261 = !DIGlobalVariableExpression(var: !5262, expr: !DIExpression())
!5262 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 1042, type: !4877, isLocal: true, isDefinition: true)
!5263 = !DIGlobalVariableExpression(var: !5264, expr: !DIExpression())
!5264 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 864, type: !4400, isLocal: true, isDefinition: true)
!5265 = !DIGlobalVariableExpression(var: !5266, expr: !DIExpression())
!5266 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 865, type: !4759, isLocal: true, isDefinition: true)
!5267 = !DIGlobalVariableExpression(var: !5268, expr: !DIExpression())
!5268 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 866, type: !4877, isLocal: true, isDefinition: true)
!5269 = !DIGlobalVariableExpression(var: !5270, expr: !DIExpression())
!5270 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 867, type: !4796, isLocal: true, isDefinition: true)
!5271 = !DIGlobalVariableExpression(var: !5272, expr: !DIExpression())
!5272 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 868, type: !4326, isLocal: true, isDefinition: true)
!5273 = !DIGlobalVariableExpression(var: !5274, expr: !DIExpression())
!5274 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 869, type: !4438, isLocal: true, isDefinition: true)
!5275 = !DIGlobalVariableExpression(var: !5276, expr: !DIExpression())
!5276 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 870, type: !4326, isLocal: true, isDefinition: true)
!5277 = !DIGlobalVariableExpression(var: !5278, expr: !DIExpression())
!5278 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 871, type: !4498, isLocal: true, isDefinition: true)
!5279 = !DIGlobalVariableExpression(var: !5280, expr: !DIExpression())
!5280 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 872, type: !4326, isLocal: true, isDefinition: true)
!5281 = !DIGlobalVariableExpression(var: !5282, expr: !DIExpression())
!5282 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 873, type: !4438, isLocal: true, isDefinition: true)
!5283 = !DIGlobalVariableExpression(var: !5284, expr: !DIExpression())
!5284 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 874, type: !4964, isLocal: true, isDefinition: true)
!5285 = !DIGlobalVariableExpression(var: !5286, expr: !DIExpression())
!5286 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 875, type: !4503, isLocal: true, isDefinition: true)
!5287 = !DIGlobalVariableExpression(var: !5288, expr: !DIExpression())
!5288 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 876, type: !4503, isLocal: true, isDefinition: true)
!5289 = !DIGlobalVariableExpression(var: !5290, expr: !DIExpression())
!5290 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 877, type: !4964, isLocal: true, isDefinition: true)
!5291 = !DIGlobalVariableExpression(var: !5292, expr: !DIExpression())
!5292 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 878, type: !5244, isLocal: true, isDefinition: true)
!5293 = !DIGlobalVariableExpression(var: !5294, expr: !DIExpression())
!5294 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 879, type: !4877, isLocal: true, isDefinition: true)
!5295 = !DIGlobalVariableExpression(var: !5296, expr: !DIExpression())
!5296 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 880, type: !4336, isLocal: true, isDefinition: true)
!5297 = !DIGlobalVariableExpression(var: !5298, expr: !DIExpression())
!5298 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 881, type: !4964, isLocal: true, isDefinition: true)
!5299 = !DIGlobalVariableExpression(var: !5300, expr: !DIExpression())
!5300 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 883, type: !4964, isLocal: true, isDefinition: true)
!5301 = !DIGlobalVariableExpression(var: !5302, expr: !DIExpression())
!5302 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 884, type: !4845, isLocal: true, isDefinition: true)
!5303 = !DIGlobalVariableExpression(var: !5304, expr: !DIExpression())
!5304 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 885, type: !4361, isLocal: true, isDefinition: true)
!5305 = !DIGlobalVariableExpression(var: !5306, expr: !DIExpression())
!5306 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 886, type: !4503, isLocal: true, isDefinition: true)
!5307 = !DIGlobalVariableExpression(var: !5308, expr: !DIExpression())
!5308 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 887, type: !4749, isLocal: true, isDefinition: true)
!5309 = !DIGlobalVariableExpression(var: !5310, expr: !DIExpression())
!5310 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 888, type: !4749, isLocal: true, isDefinition: true)
!5311 = !DIGlobalVariableExpression(var: !5312, expr: !DIExpression())
!5312 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 889, type: !4418, isLocal: true, isDefinition: true)
!5313 = !DIGlobalVariableExpression(var: !5314, expr: !DIExpression())
!5314 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 891, type: !4361, isLocal: true, isDefinition: true)
!5315 = !DIGlobalVariableExpression(var: !5316, expr: !DIExpression())
!5316 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 892, type: !4361, isLocal: true, isDefinition: true)
!5317 = !DIGlobalVariableExpression(var: !5318, expr: !DIExpression())
!5318 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 893, type: !4395, isLocal: true, isDefinition: true)
!5319 = !DIGlobalVariableExpression(var: !5320, expr: !DIExpression())
!5320 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 894, type: !4336, isLocal: true, isDefinition: true)
!5321 = !DIGlobalVariableExpression(var: !5322, expr: !DIExpression())
!5322 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 895, type: !4409, isLocal: true, isDefinition: true)
!5323 = !DIGlobalVariableExpression(var: !5324, expr: !DIExpression())
!5324 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 896, type: !4400, isLocal: true, isDefinition: true)
!5325 = !DIGlobalVariableExpression(var: !5326, expr: !DIExpression())
!5326 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 897, type: !4744, isLocal: true, isDefinition: true)
!5327 = !DIGlobalVariableExpression(var: !5328, expr: !DIExpression())
!5328 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 898, type: !4515, isLocal: true, isDefinition: true)
!5329 = !DIGlobalVariableExpression(var: !5330, expr: !DIExpression())
!5330 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 899, type: !4438, isLocal: true, isDefinition: true)
!5331 = !DIGlobalVariableExpression(var: !5332, expr: !DIExpression())
!5332 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 900, type: !5333, isLocal: true, isDefinition: true)
!5333 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 264, elements: !5334)
!5334 = !{!5335}
!5335 = !DISubrange(count: 33)
!5336 = !DIGlobalVariableExpression(var: !5337, expr: !DIExpression())
!5337 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 901, type: !4409, isLocal: true, isDefinition: true)
!5338 = !DIGlobalVariableExpression(var: !5339, expr: !DIExpression())
!5339 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 905, type: !4840, isLocal: true, isDefinition: true)
!5340 = !DIGlobalVariableExpression(var: !5341, expr: !DIExpression())
!5341 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 906, type: !4400, isLocal: true, isDefinition: true)
!5342 = !DIGlobalVariableExpression(var: !5343, expr: !DIExpression())
!5343 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 907, type: !4515, isLocal: true, isDefinition: true)
!5344 = !DIGlobalVariableExpression(var: !5345, expr: !DIExpression())
!5345 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 908, type: !4959, isLocal: true, isDefinition: true)
!5346 = !DIGlobalVariableExpression(var: !5347, expr: !DIExpression())
!5347 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 909, type: !4877, isLocal: true, isDefinition: true)
!5348 = !DIGlobalVariableExpression(var: !5349, expr: !DIExpression())
!5349 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 910, type: !4515, isLocal: true, isDefinition: true)
!5350 = !DIGlobalVariableExpression(var: !5351, expr: !DIExpression())
!5351 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 919, type: !4498, isLocal: true, isDefinition: true)
!5352 = !DIGlobalVariableExpression(var: !5353, expr: !DIExpression())
!5353 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 920, type: !4515, isLocal: true, isDefinition: true)
!5354 = !DIGlobalVariableExpression(var: !5355, expr: !DIExpression())
!5355 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 921, type: !4387, isLocal: true, isDefinition: true)
!5356 = !DIGlobalVariableExpression(var: !5357, expr: !DIExpression())
!5357 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 923, type: !4845, isLocal: true, isDefinition: true)
!5358 = !DIGlobalVariableExpression(var: !5359, expr: !DIExpression())
!5359 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 924, type: !4395, isLocal: true, isDefinition: true)
!5360 = !DIGlobalVariableExpression(var: !5361, expr: !DIExpression())
!5361 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 925, type: !4395, isLocal: true, isDefinition: true)
!5362 = !DIGlobalVariableExpression(var: !5363, expr: !DIExpression())
!5363 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 926, type: !4744, isLocal: true, isDefinition: true)
!5364 = !DIGlobalVariableExpression(var: !5365, expr: !DIExpression())
!5365 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 927, type: !4306, isLocal: true, isDefinition: true)
!5366 = !DIGlobalVariableExpression(var: !5367, expr: !DIExpression())
!5367 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 928, type: !4336, isLocal: true, isDefinition: true)
!5368 = !DIGlobalVariableExpression(var: !5369, expr: !DIExpression())
!5369 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 929, type: !4907, isLocal: true, isDefinition: true)
!5370 = !DIGlobalVariableExpression(var: !5371, expr: !DIExpression())
!5371 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 930, type: !4759, isLocal: true, isDefinition: true)
!5372 = !DIGlobalVariableExpression(var: !5373, expr: !DIExpression())
!5373 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 933, type: !5244, isLocal: true, isDefinition: true)
!5374 = !DIGlobalVariableExpression(var: !5375, expr: !DIExpression())
!5375 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 934, type: !4418, isLocal: true, isDefinition: true)
!5376 = !DIGlobalVariableExpression(var: !5377, expr: !DIExpression())
!5377 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 935, type: !4759, isLocal: true, isDefinition: true)
!5378 = !DIGlobalVariableExpression(var: !5379, expr: !DIExpression())
!5379 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 937, type: !4387, isLocal: true, isDefinition: true)
!5380 = !DIGlobalVariableExpression(var: !5381, expr: !DIExpression())
!5381 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 940, type: !4744, isLocal: true, isDefinition: true)
!5382 = !DIGlobalVariableExpression(var: !5383, expr: !DIExpression())
!5383 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 941, type: !4387, isLocal: true, isDefinition: true)
!5384 = !DIGlobalVariableExpression(var: !5385, expr: !DIExpression())
!5385 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 944, type: !4907, isLocal: true, isDefinition: true)
!5386 = !DIGlobalVariableExpression(var: !5387, expr: !DIExpression())
!5387 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 947, type: !4749, isLocal: true, isDefinition: true)
!5388 = !DIGlobalVariableExpression(var: !5389, expr: !DIExpression())
!5389 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 948, type: !4400, isLocal: true, isDefinition: true)
!5390 = !DIGlobalVariableExpression(var: !5391, expr: !DIExpression())
!5391 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 949, type: !4749, isLocal: true, isDefinition: true)
!5392 = !DIGlobalVariableExpression(var: !5393, expr: !DIExpression())
!5393 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 951, type: !4515, isLocal: true, isDefinition: true)
!5394 = !DIGlobalVariableExpression(var: !5395, expr: !DIExpression())
!5395 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 952, type: !5045, isLocal: true, isDefinition: true)
!5396 = !DIGlobalVariableExpression(var: !5397, expr: !DIExpression())
!5397 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 953, type: !4907, isLocal: true, isDefinition: true)
!5398 = !DIGlobalVariableExpression(var: !5399, expr: !DIExpression())
!5399 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 954, type: !4400, isLocal: true, isDefinition: true)
!5400 = !DIGlobalVariableExpression(var: !5401, expr: !DIExpression())
!5401 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 955, type: !4877, isLocal: true, isDefinition: true)
!5402 = !DIGlobalVariableExpression(var: !5403, expr: !DIExpression())
!5403 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 957, type: !4515, isLocal: true, isDefinition: true)
!5404 = !DIGlobalVariableExpression(var: !5405, expr: !DIExpression())
!5405 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 959, type: !4964, isLocal: true, isDefinition: true)
!5406 = !DIGlobalVariableExpression(var: !5407, expr: !DIExpression())
!5407 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 962, type: !4503, isLocal: true, isDefinition: true)
!5408 = !DIGlobalVariableExpression(var: !5409, expr: !DIExpression())
!5409 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 963, type: !4498, isLocal: true, isDefinition: true)
!5410 = !DIGlobalVariableExpression(var: !5411, expr: !DIExpression())
!5411 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 967, type: !4418, isLocal: true, isDefinition: true)
!5412 = !DIGlobalVariableExpression(var: !5413, expr: !DIExpression())
!5413 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 968, type: !4749, isLocal: true, isDefinition: true)
!5414 = !DIGlobalVariableExpression(var: !5415, expr: !DIExpression())
!5415 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 969, type: !4907, isLocal: true, isDefinition: true)
!5416 = !DIGlobalVariableExpression(var: !5417, expr: !DIExpression())
!5417 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 970, type: !4418, isLocal: true, isDefinition: true)
!5418 = !DIGlobalVariableExpression(var: !5419, expr: !DIExpression())
!5419 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 971, type: !4749, isLocal: true, isDefinition: true)
!5420 = !DIGlobalVariableExpression(var: !5421, expr: !DIExpression())
!5421 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 972, type: !4907, isLocal: true, isDefinition: true)
!5422 = !DIGlobalVariableExpression(var: !5423, expr: !DIExpression())
!5423 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 973, type: !4877, isLocal: true, isDefinition: true)
!5424 = !DIGlobalVariableExpression(var: !5425, expr: !DIExpression())
!5425 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 974, type: !4877, isLocal: true, isDefinition: true)
!5426 = !DIGlobalVariableExpression(var: !5427, expr: !DIExpression())
!5427 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 975, type: !4387, isLocal: true, isDefinition: true)
!5428 = !DIGlobalVariableExpression(var: !5429, expr: !DIExpression())
!5429 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 976, type: !4427, isLocal: true, isDefinition: true)
!5430 = !DIGlobalVariableExpression(var: !5431, expr: !DIExpression())
!5431 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 977, type: !4361, isLocal: true, isDefinition: true)
!5432 = !DIGlobalVariableExpression(var: !5433, expr: !DIExpression())
!5433 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 978, type: !4400, isLocal: true, isDefinition: true)
!5434 = !DIGlobalVariableExpression(var: !5435, expr: !DIExpression())
!5435 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 979, type: !4361, isLocal: true, isDefinition: true)
!5436 = !DIGlobalVariableExpression(var: !5437, expr: !DIExpression())
!5437 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 980, type: !4392, isLocal: true, isDefinition: true)
!5438 = !DIGlobalVariableExpression(var: !5439, expr: !DIExpression())
!5439 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 981, type: !4361, isLocal: true, isDefinition: true)
!5440 = !DIGlobalVariableExpression(var: !5441, expr: !DIExpression())
!5441 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 982, type: !4427, isLocal: true, isDefinition: true)
!5442 = !DIGlobalVariableExpression(var: !5443, expr: !DIExpression())
!5443 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 983, type: !4418, isLocal: true, isDefinition: true)
!5444 = !DIGlobalVariableExpression(var: !5445, expr: !DIExpression())
!5445 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 984, type: !4890, isLocal: true, isDefinition: true)
!5446 = !DIGlobalVariableExpression(var: !5447, expr: !DIExpression())
!5447 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 985, type: !4845, isLocal: true, isDefinition: true)
!5448 = !DIGlobalVariableExpression(var: !5449, expr: !DIExpression())
!5449 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 986, type: !4840, isLocal: true, isDefinition: true)
!5450 = !DIGlobalVariableExpression(var: !5451, expr: !DIExpression())
!5451 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 987, type: !4427, isLocal: true, isDefinition: true)
!5452 = !DIGlobalVariableExpression(var: !5453, expr: !DIExpression())
!5453 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 988, type: !4907, isLocal: true, isDefinition: true)
!5454 = !DIGlobalVariableExpression(var: !5455, expr: !DIExpression())
!5455 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 989, type: !4964, isLocal: true, isDefinition: true)
!5456 = !DIGlobalVariableExpression(var: !5457, expr: !DIExpression())
!5457 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 990, type: !4503, isLocal: true, isDefinition: true)
!5458 = !DIGlobalVariableExpression(var: !5459, expr: !DIExpression())
!5459 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 991, type: !4361, isLocal: true, isDefinition: true)
!5460 = !DIGlobalVariableExpression(var: !5461, expr: !DIExpression())
!5461 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 992, type: !4392, isLocal: true, isDefinition: true)
!5462 = !DIGlobalVariableExpression(var: !5463, expr: !DIExpression())
!5463 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 993, type: !4676, isLocal: true, isDefinition: true)
!5464 = !DIGlobalVariableExpression(var: !5465, expr: !DIExpression())
!5465 = distinct !DIGlobalVariable(scope: null, file: !1450, line: 994, type: !4409, isLocal: true, isDefinition: true)
!5466 = !DIGlobalVariableExpression(var: !5467, expr: !DIExpression())
!5467 = distinct !DIGlobalVariable(scope: null, file: !1473, line: 85, type: !4361, isLocal: true, isDefinition: true)
!5468 = !DIGlobalVariableExpression(var: !5469, expr: !DIExpression())
!5469 = distinct !DIGlobalVariable(scope: null, file: !1473, line: 85, type: !4369, isLocal: true, isDefinition: true)
!5470 = !DIGlobalVariableExpression(var: !5471, expr: !DIExpression())
!5471 = distinct !DIGlobalVariable(scope: null, file: !1430, line: 960, type: !4527, isLocal: true, isDefinition: true)
!5472 = !DIGlobalVariableExpression(var: !5473, expr: !DIExpression())
!5473 = distinct !DIGlobalVariable(scope: null, file: !1546, line: 373, type: !4613, isLocal: true, isDefinition: true)
!5474 = !DIGlobalVariableExpression(var: !5475, expr: !DIExpression())
!5475 = distinct !DIGlobalVariable(scope: null, file: !1546, line: 373, type: !4620, isLocal: true, isDefinition: true)
!5476 = !DIGlobalVariableExpression(var: !5477, expr: !DIExpression())
!5477 = distinct !DIGlobalVariable(scope: null, file: !1546, line: 373, type: !5478, isLocal: true, isDefinition: true)
!5478 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 1960, elements: !5479)
!5479 = !{!5480}
!5480 = !DISubrange(count: 245)
!5481 = !DIGlobalVariableExpression(var: !5482, expr: !DIExpression())
!5482 = distinct !DIGlobalVariable(scope: null, file: !1967, line: 140, type: !5483, isLocal: true, isDefinition: true)
!5483 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 1072, elements: !5484)
!5484 = !{!5485}
!5485 = !DISubrange(count: 134)
!5486 = !DIGlobalVariableExpression(var: !5487, expr: !DIExpression())
!5487 = distinct !DIGlobalVariable(scope: null, file: !2715, line: 478, type: !4559, isLocal: true, isDefinition: true)
!5488 = !DIGlobalVariableExpression(var: !5489, expr: !DIExpression())
!5489 = distinct !DIGlobalVariable(scope: null, file: !2715, line: 478, type: !5483, isLocal: true, isDefinition: true)
!5490 = !DIGlobalVariableExpression(var: !5491, expr: !DIExpression())
!5491 = distinct !DIGlobalVariable(scope: null, file: !2715, line: 478, type: !4520, isLocal: true, isDefinition: true)
!5492 = !DIGlobalVariableExpression(var: !5493, expr: !DIExpression())
!5493 = distinct !DIGlobalVariable(scope: null, file: !2715, line: 478, type: !5494, isLocal: true, isDefinition: true)
!5494 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 4368, elements: !5495)
!5495 = !{!5496}
!5496 = !DISubrange(count: 546)
!5497 = !DIGlobalVariableExpression(var: !5498, expr: !DIExpression())
!5498 = distinct !DIGlobalVariable(scope: null, file: !2715, line: 445, type: !4840, isLocal: true, isDefinition: true)
!5499 = !DIGlobalVariableExpression(var: !5500, expr: !DIExpression())
!5500 = distinct !DIGlobalVariable(scope: null, file: !2715, line: 445, type: !5501, isLocal: true, isDefinition: true)
!5501 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 4096, elements: !5502)
!5502 = !{!5503}
!5503 = !DISubrange(count: 512)
!5504 = !DIGlobalVariableExpression(var: !5505, expr: !DIExpression())
!5505 = distinct !DIGlobalVariable(scope: null, file: !2715, line: 623, type: !4392, isLocal: true, isDefinition: true)
!5506 = !DIGlobalVariableExpression(var: !5507, expr: !DIExpression())
!5507 = distinct !DIGlobalVariable(scope: null, file: !2715, line: 623, type: !5508, isLocal: true, isDefinition: true)
!5508 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 1848, elements: !5509)
!5509 = !{!5510}
!5510 = !DISubrange(count: 231)
!5511 = !DIGlobalVariableExpression(var: !5512, expr: !DIExpression())
!5512 = distinct !DIGlobalVariable(scope: null, file: !2715, line: 271, type: !4488, isLocal: true, isDefinition: true)
!5513 = !DIGlobalVariableExpression(var: !5514, expr: !DIExpression())
!5514 = distinct !DIGlobalVariable(scope: null, file: !2715, line: 271, type: !5515, isLocal: true, isDefinition: true)
!5515 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 736, elements: !5516)
!5516 = !{!5517}
!5517 = !DISubrange(count: 92)
!5518 = !DIGlobalVariableExpression(var: !5519, expr: !DIExpression())
!5519 = distinct !DIGlobalVariable(scope: null, file: !2715, line: 271, type: !5520, isLocal: true, isDefinition: true)
!5520 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 3472, elements: !5521)
!5521 = !{!5522}
!5522 = !DISubrange(count: 434)
!5523 = !DIGlobalVariableExpression(var: !5524, expr: !DIExpression())
!5524 = distinct !DIGlobalVariable(scope: null, file: !2715, line: 291, type: !4907, isLocal: true, isDefinition: true)
!5525 = !DIGlobalVariableExpression(var: !5526, expr: !DIExpression())
!5526 = distinct !DIGlobalVariable(scope: null, file: !2715, line: 291, type: !4613, isLocal: true, isDefinition: true)
!5527 = !DIGlobalVariableExpression(var: !5528, expr: !DIExpression())
!5528 = distinct !DIGlobalVariable(scope: null, file: !2715, line: 291, type: !5529, isLocal: true, isDefinition: true)
!5529 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 4024, elements: !5530)
!5530 = !{!5531}
!5531 = !DISubrange(count: 503)
!5532 = !DIGlobalVariableExpression(var: !5533, expr: !DIExpression())
!5533 = distinct !DIGlobalVariable(scope: null, file: !2780, line: 97, type: !5244, isLocal: true, isDefinition: true)
!5534 = !DIGlobalVariableExpression(var: !5535, expr: !DIExpression())
!5535 = distinct !DIGlobalVariable(scope: null, file: !2780, line: 97, type: !4481, isLocal: true, isDefinition: true)
!5536 = !DIGlobalVariableExpression(var: !5537, expr: !DIExpression())
!5537 = distinct !DIGlobalVariable(scope: null, file: !2780, line: 97, type: !4603, isLocal: true, isDefinition: true)
!5538 = !DIGlobalVariableExpression(var: !5539, expr: !DIExpression())
!5539 = distinct !DIGlobalVariable(scope: null, file: !2780, line: 97, type: !5540, isLocal: true, isDefinition: true)
!5540 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 1416, elements: !5541)
!5541 = !{!5542}
!5542 = !DISubrange(count: 177)
!5543 = !DIGlobalVariableExpression(var: !5544, expr: !DIExpression())
!5544 = distinct !DIGlobalVariable(scope: null, file: !2780, line: 239, type: !4488, isLocal: true, isDefinition: true)
!5545 = !DIGlobalVariableExpression(var: !5546, expr: !DIExpression())
!5546 = distinct !DIGlobalVariable(scope: null, file: !2780, line: 239, type: !4331, isLocal: true, isDefinition: true)
!5547 = !DIGlobalVariableExpression(var: !5548, expr: !DIExpression())
!5548 = distinct !DIGlobalVariable(scope: null, file: !2780, line: 239, type: !5549, isLocal: true, isDefinition: true)
!5549 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 896, elements: !5550)
!5550 = !{!5551}
!5551 = !DISubrange(count: 112)
!5552 = !DIGlobalVariableExpression(var: !5553, expr: !DIExpression())
!5553 = distinct !DIGlobalVariable(scope: null, file: !1967, line: 140, type: !5554, isLocal: true, isDefinition: true)
!5554 = !DICompositeType(tag: DW_TAG_array_type, baseType: !408, size: 1472, elements: !5555)
!5555 = !{!5556}
!5556 = !DISubrange(count: 184)
!5557 = !DIGlobalVariableExpression(var: !5558, expr: !DIExpression())
!5558 = distinct !DIGlobalVariable(scope: null, file: !5559, line: 423, type: !4498, isLocal: true, isDefinition: true)
!5559 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/vector.tcc", directory: "", checksumkind: CSK_MD5, checksum: "d0546ffb79f08cabb1d395ee56a00a29")
!5560 = !DIGlobalVariableExpression(var: !5561, expr: !DIExpression())
!5561 = distinct !DIGlobalVariable(scope: null, file: !358, line: 2826, type: !5045, isLocal: true, isDefinition: true)
!5562 = !DIGlobalVariableExpression(var: !5563, expr: !DIExpression())
!5563 = distinct !DIGlobalVariable(scope: null, file: !358, line: 302, type: !4775, isLocal: true, isDefinition: true)
!5564 = !DIGlobalVariableExpression(var: !5565, expr: !DIExpression())
!5565 = distinct !DIGlobalVariable(scope: null, file: !358, line: 470, type: !4964, isLocal: true, isDefinition: true)
!5566 = !{!5567, !5573, !5580, !5582, !5584, !5588, !5590, !5592, !5594, !5596, !5598, !5600, !5602, !5607, !5611, !5613, !5615, !5620, !5622, !5624, !5626, !5628, !5630, !5632, !5635, !5638, !5640, !5644, !5649, !5651, !5653, !5655, !5657, !5659, !5661, !5663, !5665, !5667, !5669, !5673, !5677, !5679, !5681, !5683, !5685, !5687, !5689, !5691, !5693, !5695, !5697, !5699, !5701, !5703, !5705, !5707, !5711, !5715, !5719, !5721, !5723, !5725, !5727, !5729, !5731, !5733, !5735, !5737, !5741, !5745, !5749, !5751, !5753, !5755, !5760, !5764, !5768, !5770, !5772, !5774, !5776, !5778, !5780, !5782, !5784, !5786, !5788, !5790, !5792, !5796, !5800, !5804, !5806, !5808, !5810, !5814, !5818, !5822, !5824, !5826, !5828, !5830, !5832, !5834, !5838, !5842, !5844, !5846, !5848, !5850, !5854, !5858, !5862, !5864, !5866, !5868, !5870, !5872, !5874, !5878, !5882, !5886, !5888, !5892, !5896, !5898, !5900, !5902, !5904, !5906, !5908, !5913, !5914, !5916, !5918, !5919, !5925, !5929, !5935, !5939, !5943, !5949, !5953, !5955, !5957, !5961, !5965, !5969, !5973, !5975, !5977, !5979, !5981, !5985, !5989, !5993, !5995, !5997, !6001, !6005, !6009, !6010, !6011, !6025, !6028, !6033, !6081, !6089, !6093, !6100, !6104, !6108, !6110, !6112, !6116, !6122, !6126, !6132, !6138, !6140, !6144, !6148, !6152, !6156, !6168, !6170, !6174, !6178, !6182, !6184, !6188, !6192, !6196, !6198, !6200, !6204, !6211, !6215, !6219, !6223, !6225, !6231, !6233, !6239, !6243, !6247, !6251, !6255, !6259, !6263, !6265, !6267, !6271, !6275, !6279, !6281, !6285, !6289, !6291, !6293, !6297, !6301, !6305, !6310, !6311, !6312, !6313, !6314, !6315, !6316, !6317, !6318, !6319, !6320, !6325, !6329, !6332, !6335, !6337, !6339, !6341, !6343, !6345, !6347, !6349, !6351, !6354, !6355, !6359, !6362, !6365, !6368, !6370, !6372, !6374, !6376, !6378, !6380, !6382, !6384, !6387, !6388, !6392, !6396, !6401, !6405, !6407, !6409, !6411, !6413, !6415, !6417, !6419, !6421, !6423, !6425, !6427, !6429, !6431, !6435, !6441, !6445, !6450, !6452, !6455, !6459, !6463, !6472, !6476, !6480, !6484, !6488, !6492, !6496, !6500, !6504, !6508, !6512, !6516, !6520, !6522, !6526, !6530, !6534, !6540, !6544, !6548, !6550, !6554, !6558, !6564, !6566, !6570, !6574, !6578, !6582, !6586, !6590, !6594, !6595, !6596, !6597, !6599, !6600, !6601, !6602, !6603, !6604, !6605, !6609, !6615, !6620, !6624, !6626, !6628, !6630, !6632, !6639, !6643, !6647, !6651, !6655, !6659, !6663, !6667, !6669, !6673, !6679, !6683, !6687, !6689, !6692, !6696, !6700, !6702, !6704, !6706, !6708, !6710, !6712, !6714, !6718, !6722, !6726, !6730, !6734, !6738, !6740, !6744, !6748, !6752, !6756, !6758, !6760, !6764, !6768, !6769, !6770, !6771, !6772, !6773, !6775, !6778, !6784, !6787, !6788, !6790, !6792, !6794, !6796, !6800, !6802, !6804, !6806, !6808, !6810, !6812, !6814, !6816, !6820, !6824, !6826, !6830, !6834, !6839, !6840, !6841, !6846, !6850, !6854, !6859, !6863, !6869, !6873, !6875, !6879}
!5567 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5568, file: !5572, line: 52)
!5568 = !DISubprogram(name: "abs", scope: !5569, file: !5569, line: 837, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5569 = !DIFile(filename: "/usr/include/stdlib.h", directory: "", checksumkind: CSK_MD5, checksum: "69d942f1572b8bd342d93c49f499f318")
!5570 = !DISubroutineType(types: !5571)
!5571 = !{!324, !324}
!5572 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h", directory: "")
!5573 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5574, file: !5579, line: 83)
!5574 = !DISubprogram(name: "acos", scope: !5575, file: !5575, line: 53, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5575 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", directory: "", checksumkind: CSK_MD5, checksum: "540523e6856cf8d57a3ebef5fd79793e")
!5576 = !DISubroutineType(types: !5577)
!5577 = !{!5578, !5578}
!5578 = !DIBasicType(name: "double", size: 64, encoding: DW_ATE_float)
!5579 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cmath", directory: "")
!5580 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5581, file: !5579, line: 102)
!5581 = !DISubprogram(name: "asin", scope: !5575, file: !5575, line: 55, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5582 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5583, file: !5579, line: 121)
!5583 = !DISubprogram(name: "atan", scope: !5575, file: !5575, line: 57, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5584 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5585, file: !5579, line: 140)
!5585 = !DISubprogram(name: "atan2", scope: !5575, file: !5575, line: 59, type: !5586, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5586 = !DISubroutineType(types: !5587)
!5587 = !{!5578, !5578, !5578}
!5588 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5589, file: !5579, line: 161)
!5589 = !DISubprogram(name: "ceil", scope: !5575, file: !5575, line: 159, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5590 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5591, file: !5579, line: 180)
!5591 = !DISubprogram(name: "cos", scope: !5575, file: !5575, line: 62, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5592 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5593, file: !5579, line: 199)
!5593 = !DISubprogram(name: "cosh", scope: !5575, file: !5575, line: 71, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5594 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5595, file: !5579, line: 218)
!5595 = !DISubprogram(name: "exp", scope: !5575, file: !5575, line: 95, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5596 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5597, file: !5579, line: 237)
!5597 = !DISubprogram(name: "fabs", scope: !5575, file: !5575, line: 162, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5598 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5599, file: !5579, line: 256)
!5599 = !DISubprogram(name: "floor", scope: !5575, file: !5575, line: 165, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5600 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5601, file: !5579, line: 275)
!5601 = !DISubprogram(name: "fmod", scope: !5575, file: !5575, line: 168, type: !5586, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5602 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5603, file: !5579, line: 296)
!5603 = !DISubprogram(name: "frexp", scope: !5575, file: !5575, line: 98, type: !5604, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5604 = !DISubroutineType(types: !5605)
!5605 = !{!5578, !5578, !5606}
!5606 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !324, size: 64)
!5607 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5608, file: !5579, line: 315)
!5608 = !DISubprogram(name: "ldexp", scope: !5575, file: !5575, line: 101, type: !5609, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5609 = !DISubroutineType(types: !5610)
!5610 = !{!5578, !5578, !324}
!5611 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5612, file: !5579, line: 334)
!5612 = !DISubprogram(name: "log", scope: !5575, file: !5575, line: 104, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5613 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5614, file: !5579, line: 353)
!5614 = !DISubprogram(name: "log10", scope: !5575, file: !5575, line: 107, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5615 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5616, file: !5579, line: 372)
!5616 = !DISubprogram(name: "modf", scope: !5575, file: !5575, line: 110, type: !5617, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5617 = !DISubroutineType(types: !5618)
!5618 = !{!5578, !5578, !5619}
!5619 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !5578, size: 64)
!5620 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5621, file: !5579, line: 384)
!5621 = !DISubprogram(name: "pow", scope: !5575, file: !5575, line: 140, type: !5586, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5622 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5623, file: !5579, line: 421)
!5623 = !DISubprogram(name: "sin", scope: !5575, file: !5575, line: 64, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5624 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5625, file: !5579, line: 440)
!5625 = !DISubprogram(name: "sinh", scope: !5575, file: !5575, line: 73, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5626 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5627, file: !5579, line: 459)
!5627 = !DISubprogram(name: "sqrt", scope: !5575, file: !5575, line: 143, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5628 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5629, file: !5579, line: 478)
!5629 = !DISubprogram(name: "tan", scope: !5575, file: !5575, line: 66, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5630 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5631, file: !5579, line: 497)
!5631 = !DISubprogram(name: "tanh", scope: !5575, file: !5575, line: 75, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5632 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5633, file: !5579, line: 1065)
!5633 = !DIDerivedType(tag: DW_TAG_typedef, name: "double_t", file: !5634, line: 150, baseType: !5578)
!5634 = !DIFile(filename: "/usr/include/math.h", directory: "", checksumkind: CSK_MD5, checksum: "ecf196918078d683ff91ad9a1c51599a")
!5635 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5636, file: !5579, line: 1066)
!5636 = !DIDerivedType(tag: DW_TAG_typedef, name: "float_t", file: !5634, line: 149, baseType: !5637)
!5637 = !DIBasicType(name: "float", size: 32, encoding: DW_ATE_float)
!5638 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5639, file: !5579, line: 1069)
!5639 = !DISubprogram(name: "acosh", scope: !5575, file: !5575, line: 85, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5640 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5641, file: !5579, line: 1070)
!5641 = !DISubprogram(name: "acoshf", scope: !5575, file: !5575, line: 85, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5642 = !DISubroutineType(types: !5643)
!5643 = !{!5637, !5637}
!5644 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5645, file: !5579, line: 1071)
!5645 = !DISubprogram(name: "acoshl", scope: !5575, file: !5575, line: 85, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5646 = !DISubroutineType(types: !5647)
!5647 = !{!5648, !5648}
!5648 = !DIBasicType(name: "long double", size: 128, encoding: DW_ATE_float)
!5649 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5650, file: !5579, line: 1073)
!5650 = !DISubprogram(name: "asinh", scope: !5575, file: !5575, line: 87, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5651 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5652, file: !5579, line: 1074)
!5652 = !DISubprogram(name: "asinhf", scope: !5575, file: !5575, line: 87, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5653 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5654, file: !5579, line: 1075)
!5654 = !DISubprogram(name: "asinhl", scope: !5575, file: !5575, line: 87, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5655 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5656, file: !5579, line: 1077)
!5656 = !DISubprogram(name: "atanh", scope: !5575, file: !5575, line: 89, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5657 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5658, file: !5579, line: 1078)
!5658 = !DISubprogram(name: "atanhf", scope: !5575, file: !5575, line: 89, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5659 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5660, file: !5579, line: 1079)
!5660 = !DISubprogram(name: "atanhl", scope: !5575, file: !5575, line: 89, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5661 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5662, file: !5579, line: 1081)
!5662 = !DISubprogram(name: "cbrt", scope: !5575, file: !5575, line: 152, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5663 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5664, file: !5579, line: 1082)
!5664 = !DISubprogram(name: "cbrtf", scope: !5575, file: !5575, line: 152, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5665 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5666, file: !5579, line: 1083)
!5666 = !DISubprogram(name: "cbrtl", scope: !5575, file: !5575, line: 152, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5667 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5668, file: !5579, line: 1085)
!5668 = !DISubprogram(name: "copysign", scope: !5575, file: !5575, line: 196, type: !5586, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5669 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5670, file: !5579, line: 1086)
!5670 = !DISubprogram(name: "copysignf", scope: !5575, file: !5575, line: 196, type: !5671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5671 = !DISubroutineType(types: !5672)
!5672 = !{!5637, !5637, !5637}
!5673 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5674, file: !5579, line: 1087)
!5674 = !DISubprogram(name: "copysignl", scope: !5575, file: !5575, line: 196, type: !5675, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5675 = !DISubroutineType(types: !5676)
!5676 = !{!5648, !5648, !5648}
!5677 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5678, file: !5579, line: 1089)
!5678 = !DISubprogram(name: "erf", scope: !5575, file: !5575, line: 228, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5679 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5680, file: !5579, line: 1090)
!5680 = !DISubprogram(name: "erff", scope: !5575, file: !5575, line: 228, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5681 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5682, file: !5579, line: 1091)
!5682 = !DISubprogram(name: "erfl", scope: !5575, file: !5575, line: 228, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5683 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5684, file: !5579, line: 1093)
!5684 = !DISubprogram(name: "erfc", scope: !5575, file: !5575, line: 229, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5685 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5686, file: !5579, line: 1094)
!5686 = !DISubprogram(name: "erfcf", scope: !5575, file: !5575, line: 229, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5687 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5688, file: !5579, line: 1095)
!5688 = !DISubprogram(name: "erfcl", scope: !5575, file: !5575, line: 229, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5689 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5690, file: !5579, line: 1097)
!5690 = !DISubprogram(name: "exp2", scope: !5575, file: !5575, line: 130, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5691 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5692, file: !5579, line: 1098)
!5692 = !DISubprogram(name: "exp2f", scope: !5575, file: !5575, line: 130, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5693 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5694, file: !5579, line: 1099)
!5694 = !DISubprogram(name: "exp2l", scope: !5575, file: !5575, line: 130, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5695 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5696, file: !5579, line: 1101)
!5696 = !DISubprogram(name: "expm1", scope: !5575, file: !5575, line: 119, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5697 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5698, file: !5579, line: 1102)
!5698 = !DISubprogram(name: "expm1f", scope: !5575, file: !5575, line: 119, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5699 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5700, file: !5579, line: 1103)
!5700 = !DISubprogram(name: "expm1l", scope: !5575, file: !5575, line: 119, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5701 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5702, file: !5579, line: 1105)
!5702 = !DISubprogram(name: "fdim", scope: !5575, file: !5575, line: 326, type: !5586, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5703 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5704, file: !5579, line: 1106)
!5704 = !DISubprogram(name: "fdimf", scope: !5575, file: !5575, line: 326, type: !5671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5705 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5706, file: !5579, line: 1107)
!5706 = !DISubprogram(name: "fdiml", scope: !5575, file: !5575, line: 326, type: !5675, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5707 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5708, file: !5579, line: 1109)
!5708 = !DISubprogram(name: "fma", scope: !5575, file: !5575, line: 335, type: !5709, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5709 = !DISubroutineType(types: !5710)
!5710 = !{!5578, !5578, !5578, !5578}
!5711 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5712, file: !5579, line: 1110)
!5712 = !DISubprogram(name: "fmaf", scope: !5575, file: !5575, line: 335, type: !5713, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5713 = !DISubroutineType(types: !5714)
!5714 = !{!5637, !5637, !5637, !5637}
!5715 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5716, file: !5579, line: 1111)
!5716 = !DISubprogram(name: "fmal", scope: !5575, file: !5575, line: 335, type: !5717, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5717 = !DISubroutineType(types: !5718)
!5718 = !{!5648, !5648, !5648, !5648}
!5719 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5720, file: !5579, line: 1113)
!5720 = !DISubprogram(name: "fmax", scope: !5575, file: !5575, line: 329, type: !5586, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5721 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5722, file: !5579, line: 1114)
!5722 = !DISubprogram(name: "fmaxf", scope: !5575, file: !5575, line: 329, type: !5671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5723 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5724, file: !5579, line: 1115)
!5724 = !DISubprogram(name: "fmaxl", scope: !5575, file: !5575, line: 329, type: !5675, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5725 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5726, file: !5579, line: 1117)
!5726 = !DISubprogram(name: "fmin", scope: !5575, file: !5575, line: 332, type: !5586, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5727 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5728, file: !5579, line: 1118)
!5728 = !DISubprogram(name: "fminf", scope: !5575, file: !5575, line: 332, type: !5671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5729 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5730, file: !5579, line: 1119)
!5730 = !DISubprogram(name: "fminl", scope: !5575, file: !5575, line: 332, type: !5675, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5731 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5732, file: !5579, line: 1121)
!5732 = !DISubprogram(name: "hypot", scope: !5575, file: !5575, line: 147, type: !5586, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5733 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5734, file: !5579, line: 1122)
!5734 = !DISubprogram(name: "hypotf", scope: !5575, file: !5575, line: 147, type: !5671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5735 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5736, file: !5579, line: 1123)
!5736 = !DISubprogram(name: "hypotl", scope: !5575, file: !5575, line: 147, type: !5675, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5737 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5738, file: !5579, line: 1125)
!5738 = !DISubprogram(name: "ilogb", scope: !5575, file: !5575, line: 280, type: !5739, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5739 = !DISubroutineType(types: !5740)
!5740 = !{!324, !5578}
!5741 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5742, file: !5579, line: 1126)
!5742 = !DISubprogram(name: "ilogbf", scope: !5575, file: !5575, line: 280, type: !5743, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5743 = !DISubroutineType(types: !5744)
!5744 = !{!324, !5637}
!5745 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5746, file: !5579, line: 1127)
!5746 = !DISubprogram(name: "ilogbl", scope: !5575, file: !5575, line: 280, type: !5747, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5747 = !DISubroutineType(types: !5748)
!5748 = !{!324, !5648}
!5749 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5750, file: !5579, line: 1129)
!5750 = !DISubprogram(name: "lgamma", scope: !5575, file: !5575, line: 230, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5751 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5752, file: !5579, line: 1130)
!5752 = !DISubprogram(name: "lgammaf", scope: !5575, file: !5575, line: 230, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5753 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5754, file: !5579, line: 1131)
!5754 = !DISubprogram(name: "lgammal", scope: !5575, file: !5575, line: 230, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5755 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5756, file: !5579, line: 1134)
!5756 = !DISubprogram(name: "llrint", scope: !5575, file: !5575, line: 316, type: !5757, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5757 = !DISubroutineType(types: !5758)
!5758 = !{!5759, !5578}
!5759 = !DIBasicType(name: "long long", size: 64, encoding: DW_ATE_signed)
!5760 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5761, file: !5579, line: 1135)
!5761 = !DISubprogram(name: "llrintf", scope: !5575, file: !5575, line: 316, type: !5762, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5762 = !DISubroutineType(types: !5763)
!5763 = !{!5759, !5637}
!5764 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5765, file: !5579, line: 1136)
!5765 = !DISubprogram(name: "llrintl", scope: !5575, file: !5575, line: 316, type: !5766, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5766 = !DISubroutineType(types: !5767)
!5767 = !{!5759, !5648}
!5768 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5769, file: !5579, line: 1138)
!5769 = !DISubprogram(name: "llround", scope: !5575, file: !5575, line: 322, type: !5757, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5770 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5771, file: !5579, line: 1139)
!5771 = !DISubprogram(name: "llroundf", scope: !5575, file: !5575, line: 322, type: !5762, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5772 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5773, file: !5579, line: 1140)
!5773 = !DISubprogram(name: "llroundl", scope: !5575, file: !5575, line: 322, type: !5766, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5774 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5775, file: !5579, line: 1143)
!5775 = !DISubprogram(name: "log1p", scope: !5575, file: !5575, line: 122, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5776 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5777, file: !5579, line: 1144)
!5777 = !DISubprogram(name: "log1pf", scope: !5575, file: !5575, line: 122, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5778 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5779, file: !5579, line: 1145)
!5779 = !DISubprogram(name: "log1pl", scope: !5575, file: !5575, line: 122, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5780 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5781, file: !5579, line: 1147)
!5781 = !DISubprogram(name: "log2", scope: !5575, file: !5575, line: 133, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5782 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5783, file: !5579, line: 1148)
!5783 = !DISubprogram(name: "log2f", scope: !5575, file: !5575, line: 133, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5784 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5785, file: !5579, line: 1149)
!5785 = !DISubprogram(name: "log2l", scope: !5575, file: !5575, line: 133, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5786 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5787, file: !5579, line: 1151)
!5787 = !DISubprogram(name: "logb", scope: !5575, file: !5575, line: 125, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5788 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5789, file: !5579, line: 1152)
!5789 = !DISubprogram(name: "logbf", scope: !5575, file: !5575, line: 125, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5790 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5791, file: !5579, line: 1153)
!5791 = !DISubprogram(name: "logbl", scope: !5575, file: !5575, line: 125, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5792 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5793, file: !5579, line: 1155)
!5793 = !DISubprogram(name: "lrint", scope: !5575, file: !5575, line: 314, type: !5794, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5794 = !DISubroutineType(types: !5795)
!5795 = !{!1837, !5578}
!5796 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5797, file: !5579, line: 1156)
!5797 = !DISubprogram(name: "lrintf", scope: !5575, file: !5575, line: 314, type: !5798, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5798 = !DISubroutineType(types: !5799)
!5799 = !{!1837, !5637}
!5800 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5801, file: !5579, line: 1157)
!5801 = !DISubprogram(name: "lrintl", scope: !5575, file: !5575, line: 314, type: !5802, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5802 = !DISubroutineType(types: !5803)
!5803 = !{!1837, !5648}
!5804 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5805, file: !5579, line: 1159)
!5805 = !DISubprogram(name: "lround", scope: !5575, file: !5575, line: 320, type: !5794, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5806 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5807, file: !5579, line: 1160)
!5807 = !DISubprogram(name: "lroundf", scope: !5575, file: !5575, line: 320, type: !5798, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5808 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5809, file: !5579, line: 1161)
!5809 = !DISubprogram(name: "lroundl", scope: !5575, file: !5575, line: 320, type: !5802, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5810 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5811, file: !5579, line: 1163)
!5811 = !DISubprogram(name: "nan", scope: !5575, file: !5575, line: 201, type: !5812, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5812 = !DISubroutineType(types: !5813)
!5813 = !{!5578, !407}
!5814 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5815, file: !5579, line: 1164)
!5815 = !DISubprogram(name: "nanf", scope: !5575, file: !5575, line: 201, type: !5816, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5816 = !DISubroutineType(types: !5817)
!5817 = !{!5637, !407}
!5818 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5819, file: !5579, line: 1165)
!5819 = !DISubprogram(name: "nanl", scope: !5575, file: !5575, line: 201, type: !5820, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5820 = !DISubroutineType(types: !5821)
!5821 = !{!5648, !407}
!5822 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5823, file: !5579, line: 1167)
!5823 = !DISubprogram(name: "nearbyint", scope: !5575, file: !5575, line: 294, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5824 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5825, file: !5579, line: 1168)
!5825 = !DISubprogram(name: "nearbyintf", scope: !5575, file: !5575, line: 294, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5826 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5827, file: !5579, line: 1169)
!5827 = !DISubprogram(name: "nearbyintl", scope: !5575, file: !5575, line: 294, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5828 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5829, file: !5579, line: 1171)
!5829 = !DISubprogram(name: "nextafter", scope: !5575, file: !5575, line: 259, type: !5586, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5830 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5831, file: !5579, line: 1172)
!5831 = !DISubprogram(name: "nextafterf", scope: !5575, file: !5575, line: 259, type: !5671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5832 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5833, file: !5579, line: 1173)
!5833 = !DISubprogram(name: "nextafterl", scope: !5575, file: !5575, line: 259, type: !5675, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5834 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5835, file: !5579, line: 1175)
!5835 = !DISubprogram(name: "nexttoward", scope: !5575, file: !5575, line: 261, type: !5836, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5836 = !DISubroutineType(types: !5837)
!5837 = !{!5578, !5578, !5648}
!5838 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5839, file: !5579, line: 1176)
!5839 = !DISubprogram(name: "nexttowardf", scope: !5575, file: !5575, line: 261, type: !5840, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5840 = !DISubroutineType(types: !5841)
!5841 = !{!5637, !5637, !5648}
!5842 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5843, file: !5579, line: 1177)
!5843 = !DISubprogram(name: "nexttowardl", scope: !5575, file: !5575, line: 261, type: !5675, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5844 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5845, file: !5579, line: 1179)
!5845 = !DISubprogram(name: "remainder", scope: !5575, file: !5575, line: 272, type: !5586, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5846 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5847, file: !5579, line: 1180)
!5847 = !DISubprogram(name: "remainderf", scope: !5575, file: !5575, line: 272, type: !5671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5848 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5849, file: !5579, line: 1181)
!5849 = !DISubprogram(name: "remainderl", scope: !5575, file: !5575, line: 272, type: !5675, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5850 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5851, file: !5579, line: 1183)
!5851 = !DISubprogram(name: "remquo", scope: !5575, file: !5575, line: 307, type: !5852, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5852 = !DISubroutineType(types: !5853)
!5853 = !{!5578, !5578, !5578, !5606}
!5854 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5855, file: !5579, line: 1184)
!5855 = !DISubprogram(name: "remquof", scope: !5575, file: !5575, line: 307, type: !5856, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5856 = !DISubroutineType(types: !5857)
!5857 = !{!5637, !5637, !5637, !5606}
!5858 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5859, file: !5579, line: 1185)
!5859 = !DISubprogram(name: "remquol", scope: !5575, file: !5575, line: 307, type: !5860, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5860 = !DISubroutineType(types: !5861)
!5861 = !{!5648, !5648, !5648, !5606}
!5862 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5863, file: !5579, line: 1187)
!5863 = !DISubprogram(name: "rint", scope: !5575, file: !5575, line: 256, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5864 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5865, file: !5579, line: 1188)
!5865 = !DISubprogram(name: "rintf", scope: !5575, file: !5575, line: 256, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5866 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5867, file: !5579, line: 1189)
!5867 = !DISubprogram(name: "rintl", scope: !5575, file: !5575, line: 256, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5868 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5869, file: !5579, line: 1191)
!5869 = !DISubprogram(name: "round", scope: !5575, file: !5575, line: 298, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5870 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5871, file: !5579, line: 1192)
!5871 = !DISubprogram(name: "roundf", scope: !5575, file: !5575, line: 298, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5872 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5873, file: !5579, line: 1193)
!5873 = !DISubprogram(name: "roundl", scope: !5575, file: !5575, line: 298, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5874 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5875, file: !5579, line: 1195)
!5875 = !DISubprogram(name: "scalbln", scope: !5575, file: !5575, line: 290, type: !5876, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5876 = !DISubroutineType(types: !5877)
!5877 = !{!5578, !5578, !1837}
!5878 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5879, file: !5579, line: 1196)
!5879 = !DISubprogram(name: "scalblnf", scope: !5575, file: !5575, line: 290, type: !5880, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5880 = !DISubroutineType(types: !5881)
!5881 = !{!5637, !5637, !1837}
!5882 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5883, file: !5579, line: 1197)
!5883 = !DISubprogram(name: "scalblnl", scope: !5575, file: !5575, line: 290, type: !5884, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5884 = !DISubroutineType(types: !5885)
!5885 = !{!5648, !5648, !1837}
!5886 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5887, file: !5579, line: 1199)
!5887 = !DISubprogram(name: "scalbn", scope: !5575, file: !5575, line: 276, type: !5609, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5888 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5889, file: !5579, line: 1200)
!5889 = !DISubprogram(name: "scalbnf", scope: !5575, file: !5575, line: 276, type: !5890, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5890 = !DISubroutineType(types: !5891)
!5891 = !{!5637, !5637, !324}
!5892 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5893, file: !5579, line: 1201)
!5893 = !DISubprogram(name: "scalbnl", scope: !5575, file: !5575, line: 276, type: !5894, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5894 = !DISubroutineType(types: !5895)
!5895 = !{!5648, !5648, !324}
!5896 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5897, file: !5579, line: 1203)
!5897 = !DISubprogram(name: "tgamma", scope: !5575, file: !5575, line: 235, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5898 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5899, file: !5579, line: 1204)
!5899 = !DISubprogram(name: "tgammaf", scope: !5575, file: !5575, line: 235, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5900 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5901, file: !5579, line: 1205)
!5901 = !DISubprogram(name: "tgammal", scope: !5575, file: !5575, line: 235, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5902 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5903, file: !5579, line: 1207)
!5903 = !DISubprogram(name: "trunc", scope: !5575, file: !5575, line: 302, type: !5576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5904 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5905, file: !5579, line: 1208)
!5905 = !DISubprogram(name: "truncf", scope: !5575, file: !5575, line: 302, type: !5642, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5906 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5907, file: !5579, line: 1209)
!5907 = !DISubprogram(name: "truncl", scope: !5575, file: !5575, line: 302, type: !5646, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5908 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5909, file: !5912, line: 56)
!5909 = !DIDerivedType(tag: DW_TAG_typedef, name: "max_align_t", file: !5910, line: 24, baseType: !5911)
!5910 = !DIFile(filename: "llvm5/build/lib/clang/15.0.3/include/__stddef_max_align_t.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "48e8e2456f77e6cda35d245130fa7259")
!5911 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !5910, line: 19, size: 256, flags: DIFlagFwdDecl, identifier: "_ZTS11max_align_t")
!5912 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstddef", directory: "")
!5913 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !14, entity: !1578, file: !341, line: 63)
!5914 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !14, entity: !5915, file: !341, line: 64)
!5915 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Twine", scope: !342, file: !341, line: 30, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm5TwineE")
!5916 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !14, entity: !5917, file: !341, line: 76)
!5917 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "RefCountedBaseVPTR", scope: !342, file: !341, line: 45, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm18RefCountedBaseVPTRE")
!5918 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !14, entity: !340, file: !341, line: 78)
!5919 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5920, file: !5924, line: 75)
!5920 = !DISubprogram(name: "memchr", scope: !5921, file: !5921, line: 90, type: !5922, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5921 = !DIFile(filename: "/usr/include/string.h", directory: "", checksumkind: CSK_MD5, checksum: "1029a2d94b0e7b73f8dbf87ca20ab7bc")
!5922 = !DISubroutineType(types: !5923)
!5923 = !{!330, !334, !324, !1583}
!5924 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstring", directory: "")
!5925 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5926, file: !5924, line: 76)
!5926 = !DISubprogram(name: "memcmp", scope: !5921, file: !5921, line: 63, type: !5927, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5927 = !DISubroutineType(types: !5928)
!5928 = !{!324, !334, !334, !1583}
!5929 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5930, file: !5924, line: 77)
!5930 = !DISubprogram(name: "memcpy", scope: !5921, file: !5921, line: 42, type: !5931, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5931 = !DISubroutineType(types: !5932)
!5932 = !{!330, !5933, !5934, !1583}
!5933 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !330)
!5934 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !334)
!5935 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5936, file: !5924, line: 78)
!5936 = !DISubprogram(name: "memmove", scope: !5921, file: !5921, line: 46, type: !5937, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5937 = !DISubroutineType(types: !5938)
!5938 = !{!330, !330, !334, !1583}
!5939 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5940, file: !5924, line: 79)
!5940 = !DISubprogram(name: "memset", scope: !5921, file: !5921, line: 60, type: !5941, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5941 = !DISubroutineType(types: !5942)
!5942 = !{!330, !330, !324, !1583}
!5943 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5944, file: !5924, line: 80)
!5944 = !DISubprogram(name: "strcat", scope: !5921, file: !5921, line: 129, type: !5945, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5945 = !DISubroutineType(types: !5946)
!5946 = !{!373, !5947, !5948}
!5947 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !373)
!5948 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !407)
!5949 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5950, file: !5924, line: 81)
!5950 = !DISubprogram(name: "strcmp", scope: !5921, file: !5921, line: 136, type: !5951, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5951 = !DISubroutineType(types: !5952)
!5952 = !{!324, !407, !407}
!5953 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5954, file: !5924, line: 82)
!5954 = !DISubprogram(name: "strcoll", scope: !5921, file: !5921, line: 143, type: !5951, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5955 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5956, file: !5924, line: 83)
!5956 = !DISubprogram(name: "strcpy", scope: !5921, file: !5921, line: 121, type: !5945, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5957 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5958, file: !5924, line: 84)
!5958 = !DISubprogram(name: "strcspn", scope: !5921, file: !5921, line: 272, type: !5959, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5959 = !DISubroutineType(types: !5960)
!5960 = !{!1583, !407, !407}
!5961 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5962, file: !5924, line: 85)
!5962 = !DISubprogram(name: "strerror", scope: !5921, file: !5921, line: 396, type: !5963, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5963 = !DISubroutineType(types: !5964)
!5964 = !{!373, !324}
!5965 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5966, file: !5924, line: 86)
!5966 = !DISubprogram(name: "strlen", scope: !5921, file: !5921, line: 384, type: !5967, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5967 = !DISubroutineType(types: !5968)
!5968 = !{!1583, !407}
!5969 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5970, file: !5924, line: 87)
!5970 = !DISubprogram(name: "strncat", scope: !5921, file: !5921, line: 132, type: !5971, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5971 = !DISubroutineType(types: !5972)
!5972 = !{!373, !5947, !5948, !1583}
!5973 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5974, file: !5924, line: 88)
!5974 = !DISubprogram(name: "strncmp", scope: !5921, file: !5921, line: 139, type: !1592, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5975 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5976, file: !5924, line: 89)
!5976 = !DISubprogram(name: "strncpy", scope: !5921, file: !5921, line: 124, type: !5971, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5977 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5978, file: !5924, line: 90)
!5978 = !DISubprogram(name: "strspn", scope: !5921, file: !5921, line: 276, type: !5959, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5979 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5980, file: !5924, line: 91)
!5980 = !DISubprogram(name: "strtok", scope: !5921, file: !5921, line: 335, type: !5945, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5981 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5982, file: !5924, line: 92)
!5982 = !DISubprogram(name: "strxfrm", scope: !5921, file: !5921, line: 146, type: !5983, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5983 = !DISubroutineType(types: !5984)
!5984 = !{!1583, !5947, !5948, !1583}
!5985 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5986, file: !5924, line: 93)
!5986 = !DISubprogram(name: "strchr", scope: !5921, file: !5921, line: 225, type: !5987, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5987 = !DISubroutineType(types: !5988)
!5988 = !{!373, !407, !324}
!5989 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5990, file: !5924, line: 94)
!5990 = !DISubprogram(name: "strpbrk", scope: !5921, file: !5921, line: 302, type: !5991, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5991 = !DISubroutineType(types: !5992)
!5992 = !{!373, !407, !407}
!5993 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5994, file: !5924, line: 95)
!5994 = !DISubprogram(name: "strrchr", scope: !5921, file: !5921, line: 252, type: !5987, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5995 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !5996, file: !5924, line: 96)
!5996 = !DISubprogram(name: "strstr", scope: !5921, file: !5921, line: 329, type: !5991, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!5997 = !DIImportedEntity(tag: DW_TAG_imported_module, scope: !5998, entity: !5999, file: !6000, line: 58)
!5998 = !DINamespace(name: "__gnu_debug", scope: null)
!5999 = !DINamespace(name: "__debug", scope: !353)
!6000 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/debug/debug.h", directory: "", checksumkind: CSK_MD5, checksum: "0d648599b52b1d377b1fee4a0a4b2b91")
!6001 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6002, file: !6003, line: 57)
!6002 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "exception_ptr", scope: !6004, file: !6003, line: 79, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSNSt15__exception_ptr13exception_ptrE")
!6003 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/exception_ptr.h", directory: "", checksumkind: CSK_MD5, checksum: "25d44782b686509a9fc5c8aaa8066643")
!6004 = !DINamespace(name: "__exception_ptr", scope: !353)
!6005 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !6004, entity: !6006, file: !6003, line: 73)
!6006 = !DISubprogram(name: "rethrow_exception", linkageName: "_ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE", scope: !353, file: !6003, line: 69, type: !6007, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!6007 = !DISubroutineType(types: !6008)
!6008 = !{null, !6002}
!6009 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !415, file: !384, line: 44)
!6010 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3065, file: !384, line: 45)
!6011 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6012, file: !6024, line: 64)
!6012 = !DIDerivedType(tag: DW_TAG_typedef, name: "mbstate_t", file: !6013, line: 6, baseType: !6014)
!6013 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/mbstate_t.h", directory: "", checksumkind: CSK_MD5, checksum: "ba8742313715e20e434cf6ccb2db98e3")
!6014 = !DIDerivedType(tag: DW_TAG_typedef, name: "__mbstate_t", file: !6015, line: 21, baseType: !6016)
!6015 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h", directory: "", checksumkind: CSK_MD5, checksum: "82911a3e689448e3691ded3e0b471a55")
!6016 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !6015, line: 13, size: 64, flags: DIFlagTypePassByValue, elements: !6017, identifier: "_ZTS11__mbstate_t")
!6017 = !{!6018, !6019}
!6018 = !DIDerivedType(tag: DW_TAG_member, name: "__count", scope: !6016, file: !6015, line: 15, baseType: !324, size: 32)
!6019 = !DIDerivedType(tag: DW_TAG_member, name: "__value", scope: !6016, file: !6015, line: 20, baseType: !6020, size: 32, offset: 32)
!6020 = distinct !DICompositeType(tag: DW_TAG_union_type, scope: !6016, file: !6015, line: 16, size: 32, flags: DIFlagTypePassByValue, elements: !6021, identifier: "_ZTSN11__mbstate_tUt_E")
!6021 = !{!6022, !6023}
!6022 = !DIDerivedType(tag: DW_TAG_member, name: "__wch", scope: !6020, file: !6015, line: 18, baseType: !6, size: 32)
!6023 = !DIDerivedType(tag: DW_TAG_member, name: "__wchb", scope: !6020, file: !6015, line: 19, baseType: !2106, size: 32)
!6024 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cwchar", directory: "")
!6025 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6026, file: !6024, line: 139)
!6026 = !DIDerivedType(tag: DW_TAG_typedef, name: "wint_t", file: !6027, line: 20, baseType: !6)
!6027 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/wint_t.h", directory: "", checksumkind: CSK_MD5, checksum: "aa31b53ef28dc23152ceb41e2763ded3")
!6028 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6029, file: !6024, line: 141)
!6029 = !DISubprogram(name: "btowc", scope: !6030, file: !6030, line: 318, type: !6031, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6030 = !DIFile(filename: "/usr/include/wchar.h", directory: "", checksumkind: CSK_MD5, checksum: "5c0512b032e303d7adfb2a47454ecb1c")
!6031 = !DISubroutineType(types: !6032)
!6032 = !{!6026, !324}
!6033 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6034, file: !6024, line: 142)
!6034 = !DISubprogram(name: "fgetwc", scope: !6030, file: !6030, line: 727, type: !6035, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6035 = !DISubroutineType(types: !6036)
!6036 = !{!6026, !6037}
!6037 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6038, size: 64)
!6038 = !DIDerivedType(tag: DW_TAG_typedef, name: "__FILE", file: !6039, line: 5, baseType: !6040)
!6039 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h", directory: "", checksumkind: CSK_MD5, checksum: "72a8fe90981f484acae7c6f3dfc5c2b7")
!6040 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_IO_FILE", file: !6041, line: 245, size: 1728, flags: DIFlagTypePassByValue, elements: !6042, identifier: "_ZTS8_IO_FILE")
!6041 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/libio.h", directory: "", checksumkind: CSK_MD5, checksum: "e2b53e448ab24b9cd2ba8684267b8131")
!6042 = !{!6043, !6044, !6045, !6046, !6047, !6048, !6049, !6050, !6051, !6052, !6053, !6054, !6055, !6058, !6060, !6061, !6062, !6064, !6065, !6067, !6068, !6071, !6073, !6074, !6075, !6076, !6077, !6078, !6079}
!6043 = !DIDerivedType(tag: DW_TAG_member, name: "_flags", scope: !6040, file: !6041, line: 246, baseType: !324, size: 32)
!6044 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_ptr", scope: !6040, file: !6041, line: 251, baseType: !373, size: 64, offset: 64)
!6045 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_end", scope: !6040, file: !6041, line: 252, baseType: !373, size: 64, offset: 128)
!6046 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_base", scope: !6040, file: !6041, line: 253, baseType: !373, size: 64, offset: 192)
!6047 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_base", scope: !6040, file: !6041, line: 254, baseType: !373, size: 64, offset: 256)
!6048 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_ptr", scope: !6040, file: !6041, line: 255, baseType: !373, size: 64, offset: 320)
!6049 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_end", scope: !6040, file: !6041, line: 256, baseType: !373, size: 64, offset: 384)
!6050 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_buf_base", scope: !6040, file: !6041, line: 257, baseType: !373, size: 64, offset: 448)
!6051 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_buf_end", scope: !6040, file: !6041, line: 258, baseType: !373, size: 64, offset: 512)
!6052 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_save_base", scope: !6040, file: !6041, line: 260, baseType: !373, size: 64, offset: 576)
!6053 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_backup_base", scope: !6040, file: !6041, line: 261, baseType: !373, size: 64, offset: 640)
!6054 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_save_end", scope: !6040, file: !6041, line: 262, baseType: !373, size: 64, offset: 704)
!6055 = !DIDerivedType(tag: DW_TAG_member, name: "_markers", scope: !6040, file: !6041, line: 264, baseType: !6056, size: 64, offset: 768)
!6056 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6057, size: 64)
!6057 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_IO_marker", file: !6041, line: 160, size: 192, flags: DIFlagFwdDecl, identifier: "_ZTS10_IO_marker")
!6058 = !DIDerivedType(tag: DW_TAG_member, name: "_chain", scope: !6040, file: !6041, line: 266, baseType: !6059, size: 64, offset: 832)
!6059 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6040, size: 64)
!6060 = !DIDerivedType(tag: DW_TAG_member, name: "_fileno", scope: !6040, file: !6041, line: 268, baseType: !324, size: 32, offset: 896)
!6061 = !DIDerivedType(tag: DW_TAG_member, name: "_flags2", scope: !6040, file: !6041, line: 272, baseType: !324, size: 32, offset: 928)
!6062 = !DIDerivedType(tag: DW_TAG_member, name: "_old_offset", scope: !6040, file: !6041, line: 274, baseType: !6063, size: 64, offset: 960)
!6063 = !DIDerivedType(tag: DW_TAG_typedef, name: "__off_t", file: !4714, line: 140, baseType: !1837)
!6064 = !DIDerivedType(tag: DW_TAG_member, name: "_cur_column", scope: !6040, file: !6041, line: 278, baseType: !947, size: 16, offset: 1024)
!6065 = !DIDerivedType(tag: DW_TAG_member, name: "_vtable_offset", scope: !6040, file: !6041, line: 279, baseType: !6066, size: 8, offset: 1040)
!6066 = !DIBasicType(name: "signed char", size: 8, encoding: DW_ATE_signed_char)
!6067 = !DIDerivedType(tag: DW_TAG_member, name: "_shortbuf", scope: !6040, file: !6041, line: 280, baseType: !2290, size: 8, offset: 1048)
!6068 = !DIDerivedType(tag: DW_TAG_member, name: "_lock", scope: !6040, file: !6041, line: 284, baseType: !6069, size: 64, offset: 1088)
!6069 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6070, size: 64)
!6070 = !DIDerivedType(tag: DW_TAG_typedef, name: "_IO_lock_t", file: !6041, line: 154, baseType: null)
!6071 = !DIDerivedType(tag: DW_TAG_member, name: "_offset", scope: !6040, file: !6041, line: 293, baseType: !6072, size: 64, offset: 1152)
!6072 = !DIDerivedType(tag: DW_TAG_typedef, name: "__off64_t", file: !4714, line: 141, baseType: !1837)
!6073 = !DIDerivedType(tag: DW_TAG_member, name: "__pad1", scope: !6040, file: !6041, line: 301, baseType: !330, size: 64, offset: 1216)
!6074 = !DIDerivedType(tag: DW_TAG_member, name: "__pad2", scope: !6040, file: !6041, line: 302, baseType: !330, size: 64, offset: 1280)
!6075 = !DIDerivedType(tag: DW_TAG_member, name: "__pad3", scope: !6040, file: !6041, line: 303, baseType: !330, size: 64, offset: 1344)
!6076 = !DIDerivedType(tag: DW_TAG_member, name: "__pad4", scope: !6040, file: !6041, line: 304, baseType: !330, size: 64, offset: 1408)
!6077 = !DIDerivedType(tag: DW_TAG_member, name: "__pad5", scope: !6040, file: !6041, line: 306, baseType: !1583, size: 64, offset: 1472)
!6078 = !DIDerivedType(tag: DW_TAG_member, name: "_mode", scope: !6040, file: !6041, line: 307, baseType: !324, size: 32, offset: 1536)
!6079 = !DIDerivedType(tag: DW_TAG_member, name: "_unused2", scope: !6040, file: !6041, line: 309, baseType: !6080, size: 160, offset: 1568)
!6080 = !DICompositeType(tag: DW_TAG_array_type, baseType: !374, size: 160, elements: !4516)
!6081 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6082, file: !6024, line: 143)
!6082 = !DISubprogram(name: "fgetws", scope: !6030, file: !6030, line: 756, type: !6083, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6083 = !DISubroutineType(types: !6084)
!6084 = !{!6085, !6087, !324, !6088}
!6085 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6086, size: 64)
!6086 = !DIBasicType(name: "wchar_t", size: 32, encoding: DW_ATE_signed)
!6087 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6085)
!6088 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6037)
!6089 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6090, file: !6024, line: 144)
!6090 = !DISubprogram(name: "fputwc", scope: !6030, file: !6030, line: 741, type: !6091, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6091 = !DISubroutineType(types: !6092)
!6092 = !{!6026, !6086, !6037}
!6093 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6094, file: !6024, line: 145)
!6094 = !DISubprogram(name: "fputws", scope: !6030, file: !6030, line: 763, type: !6095, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6095 = !DISubroutineType(types: !6096)
!6096 = !{!324, !6097, !6088}
!6097 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6098)
!6098 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6099, size: 64)
!6099 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6086)
!6100 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6101, file: !6024, line: 146)
!6101 = !DISubprogram(name: "fwide", scope: !6030, file: !6030, line: 573, type: !6102, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6102 = !DISubroutineType(types: !6103)
!6103 = !{!324, !6037, !324}
!6104 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6105, file: !6024, line: 147)
!6105 = !DISubprogram(name: "fwprintf", scope: !6030, file: !6030, line: 580, type: !6106, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6106 = !DISubroutineType(types: !6107)
!6107 = !{!324, !6088, !6097, null}
!6108 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6109, file: !6024, line: 148)
!6109 = !DISubprogram(name: "fwscanf", scope: !6030, file: !6030, line: 621, type: !6106, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6110 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6111, file: !6024, line: 149)
!6111 = !DISubprogram(name: "getwc", scope: !6030, file: !6030, line: 728, type: !6035, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6112 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6113, file: !6024, line: 150)
!6113 = !DISubprogram(name: "getwchar", scope: !6030, file: !6030, line: 734, type: !6114, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6114 = !DISubroutineType(types: !6115)
!6115 = !{!6026}
!6116 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6117, file: !6024, line: 151)
!6117 = !DISubprogram(name: "mbrlen", scope: !6030, file: !6030, line: 329, type: !6118, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6118 = !DISubroutineType(types: !6119)
!6119 = !{!1583, !5948, !1583, !6120}
!6120 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6121)
!6121 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6012, size: 64)
!6122 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6123, file: !6024, line: 152)
!6123 = !DISubprogram(name: "mbrtowc", scope: !6030, file: !6030, line: 296, type: !6124, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6124 = !DISubroutineType(types: !6125)
!6125 = !{!1583, !6087, !5948, !1583, !6120}
!6126 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6127, file: !6024, line: 153)
!6127 = !DISubprogram(name: "mbsinit", scope: !6030, file: !6030, line: 292, type: !6128, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6128 = !DISubroutineType(types: !6129)
!6129 = !{!324, !6130}
!6130 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6131, size: 64)
!6131 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6012)
!6132 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6133, file: !6024, line: 154)
!6133 = !DISubprogram(name: "mbsrtowcs", scope: !6030, file: !6030, line: 337, type: !6134, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6134 = !DISubroutineType(types: !6135)
!6135 = !{!1583, !6087, !6136, !1583, !6120}
!6136 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6137)
!6137 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !407, size: 64)
!6138 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6139, file: !6024, line: 155)
!6139 = !DISubprogram(name: "putwc", scope: !6030, file: !6030, line: 742, type: !6091, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6140 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6141, file: !6024, line: 156)
!6141 = !DISubprogram(name: "putwchar", scope: !6030, file: !6030, line: 748, type: !6142, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6142 = !DISubroutineType(types: !6143)
!6143 = !{!6026, !6086}
!6144 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6145, file: !6024, line: 158)
!6145 = !DISubprogram(name: "swprintf", scope: !6030, file: !6030, line: 590, type: !6146, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6146 = !DISubroutineType(types: !6147)
!6147 = !{!324, !6087, !1583, !6097, null}
!6148 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6149, file: !6024, line: 160)
!6149 = !DISubprogram(name: "swscanf", scope: !6030, file: !6030, line: 631, type: !6150, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6150 = !DISubroutineType(types: !6151)
!6151 = !{!324, !6097, !6097, null}
!6152 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6153, file: !6024, line: 161)
!6153 = !DISubprogram(name: "ungetwc", scope: !6030, file: !6030, line: 771, type: !6154, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6154 = !DISubroutineType(types: !6155)
!6155 = !{!6026, !6026, !6037}
!6156 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6157, file: !6024, line: 162)
!6157 = !DISubprogram(name: "vfwprintf", scope: !6030, file: !6030, line: 598, type: !6158, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6158 = !DISubroutineType(types: !6159)
!6159 = !{!324, !6088, !6097, !6160}
!6160 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6161, size: 64)
!6161 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__va_list_tag", size: 192, flags: DIFlagTypePassByValue, elements: !6162, identifier: "_ZTS13__va_list_tag")
!6162 = !{!6163, !6165, !6166, !6167}
!6163 = !DIDerivedType(tag: DW_TAG_member, name: "gp_offset", scope: !6161, file: !6164, baseType: !6, size: 32)
!6164 = !DIFile(filename: "llvm34/projects/clang/lib/Lex/PPMacroExpansion.cpp", directory: "/fast/fs")
!6165 = !DIDerivedType(tag: DW_TAG_member, name: "fp_offset", scope: !6161, file: !6164, baseType: !6, size: 32, offset: 32)
!6166 = !DIDerivedType(tag: DW_TAG_member, name: "overflow_arg_area", scope: !6161, file: !6164, baseType: !330, size: 64, offset: 64)
!6167 = !DIDerivedType(tag: DW_TAG_member, name: "reg_save_area", scope: !6161, file: !6164, baseType: !330, size: 64, offset: 128)
!6168 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6169, file: !6024, line: 164)
!6169 = !DISubprogram(name: "vfwscanf", scope: !6030, file: !6030, line: 673, type: !6158, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6170 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6171, file: !6024, line: 167)
!6171 = !DISubprogram(name: "vswprintf", scope: !6030, file: !6030, line: 611, type: !6172, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6172 = !DISubroutineType(types: !6173)
!6173 = !{!324, !6087, !1583, !6097, !6160}
!6174 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6175, file: !6024, line: 170)
!6175 = !DISubprogram(name: "vswscanf", scope: !6030, file: !6030, line: 685, type: !6176, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6176 = !DISubroutineType(types: !6177)
!6177 = !{!324, !6097, !6097, !6160}
!6178 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6179, file: !6024, line: 172)
!6179 = !DISubprogram(name: "vwprintf", scope: !6030, file: !6030, line: 606, type: !6180, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6180 = !DISubroutineType(types: !6181)
!6181 = !{!324, !6097, !6160}
!6182 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6183, file: !6024, line: 174)
!6183 = !DISubprogram(name: "vwscanf", scope: !6030, file: !6030, line: 681, type: !6180, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6184 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6185, file: !6024, line: 176)
!6185 = !DISubprogram(name: "wcrtomb", scope: !6030, file: !6030, line: 301, type: !6186, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6186 = !DISubroutineType(types: !6187)
!6187 = !{!1583, !5947, !6086, !6120}
!6188 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6189, file: !6024, line: 177)
!6189 = !DISubprogram(name: "wcscat", scope: !6030, file: !6030, line: 97, type: !6190, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6190 = !DISubroutineType(types: !6191)
!6191 = !{!6085, !6087, !6097}
!6192 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6193, file: !6024, line: 178)
!6193 = !DISubprogram(name: "wcscmp", scope: !6030, file: !6030, line: 106, type: !6194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6194 = !DISubroutineType(types: !6195)
!6195 = !{!324, !6098, !6098}
!6196 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6197, file: !6024, line: 179)
!6197 = !DISubprogram(name: "wcscoll", scope: !6030, file: !6030, line: 131, type: !6194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6198 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6199, file: !6024, line: 180)
!6199 = !DISubprogram(name: "wcscpy", scope: !6030, file: !6030, line: 87, type: !6190, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6200 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6201, file: !6024, line: 181)
!6201 = !DISubprogram(name: "wcscspn", scope: !6030, file: !6030, line: 187, type: !6202, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6202 = !DISubroutineType(types: !6203)
!6203 = !{!1583, !6098, !6098}
!6204 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6205, file: !6024, line: 182)
!6205 = !DISubprogram(name: "wcsftime", scope: !6030, file: !6030, line: 835, type: !6206, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6206 = !DISubroutineType(types: !6207)
!6207 = !{!1583, !6087, !1583, !6097, !6208}
!6208 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6209)
!6209 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6210, size: 64)
!6210 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4717)
!6211 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6212, file: !6024, line: 183)
!6212 = !DISubprogram(name: "wcslen", scope: !6030, file: !6030, line: 222, type: !6213, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6213 = !DISubroutineType(types: !6214)
!6214 = !{!1583, !6098}
!6215 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6216, file: !6024, line: 184)
!6216 = !DISubprogram(name: "wcsncat", scope: !6030, file: !6030, line: 101, type: !6217, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6217 = !DISubroutineType(types: !6218)
!6218 = !{!6085, !6087, !6097, !1583}
!6219 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6220, file: !6024, line: 185)
!6220 = !DISubprogram(name: "wcsncmp", scope: !6030, file: !6030, line: 109, type: !6221, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6221 = !DISubroutineType(types: !6222)
!6222 = !{!324, !6098, !6098, !1583}
!6223 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6224, file: !6024, line: 186)
!6224 = !DISubprogram(name: "wcsncpy", scope: !6030, file: !6030, line: 92, type: !6217, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6225 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6226, file: !6024, line: 187)
!6226 = !DISubprogram(name: "wcsrtombs", scope: !6030, file: !6030, line: 343, type: !6227, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6227 = !DISubroutineType(types: !6228)
!6228 = !{!1583, !5947, !6229, !1583, !6120}
!6229 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6230)
!6230 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6098, size: 64)
!6231 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6232, file: !6024, line: 188)
!6232 = !DISubprogram(name: "wcsspn", scope: !6030, file: !6030, line: 191, type: !6202, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6233 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6234, file: !6024, line: 189)
!6234 = !DISubprogram(name: "wcstod", scope: !6030, file: !6030, line: 377, type: !6235, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6235 = !DISubroutineType(types: !6236)
!6236 = !{!5578, !6097, !6237}
!6237 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6238)
!6238 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6085, size: 64)
!6239 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6240, file: !6024, line: 191)
!6240 = !DISubprogram(name: "wcstof", scope: !6030, file: !6030, line: 382, type: !6241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6241 = !DISubroutineType(types: !6242)
!6242 = !{!5637, !6097, !6237}
!6243 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6244, file: !6024, line: 193)
!6244 = !DISubprogram(name: "wcstok", scope: !6030, file: !6030, line: 217, type: !6245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6245 = !DISubroutineType(types: !6246)
!6246 = !{!6085, !6087, !6097, !6237}
!6247 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6248, file: !6024, line: 194)
!6248 = !DISubprogram(name: "wcstol", scope: !6030, file: !6030, line: 428, type: !6249, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6249 = !DISubroutineType(types: !6250)
!6250 = !{!1837, !6097, !6237, !324}
!6251 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6252, file: !6024, line: 195)
!6252 = !DISubprogram(name: "wcstoul", scope: !6030, file: !6030, line: 433, type: !6253, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6253 = !DISubroutineType(types: !6254)
!6254 = !{!417, !6097, !6237, !324}
!6255 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6256, file: !6024, line: 196)
!6256 = !DISubprogram(name: "wcsxfrm", scope: !6030, file: !6030, line: 135, type: !6257, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6257 = !DISubroutineType(types: !6258)
!6258 = !{!1583, !6087, !6097, !1583}
!6259 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6260, file: !6024, line: 197)
!6260 = !DISubprogram(name: "wctob", scope: !6030, file: !6030, line: 324, type: !6261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6261 = !DISubroutineType(types: !6262)
!6262 = !{!324, !6026}
!6263 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6264, file: !6024, line: 198)
!6264 = !DISubprogram(name: "wmemcmp", scope: !6030, file: !6030, line: 258, type: !6221, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6265 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6266, file: !6024, line: 199)
!6266 = !DISubprogram(name: "wmemcpy", scope: !6030, file: !6030, line: 262, type: !6217, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6267 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6268, file: !6024, line: 200)
!6268 = !DISubprogram(name: "wmemmove", scope: !6030, file: !6030, line: 267, type: !6269, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6269 = !DISubroutineType(types: !6270)
!6270 = !{!6085, !6085, !6098, !1583}
!6271 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6272, file: !6024, line: 201)
!6272 = !DISubprogram(name: "wmemset", scope: !6030, file: !6030, line: 271, type: !6273, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6273 = !DISubroutineType(types: !6274)
!6274 = !{!6085, !6085, !6086, !1583}
!6275 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6276, file: !6024, line: 202)
!6276 = !DISubprogram(name: "wprintf", scope: !6030, file: !6030, line: 587, type: !6277, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6277 = !DISubroutineType(types: !6278)
!6278 = !{!324, !6097, null}
!6279 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6280, file: !6024, line: 203)
!6280 = !DISubprogram(name: "wscanf", scope: !6030, file: !6030, line: 628, type: !6277, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6281 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6282, file: !6024, line: 204)
!6282 = !DISubprogram(name: "wcschr", scope: !6030, file: !6030, line: 164, type: !6283, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6283 = !DISubroutineType(types: !6284)
!6284 = !{!6085, !6098, !6086}
!6285 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6286, file: !6024, line: 205)
!6286 = !DISubprogram(name: "wcspbrk", scope: !6030, file: !6030, line: 201, type: !6287, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6287 = !DISubroutineType(types: !6288)
!6288 = !{!6085, !6098, !6098}
!6289 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6290, file: !6024, line: 206)
!6290 = !DISubprogram(name: "wcsrchr", scope: !6030, file: !6030, line: 174, type: !6283, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6291 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6292, file: !6024, line: 207)
!6292 = !DISubprogram(name: "wcsstr", scope: !6030, file: !6030, line: 212, type: !6287, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6293 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6294, file: !6024, line: 208)
!6294 = !DISubprogram(name: "wmemchr", scope: !6030, file: !6030, line: 253, type: !6295, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6295 = !DISubroutineType(types: !6296)
!6296 = !{!6085, !6098, !6086, !1583}
!6297 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6298, file: !6024, line: 248)
!6298 = !DISubprogram(name: "wcstold", scope: !6030, file: !6030, line: 384, type: !6299, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6299 = !DISubroutineType(types: !6300)
!6300 = !{!5648, !6097, !6237}
!6301 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6302, file: !6024, line: 257)
!6302 = !DISubprogram(name: "wcstoll", scope: !6030, file: !6030, line: 441, type: !6303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6303 = !DISubroutineType(types: !6304)
!6304 = !{!5759, !6097, !6237, !324}
!6305 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6306, file: !6024, line: 258)
!6306 = !DISubprogram(name: "wcstoull", scope: !6030, file: !6030, line: 448, type: !6307, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6307 = !DISubroutineType(types: !6308)
!6308 = !{!6309, !6097, !6237, !324}
!6309 = !DIBasicType(name: "unsigned long long", size: 64, encoding: DW_ATE_unsigned)
!6310 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6298, file: !6024, line: 264)
!6311 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6302, file: !6024, line: 265)
!6312 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6306, file: !6024, line: 266)
!6313 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6240, file: !6024, line: 280)
!6314 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6169, file: !6024, line: 283)
!6315 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6175, file: !6024, line: 286)
!6316 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6183, file: !6024, line: 289)
!6317 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6298, file: !6024, line: 293)
!6318 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6302, file: !6024, line: 294)
!6319 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6306, file: !6024, line: 295)
!6320 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6321, file: !6324, line: 48)
!6321 = !DIDerivedType(tag: DW_TAG_typedef, name: "int8_t", file: !6322, line: 24, baseType: !6323)
!6322 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h", directory: "", checksumkind: CSK_MD5, checksum: "457547631e07cd24d9a14c8410e28e57")
!6323 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int8_t", file: !4714, line: 36, baseType: !6066)
!6324 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdint", directory: "")
!6325 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6326, file: !6324, line: 49)
!6326 = !DIDerivedType(tag: DW_TAG_typedef, name: "int16_t", file: !6322, line: 25, baseType: !6327)
!6327 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int16_t", file: !4714, line: 38, baseType: !6328)
!6328 = !DIBasicType(name: "short", size: 16, encoding: DW_ATE_signed)
!6329 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6330, file: !6324, line: 50)
!6330 = !DIDerivedType(tag: DW_TAG_typedef, name: "int32_t", file: !6322, line: 26, baseType: !6331)
!6331 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int32_t", file: !4714, line: 40, baseType: !324)
!6332 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6333, file: !6324, line: 51)
!6333 = !DIDerivedType(tag: DW_TAG_typedef, name: "int64_t", file: !6322, line: 27, baseType: !6334)
!6334 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int64_t", file: !4714, line: 43, baseType: !1837)
!6335 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6336, file: !6324, line: 53)
!6336 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast8_t", file: !1836, line: 68, baseType: !6066)
!6337 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6338, file: !6324, line: 54)
!6338 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast16_t", file: !1836, line: 70, baseType: !1837)
!6339 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6340, file: !6324, line: 55)
!6340 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast32_t", file: !1836, line: 71, baseType: !1837)
!6341 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6342, file: !6324, line: 56)
!6342 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast64_t", file: !1836, line: 72, baseType: !1837)
!6343 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6344, file: !6324, line: 58)
!6344 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least8_t", file: !1836, line: 43, baseType: !6066)
!6345 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6346, file: !6324, line: 59)
!6346 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least16_t", file: !1836, line: 44, baseType: !6328)
!6347 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6348, file: !6324, line: 60)
!6348 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least32_t", file: !1836, line: 45, baseType: !324)
!6349 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6350, file: !6324, line: 61)
!6350 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least64_t", file: !1836, line: 47, baseType: !1837)
!6351 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6352, file: !6324, line: 63)
!6352 = !DIDerivedType(tag: DW_TAG_typedef, name: "intmax_t", file: !1836, line: 111, baseType: !6353)
!6353 = !DIDerivedType(tag: DW_TAG_typedef, name: "__intmax_t", file: !4714, line: 61, baseType: !1837)
!6354 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !1835, file: !6324, line: 64)
!6355 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6356, file: !6324, line: 66)
!6356 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint8_t", file: !6357, line: 24, baseType: !6358)
!6357 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h", directory: "", checksumkind: CSK_MD5, checksum: "9754ebe022edbe8d7928fa709e442f0d")
!6358 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint8_t", file: !4714, line: 37, baseType: !949)
!6359 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6360, file: !6324, line: 67)
!6360 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint16_t", file: !6357, line: 25, baseType: !6361)
!6361 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint16_t", file: !4714, line: 39, baseType: !947)
!6362 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6363, file: !6324, line: 68)
!6363 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint32_t", file: !6357, line: 26, baseType: !6364)
!6364 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint32_t", file: !4714, line: 41, baseType: !6)
!6365 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6366, file: !6324, line: 69)
!6366 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint64_t", file: !6357, line: 27, baseType: !6367)
!6367 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint64_t", file: !4714, line: 44, baseType: !417)
!6368 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6369, file: !6324, line: 71)
!6369 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast8_t", file: !1836, line: 81, baseType: !949)
!6370 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6371, file: !6324, line: 72)
!6371 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast16_t", file: !1836, line: 83, baseType: !417)
!6372 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6373, file: !6324, line: 73)
!6373 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast32_t", file: !1836, line: 84, baseType: !417)
!6374 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6375, file: !6324, line: 74)
!6375 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast64_t", file: !1836, line: 85, baseType: !417)
!6376 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6377, file: !6324, line: 76)
!6377 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least8_t", file: !1836, line: 54, baseType: !949)
!6378 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6379, file: !6324, line: 77)
!6379 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least16_t", file: !1836, line: 55, baseType: !947)
!6380 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6381, file: !6324, line: 78)
!6381 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least32_t", file: !1836, line: 56, baseType: !6)
!6382 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6383, file: !6324, line: 79)
!6383 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least64_t", file: !1836, line: 58, baseType: !417)
!6384 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6385, file: !6324, line: 81)
!6385 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintmax_t", file: !1836, line: 112, baseType: !6386)
!6386 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uintmax_t", file: !4714, line: 62, baseType: !417)
!6387 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !2388, file: !6324, line: 82)
!6388 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6389, file: !6391, line: 53)
!6389 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "lconv", file: !6390, line: 51, size: 768, flags: DIFlagFwdDecl, identifier: "_ZTS5lconv")
!6390 = !DIFile(filename: "/usr/include/locale.h", directory: "", checksumkind: CSK_MD5, checksum: "0595275e3f5b502d28f7cd61a0dff888")
!6391 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/clocale", directory: "")
!6392 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6393, file: !6391, line: 54)
!6393 = !DISubprogram(name: "setlocale", scope: !6390, file: !6390, line: 122, type: !6394, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6394 = !DISubroutineType(types: !6395)
!6395 = !{!373, !324, !407}
!6396 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6397, file: !6391, line: 55)
!6397 = !DISubprogram(name: "localeconv", scope: !6390, file: !6390, line: 125, type: !6398, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6398 = !DISubroutineType(types: !6399)
!6399 = !{!6400}
!6400 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6389, size: 64)
!6401 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6402, file: !6404, line: 64)
!6402 = !DISubprogram(name: "isalnum", scope: !6403, file: !6403, line: 108, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6403 = !DIFile(filename: "/usr/include/ctype.h", directory: "", checksumkind: CSK_MD5, checksum: "c67c809b09ef8ea9c273687bc20a7fd3")
!6404 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cctype", directory: "")
!6405 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6406, file: !6404, line: 65)
!6406 = !DISubprogram(name: "isalpha", scope: !6403, file: !6403, line: 109, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6407 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6408, file: !6404, line: 66)
!6408 = !DISubprogram(name: "iscntrl", scope: !6403, file: !6403, line: 110, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6409 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6410, file: !6404, line: 67)
!6410 = !DISubprogram(name: "isdigit", scope: !6403, file: !6403, line: 111, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6411 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6412, file: !6404, line: 68)
!6412 = !DISubprogram(name: "isgraph", scope: !6403, file: !6403, line: 113, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6413 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6414, file: !6404, line: 69)
!6414 = !DISubprogram(name: "islower", scope: !6403, file: !6403, line: 112, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6415 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6416, file: !6404, line: 70)
!6416 = !DISubprogram(name: "isprint", scope: !6403, file: !6403, line: 114, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6417 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6418, file: !6404, line: 71)
!6418 = !DISubprogram(name: "ispunct", scope: !6403, file: !6403, line: 115, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6419 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6420, file: !6404, line: 72)
!6420 = !DISubprogram(name: "isspace", scope: !6403, file: !6403, line: 116, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6421 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6422, file: !6404, line: 73)
!6422 = !DISubprogram(name: "isupper", scope: !6403, file: !6403, line: 117, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6423 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6424, file: !6404, line: 74)
!6424 = !DISubprogram(name: "isxdigit", scope: !6403, file: !6403, line: 118, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6425 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6426, file: !6404, line: 75)
!6426 = !DISubprogram(name: "tolower", scope: !6403, file: !6403, line: 122, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6427 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6428, file: !6404, line: 76)
!6428 = !DISubprogram(name: "toupper", scope: !6403, file: !6403, line: 125, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6429 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6430, file: !6404, line: 87)
!6430 = !DISubprogram(name: "isblank", scope: !6403, file: !6403, line: 130, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6431 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6432, file: !6434, line: 127)
!6432 = !DIDerivedType(tag: DW_TAG_typedef, name: "div_t", file: !5569, line: 62, baseType: !6433)
!6433 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !5569, line: 58, size: 64, flags: DIFlagFwdDecl, identifier: "_ZTS5div_t")
!6434 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdlib", directory: "")
!6435 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6436, file: !6434, line: 128)
!6436 = !DIDerivedType(tag: DW_TAG_typedef, name: "ldiv_t", file: !5569, line: 70, baseType: !6437)
!6437 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !5569, line: 66, size: 128, flags: DIFlagTypePassByValue, elements: !6438, identifier: "_ZTS6ldiv_t")
!6438 = !{!6439, !6440}
!6439 = !DIDerivedType(tag: DW_TAG_member, name: "quot", scope: !6437, file: !5569, line: 68, baseType: !1837, size: 64)
!6440 = !DIDerivedType(tag: DW_TAG_member, name: "rem", scope: !6437, file: !5569, line: 69, baseType: !1837, size: 64, offset: 64)
!6441 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6442, file: !6434, line: 130)
!6442 = !DISubprogram(name: "abort", scope: !5569, file: !5569, line: 588, type: !6443, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!6443 = !DISubroutineType(types: !6444)
!6444 = !{null}
!6445 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6446, file: !6434, line: 134)
!6446 = !DISubprogram(name: "atexit", scope: !5569, file: !5569, line: 592, type: !6447, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6447 = !DISubroutineType(types: !6448)
!6448 = !{!324, !6449}
!6449 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6443, size: 64)
!6450 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6451, file: !6434, line: 137)
!6451 = !DISubprogram(name: "at_quick_exit", scope: !5569, file: !5569, line: 597, type: !6447, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6452 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6453, file: !6434, line: 140)
!6453 = !DISubprogram(name: "atof", scope: !6454, file: !6454, line: 25, type: !5812, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6454 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h", directory: "", checksumkind: CSK_MD5, checksum: "ce60958b260b171e83db3307f1d644f0")
!6455 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6456, file: !6434, line: 141)
!6456 = !DISubprogram(name: "atoi", scope: !5569, file: !5569, line: 361, type: !6457, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6457 = !DISubroutineType(types: !6458)
!6458 = !{!324, !407}
!6459 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6460, file: !6434, line: 142)
!6460 = !DISubprogram(name: "atol", scope: !5569, file: !5569, line: 366, type: !6461, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6461 = !DISubroutineType(types: !6462)
!6462 = !{!1837, !407}
!6463 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6464, file: !6434, line: 143)
!6464 = !DISubprogram(name: "bsearch", scope: !6465, file: !6465, line: 20, type: !6466, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6465 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h", directory: "", checksumkind: CSK_MD5, checksum: "1a798a38b25adee7bb680abce9ef568a")
!6466 = !DISubroutineType(types: !6467)
!6467 = !{!330, !334, !334, !1583, !1583, !6468}
!6468 = !DIDerivedType(tag: DW_TAG_typedef, name: "__compar_fn_t", file: !5569, line: 805, baseType: !6469)
!6469 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6470, size: 64)
!6470 = !DISubroutineType(types: !6471)
!6471 = !{!324, !334, !334}
!6472 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6473, file: !6434, line: 144)
!6473 = !DISubprogram(name: "calloc", scope: !5569, file: !5569, line: 541, type: !6474, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6474 = !DISubroutineType(types: !6475)
!6475 = !{!330, !1583, !1583}
!6476 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6477, file: !6434, line: 145)
!6477 = !DISubprogram(name: "div", scope: !5569, file: !5569, line: 849, type: !6478, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6478 = !DISubroutineType(types: !6479)
!6479 = !{!6432, !324, !324}
!6480 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6481, file: !6434, line: 146)
!6481 = !DISubprogram(name: "exit", scope: !5569, file: !5569, line: 614, type: !6482, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!6482 = !DISubroutineType(types: !6483)
!6483 = !{null, !324}
!6484 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6485, file: !6434, line: 147)
!6485 = !DISubprogram(name: "free", scope: !5569, file: !5569, line: 563, type: !6486, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6486 = !DISubroutineType(types: !6487)
!6487 = !{null, !330}
!6488 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6489, file: !6434, line: 148)
!6489 = !DISubprogram(name: "getenv", scope: !5569, file: !5569, line: 631, type: !6490, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6490 = !DISubroutineType(types: !6491)
!6491 = !{!373, !407}
!6492 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6493, file: !6434, line: 149)
!6493 = !DISubprogram(name: "labs", scope: !5569, file: !5569, line: 838, type: !6494, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6494 = !DISubroutineType(types: !6495)
!6495 = !{!1837, !1837}
!6496 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6497, file: !6434, line: 150)
!6497 = !DISubprogram(name: "ldiv", scope: !5569, file: !5569, line: 851, type: !6498, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6498 = !DISubroutineType(types: !6499)
!6499 = !{!6436, !1837, !1837}
!6500 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6501, file: !6434, line: 151)
!6501 = !DISubprogram(name: "malloc", scope: !5569, file: !5569, line: 539, type: !6502, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6502 = !DISubroutineType(types: !6503)
!6503 = !{!330, !1583}
!6504 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6505, file: !6434, line: 153)
!6505 = !DISubprogram(name: "mblen", scope: !5569, file: !5569, line: 919, type: !6506, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6506 = !DISubroutineType(types: !6507)
!6507 = !{!324, !407, !1583}
!6508 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6509, file: !6434, line: 154)
!6509 = !DISubprogram(name: "mbstowcs", scope: !5569, file: !5569, line: 930, type: !6510, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6510 = !DISubroutineType(types: !6511)
!6511 = !{!1583, !6087, !5948, !1583}
!6512 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6513, file: !6434, line: 155)
!6513 = !DISubprogram(name: "mbtowc", scope: !5569, file: !5569, line: 922, type: !6514, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6514 = !DISubroutineType(types: !6515)
!6515 = !{!324, !6087, !5948, !1583}
!6516 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6517, file: !6434, line: 157)
!6517 = !DISubprogram(name: "qsort", scope: !5569, file: !5569, line: 827, type: !6518, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6518 = !DISubroutineType(types: !6519)
!6519 = !{null, !330, !1583, !1583, !6468}
!6520 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6521, file: !6434, line: 160)
!6521 = !DISubprogram(name: "quick_exit", scope: !5569, file: !5569, line: 620, type: !6482, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!6522 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6523, file: !6434, line: 163)
!6523 = !DISubprogram(name: "rand", scope: !5569, file: !5569, line: 453, type: !6524, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6524 = !DISubroutineType(types: !6525)
!6525 = !{!324}
!6526 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6527, file: !6434, line: 164)
!6527 = !DISubprogram(name: "realloc", scope: !5569, file: !5569, line: 549, type: !6528, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6528 = !DISubroutineType(types: !6529)
!6529 = !{!330, !330, !1583}
!6530 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6531, file: !6434, line: 165)
!6531 = !DISubprogram(name: "srand", scope: !5569, file: !5569, line: 455, type: !6532, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6532 = !DISubroutineType(types: !6533)
!6533 = !{null, !6}
!6534 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6535, file: !6434, line: 166)
!6535 = !DISubprogram(name: "strtod", scope: !5569, file: !5569, line: 117, type: !6536, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6536 = !DISubroutineType(types: !6537)
!6537 = !{!5578, !5948, !6538}
!6538 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6539)
!6539 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !373, size: 64)
!6540 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6541, file: !6434, line: 167)
!6541 = !DISubprogram(name: "strtol", scope: !5569, file: !5569, line: 176, type: !6542, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6542 = !DISubroutineType(types: !6543)
!6543 = !{!1837, !5948, !6538, !324}
!6544 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6545, file: !6434, line: 168)
!6545 = !DISubprogram(name: "strtoul", scope: !5569, file: !5569, line: 180, type: !6546, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6546 = !DISubroutineType(types: !6547)
!6547 = !{!417, !5948, !6538, !324}
!6548 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6549, file: !6434, line: 169)
!6549 = !DISubprogram(name: "system", scope: !5569, file: !5569, line: 781, type: !6457, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6550 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6551, file: !6434, line: 171)
!6551 = !DISubprogram(name: "wcstombs", scope: !5569, file: !5569, line: 933, type: !6552, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6552 = !DISubroutineType(types: !6553)
!6553 = !{!1583, !5947, !6097, !1583}
!6554 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6555, file: !6434, line: 172)
!6555 = !DISubprogram(name: "wctomb", scope: !5569, file: !5569, line: 926, type: !6556, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6556 = !DISubroutineType(types: !6557)
!6557 = !{!324, !373, !6086}
!6558 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6559, file: !6434, line: 200)
!6559 = !DIDerivedType(tag: DW_TAG_typedef, name: "lldiv_t", file: !5569, line: 80, baseType: !6560)
!6560 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !5569, line: 76, size: 128, flags: DIFlagTypePassByValue, elements: !6561, identifier: "_ZTS7lldiv_t")
!6561 = !{!6562, !6563}
!6562 = !DIDerivedType(tag: DW_TAG_member, name: "quot", scope: !6560, file: !5569, line: 78, baseType: !5759, size: 64)
!6563 = !DIDerivedType(tag: DW_TAG_member, name: "rem", scope: !6560, file: !5569, line: 79, baseType: !5759, size: 64, offset: 64)
!6564 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6565, file: !6434, line: 206)
!6565 = !DISubprogram(name: "_Exit", scope: !5569, file: !5569, line: 626, type: !6482, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!6566 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6567, file: !6434, line: 210)
!6567 = !DISubprogram(name: "llabs", scope: !5569, file: !5569, line: 841, type: !6568, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6568 = !DISubroutineType(types: !6569)
!6569 = !{!5759, !5759}
!6570 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6571, file: !6434, line: 216)
!6571 = !DISubprogram(name: "lldiv", scope: !5569, file: !5569, line: 855, type: !6572, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6572 = !DISubroutineType(types: !6573)
!6573 = !{!6559, !5759, !5759}
!6574 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6575, file: !6434, line: 227)
!6575 = !DISubprogram(name: "atoll", scope: !5569, file: !5569, line: 373, type: !6576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6576 = !DISubroutineType(types: !6577)
!6577 = !{!5759, !407}
!6578 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6579, file: !6434, line: 228)
!6579 = !DISubprogram(name: "strtoll", scope: !5569, file: !5569, line: 200, type: !6580, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6580 = !DISubroutineType(types: !6581)
!6581 = !{!5759, !5948, !6538, !324}
!6582 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6583, file: !6434, line: 229)
!6583 = !DISubprogram(name: "strtoull", scope: !5569, file: !5569, line: 205, type: !6584, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6584 = !DISubroutineType(types: !6585)
!6585 = !{!6309, !5948, !6538, !324}
!6586 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6587, file: !6434, line: 231)
!6587 = !DISubprogram(name: "strtof", scope: !5569, file: !5569, line: 123, type: !6588, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6588 = !DISubroutineType(types: !6589)
!6589 = !{!5637, !5948, !6538}
!6590 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6591, file: !6434, line: 232)
!6591 = !DISubprogram(name: "strtold", scope: !5569, file: !5569, line: 126, type: !6592, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6592 = !DISubroutineType(types: !6593)
!6593 = !{!5648, !5948, !6538}
!6594 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6559, file: !6434, line: 240)
!6595 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6565, file: !6434, line: 242)
!6596 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6567, file: !6434, line: 244)
!6597 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6598, file: !6434, line: 245)
!6598 = !DISubprogram(name: "div", linkageName: "_ZN9__gnu_cxx3divExx", scope: !5, file: !6434, line: 213, type: !6572, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6599 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6571, file: !6434, line: 246)
!6600 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6575, file: !6434, line: 248)
!6601 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6587, file: !6434, line: 249)
!6602 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6579, file: !6434, line: 250)
!6603 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6583, file: !6434, line: 251)
!6604 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6591, file: !6434, line: 252)
!6605 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6606, file: !6608, line: 98)
!6606 = !DIDerivedType(tag: DW_TAG_typedef, name: "FILE", file: !6607, line: 7, baseType: !6040)
!6607 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/FILE.h", directory: "", checksumkind: CSK_MD5, checksum: "571f9fb6223c42439075fdde11a0de5d")
!6608 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdio", directory: "")
!6609 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6610, file: !6608, line: 99)
!6610 = !DIDerivedType(tag: DW_TAG_typedef, name: "fpos_t", file: !6611, line: 78, baseType: !6612)
!6611 = !DIFile(filename: "/usr/include/stdio.h", directory: "", checksumkind: CSK_MD5, checksum: "2ab51d960d7d0ed84798d1688a6988b0")
!6612 = !DIDerivedType(tag: DW_TAG_typedef, name: "_G_fpos_t", file: !6613, line: 30, baseType: !6614)
!6613 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/_G_config.h", directory: "", checksumkind: CSK_MD5, checksum: "f78480ecfcae11a7bda5a6b08034c1fb")
!6614 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !6613, line: 26, size: 128, flags: DIFlagFwdDecl, identifier: "_ZTS9_G_fpos_t")
!6615 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6616, file: !6608, line: 101)
!6616 = !DISubprogram(name: "clearerr", scope: !6611, file: !6611, line: 757, type: !6617, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6617 = !DISubroutineType(types: !6618)
!6618 = !{null, !6619}
!6619 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6606, size: 64)
!6620 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6621, file: !6608, line: 102)
!6621 = !DISubprogram(name: "fclose", scope: !6611, file: !6611, line: 199, type: !6622, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6622 = !DISubroutineType(types: !6623)
!6623 = !{!324, !6619}
!6624 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6625, file: !6608, line: 103)
!6625 = !DISubprogram(name: "feof", scope: !6611, file: !6611, line: 759, type: !6622, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6626 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6627, file: !6608, line: 104)
!6627 = !DISubprogram(name: "ferror", scope: !6611, file: !6611, line: 761, type: !6622, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6628 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6629, file: !6608, line: 105)
!6629 = !DISubprogram(name: "fflush", scope: !6611, file: !6611, line: 204, type: !6622, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6630 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6631, file: !6608, line: 106)
!6631 = !DISubprogram(name: "fgetc", scope: !6611, file: !6611, line: 477, type: !6622, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6632 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6633, file: !6608, line: 107)
!6633 = !DISubprogram(name: "fgetpos", scope: !6611, file: !6611, line: 731, type: !6634, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6634 = !DISubroutineType(types: !6635)
!6635 = !{!324, !6636, !6637}
!6636 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6619)
!6637 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !6638)
!6638 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6610, size: 64)
!6639 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6640, file: !6608, line: 108)
!6640 = !DISubprogram(name: "fgets", scope: !6611, file: !6611, line: 564, type: !6641, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6641 = !DISubroutineType(types: !6642)
!6642 = !{!373, !5947, !324, !6636}
!6643 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6644, file: !6608, line: 109)
!6644 = !DISubprogram(name: "fopen", scope: !6611, file: !6611, line: 232, type: !6645, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6645 = !DISubroutineType(types: !6646)
!6646 = !{!6619, !5948, !5948}
!6647 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6648, file: !6608, line: 110)
!6648 = !DISubprogram(name: "fprintf", scope: !6611, file: !6611, line: 312, type: !6649, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6649 = !DISubroutineType(types: !6650)
!6650 = !{!324, !6636, !5948, null}
!6651 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6652, file: !6608, line: 111)
!6652 = !DISubprogram(name: "fputc", scope: !6611, file: !6611, line: 517, type: !6653, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6653 = !DISubroutineType(types: !6654)
!6654 = !{!324, !324, !6619}
!6655 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6656, file: !6608, line: 112)
!6656 = !DISubprogram(name: "fputs", scope: !6611, file: !6611, line: 626, type: !6657, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6657 = !DISubroutineType(types: !6658)
!6658 = !{!324, !5948, !6636}
!6659 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6660, file: !6608, line: 113)
!6660 = !DISubprogram(name: "fread", scope: !6611, file: !6611, line: 646, type: !6661, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6661 = !DISubroutineType(types: !6662)
!6662 = !{!1583, !5933, !1583, !1583, !6636}
!6663 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6664, file: !6608, line: 114)
!6664 = !DISubprogram(name: "freopen", scope: !6611, file: !6611, line: 238, type: !6665, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6665 = !DISubroutineType(types: !6666)
!6666 = !{!6619, !5948, !5948, !6636}
!6667 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6668, file: !6608, line: 115)
!6668 = !DISubprogram(name: "fscanf", scope: !6611, file: !6611, line: 377, type: !6649, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6669 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6670, file: !6608, line: 116)
!6670 = !DISubprogram(name: "fseek", scope: !6611, file: !6611, line: 684, type: !6671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6671 = !DISubroutineType(types: !6672)
!6672 = !{!324, !6619, !1837, !324}
!6673 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6674, file: !6608, line: 117)
!6674 = !DISubprogram(name: "fsetpos", scope: !6611, file: !6611, line: 736, type: !6675, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6675 = !DISubroutineType(types: !6676)
!6676 = !{!324, !6619, !6677}
!6677 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6678, size: 64)
!6678 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6610)
!6679 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6680, file: !6608, line: 118)
!6680 = !DISubprogram(name: "ftell", scope: !6611, file: !6611, line: 689, type: !6681, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6681 = !DISubroutineType(types: !6682)
!6682 = !{!1837, !6619}
!6683 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6684, file: !6608, line: 119)
!6684 = !DISubprogram(name: "fwrite", scope: !6611, file: !6611, line: 652, type: !6685, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6685 = !DISubroutineType(types: !6686)
!6686 = !{!1583, !5934, !1583, !1583, !6636}
!6687 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6688, file: !6608, line: 120)
!6688 = !DISubprogram(name: "getc", scope: !6611, file: !6611, line: 478, type: !6622, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6689 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6690, file: !6608, line: 121)
!6690 = !DISubprogram(name: "getchar", scope: !6691, file: !6691, line: 44, type: !6524, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6691 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdio.h", directory: "", checksumkind: CSK_MD5, checksum: "ae874477a6b090849220f12acdd69dc3")
!6692 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6693, file: !6608, line: 126)
!6693 = !DISubprogram(name: "perror", scope: !6611, file: !6611, line: 775, type: !6694, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6694 = !DISubroutineType(types: !6695)
!6695 = !{null, !407}
!6696 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6697, file: !6608, line: 127)
!6697 = !DISubprogram(name: "printf", scope: !6611, file: !6611, line: 318, type: !6698, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6698 = !DISubroutineType(types: !6699)
!6699 = !{!324, !5948, null}
!6700 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6701, file: !6608, line: 128)
!6701 = !DISubprogram(name: "putc", scope: !6611, file: !6611, line: 518, type: !6653, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6702 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6703, file: !6608, line: 129)
!6703 = !DISubprogram(name: "putchar", scope: !6691, file: !6691, line: 79, type: !5570, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6704 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6705, file: !6608, line: 130)
!6705 = !DISubprogram(name: "puts", scope: !6611, file: !6611, line: 632, type: !6457, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6706 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6707, file: !6608, line: 131)
!6707 = !DISubprogram(name: "remove", scope: !6611, file: !6611, line: 144, type: !6457, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6708 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6709, file: !6608, line: 132)
!6709 = !DISubprogram(name: "rename", scope: !6611, file: !6611, line: 146, type: !5951, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6710 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6711, file: !6608, line: 133)
!6711 = !DISubprogram(name: "rewind", scope: !6611, file: !6611, line: 694, type: !6617, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6712 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6713, file: !6608, line: 134)
!6713 = !DISubprogram(name: "scanf", scope: !6611, file: !6611, line: 383, type: !6698, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6714 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6715, file: !6608, line: 135)
!6715 = !DISubprogram(name: "setbuf", scope: !6611, file: !6611, line: 290, type: !6716, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6716 = !DISubroutineType(types: !6717)
!6717 = !{null, !6636, !5947}
!6718 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6719, file: !6608, line: 136)
!6719 = !DISubprogram(name: "setvbuf", scope: !6611, file: !6611, line: 294, type: !6720, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6720 = !DISubroutineType(types: !6721)
!6721 = !{!324, !6636, !5947, !324, !1583}
!6722 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6723, file: !6608, line: 137)
!6723 = !DISubprogram(name: "sprintf", scope: !6611, file: !6611, line: 320, type: !6724, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6724 = !DISubroutineType(types: !6725)
!6725 = !{!324, !5947, !5948, null}
!6726 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6727, file: !6608, line: 138)
!6727 = !DISubprogram(name: "sscanf", scope: !6611, file: !6611, line: 385, type: !6728, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6728 = !DISubroutineType(types: !6729)
!6729 = !{!324, !5948, !5948, null}
!6730 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6731, file: !6608, line: 139)
!6731 = !DISubprogram(name: "tmpfile", scope: !6611, file: !6611, line: 159, type: !6732, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6732 = !DISubroutineType(types: !6733)
!6733 = !{!6619}
!6734 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6735, file: !6608, line: 141)
!6735 = !DISubprogram(name: "tmpnam", scope: !6611, file: !6611, line: 173, type: !6736, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6736 = !DISubroutineType(types: !6737)
!6737 = !{!373, !373}
!6738 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6739, file: !6608, line: 143)
!6739 = !DISubprogram(name: "ungetc", scope: !6611, file: !6611, line: 639, type: !6653, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6740 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6741, file: !6608, line: 144)
!6741 = !DISubprogram(name: "vfprintf", scope: !6611, file: !6611, line: 327, type: !6742, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6742 = !DISubroutineType(types: !6743)
!6743 = !{!324, !6636, !5948, !6160}
!6744 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6745, file: !6608, line: 145)
!6745 = !DISubprogram(name: "vprintf", scope: !6691, file: !6691, line: 36, type: !6746, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6746 = !DISubroutineType(types: !6747)
!6747 = !{!324, !5948, !6160}
!6748 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6749, file: !6608, line: 146)
!6749 = !DISubprogram(name: "vsprintf", scope: !6611, file: !6611, line: 335, type: !6750, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6750 = !DISubroutineType(types: !6751)
!6751 = !{!324, !5947, !5948, !6160}
!6752 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6753, file: !6608, line: 175)
!6753 = !DISubprogram(name: "snprintf", scope: !6611, file: !6611, line: 340, type: !6754, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6754 = !DISubroutineType(types: !6755)
!6755 = !{!324, !5947, !1583, !5948, null}
!6756 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6757, file: !6608, line: 176)
!6757 = !DISubprogram(name: "vfscanf", scope: !6611, file: !6611, line: 420, type: !6742, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6758 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6759, file: !6608, line: 177)
!6759 = !DISubprogram(name: "vscanf", scope: !6611, file: !6611, line: 428, type: !6746, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6760 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6761, file: !6608, line: 178)
!6761 = !DISubprogram(name: "vsnprintf", scope: !6611, file: !6611, line: 344, type: !6762, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6762 = !DISubroutineType(types: !6763)
!6763 = !{!324, !5947, !1583, !5948, !6160}
!6764 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !6765, file: !6608, line: 179)
!6765 = !DISubprogram(name: "vsscanf", scope: !6611, file: !6611, line: 432, type: !6766, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6766 = !DISubroutineType(types: !6767)
!6767 = !{!324, !5948, !5948, !6160}
!6768 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6753, file: !6608, line: 185)
!6769 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6757, file: !6608, line: 186)
!6770 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6759, file: !6608, line: 187)
!6771 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6761, file: !6608, line: 188)
!6772 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6765, file: !6608, line: 189)
!6773 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !3, file: !6774, line: 86)
!6774 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr_base.h", directory: "", checksumkind: CSK_MD5, checksum: "8405222f7806be9ab20595b5fcc527fd")
!6775 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6776, file: !6774, line: 87)
!6776 = !DIGlobalVariable(name: "__default_lock_policy", linkageName: "_ZN9__gnu_cxxL21__default_lock_policyE", scope: !5, file: !4, line: 53, type: !6777, isLocal: true, isDefinition: false)
!6777 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3)
!6778 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6779, file: !6783, line: 82)
!6779 = !DIDerivedType(tag: DW_TAG_typedef, name: "wctrans_t", file: !6780, line: 48, baseType: !6781)
!6780 = !DIFile(filename: "/usr/include/wctype.h", directory: "", checksumkind: CSK_MD5, checksum: "760693b7fbeea3d686e1f29058fc2257")
!6781 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6782, size: 64)
!6782 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6331)
!6783 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cwctype", directory: "")
!6784 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6785, file: !6783, line: 83)
!6785 = !DIDerivedType(tag: DW_TAG_typedef, name: "wctype_t", file: !6786, line: 38, baseType: !417)
!6786 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/wctype-wchar.h", directory: "", checksumkind: CSK_MD5, checksum: "45eef9c3aa1d99faffa3945ed9be039a")
!6787 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6026, file: !6783, line: 84)
!6788 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6789, file: !6783, line: 86)
!6789 = !DISubprogram(name: "iswalnum", scope: !6786, file: !6786, line: 95, type: !6261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6790 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6791, file: !6783, line: 87)
!6791 = !DISubprogram(name: "iswalpha", scope: !6786, file: !6786, line: 101, type: !6261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6792 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6793, file: !6783, line: 89)
!6793 = !DISubprogram(name: "iswblank", scope: !6786, file: !6786, line: 146, type: !6261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6794 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6795, file: !6783, line: 91)
!6795 = !DISubprogram(name: "iswcntrl", scope: !6786, file: !6786, line: 104, type: !6261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6796 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6797, file: !6783, line: 92)
!6797 = !DISubprogram(name: "iswctype", scope: !6786, file: !6786, line: 159, type: !6798, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6798 = !DISubroutineType(types: !6799)
!6799 = !{!324, !6026, !6785}
!6800 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6801, file: !6783, line: 93)
!6801 = !DISubprogram(name: "iswdigit", scope: !6786, file: !6786, line: 108, type: !6261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6802 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6803, file: !6783, line: 94)
!6803 = !DISubprogram(name: "iswgraph", scope: !6786, file: !6786, line: 112, type: !6261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6804 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6805, file: !6783, line: 95)
!6805 = !DISubprogram(name: "iswlower", scope: !6786, file: !6786, line: 117, type: !6261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6806 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6807, file: !6783, line: 96)
!6807 = !DISubprogram(name: "iswprint", scope: !6786, file: !6786, line: 120, type: !6261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6808 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6809, file: !6783, line: 97)
!6809 = !DISubprogram(name: "iswpunct", scope: !6786, file: !6786, line: 125, type: !6261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6810 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6811, file: !6783, line: 98)
!6811 = !DISubprogram(name: "iswspace", scope: !6786, file: !6786, line: 130, type: !6261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6812 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6813, file: !6783, line: 99)
!6813 = !DISubprogram(name: "iswupper", scope: !6786, file: !6786, line: 135, type: !6261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6814 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6815, file: !6783, line: 100)
!6815 = !DISubprogram(name: "iswxdigit", scope: !6786, file: !6786, line: 140, type: !6261, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6816 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6817, file: !6783, line: 101)
!6817 = !DISubprogram(name: "towctrans", scope: !6780, file: !6780, line: 55, type: !6818, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6818 = !DISubroutineType(types: !6819)
!6819 = !{!6026, !6026, !6779}
!6820 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6821, file: !6783, line: 102)
!6821 = !DISubprogram(name: "towlower", scope: !6786, file: !6786, line: 166, type: !6822, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6822 = !DISubroutineType(types: !6823)
!6823 = !{!6026, !6026}
!6824 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6825, file: !6783, line: 103)
!6825 = !DISubprogram(name: "towupper", scope: !6786, file: !6786, line: 169, type: !6822, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6826 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6827, file: !6783, line: 104)
!6827 = !DISubprogram(name: "wctrans", scope: !6780, file: !6780, line: 52, type: !6828, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6828 = !DISubroutineType(types: !6829)
!6829 = !{!6779, !407}
!6830 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6831, file: !6783, line: 105)
!6831 = !DISubprogram(name: "wctype", scope: !6786, file: !6786, line: 155, type: !6832, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6832 = !DISubroutineType(types: !6833)
!6833 = !{!6785, !407}
!6834 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6835, file: !6838, line: 60)
!6835 = !DIDerivedType(tag: DW_TAG_typedef, name: "clock_t", file: !6836, line: 7, baseType: !6837)
!6836 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/clock_t.h", directory: "", checksumkind: CSK_MD5, checksum: "1aade99fd778d1551600c7ca1410b9f1")
!6837 = !DIDerivedType(tag: DW_TAG_typedef, name: "__clock_t", file: !4714, line: 144, baseType: !1837)
!6838 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ctime", directory: "")
!6839 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !4711, file: !6838, line: 61)
!6840 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !4717, file: !6838, line: 62)
!6841 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6842, file: !6838, line: 64)
!6842 = !DISubprogram(name: "clock", scope: !6843, file: !6843, line: 72, type: !6844, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6843 = !DIFile(filename: "/usr/include/time.h", directory: "", checksumkind: CSK_MD5, checksum: "3b21b4c7d8bf3fafdb33a1c7ed8e024a")
!6844 = !DISubroutineType(types: !6845)
!6845 = !{!6835}
!6846 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6847, file: !6838, line: 65)
!6847 = !DISubprogram(name: "difftime", scope: !6843, file: !6843, line: 78, type: !6848, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6848 = !DISubroutineType(types: !6849)
!6849 = !{!5578, !4711, !4711}
!6850 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6851, file: !6838, line: 66)
!6851 = !DISubprogram(name: "mktime", scope: !6843, file: !6843, line: 82, type: !6852, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6852 = !DISubroutineType(types: !6853)
!6853 = !{!4711, !4716}
!6854 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6855, file: !6838, line: 67)
!6855 = !DISubprogram(name: "time", scope: !6843, file: !6843, line: 75, type: !6856, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6856 = !DISubroutineType(types: !6857)
!6857 = !{!4711, !6858}
!6858 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4711, size: 64)
!6859 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6860, file: !6838, line: 68)
!6860 = !DISubprogram(name: "asctime", scope: !6843, file: !6843, line: 139, type: !6861, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6861 = !DISubroutineType(types: !6862)
!6862 = !{!373, !6209}
!6863 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6864, file: !6838, line: 69)
!6864 = !DISubprogram(name: "ctime", scope: !6843, file: !6843, line: 142, type: !6865, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6865 = !DISubroutineType(types: !6866)
!6866 = !{!373, !6867}
!6867 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6868, size: 64)
!6868 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4711)
!6869 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6870, file: !6838, line: 70)
!6870 = !DISubprogram(name: "gmtime", scope: !6843, file: !6843, line: 119, type: !6871, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6871 = !DISubroutineType(types: !6872)
!6872 = !{!4716, !6867}
!6873 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6874, file: !6838, line: 71)
!6874 = !DISubprogram(name: "localtime", scope: !6843, file: !6843, line: 123, type: !6871, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6875 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !353, entity: !6876, file: !6838, line: 72)
!6876 = !DISubprogram(name: "strftime", scope: !6843, file: !6843, line: 88, type: !6877, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6877 = !DISubroutineType(types: !6878)
!6878 = !{!1583, !5947, !1583, !5948, !6208}
!6879 = !DIImportedEntity(tag: DW_TAG_imported_module, scope: !0, entity: !14, file: !1450, line: 33)
!6880 = !{i32 7, !"Dwarf Version", i32 5}
!6881 = !{i32 2, !"Debug Info Version", i32 3}
!6882 = !{i32 1, !"wchar_size", i32 4}
!6883 = !{i32 7, !"PIC Level", i32 2}
!6884 = !{i32 7, !"uwtable", i32 2}
!6885 = !DILocalVariable(name: "IsValid", scope: !6886, file: !1450, line: 1373, type: !308)
!6886 = distinct !DILexicalBlock(scope: !6887, file: !1450, line: 1369, column: 42)
!6887 = distinct !DILexicalBlock(scope: !6888, file: !1450, line: 1366, column: 14)
!6888 = distinct !DILexicalBlock(scope: !6889, file: !1450, line: 1362, column: 14)
!6889 = distinct !DILexicalBlock(scope: !6890, file: !1450, line: 1339, column: 14)
!6890 = distinct !DILexicalBlock(scope: !6891, file: !1450, line: 1324, column: 14)
!6891 = distinct !DILexicalBlock(scope: !6892, file: !1450, line: 1315, column: 14)
!6892 = distinct !DILexicalBlock(scope: !6893, file: !1450, line: 1306, column: 14)
!6893 = distinct !DILexicalBlock(scope: !6894, file: !1450, line: 1280, column: 14)
!6894 = distinct !DILexicalBlock(scope: !6895, file: !1450, line: 1259, column: 7)
!6895 = distinct !DISubprogram(name: "ExpandBuiltinMacro", linkageName: "_ZN5clang12Preprocessor18ExpandBuiltinMacroERNS_5TokenE", scope: !2800, file: !1450, line: 1238, type: !6896, scopeLine: 1238, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !6899, retainedNodes: !6900)
!6896 = !DISubroutineType(types: !6897)
!6897 = !{null, !6898, !2077}
!6898 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2800, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!6899 = !DISubprogram(name: "ExpandBuiltinMacro", linkageName: "_ZN5clang12Preprocessor18ExpandBuiltinMacroERNS_5TokenE", scope: !2800, file: !2799, line: 1370, type: !6896, scopeLine: 1370, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!6900 = !{!6901, !6903, !6904, !6905, !6906, !6907, !6909, !6911, !6913, !6916, !6917, !6919, !6920, !6926, !6929, !6930, !6933, !6934, !6885, !6935, !6936, !6937, !6940, !6943, !6944, !6945, !6947, !6948, !6949}
!6901 = !DILocalVariable(name: "this", arg: 1, scope: !6895, type: !6902, flags: DIFlagArtificial | DIFlagObjectPointer)
!6902 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2800, size: 64)
!6903 = !DILocalVariable(name: "Tok", arg: 2, scope: !6895, file: !1450, line: 1238, type: !2077)
!6904 = !DILocalVariable(name: "II", scope: !6895, file: !1450, line: 1240, type: !1348)
!6905 = !DILocalVariable(name: "TmpBuffer", scope: !6895, file: !1450, line: 1252, type: !3798)
!6906 = !DILocalVariable(name: "OS", scope: !6895, file: !1450, line: 1253, type: !4734)
!6907 = !DILocalVariable(name: "Loc", scope: !6908, file: !1450, line: 1263, type: !297)
!6908 = distinct !DILexicalBlock(scope: !6894, file: !1450, line: 1259, column: 28)
!6909 = !DILocalVariable(name: "PLoc", scope: !6908, file: !1450, line: 1275, type: !6910)
!6910 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PresumedLoc", scope: !14, file: !298, line: 356, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang11PresumedLocE")
!6911 = !DILocalVariable(name: "PLoc", scope: !6912, file: !1450, line: 1283, type: !6910)
!6912 = distinct !DILexicalBlock(scope: !6893, file: !1450, line: 1280, column: 63)
!6913 = !DILocalVariable(name: "NextLoc", scope: !6914, file: !1450, line: 1288, type: !297)
!6914 = distinct !DILexicalBlock(scope: !6915, file: !1450, line: 1287, column: 53)
!6915 = distinct !DILexicalBlock(scope: !6912, file: !1450, line: 1287, column: 9)
!6916 = !DILocalVariable(name: "FN", scope: !6912, file: !1450, line: 1299, type: !3798)
!6917 = !DILocalVariable(name: "Depth", scope: !6918, file: !1450, line: 1327, type: !6)
!6918 = distinct !DILexicalBlock(scope: !6890, file: !1450, line: 1324, column: 44)
!6919 = !DILocalVariable(name: "PLoc", scope: !6918, file: !1450, line: 1329, type: !6910)
!6920 = !DILocalVariable(name: "CurFile", scope: !6921, file: !1450, line: 1345, type: !6922)
!6921 = distinct !DILexicalBlock(scope: !6889, file: !1450, line: 1339, column: 40)
!6922 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6923, size: 64)
!6923 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !6924)
!6924 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FileEntry", scope: !14, file: !6925, line: 60, size: 512, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang9FileEntryE")
!6925 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/FileManager.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "9a73a4c26400d1f0b8deba18b5ca5818")
!6926 = !DILocalVariable(name: "TheLexer", scope: !6921, file: !1450, line: 1346, type: !6927)
!6927 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !6928, size: 64)
!6928 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PreprocessorLexer", scope: !14, file: !4806, line: 27, size: 960, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang17PreprocessorLexerE")
!6929 = !DILocalVariable(name: "Result", scope: !6921, file: !1450, line: 1351, type: !407)
!6930 = !DILocalVariable(name: "TT", scope: !6931, file: !1450, line: 1353, type: !4711)
!6931 = distinct !DILexicalBlock(scope: !6932, file: !1450, line: 1352, column: 18)
!6932 = distinct !DILexicalBlock(scope: !6921, file: !1450, line: 1352, column: 9)
!6933 = !DILocalVariable(name: "TM", scope: !6931, file: !1450, line: 1354, type: !4716)
!6934 = !DILocalVariable(name: "StartLoc", scope: !6886, file: !1450, line: 1371, type: !297)
!6935 = !DILocalVariable(name: "FeatureII", scope: !6886, file: !1450, line: 1374, type: !1348)
!6936 = !DILocalVariable(name: "Value", scope: !6886, file: !1450, line: 1389, type: !308)
!6937 = !DILocalVariable(name: "Value", scope: !6938, file: !1450, line: 1412, type: !308)
!6938 = distinct !DILexicalBlock(scope: !6939, file: !1450, line: 1408, column: 45)
!6939 = distinct !DILexicalBlock(scope: !6887, file: !1450, line: 1407, column: 14)
!6940 = !DILocalVariable(name: "StartLoc", scope: !6941, file: !1450, line: 1423, type: !297)
!6941 = distinct !DILexicalBlock(scope: !6942, file: !1450, line: 1420, column: 40)
!6942 = distinct !DILexicalBlock(scope: !6939, file: !1450, line: 1420, column: 14)
!6943 = !DILocalVariable(name: "IsValid", scope: !6941, file: !1450, line: 1424, type: !308)
!6944 = !DILocalVariable(name: "Value", scope: !6941, file: !1450, line: 1425, type: !308)
!6945 = !DILocalVariable(name: "WarningName", scope: !6946, file: !1450, line: 1435, type: !350)
!6946 = distinct !DILexicalBlock(scope: !6941, file: !1450, line: 1428, column: 8)
!6947 = !DILocalVariable(name: "StrStartLoc", scope: !6946, file: !1450, line: 1436, type: !297)
!6948 = !DILocalVariable(name: "Diags", scope: !6946, file: !1450, line: 1462, type: !4185)
!6949 = !DILocalVariable(name: "ModuleII", scope: !6950, file: !1450, line: 1479, type: !1348)
!6950 = distinct !DILexicalBlock(scope: !6951, file: !1450, line: 1476, column: 37)
!6951 = distinct !DILexicalBlock(scope: !6952, file: !1450, line: 1476, column: 14)
!6952 = distinct !DILexicalBlock(scope: !6942, file: !1450, line: 1470, column: 14)
!6953 = !DILocation(line: 0, scope: !6886)
