; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -o - -S --passes=sroa | FileCheck %s
; gnochange problem in sroa
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%"class.clang::SourceRange" = type { %"class.clang::SourceLocation", %"class.clang::SourceLocation" }
%"class.clang::SourceLocation" = type { i32 }

define void @_ZN5clang19PreprocessingRecord12MacroDefinedERKNS_5TokenEPKNS_14MacroDirectiveE(i32 %call4) !dbg !4545 {
; CHECK-LABEL: @_ZN5clang19PreprocessingRecord12MacroDefinedERKNS_5TokenEPKNS_14MacroDirectiveE(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @llvm.dbg.value(metadata i64 0, metadata [[META4553:![0-9]+]], metadata !DIExpression()), !dbg [[DBG4558:![0-9]+]]
; CHECK-NEXT:    [[R_SROA_2_0_INSERT_EXT:%.*]] = zext i32 undef to i64, !dbg [[DBG4560:![0-9]+]]
; CHECK-NEXT:    [[R_SROA_2_0_INSERT_SHIFT:%.*]] = shl i64 [[R_SROA_2_0_INSERT_EXT]], 32, !dbg [[DBG4560]]
; CHECK-NEXT:    [[R_SROA_2_0_INSERT_MASK:%.*]] = and i64 undef, 4294967295, !dbg [[DBG4560]]
; CHECK-NEXT:    [[R_SROA_2_0_INSERT_INSERT:%.*]] = or i64 [[R_SROA_2_0_INSERT_MASK]], [[R_SROA_2_0_INSERT_SHIFT]], !dbg [[DBG4560]]
; CHECK-NEXT:    [[R_SROA_0_0_INSERT_EXT:%.*]] = zext i32 [[CALL4:%.*]] to i64, !dbg [[DBG4560]]
; CHECK-NEXT:    [[R_SROA_0_0_INSERT_MASK:%.*]] = and i64 [[R_SROA_2_0_INSERT_INSERT]], -4294967296, !dbg [[DBG4560]]
; CHECK-NEXT:    [[R_SROA_0_0_INSERT_INSERT:%.*]] = or i64 [[R_SROA_0_0_INSERT_MASK]], [[R_SROA_0_0_INSERT_EXT]], !dbg [[DBG4560]]
; CHECK-NEXT:    call void null(i64 [[R_SROA_0_0_INSERT_INSERT]]), !dbg [[DBG4560]]
; CHECK-NEXT:    ret void
;
entry:
  %R = alloca %"class.clang::SourceRange", align 8
  store i32 %call4, ptr %R, align 4
  %0 = load i64, ptr %R, align 8
  call void @llvm.dbg.value(metadata i64 0, metadata !4553, metadata !DIExpression()), !dbg !4558
  call void null(i64 %0), !dbg !4560
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind readnone speculatable willreturn
declare void @llvm.dbg.value(metadata, metadata, metadata) #0

attributes #0 = { nocallback nofree nosync nounwind readnone speculatable willreturn }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!4540, !4541, !4542, !4543, !4544}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2235, globals: !2857, imports: !3220, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "/fast/fs/llvm34/projects/clang/lib/Lex/PreprocessingRecord.cpp", directory: "/fast/fs/build34llvm5", checksumkind: CSK_MD5, checksum: "991bca3cdaf717d22161d5089bc09e32")
!2 = !{!3, !11, !23, !1776, !1779, !1785, !1789, !2108, !2124, !1199, !2192, !2204, !2210, !2216, !2221, !2229}
!3 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "_Lock_policy", scope: !5, file: !4, line: 49, baseType: !6, size: 32, elements: !7, identifier: "_ZTSN9__gnu_cxx12_Lock_policyE")
!4 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/concurrence.h", directory: "")
!5 = !DINamespace(name: "__gnu_cxx", scope: null)
!6 = !DIBasicType(name: "unsigned int", size: 32, encoding: DW_ATE_unsigned)
!7 = !{!8, !9, !10}
!8 = !DIEnumerator(name: "_S_single", value: 0, isUnsigned: true)
!9 = !DIEnumerator(name: "_S_mutex", value: 1, isUnsigned: true)
!10 = !DIEnumerator(name: "_S_atomic", value: 2, isUnsigned: true)
!11 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "InclusionKind", scope: !13, file: !12, line: 200, baseType: !6, size: 32, elements: !1771, identifier: "_ZTSN5clang18InclusionDirective13InclusionKindE")
!12 = !DIFile(filename: "llvm34/projects/clang/include/clang/Lex/PreprocessingRecord.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "14e396d29d0c8b929d46c7208bc24147")
!13 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "InclusionDirective", scope: !14, file: !12, line: 196, size: 384, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !15, identifier: "_ZTSN5clang18InclusionDirectiveE")
!14 = !DINamespace(name: "clang", scope: null)
!15 = !{!16, !1746, !1747, !1748, !1749, !1750, !1751, !1755, !1760, !1763, !1766, !1767, !1770}
!16 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !13, baseType: !17, flags: DIFlagPublic, extraData: i32 0)
!17 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PreprocessingDirective", scope: !14, file: !12, line: 124, size: 96, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !18, identifier: "_ZTSN5clang22PreprocessingDirectiveE")
!18 = !{!19, !1741, !1745}
!19 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !17, baseType: !20, flags: DIFlagPublic, extraData: i32 0)
!20 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PreprocessedEntity", scope: !14, file: !12, line: 47, size: 96, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !21, identifier: "_ZTSN5clang18PreprocessedEntityE")
!21 = !{!22, !31, !125, !129, !134, !137, !140, !1723, !1726, !1729, !1732, !1735, !1738}
!22 = !DIDerivedType(tag: DW_TAG_member, name: "Kind", scope: !20, file: !12, line: 75, baseType: !23, size: 32)
!23 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "EntityKind", scope: !20, file: !12, line: 50, baseType: !6, size: 32, elements: !24, identifier: "_ZTSN5clang18PreprocessedEntity10EntityKindE")
!24 = !{!25, !26, !27, !28, !29, !30}
!25 = !DIEnumerator(name: "InvalidKind", value: 0, isUnsigned: true)
!26 = !DIEnumerator(name: "MacroExpansionKind", value: 1, isUnsigned: true)
!27 = !DIEnumerator(name: "MacroDefinitionKind", value: 2, isUnsigned: true)
!28 = !DIEnumerator(name: "InclusionDirectiveKind", value: 3, isUnsigned: true)
!29 = !DIEnumerator(name: "FirstPreprocessingDirective", value: 2, isUnsigned: true)
!30 = !DIEnumerator(name: "LastPreprocessingDirective", value: 3, isUnsigned: true)
!31 = !DIDerivedType(tag: DW_TAG_member, name: "Range", scope: !20, file: !12, line: 78, baseType: !32, size: 64, offset: 32)
!32 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SourceRange", scope: !14, file: !33, line: 192, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !34, identifier: "_ZTSN5clang11SourceRangeE")
!33 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/SourceLocation.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "6fa740d6b2148f6e30f14b68326fa300")
!34 = !{!35, !97, !98, !102, !105, !108, !113, !114, !115, !116, !119, !120, !124}
!35 = !DIDerivedType(tag: DW_TAG_member, name: "B", scope: !32, file: !33, line: 193, baseType: !36, size: 32)
!36 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SourceLocation", scope: !14, file: !33, line: 87, size: 32, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !37, identifier: "_ZTSN5clang14SourceLocationE")
!37 = !{!38, !39, !43, !49, !50, !51, !52, !55, !58, !59, !63, !64, !65, !69, !74, !85, !94}
!38 = !DIDerivedType(tag: DW_TAG_member, name: "ID", scope: !36, file: !33, line: 88, baseType: !6, size: 32)
!39 = !DISubprogram(name: "SourceLocation", scope: !36, file: !33, line: 97, type: !40, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!40 = !DISubroutineType(types: !41)
!41 = !{null, !42}
!42 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !36, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!43 = !DISubprogram(name: "isFileID", linkageName: "_ZNK5clang14SourceLocation8isFileIDEv", scope: !36, file: !33, line: 99, type: !44, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!44 = !DISubroutineType(types: !45)
!45 = !{!46, !47}
!46 = !DIBasicType(name: "bool", size: 8, encoding: DW_ATE_boolean)
!47 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !48, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!48 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !36)
!49 = !DISubprogram(name: "isMacroID", linkageName: "_ZNK5clang14SourceLocation9isMacroIDEv", scope: !36, file: !33, line: 100, type: !44, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!50 = !DISubprogram(name: "isValid", linkageName: "_ZNK5clang14SourceLocation7isValidEv", scope: !36, file: !33, line: 107, type: !44, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!51 = !DISubprogram(name: "isInvalid", linkageName: "_ZNK5clang14SourceLocation9isInvalidEv", scope: !36, file: !33, line: 108, type: !44, scopeLine: 108, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!52 = !DISubprogram(name: "getOffset", linkageName: "_ZNK5clang14SourceLocation9getOffsetEv", scope: !36, file: !33, line: 112, type: !53, scopeLine: 112, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!53 = !DISubroutineType(types: !54)
!54 = !{!6, !47}
!55 = !DISubprogram(name: "getFileLoc", linkageName: "_ZN5clang14SourceLocation10getFileLocEj", scope: !36, file: !33, line: 116, type: !56, scopeLine: 116, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!56 = !DISubroutineType(types: !57)
!57 = !{!36, !6}
!58 = !DISubprogram(name: "getMacroLoc", linkageName: "_ZN5clang14SourceLocation11getMacroLocEj", scope: !36, file: !33, line: 123, type: !56, scopeLine: 123, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!59 = !DISubprogram(name: "getLocWithOffset", linkageName: "_ZNK5clang14SourceLocation16getLocWithOffsetEi", scope: !36, file: !33, line: 133, type: !60, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!60 = !DISubroutineType(types: !61)
!61 = !{!36, !47, !62}
!62 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!63 = !DISubprogram(name: "getRawEncoding", linkageName: "_ZNK5clang14SourceLocation14getRawEncodingEv", scope: !36, file: !33, line: 145, type: !53, scopeLine: 145, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!64 = !DISubprogram(name: "getFromRawEncoding", linkageName: "_ZN5clang14SourceLocation18getFromRawEncodingEj", scope: !36, file: !33, line: 151, type: !56, scopeLine: 151, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!65 = !DISubprogram(name: "getPtrEncoding", linkageName: "_ZNK5clang14SourceLocation14getPtrEncodingEv", scope: !36, file: !33, line: 162, type: !66, scopeLine: 162, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!66 = !DISubroutineType(types: !67)
!67 = !{!68, !47}
!68 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 64)
!69 = !DISubprogram(name: "getFromPtrEncoding", linkageName: "_ZN5clang14SourceLocation18getFromPtrEncodingEPKv", scope: !36, file: !33, line: 170, type: !70, scopeLine: 170, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!70 = !DISubroutineType(types: !71)
!71 = !{!36, !72}
!72 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !73, size: 64)
!73 = !DIDerivedType(tag: DW_TAG_const_type, baseType: null)
!74 = !DISubprogram(name: "print", linkageName: "_ZNK5clang14SourceLocation5printERN4llvm11raw_ostreamERKNS_13SourceManagerE", scope: !36, file: !33, line: 174, type: !75, scopeLine: 174, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!75 = !DISubroutineType(types: !76)
!76 = !{null, !47, !77, !81}
!77 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !78, size: 64)
!78 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "raw_ostream", scope: !80, file: !79, line: 47, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm11raw_ostreamE")
!79 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/LLVM.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "fe3bbe0ce03f58807015987f11a2006c")
!80 = !DINamespace(name: "llvm", scope: null)
!81 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !82, size: 64)
!82 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !83)
!83 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SourceManager", scope: !14, file: !84, line: 538, size: 4928, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang13SourceManagerE")
!84 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/SourceManager.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e6d975d790c3941a74fcadca377a23e0")
!85 = !DISubprogram(name: "printToString", linkageName: "_ZNK5clang14SourceLocation13printToStringB5cxx11ERKNS_13SourceManagerE", scope: !36, file: !33, line: 175, type: !86, scopeLine: 175, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!86 = !DISubroutineType(types: !87)
!87 = !{!88, !47, !81}
!88 = !DIDerivedType(tag: DW_TAG_typedef, name: "string", scope: !90, file: !89, line: 74, baseType: !92)
!89 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stringfwd.h", directory: "")
!90 = !DINamespace(name: "__cxx11", scope: !91, exportSymbols: true)
!91 = !DINamespace(name: "std", scope: null)
!92 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "basic_string<char, std::char_traits<char>, std::allocator<char> >", scope: !90, file: !93, line: 1607, size: 256, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE")
!93 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.tcc", directory: "")
!94 = !DISubprogram(name: "dump", linkageName: "_ZNK5clang14SourceLocation4dumpERKNS_13SourceManagerE", scope: !36, file: !33, line: 176, type: !95, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!95 = !DISubroutineType(types: !96)
!96 = !{null, !47, !81}
!97 = !DIDerivedType(tag: DW_TAG_member, name: "E", scope: !32, file: !33, line: 194, baseType: !36, size: 32, offset: 32)
!98 = !DISubprogram(name: "SourceRange", scope: !32, file: !33, line: 196, type: !99, scopeLine: 196, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!99 = !DISubroutineType(types: !100)
!100 = !{null, !101}
!101 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !32, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!102 = !DISubprogram(name: "SourceRange", scope: !32, file: !33, line: 197, type: !103, scopeLine: 197, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!103 = !DISubroutineType(types: !104)
!104 = !{null, !101, !36}
!105 = !DISubprogram(name: "SourceRange", scope: !32, file: !33, line: 198, type: !106, scopeLine: 198, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!106 = !DISubroutineType(types: !107)
!107 = !{null, !101, !36, !36}
!108 = !DISubprogram(name: "getBegin", linkageName: "_ZNK5clang11SourceRange8getBeginEv", scope: !32, file: !33, line: 200, type: !109, scopeLine: 200, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!109 = !DISubroutineType(types: !110)
!110 = !{!36, !111}
!111 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !112, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!112 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !32)
!113 = !DISubprogram(name: "getEnd", linkageName: "_ZNK5clang11SourceRange6getEndEv", scope: !32, file: !33, line: 201, type: !109, scopeLine: 201, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!114 = !DISubprogram(name: "setBegin", linkageName: "_ZN5clang11SourceRange8setBeginENS_14SourceLocationE", scope: !32, file: !33, line: 203, type: !103, scopeLine: 203, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!115 = !DISubprogram(name: "setEnd", linkageName: "_ZN5clang11SourceRange6setEndENS_14SourceLocationE", scope: !32, file: !33, line: 204, type: !103, scopeLine: 204, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!116 = !DISubprogram(name: "isValid", linkageName: "_ZNK5clang11SourceRange7isValidEv", scope: !32, file: !33, line: 206, type: !117, scopeLine: 206, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!117 = !DISubroutineType(types: !118)
!118 = !{!46, !111}
!119 = !DISubprogram(name: "isInvalid", linkageName: "_ZNK5clang11SourceRange9isInvalidEv", scope: !32, file: !33, line: 207, type: !117, scopeLine: 207, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!120 = !DISubprogram(name: "operator==", linkageName: "_ZNK5clang11SourceRangeeqERKS0_", scope: !32, file: !33, line: 209, type: !121, scopeLine: 209, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!121 = !DISubroutineType(types: !122)
!122 = !{!46, !111, !123}
!123 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !112, size: 64)
!124 = !DISubprogram(name: "operator!=", linkageName: "_ZNK5clang11SourceRangeneERKS0_", scope: !32, file: !33, line: 213, type: !121, scopeLine: 213, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!125 = !DISubprogram(name: "PreprocessedEntity", scope: !20, file: !12, line: 81, type: !126, scopeLine: 81, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!126 = !DISubroutineType(types: !127)
!127 = !{null, !128, !23, !32}
!128 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !20, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!129 = !DISubprogram(name: "getKind", linkageName: "_ZNK5clang18PreprocessedEntity7getKindEv", scope: !20, file: !12, line: 88, type: !130, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!130 = !DISubroutineType(types: !131)
!131 = !{!23, !132}
!132 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !133, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!133 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !20)
!134 = !DISubprogram(name: "getSourceRange", linkageName: "_ZNK5clang18PreprocessedEntity14getSourceRangeEv", scope: !20, file: !12, line: 92, type: !135, scopeLine: 92, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!135 = !DISubroutineType(types: !136)
!136 = !{!32, !132}
!137 = !DISubprogram(name: "isInvalid", linkageName: "_ZNK5clang18PreprocessedEntity9isInvalidEv", scope: !20, file: !12, line: 96, type: !138, scopeLine: 96, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!138 = !DISubroutineType(types: !139)
!139 = !{!46, !132}
!140 = !DISubprogram(name: "operator new", linkageName: "_ZN5clang18PreprocessedEntitynwEmRNS_19PreprocessingRecordEj", scope: !20, file: !12, line: 100, type: !141, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!141 = !DISubroutineType(types: !142)
!142 = !{!68, !143, !146, !6}
!143 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", file: !144, line: 46, baseType: !145)
!144 = !DIFile(filename: "llvm5/build/lib/clang/15.0.3/include/stddef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "b76978376d35d5cd171876ac58ac1256")
!145 = !DIBasicType(name: "unsigned long", size: 64, encoding: DW_ATE_unsigned)
!146 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !147, size: 64)
!147 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PreprocessingRecord", scope: !14, file: !12, line: 290, size: 1472, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !148, vtableHolder: !150)
!148 = !{!149, !152, !154, !157, !687, !688, !1092, !1272, !1332, !1345, !1349, !1352, !1357, !1360, !1363, !1364, !1367, !1371, !1374, !1377, !1380, !1383, !1386, !1420, !1421, !1422, !1423, !1481, !1484, !1487, !1490, !1494, !1497, !1500, !1513, !1516, !1517, !1710, !1713, !1714, !1717, !1720}
!149 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !147, baseType: !150, flags: DIFlagPublic, extraData: i32 0)
!150 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PPCallbacks", scope: !14, file: !151, line: 37, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang11PPCallbacksE")
!151 = !DIFile(filename: "llvm34/projects/clang/include/clang/Lex/PPCallbacks.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "fb2a9981872af2c0bd9119e8c0a1fd1a")
!152 = !DIDerivedType(tag: DW_TAG_member, name: "SourceMgr", scope: !147, file: !12, line: 291, baseType: !153, size: 64, offset: 64)
!153 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !83, size: 64)
!154 = !DIDerivedType(tag: DW_TAG_member, name: "BumpAlloc", scope: !147, file: !12, line: 294, baseType: !155, size: 576, offset: 128)
!155 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "BumpPtrAllocator", scope: !80, file: !156, line: 90, size: 576, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm16BumpPtrAllocatorE")
!156 = !DIFile(filename: "llvm34/include/llvm/Support/Allocator.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e9d7c083de36bffba1b1ac9811c014c8")
!157 = !DIDerivedType(tag: DW_TAG_member, name: "PreprocessedEntities", scope: !147, file: !12, line: 298, baseType: !158, size: 192, offset: 704)
!158 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<clang::PreprocessedEntity *, std::allocator<clang::PreprocessedEntity *> >", scope: !91, file: !159, line: 339, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !160, templateParams: !349, identifier: "_ZTSSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE")
!159 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h", directory: "", checksumkind: CSK_MD5, checksum: "ba305a1e10d49c66b3a70acbb63616a6")
!160 = !{!161, !350, !354, !360, !364, !370, !375, !379, !382, !385, !390, !391, !395, !398, !401, !404, !407, !469, !527, !528, !529, !534, !539, !540, !541, !542, !543, !544, !545, !548, !549, !552, !553, !554, !555, !558, !559, !567, !574, !577, !578, !579, !582, !585, !586, !587, !590, !593, !596, !600, !601, !604, !607, !610, !613, !616, !619, !622, !623, !624, !625, !626, !629, !630, !633, !634, !635, !642, !646, !649, !652, !671}
!161 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !158, baseType: !162, flags: DIFlagProtected, extraData: i32 0)
!162 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_base<clang::PreprocessedEntity *, std::allocator<clang::PreprocessedEntity *> >", scope: !91, file: !159, line: 81, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !163, templateParams: !349, identifier: "_ZTSSt12_Vector_baseIPN5clang18PreprocessedEntityESaIS2_EE")
!163 = !{!164, !303, !308, !313, !317, !320, !325, !328, !331, !334, !338, !341, !342, !345, !348}
!164 = !DIDerivedType(tag: DW_TAG_member, name: "_M_impl", scope: !162, file: !159, line: 290, baseType: !165, size: 192)
!165 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Vector_impl", scope: !162, file: !159, line: 88, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !166, identifier: "_ZTSNSt12_Vector_baseIPN5clang18PreprocessedEntityESaIS2_EE12_Vector_implE")
!166 = !{!167, !281, !284, !285, !286, !290, !295, !299}
!167 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !165, baseType: !168, extraData: i32 0)
!168 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Tp_alloc_type", scope: !162, file: !159, line: 84, baseType: !169)
!169 = !DIDerivedType(tag: DW_TAG_typedef, name: "other", scope: !171, file: !170, line: 117, baseType: !280)
!170 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/alloc_traits.h", directory: "")
!171 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "rebind<clang::PreprocessedEntity *>", scope: !172, file: !170, line: 116, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !232, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIPN5clang18PreprocessedEntityEES3_E6rebindIS3_EE")
!172 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__alloc_traits<std::allocator<clang::PreprocessedEntity *>, clang::PreprocessedEntity *>", scope: !5, file: !170, line: 50, size: 8, flags: DIFlagTypePassByValue, elements: !173, templateParams: !277, identifier: "_ZTSN9__gnu_cxx14__alloc_traitsISaIPN5clang18PreprocessedEntityEES3_EE")
!173 = !{!174, !263, !266, !270, !273, !274, !275, !276}
!174 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !172, baseType: !175, extraData: i32 0)
!175 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "allocator_traits<std::allocator<clang::PreprocessedEntity *> >", scope: !91, file: !176, line: 384, size: 8, flags: DIFlagTypePassByValue, elements: !177, templateParams: !261, identifier: "_ZTSSt16allocator_traitsISaIPN5clang18PreprocessedEntityEEE")
!176 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/alloc_traits.h", directory: "", checksumkind: CSK_MD5, checksum: "f7f651aab55acaadfc53aa53979a817c")
!177 = !{!178, !245, !249, !252, !258}
!178 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIPN5clang18PreprocessedEntityEEE8allocateERS3_m", scope: !175, file: !176, line: 435, type: !179, scopeLine: 435, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!179 = !DISubroutineType(types: !180)
!180 = !{!181, !184, !244}
!181 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !175, file: !176, line: 392, baseType: !182)
!182 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !183, size: 64)
!183 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !20, size: 64)
!184 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !185, size: 64)
!185 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !175, file: !176, line: 387, baseType: !186)
!186 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "allocator<clang::PreprocessedEntity *>", scope: !91, file: !187, line: 108, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !188, templateParams: !232, identifier: "_ZTSSaIPN5clang18PreprocessedEntityEE")
!187 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "9cafc7b584300736771313d46be845c3")
!188 = !{!189, !234, !238, !243}
!189 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !186, baseType: !190, flags: DIFlagPublic, extraData: i32 0)
!190 = !DIDerivedType(tag: DW_TAG_typedef, name: "__allocator_base<clang::PreprocessedEntity *>", scope: !91, file: !191, line: 48, baseType: !192)
!191 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8/bits/c++allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "9572fa47638d84b83d0311676a9766b8")
!192 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "new_allocator<clang::PreprocessedEntity *>", scope: !5, file: !193, line: 58, size: 8, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !194, templateParams: !232, identifier: "_ZTSN9__gnu_cxx13new_allocatorIPN5clang18PreprocessedEntityEEE")
!193 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/new_allocator.h", directory: "", checksumkind: CSK_MD5, checksum: "ece13daf300dfc0cac27dc2ea29129ca")
!194 = !{!195, !199, !204, !205, !212, !220, !226, !229}
!195 = !DISubprogram(name: "new_allocator", scope: !192, file: !193, line: 79, type: !196, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!196 = !DISubroutineType(types: !197)
!197 = !{null, !198}
!198 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !192, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!199 = !DISubprogram(name: "new_allocator", scope: !192, file: !193, line: 81, type: !200, scopeLine: 81, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!200 = !DISubroutineType(types: !201)
!201 = !{null, !198, !202}
!202 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !203, size: 64)
!203 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !192)
!204 = !DISubprogram(name: "~new_allocator", scope: !192, file: !193, line: 86, type: !196, scopeLine: 86, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!205 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorIPN5clang18PreprocessedEntityEE7addressERS3_", scope: !192, file: !193, line: 89, type: !206, scopeLine: 89, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!206 = !DISubroutineType(types: !207)
!207 = !{!208, !209, !210}
!208 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !192, file: !193, line: 63, baseType: !182)
!209 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !203, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!210 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !192, file: !193, line: 65, baseType: !211)
!211 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !183, size: 64)
!212 = !DISubprogram(name: "address", linkageName: "_ZNK9__gnu_cxx13new_allocatorIPN5clang18PreprocessedEntityEE7addressERKS3_", scope: !192, file: !193, line: 93, type: !213, scopeLine: 93, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!213 = !DISubroutineType(types: !214)
!214 = !{!215, !209, !218}
!215 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_pointer", scope: !192, file: !193, line: 64, baseType: !216)
!216 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !217, size: 64)
!217 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !183)
!218 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !192, file: !193, line: 66, baseType: !219)
!219 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !217, size: 64)
!220 = !DISubprogram(name: "allocate", linkageName: "_ZN9__gnu_cxx13new_allocatorIPN5clang18PreprocessedEntityEE8allocateEmPKv", scope: !192, file: !193, line: 99, type: !221, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!221 = !DISubroutineType(types: !222)
!222 = !{!208, !198, !223, !72}
!223 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !193, line: 61, baseType: !224)
!224 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", scope: !91, file: !225, line: 238, baseType: !145)
!225 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8/bits/c++config.h", directory: "", checksumkind: CSK_MD5, checksum: "5ab2830680f5a52514c973f039a03c0a")
!226 = !DISubprogram(name: "deallocate", linkageName: "_ZN9__gnu_cxx13new_allocatorIPN5clang18PreprocessedEntityEE10deallocateEPS3_m", scope: !192, file: !193, line: 116, type: !227, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!227 = !DISubroutineType(types: !228)
!228 = !{null, !198, !208, !223}
!229 = !DISubprogram(name: "max_size", linkageName: "_ZNK9__gnu_cxx13new_allocatorIPN5clang18PreprocessedEntityEE8max_sizeEv", scope: !192, file: !193, line: 129, type: !230, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!230 = !DISubroutineType(types: !231)
!231 = !{!223, !209}
!232 = !{!233}
!233 = !DITemplateTypeParameter(name: "_Tp", type: !183)
!234 = !DISubprogram(name: "allocator", scope: !186, file: !187, line: 131, type: !235, scopeLine: 131, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!235 = !DISubroutineType(types: !236)
!236 = !{null, !237}
!237 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !186, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!238 = !DISubprogram(name: "allocator", scope: !186, file: !187, line: 133, type: !239, scopeLine: 133, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!239 = !DISubroutineType(types: !240)
!240 = !{null, !237, !241}
!241 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !242, size: 64)
!242 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !186)
!243 = !DISubprogram(name: "~allocator", scope: !186, file: !187, line: 139, type: !235, scopeLine: 139, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!244 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !176, line: 407, baseType: !224)
!245 = !DISubprogram(name: "allocate", linkageName: "_ZNSt16allocator_traitsISaIPN5clang18PreprocessedEntityEEE8allocateERS3_mPKv", scope: !175, file: !176, line: 449, type: !246, scopeLine: 449, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!246 = !DISubroutineType(types: !247)
!247 = !{!181, !184, !244, !248}
!248 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_void_pointer", file: !176, line: 401, baseType: !72)
!249 = !DISubprogram(name: "deallocate", linkageName: "_ZNSt16allocator_traitsISaIPN5clang18PreprocessedEntityEEE10deallocateERS3_PS2_m", scope: !175, file: !176, line: 461, type: !250, scopeLine: 461, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!250 = !DISubroutineType(types: !251)
!251 = !{null, !184, !181, !244}
!252 = !DISubprogram(name: "max_size", linkageName: "_ZNSt16allocator_traitsISaIPN5clang18PreprocessedEntityEEE8max_sizeERKS3_", scope: !175, file: !176, line: 495, type: !253, scopeLine: 495, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!253 = !DISubroutineType(types: !254)
!254 = !{!255, !256}
!255 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !175, file: !176, line: 407, baseType: !224)
!256 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !257, size: 64)
!257 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !185)
!258 = !DISubprogram(name: "select_on_container_copy_construction", linkageName: "_ZNSt16allocator_traitsISaIPN5clang18PreprocessedEntityEEE37select_on_container_copy_constructionERKS3_", scope: !175, file: !176, line: 504, type: !259, scopeLine: 504, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!259 = !DISubroutineType(types: !260)
!260 = !{!185, !256}
!261 = !{!262}
!262 = !DITemplateTypeParameter(name: "_Alloc", type: !186)
!263 = !DISubprogram(name: "_S_select_on_copy", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPN5clang18PreprocessedEntityEES3_E17_S_select_on_copyERKS4_", scope: !172, file: !170, line: 94, type: !264, scopeLine: 94, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!264 = !DISubroutineType(types: !265)
!265 = !{!186, !241}
!266 = !DISubprogram(name: "_S_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPN5clang18PreprocessedEntityEES3_E10_S_on_swapERS4_S6_", scope: !172, file: !170, line: 97, type: !267, scopeLine: 97, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!267 = !DISubroutineType(types: !268)
!268 = !{null, !269, !269}
!269 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !186, size: 64)
!270 = !DISubprogram(name: "_S_propagate_on_copy_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPN5clang18PreprocessedEntityEES3_E27_S_propagate_on_copy_assignEv", scope: !172, file: !170, line: 100, type: !271, scopeLine: 100, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!271 = !DISubroutineType(types: !272)
!272 = !{!46}
!273 = !DISubprogram(name: "_S_propagate_on_move_assign", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPN5clang18PreprocessedEntityEES3_E27_S_propagate_on_move_assignEv", scope: !172, file: !170, line: 103, type: !271, scopeLine: 103, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!274 = !DISubprogram(name: "_S_propagate_on_swap", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPN5clang18PreprocessedEntityEES3_E20_S_propagate_on_swapEv", scope: !172, file: !170, line: 106, type: !271, scopeLine: 106, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!275 = !DISubprogram(name: "_S_always_equal", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPN5clang18PreprocessedEntityEES3_E15_S_always_equalEv", scope: !172, file: !170, line: 109, type: !271, scopeLine: 109, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!276 = !DISubprogram(name: "_S_nothrow_move", linkageName: "_ZN9__gnu_cxx14__alloc_traitsISaIPN5clang18PreprocessedEntityEES3_E15_S_nothrow_moveEv", scope: !172, file: !170, line: 112, type: !271, scopeLine: 112, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!277 = !{!262, !278}
!278 = !DITemplateTypeParameter(type: !183)
!279 = !{}
!280 = !DIDerivedType(tag: DW_TAG_typedef, name: "rebind_alloc<clang::PreprocessedEntity *>", scope: !175, file: !176, line: 422, baseType: !186)
!281 = !DIDerivedType(tag: DW_TAG_member, name: "_M_start", scope: !165, file: !159, line: 91, baseType: !282, size: 64)
!282 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !162, file: !159, line: 86, baseType: !283)
!283 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !172, file: !170, line: 59, baseType: !181)
!284 = !DIDerivedType(tag: DW_TAG_member, name: "_M_finish", scope: !165, file: !159, line: 92, baseType: !282, size: 64, offset: 64)
!285 = !DIDerivedType(tag: DW_TAG_member, name: "_M_end_of_storage", scope: !165, file: !159, line: 93, baseType: !282, size: 64, offset: 128)
!286 = !DISubprogram(name: "_Vector_impl", scope: !165, file: !159, line: 95, type: !287, scopeLine: 95, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!287 = !DISubroutineType(types: !288)
!288 = !{null, !289}
!289 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !165, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!290 = !DISubprogram(name: "_Vector_impl", scope: !165, file: !159, line: 99, type: !291, scopeLine: 99, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!291 = !DISubroutineType(types: !292)
!292 = !{null, !289, !293}
!293 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !294, size: 64)
!294 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !168)
!295 = !DISubprogram(name: "_Vector_impl", scope: !165, file: !159, line: 104, type: !296, scopeLine: 104, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!296 = !DISubroutineType(types: !297)
!297 = !{null, !289, !298}
!298 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !168, size: 64)
!299 = !DISubprogram(name: "_M_swap_data", linkageName: "_ZNSt12_Vector_baseIPN5clang18PreprocessedEntityESaIS2_EE12_Vector_impl12_M_swap_dataERS5_", scope: !165, file: !159, line: 110, type: !300, scopeLine: 110, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!300 = !DISubroutineType(types: !301)
!301 = !{null, !289, !302}
!302 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !165, size: 64)
!303 = !DISubprogram(name: "_M_get_Tp_allocator", linkageName: "_ZNSt12_Vector_baseIPN5clang18PreprocessedEntityESaIS2_EE19_M_get_Tp_allocatorEv", scope: !162, file: !159, line: 237, type: !304, scopeLine: 237, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!304 = !DISubroutineType(types: !305)
!305 = !{!306, !307}
!306 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !168, size: 64)
!307 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !162, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!308 = !DISubprogram(name: "_M_get_Tp_allocator", linkageName: "_ZNKSt12_Vector_baseIPN5clang18PreprocessedEntityESaIS2_EE19_M_get_Tp_allocatorEv", scope: !162, file: !159, line: 241, type: !309, scopeLine: 241, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!309 = !DISubroutineType(types: !310)
!310 = !{!293, !311}
!311 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !312, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!312 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !162)
!313 = !DISubprogram(name: "get_allocator", linkageName: "_ZNKSt12_Vector_baseIPN5clang18PreprocessedEntityESaIS2_EE13get_allocatorEv", scope: !162, file: !159, line: 245, type: !314, scopeLine: 245, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!314 = !DISubroutineType(types: !315)
!315 = !{!316, !311}
!316 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !162, file: !159, line: 234, baseType: !186)
!317 = !DISubprogram(name: "_Vector_base", scope: !162, file: !159, line: 248, type: !318, scopeLine: 248, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!318 = !DISubroutineType(types: !319)
!319 = !{null, !307}
!320 = !DISubprogram(name: "_Vector_base", scope: !162, file: !159, line: 251, type: !321, scopeLine: 251, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!321 = !DISubroutineType(types: !322)
!322 = !{null, !307, !323}
!323 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !324, size: 64)
!324 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !316)
!325 = !DISubprogram(name: "_Vector_base", scope: !162, file: !159, line: 254, type: !326, scopeLine: 254, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!326 = !DISubroutineType(types: !327)
!327 = !{null, !307, !224}
!328 = !DISubprogram(name: "_Vector_base", scope: !162, file: !159, line: 258, type: !329, scopeLine: 258, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!329 = !DISubroutineType(types: !330)
!330 = !{null, !307, !224, !323}
!331 = !DISubprogram(name: "_Vector_base", scope: !162, file: !159, line: 263, type: !332, scopeLine: 263, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!332 = !DISubroutineType(types: !333)
!333 = !{null, !307, !298}
!334 = !DISubprogram(name: "_Vector_base", scope: !162, file: !159, line: 266, type: !335, scopeLine: 266, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!335 = !DISubroutineType(types: !336)
!336 = !{null, !307, !337}
!337 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !162, size: 64)
!338 = !DISubprogram(name: "_Vector_base", scope: !162, file: !159, line: 270, type: !339, scopeLine: 270, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!339 = !DISubroutineType(types: !340)
!340 = !{null, !307, !337, !323}
!341 = !DISubprogram(name: "~_Vector_base", scope: !162, file: !159, line: 283, type: !318, scopeLine: 283, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!342 = !DISubprogram(name: "_M_allocate", linkageName: "_ZNSt12_Vector_baseIPN5clang18PreprocessedEntityESaIS2_EE11_M_allocateEm", scope: !162, file: !159, line: 293, type: !343, scopeLine: 293, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!343 = !DISubroutineType(types: !344)
!344 = !{!282, !307, !224}
!345 = !DISubprogram(name: "_M_deallocate", linkageName: "_ZNSt12_Vector_baseIPN5clang18PreprocessedEntityESaIS2_EE13_M_deallocateEPS2_m", scope: !162, file: !159, line: 300, type: !346, scopeLine: 300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!346 = !DISubroutineType(types: !347)
!347 = !{null, !307, !282, !224}
!348 = !DISubprogram(name: "_M_create_storage", linkageName: "_ZNSt12_Vector_baseIPN5clang18PreprocessedEntityESaIS2_EE17_M_create_storageEm", scope: !162, file: !159, line: 309, type: !326, scopeLine: 309, flags: DIFlagPrivate | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!349 = !{!233, !262}
!350 = !DISubprogram(name: "vector", scope: !158, file: !159, line: 391, type: !351, scopeLine: 391, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!351 = !DISubroutineType(types: !352)
!352 = !{null, !353}
!353 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !158, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!354 = !DISubprogram(name: "vector", scope: !158, file: !159, line: 402, type: !355, scopeLine: 402, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!355 = !DISubroutineType(types: !356)
!356 = !{null, !353, !357}
!357 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !358, size: 64)
!358 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !359)
!359 = !DIDerivedType(tag: DW_TAG_typedef, name: "allocator_type", scope: !158, file: !159, line: 376, baseType: !186)
!360 = !DISubprogram(name: "vector", scope: !158, file: !159, line: 415, type: !361, scopeLine: 415, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!361 = !DISubroutineType(types: !362)
!362 = !{null, !353, !363, !357}
!363 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !159, line: 374, baseType: !224)
!364 = !DISubprogram(name: "vector", scope: !158, file: !159, line: 427, type: !365, scopeLine: 427, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!365 = !DISubroutineType(types: !366)
!366 = !{null, !353, !363, !367, !357}
!367 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !368, size: 64)
!368 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !369)
!369 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !158, file: !159, line: 364, baseType: !183)
!370 = !DISubprogram(name: "vector", scope: !158, file: !159, line: 458, type: !371, scopeLine: 458, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!371 = !DISubroutineType(types: !372)
!372 = !{null, !353, !373}
!373 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !374, size: 64)
!374 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !158)
!375 = !DISubprogram(name: "vector", scope: !158, file: !159, line: 476, type: !376, scopeLine: 476, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!376 = !DISubroutineType(types: !377)
!377 = !{null, !353, !378}
!378 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !158, size: 64)
!379 = !DISubprogram(name: "vector", scope: !158, file: !159, line: 480, type: !380, scopeLine: 480, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!380 = !DISubroutineType(types: !381)
!381 = !{null, !353, !373, !357}
!382 = !DISubprogram(name: "vector", scope: !158, file: !159, line: 490, type: !383, scopeLine: 490, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!383 = !DISubroutineType(types: !384)
!384 = !{null, !353, !378, !357}
!385 = !DISubprogram(name: "vector", scope: !158, file: !159, line: 515, type: !386, scopeLine: 515, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!386 = !DISubroutineType(types: !387)
!387 = !{null, !353, !388, !357}
!388 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<clang::PreprocessedEntity *>", scope: !91, file: !389, line: 47, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listIPN5clang18PreprocessedEntityEE")
!389 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/initializer_list", directory: "")
!390 = !DISubprogram(name: "~vector", scope: !158, file: !159, line: 565, type: !351, scopeLine: 565, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!391 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EEaSERKS4_", scope: !158, file: !159, line: 582, type: !392, scopeLine: 582, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!392 = !DISubroutineType(types: !393)
!393 = !{!394, !353, !373}
!394 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !158, size: 64)
!395 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EEaSEOS4_", scope: !158, file: !159, line: 596, type: !396, scopeLine: 596, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!396 = !DISubroutineType(types: !397)
!397 = !{!394, !353, !378}
!398 = !DISubprogram(name: "operator=", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EEaSESt16initializer_listIS2_E", scope: !158, file: !159, line: 617, type: !399, scopeLine: 617, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!399 = !DISubroutineType(types: !400)
!400 = !{!394, !353, !388}
!401 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE6assignEmRKS2_", scope: !158, file: !159, line: 636, type: !402, scopeLine: 636, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!402 = !DISubroutineType(types: !403)
!403 = !{null, !353, !363, !367}
!404 = !DISubprogram(name: "assign", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE6assignESt16initializer_listIS2_E", scope: !158, file: !159, line: 681, type: !405, scopeLine: 681, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!405 = !DISubroutineType(types: !406)
!406 = !{null, !353, !388}
!407 = !DISubprogram(name: "begin", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE5beginEv", scope: !158, file: !159, line: 698, type: !408, scopeLine: 698, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!408 = !DISubroutineType(types: !409)
!409 = !{!410, !353}
!410 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !158, file: !159, line: 369, baseType: !411)
!411 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<clang::PreprocessedEntity **, std::vector<clang::PreprocessedEntity *, std::allocator<clang::PreprocessedEntity *> > >", scope: !5, file: !412, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !413, templateParams: !467, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEE")
!412 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_iterator.h", directory: "", checksumkind: CSK_MD5, checksum: "43ca426be47f2e0c5f7f184d7d27a436")
!413 = !{!414, !415, !419, !424, !435, !440, !444, !447, !448, !449, !456, !459, !462, !463, !464}
!414 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !411, file: !412, line: 767, baseType: !182, size: 64, flags: DIFlagProtected)
!415 = !DISubprogram(name: "__normal_iterator", scope: !411, file: !412, line: 779, type: !416, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!416 = !DISubroutineType(types: !417)
!417 = !{null, !418}
!418 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !411, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!419 = !DISubprogram(name: "__normal_iterator", scope: !411, file: !412, line: 783, type: !420, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!420 = !DISubroutineType(types: !421)
!421 = !{null, !418, !422}
!422 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !423, size: 64)
!423 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !182)
!424 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEdeEv", scope: !411, file: !412, line: 796, type: !425, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!425 = !DISubroutineType(types: !426)
!426 = !{!427, !433}
!427 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !411, file: !412, line: 776, baseType: !428)
!428 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !430, file: !429, line: 184, baseType: !211)
!429 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_iterator_base_types.h", directory: "")
!430 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<clang::PreprocessedEntity **>", scope: !91, file: !429, line: 178, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !431, identifier: "_ZTSSt15iterator_traitsIPPN5clang18PreprocessedEntityEE")
!431 = !{!432}
!432 = !DITemplateTypeParameter(name: "_Iterator", type: !182)
!433 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !434, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!434 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !411)
!435 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEptEv", scope: !411, file: !412, line: 800, type: !436, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!436 = !DISubroutineType(types: !437)
!437 = !{!438, !433}
!438 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !411, file: !412, line: 777, baseType: !439)
!439 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !430, file: !429, line: 183, baseType: !182)
!440 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEppEv", scope: !411, file: !412, line: 804, type: !441, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!441 = !DISubroutineType(types: !442)
!442 = !{!443, !418}
!443 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !411, size: 64)
!444 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEppEi", scope: !411, file: !412, line: 811, type: !445, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!445 = !DISubroutineType(types: !446)
!446 = !{!411, !418, !62}
!447 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEmmEv", scope: !411, file: !412, line: 816, type: !441, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!448 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEmmEi", scope: !411, file: !412, line: 823, type: !445, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!449 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEixEl", scope: !411, file: !412, line: 828, type: !450, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!450 = !DISubroutineType(types: !451)
!451 = !{!427, !433, !452}
!452 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !411, file: !412, line: 775, baseType: !453)
!453 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !430, file: !429, line: 182, baseType: !454)
!454 = !DIDerivedType(tag: DW_TAG_typedef, name: "ptrdiff_t", scope: !91, file: !225, line: 239, baseType: !455)
!455 = !DIBasicType(name: "long", size: 64, encoding: DW_ATE_signed)
!456 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEpLEl", scope: !411, file: !412, line: 832, type: !457, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!457 = !DISubroutineType(types: !458)
!458 = !{!443, !418, !452}
!459 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEplEl", scope: !411, file: !412, line: 836, type: !460, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!460 = !DISubroutineType(types: !461)
!461 = !{!411, !433, !452}
!462 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEmIEl", scope: !411, file: !412, line: 840, type: !457, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!463 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEmiEl", scope: !411, file: !412, line: 844, type: !460, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!464 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEE4baseEv", scope: !411, file: !412, line: 848, type: !465, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!465 = !DISubroutineType(types: !466)
!466 = !{!422, !433}
!467 = !{!432, !468}
!468 = !DITemplateTypeParameter(name: "_Container", type: !158)
!469 = !DISubprogram(name: "begin", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE5beginEv", scope: !158, file: !159, line: 707, type: !470, scopeLine: 707, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!470 = !DISubroutineType(types: !471)
!471 = !{!472, !526}
!472 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !158, file: !159, line: 371, baseType: !473)
!473 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__normal_iterator<clang::PreprocessedEntity *const *, std::vector<clang::PreprocessedEntity *, std::allocator<clang::PreprocessedEntity *> > >", scope: !5, file: !412, line: 764, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !474, templateParams: !525, identifier: "_ZTSN9__gnu_cxx17__normal_iteratorIPKPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEE")
!474 = !{!475, !476, !480, !485, !495, !500, !504, !507, !508, !509, !514, !517, !520, !521, !522}
!475 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !473, file: !412, line: 767, baseType: !216, size: 64, flags: DIFlagProtected)
!476 = !DISubprogram(name: "__normal_iterator", scope: !473, file: !412, line: 779, type: !477, scopeLine: 779, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!477 = !DISubroutineType(types: !478)
!478 = !{null, !479}
!479 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !473, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!480 = !DISubprogram(name: "__normal_iterator", scope: !473, file: !412, line: 783, type: !481, scopeLine: 783, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!481 = !DISubroutineType(types: !482)
!482 = !{null, !479, !483}
!483 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !484, size: 64)
!484 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !216)
!485 = !DISubprogram(name: "operator*", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEdeEv", scope: !473, file: !412, line: 796, type: !486, scopeLine: 796, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!486 = !DISubroutineType(types: !487)
!487 = !{!488, !493}
!488 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !473, file: !412, line: 776, baseType: !489)
!489 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !490, file: !429, line: 195, baseType: !219)
!490 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator_traits<clang::PreprocessedEntity *const *>", scope: !91, file: !429, line: 189, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !491, identifier: "_ZTSSt15iterator_traitsIPKPN5clang18PreprocessedEntityEE")
!491 = !{!492}
!492 = !DITemplateTypeParameter(name: "_Iterator", type: !216)
!493 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !494, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!494 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !473)
!495 = !DISubprogram(name: "operator->", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEptEv", scope: !473, file: !412, line: 800, type: !496, scopeLine: 800, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!496 = !DISubroutineType(types: !497)
!497 = !{!498, !493}
!498 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !473, file: !412, line: 777, baseType: !499)
!499 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !490, file: !429, line: 194, baseType: !216)
!500 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEppEv", scope: !473, file: !412, line: 804, type: !501, scopeLine: 804, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!501 = !DISubroutineType(types: !502)
!502 = !{!503, !479}
!503 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !473, size: 64)
!504 = !DISubprogram(name: "operator++", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEppEi", scope: !473, file: !412, line: 811, type: !505, scopeLine: 811, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!505 = !DISubroutineType(types: !506)
!506 = !{!473, !479, !62}
!507 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEmmEv", scope: !473, file: !412, line: 816, type: !501, scopeLine: 816, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!508 = !DISubprogram(name: "operator--", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEmmEi", scope: !473, file: !412, line: 823, type: !505, scopeLine: 823, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!509 = !DISubprogram(name: "operator[]", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEixEl", scope: !473, file: !412, line: 828, type: !510, scopeLine: 828, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!510 = !DISubroutineType(types: !511)
!511 = !{!488, !493, !512}
!512 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !473, file: !412, line: 775, baseType: !513)
!513 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !490, file: !429, line: 193, baseType: !454)
!514 = !DISubprogram(name: "operator+=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEpLEl", scope: !473, file: !412, line: 832, type: !515, scopeLine: 832, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!515 = !DISubroutineType(types: !516)
!516 = !{!503, !479, !512}
!517 = !DISubprogram(name: "operator+", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEplEl", scope: !473, file: !412, line: 836, type: !518, scopeLine: 836, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!518 = !DISubroutineType(types: !519)
!519 = !{!473, !493, !512}
!520 = !DISubprogram(name: "operator-=", linkageName: "_ZN9__gnu_cxx17__normal_iteratorIPKPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEmIEl", scope: !473, file: !412, line: 840, type: !515, scopeLine: 840, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!521 = !DISubprogram(name: "operator-", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEEmiEl", scope: !473, file: !412, line: 844, type: !518, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!522 = !DISubprogram(name: "base", linkageName: "_ZNK9__gnu_cxx17__normal_iteratorIPKPN5clang18PreprocessedEntityESt6vectorIS3_SaIS3_EEE4baseEv", scope: !473, file: !412, line: 848, type: !523, scopeLine: 848, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!523 = !DISubroutineType(types: !524)
!524 = !{!483, !493}
!525 = !{!492, !468}
!526 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !374, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!527 = !DISubprogram(name: "end", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE3endEv", scope: !158, file: !159, line: 716, type: !408, scopeLine: 716, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!528 = !DISubprogram(name: "end", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE3endEv", scope: !158, file: !159, line: 725, type: !470, scopeLine: 725, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!529 = !DISubprogram(name: "rbegin", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE6rbeginEv", scope: !158, file: !159, line: 734, type: !530, scopeLine: 734, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!530 = !DISubroutineType(types: !531)
!531 = !{!532, !353}
!532 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !158, file: !159, line: 373, baseType: !533)
!533 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<clang::PreprocessedEntity **, std::vector<clang::PreprocessedEntity *, std::allocator<clang::PreprocessedEntity *> > > >", scope: !91, file: !412, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPPN5clang18PreprocessedEntityESt6vectorIS4_SaIS4_EEEEE")
!534 = !DISubprogram(name: "rbegin", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE6rbeginEv", scope: !158, file: !159, line: 743, type: !535, scopeLine: 743, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!535 = !DISubroutineType(types: !536)
!536 = !{!537, !526}
!537 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reverse_iterator", scope: !158, file: !159, line: 372, baseType: !538)
!538 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<__gnu_cxx::__normal_iterator<clang::PreprocessedEntity *const *, std::vector<clang::PreprocessedEntity *, std::allocator<clang::PreprocessedEntity *> > > >", scope: !91, file: !412, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIN9__gnu_cxx17__normal_iteratorIPKPN5clang18PreprocessedEntityESt6vectorIS4_SaIS4_EEEEE")
!539 = !DISubprogram(name: "rend", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE4rendEv", scope: !158, file: !159, line: 752, type: !530, scopeLine: 752, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!540 = !DISubprogram(name: "rend", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE4rendEv", scope: !158, file: !159, line: 761, type: !535, scopeLine: 761, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!541 = !DISubprogram(name: "cbegin", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE6cbeginEv", scope: !158, file: !159, line: 771, type: !470, scopeLine: 771, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!542 = !DISubprogram(name: "cend", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE4cendEv", scope: !158, file: !159, line: 780, type: !470, scopeLine: 780, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!543 = !DISubprogram(name: "crbegin", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE7crbeginEv", scope: !158, file: !159, line: 789, type: !535, scopeLine: 789, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!544 = !DISubprogram(name: "crend", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE5crendEv", scope: !158, file: !159, line: 798, type: !535, scopeLine: 798, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!545 = !DISubprogram(name: "size", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE4sizeEv", scope: !158, file: !159, line: 805, type: !546, scopeLine: 805, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!546 = !DISubroutineType(types: !547)
!547 = !{!363, !526}
!548 = !DISubprogram(name: "max_size", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE8max_sizeEv", scope: !158, file: !159, line: 810, type: !546, scopeLine: 810, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!549 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE6resizeEm", scope: !158, file: !159, line: 824, type: !550, scopeLine: 824, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!550 = !DISubroutineType(types: !551)
!551 = !{null, !353, !363}
!552 = !DISubprogram(name: "resize", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE6resizeEmRKS2_", scope: !158, file: !159, line: 844, type: !402, scopeLine: 844, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!553 = !DISubprogram(name: "shrink_to_fit", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE13shrink_to_fitEv", scope: !158, file: !159, line: 876, type: !351, scopeLine: 876, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!554 = !DISubprogram(name: "capacity", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE8capacityEv", scope: !158, file: !159, line: 885, type: !546, scopeLine: 885, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!555 = !DISubprogram(name: "empty", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE5emptyEv", scope: !158, file: !159, line: 894, type: !556, scopeLine: 894, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!556 = !DISubroutineType(types: !557)
!557 = !{!46, !526}
!558 = !DISubprogram(name: "reserve", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE7reserveEm", scope: !158, file: !159, line: 915, type: !550, scopeLine: 915, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!559 = !DISubprogram(name: "operator[]", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EEixEm", scope: !158, file: !159, line: 930, type: !560, scopeLine: 930, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!560 = !DISubroutineType(types: !561)
!561 = !{!562, !353, !363}
!562 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !158, file: !159, line: 367, baseType: !563)
!563 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !172, file: !170, line: 64, baseType: !564)
!564 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !565, size: 64)
!565 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !172, file: !170, line: 58, baseType: !566)
!566 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !175, file: !176, line: 389, baseType: !183)
!567 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EEixEm", scope: !158, file: !159, line: 948, type: !568, scopeLine: 948, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!568 = !DISubroutineType(types: !569)
!569 = !{!570, !526, !363}
!570 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !158, file: !159, line: 368, baseType: !571)
!571 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !172, file: !170, line: 65, baseType: !572)
!572 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !573, size: 64)
!573 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !565)
!574 = !DISubprogram(name: "_M_range_check", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE14_M_range_checkEm", scope: !158, file: !159, line: 957, type: !575, scopeLine: 957, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!575 = !DISubroutineType(types: !576)
!576 = !{null, !526, !363}
!577 = !DISubprogram(name: "at", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE2atEm", scope: !158, file: !159, line: 979, type: !560, scopeLine: 979, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!578 = !DISubprogram(name: "at", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE2atEm", scope: !158, file: !159, line: 997, type: !568, scopeLine: 997, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!579 = !DISubprogram(name: "front", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE5frontEv", scope: !158, file: !159, line: 1008, type: !580, scopeLine: 1008, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!580 = !DISubroutineType(types: !581)
!581 = !{!562, !353}
!582 = !DISubprogram(name: "front", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE5frontEv", scope: !158, file: !159, line: 1019, type: !583, scopeLine: 1019, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!583 = !DISubroutineType(types: !584)
!584 = !{!570, !526}
!585 = !DISubprogram(name: "back", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE4backEv", scope: !158, file: !159, line: 1030, type: !580, scopeLine: 1030, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!586 = !DISubprogram(name: "back", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE4backEv", scope: !158, file: !159, line: 1041, type: !583, scopeLine: 1041, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!587 = !DISubprogram(name: "data", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE4dataEv", scope: !158, file: !159, line: 1055, type: !588, scopeLine: 1055, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!588 = !DISubroutineType(types: !589)
!589 = !{!182, !353}
!590 = !DISubprogram(name: "data", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE4dataEv", scope: !158, file: !159, line: 1059, type: !591, scopeLine: 1059, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!591 = !DISubroutineType(types: !592)
!592 = !{!216, !526}
!593 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE9push_backERKS2_", scope: !158, file: !159, line: 1074, type: !594, scopeLine: 1074, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!594 = !DISubroutineType(types: !595)
!595 = !{null, !353, !367}
!596 = !DISubprogram(name: "push_back", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE9push_backEOS2_", scope: !158, file: !159, line: 1090, type: !597, scopeLine: 1090, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!597 = !DISubroutineType(types: !598)
!598 = !{null, !353, !599}
!599 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !369, size: 64)
!600 = !DISubprogram(name: "pop_back", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE8pop_backEv", scope: !158, file: !159, line: 1112, type: !351, scopeLine: 1112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!601 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EERS7_", scope: !158, file: !159, line: 1150, type: !602, scopeLine: 1150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!602 = !DISubroutineType(types: !603)
!603 = !{!410, !353, !472, !367}
!604 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EEOS2_", scope: !158, file: !159, line: 1180, type: !605, scopeLine: 1180, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!605 = !DISubroutineType(types: !606)
!606 = !{!410, !353, !472, !599}
!607 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EESt16initializer_listIS2_E", scope: !158, file: !159, line: 1197, type: !608, scopeLine: 1197, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!608 = !DISubroutineType(types: !609)
!609 = !{!410, !353, !472, !388}
!610 = !DISubprogram(name: "insert", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE6insertEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EEmRS7_", scope: !158, file: !159, line: 1222, type: !611, scopeLine: 1222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!611 = !DISubroutineType(types: !612)
!612 = !{!410, !353, !472, !363, !367}
!613 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE5eraseEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EE", scope: !158, file: !159, line: 1317, type: !614, scopeLine: 1317, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!614 = !DISubroutineType(types: !615)
!615 = !{!410, !353, !472}
!616 = !DISubprogram(name: "erase", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE5eraseEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EES9_", scope: !158, file: !159, line: 1344, type: !617, scopeLine: 1344, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!617 = !DISubroutineType(types: !618)
!618 = !{!410, !353, !472, !472}
!619 = !DISubprogram(name: "swap", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE4swapERS4_", scope: !158, file: !159, line: 1367, type: !620, scopeLine: 1367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!620 = !DISubroutineType(types: !621)
!621 = !{null, !353, !394}
!622 = !DISubprogram(name: "clear", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE5clearEv", scope: !158, file: !159, line: 1385, type: !351, scopeLine: 1385, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!623 = !DISubprogram(name: "_M_fill_initialize", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE18_M_fill_initializeEmRKS2_", scope: !158, file: !159, line: 1477, type: !402, scopeLine: 1477, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!624 = !DISubprogram(name: "_M_default_initialize", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE21_M_default_initializeEm", scope: !158, file: !159, line: 1487, type: !550, scopeLine: 1487, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!625 = !DISubprogram(name: "_M_fill_assign", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE14_M_fill_assignEmRKS2_", scope: !158, file: !159, line: 1529, type: !402, scopeLine: 1529, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!626 = !DISubprogram(name: "_M_fill_insert", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS2_S4_EEmRKS2_", scope: !158, file: !159, line: 1568, type: !627, scopeLine: 1568, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!627 = !DISubroutineType(types: !628)
!628 = !{null, !353, !410, !363, !367}
!629 = !DISubprogram(name: "_M_default_append", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE17_M_default_appendEm", scope: !158, file: !159, line: 1573, type: !550, scopeLine: 1573, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!630 = !DISubprogram(name: "_M_shrink_to_fit", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE16_M_shrink_to_fitEv", scope: !158, file: !159, line: 1576, type: !631, scopeLine: 1576, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!631 = !DISubroutineType(types: !632)
!632 = !{!46, !353}
!633 = !DISubprogram(name: "_M_insert_rval", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE14_M_insert_rvalEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EEOS2_", scope: !158, file: !159, line: 1625, type: !605, scopeLine: 1625, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!634 = !DISubprogram(name: "_M_emplace_aux", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE14_M_emplace_auxEN9__gnu_cxx17__normal_iteratorIPKS2_S4_EEOS2_", scope: !158, file: !159, line: 1634, type: !605, scopeLine: 1634, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!635 = !DISubprogram(name: "_M_check_len", linkageName: "_ZNKSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE12_M_check_lenEmPKc", scope: !158, file: !159, line: 1640, type: !636, scopeLine: 1640, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!636 = !DISubroutineType(types: !637)
!637 = !{!638, !526, !363, !639}
!638 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", scope: !158, file: !159, line: 374, baseType: !224)
!639 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !640, size: 64)
!640 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !641)
!641 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
!642 = !DISubprogram(name: "_M_erase_at_end", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE15_M_erase_at_endEPS2_", scope: !158, file: !159, line: 1654, type: !643, scopeLine: 1654, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!643 = !DISubroutineType(types: !644)
!644 = !{null, !353, !645}
!645 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !158, file: !159, line: 365, baseType: !282)
!646 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE8_M_eraseEN9__gnu_cxx17__normal_iteratorIPS2_S4_EE", scope: !158, file: !159, line: 1666, type: !647, scopeLine: 1666, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!647 = !DISubroutineType(types: !648)
!648 = !{!410, !353, !410}
!649 = !DISubprogram(name: "_M_erase", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE8_M_eraseEN9__gnu_cxx17__normal_iteratorIPS2_S4_EES8_", scope: !158, file: !159, line: 1669, type: !650, scopeLine: 1669, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!650 = !DISubroutineType(types: !651)
!651 = !{!410, !353, !410, !410}
!652 = !DISubprogram(name: "_M_move_assign", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE14_M_move_assignEOS4_St17integral_constantIbLb1EE", scope: !158, file: !159, line: 1677, type: !653, scopeLine: 1677, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!653 = !DISubroutineType(types: !654)
!654 = !{null, !353, !378, !655}
!655 = !DIDerivedType(tag: DW_TAG_typedef, name: "true_type", scope: !91, file: !656, line: 75, baseType: !657)
!656 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/type_traits", directory: "")
!657 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "integral_constant<bool, true>", scope: !91, file: !656, line: 57, size: 8, flags: DIFlagTypePassByValue, elements: !658, templateParams: !668, identifier: "_ZTSSt17integral_constantIbLb1EE")
!658 = !{!659, !661, !667}
!659 = !DIDerivedType(tag: DW_TAG_member, name: "value", scope: !657, file: !656, line: 59, baseType: !660, flags: DIFlagStaticMember, extraData: i1 true)
!660 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !46)
!661 = !DISubprogram(name: "operator bool", linkageName: "_ZNKSt17integral_constantIbLb1EEcvbEv", scope: !657, file: !656, line: 62, type: !662, scopeLine: 62, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!662 = !DISubroutineType(types: !663)
!663 = !{!664, !665}
!664 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !657, file: !656, line: 60, baseType: !46)
!665 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !666, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!666 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !657)
!667 = !DISubprogram(name: "operator()", linkageName: "_ZNKSt17integral_constantIbLb1EEclEv", scope: !657, file: !656, line: 67, type: !662, scopeLine: 67, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!668 = !{!669, !670}
!669 = !DITemplateTypeParameter(name: "_Tp", type: !46)
!670 = !DITemplateValueParameter(name: "__v", type: !46, value: i8 1)
!671 = !DISubprogram(name: "_M_move_assign", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE14_M_move_assignEOS4_St17integral_constantIbLb0EE", scope: !158, file: !159, line: 1688, type: !672, scopeLine: 1688, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!672 = !DISubroutineType(types: !673)
!673 = !{null, !353, !378, !674}
!674 = !DIDerivedType(tag: DW_TAG_typedef, name: "false_type", scope: !91, file: !656, line: 78, baseType: !675)
!675 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "integral_constant<bool, false>", scope: !91, file: !656, line: 57, size: 8, flags: DIFlagTypePassByValue, elements: !676, templateParams: !685, identifier: "_ZTSSt17integral_constantIbLb0EE")
!676 = !{!677, !678, !684}
!677 = !DIDerivedType(tag: DW_TAG_member, name: "value", scope: !675, file: !656, line: 59, baseType: !660, flags: DIFlagStaticMember, extraData: i1 false)
!678 = !DISubprogram(name: "operator bool", linkageName: "_ZNKSt17integral_constantIbLb0EEcvbEv", scope: !675, file: !656, line: 62, type: !679, scopeLine: 62, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!679 = !DISubroutineType(types: !680)
!680 = !{!681, !682}
!681 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !675, file: !656, line: 60, baseType: !46)
!682 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !683, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!683 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !675)
!684 = !DISubprogram(name: "operator()", linkageName: "_ZNKSt17integral_constantIbLb0EEclEv", scope: !675, file: !656, line: 67, type: !679, scopeLine: 67, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!685 = !{!669, !686}
!686 = !DITemplateValueParameter(name: "__v", type: !46, value: i8 0)
!687 = !DIDerivedType(tag: DW_TAG_member, name: "LoadedPreprocessedEntities", scope: !147, file: !12, line: 305, baseType: !158, size: 192, offset: 896)
!688 = !DIDerivedType(tag: DW_TAG_member, name: "MacroDefinitions", scope: !147, file: !12, line: 329, baseType: !689, size: 192, offset: 1088)
!689 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMap<const clang::MacroInfo *, clang::MacroDefinition *, llvm::DenseMapInfo<const clang::MacroInfo *> >", scope: !80, file: !690, line: 534, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !691, templateParams: !1091, identifier: "_ZTSN4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEEE")
!690 = !DIFile(filename: "llvm34/include/llvm/ADT/DenseMap.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "e4a1c2d5b55fe605534e57bb36c4fe71")
!691 = !{!692, !1041, !1044, !1045, !1046, !1047, !1051, !1056, !1060, !1063, !1067, !1070, !1073, !1074, !1075, !1076, !1077, !1081, !1082, !1083, !1084, !1087, !1088}
!692 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !689, baseType: !693, flags: DIFlagPublic, extraData: i32 0)
!693 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapBase<llvm::DenseMap<const clang::MacroInfo *, clang::MacroDefinition *, llvm::DenseMapInfo<const clang::MacroInfo *> >, const clang::MacroInfo *, clang::MacroDefinition *, llvm::DenseMapInfo<const clang::MacroInfo *> >", scope: !80, file: !690, line: 41, size: 8, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !694, templateParams: !1039, identifier: "_ZTSN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_EE")
!694 = !{!695, !910, !911, !917, !918, !921, !924, !927, !930, !935, !938, !941, !944, !948, !951, !954, !957, !963, !967, !971, !974, !977, !980, !981, !982, !983, !987, !991, !994, !997, !998, !999, !1002, !1003, !1004, !1005, !1006, !1007, !1008, !1013, !1016, !1017, !1018, !1019, !1020, !1021, !1026, !1030, !1033, !1036}
!695 = !DISubprogram(name: "begin", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E5beginEv", scope: !693, file: !690, line: 53, type: !696, scopeLine: 53, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!696 = !DISubroutineType(types: !697)
!697 = !{!698, !909}
!698 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !693, file: !690, line: 50, baseType: !699)
!699 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapIterator<const clang::MacroInfo *, clang::MacroDefinition *, llvm::DenseMapInfo<const clang::MacroInfo *>, false>", scope: !80, file: !690, line: 987, size: 128, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !700, templateParams: !907, identifier: "_ZTSN4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb0EEE")
!700 = !{!701, !804, !805, !809, !812, !817, !823, !826, !898, !899, !903, !906}
!701 = !DIDerivedType(tag: DW_TAG_member, name: "Ptr", scope: !699, file: !690, line: 999, baseType: !702, size: 64)
!702 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !699, file: !690, line: 995, baseType: !703)
!703 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !704, size: 64)
!704 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !699, file: !690, line: 994, baseType: !705)
!705 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !707, file: !706, line: 236, baseType: !712)
!706 = !DIFile(filename: "llvm34/include/llvm/Support/type_traits.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "3b111e0adbb374a4c7fc591de906379a")
!707 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<false, const std::pair<const clang::MacroInfo *, clang::MacroDefinition *>, std::pair<const clang::MacroInfo *, clang::MacroDefinition *> >", scope: !80, file: !706, line: 236, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !708, identifier: "_ZTSN4llvm11conditionalILb0EKSt4pairIPKN5clang9MacroInfoEPNS2_15MacroDefinitionEES8_EE")
!708 = !{!709, !710, !803}
!709 = !DITemplateValueParameter(type: !46, value: i8 0)
!710 = !DITemplateTypeParameter(name: "T", type: !711)
!711 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !712)
!712 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<const clang::MacroInfo *, clang::MacroDefinition *>", scope: !91, file: !713, line: 208, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !714, templateParams: !800, identifier: "_ZTSSt4pairIPKN5clang9MacroInfoEPNS0_15MacroDefinitionEE")
!713 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_pair.h", directory: "", checksumkind: CSK_MD5, checksum: "9a7996187125e471e26ca57a6c9f4c5e")
!714 = !{!715, !764, !765, !766, !771, !775, !788, !797}
!715 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !712, baseType: !716, flags: DIFlagPrivate, extraData: i32 0)
!716 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<const clang::MacroInfo *, clang::MacroDefinition *>", scope: !91, file: !713, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !717, templateParams: !732, identifier: "_ZTSSt11__pair_baseIPKN5clang9MacroInfoEPNS0_15MacroDefinitionEE")
!717 = !{!718, !722, !723, !728}
!718 = !DISubprogram(name: "__pair_base", scope: !716, file: !713, line: 194, type: !719, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!719 = !DISubroutineType(types: !720)
!720 = !{null, !721}
!721 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !716, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!722 = !DISubprogram(name: "~__pair_base", scope: !716, file: !713, line: 195, type: !719, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!723 = !DISubprogram(name: "__pair_base", scope: !716, file: !713, line: 196, type: !724, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!724 = !DISubroutineType(types: !725)
!725 = !{null, !721, !726}
!726 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !727, size: 64)
!727 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !716)
!728 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIPKN5clang9MacroInfoEPNS0_15MacroDefinitionEEaSERKS6_", scope: !716, file: !713, line: 197, type: !729, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!729 = !DISubroutineType(types: !730)
!730 = !{!731, !721, !726}
!731 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !716, size: 64)
!732 = !{!733, !738}
!733 = !DITemplateTypeParameter(name: "_U1", type: !734)
!734 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !735, size: 64)
!735 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !736)
!736 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MacroInfo", scope: !14, file: !737, line: 29, size: 1984, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang9MacroInfoE")
!737 = !DIFile(filename: "llvm34/projects/clang/include/clang/Lex/MacroInfo.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "8e70dc8f9390b02811179410a0c5da5c")
!738 = !DITemplateTypeParameter(name: "_U2", type: !739)
!739 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !740, size: 64)
!740 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MacroDefinition", scope: !14, file: !12, line: 137, size: 192, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !741, identifier: "_ZTSN5clang15MacroDefinitionE")
!741 = !{!742, !743, !748, !752, !757, !760}
!742 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !740, baseType: !17, flags: DIFlagPublic, extraData: i32 0)
!743 = !DIDerivedType(tag: DW_TAG_member, name: "Name", scope: !740, file: !12, line: 139, baseType: !744, size: 64, offset: 128)
!744 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !745, size: 64)
!745 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !746)
!746 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "IdentifierInfo", scope: !14, file: !747, line: 50, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang14IdentifierInfoE")
!747 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/IdentifierTable.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "4680d46f8abc74960d0f86dc6eb6b801")
!748 = !DISubprogram(name: "MacroDefinition", scope: !740, file: !12, line: 142, type: !749, scopeLine: 142, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!749 = !DISubroutineType(types: !750)
!750 = !{null, !751, !744, !32}
!751 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !740, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!752 = !DISubprogram(name: "getName", linkageName: "_ZNK5clang15MacroDefinition7getNameEv", scope: !740, file: !12, line: 146, type: !753, scopeLine: 146, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!753 = !DISubroutineType(types: !754)
!754 = !{!744, !755}
!755 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !756, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!756 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !740)
!757 = !DISubprogram(name: "getLocation", linkageName: "_ZNK5clang15MacroDefinition11getLocationEv", scope: !740, file: !12, line: 149, type: !758, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!758 = !DISubroutineType(types: !759)
!759 = !{!36, !755}
!760 = !DISubprogram(name: "classof", linkageName: "_ZN5clang15MacroDefinition7classofEPKNS_18PreprocessedEntityE", scope: !740, file: !12, line: 152, type: !761, scopeLine: 152, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!761 = !DISubroutineType(types: !762)
!762 = !{!46, !763}
!763 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !133, size: 64)
!764 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !712, file: !713, line: 214, baseType: !734, size: 64)
!765 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !712, file: !713, line: 215, baseType: !739, size: 64, offset: 64)
!766 = !DISubprogram(name: "pair", scope: !712, file: !713, line: 303, type: !767, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!767 = !DISubroutineType(types: !768)
!768 = !{null, !769, !770}
!769 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !712, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!770 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !711, size: 64)
!771 = !DISubprogram(name: "pair", scope: !712, file: !713, line: 304, type: !772, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!772 = !DISubroutineType(types: !773)
!773 = !{null, !769, !774}
!774 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !712, size: 64)
!775 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPKN5clang9MacroInfoEPNS0_15MacroDefinitionEEaSERKS6_", scope: !712, file: !713, line: 378, type: !776, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!776 = !DISubroutineType(types: !777)
!777 = !{!778, !769, !779}
!778 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !712, size: 64)
!779 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !780, file: !656, line: 1928, baseType: !770)
!780 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<const clang::MacroInfo *, clang::MacroDefinition *> &, const std::__nonesuch_no_braces &>", scope: !91, file: !656, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !781, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIPKN5clang9MacroInfoEPNS1_15MacroDefinitionEERKSt20__nonesuch_no_bracesE")
!781 = !{!782, !783, !784}
!782 = !DITemplateValueParameter(name: "_Cond", type: !46, value: i8 1)
!783 = !DITemplateTypeParameter(name: "_Iftrue", type: !770)
!784 = !DITemplateTypeParameter(name: "_Iffalse", type: !785)
!785 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !786, size: 64)
!786 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !787)
!787 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__nonesuch_no_braces", scope: !91, file: !713, line: 185, size: 8, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt20__nonesuch_no_braces")
!788 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIPKN5clang9MacroInfoEPNS0_15MacroDefinitionEEaSEOS6_", scope: !712, file: !713, line: 389, type: !789, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!789 = !DISubroutineType(types: !790)
!790 = !{!778, !769, !791}
!791 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !792, file: !656, line: 1928, baseType: !774)
!792 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<const clang::MacroInfo *, clang::MacroDefinition *> &&, std::__nonesuch_no_braces &&>", scope: !91, file: !656, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !793, identifier: "_ZTSSt11conditionalILb1EOSt4pairIPKN5clang9MacroInfoEPNS1_15MacroDefinitionEEOSt20__nonesuch_no_bracesE")
!793 = !{!782, !794, !795}
!794 = !DITemplateTypeParameter(name: "_Iftrue", type: !774)
!795 = !DITemplateTypeParameter(name: "_Iffalse", type: !796)
!796 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !787, size: 64)
!797 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIPKN5clang9MacroInfoEPNS0_15MacroDefinitionEE4swapERS6_", scope: !712, file: !713, line: 424, type: !798, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!798 = !DISubroutineType(types: !799)
!799 = !{null, !769, !778}
!800 = !{!801, !802}
!801 = !DITemplateTypeParameter(name: "_T1", type: !734)
!802 = !DITemplateTypeParameter(name: "_T2", type: !739)
!803 = !DITemplateTypeParameter(name: "F", type: !712)
!804 = !DIDerivedType(tag: DW_TAG_member, name: "End", scope: !699, file: !690, line: 999, baseType: !702, size: 64, offset: 64)
!805 = !DISubprogram(name: "DenseMapIterator", scope: !699, file: !690, line: 1001, type: !806, scopeLine: 1001, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!806 = !DISubroutineType(types: !807)
!807 = !{null, !808}
!808 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !699, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!809 = !DISubprogram(name: "DenseMapIterator", scope: !699, file: !690, line: 1003, type: !810, scopeLine: 1003, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!810 = !DISubroutineType(types: !811)
!811 = !{null, !808, !702, !702, !46}
!812 = !DISubprogram(name: "DenseMapIterator", scope: !699, file: !690, line: 1011, type: !813, scopeLine: 1011, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!813 = !DISubroutineType(types: !814)
!814 = !{null, !808, !815}
!815 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !816, size: 64)
!816 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !699)
!817 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb0EEdeEv", scope: !699, file: !690, line: 1015, type: !818, scopeLine: 1015, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!818 = !DISubroutineType(types: !819)
!819 = !{!820, !822}
!820 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !699, file: !690, line: 996, baseType: !821)
!821 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !704, size: 64)
!822 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !816, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!823 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb0EEptEv", scope: !699, file: !690, line: 1018, type: !824, scopeLine: 1018, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!824 = !DISubroutineType(types: !825)
!825 = !{!702, !822}
!826 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb0EEeqERKNS0_IS4_S6_S8_Lb1EEE", scope: !699, file: !690, line: 1022, type: !827, scopeLine: 1022, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!827 = !DISubroutineType(types: !828)
!828 = !{!46, !822, !829}
!829 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !830, size: 64)
!830 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !831)
!831 = !DIDerivedType(tag: DW_TAG_typedef, name: "ConstIterator", scope: !699, file: !690, line: 990, baseType: !832)
!832 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DenseMapIterator<const clang::MacroInfo *, clang::MacroDefinition *, llvm::DenseMapInfo<const clang::MacroInfo *>, true>", scope: !80, file: !690, line: 987, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !833, templateParams: !878, identifier: "_ZTSN4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb1EEE")
!833 = !{!834, !842, !843, !847, !850, !853, !860, !863, !869, !870, !874, !877}
!834 = !DIDerivedType(tag: DW_TAG_member, name: "Ptr", scope: !832, file: !690, line: 999, baseType: !835, size: 64)
!835 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !832, file: !690, line: 995, baseType: !836)
!836 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !837, size: 64)
!837 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !832, file: !690, line: 994, baseType: !838)
!838 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !839, file: !706, line: 233, baseType: !711)
!839 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<const clang::MacroInfo *, clang::MacroDefinition *>, std::pair<const clang::MacroInfo *, clang::MacroDefinition *> >", scope: !80, file: !706, line: 233, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !840, identifier: "_ZTSN4llvm11conditionalILb1EKSt4pairIPKN5clang9MacroInfoEPNS2_15MacroDefinitionEES8_EE")
!840 = !{!841, !710, !803}
!841 = !DITemplateValueParameter(type: !46, value: i8 1)
!842 = !DIDerivedType(tag: DW_TAG_member, name: "End", scope: !832, file: !690, line: 999, baseType: !835, size: 64, offset: 64)
!843 = !DISubprogram(name: "DenseMapIterator", scope: !832, file: !690, line: 1001, type: !844, scopeLine: 1001, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!844 = !DISubroutineType(types: !845)
!845 = !{null, !846}
!846 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !832, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!847 = !DISubprogram(name: "DenseMapIterator", scope: !832, file: !690, line: 1003, type: !848, scopeLine: 1003, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!848 = !DISubroutineType(types: !849)
!849 = !{null, !846, !835, !835, !46}
!850 = !DISubprogram(name: "DenseMapIterator", scope: !832, file: !690, line: 1011, type: !851, scopeLine: 1011, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!851 = !DISubroutineType(types: !852)
!852 = !{null, !846, !815}
!853 = !DISubprogram(name: "operator*", linkageName: "_ZNK4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb1EEdeEv", scope: !832, file: !690, line: 1015, type: !854, scopeLine: 1015, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!854 = !DISubroutineType(types: !855)
!855 = !{!856, !858}
!856 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !832, file: !690, line: 996, baseType: !857)
!857 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !837, size: 64)
!858 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !859, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!859 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !832)
!860 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb1EEptEv", scope: !832, file: !690, line: 1018, type: !861, scopeLine: 1018, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!861 = !DISubroutineType(types: !862)
!862 = !{!835, !858}
!863 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb1EEeqERKS9_", scope: !832, file: !690, line: 1022, type: !864, scopeLine: 1022, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!864 = !DISubroutineType(types: !865)
!865 = !{!46, !858, !866}
!866 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !867, size: 64)
!867 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !868)
!868 = !DIDerivedType(tag: DW_TAG_typedef, name: "ConstIterator", scope: !832, file: !690, line: 990, baseType: !832)
!869 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb1EEneERKS9_", scope: !832, file: !690, line: 1025, type: !864, scopeLine: 1025, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!870 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb1EEppEv", scope: !832, file: !690, line: 1029, type: !871, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!871 = !DISubroutineType(types: !872)
!872 = !{!873, !846}
!873 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !832, size: 64)
!874 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb1EEppEi", scope: !832, file: !690, line: 1034, type: !875, scopeLine: 1034, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!875 = !DISubroutineType(types: !876)
!876 = !{!832, !846, !62}
!877 = !DISubprogram(name: "AdvancePastEmptyBuckets", linkageName: "_ZN4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb1EE23AdvancePastEmptyBucketsEv", scope: !832, file: !690, line: 1039, type: !844, scopeLine: 1039, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!878 = !{!879, !880, !881, !897}
!879 = !DITemplateTypeParameter(name: "KeyT", type: !734)
!880 = !DITemplateTypeParameter(name: "ValueT", type: !739)
!881 = !DITemplateTypeParameter(name: "KeyInfoT", type: !882)
!882 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "DenseMapInfo<const clang::MacroInfo *>", scope: !80, file: !883, line: 32, size: 8, flags: DIFlagTypePassByValue, elements: !884, templateParams: !895, identifier: "_ZTSN4llvm12DenseMapInfoIPKN5clang9MacroInfoEEE")
!883 = !DIFile(filename: "llvm34/include/llvm/ADT/DenseMapInfo.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "1e7505cc8cacf4830514e4c206b176d8")
!884 = !{!885, !888, !889, !892}
!885 = !DISubprogram(name: "getEmptyKey", linkageName: "_ZN4llvm12DenseMapInfoIPKN5clang9MacroInfoEE11getEmptyKeyEv", scope: !882, file: !883, line: 33, type: !886, scopeLine: 33, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!886 = !DISubroutineType(types: !887)
!887 = !{!734}
!888 = !DISubprogram(name: "getTombstoneKey", linkageName: "_ZN4llvm12DenseMapInfoIPKN5clang9MacroInfoEE15getTombstoneKeyEv", scope: !882, file: !883, line: 38, type: !886, scopeLine: 38, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!889 = !DISubprogram(name: "getHashValue", linkageName: "_ZN4llvm12DenseMapInfoIPKN5clang9MacroInfoEE12getHashValueES4_", scope: !882, file: !883, line: 43, type: !890, scopeLine: 43, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!890 = !DISubroutineType(types: !891)
!891 = !{!6, !734}
!892 = !DISubprogram(name: "isEqual", linkageName: "_ZN4llvm12DenseMapInfoIPKN5clang9MacroInfoEE7isEqualES4_S4_", scope: !882, file: !883, line: 47, type: !893, scopeLine: 47, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!893 = !DISubroutineType(types: !894)
!894 = !{!46, !734, !734}
!895 = !{!896}
!896 = !DITemplateTypeParameter(name: "T", type: !734)
!897 = !DITemplateValueParameter(name: "IsConst", type: !46, value: i8 1)
!898 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb0EEneERKNS0_IS4_S6_S8_Lb1EEE", scope: !699, file: !690, line: 1025, type: !827, scopeLine: 1025, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!899 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb0EEppEv", scope: !699, file: !690, line: 1029, type: !900, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!900 = !DISubroutineType(types: !901)
!901 = !{!902, !808}
!902 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !699, size: 64)
!903 = !DISubprogram(name: "operator++", linkageName: "_ZN4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb0EEppEi", scope: !699, file: !690, line: 1034, type: !904, scopeLine: 1034, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!904 = !DISubroutineType(types: !905)
!905 = !{!699, !808, !62}
!906 = !DISubprogram(name: "AdvancePastEmptyBuckets", linkageName: "_ZN4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EELb0EE23AdvancePastEmptyBucketsEv", scope: !699, file: !690, line: 1039, type: !806, scopeLine: 1039, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!907 = !{!879, !880, !881, !908}
!908 = !DITemplateValueParameter(name: "IsConst", type: !46, defaulted: true, value: i8 0)
!909 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !693, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!910 = !DISubprogram(name: "end", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E3endEv", scope: !693, file: !690, line: 57, type: !696, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!911 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E5beginEv", scope: !693, file: !690, line: 60, type: !912, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!912 = !DISubroutineType(types: !913)
!913 = !{!914, !915}
!914 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !693, file: !690, line: 52, baseType: !832)
!915 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !916, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!916 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !693)
!917 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E3endEv", scope: !693, file: !690, line: 63, type: !912, scopeLine: 63, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!918 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E5emptyEv", scope: !693, file: !690, line: 67, type: !919, scopeLine: 67, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!919 = !DISubroutineType(types: !920)
!920 = !{!46, !915}
!921 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E4sizeEv", scope: !693, file: !690, line: 70, type: !922, scopeLine: 70, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!922 = !DISubroutineType(types: !923)
!923 = !{!6, !915}
!924 = !DISubprogram(name: "resize", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E6resizeEm", scope: !693, file: !690, line: 73, type: !925, scopeLine: 73, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!925 = !DISubroutineType(types: !926)
!926 = !{null, !909, !143}
!927 = !DISubprogram(name: "clear", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E5clearEv", scope: !693, file: !690, line: 78, type: !928, scopeLine: 78, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!928 = !DISubroutineType(types: !929)
!929 = !{null, !909}
!930 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E5countERKS5_", scope: !693, file: !690, line: 103, type: !931, scopeLine: 103, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!931 = !DISubroutineType(types: !932)
!932 = !{!46, !915, !933}
!933 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !934, size: 64)
!934 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !734)
!935 = !DISubprogram(name: "find", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E4findERKS5_", scope: !693, file: !690, line: 108, type: !936, scopeLine: 108, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!936 = !DISubroutineType(types: !937)
!937 = !{!698, !909, !933}
!938 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E4findERKS5_", scope: !693, file: !690, line: 114, type: !939, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!939 = !DISubroutineType(types: !940)
!940 = !{!914, !915, !933}
!941 = !DISubprogram(name: "lookup", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E6lookupERKS5_", scope: !693, file: !690, line: 143, type: !942, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!942 = !DISubroutineType(types: !943)
!943 = !{!739, !915, !933}
!944 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E6insertERKSt4pairIS5_S7_E", scope: !693, file: !690, line: 153, type: !945, scopeLine: 153, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!945 = !DISubroutineType(types: !946)
!946 = !{!947, !909, !770}
!947 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::DenseMapIterator<const clang::MacroInfo *, clang::MacroDefinition *, llvm::DenseMapInfo<const clang::MacroInfo *>, false>, bool>", scope: !91, file: !713, line: 208, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt4pairIN4llvm16DenseMapIteratorIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS0_12DenseMapInfoIS5_EELb0EEEbE")
!948 = !DISubprogram(name: "insert", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E6insertEOSt4pairIS5_S7_E", scope: !693, file: !690, line: 168, type: !949, scopeLine: 168, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!949 = !DISubroutineType(types: !950)
!950 = !{!947, !909, !774}
!951 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E5eraseERKS5_", scope: !693, file: !690, line: 190, type: !952, scopeLine: 190, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!952 = !DISubroutineType(types: !953)
!953 = !{!46, !909, !933}
!954 = !DISubprogram(name: "erase", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E5eraseENS_16DenseMapIteratorIS5_S7_S9_Lb0EEE", scope: !693, file: !690, line: 201, type: !955, scopeLine: 201, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!955 = !DISubroutineType(types: !956)
!956 = !{null, !909, !698}
!957 = !DISubprogram(name: "FindAndConstruct", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E16FindAndConstructERKS5_", scope: !693, file: !690, line: 209, type: !958, scopeLine: 209, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!958 = !DISubroutineType(types: !959)
!959 = !{!960, !909, !933}
!960 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !961, size: 64)
!961 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !693, file: !690, line: 48, baseType: !962)
!962 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !693, file: !690, line: 43, baseType: !712)
!963 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_EixERKS5_", scope: !693, file: !690, line: 217, type: !964, scopeLine: 217, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!964 = !DISubroutineType(types: !965)
!965 = !{!966, !909, !933}
!966 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !739, size: 64)
!967 = !DISubprogram(name: "FindAndConstruct", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E16FindAndConstructEOS5_", scope: !693, file: !690, line: 222, type: !968, scopeLine: 222, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!968 = !DISubroutineType(types: !969)
!969 = !{!960, !909, !970}
!970 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !734, size: 64)
!971 = !DISubprogram(name: "operator[]", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_EixEOS5_", scope: !693, file: !690, line: 230, type: !972, scopeLine: 230, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!972 = !DISubroutineType(types: !973)
!973 = !{!966, !909, !970}
!974 = !DISubprogram(name: "isPointerIntoBucketsArray", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E25isPointerIntoBucketsArrayEPKv", scope: !693, file: !690, line: 238, type: !975, scopeLine: 238, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!975 = !DISubroutineType(types: !976)
!976 = !{!46, !915, !72}
!977 = !DISubprogram(name: "getPointerIntoBucketsArray", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E26getPointerIntoBucketsArrayEv", scope: !693, file: !690, line: 245, type: !978, scopeLine: 245, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!978 = !DISubroutineType(types: !979)
!979 = !{!72, !915}
!980 = !DISubprogram(name: "DenseMapBase", scope: !693, file: !690, line: 248, type: !928, scopeLine: 248, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!981 = !DISubprogram(name: "destroyAll", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E10destroyAllEv", scope: !693, file: !690, line: 250, type: !928, scopeLine: 250, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!982 = !DISubprogram(name: "initEmpty", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E9initEmptyEv", scope: !693, file: !690, line: 267, type: !928, scopeLine: 267, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!983 = !DISubprogram(name: "moveFromOldBuckets", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E18moveFromOldBucketsEPSt4pairIS5_S7_ESE_", scope: !693, file: !690, line: 278, type: !984, scopeLine: 278, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!984 = !DISubroutineType(types: !985)
!985 = !{null, !909, !986, !986}
!986 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !962, size: 64)
!987 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E4swapERSB_", scope: !693, file: !690, line: 328, type: !988, scopeLine: 328, flags: DIFlagProtected | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!988 = !DISubroutineType(types: !989)
!989 = !{null, !909, !990}
!990 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !693, size: 64)
!991 = !DISubprogram(name: "getHashValue", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E12getHashValueERKS5_", scope: !693, file: !690, line: 333, type: !992, scopeLine: 333, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!992 = !DISubroutineType(types: !993)
!993 = !{!6, !933}
!994 = !DISubprogram(name: "getEmptyKey", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E11getEmptyKeyEv", scope: !693, file: !690, line: 340, type: !995, scopeLine: 340, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!995 = !DISubroutineType(types: !996)
!996 = !{!934}
!997 = !DISubprogram(name: "getTombstoneKey", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E15getTombstoneKeyEv", scope: !693, file: !690, line: 343, type: !995, scopeLine: 343, flags: DIFlagProtected | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!998 = !DISubprogram(name: "getNumEntries", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E13getNumEntriesEv", scope: !693, file: !690, line: 348, type: !922, scopeLine: 348, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!999 = !DISubprogram(name: "setNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E13setNumEntriesEj", scope: !693, file: !690, line: 351, type: !1000, scopeLine: 351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1000 = !DISubroutineType(types: !1001)
!1001 = !{null, !909, !6}
!1002 = !DISubprogram(name: "incrementNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E19incrementNumEntriesEv", scope: !693, file: !690, line: 354, type: !928, scopeLine: 354, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1003 = !DISubprogram(name: "decrementNumEntries", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E19decrementNumEntriesEv", scope: !693, file: !690, line: 357, type: !928, scopeLine: 357, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1004 = !DISubprogram(name: "getNumTombstones", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E16getNumTombstonesEv", scope: !693, file: !690, line: 360, type: !922, scopeLine: 360, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1005 = !DISubprogram(name: "setNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E16setNumTombstonesEj", scope: !693, file: !690, line: 363, type: !1000, scopeLine: 363, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1006 = !DISubprogram(name: "incrementNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E22incrementNumTombstonesEv", scope: !693, file: !690, line: 366, type: !928, scopeLine: 366, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1007 = !DISubprogram(name: "decrementNumTombstones", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E22decrementNumTombstonesEv", scope: !693, file: !690, line: 369, type: !928, scopeLine: 369, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1008 = !DISubprogram(name: "getBuckets", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E10getBucketsEv", scope: !693, file: !690, line: 372, type: !1009, scopeLine: 372, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1009 = !DISubroutineType(types: !1010)
!1010 = !{!1011, !915}
!1011 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1012, size: 64)
!1012 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !962)
!1013 = !DISubprogram(name: "getBuckets", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E10getBucketsEv", scope: !693, file: !690, line: 375, type: !1014, scopeLine: 375, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1014 = !DISubroutineType(types: !1015)
!1015 = !{!986, !909}
!1016 = !DISubprogram(name: "getNumBuckets", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E13getNumBucketsEv", scope: !693, file: !690, line: 378, type: !922, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1017 = !DISubprogram(name: "getBucketsEnd", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E13getBucketsEndEv", scope: !693, file: !690, line: 381, type: !1014, scopeLine: 381, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1018 = !DISubprogram(name: "getBucketsEnd", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E13getBucketsEndEv", scope: !693, file: !690, line: 384, type: !1009, scopeLine: 384, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1019 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E4growEj", scope: !693, file: !690, line: 388, type: !1000, scopeLine: 388, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1020 = !DISubprogram(name: "shrink_and_clear", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E16shrink_and_clearEv", scope: !693, file: !690, line: 392, type: !928, scopeLine: 392, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1021 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E16InsertIntoBucketERKS5_RKS7_PSt4pairIS5_S7_E", scope: !693, file: !690, line: 397, type: !1022, scopeLine: 397, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1022 = !DISubroutineType(types: !1023)
!1023 = !{!986, !909, !933, !1024, !986}
!1024 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1025, size: 64)
!1025 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !739)
!1026 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E16InsertIntoBucketERKS5_OS7_PSt4pairIS5_S7_E", scope: !693, file: !690, line: 407, type: !1027, scopeLine: 407, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1027 = !DISubroutineType(types: !1028)
!1028 = !{!986, !909, !933, !1029, !986}
!1029 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !739, size: 64)
!1030 = !DISubprogram(name: "InsertIntoBucket", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E16InsertIntoBucketEOS5_OS7_PSt4pairIS5_S7_E", scope: !693, file: !690, line: 416, type: !1031, scopeLine: 416, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1031 = !DISubroutineType(types: !1032)
!1032 = !{!986, !909, !970, !1029, !986}
!1033 = !DISubprogram(name: "InsertIntoBucketImpl", linkageName: "_ZN4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E20InsertIntoBucketImplERKS5_PSt4pairIS5_S7_E", scope: !693, file: !690, line: 425, type: !1034, scopeLine: 425, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1034 = !DISubroutineType(types: !1035)
!1035 = !{!986, !909, !933, !986}
!1036 = !DISubprogram(name: "getMemorySize", linkageName: "_ZNK4llvm12DenseMapBaseINS_8DenseMapIPKN5clang9MacroInfoEPNS2_15MacroDefinitionENS_12DenseMapInfoIS5_EEEES5_S7_S9_E13getMemorySizeEv", scope: !693, file: !690, line: 527, type: !1037, scopeLine: 527, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1037 = !DISubroutineType(types: !1038)
!1038 = !{!143, !915}
!1039 = !{!1040, !879, !880, !881}
!1040 = !DITemplateTypeParameter(name: "DerivedT", type: !689)
!1041 = !DIDerivedType(tag: DW_TAG_member, name: "Buckets", scope: !689, file: !690, line: 543, baseType: !1042, size: 64)
!1042 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1043, size: 64)
!1043 = !DIDerivedType(tag: DW_TAG_typedef, name: "BucketT", scope: !689, file: !690, line: 540, baseType: !962)
!1044 = !DIDerivedType(tag: DW_TAG_member, name: "NumEntries", scope: !689, file: !690, line: 544, baseType: !6, size: 32, offset: 64)
!1045 = !DIDerivedType(tag: DW_TAG_member, name: "NumTombstones", scope: !689, file: !690, line: 545, baseType: !6, size: 32, offset: 96)
!1046 = !DIDerivedType(tag: DW_TAG_member, name: "NumBuckets", scope: !689, file: !690, line: 546, baseType: !6, size: 32, offset: 128)
!1047 = !DISubprogram(name: "DenseMap", scope: !689, file: !690, line: 549, type: !1048, scopeLine: 549, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1048 = !DISubroutineType(types: !1049)
!1049 = !{null, !1050, !6}
!1050 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !689, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1051 = !DISubprogram(name: "DenseMap", scope: !689, file: !690, line: 553, type: !1052, scopeLine: 553, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1052 = !DISubroutineType(types: !1053)
!1053 = !{null, !1050, !1054}
!1054 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1055, size: 64)
!1055 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !689)
!1056 = !DISubprogram(name: "DenseMap", scope: !689, file: !690, line: 559, type: !1057, scopeLine: 559, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1057 = !DISubroutineType(types: !1058)
!1058 = !{null, !1050, !1059}
!1059 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !689, size: 64)
!1060 = !DISubprogram(name: "~DenseMap", scope: !689, file: !690, line: 571, type: !1061, scopeLine: 571, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1061 = !DISubroutineType(types: !1062)
!1062 = !{null, !1050}
!1063 = !DISubprogram(name: "swap", linkageName: "_ZN4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEE4swapERS9_", scope: !689, file: !690, line: 576, type: !1064, scopeLine: 576, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1064 = !DISubroutineType(types: !1065)
!1065 = !{null, !1050, !1066}
!1066 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !689, size: 64)
!1067 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEEaSERKS9_", scope: !689, file: !690, line: 583, type: !1068, scopeLine: 583, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1068 = !DISubroutineType(types: !1069)
!1069 = !{!1066, !1050, !1054}
!1070 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEEaSEOS9_", scope: !689, file: !690, line: 589, type: !1071, scopeLine: 589, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1071 = !DISubroutineType(types: !1072)
!1072 = !{!1066, !1050, !1059}
!1073 = !DISubprogram(name: "copyFrom", linkageName: "_ZN4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEE8copyFromERKS9_", scope: !689, file: !690, line: 598, type: !1052, scopeLine: 598, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1074 = !DISubprogram(name: "init", linkageName: "_ZN4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEE4initEj", scope: !689, file: !690, line: 609, type: !1048, scopeLine: 609, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1075 = !DISubprogram(name: "grow", linkageName: "_ZN4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEE4growEj", scope: !689, file: !690, line: 618, type: !1048, scopeLine: 618, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1076 = !DISubprogram(name: "shrink_and_clear", linkageName: "_ZN4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEE16shrink_and_clearEv", scope: !689, file: !690, line: 635, type: !1061, scopeLine: 635, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1077 = !DISubprogram(name: "getNumEntries", linkageName: "_ZNK4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEE13getNumEntriesEv", scope: !689, file: !690, line: 653, type: !1078, scopeLine: 653, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1078 = !DISubroutineType(types: !1079)
!1079 = !{!6, !1080}
!1080 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1055, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1081 = !DISubprogram(name: "setNumEntries", linkageName: "_ZN4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEE13setNumEntriesEj", scope: !689, file: !690, line: 656, type: !1048, scopeLine: 656, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1082 = !DISubprogram(name: "getNumTombstones", linkageName: "_ZNK4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEE16getNumTombstonesEv", scope: !689, file: !690, line: 660, type: !1078, scopeLine: 660, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1083 = !DISubprogram(name: "setNumTombstones", linkageName: "_ZN4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEE16setNumTombstonesEj", scope: !689, file: !690, line: 663, type: !1048, scopeLine: 663, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1084 = !DISubprogram(name: "getBuckets", linkageName: "_ZNK4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEE10getBucketsEv", scope: !689, file: !690, line: 667, type: !1085, scopeLine: 667, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1085 = !DISubroutineType(types: !1086)
!1086 = !{!1042, !1080}
!1087 = !DISubprogram(name: "getNumBuckets", linkageName: "_ZNK4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEE13getNumBucketsEv", scope: !689, file: !690, line: 671, type: !1078, scopeLine: 671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1088 = !DISubprogram(name: "allocateBuckets", linkageName: "_ZN4llvm8DenseMapIPKN5clang9MacroInfoEPNS1_15MacroDefinitionENS_12DenseMapInfoIS4_EEE15allocateBucketsEj", scope: !689, file: !690, line: 675, type: !1089, scopeLine: 675, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1089 = !DISubroutineType(types: !1090)
!1090 = !{!46, !1050, !6}
!1091 = !{!879, !880, !881}
!1092 = !DIDerivedType(tag: DW_TAG_member, name: "ExternalSource", scope: !147, file: !12, line: 332, baseType: !1093, size: 64, offset: 1280)
!1093 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1094, size: 64)
!1094 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ExternalPreprocessingRecordSource", scope: !14, file: !12, line: 264, size: 64, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1095, vtableHolder: !1094)
!1095 = !{!1096, !1101, !1105, !1108, !1166}
!1096 = !DIDerivedType(tag: DW_TAG_member, name: "_vptr$ExternalPreprocessingRecordSource", scope: !12, file: !12, baseType: !1097, size: 64, flags: DIFlagArtificial)
!1097 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1098, size: 64)
!1098 = !DIDerivedType(tag: DW_TAG_pointer_type, name: "__vtbl_ptr_type", baseType: !1099, size: 64)
!1099 = !DISubroutineType(types: !1100)
!1100 = !{!62}
!1101 = !DISubprogram(name: "~ExternalPreprocessingRecordSource", scope: !1094, file: !12, line: 266, type: !1102, scopeLine: 266, containingType: !1094, virtualIndex: 0, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1102 = !DISubroutineType(types: !1103)
!1103 = !{null, !1104}
!1104 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1094, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1105 = !DISubprogram(name: "ReadPreprocessedEntity", linkageName: "_ZN5clang33ExternalPreprocessingRecordSource22ReadPreprocessedEntityEj", scope: !1094, file: !12, line: 272, type: !1106, scopeLine: 272, containingType: !1094, virtualIndex: 2, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!1106 = !DISubroutineType(types: !1107)
!1107 = !{!183, !1104, !6}
!1108 = !DISubprogram(name: "findPreprocessedEntitiesInRange", linkageName: "_ZN5clang33ExternalPreprocessingRecordSource31findPreprocessedEntitiesInRangeENS_11SourceRangeE", scope: !1094, file: !12, line: 277, type: !1109, scopeLine: 277, containingType: !1094, virtualIndex: 3, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagPureVirtual | DISPFlagOptimized)
!1109 = !DISubroutineType(types: !1110)
!1110 = !{!1111, !1104, !32}
!1111 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<unsigned int, unsigned int>", scope: !91, file: !713, line: 208, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1112, templateParams: !1163, identifier: "_ZTSSt4pairIjjE")
!1112 = !{!1113, !1133, !1134, !1135, !1141, !1145, !1153, !1160}
!1113 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1111, baseType: !1114, flags: DIFlagPrivate, extraData: i32 0)
!1114 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<unsigned int, unsigned int>", scope: !91, file: !713, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !1115, templateParams: !1130, identifier: "_ZTSSt11__pair_baseIjjE")
!1115 = !{!1116, !1120, !1121, !1126}
!1116 = !DISubprogram(name: "__pair_base", scope: !1114, file: !713, line: 194, type: !1117, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1117 = !DISubroutineType(types: !1118)
!1118 = !{null, !1119}
!1119 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1114, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1120 = !DISubprogram(name: "~__pair_base", scope: !1114, file: !713, line: 195, type: !1117, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1121 = !DISubprogram(name: "__pair_base", scope: !1114, file: !713, line: 196, type: !1122, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1122 = !DISubroutineType(types: !1123)
!1123 = !{null, !1119, !1124}
!1124 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1125, size: 64)
!1125 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1114)
!1126 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIjjEaSERKS0_", scope: !1114, file: !713, line: 197, type: !1127, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1127 = !DISubroutineType(types: !1128)
!1128 = !{!1129, !1119, !1124}
!1129 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1114, size: 64)
!1130 = !{!1131, !1132}
!1131 = !DITemplateTypeParameter(name: "_U1", type: !6)
!1132 = !DITemplateTypeParameter(name: "_U2", type: !6)
!1133 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !1111, file: !713, line: 214, baseType: !6, size: 32)
!1134 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !1111, file: !713, line: 215, baseType: !6, size: 32, offset: 32)
!1135 = !DISubprogram(name: "pair", scope: !1111, file: !713, line: 303, type: !1136, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1136 = !DISubroutineType(types: !1137)
!1137 = !{null, !1138, !1139}
!1138 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1111, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1139 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1140, size: 64)
!1140 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1111)
!1141 = !DISubprogram(name: "pair", scope: !1111, file: !713, line: 304, type: !1142, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1142 = !DISubroutineType(types: !1143)
!1143 = !{null, !1138, !1144}
!1144 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1111, size: 64)
!1145 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIjjEaSERKS0_", scope: !1111, file: !713, line: 378, type: !1146, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1146 = !DISubroutineType(types: !1147)
!1147 = !{!1148, !1138, !1149}
!1148 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1111, size: 64)
!1149 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1150, file: !656, line: 1928, baseType: !1139)
!1150 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<unsigned int, unsigned int> &, const std::__nonesuch_no_braces &>", scope: !91, file: !656, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !1151, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIjjERKSt20__nonesuch_no_bracesE")
!1151 = !{!782, !1152, !784}
!1152 = !DITemplateTypeParameter(name: "_Iftrue", type: !1139)
!1153 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIjjEaSEOS0_", scope: !1111, file: !713, line: 389, type: !1154, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1154 = !DISubroutineType(types: !1155)
!1155 = !{!1148, !1138, !1156}
!1156 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1157, file: !656, line: 1928, baseType: !1144)
!1157 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<unsigned int, unsigned int> &&, std::__nonesuch_no_braces &&>", scope: !91, file: !656, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !1158, identifier: "_ZTSSt11conditionalILb1EOSt4pairIjjEOSt20__nonesuch_no_bracesE")
!1158 = !{!782, !1159, !795}
!1159 = !DITemplateTypeParameter(name: "_Iftrue", type: !1144)
!1160 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIjjE4swapERS0_", scope: !1111, file: !713, line: 424, type: !1161, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1161 = !DISubroutineType(types: !1162)
!1162 = !{null, !1138, !1148}
!1163 = !{!1164, !1165}
!1164 = !DITemplateTypeParameter(name: "_T1", type: !6)
!1165 = !DITemplateTypeParameter(name: "_T2", type: !6)
!1166 = !DISubprogram(name: "isPreprocessedEntityInFileID", linkageName: "_ZN5clang33ExternalPreprocessingRecordSource28isPreprocessedEntityInFileIDEjNS_6FileIDE", scope: !1094, file: !12, line: 281, type: !1167, scopeLine: 281, containingType: !1094, virtualIndex: 4, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1167 = !DISubroutineType(types: !1168)
!1168 = !{!1169, !1104, !6, !1271}
!1169 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Optional<bool>", scope: !80, file: !1170, line: 31, size: 16, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !1171, templateParams: !1269, identifier: "_ZTSN4llvm8OptionalIbEE")
!1170 = !DIFile(filename: "llvm34/include/llvm/ADT/Optional.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "0a8f82188b0047033bdb72eb547243c2")
!1171 = !{!1172, !1194, !1195, !1203, !1206, !1210, !1215, !1219, !1223, !1227, !1230, !1234, !1237, !1240, !1241, !1242, !1246, !1250, !1253, !1257, !1260, !1261, !1262, !1263, !1264, !1265, !1268}
!1172 = !DIDerivedType(tag: DW_TAG_member, name: "storage", scope: !1169, file: !1170, line: 32, baseType: !1173, size: 8)
!1173 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArrayUnion<bool, char, char, char, char, char, char>", scope: !80, file: !1174, line: 199, size: 8, flags: DIFlagTypePassByValue, elements: !1175, templateParams: !1186, identifier: "_ZTSN4llvm21AlignedCharArrayUnionIbccccccEE")
!1174 = !DIFile(filename: "llvm34/include/llvm/Support/AlignOf.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "55acc245b7ffca1b8660602cb703d9fb")
!1175 = !{!1176}
!1176 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1173, baseType: !1177, extraData: i32 0)
!1177 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignedCharArray<1UL, 1UL>", scope: !80, file: !1174, line: 75, size: 8, flags: DIFlagTypePassByValue, elements: !1178, templateParams: !1183, identifier: "_ZTSN4llvm16AlignedCharArrayILm1ELm1EEE")
!1178 = !{!1179}
!1179 = !DIDerivedType(tag: DW_TAG_member, name: "buffer", scope: !1177, file: !1174, line: 76, baseType: !1180, size: 8, align: 8)
!1180 = !DICompositeType(tag: DW_TAG_array_type, baseType: !641, size: 8, elements: !1181)
!1181 = !{!1182}
!1182 = !DISubrange(count: 1)
!1183 = !{!1184, !1185}
!1184 = !DITemplateValueParameter(name: "Alignment", type: !145, value: i64 1)
!1185 = !DITemplateValueParameter(name: "Size", type: !145, value: i64 1)
!1186 = !{!1187, !1188, !1189, !1190, !1191, !1192, !1193}
!1187 = !DITemplateTypeParameter(name: "T1", type: !46)
!1188 = !DITemplateTypeParameter(name: "T2", type: !641, defaulted: true)
!1189 = !DITemplateTypeParameter(name: "T3", type: !641, defaulted: true)
!1190 = !DITemplateTypeParameter(name: "T4", type: !641, defaulted: true)
!1191 = !DITemplateTypeParameter(name: "T5", type: !641, defaulted: true)
!1192 = !DITemplateTypeParameter(name: "T6", type: !641, defaulted: true)
!1193 = !DITemplateTypeParameter(name: "T7", type: !641, defaulted: true)
!1194 = !DIDerivedType(tag: DW_TAG_member, name: "hasVal", scope: !1169, file: !1170, line: 33, baseType: !46, size: 8, offset: 8)
!1195 = !DISubprogram(name: "Optional", scope: !1169, file: !1170, line: 35, type: !1196, scopeLine: 35, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1196 = !DISubroutineType(types: !1197)
!1197 = !{null, !1198, !1199}
!1198 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1169, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1199 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "NoneType", scope: !80, file: !1200, line: 22, baseType: !6, size: 32, elements: !1201, identifier: "_ZTSN4llvm8NoneTypeE")
!1200 = !DIFile(filename: "llvm34/include/llvm/ADT/None.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "a0342314f03a5b3ad15259d9915a8f1b")
!1201 = !{!1202}
!1202 = !DIEnumerator(name: "None", value: 0, isUnsigned: true)
!1203 = !DISubprogram(name: "Optional", scope: !1169, file: !1170, line: 36, type: !1204, scopeLine: 36, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1204 = !DISubroutineType(types: !1205)
!1205 = !{null, !1198}
!1206 = !DISubprogram(name: "Optional", scope: !1169, file: !1170, line: 37, type: !1207, scopeLine: 37, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1207 = !DISubroutineType(types: !1208)
!1208 = !{null, !1198, !1209}
!1209 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !660, size: 64)
!1210 = !DISubprogram(name: "Optional", scope: !1169, file: !1170, line: 40, type: !1211, scopeLine: 40, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1211 = !DISubroutineType(types: !1212)
!1212 = !{null, !1198, !1213}
!1213 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1214, size: 64)
!1214 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1169)
!1215 = !DISubprogram(name: "Optional", scope: !1169, file: !1170, line: 46, type: !1216, scopeLine: 46, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1216 = !DISubroutineType(types: !1217)
!1217 = !{null, !1198, !1218}
!1218 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !46, size: 64)
!1219 = !DISubprogram(name: "Optional", scope: !1169, file: !1170, line: 49, type: !1220, scopeLine: 49, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1220 = !DISubroutineType(types: !1221)
!1221 = !{null, !1198, !1222}
!1222 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1169, size: 64)
!1223 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8OptionalIbEaSEOb", scope: !1169, file: !1170, line: 55, type: !1224, scopeLine: 55, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1224 = !DISubroutineType(types: !1225)
!1225 = !{!1226, !1198, !1218}
!1226 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1169, size: 64)
!1227 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8OptionalIbEaSEOS1_", scope: !1169, file: !1170, line: 64, type: !1228, scopeLine: 64, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1228 = !DISubroutineType(types: !1229)
!1229 = !{!1226, !1198, !1222}
!1230 = !DISubprogram(name: "create", linkageName: "_ZN4llvm8OptionalIbE6createEPKb", scope: !1169, file: !1170, line: 75, type: !1231, scopeLine: 75, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1231 = !DISubroutineType(types: !1232)
!1232 = !{!1169, !1233}
!1233 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !660, size: 64)
!1234 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8OptionalIbEaSERKb", scope: !1169, file: !1170, line: 84, type: !1235, scopeLine: 84, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1235 = !DISubroutineType(types: !1236)
!1236 = !{!1226, !1198, !1209}
!1237 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm8OptionalIbEaSERKS1_", scope: !1169, file: !1170, line: 94, type: !1238, scopeLine: 94, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1238 = !DISubroutineType(types: !1239)
!1239 = !{!1226, !1198, !1213}
!1240 = !DISubprogram(name: "reset", linkageName: "_ZN4llvm8OptionalIbE5resetEv", scope: !1169, file: !1170, line: 102, type: !1204, scopeLine: 102, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1241 = !DISubprogram(name: "~Optional", scope: !1169, file: !1170, line: 109, type: !1204, scopeLine: 109, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1242 = !DISubprogram(name: "getPointer", linkageName: "_ZNK4llvm8OptionalIbE10getPointerEv", scope: !1169, file: !1170, line: 113, type: !1243, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1243 = !DISubroutineType(types: !1244)
!1244 = !{!1233, !1245}
!1245 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1214, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1246 = !DISubprogram(name: "getPointer", linkageName: "_ZN4llvm8OptionalIbE10getPointerEv", scope: !1169, file: !1170, line: 114, type: !1247, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1247 = !DISubroutineType(types: !1248)
!1248 = !{!1249, !1198}
!1249 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !46, size: 64)
!1250 = !DISubprogram(name: "getValue", linkageName: "_ZNKR4llvm8OptionalIbE8getValueEv", scope: !1169, file: !1170, line: 115, type: !1251, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped | DIFlagLValueReference, spFlags: DISPFlagOptimized)
!1251 = !DISubroutineType(flags: DIFlagLValueReference, types: !1252)
!1252 = !{!1209, !1245}
!1253 = !DISubprogram(name: "getValue", linkageName: "_ZNR4llvm8OptionalIbE8getValueEv", scope: !1169, file: !1170, line: 116, type: !1254, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped | DIFlagLValueReference, spFlags: DISPFlagOptimized)
!1254 = !DISubroutineType(flags: DIFlagLValueReference, types: !1255)
!1255 = !{!1256, !1198}
!1256 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !46, size: 64)
!1257 = !DISubprogram(name: "operator bool", linkageName: "_ZNK4llvm8OptionalIbEcvbEv", scope: !1169, file: !1170, line: 118, type: !1258, scopeLine: 118, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1258 = !DISubroutineType(types: !1259)
!1259 = !{!46, !1245}
!1260 = !DISubprogram(name: "hasValue", linkageName: "_ZNK4llvm8OptionalIbE8hasValueEv", scope: !1169, file: !1170, line: 119, type: !1258, scopeLine: 119, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1261 = !DISubprogram(name: "operator->", linkageName: "_ZNK4llvm8OptionalIbEptEv", scope: !1169, file: !1170, line: 120, type: !1243, scopeLine: 120, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1262 = !DISubprogram(name: "operator->", linkageName: "_ZN4llvm8OptionalIbEptEv", scope: !1169, file: !1170, line: 121, type: !1247, scopeLine: 121, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1263 = !DISubprogram(name: "operator*", linkageName: "_ZNKR4llvm8OptionalIbEdeEv", scope: !1169, file: !1170, line: 122, type: !1251, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped | DIFlagLValueReference, spFlags: DISPFlagOptimized)
!1264 = !DISubprogram(name: "operator*", linkageName: "_ZNR4llvm8OptionalIbEdeEv", scope: !1169, file: !1170, line: 123, type: !1254, scopeLine: 123, flags: DIFlagPublic | DIFlagPrototyped | DIFlagLValueReference, spFlags: DISPFlagOptimized)
!1265 = !DISubprogram(name: "getValue", linkageName: "_ZNO4llvm8OptionalIbE8getValueEv", scope: !1169, file: !1170, line: 126, type: !1266, scopeLine: 126, flags: DIFlagPublic | DIFlagPrototyped | DIFlagRValueReference, spFlags: DISPFlagOptimized)
!1266 = !DISubroutineType(flags: DIFlagRValueReference, types: !1267)
!1267 = !{!1218, !1198}
!1268 = !DISubprogram(name: "operator*", linkageName: "_ZNO4llvm8OptionalIbEdeEv", scope: !1169, file: !1170, line: 127, type: !1266, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped | DIFlagRValueReference, spFlags: DISPFlagOptimized)
!1269 = !{!1270}
!1270 = !DITemplateTypeParameter(name: "T", type: !46)
!1271 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FileID", scope: !14, file: !33, line: 39, size: 32, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang6FileIDE")
!1272 = !DIDerivedType(tag: DW_TAG_member, name: "CachedRangeQuery", scope: !147, file: !12, line: 590, baseType: !1273, size: 128, offset: 1344)
!1273 = distinct !DICompositeType(tag: DW_TAG_structure_type, scope: !147, file: !12, line: 587, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1274, identifier: "_ZTSN5clang19PreprocessingRecordUt_E")
!1274 = !{!1275, !1276}
!1275 = !DIDerivedType(tag: DW_TAG_member, name: "Range", scope: !1273, file: !12, line: 588, baseType: !32, size: 64)
!1276 = !DIDerivedType(tag: DW_TAG_member, name: "Result", scope: !1273, file: !12, line: 589, baseType: !1277, size: 64, offset: 64)
!1277 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<int, int>", scope: !91, file: !713, line: 208, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1278, templateParams: !1329, identifier: "_ZTSSt4pairIiiE")
!1278 = !{!1279, !1299, !1300, !1301, !1307, !1311, !1319, !1326}
!1279 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1277, baseType: !1280, flags: DIFlagPrivate, extraData: i32 0)
!1280 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<int, int>", scope: !91, file: !713, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !1281, templateParams: !1296, identifier: "_ZTSSt11__pair_baseIiiE")
!1281 = !{!1282, !1286, !1287, !1292}
!1282 = !DISubprogram(name: "__pair_base", scope: !1280, file: !713, line: 194, type: !1283, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1283 = !DISubroutineType(types: !1284)
!1284 = !{null, !1285}
!1285 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1280, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1286 = !DISubprogram(name: "~__pair_base", scope: !1280, file: !713, line: 195, type: !1283, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1287 = !DISubprogram(name: "__pair_base", scope: !1280, file: !713, line: 196, type: !1288, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1288 = !DISubroutineType(types: !1289)
!1289 = !{null, !1285, !1290}
!1290 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1291, size: 64)
!1291 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1280)
!1292 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIiiEaSERKS0_", scope: !1280, file: !713, line: 197, type: !1293, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1293 = !DISubroutineType(types: !1294)
!1294 = !{!1295, !1285, !1290}
!1295 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1280, size: 64)
!1296 = !{!1297, !1298}
!1297 = !DITemplateTypeParameter(name: "_U1", type: !62)
!1298 = !DITemplateTypeParameter(name: "_U2", type: !62)
!1299 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !1277, file: !713, line: 214, baseType: !62, size: 32)
!1300 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !1277, file: !713, line: 215, baseType: !62, size: 32, offset: 32)
!1301 = !DISubprogram(name: "pair", scope: !1277, file: !713, line: 303, type: !1302, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1302 = !DISubroutineType(types: !1303)
!1303 = !{null, !1304, !1305}
!1304 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1277, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1305 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1306, size: 64)
!1306 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1277)
!1307 = !DISubprogram(name: "pair", scope: !1277, file: !713, line: 304, type: !1308, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1308 = !DISubroutineType(types: !1309)
!1309 = !{null, !1304, !1310}
!1310 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1277, size: 64)
!1311 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIiiEaSERKS0_", scope: !1277, file: !713, line: 378, type: !1312, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1312 = !DISubroutineType(types: !1313)
!1313 = !{!1314, !1304, !1315}
!1314 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1277, size: 64)
!1315 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1316, file: !656, line: 1928, baseType: !1305)
!1316 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<int, int> &, const std::__nonesuch_no_braces &>", scope: !91, file: !656, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !1317, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIiiERKSt20__nonesuch_no_bracesE")
!1317 = !{!782, !1318, !784}
!1318 = !DITemplateTypeParameter(name: "_Iftrue", type: !1305)
!1319 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIiiEaSEOS0_", scope: !1277, file: !713, line: 389, type: !1320, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1320 = !DISubroutineType(types: !1321)
!1321 = !{!1314, !1304, !1322}
!1322 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1323, file: !656, line: 1928, baseType: !1310)
!1323 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<int, int> &&, std::__nonesuch_no_braces &&>", scope: !91, file: !656, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !1324, identifier: "_ZTSSt11conditionalILb1EOSt4pairIiiEOSt20__nonesuch_no_bracesE")
!1324 = !{!782, !1325, !795}
!1325 = !DITemplateTypeParameter(name: "_Iftrue", type: !1310)
!1326 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIiiE4swapERS0_", scope: !1277, file: !713, line: 424, type: !1327, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1327 = !DISubroutineType(types: !1328)
!1328 = !{null, !1304, !1314}
!1329 = !{!1330, !1331}
!1330 = !DITemplateTypeParameter(name: "_T1", type: !62)
!1331 = !DITemplateTypeParameter(name: "_T2", type: !62)
!1332 = !DISubprogram(name: "getPPEntityID", linkageName: "_ZN5clang19PreprocessingRecord13getPPEntityIDEjb", scope: !147, file: !12, line: 324, type: !1333, scopeLine: 324, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1333 = !DISubroutineType(types: !1334)
!1334 = !{!1335, !6, !46}
!1335 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PPEntityID", scope: !147, file: !12, line: 316, size: 32, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1336, identifier: "_ZTSN5clang19PreprocessingRecord10PPEntityIDE")
!1336 = !{!1337, !1338, !1342}
!1337 = !DIDerivedType(tag: DW_TAG_member, name: "ID", scope: !1335, file: !12, line: 317, baseType: !62, size: 32)
!1338 = !DISubprogram(name: "PPEntityID", scope: !1335, file: !12, line: 318, type: !1339, scopeLine: 318, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1339 = !DISubroutineType(types: !1340)
!1340 = !{null, !1341, !62}
!1341 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1335, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1342 = !DISubprogram(name: "PPEntityID", scope: !1335, file: !12, line: 321, type: !1343, scopeLine: 321, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1343 = !DISubroutineType(types: !1344)
!1344 = !{null, !1341}
!1345 = !DISubprogram(name: "getPreprocessedEntity", linkageName: "_ZN5clang19PreprocessingRecord21getPreprocessedEntityENS0_10PPEntityIDE", scope: !147, file: !12, line: 335, type: !1346, scopeLine: 335, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1346 = !DISubroutineType(types: !1347)
!1347 = !{!183, !1348, !1335}
!1348 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !147, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1349 = !DISubprogram(name: "getLoadedPreprocessedEntity", linkageName: "_ZN5clang19PreprocessingRecord27getLoadedPreprocessedEntityEj", scope: !147, file: !12, line: 338, type: !1350, scopeLine: 338, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1350 = !DISubroutineType(types: !1351)
!1351 = !{!183, !1348, !6}
!1352 = !DISubprogram(name: "getNumLoadedPreprocessedEntities", linkageName: "_ZNK5clang19PreprocessingRecord32getNumLoadedPreprocessedEntitiesEv", scope: !147, file: !12, line: 342, type: !1353, scopeLine: 342, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1353 = !DISubroutineType(types: !1354)
!1354 = !{!6, !1355}
!1355 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1356, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1356 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !147)
!1357 = !DISubprogram(name: "findLocalPreprocessedEntitiesInRange", linkageName: "_ZNK5clang19PreprocessingRecord36findLocalPreprocessedEntitiesInRangeENS_11SourceRangeE", scope: !147, file: !12, line: 349, type: !1358, scopeLine: 349, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1358 = !DISubroutineType(types: !1359)
!1359 = !{!1111, !1355, !32}
!1360 = !DISubprogram(name: "findBeginLocalPreprocessedEntity", linkageName: "_ZNK5clang19PreprocessingRecord32findBeginLocalPreprocessedEntityENS_14SourceLocationE", scope: !147, file: !12, line: 350, type: !1361, scopeLine: 350, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1361 = !DISubroutineType(types: !1362)
!1362 = !{!6, !1355, !36}
!1363 = !DISubprogram(name: "findEndLocalPreprocessedEntity", linkageName: "_ZNK5clang19PreprocessingRecord30findEndLocalPreprocessedEntityENS_14SourceLocationE", scope: !147, file: !12, line: 351, type: !1361, scopeLine: 351, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1364 = !DISubprogram(name: "allocateLoadedEntities", linkageName: "_ZN5clang19PreprocessingRecord22allocateLoadedEntitiesEj", scope: !147, file: !12, line: 357, type: !1365, scopeLine: 357, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1365 = !DISubroutineType(types: !1366)
!1366 = !{!6, !1348, !6}
!1367 = !DISubprogram(name: "RegisterMacroDefinition", linkageName: "_ZN5clang19PreprocessingRecord23RegisterMacroDefinitionEPNS_9MacroInfoEPNS_15MacroDefinitionE", scope: !147, file: !12, line: 360, type: !1368, scopeLine: 360, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1368 = !DISubroutineType(types: !1369)
!1369 = !{null, !1348, !1370, !739}
!1370 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !736, size: 64)
!1371 = !DISubprogram(name: "PreprocessingRecord", scope: !147, file: !12, line: 364, type: !1372, scopeLine: 364, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1372 = !DISubroutineType(types: !1373)
!1373 = !{null, !1348, !153}
!1374 = !DISubprogram(name: "Allocate", linkageName: "_ZN5clang19PreprocessingRecord8AllocateEjj", scope: !147, file: !12, line: 367, type: !1375, scopeLine: 367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1375 = !DISubroutineType(types: !1376)
!1376 = !{!68, !1348, !6, !6}
!1377 = !DISubprogram(name: "Deallocate", linkageName: "_ZN5clang19PreprocessingRecord10DeallocateEPv", scope: !147, file: !12, line: 372, type: !1378, scopeLine: 372, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1378 = !DISubroutineType(types: !1379)
!1379 = !{null, !1348, !68}
!1380 = !DISubprogram(name: "getTotalMemory", linkageName: "_ZNK5clang19PreprocessingRecord14getTotalMemoryEv", scope: !147, file: !12, line: 374, type: !1381, scopeLine: 374, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1381 = !DISubroutineType(types: !1382)
!1382 = !{!143, !1355}
!1383 = !DISubprogram(name: "getSourceManager", linkageName: "_ZNK5clang19PreprocessingRecord16getSourceManagerEv", scope: !147, file: !12, line: 376, type: !1384, scopeLine: 376, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1384 = !DISubroutineType(types: !1385)
!1385 = !{!153, !1355}
!1386 = !DISubprogram(name: "begin", linkageName: "_ZN5clang19PreprocessingRecord5beginEv", scope: !147, file: !12, line: 499, type: !1387, scopeLine: 499, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1387 = !DISubroutineType(types: !1388)
!1388 = !{!1389, !1348}
!1389 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "iterator", scope: !147, file: !12, line: 379, size: 128, flags: DIFlagPublic | DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1390, identifier: "_ZTSN5clang19PreprocessingRecord8iteratorE")
!1390 = !{!1391, !1393, !1394, !1398, !1401, !1407, !1411, !1415, !1418, !1419}
!1391 = !DIDerivedType(tag: DW_TAG_member, name: "Self", scope: !1389, file: !12, line: 380, baseType: !1392, size: 64)
!1392 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !147, size: 64)
!1393 = !DIDerivedType(tag: DW_TAG_member, name: "Position", scope: !1389, file: !12, line: 394, baseType: !62, size: 32, offset: 64)
!1394 = !DISubprogram(name: "iterator", scope: !1389, file: !12, line: 403, type: !1395, scopeLine: 403, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1395 = !DISubroutineType(types: !1396)
!1396 = !{null, !1397}
!1397 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1389, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1398 = !DISubprogram(name: "iterator", scope: !1389, file: !12, line: 405, type: !1399, scopeLine: 405, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1399 = !DISubroutineType(types: !1400)
!1400 = !{null, !1397, !1392, !62}
!1401 = !DISubprogram(name: "operator*", linkageName: "_ZNK5clang19PreprocessingRecord8iteratordeEv", scope: !1389, file: !12, line: 408, type: !1402, scopeLine: 408, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1402 = !DISubroutineType(types: !1403)
!1403 = !{!1404, !1405}
!1404 = !DIDerivedType(tag: DW_TAG_typedef, name: "value_type", scope: !1389, file: !12, line: 397, baseType: !183)
!1405 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1406, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1406 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1389)
!1407 = !DISubprogram(name: "operator[]", linkageName: "_ZN5clang19PreprocessingRecord8iteratorixEi", scope: !1389, file: !12, line: 416, type: !1408, scopeLine: 416, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1408 = !DISubroutineType(types: !1409)
!1409 = !{!1404, !1397, !1410}
!1410 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !1389, file: !12, line: 401, baseType: !62)
!1411 = !DISubprogram(name: "operator++", linkageName: "_ZN5clang19PreprocessingRecord8iteratorppEv", scope: !1389, file: !12, line: 420, type: !1412, scopeLine: 420, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1412 = !DISubroutineType(types: !1413)
!1413 = !{!1414, !1397}
!1414 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1389, size: 64)
!1415 = !DISubprogram(name: "operator++", linkageName: "_ZN5clang19PreprocessingRecord8iteratorppEi", scope: !1389, file: !12, line: 425, type: !1416, scopeLine: 425, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1416 = !DISubroutineType(types: !1417)
!1417 = !{!1389, !1397, !62}
!1418 = !DISubprogram(name: "operator--", linkageName: "_ZN5clang19PreprocessingRecord8iteratormmEv", scope: !1389, file: !12, line: 431, type: !1412, scopeLine: 431, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1419 = !DISubprogram(name: "operator--", linkageName: "_ZN5clang19PreprocessingRecord8iteratormmEi", scope: !1389, file: !12, line: 436, type: !1416, scopeLine: 436, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1420 = !DISubprogram(name: "end", linkageName: "_ZN5clang19PreprocessingRecord3endEv", scope: !147, file: !12, line: 504, type: !1387, scopeLine: 504, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1421 = !DISubprogram(name: "local_begin", linkageName: "_ZN5clang19PreprocessingRecord11local_beginEv", scope: !147, file: !12, line: 509, type: !1387, scopeLine: 509, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1422 = !DISubprogram(name: "local_end", linkageName: "_ZN5clang19PreprocessingRecord9local_endEv", scope: !147, file: !12, line: 514, type: !1387, scopeLine: 514, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1423 = !DISubprogram(name: "getIteratorsForLoadedRange", linkageName: "_ZN5clang19PreprocessingRecord26getIteratorsForLoadedRangeEjj", scope: !147, file: !12, line: 521, type: !1424, scopeLine: 521, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1424 = !DISubroutineType(types: !1425)
!1425 = !{!1426, !1348, !6, !6}
!1426 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<clang::PreprocessingRecord::iterator, clang::PreprocessingRecord::iterator>", scope: !91, file: !713, line: 208, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1427, templateParams: !1478, identifier: "_ZTSSt4pairIN5clang19PreprocessingRecord8iteratorES2_E")
!1427 = !{!1428, !1448, !1449, !1450, !1456, !1460, !1468, !1475}
!1428 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1426, baseType: !1429, flags: DIFlagPrivate, extraData: i32 0)
!1429 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<clang::PreprocessingRecord::iterator, clang::PreprocessingRecord::iterator>", scope: !91, file: !713, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !1430, templateParams: !1445, identifier: "_ZTSSt11__pair_baseIN5clang19PreprocessingRecord8iteratorES2_E")
!1430 = !{!1431, !1435, !1436, !1441}
!1431 = !DISubprogram(name: "__pair_base", scope: !1429, file: !713, line: 194, type: !1432, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1432 = !DISubroutineType(types: !1433)
!1433 = !{null, !1434}
!1434 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1429, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1435 = !DISubprogram(name: "~__pair_base", scope: !1429, file: !713, line: 195, type: !1432, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1436 = !DISubprogram(name: "__pair_base", scope: !1429, file: !713, line: 196, type: !1437, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1437 = !DISubroutineType(types: !1438)
!1438 = !{null, !1434, !1439}
!1439 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1440, size: 64)
!1440 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1429)
!1441 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN5clang19PreprocessingRecord8iteratorES2_EaSERKS3_", scope: !1429, file: !713, line: 197, type: !1442, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1442 = !DISubroutineType(types: !1443)
!1443 = !{!1444, !1434, !1439}
!1444 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1429, size: 64)
!1445 = !{!1446, !1447}
!1446 = !DITemplateTypeParameter(name: "_U1", type: !1389)
!1447 = !DITemplateTypeParameter(name: "_U2", type: !1389)
!1448 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !1426, file: !713, line: 214, baseType: !1389, size: 128)
!1449 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !1426, file: !713, line: 215, baseType: !1389, size: 128, offset: 128)
!1450 = !DISubprogram(name: "pair", scope: !1426, file: !713, line: 303, type: !1451, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1451 = !DISubroutineType(types: !1452)
!1452 = !{null, !1453, !1454}
!1453 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1426, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1454 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1455, size: 64)
!1455 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1426)
!1456 = !DISubprogram(name: "pair", scope: !1426, file: !713, line: 304, type: !1457, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1457 = !DISubroutineType(types: !1458)
!1458 = !{null, !1453, !1459}
!1459 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1426, size: 64)
!1460 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN5clang19PreprocessingRecord8iteratorES2_EaSERKS3_", scope: !1426, file: !713, line: 378, type: !1461, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1461 = !DISubroutineType(types: !1462)
!1462 = !{!1463, !1453, !1464}
!1463 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1426, size: 64)
!1464 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1465, file: !656, line: 1928, baseType: !1454)
!1465 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<clang::PreprocessingRecord::iterator, clang::PreprocessingRecord::iterator> &, const std::__nonesuch_no_braces &>", scope: !91, file: !656, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !1466, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN5clang19PreprocessingRecord8iteratorES3_ERKSt20__nonesuch_no_bracesE")
!1466 = !{!782, !1467, !784}
!1467 = !DITemplateTypeParameter(name: "_Iftrue", type: !1454)
!1468 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN5clang19PreprocessingRecord8iteratorES2_EaSEOS3_", scope: !1426, file: !713, line: 389, type: !1469, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1469 = !DISubroutineType(types: !1470)
!1470 = !{!1463, !1453, !1471}
!1471 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1472, file: !656, line: 1928, baseType: !1459)
!1472 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<clang::PreprocessingRecord::iterator, clang::PreprocessingRecord::iterator> &&, std::__nonesuch_no_braces &&>", scope: !91, file: !656, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !1473, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN5clang19PreprocessingRecord8iteratorES3_EOSt20__nonesuch_no_bracesE")
!1473 = !{!782, !1474, !795}
!1474 = !DITemplateTypeParameter(name: "_Iftrue", type: !1459)
!1475 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN5clang19PreprocessingRecord8iteratorES2_E4swapERS3_", scope: !1426, file: !713, line: 424, type: !1476, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1476 = !DISubroutineType(types: !1477)
!1477 = !{null, !1453, !1463}
!1478 = !{!1479, !1480}
!1479 = !DITemplateTypeParameter(name: "_T1", type: !1389)
!1480 = !DITemplateTypeParameter(name: "_T2", type: !1389)
!1481 = !DISubprogram(name: "getPreprocessedEntitiesInRange", linkageName: "_ZN5clang19PreprocessingRecord30getPreprocessedEntitiesInRangeENS_11SourceRangeE", scope: !147, file: !12, line: 534, type: !1482, scopeLine: 534, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1482 = !DISubroutineType(types: !1483)
!1483 = !{!1426, !1348, !32}
!1484 = !DISubprogram(name: "isEntityInFileID", linkageName: "_ZN5clang19PreprocessingRecord16isEntityInFileIDENS0_8iteratorENS_6FileIDE", scope: !147, file: !12, line: 543, type: !1485, scopeLine: 543, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1485 = !DISubroutineType(types: !1486)
!1486 = !{!46, !1348, !1389, !1271}
!1487 = !DISubprogram(name: "addPreprocessedEntity", linkageName: "_ZN5clang19PreprocessingRecord21addPreprocessedEntityEPNS_18PreprocessedEntityE", scope: !147, file: !12, line: 546, type: !1488, scopeLine: 546, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1488 = !DISubroutineType(types: !1489)
!1489 = !{!1335, !1348, !183}
!1490 = !DISubprogram(name: "SetExternalSource", linkageName: "_ZN5clang19PreprocessingRecord17SetExternalSourceERNS_33ExternalPreprocessingRecordSourceE", scope: !147, file: !12, line: 549, type: !1491, scopeLine: 549, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1491 = !DISubroutineType(types: !1492)
!1492 = !{null, !1348, !1493}
!1493 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1094, size: 64)
!1494 = !DISubprogram(name: "getExternalSource", linkageName: "_ZNK5clang19PreprocessingRecord17getExternalSourceEv", scope: !147, file: !12, line: 552, type: !1495, scopeLine: 552, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1495 = !DISubroutineType(types: !1496)
!1496 = !{!1093, !1355}
!1497 = !DISubprogram(name: "findMacroDefinition", linkageName: "_ZN5clang19PreprocessingRecord19findMacroDefinitionEPKNS_9MacroInfoE", scope: !147, file: !12, line: 558, type: !1498, scopeLine: 558, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1498 = !DISubroutineType(types: !1499)
!1499 = !{!739, !1348, !734}
!1500 = !DISubprogram(name: "MacroExpands", linkageName: "_ZN5clang19PreprocessingRecord12MacroExpandsERKNS_5TokenEPKNS_14MacroDirectiveENS_11SourceRangeEPKNS_9MacroArgsE", scope: !147, file: !12, line: 561, type: !1501, scopeLine: 561, containingType: !147, virtualIndex: 21, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1501 = !DISubroutineType(types: !1502)
!1502 = !{null, !1348, !1503, !1507, !32, !1510}
!1503 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1504, size: 64)
!1504 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1505)
!1505 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Token", scope: !14, file: !1506, line: 36, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang5TokenE")
!1506 = !DIFile(filename: "llvm34/projects/clang/include/clang/Lex/Token.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "68b6c37e8c920a18be3730d77a6d50a1")
!1507 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1508, size: 64)
!1508 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1509)
!1509 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MacroDirective", scope: !14, file: !737, line: 321, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang14MacroDirectiveE")
!1510 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1511, size: 64)
!1511 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1512)
!1512 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MacroArgs", scope: !14, file: !151, line: 31, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang9MacroArgsE")
!1513 = !DISubprogram(name: "MacroDefined", linkageName: "_ZN5clang19PreprocessingRecord12MacroDefinedERKNS_5TokenEPKNS_14MacroDirectiveE", scope: !147, file: !12, line: 563, type: !1514, scopeLine: 563, containingType: !147, virtualIndex: 22, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1514 = !DISubroutineType(types: !1515)
!1515 = !{null, !1348, !1503, !1507}
!1516 = !DISubprogram(name: "MacroUndefined", linkageName: "_ZN5clang19PreprocessingRecord14MacroUndefinedERKNS_5TokenEPKNS_14MacroDirectiveE", scope: !147, file: !12, line: 564, type: !1514, scopeLine: 564, containingType: !147, virtualIndex: 23, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1517 = !DISubprogram(name: "InclusionDirective", linkageName: "_ZN5clang19PreprocessingRecord18InclusionDirectiveENS_14SourceLocationERKNS_5TokenEN4llvm9StringRefEbNS_15CharSourceRangeEPKNS_9FileEntryES6_S6_PKNS_6ModuleE", scope: !147, file: !12, line: 565, type: !1518, scopeLine: 565, containingType: !147, virtualIndex: 5, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1518 = !DISubroutineType(types: !1519)
!1519 = !{null, !1348, !36, !1503, !1520, !46, !1701, !1702, !1520, !1520, !1706}
!1520 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "StringRef", scope: !80, file: !1521, line: 41, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1522, identifier: "_ZTSN4llvm9StringRefE")
!1521 = !DIFile(filename: "llvm34/include/llvm/ADT/StringRef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "5c2e300880041c873457392c89335431")
!1522 = !{!1523, !1525, !1526, !1527, !1530, !1531, !1534, !1538, !1541, !1544, !1549, !1555, !1556, !1559, !1562, !1565, !1568, !1569, !1572, !1573, !1576, !1577, !1578, !1581, !1584, !1587, !1588, !1589, !1590, !1591, !1592, !1595, !1598, !1599, !1602, !1603, !1604, !1605, !1606, !1607, !1608, !1609, !1610, !1613, !1614, !1619, !1620, !1621, !1624, !1627, !1628, !1629, !1687, !1690, !1695, !1696, !1699, !1700}
!1523 = !DIDerivedType(tag: DW_TAG_member, name: "npos", scope: !1520, file: !1521, line: 45, baseType: !1524, flags: DIFlagPublic | DIFlagStaticMember, extraData: i64 -1)
!1524 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !143)
!1525 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !1520, file: !1521, line: 50, baseType: !639, size: 64)
!1526 = !DIDerivedType(tag: DW_TAG_member, name: "Length", scope: !1520, file: !1521, line: 53, baseType: !143, size: 64, offset: 64)
!1527 = !DISubprogram(name: "min", linkageName: "_ZN4llvm9StringRef3minEmm", scope: !1520, file: !1521, line: 58, type: !1528, scopeLine: 58, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1528 = !DISubroutineType(types: !1529)
!1529 = !{!143, !143, !143}
!1530 = !DISubprogram(name: "max", linkageName: "_ZN4llvm9StringRef3maxEmm", scope: !1520, file: !1521, line: 59, type: !1528, scopeLine: 59, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1531 = !DISubprogram(name: "compareMemory", linkageName: "_ZN4llvm9StringRef13compareMemoryEPKcS2_m", scope: !1520, file: !1521, line: 63, type: !1532, scopeLine: 63, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1532 = !DISubroutineType(types: !1533)
!1533 = !{!62, !639, !639, !143}
!1534 = !DISubprogram(name: "StringRef", scope: !1520, file: !1521, line: 73, type: !1535, scopeLine: 73, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1535 = !DISubroutineType(types: !1536)
!1536 = !{null, !1537}
!1537 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1520, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1538 = !DISubprogram(name: "StringRef", scope: !1520, file: !1521, line: 76, type: !1539, scopeLine: 76, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1539 = !DISubroutineType(types: !1540)
!1540 = !{null, !1537, !639}
!1541 = !DISubprogram(name: "StringRef", scope: !1520, file: !1521, line: 83, type: !1542, scopeLine: 83, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1542 = !DISubroutineType(types: !1543)
!1543 = !{null, !1537, !639, !143}
!1544 = !DISubprogram(name: "StringRef", scope: !1520, file: !1521, line: 90, type: !1545, scopeLine: 90, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1545 = !DISubroutineType(types: !1546)
!1546 = !{null, !1537, !1547}
!1547 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1548, size: 64)
!1548 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !88)
!1549 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm9StringRef5beginEv", scope: !1520, file: !1521, line: 97, type: !1550, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1550 = !DISubroutineType(types: !1551)
!1551 = !{!1552, !1553}
!1552 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !1520, file: !1521, line: 43, baseType: !639)
!1553 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1554, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1554 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1520)
!1555 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm9StringRef3endEv", scope: !1520, file: !1521, line: 99, type: !1550, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1556 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm9StringRef4dataEv", scope: !1520, file: !1521, line: 107, type: !1557, scopeLine: 107, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1557 = !DISubroutineType(types: !1558)
!1558 = !{!639, !1553}
!1559 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm9StringRef5emptyEv", scope: !1520, file: !1521, line: 110, type: !1560, scopeLine: 110, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1560 = !DISubroutineType(types: !1561)
!1561 = !{!46, !1553}
!1562 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm9StringRef4sizeEv", scope: !1520, file: !1521, line: 113, type: !1563, scopeLine: 113, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1563 = !DISubroutineType(types: !1564)
!1564 = !{!143, !1553}
!1565 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm9StringRef5frontEv", scope: !1520, file: !1521, line: 116, type: !1566, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1566 = !DISubroutineType(types: !1567)
!1567 = !{!641, !1553}
!1568 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm9StringRef4backEv", scope: !1520, file: !1521, line: 122, type: !1566, scopeLine: 122, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1569 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm9StringRef6equalsES0_", scope: !1520, file: !1521, line: 129, type: !1570, scopeLine: 129, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1570 = !DISubroutineType(types: !1571)
!1571 = !{!46, !1553, !1520}
!1572 = !DISubprogram(name: "equals_lower", linkageName: "_ZNK4llvm9StringRef12equals_lowerES0_", scope: !1520, file: !1521, line: 135, type: !1570, scopeLine: 135, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1573 = !DISubprogram(name: "compare", linkageName: "_ZNK4llvm9StringRef7compareES0_", scope: !1520, file: !1521, line: 141, type: !1574, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1574 = !DISubroutineType(types: !1575)
!1575 = !{!62, !1553, !1520}
!1576 = !DISubprogram(name: "compare_lower", linkageName: "_ZNK4llvm9StringRef13compare_lowerES0_", scope: !1520, file: !1521, line: 153, type: !1574, scopeLine: 153, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1577 = !DISubprogram(name: "compare_numeric", linkageName: "_ZNK4llvm9StringRef15compare_numericES0_", scope: !1520, file: !1521, line: 157, type: !1574, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1578 = !DISubprogram(name: "edit_distance", linkageName: "_ZNK4llvm9StringRef13edit_distanceES0_bj", scope: !1520, file: !1521, line: 177, type: !1579, scopeLine: 177, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1579 = !DISubroutineType(types: !1580)
!1580 = !{!6, !1553, !1520, !46, !6}
!1581 = !DISubprogram(name: "str", linkageName: "_ZNK4llvm9StringRef3strB5cxx11Ev", scope: !1520, file: !1521, line: 181, type: !1582, scopeLine: 181, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1582 = !DISubroutineType(types: !1583)
!1583 = !{!88, !1553}
!1584 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm9StringRefixEm", scope: !1520, file: !1521, line: 190, type: !1585, scopeLine: 190, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1585 = !DISubroutineType(types: !1586)
!1586 = !{!641, !1553, !143}
!1587 = !DISubprogram(name: "operator basic_string", linkageName: "_ZNK4llvm9StringRefcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv", scope: !1520, file: !1521, line: 199, type: !1582, scopeLine: 199, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1588 = !DISubprogram(name: "startswith", linkageName: "_ZNK4llvm9StringRef10startswithES0_", scope: !1520, file: !1521, line: 208, type: !1570, scopeLine: 208, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1589 = !DISubprogram(name: "startswith_lower", linkageName: "_ZNK4llvm9StringRef16startswith_lowerES0_", scope: !1520, file: !1521, line: 214, type: !1570, scopeLine: 214, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1590 = !DISubprogram(name: "endswith", linkageName: "_ZNK4llvm9StringRef8endswithES0_", scope: !1520, file: !1521, line: 217, type: !1570, scopeLine: 217, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1591 = !DISubprogram(name: "endswith_lower", linkageName: "_ZNK4llvm9StringRef14endswith_lowerES0_", scope: !1520, file: !1521, line: 223, type: !1570, scopeLine: 223, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1592 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm9StringRef4findEcm", scope: !1520, file: !1521, line: 233, type: !1593, scopeLine: 233, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1593 = !DISubroutineType(types: !1594)
!1594 = !{!143, !1553, !641, !143}
!1595 = !DISubprogram(name: "find", linkageName: "_ZNK4llvm9StringRef4findES0_m", scope: !1520, file: !1521, line: 244, type: !1596, scopeLine: 244, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1596 = !DISubroutineType(types: !1597)
!1597 = !{!143, !1553, !1520, !143}
!1598 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm9StringRef5rfindEcm", scope: !1520, file: !1521, line: 250, type: !1593, scopeLine: 250, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1599 = !DISubprogram(name: "rfind", linkageName: "_ZNK4llvm9StringRef5rfindES0_", scope: !1520, file: !1521, line: 265, type: !1600, scopeLine: 265, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1600 = !DISubroutineType(types: !1601)
!1601 = !{!143, !1553, !1520}
!1602 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm9StringRef13find_first_ofEcm", scope: !1520, file: !1521, line: 269, type: !1593, scopeLine: 269, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1603 = !DISubprogram(name: "find_first_of", linkageName: "_ZNK4llvm9StringRef13find_first_ofES0_m", scope: !1520, file: !1521, line: 277, type: !1596, scopeLine: 277, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1604 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm9StringRef17find_first_not_ofEcm", scope: !1520, file: !1521, line: 281, type: !1593, scopeLine: 281, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1605 = !DISubprogram(name: "find_first_not_of", linkageName: "_ZNK4llvm9StringRef17find_first_not_ofES0_m", scope: !1520, file: !1521, line: 287, type: !1596, scopeLine: 287, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1606 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm9StringRef12find_last_ofEcm", scope: !1520, file: !1521, line: 291, type: !1593, scopeLine: 291, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1607 = !DISubprogram(name: "find_last_of", linkageName: "_ZNK4llvm9StringRef12find_last_ofES0_m", scope: !1520, file: !1521, line: 299, type: !1596, scopeLine: 299, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1608 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNK4llvm9StringRef16find_last_not_ofEcm", scope: !1520, file: !1521, line: 303, type: !1593, scopeLine: 303, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1609 = !DISubprogram(name: "find_last_not_of", linkageName: "_ZNK4llvm9StringRef16find_last_not_ofES0_m", scope: !1520, file: !1521, line: 309, type: !1596, scopeLine: 309, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1610 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9StringRef5countEc", scope: !1520, file: !1521, line: 316, type: !1611, scopeLine: 316, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1611 = !DISubroutineType(types: !1612)
!1612 = !{!143, !1553, !641}
!1613 = !DISubprogram(name: "count", linkageName: "_ZNK4llvm9StringRef5countES0_", scope: !1520, file: !1521, line: 326, type: !1600, scopeLine: 326, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1614 = !DISubprogram(name: "getAsInteger", linkageName: "_ZNK4llvm9StringRef12getAsIntegerEjRNS_5APIntE", scope: !1520, file: !1521, line: 367, type: !1615, scopeLine: 367, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1615 = !DISubroutineType(types: !1616)
!1616 = !{!46, !1553, !6, !1617}
!1617 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1618, size: 64)
!1618 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "APInt", scope: !80, file: !1521, line: 24, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm5APIntE")
!1619 = !DISubprogram(name: "lower", linkageName: "_ZNK4llvm9StringRef5lowerB5cxx11Ev", scope: !1520, file: !1521, line: 374, type: !1582, scopeLine: 374, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1620 = !DISubprogram(name: "upper", linkageName: "_ZNK4llvm9StringRef5upperB5cxx11Ev", scope: !1520, file: !1521, line: 377, type: !1582, scopeLine: 377, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1621 = !DISubprogram(name: "substr", linkageName: "_ZNK4llvm9StringRef6substrEmm", scope: !1520, file: !1521, line: 392, type: !1622, scopeLine: 392, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1622 = !DISubroutineType(types: !1623)
!1623 = !{!1520, !1553, !143, !143}
!1624 = !DISubprogram(name: "drop_front", linkageName: "_ZNK4llvm9StringRef10drop_frontEm", scope: !1520, file: !1521, line: 399, type: !1625, scopeLine: 399, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1625 = !DISubroutineType(types: !1626)
!1626 = !{!1520, !1553, !143}
!1627 = !DISubprogram(name: "drop_back", linkageName: "_ZNK4llvm9StringRef9drop_backEm", scope: !1520, file: !1521, line: 406, type: !1625, scopeLine: 406, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1628 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm9StringRef5sliceEmm", scope: !1520, file: !1521, line: 421, type: !1622, scopeLine: 421, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1629 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitEc", scope: !1520, file: !1521, line: 437, type: !1630, scopeLine: 437, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1630 = !DISubroutineType(types: !1631)
!1631 = !{!1632, !1553, !641}
!1632 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<llvm::StringRef, llvm::StringRef>", scope: !91, file: !713, line: 208, size: 256, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !1633, templateParams: !1684, identifier: "_ZTSSt4pairIN4llvm9StringRefES1_E")
!1633 = !{!1634, !1654, !1655, !1656, !1662, !1666, !1674, !1681}
!1634 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !1632, baseType: !1635, flags: DIFlagPrivate, extraData: i32 0)
!1635 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<llvm::StringRef, llvm::StringRef>", scope: !91, file: !713, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !1636, templateParams: !1651, identifier: "_ZTSSt11__pair_baseIN4llvm9StringRefES1_E")
!1636 = !{!1637, !1641, !1642, !1647}
!1637 = !DISubprogram(name: "__pair_base", scope: !1635, file: !713, line: 194, type: !1638, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1638 = !DISubroutineType(types: !1639)
!1639 = !{null, !1640}
!1640 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1635, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1641 = !DISubprogram(name: "~__pair_base", scope: !1635, file: !713, line: 195, type: !1638, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1642 = !DISubprogram(name: "__pair_base", scope: !1635, file: !713, line: 196, type: !1643, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1643 = !DISubroutineType(types: !1644)
!1644 = !{null, !1640, !1645}
!1645 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1646, size: 64)
!1646 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1635)
!1647 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN4llvm9StringRefES1_EaSERKS2_", scope: !1635, file: !713, line: 197, type: !1648, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!1648 = !DISubroutineType(types: !1649)
!1649 = !{!1650, !1640, !1645}
!1650 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1635, size: 64)
!1651 = !{!1652, !1653}
!1652 = !DITemplateTypeParameter(name: "_U1", type: !1520)
!1653 = !DITemplateTypeParameter(name: "_U2", type: !1520)
!1654 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !1632, file: !713, line: 214, baseType: !1520, size: 128)
!1655 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !1632, file: !713, line: 215, baseType: !1520, size: 128, offset: 128)
!1656 = !DISubprogram(name: "pair", scope: !1632, file: !713, line: 303, type: !1657, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1657 = !DISubroutineType(types: !1658)
!1658 = !{null, !1659, !1660}
!1659 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1632, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1660 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1661, size: 64)
!1661 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1632)
!1662 = !DISubprogram(name: "pair", scope: !1632, file: !713, line: 304, type: !1663, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1663 = !DISubroutineType(types: !1664)
!1664 = !{null, !1659, !1665}
!1665 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !1632, size: 64)
!1666 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_EaSERKS2_", scope: !1632, file: !713, line: 378, type: !1667, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1667 = !DISubroutineType(types: !1668)
!1668 = !{!1669, !1659, !1670}
!1669 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1632, size: 64)
!1670 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1671, file: !656, line: 1928, baseType: !1660)
!1671 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<llvm::StringRef, llvm::StringRef> &, const std::__nonesuch_no_braces &>", scope: !91, file: !656, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !1672, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN4llvm9StringRefES2_ERKSt20__nonesuch_no_bracesE")
!1672 = !{!782, !1673, !784}
!1673 = !DITemplateTypeParameter(name: "_Iftrue", type: !1660)
!1674 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_EaSEOS2_", scope: !1632, file: !713, line: 389, type: !1675, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1675 = !DISubroutineType(types: !1676)
!1676 = !{!1669, !1659, !1677}
!1677 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !1678, file: !656, line: 1928, baseType: !1665)
!1678 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<llvm::StringRef, llvm::StringRef> &&, std::__nonesuch_no_braces &&>", scope: !91, file: !656, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !1679, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN4llvm9StringRefES2_EOSt20__nonesuch_no_bracesE")
!1679 = !{!782, !1680, !795}
!1680 = !DITemplateTypeParameter(name: "_Iftrue", type: !1665)
!1681 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN4llvm9StringRefES1_E4swapERS2_", scope: !1632, file: !713, line: 424, type: !1682, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1682 = !DISubroutineType(types: !1683)
!1683 = !{null, !1659, !1669}
!1684 = !{!1685, !1686}
!1685 = !DITemplateTypeParameter(name: "_T1", type: !1520)
!1686 = !DITemplateTypeParameter(name: "_T2", type: !1520)
!1687 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitES0_", scope: !1520, file: !1521, line: 454, type: !1688, scopeLine: 454, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1688 = !DISubroutineType(types: !1689)
!1689 = !{!1632, !1553, !1520}
!1690 = !DISubprogram(name: "split", linkageName: "_ZNK4llvm9StringRef5splitERNS_15SmallVectorImplIS0_EES0_ib", scope: !1520, file: !1521, line: 475, type: !1691, scopeLine: 475, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1691 = !DISubroutineType(types: !1692)
!1692 = !{null, !1553, !1693, !1520, !62, !46}
!1693 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !1694, size: 64)
!1694 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorImpl<llvm::StringRef>", scope: !80, file: !1521, line: 23, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm15SmallVectorImplINS_9StringRefEEE")
!1695 = !DISubprogram(name: "rsplit", linkageName: "_ZNK4llvm9StringRef6rsplitEc", scope: !1520, file: !1521, line: 489, type: !1630, scopeLine: 489, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1696 = !DISubprogram(name: "ltrim", linkageName: "_ZNK4llvm9StringRef5ltrimES0_", scope: !1520, file: !1521, line: 498, type: !1697, scopeLine: 498, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1697 = !DISubroutineType(types: !1698)
!1698 = !{!1520, !1553, !1520}
!1699 = !DISubprogram(name: "rtrim", linkageName: "_ZNK4llvm9StringRef5rtrimES0_", scope: !1520, file: !1521, line: 504, type: !1697, scopeLine: 504, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1700 = !DISubprogram(name: "trim", linkageName: "_ZNK4llvm9StringRef4trimES0_", scope: !1520, file: !1521, line: 510, type: !1697, scopeLine: 510, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1701 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "CharSourceRange", scope: !14, file: !33, line: 225, size: 96, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang15CharSourceRangeE")
!1702 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1703, size: 64)
!1703 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1704)
!1704 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FileEntry", scope: !14, file: !1705, line: 60, size: 512, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang9FileEntryE")
!1705 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/FileManager.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "9a73a4c26400d1f0b8deba18b5ca5818")
!1706 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1707, size: 64)
!1707 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !1708)
!1708 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Module", scope: !14, file: !1709, line: 47, size: 10304, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang6ModuleE")
!1709 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/Module.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "83841d02a13c6ef79f5d1dd8c1163a63")
!1710 = !DISubprogram(name: "Ifdef", linkageName: "_ZN5clang19PreprocessingRecord5IfdefENS_14SourceLocationERKNS_5TokenEPKNS_14MacroDirectiveE", scope: !147, file: !12, line: 574, type: !1711, scopeLine: 574, containingType: !147, virtualIndex: 28, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1711 = !DISubroutineType(types: !1712)
!1712 = !{null, !1348, !36, !1503, !1507}
!1713 = !DISubprogram(name: "Ifndef", linkageName: "_ZN5clang19PreprocessingRecord6IfndefENS_14SourceLocationERKNS_5TokenEPKNS_14MacroDirectiveE", scope: !147, file: !12, line: 576, type: !1711, scopeLine: 576, containingType: !147, virtualIndex: 29, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1714 = !DISubprogram(name: "Defined", linkageName: "_ZN5clang19PreprocessingRecord7DefinedERKNS_5TokenEPKNS_14MacroDirectiveENS_11SourceRangeE", scope: !147, file: !12, line: 579, type: !1715, scopeLine: 579, containingType: !147, virtualIndex: 24, flags: DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!1715 = !DISubroutineType(types: !1716)
!1716 = !{null, !1348, !1503, !1507, !32}
!1717 = !DISubprogram(name: "addMacroExpansion", linkageName: "_ZN5clang19PreprocessingRecord17addMacroExpansionERKNS_5TokenEPKNS_9MacroInfoENS_11SourceRangeE", scope: !147, file: !12, line: 582, type: !1718, scopeLine: 582, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1718 = !DISubroutineType(types: !1719)
!1719 = !{null, !1348, !1503, !734, !32}
!1720 = !DISubprogram(name: "getPreprocessedEntitiesInRangeSlow", linkageName: "_ZN5clang19PreprocessingRecord34getPreprocessedEntitiesInRangeSlowENS_11SourceRangeE", scope: !147, file: !12, line: 592, type: !1721, scopeLine: 592, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1721 = !DISubroutineType(types: !1722)
!1722 = !{!1277, !1348, !32}
!1723 = !DISubprogram(name: "operator new", linkageName: "_ZN5clang18PreprocessedEntitynwEmPv", scope: !20, file: !12, line: 105, type: !1724, scopeLine: 105, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1724 = !DISubroutineType(types: !1725)
!1725 = !{!68, !143, !68}
!1726 = !DISubprogram(name: "operator delete", linkageName: "_ZN5clang18PreprocessedEntitydlEPvRNS_19PreprocessingRecordEj", scope: !20, file: !12, line: 109, type: !1727, scopeLine: 109, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1727 = !DISubroutineType(types: !1728)
!1728 = !{null, !68, !146, !6}
!1729 = !DISubprogram(name: "operator delete", linkageName: "_ZN5clang18PreprocessedEntitydlEPvm", scope: !20, file: !12, line: 114, type: !1730, scopeLine: 114, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1730 = !DISubroutineType(types: !1731)
!1731 = !{null, !68, !224}
!1732 = !DISubprogram(name: "operator delete", linkageName: "_ZN5clang18PreprocessedEntitydlEPvS1_", scope: !20, file: !12, line: 115, type: !1733, scopeLine: 115, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1733 = !DISubroutineType(types: !1734)
!1734 = !{null, !68, !68}
!1735 = !DISubprogram(name: "operator new", linkageName: "_ZN5clang18PreprocessedEntitynwEm", scope: !20, file: !12, line: 119, type: !1736, scopeLine: 119, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1736 = !DISubroutineType(types: !1737)
!1737 = !{!68, !143}
!1738 = !DISubprogram(name: "operator delete", linkageName: "_ZN5clang18PreprocessedEntitydlEPv", scope: !20, file: !12, line: 120, type: !1739, scopeLine: 120, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1739 = !DISubroutineType(types: !1740)
!1740 = !{null, !68}
!1741 = !DISubprogram(name: "PreprocessingDirective", scope: !17, file: !12, line: 126, type: !1742, scopeLine: 126, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1742 = !DISubroutineType(types: !1743)
!1743 = !{null, !1744, !23, !32}
!1744 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !17, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1745 = !DISubprogram(name: "classof", linkageName: "_ZN5clang22PreprocessingDirective7classofEPKNS_18PreprocessedEntityE", scope: !17, file: !12, line: 130, type: !761, scopeLine: 130, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1746 = !DIDerivedType(tag: DW_TAG_member, name: "FileName", scope: !13, file: !12, line: 214, baseType: !1520, size: 128, offset: 128)
!1747 = !DIDerivedType(tag: DW_TAG_member, name: "InQuotes", scope: !13, file: !12, line: 218, baseType: !6, size: 1, offset: 256, flags: DIFlagBitField, extraData: i64 256)
!1748 = !DIDerivedType(tag: DW_TAG_member, name: "Kind", scope: !13, file: !12, line: 223, baseType: !6, size: 2, offset: 257, flags: DIFlagBitField, extraData: i64 256)
!1749 = !DIDerivedType(tag: DW_TAG_member, name: "ImportedModule", scope: !13, file: !12, line: 227, baseType: !6, size: 1, offset: 259, flags: DIFlagBitField, extraData: i64 256)
!1750 = !DIDerivedType(tag: DW_TAG_member, name: "File", scope: !13, file: !12, line: 230, baseType: !1702, size: 64, offset: 320)
!1751 = !DISubprogram(name: "InclusionDirective", scope: !13, file: !12, line: 233, type: !1752, scopeLine: 233, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1752 = !DISubroutineType(types: !1753)
!1753 = !{null, !1754, !146, !11, !1520, !46, !46, !1702, !32}
!1754 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !13, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1755 = !DISubprogram(name: "getKind", linkageName: "_ZNK5clang18InclusionDirective7getKindEv", scope: !13, file: !12, line: 239, type: !1756, scopeLine: 239, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1756 = !DISubroutineType(types: !1757)
!1757 = !{!11, !1758}
!1758 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1759, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!1759 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !13)
!1760 = !DISubprogram(name: "getFileName", linkageName: "_ZNK5clang18InclusionDirective11getFileNameEv", scope: !13, file: !12, line: 242, type: !1761, scopeLine: 242, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1761 = !DISubroutineType(types: !1762)
!1762 = !{!1520, !1758}
!1763 = !DISubprogram(name: "wasInQuotes", linkageName: "_ZNK5clang18InclusionDirective11wasInQuotesEv", scope: !13, file: !12, line: 246, type: !1764, scopeLine: 246, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1764 = !DISubroutineType(types: !1765)
!1765 = !{!46, !1758}
!1766 = !DISubprogram(name: "importedModule", linkageName: "_ZNK5clang18InclusionDirective14importedModuleEv", scope: !13, file: !12, line: 250, type: !1764, scopeLine: 250, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1767 = !DISubprogram(name: "getFile", linkageName: "_ZNK5clang18InclusionDirective7getFileEv", scope: !13, file: !12, line: 254, type: !1768, scopeLine: 254, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!1768 = !DISubroutineType(types: !1769)
!1769 = !{!1702, !1758}
!1770 = !DISubprogram(name: "classof", linkageName: "_ZN5clang18InclusionDirective7classofEPKNS_18PreprocessedEntityE", scope: !13, file: !12, line: 257, type: !761, scopeLine: 257, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!1771 = !{!1772, !1773, !1774, !1775}
!1772 = !DIEnumerator(name: "Include", value: 0, isUnsigned: true)
!1773 = !DIEnumerator(name: "Import", value: 1, isUnsigned: true)
!1774 = !DIEnumerator(name: "IncludeNext", value: 2, isUnsigned: true)
!1775 = !DIEnumerator(name: "IncludeMacros", value: 3, isUnsigned: true)
!1776 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !36, file: !33, line: 92, baseType: !6, size: 32, elements: !1777, identifier: "_ZTSN5clang14SourceLocationUt_E")
!1777 = !{!1778}
!1778 = !DIEnumerator(name: "MacroIDBit", value: 2147483648, isUnsigned: true)
!1779 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "CharacteristicKind", scope: !1780, file: !84, line: 77, baseType: !6, size: 32, elements: !1781, identifier: "_ZTSN5clang6SrcMgr18CharacteristicKindE")
!1780 = !DINamespace(name: "SrcMgr", scope: !14)
!1781 = !{!1782, !1783, !1784}
!1782 = !DIEnumerator(name: "C_User", value: 0, isUnsigned: true)
!1783 = !DIEnumerator(name: "C_System", value: 1, isUnsigned: true)
!1784 = !DIEnumerator(name: "C_ExternCSystem", value: 2, isUnsigned: true)
!1785 = !DICompositeType(tag: DW_TAG_enumeration_type, scope: !91, file: !1786, line: 70, baseType: !6, size: 32, elements: !1787)
!1786 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_bvector.h", directory: "", checksumkind: CSK_MD5, checksum: "543595f245ff5dae7fc0594cdc71787c")
!1787 = !{!1788}
!1788 = !DIEnumerator(name: "_S_word_bit", value: 64, isUnsigned: true)
!1789 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "TokenKind", scope: !1791, file: !1790, line: 23, baseType: !6, size: 32, elements: !1792, identifier: "_ZTSN5clang3tok9TokenKindE")
!1790 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/TokenKinds.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "7eb12cb2b6682ea1941c3102d162293e")
!1791 = !DINamespace(name: "tok", scope: !14)
!1792 = !{!1793, !1794, !1795, !1796, !1797, !1798, !1799, !1800, !1801, !1802, !1803, !1804, !1805, !1806, !1807, !1808, !1809, !1810, !1811, !1812, !1813, !1814, !1815, !1816, !1817, !1818, !1819, !1820, !1821, !1822, !1823, !1824, !1825, !1826, !1827, !1828, !1829, !1830, !1831, !1832, !1833, !1834, !1835, !1836, !1837, !1838, !1839, !1840, !1841, !1842, !1843, !1844, !1845, !1846, !1847, !1848, !1849, !1850, !1851, !1852, !1853, !1854, !1855, !1856, !1857, !1858, !1859, !1860, !1861, !1862, !1863, !1864, !1865, !1866, !1867, !1868, !1869, !1870, !1871, !1872, !1873, !1874, !1875, !1876, !1877, !1878, !1879, !1880, !1881, !1882, !1883, !1884, !1885, !1886, !1887, !1888, !1889, !1890, !1891, !1892, !1893, !1894, !1895, !1896, !1897, !1898, !1899, !1900, !1901, !1902, !1903, !1904, !1905, !1906, !1907, !1908, !1909, !1910, !1911, !1912, !1913, !1914, !1915, !1916, !1917, !1918, !1919, !1920, !1921, !1922, !1923, !1924, !1925, !1926, !1927, !1928, !1929, !1930, !1931, !1932, !1933, !1934, !1935, !1936, !1937, !1938, !1939, !1940, !1941, !1942, !1943, !1944, !1945, !1946, !1947, !1948, !1949, !1950, !1951, !1952, !1953, !1954, !1955, !1956, !1957, !1958, !1959, !1960, !1961, !1962, !1963, !1964, !1965, !1966, !1967, !1968, !1969, !1970, !1971, !1972, !1973, !1974, !1975, !1976, !1977, !1978, !1979, !1980, !1981, !1982, !1983, !1984, !1985, !1986, !1987, !1988, !1989, !1990, !1991, !1992, !1993, !1994, !1995, !1996, !1997, !1998, !1999, !2000, !2001, !2002, !2003, !2004, !2005, !2006, !2007, !2008, !2009, !2010, !2011, !2012, !2013, !2014, !2015, !2016, !2017, !2018, !2019, !2020, !2021, !2022, !2023, !2024, !2025, !2026, !2027, !2028, !2029, !2030, !2031, !2032, !2033, !2034, !2035, !2036, !2037, !2038, !2039, !2040, !2041, !2042, !2043, !2044, !2045, !2046, !2047, !2048, !2049, !2050, !2051, !2052, !2053, !2054, !2055, !2056, !2057, !2058, !2059, !2060, !2061, !2062, !2063, !2064, !2065, !2066, !2067, !2068, !2069, !2070, !2071, !2072, !2073, !2074, !2075, !2076, !2077, !2078, !2079, !2080, !2081, !2082, !2083, !2084, !2085, !2086, !2087, !2088, !2089, !2090, !2091, !2092, !2093, !2094, !2095, !2096, !2097, !2098, !2099, !2100, !2101, !2102, !2103, !2104, !2105, !2106, !2107}
!1793 = !DIEnumerator(name: "unknown", value: 0, isUnsigned: true)
!1794 = !DIEnumerator(name: "eof", value: 1, isUnsigned: true)
!1795 = !DIEnumerator(name: "eod", value: 2, isUnsigned: true)
!1796 = !DIEnumerator(name: "code_completion", value: 3, isUnsigned: true)
!1797 = !DIEnumerator(name: "cxx_defaultarg_end", value: 4, isUnsigned: true)
!1798 = !DIEnumerator(name: "comment", value: 5, isUnsigned: true)
!1799 = !DIEnumerator(name: "identifier", value: 6, isUnsigned: true)
!1800 = !DIEnumerator(name: "raw_identifier", value: 7, isUnsigned: true)
!1801 = !DIEnumerator(name: "numeric_constant", value: 8, isUnsigned: true)
!1802 = !DIEnumerator(name: "char_constant", value: 9, isUnsigned: true)
!1803 = !DIEnumerator(name: "wide_char_constant", value: 10, isUnsigned: true)
!1804 = !DIEnumerator(name: "utf16_char_constant", value: 11, isUnsigned: true)
!1805 = !DIEnumerator(name: "utf32_char_constant", value: 12, isUnsigned: true)
!1806 = !DIEnumerator(name: "string_literal", value: 13, isUnsigned: true)
!1807 = !DIEnumerator(name: "wide_string_literal", value: 14, isUnsigned: true)
!1808 = !DIEnumerator(name: "angle_string_literal", value: 15, isUnsigned: true)
!1809 = !DIEnumerator(name: "utf8_string_literal", value: 16, isUnsigned: true)
!1810 = !DIEnumerator(name: "utf16_string_literal", value: 17, isUnsigned: true)
!1811 = !DIEnumerator(name: "utf32_string_literal", value: 18, isUnsigned: true)
!1812 = !DIEnumerator(name: "l_square", value: 19, isUnsigned: true)
!1813 = !DIEnumerator(name: "r_square", value: 20, isUnsigned: true)
!1814 = !DIEnumerator(name: "l_paren", value: 21, isUnsigned: true)
!1815 = !DIEnumerator(name: "r_paren", value: 22, isUnsigned: true)
!1816 = !DIEnumerator(name: "l_brace", value: 23, isUnsigned: true)
!1817 = !DIEnumerator(name: "r_brace", value: 24, isUnsigned: true)
!1818 = !DIEnumerator(name: "period", value: 25, isUnsigned: true)
!1819 = !DIEnumerator(name: "ellipsis", value: 26, isUnsigned: true)
!1820 = !DIEnumerator(name: "amp", value: 27, isUnsigned: true)
!1821 = !DIEnumerator(name: "ampamp", value: 28, isUnsigned: true)
!1822 = !DIEnumerator(name: "ampequal", value: 29, isUnsigned: true)
!1823 = !DIEnumerator(name: "star", value: 30, isUnsigned: true)
!1824 = !DIEnumerator(name: "starequal", value: 31, isUnsigned: true)
!1825 = !DIEnumerator(name: "plus", value: 32, isUnsigned: true)
!1826 = !DIEnumerator(name: "plusplus", value: 33, isUnsigned: true)
!1827 = !DIEnumerator(name: "plusequal", value: 34, isUnsigned: true)
!1828 = !DIEnumerator(name: "minus", value: 35, isUnsigned: true)
!1829 = !DIEnumerator(name: "arrow", value: 36, isUnsigned: true)
!1830 = !DIEnumerator(name: "minusminus", value: 37, isUnsigned: true)
!1831 = !DIEnumerator(name: "minusequal", value: 38, isUnsigned: true)
!1832 = !DIEnumerator(name: "tilde", value: 39, isUnsigned: true)
!1833 = !DIEnumerator(name: "exclaim", value: 40, isUnsigned: true)
!1834 = !DIEnumerator(name: "exclaimequal", value: 41, isUnsigned: true)
!1835 = !DIEnumerator(name: "slash", value: 42, isUnsigned: true)
!1836 = !DIEnumerator(name: "slashequal", value: 43, isUnsigned: true)
!1837 = !DIEnumerator(name: "percent", value: 44, isUnsigned: true)
!1838 = !DIEnumerator(name: "percentequal", value: 45, isUnsigned: true)
!1839 = !DIEnumerator(name: "less", value: 46, isUnsigned: true)
!1840 = !DIEnumerator(name: "lessless", value: 47, isUnsigned: true)
!1841 = !DIEnumerator(name: "lessequal", value: 48, isUnsigned: true)
!1842 = !DIEnumerator(name: "lesslessequal", value: 49, isUnsigned: true)
!1843 = !DIEnumerator(name: "greater", value: 50, isUnsigned: true)
!1844 = !DIEnumerator(name: "greatergreater", value: 51, isUnsigned: true)
!1845 = !DIEnumerator(name: "greaterequal", value: 52, isUnsigned: true)
!1846 = !DIEnumerator(name: "greatergreaterequal", value: 53, isUnsigned: true)
!1847 = !DIEnumerator(name: "caret", value: 54, isUnsigned: true)
!1848 = !DIEnumerator(name: "caretequal", value: 55, isUnsigned: true)
!1849 = !DIEnumerator(name: "pipe", value: 56, isUnsigned: true)
!1850 = !DIEnumerator(name: "pipepipe", value: 57, isUnsigned: true)
!1851 = !DIEnumerator(name: "pipeequal", value: 58, isUnsigned: true)
!1852 = !DIEnumerator(name: "question", value: 59, isUnsigned: true)
!1853 = !DIEnumerator(name: "colon", value: 60, isUnsigned: true)
!1854 = !DIEnumerator(name: "semi", value: 61, isUnsigned: true)
!1855 = !DIEnumerator(name: "equal", value: 62, isUnsigned: true)
!1856 = !DIEnumerator(name: "equalequal", value: 63, isUnsigned: true)
!1857 = !DIEnumerator(name: "comma", value: 64, isUnsigned: true)
!1858 = !DIEnumerator(name: "hash", value: 65, isUnsigned: true)
!1859 = !DIEnumerator(name: "hashhash", value: 66, isUnsigned: true)
!1860 = !DIEnumerator(name: "hashat", value: 67, isUnsigned: true)
!1861 = !DIEnumerator(name: "periodstar", value: 68, isUnsigned: true)
!1862 = !DIEnumerator(name: "arrowstar", value: 69, isUnsigned: true)
!1863 = !DIEnumerator(name: "coloncolon", value: 70, isUnsigned: true)
!1864 = !DIEnumerator(name: "at", value: 71, isUnsigned: true)
!1865 = !DIEnumerator(name: "lesslessless", value: 72, isUnsigned: true)
!1866 = !DIEnumerator(name: "greatergreatergreater", value: 73, isUnsigned: true)
!1867 = !DIEnumerator(name: "kw_auto", value: 74, isUnsigned: true)
!1868 = !DIEnumerator(name: "kw_break", value: 75, isUnsigned: true)
!1869 = !DIEnumerator(name: "kw_case", value: 76, isUnsigned: true)
!1870 = !DIEnumerator(name: "kw_char", value: 77, isUnsigned: true)
!1871 = !DIEnumerator(name: "kw_const", value: 78, isUnsigned: true)
!1872 = !DIEnumerator(name: "kw_continue", value: 79, isUnsigned: true)
!1873 = !DIEnumerator(name: "kw_default", value: 80, isUnsigned: true)
!1874 = !DIEnumerator(name: "kw_do", value: 81, isUnsigned: true)
!1875 = !DIEnumerator(name: "kw_double", value: 82, isUnsigned: true)
!1876 = !DIEnumerator(name: "kw_else", value: 83, isUnsigned: true)
!1877 = !DIEnumerator(name: "kw_enum", value: 84, isUnsigned: true)
!1878 = !DIEnumerator(name: "kw_extern", value: 85, isUnsigned: true)
!1879 = !DIEnumerator(name: "kw_float", value: 86, isUnsigned: true)
!1880 = !DIEnumerator(name: "kw_for", value: 87, isUnsigned: true)
!1881 = !DIEnumerator(name: "kw_goto", value: 88, isUnsigned: true)
!1882 = !DIEnumerator(name: "kw_if", value: 89, isUnsigned: true)
!1883 = !DIEnumerator(name: "kw_inline", value: 90, isUnsigned: true)
!1884 = !DIEnumerator(name: "kw_int", value: 91, isUnsigned: true)
!1885 = !DIEnumerator(name: "kw_long", value: 92, isUnsigned: true)
!1886 = !DIEnumerator(name: "kw_register", value: 93, isUnsigned: true)
!1887 = !DIEnumerator(name: "kw_restrict", value: 94, isUnsigned: true)
!1888 = !DIEnumerator(name: "kw_return", value: 95, isUnsigned: true)
!1889 = !DIEnumerator(name: "kw_short", value: 96, isUnsigned: true)
!1890 = !DIEnumerator(name: "kw_signed", value: 97, isUnsigned: true)
!1891 = !DIEnumerator(name: "kw_sizeof", value: 98, isUnsigned: true)
!1892 = !DIEnumerator(name: "kw_static", value: 99, isUnsigned: true)
!1893 = !DIEnumerator(name: "kw_struct", value: 100, isUnsigned: true)
!1894 = !DIEnumerator(name: "kw_switch", value: 101, isUnsigned: true)
!1895 = !DIEnumerator(name: "kw_typedef", value: 102, isUnsigned: true)
!1896 = !DIEnumerator(name: "kw_union", value: 103, isUnsigned: true)
!1897 = !DIEnumerator(name: "kw_unsigned", value: 104, isUnsigned: true)
!1898 = !DIEnumerator(name: "kw_void", value: 105, isUnsigned: true)
!1899 = !DIEnumerator(name: "kw_volatile", value: 106, isUnsigned: true)
!1900 = !DIEnumerator(name: "kw_while", value: 107, isUnsigned: true)
!1901 = !DIEnumerator(name: "kw__Alignas", value: 108, isUnsigned: true)
!1902 = !DIEnumerator(name: "kw__Alignof", value: 109, isUnsigned: true)
!1903 = !DIEnumerator(name: "kw__Atomic", value: 110, isUnsigned: true)
!1904 = !DIEnumerator(name: "kw__Bool", value: 111, isUnsigned: true)
!1905 = !DIEnumerator(name: "kw__Complex", value: 112, isUnsigned: true)
!1906 = !DIEnumerator(name: "kw__Generic", value: 113, isUnsigned: true)
!1907 = !DIEnumerator(name: "kw__Imaginary", value: 114, isUnsigned: true)
!1908 = !DIEnumerator(name: "kw__Noreturn", value: 115, isUnsigned: true)
!1909 = !DIEnumerator(name: "kw__Static_assert", value: 116, isUnsigned: true)
!1910 = !DIEnumerator(name: "kw__Thread_local", value: 117, isUnsigned: true)
!1911 = !DIEnumerator(name: "kw___func__", value: 118, isUnsigned: true)
!1912 = !DIEnumerator(name: "kw___objc_yes", value: 119, isUnsigned: true)
!1913 = !DIEnumerator(name: "kw___objc_no", value: 120, isUnsigned: true)
!1914 = !DIEnumerator(name: "kw_asm", value: 121, isUnsigned: true)
!1915 = !DIEnumerator(name: "kw_bool", value: 122, isUnsigned: true)
!1916 = !DIEnumerator(name: "kw_catch", value: 123, isUnsigned: true)
!1917 = !DIEnumerator(name: "kw_class", value: 124, isUnsigned: true)
!1918 = !DIEnumerator(name: "kw_const_cast", value: 125, isUnsigned: true)
!1919 = !DIEnumerator(name: "kw_delete", value: 126, isUnsigned: true)
!1920 = !DIEnumerator(name: "kw_dynamic_cast", value: 127, isUnsigned: true)
!1921 = !DIEnumerator(name: "kw_explicit", value: 128, isUnsigned: true)
!1922 = !DIEnumerator(name: "kw_export", value: 129, isUnsigned: true)
!1923 = !DIEnumerator(name: "kw_false", value: 130, isUnsigned: true)
!1924 = !DIEnumerator(name: "kw_friend", value: 131, isUnsigned: true)
!1925 = !DIEnumerator(name: "kw_mutable", value: 132, isUnsigned: true)
!1926 = !DIEnumerator(name: "kw_namespace", value: 133, isUnsigned: true)
!1927 = !DIEnumerator(name: "kw_new", value: 134, isUnsigned: true)
!1928 = !DIEnumerator(name: "kw_operator", value: 135, isUnsigned: true)
!1929 = !DIEnumerator(name: "kw_private", value: 136, isUnsigned: true)
!1930 = !DIEnumerator(name: "kw_protected", value: 137, isUnsigned: true)
!1931 = !DIEnumerator(name: "kw_public", value: 138, isUnsigned: true)
!1932 = !DIEnumerator(name: "kw_reinterpret_cast", value: 139, isUnsigned: true)
!1933 = !DIEnumerator(name: "kw_static_cast", value: 140, isUnsigned: true)
!1934 = !DIEnumerator(name: "kw_template", value: 141, isUnsigned: true)
!1935 = !DIEnumerator(name: "kw_this", value: 142, isUnsigned: true)
!1936 = !DIEnumerator(name: "kw_throw", value: 143, isUnsigned: true)
!1937 = !DIEnumerator(name: "kw_true", value: 144, isUnsigned: true)
!1938 = !DIEnumerator(name: "kw_try", value: 145, isUnsigned: true)
!1939 = !DIEnumerator(name: "kw_typename", value: 146, isUnsigned: true)
!1940 = !DIEnumerator(name: "kw_typeid", value: 147, isUnsigned: true)
!1941 = !DIEnumerator(name: "kw_using", value: 148, isUnsigned: true)
!1942 = !DIEnumerator(name: "kw_virtual", value: 149, isUnsigned: true)
!1943 = !DIEnumerator(name: "kw_wchar_t", value: 150, isUnsigned: true)
!1944 = !DIEnumerator(name: "kw_alignas", value: 151, isUnsigned: true)
!1945 = !DIEnumerator(name: "kw_alignof", value: 152, isUnsigned: true)
!1946 = !DIEnumerator(name: "kw_char16_t", value: 153, isUnsigned: true)
!1947 = !DIEnumerator(name: "kw_char32_t", value: 154, isUnsigned: true)
!1948 = !DIEnumerator(name: "kw_constexpr", value: 155, isUnsigned: true)
!1949 = !DIEnumerator(name: "kw_decltype", value: 156, isUnsigned: true)
!1950 = !DIEnumerator(name: "kw_noexcept", value: 157, isUnsigned: true)
!1951 = !DIEnumerator(name: "kw_nullptr", value: 158, isUnsigned: true)
!1952 = !DIEnumerator(name: "kw_static_assert", value: 159, isUnsigned: true)
!1953 = !DIEnumerator(name: "kw_thread_local", value: 160, isUnsigned: true)
!1954 = !DIEnumerator(name: "kw__Decimal32", value: 161, isUnsigned: true)
!1955 = !DIEnumerator(name: "kw__Decimal64", value: 162, isUnsigned: true)
!1956 = !DIEnumerator(name: "kw__Decimal128", value: 163, isUnsigned: true)
!1957 = !DIEnumerator(name: "kw___null", value: 164, isUnsigned: true)
!1958 = !DIEnumerator(name: "kw___alignof", value: 165, isUnsigned: true)
!1959 = !DIEnumerator(name: "kw___attribute", value: 166, isUnsigned: true)
!1960 = !DIEnumerator(name: "kw___builtin_choose_expr", value: 167, isUnsigned: true)
!1961 = !DIEnumerator(name: "kw___builtin_offsetof", value: 168, isUnsigned: true)
!1962 = !DIEnumerator(name: "kw___builtin_types_compatible_p", value: 169, isUnsigned: true)
!1963 = !DIEnumerator(name: "kw___builtin_va_arg", value: 170, isUnsigned: true)
!1964 = !DIEnumerator(name: "kw___extension__", value: 171, isUnsigned: true)
!1965 = !DIEnumerator(name: "kw___imag", value: 172, isUnsigned: true)
!1966 = !DIEnumerator(name: "kw___int128", value: 173, isUnsigned: true)
!1967 = !DIEnumerator(name: "kw___label__", value: 174, isUnsigned: true)
!1968 = !DIEnumerator(name: "kw___real", value: 175, isUnsigned: true)
!1969 = !DIEnumerator(name: "kw___thread", value: 176, isUnsigned: true)
!1970 = !DIEnumerator(name: "kw___FUNCTION__", value: 177, isUnsigned: true)
!1971 = !DIEnumerator(name: "kw___PRETTY_FUNCTION__", value: 178, isUnsigned: true)
!1972 = !DIEnumerator(name: "kw_typeof", value: 179, isUnsigned: true)
!1973 = !DIEnumerator(name: "kw___FUNCDNAME__", value: 180, isUnsigned: true)
!1974 = !DIEnumerator(name: "kw_L__FUNCTION__", value: 181, isUnsigned: true)
!1975 = !DIEnumerator(name: "kw___is_interface_class", value: 182, isUnsigned: true)
!1976 = !DIEnumerator(name: "kw___is_sealed", value: 183, isUnsigned: true)
!1977 = !DIEnumerator(name: "kw___has_nothrow_assign", value: 184, isUnsigned: true)
!1978 = !DIEnumerator(name: "kw___has_nothrow_move_assign", value: 185, isUnsigned: true)
!1979 = !DIEnumerator(name: "kw___has_nothrow_copy", value: 186, isUnsigned: true)
!1980 = !DIEnumerator(name: "kw___has_nothrow_constructor", value: 187, isUnsigned: true)
!1981 = !DIEnumerator(name: "kw___has_trivial_assign", value: 188, isUnsigned: true)
!1982 = !DIEnumerator(name: "kw___has_trivial_move_assign", value: 189, isUnsigned: true)
!1983 = !DIEnumerator(name: "kw___has_trivial_copy", value: 190, isUnsigned: true)
!1984 = !DIEnumerator(name: "kw___has_trivial_constructor", value: 191, isUnsigned: true)
!1985 = !DIEnumerator(name: "kw___has_trivial_move_constructor", value: 192, isUnsigned: true)
!1986 = !DIEnumerator(name: "kw___has_trivial_destructor", value: 193, isUnsigned: true)
!1987 = !DIEnumerator(name: "kw___has_virtual_destructor", value: 194, isUnsigned: true)
!1988 = !DIEnumerator(name: "kw___is_abstract", value: 195, isUnsigned: true)
!1989 = !DIEnumerator(name: "kw___is_base_of", value: 196, isUnsigned: true)
!1990 = !DIEnumerator(name: "kw___is_class", value: 197, isUnsigned: true)
!1991 = !DIEnumerator(name: "kw___is_convertible_to", value: 198, isUnsigned: true)
!1992 = !DIEnumerator(name: "kw___is_empty", value: 199, isUnsigned: true)
!1993 = !DIEnumerator(name: "kw___is_enum", value: 200, isUnsigned: true)
!1994 = !DIEnumerator(name: "kw___is_final", value: 201, isUnsigned: true)
!1995 = !DIEnumerator(name: "kw___is_literal", value: 202, isUnsigned: true)
!1996 = !DIEnumerator(name: "kw___is_literal_type", value: 203, isUnsigned: true)
!1997 = !DIEnumerator(name: "kw___is_pod", value: 204, isUnsigned: true)
!1998 = !DIEnumerator(name: "kw___is_polymorphic", value: 205, isUnsigned: true)
!1999 = !DIEnumerator(name: "kw___is_trivial", value: 206, isUnsigned: true)
!2000 = !DIEnumerator(name: "kw___is_union", value: 207, isUnsigned: true)
!2001 = !DIEnumerator(name: "kw___is_trivially_constructible", value: 208, isUnsigned: true)
!2002 = !DIEnumerator(name: "kw___is_trivially_copyable", value: 209, isUnsigned: true)
!2003 = !DIEnumerator(name: "kw___is_trivially_assignable", value: 210, isUnsigned: true)
!2004 = !DIEnumerator(name: "kw___underlying_type", value: 211, isUnsigned: true)
!2005 = !DIEnumerator(name: "kw___is_lvalue_expr", value: 212, isUnsigned: true)
!2006 = !DIEnumerator(name: "kw___is_rvalue_expr", value: 213, isUnsigned: true)
!2007 = !DIEnumerator(name: "kw___is_arithmetic", value: 214, isUnsigned: true)
!2008 = !DIEnumerator(name: "kw___is_floating_point", value: 215, isUnsigned: true)
!2009 = !DIEnumerator(name: "kw___is_integral", value: 216, isUnsigned: true)
!2010 = !DIEnumerator(name: "kw___is_complete_type", value: 217, isUnsigned: true)
!2011 = !DIEnumerator(name: "kw___is_void", value: 218, isUnsigned: true)
!2012 = !DIEnumerator(name: "kw___is_array", value: 219, isUnsigned: true)
!2013 = !DIEnumerator(name: "kw___is_function", value: 220, isUnsigned: true)
!2014 = !DIEnumerator(name: "kw___is_reference", value: 221, isUnsigned: true)
!2015 = !DIEnumerator(name: "kw___is_lvalue_reference", value: 222, isUnsigned: true)
!2016 = !DIEnumerator(name: "kw___is_rvalue_reference", value: 223, isUnsigned: true)
!2017 = !DIEnumerator(name: "kw___is_fundamental", value: 224, isUnsigned: true)
!2018 = !DIEnumerator(name: "kw___is_object", value: 225, isUnsigned: true)
!2019 = !DIEnumerator(name: "kw___is_scalar", value: 226, isUnsigned: true)
!2020 = !DIEnumerator(name: "kw___is_compound", value: 227, isUnsigned: true)
!2021 = !DIEnumerator(name: "kw___is_pointer", value: 228, isUnsigned: true)
!2022 = !DIEnumerator(name: "kw___is_member_object_pointer", value: 229, isUnsigned: true)
!2023 = !DIEnumerator(name: "kw___is_member_function_pointer", value: 230, isUnsigned: true)
!2024 = !DIEnumerator(name: "kw___is_member_pointer", value: 231, isUnsigned: true)
!2025 = !DIEnumerator(name: "kw___is_const", value: 232, isUnsigned: true)
!2026 = !DIEnumerator(name: "kw___is_volatile", value: 233, isUnsigned: true)
!2027 = !DIEnumerator(name: "kw___is_standard_layout", value: 234, isUnsigned: true)
!2028 = !DIEnumerator(name: "kw___is_signed", value: 235, isUnsigned: true)
!2029 = !DIEnumerator(name: "kw___is_unsigned", value: 236, isUnsigned: true)
!2030 = !DIEnumerator(name: "kw___is_same", value: 237, isUnsigned: true)
!2031 = !DIEnumerator(name: "kw___is_convertible", value: 238, isUnsigned: true)
!2032 = !DIEnumerator(name: "kw___array_rank", value: 239, isUnsigned: true)
!2033 = !DIEnumerator(name: "kw___array_extent", value: 240, isUnsigned: true)
!2034 = !DIEnumerator(name: "kw___private_extern__", value: 241, isUnsigned: true)
!2035 = !DIEnumerator(name: "kw___module_private__", value: 242, isUnsigned: true)
!2036 = !DIEnumerator(name: "kw___declspec", value: 243, isUnsigned: true)
!2037 = !DIEnumerator(name: "kw___cdecl", value: 244, isUnsigned: true)
!2038 = !DIEnumerator(name: "kw___stdcall", value: 245, isUnsigned: true)
!2039 = !DIEnumerator(name: "kw___fastcall", value: 246, isUnsigned: true)
!2040 = !DIEnumerator(name: "kw___thiscall", value: 247, isUnsigned: true)
!2041 = !DIEnumerator(name: "kw___forceinline", value: 248, isUnsigned: true)
!2042 = !DIEnumerator(name: "kw___unaligned", value: 249, isUnsigned: true)
!2043 = !DIEnumerator(name: "kw___kernel", value: 250, isUnsigned: true)
!2044 = !DIEnumerator(name: "kw_vec_step", value: 251, isUnsigned: true)
!2045 = !DIEnumerator(name: "kw___private", value: 252, isUnsigned: true)
!2046 = !DIEnumerator(name: "kw___global", value: 253, isUnsigned: true)
!2047 = !DIEnumerator(name: "kw___local", value: 254, isUnsigned: true)
!2048 = !DIEnumerator(name: "kw___constant", value: 255, isUnsigned: true)
!2049 = !DIEnumerator(name: "kw___read_only", value: 256, isUnsigned: true)
!2050 = !DIEnumerator(name: "kw___write_only", value: 257, isUnsigned: true)
!2051 = !DIEnumerator(name: "kw___read_write", value: 258, isUnsigned: true)
!2052 = !DIEnumerator(name: "kw___builtin_astype", value: 259, isUnsigned: true)
!2053 = !DIEnumerator(name: "kw_image1d_t", value: 260, isUnsigned: true)
!2054 = !DIEnumerator(name: "kw_image1d_array_t", value: 261, isUnsigned: true)
!2055 = !DIEnumerator(name: "kw_image1d_buffer_t", value: 262, isUnsigned: true)
!2056 = !DIEnumerator(name: "kw_image2d_t", value: 263, isUnsigned: true)
!2057 = !DIEnumerator(name: "kw_image2d_array_t", value: 264, isUnsigned: true)
!2058 = !DIEnumerator(name: "kw_image3d_t", value: 265, isUnsigned: true)
!2059 = !DIEnumerator(name: "kw_sampler_t", value: 266, isUnsigned: true)
!2060 = !DIEnumerator(name: "kw_event_t", value: 267, isUnsigned: true)
!2061 = !DIEnumerator(name: "kw___pascal", value: 268, isUnsigned: true)
!2062 = !DIEnumerator(name: "kw___vector", value: 269, isUnsigned: true)
!2063 = !DIEnumerator(name: "kw___pixel", value: 270, isUnsigned: true)
!2064 = !DIEnumerator(name: "kw_half", value: 271, isUnsigned: true)
!2065 = !DIEnumerator(name: "kw___bridge", value: 272, isUnsigned: true)
!2066 = !DIEnumerator(name: "kw___bridge_transfer", value: 273, isUnsigned: true)
!2067 = !DIEnumerator(name: "kw___bridge_retained", value: 274, isUnsigned: true)
!2068 = !DIEnumerator(name: "kw___bridge_retain", value: 275, isUnsigned: true)
!2069 = !DIEnumerator(name: "kw___ptr64", value: 276, isUnsigned: true)
!2070 = !DIEnumerator(name: "kw___ptr32", value: 277, isUnsigned: true)
!2071 = !DIEnumerator(name: "kw___sptr", value: 278, isUnsigned: true)
!2072 = !DIEnumerator(name: "kw___uptr", value: 279, isUnsigned: true)
!2073 = !DIEnumerator(name: "kw___w64", value: 280, isUnsigned: true)
!2074 = !DIEnumerator(name: "kw___uuidof", value: 281, isUnsigned: true)
!2075 = !DIEnumerator(name: "kw___try", value: 282, isUnsigned: true)
!2076 = !DIEnumerator(name: "kw___finally", value: 283, isUnsigned: true)
!2077 = !DIEnumerator(name: "kw___leave", value: 284, isUnsigned: true)
!2078 = !DIEnumerator(name: "kw___int64", value: 285, isUnsigned: true)
!2079 = !DIEnumerator(name: "kw___if_exists", value: 286, isUnsigned: true)
!2080 = !DIEnumerator(name: "kw___if_not_exists", value: 287, isUnsigned: true)
!2081 = !DIEnumerator(name: "kw___single_inheritance", value: 288, isUnsigned: true)
!2082 = !DIEnumerator(name: "kw___multiple_inheritance", value: 289, isUnsigned: true)
!2083 = !DIEnumerator(name: "kw___virtual_inheritance", value: 290, isUnsigned: true)
!2084 = !DIEnumerator(name: "kw___interface", value: 291, isUnsigned: true)
!2085 = !DIEnumerator(name: "kw___builtin_convertvector", value: 292, isUnsigned: true)
!2086 = !DIEnumerator(name: "kw___unknown_anytype", value: 293, isUnsigned: true)
!2087 = !DIEnumerator(name: "annot_cxxscope", value: 294, isUnsigned: true)
!2088 = !DIEnumerator(name: "annot_typename", value: 295, isUnsigned: true)
!2089 = !DIEnumerator(name: "annot_template_id", value: 296, isUnsigned: true)
!2090 = !DIEnumerator(name: "annot_primary_expr", value: 297, isUnsigned: true)
!2091 = !DIEnumerator(name: "annot_decltype", value: 298, isUnsigned: true)
!2092 = !DIEnumerator(name: "annot_pragma_unused", value: 299, isUnsigned: true)
!2093 = !DIEnumerator(name: "annot_pragma_vis", value: 300, isUnsigned: true)
!2094 = !DIEnumerator(name: "annot_pragma_pack", value: 301, isUnsigned: true)
!2095 = !DIEnumerator(name: "annot_pragma_parser_crash", value: 302, isUnsigned: true)
!2096 = !DIEnumerator(name: "annot_pragma_captured", value: 303, isUnsigned: true)
!2097 = !DIEnumerator(name: "annot_pragma_msstruct", value: 304, isUnsigned: true)
!2098 = !DIEnumerator(name: "annot_pragma_align", value: 305, isUnsigned: true)
!2099 = !DIEnumerator(name: "annot_pragma_weak", value: 306, isUnsigned: true)
!2100 = !DIEnumerator(name: "annot_pragma_weakalias", value: 307, isUnsigned: true)
!2101 = !DIEnumerator(name: "annot_pragma_redefine_extname", value: 308, isUnsigned: true)
!2102 = !DIEnumerator(name: "annot_pragma_fp_contract", value: 309, isUnsigned: true)
!2103 = !DIEnumerator(name: "annot_pragma_opencl_extension", value: 310, isUnsigned: true)
!2104 = !DIEnumerator(name: "annot_pragma_openmp", value: 311, isUnsigned: true)
!2105 = !DIEnumerator(name: "annot_pragma_openmp_end", value: 312, isUnsigned: true)
!2106 = !DIEnumerator(name: "annot_module_include", value: 313, isUnsigned: true)
!2107 = !DIEnumerator(name: "NUM_TOKENS", value: 314, isUnsigned: true)
!2108 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !2110, file: !2109, line: 57, baseType: !6, size: 32, elements: !2120, identifier: "_ZTSN4llvm22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS1_15MacroDefinitionEEUt_E")
!2109 = !DIFile(filename: "llvm34/include/llvm/ADT/PointerUnion.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "fc2fa3fd44f400d393cc7a45e1be774f")
!2110 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerUnionUIntTraits<clang::IdentifierInfo *, clang::MacroDefinition *>", scope: !80, file: !2109, line: 53, size: 8, flags: DIFlagTypePassByValue, elements: !2111, templateParams: !2116, identifier: "_ZTSN4llvm22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS1_15MacroDefinitionEEE")
!2111 = !{!2112, !2115}
!2112 = !DISubprogram(name: "getAsVoidPointer", linkageName: "_ZN4llvm22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS1_15MacroDefinitionEE16getAsVoidPointerEPv", scope: !2110, file: !2109, line: 55, type: !2113, scopeLine: 55, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2113 = !DISubroutineType(types: !2114)
!2114 = !{!68, !68}
!2115 = !DISubprogram(name: "getFromVoidPointer", linkageName: "_ZN4llvm22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS1_15MacroDefinitionEE18getFromVoidPointerEPv", scope: !2110, file: !2109, line: 56, type: !2113, scopeLine: 56, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2116 = !{!2117, !2119}
!2117 = !DITemplateTypeParameter(name: "PT1", type: !2118)
!2118 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !746, size: 64)
!2119 = !DITemplateTypeParameter(name: "PT2", type: !739)
!2120 = !{!2121, !2122, !2123}
!2121 = !DIEnumerator(name: "PT1BitsAv", value: 1, isUnsigned: true)
!2122 = !DIEnumerator(name: "PT2BitsAv", value: 2, isUnsigned: true)
!2123 = !DIEnumerator(name: "NumLowBitsAvailable", value: 1, isUnsigned: true)
!2124 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !2126, file: !2125, line: 44, baseType: !2186, size: 64, elements: !2187, identifier: "_ZTSN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEEUt_E")
!2125 = !DIFile(filename: "llvm34/include/llvm/ADT/PointerIntPair.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "d23f9b419341ab3c3120cccf3bee7cc2")
!2126 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerIntPair<void *, 1U, bool, llvm::PointerUnionUIntTraits<clang::IdentifierInfo *, clang::MacroDefinition *> >", scope: !80, file: !2125, line: 42, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2127, templateParams: !2181, identifier: "_ZTSN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEEE")
!2127 = !{!2128, !2131, !2135, !2138, !2141, !2146, !2149, !2150, !2153, !2154, !2155, !2160, !2164, !2165, !2166, !2169, !2172, !2176, !2177, !2178, !2179, !2180}
!2128 = !DIDerivedType(tag: DW_TAG_member, name: "Value", scope: !2126, file: !2125, line: 43, baseType: !2129, size: 64)
!2129 = !DIDerivedType(tag: DW_TAG_typedef, name: "intptr_t", file: !2130, line: 97, baseType: !455)
!2130 = !DIFile(filename: "/usr/include/stdint.h", directory: "", checksumkind: CSK_MD5, checksum: "c7469e3b87cb3d1a363efabd19f04208")
!2131 = !DISubprogram(name: "PointerIntPair", scope: !2126, file: !2125, line: 60, type: !2132, scopeLine: 60, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2132 = !DISubroutineType(types: !2133)
!2133 = !{null, !2134}
!2134 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2126, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2135 = !DISubprogram(name: "PointerIntPair", scope: !2126, file: !2125, line: 61, type: !2136, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2136 = !DISubroutineType(types: !2137)
!2137 = !{null, !2134, !68, !46}
!2138 = !DISubprogram(name: "PointerIntPair", scope: !2126, file: !2125, line: 66, type: !2139, scopeLine: 66, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2139 = !DISubroutineType(types: !2140)
!2140 = !{null, !2134, !68}
!2141 = !DISubprogram(name: "getPointer", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEE10getPointerEv", scope: !2126, file: !2125, line: 70, type: !2142, scopeLine: 70, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2142 = !DISubroutineType(types: !2143)
!2143 = !{!68, !2144}
!2144 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2145, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2145 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2126)
!2146 = !DISubprogram(name: "getInt", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEE6getIntEv", scope: !2126, file: !2125, line: 75, type: !2147, scopeLine: 75, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2147 = !DISubroutineType(types: !2148)
!2148 = !{!46, !2144}
!2149 = !DISubprogram(name: "setPointer", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEE10setPointerES1_", scope: !2126, file: !2125, line: 79, type: !2139, scopeLine: 79, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2150 = !DISubprogram(name: "setInt", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEE6setIntEb", scope: !2126, file: !2125, line: 88, type: !2151, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2151 = !DISubroutineType(types: !2152)
!2152 = !{null, !2134, !46}
!2153 = !DISubprogram(name: "initWithPointer", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEE15initWithPointerES1_", scope: !2126, file: !2125, line: 97, type: !2139, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2154 = !DISubprogram(name: "setPointerAndInt", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEE16setPointerAndIntES1_b", scope: !2126, file: !2125, line: 105, type: !2136, scopeLine: 105, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2155 = !DISubprogram(name: "getAddrOfPointer", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEE16getAddrOfPointerEv", scope: !2126, file: !2125, line: 116, type: !2156, scopeLine: 116, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2156 = !DISubroutineType(types: !2157)
!2157 = !{!2158, !2144}
!2158 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2159, size: 64)
!2159 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !68)
!2160 = !DISubprogram(name: "getAddrOfPointer", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEE16getAddrOfPointerEv", scope: !2126, file: !2125, line: 120, type: !2161, scopeLine: 120, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2161 = !DISubroutineType(types: !2162)
!2162 = !{!2163, !2134}
!2163 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !68, size: 64)
!2164 = !DISubprogram(name: "getOpaqueValue", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEE14getOpaqueValueEv", scope: !2126, file: !2125, line: 127, type: !2142, scopeLine: 127, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2165 = !DISubprogram(name: "setFromOpaqueValue", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEE18setFromOpaqueValueES1_", scope: !2126, file: !2125, line: 128, type: !2139, scopeLine: 128, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2166 = !DISubprogram(name: "getFromOpaqueValue", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEE18getFromOpaqueValueES1_", scope: !2126, file: !2125, line: 130, type: !2167, scopeLine: 130, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2167 = !DISubroutineType(types: !2168)
!2168 = !{!2126, !68}
!2169 = !DISubprogram(name: "getFromOpaqueValue", linkageName: "_ZN4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEE18getFromOpaqueValueEPKv", scope: !2126, file: !2125, line: 136, type: !2170, scopeLine: 136, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2170 = !DISubroutineType(types: !2171)
!2171 = !{!2126, !72}
!2172 = !DISubprogram(name: "operator==", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEEeqERKS9_", scope: !2126, file: !2125, line: 141, type: !2173, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2173 = !DISubroutineType(types: !2174)
!2174 = !{!46, !2144, !2175}
!2175 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2145, size: 64)
!2176 = !DISubprogram(name: "operator!=", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEEneERKS9_", scope: !2126, file: !2125, line: 142, type: !2173, scopeLine: 142, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2177 = !DISubprogram(name: "operator<", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEEltERKS9_", scope: !2126, file: !2125, line: 143, type: !2173, scopeLine: 143, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2178 = !DISubprogram(name: "operator>", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEEgtERKS9_", scope: !2126, file: !2125, line: 144, type: !2173, scopeLine: 144, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2179 = !DISubprogram(name: "operator<=", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEEleERKS9_", scope: !2126, file: !2125, line: 145, type: !2173, scopeLine: 145, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2180 = !DISubprogram(name: "operator>=", linkageName: "_ZNK4llvm14PointerIntPairIPvLj1EbNS_22PointerUnionUIntTraitsIPN5clang14IdentifierInfoEPNS3_15MacroDefinitionEEEEgeERKS9_", scope: !2126, file: !2125, line: 146, type: !2173, scopeLine: 146, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2181 = !{!2182, !2183, !2184, !2185}
!2182 = !DITemplateTypeParameter(name: "PointerTy", type: !68)
!2183 = !DITemplateValueParameter(name: "IntBits", type: !6, value: i32 1)
!2184 = !DITemplateTypeParameter(name: "IntType", type: !46)
!2185 = !DITemplateTypeParameter(name: "PtrTraits", type: !2110)
!2186 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintptr_t", file: !2130, line: 100, baseType: !145)
!2187 = !{!2188, !2189, !2190, !2191}
!2188 = !DIEnumerator(name: "PointerBitMask", value: 18446744073709551614, isUnsigned: true)
!2189 = !DIEnumerator(name: "IntShift", value: 0, isUnsigned: true)
!2190 = !DIEnumerator(name: "IntMask", value: 1, isUnsigned: true)
!2191 = !DIEnumerator(name: "ShiftedIntMask", value: 1, isUnsigned: true)
!2192 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !2194, file: !2193, line: 62, baseType: !6, size: 32, elements: !2202, identifier: "_ZTSN4llvm21PointerLikeTypeTraitsIPKN5clang9MacroInfoEEUt_E")
!2193 = !DIFile(filename: "llvm34/include/llvm/Support/PointerLikeTypeTraits.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "8333c3efd9cf0bb9b9cfe8a278228322")
!2194 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerLikeTypeTraits<const clang::MacroInfo *>", scope: !80, file: !2193, line: 52, size: 8, flags: DIFlagTypePassByValue, elements: !2195, templateParams: !895, identifier: "_ZTSN4llvm21PointerLikeTypeTraitsIPKN5clang9MacroInfoEEE")
!2195 = !{!2196, !2199}
!2196 = !DISubprogram(name: "getAsVoidPointer", linkageName: "_ZN4llvm21PointerLikeTypeTraitsIPKN5clang9MacroInfoEE16getAsVoidPointerES4_", scope: !2194, file: !2193, line: 56, type: !2197, scopeLine: 56, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2197 = !DISubroutineType(types: !2198)
!2198 = !{!72, !734}
!2199 = !DISubprogram(name: "getFromVoidPointer", linkageName: "_ZN4llvm21PointerLikeTypeTraitsIPKN5clang9MacroInfoEE18getFromVoidPointerEPKv", scope: !2194, file: !2193, line: 59, type: !2200, scopeLine: 59, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2200 = !DISubroutineType(types: !2201)
!2201 = !{!734, !72}
!2202 = !{!2203}
!2203 = !DIEnumerator(name: "NumLowBitsAvailable", value: 2, isUnsigned: true)
!2204 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "FileChangeReason", scope: !150, file: !151, line: 41, baseType: !6, size: 32, elements: !2205, identifier: "_ZTSN5clang11PPCallbacks16FileChangeReasonE")
!2205 = !{!2206, !2207, !2208, !2209}
!2206 = !DIEnumerator(name: "EnterFile", value: 0, isUnsigned: true)
!2207 = !DIEnumerator(name: "ExitFile", value: 1, isUnsigned: true)
!2208 = !DIEnumerator(name: "SystemHeaderPragma", value: 2, isUnsigned: true)
!2209 = !DIEnumerator(name: "RenameFile", value: 3, isUnsigned: true)
!2210 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "PragmaIntroducerKind", scope: !14, file: !2211, line: 32, baseType: !6, size: 32, elements: !2212, identifier: "_ZTSN5clang20PragmaIntroducerKindE")
!2211 = !DIFile(filename: "llvm34/projects/clang/include/clang/Lex/Pragma.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "5d13c1760944099afa8248b805f10704")
!2212 = !{!2213, !2214, !2215}
!2213 = !DIEnumerator(name: "PIK_HashPragma", value: 0, isUnsigned: true)
!2214 = !DIEnumerator(name: "PIK__Pragma", value: 1, isUnsigned: true)
!2215 = !DIEnumerator(name: "PIK___pragma", value: 2, isUnsigned: true)
!2216 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "PragmaMessageKind", scope: !150, file: !151, line: 183, baseType: !6, size: 32, elements: !2217, identifier: "_ZTSN5clang11PPCallbacks17PragmaMessageKindE")
!2217 = !{!2218, !2219, !2220}
!2218 = !DIEnumerator(name: "PMK_Message", value: 0, isUnsigned: true)
!2219 = !DIEnumerator(name: "PMK_Warning", value: 1, isUnsigned: true)
!2220 = !DIEnumerator(name: "PMK_Error", value: 2, isUnsigned: true)
!2221 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, name: "Mapping", scope: !2223, file: !2222, line: 63, baseType: !6, size: 32, elements: !2224, identifier: "_ZTSN5clang4diag7MappingE")
!2222 = !DIFile(filename: "llvm34/projects/clang/include/clang/Basic/DiagnosticIDs.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "d3dd8be052b98ac08581c112be7e2a4d")
!2223 = !DINamespace(name: "diag", scope: !14)
!2224 = !{!2225, !2226, !2227, !2228}
!2225 = !DIEnumerator(name: "MAP_IGNORE", value: 1, isUnsigned: true)
!2226 = !DIEnumerator(name: "MAP_WARNING", value: 2, isUnsigned: true)
!2227 = !DIEnumerator(name: "MAP_ERROR", value: 3, isUnsigned: true)
!2228 = !DIEnumerator(name: "MAP_FATAL", value: 4, isUnsigned: true)
!2229 = distinct !DICompositeType(tag: DW_TAG_enumeration_type, scope: !2230, file: !1174, line: 39, baseType: !6, size: 32, elements: !2233, identifier: "_ZTSN4llvm7AlignOfIcEUt_E")
!2230 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "AlignOf<char>", scope: !80, file: !1174, line: 38, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !2231, identifier: "_ZTSN4llvm7AlignOfIcEE")
!2231 = !{!2232}
!2232 = !DITemplateTypeParameter(name: "T", type: !641)
!2233 = !{!2234}
!2234 = !DIEnumerator(name: "Alignment", value: 1, isUnsigned: true)
!2235 = !{!2236, !6, !46, !62, !2237, !2263, !2408, !1335, !2118, !1789, !68, !2129, !2410, !2411, !2413, !2186, !734, !2414, !2415, !1249, !363, !1042, !472, !2416, !411, !224, !2437, !72, !182, !2438, !410, !2489, !986, !13, !147, !1429, !1426, !1280, !1277, !1114, !1111, !473, !17, !20, !1520, !1635, !1632, !150, !1273, !1389, !2323, !2320, !2490, !2493, !2582, !32, !2611, !2615, !2126, !740, !36, !1169, !716, !712, !2677, !2754, !158, !162, !165, !186, !192, !689, !693, !2828, !699, !832}
!2236 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !641, size: 64)
!2237 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "PPEntityComp<&clang::SourceRange::getBegin>", scope: !2239, file: !2238, line: 173, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2240, templateParams: !2260)
!2238 = !DIFile(filename: "llvm34/projects/clang/lib/Lex/PreprocessingRecord.cpp", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "991bca3cdaf717d22161d5089bc09e32")
!2239 = !DINamespace(scope: null)
!2240 = !{!2241, !2242, !2246, !2251, !2254, !2257}
!2241 = !DIDerivedType(tag: DW_TAG_member, name: "SM", scope: !2237, file: !2238, line: 174, baseType: !81, size: 64)
!2242 = !DISubprogram(name: "PPEntityComp", scope: !2237, file: !2238, line: 176, type: !2243, scopeLine: 176, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!2243 = !DISubroutineType(types: !2244)
!2244 = !{null, !2245, !81}
!2245 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2237, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2246 = !DISubprogram(name: "operator()", linkageName: "_ZNK12_GLOBAL__N_112PPEntityCompIXadL_ZNK5clang11SourceRange8getBeginEvEEEclEPNS1_18PreprocessedEntityES5_", scope: !2237, file: !2238, line: 178, type: !2247, scopeLine: 178, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!2247 = !DISubroutineType(types: !2248)
!2248 = !{!46, !2249, !183, !183}
!2249 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2250, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2250 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2237)
!2251 = !DISubprogram(name: "operator()", linkageName: "_ZNK12_GLOBAL__N_112PPEntityCompIXadL_ZNK5clang11SourceRange8getBeginEvEEEclEPNS1_18PreprocessedEntityENS1_14SourceLocationE", scope: !2237, file: !2238, line: 184, type: !2252, scopeLine: 184, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!2252 = !DISubroutineType(types: !2253)
!2253 = !{!46, !2249, !183, !36}
!2254 = !DISubprogram(name: "operator()", linkageName: "_ZNK12_GLOBAL__N_112PPEntityCompIXadL_ZNK5clang11SourceRange8getBeginEvEEEclENS1_14SourceLocationEPNS1_18PreprocessedEntityE", scope: !2237, file: !2238, line: 189, type: !2255, scopeLine: 189, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!2255 = !DISubroutineType(types: !2256)
!2256 = !{!46, !2249, !36, !183}
!2257 = !DISubprogram(name: "getLoc", linkageName: "_ZNK12_GLOBAL__N_112PPEntityCompIXadL_ZNK5clang11SourceRange8getBeginEvEEE6getLocEPNS1_18PreprocessedEntityE", scope: !2237, file: !2238, line: 194, type: !2258, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!2258 = !DISubroutineType(types: !2259)
!2259 = !{!36, !2249, !183}
!2260 = !{!2261}
!2261 = !DITemplateValueParameter(name: "getRangeLoc", type: !2262, value: { i64, i64 } zeroinitializer)
!2262 = !DIDerivedType(tag: DW_TAG_ptr_to_member_type, baseType: !109, size: 128, extraData: !32)
!2263 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !2265, file: !2264, line: 101, baseType: !2266)
!2264 = !DIFile(filename: "llvm34/include/llvm/ADT/SmallVector.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "69b512a6e55455ea0ed3a25fbee45d45")
!2265 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SmallVectorTemplateCommon<clang::SrcMgr::SLocEntry, void>", scope: !80, file: !2264, line: 66, size: 384, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm25SmallVectorTemplateCommonIN5clang6SrcMgr9SLocEntryEvEE")
!2266 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2267, size: 64)
!2267 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2268)
!2268 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "SLocEntry", scope: !1780, file: !84, line: 389, size: 192, flags: DIFlagTypePassByValue, elements: !2269, identifier: "_ZTSN5clang6SrcMgr9SLocEntryE")
!2269 = !{!2270, !2271, !2386, !2390, !2393, !2394, !2398, !2402, !2405}
!2270 = !DIDerivedType(tag: DW_TAG_member, name: "Offset", scope: !2268, file: !84, line: 390, baseType: !6, size: 32)
!2271 = !DIDerivedType(tag: DW_TAG_member, scope: !2268, file: !84, line: 391, baseType: !2272, size: 128, offset: 64)
!2272 = distinct !DICompositeType(tag: DW_TAG_union_type, scope: !2268, file: !84, line: 391, size: 128, flags: DIFlagExportSymbols | DIFlagTypePassByValue, elements: !2273, identifier: "_ZTSN5clang6SrcMgr9SLocEntryUt_E")
!2273 = !{!2274, !2304}
!2274 = !DIDerivedType(tag: DW_TAG_member, name: "File", scope: !2272, file: !84, line: 392, baseType: !2275, size: 128)
!2275 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "FileInfo", scope: !1780, file: !84, line: 236, size: 128, flags: DIFlagTypePassByValue, elements: !2276, identifier: "_ZTSN5clang6SrcMgr8FileInfoE")
!2276 = !{!2277, !2278, !2279, !2280, !2286, !2291, !2294, !2297, !2300}
!2277 = !DIDerivedType(tag: DW_TAG_member, name: "IncludeLoc", scope: !2275, file: !84, line: 240, baseType: !6, size: 32)
!2278 = !DIDerivedType(tag: DW_TAG_member, name: "NumCreatedFIDs", scope: !2275, file: !84, line: 246, baseType: !6, size: 32, offset: 32)
!2279 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !2275, file: !84, line: 251, baseType: !2186, size: 64, offset: 64)
!2280 = !DISubprogram(name: "get", linkageName: "_ZN5clang6SrcMgr8FileInfo3getENS_14SourceLocationEPKNS0_12ContentCacheENS0_18CharacteristicKindE", scope: !2275, file: !84, line: 258, type: !2281, scopeLine: 258, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2281 = !DISubroutineType(types: !2282)
!2282 = !{!2275, !36, !2283, !1779}
!2283 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2284, size: 64)
!2284 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2285)
!2285 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ContentCache", scope: !1780, file: !84, line: 84, size: 320, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang6SrcMgr12ContentCacheE")
!2286 = !DISubprogram(name: "getIncludeLoc", linkageName: "_ZNK5clang6SrcMgr8FileInfo13getIncludeLocEv", scope: !2275, file: !84, line: 270, type: !2287, scopeLine: 270, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2287 = !DISubroutineType(types: !2288)
!2288 = !{!36, !2289}
!2289 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2290, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2290 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2275)
!2291 = !DISubprogram(name: "getContentCache", linkageName: "_ZNK5clang6SrcMgr8FileInfo15getContentCacheEv", scope: !2275, file: !84, line: 273, type: !2292, scopeLine: 273, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2292 = !DISubroutineType(types: !2293)
!2293 = !{!2283, !2289}
!2294 = !DISubprogram(name: "getFileCharacteristic", linkageName: "_ZNK5clang6SrcMgr8FileInfo21getFileCharacteristicEv", scope: !2275, file: !84, line: 278, type: !2295, scopeLine: 278, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2295 = !DISubroutineType(types: !2296)
!2296 = !{!1779, !2289}
!2297 = !DISubprogram(name: "hasLineDirectives", linkageName: "_ZNK5clang6SrcMgr8FileInfo17hasLineDirectivesEv", scope: !2275, file: !84, line: 283, type: !2298, scopeLine: 283, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2298 = !DISubroutineType(types: !2299)
!2299 = !{!46, !2289}
!2300 = !DISubprogram(name: "setHasLineDirectives", linkageName: "_ZN5clang6SrcMgr8FileInfo20setHasLineDirectivesEv", scope: !2275, file: !84, line: 287, type: !2301, scopeLine: 287, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2301 = !DISubroutineType(types: !2302)
!2302 = !{null, !2303}
!2303 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2275, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2304 = !DIDerivedType(tag: DW_TAG_member, name: "Expansion", scope: !2272, file: !84, line: 393, baseType: !2305, size: 96)
!2305 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ExpansionInfo", scope: !1780, file: !84, line: 295, size: 96, flags: DIFlagTypePassByValue, elements: !2306, identifier: "_ZTSN5clang6SrcMgr13ExpansionInfoE")
!2306 = !{!2307, !2308, !2309, !2310, !2315, !2316, !2317, !2375, !2378, !2379, !2380, !2383}
!2307 = !DIDerivedType(tag: DW_TAG_member, name: "SpellingLoc", scope: !2305, file: !84, line: 299, baseType: !6, size: 32)
!2308 = !DIDerivedType(tag: DW_TAG_member, name: "ExpansionLocStart", scope: !2305, file: !84, line: 307, baseType: !6, size: 32, offset: 32)
!2309 = !DIDerivedType(tag: DW_TAG_member, name: "ExpansionLocEnd", scope: !2305, file: !84, line: 307, baseType: !6, size: 32, offset: 64)
!2310 = !DISubprogram(name: "getSpellingLoc", linkageName: "_ZNK5clang6SrcMgr13ExpansionInfo14getSpellingLocEv", scope: !2305, file: !84, line: 310, type: !2311, scopeLine: 310, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2311 = !DISubroutineType(types: !2312)
!2312 = !{!36, !2313}
!2313 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2314, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2314 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2305)
!2315 = !DISubprogram(name: "getExpansionLocStart", linkageName: "_ZNK5clang6SrcMgr13ExpansionInfo20getExpansionLocStartEv", scope: !2305, file: !84, line: 313, type: !2311, scopeLine: 313, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2316 = !DISubprogram(name: "getExpansionLocEnd", linkageName: "_ZNK5clang6SrcMgr13ExpansionInfo18getExpansionLocEndEv", scope: !2305, file: !84, line: 316, type: !2311, scopeLine: 316, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2317 = !DISubprogram(name: "getExpansionLocRange", linkageName: "_ZNK5clang6SrcMgr13ExpansionInfo20getExpansionLocRangeEv", scope: !2305, file: !84, line: 322, type: !2318, scopeLine: 322, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2318 = !DISubroutineType(types: !2319)
!2319 = !{!2320, !2313}
!2320 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<clang::SourceLocation, clang::SourceLocation>", scope: !91, file: !713, line: 208, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2321, templateParams: !2372, identifier: "_ZTSSt4pairIN5clang14SourceLocationES1_E")
!2321 = !{!2322, !2342, !2343, !2344, !2350, !2354, !2362, !2369}
!2322 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2320, baseType: !2323, flags: DIFlagPrivate, extraData: i32 0)
!2323 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "__pair_base<clang::SourceLocation, clang::SourceLocation>", scope: !91, file: !713, line: 190, size: 8, flags: DIFlagTypePassByValue, elements: !2324, templateParams: !2339, identifier: "_ZTSSt11__pair_baseIN5clang14SourceLocationES1_E")
!2324 = !{!2325, !2329, !2330, !2335}
!2325 = !DISubprogram(name: "__pair_base", scope: !2323, file: !713, line: 194, type: !2326, scopeLine: 194, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2326 = !DISubroutineType(types: !2327)
!2327 = !{null, !2328}
!2328 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2323, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2329 = !DISubprogram(name: "~__pair_base", scope: !2323, file: !713, line: 195, type: !2326, scopeLine: 195, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2330 = !DISubprogram(name: "__pair_base", scope: !2323, file: !713, line: 196, type: !2331, scopeLine: 196, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2331 = !DISubroutineType(types: !2332)
!2332 = !{null, !2328, !2333}
!2333 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2334, size: 64)
!2334 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2323)
!2335 = !DISubprogram(name: "operator=", linkageName: "_ZNSt11__pair_baseIN5clang14SourceLocationES1_EaSERKS2_", scope: !2323, file: !713, line: 197, type: !2336, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized | DISPFlagDeleted)
!2336 = !DISubroutineType(types: !2337)
!2337 = !{!2338, !2328, !2333}
!2338 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2323, size: 64)
!2339 = !{!2340, !2341}
!2340 = !DITemplateTypeParameter(name: "_U1", type: !36)
!2341 = !DITemplateTypeParameter(name: "_U2", type: !36)
!2342 = !DIDerivedType(tag: DW_TAG_member, name: "first", scope: !2320, file: !713, line: 214, baseType: !36, size: 32)
!2343 = !DIDerivedType(tag: DW_TAG_member, name: "second", scope: !2320, file: !713, line: 215, baseType: !36, size: 32, offset: 32)
!2344 = !DISubprogram(name: "pair", scope: !2320, file: !713, line: 303, type: !2345, scopeLine: 303, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2345 = !DISubroutineType(types: !2346)
!2346 = !{null, !2347, !2348}
!2347 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2320, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2348 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2349, size: 64)
!2349 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2320)
!2350 = !DISubprogram(name: "pair", scope: !2320, file: !713, line: 304, type: !2351, scopeLine: 304, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2351 = !DISubroutineType(types: !2352)
!2352 = !{null, !2347, !2353}
!2353 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2320, size: 64)
!2354 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN5clang14SourceLocationES1_EaSERKS2_", scope: !2320, file: !713, line: 378, type: !2355, scopeLine: 378, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2355 = !DISubroutineType(types: !2356)
!2356 = !{!2357, !2347, !2358}
!2357 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2320, size: 64)
!2358 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2359, file: !656, line: 1928, baseType: !2348)
!2359 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, const std::pair<clang::SourceLocation, clang::SourceLocation> &, const std::__nonesuch_no_braces &>", scope: !91, file: !656, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !2360, identifier: "_ZTSSt11conditionalILb1ERKSt4pairIN5clang14SourceLocationES2_ERKSt20__nonesuch_no_bracesE")
!2360 = !{!782, !2361, !784}
!2361 = !DITemplateTypeParameter(name: "_Iftrue", type: !2348)
!2362 = !DISubprogram(name: "operator=", linkageName: "_ZNSt4pairIN5clang14SourceLocationES1_EaSEOS2_", scope: !2320, file: !713, line: 389, type: !2363, scopeLine: 389, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2363 = !DISubroutineType(types: !2364)
!2364 = !{!2357, !2347, !2365}
!2365 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2366, file: !656, line: 1928, baseType: !2353)
!2366 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, std::pair<clang::SourceLocation, clang::SourceLocation> &&, std::__nonesuch_no_braces &&>", scope: !91, file: !656, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !2367, identifier: "_ZTSSt11conditionalILb1EOSt4pairIN5clang14SourceLocationES2_EOSt20__nonesuch_no_bracesE")
!2367 = !{!782, !2368, !795}
!2368 = !DITemplateTypeParameter(name: "_Iftrue", type: !2353)
!2369 = !DISubprogram(name: "swap", linkageName: "_ZNSt4pairIN5clang14SourceLocationES1_E4swapERS2_", scope: !2320, file: !713, line: 424, type: !2370, scopeLine: 424, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2370 = !DISubroutineType(types: !2371)
!2371 = !{null, !2347, !2357}
!2372 = !{!2373, !2374}
!2373 = !DITemplateTypeParameter(name: "_T1", type: !36)
!2374 = !DITemplateTypeParameter(name: "_T2", type: !36)
!2375 = !DISubprogram(name: "isMacroArgExpansion", linkageName: "_ZNK5clang6SrcMgr13ExpansionInfo19isMacroArgExpansionEv", scope: !2305, file: !84, line: 326, type: !2376, scopeLine: 326, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2376 = !DISubroutineType(types: !2377)
!2377 = !{!46, !2313}
!2378 = !DISubprogram(name: "isMacroBodyExpansion", linkageName: "_ZNK5clang6SrcMgr13ExpansionInfo20isMacroBodyExpansionEv", scope: !2305, file: !84, line: 332, type: !2376, scopeLine: 332, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2379 = !DISubprogram(name: "isFunctionMacroExpansion", linkageName: "_ZNK5clang6SrcMgr13ExpansionInfo24isFunctionMacroExpansionEv", scope: !2305, file: !84, line: 337, type: !2376, scopeLine: 337, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2380 = !DISubprogram(name: "create", linkageName: "_ZN5clang6SrcMgr13ExpansionInfo6createENS_14SourceLocationES2_S2_", scope: !2305, file: !84, line: 348, type: !2381, scopeLine: 348, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2381 = !DISubroutineType(types: !2382)
!2382 = !{!2305, !36, !36, !36}
!2383 = !DISubprogram(name: "createForMacroArg", linkageName: "_ZN5clang6SrcMgr13ExpansionInfo17createForMacroArgENS_14SourceLocationES2_", scope: !2305, file: !84, line: 376, type: !2384, scopeLine: 376, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2384 = !DISubroutineType(types: !2385)
!2385 = !{!2305, !36, !36}
!2386 = !DISubprogram(name: "getOffset", linkageName: "_ZNK5clang6SrcMgr9SLocEntry9getOffsetEv", scope: !2268, file: !84, line: 396, type: !2387, scopeLine: 396, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2387 = !DISubroutineType(types: !2388)
!2388 = !{!6, !2389}
!2389 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2267, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2390 = !DISubprogram(name: "isExpansion", linkageName: "_ZNK5clang6SrcMgr9SLocEntry11isExpansionEv", scope: !2268, file: !84, line: 398, type: !2391, scopeLine: 398, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2391 = !DISubroutineType(types: !2392)
!2392 = !{!46, !2389}
!2393 = !DISubprogram(name: "isFile", linkageName: "_ZNK5clang6SrcMgr9SLocEntry6isFileEv", scope: !2268, file: !84, line: 399, type: !2391, scopeLine: 399, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2394 = !DISubprogram(name: "getFile", linkageName: "_ZNK5clang6SrcMgr9SLocEntry7getFileEv", scope: !2268, file: !84, line: 401, type: !2395, scopeLine: 401, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2395 = !DISubroutineType(types: !2396)
!2396 = !{!2397, !2389}
!2397 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2290, size: 64)
!2398 = !DISubprogram(name: "getExpansion", linkageName: "_ZNK5clang6SrcMgr9SLocEntry12getExpansionEv", scope: !2268, file: !84, line: 406, type: !2399, scopeLine: 406, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2399 = !DISubroutineType(types: !2400)
!2400 = !{!2401, !2389}
!2401 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2314, size: 64)
!2402 = !DISubprogram(name: "get", linkageName: "_ZN5clang6SrcMgr9SLocEntry3getEjRKNS0_8FileInfoE", scope: !2268, file: !84, line: 411, type: !2403, scopeLine: 411, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2403 = !DISubroutineType(types: !2404)
!2404 = !{!2268, !6, !2397}
!2405 = !DISubprogram(name: "get", linkageName: "_ZN5clang6SrcMgr9SLocEntry3getEjRKNS0_13ExpansionInfoE", scope: !2268, file: !84, line: 418, type: !2406, scopeLine: 418, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2406 = !DISubroutineType(types: !2407)
!2407 = !{!2268, !6, !2401}
!2408 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2265, file: !2264, line: 100, baseType: !2409)
!2409 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2268, size: 64)
!2410 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1509, size: 64)
!2411 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2412, size: 64)
!2412 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "DefInfo", scope: !1509, file: !737, line: 395, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN5clang14MacroDirective7DefInfoE")
!2413 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !1055, size: 64)
!2414 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !689, size: 64)
!2415 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !168, size: 64)
!2416 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Val_comp_iter<(anonymous namespace)::PPEntityComp<&clang::SourceRange::getBegin> >", scope: !2418, file: !2417, line: 191, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2419, templateParams: !2435)
!2417 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/predefined_ops.h", directory: "", checksumkind: CSK_MD5, checksum: "c4488885b044d9477796f6d04761c9e8")
!2418 = !DINamespace(name: "__ops", scope: !5)
!2419 = !{!2420, !2421, !2425, !2431}
!2420 = !DIDerivedType(tag: DW_TAG_member, name: "_M_comp", scope: !2416, file: !2417, line: 193, baseType: !2237, size: 64)
!2421 = !DISubprogram(name: "_Val_comp_iter", scope: !2416, file: !2417, line: 196, type: !2422, scopeLine: 196, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!2422 = !DISubroutineType(types: !2423)
!2423 = !{null, !2424, !2237}
!2424 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2416, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2425 = !DISubprogram(name: "_Val_comp_iter", scope: !2416, file: !2417, line: 201, type: !2426, scopeLine: 201, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!2426 = !DISubroutineType(types: !2427)
!2427 = !{null, !2424, !2428}
!2428 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2429, size: 64)
!2429 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2430)
!2430 = !DICompositeType(tag: DW_TAG_structure_type, name: "_Iter_comp_iter<(anonymous namespace)::PPEntityComp<&clang::SourceRange::getBegin> >", scope: !2418, file: !2417, line: 130, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial)
!2431 = !DISubprogram(name: "_Val_comp_iter", scope: !2416, file: !2417, line: 207, type: !2432, scopeLine: 207, flags: DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagOptimized)
!2432 = !DISubroutineType(types: !2433)
!2433 = !{null, !2424, !2434}
!2434 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !2430, size: 64)
!2435 = !{!2436}
!2436 = !DITemplateTypeParameter(name: "_Compare", type: !2237)
!2437 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !294, size: 64)
!2438 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "move_iterator<clang::PreprocessedEntity **>", scope: !91, file: !412, line: 1007, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2439, templateParams: !431, identifier: "_ZTSSt13move_iteratorIPPN5clang18PreprocessedEntityEE")
!2439 = !{!2440, !2441, !2445, !2449, !2454, !2464, !2468, !2472, !2475, !2476, !2477, !2481, !2484, !2485, !2486}
!2440 = !DIDerivedType(tag: DW_TAG_member, name: "_M_current", scope: !2438, file: !412, line: 1010, baseType: !182, size: 64, flags: DIFlagProtected)
!2441 = !DISubprogram(name: "move_iterator", scope: !2438, file: !412, line: 1029, type: !2442, scopeLine: 1029, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2442 = !DISubroutineType(types: !2443)
!2443 = !{null, !2444}
!2444 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2438, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2445 = !DISubprogram(name: "move_iterator", scope: !2438, file: !412, line: 1033, type: !2446, scopeLine: 1033, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2446 = !DISubroutineType(types: !2447)
!2447 = !{null, !2444, !2448}
!2448 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator_type", scope: !2438, file: !412, line: 1016, baseType: !182)
!2449 = !DISubprogram(name: "base", linkageName: "_ZNKSt13move_iteratorIPPN5clang18PreprocessedEntityEE4baseEv", scope: !2438, file: !412, line: 1042, type: !2450, scopeLine: 1042, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2450 = !DISubroutineType(types: !2451)
!2451 = !{!2448, !2452}
!2452 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2453, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2453 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2438)
!2454 = !DISubprogram(name: "operator*", linkageName: "_ZNKSt13move_iteratorIPPN5clang18PreprocessedEntityEEdeEv", scope: !2438, file: !412, line: 1046, type: !2455, scopeLine: 1046, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2455 = !DISubroutineType(types: !2456)
!2456 = !{!2457, !2452}
!2457 = !DIDerivedType(tag: DW_TAG_typedef, name: "reference", scope: !2438, file: !412, line: 1026, baseType: !2458)
!2458 = !DIDerivedType(tag: DW_TAG_typedef, name: "type", scope: !2459, file: !656, line: 1928, baseType: !2462)
!2459 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "conditional<true, clang::PreprocessedEntity *&&, clang::PreprocessedEntity *&>", scope: !91, file: !656, line: 1927, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !2460, identifier: "_ZTSSt11conditionalILb1EOPN5clang18PreprocessedEntityERS2_E")
!2460 = !{!782, !2461, !2463}
!2461 = !DITemplateTypeParameter(name: "_Iftrue", type: !2462)
!2462 = !DIDerivedType(tag: DW_TAG_rvalue_reference_type, baseType: !183, size: 64)
!2463 = !DITemplateTypeParameter(name: "_Iffalse", type: !211)
!2464 = !DISubprogram(name: "operator->", linkageName: "_ZNKSt13move_iteratorIPPN5clang18PreprocessedEntityEEptEv", scope: !2438, file: !412, line: 1050, type: !2465, scopeLine: 1050, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2465 = !DISubroutineType(types: !2466)
!2466 = !{!2467, !2452}
!2467 = !DIDerivedType(tag: DW_TAG_typedef, name: "pointer", scope: !2438, file: !412, line: 1021, baseType: !182)
!2468 = !DISubprogram(name: "operator++", linkageName: "_ZNSt13move_iteratorIPPN5clang18PreprocessedEntityEEppEv", scope: !2438, file: !412, line: 1054, type: !2469, scopeLine: 1054, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2469 = !DISubroutineType(types: !2470)
!2470 = !{!2471, !2444}
!2471 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2438, size: 64)
!2472 = !DISubprogram(name: "operator++", linkageName: "_ZNSt13move_iteratorIPPN5clang18PreprocessedEntityEEppEi", scope: !2438, file: !412, line: 1061, type: !2473, scopeLine: 1061, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2473 = !DISubroutineType(types: !2474)
!2474 = !{!2438, !2444, !62}
!2475 = !DISubprogram(name: "operator--", linkageName: "_ZNSt13move_iteratorIPPN5clang18PreprocessedEntityEEmmEv", scope: !2438, file: !412, line: 1069, type: !2469, scopeLine: 1069, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2476 = !DISubprogram(name: "operator--", linkageName: "_ZNSt13move_iteratorIPPN5clang18PreprocessedEntityEEmmEi", scope: !2438, file: !412, line: 1076, type: !2473, scopeLine: 1076, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2477 = !DISubprogram(name: "operator+", linkageName: "_ZNKSt13move_iteratorIPPN5clang18PreprocessedEntityEEplEl", scope: !2438, file: !412, line: 1084, type: !2478, scopeLine: 1084, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2478 = !DISubroutineType(types: !2479)
!2479 = !{!2438, !2452, !2480}
!2480 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !2438, file: !412, line: 1019, baseType: !453)
!2481 = !DISubprogram(name: "operator+=", linkageName: "_ZNSt13move_iteratorIPPN5clang18PreprocessedEntityEEpLEl", scope: !2438, file: !412, line: 1088, type: !2482, scopeLine: 1088, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2482 = !DISubroutineType(types: !2483)
!2483 = !{!2471, !2444, !2480}
!2484 = !DISubprogram(name: "operator-", linkageName: "_ZNKSt13move_iteratorIPPN5clang18PreprocessedEntityEEmiEl", scope: !2438, file: !412, line: 1095, type: !2478, scopeLine: 1095, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2485 = !DISubprogram(name: "operator-=", linkageName: "_ZNSt13move_iteratorIPPN5clang18PreprocessedEntityEEmIEl", scope: !2438, file: !412, line: 1099, type: !2482, scopeLine: 1099, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2486 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt13move_iteratorIPPN5clang18PreprocessedEntityEEixEl", scope: !2438, file: !412, line: 1106, type: !2487, scopeLine: 1106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2487 = !DISubroutineType(types: !2488)
!2488 = !{!2457, !2452, !2480}
!2489 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !916, size: 64)
!2490 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bit_const_iterator", scope: !91, file: !1786, line: 302, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2491, identifier: "_ZTSSt19_Bit_const_iterator")
!2491 = !{!2492, !2538, !2542, !2545, !2551, !2556, !2560, !2565, !2568, !2569, !2570, !2574, !2575, !2578, !2579}
!2492 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2490, baseType: !2493, extraData: i32 0)
!2493 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bit_iterator_base", scope: !91, file: !1786, line: 138, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2494, identifier: "_ZTSSt18_Bit_iterator_base")
!2494 = !{!2495, !2512, !2515, !2516, !2520, !2523, !2524, !2527, !2533, !2534, !2535, !2536, !2537}
!2495 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2493, baseType: !2496, extraData: i32 0)
!2496 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "iterator<std::random_access_iterator_tag, bool, long, bool *, bool &>", scope: !91, file: !429, line: 118, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !2497, identifier: "_ZTSSt8iteratorISt26random_access_iterator_tagblPbRbE")
!2497 = !{!2498, !669, !2509, !2510, !2511}
!2498 = !DITemplateTypeParameter(name: "_Category", type: !2499)
!2499 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "random_access_iterator_tag", scope: !91, file: !429, line: 103, size: 8, flags: DIFlagTypePassByValue, elements: !2500, identifier: "_ZTSSt26random_access_iterator_tag")
!2500 = !{!2501}
!2501 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2499, baseType: !2502, extraData: i32 0)
!2502 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "bidirectional_iterator_tag", scope: !91, file: !429, line: 99, size: 8, flags: DIFlagTypePassByValue, elements: !2503, identifier: "_ZTSSt26bidirectional_iterator_tag")
!2503 = !{!2504}
!2504 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2502, baseType: !2505, extraData: i32 0)
!2505 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "forward_iterator_tag", scope: !91, file: !429, line: 95, size: 8, flags: DIFlagTypePassByValue, elements: !2506, identifier: "_ZTSSt20forward_iterator_tag")
!2506 = !{!2507}
!2507 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2505, baseType: !2508, extraData: i32 0)
!2508 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "input_iterator_tag", scope: !91, file: !429, line: 89, size: 8, flags: DIFlagTypePassByValue, elements: !279, identifier: "_ZTSSt18input_iterator_tag")
!2509 = !DITemplateTypeParameter(name: "_Distance", type: !455)
!2510 = !DITemplateTypeParameter(name: "_Pointer", type: !1249)
!2511 = !DITemplateTypeParameter(name: "_Reference", type: !1256)
!2512 = !DIDerivedType(tag: DW_TAG_member, name: "_M_p", scope: !2493, file: !1786, line: 141, baseType: !2513, size: 64)
!2513 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2514, size: 64)
!2514 = !DIDerivedType(tag: DW_TAG_typedef, name: "_Bit_type", scope: !91, file: !1786, line: 69, baseType: !145)
!2515 = !DIDerivedType(tag: DW_TAG_member, name: "_M_offset", scope: !2493, file: !1786, line: 142, baseType: !6, size: 32, offset: 64)
!2516 = !DISubprogram(name: "_Bit_iterator_base", scope: !2493, file: !1786, line: 144, type: !2517, scopeLine: 144, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2517 = !DISubroutineType(types: !2518)
!2518 = !{null, !2519, !2513, !6}
!2519 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2493, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2520 = !DISubprogram(name: "_M_bump_up", linkageName: "_ZNSt18_Bit_iterator_base10_M_bump_upEv", scope: !2493, file: !1786, line: 148, type: !2521, scopeLine: 148, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2521 = !DISubroutineType(types: !2522)
!2522 = !{null, !2519}
!2523 = !DISubprogram(name: "_M_bump_down", linkageName: "_ZNSt18_Bit_iterator_base12_M_bump_downEv", scope: !2493, file: !1786, line: 158, type: !2521, scopeLine: 158, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2524 = !DISubprogram(name: "_M_incr", linkageName: "_ZNSt18_Bit_iterator_base7_M_incrEl", scope: !2493, file: !1786, line: 168, type: !2525, scopeLine: 168, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2525 = !DISubroutineType(types: !2526)
!2526 = !{null, !2519, !454}
!2527 = !DISubprogram(name: "operator==", linkageName: "_ZNKSt18_Bit_iterator_baseeqERKS_", scope: !2493, file: !1786, line: 182, type: !2528, scopeLine: 182, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2528 = !DISubroutineType(types: !2529)
!2529 = !{!46, !2530, !2532}
!2530 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2531, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2531 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2493)
!2532 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2531, size: 64)
!2533 = !DISubprogram(name: "operator<", linkageName: "_ZNKSt18_Bit_iterator_baseltERKS_", scope: !2493, file: !1786, line: 186, type: !2528, scopeLine: 186, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2534 = !DISubprogram(name: "operator!=", linkageName: "_ZNKSt18_Bit_iterator_baseneERKS_", scope: !2493, file: !1786, line: 193, type: !2528, scopeLine: 193, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2535 = !DISubprogram(name: "operator>", linkageName: "_ZNKSt18_Bit_iterator_basegtERKS_", scope: !2493, file: !1786, line: 197, type: !2528, scopeLine: 197, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2536 = !DISubprogram(name: "operator<=", linkageName: "_ZNKSt18_Bit_iterator_baseleERKS_", scope: !2493, file: !1786, line: 201, type: !2528, scopeLine: 201, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2537 = !DISubprogram(name: "operator>=", linkageName: "_ZNKSt18_Bit_iterator_basegeERKS_", scope: !2493, file: !1786, line: 205, type: !2528, scopeLine: 205, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2538 = !DISubprogram(name: "_Bit_const_iterator", scope: !2490, file: !1786, line: 309, type: !2539, scopeLine: 309, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2539 = !DISubroutineType(types: !2540)
!2540 = !{null, !2541}
!2541 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2490, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2542 = !DISubprogram(name: "_Bit_const_iterator", scope: !2490, file: !1786, line: 311, type: !2543, scopeLine: 311, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2543 = !DISubroutineType(types: !2544)
!2544 = !{null, !2541, !2513, !6}
!2545 = !DISubprogram(name: "_Bit_const_iterator", scope: !2490, file: !1786, line: 314, type: !2546, scopeLine: 314, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2546 = !DISubroutineType(types: !2547)
!2547 = !{null, !2541, !2548}
!2548 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2549, size: 64)
!2549 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2550)
!2550 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bit_iterator", scope: !91, file: !1786, line: 216, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt13_Bit_iterator")
!2551 = !DISubprogram(name: "_M_const_cast", linkageName: "_ZNKSt19_Bit_const_iterator13_M_const_castEv", scope: !2490, file: !1786, line: 318, type: !2552, scopeLine: 318, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2552 = !DISubroutineType(types: !2553)
!2553 = !{!2550, !2554}
!2554 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2555, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2555 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2490)
!2556 = !DISubprogram(name: "operator*", linkageName: "_ZNKSt19_Bit_const_iteratordeEv", scope: !2490, file: !1786, line: 322, type: !2557, scopeLine: 322, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2557 = !DISubroutineType(types: !2558)
!2558 = !{!2559, !2554}
!2559 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_reference", scope: !2490, file: !1786, line: 305, baseType: !46)
!2560 = !DISubprogram(name: "operator++", linkageName: "_ZNSt19_Bit_const_iteratorppEv", scope: !2490, file: !1786, line: 326, type: !2561, scopeLine: 326, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2561 = !DISubroutineType(types: !2562)
!2562 = !{!2563, !2541}
!2563 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2564, size: 64)
!2564 = !DIDerivedType(tag: DW_TAG_typedef, name: "const_iterator", scope: !2490, file: !1786, line: 307, baseType: !2490)
!2565 = !DISubprogram(name: "operator++", linkageName: "_ZNSt19_Bit_const_iteratorppEi", scope: !2490, file: !1786, line: 333, type: !2566, scopeLine: 333, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2566 = !DISubroutineType(types: !2567)
!2567 = !{!2564, !2541, !62}
!2568 = !DISubprogram(name: "operator--", linkageName: "_ZNSt19_Bit_const_iteratormmEv", scope: !2490, file: !1786, line: 341, type: !2561, scopeLine: 341, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2569 = !DISubprogram(name: "operator--", linkageName: "_ZNSt19_Bit_const_iteratormmEi", scope: !2490, file: !1786, line: 348, type: !2566, scopeLine: 348, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2570 = !DISubprogram(name: "operator+=", linkageName: "_ZNSt19_Bit_const_iteratorpLEl", scope: !2490, file: !1786, line: 356, type: !2571, scopeLine: 356, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2571 = !DISubroutineType(types: !2572)
!2572 = !{!2563, !2541, !2573}
!2573 = !DIDerivedType(tag: DW_TAG_typedef, name: "difference_type", scope: !2496, file: !429, line: 125, baseType: !455)
!2574 = !DISubprogram(name: "operator-=", linkageName: "_ZNSt19_Bit_const_iteratormIEl", scope: !2490, file: !1786, line: 363, type: !2571, scopeLine: 363, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2575 = !DISubprogram(name: "operator+", linkageName: "_ZNKSt19_Bit_const_iteratorplEl", scope: !2490, file: !1786, line: 370, type: !2576, scopeLine: 370, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2576 = !DISubroutineType(types: !2577)
!2577 = !{!2564, !2554, !2573}
!2578 = !DISubprogram(name: "operator-", linkageName: "_ZNKSt19_Bit_const_iteratormiEl", scope: !2490, file: !1786, line: 377, type: !2576, scopeLine: 377, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2579 = !DISubprogram(name: "operator[]", linkageName: "_ZNKSt19_Bit_const_iteratorixEl", scope: !2490, file: !1786, line: 384, type: !2580, scopeLine: 384, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2580 = !DISubroutineType(types: !2581)
!2581 = !{!2559, !2554, !2573}
!2582 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Bit_reference", scope: !91, file: !1786, line: 72, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2583, identifier: "_ZTSSt14_Bit_reference")
!2583 = !{!2584, !2585, !2586, !2590, !2593, !2598, !2602, !2606, !2609, !2610}
!2584 = !DIDerivedType(tag: DW_TAG_member, name: "_M_p", scope: !2582, file: !1786, line: 74, baseType: !2513, size: 64)
!2585 = !DIDerivedType(tag: DW_TAG_member, name: "_M_mask", scope: !2582, file: !1786, line: 75, baseType: !2514, size: 64, offset: 64)
!2586 = !DISubprogram(name: "_Bit_reference", scope: !2582, file: !1786, line: 77, type: !2587, scopeLine: 77, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2587 = !DISubroutineType(types: !2588)
!2588 = !{null, !2589, !2513, !2514}
!2589 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2582, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2590 = !DISubprogram(name: "_Bit_reference", scope: !2582, file: !1786, line: 80, type: !2591, scopeLine: 80, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2591 = !DISubroutineType(types: !2592)
!2592 = !{null, !2589}
!2593 = !DISubprogram(name: "operator bool", linkageName: "_ZNKSt14_Bit_referencecvbEv", scope: !2582, file: !1786, line: 82, type: !2594, scopeLine: 82, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2594 = !DISubroutineType(types: !2595)
!2595 = !{!46, !2596}
!2596 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2597, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2597 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2582)
!2598 = !DISubprogram(name: "operator=", linkageName: "_ZNSt14_Bit_referenceaSEb", scope: !2582, file: !1786, line: 86, type: !2599, scopeLine: 86, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2599 = !DISubroutineType(types: !2600)
!2600 = !{!2601, !2589, !46}
!2601 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2582, size: 64)
!2602 = !DISubprogram(name: "operator=", linkageName: "_ZNSt14_Bit_referenceaSERKS_", scope: !2582, file: !1786, line: 96, type: !2603, scopeLine: 96, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2603 = !DISubroutineType(types: !2604)
!2604 = !{!2601, !2589, !2605}
!2605 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2597, size: 64)
!2606 = !DISubprogram(name: "operator==", linkageName: "_ZNKSt14_Bit_referenceeqERKS_", scope: !2582, file: !1786, line: 100, type: !2607, scopeLine: 100, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2607 = !DISubroutineType(types: !2608)
!2608 = !{!46, !2596, !2605}
!2609 = !DISubprogram(name: "operator<", linkageName: "_ZNKSt14_Bit_referenceltERKS_", scope: !2582, file: !1786, line: 104, type: !2607, scopeLine: 104, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2610 = !DISubprogram(name: "flip", linkageName: "_ZNSt14_Bit_reference4flipEv", scope: !2582, file: !1786, line: 108, type: !2591, scopeLine: 108, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2611 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "MacroExpansion", scope: !14, file: !12, line: 158, size: 192, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2612, identifier: "_ZTSN5clang14MacroExpansionE")
!2612 = !{!2613, !2614, !2658, !2662, !2665, !2670, !2673, !2676}
!2613 = !DIDerivedType(tag: DW_TAG_inheritance, scope: !2611, baseType: !20, flags: DIFlagPublic, extraData: i32 0)
!2614 = !DIDerivedType(tag: DW_TAG_member, name: "NameOrDef", scope: !2611, file: !12, line: 161, baseType: !2615, size: 64, offset: 128)
!2615 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "PointerUnion<clang::IdentifierInfo *, clang::MacroDefinition *>", scope: !80, file: !2109, line: 80, size: 64, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2616, templateParams: !2116, identifier: "_ZTSN4llvm12PointerUnionIPN5clang14IdentifierInfoEPNS1_15MacroDefinitionEEE")
!2616 = !{!2617, !2619, !2623, !2626, !2629, !2634, !2635, !2640, !2644, !2649, !2652, !2655}
!2617 = !DIDerivedType(tag: DW_TAG_member, name: "Val", scope: !2615, file: !2109, line: 85, baseType: !2618, size: 64)
!2618 = !DIDerivedType(tag: DW_TAG_typedef, name: "ValTy", scope: !2615, file: !2109, line: 83, baseType: !2126)
!2619 = !DISubprogram(name: "PointerUnion", scope: !2615, file: !2109, line: 97, type: !2620, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2620 = !DISubroutineType(types: !2621)
!2621 = !{null, !2622}
!2622 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2615, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2623 = !DISubprogram(name: "PointerUnion", scope: !2615, file: !2109, line: 99, type: !2624, scopeLine: 99, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2624 = !DISubroutineType(types: !2625)
!2625 = !{null, !2622, !2118}
!2626 = !DISubprogram(name: "PointerUnion", scope: !2615, file: !2109, line: 102, type: !2627, scopeLine: 102, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2627 = !DISubroutineType(types: !2628)
!2628 = !{null, !2622, !739}
!2629 = !DISubprogram(name: "isNull", linkageName: "_ZNK4llvm12PointerUnionIPN5clang14IdentifierInfoEPNS1_15MacroDefinitionEE6isNullEv", scope: !2615, file: !2109, line: 108, type: !2630, scopeLine: 108, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2630 = !DISubroutineType(types: !2631)
!2631 = !{!46, !2632}
!2632 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2633, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2633 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2615)
!2634 = !DISubprogram(name: "operator bool", linkageName: "_ZNK4llvm12PointerUnionIPN5clang14IdentifierInfoEPNS1_15MacroDefinitionEEcvbEv", scope: !2615, file: !2109, line: 113, type: !2630, scopeLine: 113, flags: DIFlagPublic | DIFlagExplicit | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2635 = !DISubprogram(name: "getAddrOfPtr1", linkageName: "_ZNK4llvm12PointerUnionIPN5clang14IdentifierInfoEPNS1_15MacroDefinitionEE13getAddrOfPtr1Ev", scope: !2615, file: !2109, line: 144, type: !2636, scopeLine: 144, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2636 = !DISubroutineType(types: !2637)
!2637 = !{!2638, !2632}
!2638 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2639, size: 64)
!2639 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2118)
!2640 = !DISubprogram(name: "getAddrOfPtr1", linkageName: "_ZN4llvm12PointerUnionIPN5clang14IdentifierInfoEPNS1_15MacroDefinitionEE13getAddrOfPtr1Ev", scope: !2615, file: !2109, line: 150, type: !2641, scopeLine: 150, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2641 = !DISubroutineType(types: !2642)
!2642 = !{!2643, !2622}
!2643 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2118, size: 64)
!2644 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm12PointerUnionIPN5clang14IdentifierInfoEPNS1_15MacroDefinitionEEaSERKS3_", scope: !2615, file: !2109, line: 159, type: !2645, scopeLine: 159, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2645 = !DISubroutineType(types: !2646)
!2646 = !{!2647, !2622, !2648}
!2647 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2633, size: 64)
!2648 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2639, size: 64)
!2649 = !DISubprogram(name: "operator=", linkageName: "_ZN4llvm12PointerUnionIPN5clang14IdentifierInfoEPNS1_15MacroDefinitionEEaSERKS5_", scope: !2615, file: !2109, line: 164, type: !2650, scopeLine: 164, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2650 = !DISubroutineType(types: !2651)
!2651 = !{!2647, !2622, !1024}
!2652 = !DISubprogram(name: "getOpaqueValue", linkageName: "_ZNK4llvm12PointerUnionIPN5clang14IdentifierInfoEPNS1_15MacroDefinitionEE14getOpaqueValueEv", scope: !2615, file: !2109, line: 171, type: !2653, scopeLine: 171, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2653 = !DISubroutineType(types: !2654)
!2654 = !{!68, !2632}
!2655 = !DISubprogram(name: "getFromOpaqueValue", linkageName: "_ZN4llvm12PointerUnionIPN5clang14IdentifierInfoEPNS1_15MacroDefinitionEE18getFromOpaqueValueEPv", scope: !2615, file: !2109, line: 172, type: !2656, scopeLine: 172, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2656 = !DISubroutineType(types: !2657)
!2657 = !{!2615, !68}
!2658 = !DISubprogram(name: "MacroExpansion", scope: !2611, file: !12, line: 164, type: !2659, scopeLine: 164, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2659 = !DISubroutineType(types: !2660)
!2660 = !{null, !2661, !2118, !32}
!2661 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2611, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2662 = !DISubprogram(name: "MacroExpansion", scope: !2611, file: !12, line: 168, type: !2663, scopeLine: 168, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2663 = !DISubroutineType(types: !2664)
!2664 = !{null, !2661, !739, !32}
!2665 = !DISubprogram(name: "isBuiltinMacro", linkageName: "_ZNK5clang14MacroExpansion14isBuiltinMacroEv", scope: !2611, file: !12, line: 173, type: !2666, scopeLine: 173, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2666 = !DISubroutineType(types: !2667)
!2667 = !{!46, !2668}
!2668 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2669, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2669 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2611)
!2670 = !DISubprogram(name: "getName", linkageName: "_ZNK5clang14MacroExpansion7getNameEv", scope: !2611, file: !12, line: 176, type: !2671, scopeLine: 176, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2671 = !DISubroutineType(types: !2672)
!2672 = !{!744, !2668}
!2673 = !DISubprogram(name: "getDefinition", linkageName: "_ZNK5clang14MacroExpansion13getDefinitionEv", scope: !2611, file: !12, line: 184, type: !2674, scopeLine: 184, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2674 = !DISubroutineType(types: !2675)
!2675 = !{!739, !2668}
!2676 = !DISubprogram(name: "classof", linkageName: "_ZN5clang14MacroExpansion7classofEPKNS_18PreprocessedEntityE", scope: !2611, file: !12, line: 189, type: !761, scopeLine: 189, flags: DIFlagPublic | DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!2677 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ArrayRef<std::pair<clang::IdentifierInfo *, clang::SourceLocation> >", scope: !80, file: !2678, line: 31, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2679, templateParams: !2752, identifier: "_ZTSN4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEEE")
!2678 = !DIFile(filename: "llvm34/include/llvm/ADT/ArrayRef.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "6317ba9f99cd1980a6299fb308b36f31")
!2679 = !{!2680, !2684, !2686, !2690, !2693, !2697, !2700, !2703, !2709, !2715, !2716, !2721, !2722, !2725, !2728, !2731, !2734, !2735, !2738, !2741, !2744, !2747, !2751}
!2680 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !2677, file: !2678, line: 41, baseType: !2681, size: 64)
!2681 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2682, size: 64)
!2682 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2683)
!2683 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "pair<clang::IdentifierInfo *, clang::SourceLocation>", scope: !91, file: !713, line: 208, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt4pairIPN5clang14IdentifierInfoENS0_14SourceLocationEE")
!2684 = !DIDerivedType(tag: DW_TAG_member, name: "Length", scope: !2677, file: !2678, line: 44, baseType: !2685, size: 64, offset: 64)
!2685 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_type", file: !2678, line: 35, baseType: !143)
!2686 = !DISubprogram(name: "ArrayRef", scope: !2677, file: !2678, line: 51, type: !2687, scopeLine: 51, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2687 = !DISubroutineType(types: !2688)
!2688 = !{null, !2689}
!2689 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2677, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2690 = !DISubprogram(name: "ArrayRef", scope: !2677, file: !2678, line: 54, type: !2691, scopeLine: 54, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2691 = !DISubroutineType(types: !2692)
!2692 = !{null, !2689, !1199}
!2693 = !DISubprogram(name: "ArrayRef", scope: !2677, file: !2678, line: 57, type: !2694, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2694 = !DISubroutineType(types: !2695)
!2695 = !{null, !2689, !2696}
!2696 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2682, size: 64)
!2697 = !DISubprogram(name: "ArrayRef", scope: !2677, file: !2678, line: 61, type: !2698, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2698 = !DISubroutineType(types: !2699)
!2699 = !{null, !2689, !2681, !143}
!2700 = !DISubprogram(name: "ArrayRef", scope: !2677, file: !2678, line: 65, type: !2701, scopeLine: 65, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2701 = !DISubroutineType(types: !2702)
!2702 = !{null, !2689, !2681, !2681}
!2703 = !DISubprogram(name: "ArrayRef", scope: !2677, file: !2678, line: 88, type: !2704, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2704 = !DISubroutineType(types: !2705)
!2705 = !{null, !2689, !2706}
!2706 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2707, size: 64)
!2707 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2708)
!2708 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<std::pair<clang::IdentifierInfo *, clang::SourceLocation> >", scope: !91, file: !389, line: 47, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listISt4pairIPN5clang14IdentifierInfoENS1_14SourceLocationEEE")
!2709 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEE5beginEv", scope: !2677, file: !2678, line: 97, type: !2710, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2710 = !DISubroutineType(types: !2711)
!2711 = !{!2712, !2713}
!2712 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2677, file: !2678, line: 33, baseType: !2681)
!2713 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2714, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2714 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2677)
!2715 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEE3endEv", scope: !2677, file: !2678, line: 98, type: !2710, scopeLine: 98, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2716 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEE6rbeginEv", scope: !2677, file: !2678, line: 100, type: !2717, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2717 = !DISubroutineType(types: !2718)
!2718 = !{!2719, !2713}
!2719 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !2677, file: !2678, line: 37, baseType: !2720)
!2720 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const std::pair<clang::IdentifierInfo *, clang::SourceLocation> *>", scope: !91, file: !412, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKSt4pairIPN5clang14IdentifierInfoENS1_14SourceLocationEEE")
!2721 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEE4rendEv", scope: !2677, file: !2678, line: 101, type: !2717, scopeLine: 101, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2722 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEE5emptyEv", scope: !2677, file: !2678, line: 104, type: !2723, scopeLine: 104, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2723 = !DISubroutineType(types: !2724)
!2724 = !{!46, !2713}
!2725 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEE4dataEv", scope: !2677, file: !2678, line: 106, type: !2726, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2726 = !DISubroutineType(types: !2727)
!2727 = !{!2681, !2713}
!2728 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEE4sizeEv", scope: !2677, file: !2678, line: 109, type: !2729, scopeLine: 109, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2729 = !DISubroutineType(types: !2730)
!2730 = !{!143, !2713}
!2731 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEE5frontEv", scope: !2677, file: !2678, line: 112, type: !2732, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2732 = !DISubroutineType(types: !2733)
!2733 = !{!2696, !2713}
!2734 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEE4backEv", scope: !2677, file: !2678, line: 118, type: !2732, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2735 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEE6equalsES7_", scope: !2677, file: !2678, line: 124, type: !2736, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2736 = !DISubroutineType(types: !2737)
!2737 = !{!46, !2713, !2677}
!2738 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEE5sliceEj", scope: !2677, file: !2678, line: 134, type: !2739, scopeLine: 134, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2739 = !DISubroutineType(types: !2740)
!2740 = !{!2677, !2713, !6}
!2741 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEE5sliceEjj", scope: !2677, file: !2678, line: 141, type: !2742, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2742 = !DISubroutineType(types: !2743)
!2743 = !{!2677, !2713, !6, !6}
!2744 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEEixEm", scope: !2677, file: !2678, line: 149, type: !2745, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2745 = !DISubroutineType(types: !2746)
!2746 = !{!2696, !2713, !143}
!2747 = !DISubprogram(name: "vec", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEE3vecEv", scope: !2677, file: !2678, line: 157, type: !2748, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2748 = !DISubroutineType(types: !2749)
!2749 = !{!2750, !2713}
!2750 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<std::pair<clang::IdentifierInfo *, clang::SourceLocation>, std::allocator<std::pair<clang::IdentifierInfo *, clang::SourceLocation> > >", scope: !91, file: !159, line: 339, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt6vectorISt4pairIPN5clang14IdentifierInfoENS1_14SourceLocationEESaIS5_EE")
!2751 = !DISubprogram(name: "operator vector", linkageName: "_ZNK4llvm8ArrayRefISt4pairIPN5clang14IdentifierInfoENS2_14SourceLocationEEEcvSt6vectorIS6_SaIS6_EEEv", scope: !2677, file: !2678, line: 164, type: !2748, scopeLine: 164, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2752 = !{!2753}
!2753 = !DITemplateTypeParameter(name: "T", type: !2683)
!2754 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ArrayRef<int>", scope: !80, file: !2678, line: 31, size: 128, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2755, templateParams: !2826, identifier: "_ZTSN4llvm8ArrayRefIiEE")
!2755 = !{!2756, !2759, !2760, !2764, !2767, !2771, !2774, !2777, !2783, !2789, !2790, !2795, !2796, !2799, !2802, !2805, !2808, !2809, !2812, !2815, !2818, !2821, !2825}
!2756 = !DIDerivedType(tag: DW_TAG_member, name: "Data", scope: !2754, file: !2678, line: 41, baseType: !2757, size: 64)
!2757 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2758, size: 64)
!2758 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !62)
!2759 = !DIDerivedType(tag: DW_TAG_member, name: "Length", scope: !2754, file: !2678, line: 44, baseType: !2685, size: 64, offset: 64)
!2760 = !DISubprogram(name: "ArrayRef", scope: !2754, file: !2678, line: 51, type: !2761, scopeLine: 51, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2761 = !DISubroutineType(types: !2762)
!2762 = !{null, !2763}
!2763 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2754, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2764 = !DISubprogram(name: "ArrayRef", scope: !2754, file: !2678, line: 54, type: !2765, scopeLine: 54, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2765 = !DISubroutineType(types: !2766)
!2766 = !{null, !2763, !1199}
!2767 = !DISubprogram(name: "ArrayRef", scope: !2754, file: !2678, line: 57, type: !2768, scopeLine: 57, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2768 = !DISubroutineType(types: !2769)
!2769 = !{null, !2763, !2770}
!2770 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2758, size: 64)
!2771 = !DISubprogram(name: "ArrayRef", scope: !2754, file: !2678, line: 61, type: !2772, scopeLine: 61, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2772 = !DISubroutineType(types: !2773)
!2773 = !{null, !2763, !2757, !143}
!2774 = !DISubprogram(name: "ArrayRef", scope: !2754, file: !2678, line: 65, type: !2775, scopeLine: 65, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2775 = !DISubroutineType(types: !2776)
!2776 = !{null, !2763, !2757, !2757}
!2777 = !DISubprogram(name: "ArrayRef", scope: !2754, file: !2678, line: 88, type: !2778, scopeLine: 88, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2778 = !DISubroutineType(types: !2779)
!2779 = !{null, !2763, !2780}
!2780 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !2781, size: 64)
!2781 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2782)
!2782 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "initializer_list<int>", scope: !91, file: !389, line: 47, size: 128, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16initializer_listIiE")
!2783 = !DISubprogram(name: "begin", linkageName: "_ZNK4llvm8ArrayRefIiE5beginEv", scope: !2754, file: !2678, line: 97, type: !2784, scopeLine: 97, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2784 = !DISubroutineType(types: !2785)
!2785 = !{!2786, !2787}
!2786 = !DIDerivedType(tag: DW_TAG_typedef, name: "iterator", scope: !2754, file: !2678, line: 33, baseType: !2757)
!2787 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2788, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2788 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !2754)
!2789 = !DISubprogram(name: "end", linkageName: "_ZNK4llvm8ArrayRefIiE3endEv", scope: !2754, file: !2678, line: 98, type: !2784, scopeLine: 98, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2790 = !DISubprogram(name: "rbegin", linkageName: "_ZNK4llvm8ArrayRefIiE6rbeginEv", scope: !2754, file: !2678, line: 100, type: !2791, scopeLine: 100, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2791 = !DISubroutineType(types: !2792)
!2792 = !{!2793, !2787}
!2793 = !DIDerivedType(tag: DW_TAG_typedef, name: "reverse_iterator", scope: !2754, file: !2678, line: 37, baseType: !2794)
!2794 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "reverse_iterator<const int *>", scope: !91, file: !412, line: 101, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt16reverse_iteratorIPKiE")
!2795 = !DISubprogram(name: "rend", linkageName: "_ZNK4llvm8ArrayRefIiE4rendEv", scope: !2754, file: !2678, line: 101, type: !2791, scopeLine: 101, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2796 = !DISubprogram(name: "empty", linkageName: "_ZNK4llvm8ArrayRefIiE5emptyEv", scope: !2754, file: !2678, line: 104, type: !2797, scopeLine: 104, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2797 = !DISubroutineType(types: !2798)
!2798 = !{!46, !2787}
!2799 = !DISubprogram(name: "data", linkageName: "_ZNK4llvm8ArrayRefIiE4dataEv", scope: !2754, file: !2678, line: 106, type: !2800, scopeLine: 106, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2800 = !DISubroutineType(types: !2801)
!2801 = !{!2757, !2787}
!2802 = !DISubprogram(name: "size", linkageName: "_ZNK4llvm8ArrayRefIiE4sizeEv", scope: !2754, file: !2678, line: 109, type: !2803, scopeLine: 109, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2803 = !DISubroutineType(types: !2804)
!2804 = !{!143, !2787}
!2805 = !DISubprogram(name: "front", linkageName: "_ZNK4llvm8ArrayRefIiE5frontEv", scope: !2754, file: !2678, line: 112, type: !2806, scopeLine: 112, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2806 = !DISubroutineType(types: !2807)
!2807 = !{!2770, !2787}
!2808 = !DISubprogram(name: "back", linkageName: "_ZNK4llvm8ArrayRefIiE4backEv", scope: !2754, file: !2678, line: 118, type: !2806, scopeLine: 118, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2809 = !DISubprogram(name: "equals", linkageName: "_ZNK4llvm8ArrayRefIiE6equalsES1_", scope: !2754, file: !2678, line: 124, type: !2810, scopeLine: 124, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2810 = !DISubroutineType(types: !2811)
!2811 = !{!46, !2787, !2754}
!2812 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefIiE5sliceEj", scope: !2754, file: !2678, line: 134, type: !2813, scopeLine: 134, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2813 = !DISubroutineType(types: !2814)
!2814 = !{!2754, !2787, !6}
!2815 = !DISubprogram(name: "slice", linkageName: "_ZNK4llvm8ArrayRefIiE5sliceEjj", scope: !2754, file: !2678, line: 141, type: !2816, scopeLine: 141, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2816 = !DISubroutineType(types: !2817)
!2817 = !{!2754, !2787, !6, !6}
!2818 = !DISubprogram(name: "operator[]", linkageName: "_ZNK4llvm8ArrayRefIiEixEm", scope: !2754, file: !2678, line: 149, type: !2819, scopeLine: 149, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2819 = !DISubroutineType(types: !2820)
!2820 = !{!2770, !2787, !143}
!2821 = !DISubprogram(name: "vec", linkageName: "_ZNK4llvm8ArrayRefIiE3vecEv", scope: !2754, file: !2678, line: 157, type: !2822, scopeLine: 157, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2822 = !DISubroutineType(types: !2823)
!2823 = !{!2824, !2787}
!2824 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "vector<int, std::allocator<int> >", scope: !91, file: !159, line: 339, size: 192, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSSt6vectorIiSaIiEE")
!2825 = !DISubprogram(name: "operator vector", linkageName: "_ZNK4llvm8ArrayRefIiEcvSt6vectorIiSaIiEEEv", scope: !2754, file: !2678, line: 164, type: !2822, scopeLine: 164, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2826 = !{!2827}
!2827 = !DITemplateTypeParameter(name: "T", type: !62)
!2828 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_Temporary_value", scope: !158, file: !159, line: 1589, size: 128, flags: DIFlagProtected | DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2829, identifier: "_ZTSNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE16_Temporary_valueE")
!2829 = !{!2830, !2832, !2846, !2850, !2854}
!2830 = !DIDerivedType(tag: DW_TAG_member, name: "_M_this", scope: !2828, file: !159, line: 1609, baseType: !2831, size: 64, flags: DIFlagPrivate)
!2831 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !158, size: 64)
!2832 = !DIDerivedType(tag: DW_TAG_member, name: "__buf", scope: !2828, file: !159, line: 1610, baseType: !2833, size: 64, offset: 64, flags: DIFlagPrivate)
!2833 = distinct !DICompositeType(tag: DW_TAG_union_type, name: "type", scope: !2834, file: !656, line: 1802, size: 64, flags: DIFlagTypePassByValue, elements: !2838, identifier: "_ZTSNSt15aligned_storageILm8ELm8EE4typeE")
!2834 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "aligned_storage<8UL, 8UL>", scope: !91, file: !656, line: 1800, size: 8, flags: DIFlagTypePassByValue, elements: !279, templateParams: !2835, identifier: "_ZTSSt15aligned_storageILm8ELm8EE")
!2835 = !{!2836, !2837}
!2836 = !DITemplateValueParameter(name: "_Len", type: !145, value: i64 8)
!2837 = !DITemplateValueParameter(name: "_Align", type: !145, value: i64 8)
!2838 = !{!2839, !2844}
!2839 = !DIDerivedType(tag: DW_TAG_member, name: "__data", scope: !2833, file: !656, line: 1804, baseType: !2840, size: 64)
!2840 = !DICompositeType(tag: DW_TAG_array_type, baseType: !2841, size: 64, elements: !2842)
!2841 = !DIBasicType(name: "unsigned char", size: 8, encoding: DW_ATE_unsigned_char)
!2842 = !{!2843}
!2843 = !DISubrange(count: 8)
!2844 = !DIDerivedType(tag: DW_TAG_member, name: "__align", scope: !2833, file: !656, line: 1805, baseType: !2845, size: 64, align: 64)
!2845 = distinct !DICompositeType(tag: DW_TAG_structure_type, scope: !2833, file: !656, line: 1805, size: 64, align: 64, flags: DIFlagTypePassByValue, elements: !279, identifier: "_ZTSNSt15aligned_storageILm8ELm8EE4typeUt_E")
!2846 = !DISubprogram(name: "~_Temporary_value", scope: !2828, file: !159, line: 1599, type: !2847, scopeLine: 1599, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2847 = !DISubroutineType(types: !2848)
!2848 = !{null, !2849}
!2849 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2828, size: 64, flags: DIFlagArtificial | DIFlagObjectPointer)
!2850 = !DISubprogram(name: "_M_val", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE16_Temporary_value6_M_valEv", scope: !2828, file: !159, line: 1603, type: !2851, scopeLine: 1603, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2851 = !DISubroutineType(types: !2852)
!2852 = !{!2853, !2849}
!2853 = !DIDerivedType(tag: DW_TAG_reference_type, baseType: !369, size: 64)
!2854 = !DISubprogram(name: "_M_ptr", linkageName: "_ZNSt6vectorIPN5clang18PreprocessedEntityESaIS2_EE16_Temporary_value6_M_ptrEv", scope: !2828, file: !159, line: 1607, type: !2855, scopeLine: 1607, flags: DIFlagPrivate | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!2855 = !DISubroutineType(types: !2856)
!2856 = !{!182, !2849}
!2857 = !{!2858, !2863, !2868, !2873, !2878, !2883, !2888, !2893, !2895, !2900, !2905, !2910, !2915, !2917, !2922, !2924, !2929, !2934, !2939, !2944, !2949, !2954, !2959, !2964, !2969, !2974, !2976, !2981, !2986, !2991, !2996, !3001, !3006, !3011, !3016, !3021, !3026, !3031, !3036, !3038, !3043, !3048, !3053, !3058, !3060, !3065, !3070, !3072, !3077, !3082, !3087, !3092, !3097, !3102, !3107, !3109, !3114, !3116, !3121, !3123, !3125, !3127, !3129, !3131, !3133, !3135, !3140, !3142, !3147, !3149, !3155, !3160, !3162, !3167, !3173, !3175, !3177, !3182, !3187, !3192, !3197, !3200, !3205, !3210, !3215}
!2858 = !DIGlobalVariableExpression(var: !2859, expr: !DIExpression())
!2859 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 96, type: !2860, isLocal: true, isDefinition: true)
!2860 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 384, elements: !2861)
!2861 = !{!2862}
!2862 = !DISubrange(count: 48)
!2863 = !DIGlobalVariableExpression(var: !2864, expr: !DIExpression())
!2864 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 96, type: !2865, isLocal: true, isDefinition: true)
!2865 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 504, elements: !2866)
!2866 = !{!2867}
!2867 = !DISubrange(count: 63)
!2868 = !DIGlobalVariableExpression(var: !2869, expr: !DIExpression())
!2869 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 96, type: !2870, isLocal: true, isDefinition: true)
!2870 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 824, elements: !2871)
!2871 = !{!2872}
!2872 = !DISubrange(count: 103)
!2873 = !DIGlobalVariableExpression(var: !2874, expr: !DIExpression())
!2874 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 99, type: !2875, isLocal: true, isDefinition: true)
!2875 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 256, elements: !2876)
!2876 = !{!2877}
!2877 = !DISubrange(count: 32)
!2878 = !DIGlobalVariableExpression(var: !2879, expr: !DIExpression())
!2879 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 99, type: !2880, isLocal: true, isDefinition: true)
!2880 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 416, elements: !2881)
!2881 = !{!2882}
!2882 = !DISubrange(count: 52)
!2883 = !DIGlobalVariableExpression(var: !2884, expr: !DIExpression())
!2884 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 119, type: !2885, isLocal: true, isDefinition: true)
!2885 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 376, elements: !2886)
!2886 = !{!2887}
!2887 = !DISubrange(count: 47)
!2888 = !DIGlobalVariableExpression(var: !2889, expr: !DIExpression())
!2889 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 130, type: !2890, isLocal: true, isDefinition: true)
!2890 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 128, elements: !2891)
!2891 = !{!2892}
!2892 = !DISubrange(count: 16)
!2893 = !DIGlobalVariableExpression(var: !2894, expr: !DIExpression())
!2894 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 130, type: !2870, isLocal: true, isDefinition: true)
!2895 = !DIGlobalVariableExpression(var: !2896, expr: !DIExpression())
!2896 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 131, type: !2897, isLocal: true, isDefinition: true)
!2897 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 560, elements: !2898)
!2898 = !{!2899}
!2899 = !DISubrange(count: 70)
!2900 = !DIGlobalVariableExpression(var: !2901, expr: !DIExpression())
!2901 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 163, type: !2902, isLocal: true, isDefinition: true)
!2902 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 1032, elements: !2903)
!2903 = !{!2904}
!2904 = !DISubrange(count: 129)
!2905 = !DIGlobalVariableExpression(var: !2906, expr: !DIExpression())
!2906 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 248, type: !2907, isLocal: true, isDefinition: true)
!2907 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 56, elements: !2908)
!2908 = !{!2909}
!2909 = !DISubrange(count: 7)
!2910 = !DIGlobalVariableExpression(var: !2911, expr: !DIExpression())
!2911 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 248, type: !2912, isLocal: true, isDefinition: true)
!2912 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 888, elements: !2913)
!2913 = !{!2914}
!2914 = !DISubrange(count: 111)
!2915 = !DIGlobalVariableExpression(var: !2916, expr: !DIExpression())
!2916 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 252, type: !2860, isLocal: true, isDefinition: true)
!2917 = !DIGlobalVariableExpression(var: !2918, expr: !DIExpression())
!2918 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 252, type: !2919, isLocal: true, isDefinition: true)
!2919 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 1536, elements: !2920)
!2920 = !{!2921}
!2921 = !DISubrange(count: 192)
!2922 = !DIGlobalVariableExpression(var: !2923, expr: !DIExpression())
!2923 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 310, type: !2880, isLocal: true, isDefinition: true)
!2924 = !DIGlobalVariableExpression(var: !2925, expr: !DIExpression())
!2925 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 310, type: !2926, isLocal: true, isDefinition: true)
!2926 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 584, elements: !2927)
!2927 = !{!2928}
!2928 = !DISubrange(count: 73)
!2929 = !DIGlobalVariableExpression(var: !2930, expr: !DIExpression())
!2930 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 310, type: !2931, isLocal: true, isDefinition: true)
!2931 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 760, elements: !2932)
!2932 = !{!2933}
!2933 = !DISubrange(count: 95)
!2934 = !DIGlobalVariableExpression(var: !2935, expr: !DIExpression())
!2935 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 331, type: !2936, isLocal: true, isDefinition: true)
!2936 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 328, elements: !2937)
!2937 = !{!2938}
!2938 = !DISubrange(count: 41)
!2939 = !DIGlobalVariableExpression(var: !2940, expr: !DIExpression())
!2940 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 331, type: !2941, isLocal: true, isDefinition: true)
!2941 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 704, elements: !2942)
!2942 = !{!2943}
!2943 = !DISubrange(count: 88)
!2944 = !DIGlobalVariableExpression(var: !2945, expr: !DIExpression())
!2945 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 331, type: !2946, isLocal: true, isDefinition: true)
!2946 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 936, elements: !2947)
!2947 = !{!2948}
!2948 = !DISubrange(count: 117)
!2949 = !DIGlobalVariableExpression(var: !2950, expr: !DIExpression())
!2950 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 339, type: !2951, isLocal: true, isDefinition: true)
!2951 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 320, elements: !2952)
!2952 = !{!2953}
!2953 = !DISubrange(count: 40)
!2954 = !DIGlobalVariableExpression(var: !2955, expr: !DIExpression())
!2955 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 339, type: !2956, isLocal: true, isDefinition: true)
!2956 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 648, elements: !2957)
!2957 = !{!2958}
!2958 = !DISubrange(count: 81)
!2959 = !DIGlobalVariableExpression(var: !2960, expr: !DIExpression())
!2960 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 347, type: !2961, isLocal: true, isDefinition: true)
!2961 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 776, elements: !2962)
!2962 = !{!2963}
!2963 = !DISubrange(count: 97)
!2964 = !DIGlobalVariableExpression(var: !2965, expr: !DIExpression())
!2965 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 462, type: !2966, isLocal: true, isDefinition: true)
!2966 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 248, elements: !2967)
!2967 = !{!2968}
!2968 = !DISubrange(count: 31)
!2969 = !DIGlobalVariableExpression(var: !2970, expr: !DIExpression())
!2970 = distinct !DIGlobalVariable(scope: null, file: !1521, line: 85, type: !2971, isLocal: true, isDefinition: true)
!2971 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 544, elements: !2972)
!2972 = !{!2973}
!2973 = !DISubrange(count: 68)
!2974 = !DIGlobalVariableExpression(var: !2975, expr: !DIExpression())
!2975 = distinct !DIGlobalVariable(scope: null, file: !1521, line: 85, type: !2931, isLocal: true, isDefinition: true)
!2976 = !DIGlobalVariableExpression(var: !2977, expr: !DIExpression())
!2977 = distinct !DIGlobalVariable(scope: null, file: !1521, line: 85, type: !2978, isLocal: true, isDefinition: true)
!2978 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 360, elements: !2979)
!2979 = !{!2980}
!2980 = !DISubrange(count: 45)
!2981 = !DIGlobalVariableExpression(var: !2982, expr: !DIExpression())
!2982 = distinct !DIGlobalVariable(scope: null, file: !1521, line: 85, type: !2983, isLocal: true, isDefinition: true)
!2983 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 392, elements: !2984)
!2984 = !{!2985}
!2985 = !DISubrange(count: 49)
!2986 = !DIGlobalVariableExpression(var: !2987, expr: !DIExpression())
!2987 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 68, type: !2988, isLocal: true, isDefinition: true)
!2988 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 136, elements: !2989)
!2989 = !{!2990}
!2990 = !DISubrange(count: 17)
!2991 = !DIGlobalVariableExpression(var: !2992, expr: !DIExpression())
!2992 = distinct !DIGlobalVariable(scope: null, file: !2238, line: 68, type: !2993, isLocal: true, isDefinition: true)
!2993 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 832, elements: !2994)
!2994 = !{!2995}
!2995 = !DISubrange(count: 104)
!2996 = !DIGlobalVariableExpression(var: !2997, expr: !DIExpression())
!2997 = distinct !DIGlobalVariable(scope: null, file: !84, line: 1565, type: !2998, isLocal: true, isDefinition: true)
!2998 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 224, elements: !2999)
!2999 = !{!3000}
!3000 = !DISubrange(count: 28)
!3001 = !DIGlobalVariableExpression(var: !3002, expr: !DIExpression())
!3002 = distinct !DIGlobalVariable(scope: null, file: !84, line: 1565, type: !3003, isLocal: true, isDefinition: true)
!3003 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 336, elements: !3004)
!3004 = !{!3005}
!3005 = !DISubrange(count: 42)
!3006 = !DIGlobalVariableExpression(var: !3007, expr: !DIExpression())
!3007 = distinct !DIGlobalVariable(scope: null, file: !84, line: 1565, type: !3008, isLocal: true, isDefinition: true)
!3008 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 536, elements: !3009)
!3009 = !{!3010}
!3010 = !DISubrange(count: 67)
!3011 = !DIGlobalVariableExpression(var: !3012, expr: !DIExpression())
!3012 = distinct !DIGlobalVariable(scope: null, file: !84, line: 1565, type: !3013, isLocal: true, isDefinition: true)
!3013 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 664, elements: !3014)
!3014 = !{!3015}
!3015 = !DISubrange(count: 83)
!3016 = !DIGlobalVariableExpression(var: !3017, expr: !DIExpression())
!3017 = distinct !DIGlobalVariable(scope: null, file: !84, line: 1489, type: !3018, isLocal: true, isDefinition: true)
!3018 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 112, elements: !3019)
!3019 = !{!3020}
!3020 = !DISubrange(count: 14)
!3021 = !DIGlobalVariableExpression(var: !3022, expr: !DIExpression())
!3022 = distinct !DIGlobalVariable(scope: null, file: !84, line: 1489, type: !3023, isLocal: true, isDefinition: true)
!3023 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 440, elements: !3024)
!3024 = !{!3025}
!3025 = !DISubrange(count: 55)
!3026 = !DIGlobalVariableExpression(var: !3027, expr: !DIExpression())
!3027 = distinct !DIGlobalVariable(scope: null, file: !84, line: 1489, type: !3028, isLocal: true, isDefinition: true)
!3028 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 752, elements: !3029)
!3029 = !{!3030}
!3030 = !DISubrange(count: 94)
!3031 = !DIGlobalVariableExpression(var: !3032, expr: !DIExpression())
!3032 = distinct !DIGlobalVariable(scope: null, file: !2264, line: 140, type: !3033, isLocal: true, isDefinition: true)
!3033 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 176, elements: !3034)
!3034 = !{!3035}
!3035 = !DISubrange(count: 22)
!3036 = !DIGlobalVariableExpression(var: !3037, expr: !DIExpression())
!3037 = distinct !DIGlobalVariable(scope: null, file: !2264, line: 140, type: !2885, isLocal: true, isDefinition: true)
!3038 = !DIGlobalVariableExpression(var: !3039, expr: !DIExpression())
!3039 = distinct !DIGlobalVariable(scope: null, file: !2264, line: 140, type: !3040, isLocal: true, isDefinition: true)
!3040 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 1264, elements: !3041)
!3041 = !{!3042}
!3042 = !DISubrange(count: 158)
!3043 = !DIGlobalVariableExpression(var: !3044, expr: !DIExpression())
!3044 = distinct !DIGlobalVariable(scope: null, file: !84, line: 1479, type: !3045, isLocal: true, isDefinition: true)
!3045 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 432, elements: !3046)
!3046 = !{!3047}
!3047 = !DISubrange(count: 54)
!3048 = !DIGlobalVariableExpression(var: !3049, expr: !DIExpression())
!3049 = distinct !DIGlobalVariable(scope: null, file: !84, line: 1479, type: !3050, isLocal: true, isDefinition: true)
!3050 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 744, elements: !3051)
!3051 = !{!3052}
!3052 = !DISubrange(count: 93)
!3053 = !DIGlobalVariableExpression(var: !3054, expr: !DIExpression())
!3054 = distinct !DIGlobalVariable(scope: null, file: !2264, line: 144, type: !3055, isLocal: true, isDefinition: true)
!3055 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 1360, elements: !3056)
!3056 = !{!3057}
!3057 = !DISubrange(count: 170)
!3058 = !DIGlobalVariableExpression(var: !3059, expr: !DIExpression())
!3059 = distinct !DIGlobalVariable(scope: null, file: !1506, line: 162, type: !2880, isLocal: true, isDefinition: true)
!3060 = !DIGlobalVariableExpression(var: !3061, expr: !DIExpression())
!3061 = distinct !DIGlobalVariable(scope: null, file: !1506, line: 162, type: !3062, isLocal: true, isDefinition: true)
!3062 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 672, elements: !3063)
!3063 = !{!3064}
!3064 = !DISubrange(count: 84)
!3065 = !DIGlobalVariableExpression(var: !3066, expr: !DIExpression())
!3066 = distinct !DIGlobalVariable(scope: null, file: !1506, line: 162, type: !3067, isLocal: true, isDefinition: true)
!3067 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 456, elements: !3068)
!3068 = !{!3069}
!3069 = !DISubrange(count: 57)
!3070 = !DIGlobalVariableExpression(var: !3071, expr: !DIExpression())
!3071 = distinct !DIGlobalVariable(scope: null, file: !1506, line: 162, type: !2865, isLocal: true, isDefinition: true)
!3072 = !DIGlobalVariableExpression(var: !3073, expr: !DIExpression())
!3073 = distinct !DIGlobalVariable(scope: null, file: !1506, line: 164, type: !3074, isLocal: true, isDefinition: true)
!3074 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 352, elements: !3075)
!3075 = !{!3076}
!3076 = !DISubrange(count: 44)
!3077 = !DIGlobalVariableExpression(var: !3078, expr: !DIExpression())
!3078 = distinct !DIGlobalVariable(scope: null, file: !1506, line: 164, type: !3079, isLocal: true, isDefinition: true)
!3079 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 520, elements: !3080)
!3080 = !{!3081}
!3081 = !DISubrange(count: 65)
!3082 = !DIGlobalVariableExpression(var: !3083, expr: !DIExpression())
!3083 = distinct !DIGlobalVariable(scope: null, file: !2125, line: 100, type: !3084, isLocal: true, isDefinition: true)
!3084 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 288, elements: !3085)
!3085 = !{!3086}
!3086 = !DISubrange(count: 36)
!3087 = !DIGlobalVariableExpression(var: !3088, expr: !DIExpression())
!3088 = distinct !DIGlobalVariable(scope: null, file: !2125, line: 100, type: !3089, isLocal: true, isDefinition: true)
!3089 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 800, elements: !3090)
!3090 = !{!3091}
!3091 = !DISubrange(count: 100)
!3092 = !DIGlobalVariableExpression(var: !3093, expr: !DIExpression())
!3093 = distinct !DIGlobalVariable(scope: null, file: !2125, line: 100, type: !3094, isLocal: true, isDefinition: true)
!3094 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 400, elements: !3095)
!3095 = !{!3096}
!3096 = !DISubrange(count: 50)
!3097 = !DIGlobalVariableExpression(var: !3098, expr: !DIExpression())
!3098 = distinct !DIGlobalVariable(scope: null, file: !2125, line: 100, type: !3099, isLocal: true, isDefinition: true)
!3099 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 2360, elements: !3100)
!3100 = !{!3101}
!3101 = !DISubrange(count: 295)
!3102 = !DIGlobalVariableExpression(var: !3103, expr: !DIExpression())
!3103 = distinct !DIGlobalVariable(scope: null, file: !2125, line: 108, type: !3104, isLocal: true, isDefinition: true)
!3104 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 2440, elements: !3105)
!3105 = !{!3106}
!3106 = !DISubrange(count: 305)
!3107 = !DIGlobalVariableExpression(var: !3108, expr: !DIExpression())
!3108 = distinct !DIGlobalVariable(scope: null, file: !2125, line: 111, type: !2998, isLocal: true, isDefinition: true)
!3109 = !DIGlobalVariableExpression(var: !3110, expr: !DIExpression())
!3110 = distinct !DIGlobalVariable(scope: null, file: !2125, line: 111, type: !3111, isLocal: true, isDefinition: true)
!3111 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 464, elements: !3112)
!3112 = !{!3113}
!3113 = !DISubrange(count: 58)
!3114 = !DIGlobalVariableExpression(var: !3115, expr: !DIExpression())
!3115 = distinct !DIGlobalVariable(scope: null, file: !33, line: 134, type: !2890, isLocal: true, isDefinition: true)
!3116 = !DIGlobalVariableExpression(var: !3117, expr: !DIExpression())
!3117 = distinct !DIGlobalVariable(scope: null, file: !33, line: 134, type: !3118, isLocal: true, isDefinition: true)
!3118 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 496, elements: !3119)
!3119 = !{!3120}
!3120 = !DISubrange(count: 62)
!3121 = !DIGlobalVariableExpression(var: !3122, expr: !DIExpression())
!3122 = distinct !DIGlobalVariable(scope: null, file: !33, line: 134, type: !2971, isLocal: true, isDefinition: true)
!3123 = !DIGlobalVariableExpression(var: !3124, expr: !DIExpression())
!3124 = distinct !DIGlobalVariable(scope: null, file: !33, line: 134, type: !2926, isLocal: true, isDefinition: true)
!3125 = !DIGlobalVariableExpression(var: !3126, expr: !DIExpression())
!3126 = distinct !DIGlobalVariable(scope: null, file: !1170, line: 123, type: !2907, isLocal: true, isDefinition: true)
!3127 = !DIGlobalVariableExpression(var: !3128, expr: !DIExpression())
!3128 = distinct !DIGlobalVariable(scope: null, file: !1170, line: 123, type: !3074, isLocal: true, isDefinition: true)
!3129 = !DIGlobalVariableExpression(var: !3130, expr: !DIExpression())
!3130 = distinct !DIGlobalVariable(scope: null, file: !1170, line: 123, type: !3094, isLocal: true, isDefinition: true)
!3131 = !DIGlobalVariableExpression(var: !3132, expr: !DIExpression())
!3132 = distinct !DIGlobalVariable(scope: null, file: !1170, line: 114, type: !2983, isLocal: true, isDefinition: true)
!3133 = !DIGlobalVariableExpression(var: !3134, expr: !DIExpression())
!3134 = distinct !DIGlobalVariable(scope: null, file: !690, line: 271, type: !3003, isLocal: true, isDefinition: true)
!3135 = !DIGlobalVariableExpression(var: !3136, expr: !DIExpression())
!3136 = distinct !DIGlobalVariable(scope: null, file: !690, line: 271, type: !3137, isLocal: true, isDefinition: true)
!3137 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 736, elements: !3138)
!3138 = !{!3139}
!3139 = !DISubrange(count: 92)
!3140 = !DIGlobalVariableExpression(var: !3141, expr: !DIExpression())
!3141 = distinct !DIGlobalVariable(scope: null, file: !690, line: 271, type: !3074, isLocal: true, isDefinition: true)
!3142 = !DIGlobalVariableExpression(var: !3143, expr: !DIExpression())
!3143 = distinct !DIGlobalVariable(scope: null, file: !690, line: 271, type: !3144, isLocal: true, isDefinition: true)
!3144 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 3264, elements: !3145)
!3145 = !{!3146}
!3146 = !DISubrange(count: 408)
!3147 = !DIGlobalVariableExpression(var: !3148, expr: !DIExpression())
!3148 = distinct !DIGlobalVariable(scope: null, file: !1170, line: 116, type: !2983, isLocal: true, isDefinition: true)
!3149 = !DIGlobalVariableExpression(var: !3150, expr: !DIExpression())
!3150 = distinct !DIGlobalVariable(scope: null, file: !3151, line: 97, type: !3152, isLocal: true, isDefinition: true)
!3151 = !DIFile(filename: "llvm34/include/llvm/Support/Casting.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "d66d299dea704124ccd357043ea0e9d5")
!3152 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 232, elements: !3153)
!3153 = !{!3154}
!3154 = !DISubrange(count: 29)
!3155 = !DIGlobalVariableExpression(var: !3156, expr: !DIExpression())
!3156 = distinct !DIGlobalVariable(scope: null, file: !3151, line: 97, type: !3157, isLocal: true, isDefinition: true)
!3157 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 304, elements: !3158)
!3158 = !{!3159}
!3159 = !DISubrange(count: 38)
!3160 = !DIGlobalVariableExpression(var: !3161, expr: !DIExpression())
!3161 = distinct !DIGlobalVariable(scope: null, file: !3151, line: 97, type: !2885, isLocal: true, isDefinition: true)
!3162 = !DIGlobalVariableExpression(var: !3163, expr: !DIExpression())
!3163 = distinct !DIGlobalVariable(scope: null, file: !3151, line: 97, type: !3164, isLocal: true, isDefinition: true)
!3164 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 1448, elements: !3165)
!3165 = !{!3166}
!3166 = !DISubrange(count: 181)
!3167 = !DIGlobalVariableExpression(var: !3168, expr: !DIExpression())
!3168 = distinct !DIGlobalVariable(scope: null, file: !3169, line: 423, type: !3170, isLocal: true, isDefinition: true)
!3169 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/vector.tcc", directory: "", checksumkind: CSK_MD5, checksum: "d0546ffb79f08cabb1d395ee56a00a29")
!3170 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 208, elements: !3171)
!3171 = !{!3172}
!3172 = !DISubrange(count: 26)
!3173 = !DIGlobalVariableExpression(var: !3174, expr: !DIExpression())
!3174 = distinct !DIGlobalVariable(scope: null, file: !3169, line: 603, type: !3170, isLocal: true, isDefinition: true)
!3175 = !DIGlobalVariableExpression(var: !3176, expr: !DIExpression())
!3176 = distinct !DIGlobalVariable(scope: null, file: !690, line: 478, type: !3045, isLocal: true, isDefinition: true)
!3177 = !DIGlobalVariableExpression(var: !3178, expr: !DIExpression())
!3178 = distinct !DIGlobalVariable(scope: null, file: !690, line: 478, type: !3179, isLocal: true, isDefinition: true)
!3179 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 1072, elements: !3180)
!3180 = !{!3181}
!3181 = !DISubrange(count: 134)
!3182 = !DIGlobalVariableExpression(var: !3183, expr: !DIExpression())
!3183 = distinct !DIGlobalVariable(scope: null, file: !690, line: 478, type: !3184, isLocal: true, isDefinition: true)
!3184 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 4120, elements: !3185)
!3185 = !{!3186}
!3186 = !DISubrange(count: 515)
!3187 = !DIGlobalVariableExpression(var: !3188, expr: !DIExpression())
!3188 = distinct !DIGlobalVariable(scope: null, file: !690, line: 445, type: !3189, isLocal: true, isDefinition: true)
!3189 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 80, elements: !3190)
!3190 = !{!3191}
!3191 = !DISubrange(count: 10)
!3192 = !DIGlobalVariableExpression(var: !3193, expr: !DIExpression())
!3193 = distinct !DIGlobalVariable(scope: null, file: !690, line: 445, type: !3194, isLocal: true, isDefinition: true)
!3194 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 3888, elements: !3195)
!3195 = !{!3196}
!3196 = !DISubrange(count: 486)
!3197 = !DIGlobalVariableExpression(var: !3198, expr: !DIExpression())
!3198 = distinct !DIGlobalVariable(scope: null, file: !690, line: 623, type: !3199, isLocal: true, isDefinition: true)
!3199 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 64, elements: !2842)
!3200 = !DIGlobalVariableExpression(var: !3201, expr: !DIExpression())
!3201 = distinct !DIGlobalVariable(scope: null, file: !690, line: 623, type: !3202, isLocal: true, isDefinition: true)
!3202 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 1744, elements: !3203)
!3203 = !{!3204}
!3204 = !DISubrange(count: 218)
!3205 = !DIGlobalVariableExpression(var: !3206, expr: !DIExpression())
!3206 = distinct !DIGlobalVariable(scope: null, file: !690, line: 291, type: !3207, isLocal: true, isDefinition: true)
!3207 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 192, elements: !3208)
!3208 = !{!3209}
!3209 = !DISubrange(count: 24)
!3210 = !DIGlobalVariableExpression(var: !3211, expr: !DIExpression())
!3211 = distinct !DIGlobalVariable(scope: null, file: !690, line: 291, type: !3212, isLocal: true, isDefinition: true)
!3212 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 312, elements: !3213)
!3213 = !{!3214}
!3214 = !DISubrange(count: 39)
!3215 = !DIGlobalVariableExpression(var: !3216, expr: !DIExpression())
!3216 = distinct !DIGlobalVariable(scope: null, file: !690, line: 291, type: !3217, isLocal: true, isDefinition: true)
!3217 = !DICompositeType(tag: DW_TAG_array_type, baseType: !640, size: 3816, elements: !3218)
!3218 = !{!3219}
!3219 = !DISubrange(count: 477)
!3220 = !{!3221, !3227, !3234, !3236, !3238, !3242, !3244, !3246, !3248, !3250, !3252, !3254, !3256, !3261, !3265, !3267, !3269, !3274, !3276, !3278, !3280, !3282, !3284, !3286, !3289, !3292, !3294, !3298, !3303, !3305, !3307, !3309, !3311, !3313, !3315, !3317, !3319, !3321, !3323, !3327, !3331, !3333, !3335, !3337, !3339, !3341, !3343, !3345, !3347, !3349, !3351, !3353, !3355, !3357, !3359, !3361, !3365, !3369, !3373, !3375, !3377, !3379, !3381, !3383, !3385, !3387, !3389, !3391, !3395, !3399, !3403, !3405, !3407, !3409, !3414, !3418, !3422, !3424, !3426, !3428, !3430, !3432, !3434, !3436, !3438, !3440, !3442, !3444, !3446, !3450, !3454, !3458, !3460, !3462, !3464, !3468, !3472, !3476, !3478, !3480, !3482, !3484, !3486, !3488, !3492, !3496, !3498, !3500, !3502, !3504, !3508, !3512, !3516, !3518, !3520, !3522, !3524, !3526, !3528, !3532, !3536, !3540, !3542, !3546, !3550, !3552, !3554, !3556, !3558, !3560, !3562, !3567, !3568, !3570, !3572, !3573, !3579, !3583, !3589, !3593, !3597, !3603, !3607, !3609, !3611, !3615, !3619, !3623, !3627, !3629, !3631, !3633, !3635, !3639, !3643, !3647, !3649, !3651, !3655, !3659, !3665, !3669, !3674, !3676, !3679, !3683, !3687, !3696, !3700, !3704, !3708, !3710, !3714, !3718, !3722, !3724, !3728, !3735, !3739, !3743, !3745, !3747, !3751, !3755, !3761, !3765, !3769, !3771, !3778, !3782, !3788, !3790, !3794, !3798, !3802, !3806, !3811, !3815, !3819, !3820, !3821, !3822, !3824, !3825, !3826, !3827, !3828, !3829, !3830, !3834, !3838, !3855, !3858, !3863, !3915, !3920, !3924, !3928, !3932, !3936, !3938, !3940, !3944, !3950, !3954, !3960, !3966, !3968, !3972, !3976, !3980, !3984, !3996, !3998, !4002, !4006, !4010, !4012, !4016, !4020, !4024, !4026, !4028, !4032, !4040, !4044, !4048, !4052, !4054, !4060, !4062, !4068, !4072, !4076, !4080, !4084, !4088, !4092, !4094, !4096, !4100, !4104, !4108, !4110, !4114, !4118, !4120, !4122, !4126, !4130, !4134, !4138, !4139, !4140, !4141, !4142, !4143, !4144, !4145, !4146, !4147, !4148, !4153, !4157, !4160, !4163, !4165, !4167, !4169, !4171, !4173, !4175, !4177, !4179, !4182, !4183, !4187, !4190, !4193, !4196, !4198, !4200, !4202, !4204, !4206, !4208, !4210, !4212, !4215, !4216, !4220, !4224, !4229, !4233, !4235, !4237, !4239, !4241, !4243, !4245, !4247, !4249, !4251, !4253, !4255, !4257, !4259, !4260, !4261, !4265, !4271, !4276, !4280, !4282, !4284, !4286, !4288, !4295, !4299, !4303, !4307, !4311, !4315, !4319, !4323, !4325, !4329, !4335, !4339, !4343, !4345, !4348, !4352, !4356, !4358, !4360, !4362, !4364, !4366, !4368, !4370, !4374, !4378, !4382, !4386, !4390, !4394, !4396, !4400, !4404, !4408, !4412, !4414, !4416, !4420, !4424, !4425, !4426, !4427, !4428, !4429, !4435, !4438, !4439, !4441, !4443, !4445, !4447, !4451, !4453, !4455, !4457, !4459, !4461, !4463, !4465, !4467, !4471, !4475, !4477, !4481, !4485, !4487, !4490, !4495, !4499, !4500, !4505, !4509, !4514, !4519, !4523, !4529, !4533, !4535, !4539}
!3221 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3222, file: !3226, line: 52)
!3222 = !DISubprogram(name: "abs", scope: !3223, file: !3223, line: 837, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3223 = !DIFile(filename: "/usr/include/stdlib.h", directory: "", checksumkind: CSK_MD5, checksum: "69d942f1572b8bd342d93c49f499f318")
!3224 = !DISubroutineType(types: !3225)
!3225 = !{!62, !62}
!3226 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_abs.h", directory: "")
!3227 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3228, file: !3233, line: 83)
!3228 = !DISubprogram(name: "acos", scope: !3229, file: !3229, line: 53, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3229 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", directory: "", checksumkind: CSK_MD5, checksum: "540523e6856cf8d57a3ebef5fd79793e")
!3230 = !DISubroutineType(types: !3231)
!3231 = !{!3232, !3232}
!3232 = !DIBasicType(name: "double", size: 64, encoding: DW_ATE_float)
!3233 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cmath", directory: "")
!3234 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3235, file: !3233, line: 102)
!3235 = !DISubprogram(name: "asin", scope: !3229, file: !3229, line: 55, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3236 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3237, file: !3233, line: 121)
!3237 = !DISubprogram(name: "atan", scope: !3229, file: !3229, line: 57, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3238 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3239, file: !3233, line: 140)
!3239 = !DISubprogram(name: "atan2", scope: !3229, file: !3229, line: 59, type: !3240, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3240 = !DISubroutineType(types: !3241)
!3241 = !{!3232, !3232, !3232}
!3242 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3243, file: !3233, line: 161)
!3243 = !DISubprogram(name: "ceil", scope: !3229, file: !3229, line: 159, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3244 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3245, file: !3233, line: 180)
!3245 = !DISubprogram(name: "cos", scope: !3229, file: !3229, line: 62, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3246 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3247, file: !3233, line: 199)
!3247 = !DISubprogram(name: "cosh", scope: !3229, file: !3229, line: 71, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3248 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3249, file: !3233, line: 218)
!3249 = !DISubprogram(name: "exp", scope: !3229, file: !3229, line: 95, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3250 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3251, file: !3233, line: 237)
!3251 = !DISubprogram(name: "fabs", scope: !3229, file: !3229, line: 162, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3252 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3253, file: !3233, line: 256)
!3253 = !DISubprogram(name: "floor", scope: !3229, file: !3229, line: 165, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3254 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3255, file: !3233, line: 275)
!3255 = !DISubprogram(name: "fmod", scope: !3229, file: !3229, line: 168, type: !3240, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3256 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3257, file: !3233, line: 296)
!3257 = !DISubprogram(name: "frexp", scope: !3229, file: !3229, line: 98, type: !3258, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3258 = !DISubroutineType(types: !3259)
!3259 = !{!3232, !3232, !3260}
!3260 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !62, size: 64)
!3261 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3262, file: !3233, line: 315)
!3262 = !DISubprogram(name: "ldexp", scope: !3229, file: !3229, line: 101, type: !3263, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3263 = !DISubroutineType(types: !3264)
!3264 = !{!3232, !3232, !62}
!3265 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3266, file: !3233, line: 334)
!3266 = !DISubprogram(name: "log", scope: !3229, file: !3229, line: 104, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3267 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3268, file: !3233, line: 353)
!3268 = !DISubprogram(name: "log10", scope: !3229, file: !3229, line: 107, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3269 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3270, file: !3233, line: 372)
!3270 = !DISubprogram(name: "modf", scope: !3229, file: !3229, line: 110, type: !3271, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3271 = !DISubroutineType(types: !3272)
!3272 = !{!3232, !3232, !3273}
!3273 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3232, size: 64)
!3274 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3275, file: !3233, line: 384)
!3275 = !DISubprogram(name: "pow", scope: !3229, file: !3229, line: 140, type: !3240, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3276 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3277, file: !3233, line: 421)
!3277 = !DISubprogram(name: "sin", scope: !3229, file: !3229, line: 64, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3278 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3279, file: !3233, line: 440)
!3279 = !DISubprogram(name: "sinh", scope: !3229, file: !3229, line: 73, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3280 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3281, file: !3233, line: 459)
!3281 = !DISubprogram(name: "sqrt", scope: !3229, file: !3229, line: 143, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3282 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3283, file: !3233, line: 478)
!3283 = !DISubprogram(name: "tan", scope: !3229, file: !3229, line: 66, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3284 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3285, file: !3233, line: 497)
!3285 = !DISubprogram(name: "tanh", scope: !3229, file: !3229, line: 75, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3286 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3287, file: !3233, line: 1065)
!3287 = !DIDerivedType(tag: DW_TAG_typedef, name: "double_t", file: !3288, line: 150, baseType: !3232)
!3288 = !DIFile(filename: "/usr/include/math.h", directory: "", checksumkind: CSK_MD5, checksum: "ecf196918078d683ff91ad9a1c51599a")
!3289 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3290, file: !3233, line: 1066)
!3290 = !DIDerivedType(tag: DW_TAG_typedef, name: "float_t", file: !3288, line: 149, baseType: !3291)
!3291 = !DIBasicType(name: "float", size: 32, encoding: DW_ATE_float)
!3292 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3293, file: !3233, line: 1069)
!3293 = !DISubprogram(name: "acosh", scope: !3229, file: !3229, line: 85, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3294 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3295, file: !3233, line: 1070)
!3295 = !DISubprogram(name: "acoshf", scope: !3229, file: !3229, line: 85, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3296 = !DISubroutineType(types: !3297)
!3297 = !{!3291, !3291}
!3298 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3299, file: !3233, line: 1071)
!3299 = !DISubprogram(name: "acoshl", scope: !3229, file: !3229, line: 85, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3300 = !DISubroutineType(types: !3301)
!3301 = !{!3302, !3302}
!3302 = !DIBasicType(name: "long double", size: 128, encoding: DW_ATE_float)
!3303 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3304, file: !3233, line: 1073)
!3304 = !DISubprogram(name: "asinh", scope: !3229, file: !3229, line: 87, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3305 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3306, file: !3233, line: 1074)
!3306 = !DISubprogram(name: "asinhf", scope: !3229, file: !3229, line: 87, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3307 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3308, file: !3233, line: 1075)
!3308 = !DISubprogram(name: "asinhl", scope: !3229, file: !3229, line: 87, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3309 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3310, file: !3233, line: 1077)
!3310 = !DISubprogram(name: "atanh", scope: !3229, file: !3229, line: 89, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3311 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3312, file: !3233, line: 1078)
!3312 = !DISubprogram(name: "atanhf", scope: !3229, file: !3229, line: 89, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3313 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3314, file: !3233, line: 1079)
!3314 = !DISubprogram(name: "atanhl", scope: !3229, file: !3229, line: 89, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3315 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3316, file: !3233, line: 1081)
!3316 = !DISubprogram(name: "cbrt", scope: !3229, file: !3229, line: 152, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3317 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3318, file: !3233, line: 1082)
!3318 = !DISubprogram(name: "cbrtf", scope: !3229, file: !3229, line: 152, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3319 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3320, file: !3233, line: 1083)
!3320 = !DISubprogram(name: "cbrtl", scope: !3229, file: !3229, line: 152, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3321 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3322, file: !3233, line: 1085)
!3322 = !DISubprogram(name: "copysign", scope: !3229, file: !3229, line: 196, type: !3240, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3323 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3324, file: !3233, line: 1086)
!3324 = !DISubprogram(name: "copysignf", scope: !3229, file: !3229, line: 196, type: !3325, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3325 = !DISubroutineType(types: !3326)
!3326 = !{!3291, !3291, !3291}
!3327 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3328, file: !3233, line: 1087)
!3328 = !DISubprogram(name: "copysignl", scope: !3229, file: !3229, line: 196, type: !3329, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3329 = !DISubroutineType(types: !3330)
!3330 = !{!3302, !3302, !3302}
!3331 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3332, file: !3233, line: 1089)
!3332 = !DISubprogram(name: "erf", scope: !3229, file: !3229, line: 228, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3333 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3334, file: !3233, line: 1090)
!3334 = !DISubprogram(name: "erff", scope: !3229, file: !3229, line: 228, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3335 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3336, file: !3233, line: 1091)
!3336 = !DISubprogram(name: "erfl", scope: !3229, file: !3229, line: 228, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3337 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3338, file: !3233, line: 1093)
!3338 = !DISubprogram(name: "erfc", scope: !3229, file: !3229, line: 229, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3339 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3340, file: !3233, line: 1094)
!3340 = !DISubprogram(name: "erfcf", scope: !3229, file: !3229, line: 229, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3341 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3342, file: !3233, line: 1095)
!3342 = !DISubprogram(name: "erfcl", scope: !3229, file: !3229, line: 229, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3343 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3344, file: !3233, line: 1097)
!3344 = !DISubprogram(name: "exp2", scope: !3229, file: !3229, line: 130, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3345 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3346, file: !3233, line: 1098)
!3346 = !DISubprogram(name: "exp2f", scope: !3229, file: !3229, line: 130, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3347 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3348, file: !3233, line: 1099)
!3348 = !DISubprogram(name: "exp2l", scope: !3229, file: !3229, line: 130, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3349 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3350, file: !3233, line: 1101)
!3350 = !DISubprogram(name: "expm1", scope: !3229, file: !3229, line: 119, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3351 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3352, file: !3233, line: 1102)
!3352 = !DISubprogram(name: "expm1f", scope: !3229, file: !3229, line: 119, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3353 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3354, file: !3233, line: 1103)
!3354 = !DISubprogram(name: "expm1l", scope: !3229, file: !3229, line: 119, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3355 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3356, file: !3233, line: 1105)
!3356 = !DISubprogram(name: "fdim", scope: !3229, file: !3229, line: 326, type: !3240, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3357 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3358, file: !3233, line: 1106)
!3358 = !DISubprogram(name: "fdimf", scope: !3229, file: !3229, line: 326, type: !3325, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3359 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3360, file: !3233, line: 1107)
!3360 = !DISubprogram(name: "fdiml", scope: !3229, file: !3229, line: 326, type: !3329, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3361 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3362, file: !3233, line: 1109)
!3362 = !DISubprogram(name: "fma", scope: !3229, file: !3229, line: 335, type: !3363, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3363 = !DISubroutineType(types: !3364)
!3364 = !{!3232, !3232, !3232, !3232}
!3365 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3366, file: !3233, line: 1110)
!3366 = !DISubprogram(name: "fmaf", scope: !3229, file: !3229, line: 335, type: !3367, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3367 = !DISubroutineType(types: !3368)
!3368 = !{!3291, !3291, !3291, !3291}
!3369 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3370, file: !3233, line: 1111)
!3370 = !DISubprogram(name: "fmal", scope: !3229, file: !3229, line: 335, type: !3371, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3371 = !DISubroutineType(types: !3372)
!3372 = !{!3302, !3302, !3302, !3302}
!3373 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3374, file: !3233, line: 1113)
!3374 = !DISubprogram(name: "fmax", scope: !3229, file: !3229, line: 329, type: !3240, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3375 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3376, file: !3233, line: 1114)
!3376 = !DISubprogram(name: "fmaxf", scope: !3229, file: !3229, line: 329, type: !3325, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3377 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3378, file: !3233, line: 1115)
!3378 = !DISubprogram(name: "fmaxl", scope: !3229, file: !3229, line: 329, type: !3329, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3379 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3380, file: !3233, line: 1117)
!3380 = !DISubprogram(name: "fmin", scope: !3229, file: !3229, line: 332, type: !3240, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3381 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3382, file: !3233, line: 1118)
!3382 = !DISubprogram(name: "fminf", scope: !3229, file: !3229, line: 332, type: !3325, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3383 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3384, file: !3233, line: 1119)
!3384 = !DISubprogram(name: "fminl", scope: !3229, file: !3229, line: 332, type: !3329, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3385 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3386, file: !3233, line: 1121)
!3386 = !DISubprogram(name: "hypot", scope: !3229, file: !3229, line: 147, type: !3240, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3387 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3388, file: !3233, line: 1122)
!3388 = !DISubprogram(name: "hypotf", scope: !3229, file: !3229, line: 147, type: !3325, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3389 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3390, file: !3233, line: 1123)
!3390 = !DISubprogram(name: "hypotl", scope: !3229, file: !3229, line: 147, type: !3329, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3391 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3392, file: !3233, line: 1125)
!3392 = !DISubprogram(name: "ilogb", scope: !3229, file: !3229, line: 280, type: !3393, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3393 = !DISubroutineType(types: !3394)
!3394 = !{!62, !3232}
!3395 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3396, file: !3233, line: 1126)
!3396 = !DISubprogram(name: "ilogbf", scope: !3229, file: !3229, line: 280, type: !3397, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3397 = !DISubroutineType(types: !3398)
!3398 = !{!62, !3291}
!3399 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3400, file: !3233, line: 1127)
!3400 = !DISubprogram(name: "ilogbl", scope: !3229, file: !3229, line: 280, type: !3401, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3401 = !DISubroutineType(types: !3402)
!3402 = !{!62, !3302}
!3403 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3404, file: !3233, line: 1129)
!3404 = !DISubprogram(name: "lgamma", scope: !3229, file: !3229, line: 230, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3405 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3406, file: !3233, line: 1130)
!3406 = !DISubprogram(name: "lgammaf", scope: !3229, file: !3229, line: 230, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3407 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3408, file: !3233, line: 1131)
!3408 = !DISubprogram(name: "lgammal", scope: !3229, file: !3229, line: 230, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3409 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3410, file: !3233, line: 1134)
!3410 = !DISubprogram(name: "llrint", scope: !3229, file: !3229, line: 316, type: !3411, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3411 = !DISubroutineType(types: !3412)
!3412 = !{!3413, !3232}
!3413 = !DIBasicType(name: "long long", size: 64, encoding: DW_ATE_signed)
!3414 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3415, file: !3233, line: 1135)
!3415 = !DISubprogram(name: "llrintf", scope: !3229, file: !3229, line: 316, type: !3416, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3416 = !DISubroutineType(types: !3417)
!3417 = !{!3413, !3291}
!3418 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3419, file: !3233, line: 1136)
!3419 = !DISubprogram(name: "llrintl", scope: !3229, file: !3229, line: 316, type: !3420, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3420 = !DISubroutineType(types: !3421)
!3421 = !{!3413, !3302}
!3422 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3423, file: !3233, line: 1138)
!3423 = !DISubprogram(name: "llround", scope: !3229, file: !3229, line: 322, type: !3411, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3424 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3425, file: !3233, line: 1139)
!3425 = !DISubprogram(name: "llroundf", scope: !3229, file: !3229, line: 322, type: !3416, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3426 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3427, file: !3233, line: 1140)
!3427 = !DISubprogram(name: "llroundl", scope: !3229, file: !3229, line: 322, type: !3420, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3428 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3429, file: !3233, line: 1143)
!3429 = !DISubprogram(name: "log1p", scope: !3229, file: !3229, line: 122, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3430 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3431, file: !3233, line: 1144)
!3431 = !DISubprogram(name: "log1pf", scope: !3229, file: !3229, line: 122, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3432 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3433, file: !3233, line: 1145)
!3433 = !DISubprogram(name: "log1pl", scope: !3229, file: !3229, line: 122, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3434 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3435, file: !3233, line: 1147)
!3435 = !DISubprogram(name: "log2", scope: !3229, file: !3229, line: 133, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3436 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3437, file: !3233, line: 1148)
!3437 = !DISubprogram(name: "log2f", scope: !3229, file: !3229, line: 133, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3438 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3439, file: !3233, line: 1149)
!3439 = !DISubprogram(name: "log2l", scope: !3229, file: !3229, line: 133, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3440 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3441, file: !3233, line: 1151)
!3441 = !DISubprogram(name: "logb", scope: !3229, file: !3229, line: 125, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3442 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3443, file: !3233, line: 1152)
!3443 = !DISubprogram(name: "logbf", scope: !3229, file: !3229, line: 125, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3444 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3445, file: !3233, line: 1153)
!3445 = !DISubprogram(name: "logbl", scope: !3229, file: !3229, line: 125, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3446 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3447, file: !3233, line: 1155)
!3447 = !DISubprogram(name: "lrint", scope: !3229, file: !3229, line: 314, type: !3448, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3448 = !DISubroutineType(types: !3449)
!3449 = !{!455, !3232}
!3450 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3451, file: !3233, line: 1156)
!3451 = !DISubprogram(name: "lrintf", scope: !3229, file: !3229, line: 314, type: !3452, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3452 = !DISubroutineType(types: !3453)
!3453 = !{!455, !3291}
!3454 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3455, file: !3233, line: 1157)
!3455 = !DISubprogram(name: "lrintl", scope: !3229, file: !3229, line: 314, type: !3456, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3456 = !DISubroutineType(types: !3457)
!3457 = !{!455, !3302}
!3458 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3459, file: !3233, line: 1159)
!3459 = !DISubprogram(name: "lround", scope: !3229, file: !3229, line: 320, type: !3448, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3460 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3461, file: !3233, line: 1160)
!3461 = !DISubprogram(name: "lroundf", scope: !3229, file: !3229, line: 320, type: !3452, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3462 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3463, file: !3233, line: 1161)
!3463 = !DISubprogram(name: "lroundl", scope: !3229, file: !3229, line: 320, type: !3456, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3464 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3465, file: !3233, line: 1163)
!3465 = !DISubprogram(name: "nan", scope: !3229, file: !3229, line: 201, type: !3466, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3466 = !DISubroutineType(types: !3467)
!3467 = !{!3232, !639}
!3468 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3469, file: !3233, line: 1164)
!3469 = !DISubprogram(name: "nanf", scope: !3229, file: !3229, line: 201, type: !3470, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3470 = !DISubroutineType(types: !3471)
!3471 = !{!3291, !639}
!3472 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3473, file: !3233, line: 1165)
!3473 = !DISubprogram(name: "nanl", scope: !3229, file: !3229, line: 201, type: !3474, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3474 = !DISubroutineType(types: !3475)
!3475 = !{!3302, !639}
!3476 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3477, file: !3233, line: 1167)
!3477 = !DISubprogram(name: "nearbyint", scope: !3229, file: !3229, line: 294, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3478 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3479, file: !3233, line: 1168)
!3479 = !DISubprogram(name: "nearbyintf", scope: !3229, file: !3229, line: 294, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3480 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3481, file: !3233, line: 1169)
!3481 = !DISubprogram(name: "nearbyintl", scope: !3229, file: !3229, line: 294, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3482 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3483, file: !3233, line: 1171)
!3483 = !DISubprogram(name: "nextafter", scope: !3229, file: !3229, line: 259, type: !3240, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3484 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3485, file: !3233, line: 1172)
!3485 = !DISubprogram(name: "nextafterf", scope: !3229, file: !3229, line: 259, type: !3325, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3486 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3487, file: !3233, line: 1173)
!3487 = !DISubprogram(name: "nextafterl", scope: !3229, file: !3229, line: 259, type: !3329, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3488 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3489, file: !3233, line: 1175)
!3489 = !DISubprogram(name: "nexttoward", scope: !3229, file: !3229, line: 261, type: !3490, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3490 = !DISubroutineType(types: !3491)
!3491 = !{!3232, !3232, !3302}
!3492 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3493, file: !3233, line: 1176)
!3493 = !DISubprogram(name: "nexttowardf", scope: !3229, file: !3229, line: 261, type: !3494, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3494 = !DISubroutineType(types: !3495)
!3495 = !{!3291, !3291, !3302}
!3496 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3497, file: !3233, line: 1177)
!3497 = !DISubprogram(name: "nexttowardl", scope: !3229, file: !3229, line: 261, type: !3329, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3498 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3499, file: !3233, line: 1179)
!3499 = !DISubprogram(name: "remainder", scope: !3229, file: !3229, line: 272, type: !3240, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3500 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3501, file: !3233, line: 1180)
!3501 = !DISubprogram(name: "remainderf", scope: !3229, file: !3229, line: 272, type: !3325, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3502 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3503, file: !3233, line: 1181)
!3503 = !DISubprogram(name: "remainderl", scope: !3229, file: !3229, line: 272, type: !3329, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3504 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3505, file: !3233, line: 1183)
!3505 = !DISubprogram(name: "remquo", scope: !3229, file: !3229, line: 307, type: !3506, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3506 = !DISubroutineType(types: !3507)
!3507 = !{!3232, !3232, !3232, !3260}
!3508 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3509, file: !3233, line: 1184)
!3509 = !DISubprogram(name: "remquof", scope: !3229, file: !3229, line: 307, type: !3510, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3510 = !DISubroutineType(types: !3511)
!3511 = !{!3291, !3291, !3291, !3260}
!3512 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3513, file: !3233, line: 1185)
!3513 = !DISubprogram(name: "remquol", scope: !3229, file: !3229, line: 307, type: !3514, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3514 = !DISubroutineType(types: !3515)
!3515 = !{!3302, !3302, !3302, !3260}
!3516 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3517, file: !3233, line: 1187)
!3517 = !DISubprogram(name: "rint", scope: !3229, file: !3229, line: 256, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3518 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3519, file: !3233, line: 1188)
!3519 = !DISubprogram(name: "rintf", scope: !3229, file: !3229, line: 256, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3520 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3521, file: !3233, line: 1189)
!3521 = !DISubprogram(name: "rintl", scope: !3229, file: !3229, line: 256, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3522 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3523, file: !3233, line: 1191)
!3523 = !DISubprogram(name: "round", scope: !3229, file: !3229, line: 298, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3524 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3525, file: !3233, line: 1192)
!3525 = !DISubprogram(name: "roundf", scope: !3229, file: !3229, line: 298, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3526 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3527, file: !3233, line: 1193)
!3527 = !DISubprogram(name: "roundl", scope: !3229, file: !3229, line: 298, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3528 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3529, file: !3233, line: 1195)
!3529 = !DISubprogram(name: "scalbln", scope: !3229, file: !3229, line: 290, type: !3530, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3530 = !DISubroutineType(types: !3531)
!3531 = !{!3232, !3232, !455}
!3532 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3533, file: !3233, line: 1196)
!3533 = !DISubprogram(name: "scalblnf", scope: !3229, file: !3229, line: 290, type: !3534, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3534 = !DISubroutineType(types: !3535)
!3535 = !{!3291, !3291, !455}
!3536 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3537, file: !3233, line: 1197)
!3537 = !DISubprogram(name: "scalblnl", scope: !3229, file: !3229, line: 290, type: !3538, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3538 = !DISubroutineType(types: !3539)
!3539 = !{!3302, !3302, !455}
!3540 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3541, file: !3233, line: 1199)
!3541 = !DISubprogram(name: "scalbn", scope: !3229, file: !3229, line: 276, type: !3263, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3542 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3543, file: !3233, line: 1200)
!3543 = !DISubprogram(name: "scalbnf", scope: !3229, file: !3229, line: 276, type: !3544, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3544 = !DISubroutineType(types: !3545)
!3545 = !{!3291, !3291, !62}
!3546 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3547, file: !3233, line: 1201)
!3547 = !DISubprogram(name: "scalbnl", scope: !3229, file: !3229, line: 276, type: !3548, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3548 = !DISubroutineType(types: !3549)
!3549 = !{!3302, !3302, !62}
!3550 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3551, file: !3233, line: 1203)
!3551 = !DISubprogram(name: "tgamma", scope: !3229, file: !3229, line: 235, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3552 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3553, file: !3233, line: 1204)
!3553 = !DISubprogram(name: "tgammaf", scope: !3229, file: !3229, line: 235, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3554 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3555, file: !3233, line: 1205)
!3555 = !DISubprogram(name: "tgammal", scope: !3229, file: !3229, line: 235, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3556 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3557, file: !3233, line: 1207)
!3557 = !DISubprogram(name: "trunc", scope: !3229, file: !3229, line: 302, type: !3230, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3558 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3559, file: !3233, line: 1208)
!3559 = !DISubprogram(name: "truncf", scope: !3229, file: !3229, line: 302, type: !3296, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3560 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3561, file: !3233, line: 1209)
!3561 = !DISubprogram(name: "truncl", scope: !3229, file: !3229, line: 302, type: !3300, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3562 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3563, file: !3566, line: 56)
!3563 = !DIDerivedType(tag: DW_TAG_typedef, name: "max_align_t", file: !3564, line: 24, baseType: !3565)
!3564 = !DIFile(filename: "llvm5/build/lib/clang/15.0.3/include/__stddef_max_align_t.h", directory: "/fast/fs", checksumkind: CSK_MD5, checksum: "48e8e2456f77e6cda35d245130fa7259")
!3565 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !3564, line: 19, size: 256, flags: DIFlagFwdDecl, identifier: "_ZTS11max_align_t")
!3566 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstddef", directory: "")
!3567 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !14, entity: !1520, file: !79, line: 63)
!3568 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !14, entity: !3569, file: !79, line: 64)
!3569 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Twine", scope: !80, file: !79, line: 30, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm5TwineE")
!3570 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !14, entity: !3571, file: !79, line: 76)
!3571 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "RefCountedBaseVPTR", scope: !80, file: !79, line: 45, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSN4llvm18RefCountedBaseVPTRE")
!3572 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !14, entity: !78, file: !79, line: 78)
!3573 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3574, file: !3578, line: 75)
!3574 = !DISubprogram(name: "memchr", scope: !3575, file: !3575, line: 90, type: !3576, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3575 = !DIFile(filename: "/usr/include/string.h", directory: "", checksumkind: CSK_MD5, checksum: "1029a2d94b0e7b73f8dbf87ca20ab7bc")
!3576 = !DISubroutineType(types: !3577)
!3577 = !{!68, !72, !62, !143}
!3578 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstring", directory: "")
!3579 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3580, file: !3578, line: 76)
!3580 = !DISubprogram(name: "memcmp", scope: !3575, file: !3575, line: 63, type: !3581, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3581 = !DISubroutineType(types: !3582)
!3582 = !{!62, !72, !72, !143}
!3583 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3584, file: !3578, line: 77)
!3584 = !DISubprogram(name: "memcpy", scope: !3575, file: !3575, line: 42, type: !3585, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3585 = !DISubroutineType(types: !3586)
!3586 = !{!68, !3587, !3588, !143}
!3587 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !68)
!3588 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !72)
!3589 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3590, file: !3578, line: 78)
!3590 = !DISubprogram(name: "memmove", scope: !3575, file: !3575, line: 46, type: !3591, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3591 = !DISubroutineType(types: !3592)
!3592 = !{!68, !68, !72, !143}
!3593 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3594, file: !3578, line: 79)
!3594 = !DISubprogram(name: "memset", scope: !3575, file: !3575, line: 60, type: !3595, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3595 = !DISubroutineType(types: !3596)
!3596 = !{!68, !68, !62, !143}
!3597 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3598, file: !3578, line: 80)
!3598 = !DISubprogram(name: "strcat", scope: !3575, file: !3575, line: 129, type: !3599, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3599 = !DISubroutineType(types: !3600)
!3600 = !{!2236, !3601, !3602}
!3601 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !2236)
!3602 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !639)
!3603 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3604, file: !3578, line: 81)
!3604 = !DISubprogram(name: "strcmp", scope: !3575, file: !3575, line: 136, type: !3605, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3605 = !DISubroutineType(types: !3606)
!3606 = !{!62, !639, !639}
!3607 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3608, file: !3578, line: 82)
!3608 = !DISubprogram(name: "strcoll", scope: !3575, file: !3575, line: 143, type: !3605, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3609 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3610, file: !3578, line: 83)
!3610 = !DISubprogram(name: "strcpy", scope: !3575, file: !3575, line: 121, type: !3599, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3611 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3612, file: !3578, line: 84)
!3612 = !DISubprogram(name: "strcspn", scope: !3575, file: !3575, line: 272, type: !3613, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3613 = !DISubroutineType(types: !3614)
!3614 = !{!143, !639, !639}
!3615 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3616, file: !3578, line: 85)
!3616 = !DISubprogram(name: "strerror", scope: !3575, file: !3575, line: 396, type: !3617, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3617 = !DISubroutineType(types: !3618)
!3618 = !{!2236, !62}
!3619 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3620, file: !3578, line: 86)
!3620 = !DISubprogram(name: "strlen", scope: !3575, file: !3575, line: 384, type: !3621, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3621 = !DISubroutineType(types: !3622)
!3622 = !{!143, !639}
!3623 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3624, file: !3578, line: 87)
!3624 = !DISubprogram(name: "strncat", scope: !3575, file: !3575, line: 132, type: !3625, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3625 = !DISubroutineType(types: !3626)
!3626 = !{!2236, !3601, !3602, !143}
!3627 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3628, file: !3578, line: 88)
!3628 = !DISubprogram(name: "strncmp", scope: !3575, file: !3575, line: 139, type: !1532, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3629 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3630, file: !3578, line: 89)
!3630 = !DISubprogram(name: "strncpy", scope: !3575, file: !3575, line: 124, type: !3625, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3631 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3632, file: !3578, line: 90)
!3632 = !DISubprogram(name: "strspn", scope: !3575, file: !3575, line: 276, type: !3613, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3633 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3634, file: !3578, line: 91)
!3634 = !DISubprogram(name: "strtok", scope: !3575, file: !3575, line: 335, type: !3599, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3635 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3636, file: !3578, line: 92)
!3636 = !DISubprogram(name: "strxfrm", scope: !3575, file: !3575, line: 146, type: !3637, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3637 = !DISubroutineType(types: !3638)
!3638 = !{!143, !3601, !3602, !143}
!3639 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3640, file: !3578, line: 93)
!3640 = !DISubprogram(name: "strchr", scope: !3575, file: !3575, line: 225, type: !3641, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3641 = !DISubroutineType(types: !3642)
!3642 = !{!2236, !639, !62}
!3643 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3644, file: !3578, line: 94)
!3644 = !DISubprogram(name: "strpbrk", scope: !3575, file: !3575, line: 302, type: !3645, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3645 = !DISubroutineType(types: !3646)
!3646 = !{!2236, !639, !639}
!3647 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3648, file: !3578, line: 95)
!3648 = !DISubprogram(name: "strrchr", scope: !3575, file: !3575, line: 252, type: !3641, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3649 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3650, file: !3578, line: 96)
!3650 = !DISubprogram(name: "strstr", scope: !3575, file: !3575, line: 329, type: !3645, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3651 = !DIImportedEntity(tag: DW_TAG_imported_module, scope: !3652, entity: !3653, file: !3654, line: 58)
!3652 = !DINamespace(name: "__gnu_debug", scope: null)
!3653 = !DINamespace(name: "__debug", scope: !91)
!3654 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/debug/debug.h", directory: "", checksumkind: CSK_MD5, checksum: "0d648599b52b1d377b1fee4a0a4b2b91")
!3655 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3656, file: !3658, line: 127)
!3656 = !DIDerivedType(tag: DW_TAG_typedef, name: "div_t", file: !3223, line: 62, baseType: !3657)
!3657 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !3223, line: 58, size: 64, flags: DIFlagFwdDecl, identifier: "_ZTS5div_t")
!3658 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdlib", directory: "")
!3659 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3660, file: !3658, line: 128)
!3660 = !DIDerivedType(tag: DW_TAG_typedef, name: "ldiv_t", file: !3223, line: 70, baseType: !3661)
!3661 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !3223, line: 66, size: 128, flags: DIFlagTypePassByValue, elements: !3662, identifier: "_ZTS6ldiv_t")
!3662 = !{!3663, !3664}
!3663 = !DIDerivedType(tag: DW_TAG_member, name: "quot", scope: !3661, file: !3223, line: 68, baseType: !455, size: 64)
!3664 = !DIDerivedType(tag: DW_TAG_member, name: "rem", scope: !3661, file: !3223, line: 69, baseType: !455, size: 64, offset: 64)
!3665 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3666, file: !3658, line: 130)
!3666 = !DISubprogram(name: "abort", scope: !3223, file: !3223, line: 588, type: !3667, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!3667 = !DISubroutineType(types: !3668)
!3668 = !{null}
!3669 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3670, file: !3658, line: 134)
!3670 = !DISubprogram(name: "atexit", scope: !3223, file: !3223, line: 592, type: !3671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3671 = !DISubroutineType(types: !3672)
!3672 = !{!62, !3673}
!3673 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3667, size: 64)
!3674 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3675, file: !3658, line: 137)
!3675 = !DISubprogram(name: "at_quick_exit", scope: !3223, file: !3223, line: 597, type: !3671, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3676 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3677, file: !3658, line: 140)
!3677 = !DISubprogram(name: "atof", scope: !3678, file: !3678, line: 25, type: !3466, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3678 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h", directory: "", checksumkind: CSK_MD5, checksum: "ce60958b260b171e83db3307f1d644f0")
!3679 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3680, file: !3658, line: 141)
!3680 = !DISubprogram(name: "atoi", scope: !3223, file: !3223, line: 361, type: !3681, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3681 = !DISubroutineType(types: !3682)
!3682 = !{!62, !639}
!3683 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3684, file: !3658, line: 142)
!3684 = !DISubprogram(name: "atol", scope: !3223, file: !3223, line: 366, type: !3685, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3685 = !DISubroutineType(types: !3686)
!3686 = !{!455, !639}
!3687 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3688, file: !3658, line: 143)
!3688 = !DISubprogram(name: "bsearch", scope: !3689, file: !3689, line: 20, type: !3690, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3689 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h", directory: "", checksumkind: CSK_MD5, checksum: "1a798a38b25adee7bb680abce9ef568a")
!3690 = !DISubroutineType(types: !3691)
!3691 = !{!68, !72, !72, !143, !143, !3692}
!3692 = !DIDerivedType(tag: DW_TAG_typedef, name: "__compar_fn_t", file: !3223, line: 805, baseType: !3693)
!3693 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3694, size: 64)
!3694 = !DISubroutineType(types: !3695)
!3695 = !{!62, !72, !72}
!3696 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3697, file: !3658, line: 144)
!3697 = !DISubprogram(name: "calloc", scope: !3223, file: !3223, line: 541, type: !3698, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3698 = !DISubroutineType(types: !3699)
!3699 = !{!68, !143, !143}
!3700 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3701, file: !3658, line: 145)
!3701 = !DISubprogram(name: "div", scope: !3223, file: !3223, line: 849, type: !3702, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3702 = !DISubroutineType(types: !3703)
!3703 = !{!3656, !62, !62}
!3704 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3705, file: !3658, line: 146)
!3705 = !DISubprogram(name: "exit", scope: !3223, file: !3223, line: 614, type: !3706, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!3706 = !DISubroutineType(types: !3707)
!3707 = !{null, !62}
!3708 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3709, file: !3658, line: 147)
!3709 = !DISubprogram(name: "free", scope: !3223, file: !3223, line: 563, type: !1739, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3710 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3711, file: !3658, line: 148)
!3711 = !DISubprogram(name: "getenv", scope: !3223, file: !3223, line: 631, type: !3712, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3712 = !DISubroutineType(types: !3713)
!3713 = !{!2236, !639}
!3714 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3715, file: !3658, line: 149)
!3715 = !DISubprogram(name: "labs", scope: !3223, file: !3223, line: 838, type: !3716, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3716 = !DISubroutineType(types: !3717)
!3717 = !{!455, !455}
!3718 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3719, file: !3658, line: 150)
!3719 = !DISubprogram(name: "ldiv", scope: !3223, file: !3223, line: 851, type: !3720, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3720 = !DISubroutineType(types: !3721)
!3721 = !{!3660, !455, !455}
!3722 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3723, file: !3658, line: 151)
!3723 = !DISubprogram(name: "malloc", scope: !3223, file: !3223, line: 539, type: !1736, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3724 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3725, file: !3658, line: 153)
!3725 = !DISubprogram(name: "mblen", scope: !3223, file: !3223, line: 919, type: !3726, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3726 = !DISubroutineType(types: !3727)
!3727 = !{!62, !639, !143}
!3728 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3729, file: !3658, line: 154)
!3729 = !DISubprogram(name: "mbstowcs", scope: !3223, file: !3223, line: 930, type: !3730, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3730 = !DISubroutineType(types: !3731)
!3731 = !{!143, !3732, !3602, !143}
!3732 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3733)
!3733 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3734, size: 64)
!3734 = !DIBasicType(name: "wchar_t", size: 32, encoding: DW_ATE_signed)
!3735 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3736, file: !3658, line: 155)
!3736 = !DISubprogram(name: "mbtowc", scope: !3223, file: !3223, line: 922, type: !3737, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3737 = !DISubroutineType(types: !3738)
!3738 = !{!62, !3732, !3602, !143}
!3739 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3740, file: !3658, line: 157)
!3740 = !DISubprogram(name: "qsort", scope: !3223, file: !3223, line: 827, type: !3741, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3741 = !DISubroutineType(types: !3742)
!3742 = !{null, !68, !143, !143, !3692}
!3743 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3744, file: !3658, line: 160)
!3744 = !DISubprogram(name: "quick_exit", scope: !3223, file: !3223, line: 620, type: !3706, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!3745 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3746, file: !3658, line: 163)
!3746 = !DISubprogram(name: "rand", scope: !3223, file: !3223, line: 453, type: !1099, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3747 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3748, file: !3658, line: 164)
!3748 = !DISubprogram(name: "realloc", scope: !3223, file: !3223, line: 549, type: !3749, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3749 = !DISubroutineType(types: !3750)
!3750 = !{!68, !68, !143}
!3751 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3752, file: !3658, line: 165)
!3752 = !DISubprogram(name: "srand", scope: !3223, file: !3223, line: 455, type: !3753, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3753 = !DISubroutineType(types: !3754)
!3754 = !{null, !6}
!3755 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3756, file: !3658, line: 166)
!3756 = !DISubprogram(name: "strtod", scope: !3223, file: !3223, line: 117, type: !3757, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3757 = !DISubroutineType(types: !3758)
!3758 = !{!3232, !3602, !3759}
!3759 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3760)
!3760 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !2236, size: 64)
!3761 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3762, file: !3658, line: 167)
!3762 = !DISubprogram(name: "strtol", scope: !3223, file: !3223, line: 176, type: !3763, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3763 = !DISubroutineType(types: !3764)
!3764 = !{!455, !3602, !3759, !62}
!3765 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3766, file: !3658, line: 168)
!3766 = !DISubprogram(name: "strtoul", scope: !3223, file: !3223, line: 180, type: !3767, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3767 = !DISubroutineType(types: !3768)
!3768 = !{!145, !3602, !3759, !62}
!3769 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3770, file: !3658, line: 169)
!3770 = !DISubprogram(name: "system", scope: !3223, file: !3223, line: 781, type: !3681, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3771 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3772, file: !3658, line: 171)
!3772 = !DISubprogram(name: "wcstombs", scope: !3223, file: !3223, line: 933, type: !3773, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3773 = !DISubroutineType(types: !3774)
!3774 = !{!143, !3601, !3775, !143}
!3775 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3776)
!3776 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3777, size: 64)
!3777 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3734)
!3778 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3779, file: !3658, line: 172)
!3779 = !DISubprogram(name: "wctomb", scope: !3223, file: !3223, line: 926, type: !3780, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3780 = !DISubroutineType(types: !3781)
!3781 = !{!62, !2236, !3734}
!3782 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3783, file: !3658, line: 200)
!3783 = !DIDerivedType(tag: DW_TAG_typedef, name: "lldiv_t", file: !3223, line: 80, baseType: !3784)
!3784 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !3223, line: 76, size: 128, flags: DIFlagTypePassByValue, elements: !3785, identifier: "_ZTS7lldiv_t")
!3785 = !{!3786, !3787}
!3786 = !DIDerivedType(tag: DW_TAG_member, name: "quot", scope: !3784, file: !3223, line: 78, baseType: !3413, size: 64)
!3787 = !DIDerivedType(tag: DW_TAG_member, name: "rem", scope: !3784, file: !3223, line: 79, baseType: !3413, size: 64, offset: 64)
!3788 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3789, file: !3658, line: 206)
!3789 = !DISubprogram(name: "_Exit", scope: !3223, file: !3223, line: 626, type: !3706, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!3790 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3791, file: !3658, line: 210)
!3791 = !DISubprogram(name: "llabs", scope: !3223, file: !3223, line: 841, type: !3792, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3792 = !DISubroutineType(types: !3793)
!3793 = !{!3413, !3413}
!3794 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3795, file: !3658, line: 216)
!3795 = !DISubprogram(name: "lldiv", scope: !3223, file: !3223, line: 855, type: !3796, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3796 = !DISubroutineType(types: !3797)
!3797 = !{!3783, !3413, !3413}
!3798 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3799, file: !3658, line: 227)
!3799 = !DISubprogram(name: "atoll", scope: !3223, file: !3223, line: 373, type: !3800, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3800 = !DISubroutineType(types: !3801)
!3801 = !{!3413, !639}
!3802 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3803, file: !3658, line: 228)
!3803 = !DISubprogram(name: "strtoll", scope: !3223, file: !3223, line: 200, type: !3804, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3804 = !DISubroutineType(types: !3805)
!3805 = !{!3413, !3602, !3759, !62}
!3806 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3807, file: !3658, line: 229)
!3807 = !DISubprogram(name: "strtoull", scope: !3223, file: !3223, line: 205, type: !3808, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3808 = !DISubroutineType(types: !3809)
!3809 = !{!3810, !3602, !3759, !62}
!3810 = !DIBasicType(name: "unsigned long long", size: 64, encoding: DW_ATE_unsigned)
!3811 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3812, file: !3658, line: 231)
!3812 = !DISubprogram(name: "strtof", scope: !3223, file: !3223, line: 123, type: !3813, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3813 = !DISubroutineType(types: !3814)
!3814 = !{!3291, !3602, !3759}
!3815 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !3816, file: !3658, line: 232)
!3816 = !DISubprogram(name: "strtold", scope: !3223, file: !3223, line: 126, type: !3817, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3817 = !DISubroutineType(types: !3818)
!3818 = !{!3302, !3602, !3759}
!3819 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3783, file: !3658, line: 240)
!3820 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3789, file: !3658, line: 242)
!3821 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3791, file: !3658, line: 244)
!3822 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3823, file: !3658, line: 245)
!3823 = !DISubprogram(name: "div", linkageName: "_ZN9__gnu_cxx3divExx", scope: !5, file: !3658, line: 213, type: !3796, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3824 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3795, file: !3658, line: 246)
!3825 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3799, file: !3658, line: 248)
!3826 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3812, file: !3658, line: 249)
!3827 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3803, file: !3658, line: 250)
!3828 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3807, file: !3658, line: 251)
!3829 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3816, file: !3658, line: 252)
!3830 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3831, file: !3832, line: 57)
!3831 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "exception_ptr", scope: !3833, file: !3832, line: 79, size: 64, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTSNSt15__exception_ptr13exception_ptrE")
!3832 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/exception_ptr.h", directory: "", checksumkind: CSK_MD5, checksum: "25d44782b686509a9fc5c8aaa8066643")
!3833 = !DINamespace(name: "__exception_ptr", scope: !91)
!3834 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !3833, entity: !3835, file: !3832, line: 73)
!3835 = !DISubprogram(name: "rethrow_exception", linkageName: "_ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE", scope: !91, file: !3832, line: 69, type: !3836, flags: DIFlagPrototyped | DIFlagNoReturn, spFlags: DISPFlagOptimized)
!3836 = !DISubroutineType(types: !3837)
!3837 = !{null, !3831}
!3838 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3839, file: !3854, line: 64)
!3839 = !DIDerivedType(tag: DW_TAG_typedef, name: "mbstate_t", file: !3840, line: 6, baseType: !3841)
!3840 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/mbstate_t.h", directory: "", checksumkind: CSK_MD5, checksum: "ba8742313715e20e434cf6ccb2db98e3")
!3841 = !DIDerivedType(tag: DW_TAG_typedef, name: "__mbstate_t", file: !3842, line: 21, baseType: !3843)
!3842 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h", directory: "", checksumkind: CSK_MD5, checksum: "82911a3e689448e3691ded3e0b471a55")
!3843 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !3842, line: 13, size: 64, flags: DIFlagTypePassByValue, elements: !3844, identifier: "_ZTS11__mbstate_t")
!3844 = !{!3845, !3846}
!3845 = !DIDerivedType(tag: DW_TAG_member, name: "__count", scope: !3843, file: !3842, line: 15, baseType: !62, size: 32)
!3846 = !DIDerivedType(tag: DW_TAG_member, name: "__value", scope: !3843, file: !3842, line: 20, baseType: !3847, size: 32, offset: 32)
!3847 = distinct !DICompositeType(tag: DW_TAG_union_type, scope: !3843, file: !3842, line: 16, size: 32, flags: DIFlagTypePassByValue, elements: !3848, identifier: "_ZTSN11__mbstate_tUt_E")
!3848 = !{!3849, !3850}
!3849 = !DIDerivedType(tag: DW_TAG_member, name: "__wch", scope: !3847, file: !3842, line: 18, baseType: !6, size: 32)
!3850 = !DIDerivedType(tag: DW_TAG_member, name: "__wchb", scope: !3847, file: !3842, line: 19, baseType: !3851, size: 32)
!3851 = !DICompositeType(tag: DW_TAG_array_type, baseType: !641, size: 32, elements: !3852)
!3852 = !{!3853}
!3853 = !DISubrange(count: 4)
!3854 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cwchar", directory: "")
!3855 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3856, file: !3854, line: 139)
!3856 = !DIDerivedType(tag: DW_TAG_typedef, name: "wint_t", file: !3857, line: 20, baseType: !6)
!3857 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/wint_t.h", directory: "", checksumkind: CSK_MD5, checksum: "aa31b53ef28dc23152ceb41e2763ded3")
!3858 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3859, file: !3854, line: 141)
!3859 = !DISubprogram(name: "btowc", scope: !3860, file: !3860, line: 318, type: !3861, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3860 = !DIFile(filename: "/usr/include/wchar.h", directory: "", checksumkind: CSK_MD5, checksum: "5c0512b032e303d7adfb2a47454ecb1c")
!3861 = !DISubroutineType(types: !3862)
!3862 = !{!3856, !62}
!3863 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3864, file: !3854, line: 142)
!3864 = !DISubprogram(name: "fgetwc", scope: !3860, file: !3860, line: 727, type: !3865, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3865 = !DISubroutineType(types: !3866)
!3866 = !{!3856, !3867}
!3867 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3868, size: 64)
!3868 = !DIDerivedType(tag: DW_TAG_typedef, name: "__FILE", file: !3869, line: 5, baseType: !3870)
!3869 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h", directory: "", checksumkind: CSK_MD5, checksum: "72a8fe90981f484acae7c6f3dfc5c2b7")
!3870 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_IO_FILE", file: !3871, line: 245, size: 1728, flags: DIFlagTypePassByValue, elements: !3872, identifier: "_ZTS8_IO_FILE")
!3871 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/libio.h", directory: "", checksumkind: CSK_MD5, checksum: "e2b53e448ab24b9cd2ba8684267b8131")
!3872 = !{!3873, !3874, !3875, !3876, !3877, !3878, !3879, !3880, !3881, !3882, !3883, !3884, !3885, !3888, !3890, !3891, !3892, !3895, !3897, !3899, !3900, !3903, !3905, !3906, !3907, !3908, !3909, !3910, !3911}
!3873 = !DIDerivedType(tag: DW_TAG_member, name: "_flags", scope: !3870, file: !3871, line: 246, baseType: !62, size: 32)
!3874 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_ptr", scope: !3870, file: !3871, line: 251, baseType: !2236, size: 64, offset: 64)
!3875 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_end", scope: !3870, file: !3871, line: 252, baseType: !2236, size: 64, offset: 128)
!3876 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_read_base", scope: !3870, file: !3871, line: 253, baseType: !2236, size: 64, offset: 192)
!3877 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_base", scope: !3870, file: !3871, line: 254, baseType: !2236, size: 64, offset: 256)
!3878 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_ptr", scope: !3870, file: !3871, line: 255, baseType: !2236, size: 64, offset: 320)
!3879 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_write_end", scope: !3870, file: !3871, line: 256, baseType: !2236, size: 64, offset: 384)
!3880 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_buf_base", scope: !3870, file: !3871, line: 257, baseType: !2236, size: 64, offset: 448)
!3881 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_buf_end", scope: !3870, file: !3871, line: 258, baseType: !2236, size: 64, offset: 512)
!3882 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_save_base", scope: !3870, file: !3871, line: 260, baseType: !2236, size: 64, offset: 576)
!3883 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_backup_base", scope: !3870, file: !3871, line: 261, baseType: !2236, size: 64, offset: 640)
!3884 = !DIDerivedType(tag: DW_TAG_member, name: "_IO_save_end", scope: !3870, file: !3871, line: 262, baseType: !2236, size: 64, offset: 704)
!3885 = !DIDerivedType(tag: DW_TAG_member, name: "_markers", scope: !3870, file: !3871, line: 264, baseType: !3886, size: 64, offset: 768)
!3886 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3887, size: 64)
!3887 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "_IO_marker", file: !3871, line: 160, size: 192, flags: DIFlagFwdDecl, identifier: "_ZTS10_IO_marker")
!3888 = !DIDerivedType(tag: DW_TAG_member, name: "_chain", scope: !3870, file: !3871, line: 266, baseType: !3889, size: 64, offset: 832)
!3889 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3870, size: 64)
!3890 = !DIDerivedType(tag: DW_TAG_member, name: "_fileno", scope: !3870, file: !3871, line: 268, baseType: !62, size: 32, offset: 896)
!3891 = !DIDerivedType(tag: DW_TAG_member, name: "_flags2", scope: !3870, file: !3871, line: 272, baseType: !62, size: 32, offset: 928)
!3892 = !DIDerivedType(tag: DW_TAG_member, name: "_old_offset", scope: !3870, file: !3871, line: 274, baseType: !3893, size: 64, offset: 960)
!3893 = !DIDerivedType(tag: DW_TAG_typedef, name: "__off_t", file: !3894, line: 140, baseType: !455)
!3894 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types.h", directory: "", checksumkind: CSK_MD5, checksum: "25679ba19d359e314e48661b21f5aa1f")
!3895 = !DIDerivedType(tag: DW_TAG_member, name: "_cur_column", scope: !3870, file: !3871, line: 278, baseType: !3896, size: 16, offset: 1024)
!3896 = !DIBasicType(name: "unsigned short", size: 16, encoding: DW_ATE_unsigned)
!3897 = !DIDerivedType(tag: DW_TAG_member, name: "_vtable_offset", scope: !3870, file: !3871, line: 279, baseType: !3898, size: 8, offset: 1040)
!3898 = !DIBasicType(name: "signed char", size: 8, encoding: DW_ATE_signed_char)
!3899 = !DIDerivedType(tag: DW_TAG_member, name: "_shortbuf", scope: !3870, file: !3871, line: 280, baseType: !1180, size: 8, offset: 1048)
!3900 = !DIDerivedType(tag: DW_TAG_member, name: "_lock", scope: !3870, file: !3871, line: 284, baseType: !3901, size: 64, offset: 1088)
!3901 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3902, size: 64)
!3902 = !DIDerivedType(tag: DW_TAG_typedef, name: "_IO_lock_t", file: !3871, line: 154, baseType: null)
!3903 = !DIDerivedType(tag: DW_TAG_member, name: "_offset", scope: !3870, file: !3871, line: 293, baseType: !3904, size: 64, offset: 1152)
!3904 = !DIDerivedType(tag: DW_TAG_typedef, name: "__off64_t", file: !3894, line: 141, baseType: !455)
!3905 = !DIDerivedType(tag: DW_TAG_member, name: "__pad1", scope: !3870, file: !3871, line: 301, baseType: !68, size: 64, offset: 1216)
!3906 = !DIDerivedType(tag: DW_TAG_member, name: "__pad2", scope: !3870, file: !3871, line: 302, baseType: !68, size: 64, offset: 1280)
!3907 = !DIDerivedType(tag: DW_TAG_member, name: "__pad3", scope: !3870, file: !3871, line: 303, baseType: !68, size: 64, offset: 1344)
!3908 = !DIDerivedType(tag: DW_TAG_member, name: "__pad4", scope: !3870, file: !3871, line: 304, baseType: !68, size: 64, offset: 1408)
!3909 = !DIDerivedType(tag: DW_TAG_member, name: "__pad5", scope: !3870, file: !3871, line: 306, baseType: !143, size: 64, offset: 1472)
!3910 = !DIDerivedType(tag: DW_TAG_member, name: "_mode", scope: !3870, file: !3871, line: 307, baseType: !62, size: 32, offset: 1536)
!3911 = !DIDerivedType(tag: DW_TAG_member, name: "_unused2", scope: !3870, file: !3871, line: 309, baseType: !3912, size: 160, offset: 1568)
!3912 = !DICompositeType(tag: DW_TAG_array_type, baseType: !641, size: 160, elements: !3913)
!3913 = !{!3914}
!3914 = !DISubrange(count: 20)
!3915 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3916, file: !3854, line: 143)
!3916 = !DISubprogram(name: "fgetws", scope: !3860, file: !3860, line: 756, type: !3917, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3917 = !DISubroutineType(types: !3918)
!3918 = !{!3733, !3732, !62, !3919}
!3919 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3867)
!3920 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3921, file: !3854, line: 144)
!3921 = !DISubprogram(name: "fputwc", scope: !3860, file: !3860, line: 741, type: !3922, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3922 = !DISubroutineType(types: !3923)
!3923 = !{!3856, !3734, !3867}
!3924 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3925, file: !3854, line: 145)
!3925 = !DISubprogram(name: "fputws", scope: !3860, file: !3860, line: 763, type: !3926, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3926 = !DISubroutineType(types: !3927)
!3927 = !{!62, !3775, !3919}
!3928 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3929, file: !3854, line: 146)
!3929 = !DISubprogram(name: "fwide", scope: !3860, file: !3860, line: 573, type: !3930, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3930 = !DISubroutineType(types: !3931)
!3931 = !{!62, !3867, !62}
!3932 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3933, file: !3854, line: 147)
!3933 = !DISubprogram(name: "fwprintf", scope: !3860, file: !3860, line: 580, type: !3934, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3934 = !DISubroutineType(types: !3935)
!3935 = !{!62, !3919, !3775, null}
!3936 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3937, file: !3854, line: 148)
!3937 = !DISubprogram(name: "fwscanf", scope: !3860, file: !3860, line: 621, type: !3934, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3938 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3939, file: !3854, line: 149)
!3939 = !DISubprogram(name: "getwc", scope: !3860, file: !3860, line: 728, type: !3865, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3940 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3941, file: !3854, line: 150)
!3941 = !DISubprogram(name: "getwchar", scope: !3860, file: !3860, line: 734, type: !3942, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3942 = !DISubroutineType(types: !3943)
!3943 = !{!3856}
!3944 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3945, file: !3854, line: 151)
!3945 = !DISubprogram(name: "mbrlen", scope: !3860, file: !3860, line: 329, type: !3946, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3946 = !DISubroutineType(types: !3947)
!3947 = !{!143, !3602, !143, !3948}
!3948 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3949)
!3949 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3839, size: 64)
!3950 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3951, file: !3854, line: 152)
!3951 = !DISubprogram(name: "mbrtowc", scope: !3860, file: !3860, line: 296, type: !3952, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3952 = !DISubroutineType(types: !3953)
!3953 = !{!143, !3732, !3602, !143, !3948}
!3954 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3955, file: !3854, line: 153)
!3955 = !DISubprogram(name: "mbsinit", scope: !3860, file: !3860, line: 292, type: !3956, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3956 = !DISubroutineType(types: !3957)
!3957 = !{!62, !3958}
!3958 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3959, size: 64)
!3959 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3839)
!3960 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3961, file: !3854, line: 154)
!3961 = !DISubprogram(name: "mbsrtowcs", scope: !3860, file: !3860, line: 337, type: !3962, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3962 = !DISubroutineType(types: !3963)
!3963 = !{!143, !3732, !3964, !143, !3948}
!3964 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !3965)
!3965 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !639, size: 64)
!3966 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3967, file: !3854, line: 155)
!3967 = !DISubprogram(name: "putwc", scope: !3860, file: !3860, line: 742, type: !3922, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3968 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3969, file: !3854, line: 156)
!3969 = !DISubprogram(name: "putwchar", scope: !3860, file: !3860, line: 748, type: !3970, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3970 = !DISubroutineType(types: !3971)
!3971 = !{!3856, !3734}
!3972 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3973, file: !3854, line: 158)
!3973 = !DISubprogram(name: "swprintf", scope: !3860, file: !3860, line: 590, type: !3974, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3974 = !DISubroutineType(types: !3975)
!3975 = !{!62, !3732, !143, !3775, null}
!3976 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3977, file: !3854, line: 160)
!3977 = !DISubprogram(name: "swscanf", scope: !3860, file: !3860, line: 631, type: !3978, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3978 = !DISubroutineType(types: !3979)
!3979 = !{!62, !3775, !3775, null}
!3980 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3981, file: !3854, line: 161)
!3981 = !DISubprogram(name: "ungetwc", scope: !3860, file: !3860, line: 771, type: !3982, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3982 = !DISubroutineType(types: !3983)
!3983 = !{!3856, !3856, !3867}
!3984 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3985, file: !3854, line: 162)
!3985 = !DISubprogram(name: "vfwprintf", scope: !3860, file: !3860, line: 598, type: !3986, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3986 = !DISubroutineType(types: !3987)
!3987 = !{!62, !3919, !3775, !3988}
!3988 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3989, size: 64)
!3989 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "__va_list_tag", size: 192, flags: DIFlagTypePassByValue, elements: !3990, identifier: "_ZTS13__va_list_tag")
!3990 = !{!3991, !3993, !3994, !3995}
!3991 = !DIDerivedType(tag: DW_TAG_member, name: "gp_offset", scope: !3989, file: !3992, baseType: !6, size: 32)
!3992 = !DIFile(filename: "llvm34/projects/clang/lib/Lex/PreprocessingRecord.cpp", directory: "/fast/fs")
!3993 = !DIDerivedType(tag: DW_TAG_member, name: "fp_offset", scope: !3989, file: !3992, baseType: !6, size: 32, offset: 32)
!3994 = !DIDerivedType(tag: DW_TAG_member, name: "overflow_arg_area", scope: !3989, file: !3992, baseType: !68, size: 64, offset: 64)
!3995 = !DIDerivedType(tag: DW_TAG_member, name: "reg_save_area", scope: !3989, file: !3992, baseType: !68, size: 64, offset: 128)
!3996 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3997, file: !3854, line: 164)
!3997 = !DISubprogram(name: "vfwscanf", scope: !3860, file: !3860, line: 673, type: !3986, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!3998 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3999, file: !3854, line: 167)
!3999 = !DISubprogram(name: "vswprintf", scope: !3860, file: !3860, line: 611, type: !4000, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4000 = !DISubroutineType(types: !4001)
!4001 = !{!62, !3732, !143, !3775, !3988}
!4002 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4003, file: !3854, line: 170)
!4003 = !DISubprogram(name: "vswscanf", scope: !3860, file: !3860, line: 685, type: !4004, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4004 = !DISubroutineType(types: !4005)
!4005 = !{!62, !3775, !3775, !3988}
!4006 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4007, file: !3854, line: 172)
!4007 = !DISubprogram(name: "vwprintf", scope: !3860, file: !3860, line: 606, type: !4008, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4008 = !DISubroutineType(types: !4009)
!4009 = !{!62, !3775, !3988}
!4010 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4011, file: !3854, line: 174)
!4011 = !DISubprogram(name: "vwscanf", scope: !3860, file: !3860, line: 681, type: !4008, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4012 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4013, file: !3854, line: 176)
!4013 = !DISubprogram(name: "wcrtomb", scope: !3860, file: !3860, line: 301, type: !4014, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4014 = !DISubroutineType(types: !4015)
!4015 = !{!143, !3601, !3734, !3948}
!4016 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4017, file: !3854, line: 177)
!4017 = !DISubprogram(name: "wcscat", scope: !3860, file: !3860, line: 97, type: !4018, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4018 = !DISubroutineType(types: !4019)
!4019 = !{!3733, !3732, !3775}
!4020 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4021, file: !3854, line: 178)
!4021 = !DISubprogram(name: "wcscmp", scope: !3860, file: !3860, line: 106, type: !4022, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4022 = !DISubroutineType(types: !4023)
!4023 = !{!62, !3776, !3776}
!4024 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4025, file: !3854, line: 179)
!4025 = !DISubprogram(name: "wcscoll", scope: !3860, file: !3860, line: 131, type: !4022, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4026 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4027, file: !3854, line: 180)
!4027 = !DISubprogram(name: "wcscpy", scope: !3860, file: !3860, line: 87, type: !4018, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4028 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4029, file: !3854, line: 181)
!4029 = !DISubprogram(name: "wcscspn", scope: !3860, file: !3860, line: 187, type: !4030, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4030 = !DISubroutineType(types: !4031)
!4031 = !{!143, !3776, !3776}
!4032 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4033, file: !3854, line: 182)
!4033 = !DISubprogram(name: "wcsftime", scope: !3860, file: !3860, line: 835, type: !4034, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4034 = !DISubroutineType(types: !4035)
!4035 = !{!143, !3732, !143, !3775, !4036}
!4036 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4037)
!4037 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4038, size: 64)
!4038 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4039)
!4039 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "tm", file: !3860, line: 83, flags: DIFlagFwdDecl | DIFlagNonTrivial, identifier: "_ZTS2tm")
!4040 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4041, file: !3854, line: 183)
!4041 = !DISubprogram(name: "wcslen", scope: !3860, file: !3860, line: 222, type: !4042, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4042 = !DISubroutineType(types: !4043)
!4043 = !{!143, !3776}
!4044 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4045, file: !3854, line: 184)
!4045 = !DISubprogram(name: "wcsncat", scope: !3860, file: !3860, line: 101, type: !4046, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4046 = !DISubroutineType(types: !4047)
!4047 = !{!3733, !3732, !3775, !143}
!4048 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4049, file: !3854, line: 185)
!4049 = !DISubprogram(name: "wcsncmp", scope: !3860, file: !3860, line: 109, type: !4050, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4050 = !DISubroutineType(types: !4051)
!4051 = !{!62, !3776, !3776, !143}
!4052 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4053, file: !3854, line: 186)
!4053 = !DISubprogram(name: "wcsncpy", scope: !3860, file: !3860, line: 92, type: !4046, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4054 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4055, file: !3854, line: 187)
!4055 = !DISubprogram(name: "wcsrtombs", scope: !3860, file: !3860, line: 343, type: !4056, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4056 = !DISubroutineType(types: !4057)
!4057 = !{!143, !3601, !4058, !143, !3948}
!4058 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4059)
!4059 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3776, size: 64)
!4060 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4061, file: !3854, line: 188)
!4061 = !DISubprogram(name: "wcsspn", scope: !3860, file: !3860, line: 191, type: !4030, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4062 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4063, file: !3854, line: 189)
!4063 = !DISubprogram(name: "wcstod", scope: !3860, file: !3860, line: 377, type: !4064, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4064 = !DISubroutineType(types: !4065)
!4065 = !{!3232, !3775, !4066}
!4066 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4067)
!4067 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !3733, size: 64)
!4068 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4069, file: !3854, line: 191)
!4069 = !DISubprogram(name: "wcstof", scope: !3860, file: !3860, line: 382, type: !4070, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4070 = !DISubroutineType(types: !4071)
!4071 = !{!3291, !3775, !4066}
!4072 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4073, file: !3854, line: 193)
!4073 = !DISubprogram(name: "wcstok", scope: !3860, file: !3860, line: 217, type: !4074, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4074 = !DISubroutineType(types: !4075)
!4075 = !{!3733, !3732, !3775, !4066}
!4076 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4077, file: !3854, line: 194)
!4077 = !DISubprogram(name: "wcstol", scope: !3860, file: !3860, line: 428, type: !4078, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4078 = !DISubroutineType(types: !4079)
!4079 = !{!455, !3775, !4066, !62}
!4080 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4081, file: !3854, line: 195)
!4081 = !DISubprogram(name: "wcstoul", scope: !3860, file: !3860, line: 433, type: !4082, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4082 = !DISubroutineType(types: !4083)
!4083 = !{!145, !3775, !4066, !62}
!4084 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4085, file: !3854, line: 196)
!4085 = !DISubprogram(name: "wcsxfrm", scope: !3860, file: !3860, line: 135, type: !4086, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4086 = !DISubroutineType(types: !4087)
!4087 = !{!143, !3732, !3775, !143}
!4088 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4089, file: !3854, line: 197)
!4089 = !DISubprogram(name: "wctob", scope: !3860, file: !3860, line: 324, type: !4090, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4090 = !DISubroutineType(types: !4091)
!4091 = !{!62, !3856}
!4092 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4093, file: !3854, line: 198)
!4093 = !DISubprogram(name: "wmemcmp", scope: !3860, file: !3860, line: 258, type: !4050, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4094 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4095, file: !3854, line: 199)
!4095 = !DISubprogram(name: "wmemcpy", scope: !3860, file: !3860, line: 262, type: !4046, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4096 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4097, file: !3854, line: 200)
!4097 = !DISubprogram(name: "wmemmove", scope: !3860, file: !3860, line: 267, type: !4098, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4098 = !DISubroutineType(types: !4099)
!4099 = !{!3733, !3733, !3776, !143}
!4100 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4101, file: !3854, line: 201)
!4101 = !DISubprogram(name: "wmemset", scope: !3860, file: !3860, line: 271, type: !4102, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4102 = !DISubroutineType(types: !4103)
!4103 = !{!3733, !3733, !3734, !143}
!4104 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4105, file: !3854, line: 202)
!4105 = !DISubprogram(name: "wprintf", scope: !3860, file: !3860, line: 587, type: !4106, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4106 = !DISubroutineType(types: !4107)
!4107 = !{!62, !3775, null}
!4108 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4109, file: !3854, line: 203)
!4109 = !DISubprogram(name: "wscanf", scope: !3860, file: !3860, line: 628, type: !4106, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4110 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4111, file: !3854, line: 204)
!4111 = !DISubprogram(name: "wcschr", scope: !3860, file: !3860, line: 164, type: !4112, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4112 = !DISubroutineType(types: !4113)
!4113 = !{!3733, !3776, !3734}
!4114 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4115, file: !3854, line: 205)
!4115 = !DISubprogram(name: "wcspbrk", scope: !3860, file: !3860, line: 201, type: !4116, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4116 = !DISubroutineType(types: !4117)
!4117 = !{!3733, !3776, !3776}
!4118 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4119, file: !3854, line: 206)
!4119 = !DISubprogram(name: "wcsrchr", scope: !3860, file: !3860, line: 174, type: !4112, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4120 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4121, file: !3854, line: 207)
!4121 = !DISubprogram(name: "wcsstr", scope: !3860, file: !3860, line: 212, type: !4116, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4122 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4123, file: !3854, line: 208)
!4123 = !DISubprogram(name: "wmemchr", scope: !3860, file: !3860, line: 253, type: !4124, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4124 = !DISubroutineType(types: !4125)
!4125 = !{!3733, !3776, !3734, !143}
!4126 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4127, file: !3854, line: 248)
!4127 = !DISubprogram(name: "wcstold", scope: !3860, file: !3860, line: 384, type: !4128, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4128 = !DISubroutineType(types: !4129)
!4129 = !{!3302, !3775, !4066}
!4130 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4131, file: !3854, line: 257)
!4131 = !DISubprogram(name: "wcstoll", scope: !3860, file: !3860, line: 441, type: !4132, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4132 = !DISubroutineType(types: !4133)
!4133 = !{!3413, !3775, !4066, !62}
!4134 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4135, file: !3854, line: 258)
!4135 = !DISubprogram(name: "wcstoull", scope: !3860, file: !3860, line: 448, type: !4136, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4136 = !DISubroutineType(types: !4137)
!4137 = !{!3810, !3775, !4066, !62}
!4138 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4127, file: !3854, line: 264)
!4139 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4131, file: !3854, line: 265)
!4140 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4135, file: !3854, line: 266)
!4141 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4069, file: !3854, line: 280)
!4142 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3997, file: !3854, line: 283)
!4143 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4003, file: !3854, line: 286)
!4144 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4011, file: !3854, line: 289)
!4145 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4127, file: !3854, line: 293)
!4146 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4131, file: !3854, line: 294)
!4147 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4135, file: !3854, line: 295)
!4148 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4149, file: !4152, line: 48)
!4149 = !DIDerivedType(tag: DW_TAG_typedef, name: "int8_t", file: !4150, line: 24, baseType: !4151)
!4150 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdint-intn.h", directory: "", checksumkind: CSK_MD5, checksum: "457547631e07cd24d9a14c8410e28e57")
!4151 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int8_t", file: !3894, line: 36, baseType: !3898)
!4152 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdint", directory: "")
!4153 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4154, file: !4152, line: 49)
!4154 = !DIDerivedType(tag: DW_TAG_typedef, name: "int16_t", file: !4150, line: 25, baseType: !4155)
!4155 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int16_t", file: !3894, line: 38, baseType: !4156)
!4156 = !DIBasicType(name: "short", size: 16, encoding: DW_ATE_signed)
!4157 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4158, file: !4152, line: 50)
!4158 = !DIDerivedType(tag: DW_TAG_typedef, name: "int32_t", file: !4150, line: 26, baseType: !4159)
!4159 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int32_t", file: !3894, line: 40, baseType: !62)
!4160 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4161, file: !4152, line: 51)
!4161 = !DIDerivedType(tag: DW_TAG_typedef, name: "int64_t", file: !4150, line: 27, baseType: !4162)
!4162 = !DIDerivedType(tag: DW_TAG_typedef, name: "__int64_t", file: !3894, line: 43, baseType: !455)
!4163 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4164, file: !4152, line: 53)
!4164 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast8_t", file: !2130, line: 68, baseType: !3898)
!4165 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4166, file: !4152, line: 54)
!4166 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast16_t", file: !2130, line: 70, baseType: !455)
!4167 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4168, file: !4152, line: 55)
!4168 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast32_t", file: !2130, line: 71, baseType: !455)
!4169 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4170, file: !4152, line: 56)
!4170 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_fast64_t", file: !2130, line: 72, baseType: !455)
!4171 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4172, file: !4152, line: 58)
!4172 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least8_t", file: !2130, line: 43, baseType: !3898)
!4173 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4174, file: !4152, line: 59)
!4174 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least16_t", file: !2130, line: 44, baseType: !4156)
!4175 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4176, file: !4152, line: 60)
!4176 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least32_t", file: !2130, line: 45, baseType: !62)
!4177 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4178, file: !4152, line: 61)
!4178 = !DIDerivedType(tag: DW_TAG_typedef, name: "int_least64_t", file: !2130, line: 47, baseType: !455)
!4179 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4180, file: !4152, line: 63)
!4180 = !DIDerivedType(tag: DW_TAG_typedef, name: "intmax_t", file: !2130, line: 111, baseType: !4181)
!4181 = !DIDerivedType(tag: DW_TAG_typedef, name: "__intmax_t", file: !3894, line: 61, baseType: !455)
!4182 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !2129, file: !4152, line: 64)
!4183 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4184, file: !4152, line: 66)
!4184 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint8_t", file: !4185, line: 24, baseType: !4186)
!4185 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdint-uintn.h", directory: "", checksumkind: CSK_MD5, checksum: "9754ebe022edbe8d7928fa709e442f0d")
!4186 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint8_t", file: !3894, line: 37, baseType: !2841)
!4187 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4188, file: !4152, line: 67)
!4188 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint16_t", file: !4185, line: 25, baseType: !4189)
!4189 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint16_t", file: !3894, line: 39, baseType: !3896)
!4190 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4191, file: !4152, line: 68)
!4191 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint32_t", file: !4185, line: 26, baseType: !4192)
!4192 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint32_t", file: !3894, line: 41, baseType: !6)
!4193 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4194, file: !4152, line: 69)
!4194 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint64_t", file: !4185, line: 27, baseType: !4195)
!4195 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uint64_t", file: !3894, line: 44, baseType: !145)
!4196 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4197, file: !4152, line: 71)
!4197 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast8_t", file: !2130, line: 81, baseType: !2841)
!4198 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4199, file: !4152, line: 72)
!4199 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast16_t", file: !2130, line: 83, baseType: !145)
!4200 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4201, file: !4152, line: 73)
!4201 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast32_t", file: !2130, line: 84, baseType: !145)
!4202 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4203, file: !4152, line: 74)
!4203 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_fast64_t", file: !2130, line: 85, baseType: !145)
!4204 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4205, file: !4152, line: 76)
!4205 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least8_t", file: !2130, line: 54, baseType: !2841)
!4206 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4207, file: !4152, line: 77)
!4207 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least16_t", file: !2130, line: 55, baseType: !3896)
!4208 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4209, file: !4152, line: 78)
!4209 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least32_t", file: !2130, line: 56, baseType: !6)
!4210 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4211, file: !4152, line: 79)
!4211 = !DIDerivedType(tag: DW_TAG_typedef, name: "uint_least64_t", file: !2130, line: 58, baseType: !145)
!4212 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4213, file: !4152, line: 81)
!4213 = !DIDerivedType(tag: DW_TAG_typedef, name: "uintmax_t", file: !2130, line: 112, baseType: !4214)
!4214 = !DIDerivedType(tag: DW_TAG_typedef, name: "__uintmax_t", file: !3894, line: 62, baseType: !145)
!4215 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !2186, file: !4152, line: 82)
!4216 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4217, file: !4219, line: 53)
!4217 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "lconv", file: !4218, line: 51, size: 768, flags: DIFlagFwdDecl, identifier: "_ZTS5lconv")
!4218 = !DIFile(filename: "/usr/include/locale.h", directory: "", checksumkind: CSK_MD5, checksum: "0595275e3f5b502d28f7cd61a0dff888")
!4219 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/clocale", directory: "")
!4220 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4221, file: !4219, line: 54)
!4221 = !DISubprogram(name: "setlocale", scope: !4218, file: !4218, line: 122, type: !4222, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4222 = !DISubroutineType(types: !4223)
!4223 = !{!2236, !62, !639}
!4224 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4225, file: !4219, line: 55)
!4225 = !DISubprogram(name: "localeconv", scope: !4218, file: !4218, line: 125, type: !4226, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4226 = !DISubroutineType(types: !4227)
!4227 = !{!4228}
!4228 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4217, size: 64)
!4229 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4230, file: !4232, line: 64)
!4230 = !DISubprogram(name: "isalnum", scope: !4231, file: !4231, line: 108, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4231 = !DIFile(filename: "/usr/include/ctype.h", directory: "", checksumkind: CSK_MD5, checksum: "c67c809b09ef8ea9c273687bc20a7fd3")
!4232 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cctype", directory: "")
!4233 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4234, file: !4232, line: 65)
!4234 = !DISubprogram(name: "isalpha", scope: !4231, file: !4231, line: 109, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4235 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4236, file: !4232, line: 66)
!4236 = !DISubprogram(name: "iscntrl", scope: !4231, file: !4231, line: 110, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4237 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4238, file: !4232, line: 67)
!4238 = !DISubprogram(name: "isdigit", scope: !4231, file: !4231, line: 111, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4239 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4240, file: !4232, line: 68)
!4240 = !DISubprogram(name: "isgraph", scope: !4231, file: !4231, line: 113, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4241 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4242, file: !4232, line: 69)
!4242 = !DISubprogram(name: "islower", scope: !4231, file: !4231, line: 112, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4243 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4244, file: !4232, line: 70)
!4244 = !DISubprogram(name: "isprint", scope: !4231, file: !4231, line: 114, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4245 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4246, file: !4232, line: 71)
!4246 = !DISubprogram(name: "ispunct", scope: !4231, file: !4231, line: 115, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4247 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4248, file: !4232, line: 72)
!4248 = !DISubprogram(name: "isspace", scope: !4231, file: !4231, line: 116, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4249 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4250, file: !4232, line: 73)
!4250 = !DISubprogram(name: "isupper", scope: !4231, file: !4231, line: 117, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4251 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4252, file: !4232, line: 74)
!4252 = !DISubprogram(name: "isxdigit", scope: !4231, file: !4231, line: 118, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4253 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4254, file: !4232, line: 75)
!4254 = !DISubprogram(name: "tolower", scope: !4231, file: !4231, line: 122, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4255 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4256, file: !4232, line: 76)
!4256 = !DISubprogram(name: "toupper", scope: !4231, file: !4231, line: 125, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4257 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4258, file: !4232, line: 87)
!4258 = !DISubprogram(name: "isblank", scope: !4231, file: !4231, line: 130, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4259 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !224, file: !193, line: 44)
!4260 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !454, file: !193, line: 45)
!4261 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4262, file: !4264, line: 98)
!4262 = !DIDerivedType(tag: DW_TAG_typedef, name: "FILE", file: !4263, line: 7, baseType: !3870)
!4263 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/FILE.h", directory: "", checksumkind: CSK_MD5, checksum: "571f9fb6223c42439075fdde11a0de5d")
!4264 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cstdio", directory: "")
!4265 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4266, file: !4264, line: 99)
!4266 = !DIDerivedType(tag: DW_TAG_typedef, name: "fpos_t", file: !4267, line: 78, baseType: !4268)
!4267 = !DIFile(filename: "/usr/include/stdio.h", directory: "", checksumkind: CSK_MD5, checksum: "2ab51d960d7d0ed84798d1688a6988b0")
!4268 = !DIDerivedType(tag: DW_TAG_typedef, name: "_G_fpos_t", file: !4269, line: 30, baseType: !4270)
!4269 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/_G_config.h", directory: "", checksumkind: CSK_MD5, checksum: "f78480ecfcae11a7bda5a6b08034c1fb")
!4270 = distinct !DICompositeType(tag: DW_TAG_structure_type, file: !4269, line: 26, size: 128, flags: DIFlagFwdDecl, identifier: "_ZTS9_G_fpos_t")
!4271 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4272, file: !4264, line: 101)
!4272 = !DISubprogram(name: "clearerr", scope: !4267, file: !4267, line: 757, type: !4273, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4273 = !DISubroutineType(types: !4274)
!4274 = !{null, !4275}
!4275 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4262, size: 64)
!4276 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4277, file: !4264, line: 102)
!4277 = !DISubprogram(name: "fclose", scope: !4267, file: !4267, line: 199, type: !4278, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4278 = !DISubroutineType(types: !4279)
!4279 = !{!62, !4275}
!4280 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4281, file: !4264, line: 103)
!4281 = !DISubprogram(name: "feof", scope: !4267, file: !4267, line: 759, type: !4278, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4282 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4283, file: !4264, line: 104)
!4283 = !DISubprogram(name: "ferror", scope: !4267, file: !4267, line: 761, type: !4278, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4284 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4285, file: !4264, line: 105)
!4285 = !DISubprogram(name: "fflush", scope: !4267, file: !4267, line: 204, type: !4278, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4286 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4287, file: !4264, line: 106)
!4287 = !DISubprogram(name: "fgetc", scope: !4267, file: !4267, line: 477, type: !4278, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4288 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4289, file: !4264, line: 107)
!4289 = !DISubprogram(name: "fgetpos", scope: !4267, file: !4267, line: 731, type: !4290, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4290 = !DISubroutineType(types: !4291)
!4291 = !{!62, !4292, !4293}
!4292 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4275)
!4293 = !DIDerivedType(tag: DW_TAG_restrict_type, baseType: !4294)
!4294 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4266, size: 64)
!4295 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4296, file: !4264, line: 108)
!4296 = !DISubprogram(name: "fgets", scope: !4267, file: !4267, line: 564, type: !4297, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4297 = !DISubroutineType(types: !4298)
!4298 = !{!2236, !3601, !62, !4292}
!4299 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4300, file: !4264, line: 109)
!4300 = !DISubprogram(name: "fopen", scope: !4267, file: !4267, line: 232, type: !4301, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4301 = !DISubroutineType(types: !4302)
!4302 = !{!4275, !3602, !3602}
!4303 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4304, file: !4264, line: 110)
!4304 = !DISubprogram(name: "fprintf", scope: !4267, file: !4267, line: 312, type: !4305, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4305 = !DISubroutineType(types: !4306)
!4306 = !{!62, !4292, !3602, null}
!4307 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4308, file: !4264, line: 111)
!4308 = !DISubprogram(name: "fputc", scope: !4267, file: !4267, line: 517, type: !4309, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4309 = !DISubroutineType(types: !4310)
!4310 = !{!62, !62, !4275}
!4311 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4312, file: !4264, line: 112)
!4312 = !DISubprogram(name: "fputs", scope: !4267, file: !4267, line: 626, type: !4313, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4313 = !DISubroutineType(types: !4314)
!4314 = !{!62, !3602, !4292}
!4315 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4316, file: !4264, line: 113)
!4316 = !DISubprogram(name: "fread", scope: !4267, file: !4267, line: 646, type: !4317, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4317 = !DISubroutineType(types: !4318)
!4318 = !{!143, !3587, !143, !143, !4292}
!4319 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4320, file: !4264, line: 114)
!4320 = !DISubprogram(name: "freopen", scope: !4267, file: !4267, line: 238, type: !4321, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4321 = !DISubroutineType(types: !4322)
!4322 = !{!4275, !3602, !3602, !4292}
!4323 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4324, file: !4264, line: 115)
!4324 = !DISubprogram(name: "fscanf", scope: !4267, file: !4267, line: 377, type: !4305, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4325 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4326, file: !4264, line: 116)
!4326 = !DISubprogram(name: "fseek", scope: !4267, file: !4267, line: 684, type: !4327, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4327 = !DISubroutineType(types: !4328)
!4328 = !{!62, !4275, !455, !62}
!4329 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4330, file: !4264, line: 117)
!4330 = !DISubprogram(name: "fsetpos", scope: !4267, file: !4267, line: 736, type: !4331, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4331 = !DISubroutineType(types: !4332)
!4332 = !{!62, !4275, !4333}
!4333 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4334, size: 64)
!4334 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4266)
!4335 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4336, file: !4264, line: 118)
!4336 = !DISubprogram(name: "ftell", scope: !4267, file: !4267, line: 689, type: !4337, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4337 = !DISubroutineType(types: !4338)
!4338 = !{!455, !4275}
!4339 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4340, file: !4264, line: 119)
!4340 = !DISubprogram(name: "fwrite", scope: !4267, file: !4267, line: 652, type: !4341, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4341 = !DISubroutineType(types: !4342)
!4342 = !{!143, !3588, !143, !143, !4292}
!4343 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4344, file: !4264, line: 120)
!4344 = !DISubprogram(name: "getc", scope: !4267, file: !4267, line: 478, type: !4278, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4345 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4346, file: !4264, line: 121)
!4346 = !DISubprogram(name: "getchar", scope: !4347, file: !4347, line: 44, type: !1099, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4347 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/stdio.h", directory: "", checksumkind: CSK_MD5, checksum: "ae874477a6b090849220f12acdd69dc3")
!4348 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4349, file: !4264, line: 126)
!4349 = !DISubprogram(name: "perror", scope: !4267, file: !4267, line: 775, type: !4350, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4350 = !DISubroutineType(types: !4351)
!4351 = !{null, !639}
!4352 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4353, file: !4264, line: 127)
!4353 = !DISubprogram(name: "printf", scope: !4267, file: !4267, line: 318, type: !4354, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4354 = !DISubroutineType(types: !4355)
!4355 = !{!62, !3602, null}
!4356 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4357, file: !4264, line: 128)
!4357 = !DISubprogram(name: "putc", scope: !4267, file: !4267, line: 518, type: !4309, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4358 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4359, file: !4264, line: 129)
!4359 = !DISubprogram(name: "putchar", scope: !4347, file: !4347, line: 79, type: !3224, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4360 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4361, file: !4264, line: 130)
!4361 = !DISubprogram(name: "puts", scope: !4267, file: !4267, line: 632, type: !3681, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4362 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4363, file: !4264, line: 131)
!4363 = !DISubprogram(name: "remove", scope: !4267, file: !4267, line: 144, type: !3681, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4364 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4365, file: !4264, line: 132)
!4365 = !DISubprogram(name: "rename", scope: !4267, file: !4267, line: 146, type: !3605, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4366 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4367, file: !4264, line: 133)
!4367 = !DISubprogram(name: "rewind", scope: !4267, file: !4267, line: 694, type: !4273, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4368 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4369, file: !4264, line: 134)
!4369 = !DISubprogram(name: "scanf", scope: !4267, file: !4267, line: 383, type: !4354, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4370 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4371, file: !4264, line: 135)
!4371 = !DISubprogram(name: "setbuf", scope: !4267, file: !4267, line: 290, type: !4372, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4372 = !DISubroutineType(types: !4373)
!4373 = !{null, !4292, !3601}
!4374 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4375, file: !4264, line: 136)
!4375 = !DISubprogram(name: "setvbuf", scope: !4267, file: !4267, line: 294, type: !4376, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4376 = !DISubroutineType(types: !4377)
!4377 = !{!62, !4292, !3601, !62, !143}
!4378 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4379, file: !4264, line: 137)
!4379 = !DISubprogram(name: "sprintf", scope: !4267, file: !4267, line: 320, type: !4380, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4380 = !DISubroutineType(types: !4381)
!4381 = !{!62, !3601, !3602, null}
!4382 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4383, file: !4264, line: 138)
!4383 = !DISubprogram(name: "sscanf", scope: !4267, file: !4267, line: 385, type: !4384, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4384 = !DISubroutineType(types: !4385)
!4385 = !{!62, !3602, !3602, null}
!4386 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4387, file: !4264, line: 139)
!4387 = !DISubprogram(name: "tmpfile", scope: !4267, file: !4267, line: 159, type: !4388, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4388 = !DISubroutineType(types: !4389)
!4389 = !{!4275}
!4390 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4391, file: !4264, line: 141)
!4391 = !DISubprogram(name: "tmpnam", scope: !4267, file: !4267, line: 173, type: !4392, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4392 = !DISubroutineType(types: !4393)
!4393 = !{!2236, !2236}
!4394 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4395, file: !4264, line: 143)
!4395 = !DISubprogram(name: "ungetc", scope: !4267, file: !4267, line: 639, type: !4309, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4396 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4397, file: !4264, line: 144)
!4397 = !DISubprogram(name: "vfprintf", scope: !4267, file: !4267, line: 327, type: !4398, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4398 = !DISubroutineType(types: !4399)
!4399 = !{!62, !4292, !3602, !3988}
!4400 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4401, file: !4264, line: 145)
!4401 = !DISubprogram(name: "vprintf", scope: !4347, file: !4347, line: 36, type: !4402, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4402 = !DISubroutineType(types: !4403)
!4403 = !{!62, !3602, !3988}
!4404 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4405, file: !4264, line: 146)
!4405 = !DISubprogram(name: "vsprintf", scope: !4267, file: !4267, line: 335, type: !4406, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4406 = !DISubroutineType(types: !4407)
!4407 = !{!62, !3601, !3602, !3988}
!4408 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4409, file: !4264, line: 175)
!4409 = !DISubprogram(name: "snprintf", scope: !4267, file: !4267, line: 340, type: !4410, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4410 = !DISubroutineType(types: !4411)
!4411 = !{!62, !3601, !143, !3602, null}
!4412 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4413, file: !4264, line: 176)
!4413 = !DISubprogram(name: "vfscanf", scope: !4267, file: !4267, line: 420, type: !4398, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4414 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4415, file: !4264, line: 177)
!4415 = !DISubprogram(name: "vscanf", scope: !4267, file: !4267, line: 428, type: !4402, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4416 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4417, file: !4264, line: 178)
!4417 = !DISubprogram(name: "vsnprintf", scope: !4267, file: !4267, line: 344, type: !4418, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4418 = !DISubroutineType(types: !4419)
!4419 = !{!62, !3601, !143, !3602, !3988}
!4420 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !5, entity: !4421, file: !4264, line: 179)
!4421 = !DISubprogram(name: "vsscanf", scope: !4267, file: !4267, line: 432, type: !4422, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4422 = !DISubroutineType(types: !4423)
!4423 = !{!62, !3602, !3602, !3988}
!4424 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4409, file: !4264, line: 185)
!4425 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4413, file: !4264, line: 186)
!4426 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4415, file: !4264, line: 187)
!4427 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4417, file: !4264, line: 188)
!4428 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4421, file: !4264, line: 189)
!4429 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4430, file: !4434, line: 82)
!4430 = !DIDerivedType(tag: DW_TAG_typedef, name: "wctrans_t", file: !4431, line: 48, baseType: !4432)
!4431 = !DIFile(filename: "/usr/include/wctype.h", directory: "", checksumkind: CSK_MD5, checksum: "760693b7fbeea3d686e1f29058fc2257")
!4432 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4433, size: 64)
!4433 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4159)
!4434 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/cwctype", directory: "")
!4435 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4436, file: !4434, line: 83)
!4436 = !DIDerivedType(tag: DW_TAG_typedef, name: "wctype_t", file: !4437, line: 38, baseType: !145)
!4437 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/wctype-wchar.h", directory: "", checksumkind: CSK_MD5, checksum: "45eef9c3aa1d99faffa3945ed9be039a")
!4438 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3856, file: !4434, line: 84)
!4439 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4440, file: !4434, line: 86)
!4440 = !DISubprogram(name: "iswalnum", scope: !4437, file: !4437, line: 95, type: !4090, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4441 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4442, file: !4434, line: 87)
!4442 = !DISubprogram(name: "iswalpha", scope: !4437, file: !4437, line: 101, type: !4090, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4443 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4444, file: !4434, line: 89)
!4444 = !DISubprogram(name: "iswblank", scope: !4437, file: !4437, line: 146, type: !4090, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4445 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4446, file: !4434, line: 91)
!4446 = !DISubprogram(name: "iswcntrl", scope: !4437, file: !4437, line: 104, type: !4090, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4447 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4448, file: !4434, line: 92)
!4448 = !DISubprogram(name: "iswctype", scope: !4437, file: !4437, line: 159, type: !4449, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4449 = !DISubroutineType(types: !4450)
!4450 = !{!62, !3856, !4436}
!4451 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4452, file: !4434, line: 93)
!4452 = !DISubprogram(name: "iswdigit", scope: !4437, file: !4437, line: 108, type: !4090, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4453 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4454, file: !4434, line: 94)
!4454 = !DISubprogram(name: "iswgraph", scope: !4437, file: !4437, line: 112, type: !4090, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4455 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4456, file: !4434, line: 95)
!4456 = !DISubprogram(name: "iswlower", scope: !4437, file: !4437, line: 117, type: !4090, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4457 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4458, file: !4434, line: 96)
!4458 = !DISubprogram(name: "iswprint", scope: !4437, file: !4437, line: 120, type: !4090, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4459 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4460, file: !4434, line: 97)
!4460 = !DISubprogram(name: "iswpunct", scope: !4437, file: !4437, line: 125, type: !4090, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4461 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4462, file: !4434, line: 98)
!4462 = !DISubprogram(name: "iswspace", scope: !4437, file: !4437, line: 130, type: !4090, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4463 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4464, file: !4434, line: 99)
!4464 = !DISubprogram(name: "iswupper", scope: !4437, file: !4437, line: 135, type: !4090, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4465 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4466, file: !4434, line: 100)
!4466 = !DISubprogram(name: "iswxdigit", scope: !4437, file: !4437, line: 140, type: !4090, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4467 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4468, file: !4434, line: 101)
!4468 = !DISubprogram(name: "towctrans", scope: !4431, file: !4431, line: 55, type: !4469, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4469 = !DISubroutineType(types: !4470)
!4470 = !{!3856, !3856, !4430}
!4471 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4472, file: !4434, line: 102)
!4472 = !DISubprogram(name: "towlower", scope: !4437, file: !4437, line: 166, type: !4473, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4473 = !DISubroutineType(types: !4474)
!4474 = !{!3856, !3856}
!4475 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4476, file: !4434, line: 103)
!4476 = !DISubprogram(name: "towupper", scope: !4437, file: !4437, line: 169, type: !4473, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4477 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4478, file: !4434, line: 104)
!4478 = !DISubprogram(name: "wctrans", scope: !4431, file: !4431, line: 52, type: !4479, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4479 = !DISubroutineType(types: !4480)
!4480 = !{!4430, !639}
!4481 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4482, file: !4434, line: 105)
!4482 = !DISubprogram(name: "wctype", scope: !4437, file: !4437, line: 155, type: !4483, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4483 = !DISubroutineType(types: !4484)
!4484 = !{!4436, !639}
!4485 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !3, file: !4486, line: 86)
!4486 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr_base.h", directory: "", checksumkind: CSK_MD5, checksum: "8405222f7806be9ab20595b5fcc527fd")
!4487 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4488, file: !4486, line: 87)
!4488 = !DIGlobalVariable(name: "__default_lock_policy", linkageName: "_ZN9__gnu_cxxL21__default_lock_policyE", scope: !5, file: !4, line: 53, type: !4489, isLocal: true, isDefinition: false)
!4489 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !3)
!4490 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4491, file: !4494, line: 60)
!4491 = !DIDerivedType(tag: DW_TAG_typedef, name: "clock_t", file: !4492, line: 7, baseType: !4493)
!4492 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/clock_t.h", directory: "", checksumkind: CSK_MD5, checksum: "1aade99fd778d1551600c7ca1410b9f1")
!4493 = !DIDerivedType(tag: DW_TAG_typedef, name: "__clock_t", file: !3894, line: 144, baseType: !455)
!4494 = !DIFile(filename: "/usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ctime", directory: "")
!4495 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4496, file: !4494, line: 61)
!4496 = !DIDerivedType(tag: DW_TAG_typedef, name: "time_t", file: !4497, line: 7, baseType: !4498)
!4497 = !DIFile(filename: "/usr/include/x86_64-linux-gnu/bits/types/time_t.h", directory: "", checksumkind: CSK_MD5, checksum: "49b4e16ef1215de5afdbb283400ab90c")
!4498 = !DIDerivedType(tag: DW_TAG_typedef, name: "__time_t", file: !3894, line: 148, baseType: !455)
!4499 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4039, file: !4494, line: 62)
!4500 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4501, file: !4494, line: 64)
!4501 = !DISubprogram(name: "clock", scope: !4502, file: !4502, line: 72, type: !4503, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4502 = !DIFile(filename: "/usr/include/time.h", directory: "", checksumkind: CSK_MD5, checksum: "3b21b4c7d8bf3fafdb33a1c7ed8e024a")
!4503 = !DISubroutineType(types: !4504)
!4504 = !{!4491}
!4505 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4506, file: !4494, line: 65)
!4506 = !DISubprogram(name: "difftime", scope: !4502, file: !4502, line: 78, type: !4507, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4507 = !DISubroutineType(types: !4508)
!4508 = !{!3232, !4496, !4496}
!4509 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4510, file: !4494, line: 66)
!4510 = !DISubprogram(name: "mktime", scope: !4502, file: !4502, line: 82, type: !4511, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4511 = !DISubroutineType(types: !4512)
!4512 = !{!4496, !4513}
!4513 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4039, size: 64)
!4514 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4515, file: !4494, line: 67)
!4515 = !DISubprogram(name: "time", scope: !4502, file: !4502, line: 75, type: !4516, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4516 = !DISubroutineType(types: !4517)
!4517 = !{!4496, !4518}
!4518 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4496, size: 64)
!4519 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4520, file: !4494, line: 68)
!4520 = !DISubprogram(name: "asctime", scope: !4502, file: !4502, line: 139, type: !4521, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4521 = !DISubroutineType(types: !4522)
!4522 = !{!2236, !4037}
!4523 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4524, file: !4494, line: 69)
!4524 = !DISubprogram(name: "ctime", scope: !4502, file: !4502, line: 142, type: !4525, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4525 = !DISubroutineType(types: !4526)
!4526 = !{!2236, !4527}
!4527 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !4528, size: 64)
!4528 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !4496)
!4529 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4530, file: !4494, line: 70)
!4530 = !DISubprogram(name: "gmtime", scope: !4502, file: !4502, line: 119, type: !4531, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4531 = !DISubroutineType(types: !4532)
!4532 = !{!4513, !4527}
!4533 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4534, file: !4494, line: 71)
!4534 = !DISubprogram(name: "localtime", scope: !4502, file: !4502, line: 123, type: !4531, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4535 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !91, entity: !4536, file: !4494, line: 72)
!4536 = !DISubprogram(name: "strftime", scope: !4502, file: !4502, line: 88, type: !4537, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!4537 = !DISubroutineType(types: !4538)
!4538 = !{!143, !3601, !143, !3602, !4036}
!4539 = !DIImportedEntity(tag: DW_TAG_imported_module, scope: !0, entity: !14, file: !2238, line: 20)
!4540 = !{i32 7, !"Dwarf Version", i32 5}
!4541 = !{i32 2, !"Debug Info Version", i32 3}
!4542 = !{i32 1, !"wchar_size", i32 4}
!4543 = !{i32 7, !"PIC Level", i32 2}
!4544 = !{i32 7, !"uwtable", i32 2}
!4545 = distinct !DISubprogram(name: "MacroDefined", linkageName: "_ZN5clang19PreprocessingRecord12MacroDefinedERKNS_5TokenEPKNS_14MacroDirectiveE", scope: !147, file: !2238, line: 415, type: !1514, scopeLine: 416, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !1513, retainedNodes: !4546)
!4546 = !{!4547, !4548, !4549, !4550, !4551, !4552}
!4547 = !DILocalVariable(name: "this", arg: 1, scope: !4545, type: !1392, flags: DIFlagArtificial | DIFlagObjectPointer)
!4548 = !DILocalVariable(name: "Id", arg: 2, scope: !4545, file: !2238, line: 415, type: !1503)
!4549 = !DILocalVariable(name: "MD", arg: 3, scope: !4545, file: !2238, line: 416, type: !1507)
!4550 = !DILocalVariable(name: "MI", scope: !4545, file: !2238, line: 417, type: !734)
!4551 = !DILocalVariable(name: "R", scope: !4545, file: !2238, line: 418, type: !32)
!4552 = !DILocalVariable(name: "Def", scope: !4545, file: !2238, line: 419, type: !739)
!4553 = !DILocalVariable(name: "Range", arg: 3, scope: !4554, file: !12, line: 142, type: !32)
!4554 = distinct !DISubprogram(name: "MacroDefinition", linkageName: "_ZN5clang15MacroDefinitionC2EPKNS_14IdentifierInfoENS_11SourceRangeE", scope: !740, file: !12, line: 142, type: !749, scopeLine: 143, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !748, retainedNodes: !4555)
!4555 = !{!4556, !4557, !4553}
!4556 = !DILocalVariable(name: "this", arg: 1, scope: !4554, type: !739, flags: DIFlagArtificial | DIFlagObjectPointer)
!4557 = !DILocalVariable(name: "Name", arg: 2, scope: !4554, file: !12, line: 142, type: !744)
!4558 = !DILocation(line: 0, scope: !4554, inlinedAt: !4559)
!4559 = distinct !DILocation(line: 420, column: 21, scope: !4545)
!4560 = !DILocation(line: 143, column: 9, scope: !4554, inlinedAt: !4559)
