; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc %s --stop-after=finalize-isel -o - | FileCheck %s
; TODO: simply
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%class.Interval.108 = type { %class.Domain.109 }
%class.Domain.109 = type { %class.DomainBase.110 }
%class.DomainBase.110 = type { [3 x %struct.WrapNoInit.111] }
%struct.WrapNoInit.111 = type { %class.Interval }
%class.Interval = type { %class.Domain.106 }
%class.Domain.106 = type { %class.DomainBase.107 }
%class.DomainBase.107 = type { [2 x i32] }

define void @_ZNK15BisectionMapperILi3EE3mapERKSt6vectorIP4NodeI8IntervalILi3EES4_ESaIS6_EE(i1 %cmp57.2) !dbg !4 {
  ; CHECK-LABEL: name: _ZNK15BisectionMapperILi3EE3mapERKSt6vectorIP4NodeI8IntervalILi3EES4_ESaIS6_EE
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr32 = COPY $edi
  ; CHECK-NEXT:   [[AND32ri:%[0-9]+]]:gr32 = AND32ri [[COPY]], 1, implicit-def dead $eflags
  ; CHECK-NEXT:   [[SHL32ri:%[0-9]+]]:gr32 = SHL32ri [[AND32ri]], 4, implicit-def dead $eflags, debug-instr-number 1
  ; CHECK-NEXT:   [[SUBREG_TO_REG:%[0-9]+]]:gr64_nosp = SUBREG_TO_REG killed [[SHL32ri]], %subreg.sub_32bit
  ; CHECK-NEXT:   DBG_INSTR_REF !10, !DIExpression(DW_OP_LLVM_arg, 0, DW_OP_LLVM_arg, 1, DW_OP_plus, DW_OP_stack_value), %stack.0.hi, dbg-instr-ref(2, 0), debug-location !17
  ; CHECK-NEXT:   [[MOV32rm:%[0-9]+]]:gr32 = MOV32rm %stack.0.hi, 1, killed [[SUBREG_TO_REG]], 0, $noreg, debug-location !20 :: (load (s32) from %ir.arrayidx.i367, align 8)
  ; CHECK-NEXT:   MOV32mr $noreg, 1, $noreg, 0, $noreg, killed [[MOV32rm]] :: (store (s32) into `ptr null`, align 8)
  ; CHECK-NEXT:   RET 0
entry:
  %hi = alloca %class.Interval.108, align 16
  %spec.select456.2 = select i1 %cmp57.2, i64 2, i64 0
  %arrayidx.i367 = getelementptr [8 x i8], ptr %hi, i64 %spec.select456.2
    #dbg_value(ptr %arrayidx.i367, !10, !DIExpression(), !17)
  %0 = load i32, ptr %arrayidx.i367, align 8, !dbg !20
  store i32 %0, ptr null, align 8
  ret void
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 23.0.0git (https://github.com/OCHyams/llvm-project 7e489b3ebf9c337c8b6ea74bef9c4f45f2dc4fd9)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "x.cpp", directory: "/home/och/reduce", checksumkind: CSK_MD5, checksum: "a79402ede23ff238de3e4647c4f3a326")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = distinct !DISubprogram(name: "map", linkageName: "_ZNK15BisectionMapperILi3EE3mapERKSt6vectorIP4NodeI8IntervalILi3EES4_ESaIS6_EE", scope: !5, file: !1, line: 10050, type: !7, scopeLine: 10051, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !9, retainedNodes: !2, keyInstructions: true)
!5 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "BisectionMapper<3>", file: !1, line: 10024, size: 192, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, vtableHolder: !6, templateParams: !2, identifier: "_ZTS15BisectionMapperILi3EE")
!6 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "ContextMapper<3>", file: !1, line: 8030, size: 64, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, vtableHolder: !6, templateParams: !2, identifier: "_ZTS13ContextMapperILi3EE")
!7 = distinct !DISubroutineType(types: !8)
!8 = !{null}
!9 = !DISubprogram(name: "map", linkageName: "_ZNK15BisectionMapperILi3EE3mapERKSt6vectorIP4NodeI8IntervalILi3EES4_ESaIS6_EE", scope: !5, file: !1, line: 10050, type: !7, scopeLine: 10050, containingType: !5, virtualIndex: 2, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagVirtual | DISPFlagOptimized)
!10 = !DILocalVariable(name: "this", arg: 1, scope: !11, type: !15, flags: DIFlagArtificial | DIFlagObjectPointer)
!11 = distinct !DISubprogram(name: "first", linkageName: "_ZNK6DomainILi1E12DomainTraitsI8IntervalILi1EEEE5firstEv", scope: !12, file: !1, line: 3460, type: !13, scopeLine: 3460, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !14, retainedNodes: !2, keyInstructions: true)
!12 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Domain<1, DomainTraits<Interval<1> > >", file: !1, line: 3435, size: 64, flags: DIFlagTypePassByReference | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTS6DomainILi1E12DomainTraitsI8IntervalILi1EEEE")
!13 = distinct !DISubroutineType(types: !2)
!14 = !DISubprogram(name: "first", linkageName: "_ZNK6DomainILi1E12DomainTraitsI8IntervalILi1EEEE5firstEv", scope: !12, file: !1, line: 3460, type: !13, scopeLine: 3460, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagOptimized)
!15 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !16, size: 64)
!16 = !DIDerivedType(tag: DW_TAG_const_type, baseType: !12)
!17 = !DILocation(line: 0, scope: !11, inlinedAt: !18)
!18 = distinct !DILocation(line: 10086, column: 27, scope: !19)
!19 = distinct !DILexicalBlock(scope: !4, file: !1, line: 10062, column: 5)
!20 = !DILocation(line: 3624, column: 55, scope: !21, inlinedAt: !25, atomGroup: 1, atomRank: 2)
!21 = distinct !DISubprogram(name: "first", linkageName: "_ZN12DomainTraitsI8IntervalILi1EEE5firstERA2_Ki", scope: !22, file: !1, line: 3624, type: !23, scopeLine: 3624, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, declaration: !24, retainedNodes: !2, keyInstructions: true)
!22 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "DomainTraits<Interval<1> >", file: !1, line: 3607, size: 8, flags: DIFlagTypePassByValue, elements: !2, templateParams: !2, identifier: "_ZTS12DomainTraitsI8IntervalILi1EEE")
!23 = distinct !DISubroutineType(types: !2)
!24 = !DISubprogram(name: "first", linkageName: "_ZN12DomainTraitsI8IntervalILi1EEE5firstERA2_Ki", scope: !22, file: !1, line: 3624, type: !23, scopeLine: 3624, flags: DIFlagPrototyped | DIFlagStaticMember, spFlags: DISPFlagOptimized)
!25 = distinct !DILocation(line: 3460, column: 36, scope: !11, inlinedAt: !18)
